GDB (xrefs): /home/stan/gdb/src/gdb/aarch64-linux-tdep.h File Reference
/home/stan/gdb/src/gdb/aarch64-linux-tdep.h File Reference
Functions
void aarch64_linux_supply_gregset (struct regcache *regcache, const gdb_byte *gregs_buf)
void aarch64_linux_supply_fpregset (struct regcache *regcache, const gdb_byte *fpregs_buf)
Function Documentation
void aarch64_linux_supply_fpregset (struct regcache * regcache, const gdb_byte * fpregs_buf)
Definition at line 211 of file aarch64-linux-tdep.c.
References AARCH64_FPCR_REGNUM, AARCH64_FPSR_REGNUM, AARCH64_V0_REGNUM, AARCH64_V31_REGNUM, regcache_raw_supply(), and V_REGISTER_SIZE.
Referenced by supply_fpregset(), and supply_fpregset_from_core().
void aarch64_linux_supply_gregset (struct regcache * regcache, const gdb_byte * gregs_buf)
Definition at line 186 of file aarch64-linux-tdep.c.
References AARCH64_CPSR_REGNUM, AARCH64_X0_REGNUM, regcache_raw_supply(), and X_REGISTER_SIZE.
Referenced by supply_gregset(), and supply_gregset_from_core().