GDB (xrefs): /home/stan/gdb/src/gdb/aarch64-linux-nat.c File Reference
/home/stan/gdb/src/gdb/aarch64-linux-nat.c File Reference
#include "defs.h"
#include "inferior.h"
#include "gdbcore.h"
#include "regcache.h"
#include "linux-nat.h"
#include "target-descriptions.h"
#include "auxv.h"
#include "gdbcmd.h"
#include "aarch64-tdep.h"
#include "aarch64-linux-tdep.h"
#include "elf/common.h"
#include <sys/ptrace.h>
#include <sys/utsname.h>
#include "gregset.h"
#include "features/aarch64.c"
#include "gdb_proc_service.h"
Classes
struct aarch64_debug_reg_state
struct aarch64_process_info
struct arch_lwp_info
struct aarch64_dr_update_callback_param
Defines
#define TRAP_HWBKPT 0x0004
#define AARCH64_HBP_MAX_NUM 16
#define AARCH64_HWP_MAX_NUM 16
#define AARCH64_HBP_ALIGNMENT 4
#define AARCH64_HWP_ALIGNMENT 8
#define AARCH64_HWP_MAX_LEN_PER_REG 8
#define AARCH64_DEBUG_NUM_SLOTS(x) ((x) & 0xff)
#define AARCH64_DEBUG_ARCH(x) (((x) >> 8) & 0xff)
#define AARCH64_DEBUG_ARCH_V8 0x6
#define DR_MARK_ALL_CHANGED(x, m)
#define DR_MARK_N_CHANGED(x, n)
#define DR_CLEAR_CHANGED(x)
#define DR_HAS_CHANGED(x) ((x) != 0)
#define DR_N_HAS_CHANGED(x, n) ((x) & ((dr_changed_t)1 << (n)))
#define DR_CONTROL_ENABLED(ctrl) (((ctrl) & 0x1) == 1)
#define DR_CONTROL_LENGTH(ctrl) (((ctrl) >> 5) & 0xff)
Typedefs
typedef unsigned LONGEST dr_changed_t
Functions
static int get_thread_id (ptid_t ptid)
static struct
aarch64_process_info * aarch64_find_process_pid (pid_t pid)
static struct
aarch64_process_info * aarch64_add_process (pid_t pid)
static struct
aarch64_process_info * aarch64_process_info_get (pid_t pid)
static void aarch64_forget_process (pid_t pid)
static struct
aarch64_debug_reg_state * aarch64_get_debug_reg_state (pid_t pid)
static void aarch64_linux_set_debug_regs (const struct aarch64_debug_reg_state *state, int tid, int watchpoint)
static int debug_reg_change_callback (struct lwp_info *lwp, void *ptr)
static void aarch64_notify_debug_reg_change (const struct aarch64_debug_reg_state *state, int is_watchpoint, unsigned int idx)
static void aarch64_show_debug_reg_state (struct aarch64_debug_reg_state *state, const char *func, CORE_ADDR addr, int len, int type)
static void fetch_gregs_from_thread (struct regcache *regcache)
static void store_gregs_to_thread (const struct regcache *regcache)
static void fetch_fpregs_from_thread (struct regcache *regcache)
static void store_fpregs_to_thread (const struct regcache *regcache)
static void aarch64_linux_fetch_inferior_registers (struct target_ops *ops, struct regcache *regcache, int regno)
static void aarch64_linux_store_inferior_registers (struct target_ops *ops, struct regcache *regcache, int regno)
void fill_gregset (const struct regcache *regcache, gdb_gregset_t *gregsetp, int regno)
void supply_gregset (struct regcache *regcache, const gdb_gregset_t *gregsetp)
void fill_fpregset (const struct regcache *regcache, gdb_fpregset_t *fpregsetp, int regno)
void supply_fpregset (struct regcache *regcache, const gdb_fpregset_t *fpregsetp)
static void aarch64_linux_prepare_to_resume (struct lwp_info *lwp)
static void aarch64_linux_new_thread (struct lwp_info *lp)
static void aarch64_linux_new_fork (struct lwp_info *parent, pid_t child_pid)
ps_err_e ps_get_thread_area (const struct ps_prochandle *ph, lwpid_t lwpid, int idx, void **base)
static void aarch64_linux_get_debug_reg_capacity (void)
static void aarch64_linux_child_post_startup_inferior (ptid_t ptid)
static struct target_desc * aarch64_linux_read_description (struct target_ops *ops)
static void aarch64_align_watchpoint (CORE_ADDR addr, int len, CORE_ADDR *aligned_addr_p, int *aligned_len_p, CORE_ADDR *next_addr_p, int *next_len_p)
static int aarch64_linux_can_use_hw_breakpoint (int type, int cnt, int othertype)
static unsigned int aarch64_watchpoint_length (unsigned int ctrl)
static unsigned int aarch64_point_encode_ctrl_reg (int type, int len)
static int aarch64_point_is_aligned (int is_watchpoint, CORE_ADDR addr, int len)
static int aarch64_dr_state_insert_one_point (struct aarch64_debug_reg_state *state, int type, CORE_ADDR addr, int len)
static int aarch64_dr_state_remove_one_point (struct aarch64_debug_reg_state *state, int type, CORE_ADDR addr, int len)
static int aarch64_handle_breakpoint (int type, CORE_ADDR addr, int len, int is_insert)
static int aarch64_linux_insert_hw_breakpoint (struct gdbarch *gdbarch, struct bp_target_info *bp_tgt)
static int aarch64_linux_remove_hw_breakpoint (struct gdbarch *gdbarch, struct bp_target_info *bp_tgt)
static int aarch64_handle_aligned_watchpoint (int type, CORE_ADDR addr, int len, int is_insert)
static int aarch64_handle_unaligned_watchpoint (int type, CORE_ADDR addr, int len, int is_insert)
static int aarch64_handle_watchpoint (int type, CORE_ADDR addr, int len, int is_insert)
static int aarch64_linux_insert_watchpoint (CORE_ADDR addr, int len, int type, struct expression *cond)
static int aarch64_linux_remove_watchpoint (CORE_ADDR addr, int len, int type, struct expression *cond)
static int aarch64_linux_region_ok_for_hw_watchpoint (CORE_ADDR addr, int len)
static int aarch64_linux_stopped_data_address (struct target_ops *target, CORE_ADDR *addr_p)
static int aarch64_linux_stopped_by_watchpoint (void)
static int aarch64_linux_watchpoint_addr_within_range (struct target_ops *target, CORE_ADDR addr, CORE_ADDR start, int length)
static void add_show_debug_regs_command (void)
void _initialize_aarch64_linux_nat (void)
Variables
static int aarch64_num_bp_regs
static int aarch64_num_wp_regs
static int debug_hw_points
static struct
aarch64_process_info * aarch64_process_list = NULL
static void(* super_post_startup_inferior)(ptid_t ptid)
Define Documentation
#define AARCH64_DEBUG_ARCH (x) (((x) >> 8) & 0xff)
Definition at line 109 of file aarch64-linux-nat.c.
Referenced by aarch64_linux_get_debug_reg_capacity().
#define AARCH64_DEBUG_ARCH_V8 0x6
Definition at line 112 of file aarch64-linux-nat.c.
Referenced by aarch64_linux_get_debug_reg_capacity().
#define AARCH64_DEBUG_NUM_SLOTS (x) ((x) & 0xff)
Definition at line 108 of file aarch64-linux-nat.c.
Referenced by aarch64_linux_get_debug_reg_capacity().
#define AARCH64_HBP_ALIGNMENT 4
Definition at line 91 of file aarch64-linux-nat.c.
Referenced by aarch64_point_is_aligned().
#define AARCH64_HBP_MAX_NUM 16
Definition at line 76 of file aarch64-linux-nat.c.
Referenced by aarch64_linux_get_debug_reg_capacity().
#define AARCH64_HWP_ALIGNMENT 8
Definition at line 92 of file aarch64-linux-nat.c.
Referenced by aarch64_align_watchpoint(), and aarch64_point_is_aligned().
#define AARCH64_HWP_MAX_LEN_PER_REG 8
Definition at line 97 of file aarch64-linux-nat.c.
Referenced by aarch64_align_watchpoint(), and aarch64_linux_region_ok_for_hw_watchpoint().
#define AARCH64_HWP_MAX_NUM 16
Definition at line 77 of file aarch64-linux-nat.c.
Referenced by aarch64_linux_get_debug_reg_capacity().
#define DR_CLEAR_CHANGED (x)
Value:
do                                                                      \
    {                                                                   \
      (x) = 0;                                                          \
    } while (0)
Definition at line 163 of file aarch64-linux-nat.c.
Referenced by aarch64_linux_prepare_to_resume().
#define DR_CONTROL_ENABLED (ctrl) (((ctrl) & 0x1) == 1)
Definition at line 955 of file aarch64-linux-nat.c.
Referenced by aarch64_linux_stopped_data_address().
#define DR_CONTROL_LENGTH (ctrl) (((ctrl) >> 5) & 0xff)
Definition at line 956 of file aarch64-linux-nat.c.
Referenced by aarch64_watchpoint_length().
#define DR_HAS_CHANGED (x) ((x) != 0)
Definition at line 169 of file aarch64-linux-nat.c.
Referenced by aarch64_linux_prepare_to_resume().
#define DR_MARK_ALL_CHANGED (x, m)
Value:
do                                                                      \
    {                                                                   \
      gdb_assert (sizeof ((x)) * 8 >= (m));                             \
      (x) = (((dr_changed_t)1 << (m)) - 1);                             \
    } while (0)
Definition at line 150 of file aarch64-linux-nat.c.
Referenced by aarch64_linux_new_thread().
#define DR_MARK_N_CHANGED (x, n)
Value:
do                                                                      \
    {                                                                   \
      (x) |= ((dr_changed_t)1 << (n));                                  \
    } while (0)
Definition at line 157 of file aarch64-linux-nat.c.
Referenced by debug_reg_change_callback().
#define DR_N_HAS_CHANGED (x, n) ((x) & ((dr_changed_t)1 << (n)))
Definition at line 170 of file aarch64-linux-nat.c.
#define TRAP_HWBKPT 0x0004
Definition at line 45 of file aarch64-linux-nat.c.
Referenced by aarch64_linux_stopped_data_address().
Typedef Documentation
typedef unsigned LONGEST dr_changed_t
Definition at line 146 of file aarch64-linux-nat.c.
Function Documentation
void _initialize_aarch64_linux_nat (void)
Definition at line 1518 of file aarch64-linux-nat.c.
References aarch64_forget_process(), aarch64_linux_can_use_hw_breakpoint(), aarch64_linux_child_post_startup_inferior(), aarch64_linux_fetch_inferior_registers(), aarch64_linux_insert_hw_breakpoint(), aarch64_linux_insert_watchpoint(), aarch64_linux_new_fork(), aarch64_linux_new_thread(), aarch64_linux_prepare_to_resume(), aarch64_linux_read_description(), aarch64_linux_region_ok_for_hw_watchpoint(), aarch64_linux_remove_hw_breakpoint(), aarch64_linux_remove_watchpoint(), aarch64_linux_stopped_by_watchpoint(), aarch64_linux_stopped_data_address(), aarch64_linux_store_inferior_registers(), aarch64_linux_watchpoint_addr_within_range(), add_show_debug_regs_command(), linux_nat_add_target(), linux_nat_set_forget_process(), linux_nat_set_new_fork(), linux_nat_set_new_thread(), linux_nat_set_prepare_to_resume(), linux_target(), super_post_startup_inferior, target_ops::to_can_use_hw_breakpoint, target_ops::to_fetch_registers, target_ops::to_insert_hw_breakpoint, target_ops::to_insert_watchpoint, target_ops::to_post_startup_inferior, target_ops::to_read_description, target_ops::to_region_ok_for_hw_watchpoint, target_ops::to_remove_hw_breakpoint, target_ops::to_remove_watchpoint, target_ops::to_stopped_by_watchpoint, target_ops::to_stopped_data_address, target_ops::to_store_registers, and target_ops::to_watchpoint_addr_within_range.
static struct aarch64_process_info* aarch64_add_process (pid_t pid) [static, read]
Definition at line 229 of file aarch64-linux-nat.c.
References aarch64_process_list, aarch64_process_info::next, aarch64_process_info::pid, and xcalloc().
Referenced by aarch64_process_info_get().
static void aarch64_align_watchpoint (CORE_ADDR addr, int len, CORE_ADDR * aligned_addr_p, int * aligned_len_p, CORE_ADDR * next_addr_p, int * next_len_p) [static]
Definition at line 866 of file aarch64-linux-nat.c.
References AARCH64_HWP_ALIGNMENT, AARCH64_HWP_MAX_LEN_PER_REG, gdb_assert, len, and offset.
Referenced by aarch64_handle_unaligned_watchpoint().
static int aarch64_dr_state_insert_one_point (struct aarch64_debug_reg_state * state, int type, CORE_ADDR addr, int len) [static]
Definition at line 1052 of file aarch64-linux-nat.c.
References aarch64_notify_debug_reg_change(), aarch64_num_bp_regs, aarch64_num_wp_regs, aarch64_point_encode_ctrl_reg(), aarch64_point_is_aligned(), aarch64_debug_reg_state::dr_addr_bp, aarch64_debug_reg_state::dr_addr_wp, aarch64_debug_reg_state::dr_ctrl_bp, aarch64_debug_reg_state::dr_ctrl_wp, dr_ref_count, aarch64_debug_reg_state::dr_ref_count_bp, aarch64_debug_reg_state::dr_ref_count_wp, gdb_assert, hw_execute, and is_watchpoint().
Referenced by aarch64_handle_aligned_watchpoint(), aarch64_handle_breakpoint(), and aarch64_handle_unaligned_watchpoint().
static int aarch64_dr_state_remove_one_point (struct aarch64_debug_reg_state * state, int type, CORE_ADDR addr, int len) [static]
Definition at line 1124 of file aarch64-linux-nat.c.
References aarch64_notify_debug_reg_change(), aarch64_num_bp_regs, aarch64_num_wp_regs, aarch64_point_encode_ctrl_reg(), aarch64_point_is_aligned(), aarch64_debug_reg_state::dr_addr_bp, aarch64_debug_reg_state::dr_addr_wp, aarch64_debug_reg_state::dr_ctrl_bp, aarch64_debug_reg_state::dr_ctrl_wp, dr_ref_count, aarch64_debug_reg_state::dr_ref_count_bp, aarch64_debug_reg_state::dr_ref_count_wp, gdb_assert, hw_execute, and is_watchpoint().
Referenced by aarch64_handle_aligned_watchpoint(), aarch64_handle_breakpoint(), and aarch64_handle_unaligned_watchpoint().
static struct aarch64_process_info* aarch64_find_process_pid (pid_t pid) [static, read]
Definition at line 214 of file aarch64-linux-nat.c.
References aarch64_process_info::next, and aarch64_process_info::pid.
Referenced by aarch64_process_info_get().
static void aarch64_forget_process (pid_t pid) [static]
Definition at line 261 of file aarch64-linux-nat.c.
References aarch64_process_list, aarch64_process_info::next, aarch64_process_info::pid, and xfree().
Referenced by _initialize_aarch64_linux_nat(), and aarch64_linux_child_post_startup_inferior().
static struct aarch64_debug_reg_state* aarch64_get_debug_reg_state (pid_t pid) [static, read]
Definition at line 286 of file aarch64-linux-nat.c.
References aarch64_process_info_get(), and aarch64_process_info::state.
Referenced by aarch64_handle_aligned_watchpoint(), aarch64_handle_breakpoint(), aarch64_handle_unaligned_watchpoint(), aarch64_linux_insert_hw_breakpoint(), aarch64_linux_insert_watchpoint(), aarch64_linux_new_fork(), aarch64_linux_prepare_to_resume(), aarch64_linux_remove_hw_breakpoint(), aarch64_linux_remove_watchpoint(), and aarch64_linux_stopped_data_address().
static int aarch64_handle_aligned_watchpoint (int type, CORE_ADDR addr, int len, int is_insert) [static]
Definition at line 1264 of file aarch64-linux-nat.c.
References aarch64_dr_state_insert_one_point(), aarch64_dr_state_remove_one_point(), aarch64_get_debug_reg_state(), inferior_ptid, and ptid_get_pid().
Referenced by aarch64_handle_watchpoint().
static int aarch64_handle_breakpoint (int type, CORE_ADDR addr, int len, int is_insert) [static]
Definition at line 1180 of file aarch64-linux-nat.c.
References aarch64_dr_state_insert_one_point(), aarch64_dr_state_remove_one_point(), aarch64_get_debug_reg_state(), aarch64_point_is_aligned(), inferior_ptid, and ptid_get_pid().
Referenced by aarch64_linux_insert_hw_breakpoint(), and aarch64_linux_remove_hw_breakpoint().
static int aarch64_handle_unaligned_watchpoint (int type, CORE_ADDR addr, int len, int is_insert) [static]
Definition at line 1284 of file aarch64-linux-nat.c.
References aarch64_align_watchpoint(), aarch64_dr_state_insert_one_point(), aarch64_dr_state_remove_one_point(), aarch64_get_debug_reg_state(), debug_hw_points, fprintf_unfiltered(), gdb_stdlog, inferior_ptid, and ptid_get_pid().
Referenced by aarch64_handle_watchpoint().
static int aarch64_handle_watchpoint (int type, CORE_ADDR addr, int len, int is_insert) [static]
Definition at line 1322 of file aarch64-linux-nat.c.
References aarch64_handle_aligned_watchpoint(), aarch64_handle_unaligned_watchpoint(), and aarch64_point_is_aligned().
Referenced by aarch64_linux_insert_watchpoint(), and aarch64_linux_remove_watchpoint().
static int aarch64_linux_can_use_hw_breakpoint (int type, int cnt, int othertype) [static]
Definition at line 941 of file aarch64-linux-nat.c.
Referenced by _initialize_aarch64_linux_nat().
static void aarch64_linux_child_post_startup_inferior (ptid_t ptid) [static]
Definition at line 833 of file aarch64-linux-nat.c.
References aarch64_forget_process(), aarch64_linux_get_debug_reg_capacity(), ptid_get_pid(), and super_post_startup_inferior.
Referenced by _initialize_aarch64_linux_nat().
static void aarch64_linux_fetch_inferior_registers (struct target_ops * ops, struct regcache * regcache, int regno) [static]
Definition at line 574 of file aarch64-linux-nat.c.
References AARCH64_V0_REGNUM, fetch_fpregs_from_thread(), and fetch_gregs_from_thread().
Referenced by _initialize_aarch64_linux_nat().
static void aarch64_linux_get_debug_reg_capacity (void) [static]
Definition at line 777 of file aarch64-linux-nat.c.
References _, AARCH64_DEBUG_ARCH, AARCH64_DEBUG_ARCH_V8, AARCH64_DEBUG_NUM_SLOTS, AARCH64_HBP_MAX_NUM, AARCH64_HWP_MAX_NUM, aarch64_num_bp_regs, aarch64_num_wp_regs, get_thread_id(), inferior_ptid, ptrace(), PTRACE_GETREGSET, and warning().
Referenced by aarch64_linux_child_post_startup_inferior().
static int aarch64_linux_insert_hw_breakpoint (struct gdbarch * gdbarch, struct bp_target_info * bp_tgt) [static]
Definition at line 1201 of file aarch64-linux-nat.c.
References aarch64_get_debug_reg_state(), aarch64_handle_breakpoint(), aarch64_show_debug_reg_state(), debug_hw_points, fprintf_unfiltered(), gdb_stdlog, hw_execute, inferior_ptid, len, bp_target_info::placed_address, and ptid_get_pid().
Referenced by _initialize_aarch64_linux_nat().
static int aarch64_linux_insert_watchpoint (CORE_ADDR addr, int len, int type, struct expression * cond) [static]
Definition at line 1337 of file aarch64-linux-nat.c.
References aarch64_get_debug_reg_state(), aarch64_handle_watchpoint(), aarch64_show_debug_reg_state(), debug_hw_points, fprintf_unfiltered(), gdb_assert, gdb_stdlog, hw_execute, inferior_ptid, and ptid_get_pid().
Referenced by _initialize_aarch64_linux_nat().
static void aarch64_linux_new_fork (struct lwp_info * parent, pid_t child_pid) [static]
Definition at line 725 of file aarch64-linux-nat.c.
References aarch64_get_debug_reg_state(), lwp_info::arch_private, lwp_info::ptid, and ptid_get_pid().
Referenced by _initialize_aarch64_linux_nat().
static void aarch64_linux_new_thread (struct lwp_info * lp) [static]
Definition at line 710 of file aarch64-linux-nat.c.
References aarch64_num_bp_regs, aarch64_num_wp_regs, lwp_info::arch_private, arch_lwp_info::dr_changed_bp, arch_lwp_info::dr_changed_wp, and DR_MARK_ALL_CHANGED.
Referenced by _initialize_aarch64_linux_nat().
static void aarch64_linux_prepare_to_resume (struct lwp_info * lwp) [static]
Definition at line 673 of file aarch64-linux-nat.c.
References aarch64_get_debug_reg_state(), aarch64_linux_set_debug_regs(), lwp_info::arch_private, debug_hw_points, arch_lwp_info::dr_changed_bp, arch_lwp_info::dr_changed_wp, DR_CLEAR_CHANGED, DR_HAS_CHANGED, fprintf_unfiltered(), gdb_stdlog, lwp_info::ptid, ptid_get_lwp(), and ptid_get_pid().
Referenced by _initialize_aarch64_linux_nat().
static struct target_desc* aarch64_linux_read_description (struct target_ops * ops) [static, read]
Definition at line 843 of file aarch64-linux-nat.c.
References initialize_tdesc_aarch64(), and tdesc_aarch64.
Referenced by _initialize_aarch64_linux_nat().
static int aarch64_linux_region_ok_for_hw_watchpoint (CORE_ADDR addr, int len) [static]
Definition at line 1398 of file aarch64-linux-nat.c.
References AARCH64_HWP_MAX_LEN_PER_REG, and aarch64_num_wp_regs.
Referenced by _initialize_aarch64_linux_nat().
static int aarch64_linux_remove_hw_breakpoint (struct gdbarch * gdbarch, struct bp_target_info * bp_tgt) [static]
Definition at line 1233 of file aarch64-linux-nat.c.
References aarch64_get_debug_reg_state(), aarch64_handle_breakpoint(), aarch64_show_debug_reg_state(), debug_hw_points, fprintf_unfiltered(), gdb_stdlog, hw_execute, inferior_ptid, len, bp_target_info::placed_address, and ptid_get_pid().
Referenced by _initialize_aarch64_linux_nat().
static int aarch64_linux_remove_watchpoint (CORE_ADDR addr, int len, int type, struct expression * cond) [static]
Definition at line 1369 of file aarch64-linux-nat.c.
References aarch64_get_debug_reg_state(), aarch64_handle_watchpoint(), aarch64_show_debug_reg_state(), debug_hw_points, fprintf_unfiltered(), gdb_assert, gdb_stdlog, hw_execute, inferior_ptid, and ptid_get_pid().
Referenced by _initialize_aarch64_linux_nat().
static void aarch64_linux_set_debug_regs (const struct aarch64_debug_reg_state * state, int tid, int watchpoint) [static]
Definition at line 306 of file aarch64-linux-nat.c.
References _, aarch64_num_bp_regs, aarch64_num_wp_regs, aarch64_debug_reg_state::dr_addr_bp, aarch64_debug_reg_state::dr_addr_wp, aarch64_debug_reg_state::dr_ctrl_bp, aarch64_debug_reg_state::dr_ctrl_wp, error(), memset(), ptrace(), and PTRACE_SETREGSET.
Referenced by aarch64_linux_prepare_to_resume().
static int aarch64_linux_stopped_by_watchpoint (void) [static]
Definition at line 1476 of file aarch64-linux-nat.c.
References aarch64_linux_stopped_data_address(), and current_target.
Referenced by _initialize_aarch64_linux_nat().
static int aarch64_linux_stopped_data_address (struct target_ops * target, CORE_ADDR * addr_p) [static]
Definition at line 1437 of file aarch64-linux-nat.c.
References aarch64_get_debug_reg_state(), aarch64_num_wp_regs, aarch64_watchpoint_length(), aarch64_debug_reg_state::dr_addr_wp, DR_CONTROL_ENABLED, aarch64_debug_reg_state::dr_ctrl_wp, aarch64_debug_reg_state::dr_ref_count_wp, inferior_ptid, len, linux_nat_get_siginfo(), ptid_get_pid(), and TRAP_HWBKPT.
Referenced by _initialize_aarch64_linux_nat(), and aarch64_linux_stopped_by_watchpoint().
static void aarch64_linux_store_inferior_registers (struct target_ops * ops, struct regcache * regcache, int regno) [static]
Definition at line 592 of file aarch64-linux-nat.c.
References AARCH64_V0_REGNUM, store_fpregs_to_thread(), and store_gregs_to_thread().
Referenced by _initialize_aarch64_linux_nat().
static int aarch64_linux_watchpoint_addr_within_range (struct target_ops * target, CORE_ADDR addr, CORE_ADDR start, int length) [static]
Definition at line 1486 of file aarch64-linux-nat.c.
Referenced by _initialize_aarch64_linux_nat().
static void aarch64_notify_debug_reg_change (const struct aarch64_debug_reg_state * state, int is_watchpoint, unsigned int idx) [static]
Definition at line 410 of file aarch64-linux-nat.c.
References debug_reg_change_callback(), aarch64_dr_update_callback_param::idx, inferior_ptid, aarch64_dr_update_callback_param::is_watchpoint, is_watchpoint(), iterate_over_lwps(), pid_to_ptid(), and ptid_get_pid().
Referenced by aarch64_dr_state_insert_one_point(), and aarch64_dr_state_remove_one_point().
static unsigned int aarch64_point_encode_ctrl_reg (int type, int len) [static]
Definition at line 988 of file aarch64-linux-nat.c.
References _, hw_access, hw_execute, hw_read, hw_write, len, and perror_with_name().
Referenced by aarch64_dr_state_insert_one_point(), and aarch64_dr_state_remove_one_point().
static int aarch64_point_is_aligned (int is_watchpoint, CORE_ADDR addr, int len) [static]
Definition at line 1034 of file aarch64-linux-nat.c.
References AARCH64_HBP_ALIGNMENT, and AARCH64_HWP_ALIGNMENT.
Referenced by aarch64_dr_state_insert_one_point(), aarch64_dr_state_remove_one_point(), aarch64_handle_breakpoint(), and aarch64_handle_watchpoint().
static struct aarch64_process_info* aarch64_process_info_get (pid_t pid) [static, read]
Definition at line 246 of file aarch64-linux-nat.c.
References aarch64_add_process(), and aarch64_find_process_pid().
Referenced by aarch64_get_debug_reg_state().
static void aarch64_show_debug_reg_state (struct aarch64_debug_reg_state * state, const char * func, CORE_ADDR addr, int len, int type) [static]
Definition at line 425 of file aarch64-linux-nat.c.
References aarch64_num_bp_regs, aarch64_num_wp_regs, aarch64_debug_reg_state::dr_addr_bp, aarch64_debug_reg_state::dr_addr_wp, aarch64_debug_reg_state::dr_ctrl_bp, aarch64_debug_reg_state::dr_ctrl_wp, aarch64_debug_reg_state::dr_ref_count_bp, aarch64_debug_reg_state::dr_ref_count_wp, fprintf_unfiltered(), gdb_stdlog, hw_access, hw_execute, hw_read, and hw_write.
Referenced by aarch64_linux_insert_hw_breakpoint(), aarch64_linux_insert_watchpoint(), aarch64_linux_remove_hw_breakpoint(), and aarch64_linux_remove_watchpoint().
static unsigned int aarch64_watchpoint_length (unsigned int ctrl) [inline, static]
Definition at line 966 of file aarch64-linux-nat.c.
References DR_CONTROL_LENGTH.
Referenced by aarch64_linux_stopped_data_address().
static void add_show_debug_regs_command (void) [static]
Definition at line 1496 of file aarch64-linux-nat.c.
References _, add_setshow_boolean_cmd(), class_maintenance, debug_hw_points, maintenance_set_cmdlist, and maintenance_show_cmdlist.
Referenced by _initialize_aarch64_linux_nat().
static int debug_reg_change_callback (struct lwp_info * lwp, void * ptr) [static]
Definition at line 348 of file aarch64-linux-nat.c.
References aarch64_num_bp_regs, aarch64_num_wp_regs, lwp_info::arch_private, debug_hw_points, arch_lwp_info::dr_changed_bp, arch_lwp_info::dr_changed_wp, DR_MARK_N_CHANGED, fprintf_unfiltered(), gdb_assert, gdb_stdlog, get_thread_id(), aarch64_dr_update_callback_param::idx, aarch64_dr_update_callback_param::is_watchpoint, is_watchpoint(), linux_stop_lwp(), phex(), lwp_info::ptid, and lwp_info::stopped.
Referenced by aarch64_notify_debug_reg_change().
static void fetch_fpregs_from_thread (struct regcache * regcache) [static]
Definition at line 514 of file aarch64-linux-nat.c.
References _, AARCH64_FPCR_REGNUM, AARCH64_FPSR_REGNUM, AARCH64_V0_REGNUM, AARCH64_V31_REGNUM, get_thread_id(), inferior_ptid, perror_with_name(), ptrace(), PTRACE_GETREGSET, and regcache_raw_supply().
Referenced by aarch64_linux_fetch_inferior_registers().
static void fetch_gregs_from_thread (struct regcache * regcache) [static]
Definition at line 461 of file aarch64-linux-nat.c.
References _, AARCH64_CPSR_REGNUM, AARCH64_X0_REGNUM, get_thread_id(), inferior_ptid, perror_with_name(), ptrace(), PTRACE_GETREGSET, and regcache_raw_supply().
Referenced by aarch64_linux_fetch_inferior_registers().
void fill_fpregset (const struct regcache * regcache, gdb_fpregset_t * fpregsetp, int regno)
Definition at line 639 of file aarch64-linux-nat.c.
Referenced by dec_thread_store_registers(), linux_nat_collect_thread_registers(), ppcfbsd_store_inferior_registers(), ps_lgetfpregs(), sol_thread_store_registers(), store_all_fp_regs(), and store_fpregs().
void fill_gregset (const struct regcache * regcache, gdb_gregset_t * gregsetp, int regno)
Definition at line 612 of file aarch64-linux-nat.c.
Referenced by dec_thread_store_registers(), linux_nat_collect_thread_registers(), ppcfbsd_store_inferior_registers(), ps_lgetregs(), sol_thread_store_registers(), store_all_gp_regs(), store_gregs(), store_inferior_registers(), and store_regs().
static int get_thread_id (ptid_t ptid) [static]
Definition at line 55 of file aarch64-linux-nat.c.
References ptid_get_lwp(), and ptid_get_pid().
Referenced by aarch64_linux_get_debug_reg_capacity(), debug_reg_change_callback(), fetch_fpregs_from_thread(), fetch_gregs_from_thread(), store_fpregs_to_thread(), and store_gregs_to_thread().
ps_err_e ps_get_thread_area (const struct ps_prochandle * ph, lwpid_t lwpid, int idx, void ** base)
Definition at line 753 of file aarch64-linux-nat.c.
static void store_fpregs_to_thread (const struct regcache * regcache) [static]
Definition at line 541 of file aarch64-linux-nat.c.
References _, AARCH64_FPCR_REGNUM, AARCH64_FPSR_REGNUM, AARCH64_V0_REGNUM, AARCH64_V31_REGNUM, get_thread_id(), inferior_ptid, perror_with_name(), ptrace(), PTRACE_GETREGSET, PTRACE_SETREGSET, REG_VALID, regcache_raw_collect(), and regcache_register_status().
Referenced by aarch64_linux_store_inferior_registers().
static void store_gregs_to_thread (const struct regcache * regcache) [static]
Definition at line 485 of file aarch64-linux-nat.c.
References _, AARCH64_CPSR_REGNUM, AARCH64_X0_REGNUM, get_thread_id(), inferior_ptid, perror_with_name(), ptrace(), PTRACE_GETREGSET, PTRACE_SETREGSET, REG_VALID, regcache_raw_collect(), and regcache_register_status().
Referenced by aarch64_linux_store_inferior_registers().
void supply_fpregset (struct regcache * regcache, const gdb_fpregset_t * fpregsetp)
Definition at line 664 of file aarch64-linux-nat.c.
Referenced by dec_thread_fetch_registers(), fetch_all_fp_regs(), fetch_core_registers(), fetch_fpregs(), procfs_fetch_registers(), ps_lsetfpregs(), and sol_thread_fetch_registers().
void supply_gregset (struct regcache * regcache, const gdb_gregset_t * gregsetp)
Definition at line 629 of file aarch64-linux-nat.c.
Referenced by dec_thread_fetch_registers(), fetch_all_gp_regs(), fetch_core_registers(), fetch_inferior_registers(), fetch_regs(), ppcfbsd_fetch_inferior_registers(), procfs_fetch_registers(), ps_lsetregs(), and sol_thread_fetch_registers().
Variable Documentation
int aarch64_num_bp_regs [static]
Definition at line 118 of file aarch64-linux-nat.c.
Referenced by aarch64_dr_state_insert_one_point(), aarch64_dr_state_remove_one_point(), aarch64_linux_get_debug_reg_capacity(), aarch64_linux_new_thread(), aarch64_linux_set_debug_regs(), aarch64_show_debug_reg_state(), and debug_reg_change_callback().
int aarch64_num_wp_regs [static]
Definition at line 119 of file aarch64-linux-nat.c.
Referenced by aarch64_dr_state_insert_one_point(), aarch64_dr_state_remove_one_point(), aarch64_linux_get_debug_reg_capacity(), aarch64_linux_new_thread(), aarch64_linux_region_ok_for_hw_watchpoint(), aarch64_linux_set_debug_regs(), aarch64_linux_stopped_data_address(), aarch64_show_debug_reg_state(), and debug_reg_change_callback().
struct aarch64_process_info* aarch64_process_list = NULL [static]
Definition at line 209 of file aarch64-linux-nat.c.
Referenced by aarch64_add_process(), and aarch64_forget_process().
int debug_hw_points [static]
Definition at line 123 of file aarch64-linux-nat.c.
Referenced by aarch64_handle_unaligned_watchpoint(), aarch64_linux_insert_hw_breakpoint(), aarch64_linux_insert_watchpoint(), aarch64_linux_prepare_to_resume(), aarch64_linux_remove_hw_breakpoint(), aarch64_linux_remove_watchpoint(), add_show_debug_regs_command(), and debug_reg_change_callback().
void(* super_post_startup_inferior)(ptid_t ptid) [static]
Definition at line 828 of file aarch64-linux-nat.c.
Referenced by _initialize_aarch64_linux_nat(), and aarch64_linux_child_post_startup_inferior().