GDB (xrefs): /home/stan/gdb/src/gdb/aarch64-tdep.c File Reference
/home/stan/gdb/src/gdb/aarch64-tdep.c File Reference
#include "defs.h"
#include "frame.h"
#include "inferior.h"
#include "gdbcmd.h"
#include "gdbcore.h"
#include "gdb_string.h"
#include "dis-asm.h"
#include "regcache.h"
#include "reggroups.h"
#include "doublest.h"
#include "value.h"
#include "arch-utils.h"
#include "osabi.h"
#include "frame-unwind.h"
#include "frame-base.h"
#include "trad-frame.h"
#include "objfiles.h"
#include "dwarf2-frame.h"
#include "gdbtypes.h"
#include "prologue-value.h"
#include "target-descriptions.h"
#include "user-regs.h"
#include "language.h"
#include "infcall.h"
#include "aarch64-tdep.h"
#include "elf-bfd.h"
#include "elf/aarch64.h"
#include "gdb_assert.h"
#include "vec.h"
#include "features/aarch64.c"
Classes
struct aarch64_prologue_cache
struct stack_item_t
struct aarch64_call_info
Defines
#define AARCH64_Q0_REGNUM 0
#define AARCH64_D0_REGNUM (AARCH64_Q0_REGNUM + 32)
#define AARCH64_S0_REGNUM (AARCH64_D0_REGNUM + 32)
#define AARCH64_H0_REGNUM (AARCH64_S0_REGNUM + 32)
#define AARCH64_B0_REGNUM (AARCH64_H0_REGNUM + 32)
Functions
static void show_aarch64_debug (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static int32_t extract_signed_bitfield (uint32_t insn, unsigned width, unsigned offset)
static int decode_masked_match (uint32_t insn, uint32_t mask, uint32_t pattern)
static int decode_add_sub_imm (CORE_ADDR addr, uint32_t insn, unsigned *rd, unsigned *rn, int32_t *imm)
static int decode_adrp (CORE_ADDR addr, uint32_t insn, unsigned *rd)
static int decode_b (CORE_ADDR addr, uint32_t insn, unsigned *link, int32_t *offset)
static int decode_bcond (CORE_ADDR addr, uint32_t insn, unsigned *cond, int32_t *offset)
static int decode_br (CORE_ADDR addr, uint32_t insn, unsigned *link, unsigned *rn)
static int decode_cb (CORE_ADDR addr, uint32_t insn, int *is64, unsigned *op, unsigned *rn, int32_t *offset)
static int decode_eret (CORE_ADDR addr, uint32_t insn)
static int decode_movz (CORE_ADDR addr, uint32_t insn, unsigned *rd)
static int decode_orr_shifted_register_x (CORE_ADDR addr, uint32_t insn, unsigned *rd, unsigned *rn, unsigned *rm, int32_t *imm)
static int decode_ret (CORE_ADDR addr, uint32_t insn, unsigned *rn)
static int decode_stp_offset (CORE_ADDR addr, uint32_t insn, unsigned *rt1, unsigned *rt2, unsigned *rn, int32_t *imm)
static int decode_stp_offset_wb (CORE_ADDR addr, uint32_t insn, unsigned *rt1, unsigned *rt2, unsigned *rn, int32_t *imm)
static int decode_stur (CORE_ADDR addr, uint32_t insn, int *is64, unsigned *rt, unsigned *rn, int32_t *imm)
static int decode_tb (CORE_ADDR addr, uint32_t insn, unsigned *op, unsigned *bit, unsigned *rt, int32_t *imm)
static CORE_ADDR aarch64_analyze_prologue (struct gdbarch *gdbarch, CORE_ADDR start, CORE_ADDR limit, struct aarch64_prologue_cache *cache)
static CORE_ADDR aarch64_skip_prologue (struct gdbarch *gdbarch, CORE_ADDR pc)
static void aarch64_scan_prologue (struct frame_info *this_frame, struct aarch64_prologue_cache *cache)
static struct
aarch64_prologue_cache * aarch64_make_prologue_cache (struct frame_info *this_frame)
static void aarch64_prologue_this_id (struct frame_info *this_frame, void **this_cache, struct frame_id *this_id)
static struct value * aarch64_prologue_prev_register (struct frame_info *this_frame, void **this_cache, int prev_regnum)
static struct
aarch64_prologue_cache * aarch64_make_stub_cache (struct frame_info *this_frame)
static void aarch64_stub_this_id (struct frame_info *this_frame, void **this_cache, struct frame_id *this_id)
static int aarch64_stub_unwind_sniffer (const struct frame_unwind *self, struct frame_info *this_frame, void **this_prologue_cache)
static CORE_ADDR aarch64_normal_frame_base (struct frame_info *this_frame, void **this_cache)
static struct frame_id aarch64_dummy_id (struct gdbarch *gdbarch, struct frame_info *this_frame)
static CORE_ADDR aarch64_unwind_pc (struct gdbarch *gdbarch, struct frame_info *this_frame)
static CORE_ADDR aarch64_unwind_sp (struct gdbarch *gdbarch, struct frame_info *this_frame)
static struct value * aarch64_dwarf2_prev_register (struct frame_info *this_frame, void **this_cache, int regnum)
static void aarch64_dwarf2_frame_init_reg (struct gdbarch *gdbarch, int regnum, struct dwarf2_frame_state_reg *reg, struct frame_info *this_frame)
DEF_VEC_O (stack_item_t)
static int aarch64_type_align (struct type *t)
static int is_hfa (struct type *ty)
static void pass_in_x (struct gdbarch *gdbarch, struct regcache *regcache, struct aarch64_call_info *info, struct type *type, const bfd_byte *buf)
static int pass_in_v (struct gdbarch *gdbarch, struct regcache *regcache, struct aarch64_call_info *info, const bfd_byte *buf)
static void pass_on_stack (struct aarch64_call_info *info, struct type *type, const bfd_byte *buf)
static void pass_in_x_or_stack (struct gdbarch *gdbarch, struct regcache *regcache, struct aarch64_call_info *info, struct type *type, const bfd_byte *buf)
static void pass_in_v_or_stack (struct gdbarch *gdbarch, struct regcache *regcache, struct aarch64_call_info *info, struct type *type, const bfd_byte *buf)
static CORE_ADDR aarch64_push_dummy_call (struct gdbarch *gdbarch, struct value *function, struct regcache *regcache, CORE_ADDR bp_addr, int nargs, struct value **args, CORE_ADDR sp, int struct_return, CORE_ADDR struct_addr)
static CORE_ADDR aarch64_frame_align (struct gdbarch *gdbarch, CORE_ADDR sp)
static struct type * aarch64_vnq_type (struct gdbarch *gdbarch)
static struct type * aarch64_vnd_type (struct gdbarch *gdbarch)
static struct type * aarch64_vns_type (struct gdbarch *gdbarch)
static struct type * aarch64_vnh_type (struct gdbarch *gdbarch)
static struct type * aarch64_vnb_type (struct gdbarch *gdbarch)
static int aarch64_dwarf_reg_to_regnum (struct gdbarch *gdbarch, int reg)
static int aarch64_gdb_print_insn (bfd_vma memaddr, disassemble_info *info)
static const gdb_byte * aarch64_breakpoint_from_pc (struct gdbarch *gdbarch, CORE_ADDR *pcptr, int *lenptr)
static void aarch64_extract_return_value (struct type *type, struct regcache *regs, gdb_byte *valbuf)
static int aarch64_return_in_memory (struct gdbarch *gdbarch, struct type *type)
static void aarch64_store_return_value (struct type *type, struct regcache *regs, const gdb_byte *valbuf)
static enum return_value_convention aarch64_return_value (struct gdbarch *gdbarch, struct value *func_value, struct type *valtype, struct regcache *regcache, gdb_byte *readbuf, const gdb_byte *writebuf)
static int aarch64_get_longjmp_target (struct frame_info *frame, CORE_ADDR *pc)
static const char * aarch64_pseudo_register_name (struct gdbarch *gdbarch, int regnum)
static struct type * aarch64_pseudo_register_type (struct gdbarch *gdbarch, int regnum)
static int aarch64_pseudo_register_reggroup_p (struct gdbarch *gdbarch, int regnum, struct reggroup *group)
static struct value * aarch64_pseudo_read_value (struct gdbarch *gdbarch, struct regcache *regcache, int regnum)
static void aarch64_pseudo_write (struct gdbarch *gdbarch, struct regcache *regcache, int regnum, const gdb_byte *buf)
static struct value * value_of_aarch64_user_reg (struct frame_info *frame, const void *baton)
static struct gdbarch * aarch64_gdbarch_init (struct gdbarch_info info, struct gdbarch_list *arches)
static void aarch64_dump_tdep (struct gdbarch *gdbarch, struct ui_file *file)
void _initialize_aarch64_tdep (void)
Variables
struct {
const char *const name
int regnum
} aarch64_register_aliases []
static const char *const aarch64_r_register_names []
static const char *const aarch64_v_register_names []
static int aarch64_debug
struct frame_unwind aarch64_prologue_unwind
struct frame_unwind aarch64_stub_unwind
struct frame_base aarch64_normal_base
static const gdb_byte aarch64_default_breakpoint [] = {0x00, 0x00, 0x20, 0xd4}
initialize_file_ftype _initialize_aarch64_tdep
Define Documentation
#define AARCH64_B0_REGNUM (AARCH64_H0_REGNUM + 32)
Definition at line 62 of file aarch64-tdep.c.
Referenced by aarch64_pseudo_read_value(), aarch64_pseudo_register_name(), aarch64_pseudo_register_reggroup_p(), aarch64_pseudo_register_type(), and aarch64_pseudo_write().
#define AARCH64_D0_REGNUM (AARCH64_Q0_REGNUM + 32)
Definition at line 59 of file aarch64-tdep.c.
Referenced by aarch64_pseudo_read_value(), aarch64_pseudo_register_name(), aarch64_pseudo_register_reggroup_p(), aarch64_pseudo_register_type(), and aarch64_pseudo_write().
#define AARCH64_H0_REGNUM (AARCH64_S0_REGNUM + 32)
Definition at line 61 of file aarch64-tdep.c.
Referenced by aarch64_pseudo_read_value(), aarch64_pseudo_register_name(), aarch64_pseudo_register_reggroup_p(), aarch64_pseudo_register_type(), and aarch64_pseudo_write().
#define AARCH64_Q0_REGNUM 0
Definition at line 58 of file aarch64-tdep.c.
Referenced by aarch64_pseudo_read_value(), aarch64_pseudo_register_name(), aarch64_pseudo_register_reggroup_p(), aarch64_pseudo_register_type(), and aarch64_pseudo_write().
#define AARCH64_S0_REGNUM (AARCH64_D0_REGNUM + 32)
Definition at line 60 of file aarch64-tdep.c.
Referenced by aarch64_pseudo_read_value(), aarch64_pseudo_register_name(), aarch64_pseudo_register_reggroup_p(), aarch64_pseudo_register_type(), and aarch64_pseudo_write().
Function Documentation
void _initialize_aarch64_tdep (void)
Definition at line 2714 of file aarch64-tdep.c.
References _, _initialize_aarch64_tdep, aarch64_debug, aarch64_dump_tdep(), aarch64_gdbarch_init(), add_setshow_boolean_cmd(), class_maintenance, gdbarch_register(), initialize_tdesc_aarch64(), setdebuglist, show_aarch64_debug(), and showdebuglist.
static CORE_ADDR aarch64_analyze_prologue (struct gdbarch * gdbarch, CORE_ADDR start, CORE_ADDR limit, struct aarch64_prologue_cache * cache) [static]
Definition at line 658 of file aarch64-tdep.c.
References aarch64_debug, AARCH64_FP_REGNUM, AARCH64_SP_REGNUM, AARCH64_X_REGISTER_COUNT, trad_frame_saved_reg::addr, bit, core_addr_to_string_nz(), decode_add_sub_imm(), decode_adrp(), decode_b(), decode_bcond(), decode_br(), decode_cb(), decode_eret(), decode_movz(), decode_orr_shifted_register_x(), decode_ret(), decode_stp_offset(), decode_stp_offset_wb(), decode_stur(), decode_tb(), do_cleanups(), fprintf_unfiltered(), aarch64_prologue_cache::framereg, aarch64_prologue_cache::framesize, gdb_stdlog, gdbarch_addr_bit(), gdbarch_byte_order_for_code(), prologue_value::k, make_cleanup_free_pv_area(), make_pv_area(), offset, pv_add_constant(), pv_area_find_reg(), pv_area_store(), pv_area_store_would_trash(), pv_is_register(), pv_register(), pv_unknown(), read_memory_unsigned_integer(), and aarch64_prologue_cache::saved_regs.
Referenced by aarch64_scan_prologue(), and aarch64_skip_prologue().
static const gdb_byte* aarch64_breakpoint_from_pc (struct gdbarch * gdbarch, CORE_ADDR * pcptr, int * lenptr) [static]
Definition at line 1904 of file aarch64-tdep.c.
References aarch64_default_breakpoint, and gdbarch_tdep().
Referenced by aarch64_gdbarch_init().
static struct frame_id aarch64_dummy_id (struct gdbarch * gdbarch, struct frame_info * this_frame) [static, read]
Definition at line 1147 of file aarch64-tdep.c.
References AARCH64_SP_REGNUM, frame_id_build(), get_frame_pc(), and get_frame_register_unsigned().
Referenced by aarch64_gdbarch_init().
static void aarch64_dump_tdep (struct gdbarch * gdbarch, struct ui_file * file) [static]
Definition at line 2699 of file aarch64-tdep.c.
References _, fprintf_unfiltered(), gdbarch_tdep(), gdbarch_tdep::lowest_pc, and paddress().
Referenced by _initialize_aarch64_tdep().
static void aarch64_dwarf2_frame_init_reg (struct gdbarch * gdbarch, int regnum, struct dwarf2_frame_state_reg * reg, struct frame_info * this_frame) [static]
Definition at line 1198 of file aarch64-tdep.c.
References aarch64_dwarf2_prev_register(), AARCH64_PC_REGNUM, AARCH64_SP_REGNUM, DWARF2_FRAME_REG_CFA, DWARF2_FRAME_REG_FN, dwarf2_frame_state_reg::fn, dwarf2_frame_state_reg::how, and dwarf2_frame_state_reg::loc.
Referenced by aarch64_gdbarch_init().
static struct value* aarch64_dwarf2_prev_register (struct frame_info * this_frame, void ** this_cache, int regnum) [static, read]
Definition at line 1177 of file aarch64-tdep.c.
References _, AARCH64_LR_REGNUM, AARCH64_PC_REGNUM, frame_unwind_got_constant(), frame_unwind_register_unsigned(), get_frame_arch(), and internal_error().
Referenced by aarch64_dwarf2_frame_init_reg().
static int aarch64_dwarf_reg_to_regnum (struct gdbarch * gdbarch, int reg) [static]
Definition at line 1872 of file aarch64-tdep.c.
References AARCH64_DWARF_SP, AARCH64_DWARF_V0, AARCH64_DWARF_X0, AARCH64_SP_REGNUM, AARCH64_V0_REGNUM, and AARCH64_X0_REGNUM.
Referenced by aarch64_gdbarch_init().
static void aarch64_extract_return_value (struct type * type, struct regcache * regs, gdb_byte * valbuf) [static]
Definition at line 1918 of file aarch64-tdep.c.
References aarch64_debug, AARCH64_V0_REGNUM, AARCH64_X0_REGNUM, gdbarch::byte_order, check_typedef(), fprintf_unfiltered(), gdb_stdlog, gdbarch_byte_order(), gdbarch_register_name(), get_regcache_arch(), is_hfa(), len, memcpy(), regcache_cooked_read(), regcache_cooked_read_unsigned(), store_unsigned_integer(), TYPE_CODE, TYPE_CODE_BOOL, TYPE_CODE_CHAR, TYPE_CODE_COMPLEX, TYPE_CODE_ENUM, TYPE_CODE_FLT, TYPE_CODE_INT, TYPE_CODE_PTR, TYPE_CODE_REF, TYPE_FIELD_TYPE, TYPE_LENGTH, TYPE_NFIELDS, TYPE_TARGET_TYPE, ULONGEST, V_REGISTER_SIZE, and X_REGISTER_SIZE.
Referenced by aarch64_return_value().
static CORE_ADDR aarch64_frame_align (struct gdbarch * gdbarch, CORE_ADDR sp) [static]
Definition at line 1722 of file aarch64-tdep.c.
Referenced by aarch64_gdbarch_init().
static int aarch64_gdb_print_insn (bfd_vma memaddr, disassemble_info * info) [static]
Definition at line 1890 of file aarch64-tdep.c.
Referenced by aarch64_gdbarch_init().
static struct gdbarch* aarch64_gdbarch_init (struct gdbarch_info info, struct gdbarch_list * arches) [static, read]
Definition at line 2520 of file aarch64-tdep.c.
References aarch64_breakpoint_from_pc(), aarch64_dummy_id(), aarch64_dwarf2_frame_init_reg(), aarch64_dwarf_reg_to_regnum(), aarch64_frame_align(), aarch64_gdb_print_insn(), aarch64_get_longjmp_target(), AARCH64_PC_REGNUM, aarch64_pseudo_read_value(), aarch64_pseudo_register_name(), aarch64_pseudo_register_reggroup_p(), aarch64_pseudo_register_type(), aarch64_pseudo_write(), aarch64_push_dummy_call(), aarch64_r_register_names, aarch64_register_aliases, aarch64_return_value(), aarch64_skip_prologue(), AARCH64_SP_REGNUM, aarch64_unwind_pc(), aarch64_unwind_sp(), AARCH64_V0_REGNUM, aarch64_v_register_names, AARCH64_X0_REGNUM, gdbarch_info::byte_order_for_code, core_addr_lessthan(), dwarf2_append_unwinders(), dwarf2_frame_set_init_reg(), floatformats_ia64_quad, floatformats_ieee_double, floatformats_ieee_single, frame_base_set_default(), frame_unwind_append_unwinder(), gdb_assert, gdbarch_list::gdbarch, gdbarch_alloc(), gdbarch_init_osabi(), gdbarch_list_lookup_by_info(), gdbarch_tdep::jb_elt_size, gdbarch_tdep::jb_pc, gdbarch_tdep::lowest_pc, name, gdbarch_list::next, regnum, set_gdbarch_breakpoint_from_pc(), set_gdbarch_cannot_step_breakpoint(), set_gdbarch_char_signed(), set_gdbarch_double_bit(), set_gdbarch_double_format(), set_gdbarch_dummy_id(), set_gdbarch_dwarf2_reg_to_regnum(), set_gdbarch_float_bit(), set_gdbarch_float_format(), set_gdbarch_frame_align(), set_gdbarch_get_longjmp_target(), set_gdbarch_have_nonsteppable_watchpoint(), set_gdbarch_inner_than(), set_gdbarch_int_bit(), set_gdbarch_long_bit(), set_gdbarch_long_double_bit(), set_gdbarch_long_double_format(), set_gdbarch_long_long_bit(), set_gdbarch_num_pseudo_regs(), set_gdbarch_num_regs(), set_gdbarch_pc_regnum(), set_gdbarch_print_insn(), set_gdbarch_pseudo_register_read_value(), set_gdbarch_pseudo_register_write(), set_gdbarch_ptr_bit(), set_gdbarch_push_dummy_call(), set_gdbarch_return_value(), set_gdbarch_short_bit(), set_gdbarch_skip_prologue(), set_gdbarch_sp_regnum(), set_gdbarch_unwind_pc(), set_gdbarch_unwind_sp(), set_gdbarch_vbit_in_delta(), set_tdesc_pseudo_register_name(), set_tdesc_pseudo_register_reggroup_p(), set_tdesc_pseudo_register_type(), gdbarch_info::target_desc, gdbarch_info::tdep_info, tdesc_aarch64, tdesc_data, tdesc_data_alloc(), tdesc_data_cleanup(), tdesc_find_feature(), tdesc_has_registers(), tdesc_numbered_register(), tdesc_use_registers(), user_reg_add(), value_of_aarch64_user_reg(), and xcalloc().
Referenced by _initialize_aarch64_tdep().
static int aarch64_get_longjmp_target (struct frame_info * frame, CORE_ADDR * pc) [static]
Definition at line 2179 of file aarch64-tdep.c.
References AARCH64_X0_REGNUM, extract_unsigned_integer(), gdbarch_byte_order(), gdbarch_tdep(), get_frame_arch(), get_frame_register_unsigned(), gdbarch_tdep::jb_elt_size, gdbarch_tdep::jb_pc, target_read_memory(), and X_REGISTER_SIZE.
Referenced by aarch64_gdbarch_init().
static struct aarch64_prologue_cache* aarch64_make_prologue_cache (struct frame_info * this_frame) [static, read]
Definition at line 936 of file aarch64-tdep.c.
References aarch64_scan_prologue(), trad_frame_saved_reg::addr, FRAME_OBSTACK_ZALLOC, aarch64_prologue_cache::framereg, aarch64_prologue_cache::framesize, gdbarch_num_regs(), get_frame_arch(), get_frame_register_unsigned(), aarch64_prologue_cache::prev_sp, aarch64_prologue_cache::saved_regs, trad_frame_addr_p(), and trad_frame_alloc_saved_regs().
Referenced by aarch64_normal_frame_base(), aarch64_prologue_prev_register(), and aarch64_prologue_this_id().
static struct aarch64_prologue_cache* aarch64_make_stub_cache (struct frame_info * this_frame) [static, read]
Definition at line 1056 of file aarch64-tdep.c.
References AARCH64_SP_REGNUM, FRAME_OBSTACK_ZALLOC, get_frame_register_unsigned(), aarch64_prologue_cache::prev_sp, aarch64_prologue_cache::saved_regs, and trad_frame_alloc_saved_regs().
Referenced by aarch64_stub_this_id().
static CORE_ADDR aarch64_normal_frame_base (struct frame_info * this_frame, void ** this_cache) [static]
Definition at line 1120 of file aarch64-tdep.c.
References aarch64_make_prologue_cache(), aarch64_prologue_cache::framesize, and aarch64_prologue_cache::prev_sp.
static struct value* aarch64_prologue_prev_register (struct frame_info * this_frame, void ** this_cache, int prev_regnum) [static, read]
Definition at line 997 of file aarch64-tdep.c.
References AARCH64_LR_REGNUM, aarch64_make_prologue_cache(), AARCH64_PC_REGNUM, AARCH64_SP_REGNUM, frame_unwind_got_constant(), frame_unwind_register_unsigned(), get_frame_arch(), aarch64_prologue_cache::prev_sp, aarch64_prologue_cache::saved_regs, and trad_frame_get_prev_register().
static void aarch64_prologue_this_id (struct frame_info * this_frame, void ** this_cache, struct frame_id * this_id) [static]
Definition at line 969 of file aarch64-tdep.c.
References aarch64_make_prologue_cache(), frame_id_build(), func, get_frame_arch(), get_frame_func(), get_frame_pc(), and aarch64_prologue_cache::prev_sp.
static struct value* aarch64_pseudo_read_value (struct gdbarch * gdbarch, struct regcache * regcache, int regnum) [static, read]
Definition at line 2339 of file aarch64-tdep.c.
References AARCH64_B0_REGNUM, AARCH64_D0_REGNUM, AARCH64_H0_REGNUM, AARCH64_Q0_REGNUM, AARCH64_S0_REGNUM, AARCH64_V0_REGNUM, allocate_value(), B_REGISTER_SIZE, D_REGISTER_SIZE, gdb_assert_not_reached, gdbarch_num_regs(), H_REGISTER_SIZE, lval_register, mark_value_bytes_unavailable(), MAX_REGISTER_SIZE, memcpy(), Q_REGISTER_SIZE, REG_VALID, regcache_raw_read(), register_type(), regnum, S_REGISTER_SIZE, exsummary::status, TYPE_LENGTH, value_contents_raw(), VALUE_LVAL, VALUE_REGNUM, and value_type().
Referenced by aarch64_gdbarch_init().
static const char* aarch64_pseudo_register_name (struct gdbarch * gdbarch, int regnum) [static]
Definition at line 2201 of file aarch64-tdep.c.
References _, AARCH64_B0_REGNUM, AARCH64_D0_REGNUM, AARCH64_H0_REGNUM, AARCH64_Q0_REGNUM, AARCH64_S0_REGNUM, gdbarch_num_regs(), and internal_error().
Referenced by aarch64_gdbarch_init().
static int aarch64_pseudo_register_reggroup_p (struct gdbarch * gdbarch, int regnum, struct reggroup * group) [static]
Definition at line 2315 of file aarch64-tdep.c.
References AARCH64_B0_REGNUM, AARCH64_D0_REGNUM, AARCH64_H0_REGNUM, AARCH64_Q0_REGNUM, AARCH64_S0_REGNUM, all_reggroup, float_reggroup, gdbarch_num_regs(), and vector_reggroup.
Referenced by aarch64_gdbarch_init().
static struct type* aarch64_pseudo_register_type (struct gdbarch * gdbarch, int regnum) [static, read]
Definition at line 2288 of file aarch64-tdep.c.
References _, AARCH64_B0_REGNUM, AARCH64_D0_REGNUM, AARCH64_H0_REGNUM, AARCH64_Q0_REGNUM, AARCH64_S0_REGNUM, aarch64_vnb_type(), aarch64_vnd_type(), aarch64_vnh_type(), aarch64_vnq_type(), aarch64_vns_type(), gdbarch_num_regs(), and internal_error().
Referenced by aarch64_gdbarch_init().
static void aarch64_pseudo_write (struct gdbarch * gdbarch, struct regcache * regcache, int regnum, const gdb_byte * buf) [static]
Definition at line 2431 of file aarch64-tdep.c.
References AARCH64_B0_REGNUM, AARCH64_D0_REGNUM, AARCH64_H0_REGNUM, AARCH64_Q0_REGNUM, AARCH64_S0_REGNUM, AARCH64_V0_REGNUM, B_REGISTER_SIZE, D_REGISTER_SIZE, gdb_assert_not_reached, gdbarch_num_regs(), H_REGISTER_SIZE, MAX_REGISTER_SIZE, memcpy(), memset(), Q_REGISTER_SIZE, regcache_raw_write(), and S_REGISTER_SIZE.
Referenced by aarch64_gdbarch_init().
static CORE_ADDR aarch64_push_dummy_call (struct gdbarch * gdbarch, struct value * function, struct regcache * regcache, CORE_ADDR bp_addr, int nargs, struct value ** args, CORE_ADDR sp, int struct_return, CORE_ADDR struct_addr) [static]
Definition at line 1503 of file aarch64-tdep.c.
References aarch64_debug, AARCH64_LR_REGNUM, AARCH64_SP_REGNUM, AARCH64_STRUCT_RETURN_REGNUM, align_down(), builtin_type::builtin_int32, builtin_type(), builtin_type::builtin_uint32, check_typedef(), stack_item_t::data, fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_register_name(), is_hfa(), language_pass_by_reference(), len, stack_item_t::len, lookup_pointer_type(), memset(), aarch64_call_info::nsaa, aarch64_call_info::nsrn, paddress(), pass_in_v(), pass_in_v_or_stack(), pass_in_x_or_stack(), pass_on_stack(), regcache_cooked_write_unsigned(), TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_BOOL, TYPE_CODE_CHAR, TYPE_CODE_COMPLEX, TYPE_CODE_ENUM, TYPE_CODE_FLT, TYPE_CODE_FUNC, TYPE_CODE_INT, TYPE_CODE_METHOD, TYPE_CODE_PTR, TYPE_CODE_RANGE, TYPE_CODE_STRUCT, TYPE_CODE_UNION, TYPE_LENGTH, TYPE_NFIELDS, TYPE_TARGET_TYPE, TYPE_UNSIGNED, value_cast(), value_contents(), value_contents_writeable(), value_from_pointer(), value_primitive_field(), value_type(), VEC_empty, VEC_free, VEC_last, VEC_pop, and write_memory().
Referenced by aarch64_gdbarch_init().
static int aarch64_return_in_memory (struct gdbarch * gdbarch, struct type * type) [static]
Definition at line 2020 of file aarch64-tdep.c.
References CHECK_TYPEDEF, code, is_hfa(), and TYPE_LENGTH.
Referenced by aarch64_return_value().
static enum return_value_convention aarch64_return_value (struct gdbarch * gdbarch, struct value * func_value, struct type * valtype, struct regcache * regcache, gdb_byte * readbuf, const gdb_byte * writebuf) [static]
Definition at line 2146 of file aarch64-tdep.c.
References aarch64_debug, aarch64_extract_return_value(), aarch64_return_in_memory(), aarch64_store_return_value(), fprintf_unfiltered(), gdb_stdlog, gdbarch_tdep(), RETURN_VALUE_REGISTER_CONVENTION, RETURN_VALUE_STRUCT_CONVENTION, TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_STRUCT, and TYPE_CODE_UNION.
Referenced by aarch64_gdbarch_init().
static void aarch64_scan_prologue (struct frame_info * this_frame, struct aarch64_prologue_cache * cache) [static]
Definition at line 882 of file aarch64-tdep.c.
References aarch64_analyze_prologue(), AARCH64_FP_REGNUM, trad_frame_saved_reg::addr, symtab_and_line::end, find_pc_line(), find_pc_partial_function(), aarch64_prologue_cache::framereg, aarch64_prologue_cache::framesize, gdbarch_byte_order(), get_frame_address_in_block(), get_frame_arch(), get_frame_pc(), get_frame_register_unsigned(), symtab_and_line::line, LONGEST, min, and aarch64_prologue_cache::saved_regs.
Referenced by aarch64_make_prologue_cache().
static CORE_ADDR aarch64_skip_prologue (struct gdbarch * gdbarch, CORE_ADDR pc) [static]
Definition at line 844 of file aarch64-tdep.c.
References aarch64_analyze_prologue(), find_pc_partial_function(), max, and skip_prologue_using_sal().
Referenced by aarch64_gdbarch_init().
static void aarch64_store_return_value (struct type * type, struct regcache * regs, const gdb_byte * valbuf) [static]
Definition at line 2053 of file aarch64-tdep.c.
References aarch64_debug, AARCH64_V0_REGNUM, AARCH64_X0_REGNUM, gdbarch::byte_order, check_typedef(), fprintf_unfiltered(), gdb_stdlog, gdbarch_byte_order(), gdbarch_register_name(), get_regcache_arch(), is_hfa(), len, LONGEST, MAX_REGISTER_SIZE, memcpy(), regcache_cooked_write(), store_signed_integer(), TYPE_CODE, TYPE_CODE_BOOL, TYPE_CODE_CHAR, TYPE_CODE_ENUM, TYPE_CODE_FLT, TYPE_CODE_INT, TYPE_CODE_PTR, TYPE_CODE_REF, TYPE_FIELD_TYPE, TYPE_LENGTH, TYPE_NFIELDS, unpack_long(), V_REGISTER_SIZE, and X_REGISTER_SIZE.
Referenced by aarch64_return_value().
static void aarch64_stub_this_id (struct frame_info * this_frame, void ** this_cache, struct frame_id * this_id) [static]
Definition at line 1074 of file aarch64-tdep.c.
References aarch64_make_stub_cache(), frame_id_build(), get_frame_pc(), and aarch64_prologue_cache::prev_sp.
static int aarch64_stub_unwind_sniffer (const struct frame_unwind * self, struct frame_info * this_frame, void ** this_prologue_cache) [static]
Definition at line 1089 of file aarch64-tdep.c.
References dummy, get_frame_address_in_block(), get_frame_pc(), in_plt_section(), and target_read_memory().
static int aarch64_type_align (struct type * t) [static]
Definition at line 1231 of file aarch64-tdep.c.
References _, check_typedef(), internal_error(), TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_BITSTRING, TYPE_CODE_BOOL, TYPE_CODE_CHAR, TYPE_CODE_COMPLEX, TYPE_CODE_ENUM, TYPE_CODE_FLT, TYPE_CODE_INT, TYPE_CODE_PTR, TYPE_CODE_RANGE, TYPE_CODE_REF, TYPE_CODE_SET, TYPE_CODE_STRUCT, TYPE_CODE_UNION, TYPE_FIELD_TYPE, TYPE_LENGTH, TYPE_NFIELDS, and TYPE_TARGET_TYPE.
Referenced by pass_on_stack().
static CORE_ADDR aarch64_unwind_pc (struct gdbarch * gdbarch, struct frame_info * this_frame) [static]
Definition at line 1157 of file aarch64-tdep.c.
References AARCH64_PC_REGNUM, and frame_unwind_register_unsigned().
Referenced by aarch64_gdbarch_init().
static CORE_ADDR aarch64_unwind_sp (struct gdbarch * gdbarch, struct frame_info * this_frame) [static]
Definition at line 1168 of file aarch64-tdep.c.
References AARCH64_SP_REGNUM, and frame_unwind_register_unsigned().
Referenced by aarch64_gdbarch_init().
static struct type* aarch64_vnb_type (struct gdbarch * gdbarch) [static, read]
Definition at line 1845 of file aarch64-tdep.c.
References append_composite_type_field(), arch_composite_type(), builtin_type::builtin_int8, builtin_type(), builtin_type::builtin_uint8, gdbarch_tdep(), TYPE_CODE_UNION, and gdbarch_tdep::vnb_type.
Referenced by aarch64_pseudo_register_type().
static struct type* aarch64_vnd_type (struct gdbarch * gdbarch) [static, read]
Definition at line 1758 of file aarch64-tdep.c.
References append_composite_type_field(), arch_composite_type(), builtin_type::builtin_double, builtin_type::builtin_int64, builtin_type(), builtin_type::builtin_uint64, gdbarch_tdep(), TYPE_CODE_UNION, and gdbarch_tdep::vnd_type.
Referenced by aarch64_pseudo_register_type().
static struct type* aarch64_vnh_type (struct gdbarch * gdbarch) [static, read]
Definition at line 1818 of file aarch64-tdep.c.
References append_composite_type_field(), arch_composite_type(), builtin_type::builtin_int16, builtin_type(), builtin_type::builtin_uint16, gdbarch_tdep(), TYPE_CODE_UNION, and gdbarch_tdep::vnh_type.
Referenced by aarch64_pseudo_register_type().
static struct type* aarch64_vnq_type (struct gdbarch * gdbarch) [static, read]
Definition at line 1731 of file aarch64-tdep.c.
References append_composite_type_field(), arch_composite_type(), builtin_type::builtin_int128, builtin_type(), builtin_type::builtin_uint128, gdbarch_tdep(), TYPE_CODE_UNION, and gdbarch_tdep::vnq_type.
Referenced by aarch64_pseudo_register_type().
static struct type* aarch64_vns_type (struct gdbarch * gdbarch) [static, read]
Definition at line 1788 of file aarch64-tdep.c.
References append_composite_type_field(), arch_composite_type(), builtin_type::builtin_float, builtin_type::builtin_int32, builtin_type(), builtin_type::builtin_uint32, gdbarch_tdep(), TYPE_CODE_UNION, and gdbarch_tdep::vns_type.
Referenced by aarch64_pseudo_register_type().
static int decode_add_sub_imm (CORE_ADDR addr, uint32_t insn, unsigned * rd, unsigned * rn, int32_t * imm) [static]
Definition at line 219 of file aarch64-tdep.c.
References aarch64_debug, core_addr_to_string_nz(), fprintf_unfiltered(), and gdb_stdlog.
Referenced by aarch64_analyze_prologue().
static int decode_adrp (CORE_ADDR addr, uint32_t insn, unsigned * rd) [static]
Definition at line 267 of file aarch64-tdep.c.
References aarch64_debug, core_addr_to_string_nz(), decode_masked_match(), fprintf_unfiltered(), and gdb_stdlog.
Referenced by aarch64_analyze_prologue().
static int decode_b (CORE_ADDR addr, uint32_t insn, unsigned * link, int32_t * offset) [static]
Definition at line 293 of file aarch64-tdep.c.
References aarch64_debug, core_addr_to_string_nz(), decode_masked_match(), extract_signed_bitfield(), fprintf_unfiltered(), and gdb_stdlog.
Referenced by aarch64_analyze_prologue().
static int decode_bcond (CORE_ADDR addr, uint32_t insn, unsigned * cond, int32_t * offset) [static]
Definition at line 325 of file aarch64-tdep.c.
References aarch64_debug, core_addr_to_string_nz(), decode_masked_match(), extract_signed_bitfield(), fprintf_unfiltered(), and gdb_stdlog.
Referenced by aarch64_analyze_prologue().
static int decode_br (CORE_ADDR addr, uint32_t insn, unsigned * link, unsigned * rn) [static]
Definition at line 352 of file aarch64-tdep.c.
References aarch64_debug, core_addr_to_string_nz(), decode_masked_match(), fprintf_unfiltered(), and gdb_stdlog.
Referenced by aarch64_analyze_prologue().
static int decode_cb (CORE_ADDR addr, uint32_t insn, int * is64, unsigned * op, unsigned * rn, int32_t * offset) [static]
Definition at line 385 of file aarch64-tdep.c.
References aarch64_debug, core_addr_to_string_nz(), decode_masked_match(), extract_signed_bitfield(), fprintf_unfiltered(), and gdb_stdlog.
Referenced by aarch64_analyze_prologue().
static int decode_eret (CORE_ADDR addr, uint32_t insn) [static]
Definition at line 418 of file aarch64-tdep.c.
References aarch64_debug, core_addr_to_string_nz(), fprintf_unfiltered(), and gdb_stdlog.
Referenced by aarch64_analyze_prologue().
static int decode_masked_match (uint32_t insn, uint32_t mask, uint32_t pattern) [static]
Definition at line 205 of file aarch64-tdep.c.
Referenced by decode_adrp(), decode_b(), decode_bcond(), decode_br(), decode_cb(), decode_movz(), decode_orr_shifted_register_x(), decode_ret(), decode_stp_offset(), decode_stp_offset_wb(), decode_stur(), and decode_tb().
static int decode_movz (CORE_ADDR addr, uint32_t insn, unsigned * rd) [static]
Definition at line 440 of file aarch64-tdep.c.
References aarch64_debug, core_addr_to_string_nz(), decode_masked_match(), fprintf_unfiltered(), and gdb_stdlog.
Referenced by aarch64_analyze_prologue().
static int decode_orr_shifted_register_x (CORE_ADDR addr, uint32_t insn, unsigned * rd, unsigned * rn, unsigned * rm, int32_t * imm) [static]
Definition at line 468 of file aarch64-tdep.c.
References aarch64_debug, core_addr_to_string_nz(), decode_masked_match(), fprintf_unfiltered(), and gdb_stdlog.
Referenced by aarch64_analyze_prologue().
static int decode_ret (CORE_ADDR addr, uint32_t insn, unsigned * rn) [static]
Definition at line 498 of file aarch64-tdep.c.
References aarch64_debug, core_addr_to_string_nz(), decode_masked_match(), fprintf_unfiltered(), and gdb_stdlog.
Referenced by aarch64_analyze_prologue().
static int decode_stp_offset (CORE_ADDR addr, uint32_t insn, unsigned * rt1, unsigned * rt2, unsigned * rn, int32_t * imm) [static]
Definition at line 525 of file aarch64-tdep.c.
References aarch64_debug, core_addr_to_string_nz(), decode_masked_match(), extract_signed_bitfield(), fprintf_unfiltered(), and gdb_stdlog.
Referenced by aarch64_analyze_prologue().
static int decode_stp_offset_wb (CORE_ADDR addr, uint32_t insn, unsigned * rt1, unsigned * rt2, unsigned * rn, int32_t * imm) [static]
Definition at line 560 of file aarch64-tdep.c.
References aarch64_debug, core_addr_to_string_nz(), decode_masked_match(), extract_signed_bitfield(), fprintf_unfiltered(), and gdb_stdlog.
Referenced by aarch64_analyze_prologue().
static int decode_stur (CORE_ADDR addr, uint32_t insn, int * is64, unsigned * rt, unsigned * rn, int32_t * imm) [static]
Definition at line 596 of file aarch64-tdep.c.
References aarch64_debug, core_addr_to_string_nz(), decode_masked_match(), extract_signed_bitfield(), fprintf_unfiltered(), and gdb_stdlog.
Referenced by aarch64_analyze_prologue().
static int decode_tb (CORE_ADDR addr, uint32_t insn, unsigned * op, unsigned * bit, unsigned * rt, int32_t * imm) [static]
Definition at line 628 of file aarch64-tdep.c.
References aarch64_debug, core_addr_to_string_nz(), decode_masked_match(), extract_signed_bitfield(), fprintf_unfiltered(), and gdb_stdlog.
Referenced by aarch64_analyze_prologue().
DEF_VEC_O (stack_item_t)
static int32_t extract_signed_bitfield (uint32_t insn, unsigned width, unsigned offset) [static]
Definition at line 188 of file aarch64-tdep.c.
Referenced by decode_b(), decode_bcond(), decode_cb(), decode_stp_offset(), decode_stp_offset_wb(), decode_stur(), and decode_tb().
static int is_hfa (struct type * ty) [static]
Definition at line 1278 of file aarch64-tdep.c.
References check_typedef(), TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_FLT, TYPE_CODE_STRUCT, TYPE_CODE_UNION, TYPE_FIELD_TYPE, TYPE_LENGTH, TYPE_NFIELDS, and TYPE_TARGET_TYPE.
Referenced by aarch64_extract_return_value(), aarch64_push_dummy_call(), aarch64_return_in_memory(), and aarch64_store_return_value().
static int pass_in_v (struct gdbarch * gdbarch, struct regcache * regcache, struct aarch64_call_info * info, const bfd_byte * buf) [static]
Definition at line 1393 of file aarch64-tdep.c.
References aarch64_debug, AARCH64_V0_REGNUM, aarch64_call_info::argnum, fprintf_unfiltered(), gdb_stdlog, gdbarch_byte_order(), gdbarch_register_name(), aarch64_call_info::nsrn, regcache_cooked_write(), and regnum.
Referenced by aarch64_push_dummy_call(), and pass_in_v_or_stack().
static void pass_in_v_or_stack (struct gdbarch * gdbarch, struct regcache * regcache, struct aarch64_call_info * info, struct type * type, const bfd_byte * buf) [static]
Definition at line 1490 of file aarch64-tdep.c.
References pass_in_v(), and pass_on_stack().
Referenced by aarch64_push_dummy_call().
static void pass_in_x (struct gdbarch * gdbarch, struct regcache * regcache, struct aarch64_call_info * info, struct type * type, const bfd_byte * buf) [static]
Definition at line 1351 of file aarch64-tdep.c.
References aarch64_debug, AARCH64_X0_REGNUM, aarch64_call_info::argnum, extract_unsigned_integer(), fprintf_unfiltered(), gdb_stdlog, gdbarch_byte_order(), gdbarch_register_name(), len, aarch64_call_info::ngrn, phex(), regcache_cooked_write_unsigned(), regnum, TYPE_CODE, TYPE_CODE_STRUCT, TYPE_CODE_UNION, TYPE_LENGTH, and X_REGISTER_SIZE.
Referenced by pass_in_x_or_stack().
static void pass_in_x_or_stack (struct gdbarch * gdbarch, struct regcache * regcache, struct aarch64_call_info * info, struct type * type, const bfd_byte * buf) [static]
Definition at line 1466 of file aarch64-tdep.c.
References len, aarch64_call_info::ngrn, pass_in_x(), pass_on_stack(), TYPE_LENGTH, and X_REGISTER_SIZE.
Referenced by aarch64_push_dummy_call().
static void pass_on_stack (struct aarch64_call_info * info, struct type * type, const bfd_byte * buf) [static]
Definition at line 1420 of file aarch64-tdep.c.
References aarch64_debug, aarch64_type_align(), align_up(), aarch64_call_info::argnum, stack_item_t::data, fprintf_unfiltered(), gdb_stdlog, len, stack_item_t::len, aarch64_call_info::nsaa, TYPE_LENGTH, and VEC_safe_push.
Referenced by aarch64_push_dummy_call(), pass_in_v_or_stack(), pass_in_x_or_stack(), sh_push_dummy_call_fpu(), and sh_push_dummy_call_nofpu().
static void show_aarch64_debug (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 171 of file aarch64-tdep.c.
References _, and fprintf_filtered().
Referenced by _initialize_aarch64_tdep().
static struct value* value_of_aarch64_user_reg (struct frame_info * frame, const void * baton) [static, read]
Definition at line 2504 of file aarch64-tdep.c.
References value_of_register().
Referenced by aarch64_gdbarch_init().
Variable Documentation
initialize_file_ftype _initialize_aarch64_tdep
Referenced by _initialize_aarch64_tdep().
int aarch64_debug [static]
Definition at line 168 of file aarch64-tdep.c.
Referenced by _initialize_aarch64_tdep(), aarch64_analyze_prologue(), aarch64_extract_return_value(), aarch64_push_dummy_call(), aarch64_return_value(), aarch64_store_return_value(), decode_add_sub_imm(), decode_adrp(), decode_b(), decode_bcond(), decode_br(), decode_cb(), decode_eret(), decode_movz(), decode_orr_shifted_register_x(), decode_ret(), decode_stp_offset(), decode_stp_offset_wb(), decode_stur(), decode_tb(), pass_in_v(), pass_in_x(), and pass_on_stack().
const gdb_byte aarch64_default_breakpoint[] = {0x00, 0x00, 0x20, 0xd4} [static]
Definition at line 1899 of file aarch64-tdep.c.
Referenced by aarch64_breakpoint_from_pc().
struct frame_base aarch64_normal_base
Initial value:
{
  &aarch64_prologue_unwind,
  aarch64_normal_frame_base,
  aarch64_normal_frame_base,
  aarch64_normal_frame_base
}
Definition at line 1132 of file aarch64-tdep.c.
struct frame_unwind aarch64_prologue_unwind
Initial value:
{
  NORMAL_FRAME,
  default_frame_unwind_stop_reason,
  aarch64_prologue_this_id,
  aarch64_prologue_prev_register,
  NULL,
  default_frame_sniffer
}
Definition at line 1042 of file aarch64-tdep.c.
const char* const aarch64_r_register_names[] [static]
Initial value:
{
  "x0", "x1", "x2", "x3",
  "x4", "x5", "x6", "x7",
  "x8", "x9", "x10", "x11",
  "x12", "x13", "x14", "x15",
  "x16", "x17", "x18", "x19",
  "x20", "x21", "x22", "x23",
  "x24", "x25", "x26", "x27",
  "x28", "x29", "x30", "sp",
  "pc", "cpsr"
}
Definition at line 115 of file aarch64-tdep.c.
Referenced by aarch64_gdbarch_init().
struct { ... } aarch64_register_aliases[] [static]
Referenced by aarch64_gdbarch_init().
struct frame_unwind aarch64_stub_unwind
Initial value:
{
  NORMAL_FRAME,
  default_frame_unwind_stop_reason,
  aarch64_stub_this_id,
  aarch64_prologue_prev_register,
  NULL,
  aarch64_stub_unwind_sniffer
}
Definition at line 1107 of file aarch64-tdep.c.
const char* const aarch64_v_register_names[] [static]
Initial value:
{
  "v0", "v1", "v2", "v3",
  "v4", "v5", "v6", "v7",
  "v8", "v9", "v10", "v11",
  "v12", "v13", "v14", "v15",
  "v16", "v17", "v18", "v19",
  "v20", "v21", "v22", "v23",
  "v24", "v25", "v26", "v27",
  "v28", "v29", "v30", "v31",
  "fpsr",
  "fpcr"
}
Definition at line 131 of file aarch64-tdep.c.
Referenced by aarch64_gdbarch_init().
const char* const name
Definition at line 67 of file aarch64-tdep.c.
Referenced by aarch64_gdbarch_init(), ada_check_typedef(), ada_enum_name(), ada_find_parallel_type(), ada_find_renaming_symbol(), ada_fixup_array_indexes_type(), ada_in_variant(), ada_is_character_type(), ada_is_dispatch_table_ptr_type(), ada_is_ignored_field(), ada_is_interface_tag(), ada_is_others_clause(), ada_is_parent_field(), ada_is_tag_type(), ada_is_wrapper_field(), ada_lookup_simple_minsym(), ada_lookup_symbol_list_worker(), ada_name_prefix_len(), ada_print_type(), ada_search_struct_field(), ada_tag_name(), ada_tag_name_from_tsd(), ada_to_fixed_type_1(), ada_val_print_1(), ada_variant_discrim_name(), ada_variant_discrim_type(), add_bincl_to_list(), add_cmd(), add_file_name(), add_index_entry(), add_packet_config_cmd(), add_path(), add_reg(), add_struct_fields(), add_symbol_file_command(), add_to_method_list(), advance_wild_match(), agent_look_up_symbols(), aggregate_assign_from_choices(), alpha_sigtramp_frame_sniffer(), ambiguous_names_p(), amd64_linux_sigtramp_p(), amd64_sol2_sigtramp_p(), amd64nbsd_sigtramp_p(), amd64obsd_sigtramp_p(), amd64obsd_trapframe_cache(), amd64obsd_trapframe_sniffer(), append_composite_type_field_raw(), append_name(), append_user_reg(), arch_composite_type(), archpy_name(), arm_gdbarch_init(), arm_record_special_symbol(), arm_skip_stub(), ax_print(), block_lookup(), c_name_of_child(), c_type_print_base(), c_type_print_varspec_prefix(), call_function_by_hand(), check_typedef(), chop_separator(), classes_info(), classify_type(), cmdpy_init(), coff_locate_sections(), coff_read_enum_type(), coff_read_struct_type(), coff_symfile_read(), coffstab_build_psymtabs(), complain_about_struct_wipeout(), constraint(), convert_char_literal(), cp_print_class_member(), cp_scan_for_anonymous_namespaces(), cp_set_block_scope(), cp_type_print_derivation_info(), cplus_name_of_child(), cppush(), create_child_with_value(), create_type_unit_group(), d_int_type(), darwin_dump_message(), dbx_free_symfile_info(), dbx_symfile_init(), decode_constrained_packed_array_type(), define_symbol(), demangle_for_lookup(), determine_prefix(), disassemble_command(), disassemble_current_function(), disassemble_dwarf_expression(), do_remote_fileio_request(), do_set_command(), dump_insns(), dw2_expand_symtabs_matching(), dw2_get_file_names_reader(), dwarf2_canonicalize_name(), dwarf2_compute_name(), dwarf_attr_name(), dwarf_form_name(), dwarf_tag_name(), dwarf_type_encoding_name(), elf_rel_plt_read(), elfstab_build_psymtabs(), encode_actions_1(), evaluate_subexp_java(), evaluate_subexp_standard(), fetch_sec_names(), field_alignment(), filter_results(), find_definition(), find_name_end(), find_objc_msgsend(), find_overload_match(), find_size_for_pointer_math(), find_slot_in_mapped_hash(), fnpy_init(), follow_exec(), fprint_target_auxv(), frapy_name(), free_char_ptr_vec(), frv_fdpic_find_canonical_descriptor(), frv_linux_sigtramp_frame_sniffer(), gdb_bfd_close_or_warn(), gdb_bfd_open(), gdb_bfd_stash_filename(), gdb_listfuncs(), gdb_signal_to_name(), GDB_value_struct_elt(), gdbpy_initialize_breakpoints(), gdbpy_initialize_commands(), gdbpy_initialize_parameters(), gdbpy_initialize_types(), gdbpy_lookup_global_symbol(), gdbpy_lookup_symbol(), gen_expr(), generic_elf_osabi_sniff_abi_tag_sections(), get_archive_prefix_len(), get_core_siginfo(), get_java_utf8_name(), get_register_name(), gnuv3_pass_by_reference(), guess_full_die_structure_name(), h8300_print_register(), handle_psymbol_enumerators(), hppa64_hpux_search_dummy_call_sequence(), i386_in_stack_tramp_p(), i386_linux_dwarf_signal_frame_p(), i386_linux_sigtramp_p(), i386_sigtramp_p(), i386_sol2_sigtramp_p(), i386_sol2_static_transform_name(), i386_svr4_sigtramp_p(), i386nto_sigtramp_p(), i386obsd_sigtramp_p(), i386obsd_trapframe_cache(), i386obsd_trapframe_sniffer(), info_common_command_for_block(), info_mach_ports_command(), info_macro_command(), init_sec(), init_type(), inspect_type(), ioctl_with_trace(), is_constructor_name(), is_destructor_name(), is_dynamic_field(), is_nondebugging_type(), is_object_type(), is_operator_name(), is_type_conversion_operator(), is_vtable_name(), iterate_over_all_matching_symtabs(), java_link_class_type(), java_name_of_child(), java_name_of_variable(), java_print_value_fields(), java_type_print_base(), java_type_print_derivation_info(), java_value_print(), linespec_parse_basic(), linux_xfer_osdata_modules(), list_overlays_command(), lookup_minimal_symbol_internal(), lookup_symbol_global(), m32c_skip_prologue(), m32c_skip_trampoline_code(), m32c_virtual_frame_pointer(), m32r_linux_sigtramp_frame_sniffer(), m68hc11_frame_unwind_cache(), m68hc11_initialize_register_info(), m68hc11_print_registers_info(), m68hc11_pseudo_register_read(), m68hc11_pseudo_register_write(), m68hc11_register_name(), m68hc11_which_soft_register(), macho_resolve_oso_sym_with_minsym(), macro_define_command(), macro_undef_command(), make_symbol_overload_list(), make_symbol_overload_list_namespace(), maybe_add_script(), me_module_name(), mep_register_reggroup_p(), mep_skip_prologue(), mi_cmd_trace_define_variable(), mi_cmd_var_create(), mi_cmd_var_delete(), mi_cmd_var_update(), mi_interpreter_init(), microblaze_analyze_prologue(), mips_find_abi_section(), mips_find_long_section(), mips_gdbarch_init(), mips_in_frame_stub(), mips_irix_elf_osabi_sniff_abi_tag_sections(), mips_skip_mips16_trampoline_code(), mn10300_skip_prologue(), monitor_fetch_register(), monitor_open(), monitor_store_register(), msp430_skip_prologue(), mt_register_name(), namespace_name(), new_symbol_full(), new_type(), osf_free_so(), parmpy_init(), parse_number(), parse_old_style_renaming(), parse_partial_symbols(), parse_probes(), parse_symbol(), parse_type(), pascal_type_print_derivation_info(), patch_block_stabs(), patch_opaque_types(), pdc_symbol_addrs(), picobug_dumpregs(), pop_subfile(), ppcfbsd_sigtramp_frame_sniffer(), ppcobsd_sigtramp_frame_sniffer(), prettyfprint_faulttable_entry(), prim_record_minimal_symbol_full(), print_address_symbolic(), print_bfd_section_info(), print_choices(), print_objfile_section_info(), print_range_type(), print_solib_event(), print_source_lines_base(), print_subexp_standard(), print_thread_info(), proc_prettyfprint_flags(), proc_prettyfprint_signal(), proc_prettyfprint_why(), process_coff_symbol(), process_enumeration_scope(), process_linenos(), process_one_symbol(), process_xcoff_symbol(), processAttribute(), processId(), procfs_meminfo(), procfs_pidlist(), psymtab_to_symtab_1(), read_alphacoff_dynamic_symtab(), read_array_type(), read_base_type(), read_cpp_abbrev(), read_dbx_dynamic_symtab(), read_dbx_symtab(), read_enum_type(), read_enumeration_type(), read_func_scope(), read_map(), read_namespace_type(), read_pe_exported_syms(), read_structure_type(), read_subrange_type(), read_symbol_lineno(), read_tilde_fields(), read_type(), read_typedef(), record_minimal_symbol(), recursive_dump_type(), reggroup_new(), reggroups_dump(), register_name_from_keyword(), remote_query_supported(), remove_irrelevant_renamings(), replace_typedefs_qualified_name(), rl78_skip_prologue(), rx_skip_prologue(), safe_symbol_file_add(), scan_xcoff_symtab(), select_source_symtab(), selectors_info(), serial_open(), set_initial_language(), sig_print_info(), signal_catchpoint_print_mention(), signal_catchpoint_print_one(), skip_function_command(), skip_prologue(), skip_prologue_function(), skip_prologue_sal(), som_open_symbol_file_object(), sparc32_sol2_sigtramp_frame_sniffer(), sparc32nbsd_sigcontext_frame_sniffer(), sparc32obsd_sigtramp_frame_sniffer(), sparc64_sol2_sigtramp_frame_sniffer(), sparc64fbsd_sigtramp_frame_sniffer(), sparc64nbsd_sigtramp_frame_sniffer(), sparc64obsd_sigtramp_frame_sniffer(), sparc64obsd_trapframe_sniffer(), sparc_sol2_static_transform_name(), spu_gdbarch_init(), stabsect_build_psymtabs(), step_once(), symbol_file_add_from_memory(), symbol_file_add_with_addrs(), symbol_file_command(), symbol_set_demangled_name(), symbol_set_names(), symfile_bfd_open(), target_is_native(), tdesc_named_type(), thpy_get_name(), thpy_set_name(), to_fixed_range_type(), trace_variable_command(), tui_get_function_from_frame(), tui_set_source_content(), tui_show_register_group(), tui_win_name(), tvariables_info_1(), type_from_class(), type_name_no_tag_or_error(), unimplemented(), update_dynamic_varobj_children(), update_thread_private_data_name(), variable_create(), variable_obj_command(), vaxobsd_sigtramp_sniffer(), vb_match(), VEC(), watch_command_1(), wild_match(), wrap_value_struct_elt(), write_object_renaming(), xcoff_initial_scan(), xget_renaming_scope(), xtensa_register_type(), and yylex().
int regnum
Definition at line 68 of file aarch64-tdep.c.
Referenced by aarch64_gdbarch_init(), aarch64_pseudo_read_value(), alphabsd_supply_pcb(), amd64_dwarf_reg_to_regnum(), amd64_native_gregset_reg_offset(), amd64_pseudo_register_read_value(), amd64_push_arguments(), amd64_return_value(), amd64_windows_return_value(), amd64obsd_supply_pcb(), arm_gdbarch_init(), arm_push_dummy_call(), arm_register_sim_regno(), arm_return_value(), armobsd_sigframe_init(), avr_push_dummy_call(), avr_register_name(), cris_dwarf2_reg_to_regnum(), default_value_from_register(), do_ppc_sysv_return_value(), dwarf2_compile_cfa_to_ax(), dwarf2_frame_adjust_regnum(), dwarf2_frame_cache(), dwarf2_frame_prev_register(), dwarf_expr_read_reg(), frv_linux_sigtramp_frame_cache(), gdb_reggroup(), get_register(), hppa64_push_dummy_call(), hppa64_return_value(), hppabsd_supply_fpregset(), hppabsd_supply_gregset(), hppanbsd_supply_fpregset(), hppanbsd_supply_gregset(), i386_convert_register_p(), i386_next_regnum(), i386_process_record(), i386_pseudo_register_read_value(), i386bsd_supply_gregset(), i387_print_float_info(), ia64_frame_prev_register(), ia64_hpux_fetch_register(), ia64_hpux_get_register_from_save_state_t(), ia64_hpux_store_register(), ia64_sigtramp_frame_prev_register(), iq2000_register_name(), legacy_register_sim_regno(), locexpr_regname(), m32c_register_reggroup_p(), m32r_linux_sigtramp_frame_cache(), m68k_register_name(), m68kbsd_supply_fpregset(), m68kbsd_supply_gregset(), m68kbsd_supply_pcb(), m68kobsd_sigtramp_cache_init(), m88k_analyze_prologue(), m88k_frame_cache(), m88k_register_name(), m88k_store_arguments(), m88kbsd_supply_gregset(), map_arg_registers(), map_regcache_remote_table(), mi_cmd_data_list_changed_registers(), mi_cmd_data_list_register_names(), mi_cmd_data_list_register_values(), mi_cmd_data_write_register_values(), mi_cmd_trace_frame_collected(), microblaze_linux_sigtramp_cache(), microblaze_register_name(), mips64obsd_sigframe_init(), mips64obsd_supply_gregset(), mips_dwarf_dwarf2_ecoff_reg_to_regnum(), mips_eabi_return_value(), mips_gdbarch_init(), mips_n32n64_return_value(), mips_o32_return_value(), mips_o64_return_value(), mips_read_pc(), mips_register_sim_regno(), mips_stab_reg_to_regnum(), mips_write_pc(), moxie_analyze_prologue(), msp430_register_sim_regno(), mt_frame_unwind_cache(), mt_register_name(), nto_reg_offset(), one2one_register_sim_regno(), packet_reg_from_regnum(), pass_in_v(), pass_in_x(), ppc64_sysv_abi_push_dummy_call(), ppc64_sysv_abi_return_value(), ppc_linux_sigtramp_cache(), ppc_ravenscar_generic_store_registers(), ppc_sysv_abi_push_dummy_call(), ppcfbsd_sigtramp_frame_cache(), ppcfbsd_supply_pcb(), ppcnbsd_sigtramp_cache_init(), ppcobsd_sigtramp_frame_cache(), ppcobsd_supply_pcb(), print_float_info(), print_gp_register_row(), print_vector_info(), read_frame_register_value(), read_reg(), record_full_core_open_1(), record_full_reg_alloc(), record_full_restore(), record_full_save(), regcache_cooked_read(), regcache_cooked_read_value(), regcache_dump(), regcache_invalidate(), regcache_raw_collect(), regcache_raw_read(), regcache_raw_supply(), regcache_raw_write(), regcache_register_status(), regcache_restore(), regcache_save(), register_buffer(), register_size(), register_type(), registers_info(), remote_register_number_and_offset(), rl78_register_sim_regno(), score3_register_name(), score7_linux_supply_gregset(), score7_register_name(), score_return_value(), sh64_do_fp_register(), sh64_push_dummy_call(), sh64_store_return_value(), sh_extract_return_value_fpu(), sh_extract_return_value_nofpu(), sh_store_return_value_fpu(), sh_store_return_value_nofpu(), sparc32_frame_cache(), sparc32_linux_sigframe_init(), sparc32_register_name(), sparc32_skip_prologue(), sparc32_sol2_sigtramp_frame_cache(), sparc32_store_arguments(), sparc32nbsd_sigcontext_saved_regs(), sparc64_extract_floating_fields(), sparc64_linux_sigframe_init(), sparc64_register_name(), sparc64_sol2_sigtramp_frame_cache(), sparc64_store_arguments(), sparc64_store_floating_fields(), sparc64fbsd_sigtramp_frame_cache(), sparc64nbsd_sigcontext_saved_regs(), sparc64nbsd_supply_pcb(), sparc64obsd_trapframe_cache(), sparc_analyze_prologue(), sparc_ravenscar_store_registers(), spu_push_dummy_call(), tdesc_create_reg(), tilegx_analyze_prologue(), tilegx_extract_return_value(), tilegx_register_name(), tilegx_store_return_value(), trad_frame_alloc_saved_regs(), trad_frame_set_reg_addr(), trad_frame_set_reg_realreg(), trad_frame_set_unknown(), trad_frame_set_value(), tui_show_register_group(), v850_extract_return_value(), v850_register_name(), v850_store_return_value(), v850e2_register_name(), v850e3v5_register_name(), v850e_register_name(), value_fetch_lazy(), value_from_register(), value_of_register_lazy(), vax_frame_cache(), vax_register_name(), vaxbsd_supply_gregset(), vaxbsd_supply_pcb(), xstormy16_analyze_prologue(), xstormy16_extract_return_value(), xstormy16_register_name(), xstormy16_store_return_value(), xtensa_frame_cache(), xtensa_frame_prev_register(), xtensa_pseudo_register_read(), xtensa_pseudo_register_write(), xtensa_reg_to_regnum(), xtensa_register_name(), xtensa_register_reggroup_p(), xtensa_register_type(), and xtensa_window_interrupt_frame_cache().