GDB (xrefs): /home/stan/gdb/src/gdb/aarch64-linux-tdep.c File Reference
/home/stan/gdb/src/gdb/aarch64-linux-tdep.c File Reference
#include "defs.h"
#include "gdbarch.h"
#include "glibc-tdep.h"
#include "linux-tdep.h"
#include "aarch64-tdep.h"
#include "aarch64-linux-tdep.h"
#include "osabi.h"
#include "solib-svr4.h"
#include "symtab.h"
#include "tramp-frame.h"
#include "trad-frame.h"
#include "inferior.h"
#include "regcache.h"
#include "regset.h"
Defines
#define AARCH64_LINUX_SIZEOF_GREGSET (34 * X_REGISTER_SIZE)
#define AARCH64_LINUX_SIZEOF_FPREGSET (33 * V_REGISTER_SIZE)
#define AARCH64_SIGCONTEXT_REG_SIZE 8
#define AARCH64_RT_SIGFRAME_UCONTEXT_OFFSET 128
#define AARCH64_UCONTEXT_SIGCONTEXT_OFFSET 176
#define AARCH64_SIGCONTEXT_XO_OFFSET 8
Functions
static void aarch64_linux_sigframe_init (const struct tramp_frame *self, struct frame_info *this_frame, struct trad_frame_cache *this_cache, CORE_ADDR func)
void aarch64_linux_supply_gregset (struct regcache *regcache, const gdb_byte *gregs_buf)
static void supply_gregset_from_core (const struct regset *regset, struct regcache *regcache, int regnum, const void *regbuf, size_t len)
void aarch64_linux_supply_fpregset (struct regcache *regcache, const gdb_byte *fpregs_buf)
static void supply_fpregset_from_core (const struct regset *regset, struct regcache *regcache, int regnum, const void *regbuf, size_t len)
static struct regset * aarch64_linux_regset_from_core_section (struct gdbarch *gdbarch, const char *sect_name, size_t sect_size)
static void aarch64_linux_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
void _initialize_aarch64_linux_tdep (void)
Variables
static struct tramp_frame aarch64_linux_rt_sigframe
initialize_file_ftype _initialize_aarch64_linux_tdep
Define Documentation
#define AARCH64_LINUX_SIZEOF_FPREGSET (33 * V_REGISTER_SIZE)
Definition at line 46 of file aarch64-linux-tdep.c.
Referenced by aarch64_linux_regset_from_core_section().
#define AARCH64_LINUX_SIZEOF_GREGSET (34 * X_REGISTER_SIZE)
Definition at line 41 of file aarch64-linux-tdep.c.
Referenced by aarch64_linux_regset_from_core_section().
#define AARCH64_RT_SIGFRAME_UCONTEXT_OFFSET 128
Definition at line 129 of file aarch64-linux-tdep.c.
Referenced by aarch64_linux_sigframe_init().
#define AARCH64_SIGCONTEXT_REG_SIZE 8
Definition at line 128 of file aarch64-linux-tdep.c.
Referenced by aarch64_linux_sigframe_init().
#define AARCH64_SIGCONTEXT_XO_OFFSET 8
Definition at line 131 of file aarch64-linux-tdep.c.
Referenced by aarch64_linux_sigframe_init().
#define AARCH64_UCONTEXT_SIGCONTEXT_OFFSET 176
Definition at line 130 of file aarch64-linux-tdep.c.
Referenced by aarch64_linux_sigframe_init().
Function Documentation
void _initialize_aarch64_linux_tdep (void)
Definition at line 299 of file aarch64-linux-tdep.c.
References _initialize_aarch64_linux_tdep, aarch64_linux_init_abi(), GDB_OSABI_LINUX, and gdbarch_register_osabi().
static void aarch64_linux_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch) [static]
Definition at line 267 of file aarch64-linux-tdep.c.
References aarch64_linux_regset_from_core_section(), find_solib_trampoline_target(), gdbarch_tdep(), gdbarch_tdep::jb_pc, linux_get_siginfo_type(), linux_init_abi(), gdbarch_tdep::lowest_pc, set_gdbarch_fetch_tls_load_module_address(), set_gdbarch_get_siginfo_type(), set_gdbarch_regset_from_core_section(), set_gdbarch_skip_trampoline_code(), set_solib_svr4_fetch_link_map_offsets(), svr4_fetch_objfile_link_map(), svr4_lp64_fetch_link_map_offsets(), and tramp_frame_prepend_unwinder().
Referenced by _initialize_aarch64_linux_tdep().
static struct regset* aarch64_linux_regset_from_core_section (struct gdbarch * gdbarch, const char * sect_name, size_t sect_size) [static, read]
Definition at line 240 of file aarch64-linux-tdep.c.
References AARCH64_LINUX_SIZEOF_FPREGSET, AARCH64_LINUX_SIZEOF_GREGSET, gdbarch_tdep::fpregset, gdbarch_tdep(), gdbarch_tdep::gregset, regset_alloc(), supply_fpregset_from_core(), and supply_gregset_from_core().
Referenced by aarch64_linux_init_abi().
static void aarch64_linux_sigframe_init (const struct tramp_frame * self, struct frame_info * this_frame, struct trad_frame_cache * this_cache, CORE_ADDR func) [static]
Definition at line 136 of file aarch64-linux-tdep.c.
References AARCH64_FP_REGNUM, AARCH64_LR_REGNUM, AARCH64_PC_REGNUM, AARCH64_RT_SIGFRAME_UCONTEXT_OFFSET, AARCH64_SIGCONTEXT_REG_SIZE, AARCH64_SIGCONTEXT_XO_OFFSET, AARCH64_SP_REGNUM, AARCH64_UCONTEXT_SIGCONTEXT_OFFSET, AARCH64_X0_REGNUM, frame_id_build(), get_frame_arch(), get_frame_register_unsigned(), sp, trad_frame_set_id(), and trad_frame_set_reg_addr().
void aarch64_linux_supply_fpregset (struct regcache * regcache, const gdb_byte * fpregs_buf)
Definition at line 211 of file aarch64-linux-tdep.c.
References AARCH64_FPCR_REGNUM, AARCH64_FPSR_REGNUM, AARCH64_V0_REGNUM, AARCH64_V31_REGNUM, regcache_raw_supply(), and V_REGISTER_SIZE.
Referenced by supply_fpregset(), and supply_fpregset_from_core().
void aarch64_linux_supply_gregset (struct regcache * regcache, const gdb_byte * gregs_buf)
Definition at line 186 of file aarch64-linux-tdep.c.
References AARCH64_CPSR_REGNUM, AARCH64_X0_REGNUM, regcache_raw_supply(), and X_REGISTER_SIZE.
Referenced by supply_gregset(), and supply_gregset_from_core().
static void supply_fpregset_from_core (const struct regset * regset, struct regcache * regcache, int regnum, const void * regbuf, size_t len) [static]
Definition at line 230 of file aarch64-linux-tdep.c.
References aarch64_linux_supply_fpregset().
Referenced by aarch64_linux_regset_from_core_section().
static void supply_gregset_from_core (const struct regset * regset, struct regcache * regcache, int regnum, const void * regbuf, size_t len) [static]
Definition at line 200 of file aarch64-linux-tdep.c.
References aarch64_linux_supply_gregset().
Referenced by aarch64_linux_regset_from_core_section().
Variable Documentation
initialize_file_ftype _initialize_aarch64_linux_tdep
Referenced by _initialize_aarch64_linux_tdep().
struct tramp_frame aarch64_linux_rt_sigframe [static]
Initial value:
{
  SIGTRAMP_FRAME,
  4,
  {
    {0xd2801168, -1},
    {0xd4000001, -1},
    {TRAMP_SENTINEL_INSN, -1}
  },
  aarch64_linux_sigframe_init
}
Definition at line 165 of file aarch64-linux-tdep.c.