GDB (xrefs): /home/stan/gdb/linux/gdb/ada-exp.c File Reference
/home/stan/gdb/linux/gdb/ada-exp.c File Reference
#include "defs.h"
#include "gdb_string.h"
#include <ctype.h>
#include "expression.h"
#include "value.h"
#include "parser-defs.h"
#include "language.h"
#include "ada-lang.h"
#include "bfd.h"
#include "symfile.h"
#include "objfiles.h"
#include "frame.h"
#include "block.h"
#include "ada-lex.c"
Classes
struct name_info
union YYSTYPE
union yyalloc
Defines
#define YYBISON 1
#define YYBISON_VERSION "2.5"
#define YYSKELETON_NAME "yacc.c"
#define YYPURE 0
#define YYPUSH 0
#define YYPULL 1
#define YYLSP_NEEDED 0
#define parse_type builtin_type (parse_gdbarch)
#define yymaxdepth ada_maxdepth
#define yyparse _ada_parse /* ada_parse calls this after initialization */
#define yylex ada_lex
#define yyerror ada_error
#define yylval ada_lval
#define yychar ada_char
#define yydebug ada_debug
#define yypact ada_pact
#define yyr1 ada_r1
#define yyr2 ada_r2
#define yydef ada_def
#define yychk ada_chk
#define yypgo ada_pgo
#define yyact ada_act
#define yyexca ada_exca
#define yyerrflag ada_errflag
#define yynerrs ada_nerrs
#define yyps ada_ps
#define yypv ada_pv
#define yys ada_s
#define yy_yys ada_yys
#define yystate ada_state
#define yytmp ada_tmp
#define yyv ada_v
#define yy_yyv ada_yyv
#define yyval ada_val
#define yylloc ada_lloc
#define yyreds ada_reds /* With YYDEBUG defined */
#define yytoks ada_toks /* With YYDEBUG defined */
#define yyname ada_name /* With YYDEBUG defined */
#define yyrule ada_rule /* With YYDEBUG defined */
#define yyss ada_yyss
#define yysslim ada_yysslim
#define yyssp ada_yyssp
#define yystacksize ada_yystacksize
#define yyvs ada_yyvs
#define yyvsp ada_yyvsp
#define YYDEBUG 1 /* Default to yydebug support */
#define YYFPRINTF parser_fprintf
#define YYERROR_VERBOSE 0
#define YYTOKEN_TABLE 0
#define YYTOKENTYPE
#define INT 258
#define NULL_PTR 259
#define CHARLIT 260
#define FLOAT 261
#define TRUEKEYWORD 262
#define FALSEKEYWORD 263
#define COLONCOLON 264
#define STRING 265
#define NAME 266
#define DOT_ID 267
#define DOT_ALL 268
#define SPECIAL_VARIABLE 269
#define ASSIGN 270
#define ELSE 271
#define THEN 272
#define XOR 273
#define OR 274
#define _AND_ 275
#define DOTDOT 276
#define IN 277
#define GEQ 278
#define LEQ 279
#define NOTEQUAL 280
#define UNARY 281
#define REM 282
#define MOD 283
#define NOT 284
#define ABS 285
#define STARSTAR 286
#define VAR 287
#define ARROW 288
#define TICK_LENGTH 289
#define TICK_LAST 290
#define TICK_FIRST 291
#define TICK_ADDRESS 292
#define TICK_ACCESS 293
#define TICK_MODULUS 294
#define TICK_MIN 295
#define TICK_MAX 296
#define TICK_VAL 297
#define TICK_TAG 298
#define TICK_SIZE 299
#define TICK_RANGE 300
#define TICK_POS 301
#define NEW 302
#define OTHERS 303
#define YYSTYPE_IS_TRIVIAL 1
#define yystype YYSTYPE /* obsolescent; will be withdrawn */
#define YYSTYPE_IS_DECLARED 1
#define YYSIZE_T unsigned int
#define YYSIZE_MAXIMUM ((YYSIZE_T) -1)
#define YY_(msgid) msgid
#define YYUSE(e) ((void) (e))
#define YYID(n) (n)
#define YYSTACK_ALLOC YYMALLOC
#define YYSTACK_FREE YYFREE
#define YYSTACK_ALLOC_MAXIMUM YYSIZE_MAXIMUM
#define YYMALLOC xmalloc
#define YYFREE xfree
#define YYSTACK_GAP_MAXIMUM (sizeof (union yyalloc) - 1)
#define YYSTACK_BYTES(N)
#define YYCOPY_NEEDED 1
#define YYSTACK_RELOCATE(Stack_alloc, Stack)
#define YYCOPY(To, From, Count)
#define YYFINAL 57
#define YYLAST 770
#define YYNTOKENS 69
#define YYNNTS 31
#define YYNRULES 122
#define YYNSTATES 233
#define YYUNDEFTOK 2
#define YYMAXUTOK 303
#define YYTRANSLATE(YYX) ((unsigned int) (YYX) <= YYMAXUTOK ? yytranslate[YYX] : YYUNDEFTOK)
#define YYPACT_NINF -104
#define YYTABLE_NINF -83
#define yypact_value_is_default(yystate) ((yystate) == (-104))
#define yytable_value_is_error(yytable_value) YYID (0)
#define yyerrok (yyerrstatus = 0)
#define yyclearin (yychar = YYEMPTY)
#define YYEMPTY (-2)
#define YYEOF 0
#define YYACCEPT goto yyacceptlab
#define YYABORT goto yyabortlab
#define YYERROR goto yyerrorlab
#define YYFAIL goto yyerrlab
#define YYRECOVERING() (!!yyerrstatus)
#define YYBACKUP(Token, Value)
#define YYTERROR 1
#define YYERRCODE 256
#define YYRHSLOC(Rhs, K) ((Rhs)[K])
#define YYLLOC_DEFAULT(Current, Rhs, N)
#define YY_LOCATION_PRINT(File, Loc) ((void) 0)
#define YYLEX yylex ()
#define YYDPRINTF(Args)
#define YY_SYMBOL_PRINT(Title, Type, Value, Location)
#define YY_STACK_PRINT(Bottom, Top)
#define YY_REDUCE_PRINT(Rule)
#define YYINITDEPTH 200
#define YYMAXDEPTH 10000
#define YYPOPSTACK(N) (yyvsp -= (N), yyssp -= (N))
#define yy_create_buffer ada_yy_create_buffer
#define yy_delete_buffer ada_yy_delete_buffer
#define yy_init_buffer ada_yy_init_buffer
#define yy_load_buffer_state ada_yy_load_buffer_state
#define yy_switch_to_buffer ada_yy_switch_to_buffer
#define yyrestart ada_yyrestart
#define yytext ada_yytext
#define yywrap ada_yywrap
#define qsort __qsort__dummy
Typedefs
typedef union YYSTYPE YYSTYPE
typedef unsigned char yytype_uint8
typedef short int yytype_int8
typedef unsigned short int yytype_uint16
typedef short int yytype_int16
Enumerations
enum yytokentype {
INT = 258, NULL_PTR = 259, CHARLIT = 260, FLOAT = 261,
TRUEKEYWORD = 262, FALSEKEYWORD = 263, COLONCOLON = 264, STRING = 265,
NAME = 266, DOT_ID = 267, DOT_ALL = 268, SPECIAL_VARIABLE = 269,
ASSIGN = 270, ELSE = 271, THEN = 272, XOR = 273,
OR = 274, _AND_ = 275, DOTDOT = 276, IN = 277,
GEQ = 278, LEQ = 279, NOTEQUAL = 280, UNARY = 281,
REM = 282, MOD = 283, NOT = 284, ABS = 285,
STARSTAR = 286, VAR = 287, ARROW = 288, TICK_LENGTH = 289,
TICK_LAST = 290, TICK_FIRST = 291, TICK_ADDRESS = 292, TICK_ACCESS = 293,
TICK_MODULUS = 294, TICK_MIN = 295, TICK_MAX = 296, TICK_VAL = 297,
TICK_TAG = 298, TICK_SIZE = 299, TICK_RANGE = 300, TICK_POS = 301,
NEW = 302, OTHERS = 303, INT = 258, FLOAT = 259,
DECFLOAT = 260, STRING = 261, NSSTRING = 262, SELECTOR = 263,
CHAR = 264, NAME = 265, UNKNOWN_CPP_NAME = 266, COMPLETE = 267,
TYPENAME = 268, CLASSNAME = 269, OBJC_LBRAC = 270, NAME_OR_INT = 271,
OPERATOR = 272, STRUCT = 273, CLASS = 274, UNION = 275,
ENUM = 276, SIZEOF = 277, UNSIGNED = 278, COLONCOLON = 279,
TEMPLATE = 280, ERROR = 281, NEW = 282, DELETE = 283,
REINTERPRET_CAST = 284, DYNAMIC_CAST = 285, STATIC_CAST = 286, CONST_CAST = 287,
ENTRY = 288, TYPEOF = 289, DECLTYPE = 290, TYPEID = 291,
SIGNED_KEYWORD = 292, LONG = 293, SHORT = 294, INT_KEYWORD = 295,
CONST_KEYWORD = 296, VOLATILE_KEYWORD = 297, DOUBLE_KEYWORD = 298, VARIABLE = 299,
ASSIGN_MODIFY = 300, TRUEKEYWORD = 301, FALSEKEYWORD = 302, ABOVE_COMMA = 303,
OROR = 304, ANDAND = 305, NOTEQUAL = 306, EQUAL = 307,
GEQ = 308, LEQ = 309, RSH = 310, LSH = 311,
DECREMENT = 312, INCREMENT = 313, UNARY = 314, DOT_STAR = 315,
ARROW_STAR = 316, ARROW = 317, BLOCKNAME = 318, FILENAME = 319,
DOTDOTDOT = 320, INT = 258, FLOAT = 259, NAME = 260,
STRUCT = 261, CLASS = 262, UNION = 263, ENUM = 264,
SIZEOF = 265, UNSIGNED = 266, COLONCOLON = 267, TEMPLATE = 268,
ERROR = 269, NEW = 270, DELETE = 271, OPERATOR = 272,
STATIC_CAST = 273, REINTERPRET_CAST = 274, DYNAMIC_CAST = 275, SIGNED_KEYWORD = 276,
LONG = 277, SHORT = 278, INT_KEYWORD = 279, CONST_KEYWORD = 280,
VOLATILE_KEYWORD = 281, DOUBLE_KEYWORD = 282, BOOL = 283, ELLIPSIS = 284,
RESTRICT = 285, VOID = 286, FLOAT_KEYWORD = 287, CHAR = 288,
WCHAR_T = 289, ASSIGN_MODIFY = 290, TRUEKEYWORD = 291, FALSEKEYWORD = 292,
DEMANGLER_SPECIAL = 293, CONSTRUCTION_VTABLE = 294, CONSTRUCTION_IN = 295, OROR = 296,
ANDAND = 297, NOTEQUAL = 298, EQUAL = 299, GEQ = 300,
LEQ = 301, RSH = 302, LSH = 303, DECREMENT = 304,
INCREMENT = 305, UNARY = 306, ARROW = 307, INT = 258,
FLOAT = 259, STRING_LITERAL = 260, BOOLEAN_LITERAL = 261, NAME = 262,
TYPENAME = 263, NAME_OR_INT = 264, SIZEOF = 265, ERROR = 266,
INT_KEYWORD = 267, INT_S2_KEYWORD = 268, LOGICAL_S1_KEYWORD = 269, LOGICAL_S2_KEYWORD = 270,
LOGICAL_S8_KEYWORD = 271, LOGICAL_KEYWORD = 272, REAL_KEYWORD = 273, REAL_S8_KEYWORD = 274,
REAL_S16_KEYWORD = 275, COMPLEX_S8_KEYWORD = 276, COMPLEX_S16_KEYWORD = 277, COMPLEX_S32_KEYWORD = 278,
BOOL_AND = 279, BOOL_OR = 280, BOOL_NOT = 281, CHARACTER = 282,
VARIABLE = 283, ASSIGN_MODIFY = 284, ABOVE_COMMA = 285, NOTEQUAL = 286,
EQUAL = 287, GEQ = 288, LEQ = 289, GREATERTHAN = 290,
LESSTHAN = 291, RSH = 292, LSH = 293, STARSTAR = 294,
UNARY = 295, INT = 258, FLOAT = 259, RAW_STRING = 260,
STRING = 261, CHAR = 262, NAME = 263, TYPENAME = 264,
COMPLETE = 265, NAME_OR_INT = 266, TRUE_KEYWORD = 267, FALSE_KEYWORD = 268,
STRUCT_KEYWORD = 269, INTERFACE_KEYWORD = 270, TYPE_KEYWORD = 271, CHAN_KEYWORD = 272,
SIZEOF_KEYWORD = 273, LEN_KEYWORD = 274, CAP_KEYWORD = 275, NEW_KEYWORD = 276,
IOTA_KEYWORD = 277, NIL_KEYWORD = 278, CONST_KEYWORD = 279, DOTDOTDOT = 280,
ENTRY = 281, ERROR = 282, BYTE_KEYWORD = 283, DOLLAR_VARIABLE = 284,
ASSIGN_MODIFY = 285, ABOVE_COMMA = 286, OROR = 287, ANDAND = 288,
ANDNOT = 289, NOTEQUAL = 290, EQUAL = 291, GEQ = 292,
LEQ = 293, RSH = 294, LSH = 295, DECREMENT = 296,
INCREMENT = 297, UNARY = 298, LEFT_ARROW = 299, INTEGER_LITERAL = 258,
FLOATING_POINT_LITERAL = 259, IDENTIFIER = 260, STRING_LITERAL = 261, BOOLEAN_LITERAL = 262,
TYPENAME = 263, NAME_OR_INT = 264, ERROR = 265, LONG = 266,
SHORT = 267, BYTE = 268, INT = 269, CHAR = 270,
BOOLEAN = 271, DOUBLE = 272, FLOAT = 273, VARIABLE = 274,
ASSIGN_MODIFY = 275, SUPER = 276, NEW = 277, OROR = 278,
ANDAND = 279, NOTEQUAL = 280, EQUAL = 281, GEQ = 282,
LEQ = 283, RSH = 284, LSH = 285, DECREMENT = 286,
INCREMENT = 287, INT = 258, HEX = 259, ERROR = 260,
UINT = 261, M2_TRUE = 262, M2_FALSE = 263, CHAR = 264,
FLOAT = 265, STRING = 266, NAME = 267, BLOCKNAME = 268,
IDENT = 269, VARNAME = 270, TYPENAME = 271, SIZE = 272,
CAP = 273, ORD = 274, HIGH = 275, ABS = 276,
MIN_FUNC = 277, MAX_FUNC = 278, FLOAT_FUNC = 279, VAL = 280,
CHR = 281, ODD = 282, TRUNC = 283, TSIZE = 284,
INC = 285, DEC = 286, INCL = 287, EXCL = 288,
COLONCOLON = 289, INTERNAL_VAR = 290, ABOVE_COMMA = 291, ASSIGN = 292,
IN = 293, NOTEQUAL = 294, GEQ = 295, LEQ = 296,
OROR = 297, LOGICAL_AND = 298, MOD = 299, DIV = 300,
UNARY = 301, DOT = 302, NOT = 303, QID = 304,
INT = 258, FLOAT = 259, STRING = 260, FIELDNAME = 261,
COMPLETE = 262, NAME = 263, TYPENAME = 264, NAME_OR_INT = 265,
STRUCT = 266, CLASS = 267, SIZEOF = 268, COLONCOLON = 269,
ERROR = 270, VARIABLE = 271, THIS = 272, TRUEKEYWORD = 273,
FALSEKEYWORD = 274, ABOVE_COMMA = 275, ASSIGN = 276, NOT = 277,
OR = 278, XOR = 279, ANDAND = 280, NOTEQUAL = 281,
GEQ = 282, LEQ = 283, MOD = 284, DIV = 285,
RSH = 286, LSH = 287, DECREMENT = 288, INCREMENT = 289,
UNARY = 290, ARROW = 291, BLOCKNAME = 292
}
Functions
int yyparse (void)
static int yylex (void)
void yyerror (char *)
static void write_int (LONGEST, struct type *)
static void write_object_renaming (const struct block *, const char *, int, const char *, int)
static struct type * write_var_or_type (const struct block *, struct stoken)
static void write_name_assoc (struct stoken)
static void write_exp_op_with_string (enum exp_opcode, struct stoken)
static struct block * block_lookup (struct block *, const char *)
static LONGEST convert_char_literal (struct type *, LONGEST)
static void write_ambiguous_var (const struct block *, char *, int)
static struct type * type_int (void)
static struct type * type_long (void)
static struct type * type_long_long (void)
static struct type * type_float (void)
static struct type * type_double (void)
static struct type * type_long_double (void)
static struct type * type_char (void)
static struct type * type_boolean (void)
static struct type * type_system_address (void)
static void yy_symbol_value_print (FILE *yyoutput, int yytype, YYSTYPE const *const yyvaluep)
static void yy_symbol_print (FILE *yyoutput, int yytype, YYSTYPE const *const yyvaluep)
static void yy_stack_print (yytype_int16 *yybottom, yytype_int16 *yytop)
static void yy_reduce_print (YYSTYPE *yyvsp, int yyrule)
static void yydestruct (char *yymsg, int yytype, YYSTYPE *yyvaluep) const
int ada_parse (void)
static void write_var_from_sym (const struct block *orig_left_context, const struct block *block, struct symbol *sym)
static struct symbol * select_possible_type_sym (struct ada_symbol_info *syms, int nsyms)
static struct type * find_primitive_type (char *name)
static int chop_selector (char *name, int end)
static char * chop_separator (char *name)
static void write_selectors (char *sels)
static int ada_nget_field_index (const struct type *type, const char *field_name0, int field_name_len, int maybe_missing)
static struct type * get_symbol_field_type (struct symbol *sym, char *encoded_field_name)
void _initialize_ada_exp (void)
Variables
static struct stoken empty_stoken = { "", 0 }
static struct type * type_qualifier
static const yytype_uint8 yytranslate []
static const yytype_uint16 yyprhs []
static const yytype_int8 yyrhs []
static const yytype_uint16 yyrline []
static const char *const yytname []
static const yytype_uint8 yyr1 []
static const yytype_uint8 yyr2 []
static const yytype_uint8 yydefact []
static const yytype_int16 yydefgoto []
static const yytype_int16 yypact []
static const yytype_int8 yypgoto []
static const yytype_int16 yytable []
static const yytype_int16 yycheck []
static const yytype_uint8 yystos []
int yydebug
int yychar
YYSTYPE yylval
int yynerrs
static struct obstack temp_parse_space
initialize_file_ftype _initialize_ada_exp
Define Documentation
#define _AND_ 275
Definition at line 293 of file ada-exp.c.
#define ABS 285
Definition at line 303 of file ada-exp.c.
#define ARROW 288
Definition at line 306 of file ada-exp.c.
Referenced by lex_one_token(), and yylex().
#define ASSIGN 270
Definition at line 288 of file ada-exp.c.
#define CHARLIT 260
Definition at line 278 of file ada-exp.c.
#define COLONCOLON 264
Definition at line 282 of file ada-exp.c.
Referenced by yylex().
#define DOT_ALL 268
Definition at line 286 of file ada-exp.c.
#define DOT_ID 267
Definition at line 285 of file ada-exp.c.
#define DOTDOT 276
Definition at line 294 of file ada-exp.c.
#define ELSE 271
Definition at line 289 of file ada-exp.c.
#define FALSEKEYWORD 263
Definition at line 281 of file ada-exp.c.
Referenced by yylex().
#define FLOAT 261
Definition at line 279 of file ada-exp.c.
Referenced by parse_number(), processReal(), and yylex().
#define GEQ 278
Definition at line 296 of file ada-exp.c.
Referenced by yylex().
#define IN 277
Definition at line 295 of file ada-exp.c.
#define INT 258
Definition at line 276 of file ada-exp.c.
Referenced by c_print_token(), classify_name(), parse_number(), processInt(), and yylex().
#define LEQ 279
Definition at line 297 of file ada-exp.c.
Referenced by yylex().
#define MOD 283
Definition at line 301 of file ada-exp.c.
#define NAME 266
Definition at line 284 of file ada-exp.c.
#define NEW 302
Definition at line 320 of file ada-exp.c.
Referenced by yylex().
#define NOT 284
Definition at line 302 of file ada-exp.c.
#define NOTEQUAL 280
Definition at line 298 of file ada-exp.c.
Referenced by yylex().
#define NULL_PTR 259
Definition at line 277 of file ada-exp.c.
#define OR 274
Definition at line 292 of file ada-exp.c.
#define OTHERS 303
Definition at line 321 of file ada-exp.c.
#define parse_type builtin_type (parse_gdbarch)
Definition at line 86 of file ada-exp.c.
Referenced by type_boolean(), type_double(), type_float(), type_int(), type_long(), type_long_double(), type_long_long(), and type_system_address().
#define qsort __qsort__dummy
Definition at line 3055 of file ada-exp.c.
Referenced by addrs_section_sort(), arrange_linetable(), auto_load_info_scripts(), build_type_unit_groups(), classes_info(), clear_command(), complete_command(), convert_linespec_to_sals(), darwin_check_new_threads(), decode_line_2(), do_mixed_source_and_assembly(), dwarf2_build_frame_info(), end_symtab_from_static_block(), end_symtab_get_static_block(), filter_sals(), find_method(), gdb_disassemble_driver(), gdb_listfiles(), gnuv3_print_vtable(), info_auto_load_libthread_db(), info_probes_for_ops(), inherit_abstract_dies(), install_minimal_symbols(), linux_xfer_osdata_processgroups(), lm_secs_sort(), macho_symfile_read_all_oso(), map_regcache_remote_table(), memrange_sortmerge(), mi_cmd_list_thread_groups(), msymbols_sort(), normalize_mem_ranges(), print_bcache_statistics(), print_one_inferior(), read_unwind_info(), search_minsyms_for_name(), selectors_info(), sort_blocks(), sort_pst_symbols(), sort_search_symbols_remove_dups(), sync_threadlists(), target_write_memory_blocks(), tui_rl_display_match_list(), uniquify_cu_indices(), uniquify_strings(), update_global_location_list(), update_section_map(), VEC(), and windows_create_inferior().
#define REM 282
Definition at line 300 of file ada-exp.c.
#define SPECIAL_VARIABLE 269
Definition at line 287 of file ada-exp.c.
#define STARSTAR 286
Definition at line 304 of file ada-exp.c.
Referenced by yylex().
#define STRING 265
Definition at line 283 of file ada-exp.c.
Referenced by c_print_token(), parse_string_or_char(), and yylex().
#define THEN 272
Definition at line 290 of file ada-exp.c.
#define TICK_ACCESS 293
Definition at line 311 of file ada-exp.c.
#define TICK_ADDRESS 292
Definition at line 310 of file ada-exp.c.
#define TICK_FIRST 291
Definition at line 309 of file ada-exp.c.
#define TICK_LAST 290
Definition at line 308 of file ada-exp.c.
#define TICK_LENGTH 289
Definition at line 307 of file ada-exp.c.
#define TICK_MAX 296
Definition at line 314 of file ada-exp.c.
#define TICK_MIN 295
Definition at line 313 of file ada-exp.c.
#define TICK_MODULUS 294
Definition at line 312 of file ada-exp.c.
#define TICK_POS 301
Definition at line 319 of file ada-exp.c.
#define TICK_RANGE 300
Definition at line 318 of file ada-exp.c.
#define TICK_SIZE 299
Definition at line 317 of file ada-exp.c.
#define TICK_TAG 298
Definition at line 316 of file ada-exp.c.
#define TICK_VAL 297
Definition at line 315 of file ada-exp.c.
#define TRUEKEYWORD 262
Definition at line 280 of file ada-exp.c.
Referenced by yylex().
#define UNARY 281
Definition at line 299 of file ada-exp.c.
#define VAR 287
Definition at line 305 of file ada-exp.c.
#define XOR 273
Definition at line 291 of file ada-exp.c.
#define YY_ (msgid) msgid
Definition at line 419 of file ada-exp.c.
#define yy_create_buffer ada_yy_create_buffer
Definition at line 3042 of file ada-exp.c.
#define yy_delete_buffer ada_yy_delete_buffer
Definition at line 3043 of file ada-exp.c.
#define yy_init_buffer ada_yy_init_buffer
Definition at line 3044 of file ada-exp.c.
#define yy_load_buffer_state ada_yy_load_buffer_state
Definition at line 3045 of file ada-exp.c.
#define YY_LOCATION_PRINT (File, Loc) ((void) 0)
Definition at line 1158 of file ada-exp.c.
#define YY_REDUCE_PRINT (Rule)
Value:
do {                                    \
  if (yydebug)                          \
    yy_reduce_print (yyvsp, Rule); \
} while (YYID (0))
Definition at line 1317 of file ada-exp.c.
#define YY_STACK_PRINT (Bottom, Top)
Value:
do {                                                            \
  if (yydebug)                                                  \
    yy_stack_print ((Bottom), (Top));                           \
} while (YYID (0))
Definition at line 1279 of file ada-exp.c.
#define yy_switch_to_buffer ada_yy_switch_to_buffer
Definition at line 3046 of file ada-exp.c.
#define YY_SYMBOL_PRINT (Title, Type, Value, Location)
Value:
do {                                                                      \
  if (yydebug)                                                            \
    {                                                                     \
      YYFPRINTF (stderr, "%s ", Title);                                   \
      yy_symbol_print (stderr,                                            \
                  Type, Value); \
      YYFPRINTF (stderr, "\n");                                           \
    }                                                                     \
} while (YYID (0))
Definition at line 1184 of file ada-exp.c.
Referenced by yydestruct().
#define yy_yys ada_yys
Definition at line 119 of file ada-exp.c.
#define yy_yyv ada_yyv
Definition at line 123 of file ada-exp.c.
#define YYABORT goto yyabortlab
Definition at line 1087 of file ada-exp.c.
#define YYACCEPT goto yyacceptlab
Definition at line 1086 of file ada-exp.c.
#define yyact ada_act
Definition at line 112 of file ada-exp.c.
#define YYBACKUP (Token, Value)
Value:
do                                                              \
  if (yychar == YYEMPTY && yylen == 1)                          \
    {                                                           \
      yychar = (Token);                                         \
      yylval = (Value);                                         \
      YYPOPSTACK (1);                                           \
      goto yybackup;                                            \
    }                                                           \
  else                                                          \
    {                                                           \
      yyerror (YY_("syntax error: cannot back up")); \
      YYERROR;                                                  \
    }                                                           \
while (YYID (0))
Definition at line 1108 of file ada-exp.c.
#define YYBISON 1
Definition at line 44 of file ada-exp.c.
#define YYBISON_VERSION "2.5"
Definition at line 47 of file ada-exp.c.
#define yychar ada_char
Definition at line 104 of file ada-exp.c.
#define yychk ada_chk
Definition at line 110 of file ada-exp.c.
#define yyclearin (yychar = YYEMPTY)
Definition at line 1082 of file ada-exp.c.
#define YYCOPY (To, From, Count)
Value:
do                                      \
        {                                       \
          YYSIZE_T yyi;                         \
          for (yyi = 0; yyi < (Count); yyi++)   \
            (To)[yyi] = (From)[yyi];            \
        }                                       \
      while (YYID (0))
Definition at line 565 of file ada-exp.c.
#define YYCOPY_NEEDED 1
Definition at line 537 of file ada-exp.c.
#define yydebug ada_debug
Definition at line 105 of file ada-exp.c.
#define YYDEBUG 1 /* Default to yydebug support */
Definition at line 138 of file ada-exp.c.
#define yydef ada_def
Definition at line 109 of file ada-exp.c.
#define YYDPRINTF (Args)
Value:
do {                                            \
  if (yydebug)                                  \
    YYFPRINTF Args;                             \
} while (YYID (0))
Definition at line 1178 of file ada-exp.c.
#define YYEMPTY (-2)
Definition at line 1083 of file ada-exp.c.
#define YYEOF 0
Definition at line 1084 of file ada-exp.c.
#define YYERRCODE 256
Definition at line 1126 of file ada-exp.c.
#define yyerrflag ada_errflag
Definition at line 114 of file ada-exp.c.
#define yyerrok (yyerrstatus = 0)
Definition at line 1081 of file ada-exp.c.
#define yyerror ada_error
Definition at line 102 of file ada-exp.c.
Referenced by yylex().
#define YYERROR goto yyerrorlab
Definition at line 1088 of file ada-exp.c.
#define YYERROR_VERBOSE 0
Definition at line 212 of file ada-exp.c.
#define yyexca ada_exca
Definition at line 113 of file ada-exp.c.
#define YYFAIL goto yyerrlab
Definition at line 1098 of file ada-exp.c.
#define YYFINAL 57
Definition at line 578 of file ada-exp.c.
#define YYFPRINTF parser_fprintf
Definition at line 141 of file ada-exp.c.
Referenced by yy_reduce_print(), yy_stack_print(), and yy_symbol_print().
#define YYFREE xfree
Definition at line 507 of file ada-exp.c.
#define YYID (n) (n)
Definition at line 432 of file ada-exp.c.
#define YYINITDEPTH 200
Definition at line 1336 of file ada-exp.c.
#define YYLAST 770
Definition at line 580 of file ada-exp.c.
#define yylex ada_lex
Definition at line 101 of file ada-exp.c.
#define YYLEX yylex ()
Definition at line 1167 of file ada-exp.c.
#define yylloc ada_lloc
Definition at line 125 of file ada-exp.c.
#define YYLLOC_DEFAULT (Current, Rhs, N)
Value:
do                                                                      \
      if (YYID (N))                                                    \
        {                                                               \
          (Current).first_line   = YYRHSLOC (Rhs, 1).first_line;        \
          (Current).first_column = YYRHSLOC (Rhs, 1).first_column;      \
          (Current).last_line    = YYRHSLOC (Rhs, N).last_line;         \
          (Current).last_column  = YYRHSLOC (Rhs, N).last_column;       \
        }                                                               \
      else                                                              \
        {                                                               \
          (Current).first_line   = (Current).last_line   =              \
            YYRHSLOC (Rhs, 0).last_line;                                \
          (Current).first_column = (Current).last_column =              \
            YYRHSLOC (Rhs, 0).last_column;                              \
        }                                                               \
    while (YYID (0))
Definition at line 1135 of file ada-exp.c.
#define YYLSP_NEEDED 0
Definition at line 62 of file ada-exp.c.
#define yylval ada_lval
Definition at line 103 of file ada-exp.c.
Referenced by processInt(), processReal(), and yylex().
#define YYMALLOC xmalloc
Definition at line 500 of file ada-exp.c.
#define yymaxdepth ada_maxdepth
Definition at line 99 of file ada-exp.c.
#define YYMAXDEPTH 10000
Definition at line 1347 of file ada-exp.c.
#define YYMAXUTOK 303
Definition at line 593 of file ada-exp.c.
#define yyname ada_name /* With YYDEBUG defined */
Definition at line 128 of file ada-exp.c.
#define yynerrs ada_nerrs
Definition at line 115 of file ada-exp.c.
#define YYNNTS 31
Definition at line 585 of file ada-exp.c.
#define YYNRULES 122
Definition at line 587 of file ada-exp.c.
#define YYNSTATES 233
Definition at line 589 of file ada-exp.c.
#define YYNTOKENS 69
Definition at line 583 of file ada-exp.c.
Referenced by yy_symbol_print(), and yy_symbol_value_print().
#define yypact ada_pact
Definition at line 106 of file ada-exp.c.
#define YYPACT_NINF -104
Definition at line 839 of file ada-exp.c.
#define yypact_value_is_default (yystate) ((yystate) == (-104))
Definition at line 963 of file ada-exp.c.
int yyparse _ada_parse /* ada_parse calls this after initialization */
Definition at line 100 of file ada-exp.c.
Referenced by c_parse(), cp_demangled_name_to_comp(), and go_parse().
#define yypgo ada_pgo
Definition at line 111 of file ada-exp.c.
#define YYPOPSTACK (N) (yyvsp -= (N), yyssp -= (N))
#define yyps ada_ps
Definition at line 116 of file ada-exp.c.
#define YYPULL 1
Definition at line 59 of file ada-exp.c.
#define YYPURE 0
Definition at line 53 of file ada-exp.c.
#define YYPUSH 0
Definition at line 56 of file ada-exp.c.
#define yypv ada_pv
Definition at line 117 of file ada-exp.c.
#define yyr1 ada_r1
Definition at line 107 of file ada-exp.c.
#define yyr2 ada_r2
Definition at line 108 of file ada-exp.c.
#define YYRECOVERING () (!!yyerrstatus)
Definition at line 1106 of file ada-exp.c.
#define yyreds ada_reds /* With YYDEBUG defined */
Definition at line 126 of file ada-exp.c.
#define yyrestart ada_yyrestart
Definition at line 3047 of file ada-exp.c.
#define YYRHSLOC (Rhs, K) ((Rhs)[K])
Definition at line 1133 of file ada-exp.c.
#define yyrule ada_rule /* With YYDEBUG defined */
Definition at line 129 of file ada-exp.c.
Referenced by yy_reduce_print().
#define yys ada_s
Definition at line 118 of file ada-exp.c.
#define YYSIZE_MAXIMUM ((YYSIZE_T) -1)
Definition at line 409 of file ada-exp.c.
#define YYSIZE_T unsigned int
Definition at line 405 of file ada-exp.c.
#define YYSKELETON_NAME "yacc.c"
Definition at line 50 of file ada-exp.c.
#define yyss ada_yyss
Definition at line 130 of file ada-exp.c.
#define yysslim ada_yysslim
Definition at line 131 of file ada-exp.c.
#define yyssp ada_yyssp
Definition at line 132 of file ada-exp.c.
#define YYSTACK_ALLOC YYMALLOC
Definition at line 486 of file ada-exp.c.
#define YYSTACK_ALLOC_MAXIMUM YYSIZE_MAXIMUM
Definition at line 489 of file ada-exp.c.
#define YYSTACK_BYTES (N)
Value:
((N) * (sizeof (yytype_int16) + sizeof (YYSTYPE)) \
      + YYSTACK_GAP_MAXIMUM)
Definition at line 533 of file ada-exp.c.
#define YYSTACK_FREE YYFREE
Definition at line 487 of file ada-exp.c.
#define YYSTACK_GAP_MAXIMUM (sizeof (union yyalloc) - 1)
Definition at line 529 of file ada-exp.c.
#define YYSTACK_RELOCATE (Stack_alloc, Stack)
Value:
do                                                                      \
      {                                                                 \
        YYSIZE_T yynewbytes;                                            \
        YYCOPY (&yyptr->Stack_alloc, Stack, yysize);                    \
        Stack = &yyptr->Stack_alloc;                                    \
        yynewbytes = yystacksize * sizeof (*Stack) + YYSTACK_GAP_MAXIMUM; \
        yyptr += yynewbytes / sizeof (*yyptr);                          \
      }                                                                 \
    while (YYID (0))
Definition at line 544 of file ada-exp.c.
#define yystacksize ada_yystacksize
Definition at line 133 of file ada-exp.c.
#define yystate ada_state
Definition at line 120 of file ada-exp.c.
#define yystype YYSTYPE /* obsolescent; will be withdrawn */
Definition at line 353 of file ada-exp.c.
#define YYSTYPE_IS_DECLARED 1
Definition at line 354 of file ada-exp.c.
#define YYSTYPE_IS_TRIVIAL 1
Definition at line 352 of file ada-exp.c.
#define YYTABLE_NINF -83
Definition at line 880 of file ada-exp.c.
#define yytable_value_is_error (yytable_value) YYID (0)
Definition at line 966 of file ada-exp.c.
#define YYTERROR 1
Definition at line 1125 of file ada-exp.c.
char * yytext ada_yytext
Definition at line 3048 of file ada-exp.c.
#define yytmp ada_tmp
Definition at line 121 of file ada-exp.c.
#define YYTOKEN_TABLE 0
Definition at line 217 of file ada-exp.c.
#define YYTOKENTYPE
Definition at line 223 of file ada-exp.c.
#define yytoks ada_toks /* With YYDEBUG defined */
Definition at line 127 of file ada-exp.c.
#define YYTRANSLATE (YYX) ((unsigned int) (YYX) <= YYMAXUTOK ? yytranslate[YYX] : YYUNDEFTOK)
Definition at line 595 of file ada-exp.c.
#define YYUNDEFTOK 2
Definition at line 592 of file ada-exp.c.
#define YYUSE (e) ((void) (e))
Definition at line 425 of file ada-exp.c.
Referenced by yy_symbol_value_print(), and yydestruct().
#define yyv ada_v
Definition at line 122 of file ada-exp.c.
#define yyval ada_val
Definition at line 124 of file ada-exp.c.
#define yyvs ada_yyvs
Definition at line 134 of file ada-exp.c.
#define yyvsp ada_yyvsp
Definition at line 135 of file ada-exp.c.
#define yywrap ada_yywrap
Definition at line 3049 of file ada-exp.c.
Typedef Documentation
typedef union YYSTYPE YYSTYPE
typedef short int yytype_int16
Definition at line 392 of file ada-exp.c.
typedef short int yytype_int8
Definition at line 380 of file ada-exp.c.
typedef unsigned short int yytype_uint16
Definition at line 386 of file ada-exp.c.
typedef unsigned char yytype_uint8
Definition at line 371 of file ada-exp.c.
Enumeration Type Documentation
enum yytokentype
Enumerator:
INT
NULL_PTR
CHARLIT
FLOAT
TRUEKEYWORD
FALSEKEYWORD
COLONCOLON
STRING
NAME
DOT_ID
DOT_ALL
SPECIAL_VARIABLE
ASSIGN
ELSE
THEN
XOR
OR
_AND_
DOTDOT
IN
GEQ
LEQ
NOTEQUAL
UNARY
REM
MOD
NOT
ABS
STARSTAR
VAR
ARROW
TICK_LENGTH
TICK_LAST
TICK_FIRST
TICK_ADDRESS
TICK_ACCESS
TICK_MODULUS
TICK_MIN
TICK_MAX
TICK_VAL
TICK_TAG
TICK_SIZE
TICK_RANGE
TICK_POS
NEW
OTHERS
INT
FLOAT
DECFLOAT
STRING
NSSTRING
SELECTOR
CHAR
NAME
UNKNOWN_CPP_NAME
COMPLETE
TYPENAME
CLASSNAME
OBJC_LBRAC
NAME_OR_INT
OPERATOR
STRUCT
CLASS
UNION
ENUM
SIZEOF
UNSIGNED
COLONCOLON
TEMPLATE
ERROR
NEW
DELETE
REINTERPRET_CAST
DYNAMIC_CAST
STATIC_CAST
CONST_CAST
ENTRY
TYPEOF
DECLTYPE
TYPEID
SIGNED_KEYWORD
LONG
SHORT
INT_KEYWORD
CONST_KEYWORD
VOLATILE_KEYWORD
DOUBLE_KEYWORD
VARIABLE
ASSIGN_MODIFY
TRUEKEYWORD
FALSEKEYWORD
ABOVE_COMMA
OROR
ANDAND
NOTEQUAL
EQUAL
GEQ
LEQ
RSH
LSH
DECREMENT
INCREMENT
UNARY
DOT_STAR
ARROW_STAR
ARROW
BLOCKNAME
FILENAME
DOTDOTDOT
INT
FLOAT
NAME
STRUCT
CLASS
UNION
ENUM
SIZEOF
UNSIGNED
COLONCOLON
TEMPLATE
ERROR
NEW
DELETE
OPERATOR
STATIC_CAST
REINTERPRET_CAST
DYNAMIC_CAST
SIGNED_KEYWORD
LONG
SHORT
INT_KEYWORD
CONST_KEYWORD
VOLATILE_KEYWORD
DOUBLE_KEYWORD
BOOL
ELLIPSIS
RESTRICT
VOID
FLOAT_KEYWORD
CHAR
WCHAR_T
ASSIGN_MODIFY
TRUEKEYWORD
FALSEKEYWORD
DEMANGLER_SPECIAL
CONSTRUCTION_VTABLE
CONSTRUCTION_IN
OROR
ANDAND
NOTEQUAL
EQUAL
GEQ
LEQ
RSH
LSH
DECREMENT
INCREMENT
UNARY
ARROW
INT
FLOAT
STRING_LITERAL
BOOLEAN_LITERAL
NAME
TYPENAME
NAME_OR_INT
SIZEOF
ERROR
INT_KEYWORD
INT_S2_KEYWORD
LOGICAL_S1_KEYWORD
LOGICAL_S2_KEYWORD
LOGICAL_S8_KEYWORD
LOGICAL_KEYWORD
REAL_KEYWORD
REAL_S8_KEYWORD
REAL_S16_KEYWORD
COMPLEX_S8_KEYWORD
COMPLEX_S16_KEYWORD
COMPLEX_S32_KEYWORD
BOOL_AND
BOOL_OR
BOOL_NOT
CHARACTER
VARIABLE
ASSIGN_MODIFY
ABOVE_COMMA
NOTEQUAL
EQUAL
GEQ
LEQ
GREATERTHAN
LESSTHAN
RSH
LSH
STARSTAR
UNARY
INT
FLOAT
RAW_STRING
STRING
CHAR
NAME
TYPENAME
COMPLETE
NAME_OR_INT
TRUE_KEYWORD
FALSE_KEYWORD
STRUCT_KEYWORD
INTERFACE_KEYWORD
TYPE_KEYWORD
CHAN_KEYWORD
SIZEOF_KEYWORD
LEN_KEYWORD
CAP_KEYWORD
NEW_KEYWORD
IOTA_KEYWORD
NIL_KEYWORD
CONST_KEYWORD
DOTDOTDOT
ENTRY
ERROR
BYTE_KEYWORD
DOLLAR_VARIABLE
ASSIGN_MODIFY
ABOVE_COMMA
OROR
ANDAND
ANDNOT
NOTEQUAL
EQUAL
GEQ
LEQ
RSH
LSH
DECREMENT
INCREMENT
UNARY
LEFT_ARROW
INTEGER_LITERAL
FLOATING_POINT_LITERAL
IDENTIFIER
STRING_LITERAL
BOOLEAN_LITERAL
TYPENAME
NAME_OR_INT
ERROR
LONG
SHORT
BYTE
INT
CHAR
BOOLEAN
DOUBLE
FLOAT
VARIABLE
ASSIGN_MODIFY
SUPER
NEW
OROR
ANDAND
NOTEQUAL
EQUAL
GEQ
LEQ
RSH
LSH
DECREMENT
INCREMENT
INT
HEX
ERROR
UINT
M2_TRUE
M2_FALSE
CHAR
FLOAT
STRING
NAME
BLOCKNAME
IDENT
VARNAME
TYPENAME
SIZE
CAP
ORD
HIGH
ABS
MIN_FUNC
MAX_FUNC
FLOAT_FUNC
VAL
CHR
ODD
TRUNC
TSIZE
INC
DEC
INCL
EXCL
COLONCOLON
INTERNAL_VAR
ABOVE_COMMA
ASSIGN
IN
NOTEQUAL
GEQ
LEQ
OROR
LOGICAL_AND
MOD
DIV
UNARY
DOT
NOT
QID
INT
FLOAT
STRING
FIELDNAME
COMPLETE
NAME
TYPENAME
NAME_OR_INT
STRUCT
CLASS
SIZEOF
COLONCOLON
ERROR
VARIABLE
THIS
TRUEKEYWORD
FALSEKEYWORD
ABOVE_COMMA
ASSIGN
NOT
OR
XOR
ANDAND
NOTEQUAL
GEQ
LEQ
MOD
DIV
RSH
LSH
DECREMENT
INCREMENT
UNARY
ARROW
BLOCKNAME
Definition at line 226 of file ada-exp.c.
Function Documentation
void _initialize_ada_exp (void)
Definition at line 3793 of file ada-exp.c.
References temp_parse_space.
static int ada_nget_field_index (const struct type * type, const char * field_name0, int field_name_len, int maybe_missing) [static]
Definition at line 3444 of file ada-exp.c.
References ada_get_field_index(), and field_name().
Referenced by get_symbol_field_type().
int ada_parse (void)
Definition at line 3059 of file ada-exp.c.
References lexer_init(), temp_parse_space, and yyin.
Referenced by parse().
static struct block * block_lookup (struct block * context, const char * raw_name) [static, read]
Definition at line 3274 of file ada-exp.c.
References _, ada_encode(), ada_lookup_symbol_list(), BLOCKVECTOR, BLOCKVECTOR_BLOCK, error(), LOC_BLOCK, lookup_symtab(), name, STATIC_BLOCK, SYMBOL_BLOCK_VALUE, SYMBOL_CLASS, VAR_DOMAIN, and warning().
static int chop_selector (char * name, int end) [static]
Definition at line 3374 of file ada-exp.c.
Referenced by write_var_or_type().
static char* chop_separator (char * name) [static]
Definition at line 3388 of file ada-exp.c.
References name.
Referenced by get_symbol_field_type(), and write_selectors().
static LONGEST convert_char_literal (struct type * type, LONGEST val) [static]
Definition at line 3711 of file ada-exp.c.
References check_typedef(), name, TYPE_CODE, TYPE_CODE_ENUM, TYPE_FIELD_ENUMVAL, TYPE_FIELD_NAME, TYPE_NFIELDS, and xsnprintf().
static struct type* find_primitive_type (char * name) [static, read]
Definition at line 3347 of file ada-exp.c.
References ada_lookup_symbol(), language_lookup_primitive_type_by_name(), LOC_TYPEDEF, parse_gdbarch, parse_language, SYMBOL_CLASS, SYMBOL_TYPE, type, type_system_address(), and VAR_DOMAIN.
Referenced by write_var_or_type().
static struct type* get_symbol_field_type (struct symbol * sym, char * encoded_field_name) [static, read]
Definition at line 3466 of file ada-exp.c.
References ada_get_field_index(), ada_nget_field_index(), check_typedef(), chop_separator(), field_name(), SYMBOL_TYPE, and TYPE_FIELD_TYPE.
Referenced by write_var_or_type().
static struct symbol* select_possible_type_sym (struct ada_symbol_info * syms, int nsyms) [static, read]
Definition at line 3314 of file ada-exp.c.
References ada_prefer_type(), LOC_ARG, LOC_COMPUTED, LOC_LOCAL, LOC_REF_ARG, LOC_REGISTER, LOC_REGPARM_ADDR, LOC_TYPEDEF, ada_symbol_info::sym, SYMBOL_CLASS, and SYMBOL_TYPE.
Referenced by write_var_or_type().
static struct type * type_boolean (void) [static, read]
Definition at line 3774 of file ada-exp.c.
References parse_type.
static struct type * type_char (void) [static, read]
Definition at line 3768 of file ada-exp.c.
References language_string_char_type(), parse_gdbarch, and parse_language.
static struct type * type_double (void) [static, read]
Definition at line 3756 of file ada-exp.c.
References parse_type.
Referenced by processReal().
static struct type * type_float (void) [static, read]
Definition at line 3750 of file ada-exp.c.
References parse_type.
Referenced by processReal().
static struct type * type_int (void) [static, read]
Definition at line 3732 of file ada-exp.c.
References parse_type.
Referenced by processInt(), and write_object_renaming().
static struct type * type_long (void) [static, read]
Definition at line 3738 of file ada-exp.c.
References parse_type.
Referenced by processInt().
static struct type * type_long_double (void) [static, read]
Definition at line 3762 of file ada-exp.c.
References parse_type.
Referenced by processReal().
static struct type * type_long_long (void) [static, read]
Definition at line 3744 of file ada-exp.c.
References parse_type.
Referenced by processInt().
static struct type * type_system_address (void) [static, read]
Definition at line 3780 of file ada-exp.c.
References language_lookup_primitive_type_by_name(), parse_gdbarch, parse_language, and parse_type.
Referenced by find_primitive_type().
static void write_ambiguous_var (const struct block * block, char * name, int len) [static]
Definition at line 3424 of file ada-exp.c.
References language_ada, memset(), SYMBOL_DOMAIN, SYMBOL_LANGUAGE, SYMBOL_LINKAGE_NAME, temp_parse_space, UNDEF_DOMAIN, write_exp_elt_block(), write_exp_elt_opcode(), and write_exp_elt_sym().
Referenced by write_var_or_type().
static void write_exp_op_with_string (enum exp_opcode opcode, struct stoken token) [static]
Definition at line 3108 of file ada-exp.c.
References write_exp_elt_opcode(), and write_exp_string().
Referenced by write_name_assoc(), write_object_renaming(), and write_selectors().
static void write_int (LONGEST arg, struct type * type) [static]
Definition at line 3098 of file ada-exp.c.
References write_exp_elt_longcst(), write_exp_elt_opcode(), and write_exp_elt_type().
static void write_name_assoc (struct stoken name) [static]
Definition at line 3688 of file ada-exp.c.
References _, ada_lookup_symbol_list(), error(), expression_context_block, LOC_TYPEDEF, stoken::ptr, strchr(), ada_symbol_info::sym, SYMBOL_CLASS, VAR_DOMAIN, write_exp_op_with_string(), write_var_from_sym(), and write_var_or_type().
static void write_object_renaming (const struct block * orig_left_context, const char * renamed_entity, int renamed_entity_len, const char * renaming_expr, int max_depth) [static]
Definition at line 3127 of file ada-exp.c.
References _, ada_decode(), ada_lookup_encoded_symbol(), ADA_NOT_RENAMING, ADA_OBJECT_RENAMING, ada_parse_renaming(), ada_symbol_info::block, error(), get_selected_block(), stoken::length, LOC_TYPEDEF, LONGEST, name, stoken::ptr, strchr(), ada_symbol_info::sym, SYMBOL_CLASS, temp_parse_space, type_int(), VAR_DOMAIN, write_exp_elt_longcst(), write_exp_elt_opcode(), write_exp_elt_type(), write_exp_op_with_string(), write_var_from_sym(), and xmalloc().
Referenced by write_var_or_type().
static void write_selectors (char * sels) [static]
Definition at line 3403 of file ada-exp.c.
References chop_separator(), stoken::length, p, stoken::ptr, and write_exp_op_with_string().
Referenced by write_var_or_type().
static void write_var_from_sym (const struct block * orig_left_context, const struct block * block, struct symbol * sym) [static]
Definition at line 3078 of file ada-exp.c.
References contained_in(), innermost_block, symbol_read_needs_frame(), write_exp_elt_block(), write_exp_elt_opcode(), and write_exp_elt_sym().
Referenced by write_name_assoc(), write_object_renaming(), and write_var_or_type().
static struct type * write_var_or_type (const struct block * block, struct stoken name0) [static, read]
Definition at line 3516 of file ada-exp.c.
References _, ada_encode(), ADA_EXCEPTION_RENAMING, ada_find_renaming_symbol(), ada_lookup_simple_minsym(), ada_lookup_symbol_list(), ADA_NOT_RENAMING, ADA_OBJECT_RENAMING, ADA_PACKAGE_RENAMING, ada_parse_renaming(), ADA_SUBPROGRAM_RENAMING, chop_selector(), error(), expression_context_block, find_primitive_type(), get_symbol_field_type(), have_full_symbols(), have_partial_symbols(), internal_error(), MAX_RENAMING_CHAIN_LENGTH, bound_minimal_symbol::minsym, stoken::ptr, select_possible_type_sym(), ada_symbol_info::sym, SYMBOL_TYPE, temp_parse_space, type, VAR_DOMAIN, write_ambiguous_var(), write_exp_msymbol(), write_object_renaming(), write_selectors(), and write_var_from_sym().
Referenced by write_name_assoc().
static void yy_reduce_print (YYSTYPE * yyvsp, int yyrule) [static]
Definition at line 1296 of file ada-exp.c.
References yy_symbol_print(), YYFPRINTF, and yyrule.
static void yy_stack_print (yytype_int16 * yybottom, yytype_int16 * yytop) [static]
Definition at line 1265 of file ada-exp.c.
References YYFPRINTF.
static void yy_symbol_print (FILE * yyoutput, int yytype, YYSTYPE const * const yyvaluep) [static]
Definition at line 1239 of file ada-exp.c.
References yy_symbol_value_print(), YYFPRINTF, and YYNTOKENS.
Referenced by yy_reduce_print().
static void yy_symbol_value_print (FILE * yyoutput, int yytype, YYSTYPE const * const yyvaluep) [static]
Definition at line 1207 of file ada-exp.c.
References YYNTOKENS, YYPRINT, and YYUSE.
Referenced by yy_symbol_print().
static void yydestruct (char * yymsg, int yytype, YYSTYPE * yyvaluep) const [static]
Definition at line 1600 of file ada-exp.c.
References YY_SYMBOL_PRINT, and YYUSE.
void yyerror (char * msg)
Definition at line 3070 of file ada-exp.c.
References _, error(), and lexptr.
static int yylex (void) [static]
int yyparse (void)
Variable Documentation
initialize_file_ftype _initialize_ada_exp
struct stoken empty_stoken = { "", 0 } [static]
Definition at line 150 of file ada-exp.c.
struct obstack temp_parse_space [static]
Definition at line 3051 of file ada-exp.c.
Referenced by _initialize_ada_exp(), ada_parse(), processId(), processString(), write_ambiguous_var(), write_object_renaming(), and write_var_or_type().
struct type* type_qualifier [static]
Definition at line 154 of file ada-exp.c.
int yychar
Definition at line 1638 of file ada-exp.c.
const yytype_int16 yycheck[] [static]
Definition at line 969 of file ada-exp.c.
int yydebug
Definition at line 1325 of file ada-exp.c.
const yytype_uint8 yydefact[] [static]
Initial value:
{
      84,    85,    88,    86,    87,    90,    91,    89,    93,    17,
      84,    84,    84,    84,    84,    84,    84,     0,     0,     0,
       2,    19,    39,    52,     3,    53,    54,    55,    56,    57,
      83,     0,    16,     0,    18,    97,    95,    19,    21,    20,
     121,   120,    22,    23,    93,     0,     0,    39,     3,     0,
      84,   100,   105,   106,   109,    92,     0,     1,    84,     7,
       6,    84,    80,    80,    80,    69,    68,    74,    73,    84,
      84,    84,    84,    84,    84,    84,    84,    84,    84,    84,
      84,    84,    84,    84,    84,    84,     0,    84,    84,    84,
      84,    84,     0,    84,     0,    84,    79,     0,     0,     0,
       0,    84,    12,    94,   115,   110,    84,    15,    84,    84,
      84,   103,    99,   101,   102,    84,    84,     4,     5,     0,
      72,    71,    70,    93,    39,     0,    25,     0,    40,    50,
      51,    19,     0,    16,    49,    42,    41,    35,    36,    38,
      37,    31,    32,    33,    34,    84,    30,    66,    84,    62,
      84,    58,    59,    84,    63,    84,    67,    84,    84,    84,
      84,    39,     0,    10,    98,    96,    84,    84,   108,     0,
       0,   117,   112,   104,   107,    29,     0,    84,    84,     8,
      84,   122,    80,    84,    19,     0,    16,    64,    60,    61,
      65,     0,     0,     0,     0,    84,     9,     0,   116,   111,
     118,   113,    81,    26,     0,    93,    27,    44,    43,    80,
      84,    78,    84,    84,    77,     0,    84,    84,    84,    13,
      84,    47,    46,     0,     0,    14,     0,   119,   114,    28,
      75,    76,    11
}
Definition at line 800 of file ada-exp.c.
const yytype_int16 yydefgoto[] [static]
Initial value:
{
      -1,    19,    20,    37,   197,   163,    22,   125,    23,   126,
      25,    26,    27,    28,    29,   120,    30,    31,    32,    33,
      34,    49,    50,    51,    52,    53,    54,   167,   218,   166,
     217
}
Definition at line 829 of file ada-exp.c.
YYSTYPE yylval
Definition at line 1641 of file ada-exp.c.
int yynerrs
Definition at line 1644 of file ada-exp.c.
const yytype_int16 yypact[] [static]
Initial value:
{
     424,  -104,  -104,  -104,  -104,  -104,  -104,  -104,    16,  -104,
     424,   424,   118,   118,   424,   424,   286,    -7,     6,    31,
     -26,   501,   674,    20,  -104,    28,    32,    22,    34,    42,
     -44,   -21,    84,    57,  -104,  -104,  -104,   558,    63,    63,
      -3,    -3,    63,    63,    23,    26,   -36,   611,     9,    27,
     286,  -104,  -104,    29,  -104,  -104,    25,  -104,   424,  -104,
    -104,   424,    35,    35,    35,  -104,  -104,  -104,  -104,   274,
     424,   424,   424,   424,   424,   424,   424,   424,   424,   424,
     424,   424,   424,   424,   424,   424,    71,   424,   424,   350,
     387,   424,    91,   424,    85,   424,  -104,    53,    58,    59,
      60,   274,  -104,    19,  -104,  -104,   424,  -104,   424,   461,
     424,  -104,  -104,    50,  -104,   286,   118,  -104,  -104,   124,
    -104,  -104,  -104,     3,   634,   -52,  -104,    70,   719,   719,
     719,   521,   166,   173,   719,   719,   719,   730,    63,    63,
      63,    99,    99,    99,    99,   424,    99,  -104,   424,  -104,
     424,  -104,  -104,   424,  -104,   424,  -104,   424,   424,   424,
     424,   654,   -41,  -104,  -104,  -104,   461,   424,  -104,   704,
     689,  -104,  -104,  -104,  -104,    -3,    68,   424,   424,  -104,
     498,  -104,    35,   424,   538,   215,   208,  -104,  -104,  -104,
    -104,    78,    79,    80,    83,   424,  -104,    93,  -104,  -104,
    -104,  -104,  -104,  -104,   339,    14,  -104,  -104,   719,    35,
     424,  -104,   424,   424,  -104,   589,   424,   461,   424,  -104,
     424,  -104,   719,    90,    92,  -104,    98,  -104,  -104,  -104,
    -104,  -104,  -104
}
Definition at line 840 of file ada-exp.c.
const yytype_int8 yypgoto[] [static]
Initial value:
{
    -104,  -104,   127,    21,  -104,  -104,     4,    55,   -46,     0,
    -104,  -104,  -104,  -104,  -104,   -62,  -104,  -104,   -15,  -104,
    -104,  -104,  -104,   -43,  -104,  -104,  -103,  -104,  -104,  -104,
    -104
}
Definition at line 869 of file ada-exp.c.
const yytype_uint16 yyprhs[] [static]
Initial value:
{
       0,     0,     3,     5,     7,    11,    15,    18,    21,    26,
      31,    32,    40,    41,    48,    55,    59,    61,    63,    65,
      67,    70,    73,    76,    79,    80,    82,    86,    90,    96,
     101,   105,   109,   113,   117,   121,   125,   129,   133,   137,
     139,   143,   147,   151,   157,   163,   167,   174,   181,   186,
     190,   194,   198,   200,   202,   204,   206,   208,   210,   214,
     218,   223,   228,   232,   236,   241,   246,   250,   254,   257,
     260,   264,   268,   272,   275,   278,   286,   294,   300,   306,
     309,   310,   314,   316,   318,   319,   321,   323,   325,   327,
     329,   331,   333,   336,   338,   341,   344,   348,   351,   355,
     359,   361,   364,   367,   370,   374,   376,   378,   382,   386,
     388,   389,   394,   398,   399,   406,   407,   412,   416,   417,
     424,   427,   430
}
Definition at line 637 of file ada-exp.c.
const yytype_uint8 yyr1[] [static]
Initial value:
{
       0,    69,    70,    71,    71,    71,    72,    72,    72,    72,
      73,    72,    74,    72,    72,    72,    72,    72,    72,    75,
      75,    75,    75,    75,    76,    76,    76,    76,    76,    72,
      75,    75,    75,    75,    75,    75,    75,    75,    75,    77,
      77,    77,    77,    77,    77,    77,    77,    77,    77,    77,
      77,    77,    78,    78,    78,    78,    78,    78,    79,    79,
      80,    80,    81,    81,    82,    82,    83,    83,    72,    72,
      72,    72,    72,    72,    72,    72,    72,    72,    72,    72,
      84,    84,    85,    86,    86,    72,    72,    72,    72,    72,
      72,    72,    72,    87,    87,    87,    87,    88,    88,    89,
      90,    90,    90,    91,    91,    92,    92,    92,    93,    94,
      96,    95,    95,    97,    95,    98,    95,    95,    99,    95,
      72,    72,    72
}
Definition at line 762 of file ada-exp.c.
const yytype_uint8 yyr2[] [static]
Initial value:
{
       0,     2,     1,     1,     3,     3,     2,     2,     4,     4,
       0,     7,     0,     6,     6,     3,     1,     1,     1,     1,
       2,     2,     2,     2,     0,     1,     3,     3,     5,     4,
       3,     3,     3,     3,     3,     3,     3,     3,     3,     1,
       3,     3,     3,     5,     5,     3,     6,     6,     4,     3,
       3,     3,     1,     1,     1,     1,     1,     1,     3,     3,
       4,     4,     3,     3,     4,     4,     3,     3,     2,     2,
       3,     3,     3,     2,     2,     7,     7,     5,     5,     2,
       0,     3,     1,     1,     0,     1,     1,     1,     1,     1,
       1,     1,     2,     1,     2,     2,     3,     2,     3,     3,
       1,     2,     2,     2,     3,     1,     1,     3,     3,     1,
       0,     4,     3,     0,     6,     0,     4,     3,     0,     6,
       2,     2,     4
}
Definition at line 780 of file ada-exp.c.
const yytype_int8 yyrhs[] [static]
Definition at line 655 of file ada-exp.c.
const yytype_uint16 yyrline[] [static]
Initial value:
{
       0,   231,   231,   235,   236,   238,   243,   247,   251,   257,
     276,   276,   288,   292,   294,   302,   313,   323,   327,   330,
     333,   337,   341,   345,   349,   352,   354,   356,   358,   362,
     375,   379,   383,   387,   391,   395,   399,   403,   407,   411,
     414,   418,   422,   426,   428,   433,   441,   445,   451,   462,
     466,   470,   474,   475,   476,   477,   478,   479,   483,   485,
     490,   492,   497,   499,   504,   506,   510,   512,   524,   526,
     532,   535,   538,   541,   543,   545,   547,   549,   551,   553,
     557,   559,   564,   574,   576,   582,   586,   593,   601,   605,
     611,   613,   617,   621,   623,   625,   633,   644,   646,   651,
     660,   661,   667,   672,   678,   687,   688,   689,   693,   698,
     713,   712,   715,   718,   717,   723,   722,   725,   728,   727,
     735,   737,   739
}
Definition at line 704 of file ada-exp.c.
const yytype_uint8 yystos[] [static]
Initial value:
{
       0,     3,     4,     5,     6,     7,     8,    10,    11,    14,
      30,    31,    32,    34,    38,    39,    58,    60,    66,    70,
      71,    72,    75,    77,    78,    79,    80,    81,    82,    83,
      85,    86,    87,    88,    89,     9,    48,    72,    75,    75,
      72,    72,    75,    75,    11,    61,    71,    75,    78,    90,
      91,    92,    93,    94,    95,    11,    87,     0,    62,    12,
      13,    15,    44,    45,    46,    47,    48,    53,    54,    58,
      59,    21,    22,    23,    25,    26,    27,    28,    29,    30,
      31,    32,    34,    35,    36,    37,    38,    40,    18,    19,
      20,    20,    20,    19,    19,    18,    49,    52,    50,    51,
      56,    58,    64,    11,    42,    43,    43,    63,    24,    42,
      43,    65,    63,    78,    92,    65,    67,    78,    78,    58,
      84,    84,    84,    11,    75,    76,    78,    78,    75,    75,
      75,    72,    75,    87,    75,    75,    75,    75,    75,    75,
      75,    75,    75,    75,    75,    25,    75,    77,    16,    77,
      17,    77,    77,    17,    77,    16,    77,    58,    58,    58,
      58,    75,    76,    74,     9,    48,    98,    96,    78,    75,
      75,    95,    78,    65,    92,    72,     3,    43,    24,    63,
      65,    68,    55,    24,    72,    75,    87,    77,    77,    77,
      77,    78,    78,    78,    78,    24,    63,    73,    95,    78,
      42,    43,    63,    78,    75,    11,    78,    84,    75,    55,
      24,    63,    65,    65,    63,    75,    58,    99,    97,    63,
      43,    84,    75,    78,    78,    63,    78,    95,    78,    78,
      63,    63,    63
}
Definition at line 1053 of file ada-exp.c.
const yytype_int16 yytable[] [static]
Definition at line 881 of file ada-exp.c.
const char* const yytname[] [static]
Initial value:
{
  "$end", "error", "$undefined", "INT", "NULL_PTR", "CHARLIT", "FLOAT",
  "TRUEKEYWORD", "FALSEKEYWORD", "COLONCOLON", "STRING", "NAME", "DOT_ID",
  "DOT_ALL", "SPECIAL_VARIABLE", "ASSIGN", "ELSE", "THEN", "XOR", "OR",
  "_AND_", "'='", "'<'", "'>'", "DOTDOT", "IN", "GEQ", "LEQ", "NOTEQUAL",
  "'@'", "'+'", "'-'", "'&'", "UNARY", "'*'", "'/'", "REM", "MOD", "NOT",
  "ABS", "STARSTAR", "VAR", "'|'", "ARROW", "TICK_LENGTH", "TICK_LAST",
  "TICK_FIRST", "TICK_ADDRESS", "TICK_ACCESS", "TICK_MODULUS", "TICK_MIN",
  "TICK_MAX", "TICK_VAL", "TICK_TAG", "TICK_SIZE", "TICK_RANGE",
  "TICK_POS", "'.'", "'('", "'['", "NEW", "OTHERS", "';'", "')'", "'\\''",
  "','", "'{'", "'}'", "']'", "$accept", "start", "exp1", "primary", "$@1",
  "save_qualifier", "simple_exp", "arglist", "relation", "exp", "and_exp",
  "and_then_exp", "or_exp", "or_else_exp", "xor_exp", "tick_arglist",
  "type_prefix", "opt_type_prefix", "var_or_type", "block", "aggregate",
  "aggregate_component_list", "positional_list", "component_groups",
  "others", "component_group", "component_associations", "$@2", "$@3",
  "$@4", "$@5", 0
}
Definition at line 725 of file ada-exp.c.
const yytype_uint8 yytranslate[] [static]
Definition at line 599 of file ada-exp.c.