GDB (xrefs): /home/stan/gdb/src/gdb/ada-lang.h File Reference
/home/stan/gdb/src/gdb/ada-lang.h File Reference
#include "value.h"
#include "gdbtypes.h"
#include "breakpoint.h"
Classes
struct ada_opname_map
struct ada_symbol_info
struct ada_task_info
Defines
#define ADA_KNOWN_AUXILIARY_FUNCTION_NAME_PATTERNS
#define MAX_ENCLOSING_FRAME_LEVELS 7
#define MAX_RENAMING_CHAIN_LENGTH 10
#define GROW_VECT(v, s, m) if ((s) < (m)) (v) = grow_vect (v, &(s), m, sizeof *(v));
Typedefs
typedef void(ada_task_list_iterator_ftype)(struct ada_task_info *task)
Enumerations
enum ada_renaming_category {
ADA_NOT_RENAMING, ADA_OBJECT_RENAMING, ADA_EXCEPTION_RENAMING, ADA_PACKAGE_RENAMING,
ADA_SUBPROGRAM_RENAMING
}
enum ada_exception_catchpoint_kind { ada_catch_exception, ada_catch_exception_unhandled, ada_catch_assert }
Functions
void * grow_vect (void *, size_t *, size_t, int)
int ada_get_field_index (const struct type *type, const char *field_name, int maybe_missing)
int ada_parse (void)
void ada_error (char *)
void ada_print_type (struct type *, const char *, struct ui_file *, int, int, const struct type_print_options *)
void ada_print_typedef (struct type *type, struct symbol *new_symbol, struct ui_file *stream)
void ada_val_print (struct type *, const gdb_byte *, int, CORE_ADDR, struct ui_file *, int, const struct value *, const struct value_print_options *)
void ada_value_print (struct value *, struct ui_file *, const struct value_print_options *)
void ada_emit_char (int, struct type *, struct ui_file *, int, int)
void ada_printchar (int, struct type *, struct ui_file *)
void ada_printstr (struct ui_file *, struct type *, const gdb_byte *, unsigned int, const char *, int, const struct value_print_options *)
struct value * ada_convert_actual (struct value *actual, struct type *formal_type0)
struct value * ada_value_subscript (struct value *, int, struct value **)
void ada_fixup_array_indexes_type (struct type *index_desc_type)
struct type * ada_array_element_type (struct type *, int)
int ada_array_arity (struct type *)
struct type * ada_type_of_array (struct value *, int)
struct value * ada_coerce_to_simple_array_ptr (struct value *)
struct value * ada_coerce_to_simple_array (struct value *)
int ada_is_simple_array_type (struct type *)
int ada_is_array_descriptor_type (struct type *)
int ada_is_bogus_array_descriptor (struct type *)
LONGEST ada_discrete_type_low_bound (struct type *)
LONGEST ada_discrete_type_high_bound (struct type *)
struct value * ada_get_decoded_value (struct value *value)
struct type * ada_get_decoded_type (struct type *type)
const char * ada_decode_symbol (const struct general_symbol_info *)
const char * ada_decode (const char *)
enum language ada_update_initial_language (enum language)
void clear_ada_sym_cache (void)
int ada_lookup_symbol_list (const char *, const struct block *, domain_enum, struct ada_symbol_info **)
char * ada_fold_name (const char *)
struct symbol * ada_lookup_symbol (const char *, const struct block *, domain_enum, int *)
void ada_lookup_encoded_symbol (const char *name, const struct block *block, domain_enum namespace, struct ada_symbol_info *symbol_info)
struct bound_minimal_symbol ada_lookup_simple_minsym (const char *)
void ada_fill_in_ada_prototype (struct symbol *)
int user_select_syms (struct ada_symbol_info *, int, int)
int get_selections (int *, int, int, int, char *)
int ada_scan_number (const char *, int, LONGEST *, int *)
struct type * ada_parent_type (struct type *)
int ada_is_ignored_field (struct type *, int)
int ada_is_constrained_packed_array_type (struct type *)
struct value * ada_value_primitive_packed_val (struct value *, const gdb_byte *, long, int, int, struct type *)
struct type * ada_coerce_to_simple_array_type (struct type *)
int ada_is_character_type (struct type *)
int ada_is_string_type (struct type *)
int ada_is_tagged_type (struct type *, int)
int ada_is_tag_type (struct type *)
struct type * ada_tag_type (struct value *)
struct value * ada_value_tag (struct value *)
const char * ada_tag_name (struct value *)
struct value * ada_tag_value_at_base_address (struct value *obj)
int ada_is_parent_field (struct type *, int)
int ada_is_wrapper_field (struct type *, int)
int ada_is_variant_part (struct type *, int)
struct type * ada_variant_discrim_type (struct type *, struct type *)
int ada_is_others_clause (struct type *, int)
int ada_in_variant (LONGEST, struct type *, int)
char * ada_variant_discrim_name (struct type *)
struct value * ada_value_struct_elt (struct value *, char *, int)
int ada_is_aligner_type (struct type *)
struct type * ada_aligned_type (struct type *)
const gdb_byte * ada_aligned_value_addr (struct type *, const gdb_byte *)
const char * ada_attribute_name (enum exp_opcode)
int ada_is_fixed_point_type (struct type *)
int ada_is_system_address_type (struct type *)
DOUBLEST ada_delta (struct type *)
DOUBLEST ada_fixed_to_float (struct type *, LONGEST)
LONGEST ada_float_to_fixed (struct type *, DOUBLEST)
struct type * ada_system_address_type (void)
int ada_which_variant_applies (struct type *, struct type *, const gdb_byte *)
struct type * ada_to_fixed_type (struct type *, const gdb_byte *, CORE_ADDR, struct value *, int check_tag)
struct value * ada_to_fixed_value (struct value *val)
struct type * ada_template_to_fixed_record_type_1 (struct type *type, const gdb_byte *valaddr, CORE_ADDR address, struct value *dval0, int keep_dynamic_fields)
int ada_name_prefix_len (const char *)
const char * ada_type_name (struct type *)
struct type * ada_find_parallel_type (struct type *, const char *suffix)
LONGEST get_int_var_value (char *, int *)
struct symbol * ada_find_renaming_symbol (struct symbol *name_sym, const struct block *block)
int ada_prefer_type (struct type *, struct type *)
struct type * ada_get_base_type (struct type *)
struct type * ada_check_typedef (struct type *)
char * ada_encode (const char *)
const char * ada_enum_name (const char *)
int ada_is_modular_type (struct type *)
ULONGEST ada_modulus (struct type *)
struct value * ada_value_ind (struct value *)
void ada_print_scalar (struct type *, LONGEST, struct ui_file *)
int ada_is_range_type_name (const char *)
enum ada_renaming_category ada_parse_renaming (struct symbol *, const char **, int *, const char **)
void ada_find_printable_frame (struct frame_info *fi)
char * ada_breakpoint_rewrite (char *, int *)
char * ada_main_name (void)
char * ada_name_for_lookup (const char *name)
void create_ada_exception_catchpoint (struct gdbarch *gdbarch, enum ada_exception_catchpoint_kind ex_kind, char *excep_string, char *cond_string, int tempflag, int disabled, int from_tty)
int valid_task_id (int)
int ada_get_task_number (ptid_t)
void iterate_over_live_ada_tasks (ada_task_list_iterator_ftype *iterator)
int ada_build_task_list (void)
void print_ada_task_info (struct ui_out *uiout, char *taskno_str, struct inferior *inf)
Variables
struct ada_opname_map ada_opname_table []
Define Documentation
#define ADA_KNOWN_AUXILIARY_FUNCTION_NAME_PATTERNS
Value:
"___clean[.$a-zA-Z0-9_]*$", \
   "___finalizer[.$a-zA-Z0-9_]*$",
Definition at line 55 of file ada-lang.h.
#define GROW_VECT (v, s, m) if ((s) < (m)) (v) = grow_vect (v, &(s), m, sizeof *(v));
Definition at line 162 of file ada-lang.h.
Referenced by ada_decode(), ada_encode(), ada_enum_name(), ada_fold_name(), ada_variant_discrim_name(), print_dynamic_range_bound(), scan_discrim_bound(), and to_fixed_range_type().
#define MAX_ENCLOSING_FRAME_LEVELS 7
Definition at line 62 of file ada-lang.h.
#define MAX_RENAMING_CHAIN_LENGTH 10
Definition at line 67 of file ada-lang.h.
Referenced by write_var_or_type().
Typedef Documentation
typedef void(ada_task_list_iterator_ftype)(struct ada_task_info *task)
Definition at line 398 of file ada-lang.h.
Enumeration Type Documentation
enum ada_exception_catchpoint_kind
Enumerator:
ada_catch_exception
ada_catch_exception_unhandled
ada_catch_assert
Definition at line 120 of file ada-lang.h.
enum ada_renaming_category
Enumerator:
ADA_NOT_RENAMING
ADA_OBJECT_RENAMING
ADA_EXCEPTION_RENAMING
ADA_PACKAGE_RENAMING
ADA_SUBPROGRAM_RENAMING
Definition at line 96 of file ada-lang.h.
Function Documentation
struct type* ada_aligned_type (struct type *) [read]
Definition at line 8670 of file ada-lang.c.
References ada_aligned_type(), ada_get_base_type(), ada_is_aligner_type(), and TYPE_FIELD_TYPE.
Referenced by ada_aligned_type(), ada_print_type(), ada_template_to_fixed_record_type_1(), and printable_val_type().
const gdb_byte* ada_aligned_value_addr (struct type * , const gdb_byte *)
Definition at line 8683 of file ada-lang.c.
References ada_aligned_value_addr(), ada_is_aligner_type(), TYPE_FIELD_BITPOS, and TYPE_FIELD_TYPE.
Referenced by ada_aligned_value_addr(), and ada_val_print_1().
int ada_array_arity (struct type *)
Definition at line 2678 of file ada-lang.c.
References ada_check_typedef(), desc_arity(), desc_base_type(), desc_bounds_type(), TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_STRUCT, and TYPE_TARGET_TYPE.
Referenced by ada_array_element_type(), ada_index_type(), ada_is_string_type(), ada_type_of_array(), make_array_descriptor(), and print_array_type().
struct type* ada_array_element_type (struct type * , int) [read]
Definition at line 2706 of file ada-lang.c.
References ada_array_arity(), ada_check_typedef(), desc_base_type(), desc_data_target_type(), type, TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_STRUCT, and TYPE_TARGET_TYPE.
Referenced by ada_is_string_type(), ada_type_of_array(), empty_array(), and print_array_type().
const char* ada_attribute_name (enum exp_opcode)
Definition at line 8478 of file ada-lang.c.
Referenced by ada_print_subexp().
char* ada_breakpoint_rewrite (char * , int *)
int ada_build_task_list (void)
Definition at line 981 of file ada-tasks.c.
References _, current_inferior(), error(), get_ada_tasks_inferior_data(), read_known_tasks(), target_has_stack, ada_tasks_inferior_data::task_list_valid_p, and VEC_length.
Referenced by info_task(), iterate_over_live_ada_tasks(), print_ada_task_info(), ravenscar_find_new_threads(), task_command(), and valid_task_id().
struct type* ada_check_typedef (struct type *) [read]
Definition at line 8384 of file ada-lang.c.
References ada_check_typedef(), ada_find_any_type(), ada_typedef_target_type(), CHECK_TYPEDEF, is_thick_pntr(), name, type, TYPE_CODE, TYPE_CODE_ENUM, TYPE_CODE_TYPEDEF, TYPE_STUB, and TYPE_TAG_NAME.
Referenced by ada_args_match(), ada_array_arity(), ada_array_element_type(), ada_array_length(), ada_check_typedef(), ada_coerce_to_simple_array_type(), ada_convert_actual(), ada_fixup_array_indexes_type(), ada_get_decoded_value(), ada_index_struct_field_1(), ada_is_aligner_type(), ada_is_array_descriptor_type(), ada_is_direct_array_type(), ada_is_packed_array_type(), ada_is_parent_field(), ada_is_simple_array_type(), ada_is_string_type(), ada_lookup_struct_elt_type(), ada_parent_type(), ada_print_scalar(), ada_print_type(), ada_print_typedef(), ada_resolve_function(), ada_search_struct_field(), ada_template_to_fixed_record_type_1(), ada_to_fixed_type_1(), ada_type_match(), ada_type_of_array(), ada_val_print_1(), ada_value_binop(), ada_value_cast(), ada_value_primitive_field(), ada_value_primitive_packed_val(), ada_value_print(), ada_value_slice(), ada_value_slice_from_ptr(), ada_value_struct_elt(), ada_value_subscript(), ada_varobj_decode_var(), coerce_for_assign(), coerce_unspec_val_to_type(), constrained_packed_array_type(), decode_constrained_packed_array(), decode_constrained_packed_array_type(), decode_packed_array_bitsize(), desc_base_type(), desc_bounds(), desc_bounds_type(), desc_data_target_type(), dynamic_template_type(), empty_array(), ensure_lval(), fat_pntr_bounds_bitsize(), find_struct_field(), make_array_descriptor(), possible_user_operator_p(), print_record(), static_unwrap_type(), template_to_static_fixed_type(), thin_data_pntr(), to_fixed_array_type(), to_static_fixed_type(), unwrap_value(), and value_subscript_packed().
struct value* ada_coerce_to_simple_array (struct value *) [read]
Definition at line 1935 of file ada-lang.c.
References _, ada_coerce_to_simple_array_ptr(), ada_is_array_descriptor_type(), ada_is_constrained_packed_array_type(), check_size(), decode_constrained_packed_array(), error(), TYPE_TARGET_TYPE, value_ind(), and value_type().
Referenced by ada_get_decoded_value(), ada_val_print_1(), ada_value_assign(), ada_value_equal(), and ada_value_subscript().
struct value* ada_coerce_to_simple_array_ptr (struct value *) [read]
Definition at line 1914 of file ada-lang.c.
References ada_is_array_descriptor_type(), ada_is_constrained_packed_array_type(), ada_type_of_array(), decode_constrained_packed_array(), desc_data(), value_cast(), value_copy(), and value_type().
Referenced by ada_coerce_to_simple_array(), ada_get_decoded_value(), ada_val_print_1(), and read_atcb().
struct type* ada_coerce_to_simple_array_type (struct type *) [read]
Definition at line 1957 of file ada-lang.c.
References ada_check_typedef(), ada_is_array_descriptor_type(), ada_is_constrained_packed_array_type(), decode_constrained_packed_array_type(), desc_data_target_type(), and type.
Referenced by ada_get_decoded_type(), ada_varobj_ind(), and print_array_type().
struct value* ada_convert_actual (struct value * actual, struct type * formal_type0) [read]
Definition at line 4103 of file ada-lang.c.
References ada_check_typedef(), ada_is_array_descriptor_type(), ada_value_ind(), allocate_value(), desc_data(), ensure_lval(), lval_memory, make_array_descriptor(), memcpy(), TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_PTR, TYPE_CODE_REF, TYPE_LENGTH, TYPE_TARGET_TYPE, value_addr(), value_cast_pointers(), value_contents(), value_contents_raw(), VALUE_LVAL, and value_type().
Referenced by value_arg_coerce().
const char* ada_decode (const char *)
Definition at line 1036 of file ada-lang.c.
References ada_remove_po_subprogram_suffix(), ada_remove_trailing_digits(), ada_opname_map::decoded, ada_opname_map::encoded, GROW_VECT, is_lower_alphanum(), p, strstr(), and xsnprintf().
Referenced by ada_decode_symbol(), ada_la_decode(), ada_varobj_describe_simple_array_child(), is_valid_name_for_wild_match(), symbol_completion_match(), and write_object_renaming().
const char* ada_decode_symbol (const struct general_symbol_info *)
Definition at line 1300 of file ada-lang.c.
References ada_decode(), general_symbol_info::ada_mangled, decoded_names_store, general_symbol_info::language_specific, general_symbol_info::mangled_lang, general_symbol_info::name, and general_symbol_info::obstack.
Referenced by symbol_demangled_name(), and symbol_natural_name().
DOUBLEST ada_delta (struct type *)
Definition at line 10665 of file ada-lang.c.
References DOUBLEST_SCAN_FORMAT, encoding, and fixed_type_info().
Referenced by print_fixed_point_type().
LONGEST ada_discrete_type_high_bound (struct type *)
Definition at line 687 of file ada-lang.c.
References _, error(), max_of_type(), TYPE_CODE, TYPE_CODE_BOOL, TYPE_CODE_CHAR, TYPE_CODE_ENUM, TYPE_CODE_INT, TYPE_CODE_RANGE, TYPE_FIELD_ENUMVAL, TYPE_HIGH_BOUND, and TYPE_NFIELDS.
Referenced by ada_array_bound_from_type(), print_range(), and to_fixed_range_type().
LONGEST ada_discrete_type_low_bound (struct type *)
Definition at line 707 of file ada-lang.c.
References _, error(), min_of_type(), TYPE_CODE, TYPE_CODE_BOOL, TYPE_CODE_CHAR, TYPE_CODE_ENUM, TYPE_CODE_INT, TYPE_CODE_RANGE, TYPE_FIELD_ENUMVAL, and TYPE_LOW_BOUND.
Referenced by ada_array_bound_from_type(), ada_value_slice_from_ptr(), ada_varobj_describe_simple_array_child(), print_range(), and to_fixed_range_type().
void ada_emit_char (int , struct type * , struct ui_file * , int , int)
Definition at line 271 of file ada-valprint.c.
References fprintf_filtered().
Referenced by ada_printchar(), emit_char(), and printstr().
char* ada_encode (const char *)
Definition at line 869 of file ada-lang.c.
References _, ada_opname_map::decoded, ada_opname_map::encoded, error(), GROW_VECT, and p.
Referenced by ada_lookup_symbol(), ada_name_for_lookup(), block_lookup(), resolve_subexp(), type_from_tag(), VEC(), and write_var_or_type().
const char* ada_enum_name (const char *)
Definition at line 8699 of file ada-lang.c.
References GROW_VECT, name, strrchr(), strstr(), and xsnprintf().
Referenced by ada_print_scalar(), ada_val_print_1(), and print_enum_type().
void ada_error (char *)
void ada_fill_in_ada_prototype (struct symbol *)
struct type* ada_find_parallel_type (struct type * , const char * suffix) [read]
Definition at line 7480 of file ada-lang.c.
References ada_find_parallel_type_with_name(), ada_type_name(), len, and name.
Referenced by ada_array_bound_from_type(), ada_get_base_type(), ada_is_aligner_type(), ada_varobj_describe_simple_array_child(), constrained_packed_array_type(), dynamic_template_type(), print_array_type(), print_record_type(), print_variant_clauses(), thin_descriptor_type(), to_fixed_array_type(), to_fixed_variant_branch_type(), to_static_fixed_type(), and unwrap_value().
void ada_find_printable_frame (struct frame_info * fi)
Definition at line 11225 of file ada-lang.c.
References get_prev_frame(), is_known_support_routine(), and select_frame().
Referenced by print_it_exception(), and task_command_1().
struct symbol* ada_find_renaming_symbol (struct symbol * name_sym, const struct block * block) [read]
Definition at line 7290 of file ada-lang.c.
References ada_find_any_type_symbol(), find_old_style_renaming_symbol(), name, strstr(), and SYMBOL_LINKAGE_NAME.
Referenced by ada_read_var_value(), and write_var_or_type().
DOUBLEST ada_fixed_to_float (struct type * , LONGEST)
Definition at line 10711 of file ada-lang.c.
References scaling_factor().
Referenced by ada_val_print_1(), cast_from_fixed(), cast_to_fixed(), and print_fixed_point_type().
void ada_fixup_array_indexes_type (struct type * index_desc_type)
Definition at line 1393 of file ada-lang.c.
References ada_check_typedef(), ada_find_any_type(), gdb_assert, name, TYPE_FIELD_NAME, TYPE_FIELD_TYPE, TYPE_NAME, and TYPE_NFIELDS.
Referenced by ada_array_bound_from_type(), ada_varobj_describe_simple_array_child(), print_array_type(), and to_fixed_array_type().
LONGEST ada_float_to_fixed (struct type * , DOUBLEST)
Definition at line 10720 of file ada-lang.c.
References LONGEST, and scaling_factor().
Referenced by cast_to_fixed().
char* ada_fold_name (const char *)
Definition at line 921 of file ada-lang.c.
References GROW_VECT, and len.
Referenced by ada_lookup_symbol(), and ada_name_for_lookup().
struct type* ada_get_base_type (struct type *) [read]
Definition at line 8622 of file ada-lang.c.
References ada_find_any_type(), ada_find_parallel_type(), ada_is_aligner_type(), TYPE_CODE, TYPE_CODE_REF, TYPE_CODE_STRUCT, TYPE_FIELD_NAME, TYPE_FIELD_TYPE, TYPE_NFIELDS, and TYPE_TARGET_TYPE.
Referenced by ada_aligned_type(), ada_parent_type(), ada_print_type(), ada_template_to_fixed_record_type_1(), ada_value_struct_elt(), static_unwrap_type(), and unwrap_value().
struct type* ada_get_decoded_type (struct type * type) [read]
Definition at line 771 of file ada-lang.c.
References ada_coerce_to_simple_array_type(), ada_is_constrained_packed_array_type(), to_static_fixed_type(), and type.
Referenced by ada_varobj_decode_var().
struct value* ada_get_decoded_value (struct value * value) [read]
Definition at line 746 of file ada-lang.c.
References ada_check_typedef(), ada_coerce_to_simple_array(), ada_coerce_to_simple_array_ptr(), ada_is_array_descriptor_type(), ada_is_constrained_packed_array_type(), ada_to_fixed_value(), TYPE_CODE, TYPE_CODE_PTR, TYPE_CODE_TYPEDEF, and value_type().
Referenced by ada_varobj_decode_var().
int ada_get_field_index (const struct type * type, const char * field_name, int maybe_missing)
Definition at line 504 of file ada-lang.c.
References _, check_typedef(), error(), field_name_match(), TYPE_FIELD_NAME, TYPE_NAME, and TYPE_NFIELDS.
Referenced by ada_nget_field_index(), get_symbol_field_type(), get_tcb_types_info(), read_atcb(), and read_fat_string_value().
int ada_get_task_number (ptid_t)
Definition at line 292 of file ada-tasks.c.
References find_inferior_pid(), gdb_assert, get_ada_tasks_inferior_data(), ptid_equal(), ptid_get_pid(), VEC_index, and VEC_length.
Referenced by breakpoint_thread_match(), and display_current_task_id().
int ada_in_variant (LONGEST , struct type * , int)
Definition at line 6561 of file ada-lang.c.
References ada_scan_number(), L, LONGEST, name, p, and TYPE_FIELD_NAME.
Referenced by ada_which_variant_applies().
int ada_is_aligner_type (struct type *)
Definition at line 8606 of file ada-lang.c.
References ada_check_typedef(), ada_find_parallel_type(), TYPE_CODE, TYPE_CODE_STRUCT, TYPE_FIELD_NAME, and TYPE_NFIELDS.
Referenced by ada_aligned_type(), ada_aligned_value_addr(), ada_get_base_type(), ada_print_type(), ada_template_to_fixed_record_type_1(), static_unwrap_type(), and unwrap_value().
int ada_is_array_descriptor_type (struct type *)
Definition at line 1798 of file ada-lang.c.
References ada_check_typedef(), desc_arity(), desc_bounds_type(), desc_data_target_type(), TYPE_CODE, and TYPE_CODE_ARRAY.
Referenced by ada_coerce_to_simple_array(), ada_coerce_to_simple_array_ptr(), ada_coerce_to_simple_array_type(), ada_convert_actual(), ada_get_decoded_value(), ada_is_bogus_array_descriptor(), ada_is_constrained_packed_array_type(), ada_is_direct_array_type(), ada_is_string_type(), ada_is_unconstrained_packed_array_type(), ada_prefer_type(), ada_print_type(), ada_type_match(), ada_type_of_array(), ada_val_print_1(), ada_value_is_changeable_p(), ada_value_print(), ada_varobj_adjust_for_child_access(), ada_varobj_describe_child(), ada_varobj_get_number_of_children(), and ada_varobj_ind().
int ada_is_bogus_array_descriptor (struct type *)
Definition at line 1816 of file ada-lang.c.
References ada_is_array_descriptor_type(), lookup_struct_elt_type(), TYPE_CODE, and TYPE_CODE_STRUCT.
Referenced by ada_print_type(), ada_val_print_1(), and ada_value_print().
int ada_is_character_type (struct type *)
Definition at line 8549 of file ada-lang.c.
References ada_type_name(), name, TYPE_CODE, TYPE_CODE_CHAR, TYPE_CODE_INT, and TYPE_CODE_RANGE.
Referenced by ada_is_string_type(), and ada_val_print_1().
int ada_is_constrained_packed_array_type (struct type *)
Definition at line 1986 of file ada-lang.c.
References ada_is_array_descriptor_type(), and ada_is_packed_array_type().
Referenced by ada_array_bound(), ada_array_bound_from_type(), ada_array_length(), ada_coerce_to_simple_array(), ada_coerce_to_simple_array_ptr(), ada_coerce_to_simple_array_type(), ada_get_decoded_type(), ada_get_decoded_value(), ada_prefer_type(), ada_print_type(), ada_type_of_array(), ada_val_print_1(), ada_varobj_adjust_for_child_access(), find_parallel_type_by_descriptive_type(), print_array_type(), and to_fixed_array_type().
int ada_is_fixed_point_type (struct type *)
Definition at line 10646 of file ada-lang.c.
References fixed_type_info().
Referenced by ada_print_type(), ada_val_print_1(), ada_value_cast(), and cast_to_fixed().
int ada_is_ignored_field (struct type * , int)
Definition at line 6049 of file ada-lang.c.
References ada_is_dispatch_table_ptr_type(), ada_is_interface_tag(), ada_is_tagged_type(), name, TYPE_FIELD_NAME, TYPE_FIELD_TYPE, and TYPE_NFIELDS.
Referenced by ada_varobj_describe_struct_child(), ada_varobj_get_struct_number_of_children(), print_field_values(), and print_selected_record_field_types().
int ada_is_modular_type (struct type *)
Definition at line 10940 of file ada-lang.c.
References get_base_type(), TYPE_CODE, TYPE_CODE_INT, TYPE_CODE_RANGE, and TYPE_UNSIGNED.
Referenced by ada_print_type(), and decode_constrained_packed_array().
int ada_is_others_clause (struct type * , int)
Definition at line 6453 of file ada-lang.c.
References name, and TYPE_FIELD_NAME.
Referenced by ada_which_variant_applies().
int ada_is_parent_field (struct type * , int)
Definition at line 6393 of file ada-lang.c.
References ada_check_typedef(), name, and TYPE_FIELD_NAME.
Referenced by ada_parent_type(), and print_selected_record_field_types().
int ada_is_range_type_name (const char *)
Definition at line 10929 of file ada-lang.c.
References strstr().
Referenced by ada_print_type().
int ada_is_simple_array_type (struct type *)
Definition at line 1784 of file ada-lang.c.
References ada_check_typedef(), TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_PTR, and TYPE_TARGET_TYPE.
Referenced by ada_array_bound(), ada_array_bound_from_type(), ada_array_length(), ada_index_type(), ada_is_string_type(), and print_array_type().
int ada_is_string_type (struct type *)
Definition at line 8573 of file ada-lang.c.
References ada_array_arity(), ada_array_element_type(), ada_check_typedef(), ada_is_array_descriptor_type(), ada_is_character_type(), ada_is_simple_array_type(), TYPE_CODE, and TYPE_CODE_PTR.
Referenced by ada_val_print_array(), ada_value_is_changeable_p(), and ada_varobj_get_value_of_array_variable().
int ada_is_system_address_type (struct type *)
Definition at line 10654 of file ada-lang.c.
References TYPE_NAME.
Referenced by ada_val_print_1().
int ada_is_tag_type (struct type *)
Definition at line 6098 of file ada-lang.c.
References ada_type_name(), name, TYPE_CODE, TYPE_CODE_PTR, and TYPE_TARGET_TYPE.
Referenced by ada_tag_name(), and ada_val_print_1().
int ada_is_tagged_type (struct type * , int)
Definition at line 6090 of file ada-lang.c.
References ada_lookup_struct_elt_type().
Referenced by ada_coerce_ref(), ada_is_ignored_field(), ada_to_fixed_type_1(), ada_val_print_1(), ada_value_ind(), ada_varobj_describe_struct_child(), ada_varobj_get_struct_number_of_children(), and print_record_type().
int ada_is_variant_part (struct type * , int)
Definition at line 6425 of file ada-lang.c.
References is_dynamic_field(), TYPE_CODE, TYPE_CODE_UNION, TYPE_FIELD_TYPE, and TYPE_TARGET_TYPE.
Referenced by ada_index_struct_field_1(), ada_lookup_struct_elt_type(), ada_search_struct_field(), ada_template_to_fixed_record_type_1(), ada_varobj_describe_struct_child(), ada_varobj_get_struct_number_of_children(), find_struct_field(), print_field_values(), print_selected_record_field_types(), and variant_field_index().
int ada_is_wrapper_field (struct type * , int)
Definition at line 6409 of file ada-lang.c.
References name, and TYPE_FIELD_NAME.
Referenced by ada_index_struct_field_1(), ada_lookup_struct_elt_type(), ada_search_struct_field(), ada_varobj_describe_struct_child(), ada_varobj_get_struct_number_of_children(), find_struct_field(), print_field_values(), and print_selected_record_field_types().
void ada_lookup_encoded_symbol (const char * name, const struct block * block, domain_enum namespace, struct ada_symbol_info * symbol_info)
Definition at line 5297 of file ada-lang.c.
References ada_lookup_symbol_list(), fixup_symbol_section(), gdb_assert, memset(), and ada_symbol_info::sym.
Referenced by ada_lookup_symbol(), and write_object_renaming().
struct bound_minimal_symbol ada_lookup_simple_minsym (const char *) [read]
Definition at line 4415 of file ada-lang.c.
References ALL_MSYMBOLS, match_name(), memset(), bound_minimal_symbol::minsym, mst_solib_trampoline, MSYMBOL_TYPE, name, bound_minimal_symbol::objfile, should_use_wild_match(), and SYMBOL_LINKAGE_NAME.
Referenced by write_var_or_type().
struct symbol* ada_lookup_symbol (const char * , const struct block * , domain_enum , int *) [read]
Definition at line 5322 of file ada-lang.c.
References ada_encode(), ada_fold_name(), ada_lookup_encoded_symbol(), and ada_symbol_info::sym.
Referenced by ada_lookup_symbol_nonlocal(), and find_primitive_type().
int ada_lookup_symbol_list (const char * , const struct block * , domain_enum , struct ada_symbol_info **)
Definition at line 5239 of file ada-lang.c.
References ada_lookup_symbol_list_worker().
Referenced by ada_lookup_encoded_symbol(), block_lookup(), get_var_value(), resolve_subexp(), write_name_assoc(), and write_var_or_type().
char* ada_main_name (void)
Definition at line 801 of file ada-lang.c.
References _, ADA_MAIN_PROGRAM_SYMBOL_NAME, error(), lookup_minimal_symbol(), SYMBOL_VALUE_ADDRESS, target_read_string(), and xfree().
Referenced by find_main_name().
ULONGEST ada_modulus (struct type *)
Definition at line 10952 of file ada-lang.c.
References TYPE_HIGH_BOUND, and ULONGEST.
Referenced by ada_print_type(), and decode_constrained_packed_array().
char* ada_name_for_lookup (const char * name)
Definition at line 5273 of file ada-lang.c.
References ada_encode(), ada_fold_name(), memcpy(), and xmalloc().
Referenced by find_linespec_symbols().
int ada_name_prefix_len (const char *)
Definition at line 524 of file ada-lang.c.
References name, p, and strstr().
Referenced by ada_print_type(), ada_varobj_describe_simple_array_child(), ada_varobj_describe_struct_child(), find_old_style_renaming_symbol(), print_field_values(), and print_range().
struct type* ada_parent_type (struct type *) [read]
Definition at line 6362 of file ada-lang.c.
References ada_check_typedef(), ada_get_base_type(), ada_is_parent_field(), TYPE_CODE, TYPE_CODE_PTR, TYPE_CODE_STRUCT, TYPE_FIELD_TYPE, TYPE_NFIELDS, and TYPE_TARGET_TYPE.
Referenced by print_record_type().
int ada_parse (void)
Definition at line 3059 of file ada-exp.c.
References lexer_init(), temp_parse_space, and yyin.
Referenced by parse().
enum ada_renaming_category ada_parse_renaming (struct symbol * , const char ** , int * , const char **)
Definition at line 3931 of file ada-lang.c.
References ADA_EXCEPTION_RENAMING, ADA_NOT_RENAMING, ADA_OBJECT_RENAMING, ADA_PACKAGE_RENAMING, ADA_SUBPROGRAM_RENAMING, LOC_COMPUTED, LOC_LOCAL, LOC_OPTIMIZED_OUT, LOC_STATIC, LOC_TYPEDEF, parse_old_style_renaming(), strstr(), SYMBOL_CLASS, SYMBOL_LINKAGE_NAME, and SYMBOL_TYPE.
Referenced by remove_irrelevant_renamings(), write_object_renaming(), and write_var_or_type().
int ada_prefer_type (struct type * , struct type *)
Definition at line 7371 of file ada-lang.c.
References ada_is_array_descriptor_type(), ada_is_constrained_packed_array_type(), strstr(), TYPE_CODE, TYPE_CODE_VOID, TYPE_NAME, and type_name_no_tag().
Referenced by select_possible_type_sym().
void ada_print_scalar (struct type * , LONGEST , struct ui_file *)
Definition at line 382 of file ada-valprint.c.
References _, ada_check_typedef(), ada_enum_name(), ada_print_scalar(), error(), fprintf_filtered(), fputs_filtered(), gdb_flush(), LA_PRINT_CHAR, len, print_longest(), TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_BOOL, TYPE_CODE_CHAR, TYPE_CODE_ENUM, TYPE_CODE_ERROR, TYPE_CODE_FLT, TYPE_CODE_FUNC, TYPE_CODE_INT, TYPE_CODE_MEMBERPTR, TYPE_CODE_METHOD, TYPE_CODE_METHODPTR, TYPE_CODE_PTR, TYPE_CODE_RANGE, TYPE_CODE_REF, TYPE_CODE_SET, TYPE_CODE_STRING, TYPE_CODE_STRUCT, TYPE_CODE_UNDEF, TYPE_CODE_UNION, TYPE_CODE_VOID, TYPE_FIELD_ENUMVAL, TYPE_FIELD_NAME, TYPE_NFIELDS, TYPE_TARGET_TYPE, TYPE_UNSIGNED, and warning().
Referenced by ada_print_scalar(), ada_varobj_scalar_image(), print_choices(), print_dynamic_range_bound(), print_optional_low_bound(), print_range(), and print_range_bound().
void ada_print_type (struct type * , const char * , struct ui_file * , int , int , const struct type_print_options *)
Definition at line 763 of file ada-typeprint.c.
References _, ada_aligned_type(), ada_check_typedef(), ada_get_base_type(), ada_is_aligner_type(), ada_is_array_descriptor_type(), ada_is_bogus_array_descriptor(), ada_is_constrained_packed_array_type(), ada_is_fixed_point_type(), ada_is_modular_type(), ada_is_range_type_name(), ada_modulus(), ada_name_prefix_len(), ada_print_type(), ada_type_name(), c_print_type(), decoded_type_name(), fprintf_filtered(), int_string(), name, print_array_type(), print_enum_type(), print_fixed_point_type(), print_func_type(), print_range(), print_range_type(), print_record_type(), print_unchecked_union_type(), TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_BOOL, TYPE_CODE_ENUM, TYPE_CODE_FLT, TYPE_CODE_FUNC, TYPE_CODE_INT, TYPE_CODE_PTR, TYPE_CODE_RANGE, TYPE_CODE_REF, TYPE_CODE_STRUCT, TYPE_CODE_TYPEDEF, TYPE_CODE_UNION, TYPE_LENGTH, and TYPE_TARGET_TYPE.
Referenced by ada_print_type(), ada_print_typedef(), print_array_type(), print_func_type(), print_selected_record_field_types(), print_unchecked_union_type(), and user_select_syms().
void ada_print_typedef (struct type * type, struct symbol * new_symbol, struct ui_file * stream)
Definition at line 883 of file ada-typeprint.c.
References ada_check_typedef(), ada_print_type(), fprintf_filtered(), and type_print_raw_options.
void ada_printchar (int , struct type * , struct ui_file *)
Definition at line 370 of file ada-valprint.c.
References ada_emit_char(), fputs_filtered(), and TYPE_LENGTH.
Referenced by ada_val_print_1().
void ada_printstr (struct ui_file * , struct type * , const gdb_byte * , unsigned int, const char * , int , const struct value_print_options *)
Definition at line 544 of file ada-valprint.c.
References printstr(), and TYPE_LENGTH.
int ada_scan_number (const char * , int , LONGEST * , int *)
struct type* ada_system_address_type (void) [read]
const char* ada_tag_name (struct value *)
Definition at line 6331 of file ada-lang.c.
References ada_get_tsd_from_tag(), ada_is_tag_type(), ada_tag_name_from_tsd(), name, RETURN_MASK_ERROR, TRY_CATCH, and value_type().
Referenced by ada_val_print_1(), and type_from_tag().
struct type* ada_tag_type (struct value *) [read]
Definition at line 6114 of file ada-lang.c.
References ada_lookup_struct_elt_type(), and value_type().
struct value* ada_tag_value_at_base_address (struct value * obj) [read]
Definition at line 6178 of file ada-lang.c.
References ada_value_tag(), builtin_type::builtin_data_ptr, builtin_type(), is_ada95_tag(), LONGEST, lookup_pointer_type(), gdb_exception::reason, RETURN_MASK_ERROR, target_gdbarch(), TRY_CATCH, TYPE_CODE, TYPE_CODE_PTR, TYPE_CODE_REF, type_from_tag(), value_address(), value_as_long(), value_cast(), value_from_contents_and_address(), value_ind(), value_ptradd(), value_tag_from_contents_and_address(), and value_type().
Referenced by ada_coerce_ref(), ada_to_fixed_type_1(), ada_val_print_1(), and ada_value_ind().
struct type* ada_template_to_fixed_record_type_1 (struct type * type, const gdb_byte * valaddr, CORE_ADDR address, struct value * dval0, int keep_dynamic_fields) [read]
Definition at line 7588 of file ada-lang.c.
References _, ada_aligned_type(), ada_check_typedef(), ada_get_base_type(), ada_is_aligner_type(), ada_is_variant_part(), ada_to_fixed_type(), ada_type_name(), ada_typedef_target_type(), align_value(), alloc_type_copy(), check_size(), cond_offset_host(), cond_offset_target(), error(), field_alignment(), INIT_CPLUS_SPECIFIC, is_dynamic_field(), memset(), SET_FIELD_BITPOS, to_fixed_variant_branch_type(), TYPE_ALLOC, TYPE_CODE, TYPE_CODE_STRUCT, TYPE_CODE_TYPEDEF, TYPE_FIELD, TYPE_FIELD_BITPOS, TYPE_FIELD_BITSIZE, TYPE_FIELD_NAME, TYPE_FIELD_TYPE, TYPE_FIELDS, TYPE_FIXED_INSTANCE, TYPE_LENGTH, TYPE_NAME, TYPE_NFIELDS, TYPE_TAG_NAME, TYPE_TARGET_TYPE, value_free_to_mark(), value_from_contents_and_address(), value_mark(), varsize_limit, and warning().
Referenced by get_tcb_types_info(), and template_to_fixed_record_type().
struct type* ada_to_fixed_type (struct type * , const gdb_byte * , CORE_ADDR , struct value * , int check_tag) [read]
Definition at line 8278 of file ada-lang.c.
References ada_to_fixed_type_1(), ada_typedef_target_type(), type, TYPE_CODE, TYPE_CODE_TYPEDEF, and TYPE_MAIN_TYPE.
Referenced by ada_template_to_fixed_record_type_1(), ada_to_fixed_value_create(), ada_value_struct_elt(), printable_val_type(), to_fixed_array_type(), and unwrap_value().
struct value* ada_to_fixed_value (struct value * val) [read]
Definition at line 8445 of file ada-lang.c.
References ada_to_fixed_value_create(), unwrap_value(), value_address(), and value_type().
Referenced by ada_coerce_ref(), ada_get_decoded_value(), ada_value_ind(), ada_value_print(), assign_component(), and common_val_print().
const char* ada_type_name (struct type *)
Definition at line 7404 of file ada-lang.c.
References TYPE_NAME, and TYPE_TAG_NAME.
Referenced by ada_find_parallel_type(), ada_is_character_type(), ada_is_packed_array_type(), ada_is_tag_type(), ada_print_type(), ada_template_to_fixed_record_type_1(), ada_to_fixed_type_1(), ada_variant_discrim_name(), ada_varobj_describe_simple_array_child(), constrained_packed_array_type(), decode_constrained_packed_array_type(), decode_packed_array_bitsize(), decoded_type_name(), dynamic_template_type(), equiv_types(), find_parallel_type_by_descriptive_type(), fixed_type_info(), is_nondebugging_type(), is_thin_pntr(), print_record_type(), static_unwrap_type(), template_to_static_fixed_type(), thin_descriptor_type(), to_record_with_fixed_variant_part(), and unwrap_value().
struct type* ada_type_of_array (struct value * , int) [read]
Definition at line 1835 of file ada-lang.c.
References ada_array_arity(), ada_array_element_type(), ada_check_typedef(), ada_is_array_descriptor_type(), ada_is_constrained_packed_array_type(), ada_is_unconstrained_packed_array_type(), alloc_type_copy(), create_array_type(), create_range_type(), decode_constrained_packed_array_type(), decode_packed_array_bitsize(), desc_bounds(), desc_data_target_type(), desc_one_bound(), LONGEST, longest_to_int(), lookup_pointer_type(), TYPE_FIELD_BITSIZE, TYPE_LENGTH, value_as_long(), and value_type().
Referenced by ada_coerce_to_simple_array_ptr().
enum language ada_update_initial_language (enum language)
Definition at line 787 of file ada-lang.c.
References language_ada, and lookup_minimal_symbol().
Referenced by ada_exception_support_info_sniffer().
void ada_val_print (struct type * , const gdb_byte * , int , CORE_ADDR , struct ui_file * , int , const struct value * , const struct value_print_options *)
Definition at line 558 of file ada-valprint.c.
References ada_val_print_1(), RETURN_MASK_ALL, and TRY_CATCH.
Referenced by print_field_values().
struct value* ada_value_ind (struct value *) [read]
Definition at line 7182 of file ada-lang.c.
References ada_is_tagged_type(), ada_tag_value_at_base_address(), ada_to_fixed_value(), value_ind(), and value_type().
Referenced by ada_convert_actual(), ada_val_print_1(), ada_value_struct_elt(), ada_varobj_ind(), and coerce_for_assign().
struct value* ada_value_primitive_packed_val (struct value * , const gdb_byte * , long , int , int , struct type *) [read]
Definition at line 2271 of file ada-lang.c.
References ada_check_typedef(), allocate_value(), gdbarch_bits_big_endian(), get_type_arch(), has_negatives(), HOST_CHAR_BIT, L, len, lval_memory, memset(), offset, read_memory(), set_value_bitpos(), set_value_bitsize(), set_value_component_location(), set_value_offset(), set_value_parent(), TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_STRUCT, TYPE_CODE_UNION, TYPE_LENGTH, value_address(), value_at(), value_bitpos(), value_contents(), value_lazy(), and VALUE_LVAL.
Referenced by ada_value_primitive_field(), ada_value_struct_elt(), decode_constrained_packed_array(), print_field_values(), val_print_packed_array_elements(), and value_subscript_packed().
void ada_value_print (struct value * , struct ui_file * , const struct value_print_options *)
Definition at line 942 of file ada-valprint.c.
References ada_check_typedef(), ada_is_array_descriptor_type(), ada_is_bogus_array_descriptor(), ada_to_fixed_value(), value::address, current_language, value_print_options::deref_ref, fprintf_filtered(), TYPE_CODE, TYPE_CODE_INT, TYPE_CODE_PTR, TYPE_CODE_TYPEDEF, TYPE_LENGTH, type_print(), TYPE_TARGET_TYPE, TYPE_UNSIGNED, val_print(), value_address(), value_contents_for_printing(), value_embedded_offset(), and value_type().
struct value* ada_value_struct_elt (struct value * , char * , int) [read]
Definition at line 6861 of file ada-lang.c.
References _, ada_check_typedef(), ada_coerce_ref(), ada_get_base_type(), ada_search_struct_field(), ada_to_fixed_type(), ada_value_ind(), ada_value_primitive_packed_val(), coerce_ref(), error(), find_struct_field(), TYPE_CODE, TYPE_CODE_PTR, TYPE_CODE_REF, TYPE_CODE_STRUCT, TYPE_CODE_UNION, TYPE_TARGET_TYPE, value_address(), value_at_lazy(), value_ind(), and value_type().
Referenced by ada_get_tsd_from_tag(), ada_tag_name_from_tsd(), ada_value_tag(), ada_which_variant_applies(), is_ada95_tag(), and unwrap_value().
struct value* ada_value_subscript (struct value * , int , struct value **) [read]
Definition at line 2590 of file ada-lang.c.
References _, ada_check_typedef(), ada_coerce_to_simple_array(), error(), pos_atr(), TYPE_CODE, TYPE_CODE_ARRAY, TYPE_FIELD_BITSIZE, value_subscript(), value_subscript_packed(), and value_type().
Referenced by ada_varobj_simple_array_elt(), and assign_component().
struct value* ada_value_tag (struct value *) [read]
Definition at line 6131 of file ada-lang.c.
References ada_value_struct_elt().
Referenced by ada_tag_value_at_base_address().
char* ada_variant_discrim_name (struct type *)
Definition at line 6465 of file ada-lang.c.
References ada_type_name(), GROW_VECT, name, type, TYPE_CODE, TYPE_CODE_PTR, and TYPE_TARGET_TYPE.
Referenced by ada_variant_discrim_type(), ada_which_variant_applies(), is_unchecked_variant(), and print_variant_part().
struct type* ada_variant_discrim_type (struct type * , struct type *) [read]
Definition at line 6441 of file ada-lang.c.
References ada_lookup_struct_elt_type(), ada_variant_discrim_name(), and name.
Referenced by print_variant_clauses().
int ada_which_variant_applies (struct type * , struct type * , const gdb_byte *)
Definition at line 7112 of file ada-lang.c.
References ada_in_variant(), ada_is_others_clause(), ada_value_struct_elt(), ada_variant_discrim_name(), LONGEST, TYPE_NFIELDS, value_as_long(), and value_from_contents_and_address().
Referenced by print_variant_part(), and to_fixed_variant_branch_type().
void clear_ada_sym_cache (void)
void create_ada_exception_catchpoint (struct gdbarch * gdbarch, enum ada_exception_catchpoint_kind ex_kind, char * excep_string, char * cond_string, int tempflag, int disabled, int from_tty)
Definition at line 12184 of file ada-lang.c.
References ada_exception_sal(), ada_catchpoint::base, create_excep_cond_exprs(), ada_catchpoint::excep_string, init_ada_exception_breakpoint(), install_breakpoint(), and set_breakpoint_condition().
Referenced by catch_ada_exception_command(), catch_assert_command(), mi_cmd_catch_assert(), and mi_cmd_catch_exception().
LONGEST get_int_var_value (char * , int *)
Definition at line 10802 of file ada-lang.c.
References get_var_value(), and value_as_long().
Referenced by ada_to_fixed_type_1(), print_dynamic_range_bound(), and to_fixed_range_type().
int get_selections (int * , int , int , int , char *)
Definition at line 3644 of file ada-lang.c.
References _, command_line_input(), error(), error_no_arg(), and skip_spaces().
Referenced by user_select_syms().
void* grow_vect (void * , size_t * , size_t , int)
Definition at line 466 of file ada-lang.c.
References xrealloc().
void iterate_over_live_ada_tasks (ada_task_list_iterator_ftype * iterator)
Definition at line 357 of file ada-tasks.c.
References ada_build_task_list(), ada_task_is_alive(), current_inferior(), get_ada_tasks_inferior_data(), VEC_index, and VEC_length.
Referenced by ravenscar_find_new_threads().
void print_ada_task_info (struct ui_out * uiout, char * taskno_str, struct inferior * inf)
Definition at line 1001 of file ada-tasks.c.
References _, ada_build_task_list(), ada_task_info::called_task, ada_task_info::caller_task, do_cleanups(), Entry_Caller_Sleep, gdb_assert, get_ada_tasks_inferior_data(), get_task_number_from_id(), inferior_ptid, make_cleanup_ui_out_table_begin_end(), make_cleanup_ui_out_tuple_begin_end(), ada_task_info::name, ada_task_info::parent, parse_and_eval(), pid_to_thread_id(), ada_task_info::priority, ada_task_info::ptid, ptid_equal(), ada_task_info::state, target_find_new_threads(), ada_task_info::task_id, ui_left, ui_noalign, ui_out_field_fmt(), ui_out_field_int(), ui_out_field_skip(), ui_out_field_string(), ui_out_is_mi_like_p(), ui_out_message(), ui_out_table_body(), ui_out_table_header(), ui_out_text(), ui_right, value_as_long(), VEC_index, and VEC_length.
Referenced by info_tasks_command(), and mi_cmd_ada_task_info().
int user_select_syms (struct ada_symbol_info * , int , int)
Definition at line 3527 of file ada-lang.c.
References _, ada_print_type(), error(), find_function_start_sal(), gdb_stdout, get_selections(), symtab_and_line::line, LOC_BLOCK, LOC_CONST, multiple_symbols_all, multiple_symbols_cancel, multiple_symbols_select_mode(), printf_unfiltered(), sort_choices(), ada_symbol_info::sym, SYMBOL_CLASS, SYMBOL_LINE, SYMBOL_PRINT_NAME, SYMBOL_SYMTAB, SYMBOL_TYPE, symtab_and_line::symtab, symtab_to_filename_for_display(), TYPE_CODE, TYPE_CODE_ENUM, TYPE_NAME, and type_print_raw_options.
Referenced by ada_resolve_function(), and resolve_subexp().
int valid_task_id (int)
Definition at line 334 of file ada-tasks.c.
References ada_build_task_list(), current_inferior(), get_ada_tasks_inferior_data(), and VEC_length.
Referenced by bppy_set_task(), and find_condition_and_thread().
Variable Documentation
struct ada_opname_map ada_opname_table[]
Definition at line 840 of file ada-lang.c.
Referenced by is_ada_operator().