GDB (xrefs): /home/stan/gdb/src/gdb/ada-lang.c File Reference
/home/stan/gdb/src/gdb/ada-lang.c File Reference
#include "defs.h"
#include <stdio.h>
#include "gdb_string.h"
#include <ctype.h>
#include <stdarg.h>
#include "demangle.h"
#include "gdb_regex.h"
#include "frame.h"
#include "symtab.h"
#include "gdbtypes.h"
#include "gdbcmd.h"
#include "expression.h"
#include "parser-defs.h"
#include "language.h"
#include "c-lang.h"
#include "inferior.h"
#include "symfile.h"
#include "objfiles.h"
#include "breakpoint.h"
#include "gdbcore.h"
#include "hashtab.h"
#include "gdb_obstack.h"
#include "ada-lang.h"
#include "completer.h"
#include "gdb_stat.h"
#include "block.h"
#include "infcall.h"
#include "dictionary.h"
#include "exceptions.h"
#include "annotate.h"
#include "valprint.h"
#include "source.h"
#include "observer.h"
#include "vec.h"
#include "stack.h"
#include "gdb_vecs.h"
#include "typeprint.h"
#include "psymtab.h"
#include "value.h"
#include "mi/mi-common.h"
#include "arch-utils.h"
#include "cli/cli-utils.h"
Classes
struct ada_inferior_data
struct match_data
struct add_partial_datum
struct exception_support_info
struct ada_catchpoint_location
struct ada_catchpoint
Defines
#define TRUNCATION_TOWARDS_ZERO ((-5 / 2) == -2)
#define MAX_ADA_DIMENS (sizeof(bound_name) / (2*sizeof(char *)))
#define ADA_OPERATORS
#define OP_DEFN(op, len, args, binop) case op: *oplenp = len; *argsp = args; break;
#define OP_DEFN(op, len, args, binop) case op: return #op;
#define OP_DEFN(op, len, args, binop) case op: *oplenp = len; *argsp = args; break;
Typedefs
typedef CORE_ADDR(ada_unhandled_exception_name_addr_ftype)(void)
Enumerations
enum ada_primitive_types {
ada_primitive_type_int, ada_primitive_type_long, ada_primitive_type_short, ada_primitive_type_char,
ada_primitive_type_float, ada_primitive_type_double, ada_primitive_type_void, ada_primitive_type_long_long,
ada_primitive_type_long_double, ada_primitive_type_natural, ada_primitive_type_positive, ada_primitive_type_system_address,
nr_ada_primitive_types
}
Functions
static struct type * desc_base_type (struct type *)
static struct type * desc_bounds_type (struct type *)
static struct value * desc_bounds (struct value *)
static int fat_pntr_bounds_bitpos (struct type *)
static int fat_pntr_bounds_bitsize (struct type *)
static struct type * desc_data_target_type (struct type *)
static struct value * desc_data (struct value *)
static int fat_pntr_data_bitpos (struct type *)
static int fat_pntr_data_bitsize (struct type *)
static struct value * desc_one_bound (struct value *, int, int)
static int desc_bound_bitpos (struct type *, int, int)
static int desc_bound_bitsize (struct type *, int, int)
static struct type * desc_index_type (struct type *, int)
static int desc_arity (struct type *)
static int ada_type_match (struct type *, struct type *, int)
static int ada_args_match (struct symbol *, struct value **, int)
static int full_match (const char *, const char *)
static struct value * make_array_descriptor (struct type *, struct value *)
static void ada_add_block_symbols (struct obstack *, struct block *, const char *, domain_enum, struct objfile *, int)
static int is_nonfunction (struct ada_symbol_info *, int)
static void add_defn_to_vec (struct obstack *, struct symbol *, struct block *)
static int num_defns_collected (struct obstack *)
static struct ada_symbol_info * defns_collected (struct obstack *, int)
static struct value * resolve_subexp (struct expression **, int *, int, struct type *)
static void replace_operator_with_call (struct expression **, int, int, int, struct symbol *, const struct block *)
static int possible_user_operator_p (enum exp_opcode, struct value **)
static char * ada_op_name (enum exp_opcode)
static const char * ada_decoded_op_name (enum exp_opcode)
static int numeric_type_p (struct type *)
static int integer_type_p (struct type *)
static int scalar_type_p (struct type *)
static int discrete_type_p (struct type *)
static enum ada_renaming_category parse_old_style_renaming (struct type *, const char **, int *, const char **)
static struct symbol * find_old_style_renaming_symbol (const char *, const struct block *)
static struct type * ada_lookup_struct_elt_type (struct type *, char *, int, int, int *)
static struct value * evaluate_subexp_type (struct expression *, int *)
static struct type * ada_find_parallel_type_with_name (struct type *, const char *)
static int is_dynamic_field (struct type *, int)
static struct type * to_fixed_variant_branch_type (struct type *, const gdb_byte *, CORE_ADDR, struct value *)
static struct type * to_fixed_array_type (struct type *, struct value *, int)
static struct type * to_fixed_range_type (struct type *, struct value *)
static struct type * to_static_fixed_type (struct type *)
static struct type * static_unwrap_type (struct type *type)
static struct value * unwrap_value (struct value *)
static struct type * constrained_packed_array_type (struct type *, long *)
static struct type * decode_constrained_packed_array_type (struct type *)
static long decode_packed_array_bitsize (struct type *)
static struct value * decode_constrained_packed_array (struct value *)
static int ada_is_packed_array_type (struct type *)
static int ada_is_unconstrained_packed_array_type (struct type *)
static struct value * value_subscript_packed (struct value *, int, struct value **)
static void move_bits (gdb_byte *, int, const gdb_byte *, int, int, int)
static struct value * coerce_unspec_val_to_type (struct value *, struct type *)
static struct value * get_var_value (char *, char *)
static int lesseq_defined_than (struct symbol *, struct symbol *)
static int equiv_types (struct type *, struct type *)
static int is_name_suffix (const char *)
static int advance_wild_match (const char **, const char *, int)
static int wild_match (const char *, const char *)
static struct value * ada_coerce_ref (struct value *)
static LONGEST pos_atr (struct value *)
static struct value * value_pos_atr (struct type *, struct value *)
static struct value * value_val_atr (struct type *, struct value *)
static struct symbol * standard_lookup (const char *, const struct block *, domain_enum)
static struct value * ada_search_struct_field (char *, struct value *, int, struct type *)
static struct value * ada_value_primitive_field (struct value *, int, int, struct type *)
static int find_struct_field (const char *, struct type *, int, struct type **, int *, int *, int *, int *)
static struct value * ada_to_fixed_value_create (struct type *, CORE_ADDR, struct value *)
static int ada_resolve_function (struct ada_symbol_info *, int, struct value **, int, const char *, struct type *)
static int ada_is_direct_array_type (struct type *)
static void ada_language_arch_info (struct gdbarch *, struct language_arch_info *)
static void check_size (const struct type *)
static struct value * ada_index_struct_field (int, struct value *, int, struct type *)
static struct value * assign_aggregate (struct value *, struct value *, struct expression *, int *, enum noside)
static void aggregate_assign_from_choices (struct value *, struct value *, struct expression *, int *, LONGEST *, int *, int, LONGEST, LONGEST)
static void aggregate_assign_positional (struct value *, struct value *, struct expression *, int *, LONGEST *, int *, int, LONGEST, LONGEST)
static void aggregate_assign_others (struct value *, struct value *, struct expression *, int *, LONGEST *, int, LONGEST, LONGEST)
static void add_component_interval (LONGEST, LONGEST, LONGEST *, int *, int)
static struct value * ada_evaluate_subexp (struct type *, struct expression *, int *, enum noside)
static void ada_forward_operator_length (struct expression *, int, int *, int *)
static struct type * ada_find_any_type (const char *name)
static void ada_inferior_data_cleanup (struct inferior *inf, void *arg)
static struct ada_inferior_data * get_ada_inferior_data (struct inferior *inf)
static void ada_inferior_exit (struct inferior *inf)
static struct type * ada_typedef_target_type (struct type *type)
static const char * ada_unqualified_name (const char *decoded_name)
static char * add_angle_brackets (const char *str)
static char * ada_get_gdb_completer_word_break_characters (void)
static void ada_print_array_index (struct value *index_value, struct ui_file *stream, const struct value_print_options *options)
void * grow_vect (void *vect, size_t *size, size_t min_size, int element_size)
static int field_name_match (const char *field_name, const char *target)
int ada_get_field_index (const struct type *type, const char *field_name, int maybe_missing)
int ada_name_prefix_len (const char *name)
static int is_suffix (const char *str, const char *suffix)
static const gdb_byte * cond_offset_host (const gdb_byte *valaddr, long offset)
static CORE_ADDR cond_offset_target (CORE_ADDR address, long offset)
static void lim_warning (const char *format,...) ATTRIBUTE_PRINTF(1
static LONGEST max_of_size (int size)
static LONGEST min_of_size (int size)
static ULONGEST umax_of_size (int size)
static LONGEST max_of_type (struct type *t)
static LONGEST min_of_type (struct type *t)
LONGEST ada_discrete_type_high_bound (struct type *type)
LONGEST ada_discrete_type_low_bound (struct type *type)
static struct type * get_base_type (struct type *type)
struct value * ada_get_decoded_value (struct value *value)
struct type * ada_get_decoded_type (struct type *type)
enum language ada_update_initial_language (enum language lang)
char * ada_main_name (void)
char * ada_encode (const char *decoded)
char * ada_fold_name (const char *name)
static int is_lower_alphanum (const char c)
static void ada_remove_trailing_digits (const char *encoded, int *len)
static void ada_remove_po_subprogram_suffix (const char *encoded, int *len)
static void ada_remove_Xbn_suffix (const char *encoded, int *len)
const char * ada_decode (const char *encoded)
const char * ada_decode_symbol (const struct general_symbol_info *arg)
static char * ada_la_decode (const char *encoded, int options)
static int match_name (const char *sym_name, const char *name, int wild)
void ada_fixup_array_indexes_type (struct type *index_desc_type)
static int is_thin_pntr (struct type *type)
static struct type * thin_descriptor_type (struct type *type)
static struct value * thin_data_pntr (struct value *val)
static int is_thick_pntr (struct type *type)
static int ada_is_array_type (struct type *type)
int ada_is_simple_array_type (struct type *type)
int ada_is_array_descriptor_type (struct type *type)
int ada_is_bogus_array_descriptor (struct type *type)
struct type * ada_type_of_array (struct value *arr, int bounds)
struct value * ada_coerce_to_simple_array_ptr (struct value *arr)
struct value * ada_coerce_to_simple_array (struct value *arr)
struct type * ada_coerce_to_simple_array_type (struct type *type)
int ada_is_constrained_packed_array_type (struct type *type)
static int has_negatives (struct type *type)
struct value * ada_value_primitive_packed_val (struct value *obj, const gdb_byte *valaddr, long offset, int bit_offset, int bit_size, struct type *type)
static struct value * ada_value_assign (struct value *toval, struct value *fromval)
static void value_assign_to_component (struct value *container, struct value *component, struct value *val)
struct value * ada_value_subscript (struct value *arr, int arity, struct value **ind)
static struct value * ada_value_ptr_subscript (struct value *arr, struct type *type, int arity, struct value **ind)
static struct value * ada_value_slice_from_ptr (struct value *array_ptr, struct type *type, int low, int high)
static struct value * ada_value_slice (struct value *array, int low, int high)
int ada_array_arity (struct type *type)
struct type * ada_array_element_type (struct type *type, int nindices)
static struct type * ada_index_type (struct type *type, int n, const char *name)
static LONGEST ada_array_bound_from_type (struct type *arr_type, int n, int which)
static LONGEST ada_array_bound (struct value *arr, int n, int which)
static LONGEST ada_array_length (struct value *arr, int n)
static struct value * empty_array (struct type *arr_type, int low)
static void resolve (struct expression **expp, int void_context_p)
static int return_match (struct type *func_type, struct type *context_type)
static int ada_resolve_function (struct ada_symbol_info syms[], int nsyms, struct value **args, int nargs, const char *name, struct type *context_type)
static int encoded_ordered_before (const char *N0, const char *N1)
static void sort_choices (struct ada_symbol_info syms[], int nsyms)
int user_select_syms (struct ada_symbol_info *syms, int nsyms, int max_results)
int get_selections (int *choices, int n_choices, int max_results, int is_all_choice, char *annotation_suffix)
static int possible_user_operator_p (enum exp_opcode op, struct value *args[])
enum ada_renaming_category ada_parse_renaming (struct symbol *sym, const char **renamed_entity, int *len, const char **renaming_expr)
static struct value * ada_read_renaming_var_value (struct symbol *renaming_sym, struct block *block)
static struct value * ensure_lval (struct value *val)
struct value * ada_convert_actual (struct value *actual, struct type *formal_type0)
static CORE_ADDR value_pointer (struct value *value, struct type *type)
static int lookup_cached_symbol (const char *name, domain_enum namespace, struct symbol **sym, struct block **block)
static void cache_symbol (const char *name, domain_enum namespace, struct symbol *sym, const struct block *block)
static int should_use_wild_match (const char *lookup_name)
static int is_nonfunction (struct ada_symbol_info syms[], int n)
struct bound_minimal_symbol ada_lookup_simple_minsym (const char *name)
static void add_symbols_from_enclosing_procs (struct obstack *obstackp, const char *name, domain_enum namespace, int wild_match_p)
static int is_nondebugging_type (struct type *type)
static int ada_identical_enum_types_p (struct type *type1, struct type *type2)
static int symbols_are_identical_enums (struct ada_symbol_info *syms, int nsyms)
static int remove_extra_symbols (struct ada_symbol_info *syms, int nsyms)
static char * xget_renaming_scope (struct type *renaming_type)
static int is_package_name (const char *name)
static int old_renaming_is_invisible (const struct symbol *sym, const char *function_name)
static int remove_irrelevant_renamings (struct ada_symbol_info *syms, int nsyms, const struct block *current_block)
static void ada_add_local_symbols (struct obstack *obstackp, const char *name, struct block *block, domain_enum domain, int wild_match_p)
static int aux_add_nonlocal_symbols (struct block *block, struct symbol *sym, void *data0)
static int compare_names_with_case (const char *string1, const char *string2, enum case_sensitivity casing)
static int compare_names (const char *string1, const char *string2)
static void add_nonlocal_symbols (struct obstack *obstackp, const char *name, domain_enum domain, int global, int is_wild_match)
static int ada_lookup_symbol_list_worker (const char *name0, const struct block *block0, domain_enum namespace, struct ada_symbol_info **results, int full_search)
int ada_lookup_symbol_list (const char *name0, const struct block *block0, domain_enum domain, struct ada_symbol_info **results)
static void ada_iterate_over_symbols (const struct block *block, const char *name, domain_enum domain, symbol_found_callback_ftype *callback, void *data)
char * ada_name_for_lookup (const char *name)
void ada_lookup_encoded_symbol (const char *name, const struct block *block, domain_enum namespace, struct ada_symbol_info *info)
struct symbol * ada_lookup_symbol (const char *name, const struct block *block0, domain_enum namespace, int *is_a_field_of_this)
static struct symbol * ada_lookup_symbol_nonlocal (const char *name, const struct block *block, const domain_enum domain)
static int is_valid_name_for_wild_match (const char *name0)
static const char * symbol_completion_match (const char *sym_name, const char *text, int text_len, int wild_match_p, int encoded_p)
static void symbol_completion_add (VEC(char_ptr)**sv, const char *sym_name, const char *text, int text_len, const char *orig_text, const char *word, int wild_match_p, int encoded_p)
static int ada_expand_partial_symbol_name (const char *name, void *user_data)
static VEC (char_ptr)
static int ada_is_dispatch_table_ptr_type (struct type *type)
static int ada_is_interface_tag (struct type *type)
int ada_is_ignored_field (struct type *type, int field_num)
int ada_is_tagged_type (struct type *type, int refok)
int ada_is_tag_type (struct type *type)
struct type * ada_tag_type (struct value *val)
static int is_ada95_tag (struct value *tag)
struct value * ada_value_tag (struct value *val)
static struct value * value_tag_from_contents_and_address (struct type *type, const gdb_byte *valaddr, CORE_ADDR address)
static struct type * type_from_tag (struct value *tag)
struct value * ada_tag_value_at_base_address (struct value *obj)
static struct type * ada_get_tsd_type (struct inferior *inf)
static struct value * ada_get_tsd_from_tag (struct value *tag)
static char * ada_tag_name_from_tsd (struct value *tsd)
const char * ada_tag_name (struct value *tag)
struct type * ada_parent_type (struct type *type)
int ada_is_parent_field (struct type *type, int field_num)
int ada_is_wrapper_field (struct type *type, int field_num)
int ada_is_variant_part (struct type *type, int field_num)
struct type * ada_variant_discrim_type (struct type *var_type, struct type *outer_type)
int ada_is_others_clause (struct type *type, int field_num)
char * ada_variant_discrim_name (struct type *type0)
int ada_scan_number (const char str[], int k, LONGEST *R, int *new_k)
int ada_in_variant (LONGEST val, struct type *type, int field_num)
static int num_visible_fields (struct type *type)
static struct value * ada_index_struct_field_1 (int *, struct value *, int, struct type *)
struct value * ada_value_struct_elt (struct value *arg, char *name, int no_err)
static int is_unchecked_variant (struct type *var_type, struct type *outer_type)
int ada_which_variant_applies (struct type *var_type, struct type *outer_type, const gdb_byte *outer_valaddr)
struct value * ada_value_ind (struct value *val0)
static unsigned int align_value (unsigned int off, unsigned int alignment)
static unsigned int field_alignment (struct type *type, int f)
static struct symbol * ada_find_any_type_symbol (const char *name)
struct symbol * ada_find_renaming_symbol (struct symbol *name_sym, const struct block *block)
int ada_prefer_type (struct type *type0, struct type *type1)
const char * ada_type_name (struct type *type)
static struct type * find_parallel_type_by_descriptive_type (struct type *type, const char *name)
struct type * ada_find_parallel_type (struct type *type, const char *suffix)
static struct type * dynamic_template_type (struct type *type)
static int variant_field_index (struct type *type)
static struct type * empty_record (struct type *template)
struct type * ada_template_to_fixed_record_type_1 (struct type *type, const gdb_byte *valaddr, CORE_ADDR address, struct value *dval0, int keep_dynamic_fields)
static struct type * template_to_fixed_record_type (struct type *type, const gdb_byte *valaddr, CORE_ADDR address, struct value *dval0)
static struct type * template_to_static_fixed_type (struct type *type0)
static struct type * to_record_with_fixed_variant_part (struct type *type, const gdb_byte *valaddr, CORE_ADDR address, struct value *dval0)
static struct type * to_fixed_record_type (struct type *type0, const gdb_byte *valaddr, CORE_ADDR address, struct value *dval)
static struct type * ada_to_fixed_type_1 (struct type *type, const gdb_byte *valaddr, CORE_ADDR address, struct value *dval, int check_tag)
struct type * ada_to_fixed_type (struct type *type, const gdb_byte *valaddr, CORE_ADDR address, struct value *dval, int check_tag)
struct type * ada_check_typedef (struct type *type)
struct value * ada_to_fixed_value (struct value *val)
const char * ada_attribute_name (enum exp_opcode n)
int ada_is_character_type (struct type *type)
int ada_is_string_type (struct type *type)
int ada_is_aligner_type (struct type *type)
struct type * ada_get_base_type (struct type *raw_type)
struct type * ada_aligned_type (struct type *type)
const gdb_byte * ada_aligned_value_addr (struct type *type, const gdb_byte *valaddr)
const char * ada_enum_name (const char *name)
static struct value * cast_to_fixed (struct type *type, struct value *arg)
static struct value * cast_from_fixed (struct type *type, struct value *arg)
static int ada_same_array_size_p (struct type *t1, struct type *t2)
static struct value * ada_promote_array_of_integrals (struct type *type, struct value *val)
static struct value * coerce_for_assign (struct type *type, struct value *val)
static struct value * ada_value_binop (struct value *arg1, struct value *arg2, enum exp_opcode op)
static int ada_value_equal (struct value *arg1, struct value *arg2)
static int num_component_specs (struct expression *exp, int pc)
static void assign_component (struct value *container, struct value *lhs, LONGEST index, struct expression *exp, int *pos)
static struct value * ada_value_cast (struct type *type, struct value *arg2, enum noside noside)
static const char * fixed_type_info (struct type *type)
int ada_is_fixed_point_type (struct type *type)
int ada_is_system_address_type (struct type *type)
DOUBLEST ada_delta (struct type *type)
static DOUBLEST scaling_factor (struct type *type)
DOUBLEST ada_fixed_to_float (struct type *type, LONGEST x)
LONGEST ada_float_to_fixed (struct type *type, DOUBLEST x)
static int scan_discrim_bound (char *str, int k, struct value *dval, LONGEST *px, int *pnew_k)
LONGEST get_int_var_value (char *name, int *flag)
int ada_is_range_type_name (const char *name)
int ada_is_modular_type (struct type *type)
ULONGEST ada_modulus (struct type *type)
static CORE_ADDR ada_unhandled_exception_name_addr (void)
static CORE_ADDR ada_unhandled_exception_name_addr_from_raise (void)
static int ada_has_this_exception_support (const struct exception_support_info *einfo)
static void ada_exception_support_info_sniffer (void)
static int is_known_support_routine (struct frame_info *frame)
void ada_find_printable_frame (struct frame_info *fi)
static CORE_ADDR ada_exception_name_addr_1 (enum ada_exception_catchpoint_kind ex, struct breakpoint *b)
static CORE_ADDR ada_exception_name_addr (enum ada_exception_catchpoint_kind ex, struct breakpoint *b)
static char * ada_exception_catchpoint_cond_string (const char *excep_string)
static void ada_catchpoint_location_dtor (struct bp_location *bl)
static void create_excep_cond_exprs (struct ada_catchpoint *c)
static void dtor_exception (enum ada_exception_catchpoint_kind ex, struct breakpoint *b)
static struct bp_location * allocate_location_exception (enum ada_exception_catchpoint_kind ex, struct breakpoint *self)
static void re_set_exception (enum ada_exception_catchpoint_kind ex, struct breakpoint *b)
static int should_stop_exception (const struct bp_location *bl)
static void check_status_exception (enum ada_exception_catchpoint_kind ex, bpstat bs)
static enum print_stop_action print_it_exception (enum ada_exception_catchpoint_kind ex, bpstat bs)
static void print_one_exception (enum ada_exception_catchpoint_kind ex, struct breakpoint *b, struct bp_location **last_loc)
static void print_mention_exception (enum ada_exception_catchpoint_kind ex, struct breakpoint *b)
static void print_recreate_exception (enum ada_exception_catchpoint_kind ex, struct breakpoint *b, struct ui_file *fp)
static void dtor_catch_exception (struct breakpoint *b)
static struct bp_location * allocate_location_catch_exception (struct breakpoint *self)
static void re_set_catch_exception (struct breakpoint *b)
static void check_status_catch_exception (bpstat bs)
static enum print_stop_action print_it_catch_exception (bpstat bs)
static void print_one_catch_exception (struct breakpoint *b, struct bp_location **last_loc)
static void print_mention_catch_exception (struct breakpoint *b)
static void print_recreate_catch_exception (struct breakpoint *b, struct ui_file *fp)
static void dtor_catch_exception_unhandled (struct breakpoint *b)
static struct bp_location * allocate_location_catch_exception_unhandled (struct breakpoint *self)
static void re_set_catch_exception_unhandled (struct breakpoint *b)
static void check_status_catch_exception_unhandled (bpstat bs)
static enum print_stop_action print_it_catch_exception_unhandled (bpstat bs)
static void print_one_catch_exception_unhandled (struct breakpoint *b, struct bp_location **last_loc)
static void print_mention_catch_exception_unhandled (struct breakpoint *b)
static void print_recreate_catch_exception_unhandled (struct breakpoint *b, struct ui_file *fp)
static void dtor_catch_assert (struct breakpoint *b)
static struct bp_location * allocate_location_catch_assert (struct breakpoint *self)
static void re_set_catch_assert (struct breakpoint *b)
static void check_status_catch_assert (bpstat bs)
static enum print_stop_action print_it_catch_assert (bpstat bs)
static void print_one_catch_assert (struct breakpoint *b, struct bp_location **last_loc)
static void print_mention_catch_assert (struct breakpoint *b)
static void print_recreate_catch_assert (struct breakpoint *b, struct ui_file *fp)
static char * ada_get_next_arg (char **argsp)
static void catch_ada_exception_command_split (char *args, enum ada_exception_catchpoint_kind *ex, char **excep_string, char **cond_string)
static const char * ada_exception_sym_name (enum ada_exception_catchpoint_kind ex)
static struct breakpoint_ops * ada_exception_breakpoint_ops (enum ada_exception_catchpoint_kind ex)
static struct symtab_and_line ada_exception_sal (enum ada_exception_catchpoint_kind ex, char *excep_string, char **addr_string, const struct breakpoint_ops **ops)
void create_ada_exception_catchpoint (struct gdbarch *gdbarch, enum ada_exception_catchpoint_kind ex_kind, char *excep_string, char *cond_string, int tempflag, int disabled, int from_tty)
static void catch_ada_exception_command (char *arg, int from_tty, struct cmd_list_element *command)
static void catch_ada_assert_command_split (char *args, char **cond_string)
static void catch_assert_command (char *arg, int from_tty, struct cmd_list_element *command)
static void ada_operator_length (const struct expression *exp, int pc, int *oplenp, int *argsp)
static int ada_operator_check (struct expression *exp, int pos, int(*objfile_func)(struct objfile *objfile, void *data), void *data)
static int ada_dump_subexp_body (struct expression *exp, struct ui_file *stream, int elt)
static void ada_print_subexp (struct expression *exp, int *pos, struct ui_file *stream, enum precedence prec)
static void emit_char (int c, struct type *type, struct ui_file *stream, int quoter)
static int parse (void)
static symbol_name_cmp_ftype ada_get_symbol_name_cmp (const char *lookup_name)
static struct value * ada_read_var_value (struct symbol *var, struct frame_info *frame)
static void set_ada_command (char *arg, int from_tty)
static void show_ada_command (char *args, int from_tty)
static void initialize_ada_catchpoint_ops (void)
void _initialize_ada_language (void)
Variables
static unsigned int varsize_limit
static char * ada_completer_word_break_characters = " \t\n!@#$%^&*()+=|~`}{[]\";:?/,-"
static const char ADA_MAIN_PROGRAM_SYMBOL_NAME [] = "__gnat_ada_main_program_name"
static int warning_limit = 2
static int warnings_issued = 0
static const char * known_runtime_file_name_patterns []
static const char * known_auxiliary_function_name_patterns []
static struct obstack symbol_list_obstack
static struct inferior_data * ada_inferior_data
struct ada_opname_map ada_opname_table []
static struct htab * decoded_names_store
static char * bound_name []
static const char * attribute_names []
static int trust_pad_over_xvs = 1
static char * standard_exc []
static struct
exception_support_info default_exception_support_info
static struct
exception_support_info exception_support_info_fallback
static struct bp_location_ops ada_catchpoint_location_ops
static struct breakpoint_ops catch_exception_breakpoint_ops
static struct breakpoint_ops catch_exception_unhandled_breakpoint_ops
static struct breakpoint_ops catch_assert_breakpoint_ops
static struct op_print ada_op_print_tab []
static struct exp_descriptor ada_exp_descriptor
struct language_defn ada_language_defn
initialize_file_ftype _initialize_ada_language
static struct cmd_list_element * set_ada_list
static struct cmd_list_element * show_ada_list
Define Documentation
#define ADA_OPERATORS
Value:
OP_DEFN (OP_VAR_VALUE, 4, 0, 0) \
    OP_DEFN (BINOP_IN_BOUNDS, 3, 2, 0) \
    OP_DEFN (TERNOP_IN_RANGE, 1, 3, 0) \
    OP_DEFN (OP_ATR_FIRST, 1, 2, 0) \
    OP_DEFN (OP_ATR_LAST, 1, 2, 0) \
    OP_DEFN (OP_ATR_LENGTH, 1, 2, 0) \
    OP_DEFN (OP_ATR_IMAGE, 1, 2, 0) \
    OP_DEFN (OP_ATR_MAX, 1, 3, 0) \
    OP_DEFN (OP_ATR_MIN, 1, 3, 0) \
    OP_DEFN (OP_ATR_MODULUS, 1, 1, 0) \
    OP_DEFN (OP_ATR_POS, 1, 2, 0) \
    OP_DEFN (OP_ATR_SIZE, 1, 1, 0) \
    OP_DEFN (OP_ATR_TAG, 1, 1, 0) \
    OP_DEFN (OP_ATR_VAL, 1, 2, 0) \
    OP_DEFN (UNOP_QUAL, 3, 1, 0) \
    OP_DEFN (UNOP_IN_RANGE, 3, 1, 0) \
    OP_DEFN (OP_OTHERS, 1, 1, 0) \
    OP_DEFN (OP_POSITIONAL, 3, 1, 0) \
    OP_DEFN (OP_DISCRETE_RANGE, 1, 2, 0)
Definition at line 12287 of file ada-lang.c.
Referenced by ada_forward_operator_length(), ada_op_name(), and ada_operator_length().
#define MAX_ADA_DIMENS (sizeof(bound_name) / (2*sizeof(char *)))
Definition at line 1433 of file ada-lang.c.
#define OP_DEFN (op, len, args, binop) case op: *oplenp = len; *argsp = args; break;
#define OP_DEFN (op, len, args, binop) case op: return #op;
#define OP_DEFN (op, len, args, binop) case op: *oplenp = len; *argsp = args; break;
#define TRUNCATION_TOWARDS_ZERO ((-5 / 2) == -2)
Definition at line 74 of file ada-lang.c.
Referenced by ada_value_binop().
Typedef Documentation
typedef CORE_ADDR(ada_unhandled_exception_name_addr_ftype)(void)
Definition at line 10993 of file ada-lang.c.
Enumeration Type Documentation
enum ada_primitive_types
Enumerator:
ada_primitive_type_int
ada_primitive_type_long
ada_primitive_type_short
ada_primitive_type_char
ada_primitive_type_float
ada_primitive_type_double
ada_primitive_type_void
ada_primitive_type_long_long
ada_primitive_type_long_double
ada_primitive_type_natural
ada_primitive_type_positive
ada_primitive_type_system_address
nr_ada_primitive_types
Definition at line 12671 of file ada-lang.c.
Function Documentation
void _initialize_ada_language (void)
Definition at line 12907 of file ada-lang.c.
References _, ada_inferior_data_cleanup(), ada_inferior_exit(), add_catch_command(), add_language(), add_prefix_cmd(), add_setshow_boolean_cmd(), catch_ada_exception_command(), catch_assert_command(), CATCH_PERMANENT, CATCH_TEMPORARY, class_obscure, decoded_names_store, initialize_ada_catchpoint_ops(), no_class, observer_attach_inferior_exit(), set_ada_command(), setlist, show_ada_command(), showlist, streq(), symbol_list_obstack, varsize_limit, xcalloc(), and xfree().
static void ada_add_block_symbols (struct obstack * obstackp, struct block * block, const char * name, domain_enum domain, struct objfile * objfile, int wild) [static]
Definition at line 5602 of file ada-lang.c.
References add_defn_to_vec(), ALL_BLOCK_SYMBOLS, block_iter_match_first(), block_iter_match_next(), fixup_symbol_section(), full_match(), int, is_name_suffix(), LOC_UNRESOLVED, SYMBOL_CLASS, SYMBOL_DOMAIN, SYMBOL_IS_ARGUMENT, SYMBOL_LANGUAGE, SYMBOL_LINKAGE_NAME, symbol_matches_domain(), and wild_match().
Referenced by ada_add_local_symbols(), and ada_lookup_symbol_list_worker().
static void ada_add_local_symbols (struct obstack * obstackp, const char * name, struct block * block, domain_enum domain, int wild_match_p) [static]
Definition at line 4908 of file ada-lang.c.
References ada_add_block_symbols(), add_symbols_from_enclosing_procs(), block_depth(), BLOCK_SUPERBLOCK, defns_collected(), is_nonfunction(), and num_defns_collected().
Referenced by ada_lookup_symbol_list_worker().
struct type* ada_aligned_type (struct type * type) [read]
Definition at line 8670 of file ada-lang.c.
References ada_aligned_type(), ada_get_base_type(), ada_is_aligner_type(), and TYPE_FIELD_TYPE.
Referenced by ada_aligned_type(), ada_print_type(), ada_template_to_fixed_record_type_1(), and printable_val_type().
const gdb_byte* ada_aligned_value_addr (struct type * type, const gdb_byte * valaddr)
Definition at line 8683 of file ada-lang.c.
References ada_aligned_value_addr(), ada_is_aligner_type(), TYPE_FIELD_BITPOS, and TYPE_FIELD_TYPE.
Referenced by ada_aligned_value_addr(), and ada_val_print_1().
static int ada_args_match (struct symbol * func, struct value ** actuals, int n_actuals) [static]
Definition at line 3342 of file ada-lang.c.
References ada_check_typedef(), ada_type_match(), LOC_CONST, SYMBOL_CLASS, SYMBOL_TYPE, TYPE_CODE, TYPE_CODE_ENUM, TYPE_CODE_FUNC, TYPE_FIELD_TYPE, TYPE_NFIELDS, and value_type().
Referenced by ada_resolve_function().
int ada_array_arity (struct type * type)
Definition at line 2678 of file ada-lang.c.
References ada_check_typedef(), desc_arity(), desc_base_type(), desc_bounds_type(), TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_STRUCT, and TYPE_TARGET_TYPE.
Referenced by ada_array_element_type(), ada_index_type(), ada_is_string_type(), ada_type_of_array(), make_array_descriptor(), and print_array_type().
static LONGEST ada_array_bound (struct value * arr, int n, int which) [static]
Definition at line 2832 of file ada-lang.c.
References ada_array_bound_from_type(), ada_is_constrained_packed_array_type(), ada_is_simple_array_type(), decode_constrained_packed_array(), desc_bounds(), desc_one_bound(), value_as_long(), and value_type().
Referenced by make_array_descriptor().
static LONGEST ada_array_bound_from_type (struct type * arr_type, int n, int which) [static]
Definition at line 2790 of file ada-lang.c.
References ada_discrete_type_high_bound(), ada_discrete_type_low_bound(), ada_find_parallel_type(), ada_fixup_array_indexes_type(), ada_is_constrained_packed_array_type(), ada_is_simple_array_type(), decode_constrained_packed_array_type(), gdb_assert, LONGEST, to_fixed_range_type(), type, TYPE_CODE, TYPE_CODE_PTR, TYPE_FIELD_TYPE, TYPE_INDEX_TYPE, and TYPE_TARGET_TYPE.
Referenced by ada_array_bound(), and ada_array_length().
struct type* ada_array_element_type (struct type * type, int nindices) [read]
Definition at line 2706 of file ada-lang.c.
References ada_array_arity(), ada_check_typedef(), desc_base_type(), desc_data_target_type(), type, TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_STRUCT, and TYPE_TARGET_TYPE.
Referenced by ada_is_string_type(), ada_type_of_array(), empty_array(), and print_array_type().
static LONGEST ada_array_length (struct value * arr, int n) [static]
Definition at line 2851 of file ada-lang.c.
References ada_array_bound_from_type(), ada_check_typedef(), ada_is_constrained_packed_array_type(), ada_is_simple_array_type(), decode_constrained_packed_array(), desc_bounds(), desc_one_bound(), value_as_long(), and value_type().
const char* ada_attribute_name (enum exp_opcode n)
Definition at line 8478 of file ada-lang.c.
Referenced by ada_print_subexp().
static void ada_catchpoint_location_dtor (struct bp_location * bl) [static]
Definition at line 11393 of file ada-lang.c.
References ada_catchpoint_location::excep_cond_expr, and xfree().
struct type* ada_check_typedef (struct type * type) [read]
Definition at line 8384 of file ada-lang.c.
References ada_check_typedef(), ada_find_any_type(), ada_typedef_target_type(), CHECK_TYPEDEF, is_thick_pntr(), name, type, TYPE_CODE, TYPE_CODE_ENUM, TYPE_CODE_TYPEDEF, TYPE_STUB, and TYPE_TAG_NAME.
Referenced by ada_args_match(), ada_array_arity(), ada_array_element_type(), ada_array_length(), ada_check_typedef(), ada_coerce_to_simple_array_type(), ada_convert_actual(), ada_fixup_array_indexes_type(), ada_get_decoded_value(), ada_index_struct_field_1(), ada_is_aligner_type(), ada_is_array_descriptor_type(), ada_is_direct_array_type(), ada_is_packed_array_type(), ada_is_parent_field(), ada_is_simple_array_type(), ada_is_string_type(), ada_lookup_struct_elt_type(), ada_parent_type(), ada_print_scalar(), ada_print_type(), ada_print_typedef(), ada_resolve_function(), ada_search_struct_field(), ada_template_to_fixed_record_type_1(), ada_to_fixed_type_1(), ada_type_match(), ada_type_of_array(), ada_val_print_1(), ada_value_binop(), ada_value_cast(), ada_value_primitive_field(), ada_value_primitive_packed_val(), ada_value_print(), ada_value_slice(), ada_value_slice_from_ptr(), ada_value_struct_elt(), ada_value_subscript(), ada_varobj_decode_var(), coerce_for_assign(), coerce_unspec_val_to_type(), constrained_packed_array_type(), decode_constrained_packed_array(), decode_constrained_packed_array_type(), decode_packed_array_bitsize(), desc_base_type(), desc_bounds(), desc_bounds_type(), desc_data_target_type(), dynamic_template_type(), empty_array(), ensure_lval(), fat_pntr_bounds_bitsize(), find_struct_field(), make_array_descriptor(), possible_user_operator_p(), print_record(), static_unwrap_type(), template_to_static_fixed_type(), thin_data_pntr(), to_fixed_array_type(), to_static_fixed_type(), unwrap_value(), and value_subscript_packed().
static struct value * ada_coerce_ref (struct value * val0) [static, read]
Definition at line 7196 of file ada-lang.c.
References ada_is_tagged_type(), ada_tag_value_at_base_address(), ada_to_fixed_value(), coerce_ref(), TYPE_CODE, TYPE_CODE_REF, and value_type().
Referenced by ada_value_assign(), ada_value_equal(), ada_value_struct_elt(), and decode_constrained_packed_array().
struct value* ada_coerce_to_simple_array (struct value * arr) [read]
Definition at line 1935 of file ada-lang.c.
References _, ada_coerce_to_simple_array_ptr(), ada_is_array_descriptor_type(), ada_is_constrained_packed_array_type(), check_size(), decode_constrained_packed_array(), error(), TYPE_TARGET_TYPE, value_ind(), and value_type().
Referenced by ada_get_decoded_value(), ada_val_print_1(), ada_value_assign(), ada_value_equal(), and ada_value_subscript().
struct value* ada_coerce_to_simple_array_ptr (struct value * arr) [read]
Definition at line 1914 of file ada-lang.c.
References ada_is_array_descriptor_type(), ada_is_constrained_packed_array_type(), ada_type_of_array(), decode_constrained_packed_array(), desc_data(), value_cast(), value_copy(), and value_type().
Referenced by ada_coerce_to_simple_array(), ada_get_decoded_value(), ada_val_print_1(), and read_atcb().
struct type* ada_coerce_to_simple_array_type (struct type * type) [read]
Definition at line 1957 of file ada-lang.c.
References ada_check_typedef(), ada_is_array_descriptor_type(), ada_is_constrained_packed_array_type(), decode_constrained_packed_array_type(), desc_data_target_type(), and type.
Referenced by ada_get_decoded_type(), ada_varobj_ind(), and print_array_type().
struct value* ada_convert_actual (struct value * actual, struct type * formal_type0) [read]
Definition at line 4103 of file ada-lang.c.
References ada_check_typedef(), ada_is_array_descriptor_type(), ada_value_ind(), allocate_value(), desc_data(), ensure_lval(), lval_memory, make_array_descriptor(), memcpy(), TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_PTR, TYPE_CODE_REF, TYPE_LENGTH, TYPE_TARGET_TYPE, value_addr(), value_cast_pointers(), value_contents(), value_contents_raw(), VALUE_LVAL, and value_type().
Referenced by value_arg_coerce().
const char* ada_decode (const char * encoded)
Definition at line 1036 of file ada-lang.c.
References ada_remove_po_subprogram_suffix(), ada_remove_trailing_digits(), ada_opname_map::decoded, ada_opname_map::encoded, GROW_VECT, is_lower_alphanum(), p, strstr(), and xsnprintf().
Referenced by ada_decode_symbol(), ada_la_decode(), ada_varobj_describe_simple_array_child(), is_valid_name_for_wild_match(), symbol_completion_match(), and write_object_renaming().
const char* ada_decode_symbol (const struct general_symbol_info * arg)
Definition at line 1300 of file ada-lang.c.
References ada_decode(), general_symbol_info::ada_mangled, decoded_names_store, general_symbol_info::language_specific, general_symbol_info::mangled_lang, general_symbol_info::name, and general_symbol_info::obstack.
Referenced by symbol_demangled_name(), and symbol_natural_name().
static const char * ada_decoded_op_name (enum exp_opcode op) [static]
Definition at line 2888 of file ada-lang.c.
References _, ada_opname_map::decoded, ada_opname_map::encoded, and error().
Referenced by resolve_subexp().
DOUBLEST ada_delta (struct type * type)
Definition at line 10665 of file ada-lang.c.
References DOUBLEST_SCAN_FORMAT, encoding, and fixed_type_info().
Referenced by print_fixed_point_type().
LONGEST ada_discrete_type_high_bound (struct type * type)
Definition at line 687 of file ada-lang.c.
References _, error(), max_of_type(), TYPE_CODE, TYPE_CODE_BOOL, TYPE_CODE_CHAR, TYPE_CODE_ENUM, TYPE_CODE_INT, TYPE_CODE_RANGE, TYPE_FIELD_ENUMVAL, TYPE_HIGH_BOUND, and TYPE_NFIELDS.
Referenced by ada_array_bound_from_type(), print_range(), and to_fixed_range_type().
LONGEST ada_discrete_type_low_bound (struct type * type)
Definition at line 707 of file ada-lang.c.
References _, error(), min_of_type(), TYPE_CODE, TYPE_CODE_BOOL, TYPE_CODE_CHAR, TYPE_CODE_ENUM, TYPE_CODE_INT, TYPE_CODE_RANGE, TYPE_FIELD_ENUMVAL, and TYPE_LOW_BOUND.
Referenced by ada_array_bound_from_type(), ada_value_slice_from_ptr(), ada_varobj_describe_simple_array_child(), print_range(), and to_fixed_range_type().
static int ada_dump_subexp_body (struct expression * exp, struct ui_file * stream, int elt) [static]
Definition at line 12428 of file ada-lang.c.
References _, ada_forward_operator_length(), dump_subexp(), dump_subexp_body_standard(), expression::elts, fprintf_filtered(), gdb_print_host_address(), len, exp_element::longconst, longest_to_int(), exp_element::opcode, exp_element::string, exp_element::type, and type_print().
char* ada_encode (const char * decoded)
Definition at line 869 of file ada-lang.c.
References _, ada_opname_map::decoded, ada_opname_map::encoded, error(), GROW_VECT, and p.
Referenced by ada_lookup_symbol(), ada_name_for_lookup(), block_lookup(), resolve_subexp(), type_from_tag(), VEC(), and write_var_or_type().
const char* ada_enum_name (const char * name)
Definition at line 8699 of file ada-lang.c.
References GROW_VECT, name, strrchr(), strstr(), and xsnprintf().
Referenced by ada_print_scalar(), ada_val_print_1(), and print_enum_type().
static struct value* ada_evaluate_subexp (struct type * expect_type, struct expression * exp, int * pos, enum noside noside) [static, read]
Referenced by aggregate_assign_from_choices(), aggregate_assign_others(), aggregate_assign_positional(), assign_component(), and num_component_specs().
static struct breakpoint_ops* ada_exception_breakpoint_ops (enum ada_exception_catchpoint_kind ex) [static, read]
Definition at line 12063 of file ada-lang.c.
References _, ada_catch_assert, ada_catch_exception, ada_catch_exception_unhandled, catch_assert_breakpoint_ops, catch_exception_breakpoint_ops, catch_exception_unhandled_breakpoint_ops, and internal_error().
Referenced by ada_exception_sal().
static char * ada_exception_catchpoint_cond_string (const char * excep_string) [static]
Definition at line 12091 of file ada-lang.c.
References standard_exc, and xstrprintf().
Referenced by create_excep_cond_exprs().
static CORE_ADDR ada_exception_name_addr (enum ada_exception_catchpoint_kind ex, struct breakpoint * b) [static]
Definition at line 11338 of file ada-lang.c.
References _, ada_exception_name_addr_1(), gdb_exception::message, gdb_exception::reason, RETURN_MASK_ERROR, TRY_CATCH, and warning().
Referenced by print_it_exception().
static CORE_ADDR ada_exception_name_addr_1 (enum ada_exception_catchpoint_kind ex, struct breakpoint * b) [static]
Definition at line 11305 of file ada-lang.c.
References _, ada_catch_assert, ada_catch_exception, ada_catch_exception_unhandled, current_inferior(), ada_inferior_data::exception_info, get_ada_inferior_data(), internal_error(), parse_and_eval_address(), and exception_support_info::unhandled_exception_name_addr.
Referenced by ada_exception_name_addr().
static struct symtab_and_line ada_exception_sal (enum ada_exception_catchpoint_kind ex, char * excep_string, char ** addr_string, const struct breakpoint_ops ** ops) [static, read]
Definition at line 12136 of file ada-lang.c.
References ada_exception_breakpoint_ops(), ada_exception_support_info_sniffer(), ada_exception_sym_name(), find_function_start_sal(), gdb_assert, LOC_BLOCK, standard_lookup(), SYMBOL_CLASS, and VAR_DOMAIN.
Referenced by create_ada_exception_catchpoint().
static void ada_exception_support_info_sniffer (void) [static]
Definition at line 11106 of file ada-lang.c.
References _, ada_has_this_exception_support(), ada_update_initial_language(), current_inferior(), default_exception_support_info, error(), ada_inferior_data::exception_info, exception_support_info_fallback, get_ada_inferior_data(), inferior_ptid, language_ada, language_unknown, and ptid_get_pid().
Referenced by ada_exception_sal().
static const char* ada_exception_sym_name (enum ada_exception_catchpoint_kind ex) [static]
Definition at line 12036 of file ada-lang.c.
References _, ada_catch_assert, ada_catch_exception, ada_catch_exception_unhandled, exception_support_info::catch_assert_sym, exception_support_info::catch_exception_sym, exception_support_info::catch_exception_unhandled_sym, current_inferior(), ada_inferior_data::exception_info, gdb_assert, get_ada_inferior_data(), and internal_error().
Referenced by ada_exception_sal().
static int ada_expand_partial_symbol_name (const char * name, void * user_data) [static]
Definition at line 5880 of file ada-lang.c.
References symbol_completion_match().
Referenced by VEC().
static struct type * ada_find_any_type (const char * name) [static, read]
Definition at line 7273 of file ada-lang.c.
References ada_find_any_type_symbol(), and SYMBOL_TYPE.
Referenced by ada_check_typedef(), ada_find_parallel_type_with_name(), ada_fixup_array_indexes_type(), ada_get_base_type(), ada_get_tsd_type(), find_parallel_type_by_descriptive_type(), and type_from_tag().
static struct symbol* ada_find_any_type_symbol (const char * name) [static, read]
Definition at line 7256 of file ada-lang.c.
References get_selected_block(), LOC_TYPEDEF, standard_lookup(), STRUCT_DOMAIN, SYMBOL_CLASS, and VAR_DOMAIN.
Referenced by ada_find_any_type(), ada_find_renaming_symbol(), and find_old_style_renaming_symbol().
struct type* ada_find_parallel_type (struct type * type, const char * suffix) [read]
Definition at line 7480 of file ada-lang.c.
References ada_find_parallel_type_with_name(), ada_type_name(), len, and name.
Referenced by ada_array_bound_from_type(), ada_get_base_type(), ada_is_aligner_type(), ada_varobj_describe_simple_array_child(), constrained_packed_array_type(), dynamic_template_type(), print_array_type(), print_record_type(), print_variant_clauses(), thin_descriptor_type(), to_fixed_array_type(), to_fixed_variant_branch_type(), to_static_fixed_type(), and unwrap_value().
static struct type * ada_find_parallel_type_with_name (struct type * type, const char * name) [static, read]
Definition at line 7464 of file ada-lang.c.
References ada_find_any_type(), find_parallel_type_by_descriptive_type(), and HAVE_GNAT_AUX_INFO.
Referenced by ada_find_parallel_type(), and decode_constrained_packed_array_type().
void ada_find_printable_frame (struct frame_info * fi)
Definition at line 11225 of file ada-lang.c.
References get_prev_frame(), is_known_support_routine(), and select_frame().
Referenced by print_it_exception(), and task_command_1().
struct symbol* ada_find_renaming_symbol (struct symbol * name_sym, const struct block * block) [read]
Definition at line 7290 of file ada-lang.c.
References ada_find_any_type_symbol(), find_old_style_renaming_symbol(), name, strstr(), and SYMBOL_LINKAGE_NAME.
Referenced by ada_read_var_value(), and write_var_or_type().
DOUBLEST ada_fixed_to_float (struct type * type, LONGEST x)
Definition at line 10711 of file ada-lang.c.
References scaling_factor().
Referenced by ada_val_print_1(), cast_from_fixed(), cast_to_fixed(), and print_fixed_point_type().
void ada_fixup_array_indexes_type (struct type * index_desc_type)
Definition at line 1393 of file ada-lang.c.
References ada_check_typedef(), ada_find_any_type(), gdb_assert, name, TYPE_FIELD_NAME, TYPE_FIELD_TYPE, TYPE_NAME, and TYPE_NFIELDS.
Referenced by ada_array_bound_from_type(), ada_varobj_describe_simple_array_child(), print_array_type(), and to_fixed_array_type().
LONGEST ada_float_to_fixed (struct type * type, DOUBLEST x)
Definition at line 10720 of file ada-lang.c.
References LONGEST, and scaling_factor().
Referenced by cast_to_fixed().
char* ada_fold_name (const char * name)
Definition at line 921 of file ada-lang.c.
References GROW_VECT, and len.
Referenced by ada_lookup_symbol(), and ada_name_for_lookup().
static void ada_forward_operator_length (struct expression * exp, int pc, int * oplenp, int * argsp) [static]
Definition at line 12391 of file ada-lang.c.
References ADA_OPERATORS, BYTES_TO_EXP_ELEM, expression::elts, len, exp_element::longconst, longest_to_int(), and exp_element::opcode.
Referenced by ada_dump_subexp_body(), ada_print_subexp(), and resolve_subexp().
struct type* ada_get_base_type (struct type * raw_type) [read]
Definition at line 8622 of file ada-lang.c.
References ada_find_any_type(), ada_find_parallel_type(), ada_is_aligner_type(), TYPE_CODE, TYPE_CODE_REF, TYPE_CODE_STRUCT, TYPE_FIELD_NAME, TYPE_FIELD_TYPE, TYPE_NFIELDS, and TYPE_TARGET_TYPE.
Referenced by ada_aligned_type(), ada_parent_type(), ada_print_type(), ada_template_to_fixed_record_type_1(), ada_value_struct_elt(), static_unwrap_type(), and unwrap_value().
struct type* ada_get_decoded_type (struct type * type) [read]
Definition at line 771 of file ada-lang.c.
References ada_coerce_to_simple_array_type(), ada_is_constrained_packed_array_type(), to_static_fixed_type(), and type.
Referenced by ada_varobj_decode_var().
struct value* ada_get_decoded_value (struct value * value) [read]
Definition at line 746 of file ada-lang.c.
References ada_check_typedef(), ada_coerce_to_simple_array(), ada_coerce_to_simple_array_ptr(), ada_is_array_descriptor_type(), ada_is_constrained_packed_array_type(), ada_to_fixed_value(), TYPE_CODE, TYPE_CODE_PTR, TYPE_CODE_TYPEDEF, and value_type().
Referenced by ada_varobj_decode_var().
int ada_get_field_index (const struct type * type, const char * field_name, int maybe_missing)
Definition at line 504 of file ada-lang.c.
References _, check_typedef(), error(), field_name_match(), TYPE_FIELD_NAME, TYPE_NAME, and TYPE_NFIELDS.
Referenced by ada_nget_field_index(), get_symbol_field_type(), get_tcb_types_info(), read_atcb(), and read_fat_string_value().
static char* ada_get_gdb_completer_word_break_characters (void) [static]
Definition at line 446 of file ada-lang.c.
References ada_completer_word_break_characters.
static char* ada_get_next_arg (char ** argsp) [static]
Definition at line 11929 of file ada-lang.c.
References skip_spaces(), skip_to_space, and xmalloc().
Referenced by catch_ada_exception_command_split().
static symbol_name_cmp_ftype ada_get_symbol_name_cmp (const char * lookup_name) [static]
Definition at line 12769 of file ada-lang.c.
References compare_names(), should_use_wild_match(), and wild_match().
static struct value* ada_get_tsd_from_tag (struct value * tag) [static, read]
Definition at line 6271 of file ada-lang.c.
References ada_get_tsd_type(), ada_value_struct_elt(), current_inferior(), lookup_pointer_type(), type, value_cast(), value_ind(), and value_ptradd().
Referenced by ada_tag_name().
static struct type* ada_get_tsd_type (struct inferior * inf) [static, read]
Definition at line 6256 of file ada-lang.c.
References ada_find_any_type(), get_ada_inferior_data(), and ada_inferior_data::tsd_type.
Referenced by ada_get_tsd_from_tag().
static int ada_has_this_exception_support (const struct exception_support_info * einfo) [static]
Definition at line 11054 of file ada-lang.c.
References _, exception_support_info::catch_exception_sym, error(), LOC_BLOCK, lookup_minimal_symbol(), mst_solib_trampoline, MSYMBOL_TYPE, standard_lookup(), SYMBOL_CLASS, SYMBOL_LINKAGE_NAME, and VAR_DOMAIN.
Referenced by ada_exception_support_info_sniffer().
static int ada_identical_enum_types_p (struct type * type1, struct type * type2) [static]
Definition at line 4480 of file ada-lang.c.
References ada_remove_trailing_digits(), TYPE_FIELD_ENUMVAL, TYPE_FIELD_NAME, and TYPE_NFIELDS.
Referenced by symbols_are_identical_enums().
int ada_in_variant (LONGEST val, struct type * type, int field_num)
Definition at line 6561 of file ada-lang.c.
References ada_scan_number(), L, LONGEST, name, p, and TYPE_FIELD_NAME.
Referenced by ada_which_variant_applies().
static struct value * ada_index_struct_field (int index, struct value * arg, int offset, struct type * type) [static, read]
Definition at line 6801 of file ada-lang.c.
References ada_index_struct_field_1().
Referenced by assign_component().
static struct value * ada_index_struct_field_1 (int * index_p, struct value * arg, int offset, struct type * type) [static, read]
Definition at line 6813 of file ada-lang.c.
References _, ada_check_typedef(), ada_is_variant_part(), ada_is_wrapper_field(), ada_value_primitive_field(), error(), TYPE_FIELD_BITPOS, TYPE_FIELD_NAME, TYPE_FIELD_TYPE, and TYPE_NFIELDS.
Referenced by ada_index_struct_field().
static struct type* ada_index_type (struct type * type, int n, const char * name) [static, read]
Definition at line 2751 of file ada-lang.c.
References _, ada_array_arity(), ada_is_simple_array_type(), desc_base_type(), desc_bounds_type(), desc_index_type(), error(), TYPE_CODE, TYPE_CODE_UNDEF, TYPE_INDEX_TYPE, and TYPE_TARGET_TYPE.
static void ada_inferior_data_cleanup (struct inferior * inf, void * arg) [static]
Definition at line 336 of file ada-lang.c.
References xfree().
Referenced by _initialize_ada_language(), and ada_inferior_exit().
static void ada_inferior_exit (struct inferior * inf) [static]
Definition at line 372 of file ada-lang.c.
References ada_inferior_data_cleanup().
Referenced by _initialize_ada_language().
int ada_is_aligner_type (struct type * type)
Definition at line 8606 of file ada-lang.c.
References ada_check_typedef(), ada_find_parallel_type(), TYPE_CODE, TYPE_CODE_STRUCT, TYPE_FIELD_NAME, and TYPE_NFIELDS.
Referenced by ada_aligned_type(), ada_aligned_value_addr(), ada_get_base_type(), ada_print_type(), ada_template_to_fixed_record_type_1(), static_unwrap_type(), and unwrap_value().
int ada_is_array_descriptor_type (struct type * type)
Definition at line 1798 of file ada-lang.c.
References ada_check_typedef(), desc_arity(), desc_bounds_type(), desc_data_target_type(), TYPE_CODE, and TYPE_CODE_ARRAY.
Referenced by ada_coerce_to_simple_array(), ada_coerce_to_simple_array_ptr(), ada_coerce_to_simple_array_type(), ada_convert_actual(), ada_get_decoded_value(), ada_is_bogus_array_descriptor(), ada_is_constrained_packed_array_type(), ada_is_direct_array_type(), ada_is_string_type(), ada_is_unconstrained_packed_array_type(), ada_prefer_type(), ada_print_type(), ada_type_match(), ada_type_of_array(), ada_val_print_1(), ada_value_is_changeable_p(), ada_value_print(), ada_varobj_adjust_for_child_access(), ada_varobj_describe_child(), ada_varobj_get_number_of_children(), and ada_varobj_ind().
static int ada_is_array_type (struct type * type) [static]
Definition at line 1772 of file ada-lang.c.
References ada_is_direct_array_type(), TYPE_CODE, TYPE_CODE_PTR, TYPE_CODE_REF, and TYPE_TARGET_TYPE.
Referenced by possible_user_operator_p().
int ada_is_bogus_array_descriptor (struct type * type)
Definition at line 1816 of file ada-lang.c.
References ada_is_array_descriptor_type(), lookup_struct_elt_type(), TYPE_CODE, and TYPE_CODE_STRUCT.
Referenced by ada_print_type(), ada_val_print_1(), and ada_value_print().
int ada_is_character_type (struct type * type)
Definition at line 8549 of file ada-lang.c.
References ada_type_name(), name, TYPE_CODE, TYPE_CODE_CHAR, TYPE_CODE_INT, and TYPE_CODE_RANGE.
Referenced by ada_is_string_type(), and ada_val_print_1().
int ada_is_constrained_packed_array_type (struct type * type)
Definition at line 1986 of file ada-lang.c.
References ada_is_array_descriptor_type(), and ada_is_packed_array_type().
Referenced by ada_array_bound(), ada_array_bound_from_type(), ada_array_length(), ada_coerce_to_simple_array(), ada_coerce_to_simple_array_ptr(), ada_coerce_to_simple_array_type(), ada_get_decoded_type(), ada_get_decoded_value(), ada_prefer_type(), ada_print_type(), ada_type_of_array(), ada_val_print_1(), ada_varobj_adjust_for_child_access(), find_parallel_type_by_descriptive_type(), print_array_type(), and to_fixed_array_type().
static int ada_is_direct_array_type (struct type * type) [static]
Definition at line 1759 of file ada-lang.c.
References ada_check_typedef(), ada_is_array_descriptor_type(), TYPE_CODE, and TYPE_CODE_ARRAY.
Referenced by ada_is_array_type(), ada_value_assign(), ada_value_equal(), and aggregate_assign_from_choices().
static int ada_is_dispatch_table_ptr_type (struct type * type) [static]
Definition at line 6018 of file ada-lang.c.
References name, TYPE_CODE, TYPE_CODE_PTR, TYPE_NAME, and TYPE_TARGET_TYPE.
Referenced by ada_is_ignored_field().
int ada_is_fixed_point_type (struct type * type)
Definition at line 10646 of file ada-lang.c.
References fixed_type_info().
Referenced by ada_print_type(), ada_val_print_1(), ada_value_cast(), and cast_to_fixed().
int ada_is_ignored_field (struct type * type, int field_num)
Definition at line 6049 of file ada-lang.c.
References ada_is_dispatch_table_ptr_type(), ada_is_interface_tag(), ada_is_tagged_type(), name, TYPE_FIELD_NAME, TYPE_FIELD_TYPE, and TYPE_NFIELDS.
Referenced by ada_varobj_describe_struct_child(), ada_varobj_get_struct_number_of_children(), print_field_values(), and print_selected_record_field_types().
static int ada_is_interface_tag (struct type * type) [static]
Definition at line 6035 of file ada-lang.c.
References name, and TYPE_NAME.
Referenced by ada_is_ignored_field().
int ada_is_modular_type (struct type * type)
Definition at line 10940 of file ada-lang.c.
References get_base_type(), TYPE_CODE, TYPE_CODE_INT, TYPE_CODE_RANGE, and TYPE_UNSIGNED.
Referenced by ada_print_type(), and decode_constrained_packed_array().
int ada_is_others_clause (struct type * type, int field_num)
Definition at line 6453 of file ada-lang.c.
References name, and TYPE_FIELD_NAME.
Referenced by ada_which_variant_applies().
static int ada_is_packed_array_type (struct type * type) [static]
Definition at line 1971 of file ada-lang.c.
References ada_check_typedef(), ada_type_name(), desc_base_type(), and strstr().
Referenced by ada_is_constrained_packed_array_type(), and ada_is_unconstrained_packed_array_type().
int ada_is_parent_field (struct type * type, int field_num)
Definition at line 6393 of file ada-lang.c.
References ada_check_typedef(), name, and TYPE_FIELD_NAME.
Referenced by ada_parent_type(), and print_selected_record_field_types().
int ada_is_range_type_name (const char * name)
Definition at line 10929 of file ada-lang.c.
References strstr().
Referenced by ada_print_type().
int ada_is_simple_array_type (struct type * type)
Definition at line 1784 of file ada-lang.c.
References ada_check_typedef(), TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_PTR, and TYPE_TARGET_TYPE.
Referenced by ada_array_bound(), ada_array_bound_from_type(), ada_array_length(), ada_index_type(), ada_is_string_type(), and print_array_type().
int ada_is_string_type (struct type * type)
Definition at line 8573 of file ada-lang.c.
References ada_array_arity(), ada_array_element_type(), ada_check_typedef(), ada_is_array_descriptor_type(), ada_is_character_type(), ada_is_simple_array_type(), TYPE_CODE, and TYPE_CODE_PTR.
Referenced by ada_val_print_array(), ada_value_is_changeable_p(), and ada_varobj_get_value_of_array_variable().
int ada_is_system_address_type (struct type * type)
Definition at line 10654 of file ada-lang.c.
References TYPE_NAME.
Referenced by ada_val_print_1().
int ada_is_tag_type (struct type * type)
Definition at line 6098 of file ada-lang.c.
References ada_type_name(), name, TYPE_CODE, TYPE_CODE_PTR, and TYPE_TARGET_TYPE.
Referenced by ada_tag_name(), and ada_val_print_1().
int ada_is_tagged_type (struct type * type, int refok)
Definition at line 6090 of file ada-lang.c.
References ada_lookup_struct_elt_type().
Referenced by ada_coerce_ref(), ada_is_ignored_field(), ada_to_fixed_type_1(), ada_val_print_1(), ada_value_ind(), ada_varobj_describe_struct_child(), ada_varobj_get_struct_number_of_children(), and print_record_type().
static int ada_is_unconstrained_packed_array_type (struct type * type) [static]
Definition at line 1996 of file ada-lang.c.
References ada_is_array_descriptor_type(), and ada_is_packed_array_type().
Referenced by ada_type_of_array().
int ada_is_variant_part (struct type * type, int field_num)
Definition at line 6425 of file ada-lang.c.
References is_dynamic_field(), TYPE_CODE, TYPE_CODE_UNION, TYPE_FIELD_TYPE, and TYPE_TARGET_TYPE.
Referenced by ada_index_struct_field_1(), ada_lookup_struct_elt_type(), ada_search_struct_field(), ada_template_to_fixed_record_type_1(), ada_varobj_describe_struct_child(), ada_varobj_get_struct_number_of_children(), find_struct_field(), print_field_values(), print_selected_record_field_types(), and variant_field_index().
int ada_is_wrapper_field (struct type * type, int field_num)
Definition at line 6409 of file ada-lang.c.
References name, and TYPE_FIELD_NAME.
Referenced by ada_index_struct_field_1(), ada_lookup_struct_elt_type(), ada_search_struct_field(), ada_varobj_describe_struct_child(), ada_varobj_get_struct_number_of_children(), find_struct_field(), print_field_values(), and print_selected_record_field_types().
static void ada_iterate_over_symbols (const struct block * block, const char * name, domain_enum domain, symbol_found_callback_ftype * callback, void * data) [static]
Definition at line 5248 of file ada-lang.c.
References ada_lookup_symbol_list_worker(), and ada_symbol_info::sym.
static char* ada_la_decode (const char * encoded, int options) [static]
Definition at line 1335 of file ada-lang.c.
References ada_decode().
static void ada_language_arch_info (struct gdbarch * gdbarch, struct language_arch_info * lai) [static]
Definition at line 12688 of file ada-lang.c.
References ada_primitive_type_char, ada_primitive_type_double, ada_primitive_type_float, ada_primitive_type_int, ada_primitive_type_long, ada_primitive_type_long_double, ada_primitive_type_long_long, ada_primitive_type_natural, ada_primitive_type_positive, ada_primitive_type_short, ada_primitive_type_system_address, ada_primitive_type_void, arch_float_type(), arch_integer_type(), arch_type(), language_arch_info::bool_type_default, language_arch_info::bool_type_symbol, builtin_type::builtin_bool, builtin_type(), builtin_type::builtin_void, gdbarch_double_bit(), gdbarch_float_bit(), gdbarch_int_bit(), gdbarch_long_bit(), gdbarch_long_long_bit(), GDBARCH_OBSTACK_CALLOC, gdbarch_short_bit(), lookup_pointer_type(), nr_ada_primitive_types, language_arch_info::primitive_type_vector, language_arch_info::string_char_type, TYPE_CODE_VOID, and TYPE_NAME.
void ada_lookup_encoded_symbol (const char * name, const struct block * block, domain_enum namespace, struct ada_symbol_info * info)
Definition at line 5297 of file ada-lang.c.
References ada_lookup_symbol_list(), fixup_symbol_section(), gdb_assert, memset(), and ada_symbol_info::sym.
Referenced by ada_lookup_symbol(), and write_object_renaming().
struct bound_minimal_symbol ada_lookup_simple_minsym (const char * name) [read]
Definition at line 4415 of file ada-lang.c.
References ALL_MSYMBOLS, match_name(), memset(), bound_minimal_symbol::minsym, mst_solib_trampoline, MSYMBOL_TYPE, name, bound_minimal_symbol::objfile, should_use_wild_match(), and SYMBOL_LINKAGE_NAME.
Referenced by write_var_or_type().
static struct type * ada_lookup_struct_elt_type (struct type * type, char * name, int refok, int noerr, int * dispp) [static, read]
Definition at line 6963 of file ada-lang.c.
References _, ada_check_typedef(), ada_is_variant_part(), ada_is_wrapper_field(), error(), field_name_match(), fprintf_unfiltered(), gdb_flush(), gdb_stderr, gdb_stdout, target_terminal_ours, to_static_fixed_type(), TYPE_CODE, TYPE_CODE_PTR, TYPE_CODE_REF, TYPE_CODE_STRUCT, TYPE_CODE_UNION, TYPE_FIELD_BITPOS, TYPE_FIELD_NAME, TYPE_FIELD_TYPE, TYPE_NFIELDS, type_print(), and TYPE_TARGET_TYPE.
Referenced by ada_is_tagged_type(), ada_tag_type(), ada_variant_discrim_type(), and is_unchecked_variant().
struct symbol* ada_lookup_symbol (const char * name, const struct block * block0, domain_enum namespace, int * is_a_field_of_this) [read]
Definition at line 5322 of file ada-lang.c.
References ada_encode(), ada_fold_name(), ada_lookup_encoded_symbol(), and ada_symbol_info::sym.
Referenced by ada_lookup_symbol_nonlocal(), and find_primitive_type().
int ada_lookup_symbol_list (const char * name0, const struct block * block0, domain_enum domain, struct ada_symbol_info ** results)
Definition at line 5239 of file ada-lang.c.
References ada_lookup_symbol_list_worker().
Referenced by ada_lookup_encoded_symbol(), block_lookup(), get_var_value(), resolve_subexp(), write_name_assoc(), and write_var_or_type().
static int ada_lookup_symbol_list_worker (const char * name0, const struct block * block0, domain_enum namespace, struct ada_symbol_info ** results, int full_search) [static]
Definition at line 5134 of file ada-lang.c.
References ada_add_block_symbols(), ada_add_local_symbols(), add_defn_to_vec(), add_nonlocal_symbols(), cache_symbol(), defns_collected(), lookup_cached_symbol(), name, num_defns_collected(), remove_extra_symbols(), remove_irrelevant_renamings(), should_use_wild_match(), and symbol_list_obstack.
Referenced by ada_iterate_over_symbols(), and ada_lookup_symbol_list().
static struct symbol* ada_lookup_symbol_nonlocal (const char * name, const struct block * block, const domain_enum domain) [static, read]
Definition at line 5336 of file ada-lang.c.
References ada_lookup_symbol(), and block_static_block().
char* ada_main_name (void)
Definition at line 801 of file ada-lang.c.
References _, ADA_MAIN_PROGRAM_SYMBOL_NAME, error(), lookup_minimal_symbol(), SYMBOL_VALUE_ADDRESS, target_read_string(), and xfree().
Referenced by find_main_name().
ULONGEST ada_modulus (struct type * type)
Definition at line 10952 of file ada-lang.c.
References TYPE_HIGH_BOUND, and ULONGEST.
Referenced by ada_print_type(), and decode_constrained_packed_array().
char* ada_name_for_lookup (const char * name)
Definition at line 5273 of file ada-lang.c.
References ada_encode(), ada_fold_name(), memcpy(), and xmalloc().
Referenced by find_linespec_symbols().
int ada_name_prefix_len (const char * name)
Definition at line 524 of file ada-lang.c.
References name, p, and strstr().
Referenced by ada_print_type(), ada_varobj_describe_simple_array_child(), ada_varobj_describe_struct_child(), find_old_style_renaming_symbol(), print_field_values(), and print_range().
static char * ada_op_name (enum exp_opcode opcode) [static]
Definition at line 12366 of file ada-lang.c.
References ADA_OPERATORS, and op_name_standard().
static int ada_operator_check (struct expression * exp, int pos, int(*)(struct objfile *objfile, void *data) objfile_func, void * data) [static]
Definition at line 12338 of file ada-lang.c.
References expression::elts, operator_check_standard(), exp_element::type, and TYPE_OBJFILE.
static void ada_operator_length (const struct expression * exp, int pc, int * oplenp, int * argsp) [static]
Definition at line 12309 of file ada-lang.c.
References ADA_OPERATORS, expression::elts, exp_element::longconst, longest_to_int(), exp_element::opcode, and operator_length_standard().
struct type* ada_parent_type (struct type * type) [read]
Definition at line 6362 of file ada-lang.c.
References ada_check_typedef(), ada_get_base_type(), ada_is_parent_field(), TYPE_CODE, TYPE_CODE_PTR, TYPE_CODE_STRUCT, TYPE_FIELD_TYPE, TYPE_NFIELDS, and TYPE_TARGET_TYPE.
Referenced by print_record_type().
enum ada_renaming_category ada_parse_renaming (struct symbol * sym, const char ** renamed_entity, int * len, const char ** renaming_expr)
Definition at line 3931 of file ada-lang.c.
References ADA_EXCEPTION_RENAMING, ADA_NOT_RENAMING, ADA_OBJECT_RENAMING, ADA_PACKAGE_RENAMING, ADA_SUBPROGRAM_RENAMING, LOC_COMPUTED, LOC_LOCAL, LOC_OPTIMIZED_OUT, LOC_STATIC, LOC_TYPEDEF, parse_old_style_renaming(), strstr(), SYMBOL_CLASS, SYMBOL_LINKAGE_NAME, and SYMBOL_TYPE.
Referenced by remove_irrelevant_renamings(), write_object_renaming(), and write_var_or_type().
int ada_prefer_type (struct type * type0, struct type * type1)
Definition at line 7371 of file ada-lang.c.
References ada_is_array_descriptor_type(), ada_is_constrained_packed_array_type(), strstr(), TYPE_CODE, TYPE_CODE_VOID, TYPE_NAME, and type_name_no_tag().
Referenced by select_possible_type_sym().
static void ada_print_array_index (struct value * index_value, struct ui_file * stream, const struct value_print_options * options) [static]
Definition at line 454 of file ada-lang.c.
References fprintf_filtered(), and LA_VALUE_PRINT.
static void ada_print_subexp (struct expression * exp, int * pos, struct ui_file * stream, enum precedence prec) [static]
Definition at line 12500 of file ada-lang.c.
References ada_attribute_name(), ada_forward_operator_length(), expression::elts, fprintf_filtered(), fputs_filtered(), LA_PRINT_TYPE, exp_element::longconst, exp_element::opcode, PREC_ABOVE_COMMA, PREC_EQUAL, PREC_PREFIX, PREC_SUFFIX, print_subexp(), print_subexp_standard(), exp_element::symbol, SYMBOL_NATURAL_NAME, exp_element::type, TYPE_CODE, TYPE_CODE_VOID, type_print(), and type_print_raw_options.
static struct value* ada_promote_array_of_integrals (struct type * type, struct value * val) [static, read]
Definition at line 8876 of file ada-lang.c.
References _, allocate_value(), error(), gdb_assert, get_array_bounds(), is_integral_type(), LONGEST, memcpy(), TYPE_CODE, TYPE_CODE_ARRAY, TYPE_LENGTH, TYPE_TARGET_TYPE, value_cast(), value_contents_all(), value_contents_writeable(), value_subscript(), and value_type().
Referenced by coerce_for_assign().
static struct value* ada_read_renaming_var_value (struct symbol * renaming_sym, struct block * block) [static, read]
Definition at line 4055 of file ada-lang.c.
References do_cleanups(), evaluate_expression(), free_current_contents(), make_cleanup(), parse_exp_1(), and SYMBOL_LINKAGE_NAME.
Referenced by ada_read_var_value().
static struct value* ada_read_var_value (struct symbol * var, struct frame_info * frame) [static, read]
Definition at line 12780 of file ada-lang.c.
References ada_find_renaming_symbol(), ada_read_renaming_var_value(), default_read_var_value(), and get_frame_block().
static void ada_remove_po_subprogram_suffix (const char * encoded, int * len) [static]
Definition at line 989 of file ada-lang.c.
Referenced by ada_decode(), and find_old_style_renaming_symbol().
static void ada_remove_trailing_digits (const char * encoded, int * len) [static]
Definition at line 966 of file ada-lang.c.
Referenced by ada_decode(), ada_identical_enum_types_p(), and find_old_style_renaming_symbol().
static void ada_remove_Xbn_suffix (const char * encoded, int * len) [static]
Definition at line 1010 of file ada-lang.c.
Referenced by find_old_style_renaming_symbol().
static int ada_resolve_function (struct ada_symbol_info * , int , struct value ** , int , const char * , struct type *) [static]
Referenced by resolve_subexp().
static int ada_resolve_function (struct ada_symbol_info syms[], int nsyms, struct value ** args, int nargs, const char * name, struct type * context_type) [static]
Definition at line 3417 of file ada-lang.c.
References _, ada_args_match(), ada_check_typedef(), arm-linux::m, printf_filtered(), return_match(), SYMBOL_TYPE, and user_select_syms().
static int ada_same_array_size_p (struct type * t1, struct type * t2) [static]
Definition at line 8848 of file ada-lang.c.
References _, error(), get_array_bounds(), and LONGEST.
Referenced by coerce_for_assign().
int ada_scan_number (const char str[], int k, LONGEST * R, int * new_k)
Definition at line 6519 of file ada-lang.c.
References LONGEST, and ULONGEST.
Referenced by ada_in_variant(), print_choices(), print_range_bound(), and to_fixed_range_type().
static struct value * ada_search_struct_field (char * name, struct value * arg, int offset, struct type * type) [static, read]
Definition at line 6740 of file ada-lang.c.
References ada_check_typedef(), ada_is_variant_part(), ada_is_wrapper_field(), ada_value_primitive_field(), field_name_match(), name, TYPE_FIELD_BITPOS, TYPE_FIELD_NAME, TYPE_FIELD_TYPE, and TYPE_NFIELDS.
Referenced by ada_value_struct_elt(), and scan_discrim_bound().
const char* ada_tag_name (struct value * tag)
Definition at line 6331 of file ada-lang.c.
References ada_get_tsd_from_tag(), ada_is_tag_type(), ada_tag_name_from_tsd(), name, RETURN_MASK_ERROR, TRY_CATCH, and value_type().
Referenced by ada_val_print_1(), and type_from_tag().
static char* ada_tag_name_from_tsd (struct value * tsd) [static]
Definition at line 6307 of file ada-lang.c.
References ada_value_struct_elt(), name, p, read_memory_string(), and value_as_address().
Referenced by ada_tag_name().
struct type* ada_tag_type (struct value * val) [read]
Definition at line 6114 of file ada-lang.c.
References ada_lookup_struct_elt_type(), and value_type().
struct value* ada_tag_value_at_base_address (struct value * obj) [read]
Definition at line 6178 of file ada-lang.c.
References ada_value_tag(), builtin_type::builtin_data_ptr, builtin_type(), is_ada95_tag(), LONGEST, lookup_pointer_type(), gdb_exception::reason, RETURN_MASK_ERROR, target_gdbarch(), TRY_CATCH, TYPE_CODE, TYPE_CODE_PTR, TYPE_CODE_REF, type_from_tag(), value_address(), value_as_long(), value_cast(), value_from_contents_and_address(), value_ind(), value_ptradd(), value_tag_from_contents_and_address(), and value_type().
Referenced by ada_coerce_ref(), ada_to_fixed_type_1(), ada_val_print_1(), and ada_value_ind().
struct type* ada_template_to_fixed_record_type_1 (struct type * type, const gdb_byte * valaddr, CORE_ADDR address, struct value * dval0, int keep_dynamic_fields) [read]
Definition at line 7588 of file ada-lang.c.
References _, ada_aligned_type(), ada_check_typedef(), ada_get_base_type(), ada_is_aligner_type(), ada_is_variant_part(), ada_to_fixed_type(), ada_type_name(), ada_typedef_target_type(), align_value(), alloc_type_copy(), check_size(), cond_offset_host(), cond_offset_target(), error(), field_alignment(), INIT_CPLUS_SPECIFIC, is_dynamic_field(), memset(), SET_FIELD_BITPOS, to_fixed_variant_branch_type(), TYPE_ALLOC, TYPE_CODE, TYPE_CODE_STRUCT, TYPE_CODE_TYPEDEF, TYPE_FIELD, TYPE_FIELD_BITPOS, TYPE_FIELD_BITSIZE, TYPE_FIELD_NAME, TYPE_FIELD_TYPE, TYPE_FIELDS, TYPE_FIXED_INSTANCE, TYPE_LENGTH, TYPE_NAME, TYPE_NFIELDS, TYPE_TAG_NAME, TYPE_TARGET_TYPE, value_free_to_mark(), value_from_contents_and_address(), value_mark(), varsize_limit, and warning().
Referenced by get_tcb_types_info(), and template_to_fixed_record_type().
struct type* ada_to_fixed_type (struct type * type, const gdb_byte * valaddr, CORE_ADDR address, struct value * dval, int check_tag) [read]
Definition at line 8278 of file ada-lang.c.
References ada_to_fixed_type_1(), ada_typedef_target_type(), type, TYPE_CODE, TYPE_CODE_TYPEDEF, and TYPE_MAIN_TYPE.
Referenced by ada_template_to_fixed_record_type_1(), ada_to_fixed_value_create(), ada_value_struct_elt(), printable_val_type(), to_fixed_array_type(), and unwrap_value().
static struct type* ada_to_fixed_type_1 (struct type * type, const gdb_byte * valaddr, CORE_ADDR address, struct value * dval, int check_tag) [static, read]
Definition at line 8167 of file ada-lang.c.
References ada_check_typedef(), ada_is_tagged_type(), ada_tag_value_at_base_address(), ada_type_name(), copy_type(), get_int_var_value(), LONGEST, name, size, to_fixed_array_type(), to_fixed_record_type(), to_fixed_variant_branch_type(), to_static_fixed_type(), type, TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_STRUCT, TYPE_CODE_UNION, type_from_tag(), TYPE_LENGTH, TYPE_STUB, value_address(), value_from_contents_and_address(), value_tag_from_contents_and_address(), and xsnprintf().
Referenced by ada_to_fixed_type().
struct value* ada_to_fixed_value (struct value * val) [read]
Definition at line 8445 of file ada-lang.c.
References ada_to_fixed_value_create(), unwrap_value(), value_address(), and value_type().
Referenced by ada_coerce_ref(), ada_get_decoded_value(), ada_value_ind(), ada_value_print(), assign_component(), and common_val_print().
static struct value * ada_to_fixed_value_create (struct type * type0, CORE_ADDR address, struct value * val0) [static, read]
Definition at line 8429 of file ada-lang.c.
References ada_to_fixed_type(), and value_from_contents_and_address().
Referenced by ada_to_fixed_value().
static int ada_type_match (struct type * ftype, struct type * atype, int may_deref) [static]
Definition at line 3284 of file ada-lang.c.
References ada_check_typedef(), ada_is_array_descriptor_type(), TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_ENUM, TYPE_CODE_FLT, TYPE_CODE_INT, TYPE_CODE_PTR, TYPE_CODE_RANGE, TYPE_CODE_REF, TYPE_CODE_STRUCT, TYPE_CODE_UNION, and TYPE_TARGET_TYPE.
Referenced by ada_args_match().
const char* ada_type_name (struct type * type)
Definition at line 7404 of file ada-lang.c.
References TYPE_NAME, and TYPE_TAG_NAME.
Referenced by ada_find_parallel_type(), ada_is_character_type(), ada_is_packed_array_type(), ada_is_tag_type(), ada_print_type(), ada_template_to_fixed_record_type_1(), ada_to_fixed_type_1(), ada_variant_discrim_name(), ada_varobj_describe_simple_array_child(), constrained_packed_array_type(), decode_constrained_packed_array_type(), decode_packed_array_bitsize(), decoded_type_name(), dynamic_template_type(), equiv_types(), find_parallel_type_by_descriptive_type(), fixed_type_info(), is_nondebugging_type(), is_thin_pntr(), print_record_type(), static_unwrap_type(), template_to_static_fixed_type(), thin_descriptor_type(), to_record_with_fixed_variant_part(), and unwrap_value().
struct type* ada_type_of_array (struct value * arr, int bounds) [read]
Definition at line 1835 of file ada-lang.c.
References ada_array_arity(), ada_array_element_type(), ada_check_typedef(), ada_is_array_descriptor_type(), ada_is_constrained_packed_array_type(), ada_is_unconstrained_packed_array_type(), alloc_type_copy(), create_array_type(), create_range_type(), decode_constrained_packed_array_type(), decode_packed_array_bitsize(), desc_bounds(), desc_data_target_type(), desc_one_bound(), LONGEST, longest_to_int(), lookup_pointer_type(), TYPE_FIELD_BITSIZE, TYPE_LENGTH, value_as_long(), and value_type().
Referenced by ada_coerce_to_simple_array_ptr().
static struct type* ada_typedef_target_type (struct type * type) [static, read]
Definition at line 408 of file ada-lang.c.
References type, TYPE_CODE, TYPE_CODE_TYPEDEF, and TYPE_TARGET_TYPE.
Referenced by ada_check_typedef(), ada_template_to_fixed_record_type_1(), ada_to_fixed_type(), decode_packed_array_bitsize(), and desc_base_type().
static CORE_ADDR ada_unhandled_exception_name_addr (void) [static]
Definition at line 11245 of file ada-lang.c.
References parse_and_eval_address().
static CORE_ADDR ada_unhandled_exception_name_addr_from_raise (void) [static]
Definition at line 11256 of file ada-lang.c.
References exception_support_info::catch_exception_sym, current_inferior(), do_cleanups(), ada_inferior_data::exception_info, find_frame_funname(), get_ada_inferior_data(), get_current_frame(), get_prev_frame(), make_cleanup(), null_cleanup(), parse_and_eval_address(), select_frame(), and xfree().
static const char* ada_unqualified_name (const char * decoded_name) [static]
Definition at line 420 of file ada-lang.c.
References strrchr().
Referenced by symbol_completion_match().
enum language ada_update_initial_language (enum language lang)
Definition at line 787 of file ada-lang.c.
References language_ada, and lookup_minimal_symbol().
Referenced by ada_exception_support_info_sniffer().
static struct value* ada_value_assign (struct value * toval, struct value * fromval) [static, read]
Definition at line 2496 of file ada-lang.c.
References _, ada_coerce_ref(), ada_coerce_to_simple_array(), ada_is_direct_array_type(), bits, deprecated_set_value_type(), deprecated_value_modifiable(), error(), gdbarch_bits_big_endian(), get_type_arch(), HOST_CHAR_BIT, len, lval_memory, memcpy(), move_bits(), read_memory(), TYPE_CODE, TYPE_CODE_FLT, TYPE_CODE_STRUCT, TYPE_LENGTH, value_address(), value_assign(), value_bitpos(), value_bitsize(), value_cast(), value_contents(), value_contents_raw(), value_copy(), VALUE_LVAL, value_type(), and write_memory_with_notification().
static struct value* ada_value_binop (struct value * arg1, struct value * arg2, enum exp_opcode op) [static, read]
Definition at line 8956 of file ada-lang.c.
References _, ada_check_typedef(), allocate_value(), coerce_ref(), error(), gdbarch_byte_order(), get_base_type(), get_type_arch(), LONGEST, op_string(), store_unsigned_integer(), TRUNCATION_TOWARDS_ZERO, TYPE_CODE, TYPE_CODE_INT, TYPE_LENGTH, TYPE_UNSIGNED, value_as_long(), value_binop(), value_contents_raw(), and value_type().
static struct value* ada_value_cast (struct type * type, struct value * arg2, enum noside noside) [static, read]
Definition at line 9372 of file ada-lang.c.
References ada_check_typedef(), ada_is_fixed_point_type(), cast_from_fixed(), cast_to_fixed(), value_cast(), and value_type().
static int ada_value_equal (struct value * arg1, struct value * arg2) [static]
Definition at line 9014 of file ada-lang.c.
References _, ada_coerce_ref(), ada_coerce_to_simple_array(), ada_is_direct_array_type(), error(), memcmp(), TYPE_CODE, TYPE_CODE_ARRAY, TYPE_LENGTH, value_contents(), value_equal(), and value_type().
struct value* ada_value_ind (struct value * val0) [read]
Definition at line 7182 of file ada-lang.c.
References ada_is_tagged_type(), ada_tag_value_at_base_address(), ada_to_fixed_value(), value_ind(), and value_type().
Referenced by ada_convert_actual(), ada_val_print_1(), ada_value_struct_elt(), ada_varobj_ind(), and coerce_for_assign().
static struct value * ada_value_primitive_field (struct value * arg1, int offset, int fieldno, struct type * arg_type) [static, read]
Definition at line 6610 of file ada-lang.c.
References ada_check_typedef(), ada_value_primitive_packed_val(), type, TYPE_FIELD_BITPOS, TYPE_FIELD_BITSIZE, TYPE_FIELD_TYPE, value_contents(), and value_primitive_field().
Referenced by ada_index_struct_field_1(), and ada_search_struct_field().
struct value* ada_value_primitive_packed_val (struct value * obj, const gdb_byte * valaddr, long offset, int bit_offset, int bit_size, struct type * type) [read]
Definition at line 2271 of file ada-lang.c.
References ada_check_typedef(), allocate_value(), gdbarch_bits_big_endian(), get_type_arch(), has_negatives(), HOST_CHAR_BIT, L, len, lval_memory, memset(), offset, read_memory(), set_value_bitpos(), set_value_bitsize(), set_value_component_location(), set_value_offset(), set_value_parent(), TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_STRUCT, TYPE_CODE_UNION, TYPE_LENGTH, value_address(), value_at(), value_bitpos(), value_contents(), value_lazy(), and VALUE_LVAL.
Referenced by ada_value_primitive_field(), ada_value_struct_elt(), decode_constrained_packed_array(), print_field_values(), val_print_packed_array_elements(), and value_subscript_packed().
static struct value* ada_value_ptr_subscript (struct value * arr, struct type * type, int arity, struct value ** ind) [static, read]
Definition at line 2617 of file ada-lang.c.
References _, error(), get_discrete_bounds(), LONGEST, lookup_pointer_type(), pos_atr(), TYPE_CODE, TYPE_CODE_ARRAY, TYPE_INDEX_TYPE, TYPE_TARGET_TYPE, value_cast(), value_copy(), value_ind(), and value_ptradd().
static struct value* ada_value_slice (struct value * array, int low, int high) [static, read]
Definition at line 2661 of file ada-lang.c.
References ada_check_typedef(), create_array_type(), create_range_type(), TYPE_INDEX_TYPE, TYPE_TARGET_TYPE, value_cast(), value_slice(), and value_type().
static struct value* ada_value_slice_from_ptr (struct value * array_ptr, struct type * type, int low, int high) [static, read]
Definition at line 2643 of file ada-lang.c.
References ada_check_typedef(), ada_discrete_type_low_bound(), create_array_type(), create_range_type(), TYPE_INDEX_TYPE, TYPE_LENGTH, TYPE_TARGET_TYPE, value_as_address(), and value_at_lazy().
struct value* ada_value_struct_elt (struct value * arg, char * name, int no_err) [read]
Definition at line 6861 of file ada-lang.c.
References _, ada_check_typedef(), ada_coerce_ref(), ada_get_base_type(), ada_search_struct_field(), ada_to_fixed_type(), ada_value_ind(), ada_value_primitive_packed_val(), coerce_ref(), error(), find_struct_field(), TYPE_CODE, TYPE_CODE_PTR, TYPE_CODE_REF, TYPE_CODE_STRUCT, TYPE_CODE_UNION, TYPE_TARGET_TYPE, value_address(), value_at_lazy(), value_ind(), and value_type().
Referenced by ada_get_tsd_from_tag(), ada_tag_name_from_tsd(), ada_value_tag(), ada_which_variant_applies(), is_ada95_tag(), and unwrap_value().
struct value* ada_value_subscript (struct value * arr, int arity, struct value ** ind) [read]
Definition at line 2590 of file ada-lang.c.
References _, ada_check_typedef(), ada_coerce_to_simple_array(), error(), pos_atr(), TYPE_CODE, TYPE_CODE_ARRAY, TYPE_FIELD_BITSIZE, value_subscript(), value_subscript_packed(), and value_type().
Referenced by ada_varobj_simple_array_elt(), and assign_component().
struct value* ada_value_tag (struct value * val) [read]
Definition at line 6131 of file ada-lang.c.
References ada_value_struct_elt().
Referenced by ada_tag_value_at_base_address().
char* ada_variant_discrim_name (struct type * type0)
Definition at line 6465 of file ada-lang.c.
References ada_type_name(), GROW_VECT, name, type, TYPE_CODE, TYPE_CODE_PTR, and TYPE_TARGET_TYPE.
Referenced by ada_variant_discrim_type(), ada_which_variant_applies(), is_unchecked_variant(), and print_variant_part().
struct type* ada_variant_discrim_type (struct type * var_type, struct type * outer_type) [read]
Definition at line 6441 of file ada-lang.c.
References ada_lookup_struct_elt_type(), ada_variant_discrim_name(), and name.
Referenced by print_variant_clauses().
int ada_which_variant_applies (struct type * var_type, struct type * outer_type, const gdb_byte * outer_valaddr)
Definition at line 7112 of file ada-lang.c.
References ada_in_variant(), ada_is_others_clause(), ada_value_struct_elt(), ada_variant_discrim_name(), LONGEST, TYPE_NFIELDS, value_as_long(), and value_from_contents_and_address().
Referenced by print_variant_part(), and to_fixed_variant_branch_type().
static char* add_angle_brackets (const char * str) [static]
Definition at line 436 of file ada-lang.c.
References xfree(), and xstrprintf().
Referenced by symbol_completion_match().
static void add_component_interval (LONGEST low, LONGEST high, LONGEST * indices, int * size, int max_size) [static]
Definition at line 9333 of file ada-lang.c.
References _, error(), memcpy(), and size.
Referenced by aggregate_assign_from_choices(), and aggregate_assign_positional().
static void add_defn_to_vec (struct obstack * obstackp, struct symbol * sym, struct block * block) [static]
Definition at line 4349 of file ada-lang.c.
References ada_symbol_info::block, defns_collected(), lesseq_defined_than(), num_defns_collected(), and ada_symbol_info::sym.
Referenced by ada_add_block_symbols(), ada_lookup_symbol_list_worker(), and aux_add_nonlocal_symbols().
static void add_nonlocal_symbols (struct obstack * obstackp, const char * name, domain_enum domain, int global, int is_wild_match) [static]
Definition at line 5075 of file ada-lang.c.
References ALL_OBJFILES, aux_add_nonlocal_symbols(), compare_names(), full_match(), quick_symbol_functions::map_matching_symbols, memset(), num_defns_collected(), match_data::objfile, match_data::obstackp, sym_fns::qf, objfile::sf, and wild_match().
Referenced by ada_lookup_symbol_list_worker().
static void add_symbols_from_enclosing_procs (struct obstack * obstackp, const char * name, domain_enum namespace, int wild_match_p) [static]
Definition at line 4455 of file ada-lang.c.
Referenced by ada_add_local_symbols().
static int advance_wild_match (const char ** namep, const char * name0, int target0) [static]
Definition at line 5517 of file ada-lang.c.
References name.
Referenced by wild_match().
static void aggregate_assign_from_choices (struct value * container, struct value * lhs, struct expression * exp, int * pos, LONGEST * indices, int * num_indices, int max_indices, LONGEST low, LONGEST high) [static]
Definition at line 9223 of file ada-lang.c.
References _, ada_evaluate_subexp(), ada_is_direct_array_type(), add_component_interval(), assign_component(), expression::elts, error(), EVAL_NORMAL, EVAL_SKIP, find_struct_field(), exp_element::longconst, LONGEST, longest_to_int(), name, exp_element::opcode, exp_element::string, exp_element::symbol, SYMBOL_NATURAL_NAME, value_as_long(), and value_type().
static void aggregate_assign_others (struct value * container, struct value * lhs, struct expression * exp, int * pos, LONGEST * indices, int num_indices, LONGEST low, LONGEST high) [static]
Definition at line 9305 of file ada-lang.c.
References ada_evaluate_subexp(), assign_component(), EVAL_SKIP, and LONGEST.
static void aggregate_assign_positional (struct value * container, struct value * lhs, struct expression * exp, int * pos, LONGEST * indices, int * num_indices, int max_indices, LONGEST low, LONGEST high) [static]
Definition at line 9198 of file ada-lang.c.
References _, ada_evaluate_subexp(), add_component_interval(), assign_component(), expression::elts, EVAL_SKIP, exp_element::longconst, LONGEST, longest_to_int(), and warning().
static unsigned int align_value (unsigned int off, unsigned int alignment) [static]
Definition at line 7217 of file ada-lang.c.
Referenced by ada_template_to_fixed_record_type_1().
static struct bp_location* allocate_location_catch_assert (struct breakpoint * self) [static, read]
Definition at line 11879 of file ada-lang.c.
References ada_catch_assert, and allocate_location_exception().
Referenced by initialize_ada_catchpoint_ops().
static struct bp_location* allocate_location_catch_exception (struct breakpoint * self) [static, read]
Definition at line 11773 of file ada-lang.c.
References ada_catch_exception, and allocate_location_exception().
Referenced by initialize_ada_catchpoint_ops().
static struct bp_location* allocate_location_catch_exception_unhandled (struct breakpoint * self) [static, read]
Definition at line 11825 of file ada-lang.c.
References ada_catch_exception_unhandled, and allocate_location_exception().
Referenced by initialize_ada_catchpoint_ops().
static struct bp_location* allocate_location_exception (enum ada_exception_catchpoint_kind ex, struct breakpoint * self) [static, read]
Definition at line 11491 of file ada-lang.c.
References ada_catchpoint_location::base, ada_catchpoint_location::excep_cond_expr, and init_bp_location().
Referenced by allocate_location_catch_assert(), allocate_location_catch_exception(), and allocate_location_catch_exception_unhandled().
static struct value* assign_aggregate (struct value * container, struct value * lhs, struct expression * exp, int * pos, enum noside noside) [static, read]
Referenced by assign_component().
static void assign_component (struct value * container, struct value * lhs, LONGEST index, struct expression * exp, int * pos) [static]
Definition at line 9075 of file ada-lang.c.
References ada_evaluate_subexp(), ada_index_struct_field(), ada_to_fixed_value(), ada_value_subscript(), assign_aggregate(), builtin_type::builtin_int, builtin_type(), expression::elts, EVAL_NORMAL, expression::gdbarch, exp_element::opcode, TYPE_CODE, TYPE_CODE_ARRAY, unwrap_value(), value_assign_to_component(), value_free_to_mark(), value_from_longest(), value_mark(), and value_type().
Referenced by aggregate_assign_from_choices(), aggregate_assign_others(), and aggregate_assign_positional().
static int aux_add_nonlocal_symbols (struct block * block, struct symbol * sym, void * data0) [static]
Definition at line 4955 of file ada-lang.c.
References add_defn_to_vec(), match_data::arg_sym, fixup_symbol_section(), match_data::found_sym, LOC_UNRESOLVED, match_data::objfile, match_data::obstackp, SYMBOL_CLASS, and SYMBOL_IS_ARGUMENT.
Referenced by add_nonlocal_symbols().
static void cache_symbol (const char * name, domain_enum namespace, struct symbol * sym, const struct block * block) [static]
Definition at line 4233 of file ada-lang.c.
Referenced by ada_lookup_symbol_list_worker(), and standard_lookup().
static struct value* cast_from_fixed (struct type * type, struct value * arg) [static, read]
Definition at line 8836 of file ada-lang.c.
References ada_fixed_to_float(), value_as_long(), value_from_double(), and value_type().
Referenced by ada_value_cast().
static struct value* cast_to_fixed (struct type * type, struct value * arg) [static, read]
Definition at line 8815 of file ada-lang.c.
References ada_fixed_to_float(), ada_float_to_fixed(), ada_is_fixed_point_type(), LONGEST, value_as_double(), value_as_long(), value_from_longest(), and value_type().
Referenced by ada_value_cast().
static void catch_ada_assert_command_split (char * args, char ** cond_string) [static]
Definition at line 12241 of file ada-lang.c.
References _, error(), and skip_spaces().
Referenced by catch_assert_command().
static void catch_ada_exception_command (char * arg, int from_tty, struct cmd_list_element * command) [static]
Definition at line 12211 of file ada-lang.c.
References catch_ada_exception_command_split(), CATCH_TEMPORARY, create_ada_exception_catchpoint(), get_cmd_context(), and get_current_arch().
Referenced by _initialize_ada_language().
static void catch_ada_exception_command_split (char * args, enum ada_exception_catchpoint_kind * ex, char ** excep_string, char ** cond_string) [static]
Definition at line 11965 of file ada-lang.c.
References _, ada_catch_exception, ada_catch_exception_unhandled, ada_get_next_arg(), discard_cleanups(), error(), make_cleanup(), null_cleanup(), skip_spaces(), and xfree().
Referenced by catch_ada_exception_command().
static void catch_assert_command (char * arg, int from_tty, struct cmd_list_element * command) [static]
Definition at line 12265 of file ada-lang.c.
References ada_catch_assert, catch_ada_assert_command_split(), CATCH_TEMPORARY, create_ada_exception_catchpoint(), get_cmd_context(), and get_current_arch().
Referenced by _initialize_ada_language().
static void check_size (const struct type * type) [static]
Definition at line 634 of file ada-lang.c.
References _, error(), TYPE_LENGTH, and varsize_limit.
Referenced by ada_coerce_to_simple_array(), ada_template_to_fixed_record_type_1(), and coerce_unspec_val_to_type().
static void check_status_catch_assert (bpstat bs) [static]
Definition at line 11891 of file ada-lang.c.
References ada_catch_assert, and check_status_exception().
Referenced by initialize_ada_catchpoint_ops().
static void check_status_catch_exception (bpstat bs) [static]
Definition at line 11785 of file ada-lang.c.
References ada_catch_exception, and check_status_exception().
Referenced by initialize_ada_catchpoint_ops().
static void check_status_catch_exception_unhandled (bpstat bs) [static]
Definition at line 11837 of file ada-lang.c.
References ada_catch_exception_unhandled, and check_status_exception().
Referenced by initialize_ada_catchpoint_ops().
static void check_status_exception (enum ada_exception_catchpoint_kind ex, bpstat bs) [static]
Definition at line 11562 of file ada-lang.c.
References bpstats::bp_location_at, should_stop_exception(), and bpstats::stop.
Referenced by check_status_catch_assert(), check_status_catch_exception(), and check_status_catch_exception_unhandled().
static struct value* coerce_for_assign (struct type * type, struct value * val) [static, read]
Definition at line 8914 of file ada-lang.c.
References _, ada_check_typedef(), ada_promote_array_of_integrals(), ada_same_array_size_p(), ada_value_ind(), deprecated_set_value_type(), error(), is_integral_type(), TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_PTR, TYPE_LENGTH, TYPE_TARGET_TYPE, and value_type().
static struct value * coerce_unspec_val_to_type (struct value * val, struct type * type) [static, read]
Definition at line 558 of file ada-lang.c.
References ada_check_typedef(), allocate_value(), allocate_value_lazy(), check_size(), memcpy(), set_value_address(), set_value_bitpos(), set_value_bitsize(), set_value_component_location(), set_value_optimized_out(), TYPE_LENGTH, value_address(), value_bitpos(), value_bitsize(), value_contents(), value_contents_raw(), value_lazy(), value_optimized_out_const(), and value_type().
Referenced by decode_constrained_packed_array(), and unwrap_value().
static int compare_names (const char * string1, const char * string2) [static]
Definition at line 5054 of file ada-lang.c.
References case_sensitive_off, case_sensitive_on, and compare_names_with_case().
Referenced by ada_get_symbol_name_cmp(), and add_nonlocal_symbols().
static int compare_names_with_case (const char * string1, const char * string2, enum case_sensitivity casing) [static]
Definition at line 4989 of file ada-lang.c.
References case_sensitive_off, is_name_suffix(), and strcmp_iw_ordered().
Referenced by compare_names().
static const gdb_byte* cond_offset_host (const gdb_byte * valaddr, long offset) [static]
Definition at line 590 of file ada-lang.c.
References offset.
Referenced by ada_template_to_fixed_record_type_1(), and to_record_with_fixed_variant_part().
static CORE_ADDR cond_offset_target (CORE_ADDR address, long offset) [static]
Definition at line 599 of file ada-lang.c.
References offset.
Referenced by ada_template_to_fixed_record_type_1(), and to_record_with_fixed_variant_part().
static struct type * constrained_packed_array_type (struct type * type, long * elt_bits) [static, read]
Definition at line 2048 of file ada-lang.c.
References ada_check_typedef(), ada_find_parallel_type(), ada_type_name(), alloc_type_copy(), create_array_type(), get_discrete_bounds(), HOST_CHAR_BIT, LONGEST, new_type(), to_fixed_range_type(), type, TYPE_CODE, TYPE_CODE_ARRAY, TYPE_FIELD_BITSIZE, TYPE_FIELD_TYPE, TYPE_FIXED_INSTANCE, TYPE_INDEX_TYPE, TYPE_LENGTH, TYPE_NAME, and TYPE_TARGET_TYPE.
Referenced by decode_constrained_packed_array_type().
void create_ada_exception_catchpoint (struct gdbarch * gdbarch, enum ada_exception_catchpoint_kind ex_kind, char * excep_string, char * cond_string, int tempflag, int disabled, int from_tty)
Definition at line 12184 of file ada-lang.c.
References ada_exception_sal(), ada_catchpoint::base, create_excep_cond_exprs(), ada_catchpoint::excep_string, init_ada_exception_breakpoint(), install_breakpoint(), and set_breakpoint_condition().
Referenced by catch_ada_exception_command(), catch_assert_command(), mi_cmd_catch_assert(), and mi_cmd_catch_exception().
static void create_excep_cond_exprs (struct ada_catchpoint * c) [static]
Definition at line 11424 of file ada-lang.c.
References _, ada_exception_catchpoint_cond_string(), bp_location::address, ada_catchpoint::base, block_for_pc(), do_cleanups(), ada_catchpoint_location::excep_cond_expr, ada_catchpoint::excep_string, breakpoint::loc, make_cleanup(), gdb_exception::message, bp_location::next, breakpoint::number, parse_exp_1(), gdb_exception::reason, RETURN_MASK_ERROR, bp_location::shlib_disabled, TRY_CATCH, warning(), and xfree().
Referenced by create_ada_exception_catchpoint(), and re_set_exception().
static struct value * decode_constrained_packed_array (struct value * arr) [static, read]
Definition at line 2142 of file ada-lang.c.
References _, ada_check_typedef(), ada_coerce_ref(), ada_is_modular_type(), ada_modulus(), ada_value_primitive_packed_val(), coerce_unspec_val_to_type(), decode_constrained_packed_array_type(), error(), gdbarch_bits_big_endian(), get_type_arch(), HOST_CHAR_BIT, type, TYPE_CODE, TYPE_CODE_PTR, TYPE_LENGTH, ULONGEST, value_ind(), and value_type().
Referenced by ada_array_bound(), ada_array_length(), ada_coerce_to_simple_array(), and ada_coerce_to_simple_array_ptr().
static struct type * decode_constrained_packed_array_type (struct type * type) [static, read]
Definition at line 2094 of file ada-lang.c.
References _, ada_check_typedef(), ada_find_parallel_type_with_name(), ada_type_name(), bits, CHECK_TYPEDEF, constrained_packed_array_type(), decode_packed_array_bitsize(), desc_base_type(), lim_warning(), memcpy(), name, strstr(), TYPE_CODE, and TYPE_CODE_ARRAY.
Referenced by ada_array_bound_from_type(), ada_coerce_to_simple_array_type(), ada_type_of_array(), decode_constrained_packed_array(), and to_fixed_array_type().
static long decode_packed_array_bitsize (struct type * type) [static]
Definition at line 2006 of file ada-lang.c.
References _, ada_check_typedef(), ada_type_name(), ada_typedef_target_type(), bits, desc_base_type(), gdb_assert, lim_warning(), strstr(), TYPE_CODE, and TYPE_CODE_TYPEDEF.
Referenced by ada_type_of_array(), and decode_constrained_packed_array_type().
static struct ada_symbol_info * defns_collected (struct obstack * obstackp, int finish) [static, read]
Definition at line 4400 of file ada-lang.c.
Referenced by ada_add_local_symbols(), ada_lookup_symbol_list_worker(), and add_defn_to_vec().
static int desc_arity (struct type * type) [static]
Definition at line 1745 of file ada-lang.c.
References desc_base_type(), and TYPE_NFIELDS.
Referenced by ada_array_arity(), and ada_is_array_descriptor_type().
static struct type * desc_base_type (struct type * type) [static, read]
Definition at line 1443 of file ada-lang.c.
References ada_check_typedef(), ada_typedef_target_type(), type, TYPE_CODE, TYPE_CODE_PTR, TYPE_CODE_REF, TYPE_CODE_TYPEDEF, and TYPE_TARGET_TYPE.
Referenced by ada_array_arity(), ada_array_element_type(), ada_index_type(), ada_is_packed_array_type(), decode_constrained_packed_array_type(), decode_packed_array_bitsize(), desc_arity(), desc_bound_bitpos(), desc_bound_bitsize(), desc_bounds_type(), desc_data_target_type(), desc_index_type(), fat_pntr_bounds_bitpos(), fat_pntr_bounds_bitsize(), fat_pntr_data_bitpos(), fat_pntr_data_bitsize(), is_thick_pntr(), is_thin_pntr(), make_array_descriptor(), and thin_descriptor_type().
static int desc_bound_bitpos (struct type * type, int i, int which) [static]
Definition at line 1707 of file ada-lang.c.
References desc_base_type(), and TYPE_FIELD_BITPOS.
Referenced by make_array_descriptor().
static int desc_bound_bitsize (struct type * type, int i, int which) [static]
Definition at line 1717 of file ada-lang.c.
References desc_base_type(), TYPE_FIELD_BITSIZE, TYPE_FIELD_TYPE, and TYPE_LENGTH.
Referenced by make_array_descriptor().
static struct value * desc_bounds (struct value * arr) [static, read]
Definition at line 1551 of file ada-lang.c.
References _, ada_check_typedef(), desc_bounds_type(), error(), is_thick_pntr(), is_thin_pntr(), LONGEST, lookup_pointer_type(), thin_descriptor_type(), TYPE_CODE, TYPE_CODE_PTR, TYPE_LENGTH, TYPE_STUB, TYPE_TARGET_TYPE, value_address(), value_as_long(), value_cast(), value_from_longest(), value_struct_elt(), and value_type().
Referenced by ada_array_bound(), ada_array_length(), and ada_type_of_array().
static struct type * desc_bounds_type (struct type * type) [static, read]
Definition at line 1521 of file ada-lang.c.
References ada_check_typedef(), desc_base_type(), is_thin_pntr(), lookup_struct_elt_type(), thin_descriptor_type(), TYPE_CODE, TYPE_CODE_STRUCT, and TYPE_TARGET_TYPE.
Referenced by ada_array_arity(), ada_index_type(), ada_is_array_descriptor_type(), desc_bounds(), and make_array_descriptor().
static struct value * desc_data (struct value * arr) [static, read]
Definition at line 1654 of file ada-lang.c.
References _, is_thick_pntr(), is_thin_pntr(), thin_data_pntr(), value_struct_elt(), and value_type().
Referenced by ada_coerce_to_simple_array_ptr(), and ada_convert_actual().
static struct type * desc_data_target_type (struct type * type) [static, read]
Definition at line 1631 of file ada-lang.c.
References ada_check_typedef(), desc_base_type(), is_thick_pntr(), is_thin_pntr(), lookup_struct_elt_type(), thin_descriptor_type(), TYPE_CODE, TYPE_CODE_PTR, TYPE_FIELD_TYPE, and TYPE_TARGET_TYPE.
Referenced by ada_array_element_type(), ada_coerce_to_simple_array_type(), ada_is_array_descriptor_type(), ada_type_of_array(), and thin_data_pntr().
static struct type * desc_index_type (struct type * type, int i) [static, read]
Definition at line 1731 of file ada-lang.c.
References bound_name, desc_base_type(), lookup_struct_elt_type(), TYPE_CODE, and TYPE_CODE_STRUCT.
Referenced by ada_index_type().
static struct value * desc_one_bound (struct value * bounds, int i, int which) [static, read]
Definition at line 1696 of file ada-lang.c.
References _, bound_name, and value_struct_elt().
Referenced by ada_array_bound(), ada_array_length(), and ada_type_of_array().
static int discrete_type_p (struct type * type) [static]
Definition at line 3822 of file ada-lang.c.
References TYPE_CODE, TYPE_CODE_BOOL, TYPE_CODE_ENUM, TYPE_CODE_INT, and TYPE_CODE_RANGE.
Referenced by pos_atr(), and value_val_atr().
static void dtor_catch_assert (struct breakpoint * b) [static]
Definition at line 11873 of file ada-lang.c.
References ada_catch_assert, and dtor_exception().
Referenced by initialize_ada_catchpoint_ops().
static void dtor_catch_exception (struct breakpoint * b) [static]
Definition at line 11767 of file ada-lang.c.
References ada_catch_exception, and dtor_exception().
Referenced by initialize_ada_catchpoint_ops().
static void dtor_catch_exception_unhandled (struct breakpoint * b) [static]
Definition at line 11819 of file ada-lang.c.
References ada_catch_exception_unhandled, and dtor_exception().
Referenced by initialize_ada_catchpoint_ops().
static void dtor_exception (enum ada_exception_catchpoint_kind ex, struct breakpoint * b) [static]
Definition at line 11478 of file ada-lang.c.
References bkpt_breakpoint_ops, breakpoint_ops::dtor, ada_catchpoint::excep_string, and xfree().
Referenced by dtor_catch_assert(), dtor_catch_exception(), and dtor_catch_exception_unhandled().
static struct type* dynamic_template_type (struct type * type) [static, read]
Definition at line 7503 of file ada-lang.c.
References ada_check_typedef(), ada_find_parallel_type(), ada_type_name(), len, type, TYPE_CODE, and TYPE_CODE_STRUCT.
Referenced by to_fixed_record_type(), and to_static_fixed_type().
static void emit_char (int c, struct type * type, struct ui_file * stream, int quoter) [static]
Definition at line 12744 of file ada-lang.c.
References ada_emit_char().
static struct value* empty_array (struct type * arr_type, int low) [static, read]
Definition at line 2870 of file ada-lang.c.
References ada_array_element_type(), ada_check_typedef(), allocate_value(), create_array_type(), create_range_type(), TYPE_INDEX_TYPE, and TYPE_TARGET_TYPE.
static struct type* empty_record (struct type * template) [static, read]
Definition at line 7556 of file ada-lang.c.
References alloc_type_copy(), INIT_CPLUS_SPECIFIC, type, TYPE_CODE, TYPE_CODE_STRUCT, TYPE_FIELDS, TYPE_LENGTH, TYPE_NAME, TYPE_NFIELDS, and TYPE_TAG_NAME.
Referenced by to_fixed_variant_branch_type().
static int encoded_ordered_before (const char * N0, const char * N1) [static]
Definition at line 3462 of file ada-lang.c.
Referenced by sort_choices().
static struct value* ensure_lval (struct value * val) [static, read]
Definition at line 4080 of file ada-lang.c.
References ada_check_typedef(), len, lval_internalvar, lval_memory, not_lval, set_value_address(), TYPE_LENGTH, value_allocate_space_in_inferior(), value_as_long(), value_contents(), VALUE_LVAL, value_type(), and write_memory().
Referenced by ada_convert_actual(), and make_array_descriptor().
static int equiv_types (struct type * type0, struct type * type1) [static]
Definition at line 4291 of file ada-lang.c.
References ada_type_name(), TYPE_CODE, TYPE_CODE_ENUM, and TYPE_CODE_STRUCT.
Referenced by lesseq_defined_than().
static struct value * evaluate_subexp_type (struct expression * exp, int * pos) [static, read]
Definition at line 8772 of file ada-lang.c.
References EVAL_AVOID_SIDE_EFFECTS, evaluate_subexp(), and NULL_TYPE.
Referenced by resolve_subexp().
static int fat_pntr_bounds_bitpos (struct type * type) [static]
Definition at line 1606 of file ada-lang.c.
References desc_base_type(), and TYPE_FIELD_BITPOS.
Referenced by make_array_descriptor().
static int fat_pntr_bounds_bitsize (struct type * type) [static]
Definition at line 1615 of file ada-lang.c.
References ada_check_typedef(), desc_base_type(), TYPE_FIELD_BITSIZE, TYPE_FIELD_TYPE, and TYPE_LENGTH.
Referenced by make_array_descriptor().
static int fat_pntr_data_bitpos (struct type * type) [static]
Definition at line 1672 of file ada-lang.c.
References desc_base_type(), and TYPE_FIELD_BITPOS.
Referenced by make_array_descriptor().
static int fat_pntr_data_bitsize (struct type * type) [static]
Definition at line 1681 of file ada-lang.c.
References desc_base_type(), TYPE_FIELD_BITSIZE, TYPE_FIELD_TYPE, and TYPE_LENGTH.
Referenced by make_array_descriptor().
static unsigned int field_alignment (struct type * type, int f) [static]
Definition at line 7225 of file ada-lang.c.
References len, name, and TYPE_FIELD_NAME.
Referenced by ada_template_to_fixed_record_type_1(), and alignment_of().
static int field_name_match (const char * field_name, const char * target) [static]
Definition at line 482 of file ada-lang.c.
References len.
Referenced by ada_get_field_index(), ada_lookup_struct_elt_type(), ada_search_struct_field(), and find_struct_field().
static struct symbol * find_old_style_renaming_symbol (const char * name, const struct block * block) [static, read]
Definition at line 7312 of file ada-lang.c.
References ada_find_any_type_symbol(), ada_name_prefix_len(), ada_remove_po_subprogram_suffix(), ada_remove_trailing_digits(), ada_remove_Xbn_suffix(), block_linkage_function(), strstr(), SYMBOL_LINKAGE_NAME, and xsnprintf().
Referenced by ada_find_renaming_symbol().
static struct type* find_parallel_type_by_descriptive_type (struct type * type, const char * name) [static, read]
Definition at line 7418 of file ada-lang.c.
References _, ada_find_any_type(), ada_is_constrained_packed_array_type(), ada_type_name(), HAVE_GNAT_AUX_INFO, TYPE_DESCRIPTIVE_TYPE, and warning().
Referenced by ada_find_parallel_type_with_name().
static int find_struct_field (const char * name, struct type * type, int offset, struct type ** field_type_p, int * byte_offset_p, int * bit_offset_p, int * bit_size_p, int * index_p) [static]
Definition at line 6649 of file ada-lang.c.
References ada_check_typedef(), ada_is_variant_part(), ada_is_wrapper_field(), field_name_match(), TYPE_FIELD_BITPOS, TYPE_FIELD_BITSIZE, TYPE_FIELD_NAME, TYPE_FIELD_TYPE, and TYPE_NFIELDS.
Referenced by ada_value_struct_elt(), aggregate_assign_from_choices(), num_visible_fields(), and value_tag_from_contents_and_address().
static const char* fixed_type_info (struct type * type) [static]
Definition at line 10623 of file ada-lang.c.
References ada_type_name(), code, strstr(), TYPE_CODE, TYPE_CODE_INT, TYPE_CODE_RANGE, TYPE_CODE_UNDEF, and TYPE_TARGET_TYPE.
Referenced by ada_delta(), ada_is_fixed_point_type(), and scaling_factor().
static int full_match (const char * sym_name, const char * search_name) [static]
Definition at line 5590 of file ada-lang.c.
References match_name().
Referenced by ada_add_block_symbols(), and add_nonlocal_symbols().
static struct ada_inferior_data* get_ada_inferior_data (struct inferior * inf) [static, read]
Definition at line 354 of file ada-lang.c.
References XZALLOC.
Referenced by ada_exception_name_addr_1(), ada_exception_support_info_sniffer(), ada_exception_sym_name(), ada_get_tsd_type(), and ada_unhandled_exception_name_addr_from_raise().
static struct type* get_base_type (struct type * type) [static, read]
Definition at line 729 of file ada-lang.c.
References type, TYPE_CODE, TYPE_CODE_RANGE, and TYPE_TARGET_TYPE.
Referenced by ada_is_modular_type(), ada_value_binop(), and return_match().
LONGEST get_int_var_value (char * name, int * flag)
Definition at line 10802 of file ada-lang.c.
References get_var_value(), and value_as_long().
Referenced by ada_to_fixed_type_1(), print_dynamic_range_bound(), and to_fixed_range_type().
int get_selections (int * choices, int n_choices, int max_results, int is_all_choice, char * annotation_suffix)
Definition at line 3644 of file ada-lang.c.
References _, command_line_input(), error(), error_no_arg(), and skip_spaces().
Referenced by user_select_syms().
static struct value * get_var_value (char * name, char * err_msg) [static, read]
Definition at line 10778 of file ada-lang.c.
References ada_lookup_symbol_list(), error(), get_selected_block(), ada_symbol_info::sym, value_of_variable(), and VAR_DOMAIN.
Referenced by get_int_var_value().
void* grow_vect (void * vect, size_t * size, size_t min_size, int element_size)
Definition at line 466 of file ada-lang.c.
References xrealloc().
static int has_negatives (struct type * type) [static]
Definition at line 2247 of file ada-lang.c.
References TYPE_CODE, TYPE_CODE_INT, TYPE_CODE_RANGE, TYPE_LOW_BOUND, and TYPE_UNSIGNED.
Referenced by ada_value_primitive_packed_val().
static void initialize_ada_catchpoint_ops (void) [static]
Definition at line 12866 of file ada-lang.c.
References breakpoint_ops::allocate_location, allocate_location_catch_assert(), allocate_location_catch_exception(), allocate_location_catch_exception_unhandled(), bkpt_breakpoint_ops, catch_assert_breakpoint_ops, catch_exception_breakpoint_ops, catch_exception_unhandled_breakpoint_ops, breakpoint_ops::check_status, check_status_catch_assert(), check_status_catch_exception(), check_status_catch_exception_unhandled(), breakpoint_ops::dtor, dtor_catch_assert(), dtor_catch_exception(), dtor_catch_exception_unhandled(), initialize_breakpoint_ops(), breakpoint_ops::print_it, print_it_catch_assert(), print_it_catch_exception(), print_it_catch_exception_unhandled(), breakpoint_ops::print_mention, print_mention_catch_assert(), print_mention_catch_exception(), print_mention_catch_exception_unhandled(), breakpoint_ops::print_one, print_one_catch_assert(), print_one_catch_exception(), print_one_catch_exception_unhandled(), breakpoint_ops::print_recreate, print_recreate_catch_assert(), print_recreate_catch_exception(), print_recreate_catch_exception_unhandled(), breakpoint_ops::re_set, re_set_catch_assert(), re_set_catch_exception(), and re_set_catch_exception_unhandled().
Referenced by _initialize_ada_language().
static int integer_type_p (struct type * type) [static]
Definition at line 3778 of file ada-lang.c.
References TYPE_CODE, TYPE_CODE_INT, TYPE_CODE_RANGE, and TYPE_TARGET_TYPE.
Referenced by possible_user_operator_p(), and value_val_atr().
static int is_ada95_tag (struct value * tag) [static]
Definition at line 6123 of file ada-lang.c.
References ada_value_struct_elt().
Referenced by ada_tag_value_at_base_address().
static int is_dynamic_field (struct type * templ_type, int field_num) [static]
Definition at line 7525 of file ada-lang.c.
References name, strstr(), TYPE_CODE, TYPE_CODE_PTR, TYPE_FIELD_NAME, and TYPE_FIELD_TYPE.
Referenced by ada_is_variant_part(), ada_template_to_fixed_record_type_1(), template_to_static_fixed_type(), and to_fixed_variant_branch_type().
static int is_known_support_routine (struct frame_info * frame) [static]
Definition at line 11161 of file ada-lang.c.
References symtab::filename, find_frame_funname(), find_frame_sal(), known_auxiliary_function_name_patterns, known_runtime_file_name_patterns, symtab::objfile, objfile_name(), re_comp(), symtab_and_line::symtab, symtab_to_fullname(), and xfree().
Referenced by ada_find_printable_frame().
static int is_lower_alphanum (const char c) [static]
Definition at line 948 of file ada-lang.c.
Referenced by ada_decode().
static int is_name_suffix (const char * str) [static]
Definition at line 5360 of file ada-lang.c.
References len.
Referenced by ada_add_block_symbols(), compare_names_with_case(), match_name(), and wild_match().
static int is_nondebugging_type (struct type * type) [static]
Definition at line 4465 of file ada-lang.c.
References ada_type_name(), and name.
Referenced by remove_extra_symbols().
static int is_nonfunction (struct ada_symbol_info * , int) [static]
Referenced by ada_add_local_symbols(), and resolve_subexp().
static int is_nonfunction (struct ada_symbol_info syms[], int n) [static]
Definition at line 4274 of file ada-lang.c.
References LOC_CONST, SYMBOL_CLASS, SYMBOL_TYPE, TYPE_CODE, TYPE_CODE_ENUM, and TYPE_CODE_FUNC.
static int is_package_name (const char * name) [static]
Definition at line 4702 of file ada-lang.c.
References standard_lookup(), strstr(), VAR_DOMAIN, and xstrprintf().
Referenced by old_renaming_is_invisible().
static int is_suffix (const char * str, const char * suffix) [static]
Definition at line 543 of file ada-lang.c.
Referenced by is_thin_pntr(), and thin_descriptor_type().
static int is_thick_pntr (struct type * type) [static]
Definition at line 1510 of file ada-lang.c.
References desc_base_type(), lookup_struct_elt_type(), TYPE_CODE, and TYPE_CODE_STRUCT.
Referenced by ada_check_typedef(), desc_bounds(), desc_data(), and desc_data_target_type().
static int is_thin_pntr (struct type * type) [static]
Definition at line 1462 of file ada-lang.c.
References ada_type_name(), desc_base_type(), and is_suffix().
Referenced by desc_bounds(), desc_bounds_type(), desc_data(), and desc_data_target_type().
static int is_unchecked_variant (struct type * var_type, struct type * outer_type) [static]
Definition at line 7097 of file ada-lang.c.
References ada_lookup_struct_elt_type(), and ada_variant_discrim_name().
Referenced by to_fixed_variant_branch_type().
static int is_valid_name_for_wild_match (const char * name0) [static]
Definition at line 5494 of file ada-lang.c.
References ada_decode().
Referenced by wild_match().
static int lesseq_defined_than (struct symbol * sym0, struct symbol * sym1) [static]
Definition at line 4311 of file ada-lang.c.
References equiv_types(), LOC_CONST, LOC_TYPEDEF, LOC_UNDEF, SYMBOL_CLASS, SYMBOL_DOMAIN, SYMBOL_LINKAGE_NAME, SYMBOL_TYPE, SYMBOL_VALUE, and TYPE_CODE.
Referenced by add_defn_to_vec().
static void static void lim_warning (const char * format, ...) [static]
Definition at line 617 of file ada-lang.c.
References vwarning(), warning_limit, and warnings_issued.
Referenced by decode_constrained_packed_array_type(), decode_packed_array_bitsize(), to_fixed_range_type(), and value_subscript_packed().
static int lookup_cached_symbol (const char * name, domain_enum namespace, struct symbol ** sym, struct block ** block) [static]
Definition at line 4226 of file ada-lang.c.
Referenced by ada_lookup_symbol_list_worker(), and standard_lookup().
static struct value * make_array_descriptor (struct type * type, struct value * arr) [static, read]
Definition at line 4177 of file ada-lang.c.
References ada_array_arity(), ada_array_bound(), ada_check_typedef(), allocate_value(), desc_base_type(), desc_bound_bitpos(), desc_bound_bitsize(), desc_bounds_type(), ensure_lval(), fat_pntr_bounds_bitpos(), fat_pntr_bounds_bitsize(), fat_pntr_data_bitpos(), fat_pntr_data_bitsize(), modify_field(), TYPE_CODE, TYPE_CODE_PTR, TYPE_FIELD_TYPE, value_addr(), value_contents_writeable(), value_pointer(), and value_type().
Referenced by ada_convert_actual().
static int match_name (const char * sym_name, const char * name, int wild) [static]
Definition at line 1348 of file ada-lang.c.
References is_name_suffix(), and wild_match().
Referenced by ada_lookup_simple_minsym(), and full_match().
static LONGEST max_of_size (int size) [static]
Definition at line 642 of file ada-lang.c.
References LONGEST.
Referenced by max_of_type(), and min_of_size().
static LONGEST max_of_type (struct type * t) [static]
Definition at line 667 of file ada-lang.c.
References LONGEST, max_of_size(), TYPE_LENGTH, TYPE_UNSIGNED, and umax_of_size().
Referenced by ada_discrete_type_high_bound().
static LONGEST min_of_size (int size) [static]
Definition at line 651 of file ada-lang.c.
References max_of_size().
Referenced by min_of_type().
static LONGEST min_of_type (struct type * t) [static]
Definition at line 677 of file ada-lang.c.
References min_of_size(), TYPE_LENGTH, and TYPE_UNSIGNED.
Referenced by ada_discrete_type_low_bound().
static void move_bits (gdb_byte * target, int targ_offset, const gdb_byte * source, int src_offset, int n, int bits_big_endian_p) [static]
Definition at line 2428 of file ada-lang.c.
References HOST_CHAR_BIT.
Referenced by ada_value_assign(), and value_assign_to_component().
static int num_component_specs (struct expression * exp, int pc) [static]
Definition at line 9045 of file ada-lang.c.
References ada_evaluate_subexp(), expression::elts, EVAL_SKIP, exp_element::longconst, arm-linux::m, and exp_element::opcode.
static int num_defns_collected (struct obstack * obstackp) [static]
Definition at line 4390 of file ada-lang.c.
Referenced by ada_add_local_symbols(), ada_lookup_symbol_list_worker(), add_defn_to_vec(), and add_nonlocal_symbols().
static int num_visible_fields (struct type * type) [static]
Definition at line 6724 of file ada-lang.c.
References find_struct_field().
static int numeric_type_p (struct type * type) [static]
Definition at line 3755 of file ada-lang.c.
References TYPE_CODE, TYPE_CODE_FLT, TYPE_CODE_INT, TYPE_CODE_RANGE, and TYPE_TARGET_TYPE.
Referenced by possible_user_operator_p().
static int old_renaming_is_invisible (const struct symbol * sym, const char * function_name) [static]
Definition at line 4734 of file ada-lang.c.
References do_cleanups(), is_package_name(), LOC_TYPEDEF, make_cleanup(), SYMBOL_CLASS, SYMBOL_TYPE, xfree(), and xget_renaming_scope().
Referenced by remove_irrelevant_renamings().
static int parse (void) [static]
Definition at line 12750 of file ada-lang.c.
References ada_parse(), and warnings_issued.
Referenced by mi_cmd_execute(), and mi_parse().
static enum ada_renaming_category parse_old_style_renaming (struct type * type, const char ** renamed_entity, int * len, const char ** renaming_expr) [static]
Definition at line 3996 of file ada-lang.c.
References ADA_EXCEPTION_RENAMING, ADA_NOT_RENAMING, ADA_OBJECT_RENAMING, ADA_PACKAGE_RENAMING, ADA_SUBPROGRAM_RENAMING, name, strstr(), TYPE_CODE, TYPE_CODE_ENUM, TYPE_FIELD_NAME, type_name_no_tag(), and TYPE_NFIELDS.
Referenced by ada_parse_renaming().
static LONGEST pos_atr (struct value * arg) [static]
Definition at line 8489 of file ada-lang.c.
References _, coerce_ref(), discrete_type_p(), error(), LONGEST, TYPE_CODE, TYPE_CODE_ENUM, TYPE_FIELD_ENUMVAL, TYPE_NFIELDS, value_as_long(), and value_type().
Referenced by ada_value_ptr_subscript(), ada_value_subscript(), value_pos_atr(), and value_subscript_packed().
static int possible_user_operator_p (enum exp_opcode, struct value **) [static]
Referenced by resolve_subexp().
static int possible_user_operator_p (enum exp_opcode op, struct value * args[]) [static]
Definition at line 3846 of file ada-lang.c.
References ada_check_typedef(), ada_is_array_type(), integer_type_p(), numeric_type_p(), scalar_type_p(), and value_type().
static enum print_stop_action print_it_catch_assert (bpstat bs) [static]
Definition at line 11897 of file ada-lang.c.
References ada_catch_assert, and print_it_exception().
Referenced by initialize_ada_catchpoint_ops().
static enum print_stop_action print_it_catch_exception (bpstat bs) [static]
Definition at line 11791 of file ada-lang.c.
References ada_catch_exception, and print_it_exception().
Referenced by initialize_ada_catchpoint_ops().
static enum print_stop_action print_it_catch_exception_unhandled (bpstat bs) [static]
Definition at line 11843 of file ada-lang.c.
References ada_catch_exception_unhandled, and print_it_exception().
Referenced by initialize_ada_catchpoint_ops().
static enum print_stop_action print_it_exception (enum ada_exception_catchpoint_kind ex, bpstat bs) [static]
Definition at line 11571 of file ada-lang.c.
References ada_catch_assert, ada_catch_exception, ada_catch_exception_unhandled, ada_exception_name_addr(), ada_find_printable_frame(), annotate_catchpoint(), async_reason_lookup(), bpdisp_text(), bpstats::breakpoint_at, current_uiout, disp_del, breakpoint::disposition, EXEC_ASYNC_BREAKPOINT_HIT, get_current_frame(), memcpy(), breakpoint::number, PRINT_SRC_AND_LOC, read_memory(), ui_out_field_int(), ui_out_field_string(), ui_out_is_mi_like_p(), and ui_out_text().
Referenced by print_it_catch_assert(), print_it_catch_exception(), and print_it_catch_exception_unhandled().
static void print_mention_catch_assert (struct breakpoint * b) [static]
Definition at line 11909 of file ada-lang.c.
References ada_catch_assert, and print_mention_exception().
Referenced by initialize_ada_catchpoint_ops().
static void print_mention_catch_exception (struct breakpoint * b) [static]
Definition at line 11803 of file ada-lang.c.
References ada_catch_exception, and print_mention_exception().
Referenced by initialize_ada_catchpoint_ops().
static void print_mention_catch_exception_unhandled (struct breakpoint * b) [static]
Definition at line 11856 of file ada-lang.c.
References ada_catch_exception_unhandled, and print_mention_exception().
Referenced by initialize_ada_catchpoint_ops().
static void print_mention_exception (enum ada_exception_catchpoint_kind ex, struct breakpoint * b) [static]
Definition at line 11693 of file ada-lang.c.
References _, ada_catch_assert, ada_catch_exception, ada_catch_exception_unhandled, current_uiout, disp_del, breakpoint::disposition, do_cleanups(), ada_catchpoint::excep_string, internal_error(), make_cleanup(), breakpoint::number, ui_out_field_int(), ui_out_text(), xfree(), and xstrprintf().
Referenced by print_mention_catch_assert(), print_mention_catch_exception(), and print_mention_catch_exception_unhandled().
static void print_one_catch_assert (struct breakpoint * b, struct bp_location ** last_loc) [static]
Definition at line 11903 of file ada-lang.c.
References ada_catch_assert, and print_one_exception().
Referenced by initialize_ada_catchpoint_ops().
static void print_one_catch_exception (struct breakpoint * b, struct bp_location ** last_loc) [static]
Definition at line 11797 of file ada-lang.c.
References ada_catch_exception, and print_one_exception().
Referenced by initialize_ada_catchpoint_ops().
static void print_one_catch_exception_unhandled (struct breakpoint * b, struct bp_location ** last_loc) [static]
Definition at line 11849 of file ada-lang.c.
References ada_catch_exception_unhandled, and print_one_exception().
Referenced by initialize_ada_catchpoint_ops().
static void print_one_exception (enum ada_exception_catchpoint_kind ex, struct breakpoint * b, struct bp_location ** last_loc) [static]
Definition at line 11644 of file ada-lang.c.
References _, ada_catch_assert, ada_catch_exception, ada_catch_exception_unhandled, bp_location::address, value_print_options::addressprint, annotate_field(), current_uiout, ada_catchpoint::excep_string, bp_location::gdbarch, get_user_print_options(), internal_error(), breakpoint::loc, ui_out_field_core_addr(), ui_out_field_string(), xfree(), and xstrprintf().
Referenced by print_one_catch_assert(), print_one_catch_exception(), and print_one_catch_exception_unhandled().
static void print_recreate_catch_assert (struct breakpoint * b, struct ui_file * fp) [static]
Definition at line 11915 of file ada-lang.c.
References ada_catch_assert, and print_recreate_exception().
Referenced by initialize_ada_catchpoint_ops().
static void print_recreate_catch_exception (struct breakpoint * b, struct ui_file * fp) [static]
Definition at line 11809 of file ada-lang.c.
References ada_catch_exception, and print_recreate_exception().
Referenced by initialize_ada_catchpoint_ops().
static void print_recreate_catch_exception_unhandled (struct breakpoint * b, struct ui_file * fp) [static]
Definition at line 11862 of file ada-lang.c.
References ada_catch_exception_unhandled, and print_recreate_exception().
Referenced by initialize_ada_catchpoint_ops().
static void print_recreate_exception (enum ada_exception_catchpoint_kind ex, struct breakpoint * b, struct ui_file * fp) [static]
Definition at line 11737 of file ada-lang.c.
References _, ada_catch_assert, ada_catch_exception, ada_catch_exception_unhandled, ada_catchpoint::excep_string, fprintf_filtered(), internal_error(), and print_recreate_thread().
Referenced by print_recreate_catch_assert(), print_recreate_catch_exception(), and print_recreate_catch_exception_unhandled().
static void re_set_catch_assert (struct breakpoint * b) [static]
Definition at line 11885 of file ada-lang.c.
References ada_catch_assert, and re_set_exception().
Referenced by initialize_ada_catchpoint_ops().
static void re_set_catch_exception (struct breakpoint * b) [static]
Definition at line 11779 of file ada-lang.c.
References ada_catch_exception, and re_set_exception().
Referenced by initialize_ada_catchpoint_ops().
static void re_set_catch_exception_unhandled (struct breakpoint * b) [static]
Definition at line 11831 of file ada-lang.c.
References ada_catch_exception_unhandled, and re_set_exception().
Referenced by initialize_ada_catchpoint_ops().
static void re_set_exception (enum ada_exception_catchpoint_kind ex, struct breakpoint * b) [static]
Definition at line 11506 of file ada-lang.c.
References bkpt_breakpoint_ops, create_excep_cond_exprs(), and breakpoint_ops::re_set.
Referenced by re_set_catch_assert(), re_set_catch_exception(), and re_set_catch_exception_unhandled().
static int remove_extra_symbols (struct ada_symbol_info * syms, int nsyms) [static]
Definition at line 4582 of file ada-lang.c.
References is_nondebugging_type(), LOC_STATIC, SYMBOL_CLASS, SYMBOL_LINKAGE_NAME, SYMBOL_TYPE, SYMBOL_VALUE_ADDRESS, symbols_are_identical_enums(), and TYPE_STUB.
Referenced by ada_lookup_symbol_list_worker().
static int remove_irrelevant_renamings (struct ada_symbol_info * syms, int nsyms, const struct block * current_block) [static]
Definition at line 4808 of file ada-lang.c.
References ADA_OBJECT_RENAMING, ada_parse_renaming(), ada_symbol_info::block, block_linkage_function(), LOC_TYPEDEF, name, old_renaming_is_invisible(), strstr(), ada_symbol_info::sym, SYMBOL_CLASS, and SYMBOL_LINKAGE_NAME.
Referenced by ada_lookup_symbol_list_worker().
static void replace_operator_with_call (struct expression ** expp, int pc, int nargs, int oplen, struct symbol * sym, const struct block * block) [static]
Definition at line 3720 of file ada-lang.c.
References exp_element::block, expression::elts, EXP_ELEM_TO_BYTES, expression::gdbarch, expression::language_defn, exp_element::longconst, LONGEST, memcpy(), expression::nelts, exp_element::opcode, exp_element::symbol, xfree(), and xzalloc().
Referenced by resolve_subexp().
static void resolve (struct expression ** expp, int void_context_p) [static]
Definition at line 2911 of file ada-lang.c.
References builtin_type(), builtin_type::builtin_void, and resolve_subexp().
static struct value * resolve_subexp (struct expression ** expp, int * pos, int deprocedure_p, struct type * context_type) [static, read]
Definition at line 2932 of file ada-lang.c.
References _, ada_decoded_op_name(), ada_encode(), ada_forward_operator_length(), ada_lookup_symbol_list(), ada_resolve_function(), exp_element::block, ada_symbol_info::block, BYTES_TO_EXP_ELEM, check_typedef(), contained_in(), expression::elts, error(), evaluate_subexp_type(), innermost_block, is_nonfunction(), LOC_ARG, LOC_COMPUTED, LOC_LOCAL, LOC_REF_ARG, LOC_REGISTER, LOC_REGPARM_ADDR, LOC_TYPEDEF, exp_element::longconst, longest_to_int(), exp_element::opcode, possible_user_operator_p(), printf_filtered(), replace_operator_with_call(), ada_symbol_info::sym, exp_element::symbol, SYMBOL_CLASS, SYMBOL_DOMAIN, SYMBOL_LINKAGE_NAME, SYMBOL_PRINT_NAME, SYMBOL_TYPE, exp_element::type, TYPE_CODE, TYPE_CODE_FUNC, UNDEF_DOMAIN, user_select_syms(), value_type(), and VAR_DOMAIN.
Referenced by resolve().
static int return_match (struct type * func_type, struct type * context_type) [static]
Definition at line 3379 of file ada-lang.c.
References get_base_type(), TYPE_CODE, TYPE_CODE_ENUM, TYPE_CODE_FUNC, TYPE_CODE_VOID, and TYPE_TARGET_TYPE.
Referenced by ada_resolve_function().
static int scalar_type_p (struct type * type) [static]
Definition at line 3800 of file ada-lang.c.
References TYPE_CODE, TYPE_CODE_ENUM, TYPE_CODE_FLT, TYPE_CODE_INT, and TYPE_CODE_RANGE.
Referenced by possible_user_operator_p().
static DOUBLEST scaling_factor (struct type * type) [static]
Definition at line 10684 of file ada-lang.c.
References DOUBLEST_SCAN_FORMAT, encoding, and fixed_type_info().
Referenced by ada_fixed_to_float(), and ada_float_to_fixed().
static int scan_discrim_bound (char * str, int k, struct value * dval, LONGEST * px, int * pnew_k) [static]
Definition at line 10736 of file ada-lang.c.
References ada_search_struct_field(), GROW_VECT, strstr(), value_as_long(), and value_type().
Referenced by to_fixed_range_type().
static void set_ada_command (char * arg, int from_tty) [static]
Definition at line 12850 of file ada-lang.c.
References _, gdb_stdout, help_list(), and printf_unfiltered().
Referenced by _initialize_ada_language().
static int should_stop_exception (const struct bp_location * bl) [static]
Definition at line 11524 of file ada-lang.c.
References _, evaluate_expression(), ada_catchpoint::excep_string, exception_fprintf(), gdb_stderr, bp_location::owner, gdb_exception::reason, RETURN_MASK_ALL, TRY_CATCH, value_free_to_mark(), value_mark(), and value_true().
Referenced by check_status_exception().
static int should_use_wild_match (const char * lookup_name) [static]
Definition at line 4247 of file ada-lang.c.
References strstr().
Referenced by ada_get_symbol_name_cmp(), ada_lookup_simple_minsym(), and ada_lookup_symbol_list_worker().
static void show_ada_command (char * args, int from_tty) [static]
Definition at line 12860 of file ada-lang.c.
References cmd_show_list().
Referenced by _initialize_ada_language().
static void sort_choices (struct ada_symbol_info syms[], int nsyms) [static]
Definition at line 3498 of file ada-lang.c.
References encoded_ordered_before(), ada_symbol_info::sym, and SYMBOL_LINKAGE_NAME.
Referenced by user_select_syms().
static struct symbol * standard_lookup (const char * name, const struct block * block, domain_enum domain) [static, read]
Definition at line 4256 of file ada-lang.c.
References block_found, cache_symbol(), language_c, lookup_cached_symbol(), and lookup_symbol_in_language().
Referenced by ada_exception_sal(), ada_find_any_type_symbol(), ada_has_this_exception_support(), and is_package_name().
static struct type * static_unwrap_type (struct type * type) [static, read]
Definition at line 8348 of file ada-lang.c.
References ada_check_typedef(), ada_get_base_type(), ada_is_aligner_type(), ada_type_name(), to_static_fixed_type(), type, TYPE_FIELD_TYPE, and TYPE_NAME.
Referenced by template_to_static_fixed_type().
static void symbol_completion_add (VEC(char_ptr)** sv, const char * sym_name, const char * text, int text_len, const char * orig_text, const char * word, int wild_match_p, int encoded_p) [static]
Definition at line 5826 of file ada-lang.c.
References symbol_completion_match(), VEC_safe_push, word, and xmalloc().
Referenced by VEC().
static const char* symbol_completion_match (const char * sym_name, const char * text, int text_len, int wild_match_p, int encoded_p) [static]
Definition at line 5735 of file ada-lang.c.
References ada_decode(), ada_unqualified_name(), and add_angle_brackets().
Referenced by ada_expand_partial_symbol_name(), and symbol_completion_add().
static int symbols_are_identical_enums (struct ada_symbol_info * syms, int nsyms) [static]
Definition at line 4536 of file ada-lang.c.
References ada_identical_enum_types_p(), SYMBOL_TYPE, SYMBOL_VALUE, TYPE_CODE, TYPE_CODE_ENUM, and TYPE_NFIELDS.
Referenced by remove_extra_symbols().
static struct type* template_to_fixed_record_type (struct type * type, const gdb_byte * valaddr, CORE_ADDR address, struct value * dval0) [static, read]
Definition at line 7821 of file ada-lang.c.
References ada_template_to_fixed_record_type_1().
Referenced by to_fixed_record_type().
static struct type* template_to_static_fixed_type (struct type * type0) [static, read]
Definition at line 7838 of file ada-lang.c.
References ada_check_typedef(), ada_type_name(), alloc_type_copy(), INIT_CPLUS_SPECIFIC, is_dynamic_field(), memcpy(), new_type(), static_unwrap_type(), to_static_fixed_type(), type, TYPE_ALLOC, TYPE_CODE, TYPE_FIELD_NAME, TYPE_FIELD_TYPE, TYPE_FIELDS, TYPE_FIXED_INSTANCE, TYPE_LENGTH, TYPE_NAME, TYPE_NFIELDS, TYPE_TAG_NAME, and TYPE_TARGET_TYPE.
Referenced by to_static_fixed_type().
static struct value* thin_data_pntr (struct value * val) [static, read]
Definition at line 1494 of file ada-lang.c.
References ada_check_typedef(), desc_data_target_type(), lookup_pointer_type(), thin_descriptor_type(), TYPE_CODE, TYPE_CODE_PTR, value_address(), value_cast(), value_copy(), value_from_longest(), and value_type().
Referenced by desc_data().
static struct type* thin_descriptor_type (struct type * type) [static, read]
Definition at line 1472 of file ada-lang.c.
References ada_find_parallel_type(), ada_type_name(), desc_base_type(), and is_suffix().
Referenced by desc_bounds(), desc_bounds_type(), desc_data_target_type(), and thin_data_pntr().
static struct type * to_fixed_array_type (struct type * type0, struct value * dval, int ignore_too_big) [static, read]
Definition at line 8049 of file ada-lang.c.
References _, ada_check_typedef(), ada_find_parallel_type(), ada_fixup_array_indexes_type(), ada_is_constrained_packed_array_type(), ada_to_fixed_type(), alloc_type_copy(), create_array_type(), decode_constrained_packed_array_type(), error(), HOST_CHAR_BIT, len, to_fixed_range_type(), TYPE_FIELD_BITSIZE, TYPE_FIELD_TYPE, TYPE_FIXED_INSTANCE, TYPE_INDEX_TYPE, TYPE_LENGTH, TYPE_NAME, TYPE_NFIELDS, TYPE_TARGET_TYPE, and varsize_limit.
Referenced by ada_to_fixed_type_1().
static struct type * to_fixed_range_type (struct type * raw_type, struct value * dval) [static, read]
Definition at line 10831 of file ada-lang.c.
References _, ada_discrete_type_high_bound(), ada_discrete_type_low_bound(), ada_scan_number(), alloc_type_copy(), create_range_type(), gdb_assert, get_int_var_value(), GROW_VECT, L, lim_warning(), LONGEST, name, scan_discrim_bound(), strchr(), strstr(), type, TYPE_CODE, TYPE_CODE_RANGE, TYPE_NAME, and TYPE_TARGET_TYPE.
Referenced by ada_array_bound_from_type(), constrained_packed_array_type(), and to_fixed_array_type().
static struct type* to_fixed_record_type (struct type * type0, const gdb_byte * valaddr, CORE_ADDR address, struct value * dval) [static, read]
Definition at line 7967 of file ada-lang.c.
References dynamic_template_type(), template_to_fixed_record_type(), to_record_with_fixed_variant_part(), TYPE_FIXED_INSTANCE, and variant_field_index().
Referenced by ada_to_fixed_type_1(), and to_fixed_variant_branch_type().
static struct type * to_fixed_variant_branch_type (struct type * var_type0, const gdb_byte * valaddr, CORE_ADDR address, struct value * dval) [static, read]
Definition at line 8003 of file ada-lang.c.
References ada_find_parallel_type(), ada_which_variant_applies(), empty_record(), is_dynamic_field(), is_unchecked_variant(), to_fixed_record_type(), TYPE_CODE, TYPE_CODE_PTR, TYPE_FIELD_TYPE, TYPE_TARGET_TYPE, value_contents(), value_type(), and variant_field_index().
Referenced by ada_template_to_fixed_record_type_1(), ada_to_fixed_type_1(), and to_record_with_fixed_variant_part().
static struct type* to_record_with_fixed_variant_part (struct type * type, const gdb_byte * valaddr, CORE_ADDR address, struct value * dval0) [static, read]
Definition at line 7888 of file ada-lang.c.
References ada_type_name(), alloc_type_copy(), cond_offset_host(), cond_offset_target(), INIT_CPLUS_SPECIFIC, memcpy(), to_fixed_variant_branch_type(), type, TYPE_ALLOC, TYPE_CODE, TYPE_CODE_STRUCT, TYPE_FIELD_BITPOS, TYPE_FIELD_BITSIZE, TYPE_FIELD_NAME, TYPE_FIELD_TYPE, TYPE_FIELDS, TYPE_FIXED_INSTANCE, TYPE_LENGTH, TYPE_NAME, TYPE_NFIELDS, TYPE_TAG_NAME, value_free_to_mark(), value_from_contents_and_address(), value_mark(), and variant_field_index().
Referenced by to_fixed_record_type().
static struct type * to_static_fixed_type (struct type * type0) [static, read]
Definition at line 8314 of file ada-lang.c.
References ada_check_typedef(), ada_find_parallel_type(), dynamic_template_type(), template_to_static_fixed_type(), type, TYPE_CODE, TYPE_CODE_STRUCT, TYPE_CODE_UNION, and TYPE_FIXED_INSTANCE.
Referenced by ada_get_decoded_type(), ada_lookup_struct_elt_type(), ada_to_fixed_type_1(), static_unwrap_type(), and template_to_static_fixed_type().
static struct type* type_from_tag (struct value * tag) [static, read]
Definition at line 6162 of file ada-lang.c.
References ada_encode(), ada_find_any_type(), and ada_tag_name().
Referenced by ada_tag_value_at_base_address(), and ada_to_fixed_type_1().
static ULONGEST umax_of_size (int size) [static]
Definition at line 658 of file ada-lang.c.
References ULONGEST.
Referenced by max_of_type().
static struct value * unwrap_value (struct value * val) [static, read]
Definition at line 8781 of file ada-lang.c.
References ada_check_typedef(), ada_find_parallel_type(), ada_get_base_type(), ada_is_aligner_type(), ada_to_fixed_type(), ada_type_name(), ada_value_struct_elt(), coerce_unspec_val_to_type(), TYPE_NAME, value_address(), and value_type().
Referenced by ada_to_fixed_value(), and assign_component().
int user_select_syms (struct ada_symbol_info * syms, int nsyms, int max_results)
Definition at line 3527 of file ada-lang.c.
References _, ada_print_type(), error(), find_function_start_sal(), gdb_stdout, get_selections(), symtab_and_line::line, LOC_BLOCK, LOC_CONST, multiple_symbols_all, multiple_symbols_cancel, multiple_symbols_select_mode(), printf_unfiltered(), sort_choices(), ada_symbol_info::sym, SYMBOL_CLASS, SYMBOL_LINE, SYMBOL_PRINT_NAME, SYMBOL_SYMTAB, SYMBOL_TYPE, symtab_and_line::symtab, symtab_to_filename_for_display(), TYPE_CODE, TYPE_CODE_ENUM, TYPE_NAME, and type_print_raw_options.
Referenced by ada_resolve_function(), and resolve_subexp().
static void value_assign_to_component (struct value * container, struct value * component, struct value * val) [static]
Definition at line 2557 of file ada-lang.c.
References bits, gdbarch_bits_big_endian(), get_type_arch(), LONGEST, move_bits(), TYPE_LENGTH, value_address(), value_bitpos(), value_bitsize(), value_cast(), value_contents(), value_contents_writeable(), and value_type().
Referenced by assign_component().
static CORE_ADDR value_pointer (struct value * value, struct type * type) [static]
Definition at line 4156 of file ada-lang.c.
References extract_unsigned_integer(), gdbarch_address_to_pointer(), gdbarch_byte_order(), get_type_arch(), len, TYPE_LENGTH, and value_address().
Referenced by make_array_descriptor().
static struct value * value_pos_atr (struct type * type, struct value * arg) [static, read]
Definition at line 8514 of file ada-lang.c.
References pos_atr(), and value_from_longest().
static struct value * value_subscript_packed (struct value * arr, int arity, struct value ** ind) [static, read]
Definition at line 2197 of file ada-lang.c.
References _, ada_check_typedef(), ada_value_primitive_packed_val(), bits, error(), get_discrete_bounds(), HOST_CHAR_BIT, lim_warning(), LONGEST, pos_atr(), TYPE_CODE, TYPE_CODE_ARRAY, TYPE_FIELD_BITSIZE, TYPE_INDEX_TYPE, TYPE_TARGET_TYPE, and value_type().
Referenced by ada_value_subscript().
static struct value* value_tag_from_contents_and_address (struct type * type, const gdb_byte * valaddr, CORE_ADDR address) [static, read]
Definition at line 6141 of file ada-lang.c.
References find_struct_field(), and value_from_contents_and_address().
Referenced by ada_tag_value_at_base_address(), and ada_to_fixed_type_1().
static struct value * value_val_atr (struct type * type, struct value * arg) [static, read]
Definition at line 8522 of file ada-lang.c.
References _, discrete_type_p(), error(), integer_type_p(), TYPE_CODE, TYPE_CODE_ENUM, TYPE_FIELD_ENUMVAL, TYPE_NFIELDS, value_as_long(), value_from_longest(), and value_type().
static int variant_field_index (struct type * type) [static]
Definition at line 7538 of file ada-lang.c.
References ada_is_variant_part(), TYPE_CODE, TYPE_CODE_STRUCT, and TYPE_NFIELDS.
Referenced by to_fixed_record_type(), to_fixed_variant_branch_type(), and to_record_with_fixed_variant_part().
static VEC (char_ptr) [static]
Definition at line 5891 of file ada-lang.c.
References ada_encode(), ada_expand_partial_symbol_name(), ALL_BLOCK_SYMBOLS, ALL_MSYMBOLS, ALL_SYMTABS, BLOCK_SUPERBLOCK, BLOCKVECTOR, BLOCKVECTOR_BLOCK, do_cleanups(), expand_partial_symbol_names(), gdb_assert, get_selected_block(), GLOBAL_BLOCK, make_cleanup(), null_cleanup(), QUIT, STATIC_BLOCK, strchr(), strstr(), symbol_completion_add(), SYMBOL_LINKAGE_NAME, TYPE_CODE_UNDEF, VEC, VEC_alloc, word, and xfree().
static int wild_match (const char * name, const char * patn) [static]
Definition at line 5561 of file ada-lang.c.
References advance_wild_match(), is_name_suffix(), is_valid_name_for_wild_match(), name, and p.
Referenced by ada_add_block_symbols(), ada_get_symbol_name_cmp(), add_nonlocal_symbols(), and match_name().
static char* xget_renaming_scope (struct type * renaming_type) [static]
Definition at line 4668 of file ada-lang.c.
References name, strstr(), type_name_no_tag(), and xmalloc().
Referenced by old_renaming_is_invisible().
Variable Documentation
initialize_file_ftype _initialize_ada_language
Referenced by initialize_all_files().
struct bp_location_ops ada_catchpoint_location_ops [static]
Initial value:
{
  ada_catchpoint_location_dtor
}
Definition at line 11402 of file ada-lang.c.
char* ada_completer_word_break_characters = " \t\n!@#$%^&*()+=|~`}{[]\";:?/,-" [static]
Definition at line 284 of file ada-lang.c.
Referenced by ada_get_gdb_completer_word_break_characters().
struct exp_descriptor ada_exp_descriptor [static]
Initial value:
 {
  ada_print_subexp,
  ada_operator_length,
  ada_operator_check,
  ada_op_name,
  ada_dump_subexp_body,
  ada_evaluate_subexp
}
Definition at line 12756 of file ada-lang.c.
struct inferior_data* ada_inferior_data [static]
Definition at line 332 of file ada-lang.c.
struct language_defn ada_language_defn
Definition at line 12799 of file ada-lang.c.
const char ADA_MAIN_PROGRAM_SYMBOL_NAME[] = "__gnat_ada_main_program_name" [static]
Definition at line 293 of file ada-lang.c.
Referenced by ada_main_name().
struct op_print ada_op_print_tab[] [static]
Definition at line 12636 of file ada-lang.c.
struct ada_opname_map ada_opname_table[]
Initial value:
 {
  {"Oadd", "\"+\"", BINOP_ADD},
  {"Osubtract", "\"-\"", BINOP_SUB},
  {"Omultiply", "\"*\"", BINOP_MUL},
  {"Odivide", "\"/\"", BINOP_DIV},
  {"Omod", "\"mod\"", BINOP_MOD},
  {"Orem", "\"rem\"", BINOP_REM},
  {"Oexpon", "\"**\"", BINOP_EXP},
  {"Olt", "\"<\"", BINOP_LESS},
  {"Ole", "\"<=\"", BINOP_LEQ},
  {"Ogt", "\">\"", BINOP_GTR},
  {"Oge", "\">=\"", BINOP_GEQ},
  {"Oeq", "\"=\"", BINOP_EQUAL},
  {"One", "\"/=\"", BINOP_NOTEQUAL},
  {"Oand", "\"and\"", BINOP_BITWISE_AND},
  {"Oor", "\"or\"", BINOP_BITWISE_IOR},
  {"Oxor", "\"xor\"", BINOP_BITWISE_XOR},
  {"Oconcat", "\"&\"", BINOP_CONCAT},
  {"Oabs", "\"abs\"", UNOP_ABS},
  {"Onot", "\"not\"", UNOP_LOGICAL_NOT},
  {"Oadd", "\"+\"", UNOP_PLUS},
  {"Osubtract", "\"-\"", UNOP_NEG},
  {NULL, NULL}
}
Definition at line 840 of file ada-lang.c.
Referenced by is_ada_operator().
const char* attribute_names[] [static]
Initial value:
 {
  "<?>",
  "first",
  "last",
  "length",
  "image",
  "max",
  "min",
  "modulus",
  "pos",
  "size",
  "tag",
  "val",
  0
}
Definition at line 8460 of file ada-lang.c.
char* bound_name[] [static]
Initial value:
 {
  "LB0", "UB0", "LB1", "UB1", "LB2", "UB2", "LB3", "UB3",
  "LB4", "UB4", "LB5", "UB5", "LB6", "UB6", "LB7", "UB7"
}
Definition at line 1426 of file ada-lang.c.
Referenced by desc_index_type(), and desc_one_bound().
struct breakpoint_ops catch_assert_breakpoint_ops [static]
Definition at line 11920 of file ada-lang.c.
Referenced by ada_exception_breakpoint_ops(), and initialize_ada_catchpoint_ops().
struct breakpoint_ops catch_exception_breakpoint_ops [static]
Definition at line 11814 of file ada-lang.c.
Referenced by ada_exception_breakpoint_ops(), and initialize_ada_catchpoint_ops().
struct breakpoint_ops catch_exception_unhandled_breakpoint_ops [static]
Definition at line 11868 of file ada-lang.c.
Referenced by ada_exception_breakpoint_ops(), and initialize_ada_catchpoint_ops().
struct htab* decoded_names_store [static]
Definition at line 1287 of file ada-lang.c.
Referenced by _initialize_ada_language(), and ada_decode_symbol().
struct exception_support_info default_exception_support_info [static]
Initial value:
{
  "__gnat_debug_raise_exception",
  "__gnat_unhandled_exception",
  "__gnat_debug_raise_assert_failure",
  ada_unhandled_exception_name_addr
}
Definition at line 11026 of file ada-lang.c.
Referenced by ada_exception_support_info_sniffer().
struct exception_support_info exception_support_info_fallback [static]
Initial value:
{
  "__gnat_raise_nodefer_with_msg",
  "__gnat_unhandled_exception",
  "system__assertions__raise_assert_failure",
  ada_unhandled_exception_name_addr_from_raise
}
Definition at line 11038 of file ada-lang.c.
Referenced by ada_exception_support_info_sniffer().
const char* known_auxiliary_function_name_patterns[] [static]
Initial value:
 {
  ADA_KNOWN_AUXILIARY_FUNCTION_NAME_PATTERNS NULL
}
Definition at line 306 of file ada-lang.c.
Referenced by is_known_support_routine().
const char* known_runtime_file_name_patterns[] [static]
Initial value:
 {
  ADA_KNOWN_RUNTIME_FILE_NAME_PATTERNS NULL
}
Definition at line 302 of file ada-lang.c.
Referenced by is_known_support_routine().
struct cmd_list_element* set_ada_list [static]
Definition at line 12844 of file ada-lang.c.
struct cmd_list_element* show_ada_list [static]
Definition at line 12845 of file ada-lang.c.
char* standard_exc[] [static]
Initial value:
 {
  "constraint_error",
  "program_error",
  "storage_error",
  "tasking_error"
}
Definition at line 10986 of file ada-lang.c.
Referenced by ada_exception_catchpoint_cond_string().
struct obstack symbol_list_obstack [static]
Definition at line 311 of file ada-lang.c.
Referenced by _initialize_ada_language(), and ada_lookup_symbol_list_worker().
int trust_pad_over_xvs = 1 [static]
Definition at line 8599 of file ada-lang.c.
unsigned int varsize_limit [static]
Definition at line 280 of file ada-lang.c.
Referenced by _initialize_ada_language(), ada_template_to_fixed_record_type_1(), check_size(), and to_fixed_array_type().
int warning_limit = 2 [static]
Definition at line 296 of file ada-lang.c.
Referenced by lim_warning().
int warnings_issued = 0 [static]
Definition at line 300 of file ada-lang.c.
Referenced by lim_warning(), and parse().