GDB (xrefs): /home/stan/gdb/src/gdb/ada-typeprint.c File Reference
/home/stan/gdb/src/gdb/ada-typeprint.c File Reference
#include "defs.h"
#include "gdb_obstack.h"
#include "bfd.h"
#include "symtab.h"
#include "gdbtypes.h"
#include "expression.h"
#include "value.h"
#include "gdbcore.h"
#include "target.h"
#include "command.h"
#include "gdbcmd.h"
#include "language.h"
#include "demangle.h"
#include "c-lang.h"
#include "typeprint.h"
#include "ada-lang.h"
#include <ctype.h>
#include "gdb_string.h"
#include <errno.h>
Functions
static int print_selected_record_field_types (struct type *, struct type *, int, int, struct ui_file *, int, int, const struct type_print_options *)
static int print_record_field_types (struct type *, struct type *, struct ui_file *, int, int, const struct type_print_options *)
static void print_array_type (struct type *, struct ui_file *, int, int, const struct type_print_options *)
static int print_choices (struct type *, int, struct ui_file *, struct type *)
static void print_range (struct type *, struct ui_file *)
static void print_range_bound (struct type *, char *, int *, struct ui_file *)
static void print_dynamic_range_bound (struct type *, const char *, int, const char *, struct ui_file *)
static void print_range_type (struct type *, struct ui_file *)
static char * decoded_type_name (struct type *type)
static void print_enum_type (struct type *type, struct ui_file *stream)
static void print_fixed_point_type (struct type *type, struct ui_file *stream)
static void print_variant_clauses (struct type *type, int field_num, struct type *outer_type, struct ui_file *stream, int show, int level, const struct type_print_options *flags)
static void print_variant_part (struct type *type, int field_num, struct type *outer_type, struct ui_file *stream, int show, int level, const struct type_print_options *flags)
static void print_record_type (struct type *type0, struct ui_file *stream, int show, int level, const struct type_print_options *flags)
static void print_unchecked_union_type (struct type *type, struct ui_file *stream, int show, int level, const struct type_print_options *flags)
static void print_func_type (struct type *type, struct ui_file *stream, const char *name, const struct type_print_options *flags)
void ada_print_type (struct type *type0, const char *varstring, struct ui_file *stream, int show, int level, const struct type_print_options *flags)
void ada_print_typedef (struct type *type, struct symbol *new_symbol, struct ui_file *stream)
Variables
static char * name_buffer
static int name_buffer_len
Function Documentation
void ada_print_type (struct type * type0, const char * varstring, struct ui_file * stream, int show, int level, const struct type_print_options * flags)
Definition at line 763 of file ada-typeprint.c.
References _, ada_aligned_type(), ada_check_typedef(), ada_get_base_type(), ada_is_aligner_type(), ada_is_array_descriptor_type(), ada_is_bogus_array_descriptor(), ada_is_constrained_packed_array_type(), ada_is_fixed_point_type(), ada_is_modular_type(), ada_is_range_type_name(), ada_modulus(), ada_name_prefix_len(), ada_print_type(), ada_type_name(), c_print_type(), decoded_type_name(), fprintf_filtered(), int_string(), name, print_array_type(), print_enum_type(), print_fixed_point_type(), print_func_type(), print_range(), print_range_type(), print_record_type(), print_unchecked_union_type(), TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_BOOL, TYPE_CODE_ENUM, TYPE_CODE_FLT, TYPE_CODE_FUNC, TYPE_CODE_INT, TYPE_CODE_PTR, TYPE_CODE_RANGE, TYPE_CODE_REF, TYPE_CODE_STRUCT, TYPE_CODE_TYPEDEF, TYPE_CODE_UNION, TYPE_LENGTH, and TYPE_TARGET_TYPE.
Referenced by ada_print_type(), ada_print_typedef(), print_array_type(), print_func_type(), print_selected_record_field_types(), print_unchecked_union_type(), and user_select_syms().
void ada_print_typedef (struct type * type, struct symbol * new_symbol, struct ui_file * stream)
Definition at line 883 of file ada-typeprint.c.
References ada_check_typedef(), ada_print_type(), fprintf_filtered(), and type_print_raw_options.
static char* decoded_type_name (struct type * type) [static]
Definition at line 75 of file ada-typeprint.c.
References ada_type_name(), name_buffer, name_buffer_len, strstr(), and xrealloc().
Referenced by ada_print_type(), and print_record_type().
static void print_array_type (struct type * type, struct ui_file * stream, int show, int level, const struct type_print_options * flags) [static]
Definition at line 328 of file ada-typeprint.c.
References _, ada_array_arity(), ada_array_element_type(), ada_coerce_to_simple_array_type(), ada_find_parallel_type(), ada_fixup_array_indexes_type(), ada_is_constrained_packed_array_type(), ada_is_simple_array_type(), ada_print_type(), fprintf_filtered(), print_range(), print_range_type(), TYPE_CODE, TYPE_CODE_ARRAY, TYPE_FIELD_BITSIZE, TYPE_FIELD_TYPE, TYPE_INDEX_TYPE, TYPE_NFIELDS, TYPE_TARGET_TYPE, and wrap_here().
Referenced by ada_print_type().
static int print_choices (struct type * type, int field_num, struct ui_file * stream, struct type * val_type) [static]
Definition at line 410 of file ada-typeprint.c.
References ada_print_scalar(), ada_scan_number(), fprintf_filtered(), L, LONGEST, name, p, and TYPE_FIELD_NAME.
Referenced by print_variant_clauses().
static void print_dynamic_range_bound (struct type * type, const char * name, int name_len, const char * suffix, struct ui_file * stream) [static]
Definition at line 203 of file ada-typeprint.c.
References ada_print_scalar(), B, fprintf_filtered(), get_int_var_value(), GROW_VECT, and LONGEST.
Referenced by print_range_type().
static void print_enum_type (struct type * type, struct ui_file * stream) [static]
Definition at line 276 of file ada-typeprint.c.
References ada_enum_name(), fprintf_filtered(), fputs_filtered(), len, LONGEST, plongest(), QUIT, TYPE_FIELD_ENUMVAL, TYPE_FIELD_NAME, TYPE_NFIELDS, and wrap_here().
Referenced by ada_print_type().
static void print_fixed_point_type (struct type * type, struct ui_file * stream) [static]
Definition at line 307 of file ada-typeprint.c.
References ada_delta(), ada_fixed_to_float(), and fprintf_filtered().
Referenced by ada_print_type().
static void print_func_type (struct type * type, struct ui_file * stream, const char * name, const struct type_print_options * flags) [static]
Definition at line 711 of file ada-typeprint.c.
References ada_print_type(), fprintf_filtered(), fputs_filtered(), len, TYPE_CODE, TYPE_CODE_VOID, TYPE_FIELD_TYPE, TYPE_NFIELDS, TYPE_TARGET_TYPE, and wrap_here().
Referenced by ada_print_type().
static void print_range (struct type * type, struct ui_file * stream) [static]
Definition at line 126 of file ada-typeprint.c.
References ada_discrete_type_high_bound(), ada_discrete_type_low_bound(), ada_name_prefix_len(), ada_print_scalar(), fprintf_filtered(), type, TYPE_CODE, TYPE_CODE_ENUM, TYPE_CODE_RANGE, TYPE_NAME, and TYPE_TARGET_TYPE.
Referenced by ada_print_type(), print_array_type(), and print_range_type().
static void print_range_bound (struct type * type, char * bounds, int * n, struct ui_file * stream) [static]
Definition at line 156 of file ada-typeprint.c.
References ada_print_scalar(), ada_scan_number(), B, fprintf_filtered(), LONGEST, strstr(), TYPE_CODE, and TYPE_CODE_INT.
Referenced by print_range_type().
static void print_range_type (struct type * raw_type, struct ui_file * stream) [static]
Definition at line 226 of file ada-typeprint.c.
References fprintf_filtered(), gdb_assert, name, print_dynamic_range_bound(), print_range(), print_range_bound(), strchr(), strstr(), TYPE_CODE, TYPE_CODE_RANGE, TYPE_NAME, and TYPE_TARGET_TYPE.
Referenced by ada_print_type(), and print_array_type().
static int print_record_field_types (struct type * type, struct type * outer_type, struct ui_file * stream, int show, int level, const struct type_print_options * flags) [static]
Definition at line 606 of file ada-typeprint.c.
References print_selected_record_field_types(), and TYPE_NFIELDS.
Referenced by print_record_type(), print_selected_record_field_types(), and print_variant_clauses().
static void print_record_type (struct type * type0, struct ui_file * stream, int show, int level, const struct type_print_options * flags) [static]
Definition at line 621 of file ada-typeprint.c.
References _, ada_find_parallel_type(), ada_is_tagged_type(), ada_parent_type(), ada_type_name(), decoded_type_name(), fprintf_filtered(), print_record_field_types(), and type.
Referenced by ada_print_type().
static int print_selected_record_field_types (struct type * type, struct type * outer_type, int fld0, int fld1, struct ui_file * stream, int show, int level, const struct type_print_options * flags) [static]
Definition at line 562 of file ada-typeprint.c.
References ada_is_ignored_field(), ada_is_parent_field(), ada_is_variant_part(), ada_is_wrapper_field(), ada_print_type(), fprintf_filtered(), print_record_field_types(), print_variant_part(), QUIT, TYPE_FIELD_NAME, TYPE_FIELD_TYPE, and TYPE_STUB.
Referenced by print_record_field_types(), and print_variant_clauses().
static void print_unchecked_union_type (struct type * type, struct ui_file * stream, int show, int level, const struct type_print_options * flags) [static]
Definition at line 676 of file ada-typeprint.c.
References ada_print_type(), fprintf_filtered(), TYPE_FIELD_NAME, TYPE_FIELD_TYPE, and TYPE_NFIELDS.
Referenced by ada_print_type().
static void print_variant_clauses (struct type * type, int field_num, struct type * outer_type, struct ui_file * stream, int show, int level, const struct type_print_options * flags) [static]
Definition at line 491 of file ada-typeprint.c.
References ada_find_parallel_type(), ada_variant_discrim_type(), fprintf_filtered(), print_choices(), print_record_field_types(), print_selected_record_field_types(), TYPE_CODE, TYPE_CODE_PTR, TYPE_CODE_UNION, TYPE_FIELD_TYPE, TYPE_NFIELDS, and TYPE_TARGET_TYPE.
Referenced by print_variant_part().
static void print_variant_part (struct type * type, int field_num, struct type * outer_type, struct ui_file * stream, int show, int level, const struct type_print_options * flags) [static]
Definition at line 540 of file ada-typeprint.c.
References ada_variant_discrim_name(), fprintf_filtered(), print_variant_clauses(), and TYPE_FIELD_TYPE.
Referenced by print_selected_record_field_types().
Variable Documentation
char* name_buffer [static]
Definition at line 68 of file ada-typeprint.c.
Referenced by decoded_type_name().
int name_buffer_len [static]
Definition at line 69 of file ada-typeprint.c.
Referenced by decoded_type_name().