GDB (xrefs): /home/stan/gdb/src/gdb/addrmap.h File Reference
/home/stan/gdb/src/gdb/addrmap.h File Reference
Typedefs
typedef int(* addrmap_foreach_fn)(void *data, CORE_ADDR start_addr, void *obj)
Functions
struct addrmap * addrmap_create_mutable (struct obstack *obstack)
void addrmap_set_empty (struct addrmap *map, CORE_ADDR start, CORE_ADDR end_inclusive, void *obj)
void * addrmap_find (struct addrmap *map, CORE_ADDR addr)
struct addrmap * addrmap_create_fixed (struct addrmap *original, struct obstack *obstack)
void addrmap_relocate (struct addrmap *map, CORE_ADDR offset)
int addrmap_foreach (struct addrmap *map, addrmap_foreach_fn fn, void *data)
Typedef Documentation
typedef int(* addrmap_foreach_fn)(void *data, CORE_ADDR start_addr, void *obj)
Definition at line 96 of file addrmap.h.
Function Documentation
struct addrmap* addrmap_create_fixed (struct addrmap * original, struct obstack * obstack) [read]
Definition at line 71 of file addrmap.c.
References addrmap_funcs::create_fixed, and addrmap::funcs.
Referenced by create_addrmap_from_index(), dwarf2_build_psymtabs_hard(), and make_blockvector().
struct addrmap* addrmap_create_mutable (struct obstack * obstack) [read]
Definition at line 573 of file addrmap.c.
References addrmap_mutable::addrmap, addrmap_mutable_funcs, addrmap_mutable::free_nodes, addrmap::funcs, addrmap_mutable::obstack, splay_compare_CORE_ADDR_ptr(), splay_obstack_alloc(), splay_obstack_free(), and addrmap_mutable::tree.
Referenced by create_addrmap_from_index(), dwarf2_build_psymtabs_hard(), and record_block_range().
void* addrmap_find (struct addrmap * map, CORE_ADDR addr)
Definition at line 64 of file addrmap.c.
References addrmap_funcs::find, and addrmap::funcs.
Referenced by block_starting_point_at(), dw2_find_pc_sect_symtab(), find_block_in_blockvector(), and find_pc_sect_psymtab().
int addrmap_foreach (struct addrmap * map, addrmap_foreach_fn fn, void * data)
Definition at line 87 of file addrmap.c.
References addrmap_funcs::foreach, and addrmap::funcs.
Referenced by write_address_map().
void addrmap_relocate (struct addrmap * map, CORE_ADDR offset)
Definition at line 80 of file addrmap.c.
References addrmap::funcs, and addrmap_funcs::relocate.
Referenced by objfile_relocate1().
void addrmap_set_empty (struct addrmap * map, CORE_ADDR start, CORE_ADDR end_inclusive, void * obj)
Definition at line 55 of file addrmap.c.
References addrmap::funcs, and addrmap_funcs::set_empty.
Referenced by add_partial_subprogram(), create_addrmap_from_index(), dwarf2_ranges_read(), process_psymtab_comp_unit_reader(), and record_block_range().