GDB (xrefs): /home/stan/gdb/src/gdb/alphaobsd-tdep.c File Reference
/home/stan/gdb/src/gdb/alphaobsd-tdep.c File Reference
#include "defs.h"
#include "frame.h"
#include "gdbcore.h"
#include "osabi.h"
#include "obsd-tdep.h"
#include "alpha-tdep.h"
#include "alphabsd-tdep.h"
#include "solib-svr4.h"
Functions
static LONGEST alphaobsd_sigtramp_offset (struct gdbarch *gdbarch, CORE_ADDR pc)
static int alphaobsd_pc_in_sigtramp (struct gdbarch *gdbarch, CORE_ADDR pc, const char *name)
static CORE_ADDR alphaobsd_sigcontext_addr (struct frame_info *this_frame)
static void alphaobsd_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
void _initialize_alphaobsd_tdep (void)
Variables
static const int alphaobsd_page_size = 8192
Function Documentation
void _initialize_alphaobsd_tdep (void)
Definition at line 133 of file alphaobsd-tdep.c.
References alphaobsd_init_abi(), GDB_OSABI_OPENBSD_ELF, and gdbarch_register_osabi().
static void alphaobsd_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch) [static]
Definition at line 98 of file alphaobsd-tdep.c.
References alpha_dwarf2_init_abi(), alpha_mdebug_init_abi(), alpha_software_single_step(), alphanbsd_regset_from_core_section(), alphaobsd_pc_in_sigtramp(), alphaobsd_sigcontext_addr(), alphaobsd_sigtramp_offset(), gdbarch_tdep::dynamic_sigtramp_offset, gdbarch_tdep(), gdbarch_tdep::jb_elt_size, gdbarch_tdep::jb_pc, obsd_skip_solib_resolver(), gdbarch_tdep::pc_in_sigtramp, set_gdbarch_regset_from_core_section(), set_gdbarch_skip_solib_resolver(), set_gdbarch_software_single_step(), set_solib_svr4_fetch_link_map_offsets(), gdbarch_tdep::sigcontext_addr, and svr4_lp64_fetch_link_map_offsets().
Referenced by _initialize_alphaobsd_tdep().
static int alphaobsd_pc_in_sigtramp (struct gdbarch * gdbarch, CORE_ADDR pc, const char * name) [static]
Definition at line 49 of file alphaobsd-tdep.c.
References ALPHA_INSN_SIZE, alpha_read_insn(), and alphaobsd_page_size.
Referenced by alphaobsd_init_abi().
static CORE_ADDR alphaobsd_sigcontext_addr (struct frame_info * this_frame) [static]
Definition at line 72 of file alphaobsd-tdep.c.
References ALPHA_A0_REGNUM, ALPHA_INSN_SIZE, ALPHA_SP_REGNUM, alphaobsd_sigtramp_offset(), get_frame_arch(), get_frame_memory_unsigned(), get_frame_pc(), get_frame_register_unsigned(), and sp.
Referenced by alphaobsd_init_abi().
static LONGEST alphaobsd_sigtramp_offset (struct gdbarch * gdbarch, CORE_ADDR pc) [static]
Definition at line 43 of file alphaobsd-tdep.c.
References alphaobsd_page_size.
Referenced by alphaobsd_init_abi(), and alphaobsd_sigcontext_addr().
Variable Documentation
const int alphaobsd_page_size = 8192 [static]
Definition at line 40 of file alphaobsd-tdep.c.
Referenced by alphaobsd_pc_in_sigtramp(), and alphaobsd_sigtramp_offset().