GDB (xrefs): /home/stan/gdb/src/gdb/alpha-nat.c File Reference
/home/stan/gdb/src/gdb/alpha-nat.c File Reference
#include "defs.h"
#include "gdb_string.h"
#include "inferior.h"
#include "gdbcore.h"
#include "target.h"
#include "procfs.h"
#include "regcache.h"
#include "alpha-tdep.h"
#include <sys/ptrace.h>
#include <alpha/coreregs.h>
#include <sys/user.h>
#include <sys/procfs.h>
#include "gregset.h"
Defines
#define EFL (EF_SIZE / 8)
Functions
static void fetch_osf_core_registers (struct regcache *regcache, char *core_reg_sect, unsigned core_reg_size, int which, CORE_ADDR reg_addr)
void supply_gregset (struct regcache *regcache, const gdb_gregset_t *gregsetp)
void fill_gregset (const struct regcache *regcache, gdb_gregset_t *gregsetp, int regno)
void supply_fpregset (struct regcache *regcache, const gdb_fpregset_t *fpregsetp)
void fill_fpregset (const struct regcache *regcache, gdb_fpregset_t *fpregsetp, int regno)
void _initialize_alpha_nat (void)
Variables
static struct core_fns alpha_osf_core_fns
initialize_file_ftype _initialize_alpha_nat
Define Documentation
#define EFL (EF_SIZE / 8)
Referenced by fetch_osf_core_registers().
Function Documentation
void _initialize_alpha_nat (void)
Definition at line 203 of file alpha-nat.c.
References _initialize_alpha_nat, add_target(), deprecated_add_core_fns(), and procfs_target().
static void fetch_osf_core_registers (struct regcache * regcache, char * core_reg_sect, unsigned core_reg_size, int which, CORE_ADDR reg_addr) [static]
Definition at line 47 of file alpha-nat.c.
References _, ALPHA_NUM_REGS, ALPHA_UNIQUE_REGNUM, ALPHA_ZERO_REGNUM, EFL, error(), gdbarch_cannot_fetch_register(), gdbarch_register_name(), get_regcache_arch(), and regcache_raw_supply().
void fill_fpregset (const struct regcache * regcache, gdb_fpregset_t * fpregsetp, int regno)
Definition at line 176 of file alpha-nat.c.
References alpha_fill_fp_regs().
void fill_gregset (const struct regcache * regcache, gdb_gregset_t * gregsetp, int regno)
Definition at line 154 of file alpha-nat.c.
References alpha_fill_int_regs().
void supply_fpregset (struct regcache * regcache, const gdb_fpregset_t * fpregsetp)
Definition at line 167 of file alpha-nat.c.
References alpha_supply_fp_regs().
void supply_gregset (struct regcache * regcache, const gdb_gregset_t * gregsetp)
Definition at line 145 of file alpha-nat.c.
References alpha_supply_int_regs().
Variable Documentation
initialize_file_ftype _initialize_alpha_nat
Referenced by _initialize_alpha_nat().
struct core_fns alpha_osf_core_fns [static]
Initial value:
{
  bfd_target_unknown_flavour,
  default_check_format,
  default_core_sniffer,
  fetch_osf_core_registers,
  NULL
}
Definition at line 188 of file alpha-nat.c.