GDB (xrefs): /home/stan/gdb/src/gdb/alpha-linux-tdep.c File Reference
/home/stan/gdb/src/gdb/alpha-linux-tdep.c File Reference
#include "defs.h"
#include "frame.h"
#include "gdb_assert.h"
#include "gdb_string.h"
#include "osabi.h"
#include "solib-svr4.h"
#include "symtab.h"
#include "regset.h"
#include "regcache.h"
#include "linux-tdep.h"
#include "alpha-tdep.h"
Enumerations
enum {
ALPHA_LINUX_SIGABRT = 6, ALPHA_LINUX_SIGEMT = 7, ALPHA_LINUX_SIGBUS = 10, ALPHA_LINUX_SIGSYS = 12,
ALPHA_LINUX_SIGURG = 16, ALPHA_LINUX_SIGSTOP = 17, ALPHA_LINUX_SIGTSTP = 18, ALPHA_LINUX_SIGCONT = 19,
ALPHA_LINUX_SIGCHLD = 20, ALPHA_LINUX_SIGIO = 23, ALPHA_LINUX_SIGINFO = 29, ALPHA_LINUX_SIGUSR1 = 30,
ALPHA_LINUX_SIGUSR2 = 31, ALPHA_LINUX_SIGPOLL = ALPHA_LINUX_SIGIO, ALPHA_LINUX_SIGPWR = ALPHA_LINUX_SIGINFO, ALPHA_LINUX_SIGIOT = ALPHA_LINUX_SIGABRT
}
Functions
static long alpha_linux_sigtramp_offset_1 (struct gdbarch *gdbarch, CORE_ADDR pc)
static LONGEST alpha_linux_sigtramp_offset (struct gdbarch *gdbarch, CORE_ADDR pc)
static int alpha_linux_pc_in_sigtramp (struct gdbarch *gdbarch, CORE_ADDR pc, const char *func_name)
static CORE_ADDR alpha_linux_sigcontext_addr (struct frame_info *this_frame)
static void alpha_linux_supply_gregset (const struct regset *regset, struct regcache *regcache, int regnum, const void *gregs, size_t len)
static void alpha_linux_supply_fpregset (const struct regset *regset, struct regcache *regcache, int regnum, const void *fpregs, size_t len)
static struct regset * alpha_linux_regset_from_core_section (struct gdbarch *gdbarch, const char *sect_name, size_t sect_size)
static enum gdb_signal alpha_linux_gdb_signal_from_target (struct gdbarch *gdbarch, int signal)
static int alpha_linux_gdb_signal_to_target (struct gdbarch *gdbarch, enum gdb_signal signal)
static void alpha_linux_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
void _initialize_alpha_linux_tdep (void)
Variables
static struct regset alpha_linux_gregset
static struct regset alpha_linux_fpregset
initialize_file_ftype _initialize_alpha_linux_tdep
Enumeration Type Documentation
anonymous enum
Enumerator:
ALPHA_LINUX_SIGABRT
ALPHA_LINUX_SIGEMT
ALPHA_LINUX_SIGBUS
ALPHA_LINUX_SIGSYS
ALPHA_LINUX_SIGURG
ALPHA_LINUX_SIGSTOP
ALPHA_LINUX_SIGTSTP
ALPHA_LINUX_SIGCONT
ALPHA_LINUX_SIGCHLD
ALPHA_LINUX_SIGIO
ALPHA_LINUX_SIGINFO
ALPHA_LINUX_SIGUSR1
ALPHA_LINUX_SIGUSR2
ALPHA_LINUX_SIGPOLL
ALPHA_LINUX_SIGPWR
ALPHA_LINUX_SIGIOT
Definition at line 38 of file alpha-linux-tdep.c.
Function Documentation
void _initialize_alpha_linux_tdep (void)
Definition at line 387 of file alpha-linux-tdep.c.
References _initialize_alpha_linux_tdep, alpha_linux_init_abi(), GDB_OSABI_LINUX, and gdbarch_register_osabi().
static enum gdb_signal alpha_linux_gdb_signal_from_target (struct gdbarch * gdbarch, int signal) [static]
Definition at line 241 of file alpha-linux-tdep.c.
References ALPHA_LINUX_SIGBUS, ALPHA_LINUX_SIGCHLD, ALPHA_LINUX_SIGCONT, ALPHA_LINUX_SIGEMT, ALPHA_LINUX_SIGINFO, ALPHA_LINUX_SIGIO, ALPHA_LINUX_SIGSTOP, ALPHA_LINUX_SIGSYS, ALPHA_LINUX_SIGTSTP, ALPHA_LINUX_SIGURG, ALPHA_LINUX_SIGUSR1, ALPHA_LINUX_SIGUSR2, and linux_gdb_signal_from_target().
Referenced by alpha_linux_init_abi().
static int alpha_linux_gdb_signal_to_target (struct gdbarch * gdbarch, enum gdb_signal signal) [static]
Definition at line 294 of file alpha-linux-tdep.c.
References ALPHA_LINUX_SIGBUS, ALPHA_LINUX_SIGCHLD, ALPHA_LINUX_SIGCONT, ALPHA_LINUX_SIGEMT, ALPHA_LINUX_SIGINFO, ALPHA_LINUX_SIGIO, ALPHA_LINUX_SIGPOLL, ALPHA_LINUX_SIGPWR, ALPHA_LINUX_SIGSTOP, ALPHA_LINUX_SIGSYS, ALPHA_LINUX_SIGTSTP, ALPHA_LINUX_SIGURG, ALPHA_LINUX_SIGUSR1, ALPHA_LINUX_SIGUSR2, and linux_gdb_signal_to_target().
Referenced by alpha_linux_init_abi().
static void alpha_linux_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch) [static]
Definition at line 346 of file alpha-linux-tdep.c.
References alpha_dwarf2_init_abi(), alpha_linux_gdb_signal_from_target(), alpha_linux_gdb_signal_to_target(), alpha_linux_pc_in_sigtramp(), alpha_linux_regset_from_core_section(), alpha_linux_sigcontext_addr(), alpha_linux_sigtramp_offset(), alpha_mdebug_init_abi(), gdbarch_tdep::dynamic_sigtramp_offset, find_solib_trampoline_target(), gdbarch_tdep(), gdbarch_tdep::jb_elt_size, gdbarch_tdep::jb_pc, linux_init_abi(), gdbarch_tdep::pc_in_sigtramp, set_gdbarch_fetch_tls_load_module_address(), set_gdbarch_gdb_signal_from_target(), set_gdbarch_gdb_signal_to_target(), set_gdbarch_regset_from_core_section(), set_gdbarch_skip_trampoline_code(), set_solib_svr4_fetch_link_map_offsets(), gdbarch_tdep::sigcontext_addr, svr4_fetch_objfile_link_map(), and svr4_lp64_fetch_link_map_offsets().
Referenced by _initialize_alpha_linux_tdep().
static int alpha_linux_pc_in_sigtramp (struct gdbarch * gdbarch, CORE_ADDR pc, const char * func_name) [static]
Definition at line 123 of file alpha-linux-tdep.c.
References alpha_linux_sigtramp_offset().
Referenced by alpha_linux_init_abi().
static struct regset* alpha_linux_regset_from_core_section (struct gdbarch * gdbarch, const char * sect_name, size_t sect_size) [static, read]
Definition at line 225 of file alpha-linux-tdep.c.
References alpha_linux_fpregset, and alpha_linux_gregset.
Referenced by alpha_linux_init_abi().
static CORE_ADDR alpha_linux_sigcontext_addr (struct frame_info * this_frame) [static]
Definition at line 130 of file alpha-linux-tdep.c.
References alpha_linux_sigtramp_offset(), alpha_read_insn(), ALPHA_SP_REGNUM, gdb_assert, get_frame_arch(), get_frame_pc(), get_frame_register_unsigned(), sp, and ULONGEST.
Referenced by alpha_linux_init_abi().
static LONGEST alpha_linux_sigtramp_offset (struct gdbarch * gdbarch, CORE_ADDR pc) [static]
Definition at line 97 of file alpha-linux-tdep.c.
References alpha_linux_sigtramp_offset_1().
Referenced by alpha_linux_init_abi(), alpha_linux_pc_in_sigtramp(), and alpha_linux_sigcontext_addr().
static long alpha_linux_sigtramp_offset_1 (struct gdbarch * gdbarch, CORE_ADDR pc) [static]
Definition at line 75 of file alpha-linux-tdep.c.
References alpha_read_insn().
Referenced by alpha_linux_sigtramp_offset().
static void alpha_linux_supply_fpregset (const struct regset * regset, struct regcache * regcache, int regnum, const void * fpregs, size_t len) [static]
Definition at line 191 of file alpha-linux-tdep.c.
References ALPHA_FP0_REGNUM, ALPHA_FPCR_REGNUM, gdb_assert, and regcache_raw_supply().
static void alpha_linux_supply_gregset (const struct regset * regset, struct regcache * regcache, int regnum, const void * gregs, size_t len) [static]
Definition at line 164 of file alpha-linux-tdep.c.
References ALPHA_PC_REGNUM, ALPHA_UNIQUE_REGNUM, ALPHA_ZERO_REGNUM, gdb_assert, and regcache_raw_supply().
Variable Documentation
initialize_file_ftype _initialize_alpha_linux_tdep
Referenced by _initialize_alpha_linux_tdep().
struct regset alpha_linux_fpregset [static]
Initial value:
{
  NULL,
  alpha_linux_supply_fpregset
}
Definition at line 215 of file alpha-linux-tdep.c.
Referenced by alpha_linux_regset_from_core_section().
struct regset alpha_linux_gregset [static]
Initial value:
{
  NULL,
  alpha_linux_supply_gregset
}
Definition at line 209 of file alpha-linux-tdep.c.
Referenced by alpha_linux_regset_from_core_section().