GDB (xrefs): /home/stan/gdb/src/gdb/alphafbsd-tdep.c File Reference
/home/stan/gdb/src/gdb/alphafbsd-tdep.c File Reference
#include "defs.h"
#include "value.h"
#include "osabi.h"
#include "alpha-tdep.h"
#include "solib-svr4.h"
Functions
static int alphafbsd_return_in_memory (struct type *type)
static int alphafbsd_pc_in_sigtramp (struct gdbarch *gdbarch, CORE_ADDR pc, const char *func_name)
static LONGEST alphafbsd_sigtramp_offset (struct gdbarch *gdbarch, CORE_ADDR pc)
static CORE_ADDR alphafbsd_sigcontext_addr (struct frame_info *this_frame)
static void alphafbsd_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
void _initialize_alphafbsd_tdep (void)
Variables
CORE_ADDR alphafbsd_sigtramp_start = 0x11ffff68
CORE_ADDR alphafbsd_sigtramp_end = 0x11ffffe0
Function Documentation
void _initialize_alphafbsd_tdep (void)
Definition at line 123 of file alphafbsd-tdep.c.
References alphafbsd_init_abi(), GDB_OSABI_FREEBSD_ELF, and gdbarch_register_osabi().
static void alphafbsd_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch) [static]
Definition at line 91 of file alphafbsd-tdep.c.
References alpha_dwarf2_init_abi(), alpha_mdebug_init_abi(), alphafbsd_pc_in_sigtramp(), alphafbsd_return_in_memory(), alphafbsd_sigcontext_addr(), alphafbsd_sigtramp_offset(), gdbarch_tdep::dynamic_sigtramp_offset, gdbarch_tdep(), gdbarch_tdep::jb_elt_size, gdbarch_tdep::jb_pc, gdbarch_tdep::pc_in_sigtramp, gdbarch_tdep::return_in_memory, gdbarch_tdep::sc_fpregs_offset, gdbarch_tdep::sc_pc_offset, gdbarch_tdep::sc_regs_offset, set_solib_svr4_fetch_link_map_offsets(), gdbarch_tdep::sigcontext_addr, and svr4_lp64_fetch_link_map_offsets().
Referenced by _initialize_alphafbsd_tdep().
static int alphafbsd_pc_in_sigtramp (struct gdbarch * gdbarch, CORE_ADDR pc, const char * func_name) [static]
Definition at line 67 of file alphafbsd-tdep.c.
References alphafbsd_sigtramp_end, and alphafbsd_sigtramp_start.
Referenced by alphafbsd_init_abi().
static int alphafbsd_return_in_memory (struct type * type) [static]
Definition at line 28 of file alphafbsd-tdep.c.
References ALPHA_REGISTER_SIZE, code, TYPE_CODE, TYPE_CODE_STRUCT, TYPE_CODE_UNION, TYPE_FIELD_BITPOS, TYPE_FIELD_BITSIZE, TYPE_LENGTH, and TYPE_NFIELDS.
Referenced by alphafbsd_init_abi().
static CORE_ADDR alphafbsd_sigcontext_addr (struct frame_info * this_frame) [static]
Definition at line 83 of file alphafbsd-tdep.c.
References ALPHA_SP_REGNUM, and get_frame_register_unsigned().
Referenced by alphafbsd_init_abi().
static LONGEST alphafbsd_sigtramp_offset (struct gdbarch * gdbarch, CORE_ADDR pc) [static]
Definition at line 74 of file alphafbsd-tdep.c.
References alphafbsd_sigtramp_start.
Referenced by alphafbsd_init_abi().
Variable Documentation
CORE_ADDR alphafbsd_sigtramp_end = 0x11ffffe0
Definition at line 64 of file alphafbsd-tdep.c.
Referenced by alphafbsd_pc_in_sigtramp().
CORE_ADDR alphafbsd_sigtramp_start = 0x11ffff68
Definition at line 63 of file alphafbsd-tdep.c.
Referenced by alphafbsd_pc_in_sigtramp(), and alphafbsd_sigtramp_offset().