GDB (xrefs): /home/stan/gdb/src/gdb/alphabsd-nat.c File Reference
/home/stan/gdb/src/gdb/alphabsd-nat.c File Reference
#include "defs.h"
#include "inferior.h"
#include "regcache.h"
#include "alpha-tdep.h"
#include "alphabsd-tdep.h"
#include "inf-ptrace.h"
#include <sys/types.h>
#include <sys/ptrace.h>
#include <machine/reg.h>
#include "gregset.h"
#include <sys/signal.h>
#include <machine/pcb.h>
#include "bsd-kvm.h"
Typedefs
typedef struct reg gregset_t
typedef struct fpreg fpregset_t
Functions
void supply_gregset (struct regcache *regcache, const gregset_t *gregsetp)
void fill_gregset (const struct regcache *regcache, gregset_t *gregsetp, int regno)
void supply_fpregset (struct regcache *regcache, const fpregset_t *fpregsetp)
void fill_fpregset (const struct regcache *regcache, fpregset_t *fpregsetp, int regno)
static int getregs_supplies (int regno)
static void alphabsd_fetch_inferior_registers (struct target_ops *ops, struct regcache *regcache, int regno)
static void alphabsd_store_inferior_registers (struct target_ops *ops, struct regcache *regcache, int regno)
static int alphabsd_supply_pcb (struct regcache *regcache, struct pcb *pcb)
void _initialize_alphabsd_nat (void)
Typedef Documentation
typedef struct fpreg fpregset_t
Definition at line 41 of file alphabsd-nat.c.
typedef struct reg gregset_t
Definition at line 37 of file alphabsd-nat.c.
Function Documentation
void _initialize_alphabsd_nat (void)
Definition at line 195 of file alphabsd-nat.c.
References add_target(), alphabsd_fetch_inferior_registers(), alphabsd_store_inferior_registers(), alphabsd_supply_pcb(), bsd_kvm_add_target(), inf_ptrace_target(), target_ops::to_fetch_registers, and target_ops::to_store_registers.
static void alphabsd_fetch_inferior_registers (struct target_ops * ops, struct regcache * regcache, int regno) [static]
Definition at line 87 of file alphabsd-nat.c.
References _, alphabsd_supply_fpreg(), alphabsd_supply_reg(), gdbarch_fp0_regnum(), get_regcache_arch(), getregs_supplies(), inferior_ptid, perror_with_name(), ptid_get_pid(), ptrace(), and PTRACE_TYPE_ARG3.
Referenced by _initialize_alphabsd_nat().
static void alphabsd_store_inferior_registers (struct target_ops * ops, struct regcache * regcache, int regno) [static]
Definition at line 120 of file alphabsd-nat.c.
References _, alphabsd_fill_fpreg(), alphabsd_fill_reg(), gdbarch_fp0_regnum(), get_regcache_arch(), getregs_supplies(), inferior_ptid, perror_with_name(), ptid_get_pid(), ptrace(), and PTRACE_TYPE_ARG3.
Referenced by _initialize_alphabsd_nat().
static int alphabsd_supply_pcb (struct regcache * regcache, struct pcb * pcb) [static]
Definition at line 167 of file alphabsd-nat.c.
References ALPHA_A0_REGNUM, ALPHA_RA_REGNUM, ALPHA_S0_REGNUM, ALPHA_SP_REGNUM, regcache_raw_supply(), and regnum.
Referenced by _initialize_alphabsd_nat().
void fill_fpregset (const struct regcache * regcache, fpregset_t * fpregsetp, int regno)
Definition at line 68 of file alphabsd-nat.c.
References alphabsd_fill_fpreg().
void fill_gregset (const struct regcache * regcache, gregset_t * gregsetp, int regno)
Definition at line 56 of file alphabsd-nat.c.
References alphabsd_fill_reg().
static int getregs_supplies (int regno) [static]
Definition at line 77 of file alphabsd-nat.c.
References ALPHA_PC_REGNUM, ALPHA_V0_REGNUM, and ALPHA_ZERO_REGNUM.
Referenced by alphabsd_fetch_inferior_registers(), and alphabsd_store_inferior_registers().
void supply_fpregset (struct regcache * regcache, const fpregset_t * fpregsetp)
Definition at line 62 of file alphabsd-nat.c.
References alphabsd_supply_fpreg().
void supply_gregset (struct regcache * regcache, const gregset_t * gregsetp)
Definition at line 50 of file alphabsd-nat.c.
References alphabsd_supply_reg().