GDB (xrefs): /home/stan/gdb/src/gdb/alpha-tdep.h File Reference
/home/stan/gdb/src/gdb/alpha-tdep.h File Reference
Classes
struct gdbarch_tdep
Defines
#define ALPHA_REGISTER_SIZE 8
#define ALPHA_NUM_REGS 67
#define ALPHA_V0_REGNUM 0 /* Function integer return value */
#define ALPHA_T7_REGNUM 8 /* Return address register for OSF/1 __add* */
#define ALPHA_S0_REGNUM 9 /* First saved register */
#define ALPHA_GCC_FP_REGNUM 15 /* Used by gcc as frame register */
#define ALPHA_A0_REGNUM 16 /* Loc of first arg during a subr call */
#define ALPHA_T9_REGNUM 23 /* Return address register for OSF/1 __div* */
#define ALPHA_RA_REGNUM 26 /* Contains return address value */
#define ALPHA_T12_REGNUM 27 /* Contains start addr of current proc */
#define ALPHA_GP_REGNUM 29 /* Contains the global pointer */
#define ALPHA_SP_REGNUM 30 /* Contains address of top of stack */
#define ALPHA_ZERO_REGNUM 31 /* Read-only register, always 0 */
#define ALPHA_FP0_REGNUM 32 /* Floating point register 0 */
#define ALPHA_FPA0_REGNUM 48 /* First float arg during a subr call */
#define ALPHA_FPCR_REGNUM 63 /* Floating point control register */
#define ALPHA_PC_REGNUM 64 /* Contains program counter */
#define ALPHA_UNIQUE_REGNUM 66 /* PAL_rduniq value */
#define ALPHA_INSN_SIZE 4
#define ALPHA_NUM_ARG_REGS 6
Functions
unsigned int alpha_read_insn (struct gdbarch *gdbarch, CORE_ADDR pc)
int alpha_software_single_step (struct frame_info *frame)
CORE_ADDR alpha_after_prologue (CORE_ADDR pc)
void alpha_mdebug_init_abi (struct gdbarch_info, struct gdbarch *)
void alpha_dwarf2_init_abi (struct gdbarch_info, struct gdbarch *)
void alpha_supply_int_regs (struct regcache *, int, const void *, const void *, const void *)
void alpha_fill_int_regs (const struct regcache *, int, void *, void *, void *)
void alpha_supply_fp_regs (struct regcache *, int, const void *, const void *)
void alpha_fill_fp_regs (const struct regcache *, int, void *, void *)
Define Documentation
#define ALPHA_A0_REGNUM 16 /* Loc of first arg during a subr call */
Definition at line 40 of file alpha-tdep.h.
Referenced by alpha_get_longjmp_target(), alpha_push_dummy_call(), alphabsd_supply_pcb(), and alphaobsd_sigcontext_addr().
#define ALPHA_FP0_REGNUM 32 /* Floating point register 0 */
Definition at line 47 of file alpha-tdep.h.
Referenced by alpha_convert_register_p(), alpha_extract_return_value(), alpha_fill_fp_regs(), alpha_gdbarch_init(), alpha_linux_supply_fpregset(), alpha_mdebug_frame_unwind_cache(), alpha_register_reggroup_p(), alpha_register_type(), alpha_sigtramp_register_address(), alpha_store_return_value(), alpha_supply_fp_regs(), and alphanbsd_supply_fpregset().
#define ALPHA_FPA0_REGNUM 48 /* First float arg during a subr call */
Definition at line 48 of file alpha-tdep.h.
Referenced by alpha_push_dummy_call().
#define ALPHA_FPCR_REGNUM 63 /* Floating point control register */
Definition at line 49 of file alpha-tdep.h.
Referenced by alpha_fill_fp_regs(), alpha_linux_supply_fpregset(), alpha_register_reggroup_p(), alpha_supply_fp_regs(), and alphanbsd_supply_fpregset().
#define ALPHA_GCC_FP_REGNUM 15 /* Used by gcc as frame register */
Definition at line 39 of file alpha-tdep.h.
Referenced by alpha_heuristic_frame_unwind_cache().
#define ALPHA_GP_REGNUM 29 /* Contains the global pointer */
Definition at line 44 of file alpha-tdep.h.
Referenced by alpha_register_type().
#define ALPHA_INSN_SIZE 4
Definition at line 54 of file alpha-tdep.h.
Referenced by alpha_deal_with_atomic_sequence(), alpha_gdbarch_init(), alpha_heuristic_analyze_probing_loop(), alpha_heuristic_frame_unwind_cache(), alpha_heuristic_proc_start(), alpha_next_pc(), alpha_read_insn(), alpha_skip_prologue(), alphaobsd_pc_in_sigtramp(), and alphaobsd_sigcontext_addr().
#define ALPHA_NUM_ARG_REGS 6
Definition at line 68 of file alpha-tdep.h.
Referenced by alpha_mdebug_frame_args_address(), and alpha_push_dummy_call().
#define ALPHA_NUM_REGS 67
Definition at line 30 of file alpha-tdep.h.
Referenced by alpha_gdbarch_init(), alpha_heuristic_frame_unwind_cache(), and fetch_osf_core_registers().
#define ALPHA_PC_REGNUM 64 /* Contains program counter */
Definition at line 50 of file alpha-tdep.h.
Referenced by alpha_fill_int_regs(), alpha_gdbarch_init(), alpha_heuristic_frame_prev_register(), alpha_linux_supply_gregset(), alpha_mdebug_frame_prev_register(), alpha_register_type(), alpha_sigtramp_register_address(), alpha_supply_int_regs(), alpha_unwind_pc(), alphanbsd_aout_supply_gregset(), alphanbsd_supply_gregset(), and getregs_supplies().
#define ALPHA_RA_REGNUM 26 /* Contains return address value */
Definition at line 42 of file alpha-tdep.h.
Referenced by alpha_heuristic_frame_unwind_cache(), alpha_push_dummy_call(), alphabsd_supply_pcb(), and find_proc_desc().
#define ALPHA_REGISTER_SIZE 8
Definition at line 27 of file alpha-tdep.h.
Referenced by alpha_extract_return_value(), alpha_get_longjmp_target(), alpha_push_dummy_call(), alpha_sigtramp_frame_this_id(), alpha_store_return_value(), and alphafbsd_return_in_memory().
#define ALPHA_S0_REGNUM 9 /* First saved register */
Definition at line 38 of file alpha-tdep.h.
Referenced by alphabsd_supply_pcb().
#define ALPHA_SP_REGNUM 30 /* Contains address of top of stack */
Definition at line 45 of file alpha-tdep.h.
Referenced by alpha_dummy_id(), alpha_gdbarch_init(), alpha_heuristic_analyze_probing_loop(), alpha_heuristic_frame_unwind_cache(), alpha_linux_sigcontext_addr(), alpha_mdebug_frame_unwind_cache(), alpha_mdebug_frameless(), alpha_push_dummy_call(), alpha_register_type(), alpha_sigtramp_frame_this_id(), alphabsd_supply_pcb(), alphafbsd_sigcontext_addr(), and alphaobsd_sigcontext_addr().
#define ALPHA_T12_REGNUM 27 /* Contains start addr of current proc */
Definition at line 43 of file alpha-tdep.h.
Referenced by alpha_push_dummy_call().
#define ALPHA_T7_REGNUM 8 /* Return address register for OSF/1 __add* */
Definition at line 37 of file alpha-tdep.h.
Referenced by alpha_heuristic_frame_unwind_cache().
#define ALPHA_T9_REGNUM 23 /* Return address register for OSF/1 __div* */
Definition at line 41 of file alpha-tdep.h.
Referenced by alpha_heuristic_frame_unwind_cache().
#define ALPHA_UNIQUE_REGNUM 66 /* PAL_rduniq value */
Definition at line 51 of file alpha-tdep.h.
Referenced by alpha_fill_int_regs(), alpha_linux_register_u_offset(), alpha_linux_supply_gregset(), alpha_register_reggroup_p(), alpha_supply_int_regs(), and fetch_osf_core_registers().
#define ALPHA_V0_REGNUM 0 /* Function integer return value */
Definition at line 36 of file alpha-tdep.h.
Referenced by alpha_extract_return_value(), alpha_return_value(), alpha_store_return_value(), and getregs_supplies().
#define ALPHA_ZERO_REGNUM 31 /* Read-only register, always 0 */
Definition at line 46 of file alpha-tdep.h.
Referenced by alpha_cannot_store_register(), alpha_linux_supply_gregset(), alpha_register_reggroup_p(), alpha_supply_int_regs(), alphanbsd_supply_gregset(), fetch_osf_core_registers(), and getregs_supplies().
Function Documentation
CORE_ADDR alpha_after_prologue (CORE_ADDR pc)
Definition at line 662 of file alpha-tdep.c.
References symtab_and_line::end, find_pc_line(), and find_pc_partial_function().
Referenced by alpha_mdebug_after_prologue(), and alpha_skip_prologue().
void alpha_dwarf2_init_abi (struct gdbarch_info , struct gdbarch *)
Definition at line 1858 of file alpha-tdep.c.
References dwarf2_append_unwinders(), dwarf2_frame_base_sniffer(), and frame_base_append_sniffer().
Referenced by alpha_linux_init_abi(), alphafbsd_init_abi(), alphanbsd_init_abi(), and alphaobsd_init_abi().
void alpha_fill_fp_regs (const struct regcache * , int , void * , void *)
Definition at line 1559 of file alpha-tdep.c.
References ALPHA_FP0_REGNUM, ALPHA_FPCR_REGNUM, and regcache_raw_collect().
Referenced by alphabsd_fill_fpreg(), and fill_fpregset().
void alpha_fill_int_regs (const struct regcache * , int , void * , void * , void *)
Definition at line 1525 of file alpha-tdep.c.
References ALPHA_PC_REGNUM, ALPHA_UNIQUE_REGNUM, and regcache_raw_collect().
Referenced by alphabsd_fill_reg(), and fill_gregset().
void alpha_mdebug_init_abi (struct gdbarch_info , struct gdbarch *)
Definition at line 404 of file alpha-mdebug-tdep.c.
References alpha_mdebug_frame_base_sniffer(), frame_base_append_sniffer(), frame_unwind_append_unwinder(), and gdbarch_tdep().
Referenced by alpha_linux_init_abi(), alpha_osf1_init_abi(), alphafbsd_init_abi(), alphanbsd_init_abi(), and alphaobsd_init_abi().
unsigned int alpha_read_insn (struct gdbarch * gdbarch, CORE_ADDR pc)
Definition at line 682 of file alpha-tdep.c.
References ALPHA_INSN_SIZE, extract_unsigned_integer(), gdbarch_byte_order(), memory_error(), exsummary::status, and target_read_memory().
Referenced by alpha_deal_with_atomic_sequence(), alpha_heuristic_analyze_probing_loop(), alpha_heuristic_frame_unwind_cache(), alpha_heuristic_proc_start(), alpha_linux_sigcontext_addr(), alpha_linux_sigtramp_offset_1(), alpha_next_pc(), alpha_skip_prologue(), and alphaobsd_pc_in_sigtramp().
int alpha_software_single_step (struct frame_info * frame)
Definition at line 1726 of file alpha-tdep.c.
References alpha_next_pc(), get_frame_address_space(), get_frame_arch(), get_frame_pc(), and insert_single_step_breakpoint().
Referenced by alpha_osf1_init_abi(), alphanbsd_init_abi(), and alphaobsd_init_abi().
void alpha_supply_fp_regs (struct regcache * , int , const void * , const void *)
Definition at line 1543 of file alpha-tdep.c.
References ALPHA_FP0_REGNUM, ALPHA_FPCR_REGNUM, and regcache_raw_supply().
Referenced by alphabsd_supply_fpreg(), and supply_fpregset().
void alpha_supply_int_regs (struct regcache * , int , const void * , const void * , const void *)
Definition at line 1500 of file alpha-tdep.c.
References ALPHA_PC_REGNUM, ALPHA_UNIQUE_REGNUM, ALPHA_ZERO_REGNUM, and regcache_raw_supply().
Referenced by alphabsd_supply_reg(), and supply_gregset().