GDB (xrefs): /home/stan/gdb/src/gdb/alpha-osf1-tdep.c File Reference
/home/stan/gdb/src/gdb/alpha-osf1-tdep.c File Reference
#include "defs.h"
#include "frame.h"
#include "gdbcore.h"
#include "value.h"
#include "osabi.h"
#include "gdb_string.h"
#include "objfiles.h"
#include "alpha-tdep.h"
Functions
static int alpha_osf1_pc_in_sigtramp (struct gdbarch *gdbarch, CORE_ADDR pc, const char *func_name)
static CORE_ADDR alpha_osf1_sigcontext_addr (struct frame_info *this_frame)
static void alpha_osf1_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
void _initialize_alpha_osf1_tdep (void)
Variables
initialize_file_ftype _initialize_alpha_osf1_tdep
Function Documentation
void _initialize_alpha_osf1_tdep (void)
Definition at line 75 of file alpha-osf1-tdep.c.
References _initialize_alpha_osf1_tdep, alpha_osf1_init_abi(), GDB_OSABI_OSF1, and gdbarch_register_osabi().
static void alpha_osf1_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch) [static]
Definition at line 51 of file alpha-osf1-tdep.c.
References alpha_mdebug_init_abi(), alpha_osf1_pc_in_sigtramp(), alpha_osf1_sigcontext_addr(), alpha_software_single_step(), gdbarch_tdep(), gdbarch_tdep::jb_elt_size, gdbarch_tdep::jb_pc, gdbarch_tdep::pc_in_sigtramp, set_gdbarch_software_single_step(), and gdbarch_tdep::sigcontext_addr.
Referenced by _initialize_alpha_osf1_tdep().
static int alpha_osf1_pc_in_sigtramp (struct gdbarch * gdbarch, CORE_ADDR pc, const char * func_name) [static]
Definition at line 30 of file alpha-osf1-tdep.c.
Referenced by alpha_osf1_init_abi().
static CORE_ADDR alpha_osf1_sigcontext_addr (struct frame_info * this_frame) [static]
Definition at line 37 of file alpha-osf1-tdep.c.
References gdbarch::byte_order, gdbarch_byte_order(), get_frame_arch(), get_frame_id(), get_next_frame(), null_frame_id, read_memory_integer(), and frame_id::stack_addr.
Referenced by alpha_osf1_init_abi().
Variable Documentation
initialize_file_ftype _initialize_alpha_osf1_tdep
Referenced by _initialize_alpha_osf1_tdep().