GDB (xrefs): /home/stan/gdb/src/gdb/alphanbsd-tdep.c File Reference
/home/stan/gdb/src/gdb/alphanbsd-tdep.c File Reference
#include "defs.h"
#include "frame.h"
#include "gdbcore.h"
#include "osabi.h"
#include "regcache.h"
#include "regset.h"
#include "value.h"
#include "gdb_assert.h"
#include "gdb_string.h"
#include "alpha-tdep.h"
#include "alphabsd-tdep.h"
#include "nbsd-tdep.h"
#include "solib-svr4.h"
#include "target.h"
Defines
#define ALPHANBSD_SIZEOF_GREGS (32 * 8)
#define ALPHANBSD_SIZEOF_FPREGS ((32 * 8) + 8)
#define RETCODE_NWORDS 4
#define RETCODE_SIZE (RETCODE_NWORDS * 4)
Functions
static void alphanbsd_supply_fpregset (const struct regset *regset, struct regcache *regcache, int regnum, const void *fpregs, size_t len)
static void alphanbsd_supply_gregset (const struct regset *regset, struct regcache *regcache, int regnum, const void *gregs, size_t len)
static void alphanbsd_aout_supply_gregset (const struct regset *regset, struct regcache *regcache, int regnum, const void *gregs, size_t len)
struct regset * alphanbsd_regset_from_core_section (struct gdbarch *gdbarch, const char *sect_name, size_t sect_size)
static LONGEST alphanbsd_sigtramp_offset (struct gdbarch *gdbarch, CORE_ADDR pc)
static int alphanbsd_pc_in_sigtramp (struct gdbarch *gdbarch, CORE_ADDR pc, const char *func_name)
static CORE_ADDR alphanbsd_sigcontext_addr (struct frame_info *frame)
static void alphanbsd_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
static enum gdb_osabi alphanbsd_core_osabi_sniffer (bfd *abfd)
void _initialize_alphanbsd_tdep (void)
Variables
static struct regset alphanbsd_gregset
static struct regset alphanbsd_fpregset
static struct regset alphanbsd_aout_gregset
static const gdb_byte sigtramp_retcode []
Define Documentation
#define ALPHANBSD_SIZEOF_FPREGS ((32 * 8) + 8)
Definition at line 48 of file alphanbsd-tdep.c.
Referenced by alphanbsd_aout_supply_gregset(), alphanbsd_regset_from_core_section(), and alphanbsd_supply_fpregset().
#define ALPHANBSD_SIZEOF_GREGS (32 * 8)
Definition at line 45 of file alphanbsd-tdep.c.
Referenced by alphanbsd_aout_supply_gregset(), alphanbsd_regset_from_core_section(), and alphanbsd_supply_gregset().
#define RETCODE_NWORDS 4
Definition at line 209 of file alphanbsd-tdep.c.
Referenced by alphanbsd_sigtramp_offset().
#define RETCODE_SIZE (RETCODE_NWORDS * 4)
Definition at line 210 of file alphanbsd-tdep.c.
Referenced by alphanbsd_sigtramp_offset().
Function Documentation
void _initialize_alphanbsd_tdep (void)
Definition at line 308 of file alphanbsd-tdep.c.
References alphanbsd_core_osabi_sniffer(), alphanbsd_init_abi(), GDB_OSABI_NETBSD_ELF, gdbarch_register_osabi(), and gdbarch_register_osabi_sniffer().
static void alphanbsd_aout_supply_gregset (const struct regset * regset, struct regcache * regcache, int regnum, const void * gregs, size_t len) [static]
Definition at line 103 of file alphanbsd-tdep.c.
References ALPHA_PC_REGNUM, ALPHANBSD_SIZEOF_FPREGS, ALPHANBSD_SIZEOF_GREGS, alphanbsd_supply_fpregset(), gdb_assert, regcache_raw_supply(), regmap, and gdbarch_tdep::regs.
static enum gdb_osabi alphanbsd_core_osabi_sniffer (bfd * abfd) [static]
Definition at line 295 of file alphanbsd-tdep.c.
References GDB_OSABI_NETBSD_ELF, and GDB_OSABI_UNKNOWN.
Referenced by _initialize_alphanbsd_tdep().
static void alphanbsd_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch) [static]
Definition at line 263 of file alphanbsd-tdep.c.
References alpha_dwarf2_init_abi(), alpha_mdebug_init_abi(), alpha_software_single_step(), alphanbsd_pc_in_sigtramp(), alphanbsd_regset_from_core_section(), alphanbsd_sigcontext_addr(), alphanbsd_sigtramp_offset(), gdbarch_tdep::dynamic_sigtramp_offset, gdbarch_tdep(), gdbarch_tdep::jb_elt_size, gdbarch_tdep::jb_pc, gdbarch_tdep::pc_in_sigtramp, set_gdbarch_regset_from_core_section(), set_gdbarch_software_single_step(), set_solib_svr4_fetch_link_map_offsets(), gdbarch_tdep::sigcontext_addr, and svr4_lp64_fetch_link_map_offsets().
Referenced by _initialize_alphanbsd_tdep().
static int alphanbsd_pc_in_sigtramp (struct gdbarch * gdbarch, CORE_ADDR pc, const char * func_name) [static]
Definition at line 243 of file alphanbsd-tdep.c.
References alphanbsd_sigtramp_offset(), and nbsd_pc_in_sigtramp().
Referenced by alphanbsd_init_abi().
struct regset* alphanbsd_regset_from_core_section (struct gdbarch * gdbarch, const char * sect_name, size_t sect_size) [read]
Definition at line 166 of file alphanbsd-tdep.c.
References alphanbsd_aout_gregset, alphanbsd_fpregset, alphanbsd_gregset, ALPHANBSD_SIZEOF_FPREGS, and ALPHANBSD_SIZEOF_GREGS.
Referenced by alphanbsd_init_abi(), and alphaobsd_init_abi().
static CORE_ADDR alphanbsd_sigcontext_addr (struct frame_info * frame) [static]
Definition at line 251 of file alphanbsd-tdep.c.
References get_frame_base(), and get_next_frame().
Referenced by alphanbsd_init_abi().
static LONGEST alphanbsd_sigtramp_offset (struct gdbarch * gdbarch, CORE_ADDR pc) [static]
Definition at line 213 of file alphanbsd-tdep.c.
References LONGEST, memcmp(), RETCODE_NWORDS, RETCODE_SIZE, sigtramp_retcode, and target_read_memory().
Referenced by alphanbsd_init_abi(), and alphanbsd_pc_in_sigtramp().
static void alphanbsd_supply_fpregset (const struct regset * regset, struct regcache * regcache, int regnum, const void * fpregs, size_t len) [static]
Definition at line 55 of file alphanbsd-tdep.c.
References ALPHA_FP0_REGNUM, ALPHA_FPCR_REGNUM, ALPHANBSD_SIZEOF_FPREGS, gdb_assert, regcache_raw_supply(), and gdbarch_tdep::regs.
Referenced by alphanbsd_aout_supply_gregset().
static void alphanbsd_supply_gregset (const struct regset * regset, struct regcache * regcache, int regnum, const void * gregs, size_t len) [static]
Definition at line 79 of file alphanbsd-tdep.c.
References ALPHA_PC_REGNUM, ALPHA_ZERO_REGNUM, ALPHANBSD_SIZEOF_GREGS, gdb_assert, regcache_raw_supply(), and gdbarch_tdep::regs.
Variable Documentation
struct regset alphanbsd_aout_gregset [static]
Initial value:
{
  NULL,
  alphanbsd_aout_supply_gregset
}
Definition at line 156 of file alphanbsd-tdep.c.
Referenced by alphanbsd_regset_from_core_section().
struct regset alphanbsd_fpregset [static]
Initial value:
{
  NULL,
  alphanbsd_supply_fpregset
}
Definition at line 150 of file alphanbsd-tdep.c.
Referenced by alphanbsd_regset_from_core_section().
struct regset alphanbsd_gregset [static]
Initial value:
{
  NULL,
  alphanbsd_supply_gregset
}
Definition at line 144 of file alphanbsd-tdep.c.
Referenced by alphanbsd_regset_from_core_section().
const gdb_byte sigtramp_retcode[] [static]
Initial value:
{
  0x00, 0x00, 0x1e, 0xa6,
  0x10, 0x00, 0xde, 0x23,
  0x27, 0x01, 0x1f, 0x20,
  0x83, 0x00, 0x00, 0x00,
}
Definition at line 202 of file alphanbsd-tdep.c.
Referenced by alphanbsd_sigtramp_offset().