GDB (xrefs): /home/stan/gdb/src/gdb/amd64fbsd-nat.c File Reference
/home/stan/gdb/src/gdb/amd64fbsd-nat.c File Reference
#include "defs.h"
#include "inferior.h"
#include "regcache.h"
#include "target.h"
#include "gdb_assert.h"
#include <signal.h>
#include <stddef.h>
#include <sys/types.h>
#include <sys/ptrace.h>
#include <sys/sysctl.h>
#include <machine/reg.h>
#include "fbsd-nat.h"
#include "amd64-tdep.h"
#include "amd64-nat.h"
#include "amd64bsd-nat.h"
#include "i386-nat.h"
#include <machine/pcb.h>
#include <osreldate.h>
#include "bsd-kvm.h"
Defines
#define REG_OFFSET(member) offsetof (struct reg, member)
#define SC_REG_OFFSET amd64fbsd_sc_reg_offset
#define SC_RIP_OFFSET SC_REG_OFFSET[AMD64_RIP_REGNUM]
#define SC_RSP_OFFSET SC_REG_OFFSET[AMD64_RSP_REGNUM]
#define SC_RBP_OFFSET SC_REG_OFFSET[AMD64_RBP_REGNUM]
Functions
static int amd64fbsd_supply_pcb (struct regcache *regcache, struct pcb *pcb)
static void amd64fbsd_mourn_inferior (struct target_ops *ops)
void _initialize_amd64fbsd_nat (void)
Variables
static int amd64fbsd64_r_reg_offset []
static int amd64fbsd32_r_reg_offset [I386_NUM_GREGS]
static void(* super_mourn_inferior)(struct target_ops *ops)
Define Documentation
#define REG_OFFSET (member) offsetof (struct reg, member)
Definition at line 41 of file amd64fbsd-nat.c.
#define SC_RBP_OFFSET SC_REG_OFFSET[AMD64_RBP_REGNUM]
Referenced by _initialize_amd64fbsd_nat().
#define SC_REG_OFFSET amd64fbsd_sc_reg_offset
#define SC_RIP_OFFSET SC_REG_OFFSET[AMD64_RIP_REGNUM]
Referenced by _initialize_amd64fbsd_nat().
#define SC_RSP_OFFSET SC_REG_OFFSET[AMD64_RSP_REGNUM]
Referenced by _initialize_amd64fbsd_nat().
Function Documentation
void _initialize_amd64fbsd_nat (void)
Definition at line 160 of file amd64fbsd-nat.c.
References _, add_target(), amd64_native_gregset32_reg_offset, amd64_native_gregset64_reg_offset, amd64bsd_dr_get_addr(), amd64bsd_dr_get_control(), amd64bsd_dr_get_status(), amd64bsd_dr_set_addr(), amd64bsd_dr_set_control(), amd64bsd_target(), amd64fbsd32_r_reg_offset, amd64fbsd64_r_reg_offset, amd64fbsd_mourn_inferior(), amd64fbsd_sigtramp_end_addr, amd64fbsd_sigtramp_start_addr, amd64fbsd_supply_pcb(), bsd_kvm_add_target(), fbsd_find_memory_regions(), fbsd_make_corefile_notes(), fbsd_pid_to_exec_file(), i386_dr_low_type::get_addr, i386_dr_low_type::get_control, i386_dr_low_type::get_status, i386_dr_low, i386_set_debug_register_length(), i386_use_watchpoints(), len, offset, SC_RBP_OFFSET, SC_RIP_OFFSET, SC_RSP_OFFSET, i386_dr_low_type::set_addr, i386_dr_low_type::set_control, super_mourn_inferior, target_ops::to_find_memory_regions, target_ops::to_make_corefile_notes, target_ops::to_mourn_inferior, target_ops::to_pid_to_exec_file, and warning().
static void amd64fbsd_mourn_inferior (struct target_ops * ops) [static]
Definition at line 148 of file amd64fbsd-nat.c.
References i386_cleanup_dregs(), and super_mourn_inferior.
Referenced by _initialize_amd64fbsd_nat().
static int amd64fbsd_supply_pcb (struct regcache * regcache, struct pcb * pcb) [static]
Definition at line 105 of file amd64fbsd-nat.c.
References AMD64_DS_REGNUM, AMD64_ES_REGNUM, AMD64_FS_REGNUM, AMD64_GS_REGNUM, AMD64_RBP_REGNUM, AMD64_RBX_REGNUM, AMD64_RIP_REGNUM, AMD64_RSP_REGNUM, and regcache_raw_supply().
Referenced by _initialize_amd64fbsd_nat().
Variable Documentation
int amd64fbsd32_r_reg_offset[I386_NUM_GREGS] [static]
Initial value:
{
  14 * 8, 13 * 8,
  12 * 8, 11 * 8,
  20 * 8, 10 * 8,
  9 * 8, 8 * 8,
  17 * 8, 19 * 8,
  18 * 8, 21 * 8,
  -1, -1, -1, -1
}
Definition at line 84 of file amd64fbsd-nat.c.
Referenced by _initialize_amd64fbsd_nat().
int amd64fbsd64_r_reg_offset[] [static]
Initial value:
{
  REG_OFFSET (r_rax),
  REG_OFFSET (r_rbx),
  REG_OFFSET (r_rcx),
  REG_OFFSET (r_rdx),
  REG_OFFSET (r_rsi),
  REG_OFFSET (r_rdi),
  REG_OFFSET (r_rbp),
  REG_OFFSET (r_rsp),
  REG_OFFSET (r_r8),
  REG_OFFSET (r_r9),
  REG_OFFSET (r_r10),
  REG_OFFSET (r_r11),
  REG_OFFSET (r_r12),
  REG_OFFSET (r_r13),
  REG_OFFSET (r_r14),
  REG_OFFSET (r_r15),
  REG_OFFSET (r_rip),
  REG_OFFSET (r_rflags),
  REG_OFFSET (r_cs),
  REG_OFFSET (r_ss),
  -1,
  -1,
  -1,
  -1
}
Definition at line 46 of file amd64fbsd-nat.c.
Referenced by _initialize_amd64fbsd_nat().
void(* super_mourn_inferior)(struct target_ops *ops) [static]
Definition at line 145 of file amd64fbsd-nat.c.
Referenced by _initialize_amd64fbsd_nat(), and amd64fbsd_mourn_inferior().