GDB (xrefs): /home/stan/gdb/src/gdb/amd64-windows-nat.c File Reference
/home/stan/gdb/src/gdb/amd64-windows-nat.c File Reference
#include "defs.h"
#include "windows-nat.h"
#include "i386-nat.h"
#include "amd64-tdep.h"
#include <windows.h>
Defines
#define context_offset(x) (offsetof (CONTEXT, x))
Functions
static int amd64_windows_segment_register_p (int regnum)
void _initialize_amd64_windows_nat (void)
Variables
static const int mappings []
initialize_file_ftype _initialize_amd64_windows_nat
Define Documentation
#define context_offset (x) (offsetof (CONTEXT, x))
Definition at line 25 of file amd64-windows-nat.c.
Referenced by do_windows_fetch_inferior_registers().
Function Documentation
void _initialize_amd64_windows_nat (void)
Definition at line 102 of file amd64-windows-nat.c.
References _initialize_amd64_windows_nat, amd64_windows_segment_register_p(), i386_set_debug_register_length(), mappings, windows_set_context_register_offsets(), and windows_set_segment_register_p().
static int amd64_windows_segment_register_p (int regnum) [static]
Definition at line 93 of file amd64-windows-nat.c.
References AMD64_CS_REGNUM, and AMD64_GS_REGNUM.
Referenced by _initialize_amd64_windows_nat().
Variable Documentation
initialize_file_ftype _initialize_amd64_windows_nat
Referenced by _initialize_amd64_windows_nat().
const int mappings[] [static]
Definition at line 26 of file amd64-windows-nat.c.
Referenced by _initialize_amd64_windows_nat(), and procfs_info_proc().