GDB (xrefs): /home/stan/gdb/src/gdb/amd64-tdep.h File Reference
/home/stan/gdb/src/gdb/amd64-tdep.h File Reference
#include "i386-tdep.h"
Defines
#define AMD64_NUM_GREGS 24
#define AMD64_NUM_REGS (AMD64_YMM15H_REGNUM + 1)
Enumerations
enum amd64_regnum {
AMD64_RAX_REGNUM, AMD64_RBX_REGNUM, AMD64_RCX_REGNUM, AMD64_RDX_REGNUM,
AMD64_RSI_REGNUM, AMD64_RDI_REGNUM, AMD64_RBP_REGNUM, AMD64_RSP_REGNUM,
AMD64_R8_REGNUM, AMD64_R9_REGNUM, AMD64_R10_REGNUM, AMD64_R11_REGNUM,
AMD64_R12_REGNUM, AMD64_R13_REGNUM, AMD64_R14_REGNUM, AMD64_R15_REGNUM,
AMD64_RIP_REGNUM, AMD64_EFLAGS_REGNUM, AMD64_CS_REGNUM, AMD64_SS_REGNUM,
AMD64_DS_REGNUM, AMD64_ES_REGNUM, AMD64_FS_REGNUM, AMD64_GS_REGNUM,
AMD64_ST0_REGNUM = 24, AMD64_ST1_REGNUM, AMD64_FCTRL_REGNUM = AMD64_ST0_REGNUM + 8, AMD64_FSTAT_REGNUM = AMD64_ST0_REGNUM + 9,
AMD64_FTAG_REGNUM = AMD64_ST0_REGNUM + 10, AMD64_XMM0_REGNUM = 40, AMD64_XMM1_REGNUM, AMD64_MXCSR_REGNUM = AMD64_XMM0_REGNUM + 16,
AMD64_YMM0H_REGNUM, AMD64_YMM15H_REGNUM = AMD64_YMM0H_REGNUM + 15
}
Functions
struct displaced_step_closure * amd64_displaced_step_copy_insn (struct gdbarch *gdbarch, CORE_ADDR from, CORE_ADDR to, struct regcache *regs)
void amd64_displaced_step_fixup (struct gdbarch *gdbarch, struct displaced_step_closure *closure, CORE_ADDR from, CORE_ADDR to, struct regcache *regs)
void amd64_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
void amd64_x32_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
void amd64_supply_fxsave (struct regcache *regcache, int regnum, const void *fxsave)
void amd64_supply_xsave (struct regcache *regcache, int regnum, const void *xsave)
void amd64_collect_fxsave (const struct regcache *regcache, int regnum, void *fxsave)
void amd64_collect_xsave (const struct regcache *regcache, int regnum, void *xsave, int gcore)
Variables
int amd64_linux_gregset_reg_offset []
int amd64nbsd_r_reg_offset []
int amd64obsd_r_reg_offset []
CORE_ADDR amd64fbsd_sigtramp_start_addr
CORE_ADDR amd64fbsd_sigtramp_end_addr
int amd64fbsd_sc_reg_offset []
Define Documentation
#define AMD64_NUM_GREGS 24
Definition at line 71 of file amd64-tdep.h.
Referenced by _initialize_amd64nbsd_tdep(), _initialize_amd64obsd_tdep(), and amd64_init_abi().
#define AMD64_NUM_REGS (AMD64_YMM15H_REGNUM + 1)
Definition at line 73 of file amd64-tdep.h.
Referenced by amd64_init_abi().
Enumeration Type Documentation
enum amd64_regnum
Enumerator:
AMD64_RAX_REGNUM
AMD64_RBX_REGNUM
AMD64_RCX_REGNUM
AMD64_RDX_REGNUM
AMD64_RSI_REGNUM
AMD64_RDI_REGNUM
AMD64_RBP_REGNUM
AMD64_RSP_REGNUM
AMD64_R8_REGNUM
AMD64_R9_REGNUM
AMD64_R10_REGNUM
AMD64_R11_REGNUM
AMD64_R12_REGNUM
AMD64_R13_REGNUM
AMD64_R14_REGNUM
AMD64_R15_REGNUM
AMD64_RIP_REGNUM
AMD64_EFLAGS_REGNUM
AMD64_CS_REGNUM
AMD64_SS_REGNUM
AMD64_DS_REGNUM
AMD64_ES_REGNUM
AMD64_FS_REGNUM
AMD64_GS_REGNUM
AMD64_ST0_REGNUM
AMD64_ST1_REGNUM
AMD64_FCTRL_REGNUM
AMD64_FSTAT_REGNUM
AMD64_FTAG_REGNUM
AMD64_XMM0_REGNUM
AMD64_XMM1_REGNUM
AMD64_MXCSR_REGNUM
AMD64_YMM0H_REGNUM
AMD64_YMM15H_REGNUM
Definition at line 32 of file amd64-tdep.h.
Function Documentation
void amd64_collect_fxsave (const struct regcache * regcache, int regnum, void * fxsave)
Definition at line 3058 of file amd64-tdep.c.
References gdbarch_bfd_arch_info(), gdbarch_tdep(), get_regcache_arch(), i387_collect_fxsave(), I387_FISEG_REGNUM, I387_FOSEG_REGNUM, regcache_raw_collect(), and gdbarch_tdep::regs.
Referenced by amd64_collect_fpregset(), amd64_linux_store_inferior_registers(), amd64bsd_store_inferior_registers(), fill_fpregset(), and i386_darwin_store_inferior_registers().
void amd64_collect_xsave (const struct regcache * regcache, int regnum, void * xsave, int gcore)
Definition at line 3079 of file amd64-tdep.c.
References gdbarch_bfd_arch_info(), gdbarch_tdep(), get_regcache_arch(), i387_collect_xsave(), I387_FISEG_REGNUM, I387_FOSEG_REGNUM, regcache_raw_collect(), and gdbarch_tdep::regs.
Referenced by amd64_collect_xstateregset(), and amd64_linux_store_inferior_registers().
struct displaced_step_closure* amd64_displaced_step_copy_insn (struct gdbarch * gdbarch, CORE_ADDR from, CORE_ADDR to, struct regcache * regs) [read]
Definition at line 1272 of file amd64-tdep.c.
References amd64_get_insn_details(), amd64_syscall_p(), debug_displaced, displaced_step_dump_bytes(), fixup_displaced_copy(), fprintf_unfiltered(), gdb_stdlog, gdbarch_max_insn_length(), displaced_step_closure::insn_buf, displaced_step_closure::insn_details, len, displaced_step_closure::max_len, memset(), amd64_insn::opcode_offset, paddress(), read_memory(), displaced_step_closure::tmp_used, write_memory(), and xmalloc().
Referenced by amd64_linux_init_abi_common().
void amd64_displaced_step_fixup (struct gdbarch * gdbarch, struct displaced_step_closure * closure, CORE_ADDR from, CORE_ADDR to, struct regcache * regs)
Definition at line 1417 of file amd64-tdep.c.
References amd64_absolute_call_p(), amd64_absolute_jmp_p(), amd64_call_p(), amd64_ret_p(), AMD64_RIP_REGNUM, AMD64_RSP_REGNUM, amd64_syscall_p(), debug_displaced, fprintf_unfiltered(), from, gdb_stdlog, gdbarch_byte_order(), displaced_step_closure::insn_buf, displaced_step_closure::insn_details, paddress(), read_memory_unsigned_integer(), regcache_cooked_read_unsigned(), regcache_cooked_write_unsigned(), displaced_step_closure::tmp_regno, displaced_step_closure::tmp_save, displaced_step_closure::tmp_used, ULONGEST, and write_memory_unsigned_integer().
Referenced by amd64_linux_init_abi_common().
void amd64_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch)
Definition at line 2825 of file amd64-tdep.c.
References amd64_dummy_id(), amd64_dwarf_reg_to_regnum(), AMD64_EFLAGS_REGNUM, amd64_frame_align(), amd64_gen_return_address(), amd64_get_longjmp_target(), AMD64_NUM_GREGS, AMD64_NUM_REGS, amd64_pseudo_register_name(), amd64_pseudo_register_read_value(), amd64_pseudo_register_write(), amd64_push_dummy_call(), amd64_record_regmap, amd64_register_names, amd64_regset_from_core_section(), amd64_relocate_instruction(), amd64_return_value(), AMD64_RIP_REGNUM, AMD64_RSP_REGNUM, amd64_skip_prologue(), AMD64_ST0_REGNUM, AMD64_YMM0H_REGNUM, amd64_ymmh_names, frame_base_set_default(), frame_unwind_append_unwinder(), frame_unwind_prepend_unwinder(), gdbarch_tdep(), gdbarch_tdep::gregset_reg_offset, i386_stap_is_single_operand(), i386_stap_parse_special_token(), i387_convert_register_p(), I387_NUM_REGS, i387_register_to_value(), I387_SIZEOF_FXSAVE, i387_value_to_register(), gdbarch_tdep::num_byte_regs, gdbarch_tdep::num_core_regs, gdbarch_tdep::num_dword_regs, gdbarch_tdep::num_mmx_regs, gdbarch_tdep::num_word_regs, gdbarch_tdep::num_xmm_regs, gdbarch_tdep::num_ymm_regs, gdbarch_tdep::record_regmap, gdbarch_tdep::register_names, set_gdbarch_convert_register_p(), set_gdbarch_dummy_id(), set_gdbarch_dwarf2_reg_to_regnum(), set_gdbarch_fp0_regnum(), set_gdbarch_frame_align(), set_gdbarch_frame_red_zone_size(), set_gdbarch_gen_return_address(), set_gdbarch_get_longjmp_target(), set_gdbarch_long_bit(), set_gdbarch_long_double_bit(), set_gdbarch_long_long_bit(), set_gdbarch_num_regs(), set_gdbarch_pc_regnum(), set_gdbarch_ps_regnum(), set_gdbarch_pseudo_register_read_value(), set_gdbarch_pseudo_register_write(), set_gdbarch_ptr_bit(), set_gdbarch_push_dummy_call(), set_gdbarch_register_to_value(), set_gdbarch_regset_from_core_section(), set_gdbarch_relocate_instruction(), set_gdbarch_return_value(), set_gdbarch_skip_prologue(), set_gdbarch_sp_regnum(), set_gdbarch_stab_reg_to_regnum(), set_gdbarch_stap_integer_prefix(), set_gdbarch_stap_is_single_operand(), set_gdbarch_stap_parse_special_token(), set_gdbarch_stap_register_indirection_prefix(), set_gdbarch_stap_register_indirection_suffix(), set_gdbarch_stap_register_prefix(), set_gdbarch_value_to_register(), set_tdesc_pseudo_register_name(), gdbarch_tdep::sizeof_fpregset, gdbarch_tdep::st0_regnum, gdbarch_info::target_desc, gdbarch_tdep::tdesc, tdesc_amd64, tdesc_find_feature(), tdesc_has_registers(), gdbarch_tdep::ymm0h_regnum, and gdbarch_tdep::ymmh_register_names.
Referenced by amd64_dicos_init_abi(), amd64_linux_init_abi(), amd64_sol2_init_abi(), amd64_windows_init_abi(), amd64_x32_init_abi(), amd64fbsd_init_abi(), amd64nbsd_init_abi(), amd64obsd_init_abi(), and x86_darwin_init_abi_64().
void amd64_supply_fxsave (struct regcache * regcache, int regnum, const void * fxsave)
Definition at line 3007 of file amd64-tdep.c.
References gdbarch_bfd_arch_info(), gdbarch_tdep(), get_regcache_arch(), I387_FISEG_REGNUM, I387_FOSEG_REGNUM, i387_supply_fxsave(), regcache_raw_supply(), and gdbarch_tdep::regs.
Referenced by amd64_linux_fetch_inferior_registers(), amd64_supply_fpregset(), amd64bsd_fetch_inferior_registers(), amd64obsd_supply_regset(), i386_darwin_fetch_inferior_registers(), and supply_fpregset().
void amd64_supply_xsave (struct regcache * regcache, int regnum, const void * xsave)
Definition at line 3030 of file amd64-tdep.c.
References gdbarch_bfd_arch_info(), gdbarch_tdep(), get_regcache_arch(), I387_FISEG_REGNUM, I387_FOSEG_REGNUM, i387_supply_xsave(), regcache_raw_supply(), and gdbarch_tdep::regs.
Referenced by amd64_linux_fetch_inferior_registers(), and amd64_supply_xstateregset().
void amd64_x32_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch)
Definition at line 2963 of file amd64-tdep.c.
References amd64_init_abi(), amd64_x32_pseudo_register_type(), gdbarch_tdep(), gdbarch_tdep::num_dword_regs, set_gdbarch_long_bit(), set_gdbarch_ptr_bit(), set_tdesc_pseudo_register_type(), gdbarch_info::target_desc, gdbarch_tdep::tdesc, tdesc_has_registers(), and tdesc_x32.
Referenced by amd64_x32_linux_init_abi().
Variable Documentation
int amd64_linux_gregset_reg_offset[]
Definition at line 67 of file amd64-linux-tdep.c.
Referenced by _initialize_amd64_linux_nat(), amd64_linux_init_abi(), and amd64_x32_linux_init_abi().
int amd64fbsd_sc_reg_offset[]
Definition at line 93 of file amd64fbsd-tdep.c.
Referenced by amd64fbsd_init_abi().
CORE_ADDR amd64fbsd_sigtramp_end_addr
Definition at line 90 of file amd64fbsd-tdep.c.
Referenced by _initialize_amd64fbsd_nat(), and amd64fbsd_init_abi().
CORE_ADDR amd64fbsd_sigtramp_start_addr
Definition at line 89 of file amd64fbsd-tdep.c.
Referenced by _initialize_amd64fbsd_nat(), and amd64fbsd_init_abi().
int amd64nbsd_r_reg_offset[]
Definition at line 70 of file amd64nbsd-tdep.c.
Referenced by _initialize_amd64nbsd_nat(), _initialize_amd64nbsd_tdep(), and amd64nbsd_init_abi().
int amd64obsd_r_reg_offset[]
Definition at line 168 of file amd64obsd-tdep.c.
Referenced by _initialize_amd64obsd_nat(), _initialize_amd64obsd_tdep(), and amd64obsd_init_abi().