GDB (xrefs): /home/stan/gdb/src/gdb/amd64fbsd-tdep.c File Reference
/home/stan/gdb/src/gdb/amd64fbsd-tdep.c File Reference
#include "defs.h"
#include "arch-utils.h"
#include "frame.h"
#include "gdbcore.h"
#include "regcache.h"
#include "osabi.h"
#include "gdb_assert.h"
#include "gdb_string.h"
#include "amd64-tdep.h"
#include "bsd-uthread.h"
#include "solib-svr4.h"
Functions
static CORE_ADDR amd64fbsd_sigcontext_addr (struct frame_info *this_frame)
static void amd64fbsd_supply_uthread (struct regcache *regcache, int regnum, CORE_ADDR addr)
static void amd64fbsd_collect_uthread (const struct regcache *regcache, int regnum, CORE_ADDR addr)
static void amd64fbsd_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
void _initialize_amd64fbsd_tdep (void)
Variables
static int amd64fbsd_r_reg_offset []
CORE_ADDR amd64fbsd_sigtramp_start_addr = 0x7fffffffffc0ULL
CORE_ADDR amd64fbsd_sigtramp_end_addr = 0x7fffffffffe0ULL
int amd64fbsd_sc_reg_offset []
static int amd64fbsd_jmp_buf_reg_offset []
Function Documentation
void _initialize_amd64fbsd_tdep (void)
Definition at line 217 of file amd64fbsd-tdep.c.
References amd64fbsd_init_abi(), GDB_OSABI_FREEBSD_ELF, and gdbarch_register_osabi().
static void amd64fbsd_collect_uthread (const struct regcache * regcache, int regnum, CORE_ADDR addr) [static]
Definition at line 164 of file amd64fbsd-tdep.c.
References amd64fbsd_jmp_buf_reg_offset, gdb_assert, regcache_raw_collect(), and write_memory().
Referenced by amd64fbsd_init_abi().
static void amd64fbsd_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch) [static]
Definition at line 184 of file amd64fbsd-tdep.c.
References amd64_init_abi(), amd64fbsd_collect_uthread(), amd64fbsd_r_reg_offset, amd64fbsd_sc_reg_offset, amd64fbsd_sigcontext_addr(), amd64fbsd_sigtramp_end_addr, amd64fbsd_sigtramp_start_addr, amd64fbsd_supply_uthread(), bsd_uthread_set_collect_uthread(), bsd_uthread_set_supply_uthread(), gdbarch_tdep(), gdbarch_tdep::gregset_num_regs, gdbarch_tdep::gregset_reg_offset, i386bsd_init_abi(), gdbarch_tdep::sc_num_regs, gdbarch_tdep::sc_reg_offset, set_solib_svr4_fetch_link_map_offsets(), gdbarch_tdep::sigcontext_addr, gdbarch_tdep::sigtramp_end, gdbarch_tdep::sigtramp_start, gdbarch_tdep::sizeof_gregset, and svr4_lp64_fetch_link_map_offsets().
Referenced by _initialize_amd64fbsd_tdep().
static CORE_ADDR amd64fbsd_sigcontext_addr (struct frame_info * this_frame) [static]
Definition at line 40 of file amd64fbsd-tdep.c.
References AMD64_RSP_REGNUM, frame_unwind_register_unsigned(), and sp.
Referenced by amd64fbsd_init_abi().
static void amd64fbsd_supply_uthread (struct regcache * regcache, int regnum, CORE_ADDR addr) [static]
Definition at line 144 of file amd64fbsd-tdep.c.
References amd64fbsd_jmp_buf_reg_offset, gdb_assert, read_memory(), and regcache_raw_supply().
Referenced by amd64fbsd_init_abi().
Variable Documentation
int amd64fbsd_jmp_buf_reg_offset[] [static]
Initial value:
{
  -1,
  1 * 8,
  -1,
  -1,
  -1,
  -1,
  3 * 8,
  2 * 8,
  -1,
  -1,
  -1,
  -1,
  4 * 8,
  5 * 8,
  6 * 8,
  7 * 8,
  0 * 8
}
Definition at line 122 of file amd64fbsd-tdep.c.
Referenced by amd64fbsd_collect_uthread(), and amd64fbsd_supply_uthread().
int amd64fbsd_r_reg_offset[] [static]
Initial value:
{
  14 * 8,
  11 * 8,
  13 * 8,
  12 * 8,
  9 * 8,
  8 * 8,
  10 * 8,
  20 * 8,
  7 * 8,
  6 * 8,
  5 * 8,
  4 * 8,
  3 * 8,
  2 * 8,
  1 * 8,
  0 * 8,
  17 * 8,
  19 * 8,
  18 * 8,
  21 * 8,
  -1,
  -1,
  -1,
  -1
}
Definition at line 60 of file amd64fbsd-tdep.c.
Referenced by amd64fbsd_init_abi().
int amd64fbsd_sc_reg_offset[]
Initial value:
{
  24 + 6 * 8,
  24 + 7 * 8,
  24 + 3 * 8,
  24 + 2 * 8,
  24 + 1 * 8,
  24 + 0 * 8,
  24 + 8 * 8,
  24 + 22 * 8,
  24 + 4 * 8,
  24 + 5 * 8,
  24 + 9 * 8,
  24 + 10 * 8,
  24 + 11 * 8,
  24 + 12 * 8,
  24 + 13 * 8,
  24 + 14 * 8,
  24 + 19 * 8,
  24 + 21 * 8,
  24 + 20 * 8,
  24 + 23 * 8,
  -1,
  -1,
  -1,
  -1
}
Definition at line 93 of file amd64fbsd-tdep.c.
Referenced by amd64fbsd_init_abi().
CORE_ADDR amd64fbsd_sigtramp_end_addr = 0x7fffffffffe0ULL
Definition at line 90 of file amd64fbsd-tdep.c.
Referenced by _initialize_amd64fbsd_nat(), and amd64fbsd_init_abi().
CORE_ADDR amd64fbsd_sigtramp_start_addr = 0x7fffffffffc0ULL
Definition at line 89 of file amd64fbsd-tdep.c.
Referenced by _initialize_amd64fbsd_nat(), and amd64fbsd_init_abi().