GDB (xrefs): /home/stan/gdb/src/gdb/amd64nbsd-tdep.c File Reference
/home/stan/gdb/src/gdb/amd64nbsd-tdep.c File Reference
#include "defs.h"
#include "arch-utils.h"
#include "frame.h"
#include "gdbcore.h"
#include "osabi.h"
#include "symtab.h"
#include "gdb_assert.h"
#include "amd64-tdep.h"
#include "nbsd-tdep.h"
#include "solib-svr4.h"
Functions
static int amd64nbsd_sigtramp_p (struct frame_info *this_frame)
static CORE_ADDR amd64nbsd_mcontext_addr (struct frame_info *this_frame)
static void amd64nbsd_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
void _initialize_amd64nbsd_tdep (void)
Variables
int amd64nbsd_r_reg_offset []
Function Documentation
void _initialize_amd64nbsd_tdep (void)
Definition at line 128 of file amd64nbsd-tdep.c.
References AMD64_NUM_GREGS, amd64nbsd_init_abi(), amd64nbsd_r_reg_offset, gdb_assert, GDB_OSABI_NETBSD_ELF, and gdbarch_register_osabi().
static void amd64nbsd_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch) [static]
Definition at line 99 of file amd64nbsd-tdep.c.
References amd64_init_abi(), amd64nbsd_mcontext_addr(), amd64nbsd_r_reg_offset, amd64nbsd_sigtramp_p(), gdbarch_tdep(), gdbarch_tdep::gregset_num_regs, gdbarch_tdep::gregset_reg_offset, gdbarch_tdep::jb_pc_offset, gdbarch_tdep::sc_num_regs, gdbarch_tdep::sc_reg_offset, set_solib_svr4_fetch_link_map_offsets(), gdbarch_tdep::sigcontext_addr, gdbarch_tdep::sigtramp_p, gdbarch_tdep::sizeof_gregset, and svr4_lp64_fetch_link_map_offsets().
Referenced by _initialize_amd64nbsd_tdep().
static CORE_ADDR amd64nbsd_mcontext_addr (struct frame_info * this_frame) [static]
Definition at line 52 of file amd64nbsd-tdep.c.
References AMD64_R15_REGNUM, and get_frame_register_unsigned().
Referenced by amd64nbsd_init_abi().
static int amd64nbsd_sigtramp_p (struct frame_info * this_frame) [static]
Definition at line 39 of file amd64nbsd-tdep.c.
References find_pc_partial_function(), get_frame_pc(), name, and nbsd_pc_in_sigtramp().
Referenced by amd64nbsd_init_abi().
Variable Documentation
int amd64nbsd_r_reg_offset[]
Initial value:
{
  14 * 8,
  13 * 8,
  3 * 8,
  2 * 8,
  1 * 8,
  0 * 8,
  12 * 8,
  24 * 8,
  4 * 8,
  5 * 8,
  6 * 8,
  7 * 8,
  8 * 8,
  9 * 8,
  10 * 8,
  11 * 8,
  21 * 8,
  23 * 8,
  22 * 8,
  25 * 8,
  18 * 8,
  17 * 8,
  16 * 8,
  15 * 8
}
Definition at line 70 of file amd64nbsd-tdep.c.
Referenced by _initialize_amd64nbsd_nat(), _initialize_amd64nbsd_tdep(), and amd64nbsd_init_abi().