GDB (xrefs): /home/stan/gdb/src/gdb/amd64bsd-nat.c File Reference
/home/stan/gdb/src/gdb/amd64bsd-nat.c File Reference
#include "defs.h"
#include "inferior.h"
#include "regcache.h"
#include "target.h"
#include "gdb_assert.h"
#include <signal.h>
#include <sys/types.h>
#include <sys/ptrace.h>
#include <machine/reg.h>
#include "amd64-tdep.h"
#include "amd64-nat.h"
#include "amd64bsd-nat.h"
#include "inf-ptrace.h"
Functions
static void amd64bsd_fetch_inferior_registers (struct target_ops *ops, struct regcache *regcache, int regnum)
static void amd64bsd_store_inferior_registers (struct target_ops *ops, struct regcache *regcache, int regnum)
struct target_ops * amd64bsd_target (void)
Function Documentation
static void amd64bsd_fetch_inferior_registers (struct target_ops * ops, struct regcache * regcache, int regnum) [static]
Definition at line 43 of file amd64bsd-nat.c.
References _, amd64_native_gregset_supplies_p(), amd64_supply_fxsave(), amd64_supply_native_gregset(), get_regcache_arch(), inferior_ptid, perror_with_name(), ptid_get_pid(), ptrace(), and PTRACE_TYPE_ARG3.
Referenced by amd64bsd_target().
static void amd64bsd_store_inferior_registers (struct target_ops * ops, struct regcache * regcache, int regnum) [static]
Definition at line 77 of file amd64bsd-nat.c.
References _, amd64_collect_fxsave(), amd64_collect_native_gregset(), amd64_native_gregset_supplies_p(), get_regcache_arch(), inferior_ptid, perror_with_name(), ptid_get_pid(), ptrace(), and PTRACE_TYPE_ARG3.
Referenced by amd64bsd_target().
struct target_ops* amd64bsd_target (void) [read]
Definition at line 120 of file amd64bsd-nat.c.
References amd64bsd_fetch_inferior_registers(), amd64bsd_store_inferior_registers(), inf_ptrace_target(), target_ops::to_fetch_registers, and target_ops::to_store_registers.
Referenced by _initialize_amd64fbsd_nat(), _initialize_amd64nbsd_nat(), and _initialize_amd64obsd_nat().