GDB (xrefs): /home/stan/gdb/src/gdb/annotate.h File Reference
/home/stan/gdb/src/gdb/annotate.h File Reference
#include "symtab.h"
#include "gdbtypes.h"
Functions
void annotate_breakpoint (int)
void annotate_catchpoint (int)
void annotate_watchpoint (int)
void annotate_starting (void)
void annotate_stopped (void)
void annotate_exited (int)
void annotate_signalled (void)
void annotate_signal_name (void)
void annotate_signal_name_end (void)
void annotate_signal_string (void)
void annotate_signal_string_end (void)
void annotate_signal (void)
void annotate_breakpoints_headers (void)
void annotate_field (int)
void annotate_breakpoints_table (void)
void annotate_record (void)
void annotate_breakpoints_table_end (void)
void annotate_frames_invalid (void)
void annotate_new_thread (void)
void annotate_thread_changed (void)
void annotate_display_prompt (void)
void annotate_field_begin (struct type *)
void annotate_field_name_end (void)
void annotate_field_value (void)
void annotate_field_end (void)
void annotate_quit (void)
void annotate_error (void)
void annotate_error_begin (void)
void annotate_value_history_begin (int, struct type *)
void annotate_value_begin (struct type *)
void annotate_value_history_value (void)
void annotate_value_history_end (void)
void annotate_value_end (void)
void annotate_display_begin (void)
void annotate_display_number_end (void)
void annotate_display_format (void)
void annotate_display_expression (void)
void annotate_display_expression_end (void)
void annotate_display_value (void)
void annotate_display_end (void)
void annotate_arg_begin (void)
void annotate_arg_name_end (void)
void annotate_arg_value (struct type *)
void annotate_arg_end (void)
void annotate_source (char *, int, int, int, struct gdbarch *, CORE_ADDR)
void annotate_frame_begin (int, struct gdbarch *, CORE_ADDR)
void annotate_function_call (void)
void annotate_signal_handler_caller (void)
void annotate_frame_address (void)
void annotate_frame_address_end (void)
void annotate_frame_function_name (void)
void annotate_frame_args (void)
void annotate_frame_source_begin (void)
void annotate_frame_source_file (void)
void annotate_frame_source_file_end (void)
void annotate_frame_source_line (void)
void annotate_frame_source_end (void)
void annotate_frame_where (void)
void annotate_frame_end (void)
void annotate_array_section_begin (int, struct type *)
void annotate_elt_rep (unsigned int)
void annotate_elt_rep_end (void)
void annotate_elt (void)
void annotate_array_section_end (void)
Variables
void(* deprecated_annotate_signalled_hook)(void)
void(* deprecated_annotate_signal_hook)(void)
Function Documentation
void annotate_arg_begin (void)
Definition at line 382 of file annotate.c.
References annotation_level, and printf_filtered().
Referenced by print_frame_arg(), and py_print_single_arg().
void annotate_arg_end (void)
Definition at line 407 of file annotate.c.
References annotation_level, and printf_filtered().
Referenced by enumerate_args(), and print_frame_arg().
void annotate_arg_name_end (void)
Definition at line 389 of file annotate.c.
References annotation_level, and printf_filtered().
Referenced by print_frame_arg(), and py_print_single_arg().
void annotate_arg_value (struct type *)
Definition at line 396 of file annotate.c.
References annotation_level, print_value_flags(), and printf_filtered().
Referenced by print_frame_arg(), and py_print_single_arg().
void annotate_array_section_begin (int , struct type *)
Definition at line 526 of file annotate.c.
References annotation_level, print_value_flags(), and printf_filtered().
Referenced by val_print_array_elements(), and val_print_packed_array_elements().
void annotate_array_section_end (void)
Definition at line 558 of file annotate.c.
References annotation_level, and printf_filtered().
Referenced by val_print_array_elements(), and val_print_packed_array_elements().
void annotate_breakpoint (int)
Definition at line 81 of file annotate.c.
References annotation_level, and printf_filtered().
Referenced by bkpt_print_it(), and print_it_ranged_breakpoint().
void annotate_breakpoints_headers (void)
Definition at line 171 of file annotate.c.
References annotation_level, and printf_filtered().
Referenced by breakpoint_1().
void annotate_breakpoints_table (void)
Definition at line 185 of file annotate.c.
References annotation_level, and printf_filtered().
Referenced by breakpoint_1().
void annotate_breakpoints_table_end (void)
Definition at line 199 of file annotate.c.
References annotation_level, and printf_filtered().
Referenced by breakpoint_1().
void annotate_catchpoint (int)
Definition at line 88 of file annotate.c.
References annotation_level, and printf_filtered().
Referenced by print_it_catch_exec(), print_it_catch_fork(), print_it_catch_solib(), print_it_catch_syscall(), print_it_catch_vfork(), print_it_exception(), print_it_exception_catchpoint(), and signal_catchpoint_print_it().
void annotate_display_begin (void)
Definition at line 333 of file annotate.c.
References annotation_level, and printf_filtered().
Referenced by do_one_display().
void annotate_display_end (void)
Definition at line 375 of file annotate.c.
References annotation_level, and printf_filtered().
Referenced by do_one_display().
void annotate_display_expression (void)
Definition at line 354 of file annotate.c.
References annotation_level, and printf_filtered().
Referenced by do_one_display().
void annotate_display_expression_end (void)
Definition at line 361 of file annotate.c.
References annotation_level, and printf_filtered().
Referenced by do_one_display().
void annotate_display_format (void)
Definition at line 347 of file annotate.c.
References annotation_level, and printf_filtered().
Referenced by do_one_display().
void annotate_display_number_end (void)
Definition at line 340 of file annotate.c.
References annotation_level, and printf_filtered().
Referenced by do_one_display().
void annotate_display_prompt (void)
Definition at line 569 of file annotate.c.
References breakpoints_invalid_emitted, and frames_invalid_emitted.
Referenced by display_gdb_prompt().
void annotate_display_value (void)
Definition at line 368 of file annotate.c.
References annotation_level, and printf_filtered().
Referenced by do_one_display().
void annotate_elt (void)
Definition at line 551 of file annotate.c.
References annotation_level, and printf_filtered().
Referenced by val_print_array_elements(), and val_print_packed_array_elements().
void annotate_elt_rep (unsigned int)
Definition at line 537 of file annotate.c.
References annotation_level, and printf_filtered().
Referenced by val_print_array_elements(), and val_print_packed_array_elements().
void annotate_elt_rep_end (void)
Definition at line 544 of file annotate.c.
References annotation_level, and printf_filtered().
Referenced by val_print_array_elements(), and val_print_packed_array_elements().
void annotate_error (void)
Definition at line 276 of file annotate.c.
References annotation_level, and printf_filtered().
Referenced by print_exception().
void annotate_error_begin (void)
Definition at line 283 of file annotate.c.
References annotation_level, fprintf_filtered(), and gdb_stderr.
Referenced by print_any_exception(), and print_flush().
void annotate_exited (int)
Definition at line 116 of file annotate.c.
References annotation_level, and printf_filtered().
Referenced by print_exited_reason().
void annotate_field (int)
Definition at line 178 of file annotate.c.
References annotation_level, and printf_filtered().
Referenced by breakpoint_1(), print_one_breakpoint_location(), print_one_catch_exec(), print_one_catch_fork(), print_one_catch_solib(), print_one_catch_syscall(), print_one_catch_vfork(), print_one_exception(), print_one_exception_catchpoint(), print_one_ranged_breakpoint(), and signal_catchpoint_print_one().
void annotate_field_begin (struct type *)
Definition at line 237 of file annotate.c.
References annotation_level, print_value_flags(), and printf_filtered().
Referenced by cp_print_value_fields(), java_print_value_fields(), pascal_object_print_value_fields(), and print_field_values().
void annotate_field_end (void)
Definition at line 262 of file annotate.c.
References annotation_level, and printf_filtered().
Referenced by cp_print_value_fields(), java_print_value_fields(), pascal_object_print_value_fields(), and print_field_values().
void annotate_field_name_end (void)
Definition at line 248 of file annotate.c.
References annotation_level, and printf_filtered().
Referenced by cp_print_value_fields(), java_print_value_fields(), pascal_object_print_value_fields(), and print_field_values().
void annotate_field_value (void)
Definition at line 255 of file annotate.c.
References annotation_level, and printf_filtered().
Referenced by cp_print_value_fields(), java_print_value_fields(), pascal_object_print_value_fields(), and print_field_values().
void annotate_frame_address (void)
Definition at line 449 of file annotate.c.
References annotation_level, and printf_filtered().
Referenced by print_frame(), print_frame_info(), and py_print_frame().
void annotate_frame_address_end (void)
Definition at line 456 of file annotate.c.
References annotation_level, and printf_filtered().
Referenced by print_frame(), print_frame_info(), and py_print_frame().
void annotate_frame_args (void)
Definition at line 470 of file annotate.c.
References annotation_level, and printf_filtered().
Referenced by enumerate_args(), print_frame(), and py_print_args().
void annotate_frame_begin (int , struct gdbarch * , CORE_ADDR)
Definition at line 427 of file annotate.c.
References annotation_level, paddress(), and printf_filtered().
Referenced by print_frame(), print_frame_info(), and py_print_frame().
void annotate_frame_end (void)
Definition at line 519 of file annotate.c.
References annotation_level, and printf_filtered().
Referenced by print_frame_info(), and py_print_frame().
void annotate_frame_function_name (void)
Definition at line 463 of file annotate.c.
References annotation_level, and printf_filtered().
Referenced by print_frame(), and py_print_frame().
void annotate_frame_source_begin (void)
Definition at line 477 of file annotate.c.
References annotation_level, and printf_filtered().
Referenced by print_frame(), and py_print_frame().
void annotate_frame_source_end (void)
Definition at line 505 of file annotate.c.
References annotation_level, and printf_filtered().
Referenced by print_frame().
void annotate_frame_source_file (void)
Definition at line 484 of file annotate.c.
References annotation_level, and printf_filtered().
Referenced by print_frame(), and py_print_frame().
void annotate_frame_source_file_end (void)
Definition at line 491 of file annotate.c.
References annotation_level, and printf_filtered().
Referenced by print_frame(), and py_print_frame().
void annotate_frame_source_line (void)
Definition at line 498 of file annotate.c.
References annotation_level, and printf_filtered().
Referenced by print_frame(), and py_print_frame().
void annotate_frame_where (void)
Definition at line 512 of file annotate.c.
References annotation_level, and printf_filtered().
Referenced by print_frame().
void annotate_frames_invalid (void)
Definition at line 206 of file annotate.c.
References annotation_level, async_background_execution_p(), frames_invalid_emitted, printf_unfiltered(), and target_terminal_ours.
Referenced by reinit_frame_cache().
void annotate_function_call (void)
Definition at line 435 of file annotate.c.
References annotation_level, and printf_filtered().
Referenced by print_frame_info().
void annotate_new_thread (void)
Definition at line 219 of file annotate.c.
References annotation_level, and printf_unfiltered().
Referenced by add_thread_with_info().
void annotate_quit (void)
Definition at line 269 of file annotate.c.
References annotation_level, and printf_filtered().
Referenced by print_exception().
void annotate_record (void)
Definition at line 192 of file annotate.c.
References annotation_level, and printf_filtered().
Referenced by print_one_breakpoint_location().
void annotate_signal (void)
Definition at line 161 of file annotate.c.
References annotation_level, deprecated_annotate_signal_hook, and printf_filtered().
Referenced by print_signal_received_reason().
void annotate_signal_handler_caller (void)
Definition at line 442 of file annotate.c.
References annotation_level, and printf_filtered().
Referenced by print_frame_info().
void annotate_signal_name (void)
Definition at line 133 of file annotate.c.
References annotation_level, and printf_filtered().
Referenced by print_signal_exited_reason(), and print_signal_received_reason().
void annotate_signal_name_end (void)
Definition at line 140 of file annotate.c.
References annotation_level, and printf_filtered().
Referenced by print_signal_exited_reason(), and print_signal_received_reason().
void annotate_signal_string (void)
Definition at line 147 of file annotate.c.
References annotation_level, and printf_filtered().
Referenced by print_signal_exited_reason(), and print_signal_received_reason().
void annotate_signal_string_end (void)
Definition at line 154 of file annotate.c.
References annotation_level, and printf_filtered().
Referenced by print_signal_exited_reason(), and print_signal_received_reason().
void annotate_signalled (void)
Definition at line 123 of file annotate.c.
References annotation_level, deprecated_annotate_signalled_hook, and printf_filtered().
Referenced by print_signal_exited_reason().
void annotate_source (char * , int , int , int , struct gdbarch * , CORE_ADDR)
Definition at line 414 of file annotate.c.
References annotation_level, paddress(), and printf_filtered().
Referenced by identify_source_line().
void annotate_starting (void)
Definition at line 102 of file annotate.c.
References annotation_level, and printf_filtered().
Referenced by proceed().
void annotate_stopped (void)
Definition at line 109 of file annotate.c.
References annotation_level, and printf_filtered().
Referenced by normal_stop().
void annotate_thread_changed (void)
Definition at line 228 of file annotate.c.
References annotation_level, and printf_unfiltered().
Referenced by do_captured_thread_select(), and normal_stop().
void annotate_value_begin (struct type *)
Definition at line 301 of file annotate.c.
References annotation_level, print_value_flags(), and printf_filtered().
Referenced by output_command_const(), and print_command_1().
void annotate_value_end (void)
Definition at line 326 of file annotate.c.
References annotation_level, and printf_filtered().
Referenced by output_command_const(), and print_command_1().
void annotate_value_history_begin (int , struct type *)
Definition at line 290 of file annotate.c.
References annotation_level, print_value_flags(), and printf_filtered().
Referenced by print_command_1().
void annotate_value_history_end (void)
Definition at line 319 of file annotate.c.
References annotation_level, and printf_filtered().
Referenced by print_command_1().
void annotate_value_history_value (void)
Definition at line 312 of file annotate.c.
References annotation_level, and printf_filtered().
Referenced by print_command_1().
void annotate_watchpoint (int)
Definition at line 95 of file annotate.c.
References annotation_level, and printf_filtered().
Referenced by print_it_masked_watchpoint(), and print_it_watchpoint().
Variable Documentation
void(* deprecated_annotate_signal_hook)(void)
Definition at line 39 of file annotate.c.
Referenced by annotate_signal(), and gdbtk_add_hooks().
void(* deprecated_annotate_signalled_hook)(void)
Definition at line 38 of file annotate.c.
Referenced by annotate_signalled(), and gdbtk_add_hooks().