GDB (xrefs): /home/stan/gdb/src/gdb/arch-utils.c File Reference
/home/stan/gdb/src/gdb/arch-utils.c File Reference
#include "defs.h"
#include "arch-utils.h"
#include "buildsym.h"
#include "gdbcmd.h"
#include "inferior.h"
#include "gdb_string.h"
#include "regcache.h"
#include "gdb_assert.h"
#include "sim-regno.h"
#include "gdbcore.h"
#include "osabi.h"
#include "target-descriptions.h"
#include "objfiles.h"
#include "language.h"
#include "version.h"
#include "floatformat.h"
Enumerations
enum set_arch { set_arch_auto, set_arch_manual }
Functions
struct displaced_step_closure * simple_displaced_step_copy_insn (struct gdbarch *gdbarch, CORE_ADDR from, CORE_ADDR to, struct regcache *regs)
void simple_displaced_step_free_closure (struct gdbarch *gdbarch, struct displaced_step_closure *closure)
int default_displaced_step_hw_singlestep (struct gdbarch *gdbarch, struct displaced_step_closure *closure)
CORE_ADDR displaced_step_at_entry_point (struct gdbarch *gdbarch)
int legacy_register_sim_regno (struct gdbarch *gdbarch, int regnum)
CORE_ADDR generic_skip_trampoline_code (struct frame_info *frame, CORE_ADDR pc)
CORE_ADDR generic_skip_solib_resolver (struct gdbarch *gdbarch, CORE_ADDR pc)
int generic_in_solib_return_trampoline (struct gdbarch *gdbarch, CORE_ADDR pc, const char *name)
int generic_in_function_epilogue_p (struct gdbarch *gdbarch, CORE_ADDR pc)
int core_addr_lessthan (CORE_ADDR lhs, CORE_ADDR rhs)
int core_addr_greaterthan (CORE_ADDR lhs, CORE_ADDR rhs)
CORE_ADDR core_addr_identity (struct gdbarch *gdbarch, CORE_ADDR addr)
CORE_ADDR convert_from_func_ptr_addr_identity (struct gdbarch *gdbarch, CORE_ADDR addr, struct target_ops *targ)
int no_op_reg_to_regnum (struct gdbarch *gdbarch, int reg)
void default_elf_make_msymbol_special (asymbol *sym, struct minimal_symbol *msym)
void default_coff_make_msymbol_special (int val, struct minimal_symbol *msym)
int cannot_register_not (struct gdbarch *gdbarch, int regnum)
void legacy_virtual_frame_pointer (struct gdbarch *gdbarch, CORE_ADDR pc, int *frame_regnum, LONGEST *frame_offset)
int generic_convert_register_p (struct gdbarch *gdbarch, int regnum, struct type *type)
int default_stabs_argument_has_addr (struct gdbarch *gdbarch, struct type *type)
int generic_instruction_nullified (struct gdbarch *gdbarch, struct regcache *regcache)
int default_remote_register_number (struct gdbarch *gdbarch, int regno)
enum bfd_endian selected_byte_order (void)
static void show_endian (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static void set_endian (char *ignore_args, int from_tty, struct cmd_list_element *c)
static struct bfd_arch_info * choose_architecture_for_target (const struct target_desc *target_desc, const struct bfd_arch_info *selected)
const char * selected_architecture_name (void)
static void show_architecture (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static void set_architecture (char *ignore_args, int from_tty, struct cmd_list_element *c)
int gdbarch_update_p (struct gdbarch_info info)
struct gdbarch * gdbarch_from_bfd (bfd *abfd)
void set_gdbarch_from_file (bfd *abfd)
void initialize_current_architecture (void)
void gdbarch_info_init (struct gdbarch_info *info)
void gdbarch_info_fill (struct gdbarch_info *info)
struct gdbarch * get_current_arch (void)
int default_has_shared_address_space (struct gdbarch *gdbarch)
int default_fast_tracepoint_valid_at (struct gdbarch *gdbarch, CORE_ADDR addr, int *isize, char **msg)
void default_remote_breakpoint_from_pc (struct gdbarch *gdbarch, CORE_ADDR *pcptr, int *kindptr)
void default_gen_return_address (struct gdbarch *gdbarch, struct agent_expr *ax, struct axs_value *value, CORE_ADDR scope)
int default_return_in_first_hidden_param_p (struct gdbarch *gdbarch, struct type *type)
void _initialize_gdbarch_utils (void)
Variables
static int target_byte_order_user = BFD_ENDIAN_UNKNOWN
static const char endian_big [] = "big"
static const char endian_little [] = "little"
static const char endian_auto [] = "auto"
static const char *const endian_enum []
static const char * set_endian_string
static struct bfd_arch_info * target_architecture_user
static const char * set_architecture_string
static const bfd_arch_info_type * default_bfd_arch
static const bfd_target * default_bfd_vec
static int default_byte_order = BFD_ENDIAN_UNKNOWN
initialize_file_ftype _initialize_gdbarch_utils
Enumeration Type Documentation
enum set_arch
Enumerator:
set_arch_auto
set_arch_manual
Definition at line 415 of file arch-utils.c.
Function Documentation
void _initialize_gdbarch_utils (void)
Definition at line 813 of file arch-utils.c.
References _, _initialize_gdbarch_utils, add_setshow_enum_cmd(), class_support, endian_enum, set_endian(), set_endian_string, setlist, show_endian(), and showlist.
int cannot_register_not (struct gdbarch * gdbarch, int regnum)
Definition at line 183 of file arch-utils.c.
Referenced by gdbarch_alloc().
static struct bfd_arch_info* choose_architecture_for_target (const struct target_desc * target_desc, const struct bfd_arch_info * selected) [static, read]
Definition at line 344 of file arch-utils.c.
References _, tdesc_architecture(), tdesc_compatible_p(), and warning().
Referenced by gdbarch_info_fill().
CORE_ADDR convert_from_func_ptr_addr_identity (struct gdbarch * gdbarch, CORE_ADDR addr, struct target_ops * targ)
Definition at line 158 of file arch-utils.c.
References convert_from_func_ptr_addr_identity.
int core_addr_greaterthan (CORE_ADDR lhs, CORE_ADDR rhs)
Definition at line 144 of file arch-utils.c.
Referenced by hppa_gdbarch_init(), and xstormy16_gdbarch_init().
CORE_ADDR core_addr_identity (struct gdbarch * gdbarch, CORE_ADDR addr)
Definition at line 152 of file arch-utils.c.
Referenced by gdbarch_alloc().
int core_addr_lessthan (CORE_ADDR lhs, CORE_ADDR rhs)
Definition at line 138 of file arch-utils.c.
Referenced by aarch64_gdbarch_init(), alpha_gdbarch_init(), arm_gdbarch_init(), avr_gdbarch_init(), bfin_gdbarch_init(), cris_gdbarch_init(), frv_gdbarch_init(), h8300_gdbarch_init(), i386_gdbarch_init(), ia64_gdbarch_init(), iq2000_gdbarch_init(), lm32_gdbarch_init(), m32c_gdbarch_init(), m32r_gdbarch_init(), m68hc11_gdbarch_init(), m68k_gdbarch_init(), m88k_gdbarch_init(), mep_gdbarch_init(), microblaze_gdbarch_init(), mips_gdbarch_init(), mn10300_gdbarch_init(), moxie_gdbarch_init(), msp430_gdbarch_init(), mt_gdbarch_init(), nios2_gdbarch_init(), rl78_gdbarch_init(), rs6000_gdbarch_init(), rx_gdbarch_init(), s390_gdbarch_init(), score_gdbarch_init(), sh64_gdbarch_init(), sh_gdbarch_init(), sparc32_gdbarch_init(), spu_gdbarch_init(), tic6x_gdbarch_init(), tilegx_gdbarch_init(), v850_gdbarch_init(), vax_gdbarch_init(), and xtensa_gdbarch_init().
void default_coff_make_msymbol_special (int val, struct minimal_symbol * msym)
Definition at line 177 of file arch-utils.c.
Referenced by gdbarch_alloc().
int default_displaced_step_hw_singlestep (struct gdbarch * gdbarch, struct displaced_step_closure * closure)
Definition at line 71 of file arch-utils.c.
References gdbarch_software_single_step_p().
Referenced by gdbarch_alloc().
void default_elf_make_msymbol_special (asymbol * sym, struct minimal_symbol * msym)
Definition at line 171 of file arch-utils.c.
Referenced by gdbarch_alloc().
int default_fast_tracepoint_valid_at (struct gdbarch * gdbarch, CORE_ADDR addr, int * isize, char ** msg)
Definition at line 772 of file arch-utils.c.
Referenced by gdbarch_alloc().
void default_gen_return_address (struct gdbarch * gdbarch, struct agent_expr * ax, struct axs_value * value, CORE_ADDR scope)
Definition at line 790 of file arch-utils.c.
References _, and error().
Referenced by gdbarch_alloc().
int default_has_shared_address_space (struct gdbarch * gdbarch)
Definition at line 764 of file arch-utils.c.
Referenced by gdbarch_alloc().
void default_remote_breakpoint_from_pc (struct gdbarch * gdbarch, CORE_ADDR * pcptr, int * kindptr)
Definition at line 783 of file arch-utils.c.
References gdbarch_breakpoint_from_pc().
Referenced by gdbarch_alloc().
int default_remote_register_number (struct gdbarch * gdbarch, int regno)
Definition at line 241 of file arch-utils.c.
Referenced by gdbarch_alloc().
int default_return_in_first_hidden_param_p (struct gdbarch * gdbarch, struct type * type)
Definition at line 798 of file arch-utils.c.
References language_pass_by_reference().
Referenced by gdbarch_alloc().
int default_stabs_argument_has_addr (struct gdbarch * gdbarch, struct type * type)
Definition at line 228 of file arch-utils.c.
Referenced by gdbarch_alloc(), and sparc64_init_abi().
CORE_ADDR displaced_step_at_entry_point (struct gdbarch * gdbarch)
Definition at line 78 of file arch-utils.c.
References entry_point_address(), and gdbarch_breakpoint_from_pc().
Referenced by amd64_linux_init_abi_common(), arm_linux_init_abi(), i386_linux_init_abi(), rs6000_gdbarch_init(), and s390_gdbarch_init().
struct gdbarch* gdbarch_from_bfd (bfd * abfd) [read]
Definition at line 534 of file arch-utils.c.
References gdbarch_info::abfd, gdbarch_find_by_info(), and gdbarch_info_init().
Referenced by core_open(), get_objfile_bfd_data(), linux_core_info_proc_mappings(), print_bfd_section_info(), print_objfile_section_info(), and print_section_info().
void gdbarch_info_fill (struct gdbarch_info * info)
Definition at line 695 of file arch-utils.c.
References gdbarch_info::abfd, gdbarch_info::bfd_arch_info, gdbarch_info::byte_order, gdbarch_info::byte_order_for_code, choose_architecture_for_target(), default_bfd_arch, default_byte_order, gdb_assert, GDB_OSABI_DEFAULT, GDB_OSABI_UNINITIALIZED, GDB_OSABI_UNKNOWN, gdbarch_lookup_osabi(), gdbarch_info::osabi, target_architecture_user, target_byte_order_user, gdbarch_info::target_desc, and tdesc_osabi().
Referenced by darwin_check_osabi(), and gdbarch_find_by_info().
void gdbarch_info_init (struct gdbarch_info * info)
Definition at line 682 of file arch-utils.c.
References gdbarch_info::byte_order, gdbarch_info::byte_order_for_code, GDB_OSABI_UNINITIALIZED, memset(), and gdbarch_info::osabi.
Referenced by add_inferior_with_spaces(), arm_update_current_architecture(), darwin_check_osabi(), gdbarch_from_bfd(), initialize_current_architecture(), mips_abi_update(), powerpc_set_soft_float(), powerpc_set_vector_abi(), ppu2spu_sniffer(), rs6000_create_inferior(), set_architecture(), set_cris_dwarf2_cfi(), set_cris_mode(), set_cris_version(), set_endian(), set_gdbarch_from_file(), set_mips64_transfers_32bit_regs(), set_mipsfpu_double_command(), set_mipsfpu_none_command(), set_mipsfpu_single_command(), set_osabi(), spu_gdbarch(), target_clear_description(), and target_find_description().
int gdbarch_update_p (struct gdbarch_info info)
Definition at line 482 of file arch-utils.c.
References gdbarch_info::abfd, core_bfd, exec_bfd, fprintf_unfiltered(), gdb_stdlog, gdbarch_bfd_arch_info(), gdbarch_debug, gdbarch_find_by_info(), host_address_to_string(), set_target_gdbarch(), target_current_description(), gdbarch_info::target_desc, and target_gdbarch().
Referenced by arm_update_current_architecture(), darwin_check_osabi(), initialize_current_architecture(), mips_abi_update(), powerpc_set_soft_float(), powerpc_set_vector_abi(), rs6000_create_inferior(), set_architecture(), set_cris_dwarf2_cfi(), set_cris_mode(), set_cris_version(), set_endian(), set_mips64_transfers_32bit_regs(), set_mipsfpu_double_command(), set_mipsfpu_none_command(), set_mipsfpu_single_command(), set_osabi(), target_clear_description(), and target_find_description().
int generic_convert_register_p (struct gdbarch * gdbarch, int regnum, struct type * type)
Definition at line 221 of file arch-utils.c.
Referenced by gdbarch_alloc().
int generic_in_function_epilogue_p (struct gdbarch * gdbarch, CORE_ADDR pc)
Definition at line 130 of file arch-utils.c.
Referenced by gdbarch_alloc().
int generic_in_solib_return_trampoline (struct gdbarch * gdbarch, CORE_ADDR pc, const char * name)
Definition at line 123 of file arch-utils.c.
Referenced by gdbarch_alloc().
int generic_instruction_nullified (struct gdbarch * gdbarch, struct regcache * regcache)
Definition at line 234 of file arch-utils.c.
CORE_ADDR generic_skip_solib_resolver (struct gdbarch * gdbarch, CORE_ADDR pc)
Definition at line 117 of file arch-utils.c.
Referenced by gdbarch_alloc().
CORE_ADDR generic_skip_trampoline_code (struct frame_info * frame, CORE_ADDR pc)
Definition at line 111 of file arch-utils.c.
Referenced by gdbarch_alloc().
struct gdbarch* get_current_arch (void) [read]
Definition at line 755 of file arch-utils.c.
References get_frame_arch(), get_selected_frame(), has_stack_frames(), and target_gdbarch().
Referenced by add_solib_catchpoint(), add_symbol_file_command(), agent_eval_command_one(), bpfinishpy_detect_out_scope_cb(), bpfinishpy_handle_stop(), break_command_1(), break_range_command(), catch_ada_exception_command(), catch_assert_command(), catch_exec_command_1(), catch_fork_command_1(), catch_syscall_command_1(), cmdpy_destroyer(), cmdpy_function(), core_info_proc(), create_signal_catchpoint(), create_syscall_event_catchpoint(), create_tracepoint_from_upload(), disassemble_command(), do_one_display(), do_set_command(), dprintf_command(), echo_command(), extract_display_start_addr(), find_command(), ftrace_command(), gdb_CA_to_TAS(), gdb_get_blocks(), gdb_regformat(), gdb_reggroup(), gdb_reggrouplist(), gdb_selected_block(), gdb_selected_frame(), gdb_set_bp(), gdb_update_mem(), gdbpy_breakpoint_has_py_cond(), gdbpy_should_stop(), gdbtk_load_asm(), get_register(), get_register_name(), get_register_size(), get_register_types(), get_set_value(), get_show_value(), handle_gnu_v3_exceptions(), hex2bin(), inferior_call_waitpid(), info_checkpoints_command(), info_probes_for_ops(), info_proc_cmd_1(), jump_command(), line_info(), maint_agent_printf_command(), maintenance_print_architecture(), maintenance_print_reggroups(), map_arg_registers(), merge_uploaded_tracepoints(), mi_cmd_break_insert_1(), mi_cmd_catch_assert(), mi_cmd_catch_exception(), mi_cmd_data_list_register_names(), mi_cmd_data_read_memory(), mi_cmd_data_read_memory_bytes(), mi_cmd_data_write_memory(), mi_cmd_disassemble(), msp430_gdbarch_init(), overlay_load_command(), parse_cmd_to_aexpr(), parse_exp_in_context_1(), py_free_pspace(), python_on_normal_stop(), record_full_restore(), register_changed_p(), set_charset_sfunc(), set_host_charset_sfunc(), set_target_charset_sfunc(), set_target_wide_charset_sfunc(), setup_architecture_data(), show_architecture(), show_convenience(), show_endian(), show_osabi(), show_target_charset_name(), show_target_wide_charset_name(), skip_function_command(), strace_command(), trace_command(), trace_find_line_command(), tui_get_begin_asm_address(), tui_reg_next_command(), and VEC().
void initialize_current_architecture (void)
Definition at line 583 of file arch-utils.c.
References _, add_alias_cmd(), add_setshow_enum_cmd(), gdbarch_info::bfd_arch_info, gdbarch_info::byte_order, gdbarch_info::byte_order_for_code, class_support, default_bfd_arch, default_bfd_vec, default_byte_order, gdbarch_info_init(), gdbarch_printable_names(), gdbarch_update_p(), internal_error(), set_architecture(), set_architecture_string, setlist, show_architecture(), showlist, strchr(), target_name, and xrealloc().
Referenced by gdb_init().
int legacy_register_sim_regno (struct gdbarch * gdbarch, int regnum)
Definition at line 95 of file arch-utils.c.
References gdb_assert, gdbarch_num_regs(), gdbarch_register_name(), LEGACY_SIM_REGNO_IGNORE, and regnum.
Referenced by gdbarch_alloc(), sh64_gdbarch_init(), sh_dsp_register_sim_regno(), sh_gdbarch_init(), and sh_sh2a_register_sim_regno().
void legacy_virtual_frame_pointer (struct gdbarch * gdbarch, CORE_ADDR pc, int * frame_regnum, LONGEST * frame_offset)
Definition at line 193 of file arch-utils.c.
References _, gdbarch_deprecated_fp_regnum(), gdbarch_num_regs(), gdbarch_sp_regnum(), internal_error(), and legacy_virtual_frame_pointer.
int no_op_reg_to_regnum (struct gdbarch * gdbarch, int reg)
Definition at line 165 of file arch-utils.c.
Referenced by gdbarch_alloc().
const char* selected_architecture_name (void)
Definition at line 422 of file arch-utils.c.
References set_architecture_string, and target_architecture_user.
Referenced by gdbsim_open().
enum bfd_endian selected_byte_order (void)
Definition at line 265 of file arch-utils.c.
References target_byte_order_user.
Referenced by gdbsim_open().
static void set_architecture (char * ignore_args, int from_tty, struct cmd_list_element * c) [static]
Definition at line 451 of file arch-utils.c.
References _, gdbarch_info::bfd_arch_info, gdb_stdout, gdbarch_info_init(), gdbarch_update_p(), internal_error(), printf_unfiltered(), set_architecture_string, show_architecture(), and target_architecture_user.
Referenced by initialize_current_architecture().
static void set_endian (char * ignore_args, int from_tty, struct cmd_list_element * c) [static]
Definition at line 293 of file arch-utils.c.
References _, gdbarch_info::byte_order, endian_auto, endian_big, endian_little, gdb_stdout, gdbarch_info_init(), gdbarch_update_p(), internal_error(), printf_unfiltered(), set_endian_string, show_endian(), and target_byte_order_user.
Referenced by _initialize_gdbarch_utils().
void set_gdbarch_from_file (bfd * abfd)
Definition at line 547 of file arch-utils.c.
References _, gdbarch_info::abfd, error(), gdbarch_find_by_info(), gdbarch_info_init(), set_target_gdbarch(), target_current_description(), and gdbarch_info::target_desc.
Referenced by core_open(), and exec_file_attach().
static void show_architecture (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 434 of file arch-utils.c.
References _, fprintf_filtered(), gdbarch_bfd_arch_info(), get_current_arch(), set_architecture_string, and target_architecture_user.
Referenced by initialize_current_architecture(), and set_architecture().
static void show_endian (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 273 of file arch-utils.c.
References _, fprintf_unfiltered(), gdbarch_byte_order(), get_current_arch(), and target_byte_order_user.
Referenced by _initialize_gdbarch_utils(), and set_endian().
struct displaced_step_closure* simple_displaced_step_copy_insn (struct gdbarch * gdbarch, CORE_ADDR from, CORE_ADDR to, struct regcache * regs) [read]
Definition at line 42 of file arch-utils.c.
References debug_displaced, displaced_step_dump_bytes(), fprintf_unfiltered(), gdb_stdlog, gdbarch_max_insn_length(), len, paddress(), read_memory(), write_memory(), and xmalloc().
Referenced by rs6000_gdbarch_init(), and s390_gdbarch_init().
void simple_displaced_step_free_closure (struct gdbarch * gdbarch, struct displaced_step_closure * closure)
Definition at line 64 of file arch-utils.c.
References xfree().
Referenced by amd64_linux_init_abi_common(), arm_linux_init_abi(), i386_linux_init_abi(), rs6000_gdbarch_init(), and s390_gdbarch_init().
Variable Documentation
initialize_file_ftype _initialize_gdbarch_utils
Referenced by _initialize_gdbarch_utils(), and initialize_all_files().
const bfd_arch_info_type* default_bfd_arch [static]
Definition at line 570 of file arch-utils.c.
Referenced by gdbarch_info_fill(), and initialize_current_architecture().
const bfd_target* default_bfd_vec [static]
Definition at line 577 of file arch-utils.c.
Referenced by initialize_current_architecture().
int default_byte_order = BFD_ENDIAN_UNKNOWN [static]
Definition at line 580 of file arch-utils.c.
Referenced by gdbarch_info_fill(), and initialize_current_architecture().
const char endian_auto[] = "auto" [static]
Definition at line 254 of file arch-utils.c.
Referenced by set_endian().
const char endian_big[] = "big" [static]
Definition at line 252 of file arch-utils.c.
Referenced by set_endian().
const char* const endian_enum[] [static]
Initial value:
{
  endian_big,
  endian_little,
  endian_auto,
  NULL,
}
Definition at line 255 of file arch-utils.c.
Referenced by _initialize_gdbarch_utils().
const char endian_little[] = "little" [static]
Definition at line 253 of file arch-utils.c.
Referenced by set_endian().
const char* set_architecture_string [static]
Definition at line 419 of file arch-utils.c.
Referenced by initialize_current_architecture(), selected_architecture_name(), set_architecture(), and show_architecture().
const char* set_endian_string [static]
Definition at line 262 of file arch-utils.c.
Referenced by _initialize_gdbarch_utils(), and set_endian().
struct bfd_arch_info* target_architecture_user [static]
Definition at line 417 of file arch-utils.c.
Referenced by gdbarch_info_fill(), selected_architecture_name(), set_architecture(), and show_architecture().
int target_byte_order_user = BFD_ENDIAN_UNKNOWN [static]
Definition at line 250 of file arch-utils.c.
Referenced by gdbarch_info_fill(), selected_byte_order(), set_endian(), and show_endian().