GDB (xrefs): /home/stan/gdb/src/gdb/features/arm-with-vfpv2.c File Reference
/home/stan/gdb/src/gdb/features/arm-with-vfpv2.c File Reference
#include "defs.h"
#include "osabi.h"
#include "target-descriptions.h"
Functions
static void initialize_tdesc_arm_with_vfpv2 (void)
Variables
struct target_desc * tdesc_arm_with_vfpv2
Function Documentation
static void initialize_tdesc_arm_with_vfpv2 (void) [static]
Definition at line 10 of file arm-with-vfpv2.c.
References allocate_target_description(), tdesc_create_feature(), and tdesc_create_reg().
Referenced by _initialize_arm_tdep().
Variable Documentation
struct target_desc* tdesc_arm_with_vfpv2
Definition at line 8 of file arm-with-vfpv2.c.
Referenced by arm_linux_core_read_description(), and arm_linux_read_description().