GDB (xrefs): /home/stan/gdb/src/gdb/arm-linux-tdep.c File Reference
/home/stan/gdb/src/gdb/arm-linux-tdep.c File Reference
#include "defs.h"
#include "target.h"
#include "value.h"
#include "gdbtypes.h"
#include "floatformat.h"
#include "gdbcore.h"
#include "frame.h"
#include "regcache.h"
#include "doublest.h"
#include "solib-svr4.h"
#include "osabi.h"
#include "regset.h"
#include "trad-frame.h"
#include "tramp-frame.h"
#include "breakpoint.h"
#include "auxv.h"
#include "xml-syscall.h"
#include "arm-tdep.h"
#include "arm-linux-tdep.h"
#include "linux-tdep.h"
#include "glibc-tdep.h"
#include "arch-utils.h"
#include "inferior.h"
#include "gdbthread.h"
#include "symfile.h"
#include "cli/cli-utils.h"
#include "stap-probe.h"
#include "parser-defs.h"
#include "user-regs.h"
#include <ctype.h>
#include "elf/common.h"
#include "gdb_string.h"
Defines
#define ARM_LINUX_JB_ELEMENT_SIZE INT_REGISTER_SIZE
#define ARM_LINUX_JB_PC_FPA 21
#define ARM_LINUX_JB_PC_EABI 9
#define ARM_LINUX_SIGRETURN_INSTR 0xef900077
#define ARM_LINUX_RT_SIGRETURN_INSTR 0xef9000ad
#define ARM_SET_R7_SIGRETURN 0xe3a07077
#define ARM_SET_R7_RT_SIGRETURN 0xe3a070ad
#define ARM_EABI_SYSCALL 0xef000000
#define ARM_OABI_SYSCALL_RESTART_SYSCALL 0xef900000
#define ARM_LDR_PC_SP_12 0xe49df00c
#define ARM_LDR_PC_SP_4 0xe49df004
#define ARM_SIGCONTEXT_R0 0xc
#define ARM_UCONTEXT_SIGCONTEXT 0x14
#define ARM_OLD_RT_SIGFRAME_SIGINFO 0x8
#define ARM_OLD_RT_SIGFRAME_UCONTEXT 0x88
#define ARM_NEW_RT_SIGFRAME_UCONTEXT 0x80
#define ARM_NEW_SIGFRAME_MAGIC 0x5ac3c35a
#define ARM_LINUX_SIZEOF_GREGSET (18 * INT_REGISTER_SIZE)
#define typeNone 0x00
#define typeSingle 0x01
#define typeDouble 0x02
#define typeExtended 0x03
#define ARM_LINUX_SIZEOF_VFP (32 * 8 + 4)
Functions
static void arm_linux_sigtramp_cache (struct frame_info *this_frame, struct trad_frame_cache *this_cache, CORE_ADDR func, int regs_offset)
static void arm_linux_sigreturn_init (const struct tramp_frame *self, struct frame_info *this_frame, struct trad_frame_cache *this_cache, CORE_ADDR func)
static void arm_linux_rt_sigreturn_init (const struct tramp_frame *self, struct frame_info *this_frame, struct trad_frame_cache *this_cache, CORE_ADDR func)
static void arm_linux_restart_syscall_init (const struct tramp_frame *self, struct frame_info *this_frame, struct trad_frame_cache *this_cache, CORE_ADDR func)
void arm_linux_supply_gregset (const struct regset *regset, struct regcache *regcache, int regnum, const void *gregs_buf, size_t len)
void arm_linux_collect_gregset (const struct regset *regset, const struct regcache *regcache, int regnum, void *gregs_buf, size_t len)
void supply_nwfpe_register (struct regcache *regcache, int regno, const gdb_byte *regs)
void collect_nwfpe_register (const struct regcache *regcache, int regno, gdb_byte *regs)
void arm_linux_supply_nwfpe (const struct regset *regset, struct regcache *regcache, int regnum, const void *regs_buf, size_t len)
void arm_linux_collect_nwfpe (const struct regset *regset, const struct regcache *regcache, int regnum, void *regs_buf, size_t len)
static void arm_linux_supply_vfp (const struct regset *regset, struct regcache *regcache, int regnum, const void *regs_buf, size_t len)
static void arm_linux_collect_vfp (const struct regset *regset, const struct regcache *regcache, int regnum, void *regs_buf, size_t len)
static struct regset * arm_linux_regset_from_core_section (struct gdbarch *gdbarch, const char *sect_name, size_t sect_size)
static struct target_desc * arm_linux_core_read_description (struct gdbarch *gdbarch, struct target_ops *target, bfd *abfd)
static int arm_linux_sigreturn_return_addr (struct frame_info *frame, unsigned long svc_number, CORE_ADDR *pc, int *is_thumb)
static LONGEST arm_linux_get_syscall_number (struct gdbarch *gdbarch, ptid_t ptid)
static CORE_ADDR arm_linux_syscall_next_pc (struct frame_info *frame)
static int arm_linux_software_single_step (struct frame_info *frame)
static void arm_linux_cleanup_svc (struct gdbarch *gdbarch, struct regcache *regs, struct displaced_step_closure *dsc)
static int arm_linux_copy_svc (struct gdbarch *gdbarch, struct regcache *regs, struct displaced_step_closure *dsc)
static void cleanup_kernel_helper_return (struct gdbarch *gdbarch, struct regcache *regs, struct displaced_step_closure *dsc)
static void arm_catch_kernel_helper_return (struct gdbarch *gdbarch, CORE_ADDR from, CORE_ADDR to, struct regcache *regs, struct displaced_step_closure *dsc)
static struct
displaced_step_closure * arm_linux_displaced_step_copy_insn (struct gdbarch *gdbarch, CORE_ADDR from, CORE_ADDR to, struct regcache *regs)
static int arm_stap_is_single_operand (struct gdbarch *gdbarch, const char *s)
static int arm_stap_parse_special_token (struct gdbarch *gdbarch, struct stap_parse_info *p)
static void arm_linux_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
void _initialize_arm_linux_tdep (void)
Variables
int arm_apcs_32
static const gdb_byte arm_linux_arm_le_breakpoint [] = { 0x01, 0x00, 0x9f, 0xef }
static const gdb_byte arm_linux_arm_be_breakpoint [] = { 0xef, 0x9f, 0x00, 0x01 }
static const gdb_byte eabi_linux_arm_le_breakpoint [] = { 0xf0, 0x01, 0xf0, 0xe7 }
static const gdb_byte eabi_linux_arm_be_breakpoint [] = { 0xe7, 0xf0, 0x01, 0xf0 }
static const gdb_byte arm_linux_thumb_be_breakpoint [] = {0xde, 0x01}
static const gdb_byte arm_linux_thumb_le_breakpoint [] = {0x01, 0xde}
static const gdb_byte arm_linux_thumb2_be_breakpoint [] = { 0xf7, 0xf0, 0xa0, 0x00 }
static const gdb_byte arm_linux_thumb2_le_breakpoint [] = { 0xf0, 0xf7, 0x00, 0xa0 }
static struct tramp_frame arm_linux_sigreturn_tramp_frame
static struct tramp_frame arm_linux_rt_sigreturn_tramp_frame
static struct tramp_frame arm_eabi_linux_sigreturn_tramp_frame
static struct tramp_frame arm_eabi_linux_rt_sigreturn_tramp_frame
static struct tramp_frame arm_linux_restart_syscall_tramp_frame
static struct tramp_frame arm_kernel_linux_restart_syscall_tramp_frame
static struct core_regset_section arm_linux_fpa_regset_sections []
static struct core_regset_section arm_linux_vfp_regset_sections []
initialize_file_ftype _initialize_arm_linux_tdep
Define Documentation
#define ARM_EABI_SYSCALL 0xef000000
Definition at line 243 of file arm-linux-tdep.c.
#define ARM_LDR_PC_SP_12 0xe49df00c
Definition at line 248 of file arm-linux-tdep.c.
#define ARM_LDR_PC_SP_4 0xe49df004
Definition at line 249 of file arm-linux-tdep.c.
Referenced by arm_linux_restart_syscall_init().
#define ARM_LINUX_JB_ELEMENT_SIZE INT_REGISTER_SIZE
Definition at line 103 of file arm-linux-tdep.c.
Referenced by arm_linux_init_abi().
#define ARM_LINUX_JB_PC_EABI 9
Definition at line 105 of file arm-linux-tdep.c.
Referenced by arm_linux_init_abi().
#define ARM_LINUX_JB_PC_FPA 21
Definition at line 104 of file arm-linux-tdep.c.
Referenced by arm_linux_init_abi().
#define ARM_LINUX_RT_SIGRETURN_INSTR 0xef9000ad
Definition at line 235 of file arm-linux-tdep.c.
#define ARM_LINUX_SIGRETURN_INSTR 0xef900077
Definition at line 234 of file arm-linux-tdep.c.
#define ARM_LINUX_SIZEOF_GREGSET (18 * INT_REGISTER_SIZE)
Definition at line 467 of file arm-linux-tdep.c.
Referenced by arm_linux_regset_from_core_section().
#define ARM_LINUX_SIZEOF_VFP (32 * 8 + 4)
Definition at line 650 of file arm-linux-tdep.c.
Referenced by arm_linux_regset_from_core_section().
#define ARM_NEW_RT_SIGFRAME_UCONTEXT 0x80
Definition at line 313 of file arm-linux-tdep.c.
Referenced by arm_linux_rt_sigreturn_init().
#define ARM_NEW_SIGFRAME_MAGIC 0x5ac3c35a
Definition at line 315 of file arm-linux-tdep.c.
Referenced by arm_linux_sigreturn_init().
#define ARM_OABI_SYSCALL_RESTART_SYSCALL 0xef900000
Definition at line 247 of file arm-linux-tdep.c.
#define ARM_OLD_RT_SIGFRAME_SIGINFO 0x8
Definition at line 310 of file arm-linux-tdep.c.
Referenced by arm_linux_rt_sigreturn_init().
#define ARM_OLD_RT_SIGFRAME_UCONTEXT 0x88
Definition at line 311 of file arm-linux-tdep.c.
Referenced by arm_linux_rt_sigreturn_init().
#define ARM_SET_R7_RT_SIGRETURN 0xe3a070ad
Definition at line 242 of file arm-linux-tdep.c.
#define ARM_SET_R7_SIGRETURN 0xe3a07077
Definition at line 241 of file arm-linux-tdep.c.
#define ARM_SIGCONTEXT_R0 0xc
Definition at line 300 of file arm-linux-tdep.c.
Referenced by arm_linux_rt_sigreturn_init(), and arm_linux_sigreturn_init().
#define ARM_UCONTEXT_SIGCONTEXT 0x14
Definition at line 304 of file arm-linux-tdep.c.
Referenced by arm_linux_rt_sigreturn_init(), and arm_linux_sigreturn_init().
#define typeDouble 0x02
Definition at line 539 of file arm-linux-tdep.c.
Referenced by collect_nwfpe_register(), and supply_nwfpe_register().
#define typeExtended 0x03
Definition at line 540 of file arm-linux-tdep.c.
Referenced by collect_nwfpe_register(), and supply_nwfpe_register().
#define typeNone 0x00
Definition at line 537 of file arm-linux-tdep.c.
#define typeSingle 0x01
Definition at line 538 of file arm-linux-tdep.c.
Referenced by collect_nwfpe_register(), and supply_nwfpe_register().
Function Documentation
void _initialize_arm_linux_tdep (void)
Definition at line 1360 of file arm-linux-tdep.c.
References _initialize_arm_linux_tdep, arm_linux_init_abi(), GDB_OSABI_LINUX, and gdbarch_register_osabi().
static void arm_catch_kernel_helper_return (struct gdbarch * gdbarch, CORE_ADDR from, CORE_ADDR to, struct regcache * regs, struct displaced_step_closure * dsc) [static]
Definition at line 1053 of file arm-linux-tdep.c.
References ARM_LR_REGNUM, CANNOT_WRITE_PC, displaced_step_closure::cleanup, cleanup_kernel_helper_return(), displaced_read_reg(), displaced_write_reg(), from, gdbarch_byte_order(), displaced_step_closure::insn_addr, displaced_step_closure::modinsn, displaced_step_closure::numinsns, displaced_step_closure::tmp, ULONGEST, write_memory_unsigned_integer(), and displaced_step_closure::wrote_to_pc.
Referenced by arm_linux_displaced_step_copy_insn().
static void arm_linux_cleanup_svc (struct gdbarch * gdbarch, struct regcache * regs, struct displaced_step_closure * dsc) [static]
Definition at line 925 of file arm-linux-tdep.c.
References ARM_PC_REGNUM, BRANCH_WRITE_PC, debug_displaced, DISPLACED_MODIFIED_INSNS, displaced_write_reg(), fprintf_unfiltered(), from, gdb_stdlog, displaced_step_closure::insn_addr, regcache_cooked_read_unsigned(), displaced_step_closure::scratch_base, and ULONGEST.
Referenced by arm_linux_copy_svc().
void arm_linux_collect_gregset (const struct regset * regset, const struct regcache * regcache, int regnum, void * gregs_buf, size_t len)
Definition at line 508 of file arm-linux-tdep.c.
References ARM_A1_REGNUM, arm_apcs_32, ARM_CPSR_GREGNUM, ARM_PC_REGNUM, ARM_PS_REGNUM, INT_REGISTER_SIZE, and regcache_raw_collect().
Referenced by arm_linux_regset_from_core_section(), and fill_gregset().
void arm_linux_collect_nwfpe (const struct regset * regset, const struct regcache * regcache, int regnum, void * regs_buf, size_t len)
Definition at line 632 of file arm-linux-tdep.c.
References ARM_F0_REGNUM, ARM_F7_REGNUM, ARM_FPS_REGNUM, collect_nwfpe_register(), INT_REGISTER_SIZE, and regcache_raw_collect().
Referenced by arm_linux_regset_from_core_section(), and fill_fpregset().
static void arm_linux_collect_vfp (const struct regset * regset, const struct regcache * regcache, int regnum, void * regs_buf, size_t len) [static]
Definition at line 670 of file arm-linux-tdep.c.
References ARM_D0_REGNUM, ARM_D31_REGNUM, ARM_FPSCR_REGNUM, and regcache_raw_collect().
Referenced by arm_linux_regset_from_core_section().
static int arm_linux_copy_svc (struct gdbarch * gdbarch, struct regcache * regs, struct displaced_step_closure * dsc) [static]
Definition at line 954 of file arm-linux-tdep.c.
References arm_linux_cleanup_svc(), arm_linux_sigreturn_return_addr(), bp_step_resume, displaced_step_closure::cleanup, thread_info::control, debug_displaced, displaced_read_reg(), symtab_and_line::explicit_pc, find_pc_line(), find_pc_overlay(), fprintf_unfiltered(), gdb_assert, gdb_stderr, gdb_stdlog, get_current_frame(), get_frame_id(), get_frame_pc(), get_prev_frame(), inferior_thread(), insert_breakpoints(), symtab_and_line::pc, symtab_and_line::section, set_momentary_breakpoint(), thread_control_state::step_resume_breakpoint, and displaced_step_closure::wrote_to_pc.
Referenced by arm_linux_displaced_step_copy_insn().
static struct target_desc* arm_linux_core_read_description (struct gdbarch * gdbarch, struct target_ops * target, bfd * abfd) [static, read]
Definition at line 744 of file arm-linux-tdep.c.
References HWCAP_NEON, HWCAP_VFP, HWCAP_VFPv3, HWCAP_VFPv3D16, target_auxv_search(), tdesc_arm_with_neon, tdesc_arm_with_vfpv2, and tdesc_arm_with_vfpv3.
Referenced by arm_linux_init_abi().
static struct displaced_step_closure* arm_linux_displaced_step_copy_insn (struct gdbarch * gdbarch, CORE_ADDR from, CORE_ADDR to, struct regcache * regs) [static, read]
Definition at line 1086 of file arm-linux-tdep.c.
References arm_catch_kernel_helper_return(), arm_displaced_init_closure(), arm_linux_copy_svc(), arm_process_displaced_insn(), debug_displaced, fprintf_unfiltered(), gdb_stdlog, displaced_step_closure::svc, displaced_step_closure::u, and xmalloc().
Referenced by arm_linux_init_abi().
static LONGEST arm_linux_get_syscall_number (struct gdbarch * gdbarch, ptid_t ptid) [static]
Definition at line 801 of file arm-linux-tdep.c.
References ARM_PC_REGNUM, ARM_PS_REGNUM, arm_psr_thumb_bit(), gdbarch_byte_order_for_code(), gdbarch_tdep(), get_thread_regcache(), gdbarch_tdep::pc, read_memory_unsigned_integer(), regcache_cooked_read_unsigned(), and ULONGEST.
Referenced by arm_linux_init_abi().
static void arm_linux_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch) [static]
Definition at line 1235 of file arm-linux-tdep.c.
References _, gdbarch_tdep::arm_abi, ARM_ABI_AAPCS, gdbarch_tdep::arm_breakpoint, gdbarch_tdep::arm_breakpoint_size, arm_displaced_step_fixup(), ARM_FLOAT_AUTO, ARM_FLOAT_FPA, ARM_FLOAT_SOFT_FPA, ARM_FLOAT_SOFT_VFP, ARM_FLOAT_VFP, arm_linux_arm_be_breakpoint, arm_linux_arm_le_breakpoint, arm_linux_core_read_description(), arm_linux_displaced_step_copy_insn(), arm_linux_get_syscall_number(), ARM_LINUX_JB_ELEMENT_SIZE, ARM_LINUX_JB_PC_EABI, ARM_LINUX_JB_PC_FPA, arm_linux_regset_from_core_section(), arm_linux_software_single_step(), arm_linux_syscall_next_pc(), arm_linux_thumb2_be_breakpoint, arm_linux_thumb2_le_breakpoint, arm_linux_thumb_be_breakpoint, arm_linux_thumb_le_breakpoint, arm_process_record(), arm_stap_is_single_operand(), arm_stap_parse_special_token(), gdbarch_tdep::arm_swi_record, gdbarch_info::byte_order, displaced_step_at_entry_point(), eabi_linux_arm_be_breakpoint, eabi_linux_arm_le_breakpoint, find_solib_trampoline_target(), gdbarch_tdep::fp_model, gdbarch_tdep(), glibc_skip_solib_resolver(), gdbarch_tdep::have_fpa_registers, gdbarch_tdep::have_vfp_registers, internal_error(), gdbarch_tdep::jb_elt_size, gdbarch_tdep::jb_pc, linux_get_siginfo_type(), linux_init_abi(), gdbarch_tdep::lowest_pc, set_gdbarch_core_read_description(), set_gdbarch_core_regset_sections(), set_gdbarch_displaced_step_copy_insn(), set_gdbarch_displaced_step_fixup(), set_gdbarch_displaced_step_free_closure(), set_gdbarch_displaced_step_location(), set_gdbarch_fetch_tls_load_module_address(), set_gdbarch_get_siginfo_type(), set_gdbarch_get_syscall_number(), set_gdbarch_process_record(), set_gdbarch_regset_from_core_section(), set_gdbarch_skip_solib_resolver(), set_gdbarch_skip_trampoline_code(), set_gdbarch_software_single_step(), set_gdbarch_stap_gdb_register_prefix(), set_gdbarch_stap_integer_prefix(), set_gdbarch_stap_is_single_operand(), set_gdbarch_stap_parse_special_token(), set_gdbarch_stap_register_indirection_prefix(), set_gdbarch_stap_register_indirection_suffix(), set_gdbarch_stap_register_prefix(), set_solib_svr4_fetch_link_map_offsets(), set_xml_syscall_file_name(), simple_displaced_step_free_closure(), svr4_fetch_objfile_link_map(), svr4_ilp32_fetch_link_map_offsets(), gdbarch_tdep::syscall_next_pc, gdbarch_tdep::thumb2_breakpoint, gdbarch_tdep::thumb2_breakpoint_size, gdbarch_tdep::thumb_breakpoint, gdbarch_tdep::thumb_breakpoint_size, and tramp_frame_prepend_unwinder().
Referenced by _initialize_arm_linux_tdep().
static struct regset* arm_linux_regset_from_core_section (struct gdbarch * gdbarch, const char * sect_name, size_t sect_size) [static, read]
Definition at line 690 of file arm-linux-tdep.c.
References arm_linux_collect_gregset(), arm_linux_collect_nwfpe(), arm_linux_collect_vfp(), ARM_LINUX_SIZEOF_GREGSET, ARM_LINUX_SIZEOF_NWFPE, ARM_LINUX_SIZEOF_VFP, arm_linux_supply_gregset(), arm_linux_supply_nwfpe(), arm_linux_supply_vfp(), gdbarch_tdep::fpregset, gdbarch_tdep(), gdbarch_tdep::gregset, regset_alloc(), and gdbarch_tdep::vfpregset.
Referenced by arm_linux_init_abi().
static void arm_linux_restart_syscall_init (const struct tramp_frame * self, struct frame_info * this_frame, struct trad_frame_cache * this_cache, CORE_ADDR func) [static]
Definition at line 361 of file arm-linux-tdep.c.
References ARM_LDR_PC_SP_4, ARM_PC_REGNUM, ARM_PS_REGNUM, arm_psr_thumb_bit(), ARM_SP_REGNUM, frame_id_build(), gdbarch_addr_bits_remove(), get_frame_arch(), get_frame_memory_unsigned(), get_frame_register_unsigned(), sp, trad_frame_set_id(), trad_frame_set_reg_value(), and ULONGEST.
static void arm_linux_rt_sigreturn_init (const struct tramp_frame * self, struct frame_info * this_frame, struct trad_frame_cache * this_cache, CORE_ADDR func) [static]
Definition at line 338 of file arm-linux-tdep.c.
References arm_linux_sigtramp_cache(), ARM_NEW_RT_SIGFRAME_UCONTEXT, ARM_OLD_RT_SIGFRAME_SIGINFO, ARM_OLD_RT_SIGFRAME_UCONTEXT, ARM_SIGCONTEXT_R0, ARM_SP_REGNUM, ARM_UCONTEXT_SIGCONTEXT, gdbarch::byte_order, gdbarch_byte_order(), get_frame_arch(), get_frame_register_unsigned(), read_memory_unsigned_integer(), sp, and ULONGEST.
static void arm_linux_sigreturn_init (const struct tramp_frame * self, struct frame_info * this_frame, struct trad_frame_cache * this_cache, CORE_ADDR func) [static]
Definition at line 318 of file arm-linux-tdep.c.
References arm_linux_sigtramp_cache(), ARM_NEW_SIGFRAME_MAGIC, ARM_SIGCONTEXT_R0, ARM_SP_REGNUM, ARM_UCONTEXT_SIGCONTEXT, gdbarch::byte_order, gdbarch_byte_order(), get_frame_arch(), get_frame_register_unsigned(), read_memory_unsigned_integer(), sp, and ULONGEST.
static int arm_linux_sigreturn_return_addr (struct frame_info * frame, unsigned long svc_number, CORE_ADDR * pc, int * is_thumb) [static]
Definition at line 774 of file arm-linux-tdep.c.
References ARM_PS_REGNUM, arm_psr_thumb_bit(), frame_unwind_arch(), frame_unwind_caller_pc(), frame_unwind_register_unsigned(), get_frame_type(), SIGTRAMP_FRAME, and ULONGEST.
Referenced by arm_linux_copy_svc(), and arm_linux_syscall_next_pc().
static void arm_linux_sigtramp_cache (struct frame_info * this_frame, struct trad_frame_cache * this_cache, CORE_ADDR func, int regs_offset) [static]
Definition at line 252 of file arm-linux-tdep.c.
References ARM_PS_REGNUM, ARM_SP_REGNUM, frame_id_build(), get_frame_register_unsigned(), sp, trad_frame_set_id(), and trad_frame_set_reg_addr().
Referenced by arm_linux_rt_sigreturn_init(), and arm_linux_sigreturn_init().
static int arm_linux_software_single_step (struct frame_info * frame) [static]
Definition at line 898 of file arm-linux-tdep.c.
References arm_deal_with_atomic_sequence(), arm_get_next_pc(), arm_insert_single_step_breakpoint(), ARM_LR_REGNUM, get_frame_address_space(), get_frame_arch(), get_frame_pc(), and get_frame_register_unsigned().
Referenced by arm_linux_init_abi().
void arm_linux_supply_gregset (const struct regset * regset, struct regcache * regcache, int regnum, const void * gregs_buf, size_t len)
Definition at line 470 of file arm-linux-tdep.c.
References ARM_A1_REGNUM, arm_apcs_32, ARM_CPSR_GREGNUM, ARM_PC_REGNUM, ARM_PS_REGNUM, gdbarch::byte_order, extract_unsigned_integer(), gdbarch_addr_bits_remove(), gdbarch_byte_order(), get_regcache_arch(), INT_REGISTER_SIZE, regcache_raw_supply(), and store_unsigned_integer().
Referenced by arm_linux_regset_from_core_section(), and supply_gregset().
void arm_linux_supply_nwfpe (const struct regset * regset, struct regcache * regcache, int regnum, const void * regs_buf, size_t len)
Definition at line 615 of file arm-linux-tdep.c.
References ARM_F0_REGNUM, ARM_F7_REGNUM, ARM_FPS_REGNUM, NWFPE_FPSR_OFFSET, regcache_raw_supply(), and supply_nwfpe_register().
Referenced by arm_linux_regset_from_core_section(), and supply_fpregset().
static void arm_linux_supply_vfp (const struct regset * regset, struct regcache * regcache, int regnum, const void * regs_buf, size_t len) [static]
Definition at line 653 of file arm-linux-tdep.c.
References ARM_D0_REGNUM, ARM_D31_REGNUM, ARM_FPSCR_REGNUM, and regcache_raw_supply().
Referenced by arm_linux_regset_from_core_section().
static CORE_ADDR arm_linux_syscall_next_pc (struct frame_info * frame) [static]
Definition at line 852 of file arm-linux-tdep.c.
References arm_frame_is_thumb(), arm_linux_sigreturn_return_addr(), gdbarch::byte_order_for_code, gdbarch_byte_order_for_code(), get_frame_arch(), get_frame_pc(), get_frame_register_unsigned(), gdbarch_tdep::pc, read_memory_unsigned_integer(), and ULONGEST.
Referenced by arm_linux_init_abi().
static int arm_stap_is_single_operand (struct gdbarch * gdbarch, const char * s) [static]
Definition at line 1117 of file arm-linux-tdep.c.
Referenced by arm_linux_init_abi().
static int arm_stap_parse_special_token (struct gdbarch * gdbarch, struct stap_parse_info * p) [static]
Definition at line 1135 of file arm-linux-tdep.c.
References _, stap_parse_info::arg, stap_parse_info::arg_type, error(), len, stoken::length, lookup_pointer_type(), offset, stoken::ptr, stap_parse_info::saved_arg, skip_spaces_const(), displaced_step_closure::tmp, user_reg_map_name_to_regnum(), write_exp_elt_longcst(), write_exp_elt_opcode(), write_exp_elt_type(), and write_exp_string().
Referenced by arm_linux_init_abi().
static void cleanup_kernel_helper_return (struct gdbarch * gdbarch, struct regcache * regs, struct displaced_step_closure * dsc) [static]
Definition at line 1044 of file arm-linux-tdep.c.
References ARM_LR_REGNUM, ARM_PC_REGNUM, BRANCH_WRITE_PC, CANNOT_WRITE_PC, displaced_write_reg(), and displaced_step_closure::tmp.
Referenced by arm_catch_kernel_helper_return().
void collect_nwfpe_register (const struct regcache * regcache, int regno, gdb_byte * regs)
Definition at line 578 of file arm-linux-tdep.c.
References ARM_F0_REGNUM, FP_REGISTER_SIZE, memcpy(), NWFPE_TAGS_OFFSET, regcache_raw_collect(), typeDouble, typeExtended, and typeSingle.
Referenced by arm_linux_collect_nwfpe(), store_fpregister(), and store_fpregs().
void supply_nwfpe_register (struct regcache * regcache, int regno, const gdb_byte * regs)
Definition at line 543 of file arm-linux-tdep.c.
References ARM_F0_REGNUM, FP_REGISTER_SIZE, memcpy(), memset(), NWFPE_TAGS_OFFSET, regcache_raw_supply(), typeDouble, typeExtended, and typeSingle.
Referenced by arm_linux_supply_nwfpe(), fetch_fpregister(), and fetch_fpregs().
Variable Documentation
initialize_file_ftype _initialize_arm_linux_tdep
Referenced by _initialize_arm_linux_tdep(), and initialize_all_files().
int arm_apcs_32
Definition at line 279 of file arm-tdep.c.
struct tramp_frame arm_eabi_linux_rt_sigreturn_tramp_frame [static]
Initial value:
 {
  SIGTRAMP_FRAME,
  4,
  {
    { ARM_SET_R7_RT_SIGRETURN, -1 },
    { ARM_EABI_SYSCALL, -1 },
    { TRAMP_SENTINEL_INSN }
  },
  arm_linux_rt_sigreturn_init
}
Definition at line 432 of file arm-linux-tdep.c.
struct tramp_frame arm_eabi_linux_sigreturn_tramp_frame [static]
Initial value:
 {
  SIGTRAMP_FRAME,
  4,
  {
    { ARM_SET_R7_SIGRETURN, -1 },
    { ARM_EABI_SYSCALL, -1 },
    { TRAMP_SENTINEL_INSN }
  },
  arm_linux_sigreturn_init
}
Definition at line 421 of file arm-linux-tdep.c.
struct tramp_frame arm_kernel_linux_restart_syscall_tramp_frame [static]
Initial value:
 {
  NORMAL_FRAME,
  4,
  {
    { ARM_OABI_SYSCALL_RESTART_SYSCALL, -1 },
    { ARM_LDR_PC_SP_4, -1 },
    { TRAMP_SENTINEL_INSN }
  },
  arm_linux_restart_syscall_init
}
Definition at line 454 of file arm-linux-tdep.c.
const gdb_byte arm_linux_arm_be_breakpoint[] = { 0xef, 0x9f, 0x00, 0x01 } [static]
Definition at line 65 of file arm-linux-tdep.c.
Referenced by arm_linux_init_abi().
const gdb_byte arm_linux_arm_le_breakpoint[] = { 0x01, 0x00, 0x9f, 0xef } [static]
Definition at line 63 of file arm-linux-tdep.c.
Referenced by arm_linux_init_abi().
struct core_regset_section arm_linux_fpa_regset_sections[] [static]
Initial value:
{
  { ".reg", ARM_LINUX_SIZEOF_GREGSET, "general-purpose" },
  { ".reg2", ARM_LINUX_SIZEOF_NWFPE, "FPA floating-point" },
  { NULL, 0}
}
Definition at line 727 of file arm-linux-tdep.c.
struct tramp_frame arm_linux_restart_syscall_tramp_frame [static]
Initial value:
 {
  NORMAL_FRAME,
  4,
  {
    { ARM_OABI_SYSCALL_RESTART_SYSCALL, -1 },
    { ARM_LDR_PC_SP_12, -1 },
    { TRAMP_SENTINEL_INSN }
  },
  arm_linux_restart_syscall_init
}
Definition at line 443 of file arm-linux-tdep.c.
struct tramp_frame arm_linux_rt_sigreturn_tramp_frame [static]
Initial value:
 {
  SIGTRAMP_FRAME,
  4,
  {
    { ARM_LINUX_RT_SIGRETURN_INSTR, -1 },
    { TRAMP_SENTINEL_INSN }
  },
  arm_linux_rt_sigreturn_init
}
Definition at line 411 of file arm-linux-tdep.c.
struct tramp_frame arm_linux_sigreturn_tramp_frame [static]
Initial value:
 {
  SIGTRAMP_FRAME,
  4,
  {
    { ARM_LINUX_SIGRETURN_INSTR, -1 },
    { TRAMP_SENTINEL_INSN }
  },
  arm_linux_sigreturn_init
}
Definition at line 401 of file arm-linux-tdep.c.
const gdb_byte arm_linux_thumb2_be_breakpoint[] = { 0xf7, 0xf0, 0xa0, 0x00 } [static]
Definition at line 88 of file arm-linux-tdep.c.
Referenced by arm_linux_init_abi().
const gdb_byte arm_linux_thumb2_le_breakpoint[] = { 0xf0, 0xf7, 0x00, 0xa0 } [static]
Definition at line 90 of file arm-linux-tdep.c.
Referenced by arm_linux_init_abi().
const gdb_byte arm_linux_thumb_be_breakpoint[] = {0xde, 0x01} [static]
Definition at line 80 of file arm-linux-tdep.c.
Referenced by arm_linux_init_abi().
const gdb_byte arm_linux_thumb_le_breakpoint[] = {0x01, 0xde} [static]
Definition at line 82 of file arm-linux-tdep.c.
Referenced by arm_linux_init_abi().
struct core_regset_section arm_linux_vfp_regset_sections[] [static]
Initial value:
{
  { ".reg", ARM_LINUX_SIZEOF_GREGSET, "general-purpose" },
  { ".reg-arm-vfp", ARM_LINUX_SIZEOF_VFP, "VFP floating-point" },
  { NULL, 0}
}
Definition at line 734 of file arm-linux-tdep.c.
const gdb_byte eabi_linux_arm_be_breakpoint[] = { 0xe7, 0xf0, 0x01, 0xf0 } [static]
Definition at line 75 of file arm-linux-tdep.c.
Referenced by arm_linux_init_abi().
const gdb_byte eabi_linux_arm_le_breakpoint[] = { 0xf0, 0x01, 0xf0, 0xe7 } [static]
Definition at line 73 of file arm-linux-tdep.c.
Referenced by arm_linux_init_abi().