GDB (xrefs): /home/stan/gdb/src/gdb/arm-tdep.h File Reference
/home/stan/gdb/src/gdb/arm-tdep.h File Reference
Classes
struct gdbarch_tdep
struct displaced_step_closure
Defines
#define INT_REGISTER_SIZE 4
#define FP_REGISTER_SIZE 12
#define VFP_REGISTER_SIZE 8
#define NUM_FREGS 8 /* Number of floating point registers. */
#define NUM_SREGS 2 /* Number of status registers. */
#define NUM_GREGS 16 /* Number of general purpose registers. */
#define INST_EQ 0x0
#define INST_NE 0x1
#define INST_CS 0x2
#define INST_CC 0x3
#define INST_MI 0x4
#define INST_PL 0x5
#define INST_VS 0x6
#define INST_VC 0x7
#define INST_HI 0x8
#define INST_LS 0x9
#define INST_GE 0xa
#define INST_LT 0xb
#define INST_GT 0xc
#define INST_LE 0xd
#define INST_AL 0xe
#define INST_NV 0xf
#define FLAG_N 0x80000000
#define FLAG_Z 0x40000000
#define FLAG_C 0x20000000
#define FLAG_V 0x10000000
#define CPSR_T 0x20
#define XPSR_T 0x01000000
#define DISPLACED_TEMPS 16
#define DISPLACED_MODIFIED_INSNS 8
Enumerations
enum gdb_regnum {
ARM_A1_REGNUM = 0, ARM_A4_REGNUM = 3, ARM_AP_REGNUM = 11, ARM_IP_REGNUM = 12,
ARM_SP_REGNUM = 13, ARM_LR_REGNUM = 14, ARM_PC_REGNUM = 15, ARM_F0_REGNUM = 16,
ARM_F3_REGNUM = 19, ARM_F7_REGNUM = 23, ARM_FPS_REGNUM = 24, ARM_PS_REGNUM = 25,
ARM_WR0_REGNUM, ARM_WR15_REGNUM = ARM_WR0_REGNUM + 15, ARM_WC0_REGNUM, ARM_WCSSF_REGNUM = ARM_WC0_REGNUM + 2,
ARM_WCASF_REGNUM = ARM_WC0_REGNUM + 3, ARM_WC7_REGNUM = ARM_WC0_REGNUM + 7, ARM_WCGR0_REGNUM, ARM_WCGR3_REGNUM = ARM_WCGR0_REGNUM + 3,
ARM_WCGR7_REGNUM = ARM_WCGR0_REGNUM + 7, ARM_D0_REGNUM, ARM_D31_REGNUM = ARM_D0_REGNUM + 31, ARM_FPSCR_REGNUM,
ARM_NUM_REGS, ARM_FP_REGNUM = 11, THUMB_FP_REGNUM = 7, ARM_NUM_ARG_REGS = 4,
ARM_LAST_ARG_REGNUM = ARM_A4_REGNUM, ARM_NUM_FP_ARG_REGS = 4, ARM_LAST_FP_ARG_REGNUM = ARM_F3_REGNUM, BFIN_R0_REGNUM = 0,
BFIN_R1_REGNUM, BFIN_R2_REGNUM, BFIN_R3_REGNUM, BFIN_R4_REGNUM,
BFIN_R5_REGNUM, BFIN_R6_REGNUM, BFIN_R7_REGNUM, BFIN_P0_REGNUM,
BFIN_P1_REGNUM, BFIN_P2_REGNUM, BFIN_P3_REGNUM, BFIN_P4_REGNUM,
BFIN_P5_REGNUM, BFIN_SP_REGNUM, BFIN_FP_REGNUM, BFIN_I0_REGNUM,
BFIN_I1_REGNUM, BFIN_I2_REGNUM, BFIN_I3_REGNUM, BFIN_M0_REGNUM,
BFIN_M1_REGNUM, BFIN_M2_REGNUM, BFIN_M3_REGNUM, BFIN_B0_REGNUM,
BFIN_B1_REGNUM, BFIN_B2_REGNUM, BFIN_B3_REGNUM, BFIN_L0_REGNUM,
BFIN_L1_REGNUM, BFIN_L2_REGNUM, BFIN_L3_REGNUM, BFIN_A0_DOT_X_REGNUM,
BFIN_A0_DOT_W_REGNUM, BFIN_A1_DOT_X_REGNUM, BFIN_A1_DOT_W_REGNUM, BFIN_ASTAT_REGNUM,
BFIN_RETS_REGNUM, BFIN_LC0_REGNUM, BFIN_LT0_REGNUM, BFIN_LB0_REGNUM,
BFIN_LC1_REGNUM, BFIN_LT1_REGNUM, BFIN_LB1_REGNUM, BFIN_CYCLES_REGNUM,
BFIN_CYCLES2_REGNUM, BFIN_USP_REGNUM, BFIN_SEQSTAT_REGNUM, BFIN_SYSCFG_REGNUM,
BFIN_RETI_REGNUM, BFIN_RETX_REGNUM, BFIN_RETN_REGNUM, BFIN_RETE_REGNUM,
BFIN_PC_REGNUM, BFIN_CC_REGNUM, E_R0_REGNUM, E_ER0_REGNUM = E_R0_REGNUM,
E_ARG0_REGNUM = E_R0_REGNUM, E_RET0_REGNUM = E_R0_REGNUM, E_R1_REGNUM, E_ER1_REGNUM = E_R1_REGNUM,
E_RET1_REGNUM = E_R1_REGNUM, E_R2_REGNUM, E_ER2_REGNUM = E_R2_REGNUM, E_ARGLAST_REGNUM = E_R2_REGNUM,
E_R3_REGNUM, E_ER3_REGNUM = E_R3_REGNUM, E_R4_REGNUM, E_ER4_REGNUM = E_R4_REGNUM,
E_R5_REGNUM, E_ER5_REGNUM = E_R5_REGNUM, E_R6_REGNUM, E_ER6_REGNUM = E_R6_REGNUM,
E_FP_REGNUM = E_R6_REGNUM, E_SP_REGNUM, E_CCR_REGNUM, E_PC_REGNUM,
E_CYCLES_REGNUM, E_TICK_REGNUM, E_EXR_REGNUM = E_TICK_REGNUM, E_INST_REGNUM,
E_TICKS_REGNUM = E_INST_REGNUM, E_INSTS_REGNUM, E_MACH_REGNUM, E_MACL_REGNUM,
E_SBR_REGNUM, E_VBR_REGNUM, E_R0_REGNUM, E_R1_REGNUM,
E_R2_REGNUM, E_R3_REGNUM, E_R4_REGNUM, E_R5_REGNUM,
E_R6_REGNUM, E_R7_REGNUM, E_R8_REGNUM, E_R9_REGNUM,
E_R10_REGNUM, E_R11_REGNUM, E_R12_REGNUM, E_R13_REGNUM,
E_R14_REGNUM, E_R15_REGNUM, E_R16_REGNUM, E_R17_REGNUM,
E_R18_REGNUM, E_R19_REGNUM, E_R20_REGNUM, E_R21_REGNUM,
E_R22_REGNUM, E_R23_REGNUM, E_R24_REGNUM, E_R25_REGNUM,
E_R26_REGNUM, E_R27_REGNUM, E_R28_REGNUM, E_R29_REGNUM,
E_R30_REGNUM, E_R31_REGNUM, E_PC_REGNUM, E_LR_REGNUM = E_R31_REGNUM,
E_SP_REGNUM = E_R29_REGNUM, E_FP_REGNUM = E_R27_REGNUM, E_FN_RETURN_REGNUM = E_R2_REGNUM, E_1ST_ARGREG = E_R4_REGNUM,
E_LAST_ARGREG = E_R11_REGNUM, E_NUM_REGS = E_PC_REGNUM + 1, SCORE_SP_REGNUM = 0, SCORE_FP_REGNUM = 2,
SCORE_RA_REGNUM = 3, SCORE_A0_REGNUM = 4, SCORE_AL_REGNUM = 7, SCORE_PC_REGNUM = 49,
E_R0_REGNUM, E_R1_REGNUM, E_R2_REGNUM, E_1ST_ARG_REGNUM = E_R2_REGNUM,
E_PTR_RET_REGNUM = E_R2_REGNUM, E_R3_REGNUM, E_R4_REGNUM, E_R5_REGNUM,
E_R6_REGNUM, E_R7_REGNUM, E_LST_ARG_REGNUM = E_R7_REGNUM, E_R8_REGNUM,
E_R9_REGNUM, E_R10_REGNUM, E_R11_REGNUM, E_R12_REGNUM,
E_R13_REGNUM, E_FP_REGNUM = E_R13_REGNUM, E_R14_REGNUM, E_PSW_REGNUM = E_R14_REGNUM,
E_R15_REGNUM, E_SP_REGNUM = E_R15_REGNUM, E_PC_REGNUM, E_NUM_REGS
}
enum arm_float_model {
ARM_FLOAT_AUTO, ARM_FLOAT_SOFT_FPA, ARM_FLOAT_FPA, ARM_FLOAT_SOFT_VFP,
ARM_FLOAT_VFP, ARM_FLOAT_LAST
}
enum arm_abi_kind { ARM_ABI_AUTO, ARM_ABI_APCS, ARM_ABI_AAPCS, ARM_ABI_LAST }
enum struct_return {
pcc_struct_return, reg_struct_return, pcc_struct_return, reg_struct_return,
pcc_struct_return, reg_struct_return
}
enum pc_write_style {
BRANCH_WRITE_PC, BX_WRITE_PC, LOAD_WRITE_PC, ALU_WRITE_PC,
CANNOT_WRITE_PC
}
Functions
void arm_process_displaced_insn (struct gdbarch *gdbarch, CORE_ADDR from, CORE_ADDR to, struct regcache *regs, struct displaced_step_closure *dsc)
void arm_displaced_init_closure (struct gdbarch *gdbarch, CORE_ADDR from, CORE_ADDR to, struct displaced_step_closure *dsc)
ULONGEST displaced_read_reg (struct regcache *regs, struct displaced_step_closure *dsc, int regno)
void displaced_write_reg (struct regcache *regs, struct displaced_step_closure *dsc, int regno, ULONGEST val, enum pc_write_style write_pc)
CORE_ADDR arm_skip_stub (struct frame_info *, CORE_ADDR)
CORE_ADDR arm_get_next_pc (struct frame_info *, CORE_ADDR)
void arm_insert_single_step_breakpoint (struct gdbarch *, struct address_space *, CORE_ADDR)
int arm_deal_with_atomic_sequence (struct frame_info *)
int arm_software_single_step (struct frame_info *)
int arm_frame_is_thumb (struct frame_info *frame)
struct displaced_step_closure * arm_displaced_step_copy_insn (struct gdbarch *, CORE_ADDR, CORE_ADDR, struct regcache *)
void arm_displaced_step_fixup (struct gdbarch *, struct displaced_step_closure *, CORE_ADDR, CORE_ADDR, struct regcache *)
int arm_psr_thumb_bit (struct gdbarch *)
int arm_pc_is_thumb (struct gdbarch *, CORE_ADDR)
int arm_process_record (struct gdbarch *gdbarch, struct regcache *regcache, CORE_ADDR addr)
struct regset * armbsd_regset_from_core_section (struct gdbarch *gdbarch, const char *sect_name, size_t sect_size)
Variables
struct target_desc * tdesc_arm_with_m
struct target_desc * tdesc_arm_with_iwmmxt
struct target_desc * tdesc_arm_with_vfpv2
struct target_desc * tdesc_arm_with_vfpv3
struct target_desc * tdesc_arm_with_neon
Define Documentation
#define CPSR_T 0x20
Definition at line 113 of file arm-tdep.h.
Referenced by arm_psr_thumb_bit().
#define DISPLACED_MODIFIED_INSNS 8
Definition at line 219 of file arm-tdep.h.
Referenced by arm_gdbarch_init(), and arm_linux_cleanup_svc().
#define DISPLACED_TEMPS 16
Definition at line 215 of file arm-tdep.h.
#define FLAG_C 0x20000000
Definition at line 110 of file arm-tdep.h.
Referenced by arm_get_next_pc_raw(), and condition_true().
#define FLAG_N 0x80000000
Definition at line 108 of file arm-tdep.h.
Referenced by condition_true().
#define FLAG_V 0x10000000
Definition at line 111 of file arm-tdep.h.
Referenced by condition_true().
#define FLAG_Z 0x40000000
Definition at line 109 of file arm-tdep.h.
Referenced by condition_true().
#define FP_REGISTER_SIZE 12
Definition at line 72 of file arm-tdep.h.
Referenced by arm_extract_return_value(), arm_register_g_packet_guesses(), collect_nwfpe_register(), and supply_nwfpe_register().
#define INST_AL 0xe
Definition at line 105 of file arm-tdep.h.
Referenced by condition_true(), thumb2_copy_b_bl_blx(), thumb2_copy_block_xfer(), thumb2_copy_table_branch(), thumb_copy_b(), thumb_copy_bx_blx_reg(), thumb_copy_cbnz_cbz(), and thumb_copy_pop_pc_16bit().
#define INST_CC 0x3
Definition at line 94 of file arm-tdep.h.
Referenced by condition_true().
#define INST_CS 0x2
Definition at line 93 of file arm-tdep.h.
Referenced by condition_true().
#define INST_EQ 0x0
Definition at line 91 of file arm-tdep.h.
Referenced by condition_true().
#define INST_GE 0xa
Definition at line 101 of file arm-tdep.h.
Referenced by condition_true().
#define INST_GT 0xc
Definition at line 103 of file arm-tdep.h.
Referenced by condition_true().
#define INST_HI 0x8
Definition at line 99 of file arm-tdep.h.
Referenced by condition_true().
#define INST_LE 0xd
Definition at line 104 of file arm-tdep.h.
Referenced by condition_true().
#define INST_LS 0x9
Definition at line 100 of file arm-tdep.h.
Referenced by condition_true().
#define INST_LT 0xb
Definition at line 102 of file arm-tdep.h.
Referenced by condition_true().
#define INST_MI 0x4
Definition at line 95 of file arm-tdep.h.
Referenced by condition_true().
#define INST_NE 0x1
Definition at line 92 of file arm-tdep.h.
Referenced by condition_true().
#define INST_NV 0xf
Definition at line 106 of file arm-tdep.h.
Referenced by arm_get_next_pc_raw(), arm_in_function_epilogue_p(), arm_instruction_changes_pc(), and condition_true().
#define INST_PL 0x5
Definition at line 96 of file arm-tdep.h.
Referenced by condition_true().
#define INST_VC 0x7
Definition at line 98 of file arm-tdep.h.
Referenced by condition_true().
#define INST_VS 0x6
Definition at line 97 of file arm-tdep.h.
Referenced by condition_true().
#define INT_REGISTER_SIZE 4
Definition at line 67 of file arm-tdep.h.
Referenced by arm_extract_return_value(), arm_get_longjmp_target(), arm_linux_collect_gregset(), arm_linux_collect_nwfpe(), arm_linux_supply_gregset(), arm_push_dummy_call(), arm_register_g_packet_guesses(), arm_return_in_memory(), arm_return_value(), arm_store_return_value(), and thumb_get_next_pc_raw().
#define NUM_FREGS 8 /* Number of floating point registers. */
Definition at line 85 of file arm-tdep.h.
#define NUM_GREGS 16 /* Number of general purpose registers. */
Definition at line 87 of file arm-tdep.h.
Referenced by arm_register_sim_regno().
#define NUM_SREGS 2 /* Number of status registers. */
Definition at line 86 of file arm-tdep.h.
Referenced by arm_register_sim_regno().
#define VFP_REGISTER_SIZE 8
Definition at line 76 of file arm-tdep.h.
Referenced by arm_register_g_packet_guesses().
#define XPSR_T 0x01000000
Definition at line 115 of file arm-tdep.h.
Referenced by arm_psr_thumb_bit().
Enumeration Type Documentation
enum arm_abi_kind
Enumerator:
ARM_ABI_AUTO
ARM_ABI_APCS
ARM_ABI_AAPCS
ARM_ABI_LAST
Definition at line 138 of file arm-tdep.h.
enum arm_float_model
Enumerator:
ARM_FLOAT_AUTO
ARM_FLOAT_SOFT_FPA
ARM_FLOAT_FPA
ARM_FLOAT_SOFT_VFP
ARM_FLOAT_VFP
ARM_FLOAT_LAST
Definition at line 127 of file arm-tdep.h.
enum gdb_regnum
Enumerator:
ARM_A1_REGNUM
ARM_A4_REGNUM
ARM_AP_REGNUM
ARM_IP_REGNUM
ARM_SP_REGNUM
ARM_LR_REGNUM
ARM_PC_REGNUM
ARM_F0_REGNUM
ARM_F3_REGNUM
ARM_F7_REGNUM
ARM_FPS_REGNUM
ARM_PS_REGNUM
ARM_WR0_REGNUM
ARM_WR15_REGNUM
ARM_WC0_REGNUM
ARM_WCSSF_REGNUM
ARM_WCASF_REGNUM
ARM_WC7_REGNUM
ARM_WCGR0_REGNUM
ARM_WCGR3_REGNUM
ARM_WCGR7_REGNUM
ARM_D0_REGNUM
ARM_D31_REGNUM
ARM_FPSCR_REGNUM
ARM_NUM_REGS
ARM_FP_REGNUM
THUMB_FP_REGNUM
ARM_NUM_ARG_REGS
ARM_LAST_ARG_REGNUM
ARM_NUM_FP_ARG_REGS
ARM_LAST_FP_ARG_REGNUM
BFIN_R0_REGNUM
BFIN_R1_REGNUM
BFIN_R2_REGNUM
BFIN_R3_REGNUM
BFIN_R4_REGNUM
BFIN_R5_REGNUM
BFIN_R6_REGNUM
BFIN_R7_REGNUM
BFIN_P0_REGNUM
BFIN_P1_REGNUM
BFIN_P2_REGNUM
BFIN_P3_REGNUM
BFIN_P4_REGNUM
BFIN_P5_REGNUM
BFIN_SP_REGNUM
BFIN_FP_REGNUM
BFIN_I0_REGNUM
BFIN_I1_REGNUM
BFIN_I2_REGNUM
BFIN_I3_REGNUM
BFIN_M0_REGNUM
BFIN_M1_REGNUM
BFIN_M2_REGNUM
BFIN_M3_REGNUM
BFIN_B0_REGNUM
BFIN_B1_REGNUM
BFIN_B2_REGNUM
BFIN_B3_REGNUM
BFIN_L0_REGNUM
BFIN_L1_REGNUM
BFIN_L2_REGNUM
BFIN_L3_REGNUM
BFIN_A0_DOT_X_REGNUM
BFIN_A0_DOT_W_REGNUM
BFIN_A1_DOT_X_REGNUM
BFIN_A1_DOT_W_REGNUM
BFIN_ASTAT_REGNUM
BFIN_RETS_REGNUM
BFIN_LC0_REGNUM
BFIN_LT0_REGNUM
BFIN_LB0_REGNUM
BFIN_LC1_REGNUM
BFIN_LT1_REGNUM
BFIN_LB1_REGNUM
BFIN_CYCLES_REGNUM
BFIN_CYCLES2_REGNUM
BFIN_USP_REGNUM
BFIN_SEQSTAT_REGNUM
BFIN_SYSCFG_REGNUM
BFIN_RETI_REGNUM
BFIN_RETX_REGNUM
BFIN_RETN_REGNUM
BFIN_RETE_REGNUM
BFIN_PC_REGNUM
BFIN_CC_REGNUM
E_R0_REGNUM
E_ER0_REGNUM
E_ARG0_REGNUM
E_RET0_REGNUM
E_R1_REGNUM
E_ER1_REGNUM
E_RET1_REGNUM
E_R2_REGNUM
E_ER2_REGNUM
E_ARGLAST_REGNUM
E_R3_REGNUM
E_ER3_REGNUM
E_R4_REGNUM
E_ER4_REGNUM
E_R5_REGNUM
E_ER5_REGNUM
E_R6_REGNUM
E_ER6_REGNUM
E_FP_REGNUM
E_SP_REGNUM
E_CCR_REGNUM
E_PC_REGNUM
E_CYCLES_REGNUM
E_TICK_REGNUM
E_EXR_REGNUM
E_INST_REGNUM
E_TICKS_REGNUM
E_INSTS_REGNUM
E_MACH_REGNUM
E_MACL_REGNUM
E_SBR_REGNUM
E_VBR_REGNUM
E_R0_REGNUM
E_R1_REGNUM
E_R2_REGNUM
E_R3_REGNUM
E_R4_REGNUM
E_R5_REGNUM
E_R6_REGNUM
E_R7_REGNUM
E_R8_REGNUM
E_R9_REGNUM
E_R10_REGNUM
E_R11_REGNUM
E_R12_REGNUM
E_R13_REGNUM
E_R14_REGNUM
E_R15_REGNUM
E_R16_REGNUM
E_R17_REGNUM
E_R18_REGNUM
E_R19_REGNUM
E_R20_REGNUM
E_R21_REGNUM
E_R22_REGNUM
E_R23_REGNUM
E_R24_REGNUM
E_R25_REGNUM
E_R26_REGNUM
E_R27_REGNUM
E_R28_REGNUM
E_R29_REGNUM
E_R30_REGNUM
E_R31_REGNUM
E_PC_REGNUM
E_LR_REGNUM
E_SP_REGNUM
E_FP_REGNUM
E_FN_RETURN_REGNUM
E_1ST_ARGREG
E_LAST_ARGREG
E_NUM_REGS
SCORE_SP_REGNUM
SCORE_FP_REGNUM
SCORE_RA_REGNUM
SCORE_A0_REGNUM
SCORE_AL_REGNUM
SCORE_PC_REGNUM
E_R0_REGNUM
E_R1_REGNUM
E_R2_REGNUM
E_1ST_ARG_REGNUM
E_PTR_RET_REGNUM
E_R3_REGNUM
E_R4_REGNUM
E_R5_REGNUM
E_R6_REGNUM
E_R7_REGNUM
E_LST_ARG_REGNUM
E_R8_REGNUM
E_R9_REGNUM
E_R10_REGNUM
E_R11_REGNUM
E_R12_REGNUM
E_R13_REGNUM
E_FP_REGNUM
E_R14_REGNUM
E_PSW_REGNUM
E_R15_REGNUM
E_SP_REGNUM
E_PC_REGNUM
E_NUM_REGS
Definition at line 29 of file arm-tdep.h.
enum pc_write_style
Enumerator:
BRANCH_WRITE_PC
BX_WRITE_PC
LOAD_WRITE_PC
ALU_WRITE_PC
CANNOT_WRITE_PC
Definition at line 294 of file arm-tdep.h.
enum struct_return
Enumerator:
pcc_struct_return
reg_struct_return
pcc_struct_return
reg_struct_return
pcc_struct_return
reg_struct_return
Definition at line 148 of file arm-tdep.h.
Function Documentation
int arm_deal_with_atomic_sequence (struct frame_info *)
Definition at line 5220 of file arm-tdep.c.
References arm_deal_with_atomic_sequence_raw(), arm_frame_is_thumb(), and thumb_deal_with_atomic_sequence_raw().
Referenced by arm_linux_software_single_step(), and arm_software_single_step().
void arm_displaced_init_closure (struct gdbarch * gdbarch, CORE_ADDR from, CORE_ADDR to, struct displaced_step_closure * dsc)
Definition at line 8612 of file arm-tdep.c.
References gdbarch_tdep::arm_breakpoint, gdbarch_tdep::arm_breakpoint_size, debug_displaced, fprintf_unfiltered(), gdb_stdlog, gdbarch_byte_order_for_code(), gdbarch_tdep(), displaced_step_closure::is_thumb, len, displaced_step_closure::modinsn, displaced_step_closure::numinsns, offset, paddress(), size, gdbarch_tdep::thumb_breakpoint, gdbarch_tdep::thumb_breakpoint_size, write_memory(), and write_memory_unsigned_integer().
Referenced by arm_displaced_step_copy_insn(), and arm_linux_displaced_step_copy_insn().
struct displaced_step_closure* arm_displaced_step_copy_insn (struct gdbarch * , CORE_ADDR , CORE_ADDR , struct regcache *) [read]
Definition at line 8669 of file arm-tdep.c.
References arm_displaced_init_closure(), arm_process_displaced_insn(), and xmalloc().
void arm_displaced_step_fixup (struct gdbarch * , struct displaced_step_closure * , CORE_ADDR , CORE_ADDR , struct regcache *)
Definition at line 8685 of file arm-tdep.c.
References ARM_PC_REGNUM, displaced_step_closure::cleanup, displaced_step_closure::insn_addr, displaced_step_closure::insn_size, regcache_cooked_write_unsigned(), and displaced_step_closure::wrote_to_pc.
Referenced by arm_linux_init_abi().
int arm_frame_is_thumb (struct frame_info * frame)
Definition at line 295 of file arm-tdep.c.
References ARM_PS_REGNUM, arm_psr_thumb_bit(), get_frame_arch(), get_frame_register_unsigned(), and ULONGEST.
Referenced by arm_deal_with_atomic_sequence(), arm_exidx_unwind_sniffer(), arm_get_next_pc(), arm_linux_syscall_next_pc(), arm_pc_is_thumb(), and arm_scan_prologue().
CORE_ADDR arm_get_next_pc (struct frame_info * , CORE_ADDR)
Definition at line 4968 of file arm-tdep.c.
References _, arm_frame_is_thumb(), arm_get_next_pc_raw(), error(), MAKE_THUMB_ADDR, and thumb_get_next_pc_raw().
Referenced by arm_linux_software_single_step(), and arm_software_single_step().
void arm_insert_single_step_breakpoint (struct gdbarch * , struct address_space * , CORE_ADDR)
Definition at line 4993 of file arm-tdep.c.
References arm_override_mode, do_cleanups(), gdbarch_addr_bits_remove(), insert_single_step_breakpoint(), IS_THUMB_ADDR, and make_cleanup_restore_integer().
Referenced by arm_deal_with_atomic_sequence_raw(), arm_linux_software_single_step(), arm_software_single_step(), thumb_deal_with_atomic_sequence_raw(), and thumb_get_next_pc_raw().
int arm_pc_is_thumb (struct gdbarch * , CORE_ADDR)
Definition at line 382 of file arm-tdep.c.
References arm_fallback_mode_string, arm_find_mapping_symbol(), arm_force_mode_string, arm_frame_is_thumb(), arm_override_mode, debug_displaced, fprintf_unfiltered(), gdb_stdlog, get_current_frame(), get_displaced_step_closure_by_addr(), displaced_step_closure::insn_addr, IS_THUMB_ADDR, lookup_minimal_symbol_by_pc(), bound_minimal_symbol::minsym, MSYMBOL_IS_SPECIAL, target_has_registers, and type.
Referenced by arm_adjust_breakpoint_address(), arm_analyze_load_stack_chk_guard(), arm_breakpoint_from_pc(), arm_in_function_epilogue_p(), arm_linux_hw_breakpoint_initialize(), arm_push_dummy_call(), arm_remote_breakpoint_from_pc(), arm_skip_prologue(), arm_skip_stack_protector(), arm_write_pc(), and gdb_print_insn_arm().
void arm_process_displaced_insn (struct gdbarch * gdbarch, CORE_ADDR from, CORE_ADDR to, struct regcache * regs, struct displaced_step_closure * dsc)
Definition at line 8552 of file arm-tdep.c.
References _, arm_decode_b_bl_ldmstm(), arm_decode_dp_misc(), arm_decode_ld_st_word_ubyte(), arm_decode_media(), arm_decode_svc_copro(), arm_decode_unconditional(), displaced_step_closure::cleanup, debug_displaced, displaced_in_arm_mode(), fprintf_unfiltered(), from, gdb_stdlog, gdbarch_byte_order_for_code(), displaced_step_closure::insn_addr, displaced_step_closure::insn_size, internal_error(), displaced_step_closure::is_thumb, displaced_step_closure::numinsns, read_memory_unsigned_integer(), displaced_step_closure::scratch_base, thumb_process_displaced_insn(), to, and displaced_step_closure::wrote_to_pc.
Referenced by arm_displaced_step_copy_insn(), and arm_linux_displaced_step_copy_insn().
int arm_process_record (struct gdbarch * gdbarch, struct regcache * regcache, CORE_ADDR addr)
Definition at line 12537 of file arm-tdep.c.
References _, arm_mem_r::addr, insn_decode_record_t::arm_insn, ARM_INSN_SIZE_BYTES, insn_decode_record_t::arm_mems, ARM_PC_REGNUM, ARM_PS_REGNUM, arm_psr_thumb_bit(), ARM_RECORD, insn_decode_record_t::arm_regs, bits, deallocate_reg_mem(), decode_insn(), extract_arm_insn(), fprintf_unfiltered(), gdb_stdlog, insn_decode_record_t::gdbarch, gdbarch_byte_order(), arm_mem_r::len, insn_decode_record_t::mem_rec_count, memset(), paddress(), printf_unfiltered(), record_debug, record_full_arch_list_add_end(), record_full_arch_list_add_mem(), record_full_arch_list_add_reg(), insn_decode_record_t::reg_rec_count, insn_decode_record_t::regcache, regcache_raw_read_unsigned(), insn_decode_record_t::this_addr, THUMB2_INSN_SIZE_BYTES, THUMB2_RECORD, THUMB_INSN_SIZE_BYTES, THUMB_RECORD, and ULONGEST.
Referenced by arm_linux_init_abi().
int arm_psr_thumb_bit (struct gdbarch *)
Definition at line 284 of file arm-tdep.c.
References CPSR_T, and XPSR_T.
Referenced by arm_dwarf2_prev_register(), arm_frame_is_thumb(), arm_linux_get_syscall_number(), arm_linux_restart_syscall_init(), arm_linux_sigreturn_return_addr(), arm_process_record(), arm_prologue_prev_register(), arm_write_pc(), bx_write_pc(), and displaced_in_arm_mode().
CORE_ADDR arm_skip_stub (struct frame_info * , CORE_ADDR)
Definition at line 9228 of file arm-tdep.c.
References find_pc_partial_function(), find_pc_section(), get_frame_register_unsigned(), lookup_minimal_symbol(), memcpy(), name, obj_section::objfile, offset, SYMBOL_VALUE_ADDRESS, and target_name.
Referenced by arm_gdbarch_init(), and arm_pe_skip_trampoline_code().
int arm_software_single_step (struct frame_info *)
Definition at line 5234 of file arm-tdep.c.
References arm_deal_with_atomic_sequence(), arm_get_next_pc(), arm_insert_single_step_breakpoint(), get_frame_address_space(), get_frame_arch(), and get_frame_pc().
Referenced by arm_netbsd_init_abi_common(), arm_wince_init_abi(), and armobsd_init_abi().
struct regset* armbsd_regset_from_core_section (struct gdbarch * gdbarch, const char * sect_name, size_t sect_size) [read]
Definition at line 117 of file armbsd-tdep.c.
References armbsd_fpregset, armbsd_gregset, ARMBSD_SIZEOF_FPREGS, and ARMBSD_SIZEOF_GREGS.
Referenced by armobsd_init_abi().
ULONGEST displaced_read_reg (struct regcache * regs, struct displaced_step_closure * dsc, int regno)
Definition at line 5467 of file arm-tdep.c.
References ARM_PC_REGNUM, debug_displaced, fprintf_unfiltered(), from, gdb_stdlog, displaced_step_closure::insn_addr, displaced_step_closure::is_thumb, regcache_cooked_read_unsigned(), and ULONGEST.
Referenced by arm_catch_kernel_helper_return(), arm_copy_alu_imm(), arm_copy_block_xfer(), arm_copy_extra_ld_st(), arm_linux_copy_svc(), cleanup_alu_imm(), cleanup_alu_reg(), cleanup_alu_shifted_reg(), cleanup_block_load_all(), cleanup_block_load_pc(), cleanup_block_store_pc(), cleanup_branch(), cleanup_copro_load_store(), cleanup_load(), cleanup_pop_pc_16bit_all(), cleanup_store(), install_alu_reg(), install_alu_shifted_reg(), install_bx_blx_reg(), install_copro_load_store(), install_load_store(), install_pc_relative(), install_preload(), install_preload_reg(), thumb2_copy_alu_imm(), thumb2_copy_block_xfer(), thumb2_copy_load_literal(), thumb2_copy_preload(), thumb2_copy_table_branch(), thumb_copy_16bit_ldr_literal(), thumb_copy_cbnz_cbz(), and thumb_copy_pop_pc_16bit().
void displaced_write_reg (struct regcache * regs, struct displaced_step_closure * dsc, int regno, ULONGEST val, enum pc_write_style write_pc)
Definition at line 5587 of file arm-tdep.c.
References _, ALU_WRITE_PC, alu_write_pc(), ARM_PC_REGNUM, BRANCH_WRITE_PC, branch_write_pc(), BX_WRITE_PC, bx_write_pc(), CANNOT_WRITE_PC, debug_displaced, fprintf_unfiltered(), gdb_stdlog, internal_error(), LOAD_WRITE_PC, load_write_pc(), regcache_cooked_write_unsigned(), warning(), and displaced_step_closure::wrote_to_pc.
Referenced by arm_catch_kernel_helper_return(), arm_copy_alu_imm(), arm_copy_extra_ld_st(), arm_linux_cleanup_svc(), cleanup_alu_imm(), cleanup_alu_reg(), cleanup_alu_shifted_reg(), cleanup_block_load_all(), cleanup_block_load_pc(), cleanup_branch(), cleanup_copro_load_store(), cleanup_kernel_helper_return(), cleanup_load(), cleanup_pop_pc_16bit_all(), cleanup_preload(), cleanup_store(), cleanup_svc(), install_alu_reg(), install_alu_shifted_reg(), install_copro_load_store(), install_load_store(), install_pc_relative(), install_preload(), install_preload_reg(), thumb2_copy_alu_imm(), thumb2_copy_load_literal(), thumb2_copy_preload(), and thumb_copy_16bit_ldr_literal().
Variable Documentation
struct target_desc* tdesc_arm_with_iwmmxt
Definition at line 8 of file arm-with-iwmmxt.c.
Referenced by arm_linux_read_description().
struct target_desc* tdesc_arm_with_m
Definition at line 8 of file arm-with-m.c.
Referenced by arm_register_g_packet_guesses().
struct target_desc* tdesc_arm_with_neon
Definition at line 8 of file arm-with-neon.c.
Referenced by arm_linux_core_read_description(), and arm_linux_read_description().
struct target_desc* tdesc_arm_with_vfpv2
Definition at line 8 of file arm-with-vfpv2.c.
Referenced by arm_linux_core_read_description(), and arm_linux_read_description().
struct target_desc* tdesc_arm_with_vfpv3
Definition at line 8 of file arm-with-vfpv3.c.
Referenced by arm_linux_core_read_description(), and arm_linux_read_description().