GDB (xrefs): /home/stan/gdb/src/gdb/arm-linux-nat.c File Reference
/home/stan/gdb/src/gdb/arm-linux-nat.c File Reference
#include "defs.h"
#include "inferior.h"
#include "gdbcore.h"
#include "gdb_string.h"
#include "regcache.h"
#include "target.h"
#include "linux-nat.h"
#include "target-descriptions.h"
#include "auxv.h"
#include "observer.h"
#include "gdbthread.h"
#include "arm-tdep.h"
#include "arm-linux-tdep.h"
#include <elf/common.h>
#include <sys/user.h>
#include <sys/ptrace.h>
#include <sys/utsname.h>
#include <sys/procfs.h>
#include "gregset.h"
#include "gdb_proc_service.h"
Classes
struct arm_linux_hwbp_cap
struct arm_linux_hw_breakpoint
struct arm_linux_thread_points
Defines
#define PTRACE_GET_THREAD_AREA 22
#define PTRACE_GETWMMXREGS 18
#define PTRACE_SETWMMXREGS 19
#define PTRACE_GETVFPREGS 27
#define PTRACE_SETVFPREGS 28
#define PTRACE_GETHBPREGS 29
#define PTRACE_SETHBPREGS 30
#define GET_THREAD_ID(PTID) get_thread_id (PTID)
#define IWMMXT_REGS_SIZE (16 * 8 + 6 * 4)
#define VFP_REGS_SIZE (32 * 8 + 4)
Typedefs
typedef unsigned int arm_hwbp_control_t
typedef struct
arm_linux_thread_points * arm_linux_thread_points_p
Enumerations
enum arm_hwbp_type { arm_hwbp_break = 0, arm_hwbp_load = 1, arm_hwbp_store = 2, arm_hwbp_access = 3 }
Functions
static int get_thread_id (ptid_t ptid)
static void fetch_fpregister (struct regcache *regcache, int regno)
static void fetch_fpregs (struct regcache *regcache)
static void store_fpregister (const struct regcache *regcache, int regno)
static void store_fpregs (const struct regcache *regcache)
static void fetch_register (struct regcache *regcache, int regno)
static void fetch_regs (struct regcache *regcache)
static void store_register (const struct regcache *regcache, int regno)
static void store_regs (const struct regcache *regcache)
static void fetch_wmmx_regs (struct regcache *regcache)
static void store_wmmx_regs (const struct regcache *regcache)
static void fetch_vfp_regs (struct regcache *regcache)
static void store_vfp_regs (const struct regcache *regcache)
static void arm_linux_fetch_inferior_registers (struct target_ops *ops, struct regcache *regcache, int regno)
static void arm_linux_store_inferior_registers (struct target_ops *ops, struct regcache *regcache, int regno)
void fill_gregset (const struct regcache *regcache, gdb_gregset_t *gregsetp, int regno)
void supply_gregset (struct regcache *regcache, const gdb_gregset_t *gregsetp)
void fill_fpregset (const struct regcache *regcache, gdb_fpregset_t *fpregsetp, int regno)
void supply_fpregset (struct regcache *regcache, const gdb_fpregset_t *fpregsetp)
ps_err_e ps_get_thread_area (const struct ps_prochandle *ph, lwpid_t lwpid, int idx, void **base)
static struct target_desc * arm_linux_read_description (struct target_ops *ops)
static struct arm_linux_hwbp_cap * arm_linux_get_hwbp_cap (void)
static int arm_linux_get_hw_breakpoint_count (void)
static int arm_linux_get_hw_watchpoint_count (void)
static int arm_linux_can_use_hw_breakpoint (int type, int cnt, int ot)
DEF_VEC_P (arm_linux_thread_points_p)
VEC (arm_linux_thread_points_p)
static arm_hwbp_control_t arm_hwbp_control_initialize (unsigned byte_address_select, arm_hwbp_type hwbp_type, int enable)
static int arm_hwbp_control_is_enabled (arm_hwbp_control_t control)
static arm_hwbp_control_t arm_hwbp_control_disable (arm_hwbp_control_t control)
static void arm_linux_hw_breakpoint_initialize (struct gdbarch *gdbarch, struct bp_target_info *bp_tgt, struct arm_linux_hw_breakpoint *p)
static arm_hwbp_type arm_linux_get_hwbp_type (int rw)
static void arm_linux_hw_watchpoint_initialize (CORE_ADDR addr, int len, int rw, struct arm_linux_hw_breakpoint *p)
static int arm_linux_hw_breakpoint_equal (const struct arm_linux_hw_breakpoint *p1, const struct arm_linux_hw_breakpoint *p2)
static void arm_linux_insert_hw_breakpoint1 (const struct arm_linux_hw_breakpoint *bpt, int tid, int watchpoint)
static void arm_linux_remove_hw_breakpoint1 (const struct arm_linux_hw_breakpoint *bpt, int tid, int watchpoint)
static int arm_linux_insert_hw_breakpoint (struct gdbarch *gdbarch, struct bp_target_info *bp_tgt)
static int arm_linux_remove_hw_breakpoint (struct gdbarch *gdbarch, struct bp_target_info *bp_tgt)
static int arm_linux_region_ok_for_hw_watchpoint (CORE_ADDR addr, int len)
static int arm_linux_insert_watchpoint (CORE_ADDR addr, int len, int rw, struct expression *cond)
static int arm_linux_remove_watchpoint (CORE_ADDR addr, int len, int rw, struct expression *cond)
static int arm_linux_stopped_data_address (struct target_ops *target, CORE_ADDR *addr_p)
static int arm_linux_stopped_by_watchpoint (void)
static int arm_linux_watchpoint_addr_within_range (struct target_ops *target, CORE_ADDR addr, CORE_ADDR start, int length)
static void arm_linux_new_thread (struct lwp_info *lp)
static void arm_linux_thread_exit (struct thread_info *tp, int silent)
void _initialize_arm_linux_nat (void)
Variables
static int arm_linux_has_wmmx_registers
static int arm_linux_vfp_register_count
int arm_apcs_32
Define Documentation
#define GET_THREAD_ID (PTID) get_thread_id (PTID)
Definition at line 89 of file arm-linux-nat.c.
Referenced by arm_linux_get_hwbp_cap(), fetch_fpregister(), fetch_fpregs(), fetch_register(), fetch_regs(), fetch_vfp_regs(), fetch_wmmx_regs(), store_fpregister(), store_fpregs(), store_register(), store_regs(), store_vfp_regs(), and store_wmmx_regs().
#define IWMMXT_REGS_SIZE (16 * 8 + 6 * 4)
Definition at line 380 of file arm-linux-nat.c.
Referenced by fetch_wmmx_regs(), and store_wmmx_regs().
#define PTRACE_GET_THREAD_AREA 22
Definition at line 47 of file arm-linux-nat.c.
Referenced by ps_get_thread_area().
#define PTRACE_GETHBPREGS 29
Definition at line 61 of file arm-linux-nat.c.
Referenced by arm_linux_get_hwbp_cap().
#define PTRACE_GETVFPREGS 27
Definition at line 56 of file arm-linux-nat.c.
Referenced by arm_linux_read_description(), fetch_vfp_regs(), and store_vfp_regs().
#define PTRACE_GETWMMXREGS 18
Definition at line 51 of file arm-linux-nat.c.
Referenced by fetch_wmmx_regs(), and store_wmmx_regs().
#define PTRACE_SETHBPREGS 30
Definition at line 62 of file arm-linux-nat.c.
Referenced by arm_linux_insert_hw_breakpoint1(), and arm_linux_remove_hw_breakpoint1().
#define PTRACE_SETVFPREGS 28
Definition at line 57 of file arm-linux-nat.c.
Referenced by store_vfp_regs().
#define PTRACE_SETWMMXREGS 19
Definition at line 52 of file arm-linux-nat.c.
Referenced by store_wmmx_regs().
#define VFP_REGS_SIZE (32 * 8 + 4)
Definition at line 457 of file arm-linux-nat.c.
Referenced by arm_linux_read_description(), fetch_vfp_regs(), and store_vfp_regs().
Typedef Documentation
typedef unsigned int arm_hwbp_control_t
Definition at line 779 of file arm-linux-nat.c.
typedef struct arm_linux_thread_points * arm_linux_thread_points_p
Enumeration Type Documentation
enum arm_hwbp_type
Enumerator:
arm_hwbp_break
arm_hwbp_load
arm_hwbp_store
arm_hwbp_access
Definition at line 770 of file arm-linux-nat.c.
Function Documentation
void _initialize_arm_linux_nat (void)
Definition at line 1255 of file arm-linux-nat.c.
References arm_linux_can_use_hw_breakpoint(), arm_linux_fetch_inferior_registers(), arm_linux_insert_hw_breakpoint(), arm_linux_insert_watchpoint(), arm_linux_new_thread(), arm_linux_read_description(), arm_linux_region_ok_for_hw_watchpoint(), arm_linux_remove_hw_breakpoint(), arm_linux_remove_watchpoint(), arm_linux_stopped_by_watchpoint(), arm_linux_stopped_data_address(), arm_linux_store_inferior_registers(), arm_linux_thread_exit(), arm_linux_watchpoint_addr_within_range(), linux_nat_add_target(), linux_nat_set_new_thread(), linux_target(), observer_attach_thread_exit(), target_ops::to_can_use_hw_breakpoint, target_ops::to_fetch_registers, target_ops::to_insert_hw_breakpoint, target_ops::to_insert_watchpoint, target_ops::to_read_description, target_ops::to_region_ok_for_hw_watchpoint, target_ops::to_remove_hw_breakpoint, target_ops::to_remove_watchpoint, target_ops::to_stopped_by_watchpoint, target_ops::to_stopped_data_address, target_ops::to_store_registers, and target_ops::to_watchpoint_addr_within_range.
static arm_hwbp_control_t arm_hwbp_control_disable (arm_hwbp_control_t control) [static]
Definition at line 881 of file arm-linux-nat.c.
Referenced by arm_linux_remove_hw_breakpoint1().
static arm_hwbp_control_t arm_hwbp_control_initialize (unsigned byte_address_select, arm_hwbp_type hwbp_type, int enable) [static]
Definition at line 861 of file arm-linux-nat.c.
References arm_hwbp_break, enable, and gdb_assert.
Referenced by arm_linux_hw_breakpoint_initialize(), and arm_linux_hw_watchpoint_initialize().
static int arm_hwbp_control_is_enabled (arm_hwbp_control_t control) [static]
Definition at line 874 of file arm-linux-nat.c.
Referenced by arm_linux_insert_hw_breakpoint1(), and arm_linux_new_thread().
static int arm_linux_can_use_hw_breakpoint (int type, int cnt, int ot) [static]
Definition at line 750 of file arm-linux-nat.c.
References arm_linux_get_hw_breakpoint_count(), arm_linux_get_hw_watchpoint_count(), bp_access_watchpoint, bp_hardware_breakpoint, bp_hardware_watchpoint, bp_read_watchpoint, bp_watchpoint, and gdb_assert.
Referenced by _initialize_arm_linux_nat().
static void arm_linux_fetch_inferior_registers (struct target_ops * ops, struct regcache * regcache, int regno) [static]
Definition at line 520 of file arm-linux-nat.c.
References ARM_D0_REGNUM, ARM_F0_REGNUM, ARM_FPS_REGNUM, arm_linux_has_wmmx_registers, arm_linux_vfp_register_count, ARM_PS_REGNUM, ARM_WCGR7_REGNUM, ARM_WR0_REGNUM, fetch_fpregister(), fetch_fpregs(), fetch_register(), fetch_regs(), fetch_vfp_regs(), and fetch_wmmx_regs().
Referenced by _initialize_arm_linux_nat().
static int arm_linux_get_hw_breakpoint_count (void) [static]
Definition at line 733 of file arm-linux-nat.c.
References arm_linux_get_hwbp_cap(), and arm_linux_hwbp_cap::bp_count.
Referenced by arm_linux_can_use_hw_breakpoint(), arm_linux_insert_hw_breakpoint(), arm_linux_insert_hw_breakpoint1(), arm_linux_remove_hw_breakpoint(), arm_linux_remove_hw_breakpoint1(), and VEC().
static int arm_linux_get_hw_watchpoint_count (void) [static]
Definition at line 741 of file arm-linux-nat.c.
References arm_linux_get_hwbp_cap(), and arm_linux_hwbp_cap::wp_count.
Referenced by arm_linux_can_use_hw_breakpoint(), arm_linux_insert_hw_breakpoint1(), arm_linux_insert_watchpoint(), arm_linux_remove_hw_breakpoint1(), arm_linux_remove_watchpoint(), arm_linux_stopped_data_address(), and VEC().
static struct arm_linux_hwbp_cap* arm_linux_get_hwbp_cap (void) [static, read]
Definition at line 700 of file arm-linux-nat.c.
References arm_linux_hwbp_cap::arch, available, arm_linux_hwbp_cap::bp_count, GET_THREAD_ID, inferior_ptid, arm_linux_hwbp_cap::max_wp_length, ptrace(), PTRACE_GETHBPREGS, and arm_linux_hwbp_cap::wp_count.
Referenced by arm_linux_get_hw_breakpoint_count(), arm_linux_get_hw_watchpoint_count(), arm_linux_hw_watchpoint_initialize(), arm_linux_new_thread(), arm_linux_region_ok_for_hw_watchpoint(), and arm_linux_thread_exit().
static arm_hwbp_type arm_linux_get_hwbp_type (int rw) [static]
Definition at line 916 of file arm-linux-nat.c.
References arm_hwbp_access, arm_hwbp_load, arm_hwbp_store, hw_read, and hw_write.
Referenced by arm_linux_hw_watchpoint_initialize().
static int arm_linux_hw_breakpoint_equal (const struct arm_linux_hw_breakpoint * p1, const struct arm_linux_hw_breakpoint * p2) [static]
Definition at line 947 of file arm-linux-nat.c.
References arm_linux_hw_breakpoint::address, and arm_linux_hw_breakpoint::control.
Referenced by arm_linux_remove_hw_breakpoint1().
static void arm_linux_hw_breakpoint_initialize (struct gdbarch * gdbarch, struct bp_target_info * bp_tgt, struct arm_linux_hw_breakpoint * p) [static]
Definition at line 889 of file arm-linux-nat.c.
References arm_linux_hw_breakpoint::address, arm_hwbp_break, arm_hwbp_control_initialize(), arm_pc_is_thumb(), arm_linux_hw_breakpoint::control, int, and bp_target_info::placed_address.
Referenced by arm_linux_insert_hw_breakpoint(), and arm_linux_remove_hw_breakpoint().
static void arm_linux_hw_watchpoint_initialize (CORE_ADDR addr, int len, int rw, struct arm_linux_hw_breakpoint * p) [static]
Definition at line 929 of file arm-linux-nat.c.
References arm_linux_hw_breakpoint::address, arm_hwbp_control_initialize(), arm_linux_get_hwbp_cap(), arm_linux_get_hwbp_type(), arm_linux_hw_breakpoint::control, gdb_assert, int, len, and arm_linux_hwbp_cap::max_wp_length.
Referenced by arm_linux_insert_watchpoint(), and arm_linux_remove_watchpoint().
static int arm_linux_insert_hw_breakpoint (struct gdbarch * gdbarch, struct bp_target_info * bp_tgt) [static]
Definition at line 1039 of file arm-linux-nat.c.
References ALL_LWPS, arm_linux_get_hw_breakpoint_count(), arm_linux_hw_breakpoint_initialize(), arm_linux_insert_hw_breakpoint1(), lwp_info::ptid, and ptid_get_lwp().
Referenced by _initialize_arm_linux_nat().
static void arm_linux_insert_hw_breakpoint1 (const struct arm_linux_hw_breakpoint * bpt, int tid, int watchpoint) [static]
Definition at line 956 of file arm-linux-nat.c.
References _, arm_linux_hw_breakpoint::address, arm_hwbp_control_is_enabled(), arm_linux_get_hw_breakpoint_count(), arm_linux_get_hw_watchpoint_count(), arm_linux_thread_points::bpts, arm_linux_hw_breakpoint::control, gdb_assert, memcpy(), perror_with_name(), ptrace(), PTRACE_SETHBPREGS, and arm_linux_thread_points::wpts.
Referenced by arm_linux_insert_hw_breakpoint(), arm_linux_insert_watchpoint(), and arm_linux_new_thread().
static int arm_linux_insert_watchpoint (CORE_ADDR addr, int len, int rw, struct expression * cond) [static]
Definition at line 1108 of file arm-linux-nat.c.
References ALL_LWPS, arm_linux_get_hw_watchpoint_count(), arm_linux_hw_watchpoint_initialize(), arm_linux_insert_hw_breakpoint1(), lwp_info::ptid, and ptid_get_lwp().
Referenced by _initialize_arm_linux_nat().
static void arm_linux_new_thread (struct lwp_info * lp) [static]
Definition at line 1191 of file arm-linux-nat.c.
References arm_hwbp_control_is_enabled(), arm_linux_get_hwbp_cap(), arm_linux_insert_hw_breakpoint1(), arm_linux_hwbp_cap::bp_count, arm_linux_thread_points::bpts, arm_linux_hw_breakpoint::control, p, lwp_info::ptid, ptid_get_lwp(), VEC_empty, VEC_last, arm_linux_hwbp_cap::wp_count, and arm_linux_thread_points::wpts.
Referenced by _initialize_arm_linux_nat().
static struct target_desc* arm_linux_read_description (struct target_ops * ops) [static, read]
Definition at line 631 of file arm-linux-nat.c.
References arm_linux_has_wmmx_registers, arm_linux_vfp_register_count, HWCAP_IWMMXT, HWCAP_NEON, HWCAP_VFP, HWCAP_VFPv3, HWCAP_VFPv3D16, inferior_ptid, ptid_get_lwp(), ptrace(), PTRACE_GETVFPREGS, target_auxv_search(), tdesc_arm_with_iwmmxt, tdesc_arm_with_neon, tdesc_arm_with_vfpv2, tdesc_arm_with_vfpv3, and VFP_REGS_SIZE.
Referenced by _initialize_arm_linux_nat().
static int arm_linux_region_ok_for_hw_watchpoint (CORE_ADDR addr, int len) [static]
Definition at line 1076 of file arm-linux-nat.c.
References arm_linux_get_hwbp_cap(), arm_linux_hwbp_cap::max_wp_length, and arm_linux_hwbp_cap::wp_count.
Referenced by _initialize_arm_linux_nat().
static int arm_linux_remove_hw_breakpoint (struct gdbarch * gdbarch, struct bp_target_info * bp_tgt) [static]
Definition at line 1057 of file arm-linux-nat.c.
References ALL_LWPS, arm_linux_get_hw_breakpoint_count(), arm_linux_hw_breakpoint_initialize(), arm_linux_remove_hw_breakpoint1(), lwp_info::ptid, and ptid_get_lwp().
Referenced by _initialize_arm_linux_nat().
static void arm_linux_remove_hw_breakpoint1 (const struct arm_linux_hw_breakpoint * bpt, int tid, int watchpoint) [static]
Definition at line 1000 of file arm-linux-nat.c.
References _, arm_hwbp_control_disable(), arm_linux_get_hw_breakpoint_count(), arm_linux_get_hw_watchpoint_count(), arm_linux_hw_breakpoint_equal(), arm_linux_thread_points::bpts, arm_linux_hw_breakpoint::control, gdb_assert, perror_with_name(), ptrace(), PTRACE_SETHBPREGS, and arm_linux_thread_points::wpts.
Referenced by arm_linux_remove_hw_breakpoint(), and arm_linux_remove_watchpoint().
static int arm_linux_remove_watchpoint (CORE_ADDR addr, int len, int rw, struct expression * cond) [static]
Definition at line 1126 of file arm-linux-nat.c.
References ALL_LWPS, arm_linux_get_hw_watchpoint_count(), arm_linux_hw_watchpoint_initialize(), arm_linux_remove_hw_breakpoint1(), lwp_info::ptid, and ptid_get_lwp().
Referenced by _initialize_arm_linux_nat().
static int arm_linux_stopped_by_watchpoint (void) [static]
Definition at line 1174 of file arm-linux-nat.c.
References arm_linux_stopped_data_address(), and current_target.
Referenced by _initialize_arm_linux_nat().
static int arm_linux_stopped_data_address (struct target_ops * target, CORE_ADDR * addr_p) [static]
Definition at line 1144 of file arm-linux-nat.c.
References arm_linux_get_hw_watchpoint_count(), inferior_ptid, and linux_nat_get_siginfo().
Referenced by _initialize_arm_linux_nat(), and arm_linux_stopped_by_watchpoint().
static void arm_linux_store_inferior_registers (struct target_ops * ops, struct regcache * regcache, int regno) [static]
Definition at line 553 of file arm-linux-nat.c.
References ARM_D0_REGNUM, ARM_F0_REGNUM, ARM_FPS_REGNUM, arm_linux_has_wmmx_registers, arm_linux_vfp_register_count, ARM_PS_REGNUM, ARM_WCGR7_REGNUM, ARM_WR0_REGNUM, store_fpregister(), store_fpregs(), store_register(), store_regs(), store_vfp_regs(), and store_wmmx_regs().
Referenced by _initialize_arm_linux_nat().
static void arm_linux_thread_exit (struct thread_info * tp, int silent) [static]
Definition at line 1221 of file arm-linux-nat.c.
References arm_linux_get_hwbp_cap(), arm_linux_thread_points::bpts, p, thread_info::ptid, ptid_get_lwp(), VEC_iterate, VEC_unordered_remove, arm_linux_thread_points::wpts, and xfree().
Referenced by _initialize_arm_linux_nat().
static int arm_linux_watchpoint_addr_within_range (struct target_ops * target, CORE_ADDR addr, CORE_ADDR start, int length) [static]
Definition at line 1181 of file arm-linux-nat.c.
Referenced by _initialize_arm_linux_nat().
DEF_VEC_P (arm_linux_thread_points_p)
static void fetch_fpregister (struct regcache * regcache, int regno) [static]
Definition at line 95 of file arm-linux-nat.c.
References _, ARM_F0_REGNUM, ARM_F7_REGNUM, ARM_FPS_REGNUM, ARM_LINUX_SIZEOF_NWFPE, GET_THREAD_ID, inferior_ptid, NWFPE_FPSR_OFFSET, ptrace(), regcache_raw_supply(), supply_nwfpe_register(), and warning().
Referenced by arm_linux_fetch_inferior_registers().
static void fetch_fpregs (struct regcache * regcache) [static]
Definition at line 125 of file arm-linux-nat.c.
References _, ARM_F0_REGNUM, ARM_F7_REGNUM, ARM_FPS_REGNUM, ARM_LINUX_SIZEOF_NWFPE, GET_THREAD_ID, inferior_ptid, NWFPE_FPSR_OFFSET, ptrace(), regcache_raw_supply(), supply_nwfpe_register(), and warning().
Referenced by arm_linux_fetch_inferior_registers().
static void fetch_register (struct regcache * regcache, int regno) [static]
Definition at line 228 of file arm-linux-nat.c.
References _, ARM_A1_REGNUM, arm_apcs_32, ARM_CPSR_GREGNUM, ARM_PC_REGNUM, ARM_PS_REGNUM, gdbarch_addr_bits_remove(), get_regcache_arch(), GET_THREAD_ID, inferior_ptid, ptrace(), PTRACE_GETREGS, regcache_raw_supply(), and warning().
Referenced by arm_linux_fetch_inferior_registers().
static void fetch_regs (struct regcache * regcache) [static]
Definition at line 270 of file arm-linux-nat.c.
References _, ARM_A1_REGNUM, arm_apcs_32, ARM_CPSR_GREGNUM, ARM_PC_REGNUM, ARM_PS_REGNUM, gdbarch_addr_bits_remove(), get_regcache_arch(), GET_THREAD_ID, inferior_ptid, ptrace(), PTRACE_GETREGS, regcache_raw_supply(), and warning().
Referenced by arm_linux_fetch_inferior_registers().
static void fetch_vfp_regs (struct regcache * regcache) [static]
Definition at line 460 of file arm-linux-nat.c.
References _, ARM_D0_REGNUM, ARM_FPSCR_REGNUM, arm_linux_vfp_register_count, GET_THREAD_ID, inferior_ptid, ptrace(), PTRACE_GETVFPREGS, regcache_raw_supply(), VFP_REGS_SIZE, and warning().
Referenced by arm_linux_fetch_inferior_registers().
static void fetch_wmmx_regs (struct regcache * regcache) [static]
Definition at line 383 of file arm-linux-nat.c.
References _, ARM_WCGR0_REGNUM, ARM_WCSSF_REGNUM, ARM_WR0_REGNUM, GET_THREAD_ID, inferior_ptid, IWMMXT_REGS_SIZE, ptrace(), PTRACE_GETWMMXREGS, regcache_raw_supply(), and warning().
Referenced by arm_linux_fetch_inferior_registers().
void fill_fpregset (const struct regcache * regcache, gdb_fpregset_t * fpregsetp, int regno)
Definition at line 598 of file arm-linux-nat.c.
References arm_linux_collect_nwfpe().
void fill_gregset (const struct regcache * regcache, gdb_gregset_t * gregsetp, int regno)
Definition at line 585 of file arm-linux-nat.c.
References arm_linux_collect_gregset().
static int get_thread_id (ptid_t ptid) [static]
Definition at line 81 of file arm-linux-nat.c.
References ptid_get_lwp(), and ptid_get_pid().
ps_err_e ps_get_thread_area (const struct ps_prochandle * ph, lwpid_t lwpid, int idx, void ** base)
Definition at line 616 of file arm-linux-nat.c.
References PS_ERR, PS_OK, ptrace(), and PTRACE_GET_THREAD_AREA.
static void store_fpregister (const struct regcache * regcache, int regno) [static]
Definition at line 154 of file arm-linux-nat.c.
References _, ARM_F0_REGNUM, ARM_F7_REGNUM, ARM_FPS_REGNUM, ARM_LINUX_SIZEOF_NWFPE, collect_nwfpe_register(), GET_THREAD_ID, inferior_ptid, NWFPE_FPSR_OFFSET, ptrace(), PTRACE_SETFPREGS, REG_VALID, regcache_raw_collect(), regcache_register_status(), and warning().
Referenced by arm_linux_store_inferior_registers().
static void store_fpregs (const struct regcache * regcache) [static]
Definition at line 191 of file arm-linux-nat.c.
References _, ARM_F0_REGNUM, ARM_F7_REGNUM, ARM_FPS_REGNUM, ARM_LINUX_SIZEOF_NWFPE, collect_nwfpe_register(), GET_THREAD_ID, inferior_ptid, NWFPE_FPSR_OFFSET, ptrace(), PTRACE_SETFPREGS, REG_VALID, regcache_raw_collect(), regcache_register_status(), and warning().
Referenced by arm_linux_store_inferior_registers().
static void store_register (const struct regcache * regcache, int regno) [static]
Definition at line 305 of file arm-linux-nat.c.
References _, ARM_A1_REGNUM, arm_apcs_32, ARM_CPSR_GREGNUM, ARM_PC_REGNUM, ARM_PS_REGNUM, GET_THREAD_ID, inferior_ptid, ptrace(), PTRACE_GETREGS, PTRACE_SETREGS, REG_VALID, regcache_raw_collect(), regcache_register_status(), and warning().
Referenced by arm_linux_store_inferior_registers().
static void store_regs (const struct regcache * regcache) [static]
Definition at line 342 of file arm-linux-nat.c.
References _, ARM_A1_REGNUM, arm_apcs_32, ARM_CPSR_GREGNUM, ARM_PC_REGNUM, ARM_PS_REGNUM, GET_THREAD_ID, inferior_ptid, ptrace(), PTRACE_GETREGS, PTRACE_SETREGS, REG_VALID, regcache_raw_collect(), regcache_register_status(), and warning().
Referenced by arm_linux_store_inferior_registers().
static void store_vfp_regs (const struct regcache * regcache) [static]
Definition at line 484 of file arm-linux-nat.c.
References _, ARM_D0_REGNUM, ARM_FPSCR_REGNUM, arm_linux_vfp_register_count, GET_THREAD_ID, inferior_ptid, ptrace(), PTRACE_GETVFPREGS, PTRACE_SETVFPREGS, regcache_raw_collect(), VFP_REGS_SIZE, and warning().
Referenced by arm_linux_store_inferior_registers().
static void store_wmmx_regs (const struct regcache * regcache) [static]
Definition at line 412 of file arm-linux-nat.c.
References _, ARM_WCGR0_REGNUM, ARM_WCSSF_REGNUM, ARM_WR0_REGNUM, GET_THREAD_ID, inferior_ptid, IWMMXT_REGS_SIZE, ptrace(), PTRACE_GETWMMXREGS, PTRACE_SETWMMXREGS, REG_VALID, regcache_raw_collect(), regcache_register_status(), and warning().
Referenced by arm_linux_store_inferior_registers().
void supply_fpregset (struct regcache * regcache, const gdb_fpregset_t * fpregsetp)
Definition at line 608 of file arm-linux-nat.c.
References arm_linux_supply_nwfpe().
void supply_gregset (struct regcache * regcache, const gdb_gregset_t * gregsetp)
Definition at line 592 of file arm-linux-nat.c.
References arm_linux_supply_gregset().
VEC (arm_linux_thread_points_p)
Definition at line 823 of file arm-linux-nat.c.
References arm_linux_get_hw_breakpoint_count(), arm_linux_get_hw_watchpoint_count(), arm_linux_thread_points::bpts, arm_linux_thread_points::tid, VEC_iterate, VEC_safe_push, arm_linux_thread_points::wpts, xmalloc(), and xzalloc().
Variable Documentation
int arm_apcs_32
Definition at line 279 of file arm-tdep.c.
Referenced by _initialize_arm_tdep(), arm_addr_bits_remove(), arm_get_next_pc_raw(), arm_linux_collect_gregset(), arm_linux_supply_gregset(), arm_supply_gregset(), arm_write_pc(), fetch_register(), fetch_regs(), store_register(), and store_regs().
int arm_linux_has_wmmx_registers [static]
Definition at line 66 of file arm-linux-nat.c.
Referenced by arm_linux_fetch_inferior_registers(), arm_linux_read_description(), and arm_linux_store_inferior_registers().
int arm_linux_vfp_register_count [static]
Definition at line 70 of file arm-linux-nat.c.
Referenced by arm_linux_fetch_inferior_registers(), arm_linux_read_description(), arm_linux_store_inferior_registers(), fetch_vfp_regs(), and store_vfp_regs().