GDB (xrefs): /home/stan/gdb/src/gdb/arm-linux-tdep.h File Reference
/home/stan/gdb/src/gdb/arm-linux-tdep.h File Reference
Defines
#define ARM_LINUX_SIZEOF_NWFPE
#define ARM_CPSR_GREGNUM 16
#define NWFPE_FPSR_OFFSET (8 * FP_REGISTER_SIZE)
#define NWFPE_FPCR_OFFSET (NWFPE_FPSR_OFFSET + INT_REGISTER_SIZE)
#define NWFPE_TAGS_OFFSET (NWFPE_FPCR_OFFSET + INT_REGISTER_SIZE)
#define NWFPE_INITFLAG_OFFSET (NWFPE_TAGS_OFFSET + 8)
#define HWCAP_VFP 64
#define HWCAP_IWMMXT 512
#define HWCAP_NEON 4096
#define HWCAP_VFPv3 8192
#define HWCAP_VFPv3D16 16384
Functions
void arm_linux_supply_gregset (const struct regset *regset, struct regcache *regcache, int regnum, const void *gregs_buf, size_t len)
void arm_linux_collect_gregset (const struct regset *regset, const struct regcache *regcache, int regnum, void *gregs_buf, size_t len)
void supply_nwfpe_register (struct regcache *regcache, int regno, const gdb_byte *regs)
void collect_nwfpe_register (const struct regcache *regcache, int regno, gdb_byte *regs)
void arm_linux_supply_nwfpe (const struct regset *regset, struct regcache *regcache, int regnum, const void *regs_buf, size_t len)
void arm_linux_collect_nwfpe (const struct regset *regset, const struct regcache *regcache, int regnum, void *regs_buf, size_t len)
Define Documentation
#define ARM_CPSR_GREGNUM 16
Definition at line 28 of file arm-linux-tdep.h.
Referenced by arm_linux_collect_gregset(), arm_linux_supply_gregset(), fetch_register(), fetch_regs(), store_register(), and store_regs().
#define ARM_LINUX_SIZEOF_NWFPE
Value:
(8 * FP_REGISTER_SIZE \
                                + 2 * INT_REGISTER_SIZE \
                                + 8 + INT_REGISTER_SIZE)
Definition at line 23 of file arm-linux-tdep.h.
Referenced by arm_linux_regset_from_core_section(), fetch_fpregister(), fetch_fpregs(), store_fpregister(), and store_fpregs().
#define HWCAP_IWMMXT 512
Definition at line 65 of file arm-linux-tdep.h.
Referenced by arm_linux_read_description().
#define HWCAP_NEON 4096
Definition at line 66 of file arm-linux-tdep.h.
Referenced by arm_linux_core_read_description(), and arm_linux_read_description().
#define HWCAP_VFP 64
Definition at line 64 of file arm-linux-tdep.h.
Referenced by arm_linux_core_read_description(), and arm_linux_read_description().
#define HWCAP_VFPv3 8192
Definition at line 67 of file arm-linux-tdep.h.
Referenced by arm_linux_core_read_description(), and arm_linux_read_description().
#define HWCAP_VFPv3D16 16384
Definition at line 68 of file arm-linux-tdep.h.
Referenced by arm_linux_core_read_description(), and arm_linux_read_description().
#define NWFPE_FPCR_OFFSET (NWFPE_FPSR_OFFSET + INT_REGISTER_SIZE)
Definition at line 39 of file arm-linux-tdep.h.
#define NWFPE_FPSR_OFFSET (8 * FP_REGISTER_SIZE)
Definition at line 38 of file arm-linux-tdep.h.
Referenced by arm_linux_supply_nwfpe(), fetch_fpregister(), fetch_fpregs(), store_fpregister(), and store_fpregs().
#define NWFPE_INITFLAG_OFFSET (NWFPE_TAGS_OFFSET + 8)
Definition at line 41 of file arm-linux-tdep.h.
#define NWFPE_TAGS_OFFSET (NWFPE_FPCR_OFFSET + INT_REGISTER_SIZE)
Definition at line 40 of file arm-linux-tdep.h.
Referenced by collect_nwfpe_register(), and supply_nwfpe_register().
Function Documentation
void arm_linux_collect_gregset (const struct regset * regset, const struct regcache * regcache, int regnum, void * gregs_buf, size_t len)
Definition at line 508 of file arm-linux-tdep.c.
References ARM_A1_REGNUM, arm_apcs_32, ARM_CPSR_GREGNUM, ARM_PC_REGNUM, ARM_PS_REGNUM, INT_REGISTER_SIZE, and regcache_raw_collect().
Referenced by arm_linux_regset_from_core_section(), and fill_gregset().
void arm_linux_collect_nwfpe (const struct regset * regset, const struct regcache * regcache, int regnum, void * regs_buf, size_t len)
Definition at line 632 of file arm-linux-tdep.c.
References ARM_F0_REGNUM, ARM_F7_REGNUM, ARM_FPS_REGNUM, collect_nwfpe_register(), INT_REGISTER_SIZE, and regcache_raw_collect().
Referenced by arm_linux_regset_from_core_section(), and fill_fpregset().
void arm_linux_supply_gregset (const struct regset * regset, struct regcache * regcache, int regnum, const void * gregs_buf, size_t len)
Definition at line 470 of file arm-linux-tdep.c.
References ARM_A1_REGNUM, arm_apcs_32, ARM_CPSR_GREGNUM, ARM_PC_REGNUM, ARM_PS_REGNUM, gdbarch::byte_order, extract_unsigned_integer(), gdbarch_addr_bits_remove(), gdbarch_byte_order(), get_regcache_arch(), INT_REGISTER_SIZE, regcache_raw_supply(), and store_unsigned_integer().
Referenced by arm_linux_regset_from_core_section(), and supply_gregset().
void arm_linux_supply_nwfpe (const struct regset * regset, struct regcache * regcache, int regnum, const void * regs_buf, size_t len)
Definition at line 615 of file arm-linux-tdep.c.
References ARM_F0_REGNUM, ARM_F7_REGNUM, ARM_FPS_REGNUM, NWFPE_FPSR_OFFSET, regcache_raw_supply(), and supply_nwfpe_register().
Referenced by arm_linux_regset_from_core_section(), and supply_fpregset().
void collect_nwfpe_register (const struct regcache * regcache, int regno, gdb_byte * regs)
Definition at line 578 of file arm-linux-tdep.c.
References ARM_F0_REGNUM, FP_REGISTER_SIZE, memcpy(), NWFPE_TAGS_OFFSET, regcache_raw_collect(), typeDouble, typeExtended, and typeSingle.
Referenced by arm_linux_collect_nwfpe(), store_fpregister(), and store_fpregs().
void supply_nwfpe_register (struct regcache * regcache, int regno, const gdb_byte * regs)
Definition at line 543 of file arm-linux-tdep.c.
References ARM_F0_REGNUM, FP_REGISTER_SIZE, memcpy(), memset(), NWFPE_TAGS_OFFSET, regcache_raw_supply(), typeDouble, typeExtended, and typeSingle.
Referenced by arm_linux_supply_nwfpe(), fetch_fpregister(), and fetch_fpregs().