GDB (xrefs): /home/stan/gdb/src/gdb/armbsd-tdep.c File Reference
/home/stan/gdb/src/gdb/armbsd-tdep.c File Reference
#include "defs.h"
#include "osabi.h"
#include "regcache.h"
#include "regset.h"
#include "gdb_assert.h"
#include "gdb_string.h"
#include "arm-tdep.h"
Defines
#define ARMBSD_SIZEOF_GREGS (17 * 4)
#define ARMBSD_SIZEOF_FPREGS ((1 + (8 * 3)) * 4)
Functions
static int armbsd_fpreg_offset (int regnum)
static void armbsd_supply_fpregset (const struct regset *regset, struct regcache *regcache, int regnum, const void *fpregs, size_t len)
static void armbsd_supply_gregset (const struct regset *regset, struct regcache *regcache, int regnum, const void *gregs, size_t len)
struct regset * armbsd_regset_from_core_section (struct gdbarch *gdbarch, const char *sect_name, size_t sect_size)
Variables
static struct regset armbsd_gregset
static struct regset armbsd_fpregset
Define Documentation
#define ARMBSD_SIZEOF_FPREGS ((1 + (8 * 3)) * 4)
Definition at line 36 of file armbsd-tdep.c.
Referenced by armbsd_regset_from_core_section(), armbsd_supply_fpregset(), and armbsd_supply_gregset().
#define ARMBSD_SIZEOF_GREGS (17 * 4)
Definition at line 33 of file armbsd-tdep.c.
Referenced by armbsd_regset_from_core_section(), and armbsd_supply_gregset().
Function Documentation
static int armbsd_fpreg_offset (int regnum) [static]
Definition at line 39 of file armbsd-tdep.c.
References ARM_F0_REGNUM, and ARM_FPS_REGNUM.
Referenced by armbsd_supply_fpregset().
struct regset* armbsd_regset_from_core_section (struct gdbarch * gdbarch, const char * sect_name, size_t sect_size) [read]
Definition at line 117 of file armbsd-tdep.c.
References armbsd_fpregset, armbsd_gregset, ARMBSD_SIZEOF_FPREGS, and ARMBSD_SIZEOF_GREGS.
Referenced by armobsd_init_abi().
static void armbsd_supply_fpregset (const struct regset * regset, struct regcache * regcache, int regnum, const void * fpregs, size_t len) [static]
Definition at line 52 of file armbsd-tdep.c.
References ARM_F0_REGNUM, ARM_FPS_REGNUM, armbsd_fpreg_offset(), ARMBSD_SIZEOF_FPREGS, gdb_assert, regcache_raw_supply(), and gdbarch_tdep::regs.
Referenced by armbsd_supply_gregset().
static void armbsd_supply_gregset (const struct regset * regset, struct regcache * regcache, int regnum, const void * gregs, size_t len) [static]
Definition at line 73 of file armbsd-tdep.c.
References ARM_A1_REGNUM, ARM_PC_REGNUM, ARM_PS_REGNUM, ARMBSD_SIZEOF_FPREGS, ARMBSD_SIZEOF_GREGS, armbsd_supply_fpregset(), gdb_assert, regcache_raw_supply(), and gdbarch_tdep::regs.
Variable Documentation
struct regset armbsd_fpregset [static]
Initial value:
{
  NULL,
  armbsd_supply_fpregset
}
Definition at line 107 of file armbsd-tdep.c.
Referenced by armbsd_regset_from_core_section().
struct regset armbsd_gregset [static]
Initial value:
{
  NULL,
  armbsd_supply_gregset
}
Definition at line 101 of file armbsd-tdep.c.
Referenced by armbsd_regset_from_core_section().