GDB (xrefs): /home/stan/gdb/src/gdb/armnbsd-nat.c File Reference
/home/stan/gdb/src/gdb/armnbsd-nat.c File Reference
#include "defs.h"
#include "gdbcore.h"
#include "inferior.h"
#include "regcache.h"
#include "target.h"
#include "gdb_string.h"
#include <sys/types.h>
#include <sys/ptrace.h>
#include <machine/reg.h>
#include <machine/frame.h>
#include "arm-tdep.h"
#include "inf-ptrace.h"
Classes
struct md_core
Functions
static void arm_supply_gregset (struct regcache *regcache, struct reg *gregset)
static void arm_supply_fparegset (struct regcache *regcache, struct fpreg *fparegset)
static void fetch_register (struct regcache *regcache, int regno)
static void fetch_regs (struct regcache *regcache)
static void fetch_fp_register (struct regcache *regcache, int regno)
static void fetch_fp_regs (struct regcache *regcache)
static void armnbsd_fetch_registers (struct target_ops *ops, struct regcache *regcache, int regno)
static void store_register (const struct regcache *regcache, int regno)
static void store_regs (const struct regcache *regcache)
static void store_fp_register (const struct regcache *regcache, int regno)
static void store_fp_regs (const struct regcache *regcache)
static void armnbsd_store_registers (struct target_ops *ops, struct regcache *regcache, int regno)
static void fetch_core_registers (struct regcache *regcache, char *core_reg_sect, unsigned core_reg_size, int which, CORE_ADDR ignore)
static void fetch_elfcore_registers (struct regcache *regcache, char *core_reg_sect, unsigned core_reg_size, int which, CORE_ADDR ignore)
void _initialize_arm_netbsd_nat (void)
Variables
int arm_apcs_32
static struct core_fns arm_netbsd_core_fns
static struct core_fns arm_netbsd_elfcore_fns
Function Documentation
void _initialize_arm_netbsd_nat (void)
Definition at line 492 of file armnbsd-nat.c.
References add_target(), armnbsd_fetch_registers(), armnbsd_store_registers(), deprecated_add_core_fns(), inf_ptrace_target(), target_ops::to_fetch_registers, and target_ops::to_store_registers.
static void arm_supply_fparegset (struct regcache * regcache, struct fpreg * fparegset) [static]
Definition at line 64 of file armnbsd-nat.c.
References ARM_F0_REGNUM, ARM_F7_REGNUM, ARM_FPS_REGNUM, and regcache_raw_supply().
Referenced by fetch_core_registers(), fetch_elfcore_registers(), and fetch_fp_regs().
static void arm_supply_gregset (struct regcache * regcache, struct reg * gregset) [static]
Definition at line 38 of file armnbsd-nat.c.
References ARM_A1_REGNUM, arm_apcs_32, ARM_LR_REGNUM, ARM_PC_REGNUM, ARM_PS_REGNUM, ARM_SP_REGNUM, gdbarch_addr_bits_remove(), get_regcache_arch(), and regcache_raw_supply().
Referenced by fetch_core_registers(), fetch_elfcore_registers(), and fetch_regs().
static void armnbsd_fetch_registers (struct target_ops * ops, struct regcache * regcache, int regno) [static]
Definition at line 196 of file armnbsd-nat.c.
References ARM_FPS_REGNUM, fetch_fp_register(), fetch_fp_regs(), fetch_register(), and fetch_regs().
Referenced by _initialize_arm_netbsd_nat().
static void armnbsd_store_registers (struct target_ops * ops, struct regcache * regcache, int regno) [static]
Definition at line 397 of file armnbsd-nat.c.
References ARM_FPS_REGNUM, store_fp_register(), store_fp_regs(), store_register(), and store_regs().
Referenced by _initialize_arm_netbsd_nat().
static void fetch_core_registers (struct regcache * regcache, char * core_reg_sect, unsigned core_reg_size, int which, CORE_ADDR ignore) [static]
Definition at line 421 of file armnbsd-nat.c.
References arm_supply_fparegset(), arm_supply_gregset(), md_core::freg, and md_core::intreg.
static void fetch_elfcore_registers (struct regcache * regcache, char * core_reg_sect, unsigned core_reg_size, int which, CORE_ADDR ignore) [static]
Definition at line 434 of file armnbsd-nat.c.
References _, arm_supply_fparegset(), arm_supply_gregset(), memcpy(), and warning().
static void fetch_fp_register (struct regcache * regcache, int regno) [static]
Definition at line 148 of file armnbsd-nat.c.
References _, ARM_F0_REGNUM, ARM_FPS_REGNUM, inferior_ptid, ptid_get_pid(), ptrace(), PTRACE_TYPE_ARG3, regcache_raw_supply(), and warning().
Referenced by armnbsd_fetch_registers().
static void fetch_fp_regs (struct regcache * regcache) [static]
Definition at line 177 of file armnbsd-nat.c.
References _, arm_supply_fparegset(), inferior_ptid, ptid_get_pid(), ptrace(), PTRACE_TYPE_ARG3, and warning().
Referenced by armnbsd_fetch_registers().
static void fetch_register (struct regcache * regcache, int regno) [static]
Definition at line 77 of file armnbsd-nat.c.
References _, arm_apcs_32, ARM_LR_REGNUM, ARM_PC_REGNUM, ARM_PS_REGNUM, ARM_SP_REGNUM, gdbarch_addr_bits_remove(), get_regcache_arch(), inferior_ptid, ptid_get_pid(), ptrace(), PTRACE_TYPE_ARG3, regcache_raw_supply(), and warning().
Referenced by armnbsd_fetch_registers().
static void fetch_regs (struct regcache * regcache) [static]
Definition at line 129 of file armnbsd-nat.c.
References _, arm_supply_gregset(), inferior_ptid, ptid_get_pid(), ptrace(), PTRACE_TYPE_ARG3, and warning().
Referenced by armnbsd_fetch_registers().
static void store_fp_register (const struct regcache * regcache, int regno) [static]
Definition at line 340 of file armnbsd-nat.c.
References _, ARM_F0_REGNUM, ARM_FPS_REGNUM, inferior_ptid, ptid_get_pid(), ptrace(), PTRACE_TYPE_ARG3, regcache_raw_collect(), and warning().
Referenced by armnbsd_store_registers().
static void store_fp_regs (const struct regcache * regcache) [static]
Definition at line 375 of file armnbsd-nat.c.
References _, ARM_F0_REGNUM, ARM_F7_REGNUM, ARM_FPS_REGNUM, inferior_ptid, ptid_get_pid(), ptrace(), PTRACE_TYPE_ARG3, regcache_raw_collect(), and warning().
Referenced by armnbsd_store_registers().
static void store_register (const struct regcache * regcache, int regno) [static]
Definition at line 215 of file armnbsd-nat.c.
References _, arm_apcs_32, ARM_LR_REGNUM, ARM_PC_REGNUM, ARM_PS_REGNUM, ARM_SP_REGNUM, gdbarch_addr_bits_remove(), get_regcache_arch(), inferior_ptid, ptid_get_pid(), ptrace(), PTRACE_TYPE_ARG3, regcache_raw_collect(), and warning().
Referenced by armnbsd_store_registers().
static void store_regs (const struct regcache * regcache) [static]
Definition at line 292 of file armnbsd-nat.c.
References _, ARM_A1_REGNUM, arm_apcs_32, ARM_LR_REGNUM, ARM_PC_REGNUM, ARM_PS_REGNUM, ARM_SP_REGNUM, gdbarch_addr_bits_remove(), get_regcache_arch(), inferior_ptid, ptid_get_pid(), ptrace(), PTRACE_TYPE_ARG3, regcache_raw_collect(), and warning().
Referenced by armnbsd_store_registers().
Variable Documentation
int arm_apcs_32
Definition at line 279 of file arm-tdep.c.
struct core_fns arm_netbsd_core_fns [static]
Initial value:
{
  bfd_target_unknown_flavour,
  default_check_format,
  default_core_sniffer,
  fetch_core_registers,
  NULL
}
Definition at line 473 of file armnbsd-nat.c.
struct core_fns arm_netbsd_elfcore_fns [static]
Initial value:
{
  bfd_target_elf_flavour,
  default_check_format,
  default_core_sniffer,
  fetch_elfcore_registers,
  NULL
}
Definition at line 482 of file armnbsd-nat.c.