GDB (xrefs): /home/stan/gdb/src/gdb/armnbsd-tdep.c File Reference
/home/stan/gdb/src/gdb/armnbsd-tdep.c File Reference
#include "defs.h"
#include "osabi.h"
#include "gdb_string.h"
#include "arm-tdep.h"
#include "solib-svr4.h"
Defines
#define ARM_NBSD_JB_PC 24
#define ARM_NBSD_JB_ELEMENT_SIZE INT_REGISTER_SIZE
Functions
static void arm_netbsd_init_abi_common (struct gdbarch_info info, struct gdbarch *gdbarch)
static void arm_netbsd_aout_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
static void arm_netbsd_elf_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
static enum gdb_osabi arm_netbsd_aout_osabi_sniffer (bfd *abfd)
void _initialize_arm_netbsd_tdep (void)
Variables
static const gdb_byte arm_nbsd_arm_le_breakpoint [] = {0x11, 0x00, 0x00, 0xe6}
static const gdb_byte arm_nbsd_arm_be_breakpoint [] = {0xe6, 0x00, 0x00, 0x11}
static const gdb_byte arm_nbsd_thumb_le_breakpoint [] = {0xfe, 0xde}
static const gdb_byte arm_nbsd_thumb_be_breakpoint [] = {0xde, 0xfe}
initialize_file_ftype _initialize_arm_netbsd_tdep
Define Documentation
#define ARM_NBSD_JB_ELEMENT_SIZE INT_REGISTER_SIZE
Definition at line 30 of file armnbsd-tdep.c.
Referenced by arm_netbsd_init_abi_common().
#define ARM_NBSD_JB_PC 24
Definition at line 29 of file armnbsd-tdep.c.
Referenced by arm_netbsd_init_abi_common().
Function Documentation
void _initialize_arm_netbsd_tdep (void)
Definition at line 113 of file armnbsd-tdep.c.
References _initialize_arm_netbsd_tdep, arm_netbsd_aout_init_abi(), arm_netbsd_aout_osabi_sniffer(), arm_netbsd_elf_init_abi(), GDB_OSABI_NETBSD_AOUT, GDB_OSABI_NETBSD_ELF, gdbarch_register_osabi(), and gdbarch_register_osabi_sniffer().
static void arm_netbsd_aout_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch) [static]
Definition at line 75 of file armnbsd-tdep.c.
References ARM_FLOAT_AUTO, ARM_FLOAT_SOFT_FPA, arm_netbsd_init_abi_common(), gdbarch_tdep::fp_model, and gdbarch_tdep().
Referenced by _initialize_arm_netbsd_tdep().
static enum gdb_osabi arm_netbsd_aout_osabi_sniffer (bfd * abfd) [static]
Definition at line 101 of file armnbsd-tdep.c.
References GDB_OSABI_NETBSD_AOUT, and GDB_OSABI_UNKNOWN.
Referenced by _initialize_arm_netbsd_tdep().
static void arm_netbsd_elf_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch) [static]
Definition at line 86 of file armnbsd-tdep.c.
References ARM_FLOAT_AUTO, ARM_FLOAT_SOFT_VFP, arm_netbsd_init_abi_common(), gdbarch_tdep::fp_model, gdbarch_tdep(), set_solib_svr4_fetch_link_map_offsets(), and svr4_ilp32_fetch_link_map_offsets().
Referenced by _initialize_arm_netbsd_tdep().
static void arm_netbsd_init_abi_common (struct gdbarch_info info, struct gdbarch * gdbarch) [static]
Definition at line 40 of file armnbsd-tdep.c.
References _, gdbarch_tdep::arm_breakpoint, gdbarch_tdep::arm_breakpoint_size, arm_nbsd_arm_be_breakpoint, arm_nbsd_arm_le_breakpoint, ARM_NBSD_JB_ELEMENT_SIZE, ARM_NBSD_JB_PC, arm_nbsd_thumb_be_breakpoint, arm_nbsd_thumb_le_breakpoint, arm_software_single_step(), gdbarch_info::byte_order, gdbarch_tdep(), internal_error(), gdbarch_tdep::jb_elt_size, gdbarch_tdep::jb_pc, gdbarch_tdep::lowest_pc, set_gdbarch_software_single_step(), gdbarch_tdep::thumb_breakpoint, and gdbarch_tdep::thumb_breakpoint_size.
Referenced by arm_netbsd_aout_init_abi(), and arm_netbsd_elf_init_abi().
Variable Documentation
initialize_file_ftype _initialize_arm_netbsd_tdep
Referenced by _initialize_arm_netbsd_tdep(), and initialize_all_files().
const gdb_byte arm_nbsd_arm_be_breakpoint[] = {0xe6, 0x00, 0x00, 0x11} [static]
Definition at line 35 of file armnbsd-tdep.c.
Referenced by arm_netbsd_init_abi_common().
const gdb_byte arm_nbsd_arm_le_breakpoint[] = {0x11, 0x00, 0x00, 0xe6} [static]
Definition at line 34 of file armnbsd-tdep.c.
Referenced by arm_netbsd_init_abi_common().
const gdb_byte arm_nbsd_thumb_be_breakpoint[] = {0xde, 0xfe} [static]
Definition at line 37 of file armnbsd-tdep.c.
Referenced by arm_netbsd_init_abi_common().
const gdb_byte arm_nbsd_thumb_le_breakpoint[] = {0xfe, 0xde} [static]
Definition at line 36 of file armnbsd-tdep.c.
Referenced by arm_netbsd_init_abi_common().