GDB (xrefs): /home/stan/gdb/src/gdb/armobsd-tdep.c File Reference
/home/stan/gdb/src/gdb/armobsd-tdep.c File Reference
#include "defs.h"
#include "osabi.h"
#include "trad-frame.h"
#include "tramp-frame.h"
#include "gdb_string.h"
#include "obsd-tdep.h"
#include "arm-tdep.h"
#include "solib-svr4.h"
Functions
static void armobsd_sigframe_init (const struct tramp_frame *self, struct frame_info *this_frame, struct trad_frame_cache *cache, CORE_ADDR func)
static void armobsd_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
static enum gdb_osabi armobsd_core_osabi_sniffer (bfd *abfd)
void _initialize_armobsd_tdep (void)
Variables
static struct tramp_frame armobsd_sigframe
static const gdb_byte arm_obsd_thumb_le_breakpoint [] = {0xfe, 0xdf}
static const gdb_byte arm_obsd_thumb_be_breakpoint [] = {0xdf, 0xfe}
initialize_file_ftype _initialize_armobsd_tdep
Function Documentation
void _initialize_armobsd_tdep (void)
Definition at line 134 of file armobsd-tdep.c.
References _initialize_armobsd_tdep, armobsd_core_osabi_sniffer(), armobsd_init_abi(), GDB_OSABI_OPENBSD_ELF, gdbarch_register_osabi(), and gdbarch_register_osabi_sniffer().
static enum gdb_osabi armobsd_core_osabi_sniffer (bfd * abfd) [static]
Definition at line 122 of file armobsd-tdep.c.
References GDB_OSABI_OPENBSD_ELF, and GDB_OSABI_UNKNOWN.
Referenced by _initialize_armobsd_tdep().
static void armobsd_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch) [static]
Definition at line 78 of file armobsd-tdep.c.
References ARM_FLOAT_AUTO, ARM_FLOAT_SOFT_VFP, arm_obsd_thumb_be_breakpoint, arm_obsd_thumb_le_breakpoint, arm_software_single_step(), armbsd_regset_from_core_section(), gdbarch_info::byte_order, gdbarch_tdep::fp_model, gdbarch_tdep(), gdbarch_tdep::jb_elt_size, gdbarch_tdep::jb_pc, obsd_skip_solib_resolver(), pcc_struct_return, set_gdbarch_regset_from_core_section(), set_gdbarch_skip_solib_resolver(), set_gdbarch_software_single_step(), set_solib_svr4_fetch_link_map_offsets(), gdbarch_tdep::struct_return, svr4_ilp32_fetch_link_map_offsets(), gdbarch_tdep::thumb_breakpoint, gdbarch_tdep::thumb_breakpoint_size, and tramp_frame_prepend_unwinder().
Referenced by _initialize_armobsd_tdep().
static void armobsd_sigframe_init (const struct tramp_frame * self, struct frame_info * this_frame, struct trad_frame_cache * cache, CORE_ADDR func) [static]
Definition at line 34 of file armobsd-tdep.c.
References ARM_A1_REGNUM, ARM_LR_REGNUM, ARM_PC_REGNUM, ARM_SP_REGNUM, frame_id_build(), get_frame_register_signed(), regnum, gdbarch_tdep::sigcontext_addr, gdbarch_tdep::sp, trad_frame_set_id(), and trad_frame_set_reg_addr().
Variable Documentation
initialize_file_ftype _initialize_armobsd_tdep
Referenced by _initialize_armobsd_tdep(), and initialize_all_files().
const gdb_byte arm_obsd_thumb_be_breakpoint[] = {0xdf, 0xfe} [static]
Definition at line 75 of file armobsd-tdep.c.
Referenced by armobsd_init_abi().
const gdb_byte arm_obsd_thumb_le_breakpoint[] = {0xfe, 0xdf} [static]
Definition at line 74 of file armobsd-tdep.c.
Referenced by armobsd_init_abi().
struct tramp_frame armobsd_sigframe [static]
Initial value:
{
  SIGTRAMP_FRAME,
  4,
  {
    { 0xe28d0010, -1 },
    { 0xef000067, -1 },
    { 0xef000001, -1 },
    { 0xeafffffc, -1 },
    { TRAMP_SENTINEL_INSN, -1 }
  },
  armobsd_sigframe_init
}
Definition at line 58 of file armobsd-tdep.c.