GDB (xrefs): /home/stan/gdb/src/gdb/auto-load.h File Reference
/home/stan/gdb/src/gdb/auto-load.h File Reference
Classes
struct script_language
Functions
struct auto_load_pspace_info * get_auto_load_pspace_data_for_loading (struct program_space *pspace)
int maybe_add_script (struct auto_load_pspace_info *pspace_info, int loaded, const char *name, const char *full_path, const struct script_language *language)
void auto_load_objfile_script (struct objfile *objfile, const struct script_language *language)
void load_auto_scripts_for_objfile (struct objfile *objfile)
int script_not_found_warning_print (struct auto_load_pspace_info *pspace_info)
void auto_load_info_scripts (char *pattern, int from_tty, const struct script_language *language)
struct cmd_list_element ** auto_load_set_cmdlist_get (void)
struct cmd_list_element ** auto_load_show_cmdlist_get (void)
struct cmd_list_element ** auto_load_info_cmdlist_get (void)
int file_is_auto_load_safe (const char *filename, const char *debug_fmt,...)
Variables
int global_auto_load
int auto_load_local_gdbinit
char * auto_load_local_gdbinit_pathname
int auto_load_local_gdbinit_loaded
char auto_load_info_scripts_pattern_nl []
Function Documentation
struct cmd_list_element** auto_load_info_cmdlist_get (void) [read]
Definition at line 1172 of file auto-load.c.
References _, add_prefix_cmd(), class_info, info_auto_load_cmd(), and infolist.
Referenced by _initialize_thread_db(), and info_auto_load_cmd().
void auto_load_info_scripts (char * pattern, int from_tty, const struct script_language * language)
Definition at line 945 of file auto-load.c.
References _, auto_load_info_scripts_pattern_nl, collect_matching_scripts(), current_program_space, current_uiout, do_cleanups(), dont_repeat(), error(), get_auto_load_pspace_data(), auto_load_pspace_info::loaded_scripts, make_cleanup(), make_cleanup_ui_out_table_begin_end(), print_script(), qsort, re_comp(), sort_scripts_by_name(), ui_left, ui_out_message(), ui_out_table_body(), ui_out_table_header(), ui_out_text(), VEC, VEC_address, VEC_alloc, VEC_cleanup, VEC_iterate, and VEC_length.
Referenced by info_auto_load_gdb_scripts().
void auto_load_objfile_script (struct objfile * objfile, const struct script_language * language)
Definition at line 809 of file auto-load.c.
References _, auto_load_objfile_script_1(), debug_auto_load, do_cleanups(), fprintf_unfiltered(), gdb_realpath(), gdb_stdlog, len, make_cleanup(), objfile_name(), and xfree().
Referenced by load_auto_scripts_for_objfile().
struct cmd_list_element** auto_load_set_cmdlist_get (void) [read]
Definition at line 1094 of file auto-load.c.
References _, add_prefix_cmd(), class_maintenance, set_auto_load_cmd(), and setlist.
Referenced by _initialize_thread_db(), and set_auto_load_cmd().
struct cmd_list_element** auto_load_show_cmdlist_get (void) [read]
Definition at line 1121 of file auto-load.c.
References _, add_prefix_cmd(), class_maintenance, show_auto_load_cmd(), and showlist.
Referenced by _initialize_thread_db(), and show_auto_load_cmd().
int file_is_auto_load_safe (const char * filename, const char * debug_fmt, ...)
Definition at line 441 of file auto-load.c.
References _, auto_load_safe_path, auto_load_safe_path_vec_update(), debug_auto_load, do_cleanups(), filename_is_in_auto_load_safe_path_vec(), free_current_contents(), gdb_stdlog, gdbinit, make_cleanup(), printf_filtered(), vfprintf_unfiltered(), warning(), xfree(), and xstrprintf().
Referenced by captured_main(), source_gdb_script_for_objfile(), try_thread_db_load_from_dir(), and try_thread_db_load_from_pdir_1().
struct auto_load_pspace_info* get_auto_load_pspace_data_for_loading (struct program_space * pspace) [read]
Definition at line 647 of file auto-load.c.
References get_auto_load_pspace_data(), init_loaded_scripts_info(), and auto_load_pspace_info::loaded_scripts.
Referenced by source_gdb_script_for_objfile().
void load_auto_scripts_for_objfile (struct objfile * objfile)
Definition at line 841 of file auto-load.c.
References auto_load_gdb_scripts, auto_load_objfile_script(), objfile::flags, gdbpy_load_auto_scripts_for_objfile(), global_auto_load, OBJF_NOT_FILENAME, and script_language_gdb.
Referenced by auto_load_new_objfile(), and captured_main().
int maybe_add_script (struct auto_load_pspace_info * pspace_info, int loaded, const char * name, const char * full_path, const struct script_language * language)
Definition at line 664 of file auto-load.c.
References loaded_script::language, auto_load_pspace_info::loaded_scripts, name, loaded_script::name, p, and xmalloc().
Referenced by source_gdb_script_for_objfile().
int script_not_found_warning_print (struct auto_load_pspace_info * pspace_info)
Definition at line 1052 of file auto-load.c.
References auto_load_pspace_info::script_not_found_warning_printed.
Variable Documentation
char auto_load_info_scripts_pattern_nl[]
Definition at line 938 of file auto-load.c.
Referenced by auto_load_info_scripts(), info_auto_load_cmd(), and info_auto_load_libthread_db().
int auto_load_local_gdbinit
Definition at line 95 of file auto-load.c.
Referenced by captured_main().
int auto_load_local_gdbinit_loaded
Definition at line 101 of file auto-load.c.
Referenced by captured_main(), and info_auto_load_local_gdbinit().
char* auto_load_local_gdbinit_pathname
Definition at line 98 of file auto-load.c.
Referenced by captured_main(), and info_auto_load_local_gdbinit().
int global_auto_load
Definition at line 92 of file auto-load.c.
Referenced by captured_main(), and load_auto_scripts_for_objfile().