GDB (xrefs): /home/stan/gdb/src/gdb/auxv.c File Reference
/home/stan/gdb/src/gdb/auxv.c File Reference
#include "defs.h"
#include "target.h"
#include "gdbtypes.h"
#include "command.h"
#include "inferior.h"
#include "valprint.h"
#include "gdb_assert.h"
#include "gdbcore.h"
#include "observer.h"
#include "filestuff.h"
#include "auxv.h"
#include "elf/common.h"
#include <unistd.h>
#include <fcntl.h>
Classes
struct auxv_info
Defines
#define TAG(tag, text, kind) case tag: name = #tag; description = text; flavor = kind; break
Functions
static LONGEST procfs_xfer_auxv (gdb_byte *readbuf, const gdb_byte *writebuf, ULONGEST offset, LONGEST len)
static LONGEST ld_so_xfer_auxv (gdb_byte *readbuf, const gdb_byte *writebuf, ULONGEST offset, LONGEST len)
LONGEST memory_xfer_auxv (struct target_ops *ops, enum target_object object, const char *annex, gdb_byte *readbuf, const gdb_byte *writebuf, ULONGEST offset, LONGEST len)
static int default_auxv_parse (struct target_ops *ops, gdb_byte **readptr, gdb_byte *endptr, CORE_ADDR *typep, CORE_ADDR *valp)
int target_auxv_parse (struct target_ops *ops, gdb_byte **readptr, gdb_byte *endptr, CORE_ADDR *typep, CORE_ADDR *valp)
static void auxv_inferior_data_cleanup (struct inferior *inf, void *arg)
static void invalidate_auxv_cache_inf (struct inferior *inf)
static void invalidate_auxv_cache (void)
static struct auxv_info * get_auxv_inferior_data (struct target_ops *ops)
int target_auxv_search (struct target_ops *ops, CORE_ADDR match, CORE_ADDR *valp)
int fprint_target_auxv (struct ui_file *file, struct target_ops *ops)
static void info_auxv_command (char *cmd, int from_tty)
void _initialize_auxv (void)
Variables
static struct inferior_data * auxv_inferior_data
initialize_file_ftype _initialize_auxv
Define Documentation
#define TAG (tag, text, kind) case tag: name = #tag; description = text; flavor = kind; break
Referenced by fprint_target_auxv().
Function Documentation
void _initialize_auxv (void)
Definition at line 526 of file auxv.c.
References _, _initialize_auxv, add_info(), auxv_inferior_data, auxv_inferior_data_cleanup(), info_auxv_command(), invalidate_auxv_cache(), invalidate_auxv_cache_inf(), observer_attach_executable_changed(), observer_attach_inferior_appeared(), and observer_attach_inferior_exit().
static void auxv_inferior_data_cleanup (struct inferior * inf, void * arg) [static]
Definition at line 302 of file auxv.c.
References auxv_inferior_data, auxv_info::data, and xfree().
Referenced by _initialize_auxv(), and invalidate_auxv_cache_inf().
static int default_auxv_parse (struct target_ops * ops, gdb_byte ** readptr, gdb_byte * endptr, CORE_ADDR * typep, CORE_ADDR * valp) [static]
Definition at line 241 of file auxv.c.
References extract_unsigned_integer(), gdbarch_byte_order(), gdbarch_ptr_bit(), and target_gdbarch().
Referenced by target_auxv_parse().
int fprint_target_auxv (struct ui_file * file, struct target_ops * ops)
Definition at line 395 of file auxv.c.
References _, value_print_options::addressprint, auxv_info::data, fprintf_filtered(), get_auxv_inferior_data(), get_user_print_options(), auxv_info::length, name, paddress(), plongest(), TAG, target_auxv_parse(), target_gdbarch(), type, and val_print_string().
Referenced by info_auxv_command().
static struct auxv_info* get_auxv_inferior_data (struct target_ops * ops) [static, read]
Definition at line 336 of file auxv.c.
References auxv_inferior_data, current_inferior(), auxv_info::data, auxv_info::length, TARGET_OBJECT_AUXV, target_read_alloc(), and XZALLOC.
Referenced by fprint_target_auxv(), and target_auxv_search().
static void info_auxv_command (char * cmd, int from_tty) [static]
Definition at line 507 of file auxv.c.
References _, current_target, error(), fprint_target_auxv(), gdb_stdout, and target_has_stack.
Referenced by _initialize_auxv().
static void invalidate_auxv_cache (void) [static]
Definition at line 326 of file auxv.c.
References current_inferior(), and invalidate_auxv_cache_inf().
Referenced by _initialize_auxv().
static void invalidate_auxv_cache_inf (struct inferior * inf) [static]
Definition at line 318 of file auxv.c.
References auxv_inferior_data_cleanup().
Referenced by _initialize_auxv(), and invalidate_auxv_cache().
static LONGEST ld_so_xfer_auxv (gdb_byte * readbuf, const gdb_byte * writebuf, ULONGEST offset, LONGEST len) [static]
Definition at line 73 of file auxv.c.
References builtin_type::builtin_data_ptr, builtin_type(), extract_typed_address(), gdb_assert, len, LONGEST, lookup_minimal_symbol(), MSYMBOL_SIZE, offset, SYMBOL_VALUE_ADDRESS, target_gdbarch(), target_read_memory(), target_write_memory(), and TYPE_LENGTH.
Referenced by memory_xfer_auxv().
LONGEST memory_xfer_auxv (struct target_ops * ops, enum target_object object, const char * annex, gdb_byte * readbuf, const gdb_byte * writebuf, ULONGEST offset, LONGEST len)
Definition at line 206 of file auxv.c.
References current_inferior(), gdb_assert, ld_so_xfer_auxv(), LONGEST, procfs_xfer_auxv(), and TARGET_OBJECT_AUXV.
Referenced by linux_xfer_partial(), and procfs_xfer_partial().
static LONGEST procfs_xfer_auxv (gdb_byte * readbuf, const gdb_byte * writebuf, ULONGEST offset, LONGEST len) [static]
Definition at line 42 of file auxv.c.
References gdb_open_cloexec(), inferior_ptid, LONGEST, ptid_get_pid(), read(), ULONGEST, xfree(), and xstrprintf().
Referenced by memory_xfer_auxv().
int target_auxv_parse (struct target_ops * ops, gdb_byte ** readptr, gdb_byte * endptr, CORE_ADDR * typep, CORE_ADDR * valp)
Definition at line 269 of file auxv.c.
References target_ops::beneath, default_auxv_parse(), and target_ops::to_auxv_parse.
Referenced by fprint_target_auxv(), and target_auxv_search().
int target_auxv_search (struct target_ops * ops, CORE_ADDR match, CORE_ADDR * valp)
Definition at line 358 of file auxv.c.
References auxv_info::data, get_auxv_inferior_data(), auxv_info::length, target_auxv_parse(), and type.
Referenced by add_vsyscall_page(), arm_linux_core_read_description(), arm_linux_read_description(), enable_break(), linux_is_uclinux(), ppc_linux_displaced_step_location(), ppc_linux_get_hwcap(), read_program_header(), s390_core_read_description(), and svr4_exec_displacement().
Variable Documentation
initialize_file_ftype _initialize_auxv
Referenced by _initialize_auxv(), and initialize_all_files().
struct inferior_data* auxv_inferior_data [static]
Definition at line 283 of file auxv.c.
Referenced by _initialize_auxv(), auxv_inferior_data_cleanup(), and get_auxv_inferior_data().