GDB (xrefs): /home/stan/gdb/src/gdb/auxv.h File Reference
/home/stan/gdb/src/gdb/auxv.h File Reference
#include "target.h"
Functions
int target_auxv_parse (struct target_ops *ops, gdb_byte **readptr, gdb_byte *endptr, CORE_ADDR *typep, CORE_ADDR *valp)
int target_auxv_search (struct target_ops *ops, CORE_ADDR match, CORE_ADDR *valp)
int fprint_target_auxv (struct ui_file *file, struct target_ops *ops)
LONGEST memory_xfer_auxv (struct target_ops *ops, enum target_object object, const char *annex, gdb_byte *readbuf, const gdb_byte *writebuf, ULONGEST offset, LONGEST len)
Function Documentation
int fprint_target_auxv (struct ui_file * file, struct target_ops * ops)
Definition at line 395 of file auxv.c.
References _, value_print_options::addressprint, auxv_info::data, fprintf_filtered(), get_auxv_inferior_data(), get_user_print_options(), auxv_info::length, name, paddress(), plongest(), TAG, target_auxv_parse(), target_gdbarch(), type, and val_print_string().
Referenced by info_auxv_command().
LONGEST memory_xfer_auxv (struct target_ops * ops, enum target_object object, const char * annex, gdb_byte * readbuf, const gdb_byte * writebuf, ULONGEST offset, LONGEST len)
Definition at line 206 of file auxv.c.
References current_inferior(), gdb_assert, ld_so_xfer_auxv(), LONGEST, procfs_xfer_auxv(), and TARGET_OBJECT_AUXV.
Referenced by linux_xfer_partial(), and procfs_xfer_partial().
int target_auxv_parse (struct target_ops * ops, gdb_byte ** readptr, gdb_byte * endptr, CORE_ADDR * typep, CORE_ADDR * valp)
Definition at line 269 of file auxv.c.
References target_ops::beneath, default_auxv_parse(), and target_ops::to_auxv_parse.
Referenced by fprint_target_auxv(), and target_auxv_search().
int target_auxv_search (struct target_ops * ops, CORE_ADDR match, CORE_ADDR * valp)
Definition at line 358 of file auxv.c.
References auxv_info::data, get_auxv_inferior_data(), auxv_info::length, target_auxv_parse(), and type.
Referenced by add_vsyscall_page(), arm_linux_core_read_description(), arm_linux_read_description(), enable_break(), linux_is_uclinux(), ppc_linux_displaced_step_location(), ppc_linux_get_hwcap(), read_program_header(), s390_core_read_description(), and svr4_exec_displacement().