GDB (xrefs): /home/stan/gdb/src/gdb/ax-gdb.h File Reference
/home/stan/gdb/src/gdb/ax-gdb.h File Reference
Classes
struct axs_value
Enumerations
enum axs_lvalue_kind { axs_rvalue, axs_lvalue_memory, axs_lvalue_register }
Functions
struct agent_expr * gen_trace_for_expr (CORE_ADDR, struct expression *, int)
struct agent_expr * gen_trace_for_var (CORE_ADDR, struct gdbarch *, struct symbol *, int)
struct agent_expr * gen_trace_for_return_address (CORE_ADDR, struct gdbarch *, int)
struct agent_expr * gen_eval_for_expr (CORE_ADDR, struct expression *)
void gen_expr (struct expression *exp, union exp_element **pc, struct agent_expr *ax, struct axs_value *value)
void require_rvalue (struct agent_expr *ax, struct axs_value *value)
struct agent_expr * gen_printf (CORE_ADDR, struct gdbarch *, CORE_ADDR, LONGEST, const char *, int, struct format_piece *, int, struct expression **)
Enumeration Type Documentation
enum axs_lvalue_kind
Enumerator:
axs_rvalue
axs_lvalue_memory
axs_lvalue_register
Definition at line 52 of file ax-gdb.h.
Function Documentation
struct agent_expr* gen_eval_for_expr (CORE_ADDR , struct expression *) [read]
Definition at line 2475 of file ax-gdb.c.
References ax_simple(), discard_cleanups(), expression::elts, expression::gdbarch, gen_expr(), make_cleanup_free_agent_expr(), new_agent_expr(), axs_value::optimized_out, require_rvalue(), and agent_expr::tracing.
Referenced by agent_eval_command_one(), encode_actions_1(), parse_cond_to_aexpr(), remote_download_tracepoint(), and validate_actionline().
void gen_expr (struct expression * exp, union exp_element ** pc, struct agent_expr * ax, struct axs_value * value)
Definition at line 1777 of file ax-gdb.c.
References _, ax_const_l(), ax_goto(), ax_label(), ax_tsv(), axs_lvalue_memory, axs_lvalue_register, axs_rvalue, block_for_pc(), block_linkage_function(), builtin_type::builtin_int, builtin_type::builtin_long_long, builtin_type(), BYTES_TO_EXP_ELEM, check_typedef(), compile_internalvar_to_ax(), expression::elts, error(), EVAL_AVOID_SIDE_EFFECTS, evaluate_subexp(), find_trace_state_variable(), func, expression::gdbarch, gdbarch_num_pseudo_regs(), gdbarch_num_regs(), gen_address_of(), gen_aggregate_elt_ref(), gen_binop(), gen_cast(), gen_complement(), gen_deref(), gen_expr(), gen_expr_binop_rest(), gen_int_literal(), gen_integral_promotions(), gen_logical_not(), gen_repeat(), gen_sizeof(), gen_struct_ref(), gen_traced_pop(), gen_usual_arithmetic(), gen_usual_unary(), gen_var_ref(), internal_error(), internalvar_name(), axs_value::kind, language_defn::la_name_of_this, language_def(), agent_expr::len, type::length, LONGEST, longest_to_int(), lookup_language_this(), maybe_const_expr(), name, trace_state_variable::number, offset, op_name(), axs_value::optimized_out, pointer_type(), axs_value::reg, register_type(), require_rvalue(), agent_expr::scope, SYMBOL_LANGUAGE, SYMBOL_PRINT_NAME, agent_expr::tracing, axs_value::type, type, axs_value::u, user_reg_map_name_to_regnum(), value_as_long(), and value_type().
Referenced by gen_eval_for_expr(), gen_expr(), gen_expr_binop_rest(), gen_printf(), gen_repeat(), gen_sizeof(), gen_trace_for_expr(), and stap_compile_to_ax().
struct agent_expr* gen_printf (CORE_ADDR , struct gdbarch * , CORE_ADDR , LONGEST , const char * , int , struct format_piece * , int , struct expression **) [read]
Definition at line 2534 of file ax-gdb.c.
References ax_const_l(), ax_simple(), ax_string(), discard_cleanups(), expression::elts, gen_expr(), make_cleanup_free_agent_expr(), new_agent_expr(), axs_value::optimized_out, require_rvalue(), and agent_expr::tracing.
Referenced by maint_agent_printf_command(), and parse_cmd_to_aexpr().
struct agent_expr* gen_trace_for_expr (CORE_ADDR , struct expression * , int) [read]
Definition at line 2438 of file ax-gdb.c.
References ax_simple(), discard_cleanups(), expression::elts, expression::gdbarch, gen_expr(), gen_traced_pop(), make_cleanup_free_agent_expr(), new_agent_expr(), axs_value::optimized_out, agent_expr::trace_string, and agent_expr::tracing.
Referenced by agent_eval_command_one(), encode_actions_1(), and validate_actionline().
struct agent_expr* gen_trace_for_return_address (CORE_ADDR , struct gdbarch * , int) [read]
Definition at line 2502 of file ax-gdb.c.
References ax_simple(), discard_cleanups(), gdbarch_gen_return_address(), gen_traced_pop(), make_cleanup_free_agent_expr(), new_agent_expr(), agent_expr::trace_string, and agent_expr::tracing.
Referenced by agent_eval_command_one(), and encode_actions_1().
struct agent_expr* gen_trace_for_var (CORE_ADDR , struct gdbarch * , struct symbol * , int) [read]
Definition at line 2396 of file ax-gdb.c.
References ax_simple(), discard_cleanups(), do_cleanups(), gen_traced_pop(), gen_var_ref(), make_cleanup_free_agent_expr(), new_agent_expr(), axs_value::optimized_out, agent_expr::trace_string, and agent_expr::tracing.
Referenced by collect_symbol().
void require_rvalue (struct agent_expr * ax, struct axs_value * value)
Definition at line 765 of file ax-gdb.c.
References _, ax_reg(), axs_lvalue_memory, axs_lvalue_register, axs_rvalue, check_typedef(), error(), gen_extend(), gen_fetch(), axs_value::kind, axs_value::reg, axs_value::type, TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_FUNC, TYPE_CODE_STRUCT, TYPE_CODE_UNION, and axs_value::u.
Referenced by dwarf2_compile_expr_to_ax(), gen_cast(), gen_eval_for_expr(), gen_expr(), gen_printf(), gen_struct_ref(), gen_usual_unary(), and stap_compile_to_ax().