GDB (xrefs): /home/stan/gdb/src/gdb/bcache.c File Reference
/home/stan/gdb/src/gdb/bcache.c File Reference
#include "defs.h"
#include "gdb_obstack.h"
#include "bcache.h"
#include "gdb_string.h"
#include "gdb_assert.h"
#include <stddef.h>
#include <stdlib.h>
Classes
struct bstring
struct bcache
Defines
#define CHAIN_LENGTH_THRESHOLD (5)
#define BSTRING_SIZE(n) (offsetof (struct bstring, d.data) + (n))
Functions
unsigned long hash (const void *addr, int length)
unsigned long hash_continue (const void *addr, int length, unsigned long h)
static void expand_hash_table (struct bcache *bcache)
const void * bcache (const void *addr, int length, struct bcache *cache)
const void * bcache_full (const void *addr, int length, struct bcache *bcache, int *added)
static int bcache_compare (const void *addr1, const void *addr2, int length)
struct bcache * bcache_xmalloc (unsigned long(*hash_function)(const void *, int length), int(*compare_function)(const void *, const void *, int length))
void bcache_xfree (struct bcache *bcache)
static void print_percentage (int portion, int total)
void print_bcache_statistics (struct bcache *c, char *type)
int bcache_memory_used (struct bcache *bcache)
Define Documentation
#define BSTRING_SIZE (n) (offsetof (struct bstring, d.data) + (n))
Definition at line 205 of file bcache.c.
Referenced by bcache_full().
#define CHAIN_LENGTH_THRESHOLD (5)
Definition at line 129 of file bcache.c.
Referenced by bcache_full().
Function Documentation
const void* bcache (const void * addr, int length, struct bcache * cache)
Definition at line 211 of file bcache.c.
References bcache_full().
Referenced by elf_symtab_read(), macro_bcache(), and psymbol_bcache_init().
static int bcache_compare (const void * addr1, const void * addr2, int length) [static]
Definition at line 297 of file bcache.c.
References memcmp().
Referenced by bcache_xmalloc().
const void* bcache_full (const void * addr, int length, struct bcache * bcache, int * added)
Definition at line 223 of file bcache.c.
References BSTRING_SIZE, bcache::bucket, bcache::cache, CHAIN_LENGTH_THRESHOLD, bcache::compare_function, bstring::d, bstring::data, expand_hash_table(), bstring::half_hash, bcache::half_hash_miss_count, bcache::hash_function, bstring::length, memcpy(), bstring::next, bcache::num_buckets, bcache::structure_size, bcache::total_count, bcache::total_size, bcache::unique_count, and bcache::unique_size.
Referenced by bcache(), check_types_worklist(), and psymbol_bcache_full().
int bcache_memory_used (struct bcache * bcache)
Definition at line 490 of file bcache.c.
References bcache::cache, and bcache::total_count.
Referenced by print_objfile_statistics().
void bcache_xfree (struct bcache * bcache)
Definition at line 332 of file bcache.c.
References bcache::bucket, bcache::cache, bcache::total_count, and xfree().
Referenced by free_objfile_per_bfd_storage(), psymbol_bcache_free(), and typy_richcompare().
struct bcache* bcache_xmalloc (unsigned long(*)(const void *, int length) hash_function, int(*)(const void *, const void *, int length) compare_function) [read]
Definition at line 310 of file bcache.c.
References bcache_compare(), bcache::compare_function, hash(), bcache::hash_function, and XCALLOC.
Referenced by get_objfile_bfd_data(), psymbol_bcache_init(), and typy_richcompare().
static void expand_hash_table (struct bcache * bcache) [static]
Definition at line 132 of file bcache.c.
References bcache::bucket, bstring::d, bstring::data, bcache::expand_count, bcache::expand_hash_count, bcache::hash_function, bstring::length, memset(), bstring::next, bcache::num_buckets, bcache::structure_size, bcache::unique_count, xfree(), and xmalloc().
Referenced by bcache_full().
unsigned long hash (const void * addr, int length)
Definition at line 103 of file bcache.c.
References hash_continue().
Referenced by add_minsym_to_demangled_hash_table(), add_minsym_to_hash_table(), bcache_xmalloc(), dict_hash(), find_slot(), find_slot_in_mapped_hash(), frame_addr_hash(), gdb_bfd_open(), gdb_bfd_unref(), hash_address_entry(), hash_dwo_file(), hashname(), iterate_over_minimal_symbols(), lookup_dwo_unit_in_dwp(), lookup_minimal_symbol_and_objfile(), lookup_minimal_symbol_by_pc_name(), lookup_minimal_symbol_internal(), lookup_minimal_symbol_solib_trampoline(), lookup_minimal_symbol_text(), msymbol_hash(), msymbol_hash_iw(), patch_opaque_types(), and scan_file_globals().
unsigned long hash_continue (const void * addr, int length, unsigned long h)
Definition at line 111 of file bcache.c.
References bstring::length.
Referenced by hash(), and psymbol_hash().
void print_bcache_statistics (struct bcache * c, char * type)
Definition at line 363 of file bcache.c.
References _, bcache::bucket, compare_positive_ints(), bcache::expand_count, bcache::expand_hash_count, gdb_assert, bcache::half_hash_miss_count, bstring::length, bstring::next, bcache::num_buckets, print_percentage(), printf_filtered(), qsort, bcache::structure_size, bcache::total_count, bcache::total_size, bcache::unique_count, bcache::unique_size, XCALLOC, and xfree().
Referenced by print_symbol_bcache_statistics().
static void print_percentage (int portion, int total) [static]
Definition at line 348 of file bcache.c.
References _, and printf_filtered().
Referenced by print_bcache_statistics().