GDB (xrefs): /home/stan/gdb/src/gdb/bfd-target.c File Reference
/home/stan/gdb/src/gdb/bfd-target.c File Reference
#include "defs.h"
#include "target.h"
#include "bfd-target.h"
#include "exec.h"
#include "gdb_bfd.h"
Classes
struct target_bfd_data
Functions
static LONGEST target_bfd_xfer_partial (struct target_ops *ops, enum target_object object, const char *annex, gdb_byte *readbuf, const gdb_byte *writebuf, ULONGEST offset, LONGEST len)
static struct
target_section_table * target_bfd_get_section_table (struct target_ops *ops)
static void target_bfd_xclose (struct target_ops *t)
struct target_ops * target_bfd_reopen (struct bfd *abfd)
Function Documentation
static struct target_section_table* target_bfd_get_section_table (struct target_ops * ops) [static, read]
Definition at line 63 of file bfd-target.c.
References target_bfd_data::table, and target_ops::to_data.
Referenced by target_bfd_reopen().
struct target_ops* target_bfd_reopen (struct bfd * abfd) [read]
Definition at line 81 of file bfd-target.c.
References _, target_bfd_data::bfd, build_section_table(), gdb_bfd_ref(), OPS_MAGIC, target_section_table::sections, target_section_table::sections_end, target_bfd_data::table, target_bfd_get_section_table(), target_bfd_xclose(), target_bfd_xfer_partial(), target_ops::to_data, target_ops::to_doc, target_ops::to_get_section_table, target_ops::to_longname, target_ops::to_magic, target_ops::to_shortname, target_ops::to_xclose, target_ops::to_xfer_partial, and XZALLOC.
Referenced by enable_break().
static void target_bfd_xclose (struct target_ops * t) [static]
Definition at line 70 of file bfd-target.c.
References target_bfd_data::bfd, gdb_bfd_unref(), target_section_table::sections, target_bfd_data::table, target_ops::to_data, and xfree().
Referenced by target_bfd_reopen().
static LONGEST target_bfd_xfer_partial (struct target_ops * ops, enum target_object object, const char * annex, gdb_byte * readbuf, const gdb_byte * writebuf, ULONGEST offset, LONGEST len) [static]
Definition at line 40 of file bfd-target.c.
References section_table_xfer_memory_partial(), target_section_table::sections, target_section_table::sections_end, target_bfd_data::table, TARGET_OBJECT_MEMORY, and target_ops::to_data.
Referenced by target_bfd_reopen().