GDB (xrefs): /home/stan/gdb/src/gdb/bfin-linux-tdep.c File Reference
/home/stan/gdb/src/gdb/bfin-linux-tdep.c File Reference
#include "defs.h"
#include "arch-utils.h"
#include "regcache.h"
#include "tramp-frame.h"
#include "trad-frame.h"
#include "osabi.h"
#include "xml-syscall.h"
#include "linux-tdep.h"
#include "bfin-tdep.h"
Defines
#define SIGCONTEXT_OFFSET 168
Functions
static void bfin_linux_sigframe_init (const struct tramp_frame *self, struct frame_info *this_frame, struct trad_frame_cache *this_cache, CORE_ADDR func)
static LONGEST bfin_linux_get_syscall_number (struct gdbarch *gdbarch, ptid_t ptid)
static void bfin_linux_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
void _initialize_bfin_linux_tdep (void)
Variables
static const int bfin_linux_sigcontext_reg_offset [BFIN_NUM_REGS]
static struct tramp_frame bfin_linux_sigframe
initialize_file_ftype _initialize_bfin_linux_tdep
Define Documentation
#define SIGCONTEXT_OFFSET 168
Definition at line 34 of file bfin-linux-tdep.c.
Referenced by bfin_linux_sigframe_init().
Function Documentation
void _initialize_bfin_linux_tdep (void)
Definition at line 169 of file bfin-linux-tdep.c.
References _initialize_bfin_linux_tdep, bfin_linux_init_abi(), GDB_OSABI_LINUX, and gdbarch_register_osabi().
static LONGEST bfin_linux_get_syscall_number (struct gdbarch * gdbarch, ptid_t ptid) [static]
Definition at line 131 of file bfin-linux-tdep.c.
References BFIN_P0_REGNUM, extract_signed_integer(), gdbarch_byte_order(), get_thread_regcache(), LONGEST, and regcache_cooked_read().
Referenced by bfin_linux_init_abi().
static void bfin_linux_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch) [static]
Definition at line 152 of file bfin-linux-tdep.c.
References bfin_linux_get_syscall_number(), linux_init_abi(), set_gdbarch_get_syscall_number(), set_xml_syscall_file_name(), and tramp_frame_prepend_unwinder().
Referenced by _initialize_bfin_linux_tdep().
static void bfin_linux_sigframe_init (const struct tramp_frame * self, struct frame_info * this_frame, struct trad_frame_cache * this_cache, CORE_ADDR func) [static]
Definition at line 97 of file bfin-linux-tdep.c.
References bfin_linux_sigcontext_reg_offset, BFIN_NUM_REGS, frame_id_build(), get_frame_arch(), get_frame_pc(), get_frame_sp(), reg_offset, SIGCONTEXT_OFFSET, sp, trad_frame_set_id(), and trad_frame_set_reg_addr().
Variable Documentation
initialize_file_ftype _initialize_bfin_linux_tdep
Referenced by _initialize_bfin_linux_tdep(), and initialize_all_files().
const int bfin_linux_sigcontext_reg_offset[BFIN_NUM_REGS] [static]
Definition at line 36 of file bfin-linux-tdep.c.
Referenced by bfin_linux_sigframe_init().
struct tramp_frame bfin_linux_sigframe [static]
Initial value:
{
  SIGTRAMP_FRAME,
  4,
  {
    { 0x00ADE128, 0xffffffff },
    { 0x00A0, 0xffff },
    { TRAMP_SENTINEL_INSN, -1 },
  },
  bfin_linux_sigframe_init,
}
Definition at line 118 of file bfin-linux-tdep.c.