GDB (xrefs): /home/stan/gdb/src/gdb/breakpoint.c File Reference
/home/stan/gdb/src/gdb/breakpoint.c File Reference
#include "defs.h"
#include "arch-utils.h"
#include <ctype.h>
#include "hashtab.h"
#include "symtab.h"
#include "frame.h"
#include "breakpoint.h"
#include "tracepoint.h"
#include "gdbtypes.h"
#include "expression.h"
#include "gdbcore.h"
#include "gdbcmd.h"
#include "value.h"
#include "command.h"
#include "inferior.h"
#include "gdbthread.h"
#include "target.h"
#include "language.h"
#include "gdb_string.h"
#include "gdb-demangle.h"
#include "filenames.h"
#include "annotate.h"
#include "symfile.h"
#include "objfiles.h"
#include "source.h"
#include "linespec.h"
#include "completer.h"
#include "gdb.h"
#include "ui-out.h"
#include "cli/cli-script.h"
#include "gdb_assert.h"
#include "block.h"
#include "solib.h"
#include "solist.h"
#include "observer.h"
#include "exceptions.h"
#include "memattr.h"
#include "ada-lang.h"
#include "top.h"
#include "valprint.h"
#include "jit.h"
#include "xml-syscall.h"
#include "parser-defs.h"
#include "gdb_regex.h"
#include "probe.h"
#include "cli/cli-utils.h"
#include "continuations.h"
#include "stack.h"
#include "skip.h"
#include "ax-gdb.h"
#include "dummy-frame.h"
#include "format.h"
#include "readline/readline.h"
#include "readline/history.h"
#include "mi/mi-common.h"
#include "python/python.h"
Classes
struct counted_command_line
struct commands_info
struct breakpoint_objfile_data
struct captured_breakpoint_query_args
struct lang_and_radix
struct fork_catchpoint
struct solib_catchpoint
struct syscall_catchpoint
struct catch_syscall_inferior_data
struct exec_catchpoint
struct until_break_command_continuation_args
struct disp_data
Defines
#define ALL_BREAKPOINTS(B) for (B = breakpoint_chain; B; B = B->next)
#define ALL_BREAKPOINTS_SAFE(B, TMP)
#define ALL_BP_LOCATIONS(B, BP_TMP)
#define ALL_BP_LOCATIONS_AT_ADDR(BP_LOCP_TMP, BP_LOCP_START, ADDRESS)
#define ALL_TRACEPOINTS(B)
#define NUM_LONGJMP_NAMES ARRAY_SIZE(longjmp_names)
#define WP_DELETED 1
#define WP_VALUE_CHANGED 2
#define WP_VALUE_NOT_CHANGED 3
#define WP_IGNORE 4
#define BP_TEMPFLAG 1
#define BP_HARDWAREFLAG 2
#define internal_error_pure_virtual_called() gdb_assert_not_reached ("pure virtual function called")
#define BREAK_ARGS_HELP(command) command" [PROBE_MODIFIER] [LOCATION] [thread THREADNUM] [if CONDITION]\n\PROBE_MODIFIER shall be present if the command is to be placed in a\n\probe point. Accepted values are `-probe' (for a generic, automatically\n\guessed probe type) or `-probe-stap' (for a SystemTap probe).\n\LOCATION may be a line number, function name, or \"*\" and an address.\n\If a line number is specified, break at start of code for that line.\n\If a function is specified, break at start of code for that function.\n\If an address is specified, break at that exact address.\n\With no LOCATION, uses current execution address of the selected\n\stack frame. This is useful for breaking on return to a stack frame.\n\\n\THREADNUM is the number from \"info threads\".\n\CONDITION is a boolean expression.\n\\n\Multiple breakpoints at one place are permitted, and useful if their\n\conditions are different.\n\\n\Do \"help breakpoints\" for info on other commands dealing with breakpoints."
Enumerations
enum exception_event_kind {
EX_EVENT_THROW, EX_EVENT_RETHROW, EX_EVENT_CATCH, EX_EVENT_THROW,
EX_EVENT_RETHROW, EX_EVENT_CATCH
}
enum insertion_state_t { mark_inserted, mark_uninserted }
enum catch_fork_kind { catch_fork_temporary, catch_vfork_temporary, catch_fork_permanent, catch_vfork_permanent }
Functions
static void enable_delete_command (char *, int)
static void enable_once_command (char *, int)
static void enable_count_command (char *, int)
static void disable_command (char *, int)
static void enable_command (char *, int)
static void map_breakpoint_numbers (char *, void(*)(struct breakpoint *, void *), void *)
static void ignore_command (char *, int)
static int breakpoint_re_set_one (void *)
static void breakpoint_re_set_default (struct breakpoint *)
static void create_sals_from_address_default (char **, struct linespec_result *, enum bptype, char *, char **)
static void create_breakpoints_sal_default (struct gdbarch *, struct linespec_result *, char *, char *, enum bptype, enum bpdisp, int, int, int, const struct breakpoint_ops *, int, int, int, unsigned)
static void decode_linespec_default (struct breakpoint *, char **, struct symtabs_and_lines *)
static void clear_command (char *, int)
static void catch_command (char *, int)
static int can_use_hardware_watchpoint (struct value *)
static void break_command_1 (char *, int, int)
static void mention (struct breakpoint *)
static struct breakpoint * set_raw_breakpoint_without_location (struct gdbarch *, enum bptype, const struct breakpoint_ops *)
static struct bp_location * add_location_to_breakpoint (struct breakpoint *, const struct symtab_and_line *)
struct breakpoint * set_raw_breakpoint (struct gdbarch *gdbarch, struct symtab_and_line, enum bptype, const struct breakpoint_ops *)
static struct breakpoint * momentary_breakpoint_from_master (struct breakpoint *orig, enum bptype type, const struct breakpoint_ops *ops)
static void breakpoint_adjustment_warning (CORE_ADDR, CORE_ADDR, int, int)
static CORE_ADDR adjust_breakpoint_address (struct gdbarch *gdbarch, CORE_ADDR bpaddr, enum bptype bptype)
static void describe_other_breakpoints (struct gdbarch *, struct program_space *, CORE_ADDR, struct obj_section *, int)
static int breakpoint_address_match (struct address_space *aspace1, CORE_ADDR addr1, struct address_space *aspace2, CORE_ADDR addr2)
static int watchpoint_locations_match (struct bp_location *loc1, struct bp_location *loc2)
static int breakpoint_location_address_match (struct bp_location *bl, struct address_space *aspace, CORE_ADDR addr)
static void breakpoints_info (char *, int)
static void watchpoints_info (char *, int)
static int breakpoint_1 (char *, int, int(*)(const struct breakpoint *))
static int breakpoint_cond_eval (void *)
static void cleanup_executing_breakpoints (void *)
static void commands_command (char *, int)
static void condition_command (char *, int)
static int remove_breakpoint (struct bp_location *, insertion_state_t)
static int remove_breakpoint_1 (struct bp_location *, insertion_state_t)
static enum print_stop_action print_bp_stop_message (bpstat bs)
static int watchpoint_check (void *)
static void maintenance_info_breakpoints (char *, int)
static int hw_breakpoint_used_count (void)
static int hw_watchpoint_use_count (struct breakpoint *)
static int hw_watchpoint_used_count_others (struct breakpoint *except, enum bptype type, int *other_type_used)
static void hbreak_command (char *, int)
static void thbreak_command (char *, int)
static void enable_breakpoint_disp (struct breakpoint *, enum bpdisp, int count)
static void stop_command (char *arg, int from_tty)
static void stopin_command (char *arg, int from_tty)
static void stopat_command (char *arg, int from_tty)
static void tcatch_command (char *arg, int from_tty)
static void detach_single_step_breakpoints (void)
static int single_step_breakpoint_inserted_here_p (struct address_space *, CORE_ADDR pc)
static void free_bp_location (struct bp_location *loc)
static void incref_bp_location (struct bp_location *loc)
static void decref_bp_location (struct bp_location **loc)
static struct bp_location * allocate_bp_location (struct breakpoint *bpt)
static void update_global_location_list (int)
static void update_global_location_list_nothrow (int)
static int is_hardware_watchpoint (const struct breakpoint *bpt)
static void insert_breakpoint_locations (void)
static int syscall_catchpoint_p (struct breakpoint *b)
static void tracepoints_info (char *, int)
static void delete_trace_command (char *, int)
static void enable_trace_command (char *, int)
static void disable_trace_command (char *, int)
static void trace_pass_command (char *, int)
static void set_tracepoint_count (int num)
static int is_masked_watchpoint (const struct breakpoint *b)
static struct bp_location ** get_first_locp_gte_addr (CORE_ADDR address)
static int strace_marker_p (struct breakpoint *b)
struct command_line * breakpoint_commands (struct breakpoint *b)
const char * bpdisp_text (enum bpdisp disp)
static void show_can_use_hw_watchpoints (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static void show_pending_break_support (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static void show_automatic_hardware_breakpoints (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static void show_always_inserted_mode (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
int breakpoints_always_inserted_mode (void)
static const char * translate_condition_evaluation_mode (const char *mode)
static const char * breakpoint_condition_evaluation_mode (void)
static int gdb_evaluates_breakpoint_condition_p (void)
void _initialize_breakpoint (void)
VEC (bp_location_p)
static void set_breakpoint_count (int num)
void start_rbreak_breakpoints (void)
void end_rbreak_breakpoints (void)
void clear_breakpoint_hit_counts (void)
static struct
counted_command_line * alloc_counted_command_line (struct command_line *commands)
static void incref_counted_command_line (struct counted_command_line *cmd)
static void decref_counted_command_line (struct counted_command_line **cmdp)
static void do_cleanup_counted_command_line (void *arg)
static struct cleanup * make_cleanup_decref_counted_command_line (struct counted_command_line **cmdp)
struct breakpoint * get_breakpoint (int num)
static void mark_breakpoint_modified (struct breakpoint *b)
static void mark_breakpoint_location_modified (struct bp_location *loc)
static void set_condition_evaluation_mode (char *args, int from_tty, struct cmd_list_element *c)
static void show_condition_evaluation_mode (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static int bp_location_compare_addrs (const void *ap, const void *bp)
void set_breakpoint_condition (struct breakpoint *b, char *exp, int from_tty)
static VEC (char_ptr)
static void check_no_tracepoint_commands (struct command_line *commands)
static int is_tracepoint_type (enum bptype type)
int is_tracepoint (const struct breakpoint *b)
static void validate_commands_for_breakpoint (struct breakpoint *b, struct command_line *commands)
VEC (breakpoint_p)
void breakpoint_set_commands (struct breakpoint *b, struct command_line *commands)
void breakpoint_set_silent (struct breakpoint *b, int silent)
void breakpoint_set_thread (struct breakpoint *b, int thread)
void breakpoint_set_task (struct breakpoint *b, int task)
void check_tracepoint_command (char *line, void *closure)
static void do_map_commands_command (struct breakpoint *b, void *data)
static void commands_command_1 (char *arg, int from_tty, struct command_line *control)
enum command_control_type commands_from_control_command (char *arg, struct command_line *cmd)
static int bp_location_has_shadow (struct bp_location *bl)
void breakpoint_xfer_memory (gdb_byte *readbuf, gdb_byte *writebuf, const gdb_byte *writebuf_org, ULONGEST memaddr, LONGEST len)
int is_breakpoint (const struct breakpoint *bpt)
int is_watchpoint (const struct breakpoint *bpt)
static int watchpoint_in_thread_scope (struct watchpoint *b)
static void watchpoint_del_at_next_stop (struct watchpoint *w)
static void update_watchpoint (struct watchpoint *b, int reparse)
static int should_be_inserted (struct bp_location *bl)
static int unduplicated_should_be_inserted (struct bp_location *bl)
static struct agent_expr * parse_cond_to_aexpr (CORE_ADDR scope, struct expression *cond)
static void build_target_condition_list (struct bp_location *bl)
static struct agent_expr * parse_cmd_to_aexpr (CORE_ADDR scope, char *cmd)
static void build_target_command_list (struct bp_location *bl)
static int insert_bp_location (struct bp_location *bl, struct ui_file *tmp_error_stream, int *disabled_breaks, int *hw_breakpoint_error, int *hw_bp_error_explained_already)
void breakpoint_program_space_exit (struct program_space *pspace)
void insert_breakpoints (void)
void iterate_over_bp_locations (walk_bp_location_callback callback)
static void update_inserted_breakpoint_locations (void)
int remove_breakpoints (void)
static void remove_threaded_breakpoints (struct thread_info *tp, int silent)
int remove_breakpoints_pid (int pid)
int reattach_breakpoints (int pid)
static void set_breakpoint_number (int internal, struct breakpoint *b)
static struct breakpoint * create_internal_breakpoint (struct gdbarch *gdbarch, CORE_ADDR address, enum bptype type, const struct breakpoint_ops *ops)
static int msym_not_found_p (const struct minimal_symbol *msym)
static struct
breakpoint_objfile_data * get_breakpoint_objfile_data (struct objfile *objfile)
static void free_breakpoint_probes (struct objfile *obj, void *data)
static void create_overlay_event_breakpoint (void)
static void create_longjmp_master_breakpoint (void)
static void create_std_terminate_master_breakpoint (void)
static void create_exception_master_breakpoint (void)
void update_breakpoints_after_exec (void)
int detach_breakpoints (ptid_t ptid)
void mark_breakpoints_out (void)
void breakpoint_init_inferior (enum inf_context context)
enum breakpoint_here breakpoint_here_p (struct address_space *aspace, CORE_ADDR pc)
int moribund_breakpoint_here_p (struct address_space *aspace, CORE_ADDR pc)
int regular_breakpoint_inserted_here_p (struct address_space *aspace, CORE_ADDR pc)
int breakpoint_inserted_here_p (struct address_space *aspace, CORE_ADDR pc)
int software_breakpoint_inserted_here_p (struct address_space *aspace, CORE_ADDR pc)
int hardware_watchpoint_inserted_in_range (struct address_space *aspace, CORE_ADDR addr, ULONGEST len)
int breakpoint_thread_match (struct address_space *aspace, CORE_ADDR pc, ptid_t ptid)
int is_catchpoint (struct breakpoint *ep)
static void bpstat_free (bpstat bs)
void bpstat_clear (bpstat *bsp)
bpstat bpstat_copy (bpstat bs)
bpstat bpstat_find_breakpoint (bpstat bsp, struct breakpoint *breakpoint)
enum bpstat_signal_value bpstat_explains_signal (bpstat bsp, enum gdb_signal sig)
int bpstat_num (bpstat *bsp, int *num)
void bpstat_clear_actions (void)
static void breakpoint_about_to_proceed (void)
static int command_line_is_silent (struct command_line *cmd)
static int bpstat_do_actions_1 (bpstat *bsp)
void bpstat_do_actions (void)
static void watchpoint_value_print (struct value *val, struct ui_file *stream)
static void print_solib_event (int is_catchpoint)
enum print_stop_action bpstat_print (bpstat bs, int kind)
static bpstat bpstat_alloc (struct bp_location *bl, bpstat **bs_link_pointer)
int watchpoints_triggered (struct target_waitstatus *ws)
static int bpstat_check_location (const struct bp_location *bl, struct address_space *aspace, CORE_ADDR bp_addr, const struct target_waitstatus *ws)
static void bpstat_check_watchpoint (bpstat bs)
static void bpstat_check_breakpoint_conditions (bpstat bs, ptid_t ptid)
bpstat bpstat_stop_status (struct address_space *aspace, CORE_ADDR bp_addr, ptid_t ptid, const struct target_waitstatus *ws)
static void handle_jit_event (void)
struct bpstat_what bpstat_what (bpstat bs_head)
int bpstat_should_step (void)
int bpstat_causes_stop (bpstat bs)
static char * wrap_indent_at_field (struct ui_out *uiout, const char *col_name)
static const char * bp_condition_evaluator (struct breakpoint *b)
static const char * bp_location_condition_evaluator (struct bp_location *bl)
static void print_breakpoint_location (struct breakpoint *b, struct bp_location *loc)
static const char * bptype_string (enum bptype type)
static void output_thread_groups (struct ui_out *uiout, const char *field_name, VEC(int)*inf_num, int mi_only)
static void print_one_breakpoint_location (struct breakpoint *b, struct bp_location *loc, int loc_number, struct bp_location **last_loc, int allflag)
static void print_one_breakpoint (struct breakpoint *b, struct bp_location **last_loc, int allflag)
static int breakpoint_address_bits (struct breakpoint *b)
static int do_captured_breakpoint_query (struct ui_out *uiout, void *data)
enum gdb_rc gdb_breakpoint_query (struct ui_out *uiout, int bnum, char **error_message)
int user_breakpoint_p (struct breakpoint *b)
static void default_collect_info (void)
static int breakpoint_has_pc (struct breakpoint *b, struct program_space *pspace, CORE_ADDR pc, struct obj_section *section)
static int breakpoint_address_is_meaningful (struct breakpoint *bpt)
static int breakpoint_address_match_range (struct address_space *aspace1, CORE_ADDR addr1, int len1, struct address_space *aspace2, CORE_ADDR addr2)
static int tracepoint_locations_match (struct bp_location *loc1, struct bp_location *loc2)
static int breakpoint_locations_match (struct bp_location *loc1, struct bp_location *loc2)
static CORE_ADDR adjust_breakpoint_address (struct gdbarch *gdbarch, CORE_ADDR bpaddr, enum bptype bptype)
void init_bp_location (struct bp_location *loc, const struct bp_location_ops *ops, struct breakpoint *owner)
static void add_to_breakpoint_chain (struct breakpoint *b)
static void init_raw_breakpoint_without_location (struct breakpoint *b, struct gdbarch *gdbarch, enum bptype bptype, const struct breakpoint_ops *ops)
static void set_breakpoint_location_function (struct bp_location *loc, int explicit_loc)
struct gdbarch * get_sal_arch (struct symtab_and_line sal)
static void init_raw_breakpoint (struct breakpoint *b, struct gdbarch *gdbarch, struct symtab_and_line sal, enum bptype bptype, const struct breakpoint_ops *ops)
void make_breakpoint_permanent (struct breakpoint *b)
void set_longjmp_breakpoint (struct thread_info *tp, struct frame_id frame)
void delete_longjmp_breakpoint (int thread)
void delete_longjmp_breakpoint_at_next_stop (int thread)
struct breakpoint * set_longjmp_breakpoint_for_call_dummy (void)
void check_longjmp_breakpoint_for_call_dummy (int thread)
void enable_overlay_breakpoints (void)
void disable_overlay_breakpoints (void)
void set_std_terminate_breakpoint (void)
void delete_std_terminate_breakpoint (void)
struct breakpoint * create_thread_event_breakpoint (struct gdbarch *gdbarch, CORE_ADDR address)
void remove_thread_event_breakpoints (void)
struct breakpoint * create_jit_event_breakpoint (struct gdbarch *gdbarch, CORE_ADDR address)
void remove_jit_event_breakpoints (void)
void remove_solib_event_breakpoints (void)
struct breakpoint * create_solib_event_breakpoint (struct gdbarch *gdbarch, CORE_ADDR address)
void disable_breakpoints_in_shlibs (void)
static void disable_breakpoints_in_unloaded_shlib (struct so_list *solib)
static int insert_catch_fork (struct bp_location *bl)
static int remove_catch_fork (struct bp_location *bl)
static int breakpoint_hit_catch_fork (const struct bp_location *bl, struct address_space *aspace, CORE_ADDR bp_addr, const struct target_waitstatus *ws)
static enum print_stop_action print_it_catch_fork (bpstat bs)
static void print_one_catch_fork (struct breakpoint *b, struct bp_location **last_loc)
static void print_mention_catch_fork (struct breakpoint *b)
static void print_recreate_catch_fork (struct breakpoint *b, struct ui_file *fp)
static int insert_catch_vfork (struct bp_location *bl)
static int remove_catch_vfork (struct bp_location *bl)
static int breakpoint_hit_catch_vfork (const struct bp_location *bl, struct address_space *aspace, CORE_ADDR bp_addr, const struct target_waitstatus *ws)
static enum print_stop_action print_it_catch_vfork (bpstat bs)
static void print_one_catch_vfork (struct breakpoint *b, struct bp_location **last_loc)
static void print_mention_catch_vfork (struct breakpoint *b)
static void print_recreate_catch_vfork (struct breakpoint *b, struct ui_file *fp)
static void dtor_catch_solib (struct breakpoint *b)
static int insert_catch_solib (struct bp_location *ignore)
static int remove_catch_solib (struct bp_location *ignore)
static int breakpoint_hit_catch_solib (const struct bp_location *bl, struct address_space *aspace, CORE_ADDR bp_addr, const struct target_waitstatus *ws)
static void check_status_catch_solib (struct bpstats *bs)
static enum print_stop_action print_it_catch_solib (bpstat bs)
static void print_one_catch_solib (struct breakpoint *b, struct bp_location **locs)
static void print_mention_catch_solib (struct breakpoint *b)
static void print_recreate_catch_solib (struct breakpoint *b, struct ui_file *fp)
void add_solib_catchpoint (char *arg, int is_load, int is_temp, int enabled)
static void catch_load_or_unload (char *arg, int from_tty, int is_load, struct cmd_list_element *command)
static void catch_load_command_1 (char *arg, int from_tty, struct cmd_list_element *command)
static void catch_unload_command_1 (char *arg, int from_tty, struct cmd_list_element *command)
static void dtor_catch_syscall (struct breakpoint *b)
static struct
catch_syscall_inferior_data * get_catch_syscall_inferior_data (struct inferior *inf)
static void catch_syscall_inferior_data_cleanup (struct inferior *inf, void *arg)
static int insert_catch_syscall (struct bp_location *bl)
static int remove_catch_syscall (struct bp_location *bl)
static int breakpoint_hit_catch_syscall (const struct bp_location *bl, struct address_space *aspace, CORE_ADDR bp_addr, const struct target_waitstatus *ws)
static enum print_stop_action print_it_catch_syscall (bpstat bs)
static void print_one_catch_syscall (struct breakpoint *b, struct bp_location **last_loc)
static void print_mention_catch_syscall (struct breakpoint *b)
static void print_recreate_catch_syscall (struct breakpoint *b, struct ui_file *fp)
void init_catchpoint (struct breakpoint *b, struct gdbarch *gdbarch, int tempflag, char *cond_string, const struct breakpoint_ops *ops)
void install_breakpoint (int internal, struct breakpoint *b, int update_gll)
static void create_fork_vfork_event_catchpoint (struct gdbarch *gdbarch, int tempflag, char *cond_string, const struct breakpoint_ops *ops)
static void dtor_catch_exec (struct breakpoint *b)
static int insert_catch_exec (struct bp_location *bl)
static int remove_catch_exec (struct bp_location *bl)
static int breakpoint_hit_catch_exec (const struct bp_location *bl, struct address_space *aspace, CORE_ADDR bp_addr, const struct target_waitstatus *ws)
static enum print_stop_action print_it_catch_exec (bpstat bs)
static void print_one_catch_exec (struct breakpoint *b, struct bp_location **last_loc)
static void print_mention_catch_exec (struct breakpoint *b)
static void print_recreate_catch_exec (struct breakpoint *b, struct ui_file *fp)
static void create_syscall_event_catchpoint (int tempflag, VEC(int)*filter, const struct breakpoint_ops *ops)
void disable_watchpoints_before_interactive_call_start (void)
void enable_watchpoints_after_interactive_call_stop (void)
void disable_breakpoints_before_startup (void)
void enable_breakpoints_after_startup (void)
struct breakpoint * set_momentary_breakpoint (struct gdbarch *gdbarch, struct symtab_and_line sal, struct frame_id frame_id, enum bptype type)
struct breakpoint * clone_momentary_breakpoint (struct breakpoint *orig)
struct breakpoint * set_momentary_breakpoint_at_pc (struct gdbarch *gdbarch, CORE_ADDR pc, enum bptype type)
static int bp_loc_is_permanent (struct bp_location *loc)
static void update_dprintf_command_list (struct breakpoint *b)
static void update_dprintf_commands (char *args, int from_tty, struct cmd_list_element *c)
static void init_breakpoint_sal (struct breakpoint *b, struct gdbarch *gdbarch, struct symtabs_and_lines sals, char *addr_string, char *filter, char *cond_string, char *extra_string, enum bptype type, enum bpdisp disposition, int thread, int task, int ignore_count, const struct breakpoint_ops *ops, int from_tty, int enabled, int internal, unsigned flags, int display_canonical)
static void create_breakpoint_sal (struct gdbarch *gdbarch, struct symtabs_and_lines sals, char *addr_string, char *filter, char *cond_string, char *extra_string, enum bptype type, enum bpdisp disposition, int thread, int task, int ignore_count, const struct breakpoint_ops *ops, int from_tty, int enabled, int internal, unsigned flags, int display_canonical)
static void create_breakpoints_sal (struct gdbarch *gdbarch, struct linespec_result *canonical, char *cond_string, char *extra_string, enum bptype type, enum bpdisp disposition, int thread, int task, int ignore_count, const struct breakpoint_ops *ops, int from_tty, int enabled, int internal, unsigned flags)
static void parse_breakpoint_sals (char **address, struct linespec_result *canonical)
static void breakpoint_sals_to_pc (struct symtabs_and_lines *sals)
static void check_fast_tracepoint_sals (struct gdbarch *gdbarch, struct symtabs_and_lines *sals)
static void ATTRIBUTE_NORETURN invalid_thread_id_error (int id)
static void find_condition_and_thread (const char *tok, CORE_ADDR pc, char **cond_string, int *thread, int *task, char **rest)
static struct symtabs_and_lines decode_static_tracepoint_spec (char **arg_p)
int create_breakpoint (struct gdbarch *gdbarch, char *arg, char *cond_string, int thread, char *extra_string, int parse_arg, int tempflag, enum bptype type_wanted, int ignore_count, enum auto_boolean pending_break_support, const struct breakpoint_ops *ops, int from_tty, int enabled, int internal, unsigned flags)
void resolve_sal_pc (struct symtab_and_line *sal)
void break_command (char *arg, int from_tty)
void tbreak_command (char *arg, int from_tty)
static void dprintf_command (char *arg, int from_tty)
static void agent_printf_command (char *arg, int from_tty)
static int breakpoint_hit_ranged_breakpoint (const struct bp_location *bl, struct address_space *aspace, CORE_ADDR bp_addr, const struct target_waitstatus *ws)
static int resources_needed_ranged_breakpoint (const struct bp_location *bl)
static enum print_stop_action print_it_ranged_breakpoint (bpstat bs)
static void print_one_ranged_breakpoint (struct breakpoint *b, struct bp_location **last_loc)
static void print_one_detail_ranged_breakpoint (const struct breakpoint *b, struct ui_out *uiout)
static void print_mention_ranged_breakpoint (struct breakpoint *b)
static void print_recreate_ranged_breakpoint (struct breakpoint *b, struct ui_file *fp)
static CORE_ADDR find_breakpoint_range_end (struct symtab_and_line sal)
static void break_range_command (char *arg, int from_tty)
static int watchpoint_exp_is_const (const struct expression *exp)
static void dtor_watchpoint (struct breakpoint *self)
static void re_set_watchpoint (struct breakpoint *b)
static int insert_watchpoint (struct bp_location *bl)
static int remove_watchpoint (struct bp_location *bl)
static int breakpoint_hit_watchpoint (const struct bp_location *bl, struct address_space *aspace, CORE_ADDR bp_addr, const struct target_waitstatus *ws)
static void check_status_watchpoint (bpstat bs)
static int resources_needed_watchpoint (const struct bp_location *bl)
static int works_in_software_mode_watchpoint (const struct breakpoint *b)
static enum print_stop_action print_it_watchpoint (bpstat bs)
static void print_mention_watchpoint (struct breakpoint *b)
static void print_recreate_watchpoint (struct breakpoint *b, struct ui_file *fp)
static enum bpstat_signal_value explains_signal_watchpoint (struct breakpoint *b, enum gdb_signal sig)
static int insert_masked_watchpoint (struct bp_location *bl)
static int remove_masked_watchpoint (struct bp_location *bl)
static int resources_needed_masked_watchpoint (const struct bp_location *bl)
static int works_in_software_mode_masked_watchpoint (const struct breakpoint *b)
static enum print_stop_action print_it_masked_watchpoint (bpstat bs)
static void print_one_detail_masked_watchpoint (const struct breakpoint *b, struct ui_out *uiout)
static void print_mention_masked_watchpoint (struct breakpoint *b)
static void print_recreate_masked_watchpoint (struct breakpoint *b, struct ui_file *fp)
static void watch_command_1 (const char *arg, int accessflag, int from_tty, int just_location, int internal)
void watch_command_wrapper (char *arg, int from_tty, int internal)
static void watch_maybe_just_location (char *arg, int accessflag, int from_tty)
static void watch_command (char *arg, int from_tty)
void rwatch_command_wrapper (char *arg, int from_tty, int internal)
static void rwatch_command (char *arg, int from_tty)
void awatch_command_wrapper (char *arg, int from_tty, int internal)
static void awatch_command (char *arg, int from_tty)
static void until_break_command_continuation (void *arg, int err)
void until_break_command (char *arg, int from_tty, int anywhere)
char * ep_parse_optional_if_clause (char **arg)
static void catch_fork_command_1 (char *arg, int from_tty, struct cmd_list_element *command)
static void catch_exec_command_1 (char *arg, int from_tty, struct cmd_list_element *command)
void init_ada_exception_breakpoint (struct breakpoint *b, struct gdbarch *gdbarch, struct symtab_and_line sal, char *addr_string, const struct breakpoint_ops *ops, int tempflag, int enabled, int from_tty)
static VEC (int)
static void catch_syscall_command_1 (char *arg, int from_tty, struct cmd_list_element *command)
static int compare_breakpoints (const void *a, const void *b)
void breakpoint_auto_delete (bpstat bs)
static int bp_location_compare (const void *ap, const void *bp)
static void bp_location_target_extensions_update (void)
static void download_tracepoint_locations (void)
static void swap_insertion (struct bp_location *left, struct bp_location *right)
static void force_breakpoint_reinsertion (struct bp_location *bl)
void breakpoint_retire_moribund (void)
static void bpstat_remove_bp_location (bpstat bps, struct breakpoint *bpt)
static int bpstat_remove_breakpoint_callback (struct thread_info *th, void *data)
static void say_where (struct breakpoint *b)
static void bp_location_dtor (struct bp_location *self)
static void base_breakpoint_dtor (struct breakpoint *self)
static struct bp_location * base_breakpoint_allocate_location (struct breakpoint *self)
static void base_breakpoint_re_set (struct breakpoint *b)
static int base_breakpoint_insert_location (struct bp_location *bl)
static int base_breakpoint_remove_location (struct bp_location *bl)
static int base_breakpoint_breakpoint_hit (const struct bp_location *bl, struct address_space *aspace, CORE_ADDR bp_addr, const struct target_waitstatus *ws)
static void base_breakpoint_check_status (bpstat bs)
static int base_breakpoint_works_in_software_mode (const struct breakpoint *b)
static int base_breakpoint_resources_needed (const struct bp_location *bl)
static enum print_stop_action base_breakpoint_print_it (bpstat bs)
static void base_breakpoint_print_one_detail (const struct breakpoint *self, struct ui_out *uiout)
static void base_breakpoint_print_mention (struct breakpoint *b)
static void base_breakpoint_print_recreate (struct breakpoint *b, struct ui_file *fp)
static void base_breakpoint_create_sals_from_address (char **arg, struct linespec_result *canonical, enum bptype type_wanted, char *addr_start, char **copy_arg)
static void base_breakpoint_create_breakpoints_sal (struct gdbarch *gdbarch, struct linespec_result *c, char *cond_string, char *extra_string, enum bptype type_wanted, enum bpdisp disposition, int thread, int task, int ignore_count, const struct breakpoint_ops *o, int from_tty, int enabled, int internal, unsigned flags)
static void base_breakpoint_decode_linespec (struct breakpoint *b, char **s, struct symtabs_and_lines *sals)
static enum bpstat_signal_value base_breakpoint_explains_signal (struct breakpoint *b, enum gdb_signal sig)
static void base_breakpoint_after_condition_true (struct bpstats *bs)
static void bkpt_re_set (struct breakpoint *b)
static int bkpt_insert_location (struct bp_location *bl)
static int bkpt_remove_location (struct bp_location *bl)
static int bkpt_breakpoint_hit (const struct bp_location *bl, struct address_space *aspace, CORE_ADDR bp_addr, const struct target_waitstatus *ws)
static int bkpt_resources_needed (const struct bp_location *bl)
static enum print_stop_action bkpt_print_it (bpstat bs)
static void bkpt_print_mention (struct breakpoint *b)
static void bkpt_print_recreate (struct breakpoint *tp, struct ui_file *fp)
static void bkpt_create_sals_from_address (char **arg, struct linespec_result *canonical, enum bptype type_wanted, char *addr_start, char **copy_arg)
static void bkpt_create_breakpoints_sal (struct gdbarch *gdbarch, struct linespec_result *canonical, char *cond_string, char *extra_string, enum bptype type_wanted, enum bpdisp disposition, int thread, int task, int ignore_count, const struct breakpoint_ops *ops, int from_tty, int enabled, int internal, unsigned flags)
static void bkpt_decode_linespec (struct breakpoint *b, char **s, struct symtabs_and_lines *sals)
static void internal_bkpt_re_set (struct breakpoint *b)
static void internal_bkpt_check_status (bpstat bs)
static enum print_stop_action internal_bkpt_print_it (bpstat bs)
static void internal_bkpt_print_mention (struct breakpoint *b)
static void momentary_bkpt_re_set (struct breakpoint *b)
static void momentary_bkpt_check_status (bpstat bs)
static enum print_stop_action momentary_bkpt_print_it (bpstat bs)
static void momentary_bkpt_print_mention (struct breakpoint *b)
static void longjmp_bkpt_dtor (struct breakpoint *self)
static int bkpt_probe_insert_location (struct bp_location *bl)
static int bkpt_probe_remove_location (struct bp_location *bl)
static void bkpt_probe_create_sals_from_address (char **arg, struct linespec_result *canonical, enum bptype type_wanted, char *addr_start, char **copy_arg)
static void bkpt_probe_decode_linespec (struct breakpoint *b, char **s, struct symtabs_and_lines *sals)
static void tracepoint_re_set (struct breakpoint *b)
static int tracepoint_breakpoint_hit (const struct bp_location *bl, struct address_space *aspace, CORE_ADDR bp_addr, const struct target_waitstatus *ws)
static void tracepoint_print_one_detail (const struct breakpoint *self, struct ui_out *uiout)
static void tracepoint_print_mention (struct breakpoint *b)
static void tracepoint_print_recreate (struct breakpoint *self, struct ui_file *fp)
static void tracepoint_create_sals_from_address (char **arg, struct linespec_result *canonical, enum bptype type_wanted, char *addr_start, char **copy_arg)
static void tracepoint_create_breakpoints_sal (struct gdbarch *gdbarch, struct linespec_result *canonical, char *cond_string, char *extra_string, enum bptype type_wanted, enum bpdisp disposition, int thread, int task, int ignore_count, const struct breakpoint_ops *ops, int from_tty, int enabled, int internal, unsigned flags)
static void tracepoint_decode_linespec (struct breakpoint *b, char **s, struct symtabs_and_lines *sals)
static void tracepoint_probe_create_sals_from_address (char **arg, struct linespec_result *canonical, enum bptype type_wanted, char *addr_start, char **copy_arg)
static void tracepoint_probe_decode_linespec (struct breakpoint *b, char **s, struct symtabs_and_lines *sals)
static void dprintf_re_set (struct breakpoint *b)
static void dprintf_print_recreate (struct breakpoint *tp, struct ui_file *fp)
static void dprintf_after_condition_true (struct bpstats *bs)
static void strace_marker_create_sals_from_address (char **arg, struct linespec_result *canonical, enum bptype type_wanted, char *addr_start, char **copy_arg)
static void strace_marker_create_breakpoints_sal (struct gdbarch *gdbarch, struct linespec_result *canonical, char *cond_string, char *extra_string, enum bptype type_wanted, enum bpdisp disposition, int thread, int task, int ignore_count, const struct breakpoint_ops *ops, int from_tty, int enabled, int internal, unsigned flags)
static void strace_marker_decode_linespec (struct breakpoint *b, char **s, struct symtabs_and_lines *sals)
void delete_breakpoint (struct breakpoint *bpt)
static void do_delete_breakpoint_cleanup (void *b)
struct cleanup * make_cleanup_delete_breakpoint (struct breakpoint *b)
static void iterate_over_related_breakpoints (struct breakpoint *b, void(*function)(struct breakpoint *, void *), void *data)
static void do_delete_breakpoint (struct breakpoint *b, void *ignore)
static void do_map_delete_breakpoint (struct breakpoint *b, void *ignore)
void delete_command (char *arg, int from_tty)
static int all_locations_are_pending (struct bp_location *loc)
static int ambiguous_names_p (struct bp_location *loc)
static struct symtab_and_line update_static_tracepoint (struct breakpoint *b, struct symtab_and_line sal)
static int locations_are_equal (struct bp_location *a, struct bp_location *b)
void update_breakpoint_locations (struct breakpoint *b, struct symtabs_and_lines sals, struct symtabs_and_lines sals_end)
static struct symtabs_and_lines addr_string_to_sals (struct breakpoint *b, char *addr_string, int *found)
static struct cleanup * prepare_re_set_context (struct breakpoint *b)
void breakpoint_re_set (void)
void breakpoint_re_set_thread (struct breakpoint *b)
void set_ignore_count (int bptnum, int count, int from_tty)
static struct bp_location * find_location_by_number (char *number)
void disable_breakpoint (struct breakpoint *bpt)
static void do_disable_breakpoint (struct breakpoint *b, void *ignore)
static void do_map_disable_breakpoint (struct breakpoint *b, void *ignore)
void enable_breakpoint (struct breakpoint *bpt)
static void do_enable_breakpoint (struct breakpoint *bpt, void *arg)
static void do_map_enable_breakpoint (struct breakpoint *b, void *ignore)
static void do_enable_breakpoint_disp (struct breakpoint *bpt, void *arg)
static void do_map_enable_once_breakpoint (struct breakpoint *bpt, void *ignore)
static void do_map_enable_count_breakpoint (struct breakpoint *bpt, void *countptr)
static void do_map_enable_delete_breakpoint (struct breakpoint *bpt, void *ignore)
static void set_breakpoint_cmd (char *args, int from_tty)
static void show_breakpoint_cmd (char *args, int from_tty)
static void invalidate_bp_value_on_memory_change (struct inferior *inferior, CORE_ADDR addr, ssize_t len, const bfd_byte *data)
void * deprecated_insert_raw_breakpoint (struct gdbarch *gdbarch, struct address_space *aspace, CORE_ADDR pc)
int deprecated_remove_raw_breakpoint (struct gdbarch *gdbarch, void *bp)
void insert_single_step_breakpoint (struct gdbarch *gdbarch, struct address_space *aspace, CORE_ADDR next_pc)
int single_step_breakpoints_inserted (void)
void remove_single_step_breakpoints (void)
void cancel_single_step_breakpoints (void)
static int is_syscall_catchpoint_enabled (struct breakpoint *bp)
int catch_syscall_enabled (void)
int catching_syscall_number (int syscall_number)
static void trace_command (char *arg, int from_tty)
static void ftrace_command (char *arg, int from_tty)
static void strace_command (char *arg, int from_tty)
static char * read_uploaded_action (void)
struct tracepoint * create_tracepoint_from_upload (struct uploaded_tp *utp)
static void trace_pass_set_count (struct tracepoint *tp, int count, int from_tty)
struct tracepoint * get_tracepoint (int num)
struct tracepoint * get_tracepoint_by_number_on_target (int num)
struct tracepoint * get_tracepoint_by_number (char **arg, struct get_number_or_range_state *state, int optional_p)
void print_recreate_thread (struct breakpoint *b, struct ui_file *fp)
static void save_breakpoints (char *filename, int from_tty, int(*filter)(const struct breakpoint *))
static void save_breakpoints_command (char *args, int from_tty)
static void save_tracepoints_command (char *args, int from_tty)
void add_catch_command (char *name, char *docstring, void(*sfunc)(char *args, int from_tty, struct cmd_list_element *command), completer_ftype *completer, void *user_data_catch, void *user_data_tcatch)
static void clear_syscall_counts (struct inferior *inf)
static void save_command (char *arg, int from_tty)
struct breakpoint * iterate_over_breakpoints (int(*callback)(struct breakpoint *, void *), void *data)
static int is_non_inline_function (struct breakpoint *b)
int pc_at_non_inline_function (struct address_space *aspace, CORE_ADDR pc, const struct target_waitstatus *ws)
void breakpoint_free_objfile (struct objfile *objfile)
void initialize_breakpoint_ops (void)
Variables
struct breakpoint_ops base_breakpoint_ops
static struct breakpoint_ops bkpt_base_breakpoint_ops
static struct breakpoint_ops internal_breakpoint_ops
static struct breakpoint_ops momentary_breakpoint_ops
static struct breakpoint_ops longjmp_breakpoint_ops
struct breakpoint_ops bkpt_breakpoint_ops
static struct breakpoint_ops bkpt_probe_breakpoint_ops
struct breakpoint_ops dprintf_breakpoint_ops
static const char dprintf_style_gdb [] = "gdb"
static const char dprintf_style_call [] = "call"
static const char dprintf_style_agent [] = "agent"
static const char *const dprintf_style_enums []
static const char * dprintf_style = dprintf_style_gdb
static char * dprintf_function = ""
static char * dprintf_channel = ""
static int disconnected_dprintf = 1
static int breakpoint_proceeded
static int can_use_hw_watchpoints
static enum auto_boolean pending_break_support
static int automatic_hardware_breakpoints
static enum auto_boolean always_inserted_mode = AUTO_BOOLEAN_AUTO
static const char condition_evaluation_both [] = "host or target"
static const char condition_evaluation_auto [] = "auto"
static const char condition_evaluation_host [] = "host"
static const char condition_evaluation_target [] = "target"
static const char *const condition_evaluation_enums []
static const char * condition_evaluation_mode_1 = condition_evaluation_auto
static const char * condition_evaluation_mode = condition_evaluation_auto
static int executing_breakpoint_commands
static int overlay_events_enabled
int target_exact_watchpoints = 0
struct breakpoint * breakpoint_chain
static struct bp_location ** bp_location
static unsigned bp_location_count
static CORE_ADDR bp_location_placed_address_before_address_max
static CORE_ADDR bp_location_shadow_len_after_address_max
static int rbreak_start_breakpoint_count
static int internal_breakpoint_number = -1
static const char *const longjmp_names []
static struct objfile_data * breakpoint_objfile_key
static struct minimal_symbol msym_not_found
static struct breakpoint_ops catch_fork_breakpoint_ops
static struct breakpoint_ops catch_vfork_breakpoint_ops
static struct breakpoint_ops catch_solib_breakpoint_ops
static struct inferior_data * catch_syscall_inferior_data = NULL
static struct breakpoint_ops catch_syscall_breakpoint_ops
static struct breakpoint_ops catch_exec_breakpoint_ops
static struct breakpoint_ops ranged_breakpoint_ops
static struct breakpoint_ops watchpoint_breakpoint_ops
static struct breakpoint_ops masked_watchpoint_breakpoint_ops
static struct bp_location_ops bp_location_ops
struct breakpoint_ops tracepoint_breakpoint_ops
static struct breakpoint_ops tracepoint_probe_breakpoint_ops
static struct breakpoint_ops strace_marker_breakpoint_ops
static void * single_step_breakpoints [2]
static struct gdbarch * single_step_gdbarch [2]
static struct uploaded_tp * this_utp
static int next_cmd
static struct cmd_list_element * catch_cmdlist
static struct cmd_list_element * tcatch_cmdlist
static struct cmd_list_element * enablebreaklist = NULL
Define Documentation
#define ALL_BP_LOCATIONS (B, BP_TMP)
Value:
for (BP_TMP = bp_location;                                      \
             BP_TMP < bp_location + bp_location_count && (B = *BP_TMP); \
             BP_TMP++)
Definition at line 538 of file breakpoint.c.
Referenced by bp_location_target_extensions_update(), breakpoint_free_objfile(), breakpoint_here_p(), breakpoint_init_inferior(), breakpoint_program_space_exit(), breakpoint_thread_match(), detach_breakpoints(), disable_breakpoints_in_shlibs(), disable_breakpoints_in_unloaded_shlib(), insert_bp_location(), insert_breakpoint_locations(), iterate_over_bp_locations(), mark_breakpoints_out(), reattach_breakpoints(), regular_breakpoint_inserted_here_p(), remove_breakpoints(), remove_breakpoints_pid(), set_condition_evaluation_mode(), software_breakpoint_inserted_here_p(), update_breakpoints_after_exec(), update_global_location_list(), and update_inserted_breakpoint_locations().
#define ALL_BP_LOCATIONS_AT_ADDR (BP_LOCP_TMP, BP_LOCP_START, ADDRESS)
Value:
for (BP_LOCP_START = BP_LOCP_START == NULL ? get_first_locp_gte_addr (ADDRESS) : BP_LOCP_START, \
             BP_LOCP_TMP = BP_LOCP_START;                               \
             BP_LOCP_START                                              \
             && (BP_LOCP_TMP < bp_location + bp_location_count          \
             && (*BP_LOCP_TMP)->address == ADDRESS);                    \
             BP_LOCP_TMP++)
Definition at line 549 of file breakpoint.c.
Referenced by build_target_command_list(), build_target_condition_list(), and force_breakpoint_reinsertion().
#define ALL_BREAKPOINTS (B) for (B = breakpoint_chain; B; B = B->next)
Definition at line 527 of file breakpoint.c.
Referenced by bpstat_check_watchpoint(), bpstat_should_step(), bpstat_stop_status(), breakpoint_1(), breakpoint_hit_catch_solib(), catching_syscall_number(), clear_breakpoint_hit_counts(), clear_command(), condition_command(), delete_breakpoint(), delete_command(), describe_other_breakpoints(), disable_command(), disable_overlay_breakpoints(), disable_watchpoints_before_interactive_call_start(), do_captured_breakpoint_query(), enable_command(), enable_overlay_breakpoints(), enable_watchpoints_after_interactive_call_stop(), find_location_by_number(), get_breakpoint(), hardware_watchpoint_inserted_in_range(), hw_breakpoint_used_count(), hw_watchpoint_used_count_others(), insert_breakpoint_locations(), insert_breakpoints(), invalidate_bp_value_on_memory_change(), pc_at_non_inline_function(), save_breakpoints(), set_ignore_count(), set_longjmp_breakpoint_for_call_dummy(), update_dprintf_commands(), update_global_location_list(), VEC(), and watchpoints_triggered().
#define ALL_BREAKPOINTS_SAFE (B, TMP)
Value:
for (B = breakpoint_chain;      \
             B ? (TMP=B->next, 1): 0;   \
             B = TMP)
Definition at line 529 of file breakpoint.c.
Referenced by breakpoint_auto_delete(), breakpoint_init_inferior(), breakpoint_program_space_exit(), breakpoint_re_set(), check_longjmp_breakpoint_for_call_dummy(), delete_command(), delete_longjmp_breakpoint(), delete_longjmp_breakpoint_at_next_stop(), delete_std_terminate_breakpoint(), delete_trace_command(), iterate_over_breakpoints(), map_breakpoint_numbers(), remove_jit_event_breakpoints(), remove_solib_event_breakpoints(), remove_thread_event_breakpoints(), remove_threaded_breakpoints(), set_longjmp_breakpoint(), set_std_terminate_breakpoint(), and update_breakpoints_after_exec().
#define ALL_TRACEPOINTS (B)
Value:
for (B = breakpoint_chain; B; B = B->next)  \
    if (is_tracepoint (B))
Definition at line 559 of file breakpoint.c.
Referenced by delete_trace_command(), download_tracepoint_locations(), get_tracepoint(), get_tracepoint_by_number(), get_tracepoint_by_number_on_target(), and trace_pass_command().
#define BP_HARDWAREFLAG 2
Definition at line 4763 of file breakpoint.c.
Referenced by break_command_1(), hbreak_command(), and thbreak_command().
#define BP_TEMPFLAG 1
Definition at line 4762 of file breakpoint.c.
Referenced by break_command_1(), tbreak_command(), and thbreak_command().
#define BREAK_ARGS_HELP (command) command" [PROBE_MODIFIER] [LOCATION] [thread THREADNUM] [if CONDITION]\n\PROBE_MODIFIER shall be present if the command is to be placed in a\n\probe point. Accepted values are `-probe' (for a generic, automatically\n\guessed probe type) or `-probe-stap' (for a SystemTap probe).\n\LOCATION may be a line number, function name, or \"*\" and an address.\n\If a line number is specified, break at start of code for that line.\n\If a function is specified, break at start of code for that function.\n\If an address is specified, break at that exact address.\n\With no LOCATION, uses current execution address of the selected\n\stack frame. This is useful for breaking on return to a stack frame.\n\\n\THREADNUM is the number from \"info threads\".\n\CONDITION is a boolean expression.\n\\n\Multiple breakpoints at one place are permitted, and useful if their\n\conditions are different.\n\\n\Do \"help breakpoints\" for info on other commands dealing with breakpoints."
Definition at line 15658 of file breakpoint.c.
#define internal_error_pure_virtual_called () gdb_assert_not_reached ("pure virtual function called")
Definition at line 12697 of file breakpoint.c.
Referenced by base_breakpoint_breakpoint_hit(), base_breakpoint_create_breakpoints_sal(), base_breakpoint_create_sals_from_address(), base_breakpoint_decode_linespec(), base_breakpoint_insert_location(), base_breakpoint_print_it(), base_breakpoint_print_mention(), base_breakpoint_print_recreate(), base_breakpoint_remove_location(), base_breakpoint_resources_needed(), and base_breakpoint_works_in_software_mode().
#define NUM_LONGJMP_NAMES ARRAY_SIZE(longjmp_names)
Definition at line 3071 of file breakpoint.c.
Referenced by create_longjmp_master_breakpoint().
#define WP_DELETED 1
Definition at line 4754 of file breakpoint.c.
Referenced by bpstat_check_watchpoint(), and watchpoint_check().
#define WP_IGNORE 4
Definition at line 4760 of file breakpoint.c.
Referenced by bpstat_check_watchpoint(), and watchpoint_check().
#define WP_VALUE_CHANGED 2
Definition at line 4756 of file breakpoint.c.
Referenced by bpstat_check_watchpoint(), and watchpoint_check().
#define WP_VALUE_NOT_CHANGED 3
Definition at line 4758 of file breakpoint.c.
Referenced by bpstat_check_watchpoint(), and watchpoint_check().
Enumeration Type Documentation
enum catch_fork_kind
Enumerator:
catch_fork_temporary
catch_vfork_temporary
catch_fork_permanent
catch_vfork_permanent
Definition at line 11530 of file breakpoint.c.
enum exception_event_kind
Enumerator:
EX_EVENT_THROW
EX_EVENT_RETHROW
EX_EVENT_CATCH
EX_EVENT_THROW
EX_EVENT_RETHROW
EX_EVENT_CATCH
Definition at line 86 of file breakpoint.c.
enum insertion_state_t
Enumerator:
mark_inserted
mark_uninserted
Definition at line 196 of file breakpoint.c.
Function Documentation
void _initialize_breakpoint (void)
void add_catch_command (char * name, char * docstring, void(*)(char *args, int from_tty, struct cmd_list_element *command) sfunc, completer_ftype * completer, void * user_data_catch, void * user_data_tcatch)
Definition at line 15685 of file breakpoint.c.
References add_cmd(), class_breakpoint, set_cmd_context(), set_cmd_sfunc(), and cmd_list_element::sfunc.
Referenced by _initialize_ada_language(), _initialize_break_catch_sig(), and _initialize_break_catch_throw().
static struct bp_location * add_location_to_breakpoint (struct breakpoint * b, const struct symtab_and_line * sal) [static, read]
Definition at line 8863 of file breakpoint.c.
References bp_location::address, adjust_breakpoint_address(), allocate_bp_location(), symtab_and_line::explicit_line, symtab_and_line::explicit_pc, gdb_assert, bp_location::gdbarch, breakpoint::gdbarch, get_sal_arch(), symtab_and_line::line, bp_location::line_number, breakpoint::loc, bp_location::next, symtab_and_line::pc, bp_location::probe, symtab_and_line::probe, bp_location::pspace, symtab_and_line::pspace, bp_location::requested_address, bp_location::section, symtab_and_line::section, set_breakpoint_location_function(), bp_location::symtab, symtab_and_line::symtab, and breakpoint::type.
Referenced by init_breakpoint_sal(), init_raw_breakpoint(), and update_breakpoint_locations().
void add_solib_catchpoint (char * arg, int is_load, int is_temp, int enabled)
Definition at line 7988 of file breakpoint.c.
References _, solib_catchpoint::base, bp_disabled, bp_enabled, catch_solib_breakpoint_ops, solib_catchpoint::compiled, discard_cleanups(), breakpoint::enable_state, error(), get_current_arch(), get_regcomp_error(), init_catchpoint(), install_breakpoint(), solib_catchpoint::is_load, make_cleanup(), solib_catchpoint::regex, skip_spaces(), and xfree().
Referenced by catch_load_or_unload(), and mi_catch_load_unload().
static void add_to_breakpoint_chain (struct breakpoint * b) [static]
Definition at line 6976 of file breakpoint.c.
References breakpoint_chain, and breakpoint::next.
Referenced by install_breakpoint().
static struct symtabs_and_lines addr_string_to_sals (struct breakpoint * b, char * addr_string, int * found) [static, read]
Definition at line 14098 of file breakpoint.c.
References bp_disabled, bp_static_tracepoint, gdb_exception::error, find_condition_and_thread(), gdb_assert, symtabs_and_lines::nelts, NOT_FOUND_ERROR, symtab_and_line::pc, gdb_exception::reason, resolve_sal_pc(), RETURN_MASK_ERROR, symtabs_and_lines::sals, strace_marker_p(), throw_exception(), TRY_CATCH, and update_static_tracepoint().
Referenced by breakpoint_re_set_default().
static CORE_ADDR adjust_breakpoint_address (struct gdbarch * gdbarch, CORE_ADDR bpaddr, enum bptype bptype) [static]
Referenced by add_location_to_breakpoint(), set_breakpoint_location_function(), set_gdbarch_adjust_breakpoint_address(), and watch_command_1().
static CORE_ADDR adjust_breakpoint_address (struct gdbarch * gdbarch, CORE_ADDR bpaddr, enum bptype bptype) [static]
Definition at line 6835 of file breakpoint.c.
References bp_access_watchpoint, bp_catchpoint, bp_hardware_watchpoint, bp_read_watchpoint, bp_watchpoint, breakpoint_adjustment_warning(), gdbarch_adjust_breakpoint_address(), and gdbarch_adjust_breakpoint_address_p().
static void agent_printf_command (char * arg, int from_tty) [static]
Definition at line 9989 of file breakpoint.c.
References _, and error().
static int all_locations_are_pending (struct bp_location * loc) [static]
Definition at line 13767 of file breakpoint.c.
References program_space::executing_startup, breakpoint::loc, bp_location::next, bp_location::pspace, and bp_location::shlib_disabled.
Referenced by update_breakpoint_locations().
static struct counted_command_line* alloc_counted_command_line (struct command_line * commands) [static, read]
Definition at line 668 of file breakpoint.c.
References counted_command_line::commands, counted_command_line::refc, and xmalloc().
Referenced by breakpoint_set_commands(), and do_map_commands_command().
static struct bp_location * allocate_bp_location (struct breakpoint * bpt) [static, read]
Definition at line 6940 of file breakpoint.c.
References breakpoint_ops::allocate_location, and breakpoint::ops.
Referenced by add_location_to_breakpoint(), momentary_breakpoint_from_master(), and update_watchpoint().
static int ambiguous_names_p (struct bp_location * loc) [static]
Definition at line 13781 of file breakpoint.c.
References bp_location::function_name, name, bp_location::next, streq(), xcalloc(), and xfree().
Referenced by update_breakpoint_locations().
static void awatch_command (char * arg, int from_tty) [static]
Definition at line 11352 of file breakpoint.c.
References hw_access, and watch_maybe_just_location().
void awatch_command_wrapper (char * arg, int from_tty, int internal)
Definition at line 11346 of file breakpoint.c.
References hw_access, and watch_command_1().
Referenced by bppy_init(), and mi_cmd_break_watch().
static void base_breakpoint_after_condition_true (struct bpstats * bs) [static]
Definition at line 12814 of file breakpoint.c.
static struct bp_location* base_breakpoint_allocate_location (struct breakpoint * self) [static, read]
Definition at line 12682 of file breakpoint.c.
References init_bp_location().
static int base_breakpoint_breakpoint_hit (const struct bp_location * bl, struct address_space * aspace, CORE_ADDR bp_addr, const struct target_waitstatus * ws) [static]
Definition at line 12713 of file breakpoint.c.
References internal_error_pure_virtual_called.
static void base_breakpoint_check_status (bpstat bs) [static]
Definition at line 12722 of file breakpoint.c.
static void base_breakpoint_create_breakpoints_sal (struct gdbarch * gdbarch, struct linespec_result * c, char * cond_string, char * extra_string, enum bptype type_wanted, enum bpdisp disposition, int thread, int task, int ignore_count, const struct breakpoint_ops * o, int from_tty, int enabled, int internal, unsigned flags) [static]
Definition at line 12781 of file breakpoint.c.
References internal_error_pure_virtual_called.
static void base_breakpoint_create_sals_from_address (char ** arg, struct linespec_result * canonical, enum bptype type_wanted, char * addr_start, char ** copy_arg) [static]
Definition at line 12771 of file breakpoint.c.
References internal_error_pure_virtual_called.
static void base_breakpoint_decode_linespec (struct breakpoint * b, char ** s, struct symtabs_and_lines * sals) [static]
Definition at line 12797 of file breakpoint.c.
References internal_error_pure_virtual_called.
static void base_breakpoint_dtor (struct breakpoint * self) [static]
Definition at line 12671 of file breakpoint.c.
References decref_counted_command_line(), and xfree().
static enum bpstat_signal_value base_breakpoint_explains_signal (struct breakpoint * b, enum gdb_signal sig) [static]
Definition at line 12806 of file breakpoint.c.
References BPSTAT_SIGNAL_HIDE.
static int base_breakpoint_insert_location (struct bp_location * bl) [static]
Definition at line 12701 of file breakpoint.c.
References internal_error_pure_virtual_called.
static enum print_stop_action base_breakpoint_print_it (bpstat bs) [static]
Definition at line 12746 of file breakpoint.c.
References internal_error_pure_virtual_called.
static void base_breakpoint_print_mention (struct breakpoint * b) [static]
Definition at line 12759 of file breakpoint.c.
References internal_error_pure_virtual_called.
static void base_breakpoint_print_one_detail (const struct breakpoint * self, struct ui_out * uiout) [static]
Definition at line 12752 of file breakpoint.c.
static void base_breakpoint_print_recreate (struct breakpoint * b, struct ui_file * fp) [static]
Definition at line 12765 of file breakpoint.c.
References internal_error_pure_virtual_called.
static void base_breakpoint_re_set (struct breakpoint * b) [static]
Definition at line 12692 of file breakpoint.c.
static int base_breakpoint_remove_location (struct bp_location * bl) [static]
Definition at line 12707 of file breakpoint.c.
References internal_error_pure_virtual_called.
static int base_breakpoint_resources_needed (const struct bp_location * bl) [static]
Definition at line 12740 of file breakpoint.c.
References internal_error_pure_virtual_called.
static int base_breakpoint_works_in_software_mode (const struct breakpoint * b) [static]
Definition at line 12731 of file breakpoint.c.
References internal_error_pure_virtual_called.
static int bkpt_breakpoint_hit (const struct bp_location * bl, struct address_space * aspace, CORE_ADDR bp_addr, const struct target_waitstatus * ws) [static]
Definition at line 12879 of file breakpoint.c.
References bp_location::address, program_space::aspace, breakpoint_address_match(), target_waitstatus::kind, overlay_debugging, bp_location::pspace, bp_location::section, section_is_mapped(), section_is_overlay(), target_waitstatus::sig, TARGET_WAITKIND_STOPPED, and target_waitstatus::value.
Referenced by initialize_breakpoint_ops().
static void bkpt_create_breakpoints_sal (struct gdbarch * gdbarch, struct linespec_result * canonical, char * cond_string, char * extra_string, enum bptype type_wanted, enum bpdisp disposition, int thread, int task, int ignore_count, const struct breakpoint_ops * ops, int from_tty, int enabled, int internal, unsigned flags) [static]
Definition at line 13002 of file breakpoint.c.
References create_breakpoints_sal_default().
Referenced by initialize_breakpoint_ops().
static void bkpt_create_sals_from_address (char ** arg, struct linespec_result * canonical, enum bptype type_wanted, char * addr_start, char ** copy_arg) [static]
Definition at line 12992 of file breakpoint.c.
References create_sals_from_address_default().
Referenced by initialize_breakpoint_ops().
static void bkpt_decode_linespec (struct breakpoint * b, char ** s, struct symtabs_and_lines * sals) [static]
Definition at line 13023 of file breakpoint.c.
References decode_linespec_default().
Referenced by initialize_breakpoint_ops().
static int bkpt_insert_location (struct bp_location * bl) [static]
Definition at line 12859 of file breakpoint.c.
References bp_loc_hardware_breakpoint, bp_location::gdbarch, bp_location::loc_type, bp_location::target_info, target_insert_breakpoint(), and target_insert_hw_breakpoint.
Referenced by bkpt_probe_insert_location(), and initialize_breakpoint_ops().
static enum print_stop_action bkpt_print_it (bpstat bs) [static]
Definition at line 12908 of file breakpoint.c.
References bp_location::address, annotate_breakpoint(), async_reason_lookup(), bpstats::bp_location_at, bpdisp_text(), breakpoint_adjustment_warning(), bpstats::breakpoint_at, current_uiout, disp_del, breakpoint::disposition, EXEC_ASYNC_BREAKPOINT_HIT, gdb_assert, breakpoint::number, PRINT_SRC_AND_LOC, bp_location::requested_address, ui_out_field_int(), ui_out_field_string(), ui_out_is_mi_like_p(), and ui_out_text().
Referenced by initialize_breakpoint_ops().
static void bkpt_print_mention (struct breakpoint * b) [static]
Definition at line 12943 of file breakpoint.c.
References _, bp_breakpoint, bp_dprintf, bp_gnu_ifunc_resolver, bp_hardware_breakpoint, current_uiout, disp_del, breakpoint::disposition, breakpoint::number, printf_filtered(), say_where(), breakpoint::type, and ui_out_is_mi_like_p().
Referenced by initialize_breakpoint_ops().
static void bkpt_print_recreate (struct breakpoint * tp, struct ui_file * fp) [static]
Definition at line 12972 of file breakpoint.c.
References _, breakpoint::addr_string, bp_breakpoint, bp_hardware_breakpoint, disp_del, breakpoint::disposition, fprintf_unfiltered(), internal_error(), print_recreate_thread(), and breakpoint::type.
Referenced by initialize_breakpoint_ops().
static void bkpt_probe_create_sals_from_address (char ** arg, struct linespec_result * canonical, enum bptype type_wanted, char * addr_start, char ** copy_arg) [static]
Definition at line 13220 of file breakpoint.c.
References linespec_result::addr_string, linespec_sals::canonical, parse_probes(), linespec_sals::sals, and VEC_safe_push.
Referenced by initialize_breakpoint_ops(), and tracepoint_probe_create_sals_from_address().
static void bkpt_probe_decode_linespec (struct breakpoint * b, char ** s, struct symtabs_and_lines * sals) [static]
Definition at line 13236 of file breakpoint.c.
References _, error(), parse_probes(), and symtabs_and_lines::sals.
Referenced by initialize_breakpoint_ops(), and tracepoint_probe_decode_linespec().
static int bkpt_probe_insert_location (struct bp_location * bl) [static]
Definition at line 13196 of file breakpoint.c.
References bkpt_insert_location(), bp_location::gdbarch, probe::pops, bp_location::probe, and probe_ops::set_semaphore.
Referenced by initialize_breakpoint_ops().
static int bkpt_probe_remove_location (struct bp_location * bl) [static]
Definition at line 13211 of file breakpoint.c.
References bkpt_remove_location(), probe_ops::clear_semaphore, bp_location::gdbarch, probe::pops, and bp_location::probe.
Referenced by initialize_breakpoint_ops().
static void bkpt_re_set (struct breakpoint * b) [static]
Definition at line 12845 of file breakpoint.c.
References breakpoint::addr_string, breakpoint_re_set_default(), and delete_breakpoint().
Referenced by initialize_breakpoint_ops().
static int bkpt_remove_location (struct bp_location * bl) [static]
Definition at line 12870 of file breakpoint.c.
References bp_loc_hardware_breakpoint, bp_location::gdbarch, bp_location::loc_type, bp_location::target_info, target_remove_breakpoint(), and target_remove_hw_breakpoint.
Referenced by bkpt_probe_remove_location(), and initialize_breakpoint_ops().
static int bkpt_resources_needed (const struct bp_location * bl) [static]
Definition at line 12900 of file breakpoint.c.
References bp_hardware_breakpoint, gdb_assert, bp_location::owner, and breakpoint::type.
Referenced by initialize_breakpoint_ops().
static const char* bp_condition_evaluator (struct breakpoint * b) [static]
Definition at line 5686 of file breakpoint.c.
References bp_location::cond_bytecode, condition_evaluation_both, condition_evaluation_host, condition_evaluation_target, gdb_evaluates_breakpoint_condition_p(), is_breakpoint(), breakpoint::loc, bp_location::next, and target_supports_evaluation_of_breakpoint_conditions.
Referenced by print_breakpoint_location(), and print_one_breakpoint_location().
static int bp_loc_is_permanent (struct bp_location * loc) [static]
Definition at line 8910 of file breakpoint.c.
References bp_location::address, do_cleanups(), gdb_assert, bp_location::gdbarch, gdbarch_breakpoint_from_pc(), len, make_show_memory_breakpoints_cleanup(), memcmp(), bp_location::pspace, save_current_space_and_thread(), switch_to_program_space_and_thread(), and target_read_memory().
Referenced by init_breakpoint_sal().
static int bp_location_compare (const void * ap, const void * bp) [static]
Definition at line 11981 of file breakpoint.c.
References bp_location::address, bp_permanent, breakpoint::enable_state, program_space::num, breakpoint::number, bp_location::owner, and bp_location::pspace.
Referenced by update_global_location_list().
static int bp_location_compare_addrs (const void * ap, const void * bp) [static]
Definition at line 867 of file breakpoint.c.
References bp_location::address.
Referenced by get_first_locp_gte_addr().
static const char* bp_location_condition_evaluator (struct bp_location * bl) [static]
Definition at line 5722 of file breakpoint.c.
References bp_location::cond_bytecode, condition_evaluation_host, condition_evaluation_target, gdb_evaluates_breakpoint_condition_p(), is_breakpoint(), bp_location::owner, and target_supports_evaluation_of_breakpoint_conditions.
Referenced by print_breakpoint_location().
static void bp_location_dtor (struct bp_location * self) [static]
Definition at line 12654 of file breakpoint.c.
References free_agent_expr(), and xfree().
static int bp_location_has_shadow (struct bp_location * bl) [static]
Definition at line 1405 of file breakpoint.c.
References bp_loc_software_breakpoint, bp_location::inserted, bp_location::loc_type, bp_target_info::shadow_len, and bp_location::target_info.
Referenced by bp_location_target_extensions_update(), and breakpoint_xfer_memory().
static void bp_location_target_extensions_update (void) [static]
Definition at line 12020 of file breakpoint.c.
References bp_location::address, ALL_BP_LOCATIONS, bp_location_has_shadow(), gdb_assert, bp_target_info::placed_address, bp_target_info::shadow_len, and bp_location::target_info.
Referenced by update_global_location_list().
const char* bpdisp_text (enum bpdisp disp)
Definition at line 367 of file breakpoint.c.
References int.
Referenced by bkpt_print_it(), print_it_catch_exec(), print_it_catch_fork(), print_it_catch_solib(), print_it_catch_syscall(), print_it_catch_vfork(), print_it_exception(), print_it_exception_catchpoint(), print_it_ranged_breakpoint(), and print_one_breakpoint_location().
static bpstat bpstat_alloc (struct bp_location * bl, bpstat ** bs_link_pointer) [static]
Definition at line 4655 of file breakpoint.c.
References bpstats::bp_location_at, bpstats::breakpoint_at, bpstats::commands, incref_bp_location(), bpstats::next, bpstats::old_val, bp_location::owner, bpstats::print_it, print_it_normal, and xmalloc().
Referenced by bpstat_stop_status().
int bpstat_causes_stop (bpstat bs)
Definition at line 5637 of file breakpoint.c.
References bpstats::next, and bpstats::stop.
Referenced by bpstat_stop_status(), and handle_inferior_event().
static void bpstat_check_breakpoint_conditions (bpstat bs, ptid_t ptid) [static]
Definition at line 5093 of file breakpoint.c.
References _, block_innermost_frame(), bpstats::bp_location_at, bpstats::breakpoint_at, breakpoint_cond_eval(), catch_errors(), bp_location::cond, watchpoint::cond_exp, watchpoint::cond_exp_valid_block, disp_del_at_next_stop, breakpoint::disposition, breakpoint::frame_id, frame_id_eq(), frame_id_p(), gdb_assert, gdbpy_should_stop(), get_current_frame(), get_stack_frame_id(), breakpoint::hit_count, breakpoint::ignore_count, is_watchpoint(), observer_notify_breakpoint_modified(), pid_to_thread_id(), breakpoint::py_bp_object, RETURN_MASK_ALL, select_frame(), bpstats::stop, breakpoint::thread, value_free_to_mark(), value_mark(), and warning().
Referenced by bpstat_stop_status().
static int bpstat_check_location (const struct bp_location * bl, struct address_space * aspace, CORE_ADDR bp_addr, const struct target_waitstatus * ws) [static]
Definition at line 4915 of file breakpoint.c.
References breakpoint_ops::breakpoint_hit, gdb_assert, breakpoint::ops, and bp_location::owner.
Referenced by bpstat_stop_status(), and pc_at_non_inline_function().
static void bpstat_check_watchpoint (bpstat bs) [static]
Definition at line 4931 of file breakpoint.c.
References _, ALL_BREAKPOINTS, watchpoint::base, bp_access_watchpoint, bp_hardware_watchpoint, bpstats::bp_location_at, bp_read_watchpoint, bp_watchpoint, bpstats::breakpoint_at, catch_errors(), do_cleanups(), gdb_assert, hw_access, hw_read, make_cleanup(), breakpoint::number, bpstats::print_it, print_it_done, print_it_noop, printf_filtered(), RETURN_MASK_ALL, bpstats::stop, breakpoint::type, watch_triggered_unknown, watch_triggered_yes, watchpoint_check(), watchpoint_del_at_next_stop(), watchpoint::watchpoint_triggered, bp_location::watchpoint_type, WP_DELETED, WP_IGNORE, WP_VALUE_CHANGED, WP_VALUE_NOT_CHANGED, xfree(), and xstrprintf().
Referenced by check_status_watchpoint().
void bpstat_clear (bpstat * bsp)
Definition at line 4139 of file breakpoint.c.
References bpstat_free(), bpstats::next, and p.
Referenced by clear_proceed_status_thread(), clear_thread_inferior_resources(), discard_infcall_control_state(), handle_inferior_event(), and restore_infcall_control_state().
void bpstat_clear_actions (void)
Definition at line 4274 of file breakpoint.c.
References bpstats::commands, thread_info::control, decref_counted_command_line(), find_thread_ptid(), inferior_ptid, bpstats::next, null_ptid, bpstats::old_val, ptid_equal(), thread_control_state::stop_bpstat, and value_free().
Referenced by do_bpstat_clear_actions_cleanup(), and inferior_event_handler().
bpstat bpstat_copy (bpstat bs)
Definition at line 4160 of file breakpoint.c.
References bpstats::bp_location_at, bpstats::commands, incref_bp_location(), incref_counted_command_line(), memcpy(), bpstats::next, bpstats::old_val, p, release_value(), value_copy(), and xmalloc().
Referenced by save_infcall_control_state().
void bpstat_do_actions (void)
Definition at line 4435 of file breakpoint.c.
References bpstat_do_actions_1(), discard_cleanups(), inferior_ptid, inferior_thread(), is_executing(), is_exited(), make_bpstat_clear_actions_cleanup(), null_ptid, ptid_equal(), and target_has_execution.
Referenced by command_handler(), command_loop(), gdb_cmd(), gdb_immediate_command(), inferior_event_handler(), and mi_execute_command().
static int bpstat_do_actions_1 (bpstat * bsp) [static]
Definition at line 4346 of file breakpoint.c.
References cleanup_executing_breakpoints(), command_line_is_silent(), counted_command_line::commands, bpstats::commands, do_cleanups(), execute_control_command(), make_cleanup(), make_cleanup_decref_counted_command_line(), command_line::next, bpstats::next, prevent_dont_repeat(), and target_can_async_p.
Referenced by bpstat_do_actions(), and dprintf_after_condition_true().
enum bpstat_signal_value bpstat_explains_signal (bpstat bsp, enum gdb_signal sig)
Definition at line 4211 of file breakpoint.c.
References BPSTAT_SIGNAL_HIDE, BPSTAT_SIGNAL_NO, bpstats::breakpoint_at, breakpoint_ops::explains_signal, bpstats::next, and breakpoint::ops.
Referenced by handle_inferior_event(), and handle_syscall_event().
bpstat bpstat_find_breakpoint (bpstat bsp, struct breakpoint * breakpoint)
Definition at line 4195 of file breakpoint.c.
References bpstats::breakpoint_at, and bpstats::next.
Referenced by finish_command_continuation().
static void bpstat_free (bpstat bs) [static]
Definition at line 4126 of file breakpoint.c.
References bpstats::bp_location_at, bpstats::commands, decref_bp_location(), decref_counted_command_line(), bpstats::old_val, value_free(), and xfree().
Referenced by bpstat_clear().
int bpstat_num (bpstat * bsp, int * num)
Definition at line 4252 of file breakpoint.c.
References bpstats::next, and breakpoint::number.
Referenced by continue_command(), and program_info().
enum print_stop_action bpstat_print (bpstat bs, int kind)
Definition at line 4606 of file breakpoint.c.
References bpstats::next, print_bp_stop_message(), PRINT_NOTHING, print_solib_event(), PRINT_SRC_AND_LOC, PRINT_SRC_ONLY, PRINT_UNKNOWN, and TARGET_WAITKIND_LOADED.
Referenced by mi_on_normal_stop(), and normal_stop().
static void bpstat_remove_bp_location (bpstat bps, struct breakpoint * bpt) [static]
Definition at line 12578 of file breakpoint.c.
References bpstats::breakpoint_at, bpstats::next, and bpstats::old_val.
Referenced by bpstat_remove_breakpoint_callback().
static int bpstat_remove_breakpoint_callback (struct thread_info * th, void * data) [static]
Definition at line 12593 of file breakpoint.c.
References bpstat_remove_bp_location(), thread_info::control, and thread_control_state::stop_bpstat.
Referenced by delete_breakpoint().
int bpstat_should_step (void)
Definition at line 5626 of file breakpoint.c.
References ALL_BREAKPOINTS, bp_watchpoint, breakpoint::loc, and breakpoint::type.
Referenced by currently_stepping(), proceed(), and resume().
bpstat bpstat_stop_status (struct address_space * aspace, CORE_ADDR bp_addr, ptid_t ptid, const struct target_waitstatus * ws)
Definition at line 5236 of file breakpoint.c.
References breakpoint_ops::after_condition_true, ALL_BREAKPOINTS, bp_disabled, bp_hardware_watchpoint, bp_permanent, bp_shlib_event, bp_watchpoint_scope, bpstat_alloc(), bpstat_causes_stop(), bpstat_check_breakpoint_conditions(), bpstat_check_location(), bpstats::breakpoint_at, breakpoint_location_address_match(), breakpoint_ops::check_status, command_line_is_silent(), counted_command_line::commands, breakpoint::commands, bpstats::commands, disp_disable, breakpoint::disposition, breakpoint::enable_count, breakpoint::enable_state, bp_location::enabled, handle_solib_event(), breakpoint::hit_count, incref_counted_command_line(), is_hardware_watchpoint(), breakpoint::loc, bp_location::next, bpstats::next, observer_notify_breakpoint_modified(), breakpoint::ops, bpstats::print, bpstats::print_it, print_it_noop, breakpoint::related_breakpoint, bp_location::shlib_disabled, breakpoint::silent, bpstats::stop, breakpoint::type, update_global_location_list(), update_watchpoint(), VEC_iterate, watch_triggered_yes, and watchpoint::watchpoint_triggered.
Referenced by handle_inferior_event(), and handle_syscall_event().
struct bpstat_what bpstat_what (bpstat bs_head) [read]
Definition at line 5427 of file breakpoint.c.
References _, bp_access_watchpoint, bp_breakpoint, bp_call_dummy, bp_catchpoint, bp_dprintf, bp_exception, bp_exception_master, bp_exception_resume, bp_fast_tracepoint, bp_finish, bp_gnu_ifunc_resolver, bp_gnu_ifunc_resolver_return, bp_hardware_breakpoint, bp_hardware_watchpoint, bp_hp_step_resume, bp_jit_event, bp_longjmp, bp_longjmp_call_dummy, bp_longjmp_master, bp_longjmp_resume, bp_none, bp_overlay_event, bp_read_watchpoint, bp_shlib_event, bp_static_tracepoint, bp_std_terminate, bp_std_terminate_master, bp_step_resume, bp_thread_event, bp_tracepoint, bp_until, bp_watchpoint, bp_watchpoint_scope, BPSTAT_WHAT_CLEAR_LONGJMP_RESUME, BPSTAT_WHAT_HP_STEP_RESUME, BPSTAT_WHAT_KEEP_CHECKING, BPSTAT_WHAT_SET_LONGJMP_RESUME, BPSTAT_WHAT_SINGLE, BPSTAT_WHAT_STEP_RESUME, BPSTAT_WHAT_STOP_NOISY, BPSTAT_WHAT_STOP_SILENT, bpstat_what::call_dummy, debug_infrun, fprintf_unfiltered(), gdb_stdlog, gnu_ifunc_resolver_return_stop, gnu_ifunc_resolver_stop, handle_jit_event(), internal_error(), bpstat_what::is_longjmp, bpstat_what::main_action, max, STOP_NONE, STOP_STACK_DUMMY, STOP_STD_TERMINATE, and breakpoint::type.
Referenced by handle_inferior_event().
static const char* bptype_string (enum bptype type) [static]
Definition at line 5805 of file breakpoint.c.
References _, bp_access_watchpoint, bp_breakpoint, bp_call_dummy, bp_catchpoint, bp_dprintf, bp_exception, bp_exception_master, bp_exception_resume, bp_fast_tracepoint, bp_finish, bp_gnu_ifunc_resolver, bp_gnu_ifunc_resolver_return, bp_hardware_breakpoint, bp_hardware_watchpoint, bp_hp_step_resume, bp_jit_event, bp_longjmp, bp_longjmp_call_dummy, bp_longjmp_master, bp_longjmp_resume, bp_none, bp_overlay_event, bp_read_watchpoint, bp_shlib_event, bp_static_tracepoint, bp_std_terminate, bp_std_terminate_master, bp_step_resume, bp_thread_event, bp_tracepoint, bp_until, bp_watchpoint, bp_watchpoint_scope, int, internal_error(), and type.
Referenced by breakpoint_1(), create_breakpoint(), and print_one_breakpoint_location().
void break_command (char * arg, int from_tty)
Definition at line 9871 of file breakpoint.c.
References break_command_1().
Referenced by mi_cmd_break_commands(), and rbreak_command().
static void break_command_1 (char * arg, int flag, int from_tty) [static]
Definition at line 9785 of file breakpoint.c.
References bkpt_breakpoint_ops, bkpt_probe_breakpoint_ops, bp_breakpoint, bp_hardware_breakpoint, BP_HARDWAREFLAG, BP_TEMPFLAG, create_breakpoint(), get_current_arch(), and probe_linespec_to_ops().
Referenced by break_command(), hbreak_command(), stopat_command(), stopin_command(), tbreak_command(), and thbreak_command().
static void break_range_command (char * arg, int from_tty) [static]
Definition at line 10172 of file breakpoint.c.
References _, breakpoint::addr_string, breakpoint::addr_string_range_end, bp_hardware_breakpoint, decode_line_full(), DECODE_LINE_FUNFIRSTLINE, disp_donttouch, breakpoint::disposition, do_cleanups(), error(), find_breakpoint_range_end(), get_current_arch(), hbreak_command(), hw_breakpoint_used_count(), init_linespec_result(), bp_location::length, symtab_and_line::line, breakpoint::loc, make_cleanup(), make_cleanup_destroy_linespec_result(), mention(), symtabs_and_lines::nelts, breakpoint::number, observer_notify_breakpoint_created(), parse_breakpoint_sals(), symtab_and_line::pc, ranged_breakpoint_ops, linespec_sals::sals, symtabs_and_lines::sals, savestring(), set_breakpoint_count(), set_raw_breakpoint(), skip_spaces(), symtab_and_line::symtab, target_can_use_hardware_watchpoint, target_ranged_break_num_registers(), update_global_location_list(), VEC_empty, VEC_index, VEC_length, and xfree().
static int breakpoint_1 (char * args, int allflag, int(*)(const struct breakpoint *) filter) [static]
Definition at line 6383 of file breakpoint.c.
References bp_location::address, value_print_options::addressprint, ALL_BREAKPOINTS, annotate_breakpoints_headers(), annotate_breakpoints_table(), annotate_breakpoints_table_end(), annotate_field(), bptype_string(), breakpoint_address_bits(), current_uiout, do_cleanups(), bp_location::gdbarch, get_user_print_options(), make_cleanup_ui_out_table_begin_end(), breakpoint::number, number_is_in_list(), parse_and_eval_long(), print_one_breakpoint(), QUIT, server_command, set_next_address(), breakpoint::type, ui_left, ui_noalign, ui_out_message(), ui_out_table_body(), ui_out_table_header(), and user_breakpoint_p().
Referenced by breakpoints_info(), maintenance_info_breakpoints(), tracepoints_info(), and watchpoints_info().
static void breakpoint_about_to_proceed (void) [static]
Definition at line 4301 of file breakpoint.c.
References thread_info::control, thread_control_state::in_infcall, inferior_ptid, inferior_thread(), null_ptid, and ptid_equal().
static int breakpoint_address_bits (struct breakpoint * b) [static]
Definition at line 6305 of file breakpoint.c.
References bp_watchpoint, bp_location::gdbarch, gdbarch_addr_bit(), breakpoint::loc, bp_location::next, breakpoint::type, and bp_location::watchpoint_type.
Referenced by breakpoint_1().
static int breakpoint_address_is_meaningful (struct breakpoint * bpt) [static]
Definition at line 6666 of file breakpoint.c.
References bp_catchpoint, bp_watchpoint, and breakpoint::type.
Referenced by update_global_location_list().
static int breakpoint_address_match (struct address_space * aspace1, CORE_ADDR addr1, struct address_space * aspace2, CORE_ADDR addr2) [static]
Definition at line 6723 of file breakpoint.c.
References gdbarch_has_global_breakpoints(), and target_gdbarch().
Referenced by bkpt_breakpoint_hit(), breakpoint_location_address_match(), breakpoint_locations_match(), breakpoint_xfer_memory(), single_step_breakpoint_inserted_here_p(), and software_breakpoint_inserted_here_p().
static int breakpoint_address_match_range (struct address_space * aspace1, CORE_ADDR addr1, int len1, struct address_space * aspace2, CORE_ADDR addr2) [static]
Definition at line 6737 of file breakpoint.c.
References gdbarch_has_global_breakpoints(), and target_gdbarch().
Referenced by breakpoint_hit_ranged_breakpoint(), and breakpoint_location_address_match().
static void breakpoint_adjustment_warning (CORE_ADDR from_addr, CORE_ADDR to_addr, int bnum, int have_bnum) [static]
Definition at line 6812 of file breakpoint.c.
References _, hex_string_custom(), and warning().
Referenced by adjust_breakpoint_address(), and bkpt_print_it().
void breakpoint_auto_delete (bpstat bs)
Definition at line 11956 of file breakpoint.c.
References ALL_BREAKPOINTS_SAFE, bpstats::breakpoint_at, delete_breakpoint(), disp_del, disp_del_at_next_stop, breakpoint::disposition, bpstats::next, and bpstats::stop.
Referenced by normal_stop(), and run_inferior_call().
struct command_line* breakpoint_commands (struct breakpoint * b) [read]
Definition at line 356 of file breakpoint.c.
References counted_command_line::commands, and breakpoint::commands.
Referenced by all_tracepoint_actions_and_cleanup(), bppy_get_commands(), gdb_get_breakpoint_info(), gdb_get_tracepoint_info(), and remote_download_tracepoint().
static int breakpoint_cond_eval (void * exp) [static]
Definition at line 4643 of file breakpoint.c.
References evaluate_expression(), value_free_to_mark(), value_mark(), and value_true().
Referenced by bpstat_check_breakpoint_conditions().
static const char* breakpoint_condition_evaluation_mode (void) [static]
Definition at line 496 of file breakpoint.c.
References translate_condition_evaluation_mode().
Referenced by gdb_evaluates_breakpoint_condition_p(), print_breakpoint_location(), print_one_breakpoint_location(), and show_condition_evaluation_mode().
void breakpoint_free_objfile (struct objfile * objfile)
Definition at line 15784 of file breakpoint.c.
References ALL_BP_LOCATIONS, symtab::objfile, and bp_location::symtab.
Referenced by free_objfile().
static int breakpoint_has_pc (struct breakpoint * b, struct program_space * pspace, CORE_ADDR pc, struct obj_section * section) [static]
Definition at line 6587 of file breakpoint.c.
References bp_location::address, breakpoint::loc, bp_location::next, overlay_debugging, bp_location::pspace, and bp_location::section.
Referenced by describe_other_breakpoints().
enum breakpoint_here breakpoint_here_p (struct address_space * aspace, CORE_ADDR pc)
Definition at line 3896 of file breakpoint.c.
References ALL_BP_LOCATIONS, bp_loc_hardware_breakpoint, bp_loc_software_breakpoint, bp_permanent, breakpoint_location_address_match(), breakpoint::enable_state, bp_location::loc_type, ordinary_breakpoint_here, overlay_debugging, bp_location::owner, permanent_breakpoint_here, bp_location::section, section_is_mapped(), and section_is_overlay().
Referenced by crisv32_single_step_through_delay(), displaced_step_fixup(), mips_single_step_through_delay(), prepare_to_proceed(), proceed(), resume(), and tui_set_disassem_content().
static int breakpoint_hit_catch_exec (const struct bp_location * bl, struct address_space * aspace, CORE_ADDR bp_addr, const struct target_waitstatus * ws) [static]
Definition at line 8542 of file breakpoint.c.
References exec_catchpoint::exec_pathname, target_waitstatus::execd_pathname, target_waitstatus::kind, bp_location::owner, TARGET_WAITKIND_EXECD, and target_waitstatus::value.
Referenced by initialize_breakpoint_ops().
static int breakpoint_hit_catch_fork (const struct bp_location * bl, struct address_space * aspace, CORE_ADDR bp_addr, const struct target_waitstatus * ws) [static]
Definition at line 7566 of file breakpoint.c.
References fork_catchpoint::forked_inferior_pid, target_waitstatus::kind, bp_location::owner, target_waitstatus::related_pid, TARGET_WAITKIND_FORKED, and target_waitstatus::value.
Referenced by initialize_breakpoint_ops().
static int breakpoint_hit_catch_solib (const struct bp_location * bl, struct address_space * aspace, CORE_ADDR bp_addr, const struct target_waitstatus * ws) [static]
Definition at line 7822 of file breakpoint.c.
References ALL_BREAKPOINTS, bp_shlib_event, target_waitstatus::kind, bp_location::next, bp_location::owner, and TARGET_WAITKIND_LOADED.
Referenced by initialize_breakpoint_ops().
static int breakpoint_hit_catch_syscall (const struct bp_location * bl, struct address_space * aspace, CORE_ADDR bp_addr, const struct target_waitstatus * ws) [static]
Definition at line 8222 of file breakpoint.c.
References target_waitstatus::kind, bp_location::owner, target_waitstatus::syscall_number, TARGET_WAITKIND_SYSCALL_ENTRY, TARGET_WAITKIND_SYSCALL_RETURN, target_waitstatus::value, and VEC_iterate.
Referenced by initialize_breakpoint_ops().
static int breakpoint_hit_catch_vfork (const struct bp_location * bl, struct address_space * aspace, CORE_ADDR bp_addr, const struct target_waitstatus * ws) [static]
Definition at line 7683 of file breakpoint.c.
References fork_catchpoint::forked_inferior_pid, target_waitstatus::kind, bp_location::owner, target_waitstatus::related_pid, TARGET_WAITKIND_VFORKED, and target_waitstatus::value.
Referenced by initialize_breakpoint_ops().
static int breakpoint_hit_ranged_breakpoint (const struct bp_location * bl, struct address_space * aspace, CORE_ADDR bp_addr, const struct target_waitstatus * ws) [static]
Definition at line 9998 of file breakpoint.c.
References bp_location::address, program_space::aspace, breakpoint_address_match_range(), target_waitstatus::kind, bp_location::length, bp_location::pspace, target_waitstatus::sig, TARGET_WAITKIND_STOPPED, and target_waitstatus::value.
Referenced by initialize_breakpoint_ops().
static int breakpoint_hit_watchpoint (const struct bp_location * bl, struct address_space * aspace, CORE_ADDR bp_addr, const struct target_waitstatus * ws) [static]
Definition at line 10479 of file breakpoint.c.
References is_hardware_watchpoint(), bp_location::owner, watch_triggered_no, and watchpoint::watchpoint_triggered.
Referenced by initialize_breakpoint_ops().
void breakpoint_init_inferior (enum inf_context context)
Definition at line 3787 of file breakpoint.c.
References ALL_BP_LOCATIONS, ALL_BREAKPOINTS_SAFE, bp_access_watchpoint, bp_call_dummy, bp_hardware_watchpoint, bp_longjmp_call_dummy, bp_permanent, bp_read_watchpoint, bp_shlib_event, bp_step_resume, bp_watchpoint, bp_watchpoint_scope, current_program_space, decref_bp_location(), delete_breakpoint(), breakpoint::enable_state, watchpoint::exp_valid_block, gdbarch_has_global_breakpoints(), inf_starting, bp_location::inserted, breakpoint::loc, bp_location::owner, bp_location::pspace, target_gdbarch(), breakpoint::type, watchpoint::val, watchpoint::val_valid, value_free(), VEC_free, and VEC_iterate.
Referenced by follow_exec(), generic_mourn_inferior(), and init_wait_for_inferior().
int breakpoint_inserted_here_p (struct address_space * aspace, CORE_ADDR pc)
Definition at line 3976 of file breakpoint.c.
References regular_breakpoint_inserted_here_p(), and single_step_breakpoint_inserted_here_p().
Referenced by cancel_breakpoint(), handle_inferior_event(), ia64_hpux_at_dld_breakpoint_1_p(), record_full_wait_1(), resume(), and resume_stopped_resumed_lwps().
static int breakpoint_location_address_match (struct bp_location * bl, struct address_space * aspace, CORE_ADDR addr) [static]
Definition at line 6752 of file breakpoint.c.
References bp_location::address, program_space::aspace, breakpoint_address_match(), breakpoint_address_match_range(), bp_location::length, and bp_location::pspace.
Referenced by bpstat_stop_status(), breakpoint_here_p(), breakpoint_thread_match(), moribund_breakpoint_here_p(), and regular_breakpoint_inserted_here_p().
static int breakpoint_locations_match (struct bp_location * loc1, struct bp_location * loc2) [static]
Definition at line 6786 of file breakpoint.c.
References bp_location::address, program_space::aspace, breakpoint_address_match(), gdb_assert, is_hardware_watchpoint(), is_tracepoint(), bp_location::length, bp_location::owner, bp_location::pspace, tracepoint_locations_match(), and watchpoint_locations_match().
Referenced by update_breakpoint_locations(), and update_global_location_list().
void breakpoint_program_space_exit (struct program_space * pspace)
Definition at line 2673 of file breakpoint.c.
References ALL_BP_LOCATIONS, ALL_BREAKPOINTS_SAFE, delete_breakpoint(), breakpoint::loc, bp_location::next, bp_location::owner, bp_location::pspace, breakpoint::pspace, and update_global_location_list().
Referenced by release_program_space().
void breakpoint_re_set (void)
Definition at line 14310 of file breakpoint.c.
References ALL_BREAKPOINTS_SAFE, breakpoint_re_set_one(), catch_errors(), create_exception_master_breakpoint(), create_longjmp_master_breakpoint(), create_overlay_event_breakpoint(), create_std_terminate_master_breakpoint(), current_language, do_cleanups(), input_radix, jit_breakpoint_re_set(), language_defn::la_language, make_cleanup(), breakpoint::number, RETURN_MASK_ALL, save_current_program_space(), set_language(), xfree(), and xstrprintf().
Referenced by clear_symtab_users(), enable_breakpoints_after_startup(), follow_exec(), follow_inferior_reset_breakpoints(), generic_load(), new_symfile_objfile(), objfile_rebase(), objfile_relocate(), post_create_inferior(), reload_shared_libraries(), and solib_add().
static void breakpoint_re_set_default (struct breakpoint * b) [static]
Definition at line 14180 of file breakpoint.c.
References breakpoint::addr_string, breakpoint::addr_string_range_end, addr_string_to_sals(), make_cleanup(), symtabs_and_lines::sals, update_breakpoint_locations(), and xfree().
Referenced by bkpt_re_set(), dprintf_re_set(), and tracepoint_re_set().
static int breakpoint_re_set_one (void * bint) [static]
Definition at line 14296 of file breakpoint.c.
References do_cleanups(), breakpoint::ops, prepare_re_set_context(), and breakpoint_ops::re_set.
Referenced by breakpoint_re_set().
void breakpoint_re_set_thread (struct breakpoint * b)
Definition at line 14348 of file breakpoint.c.
References current_program_space, in_thread_list(), inferior_ptid, breakpoint::loc, pid_to_thread_id(), bp_location::pspace, and breakpoint::thread.
Referenced by follow_inferior_reset_breakpoints().
void breakpoint_retire_moribund (void)
Definition at line 12552 of file breakpoint.c.
References decref_bp_location(), bp_location::events_till_retirement, VEC_iterate, and VEC_unordered_remove.
Referenced by handle_inferior_event().
static void breakpoint_sals_to_pc (struct symtabs_and_lines * sals) [static]
Definition at line 9358 of file breakpoint.c.
References symtabs_and_lines::nelts, resolve_sal_pc(), and symtabs_and_lines::sals.
Referenced by create_breakpoint().
void breakpoint_set_commands (struct breakpoint * b, struct command_line * commands)
Definition at line 1210 of file breakpoint.c.
References alloc_counted_command_line(), breakpoint::commands, decref_counted_command_line(), observer_notify_breakpoint_modified(), and validate_commands_for_breakpoint().
Referenced by create_tracepoint_from_upload(), gdb_actions_command(), mi_cmd_break_commands(), trace_actions_command(), and update_dprintf_command_list().
void breakpoint_set_silent (struct breakpoint * b, int silent)
Definition at line 1225 of file breakpoint.c.
References observer_notify_breakpoint_modified(), and breakpoint::silent.
Referenced by bppy_set_silent().
void breakpoint_set_task (struct breakpoint * b, int task)
Definition at line 1251 of file breakpoint.c.
References observer_notify_breakpoint_modified(), and breakpoint::task.
Referenced by bppy_set_task().
void breakpoint_set_thread (struct breakpoint * b, int thread)
Definition at line 1238 of file breakpoint.c.
References observer_notify_breakpoint_modified(), and breakpoint::thread.
Referenced by bppy_set_thread().
int breakpoint_thread_match (struct address_space * aspace, CORE_ADDR pc, ptid_t ptid)
Definition at line 4057 of file breakpoint.c.
References ada_get_task_number(), ALL_BP_LOCATIONS, bp_loc_hardware_breakpoint, bp_loc_software_breakpoint, bp_permanent, breakpoint_location_address_match(), breakpoint::enable_state, bp_location::loc_type, overlay_debugging, bp_location::owner, pid_to_thread_id(), bp_location::section, section_is_mapped(), section_is_overlay(), breakpoint::task, and breakpoint::thread.
Referenced by handle_inferior_event().
void breakpoint_xfer_memory (gdb_byte * readbuf, gdb_byte * writebuf, const gdb_byte * writebuf_org, ULONGEST memaddr, LONGEST len)
Definition at line 1436 of file breakpoint.c.
References _, bp_location::address, program_space::aspace, bp_location_count, bp_location_has_shadow(), bp_none, breakpoint_address_match(), current_program_space, gdb_assert, bp_location::gdbarch, gdbarch_breakpoint_from_pc(), memaddr, memcpy(), breakpoint::number, bp_location::owner, bp_target_info::placed_address, bp_target_info::placed_address_space, bp_target_info::placed_size, bp_target_info::shadow_contents, bp_target_info::shadow_len, bp_location::target_info, breakpoint::type, and warning().
Referenced by memory_xfer_partial().
int breakpoints_always_inserted_mode (void)
Definition at line 448 of file breakpoint.c.
References AUTO_BOOLEAN_AUTO, AUTO_BOOLEAN_TRUE, and non_stop.
Referenced by handle_inferior_event(), insert_breakpoints(), normal_stop(), remote_start_remote(), show_always_inserted_mode(), and update_global_location_list().
static void breakpoints_info (char * args, int from_tty) [static]
Definition at line 6556 of file breakpoint.c.
References breakpoint_1(), and default_collect_info().
static void build_target_command_list (struct bp_location * bl) [static]
Definition at line 2269 of file breakpoint.c.
References bp_location::address, ALL_BP_LOCATIONS_AT_ADDR, bp_dprintf, bp_enabled, bp_location::cmd_bytecode, breakpoint::enable_state, bp_location::enabled, breakpoint::extra_string, free_agent_expr(), is_breakpoint(), bp_location::needs_update, program_space::num, bp_location::owner, parse_cmd_to_aexpr(), bp_target_info::persist, bp_location::pspace, target_can_run_breakpoint_commands, bp_location::target_info, breakpoint::type, and VEC_safe_push.
Referenced by insert_bp_location().
static void build_target_condition_list (struct bp_location * bl) [static]
Definition at line 2078 of file breakpoint.c.
References bp_location::address, ALL_BP_LOCATIONS_AT_ADDR, bp_enabled, bp_location::cond, bp_location::cond_bytecode, breakpoint::enable_state, bp_location::enabled, free_agent_expr(), gdb_evaluates_breakpoint_condition_p(), is_breakpoint(), bp_location::needs_update, program_space::num, bp_location::owner, parse_cond_to_aexpr(), bp_location::pspace, bp_location::target_info, target_supports_evaluation_of_breakpoint_conditions, and VEC_safe_push.
Referenced by insert_bp_location().
static int can_use_hardware_watchpoint (struct value * v) [static]
Definition at line 11222 of file breakpoint.c.
References check_typedef(), deprecated_value_modifiable(), is_scalar_type_recursive(), len, lval_memory, lval_register, not_lval, target_region_ok_for_hw_watchpoint, TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_STRUCT, TYPE_LENGTH, value_address(), value_lazy(), VALUE_LVAL, value_next(), and value_type().
Referenced by update_watchpoint().
void cancel_single_step_breakpoints (void)
Definition at line 14973 of file breakpoint.c.
References xfree().
Referenced by handle_inferior_event().
static void catch_command (char * arg, int from_tty) [static]
Definition at line 11743 of file breakpoint.c.
References _, and error().
static void catch_exec_command_1 (char * arg, int from_tty, struct cmd_list_element * command) [static]
Definition at line 11585 of file breakpoint.c.
References _, exec_catchpoint::base, catch_exec_breakpoint_ops, CATCH_TEMPORARY, ep_parse_optional_if_clause(), error(), exec_catchpoint::exec_pathname, get_cmd_context(), get_current_arch(), init_catchpoint(), install_breakpoint(), and skip_spaces().
static void catch_fork_command_1 (char * arg, int from_tty, struct cmd_list_element * command) [static]
Definition at line 11538 of file breakpoint.c.
References _, catch_fork_breakpoint_ops, catch_fork_permanent, catch_fork_temporary, catch_vfork_breakpoint_ops, catch_vfork_permanent, catch_vfork_temporary, create_fork_vfork_event_catchpoint(), ep_parse_optional_if_clause(), error(), get_cmd_context(), get_current_arch(), and skip_spaces().
static void catch_load_command_1 (char * arg, int from_tty, struct cmd_list_element * command) [static]
Definition at line 8042 of file breakpoint.c.
References catch_load_or_unload().
static void catch_load_or_unload (char * arg, int from_tty, int is_load, struct cmd_list_element * command) [static]
Definition at line 8030 of file breakpoint.c.
References add_solib_catchpoint(), CATCH_TEMPORARY, and get_cmd_context().
Referenced by catch_load_command_1(), and catch_unload_command_1().
static void catch_syscall_command_1 (char * arg, int from_tty, struct cmd_list_element * command) [static]
Definition at line 11704 of file breakpoint.c.
References _, catch_syscall_breakpoint_ops, CATCH_TEMPORARY, create_syscall_event_catchpoint(), error(), gdbarch_get_syscall_number_p(), get_cmd_context(), get_current_arch(), get_syscall_by_number(), skip_spaces(), and VEC.
int catch_syscall_enabled (void)
Definition at line 15036 of file breakpoint.c.
References current_inferior(), and get_catch_syscall_inferior_data().
Referenced by handle_syscall_event(), i386_linux_resume(), inf_ptrace_resume(), and linux_handle_syscall_trap().
static void catch_syscall_inferior_data_cleanup (struct inferior * inf, void * arg) [static]
Definition at line 8121 of file breakpoint.c.
References xfree().
static void catch_unload_command_1 (char * arg, int from_tty, struct cmd_list_element * command) [static]
Definition at line 8049 of file breakpoint.c.
References catch_load_or_unload().
int catching_syscall_number (int syscall_number)
Definition at line 15045 of file breakpoint.c.
References ALL_BREAKPOINTS, is_syscall_catchpoint_enabled(), and VEC_iterate.
Referenced by handle_syscall_event(), and linux_handle_syscall_trap().
static void check_fast_tracepoint_sals (struct gdbarch * gdbarch, struct symtabs_and_lines * sals) [static]
Definition at line 9374 of file breakpoint.c.
References _, do_cleanups(), error(), gdbarch_fast_tracepoint_valid_at(), get_sal_arch(), make_cleanup(), symtabs_and_lines::nelts, paddress(), symtab_and_line::pc, symtabs_and_lines::sals, and xfree().
Referenced by create_breakpoint().
void check_longjmp_breakpoint_for_call_dummy (int thread)
Definition at line 7274 of file breakpoint.c.
References ALL_BREAKPOINTS_SAFE, bp_call_dummy, bp_longjmp_call_dummy, delete_breakpoint(), dummy_frame_discard(), frame_find_by_id(), breakpoint::frame_id, breakpoint::next, breakpoint::related_breakpoint, breakpoint::thread, and breakpoint::type.
Referenced by handle_inferior_event().
static void check_no_tracepoint_commands (struct command_line * commands) [static]
Definition at line 1075 of file breakpoint.c.
References _, command_line::body_count, command_line::body_list, command_line::control_type, error(), command_line::line, command_line::next, strstr(), and while_stepping_control.
Referenced by validate_commands_for_breakpoint().
static void check_status_catch_solib (struct bpstats * bs) [static]
Definition at line 7857 of file breakpoint.c.
References bpstats::breakpoint_at, current_program_space, bpstats::print_it, print_it_noop, so_list::so_name, bpstats::stop, and VEC_iterate.
Referenced by initialize_breakpoint_ops().
static void check_status_watchpoint (bpstat bs) [static]
Definition at line 10500 of file breakpoint.c.
References bpstat_check_watchpoint(), bpstats::breakpoint_at, gdb_assert, and is_watchpoint().
Referenced by initialize_breakpoint_ops().
void check_tracepoint_command (char * line, void * closure)
Definition at line 1261 of file breakpoint.c.
References validate_actionline().
Referenced by do_map_commands_command(), gdb_actions_command(), mi_cmd_break_commands(), and trace_actions_command().
static void cleanup_executing_breakpoints (void * ignore) [static]
Definition at line 4321 of file breakpoint.c.
Referenced by bpstat_do_actions_1().
void clear_breakpoint_hit_counts (void)
Definition at line 656 of file breakpoint.c.
References ALL_BREAKPOINTS, and breakpoint::hit_count.
Referenced by run_command_1().
static void clear_command (char * arg, int from_tty) [static]
Definition at line 11780 of file breakpoint.c.
References _, bp_location::address, ALL_BREAKPOINTS, bp_none, compare_breakpoints(), DECODE_LINE_FUNFIRSTLINE, DECODE_LINE_LIST_MODE, decode_line_with_current_source(), delete_breakpoint(), do_cleanups(), error(), symtab_and_line::explicit_line, get_last_displayed_sal(), init_sal(), is_watchpoint(), symtab_and_line::line, bp_location::line_number, breakpoint::loc, make_cleanup(), symtabs_and_lines::nelts, bp_location::next, null_cleanup(), breakpoint::number, symtab_and_line::pc, printf_unfiltered(), bp_location::pspace, symtab_and_line::pspace, putchar_unfiltered(), qsort, symtabs_and_lines::sals, bp_location::section, symtab_and_line::section, section_is_overlay(), bp_location::symtab, symtab_and_line::symtab, symtab_to_fullname(), breakpoint::type, VEC, VEC_address, VEC_cleanup, VEC_empty, VEC_index, VEC_iterate, VEC_length, VEC_ordered_remove, VEC_safe_push, xfree(), and xmalloc().
static void clear_syscall_counts (struct inferior * inf) [static]
Definition at line 15708 of file breakpoint.c.
References catch_syscall_inferior_data::any_syscall_count, get_catch_syscall_inferior_data(), and VEC_free.
struct breakpoint* clone_momentary_breakpoint (struct breakpoint * orig) [read]
Definition at line 8826 of file breakpoint.c.
References momentary_breakpoint_from_master(), breakpoint::ops, and breakpoint::type.
Referenced by follow_fork().
static int command_line_is_silent (struct command_line * cmd) [static]
Definition at line 4330 of file breakpoint.c.
References command_line::line, and xdb_commands.
Referenced by bpstat_do_actions_1(), and bpstat_stop_status().
static void commands_command (char * arg, int from_tty) [static]
Definition at line 1385 of file breakpoint.c.
References commands_command_1().
static void commands_command_1 (char * arg, int from_tty, struct command_line * control) [static]
Definition at line 1338 of file breakpoint.c.
References _, commands_info::arg, commands_info::cmd, commands_info::control, do_cleanups(), do_map_commands_command(), error(), commands_info::from_tty, make_cleanup(), make_cleanup_decref_counted_command_line(), map_breakpoint_numbers(), xfree(), and xstrprintf().
Referenced by commands_command(), and commands_from_control_command().
enum command_control_type commands_from_control_command (char * arg, struct command_line * cmd)
Definition at line 1396 of file breakpoint.c.
References commands_command_1(), and simple_control.
Referenced by execute_control_command().
static int compare_breakpoints (const void * a, const void * b) [static]
Definition at line 11758 of file breakpoint.c.
Referenced by clear_command().
static void condition_command (char * arg, int from_tty) [static]
Definition at line 1034 of file breakpoint.c.
References _, ALL_BREAKPOINTS, error(), error_no_arg(), gdbpy_breakpoint_has_py_cond(), get_number(), is_breakpoint(), breakpoint::number, p, breakpoint::py_bp_object, set_breakpoint_condition(), and update_global_location_list().
int create_breakpoint (struct gdbarch * gdbarch, char * arg, char * cond_string, int thread, char * extra_string, int parse_arg, int tempflag, enum bptype type_wanted, int ignore_count, enum auto_boolean pending_break_support, const struct breakpoint_ops * ops, int from_tty, int enabled, int internal, unsigned flags)
Definition at line 9552 of file breakpoint.c.
References _, breakpoint::addr_string, AUTO_BOOLEAN_AUTO, AUTO_BOOLEAN_FALSE, tracepoint::base, bp_breakpoint, bp_disabled, bp_enabled, bp_fast_tracepoint, bp_hardware_breakpoint, bptype_string(), breakpoint_sals_to_pc(), linespec_sals::canonical, check_fast_tracepoint_sals(), breakpoint::cond_string, breakpoint::condition_not_parsed, breakpoint_ops::create_breakpoints_sal, breakpoint_ops::create_sals_from_address, current_program_space, discard_cleanups(), disp_del, disp_donttouch, breakpoint::disposition, do_cleanups(), breakpoint::enable_state, gdb_exception::error, error(), exception_print(), breakpoint::extra_string, find_condition_and_thread(), gdb_assert, GDB_NO_ERROR, gdb_stderr, breakpoint::ignore_count, init_linespec_result(), init_raw_breakpoint_without_location(), init_sal(), install_breakpoint(), is_tracepoint_type(), make_cleanup(), make_cleanup_destroy_linespec_result(), symtabs_and_lines::nelts, NOT_FOUND_ERROR, nquery(), null_cleanup(), symtab_and_line::pc, breakpoint::pspace, gdb_exception::reason, RETURN_ERROR, RETURN_MASK_ALL, linespec_sals::sals, symtabs_and_lines::sals, throw_exception(), TRY_CATCH, update_global_location_list(), VEC_empty, VEC_index, VEC_iterate, VEC_length, VEC_safe_push, warning(), and xfree().
Referenced by bpfinishpy_init(), bppy_init(), break_command_1(), create_tracepoint_from_upload(), dprintf_command(), ftrace_command(), gdb_set_bp(), mi_cmd_break_insert_1(), spu_catch_start(), strace_command(), and trace_command().
static void create_breakpoint_sal (struct gdbarch * gdbarch, struct symtabs_and_lines sals, char * addr_string, char * filter, char * cond_string, char * extra_string, enum bptype type, enum bpdisp disposition, int thread, int task, int ignore_count, const struct breakpoint_ops * ops, int from_tty, int enabled, int internal, unsigned flags, int display_canonical) [static]
Definition at line 9182 of file breakpoint.c.
References tracepoint::base, discard_cleanups(), init_breakpoint_sal(), install_breakpoint(), is_tracepoint_type(), make_cleanup(), and xfree().
Referenced by create_breakpoints_sal().
static void create_breakpoints_sal (struct gdbarch * gdbarch, struct linespec_result * canonical, char * cond_string, char * extra_string, enum bptype type, enum bpdisp disposition, int thread, int task, int ignore_count, const struct breakpoint_ops * ops, int from_tty, int enabled, int internal, unsigned flags) [static]
Definition at line 9236 of file breakpoint.c.
References linespec_result::addr_string, linespec_sals::canonical, create_breakpoint_sal(), discard_cleanups(), gdb_assert, make_cleanup(), linespec_result::pre_expanded, linespec_sals::sals, linespec_result::special_display, VEC_iterate, VEC_length, and xfree().
Referenced by create_breakpoints_sal_default().
static void create_breakpoints_sal_default (struct gdbarch * gdbarch, struct linespec_result * canonical, char * cond_string, char * extra_string, enum bptype type_wanted, enum bpdisp disposition, int thread, int task, int ignore_count, const struct breakpoint_ops * ops, int from_tty, int enabled, int internal, unsigned flags) [static]
Definition at line 14224 of file breakpoint.c.
References create_breakpoints_sal().
Referenced by bkpt_create_breakpoints_sal(), and tracepoint_create_breakpoints_sal().
static void create_exception_master_breakpoint (void) [static]
Definition at line 3362 of file breakpoint.c.
References breakpoint::addr_string, probe::address, ALL_OBJFILES, bp_disabled, bp_exception_master, can_evaluate_probe_arguments(), create_internal_breakpoint(), current_target, breakpoint::enable_state, gdbarch_convert_from_func_ptr_addr(), get_breakpoint_objfile_data(), get_objfile_arch(), internal_breakpoint_ops, lookup_minimal_symbol(), msym_not_found, msym_not_found_p(), p, SYMBOL_VALUE_ADDRESS, update_global_location_list(), VEC, VEC_free, VEC_index, and VEC_iterate.
Referenced by breakpoint_re_set(), and update_breakpoints_after_exec().
static void create_fork_vfork_event_catchpoint (struct gdbarch * gdbarch, int tempflag, char * cond_string, const struct breakpoint_ops * ops) [static]
Definition at line 8484 of file breakpoint.c.
References fork_catchpoint::base, fork_catchpoint::forked_inferior_pid, init_catchpoint(), install_breakpoint(), and null_ptid.
Referenced by catch_fork_command_1().
static struct breakpoint* create_internal_breakpoint (struct gdbarch * gdbarch, CORE_ADDR address, enum bptype type, const struct breakpoint_ops * ops) [static, read]
Definition at line 3047 of file breakpoint.c.
References current_program_space, disp_donttouch, breakpoint::disposition, find_pc_overlay(), init_sal(), breakpoint::number, symtab_and_line::pc, symtab_and_line::pspace, symtab_and_line::section, and set_raw_breakpoint().
Referenced by create_exception_master_breakpoint(), create_jit_event_breakpoint(), create_longjmp_master_breakpoint(), create_overlay_event_breakpoint(), create_solib_event_breakpoint(), create_std_terminate_master_breakpoint(), create_thread_event_breakpoint(), and watch_command_1().
struct breakpoint* create_jit_event_breakpoint (struct gdbarch * gdbarch, CORE_ADDR address) [read]
Definition at line 7394 of file breakpoint.c.
References bp_jit_event, create_internal_breakpoint(), internal_breakpoint_ops, and update_global_location_list_nothrow().
Referenced by jit_breakpoint_re_set_internal().
static void create_longjmp_master_breakpoint (void) [static]
Definition at line 3195 of file breakpoint.c.
References breakpoint::addr_string, probe::address, ALL_OBJFILES, ALL_PSPACES, bp_disabled, bp_longjmp_master, can_evaluate_probe_arguments(), create_internal_breakpoint(), do_cleanups(), breakpoint::enable_state, gdbarch_get_longjmp_target_p(), get_breakpoint_objfile_data(), get_objfile_arch(), internal_breakpoint_ops, breakpoint_objfile_data::longjmp_msym, breakpoint_objfile_data::longjmp_searched, lookup_minimal_symbol_text(), arm-linux::m, msym_not_found, msym_not_found_p(), NUM_LONGJMP_NAMES, p, save_current_program_space(), set_current_program_space(), SYMBOL_VALUE_ADDRESS, update_global_location_list(), VEC, VEC_free, VEC_index, and VEC_iterate.
Referenced by breakpoint_re_set(), and update_breakpoints_after_exec().
static void create_overlay_event_breakpoint (void) [static]
Definition at line 3144 of file breakpoint.c.
References breakpoint::addr_string, ALL_OBJFILES, bp_disabled, bp_enabled, bp_overlay_event, create_internal_breakpoint(), breakpoint::enable_state, get_breakpoint_objfile_data(), get_objfile_arch(), internal_breakpoint_ops, lookup_minimal_symbol_text(), arm-linux::m, msym_not_found, msym_not_found_p(), overlay_debugging, breakpoint_objfile_data::overlay_msym, ovly_auto, SYMBOL_VALUE_ADDRESS, and update_global_location_list().
Referenced by breakpoint_re_set(), and update_breakpoints_after_exec().
static void create_sals_from_address_default (char ** arg, struct linespec_result * canonical, enum bptype type_wanted, char * addr_start, char ** copy_arg) [static]
Definition at line 14211 of file breakpoint.c.
References parse_breakpoint_sals().
Referenced by bkpt_create_sals_from_address(), and tracepoint_create_sals_from_address().
struct breakpoint* create_solib_event_breakpoint (struct gdbarch * gdbarch, CORE_ADDR address) [read]
Definition at line 7429 of file breakpoint.c.
References bp_shlib_event, create_internal_breakpoint(), internal_breakpoint_ops, and update_global_location_list_nothrow().
Referenced by darwin_solib_create_inferior_hook(), enable_break(), enable_break2(), ocl_enable_break(), som_solib_create_inferior_hook(), spu_enable_break(), svr4_create_probe_breakpoints(), and svr4_create_solib_event_breakpoints().
static void create_std_terminate_master_breakpoint (void) [static]
Definition at line 3305 of file breakpoint.c.
References breakpoint::addr_string, ALL_OBJFILES, ALL_PSPACES, bp_disabled, bp_std_terminate_master, create_internal_breakpoint(), do_cleanups(), breakpoint::enable_state, get_breakpoint_objfile_data(), get_objfile_arch(), internal_breakpoint_ops, lookup_minimal_symbol(), arm-linux::m, mst_file_text, mst_text, msym_not_found, msym_not_found_p(), MSYMBOL_TYPE, save_current_program_space(), set_current_program_space(), SYMBOL_VALUE_ADDRESS, and update_global_location_list().
Referenced by breakpoint_re_set(), and update_breakpoints_after_exec().
static void create_syscall_event_catchpoint (int tempflag, VEC(int)* filter, const struct breakpoint_ops * ops) [static]
Definition at line 8627 of file breakpoint.c.
References syscall_catchpoint::base, get_current_arch(), init_catchpoint(), and install_breakpoint().
Referenced by catch_syscall_command_1().
struct breakpoint* create_thread_event_breakpoint (struct gdbarch * gdbarch, CORE_ADDR address) [read]
Definition at line 7357 of file breakpoint.c.
References breakpoint::addr_string, bp_location::address, bp_enabled, bp_thread_event, create_internal_breakpoint(), breakpoint::enable_state, bp_location::gdbarch, internal_breakpoint_ops, breakpoint::loc, paddress(), update_global_location_list_nothrow(), and xstrprintf().
Referenced by enable_thread_event(), and pd_enable().
struct tracepoint* create_tracepoint_from_upload (struct uploaded_tp * utp) [read]
Definition at line 15185 of file breakpoint.c.
References _, uploaded_tp::addr, uploaded_tp::at_string, tracepoint::base, breakpoint_set_commands(), uploaded_tp::cond, uploaded_tp::cond_string, create_breakpoint(), CREATE_BREAKPOINT_FLAGS_INSERTED, uploaded_tp::enabled, gdb_assert, get_current_arch(), get_tracepoint(), hex_string(), uploaded_tp::hit_count, breakpoint::hit_count, uploaded_tp::number, breakpoint::number, uploaded_tp::pass, read_command_lines_1(), read_uploaded_action(), trace_pass_command(), uploaded_tp::traceframe_usage, tracepoint::traceframe_usage, tracepoint_breakpoint_ops, uploaded_tp::type, VEC_empty, warning(), and xsnprintf().
Referenced by merge_uploaded_tracepoints().
static void decode_linespec_default (struct breakpoint * b, char ** s, struct symtabs_and_lines * sals) [static]
Definition at line 14247 of file breakpoint.c.
References decode_line_full(), DECODE_LINE_FUNFIRSTLINE, destroy_linespec_result(), breakpoint::filter, gdb_assert, init_linespec_result(), multiple_symbols_all, linespec_sals::sals, symtabs_and_lines::sals, VEC_index, and VEC_length.
Referenced by bkpt_decode_linespec(), and tracepoint_decode_linespec().
static struct symtabs_and_lines decode_static_tracepoint_spec (char ** arg_p) [static, read]
Definition at line 9496 of file breakpoint.c.
References _, static_tracepoint_marker::address, do_cleanups(), error(), find_pc_line(), init_sal(), make_cleanup(), symtabs_and_lines::nelts, p, symtab_and_line::pc, release_static_tracepoint_marker(), symtabs_and_lines::sals, savestring(), skip_spaces(), skip_to_space, target_static_tracepoint_markers_by_strid, VEC, VEC_empty, VEC_index, VEC_length, xfree(), and xmalloc().
Referenced by strace_marker_create_sals_from_address(), and strace_marker_decode_linespec().
static void decref_bp_location (struct bp_location ** loc) [static]
Definition at line 6964 of file breakpoint.c.
References free_bp_location(), and gdb_assert.
Referenced by bpstat_free(), breakpoint_init_inferior(), breakpoint_retire_moribund(), and update_global_location_list().
static void decref_counted_command_line (struct counted_command_line ** cmdp) [static]
Definition at line 692 of file breakpoint.c.
References free_command_lines(), and xfree().
Referenced by base_breakpoint_dtor(), bpstat_clear_actions(), bpstat_free(), breakpoint_set_commands(), do_cleanup_counted_command_line(), do_map_commands_command(), and watchpoint_check().
static void default_collect_info (void) [static]
Definition at line 6538 of file breakpoint.c.
References current_uiout, default_collect, ui_out_field_string(), and ui_out_text().
Referenced by breakpoints_info(), maintenance_info_breakpoints(), and tracepoints_info().
void delete_breakpoint (struct breakpoint * bpt)
Definition at line 13576 of file breakpoint.c.
References ALL_BREAKPOINTS, bp_none, bp_watchpoint_scope, bpstat_remove_breakpoint_callback(), breakpoint_ops::dtor, gdb_assert, iterate_over_threads(), breakpoint::next, breakpoint::number, observer_notify_breakpoint_deleted(), breakpoint::ops, breakpoint::related_breakpoint, breakpoint::type, update_global_location_list(), watchpoint_del_at_next_stop(), and xfree().
Referenced by bkpt_re_set(), bpfinishpy_out_of_scope(), bppy_delete_breakpoint(), breakpoint_auto_delete(), breakpoint_init_inferior(), breakpoint_program_space_exit(), check_longjmp_breakpoint_for_call_dummy(), clear_command(), delete_command(), delete_exception_resume_breakpoint(), delete_longjmp_breakpoint(), delete_std_terminate_breakpoint(), delete_step_resume_breakpoint(), delete_trace_command(), do_delete_breakpoint(), do_delete_breakpoint_cleanup(), elf_gnu_ifunc_resolver_return_stop(), finish_command_continuation(), internal_bkpt_re_set(), jit_breakpoint_re_set_internal(), pop_dummy_frame_bpt(), remove_jit_event_breakpoints(), remove_solib_event_breakpoints(), remove_thread_event_breakpoints(), until_break_command_continuation(), update_breakpoints_after_exec(), and watch_command_1().
void delete_command (char * arg, int from_tty)
Definition at line 13733 of file breakpoint.c.
References _, ALL_BREAKPOINTS, ALL_BREAKPOINTS_SAFE, delete_breakpoint(), do_map_delete_breakpoint(), dont_repeat(), map_breakpoint_numbers(), query(), and user_breakpoint_p().
Referenced by gdb_clear_file().
void delete_longjmp_breakpoint (int thread)
Definition at line 7207 of file breakpoint.c.
References ALL_BREAKPOINTS_SAFE, bp_exception, bp_longjmp, delete_breakpoint(), breakpoint::thread, and breakpoint::type.
Referenced by delete_longjmp_breakpoint_cleanup(), finish_command_continuation(), step_1_continuation(), until_break_command_continuation(), and until_next_continuation().
void delete_longjmp_breakpoint_at_next_stop (int thread)
Definition at line 7220 of file breakpoint.c.
References ALL_BREAKPOINTS_SAFE, bp_exception, bp_longjmp, disp_del_at_next_stop, breakpoint::disposition, breakpoint::thread, and breakpoint::type.
Referenced by clear_thread_inferior_resources().
void delete_std_terminate_breakpoint (void)
Definition at line 7347 of file breakpoint.c.
References ALL_BREAKPOINTS_SAFE, bp_std_terminate, delete_breakpoint(), and breakpoint::type.
Referenced by cleanup_delete_std_terminate_breakpoint().
static void delete_trace_command (char * arg, int from_tty) [static]
Definition at line 15306 of file breakpoint.c.
References _, ALL_BREAKPOINTS_SAFE, ALL_TRACEPOINTS, delete_breakpoint(), do_map_delete_breakpoint(), dont_repeat(), is_tracepoint(), map_breakpoint_numbers(), query(), and user_breakpoint_p().
void* deprecated_insert_raw_breakpoint (struct gdbarch * gdbarch, struct address_space * aspace, CORE_ADDR pc)
Definition at line 14859 of file breakpoint.c.
References bp_target_info::placed_address, bp_target_info::placed_address_space, target_insert_breakpoint(), xfree(), and XZALLOC.
Referenced by enable_break(), exec_one_dummy_insn(), and insert_single_step_breakpoint().
int deprecated_remove_raw_breakpoint (struct gdbarch * gdbarch, void * bp)
Definition at line 14883 of file breakpoint.c.
References target_remove_breakpoint(), and xfree().
Referenced by disable_break(), exec_one_dummy_insn(), procfs_mourn_inferior(), remove_dbx_link_breakpoint(), and remove_single_step_breakpoints().
static void describe_other_breakpoints (struct gdbarch * gdbarch, struct program_space * pspace, CORE_ADDR pc, struct obj_section * section, int thread) [static]
Definition at line 6608 of file breakpoint.c.
References _, ALL_BREAKPOINTS, bp_call_disabled, bp_disabled, bp_permanent, breakpoint_has_pc(), breakpoint::enable_state, fputs_filtered(), gdb_stdout, breakpoint::number, paddress(), printf_filtered(), breakpoint::thread, and user_breakpoint_p().
Referenced by init_ada_exception_breakpoint(), and init_breakpoint_sal().
int detach_breakpoints (ptid_t ptid)
Definition at line 3578 of file breakpoint.c.
References _, ALL_BP_LOCATIONS, bp_loc_other, current_inferior(), detach_single_step_breakpoints(), do_cleanups(), error(), inferior_ptid, bp_location::inserted, bp_location::loc_type, mark_inserted, bp_location::pspace, inferior::pspace, ptid_get_pid(), remove_breakpoint_1(), and save_inferior_ptid().
Referenced by handle_inferior_event(), and linux_handle_extended_wait().
static void detach_single_step_breakpoints (void) [static]
Definition at line 14990 of file breakpoint.c.
References target_remove_breakpoint().
Referenced by detach_breakpoints().
void disable_breakpoint (struct breakpoint * bpt)
Definition at line 14523 of file breakpoint.c.
References bp_disabled, bp_permanent, bp_watchpoint_scope, current_trace_status(), breakpoint::enable_state, is_tracepoint(), breakpoint::loc, mark_breakpoint_modified(), bp_location::next, observer_notify_breakpoint_modified(), target_disable_tracepoint, target_supports_enable_disable_tracepoint, breakpoint::type, and update_global_location_list().
Referenced by bpfinishpy_post_stop_hook(), bppy_set_enabled(), disable_command(), do_disable_breakpoint(), and svr4_update_solib_event_breakpoint().
void disable_breakpoints_before_startup (void)
Definition at line 8743 of file breakpoint.c.
References current_program_space, program_space::executing_startup, and update_global_location_list().
Referenced by spu_solib_create_inferior_hook().
void disable_breakpoints_in_shlibs (void)
Definition at line 7443 of file breakpoint.c.
References bp_location::address, ALL_BP_LOCATIONS, bp_breakpoint, bp_hardware_breakpoint, bp_jit_event, current_program_space, is_tracepoint(), bp_location::owner, bp_location::pspace, bp_location::shlib_disabled, solib_name_from_address(), and breakpoint::type.
Referenced by clear_solib(), and do_initial_windows_stuff().
static void disable_breakpoints_in_unloaded_shlib (struct so_list * solib) [static]
Definition at line 7476 of file breakpoint.c.
References _, bp_location::address, ALL_BP_LOCATIONS, bp_breakpoint, bp_hardware_breakpoint, bp_jit_event, bp_loc_hardware_breakpoint, bp_loc_software_breakpoint, exec_bfd, bp_location::inserted, is_tracepoint(), bp_location::loc_type, observer_notify_breakpoint_modified(), bp_location::owner, so_list::pspace, bp_location::pspace, bp_location::shlib_disabled, so_list::so_name, solib_contains_address_p(), target_terminal_ours_for_output, breakpoint::type, and warning().
static void disable_command (char * args, int from_tty) [static]
Definition at line 14572 of file breakpoint.c.
References ALL_BREAKPOINTS, current_trace_status(), disable_breakpoint(), do_map_disable_breakpoint(), bp_location::enabled, extract_arg(), find_location_by_number(), is_tracepoint(), map_breakpoint_numbers(), mark_breakpoint_location_modified(), bp_location::owner, strchr(), target_disable_tracepoint, target_supports_enable_disable_tracepoint, update_global_location_list(), and user_breakpoint_p().
Referenced by disable_trace_command().
void disable_overlay_breakpoints (void)
Definition at line 7316 of file breakpoint.c.
References ALL_BREAKPOINTS, bp_disabled, bp_overlay_event, breakpoint::enable_state, breakpoint::type, and update_global_location_list().
Referenced by overlay_manual_command(), and overlay_off_command().
static void disable_trace_command (char * args, int from_tty) [static]
Definition at line 15299 of file breakpoint.c.
References disable_command().
void disable_watchpoints_before_interactive_call_start (void)
Definition at line 8713 of file breakpoint.c.
References ALL_BREAKPOINTS, bp_call_disabled, breakpoint::enable_state, is_watchpoint(), and update_global_location_list().
Referenced by run_inferior_call().
static int do_captured_breakpoint_query (struct ui_out * uiout, void * data) [static]
Definition at line 6333 of file breakpoint.c.
References ALL_BREAKPOINTS, captured_breakpoint_query_args::bnum, GDB_RC_NONE, GDB_RC_OK, breakpoint::number, and print_one_breakpoint().
Referenced by gdb_breakpoint_query().
static void do_cleanup_counted_command_line (void * arg) [static]
Definition at line 708 of file breakpoint.c.
References decref_counted_command_line().
Referenced by make_cleanup_decref_counted_command_line().
static void do_delete_breakpoint (struct breakpoint * b, void * ignore) [static]
Definition at line 13718 of file breakpoint.c.
References delete_breakpoint().
Referenced by do_map_delete_breakpoint().
static void do_delete_breakpoint_cleanup (void * b) [static]
Definition at line 13669 of file breakpoint.c.
References delete_breakpoint().
Referenced by make_cleanup_delete_breakpoint().
static void do_disable_breakpoint (struct breakpoint * b, void * ignore) [static]
Definition at line 14557 of file breakpoint.c.
References disable_breakpoint().
Referenced by do_map_disable_breakpoint().
static void do_enable_breakpoint (struct breakpoint * bpt, void * arg) [static]
Definition at line 14687 of file breakpoint.c.
References enable_breakpoint().
Referenced by do_map_enable_breakpoint().
static void do_enable_breakpoint_disp (struct breakpoint * bpt, void * arg) [static]
Definition at line 14757 of file breakpoint.c.
References disp_data::count, disp_data::disp, and enable_breakpoint_disp().
Referenced by do_map_enable_count_breakpoint(), do_map_enable_delete_breakpoint(), and do_map_enable_once_breakpoint().
static void do_map_commands_command (struct breakpoint * b, void * data) [static]
Definition at line 1292 of file breakpoint.c.
References _, alloc_counted_command_line(), commands_info::arg, command_line::body_list, check_tracepoint_command(), commands_info::cmd, counted_command_line::commands, breakpoint::commands, commands_info::control, copy_command_lines(), decref_counted_command_line(), do_cleanups(), commands_info::from_tty, incref_counted_command_line(), is_tracepoint(), make_cleanup(), observer_notify_breakpoint_modified(), read_command_lines(), validate_commands_for_breakpoint(), xfree(), and xstrprintf().
Referenced by commands_command_1().
static void do_map_delete_breakpoint (struct breakpoint * b, void * ignore) [static]
Definition at line 13727 of file breakpoint.c.
References do_delete_breakpoint(), and iterate_over_related_breakpoints().
Referenced by delete_command(), and delete_trace_command().
static void do_map_disable_breakpoint (struct breakpoint * b, void * ignore) [static]
Definition at line 14566 of file breakpoint.c.
References do_disable_breakpoint(), and iterate_over_related_breakpoints().
Referenced by disable_command().
static void do_map_enable_breakpoint (struct breakpoint * b, void * ignore) [static]
Definition at line 14696 of file breakpoint.c.
References do_enable_breakpoint(), and iterate_over_related_breakpoints().
Referenced by enable_command().
static void do_map_enable_count_breakpoint (struct breakpoint * bpt, void * countptr) [static]
Definition at line 14779 of file breakpoint.c.
References disp_disable, do_enable_breakpoint_disp(), and iterate_over_related_breakpoints().
Referenced by enable_count_command().
static void do_map_enable_delete_breakpoint (struct breakpoint * bpt, void * ignore) [static]
Definition at line 14795 of file breakpoint.c.
References disp_del, do_enable_breakpoint_disp(), and iterate_over_related_breakpoints().
Referenced by enable_delete_command().
static void do_map_enable_once_breakpoint (struct breakpoint * bpt, void * ignore) [static]
Definition at line 14765 of file breakpoint.c.
References disp_disable, do_enable_breakpoint_disp(), and iterate_over_related_breakpoints().
Referenced by enable_once_command().
static void download_tracepoint_locations (void) [static]
Definition at line 12054 of file breakpoint.c.
References ALL_TRACEPOINTS, bp_fast_tracepoint, do_cleanups(), bp_location::inserted, breakpoint::loc, may_insert_fast_tracepoints, may_insert_tracepoints, bp_location::next, breakpoint::number, tracepoint::number_on_target, observer_notify_breakpoint_modified(), bp_location::pspace, save_current_space_and_thread(), should_be_inserted(), switch_to_program_space_and_thread(), target_can_download_tracepoint, target_download_tracepoint, and breakpoint::type.
Referenced by update_global_location_list().
static void dprintf_after_condition_true (struct bpstats * bs) [static]
Definition at line 13441 of file breakpoint.c.
References bpstat_do_actions_1(), bpstats::commands, do_cleanups(), make_cleanup_decref_counted_command_line(), and bpstats::stop.
Referenced by initialize_breakpoint_ops().
static void dprintf_command (char * arg, int from_tty) [static]
Definition at line 9973 of file breakpoint.c.
References bp_dprintf, create_breakpoint(), dprintf_breakpoint_ops, and get_current_arch().
static void dprintf_print_recreate (struct breakpoint * tp, struct ui_file * fp) [static]
Definition at line 13424 of file breakpoint.c.
References breakpoint::addr_string, breakpoint::extra_string, fprintf_unfiltered(), and print_recreate_thread().
Referenced by initialize_breakpoint_ops().
static void dprintf_re_set (struct breakpoint * b) [static]
Definition at line 13395 of file breakpoint.c.
References _, breakpoint_re_set_default(), error(), breakpoint::extra_string, breakpoint::loc, and update_dprintf_command_list().
Referenced by initialize_breakpoint_ops().
static void dtor_catch_exec (struct breakpoint * b) [static]
Definition at line 8520 of file breakpoint.c.
References base_breakpoint_ops, breakpoint_ops::dtor, exec_catchpoint::exec_pathname, and xfree().
Referenced by initialize_breakpoint_ops().
static void dtor_catch_solib (struct breakpoint * b) [static]
Definition at line 7798 of file breakpoint.c.
References base_breakpoint_ops, breakpoint_ops::dtor, and xfree().
Referenced by initialize_breakpoint_ops().
static void dtor_catch_syscall (struct breakpoint * b) [static]
Definition at line 8077 of file breakpoint.c.
References base_breakpoint_ops, breakpoint_ops::dtor, and VEC_free.
Referenced by initialize_breakpoint_ops().
static void dtor_watchpoint (struct breakpoint * self) [static]
Definition at line 10406 of file breakpoint.c.
References base_breakpoint_ops, watchpoint::cond_exp, breakpoint_ops::dtor, watchpoint::exp, watchpoint::exp_string, watchpoint::exp_string_reparse, watchpoint::val, value_free(), and xfree().
Referenced by initialize_breakpoint_ops().
void enable_breakpoint (struct breakpoint * bpt)
Definition at line 14681 of file breakpoint.c.
References breakpoint::disposition, and enable_breakpoint_disp().
Referenced by bppy_set_enabled(), do_enable_breakpoint(), enable_command(), and svr4_update_solib_event_breakpoint().
static void enable_breakpoint_disp (struct breakpoint * bpt, enum bpdisp disposition, int count) [static]
Definition at line 14614 of file breakpoint.c.
References _, bp_enabled, bp_hardware_breakpoint, bp_permanent, current_trace_status(), breakpoint::disposition, breakpoint::enable_count, breakpoint::enable_state, error(), exception_fprintf(), gdb_stderr, hw_breakpoint_used_count(), is_tracepoint(), is_watchpoint(), breakpoint::loc, mark_breakpoint_modified(), bp_location::next, breakpoint::number, observer_notify_breakpoint_modified(), gdb_exception::reason, RETURN_MASK_ALL, target_can_use_hardware_watchpoint, target_enable_tracepoint, target_supports_enable_disable_tracepoint, TRY_CATCH, breakpoint::type, update_global_location_list(), and update_watchpoint().
Referenced by do_enable_breakpoint_disp(), and enable_breakpoint().
void enable_breakpoints_after_startup (void)
Definition at line 8750 of file breakpoint.c.
References breakpoint_re_set(), current_program_space, and program_space::executing_startup.
Referenced by spu_current_sos().
static void enable_command (char * args, int from_tty) [static]
Definition at line 14706 of file breakpoint.c.
References ALL_BREAKPOINTS, current_trace_status(), do_map_enable_breakpoint(), enable_breakpoint(), bp_location::enabled, extract_arg(), find_location_by_number(), is_tracepoint(), map_breakpoint_numbers(), mark_breakpoint_location_modified(), bp_location::owner, strchr(), target_enable_tracepoint, target_supports_enable_disable_tracepoint, update_global_location_list(), and user_breakpoint_p().
Referenced by enable_trace_command().
static void enable_count_command (char * args, int from_tty) [static]
Definition at line 14787 of file breakpoint.c.
References disp_data::count, do_map_enable_count_breakpoint(), get_number(), and map_breakpoint_numbers().
static void enable_delete_command (char * args, int from_tty) [static]
Definition at line 14803 of file breakpoint.c.
References do_map_enable_delete_breakpoint(), and map_breakpoint_numbers().
static void enable_once_command (char * args, int from_tty) [static]
Definition at line 14773 of file breakpoint.c.
References do_map_enable_once_breakpoint(), and map_breakpoint_numbers().
void enable_overlay_breakpoints (void)
Definition at line 7302 of file breakpoint.c.
References ALL_BREAKPOINTS, bp_enabled, bp_overlay_event, breakpoint::enable_state, breakpoint::type, and update_global_location_list().
Referenced by overlay_auto_command().
static void enable_trace_command (char * args, int from_tty) [static]
Definition at line 15291 of file breakpoint.c.
References enable_command().
void enable_watchpoints_after_interactive_call_stop (void)
Definition at line 8728 of file breakpoint.c.
References ALL_BREAKPOINTS, bp_call_disabled, bp_enabled, breakpoint::enable_state, is_watchpoint(), and update_global_location_list().
Referenced by run_inferior_call().
void end_rbreak_breakpoints (void)
Definition at line 648 of file breakpoint.c.
References rbreak_start_breakpoint_count.
Referenced by do_end_rbreak_breakpoints().
char* ep_parse_optional_if_clause (char ** arg)
Definition at line 11505 of file breakpoint.c.
References skip_spaces().
Referenced by catch_exception_command_1(), catch_exec_command_1(), and catch_fork_command_1().
static enum bpstat_signal_value explains_signal_watchpoint (struct breakpoint * b, enum gdb_signal sig) [static]
Definition at line 10693 of file breakpoint.c.
References bp_watchpoint, BPSTAT_SIGNAL_HIDE, BPSTAT_SIGNAL_NO, and breakpoint::type.
Referenced by initialize_breakpoint_ops().
static CORE_ADDR find_breakpoint_range_end (struct symtab_and_line sal) [static]
Definition at line 10145 of file breakpoint.c.
References _, error(), symtab_and_line::explicit_pc, find_line_pc_range(), and symtab_and_line::pc.
Referenced by break_range_command(), and update_breakpoint_locations().
static void find_condition_and_thread (const char * tok, CORE_ADDR pc, char ** cond_string, int * thread, int * task, char ** rest) [static]
Definition at line 9421 of file breakpoint.c.
References _, block_for_pc(), error(), invalid_thread_id_error(), parse_exp_1(), savestring(), skip_spaces_const(), skip_to_space_const(), valid_task_id(), valid_thread_id(), and xfree().
Referenced by addr_string_to_sals(), and create_breakpoint().
static struct bp_location* find_location_by_number (char * number) [static, read]
Definition at line 14477 of file breakpoint.c.
References _, ALL_BREAKPOINTS, error(), get_number(), breakpoint::loc, bp_location::next, breakpoint::number, and strchr().
Referenced by disable_command(), and enable_command().
static void force_breakpoint_reinsertion (struct bp_location * bl) [static]
Definition at line 12131 of file breakpoint.c.
References bp_location::address, ALL_BP_LOCATIONS_AT_ADDR, bp_location::cond_bytecode, bp_location::condition_changed, condition_updated, free_agent_expr(), gdb_evaluates_breakpoint_condition_p(), is_breakpoint(), program_space::num, bp_location::owner, bp_location::pspace, and target_supports_evaluation_of_breakpoint_conditions.
Referenced by update_global_location_list().
static void free_bp_location (struct bp_location * loc) [static]
Definition at line 6946 of file breakpoint.c.
References bp_location_ops::dtor, bp_location::ops, and xfree().
Referenced by decref_bp_location().
static void free_breakpoint_probes (struct objfile * obj, void * data) [static]
Definition at line 3135 of file breakpoint.c.
References VEC_free.
static void ftrace_command (char * arg, int from_tty) [static]
Definition at line 15118 of file breakpoint.c.
References bp_fast_tracepoint, create_breakpoint(), get_current_arch(), and tracepoint_breakpoint_ops.
enum gdb_rc gdb_breakpoint_query (struct ui_out * uiout, int bnum, char ** error_message)
Definition at line 6351 of file breakpoint.c.
References captured_breakpoint_query_args::bnum, catch_exceptions_with_msg(), do_captured_breakpoint_query(), GDB_RC_FAIL, GDB_RC_OK, and RETURN_MASK_ALL.
Referenced by breakpoint_notify(), mi_breakpoint_created(), and mi_breakpoint_modified().
static int gdb_evaluates_breakpoint_condition_p (void) [static]
Definition at line 505 of file breakpoint.c.
References breakpoint_condition_evaluation_mode().
Referenced by bp_condition_evaluator(), bp_location_condition_evaluator(), build_target_condition_list(), force_breakpoint_reinsertion(), mark_breakpoint_location_modified(), and mark_breakpoint_modified().
struct breakpoint* get_breakpoint (int num) [read]
Definition at line 727 of file breakpoint.c.
References ALL_BREAKPOINTS, and breakpoint::number.
Referenced by breakpoint_notify(), gdb_get_breakpoint_info(), gdbpy_breakpoint_deleted(), and mi_cmd_break_commands().
static struct breakpoint_objfile_data* get_breakpoint_objfile_data (struct objfile * objfile) [static, read]
Definition at line 3118 of file breakpoint.c.
References memset(), and objfile::objfile_obstack.
Referenced by create_exception_master_breakpoint(), create_longjmp_master_breakpoint(), create_overlay_event_breakpoint(), and create_std_terminate_master_breakpoint().
static struct catch_syscall_inferior_data* get_catch_syscall_inferior_data (struct inferior * inf) [static, read]
Definition at line 8106 of file breakpoint.c.
References XZALLOC.
Referenced by catch_syscall_enabled(), clear_syscall_counts(), insert_catch_syscall(), and remove_catch_syscall().
static struct bp_location ** get_first_locp_gte_addr (CORE_ADDR address) [static, read]
Definition at line 884 of file breakpoint.c.
References bp_location::address, bp_location_compare_addrs(), and memset().
struct gdbarch* get_sal_arch (struct symtab_and_line sal) [read]
Definition at line 7090 of file breakpoint.c.
References get_objfile_arch(), obj_section::objfile, symtab::objfile, symtab_and_line::section, and symtab_and_line::symtab.
Referenced by add_location_to_breakpoint(), check_fast_tracepoint_sals(), init_ada_exception_breakpoint(), and init_breakpoint_sal().
struct tracepoint* get_tracepoint (int num) [read]
Definition at line 15406 of file breakpoint.c.
References ALL_TRACEPOINTS, and breakpoint::number.
Referenced by breakpoint_notify(), create_tracepoint_from_upload(), gdb_actions_command(), gdb_get_tracepoint_info(), get_traceframe_location(), mi_cmd_break_passcount(), tfile_fetch_registers(), tfile_trace_find(), and trace_find_tracepoint_command().
struct tracepoint* get_tracepoint_by_number (char ** arg, struct get_number_or_range_state * state, int optional_p) [read]
Definition at line 15442 of file breakpoint.c.
References _, ALL_TRACEPOINTS, error_no_arg(), get_number_or_range_state::finished, gdb_assert, get_number(), get_number_or_range(), breakpoint::number, printf_filtered(), and printf_unfiltered().
Referenced by trace_actions_command(), and trace_pass_command().
struct tracepoint* get_tracepoint_by_number_on_target (int num) [read]
Definition at line 15422 of file breakpoint.c.
References ALL_TRACEPOINTS, and tracepoint::number_on_target.
Referenced by tfile_get_traceframe_address(), and tfind_1().
static void handle_jit_event (void) [static]
Definition at line 5405 of file breakpoint.c.
References get_current_frame(), get_frame_arch(), jit_event_handler(), target_terminal_inferior(), and target_terminal_ours_for_output.
Referenced by bpstat_what().
int hardware_watchpoint_inserted_in_range (struct address_space * aspace, CORE_ADDR addr, ULONGEST len)
Definition at line 4022 of file breakpoint.c.
References bp_location::address, ALL_BREAKPOINTS, program_space::aspace, bp_access_watchpoint, bp_hardware_watchpoint, bp_location::inserted, bp_location::length, breakpoint::loc, max, min, bp_location::next, bp_location::pspace, and breakpoint::type.
Referenced by record_full_exec_insn().
static void hbreak_command (char * arg, int from_tty) [static]
Definition at line 9883 of file breakpoint.c.
References BP_HARDWAREFLAG, and break_command_1().
Referenced by break_range_command().
static int hw_breakpoint_used_count (void) [static]
Definition at line 8641 of file breakpoint.c.
References ALL_BREAKPOINTS, bp_hardware_breakpoint, breakpoint::loc, bp_location::next, breakpoint::ops, breakpoint_ops::resources_needed, and breakpoint::type.
Referenced by break_range_command(), enable_breakpoint_disp(), and init_breakpoint_sal().
static int hw_watchpoint_use_count (struct breakpoint * b) [static]
Definition at line 8665 of file breakpoint.c.
References breakpoint::loc, bp_location::next, breakpoint::ops, and breakpoint_ops::resources_needed.
Referenced by hw_watchpoint_used_count_others(), and update_watchpoint().
static int hw_watchpoint_used_count_others (struct breakpoint * except, enum bptype type, int * other_type_used) [static]
Definition at line 8689 of file breakpoint.c.
References ALL_BREAKPOINTS, hw_watchpoint_use_count(), is_hardware_watchpoint(), and breakpoint::type.
Referenced by update_watchpoint().
static void ignore_command (char * args, int from_tty) [static]
Definition at line 14411 of file breakpoint.c.
References _, error(), error_no_arg(), get_number(), longest_to_int(), p, parse_and_eval(), printf_filtered(), set_ignore_count(), and value_as_long().
static void incref_bp_location (struct bp_location * loc) [static]
Definition at line 6955 of file breakpoint.c.
References bp_location::refc.
Referenced by bpstat_alloc(), and bpstat_copy().
static void incref_counted_command_line (struct counted_command_line * cmd) [static]
Definition at line 681 of file breakpoint.c.
References counted_command_line::refc.
Referenced by bpstat_copy(), bpstat_stop_status(), and do_map_commands_command().
void init_ada_exception_breakpoint (struct breakpoint * b, struct gdbarch * gdbarch, struct symtab_and_line sal, char * addr_string, const struct breakpoint_ops * ops, int tempflag, int enabled, int from_tty)
Definition at line 11618 of file breakpoint.c.
References breakpoint::addr_string, bp_breakpoint, bp_disabled, bp_enabled, describe_other_breakpoints(), disp_del, disp_donttouch, breakpoint::disposition, breakpoint::enable_state, get_sal_arch(), init_raw_breakpoint(), breakpoint::language, language_ada, symtab_and_line::pc, symtab_and_line::pspace, and symtab_and_line::section.
Referenced by create_ada_exception_catchpoint().
void init_bp_location (struct bp_location * loc, const struct bp_location_ops * ops, struct breakpoint * owner)
Definition at line 6872 of file breakpoint.c.
References _, bp_access_watchpoint, bp_breakpoint, bp_call_dummy, bp_catchpoint, bp_dprintf, bp_exception, bp_exception_master, bp_exception_resume, bp_fast_tracepoint, bp_finish, bp_gnu_ifunc_resolver, bp_gnu_ifunc_resolver_return, bp_hardware_breakpoint, bp_hardware_watchpoint, bp_hp_step_resume, bp_jit_event, bp_loc_hardware_breakpoint, bp_loc_hardware_watchpoint, bp_loc_other, bp_loc_software_breakpoint, bp_longjmp, bp_longjmp_call_dummy, bp_longjmp_master, bp_longjmp_resume, bp_overlay_event, bp_read_watchpoint, bp_shlib_event, bp_static_tracepoint, bp_std_terminate, bp_std_terminate_master, bp_step_resume, bp_thread_event, bp_tracepoint, bp_until, bp_watchpoint, bp_watchpoint_scope, bp_location::cond, bp_location::cond_bytecode, bp_location::enabled, gdb_assert, internal_error(), bp_location::loc_type, mark_breakpoint_location_modified(), memset(), bp_location::ops, bp_location::owner, bp_location::refc, bp_location::shlib_disabled, and breakpoint::type.
Referenced by allocate_location_exception(), and base_breakpoint_allocate_location().
static void init_breakpoint_sal (struct breakpoint * b, struct gdbarch * gdbarch, struct symtabs_and_lines sals, char * addr_string, char * filter, char * cond_string, char * extra_string, enum bptype type, enum bpdisp disposition, int thread, int task, int ignore_count, const struct breakpoint_ops * ops, int from_tty, int enabled, int internal, unsigned flags, int display_canonical) [static]
Definition at line 9039 of file breakpoint.c.
References _, add_location_to_breakpoint(), breakpoint::addr_string, bp_location::address, block_for_pc(), bp_disabled, bp_dprintf, bp_enabled, bp_hardware_breakpoint, bp_loc_is_permanent(), bp_static_tracepoint, bp_location::cond, breakpoint::cond_string, CREATE_BREAKPOINT_FLAGS_INSERTED, describe_other_breakpoints(), breakpoint::display_canonical, breakpoint::disposition, breakpoint::enable_state, error(), breakpoint::extra_string, breakpoint::filter, gdb_assert, bp_location::gdbarch, get_sal_arch(), hw_breakpoint_used_count(), breakpoint::ignore_count, init_raw_breakpoint(), bp_location::inserted, breakpoint::loc, make_breakpoint_permanent(), symtabs_and_lines::nelts, p, paddress(), parse_exp_1(), symtab_and_line::pc, printf_filtered(), symtab_and_line::pspace, release_static_tracepoint_marker(), symtabs_and_lines::sals, savestring(), symtab_and_line::section, skip_spaces(), skip_to_space, tracepoint::static_trace_marker_id, static_tracepoint_marker::str_id, strace_marker_p(), target_can_use_hardware_watchpoint, target_static_tracepoint_marker_at, breakpoint::task, breakpoint::thread, update_dprintf_command_list(), warning(), and xstrprintf().
Referenced by create_breakpoint_sal(), and strace_marker_create_breakpoints_sal().
void init_catchpoint (struct breakpoint * b, struct gdbarch * gdbarch, int tempflag, char * cond_string, const struct breakpoint_ops * ops)
Definition at line 8452 of file breakpoint.c.
References bp_catchpoint, breakpoint::cond_string, current_program_space, disp_del, disp_donttouch, breakpoint::disposition, init_raw_breakpoint(), init_sal(), and symtab_and_line::pspace.
Referenced by add_solib_catchpoint(), catch_exec_command_1(), create_fork_vfork_event_catchpoint(), create_signal_catchpoint(), create_syscall_event_catchpoint(), and handle_gnu_v3_exceptions().
static void init_raw_breakpoint (struct breakpoint * b, struct gdbarch * gdbarch, struct symtab_and_line sal, enum bptype bptype, const struct breakpoint_ops * ops) [static]
Definition at line 7109 of file breakpoint.c.
References add_location_to_breakpoint(), bp_breakpoint, bp_catchpoint, bp_hardware_breakpoint, gdb_assert, init_raw_breakpoint_without_location(), breakpoint::pspace, and symtab_and_line::pspace.
Referenced by init_ada_exception_breakpoint(), init_breakpoint_sal(), and init_catchpoint().
static void init_raw_breakpoint_without_location (struct breakpoint * b, struct gdbarch * gdbarch, enum bptype bptype, const struct breakpoint_ops * ops) [static]
Definition at line 6997 of file breakpoint.c.
References bp_enabled, breakpoint::commands, breakpoint::condition_not_parsed, current_language, breakpoint::enable_state, breakpoint::frame_id, gdb_assert, breakpoint::gdbarch, breakpoint::ignore_count, input_radix, breakpoint::input_radix, language_defn::la_language, breakpoint::language, memset(), breakpoint::next, null_frame_id, breakpoint::ops, breakpoint::py_bp_object, breakpoint::related_breakpoint, breakpoint::silent, breakpoint::thread, and breakpoint::type.
Referenced by create_breakpoint(), init_raw_breakpoint(), and watch_command_1().
void initialize_breakpoint_ops (void)
Definition at line 15794 of file breakpoint.c.
References breakpoint_ops::after_condition_true, base_breakpoint_ops, bkpt_base_breakpoint_ops, bkpt_breakpoint_hit(), bkpt_breakpoint_ops, bkpt_create_breakpoints_sal(), bkpt_create_sals_from_address(), bkpt_decode_linespec(), bkpt_insert_location(), bkpt_print_it(), bkpt_print_mention(), bkpt_print_recreate(), bkpt_probe_breakpoint_ops, bkpt_probe_create_sals_from_address(), bkpt_probe_decode_linespec(), bkpt_probe_insert_location(), bkpt_probe_remove_location(), bkpt_re_set(), bkpt_remove_location(), bkpt_resources_needed(), breakpoint_ops::breakpoint_hit, breakpoint_hit_catch_exec(), breakpoint_hit_catch_fork(), breakpoint_hit_catch_solib(), breakpoint_hit_catch_syscall(), breakpoint_hit_catch_vfork(), breakpoint_hit_ranged_breakpoint(), breakpoint_hit_watchpoint(), catch_exec_breakpoint_ops, catch_fork_breakpoint_ops, catch_solib_breakpoint_ops, catch_syscall_breakpoint_ops, catch_vfork_breakpoint_ops, breakpoint_ops::check_status, check_status_catch_solib(), check_status_watchpoint(), breakpoint_ops::create_breakpoints_sal, breakpoint_ops::create_sals_from_address, breakpoint_ops::decode_linespec, dprintf_after_condition_true(), dprintf_breakpoint_ops, dprintf_print_recreate(), dprintf_re_set(), breakpoint_ops::dtor, dtor_catch_exec(), dtor_catch_solib(), dtor_catch_syscall(), dtor_watchpoint(), breakpoint_ops::explains_signal, explains_signal_watchpoint(), insert_catch_exec(), insert_catch_fork(), insert_catch_solib(), insert_catch_syscall(), insert_catch_vfork(), breakpoint_ops::insert_location, insert_masked_watchpoint(), insert_watchpoint(), internal_bkpt_check_status(), internal_bkpt_print_it(), internal_bkpt_print_mention(), internal_bkpt_re_set(), internal_breakpoint_ops, longjmp_bkpt_dtor(), longjmp_breakpoint_ops, masked_watchpoint_breakpoint_ops, momentary_bkpt_check_status(), momentary_bkpt_print_it(), momentary_bkpt_print_mention(), momentary_bkpt_re_set(), momentary_breakpoint_ops, breakpoint_ops::print_it, print_it_catch_exec(), print_it_catch_fork(), print_it_catch_solib(), print_it_catch_syscall(), print_it_catch_vfork(), print_it_masked_watchpoint(), print_it_ranged_breakpoint(), print_it_watchpoint(), breakpoint_ops::print_mention, print_mention_catch_exec(), print_mention_catch_fork(), print_mention_catch_solib(), print_mention_catch_syscall(), print_mention_catch_vfork(), print_mention_masked_watchpoint(), print_mention_ranged_breakpoint(), print_mention_watchpoint(), breakpoint_ops::print_one, print_one_catch_exec(), print_one_catch_fork(), print_one_catch_solib(), print_one_catch_syscall(), print_one_catch_vfork(), breakpoint_ops::print_one_detail, print_one_detail_masked_watchpoint(), print_one_detail_ranged_breakpoint(), print_one_ranged_breakpoint(), breakpoint_ops::print_recreate, print_recreate_catch_exec(), print_recreate_catch_fork(), print_recreate_catch_solib(), print_recreate_catch_syscall(), print_recreate_catch_vfork(), print_recreate_masked_watchpoint(), print_recreate_ranged_breakpoint(), print_recreate_watchpoint(), ranged_breakpoint_ops, breakpoint_ops::re_set, re_set_watchpoint(), remove_catch_exec(), remove_catch_fork(), remove_catch_solib(), remove_catch_syscall(), remove_catch_vfork(), breakpoint_ops::remove_location, remove_masked_watchpoint(), remove_watchpoint(), breakpoint_ops::resources_needed, resources_needed_masked_watchpoint(), resources_needed_ranged_breakpoint(), resources_needed_watchpoint(), strace_marker_breakpoint_ops, strace_marker_create_breakpoints_sal(), strace_marker_create_sals_from_address(), strace_marker_decode_linespec(), tracepoint_breakpoint_hit(), tracepoint_breakpoint_ops, tracepoint_create_breakpoints_sal(), tracepoint_create_sals_from_address(), tracepoint_decode_linespec(), tracepoint_print_mention(), tracepoint_print_one_detail(), tracepoint_print_recreate(), tracepoint_probe_breakpoint_ops, tracepoint_probe_create_sals_from_address(), tracepoint_probe_decode_linespec(), tracepoint_re_set(), watchpoint_breakpoint_ops, breakpoint_ops::works_in_software_mode, works_in_software_mode_masked_watchpoint(), and works_in_software_mode_watchpoint().
Referenced by initialize_ada_catchpoint_ops(), initialize_signal_catchpoint_ops(), and initialize_throw_catchpoint_ops().
static int insert_bp_location (struct bp_location * bl, struct ui_file * tmp_error_stream, int * disabled_breaks, int * hw_breakpoint_error, int * hw_bp_error_explained_already) [static]
Definition at line 2372 of file breakpoint.c.
References _, bp_location::address, ALL_BP_LOCATIONS, program_space::aspace, mem_region::attrib, bp_catchpoint, bp_disabled, bp_hardware_breakpoint, bp_loc_hardware_breakpoint, bp_loc_hardware_watchpoint, bp_loc_software_breakpoint, build_target_command_list(), build_target_condition_list(), disp_del_at_next_stop, breakpoint::disposition, do_cleanups(), bp_location::duplicate, breakpoint::enable_state, fprintf_filtered(), fprintf_unfiltered(), gdb_assert, gdb_stdout, bp_location::gdbarch, hw_access, hw_read, breakpoint_ops::insert_location, bp_location::inserted, is_breakpoint(), bp_target_info::length, bp_location::length, bp_location::loc_type, lookup_mem_region(), make_cleanup(), MEM_RW, memory_error_message(), gdb_exception::message, mem_attrib::mode, bp_location::needs_update, new_type(), breakpoint::number, observer_notify_breakpoint_modified(), breakpoint::ops, overlay_debugging, bp_location::overlay_target_info, overlay_unmapped_address(), ovly_off, bp_location::owner, paddress(), bp_target_info::placed_address, bp_target_info::placed_address_space, bp_location::pspace, gdb_exception::reason, RETURN_MASK_ALL, bp_location::section, section_is_mapped(), section_is_overlay(), bp_location::shlib_disabled, should_be_inserted(), solib_name_from_address(), bp_location::target_info, target_insert_breakpoint(), TARGET_XFER_E_IO, TRY_CATCH, breakpoint::type, warning(), watchpoint_locations_match(), bp_location::watchpoint_type, and xfree().
Referenced by insert_breakpoint_locations(), reattach_breakpoints(), and update_inserted_breakpoint_locations().
static void insert_breakpoint_locations (void) [static]
Definition at line 2814 of file breakpoint.c.
References ALL_BP_LOCATIONS, ALL_BREAKPOINTS, disp_del_at_next_stop, breakpoint::disposition, do_cleanups(), error_stream(), fprintf_unfiltered(), gdbarch_has_global_breakpoints(), inferior_ptid, insert_bp_location(), bp_location::inserted, is_hardware_watchpoint(), breakpoint::loc, make_cleanup_ui_file_delete(), mark_uninserted, mem_fileopen(), bp_location::needs_update, bp_location::next, null_ptid, breakpoint::number, bp_location::owner, bp_location::pspace, ptid_equal(), remove_breakpoint(), save_current_space_and_thread(), should_be_inserted(), switch_to_program_space_and_thread(), target_gdbarch(), target_terminal_ours_for_output, breakpoint::thread, and valid_thread_id().
Referenced by insert_breakpoints(), and update_global_location_list().
void insert_breakpoints (void)
Definition at line 2716 of file breakpoint.c.
References ALL_BREAKPOINTS, breakpoints_always_inserted_mode(), insert_breakpoint_locations(), is_hardware_watchpoint(), update_global_location_list(), and update_watchpoint().
Referenced by arm_linux_copy_svc(), follow_exec(), follow_inferior_reset_breakpoints(), gdbsim_create_inferior(), go32_create_inferior(), handle_inferior_event(), inferior_call_waitpid(), inferior_call_waitpid_cleanup(), keep_going(), linux_fork_context(), proceed(), remote_start_remote(), and resume().
static int insert_catch_exec (struct bp_location * bl) [static]
Definition at line 8530 of file breakpoint.c.
References inferior_ptid, ptid_get_pid(), and target_insert_exec_catchpoint.
Referenced by initialize_breakpoint_ops().
static int insert_catch_fork (struct bp_location * bl) [static]
Definition at line 7548 of file breakpoint.c.
References inferior_ptid, ptid_get_pid(), and target_insert_fork_catchpoint.
Referenced by initialize_breakpoint_ops().
static int insert_catch_solib (struct bp_location * ignore) [static]
Definition at line 7810 of file breakpoint.c.
Referenced by initialize_breakpoint_ops().
static int insert_catch_syscall (struct bp_location * bl) [static]
Definition at line 8131 of file breakpoint.c.
References catch_syscall_inferior_data::any_syscall_count, current_inferior(), get_catch_syscall_inferior_data(), inferior_ptid, memset(), bp_location::owner, ptid_get_pid(), target_set_syscall_catchpoint, VEC_address, VEC_index, VEC_iterate, VEC_length, VEC_replace, and VEC_safe_grow.
Referenced by initialize_breakpoint_ops().
static int insert_catch_vfork (struct bp_location * bl) [static]
Definition at line 7665 of file breakpoint.c.
References inferior_ptid, ptid_get_pid(), and target_insert_vfork_catchpoint.
Referenced by initialize_breakpoint_ops().
static int insert_masked_watchpoint (struct bp_location * bl) [static]
Definition at line 10711 of file breakpoint.c.
References bp_location::address, watchpoint::hw_wp_mask, bp_location::owner, target_insert_mask_watchpoint(), and bp_location::watchpoint_type.
Referenced by initialize_breakpoint_ops().
void insert_single_step_breakpoint (struct gdbarch * gdbarch, struct address_space * aspace, CORE_ADDR next_pc)
Definition at line 14903 of file breakpoint.c.
References _, deprecated_insert_raw_breakpoint(), error(), gdb_assert, and paddress().
Referenced by alpha_deal_with_atomic_sequence(), alpha_software_single_step(), arm_insert_single_step_breakpoint(), cris_software_single_step(), micromips_deal_with_atomic_sequence(), mips_deal_with_atomic_sequence(), mips_software_single_step(), nios2_software_single_step(), ppc_deal_with_atomic_sequence(), rs6000_software_single_step(), sparc_software_single_step(), spu_software_single_step(), and tic6x_software_single_step().
static int insert_watchpoint (struct bp_location * bl) [static]
Definition at line 10457 of file breakpoint.c.
References bp_location::address, watchpoint::cond_exp, watchpoint::exact, bp_location::length, bp_location::owner, target_insert_watchpoint, and bp_location::watchpoint_type.
Referenced by initialize_breakpoint_ops().
void install_breakpoint (int internal, struct breakpoint * b, int update_gll)
Definition at line 8469 of file breakpoint.c.
References add_to_breakpoint_chain(), is_tracepoint(), mention(), observer_notify_breakpoint_created(), set_breakpoint_number(), set_tracepoint_count(), and update_global_location_list().
Referenced by add_solib_catchpoint(), catch_exec_command_1(), create_ada_exception_catchpoint(), create_breakpoint(), create_breakpoint_sal(), create_fork_vfork_event_catchpoint(), create_signal_catchpoint(), create_syscall_event_catchpoint(), handle_gnu_v3_exceptions(), strace_marker_create_breakpoints_sal(), and watch_command_1().
static void internal_bkpt_check_status (bpstat bs) [static]
Definition at line 13057 of file breakpoint.c.
References bp_shlib_event, bpstats::breakpoint_at, bpstats::print, bpstats::stop, stop_on_solib_events, and breakpoint::type.
Referenced by initialize_breakpoint_ops().
static enum print_stop_action internal_bkpt_print_it (bpstat bs) [static]
Definition at line 13073 of file breakpoint.c.
References _, bp_exception_master, bp_longjmp_master, bp_overlay_event, bp_shlib_event, bp_std_terminate_master, bp_thread_event, bpstats::breakpoint_at, PRINT_NOTHING, print_solib_event(), printf_filtered(), and breakpoint::type.
Referenced by initialize_breakpoint_ops().
static void internal_bkpt_print_mention (struct breakpoint * b) [static]
Definition at line 13121 of file breakpoint.c.
Referenced by initialize_breakpoint_ops().
static void internal_bkpt_re_set (struct breakpoint * b) [static]
Definition at line 13032 of file breakpoint.c.
References bp_exception_master, bp_longjmp_master, bp_overlay_event, bp_shlib_event, bp_std_terminate_master, bp_thread_event, delete_breakpoint(), and breakpoint::type.
Referenced by initialize_breakpoint_ops().
static void ATTRIBUTE_NORETURN invalid_thread_id_error (int id) [static]
Definition at line 9408 of file breakpoint.c.
References _, and error().
Referenced by find_condition_and_thread(), and watch_command_1().
static void invalidate_bp_value_on_memory_change (struct inferior * inferior, CORE_ADDR addr, ssize_t len, const bfd_byte * data) [static]
Definition at line 14823 of file breakpoint.c.
References bp_location::address, ALL_BREAKPOINTS, bp_enabled, bp_hardware_watchpoint, bp_loc_hardware_watchpoint, breakpoint::enable_state, bp_location::length, breakpoint::loc, bp_location::loc_type, bp_location::next, breakpoint::type, watchpoint::val, watchpoint::val_valid, and value_free().
int is_breakpoint (const struct breakpoint * bpt)
Definition at line 1590 of file breakpoint.c.
References bp_breakpoint, bp_dprintf, bp_hardware_breakpoint, and breakpoint::type.
Referenced by bp_condition_evaluator(), bp_location_condition_evaluator(), build_target_command_list(), build_target_condition_list(), condition_command(), force_breakpoint_reinsertion(), insert_bp_location(), mark_breakpoint_location_modified(), mark_breakpoint_modified(), print_breakpoint_location(), print_one_breakpoint_location(), set_condition_evaluation_mode(), update_global_location_list(), and update_inserted_breakpoint_locations().
int is_catchpoint (struct breakpoint * ep)
Definition at line 4117 of file breakpoint.c.
References bp_catchpoint, and breakpoint::type.
Referenced by print_one_breakpoint_location().
static int is_hardware_watchpoint (const struct breakpoint * bpt) [static]
Definition at line 1600 of file breakpoint.c.
References bp_access_watchpoint, bp_hardware_watchpoint, bp_read_watchpoint, and breakpoint::type.
Referenced by bpstat_stop_status(), breakpoint_hit_watchpoint(), breakpoint_locations_match(), hw_watchpoint_used_count_others(), insert_breakpoint_locations(), insert_breakpoints(), is_watchpoint(), print_one_breakpoint(), update_global_location_list(), and watchpoints_triggered().
static int is_masked_watchpoint (const struct breakpoint * b) [static]
Definition at line 10890 of file breakpoint.c.
References masked_watchpoint_breakpoint_ops, and breakpoint::ops.
Referenced by update_watchpoint(), watchpoint_check(), and watchpoints_triggered().
static int is_non_inline_function (struct breakpoint * b) [static]
Definition at line 15745 of file breakpoint.c.
References bp_shlib_event, and breakpoint::type.
Referenced by pc_at_non_inline_function().
static int is_syscall_catchpoint_enabled (struct breakpoint * bp) [static]
Definition at line 15025 of file breakpoint.c.
References bp_call_disabled, bp_disabled, breakpoint::enable_state, and syscall_catchpoint_p().
Referenced by catching_syscall_number().
int is_tracepoint (const struct breakpoint * b)
Definition at line 1112 of file breakpoint.c.
References is_tracepoint_type(), and breakpoint::type.
Referenced by breakpoint_locations_match(), delete_trace_command(), disable_breakpoint(), disable_breakpoints_in_shlibs(), disable_breakpoints_in_unloaded_shlib(), disable_command(), do_map_commands_command(), enable_breakpoint_disp(), enable_command(), install_breakpoint(), mi_cmd_break_commands(), print_one_breakpoint_location(), remove_breakpoints(), save_breakpoints(), save_tracepoints_command(), set_breakpoint_location_function(), set_ignore_count(), swap_insertion(), tracepoint_locations_match(), tracepoints_info(), update_global_location_list(), and validate_commands_for_breakpoint().
static int is_tracepoint_type (enum bptype type) [static]
Definition at line 1104 of file breakpoint.c.
References bp_fast_tracepoint, bp_static_tracepoint, and bp_tracepoint.
Referenced by create_breakpoint(), create_breakpoint_sal(), and is_tracepoint().
int is_watchpoint (const struct breakpoint * bpt)
Definition at line 1611 of file breakpoint.c.
References bp_watchpoint, is_hardware_watchpoint(), and breakpoint::type.
Referenced by aarch64_dr_state_insert_one_point(), aarch64_dr_state_remove_one_point(), aarch64_notify_debug_reg_change(), bppy_get_expression(), bpstat_check_breakpoint_conditions(), check_status_watchpoint(), clear_command(), debug_reg_change_callback(), disable_watchpoints_before_interactive_call_start(), enable_breakpoint_disp(), enable_watchpoints_after_interactive_call_stop(), gdb_get_breakpoint_info(), print_one_breakpoint_location(), save_breakpoints(), set_breakpoint_condition(), and watchpoints_info().
void iterate_over_bp_locations (walk_bp_location_callback callback)
Definition at line 2740 of file breakpoint.c.
References ALL_BP_LOCATIONS.
Referenced by record_full_init_record_breakpoints().
struct breakpoint* iterate_over_breakpoints (int(*)(struct breakpoint *, void *) callback, void * data) [read]
Definition at line 15727 of file breakpoint.c.
References ALL_BREAKPOINTS_SAFE.
Referenced by bpfinishpy_handle_exit(), bpfinishpy_handle_stop(), gdbpy_breakpoints(), pop_dummy_frame(), and svr4_update_solib_event_breakpoints().
static void iterate_over_related_breakpoints (struct breakpoint * b, void(*)(struct breakpoint *, void *) function, void * data) [static]
Definition at line 13684 of file breakpoint.c.
References breakpoint::next, and breakpoint::related_breakpoint.
Referenced by do_map_delete_breakpoint(), do_map_disable_breakpoint(), do_map_enable_breakpoint(), do_map_enable_count_breakpoint(), do_map_enable_delete_breakpoint(), and do_map_enable_once_breakpoint().
static int locations_are_equal (struct bp_location * a, struct bp_location * b) [static]
Definition at line 13948 of file breakpoint.c.
References bp_location::address, bp_location::enabled, bp_location::next, and bp_location::shlib_disabled.
Referenced by update_breakpoint_locations().
static void longjmp_bkpt_dtor (struct breakpoint * self) [static]
Definition at line 13183 of file breakpoint.c.
References breakpoint_ops::dtor, find_thread_id(), thread_info::initiating_frame, momentary_breakpoint_ops, and null_frame_id.
Referenced by initialize_breakpoint_ops().
static void maintenance_info_breakpoints (char * args, int from_tty) [static]
Definition at line 6579 of file breakpoint.c.
References breakpoint_1(), and default_collect_info().
void make_breakpoint_permanent (struct breakpoint * b)
Definition at line 7158 of file breakpoint.c.
References bp_permanent, breakpoint::enable_state, bp_location::inserted, breakpoint::loc, and bp_location::next.
Referenced by init_breakpoint_sal(), and update_breakpoint_locations().
static struct cleanup* make_cleanup_decref_counted_command_line (struct counted_command_line ** cmdp) [static, read]
Definition at line 717 of file breakpoint.c.
References do_cleanup_counted_command_line(), and make_cleanup().
Referenced by bpstat_do_actions_1(), commands_command_1(), and dprintf_after_condition_true().
struct cleanup* make_cleanup_delete_breakpoint (struct breakpoint * b) [read]
Definition at line 13675 of file breakpoint.c.
References do_delete_breakpoint_cleanup(), and make_cleanup().
Referenced by finish_forward(), and until_break_command().
static void map_breakpoint_numbers (char * args, void(*)(struct breakpoint *,void *) function, void * data) [static]
Definition at line 14436 of file breakpoint.c.
References _, ALL_BREAKPOINTS_SAFE, error_no_arg(), get_number_or_range_state::finished, get_number_or_range(), init_number_or_range(), breakpoint::number, p, printf_unfiltered(), get_number_or_range_state::string, and warning().
Referenced by commands_command_1(), delete_command(), delete_trace_command(), disable_command(), enable_command(), enable_count_command(), enable_delete_command(), and enable_once_command().
static void mark_breakpoint_location_modified (struct bp_location * loc) [static]
Definition at line 767 of file breakpoint.c.
References bp_location::condition_changed, condition_modified, gdb_evaluates_breakpoint_condition_p(), is_breakpoint(), bp_location::owner, and target_supports_evaluation_of_breakpoint_conditions.
Referenced by disable_command(), enable_command(), init_bp_location(), and set_condition_evaluation_mode().
static void mark_breakpoint_modified (struct breakpoint * b) [static]
Definition at line 744 of file breakpoint.c.
References bp_location::condition_changed, condition_modified, gdb_evaluates_breakpoint_condition_p(), is_breakpoint(), breakpoint::loc, bp_location::next, and target_supports_evaluation_of_breakpoint_conditions.
Referenced by disable_breakpoint(), enable_breakpoint_disp(), and set_breakpoint_condition().
void mark_breakpoints_out (void)
Definition at line 3765 of file breakpoint.c.
References ALL_BP_LOCATIONS, current_program_space, bp_location::inserted, and bp_location::pspace.
Referenced by follow_exec(), and generic_mourn_inferior().
static void mention (struct breakpoint * b) [static]
Definition at line 8853 of file breakpoint.c.
References current_uiout, breakpoint::ops, breakpoint_ops::print_mention, printf_filtered(), and ui_out_is_mi_like_p().
Referenced by break_range_command(), install_breakpoint(), print_it_masked_watchpoint(), and print_it_watchpoint().
static void momentary_bkpt_check_status (bpstat bs) [static]
Definition at line 13138 of file breakpoint.c.
Referenced by initialize_breakpoint_ops().
static enum print_stop_action momentary_bkpt_print_it (bpstat bs) [static]
Definition at line 13144 of file breakpoint.c.
References async_reason_lookup(), bp_finish, bp_until, bpstats::breakpoint_at, current_uiout, EXEC_ASYNC_FUNCTION_FINISHED, EXEC_ASYNC_LOCATION_REACHED, PRINT_UNKNOWN, breakpoint::type, ui_out_field_string(), and ui_out_is_mi_like_p().
Referenced by initialize_breakpoint_ops().
static void momentary_bkpt_print_mention (struct breakpoint * b) [static]
Definition at line 13172 of file breakpoint.c.
Referenced by initialize_breakpoint_ops().
static void momentary_bkpt_re_set (struct breakpoint * b) [static]
Definition at line 13129 of file breakpoint.c.
Referenced by initialize_breakpoint_ops().
static struct breakpoint * momentary_breakpoint_from_master (struct breakpoint * orig, enum bptype type, const struct breakpoint_ops * ops) [static, read]
Definition at line 8792 of file breakpoint.c.
References bp_location::address, allocate_bp_location(), bp_enabled, disp_donttouch, breakpoint::disposition, breakpoint::enable_state, breakpoint::frame_id, bp_location::gdbarch, breakpoint::gdbarch, bp_location::line_number, breakpoint::loc, breakpoint::number, bp_location::probe, bp_location::pspace, breakpoint::pspace, bp_location::requested_address, bp_location::section, set_breakpoint_location_function(), set_raw_breakpoint_without_location(), bp_location::symtab, breakpoint::thread, and update_global_location_list_nothrow().
Referenced by clone_momentary_breakpoint(), set_longjmp_breakpoint(), set_longjmp_breakpoint_for_call_dummy(), and set_std_terminate_breakpoint().
int moribund_breakpoint_here_p (struct address_space * aspace, CORE_ADDR pc)
Definition at line 3929 of file breakpoint.c.
References breakpoint_location_address_match(), and VEC_iterate.
Referenced by adjust_pc_after_break().
static int msym_not_found_p (const struct minimal_symbol * msym) [static]
Definition at line 3109 of file breakpoint.c.
References msym_not_found.
Referenced by create_exception_master_breakpoint(), create_longjmp_master_breakpoint(), create_overlay_event_breakpoint(), and create_std_terminate_master_breakpoint().
static void output_thread_groups (struct ui_out * uiout, const char * field_name, VEC(int)* inf_num, int mi_only) [static]
Definition at line 5862 of file breakpoint.c.
References do_cleanups(), arm-linux::inf, make_cleanup_ui_out_list_begin_end(), plongest(), ui_out_field_string(), ui_out_is_mi_like_p(), ui_out_text(), VEC_iterate, and xsnprintf().
Referenced by print_one_breakpoint_location().
static void parse_breakpoint_sals (char ** address, struct linespec_result * canonical) [static]
Definition at line 9282 of file breakpoint.c.
References _, linespec_sals::canonical, decode_line_full(), DECODE_LINE_FUNFIRSTLINE, error(), symtab_and_line::explicit_pc, find_pc_line(), get_current_source_symtab_and_line(), get_last_displayed_line(), get_last_displayed_sal(), get_last_displayed_symtab(), init_sal(), last_displayed_sal_is_valid(), symtab_and_line::line, symtabs_and_lines::nelts, symtab_and_line::pc, linespec_sals::sals, symtabs_and_lines::sals, strchr(), symtab_and_line::symtab, VEC_safe_push, and xmalloc().
Referenced by break_range_command(), and create_sals_from_address_default().
static struct agent_expr* parse_cmd_to_aexpr (CORE_ADDR scope, char * cmd) [static, read]
Definition at line 2179 of file breakpoint.c.
References _, block_for_pc(), do_cleanups(), error(), free_format_pieces_cleanup(), gen_printf(), get_current_arch(), make_cleanup(), parse_exp_1(), parse_format_string(), gdb_exception::reason, RETURN_MASK_ERROR, skip_spaces_const(), and TRY_CATCH.
Referenced by build_target_command_list().
static struct agent_expr* parse_cond_to_aexpr (CORE_ADDR scope, struct expression * cond) [static, read]
Definition at line 2044 of file breakpoint.c.
References gen_eval_for_expr(), gdb_exception::reason, RETURN_MASK_ERROR, and TRY_CATCH.
Referenced by build_target_condition_list().
int pc_at_non_inline_function (struct address_space * aspace, CORE_ADDR pc, const struct target_waitstatus * ws)
Definition at line 15759 of file breakpoint.c.
References ALL_BREAKPOINTS, bpstat_check_location(), is_non_inline_function(), breakpoint::loc, bp_location::next, and bp_location::shlib_disabled.
Referenced by handle_inferior_event().
static struct cleanup* prepare_re_set_context (struct breakpoint * b) [static, read]
Definition at line 14278 of file breakpoint.c.
References input_radix, breakpoint::input_radix, breakpoint::language, breakpoint::pspace, save_current_space_and_thread(), set_language(), and switch_to_program_space_and_thread().
Referenced by breakpoint_re_set_one().
static enum print_stop_action print_bp_stop_message (bpstat bs) [static]
Definition at line 4476 of file breakpoint.c.
References _, bpstats::breakpoint_at, internal_error(), breakpoint::ops, breakpoint_ops::print_it, bpstats::print_it, print_it_done, print_it_noop, print_it_normal, PRINT_SRC_AND_LOC, and PRINT_UNKNOWN.
Referenced by bpstat_print().
static void print_breakpoint_location (struct breakpoint * b, struct bp_location * loc) [static]
Definition at line 5740 of file breakpoint.c.
References breakpoint::addr_string, bp_location::address, bp_condition_evaluator(), bp_location_condition_evaluator(), breakpoint_condition_evaluation_mode(), current_uiout, demangle, breakpoint::display_canonical, do_cleanups(), find_pc_sect_function(), bp_location::gdbarch, is_breakpoint(), bp_location::line_number, make_cleanup_ui_file_delete(), mem_fileopen(), print_address_symbolic(), bp_location::pspace, save_current_program_space(), bp_location::section, set_current_program_space(), bp_location::shlib_disabled, SYMBOL_PRINT_NAME, bp_location::symtab, symtab_to_filename_for_display(), symtab_to_fullname(), ui_out_field_int(), ui_out_field_stream(), ui_out_field_string(), ui_out_is_mi_like_p(), ui_out_text(), ui_out_wrap_hint(), and wrap_indent_at_field().
Referenced by print_one_breakpoint_location(), and print_one_ranged_breakpoint().
static enum print_stop_action print_it_catch_exec (bpstat bs) [static]
Definition at line 8556 of file breakpoint.c.
References annotate_catchpoint(), async_reason_lookup(), bpdisp_text(), bpstats::breakpoint_at, current_uiout, disp_del, breakpoint::disposition, EXEC_ASYNC_EXEC, exec_catchpoint::exec_pathname, breakpoint::number, PRINT_SRC_AND_LOC, ui_out_field_int(), ui_out_field_string(), ui_out_is_mi_like_p(), and ui_out_text().
Referenced by initialize_breakpoint_ops().
static enum print_stop_action print_it_catch_fork (bpstat bs) [static]
Definition at line 7583 of file breakpoint.c.
References annotate_catchpoint(), async_reason_lookup(), bpdisp_text(), bpstats::breakpoint_at, current_uiout, disp_del, breakpoint::disposition, EXEC_ASYNC_FORK, fork_catchpoint::forked_inferior_pid, breakpoint::number, PRINT_SRC_AND_LOC, ptid_get_pid(), ui_out_field_int(), ui_out_field_string(), ui_out_is_mi_like_p(), and ui_out_text().
Referenced by initialize_breakpoint_ops().
static enum print_stop_action print_it_catch_solib (bpstat bs) [static]
Definition at line 7897 of file breakpoint.c.
References annotate_catchpoint(), bpdisp_text(), bpstats::breakpoint_at, current_uiout, disp_del, breakpoint::disposition, breakpoint::number, print_solib_event(), PRINT_SRC_AND_LOC, ui_out_field_int(), ui_out_field_string(), ui_out_is_mi_like_p(), and ui_out_text().
Referenced by initialize_breakpoint_ops().
static enum print_stop_action print_it_catch_syscall (bpstat bs) [static]
Definition at line 8261 of file breakpoint.c.
References annotate_catchpoint(), async_reason_lookup(), bpdisp_text(), bpstats::breakpoint_at, current_uiout, disp_del, breakpoint::disposition, EXEC_ASYNC_SYSCALL_ENTRY, EXEC_ASYNC_SYSCALL_RETURN, get_last_target_status(), get_syscall_by_number(), target_waitstatus::kind, syscall::name, breakpoint::number, PRINT_SRC_AND_LOC, target_waitstatus::syscall_number, TARGET_WAITKIND_SYSCALL_ENTRY, ui_out_field_int(), ui_out_field_string(), ui_out_is_mi_like_p(), ui_out_text(), and target_waitstatus::value.
Referenced by initialize_breakpoint_ops().
static enum print_stop_action print_it_catch_vfork (bpstat bs) [static]
Definition at line 7700 of file breakpoint.c.
References annotate_catchpoint(), async_reason_lookup(), bpdisp_text(), bpstats::breakpoint_at, current_uiout, disp_del, breakpoint::disposition, EXEC_ASYNC_VFORK, fork_catchpoint::forked_inferior_pid, breakpoint::number, PRINT_SRC_AND_LOC, ptid_get_pid(), ui_out_field_int(), ui_out_field_string(), ui_out_is_mi_like_p(), and ui_out_text().
Referenced by initialize_breakpoint_ops().
static enum print_stop_action print_it_masked_watchpoint (bpstat bs) [static]
Definition at line 10755 of file breakpoint.c.
References _, annotate_watchpoint(), async_reason_lookup(), bp_access_watchpoint, bp_hardware_watchpoint, bp_read_watchpoint, bpstats::breakpoint_at, current_uiout, EXEC_ASYNC_ACCESS_WATCHPOINT_TRIGGER, EXEC_ASYNC_READ_WATCHPOINT_TRIGGER, EXEC_ASYNC_WATCHPOINT_TRIGGER, gdb_assert, internal_error(), breakpoint::loc, mention(), bp_location::next, breakpoint::number, PRINT_UNKNOWN, breakpoint::type, ui_out_field_string(), ui_out_is_mi_like_p(), and ui_out_text().
Referenced by initialize_breakpoint_ops().
static enum print_stop_action print_it_ranged_breakpoint (bpstat bs) [static]
Definition at line 10024 of file breakpoint.c.
References annotate_breakpoint(), async_reason_lookup(), bp_hardware_breakpoint, bpdisp_text(), bpstats::breakpoint_at, current_uiout, disp_del, breakpoint::disposition, EXEC_ASYNC_BREAKPOINT_HIT, gdb_assert, breakpoint::loc, bp_location::next, breakpoint::number, PRINT_SRC_AND_LOC, breakpoint::type, ui_out_field_int(), ui_out_field_string(), ui_out_is_mi_like_p(), and ui_out_text().
Referenced by initialize_breakpoint_ops().
static enum print_stop_action print_it_watchpoint (bpstat bs) [static]
Definition at line 10530 of file breakpoint.c.
References annotate_watchpoint(), async_reason_lookup(), bp_access_watchpoint, bp_hardware_watchpoint, bpstats::bp_location_at, bp_read_watchpoint, bp_watchpoint, bpstats::breakpoint_at, current_uiout, do_cleanups(), EXEC_ASYNC_ACCESS_WATCHPOINT_TRIGGER, EXEC_ASYNC_READ_WATCHPOINT_TRIGGER, EXEC_ASYNC_WATCHPOINT_TRIGGER, gdb_assert, make_cleanup_ui_file_delete(), make_cleanup_ui_out_tuple_begin_end(), mem_fileopen(), mention(), breakpoint::number, bpstats::old_val, PRINT_UNKNOWN, breakpoint::type, ui_out_field_stream(), ui_out_field_string(), ui_out_is_mi_like_p(), ui_out_text(), watchpoint::val, and watchpoint_value_print().
Referenced by initialize_breakpoint_ops().
static void print_mention_catch_exec (struct breakpoint * b) [static]
Definition at line 8609 of file breakpoint.c.
References _, breakpoint::number, and printf_filtered().
Referenced by initialize_breakpoint_ops().
static void print_mention_catch_fork (struct breakpoint * b) [static]
Definition at line 7642 of file breakpoint.c.
References _, breakpoint::number, and printf_filtered().
Referenced by initialize_breakpoint_ops().
static void print_mention_catch_solib (struct breakpoint * b) [static]
Definition at line 7957 of file breakpoint.c.
References _, breakpoint::number, and printf_filtered().
Referenced by initialize_breakpoint_ops().
static void print_mention_catch_syscall (struct breakpoint * b) [static]
Definition at line 8372 of file breakpoint.c.
References _, get_syscall_by_number(), syscall::name, syscall::number, breakpoint::number, printf_filtered(), VEC_iterate, and VEC_length.
Referenced by initialize_breakpoint_ops().
static void print_mention_catch_vfork (struct breakpoint * b) [static]
Definition at line 7758 of file breakpoint.c.
References _, breakpoint::number, and printf_filtered().
Referenced by initialize_breakpoint_ops().
static void print_mention_masked_watchpoint (struct breakpoint * b) [static]
Definition at line 10822 of file breakpoint.c.
References _, bp_access_watchpoint, bp_hardware_watchpoint, bp_read_watchpoint, current_uiout, do_cleanups(), watchpoint::exp_string, internal_error(), make_cleanup_ui_out_tuple_begin_end(), breakpoint::number, breakpoint::type, ui_out_field_int(), ui_out_field_string(), and ui_out_text().
Referenced by initialize_breakpoint_ops().
static void print_mention_ranged_breakpoint (struct breakpoint * b) [static]
Definition at line 10108 of file breakpoint.c.
References _, bp_location::address, bp_hardware_breakpoint, current_uiout, gdb_assert, bp_location::gdbarch, bp_location::length, breakpoint::loc, breakpoint::number, paddress(), printf_filtered(), breakpoint::type, and ui_out_is_mi_like_p().
Referenced by initialize_breakpoint_ops().
static void print_mention_watchpoint (struct breakpoint * b) [static]
Definition at line 10625 of file breakpoint.c.
References _, bp_access_watchpoint, bp_hardware_watchpoint, bp_read_watchpoint, bp_watchpoint, current_uiout, do_cleanups(), watchpoint::exp_string, internal_error(), make_cleanup_ui_out_tuple_begin_end(), breakpoint::number, breakpoint::type, ui_out_field_int(), ui_out_field_string(), and ui_out_text().
Referenced by initialize_breakpoint_ops().
static void print_one_breakpoint (struct breakpoint * b, struct bp_location ** last_loc, int allflag) [static]
Definition at line 6262 of file breakpoint.c.
References current_uiout, do_cleanups(), bp_location::enabled, is_hardware_watchpoint(), breakpoint::loc, make_cleanup_ui_out_tuple_begin_end(), bp_location::next, breakpoint::ops, breakpoint_ops::print_one, and print_one_breakpoint_location().
Referenced by breakpoint_1(), and do_captured_breakpoint_query().
static void print_one_breakpoint_location (struct breakpoint * b, struct bp_location * loc, int loc_number, struct bp_location ** last_loc, int allflag) [static]
Definition at line 5905 of file breakpoint.c.
References _, breakpoint::addr_string, bp_location::address, value_print_options::addressprint, ALL_INFERIORS, annotate_field(), annotate_record(), bp_access_watchpoint, bp_breakpoint, bp_call_dummy, bp_catchpoint, bp_condition_evaluator(), bp_dprintf, bp_exception, bp_exception_master, bp_exception_resume, bp_fast_tracepoint, bp_finish, bp_gnu_ifunc_resolver, bp_gnu_ifunc_resolver_return, bp_hardware_breakpoint, bp_hardware_watchpoint, bp_hp_step_resume, bp_jit_event, bp_longjmp, bp_longjmp_call_dummy, bp_longjmp_master, bp_longjmp_resume, bp_none, bp_overlay_event, bp_read_watchpoint, bp_shlib_event, bp_static_tracepoint, bp_std_terminate, bp_std_terminate_master, bp_step_resume, bp_thread_event, bp_tracepoint, bp_until, bp_watchpoint, bp_watchpoint_scope, bpdisp_text(), bptype_string(), breakpoint_condition_evaluation_mode(), counted_command_line::commands, breakpoint::commands, breakpoint::cond_string, current_uiout, breakpoint::disposition, do_cleanups(), breakpoint::enable_count, breakpoint::enable_state, bp_location::enabled, watchpoint::exp_string, breakpoint::frame_id, frame_id_p(), gdb_assert, bp_location::gdbarch, breakpoint::gdbarch, gdbarch_has_global_breakpoints(), get_user_print_options(), breakpoint::hit_count, breakpoint::ignore_count, arm-linux::inf, bp_location::inserted, internal_error(), is_breakpoint(), is_catchpoint(), is_tracepoint(), is_watchpoint(), breakpoint::loc, make_cleanup_ui_out_tuple_begin_end(), bp_location::next, inferior::num, breakpoint::number, number_of_inferiors(), number_of_program_spaces(), breakpoint::ops, output_thread_groups(), bp_location::owner, tracepoint::pass_count, print_breakpoint_location(), print_command_lines(), breakpoint_ops::print_one, breakpoint_ops::print_one_detail, bp_location::pspace, inferior::pspace, bp_location::shlib_disabled, frame_id::stack_addr, target_gdbarch(), breakpoint::task, breakpoint::thread, tracepoint::traceframe_usage, breakpoint::type, ui_out_field_core_addr(), ui_out_field_fmt(), ui_out_field_int(), ui_out_field_skip(), ui_out_field_string(), ui_out_is_mi_like_p(), ui_out_spaces(), ui_out_text(), VEC, VEC_free, VEC_safe_push, xfree(), and xstrprintf().
Referenced by print_one_breakpoint().
static void print_one_catch_exec (struct breakpoint * b, struct bp_location ** last_loc) [static]
Definition at line 8582 of file breakpoint.c.
References value_print_options::addressprint, annotate_field(), current_uiout, exec_catchpoint::exec_pathname, get_user_print_options(), ui_out_field_skip(), ui_out_field_string(), ui_out_is_mi_like_p(), and ui_out_text().
Referenced by initialize_breakpoint_ops().
static void print_one_catch_fork (struct breakpoint * b, struct bp_location ** last_loc) [static]
Definition at line 7611 of file breakpoint.c.
References value_print_options::addressprint, annotate_field(), current_uiout, fork_catchpoint::forked_inferior_pid, get_user_print_options(), null_ptid, ptid_equal(), ptid_get_pid(), ui_out_field_int(), ui_out_field_skip(), ui_out_field_string(), ui_out_is_mi_like_p(), ui_out_spaces(), and ui_out_text().
Referenced by initialize_breakpoint_ops().
static void print_one_catch_solib (struct breakpoint * b, struct bp_location ** locs) [static]
Definition at line 7916 of file breakpoint.c.
References _, value_print_options::addressprint, annotate_field(), current_uiout, get_user_print_options(), ui_out_field_skip(), ui_out_field_string(), ui_out_is_mi_like_p(), xfree(), and xstrprintf().
Referenced by initialize_breakpoint_ops().
static void print_one_catch_syscall (struct breakpoint * b, struct bp_location ** last_loc) [static]
Definition at line 8312 of file breakpoint.c.
References value_print_options::addressprint, annotate_field(), current_uiout, get_syscall_by_number(), get_user_print_options(), syscall::name, ui_out_field_skip(), ui_out_field_string(), ui_out_is_mi_like_p(), ui_out_text(), VEC_iterate, VEC_length, xfree(), and xstrprintf().
Referenced by initialize_breakpoint_ops().
static void print_one_catch_vfork (struct breakpoint * b, struct bp_location ** last_loc) [static]
Definition at line 7728 of file breakpoint.c.
References value_print_options::addressprint, annotate_field(), current_uiout, fork_catchpoint::forked_inferior_pid, get_user_print_options(), null_ptid, ptid_equal(), ptid_get_pid(), ui_out_field_int(), ui_out_field_skip(), ui_out_field_string(), ui_out_is_mi_like_p(), ui_out_spaces(), and ui_out_text().
Referenced by initialize_breakpoint_ops().
static void print_one_detail_masked_watchpoint (const struct breakpoint * b, struct ui_out * uiout) [static]
Definition at line 10805 of file breakpoint.c.
References gdb_assert, bp_location::gdbarch, watchpoint::hw_wp_mask, breakpoint::loc, bp_location::next, ui_out_field_core_addr(), and ui_out_text().
Referenced by initialize_breakpoint_ops().
static void print_one_detail_ranged_breakpoint (const struct breakpoint * b, struct ui_out * uiout) [static]
Definition at line 10081 of file breakpoint.c.
References bp_location::address, do_cleanups(), fprintf_unfiltered(), gdb_assert, bp_location::gdbarch, bp_location::length, breakpoint::loc, make_cleanup_ui_file_delete(), mem_fileopen(), print_core_address(), ui_out_field_stream(), and ui_out_text().
Referenced by initialize_breakpoint_ops().
static void print_one_ranged_breakpoint (struct breakpoint * b, struct bp_location ** last_loc) [static]
Definition at line 10056 of file breakpoint.c.
References value_print_options::addressprint, annotate_field(), current_uiout, gdb_assert, get_user_print_options(), breakpoint::loc, bp_location::next, print_breakpoint_location(), and ui_out_field_skip().
Referenced by initialize_breakpoint_ops().
static void print_recreate_catch_exec (struct breakpoint * b, struct ui_file * fp) [static]
Definition at line 8618 of file breakpoint.c.
References fprintf_unfiltered(), and print_recreate_thread().
Referenced by initialize_breakpoint_ops().
static void print_recreate_catch_fork (struct breakpoint * b, struct ui_file * fp) [static]
Definition at line 7651 of file breakpoint.c.
References fprintf_unfiltered(), and print_recreate_thread().
Referenced by initialize_breakpoint_ops().
static void print_recreate_catch_solib (struct breakpoint * b, struct ui_file * fp) [static]
Definition at line 7966 of file breakpoint.c.
References disp_del, breakpoint::disposition, and fprintf_unfiltered().
Referenced by initialize_breakpoint_ops().
static void print_recreate_catch_syscall (struct breakpoint * b, struct ui_file * fp) [static]
Definition at line 8408 of file breakpoint.c.
References fprintf_unfiltered(), get_syscall_by_number(), syscall::name, syscall::number, print_recreate_thread(), and VEC_iterate.
Referenced by initialize_breakpoint_ops().
static void print_recreate_catch_vfork (struct breakpoint * b, struct ui_file * fp) [static]
Definition at line 7767 of file breakpoint.c.
References fprintf_unfiltered(), and print_recreate_thread().
Referenced by initialize_breakpoint_ops().
static void print_recreate_masked_watchpoint (struct breakpoint * b, struct ui_file * fp) [static]
Definition at line 10857 of file breakpoint.c.
References _, bp_access_watchpoint, bp_hardware_watchpoint, bp_read_watchpoint, watchpoint::exp_string, fprintf_unfiltered(), watchpoint::hw_wp_mask, internal_error(), print_recreate_thread(), and breakpoint::type.
Referenced by initialize_breakpoint_ops().
static void print_recreate_ranged_breakpoint (struct breakpoint * b, struct ui_file * fp) [static]
Definition at line 10128 of file breakpoint.c.
References breakpoint::addr_string, breakpoint::addr_string_range_end, fprintf_unfiltered(), and print_recreate_thread().
Referenced by initialize_breakpoint_ops().
void print_recreate_thread (struct breakpoint * b, struct ui_file * fp)
Definition at line 15487 of file breakpoint.c.
References fprintf_unfiltered(), breakpoint::task, and breakpoint::thread.
Referenced by bkpt_print_recreate(), dprintf_print_recreate(), print_recreate_catch_exec(), print_recreate_catch_fork(), print_recreate_catch_syscall(), print_recreate_catch_vfork(), print_recreate_exception(), print_recreate_exception_catchpoint(), print_recreate_masked_watchpoint(), print_recreate_ranged_breakpoint(), print_recreate_watchpoint(), and tracepoint_print_recreate().
static void print_recreate_watchpoint (struct breakpoint * b, struct ui_file * fp) [static]
Definition at line 10664 of file breakpoint.c.
References _, bp_access_watchpoint, bp_hardware_watchpoint, bp_read_watchpoint, bp_watchpoint, watchpoint::exp_string, fprintf_unfiltered(), internal_error(), print_recreate_thread(), and breakpoint::type.
Referenced by initialize_breakpoint_ops().
static void print_solib_event (int is_catchpoint) [static]
Definition at line 4515 of file breakpoint.c.
References _, async_reason_lookup(), current_program_space, current_uiout, do_cleanups(), EXEC_ASYNC_SOLIB_EVENT, make_cleanup_ui_out_list_begin_end(), name, so_list::so_name, ui_out_field_string(), ui_out_is_mi_like_p(), ui_out_text(), VEC_empty, and VEC_iterate.
Referenced by bpstat_print(), internal_bkpt_print_it(), and print_it_catch_solib().
static void re_set_watchpoint (struct breakpoint * b) [static]
Definition at line 10422 of file breakpoint.c.
References update_watchpoint().
Referenced by initialize_breakpoint_ops().
static char* read_uploaded_action (void) [static]
Definition at line 15167 of file breakpoint.c.
References VEC_iterate.
Referenced by create_tracepoint_from_upload().
int reattach_breakpoints (int pid)
Definition at line 2984 of file breakpoint.c.
References ALL_BP_LOCATIONS, any_live_thread_of_process(), do_cleanups(), find_inferior_pid(), arm-linux::inf, inferior_ptid, insert_bp_location(), bp_location::inserted, make_cleanup_ui_file_delete(), mem_fileopen(), bp_location::pspace, inferior::pspace, thread_info::ptid, and save_inferior_ptid().
int regular_breakpoint_inserted_here_p (struct address_space * aspace, CORE_ADDR pc)
Definition at line 3947 of file breakpoint.c.
References ALL_BP_LOCATIONS, bp_loc_hardware_breakpoint, bp_loc_software_breakpoint, breakpoint_location_address_match(), bp_location::inserted, bp_location::loc_type, overlay_debugging, bp_location::section, section_is_mapped(), and section_is_overlay().
Referenced by breakpoint_inserted_here_p(), and handle_inferior_event().
static int remove_breakpoint (struct bp_location * bl, insertion_state_t is) [static]
Definition at line 3736 of file breakpoint.c.
References bp_none, bp_permanent, do_cleanups(), breakpoint::enable_state, gdb_assert, bp_location::owner, bp_location::pspace, remove_breakpoint_1(), save_current_space_and_thread(), switch_to_program_space_and_thread(), and breakpoint::type.
Referenced by insert_breakpoint_locations(), remove_breakpoints(), remove_breakpoints_pid(), and update_global_location_list().
static int remove_breakpoint_1 (struct bp_location * bl, insertion_state_t is) [static]
Definition at line 3622 of file breakpoint.c.
References _, bp_location::address, bp_catchpoint, bp_loc_hardware_breakpoint, bp_loc_hardware_watchpoint, bp_loc_software_breakpoint, bp_none, bp_permanent, bp_location::duplicate, breakpoint::enable_state, gdb_assert, bp_location::gdbarch, bp_location::inserted, bp_location::loc_type, mark_inserted, mark_uninserted, breakpoint::number, breakpoint::ops, overlay_debugging, bp_location::overlay_target_info, ovly_off, bp_location::owner, bp_location::pspace, breakpoint_ops::remove_location, bp_location::section, section_is_mapped(), section_is_overlay(), solib_name_from_address(), target_remove_breakpoint(), target_remove_hw_breakpoint, breakpoint::type, and warning().
Referenced by detach_breakpoints(), and remove_breakpoint().
int remove_breakpoints (void)
Definition at line 2919 of file breakpoint.c.
References ALL_BP_LOCATIONS, bp_location::inserted, is_tracepoint(), mark_uninserted, bp_location::owner, and remove_breakpoint().
Referenced by gdbsim_create_inferior(), gdbsim_mourn_inferior(), handle_inferior_event(), inferior_call_waitpid(), inferior_call_waitpid_cleanup(), keep_going(), linux_fork_context(), m32r_mourn_inferior(), normal_stop(), proceed(), and target_disconnect().
int remove_breakpoints_pid (int pid)
Definition at line 2959 of file breakpoint.c.
References ALL_BP_LOCATIONS, bp_dprintf, find_inferior_pid(), bp_location::inserted, mark_uninserted, bp_location::owner, bp_location::pspace, inferior::pspace, remove_breakpoint(), and breakpoint::type.
Referenced by linux_child_follow_fork(), and target_detach().
static int remove_catch_exec (struct bp_location * bl) [static]
Definition at line 8536 of file breakpoint.c.
References inferior_ptid, ptid_get_pid(), and target_remove_exec_catchpoint.
Referenced by initialize_breakpoint_ops().
static int remove_catch_fork (struct bp_location * bl) [static]
Definition at line 7557 of file breakpoint.c.
References inferior_ptid, ptid_get_pid(), and target_remove_fork_catchpoint.
Referenced by initialize_breakpoint_ops().
static int remove_catch_solib (struct bp_location * ignore) [static]
Definition at line 7816 of file breakpoint.c.
Referenced by initialize_breakpoint_ops().
static int remove_catch_syscall (struct bp_location * bl) [static]
Definition at line 8182 of file breakpoint.c.
References catch_syscall_inferior_data::any_syscall_count, current_inferior(), get_catch_syscall_inferior_data(), inferior_ptid, bp_location::owner, ptid_get_pid(), target_set_syscall_catchpoint, VEC_address, VEC_index, VEC_iterate, VEC_length, and VEC_replace.
Referenced by initialize_breakpoint_ops().
static int remove_catch_vfork (struct bp_location * bl) [static]
Definition at line 7674 of file breakpoint.c.
References inferior_ptid, ptid_get_pid(), and target_remove_vfork_catchpoint.
Referenced by initialize_breakpoint_ops().
void remove_jit_event_breakpoints (void)
Definition at line 7407 of file breakpoint.c.
References ALL_BREAKPOINTS_SAFE, bp_jit_event, current_program_space, delete_breakpoint(), breakpoint::loc, bp_location::pspace, and breakpoint::type.
static int remove_masked_watchpoint (struct bp_location * bl) [static]
Definition at line 10723 of file breakpoint.c.
References bp_location::address, watchpoint::hw_wp_mask, bp_location::owner, target_remove_mask_watchpoint(), and bp_location::watchpoint_type.
Referenced by initialize_breakpoint_ops().
void remove_single_step_breakpoints (void)
Definition at line 14947 of file breakpoint.c.
References deprecated_remove_raw_breakpoint(), and gdb_assert.
Referenced by handle_inferior_event(), record_full_wait_1(), and resume().
void remove_solib_event_breakpoints (void)
Definition at line 7418 of file breakpoint.c.
References ALL_BREAKPOINTS_SAFE, bp_shlib_event, current_program_space, delete_breakpoint(), breakpoint::loc, bp_location::pspace, and breakpoint::type.
Referenced by enable_break2(), and reload_shared_libraries().
void remove_thread_event_breakpoints (void)
Definition at line 7375 of file breakpoint.c.
References ALL_BREAKPOINTS_SAFE, bp_thread_event, current_program_space, delete_breakpoint(), breakpoint::loc, bp_location::pspace, and breakpoint::type.
Referenced by enable_thread_event_reporting(), thread_db_detach(), and thread_db_mourn_inferior().
static void remove_threaded_breakpoints (struct thread_info * tp, int silent) [static]
Definition at line 2936 of file breakpoint.c.
References _, ALL_BREAKPOINTS_SAFE, disp_del_at_next_stop, breakpoint::disposition, thread_info::num, breakpoint::number, printf_filtered(), breakpoint::thread, and user_breakpoint_p().
static int remove_watchpoint (struct bp_location * bl) [static]
Definition at line 10469 of file breakpoint.c.
References bp_location::address, watchpoint::cond_exp, watchpoint::exact, bp_location::length, bp_location::owner, target_remove_watchpoint, and bp_location::watchpoint_type.
Referenced by initialize_breakpoint_ops().
void resolve_sal_pc (struct symtab_and_line * sal)
Definition at line 9816 of file breakpoint.c.
References _, block_linkage_function(), blockvector_for_pc_sect(), do_cleanups(), error(), symtab_and_line::explicit_line, find_line_pc(), fixup_symbol_section(), symtab_and_line::line, lookup_minimal_symbol_by_pc(), bound_minimal_symbol::minsym, bound_minimal_symbol::objfile, symtab::objfile, symtab_and_line::pc, symtab_and_line::pspace, save_current_space_and_thread(), symtab_and_line::section, skip_prologue_sal(), switch_to_program_space_and_thread(), SYMBOL_OBJ_SECTION, symtab_and_line::symtab, and symtab_to_filename_for_display().
Referenced by addr_string_to_sals(), breakpoint_sals_to_pc(), gdb_get_function_command(), gdb_get_vars_command(), gdb_loc(), jump_command(), scope_info(), tracepoint_exists(), and until_break_command().
static int resources_needed_masked_watchpoint (const struct bp_location * bl) [static]
Definition at line 10735 of file breakpoint.c.
References bp_location::address, watchpoint::hw_wp_mask, bp_location::owner, and target_masked_watch_num_registers().
Referenced by initialize_breakpoint_ops().
static int resources_needed_ranged_breakpoint (const struct bp_location * bl) [static]
Definition at line 10015 of file breakpoint.c.
References target_ranged_break_num_registers().
Referenced by initialize_breakpoint_ops().
static int resources_needed_watchpoint (const struct bp_location * bl) [static]
Definition at line 10511 of file breakpoint.c.
References bp_location::address, watchpoint::exact, bp_location::length, bp_location::owner, and target_region_ok_for_hw_watchpoint.
Referenced by initialize_breakpoint_ops().
static void rwatch_command (char * arg, int from_tty) [static]
Definition at line 11340 of file breakpoint.c.
References hw_read, and watch_maybe_just_location().
void rwatch_command_wrapper (char * arg, int from_tty, int internal)
Definition at line 11334 of file breakpoint.c.
References hw_read, and watch_command_1().
Referenced by bppy_init(), and mi_cmd_break_watch().
static void save_breakpoints (char * filename, int from_tty, int(*)(const struct breakpoint *) filter) [static]
Definition at line 15504 of file breakpoint.c.
References _, ALL_BREAKPOINTS, bp_disabled, bp_dprintf, counted_command_line::commands, breakpoint::commands, breakpoint::cond_string, current_uiout, default_collect, do_cleanups(), breakpoint::enable_state, bp_location::enabled, error(), fprintf_unfiltered(), gdb_fopen(), breakpoint::ignore_count, is_tracepoint(), is_watchpoint(), breakpoint::loc, make_cleanup(), make_cleanup_ui_file_delete(), bp_location::next, breakpoint::ops, print_command_lines(), breakpoint_ops::print_recreate, printf_filtered(), gdb_exception::reason, RETURN_MASK_ALL, safe_strerror(), save_trace_state_variables(), throw_exception(), TRY_CATCH, breakpoint::type, ui_out_redirect(), user_breakpoint_p(), warning(), and xfree().
Referenced by save_breakpoints_command(), and save_tracepoints_command().
static void save_breakpoints_command (char * args, int from_tty) [static]
Definition at line 15624 of file breakpoint.c.
References save_breakpoints().
static void save_command (char * arg, int from_tty) [static]
Definition at line 15719 of file breakpoint.c.
References _, gdb_stdout, help_list(), and printf_unfiltered().
static void save_tracepoints_command (char * args, int from_tty) [static]
Definition at line 15632 of file breakpoint.c.
References is_tracepoint(), and save_breakpoints().
static void say_where (struct breakpoint * b) [static]
Definition at line 12605 of file breakpoint.c.
References _, breakpoint::addr_string, bp_location::address, value_print_options::addressprint, fputs_filtered(), gdb_stdout, bp_location::gdbarch, get_user_print_options(), bp_location::line_number, breakpoint::loc, bp_location::next, paddress(), printf_filtered(), bp_location::symtab, and symtab_to_filename_for_display().
Referenced by bkpt_print_mention(), and tracepoint_print_mention().
static void set_breakpoint_cmd (char * args, int from_tty) [static]
Definition at line 14809 of file breakpoint.c.
void set_breakpoint_condition (struct breakpoint * b, char * exp, int from_tty)
Definition at line 913 of file breakpoint.c.
References _, bp_location::address, block_for_pc(), bp_location::cond, watchpoint::cond_exp, watchpoint::cond_exp_valid_block, breakpoint::cond_string, breakpoint::condition_not_parsed, error(), watchpoint::exp, innermost_block, is_watchpoint(), breakpoint::loc, mark_breakpoint_modified(), bp_location::next, breakpoint::number, observer_notify_breakpoint_modified(), parse_exp_1(), printf_filtered(), and xfree().
Referenced by bppy_set_condition(), condition_command(), and create_ada_exception_catchpoint().
static void set_breakpoint_count (int num) [static]
Definition at line 624 of file breakpoint.c.
References lookup_internalvar(), and set_internalvar_integer().
Referenced by break_range_command(), and set_breakpoint_number().
static void set_breakpoint_location_function (struct bp_location * loc, int explicit_loc) [static]
Definition at line 7043 of file breakpoint.c.
References bp_location::address, adjust_breakpoint_address(), bp_breakpoint, bp_gnu_ifunc_resolver, bp_hardware_breakpoint, current_program_space, find_pc_partial_function_gnu_ifunc(), bp_location::function_name, gdb_assert, bp_location::gdbarch, gnu_ifunc_resolve_name, is_tracepoint(), breakpoint::loc, bp_location::next, bp_location::owner, bp_location::pspace, bp_location::related_address, breakpoint::related_breakpoint, bp_location::requested_address, and breakpoint::type.
Referenced by add_location_to_breakpoint(), and momentary_breakpoint_from_master().
static void set_breakpoint_number (int internal, struct breakpoint * b) [static]
Definition at line 3035 of file breakpoint.c.
References breakpoint::number, and set_breakpoint_count().
Referenced by install_breakpoint().
static void set_condition_evaluation_mode (char * args, int from_tty, struct cmd_list_element * c) [static]
Definition at line 788 of file breakpoint.c.
References _, ALL_BP_LOCATIONS, condition_evaluation_mode, condition_evaluation_mode_1, bp_location::inserted, is_breakpoint(), mark_breakpoint_location_modified(), bp_location::needs_update, bp_location::owner, target_supports_evaluation_of_breakpoint_conditions, translate_condition_evaluation_mode(), update_global_location_list(), and warning().
void set_ignore_count (int bptnum, int count, int from_tty)
Definition at line 14368 of file breakpoint.c.
References _, ALL_BREAKPOINTS, error(), breakpoint::ignore_count, is_tracepoint(), breakpoint::number, observer_notify_breakpoint_modified(), and printf_filtered().
Referenced by bppy_set_ignore_count(), continue_command(), and ignore_command().
void set_longjmp_breakpoint (struct thread_info * tp, struct frame_id frame)
Definition at line 7178 of file breakpoint.c.
References ALL_BREAKPOINTS_SAFE, bp_exception, bp_exception_master, bp_longjmp, bp_longjmp_master, current_program_space, thread_info::initiating_frame, longjmp_breakpoint_ops, momentary_breakpoint_from_master(), thread_info::num, breakpoint::pspace, breakpoint::thread, and breakpoint::type.
Referenced by finish_forward(), step_1(), until_break_command(), and until_next_command().
struct breakpoint* set_longjmp_breakpoint_for_call_dummy (void) [read]
Definition at line 7238 of file breakpoint.c.
References ALL_BREAKPOINTS, bp_longjmp_call_dummy, bp_longjmp_master, current_program_space, gdb_assert, inferior_ptid, momentary_breakpoint_from_master(), momentary_breakpoint_ops, pid_to_thread_id(), breakpoint::pspace, breakpoint::related_breakpoint, breakpoint::thread, and breakpoint::type.
Referenced by call_function_by_hand().
struct breakpoint* set_momentary_breakpoint (struct gdbarch * gdbarch, struct symtab_and_line sal, struct frame_id frame_id , enum bptype type) [read]
Definition at line 8762 of file breakpoint.c.
References bp_enabled, disp_donttouch, breakpoint::disposition, breakpoint::enable_state, breakpoint::frame_id, frame_id_artificial_p(), gdb_assert, in_thread_list(), inferior_ptid, momentary_breakpoint_ops, pid_to_thread_id(), set_raw_breakpoint(), breakpoint::thread, and update_global_location_list_nothrow().
Referenced by arm_linux_copy_svc(), call_function_by_hand(), elf_gnu_ifunc_resolver_stop(), finish_forward(), insert_step_resume_breakpoint_at_sal_1(), set_momentary_breakpoint_at_pc(), and until_break_command().
struct breakpoint* set_momentary_breakpoint_at_pc (struct gdbarch * gdbarch, CORE_ADDR pc, enum bptype type) [read]
Definition at line 8836 of file breakpoint.c.
References find_pc_line(), find_pc_overlay(), null_frame_id, symtab_and_line::pc, and set_momentary_breakpoint().
Referenced by insert_exception_resume_breakpoint(), insert_exception_resume_from_probe(), and insert_longjmp_resume_breakpoint().
struct breakpoint* set_raw_breakpoint (struct gdbarch * gdbarch, struct symtab_and_line sal, enum bptype bptype , const struct breakpoint_ops * ops) [read]
Referenced by break_range_command(), create_internal_breakpoint(), and set_momentary_breakpoint().
static struct breakpoint* set_raw_breakpoint_without_location (struct gdbarch * gdbarch, enum bptype bptype , const struct breakpoint_ops * ops) [static, read]
Referenced by momentary_breakpoint_from_master().
void set_std_terminate_breakpoint (void)
Definition at line 7332 of file breakpoint.c.
References ALL_BREAKPOINTS_SAFE, bp_std_terminate, bp_std_terminate_master, current_program_space, momentary_breakpoint_from_master(), momentary_breakpoint_ops, breakpoint::pspace, and breakpoint::type.
Referenced by call_function_by_hand().
static void set_tracepoint_count (int num) [static]
Definition at line 15087 of file breakpoint.c.
References lookup_internalvar(), and set_internalvar_integer().
Referenced by install_breakpoint().
static int should_be_inserted (struct bp_location * bl) [static]
Definition at line 1995 of file breakpoint.c.
References program_space::breakpoints_not_allowed, disp_del_at_next_stop, breakpoint::disposition, bp_location::duplicate, bp_location::enabled, program_space::executing_startup, bp_location::owner, bp_location::pspace, bp_location::shlib_disabled, and user_breakpoint_p().
Referenced by download_tracepoint_locations(), insert_bp_location(), insert_breakpoint_locations(), unduplicated_should_be_inserted(), and update_global_location_list().
static void show_always_inserted_mode (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 433 of file breakpoint.c.
References _, AUTO_BOOLEAN_AUTO, breakpoints_always_inserted_mode(), and fprintf_filtered().
static void show_automatic_hardware_breakpoints (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 415 of file breakpoint.c.
References _, and fprintf_filtered().
static void show_breakpoint_cmd (char * args, int from_tty) [static]
Definition at line 14814 of file breakpoint.c.
static void show_can_use_hw_watchpoints (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 383 of file breakpoint.c.
References _, and fprintf_filtered().
static void show_condition_evaluation_mode (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 848 of file breakpoint.c.
References _, breakpoint_condition_evaluation_mode(), and fprintf_filtered().
static void show_pending_break_support (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 399 of file breakpoint.c.
References _, and fprintf_filtered().
static int single_step_breakpoint_inserted_here_p (struct address_space * aspace, CORE_ADDR pc) [static]
Definition at line 15004 of file breakpoint.c.
References breakpoint_address_match(), bp_target_info::placed_address, and bp_target_info::placed_address_space.
Referenced by breakpoint_inserted_here_p(), and software_breakpoint_inserted_here_p().
int single_step_breakpoints_inserted (void)
Definition at line 14938 of file breakpoint.c.
Referenced by record_full_resume(), and record_full_wait_1().
int software_breakpoint_inserted_here_p (struct address_space * aspace, CORE_ADDR pc)
Definition at line 3991 of file breakpoint.c.
References bp_location::address, ALL_BP_LOCATIONS, program_space::aspace, bp_loc_software_breakpoint, breakpoint_address_match(), bp_location::inserted, bp_location::loc_type, overlay_debugging, bp_location::pspace, bp_location::section, section_is_mapped(), section_is_overlay(), and single_step_breakpoint_inserted_here_p().
Referenced by adjust_pc_after_break(), and record_full_wait_1().
void start_rbreak_breakpoints (void)
Definition at line 639 of file breakpoint.c.
Referenced by rbreak_command().
static void stop_command (char * arg, int from_tty) [static]
Definition at line 9895 of file breakpoint.c.
References _, and printf_filtered().
static void stopat_command (char * arg, int from_tty) [static]
Definition at line 9936 of file breakpoint.c.
References _, cleanup::arg, break_command_1(), and printf_filtered().
static void stopin_command (char * arg, int from_tty) [static]
Definition at line 9903 of file breakpoint.c.
References _, cleanup::arg, break_command_1(), and printf_filtered().
static void strace_command (char * arg, int from_tty) [static]
Definition at line 15136 of file breakpoint.c.
References bp_static_tracepoint, create_breakpoint(), get_current_arch(), strace_marker_breakpoint_ops, and tracepoint_breakpoint_ops.
static void strace_marker_create_breakpoints_sal (struct gdbarch * gdbarch, struct linespec_result * canonical, char * cond_string, char * extra_string, enum bptype type_wanted, enum bpdisp disposition, int thread, int task, int ignore_count, const struct breakpoint_ops * ops, int from_tty, int enabled, int internal, unsigned flags) [static]
Definition at line 13490 of file breakpoint.c.
References linespec_result::addr_string, tracepoint::base, discard_cleanups(), init_breakpoint_sal(), install_breakpoint(), make_cleanup(), symtabs_and_lines::nelts, linespec_sals::sals, symtabs_and_lines::sals, linespec_result::special_display, tracepoint::static_trace_marker_id_idx, VEC_index, and xfree().
Referenced by initialize_breakpoint_ops().
static void strace_marker_create_sals_from_address (char ** arg, struct linespec_result * canonical, enum bptype type_wanted, char * addr_start, char ** copy_arg) [static]
Definition at line 13473 of file breakpoint.c.
References linespec_result::addr_string, linespec_sals::canonical, decode_static_tracepoint_spec(), linespec_sals::sals, savestring(), and VEC_safe_push.
Referenced by initialize_breakpoint_ops().
static void strace_marker_decode_linespec (struct breakpoint * b, char ** s, struct symtabs_and_lines * sals) [static]
Definition at line 13549 of file breakpoint.c.
References _, decode_static_tracepoint_spec(), error(), symtabs_and_lines::nelts, symtabs_and_lines::sals, tracepoint::static_trace_marker_id, and tracepoint::static_trace_marker_id_idx.
Referenced by initialize_breakpoint_ops().
static int strace_marker_p (struct breakpoint * b) [static]
Definition at line 13567 of file breakpoint.c.
References breakpoint::ops, and strace_marker_breakpoint_ops.
Referenced by addr_string_to_sals(), and init_breakpoint_sal().
static void swap_insertion (struct bp_location * left, struct bp_location * right) [static]
Definition at line 12102 of file breakpoint.c.
References bp_location::duplicate, gdb_assert, bp_location::inserted, is_tracepoint(), bp_location::needs_update, bp_location::owner, and bp_location::target_info.
Referenced by update_global_location_list().
static int syscall_catchpoint_p (struct breakpoint * b) [static]
Definition at line 8441 of file breakpoint.c.
References catch_syscall_breakpoint_ops, and breakpoint::ops.
Referenced by is_syscall_catchpoint_enabled().
void tbreak_command (char * arg, int from_tty)
Definition at line 9877 of file breakpoint.c.
References BP_TEMPFLAG, and break_command_1().
Referenced by go_command(), and run_command_1().
static void tcatch_command (char * arg, int from_tty) [static]
Definition at line 11750 of file breakpoint.c.
References _, and error().
static void thbreak_command (char * arg, int from_tty) [static]
Definition at line 9889 of file breakpoint.c.
References BP_HARDWAREFLAG, BP_TEMPFLAG, and break_command_1().
static void trace_command (char * arg, int from_tty) [static]
Definition at line 15094 of file breakpoint.c.
References bp_tracepoint, create_breakpoint(), get_current_arch(), probe_linespec_to_ops(), tracepoint_breakpoint_ops, and tracepoint_probe_breakpoint_ops.
static void trace_pass_command (char * args, int from_tty) [static]
Definition at line 15359 of file breakpoint.c.
References _, ALL_TRACEPOINTS, error(), get_number_or_range_state::finished, get_tracepoint_by_number(), init_number_or_range(), skip_spaces(), and trace_pass_set_count().
Referenced by create_tracepoint_from_upload().
static void trace_pass_set_count (struct tracepoint * tp, int count, int from_tty) [static]
Definition at line 15343 of file breakpoint.c.
References _, tracepoint::base, breakpoint::number, observer_notify_breakpoint_modified(), tracepoint::pass_count, and printf_filtered().
Referenced by trace_pass_command().
static int tracepoint_breakpoint_hit (const struct bp_location * bl, struct address_space * aspace, CORE_ADDR bp_addr, const struct target_waitstatus * ws) [static]
Definition at line 13253 of file breakpoint.c.
Referenced by initialize_breakpoint_ops().
static void tracepoint_create_breakpoints_sal (struct gdbarch * gdbarch, struct linespec_result * canonical, char * cond_string, char * extra_string, enum bptype type_wanted, enum bpdisp disposition, int thread, int task, int ignore_count, const struct breakpoint_ops * ops, int from_tty, int enabled, int internal, unsigned flags) [static]
Definition at line 13339 of file breakpoint.c.
References create_breakpoints_sal_default().
Referenced by initialize_breakpoint_ops().
static void tracepoint_create_sals_from_address (char ** arg, struct linespec_result * canonical, enum bptype type_wanted, char * addr_start, char ** copy_arg) [static]
Definition at line 13329 of file breakpoint.c.
References create_sals_from_address_default().
Referenced by initialize_breakpoint_ops().
static void tracepoint_decode_linespec (struct breakpoint * b, char ** s, struct symtabs_and_lines * sals) [static]
Definition at line 13360 of file breakpoint.c.
References decode_linespec_default().
Referenced by initialize_breakpoint_ops().
static int tracepoint_locations_match (struct bp_location * loc1, struct bp_location * loc2) [static]
Definition at line 6769 of file breakpoint.c.
References bp_location::address, is_tracepoint(), and bp_location::owner.
Referenced by breakpoint_locations_match().
static void tracepoint_print_mention (struct breakpoint * b) [static]
Definition at line 13279 of file breakpoint.c.
References _, bp_fast_tracepoint, bp_static_tracepoint, bp_tracepoint, current_uiout, internal_error(), breakpoint::number, printf_filtered(), say_where(), breakpoint::type, and ui_out_is_mi_like_p().
Referenced by initialize_breakpoint_ops().
static void tracepoint_print_one_detail (const struct breakpoint * self, struct ui_out * uiout) [static]
Definition at line 13263 of file breakpoint.c.
References bp_static_tracepoint, gdb_assert, tracepoint::static_trace_marker_id, ui_out_field_string(), and ui_out_text().
Referenced by initialize_breakpoint_ops().
static void tracepoint_print_recreate (struct breakpoint * self, struct ui_file * fp) [static]
Definition at line 13307 of file breakpoint.c.
References _, bp_fast_tracepoint, bp_static_tracepoint, bp_tracepoint, fprintf_unfiltered(), internal_error(), tracepoint::pass_count, and print_recreate_thread().
Referenced by initialize_breakpoint_ops().
static void tracepoint_probe_create_sals_from_address (char ** arg, struct linespec_result * canonical, enum bptype type_wanted, char * addr_start, char ** copy_arg) [static]
Definition at line 13372 of file breakpoint.c.
References bkpt_probe_create_sals_from_address().
Referenced by initialize_breakpoint_ops().
static void tracepoint_probe_decode_linespec (struct breakpoint * b, char ** s, struct symtabs_and_lines * sals) [static]
Definition at line 13383 of file breakpoint.c.
References bkpt_probe_decode_linespec().
Referenced by initialize_breakpoint_ops().
static void tracepoint_re_set (struct breakpoint * b) [static]
Definition at line 13247 of file breakpoint.c.
References breakpoint_re_set_default().
Referenced by initialize_breakpoint_ops().
static void tracepoints_info (char * args, int from_tty) [static]
Definition at line 15270 of file breakpoint.c.
References breakpoint_1(), current_uiout, default_collect_info(), is_tracepoint(), and ui_out_message().
static const char* translate_condition_evaluation_mode (const char * mode) [static]
Definition at line 480 of file breakpoint.c.
References condition_evaluation_host, condition_evaluation_target, and target_supports_evaluation_of_breakpoint_conditions.
Referenced by breakpoint_condition_evaluation_mode(), and set_condition_evaluation_mode().
static int unduplicated_should_be_inserted (struct bp_location * bl) [static]
Definition at line 2027 of file breakpoint.c.
References bp_location::duplicate, and should_be_inserted().
Referenced by update_global_location_list().
void until_break_command (char * arg, int from_tty, int anywhere)
Definition at line 11384 of file breakpoint.c.
References _, add_continuation(), bp_until, until_break_command_continuation_args::breakpoint, until_break_command_continuation_args::breakpoint2, clear_proceed_status(), decode_line_1(), DECODE_LINE_FUNFIRSTLINE, delete_longjmp_breakpoint_cleanup(), discard_cleanups(), do_cleanups(), error(), find_pc_line(), frame_id_p(), frame_unwind_caller_arch(), frame_unwind_caller_id(), frame_unwind_caller_pc(), get_frame_arch(), get_last_displayed_line(), get_last_displayed_symtab(), get_selected_frame(), get_stack_frame_id(), inferior_ptid, inferior_thread(), is_running(), last_displayed_sal_is_valid(), make_cleanup(), make_cleanup_delete_breakpoint(), symtabs_and_lines::nelts, null_cleanup(), null_frame_id, thread_info::num, proceed(), resolve_sal_pc(), symtabs_and_lines::sals, set_longjmp_breakpoint(), set_momentary_breakpoint(), target_can_async_p, until_break_command_continuation_args::thread_num, until_break_command_continuation(), xfree(), and xmalloc().
Referenced by advance_command(), and until_command().
static void until_break_command_continuation (void * arg, int err) [static]
Definition at line 11373 of file breakpoint.c.
References until_break_command_continuation_args::breakpoint, until_break_command_continuation_args::breakpoint2, delete_breakpoint(), delete_longjmp_breakpoint(), and until_break_command_continuation_args::thread_num.
Referenced by until_break_command().
void update_breakpoint_locations (struct breakpoint * b, struct symtabs_and_lines sals, struct symtabs_and_lines sals_end)
Definition at line 13976 of file breakpoint.c.
References _, add_location_to_breakpoint(), all_locations_are_pending(), ambiguous_names_p(), block_for_pc(), bp_disabled, bp_permanent, breakpoint_locations_match(), bp_location::cond, breakpoint::cond_string, breakpoint::enable_state, bp_location::enabled, find_breakpoint_range_end(), bp_location::function_name, bp_location::length, breakpoint::loc, locations_are_equal(), make_breakpoint_permanent(), gdb_exception::message, symtabs_and_lines::nelts, bp_location::next, breakpoint::number, observer_notify_breakpoint_modified(), parse_exp_1(), symtab_and_line::pc, printf_unfiltered(), symtab_and_line::pspace, gdb_exception::reason, RETURN_MASK_ERROR, symtabs_and_lines::sals, switch_to_program_space_and_thread(), TRY_CATCH, update_global_location_list(), and warning().
Referenced by breakpoint_re_set_default(), elf_gnu_ifunc_resolver_return_stop(), and re_set_exception_catchpoint().
void update_breakpoints_after_exec (void)
Definition at line 3458 of file breakpoint.c.
References breakpoint::addr_string, ALL_BP_LOCATIONS, ALL_BREAKPOINTS_SAFE, bp_catchpoint, bp_exception, bp_exception_master, bp_exception_resume, bp_finish, bp_hp_step_resume, bp_jit_event, bp_longjmp, bp_longjmp_call_dummy, bp_longjmp_master, bp_longjmp_resume, bp_overlay_event, bp_shlib_event, bp_std_terminate_master, bp_step_resume, bp_thread_event, create_exception_master_breakpoint(), create_longjmp_master_breakpoint(), create_overlay_event_breakpoint(), create_std_terminate_master_breakpoint(), current_program_space, delete_breakpoint(), gdb_assert, bp_location::inserted, bp_location::pspace, breakpoint::pspace, and breakpoint::type.
Referenced by follow_exec().
static void update_dprintf_command_list (struct breakpoint * b) [static]
Definition at line 8951 of file breakpoint.c.
References _, command_line::body_count, command_line::body_list, breakpoint_set_commands(), command_line::control_type, error(), breakpoint::extra_string, gdb_assert, internal_error(), command_line::line, command_line::next, simple_control, skip_spaces(), target_can_run_breakpoint_commands, warning(), xmalloc(), and xstrprintf().
Referenced by dprintf_re_set(), init_breakpoint_sal(), and update_dprintf_commands().
static void update_dprintf_commands (char * args, int from_tty, struct cmd_list_element * c) [static]
Definition at line 9022 of file breakpoint.c.
References ALL_BREAKPOINTS, bp_dprintf, breakpoint::type, and update_dprintf_command_list().
static void update_global_location_list (int should_insert) [static]
Definition at line 12194 of file breakpoint.c.
References _, bp_location::address, ALL_BP_LOCATIONS, ALL_BREAKPOINTS, bp_access_watchpoint, bp_hardware_watchpoint, bp_location, bp_location_compare(), bp_location_count, bp_location_target_extensions_update(), bp_permanent, bp_read_watchpoint, breakpoint_address_is_meaningful(), breakpoint_locations_match(), breakpoints_always_inserted_mode(), bp_location::condition_changed, condition_modified, condition_unchanged, decref_bp_location(), do_cleanups(), download_tracepoint_locations(), bp_location::duplicate, breakpoint::enable_state, bp_location::events_till_retirement, force_breakpoint_reinsertion(), gdb_assert, gdbarch_has_global_breakpoints(), have_live_inferiors(), insert_breakpoint_locations(), bp_location::inserted, internal_error(), is_breakpoint(), is_hardware_watchpoint(), is_tracepoint(), breakpoint::loc, make_cleanup(), mark_uninserted, bp_location::needs_update, bp_location::next, non_stop, program_space::num, breakpoint::number, overlay_debugging, bp_location::owner, printf_filtered(), bp_location::pspace, qsort, remove_breakpoint(), bp_location::section, should_be_inserted(), swap_insertion(), target_gdbarch(), thread_count(), breakpoint::type, unduplicated_should_be_inserted(), update_inserted_breakpoint_locations(), VEC_safe_push, bp_location::watchpoint_type, xfree(), and xmalloc().
Referenced by bpstat_stop_status(), break_range_command(), breakpoint_program_space_exit(), condition_command(), create_breakpoint(), create_exception_master_breakpoint(), create_longjmp_master_breakpoint(), create_overlay_event_breakpoint(), create_std_terminate_master_breakpoint(), delete_breakpoint(), disable_breakpoint(), disable_breakpoints_before_startup(), disable_command(), disable_overlay_breakpoints(), disable_watchpoints_before_interactive_call_start(), enable_breakpoint_disp(), enable_command(), enable_overlay_breakpoints(), enable_watchpoints_after_interactive_call_stop(), insert_breakpoints(), install_breakpoint(), set_condition_evaluation_mode(), update_breakpoint_locations(), and update_global_location_list_nothrow().
static void update_global_location_list_nothrow (int inserting) [static]
Definition at line 12567 of file breakpoint.c.
References RETURN_MASK_ERROR, TRY_CATCH, and update_global_location_list().
Referenced by create_jit_event_breakpoint(), create_solib_event_breakpoint(), create_thread_event_breakpoint(), momentary_breakpoint_from_master(), and set_momentary_breakpoint().
static void update_inserted_breakpoint_locations (void) [static]
Definition at line 2755 of file breakpoint.c.
References ALL_BP_LOCATIONS, do_cleanups(), error_stream(), fprintf_unfiltered(), gdbarch_has_global_breakpoints(), inferior_ptid, insert_bp_location(), bp_location::inserted, is_breakpoint(), make_cleanup_ui_file_delete(), mem_fileopen(), bp_location::needs_update, null_ptid, bp_location::owner, bp_location::pspace, ptid_equal(), save_current_space_and_thread(), switch_to_program_space_and_thread(), target_gdbarch(), and target_terminal_ours_for_output.
Referenced by update_global_location_list().
static struct symtab_and_line update_static_tracepoint (struct breakpoint * b, struct symtab_and_line sal) [static, read]
Definition at line 13848 of file breakpoint.c.
References _, static_tracepoint_marker::address, current_uiout, find_line_pc(), find_pc_line(), find_pc_sect_function(), init_sal(), symtab_and_line::line, symtab_and_line::pc, release_static_tracepoint_marker(), static_tracepoint_marker::str_id, SYMBOL_PRINT_NAME, symtab_and_line::symtab, symtab_to_filename_for_display(), symtab_to_fullname(), target_static_tracepoint_marker_at, target_static_tracepoint_markers_by_strid, ui_out_field_int(), ui_out_field_string(), ui_out_is_mi_like_p(), ui_out_text(), VEC, VEC_empty, VEC_index, warning(), xfree(), and xstrprintf().
Referenced by addr_string_to_sals().
static void update_watchpoint (struct watchpoint * b, int reparse) [static]
Definition at line 1707 of file breakpoint.c.
References _, bp_location::address, allocate_bp_location(), watchpoint::base, bp_access_watchpoint, bp_hardware_watchpoint, bp_loc_hardware_watchpoint, bp_loc_other, bp_read_watchpoint, bp_watchpoint, can_use_hardware_watchpoint(), check_typedef(), watchpoint::cond_exp, watchpoint::cond_exp_valid_block, breakpoint::cond_string, disp_del_at_next_stop, breakpoint::disposition, error(), watchpoint::exact, watchpoint::exp, watchpoint::exp_string, watchpoint::exp_string_reparse, watchpoint::exp_valid_block, fetch_subexp_value(), frame_find_by_id(), bp_location::gdbarch, gdbarch_in_function_epilogue_p(), get_current_frame(), get_frame_arch(), get_frame_id(), get_frame_pc(), get_frame_program_space(), get_selected_frame(), get_type_arch(), hw_access, hw_read, hw_watchpoint_use_count(), hw_watchpoint_used_count_others(), hw_write, is_masked_watchpoint(), bp_location::length, breakpoint::loc, bp_location::loc_type, lval_memory, bp_location::next, value::next, breakpoint::number, breakpoint::ops, parse_exp_1(), printf_filtered(), bp_location::pspace, select_frame(), target_can_use_hardware_watchpoint, target_has_execution, type, breakpoint::type, TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_STRUCT, TYPE_LENGTH, watchpoint::val, watchpoint::val_valid, value_address(), value_free(), value_lazy(), VALUE_LVAL, value_next(), value_type(), watchpoint_del_at_next_stop(), watchpoint::watchpoint_frame, watchpoint_in_thread_scope(), bp_location::watchpoint_type, breakpoint_ops::works_in_software_mode, and xfree().
Referenced by bpstat_stop_status(), enable_breakpoint_disp(), insert_breakpoints(), re_set_watchpoint(), and watch_command_1().
int user_breakpoint_p (struct breakpoint * b)
Definition at line 6370 of file breakpoint.c.
References breakpoint::number.
Referenced by breakpoint_1(), delete_command(), delete_trace_command(), describe_other_breakpoints(), disable_command(), enable_command(), remove_threaded_breakpoints(), save_breakpoints(), and should_be_inserted().
static void validate_commands_for_breakpoint (struct breakpoint * b, struct command_line * commands) [static]
Definition at line 1122 of file breakpoint.c.
References _, command_line::body_count, command_line::body_list, bp_fast_tracepoint, bp_static_tracepoint, check_no_tracepoint_commands(), command_line::control_type, error(), gdb_assert, is_tracepoint(), command_line::line, command_line::next, tracepoint::step_count, breakpoint::type, validate_actionline(), and while_stepping_control.
Referenced by breakpoint_set_commands(), and do_map_commands_command().
VEC (bp_location_p)
Definition at line 594 of file breakpoint.c.
References bp_enabled, breakpoint::enable_state, and save_cmdlist.
static VEC (char_ptr) [static]
Definition at line 988 of file breakpoint.c.
References ALL_BREAKPOINTS, len, breakpoint::number, skip_spaces_const(), skip_to_space_const(), VEC, VEC_safe_push, and xsnprintf().
VEC (breakpoint_p)
Definition at line 1188 of file breakpoint.c.
References bp_location::address, ALL_BREAKPOINTS, bp_static_tracepoint, breakpoint::loc, bp_location::next, breakpoint::type, VEC, and VEC_safe_push.
static VEC (int) [static]
Definition at line 11655 of file breakpoint.c.
References _, discard_cleanups(), error(), get_syscall_by_name(), get_syscall_by_number(), int, make_cleanup(), syscall::number, skip_spaces(), UNKNOWN_SYSCALL, VEC, VEC_cleanup, and VEC_safe_push.
static void watch_command (char * arg, int from_tty) [static]
Definition at line 11328 of file breakpoint.c.
References hw_write, and watch_maybe_just_location().
static void watch_command_1 (const char * arg, int accessflag, int from_tty, int just_location, int internal) [static]
Definition at line 10899 of file breakpoint.c.
References _, bp_location::address, adjust_breakpoint_address(), cleanup::arg, watchpoint::base, block_innermost_frame(), bp_access_watchpoint, bp_enabled, bp_hardware_watchpoint, bp_read_watchpoint, bp_watchpoint_scope, check_typedef(), watchpoint::cond_exp_valid_block, breakpoint::cond_string, core_addr_to_string(), create_internal_breakpoint(), current_program_space, delete_breakpoint(), disp_del, disp_donttouch, breakpoint::disposition, do_cleanups(), breakpoint::enable_state, error(), watchpoint::exp, watchpoint::exp_string, watchpoint::exp_string_reparse, watchpoint::exp_valid_block, fetch_subexp_value(), breakpoint::frame_id, frame_id_p(), frame_unwind_caller_arch(), frame_unwind_caller_id(), frame_unwind_caller_pc(), bp_location::gdbarch, get_frame_id(), hw_access, hw_read, watchpoint::hw_wp_mask, inferior_ptid, init_raw_breakpoint_without_location(), innermost_block, install_breakpoint(), invalid_thread_id_error(), breakpoint::language, language_c, len, breakpoint::loc, make_cleanup(), masked_watchpoint_breakpoint_ops, momentary_breakpoint_ops, name, null_frame_id, null_ptid, parse_exp_1(), parse_to_comma_and_eval(), breakpoint::pspace, gdb_exception::reason, breakpoint::related_breakpoint, release_value(), bp_location::requested_address, RETURN_MASK_ALL, savestring(), skip_spaces_const(), skip_to_space_const(), target_masked_watch_num_registers(), breakpoint::thread, throw_exception(), TRY_CATCH, breakpoint::type, TYPE_TARGET_TYPE, type_to_string(), update_watchpoint(), watchpoint::val, watchpoint::val_valid, valid_thread_id(), value_addr(), value_as_address(), value_free_to_mark(), value_mark(), value_type(), watchpoint_breakpoint_ops, watchpoint_exp_is_const(), watchpoint::watchpoint_frame, watchpoint::watchpoint_thread, xfree(), and xstrprintf().
Referenced by awatch_command_wrapper(), rwatch_command_wrapper(), watch_command_wrapper(), and watch_maybe_just_location().
void watch_command_wrapper (char * arg, int from_tty, int internal)
Definition at line 11303 of file breakpoint.c.
References hw_write, and watch_command_1().
Referenced by bppy_init(), and mi_cmd_break_watch().
static void watch_maybe_just_location (char * arg, int accessflag, int from_tty) [static]
Definition at line 11312 of file breakpoint.c.
References check_for_argument(), skip_spaces(), and watch_command_1().
Referenced by awatch_command(), rwatch_command(), and watch_command().
static int watchpoint_check (void * p) [static]
Definition at line 4772 of file breakpoint.c.
References async_reason_lookup(), watchpoint::base, bpstats::breakpoint_at, breakpoint::commands, contained_in(), current_uiout, decref_counted_command_line(), EXEC_ASYNC_WATCHPOINT_SCOPE, watchpoint::exp, watchpoint::exp_valid_block, fetch_subexp_value(), frame_find_by_id(), gdb_assert, gdbarch_in_function_epilogue_p(), get_current_frame(), get_frame_arch(), get_frame_function(), get_frame_pc(), is_masked_watchpoint(), breakpoint::number, bpstats::old_val, release_value(), select_frame(), SYMBOL_BLOCK_VALUE, ui_out_field_int(), ui_out_field_string(), ui_out_is_mi_like_p(), ui_out_text(), watchpoint::val, watchpoint::val_valid, value_equal_contents(), value_free_to_mark(), value_mark(), watchpoint_del_at_next_stop(), watchpoint::watchpoint_frame, watchpoint_in_thread_scope(), WP_DELETED, WP_IGNORE, WP_VALUE_CHANGED, and WP_VALUE_NOT_CHANGED.
Referenced by bpstat_check_watchpoint().
static void watchpoint_del_at_next_stop (struct watchpoint * w) [static]
Definition at line 1639 of file breakpoint.c.
References watchpoint::base, bp_watchpoint_scope, disp_del_at_next_stop, breakpoint::disposition, gdb_assert, breakpoint::related_breakpoint, and breakpoint::type.
Referenced by bpstat_check_watchpoint(), delete_breakpoint(), update_watchpoint(), and watchpoint_check().
static int watchpoint_exp_is_const (const struct expression * exp) [static]
Definition at line 10293 of file breakpoint.c.
References expression::elts, LOC_BLOCK, LOC_CONST, LOC_CONST_BYTES, expression::nelts, exp_element::opcode, operator_length(), exp_element::symbol, and SYMBOL_CLASS.
Referenced by watch_command_1().
static int watchpoint_in_thread_scope (struct watchpoint * b) [static]
Definition at line 1627 of file breakpoint.c.
References watchpoint::base, current_program_space, inferior_ptid, is_executing(), null_ptid, breakpoint::pspace, ptid_equal(), and watchpoint::watchpoint_thread.
Referenced by update_watchpoint(), and watchpoint_check().
static int watchpoint_locations_match (struct bp_location * loc1, struct bp_location * loc2) [static]
Definition at line 6677 of file breakpoint.c.
References bp_location::address, program_space::aspace, watchpoint::cond_exp, gdb_assert, bp_location::length, bp_location::owner, bp_location::pspace, target_can_accel_watchpoint_condition, breakpoint::type, and bp_location::watchpoint_type.
Referenced by breakpoint_locations_match(), and insert_bp_location().
static void watchpoint_value_print (struct value * val, struct ui_file * stream) [static]
Definition at line 4457 of file breakpoint.c.
References _, fprintf_unfiltered(), get_user_print_options(), and value_print().
Referenced by print_it_watchpoint().
static void watchpoints_info (char * args, int from_tty) [static]
Definition at line 6564 of file breakpoint.c.
References breakpoint_1(), current_uiout, is_watchpoint(), and ui_out_message().
int watchpoints_triggered (struct target_waitstatus * ws)
Definition at line 4677 of file breakpoint.c.
References bp_location::address, ALL_BREAKPOINTS, current_target, watchpoint::hw_wp_mask, is_hardware_watchpoint(), is_masked_watchpoint(), bp_location::length, breakpoint::loc, bp_location::next, target_stopped_by_watchpoint, target_stopped_data_address, target_watchpoint_addr_within_range, watch_triggered_no, watch_triggered_unknown, watch_triggered_yes, and watchpoint::watchpoint_triggered.
Referenced by handle_inferior_event().
static int works_in_software_mode_masked_watchpoint (const struct breakpoint * b) [static]
Definition at line 10746 of file breakpoint.c.
Referenced by initialize_breakpoint_ops().
static int works_in_software_mode_watchpoint (const struct breakpoint * b) [static]
Definition at line 10523 of file breakpoint.c.
References bp_hardware_watchpoint, bp_watchpoint, and breakpoint::type.
Referenced by initialize_breakpoint_ops().
static char* wrap_indent_at_field (struct ui_out * uiout, const char * col_name) [static]
Definition at line 5653 of file breakpoint.c.
References gdb_assert, memset(), ui_out_query_field(), and wrap_indent.
Referenced by print_breakpoint_location().
Variable Documentation
enum auto_boolean always_inserted_mode = AUTO_BOOLEAN_AUTO [static]
Definition at line 430 of file breakpoint.c.
int automatic_hardware_breakpoints [static]
Definition at line 413 of file breakpoint.c.
struct breakpoint_ops base_breakpoint_ops
Initial value:
{
  base_breakpoint_dtor,
  base_breakpoint_allocate_location,
  base_breakpoint_re_set,
  base_breakpoint_insert_location,
  base_breakpoint_remove_location,
  base_breakpoint_breakpoint_hit,
  base_breakpoint_check_status,
  base_breakpoint_resources_needed,
  base_breakpoint_works_in_software_mode,
  base_breakpoint_print_it,
  NULL,
  base_breakpoint_print_one_detail,
  base_breakpoint_print_mention,
  base_breakpoint_print_recreate,
  base_breakpoint_create_sals_from_address,
  base_breakpoint_create_breakpoints_sal,
  base_breakpoint_decode_linespec,
  base_breakpoint_explains_signal,
  base_breakpoint_after_condition_true,
}
Definition at line 279 of file breakpoint.c.
Referenced by dtor_catch_exec(), dtor_catch_solib(), dtor_catch_syscall(), dtor_watchpoint(), initialize_breakpoint_ops(), initialize_signal_catchpoint_ops(), and signal_catchpoint_dtor().
struct breakpoint_ops bkpt_base_breakpoint_ops [static]
Definition at line 284 of file breakpoint.c.
Referenced by initialize_breakpoint_ops().
struct breakpoint_ops bkpt_breakpoint_ops
Definition at line 297 of file breakpoint.c.
Referenced by bpfinishpy_init(), bppy_init(), break_command_1(), check_status_exception_catchpoint(), dtor_exception(), dtor_exception_catchpoint(), gdb_set_bp(), initialize_ada_catchpoint_ops(), initialize_breakpoint_ops(), initialize_throw_catchpoint_ops(), mi_cmd_break_insert_1(), re_set_exception(), and spu_catch_start().
struct breakpoint_ops bkpt_probe_breakpoint_ops [static]
Definition at line 300 of file breakpoint.c.
Referenced by break_command_1(), and initialize_breakpoint_ops().
struct bp_location** bp_location [static]
Definition at line 569 of file breakpoint.c.
Referenced by update_global_location_list().
unsigned bp_location_count [static]
Definition at line 573 of file breakpoint.c.
Referenced by breakpoint_xfer_memory(), and update_global_location_list().
struct bp_location_ops bp_location_ops [static]
Initial value:
{
  bp_location_dtor
}
Definition at line 12662 of file breakpoint.c.
CORE_ADDR bp_location_placed_address_before_address_max [static]
Definition at line 581 of file breakpoint.c.
CORE_ADDR bp_location_shadow_len_after_address_max [static]
Definition at line 589 of file breakpoint.c.
struct breakpoint* breakpoint_chain
Definition at line 565 of file breakpoint.c.
Referenced by add_to_breakpoint_chain(), and tui_update_breakpoint_info().
struct objfile_data* breakpoint_objfile_key [static]
Definition at line 3101 of file breakpoint.c.
int breakpoint_proceeded [static]
Definition at line 364 of file breakpoint.c.
int can_use_hw_watchpoints [static]
Definition at line 380 of file breakpoint.c.
struct cmd_list_element* catch_cmdlist [static]
Definition at line 15679 of file breakpoint.c.
struct breakpoint_ops catch_exec_breakpoint_ops [static]
Definition at line 8624 of file breakpoint.c.
Referenced by catch_exec_command_1(), and initialize_breakpoint_ops().
struct breakpoint_ops catch_fork_breakpoint_ops [static]
Definition at line 7659 of file breakpoint.c.
Referenced by catch_fork_command_1(), and initialize_breakpoint_ops().
struct breakpoint_ops catch_solib_breakpoint_ops [static]
Definition at line 7978 of file breakpoint.c.
Referenced by add_solib_catchpoint(), and initialize_breakpoint_ops().
struct breakpoint_ops catch_syscall_breakpoint_ops [static]
Definition at line 8436 of file breakpoint.c.
Referenced by catch_syscall_command_1(), initialize_breakpoint_ops(), and syscall_catchpoint_p().
struct inferior_data* catch_syscall_inferior_data = NULL [static]
Definition at line 8086 of file breakpoint.c.
struct breakpoint_ops catch_vfork_breakpoint_ops [static]
Definition at line 7775 of file breakpoint.c.
Referenced by catch_fork_command_1(), and initialize_breakpoint_ops().
const char condition_evaluation_auto[] = "auto" [static]
Definition at line 457 of file breakpoint.c.
const char condition_evaluation_both[] = "host or target" [static]
Definition at line 454 of file breakpoint.c.
Referenced by bp_condition_evaluator().
const char* const condition_evaluation_enums[] [static]
Initial value:
 {
  condition_evaluation_auto,
  condition_evaluation_host,
  condition_evaluation_target,
  NULL
}
Definition at line 460 of file breakpoint.c.
const char condition_evaluation_host[] = "host" [static]
Definition at line 458 of file breakpoint.c.
Referenced by bp_condition_evaluator(), bp_location_condition_evaluator(), and translate_condition_evaluation_mode().
const char* condition_evaluation_mode = condition_evaluation_auto [static]
Definition at line 472 of file breakpoint.c.
Referenced by set_condition_evaluation_mode().
const char* condition_evaluation_mode_1 = condition_evaluation_auto [static]
Definition at line 468 of file breakpoint.c.
Referenced by set_condition_evaluation_mode().
const char condition_evaluation_target[] = "target" [static]
Definition at line 459 of file breakpoint.c.
Referenced by bp_condition_evaluator(), bp_location_condition_evaluator(), and translate_condition_evaluation_mode().
int disconnected_dprintf = 1 [static]
Definition at line 342 of file breakpoint.c.
struct breakpoint_ops dprintf_breakpoint_ops
Definition at line 303 of file breakpoint.c.
Referenced by dprintf_command(), initialize_breakpoint_ops(), and mi_cmd_break_insert_1().
char* dprintf_channel = "" [static]
Definition at line 338 of file breakpoint.c.
char* dprintf_function = "" [static]
Definition at line 328 of file breakpoint.c.
const char* dprintf_style = dprintf_style_gdb [static]
Definition at line 321 of file breakpoint.c.
const char dprintf_style_agent[] = "agent" [static]
Definition at line 314 of file breakpoint.c.
const char dprintf_style_call[] = "call" [static]
Definition at line 313 of file breakpoint.c.
const char* const dprintf_style_enums[] [static]
Initial value:
 {
  dprintf_style_gdb,
  dprintf_style_call,
  dprintf_style_agent,
  NULL
}
Definition at line 315 of file breakpoint.c.
const char dprintf_style_gdb[] = "gdb" [static]
Definition at line 312 of file breakpoint.c.
struct cmd_list_element* enablebreaklist = NULL [static]
Definition at line 15990 of file breakpoint.c.
int executing_breakpoint_commands [static]
Definition at line 515 of file breakpoint.c.
int internal_breakpoint_number = -1 [static]
Definition at line 3026 of file breakpoint.c.
struct breakpoint_ops internal_breakpoint_ops [static]
Definition at line 287 of file breakpoint.c.
Referenced by create_exception_master_breakpoint(), create_jit_event_breakpoint(), create_longjmp_master_breakpoint(), create_overlay_event_breakpoint(), create_solib_event_breakpoint(), create_std_terminate_master_breakpoint(), create_thread_event_breakpoint(), and initialize_breakpoint_ops().
struct breakpoint_ops longjmp_breakpoint_ops [static]
Definition at line 293 of file breakpoint.c.
Referenced by initialize_breakpoint_ops(), and set_longjmp_breakpoint().
const char* const longjmp_names[] [static]
Initial value:
  {
    "longjmp", "_longjmp", "siglongjmp", "_siglongjmp"
  }
Definition at line 3067 of file breakpoint.c.
struct breakpoint_ops masked_watchpoint_breakpoint_ops [static]
Definition at line 10885 of file breakpoint.c.
Referenced by initialize_breakpoint_ops(), is_masked_watchpoint(), and watch_command_1().
struct breakpoint_ops momentary_breakpoint_ops [static]
Definition at line 290 of file breakpoint.c.
Referenced by initialize_breakpoint_ops(), longjmp_bkpt_dtor(), set_longjmp_breakpoint_for_call_dummy(), set_momentary_breakpoint(), set_std_terminate_breakpoint(), and watch_command_1().
struct minimal_symbol msym_not_found [static]
Definition at line 3104 of file breakpoint.c.
Referenced by create_exception_master_breakpoint(), create_longjmp_master_breakpoint(), create_overlay_event_breakpoint(), create_std_terminate_master_breakpoint(), and msym_not_found_p().
int next_cmd [static]
Definition at line 15164 of file breakpoint.c.
int overlay_events_enabled [static]
Definition at line 518 of file breakpoint.c.
enum auto_boolean pending_break_support [static]
Definition at line 397 of file breakpoint.c.
struct breakpoint_ops ranged_breakpoint_ops [static]
Definition at line 10137 of file breakpoint.c.
Referenced by break_range_command(), and initialize_breakpoint_ops().
int rbreak_start_breakpoint_count [static]
Definition at line 633 of file breakpoint.c.
Referenced by end_rbreak_breakpoints().
void* single_step_breakpoints[2] [static]
Definition at line 14897 of file breakpoint.c.
struct gdbarch* single_step_gdbarch[2] [static]
Definition at line 14898 of file breakpoint.c.
struct breakpoint_ops strace_marker_breakpoint_ops [static]
Definition at line 13564 of file breakpoint.c.
Referenced by initialize_breakpoint_ops(), strace_command(), and strace_marker_p().
int target_exact_watchpoints = 0
Definition at line 521 of file breakpoint.c.
Referenced by _initialize_rs6000_tdep().
struct cmd_list_element* tcatch_cmdlist [static]
Definition at line 15682 of file breakpoint.c.
struct uploaded_tp* this_utp [static]
Definition at line 15163 of file breakpoint.c.
struct breakpoint_ops tracepoint_breakpoint_ops
Definition at line 13366 of file breakpoint.c.
Referenced by create_tracepoint_from_upload(), ftrace_command(), initialize_breakpoint_ops(), mi_cmd_break_insert_1(), strace_command(), and trace_command().
struct breakpoint_ops tracepoint_probe_breakpoint_ops [static]
Definition at line 13390 of file breakpoint.c.
Referenced by initialize_breakpoint_ops(), and trace_command().
struct breakpoint_ops watchpoint_breakpoint_ops [static]
Definition at line 10705 of file breakpoint.c.
Referenced by initialize_breakpoint_ops(), and watch_command_1().