GDB (xrefs): /home/stan/gdb/src/gdb/breakpoint.h File Reference
/home/stan/gdb/src/gdb/breakpoint.h File Reference
#include "frame.h"
#include "value.h"
#include "vec.h"
#include "ax.h"
#include "command.h"
#include "break-common.h"
Classes
struct bp_target_info
struct bp_location_ops
struct bp_location
struct breakpoint_ops
struct breakpoint
struct watchpoint
struct tracepoint
struct bpstat_what
struct bpstats
Defines
#define BREAKPOINT_MAX 16
#define CATCH_PERMANENT ((void *) (uintptr_t) 0)
#define CATCH_TEMPORARY ((void *) (uintptr_t) 1)
Typedefs
typedef struct bp_location * bp_location_p
typedef struct breakpoint * breakpoint_p
typedef struct bpstats * bpstat
typedef void(* walk_bp_location_callback)(struct bp_location *, void *)
Enumerations
enum bptype {
bp_none = 0, bp_breakpoint, bp_hardware_breakpoint, bp_until,
bp_finish, bp_watchpoint, bp_hardware_watchpoint, bp_read_watchpoint,
bp_access_watchpoint, bp_longjmp, bp_longjmp_resume, bp_longjmp_call_dummy,
bp_exception, bp_exception_resume, bp_step_resume, bp_hp_step_resume,
bp_watchpoint_scope, bp_call_dummy, bp_std_terminate, bp_shlib_event,
bp_thread_event, bp_overlay_event, bp_longjmp_master, bp_std_terminate_master,
bp_exception_master, bp_catchpoint, bp_tracepoint, bp_fast_tracepoint,
bp_static_tracepoint, bp_dprintf, bp_jit_event, bp_gnu_ifunc_resolver,
bp_gnu_ifunc_resolver_return
}
enum enable_state { bp_disabled, bp_enabled, bp_call_disabled, bp_permanent }
enum bpdisp { disp_del, disp_del_at_next_stop, disp_disable, disp_donttouch }
enum condition_status { condition_unchanged = 0, condition_modified, condition_updated }
enum bp_loc_type { bp_loc_software_breakpoint, bp_loc_hardware_breakpoint, bp_loc_hardware_watchpoint, bp_loc_other }
enum bpstat_signal_value { BPSTAT_SIGNAL_NO = 0, BPSTAT_SIGNAL_HIDE, BPSTAT_SIGNAL_PASS }
enum watchpoint_triggered { watch_triggered_no = 0, watch_triggered_unknown, watch_triggered_yes }
enum bpstat_what_main_action {
BPSTAT_WHAT_KEEP_CHECKING, BPSTAT_WHAT_SINGLE, BPSTAT_WHAT_SET_LONGJMP_RESUME, BPSTAT_WHAT_CLEAR_LONGJMP_RESUME,
BPSTAT_WHAT_STEP_RESUME, BPSTAT_WHAT_STOP_SILENT, BPSTAT_WHAT_STOP_NOISY, BPSTAT_WHAT_HP_STEP_RESUME
}
enum stop_stack_kind { STOP_NONE = 0, STOP_STACK_DUMMY, STOP_STD_TERMINATE }
enum print_stop_action { PRINT_UNKNOWN = -1, PRINT_SRC_AND_LOC, PRINT_SRC_ONLY, PRINT_NOTHING }
enum bp_print_how { print_it_normal, print_it_noop, print_it_done }
enum inf_context { inf_starting, inf_running, inf_exited, inf_execd }
enum breakpoint_here { no_breakpoint_here = 0, ordinary_breakpoint_here, permanent_breakpoint_here }
enum breakpoint_create_flags { CREATE_BREAKPOINT_FLAGS_INSERTED = 1 << 0 }
Functions
void print_recreate_thread (struct breakpoint *b, struct ui_file *fp)
DEF_VEC_P (bp_location_p)
int is_breakpoint (const struct breakpoint *bpt)
int is_watchpoint (const struct breakpoint *bpt)
DEF_VEC_P (breakpoint_p)
void bpstat_clear (bpstat *)
bpstat bpstat_copy (bpstat)
bpstat bpstat_stop_status (struct address_space *aspace, CORE_ADDR pc, ptid_t ptid, const struct target_waitstatus *ws)
struct bpstat_what bpstat_what (bpstat)
bpstat bpstat_find_breakpoint (bpstat, struct breakpoint *)
enum bpstat_signal_value bpstat_explains_signal (bpstat, enum gdb_signal)
int bpstat_causes_stop (bpstat)
int bpstat_should_step (void)
enum print_stop_action bpstat_print (bpstat, int)
int bpstat_num (bpstat *, int *)
void bpstat_do_actions (void)
void bpstat_clear_actions (void)
enum breakpoint_here breakpoint_here_p (struct address_space *, CORE_ADDR)
int moribund_breakpoint_here_p (struct address_space *, CORE_ADDR)
int breakpoint_inserted_here_p (struct address_space *, CORE_ADDR)
int regular_breakpoint_inserted_here_p (struct address_space *, CORE_ADDR)
int software_breakpoint_inserted_here_p (struct address_space *, CORE_ADDR)
int hardware_watchpoint_inserted_in_range (struct address_space *, CORE_ADDR addr, ULONGEST len)
int breakpoint_thread_match (struct address_space *, CORE_ADDR, ptid_t)
void until_break_command (char *, int, int)
void init_bp_location (struct bp_location *loc, const struct bp_location_ops *ops, struct breakpoint *owner)
void update_breakpoint_locations (struct breakpoint *b, struct symtabs_and_lines sals, struct symtabs_and_lines sals_end)
void breakpoint_re_set (void)
void breakpoint_re_set_thread (struct breakpoint *)
struct breakpoint * set_momentary_breakpoint (struct gdbarch *, struct symtab_and_line, struct frame_id, enum bptype)
struct breakpoint * set_momentary_breakpoint_at_pc (struct gdbarch *, CORE_ADDR pc, enum bptype type)
struct breakpoint * clone_momentary_breakpoint (struct breakpoint *bpkt)
void set_ignore_count (int, int, int)
void breakpoint_init_inferior (enum inf_context)
struct cleanup * make_cleanup_delete_breakpoint (struct breakpoint *)
void delete_breakpoint (struct breakpoint *)
void breakpoint_auto_delete (bpstat)
void iterate_over_bp_locations (walk_bp_location_callback)
struct command_line * breakpoint_commands (struct breakpoint *b)
const char * bpdisp_text (enum bpdisp disp)
void break_command (char *, int)
void hbreak_command_wrapper (char *, int)
void thbreak_command_wrapper (char *, int)
void rbreak_command_wrapper (char *, int)
void watch_command_wrapper (char *, int, int)
void awatch_command_wrapper (char *, int, int)
void rwatch_command_wrapper (char *, int, int)
void tbreak_command (char *, int)
void initialize_breakpoint_ops (void)
void add_catch_command (char *name, char *docstring, void(*sfunc)(char *args, int from_tty, struct cmd_list_element *command), completer_ftype *completer, void *user_data_catch, void *user_data_tcatch)
void init_ada_exception_breakpoint (struct breakpoint *b, struct gdbarch *gdbarch, struct symtab_and_line sal, char *addr_string, const struct breakpoint_ops *ops, int tempflag, int enabled, int from_tty)
void init_catchpoint (struct breakpoint *b, struct gdbarch *gdbarch, int tempflag, char *cond_string, const struct breakpoint_ops *ops)
void install_breakpoint (int internal, struct breakpoint *b, int update_gll)
int create_breakpoint (struct gdbarch *gdbarch, char *arg, char *cond_string, int thread, char *extra_string, int parse_arg, int tempflag, enum bptype wanted_type, int ignore_count, enum auto_boolean pending_break_support, const struct breakpoint_ops *ops, int from_tty, int enabled, int internal, unsigned flags)
void insert_breakpoints (void)
int remove_breakpoints (void)
int remove_breakpoints_pid (int pid)
int reattach_breakpoints (int)
void update_breakpoints_after_exec (void)
int detach_breakpoints (ptid_t ptid)
void breakpoint_program_space_exit (struct program_space *pspace)
void set_longjmp_breakpoint (struct thread_info *tp, struct frame_id frame)
void delete_longjmp_breakpoint (int thread)
void delete_longjmp_breakpoint_at_next_stop (int thread)
struct breakpoint * set_longjmp_breakpoint_for_call_dummy (void)
void check_longjmp_breakpoint_for_call_dummy (int thread)
void enable_overlay_breakpoints (void)
void disable_overlay_breakpoints (void)
void set_std_terminate_breakpoint (void)
void delete_std_terminate_breakpoint (void)
void disable_watchpoints_before_interactive_call_start (void)
void enable_watchpoints_after_interactive_call_stop (void)
void disable_breakpoints_before_startup (void)
void enable_breakpoints_after_startup (void)
enum command_control_type commands_from_control_command (char *arg, struct command_line *cmd)
void clear_breakpoint_hit_counts (void)
struct breakpoint * get_breakpoint (int num)
void disable_current_display (void)
void do_displays (void)
void disable_display (int)
void clear_displays (void)
void disable_breakpoint (struct breakpoint *)
void enable_breakpoint (struct breakpoint *)
void breakpoint_set_commands (struct breakpoint *b, struct command_line *commands)
void breakpoint_set_silent (struct breakpoint *b, int silent)
void breakpoint_set_thread (struct breakpoint *b, int thread)
void breakpoint_set_task (struct breakpoint *b, int task)
void mark_breakpoints_out (void)
void make_breakpoint_permanent (struct breakpoint *)
struct breakpoint * create_jit_event_breakpoint (struct gdbarch *, CORE_ADDR)
struct breakpoint * create_solib_event_breakpoint (struct gdbarch *, CORE_ADDR)
struct breakpoint * create_thread_event_breakpoint (struct gdbarch *, CORE_ADDR)
void remove_jit_event_breakpoints (void)
void remove_solib_event_breakpoints (void)
void remove_thread_event_breakpoints (void)
void disable_breakpoints_in_shlibs (void)
int is_catchpoint (struct breakpoint *)
void add_solib_catchpoint (char *arg, int is_load, int is_temp, int enabled)
void delete_command (char *arg, int from_tty)
void insert_single_step_breakpoint (struct gdbarch *, struct address_space *, CORE_ADDR)
int single_step_breakpoints_inserted (void)
void remove_single_step_breakpoints (void)
void cancel_single_step_breakpoints (void)
void * deprecated_insert_raw_breakpoint (struct gdbarch *, struct address_space *, CORE_ADDR)
int deprecated_remove_raw_breakpoint (struct gdbarch *, void *)
int watchpoints_triggered (struct target_waitstatus *)
void breakpoint_xfer_memory (gdb_byte *readbuf, gdb_byte *writebuf, const gdb_byte *writebuf_org, ULONGEST memaddr, LONGEST len)
int breakpoints_always_inserted_mode (void)
void breakpoint_retire_moribund (void)
void set_breakpoint_condition (struct breakpoint *b, char *exp, int from_tty)
int catch_syscall_enabled (void)
int catching_syscall_number (int syscall_number)
struct tracepoint * get_tracepoint (int num)
struct tracepoint * get_tracepoint_by_number_on_target (int num)
struct tracepoint * get_tracepoint_by_number (char **arg, struct get_number_or_range_state *state, int optional_p)
VEC (breakpoint_p)*all_tracepoints(void)
int is_tracepoint (const struct breakpoint *b)
void check_tracepoint_command (char *line, void *closure)
void start_rbreak_breakpoints (void)
void end_rbreak_breakpoints (void)
struct breakpoint * iterate_over_breakpoints (int(*)(struct breakpoint *, void *), void *)
int pc_at_non_inline_function (struct address_space *aspace, CORE_ADDR pc, const struct target_waitstatus *ws)
int user_breakpoint_p (struct breakpoint *)
struct gdbarch * get_sal_arch (struct symtab_and_line sal)
void breakpoint_free_objfile (struct objfile *objfile)
char * ep_parse_optional_if_clause (char **arg)
Variables
int target_exact_watchpoints
struct breakpoint_ops base_breakpoint_ops
struct breakpoint_ops bkpt_breakpoint_ops
struct breakpoint_ops tracepoint_breakpoint_ops
struct breakpoint_ops dprintf_breakpoint_ops
Define Documentation
#define BREAKPOINT_MAX 16
Definition at line 44 of file breakpoint.h.
Referenced by microblaze_linux_memory_remove_breakpoint(), and ppc_linux_memory_remove_breakpoint().
#define CATCH_PERMANENT ((void *) (uintptr_t) 0)
Definition at line 1217 of file breakpoint.h.
Referenced by _initialize_ada_language(), _initialize_break_catch_sig(), and _initialize_break_catch_throw().
#define CATCH_TEMPORARY ((void *) (uintptr_t) 1)
Definition at line 1218 of file breakpoint.h.
Referenced by _initialize_ada_language(), _initialize_break_catch_sig(), _initialize_break_catch_throw(), catch_ada_exception_command(), catch_assert_command(), catch_catch_command(), catch_exec_command_1(), catch_load_or_unload(), catch_rethrow_command(), catch_signal_command(), catch_syscall_command_1(), and catch_throw_command().
Typedef Documentation
typedef struct bp_location* bp_location_p
Definition at line 637 of file breakpoint.h.
typedef struct bpstats* bpstat
Definition at line 870 of file breakpoint.h.
typedef struct breakpoint* breakpoint_p
Definition at line 863 of file breakpoint.h.
typedef void(* walk_bp_location_callback)(struct bp_location *, void *)
Definition at line 1187 of file breakpoint.h.
Enumeration Type Documentation
enum bp_loc_type
Enumerator:
bp_loc_software_breakpoint
bp_loc_hardware_breakpoint
bp_loc_hardware_watchpoint
bp_loc_other
Definition at line 290 of file breakpoint.h.
enum bp_print_how
Enumerator:
print_it_normal
print_it_noop
print_it_done
Definition at line 1049 of file breakpoint.h.
enum bpdisp
Enumerator:
disp_del
disp_del_at_next_stop
disp_disable
disp_donttouch
Definition at line 210 of file breakpoint.h.
enum bpstat_signal_value
Enumerator:
BPSTAT_SIGNAL_NO
BPSTAT_SIGNAL_HIDE
BPSTAT_SIGNAL_PASS
Definition at line 477 of file breakpoint.h.
enum bpstat_what_main_action
Enumerator:
BPSTAT_WHAT_KEEP_CHECKING
BPSTAT_WHAT_SINGLE
BPSTAT_WHAT_SET_LONGJMP_RESUME
BPSTAT_WHAT_CLEAR_LONGJMP_RESUME
BPSTAT_WHAT_STEP_RESUME
BPSTAT_WHAT_STOP_SILENT
BPSTAT_WHAT_STOP_NOISY
BPSTAT_WHAT_HP_STEP_RESUME
Definition at line 900 of file breakpoint.h.
enum bptype
Enumerator:
bp_none
bp_breakpoint
bp_hardware_breakpoint
bp_until
bp_finish
bp_watchpoint
bp_hardware_watchpoint
bp_read_watchpoint
bp_access_watchpoint
bp_longjmp
bp_longjmp_resume
bp_longjmp_call_dummy
bp_exception
bp_exception_resume
bp_step_resume
bp_hp_step_resume
bp_watchpoint_scope
bp_call_dummy
bp_std_terminate
bp_shlib_event
bp_thread_event
bp_overlay_event
bp_longjmp_master
bp_std_terminate_master
bp_exception_master
bp_catchpoint
bp_tracepoint
bp_fast_tracepoint
bp_static_tracepoint
bp_dprintf
bp_jit_event
bp_gnu_ifunc_resolver
bp_gnu_ifunc_resolver_return
Definition at line 55 of file breakpoint.h.
enum breakpoint_create_flags
Enumerator:
CREATE_BREAKPOINT_FLAGS_INSERTED
Definition at line 1261 of file breakpoint.h.
enum breakpoint_here
Enumerator:
no_breakpoint_here
ordinary_breakpoint_here
permanent_breakpoint_here
Definition at line 1121 of file breakpoint.h.
enum condition_status
Enumerator:
condition_unchanged
condition_modified
condition_updated
Definition at line 222 of file breakpoint.h.
enum enable_state
Enumerator:
bp_disabled
bp_enabled
bp_call_disabled
bp_permanent
Definition at line 185 of file breakpoint.h.
enum inf_context
Enumerator:
inf_starting
inf_running
inf_exited
inf_execd
Definition at line 1111 of file breakpoint.h.
enum print_stop_action
Enumerator:
PRINT_UNKNOWN
PRINT_SRC_AND_LOC
PRINT_SRC_ONLY
PRINT_NOTHING
Definition at line 981 of file breakpoint.h.
enum stop_stack_kind
Enumerator:
STOP_NONE
STOP_STACK_DUMMY
STOP_STD_TERMINATE
Definition at line 951 of file breakpoint.h.
enum watchpoint_triggered
Enumerator:
watch_triggered_no
watch_triggered_unknown
watch_triggered_yes
Definition at line 624 of file breakpoint.h.
Function Documentation
void add_catch_command (char * name, char * docstring, void(*)(char *args, int from_tty, struct cmd_list_element *command) sfunc, completer_ftype * completer, void * user_data_catch, void * user_data_tcatch)
Definition at line 15685 of file breakpoint.c.
References add_cmd(), class_breakpoint, set_cmd_context(), set_cmd_sfunc(), and cmd_list_element::sfunc.
Referenced by _initialize_ada_language(), _initialize_break_catch_sig(), and _initialize_break_catch_throw().
void add_solib_catchpoint (char * arg, int is_load, int is_temp, int enabled)
Definition at line 7988 of file breakpoint.c.
References _, solib_catchpoint::base, bp_disabled, bp_enabled, catch_solib_breakpoint_ops, solib_catchpoint::compiled, discard_cleanups(), breakpoint::enable_state, error(), get_current_arch(), get_regcomp_error(), init_catchpoint(), install_breakpoint(), solib_catchpoint::is_load, make_cleanup(), solib_catchpoint::regex, skip_spaces(), and xfree().
Referenced by catch_load_or_unload(), and mi_catch_load_unload().
void awatch_command_wrapper (char * , int , int)
Definition at line 11346 of file breakpoint.c.
References hw_access, and watch_command_1().
Referenced by bppy_init(), and mi_cmd_break_watch().
const char* bpdisp_text (enum bpdisp disp)
Definition at line 367 of file breakpoint.c.
References int.
Referenced by bkpt_print_it(), print_it_catch_exec(), print_it_catch_fork(), print_it_catch_solib(), print_it_catch_syscall(), print_it_catch_vfork(), print_it_exception(), print_it_exception_catchpoint(), print_it_ranged_breakpoint(), and print_one_breakpoint_location().
int bpstat_causes_stop (bpstat)
Definition at line 5637 of file breakpoint.c.
References bpstats::next, and bpstats::stop.
Referenced by bpstat_stop_status(), and handle_inferior_event().
void bpstat_clear (bpstat *)
Definition at line 4139 of file breakpoint.c.
References bpstat_free(), bpstats::next, and p.
Referenced by clear_proceed_status_thread(), clear_thread_inferior_resources(), discard_infcall_control_state(), handle_inferior_event(), and restore_infcall_control_state().
void bpstat_clear_actions (void)
Definition at line 4274 of file breakpoint.c.
References bpstats::commands, thread_info::control, decref_counted_command_line(), find_thread_ptid(), inferior_ptid, bpstats::next, null_ptid, bpstats::old_val, ptid_equal(), thread_control_state::stop_bpstat, and value_free().
Referenced by do_bpstat_clear_actions_cleanup(), and inferior_event_handler().
bpstat bpstat_copy (bpstat)
Definition at line 4160 of file breakpoint.c.
References bpstats::bp_location_at, bpstats::commands, incref_bp_location(), incref_counted_command_line(), memcpy(), bpstats::next, bpstats::old_val, p, release_value(), value_copy(), and xmalloc().
Referenced by save_infcall_control_state().
void bpstat_do_actions (void)
Definition at line 4435 of file breakpoint.c.
References bpstat_do_actions_1(), discard_cleanups(), inferior_ptid, inferior_thread(), is_executing(), is_exited(), make_bpstat_clear_actions_cleanup(), null_ptid, ptid_equal(), and target_has_execution.
Referenced by command_handler(), command_loop(), gdb_cmd(), gdb_immediate_command(), inferior_event_handler(), and mi_execute_command().
enum bpstat_signal_value bpstat_explains_signal (bpstat , enum gdb_signal)
Definition at line 4211 of file breakpoint.c.
References BPSTAT_SIGNAL_HIDE, BPSTAT_SIGNAL_NO, bpstats::breakpoint_at, breakpoint_ops::explains_signal, bpstats::next, and breakpoint::ops.
Referenced by handle_inferior_event(), and handle_syscall_event().
bpstat bpstat_find_breakpoint (bpstat , struct breakpoint *)
Definition at line 4195 of file breakpoint.c.
References bpstats::breakpoint_at, and bpstats::next.
Referenced by finish_command_continuation().
int bpstat_num (bpstat * , int *)
Definition at line 4252 of file breakpoint.c.
References bpstats::next, and breakpoint::number.
Referenced by continue_command(), and program_info().
enum print_stop_action bpstat_print (bpstat , int)
Definition at line 4606 of file breakpoint.c.
References bpstats::next, print_bp_stop_message(), PRINT_NOTHING, print_solib_event(), PRINT_SRC_AND_LOC, PRINT_SRC_ONLY, PRINT_UNKNOWN, and TARGET_WAITKIND_LOADED.
Referenced by mi_on_normal_stop(), and normal_stop().
int bpstat_should_step (void)
Definition at line 5626 of file breakpoint.c.
References ALL_BREAKPOINTS, bp_watchpoint, breakpoint::loc, and breakpoint::type.
Referenced by currently_stepping(), proceed(), and resume().
bpstat bpstat_stop_status (struct address_space * aspace, CORE_ADDR pc, ptid_t ptid, const struct target_waitstatus * ws)
Definition at line 5236 of file breakpoint.c.
References breakpoint_ops::after_condition_true, ALL_BREAKPOINTS, bp_disabled, bp_hardware_watchpoint, bp_permanent, bp_shlib_event, bp_watchpoint_scope, bpstat_alloc(), bpstat_causes_stop(), bpstat_check_breakpoint_conditions(), bpstat_check_location(), bpstats::breakpoint_at, breakpoint_location_address_match(), breakpoint_ops::check_status, command_line_is_silent(), counted_command_line::commands, breakpoint::commands, bpstats::commands, disp_disable, breakpoint::disposition, breakpoint::enable_count, breakpoint::enable_state, bp_location::enabled, handle_solib_event(), breakpoint::hit_count, incref_counted_command_line(), is_hardware_watchpoint(), breakpoint::loc, bp_location::next, bpstats::next, observer_notify_breakpoint_modified(), breakpoint::ops, bpstats::print, bpstats::print_it, print_it_noop, breakpoint::related_breakpoint, bp_location::shlib_disabled, breakpoint::silent, bpstats::stop, breakpoint::type, update_global_location_list(), update_watchpoint(), VEC_iterate, watch_triggered_yes, and watchpoint::watchpoint_triggered.
Referenced by handle_inferior_event(), and handle_syscall_event().
struct bpstat_what bpstat_what (bpstat) [read]
Definition at line 5427 of file breakpoint.c.
References _, bp_access_watchpoint, bp_breakpoint, bp_call_dummy, bp_catchpoint, bp_dprintf, bp_exception, bp_exception_master, bp_exception_resume, bp_fast_tracepoint, bp_finish, bp_gnu_ifunc_resolver, bp_gnu_ifunc_resolver_return, bp_hardware_breakpoint, bp_hardware_watchpoint, bp_hp_step_resume, bp_jit_event, bp_longjmp, bp_longjmp_call_dummy, bp_longjmp_master, bp_longjmp_resume, bp_none, bp_overlay_event, bp_read_watchpoint, bp_shlib_event, bp_static_tracepoint, bp_std_terminate, bp_std_terminate_master, bp_step_resume, bp_thread_event, bp_tracepoint, bp_until, bp_watchpoint, bp_watchpoint_scope, BPSTAT_WHAT_CLEAR_LONGJMP_RESUME, BPSTAT_WHAT_HP_STEP_RESUME, BPSTAT_WHAT_KEEP_CHECKING, BPSTAT_WHAT_SET_LONGJMP_RESUME, BPSTAT_WHAT_SINGLE, BPSTAT_WHAT_STEP_RESUME, BPSTAT_WHAT_STOP_NOISY, BPSTAT_WHAT_STOP_SILENT, bpstat_what::call_dummy, debug_infrun, fprintf_unfiltered(), gdb_stdlog, gnu_ifunc_resolver_return_stop, gnu_ifunc_resolver_stop, handle_jit_event(), internal_error(), bpstat_what::is_longjmp, bpstat_what::main_action, max, STOP_NONE, STOP_STACK_DUMMY, STOP_STD_TERMINATE, and breakpoint::type.
Referenced by handle_inferior_event().
void break_command (char * , int)
Definition at line 9871 of file breakpoint.c.
References break_command_1().
Referenced by mi_cmd_break_commands(), and rbreak_command().
void breakpoint_auto_delete (bpstat)
Definition at line 11956 of file breakpoint.c.
References ALL_BREAKPOINTS_SAFE, bpstats::breakpoint_at, delete_breakpoint(), disp_del, disp_del_at_next_stop, breakpoint::disposition, bpstats::next, and bpstats::stop.
Referenced by normal_stop(), and run_inferior_call().
struct command_line* breakpoint_commands (struct breakpoint * b) [read]
Definition at line 356 of file breakpoint.c.
References counted_command_line::commands, and breakpoint::commands.
Referenced by all_tracepoint_actions_and_cleanup(), bppy_get_commands(), gdb_get_breakpoint_info(), gdb_get_tracepoint_info(), and remote_download_tracepoint().
void breakpoint_free_objfile (struct objfile * objfile)
Definition at line 15784 of file breakpoint.c.
References ALL_BP_LOCATIONS, symtab::objfile, and bp_location::symtab.
Referenced by free_objfile().
enum breakpoint_here breakpoint_here_p (struct address_space * , CORE_ADDR)
Definition at line 3896 of file breakpoint.c.
References ALL_BP_LOCATIONS, bp_loc_hardware_breakpoint, bp_loc_software_breakpoint, bp_permanent, breakpoint_location_address_match(), breakpoint::enable_state, bp_location::loc_type, ordinary_breakpoint_here, overlay_debugging, bp_location::owner, permanent_breakpoint_here, bp_location::section, section_is_mapped(), and section_is_overlay().
Referenced by crisv32_single_step_through_delay(), displaced_step_fixup(), mips_single_step_through_delay(), prepare_to_proceed(), proceed(), resume(), and tui_set_disassem_content().
void breakpoint_init_inferior (enum inf_context)
Definition at line 3787 of file breakpoint.c.
References ALL_BP_LOCATIONS, ALL_BREAKPOINTS_SAFE, bp_access_watchpoint, bp_call_dummy, bp_hardware_watchpoint, bp_longjmp_call_dummy, bp_permanent, bp_read_watchpoint, bp_shlib_event, bp_step_resume, bp_watchpoint, bp_watchpoint_scope, current_program_space, decref_bp_location(), delete_breakpoint(), breakpoint::enable_state, watchpoint::exp_valid_block, gdbarch_has_global_breakpoints(), inf_starting, bp_location::inserted, breakpoint::loc, bp_location::owner, bp_location::pspace, target_gdbarch(), breakpoint::type, watchpoint::val, watchpoint::val_valid, value_free(), VEC_free, and VEC_iterate.
Referenced by follow_exec(), generic_mourn_inferior(), and init_wait_for_inferior().
int breakpoint_inserted_here_p (struct address_space * , CORE_ADDR)
Definition at line 3976 of file breakpoint.c.
References regular_breakpoint_inserted_here_p(), and single_step_breakpoint_inserted_here_p().
Referenced by cancel_breakpoint(), handle_inferior_event(), ia64_hpux_at_dld_breakpoint_1_p(), record_full_wait_1(), resume(), and resume_stopped_resumed_lwps().
void breakpoint_program_space_exit (struct program_space * pspace)
Definition at line 2673 of file breakpoint.c.
References ALL_BP_LOCATIONS, ALL_BREAKPOINTS_SAFE, delete_breakpoint(), breakpoint::loc, bp_location::next, bp_location::owner, bp_location::pspace, breakpoint::pspace, and update_global_location_list().
Referenced by release_program_space().
void breakpoint_re_set (void)
Definition at line 14310 of file breakpoint.c.
References ALL_BREAKPOINTS_SAFE, breakpoint_re_set_one(), catch_errors(), create_exception_master_breakpoint(), create_longjmp_master_breakpoint(), create_overlay_event_breakpoint(), create_std_terminate_master_breakpoint(), current_language, do_cleanups(), input_radix, jit_breakpoint_re_set(), language_defn::la_language, make_cleanup(), breakpoint::number, RETURN_MASK_ALL, save_current_program_space(), set_language(), xfree(), and xstrprintf().
Referenced by clear_symtab_users(), enable_breakpoints_after_startup(), follow_exec(), follow_inferior_reset_breakpoints(), generic_load(), new_symfile_objfile(), objfile_rebase(), objfile_relocate(), post_create_inferior(), reload_shared_libraries(), and solib_add().
void breakpoint_re_set_thread (struct breakpoint *)
Definition at line 14348 of file breakpoint.c.
References current_program_space, in_thread_list(), inferior_ptid, breakpoint::loc, pid_to_thread_id(), bp_location::pspace, and breakpoint::thread.
Referenced by follow_inferior_reset_breakpoints().
void breakpoint_retire_moribund (void)
Definition at line 12552 of file breakpoint.c.
References decref_bp_location(), bp_location::events_till_retirement, VEC_iterate, and VEC_unordered_remove.
Referenced by handle_inferior_event().
void breakpoint_set_commands (struct breakpoint * b, struct command_line * commands)
Definition at line 1210 of file breakpoint.c.
References alloc_counted_command_line(), breakpoint::commands, decref_counted_command_line(), observer_notify_breakpoint_modified(), and validate_commands_for_breakpoint().
Referenced by create_tracepoint_from_upload(), gdb_actions_command(), mi_cmd_break_commands(), trace_actions_command(), and update_dprintf_command_list().
void breakpoint_set_silent (struct breakpoint * b, int silent)
Definition at line 1225 of file breakpoint.c.
References observer_notify_breakpoint_modified(), and breakpoint::silent.
Referenced by bppy_set_silent().
void breakpoint_set_task (struct breakpoint * b, int task)
Definition at line 1251 of file breakpoint.c.
References observer_notify_breakpoint_modified(), and breakpoint::task.
Referenced by bppy_set_task().
void breakpoint_set_thread (struct breakpoint * b, int thread)
Definition at line 1238 of file breakpoint.c.
References observer_notify_breakpoint_modified(), and breakpoint::thread.
Referenced by bppy_set_thread().
int breakpoint_thread_match (struct address_space * , CORE_ADDR , ptid_t)
Definition at line 4057 of file breakpoint.c.
References ada_get_task_number(), ALL_BP_LOCATIONS, bp_loc_hardware_breakpoint, bp_loc_software_breakpoint, bp_permanent, breakpoint_location_address_match(), breakpoint::enable_state, bp_location::loc_type, overlay_debugging, bp_location::owner, pid_to_thread_id(), bp_location::section, section_is_mapped(), section_is_overlay(), breakpoint::task, and breakpoint::thread.
Referenced by handle_inferior_event().
void breakpoint_xfer_memory (gdb_byte * readbuf, gdb_byte * writebuf, const gdb_byte * writebuf_org, ULONGEST memaddr, LONGEST len)
Definition at line 1436 of file breakpoint.c.
References _, bp_location::address, program_space::aspace, bp_location_count, bp_location_has_shadow(), bp_none, breakpoint_address_match(), current_program_space, gdb_assert, bp_location::gdbarch, gdbarch_breakpoint_from_pc(), memaddr, memcpy(), breakpoint::number, bp_location::owner, bp_target_info::placed_address, bp_target_info::placed_address_space, bp_target_info::placed_size, bp_target_info::shadow_contents, bp_target_info::shadow_len, bp_location::target_info, breakpoint::type, and warning().
Referenced by memory_xfer_partial().
int breakpoints_always_inserted_mode (void)
Definition at line 448 of file breakpoint.c.
References AUTO_BOOLEAN_AUTO, AUTO_BOOLEAN_TRUE, and non_stop.
Referenced by handle_inferior_event(), insert_breakpoints(), normal_stop(), remote_start_remote(), show_always_inserted_mode(), and update_global_location_list().
void cancel_single_step_breakpoints (void)
Definition at line 14973 of file breakpoint.c.
References xfree().
Referenced by handle_inferior_event().
int catch_syscall_enabled (void)
Definition at line 15036 of file breakpoint.c.
References current_inferior(), and get_catch_syscall_inferior_data().
Referenced by handle_syscall_event(), i386_linux_resume(), inf_ptrace_resume(), and linux_handle_syscall_trap().
int catching_syscall_number (int syscall_number)
Definition at line 15045 of file breakpoint.c.
References ALL_BREAKPOINTS, is_syscall_catchpoint_enabled(), and VEC_iterate.
Referenced by handle_syscall_event(), and linux_handle_syscall_trap().
void check_longjmp_breakpoint_for_call_dummy (int thread)
Definition at line 7274 of file breakpoint.c.
References ALL_BREAKPOINTS_SAFE, bp_call_dummy, bp_longjmp_call_dummy, delete_breakpoint(), dummy_frame_discard(), frame_find_by_id(), breakpoint::frame_id, breakpoint::next, breakpoint::related_breakpoint, breakpoint::thread, and breakpoint::type.
Referenced by handle_inferior_event().
void check_tracepoint_command (char * line, void * closure)
Definition at line 1261 of file breakpoint.c.
References validate_actionline().
Referenced by do_map_commands_command(), gdb_actions_command(), mi_cmd_break_commands(), and trace_actions_command().
void clear_breakpoint_hit_counts (void)
Definition at line 656 of file breakpoint.c.
References ALL_BREAKPOINTS, and breakpoint::hit_count.
Referenced by run_command_1().
void clear_displays (void)
Definition at line 1578 of file printcmd.c.
References free_display(), and display::next.
Referenced by clear_symtab_users(), and undisplay_command().
struct breakpoint* clone_momentary_breakpoint (struct breakpoint * bpkt) [read]
Definition at line 8826 of file breakpoint.c.
References momentary_breakpoint_from_master(), breakpoint::ops, and breakpoint::type.
Referenced by follow_fork().
enum command_control_type commands_from_control_command (char * arg, struct command_line * cmd)
Definition at line 1396 of file breakpoint.c.
References commands_command_1(), and simple_control.
Referenced by execute_control_command().
int create_breakpoint (struct gdbarch * gdbarch, char * arg, char * cond_string, int thread, char * extra_string, int parse_arg, int tempflag, enum bptype wanted_type, int ignore_count, enum auto_boolean pending_break_support, const struct breakpoint_ops * ops, int from_tty, int enabled, int internal, unsigned flags)
Definition at line 9552 of file breakpoint.c.
References _, breakpoint::addr_string, AUTO_BOOLEAN_AUTO, AUTO_BOOLEAN_FALSE, tracepoint::base, bp_breakpoint, bp_disabled, bp_enabled, bp_fast_tracepoint, bp_hardware_breakpoint, bptype_string(), breakpoint_sals_to_pc(), linespec_sals::canonical, check_fast_tracepoint_sals(), breakpoint::cond_string, breakpoint::condition_not_parsed, breakpoint_ops::create_breakpoints_sal, breakpoint_ops::create_sals_from_address, current_program_space, discard_cleanups(), disp_del, disp_donttouch, breakpoint::disposition, do_cleanups(), breakpoint::enable_state, gdb_exception::error, error(), exception_print(), breakpoint::extra_string, find_condition_and_thread(), gdb_assert, GDB_NO_ERROR, gdb_stderr, breakpoint::ignore_count, init_linespec_result(), init_raw_breakpoint_without_location(), init_sal(), install_breakpoint(), is_tracepoint_type(), make_cleanup(), make_cleanup_destroy_linespec_result(), symtabs_and_lines::nelts, NOT_FOUND_ERROR, nquery(), null_cleanup(), symtab_and_line::pc, breakpoint::pspace, gdb_exception::reason, RETURN_ERROR, RETURN_MASK_ALL, linespec_sals::sals, symtabs_and_lines::sals, throw_exception(), TRY_CATCH, update_global_location_list(), VEC_empty, VEC_index, VEC_iterate, VEC_length, VEC_safe_push, warning(), and xfree().
Referenced by bpfinishpy_init(), bppy_init(), break_command_1(), create_tracepoint_from_upload(), dprintf_command(), ftrace_command(), gdb_set_bp(), mi_cmd_break_insert_1(), spu_catch_start(), strace_command(), and trace_command().
struct breakpoint* create_jit_event_breakpoint (struct gdbarch * , CORE_ADDR) [read]
Definition at line 7394 of file breakpoint.c.
References bp_jit_event, create_internal_breakpoint(), internal_breakpoint_ops, and update_global_location_list_nothrow().
Referenced by jit_breakpoint_re_set_internal().
struct breakpoint* create_solib_event_breakpoint (struct gdbarch * , CORE_ADDR) [read]
Definition at line 7429 of file breakpoint.c.
References bp_shlib_event, create_internal_breakpoint(), internal_breakpoint_ops, and update_global_location_list_nothrow().
Referenced by darwin_solib_create_inferior_hook(), enable_break(), enable_break2(), ocl_enable_break(), som_solib_create_inferior_hook(), spu_enable_break(), svr4_create_probe_breakpoints(), and svr4_create_solib_event_breakpoints().
struct breakpoint* create_thread_event_breakpoint (struct gdbarch * , CORE_ADDR) [read]
Definition at line 7357 of file breakpoint.c.
References breakpoint::addr_string, bp_location::address, bp_enabled, bp_thread_event, create_internal_breakpoint(), breakpoint::enable_state, bp_location::gdbarch, internal_breakpoint_ops, breakpoint::loc, paddress(), update_global_location_list_nothrow(), and xstrprintf().
Referenced by enable_thread_event(), and pd_enable().
DEF_VEC_P (bp_location_p)
DEF_VEC_P (breakpoint_p)
void delete_breakpoint (struct breakpoint *)
Definition at line 13576 of file breakpoint.c.
References ALL_BREAKPOINTS, bp_none, bp_watchpoint_scope, bpstat_remove_breakpoint_callback(), breakpoint_ops::dtor, gdb_assert, iterate_over_threads(), breakpoint::next, breakpoint::number, observer_notify_breakpoint_deleted(), breakpoint::ops, breakpoint::related_breakpoint, breakpoint::type, update_global_location_list(), watchpoint_del_at_next_stop(), and xfree().
Referenced by bkpt_re_set(), bpfinishpy_out_of_scope(), bppy_delete_breakpoint(), breakpoint_auto_delete(), breakpoint_init_inferior(), breakpoint_program_space_exit(), check_longjmp_breakpoint_for_call_dummy(), clear_command(), delete_command(), delete_exception_resume_breakpoint(), delete_longjmp_breakpoint(), delete_std_terminate_breakpoint(), delete_step_resume_breakpoint(), delete_trace_command(), do_delete_breakpoint(), do_delete_breakpoint_cleanup(), elf_gnu_ifunc_resolver_return_stop(), finish_command_continuation(), internal_bkpt_re_set(), jit_breakpoint_re_set_internal(), pop_dummy_frame_bpt(), remove_jit_event_breakpoints(), remove_solib_event_breakpoints(), remove_thread_event_breakpoints(), until_break_command_continuation(), update_breakpoints_after_exec(), and watch_command_1().
void delete_command (char * arg, int from_tty)
Definition at line 13733 of file breakpoint.c.
References _, ALL_BREAKPOINTS, ALL_BREAKPOINTS_SAFE, delete_breakpoint(), do_map_delete_breakpoint(), dont_repeat(), map_breakpoint_numbers(), query(), and user_breakpoint_p().
Referenced by gdb_clear_file().
void delete_longjmp_breakpoint (int thread)
Definition at line 7207 of file breakpoint.c.
References ALL_BREAKPOINTS_SAFE, bp_exception, bp_longjmp, delete_breakpoint(), breakpoint::thread, and breakpoint::type.
Referenced by delete_longjmp_breakpoint_cleanup(), finish_command_continuation(), step_1_continuation(), until_break_command_continuation(), and until_next_continuation().
void delete_longjmp_breakpoint_at_next_stop (int thread)
Definition at line 7220 of file breakpoint.c.
References ALL_BREAKPOINTS_SAFE, bp_exception, bp_longjmp, disp_del_at_next_stop, breakpoint::disposition, breakpoint::thread, and breakpoint::type.
Referenced by clear_thread_inferior_resources().
void delete_std_terminate_breakpoint (void)
Definition at line 7347 of file breakpoint.c.
References ALL_BREAKPOINTS_SAFE, bp_std_terminate, delete_breakpoint(), and breakpoint::type.
Referenced by cleanup_delete_std_terminate_breakpoint().
void* deprecated_insert_raw_breakpoint (struct gdbarch * , struct address_space * , CORE_ADDR)
Definition at line 14859 of file breakpoint.c.
References bp_target_info::placed_address, bp_target_info::placed_address_space, target_insert_breakpoint(), xfree(), and XZALLOC.
Referenced by enable_break(), exec_one_dummy_insn(), and insert_single_step_breakpoint().
int deprecated_remove_raw_breakpoint (struct gdbarch * , void *)
Definition at line 14883 of file breakpoint.c.
References target_remove_breakpoint(), and xfree().
Referenced by disable_break(), exec_one_dummy_insn(), procfs_mourn_inferior(), remove_dbx_link_breakpoint(), and remove_single_step_breakpoints().
int detach_breakpoints (ptid_t ptid)
Definition at line 3578 of file breakpoint.c.
References _, ALL_BP_LOCATIONS, bp_loc_other, current_inferior(), detach_single_step_breakpoints(), do_cleanups(), error(), inferior_ptid, bp_location::inserted, bp_location::loc_type, mark_inserted, bp_location::pspace, inferior::pspace, ptid_get_pid(), remove_breakpoint_1(), and save_inferior_ptid().
Referenced by handle_inferior_event(), and linux_handle_extended_wait().
void disable_breakpoint (struct breakpoint *)
Definition at line 14523 of file breakpoint.c.
References bp_disabled, bp_permanent, bp_watchpoint_scope, current_trace_status(), breakpoint::enable_state, is_tracepoint(), breakpoint::loc, mark_breakpoint_modified(), bp_location::next, observer_notify_breakpoint_modified(), target_disable_tracepoint, target_supports_enable_disable_tracepoint, breakpoint::type, and update_global_location_list().
Referenced by bpfinishpy_post_stop_hook(), bppy_set_enabled(), disable_command(), do_disable_breakpoint(), and svr4_update_solib_event_breakpoint().
void disable_breakpoints_before_startup (void)
Definition at line 8743 of file breakpoint.c.
References current_program_space, program_space::executing_startup, and update_global_location_list().
Referenced by spu_solib_create_inferior_hook().
void disable_breakpoints_in_shlibs (void)
Definition at line 7443 of file breakpoint.c.
References bp_location::address, ALL_BP_LOCATIONS, bp_breakpoint, bp_hardware_breakpoint, bp_jit_event, current_program_space, is_tracepoint(), bp_location::owner, bp_location::pspace, bp_location::shlib_disabled, solib_name_from_address(), and breakpoint::type.
Referenced by clear_solib(), and do_initial_windows_stuff().
void disable_current_display (void)
Definition at line 1851 of file printcmd.c.
References _, current_display_number, disable_display(), fprintf_unfiltered(), and gdb_stderr.
Referenced by normal_stop().
void disable_display (int)
Definition at line 1837 of file printcmd.c.
References _, display::enabled_p, display::next, display::number, and printf_unfiltered().
Referenced by disable_current_display().
void disable_overlay_breakpoints (void)
Definition at line 7316 of file breakpoint.c.
References ALL_BREAKPOINTS, bp_disabled, bp_overlay_event, breakpoint::enable_state, breakpoint::type, and update_global_location_list().
Referenced by overlay_manual_command(), and overlay_off_command().
void disable_watchpoints_before_interactive_call_start (void)
Definition at line 8713 of file breakpoint.c.
References ALL_BREAKPOINTS, bp_call_disabled, breakpoint::enable_state, is_watchpoint(), and update_global_location_list().
Referenced by run_inferior_call().
void do_displays (void)
Definition at line 1825 of file printcmd.c.
References do_one_display(), and display::next.
Referenced by display_command(), normal_stop(), and tfind_1().
void enable_breakpoint (struct breakpoint *)
Definition at line 14681 of file breakpoint.c.
References breakpoint::disposition, and enable_breakpoint_disp().
Referenced by bppy_set_enabled(), do_enable_breakpoint(), enable_command(), and svr4_update_solib_event_breakpoint().
void enable_breakpoints_after_startup (void)
Definition at line 8750 of file breakpoint.c.
References breakpoint_re_set(), current_program_space, and program_space::executing_startup.
Referenced by spu_current_sos().
void enable_overlay_breakpoints (void)
Definition at line 7302 of file breakpoint.c.
References ALL_BREAKPOINTS, bp_enabled, bp_overlay_event, breakpoint::enable_state, breakpoint::type, and update_global_location_list().
Referenced by overlay_auto_command().
void enable_watchpoints_after_interactive_call_stop (void)
Definition at line 8728 of file breakpoint.c.
References ALL_BREAKPOINTS, bp_call_disabled, bp_enabled, breakpoint::enable_state, is_watchpoint(), and update_global_location_list().
Referenced by run_inferior_call().
void end_rbreak_breakpoints (void)
Definition at line 648 of file breakpoint.c.
References rbreak_start_breakpoint_count.
Referenced by do_end_rbreak_breakpoints().
char* ep_parse_optional_if_clause (char ** arg)
Definition at line 11505 of file breakpoint.c.
References skip_spaces().
Referenced by catch_exception_command_1(), catch_exec_command_1(), and catch_fork_command_1().
struct breakpoint* get_breakpoint (int num) [read]
Definition at line 727 of file breakpoint.c.
References ALL_BREAKPOINTS, and breakpoint::number.
Referenced by breakpoint_notify(), gdb_get_breakpoint_info(), gdbpy_breakpoint_deleted(), and mi_cmd_break_commands().
struct gdbarch* get_sal_arch (struct symtab_and_line sal) [read]
Definition at line 7090 of file breakpoint.c.
References get_objfile_arch(), obj_section::objfile, symtab::objfile, symtab_and_line::section, and symtab_and_line::symtab.
Referenced by add_location_to_breakpoint(), check_fast_tracepoint_sals(), init_ada_exception_breakpoint(), and init_breakpoint_sal().
struct tracepoint* get_tracepoint (int num) [read]
Definition at line 15406 of file breakpoint.c.
References ALL_TRACEPOINTS, and breakpoint::number.
Referenced by breakpoint_notify(), create_tracepoint_from_upload(), gdb_actions_command(), gdb_get_tracepoint_info(), get_traceframe_location(), mi_cmd_break_passcount(), tfile_fetch_registers(), tfile_trace_find(), and trace_find_tracepoint_command().
struct tracepoint* get_tracepoint_by_number (char ** arg, struct get_number_or_range_state * state, int optional_p) [read]
Definition at line 15442 of file breakpoint.c.
References _, ALL_TRACEPOINTS, error_no_arg(), get_number_or_range_state::finished, gdb_assert, get_number(), get_number_or_range(), breakpoint::number, printf_filtered(), and printf_unfiltered().
Referenced by trace_actions_command(), and trace_pass_command().
struct tracepoint* get_tracepoint_by_number_on_target (int num) [read]
Definition at line 15422 of file breakpoint.c.
References ALL_TRACEPOINTS, and tracepoint::number_on_target.
Referenced by tfile_get_traceframe_address(), and tfind_1().
int hardware_watchpoint_inserted_in_range (struct address_space * , CORE_ADDR addr, ULONGEST len)
Definition at line 4022 of file breakpoint.c.
References bp_location::address, ALL_BREAKPOINTS, program_space::aspace, bp_access_watchpoint, bp_hardware_watchpoint, bp_location::inserted, bp_location::length, breakpoint::loc, max, min, bp_location::next, bp_location::pspace, and breakpoint::type.
Referenced by record_full_exec_insn().
void hbreak_command_wrapper (char * , int)
void init_ada_exception_breakpoint (struct breakpoint * b, struct gdbarch * gdbarch, struct symtab_and_line sal, char * addr_string, const struct breakpoint_ops * ops, int tempflag, int enabled, int from_tty)
Definition at line 11618 of file breakpoint.c.
References breakpoint::addr_string, bp_breakpoint, bp_disabled, bp_enabled, describe_other_breakpoints(), disp_del, disp_donttouch, breakpoint::disposition, breakpoint::enable_state, get_sal_arch(), init_raw_breakpoint(), breakpoint::language, language_ada, symtab_and_line::pc, symtab_and_line::pspace, and symtab_and_line::section.
Referenced by create_ada_exception_catchpoint().
void init_bp_location (struct bp_location * loc, const struct bp_location_ops * ops, struct breakpoint * owner)
Definition at line 6872 of file breakpoint.c.
References _, bp_access_watchpoint, bp_breakpoint, bp_call_dummy, bp_catchpoint, bp_dprintf, bp_exception, bp_exception_master, bp_exception_resume, bp_fast_tracepoint, bp_finish, bp_gnu_ifunc_resolver, bp_gnu_ifunc_resolver_return, bp_hardware_breakpoint, bp_hardware_watchpoint, bp_hp_step_resume, bp_jit_event, bp_loc_hardware_breakpoint, bp_loc_hardware_watchpoint, bp_loc_other, bp_loc_software_breakpoint, bp_longjmp, bp_longjmp_call_dummy, bp_longjmp_master, bp_longjmp_resume, bp_overlay_event, bp_read_watchpoint, bp_shlib_event, bp_static_tracepoint, bp_std_terminate, bp_std_terminate_master, bp_step_resume, bp_thread_event, bp_tracepoint, bp_until, bp_watchpoint, bp_watchpoint_scope, bp_location::cond, bp_location::cond_bytecode, bp_location::enabled, gdb_assert, internal_error(), bp_location::loc_type, mark_breakpoint_location_modified(), memset(), bp_location::ops, bp_location::owner, bp_location::refc, bp_location::shlib_disabled, and breakpoint::type.
Referenced by allocate_location_exception(), and base_breakpoint_allocate_location().
void init_catchpoint (struct breakpoint * b, struct gdbarch * gdbarch, int tempflag, char * cond_string, const struct breakpoint_ops * ops)
Definition at line 8452 of file breakpoint.c.
References bp_catchpoint, breakpoint::cond_string, current_program_space, disp_del, disp_donttouch, breakpoint::disposition, init_raw_breakpoint(), init_sal(), and symtab_and_line::pspace.
Referenced by add_solib_catchpoint(), catch_exec_command_1(), create_fork_vfork_event_catchpoint(), create_signal_catchpoint(), create_syscall_event_catchpoint(), and handle_gnu_v3_exceptions().
void initialize_breakpoint_ops (void)
Definition at line 15794 of file breakpoint.c.
References breakpoint_ops::after_condition_true, base_breakpoint_ops, bkpt_base_breakpoint_ops, bkpt_breakpoint_hit(), bkpt_breakpoint_ops, bkpt_create_breakpoints_sal(), bkpt_create_sals_from_address(), bkpt_decode_linespec(), bkpt_insert_location(), bkpt_print_it(), bkpt_print_mention(), bkpt_print_recreate(), bkpt_probe_breakpoint_ops, bkpt_probe_create_sals_from_address(), bkpt_probe_decode_linespec(), bkpt_probe_insert_location(), bkpt_probe_remove_location(), bkpt_re_set(), bkpt_remove_location(), bkpt_resources_needed(), breakpoint_ops::breakpoint_hit, breakpoint_hit_catch_exec(), breakpoint_hit_catch_fork(), breakpoint_hit_catch_solib(), breakpoint_hit_catch_syscall(), breakpoint_hit_catch_vfork(), breakpoint_hit_ranged_breakpoint(), breakpoint_hit_watchpoint(), catch_exec_breakpoint_ops, catch_fork_breakpoint_ops, catch_solib_breakpoint_ops, catch_syscall_breakpoint_ops, catch_vfork_breakpoint_ops, breakpoint_ops::check_status, check_status_catch_solib(), check_status_watchpoint(), breakpoint_ops::create_breakpoints_sal, breakpoint_ops::create_sals_from_address, breakpoint_ops::decode_linespec, dprintf_after_condition_true(), dprintf_breakpoint_ops, dprintf_print_recreate(), dprintf_re_set(), breakpoint_ops::dtor, dtor_catch_exec(), dtor_catch_solib(), dtor_catch_syscall(), dtor_watchpoint(), breakpoint_ops::explains_signal, explains_signal_watchpoint(), insert_catch_exec(), insert_catch_fork(), insert_catch_solib(), insert_catch_syscall(), insert_catch_vfork(), breakpoint_ops::insert_location, insert_masked_watchpoint(), insert_watchpoint(), internal_bkpt_check_status(), internal_bkpt_print_it(), internal_bkpt_print_mention(), internal_bkpt_re_set(), internal_breakpoint_ops, longjmp_bkpt_dtor(), longjmp_breakpoint_ops, masked_watchpoint_breakpoint_ops, momentary_bkpt_check_status(), momentary_bkpt_print_it(), momentary_bkpt_print_mention(), momentary_bkpt_re_set(), momentary_breakpoint_ops, breakpoint_ops::print_it, print_it_catch_exec(), print_it_catch_fork(), print_it_catch_solib(), print_it_catch_syscall(), print_it_catch_vfork(), print_it_masked_watchpoint(), print_it_ranged_breakpoint(), print_it_watchpoint(), breakpoint_ops::print_mention, print_mention_catch_exec(), print_mention_catch_fork(), print_mention_catch_solib(), print_mention_catch_syscall(), print_mention_catch_vfork(), print_mention_masked_watchpoint(), print_mention_ranged_breakpoint(), print_mention_watchpoint(), breakpoint_ops::print_one, print_one_catch_exec(), print_one_catch_fork(), print_one_catch_solib(), print_one_catch_syscall(), print_one_catch_vfork(), breakpoint_ops::print_one_detail, print_one_detail_masked_watchpoint(), print_one_detail_ranged_breakpoint(), print_one_ranged_breakpoint(), breakpoint_ops::print_recreate, print_recreate_catch_exec(), print_recreate_catch_fork(), print_recreate_catch_solib(), print_recreate_catch_syscall(), print_recreate_catch_vfork(), print_recreate_masked_watchpoint(), print_recreate_ranged_breakpoint(), print_recreate_watchpoint(), ranged_breakpoint_ops, breakpoint_ops::re_set, re_set_watchpoint(), remove_catch_exec(), remove_catch_fork(), remove_catch_solib(), remove_catch_syscall(), remove_catch_vfork(), breakpoint_ops::remove_location, remove_masked_watchpoint(), remove_watchpoint(), breakpoint_ops::resources_needed, resources_needed_masked_watchpoint(), resources_needed_ranged_breakpoint(), resources_needed_watchpoint(), strace_marker_breakpoint_ops, strace_marker_create_breakpoints_sal(), strace_marker_create_sals_from_address(), strace_marker_decode_linespec(), tracepoint_breakpoint_hit(), tracepoint_breakpoint_ops, tracepoint_create_breakpoints_sal(), tracepoint_create_sals_from_address(), tracepoint_decode_linespec(), tracepoint_print_mention(), tracepoint_print_one_detail(), tracepoint_print_recreate(), tracepoint_probe_breakpoint_ops, tracepoint_probe_create_sals_from_address(), tracepoint_probe_decode_linespec(), tracepoint_re_set(), watchpoint_breakpoint_ops, breakpoint_ops::works_in_software_mode, works_in_software_mode_masked_watchpoint(), and works_in_software_mode_watchpoint().
Referenced by initialize_ada_catchpoint_ops(), initialize_signal_catchpoint_ops(), and initialize_throw_catchpoint_ops().
void insert_breakpoints (void)
Definition at line 2716 of file breakpoint.c.
References ALL_BREAKPOINTS, breakpoints_always_inserted_mode(), insert_breakpoint_locations(), is_hardware_watchpoint(), update_global_location_list(), and update_watchpoint().
Referenced by arm_linux_copy_svc(), follow_exec(), follow_inferior_reset_breakpoints(), gdbsim_create_inferior(), go32_create_inferior(), handle_inferior_event(), inferior_call_waitpid(), inferior_call_waitpid_cleanup(), keep_going(), linux_fork_context(), proceed(), remote_start_remote(), and resume().
void insert_single_step_breakpoint (struct gdbarch * , struct address_space * , CORE_ADDR)
Definition at line 14903 of file breakpoint.c.
References _, deprecated_insert_raw_breakpoint(), error(), gdb_assert, and paddress().
Referenced by alpha_deal_with_atomic_sequence(), alpha_software_single_step(), arm_insert_single_step_breakpoint(), cris_software_single_step(), micromips_deal_with_atomic_sequence(), mips_deal_with_atomic_sequence(), mips_software_single_step(), nios2_software_single_step(), ppc_deal_with_atomic_sequence(), rs6000_software_single_step(), sparc_software_single_step(), spu_software_single_step(), and tic6x_software_single_step().
void install_breakpoint (int internal, struct breakpoint * b, int update_gll)
Definition at line 8469 of file breakpoint.c.
References add_to_breakpoint_chain(), is_tracepoint(), mention(), observer_notify_breakpoint_created(), set_breakpoint_number(), set_tracepoint_count(), and update_global_location_list().
Referenced by add_solib_catchpoint(), catch_exec_command_1(), create_ada_exception_catchpoint(), create_breakpoint(), create_breakpoint_sal(), create_fork_vfork_event_catchpoint(), create_signal_catchpoint(), create_syscall_event_catchpoint(), handle_gnu_v3_exceptions(), strace_marker_create_breakpoints_sal(), and watch_command_1().
int is_breakpoint (const struct breakpoint * bpt)
Definition at line 1590 of file breakpoint.c.
References bp_breakpoint, bp_dprintf, bp_hardware_breakpoint, and breakpoint::type.
Referenced by bp_condition_evaluator(), bp_location_condition_evaluator(), build_target_command_list(), build_target_condition_list(), condition_command(), force_breakpoint_reinsertion(), insert_bp_location(), mark_breakpoint_location_modified(), mark_breakpoint_modified(), print_breakpoint_location(), print_one_breakpoint_location(), set_condition_evaluation_mode(), update_global_location_list(), and update_inserted_breakpoint_locations().
int is_catchpoint (struct breakpoint *)
Definition at line 4117 of file breakpoint.c.
References bp_catchpoint, and breakpoint::type.
Referenced by print_one_breakpoint_location().
int is_tracepoint (const struct breakpoint * b)
Definition at line 1112 of file breakpoint.c.
References is_tracepoint_type(), and breakpoint::type.
Referenced by breakpoint_locations_match(), delete_trace_command(), disable_breakpoint(), disable_breakpoints_in_shlibs(), disable_breakpoints_in_unloaded_shlib(), disable_command(), do_map_commands_command(), enable_breakpoint_disp(), enable_command(), install_breakpoint(), mi_cmd_break_commands(), print_one_breakpoint_location(), remove_breakpoints(), save_breakpoints(), save_tracepoints_command(), set_breakpoint_location_function(), set_ignore_count(), swap_insertion(), tracepoint_locations_match(), tracepoints_info(), update_global_location_list(), and validate_commands_for_breakpoint().
int is_watchpoint (const struct breakpoint * bpt)
Definition at line 1611 of file breakpoint.c.
References bp_watchpoint, is_hardware_watchpoint(), and breakpoint::type.
Referenced by aarch64_dr_state_insert_one_point(), aarch64_dr_state_remove_one_point(), aarch64_notify_debug_reg_change(), bppy_get_expression(), bpstat_check_breakpoint_conditions(), check_status_watchpoint(), clear_command(), debug_reg_change_callback(), disable_watchpoints_before_interactive_call_start(), enable_breakpoint_disp(), enable_watchpoints_after_interactive_call_stop(), gdb_get_breakpoint_info(), print_one_breakpoint_location(), save_breakpoints(), set_breakpoint_condition(), and watchpoints_info().
void iterate_over_bp_locations (walk_bp_location_callback)
Definition at line 2740 of file breakpoint.c.
References ALL_BP_LOCATIONS.
Referenced by record_full_init_record_breakpoints().
struct breakpoint* iterate_over_breakpoints (int(*)(struct breakpoint *, void *) , void *) [read]
Definition at line 15727 of file breakpoint.c.
References ALL_BREAKPOINTS_SAFE.
Referenced by bpfinishpy_handle_exit(), bpfinishpy_handle_stop(), gdbpy_breakpoints(), pop_dummy_frame(), and svr4_update_solib_event_breakpoints().
void make_breakpoint_permanent (struct breakpoint *)
Definition at line 7158 of file breakpoint.c.
References bp_permanent, breakpoint::enable_state, bp_location::inserted, breakpoint::loc, and bp_location::next.
Referenced by init_breakpoint_sal(), and update_breakpoint_locations().
struct cleanup* make_cleanup_delete_breakpoint (struct breakpoint *) [read]
Definition at line 13675 of file breakpoint.c.
References do_delete_breakpoint_cleanup(), and make_cleanup().
Referenced by finish_forward(), and until_break_command().
void mark_breakpoints_out (void)
Definition at line 3765 of file breakpoint.c.
References ALL_BP_LOCATIONS, current_program_space, bp_location::inserted, and bp_location::pspace.
Referenced by follow_exec(), and generic_mourn_inferior().
int moribund_breakpoint_here_p (struct address_space * , CORE_ADDR)
Definition at line 3929 of file breakpoint.c.
References breakpoint_location_address_match(), and VEC_iterate.
Referenced by adjust_pc_after_break().
int pc_at_non_inline_function (struct address_space * aspace, CORE_ADDR pc, const struct target_waitstatus * ws)
Definition at line 15759 of file breakpoint.c.
References ALL_BREAKPOINTS, bpstat_check_location(), is_non_inline_function(), breakpoint::loc, bp_location::next, and bp_location::shlib_disabled.
Referenced by handle_inferior_event().
void print_recreate_thread (struct breakpoint * b, struct ui_file * fp)
Definition at line 15487 of file breakpoint.c.
References fprintf_unfiltered(), breakpoint::task, and breakpoint::thread.
Referenced by bkpt_print_recreate(), dprintf_print_recreate(), print_recreate_catch_exec(), print_recreate_catch_fork(), print_recreate_catch_syscall(), print_recreate_catch_vfork(), print_recreate_exception(), print_recreate_exception_catchpoint(), print_recreate_masked_watchpoint(), print_recreate_ranged_breakpoint(), print_recreate_watchpoint(), and tracepoint_print_recreate().
void rbreak_command_wrapper (char * , int)
Definition at line 3874 of file symtab.c.
References rbreak_command().
int reattach_breakpoints (int)
Definition at line 2984 of file breakpoint.c.
References ALL_BP_LOCATIONS, any_live_thread_of_process(), do_cleanups(), find_inferior_pid(), arm-linux::inf, inferior_ptid, insert_bp_location(), bp_location::inserted, make_cleanup_ui_file_delete(), mem_fileopen(), bp_location::pspace, inferior::pspace, thread_info::ptid, and save_inferior_ptid().
int regular_breakpoint_inserted_here_p (struct address_space * , CORE_ADDR)
Definition at line 3947 of file breakpoint.c.
References ALL_BP_LOCATIONS, bp_loc_hardware_breakpoint, bp_loc_software_breakpoint, breakpoint_location_address_match(), bp_location::inserted, bp_location::loc_type, overlay_debugging, bp_location::section, section_is_mapped(), and section_is_overlay().
Referenced by breakpoint_inserted_here_p(), and handle_inferior_event().
int remove_breakpoints (void)
Definition at line 2919 of file breakpoint.c.
References ALL_BP_LOCATIONS, bp_location::inserted, is_tracepoint(), mark_uninserted, bp_location::owner, and remove_breakpoint().
Referenced by gdbsim_create_inferior(), gdbsim_mourn_inferior(), handle_inferior_event(), inferior_call_waitpid(), inferior_call_waitpid_cleanup(), keep_going(), linux_fork_context(), m32r_mourn_inferior(), normal_stop(), proceed(), and target_disconnect().
int remove_breakpoints_pid (int pid)
Definition at line 2959 of file breakpoint.c.
References ALL_BP_LOCATIONS, bp_dprintf, find_inferior_pid(), bp_location::inserted, mark_uninserted, bp_location::owner, bp_location::pspace, inferior::pspace, remove_breakpoint(), and breakpoint::type.
Referenced by linux_child_follow_fork(), and target_detach().
void remove_jit_event_breakpoints (void)
Definition at line 7407 of file breakpoint.c.
References ALL_BREAKPOINTS_SAFE, bp_jit_event, current_program_space, delete_breakpoint(), breakpoint::loc, bp_location::pspace, and breakpoint::type.
void remove_single_step_breakpoints (void)
Definition at line 14947 of file breakpoint.c.
References deprecated_remove_raw_breakpoint(), and gdb_assert.
Referenced by handle_inferior_event(), record_full_wait_1(), and resume().
void remove_solib_event_breakpoints (void)
Definition at line 7418 of file breakpoint.c.
References ALL_BREAKPOINTS_SAFE, bp_shlib_event, current_program_space, delete_breakpoint(), breakpoint::loc, bp_location::pspace, and breakpoint::type.
Referenced by enable_break2(), and reload_shared_libraries().
void remove_thread_event_breakpoints (void)
Definition at line 7375 of file breakpoint.c.
References ALL_BREAKPOINTS_SAFE, bp_thread_event, current_program_space, delete_breakpoint(), breakpoint::loc, bp_location::pspace, and breakpoint::type.
Referenced by enable_thread_event_reporting(), thread_db_detach(), and thread_db_mourn_inferior().
void rwatch_command_wrapper (char * , int , int)
Definition at line 11334 of file breakpoint.c.
References hw_read, and watch_command_1().
Referenced by bppy_init(), and mi_cmd_break_watch().
void set_breakpoint_condition (struct breakpoint * b, char * exp, int from_tty)
Definition at line 913 of file breakpoint.c.
References _, bp_location::address, block_for_pc(), bp_location::cond, watchpoint::cond_exp, watchpoint::cond_exp_valid_block, breakpoint::cond_string, breakpoint::condition_not_parsed, error(), watchpoint::exp, innermost_block, is_watchpoint(), breakpoint::loc, mark_breakpoint_modified(), bp_location::next, breakpoint::number, observer_notify_breakpoint_modified(), parse_exp_1(), printf_filtered(), and xfree().
Referenced by bppy_set_condition(), condition_command(), and create_ada_exception_catchpoint().
void set_ignore_count (int , int , int)
Definition at line 14368 of file breakpoint.c.
References _, ALL_BREAKPOINTS, error(), breakpoint::ignore_count, is_tracepoint(), breakpoint::number, observer_notify_breakpoint_modified(), and printf_filtered().
Referenced by bppy_set_ignore_count(), continue_command(), and ignore_command().
void set_longjmp_breakpoint (struct thread_info * tp, struct frame_id frame)
Definition at line 7178 of file breakpoint.c.
References ALL_BREAKPOINTS_SAFE, bp_exception, bp_exception_master, bp_longjmp, bp_longjmp_master, current_program_space, thread_info::initiating_frame, longjmp_breakpoint_ops, momentary_breakpoint_from_master(), thread_info::num, breakpoint::pspace, breakpoint::thread, and breakpoint::type.
Referenced by finish_forward(), step_1(), until_break_command(), and until_next_command().
struct breakpoint* set_longjmp_breakpoint_for_call_dummy (void) [read]
Definition at line 7238 of file breakpoint.c.
References ALL_BREAKPOINTS, bp_longjmp_call_dummy, bp_longjmp_master, current_program_space, gdb_assert, inferior_ptid, momentary_breakpoint_from_master(), momentary_breakpoint_ops, pid_to_thread_id(), breakpoint::pspace, breakpoint::related_breakpoint, breakpoint::thread, and breakpoint::type.
Referenced by call_function_by_hand().
struct breakpoint* set_momentary_breakpoint (struct gdbarch * , struct symtab_and_line , struct frame_id , enum bptype) [read]
struct breakpoint* set_momentary_breakpoint_at_pc (struct gdbarch * , CORE_ADDR pc, enum bptype type) [read]
Definition at line 8836 of file breakpoint.c.
References find_pc_line(), find_pc_overlay(), null_frame_id, symtab_and_line::pc, and set_momentary_breakpoint().
Referenced by insert_exception_resume_breakpoint(), insert_exception_resume_from_probe(), and insert_longjmp_resume_breakpoint().
void set_std_terminate_breakpoint (void)
Definition at line 7332 of file breakpoint.c.
References ALL_BREAKPOINTS_SAFE, bp_std_terminate, bp_std_terminate_master, current_program_space, momentary_breakpoint_from_master(), momentary_breakpoint_ops, breakpoint::pspace, and breakpoint::type.
Referenced by call_function_by_hand().
int single_step_breakpoints_inserted (void)
Definition at line 14938 of file breakpoint.c.
Referenced by record_full_resume(), and record_full_wait_1().
int software_breakpoint_inserted_here_p (struct address_space * , CORE_ADDR)
Definition at line 3991 of file breakpoint.c.
References bp_location::address, ALL_BP_LOCATIONS, program_space::aspace, bp_loc_software_breakpoint, breakpoint_address_match(), bp_location::inserted, bp_location::loc_type, overlay_debugging, bp_location::pspace, bp_location::section, section_is_mapped(), section_is_overlay(), and single_step_breakpoint_inserted_here_p().
Referenced by adjust_pc_after_break(), and record_full_wait_1().
void start_rbreak_breakpoints (void)
Definition at line 639 of file breakpoint.c.
Referenced by rbreak_command().
void tbreak_command (char * , int)
Definition at line 9877 of file breakpoint.c.
References BP_TEMPFLAG, and break_command_1().
Referenced by go_command(), and run_command_1().
void thbreak_command_wrapper (char * , int)
void until_break_command (char * , int , int)
Definition at line 11384 of file breakpoint.c.
References _, add_continuation(), bp_until, until_break_command_continuation_args::breakpoint, until_break_command_continuation_args::breakpoint2, clear_proceed_status(), decode_line_1(), DECODE_LINE_FUNFIRSTLINE, delete_longjmp_breakpoint_cleanup(), discard_cleanups(), do_cleanups(), error(), find_pc_line(), frame_id_p(), frame_unwind_caller_arch(), frame_unwind_caller_id(), frame_unwind_caller_pc(), get_frame_arch(), get_last_displayed_line(), get_last_displayed_symtab(), get_selected_frame(), get_stack_frame_id(), inferior_ptid, inferior_thread(), is_running(), last_displayed_sal_is_valid(), make_cleanup(), make_cleanup_delete_breakpoint(), symtabs_and_lines::nelts, null_cleanup(), null_frame_id, thread_info::num, proceed(), resolve_sal_pc(), symtabs_and_lines::sals, set_longjmp_breakpoint(), set_momentary_breakpoint(), target_can_async_p, until_break_command_continuation_args::thread_num, until_break_command_continuation(), xfree(), and xmalloc().
Referenced by advance_command(), and until_command().
void update_breakpoint_locations (struct breakpoint * b, struct symtabs_and_lines sals, struct symtabs_and_lines sals_end)
Definition at line 13976 of file breakpoint.c.
References _, add_location_to_breakpoint(), all_locations_are_pending(), ambiguous_names_p(), block_for_pc(), bp_disabled, bp_permanent, breakpoint_locations_match(), bp_location::cond, breakpoint::cond_string, breakpoint::enable_state, bp_location::enabled, find_breakpoint_range_end(), bp_location::function_name, bp_location::length, breakpoint::loc, locations_are_equal(), make_breakpoint_permanent(), gdb_exception::message, symtabs_and_lines::nelts, bp_location::next, breakpoint::number, observer_notify_breakpoint_modified(), parse_exp_1(), symtab_and_line::pc, printf_unfiltered(), symtab_and_line::pspace, gdb_exception::reason, RETURN_MASK_ERROR, symtabs_and_lines::sals, switch_to_program_space_and_thread(), TRY_CATCH, update_global_location_list(), and warning().
Referenced by breakpoint_re_set_default(), elf_gnu_ifunc_resolver_return_stop(), and re_set_exception_catchpoint().
void update_breakpoints_after_exec (void)
Definition at line 3458 of file breakpoint.c.
References breakpoint::addr_string, ALL_BP_LOCATIONS, ALL_BREAKPOINTS_SAFE, bp_catchpoint, bp_exception, bp_exception_master, bp_exception_resume, bp_finish, bp_hp_step_resume, bp_jit_event, bp_longjmp, bp_longjmp_call_dummy, bp_longjmp_master, bp_longjmp_resume, bp_overlay_event, bp_shlib_event, bp_std_terminate_master, bp_step_resume, bp_thread_event, create_exception_master_breakpoint(), create_longjmp_master_breakpoint(), create_overlay_event_breakpoint(), create_std_terminate_master_breakpoint(), current_program_space, delete_breakpoint(), gdb_assert, bp_location::inserted, bp_location::pspace, breakpoint::pspace, and breakpoint::type.
Referenced by follow_exec().
int user_breakpoint_p (struct breakpoint *)
Definition at line 6370 of file breakpoint.c.
References breakpoint::number.
Referenced by breakpoint_1(), delete_command(), delete_trace_command(), describe_other_breakpoints(), disable_command(), enable_command(), remove_threaded_breakpoints(), save_breakpoints(), and should_be_inserted().
VEC (breakpoint_p)
Definition at line 1188 of file breakpoint.c.
References bp_location::address, ALL_BREAKPOINTS, bp_static_tracepoint, breakpoint::loc, bp_location::next, breakpoint::type, VEC, and VEC_safe_push.
void watch_command_wrapper (char * , int , int)
Definition at line 11303 of file breakpoint.c.
References hw_write, and watch_command_1().
Referenced by bppy_init(), and mi_cmd_break_watch().
int watchpoints_triggered (struct target_waitstatus *)
Definition at line 4677 of file breakpoint.c.
References bp_location::address, ALL_BREAKPOINTS, current_target, watchpoint::hw_wp_mask, is_hardware_watchpoint(), is_masked_watchpoint(), bp_location::length, breakpoint::loc, bp_location::next, target_stopped_by_watchpoint, target_stopped_data_address, target_watchpoint_addr_within_range, watch_triggered_no, watch_triggered_unknown, watch_triggered_yes, and watchpoint::watchpoint_triggered.
Referenced by handle_inferior_event().
Variable Documentation
struct breakpoint_ops base_breakpoint_ops
Definition at line 279 of file breakpoint.c.
Referenced by dtor_catch_exec(), dtor_catch_solib(), dtor_catch_syscall(), dtor_watchpoint(), initialize_breakpoint_ops(), initialize_signal_catchpoint_ops(), and signal_catchpoint_dtor().
struct breakpoint_ops bkpt_breakpoint_ops
Definition at line 297 of file breakpoint.c.
Referenced by bpfinishpy_init(), bppy_init(), break_command_1(), check_status_exception_catchpoint(), dtor_exception(), dtor_exception_catchpoint(), gdb_set_bp(), initialize_ada_catchpoint_ops(), initialize_breakpoint_ops(), initialize_throw_catchpoint_ops(), mi_cmd_break_insert_1(), re_set_exception(), and spu_catch_start().
struct breakpoint_ops dprintf_breakpoint_ops
Definition at line 303 of file breakpoint.c.
Referenced by dprintf_command(), initialize_breakpoint_ops(), and mi_cmd_break_insert_1().
int target_exact_watchpoints
Definition at line 521 of file breakpoint.c.
Referenced by _initialize_rs6000_tdep().
struct breakpoint_ops tracepoint_breakpoint_ops
Definition at line 13366 of file breakpoint.c.
Referenced by create_tracepoint_from_upload(), ftrace_command(), initialize_breakpoint_ops(), mi_cmd_break_insert_1(), strace_command(), and trace_command().