GDB (xrefs): /home/stan/gdb/src/gdb/btrace.h File Reference
/home/stan/gdb/src/gdb/btrace.h File Reference
#include "btrace-common.h"
Classes
struct btrace_inst
struct btrace_func
struct btrace_insn_iterator
struct btrace_func_iterator
struct btrace_thread_info
Typedefs
typedef struct btrace_inst btrace_inst_s
typedef struct btrace_func btrace_func_s
Functions
DEF_VEC_O (btrace_inst_s)
DEF_VEC_O (btrace_func_s)
void btrace_enable (struct thread_info *tp)
void btrace_disable (struct thread_info *)
void btrace_teardown (struct thread_info *)
void btrace_fetch (struct thread_info *)
void btrace_clear (struct thread_info *)
void btrace_free_objfile (struct objfile *)
VEC (btrace_block_s)*parse_xml_btrace(const char *)
Typedef Documentation
typedef struct btrace_func btrace_func_s
Definition at line 65 of file btrace.h.
typedef struct btrace_inst btrace_inst_s
Definition at line 64 of file btrace.h.
Function Documentation
void btrace_clear (struct thread_info *)
Definition at line 422 of file btrace.c.
References thread_info::btrace, DEBUG, thread_info::num, thread_info::ptid, target_pid_to_str(), and VEC_free.
Referenced by btrace_disable(), btrace_fetch(), btrace_free_objfile(), and btrace_teardown().
void btrace_disable (struct thread_info *)
Definition at line 355 of file btrace.c.
References thread_info::btrace, btrace_clear(), DEBUG, thread_info::num, thread_info::ptid, btrace_thread_info::target, target_disable_btrace(), and target_pid_to_str().
Referenced by record_btrace_disable_callback(), and record_btrace_stop_recording().
void btrace_enable (struct thread_info * tp)
Definition at line 339 of file btrace.c.
References _, thread_info::btrace, DEBUG, error(), thread_info::num, thread_info::ptid, btrace_thread_info::target, target_enable_btrace(), target_pid_to_str(), and target_supports_btrace().
Referenced by record_btrace_enable_warn(), and record_btrace_open().
void btrace_fetch (struct thread_info *)
Definition at line 393 of file btrace.c.
References thread_info::btrace, btrace_clear(), btrace_init_func_iterator(), btrace_init_insn_iterator(), btrace_read_new, DEBUG, thread_info::num, thread_info::ptid, btrace_thread_info::target, target_pid_to_str(), VEC, and VEC_empty.
Referenced by record_btrace_info(), and require_btrace().
void btrace_free_objfile (struct objfile *)
Definition at line 442 of file btrace.c.
References ALL_THREADS, btrace_clear(), and DEBUG.
Referenced by free_objfile().
void btrace_teardown (struct thread_info *)
Definition at line 374 of file btrace.c.
References thread_info::btrace, btrace_clear(), DEBUG, thread_info::num, thread_info::ptid, btrace_thread_info::target, target_pid_to_str(), and target_teardown_btrace().
Referenced by clear_thread_inferior_resources().
DEF_VEC_O (btrace_inst_s)
DEF_VEC_O (btrace_func_s)
VEC (btrace_block_s) const