GDB (xrefs): /home/stan/gdb/src/gdb/buildsym.h File Reference
/home/stan/gdb/src/gdb/buildsym.h File Reference
Classes
struct subfile
struct pending
struct context_stack
Defines
#define HASHSIZE
#define PENDINGSIZE 100
#define outermost_context_p() (context_stack_depth == 0)
#define next_symbol_text(objfile) (*next_symbol_text_func)(objfile)
Functions
void add_symbol_to_list (struct symbol *symbol, struct pending **listhead)
struct symbol * find_symbol_in_list (struct pending *list, char *name, int length)
struct block * finish_block (struct symbol *symbol, struct pending **listhead, struct pending_block *old_blocks, CORE_ADDR start, CORE_ADDR end, struct objfile *objfile)
void record_block_range (struct block *, CORE_ADDR start, CORE_ADDR end_inclusive)
void really_free_pendings (void *dummy)
void start_subfile (const char *name, const char *dirname)
void patch_subfile_names (struct subfile *subfile, char *name)
void push_subfile (void)
char * pop_subfile (void)
struct block * end_symtab_get_static_block (CORE_ADDR end_addr, struct objfile *objfile, int expandable, int required)
struct symtab * end_symtab_from_static_block (struct block *static_block, struct objfile *objfile, int section, int expandable)
struct symtab * end_symtab (CORE_ADDR end_addr, struct objfile *objfile, int section)
struct symtab * end_expandable_symtab (CORE_ADDR end_addr, struct objfile *objfile, int section)
void augment_type_symtab (struct objfile *objfile, struct symtab *primary_symtab)
void scan_file_globals (struct objfile *objfile)
void buildsym_new_init (void)
void buildsym_init (void)
struct context_stack * push_context (int desc, CORE_ADDR valu)
struct context_stack * pop_context (void)
void record_line (struct subfile *subfile, int line, CORE_ADDR pc)
void start_symtab (const char *name, const char *dirname, CORE_ADDR start_addr)
void restart_symtab (CORE_ADDR start_addr)
int hashname (const char *name)
void free_pending_blocks (void)
void record_debugformat (const char *format)
void record_producer (const char *producer)
void merge_symbol_lists (struct pending **srclist, struct pending **targetlist)
void set_last_source_file (const char *name)
const char * get_last_source_file (void)
struct macro_table * get_macro_table (struct objfile *objfile, const char *comp_dir)
Variables
EXTERN CORE_ADDR last_source_start_addr
EXTERN struct subfile * current_subfile
EXTERN unsigned char processing_gcc_compilation
EXTERN unsigned char processing_acc_compilation
EXTERN unsigned int symnum
EXTERN struct pending * file_symbols
EXTERN struct pending * global_symbols
EXTERN struct pending * local_symbols
EXTERN struct using_direct * using_directives
EXTERN struct context_stack * context_stack
EXTERN int context_stack_depth
EXTERN int context_stack_size
EXTERN int within_function
EXTERN char *(* next_symbol_text_func)(struct objfile *)
Define Documentation
#define HASHSIZE
Value:
127             /* Size of things hashed via
                                   hashname().  */
Definition at line 45 of file buildsym.h.
Referenced by hashname(), and scan_file_globals().
#define next_symbol_text (objfile) (*next_symbol_text_func)(objfile)
Definition at line 175 of file buildsym.h.
Referenced by error_type(), parse_partial_symbols(), read_dbx_symtab(), and scan_xcoff_symtab().
#define outermost_context_p () (context_stack_depth == 0)
Definition at line 166 of file buildsym.h.
Referenced by read_func_scope().
#define PENDINGSIZE 100
Definition at line 93 of file buildsym.h.
Referenced by add_symbol_to_list().
Function Documentation
void add_symbol_to_list (struct symbol * symbol, struct pending ** listhead)
Definition at line 137 of file buildsym.c.
References free_pendings, symbol::ginfo, general_symbol_info::name, pending::next, pending::nsyms, PENDINGSIZE, pending::symbol, and xmalloc().
Referenced by coff_read_enum_type(), common_block_end(), define_symbol(), fixup_go_packaging(), merge_symbol_lists(), new_symbol_full(), patch_block_stabs(), process_coff_symbol(), process_xcoff_symbol(), psymtab_to_symtab_1(), and read_enum_type().
void augment_type_symtab (struct objfile * objfile, struct symtab * primary_symtab)
Definition at line 1392 of file buildsym.c.
References _, BLOCK_DICT, symtab::blockvector, BLOCKVECTOR_BLOCK, complaint(), context_stack_depth, dict_add_pending(), file_symbols, GLOBAL_BLOCK, global_symbols, have_line_numbers, reset_symtab_globals(), set_missing_symtab(), STATIC_BLOCK, and symfile_complaints.
Referenced by process_full_type_unit().
void buildsym_init (void)
Definition at line 1558 of file buildsym.c.
References file_symbols, gdb_assert, global_symbols, pending_addrmap_interesting, and using_directives.
Referenced by buildsym_new_init(), dbx_psymtab_to_symtab_1(), process_full_comp_unit(), process_full_type_unit(), and xcoff_psymtab_to_symtab_1().
void buildsym_new_init (void)
Definition at line 1578 of file buildsym.c.
References buildsym_init().
Referenced by coffstab_build_psymtabs(), dbx_new_init(), elf_new_init(), elfstab_build_psymtabs(), mdebug_build_psymtabs(), mipscoff_new_init(), som_new_init(), stabsect_build_psymtabs(), and xcoff_new_init().
struct symtab* end_expandable_symtab (CORE_ADDR end_addr, struct objfile * objfile, int section) [read]
Definition at line 1359 of file buildsym.c.
References end_symtab_from_static_block(), and end_symtab_get_static_block().
Referenced by process_full_type_unit().
struct symtab* end_symtab (CORE_ADDR end_addr, struct objfile * objfile, int section) [read]
Definition at line 1348 of file buildsym.c.
References end_symtab_from_static_block(), and end_symtab_get_static_block().
Referenced by coff_end_symtab(), process_one_symbol(), psymtab_to_symtab_1(), read_ofile_symtab(), and read_xcoff_symtab().
struct symtab* end_symtab_from_static_block (struct block * static_block, struct objfile * objfile, int section, int expandable) [read]
Definition at line 1121 of file buildsym.c.
References ALL_DICT_SYMBOLS, ALL_OBJFILE_SYMTABS, allocate_symtab(), BLOCK_DICT, BLOCK_END, BLOCK_FUNCTION, symtab::block_line_section, symtab::blockvector, BLOCKVECTOR_BLOCK, BLOCKVECTOR_NBLOCKS, compare_line_numbers(), subfile::debugformat, symtab::debugformat, subfile::dirname, symtab::dirname, finish_block_internal(), objfile::flags, GLOBAL_BLOCK, global_symbols, linetable::item, subfile::language, symtab::language, last_source_start_addr, subfile::line_vector, symtab::linetable, symtab::macro_table, make_blockvector(), memcpy(), subfile::name, subfile::next, symtab::next, linetable::nitems, OBJF_REORDERED, objfile::objfile_obstack, pending_macros, symtab::primary, subfile::producer, symtab::producer, qsort, reset_symtab_globals(), set_block_symtab(), objfile::sf, sym_fns::sym_read_linetable, SYMBOL_SYMTAB, subfile::symtab, objfile::symtabs, watch_main_source_file_lossage(), and xfree().
Referenced by end_expandable_symtab(), end_symtab(), and process_full_comp_unit().
struct block* end_symtab_get_static_block (CORE_ADDR end_addr, struct objfile * objfile, int expandable, int required) [read]
Definition at line 1023 of file buildsym.c.
References _, pending_block::block, block_compar(), cleanup_undefined_stabs_types(), complaint(), context_stack_depth, do_cleanups(), file_symbols, finish_block(), finish_block_internal(), finish_global_stabs(), objfile::flags, global_symbols, have_line_numbers, last_source_start_addr, local_symbols, make_cleanup(), context_stack::name, pending_block::next, OBJF_REORDERED, context_stack::old_blocks, pop_context(), qsort, context_stack::start_addr, symfile_complaints, xfree(), and xmalloc().
Referenced by end_expandable_symtab(), end_symtab(), and process_full_comp_unit().
struct symbol* find_symbol_in_list (struct pending * list, char * name, int length) [read]
Definition at line 171 of file buildsym.c.
References pending::next, pending::nsyms, pending::symbol, and SYMBOL_LINKAGE_NAME.
Referenced by patch_block_stabs().
struct block* finish_block (struct symbol * symbol, struct pending ** listhead, struct pending_block * old_blocks, CORE_ADDR start, CORE_ADDR end, struct objfile * objfile) [read]
Definition at line 431 of file buildsym.c.
References finish_block_internal().
Referenced by coff_symtab_read(), end_symtab_get_static_block(), process_one_symbol(), read_func_scope(), read_lexical_block_scope(), and read_xcoff_symtab().
void free_pending_blocks (void)
Definition at line 236 of file buildsym.c.
References pending_block_obstack.
Referenced by dbx_symfile_read(), make_blockvector(), really_free_pendings(), and xcoff_initial_scan().
const char* get_last_source_file (void)
Definition at line 1546 of file buildsym.c.
References last_source_file.
Referenced by coff_symtab_read(), process_linenos(), process_one_symbol(), psymtab_to_symtab_1(), and read_xcoff_symtab().
struct macro_table* get_macro_table (struct objfile * objfile, const char * comp_dir) [read]
Definition at line 843 of file buildsym.c.
References objfile_per_bfd_storage::macro_cache, new_macro_table(), pending_macros, objfile::per_bfd, and objfile_per_bfd_storage::storage_obstack.
Referenced by macro_start_file().
int hashname (const char * name)
Definition at line 1481 of file buildsym.c.
References hash(), and HASHSIZE.
Referenced by common_block_end(), define_symbol(), parse_symbol(), patch_opaque_types(), process_coff_symbol(), and scan_file_globals().
void merge_symbol_lists (struct pending ** srclist, struct pending ** targetlist)
Definition at line 1508 of file buildsym.c.
References add_symbol_to_list(), free_pendings, and merge_symbol_lists().
Referenced by merge_symbol_lists().
void patch_subfile_names (struct subfile * subfile, char * name)
Definition at line 688 of file buildsym.c.
References deduce_language_from_filename(), subfile::dirname, subfile::language, language_unknown, subfile::name, subfile::next, and set_last_source_file().
Referenced by process_one_symbol().
struct context_stack* pop_context (void) [read]
Definition at line 1470 of file buildsym.c.
References context_stack_depth, and gdb_assert.
Referenced by coff_symtab_read(), end_symtab_get_static_block(), process_one_symbol(), read_func_scope(), read_lexical_block_scope(), and read_xcoff_symtab().
char* pop_subfile (void)
Definition at line 739 of file buildsym.c.
References _, internal_error(), name, subfile_stack::name, subfile_stack::next, subfile_stack, and xfree().
Referenced by process_linenos(), and process_one_symbol().
struct context_stack* push_context (int desc, CORE_ADDR valu) [read]
Definition at line 1440 of file buildsym.c.
References context_stack, context_stack_depth, context_stack_size, context_stack::depth, local_symbols, pending_blocks, using_directives, and xrealloc().
Referenced by coff_symtab_read(), process_one_symbol(), read_func_scope(), read_lexical_block_scope(), and read_xcoff_symtab().
void push_subfile (void)
Definition at line 723 of file buildsym.c.
References _, current_subfile, internal_error(), subfile::name, subfile_stack::name, subfile_stack::next, subfile_stack, and xmalloc().
Referenced by process_linenos(), and process_one_symbol().
void really_free_pendings (void * dummy)
Definition at line 196 of file buildsym.c.
References file_symbols, free_macro_table(), free_pending_blocks(), global_symbols, pending::next, pending_addrmap_obstack, and xfree().
Referenced by dbx_psymtab_to_symtab_1(), dbx_symfile_read(), process_full_comp_unit(), process_full_type_unit(), xcoff_initial_scan(), and xcoff_psymtab_to_symtab_1().
void record_block_range (struct block * , CORE_ADDR start, CORE_ADDR end_inclusive)
Definition at line 481 of file buildsym.c.
References addrmap_create_mutable(), addrmap_set_empty(), BLOCK_END, BLOCK_START, pending_addrmap_interesting, and pending_addrmap_obstack.
Referenced by dwarf2_record_block_ranges().
void record_debugformat (const char * format)
Definition at line 1488 of file buildsym.c.
References current_subfile, and subfile::debugformat.
Referenced by coff_start_symtab(), dwarf2_start_symtab(), process_one_symbol(), and read_xcoff_symtab().
void record_line (struct subfile * subfile, int line, CORE_ADDR pc)
Definition at line 759 of file buildsym.c.
References have_line_numbers, INITIAL_LINE_VECTOR_LENGTH, linetable::item, linetable_entry::line, line, subfile::line_vector, subfile::line_vector_length, linetable::nitems, linetable_entry::pc, xmalloc(), and xrealloc().
Referenced by coff_symtab_read(), dwarf_decode_lines_1(), enter_line_range(), enter_linenos(), process_one_symbol(), and psymtab_to_symtab_1().
void record_producer (const char * producer)
Definition at line 1494 of file buildsym.c.
References current_subfile, and subfile::producer.
Referenced by dwarf2_start_symtab().
void restart_symtab (CORE_ADDR start_addr)
Definition at line 875 of file buildsym.c.
References context_stack_depth, context_stack_size, current_subfile, file_symbols, gdb_assert, global_symbols, have_line_numbers, INITIAL_CONTEXT_STACK_SIZE, last_source_start_addr, set_last_source_file(), within_function, and xmalloc().
Referenced by setup_type_unit_groups(), and start_symtab().
void scan_file_globals (struct objfile * objfile)
Definition at line 4608 of file stabsread.c.
References _, ALL_OBJFILE_MSYMBOLS, complaint(), fix_common_block(), global_sym_chain, hash(), hashname(), HASHSIZE, LOC_BLOCK, LOC_STATIC, LOC_UNRESOLVED, memset(), mst_file_bss, mst_file_data, mst_file_text, MSYMBOL_TYPE, objfile_name(), QUIT, SYMBOL_ACLASS_INDEX, SYMBOL_CLASS, SYMBOL_LINKAGE_NAME, SYMBOL_PRINT_NAME, SYMBOL_SECTION, SYMBOL_VALUE_ADDRESS, SYMBOL_VALUE_CHAIN, symfile_complaints, and symfile_objfile.
Referenced by dbx_read_symtab(), mdebug_read_symtab(), and xcoff_read_symtab().
void set_last_source_file (const char * name)
Definition at line 1537 of file buildsym.c.
References last_source_file, and xfree().
Referenced by coff_end_symtab(), coff_symtab_read(), complete_symtab(), parse_partial_symbols(), patch_subfile_names(), read_dbx_symtab(), read_ofile_symtab(), read_xcoff_symtab(), reset_symtab_globals(), restart_symtab(), scan_xcoff_symtab(), and start_symtab().
void start_subfile (const char * name, const char * dirname)
Definition at line 575 of file buildsym.c.
References current_subfile, deduce_language_from_filename(), subfile::dirname, subfile::language, language_c, language_cplus, language_fortran, language_unknown, memset(), subfile::name, subfile::next, subfiles, xfree(), and xmalloc().
Referenced by dwarf2_start_subfile(), process_linenos(), process_one_symbol(), and start_symtab().
void start_symtab (const char * name, const char * dirname, CORE_ADDR start_addr)
Definition at line 862 of file buildsym.c.
References restart_symtab(), set_last_source_file(), and start_subfile().
Referenced by coff_start_symtab(), dwarf2_start_symtab(), process_one_symbol(), and read_xcoff_symtab().
Variable Documentation
EXTERN struct context_stack* context_stack
Definition at line 155 of file buildsym.h.
Referenced by push_context().
EXTERN int context_stack_depth
Definition at line 159 of file buildsym.h.
Referenced by augment_type_symtab(), coff_symtab_read(), end_symtab_get_static_block(), new_symbol_full(), pop_context(), process_one_symbol(), push_context(), read_xcoff_symtab(), and restart_symtab().
EXTERN int context_stack_size
Definition at line 163 of file buildsym.h.
Referenced by push_context(), and restart_symtab().
EXTERN struct subfile* current_subfile
Definition at line 70 of file buildsym.h.
Referenced by coff_symtab_read(), define_symbol(), dwarf_decode_lines(), dwarf_decode_lines_1(), enter_linenos(), process_coff_symbol(), process_linenos(), process_one_symbol(), psymtab_to_symtab_1(), push_subfile(), read_enum_type(), read_type(), record_debugformat(), record_producer(), reset_symtab_globals(), restart_symtab(), setup_type_unit_groups(), and start_subfile().
EXTERN struct pending* file_symbols
Definition at line 106 of file buildsym.h.
Referenced by augment_type_symtab(), build_type_psymtabs_reader(), buildsym_init(), cleanup_undefined_types_1(), coff_read_enum_type(), define_symbol(), end_symtab_get_static_block(), new_symbol_full(), process_coff_symbol(), process_full_comp_unit(), process_full_type_unit(), process_psymtab_comp_unit_reader(), process_xcoff_symbol(), read_enum_type(), read_func_scope(), read_type(), really_free_pendings(), and restart_symtab().
EXTERN struct pending* global_symbols
Definition at line 110 of file buildsym.h.
Referenced by augment_type_symtab(), buildsym_init(), define_symbol(), end_symtab_from_static_block(), end_symtab_get_static_block(), finish_global_stabs(), fixup_go_packaging(), new_symbol_full(), patch_block_stabs(), process_coff_symbol(), process_xcoff_symbol(), really_free_pendings(), and restart_symtab().
EXTERN CORE_ADDR last_source_start_addr
Definition at line 51 of file buildsym.h.
Referenced by aix_process_linenos(), coff_end_symtab(), end_symtab_from_static_block(), end_symtab_get_static_block(), process_one_symbol(), read_ofile_symtab(), and restart_symtab().
EXTERN struct pending* local_symbols
Definition at line 114 of file buildsym.h.
Referenced by coff_read_enum_type(), coff_symtab_read(), common_block_end(), common_block_start(), define_symbol(), end_symtab_get_static_block(), process_coff_symbol(), process_one_symbol(), psymtab_to_symtab_1(), push_context(), read_enum_type(), read_func_scope(), read_lexical_block_scope(), and read_xcoff_symtab().
EXTERN char*(* next_symbol_text_func)(struct objfile *)
Definition at line 179 of file buildsym.h.
Referenced by dbx_read_symtab(), mdebug_read_symtab(), parse_partial_symbols(), read_dbx_symtab(), scan_xcoff_symtab(), and xcoff_read_symtab().
EXTERN unsigned char processing_acc_compilation
Definition at line 83 of file buildsym.h.
Referenced by coffstab_build_psymtabs(), elfstab_build_psymtabs(), read_dbx_symtab(), read_ofile_symtab(), and stabsect_build_psymtabs().
EXTERN unsigned char processing_gcc_compilation
Definition at line 75 of file buildsym.h.
Referenced by define_symbol(), dwarf2_start_symtab(), init_go32_ops(), parse_partial_symbols(), parse_procedure(), process_one_symbol(), psymtab_to_symtab_1(), and read_ofile_symtab().
EXTERN unsigned int symnum
Definition at line 87 of file buildsym.h.
Referenced by add_old_header_file(), coff_read_enum_type(), coff_read_struct_type(), coff_symtab_read(), dbx_lookup_type(), dbx_next_symbol_text(), find_corresponding_bincl_psymtab(), parse_partial_symbols(), process_one_symbol(), read_cpp_abbrev(), read_dbx_symtab(), read_ofile_symtab(), read_one_sym(), read_type(), read_xcoff_symtab(), set_namestring(), and xcoff_next_symbol_text().
EXTERN struct using_direct* using_directives
Definition at line 118 of file buildsym.h.
Referenced by buildsym_init(), cp_add_using_directive(), finish_block_internal(), push_context(), read_func_scope(), and read_lexical_block_scope().
EXTERN int within_function
Definition at line 171 of file buildsym.h.
Referenced by coff_read_enum_type(), coff_symtab_read(), define_symbol(), process_coff_symbol(), process_one_symbol(), process_xcoff_symbol(), read_enum_type(), read_xcoff_symtab(), and restart_symtab().