GDB (xrefs): /home/stan/gdb/src/gdb/build-id.h File Reference
/home/stan/gdb/src/gdb/build-id.h File Reference
Functions
int build_id_verify (bfd *abfd, size_t check_len, const bfd_byte *check)
bfd * build_id_to_debug_bfd (size_t build_id_len, const bfd_byte *build_id)
char * find_separate_debug_file_by_buildid (struct objfile *objfile)
Function Documentation
bfd* build_id_to_debug_bfd (size_t build_id_len, const bfd_byte * build_id)
Definition at line 74 of file build-id.c.
References build_id_verify(), debug_file_directory, do_cleanups(), gdb_bfd_open_maybe_remote(), gdb_bfd_unref(), make_cleanup_free_char_ptr_vec(), memcpy(), size, VEC, and VEC_iterate.
Referenced by dwarf2_get_dwz_file(), and find_separate_debug_file_by_buildid().
int build_id_verify (bfd * abfd, size_t check_len, const bfd_byte * check)
Definition at line 51 of file build-id.c.
References _, build_id_bfd_get(), memcmp(), and warning().
Referenced by build_id_to_debug_bfd(), and dwarf2_get_dwz_file().
char* find_separate_debug_file_by_buildid (struct objfile * objfile)
Definition at line 140 of file build-id.c.
References _, build_id_bfd_get(), build_id_to_debug_bfd(), gdb_bfd_unref(), objfile::obfd, objfile_name(), and warning().
Referenced by elf_symfile_read().