GDB (xrefs): /home/stan/gdb/src/gdb/c-lang.h File Reference
/home/stan/gdb/src/gdb/c-lang.h File Reference
#include "value.h"
#include "macroexp.h"
#include "parser-defs.h"
Enumerations
enum c_string_type {
C_STRING = 0, C_WIDE_STRING = 1, C_STRING_16 = 2, C_STRING_32 = 3,
C_CHAR = 4, C_WIDE_CHAR = 5, C_CHAR_16 = 6, C_CHAR_32 = 7
}
Functions
int c_parse (void)
void c_error (char *)
int c_parse_escape (const char **, struct obstack *)
void c_print_type (struct type *, const char *, struct ui_file *, int, int, const struct type_print_options *)
void c_print_typedef (struct type *, struct symbol *, struct ui_file *)
void c_val_print (struct type *, const gdb_byte *, int, CORE_ADDR, struct ui_file *, int, const struct value *, const struct value_print_options *)
void c_value_print (struct value *, struct ui_file *, const struct value_print_options *)
struct value * evaluate_subexp_c (struct type *expect_type, struct expression *exp, int *pos, enum noside noside)
void c_printchar (int, struct type *, struct ui_file *)
void c_printstr (struct ui_file *stream, struct type *elttype, const gdb_byte *string, unsigned int length, const char *user_encoding, int force_ellipses, const struct value_print_options *options)
void c_language_arch_info (struct gdbarch *gdbarch, struct language_arch_info *lai)
void c_emit_char (int c, struct type *type, struct ui_file *stream, int quoter)
void c_type_print_base (struct type *, struct ui_file *, int, int, const struct type_print_options *)
void cp_print_class_member (const gdb_byte *, struct type *, struct ui_file *, char *)
void cp_print_value_fields (struct type *, struct type *, const gdb_byte *, int, CORE_ADDR, struct ui_file *, int, const struct value *, const struct value_print_options *, struct type **, int)
void cp_print_value_fields_rtti (struct type *, const gdb_byte *, int, CORE_ADDR, struct ui_file *, int, const struct value *, const struct value_print_options *, struct type **, int)
int cp_is_vtbl_ptr_type (struct type *)
int cp_is_vtbl_member (struct type *)
int c_textual_element_type (struct type *, char)
Variables
struct exp_descriptor exp_descriptor_c
struct op_print c_op_print_tab []
Enumeration Type Documentation
enum c_string_type
Enumerator:
C_STRING
C_WIDE_STRING
C_STRING_16
C_STRING_32
C_CHAR
C_WIDE_CHAR
C_CHAR_16
C_CHAR_32
Definition at line 36 of file c-lang.h.
Function Documentation
void c_emit_char (int c, struct type * type, struct ui_file * stream, int quoter)
Definition at line 148 of file c-lang.c.
References classify_type(), encoding, generic_emit_char(), and get_type_arch().
void c_error (char *)
void c_language_arch_info (struct gdbarch * gdbarch, struct language_arch_info * lai)
Definition at line 768 of file c-lang.c.
References language_arch_info::bool_type_default, builtin_type::builtin_char, builtin_type::builtin_complex, builtin_type::builtin_decdouble, builtin_type::builtin_decfloat, builtin_type::builtin_declong, builtin_type::builtin_double, builtin_type::builtin_double_complex, builtin_type::builtin_float, builtin_type::builtin_int, builtin_type::builtin_long, builtin_type::builtin_long_double, builtin_type::builtin_long_long, builtin_type::builtin_short, builtin_type::builtin_signed_char, builtin_type(), builtin_type::builtin_unsigned_char, builtin_type::builtin_unsigned_int, builtin_type::builtin_unsigned_long, builtin_type::builtin_unsigned_long_long, builtin_type::builtin_unsigned_short, builtin_type::builtin_void, c_primitive_type_char, c_primitive_type_complex, c_primitive_type_decdouble, c_primitive_type_decfloat, c_primitive_type_declong, c_primitive_type_double, c_primitive_type_double_complex, c_primitive_type_float, c_primitive_type_int, c_primitive_type_long, c_primitive_type_long_double, c_primitive_type_long_long, c_primitive_type_short, c_primitive_type_signed_char, c_primitive_type_unsigned_char, c_primitive_type_unsigned_int, c_primitive_type_unsigned_long, c_primitive_type_unsigned_long_long, c_primitive_type_unsigned_short, c_primitive_type_void, GDBARCH_OBSTACK_CALLOC, nr_c_primitive_types, language_arch_info::primitive_type_vector, and language_arch_info::string_char_type.
int c_parse (void)
Definition at line 6209 of file c-exp.c.
References default_macro_scope(), do_cleanups(), expansion_obstack, expression_context_block, expression_context_pc, find_pc_line(), free_current_contents(), gdb_assert, make_cleanup(), make_cleanup_obstack_free(), make_cleanup_restore_integer(), parser_debug, sal_macro_scope(), scan_macro_cleanup(), user_macro_scope(), VEC_free, and yyparse.
int c_parse_escape (const char ** , struct obstack *)
Definition at line 5040 of file c-exp.c.
References _, error(), HOST_ESCAPE_CHAR, len, and obstack_grow_str.
Referenced by get_character_constant(), get_string_literal(), and parse_string_or_char().
void c_print_type (struct type * , const char * , struct ui_file * , int , int , const struct type_print_options *)
Definition at line 82 of file c-typeprint.c.
References c_type_print_base(), c_type_print_varspec_prefix(), c_type_print_varspec_suffix(), CHECK_TYPEDEF, code, find_typedef_in_hash(), fputs_filtered(), strchr(), TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_FUNC, TYPE_CODE_MEMBERPTR, TYPE_CODE_METHOD, TYPE_CODE_METHODPTR, TYPE_CODE_PTR, TYPE_CODE_REF, TYPE_NAME, and TYPE_VECTOR.
Referenced by ada_print_type(), c_type_print_args(), c_type_print_base(), c_type_print_template_args(), cp_type_print_method_args(), dwarf2_compute_name(), gnuv3_print_method_ptr(), go_print_type(), and opencl_print_type().
void c_print_typedef (struct type * , struct symbol * , struct ui_file *)
Definition at line 145 of file c-typeprint.c.
References CHECK_TYPEDEF, fprintf_filtered(), SYMBOL_LINKAGE_NAME, SYMBOL_PRINT_NAME, SYMBOL_TYPE, TYPE_CODE, TYPE_CODE_TYPEDEF, TYPE_NAME, and type_print().
void c_printchar (int , struct type * , struct ui_file *)
Definition at line 158 of file c-lang.c.
References C_CHAR, C_CHAR_16, C_CHAR_32, C_WIDE_CHAR, classify_type(), fputc_filtered(), get_type_arch(), and LA_EMIT_CHAR.
Referenced by dwarf2_compute_name().
void c_printstr (struct ui_file * stream, struct type * elttype, const gdb_byte * string, unsigned int length, const char * user_encoding, int force_ellipses, const struct value_print_options * options)
Definition at line 191 of file c-lang.c.
References C_CHAR, C_STRING, C_STRING_16, C_STRING_32, C_WIDE_STRING, classify_type(), encoding, fputs_filtered(), generic_printstr(), and get_type_arch().
int c_textual_element_type (struct type * , char)
Definition at line 57 of file c-valprint.c.
References check_typedef(), textual_name(), type, TYPE_CODE, TYPE_CODE_CHAR, TYPE_CODE_INT, TYPE_CODE_TYPEDEF, TYPE_LENGTH, TYPE_NAME, TYPE_NOTTEXT, and TYPE_TARGET_TYPE.
Referenced by c_get_string(), c_val_print(), and gen_traced_pop().
void c_type_print_base (struct type * , struct ui_file * , int , int , const struct type_print_options *)
Definition at line 830 of file c-typeprint.c.
References _, add_template_parameters(), c_print_type(), c_type_print_base(), c_type_print_modifier(), c_type_print_template_args(), CHECK_TYPEDEF, copy_typedef_hash(), cp_type_print_derivation_info(), cp_type_print_method_args(), create_typedef_hash(), do_cleanups(), field_is_static(), flags, fprintf_filtered(), fprintfi_filtered(), fputs_filtered(), gdb_assert, gdb_demangle(), gdb_mangle_name(), get_vptr_fieldno(), cleanup_check::is_constructor(), is_constructor_name(), is_destructor_name(), is_type_conversion_operator(), len, type::length, type_print_options::local_typedefs, LONGEST, make_cleanup(), make_cleanup_free_typedef_hash(), name, null_cleanup(), p, plongest(), type_print_options::print_methods, print_name_maybe_canonical(), print_spaces_filtered(), type_print_options::print_typedefs, QUIT, type_print_options::raw, recursively_update_typedef_hash(), remove_qualifiers(), strstr(), TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_ENUM, TYPE_CODE_ERROR, TYPE_CODE_FUNC, TYPE_CODE_MEMBERPTR, TYPE_CODE_METHOD, TYPE_CODE_METHODPTR, TYPE_CODE_NAMESPACE, TYPE_CODE_PTR, TYPE_CODE_RANGE, TYPE_CODE_REF, TYPE_CODE_STRUCT, TYPE_CODE_TYPEDEF, TYPE_CODE_UNDEF, TYPE_CODE_UNION, TYPE_CODE_VOID, TYPE_DECLARED_CLASS, TYPE_ERROR_NAME, TYPE_FIELD, TYPE_FIELD_ARTIFICIAL, TYPE_FIELD_BITSIZE, TYPE_FIELD_ENUMVAL, TYPE_FIELD_NAME, TYPE_FIELD_PACKED, TYPE_FIELD_PRIVATE, TYPE_FIELD_PROTECTED, TYPE_FIELD_TYPE, TYPE_FN_FIELD_ARTIFICIAL, TYPE_FN_FIELD_CONSTRUCTOR, TYPE_FN_FIELD_PHYSNAME, TYPE_FN_FIELD_PRIVATE, TYPE_FN_FIELD_PROTECTED, TYPE_FN_FIELD_STATIC_P, TYPE_FN_FIELD_STUB, TYPE_FN_FIELD_TYPE, TYPE_FN_FIELD_VIRTUAL_P, TYPE_FN_FIELDLIST1, TYPE_FN_FIELDLIST_LENGTH, TYPE_FN_FIELDLIST_NAME, TYPE_N_BASECLASSES, TYPE_NAME, type_name_no_tag(), TYPE_NFIELDS, TYPE_NFN_FIELDS, TYPE_STUB, TYPE_TAG_NAME, TYPE_TARGET_TYPE, TYPE_TYPEDEF_FIELD_COUNT, TYPE_TYPEDEF_FIELD_NAME, TYPE_TYPEDEF_FIELD_TYPE, wrap_here(), xfree(), and xmalloc().
Referenced by c_print_type(), c_type_print_base(), c_type_print_varspec_prefix(), cp_print_class_member(), and java_type_print_base().
void c_val_print (struct type * , const gdb_byte * , int , CORE_ADDR , struct ui_file * , int , const struct value * , const struct value_print_options *)
Definition at line 134 of file c-valprint.c.
References _, value_print_options::addressprint, gdbarch::byte_order, c_textual_element_type(), check_typedef(), CHECK_TYPEDEF, common_val_print(), cp_is_vtbl_member(), cp_is_vtbl_ptr_type(), cp_print_class_member(), cp_print_value_fields_rtti(), cplus_print_method_ptr(), current_language, demangle, error(), extract_typed_address(), extract_unsigned_integer(), value_print_options::format, fprintf_filtered(), fputs_filtered(), gdb_flush(), gdbarch_byte_order(), generic_val_print(), get_array_bounds(), get_type_arch(), LA_PRINT_CHAR, LA_PRINT_STRING, len, LONGEST, lookup_minimal_symbol_by_pc(), lookup_symbol(), bound_minimal_symbol::minsym, offset, value_print_options::output_format, paddress(), value_print_options::prettyformat, value_print_options::prettyformat_arrays, print_address_demangle(), print_function_pointer_address(), value_print_options::print_max, print_spaces_filtered(), print_unpacked_pointer(), value_print_options::stop_print_at_null, SYMBOL_LINKAGE_NAME, value_print_options::symbol_print, SYMBOL_PRINT_NAME, SYMBOL_TYPE, SYMBOL_VALUE_ADDRESS, type, TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_BOOL, TYPE_CODE_CHAR, TYPE_CODE_COMPLEX, TYPE_CODE_DECFLOAT, TYPE_CODE_ENUM, TYPE_CODE_ERROR, TYPE_CODE_FLAGS, TYPE_CODE_FLT, TYPE_CODE_FUNC, TYPE_CODE_INT, TYPE_CODE_MEMBERPTR, TYPE_CODE_METHOD, TYPE_CODE_METHODPTR, TYPE_CODE_PTR, TYPE_CODE_RANGE, TYPE_CODE_REF, TYPE_CODE_STRUCT, TYPE_CODE_UNDEF, TYPE_CODE_UNION, TYPE_CODE_VOID, TYPE_FIELD_BITPOS, TYPE_FIELD_TYPE, TYPE_LENGTH, TYPE_TARGET_TYPE, ULONGEST, value_print_options::unionprint, unpack_long(), unpack_pointer(), val_print_array_elements(), val_print_scalar_formatted(), val_print_string(), val_print_type_code_int(), value_at(), value_bits_valid(), value_bytes_available(), VAR_DOMAIN, VTBL_FNADDR_OFFSET, and value_print_options::vtblprint.
Referenced by ada_val_print_1(), d_val_print(), go_val_print(), and java_val_print().
void c_value_print (struct value * , struct ui_file * , const struct value_print_options *)
Definition at line 459 of file c-valprint.c.
References _, check_typedef(), current_language, value_print_options::deref_ref, fprintf_filtered(), value_print_options::objectprint, textual_name(), type, TYPE_CODE, TYPE_CODE_CLASS, TYPE_CODE_PTR, TYPE_CODE_REF, TYPE_NAME, type_print(), TYPE_TARGET_TYPE, val_print(), value_addr(), value_address(), value_as_address(), value_contents_for_printing(), value_embedded_offset(), value_enclosing_type(), value_entirely_available(), value_from_pointer(), value_full_object(), value_ind(), value_initialized(), value_ref(), value_rtti_indirect_type(), value_rtti_type(), and value_type().
int cp_is_vtbl_member (struct type *)
Definition at line 110 of file cp-valprint.c.
References cp_is_vtbl_ptr_type(), TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_PTR, TYPE_CODE_STRUCT, and TYPE_TARGET_TYPE.
Referenced by c_val_print().
int cp_is_vtbl_ptr_type (struct type *)
Definition at line 99 of file cp-valprint.c.
References type_name_no_tag(), and vtbl_ptr_name.
Referenced by c_val_print(), and cp_is_vtbl_member().
void cp_print_class_member (const gdb_byte * , struct type * , struct ui_file * , char *)
Definition at line 761 of file cp-valprint.c.
References c_type_print_base(), cp_find_class_member(), extract_signed_integer(), fprintf_filtered(), fputs_filtered(), gdbarch_byte_order(), get_type_arch(), LONGEST, name, TYPE_DOMAIN_TYPE, TYPE_FIELD_NAME, TYPE_LENGTH, type_name_no_tag(), and type_print_raw_options.
Referenced by c_val_print().
void cp_print_value_fields (struct type * , struct type * , const gdb_byte * , int , CORE_ADDR , struct ui_file * , int , const struct value * , const struct value_print_options * , struct type ** , int)
Definition at line 158 of file cp-valprint.c.
References _, annotate_field_begin(), annotate_field_end(), annotate_field_name_end(), annotate_field_value(), CHECK_TYPEDEF, common_val_print(), cp_print_static_field(), cp_print_value(), current_language, value_print_options::deref_ref, dont_print_stat_array_obstack, dont_print_statmem_obstack, extract_typed_address(), field_is_static(), fprintf_filtered(), fprintf_symbol_filtered(), fputs_filtered(), get_type_arch(), get_vptr_fieldno(), language_defn::la_language, len, gdb_exception::message, n_spaces(), value_print_options::prettyformat, print_function_pointer_address(), print_spaces_filtered(), gdb_exception::reason, RETURN_MASK_ERROR, value_print_options::static_field_print, TRY_CATCH, TYPE_FIELD, TYPE_FIELD_BITPOS, TYPE_FIELD_BITSIZE, TYPE_FIELD_IGNORE, TYPE_FIELD_NAME, TYPE_FIELD_PACKED, TYPE_FIELD_TYPE, TYPE_N_BASECLASSES, type_name_no_tag(), TYPE_NFIELDS, val_print(), val_print_optimized_out(), valprint_check_validity(), value_bits_synthetic_pointer(), value_bits_valid(), value_field_bitfield(), value_static_field(), and wrap_here().
Referenced by cp_print_static_field(), cp_print_value(), cp_print_value_fields_rtti(), and m2_val_print().
void cp_print_value_fields_rtti (struct type * , const gdb_byte * , int , CORE_ADDR , struct ui_file * , int , const struct value * , const struct value_print_options * , struct type ** , int)
Definition at line 427 of file cp-valprint.c.
References cp_print_value_fields(), type, TYPE_LENGTH, value_bits_valid(), value_from_contents_and_address(), and value_rtti_type().
Referenced by c_val_print().
struct value* evaluate_subexp_c (struct type * expect_type, struct expression * exp, int * pos, enum noside noside) [read]
Definition at line 549 of file c-lang.c.
References _, allocate_value(), BYTES_TO_EXP_ELEM, C_CHAR, C_STRING, C_STRING_16, C_STRING_32, C_WIDE_STRING, charset_for_string_type(), check_typedef(), do_cleanups(), expression::elts, error(), EVAL_SKIP, evaluate_subexp_standard(), expression::gdbarch, get_discrete_bounds(), internal_error(), expression::language_defn, language_string_char_type(), len, exp_element::longconst, LONGEST, longest_to_int(), lookup_typename(), make_cleanup_obstack_free(), memcpy(), exp_element::opcode, parse_one_string(), exp_element::string, type, TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_CHAR, TYPE_CODE_INT, TYPE_INDEX_TYPE, TYPE_LENGTH, TYPE_TARGET_TYPE, unpack_long(), value_contents_raw(), value_cstring(), and value_from_longest().
Referenced by evaluate_subexp_opencl().
Variable Documentation
struct op_print c_op_print_tab[]
Definition at line 708 of file c-lang.c.
struct exp_descriptor exp_descriptor_c
Definition at line 801 of file c-lang.c.