GDB (xrefs): /home/stan/gdb/src/gdb/c-valprint.c File Reference
/home/stan/gdb/src/gdb/c-valprint.c File Reference
#include "defs.h"
#include "gdb_string.h"
#include "symtab.h"
#include "gdbtypes.h"
#include "expression.h"
#include "value.h"
#include "valprint.h"
#include "language.h"
#include "c-lang.h"
#include "cp-abi.h"
#include "target.h"
Functions
static int textual_name (const char *name)
int c_textual_element_type (struct type *type, char format)
void c_val_print (struct type *type, const gdb_byte *valaddr, int embedded_offset, CORE_ADDR address, struct ui_file *stream, int recurse, const struct value *original_value, const struct value_print_options *options)
void c_value_print (struct value *val, struct ui_file *stream, const struct value_print_options *options)
Variables
static struct
generic_val_print_decorations c_decorations
Function Documentation
int c_textual_element_type (struct type * type, char format)
Definition at line 57 of file c-valprint.c.
References check_typedef(), textual_name(), type, TYPE_CODE, TYPE_CODE_CHAR, TYPE_CODE_INT, TYPE_CODE_TYPEDEF, TYPE_LENGTH, TYPE_NAME, TYPE_NOTTEXT, and TYPE_TARGET_TYPE.
Referenced by c_get_string(), c_val_print(), and gen_traced_pop().
void c_val_print (struct type * type, const gdb_byte * valaddr, int embedded_offset, CORE_ADDR address, struct ui_file * stream, int recurse, const struct value * original_value, const struct value_print_options * options)
Definition at line 134 of file c-valprint.c.
References _, value_print_options::addressprint, gdbarch::byte_order, c_textual_element_type(), check_typedef(), CHECK_TYPEDEF, common_val_print(), cp_is_vtbl_member(), cp_is_vtbl_ptr_type(), cp_print_class_member(), cp_print_value_fields_rtti(), cplus_print_method_ptr(), current_language, demangle, error(), extract_typed_address(), extract_unsigned_integer(), value_print_options::format, fprintf_filtered(), fputs_filtered(), gdb_flush(), gdbarch_byte_order(), generic_val_print(), get_array_bounds(), get_type_arch(), LA_PRINT_CHAR, LA_PRINT_STRING, len, LONGEST, lookup_minimal_symbol_by_pc(), lookup_symbol(), bound_minimal_symbol::minsym, offset, value_print_options::output_format, paddress(), value_print_options::prettyformat, value_print_options::prettyformat_arrays, print_address_demangle(), print_function_pointer_address(), value_print_options::print_max, print_spaces_filtered(), print_unpacked_pointer(), value_print_options::stop_print_at_null, SYMBOL_LINKAGE_NAME, value_print_options::symbol_print, SYMBOL_PRINT_NAME, SYMBOL_TYPE, SYMBOL_VALUE_ADDRESS, type, TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_BOOL, TYPE_CODE_CHAR, TYPE_CODE_COMPLEX, TYPE_CODE_DECFLOAT, TYPE_CODE_ENUM, TYPE_CODE_ERROR, TYPE_CODE_FLAGS, TYPE_CODE_FLT, TYPE_CODE_FUNC, TYPE_CODE_INT, TYPE_CODE_MEMBERPTR, TYPE_CODE_METHOD, TYPE_CODE_METHODPTR, TYPE_CODE_PTR, TYPE_CODE_RANGE, TYPE_CODE_REF, TYPE_CODE_STRUCT, TYPE_CODE_UNDEF, TYPE_CODE_UNION, TYPE_CODE_VOID, TYPE_FIELD_BITPOS, TYPE_FIELD_TYPE, TYPE_LENGTH, TYPE_TARGET_TYPE, ULONGEST, value_print_options::unionprint, unpack_long(), unpack_pointer(), val_print_array_elements(), val_print_scalar_formatted(), val_print_string(), val_print_type_code_int(), value_at(), value_bits_valid(), value_bytes_available(), VAR_DOMAIN, VTBL_FNADDR_OFFSET, and value_print_options::vtblprint.
Referenced by ada_val_print_1(), d_val_print(), go_val_print(), and java_val_print().
void c_value_print (struct value * val, struct ui_file * stream, const struct value_print_options * options)
Definition at line 459 of file c-valprint.c.
References _, check_typedef(), current_language, value_print_options::deref_ref, fprintf_filtered(), value_print_options::objectprint, textual_name(), type, TYPE_CODE, TYPE_CODE_CLASS, TYPE_CODE_PTR, TYPE_CODE_REF, TYPE_NAME, type_print(), TYPE_TARGET_TYPE, val_print(), value_addr(), value_address(), value_as_address(), value_contents_for_printing(), value_embedded_offset(), value_enclosing_type(), value_entirely_available(), value_from_pointer(), value_full_object(), value_ind(), value_initialized(), value_ref(), value_rtti_indirect_type(), value_rtti_type(), and value_type().
static int textual_name (const char * name) [static]
Definition at line 38 of file c-valprint.c.
Referenced by c_textual_element_type(), and c_value_print().
Variable Documentation
struct generic_val_print_decorations c_decorations [static]
Initial value:
{
  "",
  " + ",
  " * I",
  "true",
  "false",
  "void"
}
Definition at line 120 of file c-valprint.c.