GDB (xrefs): /home/stan/gdb/src/gdb/charset.h File Reference
/home/stan/gdb/src/gdb/charset.h File Reference
Defines
#define HOST_ESCAPE_CHAR 27
Enumerations
enum transliterations { translit_none, translit_char }
enum wchar_iterate_result { wchar_iterate_ok, wchar_iterate_invalid, wchar_iterate_incomplete, wchar_iterate_eof }
Functions
const char * host_charset (void)
const char * target_charset (struct gdbarch *gdbarch)
const char * target_wide_charset (struct gdbarch *gdbarch)
void convert_between_encodings (const char *from, const char *to, const gdb_byte *bytes, unsigned int num_bytes, int width, struct obstack *output, enum transliterations translit)
struct wchar_iterator * make_wchar_iterator (const gdb_byte *input, size_t bytes, const char *charset, size_t width)
struct cleanup * make_cleanup_wchar_iterator (struct wchar_iterator *iter)
int wchar_iterate (struct wchar_iterator *iter, enum wchar_iterate_result *out_result, gdb_wchar_t **out_chars, const gdb_byte **ptr, size_t *len)
char host_letter_to_control_character (char c)
int host_hex_value (char c)
Define Documentation
#define HOST_ESCAPE_CHAR 27
Definition at line 139 of file charset.h.
Referenced by c_parse_escape().
Enumeration Type Documentation
enum transliterations
Enumerator:
translit_none
translit_char
Definition at line 41 of file charset.h.
enum wchar_iterate_result
Enumerator:
wchar_iterate_ok
wchar_iterate_invalid
wchar_iterate_incomplete
wchar_iterate_eof
Definition at line 72 of file charset.h.
Function Documentation
void convert_between_encodings (const char * from, const char * to, const gdb_byte * bytes, unsigned int num_bytes, int width, struct obstack * output, enum transliterations translit)
Definition at line 469 of file charset.c.
References _, cleanup_iconv(), do_cleanups(), EILSEQ, error(), iconv, ICONV_CONST, iconv_open, iconv_t, make_cleanup(), obstack_grow_str, perror_with_name(), translit_none, and xsnprintf().
Referenced by convert_ucn(), generic_emit_char(), generic_printstr(), host_char_to_target(), parse_one_string(), printf_wide_c_string(), and ui_printf().
const char* host_charset (void)
Definition at line 392 of file charset.c.
References auto_host_charset_name, and host_charset_name.
Referenced by bppy_get_commands(), bppy_get_condition(), bppy_get_expression(), bppy_get_location(), cmdpy_function(), frapy_name(), gdbpy_frame_stop_reason_string(), generic_emit_char(), generic_printstr(), host_char_to_target(), objfpy_get_filename(), parse_one_string(), printf_wide_c_string(), pspy_get_filename(), python_string_to_host_string(), python_string_to_unicode(), stpy_fullname(), stpy_get_filename(), typy_str(), ui_printf(), validate(), and VEC().
int host_hex_value (char c)
Definition at line 446 of file charset.c.
References gdb_assert.
Referenced by convert_hex(), convert_octal(), convert_ucn(), mi_parse_escape(), and parse_escape().
char host_letter_to_control_character (char c)
Definition at line 435 of file charset.c.
struct cleanup* make_cleanup_wchar_iterator (struct wchar_iterator * iter) [read]
Definition at line 621 of file charset.c.
References do_cleanup_iterator(), and make_cleanup().
Referenced by generic_emit_char(), and generic_printstr().
struct wchar_iterator* make_wchar_iterator (const gdb_byte * input, size_t bytes, const char * charset, size_t width) [read]
Definition at line 588 of file charset.c.
References _, wchar_iterator::bytes, wchar_iterator::desc, iconv_open, iconv_t, wchar_iterator::input, INTERMEDIATE_ENCODING, wchar_iterator::out, wchar_iterator::out_size, perror_with_name(), and wchar_iterator::width.
Referenced by generic_emit_char(), and generic_printstr().
const char* target_charset (struct gdbarch * gdbarch)
Definition at line 400 of file charset.c.
References gdbarch_auto_charset(), and target_charset_name.
Referenced by charset_for_string_type(), f_get_encoding(), host_char_to_target(), java_get_encoding(), parse_escape(), unicode_to_target_python_string(), unicode_to_target_string(), and validate().
const char* target_wide_charset (struct gdbarch * gdbarch)
Definition at line 408 of file charset.c.
References gdbarch::byte_order, gdbarch_auto_wide_charset(), gdbarch_byte_order(), set_be_le_names(), target_wide_charset_be_name, target_wide_charset_le_name, and target_wide_charset_name.
Referenced by charset_for_string_type(), printf_wide_c_string(), and ui_printf().
int wchar_iterate (struct wchar_iterator * iter, enum wchar_iterate_result * out_result, gdb_wchar_t ** out_chars, const gdb_byte ** ptr, size_t * len)
Definition at line 627 of file charset.c.
References _, wchar_iterator::bytes, wchar_iterator::desc, EILSEQ, iconv, ICONV_CONST, wchar_iterator::input, wchar_iterator::out, wchar_iterator::out_size, perror_with_name(), wchar_iterate_eof, wchar_iterate_incomplete, wchar_iterate_invalid, wchar_iterate_ok, wchar_iterator::width, and xrealloc().
Referenced by count_next_character(), and generic_emit_char().