GDB (xrefs): gdb.command.explore.CompoundExplorer Class Reference
gdb.command.explore.CompoundExplorer Class Reference
Static Public Member Functions
def explore_expr
def explore_type
def explore_expr
def explore_type
Static Private Member Functions
def _print_fields
def _get_real_field_count
def _print_fields
def _get_real_field_count
Detailed Description
Internal class used to explore struct, classes and unions.
Definition at line 367 of file explore.py.
Member Function Documentation
def gdb.command.explore.CompoundExplorer._get_real_field_count (fields) [static, private]
Definition at line 383 of file explore.py.
Referenced by gdb.command.explore.CompoundExplorer._get_real_field_count().
def gdb.command.explore.CompoundExplorer._get_real_field_count (fields) [static, private]
Definition at line 383 of file explore.py.
References gdb.command.explore.CompoundExplorer._get_real_field_count().
def gdb.command.explore.CompoundExplorer._print_fields (print_list) [static, private]
Internal function which prints the fields of a struct/class/union.
Definition at line 371 of file explore.py.
References len.
Referenced by gdb.command.explore.CompoundExplorer._print_fields().
def gdb.command.explore.CompoundExplorer._print_fields (print_list) [static, private]
Internal function which prints the fields of a struct/class/union.
Definition at line 371 of file explore.py.
References gdb.command.explore.CompoundExplorer._print_fields(), and len.
def gdb.command.explore.CompoundExplorer.explore_expr (expr, value, is_child) [static]
Function to explore structs/classes and union values.
See Explorer.explore_expr for more information.
Definition at line 392 of file explore.py.
References gdb.command.explore.CompoundExplorer.explore_expr(), and gdb::command::explore.raw_input.
def gdb.command.explore.CompoundExplorer.explore_expr (expr, value, is_child) [static]
Function to explore structs/classes and union values.
See Explorer.explore_expr for more information.
Definition at line 392 of file explore.py.
References gdb::command::explore.raw_input.
Referenced by gdb.command.explore.CompoundExplorer.explore_expr().
def gdb.command.explore.CompoundExplorer.explore_type (name, datatype, is_child) [static]
Function to explore struct/class and union types.
See Explorer.explore_type for more information.
Definition at line 473 of file explore.py.
References len, and gdb::command::explore.raw_input.
Referenced by gdb.command.explore.CompoundExplorer.explore_type().
def gdb.command.explore.CompoundExplorer.explore_type (name, datatype, is_child) [static]
Function to explore struct/class and union types.
See Explorer.explore_type for more information.
Definition at line 473 of file explore.py.
References gdb.command.explore.CompoundExplorer.explore_type(), len, and gdb::command::explore.raw_input.
The documentation for this class was generated from the following files:
/home/stan/gdb/src/gdb/python/lib/gdb/command/explore.py
/home/stan/gdb/linux/gdb/data-directory/python/gdb/command/explore.py