GDB (xrefs): cleanup_check.CleanupChecker Class Reference
cleanup_check.CleanupChecker Class Reference
Public Member Functions
def __init__
def guess_bb_location
def compute_master
def traverse_bbs
def check_cleanups
Public Attributes
fun
seen_edges
bad_returns
master_cleanups
cleanup_aware
only_do_cleanups_seen
is_constructor
is_special_constructor
Detailed Description
Definition at line 193 of file cleanup_check.py.
Constructor & Destructor Documentation
def cleanup_check.CleanupChecker.__init__ (self, fun)
Definition at line 194 of file cleanup_check.py.
Member Function Documentation
def cleanup_check.CleanupChecker.check_cleanups (self)
Definition at line 288 of file cleanup_check.py.
def cleanup_check.CleanupChecker.compute_master (self, bb, bb_from, master_cleanup)
Definition at line 213 of file cleanup_check.py.
Referenced by cleanup_check.CleanupChecker.traverse_bbs().
def cleanup_check.CleanupChecker.guess_bb_location (self, bb)
Definition at line 204 of file cleanup_check.py.
References cleanup_check.CleanupChecker.fun.
def cleanup_check.CleanupChecker.traverse_bbs (self, edge, bb, bb_from, entry_master)
Definition at line 252 of file cleanup_check.py.
References cleanup_check.CleanupChecker.compute_master(), cleanup_check.log(), cleanup_check.CleanupChecker.master_cleanups, cleanup_check.CleanupChecker.seen_edges, and cleanup_check.CleanupChecker.traverse_bbs().
Referenced by cleanup_check.CleanupChecker.traverse_bbs().
Member Data Documentation
cleanup_check.CleanupChecker::bad_returns
Definition at line 194 of file cleanup_check.py.
cleanup_check.CleanupChecker::cleanup_aware
Definition at line 213 of file cleanup_check.py.
cleanup_check.CleanupChecker::fun
Definition at line 194 of file cleanup_check.py.
Referenced by cleanup_check.CleanupChecker::guess_bb_location().
cleanup_check.CleanupChecker::is_constructor
Definition at line 288 of file cleanup_check.py.
cleanup_check.CleanupChecker::is_special_constructor
Definition at line 288 of file cleanup_check.py.
cleanup_check.CleanupChecker::master_cleanups
Definition at line 194 of file cleanup_check.py.
Referenced by cleanup_check.CleanupChecker.traverse_bbs().
cleanup_check.CleanupChecker::only_do_cleanups_seen
Definition at line 213 of file cleanup_check.py.
cleanup_check.CleanupChecker::seen_edges
Definition at line 194 of file cleanup_check.py.
Referenced by cleanup_check.CleanupChecker.traverse_bbs().
The documentation for this class was generated from the following file:
/home/stan/gdb/src/gdb/contrib/cleanup_check.py