GDB (xrefs): gdb.command.pretty_printers.DisablePrettyPrinter Class Reference
gdb.command.pretty_printers.DisablePrettyPrinter Class Reference
Public Member Functions
def __init__
def invoke
def __init__
def invoke
Detailed Description
GDB command to disable the specified pretty-printer.
Usage: disable pretty-printer [object-regexp [name-regexp]]
OBJECT-REGEXP is a regular expression matching the objects to examine.
Objects are "global", the program space's file, and the objfiles within
that program space.
NAME-REGEXP matches the name of the pretty-printer.
Individual printers in a collection are named as
printer-name;subprinter-name.
Definition at line 339 of file pretty_printers.py.
Constructor & Destructor Documentation
def gdb.command.pretty_printers.DisablePrettyPrinter.__init__ (self)
Definition at line 353 of file pretty_printers.py.
Referenced by gdb.command.pretty_printers.DisablePrettyPrinter.__init__().
def gdb.command.pretty_printers.DisablePrettyPrinter.__init__ (self)
Definition at line 353 of file pretty_printers.py.
References gdb.command.pretty_printers.DisablePrettyPrinter.__init__().
Member Function Documentation
def gdb.command.pretty_printers.DisablePrettyPrinter.invoke (self, arg, from_tty)
GDB calls this to perform the command.
Definition at line 357 of file pretty_printers.py.
References gdb::command::pretty_printers.do_enable_pretty_printer().
Referenced by gdb.command.pretty_printers.DisablePrettyPrinter.invoke().
def gdb.command.pretty_printers.DisablePrettyPrinter.invoke (self, arg, from_tty)
GDB calls this to perform the command.
Definition at line 357 of file pretty_printers.py.
References gdb::command::pretty_printers.do_enable_pretty_printer(), gdb.command.pretty_printers.DisablePrettyPrinter.invoke(), and gdb::command::pretty_printers.register_pretty_printer_commands().
The documentation for this class was generated from the following files:
/home/stan/gdb/src/gdb/python/lib/gdb/command/pretty_printers.py
/home/stan/gdb/linux/gdb/data-directory/python/gdb/command/pretty_printers.py