GDB (xrefs): /home/stan/gdb/src/gdb/cleanups.h File Reference
/home/stan/gdb/src/gdb/cleanups.h File Reference
Typedefs
typedef void(make_cleanup_ftype)(void *)
typedef void(make_cleanup_dtor_ftype)(void *)
Functions
struct cleanup * make_cleanup (make_cleanup_ftype *, void *)
struct cleanup * make_cleanup_dtor (make_cleanup_ftype *, void *, make_cleanup_dtor_ftype *)
struct cleanup * make_final_cleanup (make_cleanup_ftype *, void *)
struct cleanup * all_cleanups (void)
void do_cleanups (struct cleanup *)
void do_final_cleanups (struct cleanup *)
void discard_cleanups (struct cleanup *)
void discard_final_cleanups (struct cleanup *)
struct cleanup * save_cleanups (void)
struct cleanup * save_final_cleanups (void)
void restore_cleanups (struct cleanup *)
void restore_final_cleanups (struct cleanup *)
void null_cleanup (void *)
Typedef Documentation
typedef void(make_cleanup_dtor_ftype)(void *)
Definition at line 33 of file cleanups.h.
typedef void(make_cleanup_ftype)(void *)
Definition at line 30 of file cleanups.h.
Function Documentation
struct cleanup* all_cleanups (void) [read]
Definition at line 166 of file cleanups.c.
References SENTINEL_CLEANUP.
Referenced by captured_command_loop(), find_overload_match(), quit_force(), reread_symbols(), and throw_exception().
void discard_cleanups (struct cleanup *)
Definition at line 213 of file cleanups.c.
References discard_my_cleanups().
Referenced by add_solib_catchpoint(), attach_command(), bpstat_do_actions(), call_function_by_hand(), call_site_find_chain_1(), catch_ada_exception_command_split(), catch_exception_command_1(), collect_symbol(), compute_enum_values(), core_open(), cp_lookup_symbol_imports(), create_breakpoint(), create_breakpoint_sal(), create_breakpoints_sal(), darwin_current_sos(), displaced_step_prepare(), dwarf2_build_psymtabs(), dwarf2_build_psymtabs_hard(), dwarf2_frame_cache(), dwarf_decode_line_header(), encode_actions_1(), execute_command(), fetch_inferior_event(), find_oload_champ_namespace_loop(), finish_forward(), forward_search_command(), frame_save_as_regcache(), frame_unwind_find_by_frame(), gather_arguments(), gcore_command(), gdbtk_init(), gen_eval_for_expr(), gen_printf(), gen_trace_for_expr(), gen_trace_for_return_address(), gen_trace_for_var(), get_command_line(), handle_gnu_v3_exceptions(), handle_redirections(), hwdebug_insert_point(), inf_ptrace_attach(), inf_ptrace_create_inferior(), inferior_event_handler(), init_cutu_and_read_dies(), init_tu_and_read_dwo_dies(), irix_current_sos(), jit_reader_load(), keep_going(), linespec_parse_basic(), linux_get_siginfo_data(), macro_expand(), macro_expand_next(), make_symbol_overload_list(), make_symbol_overload_list_using(), mi_parse(), monitor_wait(), open_and_init_dwo_file(), parse_exp_in_context_1(), parse_find_args(), parse_linespec(), pipe_windows_open(), ppu2spu_sniffer(), prepare_for_detach(), read_command_lines_1(), read_string(), record_btrace_open(), record_full_message(), record_full_restore(), record_full_save(), record_full_wait_1(), remote_file_get(), remote_file_put(), remote_notif_ack(), remote_notif_parse(), reread_symbols(), resume(), reverse_search_command(), run_command_1(), save_infcall_suspend_state(), search_symbols(), som_current_sos(), stap_parse_argument(), step_1(), strace_marker_create_breakpoints_sal(), svr4_current_sos_direct(), svr4_handle_solib_event(), svr4_read_so_list(), syms_from_objfile_1(), tfile_open(), until_break_command(), until_next_command(), varobj_create(), VEC(), wait_for_inferior(), and xml_fetch_content_from_file().
void discard_final_cleanups (struct cleanup *)
Definition at line 222 of file cleanups.c.
References discard_my_cleanups().
void do_cleanups (struct cleanup *)
Definition at line 175 of file cleanups.c.
References do_my_cleanups().
Referenced by aarch64_analyze_prologue(), ada_print_floating(), ada_read_renaming_var_value(), ada_unhandled_exception_name_addr_from_raise(), ada_varobj_describe_simple_array_child(), ada_varobj_get_value_image(), ada_varobj_get_value_of_array_variable(), ada_varobj_scalar_image(), add_inferior_command(), add_path(), add_symbol_file_command(), add_thread_object(), addr_info_make_relative(), adjust_pc_after_break(), agent_command_1(), agent_eval_command_one(), aix_thread_resume(), aix_thread_wait(), aix_thread_xfer_partial(), alias_command(), apply_frame_filter(), apropos_command(), arm_analyze_prologue(), arm_exidx_new_objfile(), arm_insert_single_step_breakpoint(), ATTRIBUTE_PRINTF(), auto_load_info_scripts(), auto_load_objfile_script(), auto_load_objfile_script_1(), backtrace_command(), bfd_lookup_symbol_from_dyn_symtab(), bootstrap_python_frame_filters(), bp_loc_is_permanent(), bpfinishpy_handle_exit(), bpfinishpy_handle_stop(), bppy_get_commands(), bppy_init(), bpstat_check_watchpoint(), bpstat_do_actions_1(), break_range_command(), breakpoint_1(), breakpoint_re_set(), breakpoint_re_set_one(), build_id_to_debug_bfd(), build_type_unit_groups(), c_parse(), c_type_print_base(), call_function_by_hand(), call_site_find_chain_1(), captured_command_loop(), captured_main(), captured_mi_execute_command(), cd_command(), check_fast_tracepoint_sals(), checkpoint_command(), clear_command(), clone_inferior_command(), clone_program_space(), cmd_show_list(), cmdpy_destroyer(), cmdpy_function(), coff_symfile_read(), command_handler(), command_loop(), commands_command_1(), compare_sections_command(), compute_enum_values(), continue_1(), convert_between_encodings(), core_open(), cp_lookup_symbol_imports_or_template(), cp_print_value(), create_addrmap_from_index(), create_breakpoint(), create_dwo_unit_in_dwp_v1(), create_dwo_unit_in_dwp_v2(), create_excep_cond_exprs(), create_longjmp_master_breakpoint(), create_sals_line_offset(), create_std_terminate_master_breakpoint(), create_tsv_from_upload(), ctf_start(), darwin_debug_regions_recurse(), darwin_solib_get_all_image_info_addr_at_init(), dbx_psymtab_to_symtab_1(), dbx_read_symtab(), dbx_symfile_read(), decode_line_1(), decode_line_2(), decode_line_full(), decode_objc(), decode_static_tracepoint_spec(), default_xfer_partial(), delete_thread_object(), delete_trace_variable_command(), detach_breakpoints(), displaced_step_fixup(), displaced_step_prepare(), display_gdb_prompt(), do_all_continuations_ptid(), do_assembly_only(), do_captured_list_thread_ids(), do_map_commands_command(), do_mixed_source_and_assembly(), do_one_display(), do_show_command(), download_tracepoint_locations(), dprintf_after_condition_true(), dsbt_relocate_main_executable(), dump_insns(), dump_memory_to_file(), dump_value_to_file(), dw2_do_instantiate_symtab(), dw2_expand_symtabs_matching(), dw2_instantiate_symtab(), dw2_map_symbol_filenames(), dwarf2_build_psymtabs_hard(), dwarf2_compile_expr_to_ax(), dwarf2_evaluate_loc_desc_full(), dwarf2_frame_cache(), dwarf2_get_dwz_file(), dwarf2_loc_desc_needs_frame(), dwarf2_physname(), dwarf_decode_line_header(), dwarf_decode_macros(), elf_rel_plt_read(), elf_symfile_read(), elfmdebug_build_psymtabs(), elfstab_build_psymtabs(), encode_actions_1(), encode_actions_and_make_cleanup(), encode_actions_rsp(), end_symtab_get_static_block(), enumerate_locals(), env_execute_cli_command(), escape_buffer(), eval_command(), evaluate_subexp_c(), exec_close_1(), exec_continue(), exec_file_attach(), exec_file_command(), exec_reverse_continue(), exec_reverse_once(), execute_cmd_post_hook(), execute_cmd_pre_hook(), execute_command(), execute_command_to_string(), execute_control_command(), execute_stack_op(), execute_user_command(), expand(), extended_remote_run(), fbsd_find_memory_regions(), fetch_inferior_event(), file_is_auto_load_safe(), file_read_description_xml(), filter_results(), find_and_open_script(), find_and_open_source(), find_command(), find_function_symbols(), find_linespec_symbols(), find_method(), find_oload_champ_namespace_loop(), find_overload_match(), find_separate_debug_file(), find_separate_debug_file_by_debuglink(), find_slot_in_mapped_hash(), find_source_lines(), find_superclass_methods(), find_symbol_in_baseclass(), fnpy_call(), forward_search_command(), frame_info(), frame_pop(), frame_unwind_find_by_frame(), frapy_read_var(), free_variable(), frv_relocate_main_executable(), func_command(), func_verify_no_selftailcall(), gcore_command(), gcore_copy_callback(), gdb_bfd_lookup_symbol_from_symtab(), gdb_disassembly(), gdb_eval(), gdb_load_info(), gdb_readline_wrapper(), gdb_search(), gdb_update_mem(), gdbpy_breakpoint_has_py_cond(), gdbpy_should_stop(), gdbtk_load_asm(), gen_trace_for_var(), gen_ui_out_table_header_info(), generic_emit_char(), generic_load(), generic_printstr(), get_command_line(), get_filename_and_charpos(), get_number_extra_fields(), get_osdata(), get_register(), get_return_value(), get_set_value(), get_show_value(), getpkt_or_notif_sane_1(), gnuv3_get_type_from_type_info(), gnuv3_get_typeid(), gnuv3_print_vtable(), go_parse(), h8300_push_dummy_call(), handle_command(), handle_inferior_event(), handle_vfork_child_exec_or_exit(), host_char_to_target(), ia64_breakpoint_from_pc(), ia64_memory_insert_breakpoint(), ia64_memory_remove_breakpoint(), if_command(), indirect_pieced_value(), inferior_call_waitpid(), info_auto_load_cmd(), info_auto_load_libthread_db(), info_macro_command(), info_macros_command(), info_osdata_command(), info_probes_for_ops(), info_sharedlibrary_command(), info_spu_dma_cmdlist(), info_spu_dma_command(), info_spu_event_command(), info_spu_mailbox_command(), info_spu_mailbox_list(), info_spu_proxydma_command(), info_spu_signal_command(), info_static_tracepoint_markers_command(), infrun_thread_stop_requested_callback(), inherit_abstract_dies(), init_cutu_and_read_dies(), init_cutu_and_read_dies_no_follow(), init_if_undefined_command(), init_tu_and_read_dwo_dies(), insert_bp_location(), insert_breakpoint_locations(), install_new_value_visualizer(), interpreter_exec_cmd(), irix_open_symbol_file_object(), iterate_over_mappings(), iterate_over_symtabs(), jit_bfd_try_read_symtab(), jit_reader_load_command(), line_info(), linespec_parse_basic(), linux_child_follow_fork(), linux_core_info_proc_mappings(), linux_corefile_thread_callback(), linux_fill_prpsinfo(), linux_find_memory_regions_full(), linux_get_siginfo_data(), linux_info_proc(), linux_make_mappings_corefile_notes(), linux_nat_xfer_partial(), linux_proc_pending_signals(), list_arg_or_local(), list_args_or_locals(), list_available_thread_groups(), list_cp_abis(), lm_info_read(), load_command(), load_progress(), load_srec(), lookup_partial_symbol(), lookup_symbol_file(), lookup_symbol_in_language(), lookup_symbol_in_objfile_from_linkage_name(), m32c_analyze_prologue(), m32r_load(), m32r_upload_command(), macho_add_oso_symfile(), macho_symfile_read(), macho_symfile_read_all_oso(), macro_define_command(), macro_expand_command(), macro_expand_next(), macro_expand_once_command(), maint_agent_printf_command(), maintenance_expand_symtabs(), maintenance_info_bfds(), maintenance_print_architecture(), maintenance_print_dummy_frames(), maintenance_print_msymbols(), maintenance_print_psymbols(), maintenance_print_reggroups(), maintenance_print_symbols(), maintenance_print_type(), maybe_expand(), memory_xfer_partial(), memory_xfer_partial_1(), mep_analyze_prologue(), mi_catch_load_unload(), mi_cmd_break_insert_1(), mi_cmd_data_evaluate_expression(), mi_cmd_data_list_changed_registers(), mi_cmd_data_list_register_names(), mi_cmd_data_list_register_values(), mi_cmd_data_read_memory(), mi_cmd_data_read_memory_bytes(), mi_cmd_data_write_memory(), mi_cmd_data_write_memory_bytes(), mi_cmd_disassemble(), mi_cmd_exec_run(), mi_cmd_execute(), mi_cmd_interpreter_exec(), mi_cmd_list_features(), mi_cmd_list_target_features(), mi_cmd_list_thread_groups(), mi_cmd_stack_list_args(), mi_cmd_stack_list_frames(), mi_cmd_symbol_list_lines(), mi_cmd_trace_find(), mi_cmd_trace_frame_collected(), mi_cmd_var_assign(), mi_cmd_var_create(), mi_cmd_var_delete(), mi_cmd_var_list_children(), mi_cmd_var_update(), mi_execute_async_cli_command(), mi_execute_cli_command(), mi_load_progress(), mi_on_normal_stop(), mipscoff_symfile_read(), mn10300_analyze_prologue(), monitor_load(), msp430_analyze_prologue(), mt_push_dummy_call(), normal_stop(), notice_new_inferior(), objfile_relocate(), old_renaming_is_invisible(), open_and_init_dwp_file(), open_symbol_file_object(), openp(), output_command_const(), output_cores(), output_register(), output_thread_groups(), parse_and_eval(), parse_and_eval_address(), parse_and_eval_long(), parse_cmd_to_aexpr(), parse_exp_in_context_1(), parse_find_args(), parse_frame_specification_1(), parse_linespec(), parse_partial_symbols(), parse_probes(), parse_to_comma_and_eval(), pascal_object_print_value(), pipe_windows_open(), ppc_linux_get_syscall_number(), ppc_linux_memory_remove_breakpoint(), print_ada_task_info(), print_address_symbolic(), print_breakpoint_location(), print_command_1(), print_frame(), print_frame_arg(), print_frame_args(), print_frame_info(), print_inferior(), print_it_watchpoint(), print_mention_exception(), print_mention_masked_watchpoint(), print_mention_watchpoint(), print_object_command(), print_one_bfd(), print_one_breakpoint(), print_one_breakpoint_location(), print_one_detail_ranged_breakpoint(), print_one_inferior(), print_one_static_tracepoint_marker(), print_program_space(), print_return_value(), print_script(), print_solib_event(), print_source_lines_base(), print_thread_info(), print_ui_out_info(), print_variable_or_computed(), printf_wide_c_string(), proceed_after_attach(), process_full_comp_unit(), process_full_type_unit(), process_structure_scope(), procfs_info_proc(), procfs_open(), procfs_pidlist(), ps_lgetfpregs(), ps_lgetregs(), ps_lsetfpregs(), ps_lsetregs(), ps_pglobal_lookup(), ps_xfer_memory(), psymtab_to_fullname(), psymtab_to_symtab(), psymtab_to_symtab_1(), putpkt_binary(), py_free_inferior(), py_free_objfile(), py_free_pspace(), py_mi_print_variables(), py_print_args(), py_print_frame(), py_print_locals(), py_print_single_arg(), py_print_type(), py_print_value(), python_inferior_exit(), python_interactive_command(), python_new_objfile(), python_on_normal_stop(), python_on_resume(), quit_confirm(), rbreak_command(), re_set_exception_catchpoint(), read_alphacoff_dynamic_symtab(), read_array_type(), read_command_file(), read_command_lines(), read_command_lines_1(), read_dbx_dynamic_symtab(), read_dbx_symtab(), read_file_scope(), read_frame(), read_import_statement(), read_pe_exported_syms(), read_pieced_value(), read_symbols(), read_value_memory(), reattach_breakpoints(), record_btrace_call_history(), record_btrace_call_history_range(), record_btrace_insn_history(), record_btrace_insn_history_range(), record_full_goto_insn(), record_full_insert_breakpoint(), record_full_remove_breakpoint(), record_full_save(), record_full_wait_1(), regcache_dump(), regcache_print(), regcache_raw_read(), regcache_raw_write(), release_program_space(), reload_shared_libraries_1(), remote_delete_command(), remote_download_tracepoint(), remote_file_get(), remote_file_put(), remote_flash_done(), remote_flash_erase(), remote_flash_write(), remote_get_command(), remote_put_command(), remote_query_supported(), remote_register_number_and_offset(), remote_threads_info(), remote_traceframe_info(), remove_breakpoint(), reopen_exec_file(), reread_symbols(), resolve_sal_pc(), restore_binary_file(), restore_section_callback(), return_command(), reverse_search_command(), rl78_analyze_prologue(), rs6000_aix_core_xfer_shared_libraries_aix(), rs6000_xfer_shared_libraries(), rw_common(), rx_analyze_prologue(), safe_symbol_file_add(), save_breakpoints(), save_infcall_suspend_state(), save_objfile_types(), save_sigtrap(), script_from_file(), search_minsyms_for_name(), search_struct_method(), search_symbols(), set_command(), set_logging_redirect(), set_substitute_path_command(), show_remote_cmd(), show_substitute_path_command(), signal_catchpoint_print_one(), simple_search_memory(), skip_info(), skip_prologue_sal(), sol_thread_resume(), sol_thread_wait(), sol_thread_xfer_partial(), solib_aix_bfd_open(), solib_aix_solib_create_inferior_hook(), solib_find(), solib_map_sections(), solib_target_current_sos(), som_open_symbol_file_object(), som_symfile_read(), som_symtab_read(), source_command(), source_script_with_search(), sources_info(), spu_symbol_file_add_from_memory(), step_1(), svr4_handle_solib_event(), svr4_keep_data_in_core(), svr4_read_so_list(), sym_info(), symbol_file_add(), symbol_file_add_from_memory(), symbol_file_add_separate(), symbol_file_command(), symfile_bfd_open(), symtab_symbol_info(), symtab_to_fullname(), target_fileio_read_alloc_1(), target_read_description_xml(), target_read_live_memory(), target_write_memory_blocks(), thread_apply_all_command(), thread_apply_command(), thread_db_load_search(), throw_exception(), thumb_analyze_prologue(), tilegx_push_dummy_call(), tk_command(), trace_actions_command(), trace_dump_actions(), trace_dump_command(), trace_find_line_command(), trace_save_command(), trace_save_ctf(), trace_save_tfile(), trace_variable_command(), try_thread_db_load_from_dir(), try_thread_db_load_from_pdir_1(), tui_register_format(), tvariables_info_1(), type_to_string(), typy_legacy_template_argument(), typy_str(), ui_out_field_stream(), ui_printf(), unset_substitute_path_command(), until_break_command(), until_next_command(), update_dynamic_varobj_children(), update_global_location_list(), update_inserted_breakpoint_locations(), val_print_string(), validate_actionline(), value_concat(), value_get_print_value(), value_of_root_1(), varobj_create(), varobj_get_display_hint(), varobj_set_visualizer(), varobj_update_one(), VEC(), verify_gdbarch(), vfprintf_maybe_filtered(), vfprintf_unfiltered(), view_command(), wait_for_inferior(), watch_command_1(), whatis_exp(), while_command(), write_memory_ptid(), write_pieced_value(), write_psymtabs_to_index(), x_command(), xcoff_initial_scan(), xcoff_psymtab_to_symtab_1(), xdb_handle_command(), xml_fetch_content_from_file(), xstormy16_push_dummy_call(), and xtensa_verify_config().
void do_final_cleanups (struct cleanup *)
Definition at line 184 of file cleanups.c.
References do_my_cleanups().
Referenced by quit_force().
struct cleanup* make_cleanup (make_cleanup_ftype * , void *) [read]
Definition at line 117 of file cleanups.c.
References make_my_cleanup().
Referenced by ada_read_renaming_var_value(), ada_unhandled_exception_name_addr_from_raise(), ada_varobj_describe_simple_array_child(), ada_varobj_get_value_of_array_variable(), add_inferior_command(), add_path(), add_solib_catchpoint(), add_symbol_file_command(), addr_info_make_relative(), adjust_pc_after_break(), agent_eval_command_one(), alias_command(), all_tracepoint_actions_and_cleanup(), apropos_command(), arm_exidx_new_objfile(), attach_command(), ATTRIBUTE_PRINTF(), auto_load_info_scripts(), auto_load_objfile_script(), auto_load_objfile_script_1(), backtrace_command(), bfd_lookup_symbol_from_dyn_symtab(), bootstrap_python_frame_filters(), bppy_get_commands(), bppy_init(), bpstat_check_watchpoint(), bpstat_do_actions_1(), break_range_command(), breakpoint_re_set(), breakpoint_re_set_default(), build_type_unit_groups(), c_get_string(), c_parse(), c_type_print_base(), call_function_by_hand(), call_site_find_chain_1(), captured_main(), captured_mi_execute_command(), catch_ada_exception_command_split(), catch_exception_command_1(), cd_command(), check_fast_tracepoint_sals(), clear_command(), clone_inferior_command(), cmdpy_function(), coff_locate_sections(), coff_symfile_read(), command_loop(), commands_command_1(), compare_sections_command(), compile_rx_or_error(), compute_enum_values(), convert_between_encodings(), core_open(), cp_lookup_symbol_imports(), cp_lookup_symbol_imports_or_template(), cp_print_value(), create_breakpoint(), create_breakpoint_sal(), create_breakpoints_sal(), create_dwo_unit_in_dwp_v1(), create_dwo_unit_in_dwp_v2(), create_excep_cond_exprs(), create_global_typedef_table(), create_sals_line_offset(), create_tsv_from_upload(), ctf_start(), darwin_current_sos(), darwin_pid_to_exec_file(), darwin_solib_get_all_image_info_addr_at_init(), dbx_psymtab_to_symtab_1(), dbx_read_symtab(), dbx_symfile_read(), decode_line_1(), decode_line_2(), decode_line_full(), decode_objc(), decode_static_tracepoint_spec(), default_xfer_partial(), demangle_for_lookup(), displaced_step_fixup(), displaced_step_prepare(), display_gdb_prompt(), do_all_continuations_ptid(), do_map_commands_command(), do_mixed_source_and_assembly(), do_set_command(), do_show_command(), dsbt_relocate_main_executable(), dump_memory_to_file(), dump_value_to_file(), dw2_do_instantiate_symtab(), dw2_instantiate_symtab(), dwarf2_add_field(), dwarf2_add_member_fn(), dwarf2_add_typedef(), dwarf2_build_psymtabs_hard(), dwarf2_compile_expr_to_ax(), dwarf2_frame_cache(), dwarf2_get_dwz_file(), dwarf2_physname(), dwarf_decode_line_header(), elf_rel_plt_read(), elf_symfile_read(), elfstab_build_psymtabs(), encode_actions_1(), encode_actions_and_make_cleanup(), end_symtab_get_static_block(), enumerate_locals(), env_execute_cli_command(), error_stream(), eval_command(), exec_file_attach(), exec_file_command(), exec_reverse_continue(), exec_reverse_once(), execute_cmd_post_hook(), execute_cmd_pre_hook(), execute_control_command(), execute_user_command(), expand(), extended_remote_run(), fbsd_find_memory_regions(), fbsd_make_corefile_notes(), fetch_inferior_event(), file_is_auto_load_safe(), file_read_description_xml(), filter_results(), find_and_open_script(), find_and_open_source(), find_command(), find_file_and_directory(), find_function_symbols(), find_linespec_symbols(), find_method(), find_oload_champ_namespace_loop(), find_overload_match(), find_separate_debug_file_by_debuglink(), find_slot_in_mapped_hash(), find_source_lines(), find_superclass_methods(), find_symbol_in_baseclass(), finish_forward(), fnpy_call(), frame_info(), frame_prepare_for_sniffer(), frapy_read_var(), frv_relocate_main_executable(), func_command(), func_verify_no_selftailcall(), gather_arguments(), gcore_command(), gcore_copy_callback(), gdb_bfd_errmsg(), gdb_bfd_lookup_symbol_from_symtab(), gdb_eval(), gdb_readline_wrapper(), gdbtk_init(), gdbtk_load_asm(), gen_ui_out_table_header_info(), generic_load(), generic_printstr(), get_number_extra_fields(), get_osdata(), get_return_value(), get_set_value(), get_show_value(), getpkt_or_notif_sane_1(), gnuv3_get_type_from_type_info(), gnuv3_get_typeid(), gnuv3_print_vtable(), go_parse(), h8300_push_dummy_call(), handle_DW_AT_stmt_list(), handle_gnu_v3_exceptions(), hwdebug_insert_point(), increment_reading_symtab(), inf_ptrace_attach(), inf_ptrace_create_inferior(), inferior_call_waitpid(), info_auto_load_libthread_db(), info_macro_command(), info_macros_command(), info_probes_for_ops(), info_static_tracepoint_markers_command(), inherit_abstract_dies(), init_cutu_and_read_dies(), init_cutu_and_read_dies_no_follow(), init_if_undefined_command(), init_tu_and_read_dwo_dies(), insert_bp_location(), irix_current_sos(), irix_open_symbol_file_object(), iterate_over_mappings(), iterate_over_symtabs(), jit_reader_load_command(), keep_going(), line_info(), linespec_parse_basic(), linux_child_follow_fork(), linux_child_pid_to_exec_file(), linux_core_info_proc_mappings(), linux_corefile_thread_callback(), linux_fill_prpsinfo(), linux_find_memory_regions_full(), linux_get_siginfo_data(), linux_info_proc(), linux_make_corefile_notes(), linux_nat_attach(), list_available_thread_groups(), lm_info_read(), load_command(), load_progress(), lookup_partial_symbol(), lookup_struct_elt_type(), lookup_symbol_file(), macho_symfile_read(), macho_symfile_read_all_oso(), macro_define_command(), macro_expand(), macro_expand_command(), macro_expand_next(), macro_expand_once_command(), maint_agent_printf_command(), maintenance_print_msymbols(), maintenance_print_psymbols(), maintenance_print_symbols(), maintenance_print_type(), make_bpstat_clear_actions_cleanup(), make_cleanup_bfd_unref(), make_cleanup_cp_demangled_name_parse_free(), make_cleanup_decref_counted_command_line(), make_cleanup_delete_breakpoint(), make_cleanup_destroy_linespec_result(), make_cleanup_discard_minimal_symbols(), make_cleanup_dyn_string_delete(), make_cleanup_fclose(), make_cleanup_free_agent_expr(), make_cleanup_free_bincl_list(), make_cleanup_free_char_ptr_vec(), make_cleanup_free_command_lines(), make_cleanup_free_dwarf_expr_context(), make_cleanup_free_objfile(), make_cleanup_free_pv_area(), make_cleanup_free_search_symbols(), make_cleanup_free_section_addr_info(), make_cleanup_free_so(), make_cleanup_free_target_description(), make_cleanup_free_typedef_hash(), make_cleanup_free_variable(), make_cleanup_freeargv(), make_cleanup_htab_delete(), make_cleanup_obstack_free(), make_cleanup_osdata_free(), make_cleanup_py_decref(), make_cleanup_py_xdecref(), make_cleanup_regcache_xfree(), make_cleanup_restore_current_language(), make_cleanup_restore_infcall_control_state(), make_cleanup_restore_infcall_suspend_state(), make_cleanup_restore_page_info(), make_cleanup_ui_file_delete(), make_cleanup_ui_out_end(), make_cleanup_ui_out_redirect_pop(), make_cleanup_ui_out_table_begin_end(), make_cleanup_unpush_target(), make_cleanup_value_free(), make_cleanup_value_free_to_mark(), make_cleanup_wchar_iterator(), make_command_stats_cleanup(), make_regfree_cleanup(), make_show_memory_breakpoints_cleanup(), make_symbol_overload_list(), make_symbol_overload_list_using(), maybe_expand(), memory_error(), memory_xfer_partial(), memory_xfer_partial_1(), mi_cmd_break_insert_1(), mi_cmd_data_evaluate_expression(), mi_cmd_data_read_memory(), mi_cmd_data_read_memory_bytes(), mi_cmd_data_write_memory(), mi_cmd_data_write_memory_bytes(), mi_cmd_disassemble(), mi_cmd_interpreter_exec(), mi_cmd_list_thread_groups(), mi_cmd_thread_list_ids(), mi_cmd_thread_select(), mi_cmd_trace_find(), mi_cmd_trace_frame_collected(), mi_cmd_var_create(), mi_cmd_var_delete(), mi_execute_async_cli_command(), mi_execute_cli_command(), mi_parse(), mips_error(), monitor_load(), monitor_wait(), mt_push_dummy_call(), normal_stop(), notice_new_inferior(), objfile_relocate(), old_renaming_is_invisible(), open_and_init_dwo_file(), open_and_init_dwp_file(), open_symbol_file_object(), operator_stoken(), output_command_const(), output_cores(), parse_and_eval(), parse_and_eval_address(), parse_and_eval_long(), parse_cmd_to_aexpr(), parse_exp_in_context_1(), parse_find_args(), parse_frame_specification_1(), parse_linespec(), parse_partial_symbols(), parse_probes(), parse_to_comma_and_eval(), pascal_object_print_value(), pipe_windows_open(), ppc_linux_get_syscall_number(), prepare_for_detach(), print_address_symbolic(), print_command_1(), print_frame(), print_mention_exception(), print_object_command(), print_thread_info(), print_ui_out_info(), print_variable_or_computed(), process_full_comp_unit(), process_full_type_unit(), process_structure_scope(), procfs_info_proc(), procfs_pidlist(), psymtab_include_file_name(), psymtab_to_fullname(), psymtab_to_symtab_1(), putpkt_binary(), py_print_frame(), py_print_single_arg(), quit_confirm(), rbreak_command(), re_set_exception_catchpoint(), read_alphacoff_dynamic_symtab(), read_array_type(), read_baseclasses(), read_command_file(), read_command_lines(), read_command_lines_1(), read_cutu_die_from_dwo(), read_dbx_dynamic_symtab(), read_file_scope(), read_frame(), read_import_statement(), read_member_functions(), read_pe_exported_syms(), read_pieced_value(), read_string(), read_struct_fields(), read_value_memory(), record_btrace_open(), record_full_message(), record_full_restore(), record_full_save(), record_full_wait_1(), regcache_dump(), reload_shared_libraries_1(), remote_download_tracepoint(), remote_file_get(), remote_file_put(), remote_flash_done(), remote_flash_erase(), remote_flash_write(), remote_notif_ack(), remote_notif_parse(), remote_query_supported(), remote_register_number_and_offset(), remote_threads_info(), remote_traceframe_info(), reopen_exec_file(), reread_symbols(), restore_binary_file(), restore_section_callback(), resume(), return_command(), rs6000_aix_core_xfer_shared_libraries_aix(), rs6000_xfer_shared_libraries(), run_command_1(), safe_symbol_file_add(), save_breakpoints(), save_current_inferior(), save_current_program_space(), save_infcall_suspend_state(), save_inferior_ptid(), scan_expression_with_cleanup(), scan_filename_with_cleanup(), script_from_file(), search_minsyms_for_name(), search_struct_method(), search_symbols(), set_command(), set_logging_redirect(), setup_type_unit_groups(), setup_user_args(), simple_search_memory(), solib_aix_bfd_open(), solib_aix_solib_create_inferior_hook(), solib_bfd_fopen(), solib_find(), solib_map_sections(), solib_target_current_sos(), som_current_sos(), som_open_symbol_file_object(), som_symtab_read(), source_command(), source_script_with_search(), sources_info(), stap_parse_argument(), step_1(), strace_marker_create_breakpoints_sal(), svr4_current_sos_direct(), svr4_handle_solib_event(), svr4_keep_data_in_core(), sym_info(), symbol_file_add_from_memory(), symfile_bfd_open(), syms_from_objfile_1(), symtab_to_fullname(), target_fileio_read_alloc_1(), target_read_description_xml(), target_write_memory_blocks(), tfile_open(), thread_apply_all_command(), thread_apply_command(), thread_db_load_search(), throw_perror_with_name(), tilegx_push_dummy_call(), tk_command(), trace_actions_command(), trace_dump_actions(), trace_dump_command(), trace_find_line_command(), trace_save_command(), trace_save_ctf(), trace_save_tfile(), trace_variable_command(), try_thread_db_load_from_dir(), try_thread_db_load_from_pdir_1(), tui_register_format(), tvariables_info_1(), ui_out_field_stream(), ui_printf(), unexpected_linespec_error(), until_break_command(), until_next_command(), update_global_location_list(), val_print_string(), validate_actionline(), value_concat(), value_get_print_value(), varobj_update_one(), VEC(), verify_gdbarch(), vfprintf_maybe_filtered(), vfprintf_unfiltered(), view_command(), wait_for_inferior(), watch_command_1(), whatis_exp(), write_pieced_value(), write_psymtabs_to_index(), x_command(), xcoff_initial_scan(), xcoff_psymtab_to_symtab_1(), xml_fetch_content_from_file(), xstormy16_push_dummy_call(), and xtensa_verify_config().
struct cleanup* make_cleanup_dtor (make_cleanup_ftype * , void * , make_cleanup_dtor_ftype *) [read]
struct cleanup* make_final_cleanup (make_cleanup_ftype * , void *) [read]
Definition at line 136 of file cleanups.c.
References make_my_cleanup().
Referenced by _initialize_python(), gdb_init(), gdb_insn_length(), and gdbtk_init().
void null_cleanup (void *)
Definition at line 295 of file cleanups.c.
Referenced by ada_unhandled_exception_name_addr_from_raise(), add_inferior_command(), add_symbol_file_command(), adjust_pc_after_break(), arm_exidx_new_objfile(), attach_command(), ATTRIBUTE_PRINTF(), backtrace_command(), bootstrap_python_frame_filters(), c_type_print_base(), call_function_by_hand(), catch_ada_exception_command_split(), clear_command(), clone_inferior_command(), command_loop(), create_breakpoint(), create_dwo_unit_in_dwp_v1(), create_dwo_unit_in_dwp_v2(), darwin_solib_get_all_image_info_addr_at_init(), dbx_read_symtab(), demangle_for_lookup(), do_mixed_source_and_assembly(), dump_memory_to_file(), dump_value_to_file(), dwarf2_physname(), elfstab_build_psymtabs(), encode_actions_and_make_cleanup(), execute_control_command(), expand(), fetch_inferior_event(), find_and_open_source(), find_method(), find_overload_match(), find_slot_in_mapped_hash(), find_superclass_methods(), frame_info(), generic_load(), get_return_value(), go_parse(), handle_gnu_v3_exceptions(), inf_ptrace_attach(), inf_ptrace_create_inferior(), info_probes_for_ops(), init_cutu_and_read_dies(), init_tu_and_read_dwo_dies(), iterate_over_mappings(), iterate_over_symtabs(), load_command(), lookup_symbol_file(), macho_symfile_read_all_oso(), make_command_stats_cleanup(), mi_cmd_break_insert_1(), mi_cmd_data_read_memory(), mi_cmd_disassemble(), mi_cmd_interpreter_exec(), normal_stop(), notice_new_inferior(), print_command_1(), process_structure_scope(), procfs_info_proc(), py_print_frame(), py_print_single_arg(), read_array_type(), read_command_lines_1(), read_file_scope(), read_pe_exported_syms(), record_btrace_open(), regcache_dump(), reload_shared_libraries_1(), restore_binary_file(), search_symbols(), set_logging_redirect(), solib_find(), step_1(), target_write_memory_blocks(), thread_db_load_search(), trace_dump_command(), until_break_command(), varobj_update_one(), VEC(), and whatis_exp().
void restore_cleanups (struct cleanup *)
Definition at line 274 of file cleanups.c.
References restore_my_cleanups().
Referenced by catcher_pop().
void restore_final_cleanups (struct cleanup *)
Definition at line 282 of file cleanups.c.
References restore_my_cleanups().
struct cleanup* save_cleanups (void) [read]
Definition at line 243 of file cleanups.c.
References save_my_cleanups().
Referenced by exceptions_state_mc_init().
struct cleanup* save_final_cleanups (void) [read]
Definition at line 252 of file cleanups.c.
References save_my_cleanups().