GDB (xrefs): /home/stan/gdb/src/gdb/cli/cli-interp.c File Reference
/home/stan/gdb/src/gdb/cli/cli-interp.c File Reference
#include "defs.h"
#include "interps.h"
#include "event-top.h"
#include "ui-out.h"
#include "cli-out.h"
#include "top.h"
#include "gdb_string.h"
#include "exceptions.h"
Functions
static struct gdb_exception safe_execute_command (struct ui_out *uiout, char *command, int from_tty)
static void * cli_interpreter_init (struct interp *self, int top_level)
static int cli_interpreter_resume (void *data)
static int cli_interpreter_suspend (void *data)
static int cli_interpreter_display_prompt_p (void *data)
static struct gdb_exception cli_interpreter_exec (void *data, const char *command_str)
static struct ui_out * cli_ui_out (struct interp *self)
void _initialize_cli_interp (void)
Variables
struct ui_out * cli_uiout
initialize_file_ftype _initialize_cli_interp
Function Documentation
void _initialize_cli_interp (void)
Definition at line 146 of file cli-interp.c.
References _initialize_cli_interp, cli_command_loop(), cli_interpreter_display_prompt_p(), cli_interpreter_exec(), cli_interpreter_init(), cli_interpreter_resume(), cli_interpreter_suspend(), cli_out_new(), cli_ui_out(), gdb_stdout, interp_add(), INTERP_CONSOLE, and interp_new().
static int cli_interpreter_display_prompt_p (void * data) [static]
Definition at line 81 of file cli-interp.c.
References interp_quiet_p().
Referenced by _initialize_cli_interp().
static struct gdb_exception cli_interpreter_exec (void * data, const char * command_str) [static, read]
Definition at line 90 of file cli-interp.c.
References cli_out_set_stream(), gdb_stdout, and safe_execute_command().
Referenced by _initialize_cli_interp().
static void* cli_interpreter_init (struct interp * self, int top_level) [static]
Definition at line 41 of file cli-interp.c.
Referenced by _initialize_cli_interp().
static int cli_interpreter_resume (void * data) [static]
Definition at line 47 of file cli-interp.c.
References cli_out_set_stream(), gdb_setup_readline(), and gdb_stdout.
Referenced by _initialize_cli_interp().
static int cli_interpreter_suspend (void * data) [static]
Definition at line 73 of file cli-interp.c.
References gdb_disable_readline().
Referenced by _initialize_cli_interp().
static struct ui_out* cli_ui_out (struct interp * self) [static, read]
Definition at line 137 of file cli-interp.c.
References cli_uiout.
Referenced by _initialize_cli_interp().
static struct gdb_exception safe_execute_command (struct ui_out * uiout, char * command, int from_tty) [static, read]
Definition at line 113 of file cli-interp.c.
References current_uiout, exception_print(), execute_command(), gdb_stderr, RETURN_MASK_ALL, and TRY_CATCH.
Referenced by cli_interpreter_exec().
Variable Documentation
initialize_file_ftype _initialize_cli_interp
Referenced by _initialize_cli_interp(), and initialize_all_files().
struct ui_out* cli_uiout
Definition at line 29 of file cli-interp.c.
Referenced by cli_ui_out().