GDB (xrefs): /home/stan/gdb/src/gdb/cli/cli-setshow.h File Reference
/home/stan/gdb/src/gdb/cli/cli-setshow.h File Reference
Functions
int parse_cli_boolean_value (char *arg)
void do_set_command (char *arg, int from_tty, struct cmd_list_element *c)
void do_show_command (char *arg, int from_tty, struct cmd_list_element *c)
void cmd_show_list (struct cmd_list_element *list, int from_tty, char *prefix)
Function Documentation
void cmd_show_list (struct cmd_list_element * list, int from_tty, char * prefix)
Definition at line 673 of file cli-setshow.c.
void do_set_command (char * arg, int from_tty, struct cmd_list_element * c)
Definition at line 151 of file cli-setshow.c.
References _, cleanup::arg, auto_boolean_enums, deprecated_set_hook, cmd_list_element::enums, error(), error_no_arg(), cmd_list_element::func, gdb_assert, get_current_arch(), is_unlimited_literal(), len, LONGEST, make_cleanup(), memcpy(), cmd_list_element::name, name, notify_command_param_changed_p(), observer_notify_command_param_changed(), p, parse_and_eval_long(), parse_auto_binary_operation(), parse_cli_boolean_value(), parse_escape(), plongest(), cmd_list_element::prefix, cmd_list_element::prefixlist, set_cmd, setlist, strchr(), cmd_list_element::type, cmd_list_element::var, var_auto_boolean, var_boolean, var_enum, var_filename, var_integer, var_optional_filename, var_string, var_string_noescape, cmd_list_element::var_type, var_uinteger, var_zinteger, var_zuinteger, var_zuinteger_unlimited, xfree(), xmalloc(), xrealloc(), and xsnprintf().
Referenced by execute_command(), set_auto_load_cmd(), and set_per_command_cmd().
void do_show_command (char * arg, int from_tty, struct cmd_list_element * c)
Definition at line 569 of file cli-setshow.c.
References _, AUTO_BOOLEAN_AUTO, AUTO_BOOLEAN_FALSE, AUTO_BOOLEAN_TRUE, current_uiout, deprecated_show_value_hack, do_cleanups(), error(), fprintf_filtered(), fputs_filtered(), fputstr_filtered(), cmd_list_element::func, gdb_assert, gdb_stdout, internal_error(), make_cleanup(), make_cleanup_ui_file_delete(), mem_fileopen(), cmd_list_element::pre_show_hook, show_cmd, cmd_list_element::show_value_func, cmd_list_element::type, ui_file_xstrdup(), ui_out_field_stream(), ui_out_is_mi_like_p(), cmd_list_element::var, var_auto_boolean, var_boolean, var_enum, var_filename, var_integer, var_optional_filename, var_string, var_string_noescape, cmd_list_element::var_type, var_uinteger, var_zinteger, var_zuinteger, var_zuinteger_unlimited, and xfree().
Referenced by cmd_show_list(), execute_command(), and show_remote_cmd().
int parse_cli_boolean_value (char * arg)
Definition at line 79 of file cli-setshow.c.
Referenced by do_set_command(), and set_per_command_cmd().