GDB (xrefs): /home/stan/gdb/src/gdb/cli/cli-utils.h File Reference
/home/stan/gdb/src/gdb/cli/cli-utils.h File Reference
Classes
struct get_number_or_range_state
Defines
#define skip_to_space(INP) ((char *) skip_to_space_const (INP))
Functions
int get_number (char **)
void init_number_or_range (struct get_number_or_range_state *state, char *string)
int get_number_or_range (struct get_number_or_range_state *state)
int number_is_in_list (char *list, int number)
char * skip_spaces (char *inp)
const char * skip_spaces_const (const char *inp)
const char * skip_to_space_const (const char *inp)
char * remove_trailing_whitespace (const char *start, char *s)
char * extract_arg (char **arg)
int check_for_argument (char **str, char *arg, int arg_len)
Define Documentation
#define skip_to_space (INP) ((char *) skip_to_space_const (INP))
Definition at line 104 of file cli-utils.h.
Referenced by ada_get_next_arg(), decode_static_tracepoint_spec(), extract_arg(), extract_exception_regexp(), info_macro_command(), init_breakpoint_sal(), and parse_probes().
Function Documentation
int check_for_argument (char ** str, char * arg, int arg_len)
Definition at line 293 of file cli-utils.c.
Referenced by agent_command_1(), extract_exception_regexp(), and watch_maybe_just_location().
char* extract_arg (char ** arg)
Definition at line 264 of file cli-utils.c.
References memcpy(), skip_spaces(), skip_to_space, and xmalloc().
Referenced by disable_command(), enable_command(), info_probes_for_ops(), and VEC().
int get_number (char **)
Definition at line 113 of file cli-utils.c.
References get_number_trailer().
Referenced by condition_command(), enable_count_command(), find_location_by_number(), get_number_or_range(), get_tracepoint_by_number(), goto_bookmark_command(), and ignore_command().
int get_number_or_range (struct get_number_or_range_state * state)
Definition at line 131 of file cli-utils.c.
References _, get_number_or_range_state::end_ptr, get_number_or_range_state::end_value, error(), get_number_or_range_state::finished, get_number(), get_number_trailer(), get_number_or_range_state::in_range, get_number_or_range_state::last_retval, skip_spaces(), and get_number_or_range_state::string.
Referenced by bookmarks_info(), decode_line_2(), delete_bookmark_command(), detach_inferior_command(), get_tracepoint_by_number(), kill_inferior_command(), map_breakpoint_numbers(), map_display_numbers(), mem_delete_command(), mem_disable_command(), mem_enable_command(), number_is_in_list(), remove_inferior_command(), and thread_apply_command().
void init_number_or_range (struct get_number_or_range_state * state, char * string)
Definition at line 121 of file cli-utils.c.
References memset(), get_number_or_range_state::string, and string.
Referenced by bookmarks_info(), decode_line_2(), delete_bookmark_command(), detach_inferior_command(), kill_inferior_command(), map_breakpoint_numbers(), map_display_numbers(), mem_delete_command(), mem_disable_command(), mem_enable_command(), number_is_in_list(), remove_inferior_command(), thread_apply_command(), and trace_pass_command().
int number_is_in_list (char * list, int number)
Definition at line 194 of file cli-utils.c.
References _, error(), get_number_or_range_state::finished, get_number_or_range(), and init_number_or_range().
Referenced by breakpoint_1(), print_inferior(), print_thread_info(), record_btrace_open(), skip_delete_command(), skip_disable_command(), skip_enable_command(), and skip_info().
char* remove_trailing_whitespace (const char * start, char * s)
Definition at line 253 of file cli-utils.c.
Referenced by copy_token_string(), and set_gnutarget_command().
char* skip_spaces (char * inp)
Definition at line 217 of file cli-utils.c.
Referenced by ada_get_next_arg(), add_solib_catchpoint(), agent_command_1(), break_range_command(), catch_ada_assert_command_split(), catch_ada_exception_command_split(), catch_exception_command_1(), catch_exec_command_1(), catch_fork_command_1(), catch_signal_command(), catch_syscall_command_1(), cmd_record_call_history(), cmd_record_insn_history(), decode_static_tracepoint_spec(), ep_parse_optional_if_clause(), extract_arg(), extract_exception_regexp(), get_call_history_modifiers(), get_context_size(), get_insn_history_modifiers(), get_number_or_range(), get_number_trailer(), get_selections(), go32_pde(), go32_pte(), go32_pte_for_address(), go32_sgdt(), go32_sidt(), go32_sldt(), info_macro_command(), init_breakpoint_sal(), is_closing_quote_enclosed(), linux_fill_prpsinfo(), linux_info_proc(), m32r_load(), m32r_upload_command(), maintenance_translate_address(), parse_method(), parse_probes(), parse_selector(), python_interactive_command(), rbreak_command(), registers_info(), restore_command(), scan_expression_with_cleanup(), scan_filename_with_cleanup(), set_ext_lang_command(), source_command(), thread_name_command(), trace_find_outside_command(), trace_find_range_command(), trace_pass_command(), trace_variable_command(), update_dprintf_command_list(), VEC(), watch_maybe_just_location(), and whatis_exp().
const char* skip_spaces_const (const char * inp)
Definition at line 229 of file cli-utils.c.
Referenced by arm_stap_parse_special_token(), decode_agent_options(), disassemble_command(), encode_actions_1(), find_condition_and_thread(), get_insn_number(), info_auto_load_libthread_db(), is_unlimited_literal(), linespec_lexer_lex_one(), linespec_lexer_lex_string(), linux_info_proc(), maint_agent_printf_command(), mi_parse(), mi_parse_argv(), msymbol_hash_iw(), parse_cmd_to_aexpr(), parse_find_args(), parse_frame_specification_1(), read_mapping(), serial_open(), stap_parse_argument(), stap_parse_argument_1(), stap_parse_argument_conditionally(), stap_parse_probe_arguments(), stap_parse_single_operand(), trace_dump_actions(), ui_printf(), validate_actionline(), VEC(), and watch_command_1().
const char* skip_to_space_const (const char * inp)
Definition at line 241 of file cli-utils.c.
Referenced by find_condition_and_thread(), VEC(), and watch_command_1().