GDB (xrefs): /home/stan/gdb/src/gdb/cli/cli-decode.h File Reference
/home/stan/gdb/src/gdb/cli/cli-decode.h File Reference
#include "command.h"
Classes
struct cmd_list_element
Defines
#define CMD_DEPRECATED 0x1
#define DEPRECATED_WARN_USER 0x2
#define MALLOCED_REPLACEMENT 0x4
#define DOC_ALLOCATED 0x8
Functions
void help_cmd_list (struct cmd_list_element *, enum command_class, char *, int, struct ui_file *)
void help_cmd (char *, struct ui_file *)
void apropos_cmd (struct ui_file *, struct cmd_list_element *, struct re_pattern_buffer *, char *)
void not_just_help_class_command (char *arg, int from_tty)
void print_doc_line (struct ui_file *, char *)
Variables
const char *const auto_boolean_enums []
Define Documentation
#define CMD_DEPRECATED 0x1
Definition at line 51 of file cli-decode.h.
Referenced by deprecate_cmd(), deprecated_cmd_warning(), and maintenance_do_deprecate().
#define DEPRECATED_WARN_USER 0x2
Definition at line 52 of file cli-decode.h.
Referenced by deprecate_cmd(), deprecated_cmd_warning(), execute_command(), lookup_cmd_1(), and maintenance_do_deprecate().
#define DOC_ALLOCATED 0x8
Definition at line 54 of file cli-decode.h.
Referenced by add_alias_cmd(), add_setshow_cmd_full(), and delete_cmd().
#define MALLOCED_REPLACEMENT 0x4
Definition at line 53 of file cli-decode.h.
Referenced by maintenance_do_deprecate().
Function Documentation
void apropos_cmd (struct ui_file * , struct cmd_list_element * , struct re_pattern_buffer * , char *)
Definition at line 881 of file cli-decode.c.
References cmd_list_element::abbrev_flag, apropos_cmd(), cmd_list_element::doc, cmd_list_element::name, cmd_list_element::next, cmd_list_element::prefixlist, cmd_list_element::prefixname, and print_help_for_command().
Referenced by apropos_cmd(), and apropos_command().
void help_cmd (char * , struct ui_file *)
Definition at line 936 of file cli-decode.c.
References all_classes, all_commands, cmd_list_element::class, cmdlist, cmd_list_element::doc, fprintf_filtered(), fputs_filtered(), cmd_list_element::func, help_all(), help_list(), cmd_list_element::hook_post, cmd_list_element::hook_pre, lookup_cmd(), cmd_list_element::name, cmd_list_element::prefixlist, and cmd_list_element::prefixname.
Referenced by help_command().
void help_cmd_list (struct cmd_list_element * , enum command_class, char * , int , struct ui_file *)
Definition at line 1179 of file cli-decode.c.
References cmd_list_element::abbrev_flag, all_classes, all_commands, cmd_list_element::class, class_user, cmd_list_element::func, help_cmd_list(), cmd_list_element::next, cmd_list_element::prefixlist, cmd_list_element::prefixname, and print_help_for_command().
Referenced by help_all(), help_cmd_list(), help_list(), and print_help_for_command().
void not_just_help_class_command (char * arg, int from_tty)
Definition at line 371 of file cli-decode.c.
void print_doc_line (struct ui_file * , char *)
Definition at line 1111 of file cli-decode.c.
References fputs_filtered(), line_buffer, p, xfree(), and xmalloc().
Referenced by deprecated_show_value_hack(), and print_help_for_command().
Variable Documentation
const char* const auto_boolean_enums[]
Definition at line 497 of file cli-decode.c.
Referenced by add_setshow_auto_boolean_cmd(), and do_set_command().