GDB (xrefs): /home/stan/gdb/src/gdb/cli/cli-script.h File Reference
/home/stan/gdb/src/gdb/cli/cli-script.h File Reference
Functions
void script_from_file (FILE *stream, const char *file)
void show_user_1 (struct cmd_list_element *c, const char *prefix, const char *name, struct ui_file *stream)
enum command_control_type execute_control_command (struct command_line *cmd)
enum command_control_type execute_control_command_untraced (struct command_line *cmd)
struct command_line * get_command_line (enum command_control_type, char *)
void print_command_lines (struct ui_out *, struct command_line *, unsigned int)
struct command_line * copy_command_lines (struct command_line *cmds)
struct cleanup * make_cleanup_free_command_lines (struct command_line **arg)
void execute_user_command (struct cmd_list_element *c, char *args)
void print_command_trace (const char *cmd)
void reset_command_nest_depth (void)
Function Documentation
struct command_line* copy_command_lines (struct command_line * cmds) [read]
Definition at line 1354 of file cli-script.c.
References command_line::body_count, command_line::body_list, command_line::control_type, copy_command_lines(), command_line::line, command_line::next, and xmalloc().
Referenced by copy_command_lines(), and do_map_commands_command().
enum command_control_type execute_control_command (struct command_line * cmd)
Definition at line 399 of file cli-script.c.
enum command_control_type execute_control_command_untraced (struct command_line * cmd)
Definition at line 591 of file cli-script.c.
References execute_control_command().
Referenced by if_command(), python_interactive_command(), and while_command().
void execute_user_command (struct cmd_list_element * c, char * args)
Definition at line 311 of file cli-script.c.
References _, break_control, do_cleanups(), do_restore_instream_cleanup(), do_restore_user_call_depth(), error(), execute_control_command(), in_user_command, instream, interpreter_async, make_cleanup(), make_cleanup_restore_integer(), max_user_call_depth, command_line::next, setup_user_args(), simple_control, cmd_list_element::user_commands, and warning().
Referenced by execute_cmd_post_hook(), execute_cmd_pre_hook(), and execute_command().
struct command_line* get_command_line (enum command_control_type, char *) [read]
Definition at line 111 of file cli-script.c.
References _, build_command_line(), discard_cleanups(), do_cleanups(), invalid_control, make_cleanup_free_command_lines(), read_next_line(), recurse_read_control_structure(), and warning().
Referenced by if_command(), python_interactive_command(), and while_command().
struct cleanup* make_cleanup_free_command_lines (struct command_line ** arg) [read]
Definition at line 1348 of file cli-script.c.
References do_free_command_lines_cleanup(), and make_cleanup().
Referenced by get_command_line(), python_interactive_command(), and read_command_lines_1().
void print_command_lines (struct ui_out * , struct command_line * , unsigned int)
Definition at line 137 of file cli-script.c.
void print_command_trace (const char * cmd)
Definition at line 379 of file cli-script.c.
References command_nest_depth, printf_filtered(), source_verbose, and trace_commands.
Referenced by execute_command(), and execute_control_command().
void reset_command_nest_depth (void)
Definition at line 362 of file cli-script.c.
Referenced by display_gdb_prompt().
void script_from_file (FILE * stream, const char * file)
Definition at line 1626 of file cli-script.c.
References _, do_cleanups(), gdb_exception::error, internal_error(), make_cleanup(), gdb_exception::message, source_cleanup_lines_args::old_file, source_cleanup_lines_args::old_line, read_command_file(), gdb_exception::reason, RETURN_ERROR, RETURN_MASK_ERROR, source_cleanup_lines(), source_file_name, source_line_number, throw_error(), and TRY_CATCH.
Referenced by source_gdb_script_for_objfile(), and source_script_from_stream().
void show_user_1 (struct cmd_list_element * c, const char * prefix, const char * name, struct ui_file * stream)
Definition at line 1670 of file cli-script.c.
References cmd_list_element::class, class_user, current_uiout, fprintf_filtered(), fputs_filtered(), gdb_stdout, cmd_list_element::name, cmd_list_element::next, cmd_list_element::prefixlist, cmd_list_element::prefixname, print_command_lines(), show_user_1(), and cmd_list_element::user_commands.
Referenced by show_user(), and show_user_1().