GDB (xrefs): /home/stan/gdb/src/gdb/cli/cli-decode.c File Reference
/home/stan/gdb/src/gdb/cli/cli-decode.c File Reference
#include "defs.h"
#include "symtab.h"
#include <ctype.h>
#include "gdb_regex.h"
#include "gdb_string.h"
#include "completer.h"
#include "ui-out.h"
#include "cli/cli-cmds.h"
#include "cli/cli-decode.h"
#include "gdb_assert.h"
Functions
static void undef_cmd_error (const char *, const char *)
static struct cmd_list_element * delete_cmd (const char *name, struct cmd_list_element **list, struct cmd_list_element **prehook, struct cmd_list_element **prehookee, struct cmd_list_element **posthook, struct cmd_list_element **posthookee)
static struct cmd_list_element * find_cmd (const char *command, int len, struct cmd_list_element *clist, int ignore_help_classes, int *nfound)
static void help_all (struct ui_file *stream)
static struct cmd_list_element * lookup_cmd_for_prefixlist (struct cmd_list_element **key, struct cmd_list_element *list)
static void set_cmd_prefix (struct cmd_list_element *c, struct cmd_list_element **list)
static void print_help_for_command (struct cmd_list_element *c, char *prefix, int recurse, struct ui_file *stream)
static void do_cfunc (struct cmd_list_element *c, char *args, int from_tty)
void set_cmd_cfunc (struct cmd_list_element *cmd, cmd_cfunc_ftype *cfunc)
static void do_sfunc (struct cmd_list_element *c, char *args, int from_tty)
void set_cmd_sfunc (struct cmd_list_element *cmd, cmd_sfunc_ftype *sfunc)
int cmd_cfunc_eq (struct cmd_list_element *cmd, void(*cfunc)(char *args, int from_tty))
void set_cmd_context (struct cmd_list_element *cmd, void *context)
void * get_cmd_context (struct cmd_list_element *cmd)
enum cmd_types cmd_type (struct cmd_list_element *cmd)
void set_cmd_completer (struct cmd_list_element *cmd, completer_ftype *completer)
struct cmd_list_element * add_cmd (const char *name, enum command_class class, void(*fun)(char *, int), char *doc, struct cmd_list_element **list)
struct cmd_list_element * deprecate_cmd (struct cmd_list_element *cmd, char *replacement)
struct cmd_list_element * add_alias_cmd (const char *name, const char *oldname, enum command_class class, int abbrev_flag, struct cmd_list_element **list)
struct cmd_list_element * add_prefix_cmd (const char *name, enum command_class class, void(*fun)(char *, int), char *doc, struct cmd_list_element **prefixlist, char *prefixname, int allow_unknown, struct cmd_list_element **list)
struct cmd_list_element * add_abbrev_prefix_cmd (const char *name, enum command_class class, void(*fun)(char *, int), char *doc, struct cmd_list_element **prefixlist, char *prefixname, int allow_unknown, struct cmd_list_element **list)
void not_just_help_class_command (char *args, int from_tty)
static void empty_sfunc (char *, int, struct cmd_list_element *)
static struct cmd_list_element * add_set_or_show_cmd (const char *name, enum cmd_types type, enum command_class class, var_types var_type, void *var, char *doc, struct cmd_list_element **list)
static void add_setshow_cmd_full (const char *name, enum command_class class, var_types var_type, void *var, const char *set_doc, const char *show_doc, const char *help_doc, cmd_sfunc_ftype *set_func, show_value_ftype *show_func, struct cmd_list_element **set_list, struct cmd_list_element **show_list, struct cmd_list_element **set_result, struct cmd_list_element **show_result)
void add_setshow_enum_cmd (const char *name, enum command_class class, const char *const *enumlist, const char **var, const char *set_doc, const char *show_doc, const char *help_doc, cmd_sfunc_ftype *set_func, show_value_ftype *show_func, struct cmd_list_element **set_list, struct cmd_list_element **show_list)
void add_setshow_auto_boolean_cmd (const char *name, enum command_class class, enum auto_boolean *var, const char *set_doc, const char *show_doc, const char *help_doc, cmd_sfunc_ftype *set_func, show_value_ftype *show_func, struct cmd_list_element **set_list, struct cmd_list_element **show_list)
void add_setshow_boolean_cmd (const char *name, enum command_class class, int *var, const char *set_doc, const char *show_doc, const char *help_doc, cmd_sfunc_ftype *set_func, show_value_ftype *show_func, struct cmd_list_element **set_list, struct cmd_list_element **show_list)
void add_setshow_filename_cmd (const char *name, enum command_class class, char **var, const char *set_doc, const char *show_doc, const char *help_doc, cmd_sfunc_ftype *set_func, show_value_ftype *show_func, struct cmd_list_element **set_list, struct cmd_list_element **show_list)
void add_setshow_string_cmd (const char *name, enum command_class class, char **var, const char *set_doc, const char *show_doc, const char *help_doc, cmd_sfunc_ftype *set_func, show_value_ftype *show_func, struct cmd_list_element **set_list, struct cmd_list_element **show_list)
struct cmd_list_element * add_setshow_string_noescape_cmd (const char *name, enum command_class class, char **var, const char *set_doc, const char *show_doc, const char *help_doc, cmd_sfunc_ftype *set_func, show_value_ftype *show_func, struct cmd_list_element **set_list, struct cmd_list_element **show_list)
void add_setshow_optional_filename_cmd (const char *name, enum command_class class, char **var, const char *set_doc, const char *show_doc, const char *help_doc, cmd_sfunc_ftype *set_func, show_value_ftype *show_func, struct cmd_list_element **set_list, struct cmd_list_element **show_list)
static VEC (char_ptr)
void add_setshow_integer_cmd (const char *name, enum command_class class, int *var, const char *set_doc, const char *show_doc, const char *help_doc, cmd_sfunc_ftype *set_func, show_value_ftype *show_func, struct cmd_list_element **set_list, struct cmd_list_element **show_list)
void add_setshow_uinteger_cmd (const char *name, enum command_class class, unsigned int *var, const char *set_doc, const char *show_doc, const char *help_doc, cmd_sfunc_ftype *set_func, show_value_ftype *show_func, struct cmd_list_element **set_list, struct cmd_list_element **show_list)
void add_setshow_zinteger_cmd (const char *name, enum command_class class, int *var, const char *set_doc, const char *show_doc, const char *help_doc, cmd_sfunc_ftype *set_func, show_value_ftype *show_func, struct cmd_list_element **set_list, struct cmd_list_element **show_list)
void add_setshow_zuinteger_unlimited_cmd (const char *name, enum command_class class, int *var, const char *set_doc, const char *show_doc, const char *help_doc, cmd_sfunc_ftype *set_func, show_value_ftype *show_func, struct cmd_list_element **set_list, struct cmd_list_element **show_list)
void add_setshow_zuinteger_cmd (const char *name, enum command_class class, unsigned int *var, const char *set_doc, const char *show_doc, const char *help_doc, cmd_sfunc_ftype *set_func, show_value_ftype *show_func, struct cmd_list_element **set_list, struct cmd_list_element **show_list)
struct cmd_list_element * add_info (const char *name, void(*fun)(char *, int), char *doc)
struct cmd_list_element * add_info_alias (const char *name, char *oldname, int abbrev_flag)
struct cmd_list_element * add_com (const char *name, enum command_class class, void(*fun)(char *, int), char *doc)
struct cmd_list_element * add_com_alias (const char *name, const char *oldname, enum command_class class, int abbrev_flag)
void apropos_cmd (struct ui_file *stream, struct cmd_list_element *commandlist, struct re_pattern_buffer *regex, char *prefix)
void help_cmd (char *arg, struct ui_file *stream)
void help_list (struct cmd_list_element *list, char *cmdtype, enum command_class class, struct ui_file *stream)
void print_doc_line (struct ui_file *stream, char *str)
void help_cmd_list (struct cmd_list_element *list, enum command_class class, char *prefix, int recurse, struct ui_file *stream)
static int find_command_name_length (const char *text)
int valid_user_defined_cmd_name_p (const char *name)
struct cmd_list_element * lookup_cmd_1 (const char **text, struct cmd_list_element *clist, struct cmd_list_element **result_list, int ignore_help_classes)
struct cmd_list_element * lookup_cmd (const char **line, struct cmd_list_element *list, char *cmdtype, int allow_unknown, int ignore_help_classes)
void deprecated_cmd_warning (const char *text)
int lookup_cmd_composition (const char *text, struct cmd_list_element **alias, struct cmd_list_element **prefix_cmd, struct cmd_list_element **cmd)
int cmd_func_p (struct cmd_list_element *cmd)
void cmd_func (struct cmd_list_element *cmd, char *args, int from_tty)
Variables
const char *const auto_boolean_enums [] = { "on", "off", "auto", NULL }
Function Documentation
struct cmd_list_element* add_abbrev_prefix_cmd (const char * name, enum command_class class, void(*)(char *, int) fun, char * doc, struct cmd_list_element ** prefixlist, char * prefixname, int allow_unknown, struct cmd_list_element ** list) [read]
Definition at line 355 of file cli-decode.c.
References cmd_list_element::abbrev_flag, add_cmd(), cmd_list_element::allow_unknown, cmd_list_element::prefixlist, and cmd_list_element::prefixname.
struct cmd_list_element* add_alias_cmd (const char * name, const char * oldname, enum command_class class, int abbrev_flag, struct cmd_list_element ** list) [read]
Definition at line 275 of file cli-decode.c.
References cmd_list_element::abbrev_flag, add_cmd(), cmd_list_element::alias_chain, cmd_list_element::aliases, cmd_list_element::allow_unknown, cmd_list_element::cmd_pointer, delete_cmd(), cmd_list_element::doc, DOC_ALLOCATED, cmd_list_element::flags, cmd_list_element::func, cmd_list_element::function, gdb_assert, lookup_cmd(), cmd_list_element::prefixlist, cmd_list_element::prefixname, and set_cmd_prefix().
Referenced by _initialize_cp_support(), _initialize_macrocmd(), _initialize_mips_tdep(), _initialize_record(), _initialize_record_full(), _initialize_solib(), _initialize_tracepoint(), _initialize_windows_tdep(), add_com_alias(), add_info_alias(), add_packet_config_cmd(), add_task_commands(), add_thread_commands(), alias_command(), and initialize_current_architecture().
struct cmd_list_element* add_cmd (const char * name, enum command_class class, void(*)(char *, int) fun, char * doc, struct cmd_list_element ** list) [read]
Definition at line 186 of file cli-decode.c.
References cmd_list_element::abbrev_flag, cmd_list_element::alias_chain, cmd_list_element::aliases, cmd_list_element::allow_unknown, cmd_list_element::class, cmd_list_element::cmd_pointer, delete_cmd(), cmd_list_element::destroyer, cmd_list_element::doc, cmd_list_element::enums, cmd_list_element::flags, cmd_list_element::hook_in, cmd_list_element::hook_post, cmd_list_element::hook_pre, cmd_list_element::hookee_post, cmd_list_element::hookee_pre, cmd_list_element::name, name, cmd_list_element::next, not_set_cmd, p, cmd_list_element::pre_show_hook, cmd_list_element::prefix, cmd_list_element::prefixlist, cmd_list_element::prefixname, cmd_list_element::replacement, set_cmd_cfunc(), set_cmd_context(), cmd_list_element::type, cmd_list_element::user_commands, cmd_list_element::var, var_boolean, cmd_list_element::var_type, and xmalloc().
Referenced by _initialize_avr_tdep(), _initialize_cli_cmds(), _initialize_cli_dump(), _initialize_cli_logging(), _initialize_cp_abi(), _initialize_cp_namespace(), _initialize_cp_support(), _initialize_fork_child(), _initialize_gdb_bfd(), _initialize_go32_nat(), _initialize_hppa_tdep(), _initialize_macrocmd(), _initialize_mem(), _initialize_mem_search(), _initialize_mips_tdep(), _initialize_psymtab(), _initialize_record(), _initialize_record_full(), _initialize_regcache(), _initialize_reggroup(), _initialize_reverse(), _initialize_sol_thread(), _initialize_spu_tdep(), _initialize_step_skip(), _initialize_symfile_mem(), _initialize_target_descriptions(), _initialize_tasks(), _initialize_thread_db(), _initialize_tracepoint(), _initialize_tui_regs(), _initialize_windows_nat(), _initialize_windows_tdep(), add_abbrev_prefix_cmd(), add_alias_cmd(), add_catch_command(), add_com(), add_deprecated_target_alias(), add_dump_command(), add_info(), add_internal_function(), add_prefix_cmd(), add_set_or_show_cmd(), add_target_with_completer(), add_task_commands(), add_thread_commands(), bsd_kvm_add_target(), cmdpy_init(), define_command(), init_cli_cmds(), initialize_inferiors(), initialize_progspace(), initialize_remote_fileio(), and initialize_targets().
struct cmd_list_element* add_com (const char * name, enum command_class class, void(*)(char *, int) fun, char * doc) [read]
Definition at line 861 of file cli-decode.c.
References add_cmd(), and cmdlist.
Referenced by _initialize_cli_cmds(), _initialize_cli_dump(), _initialize_cli_script(), _initialize_gcore(), _initialize_m32r_rom(), _initialize_mem(), _initialize_objc_language(), _initialize_python(), _initialize_regcache(), _initialize_remote_m32r(), _initialize_remote_mips(), _initialize_remote_sim(), _initialize_reverse(), _initialize_solib(), _initialize_tracepoint(), _initialize_tui_layout(), _initialize_tui_regs(), _initialize_tui_stack(), _initialize_tui_win(), _initialize_windows_nat(), gdbtk_init(), init_main(), initialize_inferiors(), initialize_targets(), and initialize_utils().
struct cmd_list_element* add_com_alias (const char * name, const char * oldname, enum command_class class, int abbrev_flag) [read]
Definition at line 870 of file cli-decode.c.
References add_alias_cmd(), and cmdlist.
Referenced by _initialize_cli_cmds(), _initialize_gcore(), _initialize_objc_language(), _initialize_python(), _initialize_record(), _initialize_reverse(), _initialize_tracepoint(), _initialize_tui_win(), _initialize_windows_nat(), and alias_command().
struct cmd_list_element* add_info (const char * name, void(*)(char *, int) fun, char * doc) [read]
Definition at line 845 of file cli-decode.c.
References add_cmd(), infolist, and no_class.
Referenced by _initialize_auxv(), _initialize_cli_cmds(), _initialize_cp_support(), _initialize_darwin_info_commands(), _initialize_mem(), _initialize_objc_language(), _initialize_osdata(), _initialize_procfs(), _initialize_reverse(), _initialize_ser_dos(), _initialize_solib(), _initialize_step_skip(), _initialize_tasks(), _initialize_tracepoint(), _initialize_tui_win(), initialize_inferiors(), and initialize_targets().
struct cmd_list_element* add_info_alias (const char * name, char * oldname, int abbrev_flag) [read]
Definition at line 853 of file cli-decode.c.
References add_alias_cmd(), and infolist.
Referenced by add_task_commands(), and set_windows_aliases().
struct cmd_list_element* add_prefix_cmd (const char * name, enum command_class class, void(*)(char *, int) fun, char * doc, struct cmd_list_element ** prefixlist, char * prefixname, int allow_unknown, struct cmd_list_element ** list) [read]
Definition at line 327 of file cli-decode.c.
References add_cmd(), cmd_list_element::allow_unknown, cmdlist, cmd_list_element::next, p, cmd_list_element::prefix, cmd_list_element::prefixlist, cmd_list_element::prefixname, and set_cmd_prefix().
Referenced by _initialize_ada_language(), _initialize_arm_tdep(), _initialize_cli_cmds(), _initialize_cli_dump(), _initialize_cli_logging(), _initialize_cp_support(), _initialize_frame(), _initialize_go32_nat(), _initialize_macrocmd(), _initialize_mem(), _initialize_mips_tdep(), _initialize_python(), _initialize_record(), _initialize_record_full(), _initialize_rs6000_tdep(), _initialize_sh_tdep(), _initialize_spu_tdep(), _initialize_step_skip(), _initialize_target_descriptions(), _initialize_tracepoint(), _initialize_tui_regs(), _initialize_tui_win(), add_internal_problem_command(), add_target_with_completer(), add_task_commands(), add_thread_commands(), auto_load_info_cmdlist_get(), auto_load_set_cmdlist_get(), auto_load_show_cmdlist_get(), bsd_kvm_add_target(), cmdpy_init(), info_probes_cmdlist_get(), init_w32_command_list(), and tui_get_cmd_list().
static struct cmd_list_element* add_set_or_show_cmd (const char * name, enum cmd_types type, enum command_class class, var_types var_type, void * var, char * doc, struct cmd_list_element ** list) [static, read]
Definition at line 392 of file cli-decode.c.
References add_cmd(), empty_sfunc(), gdb_assert, set_cmd, set_cmd_sfunc(), show_cmd, type, cmd_list_element::type, cmd_list_element::var, and cmd_list_element::var_type.
Referenced by add_setshow_cmd_full().
void add_setshow_auto_boolean_cmd (const char * name, enum command_class class, enum auto_boolean * var, const char * set_doc, const char * show_doc, const char * help_doc, cmd_sfunc_ftype * set_func, show_value_ftype * show_func, struct cmd_list_element ** set_list, struct cmd_list_element ** show_list)
Definition at line 504 of file cli-decode.c.
References add_setshow_cmd_full(), auto_boolean_enums, cmd_list_element::enums, and var_auto_boolean.
Referenced by _initialize_mips_tdep(), _initialize_rs6000_tdep(), add_packet_config_cmd(), and add_setshow_generic().
void add_setshow_boolean_cmd (const char * name, enum command_class class, int * var, const char * set_doc, const char * show_doc, const char * help_doc, cmd_sfunc_ftype * set_func, show_value_ftype * show_func, struct cmd_list_element ** set_list, struct cmd_list_element ** show_list)
Definition at line 529 of file cli-decode.c.
References add_setshow_cmd_full(), cmd_list_element::enums, and var_boolean.
Referenced by _initialize_aarch64_tdep(), _initialize_ada_language(), _initialize_aix_thread(), _initialize_arm_tdep(), _initialize_cli_cmds(), _initialize_cli_logging(), _initialize_cris_tdep(), _initialize_darwin_inferior(), _initialize_dec_thread(), _initialize_demangler(), _initialize_frame(), _initialize_gdbtypes(), _initialize_gnu_nat(), _initialize_hppa_tdep(), _initialize_mem(), _initialize_mips_linux_nat(), _initialize_mips_tdep(), _initialize_nios2_tdep(), _initialize_notif(), _initialize_pascal_valprint(), _initialize_proc_api(), _initialize_record_full(), _initialize_remote_mips(), _initialize_remote_monitors(), _initialize_rs6000_tdep(), _initialize_solib(), _initialize_solib_aix(), _initialize_spu_tdep(), _initialize_symfile_debug(), _initialize_thread_db(), _initialize_tracepoint(), _initialize_windows_nat(), _initialize_windows_tdep(), add_setshow_generic(), add_show_debug_regs_command(), init_main(), initialize_inferiors(), initialize_targets(), and initialize_utils().
static void add_setshow_cmd_full (const char * name, enum command_class class, var_types var_type, void * var, const char * set_doc, const char * show_doc, const char * help_doc, cmd_sfunc_ftype * set_func, show_value_ftype * show_func, struct cmd_list_element ** set_list, struct cmd_list_element ** show_list, struct cmd_list_element ** set_result, struct cmd_list_element ** show_result) [static]
Definition at line 422 of file cli-decode.c.
References add_set_or_show_cmd(), DOC_ALLOCATED, cmd_list_element::flags, set_cmd, set_cmd_prefix(), set_cmd_sfunc(), show_cmd, cmd_list_element::show_value_func, and xstrprintf().
Referenced by add_setshow_auto_boolean_cmd(), add_setshow_boolean_cmd(), add_setshow_enum_cmd(), add_setshow_filename_cmd(), add_setshow_integer_cmd(), add_setshow_optional_filename_cmd(), add_setshow_string_cmd(), add_setshow_string_noescape_cmd(), add_setshow_uinteger_cmd(), add_setshow_zinteger_cmd(), add_setshow_zuinteger_cmd(), and add_setshow_zuinteger_unlimited_cmd().
void add_setshow_enum_cmd (const char * name, enum command_class class, const char *const * enumlist, const char ** var, const char * set_doc, const char * show_doc, const char * help_doc, cmd_sfunc_ftype * set_func, show_value_ftype * show_func, struct cmd_list_element ** set_list, struct cmd_list_element ** show_list)
Definition at line 475 of file cli-decode.c.
References add_setshow_cmd_full(), cmd_list_element::enums, and var_enum.
Referenced by _initialize_agent(), _initialize_arm_tdep(), _initialize_charset(), _initialize_cli_cmds(), _initialize_cris_tdep(), _initialize_demangler(), _initialize_filesystem(), _initialize_gdb_osabi(), _initialize_gdbarch_utils(), _initialize_mips_tdep(), _initialize_python(), _initialize_rs6000_tdep(), _initialize_sh_tdep(), _initialize_tui_win(), add_internal_problem_command(), add_language(), add_setshow_generic(), and initialize_current_architecture().
void add_setshow_filename_cmd (const char * name, enum command_class class, char ** var, const char * set_doc, const char * show_doc, const char * help_doc, cmd_sfunc_ftype * set_func, show_value_ftype * show_func, struct cmd_list_element ** set_list, struct cmd_list_element ** show_list)
Definition at line 551 of file cli-decode.c.
References add_setshow_cmd_full(), and var_filename.
Referenced by _initialize_cli_logging(), _initialize_fork_child(), _initialize_proc_api(), _initialize_solib(), _initialize_target_descriptions(), add_setshow_generic(), and init_main().
void add_setshow_integer_cmd (const char * name, enum command_class class, int * var, const char * set_doc, const char * show_doc, const char * help_doc, cmd_sfunc_ftype * set_func, show_value_ftype * show_func, struct cmd_list_element ** set_list, struct cmd_list_element ** show_list)
Definition at line 657 of file cli-decode.c.
References add_setshow_cmd_full(), and var_integer.
Referenced by add_setshow_generic().
void add_setshow_optional_filename_cmd (const char * name, enum command_class class, char ** var, const char * set_doc, const char * show_doc, const char * help_doc, cmd_sfunc_ftype * set_func, show_value_ftype * show_func, struct cmd_list_element ** set_list, struct cmd_list_element ** show_list)
Definition at line 614 of file cli-decode.c.
References add_setshow_cmd_full(), and var_optional_filename.
Referenced by _initialize_solib(), _initialize_thread_db(), and add_setshow_generic().
void add_setshow_string_cmd (const char * name, enum command_class class, char ** var, const char * set_doc, const char * show_doc, const char * help_doc, cmd_sfunc_ftype * set_func, show_value_ftype * show_func, struct cmd_list_element ** set_list, struct cmd_list_element ** show_list)
Definition at line 573 of file cli-decode.c.
References add_setshow_cmd_full(), and var_string.
Referenced by _initialize_m32r_rom(), _initialize_remote_mips(), _initialize_tracepoint(), add_setshow_generic(), and init_main().
struct cmd_list_element* add_setshow_string_noescape_cmd (const char * name, enum command_class class, char ** var, const char * set_doc, const char * show_doc, const char * help_doc, cmd_sfunc_ftype * set_func, show_value_ftype * show_func, struct cmd_list_element ** set_list, struct cmd_list_element ** show_list) [read]
Definition at line 592 of file cli-decode.c.
References add_setshow_cmd_full(), set_cmd, and var_string_noescape.
Referenced by add_setshow_generic().
void add_setshow_uinteger_cmd (const char * name, enum command_class class, unsigned int * var, const char * set_doc, const char * show_doc, const char * help_doc, cmd_sfunc_ftype * set_func, show_value_ftype * show_func, struct cmd_list_element ** set_list, struct cmd_list_element ** show_list)
Definition at line 682 of file cli-decode.c.
References add_setshow_cmd_full(), and var_uinteger.
Referenced by _initialize_cli_cmds(), _initialize_frame(), _initialize_record(), _initialize_record_full(), add_setshow_generic(), init_main(), and initialize_utils().
void add_setshow_zinteger_cmd (const char * name, enum command_class class, int * var, const char * set_doc, const char * show_doc, const char * help_doc, cmd_sfunc_ftype * set_func, show_value_ftype * show_func, struct cmd_list_element ** set_list, struct cmd_list_element ** show_list)
Definition at line 707 of file cli-decode.c.
References add_setshow_cmd_full(), and var_zinteger.
Referenced by _initialize_alpha_tdep(), _initialize_cli_cmds(), _initialize_mips_tdep(), _initialize_remote_mips(), _initialize_ser_dos(), add_setshow_generic(), and init_main().
void add_setshow_zuinteger_cmd (const char * name, enum command_class class, unsigned int * var, const char * set_doc, const char * show_doc, const char * help_doc, cmd_sfunc_ftype * set_func, show_value_ftype * show_func, struct cmd_list_element ** set_list, struct cmd_list_element ** show_list)
Definition at line 751 of file cli-decode.c.
References add_setshow_cmd_full(), and var_zuinteger.
Referenced by _initialize_cris_tdep(), _initialize_darwin_inferior(), _initialize_dsbt_solib(), _initialize_dwarf2loc(), _initialize_frame(), _initialize_frv_solib(), _initialize_gdbtypes(), _initialize_linux_nat(), _initialize_machoread(), _initialize_mips_tdep(), _initialize_observer(), _initialize_record(), _initialize_remote_monitors(), _initialize_thread_db(), _initialize_xtensa_tdep(), and initialize_targets().
void add_setshow_zuinteger_unlimited_cmd (const char * name, enum command_class class, int * var, const char * set_doc, const char * show_doc, const char * help_doc, cmd_sfunc_ftype * set_func, show_value_ftype * show_func, struct cmd_list_element ** set_list, struct cmd_list_element ** show_list)
Definition at line 724 of file cli-decode.c.
References add_setshow_cmd_full(), and var_zuinteger_unlimited.
Referenced by _initialize_cli_cmds(), and _initialize_tracepoint().
void apropos_cmd (struct ui_file * stream, struct cmd_list_element * commandlist, struct re_pattern_buffer * regex, char * prefix)
Definition at line 881 of file cli-decode.c.
References cmd_list_element::abbrev_flag, apropos_cmd(), cmd_list_element::doc, cmd_list_element::name, cmd_list_element::next, cmd_list_element::prefixlist, cmd_list_element::prefixname, and print_help_for_command().
Referenced by apropos_cmd(), and apropos_command().
int cmd_cfunc_eq (struct cmd_list_element * cmd, void(*)(char *args, int from_tty) cfunc)
Definition at line 137 of file cli-decode.c.
References cmd_list_element::cfunc, do_cfunc(), cmd_list_element::func, and cmd_list_element::function.
Referenced by encode_actions_1(), is_complete_command(), trace_dump_actions(), and validate_actionline().
void cmd_func (struct cmd_list_element * cmd, char * args, int from_tty)
Definition at line 1879 of file cli-decode.c.
References _, cmd_func_p(), error(), and cmd_list_element::func.
Referenced by cmd_show_list(), execute_command(), gdbtk_call_command(), info_auto_load_cmd(), and show_remote_cmd().
int cmd_func_p (struct cmd_list_element * cmd)
Definition at line 1871 of file cli-decode.c.
References cmd_list_element::func.
Referenced by cmd_func(), and execute_command().
enum cmd_types cmd_type (struct cmd_list_element * cmd)
Definition at line 156 of file cli-decode.c.
References cmd_list_element::type.
static struct cmd_list_element * delete_cmd (const char * name, struct cmd_list_element ** list, struct cmd_list_element ** prehook, struct cmd_list_element ** prehookee, struct cmd_list_element ** posthook, struct cmd_list_element ** posthookee) [static, read]
Definition at line 775 of file cli-decode.c.
References cmd_list_element::alias_chain, cmd_list_element::aliases, cmd_list_element::cmd_pointer, cmd_list_element::context, cmd_list_element::destroyer, cmd_list_element::doc, DOC_ALLOCATED, cmd_list_element::flags, cmd_list_element::hook_post, cmd_list_element::hook_pre, cmd_list_element::hookee_post, cmd_list_element::hookee_pre, cmd_list_element::name, cmd_list_element::next, and xfree().
Referenced by add_alias_cmd(), and add_cmd().
struct cmd_list_element* deprecate_cmd (struct cmd_list_element * cmd, char * replacement) [read]
Definition at line 262 of file cli-decode.c.
References CMD_DEPRECATED, DEPRECATED_WARN_USER, cmd_list_element::flags, and cmd_list_element::replacement.
Referenced by _initialize_cp_namespace(), _initialize_record_full(), and add_deprecated_target_alias().
void deprecated_cmd_warning (const char * text)
Definition at line 1593 of file cli-decode.c.
References CMD_DEPRECATED, DEPRECATED_WARN_USER, cmd_list_element::flags, lookup_cmd_composition(), cmd_list_element::name, cmd_list_element::prefixname, printf_filtered(), and cmd_list_element::replacement.
Referenced by execute_command(), and lookup_cmd_1().
static void do_cfunc (struct cmd_list_element * c, char * args, int from_tty) [static]
Definition at line 105 of file cli-decode.c.
References cmd_list_element::cfunc, and cmd_list_element::function.
Referenced by cmd_cfunc_eq(), and set_cmd_cfunc().
static void do_sfunc (struct cmd_list_element * c, char * args, int from_tty) [static]
Definition at line 121 of file cli-decode.c.
References cmd_list_element::function, and cmd_list_element::sfunc.
Referenced by set_cmd_sfunc().
static void empty_sfunc (char * args, int from_tty, struct cmd_list_element * c) [static]
Definition at line 379 of file cli-decode.c.
Referenced by add_set_or_show_cmd().
static struct cmd_list_element * find_cmd (const char * command, int len, struct cmd_list_element * clist, int ignore_help_classes, int * nfound) [static, read]
Definition at line 1207 of file cli-decode.c.
References cmd_list_element::func, cmd_list_element::name, and cmd_list_element::next.
Referenced by lookup_cmd_1(), and lookup_cmd_composition().
static int find_command_name_length (const char * text) [static]
Definition at line 1230 of file cli-decode.c.
References p, and xdb_commands.
Referenced by lookup_cmd(), lookup_cmd_1(), and lookup_cmd_composition().
void* get_cmd_context (struct cmd_list_element * cmd)
Definition at line 150 of file cli-decode.c.
References cmd_list_element::context.
Referenced by call_dump_func(), catch_ada_exception_command(), catch_assert_command(), catch_catch_command(), catch_exec_command_1(), catch_fork_command_1(), catch_load_or_unload(), catch_rethrow_command(), catch_signal_command(), catch_syscall_command_1(), catch_throw_command(), cmdpy_function(), get_set_value(), get_show_value(), and VEC().
static void help_all (struct ui_file * stream) [static]
Definition at line 1068 of file cli-decode.c.
References cmd_list_element::abbrev_flag, cmd_list_element::class, cmdlist, fprintf_filtered(), cmd_list_element::func, help_cmd_list(), cmd_list_element::name, cmd_list_element::next, no_class, and print_help_for_command().
Referenced by help_cmd().
void help_cmd (char * arg, struct ui_file * stream)
Definition at line 936 of file cli-decode.c.
References all_classes, all_commands, cmd_list_element::class, cmdlist, cmd_list_element::doc, fprintf_filtered(), fputs_filtered(), cmd_list_element::func, help_all(), help_list(), cmd_list_element::hook_post, cmd_list_element::hook_pre, lookup_cmd(), cmd_list_element::name, cmd_list_element::prefixlist, and cmd_list_element::prefixname.
Referenced by help_command().
void help_cmd_list (struct cmd_list_element * list, enum command_class class, char * prefix, int recurse, struct ui_file * stream)
Definition at line 1179 of file cli-decode.c.
References cmd_list_element::abbrev_flag, all_classes, all_commands, cmd_list_element::class, class_user, cmd_list_element::func, help_cmd_list(), cmd_list_element::next, cmd_list_element::prefixlist, cmd_list_element::prefixname, and print_help_for_command().
Referenced by help_all(), help_cmd_list(), help_list(), and print_help_for_command().
void help_list (struct cmd_list_element * list, char * cmdtype, enum command_class class, struct ui_file * stream)
Definition at line 1012 of file cli-decode.c.
References all_classes, fprintf_filtered(), fputs_filtered(), help_cmd_list(), len, and wrap_here().
Referenced by append_command(), binary_append_command(), binary_dump_command(), dump_command(), go32_info_dos_command(), help_cmd(), ihex_dump_command(), info_command(), info_spu_command(), info_w32_command(), macro_command(), maint_cplus_command(), maintenance_command(), maintenance_info_command(), maintenance_print_command(), maintenance_set_cmd(), overlay_command(), remote_command(), save_command(), serial_set_cmd(), set_ada_command(), set_arm_command(), set_backtrace_cmd(), set_check(), set_dcache_command(), set_debug(), set_dwarf2_cmd(), set_history(), set_mips_command(), set_powerpc_command(), set_print(), set_print_raw(), set_print_type(), set_ravenscar_command(), set_record_command(), set_record_full_command(), set_remote_cmd(), set_sh_command(), set_spu_command(), set_tcp_cmd(), set_tdesc_cmd(), show_mips_command(), show_sh_command(), show_spu_command(), show_tcp_cmd(), srec_dump_command(), tekhex_dump_command(), tui_command(), tui_reg_command(), unset_command(), unset_tdesc_cmd(), and user_set_python().
struct cmd_list_element* lookup_cmd (const char ** line, struct cmd_list_element * list, char * cmdtype, int allow_unknown, int ignore_help_classes) [read]
Definition at line 1471 of file cli-decode.c.
References _, cmd_list_element::allow_unknown, CMD_LIST_AMBIGUOUS, error(), find_command_name_length(), int, len, lookup_cmd_1(), cmd_list_element::name, cmd_list_element::next, cmd_list_element::prefixlist, cmd_list_element::prefixname, set_cmd, cmd_list_element::type, and undef_cmd_error().
Referenced by add_alias_cmd(), add_setshow_generic(), define_command(), document_command(), encode_actions_1(), execute_command(), help_cmd(), show_user(), trace_dump_actions(), validate_actionline(), and validate_comname().
struct cmd_list_element* lookup_cmd_1 (const char ** text, struct cmd_list_element * clist, struct cmd_list_element ** result_list, int ignore_help_classes) [read]
Definition at line 1328 of file cli-decode.c.
References CMD_LIST_AMBIGUOUS, cmd_list_element::cmd_pointer, deprecated_cmd_warning(), DEPRECATED_WARN_USER, find_cmd(), find_command_name_length(), cmd_list_element::flags, len, line, lookup_cmd_1(), memcpy(), and cmd_list_element::prefixlist.
Referenced by alias_command(), gdbpy_parse_command_name(), lookup_cmd(), lookup_cmd_1(), set_verbose(), and valid_command_p().
int lookup_cmd_composition (const char * text, struct cmd_list_element ** alias, struct cmd_list_element ** prefix_cmd, struct cmd_list_element ** cmd)
Definition at line 1667 of file cli-decode.c.
References CMD_LIST_AMBIGUOUS, cmd_list_element::cmd_pointer, cmdlist, find_cmd(), find_command_name_length(), len, memcpy(), and cmd_list_element::prefixlist.
Referenced by deprecated_cmd_warning(), gdbtk_interpreter_init(), and maintenance_do_deprecate().
static struct cmd_list_element* lookup_cmd_for_prefixlist (struct cmd_list_element ** key, struct cmd_list_element * list) [static, read]
Definition at line 52 of file cli-decode.c.
References cmd_list_element::next, p, and cmd_list_element::prefixlist.
Referenced by set_cmd_prefix().
void not_just_help_class_command (char * args, int from_tty)
Definition at line 371 of file cli-decode.c.
void print_doc_line (struct ui_file * stream, char * str)
Definition at line 1111 of file cli-decode.c.
References fputs_filtered(), line_buffer, p, xfree(), and xmalloc().
Referenced by deprecated_show_value_hack(), and print_help_for_command().
static void print_help_for_command (struct cmd_list_element * c, char * prefix, int recurse, struct ui_file * stream) [static]
Definition at line 1146 of file cli-decode.c.
References cmd_list_element::abbrev_flag, all_commands, cmd_list_element::doc, fprintf_filtered(), fputs_filtered(), help_cmd_list(), cmd_list_element::name, cmd_list_element::prefixlist, cmd_list_element::prefixname, and print_doc_line().
Referenced by apropos_cmd(), help_all(), and help_cmd_list().
void set_cmd_cfunc (struct cmd_list_element * cmd, cmd_cfunc_ftype * cfunc)
Definition at line 111 of file cli-decode.c.
References cmd_list_element::cfunc, do_cfunc(), cmd_list_element::func, and cmd_list_element::function.
Referenced by add_cmd(), and gdbtk_interpreter_init().
void set_cmd_completer (struct cmd_list_element * cmd, completer_ftype * completer)
Definition at line 162 of file cli-decode.c.
References cmd_list_element::completer.
void set_cmd_context (struct cmd_list_element * cmd, void * context)
Definition at line 144 of file cli-decode.c.
References cmd_list_element::context.
Referenced by add_catch_command(), add_cmd(), add_dump_command(), add_setshow_generic(), and cmdpy_init().
static void set_cmd_prefix (struct cmd_list_element * c, struct cmd_list_element ** list) [static]
Definition at line 75 of file cli-decode.c.
References cmd_list_element::cmd_pointer, lookup_cmd_for_prefixlist(), cmd_list_element::next, p, cmd_list_element::prefix, and setlist.
Referenced by add_alias_cmd(), add_prefix_cmd(), and add_setshow_cmd_full().
void set_cmd_sfunc (struct cmd_list_element * cmd, cmd_sfunc_ftype * sfunc)
Definition at line 127 of file cli-decode.c.
References do_sfunc(), cmd_list_element::func, cmd_list_element::function, and cmd_list_element::sfunc.
Referenced by add_catch_command(), add_set_or_show_cmd(), and add_setshow_cmd_full().
static void undef_cmd_error (const char * cmdtype, const char * q) [static]
Definition at line 1446 of file cli-decode.c.
References _, and error().
Referenced by lookup_cmd().
int valid_user_defined_cmd_name_p (const char * name)
Definition at line 1268 of file cli-decode.c.
References p.
Referenced by alias_command().
VEC (char_ptr) [static]
Definition at line 638 of file cli-decode.c.
Variable Documentation
const char* const auto_boolean_enums[] = { "on", "off", "auto", NULL }
Definition at line 497 of file cli-decode.c.
Referenced by add_setshow_auto_boolean_cmd(), and do_set_command().