GDB (xrefs): /home/stan/gdb/src/gdb/cli/cli-setshow.c File Reference
/home/stan/gdb/src/gdb/cli/cli-setshow.c File Reference
#include "defs.h"
#include "readline/tilde.h"
#include "value.h"
#include <ctype.h>
#include "gdb_string.h"
#include "arch-utils.h"
#include "observer.h"
#include "ui-out.h"
#include "cli/cli-decode.h"
#include "cli/cli-cmds.h"
#include "cli/cli-setshow.h"
#include "cli/cli-utils.h"
Functions
static int notify_command_param_changed_p (int param_changed, struct cmd_list_element *c)
static enum auto_boolean parse_auto_binary_operation (const char *arg)
int parse_cli_boolean_value (char *arg)
void deprecated_show_value_hack (struct ui_file *ignore_file, int ignore_from_tty, struct cmd_list_element *c, const char *value)
static int is_unlimited_literal (const char *arg)
void do_set_command (char *arg, int from_tty, struct cmd_list_element *c)
void do_show_command (char *arg, int from_tty, struct cmd_list_element *c)
void cmd_show_list (struct cmd_list_element *list, int from_tty, char *prefix)
Function Documentation
void cmd_show_list (struct cmd_list_element * list, int from_tty, char * prefix)
Definition at line 673 of file cli-setshow.c.
References cmd_list_element::abbrev_flag, cmd_list_element::class, cmd_func(), cmd_show_list(), current_uiout, do_cleanups(), do_show_command(), make_cleanup_ui_out_tuple_begin_end(), cmd_list_element::name, cmd_list_element::next, no_set_class, cmd_list_element::prefixlist, cmd_list_element::prefixname, show_cmd, strstr(), cmd_list_element::type, ui_out_field_string(), ui_out_is_mi_like_p(), and ui_out_text().
Referenced by cmd_show_list(), maintenance_show_cmd(), serial_show_cmd(), show_ada_command(), show_arm_command(), show_auto_load_cmd(), show_backtrace_cmd(), show_check(), show_command(), show_dcache_command(), show_debug(), show_dwarf2_cmd(), show_history(), show_per_command_cmd(), show_powerpc_command(), show_print(), show_print_raw(), show_print_type(), show_ravenscar_command(), show_record_command(), show_record_full_command(), show_tdesc_cmd(), and user_show_python().
void deprecated_show_value_hack (struct ui_file * ignore_file, int ignore_from_tty, struct cmd_list_element * c, const char * value)
Definition at line 106 of file cli-setshow.c.
References deprecated_show_value_hack, cmd_list_element::doc, gdb_stdout, print_doc_line(), printf_filtered(), var_enum, var_filename, var_optional_filename, var_string, var_string_noescape, and cmd_list_element::var_type.
void do_set_command (char * arg, int from_tty, struct cmd_list_element * c)
Definition at line 151 of file cli-setshow.c.
References _, cleanup::arg, auto_boolean_enums, deprecated_set_hook, cmd_list_element::enums, error(), error_no_arg(), cmd_list_element::func, gdb_assert, get_current_arch(), is_unlimited_literal(), len, LONGEST, make_cleanup(), memcpy(), cmd_list_element::name, name, notify_command_param_changed_p(), observer_notify_command_param_changed(), p, parse_and_eval_long(), parse_auto_binary_operation(), parse_cli_boolean_value(), parse_escape(), plongest(), cmd_list_element::prefix, cmd_list_element::prefixlist, set_cmd, setlist, strchr(), cmd_list_element::type, cmd_list_element::var, var_auto_boolean, var_boolean, var_enum, var_filename, var_integer, var_optional_filename, var_string, var_string_noescape, cmd_list_element::var_type, var_uinteger, var_zinteger, var_zuinteger, var_zuinteger_unlimited, xfree(), xmalloc(), xrealloc(), and xsnprintf().
Referenced by execute_command(), set_auto_load_cmd(), and set_per_command_cmd().
void do_show_command (char * arg, int from_tty, struct cmd_list_element * c)
Definition at line 569 of file cli-setshow.c.
References _, AUTO_BOOLEAN_AUTO, AUTO_BOOLEAN_FALSE, AUTO_BOOLEAN_TRUE, current_uiout, deprecated_show_value_hack, do_cleanups(), error(), fprintf_filtered(), fputs_filtered(), fputstr_filtered(), cmd_list_element::func, gdb_assert, gdb_stdout, internal_error(), make_cleanup(), make_cleanup_ui_file_delete(), mem_fileopen(), cmd_list_element::pre_show_hook, show_cmd, cmd_list_element::show_value_func, cmd_list_element::type, ui_file_xstrdup(), ui_out_field_stream(), ui_out_is_mi_like_p(), cmd_list_element::var, var_auto_boolean, var_boolean, var_enum, var_filename, var_integer, var_optional_filename, var_string, var_string_noescape, cmd_list_element::var_type, var_uinteger, var_zinteger, var_zuinteger, var_zuinteger_unlimited, and xfree().
Referenced by cmd_show_list(), execute_command(), and show_remote_cmd().
static int is_unlimited_literal (const char * arg) [static]
Definition at line 134 of file cli-setshow.c.
References len, and skip_spaces_const().
Referenced by do_set_command().
static int notify_command_param_changed_p (int param_changed, struct cmd_list_element * c) [static]
Definition at line 36 of file cli-setshow.c.
References cmd_list_element::class, class_deprecated, class_maintenance, and class_obscure.
Referenced by do_set_command().
static enum auto_boolean parse_auto_binary_operation (const char * arg) [static]
Definition at line 50 of file cli-setshow.c.
References _, AUTO_BOOLEAN_AUTO, AUTO_BOOLEAN_FALSE, AUTO_BOOLEAN_TRUE, and error().
Referenced by do_set_command().
int parse_cli_boolean_value (char * arg)
Definition at line 79 of file cli-setshow.c.
Referenced by do_set_command(), and set_per_command_cmd().