GDB (xrefs): /home/stan/gdb/src/gdb/cli/cli-logging.c File Reference
/home/stan/gdb/src/gdb/cli/cli-logging.c File Reference
#include "defs.h"
#include "gdbcmd.h"
#include "ui-out.h"
#include "interps.h"
#include "gdb_assert.h"
#include "gdb_string.h"
Classes
struct saved_output_files
Functions
static void show_logging_filename (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static void set_logging_overwrite (char *args, int from_tty, struct cmd_list_element *c)
static void show_logging_overwrite (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static void set_logging_redirect (char *args, int from_tty, struct cmd_list_element *c)
static void show_logging_redirect (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static void pop_output_files (void)
static void handle_redirections (int from_tty)
static void set_logging_on (char *args, int from_tty)
static void set_logging_off (char *args, int from_tty)
static void set_logging_command (char *args, int from_tty)
static void show_logging_command (char *args, int from_tty)
void _initialize_cli_logging (void)
Variables
static struct saved_output_files saved_output
static char * saved_filename
static char * logging_filename
static int logging_overwrite
static int logging_redirect
static struct ui_file * logging_no_redirect_file
initialize_file_ftype _initialize_cli_logging
Function Documentation
void _initialize_cli_logging (void)
Definition at line 328 of file cli-logging.c.
References _, _initialize_cli_logging, add_cmd(), add_prefix_cmd(), add_setshow_boolean_cmd(), add_setshow_filename_cmd(), class_support, logging_filename, logging_overwrite, logging_redirect, set_logging_command(), set_logging_off(), set_logging_on(), set_logging_overwrite(), set_logging_redirect(), setlist, show_logging_command(), show_logging_filename(), show_logging_overwrite(), show_logging_redirect(), and showlist.
static void handle_redirections (int from_tty) [static]
Definition at line 188 of file cli-logging.c.
References _, current_interp_set_logging(), current_uiout, discard_cleanups(), saved_output_files::err, fprintf_unfiltered(), gdb_assert, gdb_fopen(), gdb_stderr, gdb_stdlog, gdb_stdout, gdb_stdtarg, gdb_stdtargerr, saved_output_files::log, logging_filename, logging_overwrite, logging_redirect, make_cleanup_ui_file_delete(), saved_output_files::out, perror_with_name(), saved_filename, saved_output, saved_output_files::targ, saved_output_files::targerr, tee_file_new(), ui_out_is_mi_like_p(), ui_out_redirect(), and warning().
Referenced by set_logging_on().
static void pop_output_files (void) [static]
Definition at line 156 of file cli-logging.c.
References current_interp_set_logging(), current_uiout, saved_output_files::err, gdb_stderr, gdb_stdlog, gdb_stdout, gdb_stdtarg, gdb_stdtargerr, saved_output_files::log, saved_output_files::out, saved_output, saved_output_files::targ, saved_output_files::targerr, ui_file_delete(), and ui_out_redirect().
Referenced by set_logging_off().
static void set_logging_command (char * args, int from_tty) [static]
Definition at line 283 of file cli-logging.c.
References _, and printf_unfiltered().
Referenced by _initialize_cli_logging().
static void set_logging_off (char * args, int from_tty) [static]
Definition at line 270 of file cli-logging.c.
References fprintf_unfiltered(), gdb_stdout, pop_output_files(), saved_filename, and xfree().
Referenced by _initialize_cli_logging().
static void set_logging_on (char * args, int from_tty) [static]
Definition at line 257 of file cli-logging.c.
References handle_redirections(), logging_filename, and xfree().
Referenced by _initialize_cli_logging().
static void set_logging_overwrite (char * args, int from_tty, struct cmd_list_element * c) [static]
Definition at line 53 of file cli-logging.c.
References _, saved_filename, and warning().
Referenced by _initialize_cli_logging().
static void set_logging_redirect (char * args, int from_tty, struct cmd_list_element * c) [static]
Definition at line 80 of file cli-logging.c.
References _, current_interp_set_logging(), current_uiout, do_cleanups(), fprintf_unfiltered(), gdb_assert, gdb_stderr, gdb_stdlog, gdb_stdout, gdb_stdtarg, gdb_stdtargerr, logging_filename, logging_no_redirect_file, logging_redirect, make_cleanup(), make_cleanup_ui_file_delete(), null_cleanup(), saved_output_files::out, perror_with_name(), saved_filename, saved_output, tee_file_new(), ui_out_redirect(), and warning().
Referenced by _initialize_cli_logging().
static void show_logging_command (char * args, int from_tty) [static]
Definition at line 294 of file cli-logging.c.
References _, logging_filename, logging_overwrite, logging_redirect, printf_unfiltered(), and saved_filename.
Referenced by _initialize_cli_logging().
static void show_logging_filename (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 43 of file cli-logging.c.
References _, and fprintf_filtered().
Referenced by _initialize_cli_logging().
static void show_logging_overwrite (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 61 of file cli-logging.c.
References _, and fprintf_filtered().
Referenced by _initialize_cli_logging().
static void show_logging_redirect (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 148 of file cli-logging.c.
References _, and fprintf_filtered().
Referenced by _initialize_cli_logging().
Variable Documentation
initialize_file_ftype _initialize_cli_logging
Referenced by _initialize_cli_logging(), and initialize_all_files().
char* logging_filename [static]
Definition at line 41 of file cli-logging.c.
Referenced by _initialize_cli_logging(), handle_redirections(), set_logging_on(), set_logging_redirect(), and show_logging_command().
struct ui_file* logging_no_redirect_file [static]
Definition at line 77 of file cli-logging.c.
Referenced by set_logging_redirect().
int logging_overwrite [static]
Definition at line 50 of file cli-logging.c.
Referenced by _initialize_cli_logging(), handle_redirections(), and show_logging_command().
int logging_redirect [static]
Definition at line 71 of file cli-logging.c.
Referenced by _initialize_cli_logging(), handle_redirections(), set_logging_redirect(), and show_logging_command().
char* saved_filename [static]
Definition at line 39 of file cli-logging.c.
Referenced by handle_redirections(), set_logging_off(), set_logging_overwrite(), set_logging_redirect(), and show_logging_command().
struct saved_output_files saved_output [static]
Definition at line 38 of file cli-logging.c.
Referenced by handle_redirections(), pop_output_files(), and set_logging_redirect().