GDB (xrefs): /home/stan/gdb/src/gdb/cli/cli-cmds.h File Reference
/home/stan/gdb/src/gdb/cli/cli-cmds.h File Reference
Functions
void init_cmd_lists (void)
void init_cli_cmds (void)
int is_complete_command (struct cmd_list_element *cmd)
void cd_command (char *, int)
void quit_command (char *, int)
void source_script (const char *, int)
int find_and_open_script (const char *file, int search_path, FILE **streamp, char **full_path)
Variables
struct cmd_list_element * cmdlist
struct cmd_list_element * infolist
struct cmd_list_element * enablelist
struct cmd_list_element * disablelist
struct cmd_list_element * deletelist
struct cmd_list_element * detachlist
struct cmd_list_element * killlist
struct cmd_list_element * stoplist
struct cmd_list_element * setlist
struct cmd_list_element * unsetlist
struct cmd_list_element * showlist
struct cmd_list_element * sethistlist
struct cmd_list_element * showhistlist
struct cmd_list_element * unsethistlist
struct cmd_list_element * maintenancelist
struct cmd_list_element * maintenanceinfolist
struct cmd_list_element * maintenanceprintlist
struct cmd_list_element * setprintlist
struct cmd_list_element * showprintlist
struct cmd_list_element * setdebuglist
struct cmd_list_element * showdebuglist
struct cmd_list_element * setchecklist
struct cmd_list_element * showchecklist
int source_verbose
int trace_commands
Function Documentation
void cd_command (char * , int)
Definition at line 350 of file cli-cmds.c.
References current_directory, do_cleanups(), dont_repeat(), forget_cached_source_info(), gdb_dirbuf, len, make_cleanup(), memmove(), p, perror_with_name(), pwd_command(), savestring(), and xfree().
Referenced by _initialize_cli_cmds(), and captured_main().
int find_and_open_script (const char * file, int search_path, FILE ** streamp, char ** full_path)
Definition at line 476 of file cli-cmds.c.
References do_cleanups(), make_cleanup(), openp(), OPF_RETURN_REALPATH, OPF_SEARCH_IN_PATH, OPF_TRY_CWD_FIRST, source_path, and xfree().
Referenced by source_script_with_search().
void init_cli_cmds (void)
Definition at line 1874 of file cli-cmds.c.
References _, add_cmd(), class_support, gdbinit, source_command(), and xstrprintf().
Referenced by gdb_init().
void init_cmd_lists (void)
Definition at line 1561 of file cli-cmds.c.
References max_user_call_depth.
Referenced by gdb_init().
int is_complete_command (struct cmd_list_element * cmd)
Definition at line 302 of file cli-cmds.c.
References cmd_cfunc_eq(), and complete_command().
Referenced by execute_command().
void quit_command (char * , int)
Definition at line 323 of file cli-cmds.c.
void source_script (const char * , int)
Definition at line 599 of file cli-cmds.c.
References source_script_with_search().
Referenced by captured_main().
Variable Documentation
struct cmd_list_element* cmdlist
Definition at line 105 of file cli-cmds.c.
struct cmd_list_element* deletelist
Definition at line 125 of file cli-cmds.c.
struct cmd_list_element* detachlist
Definition at line 129 of file cli-cmds.c.
struct cmd_list_element* disablelist
Definition at line 117 of file cli-cmds.c.
struct cmd_list_element* enablelist
Definition at line 113 of file cli-cmds.c.
struct cmd_list_element* infolist
Definition at line 109 of file cli-cmds.c.
struct cmd_list_element* killlist
Definition at line 133 of file cli-cmds.c.
struct cmd_list_element* maintenanceinfolist
Definition at line 165 of file cli-cmds.c.
struct cmd_list_element* maintenancelist
Definition at line 161 of file cli-cmds.c.
struct cmd_list_element* maintenanceprintlist
Definition at line 169 of file cli-cmds.c.
struct cmd_list_element* setchecklist
Definition at line 179 of file cli-cmds.c.
struct cmd_list_element* setdebuglist
Definition at line 175 of file cli-cmds.c.
struct cmd_list_element* sethistlist
Definition at line 149 of file cli-cmds.c.
struct cmd_list_element* setlist
Definition at line 137 of file cli-cmds.c.
struct cmd_list_element* setprintlist
Definition at line 171 of file cli-cmds.c.
struct cmd_list_element* showchecklist
Definition at line 181 of file cli-cmds.c.
struct cmd_list_element* showdebuglist
Definition at line 177 of file cli-cmds.c.
struct cmd_list_element* showhistlist
Definition at line 153 of file cli-cmds.c.
struct cmd_list_element* showlist
Definition at line 145 of file cli-cmds.c.
struct cmd_list_element* showprintlist
Definition at line 173 of file cli-cmds.c.
int source_verbose
Definition at line 185 of file cli-cmds.c.
Referenced by print_command_trace(), source_command(), and source_verbose_cleanup().
struct cmd_list_element* stoplist
Definition at line 121 of file cli-cmds.c.
int trace_commands
Definition at line 186 of file cli-cmds.c.
Referenced by _initialize_cli_cmds(), and print_command_trace().
struct cmd_list_element* unsethistlist
Definition at line 157 of file cli-cmds.c.
struct cmd_list_element* unsetlist
Definition at line 141 of file cli-cmds.c.