GDB (xrefs): /home/stan/gdb/src/gdb/cli/cli-cmds.c File Reference
/home/stan/gdb/src/gdb/cli/cli-cmds.c File Reference
#include "defs.h"
#include "exceptions.h"
#include "arch-utils.h"
#include "dyn-string.h"
#include "readline/readline.h"
#include "readline/tilde.h"
#include "completer.h"
#include "target.h"
#include "gdb_wait.h"
#include "gdb_regex.h"
#include "gdb_string.h"
#include "gdb_vfork.h"
#include "linespec.h"
#include "expression.h"
#include "frame.h"
#include "value.h"
#include "language.h"
#include "filenames.h"
#include "objfiles.h"
#include "source.h"
#include "disasm.h"
#include "tracepoint.h"
#include "filestuff.h"
#include "ui-out.h"
#include "top.h"
#include "cli/cli-decode.h"
#include "cli/cli-script.h"
#include "cli/cli-setshow.h"
#include "cli/cli-cmds.h"
#include "cli/cli-utils.h"
#include "python/python.h"
#include <fcntl.h>
Functions
static void complete_command (char *, int)
static void echo_command (char *, int)
static void pwd_command (char *, int)
static void show_version (char *, int)
static void help_command (char *, int)
static void show_command (char *, int)
static void info_command (char *, int)
static void show_debug (char *, int)
static void set_debug (char *, int)
static void show_user (char *, int)
static void make_command (char *, int)
static void shell_escape (char *, int)
static void edit_command (char *, int)
static void list_command (char *, int)
static void ambiguous_line_spec (struct symtabs_and_lines *)
static void filter_sals (struct symtabs_and_lines *)
void error_no_arg (char *why)
int is_complete_command (struct cmd_list_element *c)
static void show_configuration (char *args, int from_tty)
void quit_command (char *args, int from_tty)
void cd_command (char *dir, int from_tty)
static void show_script_ext_mode (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
int find_and_open_script (const char *script_file, int search_path, FILE **streamp, char **full_pathp)
static void source_script_from_stream (FILE *stream, const char *file)
static void source_script_with_search (const char *file, int from_tty, int search_path)
void source_script (const char *file, int from_tty)
static void source_verbose_cleanup (void *old_value)
static void source_command (char *args, int from_tty)
static void print_disassembly (struct gdbarch *gdbarch, const char *name, CORE_ADDR low, CORE_ADDR high, int flags)
static void disassemble_current_function (int flags)
static void disassemble_command (char *arg, int from_tty)
static void apropos_command (char *searchstr, int from_tty)
static dyn_string_t argv_to_dyn_string (char **argv, int n)
static int valid_command_p (const char *command)
static void alias_command (char *args, int from_tty)
static int compare_symtabs (const void *a, const void *b)
void init_cmd_lists (void)
static void show_info_verbose (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static void show_history_expansion_p (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static void show_remote_debug (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static void show_remote_timeout (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static void show_max_user_call_depth (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
void _initialize_cli_cmds (void)
void init_cli_cmds (void)
Variables
unsigned int max_user_call_depth
struct cmd_list_element * cmdlist
struct cmd_list_element * infolist
struct cmd_list_element * enablelist
struct cmd_list_element * disablelist
struct cmd_list_element * stoplist
struct cmd_list_element * deletelist
struct cmd_list_element * detachlist
struct cmd_list_element * killlist
struct cmd_list_element * setlist
struct cmd_list_element * unsetlist
struct cmd_list_element * showlist
struct cmd_list_element * sethistlist
struct cmd_list_element * showhistlist
struct cmd_list_element * unsethistlist
struct cmd_list_element * maintenancelist
struct cmd_list_element * maintenanceinfolist
struct cmd_list_element * maintenanceprintlist
struct cmd_list_element * setprintlist
struct cmd_list_element * showprintlist
struct cmd_list_element * setdebuglist
struct cmd_list_element * showdebuglist
struct cmd_list_element * setchecklist
struct cmd_list_element * showchecklist
int source_verbose = 0
int trace_commands = 0
static const char script_ext_off [] = "off"
static const char script_ext_soft [] = "soft"
static const char script_ext_strict [] = "strict"
static const char *const script_ext_enums []
static const char * script_ext_mode = script_ext_soft
initialize_file_ftype _initialize_cli_cmds
Function Documentation
void _initialize_cli_cmds (void)
Definition at line 1618 of file cli-cmds.c.
References _, add_cmd(), add_com(), add_com_alias(), add_info(), add_prefix_cmd(), add_setshow_boolean_cmd(), add_setshow_enum_cmd(), add_setshow_uinteger_cmd(), add_setshow_zinteger_cmd(), add_setshow_zuinteger_unlimited_cmd(), alias_command(), apropos_command(), cd_command(), class_alias, class_breakpoint, class_files, class_info, class_maintenance, class_obscure, class_run, class_stack, class_support, class_user, class_vars, class_xdb, complete_command(), cmd_list_element::completer, dbx_commands, disassemble_command(), echo_command(), edit_command(), help_command(), history_expansion_p, info_command(), info_verbose, list_command(), make_command(), max_user_call_depth, no_class, no_set_class, pwd_command(), quit_command(), remote_debug, remote_timeout, script_ext_enums, script_ext_mode, set_debug(), set_history(), set_verbose(), shell_escape(), show_command(), show_commands(), show_configuration(), show_debug(), show_history(), show_history_expansion_p(), show_info_verbose(), show_max_user_call_depth(), show_remote_debug(), show_remote_timeout(), show_script_ext_mode(), show_user(), show_version(), trace_commands, and xdb_commands.
static void alias_command (char * args, int from_tty) [static]
Definition at line 1325 of file cli-cmds.c.
References _, cmd_list_element::abbrev_flag, add_alias_cmd(), add_com_alias(), argv_to_dyn_string(), class_alias, do_cleanups(), error(), gdb_assert, gdb_buildargv(), lookup_cmd_1(), make_cleanup(), make_cleanup_dyn_string_delete(), make_cleanup_freeargv(), N_, cmd_list_element::prefixlist, strchr(), valid_command_p(), valid_user_defined_cmd_name_p(), and xfree().
Referenced by _initialize_cli_cmds().
static void ambiguous_line_spec (struct symtabs_and_lines * sals) [static]
Definition at line 1456 of file cli-cmds.c.
References _, symtab_and_line::line, symtabs_and_lines::nelts, printf_filtered(), symtabs_and_lines::sals, symtab_and_line::symtab, and symtab_to_filename_for_display().
Referenced by edit_command(), and list_command().
static void apropos_command (char * searchstr, int from_tty) [static]
Definition at line 1249 of file cli-cmds.c.
References _, apropos_cmd(), code, do_cleanups(), error(), gdb_stdout, get_regcomp_error(), make_cleanup(), make_regfree_cleanup(), and xfree().
Referenced by _initialize_cli_cmds().
static dyn_string_t argv_to_dyn_string (char ** argv, int n) [static]
Definition at line 1283 of file cli-cmds.c.
References gdb_assert.
Referenced by alias_command().
void cd_command (char * dir, int from_tty)
Definition at line 350 of file cli-cmds.c.
References current_directory, do_cleanups(), dont_repeat(), forget_cached_source_info(), gdb_dirbuf, len, make_cleanup(), memmove(), p, perror_with_name(), pwd_command(), savestring(), and xfree().
Referenced by _initialize_cli_cmds(), and captured_main().
static int compare_symtabs (const void * a, const void * b) [static]
Definition at line 1469 of file cli-cmds.c.
References symtab::dirname, symtab::filename, symtab_and_line::line, and symtab_and_line::symtab.
Referenced by filter_sals().
static void complete_command (char * arg, int from_tty) [static]
Definition at line 244 of file cli-cmds.c.
References compare_strings(), dont_repeat(), memcpy(), point, printf_unfiltered(), qsort, size, strchr(), VEC, VEC_address, VEC_free, VEC_iterate, VEC_length, and xfree().
Referenced by _initialize_cli_cmds(), and is_complete_command().
static void disassemble_command (char * arg, int from_tty) [static]
Definition at line 1120 of file cli-cmds.c.
References _, disassemble_current_function(), DISASSEMBLY_OMIT_FNAME, DISASSEMBLY_RAW_INSN, DISASSEMBLY_SOURCE, error(), find_pc_partial_function(), flags, gdbarch_deprecated_function_start_offset(), get_current_arch(), name, p, parse_and_eval_address(), parse_to_comma_and_eval(), print_disassembly(), skip_spaces_const(), tui_active, tui_get_low_disassembly_address(), and value_as_address().
Referenced by _initialize_cli_cmds().
static void disassemble_current_function (int flags) [static]
Definition at line 1081 of file cli-cmds.c.
References _, error(), find_pc_partial_function(), gdbarch_deprecated_function_start_offset(), get_frame_address_in_block(), get_frame_arch(), get_selected_frame(), name, print_disassembly(), tui_active, and tui_get_low_disassembly_address().
Referenced by disassemble_command().
static void echo_command (char * text, int from_tty) [static]
Definition at line 670 of file cli-cmds.c.
References gdb_flush(), gdb_stdout, get_current_arch(), p, parse_escape(), printf_filtered(), and wrap_here().
Referenced by _initialize_cli_cmds().
static void edit_command (char * arg, int from_tty) [static]
Definition at line 760 of file cli-cmds.c.
References _, ambiguous_line_spec(), decode_line_1(), DECODE_LINE_LIST_MODE, error(), filter_sals(), find_pc_function(), get_current_source_symtab_and_line(), get_lines_to_list(), get_objfile_arch(), hex_string(), symtab_and_line::line, symtabs_and_lines::nelts, symtab::objfile, p, paddress(), symtab_and_line::pc, printf_filtered(), symtabs_and_lines::sals, set_default_source_symtab_and_line(), shell_escape(), SYMBOL_PRINT_NAME, symtab_and_line::symtab, symtab_to_filename_for_display(), symtab_to_fullname(), xfree(), and xstrprintf().
Referenced by _initialize_cli_cmds().
void error_no_arg (char * why)
Definition at line 207 of file cli-cmds.c.
References _, and error().
Referenced by advance_command(), agent_command_1(), bsd_kvm_pcb_cmd(), bsd_kvm_proc_cmd(), condition_command(), decode_line_2(), do_set_command(), gdbsim_load(), generic_load(), get_selections(), get_tracepoint_by_number(), go32_pte_for_address(), handle_command(), ignore_command(), interpreter_exec_cmd(), jump_command(), maint_agent_printf_command(), map_breakpoint_numbers(), map_display_numbers(), mem_command(), monitor_load(), parse_exp_in_context_1(), parse_pid_to_attach(), pipe_windows_open(), proc_trace_syscalls(), remote_delete_command(), remote_get_command(), remote_put_command(), set_environment_command(), signal_command(), sym_info(), tk_command(), trace_save_command(), trace_variable_command(), ui_printf(), validate_comname(), x_command(), and xdb_handle_command().
static void filter_sals (struct symtabs_and_lines * sals) [static]
Definition at line 1505 of file cli-cmds.c.
References compare_symtabs(), current_program_space, symtabs_and_lines::nelts, symtab_and_line::pspace, qsort, symtabs_and_lines::sals, symtab_and_line::symtab, and xfree().
Referenced by edit_command(), and list_command().
int find_and_open_script (const char * script_file, int search_path, FILE ** streamp, char ** full_pathp)
Definition at line 476 of file cli-cmds.c.
References do_cleanups(), make_cleanup(), openp(), OPF_RETURN_REALPATH, OPF_SEARCH_IN_PATH, OPF_TRY_CWD_FIRST, source_path, and xfree().
Referenced by source_script_with_search().
static void help_command (char * command, int from_tty) [static]
Definition at line 236 of file cli-cmds.c.
References gdb_stdout, and help_cmd().
Referenced by _initialize_cli_cmds().
static void info_command (char * arg, int from_tty) [static]
Definition at line 217 of file cli-cmds.c.
References _, gdb_stdout, help_list(), and printf_unfiltered().
Referenced by _initialize_cli_cmds().
void init_cli_cmds (void)
Definition at line 1874 of file cli-cmds.c.
References _, add_cmd(), class_support, gdbinit, source_command(), and xstrprintf().
Referenced by gdb_init().
void init_cmd_lists (void)
Definition at line 1561 of file cli-cmds.c.
References max_user_call_depth.
Referenced by gdb_init().
int is_complete_command (struct cmd_list_element * c)
Definition at line 302 of file cli-cmds.c.
References cmd_cfunc_eq(), and complete_command().
Referenced by execute_command().
static void list_command (char * arg, int from_tty) [static]
Definition at line 859 of file cli-cmds.c.
References _, ambiguous_line_spec(), decode_line_1(), DECODE_LINE_LIST_MODE, error(), filter_sals(), find_pc_function(), get_current_source_symtab_and_line(), get_first_line_listed(), get_lines_to_list(), get_objfile_arch(), have_full_symbols(), have_partial_symbols(), hex_string(), symtab_and_line::line, max, symtabs_and_lines::nelts, symtab::objfile, p, paddress(), symtab_and_line::pc, print_source_lines(), printf_filtered(), symtabs_and_lines::sals, set_default_source_symtab_and_line(), SYMBOL_PRINT_NAME, symtab_and_line::symtab, symtab_to_filename_for_display(), and xfree().
Referenced by _initialize_cli_cmds().
static void make_command (char * arg, int from_tty) [static]
Definition at line 1203 of file cli-cmds.c.
References p, shell_escape(), and xmalloc().
Referenced by _initialize_cli_cmds().
static void print_disassembly (struct gdbarch * gdbarch, const char * name, CORE_ADDR low, CORE_ADDR high, int flags) [static]
Definition at line 1049 of file cli-cmds.c.
References current_uiout, DISASSEM_WIN, gdb_disassembly(), gdb_flush(), gdb_stdout, paddress(), printf_filtered(), tui_is_window_visible(), and tui_show_assembly().
Referenced by disassemble_command(), and disassemble_current_function().
static void pwd_command (char * args, int from_tty) [static]
Definition at line 334 of file cli-cmds.c.
References _, current_directory, error(), gdb_dirbuf, printf_unfiltered(), and safe_strerror().
Referenced by _initialize_cli_cmds(), and cd_command().
void quit_command (char * args, int from_tty)
Definition at line 323 of file cli-cmds.c.
References _, error(), query_if_trace_running(), quit_confirm(), and quit_force().
Referenced by _initialize_cli_cmds(), captured_command_loop(), and stdin_event_handler().
static void set_debug (char * arg, int from_tty) [static]
Definition at line 1547 of file cli-cmds.c.
References _, gdb_stdout, help_list(), and printf_unfiltered().
Referenced by _initialize_cli_cmds().
static void shell_escape (char * arg, int from_tty) [static]
Definition at line 699 of file cli-cmds.c.
References _, close_most_fds(), current_directory, error(), fprintf_unfiltered(), gdb_flush(), gdb_stderr, p, safe_strerror(), and exsummary::status.
Referenced by _initialize_cli_cmds(), edit_command(), and make_command().
static void show_command (char * arg, int from_tty) [static]
Definition at line 227 of file cli-cmds.c.
References cmd_show_list().
Referenced by _initialize_cli_cmds().
static void show_configuration (char * args, int from_tty) [static]
Definition at line 315 of file cli-cmds.c.
References gdb_stdout, and print_gdb_configuration().
Referenced by _initialize_cli_cmds().
static void show_debug (char * args, int from_tty) [static]
Definition at line 1555 of file cli-cmds.c.
References cmd_show_list().
Referenced by _initialize_cli_cmds().
static void show_history_expansion_p (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 1580 of file cli-cmds.c.
References _, and fprintf_filtered().
Referenced by _initialize_cli_cmds().
static void show_info_verbose (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 1567 of file cli-cmds.c.
References _, fprintf_filtered(), and info_verbose.
Referenced by _initialize_cli_cmds().
static void show_max_user_call_depth (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 1605 of file cli-cmds.c.
References _, and fprintf_filtered().
Referenced by _initialize_cli_cmds().
static void show_remote_debug (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 1588 of file cli-cmds.c.
References _, and fprintf_filtered().
Referenced by _initialize_cli_cmds().
static void show_remote_timeout (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 1596 of file cli-cmds.c.
References _, and fprintf_filtered().
Referenced by _initialize_cli_cmds().
static void show_script_ext_mode (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 457 of file cli-cmds.c.
References _, and fprintf_filtered().
Referenced by _initialize_cli_cmds().
static void show_user (char * args, int from_tty) [static]
Definition at line 1220 of file cli-cmds.c.
References _, cmd_list_element::class, class_user, cmdlist, error(), gdb_stdout, lookup_cmd(), cmd_list_element::name, cmd_list_element::next, cmd_list_element::prefixlist, show_user_1(), and cmd_list_element::user_commands.
Referenced by _initialize_cli_cmds().
static void show_version (char * args, int from_tty) [static]
Definition at line 308 of file cli-cmds.c.
References gdb_stdout, print_gdb_version(), and printf_filtered().
Referenced by _initialize_cli_cmds().
static void source_command (char * args, int from_tty) [static]
Definition at line 614 of file cli-cmds.c.
References do_cleanups(), make_cleanup(), skip_spaces(), source_script_with_search(), source_verbose, source_verbose_cleanup(), and xmalloc().
Referenced by init_cli_cmds().
void source_script (const char * file, int from_tty)
Definition at line 599 of file cli-cmds.c.
References source_script_with_search().
Referenced by captured_main().
static void source_script_from_stream (FILE * stream, const char * file) [static]
Definition at line 523 of file cli-cmds.c.
References gdb_exception::error, gdb_exception::reason, RETURN_ERROR, RETURN_MASK_ERROR, script_ext_mode, script_ext_off, script_ext_soft, script_from_file(), source_python_script(), throw_exception(), TRY_CATCH, and UNSUPPORTED_ERROR.
Referenced by source_script_with_search().
static void source_script_with_search (const char * file, int from_tty, int search_path) [static]
Definition at line 560 of file cli-cmds.c.
References _, do_cleanups(), error(), find_and_open_script(), make_cleanup(), make_cleanup_fclose(), perror_warning_with_name(), perror_with_name(), source_script_from_stream(), and xfree().
Referenced by source_command(), and source_script().
static void source_verbose_cleanup (void * old_value) [static]
Definition at line 607 of file cli-cmds.c.
References source_verbose, and xfree().
Referenced by source_command().
static int valid_command_p (const char * command) [static]
Definition at line 1305 of file cli-cmds.c.
References lookup_cmd_1().
Referenced by alias_command().
Variable Documentation
initialize_file_ftype _initialize_cli_cmds
Definition at line 1615 of file cli-cmds.c.
Referenced by initialize_all_files().
struct cmd_list_element* cmdlist
Definition at line 105 of file cli-cmds.c.
Referenced by _initialize_cli_dump(), _initialize_macrocmd(), _initialize_mem_search(), _initialize_record(), _initialize_step_skip(), _initialize_symfile_mem(), _initialize_tasks(), _initialize_tracepoint(), add_com(), add_com_alias(), add_prefix_cmd(), add_target_with_completer(), bsd_kvm_add_target(), cmdpy_init(), encode_actions_1(), execute_command(), help_all(), help_cmd(), initialize_inferiors(), lookup_cmd_composition(), show_user(), trace_dump_actions(), tui_get_cmd_list(), validate_actionline(), and validate_comname().
struct cmd_list_element* deletelist
Definition at line 125 of file cli-cmds.c.
Referenced by _initialize_mem(), _initialize_reverse(), and _initialize_tracepoint().
struct cmd_list_element* detachlist
Definition at line 129 of file cli-cmds.c.
Referenced by initialize_inferiors().
struct cmd_list_element* disablelist
Definition at line 117 of file cli-cmds.c.
Referenced by _initialize_mem().
struct cmd_list_element* enablelist
Definition at line 113 of file cli-cmds.c.
Referenced by _initialize_mem().
struct cmd_list_element* infolist
Definition at line 109 of file cli-cmds.c.
Referenced by _initialize_avr_tdep(), _initialize_go32_nat(), _initialize_macrocmd(), _initialize_record(), _initialize_spu_tdep(), add_info(), add_info_alias(), add_task_commands(), auto_load_info_cmdlist_get(), info_probes_cmdlist_get(), and init_w32_command_list().
struct cmd_list_element* killlist
Definition at line 133 of file cli-cmds.c.
Referenced by initialize_inferiors().
struct cmd_list_element* maintenanceinfolist
Definition at line 165 of file cli-cmds.c.
Referenced by _initialize_gdb_bfd(), _initialize_psymtab(), _initialize_sol_thread(), initialize_progspace(), and maintenance_info_command().
struct cmd_list_element* maintenancelist
Definition at line 161 of file cli-cmds.c.
Referenced by _initialize_cp_support(), _initialize_psymtab(), and maintenance_command().
struct cmd_list_element* maintenanceprintlist
Definition at line 169 of file cli-cmds.c.
Referenced by _initialize_hppa_tdep(), _initialize_psymtab(), _initialize_regcache(), _initialize_reggroup(), _initialize_target_descriptions(), initialize_targets(), and maintenance_print_command().
unsigned int max_user_call_depth
Definition at line 99 of file cli-cmds.c.
Referenced by _initialize_cli_cmds(), execute_user_command(), and init_cmd_lists().
const char* const script_ext_enums[] [static]
Initial value:
 {
  script_ext_off,
  script_ext_soft,
  script_ext_strict,
  NULL
}
Definition at line 194 of file cli-cmds.c.
Referenced by _initialize_cli_cmds().
const char* script_ext_mode = script_ext_soft [static]
Definition at line 201 of file cli-cmds.c.
Referenced by _initialize_cli_cmds(), and source_script_from_stream().
const char script_ext_off[] = "off" [static]
Definition at line 190 of file cli-cmds.c.
Referenced by source_script_from_stream().
const char script_ext_soft[] = "soft" [static]
Definition at line 191 of file cli-cmds.c.
Referenced by source_script_from_stream().
const char script_ext_strict[] = "strict" [static]
Definition at line 192 of file cli-cmds.c.
struct cmd_list_element* setchecklist
Definition at line 179 of file cli-cmds.c.
Referenced by _initialize_gdbtypes(), and set_check().
struct cmd_list_element* setdebuglist
Definition at line 175 of file cli-cmds.c.
Referenced by _initialize_aarch64_tdep(), _initialize_aix_thread(), _initialize_arm_tdep(), _initialize_darwin_inferior(), _initialize_dec_thread(), _initialize_dsbt_solib(), _initialize_dwarf2loc(), _initialize_frame(), _initialize_frv_solib(), _initialize_gdbtypes(), _initialize_gnu_nat(), _initialize_hppa_tdep(), _initialize_linux_nat(), _initialize_machoread(), _initialize_mips_tdep(), _initialize_nios2_tdep(), _initialize_notif(), _initialize_observer(), _initialize_record(), _initialize_remote_monitors(), _initialize_solib_aix(), _initialize_symfile_debug(), _initialize_thread_db(), _initialize_xtensa_tdep(), initialize_targets(), and initialize_utils().
struct cmd_list_element* sethistlist
Definition at line 149 of file cli-cmds.c.
Referenced by init_main(), and set_history().
struct cmd_list_element* setlist
Definition at line 137 of file cli-cmds.c.
Referenced by _initialize_ada_language(), _initialize_agent(), _initialize_alpha_tdep(), _initialize_arm_tdep(), _initialize_charset(), _initialize_cli_logging(), _initialize_cp_abi(), _initialize_cris_tdep(), _initialize_darwin_inferior(), _initialize_demangler(), _initialize_filesystem(), _initialize_fork_child(), _initialize_frame(), _initialize_gdb_osabi(), _initialize_gdbarch_utils(), _initialize_gdbtypes(), _initialize_m32r_rom(), _initialize_mem(), _initialize_mips_tdep(), _initialize_proc_api(), _initialize_python(), _initialize_record(), _initialize_remote_mips(), _initialize_remote_monitors(), _initialize_rs6000_tdep(), _initialize_ser_dos(), _initialize_sh_tdep(), _initialize_solib(), _initialize_spu_tdep(), _initialize_target_descriptions(), _initialize_thread_db(), _initialize_tracepoint(), _initialize_tui_win(), _initialize_windows_nat(), add_language(), add_task_commands(), add_thread_commands(), auto_load_set_cmdlist_get(), do_set_command(), init_main(), initialize_current_architecture(), initialize_targets(), initialize_utils(), parmpy_init(), and set_cmd_prefix().
struct cmd_list_element* setprintlist
Definition at line 171 of file cli-cmds.c.
Referenced by _initialize_demangler(), _initialize_pascal_valprint(), initialize_inferiors(), initialize_utils(), set_print(), and set_print_type().
struct cmd_list_element* showchecklist
Definition at line 181 of file cli-cmds.c.
Referenced by _initialize_gdbtypes(), and show_check().
struct cmd_list_element* showdebuglist
Definition at line 177 of file cli-cmds.c.
Referenced by _initialize_aarch64_tdep(), _initialize_aix_thread(), _initialize_arm_tdep(), _initialize_darwin_inferior(), _initialize_dec_thread(), _initialize_dsbt_solib(), _initialize_dwarf2loc(), _initialize_frame(), _initialize_frv_solib(), _initialize_gdbtypes(), _initialize_gnu_nat(), _initialize_hppa_tdep(), _initialize_linux_nat(), _initialize_machoread(), _initialize_mips_tdep(), _initialize_nios2_tdep(), _initialize_notif(), _initialize_observer(), _initialize_record(), _initialize_remote_monitors(), _initialize_solib_aix(), _initialize_symfile_debug(), _initialize_thread_db(), _initialize_xtensa_tdep(), initialize_targets(), and initialize_utils().
struct cmd_list_element* showhistlist
Definition at line 153 of file cli-cmds.c.
Referenced by init_main(), and show_history().
struct cmd_list_element* showlist
Definition at line 145 of file cli-cmds.c.
Referenced by _initialize_ada_language(), _initialize_agent(), _initialize_alpha_tdep(), _initialize_arm_tdep(), _initialize_charset(), _initialize_cli_logging(), _initialize_cp_abi(), _initialize_cris_tdep(), _initialize_darwin_inferior(), _initialize_demangler(), _initialize_filesystem(), _initialize_fork_child(), _initialize_frame(), _initialize_gdb_osabi(), _initialize_gdbarch_utils(), _initialize_gdbtypes(), _initialize_m32r_rom(), _initialize_mem(), _initialize_mips_tdep(), _initialize_proc_api(), _initialize_python(), _initialize_record(), _initialize_remote_mips(), _initialize_remote_monitors(), _initialize_rs6000_tdep(), _initialize_ser_dos(), _initialize_sh_tdep(), _initialize_solib(), _initialize_spu_tdep(), _initialize_target_descriptions(), _initialize_thread_db(), _initialize_tracepoint(), _initialize_tui_win(), _initialize_windows_nat(), add_language(), add_task_commands(), add_thread_commands(), auto_load_show_cmdlist_get(), init_main(), initialize_current_architecture(), initialize_targets(), initialize_utils(), parmpy_init(), and set_verbose().
struct cmd_list_element* showprintlist
Definition at line 173 of file cli-cmds.c.
Referenced by _initialize_demangler(), _initialize_pascal_valprint(), initialize_inferiors(), initialize_utils(), and show_print().
int source_verbose = 0
Definition at line 185 of file cli-cmds.c.
Referenced by print_command_trace(), source_command(), and source_verbose_cleanup().
struct cmd_list_element* stoplist
Definition at line 121 of file cli-cmds.c.
int trace_commands = 0
Definition at line 186 of file cli-cmds.c.
Referenced by _initialize_cli_cmds(), and print_command_trace().
struct cmd_list_element* unsethistlist
Definition at line 157 of file cli-cmds.c.
struct cmd_list_element* unsetlist
Definition at line 141 of file cli-cmds.c.
Referenced by _initialize_fork_child(), _initialize_target_descriptions(), and unset_command().