GDB (xrefs): /home/stan/gdb/src/gdb/cli-out.c File Reference
/home/stan/gdb/src/gdb/cli-out.c File Reference
#include "defs.h"
#include "ui-out.h"
#include "cli-out.h"
#include "gdb_string.h"
#include "gdb_assert.h"
#include "vec.h"
Typedefs
typedef struct cli_ui_out_data cli_out_data
Functions
static void cli_text (struct ui_out *uiout, const char *string)
static void field_separator (void)
static void out_field_fmt (struct ui_out *uiout, int fldno, const char *fldname, const char *format,...) ATTRIBUTE_PRINTF(4
static void static void cli_table_begin (struct ui_out *uiout, int nbrofcols, int nr_rows, const char *tblid)
static void cli_table_body (struct ui_out *uiout)
static void cli_table_end (struct ui_out *uiout)
static void cli_table_header (struct ui_out *uiout, int width, enum ui_align alignment, const char *col_name, const char *colhdr)
static void cli_begin (struct ui_out *uiout, enum ui_out_type type, int level, const char *id)
static void cli_end (struct ui_out *uiout, enum ui_out_type type, int level)
static void cli_field_int (struct ui_out *uiout, int fldno, int width, enum ui_align alignment, const char *fldname, int value)
static void cli_field_skip (struct ui_out *uiout, int fldno, int width, enum ui_align alignment, const char *fldname)
static void cli_field_string (struct ui_out *uiout, int fldno, int width, enum ui_align align, const char *fldname, const char *string)
static void ATTRIBUTE_PRINTF (6, 0)
static void cli_spaces (struct ui_out *uiout, int numspaces)
static void ATTRIBUTE_PRINTF (3, 0)
static void cli_wrap_hint (struct ui_out *uiout, char *identstring)
static void cli_flush (struct ui_out *uiout)
static int cli_redirect (struct ui_out *uiout, struct ui_file *outstream)
void cli_out_data_ctor (cli_out_data *self, struct ui_file *stream)
struct ui_out * cli_out_new (struct ui_file *stream)
struct ui_file * cli_out_set_stream (struct ui_out *uiout, struct ui_file *stream)
Variables
struct ui_out_impl cli_ui_out_impl
Typedef Documentation
typedef struct cli_ui_out_data cli_out_data
Definition at line 30 of file cli-out.c.
Function Documentation
static void ATTRIBUTE_PRINTF (6 , 0) [static]
Definition at line 219 of file cli-out.c.
References field_separator(), cli_ui_out_data::suppress_output, ui_noalign, ui_out_data(), VEC_last, and vfprintf_filtered().
static void ATTRIBUTE_PRINTF (3 , 0) [static]
Definition at line 265 of file cli-out.c.
References cli_ui_out_data::suppress_output, ui_out_data(), ui_out_get_verblvl(), VEC_last, and vfprintf_unfiltered().
static void cli_begin (struct ui_out * uiout, enum ui_out_type type, int level, const char * id) [static]
Definition at line 105 of file cli-out.c.
References cli_ui_out_data::suppress_output, and ui_out_data().
static void cli_end (struct ui_out * uiout, enum ui_out_type type, int level) [static]
Definition at line 119 of file cli-out.c.
References cli_ui_out_data::suppress_output, and ui_out_data().
static void cli_field_int (struct ui_out * uiout, int fldno, int width, enum ui_align alignment, const char * fldname, int value) [static]
Definition at line 132 of file cli-out.c.
References cli_ui_out_data::suppress_output, ui_out_data(), uo_field_string(), and xsnprintf().
static void cli_field_skip (struct ui_out * uiout, int fldno, int width, enum ui_align alignment, const char * fldname) [static]
Definition at line 151 of file cli-out.c.
References cli_ui_out_data::suppress_output, ui_out_data(), and uo_field_string().
static void cli_field_string (struct ui_out * uiout, int fldno, int width, enum ui_align align, const char * fldname, const char * string) [static]
Definition at line 169 of file cli-out.c.
References field_separator(), out_field_fmt(), cli_ui_out_data::suppress_output, ui_left, ui_noalign, ui_out_data(), ui_out_spaces(), and ui_right.
static void cli_flush (struct ui_out * uiout) [static]
Definition at line 293 of file cli-out.c.
References gdb_flush(), ui_out_data(), and VEC_last.
void cli_out_data_ctor (cli_out_data * self, struct ui_file * stream)
Definition at line 380 of file cli-out.c.
References gdb_assert, and VEC_safe_push.
Referenced by cli_out_new(), and tui_out_new().
struct ui_out* cli_out_new (struct ui_file * stream) [read]
Definition at line 393 of file cli-out.c.
References cli_out_data_ctor(), ui_out::data, flags, ui_out_new(), ui_source_list, and XMALLOC.
Referenced by _initialize_cli_interp(), gdbtk_interpreter_init(), and tui_initialize_io().
struct ui_file* cli_out_set_stream (struct ui_out * uiout, struct ui_file * stream) [read]
Definition at line 403 of file cli-out.c.
References ui_out_data(), VEC_pop, and VEC_quick_push.
Referenced by cli_interpreter_exec(), cli_interpreter_resume(), and tui_resume().
static int cli_redirect (struct ui_out * uiout, struct ui_file * outstream) [static]
Definition at line 306 of file cli-out.c.
References ui_out_data(), VEC_pop, and VEC_safe_push.
static void cli_spaces (struct ui_out * uiout, int numspaces) [static]
Definition at line 240 of file cli-out.c.
References print_spaces_filtered(), cli_ui_out_data::suppress_output, ui_out_data(), and VEC_last.
static void static void cli_table_begin (struct ui_out * uiout, int nbrofcols, int nr_rows, const char * tblid) [static]
Definition at line 48 of file cli-out.c.
References gdb_assert, cli_ui_out_data::suppress_output, and ui_out_data().
static void cli_table_body (struct ui_out * uiout) [static]
Definition at line 65 of file cli-out.c.
References cli_text(), cli_ui_out_data::suppress_output, and ui_out_data().
static void cli_table_end (struct ui_out * uiout) [static]
Definition at line 78 of file cli-out.c.
References cli_ui_out_data::suppress_output, and ui_out_data().
static void cli_table_header (struct ui_out * uiout, int width, enum ui_align alignment, const char * col_name, const char * colhdr) [static]
Definition at line 88 of file cli-out.c.
References cli_ui_out_data::suppress_output, ui_out_data(), and uo_field_string().
static void cli_text (struct ui_out * uiout, const char * string) [static]
Definition at line 253 of file cli-out.c.
References fputs_filtered(), cli_ui_out_data::suppress_output, ui_out_data(), and VEC_last.
Referenced by cli_table_body().
static void cli_wrap_hint (struct ui_out * uiout, char * identstring) [static]
Definition at line 283 of file cli-out.c.
References cli_ui_out_data::suppress_output, ui_out_data(), and wrap_here().
static void field_separator (void) [static]
Definition at line 342 of file cli-out.c.
References current_uiout, fputc_filtered(), ui_out_data(), and VEC_last.
Referenced by ATTRIBUTE_PRINTF(), and cli_field_string().
static void out_field_fmt (struct ui_out * uiout, int fldno, const char * fldname, const char * format, ...) [static]
Definition at line 325 of file cli-out.c.
References ui_out_data(), VEC_last, and vfprintf_filtered().
Referenced by cli_field_string().
Variable Documentation
struct ui_out_impl cli_ui_out_impl
Initial value:
{
  cli_table_begin,
  cli_table_body,
  cli_table_end,
  cli_table_header,
  cli_begin,
  cli_end,
  cli_field_int,
  cli_field_skip,
  cli_field_string,
  cli_field_fmt,
  cli_spaces,
  cli_text,
  cli_message,
  cli_wrap_hint,
  cli_flush,
  cli_redirect,
  0,
  0,
}
Definition at line 355 of file cli-out.c.
Referenced by tui_field_fmt(), tui_field_int(), tui_field_string(), and tui_text().