GDB (xrefs): /home/stan/gdb/src/gdb/coff-pe-read.h File Reference
/home/stan/gdb/src/gdb/coff-pe-read.h File Reference
Functions
void read_pe_exported_syms (struct objfile *objfile)
CORE_ADDR pe_text_section_offset (struct bfd *abfd)
Function Documentation
CORE_ADDR pe_text_section_offset (struct bfd * abfd)
Definition at line 627 of file coff-pe-read.c.
References DEFAULT_COFF_PE_TEXT_SECTION_OFFSET, pe_get16(), and pe_get32().
Referenced by windows_xfer_shared_library().
void read_pe_exported_syms (struct objfile * objfile)
Definition at line 320 of file coff-pe-read.c.
References _, add_pe_exported_sym(), add_pe_forwarded_sym(), ANOFFSET, debug_coff_pe_read, do_cleanups(), fprintf_unfiltered(), free_current_contents(), gdb_stdlog, get_section_vmas(), IMAGE_SCN_CNT_CODE, IMAGE_SCN_CNT_INITIALIZED_DATA, IMAGE_SCN_CNT_UNINITIALIZED_DATA, int, len, make_cleanup(), mst_bss, mst_data, mst_text, mst_unknown, name, pe_sections_info::nb_sections, null_cleanup(), objfile::obfd, pe_as16(), pe_as32(), pe_get16(), pe_get32(), PE_SECTION_INDEX_BSS, PE_SECTION_INDEX_DATA, PE_SECTION_INDEX_INVALID, PE_SECTION_INDEX_TEXT, PE_SECTION_TABLE_SIZE, read_pe_section_index(), read_pe_truncate_name(), SECT_OFF_TEXT, objfile::section_offsets, pe_sections_info::sections, strrchr(), xfree(), xmalloc(), xrealloc(), and xzalloc().
Referenced by coff_symtab_read().