GDB (xrefs): /home/stan/gdb/src/gdb/coffread.c File Reference
/home/stan/gdb/src/gdb/coffread.c File Reference
#include "defs.h"
#include "symtab.h"
#include "gdbtypes.h"
#include "demangle.h"
#include "breakpoint.h"
#include "bfd.h"
#include "gdb_obstack.h"
#include "gdb_string.h"
#include <ctype.h>
#include "coff/internal.h"
#include "libcoff.h"
#include "objfiles.h"
#include "buildsym.h"
#include "gdb-stabs.h"
#include "stabsread.h"
#include "complaints.h"
#include "target.h"
#include "gdb_assert.h"
#include "block.h"
#include "dictionary.h"
#include "coff-pe-read.h"
#include "psymtab.h"
Classes
struct coff_symfile_info
struct coff_symbol
struct find_targ_sec_arg
Defines
#define EXTERNAL_NAME(string, abfd)
#define SDB_TYPE(type) (BTYPE(type) | (type & N_TMASK))
#define N_BTMASK local_n_btmask
#define N_BTSHFT local_n_btshft
#define N_TMASK local_n_tmask
#define N_TSHIFT local_n_tshift
#define INITIAL_TYPE_VECTOR_LENGTH 160
#define L_LNNO32(lp) ((lp)->l_lnno)
Functions
void _initialize_coffread (void)
void stabsread_clear_cache (void)
static struct type * coff_read_struct_type (int, int, int, struct objfile *)
static struct type * decode_base_type (struct coff_symbol *, unsigned int, union internal_auxent *, struct objfile *)
static struct type * decode_type (struct coff_symbol *, unsigned int, union internal_auxent *, struct objfile *)
static struct type * decode_function_type (struct coff_symbol *, unsigned int, union internal_auxent *, struct objfile *)
static struct type * coff_read_enum_type (int, int, int, struct objfile *)
static struct symbol * process_coff_symbol (struct coff_symbol *, union internal_auxent *, struct objfile *)
static void patch_opaque_types (struct symtab *)
static void enter_linenos (long, int, int, struct objfile *)
static void free_linetab (void)
static void free_linetab_cleanup (void *ignore)
static int init_lineno (bfd *, long, int)
static char * getsymname (struct internal_syment *)
static const char * coff_getfilename (union internal_auxent *)
static void free_stringtab (void)
static void free_stringtab_cleanup (void *ignore)
static int init_stringtab (bfd *, long)
static void read_one_sym (struct coff_symbol *, struct internal_syment *, union internal_auxent *)
static void coff_symtab_read (long, unsigned int, struct objfile *)
static void coff_locate_sections (bfd *abfd, asection *sectp, void *csip)
static int cs_to_section (struct coff_symbol *, struct objfile *)
static void find_targ_sec (bfd *abfd, asection *sect, void *obj)
static struct bfd_section * cs_to_bfd_section (struct coff_symbol *cs, struct objfile *objfile)
static CORE_ADDR cs_section_address (struct coff_symbol *, bfd *)
static struct type ** coff_lookup_type (int index)
static struct type * coff_alloc_type (int index)
static void coff_start_symtab (const char *name)
static void complete_symtab (const char *name, CORE_ADDR start_addr, unsigned int size)
static void coff_end_symtab (struct objfile *objfile)
static int is_import_fixup_symbol (struct coff_symbol *cs, enum minimal_symbol_type type)
static struct minimal_symbol * record_minimal_symbol (struct coff_symbol *cs, CORE_ADDR address, enum minimal_symbol_type type, int section, struct objfile *objfile)
static void coff_symfile_init (struct objfile *objfile)
static void find_linenos (bfd *abfd, struct bfd_section *asect, void *vpinfo)
static void coff_symfile_read (struct objfile *objfile, int symfile_flags)
static void coff_new_init (struct objfile *ignore)
static void coff_symfile_finish (struct objfile *objfile)
static void patch_type (struct type *type, struct type *real_type)
static int coff_reg_to_regnum (struct symbol *sym, struct gdbarch *gdbarch)
static void coff_free_info (struct objfile *objfile, void *arg)
Variables
static struct objfile_data * coff_objfile_data_key
static struct objfile * coffread_objfile
static CORE_ADDR current_source_start_addr
static CORE_ADDR current_source_end_addr
static bfd * nlist_bfd_global
static int nlist_nsyms_global
static char * temp_sym
static char * temp_aux
static unsigned local_n_btmask
static unsigned local_n_btshft
static unsigned local_n_tmask
static unsigned local_n_tshift
static unsigned local_linesz
static unsigned local_symesz
static unsigned local_auxesz
static int pe_file
static struct symbol * opaque_type_chain [HASHSIZE]
static struct type ** type_vector
static int type_vector_length
static bfd * symfile_bfd
static char * stringtab = NULL
static char * linetab = NULL
static long linetab_offset
static unsigned long linetab_size
static struct symbol_register_ops coff_register_funcs
static int coff_register_index
static struct sym_fns coff_sym_fns
Define Documentation
#define EXTERNAL_NAME (string, abfd)
Value:
(string[0] == bfd_get_symbol_leading_char (abfd) \
        ? string + 1 : string)
Definition at line 71 of file coffread.c.
Referenced by coff_read_enum_type(), coff_read_struct_type(), and process_coff_symbol().
#define INITIAL_TYPE_VECTOR_LENGTH 160
Definition at line 160 of file coffread.c.
Referenced by coff_symtab_read().
#define L_LNNO32 (lp) ((lp)->l_lnno)
Definition at line 1460 of file coffread.c.
Referenced by enter_linenos().
#define N_BTMASK local_n_btmask
Definition at line 112 of file coffread.c.
Referenced by decode_type().
#define N_BTSHFT local_n_btshft
Definition at line 113 of file coffread.c.
#define N_TMASK local_n_tmask
Definition at line 114 of file coffread.c.
#define N_TSHIFT local_n_tshift
Definition at line 115 of file coffread.c.
#define SDB_TYPE (type) (BTYPE(type) | (type & N_TMASK))
Definition at line 80 of file coffread.c.
Referenced by coff_symtab_read(), and read_one_sym().
Function Documentation
void _initialize_coffread (void)
static struct type* coff_alloc_type (int index) [static, read]
Definition at line 367 of file coffread.c.
References alloc_type(), coff_lookup_type(), and type.
Referenced by coff_read_enum_type(), coff_read_struct_type(), decode_base_type(), and decode_type().
static void coff_end_symtab (struct objfile * objfile) [static]
Definition at line 423 of file coffread.c.
References current_source_end_addr, current_source_start_addr, end_symtab(), last_source_start_addr, SECT_OFF_TEXT, and set_last_source_file().
Referenced by coff_symtab_read().
static void coff_free_info (struct objfile * objfile, void * arg) [static]
Definition at line 2277 of file coffread.c.
References xfree().
static const char * coff_getfilename (union internal_auxent * aux_entry) [static]
Definition at line 1381 of file coffread.c.
References _, internal_error(), and stringtab.
Referenced by coff_symtab_read().
static void coff_locate_sections (bfd * abfd, asection * sectp, void * csip) [static]
Definition at line 225 of file coffread.c.
References make_cleanup(), name, stab_section_list::next, stab_section_list::section, coff_symfile_info::stabsects, coff_symfile_info::stabstrsect, coff_symfile_info::textaddr, coff_symfile_info::textsize, xfree(), and xmalloc().
Referenced by coff_symfile_read().
static struct type** coff_lookup_type (int index) [static, read]
Definition at line 343 of file coffread.c.
References memset(), type_vector, type_vector_length, and xrealloc().
Referenced by coff_alloc_type().
static void coff_new_init (struct objfile * ignore) [static]
Definition at line 749 of file coffread.c.
static struct type * coff_read_enum_type (int index, int length, int lastsym, struct objfile * objfile) [static, read]
Definition at line 2146 of file coffread.c.
References add_symbol_to_list(), allocate_symbol(), coff_symbol::c_name, coff_symbol::c_sclass, coff_symbol::c_value, coff_alloc_type(), EXTERNAL_NAME, file_symbols, gdbarch_int_bit(), get_objfile_arch(), LOC_CONST, local_symbols, name, pending::next, nlist_nsyms_global, pending::nsyms, objfile::obfd, objfile::objfile_obstack, read_one_sym(), SET_FIELD_ENUMVAL, pending::symbol, SYMBOL_ACLASS_INDEX, SYMBOL_DOMAIN, SYMBOL_LINKAGE_NAME, SYMBOL_SET_LINKAGE_NAME, SYMBOL_TYPE, SYMBOL_VALUE, symnum, type, TYPE_ALLOC, TYPE_CODE, TYPE_CODE_ENUM, TYPE_FIELD, TYPE_FIELD_BITSIZE, TYPE_FIELD_NAME, TYPE_FIELDS, TYPE_LENGTH, TYPE_NFIELDS, TYPE_UNSIGNED, VAR_DOMAIN, and within_function.
Referenced by decode_base_type().
static struct type * coff_read_struct_type (int index, int length, int lastsym, struct objfile * objfile) [static, read]
Definition at line 2053 of file coffread.c.
References coff_symbol::c_name, coff_symbol::c_sclass, coff_symbol::c_type, coff_symbol::c_value, coff_alloc_type(), decode_type(), EXTERNAL_NAME, FIELD_BITSIZE, FIELD_TYPE, INIT_CPLUS_SPECIFIC, name, nlist_nsyms_global, objfile::obfd, objfile::objfile_obstack, read_one_sym(), SET_FIELD_BITPOS, symnum, type, TYPE_ALLOC, TYPE_CODE, TYPE_CODE_STRUCT, TYPE_FIELD, TYPE_FIELDS, TYPE_LENGTH, and TYPE_NFIELDS.
Referenced by decode_base_type().
static int coff_reg_to_regnum (struct symbol * sym, struct gdbarch * gdbarch) [static]
Definition at line 1605 of file coffread.c.
References gdbarch_sdb_reg_to_regnum(), and SYMBOL_VALUE.
static void coff_start_symtab (const char * name) [static]
Definition at line 388 of file coffread.c.
References record_debugformat(), and start_symtab().
Referenced by coff_symtab_read().
static void coff_symfile_finish (struct objfile * objfile) [static]
Definition at line 760 of file coffread.c.
References dwarf2_free_objfile(), and stabsread_clear_cache().
static void coff_symfile_init (struct objfile * objfile) [static]
Definition at line 505 of file coffread.c.
References coff_objfile_data_key, dbx_objfile_data_key, objfile::flags, and OBJF_REORDERED.
static void coff_symfile_read (struct objfile * objfile, int symfile_flags) [static]
Definition at line 565 of file coffread.c.
References _, ALL_OBJFILE_MSYMBOLS, coff_locate_sections(), coff_objfile_data_key, coff_symtab_read(), coffstab_build_psymtabs(), DBX_SYMFILE_INFO, do_cleanups(), dwarf2_build_frame_info(), dwarf2_build_psymtabs(), dwarf2_has_info(), error(), find_linenos(), find_separate_debug_file_by_debuglink(), free_current_contents(), free_linetab_cleanup(), free_stringtab_cleanup(), init_lineno(), init_minimal_symbol_collection(), init_stringtab(), install_minimal_symbols(), local_auxesz, local_linesz, local_n_btmask, local_n_btshft, local_n_tmask, local_n_tshift, local_symesz, lookup_minimal_symbol(), make_cleanup(), make_cleanup_bfd_unref(), make_cleanup_discard_minimal_symbols(), coff_symfile_info::max_lineno_offset, coff_symfile_info::min_lineno_offset, mst_data, mst_solib_trampoline, mst_text, MSYMBOL_TYPE, name, objfile::obfd, objfile_has_partial_symbols(), pe_file, symbol_file_add_separate(), SYMBOL_LINKAGE_NAME, symfile_bfd, symfile_bfd_open(), dbx_symfile_info::symtab_offset, temp_aux, temp_sym, xfree(), and xmalloc().
static void coff_symtab_read (long symtab_offset, unsigned int nsyms, struct objfile * objfile) [static]
Definition at line 775 of file coffread.c.
References _, ALL_OBJFILE_SYMTABS, ANOFFSET, coff_symbol::c_name, coff_symbol::c_naux, coff_symbol::c_sclass, coff_symbol::c_secnum, coff_symbol::c_symnum, coff_symbol::c_type, coff_symbol::c_value, coff_end_symtab(), coff_getfilename(), coff_start_symtab(), complaint(), complete_symtab(), context_stack_depth, cs_to_bfd_section(), cs_to_section(), current_subfile, enter_linenos(), error(), finish_block(), gdbarch_addr_bits_remove(), gdbarch_coff_make_msymbol_special(), get_last_source_file(), get_objfile_arch(), getsymname(), INITIAL_TYPE_VECTOR_LENGTH, subfile::language, language_minimal, local_symbols, memset(), mst_abs, mst_bss, mst_data, mst_file_bss, mst_file_data, mst_file_text, mst_text, mst_unknown, nlist_bfd_global, nlist_nsyms_global, objfile::obfd, objfile_name(), patch_opaque_types(), pe_file, perror_with_name(), pop_context(), process_coff_symbol(), push_context(), QUIT, read_one_sym(), read_pe_exported_syms(), record_line(), record_minimal_symbol(), SDB_TYPE, SECT_OFF_TEXT, objfile::section_offsets, set_last_source_file(), SYMBOL_SECTION, SYMBOL_VALUE, symfile_complaints, symnum, type_vector_length, within_function, xfree(), and xmalloc().
Referenced by coff_symfile_read().
static void complete_symtab (const char * name, CORE_ADDR start_addr, unsigned int size) [static]
Definition at line 410 of file coffread.c.
References current_source_end_addr, current_source_start_addr, set_last_source_file(), and size.
Referenced by coff_symtab_read().
static CORE_ADDR cs_section_address (struct coff_symbol * cs, bfd * abfd) [static]
Definition at line 321 of file coffread.c.
References coff_symbol::c_secnum, find_targ_sec(), find_targ_sec_arg::resultp, and find_targ_sec_arg::targ_index.
Referenced by read_one_sym().
static struct bfd_section* cs_to_bfd_section (struct coff_symbol * cs, struct objfile * objfile) [static, read]
Definition at line 294 of file coffread.c.
References coff_symbol::c_secnum, find_targ_sec(), objfile::obfd, find_targ_sec_arg::resultp, and find_targ_sec_arg::targ_index.
Referenced by coff_symtab_read(), and cs_to_section().
static int cs_to_section (struct coff_symbol * cs, struct objfile * objfile) [static]
Definition at line 307 of file coffread.c.
References cs_to_bfd_section(), gdb_bfd_section_index(), objfile::obfd, and SECT_OFF_TEXT.
Referenced by coff_symtab_read(), and process_coff_symbol().
static struct type * decode_base_type (struct coff_symbol * cs, unsigned int c_type, union internal_auxent * aux, struct objfile * objfile) [static, read]
Definition at line 1901 of file coffread.c.
References _, objfile_type::builtin_char, objfile_type::builtin_double, objfile_type::builtin_float, objfile_type::builtin_int, objfile_type::builtin_long, objfile_type::builtin_long_double, objfile_type::builtin_long_long, objfile_type::builtin_short, objfile_type::builtin_unsigned_char, objfile_type::builtin_unsigned_int, objfile_type::builtin_unsigned_long, objfile_type::builtin_unsigned_long_long, objfile_type::builtin_unsigned_short, objfile_type::builtin_void, coff_symbol::c_name, coff_symbol::c_naux, coff_symbol::c_sclass, coff_symbol::c_symnum, coff_alloc_type(), coff_read_enum_type(), coff_read_struct_type(), complaint(), gdbarch_long_bit(), get_objfile_arch(), INIT_CPLUS_SPECIFIC, objfile_type(), symfile_complaints, type, TYPE_CODE, TYPE_CODE_ENUM, TYPE_CODE_STRUCT, TYPE_CODE_UNION, TYPE_FIELDS, TYPE_LENGTH, TYPE_NAME, TYPE_NFIELDS, and TYPE_TAG_NAME.
Referenced by decode_type().
static struct type * decode_function_type (struct coff_symbol * cs, unsigned int c_type, union internal_auxent * aux, struct objfile * objfile) [static, read]
Definition at line 1886 of file coffread.c.
References coff_symbol::c_naux, and decode_type().
Referenced by process_coff_symbol().
static struct type * decode_type (struct coff_symbol * cs, unsigned int c_type, union internal_auxent * aux, struct objfile * objfile) [static, read]
Definition at line 1804 of file coffread.c.
References _, objfile_type::builtin_int, coff_symbol::c_name, coff_symbol::c_naux, coff_symbol::c_sclass, coff_alloc_type(), complaint(), create_array_type(), create_range_type(), decode_base_type(), lookup_function_type(), lookup_pointer_type(), N_BTMASK, objfile_type(), symfile_complaints, and type.
Referenced by coff_read_struct_type(), decode_function_type(), and process_coff_symbol().
static void enter_linenos (long file_offset, int first_line, int last_line, struct objfile * objfile) [static]
Definition at line 1464 of file coffread.c.
References _, ANOFFSET, complaint(), current_subfile, gdbarch_addr_bits_remove(), get_objfile_arch(), L_LNNO32, linetab, linetab_offset, linetab_size, local_linesz, record_line(), SECT_OFF_TEXT, objfile::section_offsets, symfile_bfd, and symfile_complaints.
Referenced by coff_symtab_read().
static void find_linenos (bfd * abfd, struct bfd_section * asect, void * vpinfo) [static]
Definition at line 529 of file coffread.c.
References local_linesz, coff_symfile_info::max_lineno_offset, coff_symfile_info::min_lineno_offset, offset, and size.
Referenced by coff_symfile_read().
static void find_targ_sec (bfd * abfd, asection * sect, void * obj) [static]
Definition at line 284 of file coffread.c.
References find_targ_sec_arg::resultp, and find_targ_sec_arg::targ_index.
Referenced by cs_section_address(), and cs_to_bfd_section().
static void free_linetab (void) [static]
Definition at line 1446 of file coffread.c.
References linetab, and xfree().
Referenced by free_linetab_cleanup(), and init_lineno().
static void free_linetab_cleanup (void * ignore) [static]
Definition at line 1454 of file coffread.c.
References free_linetab().
Referenced by coff_symfile_read().
static void free_stringtab (void) [static]
Definition at line 1342 of file coffread.c.
References stringtab, and xfree().
Referenced by free_stringtab_cleanup(), and init_stringtab().
static void free_stringtab_cleanup (void * ignore) [static]
Definition at line 1350 of file coffread.c.
References free_stringtab().
Referenced by coff_symfile_read().
static char * getsymname (struct internal_syment * symbol_entry) [static]
Definition at line 1356 of file coffread.c.
References stringtab.
Referenced by coff_symtab_read(), and read_one_sym().
static int init_lineno (bfd * abfd, long offset, int size) [static]
Definition at line 1417 of file coffread.c.
References free_linetab(), linetab, linetab_offset, linetab_size, local_linesz, memset(), offset, size, and xmalloc().
Referenced by coff_symfile_read().
static int init_stringtab (bfd * abfd, long offset) [static]
Definition at line 1302 of file coffread.c.
References free_stringtab(), memcpy(), stringtab, symfile_bfd, and xmalloc().
Referenced by coff_symfile_read().
static int is_import_fixup_symbol (struct coff_symbol * cs, enum minimal_symbol_type type) [static]
Definition at line 439 of file coffread.c.
References coff_symbol::c_name, coff_symbol::c_type, and mst_text.
Referenced by record_minimal_symbol().
static void patch_opaque_types (struct symtab * s) [static]
Definition at line 1545 of file coffread.c.
References ALL_BLOCK_SYMBOLS, BLOCKVECTOR, BLOCKVECTOR_BLOCK, hash(), hashname(), LOC_TYPEDEF, name, patch_type(), STATIC_BLOCK, SYMBOL_CLASS, SYMBOL_DOMAIN, SYMBOL_LINKAGE_NAME, SYMBOL_TYPE, SYMBOL_VALUE_CHAIN, TYPE_CODE, TYPE_CODE_PTR, TYPE_LENGTH, TYPE_TARGET_TYPE, and VAR_DOMAIN.
Referenced by coff_symtab_read().
static void patch_type (struct type * type, struct type * real_type) [static]
Definition at line 1515 of file coffread.c.
References memcpy(), TYPE_ALLOC, TYPE_FIELDS, TYPE_LENGTH, TYPE_NAME, TYPE_NFIELDS, TYPE_TARGET_TYPE, and xfree().
Referenced by patch_opaque_types().
static struct symbol * process_coff_symbol (struct coff_symbol * cs, union internal_auxent * aux, struct objfile * objfile) [static, read]
Definition at line 1619 of file coffread.c.
References add_symbol_to_list(), allocate_symbol(), ANOFFSET, coff_symbol::c_name, coff_symbol::c_sclass, coff_symbol::c_type, coff_symbol::c_value, coff_register_index, cs_to_section(), current_subfile, decode_function_type(), decode_type(), EXTERNAL_NAME, file_symbols, global_symbols, hashname(), subfile::language, LOC_ARG, LOC_BLOCK, LOC_LOCAL, LOC_STATIC, LOC_TYPEDEF, local_symbols, lookup_function_type(), name, objfile::obfd, objfile::objfile_obstack, SECT_OFF_TEXT, objfile::section_offsets, STRUCT_DOMAIN, SYMBOL_ACLASS_INDEX, SYMBOL_DOMAIN, SYMBOL_IS_ARGUMENT, SYMBOL_LINKAGE_NAME, SYMBOL_SECTION, SYMBOL_SET_LANGUAGE, SYMBOL_SET_NAMES, SYMBOL_TYPE, SYMBOL_VALUE, SYMBOL_VALUE_ADDRESS, SYMBOL_VALUE_CHAIN, TYPE_CODE, TYPE_CODE_FUNC, TYPE_CODE_PTR, TYPE_CODE_UNDEF, TYPE_LENGTH, TYPE_NAME, TYPE_TAG_NAME, TYPE_TARGET_TYPE, VAR_DOMAIN, and within_function.
Referenced by coff_symtab_read().
static void read_one_sym (struct coff_symbol * cs, struct internal_syment * sym, union internal_auxent * aux) [static]
Definition at line 1222 of file coffread.c.
References _, coff_symbol::c_name, coff_symbol::c_naux, coff_symbol::c_sclass, coff_symbol::c_secnum, coff_symbol::c_symnum, coff_symbol::c_type, coff_symbol::c_value, cs_section_address(), error(), getsymname(), local_auxesz, local_symesz, nlist_bfd_global, objfile_name(), pe_file, SDB_TYPE, symfile_bfd, symnum, temp_aux, and temp_sym.
Referenced by coff_read_enum_type(), coff_read_struct_type(), and coff_symtab_read().
static struct minimal_symbol* record_minimal_symbol (struct coff_symbol * cs, CORE_ADDR address, enum minimal_symbol_type type, int section, struct objfile * objfile) [static, read]
Definition at line 468 of file coffread.c.
References coff_symbol::c_name, is_import_fixup_symbol(), and prim_record_minimal_symbol_and_info().
Referenced by coff_symtab_read().
void stabsread_clear_cache (void)
Definition at line 503 of file stabsread.c.
References ref_chunk, and ref_count.
Referenced by coff_symfile_finish().
Variable Documentation
struct objfile_data* coff_objfile_data_key [static]
Definition at line 52 of file coffread.c.
Referenced by coff_symfile_init(), and coff_symfile_read().
struct symbol_register_ops coff_register_funcs [static]
Initial value:
 {
  coff_reg_to_regnum
}
Definition at line 1610 of file coffread.c.
int coff_register_index [static]
Definition at line 1616 of file coffread.c.
Referenced by process_coff_symbol().
struct sym_fns coff_sym_fns [static]
Initial value:
{
  coff_new_init,
  coff_symfile_init,
  coff_symfile_read,
  NULL,
  coff_symfile_finish,
  default_symfile_offsets,
  default_symfile_segments,
  NULL,
  default_symfile_relocate,
  NULL,
  &psym_functions
}
Definition at line 2251 of file coffread.c.
struct objfile* coffread_objfile [static]
Definition at line 56 of file coffread.c.
CORE_ADDR current_source_end_addr [static]
Definition at line 86 of file coffread.c.
Referenced by coff_end_symtab(), and complete_symtab().
CORE_ADDR current_source_start_addr [static]
Definition at line 85 of file coffread.c.
Referenced by coff_end_symtab(), and complete_symtab().
char* linetab = NULL [static]
Definition at line 1408 of file coffread.c.
Referenced by enter_linenos(), free_linetab(), and init_lineno().
long linetab_offset [static]
Definition at line 1409 of file coffread.c.
Referenced by enter_linenos(), and init_lineno().
unsigned long linetab_size [static]
Definition at line 1410 of file coffread.c.
Referenced by enter_linenos(), and init_lineno().
unsigned local_auxesz [static]
Definition at line 124 of file coffread.c.
Referenced by coff_symfile_read(), and read_one_sym().
unsigned local_linesz [static]
Definition at line 122 of file coffread.c.
Referenced by coff_symfile_read(), enter_linenos(), find_linenos(), and init_lineno().
unsigned local_n_btmask [static]
Definition at line 107 of file coffread.c.
Referenced by coff_symfile_read().
unsigned local_n_btshft [static]
Definition at line 108 of file coffread.c.
Referenced by coff_symfile_read().
unsigned local_n_tmask [static]
Definition at line 109 of file coffread.c.
Referenced by coff_symfile_read().
unsigned local_n_tshift [static]
Definition at line 110 of file coffread.c.
Referenced by coff_symfile_read().
unsigned local_symesz [static]
Definition at line 123 of file coffread.c.
Referenced by coff_symfile_read(), and read_one_sym().
bfd* nlist_bfd_global [static]
Definition at line 91 of file coffread.c.
Referenced by coff_symtab_read(), and read_one_sym().
int nlist_nsyms_global [static]
Definition at line 92 of file coffread.c.
Referenced by coff_read_enum_type(), coff_read_struct_type(), and coff_symtab_read().
struct symbol* opaque_type_chain[HASHSIZE] [static]
Definition at line 133 of file coffread.c.
int pe_file [static]
Definition at line 128 of file coffread.c.
Referenced by coff_symfile_read(), coff_symtab_read(), and read_one_sym().
char* stringtab = NULL [static]
Definition at line 1299 of file coffread.c.
Referenced by coff_getfilename(), free_stringtab(), getsymname(), init_stringtab(), and som_symtab_read().
bfd* symfile_bfd [static]
Definition at line 560 of file coffread.c.
Referenced by coff_symfile_read(), enter_linenos(), init_stringtab(), and read_one_sym().
char* temp_aux [static]
Definition at line 99 of file coffread.c.
Referenced by coff_symfile_read(), and read_one_sym().
char* temp_sym [static]
Definition at line 98 of file coffread.c.
Referenced by coff_symfile_read(), and read_one_sym().
struct type** type_vector [static]
Definition at line 151 of file coffread.c.
Referenced by coff_lookup_type().
int type_vector_length [static]
Definition at line 155 of file coffread.c.
Referenced by coff_lookup_type(), and coff_symtab_read().