GDB (xrefs): /home/stan/gdb/src/gdb/command.h File Reference
/home/stan/gdb/src/gdb/command.h File Reference
#include "gdb_vecs.h"
Defines
#define CMD_LIST_AMBIGUOUS ((struct cmd_list_element *) -1)
Typedefs
typedef enum cmd_types cmd_types
typedef enum var_types var_types
typedef void cmd_cfunc_ftype (char *args, int from_tty)
typedef void cmd_sfunc_ftype (char *args, int from_tty, struct cmd_list_element *c)
typedef const char const char *void set_cmd_completer (struct cmd_list_element *, completer_ftype *)
typedef void(show_value_ftype)(struct ui_file *file, int from_tty, struct cmd_list_element *cmd, const char *value)
Enumerations
enum command_class {
class_deprecated = -3, all_classes = -2, all_commands = -1, no_class = -1,
class_run = 0, class_vars, class_stack, class_files,
class_support, class_info, class_breakpoint, class_trace,
class_alias, class_bookmark, class_obscure, class_maintenance,
class_pseudo, class_tui, class_user, class_xdb,
no_set_class
}
enum cmd_types { not_set_cmd, set_cmd, show_cmd }
enum var_types {
var_boolean, var_auto_boolean, var_uinteger, var_integer,
var_string, var_string_noescape, var_optional_filename, var_filename,
var_zinteger, var_zuinteger, var_zuinteger_unlimited, var_enum
}
Functions
int valid_user_defined_cmd_name_p (const char *name)
struct cmd_list_element * add_cmd (const char *, enum command_class, void(*fun)(char *, int), char *, struct cmd_list_element **)
struct cmd_list_element * add_alias_cmd (const char *, const char *, enum command_class, int, struct cmd_list_element **)
struct cmd_list_element * add_prefix_cmd (const char *, enum command_class, void(*fun)(char *, int), char *, struct cmd_list_element **, char *, int, struct cmd_list_element **)
struct cmd_list_element * add_abbrev_prefix_cmd (const char *, enum command_class, void(*fun)(char *, int), char *, struct cmd_list_element **, char *, int, struct cmd_list_element **)
void set_cmd_cfunc (struct cmd_list_element *cmd, cmd_cfunc_ftype *cfunc)
void set_cmd_sfunc (struct cmd_list_element *cmd, cmd_sfunc_ftype *sfunc)
typedef VEC (char_ptr)*completer_ftype(struct cmd_list_element *
int cmd_cfunc_eq (struct cmd_list_element *cmd, void(*cfunc)(char *args, int from_tty))
void set_cmd_context (struct cmd_list_element *cmd, void *context)
void * get_cmd_context (struct cmd_list_element *cmd)
void execute_cmd_pre_hook (struct cmd_list_element *cmd)
void execute_cmd_post_hook (struct cmd_list_element *cmd)
enum cmd_types cmd_type (struct cmd_list_element *cmd)
struct cmd_list_element * lookup_cmd (const char **, struct cmd_list_element *, char *, int, int)
struct cmd_list_element * lookup_cmd_1 (const char **, struct cmd_list_element *, struct cmd_list_element **, int)
struct cmd_list_element * deprecate_cmd (struct cmd_list_element *, char *)
void deprecated_cmd_warning (const char *)
int lookup_cmd_composition (const char *text, struct cmd_list_element **alias, struct cmd_list_element **prefix_cmd, struct cmd_list_element **cmd)
struct cmd_list_element * add_com (const char *, enum command_class, void(*fun)(char *, int), char *)
struct cmd_list_element * add_com_alias (const char *, const char *, enum command_class, int)
struct cmd_list_element * add_info (const char *, void(*fun)(char *, int), char *)
struct cmd_list_element * add_info_alias (const char *, char *, int)
const char const char *void help_list (struct cmd_list_element *, char *, enum command_class, struct ui_file *)
void add_setshow_enum_cmd (const char *name, enum command_class class, const char *const *enumlist, const char **var, const char *set_doc, const char *show_doc, const char *help_doc, cmd_sfunc_ftype *set_func, show_value_ftype *show_func, struct cmd_list_element **set_list, struct cmd_list_element **show_list)
void add_setshow_auto_boolean_cmd (const char *name, enum command_class class, enum auto_boolean *var, const char *set_doc, const char *show_doc, const char *help_doc, cmd_sfunc_ftype *set_func, show_value_ftype *show_func, struct cmd_list_element **set_list, struct cmd_list_element **show_list)
void add_setshow_boolean_cmd (const char *name, enum command_class class, int *var, const char *set_doc, const char *show_doc, const char *help_doc, cmd_sfunc_ftype *set_func, show_value_ftype *show_func, struct cmd_list_element **set_list, struct cmd_list_element **show_list)
void add_setshow_filename_cmd (const char *name, enum command_class class, char **var, const char *set_doc, const char *show_doc, const char *help_doc, cmd_sfunc_ftype *set_func, show_value_ftype *show_func, struct cmd_list_element **set_list, struct cmd_list_element **show_list)
void add_setshow_string_cmd (const char *name, enum command_class class, char **var, const char *set_doc, const char *show_doc, const char *help_doc, cmd_sfunc_ftype *set_func, show_value_ftype *show_func, struct cmd_list_element **set_list, struct cmd_list_element **show_list)
struct cmd_list_element * add_setshow_string_noescape_cmd (const char *name, enum command_class class, char **var, const char *set_doc, const char *show_doc, const char *help_doc, cmd_sfunc_ftype *set_func, show_value_ftype *show_func, struct cmd_list_element **set_list, struct cmd_list_element **show_list)
void add_setshow_optional_filename_cmd (const char *name, enum command_class class, char **var, const char *set_doc, const char *show_doc, const char *help_doc, cmd_sfunc_ftype *set_func, show_value_ftype *show_func, struct cmd_list_element **set_list, struct cmd_list_element **show_list)
void add_setshow_integer_cmd (const char *name, enum command_class class, int *var, const char *set_doc, const char *show_doc, const char *help_doc, cmd_sfunc_ftype *set_func, show_value_ftype *show_func, struct cmd_list_element **set_list, struct cmd_list_element **show_list)
void add_setshow_uinteger_cmd (const char *name, enum command_class class, unsigned int *var, const char *set_doc, const char *show_doc, const char *help_doc, cmd_sfunc_ftype *set_func, show_value_ftype *show_func, struct cmd_list_element **set_list, struct cmd_list_element **show_list)
void add_setshow_zinteger_cmd (const char *name, enum command_class class, int *var, const char *set_doc, const char *show_doc, const char *help_doc, cmd_sfunc_ftype *set_func, show_value_ftype *show_func, struct cmd_list_element **set_list, struct cmd_list_element **show_list)
void add_setshow_zuinteger_cmd (const char *name, enum command_class class, unsigned int *var, const char *set_doc, const char *show_doc, const char *help_doc, cmd_sfunc_ftype *set_func, show_value_ftype *show_func, struct cmd_list_element **set_list, struct cmd_list_element **show_list)
void add_setshow_zuinteger_unlimited_cmd (const char *name, enum command_class class, int *var, const char *set_doc, const char *show_doc, const char *help_doc, cmd_sfunc_ftype *set_func, show_value_ftype *show_func, struct cmd_list_element **set_list, struct cmd_list_element **show_list)
void cmd_show_list (struct cmd_list_element *, int, char *)
void error_no_arg (char *) ATTRIBUTE_NORETURN
void dont_repeat (void)
struct cleanup * prevent_dont_repeat (void)
void not_just_help_class_command (char *, int)
int cmd_func_p (struct cmd_list_element *cmd)
void cmd_func (struct cmd_list_element *cmd, char *args, int from_tty)
Variables
const char const char int
show_value_ftype deprecated_show_value_hack
Define Documentation
#define CMD_LIST_AMBIGUOUS ((struct cmd_list_element *) -1)
Definition at line 184 of file command.h.
Referenced by lookup_cmd(), lookup_cmd_1(), lookup_cmd_composition(), and set_verbose().
Typedef Documentation
typedef void cmd_cfunc_ftype(char *args, int from_tty)
Definition at line 149 of file command.h.
typedef void cmd_sfunc_ftype(char *args, int from_tty, struct cmd_list_element *c)
Definition at line 153 of file command.h.
typedef enum cmd_types cmd_types
typedef const char const char* void set_cmd_completer(struct cmd_list_element *, completer_ftype *)
typedef void(show_value_ftype)(struct ui_file *file, int from_tty, struct cmd_list_element *cmd, const char *value)
Definition at line 232 of file command.h.
typedef enum var_types var_types
Enumeration Type Documentation
enum cmd_types
Enumerator:
not_set_cmd
set_cmd
show_cmd
Definition at line 51 of file command.h.
enum command_class
Enumerator:
class_deprecated
all_classes
all_commands
no_class
class_run
class_vars
class_stack
class_files
class_support
class_info
class_breakpoint
class_trace
class_alias
class_bookmark
class_obscure
class_maintenance
class_pseudo
class_tui
class_user
class_xdb
no_set_class
Definition at line 33 of file command.h.
enum var_types
Enumerator:
var_boolean
var_auto_boolean
var_uinteger
var_integer
var_string
var_string_noescape
var_optional_filename
var_filename
var_zinteger
var_zuinteger
var_zuinteger_unlimited
var_enum
Definition at line 60 of file command.h.
Function Documentation
struct cmd_list_element* add_abbrev_prefix_cmd (const char * , enum command_class, void(*)(char *, int) fun, char * , struct cmd_list_element ** , char * , int , struct cmd_list_element **) [read]
Definition at line 355 of file cli-decode.c.
References cmd_list_element::abbrev_flag, add_cmd(), cmd_list_element::allow_unknown, cmd_list_element::prefixlist, and cmd_list_element::prefixname.
struct cmd_list_element* add_alias_cmd (const char * , const char * , enum command_class, int , struct cmd_list_element **) [read]
Definition at line 275 of file cli-decode.c.
References cmd_list_element::abbrev_flag, add_cmd(), cmd_list_element::alias_chain, cmd_list_element::aliases, cmd_list_element::allow_unknown, cmd_list_element::cmd_pointer, delete_cmd(), cmd_list_element::doc, DOC_ALLOCATED, cmd_list_element::flags, cmd_list_element::func, cmd_list_element::function, gdb_assert, lookup_cmd(), cmd_list_element::prefixlist, cmd_list_element::prefixname, and set_cmd_prefix().
Referenced by _initialize_cp_support(), _initialize_macrocmd(), _initialize_mips_tdep(), _initialize_record(), _initialize_record_full(), _initialize_solib(), _initialize_tracepoint(), _initialize_windows_tdep(), add_com_alias(), add_info_alias(), add_packet_config_cmd(), add_task_commands(), add_thread_commands(), alias_command(), and initialize_current_architecture().
struct cmd_list_element* add_cmd (const char * , enum command_class, void(*)(char *, int) fun, char * , struct cmd_list_element **) [read]
Definition at line 186 of file cli-decode.c.
References cmd_list_element::abbrev_flag, cmd_list_element::alias_chain, cmd_list_element::aliases, cmd_list_element::allow_unknown, cmd_list_element::class, cmd_list_element::cmd_pointer, delete_cmd(), cmd_list_element::destroyer, cmd_list_element::doc, cmd_list_element::enums, cmd_list_element::flags, cmd_list_element::hook_in, cmd_list_element::hook_post, cmd_list_element::hook_pre, cmd_list_element::hookee_post, cmd_list_element::hookee_pre, cmd_list_element::name, name, cmd_list_element::next, not_set_cmd, p, cmd_list_element::pre_show_hook, cmd_list_element::prefix, cmd_list_element::prefixlist, cmd_list_element::prefixname, cmd_list_element::replacement, set_cmd_cfunc(), set_cmd_context(), cmd_list_element::type, cmd_list_element::user_commands, cmd_list_element::var, var_boolean, cmd_list_element::var_type, and xmalloc().
Referenced by _initialize_avr_tdep(), _initialize_cli_cmds(), _initialize_cli_dump(), _initialize_cli_logging(), _initialize_cp_abi(), _initialize_cp_namespace(), _initialize_cp_support(), _initialize_fork_child(), _initialize_gdb_bfd(), _initialize_go32_nat(), _initialize_hppa_tdep(), _initialize_macrocmd(), _initialize_mem(), _initialize_mem_search(), _initialize_mips_tdep(), _initialize_psymtab(), _initialize_record(), _initialize_record_full(), _initialize_regcache(), _initialize_reggroup(), _initialize_reverse(), _initialize_sol_thread(), _initialize_spu_tdep(), _initialize_step_skip(), _initialize_symfile_mem(), _initialize_target_descriptions(), _initialize_tasks(), _initialize_thread_db(), _initialize_tracepoint(), _initialize_tui_regs(), _initialize_windows_nat(), _initialize_windows_tdep(), add_abbrev_prefix_cmd(), add_alias_cmd(), add_catch_command(), add_com(), add_deprecated_target_alias(), add_dump_command(), add_info(), add_internal_function(), add_prefix_cmd(), add_set_or_show_cmd(), add_target_with_completer(), add_task_commands(), add_thread_commands(), bsd_kvm_add_target(), cmdpy_init(), define_command(), init_cli_cmds(), initialize_inferiors(), initialize_progspace(), initialize_remote_fileio(), and initialize_targets().
struct cmd_list_element* add_com (const char * , enum command_class, void(*)(char *, int) fun, char *) [read]
Definition at line 861 of file cli-decode.c.
References add_cmd(), and cmdlist.
Referenced by _initialize_cli_cmds(), _initialize_cli_dump(), _initialize_cli_script(), _initialize_gcore(), _initialize_m32r_rom(), _initialize_mem(), _initialize_objc_language(), _initialize_python(), _initialize_regcache(), _initialize_remote_m32r(), _initialize_remote_mips(), _initialize_remote_sim(), _initialize_reverse(), _initialize_solib(), _initialize_tracepoint(), _initialize_tui_layout(), _initialize_tui_regs(), _initialize_tui_stack(), _initialize_tui_win(), _initialize_windows_nat(), gdbtk_init(), init_main(), initialize_inferiors(), initialize_targets(), and initialize_utils().
struct cmd_list_element* add_com_alias (const char * , const char * , enum command_class, int) [read]
Definition at line 870 of file cli-decode.c.
References add_alias_cmd(), and cmdlist.
Referenced by _initialize_cli_cmds(), _initialize_gcore(), _initialize_objc_language(), _initialize_python(), _initialize_record(), _initialize_reverse(), _initialize_tracepoint(), _initialize_tui_win(), _initialize_windows_nat(), and alias_command().
struct cmd_list_element* add_info (const char * , void(*)(char *, int) fun, char *) [read]
Definition at line 845 of file cli-decode.c.
References add_cmd(), infolist, and no_class.
Referenced by _initialize_auxv(), _initialize_cli_cmds(), _initialize_cp_support(), _initialize_darwin_info_commands(), _initialize_mem(), _initialize_objc_language(), _initialize_osdata(), _initialize_procfs(), _initialize_reverse(), _initialize_ser_dos(), _initialize_solib(), _initialize_step_skip(), _initialize_tasks(), _initialize_tracepoint(), _initialize_tui_win(), initialize_inferiors(), and initialize_targets().
struct cmd_list_element* add_info_alias (const char * , char * , int) [read]
Definition at line 853 of file cli-decode.c.
References add_alias_cmd(), and infolist.
Referenced by add_task_commands(), and set_windows_aliases().
struct cmd_list_element* add_prefix_cmd (const char * , enum command_class, void(*)(char *, int) fun, char * , struct cmd_list_element ** , char * , int , struct cmd_list_element **) [read]
Definition at line 327 of file cli-decode.c.
References add_cmd(), cmd_list_element::allow_unknown, cmdlist, cmd_list_element::next, p, cmd_list_element::prefix, cmd_list_element::prefixlist, cmd_list_element::prefixname, and set_cmd_prefix().
Referenced by _initialize_ada_language(), _initialize_arm_tdep(), _initialize_cli_cmds(), _initialize_cli_dump(), _initialize_cli_logging(), _initialize_cp_support(), _initialize_frame(), _initialize_go32_nat(), _initialize_macrocmd(), _initialize_mem(), _initialize_mips_tdep(), _initialize_python(), _initialize_record(), _initialize_record_full(), _initialize_rs6000_tdep(), _initialize_sh_tdep(), _initialize_spu_tdep(), _initialize_step_skip(), _initialize_target_descriptions(), _initialize_tracepoint(), _initialize_tui_regs(), _initialize_tui_win(), add_internal_problem_command(), add_target_with_completer(), add_task_commands(), add_thread_commands(), auto_load_info_cmdlist_get(), auto_load_set_cmdlist_get(), auto_load_show_cmdlist_get(), bsd_kvm_add_target(), cmdpy_init(), info_probes_cmdlist_get(), init_w32_command_list(), and tui_get_cmd_list().
void add_setshow_auto_boolean_cmd (const char * name, enum command_class class, enum auto_boolean * var, const char * set_doc, const char * show_doc, const char * help_doc, cmd_sfunc_ftype * set_func, show_value_ftype * show_func, struct cmd_list_element ** set_list, struct cmd_list_element ** show_list)
Definition at line 504 of file cli-decode.c.
References add_setshow_cmd_full(), auto_boolean_enums, cmd_list_element::enums, and var_auto_boolean.
Referenced by _initialize_mips_tdep(), _initialize_rs6000_tdep(), add_packet_config_cmd(), and add_setshow_generic().
void add_setshow_boolean_cmd (const char * name, enum command_class class, int * var, const char * set_doc, const char * show_doc, const char * help_doc, cmd_sfunc_ftype * set_func, show_value_ftype * show_func, struct cmd_list_element ** set_list, struct cmd_list_element ** show_list)
Definition at line 529 of file cli-decode.c.
References add_setshow_cmd_full(), cmd_list_element::enums, and var_boolean.
Referenced by _initialize_aarch64_tdep(), _initialize_ada_language(), _initialize_aix_thread(), _initialize_arm_tdep(), _initialize_cli_cmds(), _initialize_cli_logging(), _initialize_cris_tdep(), _initialize_darwin_inferior(), _initialize_dec_thread(), _initialize_demangler(), _initialize_frame(), _initialize_gdbtypes(), _initialize_gnu_nat(), _initialize_hppa_tdep(), _initialize_mem(), _initialize_mips_linux_nat(), _initialize_mips_tdep(), _initialize_nios2_tdep(), _initialize_notif(), _initialize_pascal_valprint(), _initialize_proc_api(), _initialize_record_full(), _initialize_remote_mips(), _initialize_remote_monitors(), _initialize_rs6000_tdep(), _initialize_solib(), _initialize_solib_aix(), _initialize_spu_tdep(), _initialize_symfile_debug(), _initialize_thread_db(), _initialize_tracepoint(), _initialize_windows_nat(), _initialize_windows_tdep(), add_setshow_generic(), add_show_debug_regs_command(), init_main(), initialize_inferiors(), initialize_targets(), and initialize_utils().
void add_setshow_enum_cmd (const char * name, enum command_class class, const char *const * enumlist, const char ** var, const char * set_doc, const char * show_doc, const char * help_doc, cmd_sfunc_ftype * set_func, show_value_ftype * show_func, struct cmd_list_element ** set_list, struct cmd_list_element ** show_list)
Definition at line 475 of file cli-decode.c.
References add_setshow_cmd_full(), cmd_list_element::enums, and var_enum.
Referenced by _initialize_agent(), _initialize_arm_tdep(), _initialize_charset(), _initialize_cli_cmds(), _initialize_cris_tdep(), _initialize_demangler(), _initialize_filesystem(), _initialize_gdb_osabi(), _initialize_gdbarch_utils(), _initialize_mips_tdep(), _initialize_python(), _initialize_rs6000_tdep(), _initialize_sh_tdep(), _initialize_tui_win(), add_internal_problem_command(), add_language(), add_setshow_generic(), and initialize_current_architecture().
void add_setshow_filename_cmd (const char * name, enum command_class class, char ** var, const char * set_doc, const char * show_doc, const char * help_doc, cmd_sfunc_ftype * set_func, show_value_ftype * show_func, struct cmd_list_element ** set_list, struct cmd_list_element ** show_list)
Definition at line 551 of file cli-decode.c.
References add_setshow_cmd_full(), and var_filename.
Referenced by _initialize_cli_logging(), _initialize_fork_child(), _initialize_proc_api(), _initialize_solib(), _initialize_target_descriptions(), add_setshow_generic(), and init_main().
void add_setshow_integer_cmd (const char * name, enum command_class class, int * var, const char * set_doc, const char * show_doc, const char * help_doc, cmd_sfunc_ftype * set_func, show_value_ftype * show_func, struct cmd_list_element ** set_list, struct cmd_list_element ** show_list)
Definition at line 657 of file cli-decode.c.
References add_setshow_cmd_full(), and var_integer.
Referenced by add_setshow_generic().
void add_setshow_optional_filename_cmd (const char * name, enum command_class class, char ** var, const char * set_doc, const char * show_doc, const char * help_doc, cmd_sfunc_ftype * set_func, show_value_ftype * show_func, struct cmd_list_element ** set_list, struct cmd_list_element ** show_list)
Definition at line 614 of file cli-decode.c.
References add_setshow_cmd_full(), and var_optional_filename.
Referenced by _initialize_solib(), _initialize_thread_db(), and add_setshow_generic().
void add_setshow_string_cmd (const char * name, enum command_class class, char ** var, const char * set_doc, const char * show_doc, const char * help_doc, cmd_sfunc_ftype * set_func, show_value_ftype * show_func, struct cmd_list_element ** set_list, struct cmd_list_element ** show_list)
Definition at line 573 of file cli-decode.c.
References add_setshow_cmd_full(), and var_string.
Referenced by _initialize_m32r_rom(), _initialize_remote_mips(), _initialize_tracepoint(), add_setshow_generic(), and init_main().
struct cmd_list_element* add_setshow_string_noescape_cmd (const char * name, enum command_class class, char ** var, const char * set_doc, const char * show_doc, const char * help_doc, cmd_sfunc_ftype * set_func, show_value_ftype * show_func, struct cmd_list_element ** set_list, struct cmd_list_element ** show_list) [read]
Definition at line 592 of file cli-decode.c.
References add_setshow_cmd_full(), set_cmd, and var_string_noescape.
Referenced by add_setshow_generic().
void add_setshow_uinteger_cmd (const char * name, enum command_class class, unsigned int * var, const char * set_doc, const char * show_doc, const char * help_doc, cmd_sfunc_ftype * set_func, show_value_ftype * show_func, struct cmd_list_element ** set_list, struct cmd_list_element ** show_list)
Definition at line 682 of file cli-decode.c.
References add_setshow_cmd_full(), and var_uinteger.
Referenced by _initialize_cli_cmds(), _initialize_frame(), _initialize_record(), _initialize_record_full(), add_setshow_generic(), init_main(), and initialize_utils().
void add_setshow_zinteger_cmd (const char * name, enum command_class class, int * var, const char * set_doc, const char * show_doc, const char * help_doc, cmd_sfunc_ftype * set_func, show_value_ftype * show_func, struct cmd_list_element ** set_list, struct cmd_list_element ** show_list)
Definition at line 707 of file cli-decode.c.
References add_setshow_cmd_full(), and var_zinteger.
Referenced by _initialize_alpha_tdep(), _initialize_cli_cmds(), _initialize_mips_tdep(), _initialize_remote_mips(), _initialize_ser_dos(), add_setshow_generic(), and init_main().
void add_setshow_zuinteger_cmd (const char * name, enum command_class class, unsigned int * var, const char * set_doc, const char * show_doc, const char * help_doc, cmd_sfunc_ftype * set_func, show_value_ftype * show_func, struct cmd_list_element ** set_list, struct cmd_list_element ** show_list)
Definition at line 751 of file cli-decode.c.
References add_setshow_cmd_full(), and var_zuinteger.
Referenced by _initialize_cris_tdep(), _initialize_darwin_inferior(), _initialize_dsbt_solib(), _initialize_dwarf2loc(), _initialize_frame(), _initialize_frv_solib(), _initialize_gdbtypes(), _initialize_linux_nat(), _initialize_machoread(), _initialize_mips_tdep(), _initialize_observer(), _initialize_record(), _initialize_remote_monitors(), _initialize_thread_db(), _initialize_xtensa_tdep(), and initialize_targets().
void add_setshow_zuinteger_unlimited_cmd (const char * name, enum command_class class, int * var, const char * set_doc, const char * show_doc, const char * help_doc, cmd_sfunc_ftype * set_func, show_value_ftype * show_func, struct cmd_list_element ** set_list, struct cmd_list_element ** show_list)
Definition at line 724 of file cli-decode.c.
References add_setshow_cmd_full(), and var_zuinteger_unlimited.
Referenced by _initialize_cli_cmds(), and _initialize_tracepoint().
int cmd_cfunc_eq (struct cmd_list_element * cmd, void(*)(char *args, int from_tty) cfunc)
Definition at line 137 of file cli-decode.c.
References cmd_list_element::cfunc, do_cfunc(), cmd_list_element::func, and cmd_list_element::function.
Referenced by encode_actions_1(), is_complete_command(), trace_dump_actions(), and validate_actionline().
void cmd_func (struct cmd_list_element * cmd, char * args, int from_tty)
Definition at line 1879 of file cli-decode.c.
References _, cmd_func_p(), error(), and cmd_list_element::func.
Referenced by cmd_show_list(), execute_command(), gdbtk_call_command(), info_auto_load_cmd(), and show_remote_cmd().
int cmd_func_p (struct cmd_list_element * cmd)
Definition at line 1871 of file cli-decode.c.
References cmd_list_element::func.
Referenced by cmd_func(), and execute_command().
void cmd_show_list (struct cmd_list_element * , int , char *)
Definition at line 673 of file cli-setshow.c.
References cmd_list_element::abbrev_flag, cmd_list_element::class, cmd_func(), cmd_show_list(), current_uiout, do_cleanups(), do_show_command(), make_cleanup_ui_out_tuple_begin_end(), cmd_list_element::name, cmd_list_element::next, no_set_class, cmd_list_element::prefixlist, cmd_list_element::prefixname, show_cmd, strstr(), cmd_list_element::type, ui_out_field_string(), ui_out_is_mi_like_p(), and ui_out_text().
Referenced by cmd_show_list(), maintenance_show_cmd(), serial_show_cmd(), show_ada_command(), show_arm_command(), show_auto_load_cmd(), show_backtrace_cmd(), show_check(), show_command(), show_dcache_command(), show_debug(), show_dwarf2_cmd(), show_history(), show_per_command_cmd(), show_powerpc_command(), show_print(), show_print_raw(), show_print_type(), show_ravenscar_command(), show_record_command(), show_record_full_command(), show_tdesc_cmd(), and user_show_python().
enum cmd_types cmd_type (struct cmd_list_element * cmd)
Definition at line 156 of file cli-decode.c.
References cmd_list_element::type.
struct cmd_list_element* deprecate_cmd (struct cmd_list_element * , char *) [read]
Definition at line 262 of file cli-decode.c.
References CMD_DEPRECATED, DEPRECATED_WARN_USER, cmd_list_element::flags, and cmd_list_element::replacement.
Referenced by _initialize_cp_namespace(), _initialize_record_full(), and add_deprecated_target_alias().
void deprecated_cmd_warning (const char *)
Definition at line 1593 of file cli-decode.c.
References CMD_DEPRECATED, DEPRECATED_WARN_USER, cmd_list_element::flags, lookup_cmd_composition(), cmd_list_element::name, cmd_list_element::prefixname, printf_filtered(), and cmd_list_element::replacement.
Referenced by execute_command(), and lookup_cmd_1().
void dont_repeat (void)
Definition at line 587 of file top.c.
References instream, saved_command_line, server_command, and suppress_dont_repeat.
Referenced by add_symbol_file_command(), agent_command_1(), agent_eval_command_one(), attach_command(), auto_load_info_scripts(), cd_command(), cmd_record_call_history(), cmd_record_insn_history(), cmdpy_dont_repeat(), complete_command(), core_file_command(), delete_command(), delete_trace_command(), delete_trace_variable_command(), detach_command(), directory_command(), disconnect_command(), display_command(), dll_symbol_command(), interrupt_target_command(), line_info(), load_command(), maint_agent_printf_command(), maintenance_info_symtabs(), maintenance_print_msymbols(), maintenance_print_objfiles(), maintenance_print_psymbols(), maintenance_print_symbols(), mem_delete_command(), mi_cmd_env_dir(), mi_cmd_env_path(), path_command(), prompt_for_continue(), read_command_lines_1(), recurse_read_control_structure(), run_command_1(), save_bookmark_command(), sharedlibrary_command(), signal_command(), symbol_file_command(), target_preopen(), trace_start_command(), tui_handle_resize_during_io(), tui_rl_switch_mode(), and undisplay_command().
void error_no_arg (char *)
Definition at line 207 of file cli-cmds.c.
References _, and error().
Referenced by advance_command(), agent_command_1(), bsd_kvm_pcb_cmd(), bsd_kvm_proc_cmd(), condition_command(), decode_line_2(), do_set_command(), gdbsim_load(), generic_load(), get_selections(), get_tracepoint_by_number(), go32_pte_for_address(), handle_command(), ignore_command(), interpreter_exec_cmd(), jump_command(), maint_agent_printf_command(), map_breakpoint_numbers(), map_display_numbers(), mem_command(), monitor_load(), parse_exp_in_context_1(), parse_pid_to_attach(), pipe_windows_open(), proc_trace_syscalls(), remote_delete_command(), remote_get_command(), remote_put_command(), set_environment_command(), signal_command(), sym_info(), tk_command(), trace_save_command(), trace_variable_command(), ui_printf(), validate_comname(), x_command(), and xdb_handle_command().
void execute_cmd_post_hook (struct cmd_list_element * cmd)
Definition at line 286 of file cli-script.c.
References clear_hook_in_cleanup(), do_cleanups(), execute_user_command(), cmd_list_element::hook_in, cmd_list_element::hook_post, and make_cleanup().
Referenced by execute_command().
void execute_cmd_pre_hook (struct cmd_list_element * cmd)
Definition at line 274 of file cli-script.c.
References clear_hook_in_cleanup(), do_cleanups(), execute_user_command(), cmd_list_element::hook_in, cmd_list_element::hook_pre, and make_cleanup().
Referenced by execute_command(), and hook_stop_stub().
void* get_cmd_context (struct cmd_list_element * cmd)
Definition at line 150 of file cli-decode.c.
References cmd_list_element::context.
Referenced by call_dump_func(), catch_ada_exception_command(), catch_assert_command(), catch_catch_command(), catch_exec_command_1(), catch_fork_command_1(), catch_load_or_unload(), catch_rethrow_command(), catch_signal_command(), catch_syscall_command_1(), catch_throw_command(), cmdpy_function(), get_set_value(), get_show_value(), and VEC().
const char const char* void help_list (struct cmd_list_element * , char * , enum command_class, struct ui_file *)
Definition at line 1012 of file cli-decode.c.
References all_classes, fprintf_filtered(), fputs_filtered(), help_cmd_list(), len, and wrap_here().
Referenced by append_command(), binary_append_command(), binary_dump_command(), dump_command(), go32_info_dos_command(), help_cmd(), ihex_dump_command(), info_command(), info_spu_command(), info_w32_command(), macro_command(), maint_cplus_command(), maintenance_command(), maintenance_info_command(), maintenance_print_command(), maintenance_set_cmd(), overlay_command(), remote_command(), save_command(), serial_set_cmd(), set_ada_command(), set_arm_command(), set_backtrace_cmd(), set_check(), set_dcache_command(), set_debug(), set_dwarf2_cmd(), set_history(), set_mips_command(), set_powerpc_command(), set_print(), set_print_raw(), set_print_type(), set_ravenscar_command(), set_record_command(), set_record_full_command(), set_remote_cmd(), set_sh_command(), set_spu_command(), set_tcp_cmd(), set_tdesc_cmd(), show_mips_command(), show_sh_command(), show_spu_command(), show_tcp_cmd(), srec_dump_command(), tekhex_dump_command(), tui_command(), tui_reg_command(), unset_command(), unset_tdesc_cmd(), and user_set_python().
struct cmd_list_element* lookup_cmd (const char ** , struct cmd_list_element * , char * , int , int) [read]
Definition at line 1471 of file cli-decode.c.
References _, cmd_list_element::allow_unknown, CMD_LIST_AMBIGUOUS, error(), find_command_name_length(), int, len, lookup_cmd_1(), cmd_list_element::name, cmd_list_element::next, cmd_list_element::prefixlist, cmd_list_element::prefixname, set_cmd, cmd_list_element::type, and undef_cmd_error().
Referenced by add_alias_cmd(), add_setshow_generic(), define_command(), document_command(), encode_actions_1(), execute_command(), help_cmd(), show_user(), trace_dump_actions(), validate_actionline(), and validate_comname().
struct cmd_list_element* lookup_cmd_1 (const char ** , struct cmd_list_element * , struct cmd_list_element ** , int) [read]
Definition at line 1328 of file cli-decode.c.
References CMD_LIST_AMBIGUOUS, cmd_list_element::cmd_pointer, deprecated_cmd_warning(), DEPRECATED_WARN_USER, find_cmd(), find_command_name_length(), cmd_list_element::flags, len, line, lookup_cmd_1(), memcpy(), and cmd_list_element::prefixlist.
Referenced by alias_command(), gdbpy_parse_command_name(), lookup_cmd(), lookup_cmd_1(), set_verbose(), and valid_command_p().
int lookup_cmd_composition (const char * text, struct cmd_list_element ** alias, struct cmd_list_element ** prefix_cmd, struct cmd_list_element ** cmd)
Definition at line 1667 of file cli-decode.c.
References CMD_LIST_AMBIGUOUS, cmd_list_element::cmd_pointer, cmdlist, find_cmd(), find_command_name_length(), len, memcpy(), and cmd_list_element::prefixlist.
Referenced by deprecated_cmd_warning(), gdbtk_interpreter_init(), and maintenance_do_deprecate().
void not_just_help_class_command (char * , int)
Definition at line 371 of file cli-decode.c.
struct cleanup* prevent_dont_repeat (void) [read]
Definition at line 603 of file top.c.
References make_cleanup_restore_integer(), and suppress_dont_repeat.
Referenced by bpstat_do_actions_1().
void set_cmd_cfunc (struct cmd_list_element * cmd, cmd_cfunc_ftype * cfunc)
Definition at line 111 of file cli-decode.c.
References cmd_list_element::cfunc, do_cfunc(), cmd_list_element::func, and cmd_list_element::function.
Referenced by add_cmd(), and gdbtk_interpreter_init().
void set_cmd_context (struct cmd_list_element * cmd, void * context)
Definition at line 144 of file cli-decode.c.
References cmd_list_element::context.
Referenced by add_catch_command(), add_cmd(), add_dump_command(), add_setshow_generic(), and cmdpy_init().
void set_cmd_sfunc (struct cmd_list_element * cmd, cmd_sfunc_ftype * sfunc)
Definition at line 127 of file cli-decode.c.
References do_sfunc(), cmd_list_element::func, cmd_list_element::function, and cmd_list_element::sfunc.
Referenced by add_catch_command(), add_set_or_show_cmd(), and add_setshow_cmd_full().
int valid_user_defined_cmd_name_p (const char * name)
Definition at line 1268 of file cli-decode.c.
References p.
Referenced by alias_command().
const char enum type_code const char const char enum type_code const char const char const char const char * VEC (char_ptr)
Definition at line 116 of file completer.c.
References p, VEC, VEC_safe_push, word, xfree(), and xmalloc().
Variable Documentation
show_value_ftype deprecated_show_value_hack
Referenced by deprecated_show_value_hack(), do_show_command(), show_args_command(), and show_mask_address().
const char const char int
Definition at line 219 of file command.h.
Referenced by gdb.command.frame_filters.SetFrameFilterPriority::_set_filter_priority(), ada_add_block_symbols(), add_this_object_header_file(), arm_linux_hw_breakpoint_initialize(), arm_linux_hw_watchpoint_initialize(), bl_to_blrl_insn_p(), bpdisp_text(), bptype_string(), branch_dest(), compare_symbol_name(), compile_probe_arg(), complete_target_initialization(), compute_probe_arg(), cris_delayed_get_disassembler(), dcache_xfer_memory(), do_gdb_signal_to_host(), examine_prologue(), execute_code(), gdb.command.explore.PointerExplorer::explore_expr(), gdb.command.explore.ArrayExplorer::explore_expr(), extract_long_unsigned_integer(), fetch_instruction(), find_slot_in_mapped_hash(), find_source_lines(), gdb_regformat(), gdb_signal_from_host(), get_java_utf8_name(), get_module_name(), get_number_trailer(), gnuv3_baseclass_offset(), go32_sysinfo(), handle_command(), hardwire_print_tty_state(), ia64_breakpoint_from_pc(), ia64_memory_insert_breakpoint(), ia64_write_pc(), info_checkpoints_command(), info_mappings_callback(), init_dummy_target(), install_variable(), iterate_over_minimal_symbols(), linux_gdb_signal_from_target(), linux_handle_syscall_trap(), longest_to_int(), lookup_cmd(), lookup_minimal_symbol_internal(), m68hc11_scan_prologue(), mi_cmd_data_list_register_values(), mips_adjust_breakpoint_address(), mips_gdb_signal_from_target(), monitor_read_memory_single(), monitor_vsprintf(), operator_length_standard(), parse_spufs_run(), print_frame_args(), print_frame_nameless_args(), quit_force(), read_pe_exported_syms(), read_xcoff_symtab(), record_btrace_call_history_range(), record_btrace_insn_history_range(), record_linux_msghdr(), record_linux_sockaddr(), record_linux_system_call(), remote_fileio_extract_ptr_w_len(), remote_trace_find(), rs6000_skip_trampoline_code(), score7_analyze_prologue(), select_event_lwp(), set_parameter_value(), signal_cache_update(), signals_info(), strtoulst(), tfile_get_trace_state_variable_value(), tfile_trace_find(), trace_save(), tui_dispatch_ctrl_char(), uninstall_variable(), unpack_value_bits_as_long_1(), value_assign(), varobj_get_handle(), VEC(), xtensa_linux_gdb_signal_from_target(), xtensa_register_read_masked(), and yylex().