GDB (xrefs): /home/stan/gdb/src/gdb/common/common-utils.h File Reference
/home/stan/gdb/src/gdb/common/common-utils.h File Reference
#include "config.h"
#include "ansidecl.h"
#include <stddef.h>
#include <stdarg.h>
Functions
void malloc_failure (long size) ATTRIBUTE_NORETURN
void internal_error (const char *file, int line, const char *,...) ATTRIBUTE_NORETURN ATTRIBUTE_PRINTF(3
void void * xzalloc (size_t)
void xfree (void *)
char * xstrprintf (const char *format,...) ATTRIBUTE_PRINTF(1
char char * xstrvprintf (const char *format, va_list ap) ATTRIBUTE_PRINTF(1
char char int xsnprintf (char *str, size_t size, const char *format,...) ATTRIBUTE_PRINTF(3
char char int char * savestring (const char *ptr, size_t len)
Function Documentation
void internal_error (const char * file, int line, const char * , ...)
Referenced by _initialize_gdb_osabi(), _initialize_mips_tdep(), aarch64_dwarf2_prev_register(), aarch64_pseudo_register_name(), aarch64_pseudo_register_type(), aarch64_type_align(), ada_exception_breakpoint_ops(), ada_exception_name_addr_1(), ada_exception_sym_name(), add_file_handler(), add_language(), add_symbol_nonexpandable(), addrmap_fixed_create_fixed(), addrmap_fixed_set_empty(), addrmap_mutable_find(), addrmap_mutable_relocate(), alpha_extract_return_value(), alpha_store_return_value(), amd64_get_unused_input_int_reg(), append_tokens_without_splicing(), arg_cleanup(), arm_copy_extra_ld_st(), arm_dwarf2_prev_register(), arm_extract_return_value(), arm_gdbarch_init(), arm_instruction_changes_pc(), arm_linux_init_abi(), arm_netbsd_init_abi_common(), arm_process_displaced_insn(), arm_register_sim_regno(), arm_set_abi(), arm_store_return_value(), arm_type_align(), arm_update_current_architecture(), arm_vfp_cprc_reg_char(), arm_vfp_cprc_unit_length(), ATTRIBUTE_PRINTF(), avr_pseudo_register_read(), avr_pseudo_register_write(), ax_string(), ax_tsv(), bfin_pseudo_register_read(), bfin_pseudo_register_write(), bkpt_print_recreate(), bpstat_what(), bptype_string(), build_section_table(), build_table(), call_function_by_hand(), call_site_to_target_addr(), charset_for_string_type(), check_types_equal(), classify_inner_name(), clear_complaints(), coff_getfilename(), copy_type_recursive(), cp_lookup_nested_symbol(), create_file_handler(), cris_gdbarch_init(), ctx_no_push_dwarf_reg_entry_value(), cygwin_set_dr(), decimal2str(), decimal_binop(), define_command(), delete_file_handler(), displaced_write_reg(), do_examine(), do_show_command(), dwarf2_compile_cfa_to_ax(), dwarf2_compile_expr_to_ax(), dwarf2_evaluate_loc_desc_full(), dwarf2_frame_cache(), dwarf2_frame_prev_register(), elf_gnu_ifunc_resolver_return_stop(), encode_actions_1(), encoding_for_size(), evaluate_subexp_c(), exceptions_state_mc(), execute_cfa_program(), execute_stack_op(), expand(), extract_typed_address(), fetch_register(), find_last_source_symtab_from_partial(), find_partial_die(), finish_backward(), finish_command_continuation(), follow_fork(), frame_stop_reason_string(), frame_unwind_find_by_frame(), frame_unwind_pc_if_available(), free_current_contents(), frv_extract_return_value(), frv_linux_sigcontext_reg_addr(), frv_register_sim_regno(), frv_store_return_value(), gdb_wait_for_event(), gdbarch_lookup_osabi(), gdbarch_printable_names(), gdbarch_register(), gdbarch_register_osabi(), gdbpy_breakpoint_has_py_cond(), gdbpy_should_stop(), gdbsim_store_register(), gen_aggregate_elt_ref(), gen_bitfield_ref(), gen_deref(), gen_expr(), gen_expr_binop_rest(), gen_fetch(), gen_struct_elt_for_reference(), gen_struct_ref_recursive(), gen_var_ref(), generic_elf_osabi_sniff_abi_tag_sections(), get_decimal_float_return_value(), get_frame_sp(), get_reg_mask(), get_return_value(), global_mips_abi(), global_mips_compression(), go32_create_inferior(), go32_get_dr(), go32_set_dr(), h8300_register_name(), h8300_register_type(), h8300s_register_name(), h8300sx_register_name(), handle_file_event(), handle_inferior_event(), hex_string_custom(), hppa_gdbarch_init(), i386_extract_return_value(), i386_handle_nonaligned_watchpoint(), i386_length_and_rw_bits(), i386_linux_fetch_inferior_registers(), i386_linux_store_inferior_registers(), i386_pseudo_register_name(), i386_pseudo_register_read_into_value(), i386_pseudo_register_type(), i386_pseudo_register_write(), i386_store_return_value(), i387_collect_xsave(), ia64_hpux_at_dld_breakpoint_1_p(), ia64_memory_insert_breakpoint(), init_bp_location(), init_core_ops(), init_go32_ops(), initialize_current_architecture(), int_string(), interp_set(), legacy_virtual_frame_pointer(), linux_async_pipe(), linux_handle_extended_wait(), linux_nat_attach(), list_args_or_locals(), lookup_partial_symbol(), m32c_virtual_frame_pointer(), m32r_linux_fetch_inferior_registers(), m32r_linux_store_inferior_registers(), m68k_extract_return_value(), m68k_get_longjmp_target(), m68k_linux_fetch_inferior_registers(), m68k_linux_store_inferior_registers(), m68k_register_name(), m68k_store_return_value(), maintenance_internal_error(), make_srec(), malloc_failure(), mem_file_delete(), mem_file_put(), mem_file_rewind(), mem_file_write(), memory_error_message(), mi_close(), mi_console_file_delete(), mi_console_file_flush(), mi_console_file_fputs(), mi_console_raw_packet(), mi_console_set_raw(), mi_getopt_1(), mi_open(), microblaze_extract_return_value(), mips_abi_regsize(), mips_ax_pseudo_register_push_stack(), mips_common_breakpoint(), mips_fetch_instruction(), mips_gdbarch_init(), mips_insn_size(), mips_linux_watch_get_irw_mask(), mips_linux_watch_get_num_valid(), mips_linux_watch_get_watchhi(), mips_linux_watch_get_watchlo(), mips_linux_watch_set_watchhi(), mips_linux_watch_set_watchlo(), mips_mask_address_p(), mips_o32_return_value(), mips_pseudo_register_read(), mips_pseudo_register_write(), mips_read_fp_register_double(), mips_register_name(), mips_register_to_value(), mips_request(), mips_value_to_register(), mips_xfer_register(), mn10300_extract_return_value(), mn10300_gdbarch_init(), mn10300_store_return_value(), mn10300_type_align(), monitor_dump_regs(), monitor_printf(), monitor_printf_noecho(), msp430_gdbarch_init(), mt_register_type(), normal_stop(), octal2str(), packet_ok(), parse_partial_symbols(), poll_timers(), pop_all_targets_above(), pop_subfile(), powerpc_set_soft_float(), powerpc_set_vector_abi(), print_bp_stop_message(), print_exception(), print_it_masked_watchpoint(), print_longest(), print_mention_exception(), print_mention_masked_watchpoint(), print_mention_watchpoint(), print_one_breakpoint_location(), print_one_exception(), print_recreate_exception(), print_recreate_masked_watchpoint(), print_recreate_watchpoint(), print_scalar_formatted(), process_g_packet(), process_one_symbol(), push_subfile(), push_target(), put_objfile_before(), range_error(), read_address(), read_comp_unit_head(), read_encoded_value(), read_offset_1(), read_pieced_value(), regcache_read_pc(), regcache_write_pc(), reggroups_dump(), register_cp_abi(), register_remote_g_packet_guess(), remote_download_tracepoint(), remote_insert_hw_breakpoint(), remote_insert_watchpoint(), remote_remove_hw_breakpoint(), remote_remove_watchpoint(), remote_send_printf(), remote_threads_extra_info(), remote_write_bytes(), remote_write_bytes_aux(), report_agent_reqs_errors(), rl78_dwarf_reg_to_regnum(), rs6000_create_inferior(), rs6000_pseudo_register_read(), rs6000_pseudo_register_write(), s390_pseudo_register_name(), s390_pseudo_register_read(), s390_pseudo_register_type(), s390_pseudo_register_write(), s390_push_dummy_call(), s390_return_value(), script_from_file(), section_table_xfer_memory_partial(), send_interrupt_sequence(), sentinel_frame_this_id(), serial_readchar(), set_architecture(), set_case_command(), set_cp_abi_as_auto_default(), set_cris_dwarf2_cfi(), set_cris_mode(), set_cris_version(), set_endian(), set_fp_model_sfunc(), set_internalvar_component(), set_language_command(), set_last_displayed_sal(), set_mipsfpu_double_command(), set_mipsfpu_none_command(), set_mipsfpu_single_command(), set_osabi(), set_range_command(), set_remote_protocol_packet_cmd(), set_tdesc_property(), sh64_do_pseudo_register(), sh64_print_register(), show_case_command(), show_exec_direction_func(), show_interrupt_sequence(), show_mask_address(), show_mipsfpu_command(), show_range_command(), show_remote_protocol_packet_cmd(), skip_info(), sparc64_register_type(), spu_bfd_open(), spu_pseudo_register_read(), spu_pseudo_register_write(), spu_register_type(), spu_relocate_section_addresses(), stap_get_expected_argument_type(), stap_get_opcode(), stdio_file_delete(), stdio_file_flush(), stdio_file_fputs(), stdio_file_fseek(), stdio_file_isatty(), stdio_file_read(), stdio_file_write(), store_register(), store_register_using_P(), store_typed_address(), stub_gnu_ifunc_resolver_return_stop(), stub_gnu_ifunc_resolver_stop(), symtab_to_filename_for_display(), target_attach(), target_clear_description(), target_create_inferior(), target_detach(), target_follow_fork(), target_is_pushed(), target_mourn_inferior(), target_require_runnable(), target_thread_address_space(), tdesc_add_compatible(), tdesc_gdb_type(), tdesc_register_type(), tee_file_delete(), tee_file_flush(), tee_file_fputs(), tee_file_isatty(), tee_file_write(), tfile_trace_find(), thumb_process_displaced_16bit_insn(), thumb_process_displaced_32bit_insn(), tic6x_arg_type_alignment(), tic6x_push_dummy_call(), tilegx_register_name(), tracepoint_print_mention(), tracepoint_print_recreate(), tui_exec(), tui_file_adjust_strbuf(), tui_file_delete(), tui_file_flush(), tui_file_get_strbuf(), tui_file_isatty(), tui_file_put(), tui_file_rewind(), typecmp(), ui_file_data(), ui_out_begin(), ui_out_table_begin(), ui_out_table_body(), ui_out_table_end(), ui_out_table_header(), ui_printf(), unlink_objfile(), unpack_mips16(), unpush_target(), update_dprintf_command_list(), update_global_location_list(), value_aggregate_elt(), value_fetch_lazy(), value_of_internalvar(), value_rtti_indirect_type(), VEC(), verify_field(), verify_gdbarch(), watchpoint_to_Z_packet(), wrap_here(), write_var_or_type(), xstormy16_register_name(), xstrvprintf(), xtensa_extract_return_value(), xtensa_pseudo_register_read(), xtensa_pseudo_register_write(), xtensa_reg_to_regnum(), xtensa_register_name(), xtensa_register_type(), xtensa_store_return_value(), and xtensa_verify_config().
void malloc_failure (long size)
Definition at line 1062 of file utils.c.
References _, and internal_error().
Referenced by gdb_buildargv(), xcalloc(), xmalloc(), xml_fetch_content_from_file(), and xrealloc().
char char int char* savestring (const char * ptr, size_t len)
Definition at line 156 of file common-utils.c.
void xfree (void *)
Definition at line 105 of file common-utils.c.
References free().
Referenced by _initialize_ada_language(), _initialize_gdb_bfd(), _initialize_tailcall_frame(), _initialize_tui_interp(), _proc_free(), aarch64_forget_process(), abbrev_table_free(), abbrev_table_read_table(), ada_catchpoint_location_dtor(), ada_inferior_data_cleanup(), ada_main_name(), ada_unhandled_exception_name_addr_from_raise(), ada_varobj_describe_simple_array_child(), ada_varobj_get_value_of_array_variable(), add_angle_brackets(), add_auto_load_safe_path(), add_inferior_command(), add_internal_problem_command(), add_language(), add_msglist(), add_packet_config_cmd(), add_partial_symbol(), add_path(), add_pe_exported_sym(), add_pe_forwarded_sym(), add_solib_catchpoint(), add_symbol_file_command(), addr_info_make_relative(), aix_thread_extra_thread_info(), aix_thread_pid_to_str(), alias_command(), all_tracepoint_actions_and_cleanup(), allocate_psymtab(), allocate_symtab(), ambiguous_names_p(), apropos_command(), archpy_disassemble(), arg_cleanup(), arm_adjust_breakpoint_address(), arm_exidx_new_objfile(), arm_linux_thread_exit(), arrange_linetable(), attach_command_continuation_free_args(), ATTRIBUTE_PRINTF(), auto_load_objfile_script(), auto_load_objfile_script_1(), auto_load_pspace_data_cleanup(), auto_load_safe_path_vec_update(), auxv_inferior_data_cleanup(), avr_io_reg_read_command(), backtrace_command(), base_breakpoint_dtor(), bcache_xfree(), bfd_lookup_symbol_from_dyn_symtab(), bfd_uses_spe_extensions(), bp_location_dtor(), bppy_get_commands(), bppy_init(), bppy_set_condition(), bpstat_check_watchpoint(), bpstat_free(), break_range_command(), breakpoint_notify(), breakpoint_re_set(), breakpoint_re_set_default(), bsd_kvm_open(), buffer_free(), buffer_xml_printf(), build_error_marker_type(), build_section_table(), build_type_unit_groups(), c_get_string(), c_type_print_base(), cache_unref(), call_function_by_hand(), cancel_single_step_breakpoints(), captured_main(), catch_ada_exception_command_split(), catch_exception_command_1(), catch_syscall_inferior_data_cleanup(), catcher_pop(), cd_command(), chain_candidate(), check_fast_tracepoint_sals(), check_for_redefinition(), check_status_exception_catchpoint(), check_stub_method(), classify_name(), cleanup_mapped_symtab(), cleanup_request_data(), clear_collection_list(), clear_command(), clear_dangling_display_expressions(), clear_entries(), clear_header_list(), clear_internalvar(), clear_memory_write_data(), clear_so(), clear_table(), cmdpy_destroyer(), cmdpy_function(), cmdpy_init(), coff_free_info(), coff_locate_sections(), coff_symfile_read(), coff_symtab_read(), command_from_pid(), command_line_handler(), command_line_input(), commandline_from_pid(), commands_command_1(), compare_sections_command(), compile_rx_or_error(), complete_command(), compute_enum_values(), compute_symtab_includes(), copy_terminal_info(), core_close(), core_open(), core_process_module_section(), cp_canonicalize_string(), cp_canonicalize_string_full(), cp_class_name_from_physname(), cp_demangled_name_parse_free(), cp_lookup_symbol_imports_or_template(), cp_print_value(), cppop(), create_all_comp_units(), create_breakpoint(), create_breakpoint_sal(), create_breakpoints_sal(), create_demangled_names_hash(), create_dwo_unit_in_dwp_v1(), create_dwo_unit_in_dwp_v2(), create_excep_cond_exprs(), create_filename_seen_cache(), create_quick_file_names_table(), create_sals_line_offset(), create_strtab(), create_symbol_hash_table(), create_tsv_from_upload(), create_type_unit_group(), create_typedef_hash(), ctf_start(), darwin_current_sos(), darwin_mourn_inferior(), darwin_pid_to_exec_file(), darwin_pspace_data_cleanup(), dbx_free_symfile_info(), dcache_free(), deallocate_reg_mem(), dec_thread_pid_to_str(), decimal_from_floating(), decode_line_2(), decode_line_full(), decode_loadmap(), decode_static_tracepoint_spec(), decref_counted_command_line(), default_xfer_partial(), define_symbol(), del_objfile_sal(), delete_all_bookmarks(), delete_async_event_handler(), delete_async_signal_handler(), delete_breakpoint(), delete_cmd(), delete_file_handler(), delete_file_name_entry(), delete_filename_seen_cache(), delete_one_bookmark(), delete_substitute_path_rule(), delete_symtab_entry(), delete_thread_db_info(), delete_thread_object(), delete_timer(), delete_trace_state_variable(), demangle_for_lookup(), deprecated_insert_raw_breakpoint(), deprecated_remove_raw_breakpoint(), destroy_linespec_result(), destroy_one_procinfo(), dicos_load_module_p(), directory_command(), discard_infcall_control_state(), discard_infcall_suspend_state(), discard_my_cleanups(), discard_my_continuations_1(), displaced_step_fixup(), do_cleanup_end(), do_cleanup_iterator(), do_discard_minimal_symbols_cleanup(), do_map_commands_command(), do_my_cleanups(), do_my_continuations_1(), do_one_display(), do_serial_close(), do_set_command(), do_show_command(), document_command(), dsbt_clear_solib(), dsbt_current_sos(), dsbt_free_so(), dsbt_pspace_data_cleanup(), dsbt_relocate_main_executable(), dtor_catch_exec(), dtor_catch_solib(), dtor_exception(), dtor_exception_catchpoint(), dtor_watchpoint(), dump_insns(), dump_memory_to_file(), dw2_expand_symtabs_matching(), dw2_free_cached_file_names(), dw2_map_symbol_filenames(), dwarf2_add_field(), dwarf2_add_member_fn(), dwarf2_add_typedef(), dwarf2_build_frame_info(), dwarf2_canonicalize_name(), dwarf2_compile_expr_to_ax(), dwarf2_compute_name(), dwarf2_frame_state_free(), dwarf2_frame_state_free_regs(), dwarf2_get_dwz_file(), dwarf2_name(), dwarf2_per_objfile_free(), dwarf2_physname(), dwarf2_release_queue(), dwarf2_start_subfile(), dwarf2_tailcall_sniffer_first(), dwarf_decode_macros(), edit_command(), elf_symfile_read(), enable_break(), enable_break2(), end_arglist(), end_msglist(), end_stabs(), end_symtab_from_static_block(), end_symtab_get_static_block(), enumerate_args(), enumerate_locals(), env_execute_cli_command(), error_stream(), eval_command(), evaluate_subexp_standard(), exec_close(), exec_file_attach(), exec_file_command(), exec_reverse_once(), execute_cfa_program(), expand_hash_table(), expand_hashtable(), extend_buffer_earlier(), fbsd_find_memory_regions(), fbsd_make_corefile_notes(), fbsd_pid_to_exec_file(), fetch_loadmap(), file_is_auto_load_safe(), file_read_description_xml(), filter_results(), filter_sals(), finalize_symtab(), find_and_open_script(), find_and_open_source(), find_condition_and_thread(), find_file_and_directory(), find_frame_funname(), find_global_typedef(), find_linespec_symbols(), find_oload_champ(), find_oload_champ_namespace_loop(), find_overload_match(), find_separate_debug_file(), find_separate_debug_file_by_debuglink(), find_slot_in_mapped_hash(), find_source_lines(), finish_command_continuation_free_arg(), finish_global_stabs(), fixup_definition(), fixup_go_packaging(), fixup_partial_die(), fnpy_call(), foreach_macro(), foreach_macro_in_scope(), forget_cached_source_info_for_objfile(), forget_cached_source_info_partial(), fprintf_symbol_filtered(), frame_info(), frapy_name(), frapy_read_var(), frapy_str(), free_actions_list(), free_address_space(), free_agent_expr(), free_bincl_list(), free_block(), free_bp_location(), free_buffer(), free_char_ptr_vec(), free_clbk(), free_command_lines(), free_completion_list(), free_content(), free_content_elements(), free_current_contents(), free_current_marker(), free_display(), free_dwarf_expr_context(), free_elfinfo(), free_environ(), free_fork(), free_format_pieces(), free_funcalls(), free_hashed_expandable(), free_header_files(), free_heap_comp_unit(), free_inferior(), free_line_header(), free_linear_expandable(), free_linetab(), free_macro_definition_ptr(), free_memory_read_result_vector(), free_objfile(), free_objfile_data(), free_one_bfd_section(), free_pieced_value_closure(), free_pipe_state(), free_private_thread_info(), free_pv_area(), free_search_symbols(), free_section_addr_info(), free_so(), free_stringtab(), free_symfile_segment_data(), free_target_description(), free_thread(), free_traceframe_info(), free_typedef_hash(), free_uploaded_tps(), free_uploaded_tsvs(), free_variable(), frv_clear_solib(), frv_current_sos(), frv_free_so(), frv_relocate_main_executable(), func_command(), function_destroyer(), gcore_command(), gcore_copy_callback(), gdb_bfd_errmsg(), gdb_bfd_lookup_symbol_from_symtab(), gdb_bfd_open(), gdb_eval(), gdb_event_xfree(), gdb_readline(), gdb_readline2(), gdb_readline_wrapper_cleanup(), gdb_update_mem(), gdbarch_free(), gdbpy_parse_command_name(), gdbtk_init(), gdbtk_load_asm(), gdbtk_selected_frame_changed(), gdbtk_set_result(), generic_load(), get_core_register_section(), get_core_siginfo(), get_frame_name(), get_function_name(), get_inferior_args(), get_init_files(), get_osdata(), get_register(), get_register_types(), get_set_value(), get_show_value(), getpkt_or_notif_sane_1(), gnuv3_get_type_from_type_info(), gnuv3_get_typeid(), gnuv3_print_method_ptr(), gnuv3_print_vtable(), go32_create_inferior(), go_demangle(), go_symbol_package_name(), guess_full_die_structure_name(), guess_partial_die_structure_name(), h8300_push_dummy_call(), handle_gnu_v3_exceptions(), handle_inferior_event(), handle_output_debug_string(), handle_timer_event(), hardwire_get_tty_state(), hash_expand(), hwdebug_insert_point(), hwdebug_remove_point(), i386_forget_process(), i386_gdbarch_init(), ia64_hpux_clear_solib(), ia64_hpux_free_so(), inferior_has_bug(), inflow_inferior_data_cleanup(), inflow_inferior_exit(), info_auto_load_libthread_db(), info_mach_tasks_command(), info_probes_for_ops(), infpy_read_memory(), infrun_thread_stop_requested(), inherit_abstract_dies(), init_loaded_scripts_info(), init_psymbol_list(), insert_bp_location(), inspect_type(), install_new_value(), interp_set(), invoke_async_event_handler(), irix_current_sos(), irix_free_so(), irix_open_symbol_file_object(), is_known_support_routine(), iterate_over_symtabs(), java_class_name_from_physname(), java_type_print_base(), jit_dealloc_cache(), jit_object_close_impl(), jit_program_space_data_cleanup(), jit_reader_load_command(), jit_reader_try_read_symtab(), jit_reader_unload_command(), jump_command(), jv_per_objfile_free(), libunwind_load(), line_info(), linespec_parse_basic(), linespec_parser_delete(), linespec_state_constructor(), linux_child_pid_to_exec_file(), linux_collect_thread_registers(), linux_common_core_of_thread(), linux_core_info_proc_mappings(), linux_corefile_thread_callback(), linux_fill_prpsinfo(), linux_find_memory_regions_full(), linux_get_siginfo_data(), linux_grandchild_function(), linux_info_proc(), linux_make_corefile_notes(), linux_nat_attach(), linux_nat_wait(), linux_spu_make_corefile_notes(), linux_xfer_osdata_fds(), linux_xfer_osdata_processes(), linux_xfer_osdata_processgroups(), linux_xfer_osdata_threads(), list_args_or_locals(), list_command(), lm_info_read(), load_command(), load_progress(), local_setattro(), lookup_minimal_symbol_internal(), lookup_partial_symbol(), lookup_struct_elt_type(), lookup_symbol_file(), lookup_symbol_from_bfd(), lval_func_free_closure(), lwp_free(), m32c_m16c_address_to_pointer(), macho_symfile_read(), macho_symfile_read_all_oso(), macro_bcache_free(), macro_free(), macro_include(), macro_lookup_definition(), macro_start_file(), macro_undef(), macro_undef_command(), maintenance_demangle(), maintenance_do_deprecate(), maintenance_print_msymbols(), maintenance_print_psymbols(), maintenance_print_symbols(), make_cleanup_close(), make_cleanup_discard_psymtabs(), make_cleanup_restore_integer(), make_cleanup_restore_ui_file(), make_command_stats_cleanup(), make_symbol_overload_list(), mangled_name_to_comp(), maybe_expand(), mbpy_dealloc(), mem_bfd_iovec_close(), mem_file_delete(), memory_error(), memory_xfer_partial(), method_name_from_physname(), mi_cmd_break_insert_1(), mi_cmd_data_read_memory(), mi_cmd_data_read_memory_bytes(), mi_cmd_data_write_memory(), mi_cmd_data_write_memory_bytes(), mi_cmd_disassemble(), mi_cmd_env_dir(), mi_cmd_env_path(), mi_cmd_interpreter_exec(), mi_cmd_thread_list_ids(), mi_cmd_thread_select(), mi_cmd_trace_find(), mi_cmd_trace_frame_collected(), mi_cmd_var_assign(), mi_cmd_var_create(), mi_cmd_var_evaluate_expression(), mi_cmd_var_list_children(), mi_cmd_var_set_format(), mi_console_file_delete(), mi_execute_async_cli_command(), mi_execute_cli_command(), mi_execute_command(), mi_load_progress(), mi_parse_free(), mips_error(), mips_linux_close(), mips_linux_remove_watchpoint(), monitor_close(), monitor_load(), monitor_open(), mt_push_dummy_call(), n_spaces(), nbsd_pid_to_exec_file(), net_windows_close(), notif_event_xfree(), objc_demangle(), objfile_relocate(), objfiles_pspace_data_cleanup(), obstack_xml_printf(), old_renaming_is_invisible(), open_and_init_dwp_file(), open_dwo_file(), open_symbol_file_object(), openp(), operator_stoken(), osdata_free(), osdata_item_clear(), osf_free_so(), output_cores(), overload_list_add_symbol(), parmpy_init(), parse_exp_in_context_1(), parse_expression_for_completion(), parse_float(), parse_frame_specification_1(), parse_linespec(), parse_macro_definition(), parse_number(), parse_partial_symbols(), parse_probes(), parse_scrolling_args(), parse_trace_status(), pascal_object_print_value(), pascal_val_print(), patch_type(), path_command(), pdc_dealloc(), perror_warning_with_name(), pipe_close(), pmon_end_download(), pop_current_type(), pop_dummy_frame(), pop_level(), pop_stack_item(), pop_subfile(), ppc_linux_get_syscall_number(), ppc_linux_thread_exit(), print_bcache_statistics(), print_converted_chars_to_obstack(), print_decimal_chars(), print_doc_line(), print_frame(), print_frame_args(), print_mention_exception(), print_name_maybe_canonical(), print_one_breakpoint_location(), print_one_catch_solib(), print_one_catch_syscall(), print_one_exception(), print_subexp_standard(), print_target_wait_results(), print_thread_info(), print_varobj(), proc_set_traced_sysentry(), proc_set_traced_sysexit(), process_enumeration_scope(), process_linenos(), process_next_line(), process_queue(), procfs_create_inferior(), procfs_debug_inferior(), procfs_meminfo(), procfs_open(), procfs_xfer_auxv(), prompt_for_continue(), psymbol_bcache_free(), psymtab_include_file_name(), psymtab_to_fullname(), psymtab_to_symtab_1(), pull_pid_from_list(), putpkt_binary(), pv_area_store(), py_free_inferior(), py_print_frame(), quit_confirm(), re_set_exception_catchpoint(), read_alphacoff_dynamic_symtab(), read_baseclasses(), read_dbx_dynamic_symtab(), read_dbx_symtab(), read_frame(), read_map(), read_member_functions(), read_pe_exported_syms(), read_program_header(), read_program_headers_from_bfd(), read_struct_fields(), read_type(), read_whatever_is_readable(), realloc_body_list(), really_free_pendings(), record_full_close(), record_full_core_open_1(), record_full_core_xfer_partial(), record_full_end_release(), record_full_mem_release(), record_full_reg_release(), record_full_save_cleanups(), reg_value_free_impl(), regcache_dump(), regcache_xfree(), register_remote_support_xml(), register_solib_event_probe(), registers_changed_ptid(), registry_container_free_data(), release_program_space(), release_static_tracepoint_marker(), reload_shared_libraries_1(), relocate_gdb_directory(), remote_bfd_iovec_close(), remote_disable_btrace(), remote_file_get(), remote_file_put(), remote_fileio_func_read(), remote_fileio_func_write(), remote_fileio_reset(), remote_notif_state_xfree(), remote_open_1(), remote_pass_signals(), remote_program_signals(), remote_read_qxfer(), remote_register_number_and_offset(), remote_teardown_btrace(), remote_threads_info(), remote_traceframe_info(), remove_displaced_stepping_state(), remove_dummy_frame(), reopen_exec_file(), replace_operator_with_call(), replace_typedefs(), replace_typedefs_qualified_name(), reread_symbols(), resize_section_table(), restore_binary_file(), restore_current_thread_cleanup_dtor(), restore_current_traceframe_cleanup_dtor(), restore_infcall_control_state(), restore_inferior_ptid(), restore_section_callback(), return_command(), rs6000_aix_core_xfer_shared_libraries_aix(), rs6000_aix_shared_library_to_xml(), rs6000_xfer_shared_libraries(), s390_remove_watchpoint(), salpy_dealloc(), salpy_str(), save_breakpoints(), save_infcall_suspend_state(), scan_dyntag_auxv(), scan_expression_with_cleanup(), scan_filename_with_cleanup(), scan_macro_expansion(), scan_xcoff_symtab(), score7_free_memblock(), sdata_make_value(), search_struct_method(), search_symbols(), select_source_symtab(), ser_console_close(), ser_windows_close(), serial_open(), serial_printf(), serial_unref(), set_auto_load_dir(), set_auto_load_safe_path(), set_breakpoint_condition(), set_cp_abi_as_auto_default(), set_directories_command(), set_environment_command(), set_ext_lang_command(), set_gnutarget(), set_in_environ(), set_inferior_args(), set_inferior_io_terminal(), set_last_source_file(), set_libthread_db_search_path(), set_logging_off(), set_logging_on(), set_main_name(), set_parameter_value(), set_prompt(), set_tdesc_filename_cmd(), setup_architecture_data(), show_pp_source_pos(), sim_inferior_data_cleanup(), simple_displaced_step_free_closure(), simple_free_overlay_table(), skip_delete_command(), solib_aix_bfd_open(), solib_aix_solib_create_inferior_hook(), solib_aix_xfree_lm_info(), solib_bfd_fopen(), solib_find(), solib_map_sections(), solib_target_current_sos(), solib_target_free_so(), som_current_sos(), som_free_so(), som_open_symbol_file_object(), som_symtab_read(), sort_search_symbols_remove_dups(), source_script_with_search(), source_verbose_cleanup(), spu_bfd_iovec_close(), spu_bfd_open(), spu_get_overlay_table(), stap_probe_destroy(), start_subfile(), startup_inferior(), stdio_file_delete(), step_once(), stpy_dealloc(), strace_marker_create_breakpoints_sal(), stringify_collection_list(), svr4_clear_solib(), svr4_exec_displacement(), svr4_free_so(), svr4_keep_data_in_core(), svr4_pspace_data_cleanup(), svr4_read_so_list(), sym_info(), symbol_file_add_from_memory(), symbol_set_names(), symfile_bfd_open(), symfile_debug_free_objfile(), syms_from_objfile_1(), symtab_to_fullname(), sync_threadlists(), target_bfd_xclose(), target_desc_info_free(), target_fileio_read_alloc_1(), target_read_alloc_1(), target_read_description_xml(), target_wait(), tdesc_data_cleanup(), tdesc_free_feature(), tdesc_free_reg(), tdesc_free_type(), tdesc_use_registers(), tee_file_delete(), terminal_init_inferior_with_pgrp(), terminal_ours_1(), terminal_save_ours(), tfile_close(), tfile_dtor(), tfile_open(), tfile_write_uploaded_tsv(), thpy_set_name(), thread_apply_all_command(), thread_apply_command(), thread_db_load_search(), thread_name_command(), throw_perror_with_name(), tilegx_push_dummy_call(), tk_command(), top_level_prompt(), trace_actions_command(), trace_file_writer_xfree(), trace_find_line_command(), trace_variable_command(), try_open_dwop_file(), try_thread_db_load_from_dir(), try_thread_db_load_from_pdir_1(), tui_alloc_content(), tui_alloc_source_buffer(), tui_del_window(), tui_disassemble(), tui_file_delete(), tui_find_disassembly_address(), tui_free_window(), tui_get_register(), tui_prep_terminal(), tui_set_disassem_content(), tui_set_focus(), tui_set_layout_for_display_command(), tui_set_source_content(), tui_set_win_height(), tui_show_locator_content(), tui_show_register_group(), tvariables_info_1(), type_stack_cleanup(), typy_lookup_type(), typy_str(), ui_file_delete(), ui_out_destroy(), ui_out_field_stream(), unexpected_linespec_error(), uninstall_symfile_debug_logging(), uninstall_variable(), unset_exec_wrapper_command(), unset_in_environ(), unset_tdesc_filename_cmd(), until_break_command(), until_next_command(), update_dynamic_varobj_children(), update_global_location_list(), update_section_map(), update_static_tracepoint(), update_watchpoint(), val_print_string(), value_concat(), value_free(), value_get_print_value(), value_of_root(), variable_create(), variable_delete(), variable_obj_command(), variable_type(), variable_value(), varobj_set_display_format(), varobj_set_value(), varobj_update_one(), VEC(), verify_gdbarch(), vfprintf_maybe_filtered(), vfprintf_unfiltered(), view_command(), watch_command_1(), watch_main_source_file_lossage(), windows_delete_thread(), windows_free_so(), windows_init_thread_list(), windows_xfer_shared_library(), write_psymtabs_to_index(), xcoff_free_info(), xcoff_symfile_finish(), xdb_handle_command(), xfree_observer_list_node(), xml_fetch_content_from_file(), xstormy16_push_dummy_call(), xtensa_register_type(), xtensa_verify_config(), yyfree(), and yylex().
char char int xsnprintf (char * str, size_t size, const char * format, ...)
char* xstrprintf (const char * format, ...)
char char* xstrvprintf (const char * format, va_list ap)
void void* xzalloc (size_t)
Definition at line 99 of file common-utils.c.
References xcalloc().
Referenced by addr_info_make_relative(), allocate_objfile(), allocate_value_contents(), allocate_value_lazy(), cache_new_ref1(), dwarf2_add_typedef(), hwdebug_find_thread_points_by_tid(), ia64_gdbarch_init(), lm_info_read(), m68k_gdbarch_init(), new_block(), new_bvect(), parse_partial_symbols(), push_parse_stack(), read_pe_exported_syms(), remote_enable_btrace(), remote_notif_state_allocate(), replace_operator_with_call(), solib_target_relocate_section_addresses(), svr4_default_sos(), and VEC().