GDB (xrefs): /home/stan/gdb/src/gdb/common/common-utils.c File Reference
/home/stan/gdb/src/gdb/common/common-utils.c File Reference
#include "defs.h"
#include "gdb_assert.h"
#include "gdb_string.h"
#include <stdlib.h>
#include <stdio.h>
Functions
PTR xmalloc (size_t size)
PTR xrealloc (PTR ptr, size_t size)
PTR xcalloc (size_t number, size_t size)
void * xzalloc (size_t size)
void xfree (void *ptr)
char * xstrprintf (const char *format,...)
char * xstrvprintf (const char *format, va_list ap)
int xsnprintf (char *str, size_t size, const char *format,...)
char * savestring (const char *ptr, size_t len)
Function Documentation
char* savestring (const char * ptr, size_t len)
Make a copy of a string, using freshly-allocated space and limiting to the given length. Space is gotten using xmalloc.
Parameters:
ptr pointer to the string to be copied
len maximum length to copy. If the original string is longer, then the copy will be truncated to len bytes.
Definition at line 156 of file common-utils.c.
References len, memcpy(), p, and xmalloc().
Referenced by add_path(), break_range_command(), cd_command(), copy_token_string(), decode_static_tracepoint_spec(), extract_exception_regexp(), find_condition_and_thread(), gnuv3_get_typename_from_type_info(), init_breakpoint_sal(), lookup_symbol_file(), parse_frame_specification_1(), parse_probes(), process_next_line(), read_member_functions(), read_one_struct_field(), scan_expression_with_cleanup(), scan_filename_with_cleanup(), set_environment_command(), solib_find(), strace_marker_create_sals_from_address(), stringify_collection_list(), trace_variable_command(), and watch_command_1().
PTR xcalloc (size_t number, size_t size)
Definition at line 79 of file common-utils.c.
References malloc_failure().
Referenced by _initialize_ada_language(), _initialize_demangler(), _initialize_gdb_bfd(), _initialize_tailcall_frame(), aarch64_add_process(), aarch64_gdbarch_init(), add_displaced_stepping_state(), add_thread_db_info(), ambiguous_names_p(), arm_gdbarch_init(), compute_symtab_includes(), create_demangled_names_hash(), create_filename_seen_cache(), create_quick_file_names_table(), create_strtab(), create_symbol_hash_table(), create_typedef_hash(), dict_create_hashed_expandable(), dsbt_current_sos(), dsbt_relocate_main_executable(), dw2_expand_symtabs_matching(), dw2_map_symbol_filenames(), dwarf_decode_macros(), expand_hashtable(), fbsd_pid_to_exec_file(), frv_current_sos(), frv_relocate_main_executable(), gdb_bfd_open(), gnuv3_print_vtable(), i386_add_process(), init_collection_list(), linespec_state_constructor(), linux_xfer_osdata_processes(), load_section_callback(), m32c_gdbarch_init(), mi_cmd_data_read_memory(), nbsd_pid_to_exec_file(), new_dwarf_expr_context(), new_thread(), nios2_gdbarch_init(), nto_parse_redirection(), record_full_end_alloc(), record_full_mem_alloc(), record_full_reg_alloc(), register_solib_event_probe(), remote_register_number_and_offset(), save_bookmark_command(), score_gdbarch_init(), setup_architecture_data(), tic6x_gdbarch_init(), VEC(), write_psymtabs_to_index(), and xzalloc().
void xfree (void * ptr)
Definition at line 105 of file common-utils.c.
References free().
Referenced by _initialize_ada_language(), _initialize_gdb_bfd(), _initialize_tailcall_frame(), _initialize_tui_interp(), _proc_free(), aarch64_forget_process(), abbrev_table_free(), abbrev_table_read_table(), ada_catchpoint_location_dtor(), ada_inferior_data_cleanup(), ada_main_name(), ada_unhandled_exception_name_addr_from_raise(), ada_varobj_describe_simple_array_child(), ada_varobj_get_value_of_array_variable(), add_angle_brackets(), add_auto_load_safe_path(), add_inferior_command(), add_internal_problem_command(), add_language(), add_msglist(), add_packet_config_cmd(), add_partial_symbol(), add_path(), add_pe_exported_sym(), add_pe_forwarded_sym(), add_solib_catchpoint(), add_symbol_file_command(), addr_info_make_relative(), aix_thread_extra_thread_info(), aix_thread_pid_to_str(), alias_command(), all_tracepoint_actions_and_cleanup(), allocate_psymtab(), allocate_symtab(), ambiguous_names_p(), apropos_command(), archpy_disassemble(), arg_cleanup(), arm_adjust_breakpoint_address(), arm_exidx_new_objfile(), arm_linux_thread_exit(), arrange_linetable(), attach_command_continuation_free_args(), ATTRIBUTE_PRINTF(), auto_load_objfile_script(), auto_load_objfile_script_1(), auto_load_pspace_data_cleanup(), auto_load_safe_path_vec_update(), auxv_inferior_data_cleanup(), avr_io_reg_read_command(), backtrace_command(), base_breakpoint_dtor(), bcache_xfree(), bfd_lookup_symbol_from_dyn_symtab(), bfd_uses_spe_extensions(), bp_location_dtor(), bppy_get_commands(), bppy_init(), bppy_set_condition(), bpstat_check_watchpoint(), bpstat_free(), break_range_command(), breakpoint_notify(), breakpoint_re_set(), breakpoint_re_set_default(), bsd_kvm_open(), buffer_free(), buffer_xml_printf(), build_error_marker_type(), build_section_table(), build_type_unit_groups(), c_get_string(), c_type_print_base(), cache_unref(), call_function_by_hand(), cancel_single_step_breakpoints(), captured_main(), catch_ada_exception_command_split(), catch_exception_command_1(), catch_syscall_inferior_data_cleanup(), catcher_pop(), cd_command(), chain_candidate(), check_fast_tracepoint_sals(), check_for_redefinition(), check_status_exception_catchpoint(), check_stub_method(), classify_name(), cleanup_mapped_symtab(), cleanup_request_data(), clear_collection_list(), clear_command(), clear_dangling_display_expressions(), clear_entries(), clear_header_list(), clear_internalvar(), clear_memory_write_data(), clear_so(), clear_table(), cmdpy_destroyer(), cmdpy_function(), cmdpy_init(), coff_free_info(), coff_locate_sections(), coff_symfile_read(), coff_symtab_read(), command_from_pid(), command_line_handler(), command_line_input(), commandline_from_pid(), commands_command_1(), compare_sections_command(), compile_rx_or_error(), complete_command(), compute_enum_values(), compute_symtab_includes(), copy_terminal_info(), core_close(), core_open(), core_process_module_section(), cp_canonicalize_string(), cp_canonicalize_string_full(), cp_class_name_from_physname(), cp_demangled_name_parse_free(), cp_lookup_symbol_imports_or_template(), cp_print_value(), cppop(), create_all_comp_units(), create_breakpoint(), create_breakpoint_sal(), create_breakpoints_sal(), create_demangled_names_hash(), create_dwo_unit_in_dwp_v1(), create_dwo_unit_in_dwp_v2(), create_excep_cond_exprs(), create_filename_seen_cache(), create_quick_file_names_table(), create_sals_line_offset(), create_strtab(), create_symbol_hash_table(), create_tsv_from_upload(), create_type_unit_group(), create_typedef_hash(), ctf_start(), darwin_current_sos(), darwin_mourn_inferior(), darwin_pid_to_exec_file(), darwin_pspace_data_cleanup(), dbx_free_symfile_info(), dcache_free(), deallocate_reg_mem(), dec_thread_pid_to_str(), decimal_from_floating(), decode_line_2(), decode_line_full(), decode_loadmap(), decode_static_tracepoint_spec(), decref_counted_command_line(), default_xfer_partial(), define_symbol(), del_objfile_sal(), delete_all_bookmarks(), delete_async_event_handler(), delete_async_signal_handler(), delete_breakpoint(), delete_cmd(), delete_file_handler(), delete_file_name_entry(), delete_filename_seen_cache(), delete_one_bookmark(), delete_substitute_path_rule(), delete_symtab_entry(), delete_thread_db_info(), delete_thread_object(), delete_timer(), delete_trace_state_variable(), demangle_for_lookup(), deprecated_insert_raw_breakpoint(), deprecated_remove_raw_breakpoint(), destroy_linespec_result(), destroy_one_procinfo(), dicos_load_module_p(), directory_command(), discard_infcall_control_state(), discard_infcall_suspend_state(), discard_my_cleanups(), discard_my_continuations_1(), displaced_step_fixup(), do_cleanup_end(), do_cleanup_iterator(), do_discard_minimal_symbols_cleanup(), do_map_commands_command(), do_my_cleanups(), do_my_continuations_1(), do_one_display(), do_serial_close(), do_set_command(), do_show_command(), document_command(), dsbt_clear_solib(), dsbt_current_sos(), dsbt_free_so(), dsbt_pspace_data_cleanup(), dsbt_relocate_main_executable(), dtor_catch_exec(), dtor_catch_solib(), dtor_exception(), dtor_exception_catchpoint(), dtor_watchpoint(), dump_insns(), dump_memory_to_file(), dw2_expand_symtabs_matching(), dw2_free_cached_file_names(), dw2_map_symbol_filenames(), dwarf2_add_field(), dwarf2_add_member_fn(), dwarf2_add_typedef(), dwarf2_build_frame_info(), dwarf2_canonicalize_name(), dwarf2_compile_expr_to_ax(), dwarf2_compute_name(), dwarf2_frame_state_free(), dwarf2_frame_state_free_regs(), dwarf2_get_dwz_file(), dwarf2_name(), dwarf2_per_objfile_free(), dwarf2_physname(), dwarf2_release_queue(), dwarf2_start_subfile(), dwarf2_tailcall_sniffer_first(), dwarf_decode_macros(), edit_command(), elf_symfile_read(), enable_break(), enable_break2(), end_arglist(), end_msglist(), end_stabs(), end_symtab_from_static_block(), end_symtab_get_static_block(), enumerate_args(), enumerate_locals(), env_execute_cli_command(), error_stream(), eval_command(), evaluate_subexp_standard(), exec_close(), exec_file_attach(), exec_file_command(), exec_reverse_once(), execute_cfa_program(), expand_hash_table(), expand_hashtable(), extend_buffer_earlier(), fbsd_find_memory_regions(), fbsd_make_corefile_notes(), fbsd_pid_to_exec_file(), fetch_loadmap(), file_is_auto_load_safe(), file_read_description_xml(), filter_results(), filter_sals(), finalize_symtab(), find_and_open_script(), find_and_open_source(), find_condition_and_thread(), find_file_and_directory(), find_frame_funname(), find_global_typedef(), find_linespec_symbols(), find_oload_champ(), find_oload_champ_namespace_loop(), find_overload_match(), find_separate_debug_file(), find_separate_debug_file_by_debuglink(), find_slot_in_mapped_hash(), find_source_lines(), finish_command_continuation_free_arg(), finish_global_stabs(), fixup_definition(), fixup_go_packaging(), fixup_partial_die(), fnpy_call(), foreach_macro(), foreach_macro_in_scope(), forget_cached_source_info_for_objfile(), forget_cached_source_info_partial(), fprintf_symbol_filtered(), frame_info(), frapy_name(), frapy_read_var(), frapy_str(), free_actions_list(), free_address_space(), free_agent_expr(), free_bincl_list(), free_block(), free_bp_location(), free_buffer(), free_char_ptr_vec(), free_clbk(), free_command_lines(), free_completion_list(), free_content(), free_content_elements(), free_current_contents(), free_current_marker(), free_display(), free_dwarf_expr_context(), free_elfinfo(), free_environ(), free_fork(), free_format_pieces(), free_funcalls(), free_hashed_expandable(), free_header_files(), free_heap_comp_unit(), free_inferior(), free_line_header(), free_linear_expandable(), free_linetab(), free_macro_definition_ptr(), free_memory_read_result_vector(), free_objfile(), free_objfile_data(), free_one_bfd_section(), free_pieced_value_closure(), free_pipe_state(), free_private_thread_info(), free_pv_area(), free_search_symbols(), free_section_addr_info(), free_so(), free_stringtab(), free_symfile_segment_data(), free_target_description(), free_thread(), free_traceframe_info(), free_typedef_hash(), free_uploaded_tps(), free_uploaded_tsvs(), free_variable(), frv_clear_solib(), frv_current_sos(), frv_free_so(), frv_relocate_main_executable(), func_command(), function_destroyer(), gcore_command(), gcore_copy_callback(), gdb_bfd_errmsg(), gdb_bfd_lookup_symbol_from_symtab(), gdb_bfd_open(), gdb_eval(), gdb_event_xfree(), gdb_readline(), gdb_readline2(), gdb_readline_wrapper_cleanup(), gdb_update_mem(), gdbarch_free(), gdbpy_parse_command_name(), gdbtk_init(), gdbtk_load_asm(), gdbtk_selected_frame_changed(), gdbtk_set_result(), generic_load(), get_core_register_section(), get_core_siginfo(), get_frame_name(), get_function_name(), get_inferior_args(), get_init_files(), get_osdata(), get_register(), get_register_types(), get_set_value(), get_show_value(), getpkt_or_notif_sane_1(), gnuv3_get_type_from_type_info(), gnuv3_get_typeid(), gnuv3_print_method_ptr(), gnuv3_print_vtable(), go32_create_inferior(), go_demangle(), go_symbol_package_name(), guess_full_die_structure_name(), guess_partial_die_structure_name(), h8300_push_dummy_call(), handle_gnu_v3_exceptions(), handle_inferior_event(), handle_output_debug_string(), handle_timer_event(), hardwire_get_tty_state(), hash_expand(), hwdebug_insert_point(), hwdebug_remove_point(), i386_forget_process(), i386_gdbarch_init(), ia64_hpux_clear_solib(), ia64_hpux_free_so(), inferior_has_bug(), inflow_inferior_data_cleanup(), inflow_inferior_exit(), info_auto_load_libthread_db(), info_mach_tasks_command(), info_probes_for_ops(), infpy_read_memory(), infrun_thread_stop_requested(), inherit_abstract_dies(), init_loaded_scripts_info(), init_psymbol_list(), insert_bp_location(), inspect_type(), install_new_value(), interp_set(), invoke_async_event_handler(), irix_current_sos(), irix_free_so(), irix_open_symbol_file_object(), is_known_support_routine(), iterate_over_symtabs(), java_class_name_from_physname(), java_type_print_base(), jit_dealloc_cache(), jit_object_close_impl(), jit_program_space_data_cleanup(), jit_reader_load_command(), jit_reader_try_read_symtab(), jit_reader_unload_command(), jump_command(), jv_per_objfile_free(), libunwind_load(), line_info(), linespec_parse_basic(), linespec_parser_delete(), linespec_state_constructor(), linux_child_pid_to_exec_file(), linux_collect_thread_registers(), linux_common_core_of_thread(), linux_core_info_proc_mappings(), linux_corefile_thread_callback(), linux_fill_prpsinfo(), linux_find_memory_regions_full(), linux_get_siginfo_data(), linux_grandchild_function(), linux_info_proc(), linux_make_corefile_notes(), linux_nat_attach(), linux_nat_wait(), linux_spu_make_corefile_notes(), linux_xfer_osdata_fds(), linux_xfer_osdata_processes(), linux_xfer_osdata_processgroups(), linux_xfer_osdata_threads(), list_args_or_locals(), list_command(), lm_info_read(), load_command(), load_progress(), local_setattro(), lookup_minimal_symbol_internal(), lookup_partial_symbol(), lookup_struct_elt_type(), lookup_symbol_file(), lookup_symbol_from_bfd(), lval_func_free_closure(), lwp_free(), m32c_m16c_address_to_pointer(), macho_symfile_read(), macho_symfile_read_all_oso(), macro_bcache_free(), macro_free(), macro_include(), macro_lookup_definition(), macro_start_file(), macro_undef(), macro_undef_command(), maintenance_demangle(), maintenance_do_deprecate(), maintenance_print_msymbols(), maintenance_print_psymbols(), maintenance_print_symbols(), make_cleanup_close(), make_cleanup_discard_psymtabs(), make_cleanup_restore_integer(), make_cleanup_restore_ui_file(), make_command_stats_cleanup(), make_symbol_overload_list(), mangled_name_to_comp(), maybe_expand(), mbpy_dealloc(), mem_bfd_iovec_close(), mem_file_delete(), memory_error(), memory_xfer_partial(), method_name_from_physname(), mi_cmd_break_insert_1(), mi_cmd_data_read_memory(), mi_cmd_data_read_memory_bytes(), mi_cmd_data_write_memory(), mi_cmd_data_write_memory_bytes(), mi_cmd_disassemble(), mi_cmd_env_dir(), mi_cmd_env_path(), mi_cmd_interpreter_exec(), mi_cmd_thread_list_ids(), mi_cmd_thread_select(), mi_cmd_trace_find(), mi_cmd_trace_frame_collected(), mi_cmd_var_assign(), mi_cmd_var_create(), mi_cmd_var_evaluate_expression(), mi_cmd_var_list_children(), mi_cmd_var_set_format(), mi_console_file_delete(), mi_execute_async_cli_command(), mi_execute_cli_command(), mi_execute_command(), mi_load_progress(), mi_parse_free(), mips_error(), mips_linux_close(), mips_linux_remove_watchpoint(), monitor_close(), monitor_load(), monitor_open(), mt_push_dummy_call(), n_spaces(), nbsd_pid_to_exec_file(), net_windows_close(), notif_event_xfree(), objc_demangle(), objfile_relocate(), objfiles_pspace_data_cleanup(), obstack_xml_printf(), old_renaming_is_invisible(), open_and_init_dwp_file(), open_dwo_file(), open_symbol_file_object(), openp(), operator_stoken(), osdata_free(), osdata_item_clear(), osf_free_so(), output_cores(), overload_list_add_symbol(), parmpy_init(), parse_exp_in_context_1(), parse_expression_for_completion(), parse_float(), parse_frame_specification_1(), parse_linespec(), parse_macro_definition(), parse_number(), parse_partial_symbols(), parse_probes(), parse_scrolling_args(), parse_trace_status(), pascal_object_print_value(), pascal_val_print(), patch_type(), path_command(), pdc_dealloc(), perror_warning_with_name(), pipe_close(), pmon_end_download(), pop_current_type(), pop_dummy_frame(), pop_level(), pop_stack_item(), pop_subfile(), ppc_linux_get_syscall_number(), ppc_linux_thread_exit(), print_bcache_statistics(), print_converted_chars_to_obstack(), print_decimal_chars(), print_doc_line(), print_frame(), print_frame_args(), print_mention_exception(), print_name_maybe_canonical(), print_one_breakpoint_location(), print_one_catch_solib(), print_one_catch_syscall(), print_one_exception(), print_subexp_standard(), print_target_wait_results(), print_thread_info(), print_varobj(), proc_set_traced_sysentry(), proc_set_traced_sysexit(), process_enumeration_scope(), process_linenos(), process_next_line(), process_queue(), procfs_create_inferior(), procfs_debug_inferior(), procfs_meminfo(), procfs_open(), procfs_xfer_auxv(), prompt_for_continue(), psymbol_bcache_free(), psymtab_include_file_name(), psymtab_to_fullname(), psymtab_to_symtab_1(), pull_pid_from_list(), putpkt_binary(), pv_area_store(), py_free_inferior(), py_print_frame(), quit_confirm(), re_set_exception_catchpoint(), read_alphacoff_dynamic_symtab(), read_baseclasses(), read_dbx_dynamic_symtab(), read_dbx_symtab(), read_frame(), read_map(), read_member_functions(), read_pe_exported_syms(), read_program_header(), read_program_headers_from_bfd(), read_struct_fields(), read_type(), read_whatever_is_readable(), realloc_body_list(), really_free_pendings(), record_full_close(), record_full_core_open_1(), record_full_core_xfer_partial(), record_full_end_release(), record_full_mem_release(), record_full_reg_release(), record_full_save_cleanups(), reg_value_free_impl(), regcache_dump(), regcache_xfree(), register_remote_support_xml(), register_solib_event_probe(), registers_changed_ptid(), registry_container_free_data(), release_program_space(), release_static_tracepoint_marker(), reload_shared_libraries_1(), relocate_gdb_directory(), remote_bfd_iovec_close(), remote_disable_btrace(), remote_file_get(), remote_file_put(), remote_fileio_func_read(), remote_fileio_func_write(), remote_fileio_reset(), remote_notif_state_xfree(), remote_open_1(), remote_pass_signals(), remote_program_signals(), remote_read_qxfer(), remote_register_number_and_offset(), remote_teardown_btrace(), remote_threads_info(), remote_traceframe_info(), remove_displaced_stepping_state(), remove_dummy_frame(), reopen_exec_file(), replace_operator_with_call(), replace_typedefs(), replace_typedefs_qualified_name(), reread_symbols(), resize_section_table(), restore_binary_file(), restore_current_thread_cleanup_dtor(), restore_current_traceframe_cleanup_dtor(), restore_infcall_control_state(), restore_inferior_ptid(), restore_section_callback(), return_command(), rs6000_aix_core_xfer_shared_libraries_aix(), rs6000_aix_shared_library_to_xml(), rs6000_xfer_shared_libraries(), s390_remove_watchpoint(), salpy_dealloc(), salpy_str(), save_breakpoints(), save_infcall_suspend_state(), scan_dyntag_auxv(), scan_expression_with_cleanup(), scan_filename_with_cleanup(), scan_macro_expansion(), scan_xcoff_symtab(), score7_free_memblock(), sdata_make_value(), search_struct_method(), search_symbols(), select_source_symtab(), ser_console_close(), ser_windows_close(), serial_open(), serial_printf(), serial_unref(), set_auto_load_dir(), set_auto_load_safe_path(), set_breakpoint_condition(), set_cp_abi_as_auto_default(), set_directories_command(), set_environment_command(), set_ext_lang_command(), set_gnutarget(), set_in_environ(), set_inferior_args(), set_inferior_io_terminal(), set_last_source_file(), set_libthread_db_search_path(), set_logging_off(), set_logging_on(), set_main_name(), set_parameter_value(), set_prompt(), set_tdesc_filename_cmd(), setup_architecture_data(), show_pp_source_pos(), sim_inferior_data_cleanup(), simple_displaced_step_free_closure(), simple_free_overlay_table(), skip_delete_command(), solib_aix_bfd_open(), solib_aix_solib_create_inferior_hook(), solib_aix_xfree_lm_info(), solib_bfd_fopen(), solib_find(), solib_map_sections(), solib_target_current_sos(), solib_target_free_so(), som_current_sos(), som_free_so(), som_open_symbol_file_object(), som_symtab_read(), sort_search_symbols_remove_dups(), source_script_with_search(), source_verbose_cleanup(), spu_bfd_iovec_close(), spu_bfd_open(), spu_get_overlay_table(), stap_probe_destroy(), start_subfile(), startup_inferior(), stdio_file_delete(), step_once(), stpy_dealloc(), strace_marker_create_breakpoints_sal(), stringify_collection_list(), svr4_clear_solib(), svr4_exec_displacement(), svr4_free_so(), svr4_keep_data_in_core(), svr4_pspace_data_cleanup(), svr4_read_so_list(), sym_info(), symbol_file_add_from_memory(), symbol_set_names(), symfile_bfd_open(), symfile_debug_free_objfile(), syms_from_objfile_1(), symtab_to_fullname(), sync_threadlists(), target_bfd_xclose(), target_desc_info_free(), target_fileio_read_alloc_1(), target_read_alloc_1(), target_read_description_xml(), target_wait(), tdesc_data_cleanup(), tdesc_free_feature(), tdesc_free_reg(), tdesc_free_type(), tdesc_use_registers(), tee_file_delete(), terminal_init_inferior_with_pgrp(), terminal_ours_1(), terminal_save_ours(), tfile_close(), tfile_dtor(), tfile_open(), tfile_write_uploaded_tsv(), thpy_set_name(), thread_apply_all_command(), thread_apply_command(), thread_db_load_search(), thread_name_command(), throw_perror_with_name(), tilegx_push_dummy_call(), tk_command(), top_level_prompt(), trace_actions_command(), trace_file_writer_xfree(), trace_find_line_command(), trace_variable_command(), try_open_dwop_file(), try_thread_db_load_from_dir(), try_thread_db_load_from_pdir_1(), tui_alloc_content(), tui_alloc_source_buffer(), tui_del_window(), tui_disassemble(), tui_file_delete(), tui_find_disassembly_address(), tui_free_window(), tui_get_register(), tui_prep_terminal(), tui_set_disassem_content(), tui_set_focus(), tui_set_layout_for_display_command(), tui_set_source_content(), tui_set_win_height(), tui_show_locator_content(), tui_show_register_group(), tvariables_info_1(), type_stack_cleanup(), typy_lookup_type(), typy_str(), ui_file_delete(), ui_out_destroy(), ui_out_field_stream(), unexpected_linespec_error(), uninstall_symfile_debug_logging(), uninstall_variable(), unset_exec_wrapper_command(), unset_in_environ(), unset_tdesc_filename_cmd(), until_break_command(), until_next_command(), update_dynamic_varobj_children(), update_global_location_list(), update_section_map(), update_static_tracepoint(), update_watchpoint(), val_print_string(), value_concat(), value_free(), value_get_print_value(), value_of_root(), variable_create(), variable_delete(), variable_obj_command(), variable_type(), variable_value(), varobj_set_display_format(), varobj_set_value(), varobj_update_one(), VEC(), verify_gdbarch(), vfprintf_maybe_filtered(), vfprintf_unfiltered(), view_command(), watch_command_1(), watch_main_source_file_lossage(), windows_delete_thread(), windows_free_so(), windows_init_thread_list(), windows_xfer_shared_library(), write_psymtabs_to_index(), xcoff_free_info(), xcoff_symfile_finish(), xdb_handle_command(), xfree_observer_list_node(), xml_fetch_content_from_file(), xstormy16_push_dummy_call(), xtensa_register_type(), xtensa_verify_config(), yyfree(), and yylex().
PTR xmalloc (size_t size)
Definition at line 42 of file common-utils.c.
References malloc(), and malloc_failure().
Referenced by _initialize_arm_tdep(), abbrev_table_read_table(), ada_get_next_arg(), ada_name_for_lookup(), add_cmd(), add_file_name(), add_filename_to_list(), add_include_dir(), add_inferior_silent(), add_initial_lwp(), add_internal_problem_command(), add_language(), add_msglist(), add_new_header_file(), add_substitute_path_rule(), add_symbol_file_command(), add_symbol_to_list(), add_target_with_completer(), add_thread_object(), add_to_pid_list(), addrs_section_sort(), all_tracepoint_actions_and_cleanup(), alloc_counted_command_line(), alloc_section_addr_info(), allocate_include_entry(), allocate_info(), alpha_gdbarch_init(), amd64_displaced_step_copy_insn(), amd64_relocate_instruction(), arm_adjust_breakpoint_address(), arm_displaced_step_copy_insn(), arm_exidx_new_objfile(), arm_linux_displaced_step_copy_insn(), arrange_linetable(), attach_command(), attach_thread(), auto_load_objfile_script_1(), backtrace_command(), bfd_lookup_symbol_from_dyn_symtab(), bfd_open_from_target_memory(), bfd_uses_spe_extensions(), bpstat_alloc(), bpstat_copy(), build_command_line(), build_gdb_vtable_type(), build_section_table(), build_std_type_info_type(), build_table(), c_get_string(), c_type_print_base(), call_function_by_hand(), captured_main(), chain_candidate(), check_async_event_handlers(), clear_command(), cmdpy_init(), coff_locate_sections(), coff_symfile_read(), coff_symtab_read(), command_line_handler(), command_line_input(), commandline_from_pid(), compare_sections_command(), compute_enum_values(), construct_inferior_arguments(), copy_command_lines(), copy_exp(), copy_string(), copy_type_recursive(), core_process_module_section(), cp_new_demangle_parse_info(), cp_print_value(), cppush(), create_all_comp_units(), create_all_type_units(), create_async_event_handler(), create_async_signal_handler(), create_event(), create_file_handler(), create_internalvar(), create_procinfo(), create_signatured_type_table_from_index(), create_timer(), cris_gdbarch_init(), ctf_trace_file_writer_new(), d_grab(), darwin_pid_to_exec_file(), dbx_lookup_type(), dcache_alloc(), dcache_init(), decode_line_2(), decode_loadmap(), decode_static_tracepoint_spec(), default_xfer_partial(), delete_file_handler(), demand_private_info(), dicos_load_module_p(), dict_create_hashed_expandable(), dict_create_linear_expandable(), dirnames_to_char_ptr_vec_append(), displaced_step_prepare(), display_command(), do_set_command(), do_ui_file_xstrdup(), document_command(), dos_copy_tty_state(), dos_get_tty_state(), dump_memory_to_file(), dwarf2_add_field(), dwarf2_add_member_fn(), dwarf2_compile_expr_to_ax(), dwarf2_frame_state_copy_regs(), dwarf_decode_line_header(), elf_symfile_read(), elf_symtab_read(), end_symtab_get_static_block(), expand_hash_table(), extend_buffer_earlier(), extend_psymbol_list(), extract_arg(), extract_identifier(), fetch_loadmap(), find_canonical_descriptor_in_load_object(), find_linespec_symbols(), find_oload_champ(), find_program_interpreter(), find_separate_debug_file(), find_slot_in_mapped_hash(), find_source_lines(), finish_forward(), forward_search_command(), func_command(), gather_arguments(), gcore_copy_callback(), gdb_bfd_errmsg(), gdb_bfd_lookup_symbol_from_symtab(), gdb_listfiles(), gdb_mangle_name(), gdb_readline(), gdb_readline2(), gdb_readline_wrapper(), gdb_search(), gdb_update_mem(), gdbarch_register_osabi(), gdbarch_register_osabi_sniffer(), gdbpy_parse_command_name(), get_regcomp_error(), get_thread_arch_aspace_regcache(), get_uploaded_tp(), get_uploaded_tsv(), go32_create_inferior(), growbuf_by_size(), h8300_gdbarch_init(), h8300_push_dummy_call(), hardwire_copy_tty_state(), hardwire_get_tty_state(), hwdebug_find_thread_points_by_tid(), hwdebug_insert_point(), i386_displaced_step_copy_insn(), inf_child_fileio_readlink(), info_auto_load_libthread_db(), info_mach_tasks_command(), infpy_read_memory(), inherit_abstract_dies(), init_bincl_list(), init_buffer(), init_cutu_and_read_dies(), init_environ(), init_filename_language_table(), init_header_files(), init_lineno(), init_psymbol_list(), init_so(), init_stringtab(), init_tu_and_read_dwo_dies(), initialize_expout(), insert_args(), install_variable(), irix_current_sos(), java_class_name_from_physname(), java_demangle_type_signature(), jit_reader_try_read_symtab(), jit_symtab_line_mapping_add_impl(), jit_unwind_reg_get_impl(), ldirname(), line_info(), linux_child_pid_to_exec_file(), linux_collect_thread_registers(), linux_core_info_proc_mappings(), linux_fork_to_function(), linux_get_siginfo_data(), linux_xfer_osdata_processgroups(), lm_info_read(), load_command(), load_progress(), load_section_callback(), lookup_symbol_from_bfd(), m32c_m16c_address_to_pointer(), m32c_m16c_pointer_to_address(), m68hc11_gdbarch_init(), macho_add_oso_symfile(), macho_symfile_read(), macro_alloc(), macro_bcache(), macro_define_command(), make_cleanup_close(), make_cleanup_restore_current_thread(), make_cleanup_restore_current_traceframe(), make_cleanup_restore_integer(), make_command(), make_environ(), make_inf(), make_my_cleanup2(), make_proc(), make_pv_area(), make_symbol_overload_list(), malloc_clbk(), mark_completion_tag(), maybe_add_script(), maybe_expand(), mem_file_write(), memory_xfer_partial(), mep_gdbarch_init(), mi_cmd_data_read_memory_bytes(), mi_cmd_data_write_memory(), mi_cmd_data_write_memory_bytes(), mi_cmd_trace_frame_collected(), mi_execute_command(), mi_parse(), mi_parse_argv(), mips_gdbarch_init(), mips_linux_insert_watchpoint(), mn10300_gdbarch_init(), monitor_open(), msp430_gdbarch_init(), mt_push_dummy_call(), mt_register_name(), n_spaces(), net_windows_open(), new_agent_expr(), new_dwarf_expr_context(), new_linetable(), new_macro_table(), new_remote_state(), new_root_variable(), new_variable(), new_variant(), notice_new_inferior(), objc_demangle(), objfile_relocate(), open_symbol_file_object(), operator_stoken(), osf_current_sos(), parse_breakpoint_sals(), parse_find_args(), parse_float(), parse_format_string(), parse_macro_definition(), parse_partial_symbols(), parse_static_tracepoint_marker_definition(), parse_trace_status(), parse_tracepoint_definition(), pascal_object_print_value(), pascal_val_print(), pdc_alloc(), perror_string(), pmon_end_download(), poll_timers(), ppc_linux_get_syscall_number(), print_decimal_chars(), print_doc_line(), proc_set_traced_sysentry(), proc_set_traced_sysexit(), process_linenos(), process_next_line(), procfs_create_inferior(), procfs_meminfo(), psymtab_to_symtab_1(), push_current_type(), push_stack_item(), push_subfile(), pv_area_store(), queue_comp_unit(), rank_function(), read_alphacoff_dynamic_symtab(), read_args(), read_baseclasses(), read_dbx_dynamic_symtab(), read_dbx_symtab(), read_member_functions(), read_pe_exported_syms(), read_program_header(), read_program_headers_from_bfd(), read_string(), read_struct_fields(), read_whatever_is_readable(), realloc_body_list(), record_full_core_open_1(), record_full_core_xfer_partial(), record_full_mem_alloc(), record_full_reg_alloc(), record_latest_value(), record_line(), remote_bfd_iovec_open(), remote_file_get(), remote_file_put(), remote_fileio_func_read(), remote_fileio_func_write(), remote_fileio_init_fd_map(), remote_hostio_readlink(), remote_pass_signals(), remote_program_signals(), restart_symtab(), restore_binary_file(), restore_section_callback(), rewrite_source_path(), rl78_gdbarch_init(), rs6000_aix_core_xfer_shared_libraries_aix(), rs6000_ptrace_ldinfo(), rx_gdbarch_init(), s390_insert_watchpoint(), sal_macro_scope(), save_infcall_control_state(), save_infcall_suspend_state(), save_inferior_ptid(), savestring(), scan_xcoff_symtab(), score7_malloc_and_get_memblock(), search_struct_method(), search_symbols(), ser_console_get_tty_state(), ser_console_wait_handle(), ser_windows_open(), set_in_environ(), set_width(), setup_user_args(), simple_displaced_step_copy_insn(), simple_read_overlay_table(), solib_aix_new_lm_info(), som_current_sos(), som_symtab_read(), sort_search_symbols_remove_dups(), source_command(), specify_exec_file_hook(), spu_bfd_fopen(), spu_bfd_open(), spu_get_overlay_table(), start_arglist(), start_msglist(), start_subfile(), stdio_file_new(), step_once(), stringify_collection_list(), svr4_copy_library_list(), symbol_completion_add(), sync_threadlists(), sysset_t_alloc(), target_fileio_read_alloc_1(), target_read_alloc_1(), target_read_string(), target_write_memory_blocks(), tee_file_new(), tfile_trace_file_writer_new(), tfile_write_uploaded_tsv(), thread_apply_all_command(), thread_db_load_search(), tilegx_push_dummy_call(), top_level_prompt(), trace_find_line_command(), tracepoint_exists(), try_thread_db_load_from_dir(), try_thread_db_load_from_pdir_1(), tui_alloc_content(), tui_alloc_source_buffer(), tui_file_adjust_strbuf(), tui_make_status_line(), tui_set_source_content(), tui_sfileopen(), typename_concat(), ui_file_new(), ui_printf(), until_break_command(), update_dec_thread_list(), update_dprintf_command_list(), update_global_location_list(), update_section_map(), update_thread_private_data_name(), uptok(), v850_gdbarch_init(), value_concat(), varobj_delete(), VEC(), windows_make_so(), write_object_renaming(), write_psymtabs_to_index(), xdb_handle_command(), xget_renaming_scope(), xml_escape_text(), xml_fetch_content_from_file(), xstormy16_push_dummy_call(), xtensa_register_type(), and yyalloc().
PTR xrealloc (PTR ptr, size_t size)
Definition at line 59 of file common-utils.c.
References malloc(), malloc_failure(), and realloc().
Referenced by abbrev_table_read_table(), add_aexpr(), add_bincl_to_list(), add_block(), add_cie(), add_fde(), add_file_name(), add_filename_language(), add_include_dir(), add_language(), add_memrange(), add_new_header_file(), add_piece(), add_sal_to_sals(), add_sal_to_sals_basic(), add_symbol_file_command(), add_symbol_linear_expandable(), add_target_with_completer(), add_this_object_header_file(), add_type_unit(), add_undefined_type_1(), add_undefined_type_noname(), allocate_include_entry(), append_composite_type_field_raw(), append_name(), arrange_linetable(), ATTRIBUTE_PRINTF(), ax_reg_mask(), buffer_grow(), captured_main(), coff_lookup_type(), command_line_handler(), command_line_input(), commandline_from_pid(), completion_list_objc_symbol(), copy_name(), create_file_handler(), dbx_lookup_type(), decoded_type_name(), do_listfiles(), do_set_command(), do_ui_file_xstrdup(), dwarf2_add_member_fn(), dwarf2_build_frame_info(), dwarf2_frame_state_alloc_regs(), dwarf_expr_grow_stack(), elf_rel_plt_read(), extend_psymbol_list(), find_methods(), find_source_lines(), find_symbol_in_baseclass(), fork_save_infrun_state(), forward_search_command(), gather_arguments(), gdb_listfiles(), gdb_readline(), gdb_readline2(), get_memory_packet_size(), grow_expr(), grow_vect(), growbuf_by_size(), init_environ(), init_remote_state(), initialize_current_architecture(), insert_exp(), linux_common_core_of_thread(), linux_xfer_osdata_processgroups(), macro_define_command(), mem_file_write(), mi_cmd_trace_frame_collected(), mi_parse_argv(), overload_list_add_symbol(), parse_find_args(), parse_macro_definition(), parse_partial_symbols(), parse_probes(), pdc_realloc(), process_enumeration_scope(), process_linenos(), push_context(), rbreak_command(), read_array_type(), read_comp_units_from_section(), read_frame(), read_pe_exported_syms(), read_pieced_value(), read_string(), reallocate_expout(), record_line(), ref_add(), remote_fileio_resize_fd_map(), remote_query_supported(), resize_buffer(), resize_section_table(), rs6000_ptrace_ldinfo(), set_in_environ(), set_value_enclosing_type(), set_width(), shrink_linetable(), specify_exec_file_hook(), substitute_path_component(), sync_threadlists(), target_fileio_read_alloc_1(), target_read_alloc_1(), target_read_string(), trace_dump_actions(), tui_file_adjust_strbuf(), type_stack_reserve(), ui_printf(), update_section_map(), update_thread_private_data_name(), VEC(), vec_o_reserve(), wchar_iterate(), write_exp_bitstring(), write_exp_elt(), write_exp_string(), write_exp_string_vector(), write_pieced_value(), xml_fetch_content_from_file(), yylex(), and yyxrealloc().
int xsnprintf (char * str, size_t size, const char * format, ...)
Definition at line 142 of file common-utils.c.
References gdb_assert.
Referenced by _initialize_check_for_gdb_ini(), ada_decode(), ada_enum_name(), ada_to_fixed_type_1(), add_pe_forwarded_sym(), append_ocl_sos(), append_resumption(), arm_dwarf_reg_to_regnum(), arm_neon_quad_read(), arm_neon_quad_write(), arm_pseudo_read(), arm_pseudo_write(), arm_push_dummy_call(), arm_return_value(), bpfinishpy_init(), bsd_kvm_pid_to_str(), bsd_uthread_pid_to_str(), cli_field_int(), cmd_record_save(), convert_between_encodings(), convert_char_literal(), core_pid_to_str(), core_xfer_partial(), cp_lookup_nested_symbol(), create_tracepoint_from_upload(), decimal2str(), define_command(), do_set_command(), document_command(), execute_control_command(), extended_remote_attach_1(), extended_remote_disable_randomization(), extended_remote_restart(), fetch_ppc_register(), fetch_register(), file_file_name(), find_old_style_renaming_symbol(), find_symbol_in_baseclass(), floatformat_mantissa(), gdb_connect_sync_socket(), gdb_mangle_name(), gnu_pid_to_str(), go32_sysinfo(), hex_string(), host_address_to_string(), info_auto_load_libthread_db(), info_spu_dma_command(), info_spu_event_command(), info_spu_mailbox_command(), info_spu_proxydma_command(), info_spu_signal_command(), init_source_path(), interp_set(), linux_fill_prpsinfo(), linux_find_memory_regions_full(), linux_info_proc(), linux_proc_pid_has_state(), linux_proc_xfer_spu(), linux_spu_make_corefile_notes(), m32r_open(), m32r_pid_to_str(), m68hc11_initialize_register_info(), make_types(), mi_argv_to_format(), mi_field_int(), monitor_pid_to_str(), normal_pid_to_str(), nto_find_and_open_solib(), nto_init_solib_absolute_prefix(), octal2str(), op_name_standard(), output_thread_groups(), phex(), phex_nz(), ppu2spu_sniffer(), print_source_lines_base(), print_wchar(), proc_string(), remote_add_target_side_condition(), remote_check_symbols(), remote_detach_1(), remote_disable_btrace(), remote_disable_tracepoint(), remote_download_trace_state_variable(), remote_download_tracepoint(), remote_enable_btrace(), remote_enable_tracepoint(), remote_get_min_fast_tracepoint_insn_len(), remote_get_noisy_reply(), remote_get_trace_state_variable_value(), remote_get_tracepoint_status(), remote_insert_breakpoint(), remote_insert_hw_breakpoint(), remote_insert_watchpoint(), remote_pid_to_str(), remote_query_attached(), remote_remove_breakpoint(), remote_remove_hw_breakpoint(), remote_remove_watchpoint(), remote_set_circular_trace_buffer(), remote_set_disconnected_tracing(), remote_set_permissions(), remote_set_trace_buffer_size(), remote_set_trace_notes(), remote_static_tracepoint_marker_at(), remote_stop_ns(), remote_threads_extra_info(), remote_trace_find(), remote_trace_set_readonly_regions(), remote_use_agent(), remote_vcont_resume(), remote_verify_memory(), remote_vkill(), safe_strerror(), send_g_packet(), set_thread(), set_variant_num_fprs(), set_variant_num_gprs(), sol2_core_pid_to_str(), solaris_pid_to_str(), solist_update_incremental(), spu_catch_start(), spu_current_sos(), spu_enumerate_spu_ids(), spu_fetch_inferior_registers(), spu_fetch_registers(), spu_proc_xfer_spu(), spu_pseudo_register_read(), spu_pseudo_register_read_spu(), spu_pseudo_register_write(), spu_pseudo_register_write_spu(), spu_store_inferior_registers(), spu_store_registers(), spu_symbol_file_add_from_memory(), spu_xfer_partial(), store_register(), store_register_using_P(), svr4_create_solib_event_breakpoints(), td_err_string(), td_state_string(), trace_status_mi(), tui_make_status_line(), tui_rl_display_match_list(), tui_update_gdb_sizes(), VEC(), windows_create_inferior(), windows_pid_to_exec_file(), and write_ptid().
char* xstrprintf (const char * format, ...)
Definition at line 115 of file common-utils.c.
References xstrvprintf().
Referenced by ada_exception_catchpoint_cond_string(), ada_varobj_describe_ptr_child(), ada_varobj_describe_simple_array_child(), ada_varobj_describe_struct_child(), ada_varobj_get_value_of_array_variable(), add_angle_brackets(), add_auto_load_safe_path(), add_deprecated_target_alias(), add_internal_problem_command(), add_packet_config_cmd(), add_pe_exported_sym(), add_pe_forwarded_sym(), add_sal_to_sals(), add_setshow_cmd_full(), add_vsyscall_page(), aix_thread_pid_to_str(), all_tracepoint_actions_and_cleanup(), ATTRIBUTE_PRINTF(), bpstat_check_watchpoint(), breakpoint_notify(), breakpoint_re_set(), build_error_marker_type(), c_describe_child(), c_value_of_variable(), canonical_to_fullform(), command_from_pid(), commandline_from_pid(), commands_command_1(), cplus_describe_child(), create_child_with_value(), create_dwo_unit_in_dwp_v1(), create_dwo_unit_in_dwp_v2(), create_thread_event_breakpoint(), create_tsv_from_upload(), create_type_unit_group(), ctf_start(), dec_thread_pid_to_str(), decimal_from_floating(), decode_line_2(), decode_objc(), do_map_commands_command(), edit_command(), env_execute_cli_command(), exec_reverse_once(), fbsd_find_memory_regions(), fbsd_pid_to_exec_file(), file_is_auto_load_safe(), fixup_definition(), gcore_command(), gdb_get_blocks(), gdb_selected_block(), gdb_selected_frame(), gdbtk_annotate_signal(), gdbtk_ignorable_warning(), gdbtk_init(), gdbtk_load_asm(), gdbtk_load_hash(), gdbtk_load_source(), gdbtk_selected_frame_changed(), gdbtk_set_hook(), get_core_register_section(), get_core_siginfo(), get_function_name(), get_init_files(), get_register_types(), i386_fast_tracepoint_valid_at(), init_breakpoint_sal(), init_cli_cmds(), is_package_name(), jit_reader_load_command(), linux_xfer_osdata_fds(), linux_xfer_osdata_threads(), memory_error_message(), mi_execute_async_cli_command(), mi_execute_cli_command(), nbsd_pid_to_exec_file(), new_variant(), open_and_init_dwp_file(), print_converted_chars_to_obstack(), print_mention_exception(), print_one_breakpoint_location(), print_one_catch_solib(), print_one_catch_syscall(), print_one_exception(), print_thread_info(), procfs_xfer_auxv(), regcache_dump(), salpy_str(), set_cp_abi_as_auto_default(), solib_aix_bfd_open(), solib_aix_current_sos(), sym_info(), target_waitstatus_to_string(), trace_actions_command(), update_dprintf_command_list(), update_dynamic_varobj_children(), update_static_tracepoint(), varobj_gen_name(), vfprintf_unfiltered(), view_command(), watch_command_1(), and xtensa_register_type().
char* xstrvprintf (const char * format, va_list ap)
Definition at line 127 of file common-utils.c.
References _, internal_error(), and exsummary::status.
Referenced by ATTRIBUTE_PRINTF(), gdbtk_query(), gdbtk_readline_begin(), gdbtk_set_result(), gdbtk_warning(), serial_printf(), TclDebug(), vfprintf_maybe_filtered(), vfprintf_unfiltered(), and xstrprintf().
void* xzalloc (size_t size)
Definition at line 99 of file common-utils.c.
References xcalloc().
Referenced by addr_info_make_relative(), allocate_objfile(), allocate_value_contents(), allocate_value_lazy(), cache_new_ref1(), dwarf2_add_typedef(), hwdebug_find_thread_points_by_tid(), ia64_gdbarch_init(), lm_info_read(), m68k_gdbarch_init(), new_block(), new_bvect(), parse_partial_symbols(), push_parse_stack(), read_pe_exported_syms(), remote_enable_btrace(), remote_notif_state_allocate(), replace_operator_with_call(), solib_target_relocate_section_addresses(), svr4_default_sos(), and VEC().