GDB (xrefs): /home/stan/gdb/src/gdb/complaints.c File Reference
/home/stan/gdb/src/gdb/complaints.c File Reference
#include "defs.h"
#include "complaints.h"
#include "gdb_assert.h"
#include "command.h"
#include "gdbcmd.h"
Classes
struct complain
struct explanation
struct complaints
Enumerations
enum complaint_series { ISOLATED_MESSAGE, FIRST_MESSAGE, SHORT_FIRST_MESSAGE, SUBSEQUENT_MESSAGE }
Functions
void _initialize_complaints (void)
static struct complaints * get_complaints (struct complaints **c)
static struct complain * ATTRIBUTE_PRINTF (4, 0)
void complaint (struct complaints **complaints, const char *fmt,...)
void internal_complaint (struct complaints **complaints, const char *file, int line, const char *fmt,...)
void clear_complaints (struct complaints **c, int less_verbose, int noisy)
static void complaints_show_value (struct ui_file *file, int from_tty, struct cmd_list_element *cmd, const char *value)
Variables
static struct complain complaint_sentinel
static struct explanation symfile_explanations []
static struct complaints symfile_complaint_book
struct complaints * symfile_complaints = &symfile_complaint_book
static int stop_whining = 0
Enumeration Type Documentation
enum complaint_series
Enumerator:
ISOLATED_MESSAGE
FIRST_MESSAGE
SHORT_FIRST_MESSAGE
SUBSEQUENT_MESSAGE
Definition at line 35 of file complaints.c.
Function Documentation
void _initialize_complaints (void)
static void ATTRIBUTE_PRINTF (4 , 0) [static, read]
Definition at line 122 of file complaints.c.
References complaint(), complain::counter, complain::file, complain::fmt, complain::line, line, complain::next, and XMALLOC.
void clear_complaints (struct complaints ** c, int less_verbose, int noisy)
Definition at line 274 of file complaints.c.
References _, complain::counter, FIRST_MESSAGE, fputs_unfiltered(), gdb_stderr, get_complaints(), internal_error(), ISOLATED_MESSAGE, complain::next, p, complaints::root, complaints::series, SHORT_FIRST_MESSAGE, and SUBSEQUENT_MESSAGE.
Referenced by new_symfile_objfile(), reread_symbols(), and syms_from_objfile_1().
void complaint (struct complaints ** complaints, const char * fmt, ...)
Definition at line 246 of file complaints.c.
Referenced by add_partial_enumeration(), attach_fields_to_type(), ATTRIBUTE_PRINTF(), augment_type_symtab(), bad_rfd_entry_complaint(), bad_tag_guess_complaint(), basic_type_complaint(), bf_notfound_complaint(), check_for_redefinition(), cleanup_undefined_types_1(), coff_symtab_read(), common_block_end(), common_block_start(), complain_about_struct_wipeout(), consume_improper_spaces(), create_addrmap_from_index(), create_debug_types_hash_table(), create_dwo_cu(), create_dwo_cu_reader(), create_dwp_hash_table(), dbx_lookup_type(), decode_base_type(), decode_frame_entry(), decode_locdesc(), decode_type(), define_symbol(), demangled_name_complaint(), determine_prefix(), dw2_expand_symtabs_matching(), dw2_symtab_iter_next(), dwarf2_add_member_fn(), dwarf2_attach_fields_to_type(), dwarf2_complex_location_expr_complaint(), dwarf2_compute_name(), dwarf2_const_value_attr(), dwarf2_const_value_length_mismatch_complaint(), dwarf2_debug_line_missing_end_sequence_complaint(), dwarf2_debug_line_missing_file_complaint(), dwarf2_fetch_constant_bytes(), dwarf2_frame_cache(), dwarf2_get_attr_constant_value(), dwarf2_get_ref_die_offset(), dwarf2_invalid_attrib_class_complaint(), dwarf2_macro_malformed_definition_complaint(), dwarf2_physname(), dwarf2_ranges_read(), dwarf2_record_block_ranges(), dwarf2_restore_rule(), dwarf2_section_buffer_overflow_complaint(), dwarf2_statement_list_fits_in_line_number_section_complaint(), dwarf2_symbol_mark_computed(), dwarf_decode_line_header(), dwarf_decode_lines_1(), dwarf_decode_macro_bytes(), dwarf_decode_macros(), dwarf_parse_macro_header(), eb_complaint(), ef_complaint(), elf_symtab_read(), elfstab_offset_sections(), end_symtab_get_static_block(), enter_line_range(), enter_linenos(), error_type(), execute_cfa_program(), file_file_name(), filter_overlapping_sections(), finish_block_internal(), fixup_go_packaging(), function_outside_compilation_unit_complaint(), get_DW_AT_signature_type(), get_signatured_type(), get_stap_base_address(), handle_stap_probe(), handle_unload_dll(), index_complaint(), inherit_abstract_dies(), init_cutu_and_read_dies(), invalid_cpp_abbrev_complaint(), lbrac_mismatch_complaint(), load_partial_dies(), lookup_child_selector(), lookup_die_type(), lookup_dwp_signatured_type(), lookup_objc_class(), macho_add_oso_symfile(), macho_symtab_read(), macro_include(), macro_undef(), make_blockvector(), new_symbol_full(), parse_lines(), parse_partial_symbols(), parse_procedure(), parse_symbol(), parse_type(), partial_die_parent_scope(), process_die(), process_one_symbol(), process_structure_scope(), process_xcoff_symbol(), psymtab_to_symtab_1(), read_args(), read_array_type(), read_attribute_value(), read_base_type(), read_baseclasses(), read_call_site_scope(), read_checked_initial_length_and_offset(), read_common_block(), read_cpp_abbrev(), read_dbx_symtab(), read_file_scope(), read_func_scope(), read_import_statement(), read_member_functions(), read_module_type(), read_partial_die(), read_range_type(), read_subrange_type(), read_symbol(), read_tag_pointer_type(), read_tilde_fields(), read_type(), read_type_die_1(), read_typedef(), read_xcoff_symtab(), record_include_begin(), record_include_end(), reg_value_complaint(), repeated_header_complaint(), rs6000_builtin_type(), sal_macro_scope(), scan_file_globals(), scan_xcoff_symtab(), selectors_info(), set_die_type(), set_namestring(), skip_form_bytes(), skip_one_die(), skip_unknown_opcode(), stabs_general_complaint(), stabs_method_name_from_physname(), stap_get_probes(), stap_parse_probe_arguments(), stub_noname_complaint(), unexpected_type_code_complaint(), unknown_ext_complaint(), unknown_symtype_complaint(), upgrade_type(), and xcoff_next_symbol_text().
static void complaints_show_value (struct ui_file * file, int from_tty, struct cmd_list_element * cmd, const char * value) [static]
Definition at line 316 of file complaints.c.
References _, and fprintf_filtered().
static struct complaints* get_complaints (struct complaints ** c) [static, read]
Definition at line 111 of file complaints.c.
References complaint_sentinel, ISOLATED_MESSAGE, and XMALLOC.
Referenced by clear_complaints().
void internal_complaint (struct complaints ** complaints, const char * file, int line, const char * fmt, ...)
Definition at line 256 of file complaints.c.
Variable Documentation
struct complain complaint_sentinel [static]
Definition at line 89 of file complaints.c.
Referenced by get_complaints().
int stop_whining = 0 [static]
Definition at line 161 of file complaints.c.
struct complaints symfile_complaint_book [static]
Initial value:
 {
  &complaint_sentinel,
  0,
  symfile_explanations
}
Definition at line 101 of file complaints.c.
struct complaints* symfile_complaints = &symfile_complaint_book
Definition at line 106 of file complaints.c.
Referenced by add_partial_enumeration(), attach_fields_to_type(), augment_type_symtab(), bad_rfd_entry_complaint(), bad_tag_guess_complaint(), basic_type_complaint(), bf_notfound_complaint(), check_for_redefinition(), cleanup_undefined_types_1(), coff_symtab_read(), common_block_end(), common_block_start(), complain_about_struct_wipeout(), consume_improper_spaces(), create_addrmap_from_index(), create_debug_types_hash_table(), create_dwo_cu(), create_dwo_cu_reader(), create_dwp_hash_table(), dbx_lookup_type(), decode_base_type(), decode_frame_entry(), decode_locdesc(), decode_type(), define_symbol(), demangled_name_complaint(), determine_prefix(), dw2_expand_symtabs_matching(), dw2_symtab_iter_next(), dwarf2_add_member_fn(), dwarf2_attach_fields_to_type(), dwarf2_complex_location_expr_complaint(), dwarf2_compute_name(), dwarf2_const_value_attr(), dwarf2_const_value_length_mismatch_complaint(), dwarf2_debug_line_missing_end_sequence_complaint(), dwarf2_debug_line_missing_file_complaint(), dwarf2_fetch_constant_bytes(), dwarf2_frame_cache(), dwarf2_get_attr_constant_value(), dwarf2_get_ref_die_offset(), dwarf2_invalid_attrib_class_complaint(), dwarf2_macro_malformed_definition_complaint(), dwarf2_physname(), dwarf2_ranges_read(), dwarf2_record_block_ranges(), dwarf2_restore_rule(), dwarf2_section_buffer_overflow_complaint(), dwarf2_statement_list_fits_in_line_number_section_complaint(), dwarf2_symbol_mark_computed(), dwarf_decode_line_header(), dwarf_decode_lines_1(), dwarf_decode_macro_bytes(), dwarf_decode_macros(), dwarf_parse_macro_header(), eb_complaint(), ef_complaint(), elf_symtab_read(), elfstab_offset_sections(), end_symtab_get_static_block(), enter_line_range(), enter_linenos(), error_type(), execute_cfa_program(), file_file_name(), filter_overlapping_sections(), finish_block_internal(), fixup_go_packaging(), function_outside_compilation_unit_complaint(), get_DW_AT_signature_type(), get_signatured_type(), get_stap_base_address(), handle_stap_probe(), handle_unload_dll(), index_complaint(), inherit_abstract_dies(), init_cutu_and_read_dies(), invalid_cpp_abbrev_complaint(), lbrac_mismatch_complaint(), load_partial_dies(), lookup_child_selector(), lookup_die_type(), lookup_dwp_signatured_type(), lookup_objc_class(), macho_add_oso_symfile(), macho_symtab_read(), macro_include(), macro_undef(), make_blockvector(), new_symbol_full(), new_symfile_objfile(), parse_lines(), parse_partial_symbols(), parse_procedure(), parse_symbol(), parse_type(), partial_die_parent_scope(), process_die(), process_one_symbol(), process_structure_scope(), process_xcoff_symbol(), psymtab_to_symtab_1(), read_args(), read_array_type(), read_attribute_value(), read_base_type(), read_baseclasses(), read_call_site_scope(), read_checked_initial_length_and_offset(), read_common_block(), read_cpp_abbrev(), read_dbx_symtab(), read_file_scope(), read_func_scope(), read_import_statement(), read_member_functions(), read_module_type(), read_partial_die(), read_range_type(), read_subrange_type(), read_symbol(), read_tag_pointer_type(), read_tilde_fields(), read_type(), read_type_die_1(), read_typedef(), read_xcoff_symtab(), record_include_begin(), record_include_end(), reg_value_complaint(), repeated_header_complaint(), reread_symbols(), rs6000_builtin_type(), sal_macro_scope(), scan_file_globals(), scan_xcoff_symtab(), selectors_info(), set_die_type(), set_namestring(), skip_form_bytes(), skip_one_die(), skip_unknown_opcode(), stabs_general_complaint(), stabs_method_name_from_physname(), stap_get_probes(), stap_parse_probe_arguments(), stub_noname_complaint(), syms_from_objfile_1(), unexpected_type_code_complaint(), unknown_ext_complaint(), unknown_symtype_complaint(), upgrade_type(), and xcoff_next_symbol_text().
struct explanation symfile_explanations[] [static]
Initial value:
 {
  { "During symbol reading, ", "." },
  { "During symbol reading...", "..."},
  { "", "..."},
  { "", "..."},
  { NULL, NULL }
}
Definition at line 93 of file complaints.c.