GDB (xrefs): /home/stan/gdb/src/gdb/completer.c File Reference
/home/stan/gdb/src/gdb/completer.c File Reference
#include "defs.h"
#include "symtab.h"
#include "gdbtypes.h"
#include "expression.h"
#include "filenames.h"
#include "language.h"
#include "gdb_assert.h"
#include "exceptions.h"
#include "gdb_signals.h"
#include "cli/cli-decode.h"
#include "gdbcmd.h"
#include "readline/readline.h"
#include "completer.h"
Enumerations
enum complete_line_internal_reason { handle_brkchars, handle_completions, handle_help }
Functions
static char * line_completion_function (const char *text, int matches, char *line_buffer, int point)
char * get_gdb_completer_quote_characters (void)
char * readline_line_completion_function (const char *text, int matches)
VEC (char_ptr)
static void add_struct_fields (struct type *type, VEC(char_ptr)**output, char *fieldname, int namelen)
char * gdb_completion_word_break_characters (void)
const char * skip_quoted_chars (const char *str, const char *quotechars, const char *breakchars)
const char * skip_quoted (const char *str)
Variables
static char * gdb_completer_command_word_break_characters = " \t\n!@#$%^&*()+=|~`}{[]\"';:?/>.<,"
static char * gdb_completer_file_name_break_characters = " \t\n*|\"';:?><"
static char * gdb_completer_quote_characters = "'"
Enumeration Type Documentation
enum complete_line_internal_reason
Enumerator:
handle_brkchars
handle_completions
handle_help
Definition at line 476 of file completer.c.
Function Documentation
static void add_struct_fields (struct type * type, VEC(char_ptr)** output, char * fieldname, int namelen) [static]
Definition at line 338 of file completer.c.
References CHECK_TYPEDEF, name, TYPE_BASECLASS, TYPE_CODE, TYPE_CODE_UNION, TYPE_FIELD_NAME, TYPE_FIELD_TYPE, TYPE_FN_FIELDLIST_NAME, TYPE_N_BASECLASSES, type_name_no_tag(), TYPE_NFIELDS, TYPE_NFN_FIELDS, and VEC_safe_push.
char* gdb_completion_word_break_characters (void)
Definition at line 824 of file completer.c.
References gdb_assert, handle_brkchars, and VEC.
Referenced by init_main().
char* get_gdb_completer_quote_characters (void)
Definition at line 92 of file completer.c.
References gdb_completer_quote_characters.
Referenced by init_main().
static char * line_completion_function (const char * text, int matches, char * line_buffer, int point) [static]
Definition at line 856 of file completer.c.
References current_language, language_defn::la_word_break_characters, VEC, VEC_free, VEC_index, and VEC_length.
Referenced by readline_line_completion_function().
char* readline_line_completion_function (const char * text, int matches)
Definition at line 100 of file completer.c.
References line_completion_function().
Referenced by init_main().
const char* skip_quoted (const char * str)
Definition at line 958 of file completer.c.
References skip_quoted_chars().
Referenced by yylex().
const char* skip_quoted_chars (const char * str, const char * quotechars, const char * breakchars)
Definition at line 915 of file completer.c.
References current_language, gdb_completer_quote_characters, language_defn::la_word_break_characters, scan(), and strchr().
Referenced by skip_quoted().
VEC (char_ptr)
Definition at line 108 of file completer.c.
Variable Documentation
char* gdb_completer_command_word_break_characters = " \t\n!@#$%^&*()+=|~`}{[]\"';:?/>.<," [static]
Definition at line 69 of file completer.c.
char* gdb_completer_file_name_break_characters = " \t\n*|\"';:?><" [static]
Definition at line 81 of file completer.c.
char* gdb_completer_quote_characters = "'" [static]
Definition at line 87 of file completer.c.
Referenced by get_gdb_completer_quote_characters(), and skip_quoted_chars().