GDB (xrefs): /home/stan/gdb/src/gdb/continuations.h File Reference
/home/stan/gdb/src/gdb/continuations.h File Reference
Typedefs
typedef void(continuation_ftype)(void *arg, int err)
typedef void(continuation_free_arg_ftype)(void *)
Functions
void add_continuation (struct thread_info *, continuation_ftype *, void *, continuation_free_arg_ftype *)
void do_all_continuations (int err)
void do_all_continuations_thread (struct thread_info *, int err)
void discard_all_continuations (void)
void discard_all_continuations_thread (struct thread_info *)
void add_intermediate_continuation (struct thread_info *, continuation_ftype *, void *, continuation_free_arg_ftype *)
void do_all_intermediate_continuations (int err)
void do_all_intermediate_continuations_thread (struct thread_info *, int err)
void discard_all_intermediate_continuations (void)
void discard_all_intermediate_continuations_thread (struct thread_info *)
void add_inferior_continuation (continuation_ftype *, void *, continuation_free_arg_ftype *)
void do_all_inferior_continuations (int err)
void discard_all_inferior_continuations (struct inferior *inf)
Typedef Documentation
typedef void(continuation_free_arg_ftype)(void *)
Definition at line 46 of file continuations.h.
typedef void(continuation_ftype)(void *arg, int err)
Definition at line 41 of file continuations.h.
Function Documentation
void add_continuation (struct thread_info * , continuation_ftype * , void * , continuation_free_arg_ftype *)
Definition at line 140 of file continuations.c.
References thread_info::continuations, and make_continuation().
Referenced by finish_forward(), until_break_command(), and until_next_command().
void add_inferior_continuation (continuation_ftype * , void * , continuation_free_arg_ftype *)
Definition at line 111 of file continuations.c.
References inferior::continuations, current_inferior(), and make_continuation().
Referenced by attach_command(), and notice_new_inferior().
void add_intermediate_continuation (struct thread_info * , continuation_ftype * , void * , continuation_free_arg_ftype *)
Definition at line 253 of file continuations.c.
References thread_info::intermediate_continuations, and make_continuation().
Referenced by step_once().
void discard_all_continuations (void)
Definition at line 243 of file continuations.c.
References discard_all_continuations_thread_callback(), and iterate_over_threads().
Referenced by stdin_event_handler().
void discard_all_continuations_thread (struct thread_info *)
Definition at line 235 of file continuations.c.
References discard_all_continuations_thread_callback().
void discard_all_inferior_continuations (struct inferior * inf)
Definition at line 131 of file continuations.c.
References inferior::continuations, and discard_my_continuations().
Referenced by free_inferior().
void discard_all_intermediate_continuations (void)
Definition at line 320 of file continuations.c.
References discard_all_intermediate_continuations_thread_callback(), and iterate_over_threads().
Referenced by stdin_event_handler().
void discard_all_intermediate_continuations_thread (struct thread_info *)
Definition at line 312 of file continuations.c.
References discard_all_intermediate_continuations_thread_callback().
void do_all_continuations (int err)
Definition at line 217 of file continuations.c.
References do_all_continuations_thread_callback(), and iterate_over_threads().
Referenced by finish_forward(), and inferior_event_handler().
void do_all_continuations_thread (struct thread_info * , int err)
Definition at line 209 of file continuations.c.
References do_all_continuations_thread_callback().
Referenced by clear_thread_inferior_resources(), inferior_event_handler(), and infrun_thread_stop_requested_callback().
void do_all_inferior_continuations (int err)
Definition at line 122 of file continuations.c.
References inferior::continuations, current_inferior(), and do_my_continuations().
Referenced by inferior_event_handler().
void do_all_intermediate_continuations (int err)
Definition at line 293 of file continuations.c.
References do_all_intermediate_continuations_thread_callback(), and iterate_over_threads().
Referenced by inferior_event_handler().
void do_all_intermediate_continuations_thread (struct thread_info * , int err)
Definition at line 285 of file continuations.c.
References do_all_intermediate_continuations_thread_callback().
Referenced by clear_thread_inferior_resources(), inferior_event_handler(), and infrun_thread_stop_requested_callback().