GDB (xrefs): /home/stan/gdb/src/gdb/continuations.c File Reference
/home/stan/gdb/src/gdb/continuations.c File Reference
#include "defs.h"
#include "gdbthread.h"
#include "inferior.h"
#include "continuations.h"
Classes
struct continuation
Functions
static void make_continuation (struct continuation **pmy_chain, continuation_ftype *function, void *arg, void(*free_arg)(void *))
static void do_my_continuations_1 (struct continuation **pmy_chain, int err)
static void do_my_continuations (struct continuation **list, int err)
static void discard_my_continuations_1 (struct continuation **pmy_chain)
static void discard_my_continuations (struct continuation **list)
void add_inferior_continuation (continuation_ftype *hook, void *args, continuation_free_arg_ftype *free_arg)
void do_all_inferior_continuations (int err)
void discard_all_inferior_continuations (struct inferior *inf)
void add_continuation (struct thread_info *thread, continuation_ftype *hook, void *args, continuation_free_arg_ftype *free_arg)
static void restore_thread_cleanup (void *arg)
static void do_all_continuations_ptid (ptid_t ptid, struct continuation **continuations_p, int err)
static int do_all_continuations_thread_callback (struct thread_info *thread, void *data)
void do_all_continuations_thread (struct thread_info *thread, int err)
void do_all_continuations (int err)
static int discard_all_continuations_thread_callback (struct thread_info *thread, void *data)
void discard_all_continuations_thread (struct thread_info *thread)
void discard_all_continuations (void)
void add_intermediate_continuation (struct thread_info *thread, continuation_ftype *hook, void *args, continuation_free_arg_ftype *free_arg)
static int do_all_intermediate_continuations_thread_callback (struct thread_info *thread, void *data)
void do_all_intermediate_continuations_thread (struct thread_info *thread, int err)
void do_all_intermediate_continuations (int err)
static int discard_all_intermediate_continuations_thread_callback (struct thread_info *thread, void *data)
void discard_all_intermediate_continuations_thread (struct thread_info *thread)
void discard_all_intermediate_continuations (void)
Function Documentation
void add_continuation (struct thread_info * thread, continuation_ftype * hook, void * args, continuation_free_arg_ftype * free_arg)
Definition at line 140 of file continuations.c.
References thread_info::continuations, and make_continuation().
Referenced by finish_forward(), until_break_command(), and until_next_command().
void add_inferior_continuation (continuation_ftype * hook, void * args, continuation_free_arg_ftype * free_arg)
Definition at line 111 of file continuations.c.
References inferior::continuations, current_inferior(), and make_continuation().
Referenced by attach_command(), and notice_new_inferior().
void add_intermediate_continuation (struct thread_info * thread, continuation_ftype * hook, void * args, continuation_free_arg_ftype * free_arg)
Definition at line 253 of file continuations.c.
References thread_info::intermediate_continuations, and make_continuation().
Referenced by step_once().
void discard_all_continuations (void)
Definition at line 243 of file continuations.c.
References discard_all_continuations_thread_callback(), and iterate_over_threads().
Referenced by stdin_event_handler().
void discard_all_continuations_thread (struct thread_info * thread)
Definition at line 235 of file continuations.c.
References discard_all_continuations_thread_callback().
static int discard_all_continuations_thread_callback (struct thread_info * thread, void * data) [static]
Definition at line 225 of file continuations.c.
References thread_info::continuations, and discard_my_continuations().
Referenced by discard_all_continuations(), and discard_all_continuations_thread().
void discard_all_inferior_continuations (struct inferior * inf)
Definition at line 131 of file continuations.c.
References inferior::continuations, and discard_my_continuations().
Referenced by free_inferior().
void discard_all_intermediate_continuations (void)
Definition at line 320 of file continuations.c.
References discard_all_intermediate_continuations_thread_callback(), and iterate_over_threads().
Referenced by stdin_event_handler().
void discard_all_intermediate_continuations_thread (struct thread_info * thread)
Definition at line 312 of file continuations.c.
References discard_all_intermediate_continuations_thread_callback().
static int discard_all_intermediate_continuations_thread_callback (struct thread_info * thread, void * data) [static]
Definition at line 302 of file continuations.c.
References discard_my_continuations(), and thread_info::intermediate_continuations.
Referenced by discard_all_intermediate_continuations(), and discard_all_intermediate_continuations_thread().
static void discard_my_continuations (struct continuation ** list) [static]
Definition at line 101 of file continuations.c.
References discard_my_continuations_1().
Referenced by discard_all_continuations_thread_callback(), discard_all_inferior_continuations(), and discard_all_intermediate_continuations_thread_callback().
static void discard_my_continuations_1 (struct continuation ** pmy_chain) [static]
Definition at line 87 of file continuations.c.
References continuation::arg, continuation::free_arg, continuation::next, and xfree().
Referenced by discard_my_continuations().
void do_all_continuations (int err)
Definition at line 217 of file continuations.c.
References do_all_continuations_thread_callback(), and iterate_over_threads().
Referenced by finish_forward(), and inferior_event_handler().
static void do_all_continuations_ptid (ptid_t ptid, struct continuation ** continuations_p, int err) [static]
Definition at line 165 of file continuations.c.
References current_thread, do_cleanups(), do_my_continuations(), inferior_ptid, make_cleanup(), restore_thread_cleanup(), and switch_to_thread().
Referenced by do_all_continuations_thread_callback(), and do_all_intermediate_continuations_thread_callback().
void do_all_continuations_thread (struct thread_info * thread, int err)
Definition at line 209 of file continuations.c.
References do_all_continuations_thread_callback().
Referenced by clear_thread_inferior_resources(), inferior_event_handler(), and infrun_thread_stop_requested_callback().
static int do_all_continuations_thread_callback (struct thread_info * thread, void * data) [static]
Definition at line 199 of file continuations.c.
References thread_info::continuations, do_all_continuations_ptid(), and thread_info::ptid.
Referenced by do_all_continuations(), and do_all_continuations_thread().
void do_all_inferior_continuations (int err)
Definition at line 122 of file continuations.c.
References inferior::continuations, current_inferior(), and do_my_continuations().
Referenced by inferior_event_handler().
void do_all_intermediate_continuations (int err)
Definition at line 293 of file continuations.c.
References do_all_intermediate_continuations_thread_callback(), and iterate_over_threads().
Referenced by inferior_event_handler().
void do_all_intermediate_continuations_thread (struct thread_info * thread, int err)
Definition at line 285 of file continuations.c.
References do_all_intermediate_continuations_thread_callback().
Referenced by clear_thread_inferior_resources(), inferior_event_handler(), and infrun_thread_stop_requested_callback().
static int do_all_intermediate_continuations_thread_callback (struct thread_info * thread, void * data) [static]
Definition at line 272 of file continuations.c.
References do_all_continuations_ptid(), thread_info::intermediate_continuations, and thread_info::ptid.
Referenced by do_all_intermediate_continuations(), and do_all_intermediate_continuations_thread().
static void do_my_continuations (struct continuation ** list, int err) [static]
Definition at line 67 of file continuations.c.
References do_my_continuations_1().
Referenced by do_all_continuations_ptid(), and do_all_inferior_continuations().
static void do_my_continuations_1 (struct continuation ** pmy_chain, int err) [static]
Definition at line 52 of file continuations.c.
References continuation::arg, continuation::free_arg, continuation::function, continuation::next, and xfree().
Referenced by do_my_continuations().
static void make_continuation (struct continuation ** pmy_chain, continuation_ftype * function, void * arg, void(*)(void *) free_arg) [static]
Definition at line 38 of file continuations.c.
References continuation::arg, continuation::free_arg, and continuation::function.
Referenced by add_continuation(), add_inferior_continuation(), and add_intermediate_continuation().
static void restore_thread_cleanup (void * arg) [static]
Definition at line 148 of file continuations.c.
References switch_to_thread().
Referenced by do_all_continuations_ptid().