GDB (xrefs): /home/stan/gdb/src/gdb/core-regset.c File Reference
/home/stan/gdb/src/gdb/core-regset.c File Reference
#include "defs.h"
#include "command.h"
#include "gdbcore.h"
#include "inferior.h"
#include "target.h"
#include "regcache.h"
#include <fcntl.h>
#include <errno.h>
#include "gdb_string.h"
#include <time.h>
#include "gregset.h"
Functions
static void fetch_core_registers (struct regcache *regcache, char *core_reg_sect, unsigned core_reg_size, int which, CORE_ADDR reg_addr)
void _initialize_core_regset (void)
Variables
static struct core_fns regset_core_fns
Function Documentation
void _initialize_core_regset (void)
Definition at line 120 of file core-regset.c.
References deprecated_add_core_fns().
static void fetch_core_registers (struct regcache * regcache, char * core_reg_sect, unsigned core_reg_size, int which, CORE_ADDR reg_addr) [static]
Definition at line 60 of file core-regset.c.
References _, gdbarch_fp0_regnum(), get_regcache_arch(), memcpy(), supply_fpregset(), supply_gregset(), and warning().
Variable Documentation
struct core_fns regset_core_fns [static]
Initial value:
{
  bfd_target_elf_flavour,
  default_check_format,
  default_core_sniffer,
  fetch_core_registers,
  NULL
}
Definition at line 107 of file core-regset.c.