GDB (xrefs): /home/stan/gdb/src/gdb/cp-abi.c File Reference
/home/stan/gdb/src/gdb/cp-abi.c File Reference
#include "defs.h"
#include "value.h"
#include "cp-abi.h"
#include "command.h"
#include "exceptions.h"
#include "gdbcmd.h"
#include "ui-out.h"
#include "gdb_assert.h"
#include "gdb_string.h"
Defines
#define CP_ABI_MAX 8
Functions
static struct cp_abi_ops * find_cp_abi (const char *short_name)
enum ctor_kinds is_constructor_name (const char *name)
enum dtor_kinds is_destructor_name (const char *name)
int is_vtable_name (const char *name)
int is_operator_name (const char *name)
int baseclass_offset (struct type *type, int index, const gdb_byte *valaddr, int embedded_offset, CORE_ADDR address, const struct value *val)
struct value * value_virtual_fn_field (struct value **arg1p, struct fn_field *f, int j, struct type *type, int offset)
struct type * value_rtti_type (struct value *v, int *full, int *top, int *using_enc)
void cplus_print_method_ptr (const gdb_byte *contents, struct type *type, struct ui_file *stream)
int cplus_method_ptr_size (struct type *to_type)
void cplus_make_method_ptr (struct type *type, gdb_byte *contents, CORE_ADDR value, int is_virtual)
CORE_ADDR cplus_skip_trampoline (struct frame_info *frame, CORE_ADDR stop_pc)
struct value * cplus_method_ptr_to_value (struct value **this_p, struct value *method_ptr)
void cplus_print_vtable (struct value *value)
struct value * cplus_typeid (struct value *value)
struct type * cplus_typeid_type (struct gdbarch *gdbarch)
struct type * cplus_type_from_type_info (struct value *value)
char * cplus_typename_from_type_info (struct value *value)
int cp_pass_by_reference (struct type *type)
static int switch_to_cp_abi (const char *short_name)
int register_cp_abi (struct cp_abi_ops *abi)
void set_cp_abi_as_auto_default (const char *short_name)
static void list_cp_abis (int from_tty)
static void set_cp_abi_cmd (char *args, int from_tty)
static VEC (char_ptr)
static void show_cp_abi_cmd (char *args, int from_tty)
void _initialize_cp_abi (void)
Variables
static struct cp_abi_ops current_cp_abi = { "", NULL }
static struct cp_abi_ops auto_cp_abi = { "auto", NULL }
static struct cp_abi_ops * cp_abis [CP_ABI_MAX]
static int num_cp_abis = 0
initialize_file_ftype _initialize_cp_abi
Define Documentation
#define CP_ABI_MAX 8
Definition at line 35 of file cp-abi.c.
Referenced by register_cp_abi().
Function Documentation
void _initialize_cp_abi (void)
Definition at line 397 of file cp-abi.c.
References _, _initialize_cp_abi, add_cmd(), class_obscure, register_cp_abi(), set_cp_abi_cmd(), setlist, show_cp_abi_cmd(), showlist, and switch_to_cp_abi().
int baseclass_offset (struct type * type, int index, const gdb_byte * valaddr, int embedded_offset, CORE_ADDR address, const struct value * val)
Definition at line 72 of file cp-abi.c.
References _, cp_abi_ops::baseclass_offset, gdb_exception::error, gdb_assert, NOT_AVAILABLE_ERROR, gdb_exception::reason, RETURN_MASK_ERROR, throw_error(), throw_exception(), and TRY_CATCH.
Referenced by cp_print_value(), do_search_struct_field(), dynamic_cast_check_1(), dynamic_cast_check_2(), find_method_list(), is_unique_ancestor_worker(), pascal_object_print_value(), search_struct_method(), and value_primitive_field().
int cp_pass_by_reference (struct type * type)
Definition at line 224 of file cp-abi.c.
References cp_abi_ops::pass_by_reference, and type.
void cplus_make_method_ptr (struct type * type, gdb_byte * contents, CORE_ADDR value, int is_virtual)
Definition at line 146 of file cp-abi.c.
References _, error(), and cp_abi_ops::make_method_ptr.
Referenced by value_cast().
int cplus_method_ptr_size (struct type * to_type)
Definition at line 138 of file cp-abi.c.
References _, error(), and cp_abi_ops::method_ptr_size.
Referenced by smash_to_methodptr_type().
struct value* cplus_method_ptr_to_value (struct value ** this_p, struct value * method_ptr) [read]
Definition at line 164 of file cp-abi.c.
References _, error(), and cp_abi_ops::method_ptr_to_value.
Referenced by evaluate_subexp_standard().
void cplus_print_method_ptr (const gdb_byte * contents, struct type * type, struct ui_file * stream)
Definition at line 128 of file cp-abi.c.
References _, error(), and cp_abi_ops::print_method_ptr.
Referenced by c_val_print().
void cplus_print_vtable (struct value * value)
Definition at line 175 of file cp-abi.c.
References _, error(), and cp_abi_ops::print_vtable.
Referenced by info_vtbl_command().
CORE_ADDR cplus_skip_trampoline (struct frame_info * frame, CORE_ADDR stop_pc)
Definition at line 155 of file cp-abi.c.
References cp_abi_ops::skip_trampoline, and stop_pc.
struct type* cplus_type_from_type_info (struct value * value) [read]
Definition at line 205 of file cp-abi.c.
References _, error(), and cp_abi_ops::get_type_from_type_info.
Referenced by compute_exception().
struct value* cplus_typeid (struct value * value) [read]
Definition at line 185 of file cp-abi.c.
References _, error(), and cp_abi_ops::get_typeid.
Referenced by evaluate_subexp_standard().
struct type* cplus_typeid_type (struct gdbarch * gdbarch) [read]
Definition at line 195 of file cp-abi.c.
References _, error(), and cp_abi_ops::get_typeid_type.
Referenced by evaluate_subexp_standard().
char* cplus_typename_from_type_info (struct value * value)
Definition at line 215 of file cp-abi.c.
References _, error(), and cp_abi_ops::get_typename_from_type_info.
Referenced by check_status_exception_catchpoint().
static struct cp_abi_ops * find_cp_abi (const char * short_name) [static, read]
Definition at line 299 of file cp-abi.c.
References num_cp_abis, and cp_abi_ops::shortname.
Referenced by set_cp_abi_as_auto_default(), and switch_to_cp_abi().
enum ctor_kinds is_constructor_name (const char * name)
Definition at line 40 of file cp-abi.c.
References _, error(), cp_abi_ops::is_constructor_name, and name.
Referenced by c_type_print_base(), gdb_mangle_name(), gnuv3_pass_by_reference(), and java_type_print_base().
enum dtor_kinds is_destructor_name (const char * name)
Definition at line 48 of file cp-abi.c.
References _, error(), cp_abi_ops::is_destructor_name, and name.
Referenced by c_type_print_base(), gdb_mangle_name(), java_type_print_base(), and read_member_functions().
int is_operator_name (const char * name)
Definition at line 64 of file cp-abi.c.
References _, error(), cp_abi_ops::is_operator_name, and name.
Referenced by gdb_mangle_name(), and linespec_lexer_lex_string().
int is_vtable_name (const char * name)
Definition at line 56 of file cp-abi.c.
References _, error(), cp_abi_ops::is_vtable_name, and name.
Referenced by gnuv2_value_rtti_type(), ia64_convert_from_func_ptr_addr(), process_structure_scope(), and record_minimal_symbol().
static void list_cp_abis (int from_tty) [static]
Definition at line 313 of file cp-abi.c.
References cleanup_chain, current_uiout, do_cleanups(), make_cleanup_ui_out_tuple_begin_end(), num_cp_abis, ui_out_field_string(), and ui_out_text().
Referenced by set_cp_abi_cmd().
int register_cp_abi (struct cp_abi_ops * abi)
Definition at line 249 of file cp-abi.c.
References _, CP_ABI_MAX, internal_error(), and num_cp_abis.
Referenced by _initialize_cp_abi(), _initialize_gnu_v2_abi(), and _initialize_gnu_v3_abi().
void set_cp_abi_as_auto_default (const char * short_name)
Definition at line 264 of file cp-abi.c.
References _, cp_abi_ops::doc, find_cp_abi(), internal_error(), cp_abi_ops::longname, cp_abi_ops::shortname, switch_to_cp_abi(), xfree(), and xstrprintf().
Referenced by _initialize_gnu_v3_abi().
static void set_cp_abi_cmd (char * args, int from_tty) [static]
Definition at line 346 of file cp-abi.c.
References _, error(), list_cp_abis(), and switch_to_cp_abi().
Referenced by _initialize_cp_abi().
static void show_cp_abi_cmd (char * args, int from_tty) [static]
Definition at line 382 of file cp-abi.c.
References current_uiout, cp_abi_ops::longname, cp_abi_ops::shortname, ui_out_field_string(), and ui_out_text().
Referenced by _initialize_cp_abi().
static int switch_to_cp_abi (const char * short_name) [static]
Definition at line 234 of file cp-abi.c.
References find_cp_abi().
Referenced by _initialize_cp_abi(), set_cp_abi_as_auto_default(), and set_cp_abi_cmd().
struct type* value_rtti_type (struct value * v, int * full, int * top, int * using_enc) [read]
Definition at line 110 of file cp-abi.c.
References gdb_exception::reason, RETURN_MASK_ERROR, cp_abi_ops::rtti_type, and TRY_CATCH.
Referenced by c_value_print(), cp_print_value_fields_rtti(), value_cast_structs(), value_dynamic_cast(), value_full_object(), value_rtti_indirect_type(), and whatis_exp().
struct value* value_virtual_fn_field (struct value ** arg1p, struct fn_field * f, int j, struct type * type, int offset) [read]
Definition at line 99 of file cp-abi.c.
References offset, type, and cp_abi_ops::virtual_fn_field.
Referenced by find_overload_match(), and search_struct_method().
static VEC (char_ptr) [static]
Definition at line 360 of file cp-abi.c.
References num_cp_abis.
Variable Documentation
initialize_file_ftype _initialize_cp_abi
Referenced by _initialize_cp_abi(), and initialize_all_files().
struct cp_abi_ops auto_cp_abi = { "auto", NULL } [static]
Definition at line 33 of file cp-abi.c.
struct cp_abi_ops* cp_abis[CP_ABI_MAX] [static]
Definition at line 36 of file cp-abi.c.
struct cp_abi_ops current_cp_abi = { "", NULL } [static]
Definition at line 32 of file cp-abi.c.
int num_cp_abis = 0 [static]
Definition at line 37 of file cp-abi.c.
Referenced by find_cp_abi(), list_cp_abis(), register_cp_abi(), and VEC().