GDB (xrefs): /home/stan/gdb/src/gdb/cp-namespace.c File Reference
/home/stan/gdb/src/gdb/cp-namespace.c File Reference
#include "defs.h"
#include "cp-support.h"
#include "gdb_obstack.h"
#include "symtab.h"
#include "symfile.h"
#include "gdb_assert.h"
#include "block.h"
#include "objfiles.h"
#include "gdbtypes.h"
#include "dictionary.h"
#include "command.h"
#include "frame.h"
#include "buildsym.h"
#include "language.h"
Functions
static struct symbol * lookup_namespace_scope (const char *name, const struct block *block, const domain_enum domain, const char *scope, int scope_len)
static struct symbol * lookup_symbol_file (const char *name, const struct block *block, const domain_enum domain, int anonymous_namespace, int search)
static struct type * cp_lookup_transparent_type_loop (const char *name, const char *scope, int scope_len)
void cp_scan_for_anonymous_namespaces (const struct symbol *const symbol, struct objfile *const objfile)
void cp_add_using_directive (const char *dest, const char *src, const char *alias, const char *declaration, VEC(const_char_ptr)*excludes, int copy_names, struct obstack *obstack)
int cp_is_anonymous (const char *namespace)
struct symbol * cp_lookup_symbol_nonlocal (const char *name, const struct block *block, const domain_enum domain)
static struct symbol * cp_lookup_symbol_in_namespace (const char *namespace, const char *name, const struct block *block, const domain_enum domain, int search)
static void reset_directive_searched (void *data)
struct symbol * cp_lookup_symbol_imports (const char *scope, const char *name, const struct block *block, const domain_enum domain, const int declaration_only, const int search_parents)
static struct symbol * search_symbol_list (const char *name, int num, struct symbol **syms)
struct symbol * cp_lookup_symbol_imports_or_template (const char *scope, const char *name, const struct block *block, const domain_enum domain)
struct symbol * cp_lookup_symbol_namespace (const char *scope, const char *name, const struct block *block, const domain_enum domain)
static struct symbol * find_symbol_in_baseclass (struct type *parent_type, const char *name, const struct block *block)
struct symbol * cp_lookup_nested_symbol (struct type *parent_type, const char *nested_name, const struct block *block)
struct type * cp_lookup_transparent_type (const char *name)
static void maintenance_cplus_namespace (char *args, int from_tty)
void _initialize_cp_namespace (void)
Variables
initialize_file_ftype _initialize_cp_namespace
Function Documentation
void _initialize_cp_namespace (void)
Definition at line 918 of file cp-namespace.c.
References _, add_cmd(), class_maintenance, deprecate_cmd(), maint_cplus_cmd_list, and maintenance_cplus_namespace().
void cp_add_using_directive (const char * dest, const char * src, const char * alias, const char * declaration, VEC(const_char_ptr)* excludes, int copy_names, struct obstack * obstack)
Definition at line 127 of file cp-namespace.c.
References using_direct::alias, using_direct::declaration, using_direct::excludes, using_direct::import_dest, using_direct::import_src, memcpy(), memset(), using_direct::next, using_directives, VEC_address, VEC_iterate, and VEC_length.
Referenced by cp_scan_for_anonymous_namespaces(), read_import_statement(), and read_namespace().
int cp_is_anonymous (const char * namespace)
Definition at line 212 of file cp-namespace.c.
References CP_ANONYMOUS_NAMESPACE_STR, and strstr().
Referenced by cp_lookup_symbol_in_namespace(), and cp_scan_for_anonymous_namespaces().
struct symbol* cp_lookup_nested_symbol (struct type * parent_type, const char * nested_name, const struct block * block) [read]
Definition at line 772 of file cp-namespace.c.
References _, CHECK_TYPEDEF, cp_lookup_symbol_in_namespace(), find_symbol_in_baseclass(), internal_error(), lookup_static_symbol_aux(), size, TYPE_CODE, TYPE_CODE_FUNC, TYPE_CODE_METHOD, TYPE_CODE_NAMESPACE, TYPE_CODE_STRUCT, TYPE_CODE_UNION, type_name_no_tag_or_error(), VAR_DOMAIN, and xsnprintf().
Referenced by classify_inner_name(), and lookup_symbol_file().
struct symbol* cp_lookup_symbol_imports (const char * scope, const char * name, const struct block * block, const domain_enum domain, const int declaration_only, const int search_parents) [read]
Definition at line 306 of file cp-namespace.c.
References using_direct::alias, block_using(), cp_lookup_symbol_imports(), cp_lookup_symbol_in_namespace(), using_direct::declaration, discard_cleanups(), using_direct::excludes, using_direct::import_dest, using_direct::import_src, len, make_cleanup(), using_direct::next, reset_directive_searched(), and using_direct::searched.
Referenced by cp_lookup_symbol_imports(), cp_lookup_symbol_imports_or_template(), and cp_lookup_symbol_namespace().
struct symbol* cp_lookup_symbol_imports_or_template (const char * scope, const char * name, const struct block * block, const domain_enum domain) [read]
Definition at line 445 of file cp-namespace.c.
References BLOCK_FUNCTION, BLOCK_SUPERBLOCK, cp_entire_prefix_len(), cp_lookup_symbol_imports(), do_cleanups(), get_objfile_arch(), language_cplus, language_def(), lookup_typename(), make_cleanup(), template_symbol::n_template_arguments, search_symbol_list(), SYMBOL_IS_CPLUS_TEMPLATE_FUNCTION, SYMBOL_LANGUAGE, SYMBOL_NATURAL_NAME, SYMBOL_SYMTAB, template_symbol::template_arguments, TYPE_N_TEMPLATE_ARGUMENTS, TYPE_TEMPLATE_ARGUMENTS, and xfree().
Referenced by lookup_symbol_aux_local().
static struct symbol* cp_lookup_symbol_in_namespace (const char * namespace, const char * name, const struct block * block, const domain_enum domain, int search) [static, read]
Definition at line 248 of file cp-namespace.c.
References cp_is_anonymous(), and lookup_symbol_file().
Referenced by cp_lookup_nested_symbol(), cp_lookup_symbol_imports(), cp_lookup_symbol_namespace(), find_symbol_in_baseclass(), and lookup_namespace_scope().
struct symbol* cp_lookup_symbol_namespace (const char * scope, const char * name, const struct block * block, const domain_enum domain) [read]
Definition at line 522 of file cp-namespace.c.
References BLOCK_SUPERBLOCK, cp_lookup_symbol_imports(), and cp_lookup_symbol_in_namespace().
Referenced by cp_lookup_symbol_nonlocal(), evaluate_subexp_standard(), and gen_maybe_namespace_elt().
struct symbol* cp_lookup_symbol_nonlocal (const char * name, const struct block * block, const domain_enum domain) [read]
Definition at line 227 of file cp-namespace.c.
References block_scope(), cp_lookup_symbol_namespace(), and lookup_namespace_scope().
struct type* cp_lookup_transparent_type (const char * name) [read]
Definition at line 854 of file cp-namespace.c.
References basic_lookup_transparent_type(), block_scope(), cp_lookup_transparent_type_loop(), and get_selected_block().
static struct type * cp_lookup_transparent_type_loop (const char * name, const char * scope, int scope_len) [static, read]
Definition at line 878 of file cp-namespace.c.
References basic_lookup_transparent_type(), and cp_find_first_component().
Referenced by cp_lookup_transparent_type().
void cp_scan_for_anonymous_namespaces (const struct symbol *const symbol, struct objfile *const objfile)
Definition at line 56 of file cp-namespace.c.
References cp_add_using_directive(), CP_ANONYMOUS_NAMESPACE_LEN, CP_ANONYMOUS_NAMESPACE_STR, cp_find_first_component(), cp_is_anonymous(), memcpy(), name, objfile::objfile_obstack, and SYMBOL_DEMANGLED_NAME.
Referenced by define_symbol(), and new_symbol_full().
static struct symbol* find_symbol_in_baseclass (struct type * parent_type, const char * name, const struct block * block) [static, read]
Definition at line 710 of file cp-namespace.c.
References CHECK_TYPEDEF, cp_lookup_symbol_in_namespace(), do_cleanups(), free_current_contents(), len, lookup_static_symbol_aux(), lookup_symbol_static(), make_cleanup(), TYPE_BASECLASS, TYPE_BASECLASS_NAME, TYPE_N_BASECLASSES, VAR_DOMAIN, xrealloc(), and xsnprintf().
Referenced by cp_lookup_nested_symbol().
static struct symbol * lookup_namespace_scope (const char * name, const struct block * block, const domain_enum domain, const char * scope, int scope_len) [static, read]
Definition at line 567 of file cp-namespace.c.
References cp_find_first_component(), cp_lookup_symbol_in_namespace(), and gdb_assert.
Referenced by cp_lookup_symbol_nonlocal().
static struct symbol * lookup_symbol_file (const char * name, const struct block * block, const domain_enum domain, int anonymous_namespace, int search) [static, read]
Definition at line 612 of file cp-namespace.c.
References block_global_block(), check_typedef(), cp_entire_prefix_len(), cp_lookup_nested_symbol(), do_cleanups(), language_cplus, language_def(), lookup_language_this(), lookup_symbol_aux_block(), lookup_symbol_global(), lookup_symbol_static(), make_cleanup(), null_cleanup(), savestring(), SYMBOL_TYPE, type, TYPE_NAME, TYPE_TARGET_TYPE, and xfree().
Referenced by cp_lookup_symbol_in_namespace().
static void maintenance_cplus_namespace (char * args, int from_tty) [static]
Definition at line 909 of file cp-namespace.c.
References _, and printf_unfiltered().
Referenced by _initialize_cp_namespace().
static void reset_directive_searched (void * data) [static]
Definition at line 274 of file cp-namespace.c.
References using_direct::searched.
Referenced by cp_lookup_symbol_imports().
static struct symbol* search_symbol_list (const char * name, int num, struct symbol ** syms) [static, read]
Definition at line 426 of file cp-namespace.c.
References SYMBOL_NATURAL_NAME.
Referenced by cp_lookup_symbol_imports_or_template().
Variable Documentation
initialize_file_ftype _initialize_cp_namespace
Referenced by initialize_all_files().