GDB (xrefs): /home/stan/gdb/src/gdb/cp-support.h File Reference
/home/stan/gdb/src/gdb/cp-support.h File Reference
#include "symtab.h"
#include "vec.h"
#include "gdb_vecs.h"
#include "gdb_obstack.h"
Classes
struct demangle_parse_info
struct using_direct
Defines
#define CP_ANONYMOUS_NAMESPACE_STR "(anonymous namespace)"
#define CP_ANONYMOUS_NAMESPACE_LEN 21
Typedefs
typedef const char *(canonicalization_ftype)(struct type *, void *)
Functions
char * cp_canonicalize_string (const char *string)
char * cp_canonicalize_string_no_typedefs (const char *string)
char * cp_canonicalize_string_full (const char *string, canonicalization_ftype *finder, void *data)
char * cp_class_name_from_physname (const char *physname)
char * method_name_from_physname (const char *physname)
unsigned int cp_find_first_component (const char *name)
unsigned int cp_entire_prefix_len (const char *name)
char * cp_func_name (const char *full_name)
char * cp_remove_params (const char *demangled_name)
struct symbol ** make_symbol_overload_list (const char *, const char *)
struct symbol ** make_symbol_overload_list_adl (struct type **arg_types, int nargs, const char *func_name)
struct type * cp_lookup_rtti_type (const char *name, struct block *block)
int cp_is_anonymous (const char *namespace)
void cp_add_using_directive (const char *dest, const char *src, const char *alias, const char *declaration, VEC(const_char_ptr)*excludes, int copy_names, struct obstack *obstack)
void cp_scan_for_anonymous_namespaces (const struct symbol *symbol, struct objfile *objfile)
struct symbol * cp_lookup_symbol_nonlocal (const char *name, const struct block *block, const domain_enum domain)
struct symbol * cp_lookup_symbol_namespace (const char *namespace, const char *name, const struct block *block, const domain_enum domain)
struct symbol * cp_lookup_symbol_imports (const char *scope, const char *name, const struct block *block, const domain_enum domain, const int declaration_only, const int search_parents)
struct symbol * cp_lookup_symbol_imports_or_template (const char *scope, const char *name, const struct block *block, const domain_enum domain)
struct symbol * cp_lookup_nested_symbol (struct type *parent_type, const char *nested_name, const struct block *block)
struct type * cp_lookup_transparent_type (const char *name)
struct demangle_parse_info * cp_demangled_name_to_comp (const char *demangled_name, const char **errmsg)
char * cp_comp_to_string (struct demangle_component *result, int estimated_len)
void cp_demangled_name_parse_free (struct demangle_parse_info *)
struct cleanup * make_cleanup_cp_demangled_name_parse_free (struct demangle_parse_info *)
void cp_merge_demangle_parse_infos (struct demangle_parse_info *, struct demangle_component *, struct demangle_parse_info *)
struct demangle_parse_info * cp_new_demangle_parse_info (void)
char * gdb_demangle (const char *name, int options)
Variables
struct cmd_list_element * maint_cplus_cmd_list
Define Documentation
#define CP_ANONYMOUS_NAMESPACE_LEN 21
Definition at line 46 of file cp-support.h.
Referenced by cp_scan_for_anonymous_namespaces().
#define CP_ANONYMOUS_NAMESPACE_STR "(anonymous namespace)"
Definition at line 42 of file cp-support.h.
Referenced by cp_is_anonymous(), cp_scan_for_anonymous_namespaces(), fixup_partial_die(), and namespace_name().
Typedef Documentation
typedef const char*(canonicalization_ftype)(struct type *, void *)
Definition at line 152 of file cp-support.h.
Function Documentation
void cp_add_using_directive (const char * dest, const char * src, const char * alias, const char * declaration, VEC(const_char_ptr)* excludes, int copy_names, struct obstack * obstack)
Definition at line 127 of file cp-namespace.c.
References using_direct::alias, using_direct::declaration, using_direct::excludes, using_direct::import_dest, using_direct::import_src, memcpy(), memset(), using_direct::next, using_directives, VEC_address, VEC_iterate, and VEC_length.
Referenced by cp_scan_for_anonymous_namespaces(), read_import_statement(), and read_namespace().
char* cp_canonicalize_string (const char * string)
Definition at line 571 of file cp-support.c.
References _, cp_already_canonical(), cp_comp_to_string(), cp_demangled_name_parse_free(), cp_demangled_name_to_comp(), demangle_parse_info::info, demangle_parse_info::tree, warning(), and xfree().
Referenced by check_status_exception_catchpoint(), define_symbol(), demangle_for_lookup(), dwarf2_canonicalize_name(), gnuv3_get_typeid(), lookup_minimal_symbol_internal(), read_dbx_symtab(), and read_type().
char* cp_canonicalize_string_full (const char * string, canonicalization_ftype * finder, void * data)
Definition at line 522 of file cp-support.c.
References cp_comp_to_string(), cp_demangled_name_parse_free(), cp_demangled_name_to_comp(), gdb_assert, demangle_parse_info::info, replace_typedefs(), demangle_parse_info::tree, and xfree().
Referenced by cp_canonicalize_string_no_typedefs(), and print_name_maybe_canonical().
char* cp_canonicalize_string_no_typedefs (const char * string)
Definition at line 561 of file cp-support.c.
References cp_canonicalize_string_full().
Referenced by find_linespec_symbols(), and inspect_type().
char* cp_class_name_from_physname (const char * physname)
Definition at line 657 of file cp-support.c.
References cp_comp_to_string(), cp_demangled_name_parse_free(), d_left, d_right, demangle_parse_info::info, mangled_name_to_comp(), demangle_parse_info::tree, and xfree().
char* cp_comp_to_string (struct demangle_component * result, int estimated_len)
Definition at line 4593 of file cp-name-parser.c.
Referenced by cp_canonicalize_string(), cp_canonicalize_string_full(), cp_class_name_from_physname(), cp_func_name(), cp_remove_params(), method_name_from_physname(), replace_typedefs(), replace_typedefs_qualified_name(), and typy_lookup_type().
void cp_demangled_name_parse_free (struct demangle_parse_info *)
Definition at line 4620 of file cp-name-parser.c.
References demangle_parse_info::info, demangle_info::next, demangle_parse_info::obstack, and xfree().
Referenced by cp_canonicalize_string(), cp_canonicalize_string_full(), cp_class_name_from_physname(), cp_demangled_name_to_comp(), cp_func_name(), cp_merge_demangle_parse_infos(), cp_remove_params(), do_demangled_name_parse_free_cleanup(), and method_name_from_physname().
struct demangle_parse_info* cp_demangled_name_to_comp (const char * demangled_name, const char ** errmsg) [read]
Definition at line 4681 of file cp-name-parser.c.
References allocate_info(), cp_demangled_name_parse_free(), cp_new_demangle_parse_info(), demangle_info, error_lexptr, global_errmsg, global_result, demangle_parse_info::info, lexptr, prev_lexptr, demangle_parse_info::tree, and yyparse.
Referenced by cp_canonicalize_string(), cp_canonicalize_string_full(), cp_func_name(), cp_remove_params(), inspect_type(), mangled_name_to_comp(), and typy_legacy_template_argument().
unsigned int cp_entire_prefix_len (const char * name)
Definition at line 1098 of file cp-support.c.
References cp_find_first_component(), and gdb_assert.
Referenced by cp_lookup_symbol_imports_or_template(), cp_set_block_scope(), lookup_symbol_file(), and make_symbol_overload_list_adl_namespace().
unsigned int cp_find_first_component (const char * name)
Definition at line 948 of file cp-support.c.
References cp_find_first_component_aux().
Referenced by cp_entire_prefix_len(), cp_lookup_transparent_type_loop(), cp_scan_for_anonymous_namespaces(), find_oload_champ_namespace_loop(), first_component_command(), and lookup_namespace_scope().
char* cp_func_name (const char * full_name)
Definition at line 839 of file cp-support.c.
References cp_comp_to_string(), cp_demangled_name_parse_free(), cp_demangled_name_to_comp(), demangle_parse_info::info, demangle_parse_info::tree, and unqualified_name_from_comp().
Referenced by find_overload_match().
int cp_is_anonymous (const char * namespace)
Definition at line 212 of file cp-namespace.c.
References CP_ANONYMOUS_NAMESPACE_STR, and strstr().
Referenced by cp_lookup_symbol_in_namespace(), and cp_scan_for_anonymous_namespaces().
struct symbol* cp_lookup_nested_symbol (struct type * parent_type, const char * nested_name, const struct block * block) [read]
Definition at line 772 of file cp-namespace.c.
References _, CHECK_TYPEDEF, cp_lookup_symbol_in_namespace(), find_symbol_in_baseclass(), internal_error(), lookup_static_symbol_aux(), size, TYPE_CODE, TYPE_CODE_FUNC, TYPE_CODE_METHOD, TYPE_CODE_NAMESPACE, TYPE_CODE_STRUCT, TYPE_CODE_UNION, type_name_no_tag_or_error(), VAR_DOMAIN, and xsnprintf().
Referenced by classify_inner_name(), and lookup_symbol_file().
struct type* cp_lookup_rtti_type (const char * name, struct block * block) [read]
Definition at line 1437 of file cp-support.c.
References _, LOC_TYPEDEF, lookup_symbol(), STRUCT_DOMAIN, SYMBOL_CLASS, SYMBOL_TYPE, TYPE_CODE, TYPE_CODE_CLASS, TYPE_CODE_NAMESPACE, and warning().
Referenced by gnuv2_value_rtti_type(), and gnuv3_rtti_type().
struct symbol* cp_lookup_symbol_imports (const char * scope, const char * name, const struct block * block, const domain_enum domain, const int declaration_only, const int search_parents) [read]
Definition at line 306 of file cp-namespace.c.
References using_direct::alias, block_using(), cp_lookup_symbol_imports(), cp_lookup_symbol_in_namespace(), using_direct::declaration, discard_cleanups(), using_direct::excludes, using_direct::import_dest, using_direct::import_src, len, make_cleanup(), using_direct::next, reset_directive_searched(), and using_direct::searched.
Referenced by cp_lookup_symbol_imports(), cp_lookup_symbol_imports_or_template(), and cp_lookup_symbol_namespace().
struct symbol* cp_lookup_symbol_imports_or_template (const char * scope, const char * name, const struct block * block, const domain_enum domain) [read]
Definition at line 445 of file cp-namespace.c.
References BLOCK_FUNCTION, BLOCK_SUPERBLOCK, cp_entire_prefix_len(), cp_lookup_symbol_imports(), do_cleanups(), get_objfile_arch(), language_cplus, language_def(), lookup_typename(), make_cleanup(), template_symbol::n_template_arguments, search_symbol_list(), SYMBOL_IS_CPLUS_TEMPLATE_FUNCTION, SYMBOL_LANGUAGE, SYMBOL_NATURAL_NAME, SYMBOL_SYMTAB, template_symbol::template_arguments, TYPE_N_TEMPLATE_ARGUMENTS, TYPE_TEMPLATE_ARGUMENTS, and xfree().
Referenced by lookup_symbol_aux_local().
struct symbol* cp_lookup_symbol_namespace (const char * namespace, const char * name, const struct block * block, const domain_enum domain) [read]
Definition at line 522 of file cp-namespace.c.
References BLOCK_SUPERBLOCK, cp_lookup_symbol_imports(), and cp_lookup_symbol_in_namespace().
Referenced by cp_lookup_symbol_nonlocal(), evaluate_subexp_standard(), and gen_maybe_namespace_elt().
struct symbol* cp_lookup_symbol_nonlocal (const char * name, const struct block * block, const domain_enum domain) [read]
Definition at line 227 of file cp-namespace.c.
References block_scope(), cp_lookup_symbol_namespace(), and lookup_namespace_scope().
struct type* cp_lookup_transparent_type (const char * name) [read]
Definition at line 854 of file cp-namespace.c.
References basic_lookup_transparent_type(), block_scope(), cp_lookup_transparent_type_loop(), and get_selected_block().
void cp_merge_demangle_parse_infos (struct demangle_parse_info * , struct demangle_component * , struct demangle_parse_info *)
Definition at line 4652 of file cp-name-parser.c.
References cp_demangled_name_parse_free(), demangle_parse_info::info, demangle_info::next, and demangle_parse_info::tree.
Referenced by inspect_type().
struct demangle_parse_info* cp_new_demangle_parse_info (void) [read]
Definition at line 4605 of file cp-name-parser.c.
References demangle_parse_info::info, demangle_parse_info::obstack, demangle_parse_info::tree, and xmalloc().
Referenced by cp_demangled_name_to_comp(), and mangled_name_to_comp().
char* cp_remove_params (const char * demangled_name)
Definition at line 864 of file cp-support.c.
References cp_comp_to_string(), cp_demangled_name_parse_free(), cp_demangled_name_to_comp(), d_left, demangle_parse_info::info, and demangle_parse_info::tree.
Referenced by find_frame_funname(), frame_info(), overload_list_add_symbol(), and psymtab_search_name().
void cp_scan_for_anonymous_namespaces (const struct symbol * symbol, struct objfile * objfile)
Definition at line 56 of file cp-namespace.c.
References cp_add_using_directive(), CP_ANONYMOUS_NAMESPACE_LEN, CP_ANONYMOUS_NAMESPACE_STR, cp_find_first_component(), cp_is_anonymous(), memcpy(), name, objfile::objfile_obstack, and SYMBOL_DEMANGLED_NAME.
Referenced by define_symbol(), and new_symbol_full().
char* gdb_demangle (const char * name, int options)
Definition at line 1480 of file cp-support.c.
Referenced by c_type_print_base(), check_stub_method(), demangle_for_lookup(), dwarf2_name(), dwarf2_physname(), fixup_partial_die(), gnuv3_print_method_ptr(), java_demangle(), java_type_print_base(), mangled_name_to_comp(), symbol_find_demangled_name(), and unk_lang_demangle().
struct cleanup* make_cleanup_cp_demangled_name_parse_free (struct demangle_parse_info *) [read]
Definition at line 112 of file cp-support.c.
References do_demangled_name_parse_free_cleanup(), and make_cleanup().
Referenced by typy_legacy_template_argument().
struct symbol** make_symbol_overload_list (const char * , const char *) [read]
Definition at line 1170 of file cp-support.c.
References discard_cleanups(), make_cleanup(), make_symbol_overload_list_qualified(), make_symbol_overload_list_using(), name, sym_return_val, sym_return_val_index, sym_return_val_size, xfree(), and xmalloc().
Referenced by find_oload_champ_namespace_loop().
struct symbol** make_symbol_overload_list_adl (struct type ** arg_types, int nargs, const char * func_name) [read]
Definition at line 1308 of file cp-support.c.
References gdb_assert, make_symbol_overload_list_adl_namespace(), sym_return_val, and sym_return_val_size.
Referenced by find_oload_champ_namespace_loop().
char* method_name_from_physname (const char * physname)
Definition at line 806 of file cp-support.c.
References cp_comp_to_string(), cp_demangled_name_parse_free(), demangle_parse_info::info, mangled_name_to_comp(), demangle_parse_info::tree, unqualified_name_from_comp(), and xfree().
Referenced by stabs_method_name_from_physname().
Variable Documentation
struct cmd_list_element* maint_cplus_cmd_list
Definition at line 67 of file cp-support.c.
Referenced by _initialize_cp_namespace().