GDB (xrefs): /home/stan/gdb/src/gdb/ctf.h File Reference
/home/stan/gdb/src/gdb/ctf.h File Reference
Functions
struct trace_file_writer * ctf_trace_file_writer_new (void)
Function Documentation
struct trace_file_writer* ctf_trace_file_writer_new (void) [read]
Definition at line 861 of file ctf.c.
References ctf_trace_file_writer::base, ctf_write_ops, trace_file_writer::ops, and xmalloc().
Referenced by trace_save_command(), and trace_save_ctf().