GDB (xrefs): /home/stan/gdb/src/gdb/ctf.c File Reference
/home/stan/gdb/src/gdb/ctf.c File Reference
#include "defs.h"
#include "ctf.h"
#include "tracepoint.h"
#include "regcache.h"
#include "gdb_stat.h"
#include "exec.h"
#include "completer.h"
#include <ctype.h>
Classes
struct trace_write_handler
struct ctf_trace_file_writer
Defines
#define CTF_MAGIC 0xC1FC1FC1
#define CTF_SAVE_MAJOR 1
#define CTF_SAVE_MINOR 8
#define CTF_METADATA_NAME "metadata"
#define CTF_DATASTREAM_NAME "datastream"
#define CTF_EVENT_ID_REGISTER 0
#define CTF_EVENT_ID_TSV 1
#define CTF_EVENT_ID_MEMORY 2
#define CTF_EVENT_ID_FRAME 3
#define CTF_EVENT_ID_STATUS 4
#define CTF_EVENT_ID_TSV_DEF 5
#define CTF_EVENT_ID_TP_DEF 6
#define ctf_save_write_uint32(HANDLER, U32) ctf_save_write (HANDLER, (gdb_byte *) &U32, 4)
#define ctf_save_write_int32(HANDLER, INT32) ctf_save_write ((HANDLER), (gdb_byte *) &(INT32), 4)
#define HOST_ENDIANNESS "le"
#define CTF_FILE_MIN_SIZE 4096
Functions
static void ctf_save_write_metadata (struct trace_write_handler *handler, const char *format,...)
static int ctf_save_write (struct trace_write_handler *handler, const gdb_byte *buf, size_t size)
static int ctf_save_fseek (struct trace_write_handler *handler, long offset, int whence)
static int ctf_save_align_write (struct trace_write_handler *handler, const gdb_byte *buf, size_t size, size_t align_size)
static void ctf_save_next_packet (struct trace_write_handler *handler)
static void ctf_save_metadata_header (struct trace_write_handler *handler)
static void ctf_dtor (struct trace_file_writer *self)
static int ctf_target_save (struct trace_file_writer *self, const char *dirname)
static void ctf_start (struct trace_file_writer *self, const char *dirname)
static void ctf_write_header (struct trace_file_writer *self)
static void ctf_write_regblock_type (struct trace_file_writer *self, int size)
static void ctf_write_status (struct trace_file_writer *self, struct trace_status *ts)
static void ctf_write_uploaded_tsv (struct trace_file_writer *self, struct uploaded_tsv *tsv)
static void ctf_write_uploaded_tp (struct trace_file_writer *self, struct uploaded_tp *tp)
static void ctf_write_definition_end (struct trace_file_writer *self)
static void ctf_end (struct trace_file_writer *self)
static void ctf_write_frame_start (struct trace_file_writer *self, uint16_t tpnum)
static void ctf_write_frame_r_block (struct trace_file_writer *self, gdb_byte *buf, int32_t size)
static void ctf_write_frame_m_block_header (struct trace_file_writer *self, uint64_t addr, uint16_t length)
static void ctf_write_frame_m_block_memory (struct trace_file_writer *self, gdb_byte *buf, uint16_t length)
static void ctf_write_frame_v_block (struct trace_file_writer *self, int32_t num, uint64_t val)
static void ctf_write_frame_end (struct trace_file_writer *self)
struct trace_file_writer * ctf_trace_file_writer_new (void)
void _initialize_ctf (void)
Variables
static struct trace_frame_write_ops ctf_write_frame_ops
static struct trace_file_write_ops ctf_write_ops
initialize_file_ftype _initialize_ctf
Define Documentation
#define CTF_DATASTREAM_NAME "datastream"
Definition at line 67 of file ctf.c.
Referenced by ctf_start().
#define CTF_EVENT_ID_FRAME 3
Definition at line 74 of file ctf.c.
Referenced by ctf_write_frame_start(), and ctf_write_header().
#define CTF_EVENT_ID_MEMORY 2
Definition at line 73 of file ctf.c.
Referenced by ctf_write_frame_m_block_header(), and ctf_write_header().
#define CTF_EVENT_ID_REGISTER 0
Definition at line 71 of file ctf.c.
Referenced by ctf_write_frame_r_block(), and ctf_write_regblock_type().
#define CTF_EVENT_ID_STATUS 4
Definition at line 75 of file ctf.c.
Referenced by ctf_write_status().
#define CTF_EVENT_ID_TP_DEF 6
Definition at line 77 of file ctf.c.
Referenced by ctf_write_header(), and ctf_write_uploaded_tp().
#define CTF_EVENT_ID_TSV 1
Definition at line 72 of file ctf.c.
Referenced by ctf_write_frame_v_block(), and ctf_write_header().
#define CTF_EVENT_ID_TSV_DEF 5
Definition at line 76 of file ctf.c.
Referenced by ctf_write_header(), and ctf_write_uploaded_tsv().
#define CTF_FILE_MIN_SIZE 4096
Definition at line 635 of file ctf.c.
Referenced by ctf_end().
#define CTF_MAGIC 0xC1FC1FC1
Definition at line 62 of file ctf.c.
Referenced by ctf_end(), and ctf_write_frame_start().
#define CTF_METADATA_NAME "metadata"
Definition at line 66 of file ctf.c.
Referenced by ctf_start().
#define CTF_SAVE_MAJOR 1
Definition at line 63 of file ctf.c.
Referenced by ctf_save_metadata_header().
#define CTF_SAVE_MINOR 8
Definition at line 64 of file ctf.c.
Referenced by ctf_save_metadata_header().
#define ctf_save_write_int32 (HANDLER, INT32) ctf_save_write ((HANDLER), (gdb_byte *) &(INT32), 4)
Definition at line 135 of file ctf.c.
Referenced by ctf_write_status(), ctf_write_uploaded_tp(), and ctf_write_uploaded_tsv().
#define ctf_save_write_uint32 (HANDLER, U32) ctf_save_write (HANDLER, (gdb_byte *) &U32, 4)
Definition at line 129 of file ctf.c.
Referenced by ctf_end(), ctf_write_frame_end(), and ctf_write_frame_start().
#define HOST_ENDIANNESS "le"
Referenced by ctf_save_metadata_header().
Function Documentation
void _initialize_ctf (void)
Definition at line 1857 of file ctf.c.
References add_target_with_completer().
static void ctf_dtor (struct trace_file_writer * self) [static]
Definition at line 275 of file ctf.c.
References trace_write_handler::datastream_fd, trace_write_handler::metadata_fd, and ctf_trace_file_writer::tcs.
static void ctf_end (struct trace_file_writer * self) [static]
Definition at line 641 of file ctf.c.
References trace_write_handler::content_size, CTF_FILE_MIN_SIZE, CTF_MAGIC, ctf_save_fseek(), ctf_save_write(), ctf_save_write_uint32, gdb_assert, trace_write_handler::packet_start, and ctf_trace_file_writer::tcs.
static int ctf_save_align_write (struct trace_write_handler * handler, const gdb_byte * buf, size_t size, size_t align_size) [static]
Definition at line 163 of file ctf.c.
References align_up(), trace_write_handler::content_size, ctf_save_fseek(), ctf_save_write(), and offset.
Referenced by ctf_write_frame_m_block_header(), ctf_write_frame_m_block_memory(), ctf_write_frame_r_block(), ctf_write_frame_start(), ctf_write_frame_v_block(), ctf_write_status(), ctf_write_uploaded_tp(), and ctf_write_uploaded_tsv().
static int ctf_save_fseek (struct trace_write_handler * handler, long offset, int whence) [static]
Definition at line 142 of file ctf.c.
References _, trace_write_handler::content_size, trace_write_handler::datastream_fd, error(), gdb_assert, offset, trace_write_handler::packet_start, and safe_strerror().
Referenced by ctf_end(), ctf_save_align_write(), ctf_save_next_packet(), ctf_write_frame_end(), and ctf_write_frame_start().
static void ctf_save_metadata_header (struct trace_write_handler * handler) [static]
Definition at line 193 of file ctf.c.
References CTF_SAVE_MAJOR, CTF_SAVE_MINOR, ctf_save_write_metadata(), and HOST_ENDIANNESS.
Referenced by ctf_start().
static void ctf_save_next_packet (struct trace_write_handler * handler) [static]
Definition at line 183 of file ctf.c.
References trace_write_handler::content_size, ctf_save_fseek(), and trace_write_handler::packet_start.
Referenced by ctf_write_frame_end().
static int ctf_save_write (struct trace_write_handler * handler, const gdb_byte * buf, size_t size) [static]
Definition at line 114 of file ctf.c.
References _, trace_write_handler::content_size, trace_write_handler::datastream_fd, error(), safe_strerror(), and size.
Referenced by ctf_end(), ctf_save_align_write(), ctf_write_frame_start(), ctf_write_uploaded_tp(), and ctf_write_uploaded_tsv().
static void ctf_save_write_metadata (struct trace_write_handler * handler, const char * format, ...) [static]
Definition at line 98 of file ctf.c.
References _, error(), trace_write_handler::metadata_fd, and safe_strerror().
Referenced by ctf_save_metadata_header(), ctf_write_header(), ctf_write_regblock_type(), and ctf_write_status().
static void ctf_start (struct trace_file_writer * self, const char * dirname) [static]
Definition at line 309 of file ctf.c.
References _, CTF_DATASTREAM_NAME, CTF_METADATA_NAME, ctf_save_metadata_header(), trace_write_handler::datastream_fd, do_cleanups(), error(), make_cleanup(), memset(), trace_write_handler::metadata_fd, safe_strerror(), ctf_trace_file_writer::tcs, xfree(), and xstrprintf().
static int ctf_target_save (struct trace_file_writer * self, const char * dirname) [static]
Definition at line 292 of file ctf.c.
struct trace_file_writer* ctf_trace_file_writer_new (void) [read]
Definition at line 861 of file ctf.c.
References ctf_trace_file_writer::base, ctf_write_ops, trace_file_writer::ops, and xmalloc().
Referenced by trace_save_command(), and trace_save_ctf().
static void ctf_write_definition_end (struct trace_file_writer * self) [static]
Definition at line 624 of file ctf.c.
static void ctf_write_frame_end (struct trace_file_writer * self) [static]
Definition at line 796 of file ctf.c.
References trace_write_handler::content_size, ctf_save_fseek(), ctf_save_next_packet(), ctf_save_write_uint32, trace_write_handler::packet_start, and ctf_trace_file_writer::tcs.
static void ctf_write_frame_m_block_header (struct trace_file_writer * self, uint64_t addr, uint16_t length) [static]
Definition at line 741 of file ctf.c.
References CTF_EVENT_ID_MEMORY, ctf_save_align_write(), and ctf_trace_file_writer::tcs.
static void ctf_write_frame_m_block_memory (struct trace_file_writer * self, gdb_byte * buf, uint16_t length) [static]
Definition at line 762 of file ctf.c.
References ctf_save_align_write(), and ctf_trace_file_writer::tcs.
static void ctf_write_frame_r_block (struct trace_file_writer * self, gdb_byte * buf, int32_t size) [static]
Definition at line 723 of file ctf.c.
References CTF_EVENT_ID_REGISTER, ctf_save_align_write(), and ctf_trace_file_writer::tcs.
static void ctf_write_frame_start (struct trace_file_writer * self, uint16_t tpnum) [static]
Definition at line 696 of file ctf.c.
References CTF_EVENT_ID_FRAME, CTF_MAGIC, ctf_save_align_write(), ctf_save_fseek(), ctf_save_write(), ctf_save_write_uint32, and ctf_trace_file_writer::tcs.
static void ctf_write_frame_v_block (struct trace_file_writer * self, int32_t num, uint64_t val) [static]
Definition at line 776 of file ctf.c.
References CTF_EVENT_ID_TSV, ctf_save_align_write(), and ctf_trace_file_writer::tcs.
static void ctf_write_header (struct trace_file_writer * self) [static]
Definition at line 361 of file ctf.c.
References trace_write_handler::content_size, CTF_EVENT_ID_FRAME, CTF_EVENT_ID_MEMORY, CTF_EVENT_ID_TP_DEF, CTF_EVENT_ID_TSV, CTF_EVENT_ID_TSV_DEF, ctf_save_write_metadata(), gdb_assert, trace_write_handler::packet_start, and ctf_trace_file_writer::tcs.
static void ctf_write_regblock_type (struct trace_file_writer * self, int size) [static]
Definition at line 444 of file ctf.c.
References CTF_EVENT_ID_REGISTER, ctf_save_write_metadata(), and ctf_trace_file_writer::tcs.
static void ctf_write_status (struct trace_file_writer * self, struct trace_status * ts) [static]
Definition at line 464 of file ctf.c.
References trace_status::buffer_free, trace_status::buffer_size, trace_status::circular_buffer, CTF_EVENT_ID_STATUS, ctf_save_align_write(), ctf_save_write_int32, ctf_save_write_metadata(), trace_status::disconnected_tracing, trace_status::stop_reason, trace_status::stopping_tracepoint, ctf_trace_file_writer::tcs, trace_status::traceframe_count, and trace_status::traceframes_created.
static void ctf_write_uploaded_tp (struct trace_file_writer * self, struct uploaded_tp * tp) [static]
Definition at line 541 of file ctf.c.
References uploaded_tp::addr, uploaded_tp::at_string, uploaded_tp::cond, uploaded_tp::cond_string, CTF_EVENT_ID_TP_DEF, ctf_save_align_write(), ctf_save_write(), ctf_save_write_int32, uploaded_tp::enabled, uploaded_tp::hit_count, uploaded_tp::number, uploaded_tp::pass, uploaded_tp::step, ctf_trace_file_writer::tcs, uploaded_tp::traceframe_usage, uploaded_tp::type, VEC_iterate, and VEC_length.
static void ctf_write_uploaded_tsv (struct trace_file_writer * self, struct uploaded_tsv * tsv) [static]
Definition at line 506 of file ctf.c.
References uploaded_tsv::builtin, CTF_EVENT_ID_TSV_DEF, ctf_save_align_write(), ctf_save_write(), ctf_save_write_int32, uploaded_tsv::initial_value, len, uploaded_tsv::name, uploaded_tsv::number, and ctf_trace_file_writer::tcs.
Variable Documentation
initialize_file_ftype _initialize_ctf
Referenced by initialize_all_files().
struct trace_frame_write_ops ctf_write_frame_ops [static]
Initial value:
{
  ctf_write_frame_start,
  ctf_write_frame_r_block,
  ctf_write_frame_m_block_header,
  ctf_write_frame_m_block_memory,
  ctf_write_frame_v_block,
  ctf_write_frame_end,
}
Definition at line 830 of file ctf.c.
struct trace_file_write_ops ctf_write_ops [static]
Initial value:
{
  ctf_dtor,
  ctf_target_save,
  ctf_start,
  ctf_write_header,
  ctf_write_regblock_type,
  ctf_write_status,
  ctf_write_uploaded_tsv,
  ctf_write_uploaded_tp,
  ctf_write_definition_end,
  NULL,
  &ctf_write_frame_ops,
  ctf_end,
}
Definition at line 842 of file ctf.c.
Referenced by ctf_trace_file_writer_new().