GDB (xrefs): /home/stan/gdb/src/gdb/d-lang.c File Reference
/home/stan/gdb/src/gdb/d-lang.c File Reference
#include "defs.h"
#include "symtab.h"
#include "language.h"
#include "d-lang.h"
#include "c-lang.h"
#include "gdb_string.h"
#include "parser-defs.h"
#include "gdb_obstack.h"
#include <ctype.h>
Functions
static int extract_identifiers (const char *mangled_str, struct obstack *tempbuf)
static int extract_type_info (const char *mangled_str, struct obstack *tempbuf)
char * d_demangle (const char *symbol, int options)
void _initialize_d_language (void)
Variables
static struct op_print d_op_print_tab []
static struct language_defn d_language_defn
initialize_file_ftype _initialize_d_language
Function Documentation
void _initialize_d_language (void)
Definition at line 284 of file d-lang.c.
References _initialize_d_language, and add_language().
char* d_demangle (const char * symbol, int options)
Definition at line 134 of file d-lang.c.
References extract_identifiers(), extract_type_info(), obstack_grow_str, and obstack_grow_str0.
Referenced by demangle_for_lookup(), and symbol_find_demangled_name().
static int extract_identifiers (const char * mangled_str, struct obstack * tempbuf) [static]
Definition at line 34 of file d-lang.c.
References obstack_grow_str.
Referenced by d_demangle(), and extract_type_info().
static int extract_type_info (const char * mangled_str, struct obstack * tempbuf) [static]
Definition at line 59 of file d-lang.c.
References extract_identifiers(), and obstack_grow_str.
Referenced by d_demangle().
Variable Documentation
initialize_file_ftype _initialize_d_language
Referenced by _initialize_d_language(), and initialize_all_files().
struct language_defn d_language_defn [static]
Definition at line 238 of file d-lang.c.
struct op_print d_op_print_tab[] [static]
Definition at line 204 of file d-lang.c.