GDB (xrefs): /home/stan/gdb/src/gdb/d-valprint.c File Reference
/home/stan/gdb/src/gdb/d-valprint.c File Reference
#include "defs.h"
#include "gdbtypes.h"
#include "gdbcore.h"
#include "d-lang.h"
#include "c-lang.h"
Functions
static int dynamic_array_type (struct type *type, const gdb_byte *valaddr, int embedded_offset, CORE_ADDR address, struct ui_file *stream, int recurse, const struct value *val, const struct value_print_options *options)
void d_val_print (struct type *type, const gdb_byte *valaddr, int embedded_offset, CORE_ADDR address, struct ui_file *stream, int recurse, const struct value *val, const struct value_print_options *options)
Function Documentation
void d_val_print (struct type * type, const gdb_byte * valaddr, int embedded_offset, CORE_ADDR address, struct ui_file * stream, int recurse, const struct value * val, const struct value_print_options * options)
Definition at line 74 of file d-valprint.c.
References c_val_print(), CHECK_TYPEDEF, dynamic_array_type(), TYPE_CODE, and TYPE_CODE_STRUCT.
Referenced by dynamic_array_type().
static int dynamic_array_type (struct type * type, const gdb_byte * valaddr, int embedded_offset, CORE_ADDR address, struct ui_file * stream, int recurse, const struct value * val, const struct value_print_options * options) [static]
Definition at line 31 of file d-valprint.c.
References check_typedef(), d_val_print(), lookup_array_range_type(), TYPE_CODE, TYPE_CODE_INT, TYPE_FIELD_BITPOS, TYPE_FIELD_NAME, TYPE_FIELD_TYPE, TYPE_LENGTH, TYPE_NFIELDS, TYPE_TARGET_TYPE, unpack_field_as_long(), unpack_pointer(), value_at(), value_bits_valid(), value_contents_for_printing(), and value_embedded_offset().
Referenced by d_val_print().