GDB (xrefs): /home/stan/gdb/src/gdb/darwin-nat-info.c File Reference
/home/stan/gdb/src/gdb/darwin-nat-info.c File Reference
#include "defs.h"
#include "symtab.h"
#include "gdbtypes.h"
#include "gdbcore.h"
#include "value.h"
#include "gdbcmd.h"
#include "inferior.h"
#include <sys/sysctl.h>
#include "darwin-nat.h"
#include <mach/thread_info.h>
#include <mach/thread_act.h>
#include <mach/task.h>
#include <mach/vm_map.h>
#include <mach/mach_port.h>
#include <mach/mach_init.h>
#include <mach/mach_vm.h>
Defines
#define CHECK_ARGS(what, args)
#define PRINT_FIELD(structure, field) printf_unfiltered(_(#field":\t%#lx\n"), (unsigned long) (structure)->field)
#define PRINT_TV_FIELD(structure, field)
#define task_self mach_task_self
#define task_by_unix_pid task_for_pid
#define port_name_array_t mach_port_array_t
#define port_type_array_t mach_port_array_t
Functions
static void info_mach_tasks_command (char *args, int from_tty)
static task_t get_task_from_args (char *args)
static void info_mach_task_command (char *args, int from_tty)
static void info_mach_ports_command (char *args, int from_tty)
static void darwin_debug_port_info (task_t task, mach_port_t port)
static void info_mach_port_command (char *args, int from_tty)
static void info_mach_threads_command (char *args, int from_tty)
static void info_mach_thread_command (char *args, int from_tty)
static const char * unparse_protection (vm_prot_t p)
static const char * unparse_inheritance (vm_inherit_t i)
static const char * unparse_share_mode (unsigned char p)
static const char * unparse_user_tag (unsigned int tag)
static void darwin_debug_regions (task_t task, mach_vm_address_t address, int max)
static void darwin_debug_regions_recurse (task_t task)
static void darwin_debug_region (task_t task, mach_vm_address_t address)
static void info_mach_regions_command (char *args, int from_tty)
static void info_mach_regions_recurse_command (char *args, int from_tty)
static void info_mach_region_command (char *exp, int from_tty)
static void disp_exception (const darwin_exception_info *info)
static void info_mach_exceptions_command (char *args, int from_tty)
void _initialize_darwin_info_commands (void)
Variables
initialize_file_ftype _initialize_darwin_info_commands
Define Documentation
#define CHECK_ARGS (what, args)
Value:
do { \
  if ((NULL == args) || ((args[0] != '0') && (args[1] != 'x'))) \
    error(_("%s must be specified with 0x..."), what);          \
} while (0)
Definition at line 50 of file darwin-nat-info.c.
Referenced by info_mach_port_command(), and info_mach_thread_command().
#define port_name_array_t mach_port_array_t
Definition at line 65 of file darwin-nat-info.c.
Referenced by info_mach_ports_command().
#define port_type_array_t mach_port_array_t
Definition at line 66 of file darwin-nat-info.c.
Referenced by info_mach_ports_command().
#define PRINT_FIELD (structure, field) printf_unfiltered(_(#field":\t%#lx\n"), (unsigned long) (structure)->field)
Definition at line 55 of file darwin-nat-info.c.
Referenced by info_mach_task_command(), and info_mach_thread_command().
#define PRINT_TV_FIELD (structure, field)
Value:
printf_unfiltered(_(#field":\t%u.%06u sec\n"),  \
  (unsigned) (structure)->field.seconds, \
  (unsigned) (structure)->field.microseconds)
Definition at line 58 of file darwin-nat-info.c.
Referenced by info_mach_task_command().
#define task_by_unix_pid task_for_pid
Definition at line 64 of file darwin-nat-info.c.
Referenced by info_mach_tasks_command().
#define task_self mach_task_self
Definition at line 63 of file darwin-nat-info.c.
Referenced by info_mach_ports_command(), and info_mach_threads_command().
Function Documentation
void _initialize_darwin_info_commands (void)
Definition at line 849 of file darwin-nat-info.c.
References _, _initialize_darwin_info_commands, add_info(), info_mach_exceptions_command(), info_mach_port_command(), info_mach_ports_command(), info_mach_region_command(), info_mach_regions_command(), info_mach_regions_recurse_command(), info_mach_task_command(), info_mach_tasks_command(), info_mach_thread_command(), and info_mach_threads_command().
static void darwin_debug_port_info (task_t task, mach_port_t port) [static]
Definition at line 304 of file darwin-nat-info.c.
References _, len, MACH_CHECK_ERROR, printf_unfiltered(), and exsummary::status.
Referenced by info_mach_port_command().
static void darwin_debug_region (task_t task, mach_vm_address_t address) [static]
Definition at line 696 of file darwin-nat-info.c.
References darwin_debug_regions().
Referenced by info_mach_region_command().
static void darwin_debug_regions (task_t task, mach_vm_address_t address, int max) [static]
Definition at line 512 of file darwin-nat-info.c.
References _, memcpy(), paddress(), printf_filtered(), size, target_gdbarch(), unparse_inheritance(), and unparse_protection().
Referenced by darwin_debug_region(), and info_mach_regions_command().
static void darwin_debug_regions_recurse (task_t task) [static]
Definition at line 610 of file darwin-nat-info.c.
References _, current_uiout, do_cleanups(), gdbarch_addr_bit(), make_cleanup_ui_out_table_begin_end(), make_cleanup_ui_out_tuple_begin_end(), target_gdbarch(), ui_left, ui_noalign, ui_out_field_core_addr(), ui_out_field_int(), ui_out_field_string(), ui_out_is_mi_like_p(), ui_out_table_body(), ui_out_table_header(), ui_out_text(), unparse_inheritance(), unparse_protection(), unparse_share_mode(), and unparse_user_tag().
Referenced by info_mach_regions_recurse_command().
static void disp_exception (const darwin_exception_info * info) [static]
Definition at line 749 of file darwin-nat-info.c.
References _, darwin_exception_info::behaviors, darwin_exception_info::count, darwin_exception_info::masks, darwin_exception_info::ports, printf_filtered(), and printf_unfiltered().
Referenced by info_mach_exceptions_command().
static task_t get_task_from_args (char * args) [static]
Definition at line 112 of file darwin-nat-info.c.
References _, current_inferior(), inferior_ptid, null_ptid, printf_unfiltered(), inferior::private, ptid_equal(), and private_inferior::task.
Referenced by info_mach_ports_command(), info_mach_regions_command(), info_mach_regions_recurse_command(), info_mach_task_command(), and info_mach_threads_command().
static void info_mach_exceptions_command (char * args, int from_tty) [static]
Definition at line 799 of file darwin-nat-info.c.
References _, darwin_exception_info::behaviors, darwin_exception_info::count, current_inferior(), darwin_host_self, disp_exception(), error(), private_inferior::exception_info, darwin_exception_info::flavors, arm-linux::inf, inferior_ptid, MACH_CHECK_ERROR, darwin_exception_info::masks, null_ptid, darwin_exception_info::ports, printf_unfiltered(), inferior::private, ptid_equal(), and private_inferior::task.
Referenced by _initialize_darwin_info_commands().
static void info_mach_port_command (char * args, int from_tty) [static]
Definition at line 329 of file darwin-nat-info.c.
References _, CHECK_ARGS, and darwin_debug_port_info().
Referenced by _initialize_darwin_info_commands().
static void info_mach_ports_command (char * args, int from_tty) [static]
Definition at line 192 of file darwin-nat-info.c.
References _, darwin_exception_info::count, current_inferior(), darwin_ex_port, darwin_host_self, darwin_port_set, private_inferior::exception_info, gdb_assert, private_thread_info::gdb_port, get_task_from_args(), inferior_ptid, MACH_CHECK_ERROR, name, private_inferior::notify_port, null_ptid, port_name_array_t, port_type_array_t, darwin_exception_info::ports, printf_unfiltered(), inferior::private, ptid_equal(), private_inferior::task, task_self, type, and VEC_iterate.
Referenced by _initialize_darwin_info_commands().
static void info_mach_region_command (char * exp, int from_tty) [static]
Definition at line 726 of file darwin-nat-info.c.
References _, value::address, current_inferior(), darwin_debug_region(), error(), evaluate_expression(), arm-linux::inf, inferior_ptid, null_ptid, parse_expression(), inferior::private, ptid_equal(), private_inferior::task, TYPE_CODE, TYPE_CODE_REF, value_as_address(), value_ind(), and value_type().
Referenced by _initialize_darwin_info_commands().
static void info_mach_regions_command (char * args, int from_tty) [static]
Definition at line 702 of file darwin-nat-info.c.
References darwin_debug_regions(), and get_task_from_args().
Referenced by _initialize_darwin_info_commands().
static void info_mach_regions_recurse_command (char * args, int from_tty) [static]
Definition at line 714 of file darwin-nat-info.c.
References darwin_debug_regions_recurse(), and get_task_from_args().
Referenced by _initialize_darwin_info_commands().
static void info_mach_task_command (char * args, int from_tty) [static]
Definition at line 135 of file darwin-nat-info.c.
References _, get_task_from_args(), MACH_CHECK_ERROR, PRINT_FIELD, PRINT_TV_FIELD, and printf_unfiltered().
Referenced by _initialize_darwin_info_commands().
static void info_mach_tasks_command (char * args, int from_tty) [static]
Definition at line 69 of file darwin-nat-info.c.
References _, printf_unfiltered(), task_by_unix_pid, xfree(), and xmalloc().
Referenced by _initialize_darwin_info_commands().
static void info_mach_thread_command (char * args, int from_tty) [static]
Definition at line 368 of file darwin-nat-info.c.
References _, CHECK_ARGS, flags, MACH_CHECK_ERROR, PRINT_FIELD, and printf_unfiltered().
Referenced by _initialize_darwin_info_commands().
static void info_mach_threads_command (char * args, int from_tty) [static]
Definition at line 341 of file darwin-nat-info.c.
References _, get_task_from_args(), MACH_CHECK_ERROR, printf_unfiltered(), task_self, and thread_count().
Referenced by _initialize_darwin_info_commands().
static const char* unparse_inheritance (vm_inherit_t i) [static]
Definition at line 428 of file darwin-nat-info.c.
References _.
Referenced by darwin_debug_regions(), and darwin_debug_regions_recurse().
static const char* unparse_protection (vm_prot_t p) [static]
Definition at line 402 of file darwin-nat-info.c.
Referenced by darwin_debug_regions(), and darwin_debug_regions_recurse().
static const char* unparse_share_mode (unsigned char p) [static]
Definition at line 444 of file darwin-nat-info.c.
References _.
Referenced by darwin_debug_regions_recurse().
static const char* unparse_user_tag (unsigned int tag) [static]
Definition at line 468 of file darwin-nat-info.c.
References _.
Referenced by darwin_debug_regions_recurse().
Variable Documentation
initialize_file_ftype _initialize_darwin_info_commands
Referenced by _initialize_darwin_info_commands().