GDB (xrefs): /home/stan/gdb/src/gdb/darwin-nat.h File Reference
/home/stan/gdb/src/gdb/darwin-nat.h File Reference
#include <mach/mach.h>
#include "gdb_assert.h"
Classes
struct darwin_exception_info
struct darwin_exception_msg
struct private_thread_info
struct private_inferior
Defines
#define MACH_CHECK_ERROR(ret) mach_check_error (ret, __FILE__, __LINE__, "??")
Typedefs
typedef struct
darwin_exception_info darwin_exception_info
typedef struct private_thread_info darwin_thread_t
typedef struct private_inferior darwin_inferior
Enumerations
enum darwin_msg_state { DARWIN_RUNNING, DARWIN_STOPPED, DARWIN_MESSAGE }
Functions
DEF_VEC_O (darwin_thread_t)
void mach_check_error (kern_return_t ret, const char *file, unsigned int line, const char *func)
void darwin_set_sstep (thread_t thread, int enable)
void darwin_complete_target (struct target_ops *target)
void darwin_check_osabi (darwin_inferior *inf, thread_t thread)
Variables
mach_port_t darwin_ex_port
mach_port_t darwin_port_set
mach_port_t darwin_host_self
Define Documentation
#define MACH_CHECK_ERROR (ret) mach_check_error (ret, __FILE__, __LINE__, "??")
Definition at line 144 of file darwin-nat.h.
Referenced by _initialize_darwin_inferior(), darwin_check_new_threads(), darwin_check_osabi(), darwin_debug_port_info(), darwin_decode_exception_message(), darwin_detach(), darwin_get_ada_task_ptid(), darwin_kill_inferior(), darwin_mourn_inferior(), darwin_resume_inferior(), darwin_resume_thread(), darwin_send_reply(), darwin_set_sstep(), darwin_setup_fake_stop_event(), darwin_suspend_inferior(), darwin_suspend_inferior_threads(), i386_darwin_dr_get(), i386_darwin_dr_set(), i386_darwin_fetch_inferior_registers(), i386_darwin_store_inferior_registers(), info_mach_exceptions_command(), info_mach_ports_command(), info_mach_task_command(), info_mach_thread_command(), info_mach_threads_command(), and set_enable_mach_exceptions().
Typedef Documentation
typedef struct darwin_exception_info darwin_exception_info
Definition at line 44 of file darwin-nat.h.
typedef struct private_inferior darwin_inferior
Definition at line 128 of file darwin-nat.h.
typedef struct private_thread_info darwin_thread_t
Definition at line 97 of file darwin-nat.h.
Enumeration Type Documentation
enum darwin_msg_state
Enumerator:
DARWIN_RUNNING
DARWIN_STOPPED
DARWIN_MESSAGE
Definition at line 62 of file darwin-nat.h.
Function Documentation
void darwin_check_osabi (darwin_inferior * inf, thread_t thread)
Definition at line 462 of file i386-darwin-nat.c.
References gdbarch_info::bfd_arch_info, gdbarch_info::byte_order, GDB_OSABI_DARWIN, GDB_OSABI_UNKNOWN, gdbarch_byte_order(), gdbarch_info_fill(), gdbarch_info_init(), gdbarch_osabi(), gdbarch_update_p(), MACH_CHECK_ERROR, gdbarch_info::osabi, and target_gdbarch().
Referenced by darwin_attach().
void darwin_complete_target (struct target_ops * target)
Definition at line 623 of file i386-darwin-nat.c.
References amd64_darwin_thread_state_num_regs, amd64_darwin_thread_state_reg_offset, amd64_native_gregset32_num_regs, amd64_native_gregset32_reg_offset, amd64_native_gregset64_num_regs, amd64_native_gregset64_reg_offset, i386_dr_low_type::get_addr, i386_dr_low_type::get_control, i386_dr_low_type::get_status, i386_darwin_dr_get_addr(), i386_darwin_dr_get_control(), i386_darwin_dr_get_status(), i386_darwin_dr_set_addr(), i386_darwin_dr_set_control(), i386_darwin_fetch_inferior_registers(), i386_darwin_store_inferior_registers(), i386_darwin_thread_state_num_regs, i386_darwin_thread_state_reg_offset, i386_dr_low, i386_set_debug_register_length(), i386_use_watchpoints(), i386_dr_low_type::set_addr, i386_dr_low_type::set_control, target_ops::to_fetch_registers, and target_ops::to_store_registers.
Referenced by _initialize_darwin_inferior().
void darwin_set_sstep (thread_t thread, int enable)
Definition at line 568 of file i386-darwin-nat.c.
References _, bit, error(), i386_darwin_sstep_at_sigreturn(), MACH_CHECK_ERROR, printf_unfiltered(), and X86_EFLAGS_T.
Referenced by darwin_resume_thread().
DEF_VEC_O (darwin_thread_t)
void mach_check_error (kern_return_t ret, const char * file, unsigned int line, const char * func)
Definition at line 192 of file darwin-nat.c.
References _, and warning().
Variable Documentation
mach_port_t darwin_ex_port
Definition at line 128 of file darwin-nat.c.
Referenced by darwin_attach_pid(), darwin_decode_message(), info_mach_ports_command(), and set_enable_mach_exceptions().
mach_port_t darwin_host_self
Definition at line 125 of file darwin-nat.c.
Referenced by _initialize_darwin_inferior(), info_mach_exceptions_command(), and info_mach_ports_command().
mach_port_t darwin_port_set
Definition at line 131 of file darwin-nat.c.
Referenced by darwin_attach_pid(), darwin_wait(), and info_mach_ports_command().