GDB (xrefs): /home/stan/gdb/src/gdb/dbug-rom.c File Reference
/home/stan/gdb/src/gdb/dbug-rom.c File Reference
#include "defs.h"
#include "gdbcore.h"
#include "target.h"
#include "monitor.h"
#include "serial.h"
#include "regcache.h"
#include "m68k-tdep.h"
Functions
static void dbug_open (char *args, int from_tty)
static void dbug_supply_register (struct regcache *regcache, char *regname, int regnamelen, char *val, int vallen)
static const char * dbug_regname (int index)
static void init_dbug_cmds (void)
void _initialize_dbug_rom (void)
Variables
static struct target_ops dbug_ops
static struct monitor_ops dbug_cmds
static char * dbug_inits []
initialize_file_ftype _initialize_dbug_rom
Function Documentation
void _initialize_dbug_rom (void)
Definition at line 166 of file dbug-rom.c.
References _initialize_dbug_rom, add_target(), dbug_open(), dbug_ops, init_dbug_cmds(), init_monitor_ops(), target_ops::to_doc, target_ops::to_longname, target_ops::to_open, and target_ops::to_shortname.
static void dbug_open (char * args, int from_tty) [static]
Definition at line 158 of file dbug-rom.c.
References dbug_cmds, and monitor_open().
Referenced by _initialize_dbug_rom().
static const char* dbug_regname (int index) [static]
Definition at line 82 of file dbug-rom.c.
Referenced by init_dbug_cmds().
static void dbug_supply_register (struct regcache * regcache, char * regname, int regnamelen, char * val, int vallen) [static]
Definition at line 38 of file dbug-rom.c.
References gdbarch_pc_regnum(), gdbarch_ps_regnum(), get_regcache_arch(), M68K_A0_REGNUM, M68K_D0_REGNUM, and monitor_supply_register().
Referenced by init_dbug_cmds().
static void init_dbug_cmds (void) [static]
Definition at line 107 of file dbug-rom.c.
References monitor_ops::clr_all_break, monitor_ops::clr_break, regrw_cmd::cmd, monitor_ops::cmd_end, memrw_cmd::cmdb, memrw_cmd::cmdl, memrw_cmd::cmdll, memrw_cmd::cmdw, monitor_ops::cont, dbug_cmds, dbug_inits, dbug_ops, dbug_regname(), dbug_supply_register(), monitor_ops::dump_registers, monitor_ops::fill, monitor_ops::flags, monitor_ops::getmem, monitor_ops::getreg, monitor_ops::init, monitor_ops::line_term, monitor_ops::load, monitor_ops::loadresp, monitor_ops::magic, MO_CLR_BREAK_USES_ADDR, MO_FILL_USES_ADDR, MO_GETMEM_NEEDS_RANGE, MONITOR_OPS_MAGIC, monitor_ops::prompt, monitor_ops::register_pattern, monitor_ops::regname, monitor_ops::regnames, memrw_cmd::resp_delim, regrw_cmd::resp_delim, SERIAL_1_STOPBITS, monitor_ops::set_break, monitor_ops::setmem, monitor_ops::setreg, monitor_ops::step, monitor_ops::stop, monitor_ops::stopbits, monitor_ops::supply_register, monitor_ops::target, memrw_cmd::term, regrw_cmd::term, memrw_cmd::term_cmd, and regrw_cmd::term_cmd.
Referenced by _initialize_dbug_rom().
Variable Documentation
initialize_file_ftype _initialize_dbug_rom
Referenced by _initialize_dbug_rom(), and initialize_all_files().
struct monitor_ops dbug_cmds [static]
Definition at line 100 of file dbug-rom.c.
Referenced by dbug_open(), and init_dbug_cmds().
char* dbug_inits[] [static]
Initial value:
{"\r", NULL}
Definition at line 102 of file dbug-rom.c.
Referenced by init_dbug_cmds().
struct target_ops dbug_ops [static]
Definition at line 99 of file dbug-rom.c.
Referenced by _initialize_dbug_rom(), and init_dbug_cmds().