GDB (xrefs): /home/stan/gdb/src/gdb/dbxread.c File Reference
/home/stan/gdb/src/gdb/dbxread.c File Reference
#include "defs.h"
#include "gdb_string.h"
#include "gdb_obstack.h"
#include "gdb_stat.h"
#include "symtab.h"
#include "breakpoint.h"
#include "target.h"
#include "gdbcore.h"
#include "libaout.h"
#include "filenames.h"
#include "objfiles.h"
#include "buildsym.h"
#include "stabsread.h"
#include "gdb-stabs.h"
#include "demangle.h"
#include "complaints.h"
#include "cp-abi.h"
#include "cp-support.h"
#include "psympriv.h"
#include "block.h"
#include "gdb_assert.h"
#include "aout/aout64.h"
#include "aout/stab_gnu.h"
Classes
struct symloc
struct header_file_location
Defines
#define LDSYMOFF(p) (((struct symloc *)((p)->read_symtab_private))->ldsymoff)
#define LDSYMLEN(p) (((struct symloc *)((p)->read_symtab_private))->ldsymlen)
#define SYMLOC(p) ((struct symloc *)((p)->read_symtab_private))
#define SYMBOL_SIZE(p) (SYMLOC(p)->symbol_size)
#define SYMBOL_OFFSET(p) (SYMLOC(p)->symbol_offset)
#define STRING_OFFSET(p) (SYMLOC(p)->string_offset)
#define FILE_STRING_OFFSET(p) (SYMLOC(p)->file_string_offset)
#define DBX_STRINGTAB_SIZE_SIZE sizeof(long) /* FIXME */
#define STRING_TABLE_OFFSET (sym_bfd->origin + obj_str_filepos (sym_bfd))
#define SYMBOL_TABLE_OFFSET (sym_bfd->origin + obj_sym_filepos (sym_bfd))
#define INTERNALIZE_SYMBOL(intern, extern, abfd)
#define COFF_STABS_SYMBOL_SIZE 12 /* XXX FIXME XXX */
#define ELF_STABS_SYMBOL_SIZE 12 /* XXX FIXME XXX */
Functions
static void unknown_symtype_complaint (const char *arg1)
static void lbrac_mismatch_complaint (int arg1)
static void repeated_header_complaint (const char *arg1, int arg2)
static void find_text_range (bfd *sym_bfd, struct objfile *objfile)
void _initialize_dbxread (void)
static void read_ofile_symtab (struct objfile *, struct partial_symtab *)
static void dbx_read_symtab (struct partial_symtab *self, struct objfile *objfile)
static void dbx_psymtab_to_symtab_1 (struct objfile *, struct partial_symtab *)
static void read_dbx_dynamic_symtab (struct objfile *objfile)
static void read_dbx_symtab (struct objfile *)
static void free_bincl_list (struct objfile *)
static struct partial_symtab * find_corresponding_bincl_psymtab (char *, int)
static void add_bincl_to_list (struct partial_symtab *, char *, int)
static void init_bincl_list (int, struct objfile *)
static char * dbx_next_symbol_text (struct objfile *)
static void fill_symbuf (bfd *)
static void dbx_symfile_init (struct objfile *)
static void dbx_new_init (struct objfile *)
static void dbx_symfile_read (struct objfile *, int)
static void dbx_symfile_finish (struct objfile *)
static void record_minimal_symbol (const char *, CORE_ADDR, int, struct objfile *)
static void add_new_header_file (char *, int)
static void add_old_header_file (char *, int)
static void add_this_object_header_file (int)
static struct partial_symtab * start_psymtab (struct objfile *, char *, CORE_ADDR, int, struct partial_symbol **, struct partial_symbol **)
void free_header_files (void)
void init_header_files (void)
static void dbx_free_symfile_info (struct objfile *objfile, void *arg)
static void stabs_seek (int sym_offset)
static void do_free_bincl_list_cleanup (void *objfile)
static struct cleanup * make_cleanup_free_bincl_list (struct objfile *objfile)
static char * set_namestring (struct objfile *objfile, const struct internal_nlist *nlist)
static CORE_ADDR find_stab_function_addr (char *namestring, const char *filename, struct objfile *objfile)
static void function_outside_compilation_unit_complaint (const char *arg1)
struct partial_symtab * end_psymtab (struct objfile *objfile, struct partial_symtab *pst, const char **include_list, int num_includes, int capping_symbol_offset, CORE_ADDR capping_text, struct partial_symtab **dependency_list, int number_dependencies, int textlow_not_set)
static void cp_set_block_scope (const struct symbol *symbol, struct block *block, struct obstack *obstack)
void process_one_symbol (int type, int desc, CORE_ADDR valu, char *name, const struct section_offsets *section_offsets, struct objfile *objfile)
void coffstab_build_psymtabs (struct objfile *objfile, CORE_ADDR textaddr, unsigned int textsize, struct stab_section_list *stabsects, file_ptr stabstroffset, unsigned int stabstrsize)
void elfstab_build_psymtabs (struct objfile *objfile, asection *stabsect, file_ptr stabstroffset, unsigned int stabstrsize)
void stabsect_build_psymtabs (struct objfile *objfile, char *stab_name, char *stabstr_name, char *text_name)
Variables
struct objfile_data * dbx_objfile_data_key
static struct objfile * dbxread_objfile
static enum language psymtab_language = language_unknown
static bfd * symfile_bfd
static unsigned symbol_size
static unsigned symbol_table_offset
static unsigned string_table_offset
static unsigned int file_string_table_offset
static unsigned int next_file_string_table_offset
static int symfile_relocatable = 0
static int block_address_function_relative = 0
static CORE_ADDR lowest_text_address
static int has_line_numbers
static struct
header_file_location * bincl_list
static struct
header_file_location * next_bincl
static int bincls_allocated
static struct external_nlist symbuf [4096]
static int symbuf_idx
static int symbuf_end
static char * last_function_name
static char * stringtab_global
static struct stab_section_list * symbuf_sections
static unsigned int symbuf_left
static unsigned int symbuf_read
static bfd_byte * stabs_data
static struct sym_fns aout_sym_fns
Define Documentation
#define COFF_STABS_SYMBOL_SIZE 12 /* XXX FIXME XXX */
Referenced by coffstab_build_psymtabs().
#define DBX_STRINGTAB_SIZE_SIZE sizeof(long) /* FIXME */
Definition at line 613 of file dbxread.c.
Referenced by dbx_symfile_init().
#define ELF_STABS_SYMBOL_SIZE 12 /* XXX FIXME XXX */
Referenced by elfstab_build_psymtabs().
#define FILE_STRING_OFFSET (p) (SYMLOC(p)->file_string_offset)
Definition at line 108 of file dbxread.c.
Referenced by dbx_psymtab_to_symtab_1(), and start_psymtab().
#define INTERNALIZE_SYMBOL (intern, extern, abfd)
Value:
{                                                                       \
    (intern).n_strx = bfd_h_get_32 (abfd, (extern)->e_strx);            \
    (intern).n_type = bfd_h_get_8 (abfd, (extern)->e_type);             \
    (intern).n_other = 0;                                               \
    (intern).n_desc = bfd_h_get_16 (abfd, (extern)->e_desc);            \
    if (bfd_get_sign_extend_vma (abfd))                                 \
      (intern).n_value = bfd_h_get_signed_32 (abfd, (extern)->e_value); \
    else                                                                \
      (intern).n_value = bfd_h_get_32 (abfd, (extern)->e_value);        \
  }
Definition at line 855 of file dbxread.c.
Referenced by dbx_next_symbol_text(), read_dbx_symtab(), and read_ofile_symtab().
#define LDSYMLEN (p) (((struct symloc *)((p)->read_symtab_private))->ldsymlen)
Definition at line 103 of file dbxread.c.
Referenced by dbx_psymtab_to_symtab_1(), dbx_read_symtab(), end_psymtab(), and read_ofile_symtab().
#define LDSYMOFF (p) (((struct symloc *)((p)->read_symtab_private))->ldsymoff)
Definition at line 102 of file dbxread.c.
Referenced by end_psymtab(), read_ofile_symtab(), and start_psymtab().
#define STRING_OFFSET (p) (SYMLOC(p)->string_offset)
Definition at line 107 of file dbxread.c.
Referenced by start_psymtab().
#define STRING_TABLE_OFFSET (sym_bfd->origin + obj_str_filepos (sym_bfd))
Referenced by dbx_symfile_init().
#define SYMBOL_OFFSET (p) (SYMLOC(p)->symbol_offset)
Definition at line 106 of file dbxread.c.
Referenced by dbx_psymtab_to_symtab_1(), and start_psymtab().
#define SYMBOL_SIZE (p) (SYMLOC(p)->symbol_size)
Definition at line 105 of file dbxread.c.
Referenced by dbx_psymtab_to_symtab_1(), and start_psymtab().
#define SYMBOL_TABLE_OFFSET (sym_bfd->origin + obj_sym_filepos (sym_bfd))
Referenced by dbx_symfile_init().
#define SYMLOC (p) ((struct symloc *)((p)->read_symtab_private))
Definition at line 104 of file dbxread.c.
Function Documentation
void _initialize_dbxread (void)
static void add_bincl_to_list (struct partial_symtab * pst, char * name, int instance) [static]
Definition at line 907 of file dbxread.c.
References bincl_list, bincls_allocated, header_file_location::instance, name, header_file_location::name, offset, header_file_location::pst, and xrealloc().
Referenced by read_dbx_symtab().
static void add_new_header_file (char * name, int instance) [static]
Definition at line 379 of file dbxread.c.
References add_this_object_header_file(), HEADER_FILES, header_file::instance, header_file::length, memset(), N_ALLOCATED_HEADER_FILES, N_HEADER_FILES, header_file::name, header_file::vector, xmalloc(), and xrealloc().
Referenced by process_one_symbol().
static void add_old_header_file (char * name, int instance) [static]
Definition at line 353 of file dbxread.c.
References add_this_object_header_file(), HEADER_FILES, header_file::instance, N_HEADER_FILES, p, repeated_header_complaint(), and symnum.
Referenced by process_one_symbol().
static void add_this_object_header_file (int i) [static]
Definition at line 334 of file dbxread.c.
References int, n_allocated_this_object_header_files, n_this_object_header_files, this_object_header_files, and xrealloc().
Referenced by add_new_header_file(), and add_old_header_file().
void coffstab_build_psymtabs (struct objfile * objfile, CORE_ADDR textaddr, unsigned int textsize, struct stab_section_list * stabsects, file_ptr stabstroffset, unsigned int stabstrsize)
Definition at line 3323 of file dbxread.c.
References _, buildsym_new_init(), COFF_STABS_SYMBOL_SIZE, DBX_STRINGTAB, DBX_STRINGTAB_SIZE, DBX_SYMBOL_SIZE, DBX_SYMCOUNT, DBX_SYMFILE_INFO, dbx_symfile_read(), DBX_SYMTAB_OFFSET, DBX_TEXT_ADDR, DBX_TEXT_SIZE, error(), free_header_files(), init_header_files(), name, stab_section_list::next, objfile::obfd, objfile::objfile_obstack, OBJSTAT, perror_with_name(), processing_acc_compilation, stab_section_list::section, and stabsread_new_init().
Referenced by coff_symfile_read().
static void cp_set_block_scope (const struct symbol * symbol, struct block * block, struct obstack * obstack) [static]
Definition at line 2681 of file dbxread.c.
References block_set_scope(), cp_entire_prefix_len(), name, and SYMBOL_DEMANGLED_NAME.
Referenced by process_one_symbol().
static void dbx_free_symfile_info (struct objfile * objfile, void * arg) [static]
Definition at line 739 of file dbxread.c.
References dbx_symfile_info::header_files, dbx_symfile_info::n_header_files, name, header_file::vector, and xfree().
static void dbx_new_init (struct objfile * ignore) [static]
Definition at line 592 of file dbxread.c.
References buildsym_new_init(), init_header_files(), and stabsread_new_init().
static char * dbx_next_symbol_text (struct objfile * objfile) [static]
Definition at line 877 of file dbxread.c.
References file_string_table_offset, fill_symbuf(), INTERNALIZE_SYMBOL, OBJSTAT, symbuf, symfile_bfd, and symnum.
Referenced by dbx_read_symtab(), and read_dbx_symtab().
static void dbx_psymtab_to_symtab_1 (struct objfile * objfile, struct partial_symtab * pst) [static]
Definition at line 2396 of file dbxread.c.
References buildsym_init(), partial_symtab::dependencies, do_cleanups(), FILE_STRING_OFFSET, file_string_table_offset, partial_symtab::filename, fprintf_unfiltered(), fputs_filtered(), gdb_flush(), gdb_stderr, gdb_stdout, info_verbose, LDSYMLEN, make_cleanup(), partial_symtab::number_of_dependencies, objfile::obfd, printf_filtered(), read_ofile_symtab(), partial_symtab::readin, really_free_pendings(), stabsread_init(), SYMBOL_OFFSET, SYMBOL_SIZE, symbol_size, and wrap_here().
Referenced by dbx_read_symtab().
static void dbx_read_symtab (struct partial_symtab * self, struct objfile * objfile) [static]
Definition at line 2450 of file dbxread.c.
References dbx_next_symbol_text(), dbx_psymtab_to_symtab_1(), DBX_STAB_SECTION, do_cleanups(), fprintf_unfiltered(), free_current_contents(), gdb_flush(), gdb_stderr, gdb_stdout, info_verbose, LDSYMLEN, make_cleanup(), next_symbol_text_func, null_cleanup(), objfile::obfd, printf_filtered(), scan_file_globals(), and symfile_relocate_debug_section().
Referenced by start_psymtab().
static void dbx_symfile_finish (struct objfile * objfile) [static]
Definition at line 733 of file dbxread.c.
References free_header_files().
static void dbx_symfile_init (struct objfile * objfile) [static]
Definition at line 616 of file dbxread.c.
References _, DBX_BSS_SECTION, DBX_DATA_SECTION, dbx_objfile_data_key, DBX_STRINGTAB, DBX_STRINGTAB_SIZE, DBX_STRINGTAB_SIZE_SIZE, DBX_SYMBOL_SIZE, DBX_SYMCOUNT, DBX_SYMFILE_INFO, DBX_SYMTAB_OFFSET, DBX_TEXT_ADDR, DBX_TEXT_SECTION, DBX_TEXT_SIZE, error(), memset(), name, objfile::obfd, objfile::objfile_obstack, OBJSTAT, perror_with_name(), STRING_TABLE_OFFSET, and SYMBOL_TABLE_OFFSET.
static void dbx_symfile_read (struct objfile * objfile, int symfile_flags) [static]
Definition at line 528 of file dbxread.c.
References block_address_function_relative, DBX_SYMBOL_SIZE, DBX_SYMCOUNT, DBX_SYMTAB_OFFSET, do_cleanups(), free_pending_blocks(), objfile::global_psymbols, init_minimal_symbol_collection(), init_psymbol_list(), install_minimal_symbols(), make_cleanup(), make_cleanup_discard_minimal_symbols(), objfile::obfd, objfile_name(), perror_with_name(), read_dbx_dynamic_symtab(), read_dbx_symtab(), really_free_pendings(), psymbol_allocation_list::size, objfile::static_psymbols, symbol_size, symbol_table_offset, and symfile_relocatable.
Referenced by coffstab_build_psymtabs(), elfstab_build_psymtabs(), and stabsect_build_psymtabs().
static void do_free_bincl_list_cleanup (void * objfile) [static]
Definition at line 952 of file dbxread.c.
References free_bincl_list().
Referenced by make_cleanup_free_bincl_list().
void elfstab_build_psymtabs (struct objfile * objfile, asection * stabsect, file_ptr stabstroffset, unsigned int stabstrsize)
Definition at line 3414 of file dbxread.c.
References _, buildsym_new_init(), DBX_STAB_SECTION, DBX_STRINGTAB, DBX_STRINGTAB_SIZE, DBX_SYMBOL_SIZE, DBX_SYMCOUNT, DBX_SYMFILE_INFO, dbx_symfile_read(), DBX_SYMTAB_OFFSET, do_cleanups(), ELF_STABS_SYMBOL_SIZE, error(), find_text_range(), free_current_contents(), free_header_files(), init_header_files(), make_cleanup(), name, null_cleanup(), objfile::obfd, objfile::objfile_obstack, OBJSTAT, perror_with_name(), processing_acc_compilation, stabsread_new_init(), and symfile_relocate_debug_section().
Referenced by elf_symfile_read().
struct partial_symtab* end_psymtab (struct objfile * objfile, struct partial_symtab * pst, const char ** include_list, int num_includes, int capping_symbol_offset, CORE_ADDR capping_text, struct partial_symtab ** dependency_list, int number_dependencies, int textlow_not_set) [read]
Definition at line 2230 of file dbxread.c.
References ALL_OBJFILE_PSYMTABS, allocate_psymtab(), partial_symtab::dependencies, discard_psymtab(), partial_symtab::filename, gdbarch_sofun_address_maybe_missing(), get_objfile_arch(), objfile::global_psymbols, partial_symtab::globals_offset, has_line_numbers, last_function_name, LDSYMLEN, LDSYMOFF, psymbol_allocation_list::list, lookup_minimal_symbol(), memcpy(), MSYMBOL_SIZE, partial_symtab::n_global_syms, partial_symtab::n_static_syms, psymbol_allocation_list::next, partial_symtab::number_of_dependencies, objfile::objfile_obstack, p, partial_symtab::read_symtab, partial_symtab::read_symtab_private, partial_symtab::readin, partial_symtab::section_offsets, sort_pst_symbols(), objfile::static_psymbols, partial_symtab::statics_offset, strchr(), SYMBOL_VALUE_ADDRESS, partial_symtab::symtab, partial_symtab::texthigh, and partial_symtab::textlow.
Referenced by parse_partial_symbols(), and read_dbx_symtab().
static void fill_symbuf (bfd * sym_bfd) [static]
Definition at line 797 of file dbxread.c.
References _, error(), memcpy(), stab_section_list::next, perror_with_name(), stab_section_list::section, symbol_size, symbol_table_offset, symbuf, symbuf_left, and symbuf_read.
Referenced by dbx_next_symbol_text(), read_dbx_symtab(), and read_ofile_symtab().
static struct partial_symtab * find_corresponding_bincl_psymtab (char * name, int instance) [static, read]
Definition at line 929 of file dbxread.c.
References header_file_location::instance, header_file_location::name, next_bincl, header_file_location::pst, repeated_header_complaint(), and symnum.
Referenced by read_dbx_symtab().
static CORE_ADDR find_stab_function_addr (char * namestring, const char * filename, struct objfile * objfile) [static]
Definition at line 1134 of file dbxread.c.
References lookup_minimal_symbol(), p, strchr(), and SYMBOL_VALUE_ADDRESS.
Referenced by process_one_symbol(), and read_dbx_symtab().
static void find_text_range (bfd * sym_bfd, struct objfile * objfile) [static]
Definition at line 204 of file dbxread.c.
References _, DBX_TEXT_ADDR, DBX_TEXT_SIZE, and error().
Referenced by elfstab_build_psymtabs().
static void free_bincl_list (struct objfile * objfile) [static]
Definition at line 945 of file dbxread.c.
References bincls_allocated, and xfree().
Referenced by do_free_bincl_list_cleanup().
void free_header_files (void)
Definition at line 311 of file dbxread.c.
References n_allocated_this_object_header_files, this_object_header_files, and xfree().
Referenced by coffstab_build_psymtabs(), dbx_symfile_finish(), elfstab_build_psymtabs(), mdebug_build_psymtabs(), and stabsect_build_psymtabs().
static void function_outside_compilation_unit_complaint (const char * arg1) [static]
Definition at line 1178 of file dbxread.c.
References _, complaint(), and symfile_complaints.
Referenced by read_dbx_symtab().
static void init_bincl_list (int number, struct objfile * objfile) [static]
Definition at line 897 of file dbxread.c.
References bincls_allocated, and xmalloc().
Referenced by read_dbx_symtab().
void init_header_files (void)
Definition at line 324 of file dbxread.c.
References n_allocated_this_object_header_files, this_object_header_files, and xmalloc().
Referenced by coffstab_build_psymtabs(), dbx_new_init(), elfstab_build_psymtabs(), mdebug_build_psymtabs(), and stabsect_build_psymtabs().
static void lbrac_mismatch_complaint (int arg1) [static]
Definition at line 179 of file dbxread.c.
References _, complaint(), and symfile_complaints.
Referenced by process_one_symbol().
static struct cleanup* make_cleanup_free_bincl_list (struct objfile * objfile) [static, read]
Definition at line 958 of file dbxread.c.
References do_free_bincl_list_cleanup(), and make_cleanup().
Referenced by read_dbx_symtab().
void process_one_symbol (int type, int desc, CORE_ADDR valu, char * name, const struct section_offsets * section_offsets, struct objfile * objfile)
Definition at line 2720 of file dbxread.c.
References _, add_new_header_file(), add_old_header_file(), ANOFFSET, block_address_function_relative, common_block_end(), common_block_start(), complaint(), context_stack_depth, cp_set_block_scope(), current_subfile, define_symbol(), subfile::dirname, end_stabs(), end_symtab(), find_stab_function_addr(), finish_block(), gdb_assert, gdbarch_addr_bits_remove(), gdbarch_sofun_address_maybe_missing(), get_last_source_file(), get_objfile_arch(), hex_string(), internal_error(), language_cplus, last_source_start_addr, lbrac_mismatch_complaint(), local_symbols, name, objfile::objfile_obstack, p, patch_subfile_names(), pop_context(), pop_subfile(), previous_stab_code, processing_gcc_compilation, push_context(), push_subfile(), record_debugformat(), record_line(), ref_add(), ref_search(), SECT_OFF_BSS, SECT_OFF_DATA, SECT_OFF_RODATA, SECT_OFF_TEXT, set_main_name(), start_stabs(), start_subfile(), start_symtab(), strchr(), SYMBOL_LANGUAGE, symbol_reference_defined(), symfile_complaints, symfile_relocatable, symnum, type, unknown_symtype_complaint(), and within_function.
Referenced by psymtab_to_symtab_1(), and read_ofile_symtab().
static void read_dbx_dynamic_symtab (struct objfile * objfile) [static]
Definition at line 991 of file dbxread.c.
References ANOFFSET, do_cleanups(), make_cleanup(), mst_solib_trampoline, name, objfile::obfd, prim_record_minimal_symbol(), record_minimal_symbol(), SECT_OFF_BSS, SECT_OFF_DATA, SECT_OFF_TEXT, objfile::section_offsets, type, xfree(), and xmalloc().
Referenced by dbx_symfile_read().
static void read_dbx_symtab (struct objfile * objfile) [static]
Definition at line 1190 of file dbxread.c.
References _, add_bincl_to_list(), add_psymbol_to_list(), ANOFFSET, complaint(), cp_canonicalize_string(), dbx_next_symbol_text(), DBX_STRINGTAB, DBX_SYMCOUNT, DBX_TEXT_ADDR, DBX_TEXT_SIZE, deduce_language_from_filename(), partial_symtab::dirname, do_cleanups(), end_psymtab(), error(), file_string_table_offset, partial_symtab::filename, fill_symbuf(), find_corresponding_bincl_psymtab(), find_stab_function_addr(), fprintf_unfiltered(), function_outside_compilation_unit_complaint(), gdb_stderr, gdbarch_sofun_address_maybe_missing(), gdbarch_static_transform_name(), gdbarch_static_transform_name_p(), get_objfile_arch(), objfile::global_psymbols, has_line_numbers, hex_string(), init_bincl_list(), INTERNALIZE_SYMBOL, language_c, language_cplus, language_unknown, LOC_BLOCK, LOC_CONST, LOC_STATIC, LOC_TYPEDEF, lowest_text_address, make_cleanup_free_bincl_list(), memcpy(), name, psymbol_allocation_list::next, next_file_string_table_offset, next_symbol_text, next_symbol_text_func, objfile::obfd, objfile::objfile_obstack, OBJSTAT, p, processing_acc_compilation, psymtab_language, QUIT, record_minimal_symbol(), objfile::sect_index_data, SECT_OFF_BSS, SECT_OFF_DATA, SECT_OFF_RODATA, SECT_OFF_TEXT, objfile::section_offsets, set_last_source_file(), set_namestring(), start_psymtab(), objfile::static_psymbols, strchr(), STRUCT_DOMAIN, symbol_size, symbuf, symfile_bfd, symfile_complaints, symnum, partial_symtab::texthigh, partial_symtab::textlow, unknown_symtype_complaint(), VAR_DOMAIN, xfree(), and xmalloc().
Referenced by dbx_symfile_read().
static void read_ofile_symtab (struct objfile * objfile, struct partial_symtab * pst) [static]
Definition at line 2508 of file dbxread.c.
References _, DBX_STRINGTAB, end_stabs(), end_symtab(), error(), fill_symbuf(), INTERNALIZE_SYMBOL, last_source_start_addr, LDSYMLEN, LDSYMOFF, objfile::obfd, OBJSTAT, process_one_symbol(), processing_acc_compilation, processing_gcc_compilation, QUIT, SECT_OFF_TEXT, partial_symtab::section_offsets, set_last_source_file(), set_namestring(), stabs_seek(), symbol_size, symbuf, symbuf_idx, symfile_bfd, symnum, partial_symtab::symtab, text_offset, partial_symtab::texthigh, partial_symtab::textlow, and type.
Referenced by dbx_psymtab_to_symtab_1().
static void record_minimal_symbol (const char * name, CORE_ADDR address, int type, struct objfile * objfile) [static]
Definition at line 439 of file dbxread.c.
References is_vtable_name(), lowest_text_address, mst_abs, mst_bss, mst_data, mst_file_bss, mst_file_data, mst_file_text, mst_text, mst_unknown, name, objfile::obfd, prim_record_minimal_symbol_and_info(), SECT_OFF_BSS, SECT_OFF_DATA, and SECT_OFF_TEXT.
Referenced by read_dbx_dynamic_symtab(), and read_dbx_symtab().
static void repeated_header_complaint (const char * arg1, int arg2) [static]
Definition at line 186 of file dbxread.c.
References _, complaint(), and symfile_complaints.
Referenced by add_old_header_file(), and find_corresponding_bincl_psymtab().
static char* set_namestring (struct objfile * objfile, const struct internal_nlist * nlist) [static]
Definition at line 968 of file dbxread.c.
References _, complaint(), DBX_STRINGTAB, DBX_STRINGTAB_SIZE, file_string_table_offset, symfile_complaints, and symnum.
Referenced by read_dbx_symtab(), and read_ofile_symtab().
static void stabs_seek (int sym_offset) [static]
Definition at line 844 of file dbxread.c.
References symfile_bfd.
Referenced by read_ofile_symtab().
void stabsect_build_psymtabs (struct objfile * objfile, char * stab_name, char * stabstr_name, char * text_name)
Definition at line 3495 of file dbxread.c.
References _, buildsym_new_init(), dbx_objfile_data_key, DBX_STRINGTAB, DBX_STRINGTAB_SIZE, DBX_SYMBOL_SIZE, DBX_SYMCOUNT, dbx_symfile_read(), DBX_SYMTAB_OFFSET, DBX_TEXT_ADDR, DBX_TEXT_SIZE, error(), free_header_files(), init_header_files(), name, objfile::obfd, objfile::objfile_obstack, OBJSTAT, perror_with_name(), processing_acc_compilation, and stabsread_new_init().
Referenced by som_symfile_read().
static struct partial_symtab * start_psymtab (struct objfile * objfile, char * filename, CORE_ADDR textlow, int ldsymoff, struct partial_symbol ** global_syms, struct partial_symbol ** static_syms) [static, read]
Definition at line 2193 of file dbxread.c.
References dbx_read_symtab(), deduce_language_from_filename(), elfstab_offset_sections(), FILE_STRING_OFFSET, file_string_table_offset, LDSYMOFF, objfile::objfile_obstack, psymtab_language, partial_symtab::read_symtab, partial_symtab::read_symtab_private, objfile::section_offsets, start_psymtab_common(), STRING_OFFSET, string_table_offset, SYMBOL_OFFSET, SYMBOL_SIZE, symbol_size, and symbol_table_offset.
Referenced by read_dbx_symtab().
static void unknown_symtype_complaint (const char * arg1) [static]
Definition at line 173 of file dbxread.c.
References _, complaint(), and symfile_complaints.
Referenced by process_one_symbol(), and read_dbx_symtab().
Variable Documentation
struct sym_fns aout_sym_fns [static]
Initial value:
{
  dbx_new_init,
  dbx_symfile_init,
  dbx_symfile_read,
  NULL,
  dbx_symfile_finish,
  default_symfile_offsets,
  default_symfile_segments,
  NULL,
  default_symfile_relocate,
  NULL,
  &psym_functions
}
Definition at line 3565 of file dbxread.c.
struct header_file_location* bincl_list [static]
Definition at line 256 of file dbxread.c.
Referenced by add_bincl_to_list().
int bincls_allocated [static]
Definition at line 257 of file dbxread.c.
Referenced by add_bincl_to_list(), free_bincl_list(), and init_bincl_list().
int block_address_function_relative = 0 [static]
Definition at line 155 of file dbxread.c.
Referenced by dbx_symfile_read(), and process_one_symbol().
struct objfile_data* dbx_objfile_data_key
Definition at line 70 of file dbxread.c.
Referenced by coff_symfile_init(), dbx_symfile_init(), elf_symfile_read(), and stabsect_build_psymtabs().
struct objfile* dbxread_objfile [static]
Definition at line 113 of file dbxread.c.
unsigned int file_string_table_offset [static]
Definition at line 143 of file dbxread.c.
Referenced by dbx_next_symbol_text(), dbx_psymtab_to_symtab_1(), read_dbx_symtab(), set_namestring(), and start_psymtab().
int has_line_numbers [static]
Definition at line 168 of file dbxread.c.
Referenced by end_psymtab(), and read_dbx_symtab().
char* last_function_name [static]
Definition at line 768 of file dbxread.c.
Referenced by end_psymtab().
CORE_ADDR lowest_text_address [static]
Definition at line 163 of file dbxread.c.
Referenced by read_dbx_symtab(), and record_minimal_symbol().
struct header_file_location * next_bincl [static]
Definition at line 256 of file dbxread.c.
Referenced by find_corresponding_bincl_psymtab().
unsigned int next_file_string_table_offset [static]
Definition at line 144 of file dbxread.c.
Referenced by read_dbx_symtab().
enum language psymtab_language = language_unknown [static]
Definition at line 117 of file dbxread.c.
Referenced by read_dbx_symtab(), and start_psymtab().
bfd_byte* stabs_data [static]
Definition at line 788 of file dbxread.c.
unsigned string_table_offset [static]
Definition at line 135 of file dbxread.c.
Referenced by start_psymtab().
char* stringtab_global [static]
Definition at line 777 of file dbxread.c.
unsigned symbol_size [static]
Definition at line 127 of file dbxread.c.
Referenced by dbx_psymtab_to_symtab_1(), dbx_symfile_read(), fill_symbuf(), read_dbx_symtab(), read_ofile_symtab(), and start_psymtab().
unsigned symbol_table_offset [static]
Definition at line 131 of file dbxread.c.
Referenced by dbx_symfile_read(), fill_symbuf(), and start_psymtab().
struct external_nlist symbuf[4096] [static]
Definition at line 762 of file dbxread.c.
Referenced by dbx_next_symbol_text(), fill_symbuf(), read_dbx_symtab(), and read_ofile_symtab().
int symbuf_end [static]
Definition at line 764 of file dbxread.c.
int symbuf_idx [static]
Definition at line 763 of file dbxread.c.
Referenced by read_ofile_symtab().
unsigned int symbuf_left [static]
Definition at line 783 of file dbxread.c.
Referenced by fill_symbuf().
unsigned int symbuf_read [static]
Definition at line 784 of file dbxread.c.
Referenced by fill_symbuf().
struct stab_section_list* symbuf_sections [static]
Definition at line 782 of file dbxread.c.
bfd* symfile_bfd [static]
Definition at line 121 of file dbxread.c.
Referenced by dbx_next_symbol_text(), read_dbx_symtab(), read_ofile_symtab(), and stabs_seek().
int symfile_relocatable = 0 [static]
Definition at line 150 of file dbxread.c.
Referenced by dbx_symfile_read(), and process_one_symbol().