GDB (xrefs): /home/stan/gdb/src/gdb/dcache.h File Reference
/home/stan/gdb/src/gdb/dcache.h File Reference
Typedefs
typedef struct dcache_struct DCACHE
Functions
void dcache_invalidate (DCACHE *dcache)
DCACHE * dcache_init (void)
void dcache_free (DCACHE *)
int dcache_xfer_memory (struct target_ops *ops, DCACHE *cache, CORE_ADDR mem, gdb_byte *my, int len, int should_write)
void dcache_update (DCACHE *dcache, CORE_ADDR memaddr, gdb_byte *myaddr, int len)
Typedef Documentation
typedef struct dcache_struct DCACHE
Definition at line 24 of file dcache.h.
Function Documentation
void dcache_free (DCACHE *)
Definition at line 226 of file dcache.c.
References for_each_block(), free_block(), dcache_struct::freelist, dcache_struct::oldest, dcache_struct::tree, and xfree().
DCACHE* dcache_init (void)
Definition at line 456 of file dcache.c.
References dcache_line_size, dcache_splay_tree_compare(), dcache_struct::freelist, dcache_struct::line_size, null_ptid, dcache_struct::oldest, dcache_struct::ptid, dcache_struct::size, dcache_struct::tree, and xmalloc().
Referenced by initialize_targets().
void dcache_invalidate (DCACHE * dcache)
Definition at line 254 of file dcache.c.
References dcache_line_size, for_each_block(), free_block(), dcache_struct::freelist, invalidate_block(), dcache_struct::line_size, null_ptid, dcache_struct::oldest, dcache_struct::ptid, and dcache_struct::size.
Referenced by dcache_xfer_memory(), set_dcache_line_size(), set_dcache_size(), and target_dcache_invalidate().
void dcache_update (DCACHE * dcache, CORE_ADDR memaddr, gdb_byte * myaddr, int len)
Definition at line 552 of file dcache.c.
References dcache_poke_byte(), and len.
Referenced by memory_xfer_partial_1().
int dcache_xfer_memory (struct target_ops * ops, DCACHE * cache, CORE_ADDR mem, gdb_byte * my, int len, int should_write)
Definition at line 488 of file dcache.c.
References dcache_block::addr, dcache_invalidate(), dcache_invalidate_line(), dcache_peek_byte(), dcache_poke_byte(), inferior_ptid, int, len, dcache_struct::ptid, ptid_equal(), TARGET_OBJECT_RAW_MEMORY, and target_write().
Referenced by memory_xfer_partial_1().