GDB (xrefs): /home/stan/gdb/src/gdb/defs.h File Reference
/home/stan/gdb/src/gdb/defs.h File Reference
#include "config.h"
#include "build-gnulib/config.h"
#include <sys/types.h>
#include <stdio.h>
#include <errno.h>
#include <limits.h>
#include <stdint.h>
#include <unistd.h>
#include "pathmax.h"
#include <fcntl.h>
#include "ansidecl.h"
#include "gdb_locale.h"
#include "gdb_wchar.h"
#include "gdb/signals.h"
#include "ui-file.h"
#include "host-defs.h"
#include <stdarg.h>
#include "libiberty.h"
#include "hashtab.h"
#include "bfd.h"
#include "ptid.h"
#include "fopen-bin.h"
#include "common-utils.h"
#include "gdbarch.h"
#include "utils.h"
Classes
struct command_line
Defines
#define GCC_GENERATED_STDINT_H 1
#define CORE_ADDR_MAX (~ (CORE_ADDR) 0)
#define LONGEST long long
#define ULONGEST unsigned long long
#define QUIT
#define OPF_TRY_CWD_FIRST 0x01
#define OPF_SEARCH_IN_PATH 0x02
#define OPF_RETURN_REALPATH 0x04
#define XZALLOC(TYPE) ((TYPE*) xzalloc (sizeof (TYPE)))
#define XMALLOC(TYPE) ((TYPE*) xmalloc (sizeof (TYPE)))
#define XCALLOC(NMEMB, TYPE) ((TYPE*) xcalloc ((NMEMB), sizeof (TYPE)))
#define HOST_CHAR_BIT TARGET_CHAR_BIT
#define GDB_MI_MSG_WIDTH 80
Typedefs
typedef bfd_byte gdb_byte
typedef bfd_vma CORE_ADDR
typedef void initialize_file_ftype (void)
typedef int(* find_memory_region_ftype)(CORE_ADDR addr, unsigned long size, int read, int write, int exec, int modified, void *data)
Enumerations
enum language {
language_unknown, language_auto, language_c, language_cplus,
language_d, language_go, language_objc, language_java,
language_fortran, language_m2, language_asm, language_pascal,
language_ada, language_opencl, language_minimal, nr_languages
}
enum precision_type { single_precision, double_precision, unspecified_precision }
enum auto_boolean { AUTO_BOOLEAN_TRUE, AUTO_BOOLEAN_FALSE, AUTO_BOOLEAN_AUTO }
enum return_value_convention { RETURN_VALUE_REGISTER_CONVENTION, RETURN_VALUE_STRUCT_CONVENTION, RETURN_VALUE_ABI_RETURNS_ADDRESS, RETURN_VALUE_ABI_PRESERVES_ADDRESS }
enum lval_type {
not_lval, lval_memory, lval_register, lval_internalvar,
lval_internalvar_component, lval_computed
}
enum misc_command_type { ok_command, end_command, else_command, nop_command }
enum command_control_type {
simple_control, break_control, continue_control, while_control,
if_control, commands_control, python_control, while_stepping_control,
invalid_control
}
enum info_proc_what {
IP_MINIMAL, IP_MAPPINGS, IP_STATUS, IP_STAT,
IP_CMDLINE, IP_EXE, IP_CWD, IP_ALL
}
enum val_prettyformat { Val_no_prettyformat = 0, Val_prettyformat, Val_prettyformat_default }
enum gdb_osabi {
GDB_OSABI_UNINITIALIZED = -1, GDB_OSABI_UNKNOWN = 0, GDB_OSABI_SVR4, GDB_OSABI_HURD,
GDB_OSABI_SOLARIS, GDB_OSABI_OSF1, GDB_OSABI_LINUX, GDB_OSABI_FREEBSD_AOUT,
GDB_OSABI_FREEBSD_ELF, GDB_OSABI_NETBSD_AOUT, GDB_OSABI_NETBSD_ELF, GDB_OSABI_OPENBSD_ELF,
GDB_OSABI_WINCE, GDB_OSABI_GO32, GDB_OSABI_IRIX, GDB_OSABI_HPUX_ELF,
GDB_OSABI_HPUX_SOM, GDB_OSABI_QNXNTO, GDB_OSABI_CYGWIN, GDB_OSABI_AIX,
GDB_OSABI_DICOS, GDB_OSABI_DARWIN, GDB_OSABI_SYMBIAN, GDB_OSABI_OPENVMS,
GDB_OSABI_LYNXOS178, GDB_OSABI_NEWLIB, GDB_OSABI_INVALID
}
enum { MAX_REGISTER_SIZE = 64 }
enum block_enum { GLOBAL_BLOCK = 0, STATIC_BLOCK = 1, FIRST_LOCAL_BLOCK = 2 }
Functions
void clear_quit_flag (void)
int check_quit_flag (void)
void set_quit_flag (void)
void quit (void)
char * relocate_gdb_directory (const char *initial, int flag)
char * re_comp (const char *)
void symbol_file_command (char *, int)
void generic_load (char *name, int from_tty)
void print_transfer_performance (struct ui_file *stream, unsigned long data_count, unsigned long write_count, const struct timeval *start_time, const struct timeval *end_time)
char * gdb_readline (char *)
char * gdb_readline_wrapper (char *)
char * command_line_input (char *, int, char *)
void print_prompt (void)
int input_from_terminal_p (void)
void set_next_address (struct gdbarch *, CORE_ADDR)
int print_address_symbolic (struct gdbarch *, CORE_ADDR, struct ui_file *, int, char *)
int build_address_symbolic (struct gdbarch *, CORE_ADDR addr, int do_demangle, char **name, int *offset, char **filename, int *line, int *unmapped)
void print_address (struct gdbarch *, CORE_ADDR, struct ui_file *)
const char * pc_prefix (CORE_ADDR)
int openp (const char *, int, const char *, int, char **)
int source_full_path_of (const char *, char **)
void mod_path (char *, char **)
void add_path (char *, char **, int)
void directory_switch (char *, int)
void init_source_path (void)
void exec_set_find_memory_regions (int(*func)(find_memory_region_ftype func, void *data))
struct command_line * read_command_lines (char *, int, int, void(*)(char *, void *), void *)
struct command_line * read_command_lines_1 (char *(*)(void), int, void(*)(char *, void *), void *)
void free_command_lines (struct command_line **)
int longest_to_int (LONGEST)
double atof (const char *)
LONGEST extract_signed_integer (const gdb_byte *, int, enum bfd_endian)
ULONGEST extract_unsigned_integer (const gdb_byte *, int, enum bfd_endian)
int extract_long_unsigned_integer (const gdb_byte *, int, enum bfd_endian, LONGEST *)
CORE_ADDR extract_typed_address (const gdb_byte *buf, struct type *type)
void store_signed_integer (gdb_byte *, int, enum bfd_endian, LONGEST)
void store_unsigned_integer (gdb_byte *, int, enum bfd_endian, ULONGEST)
void store_typed_address (gdb_byte *buf, struct type *type, CORE_ADDR addr)
void initialize_progspace (void)
void initialize_inferiors (void)
Variables
int xdb_commands
int dbx_commands
char * gdb_sysroot
char * gdb_datadir
char * python_libdir
char * debug_file_directory
int immediate_quit
int annotation_level
int info_verbose
char * source_path
char * current_directory
unsigned input_radix
unsigned output_radix
int watchdog
char * interpreter_p
void(* deprecated_pre_add_symbol_hook)(const char *)
void(* deprecated_post_add_symbol_hook)(void)
void(* selected_frame_level_changed_hook)(int)
int(* deprecated_ui_loop_hook)(int signo)
void(* deprecated_init_ui_hook)(char *argv0)
void(* deprecated_show_load_progress)(const char *section, unsigned long section_sent, unsigned long section_size, unsigned long total_sent, unsigned long total_size)
void(* deprecated_print_frame_info_listing_hook)(struct symtab *s, int line, int stopline, int noerror)
int(* deprecated_query_hook)(const char *, va_list) ATTRIBUTE_FPTR_PRINTF(1
int(*) void(* deprecated_warning_hook)(const char *, va_list) ATTRIBUTE_FPTR_PRINTF(1
int(*) void(*) void(* deprecated_flush_hook)(struct ui_file *stream)
void(* deprecated_interactive_hook)(void)
void(* deprecated_readline_begin_hook)(char *,...) ATTRIBUTE_FPTR_PRINTF_1
char *(* deprecated_readline_hook)(char *)
void(* deprecated_readline_end_hook)(void)
void(* deprecated_register_changed_hook)(int regno)
void(* deprecated_context_hook)(int)
ptid_t(* deprecated_target_wait_hook)(ptid_t ptid, struct target_waitstatus *status, int options)
void(* deprecated_attach_hook)(void)
void(* deprecated_detach_hook)(void)
void(* deprecated_call_command_hook)(struct cmd_list_element *c, char *cmd, int from_tty)
void(* deprecated_set_hook)(struct cmd_list_element *c)
int(* deprecated_ui_load_progress_hook)(const char *section, unsigned long num)
int use_windows
Define Documentation
#define CORE_ADDR_MAX (~ (CORE_ADDR) 0)
Definition at line 115 of file defs.h.
Referenced by addrmap_mutable_set_empty(), infpy_search_memory(), mips_segment_boundary(), and parse_find_args().
#define GCC_GENERATED_STDINT_H 1
Definition at line 49 of file defs.h.
#define GDB_MI_MSG_WIDTH 80
Definition at line 761 of file defs.h.
Referenced by ser_base_read_error_fd().
#define HOST_CHAR_BIT TARGET_CHAR_BIT
Definition at line 667 of file defs.h.
Referenced by ada_value_assign(), ada_value_primitive_packed_val(), binop_promote(), constrained_packed_array_type(), decode_constrained_packed_array(), enable_break(), find_frame_addr_in_frame_chain(), java_value_print(), linux_get_siginfo_type(), linux_xfer_partial(), move_bits(), objfile_type(), paddress(), parse_number(), parse_symbol(), print_core_address(), print_field_values(), print_scalar_formatted(), print_variant_part(), read_direct_string(), read_enum_type(), read_indirect_string_at_offset(), read_indirect_string_from_dwz(), read_n_bytes(), read_range_type(), to_fixed_array_type(), val_print_packed_array_elements(), value_assign(), value_cast(), value_subscript_packed(), and write_exp_bitstring().
#define LONGEST long long
Definition at line 126 of file defs.h.
Referenced by aarch64_scan_prologue(), aarch64_store_return_value(), access_memory(), ada_array_bound_from_type(), ada_float_to_fixed(), ada_in_variant(), ada_promote_array_of_integrals(), ada_same_array_size_p(), ada_scan_number(), ada_tag_value_at_base_address(), ada_to_fixed_type_1(), ada_type_of_array(), ada_val_print_1(), ada_value_binop(), ada_value_ptr_subscript(), ada_varobj_get_array_number_of_children(), ada_which_variant_applies(), aggregate_assign_from_choices(), aggregate_assign_others(), aggregate_assign_positional(), aix_thread_xfer_partial(), alpha_next_pc(), alphanbsd_sigtramp_offset(), amd64_linux_get_syscall_number(), amd64_relocate_instruction(), arm_exidx_new_objfile(), arm_exidx_unwind_sniffer(), arm_m_exception_cache(), arm_record_ld_st_reg_offset(), arm_scan_prologue(), arm_store_return_value(), avr_io_reg_read_command(), ax_const_l(), bfin_linux_get_syscall_number(), c_get_string(), c_type_print_base(), c_type_print_varspec_suffix(), c_val_print(), call_target_sbrk(), cast_to_fixed(), check_typedef(), compare_blocks(), const_expr(), const_var_ref(), constrained_packed_array_type(), cp_find_class_member(), cp_print_class_member(), create_array_type(), create_set_type(), darwin_solib_read_all_image_info_addr(), debug_print_register(), decimal_from_integral(), decode_frame_entry_1(), decode_prologue(), default_read_var_value(), desc_bounds(), do_set_command(), dump_subexp_body_standard(), dwarf2_add_field(), dwarf2_compile_expr_to_ax(), dwarf2_compute_name(), dwarf2_const_value(), dwarf2_const_value_data(), dwarf2_fetch_constant_bytes(), dwarf2_frame_cache(), dwarf_block_to_fb_offset(), dwarf_block_to_sp_offset(), dwarf_decode_macro_bytes(), encode_actions_and_make_cleanup(), attribute::ENUM_BITFIELD(), evaluate_subexp_c(), evaluate_subexp_for_sizeof(), evaluate_subexp_opencl(), evaluate_subexp_standard(), extract_long_unsigned_integer(), extract_signed_integer(), f_val_print(), find_extant_func_descr(), find_size_for_pointer_math(), fp_register_sign_bit(), fp_register_zero_p(), frv_analyze_prologue(), frv_linux_pc_in_sigtramp(), frv_linux_sigtramp_frame_cache(), frv_skip_main_prologue(), gdb_py_object_from_longest(), gdb_sign_extend(), gen_expr(), gen_frame_args_address(), gen_frame_locals_address(), gen_var_ref(), generic_ext(), generic_val_print(), get_array_bounds(), get_discrete_bounds(), get_number_trailer(), gnuv2_baseclass_offset(), gnuv2_virtual_fn_field(), gnuv3_decode_method_ptr(), gnuv3_method_ptr_to_value(), gnuv3_print_method_ptr(), gnuv3_rtti_type(), h8300_is_argument_spill(), h8300_print_register(), handle_inferior_event(), hppa_hpux_save_state_offset(), hppa_linux_find_global_pointer(), hppabsd_find_global_pointer(), i386_linux_get_syscall_number_from_regcache(), i386_linux_intx80_sysenter_syscall_record(), ia64_find_global_pointer_from_dynamic_section(), ia64_hpux_find_global_pointer_from_solib(), ia64_hpux_xfer_memory_no_bs(), ia64_hpux_xfer_partial(), indirect_pieced_value(), inf_ptrace_xfer_partial(), info_spu_dma_command(), info_spu_event_command(), info_spu_mailbox_command(), info_spu_proxydma_command(), info_spu_signal_command(), integer_pow(), iq2000_scan_prologue(), is_scalar_type_recursive(), ld_so_xfer_auxv(), linespec_parse_variable(), linux_common_xfer_osdata(), linux_corefile_thread_callback(), linux_get_siginfo_data(), linux_nat_xfer_partial(), linux_proc_xfer_partial(), linux_spu_make_corefile_notes(), linux_xfer_osdata_fds(), linux_xfer_osdata_isockets(), linux_xfer_osdata_modules(), linux_xfer_osdata_msg(), linux_xfer_osdata_processes(), linux_xfer_osdata_processgroups(), linux_xfer_osdata_sem(), linux_xfer_osdata_shm(), linux_xfer_osdata_threads(), linux_xfer_partial(), longest_to_int(), lookup_opencl_vector_type(), lval_func_read(), lval_func_write(), m2_enum(), m2_get_discrete_bounds(), m2_is_long_set(), m2_is_long_set_of_type(), m2_long_set(), m2_print_long_set(), m2_print_unbounded_array(), m2_val_print(), m32r_skip_prologue(), m68hc11_print_register(), m68hc11_scan_prologue(), make_blockvector(), mark_common_block_symbol_computed(), max_of_size(), max_of_type(), memory_xfer_auxv(), memory_xfer_partial_1(), mi_cmd_data_read_memory_bytes(), mi_cmd_data_write_memory(), mi_cmd_data_write_register_values(), mi_cmd_trace_define_variable(), mips64_fill_fpregset(), mips64_fill_gregset(), mips_eabi_push_dummy_call(), mips_linux_get_syscall_number(), mips_n32n64_push_dummy_call(), mips_o32_push_dummy_call(), mips_o64_push_dummy_call(), mips_pseudo_register_read(), mips_pseudo_register_write(), mips_read_pc(), mn10300_analyze_prologue(), moxie_analyze_prologue(), msp430_return_value(), mt_registers_info(), opencl_component_ref(), opencl_logical_not(), operator_check_standard(), parse_and_eval_long(), parse_find_args(), parse_number(), pascal_type_print_base(), pascal_val_print(), pos_atr(), ppc64_sysv_abi_push_dummy_call(), ppc_displaced_step_fixup(), ppc_linux_get_syscall_number(), print_choices(), print_dynamic_range_bound(), print_enum_type(), print_go_string(), print_optional_low_bound(), print_range_bound(), print_scalar_formatted(), print_subexp_standard(), processInt(), procfs_xfer_auxv(), python_inferior_exit(), read_attribute_value(), read_checked_initial_length_and_offset(), read_const(), read_indirect_string(), read_initial_length(), read_memory(), read_memory_integer(), read_offset(), read_offset_1(), read_signed_leb128(), read_subrange_type(), read_whatever_is_readable(), record_linux_system_call(), remote_fileio_extract_int(), remote_fileio_extract_ptr_w_len(), remote_fileio_func_fstat(), remote_fileio_func_gettimeofday(), remote_fileio_func_lseek(), remote_fileio_func_read(), remote_fileio_func_stat(), remote_fileio_func_write(), remote_fileio_to_fio_stat(), remote_fileio_to_fio_time(), remote_fileio_to_fio_uint(), remote_flash_write(), remote_get_trace_state_variable_value(), remote_parse_stop_reply(), remote_read_qxfer(), remote_xfer_partial(), replace_operator_with_call(), rs6000_aix_core_xfer_shared_libraries_aix(), rs6000_aix_ld_info_to_xml(), rs6000_xfer_partial(), s390_backchain_frame_unwind_cache(), s390_unwind_pseudo_register(), scalar_binop(), sdata_make_value(), siginfo_value_read(), siginfo_value_write(), sparc32_linux_get_syscall_number(), sparc64_linux_get_syscall_number(), sparc64fbsd_sigtramp_frame_cache(), spu_enumerate_spu_ids(), spu_frame_unwind_cache(), spu_xfer_partial(), stap_modify_semaphore(), target_fileio_read_alloc_1(), target_fileio_read_stralloc(), target_read(), target_read_alloc_1(), target_read_live_memory(), target_read_stralloc(), target_write_memory_blocks(), target_write_with_progress(), target_xfer_partial(), tilegx_analyze_prologue(), to_fixed_range_type(), trace_save(), trace_status_command(), trace_variable_command(), typy_range(), unpack_field_as_long(), update_current_target(), val_print_array_elements(), val_print_packed_array_elements(), val_print_type_code_int(), value_assign(), value_assign_to_component(), value_bit_index(), value_cast(), value_coerce_to_target(), value_complement(), value_f90_subarray(), value_fetch_lazy(), value_field_bitfield(), value_neg(), value_one(), value_primitive_field(), value_ptradd(), value_ptrdiff(), value_slice(), value_subscript(), value_subscript_packed(), value_vector_widen(), VEC(), vector_binop(), vector_relop(), windows_core_xfer_shared_libraries(), windows_xfer_shared_libraries(), write_dollar_variable(), write_exp_bitstring(), write_exp_msymbol(), write_exp_string(), write_object_renaming(), xml_builtin_xfer_partial(), xstormy16_analyze_prologue(), xstormy16_find_jmp_table_entry(), and xstormy16_resolve_jmp_table_entry().
#define OPF_RETURN_REALPATH 0x04
Definition at line 350 of file defs.h.
Referenced by find_and_open_script(), find_and_open_source(), nto_find_and_open_solib(), openp(), solib_find(), source_full_path_of(), symfile_bfd_open(), and try_open_dwop_file().
#define OPF_SEARCH_IN_PATH 0x02
Definition at line 349 of file defs.h.
Referenced by find_and_open_script(), find_and_open_source(), openp(), source_full_path_of(), and try_open_dwop_file().
#define OPF_TRY_CWD_FIRST 0x01
Definition at line 348 of file defs.h.
Referenced by exec_file_attach(), find_and_open_script(), nto_find_and_open_solib(), openp(), solib_find(), source_full_path_of(), and symfile_bfd_open().
#define QUIT
Value:
{ \
  if (check_quit_flag ()) quit (); \
  if (deprecated_interactive_hook) deprecated_interactive_hook (); \
}
Definition at line 191 of file defs.h.
Referenced by ada_val_print_1(), amd64_windows_frame_decode_epilogue(), amd64_windows_frame_decode_insns(), backtrace_command_1(), breakpoint_1(), c_type_print_base(), c_type_print_varspec_prefix(), c_type_print_varspec_suffix(), classes_info(), coff_symtab_read(), collect_symbol(), command_line_input(), cp_find_class_member(), do_examine(), dump_insns(), encode_actions_1(), execute_control_command(), execute_stack_op(), f_type_print_base(), f_type_print_varspec_prefix(), f_type_print_varspec_suffix(), find_methods(), gdb_disassemble_driver(), generic_printstr(), generic_val_print(), getpkt_or_notif_sane_1(), java_type_print_base(), m2_enum(), m2_print_type(), m2_printstr(), m2_record_fields(), m32r_load_section(), maintenance_check_symtabs(), maintenance_expand_file_matcher(), maintenance_info_psymtabs(), maintenance_info_symtabs(), maintenance_print_msymbols(), maintenance_print_objfiles(), maintenance_print_psymbols(), maintenance_print_symbols(), make_symbol_overload_list_qualified(), map_matching_symbols_psymtab(), map_symbol_filenames_psymtab(), mi_cmd_stack_info_depth(), mi_cmd_stack_list_args(), mi_cmd_stack_list_frames(), mips_expect_timeout(), mips_xfer_memory(), monitor_expect(), pascal_printstr(), pascal_type_print_base(), pascal_type_print_varspec_prefix(), pascal_type_print_varspec_suffix(), print_enum_type(), print_frame(), print_frame_args(), print_frame_nameless_args(), print_object_command(), print_objfile_statistics(), print_partial_symbols(), print_selected_record_field_types(), print_symbol_bcache_statistics(), printf_c_string(), printf_wide_c_string(), printstr(), prompt_for_continue(), read_dbx_symtab(), read_memory(), read_ofile_symtab(), read_string(), read_xcoff_symtab(), recursively_search_psymtabs(), remote_download_command_source(), remote_download_tracepoint(), remote_get_noisy_reply(), remote_rcmd(), remote_start_remote(), resume(), scan_file_globals(), scan_xcoff_symtab(), scope_info(), search_symbols(), selectors_info(), signals_info(), skip_info(), som_symtab_read(), stringify_collection_list(), symtab_symbol_info(), target_fileio_read_alloc_1(), target_read(), target_read_alloc_1(), target_write_with_progress(), trace_dump_actions(), val_print(), validate_actionline(), and VEC().
#define ULONGEST unsigned long long
Definition at line 127 of file defs.h.
Referenced by aarch64_extract_return_value(), access_memory(), ada_modulus(), ada_scan_number(), alpha_dummy_id(), alpha_extract_return_value(), alpha_heuristic_frame_unwind_cache(), alpha_lds(), alpha_linux_sigcontext_addr(), alpha_mdebug_frame_unwind_cache(), alpha_return_value(), alpha_store_return_value(), alpha_sts(), alpha_unwind_pc(), amd64_displaced_step_fixup(), amd64_linux_record_signal(), amd64_linux_syscall_record(), amd64_return_value(), amd64_windows_return_value(), amd64_windows_skip_trampoline_code(), amd64obsd_sigcontext_addr(), amd64obsd_trapframe_cache(), amd64obsd_trapframe_sniffer(), arm_catch_kernel_helper_return(), arm_copy_alu_imm(), arm_copy_extra_ld_st(), arm_dwarf2_prev_register(), arm_exidx_fill_cache(), arm_extract_return_value(), arm_frame_is_thumb(), arm_linux_cleanup_svc(), arm_linux_get_syscall_number(), arm_linux_restart_syscall_init(), arm_linux_rt_sigreturn_init(), arm_linux_sigreturn_init(), arm_linux_sigreturn_return_addr(), arm_linux_syscall_next_pc(), arm_pe_skip_trampoline_code(), arm_process_record(), arm_prologue_prev_register(), arm_record_data_proc_misc_ld_str(), arm_record_extension_space(), arm_record_ld_st_imm_offset(), arm_record_ld_st_multiple(), arm_record_ld_st_reg_offset(), arm_record_strx(), arm_symbian_skip_trampoline_code(), arm_wince_skip_main_prologue(), arm_write_pc(), avr_dummy_id(), avr_frame_prev_register(), avr_frame_unwind_cache(), avr_integer_to_address(), avr_pseudo_register_read(), avr_pseudo_register_write(), avr_push_dummy_call(), avr_read_pc(), avr_unwind_pc(), avr_unwind_sp(), bfin_extract_return_value(), branch_write_pc(), bsd_uthread_check_magic(), bsd_uthread_extra_thread_info(), bsd_uthread_thread_alive(), bsd_uthread_wait(), bsearch_cie_cmp(), build_traceframe_info(), bx_write_pc(), c_val_print(), check_binary_download(), check_typedef(), claim_memory(), cleanup_alu_imm(), cleanup_alu_reg(), cleanup_alu_shifted_reg(), cleanup_block_load_pc(), cleanup_branch(), cleanup_copro_load_store(), cleanup_load(), cleanup_store(), cmd_record_call_history(), cmd_record_goto(), cmd_record_insn_history(), create_addrmap_from_index(), create_cus_from_index_list(), create_debug_types_hash_table(), create_signatured_type_table_from_index(), cris_extract_return_value(), cris_scan_prologue(), cris_store_return_value(), cris_unwind_pc(), cris_unwind_sp(), crisv32_scan_prologue(), crisv32_single_step_through_delay(), current_me_module(), current_options(), debug_print_register(), decode_constrained_packed_array(), decode_frame_entry_1(), deprecated_mips_set_processor_regs_hack(), displaced_in_arm_mode(), displaced_read_reg(), displaced_step_prepare(), displaced_step_restore(), display_one_tib(), do_ppc_sysv_return_value(), dump_memory_to_file(), dwarf2_compile_expr_to_ax(), dwarf2_evaluate_loc_desc_full(), dwarf2_read_addr_index(), dwarf2_restore_rule(), dwarf_expr_fetch_address(), enable_watchpoints_in_psr(), attribute::ENUM_BITFIELD(), execute_s32e(), execute_stack_op(), extract_unsigned_integer(), fetch_ppc_memory(), fetch_ppc_register(), fill_gregset(), find_command(), find_func_descr(), fixup_riprel(), follow_die_sig(), frv_analyze_prologue(), frv_extract_return_value(), frv_fdpic_loadmap_addresses(), get_insn_number(), get_target_memory_unsigned(), h8300_extract_return_value(), h8300_print_register(), h8300_push_dummy_call(), h8300_store_return_value(), h8300h_extract_return_value(), h8300h_return_value(), h8300h_store_return_value(), heuristic_proc_start(), hppa64_convert_code_addr_to_fptr(), hppa64_push_dummy_call(), hppa_fallback_frame_cache(), hppa_hpux_fetch_register(), hppa_hpux_read_pc(), hppa_hpux_save_state_offset(), hppa_hpux_store_register(), hppa_hpux_supply_save_state(), hppa_hpux_unwind_adjust_stub(), hppa_hpux_unwind_pc(), hppa_hpux_write_pc(), hppa_pseudo_register_read(), hppa_read_pc(), hppa_skip_permanent_breakpoint(), hppa_unwind_pc(), i386_darwin_sstep_at_sigreturn(), i386_displaced_step_fixup(), i386_frame_prev_register(), i386_linux_record_signal(), i386_linux_resume(), i386_mmx_regnum_to_fp_regnum(), i386_process_record(), i386_record_lea_modrm_addr(), i386_record_push(), i386_return_value(), i386_store_return_value(), i386fbsd_resume(), i386obsd_trapframe_cache(), i386obsd_trapframe_sniffer(), i387_print_float_info(), i387_return_value(), ia64_allocate_new_rse_frame(), ia64_extract_return_value(), ia64_frame_prev_register(), ia64_hpux_handle_dld_breakpoint_1(), ia64_hpux_handle_load_event(), ia64_hpux_push_dummy_code(), ia64_pseudo_register_read(), ia64_pseudo_register_write(), ia64_push_dummy_call(), ia64_read_pc(), ia64_store_return_value(), ia64_write_pc(), inf_ptrace_xfer_partial(), info_checkpoints_command(), info_spu_dma_cmdlist(), info_spu_dma_command(), info_spu_event_command(), info_spu_mailbox_list(), info_spu_proxydma_command(), info_spu_signal_command(), init_cutu_and_read_dies(), install_alu_reg(), install_alu_shifted_reg(), install_copro_load_store(), install_load_store(), install_preload(), install_preload_reg(), iq2000_extract_return_value(), java_val_print(), linux_core_info_proc_mappings(), linux_find_memory_regions_full(), linux_info_proc(), linux_make_mappings_callback(), linux_make_mappings_corefile_notes(), linux_xfer_partial(), lm32_extract_return_value(), lm32_frame_cache(), lm32_push_dummy_call(), lm32_store_return_value(), locexpr_describe_location_piece(), lookup_die_type(), lookup_dwo_unit(), lookup_dwo_unit_in_dwp(), m32c_push_dummy_call(), m32c_read_flg(), m32c_return_value(), m32r_extract_return_value(), m32r_frame_unwind_cache(), m32r_read_pc(), m32r_store_register(), m32r_supply_register(), m68hc11_dummy_id(), m68hc11_frame_unwind_cache(), m68hc11_print_register(), m68hc11_pseudo_register_read(), m68hc11_push_dummy_call(), m68hc11_unwind_pc(), m68hc11_unwind_sp(), m68k_return_value(), m68k_svr4_return_value(), m88k_analyze_prologue(), mark_value_bytes_unavailable(), mem_ranges_overlap(), memory_xfer_live_readonly_partial(), mep_pseudo_csr_write(), mep_push_dummy_call(), mep_read_pc(), mep_return_value(), micromips_bc1_pc(), micromips_deal_with_atomic_sequence(), micromips_in_function_epilogue_p(), micromips_instruction_has_delay_slot(), micromips_next_pc(), micromips_pc_insn_size(), micromips_scan_prologue(), mips32_bc1_pc(), mips_about_to_return(), mips_addr_bits_remove(), mips_breakpoint_from_pc(), mips_deal_with_atomic_sequence(), mips_get_mips16_fn_stub_pc(), mips_linux_in_dynsym_stub(), mips_linux_syscall_next_pc(), mips_remote_breakpoint_from_pc(), mips_request(), mips_single_step_through_delay(), mn10300_read_pc(), mn10300_unwind_pc(), mn10300_unwind_sp(), modify_field(), monitor_store_register(), monitor_supply_register(), moxie_analyze_prologue(), moxie_extract_return_value(), moxie_read_pc(), msp430_prev_register(), msp430_pseudo_register_read(), msp430_pseudo_register_write(), msp430_push_dummy_call(), msp430_return_value(), mt_frame_unwind_cache(), mt_pseudo_register_read(), mt_pseudo_register_write(), mt_registers_info(), mt_return_value(), mt_unwind_pc(), mt_unwind_sp(), nios2_linux_syscall_next_pc(), parse_find_args(), parse_number(), parse_spufs_run(), parse_static_tracepoint_marker_definition(), parse_trace_status(), parse_tracepoint_definition(), parse_tracepoint_status(), parse_tsv_definition(), pascal_val_print(), place_section(), ppc64_sysv_abi_push_dummy_call(), ppc64_sysv_abi_return_value(), ppc_displaced_step_fixup(), ppc_ravenscar_generic_store_registers(), ppc_sysv_abi_push_dummy_call(), print_transfer_performance(), print_wchar(), process_enumeration_scope(), processInt(), procfs_xfer_auxv(), queue_and_load_dwo_tu(), ranges_overlap(), read_attribute_value(), read_cutu_die_from_dwo(), read_hex_value(), read_memory_unsigned_integer(), read_pieced_value(), read_ptid(), read_str_index(), read_unsigned_leb128(), read_whatever_is_readable(), record_btrace_call_history_from(), record_btrace_insn_history_from(), record_full_core_xfer_partial(), record_linux_msghdr(), record_linux_system_call(), regcache_read_pc(), remote_address_masked(), remote_download_trace_state_variable(), remote_file_get(), remote_file_put(), remote_get_min_fast_tracepoint_insn_len(), remote_get_noisy_reply(), remote_get_thread_local_address(), remote_get_tib_address(), remote_get_trace_state_variable_value(), remote_insert_breakpoint(), remote_insert_hw_breakpoint(), remote_insert_watchpoint(), remote_parse_stop_reply(), remote_read_bytes(), remote_remove_breakpoint(), remote_remove_hw_breakpoint(), remote_remove_watchpoint(), remote_search_memory(), remote_set_trace_buffer_size(), remote_write_bytes_aux(), remote_write_qxfer(), rl78_prev_register(), rl78_pseudo_register_read(), rl78_pseudo_register_write(), rl78_return_value(), rs6000_lynx178_push_dummy_call(), rs6000_lynx178_return_value(), rs6000_push_dummy_call(), rs6000_return_value(), rs6000_xfer_partial(), rs6000_xfer_shared_libraries(), rx_push_dummy_call(), rx_return_value(), rx_unwind_pc(), rx_unwind_sp(), s390_backchain_frame_unwind_cache(), s390_displaced_step_fixup(), s390_prologue_frame_unwind_cache(), s390_pseudo_register_read(), s390_pseudo_register_write(), s390_push_dummy_call(), s390_sigtramp_frame_unwind_cache(), s390_stub_frame_unwind_cache(), s390_supply_tdb_regset(), s390_unwind_pc(), s390_unwind_sp(), scalar_binop(), score_push_dummy_call(), section_table_xfer_memory_partial(), sh_analyze_prologue(), sh_extract_return_value_nofpu(), sh_frame_cache(), sh_in_function_epilogue_p(), sh_store_return_value_nofpu(), solib_svr4_r_ldsomap(), solib_target_relocate_section_addresses(), sparc32_frame_prev_register(), sparc32_linux_step_trap(), sparc32_return_value(), sparc32_supply_gregset(), sparc32nbsd_sigcontext_saved_regs(), sparc64_collect_gregset(), sparc64_frame_prev_register(), sparc64_linux_step_trap(), sparc64_linux_write_pc(), sparc64_pseudo_register_read(), sparc64_pseudo_register_write(), sparc64_supply_gregset(), sparc64nbsd_sigcontext_saved_regs(), sparc64obsd_trapframe_sniffer(), sparc_collect_rwindow(), sparc_linux_write_pc(), sparc_ravenscar_fetch_registers(), sparc_ravenscar_store_registers(), sparc_store_inferior_registers(), sparc_supply_rwindow(), sparcnbsd_step_trap(), spu_bfd_iovec_pread(), spu_bfd_open(), spu_child_post_attach(), spu_child_post_startup_inferior(), spu_fetch_inferior_registers(), spu_frame_unwind_cache(), spu_integer_to_address(), spu_mfc_get_bitfield(), spu_pointer_to_address(), spu_pseudo_register_read(), spu_pseudo_register_read_spu(), spu_pseudo_register_write(), spu_pseudo_register_write_spu(), spu_read_pc(), spu_software_single_step(), spu_store_inferior_registers(), spu_symbol_file_add_from_memory(), spu_write_pc(), spu_xfer_partial(), stap_modify_semaphore(), store_ppc_memory(), strtoulst(), supply_gregset(), tfile_xfer_partial(), thumb2_copy_alu_imm(), thumb2_copy_load_literal(), thumb2_copy_preload(), thumb2_copy_table_branch(), thumb_deal_with_atomic_sequence_raw(), thumb_get_next_pc_raw(), thumb_record_ld_st_imm_offset(), thumb_record_ld_st_reg_offset(), thumb_record_ld_st_stack(), thumb_record_ldm_stm_swi(), thumb_record_misc(), tic6x_linux_syscall_next_pc(), tic6x_push_dummy_call(), tilegx_analyze_prologue(), tilegx_in_function_epilogue_p(), tilegx_push_dummy_call(), trace_save(), traceframe_available_memory(), tramp_frame_start(), uinteger_pow(), umax_of_size(), unpack_double(), unpack_value_bits_as_long_1(), unpack_varlen_hex(), update_current_target(), v850_extract_return_value(), v850_frame_cache(), val_print_type_code_flags(), value_assign(), value_available_contents_eq(), value_contents_copy_raw(), vax_frame_cache(), vax_return_value(), VEC(), write_pieced_value(), xstormy16_analyze_prologue(), xstormy16_in_function_epilogue_p(), xstormy16_push_dummy_call(), xtensa_extract_return_value(), xtensa_frame_prev_register(), xtensa_push_dummy_call(), xtensa_read_register(), xtensa_register_read_masked(), xtensa_register_write_masked(), and xtensa_store_return_value().
#define XCALLOC (NMEMB, TYPE) ((TYPE*) xcalloc ((NMEMB), sizeof (TYPE)))
Definition at line 563 of file defs.h.
Referenced by allocate_lval_closure(), allocate_piece_closure(), bcache_xmalloc(), copy_type_recursive(), default_symfile_segments(), elf_symfile_segments(), i386_gdbarch_init(), jit_frame_sniffer(), mt_gdbarch_init(), prim_record_minimal_symbol_full(), print_bcache_statistics(), psymbol_bcache_init(), regcache_xmalloc_1(), registry_alloc_data(), rs6000_gdbarch_init(), s390_gdbarch_init(), serial_fdopen_ops(), solib_aix_get_section_offsets(), and spu_gdbarch_init().
#define XMALLOC (TYPE) ((TYPE*) xmalloc (sizeof (TYPE)))
Definition at line 562 of file defs.h.
Referenced by _initialize_reggroup(), _initialize_ser_windows(), abbrev_table_read_table(), add_dump_command(), append_header_to_list(), ATTRIBUTE_PRINTF(), avr_gdbarch_init(), bfin_gdbarch_init(), cli_out_new(), execute_cfa_program(), gdbarch_alloc(), gdbarch_data_register(), gdbarch_find_by_info(), gdbarch_register(), get_complaints(), interp_new(), lm32_gdbarch_init(), m32r_gdbarch_init(), make_cleanup_ui_out_end(), make_pipe_state(), mem_file_new(), mi_console_file_new(), mi_interpreter_init(), mi_out_new(), mi_parse(), microblaze_gdbarch_init(), moxie_gdbarch_init(), pipe_open(), push_level(), regcache_xmalloc_1(), reggroup_new(), register_data_with_cleanup(), remote_notif_stop_alloc_reply(), ser_base_copy_tty_state(), ser_base_get_tty_state(), serial_open(), sh64_gdbarch_init(), tui_add_content_elements(), tui_alloc_generic_win_info(), tui_alloc_win_info(), tui_file_new(), tui_out_new(), ui_out_new(), user_reg_add_builtin(), and xalloc_observer_list_node().
#define XZALLOC (TYPE) ((TYPE*) xzalloc (sizeof (TYPE)))
Definition at line 561 of file defs.h.
Referenced by add_fork(), add_program_space(), alloc_type_arch(), alloc_type_instance(), allocate_lval_closure(), allocate_piece_closure(), allocate_target_description(), append_ocl_sos(), bsd_uthread_target(), core_open(), darwin_attach_pid(), darwin_check_new_threads(), darwin_current_sos(), default_symfile_segments(), deprecated_insert_raw_breakpoint(), dummy_frame_push(), dwarf2_frame_cache(), elf_symfile_segments(), exceptions_state_mc_init(), gdbtk_interpreter_init(), get_ada_inferior_data(), get_ada_tasks_inferior_data(), get_ada_tasks_pspace_data(), get_auto_load_pspace_data(), get_auxv_inferior_data(), get_catch_syscall_inferior_data(), get_darwin_info(), get_dsbt_info(), get_inflow_inferior_data(), get_jit_objfile_data(), get_jit_program_space_data(), get_objfile_pspace_data(), get_sim_inferior_data(), get_solib_aix_inferior_data(), get_svr4_info(), hppa_gdbarch_init(), ia64_hpux_target_so_ops(), inf_child_target(), install_symfile_debug_logging(), jit_block_open_impl(), jit_frame_sniffer(), jit_object_open_impl(), jit_reader_load(), jit_symtab_open_impl(), make_command_stats_cleanup(), make_params(), new_address_space(), new_so_list(), save_infcall_suspend_state(), sh_gdbarch_init(), skip_file_command(), skip_function(), solib_aix_current_sos(), solib_target_current_sos(), sparc32_gdbarch_init(), spu_current_sos(), svr4_default_sos(), svr4_keep_data_in_core(), svr4_read_so_list(), target_bfd_reopen(), tdesc_create_feature(), tdesc_create_flags(), tdesc_create_reg(), tdesc_create_struct(), tdesc_create_union(), tdesc_create_vector(), tdesc_data_alloc(), windows_add_thread(), and windows_make_so().
Typedef Documentation
typedef bfd_vma CORE_ADDR
Definition at line 112 of file defs.h.
typedef int(* find_memory_region_ftype)(CORE_ADDR addr, unsigned long size, int read, int write, int exec, int modified, void *data)
Definition at line 373 of file defs.h.
typedef bfd_byte gdb_byte
Definition at line 109 of file defs.h.
typedef void initialize_file_ftype(void)
Definition at line 312 of file defs.h.
Enumeration Type Documentation
anonymous enum
Enumerator:
MAX_REGISTER_SIZE
Definition at line 649 of file defs.h.
enum auto_boolean
Enumerator:
AUTO_BOOLEAN_TRUE
AUTO_BOOLEAN_FALSE
AUTO_BOOLEAN_AUTO
Definition at line 229 of file defs.h.
enum block_enum
Enumerator:
GLOBAL_BLOCK
STATIC_BLOCK
FIRST_LOCAL_BLOCK
Definition at line 770 of file defs.h.
enum command_control_type
Enumerator:
simple_control
break_control
continue_control
while_control
if_control
commands_control
python_control
while_stepping_control
invalid_control
Definition at line 411 of file defs.h.
enum gdb_osabi
Enumerator:
GDB_OSABI_UNINITIALIZED
GDB_OSABI_UNKNOWN
GDB_OSABI_SVR4
GDB_OSABI_HURD
GDB_OSABI_SOLARIS
GDB_OSABI_OSF1
GDB_OSABI_LINUX
GDB_OSABI_FREEBSD_AOUT
GDB_OSABI_FREEBSD_ELF
GDB_OSABI_NETBSD_AOUT
GDB_OSABI_NETBSD_ELF
GDB_OSABI_OPENBSD_ELF
GDB_OSABI_WINCE
GDB_OSABI_GO32
GDB_OSABI_IRIX
GDB_OSABI_HPUX_ELF
GDB_OSABI_HPUX_SOM
GDB_OSABI_QNXNTO
GDB_OSABI_CYGWIN
GDB_OSABI_AIX
GDB_OSABI_DICOS
GDB_OSABI_DARWIN
GDB_OSABI_SYMBIAN
GDB_OSABI_OPENVMS
GDB_OSABI_LYNXOS178
GDB_OSABI_NEWLIB
GDB_OSABI_INVALID
Definition at line 569 of file defs.h.
enum info_proc_what
Enumerator:
IP_MINIMAL
IP_MAPPINGS
IP_STATUS
IP_STAT
IP_CMDLINE
IP_EXE
IP_CWD
IP_ALL
Definition at line 451 of file defs.h.
enum language
Enumerator:
language_unknown
language_auto
language_c
language_cplus
language_d
language_go
language_objc
language_java
language_fortran
language_m2
language_asm
language_pascal
language_ada
language_opencl
language_minimal
nr_languages
Definition at line 201 of file defs.h.
enum lval_type
Enumerator:
not_lval
lval_memory
lval_register
lval_internalvar
lval_internalvar_component
lval_computed
Definition at line 384 of file defs.h.
enum misc_command_type
Enumerator:
ok_command
end_command
else_command
nop_command
Definition at line 403 of file defs.h.
enum precision_type
Enumerator:
single_precision
double_precision
unspecified_precision
Definition at line 221 of file defs.h.
enum return_value_convention
Enumerator:
RETURN_VALUE_REGISTER_CONVENTION
RETURN_VALUE_STRUCT_CONVENTION
RETURN_VALUE_ABI_RETURNS_ADDRESS
RETURN_VALUE_ABI_PRESERVES_ADDRESS
Definition at line 237 of file defs.h.
enum val_prettyformat
Enumerator:
Val_no_prettyformat
Val_prettyformat
Val_prettyformat_default
Definition at line 492 of file defs.h.
Function Documentation
void add_path (char * , char ** , int)
Definition at line 459 of file source.c.
References _, current_directory, dirnames_to_char_ptr_vec_append(), do_cleanups(), fprintf_unfiltered(), gdb_buildargv(), gdb_stderr, len, make_cleanup(), make_cleanup_free_char_ptr_vec(), memmove(), name, p, print_sys_errmsg(), savestring(), VEC, VEC_iterate, VEC_safe_push, warning(), and xfree().
Referenced by directory_switch(), env_mod_path(), and mod_path().
double atof (const char *)
Referenced by define_symbol(), and parse_number().
int build_address_symbolic (struct gdbarch * , CORE_ADDR addr, int do_demangle, char ** name, int * offset, char ** filename, int * line, int * unmapped)
Definition at line 626 of file printcmd.c.
References asm_demangle, BLOCK_START, find_pc_overlay(), find_pc_sect_function(), find_pc_sect_line(), gdbarch_addr_bits_remove(), lookup_minimal_symbol_by_pc_section(), max_symbolic_offset, bound_minimal_symbol::minsym, mst_file_text, mst_solib_trampoline, mst_text, mst_text_gnu_ifunc, MSYMBOL_HAS_SIZE, MSYMBOL_SIZE, MSYMBOL_TYPE, overlay_debugging, overlay_mapped_address(), pc_in_unmapped_range(), print_symbol_filename, SYMBOL_BLOCK_VALUE, SYMBOL_LINKAGE_NAME, SYMBOL_PRINT_NAME, SYMBOL_VALUE_ADDRESS, and symtab_to_filename_for_display().
Referenced by dump_insns(), and print_address_symbolic().
int check_quit_flag (void)
Definition at line 160 of file utils.c.
Referenced by async_request_quit(), gdb_os_poll_quit(), load_progress(), and remote_wait_as().
void clear_quit_flag (void)
Referenced by captured_main(), command_handler(), command_loop(), gdb_os_poll_quit(), remote_wait_as(), and throw_exception().
char* command_line_input (char * , int , char *)
Definition at line 887 of file top.c.
References annotation_level, command_editing_p, command_line_input(), deprecated_readline_hook, gdb_flush(), gdb_readline(), gdb_readline_wrapper(), gdb_stderr, gdb_stdout, history_expansion_p, immediate_quit, input_from_terminal_p(), instream, job_control, p, printf_unfiltered(), puts_unfiltered(), QUIT, saved_command_line, saved_command_line_size, server_command, SERVER_COMMAND_LENGTH, source_file_name, source_line_number, wrap_here(), xfree(), xmalloc(), and xrealloc().
Referenced by command_line_input(), command_loop(), decode_line_2(), gdbpy_readline_wrapper(), get_selections(), and read_next_line().
void directory_switch (char * , int)
Definition at line 439 of file source.c.
References add_path(), and source_path.
Referenced by captured_main().
void exec_set_find_memory_regions (int(*)(find_memory_region_ftype func, void *data) func)
Referenced by _initialize_gcore().
int extract_long_unsigned_integer (const gdb_byte * , int , enum bfd_endian, LONGEST *)
Definition at line 121 of file findvar.c.
References extract_unsigned_integer(), int, len, LONGEST, and p.
Referenced by val_print_type_code_int().
LONGEST extract_signed_integer (const gdb_byte * , int , enum bfd_endian)
Definition at line 51 of file findvar.c.
References _, error(), len, LONGEST, and p.
Referenced by amd64_linux_get_syscall_number(), amd64_relocate_instruction(), amd64_skip_main_prologue(), amd64_windows_frame_decode_epilogue(), bfin_linux_get_syscall_number(), cp_print_class_member(), decode_debug_loc_addresses(), disassemble_dwarf_expression(), dwarf2_compile_expr_to_ax(), evaluate_subexp_java(), execute_stack_op(), extend_simple_arg(), extract_mips_address(), fill_gregset(), find_extant_func_descr(), fixup_riprel(), frame_unwind_register_signed(), frv_analyze_prologue(), gnuv3_decode_method_ptr(), hppa_linux_find_global_pointer(), hppabsd_find_global_pointer(), i386_linux_get_syscall_number_from_regcache(), i386_record_lea_modrm_addr(), i386_relocate_instruction(), i386_skip_main_prologue(), ia64_find_global_pointer_from_dynamic_section(), java_value_print(), mips64_fill_fpregset(), mips64_fill_gregset(), mips_eabi_push_dummy_call(), mips_get_mips16_fn_stub_pc(), mips_integer_to_address(), mips_linux_get_syscall_number(), mips_n32n64_push_dummy_call(), mips_o32_push_dummy_call(), mips_o64_push_dummy_call(), mips_pseudo_register_write(), mn10300_analyze_prologue(), mt_select_coprocessor(), ppc_linux_get_syscall_number(), ppc_linux_spe_context(), read_memory_integer(), record_linux_system_call(), regcache_cooked_read_signed(), regcache_raw_read_signed(), rs6000_aix_extract_ld_info(), s390_return_value(), signed_pointer_to_address(), sparc32_linux_get_syscall_number(), sparc64_linux_get_syscall_number(), supply_32bit_reg(), tfile_get_trace_state_variable_value(), tfile_get_traceframe_address(), tfile_trace_find(), trace_save(), and unpack_long().
CORE_ADDR extract_typed_address (const gdb_byte * buf, struct type * type)
Definition at line 171 of file findvar.c.
References _, gdbarch_pointer_to_address(), get_type_arch(), internal_error(), TYPE_CODE, TYPE_CODE_PTR, and TYPE_CODE_REF.
Referenced by ada_val_print_1(), amd64_get_longjmp_target(), c_val_print(), cp_print_value_fields(), darwin_current_sos(), darwin_load_image_infos(), darwin_read_exec_load_addr(), elf_gnu_ifunc_resolve_by_got(), elf_locate_base(), generic_val_print(), get_running_thread_id(), gnuv3_decode_method_ptr(), handle_stap_probe(), i386_unwind_pc(), jit_read_code_entry(), jit_read_descriptor(), ld_so_xfer_auxv(), lm_addr(), lm_info_read(), m68k_unwind_pc(), microblaze_unwind_pc(), nios2_unwind_pc(), open_symbol_file_object(), read_known_tasks_array(), read_known_tasks_list(), read_memory_typed_address(), rs6000_aix_extract_ld_info(), scan_dyntag(), tic6x_unwind_pc(), unpack_long(), value_of_dwarf_reg_entry(), and xtensa_unwind_pc().
ULONGEST extract_unsigned_integer (const gdb_byte * , int , enum bfd_endian)
Definition at line 86 of file findvar.c.
References _, error(), len, p, and ULONGEST.
Referenced by aarch64_get_longjmp_target(), agent_capability_check(), agent_get_helper_thread_id(), alpha_get_longjmp_target(), alpha_lds(), alpha_read_insn(), alpha_sts(), amd64_darwin_sigcontext_addr(), amd64_epilogue_frame_cache(), amd64_frame_cache_1(), amd64_linux_sigcontext_addr(), amd64_sigtramp_frame_cache(), amd64_windows_find_unwind_info(), amd64_windows_frame_cache(), amd64_windows_frame_decode_epilogue(), amd64_windows_frame_decode_insns(), amd64obsd_collect_uthread(), arm_adjust_breakpoint_address(), arm_breakpoint_from_pc(), arm_get_longjmp_target(), arm_linux_supply_gregset(), arm_push_dummy_call(), arm_symbian_skip_trampoline_code(), avr_pointer_to_address(), avr_pseudo_register_write(), avr_push_dummy_call(), avr_scan_prologue(), bsd_uthread_wait(), build_traceframe_info(), c_get_string(), c_val_print(), char_at(), core_process_module_section(), create_addrmap_from_index(), create_cus_from_index_list(), create_signatured_type_table_from_index(), cris_sigcontext_addr(), cris_sigtramp_frame_unwind_cache(), cris_store_return_value(), darwin_current_sos(), darwin_load_image_infos(), darwin_read_exec_load_addr(), darwin_solib_read_all_image_info_addr(), debug_print_register(), decode_debug_loc_addresses(), decode_debug_loc_dwo_addresses(), decode_loadmap(), default_auxv_parse(), disassemble_dwarf_expression(), display_one_tib(), dsbt_current_sos(), dwarf2_compile_expr_to_ax(), dwarf2_find_location_expression(), dwarf_expr_fetch_address(), enable_break2(), examine_prologue(), execute_cfa_program(), execute_stack_op(), extend_simple_arg(), extract_arm_insn(), extract_call_winsize(), extract_long_unsigned_integer(), fetch_lm_info(), fetch_loadmap(), fetch_mips_16(), fill_gregset(), find_canonical_descriptor_in_load_object(), frame_info(), frame_unwind_register_unsigned(), frv_current_sos(), frv_linux_pc_in_sigtramp(), frv_linux_sigcontext_reg_addr(), frv_linux_sigtramp_frame_cache(), frv_push_dummy_call(), frv_skip_main_prologue(), generic_printstr(), get_target_memory_unsigned(), h8300_push_dummy_call(), h8300_store_return_value(), h8300h_store_return_value(), hppa32_hpux_find_global_pointer(), hppa32_hpux_search_dummy_call_sequence(), hppa64_convert_code_addr_to_fptr(), hppa64_hpux_find_global_pointer(), hppa64_hpux_search_dummy_call_sequence(), hppa_frame_cache(), hppa_frame_prev_register_helper(), hppa_hpux_fetch_register(), hppa_hpux_search_pattern(), hppa_hpux_sigtramp_unwind_sniffer(), hppa_hpux_store_register(), hppa_hpux_supply_save_state(), hppa_hpux_unwind_adjust_stub(), hppa_in_function_epilogue_p(), hppa_linux_find_global_pointer(), hppa_match_insns(), hppabsd_find_global_pointer(), i386_darwin_sigcontext_addr(), i386_frame_cache_1(), i386_get_longjmp_target(), i386_linux_sigcontext_addr(), i386_process_record(), i386_sigtramp_frame_cache(), i386_svr4_sigcontext_addr(), i386bsd_sigcontext_addr(), i386nto_sigcontext_addr(), i386obsd_collect_uthread(), ia64_convert_from_func_ptr_addr(), ia64_dummy_id(), ia64_find_global_pointer_from_dynamic_section(), ia64_frame_cache(), ia64_frame_prev_register(), ia64_hpux_find_global_pointer_from_solib(), ia64_hpux_get_register_from_save_state_t(), ia64_hpux_stopped_in_syscall(), ia64_linux_sigcontext_register_address(), ia64_pseudo_register_write(), ia64_push_dummy_call(), ia64_sigtramp_frame_cache(), ia64_sigtramp_frame_prev_register(), ia64_unwind_pc(), info_spu_dma_cmdlist(), info_spu_dma_command(), info_spu_mailbox_list(), info_spu_proxydma_command(), info_spu_signal_command(), insns_match_pattern(), iq2000_pointer_to_address(), java_value_print(), jit_read_code_entry(), jit_read_descriptor(), link_map_start(), linux_spu_make_corefile_notes(), lm32_push_dummy_call(), lm32_store_return_value(), lm_base(), locexpr_describe_location_piece(), loclist_describe_location(), m32c_m16c_pointer_to_address(), m32c_push_dummy_call(), m32c_return_value(), m32r_push_dummy_call(), m32r_store_return_value(), m68hc11_pseudo_register_write(), m68hc11_push_dummy_call(), m68k_frame_cache(), m68k_get_longjmp_target(), m68k_linux_pc_in_sigtramp(), m68k_linux_sigtramp_frame_cache(), mep_get_insn(), mep_pseudo_cr32_read(), mep_pseudo_cr32_write(), mep_pseudo_csr_write(), mep_push_dummy_call(), microblaze_fetch_instruction(), mips64_linux_get_longjmp_target(), mips_fetch_instruction(), mips_linux_get_longjmp_target(), mips_linux_in_dynsym_stub(), mips_n32n64_push_dummy_call(), mips_o32_push_dummy_call(), mips_o64_push_dummy_call(), mips_skip_pic_trampoline_code(), mips_xfer_memory(), mipsnbsd_get_longjmp_target(), mn10300_push_dummy_call(), modify_field(), monitor_write_memory(), moxie_process_readu(), moxie_process_record(), moxie_store_return_value(), msp430_pseudo_register_write(), msp430_push_dummy_call(), msp430_return_value(), mt_pseudo_register_write(), mt_push_dummy_call(), mt_registers_info(), nios2_get_longjmp_target(), nios2_push_dummy_call(), parse_spufs_run(), pascal_printstr(), pascal_val_print(), pass_in_x(), ppc64_convert_from_func_ptr_addr(), ppc_displaced_step_fixup(), ppc_linux_auxv_parse(), ppc_linux_spe_context(), ppcfbsd_sigtramp_frame_sniffer(), ppcobsd_sigtramp_frame_cache(), ppcobsd_sigtramp_frame_sniffer(), ppu2spu_sniffer(), print_wchar(), printf_wide_c_string(), read_frame_register_unsigned(), read_memory_unsigned_integer(), read_program_header(), read_string(), read_target_long_array(), record_linux_msghdr(), record_linux_sockaddr(), record_linux_system_call(), regcache_cooked_read_unsigned(), regcache_raw_read_unsigned(), rl78_pointer_to_address(), rl78_return_value(), rs6000_aix_extract_ld_info(), rs6000_fetch_instruction(), rs6000_in_function_epilogue_p(), rs6000_skip_main_prologue(), rx_push_dummy_call(), rx_return_value(), s390_auxv_parse(), s390_pseudo_register_write(), s390_return_value(), scan_dyntag_auxv(), score3_adjust_pc_and_fetch_inst(), score7_breakpoint_from_pc(), score7_fetch_inst(), score_push_dummy_call(), sh64_pseudo_register_read(), sh64_pseudo_register_write(), sh64_push_dummy_call(), sh_push_dummy_call_fpu(), sh_push_dummy_call_nofpu(), sh_store_return_value_nofpu(), skip_prologue(), skip_prologue_hard_way(), som_current_sos(), som_open_symbol_file_object(), som_solib_create_inferior_hook(), sparc32obsd_collect_uthread(), sparc64_collect_gregset(), sparc64_pseudo_register_write(), sparc64_supply_gregset(), sparc64obsd_collect_uthread(), sparc_collect_rwindow(), sparc_fetch_wcookie(), sparc_supply_rwindow(), spu2ppu_sniffer(), spu_analyze_prologue(), spu_current_sos(), spu_frame_unwind_cache(), spu_get_longjmp_target(), spu_get_overlay_table(), spu_in_function_epilogue_p(), spu_pointer_to_address(), spu_pseudo_register_write_spu(), spu_push_dummy_call(), spu_software_single_step(), stap_modify_semaphore(), supply_gregset(), svr4_exec_displacement(), tfile_trace_find(), tfile_xfer_partial(), thumb2_copy_table_branch(), thumb_in_function_epilogue_p(), tic6x_get_longjmp_target(), tic6x_push_dummy_call(), tilegx_analyze_prologue(), tilegx_get_longjmp_target(), tilegx_push_dummy_call(), trace_save(), traceframe_walk_blocks(), tramp_frame_start(), unpack_long(), unpack_value_bits_as_long_1(), unsigned_pointer_to_address(), v850_push_dummy_call(), v850_store_return_value(), val_print_string(), value_bit_index(), value_cast(), value_pointer(), xstormy16_find_jmp_table_entry(), xstormy16_pointer_to_address(), xstormy16_push_dummy_call(), xstormy16_resolve_jmp_table_entry(), xtensa_pseudo_register_read(), xtensa_pseudo_register_write(), and xtensa_push_dummy_call().
void free_command_lines (struct command_line **)
Definition at line 1318 of file cli-script.c.
References command_line::body_count, command_line::body_list, free_command_lines(), command_line::line, command_line::next, and xfree().
Referenced by decref_counted_command_line(), define_command(), do_free_command_lines_cleanup(), document_command(), free_command_lines(), if_command(), and while_command().
char* gdb_readline (char *)
Definition at line 620 of file top.c.
References fputs_unfiltered(), gdb_flush(), gdb_stdout, instream, xfree(), xmalloc(), and xrealloc().
Referenced by command_line_input().
char* gdb_readline_wrapper (char *)
Definition at line 792 of file top.c.
References after_char_processing_hook, gdb_readline_wrapper_cleanup::already_prompted_orig, display_gdb_prompt(), do_cleanups(), gdb_assert, gdb_do_one_event(), gdb_readline_wrapper_done, gdb_readline_wrapper_line(), gdb_readline_wrapper_result, gdb_readline_wrapper_cleanup::handler_orig, input_handler, make_cleanup(), and xmalloc().
Referenced by command_line_input(), and prompt_for_continue().
void generic_load (char * name, int from_tty)
Definition at line 2028 of file symfile.c.
References _, add_section_size_callback(), breakpoint_re_set(), clear_memory_write_data(), current_uiout, load_progress_data::data_count, do_cleanups(), error(), error_no_arg(), flash_discard, gdb_bfd_open(), gdb_buildargv(), gdb_stdout, gdbarch_addr_bits_remove(), get_current_regcache(), gnutarget, load_section_data::load_offset, load_progress(), load_section_callback(), make_cleanup(), make_cleanup_bfd_unref(), make_cleanup_freeargv(), memset(), null_cleanup(), paddress(), perror_with_name(), print_transfer_performance(), load_section_data::progress_data, regcache_write_pc(), strtoulst(), target_gdbarch(), target_write_memory_blocks(), load_progress_data::total_size, ui_out_field_fmt(), ui_out_text(), load_progress_data::write_count, and xfree().
Referenced by init_remote_ops(), and m32r_load_gen().
void init_source_path (void)
Definition at line 402 of file source.c.
References forget_cached_source_info(), source_path, and xsnprintf().
Referenced by directory_command(), mi_cmd_env_dir(), and set_directories_command().
void initialize_inferiors (void)
Definition at line 986 of file inferior.c.
References _, add_cmd(), add_com(), add_inferior(), add_inferior_command(), add_info(), add_setshow_boolean_cmd(), program_space::aspace, inferior::aspace, class_run, clone_inferior_command(), cmdlist, current_inferior_, current_program_space, detach_inferior_command(), detachlist, inferior_command(), info_inferiors_command(), kill_inferior_command(), killlist, no_class, print_inferior_events, inferior::pspace, remove_inferior_command(), setprintlist, show_print_inferior_events(), and showprintlist.
Referenced by gdb_init().
void initialize_progspace (void)
Definition at line 524 of file progspace.c.
References _, add_cmd(), add_program_space(), class_maintenance, maintenance_info_program_spaces_command(), maintenanceinfolist, and new_address_space().
Referenced by gdb_init().
int input_from_terminal_p (void)
Definition at line 1435 of file top.c.
References batch_flag, gdb_has_a_terminal(), in_user_command, and instream.
Referenced by ATTRIBUTE_PRINTF(), command_line_input(), quit_force(), and read_command_lines().
int longest_to_int (LONGEST)
Definition at line 1038 of file valprint.c.
References _, error(), int, and LONGEST.
Referenced by ada_dump_subexp_body(), ada_forward_operator_length(), ada_operator_length(), ada_type_of_array(), aggregate_assign_from_choices(), aggregate_assign_positional(), dump_subexp_body_standard(), dwarf2_evaluate_loc_desc_full(), evaluate_subexp_c(), evaluate_subexp_java(), evaluate_subexp_opencl(), evaluate_subexp_standard(), extract_field_op(), gen_expr(), ignore_command(), operator_length_standard(), print_subexp_standard(), resolve_subexp(), value_concat(), value_equal(), value_f90_subarray(), value_less(), and value_subscripted_rvalue().
void mod_path (char * , char **)
Definition at line 447 of file source.c.
References add_path().
Referenced by directory_command(), path_command(), and set_directories_command().
int openp (const char * , int , const char * , int , char **)
Definition at line 703 of file source.c.
References current_directory, do_cleanups(), gdb_assert, gdb_open_cloexec(), gdb_realpath(), is_regular_file(), len, make_cleanup_free_char_ptr_vec(), OPF_RETURN_REALPATH, OPF_SEARCH_IN_PATH, OPF_TRY_CWD_FIRST, strchr(), VEC, VEC_iterate, and xfree().
Referenced by exec_file_attach(), find_and_open_script(), find_and_open_source(), nto_find_and_open_solib(), solib_find(), source_full_path_of(), symfile_bfd_open(), and try_open_dwop_file().
const char* pc_prefix (CORE_ADDR)
Definition at line 767 of file printcmd.c.
References get_frame_pc_if_available(), get_selected_frame(), and has_stack_frames().
Referenced by do_examine(), and dump_insns().
void print_address (struct gdbarch * , CORE_ADDR , struct ui_file *)
Definition at line 756 of file printcmd.c.
References asm_demangle, fputs_filtered(), paddress(), and print_address_symbolic().
Referenced by dis_asm_print_address(), do_examine(), find_command(), line_info(), print_scalar_formatted(), spu_dis_asm_print_address(), trace_find_line_command(), and tui_disassemble().
int print_address_symbolic (struct gdbarch * , CORE_ADDR , struct ui_file * , int , char *)
Definition at line 571 of file printcmd.c.
References build_address_symbolic(), cleanup_chain, do_cleanups(), fprintf_filtered(), fputs_filtered(), free_current_contents(), line, make_cleanup(), name, offset, and print_symbol_filename.
Referenced by gdbtk_load_asm(), print_address(), print_address_demangle(), print_breakpoint_location(), and tui_get_function_from_frame().
void print_prompt (void)
void print_transfer_performance (struct ui_file * stream, unsigned long data_count, unsigned long write_count, const struct timeval * start_time, const struct timeval * end_time)
Definition at line 2137 of file symfile.c.
References current_uiout, rate, ui_out_field_fmt(), ui_out_is_mi_like_p(), ui_out_text(), and ULONGEST.
Referenced by generic_load(), load_srec(), m32r_load(), and m32r_upload_command().
void quit (void)
Definition at line 1040 of file utils.c.
References current_target, fatal(), and target_ops::to_terminal_ours.
Referenced by async_remote_fileio_interrupt(), async_request_quit(), gdbsim_stop_inferior(), gdbsim_wait(), interrupt_query(), mips_kill(), monitor_interrupt_query(), prompt_for_continue(), and x_event().
char* re_comp (const char *)
Referenced by auto_load_info_scripts(), classes_info(), forward_search_command(), info_sharedlibrary_command(), is_known_support_routine(), maintenance_expand_symtabs(), maintenance_info_psymtabs(), maintenance_info_symtabs(), maintenance_print_objfiles(), reverse_search_command(), selectors_info(), solib_add(), and thread_find_command().
struct command_line* read_command_lines (char * , int , int , void(*)(char *, void *) , void *) [read]
Definition at line 1198 of file cli-script.c.
References current_interp_named_p(), deprecated_readline_begin_hook, deprecated_readline_end_hook, do_cleanups(), END_MESSAGE, gdb_flush(), gdb_stdout, input_from_terminal_p(), INTERP_CONSOLE, interp_set_temp(), make_cleanup(), printf_unfiltered(), read_command_lines_1(), read_next_line(), and restore_interp().
Referenced by define_command(), do_map_commands_command(), document_command(), and trace_actions_command().
struct command_line* read_command_lines_1 (char * *)(void, int , void(*)(char *, void *) , void *) [read]
char* relocate_gdb_directory (const char * initial, int flag)
Definition at line 131 of file main.c.
References gdb_program_name, relocate_path(), and xfree().
Referenced by captured_main().
void set_next_address (struct gdbarch * , CORE_ADDR)
Definition at line 549 of file printcmd.c.
References builtin_type::builtin_data_ptr, builtin_type(), lookup_internalvar(), next_address, set_internalvar(), and value_from_pointer().
Referenced by breakpoint_1(), and line_info().
void set_quit_flag (void)
Definition at line 152 of file utils.c.
Referenced by gdb_stop(), handle_sigint(), and x_event().
int source_full_path_of (const char * , char **)
Definition at line 896 of file source.c.
References openp(), OPF_RETURN_REALPATH, OPF_SEARCH_IN_PATH, OPF_TRY_CWD_FIRST, and source_path.
Referenced by attach_command_post_wait().
void store_signed_integer (gdb_byte * , int , enum bfd_endian, LONGEST)
Definition at line 186 of file findvar.c.
References len, and p.
Referenced by aarch64_store_return_value(), address_to_signed_pointer(), amd64_relocate_instruction(), arm_store_return_value(), default_read_var_value(), i386_relocate_instruction(), mi_cmd_data_write_memory(), mips64_fill_fpregset(), mips64_fill_gregset(), mips_eabi_push_dummy_call(), mips_o64_push_dummy_call(), mips_pseudo_register_read(), mips_value_to_register(), mt_pseudo_register_read(), mt_select_coprocessor(), pack_long(), regcache_cooked_write_signed(), regcache_raw_write_signed(), scalar_binop(), supply_32bit_reg(), value_fetch_lazy(), and write_memory_signed_integer().
void store_typed_address (gdb_byte * buf, struct type * type, CORE_ADDR addr)
Definition at line 244 of file findvar.c.
References _, gdbarch_address_to_pointer(), get_type_arch(), internal_error(), TYPE_CODE, TYPE_CODE_PTR, and TYPE_CODE_REF.
Referenced by default_read_var_value(), pack_long(), pack_unsigned_long(), tlb_value_read(), and value_from_pointer().
void store_unsigned_integer (gdb_byte * , int , enum bfd_endian, ULONGEST)
Definition at line 214 of file findvar.c.
References len, and p.
Referenced by aarch64_extract_return_value(), ada_value_binop(), add_address_entry(), add_to_spuid_list(), alpha_extract_return_value(), alpha_lds(), alpha_push_dummy_call(), alpha_sts(), amd64_push_dummy_call(), amd64_relocate_instruction(), amd64_windows_push_dummy_call(), amd64obsd_supply_uthread(), arm_extract_return_value(), arm_linux_supply_gregset(), arm_push_dummy_call(), avr_address_to_pointer(), avr_pseudo_register_read(), bfin_extract_return_value(), cris_extract_return_value(), cris_push_dummy_call(), do_ppc_sysv_return_value(), dwarf2_const_value_attr(), dwarf2_const_value_data(), dwarf2_fetch_constant_bytes(), dwarf_expr_fetch_address(), execute_stack_op(), fill_gregset(), find_func_descr(), frame_unwind_got_constant(), frv_extract_return_value(), frv_push_dummy_call(), gnuv3_make_method_ptr(), h8300_extract_return_value(), h8300h_extract_return_value(), hppa32_push_dummy_call(), hppa64_push_dummy_call(), hppa_hpux_fetch_register(), hppa_hpux_store_register(), hppa_hpux_supply_save_state(), hppa_pseudo_register_read(), i386_darwin_push_dummy_call(), i386_push_dummy_call(), i386_relocate_instruction(), i386obsd_supply_uthread(), i387_supply_fsave(), ia64_extract_return_value(), ia64_pseudo_register_read(), ia64_pseudo_register_write(), ia64_push_dummy_call(), iq2000_address_to_pointer(), iq2000_extract_return_value(), iq2000_push_dummy_call(), lm32_extract_return_value(), m32c_m16c_address_to_pointer(), m32c_return_value(), m32r_extract_return_value(), m32r_fetch_register(), m32r_push_dummy_call(), m68hc11_pseudo_register_read(), m68hc11_push_dummy_call(), m68k_push_dummy_call(), mark_common_block_symbol_computed(), mep_pseudo_cr32_read(), mep_pseudo_cr32_write(), mep_push_dummy_call(), mips_eabi_push_dummy_call(), mips_xfer_memory(), mn10300_push_dummy_call(), modify_field(), monitor_read_memory_single(), monitor_supply_register(), moxie_extract_return_value(), msp430_pseudo_register_read(), msp430_push_dummy_call(), msp430_return_value(), mt_return_value(), netorder16(), netorder32(), netorder64(), pack_unsigned_long(), ppc64_sysv_abi_return_value(), ppc_sysv_abi_push_dummy_call(), ppu2spu_unwind_register(), regcache_cooked_write_unsigned(), regcache_raw_write_unsigned(), rl78_address_to_pointer(), rl78_push_dummy_call(), rl78_return_value(), rs6000_lynx178_push_dummy_call(), rs6000_lynx178_return_value(), rs6000_push_dummy_call(), rs6000_return_value(), rx_return_value(), s390_pseudo_register_read(), scalar_binop(), sh64_pseudo_register_read(), sh64_pseudo_register_write(), sh_extract_return_value_nofpu(), som_solib_create_inferior_hook(), sparc32_push_dummy_code(), sparc32_store_arguments(), sparc32obsd_supply_uthread(), sparc64_collect_gregset(), sparc64_pseudo_register_read(), sparc64_supply_gregset(), sparc64obsd_supply_uthread(), sparc_collect_rwindow(), sparc_supply_rwindow(), spu_address_to_pointer(), spu_enumerate_spu_ids(), spu_fetch_inferior_registers(), spu_fetch_registers(), spu_pseudo_register_read_spu(), spu_push_dummy_call(), stap_modify_semaphore(), supply_gregset(), svr4_exec_displacement(), tfile_fetch_registers(), tic6x_push_dummy_call(), unsigned_address_to_pointer(), v850_extract_return_value(), v850_push_dummy_call(), vax_push_dummy_call(), vax_store_arguments(), write_constant_as_bytes(), write_memory_unsigned_integer(), write_one_signatured_type(), write_psymtabs_to_index(), xstormy16_address_to_pointer(), xstormy16_push_dummy_call(), and xtensa_push_dummy_call().
void symbol_file_command (char * , int)
Definition at line 1578 of file symfile.c.
References _, do_cleanups(), dont_repeat(), error(), flags, gdb_buildargv(), make_cleanup_freeargv(), name, OBJF_READNOW, OBJF_USERLOADED, symbol_file_add_main_1(), and symbol_file_clear().
Referenced by file_command().
Variable Documentation
int annotation_level
Definition at line 114 of file stack.c.
Referenced by annotate_arg_begin(), annotate_arg_end(), annotate_arg_name_end(), annotate_arg_value(), annotate_array_section_begin(), annotate_array_section_end(), annotate_breakpoint(), annotate_breakpoints_headers(), annotate_breakpoints_invalid(), annotate_breakpoints_table(), annotate_breakpoints_table_end(), annotate_catchpoint(), annotate_display_begin(), annotate_display_end(), annotate_display_expression(), annotate_display_expression_end(), annotate_display_format(), annotate_display_number_end(), annotate_display_value(), annotate_elt(), annotate_elt_rep(), annotate_elt_rep_end(), annotate_error(), annotate_error_begin(), annotate_exited(), annotate_field(), annotate_field_begin(), annotate_field_end(), annotate_field_name_end(), annotate_field_value(), annotate_frame_address(), annotate_frame_address_end(), annotate_frame_args(), annotate_frame_begin(), annotate_frame_end(), annotate_frame_function_name(), annotate_frame_source_begin(), annotate_frame_source_end(), annotate_frame_source_file(), annotate_frame_source_file_end(), annotate_frame_source_line(), annotate_frame_where(), annotate_frames_invalid(), annotate_function_call(), annotate_new_thread(), annotate_quit(), annotate_record(), annotate_signal(), annotate_signal_handler_caller(), annotate_signal_name(), annotate_signal_name_end(), annotate_signal_string(), annotate_signal_string_end(), annotate_signalled(), annotate_source(), annotate_starting(), annotate_stopped(), annotate_thread_changed(), annotate_value_begin(), annotate_value_end(), annotate_value_history_begin(), annotate_value_history_end(), annotate_value_history_value(), annotate_watchpoint(), ATTRIBUTE_PRINTF(), captured_main(), command_line_handler(), command_line_input(), init_main(), line_info(), print_frame_info(), prompt_for_continue(), and top_level_prompt().
char* current_directory
Definition at line 122 of file top.c.
Referenced by add_path(), bsd_kvm_open(), captured_main(), cd_command(), core_open(), gdb_init(), Gdbtk_Init(), go32_wait(), init_history(), m32r_upload_command(), openp(), pwd_command(), set_history_filename(), shell_escape(), and tfile_open().
int dbx_commands
Definition at line 59 of file main.c.
Referenced by _initialize_cli_cmds(), and captured_main().
char* debug_file_directory
Definition at line 1368 of file symfile.c.
Referenced by build_id_to_debug_bfd(), captured_main(), find_separate_debug_file(), open_dwo_file(), open_dwp_file(), try_open_dwop_file(), and VEC().
void(* deprecated_attach_hook)(void)
Definition at line 229 of file top.c.
Referenced by attach_command_post_wait(), and gdbtk_add_hooks().
void(* deprecated_call_command_hook)(struct cmd_list_element *c, char *cmd, int from_tty)
Definition at line 252 of file top.c.
Referenced by clear_interpreter_hooks(), execute_command(), and gdbtk_add_hooks().
void(* deprecated_context_hook)(int)
Definition at line 262 of file top.c.
Referenced by clear_interpreter_hooks(), gdbtk_add_hooks(), and handle_inferior_event().
void(* deprecated_detach_hook)(void)
Definition at line 230 of file top.c.
Referenced by detach_command(), disconnect_command(), gdbtk_add_hooks(), and generic_mourn_inferior().
int(*) void(*) void(* deprecated_flush_hook)(struct ui_file *stream)
void(* deprecated_init_ui_hook)(char *argv0)
Definition at line 186 of file top.c.
Referenced by _initialize_windows_nat(), clear_interpreter_hooks(), and gdb_init().
void(* deprecated_interactive_hook)(void)
Definition at line 235 of file top.c.
Referenced by clear_interpreter_hooks(), and gdbtk_add_hooks().
void(* deprecated_post_add_symbol_hook)(void)
Definition at line 79 of file symfile.c.
Referenced by gdbtk_add_hooks(), and symbol_file_add_with_addrs().
void(* deprecated_pre_add_symbol_hook)(const char *)
Definition at line 78 of file symfile.c.
Referenced by gdbtk_add_hooks(), and symbol_file_add_with_addrs().
void(* deprecated_print_frame_info_listing_hook)(struct symtab *s, int line, int stopline, int noerror)
Definition at line 198 of file top.c.
Referenced by clear_interpreter_hooks(), gdbtk_add_hooks(), print_frame_info(), tui_install_hooks(), and tui_remove_hooks().
int(* deprecated_query_hook)(const char *, va_list) ATTRIBUTE_FPTR_PRINTF(1
Definition at line 204 of file top.c.
Referenced by ATTRIBUTE_PRINTF(), clear_interpreter_hooks(), gdbtk_add_hooks(), mi_insert_notify_hooks(), mi_remove_notify_hooks(), tui_install_hooks(), and tui_remove_hooks().
void(* deprecated_readline_begin_hook)(char *,...) ATTRIBUTE_FPTR_PRINTF_1
Definition at line 222 of file top.c.
Referenced by clear_interpreter_hooks(), gdbtk_add_hooks(), and read_command_lines().
void(* deprecated_readline_end_hook)(void)
Definition at line 224 of file top.c.
Referenced by clear_interpreter_hooks(), gdbtk_add_hooks(), and read_command_lines().
char*(* deprecated_readline_hook)(char *)
Definition at line 223 of file top.c.
Referenced by clear_interpreter_hooks(), command_line_input(), gdbtk_add_hooks(), and read_next_line().
void(* deprecated_register_changed_hook)(int regno)
Definition at line 240 of file top.c.
Referenced by clear_interpreter_hooks(), gdbtk_add_hooks(), tui_install_hooks(), tui_remove_hooks(), and value_assign().
void(* deprecated_set_hook)(struct cmd_list_element *c)
Definition at line 258 of file top.c.
Referenced by do_set_command(), and gdbtk_add_hooks().
void(* deprecated_show_load_progress)(const char *section, unsigned long section_sent, unsigned long section_size, unsigned long total_sent, unsigned long total_size)
Definition at line 73 of file symfile.c.
Referenced by load_progress(), and mi_interpreter_resume().
ptid_t(* deprecated_target_wait_hook)(ptid_t ptid, struct target_waitstatus *status, int options)
Definition at line 245 of file top.c.
Referenced by clear_interpreter_hooks(), fetch_inferior_event(), gdbtk_add_hooks(), prepare_for_detach(), and wait_for_inferior().
int(* deprecated_ui_load_progress_hook)(const char *section, unsigned long num)
Definition at line 71 of file symfile.c.
Referenced by gdbtk_add_hooks(), load_progress(), and load_srec().
int(* deprecated_ui_loop_hook)(int signo)
Definition at line 193 of file top.c.
Referenced by do_hardwire_readchar(), do_ser_base_readchar(), gdb_os_poll_quit(), gdbtk_add_hooks(), wait_for_connect(), and windows_wait().
int(*) void(* deprecated_warning_hook)(const char *, va_list) ATTRIBUTE_FPTR_PRINTF(1
Definition at line 208 of file top.c.
Referenced by clear_interpreter_hooks(), gdbtk_add_hooks(), and vwarning().
char* gdb_datadir
Definition at line 65 of file main.c.
Referenced by captured_main(), get_init_files(), init_main(), and VEC().
char* gdb_sysroot
Definition at line 62 of file main.c.
Referenced by _initialize_solib(), captured_main(), find_separate_debug_file(), follow_exec(), gdbsim_open(), and solib_find().
int immediate_quit
Referenced by command_line_input(), handle_sigint(), mips_expect_timeout(), monitor_expect(), remote_start_remote(), throw_exception(), tui_redisplay_readline(), tui_rl_startup_hook(), vfprintf_maybe_filtered(), and x_event().
int info_verbose
Definition at line 1569 of file top.c.
Referenced by _initialize_cli_cmds(), add_memrange(), add_register(), add_static_trace_data(), backtrace_command_1(), check_frame_language_change(), checkpoint_command(), close_with_trace(), collect_symbol(), dbx_psymtab_to_symtab_1(), dbx_read_symtab(), dwarf2_read_symtab(), encode_actions_1(), fbsd_find_memory_regions(), gcore_command(), gcore_create_callback(), handle_vfork_child_exec_or_exit(), ioctl_with_trace(), linux_child_follow_fork(), lm_addr_check(), map_overlay_command(), mdebug_read_symtab(), merge_uploaded_trace_state_variables(), open_with_trace(), overlay_auto_command(), overlay_manual_command(), overlay_off_command(), parse_external(), post_create_inferior(), print_section_info(), procfs_note(), procfs_wait(), psymtab_to_symtab_1(), remote_resume(), restore_command(), set_verbose(), show_info_verbose(), sol_thread_resume(), sol_thread_wait(), solib_add(), solib_read_symbols(), stringify_collection_list(), svr4_exec_displacement(), symbol_file_add_with_addrs(), tfind_1(), wait_with_trace(), windows_delete_thread(), xcoff_psymtab_to_symtab_1(), and xcoff_read_symtab().
unsigned input_radix
Definition at line 170 of file valprint.c.
Referenced by breakpoint_re_set(), classify_name(), init_raw_breakpoint_without_location(), lex_one_token(), parse_number(), prepare_re_set_context(), set_input_radix_1(), show_radix(), varobj_set_value(), and yylex().
char* interpreter_p
Definition at line 53 of file main.c.
Referenced by _initialize_tui_interp(), captured_main(), and interp_set().
unsigned output_radix
Definition at line 180 of file valprint.c.
Referenced by set_output_radix_1(), and show_radix().
char* python_libdir
Definition at line 74 of file main.c.
Referenced by _initialize_python(), and captured_main().
void(* selected_frame_level_changed_hook)(int)
char* source_path
Definition at line 70 of file source.c.
Referenced by directory_command(), directory_switch(), find_and_open_script(), find_and_open_source(), Gdbtk_Init(), init_source_path(), mi_cmd_env_dir(), set_directories_command(), show_directories_1(), and source_full_path_of().
int use_windows
Definition at line 91 of file top.c.
Referenced by captured_main(), and gdb_main().
int watchdog
Definition at line 76 of file maint.c.
Referenced by getpkt_or_notif_sane_1(), mips_readchar(), and monitor_wait().
int xdb_commands
Definition at line 56 of file main.c.
Referenced by _initialize_cli_cmds(), _initialize_tui_layout(), _initialize_tui_regs(), _initialize_tui_win(), captured_main(), command_line_is_silent(), find_command_name_length(), and initialize_utils().