GDB (xrefs): /home/stan/gdb/src/gdb/demangle.c File Reference
/home/stan/gdb/src/gdb/demangle.c File Reference
#include "defs.h"
#include "command.h"
#include "gdbcmd.h"
#include "demangle.h"
#include "gdb-demangle.h"
#include "gdb_string.h"
Defines
#define DEFAULT_DEMANGLING_STYLE AUTO_DEMANGLING_STYLE_STRING
Functions
static void show_demangle (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static void show_asm_demangle (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static void show_demangling_style_names (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static void set_demangling_command (char *ignore, int from_tty, struct cmd_list_element *c)
int is_cplus_marker (int c)
void _initialize_demangler (void)
Variables
int demangle = 1
int asm_demangle = 0
static const char * current_demangling_style_string
static const char ** demangling_style_names
static char cplus_markers [] = {'$', '.', '\0'}
initialize_file_ftype _initialize_demangler
Define Documentation
#define DEFAULT_DEMANGLING_STYLE AUTO_DEMANGLING_STYLE_STRING
Definition at line 42 of file demangle.c.
Referenced by _initialize_demangler().
Function Documentation
void _initialize_demangler (void)
Definition at line 159 of file demangle.c.
References _, _initialize_demangler, add_setshow_boolean_cmd(), add_setshow_enum_cmd(), asm_demangle, class_support, current_demangling_style_string, DEFAULT_DEMANGLING_STYLE, demangle, demangling_style_names, set_demangling_command(), setlist, setprintlist, show_asm_demangle(), show_demangle(), show_demangling_style_names(), showlist, showprintlist, and xcalloc().
int is_cplus_marker (int c)
Definition at line 151 of file demangle.c.
References cplus_markers, and strchr().
Referenced by define_symbol(), gnuv2_is_destructor_name(), gnuv2_is_vtable_name(), is_vtable_name(), java_type_print_base(), parse_symbol(), pascal_type_print_base(), read_member_functions(), read_struct_fields(), read_tilde_fields(), and vb_match().
static void set_demangling_command (char * ignore, int from_tty, struct cmd_list_element * c) [static]
Definition at line 106 of file demangle.c.
References current_demangling_style_string, demangling_style_names, and gdb_assert.
Referenced by _initialize_demangler().
static void show_asm_demangle (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 62 of file demangle.c.
References _, and fprintf_filtered().
Referenced by _initialize_demangler().
static void show_demangle (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 49 of file demangle.c.
References _, and fprintf_filtered().
Referenced by _initialize_demangler().
static void show_demangling_style_names (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 82 of file demangle.c.
References _, and fprintf_filtered().
Referenced by _initialize_demangler().
Variable Documentation
initialize_file_ftype _initialize_demangler
Referenced by _initialize_demangler(), and initialize_all_files().
int asm_demangle = 0
Definition at line 59 of file demangle.c.
Referenced by _initialize_demangler(), build_address_symbolic(), and print_address().
char cplus_markers[] = {'$', '.', '\0'} [static]
Definition at line 146 of file demangle.c.
Referenced by is_cplus_marker().
const char* current_demangling_style_string [static]
Definition at line 75 of file demangle.c.
Referenced by _initialize_demangler(), and set_demangling_command().
int demangle = 1
Definition at line 46 of file demangle.c.
Referenced by _initialize_demangler(), c_val_print(), f_val_print(), fprintf_symbol_filtered(), generic_val_print(), gnuv3_print_method_ptr(), java_val_print(), pascal_val_print(), print_breakpoint_location(), print_function_pointer_address(), and tui_get_function_from_frame().
const char** demangling_style_names [static]
Definition at line 80 of file demangle.c.
Referenced by _initialize_demangler(), and set_demangling_command().