GDB (xrefs): /home/stan/gdb/src/gdb/dicos-tdep.c File Reference
/home/stan/gdb/src/gdb/dicos-tdep.c File Reference
#include "defs.h"
#include "osabi.h"
#include "gdb_string.h"
#include "solib.h"
#include "solib-target.h"
#include "inferior.h"
#include "dicos-tdep.h"
Functions
void dicos_init_abi (struct gdbarch *gdbarch)
int dicos_load_module_p (bfd *abfd, int header_size)
Function Documentation
void dicos_init_abi (struct gdbarch * gdbarch)
Definition at line 29 of file dicos-tdep.c.
References gdbarch_tdep(), set_gdbarch_decr_pc_after_break(), set_gdbarch_has_global_breakpoints(), set_gdbarch_has_global_solist(), set_solib_ops(), and solib_target_so_ops.
Referenced by amd64_dicos_init_abi(), and i386_dicos_init_abi().
int dicos_load_module_p (bfd * abfd, int header_size)
Definition at line 57 of file dicos-tdep.c.
References _, warning(), xfree(), and xmalloc().
Referenced by amd64_dicos_osabi_sniffer(), and i386_dicos_osabi_sniffer().