GDB (xrefs): /home/stan/gdb/src/gdb/dictionary.h File Reference
/home/stan/gdb/src/gdb/dictionary.h File Reference
#include "symfile.h"
Classes
struct dict_iterator
Defines
#define ALL_DICT_SYMBOLS(dict, iter, sym)
Functions
struct dictionary * dict_create_hashed (struct obstack *obstack, const struct pending *symbol_list)
struct dictionary * dict_create_hashed_expandable (void)
struct dictionary * dict_create_linear (struct obstack *obstack, const struct pending *symbol_list)
struct dictionary * dict_create_linear_expandable (void)
void dict_free (struct dictionary *dict)
void dict_add_symbol (struct dictionary *dict, struct symbol *sym)
void dict_add_pending (struct dictionary *dict, const struct pending *symbol_list)
int dict_empty (struct dictionary *dict)
struct symbol * dict_iterator_first (const struct dictionary *dict, struct dict_iterator *iterator)
struct symbol * dict_iterator_next (struct dict_iterator *iterator)
struct symbol * dict_iter_name_first (const struct dictionary *dict, const char *name, struct dict_iterator *iterator)
struct symbol * dict_iter_name_next (const char *name, struct dict_iterator *iterator)
struct symbol * dict_iter_match_first (const struct dictionary *dict, const char *name, symbol_compare_ftype *compare, struct dict_iterator *iterator)
struct symbol * dict_iter_match_next (const char *name, symbol_compare_ftype *compare, struct dict_iterator *iterator)
int dict_size (const struct dictionary *dict)
Define Documentation
#define ALL_DICT_SYMBOLS (dict, iter, sym)
Value:
for ((sym) = dict_iterator_first ((dict), &(iter));     \
             (sym);                                             \
             (sym) = dict_iterator_next (&(iter)))
Definition at line 179 of file dictionary.h.
Referenced by dump_symtab_1(), end_symtab_from_static_block(), finish_block_internal(), and objfile_relocate1().
Function Documentation
void dict_add_pending (struct dictionary * dict, const struct pending * symbol_list)
Definition at line 505 of file dictionary.c.
References dict_add_symbol(), pending::next, pending::nsyms, and pending::symbol.
Referenced by augment_type_symtab(), and finish_block_internal().
void dict_add_symbol (struct dictionary * dict, struct symbol * sym)
Definition at line 496 of file dictionary.c.
References add_symbol(), and DICT_VECTOR.
Referenced by add_class_symtab_symbol(), add_symbol(), and dict_add_pending().
struct dictionary* dict_create_hashed (struct obstack * obstack, const struct pending * symbol_list) [read]
Definition at line 357 of file dictionary.c.
References DICT_HASHED_BUCKETS, DICT_HASHED_NBUCKETS, dict_hashed_vector, DICT_HASHTABLE_SIZE, DICT_VECTOR, insert_symbol_hashed(), memset(), pending::next, pending::nsyms, and pending::symbol.
Referenced by finish_block_internal().
struct dictionary* dict_create_hashed_expandable (void) [read]
Definition at line 401 of file dictionary.c.
References DICT_EXPANDABLE_INITIAL_CAPACITY, DICT_HASHED_BUCKETS, DICT_HASHED_EXPANDABLE_NSYMS, dict_hashed_expandable_vector, DICT_HASHED_NBUCKETS, DICT_VECTOR, xcalloc(), and xmalloc().
Referenced by finish_block_internal(), get_java_class_symtab(), and new_block().
struct dictionary* dict_create_linear (struct obstack * obstack, const struct pending * symbol_list) [read]
Definition at line 421 of file dictionary.c.
References DICT_LINEAR_NSYMS, DICT_LINEAR_SYMS, dict_linear_vector, DICT_VECTOR, pending::next, pending::nsyms, and pending::symbol.
Referenced by finalize_symtab(), finish_block_internal(), and get_java_class_symtab().
struct dictionary* dict_create_linear_expandable (void) [read]
Definition at line 466 of file dictionary.c.
References DICT_EXPANDABLE_INITIAL_CAPACITY, DICT_LINEAR_EXPANDABLE_CAPACITY, dict_linear_expandable_vector, DICT_LINEAR_NSYMS, DICT_LINEAR_SYMS, DICT_VECTOR, and xmalloc().
Referenced by new_block().
int dict_empty (struct dictionary * dict)
Definition at line 581 of file dictionary.c.
References dict_iterator_first().
void dict_free (struct dictionary * dict)
Definition at line 488 of file dictionary.c.
References DICT_VECTOR, and free().
Referenced by jv_per_objfile_free().
struct symbol* dict_iter_match_first (const struct dictionary * dict, const char * name, symbol_compare_ftype * compare, struct dict_iterator * iterator) [read]
Definition at line 552 of file dictionary.c.
References DICT_VECTOR.
Referenced by block_iter_match_first(), block_iter_match_step(), and dict_iter_name_first().
struct symbol* dict_iter_match_next (const char * name, symbol_compare_ftype * compare, struct dict_iterator * iterator) [read]
Definition at line 561 of file dictionary.c.
References DICT_ITERATOR_DICT, and DICT_VECTOR.
Referenced by block_iter_match_next(), block_iter_match_step(), and dict_iter_name_next().
struct symbol* dict_iter_name_first (const struct dictionary * dict, const char * name, struct dict_iterator * iterator) [read]
Definition at line 538 of file dictionary.c.
References dict_iter_match_first(), and strcmp_iw().
Referenced by block_iter_name_first(), and block_iter_name_step().
struct symbol* dict_iter_name_next (const char * name, struct dict_iterator * iterator) [read]
Definition at line 546 of file dictionary.c.
References dict_iter_match_next(), and strcmp_iw().
Referenced by block_iter_name_next(), and block_iter_name_step().
struct symbol* dict_iterator_first (const struct dictionary * dict, struct dict_iterator * iterator) [read]
Definition at line 521 of file dictionary.c.
References DICT_VECTOR.
Referenced by block_iterator_first(), block_iterator_step(), and dict_empty().
struct symbol* dict_iterator_next (struct dict_iterator * iterator) [read]
Definition at line 531 of file dictionary.c.
References DICT_ITERATOR_DICT, and DICT_VECTOR.
Referenced by block_iterator_next(), and block_iterator_step().
int dict_size (const struct dictionary * dict)
Definition at line 569 of file dictionary.c.
References DICT_VECTOR.
Referenced by dump_symtab_1().