GDB (xrefs): /home/stan/gdb/src/gdb/dink32-rom.c File Reference
/home/stan/gdb/src/gdb/dink32-rom.c File Reference
#include "defs.h"
#include "gdbcore.h"
#include "target.h"
#include "monitor.h"
#include "serial.h"
#include "symfile.h"
#include "inferior.h"
#include "regcache.h"
Functions
static void dink32_open (char *args, int from_tty)
static void dink32_supply_register (struct regcache *regcache, char *regname, int regnamelen, char *val, int vallen)
void _initialize_dink32_rom (void)
Variables
static char * dink32_regnames []
static struct target_ops dink32_ops
static char * dink32_inits []
static struct monitor_ops dink32_cmds
initialize_file_ftype _initialize_dink32_rom
Function Documentation
void _initialize_dink32_rom (void)
Definition at line 134 of file dink32-rom.c.
References _initialize_dink32_rom, add_target(), monitor_ops::clr_break, regrw_cmd::cmd, memrw_cmd::cmdb, memrw_cmd::cmdl, memrw_cmd::cmdw, monitor_ops::cont, dink32_cmds, dink32_inits, dink32_open(), dink32_ops, dink32_regnames, dink32_supply_register(), monitor_ops::dump_registers, monitor_ops::fill, monitor_ops::flags, monitor_ops::getmem, monitor_ops::getreg, monitor_ops::init, init_monitor_ops(), monitor_ops::line_term, monitor_ops::load, monitor_ops::loadresp, monitor_ops::magic, MO_32_REGS_PAIRED, MO_CLR_BREAK_1_BASED, MO_FILL_USES_ADDR, MO_GETMEM_16_BOUNDARY, MO_GETMEM_NEEDS_RANGE, MO_HANDLE_NL, MO_HEX_PREFIX, MO_SETMEM_INTERACTIVE, MO_SETREG_INTERACTIVE, MO_SREC_ACK, MO_SREC_ACK_ROTATE, MONITOR_OPS_MAGIC, monitor_ops::prompt, monitor_ops::register_pattern, monitor_ops::regnames, memrw_cmd::resp_delim, regrw_cmd::resp_delim, SERIAL_1_STOPBITS, monitor_ops::set_break, monitor_ops::setmem, monitor_ops::setreg, monitor_ops::step, monitor_ops::stopbits, monitor_ops::supply_register, monitor_ops::target, memrw_cmd::term, regrw_cmd::term, target_ops::to_doc, target_ops::to_longname, target_ops::to_open, and target_ops::to_shortname.
static void dink32_open (char * args, int from_tty) [static]
Definition at line 126 of file dink32-rom.c.
References dink32_cmds, and monitor_open().
Referenced by _initialize_dink32_rom().
static void dink32_supply_register (struct regcache * regcache, char * regname, int regnamelen, char * val, int vallen) [static]
Definition at line 32 of file dink32-rom.c.
References monitor_supply_register().
Referenced by _initialize_dink32_rom().
Variable Documentation
initialize_file_ftype _initialize_dink32_rom
Referenced by _initialize_dink32_rom(), and initialize_all_files().
struct monitor_ops dink32_cmds [static]
Definition at line 123 of file dink32-rom.c.
Referenced by _initialize_dink32_rom(), and dink32_open().
char* dink32_inits[] [static]
Initial value:
{"\r", NULL}
Definition at line 120 of file dink32-rom.c.
Referenced by _initialize_dink32_rom().
struct target_ops dink32_ops [static]
Definition at line 118 of file dink32-rom.c.
Referenced by _initialize_dink32_rom().
char* dink32_regnames[] [static]
Initial value:
{
  "r0", "r1", "r2", "r3", "r4", "r5", "r6", "r7",
  "r8", "r9", "r10", "r11", "r12", "r13", "r14", "r15",
  "r16", "r17", "r18", "r19", "r20", "r21", "r22", "r23",
  "r24", "r25", "r26", "r27", "r28", "r29", "r30", "r31",
  "f0", "f1", "f2", "f3", "f4", "f5", "f6", "f7",
  "f8", "f9", "f10", "f11", "f12", "f13", "f14", "f15",
  "f16", "f17", "f18", "f19", "f20", "f21", "f22", "f23",
  "f24", "f25", "f26", "f27", "f28", "f29", "f30", "f31",
  "srr0", "msr", "cr", "lr", "ctr", "xer", "xer"
}
Definition at line 103 of file dink32-rom.c.
Referenced by _initialize_dink32_rom().