GDB (xrefs): /home/stan/gdb/src/gdb/disasm.h File Reference
/home/stan/gdb/src/gdb/disasm.h File Reference
Defines
#define DISASSEMBLY_SOURCE (0x1 << 0)
#define DISASSEMBLY_RAW_INSN (0x1 << 1)
#define DISASSEMBLY_OMIT_FNAME (0x1 << 2)
#define DISASSEMBLY_FILENAME (0x1 << 3)
#define DISASSEMBLY_OMIT_PC (0x1 << 4)
Functions
void gdb_disassembly (struct gdbarch *gdbarch, struct ui_out *uiout, char *file_string, int flags, int how_many, CORE_ADDR low, CORE_ADDR high)
int gdb_print_insn (struct gdbarch *gdbarch, CORE_ADDR memaddr, struct ui_file *stream, int *branch_delay_insns)
int gdb_insn_length (struct gdbarch *gdbarch, CORE_ADDR memaddr)
int gdb_buffered_insn_length (struct gdbarch *gdbarch, const gdb_byte *insn, int max_len, CORE_ADDR memaddr)
Define Documentation
#define DISASSEMBLY_FILENAME (0x1 << 3)
Definition at line 25 of file disasm.h.
Referenced by do_mixed_source_and_assembly(), and get_insn_history_modifiers().
#define DISASSEMBLY_OMIT_FNAME (0x1 << 2)
Definition at line 24 of file disasm.h.
Referenced by disassemble_command(), dump_insns(), and get_insn_history_modifiers().
#define DISASSEMBLY_OMIT_PC (0x1 << 4)
Definition at line 26 of file disasm.h.
Referenced by dump_insns(), and get_insn_history_modifiers().
#define DISASSEMBLY_RAW_INSN (0x1 << 1)
Definition at line 23 of file disasm.h.
Referenced by disassemble_command(), do_gdb_disassembly(), dump_insns(), get_insn_history_modifiers(), and mi_cmd_disassemble().
#define DISASSEMBLY_SOURCE (0x1 << 0)
Definition at line 22 of file disasm.h.
Referenced by disassemble_command(), gdb_disassembly(), get_insn_history_modifiers(), and mi_cmd_disassemble().
Function Documentation
int gdb_buffered_insn_length (struct gdbarch * gdbarch, const gdb_byte * insn, int max_len, CORE_ADDR memaddr)
Definition at line 527 of file disasm.c.
References gdb_buffered_insn_length_init_dis(), and gdbarch_print_insn().
Referenced by amd64_relocate_instruction(), fixup_riprel(), and i386_relocate_instruction().
void gdb_disassembly (struct gdbarch * gdbarch, struct ui_out * uiout, char * file_string, int flags, int how_many, CORE_ADDR low, CORE_ADDR high)
Definition at line 407 of file disasm.c.
References DISASSEMBLY_SOURCE, do_assembly_only(), do_cleanups(), do_mixed_source_and_assembly(), find_pc_symtab(), gdb_disassemble_info(), gdb_flush(), gdb_stdout, linetable::item, symtab::linetable, make_cleanup_ui_file_delete(), mem_fileopen(), and linetable::nitems.
Referenced by btrace_insn_history(), do_gdb_disassembly(), mi_cmd_disassemble(), and print_disassembly().
int gdb_insn_length (struct gdbarch * gdbarch, CORE_ADDR memaddr)
Definition at line 474 of file disasm.c.
References do_ui_file_delete(), gdb_print_insn(), make_final_cleanup(), and ui_file_new().
Referenced by VEC().
int gdb_print_insn (struct gdbarch * gdbarch, CORE_ADDR memaddr, struct ui_file * stream, int * branch_delay_insns)
Definition at line 446 of file disasm.c.
References gdb_disassemble_info(), and gdbarch_print_insn().
Referenced by archpy_disassemble(), gdb_insn_length(), gdbtk_load_asm(), i386_fast_tracepoint_valid_at(), print_formatted(), and tui_disassemble().