GDB (xrefs): /home/stan/gdb/src/gdb/doublest.h File Reference
/home/stan/gdb/src/gdb/doublest.h File Reference
#include "floatformat.h"
Defines
#define DOUBLEST_PRINT_FORMAT "g"
#define DOUBLEST_SCAN_FORMAT "lg"
Typedefs
typedef double DOUBLEST
Enumerations
enum float_kind {
float_nan, float_infinite, float_zero, float_normal,
float_subnormal
}
Functions
void floatformat_to_doublest (const struct floatformat *, const void *in, DOUBLEST *out)
void floatformat_from_doublest (const struct floatformat *, const DOUBLEST *in, void *out)
int floatformat_is_negative (const struct floatformat *, const bfd_byte *)
enum float_kind floatformat_classify (const struct floatformat *, const bfd_byte *)
const char * floatformat_mantissa (const struct floatformat *, const bfd_byte *)
struct floatformat * floatformat_from_type (const struct type *type)
DOUBLEST extract_typed_floating (const void *addr, const struct type *type)
void store_typed_floating (void *addr, const struct type *type, DOUBLEST val)
void convert_typed_floating (const void *from, const struct type *from_type, void *to, const struct type *to_type)
Define Documentation
#define DOUBLEST_PRINT_FORMAT "g"
Definition at line 54 of file doublest.h.
Referenced by decimal_from_floating().
#define DOUBLEST_SCAN_FORMAT "lg"
Definition at line 55 of file doublest.h.
Referenced by ada_delta(), parse_float(), processReal(), and scaling_factor().
Typedef Documentation
typedef double DOUBLEST
Definition at line 24 of file doublest.h.
Enumeration Type Documentation
enum float_kind
Enumerator:
float_nan
float_infinite
float_zero
float_normal
float_subnormal
Definition at line 66 of file doublest.h.
Function Documentation
void convert_typed_floating (const void * from, const struct type * from_type, void * to, const struct type * to_type)
Definition at line 864 of file doublest.c.
References _, floatformat_from_doublest(), floatformat_from_type(), floatformat_to_doublest(), memcpy(), memset(), min, TYPE_LENGTH, and warning().
Referenced by do_ppc_sysv_return_value(), i386_extract_return_value(), i386_store_return_value(), i387_register_to_value(), i387_value_to_register(), ia64_extract_return_value(), ia64_push_dummy_call(), ia64_register_to_value(), ia64_store_return_value(), ia64_value_to_register(), m68k_register_to_value(), m68k_svr4_extract_return_value(), m68k_svr4_store_return_value(), m68k_value_to_register(), ppc64_sysv_abi_push_dummy_call(), ppc64_sysv_abi_push_float(), ppc64_sysv_abi_return_value(), ppc_sysv_abi_push_dummy_call(), rs6000_lynx178_push_dummy_call(), rs6000_lynx178_return_value(), rs6000_push_dummy_call(), rs6000_register_to_value(), rs6000_return_value(), and rs6000_value_to_register().
DOUBLEST extract_typed_floating (const void * addr, const struct type * type)
Definition at line 819 of file doublest.c.
References floatformat_from_type(), and floatformat_to_doublest().
Referenced by print_i387_value(), sh64_register_convert_to_raw(), sh_register_convert_to_raw(), unpack_double(), and unpack_long().
enum float_kind floatformat_classify (const struct floatformat * , const bfd_byte *)
Definition at line 534 of file doublest.c.
References float_infinite, float_nan, float_normal, float_subnormal, float_zero, FLOATFORMAT_CHAR_BIT, FLOATFORMAT_LARGEST_BYTES, floatformat_normalize_byteorder(), gdb_assert, get_field(), and min.
Referenced by convert_floatformat_to_doublest(), and print_floating().
void floatformat_from_doublest (const struct floatformat * , const DOUBLEST * in, void * out)
Definition at line 729 of file doublest.c.
References convert_doublest_to_floatformat(), gdb_assert, host_double_format, host_float_format, host_long_double_format, and memcpy().
Referenced by convert_doublest_to_floatformat(), convert_from_extended(), convert_to_extended(), convert_typed_floating(), sh64_register_convert_to_raw(), sh_register_convert_to_raw(), and store_typed_floating().
struct floatformat* floatformat_from_type (const struct type * type) [read]
Definition at line 804 of file doublest.c.
References floatformat_from_length(), gdb_assert, gdbarch_byte_order(), get_type_arch(), TYPE_CODE, TYPE_CODE_FLT, TYPE_FLOATFORMAT, and TYPE_LENGTH.
Referenced by arm_extract_return_value(), arm_store_return_value(), convert_typed_floating(), extract_typed_floating(), print_floating(), store_typed_floating(), and unpack_double().
int floatformat_is_negative (const struct floatformat * , const bfd_byte *)
Definition at line 508 of file doublest.c.
References FLOATFORMAT_CHAR_BIT, FLOATFORMAT_LARGEST_BYTES, floatformat_normalize_byteorder(), gdb_assert, and get_field().
Referenced by print_floating().
const char* floatformat_mantissa (const struct floatformat * , const bfd_byte *)
Definition at line 621 of file doublest.c.
References FLOATFORMAT_CHAR_BIT, FLOATFORMAT_LARGEST_BYTES, floatformat_normalize_byteorder(), gdb_assert, get_field(), len, and xsnprintf().
Referenced by print_floating().
void floatformat_to_doublest (const struct floatformat * , const void * in, DOUBLEST * out)
Definition at line 699 of file doublest.c.
References convert_floatformat_to_doublest(), gdb_assert, host_double_format, host_float_format, host_long_double_format, and memcpy().
Referenced by convert_floatformat_to_doublest(), convert_from_extended(), convert_to_extended(), convert_typed_floating(), extract_typed_floating(), sh64_extract_return_value(), sh64_register_convert_to_virtual(), and sh_register_convert_to_virtual().
void store_typed_floating (void * addr, const struct type * type, DOUBLEST val)
Definition at line 832 of file doublest.c.
References floatformat_from_doublest(), floatformat_from_type(), memset(), and TYPE_LENGTH.
Referenced by define_symbol(), scalar_binop(), sh64_extract_return_value(), sh64_register_convert_to_virtual(), sh_register_convert_to_virtual(), and value_from_double().