GDB (xrefs): /home/stan/gdb/src/gdb/dummy-frame.h File Reference
/home/stan/gdb/src/gdb/dummy-frame.h File Reference
#include "frame.h"
Functions
void dummy_frame_push (struct infcall_suspend_state *caller_state, const struct frame_id *dummy_id)
void dummy_frame_pop (struct frame_id dummy_id)
void dummy_frame_discard (struct frame_id dummy_id)
Variables
struct frame_unwind dummy_frame_unwind
Function Documentation
void dummy_frame_discard (struct frame_id dummy_id)
Definition at line 165 of file dummy-frame.c.
References lookup_dummy_frame(), and remove_dummy_frame().
Referenced by check_longjmp_breakpoint_for_call_dummy().
void dummy_frame_pop (struct frame_id dummy_id)
Definition at line 151 of file dummy-frame.c.
References gdb_assert, lookup_dummy_frame(), and pop_dummy_frame().
Referenced by call_function_by_hand(), and frame_pop().
void dummy_frame_push (struct infcall_suspend_state * caller_state, const struct frame_id * dummy_id)
Definition at line 54 of file dummy-frame.c.
References dummy_frame::caller_state, dummy_frame_stack, dummy_frame::id, dummy_frame::next, and XZALLOC.
Referenced by call_function_by_hand().
Variable Documentation
struct frame_unwind dummy_frame_unwind
Definition at line 281 of file dummy-frame.c.
Referenced by frame_unwind_init().