GDB (xrefs): /home/stan/gdb/src/gdb/dummy-frame.c File Reference
/home/stan/gdb/src/gdb/dummy-frame.c File Reference
#include "defs.h"
#include "dummy-frame.h"
#include "regcache.h"
#include "frame.h"
#include "inferior.h"
#include "gdb_assert.h"
#include "frame-unwind.h"
#include "command.h"
#include "gdbcmd.h"
#include "gdb_string.h"
#include "observer.h"
#include "gdbthread.h"
Classes
struct dummy_frame
struct dummy_frame_cache
Functions
void dummy_frame_push (struct infcall_suspend_state *caller_state, const struct frame_id *dummy_id)
static void remove_dummy_frame (struct dummy_frame **dummy_ptr)
static int pop_dummy_frame_bpt (struct breakpoint *b, void *dummy_voidp)
static void pop_dummy_frame (struct dummy_frame **dummy_ptr)
static struct dummy_frame ** lookup_dummy_frame (struct frame_id dummy_id)
void dummy_frame_pop (struct frame_id dummy_id)
void dummy_frame_discard (struct frame_id dummy_id)
static void cleanup_dummy_frames (struct target_ops *target, int from_tty)
static int dummy_frame_sniffer (const struct frame_unwind *self, struct frame_info *this_frame, void **this_prologue_cache)
static struct value * dummy_frame_prev_register (struct frame_info *this_frame, void **this_prologue_cache, int regnum)
static void dummy_frame_this_id (struct frame_info *this_frame, void **this_prologue_cache, struct frame_id *this_id)
static void fprint_dummy_frames (struct ui_file *file)
static void maintenance_print_dummy_frames (char *args, int from_tty)
void _initialize_dummy_frame (void)
Variables
static struct dummy_frame * dummy_frame_stack = NULL
struct frame_unwind dummy_frame_unwind
Function Documentation
void _initialize_dummy_frame (void)
static void cleanup_dummy_frames (struct target_ops * target, int from_tty) [static]
Definition at line 179 of file dummy-frame.c.
References remove_dummy_frame().
void dummy_frame_discard (struct frame_id dummy_id)
Definition at line 165 of file dummy-frame.c.
References lookup_dummy_frame(), and remove_dummy_frame().
Referenced by check_longjmp_breakpoint_for_call_dummy().
void dummy_frame_pop (struct frame_id dummy_id)
Definition at line 151 of file dummy-frame.c.
References gdb_assert, lookup_dummy_frame(), and pop_dummy_frame().
Referenced by call_function_by_hand(), and frame_pop().
static struct value* dummy_frame_prev_register (struct frame_info * this_frame, void ** this_prologue_cache, int regnum) [static, read]
Definition at line 241 of file dummy-frame.c.
References gdb_assert, get_frame_arch(), not_lval, dummy_frame_cache::prev_regcache, regcache_cooked_read(), register_type(), value_contents_writeable(), and value_zero().
void dummy_frame_push (struct infcall_suspend_state * caller_state, const struct frame_id * dummy_id)
Definition at line 54 of file dummy-frame.c.
References dummy_frame::caller_state, dummy_frame_stack, dummy_frame::id, dummy_frame::next, and XZALLOC.
Referenced by call_function_by_hand().
static int dummy_frame_sniffer (const struct frame_unwind * self, struct frame_info * this_frame, void ** this_prologue_cache) [static]
Definition at line 194 of file dummy-frame.c.
References dummy_frame::caller_state, frame_id_eq(), FRAME_OBSTACK_ZALLOC, gdbarch_dummy_id(), get_frame_arch(), get_infcall_suspend_state_regcache(), dummy_frame::id, dummy_frame::next, dummy_frame_cache::prev_regcache, and dummy_frame_cache::this_id.
static void dummy_frame_this_id (struct frame_info * this_frame, void ** this_prologue_cache, struct frame_id * this_id) [static]
Definition at line 270 of file dummy-frame.c.
References gdb_assert, and dummy_frame_cache::this_id.
static void fprint_dummy_frames (struct ui_file * file) [static]
Definition at line 292 of file dummy-frame.c.
References fprint_frame_id(), fprintf_unfiltered(), gdb_print_host_address(), dummy_frame::id, and dummy_frame::next.
Referenced by maintenance_print_dummy_frames().
static struct dummy_frame** lookup_dummy_frame (struct frame_id dummy_id) [static, read]
Definition at line 128 of file dummy-frame.c.
References frame_id_eq(), and dummy_frame::next.
Referenced by dummy_frame_discard(), and dummy_frame_pop().
static void maintenance_print_dummy_frames (char * args, int from_tty) [static]
Definition at line 307 of file dummy-frame.c.
References _, do_cleanups(), fprint_dummy_frames(), gdb_fopen(), gdb_stdout, make_cleanup_ui_file_delete(), and perror_with_name().
static void pop_dummy_frame (struct dummy_frame ** dummy_ptr) [static]
Definition at line 106 of file dummy-frame.c.
References dummy_frame::caller_state, dummy, iterate_over_breakpoints(), dummy_frame::next, pop_dummy_frame_bpt(), reinit_frame_cache(), restore_infcall_suspend_state(), and xfree().
Referenced by dummy_frame_pop().
static int pop_dummy_frame_bpt (struct breakpoint * b, void * dummy_voidp) [static]
Definition at line 82 of file dummy-frame.c.
References delete_breakpoint(), disp_del, breakpoint::disposition, dummy, breakpoint::frame_id, frame_id_eq(), dummy_frame::id, inferior_ptid, pid_to_thread_id(), breakpoint::related_breakpoint, and breakpoint::thread.
Referenced by pop_dummy_frame().
static void remove_dummy_frame (struct dummy_frame ** dummy_ptr) [static]
Definition at line 69 of file dummy-frame.c.
References dummy_frame::caller_state, discard_infcall_suspend_state(), dummy, dummy_frame::next, and xfree().
Referenced by cleanup_dummy_frames(), and dummy_frame_discard().
Variable Documentation
struct dummy_frame* dummy_frame_stack = NULL [static]
Definition at line 48 of file dummy-frame.c.
Referenced by dummy_frame_push().
struct frame_unwind dummy_frame_unwind
Initial value:
{
  DUMMY_FRAME,
  default_frame_unwind_stop_reason,
  dummy_frame_this_id,
  dummy_frame_prev_register,
  NULL,
  dummy_frame_sniffer,
}
Definition at line 281 of file dummy-frame.c.
Referenced by frame_unwind_init().