GDB (xrefs): /home/stan/gdb/src/gdb/dwarf2-frame.h File Reference
/home/stan/gdb/src/gdb/dwarf2-frame.h File Reference
Classes
struct dwarf2_frame_state_reg
Enumerations
enum dwarf2_frame_reg_rule {
DWARF2_FRAME_REG_UNSPECIFIED = 0, DWARF2_FRAME_REG_UNDEFINED, DWARF2_FRAME_REG_SAVED_OFFSET, DWARF2_FRAME_REG_SAVED_REG,
DWARF2_FRAME_REG_SAVED_EXP, DWARF2_FRAME_REG_SAME_VALUE, DWARF2_FRAME_REG_SAVED_VAL_OFFSET, DWARF2_FRAME_REG_SAVED_VAL_EXP,
DWARF2_FRAME_REG_FN, DWARF2_FRAME_REG_RA, DWARF2_FRAME_REG_RA_OFFSET, DWARF2_FRAME_REG_CFA,
DWARF2_FRAME_REG_CFA_OFFSET
}
Functions
void dwarf2_frame_set_init_reg (struct gdbarch *gdbarch, void(*init_reg)(struct gdbarch *, int, struct dwarf2_frame_state_reg *, struct frame_info *))
void dwarf2_frame_set_signal_frame_p (struct gdbarch *gdbarch, int(*signal_frame_p)(struct gdbarch *, struct frame_info *))
void dwarf2_frame_set_adjust_regnum (struct gdbarch *gdbarch, int(*adjust_regnum)(struct gdbarch *, int, int))
void dwarf2_append_unwinders (struct gdbarch *gdbarch)
struct frame_base * dwarf2_frame_base_sniffer (struct frame_info *this_frame)
CORE_ADDR dwarf2_frame_cfa (struct frame_info *this_frame)
void dwarf2_compile_cfa_to_ax (struct agent_expr *expr, struct axs_value *loc, struct gdbarch *gdbarch, CORE_ADDR pc, struct dwarf2_per_cu_data *data)
Enumeration Type Documentation
enum dwarf2_frame_reg_rule
Enumerator:
DWARF2_FRAME_REG_UNSPECIFIED
DWARF2_FRAME_REG_UNDEFINED
DWARF2_FRAME_REG_SAVED_OFFSET
DWARF2_FRAME_REG_SAVED_REG
DWARF2_FRAME_REG_SAVED_EXP
DWARF2_FRAME_REG_SAME_VALUE
DWARF2_FRAME_REG_SAVED_VAL_OFFSET
DWARF2_FRAME_REG_SAVED_VAL_EXP
DWARF2_FRAME_REG_FN
DWARF2_FRAME_REG_RA
DWARF2_FRAME_REG_RA_OFFSET
DWARF2_FRAME_REG_CFA
DWARF2_FRAME_REG_CFA_OFFSET
Definition at line 34 of file dwarf2-frame.h.
Function Documentation
void dwarf2_append_unwinders (struct gdbarch * gdbarch)
Definition at line 1446 of file dwarf2-frame.c.
References dwarf2_tailcall_frame_unwind, and frame_unwind_append_unwinder().
Referenced by aarch64_gdbarch_init(), alpha_dwarf2_init_abi(), arm_gdbarch_init(), bfin_gdbarch_init(), cris_gdbarch_init(), h8300_gdbarch_init(), hppabsd_init_abi(), i386_gdbarch_init(), iq2000_gdbarch_init(), m68hc11_gdbarch_init(), m68k_gdbarch_init(), microblaze_gdbarch_init(), mips_gdbarch_init(), mn10300_frame_unwind_init(), msp430_gdbarch_init(), mt_gdbarch_init(), nios2_gdbarch_init(), rl78_gdbarch_init(), rs6000_gdbarch_init(), rx_gdbarch_init(), s390_gdbarch_init(), score_gdbarch_init(), sh64_gdbarch_init(), sh_gdbarch_init(), sparc32_linux_init_abi(), sparc64_linux_init_abi(), tic6x_gdbarch_init(), tilegx_gdbarch_init(), v850_gdbarch_init(), xstormy16_gdbarch_init(), and xtensa_gdbarch_init().
void dwarf2_compile_cfa_to_ax (struct agent_expr * expr, struct axs_value * loc, struct gdbarch * gdbarch, CORE_ADDR pc, struct dwarf2_per_cu_data * data)
Definition at line 886 of file dwarf2-frame.c.
References _, dwarf2_cie::addr_size, dwarf2_frame_state::armcc_cfa_offsets_reversed, ax_const_l(), ax_reg(), ax_simple(), dwarf2_frame_state::dwarf2_frame_state_reg_info::cfa_exp, dwarf2_frame_state::dwarf2_frame_state_reg_info::cfa_how, dwarf2_frame_state::dwarf2_frame_state_reg_info::cfa_offset, dwarf2_frame_state::dwarf2_frame_state_reg_info::cfa_reg, dwarf2_fde::cie, dwarf2_frame_state::code_align, dwarf2_cie::code_alignment_factor, dwarf2_frame_state::data_align, dwarf2_cie::data_alignment_factor, dwarf2_compile_expr_to_ax(), dwarf2_frame_find_fde(), dwarf2_frame_find_quirks(), dwarf2_frame_state_copy_regs(), dwarf2_cie::end, dwarf2_fde::end, error(), execute_cfa_program(), gdbarch_dwarf2_reg_to_regnum(), dwarf2_frame_state::initial, dwarf2_cie::initial_instructions, dwarf2_fde::instructions, internal_error(), memset(), dwarf2_frame_state::pc, dwarf2_frame_state::dwarf2_frame_state_reg_info::reg, regnum, dwarf2_frame_state::regs, dwarf2_frame_state::retaddr_column, dwarf2_cie::return_address_register, and text_offset.
Referenced by dwarf2_compile_expr_to_ax().
struct frame_base* dwarf2_frame_base_sniffer (struct frame_info * this_frame) [read]
Definition at line 1481 of file dwarf2-frame.c.
References dwarf2_frame_base, dwarf2_frame_find_fde(), and get_frame_address_in_block().
Referenced by alpha_dwarf2_init_abi(), microblaze_gdbarch_init(), mips_gdbarch_init(), s390_gdbarch_init(), and score_gdbarch_init().
CORE_ADDR dwarf2_frame_cfa (struct frame_info * this_frame)
Definition at line 1496 of file dwarf2-frame.c.
References _, dwarf2_tailcall_frame_unwind, error(), frame_unwinder_is(), get_frame_base(), get_frame_type(), get_frame_unwind_stop_reason(), get_prev_frame(), INLINE_FRAME, NOT_AVAILABLE_ERROR, and throw_error().
Referenced by dwarf2_tailcall_prev_register_first(), and dwarf_expr_frame_cfa().
void dwarf2_frame_set_adjust_regnum (struct gdbarch * gdbarch, int(*)(struct gdbarch *, int, int) adjust_regnum)
Definition at line 828 of file dwarf2-frame.c.
References dwarf2_frame_ops::adjust_regnum, and gdbarch_data().
Referenced by rs6000_gdbarch_init(), and s390_gdbarch_init().
void dwarf2_frame_set_init_reg (struct gdbarch * gdbarch, void(*)(struct gdbarch *, int, struct dwarf2_frame_state_reg *, struct frame_info *) init_reg)
Definition at line 775 of file dwarf2-frame.c.
References gdbarch_data(), and dwarf2_frame_ops::init_reg.
Referenced by aarch64_gdbarch_init(), arm_gdbarch_init(), cris_gdbarch_init(), hppabsd_init_abi(), rs6000_gdbarch_init(), s390_gdbarch_init(), sh_gdbarch_init(), sparc32_gdbarch_init(), sparc64_init_abi(), and tic6x_gdbarch_init().
void dwarf2_frame_set_signal_frame_p (struct gdbarch * gdbarch, int(*)(struct gdbarch *, struct frame_info *) signal_frame_p)
Definition at line 801 of file dwarf2-frame.c.
References gdbarch_data(), and dwarf2_frame_ops::signal_frame_p.
Referenced by i386_darwin_init_abi(), i386_linux_init_abi(), and x86_darwin_init_abi_64().