GDB (xrefs): /home/stan/gdb/src/gdb/dwarf2read.c File Reference
/home/stan/gdb/src/gdb/dwarf2read.c File Reference
#include "defs.h"
#include "bfd.h"
#include "elf-bfd.h"
#include "symtab.h"
#include "gdbtypes.h"
#include "objfiles.h"
#include "dwarf2.h"
#include "buildsym.h"
#include "demangle.h"
#include "gdb-demangle.h"
#include "expression.h"
#include "filenames.h"
#include "macrotab.h"
#include "language.h"
#include "complaints.h"
#include "bcache.h"
#include "dwarf2expr.h"
#include "dwarf2loc.h"
#include "cp-support.h"
#include "hashtab.h"
#include "command.h"
#include "gdbcmd.h"
#include "block.h"
#include "addrmap.h"
#include "typeprint.h"
#include "jv-lang.h"
#include "psympriv.h"
#include "exceptions.h"
#include "gdb_stat.h"
#include "completer.h"
#include "vec.h"
#include "c-lang.h"
#include "go-lang.h"
#include "valprint.h"
#include "gdbcore.h"
#include "gdb/gdb-index.h"
#include <ctype.h>
#include "gdb_bfd.h"
#include "f-lang.h"
#include "source.h"
#include "filestuff.h"
#include "build-id.h"
#include <fcntl.h>
#include "gdb_string.h"
#include "gdb_assert.h"
#include <sys/types.h>
Classes
struct dwarf2_section_info
struct mapped_index
struct dwarf2_per_objfile
struct dwop_section_names
struct comp_unit_head
struct delayed_method_info
struct dwarf2_cu
struct dwarf2_per_cu_data
struct signatured_type
struct stmt_list_hash
struct type_unit_group
struct dwo_sections
struct dwo_unit
struct dwo_file
struct dwp_sections
struct virtual_v1_dwo_sections
struct virtual_v2_dwo_sections
struct dwp_hash_table
struct dwp_file
struct dwz_file
struct die_reader_specs
struct line_header
struct line_header::file_entry
struct partial_die_info
struct abbrev_info
struct attr_abbrev
struct abbrev_table
struct attribute
struct die_info
struct dwarf_block
struct field_info
struct field_info::nextfield
struct field_info::nextfnfield
struct field_info::fnfieldlist
struct field_info::typedef_field_list
struct dwarf2_queue_item
struct quick_file_names
struct dwarf2_per_cu_quick_data
struct dw2_symtab_iterator
struct tu_abbrev_offset
struct process_psymtab_comp_unit_data
struct create_dwo_cu_data
struct dwarf2_read_addr_index_data
struct dwarf2_per_cu_offset_and_type
struct strtab_entry
struct symtab_index_entry
struct mapped_symtab
struct psymtab_cu_index_map
struct addrmap_index_data
struct signatured_type_index_data
Defines
#define DW2_GDB_INDEX_SYMBOL_STATIC_SET_VALUE(cu_index, value)
#define DW2_GDB_INDEX_SYMBOL_KIND_SET_VALUE(cu_index, value)
#define DW2_GDB_INDEX_CU_SET_VALUE(cu_index, value)
#define IS_TYPE_UNIT_GROUP(per_cu) ((per_cu)->section == NULL)
#define MAX_NR_V2_DWO_SECTIONS
#define ABBREV_HASH_SIZE 121
#define DW_STRING(attr) ((attr)->u.str)
#define DW_STRING_IS_CANONICAL(attr) ((attr)->string_is_canonical)
#define DW_UNSND(attr) ((attr)->u.unsnd)
#define DW_BLOCK(attr) ((attr)->u.blk)
#define DW_SND(attr) ((attr)->u.snd)
#define DW_ADDR(attr) ((attr)->u.addr)
#define DW_SIGNATURE(attr) ((attr)->u.signature)
#define ATTR_ALLOC_CHUNK 4
#define DW_FIELD_ALLOC_CHUNK 4
#define MAYBE_SWAP(V) (V)
#define INDEX_SUFFIX ".gdb-index"
#define NO_STMT_LIST_TYPE_UNIT_PSYMTAB (1 << 31)
#define NO_STMT_LIST_TYPE_UNIT_PSYMTAB_SIZE 10
#define MAX_NR_V1_DWO_SECTIONS
#define MAX_SEP_LEN 7 /* strlen ("__") + strlen ("_MOD_") */
Typedefs
typedef struct symbol * symbolp
typedef struct dwarf2_section_info dwarf2_section_info_def
typedef uint32_t offset_type
typedef struct dwarf2_per_cu_data * dwarf2_per_cu_ptr
typedef struct delayed_method_info delayed_method_info
typedef struct signatured_type * sig_type_ptr
typedef void(die_reader_func_ftype)(const struct die_reader_specs *reader, const gdb_byte *info_ptr, struct die_info *comp_unit_die, int has_children, void *data)
Enumerations
enum dwp_v2_section_ids { DW_SECT_MIN = 1 }
Functions
DEF_VEC_P (symbolp)
DEF_VEC_O (dwarf2_section_info_def)
DEF_VEC_I (offset_type)
DEF_VEC_P (dwarf2_per_cu_ptr)
DEF_VEC_O (delayed_method_info)
DEF_VEC_P (sig_type_ptr)
static void show_dwarf2_max_cache_age (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static const char * get_section_name (const struct dwarf2_section_info *)
static const char * get_section_file_name (const struct dwarf2_section_info *)
static void dwarf2_locate_sections (bfd *, asection *, void *)
static void dwarf2_find_base_address (struct die_info *die, struct dwarf2_cu *cu)
static struct partial_symtab * create_partial_symtab (struct dwarf2_per_cu_data *per_cu, const char *name)
static void dwarf2_build_psymtabs_hard (struct objfile *)
static void scan_partial_symbols (struct partial_die_info *, CORE_ADDR *, CORE_ADDR *, int, struct dwarf2_cu *)
static void add_partial_symbol (struct partial_die_info *, struct dwarf2_cu *)
static void add_partial_namespace (struct partial_die_info *pdi, CORE_ADDR *lowpc, CORE_ADDR *highpc, int need_pc, struct dwarf2_cu *cu)
static void add_partial_module (struct partial_die_info *pdi, CORE_ADDR *lowpc, CORE_ADDR *highpc, int need_pc, struct dwarf2_cu *cu)
static void add_partial_enumeration (struct partial_die_info *enum_pdi, struct dwarf2_cu *cu)
static void add_partial_subprogram (struct partial_die_info *pdi, CORE_ADDR *lowpc, CORE_ADDR *highpc, int need_pc, struct dwarf2_cu *cu)
static void dwarf2_read_symtab (struct partial_symtab *, struct objfile *)
static void psymtab_to_symtab_1 (struct partial_symtab *)
static struct abbrev_info * abbrev_table_lookup_abbrev (const struct abbrev_table *, unsigned int)
static struct abbrev_table * abbrev_table_read_table (struct dwarf2_section_info *, sect_offset)
static void abbrev_table_free (struct abbrev_table *)
static void abbrev_table_free_cleanup (void *)
static void dwarf2_read_abbrevs (struct dwarf2_cu *, struct dwarf2_section_info *)
static void dwarf2_free_abbrev_table (void *)
static unsigned int peek_abbrev_code (bfd *, const gdb_byte *)
static struct partial_die_info * load_partial_dies (const struct die_reader_specs *, const gdb_byte *, int)
static const gdb_byte * read_partial_die (const struct die_reader_specs *, struct partial_die_info *, struct abbrev_info *, unsigned int, const gdb_byte *)
static struct partial_die_info * find_partial_die (sect_offset, int, struct dwarf2_cu *)
static void fixup_partial_die (struct partial_die_info *, struct dwarf2_cu *)
static const gdb_byte * read_attribute (const struct die_reader_specs *, struct attribute *, struct attr_abbrev *, const gdb_byte *)
static unsigned int read_1_byte (bfd *, const gdb_byte *)
static int read_1_signed_byte (bfd *, const gdb_byte *)
static unsigned int read_2_bytes (bfd *, const gdb_byte *)
static unsigned int read_4_bytes (bfd *, const gdb_byte *)
static ULONGEST read_8_bytes (bfd *, const gdb_byte *)
static CORE_ADDR read_address (bfd *, const gdb_byte *ptr, struct dwarf2_cu *, unsigned int *)
static LONGEST read_initial_length (bfd *, const gdb_byte *, unsigned int *)
static LONGEST read_checked_initial_length_and_offset (bfd *, const gdb_byte *, const struct comp_unit_head *, unsigned int *, unsigned int *)
static LONGEST read_offset (bfd *, const gdb_byte *, const struct comp_unit_head *, unsigned int *)
static LONGEST read_offset_1 (bfd *, const gdb_byte *, unsigned int)
static sect_offset read_abbrev_offset (struct dwarf2_section_info *, sect_offset)
static const gdb_byte * read_n_bytes (bfd *, const gdb_byte *, unsigned int)
static const char * read_direct_string (bfd *, const gdb_byte *, unsigned int *)
static const char * read_indirect_string (bfd *, const gdb_byte *, const struct comp_unit_head *, unsigned int *)
static const char * read_indirect_string_from_dwz (struct dwz_file *, LONGEST)
static ULONGEST read_unsigned_leb128 (bfd *, const gdb_byte *, unsigned int *)
static LONGEST read_signed_leb128 (bfd *, const gdb_byte *, unsigned int *)
static CORE_ADDR read_addr_index_from_leb128 (struct dwarf2_cu *, const gdb_byte *, unsigned int *)
static const char * read_str_index (const struct die_reader_specs *reader, struct dwarf2_cu *cu, ULONGEST str_index)
static void set_cu_language (unsigned int, struct dwarf2_cu *)
static struct attribute * dwarf2_attr (struct die_info *, unsigned int, struct dwarf2_cu *)
static struct attribute * dwarf2_attr_no_follow (struct die_info *, unsigned int)
static int dwarf2_flag_true_p (struct die_info *die, unsigned name, struct dwarf2_cu *cu)
static int die_is_declaration (struct die_info *, struct dwarf2_cu *cu)
static struct die_info * die_specification (struct die_info *die, struct dwarf2_cu **)
static void free_line_header (struct line_header *lh)
static struct line_header * dwarf_decode_line_header (unsigned int offset, struct dwarf2_cu *cu)
static void dwarf_decode_lines (struct line_header *, const char *, struct dwarf2_cu *, struct partial_symtab *, int)
static void dwarf2_start_subfile (const char *, const char *, const char *)
static void dwarf2_start_symtab (struct dwarf2_cu *, const char *, const char *, CORE_ADDR)
static struct symbol * new_symbol (struct die_info *, struct type *, struct dwarf2_cu *)
static struct symbol * new_symbol_full (struct die_info *, struct type *, struct dwarf2_cu *, struct symbol *)
static void dwarf2_const_value (const struct attribute *, struct symbol *, struct dwarf2_cu *)
static void dwarf2_const_value_attr (const struct attribute *attr, struct type *type, const char *name, struct obstack *obstack, struct dwarf2_cu *cu, LONGEST *value, const gdb_byte **bytes, struct dwarf2_locexpr_baton **baton)
static struct type * die_type (struct die_info *, struct dwarf2_cu *)
static int need_gnat_info (struct dwarf2_cu *)
static struct type * die_descriptive_type (struct die_info *, struct dwarf2_cu *)
static void set_descriptive_type (struct type *, struct die_info *, struct dwarf2_cu *)
static struct type * die_containing_type (struct die_info *, struct dwarf2_cu *)
static struct type * lookup_die_type (struct die_info *, const struct attribute *, struct dwarf2_cu *)
static struct type * read_type_die (struct die_info *, struct dwarf2_cu *)
static struct type * read_type_die_1 (struct die_info *, struct dwarf2_cu *)
static const char * determine_prefix (struct die_info *die, struct dwarf2_cu *)
static char * typename_concat (struct obstack *obs, const char *prefix, const char *suffix, int physname, struct dwarf2_cu *cu)
static void read_file_scope (struct die_info *, struct dwarf2_cu *)
static void read_type_unit_scope (struct die_info *, struct dwarf2_cu *)
static void read_func_scope (struct die_info *, struct dwarf2_cu *)
static void read_lexical_block_scope (struct die_info *, struct dwarf2_cu *)
static void read_call_site_scope (struct die_info *die, struct dwarf2_cu *cu)
static int dwarf2_ranges_read (unsigned, CORE_ADDR *, CORE_ADDR *, struct dwarf2_cu *, struct partial_symtab *)
static int dwarf2_get_pc_bounds (struct die_info *, CORE_ADDR *, CORE_ADDR *, struct dwarf2_cu *, struct partial_symtab *)
static void get_scope_pc_bounds (struct die_info *, CORE_ADDR *, CORE_ADDR *, struct dwarf2_cu *)
static void dwarf2_record_block_ranges (struct die_info *, struct block *, CORE_ADDR, struct dwarf2_cu *)
static void dwarf2_add_field (struct field_info *, struct die_info *, struct dwarf2_cu *)
static void dwarf2_attach_fields_to_type (struct field_info *, struct type *, struct dwarf2_cu *)
static void dwarf2_add_member_fn (struct field_info *, struct die_info *, struct type *, struct dwarf2_cu *)
static void dwarf2_attach_fn_fields_to_type (struct field_info *, struct type *, struct dwarf2_cu *)
static void process_structure_scope (struct die_info *, struct dwarf2_cu *)
static void read_common_block (struct die_info *, struct dwarf2_cu *)
static void read_namespace (struct die_info *die, struct dwarf2_cu *)
static void read_module (struct die_info *die, struct dwarf2_cu *cu)
static void read_import_statement (struct die_info *die, struct dwarf2_cu *)
static struct type * read_module_type (struct die_info *die, struct dwarf2_cu *cu)
static const char * namespace_name (struct die_info *die, int *is_anonymous, struct dwarf2_cu *)
static void process_enumeration_scope (struct die_info *, struct dwarf2_cu *)
static CORE_ADDR decode_locdesc (struct dwarf_block *, struct dwarf2_cu *)
static enum
dwarf_array_dim_ordering read_array_order (struct die_info *, struct dwarf2_cu *)
static struct die_info * read_die_and_siblings_1 (const struct die_reader_specs *, const gdb_byte *, const gdb_byte **, struct die_info *)
static struct die_info * read_die_and_siblings (const struct die_reader_specs *, const gdb_byte *info_ptr, const gdb_byte **new_info_ptr, struct die_info *parent)
static const gdb_byte * read_full_die_1 (const struct die_reader_specs *, struct die_info **, const gdb_byte *, int *, int)
static const gdb_byte * read_full_die (const struct die_reader_specs *, struct die_info **, const gdb_byte *, int *)
static void process_die (struct die_info *, struct dwarf2_cu *)
static const char * dwarf2_canonicalize_name (const char *, struct dwarf2_cu *, struct obstack *)
static const char * dwarf2_name (struct die_info *die, struct dwarf2_cu *)
static const char * dwarf2_full_name (const char *name, struct die_info *die, struct dwarf2_cu *cu)
static const char * dwarf2_physname (const char *name, struct die_info *die, struct dwarf2_cu *cu)
static struct die_info * dwarf2_extension (struct die_info *die, struct dwarf2_cu **)
static const char * dwarf_tag_name (unsigned int)
static const char * dwarf_attr_name (unsigned int)
static const char * dwarf_form_name (unsigned int)
static char * dwarf_bool_name (unsigned int)
static const char * dwarf_type_encoding_name (unsigned int)
static struct die_info * sibling_die (struct die_info *)
static void dump_die_shallow (struct ui_file *, int indent, struct die_info *)
static void dump_die_for_error (struct die_info *)
static void dump_die_1 (struct ui_file *, int level, int max_level, struct die_info *)
void dump_die (struct die_info *, int max_level)
static void store_in_ref_table (struct die_info *, struct dwarf2_cu *)
static sect_offset dwarf2_get_ref_die_offset (const struct attribute *)
static LONGEST dwarf2_get_attr_constant_value (const struct attribute *, int)
static struct die_info * follow_die_ref_or_sig (struct die_info *, const struct attribute *, struct dwarf2_cu **)
static struct die_info * follow_die_ref (struct die_info *, const struct attribute *, struct dwarf2_cu **)
static struct die_info * follow_die_sig (struct die_info *, const struct attribute *, struct dwarf2_cu **)
static struct type * get_signatured_type (struct die_info *, ULONGEST, struct dwarf2_cu *)
static struct type * get_DW_AT_signature_type (struct die_info *, const struct attribute *, struct dwarf2_cu *)
static void load_full_type_unit (struct dwarf2_per_cu_data *per_cu)
static void read_signatured_type (struct signatured_type *)
static struct type_unit_group * get_type_unit_group (struct dwarf2_cu *, const struct attribute *)
static void build_type_unit_groups (die_reader_func_ftype *, void *)
static struct dwarf_block * dwarf_alloc_block (struct dwarf2_cu *)
static struct die_info * dwarf_alloc_die (struct dwarf2_cu *, int)
static void dwarf_decode_macros (struct dwarf2_cu *, unsigned int, const char *, int)
static int attr_form_is_block (const struct attribute *)
static int attr_form_is_section_offset (const struct attribute *)
static int attr_form_is_constant (const struct attribute *)
static int attr_form_is_ref (const struct attribute *)
static void fill_in_loclist_baton (struct dwarf2_cu *cu, struct dwarf2_loclist_baton *baton, const struct attribute *attr)
static void dwarf2_symbol_mark_computed (const struct attribute *attr, struct symbol *sym, struct dwarf2_cu *cu, int is_block)
static const gdb_byte * skip_one_die (const struct die_reader_specs *reader, const gdb_byte *info_ptr, struct abbrev_info *abbrev)
static void free_stack_comp_unit (void *)
static hashval_t partial_die_hash (const void *item)
static int partial_die_eq (const void *item_lhs, const void *item_rhs)
static struct dwarf2_per_cu_data * dwarf2_find_containing_comp_unit (sect_offset offset, unsigned int offset_in_dwz, struct objfile *objfile)
static void init_one_comp_unit (struct dwarf2_cu *cu, struct dwarf2_per_cu_data *per_cu)
static void prepare_one_comp_unit (struct dwarf2_cu *cu, struct die_info *comp_unit_die, enum language pretend_language)
static void free_heap_comp_unit (void *)
static void free_cached_comp_units (void *)
static void age_cached_comp_units (void)
static void free_one_cached_comp_unit (struct dwarf2_per_cu_data *)
static struct type * set_die_type (struct die_info *, struct type *, struct dwarf2_cu *)
static void create_all_comp_units (struct objfile *)
static int create_all_type_units (struct objfile *)
static void load_full_comp_unit (struct dwarf2_per_cu_data *, enum language)
static void process_full_comp_unit (struct dwarf2_per_cu_data *, enum language)
static void process_full_type_unit (struct dwarf2_per_cu_data *, enum language)
static void dwarf2_add_dependence (struct dwarf2_cu *, struct dwarf2_per_cu_data *)
static void dwarf2_mark (struct dwarf2_cu *)
static void dwarf2_clear_marks (struct dwarf2_per_cu_data *)
static struct type * get_die_type_at_offset (sect_offset, struct dwarf2_per_cu_data *)
static struct type * get_die_type (struct die_info *die, struct dwarf2_cu *cu)
static void dwarf2_release_queue (void *dummy)
static void queue_comp_unit (struct dwarf2_per_cu_data *per_cu, enum language pretend_language)
static void process_queue (void)
static void find_file_and_directory (struct die_info *die, struct dwarf2_cu *cu, const char **name, const char **comp_dir)
static char * file_full_name (int file, struct line_header *lh, const char *comp_dir)
static const gdb_byte * read_and_check_comp_unit_head (struct comp_unit_head *header, struct dwarf2_section_info *section, struct dwarf2_section_info *abbrev_section, const gdb_byte *info_ptr, int is_debug_types_section)
static void init_cutu_and_read_dies (struct dwarf2_per_cu_data *this_cu, struct abbrev_table *abbrev_table, int use_existing_cu, int keep, die_reader_func_ftype *die_reader_func, void *data)
static void init_cutu_and_read_dies_simple (struct dwarf2_per_cu_data *this_cu, die_reader_func_ftype *die_reader_func, void *data)
static htab_t allocate_signatured_type_table (struct objfile *objfile)
static htab_t allocate_dwo_unit_table (struct objfile *objfile)
static struct dwo_unit * lookup_dwo_unit_in_dwp (struct dwp_file *dwp_file, const char *comp_dir, ULONGEST signature, int is_debug_types)
static struct dwp_file * get_dwp_file (void)
static struct dwo_unit * lookup_dwo_comp_unit (struct dwarf2_per_cu_data *, const char *, const char *, ULONGEST)
static struct dwo_unit * lookup_dwo_type_unit (struct signatured_type *, const char *, const char *)
static void queue_and_load_all_dwo_tus (struct dwarf2_per_cu_data *)
static void free_dwo_file_cleanup (void *)
static void process_cu_includes (void)
static void check_producer (struct dwarf2_cu *cu)
static void dwarf2_statement_list_fits_in_line_number_section_complaint (void)
static void dwarf2_debug_line_missing_file_complaint (void)
static void dwarf2_debug_line_missing_end_sequence_complaint (void)
static void dwarf2_complex_location_expr_complaint (void)
static void dwarf2_const_value_length_mismatch_complaint (const char *arg1, int arg2, int arg3)
static void dwarf2_section_buffer_overflow_complaint (struct dwarf2_section_info *section)
static void dwarf2_macro_malformed_definition_complaint (const char *arg1)
static void dwarf2_invalid_attrib_class_complaint (const char *arg1, const char *arg2)
int dwarf2_has_info (struct objfile *objfile, const struct dwarf2_debug_sections *names)
static struct dwarf2_section_info * get_containing_section (const struct dwarf2_section_info *section)
static struct bfd * get_section_bfd_owner (const struct dwarf2_section_info *section)
static asection * get_section_bfd_section (const struct dwarf2_section_info *section)
static int get_section_id (const struct dwarf2_section_info *section)
static int get_section_flags (const struct dwarf2_section_info *section)
static int section_is_p (const char *section_name, const struct dwarf2_section_names *names)
static int dwarf2_section_empty_p (const struct dwarf2_section_info *section)
static void dwarf2_read_section (struct objfile *objfile, struct dwarf2_section_info *info)
static bfd_size_type dwarf2_section_size (struct objfile *objfile, struct dwarf2_section_info *info)
void dwarf2_get_section_info (struct objfile *objfile, enum dwarf2_section_enum sect, asection **sectp, const gdb_byte **bufp, bfd_size_type *sizep)
static void locate_dwz_sections (bfd *abfd, asection *sectp, void *arg)
static struct dwz_file * dwarf2_get_dwz_file (void)
static hashval_t hash_stmt_list_entry (const struct stmt_list_hash *stmt_list_hash)
static int eq_stmt_list_entry (const struct stmt_list_hash *lhs, const struct stmt_list_hash *rhs)
static hashval_t hash_file_name_entry (const void *e)
static int eq_file_name_entry (const void *a, const void *b)
static void delete_file_name_entry (void *e)
static htab_t create_quick_file_names_table (unsigned int nr_initial_entries)
static void load_cu (struct dwarf2_per_cu_data *per_cu)
static void dw2_do_instantiate_symtab (struct dwarf2_per_cu_data *per_cu)
static struct symtab * dw2_instantiate_symtab (struct dwarf2_per_cu_data *per_cu)
static struct dwarf2_per_cu_data * dw2_get_cu (int index)
static struct dwarf2_per_cu_data * dw2_get_primary_cu (int index)
static void create_cus_from_index_list (struct objfile *objfile, const gdb_byte *cu_list, offset_type n_elements, struct dwarf2_section_info *section, int is_dwz, int base_offset)
static void create_cus_from_index (struct objfile *objfile, const gdb_byte *cu_list, offset_type cu_list_elements, const gdb_byte *dwz_list, offset_type dwz_elements)
static void create_signatured_type_table_from_index (struct objfile *objfile, struct dwarf2_section_info *section, const gdb_byte *bytes, offset_type elements)
static void create_addrmap_from_index (struct objfile *objfile, struct mapped_index *index)
static hashval_t mapped_index_string_hash (int index_version, const void *p)
static int find_slot_in_mapped_hash (struct mapped_index *index, const char *name, offset_type **vec_out)
static int read_index_from_section (struct objfile *objfile, const char *filename, int deprecated_ok, struct dwarf2_section_info *section, struct mapped_index *map, const gdb_byte **cu_list, offset_type *cu_list_elements, const gdb_byte **types_list, offset_type *types_list_elements)
static int dwarf2_read_index (struct objfile *objfile)
static void dw2_setup (struct objfile *objfile)
static void dw2_get_file_names_reader (const struct die_reader_specs *reader, const gdb_byte *info_ptr, struct die_info *comp_unit_die, int has_children, void *data)
static struct quick_file_names * dw2_get_file_names (struct dwarf2_per_cu_data *this_cu)
static const char * dw2_get_real_path (struct objfile *objfile, struct quick_file_names *qfn, int index)
static struct symtab * dw2_find_last_source_symtab (struct objfile *objfile)
static int dw2_free_cached_file_names (void **slot, void *info)
static void dw2_forget_cached_source_info (struct objfile *objfile)
static int dw2_map_expand_apply (struct objfile *objfile, struct dwarf2_per_cu_data *per_cu, const char *name, const char *real_path, int(*callback)(struct symtab *, void *), void *data)
static int dw2_map_symtabs_matching_filename (struct objfile *objfile, const char *name, const char *real_path, int(*callback)(struct symtab *, void *), void *data)
static void dw2_symtab_iter_init (struct dw2_symtab_iterator *iter, struct mapped_index *index, int want_specific_block, int block_index, domain_enum domain, const char *name)
static struct dwarf2_per_cu_data * dw2_symtab_iter_next (struct dw2_symtab_iterator *iter)
static struct symtab * dw2_lookup_symbol (struct objfile *objfile, int block_index, const char *name, domain_enum domain)
static void dw2_print_stats (struct objfile *objfile)
static void dw2_dump (struct objfile *objfile)
static void dw2_relocate (struct objfile *objfile, const struct section_offsets *new_offsets, const struct section_offsets *delta)
static void dw2_expand_symtabs_for_function (struct objfile *objfile, const char *func_name)
static void dw2_expand_all_symtabs (struct objfile *objfile)
static void dw2_expand_symtabs_with_fullname (struct objfile *objfile, const char *fullname)
static void dw2_map_matching_symbols (struct objfile *objfile, const char *name, domain_enum namespace, int global, int(*callback)(struct block *, struct symbol *, void *), void *data, symbol_compare_ftype *match, symbol_compare_ftype *ordered_compare)
static void dw2_expand_symtabs_matching (struct objfile *objfile, int(*file_matcher)(const char *, void *, int basenames), int(*name_matcher)(const char *, void *), enum search_domain kind, void *data)
static struct symtab * recursively_find_pc_sect_symtab (struct symtab *symtab, CORE_ADDR pc)
static struct symtab * dw2_find_pc_sect_symtab (struct objfile *objfile, struct minimal_symbol *msymbol, CORE_ADDR pc, struct obj_section *section, int warn_if_readin)
static void dw2_map_symbol_filenames (struct objfile *objfile, symbol_filename_ftype *fun, void *data, int need_fullname)
static int dw2_has_symbols (struct objfile *objfile)
int dwarf2_initialize_objfile (struct objfile *objfile)
void dwarf2_build_psymtabs (struct objfile *objfile)
static unsigned int get_cu_length (const struct comp_unit_head *header)
static int offset_in_cu_p (const struct comp_unit_head *cu_header, sect_offset offset)
static const gdb_byte * read_comp_unit_head (struct comp_unit_head *cu_header, const gdb_byte *info_ptr, bfd *abfd)
static struct dwarf2_section_info * get_abbrev_section_for_cu (struct dwarf2_per_cu_data *this_cu)
static void error_check_comp_unit_head (struct comp_unit_head *header, struct dwarf2_section_info *section, struct dwarf2_section_info *abbrev_section)
static const gdb_byte * read_and_check_type_unit_head (struct comp_unit_head *header, struct dwarf2_section_info *section, struct dwarf2_section_info *abbrev_section, const gdb_byte *info_ptr, ULONGEST *signature, cu_offset *type_offset_in_tu)
static void dwarf2_create_include_psymtab (const char *name, struct partial_symtab *pst, struct objfile *objfile)
static void dwarf2_build_include_psymtabs (struct dwarf2_cu *cu, struct die_info *die, struct partial_symtab *pst)
static hashval_t hash_signatured_type (const void *item)
static int eq_signatured_type (const void *item_lhs, const void *item_rhs)
static int add_signatured_type_cu_to_table (void **slot, void *datum)
static htab_t create_debug_types_hash_table (struct dwo_file *dwo_file, VEC(dwarf2_section_info_def)*types)
static void fill_in_sig_entry_from_dwo_entry (struct objfile *objfile, struct signatured_type *sig_entry, struct dwo_unit *dwo_entry)
static struct signatured_type * lookup_dwo_signatured_type (struct dwarf2_cu *cu, ULONGEST sig)
static struct signatured_type * add_type_unit (ULONGEST sig)
static struct signatured_type * lookup_dwp_signatured_type (struct dwarf2_cu *cu, ULONGEST sig)
static struct signatured_type * lookup_signatured_type (struct dwarf2_cu *cu, ULONGEST sig)
static void init_cu_die_reader (struct die_reader_specs *reader, struct dwarf2_cu *cu, struct dwarf2_section_info *section, struct dwo_file *dwo_file)
static int read_cutu_die_from_dwo (struct dwarf2_per_cu_data *this_cu, struct dwo_unit *dwo_unit, int abbrev_table_provided, struct die_info *stub_comp_unit_die, const char *stub_comp_dir, struct die_reader_specs *result_reader, const gdb_byte **result_info_ptr, struct die_info **result_comp_unit_die, int *result_has_children)
static struct dwo_unit * lookup_dwo_unit (struct dwarf2_per_cu_data *this_cu, struct die_info *comp_unit_die)
static void init_tu_and_read_dwo_dies (struct dwarf2_per_cu_data *this_cu, int keep, die_reader_func_ftype *die_reader_func, void *data)
static void init_cutu_and_read_dies_no_follow (struct dwarf2_per_cu_data *this_cu, struct dwarf2_section_info *abbrev_section, struct dwo_file *dwo_file, die_reader_func_ftype *die_reader_func, void *data)
static hashval_t hash_type_unit_group (const void *item)
static int eq_type_unit_group (const void *item_lhs, const void *item_rhs)
static htab_t allocate_type_unit_groups_table (void)
static struct type_unit_group * create_type_unit_group (struct dwarf2_cu *cu, sect_offset line_offset_struct)
static int sort_tu_by_abbrev_offset (const void *ap, const void *bp)
static int add_type_unit_group_to_table (void **slot, void *datum)
static void process_psymtab_comp_unit_reader (const struct die_reader_specs *reader, const gdb_byte *info_ptr, struct die_info *comp_unit_die, int has_children, void *data)
static void process_psymtab_comp_unit (struct dwarf2_per_cu_data *this_cu, int want_partial_unit, enum language pretend_language)
static void build_type_psymtabs_reader (const struct die_reader_specs *reader, const gdb_byte *info_ptr, struct die_info *type_unit_die, int has_children, void *data)
static int build_type_psymtab_dependencies (void **slot, void *info)
static void build_type_psymtabs (struct objfile *objfile)
static void psymtabs_addrmap_cleanup (void *o)
static void set_partial_user (struct objfile *objfile)
static void load_partial_comp_unit_reader (const struct die_reader_specs *reader, const gdb_byte *info_ptr, struct die_info *comp_unit_die, int has_children, void *data)
static void load_partial_comp_unit (struct dwarf2_per_cu_data *this_cu)
static void read_comp_units_from_section (struct objfile *objfile, struct dwarf2_section_info *section, unsigned int is_dwz, int *n_allocated, int *n_comp_units, struct dwarf2_per_cu_data ***all_comp_units)
static const char * partial_die_parent_scope (struct partial_die_info *pdi, struct dwarf2_cu *cu)
static char * partial_die_full_name (struct partial_die_info *pdi, struct dwarf2_cu *cu)
static struct abbrev_info * peek_die_abbrev (const gdb_byte *info_ptr, unsigned int *bytes_read, struct dwarf2_cu *cu)
static const gdb_byte * skip_children (const struct die_reader_specs *reader, const gdb_byte *info_ptr)
static const gdb_byte * locate_pdi_sibling (const struct die_reader_specs *reader, struct partial_die_info *orig_pdi, const gdb_byte *info_ptr)
static int maybe_queue_comp_unit (struct dwarf2_cu *dependent_cu, struct dwarf2_per_cu_data *per_cu, enum language pretend_language)
static hashval_t die_hash (const void *item)
static int die_eq (const void *item_lhs, const void *item_rhs)
static void load_full_comp_unit_reader (const struct die_reader_specs *reader, const gdb_byte *info_ptr, struct die_info *comp_unit_die, int has_children, void *data)
static void add_to_method_list (struct type *type, int fnfield_index, int index, const char *name, struct die_info *die, struct dwarf2_cu *cu)
static void free_delayed_list (void *ptr)
static void compute_delayed_physnames (struct dwarf2_cu *cu)
static void fixup_go_packaging (struct dwarf2_cu *cu)
static struct symtab * get_symtab (struct dwarf2_per_cu_data *per_cu)
static void recursively_compute_inclusions (VEC(symtab_ptr)**result, htab_t all_children, htab_t all_type_symtabs, struct dwarf2_per_cu_data *per_cu, struct symtab *immediate_parent)
static void compute_symtab_includes (struct dwarf2_per_cu_data *per_cu)
static void process_imported_unit_die (struct die_info *die, struct dwarf2_cu *cu)
static int die_needs_namespace (struct die_info *die, struct dwarf2_cu *cu)
static void do_ui_file_peek_last (void *object, const char *buffer, long length)
static const char * dwarf2_compute_name (const char *name, struct die_info *die, struct dwarf2_cu *cu, int physname)
static void free_cu_line_header (void *arg)
static int producer_is_gcc_lt_4_3 (struct dwarf2_cu *cu)
static void handle_DW_AT_stmt_list (struct die_info *die, struct dwarf2_cu *cu, const char *comp_dir)
static void setup_type_unit_groups (struct die_info *die, struct dwarf2_cu *cu)
static hashval_t hash_dwo_file (const void *item)
static int eq_dwo_file (const void *item_lhs, const void *item_rhs)
static htab_t allocate_dwo_file_hash_table (void)
static void ** lookup_dwo_file_slot (const char *dwo_name, const char *comp_dir)
static hashval_t hash_dwo_unit (const void *item)
static int eq_dwo_unit (const void *item_lhs, const void *item_rhs)
static void create_dwo_cu_reader (const struct die_reader_specs *reader, const gdb_byte *info_ptr, struct die_info *comp_unit_die, int has_children, void *datap)
static struct dwo_unit * create_dwo_cu (struct dwo_file *dwo_file)
static struct dwp_hash_table * create_dwp_hash_table (struct dwp_file *dwp_file, int is_debug_types)
static int locate_v1_virtual_dwo_sections (asection *sectp, struct virtual_v1_dwo_sections *sections)
static struct dwo_unit * create_dwo_unit_in_dwp_v1 (struct dwp_file *dwp_file, uint32_t unit_index, const char *comp_dir, ULONGEST signature, int is_debug_types)
static struct dwarf2_section_info create_dwp_v2_section (struct dwarf2_section_info *section, bfd_size_type offset, bfd_size_type size)
static struct dwo_unit * create_dwo_unit_in_dwp_v2 (struct dwp_file *dwp_file, uint32_t unit_index, const char *comp_dir, ULONGEST signature, int is_debug_types)
static bfd * try_open_dwop_file (const char *file_name, int is_dwp, int search_cwd)
static bfd * open_dwo_file (const char *file_name, const char *comp_dir)
static void dwarf2_locate_dwo_sections (bfd *abfd, asection *sectp, void *dwo_sections_ptr)
static struct dwo_file * open_and_init_dwo_file (struct dwarf2_per_cu_data *per_cu, const char *dwo_name, const char *comp_dir)
static void dwarf2_locate_common_dwp_sections (bfd *abfd, asection *sectp, void *dwp_file_ptr)
static void dwarf2_locate_v2_dwp_sections (bfd *abfd, asection *sectp, void *dwp_file_ptr)
static hashval_t hash_dwp_loaded_cutus (const void *item)
static int eq_dwp_loaded_cutus (const void *a, const void *b)
static htab_t allocate_dwp_loaded_cutus_table (struct objfile *objfile)
static bfd * open_dwp_file (const char *file_name)
static struct dwp_file * open_and_init_dwp_file (void)
static struct dwo_unit * lookup_dwo_cutu (struct dwarf2_per_cu_data *this_unit, const char *dwo_name, const char *comp_dir, ULONGEST signature, int is_debug_types)
static int queue_and_load_dwo_tu (void **slot, void *info)
static void free_dwo_file (struct dwo_file *dwo_file, struct objfile *objfile)
static int free_dwo_file_from_slot (void **slot, void *info)
static void free_dwo_files (htab_t dwo_files, struct objfile *objfile)
static int unsigned_int_compar (const void *ap, const void *bp)
static void inherit_abstract_dies (struct die_info *die, struct dwarf2_cu *cu)
static void dwarf2_get_subprogram_pc_bounds (struct die_info *die, CORE_ADDR *lowpc, CORE_ADDR *highpc, struct dwarf2_cu *cu)
static int producer_is_gxx_lt_4_6 (struct dwarf2_cu *cu)
static enum dwarf_access_attribute dwarf2_default_access_attribute (struct die_info *die, struct dwarf2_cu *cu)
static int handle_data_member_location (struct die_info *die, struct dwarf2_cu *cu, LONGEST *offset)
static void dwarf2_add_typedef (struct field_info *fip, struct die_info *die, struct dwarf2_cu *cu)
static int dwarf2_is_constructor (struct die_info *die, struct dwarf2_cu *cu)
static int is_vtable_name (const char *name, struct dwarf2_cu *cu)
static void quirk_gcc_member_function_pointer (struct type *type, struct objfile *objfile)
static int producer_is_icc (struct dwarf2_cu *cu)
static struct type * read_structure_type (struct die_info *die, struct dwarf2_cu *cu)
static struct type * read_enumeration_type (struct die_info *die, struct dwarf2_cu *cu)
static struct type * read_array_type (struct die_info *die, struct dwarf2_cu *cu)
static struct type * read_set_type (struct die_info *die, struct dwarf2_cu *cu)
static void mark_common_block_symbol_computed (struct symbol *sym, struct die_info *common_die, struct attribute *common_loc, struct attribute *member_loc, struct dwarf2_cu *cu)
static struct type * read_namespace_type (struct die_info *die, struct dwarf2_cu *cu)
static struct type * read_tag_pointer_type (struct die_info *die, struct dwarf2_cu *cu)
static struct type * read_tag_ptr_to_member_type (struct die_info *die, struct dwarf2_cu *cu)
static struct type * read_tag_reference_type (struct die_info *die, struct dwarf2_cu *cu)
static struct type * read_tag_const_type (struct die_info *die, struct dwarf2_cu *cu)
static struct type * read_tag_volatile_type (struct die_info *die, struct dwarf2_cu *cu)
static struct type * read_tag_restrict_type (struct die_info *die, struct dwarf2_cu *cu)
static struct type * read_tag_string_type (struct die_info *die, struct dwarf2_cu *cu)
static int prototyped_function_p (struct die_info *die, struct dwarf2_cu *cu)
static struct type * read_subroutine_type (struct die_info *die, struct dwarf2_cu *cu)
static struct type * read_typedef (struct die_info *die, struct dwarf2_cu *cu)
static struct type * read_base_type (struct die_info *die, struct dwarf2_cu *cu)
static struct type * read_subrange_type (struct die_info *die, struct dwarf2_cu *cu)
static struct type * read_unspecified_type (struct die_info *die, struct dwarf2_cu *cu)
static struct die_info * read_die_and_children (const struct die_reader_specs *reader, const gdb_byte *info_ptr, const gdb_byte **new_info_ptr, struct die_info *parent)
static struct abbrev_info * abbrev_table_alloc_abbrev (struct abbrev_table *abbrev_table)
static void abbrev_table_add_abbrev (struct abbrev_table *abbrev_table, unsigned int abbrev_number, struct abbrev_info *abbrev)
static int is_type_tag_for_partial (int tag)
static struct partial_die_info * find_partial_die_in_comp_unit (sect_offset offset, struct dwarf2_cu *cu)
static void guess_partial_die_structure_name (struct partial_die_info *struct_pdi, struct dwarf2_cu *cu)
static const gdb_byte * read_attribute_value (const struct die_reader_specs *reader, struct attribute *attr, unsigned form, const gdb_byte *info_ptr)
static int read_2_signed_bytes (bfd *abfd, const gdb_byte *buf)
static int read_4_signed_bytes (bfd *abfd, const gdb_byte *buf)
static const char * read_indirect_string_at_offset (bfd *abfd, LONGEST str_offset)
static CORE_ADDR read_addr_index_1 (unsigned int addr_index, ULONGEST addr_base, int addr_size)
static CORE_ADDR read_addr_index (struct dwarf2_cu *cu, unsigned int addr_index)
static void dwarf2_read_addr_index_reader (const struct die_reader_specs *reader, const gdb_byte *info_ptr, struct die_info *comp_unit_die, int has_children, void *data)
CORE_ADDR dwarf2_read_addr_index (struct dwarf2_per_cu_data *per_cu, unsigned int addr_index)
static int leb128_size (const gdb_byte *buf)
static void add_include_dir (struct line_header *lh, const char *include_dir)
static void add_file_name (struct line_header *lh, const char *name, unsigned int dir_index, unsigned int mod_time, unsigned int length)
static struct dwarf2_section_info * get_debug_line_section (struct dwarf2_cu *cu)
static const char * psymtab_include_file_name (const struct line_header *lh, int file_index, const struct partial_symtab *pst, const char *comp_dir)
static void noop_record_line (struct subfile *subfile, int line, CORE_ADDR pc)
static void dwarf_decode_lines_1 (struct line_header *lh, const char *comp_dir, struct dwarf2_cu *cu, struct partial_symtab *pst)
static void var_decode_location (struct attribute *attr, struct symbol *sym, struct dwarf2_cu *cu)
static gdb_byte * dwarf2_const_value_data (const struct attribute *attr, struct obstack *obstack, struct dwarf2_cu *cu, LONGEST *value, int bits)
static struct type * build_error_marker_type (struct dwarf2_cu *cu, struct die_info *die)
static char * guess_full_die_structure_name (struct die_info *die, struct dwarf2_cu *cu)
static char * anonymous_struct_prefix (struct die_info *die, struct dwarf2_cu *cu)
static struct die_info * follow_die_offset (sect_offset offset, int offset_in_dwz, struct dwarf2_cu **ref_cu)
struct dwarf2_locexpr_baton dwarf2_fetch_die_loc_sect_off (sect_offset offset, struct dwarf2_per_cu_data *per_cu, CORE_ADDR(*get_frame_pc)(void *baton), void *baton)
struct dwarf2_locexpr_baton dwarf2_fetch_die_loc_cu_off (cu_offset offset_in_cu, struct dwarf2_per_cu_data *per_cu, CORE_ADDR(*get_frame_pc)(void *baton), void *baton)
static const gdb_byte * write_constant_as_bytes (struct obstack *obstack, enum bfd_endian byte_order, struct type *type, ULONGEST value, LONGEST *len)
const gdb_byte * dwarf2_fetch_constant_bytes (sect_offset offset, struct dwarf2_per_cu_data *per_cu, struct obstack *obstack, LONGEST *len)
struct type * dwarf2_get_die_type (cu_offset die_offset, struct dwarf2_per_cu_data *per_cu)
static struct die_info * follow_die_sig_1 (struct die_info *src_die, struct signatured_type *sig_type, struct dwarf2_cu **ref_cu)
static void read_signatured_type_reader (const struct die_reader_specs *reader, const gdb_byte *info_ptr, struct die_info *comp_unit_die, int has_children, void *data)
static char * file_file_name (int file, struct line_header *lh)
static struct macro_source_file * macro_start_file (int file, int line, struct macro_source_file *current_file, const char *comp_dir, struct line_header *lh, struct objfile *objfile)
static char * copy_string (const char *buf, int len)
static const char * consume_improper_spaces (const char *p, const char *body)
static void parse_macro_definition (struct macro_source_file *file, int line, const char *body)
static const gdb_byte * skip_form_bytes (bfd *abfd, const gdb_byte *bytes, const gdb_byte *buffer_end, enum dwarf_form form, unsigned int offset_size, struct dwarf2_section_info *section)
static const gdb_byte * skip_unknown_opcode (unsigned int opcode, const gdb_byte **opcode_definitions, const gdb_byte *mac_ptr, const gdb_byte *mac_end, bfd *abfd, unsigned int offset_size, struct dwarf2_section_info *section)
static const gdb_byte * dwarf_parse_macro_header (const gdb_byte **opcode_definitions, bfd *abfd, const gdb_byte *mac_ptr, unsigned int *offset_size, int section_is_gnu)
static void dwarf_decode_macro_bytes (bfd *abfd, const gdb_byte *mac_ptr, const gdb_byte *mac_end, struct macro_source_file *current_file, struct line_header *lh, const char *comp_dir, struct dwarf2_section_info *section, int section_is_gnu, int section_is_dwz, unsigned int offset_size, struct objfile *objfile, htab_t include_hash)
static struct dwarf2_section_info * cu_debug_loc_section (struct dwarf2_cu *cu)
struct objfile * dwarf2_per_cu_objfile (struct dwarf2_per_cu_data *per_cu)
static struct comp_unit_head * per_cu_header_read_in (struct comp_unit_head *cu_headerp, struct dwarf2_per_cu_data *per_cu)
int dwarf2_per_cu_addr_size (struct dwarf2_per_cu_data *per_cu)
int dwarf2_per_cu_offset_size (struct dwarf2_per_cu_data *per_cu)
int dwarf2_per_cu_ref_addr_size (struct dwarf2_per_cu_data *per_cu)
CORE_ADDR dwarf2_per_cu_text_offset (struct dwarf2_per_cu_data *per_cu)
void dwarf2_free_objfile (struct objfile *objfile)
static hashval_t per_cu_offset_and_type_hash (const void *item)
static int per_cu_offset_and_type_eq (const void *item_lhs, const void *item_rhs)
static int dwarf2_mark_helper (void **slot, void *data)
static void set_dwarf2_cmd (char *args, int from_tty)
static void show_dwarf2_cmd (char *args, int from_tty)
static void dwarf2_per_objfile_free (struct objfile *objfile, void *d)
static hashval_t hash_strtab_entry (const void *e)
static int eq_strtab_entry (const void *a, const void *b)
static htab_t create_strtab (void)
static offset_type add_string (htab_t table, struct obstack *cpool, const char *str)
static hashval_t hash_symtab_entry (const void *e)
static int eq_symtab_entry (const void *a, const void *b)
static void delete_symtab_entry (void *p)
static htab_t create_symbol_hash_table (void)
static struct mapped_symtab * create_mapped_symtab (void)
static void cleanup_mapped_symtab (void *p)
static struct symtab_index_entry ** find_slot (struct mapped_symtab *symtab, const char *name)
static void hash_expand (struct mapped_symtab *symtab)
static void add_index_entry (struct mapped_symtab *symtab, const char *name, int is_static, gdb_index_symbol_kind kind, offset_type cu_index)
static int offset_type_compare (const void *ap, const void *bp)
static void uniquify_cu_indices (struct mapped_symtab *symtab)
static offset_type add_indices_to_cpool (htab_t symbol_hash_table, struct obstack *cpool, struct symtab_index_entry *entry)
static void write_hash_table (struct mapped_symtab *symtab, struct obstack *output, struct obstack *cpool)
static hashval_t hash_psymtab_cu_index (const void *item)
static int eq_psymtab_cu_index (const void *item_lhs, const void *item_rhs)
static void add_address_entry (struct objfile *objfile, struct obstack *obstack, CORE_ADDR start, CORE_ADDR end, unsigned int cu_index)
static int add_address_entry_worker (void *datap, CORE_ADDR start_addr, void *obj)
static void write_address_map (struct objfile *objfile, struct obstack *obstack, htab_t cu_index_htab)
static gdb_index_symbol_kind symbol_kind (struct partial_symbol *psym)
static void write_psymbols (struct mapped_symtab *symtab, htab_t psyms_seen, struct partial_symbol **psymp, int count, offset_type cu_index, int is_static)
static void write_obstack (FILE *file, struct obstack *obstack)
static void unlink_if_set (void *p)
static int write_one_signatured_type (void **slot, void *d)
static void recursively_write_psymbols (struct objfile *objfile, struct partial_symtab *psymtab, struct mapped_symtab *symtab, htab_t psyms_seen, offset_type cu_index)
static void write_psymtabs_to_index (struct objfile *objfile, const char *dir)
static void save_gdb_index_command (char *arg, int from_tty)
static void show_dwarf2_always_disassemble (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static void show_check_physname (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
void _initialize_dwarf2_read (void)
Variables
static int dwarf2_read_debug = 0
static unsigned int dwarf2_die_debug = 0
static int check_physname = 0
static int use_deprecated_index_sections = 0
static struct objfile_data * dwarf2_objfile_data_key
static int dwarf2_locexpr_index
static int dwarf2_loclist_index
static int dwarf2_locexpr_block_index
static int dwarf2_loclist_block_index
static struct dwarf2_per_objfile * dwarf2_per_objfile
static struct dwarf2_debug_sections dwarf2_elf_names
static struct dwop_section_names dwop_section_names
static int bits_per_byte = 8
static struct dwarf2_queue_item * dwarf2_queue
static struct dwarf2_queue_item * dwarf2_queue_tail
static int dwarf2_max_cache_age = 5
struct quick_symbol_functions dwarf2_gdb_index_functions
static struct cmd_list_element * set_dwarf2_cmdlist
static struct cmd_list_element * show_dwarf2_cmdlist
int dwarf2_always_disassemble
Define Documentation
#define ABBREV_HASH_SIZE 121
Definition at line 1171 of file dwarf2read.c.
Referenced by abbrev_table_add_abbrev(), abbrev_table_lookup_abbrev(), and abbrev_table_read_table().
#define ATTR_ALLOC_CHUNK 4
Definition at line 1267 of file dwarf2read.c.
Referenced by abbrev_table_read_table().
#define DW2_GDB_INDEX_CU_SET_VALUE (cu_index, value)
Value:
do { \
    gdb_assert (((value) & ~GDB_INDEX_CU_MASK) == 0); \
    GDB_INDEX_CU_SET_VALUE((cu_index), (value)); \
  } while (0)
Definition at line 169 of file dwarf2read.c.
Referenced by add_index_entry().
#define DW2_GDB_INDEX_SYMBOL_KIND_SET_VALUE (cu_index, value)
Value:
do { \
    gdb_assert ((value) >= GDB_INDEX_SYMBOL_KIND_TYPE \
                && (value) <= GDB_INDEX_SYMBOL_KIND_OTHER); \
    GDB_INDEX_SYMBOL_KIND_SET_VALUE((cu_index), (value)); \
  } while (0)
Definition at line 161 of file dwarf2read.c.
Referenced by add_index_entry().
#define DW2_GDB_INDEX_SYMBOL_STATIC_SET_VALUE (cu_index, value)
Value:
do { \
    gdb_assert ((unsigned int) (value) <= 1); \
    GDB_INDEX_SYMBOL_STATIC_SET_VALUE((cu_index), (value)); \
  } while (0)
Definition at line 154 of file dwarf2read.c.
Referenced by add_index_entry().
#define DW_ADDR (attr) ((attr)->u.addr)
Definition at line 1254 of file dwarf2read.c.
Referenced by dump_die_shallow(), dwarf2_const_value_attr(), dwarf2_fetch_constant_bytes(), dwarf2_find_base_address(), dwarf2_get_pc_bounds(), dwarf2_record_block_ranges(), new_symbol_full(), read_attribute_value(), read_call_site_scope(), and read_partial_die().
#define DW_BLOCK (attr) ((attr)->u.blk)
Definition at line 1252 of file dwarf2read.c.
Referenced by dump_die_shallow(), dwarf2_add_member_fn(), dwarf2_const_value_attr(), dwarf2_fetch_constant_bytes(), dwarf2_fetch_die_loc_sect_off(), dwarf2_symbol_mark_computed(), handle_data_member_location(), mark_common_block_symbol_computed(), read_attribute_value(), read_call_site_scope(), read_partial_die(), and var_decode_location().
#define DW_FIELD_ALLOC_CHUNK 4
Definition at line 1272 of file dwarf2read.c.
Referenced by dwarf2_add_member_fn(), process_enumeration_scope(), and read_array_type().
#define DW_SIGNATURE (attr) ((attr)->u.signature)
Definition at line 1255 of file dwarf2read.c.
Referenced by dump_die_shallow(), follow_die_sig(), get_DW_AT_signature_type(), lookup_die_type(), and read_attribute_value().
#define DW_SND (attr) ((attr)->u.snd)
Definition at line 1253 of file dwarf2read.c.
Referenced by dwarf2_const_value_attr(), dwarf2_fetch_constant_bytes(), dwarf2_get_attr_constant_value(), read_array_order(), and read_attribute_value().
#define DW_STRING (attr) ((attr)->u.str)
Definition at line 1249 of file dwarf2read.c.
Referenced by anonymous_struct_prefix(), dump_die_shallow(), dwarf2_compute_name(), dwarf2_const_value_attr(), dwarf2_fetch_constant_bytes(), dwarf2_name(), dwarf2_physname(), find_file_and_directory(), guess_full_die_structure_name(), lookup_dwo_unit(), prepare_one_comp_unit(), process_psymtab_comp_unit_reader(), read_attribute_value(), read_call_site_scope(), read_cutu_die_from_dwo(), and read_partial_die().
#define DW_STRING_IS_CANONICAL (attr) ((attr)->string_is_canonical)
Definition at line 1250 of file dwarf2read.c.
Referenced by anonymous_struct_prefix(), dump_die_shallow(), dwarf2_name(), read_attribute_value(), and read_cutu_die_from_dwo().
#define DW_UNSND (attr) ((attr)->u.unsnd)
Definition at line 1251 of file dwarf2read.c.
Referenced by create_dwo_cu_reader(), dump_die_shallow(), dw2_get_file_names_reader(), dwarf2_add_field(), dwarf2_add_member_fn(), dwarf2_build_include_psymtabs(), dwarf2_const_value_attr(), dwarf2_const_value_data(), dwarf2_fetch_constant_bytes(), dwarf2_flag_true_p(), dwarf2_get_attr_constant_value(), dwarf2_get_pc_bounds(), dwarf2_get_ref_die_offset(), dwarf2_record_block_ranges(), dwarf2_symbol_mark_computed(), fill_in_loclist_baton(), get_type_unit_group(), handle_DW_AT_stmt_list(), lookup_dwo_unit(), new_symbol_full(), prepare_one_comp_unit(), prototyped_function_p(), read_array_type(), read_attribute_value(), read_base_type(), read_cutu_die_from_dwo(), read_enumeration_type(), read_file_scope(), read_func_scope(), read_partial_die(), read_set_type(), read_structure_type(), read_subrange_type(), read_subroutine_type(), read_tag_pointer_type(), read_tag_reference_type(), read_tag_string_type(), and setup_type_unit_groups().
#define INDEX_SUFFIX ".gdb-index"
Definition at line 1940 of file dwarf2read.c.
Referenced by write_psymtabs_to_index().
#define IS_TYPE_UNIT_GROUP (per_cu) ((per_cu)->section == NULL)
Definition at line 714 of file dwarf2read.c.
Referenced by build_type_psymtab_dependencies(), dw2_do_instantiate_symtab(), dw2_get_file_names(), and load_full_type_unit().
#define MAX_NR_V1_DWO_SECTIONS
Value:
(1 /* .debug_info or .debug_types */ \
   + 1 /* .debug_abbrev */ \
   + 1 /* .debug_line */ \
   + 1 /* .debug_loc */ \
   + 1 /* .debug_str_offsets */ \
   + 1 /* .debug_macro or .debug_macinfo */ \
   + 1 /* trailing zero */)
Referenced by create_dwo_unit_in_dwp_v1().
#define MAX_NR_V2_DWO_SECTIONS
Value:
(1 /* .debug_info or .debug_types */ \
   + 1 /* .debug_abbrev */ \
   + 1 /* .debug_line */ \
   + 1 /* .debug_loc */ \
   + 1 /* .debug_str_offsets */ \
   + 1 /* .debug_macro or .debug_macinfo */)
Definition at line 927 of file dwarf2read.c.
Referenced by create_dwp_hash_table().
#define MAX_SEP_LEN 7 /* strlen ("__") + strlen ("_MOD_") */
Definition at line 18320 of file dwarf2read.c.
Referenced by typename_concat().
#define MAYBE_SWAP (V) (V)
Definition at line 1936 of file dwarf2read.c.
Referenced by add_address_entry(), add_indices_to_cpool(), dw2_expand_symtabs_matching(), dw2_symtab_iter_init(), dw2_symtab_iter_next(), find_slot_in_mapped_hash(), read_index_from_section(), write_hash_table(), and write_psymtabs_to_index().
#define NO_STMT_LIST_TYPE_UNIT_PSYMTAB (1 << 31)
Definition at line 5589 of file dwarf2read.c.
Referenced by create_type_unit_group(), and get_type_unit_group().
#define NO_STMT_LIST_TYPE_UNIT_PSYMTAB_SIZE 10
Definition at line 5590 of file dwarf2read.c.
Referenced by get_type_unit_group().
Typedef Documentation
typedef struct delayed_method_info delayed_method_info
Definition at line 420 of file dwarf2read.c.
typedef void(die_reader_func_ftype)(const struct die_reader_specs *reader, const gdb_byte *info_ptr, struct die_info *comp_unit_die, int has_children, void *data)
Definition at line 1020 of file dwarf2read.c.
typedef struct dwarf2_per_cu_data* dwarf2_per_cu_ptr
Definition at line 201 of file dwarf2read.c.
typedef struct dwarf2_section_info dwarf2_section_info_def
Definition at line 144 of file dwarf2read.c.
typedef uint32_t offset_type
Definition at line 149 of file dwarf2read.c.
typedef struct signatured_type* sig_type_ptr
Definition at line 689 of file dwarf2read.c.
typedef struct symbol* symbolp
Definition at line 79 of file dwarf2read.c.
Enumeration Type Documentation
enum dwp_v2_section_ids
Enumerator:
DW_SECT_MIN
Definition at line 788 of file dwarf2read.c.
Function Documentation
void _initialize_dwarf2_read (void)
static void abbrev_table_add_abbrev (struct abbrev_table * abbrev_table, unsigned int abbrev_number, struct abbrev_info * abbrev) [static]
Definition at line 14531 of file dwarf2read.c.
References ABBREV_HASH_SIZE, abbrev_table::abbrevs, and abbrev_info::next.
Referenced by abbrev_table_read_table().
static struct abbrev_info* abbrev_table_alloc_abbrev (struct abbrev_table * abbrev_table) [static, read]
Definition at line 14518 of file dwarf2read.c.
References abbrev_table::abbrev_obstack, and memset().
Referenced by abbrev_table_read_table().
static void abbrev_table_free (struct abbrev_table * abbrev_table) [static]
Definition at line 14662 of file dwarf2read.c.
References abbrev_table::abbrev_obstack, and xfree().
Referenced by abbrev_table_free_cleanup(), build_type_unit_groups(), and dwarf2_free_abbrev_table().
static void abbrev_table_free_cleanup (void * table_ptr) [static]
Definition at line 14674 of file dwarf2read.c.
References abbrev_table_free().
Referenced by build_type_unit_groups().
static struct abbrev_info * abbrev_table_lookup_abbrev (const struct abbrev_table * abbrev_table, unsigned int abbrev_number) [static, read]
Definition at line 14546 of file dwarf2read.c.
References ABBREV_HASH_SIZE, abbrev_table::abbrevs, abbrev_info::next, and abbrev_info::number.
Referenced by abbrev_table_read_table(), peek_die_abbrev(), and read_full_die_1().
static struct abbrev_table * abbrev_table_read_table (struct dwarf2_section_info * section, sect_offset offset) [static, read]
Definition at line 14567 of file dwarf2read.c.
References ABBREV_HASH_SIZE, abbrev_table::abbrev_obstack, abbrev_table_add_abbrev(), abbrev_table_alloc_abbrev(), abbrev_table_lookup_abbrev(), abbrev_table::abbrevs, ATTR_ALLOC_CHUNK, abbrev_info::attrs, dwarf2_section_info::buffer, dwarf2_read_section(), get_section_bfd_owner(), abbrev_info::has_children, memcpy(), memset(), abbrev_info::num_attrs, abbrev_info::number, offset, abbrev_table::offset, read_1_byte(), read_unsigned_leb128(), sect_offset::sect_off, dwarf2_section_info::size, abbrev_info::tag, xfree(), xmalloc(), XMALLOC, and xrealloc().
Referenced by build_type_unit_groups(), and dwarf2_read_abbrevs().
static void add_address_entry (struct objfile * objfile, struct obstack * obstack, CORE_ADDR start, CORE_ADDR end, unsigned int cu_index) [static]
Definition at line 21827 of file dwarf2read.c.
References ANOFFSET, MAYBE_SWAP, SECT_OFF_TEXT, objfile::section_offsets, and store_unsigned_integer().
Referenced by add_address_entry_worker(), and write_address_map().
static int add_address_entry_worker (void * datap, CORE_ADDR start_addr, void * obj) [static]
Definition at line 21847 of file dwarf2read.c.
References add_address_entry(), addrmap_index_data::addr_obstack, psymtab_cu_index_map::cu_index, addrmap_index_data::cu_index_htab, gdb_assert, addrmap_index_data::objfile, addrmap_index_data::previous_cu_index, addrmap_index_data::previous_cu_start, addrmap_index_data::previous_valid, and psymtab_cu_index_map::psymtab.
Referenced by write_address_map().
static void add_file_name (struct line_header * lh, const char * name, unsigned int dir_index, unsigned int mod_time, unsigned int length) [static]
Definition at line 16420 of file dwarf2read.c.
References line_header::file_names, line_header::file_names_size, name, line_header::file_entry::name, line_header::num_file_names, xmalloc(), and xrealloc().
Referenced by dwarf_decode_line_header(), and dwarf_decode_lines_1().
static void add_include_dir (struct line_header * lh, const char * include_dir) [static]
Definition at line 16397 of file dwarf2read.c.
References line_header::include_dirs, line_header::include_dirs_size, line_header::num_include_dirs, xmalloc(), and xrealloc().
Referenced by dwarf_decode_line_header().
static void add_index_entry (struct mapped_symtab * symtab, const char * name, int is_static, gdb_index_symbol_kind kind, offset_type cu_index) [static]
Definition at line 21607 of file dwarf2read.c.
References DW2_GDB_INDEX_CU_SET_VALUE, DW2_GDB_INDEX_SYMBOL_KIND_SET_VALUE, DW2_GDB_INDEX_SYMBOL_STATIC_SET_VALUE, find_slot(), hash_expand(), mapped_symtab::n_elements, name, mapped_symtab::size, and VEC_safe_push.
Referenced by write_psymbols().
static offset_type add_indices_to_cpool (htab_t symbol_hash_table, struct obstack * cpool, struct symtab_index_entry * entry) [static]
Definition at line 21698 of file dwarf2read.c.
References symtab_index_entry::index_offset, len, MAYBE_SWAP, VEC_iterate, and VEC_length.
Referenced by write_hash_table().
static void add_partial_enumeration (struct partial_die_info * enum_pdi, struct dwarf2_cu * cu) [static]
Definition at line 6912 of file dwarf2read.c.
References _, add_partial_symbol(), complaint(), partial_die_info::die_child, partial_die_info::die_sibling, and symfile_complaints.
Referenced by scan_partial_symbols().
static void add_partial_module (struct partial_die_info * pdi, CORE_ADDR * lowpc, CORE_ADDR * highpc, int need_pc, struct dwarf2_cu * cu) [static]
Definition at line 6835 of file dwarf2read.c.
References partial_die_info::die_child, and scan_partial_symbols().
Referenced by scan_partial_symbols().
static void add_partial_namespace (struct partial_die_info * pdi, CORE_ADDR * lowpc, CORE_ADDR * highpc, int need_pc, struct dwarf2_cu * cu) [static]
Definition at line 6818 of file dwarf2read.c.
References add_partial_symbol(), partial_die_info::die_child, and scan_partial_symbols().
Referenced by scan_partial_symbols().
static void add_partial_subprogram (struct partial_die_info * pdi, CORE_ADDR * lowpc, CORE_ADDR * highpc, int need_pc, struct dwarf2_cu * cu) [static]
Definition at line 6855 of file dwarf2read.c.
References add_partial_symbol(), addrmap_set_empty(), ANOFFSET, partial_die_info::die_child, partial_die_info::die_sibling, fixup_partial_die(), partial_die_info::highpc, dwarf2_cu::language, language_ada, partial_die_info::lowpc, dwarf2_cu::objfile, dwarf2_cu::per_cu, dwarf2_per_cu_data::psymtab, objfile::psymtabs_addrmap, SECT_OFF_TEXT, objfile::section_offsets, and dwarf2_per_cu_data::v.
Referenced by scan_partial_symbols().
static void add_partial_symbol (struct partial_die_info * pdi, struct dwarf2_cu * cu) [static]
Definition at line 6638 of file dwarf2read.c.
References add_psymbol_to_list(), ANOFFSET, partial_die_info::d, decode_locdesc(), objfile::global_psymbols, dwarf2_per_objfile::has_section_at_zero, dwarf2_cu::language, language_ada, language_cplus, language_java, psymbol_allocation_list::list, LOC_BLOCK, LOC_CONST, LOC_STATIC, LOC_TYPEDEF, partial_die_info::lowpc, dwarf2_cu::objfile, partial_die_full_name(), SECT_OFF_TEXT, objfile::section_offsets, objfile::static_psymbols, STRUCT_DOMAIN, VAR_DOMAIN, and xfree().
Referenced by add_partial_enumeration(), add_partial_namespace(), add_partial_subprogram(), and scan_partial_symbols().
static int add_signatured_type_cu_to_table (void ** slot, void * datum) [static]
Definition at line 4449 of file dwarf2read.c.
Referenced by create_all_type_units().
static offset_type add_string (htab_t table, struct obstack * cpool, const char * str) [static]
Definition at line 21444 of file dwarf2read.c.
References obstack_grow_str0, strtab_entry::offset, and strtab_entry::str.
Referenced by write_hash_table().
static void add_to_method_list (struct type * type, int fnfield_index, int index, const char * name, struct die_info * die, struct dwarf2_cu * cu) [static]
Definition at line 7467 of file dwarf2read.c.
References delayed_method_info::die, delayed_method_info::fnfield_index, delayed_method_info::index, name, delayed_method_info::name, type, delayed_method_info::type, and VEC_safe_push.
Referenced by dwarf2_add_member_fn().
static struct signatured_type* add_type_unit (ULONGEST sig) [static, read]
Definition at line 4743 of file dwarf2read.c.
References gdb_assert, dwarf2_per_cu_data::is_debug_types, objfile::objfile_obstack, OBSTACK_ZALLOC, signatured_type::per_cu, dwarf2_per_cu_data::quick, signatured_type::signature, dwarf2_per_cu_data::v, and xrealloc().
Referenced by lookup_dwp_signatured_type().
static int add_type_unit_group_to_table (void ** slot, void * datum) [static]
Definition at line 5721 of file dwarf2read.c.
Referenced by build_type_unit_groups().
static void age_cached_comp_units (void) [static]
Definition at line 21041 of file dwarf2read.c.
References dwarf2_per_cu_data::cu, dwarf2_clear_marks(), dwarf2_mark(), dwarf2_max_cache_age, free_heap_comp_unit(), dwarf2_cu::last_used, dwarf2_per_objfile::read_in_chain, and dwarf2_cu::read_in_chain.
Referenced by dw2_do_instantiate_symtab(), dwarf2_fetch_die_loc_sect_off(), and process_psymtab_comp_unit().
static htab_t allocate_dwo_file_hash_table (void) [static]
Definition at line 8982 of file dwarf2read.c.
References dummy_obstack_deallocate(), eq_dwo_file(), hash_dwo_file(), hashtab_obstack_allocate(), and objfile::objfile_obstack.
Referenced by lookup_dwo_file_slot().
static htab_t allocate_dwo_unit_table (struct objfile * objfile) [static]
Definition at line 9040 of file dwarf2read.c.
References dummy_obstack_deallocate(), eq_dwo_unit(), hash_dwo_unit(), hashtab_obstack_allocate(), and objfile::objfile_obstack.
Referenced by create_debug_types_hash_table().
static htab_t allocate_dwp_loaded_cutus_table (struct objfile * objfile) [static]
Definition at line 10307 of file dwarf2read.c.
References dummy_obstack_deallocate(), eq_dwp_loaded_cutus(), hash_dwp_loaded_cutus(), hashtab_obstack_allocate(), and objfile::objfile_obstack.
Referenced by open_and_init_dwp_file().
static htab_t allocate_signatured_type_table (struct objfile * objfile) [static]
Definition at line 4435 of file dwarf2read.c.
References dummy_obstack_deallocate(), eq_signatured_type(), hash_signatured_type(), hashtab_obstack_allocate(), and objfile::objfile_obstack.
Referenced by create_debug_types_hash_table(), and create_signatured_type_table_from_index().
static htab_t allocate_type_unit_groups_table (void) [static]
Definition at line 5575 of file dwarf2read.c.
References dummy_obstack_deallocate(), eq_type_unit_group(), hash_type_unit_group(), and hashtab_obstack_allocate().
Referenced by build_type_unit_groups(), and get_type_unit_group().
static char* anonymous_struct_prefix (struct die_info * die, struct dwarf2_cu * cu) [static]
Definition at line 18132 of file dwarf2read.c.
References DW_STRING, DW_STRING_IS_CANONICAL, dwarf2_attr(), gdb_assert, dwarf2_cu::objfile, objfile::objfile_obstack, and strrchr().
Referenced by determine_prefix().
static int attr_form_is_block (const struct attribute * attr) [static]
Definition at line 20623 of file dwarf2read.c.
Referenced by dwarf2_add_member_fn(), dwarf2_fetch_die_loc_sect_off(), dwarf2_symbol_mark_computed(), handle_data_member_location(), mark_common_block_symbol_computed(), read_call_site_scope(), read_common_block(), read_partial_die(), read_subrange_type(), and var_decode_location().
static int attr_form_is_constant (const struct attribute * attr) [static]
Definition at line 20664 of file dwarf2read.c.
Referenced by handle_data_member_location(), mark_common_block_symbol_computed(), and read_common_block().
static int attr_form_is_ref (const struct attribute * attr) [static]
Definition at line 20685 of file dwarf2read.c.
Referenced by dwarf2_get_ref_die_offset(), follow_die_ref_or_sig(), get_DW_AT_signature_type(), lookup_die_type(), read_attribute_value(), read_call_site_scope(), and read_subrange_type().
static int attr_form_is_section_offset (const struct attribute * attr) [static]
Definition at line 20643 of file dwarf2read.c.
Referenced by dwarf2_add_member_fn(), dwarf2_fetch_die_loc_sect_off(), dwarf2_symbol_mark_computed(), handle_data_member_location(), read_common_block(), and read_partial_die().
static struct type* build_error_marker_type (struct dwarf2_cu * cu, struct die_info * die) [static, read]
Definition at line 17867 of file dwarf2read.c.
References _, dwarf2_cu::header, init_type(), objfile_name(), objfile::objfile_obstack, comp_unit_head::offset, sect_offset::sect_off, TYPE_CODE_ERROR, xfree(), and xstrprintf().
Referenced by get_DW_AT_signature_type(), get_signatured_type(), and lookup_die_type().
static int build_type_psymtab_dependencies (void ** slot, void * info) [static]
Definition at line 6141 of file dwarf2read.c.
References partial_symtab::dependencies, gdb_assert, dwarf2_per_cu_data::is_debug_types, IS_TYPE_UNIT_GROUP, len, partial_symtab::number_of_dependencies, objfile::objfile_obstack, signatured_type::per_cu, type_unit_group::per_cu, dwarf2_per_cu_data::psymtab, signatured_type::type_unit_group, dwarf2_per_cu_data::v, VEC_free, VEC_iterate, and VEC_length.
Referenced by build_type_psymtabs().
static void build_type_psymtabs (struct objfile * objfile) [static]
Definition at line 6175 of file dwarf2read.c.
References build_type_psymtab_dependencies(), build_type_psymtabs_reader(), build_type_unit_groups(), and create_all_type_units().
Referenced by dwarf2_build_psymtabs_hard().
static void build_type_psymtabs_reader (const struct die_reader_specs * reader, const gdb_byte * info_ptr, struct die_info * type_unit_die, int has_children, void * data) [static]
Definition at line 6092 of file dwarf2read.c.
References partial_symtab::anonymous, create_partial_symtab(), die_reader_specs::cu, dwarf2_attr_no_follow(), file_symbols, gdb_assert, get_type_unit_group(), objfile::global_psymbols, partial_symtab::globals_offset, partial_die_info::highpc, dwarf2_per_cu_data::is_debug_types, language_minimal, psymbol_allocation_list::list, dwarf2_cu::list_in_scope, load_partial_dies(), partial_die_info::lowpc, partial_symtab::n_global_syms, partial_symtab::n_static_syms, psymbol_allocation_list::next, dwarf2_cu::per_cu, prepare_one_comp_unit(), scan_partial_symbols(), sort_pst_symbols(), objfile::static_psymbols, partial_symtab::statics_offset, and VEC_safe_push.
Referenced by build_type_psymtabs().
static void build_type_unit_groups (die_reader_func_ftype * func, void * data) [static]
Definition at line 5751 of file dwarf2read.c.
References dwarf2_per_objfile::abbrev, tu_abbrev_offset::abbrev_offset, abbrev_table_free(), abbrev_table_free_cleanup(), abbrev_table_read_table(), add_type_unit_group_to_table(), allocate_type_unit_groups_table(), do_cleanups(), dwarf2_read_debug, fprintf_unfiltered(), gdb_assert, gdb_stdlog, init_cutu_and_read_dies(), make_cleanup(), objfile::objfile_obstack, dwarf2_per_cu_data::offset, signatured_type::per_cu, qsort, read_abbrev_offset(), sect_offset::sect_off, dwarf2_per_cu_data::section, tu_abbrev_offset::sig_type, sort_tu_by_abbrev_offset(), dwarf2_per_objfile::tu_stats, and xfree().
Referenced by build_type_psymtabs().
static void check_producer (struct dwarf2_cu * cu) [static]
Definition at line 11816 of file dwarf2read.c.
References dwarf2_cu::producer.
Referenced by producer_is_gcc_lt_4_3(), producer_is_gxx_lt_4_6(), and producer_is_icc().
static void cleanup_mapped_symtab (void * p) [static]
Definition at line 21546 of file dwarf2read.c.
References mapped_symtab::data, and xfree().
Referenced by write_psymtabs_to_index().
static void compute_delayed_physnames (struct dwarf2_cu * cu) [static]
Definition at line 7500 of file dwarf2read.c.
References delayed_method_info::die, dwarf2_physname(), delayed_method_info::fnfield_index, delayed_method_info::index, delayed_method_info::name, delayed_method_info::type, TYPE_FN_FIELDLIST, and VEC_iterate.
Referenced by process_full_comp_unit(), and process_full_type_unit().
static void compute_symtab_includes (struct dwarf2_per_cu_data * per_cu) [static]
Definition at line 7661 of file dwarf2read.c.
References gdb_assert, get_symtab(), symtab::includes, dwarf2_per_cu_data::is_debug_types, len, recursively_compute_inclusions(), VEC, VEC_empty, VEC_free, VEC_iterate, VEC_length, xcalloc(), and xfree().
Referenced by process_cu_includes().
static const char* consume_improper_spaces (const char * p, const char * body) [static]
Definition at line 19807 of file dwarf2read.c.
References _, complaint(), and symfile_complaints.
Referenced by parse_macro_definition().
static char* copy_string (const char * buf, int len) [static]
Definition at line 19796 of file dwarf2read.c.
References len, memcpy(), and xmalloc().
Referenced by parse_macro_definition().
static void create_addrmap_from_index (struct objfile * objfile, struct mapped_index * index) [static]
Definition at line 2811 of file dwarf2read.c.
References _, mapped_index::address_table, mapped_index::address_table_size, addrmap_create_fixed(), addrmap_create_mutable(), addrmap_set_empty(), ANOFFSET, complaint(), do_cleanups(), dw2_get_cu(), extract_unsigned_integer(), hex_string(), make_cleanup_obstack_free(), objfile::objfile_obstack, objfile::psymtabs_addrmap, SECT_OFF_TEXT, objfile::section_offsets, symfile_complaints, and ULONGEST.
Referenced by dwarf2_read_index().
static void create_all_comp_units (struct objfile * objfile) [static]
Definition at line 6367 of file dwarf2read.c.
References dwarf2_get_dwz_file(), dwarf2_per_objfile::info, dwz_file::info, memcpy(), objfile::objfile_obstack, read_comp_units_from_section(), xfree(), and xmalloc().
Referenced by dwarf2_build_psymtabs_hard(), and dwarf2_initialize_objfile().
static int create_all_type_units (struct objfile * objfile) [static]
Definition at line 4627 of file dwarf2read.c.
References add_signatured_type_cu_to_table(), create_debug_types_hash_table(), gdb_assert, and xmalloc().
Referenced by build_type_psymtabs(), and dwarf2_initialize_objfile().
static void create_cus_from_index (struct objfile * objfile, const gdb_byte * cu_list, offset_type cu_list_elements, const gdb_byte * dwz_list, offset_type dwz_elements) [static]
Definition at line 2732 of file dwarf2read.c.
References create_cus_from_index_list(), dwarf2_get_dwz_file(), dwarf2_per_objfile::info, dwz_file::info, and objfile::objfile_obstack.
Referenced by dwarf2_read_index().
static void create_cus_from_index_list (struct objfile * objfile, const gdb_byte * cu_list, offset_type n_elements, struct dwarf2_section_info * section, int is_dwz, int base_offset) [static]
Definition at line 2697 of file dwarf2read.c.
References extract_unsigned_integer(), gdb_static_assert, dwarf2_per_cu_data::is_dwz, dwarf2_per_cu_data::length, dwarf2_per_cu_data::objfile, objfile::objfile_obstack, OBSTACK_ZALLOC, offset, dwarf2_per_cu_data::offset, dwarf2_per_cu_data::quick, sect_offset::sect_off, dwarf2_per_cu_data::section, ULONGEST, and dwarf2_per_cu_data::v.
Referenced by create_cus_from_index().
static htab_t create_debug_types_hash_table (struct dwo_file * dwo_file, VEC(dwarf2_section_info_def)* types) [static]
Definition at line 4470 of file dwarf2read.c.
References _, dwarf2_per_objfile::abbrev, dwo_sections::abbrev, allocate_dwo_unit_table(), allocate_signatured_type_table(), dwarf2_section_info::buffer, complaint(), dwarf2_read_debug, dwarf2_read_section(), dwo_unit::dwo_file, fprintf_unfiltered(), gdb_assert, gdb_stdlog, get_cu_length(), get_section_bfd_owner(), get_section_file_name(), hex_string(), dwarf2_per_cu_data::is_debug_types, comp_unit_head::length, dwarf2_per_cu_data::length, dwo_unit::length, dwarf2_per_cu_data::objfile, objfile::objfile_obstack, OBSTACK_ZALLOC, offset, dwarf2_per_cu_data::offset, dwo_unit::offset, peek_abbrev_code(), signatured_type::per_cu, read_and_check_type_unit_head(), sect_offset::sect_off, dwarf2_per_cu_data::section, dwo_unit::section, dwo_file::sections, signatured_type::signature, dwo_unit::signature, dwarf2_section_info::size, symfile_complaints, signatured_type::type_offset_in_tu, dwo_unit::type_offset_in_tu, ULONGEST, VEC_empty, and VEC_iterate.
Referenced by create_all_type_units(), and open_and_init_dwo_file().
static struct dwo_unit* create_dwo_cu (struct dwo_file * dwo_file) [static, read]
Definition at line 9104 of file dwarf2read.c.
References _, dwo_sections::abbrev, dwarf2_section_info::buffer, complaint(), create_dwo_cu_reader(), dwarf2_read_debug, dwarf2_read_section(), dwo_unit::dwo_file, create_dwo_cu_data::dwo_file, dwo_file::dwo_name, create_dwo_cu_data::dwo_unit, fprintf_unfiltered(), gdb_stdlog, get_section_bfd_owner(), get_section_file_name(), get_section_name(), dwo_sections::info, init_cutu_and_read_dies_no_follow(), dwarf2_per_cu_data::is_debug_types, dwarf2_per_cu_data::length, memset(), dwarf2_per_cu_data::objfile, objfile_name(), objfile::objfile_obstack, OBSTACK_ZALLOC, dwarf2_per_cu_data::offset, sect_offset::sect_off, dwarf2_per_cu_data::section, dwo_file::sections, dwarf2_section_info::size, and symfile_complaints.
Referenced by open_and_init_dwo_file().
static void create_dwo_cu_reader (const struct die_reader_specs * reader, const gdb_byte * info_ptr, struct die_info * comp_unit_die, int has_children, void * datap) [static]
Definition at line 9064 of file dwarf2read.c.
References _, complaint(), die_reader_specs::cu, DW_UNSND, dwarf2_attr(), dwarf2_read_debug, dwo_unit::dwo_file, create_dwo_cu_data::dwo_file, dwo_file::dwo_name, create_dwo_cu_data::dwo_unit, fprintf_unfiltered(), gdb_stdlog, hex_string(), dwarf2_per_cu_data::length, dwo_unit::length, offset, dwarf2_per_cu_data::offset, dwo_unit::offset, dwarf2_cu::per_cu, sect_offset::sect_off, dwarf2_per_cu_data::section, dwo_unit::section, dwo_unit::signature, and symfile_complaints.
Referenced by create_dwo_cu().
static struct dwo_unit* create_dwo_unit_in_dwp_v1 (struct dwp_file * dwp_file, uint32_t unit_index, const char * comp_dir, ULONGEST signature, int is_debug_types) [static, read]
Definition at line 9551 of file dwarf2read.c.
References _, dwo_sections::abbrev, virtual_v1_dwo_sections::abbrev, dwo_file::comp_dir, dwp_file::cus, dwp_file::dbfd, do_cleanups(), dwarf2_read_debug, dwarf2_section_empty_p(), dwo_unit::dwo_file, dwo_file::dwo_name, dwp_file::elf_sections, error(), fprintf_unfiltered(), gdb_assert, gdb_stdlog, get_section_id(), hex_string(), virtual_v1_dwo_sections::info_or_types, dwo_sections::line, virtual_v1_dwo_sections::line, dwo_sections::loc, virtual_v1_dwo_sections::loc, locate_v1_virtual_dwo_sections(), lookup_dwo_file_slot(), dwo_sections::macinfo, virtual_v1_dwo_sections::macinfo, dwo_sections::macro, virtual_v1_dwo_sections::macro, make_cleanup(), MAX_NR_V1_DWO_SECTIONS, memset(), dwp_file::name, null_cleanup(), dwp_file::num_sections, objfile::objfile_obstack, OBSTACK_ZALLOC, pulongest(), read_4_bytes(), dwo_unit::section, dwp_hash_table::section_pool, dwo_file::sections, dwp_file::sections, dwo_unit::signature, dwo_sections::str, dwp_sections::str, dwo_sections::str_offsets, virtual_v1_dwo_sections::str_offsets, dwp_file::tus, dwp_hash_table::v1, dwp_file::version, xfree(), and xstrprintf().
Referenced by lookup_dwo_unit_in_dwp().
static struct dwo_unit* create_dwo_unit_in_dwp_v2 (struct dwp_file * dwp_file, uint32_t unit_index, const char * comp_dir, ULONGEST signature, int is_debug_types) [static, read]
Definition at line 9756 of file dwarf2read.c.
References dwo_sections::abbrev, dwp_sections::abbrev, virtual_v2_dwo_sections::abbrev_offset, virtual_v2_dwo_sections::abbrev_size, dwo_file::comp_dir, create_dwp_v2_section(), dwp_file::cus, dwp_file::dbfd, do_cleanups(), dwarf2_read_debug, dwo_unit::dwo_file, dwo_file::dwo_name, fprintf_unfiltered(), gdb_assert, gdb_stdlog, hex_string(), dwp_sections::info, virtual_v2_dwo_sections::info_or_types_offset, virtual_v2_dwo_sections::info_or_types_size, dwo_sections::line, dwp_sections::line, virtual_v2_dwo_sections::line_offset, virtual_v2_dwo_sections::line_size, dwo_sections::loc, dwp_sections::loc, virtual_v2_dwo_sections::loc_offset, virtual_v2_dwo_sections::loc_size, lookup_dwo_file_slot(), dwo_sections::macinfo, dwp_sections::macinfo, virtual_v2_dwo_sections::macinfo_offset, virtual_v2_dwo_sections::macinfo_size, dwo_sections::macro, dwp_sections::macro, virtual_v2_dwo_sections::macro_offset, virtual_v2_dwo_sections::macro_size, make_cleanup(), memset(), dwp_file::name, dwp_hash_table::nr_columns, null_cleanup(), objfile::objfile_obstack, OBSTACK_ZALLOC, offset, pulongest(), read_4_bytes(), dwo_unit::section, dwp_hash_table::section_pool, dwo_file::sections, dwp_file::sections, dwo_unit::signature, size, dwo_sections::str, dwp_sections::str, dwo_sections::str_offsets, dwp_sections::str_offsets, virtual_v2_dwo_sections::str_offsets_offset, virtual_v2_dwo_sections::str_offsets_size, dwp_file::tus, dwp_sections::types, dwp_hash_table::v2, dwp_file::version, xfree(), and xstrprintf().
Referenced by lookup_dwo_unit_in_dwp().
static struct dwp_hash_table* create_dwp_hash_table (struct dwp_file * dwp_file, int is_debug_types) [static, read]
Definition at line 9314 of file dwarf2read.c.
References _, dwarf2_section_info::buffer, complaint(), dwp_sections::cu_index, dwp_file::dbfd, dwarf2_read_section(), dwarf2_section_empty_p(), error(), dwp_hash_table::hash_table, MAX_NR_V2_DWO_SECTIONS, memset(), dwp_file::name, dwp_hash_table::nr_columns, dwp_hash_table::nr_slots, dwp_hash_table::nr_units, objfile::objfile_obstack, OBSTACK_ZALLOC, pulongest(), read_4_bytes(), dwp_hash_table::section_pool, dwp_file::sections, dwarf2_section_info::size, symfile_complaints, dwp_sections::tu_index, dwp_hash_table::unit_table, dwp_hash_table::v1, dwp_hash_table::v2, version, and dwp_hash_table::version.
Referenced by open_and_init_dwp_file().
static struct dwarf2_section_info create_dwp_v2_section (struct dwarf2_section_info * section, bfd_size_type offset, bfd_size_type size) [static, read]
Definition at line 9713 of file dwarf2read.c.
References _, dwarf2_section_info::asection, dwarf2_section_info::containing_section, error(), gdb_assert, get_section_bfd_section(), dwarf2_section_info::is_virtual, memset(), objfile_name(), offset, dwarf2_section_info::s, dwarf2_section_info::size, size, and dwarf2_section_info::virtual_offset.
Referenced by create_dwo_unit_in_dwp_v2().
static struct mapped_symtab* create_mapped_symtab (void) [static, read]
Definition at line 21534 of file dwarf2read.c.
References mapped_symtab::data, mapped_symtab::n_elements, and mapped_symtab::size.
Referenced by write_psymtabs_to_index().
static struct partial_symtab * create_partial_symtab (struct dwarf2_per_cu_data * per_cu, const char * name) [static, read]
Definition at line 5890 of file dwarf2read.c.
References dwarf2_read_symtab(), objfile::global_psymbols, psymbol_allocation_list::next, dwarf2_per_cu_data::objfile, dwarf2_per_cu_data::psymtab, partial_symtab::psymtabs_addrmap_supported, partial_symtab::read_symtab, partial_symtab::read_symtab_private, objfile::section_offsets, start_psymtab_common(), objfile::static_psymbols, and dwarf2_per_cu_data::v.
Referenced by build_type_psymtabs_reader(), create_type_unit_group(), and process_psymtab_comp_unit_reader().
static htab_t create_quick_file_names_table (unsigned int nr_initial_entries) [static]
Definition at line 2554 of file dwarf2read.c.
References delete_file_name_entry(), eq_file_name_entry(), hash_file_name_entry(), xcalloc(), and xfree().
Referenced by dwarf2_initialize_objfile(), and dwarf2_read_index().
static void create_signatured_type_table_from_index (struct objfile * objfile, struct dwarf2_section_info * section, const gdb_byte * bytes, offset_type elements) [static]
Definition at line 2758 of file dwarf2read.c.
References allocate_signatured_type_table(), cu_offset::cu_off, extract_unsigned_integer(), gdb_static_assert, dwarf2_per_cu_data::is_debug_types, dwarf2_per_cu_data::objfile, objfile::objfile_obstack, OBSTACK_ZALLOC, offset, dwarf2_per_cu_data::offset, signatured_type::per_cu, dwarf2_per_cu_data::quick, sect_offset::sect_off, dwarf2_per_cu_data::section, signatured_type::signature, signatured_type::type_offset_in_tu, ULONGEST, dwarf2_per_cu_data::v, and xmalloc().
Referenced by dwarf2_read_index().
static htab_t create_strtab (void) [static]
Definition at line 21434 of file dwarf2read.c.
References eq_strtab_entry(), hash_strtab_entry(), xcalloc(), and xfree().
Referenced by write_hash_table().
static htab_t create_symbol_hash_table (void) [static]
Definition at line 21525 of file dwarf2read.c.
References delete_symtab_entry(), eq_symtab_entry(), hash_symtab_entry(), xcalloc(), and xfree().
Referenced by write_hash_table().
static struct type_unit_group* create_type_unit_group (struct dwarf2_cu * cu, sect_offset line_offset_struct) [static, read]
Definition at line 5596 of file dwarf2read.c.
References partial_symtab::anonymous, create_partial_symtab(), name, NO_STMT_LIST_TYPE_UNIT_PSYMTAB, dwarf2_per_cu_data::objfile, objfile::objfile_obstack, OBSTACK_ZALLOC, type_unit_group::per_cu, dwarf2_per_cu_data::quick, sect_offset::sect_off, dwarf2_per_objfile::using_index, dwarf2_per_cu_data::v, xfree(), and xstrprintf().
Referenced by get_type_unit_group().
static struct dwarf2_section_info* cu_debug_loc_section (struct dwarf2_cu * cu) [static, read]
Definition at line 20706 of file dwarf2read.c.
References dwarf2_per_objfile::loc.
Referenced by dwarf2_symbol_mark_computed(), and fill_in_loclist_baton().
static CORE_ADDR decode_locdesc (struct dwarf_block * blk, struct dwarf2_cu * cu) [static]
Definition at line 19436 of file dwarf2read.c.
References _, complaint(), dwarf_block::data, dwarf2_complex_location_expr_complaint(), objfile::obfd, dwarf2_cu::objfile, read_1_byte(), read_1_signed_byte(), read_2_bytes(), read_2_signed_bytes(), read_4_bytes(), read_4_signed_bytes(), read_8_bytes(), read_addr_index_from_leb128(), read_address(), read_signed_leb128(), read_unsigned_leb128(), size, dwarf_block::size, and symfile_complaints.
Referenced by add_partial_symbol(), dwarf2_add_member_fn(), and handle_data_member_location().
DEF_VEC_I (offset_type)
DEF_VEC_O (dwarf2_section_info_def)
DEF_VEC_O (delayed_method_info)
DEF_VEC_P (symbolp)
DEF_VEC_P (dwarf2_per_cu_ptr)
DEF_VEC_P (sig_type_ptr)
static void delete_file_name_entry (void * e) [static]
Definition at line 2535 of file dwarf2read.c.
References quick_file_names::file_names, quick_file_names::num_file_names, quick_file_names::real_names, and xfree().
Referenced by create_quick_file_names_table().
static void delete_symtab_entry (void * p) [static]
Definition at line 21515 of file dwarf2read.c.
References VEC_free, and xfree().
Referenced by create_symbol_hash_table().
static const char * determine_prefix (struct die_info * die, struct dwarf2_cu * cu) [static]
Definition at line 18179 of file dwarf2read.c.
References _, anonymous_struct_prefix(), complaint(), die_specification(), dwarf2_name(), guess_full_die_structure_name(), dwarf2_cu::language, language_cplus, language_fortran, language_java, name, read_type_die(), symfile_complaints, TYPE_TAG_NAME, and VEC_empty.
Referenced by dwarf2_compute_name(), read_func_scope(), read_import_statement(), read_namespace(), and read_namespace_type().
static struct type * die_containing_type (struct die_info * die, struct dwarf2_cu * cu) [static, read]
Definition at line 17852 of file dwarf2read.c.
References _, dwarf2_attr(), error(), lookup_die_type(), dwarf2_cu::objfile, and objfile_name().
Referenced by dwarf2_add_member_fn(), process_structure_scope(), and read_tag_ptr_to_member_type().
static struct type * die_descriptive_type (struct die_info * die, struct dwarf2_cu * cu) [static, read]
Definition at line 17821 of file dwarf2read.c.
References dwarf2_attr(), and lookup_die_type().
Referenced by set_descriptive_type().
static int die_eq (const void * item_lhs, const void * item_rhs) [static]
Definition at line 7405 of file dwarf2read.c.
Referenced by load_full_comp_unit_reader(), and read_signatured_type_reader().
static hashval_t die_hash (const void * item) [static]
Definition at line 7394 of file dwarf2read.c.
Referenced by load_full_comp_unit_reader(), and read_signatured_type_reader().
static int die_is_declaration (struct die_info * die, struct dwarf2_cu * cu) [static]
Definition at line 16338 of file dwarf2read.c.
References dwarf2_attr(), and dwarf2_flag_true_p().
Referenced by dwarf2_add_field(), new_symbol_full(), process_enumeration_scope(), process_structure_scope(), read_call_site_scope(), read_enumeration_type(), and read_structure_type().
static int die_needs_namespace (struct die_info * die, struct dwarf2_cu * cu) [static]
Definition at line 8043 of file dwarf2read.c.
References die_specification(), and dwarf2_attr().
Referenced by dwarf2_compute_name(), and dwarf2_physname().
static struct die_info * die_specification (struct die_info * die, struct dwarf2_cu ** spec_cu) [static, read]
Definition at line 16358 of file dwarf2read.c.
References dwarf2_attr(), and follow_die_ref().
Referenced by determine_prefix(), die_needs_namespace(), dwarf2_name(), guess_full_die_structure_name(), and read_func_scope().
static struct type * die_type (struct die_info * die, struct dwarf2_cu * cu) [static, read]
Definition at line 17784 of file dwarf2read.c.
References objfile_type::builtin_void, dwarf2_attr(), lookup_die_type(), dwarf2_cu::objfile, and objfile_type().
Referenced by dwarf2_add_field(), dwarf2_compute_name(), dwarf2_fetch_constant_bytes(), new_symbol_full(), read_array_type(), read_set_type(), read_subrange_type(), read_subroutine_type(), read_tag_const_type(), read_tag_pointer_type(), read_tag_ptr_to_member_type(), read_tag_reference_type(), read_tag_restrict_type(), read_tag_volatile_type(), and read_typedef().
static void do_ui_file_peek_last (void * object, const char * buffer, long length) [static]
Definition at line 8098 of file dwarf2read.c.
Referenced by dwarf2_compute_name().
void dump_die (struct die_info * die, int max_level)
Definition at line 18765 of file dwarf2read.c.
References dump_die_1(), and gdb_stdlog.
Referenced by read_cutu_die_from_dwo(), read_die_and_siblings(), and read_full_die().
static void dump_die_1 (struct ui_file * f, int level, int max_level, struct die_info * die) [static]
Definition at line 18728 of file dwarf2read.c.
References dump_die_shallow(), fprintf_unfiltered(), gdb_assert, and print_spaces().
Referenced by dump_die().
static void dump_die_for_error (struct die_info * die) [static]
Definition at line 18722 of file dwarf2read.c.
References dump_die_shallow(), and gdb_stderr.
Referenced by follow_die_ref_or_sig(), and follow_die_sig().
static void dump_die_shallow (struct ui_file * f, int indent, struct die_info * die) [static]
Definition at line 18608 of file dwarf2read.c.
References DW_ADDR, DW_BLOCK, DW_SIGNATURE, DW_STRING, DW_STRING_IS_CANONICAL, DW_UNSND, dwarf_attr_name(), dwarf_bool_name(), dwarf_form_name(), dwarf_tag_name(), fprintf_unfiltered(), fputs_filtered(), hex_string(), print_spaces(), and pulongest().
Referenced by dump_die_1(), and dump_die_for_error().
static void dw2_do_instantiate_symtab (struct dwarf2_per_cu_data * per_cu) [static]
Definition at line 2581 of file dwarf2read.c.
References age_cached_comp_units(), dwarf2_per_cu_data::cu, do_cleanups(), dwarf2_release_queue(), get_dwp_file(), dwarf2_per_objfile::index_table, dwarf2_per_cu_data::is_debug_types, IS_TYPE_UNIT_GROUP, language_minimal, load_cu(), make_cleanup(), process_queue(), dwarf2_per_cu_data::psymtab, queue_and_load_all_dwo_tus(), queue_comp_unit(), dwarf2_per_cu_data::quick, partial_symtab::readin, dwarf2_per_cu_quick_data::symtab, dwarf2_per_objfile::using_index, dwarf2_per_cu_data::v, and mapped_index::version.
Referenced by dw2_instantiate_symtab(), and psymtab_to_symtab_1().
static void dw2_dump (struct objfile * objfile) [static]
Definition at line 3632 of file dwarf2read.c.
References dw2_setup(), gdb_assert, dwarf2_per_objfile::index_table, printf_filtered(), dwarf2_per_objfile::using_index, and mapped_index::version.
static void dw2_expand_all_symtabs (struct objfile * objfile) [static]
Definition at line 3681 of file dwarf2read.c.
References dw2_get_cu(), dw2_instantiate_symtab(), and dw2_setup().
static void dw2_expand_symtabs_for_function (struct objfile * objfile, const char * func_name) [static]
Definition at line 3656 of file dwarf2read.c.
References dw2_instantiate_symtab(), dw2_setup(), dw2_symtab_iter_init(), dw2_symtab_iter_next(), GLOBAL_BLOCK, dwarf2_per_objfile::index_table, and VAR_DOMAIN.
static void dw2_expand_symtabs_matching (struct objfile * objfile, int(*)(const char *, void *, int basenames) file_matcher, int(*)(const char *, void *) name_matcher, enum search_domain kind, void * data) [static]
Definition at line 3752 of file dwarf2read.c.
References _, basenames_may_differ, complaint(), mapped_index::constant_pool, do_cleanups(), dw2_get_cu(), dw2_get_file_names(), dw2_get_primary_cu(), dw2_get_real_path(), dw2_instantiate_symtab(), dw2_setup(), quick_file_names::file_names, FUNCTIONS_DOMAIN, dwarf2_per_objfile::index_table, make_cleanup_htab_delete(), dwarf2_per_cu_quick_data::mark, MAYBE_SWAP, name, quick_file_names::num_file_names, objfile_name(), dwarf2_per_cu_data::quick, symbol_kind(), mapped_index::symbol_table, mapped_index::symbol_table_slots, symfile_complaints, dwarf2_per_cu_quick_data::symtab, TYPES_DOMAIN, dwarf2_per_cu_data::v, VARIABLES_DOMAIN, mapped_index::version, xcalloc(), and xfree().
static void dw2_expand_symtabs_with_fullname (struct objfile * objfile, const char * fullname) [static]
Definition at line 3697 of file dwarf2read.c.
References dw2_get_cu(), dw2_get_file_names(), dw2_instantiate_symtab(), dw2_setup(), quick_file_names::file_names, quick_file_names::num_file_names, dwarf2_per_cu_data::quick, dwarf2_per_cu_quick_data::symtab, and dwarf2_per_cu_data::v.
static struct symtab* dw2_find_last_source_symtab (struct objfile * objfile) [static, read]
Definition at line 3290 of file dwarf2read.c.
References dw2_get_cu(), dw2_instantiate_symtab(), and dw2_setup().
static struct symtab* dw2_find_pc_sect_symtab (struct objfile * objfile, struct minimal_symbol * msymbol, CORE_ADDR pc, struct obj_section * section, int warn_if_readin) [static, read]
Definition at line 3947 of file dwarf2read.c.
References _, addrmap_find(), dw2_instantiate_symtab(), dw2_setup(), gdb_assert, get_objfile_arch(), paddress(), objfile::psymtabs_addrmap, dwarf2_per_cu_data::quick, recursively_find_pc_sect_symtab(), dwarf2_per_cu_quick_data::symtab, dwarf2_per_cu_data::v, and warning().
static void dw2_forget_cached_source_info (struct objfile * objfile) [static]
Definition at line 3321 of file dwarf2read.c.
References dw2_free_cached_file_names(), dw2_setup(), and dwarf2_per_objfile::quick_file_names_table.
static int dw2_free_cached_file_names (void ** slot, void * info) [static]
Definition at line 3302 of file dwarf2read.c.
References quick_file_names::num_file_names, quick_file_names::real_names, and xfree().
Referenced by dw2_forget_cached_source_info().
static struct dwarf2_per_cu_data* dw2_get_cu (int index) [static, read]
Definition at line 2653 of file dwarf2read.c.
References gdb_assert.
Referenced by create_addrmap_from_index(), dw2_expand_all_symtabs(), dw2_expand_symtabs_matching(), dw2_expand_symtabs_with_fullname(), dw2_find_last_source_symtab(), dw2_map_symbol_filenames(), dw2_print_stats(), dw2_symtab_iter_next(), dwarf2_build_psymtabs_hard(), dwarf2_initialize_objfile(), and set_partial_user().
static struct quick_file_names* dw2_get_file_names (struct dwarf2_per_cu_data * this_cu) [static, read]
Definition at line 3252 of file dwarf2read.c.
References dw2_get_file_names_reader(), dwarf2_per_cu_quick_data::file_names, gdb_assert, init_cutu_and_read_dies_simple(), dwarf2_per_cu_data::is_debug_types, IS_TYPE_UNIT_GROUP, dwarf2_per_cu_quick_data::no_file_data, dwarf2_per_cu_data::quick, and dwarf2_per_cu_data::v.
Referenced by dw2_expand_symtabs_matching(), dw2_expand_symtabs_with_fullname(), dw2_map_symbol_filenames(), and dw2_map_symtabs_matching_filename().
static void dw2_get_file_names_reader (const struct die_reader_specs * reader, const gdb_byte * info_ptr, struct die_info * comp_unit_die, int has_children, void * data) [static]
Definition at line 3168 of file dwarf2read.c.
References die_reader_specs::cu, DW_UNSND, dwarf2_attr(), dwarf_decode_line_header(), stmt_list_hash::dwo_unit, file_full_name(), quick_file_names::file_names, dwarf2_per_cu_quick_data::file_names, find_file_and_directory(), free_line_header(), gdb_assert, quick_file_names::hash, dwarf2_per_cu_data::is_debug_types, stmt_list_hash::line_offset, name, dwarf2_per_cu_quick_data::no_file_data, line_header::num_file_names, quick_file_names::num_file_names, objfile::objfile_obstack, dwarf2_cu::per_cu, dwarf2_per_cu_data::quick, dwarf2_per_objfile::quick_file_names_table, quick_file_names::real_names, sect_offset::sect_off, and dwarf2_per_cu_data::v.
Referenced by dw2_get_file_names().
static struct dwarf2_per_cu_data* dw2_get_primary_cu (int index) [static, read]
Definition at line 2681 of file dwarf2read.c.
References gdb_assert.
Referenced by dw2_expand_symtabs_matching(), dw2_map_symbol_filenames(), and dw2_map_symtabs_matching_filename().
static const char* dw2_get_real_path (struct objfile * objfile, struct quick_file_names * qfn, int index) [static]
Definition at line 3276 of file dwarf2read.c.
References quick_file_names::file_names, gdb_realpath(), quick_file_names::num_file_names, objfile::objfile_obstack, OBSTACK_CALLOC, and quick_file_names::real_names.
Referenced by dw2_expand_symtabs_matching(), dw2_map_symbol_filenames(), and dw2_map_symtabs_matching_filename().
static int dw2_has_symbols (struct objfile * objfile) [static]
Definition at line 4042 of file dwarf2read.c.
static struct symtab* dw2_instantiate_symtab (struct dwarf2_per_cu_data * per_cu) [static, read]
Definition at line 2625 of file dwarf2read.c.
References do_cleanups(), dw2_do_instantiate_symtab(), free_cached_comp_units(), gdb_assert, increment_reading_symtab(), make_cleanup(), process_cu_includes(), dwarf2_per_cu_data::quick, dwarf2_per_cu_quick_data::symtab, dwarf2_per_objfile::using_index, and dwarf2_per_cu_data::v.
Referenced by dw2_expand_all_symtabs(), dw2_expand_symtabs_for_function(), dw2_expand_symtabs_matching(), dw2_expand_symtabs_with_fullname(), dw2_find_last_source_symtab(), dw2_find_pc_sect_symtab(), dw2_lookup_symbol(), and dw2_map_expand_apply().
static struct symtab* dw2_lookup_symbol (struct objfile * objfile, int block_index, const char * name, domain_enum domain) [static, read]
Definition at line 3558 of file dwarf2read.c.
References BLOCKVECTOR, BLOCKVECTOR_BLOCK, dw2_instantiate_symtab(), dw2_setup(), dw2_symtab_iter_init(), dw2_symtab_iter_next(), dwarf2_per_objfile::index_table, lookup_block_symbol(), symtab::primary, strcmp_iw(), SYMBOL_SEARCH_NAME, SYMBOL_TYPE, and TYPE_IS_OPAQUE.
static int dw2_map_expand_apply (struct objfile * objfile, struct dwarf2_per_cu_data * per_cu, const char * name, const char * real_path, int(*)(struct symtab *, void *) callback, void * data) [static]
Definition at line 3333 of file dwarf2read.c.
References dw2_instantiate_symtab(), iterate_over_some_symtabs(), dwarf2_per_cu_data::quick, dwarf2_per_cu_quick_data::symtab, objfile::symtabs, and dwarf2_per_cu_data::v.
Referenced by dw2_map_symtabs_matching_filename().
static void dw2_map_matching_symbols (struct objfile * objfile, const char * name, domain_enum namespace, int global, int(*)(struct block *, struct symbol *, void *) callback, void * data, symbol_compare_ftype * match, symbol_compare_ftype * ordered_compare) [static]
Definition at line 3737 of file dwarf2read.c.
static void dw2_map_symbol_filenames (struct objfile * objfile, symbol_filename_ftype * fun, void * data, int need_fullname) [static]
Definition at line 3975 of file dwarf2read.c.
References do_cleanups(), dw2_get_cu(), dw2_get_file_names(), dw2_get_primary_cu(), dw2_get_real_path(), dw2_setup(), quick_file_names::file_names, dwarf2_per_cu_quick_data::file_names, make_cleanup_htab_delete(), quick_file_names::num_file_names, dwarf2_per_cu_data::quick, dwarf2_per_cu_quick_data::symtab, dwarf2_per_cu_data::v, xcalloc(), and xfree().
static int dw2_map_symtabs_matching_filename (struct objfile * objfile, const char * name, const char * real_path, int(*)(struct symtab *, void *) callback, void * data) [static]
Definition at line 3356 of file dwarf2read.c.
References basenames_may_differ, compare_filenames_for_search(), dw2_get_file_names(), dw2_get_primary_cu(), dw2_get_real_path(), dw2_map_expand_apply(), dw2_setup(), quick_file_names::file_names, gdb_assert, quick_file_names::num_file_names, dwarf2_per_cu_data::quick, dwarf2_per_cu_quick_data::symtab, and dwarf2_per_cu_data::v.
static void dw2_print_stats (struct objfile * objfile) [static]
Definition at line 3608 of file dwarf2read.c.
References _, dw2_get_cu(), dw2_setup(), printf_filtered(), dwarf2_per_cu_data::quick, dwarf2_per_cu_quick_data::symtab, and dwarf2_per_cu_data::v.
static void dw2_relocate (struct objfile * objfile, const struct section_offsets * new_offsets, const struct section_offsets * delta) [static]
Definition at line 3648 of file dwarf2read.c.
static void dw2_setup (struct objfile * objfile) [static]
Definition at line 3159 of file dwarf2read.c.
References dwarf2_objfile_data_key, and gdb_assert.
Referenced by dw2_dump(), dw2_expand_all_symtabs(), dw2_expand_symtabs_for_function(), dw2_expand_symtabs_matching(), dw2_expand_symtabs_with_fullname(), dw2_find_last_source_symtab(), dw2_find_pc_sect_symtab(), dw2_forget_cached_source_info(), dw2_lookup_symbol(), dw2_map_symbol_filenames(), dw2_map_symtabs_matching_filename(), dw2_print_stats(), dwarf2_fetch_constant_bytes(), dwarf2_fetch_die_loc_sect_off(), dwarf2_get_die_type(), and dwarf2_read_addr_index().
static void dw2_symtab_iter_init (struct dw2_symtab_iterator * iter, struct mapped_index * index, int want_specific_block, int block_index, domain_enum domain, const char * name) [static]
Definition at line 3457 of file dwarf2read.c.
References dw2_symtab_iterator::block_index, dw2_symtab_iterator::domain, find_slot_in_mapped_hash(), dw2_symtab_iterator::index, dw2_symtab_iterator::length, MAYBE_SWAP, dw2_symtab_iterator::next, dw2_symtab_iterator::vec, and dw2_symtab_iterator::want_specific_block.
Referenced by dw2_expand_symtabs_for_function(), and dw2_lookup_symbol().
static struct dwarf2_per_cu_data* dw2_symtab_iter_next (struct dw2_symtab_iterator * iter) [static, read]
Definition at line 3482 of file dwarf2read.c.
References _, dw2_symtab_iterator::block_index, complaint(), dw2_symtab_iterator::domain, dw2_get_cu(), GLOBAL_BLOCK, dw2_symtab_iterator::index, LABEL_DOMAIN, dw2_symtab_iterator::length, MAYBE_SWAP, dw2_symtab_iterator::next, objfile_name(), dwarf2_per_cu_data::quick, STRUCT_DOMAIN, symbol_kind(), symfile_complaints, dwarf2_per_cu_quick_data::symtab, dwarf2_per_cu_data::v, VAR_DOMAIN, dw2_symtab_iterator::vec, mapped_index::version, and dw2_symtab_iterator::want_specific_block.
Referenced by dw2_expand_symtabs_for_function(), and dw2_lookup_symbol().
static void dwarf2_add_dependence (struct dwarf2_cu * cu, struct dwarf2_per_cu_data * ref_per_cu) [static]
Definition at line 21262 of file dwarf2read.c.
References dwarf2_cu::comp_unit_obstack, dwarf2_cu::dependencies, dummy_obstack_deallocate(), and hashtab_obstack_allocate().
Referenced by maybe_queue_comp_unit().
static void dwarf2_add_field (struct field_info * fip, struct die_info * die, struct dwarf2_cu * cu) [static]
Definition at line 11940 of file dwarf2read.c.
References field_info::baseclasses, bits_per_byte, die_is_declaration(), die_type(), DW_UNSND, dwarf2_attr(), dwarf2_default_access_attribute(), dwarf2_flag_true_p(), dwarf2_name(), dwarf2_physname(), FIELD_ARTIFICIAL, FIELD_BITPOS, FIELD_BITSIZE, FIELD_NAME, FIELD_TYPE, field_info::fields, gdbarch_bits_big_endian(), get_objfile_arch(), handle_data_member_location(), LONGEST, make_cleanup(), memset(), field_info::nbaseclasses, new_symbol(), field_info::nextfield::next, field_info::nfields, field_info::non_public_fields, dwarf2_cu::objfile, offset, SET_FIELD_BITPOS, SET_FIELD_PHYSNAME, TYPE_LENGTH, type_name_no_tag(), xfree(), and xmalloc().
Referenced by process_structure_scope().
static void dwarf2_add_member_fn (struct field_info * fip, struct die_info * die, struct type * type, struct dwarf2_cu * cu) [static]
Definition at line 12290 of file dwarf2read.c.
References _, add_to_method_list(), comp_unit_head::addr_size, alloc_type(), ALLOCATE_CPLUS_STRUCT_TYPE, attr_form_is_block(), attr_form_is_section_offset(), complaint(), dwarf_block::data, decode_locdesc(), die_containing_type(), DW_BLOCK, DW_FIELD_ALLOC_CHUNK, DW_UNSND, dwarf2_attr(), dwarf2_complex_location_expr_complaint(), dwarf2_default_access_attribute(), dwarf2_full_name(), dwarf2_invalid_attrib_class_complaint(), dwarf2_is_constructor(), dwarf2_name(), dwarf2_physname(), error(), field_info::fnfieldlists, free_current_contents(), dwarf2_cu::header, dwarf2_cu::language, language_ada, language_cplus, language_java, type::length, make_cleanup(), memset(), field_info::fnfieldlist::name, field_info::nfnfields, dwarf2_cu::objfile, offset, read_type_die(), size, dwarf_block::size, smash_to_method_type(), symfile_complaints, TYPE_CODE, TYPE_CODE_FUNC, TYPE_CPLUS_DYNAMIC, TYPE_FIELD_ARTIFICIAL, TYPE_FIELD_TYPE, TYPE_FIELDS, TYPE_NFIELDS, TYPE_TARGET_TYPE, TYPE_VARARGS, VOFFSET_STATIC, xfree(), xmalloc(), and xrealloc().
Referenced by process_structure_scope().
static void dwarf2_add_typedef (struct field_info * fip, struct die_info * die, struct dwarf2_cu * cu) [static]
Definition at line 12127 of file dwarf2read.c.
References dwarf2_name(), gdb_assert, make_cleanup(), dwarf2_cu::objfile, read_type_die(), field_info::typedef_field_list, field_info::typedef_field_list_count, xfree(), and xzalloc().
Referenced by process_structure_scope().
static void dwarf2_attach_fields_to_type (struct field_info * fip, struct type * type, struct dwarf2_cu * cu) [static]
Definition at line 12159 of file dwarf2read.c.
References _, ALLOCATE_CPLUS_STRUCT_TYPE, B_BYTES, B_CLRALL, B_TYPE, field_info::baseclasses, complaint(), error(), field_info::fields, dwarf2_cu::language, language_ada, memset(), field_info::nbaseclasses, field_info::nextfield::next, field_info::nfields, field_info::non_public_fields, SET_TYPE_FIELD_PRIVATE, SET_TYPE_FIELD_PROTECTED, SET_TYPE_FIELD_VIRTUAL, symfile_complaints, TYPE_ALLOC, TYPE_FIELD, TYPE_FIELD_IGNORE_BITS, TYPE_FIELD_PRIVATE_BITS, TYPE_FIELD_PROTECTED_BITS, TYPE_FIELD_VIRTUAL_BITS, TYPE_FIELDS, TYPE_N_BASECLASSES, and TYPE_NFIELDS.
Referenced by process_structure_scope().
static void dwarf2_attach_fn_fields_to_type (struct field_info * fip, struct type * type, struct dwarf2_cu * cu) [static]
Definition at line 12490 of file dwarf2read.c.
References _, ALLOCATE_CPLUS_STRUCT_TYPE, error(), field_info::fnfieldlists, dwarf2_cu::language, language_ada, type::length, field_info::nfnfields, TYPE_ALLOC, TYPE_FN_FIELDLIST, TYPE_FN_FIELDLIST_LENGTH, TYPE_FN_FIELDLIST_NAME, TYPE_FN_FIELDLISTS, and TYPE_NFN_FIELDS.
Referenced by process_structure_scope().
static struct attribute * dwarf2_attr (struct die_info * die, unsigned int name, struct dwarf2_cu * cu) [static, read]
Definition at line 16282 of file dwarf2read.c.
References follow_die_ref().
Referenced by anonymous_struct_prefix(), create_dwo_cu_reader(), die_containing_type(), die_descriptive_type(), die_is_declaration(), die_needs_namespace(), die_specification(), die_type(), dw2_get_file_names_reader(), dwarf2_add_field(), dwarf2_add_member_fn(), dwarf2_build_include_psymtabs(), dwarf2_compute_name(), dwarf2_extension(), dwarf2_fetch_constant_bytes(), dwarf2_fetch_die_loc_sect_off(), dwarf2_find_base_address(), dwarf2_flag_true_p(), dwarf2_get_pc_bounds(), dwarf2_name(), dwarf2_physname(), dwarf2_record_block_ranges(), find_file_and_directory(), guess_full_die_structure_name(), handle_data_member_location(), handle_DW_AT_stmt_list(), inherit_abstract_dies(), init_cutu_and_read_dies(), lookup_dwo_unit(), new_symbol_full(), prepare_one_comp_unit(), process_imported_unit_die(), process_psymtab_comp_unit_reader(), process_structure_scope(), prototyped_function_p(), read_array_order(), read_array_type(), read_base_type(), read_call_site_scope(), read_common_block(), read_cutu_die_from_dwo(), read_enumeration_type(), read_file_scope(), read_func_scope(), read_import_statement(), read_namespace(), read_namespace_type(), read_set_type(), read_structure_type(), read_subrange_type(), read_subroutine_type(), read_tag_pointer_type(), read_tag_reference_type(), read_tag_string_type(), and setup_type_unit_groups().
static struct attribute * dwarf2_attr_no_follow (struct die_info * die, unsigned int name) [static, read]
Definition at line 16314 of file dwarf2read.c.
Referenced by build_type_psymtabs_reader(), read_enumeration_type(), and read_structure_type().
static void dwarf2_build_include_psymtabs (struct dwarf2_cu * cu, struct die_info * die, struct partial_symtab * pst) [static]
Definition at line 4395 of file dwarf2read.c.
References partial_symtab::dirname, DW_UNSND, dwarf2_attr(), dwarf_decode_line_header(), dwarf_decode_lines(), and free_line_header().
Referenced by process_psymtab_comp_unit_reader().
void dwarf2_build_psymtabs (struct objfile * objfile)
Definition at line 4112 of file dwarf2read.c.
References discard_cleanups(), dwarf2_build_psymtabs_hard(), exception_print(), gdb_stderr, objfile::global_psymbols, init_psymbol_list(), make_cleanup_discard_psymtabs(), gdb_exception::reason, RETURN_MASK_ERROR, psymbol_allocation_list::size, objfile::static_psymbols, and TRY_CATCH.
Referenced by coff_symfile_read(), macho_symfile_read(), read_psyms(), and xcoff_initial_scan().
static void dwarf2_build_psymtabs_hard (struct objfile * objfile) [static]
Definition at line 6226 of file dwarf2read.c.
References addrmap_create_fixed(), addrmap_create_mutable(), build_type_psymtabs(), create_all_comp_units(), discard_cleanups(), do_cleanups(), dw2_get_cu(), dwarf2_read_debug, dwarf2_read_section(), fprintf_unfiltered(), free_cached_comp_units(), gdb_stdlog, dwarf2_per_objfile::info, language_minimal, make_cleanup(), make_cleanup_obstack_free(), objfile_name(), objfile::objfile_obstack, process_psymtab_comp_unit(), objfile::psymtabs_addrmap, psymtabs_addrmap_cleanup(), dwarf2_per_objfile::reading_partial_symbols, and set_partial_user().
Referenced by dwarf2_build_psymtabs().
static const char * dwarf2_canonicalize_name (const char * name, struct dwarf2_cu * cu, struct obstack * obstack) [static]
Definition at line 18379 of file dwarf2read.c.
References cp_canonicalize_string(), dwarf2_cu::language, language_cplus, name, and xfree().
Referenced by dwarf2_compute_name(), dwarf2_name(), and read_partial_die().
static void dwarf2_clear_marks (struct dwarf2_per_cu_data * per_cu) [static]
Definition at line 21320 of file dwarf2read.c.
References dwarf2_per_cu_data::cu, and dwarf2_cu::read_in_chain.
Referenced by age_cached_comp_units().
static void dwarf2_complex_location_expr_complaint (void) [static]
Definition at line 1877 of file dwarf2read.c.
References _, complaint(), and symfile_complaints.
Referenced by decode_locdesc(), dwarf2_add_member_fn(), handle_data_member_location(), read_common_block(), and read_partial_die().
static const char* dwarf2_compute_name (const char * name, struct die_info * die, struct dwarf2_cu * cu, int physname) [static]
Definition at line 8122 of file dwarf2read.c.
References _, allocate_value(), c_print_type(), c_printchar(), c_type_print_args(), dwarf2_cu::comp_unit_obstack, complaint(), dwarf2_locexpr_baton::data, determine_prefix(), die_needs_namespace(), die_type(), do_ui_file_peek_last(), DW_STRING, dwarf2_attr(), dwarf2_canonicalize_name(), dwarf2_const_value_attr(), dwarf2_evaluate_loc_desc(), dwarf2_name(), fputs_unfiltered(), get_formatted_print_options(), java_print_type(), dwarf2_cu::language, language_ada, language_cplus, language_fortran, language_java, LONGEST, mem_fileopen(), memcpy(), name, dwarf2_cu::objfile, objfile::objfile_obstack, dwarf2_locexpr_baton::per_cu, value_print_options::raw, read_type_die(), release_value(), dwarf2_locexpr_baton::size, strchr(), symfile_complaints, type, TYPE_CODE, TYPE_CODE_PTR, TYPE_CONST, TYPE_FIELD_ARTIFICIAL, TYPE_FIELD_TYPE, TYPE_LENGTH, TYPE_NFIELDS, TYPE_NOSIGN, type_print_raw_options, TYPE_TARGET_TYPE, typename_concat(), ui_file_delete(), ui_file_obsavestring(), ui_file_put(), value_contents_writeable(), value_free(), value_from_longest(), value_print(), and xfree().
Referenced by dwarf2_full_name(), and dwarf2_physname().
static void dwarf2_const_value (const struct attribute * attr, struct symbol * sym, struct dwarf2_cu * cu) [static]
Definition at line 17750 of file dwarf2read.c.
References dwarf2_const_value_attr(), dwarf2_locexpr_index, dwarf2_cu::header, LOC_CONST, LOC_CONST_BYTES, LONGEST, dwarf2_cu::objfile, objfile::objfile_obstack, SYMBOL_ACLASS_INDEX, SYMBOL_LOCATION_BATON, SYMBOL_PRINT_NAME, SYMBOL_TYPE, SYMBOL_VALUE, and SYMBOL_VALUE_BYTES.
Referenced by new_symbol_full().
static void dwarf2_const_value_attr (const struct attribute * attr, struct type * type, const char * name, struct obstack * obstack, struct dwarf2_cu * cu, LONGEST * value, const gdb_byte ** bytes, struct dwarf2_locexpr_baton ** baton) [static]
Definition at line 17647 of file dwarf2read.c.
References _, comp_unit_head::addr_size, complaint(), dwarf_block::data, DW_ADDR, DW_BLOCK, DW_SND, DW_STRING, DW_UNSND, dwarf2_const_value_data(), dwarf2_const_value_length_mismatch_complaint(), dwarf_form_name(), gdb_assert, dwarf2_cu::header, objfile::obfd, dwarf2_cu::objfile, dwarf2_cu::per_cu, dwarf_block::size, store_unsigned_integer(), symfile_complaints, and TYPE_LENGTH.
Referenced by dwarf2_compute_name(), and dwarf2_const_value().
static gdb_byte* dwarf2_const_value_data (const struct attribute * attr, struct obstack * obstack, struct dwarf2_cu * cu, LONGEST * value, int bits) [static]
Definition at line 17615 of file dwarf2read.c.
References DW_UNSND, LONGEST, objfile::obfd, dwarf2_cu::objfile, and store_unsigned_integer().
Referenced by dwarf2_const_value_attr(), and dwarf2_fetch_constant_bytes().
static void dwarf2_const_value_length_mismatch_complaint (const char * arg1, int arg2, int arg3) [static]
Definition at line 1883 of file dwarf2read.c.
References _, complaint(), and symfile_complaints.
Referenced by dwarf2_const_value_attr().
static void dwarf2_create_include_psymtab (const char * name, struct partial_symtab * pst, struct objfile * objfile) [static]
Definition at line 4355 of file dwarf2read.c.
References allocate_psymtab(), partial_symtab::dependencies, partial_symtab::dirname, partial_symtab::filename, partial_symtab::globals_offset, partial_symtab::n_global_syms, partial_symtab::n_static_syms, partial_symtab::number_of_dependencies, objfile::objfile_obstack, partial_symtab::read_symtab, partial_symtab::read_symtab_private, partial_symtab::readin, partial_symtab::section_offsets, partial_symtab::statics_offset, partial_symtab::symtab, partial_symtab::texthigh, and partial_symtab::textlow.
Referenced by dwarf_decode_lines().
static void dwarf2_debug_line_missing_end_sequence_complaint (void) [static]
Definition at line 1869 of file dwarf2read.c.
References _, complaint(), and symfile_complaints.
Referenced by dwarf_decode_lines_1().
static void dwarf2_debug_line_missing_file_complaint (void) [static]
Definition at line 1862 of file dwarf2read.c.
References _, complaint(), and symfile_complaints.
Referenced by dwarf_decode_lines_1().
static enum dwarf_access_attribute dwarf2_default_access_attribute (struct die_info * die, struct dwarf2_cu * cu) [static]
Definition at line 11877 of file dwarf2read.c.
References dwarf2_cu::header, producer_is_gxx_lt_4_6(), and comp_unit_head::version.
Referenced by dwarf2_add_field(), and dwarf2_add_member_fn().
static struct die_info * dwarf2_extension (struct die_info * die, struct dwarf2_cu ** ext_cu) [static, read]
Definition at line 18525 of file dwarf2read.c.
References dwarf2_attr(), and follow_die_ref().
Referenced by namespace_name(), and read_namespace_type().
const gdb_byte* dwarf2_fetch_constant_bytes (sect_offset offset, struct dwarf2_per_cu_data * per_cu, struct obstack * obstack, LONGEST * len)
Definition at line 19024 of file dwarf2read.c.
References _, comp_unit_head::addr_size, complaint(), dwarf2_per_cu_data::cu, die_type(), dw2_setup(), DW_ADDR, DW_BLOCK, DW_SND, DW_STRING, DW_UNSND, dwarf2_attr(), dwarf2_const_value_data(), dwarf_form_name(), error(), follow_die_offset(), dwarf2_cu::header, dwarf2_per_cu_data::is_dwz, load_cu(), LONGEST, objfile::obfd, dwarf2_per_cu_data::objfile, objfile_name(), sect_offset::sect_off, store_unsigned_integer(), symfile_complaints, type, and write_constant_as_bytes().
Referenced by indirect_pieced_value().
struct dwarf2_locexpr_baton dwarf2_fetch_die_loc_cu_off (cu_offset offset_in_cu, struct dwarf2_per_cu_data * per_cu, CORE_ADDR(*)(void *baton) get_frame_pc, void * baton) [read]
Definition at line 18989 of file dwarf2read.c.
References dwarf2_fetch_die_loc_sect_off(), get_frame_pc(), and offset.
Referenced by dwarf2_compile_expr_to_ax(), and per_cu_dwarf_call().
struct dwarf2_locexpr_baton dwarf2_fetch_die_loc_sect_off (sect_offset offset, struct dwarf2_per_cu_data * per_cu, CORE_ADDR(*)(void *baton) get_frame_pc, void * baton) [read]
Definition at line 18926 of file dwarf2read.c.
References _, age_cached_comp_units(), attr_form_is_block(), attr_form_is_section_offset(), dwarf2_locexpr_baton::data, dw2_setup(), DW_BLOCK, dwarf2_attr(), dwarf2_find_location_expression(), error(), fill_in_loclist_baton(), follow_die_offset(), load_cu(), objfile_name(), dwarf2_locexpr_baton::per_cu, dwarf2_cu::per_cu, dwarf2_locexpr_baton::size, and size.
Referenced by dwarf2_fetch_die_loc_cu_off(), and indirect_pieced_value().
static void dwarf2_find_base_address (struct die_info * die, struct dwarf2_cu * cu) [static]
Definition at line 4161 of file dwarf2read.c.
References dwarf2_cu::base_address, dwarf2_cu::base_known, DW_ADDR, and dwarf2_attr().
Referenced by load_cu(), and process_psymtab_comp_unit_reader().
static struct dwarf2_per_cu_data * dwarf2_find_containing_comp_unit (sect_offset offset, unsigned int offset_in_dwz, struct objfile * objfile) [static, read]
Definition at line 20894 of file dwarf2read.c.
References _, error(), gdb_assert, dwarf2_per_cu_data::is_dwz, dwarf2_per_cu_data::length, objfile::obfd, dwarf2_per_cu_data::offset, and sect_offset::sect_off.
Referenced by find_partial_die(), follow_die_offset(), lookup_die_type(), process_imported_unit_die(), and scan_partial_symbols().
static int dwarf2_flag_true_p (struct die_info * die, unsigned name, struct dwarf2_cu * cu) [static]
Definition at line 16330 of file dwarf2read.c.
References DW_UNSND, and dwarf2_attr().
Referenced by die_is_declaration(), dwarf2_add_field(), and read_call_site_scope().
static void dwarf2_free_abbrev_table (void * ptr_to_cu) [static]
Definition at line 14696 of file dwarf2read.c.
References dwarf2_cu::abbrev_table, and abbrev_table_free().
Referenced by init_cutu_and_read_dies(), init_cutu_and_read_dies_no_follow(), init_tu_and_read_dwo_dies(), and read_cutu_die_from_dwo().
void dwarf2_free_objfile (struct objfile * objfile)
Definition at line 21107 of file dwarf2read.c.
References dwarf2_objfile_data_key, free_cached_comp_units(), and dwarf2_per_objfile::quick_file_names_table.
Referenced by coff_symfile_finish(), elf_symfile_finish(), and xcoff_symfile_finish().
static const char * dwarf2_full_name (const char * name, struct die_info * die, struct dwarf2_cu * cu) [static]
Definition at line 8364 of file dwarf2read.c.
References dwarf2_compute_name().
Referenced by dwarf2_add_member_fn(), new_symbol_full(), partial_die_full_name(), read_enumeration_type(), read_structure_type(), and read_typedef().
static LONGEST dwarf2_get_attr_constant_value (const struct attribute * attr, int default_value) [static]
Definition at line 18803 of file dwarf2read.c.
References _, complaint(), DW_SND, DW_UNSND, dwarf_form_name(), and symfile_complaints.
Referenced by handle_data_member_location(), mark_common_block_symbol_computed(), and read_subrange_type().
struct type* dwarf2_get_die_type (cu_offset die_offset, struct dwarf2_per_cu_data * per_cu) [read]
Definition at line 19147 of file dwarf2read.c.
References cu_offset::cu_off, dw2_setup(), get_die_type_at_offset(), dwarf2_per_cu_data::objfile, dwarf2_per_cu_data::offset, and sect_offset::sect_off.
Referenced by disassemble_dwarf_expression(), and dwarf_expr_get_base_type().
static struct dwz_file* dwarf2_get_dwz_file (void) [static, read]
Definition at line 2361 of file dwarf2read.c.
References _, build_id_to_debug_bfd(), build_id_verify(), do_cleanups(), dwz_file::dwz_bfd, dwarf2_per_objfile::dwz_file, error(), gdb_bfd_open(), gdb_bfd_unref(), gdb_realpath(), gnutarget, ldirname(), locate_dwz_sections(), make_cleanup(), objfile_name(), OBSTACK_ZALLOC, and xfree().
Referenced by create_all_comp_units(), create_cus_from_index(), dwarf2_read_index(), dwarf_decode_macro_bytes(), get_abbrev_section_for_cu(), get_debug_line_section(), and read_attribute_value().
static int dwarf2_get_pc_bounds (struct die_info * die, CORE_ADDR * lowpc, CORE_ADDR * highpc, struct dwarf2_cu * cu, struct partial_symtab * pst) [static]
Definition at line 11507 of file dwarf2read.c.
References DW_ADDR, DW_UNSND, dwarf2_attr(), dwarf2_ranges_read(), and dwarf2_per_objfile::has_section_at_zero.
Referenced by dwarf2_get_subprogram_pc_bounds(), get_scope_pc_bounds(), process_psymtab_comp_unit_reader(), read_call_site_scope(), read_func_scope(), and read_lexical_block_scope().
static sect_offset dwarf2_get_ref_die_offset (const struct attribute * attr) [static]
Definition at line 18785 of file dwarf2read.c.
References _, attr_form_is_ref(), complaint(), DW_UNSND, dwarf_form_name(), sect_offset::sect_off, and symfile_complaints.
Referenced by follow_die_ref(), lookup_die_type(), process_imported_unit_die(), read_call_site_scope(), read_partial_die(), and skip_one_die().
void dwarf2_get_section_info (struct objfile * objfile, enum dwarf2_section_enum sect, asection ** sectp, const gdb_byte ** bufp, bfd_size_type * sizep)
Definition at line 2278 of file dwarf2read.c.
References dwarf2_section_info::buffer, DWARF2_DEBUG_FRAME, DWARF2_EH_FRAME, dwarf2_objfile_data_key, dwarf2_read_section(), dwarf2_per_objfile::eh_frame, dwarf2_per_objfile::frame, gdb_assert_not_reached, get_section_bfd_section(), and dwarf2_section_info::size.
Referenced by dwarf2_build_frame_info().
static void dwarf2_get_subprogram_pc_bounds (struct die_info * die, CORE_ADDR * lowpc, CORE_ADDR * highpc, struct dwarf2_cu * cu) [static]
Definition at line 11587 of file dwarf2read.c.
References dwarf2_get_pc_bounds(), dwarf2_cu::language, language_ada, max, min, and sibling_die().
Referenced by get_scope_pc_bounds().
int dwarf2_has_info (struct objfile * objfile, const struct dwarf2_debug_sections * names)
Definition at line 1948 of file dwarf2read.c.
References dwarf2_per_objfile::abbrev, dwarf2_section_info::asection, dwarf2_locate_sections(), dwarf2_objfile_data_key, dwarf2_per_objfile::info, dwarf2_section_info::is_virtual, memset(), objfile::obfd, objfile::objfile_obstack, and dwarf2_section_info::s.
Referenced by coff_symfile_read(), elf_symfile_read(), macho_symfile_read(), read_psyms(), and xcoff_initial_scan().
int dwarf2_initialize_objfile (struct objfile * objfile)
Definition at line 4070 of file dwarf2read.c.
References create_all_comp_units(), create_all_type_units(), create_quick_file_names_table(), dw2_get_cu(), dwarf2_read_index(), objfile::flags, OBJF_READNOW, objfile::objfile_obstack, OBSTACK_ZALLOC, dwarf2_per_cu_data::quick, dwarf2_per_objfile::quick_file_names_table, dwarf2_per_objfile::using_index, and dwarf2_per_cu_data::v.
Referenced by elf_symfile_read().
static void dwarf2_invalid_attrib_class_complaint (const char * arg1, const char * arg2) [static]
Definition at line 1911 of file dwarf2read.c.
References _, complaint(), and symfile_complaints.
Referenced by dwarf2_add_member_fn(), dwarf2_symbol_mark_computed(), read_common_block(), and read_partial_die().
static int dwarf2_is_constructor (struct die_info * die, struct dwarf2_cu * cu) [static]
Definition at line 12263 of file dwarf2read.c.
References dwarf2_name(), and len.
Referenced by dwarf2_add_member_fn().
static void dwarf2_locate_common_dwp_sections (bfd * abfd, asection * sectp, void * dwp_file_ptr) [static]
Definition at line 10192 of file dwarf2read.c.
References dwarf2_section_info::asection, dwop_section_names::cu_index, dwp_sections::cu_index, dwop_section_names, dwp_file::elf_sections, gdb_assert, dwarf2_section_info::s, section_is_p(), dwp_file::sections, dwarf2_section_info::size, dwp_sections::str, dwop_section_names::str_dwo, dwop_section_names::tu_index, and dwp_sections::tu_index.
Referenced by open_and_init_dwp_file().
static void dwarf2_locate_dwo_sections (bfd * abfd, asection * sectp, void * dwo_sections_ptr) [static]
Definition at line 10088 of file dwarf2read.c.
References dwo_sections::abbrev, dwop_section_names::abbrev_dwo, dwarf2_section_info::asection, dwop_section_names, dwo_sections::info, dwop_section_names::info_dwo, dwo_sections::line, dwop_section_names::line_dwo, dwo_sections::loc, dwop_section_names::loc_dwo, dwo_sections::macinfo, dwop_section_names::macinfo_dwo, dwo_sections::macro, dwop_section_names::macro_dwo, memset(), dwarf2_section_info::s, section_is_p(), dwarf2_section_info::size, dwo_sections::str, dwop_section_names::str_dwo, dwo_sections::str_offsets, dwop_section_names::str_offsets_dwo, dwop_section_names::types_dwo, and VEC_safe_push.
Referenced by open_and_init_dwo_file().
static void dwarf2_locate_sections (bfd * abfd, asection * sectp, void * vnames) [static]
Definition at line 2075 of file dwarf2read.c.
References dwarf2_per_objfile::abbrev, dwarf2_debug_sections::abbrev, dwarf2_per_objfile::addr, dwarf2_debug_sections::addr, dwarf2_section_info::asection, dwarf2_elf_names, dwarf2_per_objfile::eh_frame, dwarf2_debug_sections::eh_frame, dwarf2_per_objfile::frame, dwarf2_debug_sections::frame, dwarf2_per_objfile::gdb_index, dwarf2_debug_sections::gdb_index, dwarf2_per_objfile::has_section_at_zero, dwarf2_per_objfile::info, dwarf2_debug_sections::info, dwarf2_per_objfile::line, dwarf2_debug_sections::line, dwarf2_per_objfile::loc, dwarf2_debug_sections::loc, dwarf2_per_objfile::macinfo, dwarf2_debug_sections::macinfo, dwarf2_per_objfile::macro, dwarf2_debug_sections::macro, memset(), dwarf2_per_objfile::ranges, dwarf2_debug_sections::ranges, dwarf2_section_info::s, section_is_p(), dwarf2_section_info::size, dwarf2_per_objfile::str, dwarf2_debug_sections::str, dwarf2_debug_sections::types, and VEC_safe_push.
Referenced by dwarf2_has_info().
static void dwarf2_locate_v2_dwp_sections (bfd * abfd, asection * sectp, void * dwp_file_ptr) [static]
Definition at line 10228 of file dwarf2read.c.
References dwp_sections::abbrev, dwop_section_names::abbrev_dwo, dwarf2_section_info::asection, dwop_section_names, dwp_file::elf_sections, gdb_assert, dwp_sections::info, dwop_section_names::info_dwo, dwp_sections::line, dwop_section_names::line_dwo, dwp_sections::loc, dwop_section_names::loc_dwo, dwp_sections::macinfo, dwop_section_names::macinfo_dwo, dwp_sections::macro, dwop_section_names::macro_dwo, dwarf2_section_info::s, section_is_p(), dwp_file::sections, dwarf2_section_info::size, dwp_sections::str_offsets, dwop_section_names::str_offsets_dwo, dwp_sections::types, and dwop_section_names::types_dwo.
Referenced by open_and_init_dwp_file().
static void dwarf2_macro_malformed_definition_complaint (const char * arg1) [static]
Definition at line 1902 of file dwarf2read.c.
References _, complaint(), and symfile_complaints.
Referenced by parse_macro_definition().
static void dwarf2_mark (struct dwarf2_cu * cu) [static]
Definition at line 21310 of file dwarf2read.c.
References dwarf2_cu::dependencies, and dwarf2_mark_helper().
Referenced by age_cached_comp_units().
static int dwarf2_mark_helper (void ** slot, void * data) [static]
Definition at line 21284 of file dwarf2read.c.
References dwarf2_per_cu_data::cu, and dwarf2_cu::dependencies.
Referenced by dwarf2_mark().
static const char * dwarf2_name (struct die_info * die, struct dwarf2_cu * cu) [static]
Definition at line 18400 of file dwarf2read.c.
References die_specification(), DW_STRING, DW_STRING_IS_CANONICAL, dwarf2_attr(), dwarf2_canonicalize_name(), gdb_demangle(), dwarf2_cu::language, language_java, dwarf2_cu::objfile, objfile::objfile_obstack, strrchr(), and xfree().
Referenced by determine_prefix(), dwarf2_add_field(), dwarf2_add_member_fn(), dwarf2_add_typedef(), dwarf2_compute_name(), dwarf2_is_constructor(), guess_full_die_structure_name(), namespace_name(), new_symbol_full(), process_enumeration_scope(), read_array_type(), read_base_type(), read_func_scope(), read_import_statement(), read_module_type(), read_structure_type(), read_subrange_type(), read_subroutine_type(), and read_unspecified_type().
int dwarf2_per_cu_addr_size (struct dwarf2_per_cu_data * per_cu)
Definition at line 20838 of file dwarf2read.c.
References comp_unit_head::addr_size, and per_cu_header_read_in().
Referenced by dwarf2_evaluate_loc_desc_full(), dwarf2_find_location_expression(), dwarf2_loc_desc_needs_frame(), dwarf_expr_push_dwarf_reg_entry_value(), locexpr_describe_location(), locexpr_tracepoint_var_ref(), loclist_describe_location(), and loclist_tracepoint_var_ref().
struct objfile* dwarf2_per_cu_objfile (struct dwarf2_per_cu_data * per_cu) [read]
Definition at line 20802 of file dwarf2read.c.
References dwarf2_per_cu_data::objfile, and objfile::separate_debug_objfile_backlink.
Referenced by dwarf2_evaluate_loc_desc_full(), dwarf2_find_location_expression(), dwarf2_loc_desc_needs_frame(), dwarf_expr_push_dwarf_reg_entry_value(), dwarf_expr_tls_address(), locexpr_describe_location(), and loclist_describe_location().
int dwarf2_per_cu_offset_size (struct dwarf2_per_cu_data * per_cu)
Definition at line 20851 of file dwarf2read.c.
References comp_unit_head::offset_size, and per_cu_header_read_in().
Referenced by locexpr_describe_location(), and loclist_describe_location().
int dwarf2_per_cu_ref_addr_size (struct dwarf2_per_cu_data * per_cu)
Definition at line 20864 of file dwarf2read.c.
References comp_unit_head::addr_size, comp_unit_head::offset_size, per_cu_header_read_in(), and comp_unit_head::version.
Referenced by dwarf2_evaluate_loc_desc_full(), and dwarf2_loc_desc_needs_frame().
CORE_ADDR dwarf2_per_cu_text_offset (struct dwarf2_per_cu_data * per_cu)
Definition at line 20883 of file dwarf2read.c.
References ANOFFSET, dwarf2_per_cu_data::objfile, SECT_OFF_TEXT, and objfile::section_offsets.
Referenced by dwarf2_compile_expr_to_ax(), dwarf2_evaluate_loc_desc_full(), dwarf2_find_location_expression(), dwarf2_loc_desc_needs_frame(), dwarf_expr_push_dwarf_reg_entry_value(), and loclist_describe_location().
static void dwarf2_per_objfile_free (struct objfile * objfile, void * d) [static]
Definition at line 21370 of file dwarf2read.c.
References dwp_file::dbfd, dwarf2_per_objfile::dwo_files, dwarf2_per_objfile::dwp_file, dwz_file::dwz_bfd, dwarf2_per_objfile::dwz_file, free_dwo_files(), gdb_bfd_unref(), VEC_free, and xfree().
static const char * dwarf2_physname (const char * name, struct die_info * die, struct dwarf2_cu * cu) [static]
Definition at line 8377 of file dwarf2read.c.
References _, check_physname, complaint(), die_needs_namespace(), do_cleanups(), DW_STRING, dwarf2_attr(), dwarf2_compute_name(), gdb_demangle(), dwarf2_cu::language, language_go, language_java, make_cleanup(), mangled, null_cleanup(), dwarf2_cu::objfile, objfile_name(), objfile::objfile_obstack, symfile_complaints, and xfree().
Referenced by compute_delayed_physnames(), dwarf2_add_field(), dwarf2_add_member_fn(), new_symbol_full(), and read_call_site_scope().
static int dwarf2_ranges_read (unsigned offset, CORE_ADDR * low_return, CORE_ADDR * high_return, struct dwarf2_cu * cu, struct partial_symtab * ranges_pst) [static]
Definition at line 11354 of file dwarf2read.c.
References _, comp_unit_head::addr_size, addrmap_set_empty(), ANOFFSET, dwarf2_cu::base_address, dwarf2_cu::base_known, dwarf2_section_info::buffer, complaint(), dummy, dwarf2_read_section(), dwarf2_per_objfile::has_section_at_zero, dwarf2_cu::header, objfile::obfd, dwarf2_cu::objfile, objfile_name(), offset, objfile::psymtabs_addrmap, dwarf2_per_objfile::ranges, read_address(), SECT_OFF_TEXT, objfile::section_offsets, dwarf2_section_info::size, and symfile_complaints.
Referenced by dwarf2_get_pc_bounds().
static void dwarf2_read_abbrevs (struct dwarf2_cu * cu, struct dwarf2_section_info * abbrev_section) [static]
Definition at line 14686 of file dwarf2read.c.
References comp_unit_head::abbrev_offset, dwarf2_cu::abbrev_table, abbrev_table_read_table(), and dwarf2_cu::header.
Referenced by init_cutu_and_read_dies(), init_cutu_and_read_dies_no_follow(), and read_cutu_die_from_dwo().
CORE_ADDR dwarf2_read_addr_index (struct dwarf2_per_cu_data * per_cu, unsigned int addr_index)
Definition at line 16119 of file dwarf2read.c.
References dwarf2_read_addr_index_data::addr_base, comp_unit_head::addr_size, dwarf2_read_addr_index_data::addr_size, dwarf2_per_cu_data::cu, dw2_setup(), dwarf2_read_addr_index_reader(), dwarf2_cu::header, init_cutu_and_read_dies(), dwarf2_per_cu_data::objfile, read_addr_index_1(), and ULONGEST.
Referenced by decode_debug_loc_dwo_addresses(), disassemble_dwarf_expression(), dwarf_expr_get_addr_index(), and locexpr_describe_location_piece().
static void dwarf2_read_addr_index_reader (const struct die_reader_specs * reader, const gdb_byte * info_ptr, struct die_info * comp_unit_die, int has_children, void * data) [static]
Definition at line 16099 of file dwarf2read.c.
References dwarf2_read_addr_index_data::addr_base, comp_unit_head::addr_size, dwarf2_read_addr_index_data::addr_size, die_reader_specs::cu, and dwarf2_cu::header.
Referenced by dwarf2_read_addr_index().
static int dwarf2_read_index (struct objfile * objfile) [static]
Definition at line 3083 of file dwarf2read.c.
References _, create_addrmap_from_index(), create_cus_from_index(), create_quick_file_names_table(), create_signatured_type_table_from_index(), dwarf2_get_dwz_file(), dwz_file::dwz_bfd, dwarf2_per_objfile::gdb_index, dwz_file::gdb_index, dwarf2_per_objfile::index_table, objfile_name(), objfile::objfile_obstack, dwarf2_per_objfile::quick_file_names_table, read_index_from_section(), mapped_index::symbol_table_slots, use_deprecated_index_sections, dwarf2_per_objfile::using_index, VEC_index, VEC_length, and warning().
Referenced by dwarf2_initialize_objfile().
static void dwarf2_read_section (struct objfile * objfile, struct dwarf2_section_info * info) [static]
Definition at line 2183 of file dwarf2read.c.
References _, dwarf2_section_info::asection, dwarf2_section_info::buffer, dwarf2_section_info::containing_section, dwarf2_section_empty_p(), error(), gdb_assert, gdb_bfd_map_section(), get_containing_section(), get_section_bfd_owner(), get_section_bfd_section(), get_section_file_name(), get_section_name(), dwarf2_section_info::is_virtual, objfile::objfile_obstack, dwarf2_section_info::readin, dwarf2_section_info::size, symfile_relocate_debug_section(), and dwarf2_section_info::virtual_offset.
Referenced by abbrev_table_read_table(), create_debug_types_hash_table(), create_dwo_cu(), create_dwp_hash_table(), dwarf2_build_psymtabs_hard(), dwarf2_get_section_info(), dwarf2_ranges_read(), dwarf2_record_block_ranges(), dwarf2_section_size(), dwarf_decode_line_header(), dwarf_decode_macro_bytes(), dwarf_decode_macros(), fill_in_loclist_baton(), init_cutu_and_read_dies(), init_cutu_and_read_dies_no_follow(), read_abbrev_offset(), read_addr_index_1(), read_comp_units_from_section(), read_cutu_die_from_dwo(), read_index_from_section(), read_indirect_string_at_offset(), read_indirect_string_from_dwz(), and read_str_index().
static void dwarf2_read_symtab (struct partial_symtab * self, struct objfile * objfile) [static]
Definition at line 7139 of file dwarf2read.c.
References _, dwarf2_objfile_data_key, gdb_flush(), gdb_stdout, dwarf2_per_objfile::has_section_at_zero, info_verbose, printf_filtered(), process_cu_includes(), psymtab_to_symtab_1(), dwarf2_per_objfile::reading_partial_symbols, objfile::separate_debug_objfile_backlink, and warning().
Referenced by create_partial_symtab().
static void dwarf2_record_block_ranges (struct die_info * die, struct block * block, CORE_ADDR baseaddr, struct dwarf2_cu * cu) [static]
Definition at line 11681 of file dwarf2read.c.
References _, comp_unit_head::addr_size, dwarf2_cu::base_address, dwarf2_cu::base_known, dwarf2_section_info::buffer, complaint(), DW_ADDR, DW_UNSND, dwarf2_attr(), dwarf2_read_section(), dwarf2_per_objfile::has_section_at_zero, dwarf2_cu::header, objfile::obfd, dwarf2_cu::objfile, objfile_name(), offset, dwarf2_per_objfile::ranges, read_address(), record_block_range(), dwarf2_section_info::size, and symfile_complaints.
Referenced by process_full_comp_unit(), read_func_scope(), and read_lexical_block_scope().
static void dwarf2_release_queue (void * dummy) [static]
Definition at line 7323 of file dwarf2read.c.
References dwarf2_per_cu_data::cu, dwarf2_queue, free_one_cached_comp_unit(), dwarf2_queue_item::next, dwarf2_queue_item::per_cu, dwarf2_per_cu_data::queued, and xfree().
Referenced by dw2_do_instantiate_symtab().
static void dwarf2_section_buffer_overflow_complaint (struct dwarf2_section_info * section) [static]
Definition at line 1892 of file dwarf2read.c.
References _, complaint(), get_section_file_name(), get_section_name(), and symfile_complaints.
Referenced by dwarf_decode_macro_bytes(), and skip_form_bytes().
static int dwarf2_section_empty_p (const struct dwarf2_section_info * section) [static]
Definition at line 2169 of file dwarf2read.c.
References dwarf2_section_info::asection, dwarf2_section_info::is_virtual, dwarf2_section_info::s, and dwarf2_section_info::size.
Referenced by create_dwo_unit_in_dwp_v1(), create_dwp_hash_table(), dwarf2_read_section(), and read_index_from_section().
static bfd_size_type dwarf2_section_size (struct objfile * objfile, struct dwarf2_section_info * info) [static]
Definition at line 2266 of file dwarf2read.c.
References dwarf2_read_section(), dwarf2_section_info::readin, and dwarf2_section_info::size.
Referenced by dwarf2_symbol_mark_computed(), and error_check_comp_unit_head().
static void dwarf2_start_subfile (const char * filename, const char * dirname, const char * comp_dir) [static]
Definition at line 17106 of file dwarf2read.c.
References start_subfile(), and xfree().
Referenced by dwarf_decode_lines(), dwarf_decode_lines_1(), and setup_type_unit_groups().
static void dwarf2_start_symtab (struct dwarf2_cu * cu, const char * name, const char * comp_dir, CORE_ADDR low_pc) [static]
Definition at line 17137 of file dwarf2read.c.
References processing_gcc_compilation, dwarf2_cu::producer, record_debugformat(), record_producer(), and start_symtab().
Referenced by read_file_scope(), and setup_type_unit_groups().
static void dwarf2_statement_list_fits_in_line_number_section_complaint (void) [static]
Definition at line 1855 of file dwarf2read.c.
References _, complaint(), and symfile_complaints.
Referenced by dwarf_decode_line_header().
static void dwarf2_symbol_mark_computed (const struct attribute * attr, struct symbol * sym, struct dwarf2_cu * cu, int is_block) [static]
Definition at line 20735 of file dwarf2read.c.
References _, attr_form_is_block(), attr_form_is_section_offset(), dwarf2_cu::base_known, complaint(), cu_debug_loc_section(), dwarf2_locexpr_baton::data, DW_BLOCK, DW_UNSND, dwarf2_invalid_attrib_class_complaint(), dwarf2_locexpr_block_index, dwarf2_locexpr_index, dwarf2_loclist_block_index, dwarf2_loclist_index, dwarf2_section_size(), fill_in_loclist_baton(), gdb_assert, objfile::objfile_obstack, dwarf2_locexpr_baton::per_cu, dwarf2_cu::per_cu, dwarf2_locexpr_baton::size, SYMBOL_ACLASS_INDEX, SYMBOL_LOCATION_BATON, SYMBOL_NATURAL_NAME, and symfile_complaints.
Referenced by read_func_scope(), and var_decode_location().
static struct dwarf_block * dwarf_alloc_block (struct dwarf2_cu * cu) [static, read]
Definition at line 19680 of file dwarf2read.c.
References dwarf2_cu::comp_unit_obstack.
Referenced by read_attribute_value().
static struct die_info * dwarf_alloc_die (struct dwarf2_cu * cu, int num_attrs) [static, read]
Definition at line 19690 of file dwarf2read.c.
References dwarf2_cu::comp_unit_obstack, memset(), and size.
Referenced by read_full_die_1().
static const char * dwarf_attr_name (unsigned int) [static]
Definition at line 18552 of file dwarf2read.c.
References name.
Referenced by dump_die_shallow(), and lookup_die_type().
static char * dwarf_bool_name (unsigned int) [static]
Definition at line 18586 of file dwarf2read.c.
Referenced by dump_die_shallow().
static struct line_header * dwarf_decode_line_header (unsigned int offset, struct dwarf2_cu * cu) [static, read]
Definition at line 16485 of file dwarf2read.c.
References _, add_file_name(), add_include_dir(), dwarf2_section_info::buffer, complaint(), discard_cleanups(), do_cleanups(), dwarf2_read_section(), dwarf2_statement_list_fits_in_line_number_section_complaint(), free_line_header(), get_debug_line_section(), get_section_bfd_owner(), dwarf2_cu::header, dwarf2_per_cu_data::is_debug_types, make_cleanup(), memset(), offset, dwarf2_cu::per_cu, read_1_byte(), read_1_signed_byte(), read_2_bytes(), read_checked_initial_length_and_offset(), read_direct_string(), read_offset_1(), read_unsigned_leb128(), dwarf2_section_info::size, symfile_complaints, and xmalloc().
Referenced by dw2_get_file_names_reader(), dwarf2_build_include_psymtabs(), handle_DW_AT_stmt_list(), and setup_type_unit_groups().
static void dwarf_decode_lines (struct line_header * lh, const char * comp_dir, struct dwarf2_cu * cu, struct partial_symtab * pst, int want_line_info) [static]
Definition at line 17024 of file dwarf2read.c.
References allocate_symtab(), current_subfile, dwarf2_create_include_psymtab(), dwarf2_start_subfile(), dwarf_decode_lines_1(), line_header::file_names, line_header::include_dirs, line_header::file_entry::included_p, subfile::name, line_header::num_file_names, dwarf2_cu::objfile, psymtab_include_file_name(), and subfile::symtab.
Referenced by dwarf2_build_include_psymtabs(), and handle_DW_AT_stmt_list().
static void dwarf_decode_lines_1 (struct line_header * lh, const char * comp_dir, struct dwarf2_cu * cu, struct partial_symtab * pst) [static]
Definition at line 16709 of file dwarf2read.c.
References _, add_file_name(), ANOFFSET, dwarf2_section_info::buffer, complaint(), current_subfile, line_header::default_is_stmt, dwarf2_debug_line_missing_end_sequence_complaint(), dwarf2_debug_line_missing_file_complaint(), dwarf2_start_subfile(), line_header::file_names, gdbarch_addr_bits_remove(), get_debug_line_section(), get_objfile_arch(), dwarf2_per_objfile::has_section_at_zero, line_header::include_dirs, line_header::file_entry::included_p, line, line_header::line_base, line_header::line_range, line_header::maximum_ops_per_instruction, line_header::minimum_instruction_length, noop_record_line(), line_header::num_file_names, objfile::obfd, dwarf2_cu::objfile, objfile_name(), line_header::opcode_base, read_1_byte(), read_2_bytes(), read_address(), read_direct_string(), read_signed_leb128(), read_unsigned_leb128(), record_line(), SECT_OFF_TEXT, objfile::section_offsets, line_header::standard_opcode_lengths, line_header::statement_program_end, line_header::statement_program_start, and symfile_complaints.
Referenced by dwarf_decode_lines().
static void dwarf_decode_macro_bytes (bfd * abfd, const gdb_byte * mac_ptr, const gdb_byte * mac_end, struct macro_source_file * current_file, struct line_header * lh, const char * comp_dir, struct dwarf2_section_info * section, int section_is_gnu, int section_is_dwz, unsigned int offset_size, struct objfile * objfile, htab_t include_hash) [static]
Definition at line 20152 of file dwarf2read.c.
References _, dwarf2_section_info::buffer, complaint(), dwarf2_get_dwz_file(), dwarf2_read_section(), dwarf2_section_buffer_overflow_complaint(), dwarf_parse_macro_header(), gdb_assert, get_section_bfd_owner(), macro_source_file::included_by, line, LONGEST, dwz_file::macro, macro_start_file(), macro_undef(), offset, parse_macro_definition(), read_1_byte(), read_direct_string(), read_indirect_string_at_offset(), read_indirect_string_from_dwz(), read_offset_1(), read_unsigned_leb128(), dwarf2_section_info::size, skip_unknown_opcode(), and symfile_complaints.
Referenced by dwarf_decode_macros().
static void dwarf_decode_macros (struct dwarf2_cu * cu, unsigned int offset, const char * comp_dir, int section_is_gnu) [static]
Definition at line 20427 of file dwarf2read.c.
References _, dwarf2_section_info::buffer, complaint(), do_cleanups(), dwarf2_read_section(), dwarf_decode_macro_bytes(), dwarf_parse_macro_header(), get_section_bfd_owner(), dwarf2_cu::header, line, dwarf2_cu::line_header, dwarf2_per_objfile::macinfo, dwarf2_per_objfile::macro, macro_start_file(), make_cleanup_htab_delete(), offset, comp_unit_head::offset_size, read_1_byte(), read_direct_string(), read_unsigned_leb128(), dwarf2_section_info::size, skip_unknown_opcode(), symfile_complaints, xcalloc(), and xfree().
Referenced by read_file_scope().
static const char * dwarf_form_name (unsigned int) [static]
Definition at line 18575 of file dwarf2read.c.
References name.
Referenced by dump_die_shallow(), dwarf2_const_value_attr(), dwarf2_fetch_constant_bytes(), dwarf2_get_attr_constant_value(), dwarf2_get_ref_die_offset(), get_DW_AT_signature_type(), read_attribute_value(), and skip_one_die().
static const gdb_byte* dwarf_parse_macro_header (const gdb_byte ** opcode_definitions, bfd * abfd, const gdb_byte * mac_ptr, unsigned int * offset_size, int section_is_gnu) [static]
Definition at line 20093 of file dwarf2read.c.
References _, complaint(), flags, memset(), read_1_byte(), read_2_bytes(), read_unsigned_leb128(), symfile_complaints, and version.
Referenced by dwarf_decode_macro_bytes(), and dwarf_decode_macros().
static const char * dwarf_tag_name (unsigned int) [static]
Definition at line 18539 of file dwarf2read.c.
References name.
Referenced by dump_die_shallow(), new_symbol_full(), process_die(), read_import_statement(), and read_type_die_1().
static const char * dwarf_type_encoding_name (unsigned int) [static]
Definition at line 18597 of file dwarf2read.c.
References name.
Referenced by read_base_type().
static int eq_dwo_file (const void * item_lhs, const void * item_rhs) [static]
Definition at line 8967 of file dwarf2read.c.
References dwo_file::comp_dir, and dwo_file::dwo_name.
Referenced by allocate_dwo_file_hash_table().
static int eq_dwo_unit (const void * item_lhs, const void * item_rhs) [static]
Definition at line 9024 of file dwarf2read.c.
References dwo_unit::signature.
Referenced by allocate_dwo_unit_table().
static int eq_dwp_loaded_cutus (const void * a, const void * b) [static]
Definition at line 10296 of file dwarf2read.c.
References dwo_unit::signature.
Referenced by allocate_dwp_loaded_cutus_table().
static int eq_file_name_entry (const void * a, const void * b) [static]
Definition at line 2524 of file dwarf2read.c.
References eq_stmt_list_entry(), and quick_file_names::hash.
Referenced by create_quick_file_names_table().
static int eq_psymtab_cu_index (const void * item_lhs, const void * item_rhs) [static]
Definition at line 21799 of file dwarf2read.c.
References psymtab_cu_index_map::psymtab.
Referenced by write_psymtabs_to_index().
static int eq_signatured_type (const void * item_lhs, const void * item_rhs) [static]
Definition at line 4424 of file dwarf2read.c.
References signatured_type::signature.
Referenced by allocate_signatured_type_table().
static int eq_stmt_list_entry (const struct stmt_list_hash * lhs, const struct stmt_list_hash * rhs) [static]
Definition at line 2499 of file dwarf2read.c.
References dwo_unit::dwo_file, stmt_list_hash::dwo_unit, stmt_list_hash::line_offset, and sect_offset::sect_off.
Referenced by eq_file_name_entry(), and eq_type_unit_group().
static int eq_strtab_entry (const void * a, const void * b) [static]
Definition at line 21424 of file dwarf2read.c.
References strtab_entry::str.
Referenced by create_strtab().
static int eq_symtab_entry (const void * a, const void * b) [static]
Definition at line 21500 of file dwarf2read.c.
References len, memcmp(), VEC_address, and VEC_length.
Referenced by create_symbol_hash_table().
static int eq_type_unit_group (const void * item_lhs, const void * item_rhs) [static]
Definition at line 5564 of file dwarf2read.c.
References eq_stmt_list_entry().
Referenced by allocate_type_unit_groups_table().
static void error_check_comp_unit_head (struct comp_unit_head * header, struct dwarf2_section_info * section, struct dwarf2_section_info * abbrev_section) [static]
Definition at line 4237 of file dwarf2read.c.
References _, comp_unit_head::abbrev_offset, dwarf2_section_size(), error(), get_cu_length(), get_section_bfd_owner(), get_section_file_name(), comp_unit_head::length, comp_unit_head::offset, sect_offset::sect_off, dwarf2_section_info::size, and comp_unit_head::version.
Referenced by read_and_check_comp_unit_head(), and read_and_check_type_unit_head().
static char* file_file_name (int file, struct line_header * lh) [static]
Definition at line 19711 of file dwarf2read.c.
References _, complaint(), line_header::file_names, line_header::include_dirs, symfile_complaints, and xsnprintf().
Referenced by file_full_name(), and macro_start_file().
static char * file_full_name (int file, struct line_header * lh, const char * comp_dir) [static]
Definition at line 19747 of file dwarf2read.c.
References file_file_name().
Referenced by dw2_get_file_names_reader().
static void fill_in_loclist_baton (struct dwarf2_cu * cu, struct dwarf2_loclist_baton * baton, const struct attribute * attr) [static]
Definition at line 20716 of file dwarf2read.c.
References dwarf2_loclist_baton::base_address, dwarf2_cu::base_address, dwarf2_section_info::buffer, cu_debug_loc_section(), dwarf2_loclist_baton::data, DW_UNSND, dwarf2_read_section(), dwarf2_loclist_baton::from_dwo, gdb_assert, dwarf2_loclist_baton::per_cu, dwarf2_cu::per_cu, dwarf2_loclist_baton::size, and dwarf2_section_info::size.
Referenced by dwarf2_fetch_die_loc_sect_off(), and dwarf2_symbol_mark_computed().
static void fill_in_sig_entry_from_dwo_entry (struct objfile * objfile, struct signatured_type * sig_entry, struct dwo_unit * dwo_entry) [static]
Definition at line 4657 of file dwarf2read.c.
References dwarf2_per_cu_data::cu, signatured_type::dwo_unit, gdb_assert, dwarf2_per_cu_data::length, dwo_unit::length, dwarf2_per_cu_data::objfile, dwarf2_per_cu_data::offset, dwo_unit::offset, signatured_type::per_cu, dwarf2_per_cu_data::queued, dwarf2_per_cu_data::quick, dwarf2_per_cu_data::reading_dwo_directly, sect_offset::sect_off, dwarf2_per_cu_data::section, dwo_unit::section, signatured_type::signature, dwo_unit::signature, dwarf2_per_cu_quick_data::symtab, signatured_type::type_offset_in_section, signatured_type::type_offset_in_tu, dwo_unit::type_offset_in_tu, signatured_type::type_unit_group, and dwarf2_per_cu_data::v.
Referenced by lookup_dwo_signatured_type(), and lookup_dwp_signatured_type().
static void find_file_and_directory (struct die_info * die, struct dwarf2_cu * cu, const char ** name, const char ** comp_dir) [static]
Definition at line 8649 of file dwarf2read.c.
References DW_STRING, dwarf2_attr(), ldirname(), make_cleanup(), producer_is_gcc_lt_4_3(), strchr(), and xfree().
Referenced by dw2_get_file_names_reader(), and read_file_scope().
static struct partial_die_info * find_partial_die (sect_offset offset, int offset_in_dwz, struct dwarf2_cu * cu) [static, read]
Definition at line 15250 of file dwarf2read.c.
References _, dwarf2_per_cu_data::cu, dwarf2_find_containing_comp_unit(), error(), find_partial_die_in_comp_unit(), dwarf2_cu::header, internal_error(), dwarf2_per_cu_data::is_debug_types, dwarf2_per_cu_data::is_dwz, dwarf2_cu::last_used, dwarf2_per_cu_data::load_all_dies, load_partial_comp_unit(), objfile::obfd, dwarf2_cu::objfile, comp_unit_head::offset, offset_in_cu_p(), dwarf2_cu::partial_dies, dwarf2_cu::per_cu, and sect_offset::sect_off.
Referenced by fixup_partial_die(), guess_partial_die_structure_name(), and partial_die_parent_scope().
static struct partial_die_info* find_partial_die_in_comp_unit (sect_offset offset, struct dwarf2_cu * cu) [static, read]
Definition at line 15232 of file dwarf2read.c.
References offset, partial_die_info::offset, dwarf2_cu::partial_dies, and sect_offset::sect_off.
Referenced by find_partial_die().
static struct symtab_index_entry** find_slot (struct mapped_symtab * symtab, const char * name) [static, read]
Definition at line 21562 of file dwarf2read.c.
References mapped_symtab::data, hash(), mapped_index_string_hash(), symtab_index_entry::name, and mapped_symtab::size.
Referenced by add_index_entry(), and hash_expand().
static int find_slot_in_mapped_hash (struct mapped_index * index, const char * name, offset_type ** vec_out) [static]
Definition at line 2893 of file dwarf2read.c.
References case_sensitive_off, case_sensitive_on, mapped_index::constant_pool, current_language, do_cleanups(), hash(), int, language_defn::la_language, language_cplus, language_fortran, language_java, make_cleanup(), mapped_index_string_hash(), MAYBE_SWAP, memcpy(), name, null_cleanup(), strchr(), mapped_index::symbol_table, mapped_index::symbol_table_slots, mapped_index::version, xfree(), and xmalloc().
Referenced by dw2_symtab_iter_init().
static void fixup_go_packaging (struct dwarf2_cu * cu) [static]
Definition at line 7526 of file dwarf2read.c.
References _, add_symbol_to_list(), allocate_symbol(), complaint(), global_symbols, go_symbol_package_name(), init_type(), language_go, LOC_BLOCK, LOC_TYPEDEF, pending::next, pending::nsyms, dwarf2_cu::objfile, objfile_name(), objfile::objfile_obstack, STRUCT_DOMAIN, pending::symbol, SYMBOL_ACLASS_INDEX, SYMBOL_CLASS, SYMBOL_DOMAIN, SYMBOL_LANGUAGE, SYMBOL_SET_LANGUAGE, SYMBOL_SET_NAMES, SYMBOL_SYMTAB, SYMBOL_TYPE, symfile_complaints, symtab_to_filename_for_display(), type, TYPE_CODE_MODULE, TYPE_NAME, TYPE_TAG_NAME, and xfree().
Referenced by process_full_comp_unit(), and process_full_type_unit().
static void fixup_partial_die (struct partial_die_info * part_die, struct dwarf2_cu * cu) [static]
Definition at line 15368 of file dwarf2read.c.
References CP_ANONYMOUS_NAMESPACE_STR, partial_die_info::die_parent, find_partial_die(), gdb_demangle(), guess_partial_die_structure_name(), dwarf2_cu::language, language_cplus, dwarf2_cu::objfile, objfile::objfile_obstack, partial_die_info::spec_offset, strrchr(), VEC_empty, and xfree().
Referenced by add_partial_subprogram(), partial_die_full_name(), partial_die_parent_scope(), and scan_partial_symbols().
static struct die_info* follow_die_offset (sect_offset offset, int offset_in_dwz, struct dwarf2_cu ** ref_cu) [static, read]
Definition at line 18852 of file dwarf2read.c.
References dwarf2_per_cu_data::cu, dwarf2_cu::die_hash, dwarf2_cu::dies, dwarf2_find_containing_comp_unit(), gdb_assert, dwarf2_cu::header, dwarf2_per_cu_data::is_debug_types, dwarf2_per_cu_data::is_dwz, dwarf2_cu::language, language_minimal, load_full_comp_unit(), maybe_queue_comp_unit(), dwarf2_cu::objfile, offset, offset_in_cu_p(), dwarf2_cu::per_cu, dwarf2_per_objfile::reading_partial_symbols, and sect_offset::sect_off.
Referenced by dwarf2_fetch_constant_bytes(), dwarf2_fetch_die_loc_sect_off(), and follow_die_ref().
static struct die_info * follow_die_ref (struct die_info * src_die, const struct attribute * attr, struct dwarf2_cu ** ref_cu) [static, read]
Definition at line 18901 of file dwarf2read.c.
References _, dwarf2_get_ref_die_offset(), error(), follow_die_offset(), dwarf2_per_cu_data::is_dwz, dwarf2_cu::objfile, objfile_name(), dwarf2_cu::per_cu, and sect_offset::sect_off.
Referenced by die_specification(), dwarf2_attr(), dwarf2_extension(), follow_die_ref_or_sig(), get_DW_AT_signature_type(), inherit_abstract_dies(), lookup_die_type(), partial_die_full_name(), read_call_site_scope(), and read_subroutine_type().
static struct die_info * follow_die_ref_or_sig (struct die_info * src_die, const struct attribute * attr, struct dwarf2_cu ** ref_cu) [static, read]
Definition at line 18827 of file dwarf2read.c.
References _, attr_form_is_ref(), dump_die_for_error(), error(), follow_die_ref(), follow_die_sig(), and objfile_name().
Referenced by read_import_statement().
static struct die_info * follow_die_sig (struct die_info * src_die, const struct attribute * attr, struct dwarf2_cu ** ref_cu) [static, read]
Definition at line 19213 of file dwarf2read.c.
References _, dump_die_for_error(), DW_SIGNATURE, error(), follow_die_sig_1(), gdb_assert, hex_string(), lookup_signatured_type(), objfile_name(), and ULONGEST.
Referenced by follow_die_ref_or_sig().
static struct die_info* follow_die_sig_1 (struct die_info * src_die, struct signatured_type * sig_type, struct dwarf2_cu ** ref_cu) [static, read]
Definition at line 19164 of file dwarf2read.c.
References dwarf2_per_cu_data::cu, dwarf2_cu::die_hash, gdb_assert, dwarf2_per_objfile::index_table, language_minimal, maybe_queue_comp_unit(), dwarf2_cu::per_cu, signatured_type::per_cu, read_signatured_type(), sect_offset::sect_off, signatured_type::type_offset_in_section, VEC_safe_push, and mapped_index::version.
Referenced by follow_die_sig(), and get_signatured_type().
static void free_cached_comp_units (void * data) [static]
Definition at line 21018 of file dwarf2read.c.
References dwarf2_per_cu_data::cu, free_heap_comp_unit(), dwarf2_per_objfile::read_in_chain, and dwarf2_cu::read_in_chain.
Referenced by dw2_instantiate_symtab(), dwarf2_build_psymtabs_hard(), and dwarf2_free_objfile().
static void free_cu_line_header (void * arg) [static]
Definition at line 8627 of file dwarf2read.c.
References free_line_header(), and dwarf2_cu::line_header.
Referenced by handle_DW_AT_stmt_list(), and setup_type_unit_groups().
static void free_delayed_list (void * ptr) [static]
Definition at line 7483 of file dwarf2read.c.
References VEC_free.
Referenced by process_full_comp_unit(), and process_full_type_unit().
static void free_dwo_file (struct dwo_file * dwo_file, struct objfile * objfile) [static]
Definition at line 10643 of file dwarf2read.c.
References dwo_file::dbfd, gdb_bfd_unref(), dwo_file::sections, and VEC_free.
Referenced by free_dwo_file_cleanup(), and free_dwo_file_from_slot().
static void free_dwo_file_cleanup (void * arg) [static]
Definition at line 10657 of file dwarf2read.c.
References free_dwo_file().
Referenced by open_and_init_dwo_file().
static int free_dwo_file_from_slot (void ** slot, void * info) [static]
Definition at line 10668 of file dwarf2read.c.
References free_dwo_file().
Referenced by free_dwo_files().
static void free_dwo_files (htab_t dwo_files, struct objfile * objfile) [static]
Definition at line 10681 of file dwarf2read.c.
References free_dwo_file_from_slot().
Referenced by dwarf2_per_objfile_free().
static void free_heap_comp_unit (void * data) [static]
Definition at line 20985 of file dwarf2read.c.
References dwarf2_cu::comp_unit_obstack, dwarf2_per_cu_data::cu, gdb_assert, dwarf2_cu::per_cu, and xfree().
Referenced by age_cached_comp_units(), free_cached_comp_units(), free_one_cached_comp_unit(), init_cutu_and_read_dies(), and init_tu_and_read_dwo_dies().
static void free_line_header (struct line_header * lh) [static]
Definition at line 16377 of file dwarf2read.c.
References line_header::file_names, line_header::include_dirs, line_header::standard_opcode_lengths, and xfree().
Referenced by dw2_get_file_names_reader(), dwarf2_build_include_psymtabs(), dwarf_decode_line_header(), and free_cu_line_header().
static void free_one_cached_comp_unit (struct dwarf2_per_cu_data * target_per_cu) [static]
Definition at line 21078 of file dwarf2read.c.
References dwarf2_per_cu_data::cu, free_heap_comp_unit(), dwarf2_per_objfile::read_in_chain, and dwarf2_cu::read_in_chain.
Referenced by dwarf2_release_queue(), and process_psymtab_comp_unit().
static void free_stack_comp_unit (void * data) [static]
Definition at line 21003 of file dwarf2read.c.
References dwarf2_cu::comp_unit_obstack, dwarf2_per_cu_data::cu, gdb_assert, dwarf2_cu::partial_dies, and dwarf2_cu::per_cu.
Referenced by init_cutu_and_read_dies_no_follow().
static struct dwarf2_section_info* get_abbrev_section_for_cu (struct dwarf2_per_cu_data * this_cu) [static, read]
Definition at line 4220 of file dwarf2read.c.
References dwarf2_per_objfile::abbrev, dwz_file::abbrev, dwarf2_get_dwz_file(), and dwarf2_per_cu_data::is_dwz.
Referenced by init_cutu_and_read_dies(), and init_cutu_and_read_dies_simple().
static struct dwarf2_section_info* get_containing_section (const struct dwarf2_section_info * section) [static, read]
Definition at line 1975 of file dwarf2read.c.
References dwarf2_section_info::containing_section, gdb_assert, dwarf2_section_info::is_virtual, and dwarf2_section_info::s.
Referenced by dwarf2_read_section(), get_section_bfd_owner(), and get_section_bfd_section().
static unsigned int get_cu_length (const struct comp_unit_head * header) [static]
Definition at line 4138 of file dwarf2read.c.
References comp_unit_head::initial_length_size, and comp_unit_head::length.
Referenced by create_debug_types_hash_table(), error_check_comp_unit_head(), init_cutu_and_read_dies(), init_cutu_and_read_dies_no_follow(), offset_in_cu_p(), and read_cutu_die_from_dwo().
static struct dwarf2_section_info* get_debug_line_section (struct dwarf2_cu * cu) [static, read]
Definition at line 16456 of file dwarf2read.c.
References dwarf2_get_dwz_file(), dwarf2_per_cu_data::is_debug_types, dwarf2_per_cu_data::is_dwz, dwarf2_per_objfile::line, dwz_file::line, and dwarf2_cu::per_cu.
Referenced by dwarf_decode_line_header(), and dwarf_decode_lines_1().
static struct type * get_die_type (struct die_info * die, struct dwarf2_cu * cu) [static, read]
Definition at line 21254 of file dwarf2read.c.
References get_die_type_at_offset(), and dwarf2_cu::per_cu.
Referenced by process_enumeration_scope(), process_structure_scope(), read_array_type(), read_call_site_scope(), read_set_type(), read_structure_type(), read_subrange_type(), read_subroutine_type(), read_tag_const_type(), read_tag_pointer_type(), read_tag_ptr_to_member_type(), read_tag_reference_type(), read_tag_restrict_type(), read_tag_volatile_type(), and read_type_die().
static struct type * get_die_type_at_offset (sect_offset offset, struct dwarf2_per_cu_data * per_cu) [static, read]
Definition at line 21233 of file dwarf2read.c.
References dwarf2_per_objfile::die_type_hash, offset, dwarf2_per_cu_offset_and_type::offset, dwarf2_per_cu_offset_and_type::per_cu, and dwarf2_per_cu_offset_and_type::type.
Referenced by dwarf2_get_die_type(), get_die_type(), and lookup_die_type().
static struct type * get_DW_AT_signature_type (struct die_info * die, const struct attribute * attr, struct dwarf2_cu * cu) [static, read]
Definition at line 19311 of file dwarf2read.c.
References _, attr_form_is_ref(), build_error_marker_type(), complaint(), DW_SIGNATURE, dwarf_form_name(), follow_die_ref(), get_signatured_type(), objfile_name(), read_type_die(), and symfile_complaints.
Referenced by read_enumeration_type(), and read_structure_type().
static struct dwp_file * get_dwp_file (void) [static, read]
Definition at line 10437 of file dwarf2read.c.
References dwarf2_per_objfile::dwp_checked, dwarf2_per_objfile::dwp_file, and open_and_init_dwp_file().
Referenced by dw2_do_instantiate_symtab(), lookup_dwo_cutu(), lookup_dwp_signatured_type(), lookup_signatured_type(), and queue_and_load_all_dwo_tus().
static void get_scope_pc_bounds (struct die_info * die, CORE_ADDR * lowpc, CORE_ADDR * highpc, struct dwarf2_cu * cu) [static]
Definition at line 11623 of file dwarf2read.c.
References dwarf2_get_pc_bounds(), dwarf2_get_subprogram_pc_bounds(), max, min, and sibling_die().
Referenced by process_full_comp_unit(), and read_file_scope().
static struct bfd* get_section_bfd_owner (const struct dwarf2_section_info * section) [static, read]
Definition at line 1984 of file dwarf2read.c.
References dwarf2_section_info::asection, gdb_assert, get_containing_section(), dwarf2_section_info::is_virtual, and dwarf2_section_info::s.
Referenced by abbrev_table_read_table(), create_debug_types_hash_table(), create_dwo_cu(), dwarf2_read_section(), dwarf_decode_line_header(), dwarf_decode_macro_bytes(), dwarf_decode_macros(), error_check_comp_unit_head(), get_section_file_name(), get_section_name(), init_cu_die_reader(), init_cutu_and_read_dies(), init_cutu_and_read_dies_no_follow(), read_abbrev_offset(), read_and_check_comp_unit_head(), read_and_check_type_unit_head(), read_comp_units_from_section(), and read_cutu_die_from_dwo().
static asection* get_section_bfd_section (const struct dwarf2_section_info * section) [static]
Definition at line 1998 of file dwarf2read.c.
References dwarf2_section_info::asection, gdb_assert, get_containing_section(), dwarf2_section_info::is_virtual, and dwarf2_section_info::s.
Referenced by create_dwp_v2_section(), dwarf2_get_section_info(), dwarf2_read_section(), get_section_flags(), get_section_id(), and get_section_name().
static const char * get_section_file_name (const struct dwarf2_section_info * section) [static]
Definition at line 2022 of file dwarf2read.c.
References get_section_bfd_owner().
Referenced by create_debug_types_hash_table(), create_dwo_cu(), dwarf2_read_section(), dwarf2_section_buffer_overflow_complaint(), error_check_comp_unit_head(), and read_comp_units_from_section().
static int get_section_flags (const struct dwarf2_section_info * section) [static]
Definition at line 2046 of file dwarf2read.c.
References gdb_assert, and get_section_bfd_section().
Referenced by read_index_from_section().
static int get_section_id (const struct dwarf2_section_info * section) [static]
Definition at line 2033 of file dwarf2read.c.
References get_section_bfd_section().
Referenced by create_dwo_unit_in_dwp_v1().
static const char * get_section_name (const struct dwarf2_section_info * section) [static]
Definition at line 2011 of file dwarf2read.c.
References gdb_assert, get_section_bfd_owner(), and get_section_bfd_section().
Referenced by create_dwo_cu(), dwarf2_read_section(), dwarf2_section_buffer_overflow_complaint(), read_comp_units_from_section(), read_cutu_die_from_dwo(), read_die_and_siblings(), read_full_die(), and skip_form_bytes().
static struct type * get_signatured_type (struct die_info * die, ULONGEST signature, struct dwarf2_cu * cu) [static, read]
Definition at line 19250 of file dwarf2read.c.
References _, build_error_marker_type(), complaint(), follow_die_sig_1(), hex_string(), lookup_signatured_type(), objfile_name(), read_type_die(), symfile_complaints, type, and signatured_type::type.
Referenced by get_DW_AT_signature_type(), and lookup_die_type().
static struct symtab* get_symtab (struct dwarf2_per_cu_data * per_cu) [static, read]
Definition at line 7594 of file dwarf2read.c.
References dwarf2_per_cu_data::psymtab, dwarf2_per_cu_data::quick, partial_symtab::symtab, dwarf2_per_cu_quick_data::symtab, dwarf2_per_objfile::using_index, and dwarf2_per_cu_data::v.
Referenced by compute_symtab_includes(), and recursively_compute_inclusions().
static struct type_unit_group * get_type_unit_group (struct dwarf2_cu * cu, const struct attribute * stmt_list) [static, read]
Definition at line 5641 of file dwarf2read.c.
References allocate_type_unit_groups_table(), create_type_unit_group(), DW_UNSND, gdb_assert, NO_STMT_LIST_TYPE_UNIT_PSYMTAB, NO_STMT_LIST_TYPE_UNIT_PSYMTAB_SIZE, sect_offset::sect_off, and dwarf2_per_objfile::tu_stats.
Referenced by build_type_psymtabs_reader(), and setup_type_unit_groups().
static char* guess_full_die_structure_name (struct die_info * die, struct dwarf2_cu * cu) [static]
Definition at line 18064 of file dwarf2read.c.
References die_specification(), DW_STRING, dwarf2_attr(), dwarf2_name(), language_class_name_from_physname(), dwarf2_cu::language_defn, name, dwarf2_cu::objfile, objfile::objfile_obstack, and xfree().
Referenced by determine_prefix().
static void guess_partial_die_structure_name (struct partial_die_info * struct_pdi, struct dwarf2_cu * cu) [static]
Definition at line 15317 of file dwarf2read.c.
References partial_die_info::die_child, partial_die_info::die_parent, partial_die_info::die_sibling, find_partial_die(), language_class_name_from_physname(), dwarf2_cu::language_defn, dwarf2_cu::objfile, objfile::objfile_obstack, partial_die_info::spec_offset, and xfree().
Referenced by fixup_partial_die().
static int handle_data_member_location (struct die_info * die, struct dwarf2_cu * cu, LONGEST * offset) [static]
Definition at line 11908 of file dwarf2read.c.
References attr_form_is_block(), attr_form_is_constant(), attr_form_is_section_offset(), decode_locdesc(), DW_BLOCK, dwarf2_attr(), dwarf2_complex_location_expr_complaint(), and dwarf2_get_attr_constant_value().
Referenced by dwarf2_add_field().
static void handle_DW_AT_stmt_list (struct die_info * die, struct dwarf2_cu * cu, const char * comp_dir) [static]
Definition at line 8697 of file dwarf2read.c.
References DW_UNSND, dwarf2_attr(), dwarf_decode_line_header(), dwarf_decode_lines(), free_cu_line_header(), gdb_assert, dwarf2_per_cu_data::is_debug_types, dwarf2_cu::line_header, make_cleanup(), and dwarf2_cu::per_cu.
Referenced by read_file_scope().
static hashval_t hash_dwo_file (const void * item) [static]
Definition at line 8955 of file dwarf2read.c.
References dwo_file::comp_dir, dwo_file::dwo_name, and hash().
Referenced by allocate_dwo_file_hash_table().
static hashval_t hash_dwo_unit (const void * item) [static]
Definition at line 9015 of file dwarf2read.c.
References dwo_unit::signature.
Referenced by allocate_dwo_unit_table().
static hashval_t hash_dwp_loaded_cutus (const void * item) [static]
Definition at line 10285 of file dwarf2read.c.
References dwo_unit::signature.
Referenced by allocate_dwp_loaded_cutus_table().
static void hash_expand (struct mapped_symtab * symtab) [static]
Definition at line 21580 of file dwarf2read.c.
References mapped_symtab::data, find_slot(), mapped_symtab::size, and xfree().
Referenced by add_index_entry().
static hashval_t hash_file_name_entry (const void * e) [static]
Definition at line 2514 of file dwarf2read.c.
References quick_file_names::hash, and hash_stmt_list_entry().
Referenced by create_quick_file_names_table().
static hashval_t hash_psymtab_cu_index (const void * item) [static]
Definition at line 21791 of file dwarf2read.c.
References psymtab_cu_index_map::psymtab.
Referenced by write_psymtabs_to_index().
static hashval_t hash_signatured_type (const void * item) [static]
Definition at line 4415 of file dwarf2read.c.
References signatured_type::signature.
Referenced by allocate_signatured_type_table().
static hashval_t hash_stmt_list_entry (const struct stmt_list_hash * stmt_list_hash) [static]
Definition at line 2486 of file dwarf2read.c.
References dwo_unit::dwo_file, stmt_list_hash::dwo_unit, stmt_list_hash::line_offset, and sect_offset::sect_off.
Referenced by hash_file_name_entry(), and hash_type_unit_group().
static hashval_t hash_strtab_entry (const void * e) [static]
Definition at line 21415 of file dwarf2read.c.
References mapped_index_string_hash(), and strtab_entry::str.
Referenced by create_strtab().
static hashval_t hash_symtab_entry (const void * e) [static]
Definition at line 21488 of file dwarf2read.c.
References VEC_address, and VEC_length.
Referenced by create_symbol_hash_table().
static hashval_t hash_type_unit_group (const void * item) [static]
Definition at line 5556 of file dwarf2read.c.
References hash_stmt_list_entry().
Referenced by allocate_type_unit_groups_table().
static void inherit_abstract_dies (struct die_info * die, struct dwarf2_cu * cu) [static]
Definition at line 10705 of file dwarf2read.c.
References _, complaint(), do_cleanups(), dwarf2_attr(), follow_die_ref(), dwarf2_cu::list_in_scope, make_cleanup(), process_die(), qsort, sect_offset::sect_off, sibling_die(), symfile_complaints, unsigned_int_compar(), xfree(), and xmalloc().
Referenced by read_func_scope().
static void init_cu_die_reader (struct die_reader_specs * reader, struct dwarf2_cu * cu, struct dwarf2_section_info * section, struct dwo_file * dwo_file) [static]
Definition at line 4859 of file dwarf2read.c.
References die_reader_specs::abfd, dwarf2_section_info::buffer, die_reader_specs::buffer, die_reader_specs::buffer_end, die_reader_specs::comp_dir, die_reader_specs::cu, die_reader_specs::die_section, die_reader_specs::dwo_file, gdb_assert, get_section_bfd_owner(), dwarf2_section_info::readin, and dwarf2_section_info::size.
Referenced by init_cutu_and_read_dies(), init_cutu_and_read_dies_no_follow(), and read_cutu_die_from_dwo().
static void init_cutu_and_read_dies (struct dwarf2_per_cu_data * this_cu, struct abbrev_table * abbrev_table, int use_existing_cu, int keep, die_reader_func_ftype * die_reader_func, void * data) [static]
Definition at line 5227 of file dwarf2read.c.
References _, comp_unit_head::abbrev_offset, dwarf2_cu::abbrev_table, dwarf2_section_info::buffer, complaint(), dwarf2_per_cu_data::cu, cu_offset::cu_off, discard_cleanups(), do_cleanups(), dwarf2_attr(), dwarf2_die_debug, dwarf2_free_abbrev_table(), dwarf2_read_abbrevs(), dwarf2_read_section(), comp_unit_head::first_die_offset, fprintf_unfiltered(), free_heap_comp_unit(), gdb_assert, gdb_stdlog, get_abbrev_section_for_cu(), get_cu_length(), get_section_bfd_owner(), dwarf2_cu::header, init_cu_die_reader(), init_one_comp_unit(), init_tu_and_read_dwo_dies(), dwarf2_per_cu_data::is_debug_types, dwarf2_per_cu_data::length, lookup_dwo_unit(), make_cleanup(), null_cleanup(), comp_unit_head::offset, dwarf2_per_cu_data::offset, abbrev_table::offset, peek_abbrev_code(), read_and_check_comp_unit_head(), read_and_check_type_unit_head(), read_cutu_die_from_dwo(), read_full_die(), dwarf2_per_objfile::read_in_chain, dwarf2_cu::read_in_chain, dwarf2_per_cu_data::reading_dwo_directly, sect_offset::sect_off, dwarf2_per_cu_data::section, signatured_type::signature, symfile_complaints, signatured_type::type_offset_in_section, signatured_type::type_offset_in_tu, ULONGEST, and xmalloc().
Referenced by build_type_unit_groups(), dwarf2_read_addr_index(), load_full_comp_unit(), load_partial_comp_unit(), process_psymtab_comp_unit(), and read_signatured_type().
static void init_cutu_and_read_dies_no_follow (struct dwarf2_per_cu_data * this_cu, struct dwarf2_section_info * abbrev_section, struct dwo_file * dwo_file, die_reader_func_ftype * die_reader_func, void * data) [static]
Definition at line 5471 of file dwarf2read.c.
References dwarf2_section_info::buffer, dwarf2_per_cu_data::cu, do_cleanups(), dwarf2_die_debug, dwarf2_free_abbrev_table(), dwarf2_read_abbrevs(), dwarf2_read_section(), fprintf_unfiltered(), free_stack_comp_unit(), gdb_assert, gdb_stdlog, get_cu_length(), get_section_bfd_owner(), dwarf2_cu::header, init_cu_die_reader(), init_one_comp_unit(), dwarf2_per_cu_data::is_debug_types, dwarf2_per_cu_data::length, make_cleanup(), dwarf2_per_cu_data::offset, peek_abbrev_code(), read_and_check_comp_unit_head(), read_full_die(), sect_offset::sect_off, and dwarf2_per_cu_data::section.
Referenced by create_dwo_cu(), and init_cutu_and_read_dies_simple().
static void init_cutu_and_read_dies_simple (struct dwarf2_per_cu_data * this_cu, die_reader_func_ftype * die_reader_func, void * data) [static]
Definition at line 5537 of file dwarf2read.c.
References get_abbrev_section_for_cu(), and init_cutu_and_read_dies_no_follow().
Referenced by dw2_get_file_names().
static void init_one_comp_unit (struct dwarf2_cu * cu, struct dwarf2_per_cu_data * per_cu) [static]
Definition at line 20946 of file dwarf2read.c.
References dwarf2_cu::comp_unit_obstack, dwarf2_per_cu_data::cu, memset(), dwarf2_cu::objfile, dwarf2_per_cu_data::objfile, and dwarf2_cu::per_cu.
Referenced by init_cutu_and_read_dies(), init_cutu_and_read_dies_no_follow(), and init_tu_and_read_dwo_dies().
static void init_tu_and_read_dwo_dies (struct dwarf2_per_cu_data * this_cu, int keep, die_reader_func_ftype * die_reader_func, void * data) [static]
Definition at line 5145 of file dwarf2read.c.
References dwo_file::comp_dir, dwarf2_per_cu_data::cu, discard_cleanups(), do_cleanups(), dwarf2_free_abbrev_table(), dwo_unit::dwo_file, signatured_type::dwo_unit, free_heap_comp_unit(), gdb_assert, init_one_comp_unit(), dwarf2_per_cu_data::is_debug_types, make_cleanup(), null_cleanup(), read_cutu_die_from_dwo(), dwarf2_per_objfile::read_in_chain, dwarf2_cu::read_in_chain, dwarf2_per_cu_data::reading_dwo_directly, and xmalloc().
Referenced by init_cutu_and_read_dies().
static int is_type_tag_for_partial (int tag) [static]
Definition at line 14711 of file dwarf2read.c.
Referenced by load_partial_dies().
static int is_vtable_name (const char * name, struct dwarf2_cu * cu) [static]
Definition at line 12523 of file dwarf2read.c.
References is_cplus_marker(), dwarf2_cu::language, and language_java.
static int leb128_size (const gdb_byte * buf) [static]
Definition at line 16213 of file dwarf2read.c.
Referenced by locexpr_describe_location_piece(), and var_decode_location().
static void load_cu (struct dwarf2_per_cu_data * per_cu) [static]
Definition at line 2566 of file dwarf2read.c.
References dwarf2_per_cu_data::cu, dwarf2_cu::dies, dwarf2_find_base_address(), gdb_assert, dwarf2_per_cu_data::is_debug_types, language_minimal, load_full_comp_unit(), and load_full_type_unit().
Referenced by dw2_do_instantiate_symtab(), dwarf2_fetch_constant_bytes(), and dwarf2_fetch_die_loc_sect_off().
static void load_full_comp_unit (struct dwarf2_per_cu_data * this_cu, enum language pretend_language) [static]
Definition at line 7455 of file dwarf2read.c.
References gdb_assert, init_cutu_and_read_dies(), dwarf2_per_cu_data::is_debug_types, and load_full_comp_unit_reader().
Referenced by follow_die_offset(), load_cu(), and process_imported_unit_die().
static void load_full_comp_unit_reader (const struct die_reader_specs * reader, const gdb_byte * info_ptr, struct die_info * comp_unit_die, int has_children, void * data) [static]
Definition at line 7418 of file dwarf2read.c.
References dwarf2_cu::comp_unit_obstack, die_reader_specs::cu, die_eq(), dwarf2_cu::die_hash, die_hash(), dwarf2_cu::dies, dummy_obstack_deallocate(), gdb_assert, hashtab_obstack_allocate(), dwarf2_cu::header, comp_unit_head::length, prepare_one_comp_unit(), and read_die_and_siblings().
Referenced by load_full_comp_unit().
static void load_full_type_unit (struct dwarf2_per_cu_data * per_cu) [static]
Definition at line 19340 of file dwarf2read.c.
References dwarf2_per_cu_data::cu, gdb_assert, dwarf2_per_cu_data::is_debug_types, IS_TYPE_UNIT_GROUP, and read_signatured_type().
Referenced by load_cu(), and queue_and_load_dwo_tu().
static void load_partial_comp_unit (struct dwarf2_per_cu_data * this_cu) [static]
Definition at line 6301 of file dwarf2read.c.
References init_cutu_and_read_dies(), and load_partial_comp_unit_reader().
Referenced by find_partial_die().
static void load_partial_comp_unit_reader (const struct die_reader_specs * reader, const gdb_byte * info_ptr, struct die_info * comp_unit_die, int has_children, void * data) [static]
Definition at line 6280 of file dwarf2read.c.
References die_reader_specs::cu, language_minimal, load_partial_dies(), and prepare_one_comp_unit().
Referenced by load_partial_comp_unit().
static struct partial_die_info * load_partial_dies (const struct die_reader_specs * reader, const gdb_byte * info_ptr, int building_psymtab) [static, read]
Definition at line 14742 of file dwarf2read.c.
References _, add_psymbol_to_list(), dwarf2_cu::comp_unit_obstack, complaint(), die_reader_specs::cu, partial_die_info::die_child, partial_die_info::die_parent, partial_die_info::die_sibling, dummy_obstack_deallocate(), gdb_assert, objfile::global_psymbols, hashtab_obstack_allocate(), dwarf2_cu::header, is_type_tag_for_partial(), dwarf2_cu::language, language_ada, language_c, language_cplus, language_java, comp_unit_head::length, dwarf2_per_cu_data::load_all_dies, LOC_CONST, LOC_TYPEDEF, locate_pdi_sibling(), dwarf2_cu::objfile, objfile_name(), partial_die_info::offset, partial_die_eq(), partial_die_hash(), dwarf2_cu::partial_dies, peek_die_abbrev(), dwarf2_cu::per_cu, read_partial_die(), sect_offset::sect_off, skip_one_die(), objfile::static_psymbols, strchr(), symfile_complaints, abbrev_info::tag, and VAR_DOMAIN.
Referenced by build_type_psymtabs_reader(), load_partial_comp_unit_reader(), and process_psymtab_comp_unit_reader().
static void locate_dwz_sections (bfd * abfd, asection * sectp, void * arg) [static]
Definition at line 2318 of file dwarf2read.c.
References dwarf2_debug_sections::abbrev, dwz_file::abbrev, dwarf2_section_info::asection, dwarf2_debug_sections::gdb_index, dwz_file::gdb_index, dwarf2_debug_sections::info, dwz_file::info, dwarf2_debug_sections::line, dwz_file::line, dwarf2_debug_sections::macro, dwz_file::macro, dwarf2_section_info::s, section_is_p(), dwarf2_section_info::size, dwarf2_debug_sections::str, and dwz_file::str.
Referenced by dwarf2_get_dwz_file().
static const gdb_byte* locate_pdi_sibling (const struct die_reader_specs * reader, struct partial_die_info * orig_pdi, const gdb_byte * info_ptr) [static]
Definition at line 7116 of file dwarf2read.c.
References partial_die_info::sibling, and skip_children().
Referenced by load_partial_dies().
static int locate_v1_virtual_dwo_sections (asection * sectp, struct virtual_v1_dwo_sections * sections) [static]
Definition at line 9474 of file dwarf2read.c.
References virtual_v1_dwo_sections::abbrev, dwop_section_names::abbrev_dwo, dwarf2_section_info::asection, dwop_section_names, dwop_section_names::info_dwo, virtual_v1_dwo_sections::info_or_types, virtual_v1_dwo_sections::line, dwop_section_names::line_dwo, virtual_v1_dwo_sections::loc, dwop_section_names::loc_dwo, virtual_v1_dwo_sections::macinfo, dwop_section_names::macinfo_dwo, virtual_v1_dwo_sections::macro, dwop_section_names::macro_dwo, dwarf2_section_info::s, section_is_p(), dwarf2_section_info::size, virtual_v1_dwo_sections::str_offsets, dwop_section_names::str_offsets_dwo, and dwop_section_names::types_dwo.
Referenced by create_dwo_unit_in_dwp_v1().
static struct type * lookup_die_type (struct die_info * die, const struct attribute * attr, struct dwarf2_cu * cu) [static, read]
Definition at line 17889 of file dwarf2read.c.
References _, attr_form_is_ref(), build_error_marker_type(), complaint(), DW_SIGNATURE, dwarf2_find_containing_comp_unit(), dwarf2_get_ref_die_offset(), dwarf_attr_name(), follow_die_ref(), gdb_assert, get_die_type_at_offset(), get_signatured_type(), dwarf2_cu::objfile, objfile_name(), dwarf2_cu::per_cu, read_type_die(), symfile_complaints, and ULONGEST.
Referenced by die_containing_type(), die_descriptive_type(), and die_type().
static struct dwo_unit * lookup_dwo_comp_unit (struct dwarf2_per_cu_data * this_cu, const char * dwo_name, const char * comp_dir, ULONGEST signature) [static, read]
Definition at line 10572 of file dwarf2read.c.
References lookup_dwo_cutu().
Referenced by lookup_dwo_unit().
static struct dwo_unit* lookup_dwo_cutu (struct dwarf2_per_cu_data * this_unit, const char * dwo_name, const char * comp_dir, ULONGEST signature, int is_debug_types) [static, read]
Definition at line 10464 of file dwarf2read.c.
References _, dwo_file::cu, dwp_file::cus, dwarf2_read_debug, fprintf_unfiltered(), gdb_stdlog, get_dwp_file(), hex_string(), host_address_to_string(), dwarf2_per_cu_data::is_debug_types, lookup_dwo_file_slot(), lookup_dwo_unit_in_dwp(), memset(), objfile_name(), dwarf2_per_cu_data::offset, open_and_init_dwo_file(), sect_offset::sect_off, dwo_unit::signature, dwo_file::tus, dwp_file::tus, and warning().
Referenced by lookup_dwo_comp_unit(), and lookup_dwo_type_unit().
static void** lookup_dwo_file_slot (const char * dwo_name, const char * comp_dir) [static]
Definition at line 8998 of file dwarf2read.c.
References allocate_dwo_file_hash_table(), dwo_file::comp_dir, dwarf2_per_objfile::dwo_files, dwo_file::dwo_name, and memset().
Referenced by create_dwo_unit_in_dwp_v1(), create_dwo_unit_in_dwp_v2(), and lookup_dwo_cutu().
static struct signatured_type* lookup_dwo_signatured_type (struct dwarf2_cu * cu, ULONGEST sig) [static, read]
Definition at line 4693 of file dwarf2read.c.
References fill_in_sig_entry_from_dwo_entry(), gdb_assert, signatured_type::per_cu, signatured_type::signature, dwo_unit::signature, dwarf2_per_cu_data::tu_read, dwo_file::tus, and dwarf2_per_objfile::using_index.
Referenced by lookup_signatured_type(), and queue_and_load_dwo_tu().
static struct dwo_unit * lookup_dwo_type_unit (struct signatured_type * this_tu, const char * dwo_name, const char * comp_dir) [static, read]
Definition at line 10583 of file dwarf2read.c.
References lookup_dwo_cutu(), signatured_type::per_cu, and signatured_type::signature.
Referenced by lookup_dwo_unit().
static struct dwo_unit* lookup_dwo_unit (struct dwarf2_per_cu_data * this_cu, struct die_info * comp_unit_die) [static, read]
Definition at line 5094 of file dwarf2read.c.
References _, dwarf2_per_cu_data::cu, DW_STRING, DW_UNSND, dwarf2_attr(), error(), gdb_assert, dwarf2_per_cu_data::is_debug_types, lookup_dwo_comp_unit(), lookup_dwo_type_unit(), dwarf2_per_cu_data::objfile, objfile_name(), signatured_type::signature, and ULONGEST.
Referenced by init_cutu_and_read_dies().
static struct dwo_unit * lookup_dwo_unit_in_dwp (struct dwp_file * dwp_file, const char * comp_dir, ULONGEST signature, int is_debug_types) [static, read]
Definition at line 9929 of file dwarf2read.c.
References _, create_dwo_unit_in_dwp_v1(), create_dwo_unit_in_dwp_v2(), dwp_file::cus, dwp_file::dbfd, error(), hash(), dwp_hash_table::hash_table, dwp_file::loaded_cus, dwp_file::loaded_tus, memset(), dwp_file::name, dwp_hash_table::nr_slots, read_4_bytes(), read_8_bytes(), dwo_unit::signature, dwp_file::tus, ULONGEST, dwp_hash_table::unit_table, and dwp_file::version.
Referenced by lookup_dwo_cutu(), and lookup_dwp_signatured_type().
static struct signatured_type* lookup_dwp_signatured_type (struct dwarf2_cu * cu, ULONGEST sig) [static, read]
Definition at line 4781 of file dwarf2read.c.
References _, add_type_unit(), complaint(), fill_in_sig_entry_from_dwo_entry(), gdb_assert, get_dwp_file(), hex_string(), dwarf2_per_cu_data::is_debug_types, lookup_dwo_unit_in_dwp(), objfile_name(), dwarf2_per_cu_data::offset, dwarf2_cu::per_cu, sect_offset::sect_off, signatured_type::signature, symfile_complaints, dwp_file::tus, and dwarf2_per_objfile::using_index.
Referenced by lookup_signatured_type().
static struct signatured_type* lookup_signatured_type (struct dwarf2_cu * cu, ULONGEST sig) [static, read]
Definition at line 4830 of file dwarf2read.c.
References get_dwp_file(), lookup_dwo_signatured_type(), lookup_dwp_signatured_type(), signatured_type::signature, and dwarf2_per_objfile::using_index.
Referenced by follow_die_sig(), and get_signatured_type().
static struct macro_source_file* macro_start_file (int file, int line, struct macro_source_file * current_file, const char * comp_dir, struct line_header * lh, struct objfile * objfile) [static, read]
Definition at line 19765 of file dwarf2read.c.
References file_file_name(), get_macro_table(), macro_define_special(), macro_include(), macro_set_main(), and xfree().
Referenced by dwarf_decode_macro_bytes(), and dwarf_decode_macros().
static hashval_t mapped_index_string_hash (int index_version, const void * p) [static]
Definition at line 2872 of file dwarf2read.c.
Referenced by find_slot(), find_slot_in_mapped_hash(), and hash_strtab_entry().
static void mark_common_block_symbol_computed (struct symbol * sym, struct die_info * common_die, struct attribute * common_loc, struct attribute * member_loc, struct dwarf2_cu * cu) [static]
Definition at line 13271 of file dwarf2read.c.
References comp_unit_head::addr_size, attr_form_is_block(), attr_form_is_constant(), dwarf2_locexpr_baton::data, DW_BLOCK, dwarf2_get_attr_constant_value(), dwarf2_locexpr_index, gdb_assert, gdbarch_byte_order(), get_objfile_arch(), dwarf2_cu::header, LONGEST, memcpy(), objfile::objfile_obstack, dwarf2_per_cu_data::offset, dwarf2_locexpr_baton::per_cu, dwarf2_cu::per_cu, sect_offset::sect_off, dwarf2_locexpr_baton::size, size, store_unsigned_integer(), SYMBOL_ACLASS_INDEX, and SYMBOL_LOCATION_BATON.
Referenced by read_common_block().
static int maybe_queue_comp_unit (struct dwarf2_cu * dependent_cu, struct dwarf2_per_cu_data * per_cu, enum language pretend_language) [static]
Definition at line 7219 of file dwarf2read.c.
References dwarf2_per_cu_data::cu, dwarf2_cu::dies, dwarf2_add_dependence(), dwarf2_cu::last_used, queue_comp_unit(), dwarf2_per_cu_data::queued, and dwarf2_per_objfile::reading_partial_symbols.
Referenced by follow_die_offset(), follow_die_sig_1(), process_imported_unit_die(), and queue_and_load_dwo_tu().
static const char * namespace_name (struct die_info * die, int * is_anonymous, struct dwarf2_cu * cu) [static]
Definition at line 13558 of file dwarf2read.c.
References CP_ANONYMOUS_NAMESPACE_STR, dwarf2_extension(), dwarf2_name(), and name.
Referenced by gen_maybe_namespace_elt(), read_namespace(), and read_namespace_type().
static int need_gnat_info (struct dwarf2_cu * cu) [static]
Definition at line 17803 of file dwarf2read.c.
Referenced by set_die_type().
static struct symbol * new_symbol (struct die_info * die, struct type * type, struct dwarf2_cu * cu) [static, read]
Definition at line 17601 of file dwarf2read.c.
References new_symbol_full().
Referenced by dwarf2_add_field(), process_die(), process_enumeration_scope(), process_structure_scope(), read_common_block(), read_func_scope(), and read_namespace().
static struct symbol * new_symbol_full (struct die_info * die, struct type * type, struct dwarf2_cu * cu, struct symbol * space) [static, read]
Definition at line 17224 of file dwarf2read.c.
References _, add_symbol_to_list(), allocate_symbol(), ANOFFSET, objfile_type::builtin_core_addr, COMMON_BLOCK_DOMAIN, complaint(), context_stack_depth, cp_scan_for_anonymous_namespaces(), die_is_declaration(), die_type(), DW_ADDR, DW_UNSND, dwarf2_attr(), dwarf2_const_value(), dwarf2_full_name(), dwarf2_name(), dwarf2_physname(), dwarf_tag_name(), line_header::file_names, file_symbols, gdb_assert, symbol::ginfo, global_symbols, dwarf2_per_objfile::has_section_at_zero, symbol::hash_next, LABEL_DOMAIN, dwarf2_cu::language, language_ada, language_cplus, language_fortran, language_java, dwarf2_cu::line_header, dwarf2_cu::list_in_scope, LOC_BLOCK, LOC_COMMON_BLOCK, LOC_LABEL, LOC_OPTIMIZED_OUT, LOC_STATIC, LOC_TYPEDEF, LOC_UNRESOLVED, name, objfile_type::nodebug_data_symbol, line_header::num_file_names, dwarf2_cu::objfile, objfile::objfile_obstack, objfile_type(), OBJSTAT, dwarf2_cu::producer, SECT_OFF_TEXT, objfile::section_offsets, STRUCT_DOMAIN, SYMBOL_ACLASS_INDEX, SYMBOL_CLASS, SYMBOL_DOMAIN, symbol_get_demangled_name(), SYMBOL_INLINED, SYMBOL_IS_ARGUMENT, SYMBOL_LINE, SYMBOL_SEARCH_NAME, symbol_set_demangled_name(), SYMBOL_SET_LANGUAGE, SYMBOL_SET_NAMES, SYMBOL_SYMTAB, SYMBOL_TYPE, SYMBOL_VALUE_ADDRESS, symfile_complaints, objfile::template_symbols, type, TYPE_CODE, TYPE_CODE_VOID, TYPE_NAME, var_decode_location(), and VAR_DOMAIN.
Referenced by new_symbol(), and read_func_scope().
static void noop_record_line (struct subfile * subfile, int line, CORE_ADDR pc) [static]
Definition at line 16700 of file dwarf2read.c.
Referenced by dwarf_decode_lines_1().
static int offset_in_cu_p (const struct comp_unit_head * cu_header, sect_offset offset) [inline, static]
Definition at line 4146 of file dwarf2read.c.
References get_cu_length(), comp_unit_head::offset, and sect_offset::sect_off.
Referenced by find_partial_die(), follow_die_offset(), and read_call_site_scope().
static int offset_type_compare (const void * ap, const void * bp) [static]
Definition at line 21645 of file dwarf2read.c.
Referenced by uniquify_cu_indices().
static struct dwo_file* open_and_init_dwo_file (struct dwarf2_per_cu_data * per_cu, const char * dwo_name, const char * comp_dir) [static, read]
Definition at line 10150 of file dwarf2read.c.
References dwo_file::comp_dir, create_debug_types_hash_table(), create_dwo_cu(), dwo_file::cu, dwo_file::dbfd, discard_cleanups(), dwarf2_locate_dwo_sections(), dwarf2_read_debug, dwo_file::dwo_name, fprintf_unfiltered(), free_dwo_file_cleanup(), gdb_stdlog, make_cleanup(), objfile::objfile_obstack, OBSTACK_ZALLOC, open_dwo_file(), dwo_file::sections, and dwo_file::tus.
Referenced by lookup_dwo_cutu().
static struct dwp_file* open_and_init_dwp_file (void) [static, read]
Definition at line 10358 of file dwarf2read.c.
References _, allocate_dwp_loaded_cutus_table(), create_dwp_hash_table(), dwp_file::cus, dwp_file::dbfd, do_cleanups(), dwarf2_locate_common_dwp_sections(), dwarf2_locate_v2_dwp_sections(), dwarf2_read_debug, dwp_file::elf_sections, error(), fprintf_unfiltered(), gdb_stdlog, dwp_file::loaded_cus, dwp_file::loaded_tus, make_cleanup(), dwp_file::name, dwp_hash_table::nr_units, dwp_file::num_sections, objfile_name(), objfile::objfile_obstack, OBSTACK_CALLOC, OBSTACK_ZALLOC, open_dwp_file(), objfile::original_name, pulongest(), dwp_file::tus, dwp_hash_table::version, dwp_file::version, xfree(), and xstrprintf().
Referenced by get_dwp_file().
static bfd* open_dwo_file (const char * file_name, const char * comp_dir) [static]
Definition at line 10054 of file dwarf2read.c.
References debug_file_directory, try_open_dwop_file(), and xfree().
Referenced by open_and_init_dwo_file().
static bfd* open_dwp_file (const char * file_name) [static]
Definition at line 10325 of file dwarf2read.c.
References debug_file_directory, and try_open_dwop_file().
Referenced by open_and_init_dwp_file().
static void parse_macro_definition (struct macro_source_file * file, int line, const char * body) [static]
Definition at line 19825 of file dwarf2read.c.
References consume_improper_spaces(), copy_string(), dwarf2_macro_malformed_definition_complaint(), macro_define_function(), macro_define_object(), p, xfree(), xmalloc(), and xrealloc().
Referenced by dwarf_decode_macro_bytes().
static int partial_die_eq (const void * item_lhs, const void * item_rhs) [static]
Definition at line 21344 of file dwarf2read.c.
References partial_die_info::offset, and sect_offset::sect_off.
Referenced by load_partial_dies().
static char* partial_die_full_name (struct partial_die_info * pdi, struct dwarf2_cu * cu) [static]
Definition at line 6601 of file dwarf2read.c.
References dwarf2_full_name(), fixup_partial_die(), follow_die_ref(), partial_die_info::offset, partial_die_parent_scope(), sect_offset::sect_off, strchr(), typename_concat(), and attribute::u.
Referenced by add_partial_symbol().
static hashval_t partial_die_hash (const void * item) [static]
Definition at line 21333 of file dwarf2read.c.
References partial_die_info::offset, and sect_offset::sect_off.
Referenced by load_partial_dies().
static const char* partial_die_parent_scope (struct partial_die_info * pdi, struct dwarf2_cu * cu) [static]
Definition at line 6526 of file dwarf2read.c.
References _, dwarf2_cu::comp_unit_obstack, complaint(), partial_die_info::die_parent, find_partial_die(), fixup_partial_die(), dwarf2_cu::language, language_cplus, partial_die_info::offset, sect_offset::sect_off, partial_die_info::spec_offset, symfile_complaints, and typename_concat().
Referenced by partial_die_full_name().
static unsigned int peek_abbrev_code (bfd * abfd, const gdb_byte * info_ptr) [static]
Definition at line 6934 of file dwarf2read.c.
References read_unsigned_leb128().
Referenced by create_debug_types_hash_table(), init_cutu_and_read_dies(), init_cutu_and_read_dies_no_follow(), and read_cutu_die_from_dwo().
static struct abbrev_info* peek_die_abbrev (const gdb_byte * info_ptr, unsigned int * bytes_read, struct dwarf2_cu * cu) [static, read]
Definition at line 6947 of file dwarf2read.c.
References _, dwarf2_cu::abbrev_table, abbrev_table_lookup_abbrev(), error(), objfile::obfd, dwarf2_cu::objfile, and read_unsigned_leb128().
Referenced by load_partial_dies(), and skip_children().
static struct comp_unit_head* per_cu_header_read_in (struct comp_unit_head * cu_headerp, struct dwarf2_per_cu_data * per_cu) [static, read]
Definition at line 20819 of file dwarf2read.c.
References dwarf2_section_info::buffer, dwarf2_per_cu_data::cu, dwarf2_cu::header, memset(), objfile::obfd, dwarf2_per_cu_data::objfile, dwarf2_per_cu_data::offset, read_comp_unit_head(), sect_offset::sect_off, and dwarf2_per_cu_data::section.
Referenced by dwarf2_per_cu_addr_size(), dwarf2_per_cu_offset_size(), and dwarf2_per_cu_ref_addr_size().
static int per_cu_offset_and_type_eq (const void * item_lhs, const void * item_rhs) [static]
Definition at line 21157 of file dwarf2read.c.
References dwarf2_per_cu_offset_and_type::offset, dwarf2_per_cu_offset_and_type::per_cu, and sect_offset::sect_off.
Referenced by set_die_type().
static hashval_t per_cu_offset_and_type_hash (const void * item) [static]
Definition at line 21147 of file dwarf2read.c.
References dwarf2_per_cu_offset_and_type::offset, dwarf2_per_cu_offset_and_type::per_cu, and sect_offset::sect_off.
Referenced by set_die_type().
static void prepare_one_comp_unit (struct dwarf2_cu * cu, struct die_info * comp_unit_die, enum language pretend_language) [static]
Definition at line 20958 of file dwarf2read.c.
References DW_STRING, DW_UNSND, dwarf2_attr(), dwarf2_cu::language, language_def(), dwarf2_cu::language_defn, dwarf2_cu::producer, and set_cu_language().
Referenced by build_type_psymtabs_reader(), load_full_comp_unit_reader(), load_partial_comp_unit_reader(), process_psymtab_comp_unit_reader(), read_file_scope(), read_signatured_type_reader(), and read_type_unit_scope().
static void process_cu_includes (void) [static]
Definition at line 7714 of file dwarf2read.c.
References compute_symtab_includes(), dwarf2_per_cu_data::is_debug_types, VEC_free, and VEC_iterate.
Referenced by dw2_instantiate_symtab(), and dwarf2_read_symtab().
static void process_die (struct die_info * die, struct dwarf2_cu * cu) [static]
Definition at line 7949 of file dwarf2read.c.
References _, complaint(), dwarf_tag_name(), dwarf2_cu::language, language_fortran, new_symbol(), process_enumeration_scope(), process_imported_unit_die(), process_structure_scope(), read_call_site_scope(), read_common_block(), read_file_scope(), read_func_scope(), read_import_statement(), read_lexical_block_scope(), read_module(), read_namespace(), read_type_die(), read_type_unit_scope(), and symfile_complaints.
Referenced by inherit_abstract_dies(), process_enumeration_scope(), process_full_comp_unit(), process_full_type_unit(), process_structure_scope(), read_file_scope(), read_func_scope(), read_import_statement(), read_lexical_block_scope(), read_module(), read_namespace(), and read_type_unit_scope().
static void process_enumeration_scope (struct die_info * die, struct dwarf2_cu * cu) [static]
Definition at line 12988 of file dwarf2read.c.
References die_is_declaration(), DW_FIELD_ALLOC_CHUNK, dwarf2_name(), FIELD_BITSIZE, FIELD_NAME, FIELD_TYPE, gdb_assert, get_die_type(), dwarf2_per_cu_data::is_debug_types, memcpy(), name, new_symbol(), dwarf2_cu::per_cu, process_die(), read_enumeration_type(), sect_offset::sect_off, SET_FIELD_ENUMVAL, sibling_die(), SYMBOL_LINKAGE_NAME, SYMBOL_VALUE, TYPE_ALLOC, TYPE_FIELDS, TYPE_FLAG_ENUM, TYPE_NFIELDS, signatured_type::type_offset_in_section, TYPE_UNSIGNED, ULONGEST, xfree(), and xrealloc().
Referenced by process_die().
static void process_full_comp_unit (struct dwarf2_per_cu_data * per_cu, enum language pretend_language) [static]
Definition at line 7735 of file dwarf2read.c.
References ANOFFSET, buildsym_init(), symtab::call_site_htab, compute_delayed_physnames(), dwarf2_per_cu_data::cu, dwarf2_cu::dies, do_cleanups(), dwarf2_record_block_ranges(), end_symtab_from_static_block(), end_symtab_get_static_block(), symtab::epilogue_unwind_valid, file_symbols, fixup_go_packaging(), free_delayed_list(), get_scope_pc_bounds(), dwarf2_cu::language, symtab::language, language_c, language_def(), dwarf2_cu::language_defn, language_go, dwarf2_cu::list_in_scope, symtab::locations_valid, make_cleanup(), dwarf2_per_cu_data::objfile, process_die(), dwarf2_cu::producer, producer_is_gcc_ge_4(), dwarf2_per_cu_data::psymtab, dwarf2_per_cu_data::quick, partial_symtab::readin, really_free_pendings(), SECT_OFF_TEXT, objfile::section_offsets, partial_symtab::symtab, dwarf2_per_cu_quick_data::symtab, dwarf2_per_objfile::using_index, dwarf2_per_cu_data::v, and VEC_safe_push.
Referenced by process_queue().
static void process_full_type_unit (struct dwarf2_per_cu_data * per_cu, enum language pretend_language) [static]
Definition at line 7838 of file dwarf2read.c.
References augment_type_symtab(), buildsym_init(), compute_delayed_physnames(), dwarf2_per_cu_data::cu, dwarf2_cu::dies, do_cleanups(), end_expandable_symtab(), file_symbols, fixup_go_packaging(), free_delayed_list(), gdb_assert, dwarf2_per_cu_data::is_debug_types, dwarf2_cu::language, symtab::language, language_c, language_def(), dwarf2_cu::language_defn, language_go, dwarf2_cu::list_in_scope, make_cleanup(), dwarf2_per_cu_data::objfile, process_die(), dwarf2_per_cu_data::psymtab, dwarf2_per_cu_data::quick, partial_symtab::readin, really_free_pendings(), SECT_OFF_TEXT, partial_symtab::symtab, dwarf2_per_cu_quick_data::symtab, signatured_type::type_unit_group, dwarf2_per_objfile::using_index, and dwarf2_per_cu_data::v.
Referenced by process_queue().
static void process_imported_unit_die (struct die_info * die, struct dwarf2_cu * cu) [static]
Definition at line 7913 of file dwarf2read.c.
References _, dwarf2_attr(), dwarf2_find_containing_comp_unit(), dwarf2_get_ref_die_offset(), error(), dwarf2_per_cu_data::is_debug_types, dwarf2_per_cu_data::is_dwz, dwarf2_cu::language, load_full_comp_unit(), maybe_queue_comp_unit(), dwarf2_cu::objfile, objfile_name(), offset, dwarf2_cu::per_cu, and VEC_safe_push.
Referenced by process_die().
static void process_psymtab_comp_unit (struct dwarf2_per_cu_data * this_cu, int want_partial_unit, enum language pretend_language) [static]
Definition at line 6064 of file dwarf2read.c.
References age_cached_comp_units(), dwarf2_per_cu_data::cu, free_one_cached_comp_unit(), gdb_assert, init_cutu_and_read_dies(), dwarf2_per_cu_data::is_debug_types, process_psymtab_comp_unit_data::pretend_language, process_psymtab_comp_unit_reader(), and process_psymtab_comp_unit_data::want_partial_unit.
Referenced by dwarf2_build_psymtabs_hard(), and scan_partial_symbols().
static void process_psymtab_comp_unit_reader (const struct die_reader_specs * reader, const gdb_byte * info_ptr, struct die_info * comp_unit_die, int has_children, void * data) [static]
Definition at line 5928 of file dwarf2read.c.
References addrmap_set_empty(), ANOFFSET, create_partial_symtab(), die_reader_specs::cu, partial_symtab::dependencies, partial_symtab::dirname, DW_STRING, dwarf2_attr(), dwarf2_build_include_psymtabs(), dwarf2_find_base_address(), dwarf2_get_pc_bounds(), dwarf2_read_debug, file_symbols, partial_symtab::filename, fprintf_unfiltered(), gdb_assert, gdb_stdlog, get_objfile_arch(), objfile::global_psymbols, partial_symtab::globals_offset, partial_die_info::highpc, dwarf2_per_cu_data::is_debug_types, len, psymbol_allocation_list::list, dwarf2_cu::list_in_scope, load_partial_dies(), partial_die_info::lowpc, partial_symtab::n_global_syms, partial_symtab::n_static_syms, psymbol_allocation_list::next, partial_symtab::number_of_dependencies, dwarf2_cu::objfile, objfile::objfile_obstack, dwarf2_per_cu_data::offset, paddress(), dwarf2_cu::per_cu, prepare_one_comp_unit(), process_psymtab_comp_unit_data::pretend_language, dwarf2_per_cu_data::psymtab, objfile::psymtabs_addrmap, scan_partial_symbols(), sect_offset::sect_off, SECT_OFF_TEXT, objfile::section_offsets, sort_pst_symbols(), objfile::static_psymbols, partial_symtab::statics_offset, partial_symtab::texthigh, partial_symtab::textlow, dwarf2_per_cu_data::v, VEC_empty, VEC_free, VEC_iterate, VEC_length, and process_psymtab_comp_unit_data::want_partial_unit.
Referenced by process_psymtab_comp_unit().
static void process_queue (void) [static]
Definition at line 7259 of file dwarf2read.c.
References dwarf2_read_debug, fprintf_unfiltered(), gdb_stdlog, hex_string(), dwarf2_per_cu_data::is_debug_types, dwarf2_queue_item::next, objfile_name(), dwarf2_per_cu_data::offset, dwarf2_queue_item::per_cu, dwarf2_queue_item::pretend_language, process_full_comp_unit(), process_full_type_unit(), dwarf2_per_cu_data::psymtab, dwarf2_per_cu_data::queued, dwarf2_per_cu_data::quick, partial_symtab::readin, sect_offset::sect_off, signatured_type::signature, dwarf2_per_cu_quick_data::symtab, dwarf2_per_objfile::using_index, dwarf2_per_cu_data::v, and xfree().
Referenced by dw2_do_instantiate_symtab().
static void process_structure_scope (struct die_info * die, struct dwarf2_cu * cu) [static]
Definition at line 12721 of file dwarf2read.c.
References _, ALLOCATE_CPLUS_STRUCT_TYPE, complaint(), die_containing_type(), die_is_declaration(), do_cleanups(), dwarf2_add_field(), dwarf2_add_member_fn(), dwarf2_add_typedef(), dwarf2_attach_fields_to_type(), dwarf2_attach_fn_fields_to_type(), dwarf2_attr(), field_info::typedef_field_list::field, get_die_type(), HAVE_CPLUS_STRUCT, is_vtable_name(), dwarf2_cu::language, language_java, make_cleanup(), memcpy(), memset(), new_symbol(), field_info::typedef_field_list::next, field_info::nfields, field_info::nfnfields, null_cleanup(), dwarf2_cu::objfile, objfile::objfile_obstack, process_die(), dwarf2_cu::producer, quirk_gcc_member_function_pointer(), read_structure_type(), sibling_die(), symfile_complaints, type, TYPE_ALLOC, TYPE_CPLUS_REALLY_JAVA, TYPE_FIELD_NAME, TYPE_N_BASECLASSES, TYPE_N_TEMPLATE_ARGUMENTS, TYPE_NFIELDS, TYPE_TAG_NAME, TYPE_TEMPLATE_ARGUMENTS, TYPE_TYPEDEF_FIELD, TYPE_TYPEDEF_FIELD_ARRAY, TYPE_TYPEDEF_FIELD_COUNT, TYPE_VPTR_BASETYPE, TYPE_VPTR_FIELDNO, field_info::typedef_field_list, field_info::typedef_field_list_count, VEC, VEC_address, VEC_empty, VEC_free, VEC_length, and VEC_safe_push.
Referenced by process_die().
static int producer_is_gcc_lt_4_3 (struct dwarf2_cu * cu) [static]
Definition at line 8640 of file dwarf2read.c.
References check_producer().
Referenced by find_file_and_directory().
static int producer_is_gxx_lt_4_6 (struct dwarf2_cu * cu) [static]
Definition at line 11865 of file dwarf2read.c.
References check_producer().
Referenced by dwarf2_default_access_attribute().
static int producer_is_icc (struct dwarf2_cu * cu) [static]
Definition at line 12587 of file dwarf2read.c.
References check_producer().
Referenced by read_structure_type().
static int prototyped_function_p (struct die_info * die, struct dwarf2_cu * cu) [static]
Definition at line 13831 of file dwarf2read.c.
References DW_UNSND, dwarf2_attr(), dwarf2_cu::language, language_c, language_objc, language_opencl, dwarf2_cu::producer, and producer_is_realview().
Referenced by read_subroutine_type().
static const char* psymtab_include_file_name (const struct line_header * lh, int file_index, const struct partial_symtab * pst, const char * comp_dir) [static]
Definition at line 16623 of file dwarf2read.c.
References partial_symtab::dirname, line_header::file_names, partial_symtab::filename, line_header::include_dirs, make_cleanup(), line_header::file_entry::name, and xfree().
Referenced by dwarf_decode_lines().
static void psymtab_to_symtab_1 (struct partial_symtab * pst) [static]
Definition at line 7350 of file dwarf2read.c.
References partial_symtab::dependencies, dw2_do_instantiate_symtab(), partial_symtab::filename, fputs_filtered(), gdb_flush(), gdb_stdout, info_verbose, partial_symtab::number_of_dependencies, printf_filtered(), partial_symtab::read_symtab_private, partial_symtab::readin, partial_symtab::user, and wrap_here().
Referenced by dwarf2_read_symtab().
static void psymtabs_addrmap_cleanup (void * o) [static]
Definition at line 6190 of file dwarf2read.c.
References objfile::psymtabs_addrmap.
Referenced by dwarf2_build_psymtabs_hard().
static void queue_and_load_all_dwo_tus (struct dwarf2_per_cu_data * per_cu) [static]
Definition at line 10621 of file dwarf2read.c.
References dwarf2_per_cu_data::cu, dwo_unit::dwo_file, gdb_assert, get_dwp_file(), dwarf2_per_cu_data::is_debug_types, queue_and_load_dwo_tu(), and dwo_file::tus.
Referenced by dw2_do_instantiate_symtab().
static int queue_and_load_dwo_tu (void ** slot, void * info) [static]
Definition at line 10592 of file dwarf2read.c.
References dwarf2_per_cu_data::cu, dwarf2_cu::language, load_full_type_unit(), lookup_dwo_signatured_type(), maybe_queue_comp_unit(), signatured_type::per_cu, dwo_unit::signature, ULONGEST, and VEC_safe_push.
Referenced by queue_and_load_all_dwo_tus().
static void queue_comp_unit (struct dwarf2_per_cu_data * per_cu, enum language pretend_language) [static]
Definition at line 7190 of file dwarf2read.c.
References dwarf2_queue_item::next, dwarf2_queue_item::per_cu, dwarf2_queue_item::pretend_language, dwarf2_per_cu_data::queued, and xmalloc().
Referenced by dw2_do_instantiate_symtab(), and maybe_queue_comp_unit().
static void quirk_gcc_member_function_pointer (struct type * type, struct objfile * objfile) [static]
Definition at line 12546 of file dwarf2read.c.
References alloc_type(), new_type(), smash_to_method_type(), smash_to_methodptr_type(), TYPE_CODE, TYPE_CODE_FUNC, TYPE_CODE_PTR, TYPE_CODE_STRUCT, TYPE_FIELD_NAME, TYPE_FIELD_TYPE, TYPE_FIELDS, TYPE_NFIELDS, TYPE_TARGET_TYPE, and TYPE_VARARGS.
Referenced by process_structure_scope().
static unsigned int read_1_byte (bfd * abfd, const gdb_byte * buf) [static]
Definition at line 15683 of file dwarf2read.c.
Referenced by abbrev_table_read_table(), decode_locdesc(), dwarf_decode_line_header(), dwarf_decode_lines_1(), dwarf_decode_macro_bytes(), dwarf_decode_macros(), dwarf_parse_macro_header(), read_attribute_value(), read_comp_unit_head(), skip_form_bytes(), and skip_one_die().
static int read_1_signed_byte (bfd * abfd, const gdb_byte * buf) [static]
Definition at line 15689 of file dwarf2read.c.
Referenced by decode_locdesc(), and dwarf_decode_line_header().
static unsigned int read_2_bytes (bfd * abfd, const gdb_byte * buf) [static]
Definition at line 15695 of file dwarf2read.c.
Referenced by decode_locdesc(), dwarf_decode_line_header(), dwarf_decode_lines_1(), dwarf_parse_macro_header(), read_attribute_value(), read_comp_unit_head(), skip_form_bytes(), and skip_one_die().
static int read_2_signed_bytes (bfd * abfd, const gdb_byte * buf) [static]
Definition at line 15701 of file dwarf2read.c.
Referenced by decode_locdesc().
static unsigned int read_4_bytes (bfd * abfd, const gdb_byte * buf) [static]
Definition at line 15707 of file dwarf2read.c.
Referenced by create_dwo_unit_in_dwp_v1(), create_dwo_unit_in_dwp_v2(), create_dwp_hash_table(), decode_locdesc(), lookup_dwo_unit_in_dwp(), read_attribute_value(), skip_form_bytes(), and skip_one_die().
static int read_4_signed_bytes (bfd * abfd, const gdb_byte * buf) [static]
Definition at line 15713 of file dwarf2read.c.
Referenced by decode_locdesc().
static ULONGEST read_8_bytes (bfd * abfd, const gdb_byte * buf) [static]
Definition at line 15719 of file dwarf2read.c.
Referenced by decode_locdesc(), lookup_dwo_unit_in_dwp(), read_and_check_type_unit_head(), and read_attribute_value().
static sect_offset read_abbrev_offset (struct dwarf2_section_info * section, sect_offset offset) [static]
Definition at line 4334 of file dwarf2read.c.
References dwarf2_section_info::buffer, dwarf2_read_section(), get_section_bfd_owner(), read_initial_length(), read_offset_1(), and sect_offset::sect_off.
Referenced by build_type_unit_groups().
static CORE_ADDR read_addr_index (struct dwarf2_cu * cu, unsigned int addr_index) [static]
Definition at line 16070 of file dwarf2read.c.
References comp_unit_head::addr_size, dwarf2_cu::header, and read_addr_index_1().
Referenced by read_addr_index_from_leb128().
static CORE_ADDR read_addr_index_1 (unsigned int addr_index, ULONGEST addr_base, int addr_size) [static]
Definition at line 16045 of file dwarf2read.c.
References _, dwarf2_per_objfile::addr, dwarf2_section_info::buffer, dwarf2_read_section(), error(), objfile::obfd, objfile_name(), and dwarf2_section_info::size.
Referenced by dwarf2_read_addr_index(), and read_addr_index().
static CORE_ADDR read_addr_index_from_leb128 (struct dwarf2_cu * cu, const gdb_byte * info_ptr, unsigned int * bytes_read) [static]
Definition at line 16078 of file dwarf2read.c.
References objfile::obfd, dwarf2_cu::objfile, read_addr_index(), and read_unsigned_leb128().
Referenced by decode_locdesc(), read_attribute_value(), and var_decode_location().
static CORE_ADDR read_address (bfd * abfd, const gdb_byte * ptr, struct dwarf2_cu * cu, unsigned int * bytes_read) [static]
Definition at line 15725 of file dwarf2read.c.
References _, comp_unit_head::addr_size, dwarf2_cu::header, internal_error(), and comp_unit_head::signed_addr_p.
Referenced by decode_locdesc(), dwarf2_ranges_read(), dwarf2_record_block_ranges(), dwarf_decode_lines_1(), read_attribute_value(), and var_decode_location().
static const gdb_byte * read_and_check_comp_unit_head (struct comp_unit_head * header, struct dwarf2_section_info * section, struct dwarf2_section_info * abbrev_section, const gdb_byte * info_ptr, int is_debug_types_section) [static]
Definition at line 4271 of file dwarf2read.c.
References dwarf2_section_info::buffer, cu_offset::cu_off, error_check_comp_unit_head(), comp_unit_head::first_die_offset, get_section_bfd_owner(), comp_unit_head::offset, comp_unit_head::offset_size, read_comp_unit_head(), and sect_offset::sect_off.
Referenced by init_cutu_and_read_dies(), init_cutu_and_read_dies_no_follow(), and read_cutu_die_from_dwo().
static const gdb_byte* read_and_check_type_unit_head (struct comp_unit_head * header, struct dwarf2_section_info * section, struct dwarf2_section_info * abbrev_section, const gdb_byte * info_ptr, ULONGEST * signature, cu_offset * type_offset_in_tu) [static]
Definition at line 4300 of file dwarf2read.c.
References dwarf2_section_info::buffer, cu_offset::cu_off, error_check_comp_unit_head(), comp_unit_head::first_die_offset, get_section_bfd_owner(), comp_unit_head::offset, comp_unit_head::offset_size, read_8_bytes(), read_comp_unit_head(), read_offset_1(), and sect_offset::sect_off.
Referenced by create_debug_types_hash_table(), init_cutu_and_read_dies(), and read_cutu_die_from_dwo().
static enum dwarf_array_dim_ordering read_array_order (struct die_info * die, struct dwarf2_cu * cu) [static]
Definition at line 13205 of file dwarf2read.c.
References array_column_major, array_row_major, DW_SND, dwarf2_attr(), language_defn::la_array_ordering, dwarf2_cu::language, dwarf2_cu::language_defn, language_fortran, dwarf2_cu::producer, and strstr().
Referenced by read_array_type().
static struct type* read_array_type (struct die_info * die, struct dwarf2_cu * cu) [static, read]
Definition at line 13092 of file dwarf2read.c.
References _, objfile_type::builtin_int, complaint(), create_array_type(), create_range_type(), die_type(), do_cleanups(), DW_FIELD_ALLOC_CHUNK, DW_UNSND, dwarf2_attr(), dwarf2_name(), free_current_contents(), get_die_type(), make_cleanup(), make_vector_type(), name, null_cleanup(), dwarf2_cu::objfile, objfile_type(), read_array_order(), read_type_die(), set_descriptive_type(), set_die_type(), sibling_die(), symfile_complaints, type, TYPE_LENGTH, TYPE_NAME, and xrealloc().
Referenced by read_type_die_1().
static const gdb_byte * read_attribute (const struct die_reader_specs * reader, struct attribute * attr, struct attr_abbrev * abbrev, const gdb_byte * info_ptr) [static]
Definition at line 15672 of file dwarf2read.c.
References read_attribute_value().
Referenced by read_full_die_1(), read_partial_die(), and skip_one_die().
static const gdb_byte* read_attribute_value (const struct die_reader_specs * reader, struct attribute * attr, unsigned form, const gdb_byte * info_ptr) [static]
Definition at line 15452 of file dwarf2read.c.
References _, die_reader_specs::abfd, attr_form_is_ref(), complaint(), die_reader_specs::cu, dwarf_block::data, DW_ADDR, DW_BLOCK, DW_SIGNATURE, DW_SND, DW_STRING, DW_STRING_IS_CANONICAL, DW_UNSND, dwarf2_get_dwz_file(), dwarf_alloc_block(), dwarf_form_name(), die_reader_specs::dwo_file, error(), dwarf2_cu::header, hex_string(), dwarf2_per_cu_data::is_dwz, LONGEST, comp_unit_head::offset, dwarf2_cu::per_cu, read_1_byte(), read_2_bytes(), read_4_bytes(), read_8_bytes(), read_addr_index_from_leb128(), read_address(), read_direct_string(), read_indirect_string(), read_indirect_string_from_dwz(), read_n_bytes(), read_offset(), read_signed_leb128(), read_str_index(), read_unsigned_leb128(), sect_offset::sect_off, dwarf_block::size, symfile_complaints, ULONGEST, and comp_unit_head::version.
Referenced by read_attribute().
static struct type* read_base_type (struct die_info * die, struct dwarf2_cu * cu) [static, read]
Definition at line 14044 of file dwarf2read.c.
References _, code, complaint(), DW_UNSND, dwarf2_attr(), dwarf2_name(), dwarf_type_encoding_name(), encoding, init_type(), dwarf2_cu::language, language_ada, language_fortran, language_m2, language_pascal, name, dwarf2_cu::objfile, set_die_type(), size, symfile_complaints, type, TYPE_CODE_BOOL, TYPE_CODE_CHAR, TYPE_CODE_COMPLEX, TYPE_CODE_DECFLOAT, TYPE_CODE_FLT, TYPE_CODE_INT, TYPE_CODE_PTR, TYPE_CODE_VOID, TYPE_FLAG_UNSIGNED, TYPE_NAME, TYPE_NOSIGN, and TYPE_TARGET_TYPE.
Referenced by read_type_die_1().
static void read_call_site_scope (struct die_info * die, struct dwarf2_cu * cu) [static]
Definition at line 11060 of file dwarf2read.c.
References _, ANOFFSET, attr_form_is_block(), attr_form_is_ref(), CALL_SITE_PARAMETER_DWARF_REG, CALL_SITE_PARAMETER_FB_OFFSET, CALL_SITE_PARAMETER_PARAM_OFFSET, complaint(), core_addr_eq(), core_addr_hash(), dwarf2_locexpr_baton::data, die_is_declaration(), DW_ADDR, DW_BLOCK, DW_STRING, dwarf2_attr(), dwarf2_flag_true_p(), dwarf2_get_pc_bounds(), dwarf2_get_ref_die_offset(), dwarf2_physname(), dwarf_block_to_dwarf_reg(), dwarf_block_to_sp_offset(), follow_die_ref(), gdb_assert, get_die_type(), get_objfile_arch(), hashtab_obstack_allocate(), dwarf2_cu::header, memset(), dwarf2_cu::objfile, objfile_name(), objfile::objfile_obstack, offset, comp_unit_head::offset, offset_in_cu_p(), paddress(), call_site::parameter, call_site::parameter_count, call_site::pc, dwarf2_locexpr_baton::per_cu, dwarf2_cu::per_cu, call_site::per_cu, sect_offset::sect_off, SECT_OFF_TEXT, objfile::section_offsets, SET_FIELD_DWARF_BLOCK, SET_FIELD_PHYSADDR, SET_FIELD_PHYSNAME, sibling_die(), dwarf2_locexpr_baton::size, size, symfile_complaints, call_site::tail_call_next, call_site::target, TYPE_CODE, TYPE_CODE_FUNC, and TYPE_TAIL_CALL_LIST.
Referenced by process_die().
static LONGEST read_checked_initial_length_and_offset (bfd * abfd, const gdb_byte * buf, const struct comp_unit_head * cu_header, unsigned int * bytes_read, unsigned int * offset_size) [static]
Definition at line 15846 of file dwarf2read.c.
References _, complaint(), gdb_assert, comp_unit_head::initial_length_size, comp_unit_head::length, LONGEST, read_initial_length(), and symfile_complaints.
Referenced by dwarf_decode_line_header().
static void read_common_block (struct die_info * die, struct dwarf2_cu * cu) [static]
Definition at line 13340 of file dwarf2read.c.
References _, attr_form_is_block(), attr_form_is_constant(), attr_form_is_section_offset(), common_block, complaint(), common_block::contents, dwarf2_attr(), dwarf2_complex_location_expr_complaint(), dwarf2_invalid_attrib_class_complaint(), mark_common_block_symbol_computed(), memset(), common_block::n_entries, new_symbol(), dwarf2_cu::objfile, objfile_name(), objfile::objfile_obstack, sibling_die(), size, SYMBOL_VALUE_COMMON_BLOCK, and symfile_complaints.
Referenced by process_die().
static const gdb_byte* read_comp_unit_head (struct comp_unit_head * cu_header, const gdb_byte * info_ptr, bfd * abfd) [static]
Definition at line 4190 of file dwarf2read.c.
References _, comp_unit_head::abbrev_offset, comp_unit_head::addr_size, comp_unit_head::initial_length_size, internal_error(), comp_unit_head::length, comp_unit_head::offset_size, read_1_byte(), read_2_bytes(), read_initial_length(), read_offset(), sect_offset::sect_off, comp_unit_head::signed_addr_p, and comp_unit_head::version.
Referenced by per_cu_header_read_in(), read_and_check_comp_unit_head(), and read_and_check_type_unit_head().
static void read_comp_units_from_section (struct objfile * objfile, struct dwarf2_section_info * section, unsigned int is_dwz, int * n_allocated, int * n_comp_units, struct dwarf2_per_cu_data *** all_comp_units) [static]
Definition at line 6308 of file dwarf2read.c.
References dwarf2_section_info::buffer, dwarf2_read_debug, dwarf2_read_section(), fprintf_unfiltered(), gdb_stdlog, get_section_bfd_owner(), get_section_file_name(), get_section_name(), dwarf2_per_cu_data::is_dwz, dwarf2_per_cu_data::length, memset(), dwarf2_per_cu_data::objfile, objfile::objfile_obstack, offset, dwarf2_per_cu_data::offset, read_initial_length(), sect_offset::sect_off, dwarf2_per_cu_data::section, dwarf2_section_info::size, and xrealloc().
Referenced by create_all_comp_units().
static int read_cutu_die_from_dwo (struct dwarf2_per_cu_data * this_cu, struct dwo_unit * dwo_unit, int abbrev_table_provided, struct die_info * stub_comp_unit_die, const char * stub_comp_dir, struct die_reader_specs * result_reader, const gdb_byte ** result_info_ptr, struct die_info ** result_comp_unit_die, int * result_has_children) [static]
Definition at line 4892 of file dwarf2read.c.
References _, dwo_sections::abbrev, dwarf2_section_info::buffer, die_reader_specs::comp_dir, dwarf2_cu::comp_unit_obstack, dwarf2_per_cu_data::cu, cu_offset::cu_off, dump_die(), DW_STRING, DW_STRING_IS_CANONICAL, DW_UNSND, dwarf2_attr(), dwarf2_die_debug, dwarf2_free_abbrev_table(), dwarf2_read_abbrevs(), dwarf2_read_section(), dwo_unit::dwo_file, error(), fprintf_unfiltered(), gdb_assert, gdb_stdlog, get_cu_length(), get_section_bfd_owner(), get_section_name(), dwarf2_cu::header, hex_string(), init_cu_die_reader(), dwarf2_per_cu_data::is_debug_types, dwo_unit::length, make_cleanup(), comp_unit_head::offset, dwo_unit::offset, peek_abbrev_code(), read_and_check_comp_unit_head(), read_and_check_type_unit_head(), read_full_die_1(), sect_offset::sect_off, dwo_unit::section, dwo_file::sections, signatured_type::signature, signatured_type::type_offset_in_section, signatured_type::type_offset_in_tu, dwo_unit::type_offset_in_tu, and ULONGEST.
Referenced by init_cutu_and_read_dies(), and init_tu_and_read_dwo_dies().
static struct die_info* read_die_and_children (const struct die_reader_specs * reader, const gdb_byte * info_ptr, const gdb_byte ** new_info_ptr, struct die_info * parent) [static, read]
Definition at line 14333 of file dwarf2read.c.
References die_reader_specs::cu, read_die_and_siblings_1(), read_full_die_1(), and store_in_ref_table().
Referenced by read_die_and_siblings_1().
static struct die_info * read_die_and_siblings (const struct die_reader_specs * reader, const gdb_byte * info_ptr, const gdb_byte ** new_info_ptr, struct die_info * parent) [static, read]
Definition at line 14405 of file dwarf2read.c.
References die_reader_specs::abfd, dwarf2_section_info::buffer, die_reader_specs::die_section, dump_die(), dwarf2_die_debug, fprintf_unfiltered(), gdb_stdlog, get_section_name(), and read_die_and_siblings_1().
Referenced by load_full_comp_unit_reader(), and read_signatured_type_reader().
static struct die_info * read_die_and_siblings_1 (const struct die_reader_specs * reader, const gdb_byte * info_ptr, const gdb_byte ** new_info_ptr, struct die_info * parent) [static, read]
Definition at line 14368 of file dwarf2read.c.
References read_die_and_children().
Referenced by read_die_and_children(), and read_die_and_siblings().
static const char * read_direct_string (bfd * abfd, const gdb_byte * buf, unsigned int * bytes_read_ptr) [static]
Definition at line 15914 of file dwarf2read.c.
References gdb_assert, and HOST_CHAR_BIT.
Referenced by dwarf_decode_line_header(), dwarf_decode_lines_1(), dwarf_decode_macro_bytes(), dwarf_decode_macros(), read_attribute_value(), skip_form_bytes(), and skip_one_die().
static struct type* read_enumeration_type (struct die_info * die, struct dwarf2_cu * cu) [static, read]
Definition at line 12933 of file dwarf2read.c.
References alloc_type(), die_is_declaration(), DW_UNSND, dwarf2_attr(), dwarf2_attr_no_follow(), dwarf2_full_name(), get_DW_AT_signature_type(), name, dwarf2_cu::objfile, set_die_type(), type, TYPE_CODE, TYPE_CODE_ENUM, TYPE_LENGTH, TYPE_STUB, and TYPE_TAG_NAME.
Referenced by process_enumeration_scope(), and read_type_die_1().
static void read_file_scope (struct die_info * die, struct dwarf2_cu * cu) [static]
Definition at line 8723 of file dwarf2read.c.
References _, ANOFFSET, complaint(), do_cleanups(), DW_UNSND, dwarf2_attr(), dwarf2_start_symtab(), dwarf_decode_macros(), find_file_and_directory(), get_scope_pc_bounds(), handle_DW_AT_stmt_list(), dwarf2_cu::language, language_opencl, dwarf2_cu::line_header, make_cleanup(), null_cleanup(), objfile::obfd, prepare_one_comp_unit(), process_die(), dwarf2_cu::producer, SECT_OFF_TEXT, objfile::section_offsets, set_cu_language(), sibling_die(), strstr(), and symfile_complaints.
Referenced by process_die().
static const gdb_byte * read_full_die (const struct die_reader_specs * reader, struct die_info ** diep, const gdb_byte * info_ptr, int * has_children) [static]
Definition at line 14487 of file dwarf2read.c.
References die_reader_specs::abfd, dwarf2_section_info::buffer, die_reader_specs::die_section, dump_die(), dwarf2_die_debug, fprintf_unfiltered(), gdb_stdlog, get_section_name(), and read_full_die_1().
Referenced by init_cutu_and_read_dies(), and init_cutu_and_read_dies_no_follow().
static const gdb_byte * read_full_die_1 (const struct die_reader_specs * reader, struct die_info ** diep, const gdb_byte * info_ptr, int * has_children, int num_extra_attrs) [static]
Definition at line 14435 of file dwarf2read.c.
References _, dwarf2_cu::abbrev_table, abbrev_table_lookup_abbrev(), die_reader_specs::abfd, abbrev_info::attrs, die_reader_specs::buffer, die_reader_specs::cu, dwarf_alloc_die(), error(), abbrev_info::has_children, abbrev_info::num_attrs, offset, read_attribute(), read_unsigned_leb128(), sect_offset::sect_off, and abbrev_info::tag.
Referenced by read_cutu_die_from_dwo(), read_die_and_children(), and read_full_die().
static void read_func_scope (struct die_info * die, struct dwarf2_cu * cu) [static]
Definition at line 10827 of file dwarf2read.c.
References _, allocate_template_symbol(), ANOFFSET, template_symbol::base, block_set_scope(), complaint(), determine_prefix(), die_specification(), DW_UNSND, dwarf2_attr(), dwarf2_get_pc_bounds(), dwarf2_name(), dwarf2_record_block_ranges(), dwarf2_symbol_mark_computed(), file_symbols, finish_block(), gdb_assert, inherit_abstract_dies(), symbol::is_cplus_template_function, dwarf2_cu::language, language_cplus, language_fortran, dwarf2_cu::list_in_scope, local_symbols, memcpy(), name, new_symbol(), new_symbol_full(), dwarf2_cu::objfile, objfile::objfile_obstack, outermost_context_p, pop_context(), process_die(), push_context(), read_lexical_block_scope(), read_type_die(), SECT_OFF_TEXT, objfile::section_offsets, sibling_die(), symfile_complaints, using_directives, VEC, VEC_address, VEC_empty, VEC_free, VEC_length, and VEC_safe_push.
Referenced by process_die().
static void read_import_statement (struct die_info * die, struct dwarf2_cu * cu) [static]
Definition at line 8481 of file dwarf2read.c.
References _, complaint(), cp_add_using_directive(), determine_prefix(), do_cleanups(), dwarf2_attr(), dwarf2_name(), dwarf_tag_name(), follow_die_ref_or_sig(), dwarf2_cu::language, language_fortran, make_cleanup(), obconcat(), dwarf2_cu::objfile, objfile_name(), objfile::objfile_obstack, process_die(), sibling_die(), symfile_complaints, VEC, VEC_cleanup, and VEC_safe_push.
Referenced by process_die().
static int read_index_from_section (struct objfile * objfile, const char * filename, int deprecated_ok, struct dwarf2_section_info * section, struct mapped_index * map, const gdb_byte ** cu_list, offset_type * cu_list_elements, const gdb_byte ** types_list, offset_type * types_list_elements) [static]
Definition at line 2970 of file dwarf2read.c.
References _, mapped_index::address_table, mapped_index::address_table_size, dwarf2_section_info::buffer, mapped_index::constant_pool, dwarf2_read_section(), dwarf2_section_empty_p(), get_section_flags(), MAYBE_SWAP, dwarf2_section_info::size, mapped_index::symbol_table, mapped_index::symbol_table_slots, mapped_index::total_size, version, mapped_index::version, and warning().
Referenced by dwarf2_read_index().
static const char * read_indirect_string (bfd * abfd, const gdb_byte * buf, const struct comp_unit_head * cu_header, unsigned int * bytes_read_ptr) [static]
Definition at line 15972 of file dwarf2read.c.
References LONGEST, read_indirect_string_at_offset(), and read_offset().
Referenced by read_attribute_value().
static const char* read_indirect_string_at_offset (bfd * abfd, LONGEST str_offset) [static]
Definition at line 15931 of file dwarf2read.c.
References _, dwarf2_section_info::buffer, dwarf2_read_section(), error(), gdb_assert, HOST_CHAR_BIT, dwarf2_section_info::size, and dwarf2_per_objfile::str.
Referenced by dwarf_decode_macro_bytes(), and read_indirect_string().
static const char * read_indirect_string_from_dwz (struct dwz_file * dwz, LONGEST str_offset) [static]
Definition at line 15953 of file dwarf2read.c.
References _, dwarf2_section_info::buffer, dwarf2_read_section(), dwz_file::dwz_bfd, error(), gdb_assert, HOST_CHAR_BIT, dwarf2_section_info::size, and dwz_file::str.
Referenced by dwarf_decode_macro_bytes(), and read_attribute_value().
static LONGEST read_initial_length (bfd * abfd, const gdb_byte * buf, unsigned int * bytes_read) [static]
Definition at line 15814 of file dwarf2read.c.
References comp_unit_head::length, and LONGEST.
Referenced by read_abbrev_offset(), read_checked_initial_length_and_offset(), read_comp_unit_head(), and read_comp_units_from_section().
static void read_lexical_block_scope (struct die_info * die, struct dwarf2_cu * cu) [static]
Definition at line 11003 of file dwarf2read.c.
References ANOFFSET, dwarf2_get_pc_bounds(), dwarf2_record_block_ranges(), finish_block(), local_symbols, dwarf2_cu::objfile, pop_context(), process_die(), push_context(), SECT_OFF_TEXT, objfile::section_offsets, sibling_die(), and using_directives.
Referenced by process_die(), and read_func_scope().
static void read_module (struct die_info * die, struct dwarf2_cu * cu) [static]
Definition at line 13542 of file dwarf2read.c.
References process_die(), and sibling_die().
Referenced by process_die().
static struct type * read_module_type (struct die_info * die, struct dwarf2_cu * cu) [static, read]
Definition at line 13520 of file dwarf2read.c.
References _, complaint(), dwarf2_name(), init_type(), dwarf2_cu::objfile, set_die_type(), symfile_complaints, type, TYPE_CODE_MODULE, TYPE_NAME, and TYPE_TAG_NAME.
Referenced by read_type_die_1().
static const gdb_byte * read_n_bytes (bfd * abfd, const gdb_byte * buf, unsigned int size) [static]
Definition at line 15904 of file dwarf2read.c.
References gdb_assert, and HOST_CHAR_BIT.
Referenced by read_attribute_value().
static void read_namespace (struct die_info * die, struct dwarf2_cu * cu) [static]
Definition at line 13477 of file dwarf2read.c.
References cp_add_using_directive(), determine_prefix(), dwarf2_attr(), namespace_name(), new_symbol(), dwarf2_cu::objfile, objfile::objfile_obstack, process_die(), read_type_die(), sibling_die(), type, and TYPE_NAME.
Referenced by process_die().
static struct type* read_namespace_type (struct die_info * die, struct dwarf2_cu * cu) [static, read]
Definition at line 13435 of file dwarf2read.c.
References determine_prefix(), dwarf2_attr(), dwarf2_extension(), init_type(), name, namespace_name(), dwarf2_cu::objfile, objfile::objfile_obstack, read_type_die(), set_die_type(), type, TYPE_CODE_NAMESPACE, TYPE_NAME, TYPE_TAG_NAME, and typename_concat().
Referenced by read_type_die_1().
static LONGEST read_offset (bfd * abfd, const gdb_byte * buf, const struct comp_unit_head * cu_header, unsigned int * bytes_read) [static]
Definition at line 15869 of file dwarf2read.c.
References LONGEST, offset, comp_unit_head::offset_size, and read_offset_1().
Referenced by read_attribute_value(), read_comp_unit_head(), read_indirect_string(), and unpack_value_bits_as_long_1().
static LONGEST read_offset_1 (bfd * abfd, const gdb_byte * buf, unsigned int offset_size) [static]
Definition at line 15882 of file dwarf2read.c.
References _, internal_error(), and LONGEST.
Referenced by dwarf_decode_line_header(), dwarf_decode_macro_bytes(), read_abbrev_offset(), read_and_check_type_unit_head(), and read_offset().
static const gdb_byte * read_partial_die (const struct die_reader_specs * reader, struct partial_die_info * part_die, struct abbrev_info * abbrev, unsigned int abbrev_len, const gdb_byte * info_ptr) [static]
Definition at line 15018 of file dwarf2read.c.
References _, attr_form_is_block(), attr_form_is_section_offset(), abbrev_info::attrs, die_reader_specs::buffer, complaint(), die_reader_specs::cu, partial_die_info::d, DW_ADDR, DW_BLOCK, DW_STRING, DW_UNSND, dwarf2_canonicalize_name(), dwarf2_complex_location_expr_complaint(), dwarf2_get_ref_die_offset(), dwarf2_invalid_attrib_class_complaint(), get_objfile_arch(), abbrev_info::has_children, dwarf2_per_objfile::has_section_at_zero, partial_die_info::highpc, dwarf2_per_cu_data::is_dwz, dwarf2_cu::language, language_ada, language_fortran, language_of_main, partial_die_info::lowpc, memset(), abbrev_info::num_attrs, dwarf2_cu::objfile, objfile_name(), objfile::objfile_obstack, partial_die_info::offset, paddress(), dwarf2_cu::per_cu, read_attribute(), sect_offset::sect_off, set_main_name(), partial_die_info::sibling, partial_die_info::spec_offset, symfile_complaints, and abbrev_info::tag.
Referenced by load_partial_dies().
static struct type* read_set_type (struct die_info * die, struct dwarf2_cu * cu) [static, read]
Definition at line 13240 of file dwarf2read.c.
References create_set_type(), die_type(), DW_UNSND, dwarf2_attr(), get_die_type(), set_die_type(), set_type(), and TYPE_LENGTH.
Referenced by read_type_die_1().
static void read_signatured_type (struct signatured_type * sig_type) [static]
Definition at line 19402 of file dwarf2read.c.
References dwarf2_per_cu_data::cu, gdb_assert, init_cutu_and_read_dies(), dwarf2_per_cu_data::is_debug_types, signatured_type::per_cu, read_signatured_type_reader(), and dwarf2_per_cu_data::tu_read.
Referenced by follow_die_sig_1(), and load_full_type_unit().
static void read_signatured_type_reader (const struct die_reader_specs * reader, const gdb_byte * info_ptr, struct die_info * comp_unit_die, int has_children, void * data) [static]
Definition at line 19364 of file dwarf2read.c.
References dwarf2_cu::comp_unit_obstack, die_reader_specs::cu, die_eq(), dwarf2_cu::die_hash, die_hash(), dwarf2_cu::dies, dummy_obstack_deallocate(), gdb_assert, hashtab_obstack_allocate(), dwarf2_cu::header, language_minimal, comp_unit_head::length, prepare_one_comp_unit(), and read_die_and_siblings().
Referenced by read_signatured_type().
static LONGEST read_signed_leb128 (bfd * abfd, const gdb_byte * buf, unsigned int * bytes_read_ptr) [static]
Definition at line 16011 of file dwarf2read.c.
References LONGEST.
Referenced by decode_locdesc(), dwarf_decode_lines_1(), and read_attribute_value().
static const char * read_str_index (const struct die_reader_specs * reader, struct dwarf2_cu * cu, ULONGEST str_index) [static]
Definition at line 16170 of file dwarf2read.c.
References _, dwarf2_section_info::buffer, dwarf2_read_section(), die_reader_specs::dwo_file, error(), dwarf2_cu::header, objfile::obfd, objfile_name(), comp_unit_head::offset, comp_unit_head::offset_size, sect_offset::sect_off, dwo_file::sections, dwarf2_section_info::size, dwo_sections::str, dwo_sections::str_offsets, and ULONGEST.
Referenced by read_attribute_value().
static struct type* read_structure_type (struct die_info * die, struct dwarf2_cu * cu) [static, read]
Definition at line 12613 of file dwarf2read.c.
References alloc_type(), die_is_declaration(), DW_UNSND, dwarf2_attr(), dwarf2_attr_no_follow(), dwarf2_full_name(), dwarf2_name(), get_die_type(), get_DW_AT_signature_type(), INIT_CPLUS_SPECIFIC, dwarf2_cu::language, language_cplus, language_java, name, dwarf2_cu::objfile, dwarf2_cu::producer, producer_is_icc(), producer_is_realview(), set_descriptive_type(), set_die_type(), type, TYPE_CODE, TYPE_CODE_CLASS, TYPE_CODE_STRUCT, TYPE_CODE_UNION, TYPE_DECLARED_CLASS, TYPE_LENGTH, TYPE_NAME, TYPE_STUB, TYPE_STUB_SUPPORTED, and TYPE_TAG_NAME.
Referenced by process_structure_scope(), and read_type_die_1().
static struct type* read_subrange_type (struct die_info * die, struct dwarf2_cu * cu) [static, read]
Definition at line 14140 of file dwarf2read.c.
References _, attr_form_is_block(), attr_form_is_ref(), objfile_type::builtin_int, objfile_type::builtin_long, objfile_type::builtin_long_long, check_typedef(), complaint(), create_range_type(), die_type(), DW_UNSND, dwarf2_attr(), dwarf2_get_attr_constant_value(), dwarf2_name(), gdbarch_addr_bit(), get_die_type(), get_objfile_arch(), dwarf2_cu::header, dwarf2_cu::language, language_ada, language_c, language_cplus, language_d, language_fortran, language_java, language_m2, language_objc, language_pascal, LONGEST, name, dwarf2_cu::objfile, objfile_name(), objfile_type(), set_descriptive_type(), set_die_type(), symfile_complaints, TYPE_CODE, TYPE_CODE_VOID, TYPE_HIGH_BOUND_UNDEFINED, TYPE_LENGTH, TYPE_NAME, TYPE_UNSIGNED, and comp_unit_head::version.
Referenced by read_type_die_1().
static struct type* read_subroutine_type (struct die_info * die, struct dwarf2_cu * cu) [static, read]
Definition at line 13870 of file dwarf2read.c.
References objfile_type::builtin_void, die_type(), DW_UNSND, dwarf2_attr(), dwarf2_name(), follow_die_ref(), get_die_type(), dwarf2_cu::language, language_cplus, language_java, lookup_function_type(), make_cv_type(), dwarf2_cu::objfile, objfile_type(), dwarf2_cu::producer, prototyped_function_p(), set_die_type(), sibling_die(), strstr(), type, TYPE_CALLING_CONVENTION, TYPE_CONST, TYPE_FIELD_ARTIFICIAL, TYPE_FIELD_TYPE, TYPE_FIELDS, TYPE_NFIELDS, TYPE_PROTOTYPED, TYPE_VARARGS, TYPE_VOLATILE, and TYPE_ZALLOC.
Referenced by read_type_die_1().
static struct type* read_tag_const_type (struct die_info * die, struct dwarf2_cu * cu) [static, read]
Definition at line 13714 of file dwarf2read.c.
References copy_type(), die_type(), get_die_type(), make_cv_type(), set_die_type(), TYPE_CODE, TYPE_CODE_ARRAY, TYPE_TARGET_TYPE, and TYPE_VOLATILE.
Referenced by read_type_die_1().
static struct type* read_tag_pointer_type (struct die_info * die, struct dwarf2_cu * cu) [static, read]
Definition at line 13587 of file dwarf2read.c.
References _, comp_unit_head::addr_size, complaint(), die_type(), DW_UNSND, dwarf2_attr(), gdb_assert, gdbarch_address_class_type_flags(), gdbarch_address_class_type_flags_p(), get_die_type(), get_objfile_arch(), dwarf2_cu::header, lookup_pointer_type(), make_type_with_address_space(), dwarf2_cu::objfile, set_die_type(), symfile_complaints, type, TYPE_INSTANCE_FLAG_ADDRESS_CLASS_ALL, and TYPE_LENGTH.
Referenced by read_type_die_1().
static struct type* read_tag_ptr_to_member_type (struct die_info * die, struct dwarf2_cu * cu) [static, read]
Definition at line 13652 of file dwarf2read.c.
References alloc_type(), check_typedef(), die_containing_type(), die_type(), get_die_type(), lookup_memberptr_type(), lookup_methodptr_type(), new_type(), dwarf2_cu::objfile, set_die_type(), smash_to_method_type(), type, TYPE_CODE, TYPE_CODE_FUNC, TYPE_CODE_METHOD, TYPE_FIELDS, TYPE_NFIELDS, TYPE_TARGET_TYPE, and TYPE_VARARGS.
Referenced by read_type_die_1().
static struct type* read_tag_reference_type (struct die_info * die, struct dwarf2_cu * cu) [static, read]
Definition at line 13687 of file dwarf2read.c.
References comp_unit_head::addr_size, die_type(), DW_UNSND, dwarf2_attr(), get_die_type(), dwarf2_cu::header, lookup_reference_type(), set_die_type(), type, and TYPE_LENGTH.
Referenced by read_type_die_1().
static struct type* read_tag_restrict_type (struct die_info * die, struct dwarf2_cu * cu) [static, read]
Definition at line 13771 of file dwarf2read.c.
References die_type(), get_die_type(), make_restrict_type(), and set_die_type().
Referenced by read_type_die_1().
static struct type* read_tag_string_type (struct die_info * die, struct dwarf2_cu * cu) [static, read]
Definition at line 13792 of file dwarf2read.c.
References objfile_type::builtin_int, create_range_type(), create_string_type(), DW_UNSND, dwarf2_attr(), get_objfile_arch(), dwarf2_cu::language_defn, language_string_char_type(), dwarf2_cu::objfile, objfile_type(), set_die_type(), and type.
Referenced by read_type_die_1().
static struct type* read_tag_volatile_type (struct die_info * die, struct dwarf2_cu * cu) [static, read]
Definition at line 13753 of file dwarf2read.c.
References die_type(), get_die_type(), make_cv_type(), set_die_type(), and TYPE_CONST.
Referenced by read_type_die_1().
static struct type * read_type_die (struct die_info * die, struct dwarf2_cu * cu) [static, read]
Definition at line 17965 of file dwarf2read.c.
References get_die_type(), and read_type_die_1().
Referenced by determine_prefix(), dwarf2_add_member_fn(), dwarf2_add_typedef(), dwarf2_compute_name(), get_DW_AT_signature_type(), get_signatured_type(), lookup_die_type(), process_die(), read_array_type(), read_func_scope(), read_namespace(), and read_namespace_type().
static struct type * read_type_die_1 (struct die_info * die, struct dwarf2_cu * cu) [static, read]
Definition at line 17980 of file dwarf2read.c.
References _, complaint(), dwarf_tag_name(), read_array_type(), read_base_type(), read_enumeration_type(), read_module_type(), read_namespace_type(), read_set_type(), read_structure_type(), read_subrange_type(), read_subroutine_type(), read_tag_const_type(), read_tag_pointer_type(), read_tag_ptr_to_member_type(), read_tag_reference_type(), read_tag_restrict_type(), read_tag_string_type(), read_tag_volatile_type(), read_typedef(), read_unspecified_type(), and symfile_complaints.
Referenced by read_type_die().
static void read_type_unit_scope (struct die_info * die, struct dwarf2_cu * cu) [static]
Definition at line 8923 of file dwarf2read.c.
References language_minimal, prepare_one_comp_unit(), process_die(), setup_type_unit_groups(), and sibling_die().
Referenced by process_die().
static struct type* read_typedef (struct die_info * die, struct dwarf2_cu * cu) [static, read]
Definition at line 14013 of file dwarf2read.c.
References _, complaint(), die_type(), dwarf2_full_name(), init_type(), name, dwarf2_cu::objfile, objfile_name(), set_die_type(), symfile_complaints, TYPE_CODE_TYPEDEF, TYPE_FLAG_TARGET_STUB, TYPE_NAME, and TYPE_TARGET_TYPE.
Referenced by read_type_die_1().
static ULONGEST read_unsigned_leb128 (bfd * abfd, const gdb_byte * buf, unsigned int * bytes_read_ptr) [static]
Definition at line 15982 of file dwarf2read.c.
References ULONGEST.
Referenced by abbrev_table_read_table(), decode_locdesc(), dwarf_decode_line_header(), dwarf_decode_lines_1(), dwarf_decode_macro_bytes(), dwarf_decode_macros(), dwarf_parse_macro_header(), peek_abbrev_code(), peek_die_abbrev(), read_addr_index_from_leb128(), read_attribute_value(), read_full_die_1(), skip_form_bytes(), skip_one_die(), and skip_unknown_opcode().
static struct type* read_unspecified_type (struct die_info * die, struct dwarf2_cu * cu) [static, read]
Definition at line 14314 of file dwarf2read.c.
References dwarf2_name(), init_type(), dwarf2_cu::objfile, set_die_type(), type, TYPE_CODE_VOID, and TYPE_NAME.
Referenced by read_type_die_1().
static void recursively_compute_inclusions (VEC(symtab_ptr)** result, htab_t all_children, htab_t all_type_symtabs, struct dwarf2_per_cu_data * per_cu, struct symtab * immediate_parent) [static]
Definition at line 7605 of file dwarf2read.c.
References get_symtab(), dwarf2_per_cu_data::is_debug_types, symtab::user, VEC_iterate, and VEC_safe_push.
Referenced by compute_symtab_includes().
static struct symtab* recursively_find_pc_sect_symtab (struct symtab * symtab, CORE_ADDR pc) [static, read]
Definition at line 3923 of file dwarf2read.c.
References BLOCKVECTOR, blockvector_contains_pc(), and symtab::includes.
Referenced by dw2_find_pc_sect_symtab().
static void recursively_write_psymbols (struct objfile * objfile, struct partial_symtab * psymtab, struct mapped_symtab * symtab, htab_t psyms_seen, offset_type cu_index) [static]
Definition at line 22049 of file dwarf2read.c.
References partial_symtab::dependencies, objfile::global_psymbols, partial_symtab::globals_offset, psymbol_allocation_list::list, partial_symtab::n_global_syms, partial_symtab::n_static_syms, partial_symtab::number_of_dependencies, objfile::static_psymbols, partial_symtab::statics_offset, partial_symtab::user, and write_psymbols().
Referenced by write_psymtabs_to_index().
static void save_gdb_index_command (char * arg, int from_tty) [static]
Definition at line 22266 of file dwarf2read.c.
References _, ALL_OBJFILES, dwarf2_objfile_data_key, error(), exception_fprintf(), gdb_stderr, objfile_name(), gdb_exception::reason, RETURN_MASK_ERROR, TRY_CATCH, and write_psymtabs_to_index().
static void scan_partial_symbols (struct partial_die_info * first_die, CORE_ADDR * lowpc, CORE_ADDR * highpc, int need_pc, struct dwarf2_cu * cu) [static]
Definition at line 6405 of file dwarf2read.c.
References _, add_partial_enumeration(), add_partial_module(), add_partial_namespace(), add_partial_subprogram(), add_partial_symbol(), partial_die_info::d, partial_die_info::die_sibling, dwarf2_find_containing_comp_unit(), error(), fixup_partial_die(), dwarf2_per_cu_data::is_debug_types, dwarf2_cu::language, dwarf2_cu::objfile, objfile_name(), dwarf2_cu::per_cu, process_psymtab_comp_unit(), dwarf2_per_cu_data::psymtab, dwarf2_per_cu_data::v, and VEC_safe_push.
Referenced by add_partial_module(), add_partial_namespace(), build_type_psymtabs_reader(), and process_psymtab_comp_unit_reader().
static int section_is_p (const char * section_name, const struct dwarf2_section_names * names) [static]
Definition at line 2058 of file dwarf2read.c.
References dwarf2_section_names::compressed, and dwarf2_section_names::normal.
Referenced by dwarf2_locate_common_dwp_sections(), dwarf2_locate_dwo_sections(), dwarf2_locate_sections(), dwarf2_locate_v2_dwp_sections(), locate_dwz_sections(), and locate_v1_virtual_dwo_sections().
static void set_cu_language (unsigned int lang, struct dwarf2_cu * cu) [static]
Definition at line 16227 of file dwarf2read.c.
References dwarf2_cu::language, language_ada, language_asm, language_c, language_cplus, language_d, language_def(), dwarf2_cu::language_defn, language_fortran, language_go, language_java, language_m2, language_minimal, language_objc, and language_pascal.
Referenced by prepare_one_comp_unit(), and read_file_scope().
static void set_descriptive_type (struct type * type, struct die_info * die, struct dwarf2_cu * cu) [static]
Definition at line 17836 of file dwarf2read.c.
References ALLOCATE_GNAT_AUX_TYPE, die_descriptive_type(), and TYPE_DESCRIPTIVE_TYPE.
Referenced by read_array_type(), read_structure_type(), and read_subrange_type().
static struct type * set_die_type (struct die_info * die, struct type * type, struct dwarf2_cu * cu) [static, read]
Definition at line 21185 of file dwarf2read.c.
References _, complaint(), dwarf2_per_objfile::die_type_hash, dummy_obstack_deallocate(), hashtab_obstack_allocate(), HAVE_GNAT_AUX_INFO, INIT_GNAT_SPECIFIC, need_gnat_info(), dwarf2_cu::objfile, objfile::objfile_obstack, dwarf2_per_cu_offset_and_type::offset, dwarf2_cu::per_cu, dwarf2_per_cu_offset_and_type::per_cu, per_cu_offset_and_type_eq(), per_cu_offset_and_type_hash(), symfile_complaints, type, dwarf2_per_cu_offset_and_type::type, TYPE_CODE, TYPE_CODE_FLT, and TYPE_CODE_FUNC.
Referenced by read_array_type(), read_base_type(), read_enumeration_type(), read_module_type(), read_namespace_type(), read_set_type(), read_structure_type(), read_subrange_type(), read_subroutine_type(), read_tag_const_type(), read_tag_pointer_type(), read_tag_ptr_to_member_type(), read_tag_reference_type(), read_tag_restrict_type(), read_tag_string_type(), read_tag_volatile_type(), read_typedef(), and read_unspecified_type().
static void set_dwarf2_cmd (char * args, int from_tty) [static]
Definition at line 21356 of file dwarf2read.c.
References gdb_stdout, and help_list().
static void set_partial_user (struct objfile * objfile) [static]
Definition at line 6200 of file dwarf2read.c.
References partial_symtab::dependencies, dw2_get_cu(), partial_symtab::number_of_dependencies, dwarf2_per_cu_data::psymtab, partial_symtab::user, and dwarf2_per_cu_data::v.
Referenced by dwarf2_build_psymtabs_hard().
static void setup_type_unit_groups (struct die_info * die, struct dwarf2_cu * cu) [static]
Definition at line 8813 of file dwarf2read.c.
References allocate_symtab(), current_subfile, DW_UNSND, dwarf2_attr(), dwarf2_start_subfile(), dwarf2_start_symtab(), dwarf_decode_line_header(), line_header::file_names, first_time, free_cu_line_header(), gdb_assert, get_type_unit_group(), line_header::include_dirs, dwarf2_per_cu_data::is_debug_types, dwarf2_cu::line_header, make_cleanup(), subfile::name, line_header::num_file_names, dwarf2_cu::per_cu, restart_symtab(), subfile::symtab, line_header::file_entry::symtab, and signatured_type::type_unit_group.
Referenced by read_type_unit_scope().
static void show_check_physname (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 22313 of file dwarf2read.c.
References _, and fprintf_filtered().
static void show_dwarf2_always_disassemble (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 22303 of file dwarf2read.c.
References _, and fprintf_filtered().
static void show_dwarf2_cmd (char * args, int from_tty) [static]
Definition at line 21362 of file dwarf2read.c.
References cmd_show_list().
static void show_dwarf2_max_cache_age (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 1357 of file dwarf2read.c.
References _, and fprintf_filtered().
static struct die_info * sibling_die (struct die_info * die) [static, read]
Definition at line 18371 of file dwarf2read.c.
Referenced by dwarf2_get_subprogram_pc_bounds(), get_scope_pc_bounds(), inherit_abstract_dies(), process_enumeration_scope(), process_structure_scope(), read_array_type(), read_call_site_scope(), read_common_block(), read_file_scope(), read_func_scope(), read_import_statement(), read_lexical_block_scope(), read_module(), read_namespace(), read_subroutine_type(), and read_type_unit_scope().
static const gdb_byte* skip_children (const struct die_reader_specs * reader, const gdb_byte * info_ptr) [static]
Definition at line 6974 of file dwarf2read.c.
References die_reader_specs::cu, peek_die_abbrev(), and skip_one_die().
Referenced by locate_pdi_sibling(), and skip_one_die().
static const gdb_byte* skip_form_bytes (bfd * abfd, const gdb_byte * bytes, const gdb_byte * buffer_end, enum dwarf_form form, unsigned int offset_size, struct dwarf2_section_info * section) [static]
Definition at line 19968 of file dwarf2read.c.
References _, complaint(), dwarf2_section_buffer_overflow_complaint(), gdb_skip_leb128(), get_section_name(), read_1_byte(), read_2_bytes(), read_4_bytes(), read_direct_string(), read_unsigned_leb128(), and symfile_complaints.
Referenced by skip_unknown_opcode().
static const gdb_byte * skip_one_die (const struct die_reader_specs * reader, const gdb_byte * info_ptr, struct abbrev_info * abbrev) [static]
Definition at line 6997 of file dwarf2read.c.
References _, die_reader_specs::abfd, comp_unit_head::addr_size, abbrev_info::attrs, die_reader_specs::buffer, die_reader_specs::buffer_end, complaint(), die_reader_specs::cu, dwarf2_get_ref_die_offset(), dwarf_form_name(), error(), abbrev_info::has_children, dwarf2_cu::header, abbrev_info::num_attrs, comp_unit_head::offset_size, read_1_byte(), read_2_bytes(), read_4_bytes(), read_attribute(), read_direct_string(), read_unsigned_leb128(), safe_skip_leb128(), sect_offset::sect_off, skip_children(), symfile_complaints, and comp_unit_head::version.
Referenced by load_partial_dies(), and skip_children().
static const gdb_byte* skip_unknown_opcode (unsigned int opcode, const gdb_byte ** opcode_definitions, const gdb_byte * mac_ptr, const gdb_byte * mac_end, bfd * abfd, unsigned int offset_size, struct dwarf2_section_info * section) [static]
Definition at line 20050 of file dwarf2read.c.
References _, complaint(), read_unsigned_leb128(), skip_form_bytes(), and symfile_complaints.
Referenced by dwarf_decode_macro_bytes(), and dwarf_decode_macros().
static int sort_tu_by_abbrev_offset (const void * ap, const void * bp) [static]
Definition at line 5708 of file dwarf2read.c.
References tu_abbrev_offset::abbrev_offset, and sect_offset::sect_off.
Referenced by build_type_unit_groups().
static void store_in_ref_table (struct die_info * die, struct dwarf2_cu * cu) [static]
Definition at line 18771 of file dwarf2read.c.
References dwarf2_cu::die_hash.
Referenced by read_die_and_children().
static gdb_index_symbol_kind symbol_kind (struct partial_symbol * psym) [static]
Definition at line 21909 of file dwarf2read.c.
References LOC_BLOCK, LOC_COMPUTED, LOC_CONST, LOC_CONST_BYTES, LOC_OPTIMIZED_OUT, LOC_STATIC, LOC_TYPEDEF, PSYMBOL_CLASS, PSYMBOL_DOMAIN, STRUCT_DOMAIN, and VAR_DOMAIN.
Referenced by dw2_expand_symtabs_matching(), dw2_symtab_iter_next(), and write_psymbols().
static bfd* try_open_dwop_file (const char * file_name, int is_dwp, int search_cwd) [static]
Definition at line 10000 of file dwarf2read.c.
References debug_file_directory, flags, gdb_bfd_open(), gdb_bfd_unref(), gnutarget, openp(), OPF_RETURN_REALPATH, OPF_SEARCH_IN_PATH, and xfree().
Referenced by open_dwo_file(), and open_dwp_file().
static char * typename_concat (struct obstack * obs, const char * prefix, const char * suffix, int physname, struct dwarf2_cu * cu) [static]
Definition at line 18323 of file dwarf2read.c.
References dwarf2_cu::language, language_fortran, language_java, MAX_SEP_LEN, obconcat(), and xmalloc().
Referenced by dwarf2_compute_name(), partial_die_full_name(), partial_die_parent_scope(), and read_namespace_type().
static void uniquify_cu_indices (struct mapped_symtab * symtab) [static]
Definition at line 21656 of file dwarf2read.c.
References mapped_symtab::data, offset_type_compare(), qsort, mapped_symtab::size, VEC_address, VEC_index, VEC_length, VEC_replace, and VEC_truncate.
Referenced by write_psymtabs_to_index().
static void unlink_if_set (void * p) [static]
Definition at line 21990 of file dwarf2read.c.
Referenced by write_psymtabs_to_index().
static int unsigned_int_compar (const void * ap, const void * bp) [static]
Definition at line 10691 of file dwarf2read.c.
Referenced by inherit_abstract_dies().
static void var_decode_location (struct attribute * attr, struct symbol * sym, struct dwarf2_cu * cu) [static]
Definition at line 17151 of file dwarf2read.c.
References comp_unit_head::addr_size, ANOFFSET, attr_form_is_block(), dummy, DW_BLOCK, dwarf2_symbol_mark_computed(), fixup_symbol_section(), dwarf2_cu::header, leb128_size(), LOC_OPTIMIZED_OUT, LOC_STATIC, objfile::obfd, dwarf2_cu::objfile, read_addr_index_from_leb128(), read_address(), objfile::section_offsets, size, SYMBOL_ACLASS_INDEX, SYMBOL_COMPUTED_OPS, SYMBOL_SECTION, and SYMBOL_VALUE_ADDRESS.
Referenced by new_symbol_full().
static void write_address_map (struct objfile * objfile, struct obstack * obstack, htab_t cu_index_htab) [static]
Definition at line 21878 of file dwarf2read.c.
References add_address_entry(), add_address_entry_worker(), addrmap_index_data::addr_obstack, addrmap_foreach(), addrmap_index_data::cu_index_htab, addrmap_index_data::objfile, addrmap_index_data::previous_cu_index, addrmap_index_data::previous_cu_start, addrmap_index_data::previous_valid, and objfile::psymtabs_addrmap.
Referenced by write_psymtabs_to_index().
static const gdb_byte* write_constant_as_bytes (struct obstack * obstack, enum bfd_endian byte_order, struct type * type, ULONGEST value, LONGEST * len) [static]
Definition at line 19003 of file dwarf2read.c.
References store_unsigned_integer(), and TYPE_LENGTH.
Referenced by dwarf2_fetch_constant_bytes().
static void write_hash_table (struct mapped_symtab * symtab, struct obstack * output, struct obstack * cpool) [static]
Definition at line 21736 of file dwarf2read.c.
References add_indices_to_cpool(), add_string(), create_strtab(), create_symbol_hash_table(), mapped_symtab::data, symtab_index_entry::index_offset, MAYBE_SWAP, symtab_index_entry::name, and mapped_symtab::size.
Referenced by write_psymtabs_to_index().
static void write_obstack (FILE * file, struct obstack * obstack) [static]
Definition at line 21979 of file dwarf2read.c.
References _, and error().
Referenced by write_psymtabs_to_index().
static int write_one_signatured_type (void ** slot, void * d) [static]
Definition at line 22011 of file dwarf2read.c.
References signatured_type_index_data::cu_index, cu_offset::cu_off, objfile::global_psymbols, partial_symtab::globals_offset, psymbol_allocation_list::list, partial_symtab::n_global_syms, partial_symtab::n_static_syms, signatured_type_index_data::objfile, dwarf2_per_cu_data::offset, signatured_type::per_cu, signatured_type_index_data::psyms_seen, dwarf2_per_cu_data::psymtab, sect_offset::sect_off, signatured_type::signature, objfile::static_psymbols, partial_symtab::statics_offset, store_unsigned_integer(), signatured_type_index_data::symtab, signatured_type::type_offset_in_tu, signatured_type_index_data::types_list, dwarf2_per_cu_data::v, and write_psymbols().
Referenced by write_psymtabs_to_index().
static void write_psymbols (struct mapped_symtab * symtab, htab_t psyms_seen, struct partial_symbol ** psymp, int count, offset_type cu_index, int is_static) [static]
Definition at line 21947 of file dwarf2read.c.
References _, add_index_entry(), error(), language_ada, symbol_kind(), SYMBOL_LANGUAGE, and SYMBOL_SEARCH_NAME.
Referenced by recursively_write_psymbols(), and write_one_signatured_type().
static void write_psymtabs_to_index (struct objfile * objfile, const char * dir) [static]
Definition at line 22077 of file dwarf2read.c.
References _, cleanup_mapped_symtab(), create_mapped_symtab(), psymtab_cu_index_map::cu_index, signatured_type_index_data::cu_index, do_cleanups(), eq_psymtab_cu_index(), error(), gdb_assert, gdb_fopen_cloexec(), hash_psymtab_cu_index(), INDEX_SUFFIX, dwarf2_per_cu_data::length, make_cleanup(), make_cleanup_htab_delete(), make_cleanup_obstack_free(), MAYBE_SWAP, signatured_type_index_data::objfile, objfile_name(), dwarf2_per_cu_data::offset, perror_with_name(), signatured_type_index_data::psyms_seen, dwarf2_per_cu_data::psymtab, psymtab_cu_index_map::psymtab, objfile::psymtabs, objfile::psymtabs_addrmap, recursively_write_psymbols(), sect_offset::sect_off, store_unsigned_integer(), signatured_type_index_data::symtab, signatured_type_index_data::types_list, uniquify_cu_indices(), unlink_if_set(), partial_symtab::user, dwarf2_per_objfile::using_index, dwarf2_per_cu_data::v, VEC_length, write_address_map(), write_hash_table(), write_obstack(), write_one_signatured_type(), xcalloc(), xfree(), and xmalloc().
Referenced by save_gdb_index_command().
Variable Documentation
int bits_per_byte = 8 [static]
Definition at line 1278 of file dwarf2read.c.
Referenced by dwarf2_add_field(), and mips_isa_regsize().
int check_physname = 0 [static]
Definition at line 90 of file dwarf2read.c.
Referenced by dwarf2_physname().
int dwarf2_always_disassemble
Definition at line 22300 of file dwarf2read.c.
Referenced by locexpr_describe_location_1().
unsigned int dwarf2_die_debug = 0 [static]
Definition at line 87 of file dwarf2read.c.
Referenced by init_cutu_and_read_dies(), init_cutu_and_read_dies_no_follow(), read_cutu_die_from_dwo(), read_die_and_siblings(), and read_full_die().
struct dwarf2_debug_sections dwarf2_elf_names [static]
Initial value:
{
  { ".debug_info", ".zdebug_info" },
  { ".debug_abbrev", ".zdebug_abbrev" },
  { ".debug_line", ".zdebug_line" },
  { ".debug_loc", ".zdebug_loc" },
  { ".debug_macinfo", ".zdebug_macinfo" },
  { ".debug_macro", ".zdebug_macro" },
  { ".debug_str", ".zdebug_str" },
  { ".debug_ranges", ".zdebug_ranges" },
  { ".debug_types", ".zdebug_types" },
  { ".debug_addr", ".zdebug_addr" },
  { ".debug_frame", ".zdebug_frame" },
  { ".eh_frame", NULL },
  { ".gdb_index", ".zgdb_index" },
  23
}
Definition at line 324 of file dwarf2read.c.
Referenced by dwarf2_locate_sections().
struct quick_symbol_functions dwarf2_gdb_index_functions
Initial value:
{
  dw2_has_symbols,
  dw2_find_last_source_symtab,
  dw2_forget_cached_source_info,
  dw2_map_symtabs_matching_filename,
  dw2_lookup_symbol,
  dw2_print_stats,
  dw2_dump,
  dw2_relocate,
  dw2_expand_symtabs_for_function,
  dw2_expand_all_symtabs,
  dw2_expand_symtabs_with_fullname,
  dw2_map_matching_symbols,
  dw2_expand_symtabs_matching,
  dw2_find_pc_sect_symtab,
  dw2_map_symbol_filenames
}
Definition at line 4047 of file dwarf2read.c.
int dwarf2_locexpr_block_index [static]
Definition at line 101 of file dwarf2read.c.
Referenced by dwarf2_symbol_mark_computed().
int dwarf2_locexpr_index [static]
Definition at line 99 of file dwarf2read.c.
Referenced by dwarf2_const_value(), dwarf2_symbol_mark_computed(), and mark_common_block_symbol_computed().
int dwarf2_loclist_block_index [static]
Definition at line 102 of file dwarf2read.c.
Referenced by dwarf2_symbol_mark_computed().
int dwarf2_loclist_index [static]
Definition at line 100 of file dwarf2read.c.
Referenced by dwarf2_symbol_mark_computed().
int dwarf2_max_cache_age = 5 [static]
Definition at line 1355 of file dwarf2read.c.
Referenced by age_cached_comp_units().
struct objfile_data* dwarf2_objfile_data_key [static]
Definition at line 95 of file dwarf2read.c.
Referenced by dw2_setup(), dwarf2_free_objfile(), dwarf2_get_section_info(), dwarf2_has_info(), dwarf2_read_symtab(), and save_gdb_index_command().
struct dwarf2_per_objfile* dwarf2_per_objfile [static]
Definition at line 317 of file dwarf2read.c.
struct dwarf2_queue_item* dwarf2_queue [static]
Definition at line 1348 of file dwarf2read.c.
Referenced by dwarf2_release_queue().
struct dwarf2_queue_item * dwarf2_queue_tail [static]
Definition at line 1348 of file dwarf2read.c.
int dwarf2_read_debug = 0 [static]
Definition at line 84 of file dwarf2read.c.
Referenced by build_type_unit_groups(), create_debug_types_hash_table(), create_dwo_cu(), create_dwo_cu_reader(), create_dwo_unit_in_dwp_v1(), create_dwo_unit_in_dwp_v2(), dwarf2_build_psymtabs_hard(), lookup_dwo_cutu(), open_and_init_dwo_file(), open_and_init_dwp_file(), process_psymtab_comp_unit_reader(), process_queue(), and read_comp_units_from_section().
struct dwop_section_names dwop_section_names [static]
Referenced by dwarf2_locate_common_dwp_sections(), dwarf2_locate_dwo_sections(), dwarf2_locate_v2_dwp_sections(), and locate_v1_virtual_dwo_sections().
struct cmd_list_element* set_dwarf2_cmdlist [static]
Definition at line 21352 of file dwarf2read.c.
struct cmd_list_element* show_dwarf2_cmdlist [static]
Definition at line 21353 of file dwarf2read.c.
int use_deprecated_index_sections = 0 [static]
Definition at line 93 of file dwarf2read.c.
Referenced by dwarf2_read_index().