GDB (xrefs): /home/stan/gdb/src/gdb/dwarf2-frame-tailcall.h File Reference
/home/stan/gdb/src/gdb/dwarf2-frame-tailcall.h File Reference
Functions
void dwarf2_tailcall_sniffer_first (struct frame_info *this_frame, void **tailcall_cachep, const LONGEST *entry_cfa_sp_offsetp)
struct value * dwarf2_tailcall_prev_register_first (struct frame_info *this_frame, void **tailcall_cachep, int regnum)
Variables
struct frame_unwind dwarf2_tailcall_frame_unwind
Function Documentation
struct value* dwarf2_tailcall_prev_register_first (struct frame_info * this_frame, void ** tailcall_cachep, int regnum) [read]
Definition at line 267 of file dwarf2-frame-tailcall.c.
References tailcall_cache::chain_levels, dwarf2_frame_cfa(), tailcall_cache::entry_cfa_sp_offset, existing_next_levels(), frame_unwind_got_address(), gdbarch_pc_regnum(), gdbarch_sp_regnum(), get_frame_arch(), pretend_pc(), tailcall_cache::prev_sp, and tailcall_cache::prev_sp_p.
Referenced by dwarf2_frame_prev_register(), and tailcall_frame_prev_register().
void dwarf2_tailcall_sniffer_first (struct frame_info * this_frame, void ** tailcall_cachep, const LONGEST * entry_cfa_sp_offsetp)
Definition at line 363 of file dwarf2-frame-tailcall.c.
References cache_new_ref1(), call_site_find_chain(), tailcall_cache::chain, tailcall_cache::chain_levels, tailcall_cache::entry_cfa_sp_offset, entry_values_debug, exception_print(), frame_unwind_arch(), frame_unwind_register_unsigned(), gdb_assert, gdb_stdout, gdbarch_sp_regnum(), gdbarch_unwind_pc(), get_frame_address_in_block(), call_site_chain::length, pretended_chain_levels(), tailcall_cache::prev_pc, tailcall_cache::prev_sp, tailcall_cache::prev_sp_p, gdb_exception::reason, RETURN_MASK_ERROR, sp_regnum, TRY_CATCH, and xfree().
Referenced by dwarf2_frame_cache().
Variable Documentation
struct frame_unwind dwarf2_tailcall_frame_unwind
Definition at line 457 of file dwarf2-frame-tailcall.c.
Referenced by dwarf2_append_unwinders(), dwarf2_frame_cfa(), dwarf2_frame_dealloc_cache(), and frame_is_tailcall().