GDB (xrefs): /home/stan/gdb/src/gdb/dwarf2expr.h File Reference
/home/stan/gdb/src/gdb/dwarf2expr.h File Reference
#include "leb128.h"
#include "gdbtypes.h"
Classes
struct dwarf_expr_context_funcs
struct dwarf_stack_value
struct dwarf_expr_context
struct dwarf_expr_piece
Enumerations
enum dwarf_value_location {
DWARF_VALUE_MEMORY, DWARF_VALUE_REGISTER, DWARF_VALUE_STACK, DWARF_VALUE_LITERAL,
DWARF_VALUE_OPTIMIZED_OUT, DWARF_VALUE_IMPLICIT_POINTER
}
Functions
struct dwarf_expr_context * new_dwarf_expr_context (void)
void free_dwarf_expr_context (struct dwarf_expr_context *ctx)
struct cleanup * make_cleanup_free_dwarf_expr_context (struct dwarf_expr_context *ctx)
void dwarf_expr_push_address (struct dwarf_expr_context *ctx, CORE_ADDR value, int in_stack_memory)
void dwarf_expr_eval (struct dwarf_expr_context *ctx, const gdb_byte *addr, size_t len)
struct value * dwarf_expr_fetch (struct dwarf_expr_context *ctx, int n)
CORE_ADDR dwarf_expr_fetch_address (struct dwarf_expr_context *ctx, int n)
int dwarf_expr_fetch_in_stack_memory (struct dwarf_expr_context *ctx, int n)
void dwarf_expr_require_composition (const gdb_byte *, const gdb_byte *, const char *)
void ctx_no_get_frame_base (void *baton, const gdb_byte **start, size_t *length)
CORE_ADDR ctx_no_get_frame_cfa (void *baton)
CORE_ADDR ctx_no_get_frame_pc (void *baton)
CORE_ADDR ctx_no_get_tls_address (void *baton, CORE_ADDR offset)
void ctx_no_dwarf_call (struct dwarf_expr_context *ctx, cu_offset die_offset)
struct type * ctx_no_get_base_type (struct dwarf_expr_context *ctx, cu_offset die)
void ctx_no_push_dwarf_reg_entry_value (struct dwarf_expr_context *ctx, enum call_site_parameter_kind kind, union call_site_parameter_u kind_u, int deref_size)
CORE_ADDR ctx_no_get_addr_index (void *baton, unsigned int index)
int dwarf_block_to_dwarf_reg (const gdb_byte *buf, const gdb_byte *buf_end)
int dwarf_block_to_dwarf_reg_deref (const gdb_byte *buf, const gdb_byte *buf_end, CORE_ADDR *deref_size_return)
int dwarf_block_to_fb_offset (const gdb_byte *buf, const gdb_byte *buf_end, CORE_ADDR *fb_offset_return)
int dwarf_block_to_sp_offset (struct gdbarch *gdbarch, const gdb_byte *buf, const gdb_byte *buf_end, CORE_ADDR *sp_offset_return)
static const gdb_byte * gdb_read_uleb128 (const gdb_byte *buf, const gdb_byte *buf_end, uint64_t *r)
static const gdb_byte * gdb_read_sleb128 (const gdb_byte *buf, const gdb_byte *buf_end, int64_t *r)
static const gdb_byte * gdb_skip_leb128 (const gdb_byte *buf, const gdb_byte *buf_end)
const gdb_byte * safe_read_uleb128 (const gdb_byte *buf, const gdb_byte *buf_end, uint64_t *r)
const gdb_byte * safe_read_sleb128 (const gdb_byte *buf, const gdb_byte *buf_end, int64_t *r)
const gdb_byte * safe_skip_leb128 (const gdb_byte *buf, const gdb_byte *buf_end)
Enumeration Type Documentation
enum dwarf_value_location
Enumerator:
DWARF_VALUE_MEMORY
DWARF_VALUE_REGISTER
DWARF_VALUE_STACK
DWARF_VALUE_LITERAL
DWARF_VALUE_OPTIMIZED_OUT
DWARF_VALUE_IMPLICIT_POINTER
Definition at line 89 of file dwarf2expr.h.
Function Documentation
void ctx_no_dwarf_call (struct dwarf_expr_context * ctx, cu_offset die_offset)
Definition at line 1539 of file dwarf2expr.c.
References _, and error().
CORE_ADDR ctx_no_get_addr_index (void * baton, unsigned int index)
Definition at line 1568 of file dwarf2expr.c.
References _, and error().
struct type* ctx_no_get_base_type (struct dwarf_expr_context * ctx, cu_offset die) [read]
Definition at line 1547 of file dwarf2expr.c.
References _, and error().
void ctx_no_get_frame_base (void * baton, const gdb_byte ** start, size_t * length)
Definition at line 1507 of file dwarf2expr.c.
References _, and error().
CORE_ADDR ctx_no_get_frame_cfa (void * baton)
Definition at line 1515 of file dwarf2expr.c.
References _, and error().
CORE_ADDR ctx_no_get_frame_pc (void * baton)
Definition at line 1523 of file dwarf2expr.c.
References _, and error().
CORE_ADDR ctx_no_get_tls_address (void * baton, CORE_ADDR offset)
Definition at line 1531 of file dwarf2expr.c.
References _, and error().
void ctx_no_push_dwarf_reg_entry_value (struct dwarf_expr_context * ctx, enum call_site_parameter_kind kind, union call_site_parameter_u kind_u, int deref_size)
Definition at line 1556 of file dwarf2expr.c.
References _, and internal_error().
int dwarf_block_to_dwarf_reg (const gdb_byte * buf, const gdb_byte * buf_end)
Definition at line 465 of file dwarf2expr.c.
References gdb_read_uleb128(), and gdb_skip_leb128().
Referenced by execute_stack_op(), read_call_site_scope(), and value_of_dwarf_block_entry().
int dwarf_block_to_dwarf_reg_deref (const gdb_byte * buf, const gdb_byte * buf_end, CORE_ADDR * deref_size_return)
Definition at line 508 of file dwarf2expr.c.
References gdb_read_sleb128(), gdb_read_uleb128(), and offset.
Referenced by execute_stack_op().
int dwarf_block_to_fb_offset (const gdb_byte * buf, const gdb_byte * buf_end, CORE_ADDR * fb_offset_return)
Definition at line 567 of file dwarf2expr.c.
References gdb_read_sleb128(), and LONGEST.
Referenced by value_of_dwarf_block_entry().
int dwarf_block_to_sp_offset (struct gdbarch * gdbarch, const gdb_byte * buf, const gdb_byte * buf_end, CORE_ADDR * sp_offset_return)
Definition at line 594 of file dwarf2expr.c.
References gdb_read_sleb128(), gdb_read_uleb128(), gdbarch_dwarf2_reg_to_regnum(), gdbarch_sp_regnum(), and LONGEST.
Referenced by read_call_site_scope().
void dwarf_expr_eval (struct dwarf_expr_context * ctx, const gdb_byte * addr, size_t len)
Definition at line 359 of file dwarf2expr.c.
References execute_stack_op(), gdb_assert, and dwarf_expr_context::recursion_depth.
Referenced by dwarf2_evaluate_loc_desc_full(), dwarf2_loc_desc_needs_frame(), dwarf_expr_push_dwarf_reg_entry_value(), execute_stack_op(), and per_cu_dwarf_call().
struct value* dwarf_expr_fetch (struct dwarf_expr_context * ctx, int n) [read]
Definition at line 189 of file dwarf2expr.c.
References _, error(), dwarf_expr_context::stack, and dwarf_expr_context::stack_len.
Referenced by add_piece(), dwarf2_evaluate_loc_desc_full(), dwarf_expr_fetch_address(), and execute_stack_op().
CORE_ADDR dwarf_expr_fetch_address (struct dwarf_expr_context * ctx, int n)
Definition at line 256 of file dwarf2expr.c.
References dwarf_expr_context::addr_size, dwarf_expr_fetch(), dwarf_require_integral(), extract_unsigned_integer(), dwarf_expr_context::gdbarch, gdbarch_byte_order(), gdbarch_integer_to_address(), gdbarch_integer_to_address_p(), get_unsigned_type(), store_unsigned_integer(), TYPE_LENGTH, ULONGEST, value_contents(), and value_type().
Referenced by add_piece(), dwarf2_evaluate_loc_desc_full(), and execute_stack_op().
int dwarf_expr_fetch_in_stack_memory (struct dwarf_expr_context * ctx, int n)
Definition at line 289 of file dwarf2expr.c.
References _, error(), dwarf_expr_context::stack, and dwarf_expr_context::stack_len.
Referenced by add_piece(), dwarf2_evaluate_loc_desc_full(), and execute_stack_op().
void dwarf_expr_push_address (struct dwarf_expr_context * ctx, CORE_ADDR value, int in_stack_memory)
Definition at line 168 of file dwarf2expr.c.
References dwarf_expr_address_type(), dwarf_expr_push(), and value_from_ulongest().
Referenced by execute_stack_op(), and needs_dwarf_reg_entry_value().
void dwarf_expr_require_composition (const gdb_byte * , const gdb_byte * , const char *)
Definition at line 409 of file dwarf2expr.c.
References _, and error().
Referenced by dwarf2_compile_expr_to_ax(), and execute_stack_op().
void free_dwarf_expr_context (struct dwarf_expr_context * ctx)
Definition at line 112 of file dwarf2expr.c.
References dwarf_expr_context::pieces, dwarf_expr_context::stack, and xfree().
Referenced by free_dwarf_expr_context_cleanup().
static const gdb_byte* gdb_read_sleb128 (const gdb_byte * buf, const gdb_byte * buf_end, int64_t * r) [inline, static]
Definition at line 311 of file dwarf2expr.h.
Referenced by decode_frame_entry_1(), dwarf_block_to_dwarf_reg_deref(), dwarf_block_to_fb_offset(), dwarf_block_to_sp_offset(), and safe_read_sleb128().
static const gdb_byte* gdb_read_uleb128 (const gdb_byte * buf, const gdb_byte * buf_end, uint64_t * r) [inline, static]
Definition at line 300 of file dwarf2expr.h.
Referenced by decode_debug_loc_dwo_addresses(), decode_frame_entry_1(), dwarf_block_to_dwarf_reg(), dwarf_block_to_dwarf_reg_deref(), dwarf_block_to_sp_offset(), and safe_read_uleb128().
static const gdb_byte* gdb_skip_leb128 (const gdb_byte * buf, const gdb_byte * buf_end) [inline, static]
Definition at line 322 of file dwarf2expr.h.
Referenced by dwarf_block_to_dwarf_reg(), safe_skip_leb128(), and skip_form_bytes().
struct cleanup* make_cleanup_free_dwarf_expr_context (struct dwarf_expr_context * ctx) [read]
Definition at line 130 of file dwarf2expr.c.
References free_dwarf_expr_context_cleanup(), and make_cleanup().
Referenced by dwarf2_evaluate_loc_desc_full(), dwarf2_loc_desc_needs_frame(), and execute_stack_op().
struct dwarf_expr_context* new_dwarf_expr_context (void) [read]
Definition at line 94 of file dwarf2expr.c.
References dwarf_expr_context::max_recursion_depth, dwarf_expr_context::num_pieces, dwarf_expr_context::pieces, dwarf_expr_context::stack, dwarf_expr_context::stack_allocated, dwarf_expr_context::stack_len, xcalloc(), and xmalloc().
Referenced by dwarf2_evaluate_loc_desc_full(), dwarf2_loc_desc_needs_frame(), and execute_stack_op().
const gdb_byte* safe_read_sleb128 (const gdb_byte * buf, const gdb_byte * buf_end, int64_t * r)
Definition at line 386 of file dwarf2expr.c.
References _, error(), and gdb_read_sleb128().
Referenced by disassemble_dwarf_expression(), dwarf2_compile_expr_to_ax(), execute_cfa_program(), execute_stack_op(), locexpr_describe_location_piece(), and read_encoded_value().
const gdb_byte* safe_read_uleb128 (const gdb_byte * buf, const gdb_byte * buf_end, uint64_t * r)
Definition at line 374 of file dwarf2expr.c.
References _, error(), and gdb_read_uleb128().
Referenced by disassemble_dwarf_expression(), dwarf2_compile_expr_to_ax(), execute_cfa_program(), execute_stack_op(), locexpr_describe_location_1(), locexpr_describe_location_piece(), and read_encoded_value().
const gdb_byte* safe_skip_leb128 (const gdb_byte * buf, const gdb_byte * buf_end)
Definition at line 396 of file dwarf2expr.c.
References _, error(), and gdb_skip_leb128().
Referenced by skip_one_die().