GDB (xrefs): /home/stan/gdb/src/gdb/environ.h File Reference
/home/stan/gdb/src/gdb/environ.h File Reference
Classes
struct gdb_environ
Functions
struct gdb_environ * make_environ (void)
void free_environ (struct gdb_environ *)
void init_environ (struct gdb_environ *)
char * get_in_environ (const struct gdb_environ *, const char *)
void set_in_environ (struct gdb_environ *, const char *, const char *)
void unset_in_environ (struct gdb_environ *, char *)
char ** environ_vector (struct gdb_environ *)
Function Documentation
char** environ_vector (struct gdb_environ *)
Definition at line 93 of file environ.c.
References gdb_environ::vector.
Referenced by environment_info(), and run_command_1().
void free_environ (struct gdb_environ *)
Definition at line 44 of file environ.c.
References gdb_environ::vector, and xfree().
Referenced by free_inferior(), and unset_environment_command().
char* get_in_environ (const struct gdb_environ * , const char *)
Definition at line 101 of file environ.c.
References len, and gdb_environ::vector.
Referenced by environment_info(), mi_cmd_env_path(), path_command(), path_info(), and solib_find().
void init_environ (struct gdb_environ *)
Definition at line 60 of file environ.c.
References gdb_environ::allocated, environ, len, max, memcpy(), gdb_environ::vector, xmalloc(), and xrealloc().
Referenced by add_inferior_silent().
struct gdb_environ* make_environ (void) [read]
Definition at line 29 of file environ.c.
References gdb_environ::allocated, gdb_environ::vector, and xmalloc().
Referenced by add_inferior_silent(), and unset_environment_command().
void set_in_environ (struct gdb_environ * , const char * , const char *)
Definition at line 117 of file environ.c.
References gdb_environ::allocated, len, gdb_environ::vector, xfree(), xmalloc(), and xrealloc().
Referenced by mi_cmd_env_path(), path_command(), and set_environment_command().
void unset_in_environ (struct gdb_environ * , char *)
Definition at line 164 of file environ.c.
References len, gdb_environ::vector, and xfree().
Referenced by unset_environment_command().