GDB (xrefs): /home/stan/gdb/src/gdb/event-top.c File Reference
/home/stan/gdb/src/gdb/event-top.c File Reference
#include "defs.h"
#include "top.h"
#include "inferior.h"
#include "target.h"
#include "terminal.h"
#include "event-loop.h"
#include "event-top.h"
#include "interps.h"
#include <signal.h>
#include "exceptions.h"
#include "cli/cli-script.h"
#include "main.h"
#include "gdbthread.h"
#include "observer.h"
#include "continuations.h"
#include "gdbcmd.h"
#include "annotate.h"
#include "maint.h"
#include "readline/readline.h"
#include "readline/history.h"
Classes
struct readline_input_state
Defines
#define SERVER_COMMAND_LENGTH 7
Functions
static void rl_callback_read_char_wrapper (gdb_client_data client_data)
static void command_line_handler (char *rl)
static void change_line_handler (void)
static void command_handler (char *command)
static char * top_level_prompt (void)
static void handle_sigfpe (int sig)
static void async_float_handler (gdb_client_data)
void cli_command_loop (void *data)
void display_gdb_prompt (char *new_prompt)
void stdin_event_handler (int error, gdb_client_data client_data)
void async_enable_stdin (void)
void async_disable_stdin (void)
void gdb_readline2 (gdb_client_data client_data)
void async_init_signals (void)
void handle_sigint (int sig)
void handle_sigterm (int sig)
void async_request_quit (gdb_client_data arg)
void set_async_editing_command (char *args, int from_tty, struct cmd_list_element *c)
void gdb_setup_readline (void)
void gdb_disable_readline (void)
Variables
void(* input_handler)(char *)
void(* call_readline)(gdb_client_data)
int async_command_editing_p
char * async_annotation_suffix
int exec_done_display_p = 0
int input_fd
static struct
async_signal_handler * sigint_token
static struct
async_signal_handler * sigfpe_token
static int more_to_come = 0
struct readline_input_state readline_input_state
void(* after_char_processing_hook)(void)
Define Documentation
#define SERVER_COMMAND_LENGTH 7
Referenced by command_line_handler(), and command_line_input().
Function Documentation
void async_disable_stdin (void)
Definition at line 400 of file event-top.c.
References sync_execution.
Referenced by advance_command(), attach_command(), continue_command(), finish_command(), jump_command(), run_command_1(), signal_command(), step_1(), and until_command().
void async_enable_stdin (void)
Definition at line 383 of file event-top.c.
References sync_execution, and target_terminal_ours.
Referenced by attach_command(), attach_command_post_wait(), inferior_event_handler(), normal_stop(), and start_event_loop().
static void async_float_handler (gdb_client_data arg) [static]
Definition at line 932 of file event-top.c.
References _, and error().
Referenced by async_init_signals().
void async_init_signals (void)
Definition at line 731 of file event-top.c.
References async_float_handler(), async_request_quit(), create_async_signal_handler(), handle_sigfpe(), handle_sigint(), and handle_sigterm().
Referenced by gdb_init().
void async_request_quit (gdb_client_data arg)
Definition at line 812 of file event-top.c.
References check_quit_flag(), and quit().
Referenced by async_init_signals().
static void change_line_handler (void) [static]
Definition at line 189 of file event-top.c.
References async_command_editing_p, call_readline, command_line_handler(), gdb_readline2(), input_handler, and rl_callback_read_char_wrapper().
Referenced by set_async_editing_command().
void cli_command_loop (void * data)
Definition at line 174 of file event-top.c.
References display_gdb_prompt(), and start_event_loop().
Referenced by _initialize_cli_interp(), and _initialize_tui_interp().
static void command_handler (char * command) [static]
Definition at line 413 of file event-top.c.
References bpstat_do_actions(), clear_quit_flag(), do_cleanups(), execute_command(), instream, make_command_stats_cleanup(), printf_unfiltered(), and reinitialize_more_filter().
Referenced by command_line_handler().
static void command_line_handler (char * rl) [static]
Definition at line 453 of file event-top.c.
References annotation_level, async_annotation_suffix, command_handler(), display_gdb_prompt(), gdb_flush(), gdb_stderr, gdb_stdout, history_expansion_p, instream, job_control, readline_input_state::linebuffer, readline_input_state::linebuffer_ptr, more_to_come, p, printf_unfiltered(), puts_unfiltered(), saved_command_line, saved_command_line_size, server_command, SERVER_COMMAND_LENGTH, source_file_name, source_line_number, wrap_here(), xfree(), xmalloc(), and xrealloc().
Referenced by change_line_handler(), and gdb_setup_readline().
void display_gdb_prompt (char * new_prompt)
Definition at line 233 of file event-top.c.
References annotate_display_prompt(), async_command_editing_p, current_interp_display_prompt_p(), do_cleanups(), fputs_unfiltered(), free_current_contents(), gdb_flush(), gdb_stdout, input_handler, make_cleanup(), reset_command_nest_depth(), sync_execution, and top_level_prompt().
Referenced by cli_command_loop(), command_line_handler(), fetch_inferior_event(), gdb_readline_wrapper(), inferior_event_handler(), interp_set(), and start_event_loop().
void gdb_disable_readline (void)
Definition at line 1010 of file event-top.c.
References delete_file_handler(), gdb_stderr, gdb_stdlog, gdb_stdout, gdb_stdtarg, gdb_stdtargerr, input_fd, and ui_file_delete().
Referenced by cli_interpreter_suspend(), and mi_interpreter_suspend().
void gdb_readline2 (gdb_client_data client_data)
Definition at line 651 of file event-top.c.
References instream, xfree(), xmalloc(), and xrealloc().
Referenced by change_line_handler(), gdb_setup_readline(), and mi_interpreter_resume().
void gdb_setup_readline (void)
Definition at line 952 of file event-top.c.
References add_file_handler(), async_command_editing_p, batch_silent, call_readline, command_line_handler(), gdb_readline2(), gdb_stderr, gdb_stdlog, gdb_stdout, gdb_stdtarg, gdb_stdtargerr, input_fd, input_handler, instream, rl_callback_read_char_wrapper(), stderr_fileopen(), stdin_event_handler(), and stdio_fileopen().
Referenced by cli_interpreter_resume(), mi_interpreter_resume(), and tui_resume().
static void handle_sigfpe (int sig) [static]
Definition at line 924 of file event-top.c.
References mark_async_signal_handler().
Referenced by async_init_signals().
void handle_sigint (int sig)
Definition at line 779 of file event-top.c.
References gdb_call_async_signal_handler(), handle_sigint(), immediate_quit, and set_quit_flag().
Referenced by async_cleanup_sigint_signal_handler(), async_init_signals(), handle_sigint(), interrupt_query(), and record_full_wait_1().
void handle_sigterm (int sig)
Definition at line 804 of file event-top.c.
References handle_sigterm(), instream, and quit_force().
Referenced by async_init_signals(), and handle_sigterm().
static void rl_callback_read_char_wrapper (gdb_client_data client_data) [static]
Definition at line 162 of file event-top.c.
References after_char_processing_hook.
Referenced by change_line_handler(), and gdb_setup_readline().
void set_async_editing_command (char * args, int from_tty, struct cmd_list_element * c)
Definition at line 942 of file event-top.c.
References change_line_handler().
Referenced by init_main().
void stdin_event_handler (int error, gdb_client_data client_data)
Definition at line 363 of file event-top.c.
References _, call_readline, delete_file_handler(), discard_all_continuations(), discard_all_intermediate_continuations(), input_fd, instream, printf_unfiltered(), and quit_command().
Referenced by gdb_setup_readline(), linux_nat_terminal_ours(), and remote_terminal_ours().
static char * top_level_prompt (void) [static]
Definition at line 311 of file event-top.c.
References annotation_level, async_annotation_suffix, get_prompt(), observer_notify_before_prompt(), xfree(), and xmalloc().
Referenced by display_gdb_prompt().
Variable Documentation
void(* after_char_processing_hook)(void)
Definition at line 155 of file event-top.c.
Referenced by gdb_readline_wrapper(), gdb_readline_wrapper_cleanup(), gdb_readline_wrapper_line(), gdb_rl_operate_and_get_next(), gdb_rl_operate_and_get_next_completion(), rl_callback_read_char_wrapper(), and start_event_loop().
char* async_annotation_suffix
Definition at line 111 of file event-top.c.
Referenced by command_line_handler(), init_main(), and top_level_prompt().
int async_command_editing_p
Definition at line 107 of file event-top.c.
Referenced by change_line_handler(), display_gdb_prompt(), gdb_readline_wrapper_line(), gdb_setup_readline(), init_main(), and mi_interpreter_resume().
void(* call_readline)(gdb_client_data)
Definition at line 97 of file event-top.c.
Referenced by change_line_handler(), gdb_setup_readline(), mi_interpreter_resume(), and stdin_event_handler().
int exec_done_display_p = 0
Definition at line 115 of file event-top.c.
Referenced by fetch_inferior_event(), and init_main().
int input_fd
Definition at line 119 of file event-top.c.
Referenced by gdb_disable_readline(), gdb_setup_readline(), linux_nat_terminal_inferior(), linux_nat_terminal_ours(), remote_terminal_inferior(), remote_terminal_ours(), and stdin_event_handler().
void(* input_handler)(char *)
Definition at line 96 of file event-top.c.
Referenced by change_line_handler(), display_gdb_prompt(), gdb_readline_wrapper(), gdb_readline_wrapper_cleanup(), gdb_setup_readline(), and mi_interpreter_resume().
int more_to_come = 0 [static]
Definition at line 144 of file event-top.c.
Referenced by command_line_handler().
struct readline_input_state readline_input_state
struct async_signal_handler* sigfpe_token [static]
Definition at line 134 of file event-top.c.
struct async_signal_handler* sigint_token [static]
Definition at line 127 of file event-top.c.