GDB (xrefs): /home/stan/gdb/src/gdb/event-loop.h File Reference
/home/stan/gdb/src/gdb/event-loop.h File Reference
Typedefs
typedef void * gdb_client_data
typedef void(handler_func)(int, gdb_client_data)
typedef void(sig_handler_func)(gdb_client_data)
typedef void(async_event_handler_func)(gdb_client_data)
typedef void(timer_handler_func)(gdb_client_data)
Functions
void initialize_event_loop (void)
void start_event_loop (void)
int gdb_do_one_event (void)
void delete_file_handler (int fd)
void add_file_handler (int fd, handler_func *proc, gdb_client_data client_data)
struct async_signal_handler * create_async_signal_handler (sig_handler_func *proc, gdb_client_data client_data)
void delete_async_signal_handler (struct async_signal_handler **)
int create_timer (int milliseconds, timer_handler_func *proc, gdb_client_data client_data)
void delete_timer (int id)
void call_async_signal_handler (struct async_signal_handler *handler)
void mark_async_signal_handler (struct async_signal_handler *handler)
void gdb_call_async_signal_handler (struct async_signal_handler *handler, int immediate_p)
struct async_event_handler * create_async_event_handler (async_event_handler_func *proc, gdb_client_data client_data)
void delete_async_event_handler (struct async_event_handler **handler_ptr)
void mark_async_event_handler (struct async_event_handler *handler)
Typedef Documentation
typedef void(async_event_handler_func)(gdb_client_data)
Definition at line 75 of file event-loop.h.
typedef void* gdb_client_data
Definition at line 70 of file event-loop.h.
typedef void(handler_func)(int, gdb_client_data)
Definition at line 73 of file event-loop.h.
typedef void(sig_handler_func)(gdb_client_data)
Definition at line 74 of file event-loop.h.
typedef void(timer_handler_func)(gdb_client_data)
Definition at line 76 of file event-loop.h.
Function Documentation
void add_file_handler (int fd, handler_func * proc, gdb_client_data client_data)
Definition at line 473 of file event-loop.c.
References _, create_file_handler(), GDB_EXCEPTION, GDB_READABLE, and internal_error().
Referenced by gdb_setup_readline(), linux_nat_async(), linux_nat_terminal_ours(), remote_terminal_ours(), reschedule(), and tui_initialize_io().
void call_async_signal_handler (struct async_signal_handler * handler)
Definition at line 955 of file event-loop.c.
References async_signal_handler::client_data, and async_signal_handler::proc.
Referenced by gdb_call_async_signal_handler(), and gdb_select().
struct async_event_handler* create_async_event_handler (async_event_handler_func * proc, gdb_client_data client_data) [read]
Definition at line 1031 of file event-loop.c.
References async_event_handler_list, async_event_handler::client_data, async_event_handler::next_handler, async_event_handler::proc, async_event_handler::ready, and xmalloc().
Referenced by record_full_open(), remote_notif_state_allocate(), and remote_open_1().
struct async_signal_handler* create_async_signal_handler (sig_handler_func * proc, gdb_client_data client_data) [read]
Definition at line 932 of file event-loop.c.
References async_signal_handler::client_data, async_signal_handler::next_handler, async_signal_handler::proc, async_signal_handler::ready, sighandler_list, and xmalloc().
Referenced by async_init_signals(), and initialize_remote_fileio().
int create_timer (int milliseconds, timer_handler_func * proc, gdb_client_data client_data)
Definition at line 1140 of file event-loop.c.
References gdb_timer::client_data, gdb_notifier, gdb_timer::next, gdb_timer::proc, gdb_timer::timer_id, timer_list, gdb_timer::when, and xmalloc().
Referenced by reschedule().
void delete_async_event_handler (struct async_event_handler ** handler_ptr)
Definition at line 1110 of file event-loop.c.
References async_event_handler_list, gdb_assert, async_event_handler::next_handler, and xfree().
Referenced by record_full_close(), remote_close(), and remote_notif_state_xfree().
void delete_async_signal_handler (struct async_signal_handler **)
Definition at line 1002 of file event-loop.c.
References gdb_assert, async_signal_handler::next_handler, sighandler_list, and xfree().
void delete_file_handler (int fd)
Definition at line 599 of file event-loop.c.
References _, file_handler::fd, GDB_EXCEPTION, gdb_notifier, GDB_READABLE, GDB_WRITABLE, internal_error(), file_handler::mask, file_handler::next_file, xfree(), and xmalloc().
Referenced by gdb_disable_readline(), linux_nat_async(), linux_nat_terminal_inferior(), remote_terminal_inferior(), reschedule(), ser_base_async(), and stdin_event_handler().
void delete_timer (int id)
Definition at line 1206 of file event-loop.c.
References gdb_notifier, gdb_timer::next, gdb_timer::timer_id, timer_list, and xfree().
Referenced by reschedule(), and ser_base_async().
void gdb_call_async_signal_handler (struct async_signal_handler * handler, int immediate_p)
Definition at line 255 of file mingw-hdep.c.
References call_async_signal_handler(), mark_async_signal_handler(), and sigint_event.
Referenced by handle_sigint(), remote_fileio_ctrl_c_signal_handler(), sync_remote_interrupt(), and sync_remote_interrupt_twice().
int gdb_do_one_event (void)
Definition at line 356 of file event-loop.c.
References check_async_event_handlers(), gdb_wait_for_event(), poll_timers(), and process_event().
Referenced by execute_command(), gdb_readline_wrapper(), and start_event_loop().
void initialize_event_loop (void)
Definition at line 299 of file event-loop.c.
References gdb_event_xfree(), and QUEUE_alloc.
Referenced by gdb_init().
void mark_async_event_handler (struct async_event_handler * handler)
Definition at line 1054 of file event-loop.c.
References async_event_handler::ready.
Referenced by handle_notification(), push_stop_reply(), queued_stop_reply(), record_full_core_resume(), record_full_resume(), remote_notif_stop_can_get_pending_events(), and remote_wait().
void mark_async_signal_handler (struct async_signal_handler * handler)
Definition at line 965 of file event-loop.c.
References async_signal_handler::ready.
Referenced by async_handle_remote_sigint(), async_handle_remote_sigint_twice(), gdb_call_async_signal_handler(), and handle_sigfpe().
void start_event_loop (void)
Definition at line 418 of file event-loop.c.
References after_char_processing_hook, async_enable_stdin(), display_gdb_prompt(), exception_print(), gdb_do_one_event(), gdb_stderr, gdb_exception::reason, RETURN_MASK_ALL, and TRY_CATCH.
Referenced by cli_command_loop(), and mi_command_loop().