GDB (xrefs): /home/stan/gdb/src/gdb/contrib/expect-read1.c File Reference
/home/stan/gdb/src/gdb/contrib/expect-read1.c File Reference
#include <dlfcn.h>
#include <unistd.h>
#include <fcntl.h>
#include <stdlib.h>
Defines
#define _GNU_SOURCE 1
Functions
ssize_t read (int fd, void *buf, size_t count)
Define Documentation
#define _GNU_SOURCE 1
Definition at line 19 of file expect-read1.c.
Function Documentation
ssize_t read (int fd, void * buf, size_t count)
Definition at line 26 of file expect-read1.c.
Referenced by add_reg(), agent_run_command(), append_user_reg(), async_file_flush(), darwin_ptrace_me(), do_hardwire_readchar(), fbsd_find_memory_regions(), gdb_select(), inf_child_fileio_pread(), iterate_over_mappings(), linux_find_memory_regions_full(), linux_proc_xfer_partial(), linux_proc_xfer_spu(), myread(), proc_get_status(), proc_get_traced_sysentry(), proc_get_traced_sysexit(), procfs_xfer_auxv(), procfs_xfer_memory(), regcache_xfer_part(), remote_fileio_func_read(), ser_base_read_error_fd(), ser_unix_read_prim(), spu_proc_xfer_spu(), stdio_file_read(), tfile_read(), and value_fetch_lazy().