GDB (xrefs): /home/stan/gdb/src/gdb/expprint.c File Reference
/home/stan/gdb/src/gdb/expprint.c File Reference
#include "defs.h"
#include "symtab.h"
#include "gdbtypes.h"
#include "expression.h"
#include "value.h"
#include "language.h"
#include "parser-defs.h"
#include "user-regs.h"
#include "target.h"
#include "gdb_string.h"
#include "block.h"
#include "objfiles.h"
#include "gdb_assert.h"
#include "valprint.h"
#include <ctype.h>
#include "std-operator.def"
Defines
#define OP(name)
Functions
void print_expression (struct expression *exp, struct ui_file *stream)
void print_subexp (struct expression *exp, int *pos, struct ui_file *stream, enum precedence prec)
void print_subexp_standard (struct expression *exp, int *pos, struct ui_file *stream, enum precedence prec)
char * op_string (enum exp_opcode op)
static int dump_subexp_body (struct expression *exp, struct ui_file *, int)
char * op_name (struct expression *exp, enum exp_opcode opcode)
char * op_name_standard (enum exp_opcode opcode)
void dump_raw_expression (struct expression *exp, struct ui_file *stream, char *note)
int dump_subexp (struct expression *exp, struct ui_file *stream, int elt)
int dump_subexp_body_standard (struct expression *exp, struct ui_file *stream, int elt)
void dump_prefix_expression (struct expression *exp, struct ui_file *stream)
Define Documentation
#define OP (name)
Value:
case name:              \
      return #name ;
Function Documentation
void dump_prefix_expression (struct expression * exp, struct ui_file * stream)
Definition at line 1031 of file expprint.c.
References dump_subexp(), fprintf_filtered(), fputs_filtered(), gdb_print_host_address(), language_defn::la_name, expression::language_defn, expression::nelts, and print_expression().
Referenced by parse_exp_in_context_1(), and stap_parse_probe_arguments().
void dump_raw_expression (struct expression * exp, struct ui_file * stream, char * note)
Definition at line 687 of file expprint.c.
References expression::elts, fprintf_filtered(), gdb_print_host_address(), language_defn::la_name, expression::language_defn, exp_element::longconst, expression::nelts, op_name(), exp_element::opcode, and print_longest().
Referenced by parse_exp_in_context_1(), and stap_parse_probe_arguments().
int dump_subexp (struct expression * exp, struct ui_file * stream, int elt)
Definition at line 730 of file expprint.c.
References dump_subexp_body(), expression::elts, fprintf_filtered(), op_name(), and exp_element::opcode.
Referenced by ada_dump_subexp_body(), dump_prefix_expression(), and dump_subexp_body_standard().
static int dump_subexp_body (struct expression * exp, struct ui_file * stream, int elt) [static]
Definition at line 756 of file expprint.c.
References exp_descriptor::dump_subexp_body, language_defn::la_exp_desc, and expression::language_defn.
Referenced by dump_subexp().
int dump_subexp_body_standard (struct expression * exp, struct ui_file * stream, int elt)
Definition at line 764 of file expprint.c.
References exp_element::block, BYTES_TO_EXP_ELEM, exp_element::doubleconst, dump_subexp(), expression::elts, fprintf_filtered(), fputs_filtered(), gdb_print_host_address(), exp_element::internalvar, internalvar_name(), len, exp_element::longconst, LONGEST, longest_to_int(), exp_element::objfile, objfile_name(), exp_element::opcode, op_print::opcode, plongest(), exp_element::string, exp_element::symbol, SYMBOL_PRINT_NAME, exp_element::type, and type_print().
Referenced by ada_dump_subexp_body().
char* op_name (struct expression * exp, enum exp_opcode opcode)
Definition at line 655 of file expprint.c.
References language_defn::la_exp_desc, expression::language_defn, and exp_descriptor::op_name.
Referenced by dump_raw_expression(), dump_subexp(), and gen_expr().
char* op_name_standard (enum exp_opcode opcode)
Definition at line 664 of file expprint.c.
References xsnprintf().
Referenced by ada_op_name().
char* op_string (enum exp_opcode op)
Definition at line 635 of file expprint.c.
References current_language, language_defn::la_op_print_tab, op_print::opcode, and op_print::string.
Referenced by ada_value_binop().
void print_expression (struct expression * exp, struct ui_file * stream)
Definition at line 38 of file expprint.c.
References PREC_NULL, and print_subexp().
Referenced by append_exp(), and dump_prefix_expression().
void print_subexp (struct expression * exp, int * pos, struct ui_file * stream, enum precedence prec)
Definition at line 51 of file expprint.c.
References language_defn::la_exp_desc, expression::language_defn, and exp_descriptor::print_subexp.
Referenced by ada_print_subexp(), print_expression(), and print_subexp_standard().
void print_subexp_standard (struct expression * exp, int * pos, struct ui_file * stream, enum precedence prec)
Definition at line 60 of file expprint.c.
References _, exp_element::block, BLOCK_FUNCTION, builtin_type::builtin_char, BYTES_TO_EXP_ELEM, exp_element::doubleconst, expression::elts, error(), fprintf_filtered(), fprintf_unfiltered(), fputs_filtered(), fputs_unfiltered(), gdb_assert, expression::gdbarch, get_no_prettyformat_print_options(), get_user_print_options(), exp_element::internalvar, internalvar_name(), language_defn::la_language, language_defn::la_name, language_defn::la_name_of_this, language_defn::la_op_print_tab, LA_PRINT_STRING, language_c, expression::language_defn, exp_element::longconst, LONGEST, longest_to_int(), name, exp_element::opcode, op_print::opcode, PREC_ABOVE_COMMA, PREC_ASSIGN, PREC_BUILTIN_FUNCTION, PREC_COMMA, PREC_HYPER, PREC_NULL, PREC_PREFIX, PREC_SUFFIX, op_print::precedence, print_subexp(), op_print::right_assoc, selector, strchr(), exp_element::string, op_print::string, exp_element::symbol, SYMBOL_PRINT_NAME, target_read_string(), exp_element::type, TYPE_CODE, TYPE_CODE_FUNC, type_name_no_tag(), type_print(), value_at_lazy(), value_from_double(), value_from_longest(), value_print(), and xfree().
Referenced by ada_print_subexp().