GDB (xrefs): /home/stan/gdb/src/gdb/expression.h File Reference
/home/stan/gdb/src/gdb/expression.h File Reference
#include "symtab.h"
#include "doublest.h"
#include "std-operator.def"
#include "ada-operator.def"
Classes
union exp_element
struct expression
Defines
#define OP(name) name ,
#define EXP_ELEM_TO_BYTES(elements) ((elements) * sizeof (union exp_element))
#define BYTES_TO_EXP_ELEM(bytes) (((bytes) + sizeof (union exp_element) - 1) / sizeof (union exp_element))
Enumerations
enum exp_opcode
enum noside { EVAL_NORMAL, EVAL_SKIP, EVAL_AVOID_SIDE_EFFECTS }
Functions
OP (BINOP_ADD) OP(BINOP_SUB) OP(BINOP_MUL) OP(BINOP_DIV) OP(BINOP_REM) OP(BINOP_MOD) OP(BINOP_LSH) OP(BINOP_RSH) OP(BINOP_LOGICAL_AND) OP(BINOP_LOGICAL_OR) OP(BINOP_BITWISE_AND) OP(BINOP_BITWISE_IOR) OP(BINOP_BITWISE_XOR) OP(BINOP_EQUAL) OP(BINOP_NOTEQUAL) OP(BINOP_LESS) OP(BINOP_GTR) OP(BINOP_LEQ) OP(BINOP_GEQ) OP(BINOP_REPEAT) OP(BINOP_ASSIGN) OP(BINOP_COMMA) OP(BINOP_SUBSCRIPT) OP(BINOP_EXP) OP(BINOP_MIN) OP(BINOP_MAX) OP(BINOP_IN) OP(TERNOP_COND) OP(UNOP_NEG) OP(UNOP_LOGICAL_NOT) OP(UNOP_COMPLEMENT) OP(UNOP_IND) OP(UNOP_ADDR) OP(UNOP_PREINCREMENT) OP(UNOP_POSTINCREMENT) OP(UNOP_PREDECREMENT) OP(UNOP_POSTDECREMENT) OP(UNOP_SIZEOF) OP(UNOP_PLUS) OP(UNOP_CAP) OP(OP_BOOL) OP(OP_M2_STRING) OP_UNUSED_LAST
struct expression * parse_expression (const char *)
struct type * parse_expression_for_completion (const char *, char **, enum type_code *)
struct expression * parse_exp_1 (const char **, CORE_ADDR pc, const struct block *, int)
struct value * evaluate_subexp_standard (struct type *, struct expression *, int *, enum noside)
void print_expression (struct expression *, struct ui_file *)
char * op_name (struct expression *exp, enum exp_opcode opcode)
char * op_string (enum exp_opcode)
void dump_raw_expression (struct expression *, struct ui_file *, char *)
void dump_prefix_expression (struct expression *, struct ui_file *)
Variables
int parse_completion
struct block * innermost_block
Define Documentation
#define BYTES_TO_EXP_ELEM (bytes) (((bytes) + sizeof (union exp_element) - 1) / sizeof (union exp_element))
Definition at line 93 of file expression.h.
Referenced by ada_forward_operator_length(), dump_subexp_body_standard(), evaluate_subexp_c(), evaluate_subexp_java(), evaluate_subexp_opencl(), evaluate_subexp_standard(), extract_field_op(), gen_expr(), operator_length_standard(), print_subexp_standard(), resolve_subexp(), write_exp_bitstring(), write_exp_string(), and write_exp_string_vector().
#define EXP_ELEM_TO_BYTES (elements) ((elements) * sizeof (union exp_element))
Definition at line 91 of file expression.h.
Referenced by copy_exp(), initialize_expout(), insert_exp(), prefixify_subexp(), reallocate_expout(), replace_operator_with_call(), and write_exp_string_vector().
#define OP (name) name ,
Definition at line 45 of file expression.h.
Enumeration Type Documentation
enum exp_opcode
Definition at line 43 of file expression.h.
enum noside
Enumerator:
EVAL_NORMAL
EVAL_SKIP
EVAL_AVOID_SIDE_EFFECTS
Definition at line 119 of file expression.h.
Function Documentation
void dump_prefix_expression (struct expression * , struct ui_file *)
Definition at line 1031 of file expprint.c.
References dump_subexp(), fprintf_filtered(), fputs_filtered(), gdb_print_host_address(), language_defn::la_name, expression::language_defn, expression::nelts, and print_expression().
Referenced by parse_exp_in_context_1(), and stap_parse_probe_arguments().
void dump_raw_expression (struct expression * , struct ui_file * , char *)
Definition at line 687 of file expprint.c.
References expression::elts, fprintf_filtered(), gdb_print_host_address(), language_defn::la_name, expression::language_defn, exp_element::longconst, expression::nelts, op_name(), exp_element::opcode, and print_longest().
Referenced by parse_exp_in_context_1(), and stap_parse_probe_arguments().
struct value* evaluate_subexp_standard (struct type * , struct expression * , int * , enum noside) [read]
exp_opcode::OP (BINOP_ADD)
char* op_name (struct expression * exp, enum exp_opcode opcode)
Definition at line 655 of file expprint.c.
References language_defn::la_exp_desc, expression::language_defn, and exp_descriptor::op_name.
Referenced by dump_raw_expression(), dump_subexp(), and gen_expr().
char* op_string (enum exp_opcode)
Definition at line 635 of file expprint.c.
References current_language, language_defn::la_op_print_tab, op_print::opcode, and op_print::string.
Referenced by ada_value_binop().
struct expression* parse_exp_1 (const char ** , CORE_ADDR pc, const struct block * , int) [read]
Definition at line 1134 of file parse.c.
References parse_exp_in_context().
Referenced by ada_read_renaming_var_value(), agent_eval_command_one(), create_excep_cond_exprs(), encode_actions_1(), find_condition_and_thread(), init_breakpoint_sal(), maint_agent_printf_command(), parse_cmd_to_aexpr(), parse_expression(), parse_to_comma_and_eval(), set_breakpoint_condition(), update_breakpoint_locations(), update_watchpoint(), validate_actionline(), varobj_create(), varobj_set_value(), and watch_command_1().
struct expression* parse_expression (const char *) [read]
Definition at line 1283 of file parse.c.
References _, error(), and parse_exp_1().
Referenced by display_command(), do_one_display(), execute_control_command(), gdb_eval(), gnuv3_get_type_from_type_info(), info_mach_region_command(), init_if_undefined_command(), maintenance_print_type(), mi_cmd_data_evaluate_expression(), output_command_const(), parse_and_eval(), parse_and_eval_address(), parse_and_eval_long(), parse_and_eval_type(), print_command_1(), print_object_command(), print_variable_or_computed(), return_command(), set_command(), whatis_exp(), and x_command().
struct type* parse_expression_for_completion (const char * , char ** , enum type_code *) [read]
Definition at line 1302 of file parse.c.
References evaluate_subexpression_type(), expout_completion_name, expout_last_struct, expout_tag_completion_type, extract_field_op(), parse_completion, parse_exp_in_context(), gdb_exception::reason, RETURN_MASK_ERROR, TRY_CATCH, TYPE_CODE_UNDEF, value_type(), and xfree().
void print_expression (struct expression * , struct ui_file *)
Definition at line 38 of file expprint.c.
References PREC_NULL, and print_subexp().
Referenced by append_exp(), and dump_prefix_expression().
Variable Documentation
struct block* innermost_block
Definition at line 75 of file parse.c.
Referenced by clear_symtab_users(), display_command(), do_one_display(), free_objfile(), push_variable(), resolve_subexp(), set_breakpoint_condition(), varobj_create(), watch_command_1(), and write_var_from_sym().
int parse_completion
Definition at line 84 of file parse.c.
Referenced by lex_one_token(), mark_completion_tag(), mark_struct_expression(), parse_exp_in_context_1(), parse_expression_for_completion(), and yylex().