GDB (xrefs): /home/stan/gdb/linux/gdb/f-exp.c File Reference
/home/stan/gdb/linux/gdb/f-exp.c File Reference
#include "defs.h"
#include "gdb_string.h"
#include "expression.h"
#include "value.h"
#include "parser-defs.h"
#include "language.h"
#include "f-lang.h"
#include "bfd.h"
#include "symfile.h"
#include "objfiles.h"
#include "block.h"
#include <ctype.h>
Classes
union YYSTYPE
union yyalloc
struct token
struct f77_boolean_val
Defines
#define YYBISON 1
#define YYBISON_VERSION "2.5"
#define YYSKELETON_NAME "yacc.c"
#define YYPURE 0
#define YYPUSH 0
#define YYPULL 1
#define YYLSP_NEEDED 0
#define parse_type builtin_type (parse_gdbarch)
#define parse_f_type builtin_f_type (parse_gdbarch)
#define yymaxdepth f_maxdepth
#define yyparse f_parse
#define yylex f_lex
#define yyerror f_error
#define yylval f_lval
#define yychar f_char
#define yydebug f_debug
#define yypact f_pact
#define yyr1 f_r1
#define yyr2 f_r2
#define yydef f_def
#define yychk f_chk
#define yypgo f_pgo
#define yyact f_act
#define yyexca f_exca
#define yyerrflag f_errflag
#define yynerrs f_nerrs
#define yyps f_ps
#define yypv f_pv
#define yys f_s
#define yy_yys f_yys
#define yystate f_state
#define yytmp f_tmp
#define yyv f_v
#define yy_yyv f_yyv
#define yyval f_val
#define yylloc f_lloc
#define yyreds f_reds /* With YYDEBUG defined */
#define yytoks f_toks /* With YYDEBUG defined */
#define yyname f_name /* With YYDEBUG defined */
#define yyrule f_rule /* With YYDEBUG defined */
#define yylhs f_yylhs
#define yylen f_yylen
#define yydefred f_yydefred
#define yydgoto f_yydgoto
#define yysindex f_yysindex
#define yyrindex f_yyrindex
#define yygindex f_yygindex
#define yytable f_yytable
#define yycheck f_yycheck
#define yyss f_yyss
#define yysslim f_yysslim
#define yyssp f_yyssp
#define yystacksize f_yystacksize
#define yyvs f_yyvs
#define yyvsp f_yyvsp
#define YYDEBUG 1 /* Default to yydebug support */
#define YYFPRINTF parser_fprintf
#define YYERROR_VERBOSE 0
#define YYTOKEN_TABLE 0
#define YYTOKENTYPE
#define INT 258
#define FLOAT 259
#define STRING_LITERAL 260
#define BOOLEAN_LITERAL 261
#define NAME 262
#define TYPENAME 263
#define NAME_OR_INT 264
#define SIZEOF 265
#define ERROR 266
#define INT_KEYWORD 267
#define INT_S2_KEYWORD 268
#define LOGICAL_S1_KEYWORD 269
#define LOGICAL_S2_KEYWORD 270
#define LOGICAL_S8_KEYWORD 271
#define LOGICAL_KEYWORD 272
#define REAL_KEYWORD 273
#define REAL_S8_KEYWORD 274
#define REAL_S16_KEYWORD 275
#define COMPLEX_S8_KEYWORD 276
#define COMPLEX_S16_KEYWORD 277
#define COMPLEX_S32_KEYWORD 278
#define BOOL_AND 279
#define BOOL_OR 280
#define BOOL_NOT 281
#define CHARACTER 282
#define VARIABLE 283
#define ASSIGN_MODIFY 284
#define ABOVE_COMMA 285
#define NOTEQUAL 286
#define EQUAL 287
#define GEQ 288
#define LEQ 289
#define GREATERTHAN 290
#define LESSTHAN 291
#define RSH 292
#define LSH 293
#define STARSTAR 294
#define UNARY 295
#define YYSTYPE_IS_TRIVIAL 1
#define yystype YYSTYPE /* obsolescent; will be withdrawn */
#define YYSTYPE_IS_DECLARED 1
#define YYSIZE_T unsigned int
#define YYSIZE_MAXIMUM ((YYSIZE_T) -1)
#define YY_(msgid) msgid
#define YYUSE(e) ((void) (e))
#define YYID(n) (n)
#define YYSTACK_ALLOC YYMALLOC
#define YYSTACK_FREE YYFREE
#define YYSTACK_ALLOC_MAXIMUM YYSIZE_MAXIMUM
#define YYMALLOC xmalloc
#define YYFREE xfree
#define YYSTACK_GAP_MAXIMUM (sizeof (union yyalloc) - 1)
#define YYSTACK_BYTES(N)
#define YYCOPY_NEEDED 1
#define YYSTACK_RELOCATE(Stack_alloc, Stack)
#define YYCOPY(To, From, Count)
#define YYFINAL 47
#define YYLAST 529
#define YYNTOKENS 57
#define YYNNTS 18
#define YYNRULES 86
#define YYNSTATES 131
#define YYUNDEFTOK 2
#define YYMAXUTOK 295
#define YYTRANSLATE(YYX) ((unsigned int) (YYX) <= YYMAXUTOK ? yytranslate[YYX] : YYUNDEFTOK)
#define YYPACT_NINF -57
#define YYTABLE_NINF -1
#define yypact_value_is_default(yystate) ((yystate) == (-57))
#define yytable_value_is_error(yytable_value) YYID (0)
#define yyerrok (yyerrstatus = 0)
#define yyclearin (yychar = YYEMPTY)
#define YYEMPTY (-2)
#define YYEOF 0
#define YYACCEPT goto yyacceptlab
#define YYABORT goto yyabortlab
#define YYERROR goto yyerrorlab
#define YYFAIL goto yyerrlab
#define YYRECOVERING() (!!yyerrstatus)
#define YYBACKUP(Token, Value)
#define YYTERROR 1
#define YYERRCODE 256
#define YYRHSLOC(Rhs, K) ((Rhs)[K])
#define YYLLOC_DEFAULT(Current, Rhs, N)
#define YY_LOCATION_PRINT(File, Loc) ((void) 0)
#define YYLEX yylex ()
#define YYDPRINTF(Args)
#define YY_SYMBOL_PRINT(Title, Type, Value, Location)
#define YY_STACK_PRINT(Bottom, Top)
#define YY_REDUCE_PRINT(Rule)
#define YYINITDEPTH 200
#define YYMAXDEPTH 10000
#define YYPOPSTACK(N) (yyvsp -= (N), yyssp -= (N))
#define GROWBY_MIN_SIZE 64 /* Minimum amount to grow buffer by */
#define CHECKBUF(size)
Typedefs
typedef union YYSTYPE YYSTYPE
typedef unsigned char yytype_uint8
typedef short int yytype_int8
typedef unsigned short int yytype_uint16
typedef short int yytype_int16
Enumerations
enum yytokentype {
INT = 258, NULL_PTR = 259, CHARLIT = 260, FLOAT = 261,
TRUEKEYWORD = 262, FALSEKEYWORD = 263, COLONCOLON = 264, STRING = 265,
NAME = 266, DOT_ID = 267, DOT_ALL = 268, SPECIAL_VARIABLE = 269,
ASSIGN = 270, ELSE = 271, THEN = 272, XOR = 273,
OR = 274, _AND_ = 275, DOTDOT = 276, IN = 277,
GEQ = 278, LEQ = 279, NOTEQUAL = 280, UNARY = 281,
REM = 282, MOD = 283, NOT = 284, ABS = 285,
STARSTAR = 286, VAR = 287, ARROW = 288, TICK_LENGTH = 289,
TICK_LAST = 290, TICK_FIRST = 291, TICK_ADDRESS = 292, TICK_ACCESS = 293,
TICK_MODULUS = 294, TICK_MIN = 295, TICK_MAX = 296, TICK_VAL = 297,
TICK_TAG = 298, TICK_SIZE = 299, TICK_RANGE = 300, TICK_POS = 301,
NEW = 302, OTHERS = 303, INT = 258, FLOAT = 259,
DECFLOAT = 260, STRING = 261, NSSTRING = 262, SELECTOR = 263,
CHAR = 264, NAME = 265, UNKNOWN_CPP_NAME = 266, COMPLETE = 267,
TYPENAME = 268, CLASSNAME = 269, OBJC_LBRAC = 270, NAME_OR_INT = 271,
OPERATOR = 272, STRUCT = 273, CLASS = 274, UNION = 275,
ENUM = 276, SIZEOF = 277, UNSIGNED = 278, COLONCOLON = 279,
TEMPLATE = 280, ERROR = 281, NEW = 282, DELETE = 283,
REINTERPRET_CAST = 284, DYNAMIC_CAST = 285, STATIC_CAST = 286, CONST_CAST = 287,
ENTRY = 288, TYPEOF = 289, DECLTYPE = 290, TYPEID = 291,
SIGNED_KEYWORD = 292, LONG = 293, SHORT = 294, INT_KEYWORD = 295,
CONST_KEYWORD = 296, VOLATILE_KEYWORD = 297, DOUBLE_KEYWORD = 298, VARIABLE = 299,
ASSIGN_MODIFY = 300, TRUEKEYWORD = 301, FALSEKEYWORD = 302, ABOVE_COMMA = 303,
OROR = 304, ANDAND = 305, NOTEQUAL = 306, EQUAL = 307,
GEQ = 308, LEQ = 309, RSH = 310, LSH = 311,
DECREMENT = 312, INCREMENT = 313, UNARY = 314, DOT_STAR = 315,
ARROW_STAR = 316, ARROW = 317, BLOCKNAME = 318, FILENAME = 319,
DOTDOTDOT = 320, INT = 258, FLOAT = 259, NAME = 260,
STRUCT = 261, CLASS = 262, UNION = 263, ENUM = 264,
SIZEOF = 265, UNSIGNED = 266, COLONCOLON = 267, TEMPLATE = 268,
ERROR = 269, NEW = 270, DELETE = 271, OPERATOR = 272,
STATIC_CAST = 273, REINTERPRET_CAST = 274, DYNAMIC_CAST = 275, SIGNED_KEYWORD = 276,
LONG = 277, SHORT = 278, INT_KEYWORD = 279, CONST_KEYWORD = 280,
VOLATILE_KEYWORD = 281, DOUBLE_KEYWORD = 282, BOOL = 283, ELLIPSIS = 284,
RESTRICT = 285, VOID = 286, FLOAT_KEYWORD = 287, CHAR = 288,
WCHAR_T = 289, ASSIGN_MODIFY = 290, TRUEKEYWORD = 291, FALSEKEYWORD = 292,
DEMANGLER_SPECIAL = 293, CONSTRUCTION_VTABLE = 294, CONSTRUCTION_IN = 295, OROR = 296,
ANDAND = 297, NOTEQUAL = 298, EQUAL = 299, GEQ = 300,
LEQ = 301, RSH = 302, LSH = 303, DECREMENT = 304,
INCREMENT = 305, UNARY = 306, ARROW = 307, INT = 258,
FLOAT = 259, STRING_LITERAL = 260, BOOLEAN_LITERAL = 261, NAME = 262,
TYPENAME = 263, NAME_OR_INT = 264, SIZEOF = 265, ERROR = 266,
INT_KEYWORD = 267, INT_S2_KEYWORD = 268, LOGICAL_S1_KEYWORD = 269, LOGICAL_S2_KEYWORD = 270,
LOGICAL_S8_KEYWORD = 271, LOGICAL_KEYWORD = 272, REAL_KEYWORD = 273, REAL_S8_KEYWORD = 274,
REAL_S16_KEYWORD = 275, COMPLEX_S8_KEYWORD = 276, COMPLEX_S16_KEYWORD = 277, COMPLEX_S32_KEYWORD = 278,
BOOL_AND = 279, BOOL_OR = 280, BOOL_NOT = 281, CHARACTER = 282,
VARIABLE = 283, ASSIGN_MODIFY = 284, ABOVE_COMMA = 285, NOTEQUAL = 286,
EQUAL = 287, GEQ = 288, LEQ = 289, GREATERTHAN = 290,
LESSTHAN = 291, RSH = 292, LSH = 293, STARSTAR = 294,
UNARY = 295, INT = 258, FLOAT = 259, RAW_STRING = 260,
STRING = 261, CHAR = 262, NAME = 263, TYPENAME = 264,
COMPLETE = 265, NAME_OR_INT = 266, TRUE_KEYWORD = 267, FALSE_KEYWORD = 268,
STRUCT_KEYWORD = 269, INTERFACE_KEYWORD = 270, TYPE_KEYWORD = 271, CHAN_KEYWORD = 272,
SIZEOF_KEYWORD = 273, LEN_KEYWORD = 274, CAP_KEYWORD = 275, NEW_KEYWORD = 276,
IOTA_KEYWORD = 277, NIL_KEYWORD = 278, CONST_KEYWORD = 279, DOTDOTDOT = 280,
ENTRY = 281, ERROR = 282, BYTE_KEYWORD = 283, DOLLAR_VARIABLE = 284,
ASSIGN_MODIFY = 285, ABOVE_COMMA = 286, OROR = 287, ANDAND = 288,
ANDNOT = 289, NOTEQUAL = 290, EQUAL = 291, GEQ = 292,
LEQ = 293, RSH = 294, LSH = 295, DECREMENT = 296,
INCREMENT = 297, UNARY = 298, LEFT_ARROW = 299, INTEGER_LITERAL = 258,
FLOATING_POINT_LITERAL = 259, IDENTIFIER = 260, STRING_LITERAL = 261, BOOLEAN_LITERAL = 262,
TYPENAME = 263, NAME_OR_INT = 264, ERROR = 265, LONG = 266,
SHORT = 267, BYTE = 268, INT = 269, CHAR = 270,
BOOLEAN = 271, DOUBLE = 272, FLOAT = 273, VARIABLE = 274,
ASSIGN_MODIFY = 275, SUPER = 276, NEW = 277, OROR = 278,
ANDAND = 279, NOTEQUAL = 280, EQUAL = 281, GEQ = 282,
LEQ = 283, RSH = 284, LSH = 285, DECREMENT = 286,
INCREMENT = 287, INT = 258, HEX = 259, ERROR = 260,
UINT = 261, M2_TRUE = 262, M2_FALSE = 263, CHAR = 264,
FLOAT = 265, STRING = 266, NAME = 267, BLOCKNAME = 268,
IDENT = 269, VARNAME = 270, TYPENAME = 271, SIZE = 272,
CAP = 273, ORD = 274, HIGH = 275, ABS = 276,
MIN_FUNC = 277, MAX_FUNC = 278, FLOAT_FUNC = 279, VAL = 280,
CHR = 281, ODD = 282, TRUNC = 283, TSIZE = 284,
INC = 285, DEC = 286, INCL = 287, EXCL = 288,
COLONCOLON = 289, INTERNAL_VAR = 290, ABOVE_COMMA = 291, ASSIGN = 292,
IN = 293, NOTEQUAL = 294, GEQ = 295, LEQ = 296,
OROR = 297, LOGICAL_AND = 298, MOD = 299, DIV = 300,
UNARY = 301, DOT = 302, NOT = 303, QID = 304,
INT = 258, FLOAT = 259, STRING = 260, FIELDNAME = 261,
COMPLETE = 262, NAME = 263, TYPENAME = 264, NAME_OR_INT = 265,
STRUCT = 266, CLASS = 267, SIZEOF = 268, COLONCOLON = 269,
ERROR = 270, VARIABLE = 271, THIS = 272, TRUEKEYWORD = 273,
FALSEKEYWORD = 274, ABOVE_COMMA = 275, ASSIGN = 276, NOT = 277,
OR = 278, XOR = 279, ANDAND = 280, NOTEQUAL = 281,
GEQ = 282, LEQ = 283, MOD = 284, DIV = 285,
RSH = 286, LSH = 287, DECREMENT = 288, INCREMENT = 289,
UNARY = 290, ARROW = 291, BLOCKNAME = 292
}
Functions
int yyparse (void)
static int yylex (void)
void yyerror (char *)
static void growbuf_by_size (int)
static int match_string_literal (void)
static int parse_number (const char *, int, int, YYSTYPE *)
static void yy_symbol_value_print (FILE *yyoutput, int yytype, YYSTYPE const *const yyvaluep)
static void yy_symbol_print (FILE *yyoutput, int yytype, YYSTYPE const *const yyvaluep)
static void yy_stack_print (yytype_int16 *yybottom, yytype_int16 *yytop)
static void yy_reduce_print (YYSTYPE *yyvsp, int yyrule)
static void yydestruct (char *yymsg, int yytype, YYSTYPE *yyvaluep) const
Variables
static const yytype_uint8 yytranslate []
static const yytype_uint8 yyprhs []
static const yytype_int8 yyrhs []
static const yytype_uint16 yyrline []
static const char *const yytname []
static const yytype_uint8 yyr1 []
static const yytype_uint8 yyr2 []
static const yytype_uint8 yydefact []
static const yytype_int8 yydefgoto []
static const yytype_int16 yypact []
static const yytype_int8 yypgoto []
static const yytype_uint8 yytable []
static const yytype_int8 yycheck []
static const yytype_uint8 yystos []
int yydebug
int yychar
YYSTYPE yylval
int yynerrs
static struct token dot_ops []
static struct f77_boolean_val boolean_values []
static struct token f77_keywords []
static char * tempbuf
static int tempbufsize
static int tempbufindex
Define Documentation
#define ABOVE_COMMA 285
Definition at line 256 of file f-exp.c.
#define ASSIGN_MODIFY 284
Definition at line 255 of file f-exp.c.
#define BOOL_AND 279
Definition at line 250 of file f-exp.c.
#define BOOL_NOT 281
Definition at line 252 of file f-exp.c.
#define BOOL_OR 280
Definition at line 251 of file f-exp.c.
#define BOOLEAN_LITERAL 261
Definition at line 232 of file f-exp.c.
Referenced by yylex().
#define CHARACTER 282
Definition at line 253 of file f-exp.c.
#define CHECKBUF (size)
Value:
do { \
    if (tempbufindex + (size) >= tempbufsize) \
      { \
        growbuf_by_size (size); \
      } \
  } while (0);
Definition at line 2858 of file f-exp.c.
Referenced by match_string_literal().
#define COMPLEX_S16_KEYWORD 277
Definition at line 248 of file f-exp.c.
#define COMPLEX_S32_KEYWORD 278
Definition at line 249 of file f-exp.c.
#define COMPLEX_S8_KEYWORD 276
Definition at line 247 of file f-exp.c.
#define EQUAL 287
Definition at line 258 of file f-exp.c.
#define ERROR 266
Definition at line 237 of file f-exp.c.
#define FLOAT 259
Definition at line 230 of file f-exp.c.
#define GEQ 288
Definition at line 259 of file f-exp.c.
#define GREATERTHAN 290
Definition at line 261 of file f-exp.c.
#define GROWBY_MIN_SIZE 64 /* Minimum amount to grow buffer by */
Definition at line 2856 of file f-exp.c.
Referenced by growbuf_by_size().
#define INT 258
Definition at line 229 of file f-exp.c.
#define INT_KEYWORD 267
Definition at line 238 of file f-exp.c.
#define INT_S2_KEYWORD 268
Definition at line 239 of file f-exp.c.
#define LEQ 289
Definition at line 260 of file f-exp.c.
#define LESSTHAN 291
Definition at line 262 of file f-exp.c.
#define LOGICAL_KEYWORD 272
Definition at line 243 of file f-exp.c.
#define LOGICAL_S1_KEYWORD 269
Definition at line 240 of file f-exp.c.
#define LOGICAL_S2_KEYWORD 270
Definition at line 241 of file f-exp.c.
#define LOGICAL_S8_KEYWORD 271
Definition at line 242 of file f-exp.c.
#define LSH 293
Definition at line 264 of file f-exp.c.
#define NAME 262
Definition at line 233 of file f-exp.c.
#define NAME_OR_INT 264
Definition at line 235 of file f-exp.c.
#define NOTEQUAL 286
Definition at line 257 of file f-exp.c.
#define parse_f_type builtin_f_type (parse_gdbarch)
Definition at line 86 of file f-exp.c.
#define parse_type builtin_type (parse_gdbarch)
Definition at line 85 of file f-exp.c.
Referenced by parse_number().
#define REAL_KEYWORD 273
Definition at line 244 of file f-exp.c.
#define REAL_S16_KEYWORD 275
Definition at line 246 of file f-exp.c.
#define REAL_S8_KEYWORD 274
Definition at line 245 of file f-exp.c.
#define RSH 292
Definition at line 263 of file f-exp.c.
#define SIZEOF 265
Definition at line 236 of file f-exp.c.
#define STARSTAR 294
Definition at line 265 of file f-exp.c.
#define STRING_LITERAL 260
Definition at line 231 of file f-exp.c.
Referenced by match_string_literal(), and yylex().
#define TYPENAME 263
Definition at line 234 of file f-exp.c.
#define UNARY 295
Definition at line 266 of file f-exp.c.
#define VARIABLE 283
Definition at line 254 of file f-exp.c.
#define YY_ (msgid) msgid
Definition at line 375 of file f-exp.c.
#define YY_LOCATION_PRINT (File, Loc) ((void) 0)
Definition at line 992 of file f-exp.c.
#define YY_REDUCE_PRINT (Rule)
Value:
do {                                    \
  if (yydebug)                          \
    yy_reduce_print (yyvsp, Rule); \
} while (YYID (0))
Definition at line 1151 of file f-exp.c.
#define YY_STACK_PRINT (Bottom, Top)
Value:
do {                                                            \
  if (yydebug)                                                  \
    yy_stack_print ((Bottom), (Top));                           \
} while (YYID (0))
Definition at line 1113 of file f-exp.c.
#define YY_SYMBOL_PRINT (Title, Type, Value, Location)
Value:
do {                                                                      \
  if (yydebug)                                                            \
    {                                                                     \
      YYFPRINTF (stderr, "%s ", Title);                                   \
      yy_symbol_print (stderr,                                            \
                  Type, Value); \
      YYFPRINTF (stderr, "\n");                                           \
    }                                                                     \
} while (YYID (0))
Definition at line 1018 of file f-exp.c.
Referenced by yydestruct().
#define yy_yys f_yys
Definition at line 115 of file f-exp.c.
#define yy_yyv f_yyv
Definition at line 119 of file f-exp.c.
#define YYABORT goto yyabortlab
Definition at line 921 of file f-exp.c.
#define YYACCEPT goto yyacceptlab
Definition at line 920 of file f-exp.c.
#define yyact f_act
Definition at line 108 of file f-exp.c.
#define YYBACKUP (Token, Value)
Value:
do                                                              \
  if (yychar == YYEMPTY && yylen == 1)                          \
    {                                                           \
      yychar = (Token);                                         \
      yylval = (Value);                                         \
      YYPOPSTACK (1);                                           \
      goto yybackup;                                            \
    }                                                           \
  else                                                          \
    {                                                           \
      yyerror (YY_("syntax error: cannot back up")); \
      YYERROR;                                                  \
    }                                                           \
while (YYID (0))
Definition at line 942 of file f-exp.c.
#define YYBISON 1
Definition at line 44 of file f-exp.c.
#define YYBISON_VERSION "2.5"
Definition at line 47 of file f-exp.c.
#define yychar f_char
Definition at line 100 of file f-exp.c.
#define yycheck f_yycheck
Definition at line 134 of file f-exp.c.
#define yychk f_chk
Definition at line 106 of file f-exp.c.
#define yyclearin (yychar = YYEMPTY)
Definition at line 916 of file f-exp.c.
#define YYCOPY (To, From, Count)
Value:
do                                      \
        {                                       \
          YYSIZE_T yyi;                         \
          for (yyi = 0; yyi < (Count); yyi++)   \
            (To)[yyi] = (From)[yyi];            \
        }                                       \
      while (YYID (0))
Definition at line 521 of file f-exp.c.
#define YYCOPY_NEEDED 1
Definition at line 493 of file f-exp.c.
#define yydebug f_debug
Definition at line 101 of file f-exp.c.
#define YYDEBUG 1 /* Default to yydebug support */
Definition at line 143 of file f-exp.c.
#define yydef f_def
Definition at line 105 of file f-exp.c.
#define yydefred f_yydefred
Definition at line 128 of file f-exp.c.
#define yydgoto f_yydgoto
Definition at line 129 of file f-exp.c.
#define YYDPRINTF (Args)
Value:
do {                                            \
  if (yydebug)                                  \
    YYFPRINTF Args;                             \
} while (YYID (0))
Definition at line 1012 of file f-exp.c.
#define YYEMPTY (-2)
Definition at line 917 of file f-exp.c.
#define YYEOF 0
Definition at line 918 of file f-exp.c.
#define YYERRCODE 256
Definition at line 960 of file f-exp.c.
#define yyerrflag f_errflag
Definition at line 110 of file f-exp.c.
#define yyerrok (yyerrstatus = 0)
Definition at line 915 of file f-exp.c.
#define yyerror f_error
Definition at line 98 of file f-exp.c.
#define YYERROR goto yyerrorlab
Definition at line 922 of file f-exp.c.
#define YYERROR_VERBOSE 0
Definition at line 173 of file f-exp.c.
#define yyexca f_exca
Definition at line 109 of file f-exp.c.
#define YYFAIL goto yyerrlab
Definition at line 932 of file f-exp.c.
#define YYFINAL 47
Definition at line 534 of file f-exp.c.
#define YYFPRINTF parser_fprintf
Definition at line 146 of file f-exp.c.
Referenced by yy_reduce_print(), yy_stack_print(), and yy_symbol_print().
#define YYFREE xfree
Definition at line 463 of file f-exp.c.
#define yygindex f_yygindex
Definition at line 132 of file f-exp.c.
#define YYID (n) (n)
Definition at line 388 of file f-exp.c.
#define YYINITDEPTH 200
Definition at line 1170 of file f-exp.c.
#define YYLAST 529
Definition at line 536 of file f-exp.c.
#define yylen f_yylen
Definition at line 127 of file f-exp.c.
#define yylex f_lex
Definition at line 97 of file f-exp.c.
#define YYLEX yylex ()
Definition at line 1001 of file f-exp.c.
#define yylhs f_yylhs
Definition at line 126 of file f-exp.c.
#define yylloc f_lloc
Definition at line 121 of file f-exp.c.
#define YYLLOC_DEFAULT (Current, Rhs, N)
Value:
do                                                                      \
      if (YYID (N))                                                    \
        {                                                               \
          (Current).first_line   = YYRHSLOC (Rhs, 1).first_line;        \
          (Current).first_column = YYRHSLOC (Rhs, 1).first_column;      \
          (Current).last_line    = YYRHSLOC (Rhs, N).last_line;         \
          (Current).last_column  = YYRHSLOC (Rhs, N).last_column;       \
        }                                                               \
      else                                                              \
        {                                                               \
          (Current).first_line   = (Current).last_line   =              \
            YYRHSLOC (Rhs, 0).last_line;                                \
          (Current).first_column = (Current).last_column =              \
            YYRHSLOC (Rhs, 0).last_column;                              \
        }                                                               \
    while (YYID (0))
Definition at line 969 of file f-exp.c.
#define YYLSP_NEEDED 0
Definition at line 62 of file f-exp.c.
#define yylval f_lval
Definition at line 99 of file f-exp.c.
#define YYMALLOC xmalloc
Definition at line 456 of file f-exp.c.
#define yymaxdepth f_maxdepth
Definition at line 95 of file f-exp.c.
#define YYMAXDEPTH 10000
Definition at line 1181 of file f-exp.c.
#define YYMAXUTOK 295
Definition at line 549 of file f-exp.c.
#define yyname f_name /* With YYDEBUG defined */
Definition at line 124 of file f-exp.c.
#define yynerrs f_nerrs
Definition at line 111 of file f-exp.c.
#define YYNNTS 18
Definition at line 541 of file f-exp.c.
#define YYNRULES 86
Definition at line 543 of file f-exp.c.
#define YYNSTATES 131
Definition at line 545 of file f-exp.c.
#define YYNTOKENS 57
Definition at line 539 of file f-exp.c.
Referenced by yy_symbol_print(), and yy_symbol_value_print().
#define yypact f_pact
Definition at line 102 of file f-exp.c.
#define YYPACT_NINF -57
Definition at line 745 of file f-exp.c.
#define yypact_value_is_default (yystate) ((yystate) == (-57))
Definition at line 832 of file f-exp.c.
#define yyparse f_parse
Definition at line 96 of file f-exp.c.
#define yypgo f_pgo
Definition at line 107 of file f-exp.c.
#define YYPOPSTACK (N) (yyvsp -= (N), yyssp -= (N))
#define yyps f_ps
Definition at line 112 of file f-exp.c.
#define YYPULL 1
Definition at line 59 of file f-exp.c.
#define YYPURE 0
Definition at line 53 of file f-exp.c.
#define YYPUSH 0
Definition at line 56 of file f-exp.c.
#define yypv f_pv
Definition at line 113 of file f-exp.c.
#define yyr1 f_r1
Definition at line 103 of file f-exp.c.
#define yyr2 f_r2
Definition at line 104 of file f-exp.c.
#define YYRECOVERING () (!!yyerrstatus)
Definition at line 940 of file f-exp.c.
#define yyreds f_reds /* With YYDEBUG defined */
Definition at line 122 of file f-exp.c.
#define YYRHSLOC (Rhs, K) ((Rhs)[K])
Definition at line 967 of file f-exp.c.
#define yyrindex f_yyrindex
Definition at line 131 of file f-exp.c.
#define yyrule f_rule /* With YYDEBUG defined */
Definition at line 125 of file f-exp.c.
Referenced by yy_reduce_print().
#define yys f_s
Definition at line 114 of file f-exp.c.
#define yysindex f_yysindex
Definition at line 130 of file f-exp.c.
#define YYSIZE_MAXIMUM ((YYSIZE_T) -1)
Definition at line 365 of file f-exp.c.
#define YYSIZE_T unsigned int
Definition at line 361 of file f-exp.c.
#define YYSKELETON_NAME "yacc.c"
Definition at line 50 of file f-exp.c.
#define yyss f_yyss
Definition at line 135 of file f-exp.c.
#define yysslim f_yysslim
Definition at line 136 of file f-exp.c.
#define yyssp f_yyssp
Definition at line 137 of file f-exp.c.
#define YYSTACK_ALLOC YYMALLOC
Definition at line 442 of file f-exp.c.
#define YYSTACK_ALLOC_MAXIMUM YYSIZE_MAXIMUM
Definition at line 445 of file f-exp.c.
#define YYSTACK_BYTES (N)
Value:
((N) * (sizeof (yytype_int16) + sizeof (YYSTYPE)) \
      + YYSTACK_GAP_MAXIMUM)
Definition at line 489 of file f-exp.c.
#define YYSTACK_FREE YYFREE
Definition at line 443 of file f-exp.c.
#define YYSTACK_GAP_MAXIMUM (sizeof (union yyalloc) - 1)
Definition at line 485 of file f-exp.c.
#define YYSTACK_RELOCATE (Stack_alloc, Stack)
Value:
do                                                                      \
      {                                                                 \
        YYSIZE_T yynewbytes;                                            \
        YYCOPY (&yyptr->Stack_alloc, Stack, yysize);                    \
        Stack = &yyptr->Stack_alloc;                                    \
        yynewbytes = yystacksize * sizeof (*Stack) + YYSTACK_GAP_MAXIMUM; \
        yyptr += yynewbytes / sizeof (*yyptr);                          \
      }                                                                 \
    while (YYID (0))
Definition at line 500 of file f-exp.c.
#define yystacksize f_yystacksize
Definition at line 138 of file f-exp.c.
#define yystate f_state
Definition at line 116 of file f-exp.c.
#define yystype YYSTYPE /* obsolescent; will be withdrawn */
Definition at line 303 of file f-exp.c.
#define YYSTYPE_IS_DECLARED 1
Definition at line 304 of file f-exp.c.
#define YYSTYPE_IS_TRIVIAL 1
Definition at line 302 of file f-exp.c.
#define yytable f_yytable
Definition at line 133 of file f-exp.c.
#define YYTABLE_NINF -1
Definition at line 774 of file f-exp.c.
#define yytable_value_is_error (yytable_value) YYID (0)
Definition at line 835 of file f-exp.c.
#define YYTERROR 1
Definition at line 959 of file f-exp.c.
#define yytmp f_tmp
Definition at line 117 of file f-exp.c.
#define YYTOKEN_TABLE 0
Definition at line 178 of file f-exp.c.
#define YYTOKENTYPE
Definition at line 184 of file f-exp.c.
#define yytoks f_toks /* With YYDEBUG defined */
Definition at line 123 of file f-exp.c.
#define YYTRANSLATE (YYX) ((unsigned int) (YYX) <= YYMAXUTOK ? yytranslate[YYX] : YYUNDEFTOK)
Definition at line 551 of file f-exp.c.
#define YYUNDEFTOK 2
Definition at line 548 of file f-exp.c.
#define YYUSE (e) ((void) (e))
Definition at line 381 of file f-exp.c.
Referenced by yy_symbol_value_print(), and yydestruct().
#define yyv f_v
Definition at line 118 of file f-exp.c.
#define yyval f_val
Definition at line 120 of file f-exp.c.
#define yyvs f_yyvs
Definition at line 139 of file f-exp.c.
#define yyvsp f_yyvsp
Definition at line 140 of file f-exp.c.
Typedef Documentation
typedef union YYSTYPE YYSTYPE
typedef short int yytype_int16
Definition at line 348 of file f-exp.c.
typedef short int yytype_int8
Definition at line 336 of file f-exp.c.
typedef unsigned short int yytype_uint16
Definition at line 342 of file f-exp.c.
typedef unsigned char yytype_uint8
Definition at line 327 of file f-exp.c.
Enumeration Type Documentation
enum yytokentype
Enumerator:
INT
NULL_PTR
CHARLIT
FLOAT
TRUEKEYWORD
FALSEKEYWORD
COLONCOLON
STRING
NAME
DOT_ID
DOT_ALL
SPECIAL_VARIABLE
ASSIGN
ELSE
THEN
XOR
OR
_AND_
DOTDOT
IN
GEQ
LEQ
NOTEQUAL
UNARY
REM
MOD
NOT
ABS
STARSTAR
VAR
ARROW
TICK_LENGTH
TICK_LAST
TICK_FIRST
TICK_ADDRESS
TICK_ACCESS
TICK_MODULUS
TICK_MIN
TICK_MAX
TICK_VAL
TICK_TAG
TICK_SIZE
TICK_RANGE
TICK_POS
NEW
OTHERS
INT
FLOAT
DECFLOAT
STRING
NSSTRING
SELECTOR
CHAR
NAME
UNKNOWN_CPP_NAME
COMPLETE
TYPENAME
CLASSNAME
OBJC_LBRAC
NAME_OR_INT
OPERATOR
STRUCT
CLASS
UNION
ENUM
SIZEOF
UNSIGNED
COLONCOLON
TEMPLATE
ERROR
NEW
DELETE
REINTERPRET_CAST
DYNAMIC_CAST
STATIC_CAST
CONST_CAST
ENTRY
TYPEOF
DECLTYPE
TYPEID
SIGNED_KEYWORD
LONG
SHORT
INT_KEYWORD
CONST_KEYWORD
VOLATILE_KEYWORD
DOUBLE_KEYWORD
VARIABLE
ASSIGN_MODIFY
TRUEKEYWORD
FALSEKEYWORD
ABOVE_COMMA
OROR
ANDAND
NOTEQUAL
EQUAL
GEQ
LEQ
RSH
LSH
DECREMENT
INCREMENT
UNARY
DOT_STAR
ARROW_STAR
ARROW
BLOCKNAME
FILENAME
DOTDOTDOT
INT
FLOAT
NAME
STRUCT
CLASS
UNION
ENUM
SIZEOF
UNSIGNED
COLONCOLON
TEMPLATE
ERROR
NEW
DELETE
OPERATOR
STATIC_CAST
REINTERPRET_CAST
DYNAMIC_CAST
SIGNED_KEYWORD
LONG
SHORT
INT_KEYWORD
CONST_KEYWORD
VOLATILE_KEYWORD
DOUBLE_KEYWORD
BOOL
ELLIPSIS
RESTRICT
VOID
FLOAT_KEYWORD
CHAR
WCHAR_T
ASSIGN_MODIFY
TRUEKEYWORD
FALSEKEYWORD
DEMANGLER_SPECIAL
CONSTRUCTION_VTABLE
CONSTRUCTION_IN
OROR
ANDAND
NOTEQUAL
EQUAL
GEQ
LEQ
RSH
LSH
DECREMENT
INCREMENT
UNARY
ARROW
INT
FLOAT
STRING_LITERAL
BOOLEAN_LITERAL
NAME
TYPENAME
NAME_OR_INT
SIZEOF
ERROR
INT_KEYWORD
INT_S2_KEYWORD
LOGICAL_S1_KEYWORD
LOGICAL_S2_KEYWORD
LOGICAL_S8_KEYWORD
LOGICAL_KEYWORD
REAL_KEYWORD
REAL_S8_KEYWORD
REAL_S16_KEYWORD
COMPLEX_S8_KEYWORD
COMPLEX_S16_KEYWORD
COMPLEX_S32_KEYWORD
BOOL_AND
BOOL_OR
BOOL_NOT
CHARACTER
VARIABLE
ASSIGN_MODIFY
ABOVE_COMMA
NOTEQUAL
EQUAL
GEQ
LEQ
GREATERTHAN
LESSTHAN
RSH
LSH
STARSTAR
UNARY
INT
FLOAT
RAW_STRING
STRING
CHAR
NAME
TYPENAME
COMPLETE
NAME_OR_INT
TRUE_KEYWORD
FALSE_KEYWORD
STRUCT_KEYWORD
INTERFACE_KEYWORD
TYPE_KEYWORD
CHAN_KEYWORD
SIZEOF_KEYWORD
LEN_KEYWORD
CAP_KEYWORD
NEW_KEYWORD
IOTA_KEYWORD
NIL_KEYWORD
CONST_KEYWORD
DOTDOTDOT
ENTRY
ERROR
BYTE_KEYWORD
DOLLAR_VARIABLE
ASSIGN_MODIFY
ABOVE_COMMA
OROR
ANDAND
ANDNOT
NOTEQUAL
EQUAL
GEQ
LEQ
RSH
LSH
DECREMENT
INCREMENT
UNARY
LEFT_ARROW
INTEGER_LITERAL
FLOATING_POINT_LITERAL
IDENTIFIER
STRING_LITERAL
BOOLEAN_LITERAL
TYPENAME
NAME_OR_INT
ERROR
LONG
SHORT
BYTE
INT
CHAR
BOOLEAN
DOUBLE
FLOAT
VARIABLE
ASSIGN_MODIFY
SUPER
NEW
OROR
ANDAND
NOTEQUAL
EQUAL
GEQ
LEQ
RSH
LSH
DECREMENT
INCREMENT
INT
HEX
ERROR
UINT
M2_TRUE
M2_FALSE
CHAR
FLOAT
STRING
NAME
BLOCKNAME
IDENT
VARNAME
TYPENAME
SIZE
CAP
ORD
HIGH
ABS
MIN_FUNC
MAX_FUNC
FLOAT_FUNC
VAL
CHR
ODD
TRUNC
TSIZE
INC
DEC
INCL
EXCL
COLONCOLON
INTERNAL_VAR
ABOVE_COMMA
ASSIGN
IN
NOTEQUAL
GEQ
LEQ
OROR
LOGICAL_AND
MOD
DIV
UNARY
DOT
NOT
QID
INT
FLOAT
STRING
FIELDNAME
COMPLETE
NAME
TYPENAME
NAME_OR_INT
STRUCT
CLASS
SIZEOF
COLONCOLON
ERROR
VARIABLE
THIS
TRUEKEYWORD
FALSEKEYWORD
ABOVE_COMMA
ASSIGN
NOT
OR
XOR
ANDAND
NOTEQUAL
GEQ
LEQ
MOD
DIV
RSH
LSH
DECREMENT
INCREMENT
UNARY
ARROW
BLOCKNAME
Definition at line 187 of file f-exp.c.
Function Documentation
static void growbuf_by_size (int count) [static]
Definition at line 2871 of file f-exp.c.
References GROWBY_MIN_SIZE, max, xmalloc(), and xrealloc().
static int match_string_literal (void) [static]
Definition at line 2893 of file f-exp.c.
References CHECKBUF, stoken::length, lexptr, stoken::ptr, STRING_LITERAL, YYSTYPE::sval, tempbuf, and tempbufindex.
Referenced by yylex().
static int parse_number (const char * p, int len, int parsed_float, YYSTYPE * putithere) [static]
Definition at line 2644 of file f-exp.c.
References _, atof(), YYSTYPE::dval, ERROR, FLOAT, gdbarch_int_bit(), gdbarch_long_bit(), input_radix, INT, LONGEST, parse_gdbarch, parse_type, RANGE_CHECK, range_error(), YYSTYPE::type, YYSTYPE::typed_val, ULONGEST, YYSTYPE::val, and xfree().
Referenced by yylex().
static void yy_reduce_print (YYSTYPE * yyvsp, int yyrule) [static]
Definition at line 1130 of file f-exp.c.
References yy_symbol_print(), YYFPRINTF, and yyrule.
static void yy_stack_print (yytype_int16 * yybottom, yytype_int16 * yytop) [static]
Definition at line 1099 of file f-exp.c.
References YYFPRINTF.
static void yy_symbol_print (FILE * yyoutput, int yytype, YYSTYPE const * const yyvaluep) [static]
Definition at line 1073 of file f-exp.c.
References yy_symbol_value_print(), YYFPRINTF, and YYNTOKENS.
Referenced by yy_reduce_print().
static void yy_symbol_value_print (FILE * yyoutput, int yytype, YYSTYPE const * const yyvaluep) [static]
Definition at line 1041 of file f-exp.c.
References YYNTOKENS, YYPRINT, and YYUSE.
Referenced by yy_symbol_print().
static void yydestruct (char * yymsg, int yytype, YYSTYPE * yyvaluep) const [static]
Definition at line 1434 of file f-exp.c.
References YY_SYMBOL_PRINT, and YYUSE.
void yyerror (char * msg)
static int yylex (void) [static]
Definition at line 2925 of file f-exp.c.
References _, BOOLEAN_LITERAL, comma_terminates, copy_name(), ERROR, error(), expression_context_block, input_radix, INT, symtoken::is_a_field_of_this, language_cplus, language_lookup_primitive_type_by_name(), stoken::length, lexptr, LOC_TYPEDEF, lookup_symbol(), YYSTYPE::lval, match_string_literal(), memcpy(), memset(), name, NAME, f77_boolean_val::name, NAME_OR_INT, YYSTYPE::opcode, token::opcode, token::operator, p, paren_depth, parse_gdbarch, parse_language, parse_number(), prev_lexptr, stoken::ptr, YYSTYPE::ssym, STARSTAR, YYSTYPE::sval, symtoken::sym, SYMBOL_CLASS, SYMBOL_TYPE, token, token::token, YYSTYPE::tsym, ttype::type, field_of_this_result::type, TYPENAME, f77_boolean_val::value, VAR_DOMAIN, VARIABLE, and write_dollar_variable().
int yyparse (void)
Variable Documentation
struct f77_boolean_val boolean_values[] [static]
Initial value:
{
  { ".true.", 1 },
  { ".TRUE.", 1 },
  { ".false.", 0 },
  { ".FALSE.", 0 },
  { NULL, 0 }
}
Definition at line 2819 of file f-exp.c.
struct token dot_ops[] [static]
Initial value:
{
  { ".and.", BOOL_AND, BINOP_END },
  { ".AND.", BOOL_AND, BINOP_END },
  { ".or.", BOOL_OR, BINOP_END },
  { ".OR.", BOOL_OR, BINOP_END },
  { ".not.", BOOL_NOT, BINOP_END },
  { ".NOT.", BOOL_NOT, BINOP_END },
  { ".eq.", EQUAL, BINOP_END },
  { ".EQ.", EQUAL, BINOP_END },
  { ".eqv.", EQUAL, BINOP_END },
  { ".NEQV.", NOTEQUAL, BINOP_END },
  { ".neqv.", NOTEQUAL, BINOP_END },
  { ".EQV.", EQUAL, BINOP_END },
  { ".ne.", NOTEQUAL, BINOP_END },
  { ".NE.", NOTEQUAL, BINOP_END },
  { ".le.", LEQ, BINOP_END },
  { ".LE.", LEQ, BINOP_END },
  { ".ge.", GEQ, BINOP_END },
  { ".GE.", GEQ, BINOP_END },
  { ".gt.", GREATERTHAN, BINOP_END },
  { ".GT.", GREATERTHAN, BINOP_END },
  { ".lt.", LESSTHAN, BINOP_END },
  { ".LT.", LESSTHAN, BINOP_END },
  { NULL, 0, 0 }
}
Definition at line 2786 of file f-exp.c.
struct token f77_keywords[] [static]
Initial value:
{
  { "complex_16", COMPLEX_S16_KEYWORD, BINOP_END },
  { "complex_32", COMPLEX_S32_KEYWORD, BINOP_END },
  { "character", CHARACTER, BINOP_END },
  { "integer_2", INT_S2_KEYWORD, BINOP_END },
  { "logical_1", LOGICAL_S1_KEYWORD, BINOP_END },
  { "logical_2", LOGICAL_S2_KEYWORD, BINOP_END },
  { "logical_8", LOGICAL_S8_KEYWORD, BINOP_END },
  { "complex_8", COMPLEX_S8_KEYWORD, BINOP_END },
  { "integer", INT_KEYWORD, BINOP_END },
  { "logical", LOGICAL_KEYWORD, BINOP_END },
  { "real_16", REAL_S16_KEYWORD, BINOP_END },
  { "complex", COMPLEX_S8_KEYWORD, BINOP_END },
  { "sizeof", SIZEOF, BINOP_END },
  { "real_8", REAL_S8_KEYWORD, BINOP_END },
  { "real", REAL_KEYWORD, BINOP_END },
  { NULL, 0, 0 }
}
Definition at line 2828 of file f-exp.c.
char* tempbuf [static]
Definition at line 2852 of file f-exp.c.
Referenced by match_string_literal().
int tempbufindex [static]
Definition at line 2854 of file f-exp.c.
Referenced by match_string_literal(), and yylex().
int tempbufsize [static]
Definition at line 2853 of file f-exp.c.
Referenced by yylex().
int yychar
Definition at line 1472 of file f-exp.c.
const yytype_int8 yycheck[] [static]
Definition at line 838 of file f-exp.c.
int yydebug
Definition at line 1159 of file f-exp.c.
const yytype_uint8 yydefact[] [static]
Initial value:
{
       0,    47,    49,    54,    53,    86,    69,    48,     0,    70,
      71,    76,    75,    73,    74,    77,    78,    79,    80,    81,
      82,     0,    72,    51,     0,     0,     0,     0,     0,     0,
       3,     2,    50,     4,    56,    57,    55,     0,    11,     9,
       7,     8,     6,     0,     0,     0,    10,     1,     0,     0,
       0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
       0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
      12,    61,    59,     0,    58,    63,    66,     0,     0,     5,
      23,     0,    43,    44,    46,    45,    42,    41,    40,    35,
      34,    37,    36,    39,    38,    33,    32,    26,    30,    31,
      28,    29,    27,    85,    25,    14,    62,    60,    67,    83,
       0,     0,     0,    65,    52,    22,    24,    21,    15,     0,
      16,    64,     0,    68,    20,    19,     0,    13,    84,    18,
      17
}
Definition at line 718 of file f-exp.c.
const yytype_int8 yydefgoto[] [static]
Initial value:
{
      -1,    29,    30,    43,   105,   119,   120,    44,    32,   109,
      34,    74,    75,    76,    35,   111,   104,    36
}
Definition at line 737 of file f-exp.c.
YYSTYPE yylval
Definition at line 1475 of file f-exp.c.
int yynerrs
Definition at line 1478 of file f-exp.c.
const yytype_int16 yypact[] [static]
Initial value:
{
     134,   -57,   -57,   -57,   -57,   -57,   -57,   -57,   162,   -57,
     -57,   -57,   -57,   -57,   -57,   -57,   -57,   -57,   -57,   -57,
     -57,   190,   -57,   -57,   190,   190,   190,   134,   190,    19,
     -57,   359,   -57,   -57,   -57,   -35,   -57,   134,   -33,   -33,
     -33,   -33,   -33,   328,   -32,   -31,   -33,   -57,   190,   190,
     190,   190,   190,   190,   190,   190,   190,   190,   190,   190,
     190,   190,   190,   190,   190,   190,   190,   190,   190,    24,
     -57,   -35,   -35,   234,   -57,   -12,   -57,   -11,   190,   -57,
     -57,   190,   407,   387,   359,   359,   426,   444,   461,   476,
     476,   228,   228,   228,   228,   -13,   -13,    49,   -39,   -39,
     -46,   -46,   -46,   -57,   -57,    80,   -57,   -57,   -57,   -57,
     -10,   -27,   277,   -57,    66,   359,   -33,   190,   298,   -24,
     -57,   -57,   293,   -57,   359,   190,   190,   -57,   -57,   359,
     359
}
Definition at line 746 of file f-exp.c.
const yytype_int8 yypgoto[] [static]
Initial value:
{
     -57,   -57,   -57,     0,   -57,   -57,   -57,   -57,   -57,     2,
     -57,   -56,   -57,   -30,   -57,   -57,   -57,   -57
}
Definition at line 765 of file f-exp.c.
const yytype_uint8 yyprhs[] [static]
Initial value:
{
       0,     0,     3,     5,     7,     9,    13,    16,    19,    22,
      25,    28,    31,    32,    38,    39,    41,    43,    47,    51,
      54,    57,    59,    63,    67,    72,    76,    80,    84,    88,
      92,    96,   100,   104,   108,   112,   116,   120,   124,   128,
     132,   136,   140,   144,   148,   152,   156,   160,   162,   164,
     166,   168,   170,   175,   177,   179,   181,   183,   185,   188,
     190,   193,   195,   198,   200,   204,   207,   209,   212,   216,
     218,   220,   222,   224,   226,   228,   230,   232,   234,   236,
     238,   240,   242,   244,   246,   250,   252
}
Definition at line 592 of file f-exp.c.
const yytype_uint8 yyr1[] [static]
Initial value:
{
       0,    57,    58,    58,    59,    60,    60,    60,    60,    60,
      60,    60,    61,    60,    62,    62,    62,    62,    63,    63,
      63,    63,    64,    60,    60,    60,    60,    60,    60,    60,
      60,    60,    60,    60,    60,    60,    60,    60,    60,    60,
      60,    60,    60,    60,    60,    60,    60,    60,    60,    60,
      60,    60,    60,    60,    60,    65,    66,    67,    67,    68,
      68,    68,    68,    68,    69,    69,    69,    70,    70,    71,
      71,    71,    71,    71,    71,    71,    71,    71,    71,    71,
      71,    71,    71,    72,    72,    73,    74
}
Definition at line 688 of file f-exp.c.
const yytype_uint8 yyr2[] [static]
Initial value:
{
       0,     2,     1,     1,     1,     3,     2,     2,     2,     2,
       2,     2,     0,     5,     0,     1,     1,     3,     3,     2,
       2,     1,     3,     3,     4,     3,     3,     3,     3,     3,
       3,     3,     3,     3,     3,     3,     3,     3,     3,     3,
       3,     3,     3,     3,     3,     3,     3,     1,     1,     1,
       1,     1,     4,     1,     1,     1,     1,     1,     2,     1,
       2,     1,     2,     1,     3,     2,     1,     2,     3,     1,
       1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
       1,     1,     1,     1,     3,     1,     1
}
Definition at line 702 of file f-exp.c.
const yytype_int8 yyrhs[] [static]
Initial value:
{
      58,     0,    -1,    60,    -1,    59,    -1,    66,    -1,    53,
      60,    54,    -1,    48,    60,    -1,    36,    60,    -1,    47,
      60,    -1,    26,    60,    -1,    55,    60,    -1,    10,    60,
      -1,    -1,    60,    53,    61,    62,    54,    -1,    -1,    60,
      -1,    63,    -1,    62,    30,    60,    -1,    60,    56,    60,
      -1,    60,    56,    -1,    56,    60,    -1,    56,    -1,    60,
      30,    60,    -1,    53,    64,    54,    -1,    53,    66,    54,
      60,    -1,    60,    51,    73,    -1,    60,    45,    60,    -1,
      60,    50,    60,    -1,    60,    48,    60,    -1,    60,    49,
      60,    -1,    60,    46,    60,    -1,    60,    47,    60,    -1,
      60,    44,    60,    -1,    60,    43,    60,    -1,    60,    38,
      60,    -1,    60,    37,    60,    -1,    60,    40,    60,    -1,
      60,    39,    60,    -1,    60,    42,    60,    -1,    60,    41,
      60,    -1,    60,    36,    60,    -1,    60,    35,    60,    -1,
      60,    34,    60,    -1,    60,    24,    60,    -1,    60,    25,
      60,    -1,    60,    32,    60,    -1,    60,    29,    60,    -1,
       3,    -1,     9,    -1,     4,    -1,    65,    -1,    28,    -1,
      10,    53,    66,    54,    -1,     6,    -1,     5,    -1,    74,
      -1,    67,    -1,    71,    -1,    71,    68,    -1,    48,    -1,
      48,    68,    -1,    36,    -1,    36,    68,    -1,    69,    -1,
      53,    68,    54,    -1,    69,    70,    -1,    70,    -1,    53,
      54,    -1,    53,    72,    54,    -1,     8,    -1,    12,    -1,
      13,    -1,    27,    -1,    16,    -1,    17,    -1,    15,    -1,
      14,    -1,    18,    -1,    19,    -1,    20,    -1,    21,    -1,
      22,    -1,    23,    -1,    66,    -1,    72,    30,    66,    -1,
       7,    -1,     7,    -1
}
Definition at line 606 of file f-exp.c.
const yytype_uint16 yyrline[] [static]
Initial value:
{
       0,   237,   237,   238,   241,   247,   252,   256,   260,   264,
     268,   272,   282,   281,   289,   292,   296,   300,   306,   312,
     318,   324,   330,   334,   340,   346,   354,   358,   362,   366,
     370,   374,   378,   382,   386,   390,   394,   398,   402,   406,
     410,   414,   418,   422,   427,   431,   435,   441,   448,   457,
     464,   467,   470,   478,   485,   493,   533,   536,   537,   580,
     582,   584,   586,   588,   591,   593,   595,   599,   601,   606,
     608,   610,   612,   614,   616,   618,   620,   622,   624,   626,
     628,   630,   632,   637,   642,   649,   653
}
Definition at line 637 of file f-exp.c.
const yytype_uint8 yystos[] [static]
Initial value:
{
       0,     3,     4,     5,     6,     7,     8,     9,    10,    12,
      13,    14,    15,    16,    17,    18,    19,    20,    21,    22,
      23,    26,    27,    28,    36,    47,    48,    53,    55,    58,
      59,    60,    65,    66,    67,    71,    74,    53,    60,    60,
      60,    60,    60,    60,    64,    66,    60,     0,    24,    25,
      29,    32,    34,    35,    36,    37,    38,    39,    40,    41,
      42,    43,    44,    45,    46,    47,    48,    49,    50,    51,
      53,    36,    48,    53,    68,    69,    70,    66,    30,    54,
      54,    54,    60,    60,    60,    60,    60,    60,    60,    60,
      60,    60,    60,    60,    60,    60,    60,    60,    60,    60,
      60,    60,    60,     7,    73,    61,    68,    68,    54,    66,
      68,    72,    53,    70,    54,    60,    60,    56,    60,    62,
      63,    54,    30,    54,    60,    56,    30,    54,    66,    60,
      60
}
Definition at line 897 of file f-exp.c.
const yytype_uint8 yytable[] [static]
Definition at line 775 of file f-exp.c.
const char* const yytname[] [static]
Initial value:
{
  "$end", "error", "$undefined", "INT", "FLOAT", "STRING_LITERAL",
  "BOOLEAN_LITERAL", "NAME", "TYPENAME", "NAME_OR_INT", "SIZEOF", "ERROR",
  "INT_KEYWORD", "INT_S2_KEYWORD", "LOGICAL_S1_KEYWORD",
  "LOGICAL_S2_KEYWORD", "LOGICAL_S8_KEYWORD", "LOGICAL_KEYWORD",
  "REAL_KEYWORD", "REAL_S8_KEYWORD", "REAL_S16_KEYWORD",
  "COMPLEX_S8_KEYWORD", "COMPLEX_S16_KEYWORD", "COMPLEX_S32_KEYWORD",
  "BOOL_AND", "BOOL_OR", "BOOL_NOT", "CHARACTER", "VARIABLE",
  "ASSIGN_MODIFY", "','", "ABOVE_COMMA", "'='", "'?'", "'|'", "'^'", "'&'",
  "NOTEQUAL", "EQUAL", "GEQ", "LEQ", "GREATERTHAN", "LESSTHAN", "RSH",
  "LSH", "'@'", "'+'", "'-'", "'*'", "'/'", "STARSTAR", "'%'", "UNARY",
  "'('", "')'", "'~'", "':'", "$accept", "start", "type_exp", "exp", "$@1",
  "arglist", "subrange", "complexnum", "variable", "type", "ptype",
  "abs_decl", "direct_abs_decl", "func_mod", "typebase",
  "nonempty_typelist", "name", "name_not_typename", 0
}
Definition at line 654 of file f-exp.c.
const yytype_uint8 yytranslate[] [static]
Definition at line 555 of file f-exp.c.