GDB (xrefs): /home/stan/gdb/src/gdb/f-lang.c File Reference
/home/stan/gdb/src/gdb/f-lang.c File Reference
#include "defs.h"
#include "gdb_string.h"
#include "symtab.h"
#include "gdbtypes.h"
#include "expression.h"
#include "parser-defs.h"
#include "language.h"
#include "f-lang.h"
#include "valprint.h"
#include "value.h"
#include "cp-support.h"
#include "charset.h"
#include "c-lang.h"
Enumerations
enum f_primitive_types {
f_primitive_type_character, f_primitive_type_logical, f_primitive_type_logical_s1, f_primitive_type_logical_s2,
f_primitive_type_logical_s8, f_primitive_type_integer, f_primitive_type_integer_s2, f_primitive_type_real,
f_primitive_type_real_s8, f_primitive_type_real_s16, f_primitive_type_complex_s8, f_primitive_type_complex_s16,
f_primitive_type_void, nr_f_primitive_types
}
Functions
void _initialize_f_language (void)
static void f_printchar (int c, struct type *type, struct ui_file *stream)
static void f_emit_char (int c, struct type *type, struct ui_file *stream, int quoter)
static const char * f_get_encoding (struct type *type)
static void f_printstr (struct ui_file *stream, struct type *type, const gdb_byte *string, unsigned int length, const char *encoding, int force_ellipses, const struct value_print_options *options)
static void f_language_arch_info (struct gdbarch *gdbarch, struct language_arch_info *lai)
static char * f_word_break_characters (void)
static VEC (char_ptr)
static void * build_fortran_types (struct gdbarch *gdbarch)
struct builtin_f_type * builtin_f_type (struct gdbarch *gdbarch)
Variables
static struct op_print f_op_print_tab []
struct language_defn f_language_defn
static struct gdbarch_data * f_type_data
Enumeration Type Documentation
enum f_primitive_types
Enumerator:
f_primitive_type_character
f_primitive_type_logical
f_primitive_type_logical_s1
f_primitive_type_logical_s2
f_primitive_type_logical_s8
f_primitive_type_integer
f_primitive_type_integer_s2
f_primitive_type_real
f_primitive_type_real_s8
f_primitive_type_real_s16
f_primitive_type_complex_s8
f_primitive_type_complex_s16
f_primitive_type_void
nr_f_primitive_types
Definition at line 149 of file f-lang.c.
Function Documentation
void _initialize_f_language (void)
static void* build_fortran_types (struct gdbarch * gdbarch) [static]
Definition at line 280 of file f-lang.c.
References arch_boolean_type(), arch_complex_type(), arch_float_type(), arch_integer_type(), arch_type(), builtin_f_type::builtin_character, builtin_f_type::builtin_complex_s16, builtin_f_type::builtin_complex_s32, builtin_f_type::builtin_complex_s8, builtin_f_type(), builtin_f_type::builtin_integer, builtin_f_type::builtin_integer_s2, builtin_f_type::builtin_logical, builtin_f_type::builtin_logical_s1, builtin_f_type::builtin_logical_s2, builtin_f_type::builtin_logical_s8, builtin_f_type::builtin_real, builtin_f_type::builtin_real_s16, builtin_f_type::builtin_real_s8, builtin_f_type::builtin_void, gdbarch_double_bit(), gdbarch_float_bit(), gdbarch_int_bit(), gdbarch_long_double_bit(), gdbarch_long_long_bit(), GDBARCH_OBSTACK_ZALLOC, gdbarch_short_bit(), and TYPE_CODE_VOID.
struct builtin_f_type* builtin_f_type (struct gdbarch * gdbarch) [read]
Definition at line 340 of file f-lang.c.
References gdbarch_data().
Referenced by build_fortran_types(), and f_language_arch_info().
static void f_emit_char (int c, struct type * type, struct ui_file * stream, int quoter) [static]
Definition at line 80 of file f-lang.c.
References encoding, f_get_encoding(), and generic_emit_char().
static const char* f_get_encoding (struct type * type) [static]
Definition at line 50 of file f-lang.c.
References _, encoding, error(), gdbarch_byte_order(), get_type_arch(), target_charset(), and TYPE_LENGTH.
Referenced by f_emit_char(), and f_printstr().
static void f_language_arch_info (struct gdbarch * gdbarch, struct language_arch_info * lai) [static]
Definition at line 167 of file f-lang.c.
References language_arch_info::bool_type_default, language_arch_info::bool_type_symbol, builtin_f_type::builtin_character, builtin_f_type::builtin_complex_s16, builtin_f_type::builtin_complex_s8, builtin_f_type(), builtin_f_type::builtin_logical, builtin_f_type::builtin_logical_s1, builtin_f_type::builtin_logical_s2, builtin_f_type::builtin_logical_s8, builtin_f_type::builtin_real, builtin_f_type::builtin_real_s16, builtin_f_type::builtin_real_s8, builtin_f_type::builtin_void, f_primitive_type_character, f_primitive_type_complex_s16, f_primitive_type_complex_s8, f_primitive_type_logical, f_primitive_type_logical_s1, f_primitive_type_logical_s2, f_primitive_type_logical_s8, f_primitive_type_real, f_primitive_type_real_s16, f_primitive_type_real_s8, f_primitive_type_void, GDBARCH_OBSTACK_CALLOC, nr_f_primitive_types, language_arch_info::primitive_type_vector, and language_arch_info::string_char_type.
static void f_printchar (int c, struct type * type, struct ui_file * stream) [static]
Definition at line 90 of file f-lang.c.
References fputs_filtered(), and LA_EMIT_CHAR.
static void f_printstr (struct ui_file * stream, struct type * type, const gdb_byte * string, unsigned int length, const char * encoding, int force_ellipses, const struct value_print_options * options) [static]
Definition at line 105 of file f-lang.c.
References f_get_encoding(), fputs_filtered(), generic_printstr(), and TYPE_LENGTH.
static char* f_word_break_characters (void) [static]
Definition at line 207 of file f-lang.c.
References default_word_break_characters(), and strchr().
static VEC (char_ptr) [static]
Definition at line 231 of file f-lang.c.
Variable Documentation
struct language_defn f_language_defn
Definition at line 238 of file f-lang.c.
struct op_print f_op_print_tab[] [static]
Initial value:
{
  {"+", BINOP_ADD, PREC_ADD, 0},
  {"+", UNOP_PLUS, PREC_PREFIX, 0},
  {"-", BINOP_SUB, PREC_ADD, 0},
  {"-", UNOP_NEG, PREC_PREFIX, 0},
  {"*", BINOP_MUL, PREC_MUL, 0},
  {"/", BINOP_DIV, PREC_MUL, 0},
  {"DIV", BINOP_INTDIV, PREC_MUL, 0},
  {"MOD", BINOP_REM, PREC_MUL, 0},
  {"=", BINOP_ASSIGN, PREC_ASSIGN, 1},
  {".OR.", BINOP_LOGICAL_OR, PREC_LOGICAL_OR, 0},
  {".AND.", BINOP_LOGICAL_AND, PREC_LOGICAL_AND, 0},
  {".NOT.", UNOP_LOGICAL_NOT, PREC_PREFIX, 0},
  {".EQ.", BINOP_EQUAL, PREC_EQUAL, 0},
  {".NE.", BINOP_NOTEQUAL, PREC_EQUAL, 0},
  {".LE.", BINOP_LEQ, PREC_ORDER, 0},
  {".GE.", BINOP_GEQ, PREC_ORDER, 0},
  {".GT.", BINOP_GTR, PREC_ORDER, 0},
  {".LT.", BINOP_LESS, PREC_ORDER, 0},
  {"**", UNOP_IND, PREC_PREFIX, 0},
  {"@", BINOP_REPEAT, PREC_REPEAT, 0},
  {NULL, 0, 0, 0}
}
Definition at line 124 of file f-lang.c.
struct gdbarch_data* f_type_data [static]
Definition at line 337 of file f-lang.c.