GDB (xrefs): /home/stan/gdb/src/gdb/f-lang.h File Reference
/home/stan/gdb/src/gdb/f-lang.h File Reference
Classes
struct common_block
struct builtin_f_type
Enumerations
enum f90_range_type { BOTH_BOUND_DEFAULT, LOW_BOUND_DEFAULT, HIGH_BOUND_DEFAULT, NONE_BOUND_DEFAULT }
Functions
int f_parse (void)
void f_error (char *)
void f_print_type (struct type *, const char *, struct ui_file *, int, int, const struct type_print_options *)
void f_val_print (struct type *, const gdb_byte *, int, CORE_ADDR, struct ui_file *, int, const struct value *, const struct value_print_options *)
int f77_get_upperbound (struct type *)
int f77_get_lowerbound (struct type *)
void f77_get_dynamic_array_length (struct type *)
int calc_f77_array_dims (struct type *)
struct builtin_f_type * builtin_f_type (struct gdbarch *gdbarch)
Enumeration Type Documentation
enum f90_range_type
Enumerator:
BOTH_BOUND_DEFAULT
LOW_BOUND_DEFAULT
HIGH_BOUND_DEFAULT
NONE_BOUND_DEFAULT
Definition at line 44 of file f-lang.h.
Function Documentation
struct builtin_f_type* builtin_f_type (struct gdbarch * gdbarch) [read]
Definition at line 340 of file f-lang.c.
References gdbarch_data().
Referenced by build_fortran_types(), and f_language_arch_info().
int calc_f77_array_dims (struct type *)
Definition at line 3076 of file eval.c.
References _, error(), TYPE_CODE, TYPE_CODE_ARRAY, and TYPE_TARGET_TYPE.
Referenced by evaluate_subexp_standard(), and f77_print_array().
void f77_get_dynamic_array_length (struct type *)
int f77_get_lowerbound (struct type *)
Definition at line 61 of file f-valprint.c.
References _, error(), TYPE_ARRAY_LOWER_BOUND_IS_UNDEFINED, and TYPE_ARRAY_LOWER_BOUND_VALUE.
Referenced by evaluate_subexp_standard(), f77_create_arrayprint_offset_tbl(), f77_get_dynamic_length_of_aggregate(), f77_get_upperbound(), and f_type_print_varspec_suffix().
int f77_get_upperbound (struct type *)
Definition at line 70 of file f-valprint.c.
References f77_get_lowerbound(), TYPE_ARRAY_UPPER_BOUND_IS_UNDEFINED, and TYPE_ARRAY_UPPER_BOUND_VALUE.
Referenced by f77_create_arrayprint_offset_tbl(), f77_get_dynamic_length_of_aggregate(), f_type_print_base(), and f_type_print_varspec_suffix().
void f_error (char *)
int f_parse (void)
void f_print_type (struct type * , const char * , struct ui_file * , int , int , const struct type_print_options *)
Definition at line 53 of file f-typeprint.c.
References code, f_type_print_base(), f_type_print_varspec_prefix(), f_type_print_varspec_suffix(), fputs_filtered(), TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_FUNC, TYPE_CODE_METHOD, TYPE_CODE_PTR, TYPE_CODE_REF, and TYPE_NAME.
void f_val_print (struct type * , const gdb_byte * , int , CORE_ADDR , struct ui_file * , int , const struct value * , const struct value_print_options *)
Definition at line 258 of file f-valprint.c.
References value_print_options::addressprint, gdbarch::byte_order, check_typedef(), CHECK_TYPEDEF, current_language, demangle, f77_get_dynamic_length_of_aggregate(), f77_print_array(), value_print_options::format, fprintf_filtered(), fputs_filtered(), gdb_flush(), gdbarch_byte_order(), generic_val_print(), get_type_arch(), LA_PRINT_CHAR, LA_PRINT_STRING, LONGEST, offset, value_print_options::output_format, paddress(), print_address_demangle(), print_function_pointer_address(), value_print_options::symbol_print, TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_BOOL, TYPE_CODE_CHAR, TYPE_CODE_COMPLEX, TYPE_CODE_ERROR, TYPE_CODE_FLAGS, TYPE_CODE_FLT, TYPE_CODE_FUNC, TYPE_CODE_INT, TYPE_CODE_PTR, TYPE_CODE_RANGE, TYPE_CODE_REF, TYPE_CODE_STRING, TYPE_CODE_STRUCT, TYPE_CODE_UNDEF, TYPE_CODE_UNION, TYPE_CODE_VOID, TYPE_FIELD_BITPOS, TYPE_FIELD_TYPE, TYPE_LENGTH, TYPE_NFIELDS, TYPE_TARGET_TYPE, unpack_long(), unpack_pointer(), val_print(), val_print_scalar_formatted(), val_print_string(), and val_print_type_code_int().