GDB (xrefs): /home/stan/gdb/src/gdb/f-typeprint.c File Reference
/home/stan/gdb/src/gdb/f-typeprint.c File Reference
#include "defs.h"
#include "gdb_obstack.h"
#include "bfd.h"
#include "symtab.h"
#include "gdbtypes.h"
#include "expression.h"
#include "value.h"
#include "gdbcore.h"
#include "target.h"
#include "f-lang.h"
#include "gdb_string.h"
#include <errno.h>
Functions
static void f_type_print_varspec_suffix (struct type *, struct ui_file *, int, int, int, int)
void f_type_print_varspec_prefix (struct type *, struct ui_file *, int, int)
void f_type_print_base (struct type *, struct ui_file *, int, int)
void f_print_type (struct type *type, const char *varstring, struct ui_file *stream, int show, int level, const struct type_print_options *flags)
Function Documentation
void f_print_type (struct type * type, const char * varstring, struct ui_file * stream, int show, int level, const struct type_print_options * flags)
Definition at line 53 of file f-typeprint.c.
References code, f_type_print_base(), f_type_print_varspec_prefix(), f_type_print_varspec_suffix(), fputs_filtered(), TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_FUNC, TYPE_CODE_METHOD, TYPE_CODE_PTR, TYPE_CODE_REF, and TYPE_NAME.
void f_type_print_base (struct type * type, struct ui_file * stream, int show, int level)
Definition at line 254 of file f-typeprint.c.
References _, CHECK_TYPEDEF, error(), f77_get_upperbound(), f_type_print_varspec_suffix(), fprintf_filtered(), fprintfi_filtered(), fputs_filtered(), QUIT, TYPE_ARRAY_UPPER_BOUND_IS_UNDEFINED, TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_CHAR, TYPE_CODE_ERROR, TYPE_CODE_FUNC, TYPE_CODE_INT, TYPE_CODE_MODULE, TYPE_CODE_PTR, TYPE_CODE_RANGE, TYPE_CODE_REF, TYPE_CODE_STRING, TYPE_CODE_STRUCT, TYPE_CODE_TYPEDEF, TYPE_CODE_UNDEF, TYPE_CODE_UNION, TYPE_CODE_VOID, TYPE_ERROR_NAME, TYPE_FIELD_NAME, TYPE_FIELD_TYPE, TYPE_NAME, TYPE_NFIELDS, TYPE_TAG_NAME, TYPE_TARGET_TYPE, and wrap_here().
Referenced by f_print_type().
void f_type_print_varspec_prefix (struct type * type, struct ui_file * stream, int show, int passed_a_ptr)
Definition at line 93 of file f-typeprint.c.
References fprintf_filtered(), QUIT, TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_BOOL, TYPE_CODE_CHAR, TYPE_CODE_COMPLEX, TYPE_CODE_ENUM, TYPE_CODE_ERROR, TYPE_CODE_FLT, TYPE_CODE_FUNC, TYPE_CODE_INT, TYPE_CODE_METHOD, TYPE_CODE_PTR, TYPE_CODE_RANGE, TYPE_CODE_REF, TYPE_CODE_SET, TYPE_CODE_STRING, TYPE_CODE_STRUCT, TYPE_CODE_TYPEDEF, TYPE_CODE_UNDEF, TYPE_CODE_UNION, TYPE_CODE_VOID, TYPE_NAME, and TYPE_TARGET_TYPE.
Referenced by f_print_type().
static void f_type_print_varspec_suffix (struct type * type, struct ui_file * stream, int show, int passed_a_ptr, int demangled_args, int arrayprint_recurse_level) [static]
Definition at line 148 of file f-typeprint.c.
References f77_get_lowerbound(), f77_get_upperbound(), fprintf_filtered(), QUIT, TYPE_ARRAY_UPPER_BOUND_IS_UNDEFINED, TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_BOOL, TYPE_CODE_CHAR, TYPE_CODE_COMPLEX, TYPE_CODE_ENUM, TYPE_CODE_ERROR, TYPE_CODE_FLT, TYPE_CODE_FUNC, TYPE_CODE_INT, TYPE_CODE_METHOD, TYPE_CODE_PTR, TYPE_CODE_RANGE, TYPE_CODE_REF, TYPE_CODE_SET, TYPE_CODE_STRING, TYPE_CODE_STRUCT, TYPE_CODE_TYPEDEF, TYPE_CODE_UNDEF, TYPE_CODE_UNION, TYPE_CODE_VOID, TYPE_NAME, and TYPE_TARGET_TYPE.
Referenced by f_print_type(), and f_type_print_base().