GDB (xrefs): /home/stan/gdb/src/gdb/f-valprint.c File Reference
/home/stan/gdb/src/gdb/f-valprint.c File Reference
#include "defs.h"
#include "gdb_string.h"
#include "symtab.h"
#include "gdbtypes.h"
#include "expression.h"
#include "value.h"
#include "valprint.h"
#include "language.h"
#include "f-lang.h"
#include "frame.h"
#include "gdbcore.h"
#include "command.h"
#include "block.h"
#include "dictionary.h"
#include "gdb_assert.h"
#include "exceptions.h"
Defines
#define F77_DIM_SIZE(n) (f77_array_offset_tbl[n][1])
#define F77_DIM_OFFSET(n) (f77_array_offset_tbl[n][0])
Functions
void _initialize_f_valprint (void)
static void info_common_command (char *, int)
static void f77_create_arrayprint_offset_tbl (struct type *, struct ui_file *)
static void f77_get_dynamic_length_of_aggregate (struct type *)
int f77_get_lowerbound (struct type *type)
int f77_get_upperbound (struct type *type)
static void f77_print_array_1 (int nss, int ndimensions, struct type *type, const gdb_byte *valaddr, int embedded_offset, CORE_ADDR address, struct ui_file *stream, int recurse, const struct value *val, const struct value_print_options *options, int *elts)
static void f77_print_array (struct type *type, const gdb_byte *valaddr, int embedded_offset, CORE_ADDR address, struct ui_file *stream, int recurse, const struct value *val, const struct value_print_options *options)
void f_val_print (struct type *type, const gdb_byte *valaddr, int embedded_offset, CORE_ADDR address, struct ui_file *stream, int recurse, const struct value *original_value, const struct value_print_options *options)
static void info_common_command_for_block (struct block *block, const char *comname, int *any_printed)
Variables
int f77_array_offset_tbl [MAX_FORTRAN_DIMS+1][2]
static struct
generic_val_print_decorations f_decorations
Define Documentation
#define F77_DIM_OFFSET (n) (f77_array_offset_tbl[n][0])
Definition at line 58 of file f-valprint.c.
Referenced by f77_create_arrayprint_offset_tbl(), and f77_print_array_1().
#define F77_DIM_SIZE (n) (f77_array_offset_tbl[n][1])
Definition at line 54 of file f-valprint.c.
Referenced by f77_create_arrayprint_offset_tbl(), and f77_print_array_1().
Function Documentation
void _initialize_f_valprint (void)
static void f77_create_arrayprint_offset_tbl (struct type * type, struct ui_file * stream) [static]
Definition at line 121 of file f-valprint.c.
References F77_DIM_OFFSET, F77_DIM_SIZE, f77_get_lowerbound(), f77_get_upperbound(), type, TYPE_CODE, TYPE_CODE_ARRAY, TYPE_LENGTH, and TYPE_TARGET_TYPE.
Referenced by f77_print_array().
static void f77_get_dynamic_length_of_aggregate (struct type * type) [static]
Definition at line 88 of file f-valprint.c.
References check_typedef(), f77_get_lowerbound(), f77_get_upperbound(), TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_STRING, TYPE_LENGTH, and TYPE_TARGET_TYPE.
Referenced by f_val_print().
int f77_get_lowerbound (struct type * type)
Definition at line 61 of file f-valprint.c.
References _, error(), TYPE_ARRAY_LOWER_BOUND_IS_UNDEFINED, and TYPE_ARRAY_LOWER_BOUND_VALUE.
Referenced by evaluate_subexp_standard(), f77_create_arrayprint_offset_tbl(), f77_get_dynamic_length_of_aggregate(), f77_get_upperbound(), and f_type_print_varspec_suffix().
int f77_get_upperbound (struct type * type)
Definition at line 70 of file f-valprint.c.
References f77_get_lowerbound(), TYPE_ARRAY_UPPER_BOUND_IS_UNDEFINED, and TYPE_ARRAY_UPPER_BOUND_VALUE.
Referenced by f77_create_arrayprint_offset_tbl(), f77_get_dynamic_length_of_aggregate(), f_type_print_base(), and f_type_print_varspec_suffix().
static void f77_print_array (struct type * type, const gdb_byte * valaddr, int embedded_offset, CORE_ADDR address, struct ui_file * stream, int recurse, const struct value * val, const struct value_print_options * options) [static]
Definition at line 214 of file f-valprint.c.
References _, calc_f77_array_dims(), error(), f77_create_arrayprint_offset_tbl(), f77_print_array_1(), and MAX_FORTRAN_DIMS.
Referenced by f_val_print().
static void f77_print_array_1 (int nss, int ndimensions, struct type * type, const gdb_byte * valaddr, int embedded_offset, CORE_ADDR address, struct ui_file * stream, int recurse, const struct value * val, const struct value_print_options * options, int * elts) [static]
Definition at line 162 of file f-valprint.c.
References current_language, F77_DIM_OFFSET, F77_DIM_SIZE, fprintf_filtered(), value_print_options::print_max, TYPE_TARGET_TYPE, and val_print().
Referenced by f77_print_array().
void f_val_print (struct type * type, const gdb_byte * valaddr, int embedded_offset, CORE_ADDR address, struct ui_file * stream, int recurse, const struct value * original_value, const struct value_print_options * options)
Definition at line 258 of file f-valprint.c.
References value_print_options::addressprint, gdbarch::byte_order, check_typedef(), CHECK_TYPEDEF, current_language, demangle, f77_get_dynamic_length_of_aggregate(), f77_print_array(), value_print_options::format, fprintf_filtered(), fputs_filtered(), gdb_flush(), gdbarch_byte_order(), generic_val_print(), get_type_arch(), LA_PRINT_CHAR, LA_PRINT_STRING, LONGEST, offset, value_print_options::output_format, paddress(), print_address_demangle(), print_function_pointer_address(), value_print_options::symbol_print, TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_BOOL, TYPE_CODE_CHAR, TYPE_CODE_COMPLEX, TYPE_CODE_ERROR, TYPE_CODE_FLAGS, TYPE_CODE_FLT, TYPE_CODE_FUNC, TYPE_CODE_INT, TYPE_CODE_PTR, TYPE_CODE_RANGE, TYPE_CODE_REF, TYPE_CODE_STRING, TYPE_CODE_STRUCT, TYPE_CODE_UNDEF, TYPE_CODE_UNION, TYPE_CODE_VOID, TYPE_FIELD_BITPOS, TYPE_FIELD_TYPE, TYPE_LENGTH, TYPE_NFIELDS, TYPE_TARGET_TYPE, unpack_long(), unpack_pointer(), val_print(), val_print_scalar_formatted(), val_print_string(), and val_print_type_code_int().
static void info_common_command (char * comname, int from_tty) [static]
Definition at line 472 of file f-valprint.c.
References _, BLOCK_FUNCTION, BLOCK_SUPERBLOCK, get_frame_block(), get_selected_frame(), info_common_command_for_block(), and printf_filtered().
static void info_common_command_for_block (struct block * block, const char * comname, int * any_printed) [static]
Definition at line 414 of file f-valprint.c.
References _, ALL_BLOCK_SYMBOLS, COMMON_BLOCK_DOMAIN, common_block::contents, gdb_assert, gdb_stdout, get_user_print_options(), LOC_COMMON_BLOCK, gdb_exception::message, common_block::n_entries, name, printf_filtered(), putchar_filtered(), gdb_exception::reason, RETURN_MASK_ERROR, SYMBOL_CLASS, SYMBOL_DOMAIN, SYMBOL_LINKAGE_NAME, SYMBOL_PRINT_NAME, SYMBOL_VALUE_COMMON_BLOCK, TRY_CATCH, value_of_variable(), and value_print().
Referenced by info_common_command().
Variable Documentation
int f77_array_offset_tbl[MAX_FORTRAN_DIMS+1][2]
Definition at line 46 of file f-valprint.c.
struct generic_val_print_decorations f_decorations [static]
Initial value:
{
  "(",
  ",",
  ")",
  ".TRUE.",
  ".FALSE.",
  "VOID",
}
Definition at line 244 of file f-valprint.c.