GDB (xrefs): /home/stan/gdb/src/gdb/fbsd-nat.h File Reference
/home/stan/gdb/src/gdb/fbsd-nat.h File Reference
Functions
char * fbsd_pid_to_exec_file (int pid)
int fbsd_find_memory_regions (find_memory_region_ftype func, void *obfd)
char * fbsd_make_corefile_notes (bfd *obfd, int *note_size)
Function Documentation
int fbsd_find_memory_regions (find_memory_region_ftype func, void * obfd)
Definition at line 94 of file fbsd-nat.c.
References _, do_cleanups(), error(), fbsd_read_mapping(), fprintf_filtered(), func, gdb_stdout, inferior_ptid, info_verbose, make_cleanup(), make_cleanup_fclose(), paddress(), ptid_get_pid(), read(), size, strchr(), target_gdbarch(), xfree(), and xstrprintf().
Referenced by _initialize_amd64fbsd_nat(), _initialize_i386fbsd_nat(), _initialize_ppcfbsd_nat(), and _initialize_sparc64fbsd_nat().
char* fbsd_make_corefile_notes (bfd * obfd, int * note_size)
Definition at line 169 of file fbsd-nat.c.
References regset::collect_regset, find_stop_signal(), gdb_assert, gdbarch_regset_from_core_section(), gdbarch_regset_from_core_section_p(), get_current_regcache(), get_exec_file(), get_inferior_args(), get_regcache_arch(), inferior_ptid, make_cleanup(), ptid_get_pid(), size, and xfree().
Referenced by _initialize_amd64fbsd_nat(), _initialize_i386fbsd_nat(), _initialize_ppcfbsd_nat(), and _initialize_sparc64fbsd_nat().
char* fbsd_pid_to_exec_file (int pid)
Definition at line 40 of file fbsd-nat.c.
References len, xcalloc(), xfree(), and xstrprintf().
Referenced by _initialize_amd64fbsd_nat(), _initialize_i386fbsd_nat(), _initialize_ppcfbsd_nat(), and _initialize_sparc64fbsd_nat().