GDB (xrefs): /home/stan/gdb/src/gdb/findcmd.c File Reference
/home/stan/gdb/src/gdb/findcmd.c File Reference
#include "defs.h"
#include "arch-utils.h"
#include <ctype.h>
#include "gdb_string.h"
#include "gdbcmd.h"
#include "value.h"
#include "target.h"
#include "cli/cli-utils.h"
Defines
#define INITIAL_PATTERN_BUF_SIZE 100
Functions
static void put_bits (bfd_uint64_t data, gdb_byte *buf, int bits, bfd_boolean big_p)
static void parse_find_args (char *args, ULONGEST *max_countp, gdb_byte **pattern_bufp, ULONGEST *pattern_lenp, CORE_ADDR *start_addrp, ULONGEST *search_space_lenp, bfd_boolean big_p)
static void find_command (char *args, int from_tty)
void _initialize_mem_search (void)
Variables
initialize_file_ftype _initialize_mem_search
Define Documentation
#define INITIAL_PATTERN_BUF_SIZE 100
Referenced by parse_find_args().
Function Documentation
void _initialize_mem_search (void)
Definition at line 323 of file findcmd.c.
References _, _initialize_mem_search, add_cmd(), class_vars, cmdlist, and find_command().
static void find_command (char * args, int from_tty) [static]
Definition at line 245 of file findcmd.c.
References builtin_type::builtin_data_ptr, builtin_type(), do_cleanups(), free_current_contents(), gdb_stdout, gdbarch_byte_order(), get_current_arch(), lookup_internalvar(), make_cleanup(), parse_find_args(), print_address(), printf_filtered(), set_internalvar(), set_internalvar_integer(), target_search_memory(), ULONGEST, and value_from_pointer().
Referenced by _initialize_mem_search().
static void parse_find_args (char * args, ULONGEST * max_countp, gdb_byte ** pattern_bufp, ULONGEST * pattern_lenp, CORE_ADDR * start_addrp, ULONGEST * search_space_lenp, bfd_boolean big_p) [static]
Definition at line 53 of file findcmd.c.
References _, CORE_ADDR_MAX, discard_cleanups(), do_cleanups(), error(), free_current_contents(), INITIAL_PATTERN_BUF_SIZE, len, LONGEST, make_cleanup(), max, memcpy(), parse_to_comma_and_eval(), printf_filtered(), put_bits(), size, skip_spaces_const(), TYPE_LENGTH, ULONGEST, value_as_address(), value_as_long(), value_contents(), value_type(), xmalloc(), and xrealloc().
Referenced by find_command().
static void put_bits (bfd_uint64_t data, gdb_byte * buf, int bits, bfd_boolean big_p) [static]
Definition at line 32 of file findcmd.c.
References gdb_assert.
Referenced by parse_find_args().
Variable Documentation
initialize_file_ftype _initialize_mem_search
Referenced by _initialize_mem_search(), and initialize_all_files().