GDB (xrefs): /home/stan/gdb/src/gdb/findvar.c File Reference
/home/stan/gdb/src/gdb/findvar.c File Reference
#include "defs.h"
#include "symtab.h"
#include "gdbtypes.h"
#include "frame.h"
#include "value.h"
#include "gdbcore.h"
#include "inferior.h"
#include "target.h"
#include "gdb_string.h"
#include "gdb_assert.h"
#include "floatformat.h"
#include "symfile.h"
#include "regcache.h"
#include "user-regs.h"
#include "block.h"
#include "objfiles.h"
#include "language.h"
Classes
struct minsym_lookup_data
Functions
LONGEST extract_signed_integer (const gdb_byte *addr, int len, enum bfd_endian byte_order)
ULONGEST extract_unsigned_integer (const gdb_byte *addr, int len, enum bfd_endian byte_order)
int extract_long_unsigned_integer (const gdb_byte *addr, int orig_len, enum bfd_endian byte_order, LONGEST *pval)
CORE_ADDR extract_typed_address (const gdb_byte *buf, struct type *type)
void store_signed_integer (gdb_byte *addr, int len, enum bfd_endian byte_order, LONGEST val)
void store_unsigned_integer (gdb_byte *addr, int len, enum bfd_endian byte_order, ULONGEST val)
void store_typed_address (gdb_byte *buf, struct type *type, CORE_ADDR addr)
struct value * value_of_register (int regnum, struct frame_info *frame)
struct value * value_of_register_lazy (struct frame_info *frame, int regnum)
CORE_ADDR unsigned_pointer_to_address (struct gdbarch *gdbarch, struct type *type, const gdb_byte *buf)
CORE_ADDR signed_pointer_to_address (struct gdbarch *gdbarch, struct type *type, const gdb_byte *buf)
void unsigned_address_to_pointer (struct gdbarch *gdbarch, struct type *type, gdb_byte *buf, CORE_ADDR addr)
void address_to_signed_pointer (struct gdbarch *gdbarch, struct type *type, gdb_byte *buf, CORE_ADDR addr)
int symbol_read_needs_frame (struct symbol *sym)
static int minsym_lookup_iterator_cb (struct objfile *objfile, void *cb_data)
struct value * default_read_var_value (struct symbol *var, struct frame_info *frame)
struct value * read_var_value (struct symbol *var, struct frame_info *frame)
struct value * default_value_from_register (struct type *type, int regnum, struct frame_info *frame)
void read_frame_register_value (struct value *value, struct frame_info *frame)
struct value * value_from_register (struct type *type, int regnum, struct frame_info *frame)
CORE_ADDR address_from_register (struct type *type, int regnum, struct frame_info *frame)
Function Documentation
CORE_ADDR address_from_register (struct type * type, int regnum, struct frame_info * frame)
Definition at line 752 of file findvar.c.
References error_value_optimized_out(), gdb_assert, release_value(), value_as_address(), value_free(), value_from_register(), and value_optimized_out().
Referenced by dwarf_expr_read_reg().
void address_to_signed_pointer (struct gdbarch * gdbarch, struct type * type, gdb_byte * buf, CORE_ADDR addr)
Definition at line 333 of file findvar.c.
References gdbarch_byte_order(), store_signed_integer(), and TYPE_LENGTH.
Referenced by mips_gdbarch_init().
struct value* default_read_var_value (struct symbol * var, struct frame_info * frame) [read]
Definition at line 422 of file findvar.c.
References _, allocate_optimized_out_value(), allocate_value(), BLOCK_START, check_typedef(), error(), gdb_assert, gdb_assert_not_reached, gdbarch_byte_order(), gdbarch_iterate_over_objfiles_in_search_order(), get_frame_arch(), get_frame_args_address(), get_frame_locals_address(), get_objfile_arch(), get_type_arch(), LOC_ARG, LOC_BLOCK, LOC_COMPUTED, LOC_CONST, LOC_CONST_BYTES, LOC_LABEL, LOC_LOCAL, LOC_OPTIMIZED_OUT, LOC_REF_ARG, LOC_REGISTER, LOC_REGPARM_ADDR, LOC_STATIC, LOC_TYPEDEF, LOC_UNRESOLVED, LONGEST, lookup_pointer_type(), memcpy(), memset(), minsym_lookup_iterator_cb(), minsym_lookup_data::name, not_lval, obj_section::objfile, minsym_lookup_data::objfile, overlay_debugging, minsym_lookup_data::result, store_signed_integer(), store_typed_address(), SYMBOL_BLOCK_VALUE, SYMBOL_CLASS, SYMBOL_COMPUTED_OPS, SYMBOL_LINKAGE_NAME, SYMBOL_OBJ_SECTION, SYMBOL_OBJFILE, symbol_overlayed_address(), SYMBOL_PRINT_NAME, symbol_read_needs_frame(), SYMBOL_REGISTER_OPS, SYMBOL_SYMTAB, SYMBOL_TYPE, SYMBOL_VALUE, SYMBOL_VALUE_ADDRESS, SYMBOL_VALUE_BYTES, target_translate_tls_address(), obj_section::the_bfd_section, TYPE_LENGTH, value_as_address(), value_at(), value_at_lazy(), value_contents_raw(), value_from_register(), and VALUE_LVAL.
Referenced by ada_read_var_value().
struct value* default_value_from_register (struct type * type, int regnum, struct frame_info * frame) [read]
Definition at line 622 of file findvar.c.
References allocate_value(), gdbarch_byte_order(), get_frame_arch(), get_frame_id(), len, lval_register, register_size(), regnum, set_value_offset(), TYPE_LENGTH, VALUE_FRAME_ID, VALUE_LVAL, and VALUE_REGNUM.
Referenced by gdbarch_alloc(), s390_value_from_register(), and spu_value_from_register().
int extract_long_unsigned_integer (const gdb_byte * addr, int orig_len, enum bfd_endian byte_order, LONGEST * pval)
Definition at line 121 of file findvar.c.
References extract_unsigned_integer(), int, len, LONGEST, and p.
Referenced by val_print_type_code_int().
LONGEST extract_signed_integer (const gdb_byte * addr, int len, enum bfd_endian byte_order)
Definition at line 51 of file findvar.c.
References _, error(), len, LONGEST, and p.
Referenced by amd64_linux_get_syscall_number(), amd64_relocate_instruction(), amd64_skip_main_prologue(), amd64_windows_frame_decode_epilogue(), bfin_linux_get_syscall_number(), cp_print_class_member(), decode_debug_loc_addresses(), disassemble_dwarf_expression(), dwarf2_compile_expr_to_ax(), evaluate_subexp_java(), execute_stack_op(), extend_simple_arg(), extract_mips_address(), fill_gregset(), find_extant_func_descr(), fixup_riprel(), frame_unwind_register_signed(), frv_analyze_prologue(), gnuv3_decode_method_ptr(), hppa_linux_find_global_pointer(), hppabsd_find_global_pointer(), i386_linux_get_syscall_number_from_regcache(), i386_record_lea_modrm_addr(), i386_relocate_instruction(), i386_skip_main_prologue(), ia64_find_global_pointer_from_dynamic_section(), java_value_print(), mips64_fill_fpregset(), mips64_fill_gregset(), mips_eabi_push_dummy_call(), mips_get_mips16_fn_stub_pc(), mips_integer_to_address(), mips_linux_get_syscall_number(), mips_n32n64_push_dummy_call(), mips_o32_push_dummy_call(), mips_o64_push_dummy_call(), mips_pseudo_register_write(), mn10300_analyze_prologue(), mt_select_coprocessor(), ppc_linux_get_syscall_number(), ppc_linux_spe_context(), read_memory_integer(), record_linux_system_call(), regcache_cooked_read_signed(), regcache_raw_read_signed(), rs6000_aix_extract_ld_info(), s390_return_value(), signed_pointer_to_address(), sparc32_linux_get_syscall_number(), sparc64_linux_get_syscall_number(), supply_32bit_reg(), tfile_get_trace_state_variable_value(), tfile_get_traceframe_address(), tfile_trace_find(), trace_save(), and unpack_long().
CORE_ADDR extract_typed_address (const gdb_byte * buf, struct type * type)
Definition at line 171 of file findvar.c.
References _, gdbarch_pointer_to_address(), get_type_arch(), internal_error(), TYPE_CODE, TYPE_CODE_PTR, and TYPE_CODE_REF.
Referenced by ada_val_print_1(), amd64_get_longjmp_target(), c_val_print(), cp_print_value_fields(), darwin_current_sos(), darwin_load_image_infos(), darwin_read_exec_load_addr(), elf_gnu_ifunc_resolve_by_got(), elf_locate_base(), generic_val_print(), get_running_thread_id(), gnuv3_decode_method_ptr(), handle_stap_probe(), i386_unwind_pc(), jit_read_code_entry(), jit_read_descriptor(), ld_so_xfer_auxv(), lm_addr(), lm_info_read(), m68k_unwind_pc(), microblaze_unwind_pc(), nios2_unwind_pc(), open_symbol_file_object(), read_known_tasks_array(), read_known_tasks_list(), read_memory_typed_address(), rs6000_aix_extract_ld_info(), scan_dyntag(), tic6x_unwind_pc(), unpack_long(), value_of_dwarf_reg_entry(), and xtensa_unwind_pc().
ULONGEST extract_unsigned_integer (const gdb_byte * addr, int len, enum bfd_endian byte_order)
Definition at line 86 of file findvar.c.
References _, error(), len, p, and ULONGEST.
Referenced by aarch64_get_longjmp_target(), agent_capability_check(), agent_get_helper_thread_id(), alpha_get_longjmp_target(), alpha_lds(), alpha_read_insn(), alpha_sts(), amd64_darwin_sigcontext_addr(), amd64_epilogue_frame_cache(), amd64_frame_cache_1(), amd64_linux_sigcontext_addr(), amd64_sigtramp_frame_cache(), amd64_windows_find_unwind_info(), amd64_windows_frame_cache(), amd64_windows_frame_decode_epilogue(), amd64_windows_frame_decode_insns(), amd64obsd_collect_uthread(), arm_adjust_breakpoint_address(), arm_breakpoint_from_pc(), arm_get_longjmp_target(), arm_linux_supply_gregset(), arm_push_dummy_call(), arm_symbian_skip_trampoline_code(), avr_pointer_to_address(), avr_pseudo_register_write(), avr_push_dummy_call(), avr_scan_prologue(), bsd_uthread_wait(), build_traceframe_info(), c_get_string(), c_val_print(), char_at(), core_process_module_section(), create_addrmap_from_index(), create_cus_from_index_list(), create_signatured_type_table_from_index(), cris_sigcontext_addr(), cris_sigtramp_frame_unwind_cache(), cris_store_return_value(), darwin_current_sos(), darwin_load_image_infos(), darwin_read_exec_load_addr(), darwin_solib_read_all_image_info_addr(), debug_print_register(), decode_debug_loc_addresses(), decode_debug_loc_dwo_addresses(), decode_loadmap(), default_auxv_parse(), disassemble_dwarf_expression(), display_one_tib(), dsbt_current_sos(), dwarf2_compile_expr_to_ax(), dwarf2_find_location_expression(), dwarf_expr_fetch_address(), enable_break2(), examine_prologue(), execute_cfa_program(), execute_stack_op(), extend_simple_arg(), extract_arm_insn(), extract_call_winsize(), extract_long_unsigned_integer(), fetch_lm_info(), fetch_loadmap(), fetch_mips_16(), fill_gregset(), find_canonical_descriptor_in_load_object(), frame_info(), frame_unwind_register_unsigned(), frv_current_sos(), frv_linux_pc_in_sigtramp(), frv_linux_sigcontext_reg_addr(), frv_linux_sigtramp_frame_cache(), frv_push_dummy_call(), frv_skip_main_prologue(), generic_printstr(), get_target_memory_unsigned(), h8300_push_dummy_call(), h8300_store_return_value(), h8300h_store_return_value(), hppa32_hpux_find_global_pointer(), hppa32_hpux_search_dummy_call_sequence(), hppa64_convert_code_addr_to_fptr(), hppa64_hpux_find_global_pointer(), hppa64_hpux_search_dummy_call_sequence(), hppa_frame_cache(), hppa_frame_prev_register_helper(), hppa_hpux_fetch_register(), hppa_hpux_search_pattern(), hppa_hpux_sigtramp_unwind_sniffer(), hppa_hpux_store_register(), hppa_hpux_supply_save_state(), hppa_hpux_unwind_adjust_stub(), hppa_in_function_epilogue_p(), hppa_linux_find_global_pointer(), hppa_match_insns(), hppabsd_find_global_pointer(), i386_darwin_sigcontext_addr(), i386_frame_cache_1(), i386_get_longjmp_target(), i386_linux_sigcontext_addr(), i386_process_record(), i386_sigtramp_frame_cache(), i386_svr4_sigcontext_addr(), i386bsd_sigcontext_addr(), i386nto_sigcontext_addr(), i386obsd_collect_uthread(), ia64_convert_from_func_ptr_addr(), ia64_dummy_id(), ia64_find_global_pointer_from_dynamic_section(), ia64_frame_cache(), ia64_frame_prev_register(), ia64_hpux_find_global_pointer_from_solib(), ia64_hpux_get_register_from_save_state_t(), ia64_hpux_stopped_in_syscall(), ia64_linux_sigcontext_register_address(), ia64_pseudo_register_write(), ia64_push_dummy_call(), ia64_sigtramp_frame_cache(), ia64_sigtramp_frame_prev_register(), ia64_unwind_pc(), info_spu_dma_cmdlist(), info_spu_dma_command(), info_spu_mailbox_list(), info_spu_proxydma_command(), info_spu_signal_command(), insns_match_pattern(), iq2000_pointer_to_address(), java_value_print(), jit_read_code_entry(), jit_read_descriptor(), link_map_start(), linux_spu_make_corefile_notes(), lm32_push_dummy_call(), lm32_store_return_value(), lm_base(), locexpr_describe_location_piece(), loclist_describe_location(), m32c_m16c_pointer_to_address(), m32c_push_dummy_call(), m32c_return_value(), m32r_push_dummy_call(), m32r_store_return_value(), m68hc11_pseudo_register_write(), m68hc11_push_dummy_call(), m68k_frame_cache(), m68k_get_longjmp_target(), m68k_linux_pc_in_sigtramp(), m68k_linux_sigtramp_frame_cache(), mep_get_insn(), mep_pseudo_cr32_read(), mep_pseudo_cr32_write(), mep_pseudo_csr_write(), mep_push_dummy_call(), microblaze_fetch_instruction(), mips64_linux_get_longjmp_target(), mips_fetch_instruction(), mips_linux_get_longjmp_target(), mips_linux_in_dynsym_stub(), mips_n32n64_push_dummy_call(), mips_o32_push_dummy_call(), mips_o64_push_dummy_call(), mips_skip_pic_trampoline_code(), mips_xfer_memory(), mipsnbsd_get_longjmp_target(), mn10300_push_dummy_call(), modify_field(), monitor_write_memory(), moxie_process_readu(), moxie_process_record(), moxie_store_return_value(), msp430_pseudo_register_write(), msp430_push_dummy_call(), msp430_return_value(), mt_pseudo_register_write(), mt_push_dummy_call(), mt_registers_info(), nios2_get_longjmp_target(), nios2_push_dummy_call(), parse_spufs_run(), pascal_printstr(), pascal_val_print(), pass_in_x(), ppc64_convert_from_func_ptr_addr(), ppc_displaced_step_fixup(), ppc_linux_auxv_parse(), ppc_linux_spe_context(), ppcfbsd_sigtramp_frame_sniffer(), ppcobsd_sigtramp_frame_cache(), ppcobsd_sigtramp_frame_sniffer(), ppu2spu_sniffer(), print_wchar(), printf_wide_c_string(), read_frame_register_unsigned(), read_memory_unsigned_integer(), read_program_header(), read_string(), read_target_long_array(), record_linux_msghdr(), record_linux_sockaddr(), record_linux_system_call(), regcache_cooked_read_unsigned(), regcache_raw_read_unsigned(), rl78_pointer_to_address(), rl78_return_value(), rs6000_aix_extract_ld_info(), rs6000_fetch_instruction(), rs6000_in_function_epilogue_p(), rs6000_skip_main_prologue(), rx_push_dummy_call(), rx_return_value(), s390_auxv_parse(), s390_pseudo_register_write(), s390_return_value(), scan_dyntag_auxv(), score3_adjust_pc_and_fetch_inst(), score7_breakpoint_from_pc(), score7_fetch_inst(), score_push_dummy_call(), sh64_pseudo_register_read(), sh64_pseudo_register_write(), sh64_push_dummy_call(), sh_push_dummy_call_fpu(), sh_push_dummy_call_nofpu(), sh_store_return_value_nofpu(), skip_prologue(), skip_prologue_hard_way(), som_current_sos(), som_open_symbol_file_object(), som_solib_create_inferior_hook(), sparc32obsd_collect_uthread(), sparc64_collect_gregset(), sparc64_pseudo_register_write(), sparc64_supply_gregset(), sparc64obsd_collect_uthread(), sparc_collect_rwindow(), sparc_fetch_wcookie(), sparc_supply_rwindow(), spu2ppu_sniffer(), spu_analyze_prologue(), spu_current_sos(), spu_frame_unwind_cache(), spu_get_longjmp_target(), spu_get_overlay_table(), spu_in_function_epilogue_p(), spu_pointer_to_address(), spu_pseudo_register_write_spu(), spu_push_dummy_call(), spu_software_single_step(), stap_modify_semaphore(), supply_gregset(), svr4_exec_displacement(), tfile_trace_find(), tfile_xfer_partial(), thumb2_copy_table_branch(), thumb_in_function_epilogue_p(), tic6x_get_longjmp_target(), tic6x_push_dummy_call(), tilegx_analyze_prologue(), tilegx_get_longjmp_target(), tilegx_push_dummy_call(), trace_save(), traceframe_walk_blocks(), tramp_frame_start(), unpack_long(), unpack_value_bits_as_long_1(), unsigned_pointer_to_address(), v850_push_dummy_call(), v850_store_return_value(), val_print_string(), value_bit_index(), value_cast(), value_pointer(), xstormy16_find_jmp_table_entry(), xstormy16_pointer_to_address(), xstormy16_push_dummy_call(), xstormy16_resolve_jmp_table_entry(), xtensa_pseudo_register_read(), xtensa_pseudo_register_write(), and xtensa_push_dummy_call().
static int minsym_lookup_iterator_cb (struct objfile * objfile, void * cb_data) [static]
Definition at line 405 of file findvar.c.
References gdb_assert, lookup_minimal_symbol(), minsym_lookup_data::name, minsym_lookup_data::objfile, and minsym_lookup_data::result.
Referenced by default_read_var_value().
void read_frame_register_value (struct value * value, struct frame_info * frame)
Definition at line 656 of file findvar.c.
References check_typedef(), gdb_assert, get_frame_arch(), get_frame_register_value(), len, lval_register, offset, reg_offset, register_size(), regnum, set_value_optimized_out(), TYPE_LENGTH, value_contents_copy(), VALUE_LVAL, value_offset(), value_optimized_out(), VALUE_REGNUM, and value_type().
Referenced by value_from_register().
struct value* read_var_value (struct symbol * var, struct frame_info * frame) [read]
Definition at line 609 of file findvar.c.
References gdb_assert, language_defn::la_read_var_value, language_def(), and SYMBOL_LANGUAGE.
Referenced by bpfinishpy_init(), enumerate_locals(), finish_command_continuation(), frapy_read_var(), insert_exception_resume_breakpoint(), print_variable_and_value(), read_frame_arg(), read_frame_local(), return_command(), sympy_value(), value_of_this(), and value_of_variable().
CORE_ADDR signed_pointer_to_address (struct gdbarch * gdbarch, struct type * type, const gdb_byte * buf)
Definition at line 313 of file findvar.c.
References extract_signed_integer(), gdbarch_byte_order(), and TYPE_LENGTH.
Referenced by mips_gdbarch_init().
void store_signed_integer (gdb_byte * addr, int len, enum bfd_endian byte_order, LONGEST val)
Definition at line 186 of file findvar.c.
References len, and p.
Referenced by aarch64_store_return_value(), address_to_signed_pointer(), amd64_relocate_instruction(), arm_store_return_value(), default_read_var_value(), i386_relocate_instruction(), mi_cmd_data_write_memory(), mips64_fill_fpregset(), mips64_fill_gregset(), mips_eabi_push_dummy_call(), mips_o64_push_dummy_call(), mips_pseudo_register_read(), mips_value_to_register(), mt_pseudo_register_read(), mt_select_coprocessor(), pack_long(), regcache_cooked_write_signed(), regcache_raw_write_signed(), scalar_binop(), supply_32bit_reg(), value_fetch_lazy(), and write_memory_signed_integer().
void store_typed_address (gdb_byte * buf, struct type * type, CORE_ADDR addr)
Definition at line 244 of file findvar.c.
References _, gdbarch_address_to_pointer(), get_type_arch(), internal_error(), TYPE_CODE, TYPE_CODE_PTR, and TYPE_CODE_REF.
Referenced by default_read_var_value(), pack_long(), pack_unsigned_long(), tlb_value_read(), and value_from_pointer().
void store_unsigned_integer (gdb_byte * addr, int len, enum bfd_endian byte_order, ULONGEST val)
Definition at line 214 of file findvar.c.
References len, and p.
Referenced by aarch64_extract_return_value(), ada_value_binop(), add_address_entry(), add_to_spuid_list(), alpha_extract_return_value(), alpha_lds(), alpha_push_dummy_call(), alpha_sts(), amd64_push_dummy_call(), amd64_relocate_instruction(), amd64_windows_push_dummy_call(), amd64obsd_supply_uthread(), arm_extract_return_value(), arm_linux_supply_gregset(), arm_push_dummy_call(), avr_address_to_pointer(), avr_pseudo_register_read(), bfin_extract_return_value(), cris_extract_return_value(), cris_push_dummy_call(), do_ppc_sysv_return_value(), dwarf2_const_value_attr(), dwarf2_const_value_data(), dwarf2_fetch_constant_bytes(), dwarf_expr_fetch_address(), execute_stack_op(), fill_gregset(), find_func_descr(), frame_unwind_got_constant(), frv_extract_return_value(), frv_push_dummy_call(), gnuv3_make_method_ptr(), h8300_extract_return_value(), h8300h_extract_return_value(), hppa32_push_dummy_call(), hppa64_push_dummy_call(), hppa_hpux_fetch_register(), hppa_hpux_store_register(), hppa_hpux_supply_save_state(), hppa_pseudo_register_read(), i386_darwin_push_dummy_call(), i386_push_dummy_call(), i386_relocate_instruction(), i386obsd_supply_uthread(), i387_supply_fsave(), ia64_extract_return_value(), ia64_pseudo_register_read(), ia64_pseudo_register_write(), ia64_push_dummy_call(), iq2000_address_to_pointer(), iq2000_extract_return_value(), iq2000_push_dummy_call(), lm32_extract_return_value(), m32c_m16c_address_to_pointer(), m32c_return_value(), m32r_extract_return_value(), m32r_fetch_register(), m32r_push_dummy_call(), m68hc11_pseudo_register_read(), m68hc11_push_dummy_call(), m68k_push_dummy_call(), mark_common_block_symbol_computed(), mep_pseudo_cr32_read(), mep_pseudo_cr32_write(), mep_push_dummy_call(), mips_eabi_push_dummy_call(), mips_xfer_memory(), mn10300_push_dummy_call(), modify_field(), monitor_read_memory_single(), monitor_supply_register(), moxie_extract_return_value(), msp430_pseudo_register_read(), msp430_push_dummy_call(), msp430_return_value(), mt_return_value(), netorder16(), netorder32(), netorder64(), pack_unsigned_long(), ppc64_sysv_abi_return_value(), ppc_sysv_abi_push_dummy_call(), ppu2spu_unwind_register(), regcache_cooked_write_unsigned(), regcache_raw_write_unsigned(), rl78_address_to_pointer(), rl78_push_dummy_call(), rl78_return_value(), rs6000_lynx178_push_dummy_call(), rs6000_lynx178_return_value(), rs6000_push_dummy_call(), rs6000_return_value(), rx_return_value(), s390_pseudo_register_read(), scalar_binop(), sh64_pseudo_register_read(), sh64_pseudo_register_write(), sh_extract_return_value_nofpu(), som_solib_create_inferior_hook(), sparc32_push_dummy_code(), sparc32_store_arguments(), sparc32obsd_supply_uthread(), sparc64_collect_gregset(), sparc64_pseudo_register_read(), sparc64_supply_gregset(), sparc64obsd_supply_uthread(), sparc_collect_rwindow(), sparc_supply_rwindow(), spu_address_to_pointer(), spu_enumerate_spu_ids(), spu_fetch_inferior_registers(), spu_fetch_registers(), spu_pseudo_register_read_spu(), spu_push_dummy_call(), stap_modify_semaphore(), supply_gregset(), svr4_exec_displacement(), tfile_fetch_registers(), tic6x_push_dummy_call(), unsigned_address_to_pointer(), v850_extract_return_value(), v850_push_dummy_call(), vax_push_dummy_call(), vax_store_arguments(), write_constant_as_bytes(), write_memory_unsigned_integer(), write_one_signatured_type(), write_psymtabs_to_index(), xstormy16_address_to_pointer(), xstormy16_push_dummy_call(), and xtensa_push_dummy_call().
int symbol_read_needs_frame (struct symbol * sym)
Definition at line 345 of file findvar.c.
References _, gdb_assert_not_reached, LOC_ARG, LOC_BLOCK, LOC_COMPUTED, LOC_CONST, LOC_CONST_BYTES, LOC_LABEL, LOC_LOCAL, LOC_OPTIMIZED_OUT, LOC_REF_ARG, LOC_REGISTER, LOC_REGPARM_ADDR, LOC_STATIC, LOC_TYPEDEF, LOC_UNDEF, LOC_UNRESOLVED, SYMBOL_CLASS, and SYMBOL_COMPUTED_OPS.
Referenced by default_read_var_value(), push_variable(), sympy_needs_frame(), sympy_value(), value_of_variable(), and write_var_from_sym().
void unsigned_address_to_pointer (struct gdbarch * gdbarch, struct type * type, gdb_byte * buf, CORE_ADDR addr)
Definition at line 324 of file findvar.c.
References gdbarch_byte_order(), store_unsigned_integer(), and TYPE_LENGTH.
Referenced by gdbarch_alloc().
CORE_ADDR unsigned_pointer_to_address (struct gdbarch * gdbarch, struct type * type, const gdb_byte * buf)
Definition at line 304 of file findvar.c.
References extract_unsigned_integer(), gdbarch_byte_order(), and TYPE_LENGTH.
Referenced by gdbarch_alloc().
struct value* value_from_register (struct type * type, int regnum, struct frame_info * frame) [read]
Definition at line 702 of file findvar.c.
References allocate_value(), check_typedef(), gdbarch_convert_register_p(), gdbarch_register_to_value(), gdbarch_value_from_register(), get_frame_arch(), get_frame_id(), lval_register, mark_value_bytes_unavailable(), read_frame_register_value(), regnum, set_value_optimized_out(), TYPE_LENGTH, value_contents_raw(), VALUE_FRAME_ID, VALUE_LVAL, and VALUE_REGNUM.
Referenced by address_from_register(), default_read_var_value(), dwarf2_evaluate_loc_desc_full(), and set_gdbarch_value_from_register().
struct value* value_of_register (int regnum, struct frame_info * frame) [read]
Definition at line 262 of file findvar.c.
References gdbarch_num_pseudo_regs(), gdbarch_num_regs(), get_frame_arch(), value_fetch_lazy(), value_of_register_lazy(), and value_of_user_reg().
Referenced by default_print_registers_info(), evaluate_subexp_standard(), output_register(), value_of_aarch64_user_reg(), value_of_arm_user_reg(), value_of_builtin_frame_fp_reg(), value_of_builtin_frame_pc_reg(), value_of_builtin_frame_ps_reg(), value_of_builtin_frame_sp_reg(), and value_of_mips_user_reg().
struct value* value_of_register_lazy (struct frame_info * frame, int regnum) [read]
Definition at line 283 of file findvar.c.
References allocate_value_lazy(), frame_id_p(), gdb_assert, gdbarch_num_pseudo_regs(), gdbarch_num_regs(), get_frame_arch(), get_frame_id(), lval_register, register_type(), regnum, VALUE_FRAME_ID, VALUE_LVAL, and VALUE_REGNUM.
Referenced by frame_unwind_got_register(), and value_of_register().