GDB (xrefs): /home/stan/gdb/src/gdb/fork-child.c File Reference
/home/stan/gdb/src/gdb/fork-child.c File Reference
#include "defs.h"
#include "gdb_string.h"
#include "inferior.h"
#include "terminal.h"
#include "target.h"
#include "gdb_wait.h"
#include "gdb_vfork.h"
#include "gdbcore.h"
#include "gdbthread.h"
#include "command.h"
#include "gdbcmd.h"
#include "solib.h"
#include "filestuff.h"
#include <signal.h>
Defines
#define SHELL_FILE "/bin/sh"
Functions
static void breakup_args (char *scratch, char **argv)
static int escape_bang_in_quoted_argument (const char *shell_file)
int fork_inferior (char *exec_file_arg, char *allargs, char **env, void(*traceme_fun)(void), void(*init_trace_fun)(int), void(*pre_trace_fun)(void), char *shell_file_arg, void(*exec_fun)(const char *file, char *const *argv, char *const *env))
void startup_inferior (int ntraps)
static void unset_exec_wrapper_command (char *args, int from_tty)
void _initialize_fork_child (void)
Variables
char ** environ
static char * exec_wrapper
initialize_file_ftype _initialize_fork_child
Define Documentation
#define SHELL_FILE "/bin/sh"
Definition at line 40 of file fork-child.c.
Referenced by fork_inferior().
Function Documentation
void _initialize_fork_child (void)
Definition at line 540 of file fork-child.c.
References _, add_cmd(), add_setshow_filename_cmd(), class_run, exec_wrapper, setlist, showlist, unset_exec_wrapper_command(), and unsetlist.
static void breakup_args (char * scratch, char ** argv) [static]
Definition at line 52 of file fork-child.c.
References strchr().
Referenced by fork_inferior().
static int escape_bang_in_quoted_argument (const char * shell_file) [static]
Definition at line 94 of file fork-child.c.
Referenced by fork_inferior().
int fork_inferior (char * exec_file_arg, char * allargs, char ** env, void(*)(void) traceme_fun, void(*)(int) init_trace_fun, void(*)(void) pre_trace_fun, char * shell_file_arg, void(*)(const char *file, char *const *argv, char *const *env) exec_fun)
Definition at line 124 of file fork-child.c.
References _, add_thread_silent(), inferior::argc, inferior::argv, breakup_args(), close_most_fds(), create_tty_session(), current_inferior(), environ, escape_bang_in_quoted_argument(), exec_wrapper, fprintf_unfiltered(), gdb_flush(), gdb_setpgid(), gdb_stderr, gdb_stdout, get_exec_file(), get_inferior_io_terminal(), have_inferiors(), arm-linux::inf, inferior_appeared(), inferior_ptid, init_thread_list(), len, new_tty(), new_tty_postfork(), new_tty_prefork(), p, perror_with_name(), inferior::pid, pid_to_ptid(), safe_strerror(), SHELL_FILE, sleep(), and STARTUP_WITH_SHELL.
Referenced by darwin_create_inferior(), gnu_create_inferior(), inf_ptrace_create_inferior(), and procfs_create_inferior().
void startup_inferior (int ntraps)
Definition at line 416 of file fork-child.c.
References _, error(), exec_wrapper, target_waitstatus::execd_pathname, gdb_signal_to_name(), gdb_signal_to_string(), inferior_ptid, target_waitstatus::integer, target_waitstatus::kind, memset(), minus_one_ptid, pid_to_ptid(), ptid_get_pid(), resume_signal, set_executing(), target_waitstatus::sig, switch_to_thread(), target_mourn_inferior(), target_resume(), target_supports_multi_process, target_terminal_inferior(), target_terminal_init, target_terminal_ours, target_wait(), TARGET_WAITKIND_EXECD, TARGET_WAITKIND_EXITED, TARGET_WAITKIND_FORKED, TARGET_WAITKIND_IGNORE, TARGET_WAITKIND_LOADED, TARGET_WAITKIND_SIGNALLED, TARGET_WAITKIND_SPURIOUS, TARGET_WAITKIND_STOPPED, TARGET_WAITKIND_SYSCALL_ENTRY, TARGET_WAITKIND_SYSCALL_RETURN, TARGET_WAITKIND_VFORKED, target_waitstatus::value, and xfree().
Referenced by darwin_ptrace_him(), gnu_create_inferior(), inf_ptrace_create_inferior(), and procfs_init_inferior().
static void unset_exec_wrapper_command (char * args, int from_tty) [static]
Definition at line 530 of file fork-child.c.
References exec_wrapper, and xfree().
Referenced by _initialize_fork_child().
Variable Documentation
initialize_file_ftype _initialize_fork_child
Referenced by initialize_all_files().
char** environ
Referenced by fork_inferior(), go32_create_inferior(), init_environ(), and windows_create_inferior().
char* exec_wrapper [static]
Definition at line 44 of file fork-child.c.
Referenced by _initialize_fork_child(), fork_inferior(), startup_inferior(), and unset_exec_wrapper_command().