GDB (xrefs): /home/stan/gdb/src/gdb/frame-unwind.c File Reference
/home/stan/gdb/src/gdb/frame-unwind.c File Reference
#include "defs.h"
#include "frame.h"
#include "frame-unwind.h"
#include "dummy-frame.h"
#include "inline-frame.h"
#include "value.h"
#include "regcache.h"
#include "exceptions.h"
#include "gdb_assert.h"
#include "gdb_obstack.h"
Classes
struct frame_unwind_table_entry
struct frame_unwind_table
Functions
static void * frame_unwind_init (struct obstack *obstack)
void frame_unwind_prepend_unwinder (struct gdbarch *gdbarch, const struct frame_unwind *unwinder)
void frame_unwind_append_unwinder (struct gdbarch *gdbarch, const struct frame_unwind *unwinder)
void frame_unwind_find_by_frame (struct frame_info *this_frame, void **this_cache)
int default_frame_sniffer (const struct frame_unwind *self, struct frame_info *this_frame, void **this_prologue_cache)
enum unwind_stop_reason default_frame_unwind_stop_reason (struct frame_info *this_frame, void **this_cache)
struct value * frame_unwind_got_optimized (struct frame_info *frame, int regnum)
struct value * frame_unwind_got_register (struct frame_info *frame, int regnum, int new_regnum)
struct value * frame_unwind_got_memory (struct frame_info *frame, int regnum, CORE_ADDR addr)
struct value * frame_unwind_got_constant (struct frame_info *frame, int regnum, ULONGEST val)
struct value * frame_unwind_got_bytes (struct frame_info *frame, int regnum, gdb_byte *buf)
struct value * frame_unwind_got_address (struct frame_info *frame, int regnum, CORE_ADDR addr)
void _initialize_frame_unwind (void)
Variables
static struct gdbarch_data * frame_unwind_data
initialize_file_ftype _initialize_frame_unwind
Function Documentation
void _initialize_frame_unwind (void)
Definition at line 242 of file frame-unwind.c.
References _initialize_frame_unwind, frame_unwind_init(), and gdbarch_data_register_pre_init().
int default_frame_sniffer (const struct frame_unwind * self, struct frame_info * this_frame, void ** this_prologue_cache)
Definition at line 139 of file frame-unwind.c.
enum unwind_stop_reason default_frame_unwind_stop_reason (struct frame_info * this_frame, void ** this_cache)
Definition at line 150 of file frame-unwind.c.
Referenced by tramp_frame_prepend_unwinder().
void frame_unwind_append_unwinder (struct gdbarch * gdbarch, const struct frame_unwind * unwinder)
Definition at line 79 of file frame-unwind.c.
References gdbarch_data(), GDBARCH_OBSTACK_ZALLOC, frame_unwind_table_entry::next, frame_unwind_table::osabi_head, and frame_unwind_table_entry::unwinder.
Referenced by aarch64_gdbarch_init(), alpha_gdbarch_init(), alpha_mdebug_init_abi(), amd64_init_abi(), amd64_windows_init_abi(), arm_gdbarch_init(), avr_gdbarch_init(), bfin_gdbarch_init(), cris_gdbarch_init(), dwarf2_append_unwinders(), frv_gdbarch_init(), frv_linux_init_abi(), h8300_gdbarch_init(), hppa_gdbarch_init(), hppa_hpux_init_abi(), hppa_linux_init_abi(), i386_gdbarch_init(), ia64_gdbarch_init(), iq2000_gdbarch_init(), lm32_gdbarch_init(), m32c_gdbarch_init(), m32r_gdbarch_init(), m32r_linux_init_abi(), m68hc11_gdbarch_init(), m68k_gdbarch_init(), m68k_linux_init_abi(), m88k_gdbarch_init(), mep_gdbarch_init(), microblaze_gdbarch_init(), mips_gdbarch_init(), mn10300_frame_unwind_init(), moxie_gdbarch_init(), msp430_gdbarch_init(), mt_gdbarch_init(), nios2_gdbarch_init(), ppcfbsd_init_abi(), ppcobsd_init_abi(), rl78_gdbarch_init(), rs6000_gdbarch_init(), rx_gdbarch_init(), s390_gdbarch_init(), score_gdbarch_init(), sh64_gdbarch_init(), sh_gdbarch_init(), sparc32_gdbarch_init(), sparc32_sol2_init_abi(), sparc32nbsd_init_abi(), sparc32obsd_init_abi(), sparc64_init_abi(), sparc64_sol2_init_abi(), sparc64fbsd_init_abi(), sparc64nbsd_init_abi(), sparc64obsd_init_abi(), spu_gdbarch_init(), tic6x_gdbarch_init(), tilegx_gdbarch_init(), v850_gdbarch_init(), vax_gdbarch_init(), vaxobsd_init_abi(), xstormy16_gdbarch_init(), and xtensa_gdbarch_init().
void frame_unwind_find_by_frame (struct frame_info * this_frame, void ** this_cache)
Definition at line 96 of file frame-unwind.c.
References _, discard_cleanups(), do_cleanups(), gdb_exception::error, frame_prepare_for_sniffer(), gdbarch_data(), get_frame_arch(), internal_error(), frame_unwind_table::list, frame_unwind_table_entry::next, NOT_AVAILABLE_ERROR, gdb_exception::reason, RETURN_MASK_ERROR, frame_unwind::sniffer, throw_exception(), TRY_CATCH, and frame_unwind_table_entry::unwinder.
Referenced by create_new_frame(), frame_unwind_arch(), frame_unwind_register_value(), frame_unwinder_is(), get_frame_id(), get_frame_type(), and get_prev_frame_1().
struct value* frame_unwind_got_address (struct frame_info * frame, int regnum, CORE_ADDR addr) [read]
Definition at line 226 of file frame-unwind.c.
References frame_unwind_arch(), not_lval, pack_long(), register_type(), value_contents_writeable(), and value_zero().
Referenced by dwarf2_frame_prev_register(), and dwarf2_tailcall_prev_register_first().
struct value* frame_unwind_got_bytes (struct frame_info * frame, int regnum, gdb_byte * buf) [read]
Definition at line 211 of file frame-unwind.c.
References frame_unwind_arch(), memcpy(), not_lval, register_size(), register_type(), value_contents_raw(), and value_zero().
Referenced by jit_frame_prev_register(), libunwind_frame_prev_register(), ppu2spu_prev_register(), and spu2ppu_prev_register().
struct value* frame_unwind_got_constant (struct frame_info * frame, int regnum, ULONGEST val) [read]
Definition at line 197 of file frame-unwind.c.
References gdbarch::byte_order, frame_unwind_arch(), gdbarch_byte_order(), not_lval, register_size(), register_type(), store_unsigned_integer(), value_contents_writeable(), and value_zero().
Referenced by aarch64_dwarf2_prev_register(), aarch64_prologue_prev_register(), amd64_frame_prev_register(), amd64_windows_frame_prev_register(), arm_dwarf2_prev_register(), arm_m_exception_prev_register(), arm_prologue_prev_register(), avr_frame_prev_register(), bfin_frame_prev_register(), dwarf2_frame_prev_register(), h8300_frame_prev_register(), hppa_frame_prev_register_helper(), i386_frame_prev_register(), ia64_frame_prev_register(), ia64_sigtramp_frame_prev_register(), iq2000_frame_prev_register(), libunwind_frame_prev_register(), m32c_prev_register(), m68hc11_frame_prev_register(), m68k_frame_prev_register(), m88k_frame_prev_register(), mep_frame_prev_register(), mn10300_frame_prev_register(), moxie_frame_prev_register(), msp430_prev_register(), nios2_frame_prev_register(), rl78_prev_register(), rx_frame_prev_register(), sh64_frame_prev_register(), sh_frame_prev_register(), sparc32_frame_prev_register(), sparc64_frame_prev_register(), tic6x_frame_prev_register(), trad_frame_get_prev_register(), xstormy16_frame_prev_register(), and xtensa_frame_prev_register().
struct value* frame_unwind_got_memory (struct frame_info * frame, int regnum, CORE_ADDR addr) [read]
Definition at line 184 of file frame-unwind.c.
References frame_unwind_arch(), register_type(), set_value_stack(), and value_at_lazy().
Referenced by alpha_sigtramp_frame_prev_register(), amd64_frame_prev_register(), amd64_windows_frame_prev_register(), bfin_frame_prev_register(), dwarf2_frame_prev_register(), h8300_frame_prev_register(), i386_frame_prev_register(), ia64_frame_prev_register(), ia64_sigtramp_frame_prev_register(), iq2000_frame_prev_register(), libunwind_frame_prev_register(), m32c_prev_register(), m68k_frame_prev_register(), mep_frame_prev_register(), mn10300_frame_prev_register(), moxie_frame_prev_register(), msp430_prev_register(), nios2_frame_prev_register(), rl78_prev_register(), rx_frame_prev_register(), sh64_frame_prev_register(), sh_frame_prev_register(), sparc32_frame_prev_register(), sparc64_frame_prev_register(), tic6x_frame_prev_register(), trad_frame_get_prev_register(), xstormy16_frame_prev_register(), and xtensa_frame_prev_register().
struct value* frame_unwind_got_optimized (struct frame_info * frame, int regnum) [read]
Definition at line 162 of file frame-unwind.c.
References allocate_optimized_out_value(), frame_unwind_arch(), and register_type().
Referenced by avr_frame_prev_register(), dwarf2_frame_prev_register(), jit_frame_prev_register(), and trad_frame_get_prev_register().
struct value* frame_unwind_got_register (struct frame_info * frame, int regnum, int new_regnum) [read]
Definition at line 174 of file frame-unwind.c.
References value_of_register_lazy().
Referenced by alpha_sigtramp_frame_prev_register(), amd64_frame_prev_register(), amd64_windows_frame_prev_register(), bfin_frame_prev_register(), dwarf2_frame_prev_register(), h8300_frame_prev_register(), i386_frame_prev_register(), ia64_frame_prev_register(), iq2000_frame_prev_register(), libunwind_frame_prev_register(), m32c_prev_register(), m68k_frame_prev_register(), mep_frame_prev_register(), mn10300_frame_prev_register(), moxie_frame_prev_register(), msp430_prev_register(), nios2_frame_prev_register(), rl78_prev_register(), rx_frame_prev_register(), sh64_frame_prev_register(), sh_frame_prev_register(), sparc32_frame_prev_register(), sparc64_frame_prev_register(), tailcall_frame_prev_register(), tic6x_frame_prev_register(), trad_frame_get_prev_register(), xstormy16_frame_prev_register(), and xtensa_frame_prev_register().
static void* frame_unwind_init (struct obstack * obstack) [static]
Definition at line 47 of file frame-unwind.c.
References dummy_frame_unwind, inline_frame_unwind, frame_unwind_table::list, frame_unwind_table_entry::next, OBSTACK_ZALLOC, frame_unwind_table::osabi_head, and frame_unwind_table_entry::unwinder.
Referenced by _initialize_frame_unwind().
void frame_unwind_prepend_unwinder (struct gdbarch * gdbarch, const struct frame_unwind * unwinder)
Definition at line 65 of file frame-unwind.c.
References gdbarch_data(), GDBARCH_OBSTACK_ZALLOC, frame_unwind_table_entry::next, frame_unwind_table::osabi_head, and frame_unwind_table_entry::unwinder.
Referenced by amd64_init_abi(), amd64obsd_init_abi(), i386obsd_init_abi(), jit_prepend_unwinder(), ppc_linux_init_abi(), spu_gdbarch_init(), and tramp_frame_prepend_unwinder().
Variable Documentation
initialize_file_ftype _initialize_frame_unwind
Referenced by _initialize_frame_unwind(), and initialize_all_files().
struct gdbarch_data* frame_unwind_data [static]
Definition at line 31 of file frame-unwind.c.