GDB (xrefs): /home/stan/gdb/src/gdb/frame.c File Reference
/home/stan/gdb/src/gdb/frame.c File Reference
#include "defs.h"
#include "frame.h"
#include "target.h"
#include "value.h"
#include "inferior.h"
#include "regcache.h"
#include "gdb_assert.h"
#include "gdb_string.h"
#include "user-regs.h"
#include "gdb_obstack.h"
#include "dummy-frame.h"
#include "sentinel-frame.h"
#include "gdbcore.h"
#include "annotate.h"
#include "language.h"
#include "frame-unwind.h"
#include "frame-base.h"
#include "command.h"
#include "gdbcmd.h"
#include "observer.h"
#include "objfiles.h"
#include "exceptions.h"
#include "gdbthread.h"
#include "block.h"
#include "inline-frame.h"
#include "tracepoint.h"
#include "hashtab.h"
#include "unwind_stop_reasons.def"
Classes
struct frame_info
Defines
#define SET(name, description) case name: return _(description);
Functions
static struct frame_info * get_prev_frame_1 (struct frame_info *this_frame)
static struct frame_info * get_prev_frame_raw (struct frame_info *this_frame)
static hashval_t frame_addr_hash (const void *ap)
static int frame_addr_hash_eq (const void *a, const void *b)
static void frame_stash_create (void)
static void frame_stash_add (struct frame_info *frame)
static struct frame_info * frame_stash_find (struct frame_id id)
static void frame_stash_invalidate (void)
static void show_frame_debug (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static void show_backtrace_past_main (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static void show_backtrace_past_entry (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static void show_backtrace_limit (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static void fprint_field (struct ui_file *file, const char *name, int p, CORE_ADDR addr)
void fprint_frame_id (struct ui_file *file, struct frame_id id)
static void fprint_frame_type (struct ui_file *file, enum frame_type type)
static void fprint_frame (struct ui_file *file, struct frame_info *fi)
static struct frame_info * skip_artificial_frames (struct frame_info *frame)
struct frame_id get_frame_id (struct frame_info *fi)
struct frame_id get_stack_frame_id (struct frame_info *next_frame)
struct frame_id frame_unwind_caller_id (struct frame_info *next_frame)
struct frame_id frame_id_build_special (CORE_ADDR stack_addr, CORE_ADDR code_addr, CORE_ADDR special_addr)
struct frame_id frame_id_build (CORE_ADDR stack_addr, CORE_ADDR code_addr)
struct frame_id frame_id_build_wild (CORE_ADDR stack_addr)
int frame_id_p (struct frame_id l)
int frame_id_artificial_p (struct frame_id l)
int frame_id_eq (struct frame_id l, struct frame_id r)
static int frame_id_inner (struct gdbarch *gdbarch, struct frame_id l, struct frame_id r)
struct frame_info * frame_find_by_id (struct frame_id id)
static int frame_unwind_pc_if_available (struct frame_info *this_frame, CORE_ADDR *pc)
static CORE_ADDR frame_unwind_pc (struct frame_info *this_frame)
CORE_ADDR frame_unwind_caller_pc (struct frame_info *this_frame)
int frame_unwind_caller_pc_if_available (struct frame_info *this_frame, CORE_ADDR *pc)
int get_frame_func_if_available (struct frame_info *this_frame, CORE_ADDR *pc)
CORE_ADDR get_frame_func (struct frame_info *this_frame)
static enum register_status do_frame_register_read (void *src, int regnum, gdb_byte *buf)
struct regcache * frame_save_as_regcache (struct frame_info *this_frame)
void frame_pop (struct frame_info *this_frame)
void frame_register_unwind (struct frame_info *frame, int regnum, int *optimizedp, int *unavailablep, enum lval_type *lvalp, CORE_ADDR *addrp, int *realnump, gdb_byte *bufferp)
void frame_register (struct frame_info *frame, int regnum, int *optimizedp, int *unavailablep, enum lval_type *lvalp, CORE_ADDR *addrp, int *realnump, gdb_byte *bufferp)
void frame_unwind_register (struct frame_info *frame, int regnum, gdb_byte *buf)
void get_frame_register (struct frame_info *frame, int regnum, gdb_byte *buf)
struct value * frame_unwind_register_value (struct frame_info *frame, int regnum)
struct value * get_frame_register_value (struct frame_info *frame, int regnum)
LONGEST frame_unwind_register_signed (struct frame_info *frame, int regnum)
LONGEST get_frame_register_signed (struct frame_info *frame, int regnum)
ULONGEST frame_unwind_register_unsigned (struct frame_info *frame, int regnum)
ULONGEST get_frame_register_unsigned (struct frame_info *frame, int regnum)
int read_frame_register_unsigned (struct frame_info *frame, int regnum, ULONGEST *val)
void put_frame_register (struct frame_info *frame, int regnum, const gdb_byte *buf)
int deprecated_frame_register_read (struct frame_info *frame, int regnum, gdb_byte *myaddr)
int get_frame_register_bytes (struct frame_info *frame, int regnum, CORE_ADDR offset, int len, gdb_byte *myaddr, int *optimizedp, int *unavailablep)
void put_frame_register_bytes (struct frame_info *frame, int regnum, CORE_ADDR offset, int len, const gdb_byte *myaddr)
static struct frame_info * create_sentinel_frame (struct program_space *pspace, struct regcache *regcache)
void * frame_obstack_zalloc (unsigned long size)
static int unwind_to_current_frame (struct ui_out *ui_out, void *args)
struct frame_info * get_current_frame (void)
int has_stack_frames (void)
struct frame_info * get_selected_frame (const char *message)
struct frame_info * get_selected_frame_if_set (void)
struct frame_info * deprecated_safe_get_selected_frame (void)
void select_frame (struct frame_info *fi)
struct frame_info * create_new_frame (CORE_ADDR addr, CORE_ADDR pc)
struct frame_info * get_next_frame (struct frame_info *this_frame)
static void frame_observer_target_changed (struct target_ops *target)
void reinit_frame_cache (void)
static void frame_register_unwind_location (struct frame_info *this_frame, int regnum, int *optimizedp, enum lval_type *lvalp, CORE_ADDR *addrp, int *realnump)
static void frame_debug_got_null_frame (struct frame_info *this_frame, const char *reason)
static int inside_main_func (struct frame_info *this_frame)
static int inside_entry_func (struct frame_info *this_frame)
struct frame_info * get_prev_frame (struct frame_info *this_frame)
CORE_ADDR get_frame_pc (struct frame_info *frame)
int get_frame_pc_if_available (struct frame_info *frame, CORE_ADDR *pc)
CORE_ADDR get_frame_address_in_block (struct frame_info *this_frame)
int get_frame_address_in_block_if_available (struct frame_info *this_frame, CORE_ADDR *pc)
void find_frame_sal (struct frame_info *frame, struct symtab_and_line *sal)
CORE_ADDR get_frame_base (struct frame_info *fi)
CORE_ADDR get_frame_base_address (struct frame_info *fi)
CORE_ADDR get_frame_locals_address (struct frame_info *fi)
CORE_ADDR get_frame_args_address (struct frame_info *fi)
int frame_unwinder_is (struct frame_info *fi, const struct frame_unwind *unwinder)
int frame_relative_level (struct frame_info *fi)
enum frame_type get_frame_type (struct frame_info *frame)
struct program_space * get_frame_program_space (struct frame_info *frame)
struct program_space * frame_unwind_program_space (struct frame_info *this_frame)
struct address_space * get_frame_address_space (struct frame_info *frame)
void get_frame_memory (struct frame_info *this_frame, CORE_ADDR addr, gdb_byte *buf, int len)
LONGEST get_frame_memory_signed (struct frame_info *this_frame, CORE_ADDR addr, int len)
ULONGEST get_frame_memory_unsigned (struct frame_info *this_frame, CORE_ADDR addr, int len)
int safe_frame_unwind_memory (struct frame_info *this_frame, CORE_ADDR addr, gdb_byte *buf, int len)
struct gdbarch * get_frame_arch (struct frame_info *this_frame)
struct gdbarch * frame_unwind_arch (struct frame_info *next_frame)
struct gdbarch * frame_unwind_caller_arch (struct frame_info *next_frame)
CORE_ADDR get_frame_sp (struct frame_info *this_frame)
enum unwind_stop_reason get_frame_unwind_stop_reason (struct frame_info *frame)
const char * frame_stop_reason_string (enum unwind_stop_reason reason)
static void frame_cleanup_after_sniffer (void *arg)
struct cleanup * frame_prepare_for_sniffer (struct frame_info *frame, const struct frame_unwind *unwind)
static void set_backtrace_cmd (char *args, int from_tty)
static void show_backtrace_cmd (char *args, int from_tty)
void _initialize_frame (void)
Variables
static htab_t frame_stash
unsigned int frame_debug
static int backtrace_past_main
static int backtrace_past_entry
static unsigned int backtrace_limit = UINT_MAX
struct frame_id null_frame_id
struct frame_id outer_frame_id = { 0, 0, 0, 0, 0, 1, 0 }
static struct frame_info * current_frame
static struct obstack frame_cache_obstack
static struct frame_info * selected_frame
initialize_file_ftype _initialize_frame
static struct cmd_list_element * set_backtrace_cmdlist
static struct cmd_list_element * show_backtrace_cmdlist
Define Documentation
#define SET (name, description) case name: return _(description);
Function Documentation
void _initialize_frame (void)
Definition at line 2522 of file frame.c.
References _, _initialize_frame, add_prefix_cmd(), add_setshow_boolean_cmd(), add_setshow_uinteger_cmd(), add_setshow_zuinteger_cmd(), backtrace_limit, backtrace_past_entry, backtrace_past_main, class_maintenance, class_obscure, frame_cache_obstack, frame_debug, frame_observer_target_changed(), frame_stash_create(), observer_attach_target_changed(), set_backtrace_cmd(), setdebuglist, setlist, show_backtrace_cmd(), show_backtrace_limit(), show_backtrace_past_entry(), show_backtrace_past_main(), show_frame_debug(), showdebuglist, and showlist.
struct frame_info* create_new_frame (CORE_ADDR addr, CORE_ADDR pc) [read]
Definition at line 1534 of file frame.c.
References frame_info::aspace, create_sentinel_frame(), current_program_space, fprint_frame(), fprintf_unfiltered(), frame_debug, frame_id_build(), FRAME_OBSTACK_ZALLOC, frame_unwind_find_by_frame(), gdb_stdlog, get_current_regcache(), hex_string(), frame_info::next, frame_info::p, frame_info::prev_pc, frame_info::prologue_cache, frame_info::pspace, frame_info::this_id, and frame_info::value.
Referenced by mn10300_push_dummy_call(), and parse_frame_specification_1().
static struct frame_info* create_sentinel_frame (struct program_space * pspace, struct regcache * regcache) [static, read]
Definition at line 1307 of file frame.c.
References frame_info::aspace, fprint_frame(), fprintf_unfiltered(), frame_debug, FRAME_OBSTACK_ZALLOC, gdb_stdlog, get_regcache_aspace(), frame_info::level, frame_info::next, null_frame_id, frame_info::p, frame_info::prologue_cache, frame_info::pspace, sentinel_frame_cache(), sentinel_frame_unwind, frame_info::this_id, frame_info::unwind, and frame_info::value.
Referenced by create_new_frame(), and get_current_frame().
int deprecated_frame_register_read (struct frame_info * frame, int regnum, gdb_byte * myaddr)
Definition at line 1171 of file frame.c.
References frame_register().
Referenced by do_frame_register_read(), i386_frame_cache_1(), jit_unwind_reg_get_impl(), mips_read_fp_register_double(), mips_read_fp_register_single(), mt_registers_info(), print_gp_register_row(), put_frame_register_bytes(), sh64_do_fp_register(), and sh64_do_register().
struct frame_info* deprecated_safe_get_selected_frame (void) [read]
Definition at line 1477 of file frame.c.
References get_selected_frame(), and has_stack_frames().
Referenced by check_frame_language_change(), default_macro_scope(), get_frame_language(), make_visible_with_new_height(), tui_enable(), and value_assign().
static enum register_status do_frame_register_read (void * src, int regnum, gdb_byte * buf) [static]
Definition at line 848 of file frame.c.
References deprecated_frame_register_read(), REG_UNAVAILABLE, and REG_VALID.
Referenced by frame_save_as_regcache().
void find_frame_sal (struct frame_info * frame, struct symtab_and_line * sal)
Definition at line 2160 of file frame.c.
References find_pc_line(), frame_inlined_callees(), gdb_assert, get_frame_address_in_block(), get_frame_function(), get_frame_pc(), get_frame_pc_if_available(), get_frame_program_space(), get_next_frame(), inferior_ptid, init_sal(), inline_skipped_symbol(), symtab_and_line::line, symtab_and_line::pc, symtab_and_line::pspace, SYMBOL_LINE, SYMBOL_SYMTAB, and symtab_and_line::symtab.
Referenced by frame_info(), frapy_find_sal(), gdb_loc(), handle_inferior_event(), is_known_support_routine(), print_frame_info(), set_current_sal_from_frame(), set_step_frame(), and tui_show_frame_info().
static void fprint_field (struct ui_file * file, const char * name, int p, CORE_ADDR addr) [static]
Definition at line 281 of file frame.c.
References fprintf_unfiltered(), and hex_string().
Referenced by fprint_frame_id().
static void fprint_frame (struct ui_file * file, struct frame_info * fi) [static]
Definition at line 336 of file frame.c.
References frame_info::addr, fprint_frame_id(), fprint_frame_type(), fprintf_unfiltered(), gdb_print_host_address(), hex_string(), frame_info::level, frame_info::next, frame_info::p, frame_info::prev_func, frame_info::prev_pc, frame_info::this_id, frame_unwind::type, frame_info::unwind, and frame_info::value.
Referenced by create_new_frame(), create_sentinel_frame(), get_prev_frame_1(), and get_prev_frame_raw().
void fprint_frame_id (struct ui_file * file, struct frame_id id)
Definition at line 290 of file frame.c.
References fprint_field(), and fprintf_unfiltered().
Referenced by fprint_dummy_frames(), fprint_frame(), frame_id_eq(), frame_id_inner(), frame_id_p(), frapy_str(), and get_frame_id().
static void fprint_frame_type (struct ui_file * file, enum frame_type type) [static]
Definition at line 304 of file frame.c.
References ARCH_FRAME, DUMMY_FRAME, fprintf_unfiltered(), INLINE_FRAME, NORMAL_FRAME, SENTINEL_FRAME, SIGTRAMP_FRAME, and TAILCALL_FRAME.
Referenced by fprint_frame().
static hashval_t frame_addr_hash (const void * ap) [static]
Definition at line 144 of file frame.c.
References frame_id::code_addr, frame_id::code_addr_p, gdb_assert, hash(), frame_id::special_addr, frame_id::special_addr_p, frame_id::stack_addr, frame_id::stack_addr_p, frame_info::this_id, and frame_info::value.
Referenced by frame_stash_create().
static int frame_addr_hash_eq (const void * a, const void * b) [static]
Definition at line 170 of file frame.c.
References frame_id_eq(), frame_info::this_id, and frame_info::value.
Referenced by frame_stash_create().
static void frame_cleanup_after_sniffer (void * arg) [static]
Definition at line 2464 of file frame.c.
References frame_info::addr, gdb_assert, frame_info::p, frame_info::prev_func, frame_info::prev_p, frame_info::prologue_cache, frame_info::this_id, and frame_info::unwind.
Referenced by frame_prepare_for_sniffer().
static void frame_debug_got_null_frame (struct frame_info * this_frame, const char * reason) [static]
Definition at line 1898 of file frame.c.
References fprintf_unfiltered(), frame_debug, gdb_stdlog, and frame_info::level.
Referenced by get_prev_frame().
struct frame_info* frame_find_by_id (struct frame_id id) [read]
Definition at line 647 of file frame.c.
References frame_id_eq(), frame_id_inner(), frame_id_p(), frame_stash_find(), get_current_frame(), get_frame_arch(), get_frame_id(), get_frame_type(), get_prev_frame(), and NORMAL_FRAME.
Referenced by address_of_variable(), backtrace_command_1(), bpfinishpy_detect_out_scope_cb(), check_longjmp_breakpoint_for_call_dummy(), check_scope(), do_print_variable_and_value(), frame_object_to_frame_info(), handle_inferior_event(), read_pieced_value(), restore_selected_frame(), update_watchpoint(), value_assign(), value_fetch_lazy(), varobj_create(), watchpoint_check(), and write_pieced_value().
int frame_id_artificial_p (struct frame_id l)
Definition at line 511 of file frame.c.
References frame_id::artificial_depth, and frame_id_p().
Referenced by set_momentary_breakpoint().
struct frame_id frame_id_build (CORE_ADDR stack_addr, CORE_ADDR code_addr) [read]
Definition at line 470 of file frame.c.
References frame_id::code_addr, null_frame_id, and frame_id::stack_addr.
Referenced by aarch64_dummy_id(), aarch64_linux_sigframe_init(), aarch64_prologue_this_id(), aarch64_stub_this_id(), alpha_dummy_id(), alpha_heuristic_frame_this_id(), alpha_mdebug_frame_this_id(), alpha_sigtramp_frame_this_id(), am33_linux_sigframe_cache_init(), amd64_dummy_id(), amd64_epilogue_frame_this_id(), amd64_frame_this_id(), amd64_sigtramp_frame_this_id(), amd64_windows_frame_this_id(), amd64obsd_trapframe_cache(), arm_dummy_id(), arm_linux_restart_syscall_init(), arm_linux_sigtramp_cache(), arm_m_exception_this_id(), arm_prologue_this_id(), arm_stub_this_id(), armobsd_sigframe_init(), avr_dummy_id(), avr_frame_this_id(), bfin_dummy_id(), bfin_frame_this_id(), bfin_linux_sigframe_init(), call_function_by_hand(), create_new_frame(), cris_dummy_id(), cris_frame_this_id(), cris_sigtramp_frame_this_id(), dwarf2_frame_this_id(), frv_dummy_id(), frv_frame_this_id(), frv_linux_sigtramp_frame_cache(), h8300_dummy_id(), h8300_frame_this_id(), hppa_dummy_id(), hppa_fallback_frame_this_id(), hppa_frame_this_id(), hppa_hpux_sigtramp_frame_this_id(), hppa_linux_sigtramp_frame_this_id(), hppa_stub_frame_this_id(), hppanbsd_sigtramp_cache_init(), i386_dummy_id(), i386_epilogue_frame_this_id(), i386_frame_this_id(), i386_sigtramp_frame_this_id(), i386nbsd_sigtramp_cache_init(), i386obsd_trapframe_cache(), iq2000_dummy_id(), iq2000_frame_this_id(), jit_frame_this_id(), libunwind_frame_this_id(), lm32_dummy_id(), lm32_frame_this_id(), m32c_dummy_id(), m32c_this_id(), m32r_dummy_id(), m32r_frame_this_id(), m32r_linux_sigtramp_frame_this_id(), m68hc11_dummy_id(), m68hc11_frame_this_id(), m68k_dummy_id(), m68k_frame_this_id(), m68k_linux_sigtramp_frame_cache(), m68kobsd_sigtramp_cache_init(), m88k_dummy_id(), m88k_frame_this_id(), mep_dummy_id(), mep_frame_this_id(), microblaze_frame_this_id(), microblaze_linux_sigtramp_cache(), mips64obsd_sigframe_init(), mips_dummy_id(), mips_insn16_frame_this_id(), mips_insn32_frame_this_id(), mips_irix_n32_stack_tramp_frame_init(), mips_irix_n32_tramp_frame_init(), mips_linux_n32n64_sigframe_init(), mips_linux_o32_sigframe_init(), mips_micro_frame_this_id(), mips_stub_frame_cache(), mn10300_dummy_id(), mn10300_frame_this_id(), moxie_dummy_id(), moxie_frame_this_id(), msp430_dummy_id(), msp430_this_id(), mt_dummy_id(), mt_frame_this_id(), nios2_dummy_id(), nios2_frame_this_id(), nios2_linux_rt_sigreturn_init(), nios2_linux_sigreturn_init(), nios2_stub_frame_cache(), ppc_linux_sigtramp_cache(), ppcfbsd_sigtramp_frame_cache(), ppcnbsd_sigtramp_cache_init(), ppcobsd_sigtramp_frame_cache(), ppu2spu_sniffer(), rl78_dummy_id(), rl78_this_id(), rs6000_dummy_id(), rs6000_frame_this_id(), rx_dummy_id(), rx_frame_this_id(), s390_dummy_id(), s390_frame_this_id(), s390_sigtramp_frame_this_id(), s390_stub_frame_this_id(), score_dummy_id(), score_prologue_this_id(), sh64_dummy_id(), sh64_frame_this_id(), sh_dummy_id(), sh_frame_this_id(), sh_linux_sigtramp_cache(), sh_stub_this_id(), sparc32_frame_this_id(), sparc32_linux_sigframe_init(), sparc32_sol2_sigtramp_frame_this_id(), sparc32nbsd_sigcontext_frame_this_id(), sparc32obsd_sigtramp_frame_this_id(), sparc64_frame_this_id(), sparc64_linux_sigframe_init(), sparc64_sol2_sigtramp_frame_this_id(), sparc64fbsd_sigtramp_frame_this_id(), sparc64nbsd_sigcontext_frame_this_id(), sparc64obsd_frame_this_id(), sparc64obsd_trapframe_this_id(), sparc_dummy_id(), spu2ppu_sniffer(), spu_dummy_id(), spu_frame_this_id(), tic6x_dummy_id(), tic6x_frame_this_id(), tic6x_linux_rt_sigreturn_init(), tic6x_stub_this_id(), tilegx_frame_this_id(), tilegx_linux_sigframe_init(), tilegx_unwind_dummy_id(), v850_dummy_id(), v850_frame_this_id(), vax_dummy_id(), vax_frame_this_id(), vaxobsd_sigtramp_frame_cache(), xstormy16_dummy_id(), xstormy16_frame_this_id(), xtensa_dummy_id(), and xtensa_frame_this_id().
struct frame_id frame_id_build_special (CORE_ADDR stack_addr, CORE_ADDR code_addr, CORE_ADDR special_addr) [read]
Definition at line 455 of file frame.c.
References frame_id::code_addr, null_frame_id, frame_id::special_addr, and frame_id::stack_addr.
Referenced by ia64_dummy_id(), ia64_frame_this_id(), ia64_hpux_dummy_id(), and ia64_sigtramp_frame_this_id().
struct frame_id frame_id_build_wild (CORE_ADDR stack_addr) [read]
Definition at line 482 of file frame.c.
References null_frame_id, and frame_id::stack_addr.
Referenced by parse_frame_specification_1().
int frame_id_eq (struct frame_id l, struct frame_id r)
Definition at line 520 of file frame.c.
References frame_id::artificial_depth, frame_id::code_addr, frame_id::code_addr_p, fprint_frame_id(), fprintf_unfiltered(), frame_debug, gdb_stdlog, frame_id::special_addr, frame_id::special_addr_p, frame_id::stack_addr, and frame_id::stack_addr_p.
Referenced by bpfinishpy_init(), bpstat_check_breakpoint_conditions(), dummy_frame_sniffer(), elf_gnu_ifunc_resolver_stop(), frame_addr_hash_eq(), frame_find_by_id(), frapy_richcompare(), get_prev_frame_1(), handle_inferior_event(), inline_frame_this_id(), lookup_dummy_frame(), normal_stop(), parse_frame_specification_1(), pop_dummy_frame_bpt(), restore_selected_frame(), stepped_in_from(), and tfind_1().
static int frame_id_inner (struct gdbarch * gdbarch, struct frame_id l, struct frame_id r) [static]
Definition at line 599 of file frame.c.
References frame_id::artificial_depth, block_for_pc(), frame_id::code_addr, frame_id::code_addr_p, contained_in(), fprint_frame_id(), fprintf_unfiltered(), frame_debug, gdb_assert, gdb_stdlog, gdbarch_inner_than(), frame_id::special_addr, frame_id::special_addr_p, frame_id::stack_addr, and frame_id::stack_addr_p.
Referenced by frame_find_by_id(), and get_prev_frame_1().
int frame_id_p (struct frame_id l)
Definition at line 492 of file frame.c.
References fprint_frame_id(), fprintf_unfiltered(), frame_debug, gdb_stdlog, memcmp(), p, and frame_id::stack_addr_p.
Referenced by bpstat_check_breakpoint_conditions(), elf_gnu_ifunc_resolver_stop(), frame_find_by_id(), frame_id_artificial_p(), get_frame_id(), handle_inferior_event(), inline_frame_this_id(), insert_step_resume_breakpoint_at_caller(), print_one_breakpoint_location(), until_break_command(), value_of_register_lazy(), varobj_create(), and watch_command_1().
static void frame_observer_target_changed (struct target_ops * target) [static]
Definition at line 1594 of file frame.c.
References reinit_frame_cache().
Referenced by _initialize_frame().
void* frame_obstack_zalloc (unsigned long size)
Definition at line 1347 of file frame.c.
References frame_cache_obstack, and memset().
void frame_pop (struct frame_info * this_frame)
Definition at line 870 of file frame.c.
References _, do_cleanups(), DUMMY_FRAME, dummy_frame_pop(), error(), frame_save_as_regcache(), get_current_regcache(), get_frame_id(), get_frame_type(), get_prev_frame(), get_prev_frame_1(), make_cleanup_regcache_xfree(), regcache_cpy(), reinit_frame_cache(), and TAILCALL_FRAME.
Referenced by normal_stop(), and return_command().
struct cleanup* frame_prepare_for_sniffer (struct frame_info * frame, const struct frame_unwind * unwind) [read]
Definition at line 2496 of file frame.c.
References frame_cleanup_after_sniffer(), gdb_assert, make_cleanup(), and frame_info::unwind.
Referenced by frame_unwind_find_by_frame().
void frame_register (struct frame_info * frame, int regnum, int * optimizedp, int * unavailablep, enum lval_type * lvalp, CORE_ADDR * addrp, int * realnump, gdb_byte * bufferp)
Definition at line 962 of file frame.c.
References frame_register_unwind(), gdb_assert, and frame_info::next.
Referenced by deprecated_frame_register_read(), get_frame_register_bytes(), and put_frame_register().
void frame_register_unwind (struct frame_info * frame, int regnum, int * optimizedp, int * unavailablep, enum lval_type * lvalp, CORE_ADDR * addrp, int * realnump, gdb_byte * bufferp)
Definition at line 921 of file frame.c.
References frame_unwind_register_value(), gdb_assert, memcpy(), memset(), release_value(), TYPE_LENGTH, value_address(), value_contents_all(), value_entirely_available(), value_free(), VALUE_LVAL, value_optimized_out(), VALUE_REGNUM, and value_type().
Referenced by frame_info(), frame_register(), frame_register_unwind_location(), and frame_unwind_register().
static void frame_register_unwind_location (struct frame_info * this_frame, int regnum, int * optimizedp, enum lval_type * lvalp, CORE_ADDR * addrp, int * realnump) [static]
Definition at line 1634 of file frame.c.
References frame_register_unwind(), gdb_assert, get_next_frame(), frame_info::level, and lval_register.
Referenced by get_prev_frame_1().
int frame_relative_level (struct frame_info * fi)
Definition at line 2286 of file frame.c.
References frame_info::level.
Referenced by amd64_epilogue_frame_sniffer(), existing_next_levels(), frame_info(), hppa_fallback_frame_cache(), hppa_frame_cache(), i386_epilogue_frame_sniffer(), i386_stack_tramp_frame_sniffer(), ia64_hpux_size_of_register_frame(), make_cleanup_restore_current_thread(), microblaze_unwind_pc(), mips_unwind_pc(), nios2_analyze_prologue(), print_frame(), print_frame_info(), py_print_frame(), select_frame(), task_command_1(), and value_fetch_lazy().
struct regcache* frame_save_as_regcache (struct frame_info * this_frame) [read]
Definition at line 857 of file frame.c.
References discard_cleanups(), do_frame_register_read(), get_frame_address_space(), get_frame_arch(), make_cleanup_regcache_xfree(), regcache_save(), and regcache_xmalloc().
Referenced by frame_pop(), mi_cmd_data_list_changed_registers(), and spu2ppu_sniffer().
static void frame_stash_add (struct frame_info * frame) [static]
Definition at line 196 of file frame.c.
References frame_stash, and frame_info::level.
Referenced by get_frame_id().
static void frame_stash_create (void) [static]
Definition at line 183 of file frame.c.
References frame_addr_hash(), frame_addr_hash_eq(), and frame_stash.
Referenced by _initialize_frame().
static struct frame_info* frame_stash_find (struct frame_id id) [static, read]
Definition at line 215 of file frame.c.
References frame_stash, frame_info::this_id, and frame_info::value.
Referenced by frame_find_by_id().
static void frame_stash_invalidate (void) [static]
Definition at line 230 of file frame.c.
References frame_stash.
Referenced by reinit_frame_cache().
const char* frame_stop_reason_string (enum unwind_stop_reason reason)
Definition at line 2445 of file frame.c.
References internal_error().
Referenced by backtrace_command_1(), frame_info(), and gdbpy_frame_stop_reason_string().
struct gdbarch* frame_unwind_arch (struct frame_info * next_frame) [read]
Definition at line 2373 of file frame.c.
References frame_info::arch, fprintf_unfiltered(), frame_debug, frame_unwind_find_by_frame(), gdb_stdlog, gdbarch_bfd_arch_info(), get_frame_arch(), frame_info::level, frame_info::p, frame_info::prev_arch, frame_unwind::prev_arch, frame_info::prologue_cache, and frame_info::unwind.
Referenced by arm_linux_sigreturn_return_addr(), dwarf2_tailcall_sniffer_first(), dwarf_expr_reg_to_entry_parameter(), frame_unwind_caller_arch(), frame_unwind_got_address(), frame_unwind_got_bytes(), frame_unwind_got_constant(), frame_unwind_got_memory(), frame_unwind_got_optimized(), frame_unwind_pc_if_available(), frame_unwind_register_signed(), frame_unwind_register_unsigned(), frame_unwind_register_value(), and get_frame_arch().
struct gdbarch* frame_unwind_caller_arch (struct frame_info * next_frame) [read]
Definition at line 2401 of file frame.c.
References frame_unwind_arch(), and skip_artificial_frames().
Referenced by insert_step_resume_breakpoint_at_caller(), until_break_command(), and watch_command_1().
struct frame_id frame_unwind_caller_id (struct frame_info * next_frame) [read]
Definition at line 434 of file frame.c.
References get_frame_id(), get_prev_frame_1(), null_frame_id, and skip_artificial_frames().
Referenced by handle_inferior_event(), insert_step_resume_breakpoint_at_caller(), until_break_command(), and watch_command_1().
CORE_ADDR frame_unwind_caller_pc (struct frame_info * this_frame)
Definition at line 780 of file frame.c.
References frame_unwind_pc(), and skip_artificial_frames().
Referenced by arm_linux_sigreturn_return_addr(), glibc_skip_solib_resolver(), insert_step_resume_breakpoint_at_caller(), mips_linux_skip_resolver(), mips_linux_syscall_next_pc(), nios2_linux_syscall_next_pc(), obsd_skip_solib_resolver(), sol2_skip_solib_resolver(), tic6x_linux_syscall_next_pc(), until_break_command(), and watch_command_1().
int frame_unwind_caller_pc_if_available (struct frame_info * this_frame, CORE_ADDR * pc)
Definition at line 786 of file frame.c.
References frame_unwind_pc_if_available(), and skip_artificial_frames().
Referenced by frame_info().
static CORE_ADDR frame_unwind_pc (struct frame_info * this_frame) [static]
Definition at line 769 of file frame.c.
References _, frame_unwind_pc_if_available(), NOT_AVAILABLE_ERROR, and throw_error().
Referenced by frame_unwind_caller_pc(), get_frame_pc(), and get_frame_pc_if_available().
static int frame_unwind_pc_if_available (struct frame_info * this_frame, CORE_ADDR * pc) [static]
Definition at line 695 of file frame.c.
References _, gdb_exception::error, fprintf_unfiltered(), frame_debug, frame_unwind_arch(), gdb_stdlog, gdbarch_unwind_pc(), gdbarch_unwind_pc_p(), hex_string(), internal_error(), frame_info::level, NOT_AVAILABLE_ERROR, frame_info::p, frame_info::prev_pc, gdb_exception::reason, RETURN_MASK_ERROR, throw_exception(), TRY_CATCH, and frame_info::value.
Referenced by frame_unwind_caller_pc_if_available(), and frame_unwind_pc().
struct program_space* frame_unwind_program_space (struct frame_info * this_frame) [read]
Definition at line 2311 of file frame.c.
References gdb_assert, and frame_info::pspace.
Referenced by insert_step_resume_breakpoint_at_caller().
void frame_unwind_register (struct frame_info * frame, int regnum, gdb_byte * buf)
Definition at line 982 of file frame.c.
References _, error(), frame_register_unwind(), value::lval, NOT_AVAILABLE_ERROR, and throw_error().
Referenced by frame_unwind_register_signed(), frame_unwind_register_unsigned(), get_frame_register(), i386_unwind_pc(), ia64_unwind_pc(), m68k_unwind_pc(), microblaze_unwind_pc(), nios2_unwind_pc(), tic6x_unwind_pc(), and xtensa_unwind_pc().
LONGEST frame_unwind_register_signed (struct frame_info * frame, int regnum)
Definition at line 1077 of file frame.c.
References gdbarch::byte_order, extract_signed_integer(), frame_unwind_arch(), frame_unwind_register(), gdbarch_byte_order(), MAX_REGISTER_SIZE, register_size(), and size.
Referenced by get_frame_register_signed(), mips_unwind_pc(), and mips_unwind_sp().
ULONGEST frame_unwind_register_unsigned (struct frame_info * frame, int regnum)
Definition at line 1095 of file frame.c.
References gdbarch::byte_order, extract_unsigned_integer(), frame_unwind_arch(), frame_unwind_register(), gdbarch_byte_order(), MAX_REGISTER_SIZE, register_size(), and size.
Referenced by aarch64_dwarf2_prev_register(), aarch64_prologue_prev_register(), aarch64_unwind_pc(), aarch64_unwind_sp(), alpha_unwind_pc(), amd64fbsd_sigcontext_addr(), arm_dwarf2_prev_register(), arm_linux_sigreturn_return_addr(), arm_prologue_prev_register(), arm_unwind_pc(), arm_unwind_sp(), avr_unwind_pc(), avr_unwind_sp(), bfin_unwind_pc(), cris_unwind_pc(), cris_unwind_sp(), dwarf2_tailcall_sniffer_first(), frv_unwind_pc(), frv_unwind_sp(), get_frame_register_unsigned(), h8300_unwind_pc(), h8300_unwind_sp(), hppa32_hpux_search_dummy_call_sequence(), hppa_hpux_unwind_pc(), hppa_unwind_pc(), iq2000_unwind_pc(), iq2000_unwind_sp(), lm32_unwind_pc(), lm32_unwind_sp(), m32c_unwind_pc(), m32c_unwind_sp(), m32r_unwind_pc(), m32r_unwind_sp(), m68hc11_unwind_pc(), m68hc11_unwind_sp(), m88k_unwind_pc(), mep_unwind_pc(), mep_unwind_sp(), microblaze_linux_sigtramp_cache(), mn10300_unwind_pc(), mn10300_unwind_sp(), moxie_unwind_pc(), moxie_unwind_sp(), msp430_unwind_pc(), msp430_unwind_sp(), mt_unwind_pc(), mt_unwind_sp(), nios2_unwind_sp(), rl78_unwind_pc(), rl78_unwind_sp(), rs6000_unwind_pc(), rx_unwind_pc(), rx_unwind_sp(), s390_unwind_pc(), s390_unwind_sp(), score_unwind_pc(), score_unwind_sp(), sh64_unwind_pc(), sh64_unwind_sp(), sh_unwind_pc(), sh_unwind_sp(), sparc_unwind_pc(), spu_unwind_pc(), spu_unwind_sp(), tic6x_unwind_sp(), tilegx_unwind_pc(), tilegx_unwind_sp(), v850_unwind_pc(), v850_unwind_sp(), vax_unwind_pc(), xstormy16_unwind_pc(), and xstormy16_unwind_sp().
struct value* frame_unwind_register_value (struct frame_info * frame, int regnum) [read]
Definition at line 1008 of file frame.c.
References fprintf_unfiltered(), frame_debug, frame_unwind_arch(), frame_unwind_find_by_frame(), gdb_assert, gdb_stdlog, frame_info::level, lval_memory, lval_register, paddress(), frame_unwind::prev_register, frame_info::prologue_cache, register_size(), frame_info::unwind, user_reg_map_regnum_to_name(), value_address(), value_contents(), value_lazy(), VALUE_LVAL, value_optimized_out(), and VALUE_REGNUM.
Referenced by frame_register_unwind(), get_frame_register_value(), and s390_unwind_pseudo_register().
int frame_unwinder_is (struct frame_info * fi, const struct frame_unwind * unwinder)
Definition at line 2275 of file frame.c.
References frame_unwind_find_by_frame(), frame_info::prologue_cache, and frame_info::unwind.
Referenced by dwarf2_frame_cfa(), and frame_is_tailcall().
struct frame_info* get_current_frame (void) [read]
Definition at line 1374 of file frame.c.
References _, catch_exceptions(), create_sentinel_frame(), current_frame, current_program_space, current_uiout, error(), get_current_regcache(), get_traceframe_number(), inferior_ptid, is_executing(), is_exited(), null_ptid, ptid_equal(), RETURN_MASK_ERROR, target_has_memory, target_has_registers, target_has_stack, and unwind_to_current_frame().
Referenced by ada_unhandled_exception_name_addr_from_raise(), agent_command_1(), amd64_linux_siginfo_fixup(), arm_linux_copy_svc(), arm_pc_is_thumb(), backtrace_command_1(), block_innermost_frame(), bpfinishpy_init(), bpstat_check_breakpoint_conditions(), call_function_by_hand(), derive_stack_segment(), elf_gnu_ifunc_resolver_return_stop(), elf_gnu_ifunc_resolver_stop(), enable_break(), find_frame_addr_in_frame_chain(), finish_backward(), finish_command_continuation(), flush_ea_cache(), frame_find_by_id(), gdbpy_newest_frame(), get_selected_frame(), glibc_skip_solib_resolver(), handle_inferior_event(), handle_jit_event(), handle_step_into_function(), hppa32_hpux_search_dummy_call_sequence(), jump_command(), m32c_skip_trampoline_code(), maint_agent_printf_command(), maybe_software_singlestep(), mi_cmd_execute(), mi_cmd_stack_info_depth(), mi_cmd_stack_list_args(), mi_cmd_stack_list_frames(), mi_cmd_trace_frame_collected(), mips_linux_skip_resolver(), mips_linux_syscall_next_pc(), normal_stop(), obsd_skip_solib_resolver(), parse_frame_specification_1(), print_it_exception(), proceed(), record_full_resume(), record_full_wait_1(), resolve_msgsend(), resolve_msgsend_stret(), resolve_msgsend_super(), resolve_msgsend_super_stret(), restore_infcall_control_state(), restore_selected_frame(), resume(), return_command(), rs6000_in_function_epilogue_p(), save_bookmark_command(), set_step_frame(), skip_inline_frames(), sol2_skip_solib_resolver(), step_1(), step_once(), tfind_1(), trace_dump_command(), trace_find_line_command(), until_next_command(), update_watchpoint(), watchpoint_check(), and wrap_get_current_frame().
CORE_ADDR get_frame_address_in_block (struct frame_info * this_frame)
Definition at line 2082 of file frame.c.
References get_frame_pc(), get_frame_type(), INLINE_FRAME, frame_info::next, NORMAL_FRAME, and TAILCALL_FRAME.
Referenced by aarch64_scan_prologue(), aarch64_stub_unwind_sniffer(), alpha_mdebug_frame_base_sniffer(), alpha_mdebug_frame_sniffer(), alpha_mdebug_frame_unwind_cache(), arm_exidx_unwind_sniffer(), arm_scan_prologue(), arm_stub_unwind_sniffer(), backtrace_command_1(), disassemble_current_function(), dwarf2_frame_base_sniffer(), dwarf2_frame_cache(), dwarf2_frame_sniffer(), dwarf2_tailcall_sniffer_first(), dwarf_expr_frame_base(), dwarf_expr_frame_pc(), find_frame_funname(), find_frame_sal(), frapy_function(), get_frame_address_in_block_if_available(), get_frame_address_in_block_wrapper(), get_frame_language(), get_prev_frame_1(), hppa_find_unwind_entry_in_block(), hppa_stub_unwind_sniffer(), inline_frame_sniffer(), loclist_read_variable(), microblaze_frame_cache(), microblaze_linux_sigtramp_cache(), mips_insn16_frame_cache(), mips_insn32_frame_cache(), mips_micro_frame_cache(), mips_stub_frame_sniffer(), nios2_stub_frame_sniffer(), s390_stub_frame_sniffer(), sh_stub_unwind_sniffer(), sparc32_dwarf2_struct_return_p(), sparc64obsd_trapframe_sniffer(), and tic6x_stub_unwind_sniffer().
int get_frame_address_in_block_if_available (struct frame_info * this_frame, CORE_ADDR * pc)
Definition at line 2142 of file frame.c.
References gdb_exception::error, get_frame_address_in_block(), NOT_AVAILABLE_ERROR, gdb_exception::reason, RETURN_MASK_ERROR, throw_exception(), and TRY_CATCH.
Referenced by find_frame_funname(), get_frame_block(), get_frame_func_if_available(), and select_frame().
struct address_space* get_frame_address_space (struct frame_info * frame) [read]
Definition at line 2322 of file frame.c.
References frame_info::aspace.
Referenced by alpha_deal_with_atomic_sequence(), alpha_software_single_step(), arm_deal_with_atomic_sequence_raw(), arm_linux_software_single_step(), arm_software_single_step(), cris_software_single_step(), crisv32_single_step_through_delay(), enable_break(), frame_save_as_regcache(), mips_single_step_through_delay(), mips_software_single_step(), nios2_software_single_step(), ppc_deal_with_atomic_sequence(), ppu2spu_sniffer(), rs6000_software_single_step(), sparc_software_single_step(), spu_software_single_step(), thumb_deal_with_atomic_sequence_raw(), thumb_get_next_pc_raw(), and tic6x_software_single_step().
struct gdbarch* get_frame_arch (struct frame_info * this_frame) [read]
Definition at line 2367 of file frame.c.
References frame_unwind_arch(), and frame_info::next.
Referenced by aarch64_dwarf2_prev_register(), aarch64_get_longjmp_target(), aarch64_linux_sigframe_init(), aarch64_make_prologue_cache(), aarch64_prologue_prev_register(), aarch64_prologue_this_id(), aarch64_scan_prologue(), address_of_variable(), alpha_deal_with_atomic_sequence(), alpha_get_longjmp_target(), alpha_heuristic_frame_unwind_cache(), alpha_linux_sigcontext_addr(), alpha_next_pc(), alpha_osf1_sigcontext_addr(), alpha_register_to_value(), alpha_sigtramp_frame_prev_register(), alpha_sigtramp_frame_sniffer(), alpha_sigtramp_frame_this_id(), alpha_sigtramp_frame_unwind_cache(), alpha_software_single_step(), alpha_value_to_register(), alphaobsd_sigcontext_addr(), amd64_darwin_sigcontext_addr(), amd64_epilogue_frame_cache(), amd64_epilogue_frame_sniffer(), amd64_frame_cache_1(), amd64_frame_prev_register(), amd64_get_longjmp_target(), amd64_linux_sigcontext_addr(), amd64_linux_siginfo_fixup(), amd64_linux_sigtramp_start(), amd64_sigtramp_frame_cache(), amd64_sigtramp_frame_sniffer(), amd64_windows_frame_cache(), amd64_windows_frame_decode_epilogue(), amd64_windows_frame_decode_insns(), amd64_windows_frame_prev_register(), amd64_windows_frame_this_id(), amd64_windows_skip_trampoline_code(), amd64obsd_trapframe_cache(), apply_frame_filter(), arm_deal_with_atomic_sequence_raw(), arm_dwarf2_prev_register(), arm_exidx_unwind_sniffer(), arm_frame_is_thumb(), arm_get_longjmp_target(), arm_get_next_pc_raw(), arm_linux_restart_syscall_init(), arm_linux_rt_sigreturn_init(), arm_linux_sigreturn_init(), arm_linux_software_single_step(), arm_linux_syscall_next_pc(), arm_m_exception_cache(), arm_m_exception_prev_register(), arm_make_prologue_cache(), arm_pe_skip_trampoline_code(), arm_prologue_prev_register(), arm_prologue_this_id(), arm_scan_prologue(), arm_software_single_step(), arm_symbian_skip_trampoline_code(), avr_frame_prev_register(), avr_frame_unwind_cache(), bfin_frame_prev_register(), bfin_linux_sigframe_init(), branch_dest(), call0_frame_cache(), call_function_by_hand(), call_site_to_target_addr(), cris_frame_unwind_cache(), cris_scan_prologue(), cris_sigcontext_addr(), cris_sigtramp_frame_unwind_cache(), cris_software_single_step(), crisv32_scan_prologue(), default_read_var_value(), default_value_from_register(), derive_stack_segment(), disassemble_current_function(), dummy_frame_prev_register(), dummy_frame_sniffer(), dwarf2_evaluate_loc_desc_full(), dwarf2_frame_cache(), dwarf2_frame_prev_register(), dwarf2_frame_sniffer(), dwarf2_tailcall_prev_register_first(), dwarf_expr_read_reg(), dwarf_expr_reg_to_entry_parameter(), elf_gnu_ifunc_resolver_return_stop(), elf_gnu_ifunc_resolver_stop(), examine_prologue(), execute_stack_op(), extended_mips16_next_pc(), find_frame_addr_in_frame_chain(), find_step_target(), finish_backward(), finish_forward(), frame_base_find_by_frame(), frame_find_by_id(), frame_info(), frame_info_to_frame_object(), frame_save_as_regcache(), frame_unwind_arch(), frame_unwind_find_by_frame(), frv_frame_unwind_cache(), frv_linux_sigcontext_reg_addr(), frv_linux_sigtramp_frame_cache(), frv_linux_sigtramp_frame_sniffer(), get_current_arch(), get_frame_memory_signed(), get_frame_memory_unsigned(), get_frame_register_bytes(), get_frame_sp(), get_prev_frame_1(), get_register(), gnuv3_skip_trampoline(), h8300_frame_cache(), h8300_frame_prev_register(), handle_inferior_event(), handle_jit_event(), hppa_fallback_frame_cache(), hppa_find_unwind_entry_in_block(), hppa_frame_cache(), hppa_frame_prev_register_helper(), hppa_hpux_sigtramp_frame_unwind_cache(), hppa_hpux_sigtramp_unwind_sniffer(), hppa_hpux_skip_trampoline_code(), hppa_hpux_unwind_adjust_stub(), hppa_linux_sigtramp_frame_sniffer(), hppa_linux_sigtramp_frame_unwind_cache(), hppa_skip_trampoline_code(), hppa_stub_frame_unwind_cache(), hppa_stub_unwind_sniffer(), hppanbsd_sigtramp_cache_init(), i386_darwin_sigcontext_addr(), i386_epilogue_frame_sniffer(), i386_fetch_pointer_argument(), i386_frame_cache_1(), i386_get_longjmp_target(), i386_linux_sigcontext_addr(), i386_pe_skip_trampoline_code(), i386_register_to_value(), i386_sigtramp_frame_cache(), i386_sigtramp_frame_sniffer(), i386_svr4_sigcontext_addr(), i386_value_to_register(), i386bsd_sigcontext_addr(), i386nbsd_sigtramp_cache_init(), i386nto_sigcontext_addr(), i386obsd_trapframe_cache(), i387_print_float_info(), i387_register_to_value(), i387_value_to_register(), ia64_frame_cache(), ia64_frame_prev_register(), ia64_frame_this_id(), ia64_hpux_size_of_register_frame(), ia64_register_to_value(), ia64_sigtramp_frame_cache(), ia64_sigtramp_frame_init_saved_regs(), ia64_sigtramp_frame_prev_register(), ia64_sigtramp_frame_sniffer(), ia64_sigtramp_frame_this_id(), ia64_value_to_register(), info_spu_dma_command(), info_spu_event_command(), info_spu_mailbox_command(), info_spu_proxydma_command(), info_spu_signal_command(), insert_exception_resume_breakpoint(), insert_exception_resume_from_probe(), insert_hp_step_resume_breakpoint_at_frame(), inside_main_func(), iq2000_frame_cache(), jit_dealloc_cache(), jit_frame_sniffer(), jit_unwind_reg_get_impl(), jit_unwind_reg_set_impl(), libunwind_frame_cache(), libunwind_frame_prev_register(), libunwind_frame_sniffer(), libunwind_sigtramp_frame_sniffer(), lm32_frame_cache(), m32c_analyze_frame_prologue(), m32c_frame_base(), m32c_prev_register(), m32c_skip_trampoline_code(), m32r_frame_unwind_cache(), m68hc11_frame_prev_register(), m68hc11_frame_unwind_cache(), m68k_frame_cache(), m68k_get_longjmp_target(), m68k_linux_get_sigtramp_info(), m68k_linux_pc_in_sigtramp(), m68k_linux_sigtramp_frame_cache(), m68k_register_to_value(), m68k_value_to_register(), m88k_frame_cache(), make_visible_with_new_height(), mep_analyze_frame_prologue(), mi_cmd_data_list_register_values(), mi_cmd_trace_frame_collected(), microblaze_frame_cache(), microblaze_linux_sigtramp_cache(), micromips_next_pc(), mips16_next_pc(), mips2_fp_compat(), mips32_next_pc(), mips64_linux_get_longjmp_target(), mips64obsd_sigframe_init(), mips_get_mips16_fn_stub_pc(), mips_insn16_frame_base_sniffer(), mips_insn16_frame_cache(), mips_insn16_frame_sniffer(), mips_insn32_frame_cache(), mips_irix_n32_stack_tramp_frame_init(), mips_irix_n32_tramp_frame_init(), mips_linux_get_longjmp_target(), mips_linux_n32n64_sigframe_init(), mips_linux_o32_sigframe_init(), mips_micro_frame_base_sniffer(), mips_micro_frame_cache(), mips_micro_frame_sniffer(), mips_next_pc(), mips_print_fp_register(), mips_print_register(), mips_read_fp_register_double(), mips_read_fp_register_single(), mips_register_to_value(), mips_skip_mips16_trampoline_code(), mips_skip_pic_trampoline_code(), mips_software_single_step(), mips_stub_frame_cache(), mips_value_to_register(), mipsnbsd_get_longjmp_target(), mn10300_analyze_frame_prologue(), mn10300_frame_prev_register(), moxie_frame_cache(), msp430_analyze_frame_prologue(), msp430_skip_trampoline_code(), mt_frame_unwind_cache(), nios2_frame_unwind_cache(), nios2_get_longjmp_target(), nios2_get_next_pc(), nios2_software_single_step(), nios2_stub_frame_cache(), objc_skip_trampoline(), output_register(), ppc64_standard_linkage1_target(), ppc64_standard_linkage2_target(), ppc64_standard_linkage3_target(), ppc_deal_with_atomic_sequence(), ppc_linux_sigtramp_cache(), ppc_skip_trampoline_code(), ppcfbsd_sigtramp_frame_cache(), ppcfbsd_sigtramp_frame_sniffer(), ppcnbsd_sigtramp_cache_init(), ppcobsd_sigtramp_frame_cache(), ppcobsd_sigtramp_frame_sniffer(), ppu2spu_sniffer(), print_float_info(), print_frame(), print_frame_args(), print_frame_info(), print_frame_nameless_args(), print_gp_register_row(), print_vector_info(), put_frame_register(), put_frame_register_bytes(), py_print_frame(), read_frame_register_unsigned(), read_frame_register_value(), read_insn(), read_pieced_value(), read_reg(), registers_info(), resolve_msgsend(), resolve_msgsend_stret(), resolve_msgsend_super(), resolve_msgsend_super_stret(), return_command(), rs6000_frame_cache(), rs6000_register_to_value(), rs6000_skip_trampoline_code(), rs6000_software_single_step(), rs6000_value_to_register(), rx_frame_prev_register(), s390_backchain_frame_unwind_cache(), s390_frame_prev_register(), s390_prologue_frame_unwind_cache(), s390_sigtramp_frame_unwind_cache(), s390_stub_frame_unwind_cache(), s390_unwind_pseudo_register(), score3_analyze_prologue(), score7_analyze_prologue(), sh64_frame_cache(), sh64_frame_prev_register(), sh_frame_cache(), sh_frame_prev_register(), sh_linux_sigtramp_cache(), sh_make_stub_cache(), sparc32_frame_prev_register(), sparc32_linux_step_trap(), sparc32nbsd_sigcontext_saved_regs(), sparc64_frame_prev_register(), sparc64_linux_step_trap(), sparc64nbsd_sigcontext_saved_regs(), sparc_analyze_control_transfer(), sparc_frame_cache(), sparc_software_single_step(), spu2ppu_sniffer(), spu_frame_unwind_cache(), spu_get_longjmp_target(), spu_objfile_from_frame(), spu_software_single_step(), tailcall_frame_prev_arch(), thumb_deal_with_atomic_sequence_raw(), thumb_get_next_pc_raw(), tic6x_frame_unwind_cache(), tic6x_get_longjmp_target(), tic6x_get_next_pc(), tic6x_linux_rt_sigreturn_init(), tic6x_software_single_step(), tilegx_frame_cache(), tilegx_get_longjmp_target(), trad_frame_alloc_saved_regs(), tramp_frame_start(), tui_get_function_from_frame(), tui_register_format(), tui_show_frame_info(), tui_show_register_group(), until_break_command(), update_watchpoint(), v850_frame_cache(), value_assign(), value_fetch_lazy(), value_from_register(), value_of_builtin_frame_fp_reg(), value_of_builtin_frame_pc_reg(), value_of_builtin_frame_ps_reg(), value_of_builtin_frame_sp_reg(), value_of_register(), value_of_register_lazy(), value_of_user_reg(), watchpoint_check(), write_pieced_value(), xstormy16_frame_cache(), xstormy16_skip_trampoline_code(), xtensa_frame_cache(), xtensa_frame_prev_register(), and xtensa_window_interrupt_frame_cache().
CORE_ADDR get_frame_args_address (struct frame_info * fi)
Definition at line 2257 of file frame.c.
References frame_info::base, frame_info::base_cache, frame_base_find_by_frame(), get_frame_type(), NORMAL_FRAME, frame_info::prologue_cache, frame_base::this_args, frame_base::unwind, and frame_info::unwind.
Referenced by default_read_var_value(), frame_info(), and print_frame_nameless_args().
CORE_ADDR get_frame_base (struct frame_info * fi)
Definition at line 2220 of file frame.c.
References get_frame_id(), and frame_id::stack_addr.
Referenced by alphanbsd_sigcontext_addr(), branch_dest(), default_frame_base_address(), derive_stack_segment(), dwarf2_frame_cfa(), frame_info(), and gdb_selected_frame().
CORE_ADDR get_frame_base_address (struct frame_info * fi)
Definition at line 2228 of file frame.c.
References frame_info::base, frame_info::base_cache, frame_base_find_by_frame(), get_frame_type(), NORMAL_FRAME, frame_info::prologue_cache, frame_base::this_base, frame_base::unwind, and frame_info::unwind.
Referenced by find_frame_addr_in_frame_chain(), value_of_builtin_frame_fp_reg(), and vax_frame_num_args().
CORE_ADDR get_frame_func (struct frame_info * this_frame)
Definition at line 837 of file frame.c.
References _, get_frame_func_if_available(), NOT_AVAILABLE_ERROR, and throw_error().
Referenced by aarch64_prologue_this_id(), alpha_mdebug_frame_this_id(), alpha_sigtramp_frame_this_id(), amd64_frame_cache_1(), amd64obsd_trapframe_cache(), arm_prologue_this_id(), avr_frame_this_id(), avr_frame_unwind_cache(), bfin_frame_cache(), cris_frame_this_id(), cris_frame_unwind_cache(), dwarf2_frame_this_id(), dwarf_expr_reg_to_entry_parameter(), frv_frame_this_id(), frv_frame_unwind_cache(), h8300_frame_cache(), hppa_fallback_frame_cache(), hppa_fallback_frame_this_id(), hppa_frame_cache(), hppa_stub_frame_this_id(), i386_epilogue_frame_cache(), i386_frame_cache_1(), i386obsd_trapframe_cache(), ia64_frame_cache(), inside_entry_func(), inside_main_func(), libunwind_frame_cache(), lm32_frame_cache(), m32c_analyze_frame_prologue(), m32c_this_id(), m32r_frame_this_id(), m32r_frame_unwind_cache(), m32r_linux_sigtramp_frame_cache(), m68hc11_frame_this_id(), m68hc11_frame_unwind_cache(), m68k_frame_cache(), m88k_frame_cache(), mep_analyze_frame_prologue(), mep_frame_this_id(), microblaze_frame_cache(), mips_insn16_frame_this_id(), mips_insn32_frame_this_id(), mips_micro_frame_this_id(), mn10300_analyze_frame_prologue(), mn10300_frame_this_id(), moxie_frame_cache(), msp430_analyze_frame_prologue(), msp430_this_id(), mt_frame_this_id(), mt_frame_unwind_cache(), nios2_frame_unwind_cache(), rl78_analyze_frame_prologue(), rl78_this_id(), rs6000_frame_cache(), rs6000_frame_this_id(), rx_analyze_frame_prologue(), rx_frame_this_id(), s390_prologue_frame_unwind_cache(), score_prologue_this_id(), sh64_frame_cache(), sh_frame_cache(), sparc_frame_cache(), spu_frame_unwind_cache(), tic6x_frame_unwind_cache(), tilegx_frame_cache(), v850_frame_cache(), vax_frame_this_id(), xstormy16_frame_cache(), xtensa_frame_cache(), and xtensa_window_interrupt_frame_cache().
int get_frame_func_if_available (struct frame_info * this_frame, CORE_ADDR * pc)
Definition at line 793 of file frame.c.
References frame_info::addr, fprintf_unfiltered(), frame_debug, gdb_stdlog, get_frame_address_in_block_if_available(), get_pc_function_start(), hex_string(), frame_info::level, frame_info::next, frame_info::p, and frame_info::prev_func.
Referenced by dwarf2_frame_cache(), get_frame_func(), and loclist_read_variable_at_entry().
struct frame_id get_frame_id (struct frame_info * fi) [read]
Definition at line 396 of file frame.c.
References fprint_frame_id(), fprintf_unfiltered(), frame_debug, frame_id_p(), frame_stash_add(), frame_unwind_find_by_frame(), gdb_assert, gdb_stdlog, null_frame_id, and outer_frame_id.
Referenced by alpha_osf1_sigcontext_addr(), arm_linux_copy_svc(), backtrace_command_1(), bpfinishpy_init(), default_value_from_register(), dwarf2_evaluate_loc_desc_full(), finish_forward(), frame_find_by_id(), frame_info_to_frame_object(), frame_pop(), frame_unwind_caller_id(), get_frame_base(), get_prev_frame_1(), get_stack_frame_id(), handle_inferior_event(), inline_frame_this_id(), make_cleanup_restore_current_thread(), normal_stop(), parse_frame_specification_1(), print_frame_arg_vars(), print_frame_local_vars(), restore_selected_frame(), save_infcall_control_state(), sentinel_frame_prev_register(), set_step_info(), step_1(), stepped_in_from(), tailcall_frame_this_id(), tfind_1(), until_next_command(), update_watchpoint(), value_assign(), value_from_register(), value_of_register_lazy(), varobj_create(), and watch_command_1().
CORE_ADDR get_frame_locals_address (struct frame_info * fi)
Definition at line 2242 of file frame.c.
References frame_info::base, frame_info::base_cache, frame_base_find_by_frame(), get_frame_type(), NORMAL_FRAME, frame_info::prologue_cache, frame_base::this_locals, frame_base::unwind, and frame_info::unwind.
Referenced by default_read_var_value(), and frame_info().
void get_frame_memory (struct frame_info * this_frame, CORE_ADDR addr, gdb_byte * buf, int len)
Definition at line 2330 of file frame.c.
References read_memory().
LONGEST get_frame_memory_signed (struct frame_info * this_frame, CORE_ADDR addr, int len)
Definition at line 2337 of file frame.c.
References gdbarch::byte_order, gdbarch_byte_order(), get_frame_arch(), and read_memory_integer().
ULONGEST get_frame_memory_unsigned (struct frame_info * this_frame, CORE_ADDR addr, int len)
Definition at line 2347 of file frame.c.
References gdbarch::byte_order, gdbarch_byte_order(), get_frame_arch(), and read_memory_unsigned_integer().
Referenced by alpha_sigtramp_frame_this_id(), alphaobsd_sigcontext_addr(), am33_linux_sigframe_cache_init(), amd64_sol2_mcontext_addr(), arm_exidx_fill_cache(), arm_linux_restart_syscall_init(), i386_sol2_mcontext_addr(), m32r_frame_unwind_cache(), m68kobsd_sigtramp_cache_init(), mt_frame_unwind_cache(), sparc32_frame_prev_register(), sparc32_linux_sigframe_init(), sparc32_sol2_sigtramp_frame_cache(), sparc32nbsd_sigcontext_saved_regs(), sparc64_frame_prev_register(), sparc64_linux_sigframe_init(), sparc64_sol2_sigtramp_frame_cache(), sparc64fbsd_sigtramp_frame_cache(), sparc64nbsd_sigcontext_saved_regs(), thumb_get_next_pc_raw(), tilegx_linux_sigframe_init(), vax_frame_cache(), vax_frame_num_args(), and vaxobsd_sigtramp_frame_cache().
CORE_ADDR get_frame_pc (struct frame_info * frame)
Definition at line 2051 of file frame.c.
References frame_unwind_pc(), gdb_assert, and frame_info::next.
Referenced by aarch64_dummy_id(), aarch64_prologue_this_id(), aarch64_scan_prologue(), aarch64_stub_this_id(), aarch64_stub_unwind_sniffer(), agent_command_1(), alpha_deal_with_atomic_sequence(), alpha_dummy_id(), alpha_heuristic_frame_unwind_cache(), alpha_linux_sigcontext_addr(), alpha_sigtramp_frame_sniffer(), alpha_sigtramp_frame_this_id(), alpha_software_single_step(), alphaobsd_sigcontext_addr(), amd64_dummy_id(), amd64_epilogue_frame_cache(), amd64_epilogue_frame_sniffer(), amd64_frame_cache_1(), amd64_linux_sigtramp_p(), amd64_linux_sigtramp_start(), amd64_sigtramp_frame_sniffer(), amd64_sigtramp_frame_this_id(), amd64_sol2_sigtramp_p(), amd64_windows_frame_cache(), amd64nbsd_sigtramp_p(), amd64obsd_sigcontext_addr(), amd64obsd_sigtramp_p(), amd64obsd_trapframe_sniffer(), arm_deal_with_atomic_sequence_raw(), arm_dummy_id(), arm_exidx_unwind_sniffer(), arm_linux_copy_svc(), arm_linux_software_single_step(), arm_linux_syscall_next_pc(), arm_m_exception_this_id(), arm_m_exception_unwind_sniffer(), arm_prologue_this_id(), arm_scan_prologue(), arm_software_single_step(), arm_stub_this_id(), arm_stub_unwind_sniffer(), avr_dummy_id(), avr_frame_unwind_cache(), bfin_dummy_id(), bfin_frame_cache(), bfin_linux_sigframe_init(), bpfinishpy_init(), check_exception_resume(), check_scope(), compute_probe_arg(), cris_dummy_id(), cris_rt_sigtramp_start(), cris_scan_prologue(), cris_sigtramp_frame_this_id(), cris_sigtramp_start(), dwarf2_fetch_die_loc_cu_off(), dwarf_expr_reg_to_entry_parameter(), elf_gnu_ifunc_resolver_stop(), fetch_probe_arguments(), find_frame_sal(), finish_backward(), finish_command(), finish_forward(), frame_info(), frame_show_address(), frapy_pc(), frv_analyze_prologue(), frv_dummy_id(), frv_linux_sigcontext_reg_addr(), frv_linux_sigtramp_frame_cache(), frv_linux_sigtramp_frame_sniffer(), func_command(), gdb_get_blocks(), gdb_loc(), get_frame_address_in_block(), get_frame_name(), h8300_dummy_id(), h8300_frame_cache(), hppa_dummy_id(), hppa_fallback_frame_cache(), hppa_frame_cache(), hppa_frame_this_id(), hppa_hpux_sigtramp_frame_this_id(), hppa_hpux_sigtramp_unwind_sniffer(), hppa_linux_sigtramp_frame_sniffer(), hppa_linux_sigtramp_frame_this_id(), hppa_linux_sigtramp_frame_unwind_cache(), hppa_stub_frame_unwind_cache(), i386_dummy_id(), i386_epilogue_frame_sniffer(), i386_frame_cache_1(), i386_linux_dwarf_signal_frame_p(), i386_linux_rt_sigtramp_start(), i386_linux_sigcontext_addr(), i386_linux_sigtramp_p(), i386_linux_sigtramp_start(), i386_sigtramp_frame_sniffer(), i386_sigtramp_frame_this_id(), i386_sigtramp_p(), i386_sol2_sigtramp_p(), i386_stack_tramp_frame_sniffer(), i386_svr4_sigtramp_p(), i386nto_sigtramp_p(), i386obsd_sigtramp_p(), i386obsd_trapframe_sniffer(), ia64_dummy_id(), ia64_frame_cache(), ia64_hpux_dummy_id(), ia64_sigtramp_frame_sniffer(), ia64_sigtramp_frame_this_id(), insert_hp_step_resume_breakpoint_at_frame(), iq2000_dummy_id(), iq2000_frame_cache(), libunwind_frame_cache(), lm32_dummy_id(), lm32_frame_cache(), m32c_analyze_frame_prologue(), m32c_dummy_id(), m32r_dummy_id(), m32r_frame_unwind_cache(), m32r_linux_sigtramp_frame_cache(), m32r_linux_sigtramp_frame_sniffer(), m68hc11_dummy_id(), m68hc11_frame_unwind_cache(), m68k_dummy_id(), m68k_frame_cache(), m68k_linux_pc_in_sigtramp(), m68k_linux_sigtramp_frame_cache(), m88k_dummy_id(), m88k_frame_cache(), maint_agent_printf_command(), make_visible_with_new_height(), mep_analyze_frame_prologue(), mep_dummy_id(), mips_dummy_id(), mips_insn16_frame_base_sniffer(), mips_insn16_frame_sniffer(), mips_insn32_frame_base_sniffer(), mips_insn32_frame_sniffer(), mips_linux_syscall_next_pc(), mips_micro_frame_base_sniffer(), mips_micro_frame_sniffer(), mips_single_step_through_delay(), mips_software_single_step(), mips_stub_frame_cache(), mips_stub_frame_sniffer(), mn10300_analyze_frame_prologue(), moxie_dummy_id(), moxie_frame_cache(), msp430_analyze_frame_prologue(), msp430_dummy_id(), mt_dummy_id(), mt_frame_unwind_cache(), nios2_dummy_id(), nios2_frame_unwind_cache(), nios2_linux_syscall_next_pc(), nios2_software_single_step(), nios2_stub_frame_cache(), nios2_stub_frame_sniffer(), per_cu_dwarf_call(), ppc_deal_with_atomic_sequence(), ppc_linux_sigtramp_cache(), ppcfbsd_sigtramp_frame_cache(), ppcfbsd_sigtramp_frame_sniffer(), ppcobsd_sigtramp_frame_cache(), ppcobsd_sigtramp_frame_sniffer(), ppu2spu_sniffer(), print_frame(), print_frame_info(), probe_safe_evaluate_at_pc(), rl78_analyze_frame_prologue(), rl78_dummy_id(), rs6000_dummy_id(), rs6000_frame_cache(), rs6000_software_single_step(), rx_analyze_frame_prologue(), rx_dummy_id(), s390_backchain_frame_unwind_cache(), s390_dummy_id(), s390_prologue_frame_unwind_cache(), s390_sigtramp_frame_sniffer(), s390_sigtramp_frame_this_id(), s390_sigtramp_frame_unwind_cache(), s390_stub_frame_sniffer(), s390_stub_frame_this_id(), score_dummy_id(), score_make_prologue_cache(), sh64_dummy_id(), sh64_frame_cache(), sh64_print_registers_info(), sh_dummy_id(), sh_frame_cache(), sh_stub_this_id(), skip_inline_frames(), sparc32_sol2_sigtramp_frame_sniffer(), sparc32nbsd_sigcontext_frame_sniffer(), sparc32obsd_sigtramp_frame_cache(), sparc32obsd_sigtramp_frame_sniffer(), sparc64_sol2_sigtramp_frame_sniffer(), sparc64fbsd_sigtramp_frame_sniffer(), sparc64nbsd_sigtramp_frame_sniffer(), sparc64obsd_frame_cache(), sparc64obsd_sigtramp_frame_sniffer(), sparc_dummy_id(), sparc_frame_cache(), spu2ppu_sniffer(), spu_frame_unwind_cache(), spu_software_single_step(), step_once(), tailcall_frame_this_id(), thumb_deal_with_atomic_sequence_raw(), tic6x_dummy_id(), tic6x_frame_unwind_cache(), tic6x_linux_syscall_next_pc(), tic6x_software_single_step(), tic6x_stub_this_id(), tilegx_frame_cache(), tilegx_unwind_dummy_id(), trace_find_line_command(), tramp_frame_sniffer(), tui_get_function_from_frame(), tui_horizontal_source_scroll(), tui_show_frame_info(), tui_vertical_source_scroll(), until_next_command(), update_watchpoint(), v850_dummy_id(), v850_frame_cache(), value_of_builtin_frame_pc_reg(), varobj_create(), vax_dummy_id(), vaxobsd_sigtramp_frame_cache(), vaxobsd_sigtramp_sniffer(), watchpoint_check(), xstormy16_dummy_id(), xstormy16_frame_cache(), and xtensa_dummy_id().
int get_frame_pc_if_available (struct frame_info * frame, CORE_ADDR * pc)
Definition at line 2058 of file frame.c.
References gdb_exception::error, frame_unwind_pc(), gdb_assert, frame_info::next, NOT_AVAILABLE_ERROR, gdb_exception::reason, RETURN_MASK_ERROR, throw_exception(), and TRY_CATCH.
Referenced by bpfinishpy_init(), default_macro_scope(), find_frame_sal(), frame_info(), get_prev_frame(), pc_prefix(), print_frame(), print_frame_arg_vars(), print_frame_info(), print_frame_local_vars(), set_traceframe_context(), tui_selected_frame_level_changed_hook(), and tui_show_frame_info().
struct program_space* get_frame_program_space (struct frame_info * frame) [read]
Definition at line 2305 of file frame.c.
References frame_info::pspace.
Referenced by find_frame_sal(), finish_backward(), get_frame_name(), handle_inferior_event(), handle_step_into_function(), insert_hp_step_resume_breakpoint_at_frame(), print_frame(), save_bookmark_command(), and update_watchpoint().
void get_frame_register (struct frame_info * frame, int regnum, gdb_byte * buf)
Definition at line 1001 of file frame.c.
References frame_unwind_register(), and frame_info::next.
Referenced by amd64_darwin_sigcontext_addr(), amd64_epilogue_frame_cache(), amd64_frame_cache_1(), amd64_get_longjmp_target(), amd64_linux_sigcontext_addr(), amd64_sigtramp_frame_cache(), amd64_windows_frame_cache(), amd64_windows_frame_decode_insns(), cris_sigcontext_addr(), cris_sigtramp_frame_unwind_cache(), examine_prologue(), frv_linux_sigcontext_reg_addr(), frv_linux_sigtramp_frame_cache(), i386_darwin_sigcontext_addr(), i386_frame_cache_1(), i386_get_longjmp_target(), i386_linux_sigcontext_addr(), i386_sigtramp_frame_cache(), i386_svr4_sigcontext_addr(), i386bsd_sigcontext_addr(), i386nto_sigcontext_addr(), ia64_dummy_id(), ia64_frame_cache(), ia64_frame_prev_register(), ia64_sigtramp_frame_cache(), m68k_frame_cache(), m68k_linux_sigtramp_frame_cache(), mips_register_to_value(), read_reg(), and spu_frame_unwind_cache().
int get_frame_register_bytes (struct frame_info * frame, int regnum, CORE_ADDR offset, int len, gdb_byte * myaddr, int * optimizedp, int * unavailablep)
Definition at line 1187 of file frame.c.
References _, error(), frame_register(), gdbarch_num_pseudo_regs(), gdbarch_num_regs(), get_frame_arch(), len, MAX_REGISTER_SIZE, memcpy(), offset, and register_size().
Referenced by alpha_register_to_value(), i386_register_to_value(), i387_register_to_value(), ia64_register_to_value(), m68k_register_to_value(), mips_register_to_value(), read_pieced_value(), rs6000_register_to_value(), spu_get_longjmp_target(), spu_software_single_step(), value_assign(), and write_pieced_value().
LONGEST get_frame_register_signed (struct frame_info * frame, int regnum)
Definition at line 1089 of file frame.c.
References frame_unwind_register_signed(), and frame_info::next.
Referenced by alpha_next_pc(), armobsd_sigframe_init(), extended_mips16_next_pc(), h8300_print_register(), m68hc11_print_register(), micromips_next_pc(), micromips_scan_prologue(), mips16_scan_prologue(), mips32_next_pc(), mips32_scan_prologue(), mips64obsd_sigframe_init(), mips_dummy_id(), mips_irix_n32_stack_tramp_frame_init(), mips_irix_n32_tramp_frame_init(), mips_skip_mips16_trampoline_code(), mips_stub_frame_cache(), nios2_get_next_pc(), tic6x_condition_true(), and tic6x_get_next_pc().
ULONGEST get_frame_register_unsigned (struct frame_info * frame, int regnum)
Definition at line 1107 of file frame.c.
References frame_unwind_register_unsigned(), and frame_info::next.
Referenced by aarch64_dummy_id(), aarch64_get_longjmp_target(), aarch64_linux_sigframe_init(), aarch64_make_prologue_cache(), aarch64_make_stub_cache(), aarch64_scan_prologue(), alpha_dummy_id(), alpha_get_longjmp_target(), alpha_heuristic_frame_unwind_cache(), alpha_linux_sigcontext_addr(), alpha_mdebug_frame_unwind_cache(), alpha_next_pc(), alphafbsd_sigcontext_addr(), alphaobsd_sigcontext_addr(), am33_linux_sigframe_cache_init(), amd64_dummy_id(), amd64_sol2_mcontext_addr(), amd64nbsd_mcontext_addr(), amd64obsd_sigcontext_addr(), amd64obsd_trapframe_cache(), amd64obsd_trapframe_sniffer(), arm_dummy_id(), arm_dwarf2_prev_register(), arm_exidx_fill_cache(), arm_frame_is_thumb(), arm_get_longjmp_target(), arm_get_next_pc_raw(), arm_linux_restart_syscall_init(), arm_linux_rt_sigreturn_init(), arm_linux_sigreturn_init(), arm_linux_sigtramp_cache(), arm_linux_software_single_step(), arm_linux_syscall_next_pc(), arm_m_exception_cache(), arm_make_prologue_cache(), arm_make_stub_cache(), arm_print_float_info(), arm_prologue_prev_register(), arm_scan_prologue(), arm_skip_stub(), avr_dummy_id(), avr_frame_unwind_cache(), bfin_dummy_id(), bfin_frame_cache(), branch_dest(), call0_frame_cache(), cris_dummy_id(), cris_scan_prologue(), crisv32_scan_prologue(), crisv32_single_step_through_delay(), dwarf2_frame_prev_register(), find_step_target(), frv_analyze_prologue(), frv_dummy_id(), get_frame_sp(), h8300_dummy_id(), h8300_frame_cache(), hppa_dummy_id(), hppa_fallback_frame_cache(), hppa_fetch_pointer_argument(), hppa_hpux_sigtramp_frame_unwind_cache(), hppa_hpux_skip_trampoline_code(), hppa_linux_sigtramp_frame_unwind_cache(), hppa_skip_trampoline_code(), hppa_stub_frame_unwind_cache(), hppanbsd_sigtramp_cache_init(), i386_dummy_id(), i386_epilogue_frame_cache(), i386_fetch_pointer_argument(), i386_frame_prev_register(), i386_sol2_mcontext_addr(), i386nbsd_sigtramp_cache_init(), i386obsd_trapframe_cache(), i386obsd_trapframe_sniffer(), ia64_hpux_dummy_id(), info_spu_dma_command(), info_spu_event_command(), info_spu_mailbox_command(), info_spu_proxydma_command(), info_spu_signal_command(), iq2000_dummy_id(), iq2000_frame_cache(), lm32_dummy_id(), lm32_frame_cache(), m32c_dummy_id(), m32c_frame_base(), m32r_dummy_id(), m32r_frame_unwind_cache(), m32r_linux_sigtramp_frame_cache(), m68hc11_dummy_id(), m68hc11_frame_unwind_cache(), m68hc11_print_register(), m68k_dummy_id(), m68k_get_longjmp_target(), m68k_linux_get_sigtramp_info(), m68kobsd_sigtramp_cache_init(), m88k_dummy_id(), m88k_frame_cache(), mep_dummy_id(), mep_frame_base(), micromips_bc1_pc(), micromips_next_pc(), mips2_fp_compat(), mips32_bc1_pc(), mips32_next_pc(), mips64_linux_get_longjmp_target(), mips_linux_get_longjmp_target(), mips_linux_syscall_next_pc(), mipsnbsd_get_longjmp_target(), mn10300_dummy_id(), mn10300_frame_base(), moxie_dummy_id(), moxie_frame_cache(), msp430_dummy_id(), msp430_frame_base(), msp430_skip_trampoline_code(), mt_dummy_id(), mt_frame_unwind_cache(), nios2_analyze_prologue(), nios2_dummy_id(), nios2_get_longjmp_target(), nios2_get_next_pc(), nios2_linux_syscall_next_pc(), nios2_stub_frame_cache(), ppc64_standard_linkage1_target(), ppc64_standard_linkage2_target(), ppc64_standard_linkage3_target(), ppc_linux_sigtramp_cache(), ppc_skip_trampoline_code(), ppcfbsd_sigtramp_frame_cache(), ppcnbsd_sigtramp_cache_init(), ppcobsd_sigtramp_frame_cache(), rl78_dummy_id(), rl78_frame_base(), rs6000_dummy_id(), rs6000_fetch_pointer_argument(), rs6000_frame_cache(), rs6000_in_function_epilogue_p(), rs6000_skip_trampoline_code(), rx_dummy_id(), rx_frame_base(), s390_backchain_frame_unwind_cache(), s390_dummy_id(), s390_prologue_frame_unwind_cache(), s390_sigtramp_frame_unwind_cache(), s390_stub_frame_unwind_cache(), score3_analyze_prologue(), score7_analyze_prologue(), score_dummy_id(), sh64_do_cr_c_register_info(), sh64_do_pseudo_register(), sh64_dummy_id(), sh64_frame_cache(), sh_dummy_id(), sh_frame_cache(), sh_linux_sigtramp_cache(), sh_make_stub_cache(), shifted_reg_val(), sparc32_frame_cache(), sparc32_frame_prev_register(), sparc32_linux_sigframe_init(), sparc32_linux_step_trap(), sparc32_sol2_sigtramp_frame_cache(), sparc32nbsd_sigcontext_frame_cache(), sparc32nbsd_sigcontext_saved_regs(), sparc32obsd_sigtramp_frame_cache(), sparc64_frame_prev_register(), sparc64_linux_sigframe_init(), sparc64_linux_step_trap(), sparc64_sol2_sigtramp_frame_cache(), sparc64fbsd_sigtramp_frame_cache(), sparc64nbsd_sigcontext_frame_cache(), sparc64obsd_frame_cache(), sparc64obsd_trapframe_cache(), sparc64obsd_trapframe_sniffer(), sparc_dummy_id(), sparc_frame_cache(), sparc_software_single_step(), sparcnbsd_step_trap(), spu_dummy_id(), spu_frame_unwind_cache(), spu_software_single_step(), thumb_deal_with_atomic_sequence_raw(), thumb_get_next_pc_raw(), tic6x_analyze_prologue(), tic6x_dummy_id(), tic6x_get_longjmp_target(), tic6x_get_next_pc(), tic6x_linux_rt_sigreturn_init(), tic6x_linux_syscall_next_pc(), tic6x_make_stub_cache(), tilegx_frame_cache(), tilegx_get_longjmp_target(), tilegx_linux_sigframe_init(), tilegx_unwind_dummy_id(), v850_dummy_id(), v850_frame_cache(), vax_dummy_id(), vax_frame_args_address(), vax_frame_cache(), vax_frame_num_args(), vaxobsd_sigtramp_frame_cache(), xstormy16_dummy_id(), xstormy16_frame_cache(), xtensa_dummy_id(), xtensa_frame_cache(), and xtensa_window_interrupt_frame_cache().
struct value* get_frame_register_value (struct frame_info * frame, int regnum) [read]
Definition at line 1071 of file frame.c.
References frame_unwind_register_value(), and frame_info::next.
Referenced by get_register(), i387_print_float_info(), inline_frame_prev_register(), mep_frame_prev_register(), mips_print_register(), read_frame_register_unsigned(), read_frame_register_value(), register_changed_p(), and value_fetch_lazy().
CORE_ADDR get_frame_sp (struct frame_info * this_frame)
Definition at line 2409 of file frame.c.
References _, gdbarch_sp_regnum(), gdbarch_unwind_sp(), gdbarch_unwind_sp_p(), get_frame_arch(), get_frame_register_unsigned(), internal_error(), and frame_info::next.
Referenced by bfin_linux_sigframe_init(), call_function_by_hand(), derive_stack_segment(), m32c_skip_trampoline_code(), mips_linux_n32n64_sigframe_init(), mips_linux_o32_sigframe_init(), ppu2spu_sniffer(), and spu2ppu_sniffer().
enum frame_type get_frame_type (struct frame_info * frame)
Definition at line 2295 of file frame.c.
References frame_unwind_find_by_frame(), frame_info::prologue_cache, frame_unwind::type, and frame_info::unwind.
Referenced by arm_exidx_unwind_sniffer(), arm_linux_sigreturn_return_addr(), bpfinishpy_init(), dwarf2_frame_cfa(), dwarf_expr_reg_to_entry_parameter(), finish_command(), frame_find_by_id(), frame_info(), frame_inlined_callees(), frame_pop(), frame_show_address(), frapy_type(), get_frame_address_in_block(), get_frame_args_address(), get_frame_base_address(), get_frame_locals_address(), get_frame_name(), get_prev_frame(), get_prev_frame_1(), handle_inferior_event(), inline_frame_sniffer(), normal_stop(), ppu2spu_sniffer(), print_frame_info(), return_command(), s390_prologue_frame_unwind_cache(), skip_artificial_frames(), and stepped_in_from().
enum unwind_stop_reason get_frame_unwind_stop_reason (struct frame_info * frame)
Definition at line 2430 of file frame.c.
References frame_info::prev_p, and frame_info::stop_reason.
Referenced by backtrace_command_1(), dwarf2_frame_cfa(), frame_info(), frame_info_to_frame_object(), and frapy_unwind_stop_reason().
struct frame_info* get_next_frame (struct frame_info * this_frame) [read]
Definition at line 1583 of file frame.c.
References frame_info::level, and frame_info::next.
Referenced by alpha_osf1_sigcontext_addr(), alphanbsd_sigcontext_addr(), arm_exidx_unwind_sniffer(), cache_find(), find_frame_sal(), find_relative_frame(), frame_info(), frame_info_to_frame_object(), frame_inlined_callees(), frame_register_unwind_location(), frame_show_address(), frapy_newer(), get_prev_frame(), get_prev_frame_1(), inline_frame_sniffer(), ppu2spu_sniffer(), s390_prologue_frame_unwind_cache(), spu2ppu_sniffer(), tailcall_frame_sniffer(), tailcall_frame_this_id(), and wrap_get_next_frame().
struct frame_info* get_prev_frame (struct frame_info * this_frame) [read]
Definition at line 1956 of file frame.c.
References backtrace_limit, backtrace_past_entry, backtrace_past_main, frame_debug_got_null_frame(), gdb_assert, get_frame_pc_if_available(), get_frame_type(), get_next_frame(), get_prev_frame_1(), INLINE_FRAME, inside_entry_func(), inside_main_func(), frame_info::level, and NORMAL_FRAME.
Referenced by ada_find_printable_frame(), ada_unhandled_exception_name_addr_from_raise(), arm_linux_copy_svc(), backtrace_command_1(), block_innermost_frame(), bpfinishpy_init(), derive_stack_segment(), dwarf2_frame_cfa(), dwarf_expr_push_dwarf_reg_entry_value(), dwarf_expr_reg_to_entry_parameter(), elf_gnu_ifunc_resolver_stop(), find_frame_addr_in_frame_chain(), find_relative_frame(), finish_command(), frame_find_by_id(), frame_info(), frame_info_to_frame_object(), frame_object_to_frame_info(), frame_pop(), frapy_older(), inline_frame_this_id(), mi_cmd_stack_info_depth(), mi_cmd_stack_list_args(), mi_cmd_stack_list_frames(), parse_frame_specification_1(), skip_artificial_frames(), stepped_in_from(), unwind_to_current_frame(), value_of_dwarf_reg_entry(), and wrap_get_prev_frame().
static struct frame_info * get_prev_frame_1 (struct frame_info * this_frame) [static, read]
Definition at line 1665 of file frame.c.
References fprint_frame(), fprintf_unfiltered(), frame_debug, frame_id_eq(), frame_id_inner(), frame_register_unwind_location(), frame_unwind_find_by_frame(), gdb_assert, gdb_stdlog, gdbarch_pc_regnum(), get_frame_address_in_block(), get_frame_arch(), get_frame_id(), get_frame_type(), get_next_frame(), get_prev_frame_raw(), INLINE_FRAME, frame_info::level, lookup_minimal_symbol_by_pc(), lval_memory, lval_register, bound_minimal_symbol::minsym, frame_info::next, NORMAL_FRAME, frame_info::prev, frame_info::prev_p, frame_info::prologue_cache, frame_info::stop_reason, frame_unwind::stop_reason, SYMBOL_LINKAGE_NAME, frame_unwind::type, and frame_info::unwind.
Referenced by frame_pop(), frame_unwind_caller_id(), and get_prev_frame().
static struct frame_info * get_prev_frame_raw (struct frame_info * this_frame) [static, read]
Definition at line 1840 of file frame.c.
References frame_info::aspace, fprint_frame(), fprintf_unfiltered(), frame_debug, FRAME_OBSTACK_ZALLOC, gdb_stdlog, frame_info::level, frame_info::next, frame_info::prev, and frame_info::pspace.
Referenced by get_prev_frame_1().
struct frame_info* get_selected_frame (const char * message) [read]
Definition at line 1448 of file frame.c.
References error(), gdb_assert, get_current_frame(), has_stack_frames(), select_frame(), and selected_frame.
Referenced by args_info(), bsd_kvm_open(), bsd_kvm_pcb_cmd(), bsd_kvm_proc_cmd(), compute_probe_arg(), core_open(), current_frame_command(), deprecated_safe_get_selected_frame(), disassemble_current_function(), do_captured_thread_select(), down_command(), down_silently_base(), evaluate_subexp_standard(), fetch_probe_arguments(), finish_backward(), finish_command(), float_info(), frame_command(), func_command(), gdb_block_vars(), gdb_get_blocks(), gdb_get_vars_command(), gdb_loc(), gdb_selected_block(), gdb_selected_frame(), gdbpy_lookup_symbol(), gdbpy_selected_frame(), get_current_arch(), get_register(), get_selected_block(), indirect_pieced_value(), inferior_command(), info_common_command(), info_spu_dma_command(), info_spu_event_command(), info_spu_mailbox_command(), info_spu_proxydma_command(), info_spu_signal_command(), kill_command(), linux_fork_context(), locals_info(), mi_cmd_data_list_changed_registers(), mi_cmd_data_list_register_values(), mi_cmd_exec_return(), mi_cmd_stack_info_frame(), mi_cmd_stack_list_locals(), mi_cmd_stack_list_variables(), mi_cmd_trace_find(), mi_cmd_trace_frame_collected(), mi_on_normal_stop(), normal_stop(), parse_frame_specification_1(), pc_prefix(), print_thread_info(), record_full_goto_entry(), record_full_restore(), register_changed_p(), registers_info(), restore_selected_frame(), return_command(), save_infcall_control_state(), task_command_1(), tfind_1(), tui_horizontal_source_scroll(), tui_print_frame_info_listing_hook(), tui_register_changed_hook(), tui_selected_frame_level_changed_hook(), tui_show_registers(), tui_vertical_source_scroll(), until_break_command(), up_command(), up_silently_base(), update_watchpoint(), value_of_this(), value_of_variable(), varobj_create(), and vector_info().
struct frame_info* get_selected_frame_if_set (void) [read]
Definition at line 1467 of file frame.c.
References selected_frame.
Referenced by block_innermost_frame(), and make_cleanup_restore_current_thread().
struct frame_id get_stack_frame_id (struct frame_info * next_frame) [read]
Definition at line 428 of file frame.c.
References get_frame_id(), and skip_artificial_frames().
Referenced by bpstat_check_breakpoint_conditions(), elf_gnu_ifunc_resolver_stop(), finish_forward(), handle_inferior_event(), insert_hp_step_resume_breakpoint_at_frame(), set_step_info(), and until_break_command().
int has_stack_frames (void)
Definition at line 1419 of file frame.c.
References get_traceframe_number(), inferior_ptid, is_executing(), is_exited(), null_ptid, ptid_equal(), target_has_memory, target_has_registers, and target_has_stack.
Referenced by check_frame_language_change(), deprecated_safe_get_selected_frame(), enable_break(), flush_ea_cache(), get_current_arch(), get_selected_block(), get_selected_frame(), mi_cmd_trace_find(), normal_stop(), pc_prefix(), tfind_1(), and varobj_create().
static int inside_entry_func (struct frame_info * this_frame) [static]
Definition at line 1936 of file frame.c.
References entry_point_address_query(), and get_frame_func().
Referenced by get_prev_frame().
static int inside_main_func (struct frame_info * this_frame) [static]
Definition at line 1915 of file frame.c.
References current_target, gdbarch_convert_from_func_ptr_addr(), get_frame_arch(), get_frame_func(), lookup_minimal_symbol(), main_name(), SYMBOL_VALUE_ADDRESS, and symfile_objfile.
Referenced by get_prev_frame().
void put_frame_register (struct frame_info * frame, int regnum, const gdb_byte * buf)
Definition at line 1133 of file frame.c.
References _, error(), frame_register(), get_current_regcache(), get_frame_arch(), lval_memory, lval_register, regcache_cooked_write(), register_size(), and write_memory().
Referenced by alpha_value_to_register(), i386_value_to_register(), i387_value_to_register(), ia64_value_to_register(), m68k_value_to_register(), mips_value_to_register(), put_frame_register_bytes(), and rs6000_value_to_register().
void put_frame_register_bytes (struct frame_info * frame, int regnum, CORE_ADDR offset, int len, const gdb_byte * myaddr)
Definition at line 1264 of file frame.c.
References deprecated_frame_register_read(), get_frame_arch(), len, MAX_REGISTER_SIZE, memcpy(), offset, put_frame_register(), and register_size().
Referenced by mips_value_to_register(), value_assign(), and write_pieced_value().
int read_frame_register_unsigned (struct frame_info * frame, int regnum, ULONGEST * val)
Definition at line 1113 of file frame.c.
References gdbarch::byte_order, extract_unsigned_integer(), gdbarch_byte_order(), get_frame_arch(), get_frame_register_value(), register_size(), size, value_contents(), value_entirely_available(), value_optimized_out(), and VALUE_REGNUM.
Referenced by i387_print_float_info().
void reinit_frame_cache (void)
Definition at line 1602 of file frame.c.
References annotate_frames_invalid(), frame_info::base, frame_info::base_cache, frame_unwind::dealloc_cache, fprintf_unfiltered(), frame_cache_obstack, frame_debug, frame_stash_invalidate(), gdb_stdlog, frame_info::prev, frame_info::prologue_cache, select_frame(), frame_base::unwind, and frame_info::unwind.
Referenced by add_symbol_file_command(), bsd_kvm_open(), bsd_kvm_pcb_cmd(), bsd_kvm_proc_cmd(), core_detach(), core_open(), fork_load_infrun_state(), frame_observer_target_changed(), frame_pop(), generic_mourn_inferior(), handle_inferior_event(), pop_dummy_frame(), record_full_goto_entry(), record_full_wait_1(), regcache_write_pc(), registers_changed_ptid(), reinit_frame_cache_sfunc(), reload_shared_libraries(), reread_symbols(), set_current_program_space(), skip_inline_frames(), solib_add(), step_into_inline_frame(), switch_to_thread(), symbol_file_add_from_memory(), symbol_file_add_main_1(), tfind_1(), and wrap_reinit_frame_cache().
int safe_frame_unwind_memory (struct frame_info * this_frame, CORE_ADDR addr, gdb_byte * buf, int len)
Definition at line 2357 of file frame.c.
References target_read_memory().
Referenced by amd64_linux_sigtramp_start(), amd64obsd_sigtramp_p(), cris_rt_sigtramp_start(), cris_sigtramp_start(), hppa_frame_cache(), hppa_hpux_sigtramp_unwind_sniffer(), i386_linux_rt_sigtramp_start(), i386_linux_sigtramp_start(), i386obsd_sigtramp_p(), m32r_linux_rt_sigtramp_start(), m32r_linux_sigtramp_start(), m68k_linux_pc_in_sigtramp(), ppcfbsd_sigtramp_frame_cache(), ppcfbsd_sigtramp_frame_sniffer(), ppcobsd_sigtramp_frame_cache(), ppcobsd_sigtramp_frame_sniffer(), rs6000_in_function_epilogue_p(), tilegx_analyze_prologue(), tramp_frame_start(), and vaxobsd_sigtramp_sniffer().
void select_frame (struct frame_info * fi)
Definition at line 1487 of file frame.c.
References current_language, deprecated_selected_frame_level_changed_hook, find_pc_symtab(), frame_relative_level(), get_frame_address_in_block_if_available(), language_defn::la_language, symtab::language, language_mode_auto, language_unknown, and set_language().
Referenced by ada_find_printable_frame(), ada_unhandled_exception_name_addr_from_raise(), bpstat_check_breakpoint_conditions(), check_scope(), down_silently_base(), frapy_select(), get_selected_frame(), mi_cmd_execute(), mi_cmd_trace_frame_collected(), normal_stop(), reinit_frame_cache(), restore_infcall_control_state(), restore_selected_frame(), select_and_print_frame(), select_frame_command(), trace_dump_command(), up_silently_base(), update_watchpoint(), value_assign(), varobj_create(), and watchpoint_check().
static void set_backtrace_cmd (char * args, int from_tty) [static]
Definition at line 2510 of file frame.c.
References gdb_stdout, and help_list().
Referenced by _initialize_frame().
static void show_backtrace_cmd (char * args, int from_tty) [static]
Definition at line 2516 of file frame.c.
References cmd_show_list().
Referenced by _initialize_frame().
static void show_backtrace_limit (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 270 of file frame.c.
References _, and fprintf_filtered().
Referenced by _initialize_frame().
static void show_backtrace_past_entry (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 260 of file frame.c.
References _, and fprintf_filtered().
Referenced by _initialize_frame().
static void show_backtrace_past_main (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 249 of file frame.c.
References _, and fprintf_filtered().
Referenced by _initialize_frame().
static void show_frame_debug (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 239 of file frame.c.
References _, and fprintf_filtered().
Referenced by _initialize_frame().
static struct frame_info* skip_artificial_frames (struct frame_info * frame) [static, read]
Definition at line 383 of file frame.c.
References get_frame_type(), get_prev_frame(), INLINE_FRAME, and TAILCALL_FRAME.
Referenced by frame_unwind_caller_arch(), frame_unwind_caller_id(), frame_unwind_caller_pc(), frame_unwind_caller_pc_if_available(), and get_stack_frame_id().
static int unwind_to_current_frame (struct ui_out * ui_out, void * args) [static]
Definition at line 1361 of file frame.c.
References get_prev_frame().
Referenced by get_current_frame().
Variable Documentation
initialize_file_ftype _initialize_frame
Referenced by _initialize_frame(), and initialize_all_files().
unsigned int backtrace_limit = UINT_MAX [static]
Definition at line 268 of file frame.c.
Referenced by _initialize_frame(), and get_prev_frame().
int backtrace_past_entry [static]
Definition at line 258 of file frame.c.
Referenced by _initialize_frame(), and get_prev_frame().
int backtrace_past_main [static]
Definition at line 247 of file frame.c.
Referenced by _initialize_frame(), and get_prev_frame().
struct frame_info* current_frame [static]
Definition at line 1338 of file frame.c.
Referenced by get_current_frame().
struct obstack frame_cache_obstack [static]
Definition at line 1344 of file frame.c.
Referenced by _initialize_frame(), frame_obstack_zalloc(), and reinit_frame_cache().
unsigned int frame_debug
Definition at line 237 of file frame.c.
Referenced by _initialize_frame(), amd64_windows_find_unwind_info(), amd64_windows_frame_decode_insns(), amd64_windows_frame_prev_register(), create_new_frame(), create_sentinel_frame(), frame_debug_got_null_frame(), frame_id_eq(), frame_id_inner(), frame_id_p(), frame_unwind_arch(), frame_unwind_pc_if_available(), frame_unwind_register_value(), get_frame_func_if_available(), get_frame_id(), get_prev_frame_1(), get_prev_frame_raw(), reinit_frame_cache(), and value_fetch_lazy().
htab_t frame_stash [static]
Definition at line 137 of file frame.c.
Referenced by frame_stash_add(), frame_stash_create(), frame_stash_find(), and frame_stash_invalidate().
struct frame_id null_frame_id
Definition at line 451 of file frame.c.
Referenced by allocate_value_lazy(), alpha_osf1_sigcontext_addr(), bpfinishpy_init(), clear_proceed_status_thread(), create_sentinel_frame(), finish_backward(), follow_fork(), frame_id_build(), frame_id_build_special(), frame_id_build_wild(), frame_unwind_caller_id(), get_frame_id(), handle_inferior_event(), handle_step_into_function(), ia64_hpux_dummy_id(), init_raw_breakpoint_without_location(), longjmp_bkpt_dtor(), new_root_variable(), set_momentary_breakpoint_at_pc(), tfind_1(), until_break_command(), varobj_create(), and watch_command_1().
struct frame_id outer_frame_id = { 0, 0, 0, 0, 0, 1, 0 }
Definition at line 452 of file frame.c.
Referenced by amd64obsd_trapframe_cache(), get_frame_id(), handle_inferior_event(), i386obsd_trapframe_cache(), and inline_frame_this_id().
struct frame_info* selected_frame [static]
Definition at line 1416 of file frame.c.
Referenced by gdbpy_lookup_symbol(), get_selected_frame(), and get_selected_frame_if_set().
struct cmd_list_element* set_backtrace_cmdlist [static]
Definition at line 2506 of file frame.c.
struct cmd_list_element* show_backtrace_cmdlist [static]
Definition at line 2507 of file frame.c.