GDB (xrefs): /home/stan/gdb/src/gdb/gdb.h File Reference
/home/stan/gdb/src/gdb/gdb.h File Reference
Enumerations
enum gdb_rc { GDB_RC_FAIL = 0, GDB_RC_NONE = 1, GDB_RC_OK = 2 }
Functions
enum gdb_rc gdb_breakpoint_query (struct ui_out *uiout, int bnum, char **error_message)
enum gdb_rc gdb_thread_select (struct ui_out *uiout, char *tidstr, char **error_message)
enum gdb_rc gdb_list_thread_ids (struct ui_out *uiout, char **error_message)
Enumeration Type Documentation
enum gdb_rc
Enumerator:
GDB_RC_FAIL
GDB_RC_NONE
GDB_RC_OK
Definition at line 27 of file gdb.h.
Function Documentation
enum gdb_rc gdb_breakpoint_query (struct ui_out * uiout, int bnum, char ** error_message)
Definition at line 6351 of file breakpoint.c.
References captured_breakpoint_query_args::bnum, catch_exceptions_with_msg(), do_captured_breakpoint_query(), GDB_RC_FAIL, GDB_RC_OK, and RETURN_MASK_ALL.
Referenced by breakpoint_notify(), mi_breakpoint_created(), and mi_breakpoint_modified().
enum gdb_rc gdb_list_thread_ids (struct ui_out * uiout, char ** error_message)
Definition at line 532 of file thread.c.
References catch_exceptions_with_msg(), do_captured_list_thread_ids(), GDB_RC_FAIL, GDB_RC_OK, and RETURN_MASK_ALL.
Referenced by mi_cmd_thread_list_ids().
enum gdb_rc gdb_thread_select (struct ui_out * uiout, char * tidstr, char ** error_message)
Definition at line 1481 of file thread.c.
References catch_exceptions_with_msg(), do_captured_thread_select(), GDB_RC_FAIL, GDB_RC_OK, and RETURN_MASK_ALL.
Referenced by mi_cmd_thread_select(), and thread_command().