GDB (xrefs): /home/stan/gdb/src/gdb/gdb_select.h File Reference
/home/stan/gdb/src/gdb/gdb_select.h File Reference
#include <sys/time.h>
Functions
int gdb_select (int n, fd_set *readfds, fd_set *writefds, fd_set *exceptfds, struct timeval *timeout)
Function Documentation
int gdb_select (int n, fd_set * readfds, fd_set * writefds, fd_set * exceptfds, struct timeval * timeout)
Definition at line 105 of file mingw-hdep.c.
References call_async_signal_handler(), serial::fd, gdb_assert, read(), serial_for_fd(), and sigint_event.
Referenced by gdb_usleep(), gdb_wait_for_event(), ser_base_wait_for(), stdio_file_read(), wait_for(), and wait_for_connect().