GDB (xrefs): /home/stan/gdb/src/gdb/common/gdb_vecs.h File Reference
/home/stan/gdb/src/gdb/common/gdb_vecs.h File Reference
#include "vec.h"
Typedefs
typedef char * char_ptr
typedef const char * const_char_ptr
Functions
DEF_VEC_P (char_ptr)
DEF_VEC_P (const_char_ptr)
DEF_VEC_I (int)
void free_char_ptr_vec (VEC(char_ptr)*char_ptr_vec)
struct cleanup * make_cleanup_free_char_ptr_vec (VEC(char_ptr)*char_ptr_vec)
void dirnames_to_char_ptr_vec_append (VEC(char_ptr)**vecp, const char *dirnames)
VEC (char_ptr)*dirnames_to_char_ptr_vec(const char *dirnames)
Typedef Documentation
typedef char* char_ptr
Definition at line 25 of file gdb_vecs.h.
typedef const char* const_char_ptr
Definition at line 26 of file gdb_vecs.h.
Function Documentation
DEF_VEC_I (int)
DEF_VEC_P (char_ptr)
DEF_VEC_P (const_char_ptr)
void dirnames_to_char_ptr_vec_append (VEC(char_ptr)** vecp, const char * dirnames)
Definition at line 52 of file gdb_vecs.c.
References memcpy(), strchr(), VEC_safe_push, and xmalloc().
Referenced by add_path(), and VEC().
void free_char_ptr_vec (VEC(char_ptr)* char_ptr_vec)
Definition at line 37 of file gdb_vecs.c.
References name, VEC_free, VEC_iterate, and xfree().
Referenced by auto_load_safe_path_vec_update(), clear_program_space_solib_cache(), and do_free_char_ptr_vec().
struct cleanup* make_cleanup_free_char_ptr_vec (VEC(char_ptr)* char_ptr_vec) [read]
Definition at line 3506 of file utils.c.
References do_free_char_ptr_vec(), and make_cleanup().
Referenced by add_path(), auto_load_objfile_script_1(), build_id_to_debug_bfd(), find_separate_debug_file(), openp(), and thread_db_load_search().
VEC (char_ptr) const