GDB (xrefs): /home/stan/gdb/src/gdb/gdb_proc_service.h File Reference
/home/stan/gdb/src/gdb/gdb_proc_service.h File Reference
#include <sys/types.h>
#include "gregset.h"
Classes
struct ps_prochandle
Typedefs
typedef unsigned int lwpid_t
typedef void * psaddr_t
typedef gdb_gregset_t prgregset_t
typedef gdb_fpregset_t prfpregset_t
typedef prfpregset_t gdb_prfpregset_t
Enumerations
enum ps_err_e {
PS_OK, PS_ERR, PS_BADPID, PS_BADLID,
PS_BADADDR, PS_NOSYM, PS_NOFREGS
}
Functions
ps_err_e ps_pdread (struct ps_prochandle *, psaddr_t, void *, size_t)
ps_err_e ps_pdwrite (struct ps_prochandle *, psaddr_t, const void *, size_t)
ps_err_e ps_ptread (struct ps_prochandle *, psaddr_t, void *, size_t)
ps_err_e ps_ptwrite (struct ps_prochandle *, psaddr_t, const void *, size_t)
ps_err_e ps_lgetregs (struct ps_prochandle *, lwpid_t, prgregset_t)
ps_err_e ps_lsetregs (struct ps_prochandle *, lwpid_t, const prgregset_t)
ps_err_e ps_lgetfpregs (struct ps_prochandle *, lwpid_t, prfpregset_t *)
ps_err_e ps_lsetfpregs (struct ps_prochandle *, lwpid_t, const prfpregset_t *)
pid_t ps_getpid (struct ps_prochandle *)
ps_err_e ps_get_thread_area (const struct ps_prochandle *, lwpid_t, int, psaddr_t *)
ps_err_e ps_pglobal_lookup (struct ps_prochandle *, const char *object_name, const char *sym_name, psaddr_t *sym_addr)
ps_err_e ps_pstop (struct ps_prochandle *)
ps_err_e ps_pcontinue (struct ps_prochandle *)
ps_err_e ps_lstop (struct ps_prochandle *, lwpid_t)
ps_err_e ps_lcontinue (struct ps_prochandle *, lwpid_t)
ps_err_e ps_lgetxregsize (struct ps_prochandle *ph, lwpid_t lwpid, int *xregsize)
ps_err_e ps_lgetxregs (struct ps_prochandle *ph, lwpid_t lwpid, caddr_t xregset)
ps_err_e ps_lsetxregs (struct ps_prochandle *ph, lwpid_t lwpid, caddr_t xregset)
void ps_plog (const char *fmt,...)
Typedef Documentation
typedef prfpregset_t gdb_prfpregset_t
Definition at line 164 of file gdb_proc_service.h.
typedef unsigned int lwpid_t
Definition at line 71 of file gdb_proc_service.h.
typedef gdb_fpregset_t prfpregset_t
Definition at line 83 of file gdb_proc_service.h.
typedef gdb_gregset_t prgregset_t
Definition at line 79 of file gdb_proc_service.h.
typedef void* psaddr_t
Definition at line 75 of file gdb_proc_service.h.
Enumeration Type Documentation
enum ps_err_e
Enumerator:
PS_OK
PS_ERR
PS_BADPID
PS_BADLID
PS_BADADDR
PS_NOSYM
PS_NOFREGS
Definition at line 59 of file gdb_proc_service.h.
Function Documentation
ps_err_e ps_get_thread_area (const struct ps_prochandle * , lwpid_t , int , psaddr_t *)
Definition at line 753 of file aarch64-linux-nat.c.
References ELF_NGREG, gdb_assert, gdbarch_bfd_arch_info(), PS_BADADDR, PS_ERR, PS_OK, ptrace(), PTRACE_ARCH_PRCTL, PTRACE_GET_THREAD_AREA, PTRACE_GETREGSET, and target_gdbarch().
pid_t ps_getpid (struct ps_prochandle *)
ps_err_e ps_lcontinue (struct ps_prochandle * , lwpid_t)
ps_err_e ps_lgetfpregs (struct ps_prochandle * , lwpid_t , prfpregset_t *)
ps_err_e ps_lgetregs (struct ps_prochandle * , lwpid_t , prgregset_t)
ps_err_e ps_lgetxregs (struct ps_prochandle * ph, lwpid_t lwpid, caddr_t xregset)
ps_err_e ps_lgetxregsize (struct ps_prochandle * ph, lwpid_t lwpid, int * xregsize)
ps_err_e ps_lsetfpregs (struct ps_prochandle * , lwpid_t , const prfpregset_t *)
ps_err_e ps_lsetregs (struct ps_prochandle * , lwpid_t , const prgregset_t)
ps_err_e ps_lsetxregs (struct ps_prochandle * ph, lwpid_t lwpid, caddr_t xregset)
ps_err_e ps_lstop (struct ps_prochandle * , lwpid_t)
ps_err_e ps_pcontinue (struct ps_prochandle *)
ps_err_e ps_pdread (struct ps_prochandle * , psaddr_t , void * , size_t)
ps_err_e ps_pdwrite (struct ps_prochandle * , psaddr_t , const void * , size_t)
ps_err_e ps_pglobal_lookup (struct ps_prochandle * , const char * object_name, const char * sym_name, psaddr_t * sym_addr)
void ps_plog (const char * fmt, ...)
Definition at line 180 of file proc-service.c.
References gdb_stderr, and vfprintf_filtered().
ps_err_e ps_pstop (struct ps_prochandle *)
ps_err_e ps_ptread (struct ps_prochandle * , psaddr_t , void * , size_t)
ps_err_e ps_ptwrite (struct ps_prochandle * , psaddr_t , const void * , size_t)