GDB (xrefs): /home/stan/gdb/src/gdb/common/gdb_vecs.c File Reference
/home/stan/gdb/src/gdb/common/gdb_vecs.c File Reference
#include "defs.h"
#include "gdb_vecs.h"
#include "host-defs.h"
Functions
void free_char_ptr_vec (VEC(char_ptr)*char_ptr_vec)
void dirnames_to_char_ptr_vec_append (VEC(char_ptr)**vecp, const char *dirnames)
VEC (char_ptr)
Function Documentation
void dirnames_to_char_ptr_vec_append (VEC(char_ptr)** vecp, const char * dirnames)
Definition at line 52 of file gdb_vecs.c.
References memcpy(), strchr(), VEC_safe_push, and xmalloc().
Referenced by add_path(), and VEC().
void free_char_ptr_vec (VEC(char_ptr)* char_ptr_vec)
Definition at line 37 of file gdb_vecs.c.
References name, VEC_free, VEC_iterate, and xfree().
Referenced by auto_load_safe_path_vec_update(), clear_program_space_solib_cache(), and do_free_char_ptr_vec().
VEC (char_ptr)
Definition at line 85 of file gdb_vecs.c.
References dirnames_to_char_ptr_vec_append(), and VEC.