GDB (xrefs): /home/stan/gdb/src/gdb/gdb_ptrace.h File Reference
/home/stan/gdb/src/gdb/gdb_ptrace.h File Reference
Defines
#define PT_TRACE_ME 0
#define PT_READ_I 1 /* Read word in child's I space. */
#define PT_READ_D 2 /* Read word in child's D space. */
#define PT_READ_U 3 /* Read word in child's U space. */
#define PT_WRITE_I 4 /* Write word in child's I space. */
#define PT_WRITE_D 5 /* Write word in child's D space. */
#define PT_WRITE_U 6 /* Write word in child's U space. */
#define PT_CONTINUE 7 /* Continue the child. */
#define PT_KILL 8 /* Kill the child process. */
#define PT_STEP 9 /* Single step the child. */
#define PT_SYSCALL PT_CONTINUE
Functions
PTRACE_TYPE_RET ptrace ()
Define Documentation
#define PT_CONTINUE 7 /* Continue the child. */
Definition at line 79 of file gdb_ptrace.h.
Referenced by exec_one_dummy_insn(), i386fbsd_resume(), and inf_ptrace_resume().
#define PT_KILL 8 /* Kill the child process. */
Definition at line 84 of file gdb_ptrace.h.
Referenced by inf_ptrace_kill(), and linux_nat_kill().
#define PT_READ_D 2 /* Read word in child's D space. */
Definition at line 51 of file gdb_ptrace.h.
#define PT_READ_I 1 /* Read word in child's I space. */
Definition at line 47 of file gdb_ptrace.h.
Referenced by fetch_ppc_memory_1(), inf_ptrace_xfer_partial(), and rs6000_xfer_partial().
#define PT_READ_U 3 /* Read word in child's U space. */
Definition at line 55 of file gdb_ptrace.h.
Referenced by fetch_ppc_register(), ia64_linux_fetch_register(), and inf_ptrace_fetch_register().
#define PT_STEP 9 /* Single step the child. */
Definition at line 91 of file gdb_ptrace.h.
Referenced by i386fbsd_resume(), and inf_ptrace_resume().
#define PT_SYSCALL PT_CONTINUE
Definition at line 120 of file gdb_ptrace.h.
Referenced by inf_ptrace_resume(), spu_child_post_attach(), and spu_child_post_startup_inferior().
#define PT_TRACE_ME 0
Definition at line 43 of file gdb_ptrace.h.
Referenced by darwin_ptrace_me(), and inf_ptrace_me().
#define PT_WRITE_D 5 /* Write word in child's D space. */
Definition at line 63 of file gdb_ptrace.h.
Referenced by inf_ptrace_xfer_partial(), rs6000_xfer_partial(), and store_ppc_memory_1().
#define PT_WRITE_I 4 /* Write word in child's I space. */
Definition at line 59 of file gdb_ptrace.h.
Referenced by inf_ptrace_xfer_partial().
#define PT_WRITE_U 6 /* Write word in child's U space. */
Definition at line 67 of file gdb_ptrace.h.
Referenced by ia64_linux_store_register(), inf_ptrace_store_register(), and store_debug_register().
Function Documentation
PTRACE_TYPE_RET ptrace ()
Referenced by aarch64_linux_get_debug_reg_capacity(), aarch64_linux_set_debug_regs(), alphabsd_fetch_inferior_registers(), alphabsd_store_inferior_registers(), amd64_linux_dr_get(), amd64_linux_dr_set(), amd64_linux_fetch_inferior_registers(), amd64_linux_read_description(), amd64_linux_store_inferior_registers(), amd64bsd_fetch_inferior_registers(), amd64bsd_store_inferior_registers(), arm_linux_get_hwbp_cap(), arm_linux_insert_hw_breakpoint1(), arm_linux_read_description(), arm_linux_remove_hw_breakpoint1(), check_regset(), darwin_ptrace(), delete_checkpoint_command(), detach_callback(), detach_checkpoint_command(), fetch_all_fp_regs(), fetch_all_gp_regs(), fetch_altivec_register(), fetch_altivec_registers(), fetch_fp_register(), fetch_fp_regs(), fetch_fpregister(), fetch_fpregs(), fetch_fpregs_from_thread(), fetch_gregs(), fetch_gregs_from_thread(), fetch_inferior_registers(), fetch_ppc_memory_1(), fetch_ppc_register(), fetch_register(), fetch_regs(), fetch_regset(), fetch_vfp_regs(), fetch_vsx_register(), fetch_vsx_registers(), fetch_wmmx_regs(), fetch_xstateregs(), fetch_xtregs(), get_spe_registers(), gnu_create_inferior(), hppa_hpux_fetch_register(), hppa_hpux_store_register(), hppabsd_fetch_registers(), hppabsd_store_registers(), hppanbsd_fetch_registers(), hppanbsd_store_registers(), hwdebug_insert_point(), hwdebug_remove_point(), i386_linux_dr_get(), i386_linux_dr_set(), i386_linux_read_description(), i386_linux_resume(), i386bsd_fetch_inferior_registers(), i386bsd_store_inferior_registers(), i386fbsd_resume(), ia64_linux_fetch_register(), ia64_linux_store_register(), inf_ptrace_attach(), inf_ptrace_detach(), inf_ptrace_fetch_register(), inf_ptrace_kill(), inf_ptrace_me(), inf_ptrace_resume(), inf_ptrace_store_register(), inf_ptrace_wait(), inf_ptrace_xfer_partial(), kill_callback(), lin_lwp_attach_lwp(), linux_check_ptrace_features(), linux_child_follow_fork(), linux_child_function(), linux_enable_event_reporting(), linux_fork_detach(), linux_handle_extended_wait(), linux_handle_syscall_trap(), linux_nat_get_siginfo(), linux_nat_kill(), linux_nat_post_attach_wait(), linux_ptrace_test_ret_to_nx(), linux_test_for_tracefork(), linux_test_for_tracesysgood(), linux_xfer_siginfo(), m68kbsd_fetch_inferior_registers(), m68kbsd_store_inferior_registers(), m88kbsd_fetch_inferior_registers(), m88kbsd_store_inferior_registers(), mips64_linux_regsets_fetch_registers(), mips64_linux_regsets_store_registers(), mips64obsd_fetch_inferior_registers(), mips64obsd_store_inferior_registers(), mips_linux_new_thread(), mips_linux_read_description(), mips_linux_read_watch_registers(), mipsnbsd_fetch_inferior_registers(), mipsnbsd_store_inferior_registers(), ppc_linux_can_use_hw_breakpoint(), ppc_linux_insert_watchpoint(), ppc_linux_new_thread(), ppc_linux_read_description(), ppc_linux_remove_watchpoint(), ppc_linux_target_wordsize(), ppcfbsd_fetch_inferior_registers(), ppcfbsd_store_inferior_registers(), ppcnbsd_fetch_inferior_registers(), ppcnbsd_store_inferior_registers(), ppcobsd_fetch_registers(), ppcobsd_store_registers(), ps_get_thread_area(), ptrace32(), rs6000_ptrace32(), s390_fix_watch_points(), s390_stopped_by_watchpoint(), s390_target_wordsize(), set_spe_registers(), shnbsd_fetch_inferior_registers(), shnbsd_store_inferior_registers(), sparc_fetch_inferior_registers(), sparc_store_inferior_registers(), sparc_xfer_wcookie(), spu_child_post_attach(), spu_child_post_startup_inferior(), stop_wait_callback(), store_all_fp_regs(), store_all_gp_regs(), store_altivec_register(), store_altivec_registers(), store_debug_register(), store_fp_register(), store_fp_regs(), store_fpregister(), store_fpregs(), store_fpregs_to_thread(), store_gregs(), store_gregs_to_thread(), store_inferior_registers(), store_ppc_memory_1(), store_register(), store_regs(), store_regset(), store_vfp_regs(), store_vsx_register(), store_vsx_registers(), store_wmmx_regs(), store_xstateregs(), store_xtregs(), vax_register_u_offset(), vaxbsd_fetch_inferior_registers(), vaxbsd_store_inferior_registers(), VEC(), and write_watchpoint_regs().