GDB (xrefs): /home/stan/gdb/src/gdb/gdb_regex.h File Reference
/home/stan/gdb/src/gdb/gdb_regex.h File Reference
#include <regex.h>
Defines
#define _REGEX_RE_COMP
Functions
struct cleanup * make_regfree_cleanup (regex_t *)
char * get_regcomp_error (int, regex_t *)
struct cleanup * compile_rx_or_error (regex_t *pattern, const char *rx, const char *message)
Define Documentation
#define _REGEX_RE_COMP
Definition at line 26 of file gdb_regex.h.
Function Documentation
struct cleanup* compile_rx_or_error (regex_t * pattern, const char * rx, const char * message) [read]
Definition at line 1147 of file utils.c.
References code, error(), gdb_assert, get_regcomp_error(), make_cleanup(), make_regfree_cleanup(), and xfree().
Referenced by handle_gnu_v3_exceptions().
char* get_regcomp_error (int , regex_t *)
Definition at line 1133 of file utils.c.
References xmalloc().
Referenced by add_solib_catchpoint(), apropos_command(), compile_rx_or_error(), and search_symbols().
struct cleanup* make_regfree_cleanup (regex_t *) [read]
Definition at line 1124 of file utils.c.
References do_regfree_cleanup(), and make_cleanup().
Referenced by apropos_command(), compile_rx_or_error(), and search_symbols().