GDB (xrefs): /home/stan/gdb/src/gdb/gdbarch.c File Reference
/home/stan/gdb/src/gdb/gdbarch.c File Reference
#include "defs.h"
#include "arch-utils.h"
#include "gdbcmd.h"
#include "inferior.h"
#include "symcat.h"
#include "floatformat.h"
#include "gdb_assert.h"
#include "gdb_string.h"
#include "reggroups.h"
#include "osabi.h"
#include "gdb_obstack.h"
#include "observer.h"
#include "regcache.h"
#include "objfiles.h"
Classes
struct gdbarch
struct gdbarch_data
struct gdbarch_data_registration
struct gdbarch_data_registry
struct gdbarch_registration
Defines
#define GDBARCH_DEBUG 0
Functions
static void alloc_gdbarch_data (struct gdbarch *)
static void show_gdbarch_debug (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static const char * pformat (const struct floatformat **format)
static const char * pstring (const char *string)
struct gdbarch * gdbarch_alloc (const struct gdbarch_info *info, struct gdbarch_tdep *tdep)
void * gdbarch_obstack_zalloc (struct gdbarch *arch, long size)
void gdbarch_free (struct gdbarch *arch)
static void verify_gdbarch (struct gdbarch *gdbarch)
void gdbarch_dump (struct gdbarch *gdbarch, struct ui_file *file)
struct gdbarch_tdep * gdbarch_tdep (struct gdbarch *gdbarch)
struct bfd_arch_info * gdbarch_bfd_arch_info (struct gdbarch *gdbarch)
int gdbarch_byte_order (struct gdbarch *gdbarch)
int gdbarch_byte_order_for_code (struct gdbarch *gdbarch)
enum gdb_osabi gdbarch_osabi (struct gdbarch *gdbarch)
struct target_desc * gdbarch_target_desc (struct gdbarch *gdbarch)
int gdbarch_bits_big_endian (struct gdbarch *gdbarch)
void set_gdbarch_bits_big_endian (struct gdbarch *gdbarch, int bits_big_endian)
int gdbarch_short_bit (struct gdbarch *gdbarch)
void set_gdbarch_short_bit (struct gdbarch *gdbarch, int short_bit)
int gdbarch_int_bit (struct gdbarch *gdbarch)
void set_gdbarch_int_bit (struct gdbarch *gdbarch, int int_bit)
int gdbarch_long_bit (struct gdbarch *gdbarch)
void set_gdbarch_long_bit (struct gdbarch *gdbarch, int long_bit)
int gdbarch_long_long_bit (struct gdbarch *gdbarch)
void set_gdbarch_long_long_bit (struct gdbarch *gdbarch, int long_long_bit)
int gdbarch_long_long_align_bit (struct gdbarch *gdbarch)
void set_gdbarch_long_long_align_bit (struct gdbarch *gdbarch, int long_long_align_bit)
int gdbarch_half_bit (struct gdbarch *gdbarch)
void set_gdbarch_half_bit (struct gdbarch *gdbarch, int half_bit)
struct floatformat ** gdbarch_half_format (struct gdbarch *gdbarch)
void set_gdbarch_half_format (struct gdbarch *gdbarch, const struct floatformat **half_format)
int gdbarch_float_bit (struct gdbarch *gdbarch)
void set_gdbarch_float_bit (struct gdbarch *gdbarch, int float_bit)
struct floatformat ** gdbarch_float_format (struct gdbarch *gdbarch)
void set_gdbarch_float_format (struct gdbarch *gdbarch, const struct floatformat **float_format)
int gdbarch_double_bit (struct gdbarch *gdbarch)
void set_gdbarch_double_bit (struct gdbarch *gdbarch, int double_bit)
struct floatformat ** gdbarch_double_format (struct gdbarch *gdbarch)
void set_gdbarch_double_format (struct gdbarch *gdbarch, const struct floatformat **double_format)
int gdbarch_long_double_bit (struct gdbarch *gdbarch)
void set_gdbarch_long_double_bit (struct gdbarch *gdbarch, int long_double_bit)
struct floatformat ** gdbarch_long_double_format (struct gdbarch *gdbarch)
void set_gdbarch_long_double_format (struct gdbarch *gdbarch, const struct floatformat **long_double_format)
int gdbarch_ptr_bit (struct gdbarch *gdbarch)
void set_gdbarch_ptr_bit (struct gdbarch *gdbarch, int ptr_bit)
int gdbarch_addr_bit (struct gdbarch *gdbarch)
void set_gdbarch_addr_bit (struct gdbarch *gdbarch, int addr_bit)
int gdbarch_dwarf2_addr_size (struct gdbarch *gdbarch)
void set_gdbarch_dwarf2_addr_size (struct gdbarch *gdbarch, int dwarf2_addr_size)
int gdbarch_char_signed (struct gdbarch *gdbarch)
void set_gdbarch_char_signed (struct gdbarch *gdbarch, int char_signed)
int gdbarch_read_pc_p (struct gdbarch *gdbarch)
CORE_ADDR gdbarch_read_pc (struct gdbarch *gdbarch, struct regcache *regcache)
void set_gdbarch_read_pc (struct gdbarch *gdbarch, gdbarch_read_pc_ftype read_pc)
int gdbarch_write_pc_p (struct gdbarch *gdbarch)
void gdbarch_write_pc (struct gdbarch *gdbarch, struct regcache *regcache, CORE_ADDR val)
void set_gdbarch_write_pc (struct gdbarch *gdbarch, gdbarch_write_pc_ftype write_pc)
void gdbarch_virtual_frame_pointer (struct gdbarch *gdbarch, CORE_ADDR pc, int *frame_regnum, LONGEST *frame_offset)
void set_gdbarch_virtual_frame_pointer (struct gdbarch *gdbarch, gdbarch_virtual_frame_pointer_ftype virtual_frame_pointer)
int gdbarch_pseudo_register_read_p (struct gdbarch *gdbarch)
enum register_status gdbarch_pseudo_register_read (struct gdbarch *gdbarch, struct regcache *regcache, int cookednum, gdb_byte *buf)
void set_gdbarch_pseudo_register_read (struct gdbarch *gdbarch, gdbarch_pseudo_register_read_ftype pseudo_register_read)
int gdbarch_pseudo_register_read_value_p (struct gdbarch *gdbarch)
struct value * gdbarch_pseudo_register_read_value (struct gdbarch *gdbarch, struct regcache *regcache, int cookednum)
void set_gdbarch_pseudo_register_read_value (struct gdbarch *gdbarch, gdbarch_pseudo_register_read_value_ftype pseudo_register_read_value)
int gdbarch_pseudo_register_write_p (struct gdbarch *gdbarch)
void gdbarch_pseudo_register_write (struct gdbarch *gdbarch, struct regcache *regcache, int cookednum, const gdb_byte *buf)
void set_gdbarch_pseudo_register_write (struct gdbarch *gdbarch, gdbarch_pseudo_register_write_ftype pseudo_register_write)
int gdbarch_num_regs (struct gdbarch *gdbarch)
void set_gdbarch_num_regs (struct gdbarch *gdbarch, int num_regs)
int gdbarch_num_pseudo_regs (struct gdbarch *gdbarch)
void set_gdbarch_num_pseudo_regs (struct gdbarch *gdbarch, int num_pseudo_regs)
int gdbarch_ax_pseudo_register_collect_p (struct gdbarch *gdbarch)
int gdbarch_ax_pseudo_register_collect (struct gdbarch *gdbarch, struct agent_expr *ax, int reg)
void set_gdbarch_ax_pseudo_register_collect (struct gdbarch *gdbarch, gdbarch_ax_pseudo_register_collect_ftype ax_pseudo_register_collect)
int gdbarch_ax_pseudo_register_push_stack_p (struct gdbarch *gdbarch)
int gdbarch_ax_pseudo_register_push_stack (struct gdbarch *gdbarch, struct agent_expr *ax, int reg)
void set_gdbarch_ax_pseudo_register_push_stack (struct gdbarch *gdbarch, gdbarch_ax_pseudo_register_push_stack_ftype ax_pseudo_register_push_stack)
int gdbarch_sp_regnum (struct gdbarch *gdbarch)
void set_gdbarch_sp_regnum (struct gdbarch *gdbarch, int sp_regnum)
int gdbarch_pc_regnum (struct gdbarch *gdbarch)
void set_gdbarch_pc_regnum (struct gdbarch *gdbarch, int pc_regnum)
int gdbarch_ps_regnum (struct gdbarch *gdbarch)
void set_gdbarch_ps_regnum (struct gdbarch *gdbarch, int ps_regnum)
int gdbarch_fp0_regnum (struct gdbarch *gdbarch)
void set_gdbarch_fp0_regnum (struct gdbarch *gdbarch, int fp0_regnum)
int gdbarch_stab_reg_to_regnum (struct gdbarch *gdbarch, int stab_regnr)
void set_gdbarch_stab_reg_to_regnum (struct gdbarch *gdbarch, gdbarch_stab_reg_to_regnum_ftype stab_reg_to_regnum)
int gdbarch_ecoff_reg_to_regnum (struct gdbarch *gdbarch, int ecoff_regnr)
void set_gdbarch_ecoff_reg_to_regnum (struct gdbarch *gdbarch, gdbarch_ecoff_reg_to_regnum_ftype ecoff_reg_to_regnum)
int gdbarch_sdb_reg_to_regnum (struct gdbarch *gdbarch, int sdb_regnr)
void set_gdbarch_sdb_reg_to_regnum (struct gdbarch *gdbarch, gdbarch_sdb_reg_to_regnum_ftype sdb_reg_to_regnum)
int gdbarch_dwarf2_reg_to_regnum (struct gdbarch *gdbarch, int dwarf2_regnr)
void set_gdbarch_dwarf2_reg_to_regnum (struct gdbarch *gdbarch, gdbarch_dwarf2_reg_to_regnum_ftype dwarf2_reg_to_regnum)
const char * gdbarch_register_name (struct gdbarch *gdbarch, int regnr)
void set_gdbarch_register_name (struct gdbarch *gdbarch, gdbarch_register_name_ftype register_name)
int gdbarch_register_type_p (struct gdbarch *gdbarch)
struct type * gdbarch_register_type (struct gdbarch *gdbarch, int reg_nr)
void set_gdbarch_register_type (struct gdbarch *gdbarch, gdbarch_register_type_ftype register_type)
int gdbarch_dummy_id_p (struct gdbarch *gdbarch)
struct frame_id gdbarch_dummy_id (struct gdbarch *gdbarch, struct frame_info *this_frame)
void set_gdbarch_dummy_id (struct gdbarch *gdbarch, gdbarch_dummy_id_ftype dummy_id)
int gdbarch_deprecated_fp_regnum (struct gdbarch *gdbarch)
void set_gdbarch_deprecated_fp_regnum (struct gdbarch *gdbarch, int deprecated_fp_regnum)
int gdbarch_push_dummy_call_p (struct gdbarch *gdbarch)
CORE_ADDR gdbarch_push_dummy_call (struct gdbarch *gdbarch, struct value *function, struct regcache *regcache, CORE_ADDR bp_addr, int nargs, struct value **args, CORE_ADDR sp, int struct_return, CORE_ADDR struct_addr)
void set_gdbarch_push_dummy_call (struct gdbarch *gdbarch, gdbarch_push_dummy_call_ftype push_dummy_call)
int gdbarch_call_dummy_location (struct gdbarch *gdbarch)
void set_gdbarch_call_dummy_location (struct gdbarch *gdbarch, int call_dummy_location)
int gdbarch_push_dummy_code_p (struct gdbarch *gdbarch)
CORE_ADDR gdbarch_push_dummy_code (struct gdbarch *gdbarch, CORE_ADDR sp, CORE_ADDR funaddr, struct value **args, int nargs, struct type *value_type, CORE_ADDR *real_pc, CORE_ADDR *bp_addr, struct regcache *regcache)
void set_gdbarch_push_dummy_code (struct gdbarch *gdbarch, gdbarch_push_dummy_code_ftype push_dummy_code)
void gdbarch_print_registers_info (struct gdbarch *gdbarch, struct ui_file *file, struct frame_info *frame, int regnum, int all)
void set_gdbarch_print_registers_info (struct gdbarch *gdbarch, gdbarch_print_registers_info_ftype print_registers_info)
int gdbarch_print_float_info_p (struct gdbarch *gdbarch)
void gdbarch_print_float_info (struct gdbarch *gdbarch, struct ui_file *file, struct frame_info *frame, const char *args)
void set_gdbarch_print_float_info (struct gdbarch *gdbarch, gdbarch_print_float_info_ftype print_float_info)
int gdbarch_print_vector_info_p (struct gdbarch *gdbarch)
void gdbarch_print_vector_info (struct gdbarch *gdbarch, struct ui_file *file, struct frame_info *frame, const char *args)
void set_gdbarch_print_vector_info (struct gdbarch *gdbarch, gdbarch_print_vector_info_ftype print_vector_info)
int gdbarch_register_sim_regno (struct gdbarch *gdbarch, int reg_nr)
void set_gdbarch_register_sim_regno (struct gdbarch *gdbarch, gdbarch_register_sim_regno_ftype register_sim_regno)
int gdbarch_cannot_fetch_register (struct gdbarch *gdbarch, int regnum)
void set_gdbarch_cannot_fetch_register (struct gdbarch *gdbarch, gdbarch_cannot_fetch_register_ftype cannot_fetch_register)
int gdbarch_cannot_store_register (struct gdbarch *gdbarch, int regnum)
void set_gdbarch_cannot_store_register (struct gdbarch *gdbarch, gdbarch_cannot_store_register_ftype cannot_store_register)
int gdbarch_get_longjmp_target_p (struct gdbarch *gdbarch)
int gdbarch_get_longjmp_target (struct gdbarch *gdbarch, struct frame_info *frame, CORE_ADDR *pc)
void set_gdbarch_get_longjmp_target (struct gdbarch *gdbarch, gdbarch_get_longjmp_target_ftype get_longjmp_target)
int gdbarch_believe_pcc_promotion (struct gdbarch *gdbarch)
void set_gdbarch_believe_pcc_promotion (struct gdbarch *gdbarch, int believe_pcc_promotion)
int gdbarch_convert_register_p (struct gdbarch *gdbarch, int regnum, struct type *type)
void set_gdbarch_convert_register_p (struct gdbarch *gdbarch, gdbarch_convert_register_p_ftype convert_register_p)
int gdbarch_register_to_value (struct gdbarch *gdbarch, struct frame_info *frame, int regnum, struct type *type, gdb_byte *buf, int *optimizedp, int *unavailablep)
void set_gdbarch_register_to_value (struct gdbarch *gdbarch, gdbarch_register_to_value_ftype register_to_value)
void gdbarch_value_to_register (struct gdbarch *gdbarch, struct frame_info *frame, int regnum, struct type *type, const gdb_byte *buf)
void set_gdbarch_value_to_register (struct gdbarch *gdbarch, gdbarch_value_to_register_ftype value_to_register)
struct value * gdbarch_value_from_register (struct gdbarch *gdbarch, struct type *type, int regnum, struct frame_info *frame)
void set_gdbarch_value_from_register (struct gdbarch *gdbarch, gdbarch_value_from_register_ftype value_from_register)
CORE_ADDR gdbarch_pointer_to_address (struct gdbarch *gdbarch, struct type *type, const gdb_byte *buf)
void set_gdbarch_pointer_to_address (struct gdbarch *gdbarch, gdbarch_pointer_to_address_ftype pointer_to_address)
void gdbarch_address_to_pointer (struct gdbarch *gdbarch, struct type *type, gdb_byte *buf, CORE_ADDR addr)
void set_gdbarch_address_to_pointer (struct gdbarch *gdbarch, gdbarch_address_to_pointer_ftype address_to_pointer)
int gdbarch_integer_to_address_p (struct gdbarch *gdbarch)
CORE_ADDR gdbarch_integer_to_address (struct gdbarch *gdbarch, struct type *type, const gdb_byte *buf)
void set_gdbarch_integer_to_address (struct gdbarch *gdbarch, gdbarch_integer_to_address_ftype integer_to_address)
int gdbarch_return_value_p (struct gdbarch *gdbarch)
enum return_value_convention gdbarch_return_value (struct gdbarch *gdbarch, struct value *function, struct type *valtype, struct regcache *regcache, gdb_byte *readbuf, const gdb_byte *writebuf)
void set_gdbarch_return_value (struct gdbarch *gdbarch, gdbarch_return_value_ftype return_value)
int gdbarch_return_in_first_hidden_param_p (struct gdbarch *gdbarch, struct type *type)
void set_gdbarch_return_in_first_hidden_param_p (struct gdbarch *gdbarch, gdbarch_return_in_first_hidden_param_p_ftype return_in_first_hidden_param_p)
CORE_ADDR gdbarch_skip_prologue (struct gdbarch *gdbarch, CORE_ADDR ip)
void set_gdbarch_skip_prologue (struct gdbarch *gdbarch, gdbarch_skip_prologue_ftype skip_prologue)
int gdbarch_skip_main_prologue_p (struct gdbarch *gdbarch)
CORE_ADDR gdbarch_skip_main_prologue (struct gdbarch *gdbarch, CORE_ADDR ip)
void set_gdbarch_skip_main_prologue (struct gdbarch *gdbarch, gdbarch_skip_main_prologue_ftype skip_main_prologue)
int gdbarch_inner_than (struct gdbarch *gdbarch, CORE_ADDR lhs, CORE_ADDR rhs)
void set_gdbarch_inner_than (struct gdbarch *gdbarch, gdbarch_inner_than_ftype inner_than)
const gdb_byte * gdbarch_breakpoint_from_pc (struct gdbarch *gdbarch, CORE_ADDR *pcptr, int *lenptr)
void set_gdbarch_breakpoint_from_pc (struct gdbarch *gdbarch, gdbarch_breakpoint_from_pc_ftype breakpoint_from_pc)
void gdbarch_remote_breakpoint_from_pc (struct gdbarch *gdbarch, CORE_ADDR *pcptr, int *kindptr)
void set_gdbarch_remote_breakpoint_from_pc (struct gdbarch *gdbarch, gdbarch_remote_breakpoint_from_pc_ftype remote_breakpoint_from_pc)
int gdbarch_adjust_breakpoint_address_p (struct gdbarch *gdbarch)
CORE_ADDR gdbarch_adjust_breakpoint_address (struct gdbarch *gdbarch, CORE_ADDR bpaddr)
void set_gdbarch_adjust_breakpoint_address (struct gdbarch *gdbarch, gdbarch_adjust_breakpoint_address_ftype adjust_breakpoint_address)
int gdbarch_memory_insert_breakpoint (struct gdbarch *gdbarch, struct bp_target_info *bp_tgt)
void set_gdbarch_memory_insert_breakpoint (struct gdbarch *gdbarch, gdbarch_memory_insert_breakpoint_ftype memory_insert_breakpoint)
int gdbarch_memory_remove_breakpoint (struct gdbarch *gdbarch, struct bp_target_info *bp_tgt)
void set_gdbarch_memory_remove_breakpoint (struct gdbarch *gdbarch, gdbarch_memory_remove_breakpoint_ftype memory_remove_breakpoint)
CORE_ADDR gdbarch_decr_pc_after_break (struct gdbarch *gdbarch)
void set_gdbarch_decr_pc_after_break (struct gdbarch *gdbarch, CORE_ADDR decr_pc_after_break)
CORE_ADDR gdbarch_deprecated_function_start_offset (struct gdbarch *gdbarch)
void set_gdbarch_deprecated_function_start_offset (struct gdbarch *gdbarch, CORE_ADDR deprecated_function_start_offset)
int gdbarch_remote_register_number (struct gdbarch *gdbarch, int regno)
void set_gdbarch_remote_register_number (struct gdbarch *gdbarch, gdbarch_remote_register_number_ftype remote_register_number)
int gdbarch_fetch_tls_load_module_address_p (struct gdbarch *gdbarch)
CORE_ADDR gdbarch_fetch_tls_load_module_address (struct gdbarch *gdbarch, struct objfile *objfile)
void set_gdbarch_fetch_tls_load_module_address (struct gdbarch *gdbarch, gdbarch_fetch_tls_load_module_address_ftype fetch_tls_load_module_address)
CORE_ADDR gdbarch_frame_args_skip (struct gdbarch *gdbarch)
void set_gdbarch_frame_args_skip (struct gdbarch *gdbarch, CORE_ADDR frame_args_skip)
int gdbarch_unwind_pc_p (struct gdbarch *gdbarch)
CORE_ADDR gdbarch_unwind_pc (struct gdbarch *gdbarch, struct frame_info *next_frame)
void set_gdbarch_unwind_pc (struct gdbarch *gdbarch, gdbarch_unwind_pc_ftype unwind_pc)
int gdbarch_unwind_sp_p (struct gdbarch *gdbarch)
CORE_ADDR gdbarch_unwind_sp (struct gdbarch *gdbarch, struct frame_info *next_frame)
void set_gdbarch_unwind_sp (struct gdbarch *gdbarch, gdbarch_unwind_sp_ftype unwind_sp)
int gdbarch_frame_num_args_p (struct gdbarch *gdbarch)
int gdbarch_frame_num_args (struct gdbarch *gdbarch, struct frame_info *frame)
void set_gdbarch_frame_num_args (struct gdbarch *gdbarch, gdbarch_frame_num_args_ftype frame_num_args)
int gdbarch_frame_align_p (struct gdbarch *gdbarch)
CORE_ADDR gdbarch_frame_align (struct gdbarch *gdbarch, CORE_ADDR address)
void set_gdbarch_frame_align (struct gdbarch *gdbarch, gdbarch_frame_align_ftype frame_align)
int gdbarch_stabs_argument_has_addr (struct gdbarch *gdbarch, struct type *type)
void set_gdbarch_stabs_argument_has_addr (struct gdbarch *gdbarch, gdbarch_stabs_argument_has_addr_ftype stabs_argument_has_addr)
int gdbarch_frame_red_zone_size (struct gdbarch *gdbarch)
void set_gdbarch_frame_red_zone_size (struct gdbarch *gdbarch, int frame_red_zone_size)
CORE_ADDR gdbarch_convert_from_func_ptr_addr (struct gdbarch *gdbarch, CORE_ADDR addr, struct target_ops *targ)
void set_gdbarch_convert_from_func_ptr_addr (struct gdbarch *gdbarch, gdbarch_convert_from_func_ptr_addr_ftype convert_from_func_ptr_addr)
CORE_ADDR gdbarch_addr_bits_remove (struct gdbarch *gdbarch, CORE_ADDR addr)
void set_gdbarch_addr_bits_remove (struct gdbarch *gdbarch, gdbarch_addr_bits_remove_ftype addr_bits_remove)
int gdbarch_software_single_step_p (struct gdbarch *gdbarch)
int gdbarch_software_single_step (struct gdbarch *gdbarch, struct frame_info *frame)
void set_gdbarch_software_single_step (struct gdbarch *gdbarch, gdbarch_software_single_step_ftype software_single_step)
int gdbarch_single_step_through_delay_p (struct gdbarch *gdbarch)
int gdbarch_single_step_through_delay (struct gdbarch *gdbarch, struct frame_info *frame)
void set_gdbarch_single_step_through_delay (struct gdbarch *gdbarch, gdbarch_single_step_through_delay_ftype single_step_through_delay)
int gdbarch_print_insn (struct gdbarch *gdbarch, bfd_vma vma, struct disassemble_info *info)
void set_gdbarch_print_insn (struct gdbarch *gdbarch, gdbarch_print_insn_ftype print_insn)
CORE_ADDR gdbarch_skip_trampoline_code (struct gdbarch *gdbarch, struct frame_info *frame, CORE_ADDR pc)
void set_gdbarch_skip_trampoline_code (struct gdbarch *gdbarch, gdbarch_skip_trampoline_code_ftype skip_trampoline_code)
CORE_ADDR gdbarch_skip_solib_resolver (struct gdbarch *gdbarch, CORE_ADDR pc)
void set_gdbarch_skip_solib_resolver (struct gdbarch *gdbarch, gdbarch_skip_solib_resolver_ftype skip_solib_resolver)
int gdbarch_in_solib_return_trampoline (struct gdbarch *gdbarch, CORE_ADDR pc, const char *name)
void set_gdbarch_in_solib_return_trampoline (struct gdbarch *gdbarch, gdbarch_in_solib_return_trampoline_ftype in_solib_return_trampoline)
int gdbarch_in_function_epilogue_p (struct gdbarch *gdbarch, CORE_ADDR addr)
void set_gdbarch_in_function_epilogue_p (struct gdbarch *gdbarch, gdbarch_in_function_epilogue_p_ftype in_function_epilogue_p)
void gdbarch_elf_make_msymbol_special (struct gdbarch *gdbarch, asymbol *sym, struct minimal_symbol *msym)
void set_gdbarch_elf_make_msymbol_special (struct gdbarch *gdbarch, gdbarch_elf_make_msymbol_special_ftype elf_make_msymbol_special)
void gdbarch_coff_make_msymbol_special (struct gdbarch *gdbarch, int val, struct minimal_symbol *msym)
void set_gdbarch_coff_make_msymbol_special (struct gdbarch *gdbarch, gdbarch_coff_make_msymbol_special_ftype coff_make_msymbol_special)
int gdbarch_cannot_step_breakpoint (struct gdbarch *gdbarch)
void set_gdbarch_cannot_step_breakpoint (struct gdbarch *gdbarch, int cannot_step_breakpoint)
int gdbarch_have_nonsteppable_watchpoint (struct gdbarch *gdbarch)
void set_gdbarch_have_nonsteppable_watchpoint (struct gdbarch *gdbarch, int have_nonsteppable_watchpoint)
int gdbarch_address_class_type_flags_p (struct gdbarch *gdbarch)
int gdbarch_address_class_type_flags (struct gdbarch *gdbarch, int byte_size, int dwarf2_addr_class)
void set_gdbarch_address_class_type_flags (struct gdbarch *gdbarch, gdbarch_address_class_type_flags_ftype address_class_type_flags)
int gdbarch_address_class_type_flags_to_name_p (struct gdbarch *gdbarch)
const char * gdbarch_address_class_type_flags_to_name (struct gdbarch *gdbarch, int type_flags)
void set_gdbarch_address_class_type_flags_to_name (struct gdbarch *gdbarch, gdbarch_address_class_type_flags_to_name_ftype address_class_type_flags_to_name)
int gdbarch_address_class_name_to_type_flags_p (struct gdbarch *gdbarch)
int gdbarch_address_class_name_to_type_flags (struct gdbarch *gdbarch, const char *name, int *type_flags_ptr)
void set_gdbarch_address_class_name_to_type_flags (struct gdbarch *gdbarch, gdbarch_address_class_name_to_type_flags_ftype address_class_name_to_type_flags)
int gdbarch_register_reggroup_p (struct gdbarch *gdbarch, int regnum, struct reggroup *reggroup)
void set_gdbarch_register_reggroup_p (struct gdbarch *gdbarch, gdbarch_register_reggroup_p_ftype register_reggroup_p)
int gdbarch_fetch_pointer_argument_p (struct gdbarch *gdbarch)
CORE_ADDR gdbarch_fetch_pointer_argument (struct gdbarch *gdbarch, struct frame_info *frame, int argi, struct type *type)
void set_gdbarch_fetch_pointer_argument (struct gdbarch *gdbarch, gdbarch_fetch_pointer_argument_ftype fetch_pointer_argument)
int gdbarch_regset_from_core_section_p (struct gdbarch *gdbarch)
struct regset * gdbarch_regset_from_core_section (struct gdbarch *gdbarch, const char *sect_name, size_t sect_size)
void set_gdbarch_regset_from_core_section (struct gdbarch *gdbarch, gdbarch_regset_from_core_section_ftype regset_from_core_section)
struct core_regset_section * gdbarch_core_regset_sections (struct gdbarch *gdbarch)
void set_gdbarch_core_regset_sections (struct gdbarch *gdbarch, struct core_regset_section *core_regset_sections)
int gdbarch_make_corefile_notes_p (struct gdbarch *gdbarch)
char * gdbarch_make_corefile_notes (struct gdbarch *gdbarch, bfd *obfd, int *note_size)
void set_gdbarch_make_corefile_notes (struct gdbarch *gdbarch, gdbarch_make_corefile_notes_ftype make_corefile_notes)
int gdbarch_elfcore_write_linux_prpsinfo_p (struct gdbarch *gdbarch)
char * gdbarch_elfcore_write_linux_prpsinfo (struct gdbarch *gdbarch, bfd *obfd, char *note_data, int *note_size, const struct elf_internal_linux_prpsinfo *info)
void set_gdbarch_elfcore_write_linux_prpsinfo (struct gdbarch *gdbarch, gdbarch_elfcore_write_linux_prpsinfo_ftype elfcore_write_linux_prpsinfo)
int gdbarch_find_memory_regions_p (struct gdbarch *gdbarch)
int gdbarch_find_memory_regions (struct gdbarch *gdbarch, find_memory_region_ftype func, void *data)
void set_gdbarch_find_memory_regions (struct gdbarch *gdbarch, gdbarch_find_memory_regions_ftype find_memory_regions)
int gdbarch_core_xfer_shared_libraries_p (struct gdbarch *gdbarch)
LONGEST gdbarch_core_xfer_shared_libraries (struct gdbarch *gdbarch, gdb_byte *readbuf, ULONGEST offset, LONGEST len)
void set_gdbarch_core_xfer_shared_libraries (struct gdbarch *gdbarch, gdbarch_core_xfer_shared_libraries_ftype core_xfer_shared_libraries)
int gdbarch_core_xfer_shared_libraries_aix_p (struct gdbarch *gdbarch)
LONGEST gdbarch_core_xfer_shared_libraries_aix (struct gdbarch *gdbarch, gdb_byte *readbuf, ULONGEST offset, LONGEST len)
void set_gdbarch_core_xfer_shared_libraries_aix (struct gdbarch *gdbarch, gdbarch_core_xfer_shared_libraries_aix_ftype core_xfer_shared_libraries_aix)
int gdbarch_core_pid_to_str_p (struct gdbarch *gdbarch)
char * gdbarch_core_pid_to_str (struct gdbarch *gdbarch, ptid_t ptid)
void set_gdbarch_core_pid_to_str (struct gdbarch *gdbarch, gdbarch_core_pid_to_str_ftype core_pid_to_str)
int gdbarch_gcore_bfd_target_p (struct gdbarch *gdbarch)
const char * gdbarch_gcore_bfd_target (struct gdbarch *gdbarch)
void set_gdbarch_gcore_bfd_target (struct gdbarch *gdbarch, const char *gcore_bfd_target)
int gdbarch_vtable_function_descriptors (struct gdbarch *gdbarch)
void set_gdbarch_vtable_function_descriptors (struct gdbarch *gdbarch, int vtable_function_descriptors)
int gdbarch_vbit_in_delta (struct gdbarch *gdbarch)
void set_gdbarch_vbit_in_delta (struct gdbarch *gdbarch, int vbit_in_delta)
int gdbarch_skip_permanent_breakpoint_p (struct gdbarch *gdbarch)
void gdbarch_skip_permanent_breakpoint (struct gdbarch *gdbarch, struct regcache *regcache)
void set_gdbarch_skip_permanent_breakpoint (struct gdbarch *gdbarch, gdbarch_skip_permanent_breakpoint_ftype skip_permanent_breakpoint)
int gdbarch_max_insn_length_p (struct gdbarch *gdbarch)
ULONGEST gdbarch_max_insn_length (struct gdbarch *gdbarch)
void set_gdbarch_max_insn_length (struct gdbarch *gdbarch, ULONGEST max_insn_length)
int gdbarch_displaced_step_copy_insn_p (struct gdbarch *gdbarch)
struct displaced_step_closure * gdbarch_displaced_step_copy_insn (struct gdbarch *gdbarch, CORE_ADDR from, CORE_ADDR to, struct regcache *regs)
void set_gdbarch_displaced_step_copy_insn (struct gdbarch *gdbarch, gdbarch_displaced_step_copy_insn_ftype displaced_step_copy_insn)
int gdbarch_displaced_step_hw_singlestep (struct gdbarch *gdbarch, struct displaced_step_closure *closure)
void set_gdbarch_displaced_step_hw_singlestep (struct gdbarch *gdbarch, gdbarch_displaced_step_hw_singlestep_ftype displaced_step_hw_singlestep)
int gdbarch_displaced_step_fixup_p (struct gdbarch *gdbarch)
void gdbarch_displaced_step_fixup (struct gdbarch *gdbarch, struct displaced_step_closure *closure, CORE_ADDR from, CORE_ADDR to, struct regcache *regs)
void set_gdbarch_displaced_step_fixup (struct gdbarch *gdbarch, gdbarch_displaced_step_fixup_ftype displaced_step_fixup)
void gdbarch_displaced_step_free_closure (struct gdbarch *gdbarch, struct displaced_step_closure *closure)
void set_gdbarch_displaced_step_free_closure (struct gdbarch *gdbarch, gdbarch_displaced_step_free_closure_ftype displaced_step_free_closure)
CORE_ADDR gdbarch_displaced_step_location (struct gdbarch *gdbarch)
void set_gdbarch_displaced_step_location (struct gdbarch *gdbarch, gdbarch_displaced_step_location_ftype displaced_step_location)
int gdbarch_relocate_instruction_p (struct gdbarch *gdbarch)
void gdbarch_relocate_instruction (struct gdbarch *gdbarch, CORE_ADDR *to, CORE_ADDR from)
void set_gdbarch_relocate_instruction (struct gdbarch *gdbarch, gdbarch_relocate_instruction_ftype relocate_instruction)
int gdbarch_overlay_update_p (struct gdbarch *gdbarch)
void gdbarch_overlay_update (struct gdbarch *gdbarch, struct obj_section *osect)
void set_gdbarch_overlay_update (struct gdbarch *gdbarch, gdbarch_overlay_update_ftype overlay_update)
int gdbarch_core_read_description_p (struct gdbarch *gdbarch)
struct target_desc * gdbarch_core_read_description (struct gdbarch *gdbarch, struct target_ops *target, bfd *abfd)
void set_gdbarch_core_read_description (struct gdbarch *gdbarch, gdbarch_core_read_description_ftype core_read_description)
int gdbarch_static_transform_name_p (struct gdbarch *gdbarch)
const char * gdbarch_static_transform_name (struct gdbarch *gdbarch, const char *name)
void set_gdbarch_static_transform_name (struct gdbarch *gdbarch, gdbarch_static_transform_name_ftype static_transform_name)
int gdbarch_sofun_address_maybe_missing (struct gdbarch *gdbarch)
void set_gdbarch_sofun_address_maybe_missing (struct gdbarch *gdbarch, int sofun_address_maybe_missing)
int gdbarch_process_record_p (struct gdbarch *gdbarch)
int gdbarch_process_record (struct gdbarch *gdbarch, struct regcache *regcache, CORE_ADDR addr)
void set_gdbarch_process_record (struct gdbarch *gdbarch, gdbarch_process_record_ftype process_record)
int gdbarch_process_record_signal_p (struct gdbarch *gdbarch)
int gdbarch_process_record_signal (struct gdbarch *gdbarch, struct regcache *regcache, enum gdb_signal signal)
void set_gdbarch_process_record_signal (struct gdbarch *gdbarch, gdbarch_process_record_signal_ftype process_record_signal)
int gdbarch_gdb_signal_from_target_p (struct gdbarch *gdbarch)
enum gdb_signal gdbarch_gdb_signal_from_target (struct gdbarch *gdbarch, int signo)
void set_gdbarch_gdb_signal_from_target (struct gdbarch *gdbarch, gdbarch_gdb_signal_from_target_ftype gdb_signal_from_target)
int gdbarch_gdb_signal_to_target_p (struct gdbarch *gdbarch)
int gdbarch_gdb_signal_to_target (struct gdbarch *gdbarch, enum gdb_signal signal)
void set_gdbarch_gdb_signal_to_target (struct gdbarch *gdbarch, gdbarch_gdb_signal_to_target_ftype gdb_signal_to_target)
int gdbarch_get_siginfo_type_p (struct gdbarch *gdbarch)
struct type * gdbarch_get_siginfo_type (struct gdbarch *gdbarch)
void set_gdbarch_get_siginfo_type (struct gdbarch *gdbarch, gdbarch_get_siginfo_type_ftype get_siginfo_type)
int gdbarch_record_special_symbol_p (struct gdbarch *gdbarch)
void gdbarch_record_special_symbol (struct gdbarch *gdbarch, struct objfile *objfile, asymbol *sym)
void set_gdbarch_record_special_symbol (struct gdbarch *gdbarch, gdbarch_record_special_symbol_ftype record_special_symbol)
int gdbarch_get_syscall_number_p (struct gdbarch *gdbarch)
LONGEST gdbarch_get_syscall_number (struct gdbarch *gdbarch, ptid_t ptid)
void set_gdbarch_get_syscall_number (struct gdbarch *gdbarch, gdbarch_get_syscall_number_ftype get_syscall_number)
const char * gdbarch_stap_integer_prefix (struct gdbarch *gdbarch)
void set_gdbarch_stap_integer_prefix (struct gdbarch *gdbarch, const char *stap_integer_prefix)
const char * gdbarch_stap_integer_suffix (struct gdbarch *gdbarch)
void set_gdbarch_stap_integer_suffix (struct gdbarch *gdbarch, const char *stap_integer_suffix)
const char * gdbarch_stap_register_prefix (struct gdbarch *gdbarch)
void set_gdbarch_stap_register_prefix (struct gdbarch *gdbarch, const char *stap_register_prefix)
const char * gdbarch_stap_register_suffix (struct gdbarch *gdbarch)
void set_gdbarch_stap_register_suffix (struct gdbarch *gdbarch, const char *stap_register_suffix)
const char * gdbarch_stap_register_indirection_prefix (struct gdbarch *gdbarch)
void set_gdbarch_stap_register_indirection_prefix (struct gdbarch *gdbarch, const char *stap_register_indirection_prefix)
const char * gdbarch_stap_register_indirection_suffix (struct gdbarch *gdbarch)
void set_gdbarch_stap_register_indirection_suffix (struct gdbarch *gdbarch, const char *stap_register_indirection_suffix)
const char * gdbarch_stap_gdb_register_prefix (struct gdbarch *gdbarch)
void set_gdbarch_stap_gdb_register_prefix (struct gdbarch *gdbarch, const char *stap_gdb_register_prefix)
const char * gdbarch_stap_gdb_register_suffix (struct gdbarch *gdbarch)
void set_gdbarch_stap_gdb_register_suffix (struct gdbarch *gdbarch, const char *stap_gdb_register_suffix)
int gdbarch_stap_is_single_operand_p (struct gdbarch *gdbarch)
int gdbarch_stap_is_single_operand (struct gdbarch *gdbarch, const char *s)
void set_gdbarch_stap_is_single_operand (struct gdbarch *gdbarch, gdbarch_stap_is_single_operand_ftype stap_is_single_operand)
int gdbarch_stap_parse_special_token_p (struct gdbarch *gdbarch)
int gdbarch_stap_parse_special_token (struct gdbarch *gdbarch, struct stap_parse_info *p)
void set_gdbarch_stap_parse_special_token (struct gdbarch *gdbarch, gdbarch_stap_parse_special_token_ftype stap_parse_special_token)
int gdbarch_has_global_solist (struct gdbarch *gdbarch)
void set_gdbarch_has_global_solist (struct gdbarch *gdbarch, int has_global_solist)
int gdbarch_has_global_breakpoints (struct gdbarch *gdbarch)
void set_gdbarch_has_global_breakpoints (struct gdbarch *gdbarch, int has_global_breakpoints)
int gdbarch_has_shared_address_space (struct gdbarch *gdbarch)
void set_gdbarch_has_shared_address_space (struct gdbarch *gdbarch, gdbarch_has_shared_address_space_ftype has_shared_address_space)
int gdbarch_fast_tracepoint_valid_at (struct gdbarch *gdbarch, CORE_ADDR addr, int *isize, char **msg)
void set_gdbarch_fast_tracepoint_valid_at (struct gdbarch *gdbarch, gdbarch_fast_tracepoint_valid_at_ftype fast_tracepoint_valid_at)
const char * gdbarch_auto_charset (struct gdbarch *gdbarch)
void set_gdbarch_auto_charset (struct gdbarch *gdbarch, gdbarch_auto_charset_ftype auto_charset)
const char * gdbarch_auto_wide_charset (struct gdbarch *gdbarch)
void set_gdbarch_auto_wide_charset (struct gdbarch *gdbarch, gdbarch_auto_wide_charset_ftype auto_wide_charset)
const char * gdbarch_solib_symbols_extension (struct gdbarch *gdbarch)
void set_gdbarch_solib_symbols_extension (struct gdbarch *gdbarch, const char *solib_symbols_extension)
int gdbarch_has_dos_based_file_system (struct gdbarch *gdbarch)
void set_gdbarch_has_dos_based_file_system (struct gdbarch *gdbarch, int has_dos_based_file_system)
void gdbarch_gen_return_address (struct gdbarch *gdbarch, struct agent_expr *ax, struct axs_value *value, CORE_ADDR scope)
void set_gdbarch_gen_return_address (struct gdbarch *gdbarch, gdbarch_gen_return_address_ftype gen_return_address)
int gdbarch_info_proc_p (struct gdbarch *gdbarch)
void gdbarch_info_proc (struct gdbarch *gdbarch, char *args, enum info_proc_what what)
void set_gdbarch_info_proc (struct gdbarch *gdbarch, gdbarch_info_proc_ftype info_proc)
int gdbarch_core_info_proc_p (struct gdbarch *gdbarch)
void gdbarch_core_info_proc (struct gdbarch *gdbarch, char *args, enum info_proc_what what)
void set_gdbarch_core_info_proc (struct gdbarch *gdbarch, gdbarch_core_info_proc_ftype core_info_proc)
void gdbarch_iterate_over_objfiles_in_search_order (struct gdbarch *gdbarch, iterate_over_objfiles_in_search_order_cb_ftype *cb, void *cb_data, struct objfile *current_objfile)
void set_gdbarch_iterate_over_objfiles_in_search_order (struct gdbarch *gdbarch, gdbarch_iterate_over_objfiles_in_search_order_ftype iterate_over_objfiles_in_search_order)
struct ravenscar_arch_ops * gdbarch_ravenscar_ops (struct gdbarch *gdbarch)
void set_gdbarch_ravenscar_ops (struct gdbarch *gdbarch, struct ravenscar_arch_ops *ravenscar_ops)
static struct gdbarch_data * gdbarch_data_register (gdbarch_data_pre_init_ftype *pre_init, gdbarch_data_post_init_ftype *post_init)
struct gdbarch_data * gdbarch_data_register_pre_init (gdbarch_data_pre_init_ftype *pre_init)
struct gdbarch_data * gdbarch_data_register_post_init (gdbarch_data_post_init_ftype *post_init)
void deprecated_set_gdbarch_data (struct gdbarch *gdbarch, struct gdbarch_data *data, void *pointer)
void * gdbarch_data (struct gdbarch *gdbarch, struct gdbarch_data *data)
static void append_name (const char ***buf, int *nr, const char *name)
const char ** gdbarch_printable_names (void)
void gdbarch_register (enum bfd_architecture bfd_architecture, gdbarch_init_ftype *init, gdbarch_dump_tdep_ftype *dump_tdep)
void register_gdbarch_init (enum bfd_architecture bfd_architecture, gdbarch_init_ftype *init)
struct gdbarch_list * gdbarch_list_lookup_by_info (struct gdbarch_list *arches, const struct gdbarch_info *info)
struct gdbarch * gdbarch_find_by_info (struct gdbarch_info info)
void set_target_gdbarch (struct gdbarch *new_gdbarch)
struct gdbarch * target_gdbarch (void)
void _initialize_gdbarch (void)
Variables
unsigned int gdbarch_debug = GDBARCH_DEBUG
struct bfd_arch_info bfd_default_arch_struct
struct gdbarch startup_gdbarch
struct gdbarch_data_registry gdbarch_data_registry
static struct
gdbarch_registration * gdbarch_registry = NULL
Define Documentation
#define GDBARCH_DEBUG 0
Definition at line 61 of file gdbarch.c.
Function Documentation
void _initialize_gdbarch (void)
static void alloc_gdbarch_data (struct gdbarch * gdbarch) [static]
Definition at line 4489 of file gdbarch.c.
References gdbarch::data, gdb_assert, GDBARCH_OBSTACK_CALLOC, gdbarch_data_registry::nr, and gdbarch::nr_data.
Referenced by gdbarch_alloc().
static void append_name (const char *** buf, int * nr, const char * name) [static]
Definition at line 4564 of file gdbarch.c.
References name, and xrealloc().
Referenced by gdbarch_printable_names().
void deprecated_set_gdbarch_data (struct gdbarch * gdbarch, struct gdbarch_data * data, void * pointer)
Definition at line 4500 of file gdbarch.c.
References gdbarch::data, gdb_assert, gdbarch_data::index, gdbarch::nr_data, and gdbarch_data::pre_init.
Referenced by libunwind_frame_set_descr(), reggroup_add(), and user_reg_add().
int gdbarch_addr_bit (struct gdbarch * gdbarch)
Definition at line 1735 of file gdbarch.c.
References gdbarch::addr_bit, fprintf_unfiltered(), gdb_assert, gdb_stdlog, and gdbarch_debug.
Referenced by aarch64_analyze_prologue(), amd64_linux_siginfo_fixup(), append_resumption(), arm_analyze_prologue(), breakpoint_address_bits(), darwin_debug_regions_recurse(), enable_break(), find_frame_addr_in_frame_chain(), i386_show_dr(), info_mappings_callback(), info_probes_for_ops(), info_static_tracepoint_markers_command(), irix_current_sos(), irix_open_symbol_file_object(), linux_core_info_proc_mappings(), linux_info_proc(), linux_xfer_partial(), m32c_analyze_prologue(), m32r_load_section(), mem_info_command(), mep_analyze_prologue(), mips_common_breakpoint(), mips_request(), mn10300_analyze_prologue(), monitor_vsprintf(), msp430_analyze_prologue(), objfile_type(), paddress(), print_bfd_section_info(), print_core_address(), print_msymbol_info(), print_objfile_section_info(), print_one_static_tracepoint_marker(), print_scalar_formatted(), print_section_info(), read_subrange_type(), remote_address_masked(), remote_check_symbols(), remote_flash_erase(), remote_search_memory(), rl78_analyze_prologue(), rx_analyze_prologue(), s390_analyze_prologue(), stap_get_expected_argument_type(), thumb_analyze_prologue(), tilegx_linux_init_abi(), and value_cast().
CORE_ADDR gdbarch_addr_bits_remove (struct gdbarch * gdbarch, CORE_ADDR addr)
Definition at line 3003 of file gdbarch.c.
References gdbarch::addr_bits_remove, fprintf_unfiltered(), gdb_assert, gdb_stdlog, and gdbarch_debug.
Referenced by arm_adjust_breakpoint_address(), arm_insert_single_step_breakpoint(), arm_linux_restart_syscall_init(), arm_linux_supply_gregset(), arm_scan_prologue(), arm_supply_gregset(), arm_symbian_skip_trampoline_code(), build_address_symbolic(), coff_symtab_read(), do_one_display(), dwarf_decode_lines_1(), enable_break(), enter_line_range(), enter_linenos(), exec_entry_point(), fetch_register(), fetch_regs(), generic_load(), heuristic_proc_start(), hppa_find_unwind_entry_in_block(), init_entry_point_info(), insert_hp_step_resume_breakpoint_at_frame(), insert_step_resume_breakpoint_at_caller(), mips_common_breakpoint(), monitor_insert_breakpoint(), monitor_read_memory(), monitor_write_memory(), print_section_info(), process_one_symbol(), psymtab_to_symtab_1(), record_minimal_symbol(), regcache_read_pc(), s390_dummy_id(), s390_prologue_frame_unwind_cache(), s390_push_dummy_call(), s390_unwind_pc(), s390_unwind_sp(), som_symtab_read(), store_register(), store_regs(), and value_as_address().
int gdbarch_address_class_name_to_type_flags (struct gdbarch * gdbarch, const char * name, int * type_flags_ptr)
Definition at line 3276 of file gdbarch.c.
References gdbarch::address_class_name_to_type_flags, fprintf_unfiltered(), gdb_assert, gdb_stdlog, and gdbarch_debug.
Referenced by address_space_name_to_int().
int gdbarch_address_class_name_to_type_flags_p (struct gdbarch * gdbarch)
Definition at line 3269 of file gdbarch.c.
References gdbarch::address_class_name_to_type_flags, and gdb_assert.
Referenced by address_space_name_to_int(), and gdbarch_dump().
int gdbarch_address_class_type_flags (struct gdbarch * gdbarch, int byte_size, int dwarf2_addr_class)
Definition at line 3228 of file gdbarch.c.
References gdbarch::address_class_type_flags, fprintf_unfiltered(), gdb_assert, gdb_stdlog, and gdbarch_debug.
Referenced by read_tag_pointer_type().
int gdbarch_address_class_type_flags_p (struct gdbarch * gdbarch)
Definition at line 3221 of file gdbarch.c.
References gdbarch::address_class_type_flags, and gdb_assert.
Referenced by gdbarch_dump(), and read_tag_pointer_type().
const char* gdbarch_address_class_type_flags_to_name (struct gdbarch * gdbarch, int type_flags)
Definition at line 3252 of file gdbarch.c.
References gdbarch::address_class_type_flags_to_name, fprintf_unfiltered(), gdb_assert, gdb_stdlog, and gdbarch_debug.
Referenced by address_space_int_to_name().
int gdbarch_address_class_type_flags_to_name_p (struct gdbarch * gdbarch)
Definition at line 3245 of file gdbarch.c.
References gdbarch::address_class_type_flags_to_name, and gdb_assert.
Referenced by address_space_int_to_name(), and gdbarch_dump().
void gdbarch_address_to_pointer (struct gdbarch * gdbarch, struct type * type, gdb_byte * buf, CORE_ADDR addr)
Definition at line 2533 of file gdbarch.c.
References gdbarch::address_to_pointer, fprintf_unfiltered(), gdb_assert, gdb_stdlog, and gdbarch_debug.
Referenced by store_typed_address(), value_of_builtin_frame_fp_reg(), value_of_builtin_frame_pc_reg(), and value_pointer().
CORE_ADDR gdbarch_adjust_breakpoint_address (struct gdbarch * gdbarch, CORE_ADDR bpaddr)
Definition at line 2714 of file gdbarch.c.
References gdbarch::adjust_breakpoint_address, fprintf_unfiltered(), gdb_assert, gdb_stdlog, and gdbarch_debug.
Referenced by adjust_breakpoint_address(), and handle_step_into_function().
int gdbarch_adjust_breakpoint_address_p (struct gdbarch * gdbarch)
Definition at line 2707 of file gdbarch.c.
References gdbarch::adjust_breakpoint_address, and gdb_assert.
Referenced by adjust_breakpoint_address(), gdbarch_dump(), and handle_step_into_function().
struct gdbarch* gdbarch_alloc (const struct gdbarch_info * info, struct gdbarch_tdep * tdep) [read]
Definition at line 472 of file gdbarch.c.
References gdbarch::addr_bits_remove, gdbarch::address_to_pointer, alloc_gdbarch_data(), AT_ENTRY_POINT, gdbarch::auto_charset, gdbarch::auto_wide_charset, gdbarch::bfd_arch_info, gdbarch_info::bfd_arch_info, gdbarch::bits_big_endian, gdbarch::byte_order, gdbarch_info::byte_order, gdbarch::byte_order_for_code, gdbarch_info::byte_order_for_code, gdbarch::call_dummy_location, gdbarch::cannot_fetch_register, cannot_register_not(), gdbarch::cannot_store_register, gdbarch::char_signed, gdbarch::coff_make_msymbol_special, gdbarch::convert_from_func_ptr_addr, convert_from_func_ptr_addr_identity, gdbarch::convert_register_p, core_addr_identity(), default_auto_charset(), default_auto_wide_charset(), default_coff_make_msymbol_special(), default_displaced_step_hw_singlestep(), default_elf_make_msymbol_special(), default_fast_tracepoint_valid_at(), default_gen_return_address(), default_has_shared_address_space(), default_iterate_over_objfiles_in_search_order(), default_memory_insert_breakpoint(), default_memory_remove_breakpoint(), default_print_registers_info(), default_register_reggroup_p(), default_remote_breakpoint_from_pc(), default_remote_register_number(), default_return_in_first_hidden_param_p(), default_stabs_argument_has_addr(), default_value_from_register(), gdbarch::deprecated_fp_regnum, gdbarch::displaced_step_fixup, gdbarch::displaced_step_free_closure, gdbarch::displaced_step_hw_singlestep, gdbarch::displaced_step_location, gdbarch::double_bit, gdbarch::dwarf2_reg_to_regnum, gdbarch::ecoff_reg_to_regnum, gdbarch::elf_make_msymbol_special, gdbarch::fast_tracepoint_valid_at, gdbarch::float_bit, gdbarch::fp0_regnum, gdbarch::gen_return_address, generic_convert_register_p(), generic_in_function_epilogue_p(), generic_in_solib_return_trampoline(), generic_skip_solib_resolver(), generic_skip_trampoline_code(), gdbarch::half_bit, gdbarch::has_shared_address_space, gdbarch::in_function_epilogue_p, gdbarch::in_solib_return_trampoline, gdbarch::int_bit, gdbarch::iterate_over_objfiles_in_search_order, legacy_register_sim_regno(), legacy_virtual_frame_pointer, gdbarch::long_bit, gdbarch::long_double_bit, gdbarch::long_long_align_bit, gdbarch::long_long_bit, gdbarch::memory_insert_breakpoint, gdbarch::memory_remove_breakpoint, memset(), no_op_reg_to_regnum(), gdbarch::num_regs, gdbarch::obstack, gdbarch::osabi, gdbarch_info::osabi, gdbarch::pc_regnum, gdbarch::pointer_to_address, gdbarch::print_registers_info, gdbarch::ps_regnum, gdbarch::ptr_bit, gdbarch::ravenscar_ops, gdbarch::register_reggroup_p, gdbarch::register_sim_regno, gdbarch::relocate_instruction, gdbarch::remote_breakpoint_from_pc, gdbarch::remote_register_number, gdbarch::return_in_first_hidden_param_p, gdbarch::sdb_reg_to_regnum, gdbarch::short_bit, gdbarch::skip_solib_resolver, gdbarch::skip_trampoline_code, gdbarch::sp_regnum, gdbarch::stab_reg_to_regnum, gdbarch::stabs_argument_has_addr, gdbarch::target_desc, gdbarch_info::target_desc, gdbarch::tdep, unsigned_address_to_pointer(), unsigned_pointer_to_address(), gdbarch::value_from_register, gdbarch::virtual_frame_pointer, and XMALLOC.
Referenced by aarch64_gdbarch_init(), alpha_gdbarch_init(), arm_gdbarch_init(), avr_gdbarch_init(), bfin_gdbarch_init(), cris_gdbarch_init(), frv_gdbarch_init(), h8300_gdbarch_init(), hppa_gdbarch_init(), i386_gdbarch_init(), ia64_gdbarch_init(), iq2000_gdbarch_init(), lm32_gdbarch_init(), m32c_gdbarch_init(), m32r_gdbarch_init(), m68hc11_gdbarch_init(), m68k_gdbarch_init(), m88k_gdbarch_init(), mep_gdbarch_init(), microblaze_gdbarch_init(), mips_gdbarch_init(), mn10300_gdbarch_init(), moxie_gdbarch_init(), msp430_gdbarch_init(), mt_gdbarch_init(), nios2_gdbarch_init(), rl78_gdbarch_init(), rs6000_gdbarch_init(), rx_gdbarch_init(), s390_gdbarch_init(), score_gdbarch_init(), sh64_gdbarch_init(), sh_gdbarch_init(), sparc32_gdbarch_init(), spu_gdbarch_init(), tic6x_gdbarch_init(), tilegx_gdbarch_init(), v850_gdbarch_init(), vax_gdbarch_init(), xstormy16_gdbarch_init(), and xtensa_gdbarch_init().
const char* gdbarch_auto_charset (struct gdbarch * gdbarch)
Definition at line 4260 of file gdbarch.c.
References gdbarch::auto_charset, fprintf_unfiltered(), gdb_assert, gdb_stdlog, and gdbarch_debug.
Referenced by show_target_charset_name(), and target_charset().
const char* gdbarch_auto_wide_charset (struct gdbarch * gdbarch)
Definition at line 4277 of file gdbarch.c.
References gdbarch::auto_wide_charset, fprintf_unfiltered(), gdb_assert, gdb_stdlog, and gdbarch_debug.
Referenced by set_be_le_names(), show_target_wide_charset_name(), target_wide_charset(), and validate().
int gdbarch_ax_pseudo_register_collect (struct gdbarch * gdbarch, struct agent_expr * ax, int reg)
Definition at line 1968 of file gdbarch.c.
References gdbarch::ax_pseudo_register_collect, fprintf_unfiltered(), gdb_assert, gdb_stdlog, and gdbarch_debug.
Referenced by ax_reg_mask().
int gdbarch_ax_pseudo_register_collect_p (struct gdbarch * gdbarch)
Definition at line 1961 of file gdbarch.c.
References gdbarch::ax_pseudo_register_collect, and gdb_assert.
Referenced by ax_reg_mask(), and gdbarch_dump().
int gdbarch_ax_pseudo_register_push_stack (struct gdbarch * gdbarch, struct agent_expr * ax, int reg)
Definition at line 1992 of file gdbarch.c.
References gdbarch::ax_pseudo_register_push_stack, fprintf_unfiltered(), gdb_assert, gdb_stdlog, and gdbarch_debug.
Referenced by ax_reg().
int gdbarch_ax_pseudo_register_push_stack_p (struct gdbarch * gdbarch)
Definition at line 1985 of file gdbarch.c.
References gdbarch::ax_pseudo_register_push_stack, and gdb_assert.
Referenced by ax_reg(), and gdbarch_dump().
int gdbarch_believe_pcc_promotion (struct gdbarch * gdbarch)
Definition at line 2432 of file gdbarch.c.
References gdbarch::believe_pcc_promotion, fprintf_unfiltered(), gdb_assert, gdb_stdlog, and gdbarch_debug.
Referenced by define_symbol().
struct bfd_arch_info* gdbarch_bfd_arch_info (struct gdbarch * gdbarch) [read]
Definition at line 1439 of file gdbarch.c.
References gdbarch::bfd_arch_info, fprintf_unfiltered(), gdb_assert, gdb_stdlog, and gdbarch_debug.
Referenced by amd64_collect_fxsave(), amd64_collect_native_gregset(), amd64_collect_xsave(), amd64_linux_siginfo_fixup(), amd64_native_gregset_reg_offset(), amd64_supply_fxsave(), amd64_supply_native_gregset(), amd64_supply_xsave(), archpy_name(), arm_show_abi(), arm_update_current_architecture(), darwin_bfd_open(), darwin_solib_get_all_image_info_addr_at_init(), debug_to_thread_architecture(), default_gcore_arch(), default_gcore_mach(), dwarf_expr_reg_to_entry_parameter(), frame_unwind_arch(), gdb_buffered_insn_length_init_dis(), gdb_disassemble_info(), gdbarch_dump(), gdbarch_update_p(), info_spu_dma_command(), info_spu_event_command(), info_spu_mailbox_command(), info_spu_proxydma_command(), info_spu_signal_command(), is_h8300_normal_mode(), is_h8300hmode(), is_h8300smode(), is_h8300sxmode(), is_octeon(), jit_bfd_try_read_symtab(), m32c_analyze_prologue(), m32c_is_1st_arg_reg(), m32c_is_arg_reg(), m32c_push_dummy_call(), m32c_sb_read(), m32c_sb_write(), make_regs(), make_types(), mips_isa_regsize(), msp430_gdbarch_init(), mt_breakpoint_from_pc(), mt_copro_register_type(), mt_pseudo_register_read(), mt_pseudo_register_write(), mt_registers_info(), nto_find_and_open_solib(), nto_init_solib_absolute_prefix(), parse_spufs_run(), ppu2spu_sniffer(), procfs_open(), ps_get_thread_area(), sh_in_function_epilogue_p(), show_architecture(), show_fp_model(), show_mips_abi(), show_mipsfpu_command(), skip_prologue(), solib_bfd_open(), spu2ppu_sniffer(), spu_fetch_registers(), spu_objfile_from_frame(), and spu_store_registers().
int gdbarch_bits_big_endian (struct gdbarch * gdbarch)
Definition at line 1484 of file gdbarch.c.
References gdbarch::bits_big_endian, fprintf_unfiltered(), gdb_assert, gdb_stdlog, and gdbarch_debug.
Referenced by access_memory(), ada_value_assign(), ada_value_primitive_packed_val(), decode_constrained_packed_array(), dwarf2_add_field(), dwarf2_compile_expr_to_ax(), evaluate_subexp_standard(), modify_field(), read_pieced_value(), tdesc_gdb_type(), unpack_value_bits_as_long_1(), value_assign_to_component(), value_bit_index(), and write_pieced_value().
const gdb_byte* gdbarch_breakpoint_from_pc (struct gdbarch * gdbarch, CORE_ADDR * pcptr, int * lenptr)
Definition at line 2673 of file gdbarch.c.
References gdbarch::breakpoint_from_pc, fprintf_unfiltered(), gdb_assert, gdb_stdlog, and gdbarch_debug.
Referenced by bp_loc_is_permanent(), breakpoint_xfer_memory(), call_function_by_hand(), default_memory_insert_breakpoint(), default_remote_breakpoint_from_pc(), displaced_step_at_entry_point(), microblaze_linux_memory_remove_breakpoint(), monitor_insert_breakpoint(), and ppc_linux_memory_remove_breakpoint().
int gdbarch_byte_order (struct gdbarch * gdbarch)
Definition at line 1448 of file gdbarch.c.
References gdbarch::byte_order, fprintf_unfiltered(), gdb_assert, gdb_stdlog, and gdbarch_debug.
Referenced by aarch64_extract_return_value(), aarch64_get_longjmp_target(), aarch64_scan_prologue(), aarch64_store_return_value(), ada_val_print_array(), ada_value_binop(), address_to_signed_pointer(), agent_capability_check(), agent_get_helper_thread_id(), alpha_extract_return_value(), alpha_get_longjmp_target(), alpha_lds(), alpha_osf1_sigcontext_addr(), alpha_push_dummy_call(), alpha_read_insn(), alpha_sts(), amd64_analyze_prologue(), amd64_darwin_sigcontext_addr(), amd64_displaced_step_fixup(), amd64_epilogue_frame_cache(), amd64_frame_cache_1(), amd64_linux_get_syscall_number(), amd64_linux_sigcontext_addr(), amd64_push_dummy_call(), amd64_relocate_instruction(), amd64_sigtramp_frame_cache(), amd64_skip_main_prologue(), amd64_windows_find_unwind_info(), amd64_windows_frame_cache(), amd64_windows_frame_decode_epilogue(), amd64_windows_frame_decode_insns(), amd64_windows_frame_prev_register(), amd64_windows_push_dummy_call(), amd64_windows_skip_trampoline_code(), amd64obsd_collect_uthread(), amd64obsd_supply_uthread(), amd64obsd_trapframe_cache(), arm_analyze_prologue(), arm_catch_kernel_helper_return(), arm_extract_return_value(), arm_get_longjmp_target(), arm_get_next_pc_raw(), arm_linux_rt_sigreturn_init(), arm_linux_sigreturn_init(), arm_linux_supply_gregset(), arm_m_exception_cache(), arm_neon_quad_read(), arm_neon_quad_write(), arm_pe_skip_trampoline_code(), arm_process_record(), arm_pseudo_read(), arm_pseudo_write(), arm_push_dummy_call(), arm_scan_prologue(), arm_store_return_value(), arm_symbian_skip_trampoline_code(), arm_wince_skip_main_prologue(), avr_address_to_pointer(), avr_frame_prev_register(), avr_pointer_to_address(), avr_pseudo_register_read(), avr_pseudo_register_write(), avr_push_dummy_call(), avr_scan_prologue(), bfin_breakpoint_from_pc(), bfin_extract_return_value(), bfin_linux_get_syscall_number(), bfin_push_dummy_call(), bfin_skip_prologue(), branch_dest(), bsd_uthread_check_magic(), bsd_uthread_extra_thread_info(), bsd_uthread_lookup_offset(), bsd_uthread_thread_alive(), bsd_uthread_wait(), build_traceframe_info(), c_get_string(), c_val_print(), call0_frame_cache(), call0_track_op(), charset_for_string_type(), check_for_saved(), cleanup_block_load_all(), cleanup_block_store_pc(), core_process_module_section(), cp_print_class_member(), cris_extract_return_value(), cris_push_dummy_call(), cris_scan_prologue(), cris_sigcontext_addr(), cris_sigtramp_frame_unwind_cache(), cris_store_return_value(), darwin_check_osabi(), darwin_current_sos(), darwin_load_image_infos(), darwin_read_exec_load_addr(), darwin_solib_read_all_image_info_addr(), debug_print_register(), decode_loadmap(), decode_prologue(), default_auxv_parse(), default_print_one_register_info(), default_read_var_value(), default_value_from_register(), define_symbol(), dfp_pseudo_register_read(), dfp_pseudo_register_write(), disassemble_dwarf_expression(), display_one_tib(), do_ppc_sysv_return_value(), dsbt_current_sos(), dwarf2_compile_expr_to_ax(), dwarf2_evaluate_loc_desc_full(), dwarf2_find_location_expression(), dwarf_expr_fetch_address(), e500_move_ev_register(), enable_break(), enable_break2(), evaluate_subexp_java(), examine_prologue(), execute_cfa_program(), execute_l32e(), execute_s32e(), execute_stack_op(), extend_simple_arg(), extract_arm_insn(), extract_call_winsize(), f_get_encoding(), f_val_print(), fetch_lm_info(), fetch_loadmap(), fetch_mips_16(), fetch_register(), fill_gregset(), find_canonical_descriptor_in_load_object(), find_command(), find_extant_func_descr(), find_func_descr(), find_implementation_from_class(), find_step_target(), fixup_riprel(), floatformat_from_length(), floatformat_from_type(), frame_info(), frame_unwind_got_constant(), frame_unwind_register_signed(), frame_unwind_register_unsigned(), frv_analyze_prologue(), frv_convert_from_func_ptr_addr(), frv_current_sos(), frv_extract_return_value(), frv_linux_pc_in_sigtramp(), frv_linux_sigcontext_reg_addr(), frv_linux_sigtramp_frame_cache(), frv_push_dummy_call(), frv_skip_main_prologue(), gdb_buffered_insn_length_init_dis(), gdb_disassemble_info(), gen_bitfield_ref(), generic_emit_char(), generic_printstr(), get_frame_memory_signed(), get_frame_memory_unsigned(), get_register(), gnuv3_decode_method_ptr(), gnuv3_make_method_ptr(), h8300_analyze_prologue(), h8300_extract_return_value(), h8300_is_argument_spill(), h8300_push_dummy_call(), h8300_store_return_value(), h8300h_extract_return_value(), h8300h_store_return_value(), hex2bin(), hppa32_hpux_find_global_pointer(), hppa32_hpux_in_solib_call_trampoline(), hppa32_hpux_search_dummy_call_sequence(), hppa32_push_dummy_call(), hppa64_convert_code_addr_to_fptr(), hppa64_hpux_find_global_pointer(), hppa64_hpux_in_solib_call_trampoline(), hppa64_hpux_search_dummy_call_sequence(), hppa64_push_dummy_call(), hppa_fallback_frame_cache(), hppa_frame_cache(), hppa_frame_prev_register_helper(), hppa_hpux_fetch_register(), hppa_hpux_in_solib_return_trampoline(), hppa_hpux_search_pattern(), hppa_hpux_sigtramp_frame_unwind_cache(), hppa_hpux_sigtramp_unwind_sniffer(), hppa_hpux_skip_trampoline_code(), hppa_hpux_store_register(), hppa_hpux_supply_save_state(), hppa_hpux_unwind_adjust_stub(), hppa_in_function_epilogue_p(), hppa_linux_find_global_pointer(), hppa_match_insns(), hppa_pseudo_register_read(), hppabsd_find_global_pointer(), i386_analyze_frame_setup(), i386_darwin_push_dummy_call(), i386_darwin_sigcontext_addr(), i386_darwin_sstep_at_sigreturn(), i386_displaced_step_fixup(), i386_fetch_pointer_argument(), i386_follow_jump(), i386_frame_cache_1(), i386_get_longjmp_target(), i386_linux_get_syscall_number_from_regcache(), i386_linux_resume(), i386_linux_sigcontext_addr(), i386_pe_skip_trampoline_code(), i386_process_record(), i386_push_dummy_call(), i386_record_lea_modrm_addr(), i386_relocate_instruction(), i386_sigtramp_frame_cache(), i386_skip_main_prologue(), i386_skip_prologue(), i386_svr4_sigcontext_addr(), i386bsd_sigcontext_addr(), i386nbsd_sigtramp_cache_init(), i386nto_sigcontext_addr(), i386obsd_collect_uthread(), i386obsd_supply_pcb(), i386obsd_supply_uthread(), i386obsd_trapframe_cache(), i387_supply_fsave(), ia64_convert_from_func_ptr_addr(), ia64_dummy_id(), ia64_extract_return_value(), ia64_find_global_pointer_from_dynamic_section(), ia64_frame_cache(), ia64_frame_prev_register(), ia64_hpux_find_global_pointer_from_solib(), ia64_hpux_stopped_in_syscall(), ia64_linux_sigcontext_register_address(), ia64_pseudo_register_read(), ia64_pseudo_register_write(), ia64_push_dummy_call(), ia64_sigtramp_frame_cache(), ia64_sigtramp_frame_prev_register(), ia64_unwind_pc(), info_spu_dma_command(), info_spu_mailbox_command(), info_spu_proxydma_command(), info_spu_signal_command(), insns_match_pattern(), iq2000_address_to_pointer(), iq2000_breakpoint_from_pc(), iq2000_extract_return_value(), iq2000_pointer_to_address(), iq2000_push_dummy_call(), iq2000_scan_prologue(), irix_current_sos(), irix_open_symbol_file_object(), java_get_encoding(), java_value_print(), jit_read_code_entry(), jit_read_descriptor(), libunwind_frame_cache(), libunwind_frame_sniffer(), libunwind_get_reg_special(), libunwind_sigtramp_frame_sniffer(), link_map_start(), linux_spu_make_corefile_notes(), lm32_analyze_prologue(), lm32_extract_return_value(), lm32_push_dummy_call(), lm32_store_return_value(), lm_base(), locexpr_describe_location_piece(), loclist_describe_location(), look_for_args_moves(), m32c_cat_read(), m32c_cat_write(), m32c_find_part(), m32c_m16c_address_to_pointer(), m32c_m16c_pointer_to_address(), m32c_push_dummy_call(), m32c_r3r2r1r0_read(), m32c_r3r2r1r0_write(), m32c_return_value(), m32c_skip_trampoline_code(), m32r_breakpoint_from_pc(), m32r_extract_return_value(), m32r_fetch_register(), m32r_memory_insert_breakpoint(), m32r_memory_remove_breakpoint(), m32r_push_dummy_call(), m32r_resume(), m32r_skip_prologue(), m32r_store_return_value(), m32r_wait(), m68hc11_analyze_instruction(), m68hc11_pseudo_register_read(), m68hc11_pseudo_register_write(), m68hc11_push_dummy_call(), m68k_analyze_frame_setup(), m68k_analyze_prologue(), m68k_analyze_register_saves(), m68k_frame_cache(), m68k_get_longjmp_target(), m68k_linux_get_sigtramp_info(), m68k_linux_pc_in_sigtramp(), m68k_linux_sigtramp_frame_cache(), m68k_push_dummy_call(), m88k_analyze_prologue(), mark_common_block_symbol_computed(), mep_extract_return_value(), mep_get_insn(), mep_pseudo_cr32_read(), mep_pseudo_cr32_write(), mep_pseudo_csr_write(), mep_push_dummy_call(), mep_store_return_value(), mi_cmd_data_write_memory(), microblaze_fetch_instruction(), mips64_fill_fpregset(), mips64_fill_gregset(), mips64_linux_get_longjmp_target(), mips64_supply_fpregset(), mips_ax_pseudo_register_push_stack(), mips_breakpoint_from_pc(), mips_convert_register_float_case_p(), mips_eabi_push_dummy_call(), mips_eabi_return_value(), mips_fetch_instruction(), mips_get_mips16_fn_stub_pc(), mips_integer_to_address(), mips_linux_get_longjmp_target(), mips_linux_get_syscall_number(), mips_linux_in_dynsym_stub(), mips_linux_o32_sigframe_init(), mips_n32n64_push_dummy_call(), mips_n32n64_return_value(), mips_o32_push_dummy_call(), mips_o32_return_value(), mips_o64_push_dummy_call(), mips_o64_return_value(), mips_pseudo_register_read(), mips_pseudo_register_write(), mips_read_fp_register_double(), mips_read_fp_register_single(), mips_register_to_value(), mips_single_step_through_delay(), mips_skip_pic_trampoline_code(), mips_value_to_register(), mips_xfer_memory(), mipsnbsd_get_longjmp_target(), mn10300_analyze_prologue(), mn10300_push_dummy_call(), modify_field(), monitor_read_memory_single(), monitor_supply_register(), monitor_write_memory(), moxie_analyze_prologue(), moxie_extract_return_value(), moxie_process_record(), moxie_store_return_value(), msp430_pseudo_register_read(), msp430_pseudo_register_write(), msp430_push_dummy_call(), msp430_return_value(), msp430_skip_trampoline_code(), mt_pseudo_register_read(), mt_pseudo_register_write(), mt_push_dummy_call(), mt_registers_info(), mt_return_value(), mt_select_coprocessor(), mt_skip_prologue(), nios2_analyze_prologue(), nios2_fetch_instruction(), nios2_get_longjmp_target(), nios2_in_epilogue_p(), nios2_match_sequence(), nios2_push_dummy_call(), nto_find_and_open_solib(), nto_init_solib_absolute_prefix(), pack_long(), pack_unsigned_long(), parse_number(), parse_spufs_run(), pascal_printstr(), pascal_val_print(), pass_in_v(), pass_in_x(), ppc64_convert_from_func_ptr_addr(), ppc64_desc_entry_point(), ppc64_sysv_abi_push_dummy_call(), ppc64_sysv_abi_return_value(), ppc_collect_reg(), ppc_deal_with_atomic_sequence(), ppc_displaced_step_fixup(), ppc_linux_auxv_parse(), ppc_linux_get_syscall_number(), ppc_linux_init_abi(), ppc_linux_sigtramp_cache(), ppc_skip_trampoline_code(), ppc_supply_reg(), ppc_sysv_abi_push_dummy_call(), ppcfbsd_sigtramp_frame_cache(), ppcfbsd_sigtramp_frame_sniffer(), ppcobsd_sigtramp_frame_cache(), ppcobsd_sigtramp_frame_sniffer(), ppu2spu_sniffer(), ppu2spu_unwind_register(), print_decimal_floating(), print_frame_nameless_args(), print_gp_register_row(), print_scalar_formatted(), printf_decfloat(), printf_wide_c_string(), printstr(), read_frame_register_unsigned(), read_insn(), read_objc_class(), read_objc_methlist_nmethods(), read_objc_method(), read_objc_object(), read_objc_super(), read_pieced_value(), read_program_header(), record_linux_msghdr(), record_linux_sockaddr(), record_linux_system_call(), regcache_cooked_read_signed(), regcache_cooked_read_unsigned(), regcache_cooked_write_signed(), regcache_cooked_write_unsigned(), regcache_dump(), regcache_raw_read_signed(), regcache_raw_read_unsigned(), regcache_raw_write_signed(), regcache_raw_write_unsigned(), rl78_address_to_pointer(), rl78_pointer_to_address(), rl78_push_dummy_call(), rl78_return_value(), rs6000_aix_extract_ld_info(), rs6000_breakpoint_from_pc(), rs6000_convert_from_func_ptr_addr(), rs6000_fetch_instruction(), rs6000_frame_cache(), rs6000_in_function_epilogue_p(), rs6000_lynx178_push_dummy_call(), rs6000_lynx178_return_value(), rs6000_push_dummy_call(), rs6000_return_value(), rs6000_skip_main_prologue(), rs6000_skip_trampoline_code(), rs6000_software_single_step(), rx_push_dummy_call(), rx_return_value(), s390_analyze_prologue(), s390_auxv_parse(), s390_backchain_frame_unwind_cache(), s390_pseudo_register_read(), s390_pseudo_register_write(), s390_push_dummy_call(), s390_return_value(), s390_sigtramp_frame_unwind_cache(), scalar_binop(), scan_dyntag_auxv(), score3_analyze_prologue(), score3_breakpoint_from_pc(), score3_in_function_epilogue_p(), score3_skip_prologue(), score7_breakpoint_from_pc(), score7_fetch_inst(), score_adjust_breakpoint_address(), score_push_dummy_call(), score_return_value(), sh64_analyze_prologue(), sh64_breakpoint_from_pc(), sh64_do_fp_register(), sh64_extract_return_value(), sh64_frame_prev_register(), sh64_pseudo_register_read(), sh64_pseudo_register_write(), sh64_push_dummy_call(), sh64_register_convert_to_raw(), sh64_register_convert_to_virtual(), sh64_skip_prologue_hard_way(), sh64_store_return_value(), sh_analyze_prologue(), sh_breakpoint_from_pc(), sh_extract_return_value_fpu(), sh_extract_return_value_nofpu(), sh_in_function_epilogue_p(), sh_justify_value_in_reg(), sh_next_flt_argreg(), sh_push_dummy_call_fpu(), sh_push_dummy_call_nofpu(), sh_register_convert_to_raw(), sh_register_convert_to_virtual(), sh_store_return_value_fpu(), sh_store_return_value_nofpu(), show_endian(), signed_pointer_to_address(), simple_overlay_update_1(), simple_read_overlay_table(), skip_prologue(), skip_prologue_hard_way(), solib_svr4_r_ldsomap(), som_current_sos(), som_open_symbol_file_object(), som_solib_create_inferior_hook(), sparc32_linux_get_syscall_number(), sparc32_linux_step_trap(), sparc32_push_dummy_code(), sparc32_return_value(), sparc32_store_arguments(), sparc32obsd_collect_uthread(), sparc32obsd_supply_uthread(), sparc64_collect_gregset(), sparc64_linux_get_syscall_number(), sparc64_linux_step_trap(), sparc64_pseudo_register_read(), sparc64_pseudo_register_write(), sparc64_supply_gregset(), sparc64obsd_collect_uthread(), sparc64obsd_supply_uthread(), sparc_collect_rwindow(), sparc_fetch_wcookie(), sparc_supply_rwindow(), spu2ppu_sniffer(), spu_address_to_pointer(), spu_analyze_prologue(), spu_current_sos(), spu_enumerate_spu_ids(), spu_fetch_inferior_registers(), spu_fetch_registers(), spu_frame_unwind_cache(), spu_get_longjmp_target(), spu_in_function_epilogue_p(), spu_pointer_to_address(), spu_pseudo_register_read_spu(), spu_pseudo_register_write_spu(), spu_push_dummy_call(), spu_software_single_step(), stap_modify_semaphore(), store_register(), supply_32bit_reg(), supply_64bit_reg(), supply_gregset(), svr4_exec_displacement(), target_wide_charset(), tfile_fetch_registers(), tfile_get_trace_state_variable_value(), tfile_get_traceframe_address(), tfile_trace_find(), tfile_xfer_partial(), thumb2_copy_table_branch(), thumb_analyze_prologue(), thumb_get_next_pc_raw(), tic6x_analyze_prologue(), tic6x_fetch_instruction(), tic6x_get_longjmp_target(), tic6x_push_dummy_call(), tic6x_return_value(), tilegx_analyze_prologue(), tilegx_get_longjmp_target(), tilegx_push_dummy_call(), trace_save(), traceframe_walk_blocks(), tramp_frame_start(), unpack_double(), unpack_long(), unpack_value_bits_as_long_1(), unsigned_address_to_pointer(), unsigned_pointer_to_address(), v850_analyze_prologue(), v850_extract_return_value(), v850_push_dummy_call(), v850_store_return_value(), val_print_string(), val_print_type_code_int(), value_args_as_decimal(), value_bit_index(), value_cast(), value_fetch_lazy(), value_logical_not(), value_neg(), value_one(), value_pointer(), vax_push_dummy_call(), vax_skip_prologue(), vax_store_arguments(), vsx_pseudo_register_read(), vsx_pseudo_register_write(), write_pieced_value(), xstormy16_address_to_pointer(), xstormy16_analyze_prologue(), xstormy16_find_jmp_table_entry(), xstormy16_in_function_epilogue_p(), xstormy16_pointer_to_address(), xstormy16_push_dummy_call(), xstormy16_resolve_jmp_table_entry(), xtensa_breakpoint_from_pc(), xtensa_extract_return_value(), xtensa_frame_cache(), xtensa_pseudo_register_read(), xtensa_pseudo_register_write(), xtensa_push_dummy_call(), xtensa_register_read_masked(), xtensa_register_write_masked(), xtensa_store_return_value(), and xtensa_window_interrupt_insn().
int gdbarch_byte_order_for_code (struct gdbarch * gdbarch)
Definition at line 1457 of file gdbarch.c.
References gdbarch::byte_order_for_code, fprintf_unfiltered(), gdb_assert, gdb_stdlog, and gdbarch_debug.
Referenced by aarch64_analyze_prologue(), arm_adjust_breakpoint_address(), arm_analyze_load_stack_chk_guard(), arm_analyze_prologue(), arm_breakpoint_from_pc(), arm_deal_with_atomic_sequence_raw(), arm_displaced_init_closure(), arm_exidx_unwind_sniffer(), arm_get_next_pc_raw(), arm_in_function_epilogue_p(), arm_linux_get_syscall_number(), arm_linux_syscall_next_pc(), arm_process_displaced_insn(), arm_skip_prologue(), arm_skip_stack_protector(), gdb_buffered_insn_length_init_dis(), gdb_disassemble_info(), nios2_breakpoint_from_pc(), skip_prologue_function(), thumb_analyze_prologue(), thumb_deal_with_atomic_sequence_raw(), thumb_get_next_pc_raw(), thumb_in_function_epilogue_p(), thumb_process_displaced_insn(), and tic6x_breakpoint_from_pc().
int gdbarch_call_dummy_location (struct gdbarch * gdbarch)
Definition at line 2251 of file gdbarch.c.
References gdbarch::call_dummy_location, fprintf_unfiltered(), gdb_assert, gdb_stdlog, and gdbarch_debug.
Referenced by call_function_by_hand().
int gdbarch_cannot_fetch_register (struct gdbarch * gdbarch, int regnum)
Definition at line 2374 of file gdbarch.c.
References gdbarch::cannot_fetch_register, fprintf_unfiltered(), gdb_assert, gdb_stdlog, and gdbarch_debug.
Referenced by fetch_osf_core_registers(), fetch_register(), inf_ptrace_fetch_register(), mipsnbsd_supply_fpreg(), and mipsnbsd_supply_reg().
int gdbarch_cannot_step_breakpoint (struct gdbarch * gdbarch)
Definition at line 3187 of file gdbarch.c.
References gdbarch::cannot_step_breakpoint, fprintf_unfiltered(), gdb_assert, gdb_stdlog, and gdbarch_debug.
Referenced by resume().
int gdbarch_cannot_store_register (struct gdbarch * gdbarch, int regnum)
Definition at line 2391 of file gdbarch.c.
References gdbarch::cannot_store_register, fprintf_unfiltered(), gdb_assert, gdb_stdlog, and gdbarch_debug.
Referenced by inf_ptrace_store_register(), mipsnbsd_fill_fpreg(), mipsnbsd_fill_reg(), regcache_raw_write(), and store_register().
int gdbarch_char_signed (struct gdbarch * gdbarch)
Definition at line 1771 of file gdbarch.c.
References gdbarch::char_signed, fprintf_unfiltered(), gdb_assert, gdb_stdlog, and gdbarch_debug.
Referenced by gdbtypes_post_init(), and objfile_type().
void gdbarch_coff_make_msymbol_special (struct gdbarch * gdbarch, int val, struct minimal_symbol * msym)
Definition at line 3170 of file gdbarch.c.
References gdbarch::coff_make_msymbol_special, fprintf_unfiltered(), gdb_assert, gdb_stdlog, and gdbarch_debug.
Referenced by coff_symtab_read().
CORE_ADDR gdbarch_convert_from_func_ptr_addr (struct gdbarch * gdbarch, CORE_ADDR addr, struct target_ops * targ)
Definition at line 2986 of file gdbarch.c.
References gdbarch::convert_from_func_ptr_addr, fprintf_unfiltered(), gdb_assert, gdb_stdlog, and gdbarch_debug.
Referenced by add_minsym(), create_exception_master_breakpoint(), elf_gnu_ifunc_resolve_addr(), elf_gnu_ifunc_resolve_by_got(), elf_gnu_ifunc_resolver_return_stop(), enable_break(), enable_thread_event(), evaluate_subexp_standard(), exec_entry_point(), find_function_addr(), find_solib_trampoline_target(), gnuv3_skip_trampoline(), hppa_hpux_push_dummy_code(), init_entry_point_info(), inside_main_func(), minsym_found(), ppc_linux_displaced_step_location(), print_function_pointer_address(), remote_check_symbols(), spu_enable_break(), value_fn_field(), and write_exp_msymbol().
int gdbarch_convert_register_p (struct gdbarch * gdbarch, int regnum, struct type * type)
Definition at line 2448 of file gdbarch.c.
References gdbarch::convert_register_p, fprintf_unfiltered(), gdb_assert, gdb_stdlog, and gdbarch_debug.
Referenced by value_assign(), value_fetch_lazy(), and value_from_register().
void gdbarch_core_info_proc (struct gdbarch * gdbarch, char * args, enum info_proc_what what)
Definition at line 4375 of file gdbarch.c.
References gdbarch::core_info_proc, fprintf_unfiltered(), gdb_assert, gdb_stdlog, and gdbarch_debug.
Referenced by core_info_proc().
int gdbarch_core_info_proc_p (struct gdbarch * gdbarch)
Definition at line 4368 of file gdbarch.c.
References gdbarch::core_info_proc, and gdb_assert.
Referenced by core_info_proc(), and gdbarch_dump().
char* gdbarch_core_pid_to_str (struct gdbarch * gdbarch, ptid_t ptid)
Definition at line 3501 of file gdbarch.c.
References gdbarch::core_pid_to_str, fprintf_unfiltered(), gdb_assert, gdb_stdlog, and gdbarch_debug.
Referenced by core_pid_to_str().
int gdbarch_core_pid_to_str_p (struct gdbarch * gdbarch)
Definition at line 3494 of file gdbarch.c.
References gdbarch::core_pid_to_str, and gdb_assert.
Referenced by core_pid_to_str(), and gdbarch_dump().
struct target_desc* gdbarch_core_read_description (struct gdbarch * gdbarch, struct target_ops * target, bfd * abfd) [read]
Definition at line 3782 of file gdbarch.c.
References gdbarch::core_read_description, fprintf_unfiltered(), gdb_assert, gdb_stdlog, and gdbarch_debug.
Referenced by core_read_description().
int gdbarch_core_read_description_p (struct gdbarch * gdbarch)
Definition at line 3775 of file gdbarch.c.
References gdbarch::core_read_description, and gdb_assert.
Referenced by core_read_description(), and gdbarch_dump().
struct core_regset_section* gdbarch_core_regset_sections (struct gdbarch * gdbarch) [read]
Definition at line 3358 of file gdbarch.c.
References gdbarch::core_regset_sections, fprintf_unfiltered(), gdb_assert, gdb_stdlog, and gdbarch_debug.
Referenced by get_core_registers(), linux_collect_thread_registers(), and linux_make_corefile_notes_1().
LONGEST gdbarch_core_xfer_shared_libraries (struct gdbarch * gdbarch, gdb_byte * readbuf, ULONGEST offset, LONGEST len)
Definition at line 3453 of file gdbarch.c.
References gdbarch::core_xfer_shared_libraries, fprintf_unfiltered(), gdb_assert, gdb_stdlog, and gdbarch_debug.
Referenced by core_xfer_partial().
LONGEST gdbarch_core_xfer_shared_libraries_aix (struct gdbarch * gdbarch, gdb_byte * readbuf, ULONGEST offset, LONGEST len)
Definition at line 3477 of file gdbarch.c.
References gdbarch::core_xfer_shared_libraries_aix, fprintf_unfiltered(), gdb_assert, gdb_stdlog, and gdbarch_debug.
Referenced by core_xfer_partial().
int gdbarch_core_xfer_shared_libraries_aix_p (struct gdbarch * gdbarch)
Definition at line 3470 of file gdbarch.c.
References gdbarch::core_xfer_shared_libraries_aix, and gdb_assert.
Referenced by core_xfer_partial(), and gdbarch_dump().
int gdbarch_core_xfer_shared_libraries_p (struct gdbarch * gdbarch)
Definition at line 3446 of file gdbarch.c.
References gdbarch::core_xfer_shared_libraries, and gdb_assert.
Referenced by core_xfer_partial(), and gdbarch_dump().
void* gdbarch_data (struct gdbarch * gdbarch, struct gdbarch_data * data)
Definition at line 4514 of file gdbarch.c.
References gdbarch::data, gdb_assert, gdbarch_data::index, gdbarch_data::init_p, gdbarch::initialized_p, gdbarch::nr_data, gdbarch::obstack, gdbarch_data::post_init, and gdbarch_data::pre_init.
Referenced by bsd_uthread_activate(), bsd_uthread_fetch_registers(), bsd_uthread_set_collect_uthread(), bsd_uthread_set_supply_uthread(), bsd_uthread_store_registers(), builtin_f_type(), builtin_go_type(), builtin_java_type(), builtin_m2_type(), builtin_opencl_type(), builtin_type(), dwarf2_frame_adjust_regnum(), dwarf2_frame_init_reg(), dwarf2_frame_set_adjust_regnum(), dwarf2_frame_set_init_reg(), dwarf2_frame_set_signal_frame_p(), dwarf2_frame_signal_frame_p(), dwarf_expr_address_type(), frame_base_append_sniffer(), frame_base_find_by_frame(), frame_base_set_default(), frame_unwind_append_unwinder(), frame_unwind_find_by_frame(), frame_unwind_prepend_unwinder(), get_linux_gdbarch_data(), get_remote_arch_state(), gnuv3_get_typeid_type(), gnuv3_get_vtable(), jit_prepend_unwinder(), language_bool_type(), language_lookup_primitive_type_by_name(), language_string_char_type(), libunwind_descr(), libunwind_frame_set_descr(), regcache_descr(), reggroup_add(), reggroup_next(), register_remote_g_packet_guess(), remote_read_description(), remote_read_description_p(), set_solib_ops(), set_solib_svr4_fetch_link_map_offsets(), set_tdesc_pseudo_register_name(), set_tdesc_pseudo_register_reggroup_p(), set_tdesc_pseudo_register_type(), solib_ops(), svr4_fetch_link_map_offsets(), svr4_have_link_map_offsets(), target_find_description(), tdesc_find_arch_register(), tdesc_find_type(), tdesc_register_name(), tdesc_register_reggroup_p(), tdesc_register_type(), tdesc_use_registers(), user_reg_add(), user_reg_map_name_to_regnum(), usernum_to_user_reg(), vtable_address_point_offset(), and vtable_ptrdiff_type().
static struct gdbarch_data* gdbarch_data_register (gdbarch_data_pre_init_ftype * pre_init, gdbarch_data_post_init_ftype * post_init) [static, read]
Definition at line 4455 of file gdbarch.c.
References gdbarch_data_registration::next, gdbarch_data_registry::nr, gdbarch_data_registry::registrations, and XMALLOC.
Referenced by gdbarch_data_register_post_init(), and gdbarch_data_register_pre_init().
struct gdbarch_data* gdbarch_data_register_post_init (gdbarch_data_post_init_ftype * post_init) [read]
Definition at line 4481 of file gdbarch.c.
References gdbarch_data_register().
Referenced by _initialize_dwarf2expr(), _initialize_gdbtypes(), _initialize_go_language(), _initialize_libunwind_frame(), _initialize_linux_tdep(), _initialize_regcache(), _initialize_reggroup(), _initialize_user_regs(), gdbpy_initialize_arch(), and init_gnuv3_ops().
struct gdbarch_data* gdbarch_data_register_pre_init (gdbarch_data_pre_init_ftype * pre_init) [read]
Definition at line 4475 of file gdbarch.c.
References gdbarch_data_register().
Referenced by _initialize_bsd_uthread(), _initialize_frame_base(), _initialize_frame_unwind(), _initialize_solib(), _initialize_svr4_solib(), and _initialize_target_descriptions().
CORE_ADDR gdbarch_decr_pc_after_break (struct gdbarch * gdbarch)
Definition at line 2765 of file gdbarch.c.
References gdbarch::decr_pc_after_break, fprintf_unfiltered(), gdb_assert, gdb_stdlog, and gdbarch_debug.
Referenced by adjust_pc_after_break(), aix_thread_wait(), cancel_breakpoint(), check_event(), and record_full_wait_1().
int gdbarch_deprecated_fp_regnum (struct gdbarch * gdbarch)
Definition at line 2210 of file gdbarch.c.
References gdbarch::deprecated_fp_regnum, fprintf_unfiltered(), gdb_assert, gdb_stdlog, and gdbarch_debug.
Referenced by legacy_virtual_frame_pointer(), and value_of_builtin_frame_fp_reg().
CORE_ADDR gdbarch_deprecated_function_start_offset (struct gdbarch * gdbarch)
Definition at line 2782 of file gdbarch.c.
References gdbarch::deprecated_function_start_offset, fprintf_unfiltered(), gdb_assert, gdb_stdlog, and gdbarch_debug.
Referenced by disassemble_command(), disassemble_current_function(), fill_in_stop_func(), find_function_addr(), skip_prologue_sal(), and skip_prologue_using_sal().
struct displaced_step_closure* gdbarch_displaced_step_copy_insn (struct gdbarch * gdbarch, CORE_ADDR from, CORE_ADDR to, struct regcache * regs) [read]
Definition at line 3633 of file gdbarch.c.
References gdbarch::displaced_step_copy_insn, fprintf_unfiltered(), gdb_assert, gdb_stdlog, and gdbarch_debug.
Referenced by displaced_step_prepare().
int gdbarch_displaced_step_copy_insn_p (struct gdbarch * gdbarch)
Definition at line 3626 of file gdbarch.c.
References gdbarch::displaced_step_copy_insn, and gdb_assert.
Referenced by displaced_step_prepare(), gdbarch_dump(), and use_displaced_stepping().
void gdbarch_displaced_step_fixup (struct gdbarch * gdbarch, struct displaced_step_closure * closure, CORE_ADDR from, CORE_ADDR to, struct regcache * regs)
Definition at line 3674 of file gdbarch.c.
References gdbarch::displaced_step_fixup, fprintf_unfiltered(), gdb_assert, gdb_stdlog, and gdbarch_debug.
Referenced by displaced_step_fixup().
int gdbarch_displaced_step_fixup_p (struct gdbarch * gdbarch)
Definition at line 3667 of file gdbarch.c.
References gdbarch::displaced_step_fixup, and gdb_assert.
Referenced by gdbarch_dump().
void gdbarch_displaced_step_free_closure (struct gdbarch * gdbarch, struct displaced_step_closure * closure)
Definition at line 3692 of file gdbarch.c.
References gdbarch::displaced_step_free_closure, fprintf_unfiltered(), gdb_assert, gdb_stdlog, and gdbarch_debug.
Referenced by displaced_step_clear().
int gdbarch_displaced_step_hw_singlestep (struct gdbarch * gdbarch, struct displaced_step_closure * closure)
Definition at line 3650 of file gdbarch.c.
References gdbarch::displaced_step_hw_singlestep, fprintf_unfiltered(), gdb_assert, gdb_stdlog, and gdbarch_debug.
Referenced by displaced_step_fixup(), and resume().
CORE_ADDR gdbarch_displaced_step_location (struct gdbarch * gdbarch)
Definition at line 3709 of file gdbarch.c.
References gdbarch::displaced_step_location, fprintf_unfiltered(), gdb_assert, gdb_stdlog, and gdbarch_debug.
Referenced by displaced_step_prepare().
int gdbarch_double_bit (struct gdbarch * gdbarch)
Definition at line 1652 of file gdbarch.c.
References gdbarch::double_bit, fprintf_unfiltered(), gdb_assert, gdb_stdlog, and gdbarch_debug.
Referenced by ada_language_arch_info(), basic_type(), binop_promote(), build_fortran_types(), floatformat_from_length(), gdbtypes_post_init(), objfile_type(), processReal(), and tdesc_register_type().
struct floatformat** gdbarch_double_format (struct gdbarch * gdbarch) [read]
Definition at line 1669 of file gdbarch.c.
References gdbarch::double_format, fprintf_unfiltered(), gdb_assert, gdb_stdlog, and gdbarch_debug.
Referenced by floatformat_from_length(), gdbtypes_post_init(), and objfile_type().
struct frame_id gdbarch_dummy_id (struct gdbarch * gdbarch, struct frame_info * this_frame) [read]
Definition at line 2193 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, and gdbarch_debug.
Referenced by dummy_frame_sniffer().
int gdbarch_dummy_id_p (struct gdbarch * gdbarch)
Definition at line 2186 of file gdbarch.c.
References gdbarch::dummy_id, and gdb_assert.
Referenced by gdbarch_dump().
void gdbarch_dump (struct gdbarch * gdbarch, struct ui_file * file)
Definition at line 782 of file gdbarch.c.
References gdbarch::addr_bit, gdbarch::addr_bits_remove, gdbarch::address_class_name_to_type_flags, gdbarch::address_class_type_flags, gdbarch::address_class_type_flags_to_name, gdbarch::address_to_pointer, gdbarch::adjust_breakpoint_address, gdbarch::auto_charset, gdbarch::auto_wide_charset, gdbarch::ax_pseudo_register_collect, gdbarch::ax_pseudo_register_push_stack, gdbarch::believe_pcc_promotion, gdbarch::bits_big_endian, gdbarch::breakpoint_from_pc, gdbarch::byte_order, gdbarch::byte_order_for_code, gdbarch::call_dummy_location, gdbarch::cannot_fetch_register, gdbarch::cannot_step_breakpoint, gdbarch::cannot_store_register, gdbarch::char_signed, gdbarch::coff_make_msymbol_special, gdbarch::convert_from_func_ptr_addr, gdbarch::convert_register_p, core_addr_to_string_nz(), gdbarch::core_info_proc, gdbarch::core_pid_to_str, gdbarch::core_read_description, gdbarch::core_regset_sections, gdbarch::core_xfer_shared_libraries, gdbarch::core_xfer_shared_libraries_aix, gdbarch::decr_pc_after_break, gdbarch::deprecated_fp_regnum, gdbarch::deprecated_function_start_offset, gdbarch::displaced_step_copy_insn, gdbarch::displaced_step_fixup, gdbarch::displaced_step_free_closure, gdbarch::displaced_step_hw_singlestep, gdbarch::displaced_step_location, gdbarch::double_bit, gdbarch::double_format, gdbarch::dummy_id, gdbarch::dump_tdep, gdbarch::dwarf2_addr_size, gdbarch::dwarf2_reg_to_regnum, gdbarch::ecoff_reg_to_regnum, gdbarch::elf_make_msymbol_special, gdbarch::elfcore_write_linux_prpsinfo, gdbarch::fast_tracepoint_valid_at, gdbarch::fetch_pointer_argument, gdbarch::fetch_tls_load_module_address, gdbarch::find_memory_regions, gdbarch::float_bit, gdbarch::float_format, gdbarch::fp0_regnum, fprintf_unfiltered(), gdbarch::frame_align, gdbarch::frame_args_skip, gdbarch::frame_num_args, gdbarch::frame_red_zone_size, gdbarch::gcore_bfd_target, GDB_NM_FILE, gdbarch::gdb_signal_from_target, gdbarch::gdb_signal_to_target, gdbarch_address_class_name_to_type_flags_p(), gdbarch_address_class_type_flags_p(), gdbarch_address_class_type_flags_to_name_p(), gdbarch_adjust_breakpoint_address_p(), gdbarch_ax_pseudo_register_collect_p(), gdbarch_ax_pseudo_register_push_stack_p(), gdbarch_bfd_arch_info(), gdbarch_core_info_proc_p(), gdbarch_core_pid_to_str_p(), gdbarch_core_read_description_p(), gdbarch_core_xfer_shared_libraries_aix_p(), gdbarch_core_xfer_shared_libraries_p(), gdbarch_displaced_step_copy_insn_p(), gdbarch_displaced_step_fixup_p(), gdbarch_dummy_id_p(), gdbarch_elfcore_write_linux_prpsinfo_p(), gdbarch_fetch_pointer_argument_p(), gdbarch_fetch_tls_load_module_address_p(), gdbarch_find_memory_regions_p(), gdbarch_frame_align_p(), gdbarch_frame_num_args_p(), gdbarch_gcore_bfd_target_p(), gdbarch_gdb_signal_from_target_p(), gdbarch_gdb_signal_to_target_p(), gdbarch_get_longjmp_target_p(), gdbarch_get_siginfo_type_p(), gdbarch_get_syscall_number_p(), gdbarch_info_proc_p(), gdbarch_integer_to_address_p(), gdbarch_make_corefile_notes_p(), gdbarch_max_insn_length_p(), gdbarch_overlay_update_p(), gdbarch_print_float_info_p(), gdbarch_print_vector_info_p(), gdbarch_process_record_p(), gdbarch_process_record_signal_p(), gdbarch_pseudo_register_read_p(), gdbarch_pseudo_register_read_value_p(), gdbarch_pseudo_register_write_p(), gdbarch_push_dummy_call_p(), gdbarch_push_dummy_code_p(), gdbarch_read_pc_p(), gdbarch_record_special_symbol_p(), gdbarch_register_type_p(), gdbarch_regset_from_core_section_p(), gdbarch_relocate_instruction_p(), gdbarch_return_value_p(), gdbarch_single_step_through_delay_p(), gdbarch_skip_main_prologue_p(), gdbarch_skip_permanent_breakpoint_p(), gdbarch_software_single_step_p(), gdbarch_stap_is_single_operand_p(), gdbarch_stap_parse_special_token_p(), gdbarch_static_transform_name_p(), gdbarch_unwind_pc_p(), gdbarch_unwind_sp_p(), gdbarch_write_pc_p(), gdbarch::gen_return_address, gdbarch::get_longjmp_target, gdbarch::get_siginfo_type, gdbarch::get_syscall_number, gdbarch::half_bit, gdbarch::half_format, gdbarch::has_dos_based_file_system, gdbarch::has_global_breakpoints, gdbarch::has_global_solist, gdbarch::has_shared_address_space, gdbarch::have_nonsteppable_watchpoint, host_address_to_string(), gdbarch::in_function_epilogue_p, gdbarch::in_solib_return_trampoline, gdbarch::info_proc, gdbarch::inner_than, gdbarch::int_bit, gdbarch::integer_to_address, gdbarch::iterate_over_objfiles_in_search_order, gdbarch::long_bit, gdbarch::long_double_bit, gdbarch::long_double_format, gdbarch::long_long_align_bit, gdbarch::long_long_bit, gdbarch::make_corefile_notes, gdbarch::max_insn_length, gdbarch::memory_insert_breakpoint, gdbarch::memory_remove_breakpoint, gdbarch::num_pseudo_regs, gdbarch::num_regs, gdbarch::osabi, gdbarch::overlay_update, gdbarch::pc_regnum, pformat(), plongest(), gdbarch::pointer_to_address, gdbarch::print_float_info, gdbarch::print_insn, gdbarch::print_registers_info, gdbarch::print_vector_info, gdbarch::process_record, gdbarch::process_record_signal, gdbarch::ps_regnum, gdbarch::pseudo_register_read, gdbarch::pseudo_register_read_value, gdbarch::pseudo_register_write, pstring(), gdbarch::ptr_bit, gdbarch::push_dummy_call, gdbarch::push_dummy_code, gdbarch::ravenscar_ops, gdbarch::read_pc, gdbarch::record_special_symbol, gdbarch::register_name, gdbarch::register_reggroup_p, gdbarch::register_sim_regno, gdbarch::register_to_value, gdbarch::register_type, gdbarch::regset_from_core_section, gdbarch::relocate_instruction, gdbarch::remote_breakpoint_from_pc, gdbarch::remote_register_number, gdbarch::return_in_first_hidden_param_p, gdbarch::return_value, gdbarch::sdb_reg_to_regnum, gdbarch::short_bit, gdbarch::single_step_through_delay, gdbarch::skip_main_prologue, gdbarch::skip_permanent_breakpoint, gdbarch::skip_prologue, gdbarch::skip_solib_resolver, gdbarch::skip_trampoline_code, gdbarch::software_single_step, gdbarch::sofun_address_maybe_missing, gdbarch::solib_symbols_extension, gdbarch::sp_regnum, gdbarch::stab_reg_to_regnum, gdbarch::stabs_argument_has_addr, gdbarch::stap_gdb_register_prefix, gdbarch::stap_gdb_register_suffix, gdbarch::stap_integer_prefix, gdbarch::stap_integer_suffix, gdbarch::stap_is_single_operand, gdbarch::stap_parse_special_token, gdbarch::stap_register_indirection_prefix, gdbarch::stap_register_indirection_suffix, gdbarch::stap_register_prefix, gdbarch::stap_register_suffix, gdbarch::static_transform_name, gdbarch::target_desc, gdbarch::unwind_pc, gdbarch::unwind_sp, gdbarch::value_from_register, gdbarch::value_to_register, gdbarch::vbit_in_delta, gdbarch::virtual_frame_pointer, gdbarch::vtable_function_descriptors, and gdbarch::write_pc.
Referenced by gdbarch_find_by_info(), and maintenance_print_architecture().
int gdbarch_dwarf2_addr_size (struct gdbarch * gdbarch)
Definition at line 1753 of file gdbarch.c.
References gdbarch::dwarf2_addr_size, fprintf_unfiltered(), gdb_assert, gdb_stdlog, and gdbarch_debug.
Referenced by decode_frame_entry_1().
int gdbarch_dwarf2_reg_to_regnum (struct gdbarch * gdbarch, int dwarf2_regnr)
Definition at line 2128 of file gdbarch.c.
References gdbarch::dwarf2_reg_to_regnum, fprintf_unfiltered(), gdb_assert, gdb_stdlog, and gdbarch_debug.
Referenced by dwarf2_compile_cfa_to_ax(), dwarf2_evaluate_loc_desc_full(), dwarf2_frame_cache(), dwarf2_frame_prev_register(), dwarf2_restore_rule(), dwarf_block_to_sp_offset(), dwarf_expr_read_reg(), jit_unwind_reg_get_impl(), jit_unwind_reg_set_impl(), locexpr_regname(), read_pieced_value(), read_reg(), translate_register(), and write_pieced_value().
int gdbarch_ecoff_reg_to_regnum (struct gdbarch * gdbarch, int ecoff_regnr)
Definition at line 2094 of file gdbarch.c.
References gdbarch::ecoff_reg_to_regnum, fprintf_unfiltered(), gdb_assert, gdb_stdlog, and gdbarch_debug.
Referenced by mdebug_reg_to_regnum().
void gdbarch_elf_make_msymbol_special (struct gdbarch * gdbarch, asymbol * sym, struct minimal_symbol * msym)
Definition at line 3153 of file gdbarch.c.
References gdbarch::elf_make_msymbol_special, fprintf_unfiltered(), gdb_assert, gdb_stdlog, and gdbarch_debug.
Referenced by elf_symtab_read().
char* gdbarch_elfcore_write_linux_prpsinfo (struct gdbarch * gdbarch, bfd * obfd, char * note_data, int * note_size, const struct elf_internal_linux_prpsinfo * info)
Definition at line 3405 of file gdbarch.c.
References gdbarch::elfcore_write_linux_prpsinfo, fprintf_unfiltered(), gdb_assert, gdb_stdlog, and gdbarch_debug.
Referenced by linux_make_corefile_notes().
int gdbarch_elfcore_write_linux_prpsinfo_p (struct gdbarch * gdbarch)
Definition at line 3398 of file gdbarch.c.
References gdbarch::elfcore_write_linux_prpsinfo, and gdb_assert.
Referenced by gdbarch_dump(), and linux_make_corefile_notes().
int gdbarch_fast_tracepoint_valid_at (struct gdbarch * gdbarch, CORE_ADDR addr, int * isize, char ** msg)
Definition at line 4243 of file gdbarch.c.
References gdbarch::fast_tracepoint_valid_at, fprintf_unfiltered(), gdb_assert, gdb_stdlog, and gdbarch_debug.
Referenced by check_fast_tracepoint_sals(), and remote_download_tracepoint().
CORE_ADDR gdbarch_fetch_pointer_argument (struct gdbarch * gdbarch, struct frame_info * frame, int argi, struct type * type)
Definition at line 3317 of file gdbarch.c.
References gdbarch::fetch_pointer_argument, fprintf_unfiltered(), gdb_assert, gdb_stdlog, and gdbarch_debug.
Referenced by resolve_msgsend(), resolve_msgsend_stret(), resolve_msgsend_super(), and resolve_msgsend_super_stret().
int gdbarch_fetch_pointer_argument_p (struct gdbarch * gdbarch)
Definition at line 3310 of file gdbarch.c.
References gdbarch::fetch_pointer_argument, and gdb_assert.
Referenced by gdbarch_dump().
CORE_ADDR gdbarch_fetch_tls_load_module_address (struct gdbarch * gdbarch, struct objfile * objfile)
Definition at line 2823 of file gdbarch.c.
References gdbarch::fetch_tls_load_module_address, fprintf_unfiltered(), gdb_assert, gdb_stdlog, and gdbarch_debug.
Referenced by target_translate_tls_address().
int gdbarch_fetch_tls_load_module_address_p (struct gdbarch * gdbarch)
Definition at line 2816 of file gdbarch.c.
References gdbarch::fetch_tls_load_module_address, and gdb_assert.
Referenced by gdbarch_dump(), and target_translate_tls_address().
struct gdbarch* gdbarch_find_by_info (struct gdbarch_info info) [read]
Definition at line 4677 of file gdbarch.c.
References gdbarch_info::abfd, gdbarch_registration::arches, gdbarch::bfd_arch_info, gdbarch_info::bfd_arch_info, gdbarch_registration::bfd_architecture, gdbarch_info::byte_order, gdbarch::dump_tdep, gdbarch_registration::dump_tdep, fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_list::gdbarch, gdbarch_debug, gdbarch_dump(), gdbarch_info_fill(), gdbarch_osabi_name(), host_address_to_string(), gdbarch_registration::init, gdbarch::initialized_p, gdbarch_list::next, gdbarch_registration::next, gdbarch_info::osabi, gdbarch_info::tdep_info, verify_gdbarch(), and XMALLOC.
Referenced by add_inferior_with_spaces(), gdbarch_from_bfd(), gdbarch_update_p(), ppu2spu_sniffer(), set_gdbarch_from_file(), and spu_gdbarch().
int gdbarch_find_memory_regions (struct gdbarch * gdbarch, find_memory_region_ftype func, void * data)
Definition at line 3429 of file gdbarch.c.
References gdbarch::find_memory_regions, fprintf_unfiltered(), gdb_assert, gdb_stdlog, and gdbarch_debug.
Referenced by gcore_memory_sections().
int gdbarch_find_memory_regions_p (struct gdbarch * gdbarch)
Definition at line 3422 of file gdbarch.c.
References gdbarch::find_memory_regions, and gdb_assert.
Referenced by gcore_memory_sections(), and gdbarch_dump().
int gdbarch_float_bit (struct gdbarch * gdbarch)
Definition at line 1619 of file gdbarch.c.
References gdbarch::float_bit, fprintf_unfiltered(), gdb_assert, gdb_stdlog, and gdbarch_debug.
Referenced by ada_language_arch_info(), basic_type(), build_fortran_types(), build_m2_types(), floatformat_from_length(), gdbtypes_post_init(), objfile_type(), and tdesc_register_type().
struct floatformat** gdbarch_float_format (struct gdbarch * gdbarch) [read]
Definition at line 1636 of file gdbarch.c.
References gdbarch::float_format, fprintf_unfiltered(), gdb_assert, gdb_stdlog, and gdbarch_debug.
Referenced by floatformat_from_length(), gdbtypes_post_init(), and objfile_type().
int gdbarch_fp0_regnum (struct gdbarch * gdbarch)
Definition at line 2060 of file gdbarch.c.
References gdbarch::fp0_regnum, fprintf_unfiltered(), gdb_assert, gdb_stdlog, and gdbarch_debug.
Referenced by alpha_linux_register_u_offset(), alpha_next_pc(), alphabsd_fetch_inferior_registers(), alphabsd_store_inferior_registers(), dr_reg_base_num(), fetch_core_registers(), fetch_register(), fill_fpregset(), fv_reg_base_num(), go32_fetch_registers(), go32_store_registers(), invalidate_cache(), m68k_register_type(), mips64_fill_fpregset(), mips64_linux_register_addr(), mips64_supply_fpregset(), mips_fill_fpregset(), mips_supply_fpregset(), mipsnbsd_fetch_inferior_registers(), mipsnbsd_fill_fpreg(), mipsnbsd_store_inferior_registers(), mipsnbsd_supply_fpreg(), ppc_linux_sigtramp_cache(), procfs_fetch_registers(), sh64_compact_reg_base_num(), sh64_do_fp_register(), sh64_dr_reg_base_num(), sh64_extract_return_value(), sh64_fpp_reg_base_num(), sh64_fv_reg_base_num(), sh64_media_print_registers_info(), sh64_push_dummy_call(), sh64_register_type(), sh64_store_return_value(), sh_extract_return_value_fpu(), sh_linux_sigtramp_cache(), sh_sh2a_register_type(), sh_sh3e_register_type(), sh_sh4_register_type(), sh_store_return_value_fpu(), store_register(), and supply_fpregset().
CORE_ADDR gdbarch_frame_align (struct gdbarch * gdbarch, CORE_ADDR address)
Definition at line 2936 of file gdbarch.c.
References fprintf_unfiltered(), gdbarch::frame_align, gdb_assert, gdb_stdlog, and gdbarch_debug.
Referenced by call_function_by_hand(), and hppa_hpux_push_dummy_code().
int gdbarch_frame_align_p (struct gdbarch * gdbarch)
Definition at line 2929 of file gdbarch.c.
References gdbarch::frame_align, and gdb_assert.
Referenced by call_function_by_hand(), and gdbarch_dump().
CORE_ADDR gdbarch_frame_args_skip (struct gdbarch * gdbarch)
Definition at line 2840 of file gdbarch.c.
References fprintf_unfiltered(), gdbarch::frame_args_skip, gdb_assert, gdb_stdlog, and gdbarch_debug.
Referenced by print_frame_args().
int gdbarch_frame_num_args (struct gdbarch * gdbarch, struct frame_info * frame)
Definition at line 2912 of file gdbarch.c.
References fprintf_unfiltered(), gdbarch::frame_num_args, gdb_assert, gdb_stdlog, and gdbarch_debug.
Referenced by frame_info(), and print_frame().
int gdbarch_frame_num_args_p (struct gdbarch * gdbarch)
Definition at line 2905 of file gdbarch.c.
References gdbarch::frame_num_args, and gdb_assert.
Referenced by frame_info(), gdbarch_dump(), and print_frame().
int gdbarch_frame_red_zone_size (struct gdbarch * gdbarch)
Definition at line 2970 of file gdbarch.c.
References fprintf_unfiltered(), gdbarch::frame_red_zone_size, gdb_assert, gdb_stdlog, and gdbarch_debug.
Referenced by call_function_by_hand().
void gdbarch_free (struct gdbarch * arch)
Definition at line 580 of file gdbarch.c.
References gdb_assert, gdbarch::initialized_p, gdbarch::obstack, and xfree().
Referenced by i386_gdbarch_init().
const char* gdbarch_gcore_bfd_target (struct gdbarch * gdbarch)
Definition at line 3525 of file gdbarch.c.
References fprintf_unfiltered(), gdbarch::gcore_bfd_target, gdb_assert, gdb_stdlog, and gdbarch_debug.
Referenced by default_gcore_target().
int gdbarch_gcore_bfd_target_p (struct gdbarch * gdbarch)
Definition at line 3518 of file gdbarch.c.
References gdbarch::gcore_bfd_target, and gdb_assert.
Referenced by default_gcore_target(), and gdbarch_dump().
enum gdb_signal gdbarch_gdb_signal_from_target (struct gdbarch * gdbarch, int signo)
Definition at line 3895 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdbarch::gdb_signal_from_target, gdb_stdlog, and gdbarch_debug.
Referenced by core_open().
int gdbarch_gdb_signal_from_target_p (struct gdbarch * gdbarch)
Definition at line 3888 of file gdbarch.c.
References gdb_assert, and gdbarch::gdb_signal_from_target.
Referenced by core_open(), and gdbarch_dump().
int gdbarch_gdb_signal_to_target (struct gdbarch * gdbarch, enum gdb_signal signal)
Definition at line 3919 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdbarch::gdb_signal_to_target, gdb_stdlog, and gdbarch_debug.
Referenced by handle_inferior_event().
int gdbarch_gdb_signal_to_target_p (struct gdbarch * gdbarch)
Definition at line 3912 of file gdbarch.c.
References gdb_assert, and gdbarch::gdb_signal_to_target.
Referenced by gdbarch_dump(), and handle_inferior_event().
void gdbarch_gen_return_address (struct gdbarch * gdbarch, struct agent_expr * ax, struct axs_value * value, CORE_ADDR scope)
Definition at line 4327 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::gen_return_address.
Referenced by gen_trace_for_return_address().
int gdbarch_get_longjmp_target (struct gdbarch * gdbarch, struct frame_info * frame, CORE_ADDR * pc)
Definition at line 2415 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::get_longjmp_target.
Referenced by handle_inferior_event().
int gdbarch_get_longjmp_target_p (struct gdbarch * gdbarch)
Definition at line 2408 of file gdbarch.c.
References gdb_assert, and gdbarch::get_longjmp_target.
Referenced by create_longjmp_master_breakpoint(), gdbarch_dump(), and handle_inferior_event().
struct type* gdbarch_get_siginfo_type (struct gdbarch * gdbarch) [read]
Definition at line 3943 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::get_siginfo_type.
Referenced by linux_get_siginfo_data(), restore_infcall_suspend_state(), save_infcall_suspend_state(), and siginfo_make_value().
int gdbarch_get_siginfo_type_p (struct gdbarch * gdbarch)
Definition at line 3936 of file gdbarch.c.
References gdb_assert, and gdbarch::get_siginfo_type.
Referenced by gdbarch_dump(), linux_get_siginfo_data(), save_infcall_suspend_state(), and siginfo_make_value().
LONGEST gdbarch_get_syscall_number (struct gdbarch * gdbarch, ptid_t ptid)
Definition at line 3991 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::get_syscall_number.
Referenced by linux_handle_syscall_trap().
int gdbarch_get_syscall_number_p (struct gdbarch * gdbarch)
Definition at line 3984 of file gdbarch.c.
References gdb_assert, and gdbarch::get_syscall_number.
Referenced by catch_syscall_command_1(), and gdbarch_dump().
int gdbarch_half_bit (struct gdbarch * gdbarch)
Definition at line 1586 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::half_bit.
Referenced by floatformat_from_length().
struct floatformat** gdbarch_half_format (struct gdbarch * gdbarch) [read]
Definition at line 1603 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::half_format.
Referenced by floatformat_from_length().
int gdbarch_has_dos_based_file_system (struct gdbarch * gdbarch)
Definition at line 4310 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::has_dos_based_file_system.
Referenced by effective_target_file_system_kind().
int gdbarch_has_global_breakpoints (struct gdbarch * gdbarch)
Definition at line 4209 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::has_global_breakpoints.
Referenced by breakpoint_address_match(), breakpoint_address_match_range(), breakpoint_init_inferior(), insert_breakpoint_locations(), print_one_breakpoint_location(), remote_insert_breakpoint(), remote_insert_hw_breakpoint(), remote_insert_watchpoint(), remote_remove_breakpoint(), remote_remove_hw_breakpoint(), remote_remove_watchpoint(), remote_start_remote(), target_detach(), update_global_location_list(), and update_inserted_breakpoint_locations().
int gdbarch_has_global_solist (struct gdbarch * gdbarch)
Definition at line 4192 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::has_global_solist.
Referenced by attach_command(), detach_command(), mi_solib_loaded(), mi_solib_unloaded(), post_create_inferior(), remote_add_inferior(), remote_start_remote(), target_pre_inferior(), and update_address_spaces().
int gdbarch_has_shared_address_space (struct gdbarch * gdbarch)
Definition at line 4226 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::has_shared_address_space.
Referenced by maybe_new_address_space(), release_program_space(), and update_address_spaces().
int gdbarch_have_nonsteppable_watchpoint (struct gdbarch * gdbarch)
Definition at line 3204 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::have_nonsteppable_watchpoint.
Referenced by handle_inferior_event(), and procfs_insert_watchpoint().
int gdbarch_in_function_epilogue_p (struct gdbarch * gdbarch, CORE_ADDR addr)
Definition at line 3136 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::in_function_epilogue_p.
Referenced by update_watchpoint(), and watchpoint_check().
int gdbarch_in_solib_return_trampoline (struct gdbarch * gdbarch, CORE_ADDR pc, const char * name)
Definition at line 3119 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::in_solib_return_trampoline.
Referenced by handle_inferior_event(), and hppa_stub_unwind_sniffer().
void gdbarch_info_proc (struct gdbarch * gdbarch, char * args, enum info_proc_what what)
Definition at line 4351 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::info_proc.
Referenced by info_proc_cmd_1().
int gdbarch_info_proc_p (struct gdbarch * gdbarch)
Definition at line 4344 of file gdbarch.c.
References gdb_assert, and gdbarch::info_proc.
Referenced by gdbarch_dump(), and info_proc_cmd_1().
int gdbarch_inner_than (struct gdbarch * gdbarch, CORE_ADDR lhs, CORE_ADDR rhs)
Definition at line 2656 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::inner_than.
Referenced by call_function_by_hand(), derive_stack_segment(), and frame_id_inner().
int gdbarch_int_bit (struct gdbarch * gdbarch)
Definition at line 1518 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::int_bit.
Referenced by ada_language_arch_info(), amd64_linux_init_abi_common(), basic_type(), build_fortran_types(), build_go_types(), build_m2_types(), coff_read_enum_type(), define_symbol(), gdbtypes_post_init(), i386_linux_init_abi(), linux_get_siginfo_type(), objfile_type(), parse_number(), parse_symbol(), processInt(), read_enum_type(), read_one_struct_field(), read_range_type(), and tdesc_register_type().
CORE_ADDR gdbarch_integer_to_address (struct gdbarch * gdbarch, struct type * type, const gdb_byte * buf)
Definition at line 2557 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::integer_to_address.
Referenced by dwarf_expr_fetch_address(), and value_as_address().
int gdbarch_integer_to_address_p (struct gdbarch * gdbarch)
Definition at line 2550 of file gdbarch.c.
References gdb_assert, and gdbarch::integer_to_address.
Referenced by dwarf_expr_fetch_address(), gdbarch_dump(), and value_as_address().
void gdbarch_iterate_over_objfiles_in_search_order (struct gdbarch * gdbarch, iterate_over_objfiles_in_search_order_cb_ftype * cb, void * cb_data, struct objfile * current_objfile)
Definition at line 4392 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::iterate_over_objfiles_in_search_order.
Referenced by default_read_var_value(), and lookup_symbol_global().
struct gdbarch_list* gdbarch_list_lookup_by_info (struct gdbarch_list * arches, const struct gdbarch_info * info) [read]
Definition at line 4654 of file gdbarch.c.
References gdbarch::bfd_arch_info, gdbarch_info::bfd_arch_info, gdbarch::byte_order, gdbarch_info::byte_order, gdbarch_list::gdbarch, gdbarch_list::next, gdbarch::osabi, gdbarch_info::osabi, gdbarch::target_desc, and gdbarch_info::target_desc.
Referenced by aarch64_gdbarch_init(), alpha_gdbarch_init(), arm_gdbarch_init(), avr_gdbarch_init(), bfin_gdbarch_init(), cris_gdbarch_init(), frv_gdbarch_init(), h8300_gdbarch_init(), hppa_gdbarch_init(), i386_gdbarch_init(), ia64_gdbarch_init(), iq2000_gdbarch_init(), lm32_gdbarch_init(), m32c_gdbarch_init(), m32r_gdbarch_init(), m68hc11_gdbarch_init(), m68k_gdbarch_init(), m88k_gdbarch_init(), mep_gdbarch_init(), microblaze_gdbarch_init(), mips_gdbarch_init(), mn10300_gdbarch_init(), moxie_gdbarch_init(), msp430_gdbarch_init(), mt_gdbarch_init(), nios2_gdbarch_init(), rl78_gdbarch_init(), rs6000_gdbarch_init(), rx_gdbarch_init(), s390_gdbarch_init(), score_gdbarch_init(), sh64_gdbarch_init(), sh_gdbarch_init(), sparc32_gdbarch_init(), spu_gdbarch_init(), tic6x_gdbarch_init(), tilegx_gdbarch_init(), v850_gdbarch_init(), vax_gdbarch_init(), and xstormy16_gdbarch_init().
int gdbarch_long_bit (struct gdbarch * gdbarch)
Definition at line 1535 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::long_bit.
Referenced by ada_language_arch_info(), amd64_linux_init_abi_common(), binop_promote(), decode_base_type(), gdbtypes_post_init(), i386_linux_init_abi(), linux_get_siginfo_type(), linux_make_mappings_corefile_notes(), objfile_type(), parse_number(), processInt(), simple_overlay_update_1(), simple_read_overlay_table(), and tdesc_register_type().
int gdbarch_long_double_bit (struct gdbarch * gdbarch)
Definition at line 1685 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::long_double_bit.
Referenced by build_fortran_types(), floatformat_from_length(), gdbtypes_post_init(), objfile_type(), processReal(), and tdesc_register_type().
struct floatformat** gdbarch_long_double_format (struct gdbarch * gdbarch) [read]
Definition at line 1702 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::long_double_format.
Referenced by do_ppc_sysv_return_value(), floatformat_from_length(), gdbtypes_post_init(), objfile_type(), ppc64_sysv_abi_push_dummy_call(), and ppc_sysv_abi_push_dummy_call().
int gdbarch_long_long_align_bit (struct gdbarch * gdbarch)
Definition at line 1569 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::long_long_align_bit.
Referenced by jit_read_code_entry().
int gdbarch_long_long_bit (struct gdbarch * gdbarch)
Definition at line 1552 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::long_long_bit.
Referenced by ada_language_arch_info(), build_fortran_types(), gdbtypes_post_init(), objfile_type(), parse_number(), read_range_type(), and tdesc_register_type().
char* gdbarch_make_corefile_notes (struct gdbarch * gdbarch, bfd * obfd, int * note_size)
Definition at line 3381 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::make_corefile_notes.
Referenced by write_gcore_file().
int gdbarch_make_corefile_notes_p (struct gdbarch * gdbarch)
Definition at line 3374 of file gdbarch.c.
References gdb_assert, and gdbarch::make_corefile_notes.
Referenced by gdbarch_dump(), and write_gcore_file().
ULONGEST gdbarch_max_insn_length (struct gdbarch * gdbarch)
Definition at line 3608 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::max_insn_length.
Referenced by amd64_displaced_step_copy_insn(), amd64_relocate_instruction(), displaced_step_prepare(), displaced_step_restore(), i386_displaced_step_copy_insn(), i386_displaced_step_fixup(), and simple_displaced_step_copy_insn().
int gdbarch_max_insn_length_p (struct gdbarch * gdbarch)
Definition at line 3601 of file gdbarch.c.
References gdb_assert, and gdbarch::max_insn_length.
Referenced by gdbarch_dump().
int gdbarch_memory_insert_breakpoint (struct gdbarch * gdbarch, struct bp_target_info * bp_tgt)
Definition at line 2731 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::memory_insert_breakpoint.
Referenced by memory_insert_breakpoint().
int gdbarch_memory_remove_breakpoint (struct gdbarch * gdbarch, struct bp_target_info * bp_tgt)
Definition at line 2748 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::memory_remove_breakpoint.
Referenced by memory_remove_breakpoint().
int gdbarch_num_pseudo_regs (struct gdbarch * gdbarch)
Definition at line 1944 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::num_pseudo_regs.
Referenced by default_print_registers_info(), dwarf2_frame_cache(), evaluate_subexp_standard(), frame_info(), gdb_regformat(), gdb_reggroup(), gen_expr(), get_frame_register_bytes(), h8300_register_type(), i386_dbx_reg_to_regnum(), i386_svr4_reg_to_regnum(), init_regcache_descr(), m68hc11_frame_unwind_cache(), m68k_dwarf_reg_to_regnum(), map_arg_registers(), mi_cmd_data_list_changed_registers(), mi_cmd_data_list_register_names(), mi_cmd_data_list_register_values(), mi_cmd_data_write_register_values(), mi_cmd_trace_frame_collected(), mips_dwarf_dwarf2_ecoff_reg_to_regnum(), mips_print_registers_info(), mips_stab_reg_to_regnum(), print_float_info(), print_gp_register_row(), print_vector_info(), regcache_dump(), register_size(), registers_info(), rs6000_gdbarch_init(), rs6000_register_sim_regno(), setup_architecture_data(), sh64_compact_print_registers_info(), sh64_media_print_registers_info(), sh64_print_register(), stab_reg_to_regnum(), tdesc_register_name(), tdesc_register_reggroup_p(), tdesc_register_type(), trad_frame_alloc_saved_regs(), tui_show_register_group(), user_reg_map_name_to_regnum(), user_reg_map_regnum_to_name(), value_of_register(), value_of_register_lazy(), value_of_user_reg(), xtensa_find_register_by_name(), xtensa_pseudo_register_read(), xtensa_pseudo_register_write(), xtensa_reg_to_regnum(), xtensa_register_name(), and xtensa_register_type().
int gdbarch_num_regs (struct gdbarch * gdbarch)
Definition at line 1926 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::num_regs.
Referenced by aarch64_make_prologue_cache(), aarch64_pseudo_read_value(), aarch64_pseudo_register_name(), aarch64_pseudo_register_reggroup_p(), aarch64_pseudo_register_type(), aarch64_pseudo_write(), amd64_collect_native_gregset(), amd64_native_gregset_reg_offset(), amd64_supply_native_gregset(), arm_make_prologue_cache(), arm_pseudo_read(), arm_pseudo_write(), arm_register_name(), arm_register_sim_regno(), arm_register_type(), avr_frame_unwind_cache(), ax_reg(), ax_reg_mask(), cris_cannot_fetch_register(), cris_cannot_store_register(), cris_register_name(), cris_register_size(), crisv32_cannot_fetch_register(), crisv32_cannot_store_register(), debug_print_register(), default_print_registers_info(), default_register_reggroup_p(), do_windows_fetch_inferior_registers(), do_windows_store_inferior_registers(), dwarf2_frame_cache(), encode_actions_1(), evaluate_subexp_standard(), fetch_core_registers(), fetch_register(), fill_gregset(), frame_info(), frv_register_sim_regno(), gdb_regformat(), gdb_reggroup(), gdbsim_fetch_register(), gdbsim_store_register(), gen_expr(), get_core_registers(), get_frame_register_bytes(), h8300_frame_cache(), h8300_frame_prev_register(), h8300_init_frame_cache(), h8300_register_type(), hppa_hpux_fetch_inferior_registers(), hppa_hpux_store_inferior_registers(), hppa_linux_fetch_inferior_registers(), hppa_linux_store_inferior_registers(), i386_dbx_reg_to_regnum(), i386_gdbarch_init(), i386_linux_fetch_inferior_registers(), i386_linux_store_inferior_registers(), i386_svr4_reg_to_regnum(), ia64_cannot_fetch_register(), ia64_cannot_store_register(), ia64_hpux_fetch_registers(), ia64_hpux_store_registers(), ia64_linux_fetch_registers(), ia64_linux_store_registers(), ia64_register_addr(), inf_child_fetch_inferior_registers(), inf_ptrace_fetch_registers(), inf_ptrace_store_registers(), init_regcache_descr(), init_remote_state(), init_sim_regno_table(), jit_dealloc_cache(), jit_frame_sniffer(), legacy_register_sim_regno(), legacy_virtual_frame_pointer(), lm32_frame_cache(), m32c_virtual_frame_pointer(), m32r_fetch_register(), m32r_frame_unwind_cache(), m32r_store_register(), m68hc11_frame_unwind_cache(), m68hc11_register_reggroup_p(), m68k_dwarf_reg_to_regnum(), map_arg_registers(), map_regcache_remote_table(), mi_cmd_data_list_changed_registers(), mi_cmd_data_list_register_names(), mi_cmd_data_list_register_values(), mi_cmd_data_write_register_values(), mi_cmd_trace_frame_collected(), microblaze_frame_cache(), micromips_scan_prologue(), mips16_scan_prologue(), mips32_scan_prologue(), mips64_linux_register_addr(), mips64obsd_sigframe_init(), mips_ax_pseudo_register_collect(), mips_ax_pseudo_register_push_stack(), mips_convert_register_gpreg_case_p(), mips_dummy_id(), mips_dwarf_dwarf2_ecoff_reg_to_regnum(), mips_eabi_return_value(), mips_float_register_p(), mips_gdbarch_init(), mips_insn16_frame_cache(), mips_insn32_frame_cache(), mips_irix_n32_stack_tramp_frame_init(), mips_irix_n32_tramp_frame_init(), mips_linux_init_abi(), mips_linux_n32n64_sigframe_init(), mips_linux_o32_sigframe_init(), mips_linux_register_addr(), mips_micro_frame_cache(), mips_n32n64_return_value(), mips_o32_return_value(), mips_o64_return_value(), mips_print_fp_register(), mips_print_registers_info(), mips_pseudo_register_read(), mips_pseudo_register_type(), mips_pseudo_register_write(), mips_read_fp_register_double(), mips_register_name(), mips_register_reggroup_p(), mips_register_sim_regno(), mips_register_type(), mips_skip_mips16_trampoline_code(), mips_stab_reg_to_regnum(), mips_stub_frame_cache(), mips_tdesc_register_reggroup_p(), mips_unwind_pc(), mips_unwind_sp(), mips_xfer_register(), monitor_fetch_registers(), monitor_store_registers(), nios2_stub_frame_cache(), old_fetch_inferior_registers(), old_store_inferior_registers(), one2one_register_sim_regno(), packet_reg_from_pnum(), packet_reg_from_regnum(), picobug_dumpregs(), ppc_linux_init_abi(), ppc_ravenscar_generic_fetch_registers(), ppu2spu_prev_register(), print_float_info(), print_gp_register_row(), print_vector_info(), process_g_packet(), record_full_core_fetch_registers(), record_full_core_open_1(), record_full_registers_change(), record_full_store_registers(), regcache_dump(), register_size(), registers_info(), remote_fetch_registers(), remote_prepare_to_store(), remote_register_number_and_offset(), remote_store_registers(), reset_saved_regs(), rs6000_gdbarch_init(), rs6000_register_sim_regno(), s390_gdbarch_init(), set_reg_offset(), setup_architecture_data(), sh64_compact_print_registers_info(), sh64_do_pseudo_register(), sh64_media_print_registers_info(), sh64_print_register(), sparc_ravenscar_fetch_registers(), stab_reg_to_regnum(), store_register(), store_registers_using_G(), supply_gregset(), tdesc_register_name(), tdesc_register_reggroup_p(), tdesc_register_type(), tdesc_use_registers(), tfile_fetch_registers(), trad_frame_alloc_saved_regs(), tui_show_register_group(), user_reg_map_name_to_regnum(), user_reg_map_regnum_to_name(), v850_frame_cache(), value_of_register(), value_of_register_lazy(), value_of_user_reg(), xtensa_find_register_by_name(), xtensa_pseudo_register_read(), xtensa_pseudo_register_write(), xtensa_reg_to_regnum(), xtensa_register_name(), xtensa_register_reggroup_p(), and xtensa_register_type().
void* gdbarch_obstack_zalloc (struct gdbarch * arch, long size)
Definition at line 564 of file gdbarch.c.
References memset(), and gdbarch::obstack.
enum gdb_osabi gdbarch_osabi (struct gdbarch * gdbarch)
Definition at line 1466 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::osabi.
Referenced by darwin_check_osabi(), hppa_stub_frame_unwind_cache(), mips_breakpoint_from_pc(), mips_pseudo_register_type(), mips_register_type(), and show_osabi().
void gdbarch_overlay_update (struct gdbarch * gdbarch, struct obj_section * osect)
Definition at line 3758 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::overlay_update.
Referenced by overlay_load_command(), and section_is_mapped().
int gdbarch_overlay_update_p (struct gdbarch * gdbarch)
Definition at line 3751 of file gdbarch.c.
References gdb_assert, and gdbarch::overlay_update.
Referenced by gdbarch_dump(), overlay_load_command(), and section_is_mapped().
int gdbarch_pc_regnum (struct gdbarch * gdbarch)
Definition at line 2026 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::pc_regnum.
Referenced by alpha_linux_register_u_offset(), cris_dwarf2_frame_init_reg(), cris_register_size(), cris_register_type(), cris_scan_prologue(), cris_sigtramp_frame_unwind_cache(), cris_software_single_step(), cris_supply_gregset(), cris_unwind_pc(), crisv32_register_name(), crisv32_register_type(), crisv32_scan_prologue(), dbug_supply_register(), dwarf2_frame_default_init_reg(), dwarf2_tailcall_prev_register_first(), fetch_ppc_registers(), fill_gregset(), fill_sprs32(), fill_sprs64(), find_step_target(), frame_info(), get_prev_frame_1(), getregs_supplies(), i386_linux_resume(), i386_unwind_pc(), init_sim_regno_table(), m68hc11_unwind_pc(), m68k_register_type(), m68k_unwind_pc(), mips_irix_n32_stack_tramp_frame_init(), mips_read_pc(), mips_stub_frame_cache(), mips_unwind_pc(), mips_write_pc(), mipsnbsd_fill_reg(), mipsnbsd_supply_reg(), nios2_stub_frame_cache(), ppc_collect_gregset(), ppc_displaced_step_fixup(), ppc_dwarf2_frame_init_reg(), ppc_greg_offset(), ppc_linux_sigtramp_cache(), ppc_linux_write_pc(), ppc_register_u_addr(), ppc_supply_gregset(), ppcfbsd_sigtramp_frame_cache(), ppcnbsd_sigtramp_cache_init(), ppcnbsd_supply_pcb(), ppcobsd_sigtramp_frame_cache(), ppcobsd_supply_pcb(), procfs_fetch_registers(), regcache_read_pc(), regcache_write_pc(), regmap(), rs6000_fetch_inferior_registers(), rs6000_frame_cache(), rs6000_store_inferior_registers(), rs6000_unwind_pc(), sh64_compact_reg_base_num(), sh64_frame_prev_register(), sh64_unwind_pc(), sh_dwarf2_frame_init_reg(), sh_frame_prev_register(), sh_unwind_pc(), special_register_p(), store_ppc_registers(), store_regs_user_thread(), supply_gregset(), supply_gregset_reg(), supply_sprs32(), supply_sprs64(), tfile_fetch_registers(), tic6x_dwarf2_frame_init_reg(), v850_unwind_pc(), value_of_builtin_frame_pc_reg(), xtensa_extract_return_value(), xtensa_frame_cache(), xtensa_frame_prev_register(), xtensa_register_type(), xtensa_store_return_value(), xtensa_supply_gregset(), and xtensa_unwind_pc().
CORE_ADDR gdbarch_pointer_to_address (struct gdbarch * gdbarch, struct type * type, const gdb_byte * buf)
Definition at line 2516 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::pointer_to_address.
Referenced by extract_typed_address(), and proc_watchpoint_address().
void gdbarch_print_float_info (struct gdbarch * gdbarch, struct ui_file * file, struct frame_info * frame, const char * args)
Definition at line 2316 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::print_float_info.
Referenced by print_float_info().
int gdbarch_print_float_info_p (struct gdbarch * gdbarch)
Definition at line 2309 of file gdbarch.c.
References gdb_assert, and gdbarch::print_float_info.
Referenced by gdbarch_dump(), and print_float_info().
int gdbarch_print_insn (struct gdbarch * gdbarch, bfd_vma vma, struct disassemble_info * info)
Definition at line 3068 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::print_insn.
Referenced by dump_insns(), gdb_buffered_insn_length(), and gdb_print_insn().
void gdbarch_print_registers_info (struct gdbarch * gdbarch, struct ui_file * file, struct frame_info * frame, int regnum, int all)
Definition at line 2292 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::print_registers_info.
Referenced by print_float_info(), print_vector_info(), registers_info(), and tui_register_format().
void gdbarch_print_vector_info (struct gdbarch * gdbarch, struct ui_file * file, struct frame_info * frame, const char * args)
Definition at line 2340 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::print_vector_info.
Referenced by print_vector_info().
int gdbarch_print_vector_info_p (struct gdbarch * gdbarch)
Definition at line 2333 of file gdbarch.c.
References gdb_assert, and gdbarch::print_vector_info.
Referenced by gdbarch_dump(), and print_vector_info().
const char** gdbarch_printable_names (void)
Definition at line 4572 of file gdbarch.c.
References _, append_name(), gdbarch_registration::arches, gdbarch_registration::bfd_architecture, internal_error(), and gdbarch_registration::next.
Referenced by initialize_current_architecture().
int gdbarch_process_record (struct gdbarch * gdbarch, struct regcache * regcache, CORE_ADDR addr)
Definition at line 3847 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::process_record.
Referenced by record_full_message().
int gdbarch_process_record_p (struct gdbarch * gdbarch)
Definition at line 3840 of file gdbarch.c.
References gdb_assert, and gdbarch::process_record.
Referenced by gdbarch_dump(), and record_full_open_1().
int gdbarch_process_record_signal (struct gdbarch * gdbarch, struct regcache * regcache, enum gdb_signal signal)
Definition at line 3871 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::process_record_signal.
Referenced by record_full_message().
int gdbarch_process_record_signal_p (struct gdbarch * gdbarch)
Definition at line 3864 of file gdbarch.c.
References gdb_assert, and gdbarch::process_record_signal.
Referenced by gdbarch_dump(), and record_full_message().
int gdbarch_ps_regnum (struct gdbarch * gdbarch)
Definition at line 2043 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::ps_regnum.
Referenced by dbug_supply_register(), fill_gregset(), supply_gregset(), supply_gregset_reg(), value_of_builtin_frame_ps_reg(), windows_resume(), xtensa_frame_cache(), xtensa_frame_prev_register(), xtensa_push_dummy_call(), xtensa_supply_gregset(), and xtensa_window_interrupt_frame_cache().
enum register_status gdbarch_pseudo_register_read (struct gdbarch * gdbarch, struct regcache * regcache, int cookednum, gdb_byte * buf)
Definition at line 1861 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::pseudo_register_read.
Referenced by ppu2spu_prev_register(), and regcache_cooked_read().
int gdbarch_pseudo_register_read_p (struct gdbarch * gdbarch)
Definition at line 1854 of file gdbarch.c.
References gdb_assert, and gdbarch::pseudo_register_read.
Referenced by gdbarch_dump().
struct value* gdbarch_pseudo_register_read_value (struct gdbarch * gdbarch, struct regcache * regcache, int cookednum) [read]
Definition at line 1885 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::pseudo_register_read_value.
Referenced by regcache_cooked_read(), and regcache_cooked_read_value().
int gdbarch_pseudo_register_read_value_p (struct gdbarch * gdbarch)
Definition at line 1878 of file gdbarch.c.
References gdb_assert, and gdbarch::pseudo_register_read_value.
Referenced by gdbarch_dump(), regcache_cooked_read(), and regcache_cooked_read_value().
void gdbarch_pseudo_register_write (struct gdbarch * gdbarch, struct regcache * regcache, int cookednum, const gdb_byte * buf)
Definition at line 1909 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::pseudo_register_write.
Referenced by regcache_cooked_write().
int gdbarch_pseudo_register_write_p (struct gdbarch * gdbarch)
Definition at line 1902 of file gdbarch.c.
References gdb_assert, and gdbarch::pseudo_register_write.
Referenced by gdbarch_dump().
int gdbarch_ptr_bit (struct gdbarch * gdbarch)
Definition at line 1718 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::ptr_bit.
Referenced by amd64_analyze_prologue(), amd64_linux_core_read_description(), amd64_linux_enable_btrace(), amd64_linux_init_abi_common(), amd64_linux_sigtramp_start(), build_gdb_vtable_type(), build_go_types(), build_opencl_types(), decode_frame_entry_1(), default_auxv_parse(), default_region_ok_for_hw_watchpoint(), display_one_tib(), do_examine(), fill_gregset(), get_java_object_header_size(), hppa_frame_cache(), hppa_hpux_skip_trampoline_code(), hppa_hpux_unwind_adjust_stub(), i386_darwin_fetch_inferior_registers(), i386_darwin_store_inferior_registers(), i386_linux_enable_btrace(), i386_linux_init_abi(), info_proc_mappings(), info_sharedlibrary_command(), java_value_print(), linux_get_siginfo_type(), linux_make_corefile_notes(), m68k_get_longjmp_target(), make_pointer_type(), make_reference_type(), make_types(), mips64_linux_get_longjmp_target(), mips_linux_get_longjmp_target(), mipsnbsd_init_abi(), nto_truncate_ptr(), s390_analyze_prologue(), s390_backchain_frame_unwind_cache(), s390_dummy_id(), s390_in_function_epilogue_p(), s390_linux_fetch_inferior_registers(), s390_prologue_frame_unwind_cache(), s390_push_dummy_call(), s390_regset_from_core_section(), s390_return_value(), s390_sigtramp_frame_unwind_cache(), s390_stub_frame_unwind_cache(), skip_prologue_hard_way(), smash_to_memberptr_type(), sparc64_collect_fpregset(), sparc64_collect_gregset(), sparc64_fpregset_supplies_p(), sparc64_gregset_supplies_p(), sparc64_supply_fpregset(), sparc64_supply_gregset(), sparc64nbsd_collect_fpregset(), sparc64nbsd_collect_gregset(), sparc64nbsd_fpregset_supplies_p(), sparc64nbsd_gregset_supplies_p(), sparc64nbsd_supply_fpregset(), sparc64nbsd_supply_gregset(), sparc_collect_rwindow(), sparc_supply_rwindow(), supply_gregset(), svr4_truncate_ptr(), tdesc_register_type(), tilegx_gdbarch_init(), verify_gdbarch(), and windows_get_tlb_type().
CORE_ADDR gdbarch_push_dummy_call (struct gdbarch * gdbarch, struct value * function, struct regcache * regcache, CORE_ADDR bp_addr, int nargs, struct value ** args, CORE_ADDR sp, int struct_return, CORE_ADDR struct_addr)
Definition at line 2234 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::push_dummy_call.
Referenced by call_function_by_hand().
int gdbarch_push_dummy_call_p (struct gdbarch * gdbarch)
Definition at line 2227 of file gdbarch.c.
References gdb_assert, and gdbarch::push_dummy_call.
Referenced by call_function_by_hand(), and gdbarch_dump().
CORE_ADDR gdbarch_push_dummy_code (struct gdbarch * gdbarch, CORE_ADDR sp, CORE_ADDR funaddr, struct value ** args, int nargs, struct type * value_type, CORE_ADDR * real_pc, CORE_ADDR * bp_addr, struct regcache * regcache)
Definition at line 2275 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::push_dummy_code.
Referenced by push_dummy_code().
int gdbarch_push_dummy_code_p (struct gdbarch * gdbarch)
Definition at line 2268 of file gdbarch.c.
References gdb_assert, and gdbarch::push_dummy_code.
Referenced by gdbarch_dump(), hppa32_push_dummy_call(), hppa64_push_dummy_call(), and push_dummy_code().
struct ravenscar_arch_ops* gdbarch_ravenscar_ops (struct gdbarch * gdbarch) [read]
Definition at line 4409 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::ravenscar_ops.
Referenced by ravenscar_fetch_registers(), ravenscar_inferior_created(), ravenscar_prepare_to_store(), and ravenscar_store_registers().
CORE_ADDR gdbarch_read_pc (struct gdbarch * gdbarch, struct regcache * regcache)
Definition at line 1796 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::read_pc.
Referenced by regcache_read_pc().
int gdbarch_read_pc_p (struct gdbarch * gdbarch)
Definition at line 1789 of file gdbarch.c.
References gdb_assert, and gdbarch::read_pc.
Referenced by gdbarch_dump(), and regcache_read_pc().
void gdbarch_record_special_symbol (struct gdbarch * gdbarch, struct objfile * objfile, asymbol * sym)
Definition at line 3967 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::record_special_symbol.
Referenced by elf_symtab_read().
int gdbarch_record_special_symbol_p (struct gdbarch * gdbarch)
Definition at line 3960 of file gdbarch.c.
References gdb_assert, and gdbarch::record_special_symbol.
Referenced by elf_symtab_read(), and gdbarch_dump().
void gdbarch_register (enum bfd_architecture bfd_architecture , gdbarch_init_ftype * init, gdbarch_dump_tdep_ftype * dump_tdep)
Definition at line 4602 of file gdbarch.c.
References _, fprintf_unfiltered(), gdb_stdlog, gdbarch_debug, host_address_to_string(), internal_error(), gdbarch_registration::next, and XMALLOC.
Referenced by _initialize_aarch64_tdep(), _initialize_alpha_tdep(), _initialize_arm_tdep(), _initialize_cris_tdep(), _initialize_hppa_tdep(), _initialize_ia64_tdep(), _initialize_m68k_tdep(), _initialize_mips_tdep(), _initialize_mn10300_tdep(), _initialize_nios2_tdep(), _initialize_rs6000_tdep(), _initialize_score_tdep(), _initialize_sh_tdep(), _initialize_xtensa_tdep(), and register_gdbarch_init().
const char* gdbarch_register_name (struct gdbarch * gdbarch, int regnr)
Definition at line 2145 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::register_name.
Referenced by aarch64_extract_return_value(), aarch64_push_dummy_call(), aarch64_store_return_value(), address_info(), address_of_variable(), alpha_register_reggroup_p(), amd64_windows_frame_decode_insns(), amd64_windows_frame_prev_register(), arm_push_dummy_call(), debug_print_register(), default_print_registers_info(), default_register_reggroup_p(), dwarf2_frame_cache(), dwarf2_restore_rule(), fetch_osf_core_registers(), fetch_register(), fetch_register_using_p(), frame_info(), gdbsim_fetch_register(), gdbsim_store_register(), get_register_name(), gnu_fetch_registers(), gnu_store_registers(), h8300_print_register(), hppa_hpux_fetch_register(), hppa_hpux_store_register(), ia64_hpux_fetch_register(), ia64_hpux_store_register(), ia64_linux_fetch_register(), ia64_linux_store_register(), inf_ptrace_fetch_register(), inf_ptrace_store_register(), legacy_register_sim_regno(), locexpr_regname(), m68hc11_print_registers_info(), map_arg_registers(), mi_cmd_data_list_changed_registers(), mi_cmd_data_list_register_names(), mi_cmd_data_list_register_values(), mi_cmd_data_write_register_values(), mi_cmd_trace_frame_collected(), mips_print_fp_register(), mips_print_register(), mips_print_registers_info(), mips_read_fp_register_double(), mips_read_fp_register_single(), mips_register_reggroup_p(), mips_register_sim_regno(), mt_registers_info(), pass_in_v(), pass_in_x(), print_gp_register_row(), record_full_store_registers(), regcache_dump(), rs6000_pseudo_register_read(), rs6000_pseudo_register_write(), scope_info(), sh64_compact_print_registers_info(), sh64_do_fp_register(), sh64_do_register(), sh64_media_print_registers_info(), sh_register_reggroup_p(), store_register(), store_register_using_P(), tui_show_register_group(), user_reg_map_name_to_regnum(), and user_reg_map_regnum_to_name().
int gdbarch_register_reggroup_p (struct gdbarch * gdbarch, int regnum, struct reggroup * reggroup)
Definition at line 3293 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::register_reggroup_p.
Referenced by default_print_registers_info(), frame_info(), gdb_reggroup(), print_float_info(), print_vector_info(), regcache_dump(), regcache_restore(), regcache_save(), registers_info(), sh_frame_cache(), and tui_show_register_group().
int gdbarch_register_sim_regno (struct gdbarch * gdbarch, int reg_nr)
Definition at line 2357 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::register_sim_regno.
Referenced by gdbsim_fetch_register(), and gdbsim_store_register().
int gdbarch_register_to_value (struct gdbarch * gdbarch, struct frame_info * frame, int regnum, struct type * type, gdb_byte * buf, int * optimizedp, int * unavailablep)
Definition at line 2465 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::register_to_value.
Referenced by value_from_register().
struct type* gdbarch_register_type (struct gdbarch * gdbarch, int reg_nr) [read]
Definition at line 2169 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::register_type.
Referenced by init_regcache_descr(), m68kbsd_fpreg_offset(), and mips_pseudo_register_type().
int gdbarch_register_type_p (struct gdbarch * gdbarch)
Definition at line 2162 of file gdbarch.c.
References gdb_assert, and gdbarch::register_type.
Referenced by gdbarch_dump().
struct regset* gdbarch_regset_from_core_section (struct gdbarch * gdbarch, const char * sect_name, size_t sect_size) [read]
Definition at line 3341 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::regset_from_core_section.
Referenced by fbsd_make_corefile_notes(), get_core_register_section(), linux_collect_thread_registers(), and linux_nat_collect_thread_registers().
int gdbarch_regset_from_core_section_p (struct gdbarch * gdbarch)
Definition at line 3334 of file gdbarch.c.
References gdb_assert, and gdbarch::regset_from_core_section.
Referenced by fbsd_make_corefile_notes(), gdbarch_dump(), get_core_register_section(), get_core_registers(), i386_gdbarch_init(), linux_nat_collect_thread_registers(), and sniff_core_bfd().
void gdbarch_relocate_instruction (struct gdbarch * gdbarch, CORE_ADDR * to, CORE_ADDR from)
Definition at line 3733 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::relocate_instruction.
Referenced by remote_get_noisy_reply().
int gdbarch_relocate_instruction_p (struct gdbarch * gdbarch)
Definition at line 3726 of file gdbarch.c.
References gdb_assert, and gdbarch::relocate_instruction.
Referenced by gdbarch_dump().
void gdbarch_remote_breakpoint_from_pc (struct gdbarch * gdbarch, CORE_ADDR * pcptr, int * kindptr)
Definition at line 2690 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::remote_breakpoint_from_pc.
Referenced by remote_insert_breakpoint(), and remote_insert_hw_breakpoint().
int gdbarch_remote_register_number (struct gdbarch * gdbarch, int regno)
Definition at line 2799 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::remote_register_number.
Referenced by map_regcache_remote_table().
int gdbarch_return_in_first_hidden_param_p (struct gdbarch * gdbarch, struct type * type)
Definition at line 2598 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::return_in_first_hidden_param_p.
Referenced by call_function_by_hand().
enum return_value_convention gdbarch_return_value (struct gdbarch * gdbarch, struct value * function, struct type * valtype, struct regcache * regcache, gdb_byte * readbuf, const gdb_byte * writebuf)
Definition at line 2581 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::return_value.
Referenced by call_function_by_hand(), elf_gnu_ifunc_resolver_return_stop(), get_return_value(), return_command(), and struct_return_convention().
int gdbarch_return_value_p (struct gdbarch * gdbarch)
Definition at line 2574 of file gdbarch.c.
References gdb_assert, and gdbarch::return_value.
Referenced by gdbarch_dump().
int gdbarch_sdb_reg_to_regnum (struct gdbarch * gdbarch, int sdb_regnr)
Definition at line 2111 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::sdb_reg_to_regnum.
Referenced by coff_reg_to_regnum().
int gdbarch_short_bit (struct gdbarch * gdbarch)
Definition at line 1501 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::short_bit.
Referenced by ada_language_arch_info(), build_fortran_types(), gdbtypes_post_init(), objfile_type(), and tdesc_register_type().
int gdbarch_single_step_through_delay (struct gdbarch * gdbarch, struct frame_info * frame)
Definition at line 3051 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::single_step_through_delay.
Referenced by handle_inferior_event(), and proceed().
int gdbarch_single_step_through_delay_p (struct gdbarch * gdbarch)
Definition at line 3044 of file gdbarch.c.
References gdb_assert, and gdbarch::single_step_through_delay.
Referenced by gdbarch_dump(), handle_inferior_event(), and proceed().
CORE_ADDR gdbarch_skip_main_prologue (struct gdbarch * gdbarch, CORE_ADDR ip)
Definition at line 2639 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::skip_main_prologue.
Referenced by skip_prologue_sal().
int gdbarch_skip_main_prologue_p (struct gdbarch * gdbarch)
Definition at line 2632 of file gdbarch.c.
References gdb_assert, and gdbarch::skip_main_prologue.
Referenced by gdbarch_dump(), and skip_prologue_sal().
void gdbarch_skip_permanent_breakpoint (struct gdbarch * gdbarch, struct regcache * regcache)
Definition at line 3584 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::skip_permanent_breakpoint.
Referenced by resume().
int gdbarch_skip_permanent_breakpoint_p (struct gdbarch * gdbarch)
Definition at line 3577 of file gdbarch.c.
References gdb_assert, and gdbarch::skip_permanent_breakpoint.
Referenced by gdbarch_dump(), and resume().
CORE_ADDR gdbarch_skip_prologue (struct gdbarch * gdbarch, CORE_ADDR ip)
Definition at line 2615 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::skip_prologue.
Referenced by handle_step_into_function(), handle_step_into_function_backward(), in_prologue(), and skip_prologue_sal().
CORE_ADDR gdbarch_skip_solib_resolver (struct gdbarch * gdbarch, CORE_ADDR pc)
Definition at line 3102 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::skip_solib_resolver.
Referenced by handle_inferior_event().
CORE_ADDR gdbarch_skip_trampoline_code (struct gdbarch * gdbarch, struct frame_info * frame, CORE_ADDR pc)
Definition at line 3085 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::skip_trampoline_code.
Referenced by gnuv3_skip_trampoline(), handle_inferior_event(), and objc_skip_trampoline().
int gdbarch_software_single_step (struct gdbarch * gdbarch, struct frame_info * frame)
Definition at line 3027 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::software_single_step.
Referenced by maybe_software_singlestep(), record_full_resume(), and record_full_wait_1().
int gdbarch_software_single_step_p (struct gdbarch * gdbarch)
Definition at line 3020 of file gdbarch.c.
References gdb_assert, and gdbarch::software_single_step.
Referenced by default_displaced_step_hw_singlestep(), gdbarch_dump(), maybe_software_singlestep(), record_full_resume(), record_full_wait_1(), and resume().
int gdbarch_sofun_address_maybe_missing (struct gdbarch * gdbarch)
Definition at line 3823 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::sofun_address_maybe_missing.
Referenced by end_psymtab(), parse_partial_symbols(), process_one_symbol(), and read_dbx_symtab().
const char* gdbarch_solib_symbols_extension (struct gdbarch * gdbarch)
Definition at line 4294 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::solib_symbols_extension.
Referenced by solib_find().
int gdbarch_sp_regnum (struct gdbarch * gdbarch)
Definition at line 2009 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::sp_regnum.
Referenced by amd64_frame_prev_register(), bfin_frame_prev_register(), cris_dummy_id(), cris_dwarf2_frame_init_reg(), cris_push_dummy_call(), cris_register_type(), cris_scan_prologue(), cris_sigcontext_addr(), cris_sigtramp_frame_unwind_cache(), cris_unwind_sp(), crisv32_register_type(), crisv32_scan_prologue(), dwarf2_frame_cache(), dwarf2_frame_default_init_reg(), dwarf2_tailcall_prev_register_first(), dwarf2_tailcall_sniffer_first(), dwarf_block_to_sp_offset(), frame_info(), get_frame_sp(), ia64_frame_prev_register(), legacy_virtual_frame_pointer(), libunwind_frame_cache(), m32r_supply_register(), m68k_get_longjmp_target(), ppc64_sysv_abi_push_dummy_call(), ppc_dwarf2_frame_init_reg(), ppc_linux_sigtramp_cache(), ppc_ravenscar_generic_fetch_registers(), ppc_sysv_abi_push_dummy_call(), ppcfbsd_sigtramp_frame_cache(), ppcfbsd_supply_pcb(), ppcnbsd_sigtramp_cache_init(), ppcobsd_sigtramp_frame_cache(), ppcobsd_supply_pcb(), procfs_fetch_registers(), rs6000_dummy_id(), rs6000_frame_cache(), rs6000_lynx178_push_dummy_call(), rs6000_push_dummy_call(), sh64_dummy_id(), sh64_frame_cache(), sh64_frame_prev_register(), sh64_push_dummy_call(), sh64_unwind_sp(), sh_dummy_id(), sh_dwarf2_frame_init_reg(), sh_frame_cache(), sh_frame_prev_register(), sh_linux_sigtramp_cache(), sh_make_stub_cache(), sh_push_dummy_call_fpu(), sh_push_dummy_call_nofpu(), sh_unwind_sp(), sparc_ravenscar_fetch_registers(), stab_reg_to_regnum(), store_register(), supply_gregset(), tic6x_dwarf2_frame_init_reg(), v850_dummy_id(), v850_unwind_sp(), and value_of_builtin_frame_sp_reg().
int gdbarch_stab_reg_to_regnum (struct gdbarch * gdbarch, int stab_regnr)
Definition at line 2077 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::stab_reg_to_regnum.
Referenced by stab_reg_to_regnum().
int gdbarch_stabs_argument_has_addr (struct gdbarch * gdbarch, struct type * type)
Definition at line 2953 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::stabs_argument_has_addr.
Referenced by define_symbol().
const char* gdbarch_stap_gdb_register_prefix (struct gdbarch * gdbarch)
Definition at line 4110 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::stap_gdb_register_prefix.
Referenced by stap_parse_register_operand().
const char* gdbarch_stap_gdb_register_suffix (struct gdbarch * gdbarch)
Definition at line 4127 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::stap_gdb_register_suffix.
Referenced by stap_parse_register_operand().
const char* gdbarch_stap_integer_prefix (struct gdbarch * gdbarch)
Definition at line 4008 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::stap_integer_prefix.
Referenced by stap_parse_single_operand().
const char* gdbarch_stap_integer_suffix (struct gdbarch * gdbarch)
Definition at line 4025 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::stap_integer_suffix.
Referenced by stap_parse_single_operand().
int gdbarch_stap_is_single_operand (struct gdbarch * gdbarch, const char * s)
Definition at line 4151 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::stap_is_single_operand.
Referenced by stap_parse_argument_conditionally().
int gdbarch_stap_is_single_operand_p (struct gdbarch * gdbarch)
Definition at line 4144 of file gdbarch.c.
References gdb_assert, and gdbarch::stap_is_single_operand.
Referenced by gdbarch_dump(), and stap_can_evaluate_probe_arguments().
int gdbarch_stap_parse_special_token (struct gdbarch * gdbarch, struct stap_parse_info * p)
Definition at line 4175 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::stap_parse_special_token.
Referenced by stap_parse_single_operand().
int gdbarch_stap_parse_special_token_p (struct gdbarch * gdbarch)
Definition at line 4168 of file gdbarch.c.
References gdb_assert, and gdbarch::stap_parse_special_token.
Referenced by gdbarch_dump(), and stap_parse_single_operand().
const char* gdbarch_stap_register_indirection_prefix (struct gdbarch * gdbarch)
Definition at line 4076 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::stap_register_indirection_prefix.
Referenced by stap_parse_register_operand(), and stap_parse_single_operand().
const char* gdbarch_stap_register_indirection_suffix (struct gdbarch * gdbarch)
Definition at line 4093 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::stap_register_indirection_suffix.
Referenced by stap_parse_register_operand().
const char* gdbarch_stap_register_prefix (struct gdbarch * gdbarch)
Definition at line 4042 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::stap_register_prefix.
Referenced by stap_parse_register_operand(), and stap_parse_single_operand().
const char* gdbarch_stap_register_suffix (struct gdbarch * gdbarch)
Definition at line 4059 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::stap_register_suffix.
Referenced by stap_parse_register_operand().
const char* gdbarch_static_transform_name (struct gdbarch * gdbarch, const char * name)
Definition at line 3806 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::static_transform_name.
Referenced by define_symbol(), parse_partial_symbols(), read_dbx_symtab(), and scan_xcoff_symtab().
int gdbarch_static_transform_name_p (struct gdbarch * gdbarch)
Definition at line 3799 of file gdbarch.c.
References gdb_assert, and gdbarch::static_transform_name.
Referenced by define_symbol(), gdbarch_dump(), parse_partial_symbols(), read_dbx_symtab(), and scan_xcoff_symtab().
struct target_desc* gdbarch_target_desc (struct gdbarch * gdbarch) [read]
Definition at line 1475 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::target_desc.
Referenced by arm_register_type(), mips_linux_restart_reg_p(), mips_register_name(), nios2_register_type(), ppc_linux_trap_reg_p(), remote_start_remote(), target_find_description(), and tic6x_register_name().
struct gdbarch_tdep* gdbarch_tdep (struct gdbarch * gdbarch) [read]
Definition at line 1430 of file gdbarch.c.
References fprintf_unfiltered(), gdb_stdlog, gdbarch_debug, and gdbarch::tdep.
Referenced by aarch64_breakpoint_from_pc(), aarch64_dump_tdep(), aarch64_get_longjmp_target(), aarch64_linux_init_abi(), aarch64_linux_regset_from_core_section(), aarch64_newlib_init_abi(), aarch64_return_value(), aarch64_vnb_type(), aarch64_vnd_type(), aarch64_vnh_type(), aarch64_vnq_type(), aarch64_vns_type(), add_reg(), alpha_get_longjmp_target(), alpha_heuristic_proc_start(), alpha_linux_init_abi(), alpha_mdebug_init_abi(), alpha_osf1_init_abi(), alpha_sigtramp_frame_this_id(), alpha_sigtramp_frame_unwind_cache(), alpha_sigtramp_register_address(), alphafbsd_init_abi(), alphanbsd_init_abi(), alphaobsd_init_abi(), altivec_register_p(), amd64_collect_fpregset(), amd64_collect_fxsave(), amd64_collect_xsave(), amd64_dicos_init_abi(), amd64_dwarf_reg_to_regnum(), amd64_get_longjmp_target(), amd64_init_abi(), amd64_linux_init_abi(), amd64_linux_init_abi_common(), amd64_pseudo_register_name(), amd64_pseudo_register_read_value(), amd64_pseudo_register_write(), amd64_regset_from_core_section(), amd64_sigtramp_frame_cache(), amd64_sigtramp_frame_sniffer(), amd64_sol2_init_abi(), amd64_supply_fpregset(), amd64_supply_fxsave(), amd64_supply_xsave(), amd64_windows_init_abi(), amd64_x32_init_abi(), amd64_x32_linux_init_abi(), amd64_x32_pseudo_register_type(), amd64fbsd_init_abi(), amd64nbsd_init_abi(), amd64obsd_init_abi(), amd64obsd_regset_from_core_section(), amd64obsd_supply_regset(), areg_number(), arm_breakpoint_from_pc(), arm_displaced_init_closure(), arm_dump_tdep(), arm_ext_type(), arm_get_longjmp_target(), arm_get_next_pc_raw(), arm_linux_get_syscall_number(), arm_linux_init_abi(), arm_linux_regset_from_core_section(), arm_neon_double_type(), arm_neon_quad_type(), arm_netbsd_aout_init_abi(), arm_netbsd_elf_init_abi(), arm_netbsd_init_abi_common(), arm_record_coproc_data_proc(), arm_return_value(), arm_show_abi(), arm_show_force_mode(), arm_symbian_init_abi(), arm_vfp_abi_for_function(), arm_wince_init_abi(), armobsd_init_abi(), arreg_number(), avr_frame_prev_register(), avr_frame_unwind_cache(), avr_push_dummy_call(), avr_register_type(), avr_scan_prologue(), bfin_abi(), bfin_push_dummy_call(), branch_dest(), call0_frame_cache(), call0_track_op(), check_for_saved(), cris_breakpoint_from_pc(), cris_dump_tdep(), cris_frame_unwind_cache(), cris_gdbarch_init(), cris_linux_init_abi(), cris_register_size(), cris_sigtramp_frame_unwind_cache(), cris_skip_prologue(), cris_spec_reg_applicable(), cris_supply_gregset(), crisv32_single_step_through_delay(), current_me_module(), deprecated_mips_set_processor_regs_hack(), dfp_pseudo_register_read(), dfp_pseudo_register_write(), dicos_init_abi(), do_ppc_sysv_return_value(), do_windows_fetch_inferior_registers(), e500_move_ev_register(), efpr_pseudo_register_read(), efpr_pseudo_register_write(), fetch_all_gp_regs(), fetch_altivec_register(), fetch_fp_regs(), fetch_gp_regs(), fetch_ppc_registers(), fetch_register(), fetch_regs_kernel_thread(), fetch_regs_user_thread(), fetch_spe_register(), fetch_vsx_register(), fill_fprs(), fill_gprs32(), fill_gprs64(), fill_gregset(), fill_sprs32(), fill_sprs64(), fill_vrregset(), fill_vsxregset(), frv_abi(), frv_linux_sigtramp_frame_cache(), frv_register_name(), get_decimal_float_return_value(), getfpregs_supplies(), getregs_supplies(), hppa32_hpux_find_global_pointer(), hppa32_push_dummy_call(), hppa64_hpux_find_global_pointer(), hppa64_push_dummy_call(), hppa_dump_tdep(), hppa_hpux_elf_init_abi(), hppa_hpux_init_abi(), hppa_hpux_sigtramp_frame_unwind_cache(), hppa_hpux_som_init_abi(), hppa_hpux_sr_for_addr(), hppa_linux_init_abi(), hppa_linux_supply_regset(), hppa_stub_unwind_sniffer(), hppabsd_init_abi(), hppanbsd_sigtramp_cache_init(), i386_byte_regnum_p(), i386_collect_fpregset(), i386_collect_gregset(), i386_cygwin_init_abi(), i386_darwin_init_abi(), i386_darwin_push_dummy_call(), i386_dbx_reg_to_regnum(), i386_dicos_init_abi(), i386_dword_regnum_p(), i386_extract_return_value(), i386_fp_regnum_p(), i386_fpc_regnum_p(), i386_get_longjmp_target(), i386_go32_init_abi(), i386_linux_init_abi(), i386_mmx_regnum_p(), i386_mmx_regnum_to_fp_regnum(), i386_mmx_type(), i386_mxcsr_regnum_p(), i386_process_record(), i386_pseudo_register_name(), i386_pseudo_register_read_into_value(), i386_pseudo_register_write(), i386_record_floats(), i386_reg_struct_return_p(), i386_register_reggroup_p(), i386_regset_from_core_section(), i386_sigtramp_frame_cache(), i386_sigtramp_frame_sniffer(), i386_sol2_init_abi(), i386_store_return_value(), i386_supply_fpregset(), i386_supply_gregset(), i386_svr4_init_abi(), i386_svr4_reg_to_regnum(), i386_windows_regset_from_core_section(), i386_word_regnum_p(), i386_xmm_regnum_p(), i386_ymm_regnum_p(), i386_ymm_type(), i386_ymmh_regnum_p(), i386bsd_init_abi(), i386fbsd4_init_abi(), i386fbsdaout_init_abi(), i386gnu_init_abi(), i386nbsd_init_abi(), i386nbsd_sigtramp_cache_init(), i386nbsdelf_init_abi(), i386nto_init_abi(), i386nto_register_area(), i386nto_supply_gregset(), i386obsd_aout_regset_from_core_section(), i386obsd_aout_supply_regset(), i386obsd_elf_init_abi(), i386obsd_init_abi(), i387_collect_fsave(), i387_collect_fxsave(), i387_collect_xsave(), i387_ext_type(), i387_print_float_info(), i387_return_value(), i387_supply_fsave(), i387_supply_fxsave(), i387_supply_xsave(), ia64_ext_type(), ia64_find_global_pointer(), ia64_hpux_init_abi(), ia64_linux_init_abi(), ia64_push_dummy_call(), ia64_sigtramp_frame_init_saved_regs(), ia64_sigtramp_frame_sniffer(), init_sim_regno_table(), internalize_unwinds(), is_micromips_isa(), is_mips16_isa(), m32c_analyze_prologue(), m32c_debug_info_reg_to_regnum(), m32c_dummy_id(), m32c_frame_base(), m32c_is_1st_arg_reg(), m32c_is_arg_reg(), m32c_is_arg_spill(), m32c_is_struct_return(), m32c_prev_register(), m32c_pseudo_register_read(), m32c_pseudo_register_write(), m32c_push_dummy_call(), m32c_pushm_is_reg_save(), m32c_pv_enter(), m32c_pv_pushm(), m32c_r3r2r1r0_read(), m32c_r3r2r1r0_write(), m32c_read_flg(), m32c_register_name(), m32c_register_reggroup_p(), m32c_register_sim_regno(), m32c_register_type(), m32c_return_value(), m32c_skip_trampoline_code(), m32c_unwind_pc(), m32c_unwind_sp(), m32c_virtual_frame_pointer(), m32r_linux_init_abi(), m32r_linux_regset_from_core_section(), m68881_ext_type(), m68hc11_scan_prologue(), m68k_dump_tdep(), m68k_get_longjmp_target(), m68k_linux_init_abi(), m68k_linux_sigtramp_frame_cache(), m68k_ps_type(), m68k_push_dummy_call(), m68k_reg_struct_return_p(), m68k_register_type(), m68k_svr4_extract_return_value(), m68k_svr4_init_abi(), m68k_svr4_store_return_value(), m68kbsd_aout_init_abi(), m68kbsd_elf_init_abi(), m68kbsd_init_abi(), make_regs(), make_types(), me_module_register_set(), mep_register_name(), microblaze_linux_init_abi(), microblaze_linux_sigtramp_cache(), mips32_next_pc(), mips_abi(), mips_addr_bits_remove(), mips_dump_tdep(), mips_eabi_return_value(), mips_gdbarch_init(), mips_isa_regsize(), mips_linux_get_syscall_number(), mips_linux_init_abi(), mips_linux_regset_from_core_section(), mips_n32n64_return_value(), mips_o32_return_value(), mips_o64_return_value(), mips_register_name(), mips_regnum(), mn10300_dump_tdep(), mn10300_frame_prev_register(), msp430_analyze_prologue(), msp430_gdbarch_init(), msp430_push_dummy_call(), msp430_return_value(), mt_register_type(), nios2_get_longjmp_target(), nios2_get_next_pc(), nios2_linux_init_abi(), parse_spufs_run(), ppc64_standard_linkage1_target(), ppc64_standard_linkage2_target(), ppc64_standard_linkage3_target(), ppc64_sysv_abi_push_dummy_call(), ppc64_sysv_abi_return_value(), ppc_altivec_support_p(), ppc_collect_fpregset(), ppc_collect_gregset(), ppc_collect_vrregset(), ppc_collect_vsxregset(), ppc_dwarf2_frame_init_reg(), ppc_floating_point_unit_p(), ppc_linux_get_syscall_number(), ppc_linux_init_abi(), ppc_linux_regset_from_core_section(), ppc_linux_sigtramp_cache(), ppc_register_u_addr(), ppc_skip_trampoline_code(), ppc_supply_fpregset(), ppc_supply_gregset(), ppc_supply_vrregset(), ppc_supply_vsxregset(), ppc_sysv_abi_push_dummy_call(), ppc_vsx_support_p(), ppcfbsd_init_abi(), ppcfbsd_regset_from_core_section(), ppcfbsd_sigtramp_frame_cache(), ppcfbsd_supply_pcb(), ppcnbsd_sigtramp_cache_init(), ppcnbsd_supply_pcb(), ppcobsd_sigtramp_frame_cache(), ppcobsd_supply_pcb(), ppu2spu_sniffer(), regmap(), rl78_register_type(), rs6000_aix_extract_ld_info(), rs6000_aix_init_osabi(), rs6000_builtin_type_vec128(), rs6000_builtin_type_vec64(), rs6000_convert_from_func_ptr_addr(), rs6000_convert_register_p(), rs6000_dump_tdep(), rs6000_dwarf2_reg_to_regnum(), rs6000_fetch_inferior_registers(), rs6000_frame_cache(), rs6000_gdbarch_init(), rs6000_in_function_epilogue_p(), rs6000_lynx178_push_dummy_call(), rs6000_lynx178_return_value(), rs6000_pseudo_register_read(), rs6000_pseudo_register_reggroup_p(), rs6000_pseudo_register_type(), rs6000_pseudo_register_write(), rs6000_push_dummy_call(), rs6000_register_name(), rs6000_register_sim_regno(), rs6000_return_value(), rs6000_skip_trampoline_code(), rs6000_stab_reg_to_regnum(), rs6000_store_inferior_registers(), s390_dwarf2_frame_init_reg(), s390_dwarf_reg_to_regnum(), s390_gdbarch_init(), s390_pseudo_register_name(), s390_pseudo_register_read(), s390_pseudo_register_reggroup_p(), s390_pseudo_register_type(), s390_pseudo_register_write(), s390_push_dummy_call(), s390_register_call_saved(), s390_regset_from_core_section(), s390_sigtramp_frame_unwind_cache(), s390_unwind_pc(), s390_unwind_pseudo_register(), s390_write_pc(), score7_linux_regset_from_core_section(), set_dwarf_regnum(), sh64_analyze_prologue(), sh_corefile_collect_regset(), sh_corefile_supply_regset(), sh_linux_init_abi(), sh_regset_from_core_section(), shnbsd_init_abi(), show_fp_model(), show_mask_address(), skip_prologue(), som_solib_select(), sparc32_linux_init_abi(), sparc32_sol2_init_abi(), sparc32nbsd_init_abi(), sparc32obsd_init_abi(), sparc64_fprs_type(), sparc64_fsr_type(), sparc64_init_abi(), sparc64_linux_init_abi(), sparc64_linux_write_pc(), sparc64_pstate_type(), sparc64_sol2_init_abi(), sparc64fbsd_init_abi(), sparc64nbsd_init_abi(), sparc64obsd_init_abi(), sparc_analyze_control_transfer(), sparc_analyze_prologue(), sparc_fsr_type(), sparc_linux_write_pc(), sparc_psr_type(), sparc_regset_from_core_section(), sparc_software_single_step(), sparc_unwind_pc(), sparc_write_pc(), spe_register_p(), special_register_p(), spu_builtin_type_vec128(), spu_dummy_id(), spu_frame_unwind_cache(), spu_gdbarch_id(), spu_gdbarch_init(), spu_get_longjmp_target(), spu_objfile_from_frame(), spu_read_pc(), spu_unwind_pc(), spu_unwind_sp(), store_all_gp_regs(), store_altivec_register(), store_fp_regs(), store_gp_regs(), store_ppc_registers(), store_register(), store_regs_kernel_thread(), store_regs_user_thread(), store_spe_register(), store_vsx_register(), supply_fprs(), supply_gprs64(), supply_gregset_reg(), supply_sprs32(), supply_sprs64(), supply_vrregset(), supply_vsxregset(), thumb_get_next_pc_raw(), thumb_record_ldm_stm_swi(), tic6x_breakpoint_from_pc(), tic6x_gdbarch_init(), tic6x_get_next_pc(), tic6x_linux_rt_sigreturn_init(), tic6x_register_sigcontext_offset(), tic6x_uclinux_init_abi(), v850_gdbarch_init(), vsx_pseudo_register_read(), vsx_pseudo_register_write(), vsx_register_p(), x86_darwin_init_abi_64(), xtensa_extract_return_value(), xtensa_frame_prev_register(), xtensa_pseudo_register_read(), xtensa_pseudo_register_write(), xtensa_reg_to_regnum(), xtensa_register_name(), xtensa_register_reggroup_p(), xtensa_register_type(), xtensa_scan_prologue(), xtensa_store_return_value(), xtensa_supply_gregset(), and xtensa_verify_config().
CORE_ADDR gdbarch_unwind_pc (struct gdbarch * gdbarch, struct frame_info * next_frame)
Definition at line 2864 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::unwind_pc.
Referenced by dwarf2_tailcall_sniffer_first(), and frame_unwind_pc_if_available().
int gdbarch_unwind_pc_p (struct gdbarch * gdbarch)
Definition at line 2857 of file gdbarch.c.
References gdb_assert, and gdbarch::unwind_pc.
Referenced by frame_unwind_pc_if_available(), and gdbarch_dump().
CORE_ADDR gdbarch_unwind_sp (struct gdbarch * gdbarch, struct frame_info * next_frame)
Definition at line 2888 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::unwind_sp.
Referenced by get_frame_sp().
int gdbarch_unwind_sp_p (struct gdbarch * gdbarch)
Definition at line 2881 of file gdbarch.c.
References gdb_assert, and gdbarch::unwind_sp.
Referenced by gdbarch_dump(), and get_frame_sp().
struct value* gdbarch_value_from_register (struct gdbarch * gdbarch, struct type * type, int regnum, struct frame_info * frame) [read]
Definition at line 2499 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::value_from_register.
Referenced by value_from_register().
void gdbarch_value_to_register (struct gdbarch * gdbarch, struct frame_info * frame, int regnum, struct type * type, const gdb_byte * buf)
Definition at line 2482 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::value_to_register.
Referenced by value_assign().
int gdbarch_vbit_in_delta (struct gdbarch * gdbarch)
Definition at line 3560 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::vbit_in_delta.
Referenced by gnuv3_decode_method_ptr(), and gnuv3_make_method_ptr().
void gdbarch_virtual_frame_pointer (struct gdbarch * gdbarch, CORE_ADDR pc, int * frame_regnum, LONGEST * frame_offset)
Definition at line 1837 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::virtual_frame_pointer.
Referenced by encode_actions_and_make_cleanup(), gen_frame_args_address(), and gen_frame_locals_address().
int gdbarch_vtable_function_descriptors (struct gdbarch * gdbarch)
Definition at line 3543 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::vtable_function_descriptors.
Referenced by gnuv3_get_virtual_fn(), and print_one_vtable().
void gdbarch_write_pc (struct gdbarch * gdbarch, struct regcache * regcache, CORE_ADDR val)
Definition at line 1820 of file gdbarch.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_debug, and gdbarch::write_pc.
Referenced by regcache_write_pc().
int gdbarch_write_pc_p (struct gdbarch * gdbarch)
Definition at line 1813 of file gdbarch.c.
References gdb_assert, and gdbarch::write_pc.
Referenced by gdbarch_dump(), and regcache_write_pc().
static const char* pformat (const struct floatformat ** format) [static]
Definition at line 72 of file gdbarch.c.
Referenced by gdbarch_dump().
static const char* pstring (const char * string) [static]
Definition at line 82 of file gdbarch.c.
References string.
Referenced by gdbarch_dump().
void register_gdbarch_init (enum bfd_architecture bfd_architecture , gdbarch_init_ftype * init)
Definition at line 4644 of file gdbarch.c.
References gdbarch_register().
Referenced by _initialize_avr_tdep(), _initialize_bfin_tdep(), _initialize_h8300_tdep(), _initialize_iq2000_tdep(), _initialize_lm32_tdep(), _initialize_m32c_tdep(), _initialize_m68hc11_tdep(), _initialize_mep_tdep(), _initialize_msp430_tdep(), _initialize_mt_tdep(), _initialize_rl78_tdep(), _initialize_rx_tdep(), _initialize_s390_tdep(), _initialize_spu_tdep(), _initialize_tic6x_tdep(), _initialize_tilegx_tdep(), _initialize_v850_tdep(), and _initialize_xstormy16_tdep().
void set_gdbarch_addr_bit (struct gdbarch * gdbarch, int addr_bit)
Definition at line 1746 of file gdbarch.c.
References gdbarch::addr_bit.
Referenced by avr_gdbarch_init(), h8300_gdbarch_init(), m68hc11_gdbarch_init(), make_types(), msp430_gdbarch_init(), nios2_gdbarch_init(), rl78_gdbarch_init(), spu_gdbarch_init(), tic6x_gdbarch_init(), tilegx_gdbarch_init(), v850_gdbarch_init(), and xstormy16_gdbarch_init().
void set_gdbarch_addr_bits_remove (struct gdbarch * gdbarch, gdbarch_addr_bits_remove_ftype addr_bits_remove)
Definition at line 3013 of file gdbarch.c.
References gdbarch::addr_bits_remove.
Referenced by arm_gdbarch_init(), hppa_gdbarch_init(), m88k_gdbarch_init(), mips_gdbarch_init(), rl78_gdbarch_init(), and s390_gdbarch_init().
void set_gdbarch_address_class_name_to_type_flags (struct gdbarch * gdbarch, gdbarch_address_class_name_to_type_flags_ftype address_class_name_to_type_flags)
Definition at line 3286 of file gdbarch.c.
References gdbarch::address_class_name_to_type_flags.
Referenced by s390_gdbarch_init(), and spu_gdbarch_init().
void set_gdbarch_address_class_type_flags (struct gdbarch * gdbarch, gdbarch_address_class_type_flags_ftype address_class_type_flags)
Definition at line 3238 of file gdbarch.c.
References gdbarch::address_class_type_flags.
Referenced by s390_gdbarch_init(), and spu_gdbarch_init().
void set_gdbarch_address_class_type_flags_to_name (struct gdbarch * gdbarch, gdbarch_address_class_type_flags_to_name_ftype address_class_type_flags_to_name)
Definition at line 3262 of file gdbarch.c.
References gdbarch::address_class_type_flags_to_name.
Referenced by s390_gdbarch_init(), and spu_gdbarch_init().
void set_gdbarch_address_to_pointer (struct gdbarch * gdbarch, gdbarch_address_to_pointer_ftype address_to_pointer)
Definition at line 2543 of file gdbarch.c.
References gdbarch::address_to_pointer.
Referenced by avr_gdbarch_init(), iq2000_gdbarch_init(), m32c_gdbarch_init(), mips_gdbarch_init(), rl78_gdbarch_init(), spu_gdbarch_init(), and xstormy16_gdbarch_init().
void set_gdbarch_adjust_breakpoint_address (struct gdbarch * gdbarch, gdbarch_adjust_breakpoint_address_ftype adjust_breakpoint_address)
Definition at line 2724 of file gdbarch.c.
References adjust_breakpoint_address(), and gdbarch::adjust_breakpoint_address.
Referenced by arm_gdbarch_init(), frv_gdbarch_init(), mips_gdbarch_init(), and score_gdbarch_init().
void set_gdbarch_auto_charset (struct gdbarch * gdbarch, gdbarch_auto_charset_ftype auto_charset)
Definition at line 4270 of file gdbarch.c.
References gdbarch::auto_charset.
void set_gdbarch_auto_wide_charset (struct gdbarch * gdbarch, gdbarch_auto_wide_charset_ftype auto_wide_charset)
Definition at line 4287 of file gdbarch.c.
References gdbarch::auto_wide_charset.
Referenced by amd64_windows_init_abi(), i386_cygwin_init_abi(), and rs6000_aix_init_osabi().
void set_gdbarch_ax_pseudo_register_collect (struct gdbarch * gdbarch, gdbarch_ax_pseudo_register_collect_ftype ax_pseudo_register_collect)
Definition at line 1978 of file gdbarch.c.
References gdbarch::ax_pseudo_register_collect.
Referenced by mips_gdbarch_init().
void set_gdbarch_ax_pseudo_register_push_stack (struct gdbarch * gdbarch, gdbarch_ax_pseudo_register_push_stack_ftype ax_pseudo_register_push_stack)
Definition at line 2002 of file gdbarch.c.
References gdbarch::ax_pseudo_register_push_stack.
Referenced by mips_gdbarch_init().
void set_gdbarch_believe_pcc_promotion (struct gdbarch * gdbarch, int believe_pcc_promotion)
Definition at line 2441 of file gdbarch.c.
References gdbarch::believe_pcc_promotion.
Referenced by bfin_gdbarch_init(), h8300_gdbarch_init(), hppa_gdbarch_init(), m68hc11_gdbarch_init(), m68k_gdbarch_init(), rs6000_gdbarch_init(), s390_gdbarch_init(), sh64_gdbarch_init(), sh_gdbarch_init(), vax_gdbarch_init(), and xtensa_gdbarch_init().
void set_gdbarch_bits_big_endian (struct gdbarch * gdbarch, int bits_big_endian)
Definition at line 1494 of file gdbarch.c.
References gdbarch::bits_big_endian.
void set_gdbarch_breakpoint_from_pc (struct gdbarch * gdbarch, gdbarch_breakpoint_from_pc_ftype breakpoint_from_pc)
Definition at line 2683 of file gdbarch.c.
References gdbarch::breakpoint_from_pc.
Referenced by aarch64_gdbarch_init(), alpha_gdbarch_init(), arm_gdbarch_init(), avr_gdbarch_init(), bfin_gdbarch_init(), cris_gdbarch_init(), frv_gdbarch_init(), h8300_gdbarch_init(), hppa_gdbarch_init(), i386_gdbarch_init(), ia64_gdbarch_init(), iq2000_gdbarch_init(), lm32_gdbarch_init(), m32c_gdbarch_init(), m32r_gdbarch_init(), m68hc11_gdbarch_init(), m68k_gdbarch_init(), m88k_gdbarch_init(), mep_gdbarch_init(), microblaze_gdbarch_init(), mips_gdbarch_init(), mn10300_gdbarch_init(), moxie_gdbarch_init(), msp430_gdbarch_init(), mt_gdbarch_init(), nios2_gdbarch_init(), rl78_gdbarch_init(), rs6000_gdbarch_init(), rx_gdbarch_init(), s390_gdbarch_init(), score_gdbarch_init(), sh64_gdbarch_init(), sh_gdbarch_init(), sparc32_gdbarch_init(), spu_gdbarch_init(), tic6x_gdbarch_init(), tilegx_gdbarch_init(), v850_gdbarch_init(), vax_gdbarch_init(), xstormy16_gdbarch_init(), and xtensa_gdbarch_init().
void set_gdbarch_call_dummy_location (struct gdbarch * gdbarch, int call_dummy_location)
Definition at line 2261 of file gdbarch.c.
References gdbarch::call_dummy_location.
Referenced by hppa_hpux_init_abi(), i386_gdbarch_init(), ia64_hpux_init_abi(), microblaze_gdbarch_init(), mips_gdbarch_init(), score_gdbarch_init(), sparc32_gdbarch_init(), sparc64_init_abi(), and spu_gdbarch_init().
void set_gdbarch_cannot_fetch_register (struct gdbarch * gdbarch, gdbarch_cannot_fetch_register_ftype cannot_fetch_register)
Definition at line 2384 of file gdbarch.c.
References gdbarch::cannot_fetch_register.
Referenced by alpha_gdbarch_init(), cris_gdbarch_init(), hppa_gdbarch_init(), mipsnbsd_init_abi(), and tilegx_gdbarch_init().
void set_gdbarch_cannot_step_breakpoint (struct gdbarch * gdbarch, int cannot_step_breakpoint)
Definition at line 3197 of file gdbarch.c.
References gdbarch::cannot_step_breakpoint.
Referenced by aarch64_gdbarch_init(), alpha_gdbarch_init(), and spu_gdbarch_init().
void set_gdbarch_cannot_store_register (struct gdbarch * gdbarch, gdbarch_cannot_store_register_ftype cannot_store_register)
Definition at line 2401 of file gdbarch.c.
References gdbarch::cannot_store_register.
Referenced by alpha_gdbarch_init(), cris_gdbarch_init(), hppa_gdbarch_init(), ia64_hpux_init_abi(), lm32_gdbarch_init(), mipsnbsd_init_abi(), s390_gdbarch_init(), and tilegx_gdbarch_init().
void set_gdbarch_char_signed (struct gdbarch * gdbarch, int char_signed)
Definition at line 1782 of file gdbarch.c.
References gdbarch::char_signed.
Referenced by aarch64_gdbarch_init(), arm_gdbarch_init(), arm_wince_init_abi(), h8300_gdbarch_init(), m68hc11_gdbarch_init(), mn10300_gdbarch_init(), msp430_gdbarch_init(), rl78_gdbarch_init(), rs6000_gdbarch_init(), rx_gdbarch_init(), s390_gdbarch_init(), spu_gdbarch_init(), v850_gdbarch_init(), and xstormy16_gdbarch_init().
void set_gdbarch_coff_make_msymbol_special (struct gdbarch * gdbarch, gdbarch_coff_make_msymbol_special_ftype coff_make_msymbol_special)
Definition at line 3180 of file gdbarch.c.
References gdbarch::coff_make_msymbol_special.
Referenced by arm_gdbarch_init().
void set_gdbarch_convert_from_func_ptr_addr (struct gdbarch * gdbarch, gdbarch_convert_from_func_ptr_addr_ftype convert_from_func_ptr_addr)
Definition at line 2996 of file gdbarch.c.
References gdbarch::convert_from_func_ptr_addr.
Referenced by frv_gdbarch_init(), hppa_gdbarch_init(), ia64_gdbarch_init(), ppc_linux_init_abi(), ppcfbsd_init_abi(), and rs6000_aix_init_osabi().
void set_gdbarch_convert_register_p (struct gdbarch * gdbarch, gdbarch_convert_register_p_ftype convert_register_p)
Definition at line 2458 of file gdbarch.c.
References gdbarch::convert_register_p.
Referenced by alpha_gdbarch_init(), amd64_init_abi(), i386_gdbarch_init(), ia64_gdbarch_init(), m68k_gdbarch_init(), mips_gdbarch_init(), and rs6000_gdbarch_init().
void set_gdbarch_core_info_proc (struct gdbarch * gdbarch, gdbarch_core_info_proc_ftype core_info_proc)
Definition at line 4385 of file gdbarch.c.
References gdbarch::core_info_proc, and core_info_proc().
Referenced by linux_init_abi().
void set_gdbarch_core_pid_to_str (struct gdbarch * gdbarch, gdbarch_core_pid_to_str_ftype core_pid_to_str)
Definition at line 3511 of file gdbarch.c.
References gdbarch::core_pid_to_str, and core_pid_to_str().
Referenced by amd64_sol2_init_abi(), i386_cygwin_init_abi(), i386_sol2_init_abi(), linux_init_abi(), sparc32_sol2_init_abi(), and sparc64_sol2_init_abi().
void set_gdbarch_core_read_description (struct gdbarch * gdbarch, gdbarch_core_read_description_ftype core_read_description)
Definition at line 3792 of file gdbarch.c.
References gdbarch::core_read_description, and core_read_description().
Referenced by amd64_linux_init_abi_common(), arm_linux_init_abi(), i386_linux_init_abi(), mips_linux_init_abi(), ppc_linux_init_abi(), and s390_gdbarch_init().
void set_gdbarch_core_regset_sections (struct gdbarch * gdbarch, struct core_regset_section * core_regset_sections)
Definition at line 3367 of file gdbarch.c.
References gdbarch::core_regset_sections.
Referenced by amd64_linux_init_abi_common(), arm_linux_init_abi(), i386_linux_init_abi(), ppc_linux_init_abi(), and s390_gdbarch_init().
void set_gdbarch_core_xfer_shared_libraries (struct gdbarch * gdbarch, gdbarch_core_xfer_shared_libraries_ftype core_xfer_shared_libraries)
Definition at line 3463 of file gdbarch.c.
References gdbarch::core_xfer_shared_libraries.
Referenced by i386_cygwin_init_abi().
void set_gdbarch_core_xfer_shared_libraries_aix (struct gdbarch * gdbarch, gdbarch_core_xfer_shared_libraries_aix_ftype core_xfer_shared_libraries_aix)
Definition at line 3487 of file gdbarch.c.
References gdbarch::core_xfer_shared_libraries_aix.
Referenced by rs6000_aix_init_osabi().
void set_gdbarch_decr_pc_after_break (struct gdbarch * gdbarch, CORE_ADDR decr_pc_after_break)
Definition at line 2775 of file gdbarch.c.
References gdbarch::decr_pc_after_break.
Referenced by alpha_gdbarch_init(), bfin_gdbarch_init(), dicos_init_abi(), i386_gdbarch_init(), i386nto_init_abi(), lm32_gdbarch_init(), m68k_gdbarch_init(), m68k_linux_init_abi(), m68kbsd_init_abi(), mep_gdbarch_init(), msp430_gdbarch_init(), mt_gdbarch_init(), rl78_gdbarch_init(), rx_gdbarch_init(), s390_gdbarch_init(), spu_gdbarch_init(), and xtensa_gdbarch_init().
void set_gdbarch_deprecated_fp_regnum (struct gdbarch * gdbarch, int deprecated_fp_regnum)
Definition at line 2220 of file gdbarch.c.
References gdbarch::deprecated_fp_regnum.
Referenced by frv_gdbarch_init(), and rs6000_gdbarch_init().
void set_gdbarch_deprecated_function_start_offset (struct gdbarch * gdbarch, CORE_ADDR deprecated_function_start_offset)
Definition at line 2792 of file gdbarch.c.
References gdbarch::deprecated_function_start_offset.
Referenced by vax_gdbarch_init().
void set_gdbarch_displaced_step_copy_insn (struct gdbarch * gdbarch, gdbarch_displaced_step_copy_insn_ftype displaced_step_copy_insn)
Definition at line 3643 of file gdbarch.c.
References gdbarch::displaced_step_copy_insn.
Referenced by amd64_linux_init_abi_common(), arm_linux_init_abi(), i386_linux_init_abi(), rs6000_aix_init_osabi(), rs6000_gdbarch_init(), and s390_gdbarch_init().
void set_gdbarch_displaced_step_fixup (struct gdbarch * gdbarch, gdbarch_displaced_step_fixup_ftype displaced_step_fixup)
Definition at line 3685 of file gdbarch.c.
References gdbarch::displaced_step_fixup, and displaced_step_fixup().
Referenced by amd64_linux_init_abi_common(), arm_linux_init_abi(), i386_linux_init_abi(), rs6000_aix_init_osabi(), rs6000_gdbarch_init(), and s390_gdbarch_init().
void set_gdbarch_displaced_step_free_closure (struct gdbarch * gdbarch, gdbarch_displaced_step_free_closure_ftype displaced_step_free_closure)
Definition at line 3702 of file gdbarch.c.
References gdbarch::displaced_step_free_closure.
Referenced by amd64_linux_init_abi_common(), arm_linux_init_abi(), i386_linux_init_abi(), rs6000_aix_init_osabi(), rs6000_gdbarch_init(), and s390_gdbarch_init().
void set_gdbarch_displaced_step_hw_singlestep (struct gdbarch * gdbarch, gdbarch_displaced_step_hw_singlestep_ftype displaced_step_hw_singlestep)
Definition at line 3660 of file gdbarch.c.
References gdbarch::displaced_step_hw_singlestep.
Referenced by rs6000_gdbarch_init().
void set_gdbarch_displaced_step_location (struct gdbarch * gdbarch, gdbarch_displaced_step_location_ftype displaced_step_location)
Definition at line 3719 of file gdbarch.c.
References gdbarch::displaced_step_location.
Referenced by amd64_linux_init_abi_common(), arm_linux_init_abi(), i386_linux_init_abi(), ppc_linux_init_abi(), rs6000_aix_init_osabi(), rs6000_gdbarch_init(), and s390_gdbarch_init().
void set_gdbarch_double_bit (struct gdbarch * gdbarch, int double_bit)
Definition at line 1662 of file gdbarch.c.
References gdbarch::double_bit.
Referenced by aarch64_gdbarch_init(), alpha_gdbarch_init(), avr_gdbarch_init(), cris_gdbarch_init(), frv_gdbarch_init(), h8300_gdbarch_init(), ia64_gdbarch_init(), iq2000_gdbarch_init(), lm32_gdbarch_init(), m68hc11_gdbarch_init(), mips_gdbarch_init(), msp430_gdbarch_init(), mt_gdbarch_init(), nios2_gdbarch_init(), rl78_gdbarch_init(), rs6000_gdbarch_init(), rx_gdbarch_init(), score_gdbarch_init(), sh64_gdbarch_init(), sh_gdbarch_init(), spu_gdbarch_init(), tic6x_gdbarch_init(), tilegx_gdbarch_init(), v850_gdbarch_init(), and xstormy16_gdbarch_init().
void set_gdbarch_double_format (struct gdbarch * gdbarch, const struct floatformat ** double_format)
Definition at line 1678 of file gdbarch.c.
References gdbarch::double_format.
Referenced by aarch64_gdbarch_init(), arm_gdbarch_init(), avr_gdbarch_init(), h8300_gdbarch_init(), iq2000_gdbarch_init(), m68hc11_gdbarch_init(), msp430_gdbarch_init(), mt_gdbarch_init(), nios2_gdbarch_init(), rl78_gdbarch_init(), rx_gdbarch_init(), sh_gdbarch_init(), spu_gdbarch_init(), tic6x_gdbarch_init(), and vax_gdbarch_init().
void set_gdbarch_dummy_id (struct gdbarch * gdbarch, gdbarch_dummy_id_ftype dummy_id)
Definition at line 2203 of file gdbarch.c.
References gdbarch::dummy_id.
Referenced by aarch64_gdbarch_init(), alpha_gdbarch_init(), amd64_init_abi(), arm_gdbarch_init(), avr_gdbarch_init(), bfin_gdbarch_init(), cris_gdbarch_init(), frv_gdbarch_init(), h8300_gdbarch_init(), hppa_gdbarch_init(), i386_gdbarch_init(), ia64_gdbarch_init(), ia64_hpux_init_abi(), iq2000_gdbarch_init(), lm32_gdbarch_init(), m32c_gdbarch_init(), m32r_gdbarch_init(), m68hc11_gdbarch_init(), m68k_gdbarch_init(), m88k_gdbarch_init(), mep_gdbarch_init(), mips_gdbarch_init(), mn10300_frame_unwind_init(), moxie_gdbarch_init(), msp430_gdbarch_init(), mt_gdbarch_init(), nios2_gdbarch_init(), rl78_gdbarch_init(), rs6000_gdbarch_init(), rx_gdbarch_init(), s390_gdbarch_init(), score_gdbarch_init(), sh64_gdbarch_init(), sh_gdbarch_init(), sparc32_gdbarch_init(), spu_gdbarch_init(), tic6x_gdbarch_init(), tilegx_gdbarch_init(), v850_gdbarch_init(), vax_gdbarch_init(), xstormy16_gdbarch_init(), and xtensa_gdbarch_init().
void set_gdbarch_dwarf2_addr_size (struct gdbarch * gdbarch, int dwarf2_addr_size)
Definition at line 1764 of file gdbarch.c.
References gdbarch::dwarf2_addr_size.
Referenced by msp430_gdbarch_init(), rl78_gdbarch_init(), and xstormy16_gdbarch_init().
void set_gdbarch_dwarf2_reg_to_regnum (struct gdbarch * gdbarch, gdbarch_dwarf2_reg_to_regnum_ftype dwarf2_reg_to_regnum)
Definition at line 2138 of file gdbarch.c.
References gdbarch::dwarf2_reg_to_regnum.
Referenced by aarch64_gdbarch_init(), amd64_init_abi(), arm_gdbarch_init(), avr_gdbarch_init(), bfin_gdbarch_init(), cris_gdbarch_init(), h8300_gdbarch_init(), hppa_gdbarch_init(), hppa_linux_init_abi(), i386_gdbarch_init(), ia64_gdbarch_init(), m68k_gdbarch_init(), make_regs(), mep_gdbarch_init(), microblaze_gdbarch_init(), mips_gdbarch_init(), mn10300_gdbarch_init(), msp430_gdbarch_init(), nios2_gdbarch_init(), rl78_gdbarch_init(), rs6000_gdbarch_init(), s390_gdbarch_init(), tilegx_gdbarch_init(), and xtensa_gdbarch_init().
void set_gdbarch_ecoff_reg_to_regnum (struct gdbarch * gdbarch, gdbarch_ecoff_reg_to_regnum_ftype ecoff_reg_to_regnum)
Definition at line 2104 of file gdbarch.c.
References gdbarch::ecoff_reg_to_regnum.
Referenced by h8300_gdbarch_init(), and mips_gdbarch_init().
void set_gdbarch_elf_make_msymbol_special (struct gdbarch * gdbarch, gdbarch_elf_make_msymbol_special_ftype elf_make_msymbol_special)
Definition at line 3163 of file gdbarch.c.
References gdbarch::elf_make_msymbol_special.
Referenced by arm_gdbarch_init(), m68hc11_gdbarch_init(), mips_gdbarch_init(), ppc_linux_init_abi(), ppcfbsd_init_abi(), and sh64_gdbarch_init().
void set_gdbarch_elfcore_write_linux_prpsinfo (struct gdbarch * gdbarch, gdbarch_elfcore_write_linux_prpsinfo_ftype elfcore_write_linux_prpsinfo)
Definition at line 3415 of file gdbarch.c.
References gdbarch::elfcore_write_linux_prpsinfo.
Referenced by ppc_linux_init_abi().
void set_gdbarch_fast_tracepoint_valid_at (struct gdbarch * gdbarch, gdbarch_fast_tracepoint_valid_at_ftype fast_tracepoint_valid_at)
Definition at line 4253 of file gdbarch.c.
References gdbarch::fast_tracepoint_valid_at.
Referenced by i386_gdbarch_init().
void set_gdbarch_fetch_pointer_argument (struct gdbarch * gdbarch, gdbarch_fetch_pointer_argument_ftype fetch_pointer_argument)
Definition at line 3327 of file gdbarch.c.
References gdbarch::fetch_pointer_argument.
Referenced by hppa_gdbarch_init(), i386_gdbarch_init(), and rs6000_gdbarch_init().
void set_gdbarch_fetch_tls_load_module_address (struct gdbarch * gdbarch, gdbarch_fetch_tls_load_module_address_ftype fetch_tls_load_module_address)
Definition at line 2833 of file gdbarch.c.
References gdbarch::fetch_tls_load_module_address.
Referenced by aarch64_linux_init_abi(), alpha_linux_init_abi(), amd64_linux_init_abi_common(), arm_linux_init_abi(), cris_linux_init_abi(), frv_gdbarch_init(), hppa_linux_init_abi(), i386_linux_init_abi(), ia64_linux_init_abi(), m32r_linux_init_abi(), m68k_linux_init_abi(), mips_linux_init_abi(), nios2_linux_init_abi(), ppc_linux_init_abi(), ppcfbsd_init_abi(), s390_gdbarch_init(), sh_linux_init_abi(), sparc32_linux_init_abi(), sparc64_linux_init_abi(), and tilegx_linux_init_abi().
void set_gdbarch_find_memory_regions (struct gdbarch * gdbarch, gdbarch_find_memory_regions_ftype find_memory_regions)
Definition at line 3439 of file gdbarch.c.
References gdbarch::find_memory_regions.
Referenced by linux_init_abi().
void set_gdbarch_float_bit (struct gdbarch * gdbarch, int float_bit)
Definition at line 1629 of file gdbarch.c.
References gdbarch::float_bit.
Referenced by aarch64_gdbarch_init(), alpha_gdbarch_init(), avr_gdbarch_init(), frv_gdbarch_init(), ia64_gdbarch_init(), iq2000_gdbarch_init(), lm32_gdbarch_init(), m68hc11_gdbarch_init(), mips_gdbarch_init(), msp430_gdbarch_init(), mt_gdbarch_init(), nios2_gdbarch_init(), rl78_gdbarch_init(), rs6000_gdbarch_init(), rx_gdbarch_init(), score_gdbarch_init(), sh64_gdbarch_init(), sh_gdbarch_init(), spu_gdbarch_init(), tic6x_gdbarch_init(), tilegx_gdbarch_init(), v850_gdbarch_init(), and xstormy16_gdbarch_init().
void set_gdbarch_float_format (struct gdbarch * gdbarch, const struct floatformat ** float_format)
Definition at line 1645 of file gdbarch.c.
References gdbarch::float_format.
Referenced by aarch64_gdbarch_init(), arm_gdbarch_init(), avr_gdbarch_init(), iq2000_gdbarch_init(), msp430_gdbarch_init(), mt_gdbarch_init(), nios2_gdbarch_init(), rl78_gdbarch_init(), rx_gdbarch_init(), spu_gdbarch_init(), tic6x_gdbarch_init(), and vax_gdbarch_init().
void set_gdbarch_fp0_regnum (struct gdbarch * gdbarch, int fp0_regnum)
Definition at line 2070 of file gdbarch.c.
References gdbarch::fp0_regnum.
Referenced by alpha_gdbarch_init(), amd64_init_abi(), hppa_gdbarch_init(), i386_gdbarch_init(), ia64_gdbarch_init(), m68hc11_gdbarch_init(), m68k_gdbarch_init(), mips_gdbarch_init(), mn10300_gdbarch_init(), rs6000_gdbarch_init(), s390_gdbarch_init(), sh64_gdbarch_init(), sh_gdbarch_init(), sparc32_gdbarch_init(), and v850_gdbarch_init().
void set_gdbarch_frame_align (struct gdbarch * gdbarch, gdbarch_frame_align_ftype frame_align)
Definition at line 2946 of file gdbarch.c.
References gdbarch::frame_align.
Referenced by aarch64_gdbarch_init(), amd64_init_abi(), arm_gdbarch_init(), bfin_gdbarch_init(), cris_gdbarch_init(), frv_gdbarch_init(), hppa_gdbarch_init(), i386_gdbarch_init(), ia64_gdbarch_init(), iq2000_gdbarch_init(), lm32_gdbarch_init(), m32r_gdbarch_init(), m68k_gdbarch_init(), mep_gdbarch_init(), mips_gdbarch_init(), moxie_gdbarch_init(), msp430_gdbarch_init(), mt_gdbarch_init(), nios2_gdbarch_init(), rl78_gdbarch_init(), rs6000_gdbarch_init(), s390_gdbarch_init(), score_gdbarch_init(), sh64_gdbarch_init(), sh_gdbarch_init(), sparc32_gdbarch_init(), sparc64_init_abi(), spu_gdbarch_init(), tic6x_gdbarch_init(), tilegx_gdbarch_init(), v850_gdbarch_init(), xstormy16_gdbarch_init(), and xtensa_gdbarch_init().
void set_gdbarch_frame_args_skip (struct gdbarch * gdbarch, CORE_ADDR frame_args_skip)
Definition at line 2850 of file gdbarch.c.
References gdbarch::frame_args_skip.
Referenced by bfin_gdbarch_init(), i386_gdbarch_init(), iq2000_gdbarch_init(), lm32_gdbarch_init(), m68k_gdbarch_init(), mep_gdbarch_init(), microblaze_gdbarch_init(), mt_gdbarch_init(), rs6000_gdbarch_init(), sparc32_gdbarch_init(), spu_gdbarch_init(), vax_gdbarch_init(), and xtensa_gdbarch_init().
void set_gdbarch_frame_num_args (struct gdbarch * gdbarch, gdbarch_frame_num_args_ftype frame_num_args)
Definition at line 2922 of file gdbarch.c.
References gdbarch::frame_num_args.
Referenced by vax_gdbarch_init().
void set_gdbarch_frame_red_zone_size (struct gdbarch * gdbarch, int frame_red_zone_size)
Definition at line 2979 of file gdbarch.c.
References gdbarch::frame_red_zone_size.
Referenced by amd64_init_abi(), rs6000_aix_init_osabi(), rs6000_gdbarch_init(), and spu_gdbarch_init().
void set_gdbarch_gcore_bfd_target (struct gdbarch * gdbarch, const char * gcore_bfd_target)
Definition at line 3536 of file gdbarch.c.
References gdbarch::gcore_bfd_target.
Referenced by ppc_linux_init_abi(), and ppcfbsd_init_abi().
void set_gdbarch_gdb_signal_from_target (struct gdbarch * gdbarch, gdbarch_gdb_signal_from_target_ftype gdb_signal_from_target)
Definition at line 3905 of file gdbarch.c.
References gdbarch::gdb_signal_from_target.
Referenced by alpha_linux_init_abi(), linux_init_abi(), mips_linux_init_abi(), sparc32_linux_init_abi(), and xtensa_linux_init_abi().
void set_gdbarch_gdb_signal_to_target (struct gdbarch * gdbarch, gdbarch_gdb_signal_to_target_ftype gdb_signal_to_target)
Definition at line 3929 of file gdbarch.c.
References gdbarch::gdb_signal_to_target.
Referenced by alpha_linux_init_abi(), linux_init_abi(), mips_linux_init_abi(), sparc32_linux_init_abi(), and xtensa_linux_init_abi().
void set_gdbarch_gen_return_address (struct gdbarch * gdbarch, gdbarch_gen_return_address_ftype gen_return_address)
Definition at line 4337 of file gdbarch.c.
References gdbarch::gen_return_address.
Referenced by amd64_init_abi(), and i386_gdbarch_init().
void set_gdbarch_get_longjmp_target (struct gdbarch * gdbarch, gdbarch_get_longjmp_target_ftype get_longjmp_target)
Definition at line 2425 of file gdbarch.c.
References gdbarch::get_longjmp_target.
Referenced by aarch64_gdbarch_init(), alpha_gdbarch_init(), amd64_init_abi(), arm_gdbarch_init(), i386_gdbarch_init(), m68k_gdbarch_init(), mips_linux_init_abi(), mipsnbsd_init_abi(), nios2_gdbarch_init(), spu_gdbarch_init(), tic6x_gdbarch_init(), and tilegx_gdbarch_init().
void set_gdbarch_get_siginfo_type (struct gdbarch * gdbarch, gdbarch_get_siginfo_type_ftype get_siginfo_type)
Definition at line 3953 of file gdbarch.c.
References gdbarch::get_siginfo_type.
Referenced by aarch64_linux_init_abi(), amd64_linux_init_abi_common(), arm_linux_init_abi(), i386_linux_init_abi(), m68k_linux_init_abi(), ppc_linux_init_abi(), s390_gdbarch_init(), and tilegx_linux_init_abi().
void set_gdbarch_get_syscall_number (struct gdbarch * gdbarch, gdbarch_get_syscall_number_ftype get_syscall_number)
Definition at line 4001 of file gdbarch.c.
References gdbarch::get_syscall_number.
Referenced by amd64_linux_init_abi_common(), arm_linux_init_abi(), bfin_linux_init_abi(), i386_linux_init_abi(), mips_linux_init_abi(), ppc_linux_init_abi(), sparc32_linux_init_abi(), and sparc64_linux_init_abi().
void set_gdbarch_half_bit (struct gdbarch * gdbarch, int half_bit)
Definition at line 1596 of file gdbarch.c.
References gdbarch::half_bit.
void set_gdbarch_half_format (struct gdbarch * gdbarch, const struct floatformat ** half_format)
Definition at line 1612 of file gdbarch.c.
References gdbarch::half_format.
void set_gdbarch_has_dos_based_file_system (struct gdbarch * gdbarch, int has_dos_based_file_system)
Definition at line 4320 of file gdbarch.c.
References gdbarch::has_dos_based_file_system.
Referenced by arm_symbian_init_abi(), i386_go32_init_abi(), and windows_init_abi().
void set_gdbarch_has_global_breakpoints (struct gdbarch * gdbarch, int has_global_breakpoints)
Definition at line 4219 of file gdbarch.c.
References gdbarch::has_global_breakpoints.
Referenced by dicos_init_abi().
void set_gdbarch_has_global_solist (struct gdbarch * gdbarch, int has_global_solist)
Definition at line 4202 of file gdbarch.c.
References gdbarch::has_global_solist.
Referenced by dicos_init_abi().
void set_gdbarch_has_shared_address_space (struct gdbarch * gdbarch, gdbarch_has_shared_address_space_ftype has_shared_address_space)
Definition at line 4236 of file gdbarch.c.
References gdbarch::has_shared_address_space.
Referenced by linux_init_abi().
void set_gdbarch_have_nonsteppable_watchpoint (struct gdbarch * gdbarch, int have_nonsteppable_watchpoint)
Definition at line 3214 of file gdbarch.c.
References gdbarch::have_nonsteppable_watchpoint.
Referenced by aarch64_gdbarch_init(), arm_gdbarch_init(), cris_gdbarch_init(), hppa_gdbarch_init(), lm32_gdbarch_init(), mips_gdbarch_init(), rs6000_gdbarch_init(), score_gdbarch_init(), and xtensa_gdbarch_init().
void set_gdbarch_in_function_epilogue_p (struct gdbarch * gdbarch, gdbarch_in_function_epilogue_p_ftype in_function_epilogue_p)
Definition at line 3146 of file gdbarch.c.
References gdbarch::in_function_epilogue_p.
Referenced by arm_gdbarch_init(), hppa_gdbarch_init(), mips_gdbarch_init(), nios2_gdbarch_init(), rs6000_gdbarch_init(), s390_gdbarch_init(), score_gdbarch_init(), sh_gdbarch_init(), spu_gdbarch_init(), tic6x_gdbarch_init(), tilegx_gdbarch_init(), and xstormy16_gdbarch_init().
void set_gdbarch_in_solib_return_trampoline (struct gdbarch * gdbarch, gdbarch_in_solib_return_trampoline_ftype in_solib_return_trampoline)
Definition at line 3129 of file gdbarch.c.
References gdbarch::in_solib_return_trampoline.
Referenced by hppa_hpux_init_abi(), mips_gdbarch_init(), msp430_gdbarch_init(), and rs6000_gdbarch_init().
void set_gdbarch_info_proc (struct gdbarch * gdbarch, gdbarch_info_proc_ftype info_proc)
Definition at line 4361 of file gdbarch.c.
References gdbarch::info_proc.
Referenced by linux_init_abi().
void set_gdbarch_inner_than (struct gdbarch * gdbarch, gdbarch_inner_than_ftype inner_than)
Definition at line 2666 of file gdbarch.c.
References gdbarch::inner_than.
Referenced by aarch64_gdbarch_init(), alpha_gdbarch_init(), arm_gdbarch_init(), avr_gdbarch_init(), bfin_gdbarch_init(), cris_gdbarch_init(), frv_gdbarch_init(), h8300_gdbarch_init(), hppa_gdbarch_init(), i386_gdbarch_init(), ia64_gdbarch_init(), iq2000_gdbarch_init(), lm32_gdbarch_init(), m32c_gdbarch_init(), m32r_gdbarch_init(), m68hc11_gdbarch_init(), m68k_gdbarch_init(), m88k_gdbarch_init(), mep_gdbarch_init(), microblaze_gdbarch_init(), mips_gdbarch_init(), mn10300_gdbarch_init(), moxie_gdbarch_init(), msp430_gdbarch_init(), mt_gdbarch_init(), nios2_gdbarch_init(), rl78_gdbarch_init(), rs6000_gdbarch_init(), rx_gdbarch_init(), s390_gdbarch_init(), score_gdbarch_init(), sh64_gdbarch_init(), sh_gdbarch_init(), sparc32_gdbarch_init(), spu_gdbarch_init(), tic6x_gdbarch_init(), tilegx_gdbarch_init(), v850_gdbarch_init(), vax_gdbarch_init(), xstormy16_gdbarch_init(), and xtensa_gdbarch_init().
void set_gdbarch_int_bit (struct gdbarch * gdbarch, int int_bit)
Definition at line 1528 of file gdbarch.c.
References gdbarch::int_bit.
Referenced by aarch64_gdbarch_init(), alpha_gdbarch_init(), avr_gdbarch_init(), frv_gdbarch_init(), h8300_gdbarch_init(), ia64_gdbarch_init(), iq2000_gdbarch_init(), lm32_gdbarch_init(), m68hc11_gdbarch_init(), make_types(), mips_gdbarch_init(), msp430_gdbarch_init(), mt_gdbarch_init(), nios2_gdbarch_init(), rl78_gdbarch_init(), rs6000_gdbarch_init(), rx_gdbarch_init(), score_gdbarch_init(), sh64_gdbarch_init(), sh_gdbarch_init(), spu_gdbarch_init(), tic6x_gdbarch_init(), tilegx_gdbarch_init(), v850_gdbarch_init(), and xstormy16_gdbarch_init().
void set_gdbarch_integer_to_address (struct gdbarch * gdbarch, gdbarch_integer_to_address_ftype integer_to_address)
Definition at line 2567 of file gdbarch.c.
References gdbarch::integer_to_address.
Referenced by avr_gdbarch_init(), mips_gdbarch_init(), and spu_gdbarch_init().
void set_gdbarch_iterate_over_objfiles_in_search_order (struct gdbarch * gdbarch, gdbarch_iterate_over_objfiles_in_search_order_ftype iterate_over_objfiles_in_search_order)
Definition at line 4402 of file gdbarch.c.
References gdbarch::iterate_over_objfiles_in_search_order.
Referenced by windows_init_abi().
void set_gdbarch_long_bit (struct gdbarch * gdbarch, int long_bit)
Definition at line 1545 of file gdbarch.c.
References gdbarch::long_bit.
Referenced by aarch64_gdbarch_init(), alpha_gdbarch_init(), amd64_init_abi(), amd64_windows_init_abi(), amd64_x32_init_abi(), avr_gdbarch_init(), frv_gdbarch_init(), h8300_gdbarch_init(), hppa_gdbarch_init(), ia64_gdbarch_init(), iq2000_gdbarch_init(), lm32_gdbarch_init(), m68hc11_gdbarch_init(), mips_gdbarch_init(), msp430_gdbarch_init(), mt_gdbarch_init(), nios2_gdbarch_init(), rl78_gdbarch_init(), rs6000_gdbarch_init(), rx_gdbarch_init(), s390_gdbarch_init(), sh64_gdbarch_init(), sh_gdbarch_init(), sparc64_init_abi(), spu_gdbarch_init(), tic6x_gdbarch_init(), tilegx_gdbarch_init(), v850_gdbarch_init(), and xstormy16_gdbarch_init().
void set_gdbarch_long_double_bit (struct gdbarch * gdbarch, int long_double_bit)
Definition at line 1695 of file gdbarch.c.
References gdbarch::long_double_bit.
Referenced by aarch64_gdbarch_init(), alpha_gdbarch_init(), amd64_init_abi(), avr_gdbarch_init(), cris_gdbarch_init(), frv_gdbarch_init(), h8300_gdbarch_init(), hppa_gdbarch_init(), hppa_linux_init_abi(), hppabsd_init_abi(), i386_darwin_init_abi(), i386_gdbarch_init(), ia64_gdbarch_init(), iq2000_gdbarch_init(), lm32_gdbarch_init(), m68hc11_gdbarch_init(), m68k_gdbarch_init(), m88k_gdbarch_init(), microblaze_gdbarch_init(), mips64obsd_init_abi(), mips_gdbarch_init(), mips_linux_init_abi(), msp430_gdbarch_init(), mt_gdbarch_init(), ppc_linux_init_abi(), ppcfbsd_init_abi(), ppcobsd_init_abi(), rl78_gdbarch_init(), rs6000_aix_init_osabi(), rs6000_gdbarch_init(), rs6000_lynx178_init_osabi(), rx_gdbarch_init(), s390_gdbarch_init(), score_gdbarch_init(), sh64_gdbarch_init(), sh_gdbarch_init(), sparc32_gdbarch_init(), sparc32nbsd_init_abi(), spu_gdbarch_init(), tilegx_gdbarch_init(), v850_gdbarch_init(), vax_gdbarch_init(), and xstormy16_gdbarch_init().
void set_gdbarch_long_double_format (struct gdbarch * gdbarch, const struct floatformat ** long_double_format)
Definition at line 1711 of file gdbarch.c.
References gdbarch::long_double_format.
Referenced by aarch64_gdbarch_init(), arm_gdbarch_init(), avr_gdbarch_init(), h8300_gdbarch_init(), hppa_gdbarch_init(), hppabsd_init_abi(), i386_gdbarch_init(), ia64_gdbarch_init(), ia64_hpux_init_abi(), ia64_openvms_init_abi(), iq2000_gdbarch_init(), m68k_gdbarch_init(), m88k_gdbarch_init(), mips64obsd_init_abi(), mips_gdbarch_init(), mips_linux_init_abi(), msp430_gdbarch_init(), mt_gdbarch_init(), ppc_linux_init_abi(), ppcfbsd_init_abi(), ppcobsd_init_abi(), rl78_gdbarch_init(), rx_gdbarch_init(), s390_gdbarch_init(), sparc32_gdbarch_init(), sparc32nbsd_init_abi(), spu_gdbarch_init(), and vax_gdbarch_init().
void set_gdbarch_long_long_align_bit (struct gdbarch * gdbarch, int long_long_align_bit)
Definition at line 1579 of file gdbarch.c.
References gdbarch::long_long_align_bit.
Referenced by i386_gdbarch_init().
void set_gdbarch_long_long_bit (struct gdbarch * gdbarch, int long_long_bit)
Definition at line 1562 of file gdbarch.c.
References gdbarch::long_long_bit.
Referenced by aarch64_gdbarch_init(), alpha_gdbarch_init(), amd64_init_abi(), avr_gdbarch_init(), frv_gdbarch_init(), h8300_gdbarch_init(), hppa_gdbarch_init(), ia64_gdbarch_init(), iq2000_gdbarch_init(), lm32_gdbarch_init(), m68hc11_gdbarch_init(), mips_gdbarch_init(), msp430_gdbarch_init(), mt_gdbarch_init(), nios2_gdbarch_init(), rl78_gdbarch_init(), rs6000_gdbarch_init(), rx_gdbarch_init(), s390_gdbarch_init(), sh64_gdbarch_init(), sh_gdbarch_init(), sparc64_init_abi(), spu_gdbarch_init(), tic6x_gdbarch_init(), tilegx_gdbarch_init(), v850_gdbarch_init(), and xstormy16_gdbarch_init().
void set_gdbarch_make_corefile_notes (struct gdbarch * gdbarch, gdbarch_make_corefile_notes_ftype make_corefile_notes)
Definition at line 3391 of file gdbarch.c.
References gdbarch::make_corefile_notes.
Referenced by linux_init_abi().
void set_gdbarch_max_insn_length (struct gdbarch * gdbarch, ULONGEST max_insn_length)
Definition at line 3619 of file gdbarch.c.
References gdbarch::max_insn_length.
Referenced by arm_gdbarch_init(), i386_gdbarch_init(), rs6000_gdbarch_init(), and s390_gdbarch_init().
void set_gdbarch_memory_insert_breakpoint (struct gdbarch * gdbarch, gdbarch_memory_insert_breakpoint_ftype memory_insert_breakpoint)
Definition at line 2741 of file gdbarch.c.
References memory_insert_breakpoint(), and gdbarch::memory_insert_breakpoint.
Referenced by ia64_gdbarch_init(), and m32r_gdbarch_init().
void set_gdbarch_memory_remove_breakpoint (struct gdbarch * gdbarch, gdbarch_memory_remove_breakpoint_ftype memory_remove_breakpoint)
Definition at line 2758 of file gdbarch.c.
References memory_remove_breakpoint(), and gdbarch::memory_remove_breakpoint.
Referenced by ia64_gdbarch_init(), m32r_gdbarch_init(), microblaze_linux_init_abi(), ppc_linux_init_abi(), and spu_gdbarch_init().
void set_gdbarch_num_pseudo_regs (struct gdbarch * gdbarch, int num_pseudo_regs)
Definition at line 1954 of file gdbarch.c.
References gdbarch::num_pseudo_regs.
Referenced by aarch64_gdbarch_init(), arm_gdbarch_init(), avr_gdbarch_init(), bfin_gdbarch_init(), frv_gdbarch_init(), h8300_gdbarch_init(), i386_gdbarch_init(), ia64_gdbarch_init(), iq2000_gdbarch_init(), m68hc11_gdbarch_init(), make_regs(), mep_gdbarch_init(), mips_gdbarch_init(), mips_linux_init_abi(), msp430_gdbarch_init(), mt_gdbarch_init(), rl78_gdbarch_init(), rs6000_gdbarch_init(), rx_gdbarch_init(), s390_gdbarch_init(), sh64_gdbarch_init(), sh_gdbarch_init(), sparc32_gdbarch_init(), sparc64_init_abi(), spu_gdbarch_init(), tilegx_gdbarch_init(), v850_gdbarch_init(), xstormy16_gdbarch_init(), and xtensa_gdbarch_init().
void set_gdbarch_num_regs (struct gdbarch * gdbarch, int num_regs)
Definition at line 1937 of file gdbarch.c.
References gdbarch::num_regs.
Referenced by aarch64_gdbarch_init(), alpha_gdbarch_init(), amd64_init_abi(), amd64_linux_init_abi(), amd64_x32_linux_init_abi(), arm_gdbarch_init(), avr_gdbarch_init(), bfin_gdbarch_init(), cris_gdbarch_init(), frv_gdbarch_init(), h8300_gdbarch_init(), hppa_gdbarch_init(), i386_darwin_init_abi(), i386_gdbarch_init(), i386_linux_init_abi(), ia64_gdbarch_init(), iq2000_gdbarch_init(), lm32_gdbarch_init(), m32r_gdbarch_init(), m32r_linux_init_abi(), m68hc11_gdbarch_init(), m68k_gdbarch_init(), m88k_gdbarch_init(), make_regs(), mep_gdbarch_init(), microblaze_gdbarch_init(), mips_gdbarch_init(), mips_linux_init_abi(), mn10300_gdbarch_init(), moxie_gdbarch_init(), msp430_gdbarch_init(), mt_gdbarch_init(), nios2_gdbarch_init(), ppc_linux_init_abi(), rl78_gdbarch_init(), rs6000_gdbarch_init(), rx_gdbarch_init(), s390_gdbarch_init(), score_gdbarch_init(), sh64_gdbarch_init(), sh_gdbarch_init(), sparc32_gdbarch_init(), sparc64_init_abi(), spu_gdbarch_init(), tdesc_use_registers(), tic6x_gdbarch_init(), tilegx_gdbarch_init(), v850_gdbarch_init(), vax_gdbarch_init(), xstormy16_gdbarch_init(), and xtensa_gdbarch_init().
void set_gdbarch_overlay_update (struct gdbarch * gdbarch, gdbarch_overlay_update_ftype overlay_update)
Definition at line 3768 of file gdbarch.c.
References gdbarch::overlay_update.
Referenced by m32r_gdbarch_init(), moxie_gdbarch_init(), and spu_gdbarch_init().
void set_gdbarch_pc_regnum (struct gdbarch * gdbarch, int pc_regnum)
Definition at line 2036 of file gdbarch.c.
References pc_regnum, and gdbarch::pc_regnum.
Referenced by aarch64_gdbarch_init(), alpha_gdbarch_init(), amd64_init_abi(), arm_gdbarch_init(), avr_gdbarch_init(), bfin_gdbarch_init(), cris_gdbarch_init(), frv_gdbarch_init(), h8300_gdbarch_init(), i386_gdbarch_init(), iq2000_gdbarch_init(), lm32_gdbarch_init(), m32r_gdbarch_init(), m68hc11_gdbarch_init(), m68k_gdbarch_init(), m88k_gdbarch_init(), make_regs(), mep_gdbarch_init(), microblaze_gdbarch_init(), mips_gdbarch_init(), mn10300_gdbarch_init(), moxie_gdbarch_init(), msp430_gdbarch_init(), mt_gdbarch_init(), nios2_gdbarch_init(), rl78_gdbarch_init(), rs6000_gdbarch_init(), rx_gdbarch_init(), s390_gdbarch_init(), score_gdbarch_init(), sh64_gdbarch_init(), sh_gdbarch_init(), sparc32_gdbarch_init(), sparc64_init_abi(), spu_gdbarch_init(), tic6x_gdbarch_init(), tilegx_gdbarch_init(), v850_gdbarch_init(), vax_gdbarch_init(), xstormy16_gdbarch_init(), and xtensa_gdbarch_init().
void set_gdbarch_pointer_to_address (struct gdbarch * gdbarch, gdbarch_pointer_to_address_ftype pointer_to_address)
Definition at line 2526 of file gdbarch.c.
References gdbarch::pointer_to_address.
Referenced by avr_gdbarch_init(), iq2000_gdbarch_init(), m32c_gdbarch_init(), mips_gdbarch_init(), rl78_gdbarch_init(), spu_gdbarch_init(), and xstormy16_gdbarch_init().
void set_gdbarch_print_float_info (struct gdbarch * gdbarch, gdbarch_print_float_info_ftype print_float_info)
Definition at line 2326 of file gdbarch.c.
References gdbarch::print_float_info, and print_float_info().
Referenced by arm_gdbarch_init(), h8300_gdbarch_init(), and i386_gdbarch_init().
void set_gdbarch_print_insn (struct gdbarch * gdbarch, gdbarch_print_insn_ftype print_insn)
Definition at line 3078 of file gdbarch.c.
References gdbarch::print_insn.
Referenced by aarch64_gdbarch_init(), alpha_gdbarch_init(), arm_gdbarch_init(), avr_gdbarch_init(), bfin_gdbarch_init(), cris_gdbarch_init(), frv_gdbarch_init(), h8300_gdbarch_init(), hppa_gdbarch_init(), i386_gdbarch_init(), ia64_gdbarch_init(), iq2000_gdbarch_init(), lm32_gdbarch_init(), m32c_gdbarch_init(), m32r_gdbarch_init(), m68hc11_gdbarch_init(), m68k_gdbarch_init(), m88k_gdbarch_init(), mep_gdbarch_init(), microblaze_gdbarch_init(), mips_gdbarch_init(), mn10300_gdbarch_init(), moxie_gdbarch_init(), msp430_gdbarch_init(), mt_gdbarch_init(), nios2_gdbarch_init(), rl78_gdbarch_init(), rs6000_gdbarch_init(), rx_gdbarch_init(), s390_gdbarch_init(), score_gdbarch_init(), sh64_gdbarch_init(), sh_gdbarch_init(), sparc32_gdbarch_init(), spu_gdbarch_init(), tic6x_gdbarch_init(), tilegx_gdbarch_init(), v850_gdbarch_init(), vax_gdbarch_init(), xstormy16_gdbarch_init(), and xtensa_gdbarch_init().
void set_gdbarch_print_registers_info (struct gdbarch * gdbarch, gdbarch_print_registers_info_ftype print_registers_info)
Definition at line 2302 of file gdbarch.c.
References gdbarch::print_registers_info.
Referenced by h8300_gdbarch_init(), m68hc11_gdbarch_init(), mips_gdbarch_init(), mt_gdbarch_init(), and sh64_gdbarch_init().
void set_gdbarch_print_vector_info (struct gdbarch * gdbarch, gdbarch_print_vector_info_ftype print_vector_info)
Definition at line 2350 of file gdbarch.c.
References gdbarch::print_vector_info, and print_vector_info().
void set_gdbarch_process_record (struct gdbarch * gdbarch, gdbarch_process_record_ftype process_record)
Definition at line 3857 of file gdbarch.c.
References gdbarch::process_record.
Referenced by amd64_linux_init_abi_common(), arm_linux_init_abi(), i386_linux_init_abi(), and moxie_gdbarch_init().
void set_gdbarch_process_record_signal (struct gdbarch * gdbarch, gdbarch_process_record_signal_ftype process_record_signal)
Definition at line 3881 of file gdbarch.c.
References gdbarch::process_record_signal.
Referenced by amd64_linux_init_abi_common(), and i386_linux_init_abi().
void set_gdbarch_ps_regnum (struct gdbarch * gdbarch, int ps_regnum)
Definition at line 2053 of file gdbarch.c.
References gdbarch::ps_regnum.
Referenced by amd64_init_abi(), bfin_gdbarch_init(), i386_gdbarch_init(), m68k_gdbarch_init(), rs6000_gdbarch_init(), vax_gdbarch_init(), and xtensa_gdbarch_init().
void set_gdbarch_pseudo_register_read (struct gdbarch * gdbarch, gdbarch_pseudo_register_read_ftype pseudo_register_read)
Definition at line 1871 of file gdbarch.c.
References gdbarch::pseudo_register_read.
Referenced by arm_gdbarch_init(), avr_gdbarch_init(), bfin_gdbarch_init(), frv_gdbarch_init(), h8300_gdbarch_init(), hppa_gdbarch_init(), ia64_gdbarch_init(), m68hc11_gdbarch_init(), make_regs(), mep_gdbarch_init(), mips_gdbarch_init(), msp430_gdbarch_init(), mt_gdbarch_init(), rl78_gdbarch_init(), rs6000_gdbarch_init(), s390_gdbarch_init(), sh64_gdbarch_init(), sh_gdbarch_init(), sparc32_gdbarch_init(), sparc64_init_abi(), spu_gdbarch_init(), and xtensa_gdbarch_init().
void set_gdbarch_pseudo_register_read_value (struct gdbarch * gdbarch, gdbarch_pseudo_register_read_value_ftype pseudo_register_read_value)
Definition at line 1895 of file gdbarch.c.
References gdbarch::pseudo_register_read_value.
Referenced by aarch64_gdbarch_init(), amd64_init_abi(), and i386_gdbarch_init().
void set_gdbarch_pseudo_register_write (struct gdbarch * gdbarch, gdbarch_pseudo_register_write_ftype pseudo_register_write)
Definition at line 1919 of file gdbarch.c.
References gdbarch::pseudo_register_write.
Referenced by aarch64_gdbarch_init(), amd64_init_abi(), arm_gdbarch_init(), avr_gdbarch_init(), bfin_gdbarch_init(), frv_gdbarch_init(), h8300_gdbarch_init(), i386_gdbarch_init(), ia64_gdbarch_init(), m68hc11_gdbarch_init(), make_regs(), mep_gdbarch_init(), mips_gdbarch_init(), msp430_gdbarch_init(), mt_gdbarch_init(), rl78_gdbarch_init(), rs6000_gdbarch_init(), s390_gdbarch_init(), sh64_gdbarch_init(), sh_gdbarch_init(), sparc32_gdbarch_init(), sparc64_init_abi(), spu_gdbarch_init(), and xtensa_gdbarch_init().
void set_gdbarch_ptr_bit (struct gdbarch * gdbarch, int ptr_bit)
Definition at line 1728 of file gdbarch.c.
References gdbarch::ptr_bit.
Referenced by aarch64_gdbarch_init(), alpha_gdbarch_init(), amd64_init_abi(), amd64_x32_init_abi(), avr_gdbarch_init(), frv_gdbarch_init(), h8300_gdbarch_init(), hppa_gdbarch_init(), ia64_gdbarch_init(), iq2000_gdbarch_init(), lm32_gdbarch_init(), m68hc11_gdbarch_init(), make_types(), mips_gdbarch_init(), msp430_gdbarch_init(), mt_gdbarch_init(), nios2_gdbarch_init(), rl78_gdbarch_init(), rs6000_gdbarch_init(), rx_gdbarch_init(), s390_gdbarch_init(), sh64_gdbarch_init(), sh_gdbarch_init(), sparc64_init_abi(), spu_gdbarch_init(), tic6x_gdbarch_init(), tilegx_gdbarch_init(), v850_gdbarch_init(), and xstormy16_gdbarch_init().
void set_gdbarch_push_dummy_call (struct gdbarch * gdbarch, gdbarch_push_dummy_call_ftype push_dummy_call)
Definition at line 2244 of file gdbarch.c.
References gdbarch::push_dummy_call.
Referenced by aarch64_gdbarch_init(), alpha_gdbarch_init(), amd64_init_abi(), amd64_windows_init_abi(), arm_gdbarch_init(), avr_gdbarch_init(), bfin_gdbarch_init(), cris_gdbarch_init(), frv_gdbarch_init(), h8300_gdbarch_init(), hppa_gdbarch_init(), i386_darwin_init_abi(), i386_gdbarch_init(), ia64_gdbarch_init(), iq2000_gdbarch_init(), lm32_gdbarch_init(), m32c_gdbarch_init(), m32r_gdbarch_init(), m68hc11_gdbarch_init(), m68k_gdbarch_init(), m88k_gdbarch_init(), mep_gdbarch_init(), microblaze_gdbarch_init(), mips_gdbarch_init(), mn10300_gdbarch_init(), msp430_gdbarch_init(), mt_gdbarch_init(), nios2_gdbarch_init(), rl78_gdbarch_init(), rs6000_aix_init_osabi(), rs6000_gdbarch_init(), rs6000_lynx178_init_osabi(), rx_gdbarch_init(), s390_gdbarch_init(), score_gdbarch_init(), sh64_gdbarch_init(), sh_gdbarch_init(), sparc32_gdbarch_init(), sparc64_init_abi(), spu_gdbarch_init(), tic6x_gdbarch_init(), tilegx_gdbarch_init(), v850_gdbarch_init(), vax_gdbarch_init(), xstormy16_gdbarch_init(), and xtensa_gdbarch_init().
void set_gdbarch_push_dummy_code (struct gdbarch * gdbarch, gdbarch_push_dummy_code_ftype push_dummy_code)
Definition at line 2285 of file gdbarch.c.
References gdbarch::push_dummy_code, and push_dummy_code().
Referenced by cris_gdbarch_init(), hppa_hpux_init_abi(), i386_gdbarch_init(), ia64_hpux_init_abi(), microblaze_gdbarch_init(), mips_gdbarch_init(), sparc32_gdbarch_init(), sparc64_init_abi(), and spu_gdbarch_init().
void set_gdbarch_ravenscar_ops (struct gdbarch * gdbarch, struct ravenscar_arch_ops * ravenscar_ops)
Definition at line 4419 of file gdbarch.c.
References ravenscar_ops, and gdbarch::ravenscar_ops.
Referenced by register_e500_ravenscar_ops(), register_ppc_ravenscar_ops(), and register_sparc_ravenscar_ops().
void set_gdbarch_read_pc (struct gdbarch * gdbarch, gdbarch_read_pc_ftype read_pc)
Definition at line 1806 of file gdbarch.c.
References gdbarch::read_pc.
Referenced by avr_gdbarch_init(), hppa_gdbarch_init(), hppa_hpux_init_abi(), ia64_gdbarch_init(), m32r_gdbarch_init(), mep_gdbarch_init(), mips_gdbarch_init(), mn10300_gdbarch_init(), moxie_gdbarch_init(), and spu_gdbarch_init().
void set_gdbarch_record_special_symbol (struct gdbarch * gdbarch, gdbarch_record_special_symbol_ftype record_special_symbol)
Definition at line 3977 of file gdbarch.c.
References gdbarch::record_special_symbol.
Referenced by arm_gdbarch_init().
void set_gdbarch_register_name (struct gdbarch * gdbarch, gdbarch_register_name_ftype register_name)
Definition at line 2155 of file gdbarch.c.
References gdbarch::register_name, and register_name().
Referenced by alpha_gdbarch_init(), arm_gdbarch_init(), avr_gdbarch_init(), bfin_gdbarch_init(), cris_gdbarch_init(), frv_gdbarch_init(), h8300_gdbarch_init(), hppa_gdbarch_init(), i386_gdbarch_init(), ia64_gdbarch_init(), iq2000_gdbarch_init(), lm32_gdbarch_init(), m32r_gdbarch_init(), m68hc11_gdbarch_init(), m68k_gdbarch_init(), m88k_gdbarch_init(), make_regs(), mep_gdbarch_init(), microblaze_gdbarch_init(), mips_gdbarch_init(), mn10300_gdbarch_init(), moxie_gdbarch_init(), msp430_gdbarch_init(), mt_gdbarch_init(), nios2_gdbarch_init(), rl78_gdbarch_init(), rs6000_gdbarch_init(), rx_gdbarch_init(), score_gdbarch_init(), sh64_gdbarch_init(), sh_gdbarch_init(), sparc32_gdbarch_init(), sparc64_init_abi(), spu_gdbarch_init(), tdesc_use_registers(), tic6x_gdbarch_init(), tilegx_gdbarch_init(), v850_gdbarch_init(), vax_gdbarch_init(), xstormy16_gdbarch_init(), and xtensa_gdbarch_init().
void set_gdbarch_register_reggroup_p (struct gdbarch * gdbarch, gdbarch_register_reggroup_p_ftype register_reggroup_p)
Definition at line 3303 of file gdbarch.c.
References gdbarch::register_reggroup_p.
Referenced by alpha_gdbarch_init(), arm_gdbarch_init(), i386_gdbarch_init(), ia64_gdbarch_init(), lm32_gdbarch_init(), m68hc11_gdbarch_init(), make_regs(), mep_gdbarch_init(), mips_gdbarch_init(), msp430_gdbarch_init(), mt_gdbarch_init(), rl78_gdbarch_init(), sh_gdbarch_init(), spu_gdbarch_init(), tdesc_use_registers(), and xtensa_gdbarch_init().
void set_gdbarch_register_sim_regno (struct gdbarch * gdbarch, gdbarch_register_sim_regno_ftype register_sim_regno)
Definition at line 2367 of file gdbarch.c.
References gdbarch::register_sim_regno.
Referenced by arm_gdbarch_init(), frv_gdbarch_init(), make_regs(), mips_gdbarch_init(), msp430_gdbarch_init(), rl78_gdbarch_init(), rs6000_gdbarch_init(), score_gdbarch_init(), sh64_gdbarch_init(), and sh_gdbarch_init().
void set_gdbarch_register_to_value (struct gdbarch * gdbarch, gdbarch_register_to_value_ftype register_to_value)
Definition at line 2475 of file gdbarch.c.
References gdbarch::register_to_value.
Referenced by alpha_gdbarch_init(), amd64_init_abi(), i386_gdbarch_init(), ia64_gdbarch_init(), m68k_gdbarch_init(), mips_gdbarch_init(), and rs6000_gdbarch_init().
void set_gdbarch_register_type (struct gdbarch * gdbarch, gdbarch_register_type_ftype register_type)
Definition at line 2179 of file gdbarch.c.
References register_type(), and gdbarch::register_type.
Referenced by alpha_gdbarch_init(), arm_gdbarch_init(), avr_gdbarch_init(), bfin_gdbarch_init(), cris_gdbarch_init(), frv_gdbarch_init(), h8300_gdbarch_init(), hppa_gdbarch_init(), ia64_gdbarch_init(), iq2000_gdbarch_init(), lm32_gdbarch_init(), m32r_gdbarch_init(), m68hc11_gdbarch_init(), m68k_gdbarch_init(), m88k_gdbarch_init(), make_regs(), mep_gdbarch_init(), microblaze_gdbarch_init(), mips_gdbarch_init(), mn10300_gdbarch_init(), moxie_gdbarch_init(), msp430_gdbarch_init(), mt_gdbarch_init(), nios2_gdbarch_init(), rl78_gdbarch_init(), rx_gdbarch_init(), score_gdbarch_init(), sh64_gdbarch_init(), sh_gdbarch_init(), sparc32_gdbarch_init(), sparc64_init_abi(), spu_gdbarch_init(), tdesc_use_registers(), tic6x_gdbarch_init(), tilegx_gdbarch_init(), v850_gdbarch_init(), vax_gdbarch_init(), xstormy16_gdbarch_init(), and xtensa_gdbarch_init().
void set_gdbarch_regset_from_core_section (struct gdbarch * gdbarch, gdbarch_regset_from_core_section_ftype regset_from_core_section)
Definition at line 3351 of file gdbarch.c.
References gdbarch::regset_from_core_section.
Referenced by aarch64_linux_init_abi(), alpha_linux_init_abi(), alphanbsd_init_abi(), alphaobsd_init_abi(), am33_linux_init_osabi(), amd64_init_abi(), amd64obsd_core_init_abi(), arm_linux_init_abi(), armobsd_init_abi(), frv_linux_init_abi(), hppa_hpux_init_abi(), hppa_linux_init_abi(), hppanbsd_init_abi(), hppaobsd_init_abi(), i386_cygwin_init_abi(), i386_gdbarch_init(), i386obsd_aout_init_abi(), m32r_linux_init_abi(), m68kbsd_init_abi(), m88k_gdbarch_init(), mips64obsd_init_abi(), mips_linux_init_abi(), mipsnbsd_init_abi(), nios2_linux_init_abi(), ppc_linux_init_abi(), ppcfbsd_init_abi(), ppcnbsd_init_abi(), ppcobsd_init_abi(), rs6000_aix_init_osabi(), s390_gdbarch_init(), score_gdbarch_init(), sh_gdbarch_init(), sparc32_gdbarch_init(), tilegx_linux_init_abi(), vax_gdbarch_init(), and xtensa_gdbarch_init().
void set_gdbarch_relocate_instruction (struct gdbarch * gdbarch, gdbarch_relocate_instruction_ftype relocate_instruction)
Definition at line 3744 of file gdbarch.c.
References gdbarch::relocate_instruction.
Referenced by amd64_init_abi(), and i386_gdbarch_init().
void set_gdbarch_remote_breakpoint_from_pc (struct gdbarch * gdbarch, gdbarch_remote_breakpoint_from_pc_ftype remote_breakpoint_from_pc)
Definition at line 2700 of file gdbarch.c.
References gdbarch::remote_breakpoint_from_pc.
Referenced by arm_gdbarch_init(), and mips_gdbarch_init().
void set_gdbarch_remote_register_number (struct gdbarch * gdbarch, gdbarch_remote_register_number_ftype remote_register_number)
Definition at line 2809 of file gdbarch.c.
References gdbarch::remote_register_number.
Referenced by tdesc_use_registers().
void set_gdbarch_return_in_first_hidden_param_p (struct gdbarch * gdbarch, gdbarch_return_in_first_hidden_param_p_ftype return_in_first_hidden_param_p)
Definition at line 2608 of file gdbarch.c.
References gdbarch::return_in_first_hidden_param_p.
Referenced by m68k_gdbarch_init(), sh_gdbarch_init(), and tic6x_gdbarch_init().
void set_gdbarch_return_value (struct gdbarch * gdbarch, gdbarch_return_value_ftype return_value)
Definition at line 2591 of file gdbarch.c.
References gdbarch::return_value.
Referenced by aarch64_gdbarch_init(), alpha_gdbarch_init(), amd64_init_abi(), amd64_windows_init_abi(), arm_gdbarch_init(), avr_gdbarch_init(), bfin_gdbarch_init(), cris_gdbarch_init(), frv_gdbarch_init(), h8300_gdbarch_init(), hppa_gdbarch_init(), i386_gdbarch_init(), ia64_gdbarch_init(), iq2000_gdbarch_init(), lm32_gdbarch_init(), m32c_gdbarch_init(), m32r_gdbarch_init(), m68hc11_gdbarch_init(), m68k_gdbarch_init(), m68k_svr4_init_abi(), m88k_gdbarch_init(), mep_gdbarch_init(), microblaze_gdbarch_init(), mips_gdbarch_init(), mn10300_gdbarch_init(), moxie_gdbarch_init(), msp430_gdbarch_init(), mt_gdbarch_init(), nios2_gdbarch_init(), ppc_linux_init_abi(), ppcfbsd_init_abi(), ppcnbsd_init_abi(), ppcobsd_init_abi(), rl78_gdbarch_init(), rs6000_aix_init_osabi(), rs6000_gdbarch_init(), rs6000_lynx178_init_osabi(), rx_gdbarch_init(), s390_gdbarch_init(), score_gdbarch_init(), sh64_gdbarch_init(), sh_gdbarch_init(), sparc32_gdbarch_init(), sparc64_init_abi(), spu_gdbarch_init(), tic6x_gdbarch_init(), tilegx_gdbarch_init(), v850_gdbarch_init(), vax_gdbarch_init(), xstormy16_gdbarch_init(), and xtensa_gdbarch_init().
void set_gdbarch_sdb_reg_to_regnum (struct gdbarch * gdbarch, gdbarch_sdb_reg_to_regnum_ftype sdb_reg_to_regnum)
Definition at line 2121 of file gdbarch.c.
References gdbarch::sdb_reg_to_regnum.
Referenced by i386_gdbarch_init(), and i386_go32_init_abi().
void set_gdbarch_short_bit (struct gdbarch * gdbarch, int short_bit)
Definition at line 1511 of file gdbarch.c.
References gdbarch::short_bit.
Referenced by aarch64_gdbarch_init(), alpha_gdbarch_init(), avr_gdbarch_init(), frv_gdbarch_init(), ia64_gdbarch_init(), iq2000_gdbarch_init(), lm32_gdbarch_init(), m68hc11_gdbarch_init(), mips_gdbarch_init(), msp430_gdbarch_init(), mt_gdbarch_init(), nios2_gdbarch_init(), rl78_gdbarch_init(), rs6000_gdbarch_init(), rx_gdbarch_init(), score_gdbarch_init(), sh64_gdbarch_init(), sh_gdbarch_init(), spu_gdbarch_init(), tic6x_gdbarch_init(), tilegx_gdbarch_init(), v850_gdbarch_init(), and xstormy16_gdbarch_init().
void set_gdbarch_single_step_through_delay (struct gdbarch * gdbarch, gdbarch_single_step_through_delay_ftype single_step_through_delay)
Definition at line 3061 of file gdbarch.c.
References gdbarch::single_step_through_delay.
Referenced by cris_gdbarch_init(), and mips_gdbarch_init().
void set_gdbarch_skip_main_prologue (struct gdbarch * gdbarch, gdbarch_skip_main_prologue_ftype skip_main_prologue)
Definition at line 2649 of file gdbarch.c.
References gdbarch::skip_main_prologue.
Referenced by amd64_windows_init_abi(), arm_wince_init_abi(), frv_gdbarch_init(), i386_cygwin_init_abi(), and rs6000_gdbarch_init().
void set_gdbarch_skip_permanent_breakpoint (struct gdbarch * gdbarch, gdbarch_skip_permanent_breakpoint_ftype skip_permanent_breakpoint)
Definition at line 3594 of file gdbarch.c.
References gdbarch::skip_permanent_breakpoint.
Referenced by hppa_hpux_init_abi(), and i386_gdbarch_init().
void set_gdbarch_skip_prologue (struct gdbarch * gdbarch, gdbarch_skip_prologue_ftype skip_prologue)
Definition at line 2625 of file gdbarch.c.
References gdbarch::skip_prologue, and skip_prologue().
Referenced by aarch64_gdbarch_init(), alpha_gdbarch_init(), amd64_init_abi(), amd64_windows_init_abi(), arm_gdbarch_init(), avr_gdbarch_init(), bfin_gdbarch_init(), cris_gdbarch_init(), frv_gdbarch_init(), h8300_gdbarch_init(), hppa_gdbarch_init(), i386_gdbarch_init(), ia64_gdbarch_init(), iq2000_gdbarch_init(), lm32_gdbarch_init(), m32c_gdbarch_init(), m32r_gdbarch_init(), m68hc11_gdbarch_init(), m68k_gdbarch_init(), m88k_gdbarch_init(), mep_gdbarch_init(), microblaze_gdbarch_init(), mips_gdbarch_init(), mn10300_gdbarch_init(), moxie_gdbarch_init(), msp430_gdbarch_init(), mt_gdbarch_init(), nios2_gdbarch_init(), rl78_gdbarch_init(), rs6000_gdbarch_init(), rx_gdbarch_init(), s390_gdbarch_init(), score_gdbarch_init(), sh64_gdbarch_init(), sh_gdbarch_init(), sparc32_gdbarch_init(), sparc64_init_abi(), spu_gdbarch_init(), tic6x_gdbarch_init(), tilegx_gdbarch_init(), v850_gdbarch_init(), vax_gdbarch_init(), xstormy16_gdbarch_init(), and xtensa_gdbarch_init().
void set_gdbarch_skip_solib_resolver (struct gdbarch * gdbarch, gdbarch_skip_solib_resolver_ftype skip_solib_resolver)
Definition at line 3112 of file gdbarch.c.
References gdbarch::skip_solib_resolver.
Referenced by alphaobsd_init_abi(), amd64_linux_init_abi_common(), amd64_sol2_init_abi(), arm_linux_init_abi(), armobsd_init_abi(), hppa_linux_init_abi(), i386_linux_init_abi(), i386_sol2_init_abi(), m68k_linux_init_abi(), mips_linux_init_abi(), nios2_linux_init_abi(), ppc_linux_init_abi(), sh_linux_init_abi(), sparc32_sol2_init_abi(), sparc32obsd_init_abi(), sparc64_sol2_init_abi(), sparc64obsd_init_abi(), and tilegx_linux_init_abi().
void set_gdbarch_skip_trampoline_code (struct gdbarch * gdbarch, gdbarch_skip_trampoline_code_ftype skip_trampoline_code)
Definition at line 3095 of file gdbarch.c.
References gdbarch::skip_trampoline_code.
Referenced by aarch64_linux_init_abi(), alpha_gdbarch_init(), alpha_linux_init_abi(), amd64_linux_init_abi_common(), amd64_windows_init_abi(), arm_gdbarch_init(), arm_linux_init_abi(), arm_symbian_init_abi(), arm_wince_init_abi(), hppa_hpux_init_abi(), hppa_linux_init_abi(), hppabsd_init_abi(), i386_cygwin_init_abi(), i386_linux_init_abi(), i386_svr4_init_abi(), ia64_linux_init_abi(), m32c_gdbarch_init(), m32r_linux_init_abi(), m68k_linux_init_abi(), mips_gdbarch_init(), msp430_gdbarch_init(), nios2_linux_init_abi(), ppc_linux_init_abi(), ppcfbsd_init_abi(), rs6000_gdbarch_init(), s390_gdbarch_init(), sh_linux_init_abi(), sparc32_linux_init_abi(), sparc32_sol2_init_abi(), sparc64_linux_init_abi(), sparc64_sol2_init_abi(), sparc64fbsd_init_abi(), sparc64nbsd_init_abi(), tilegx_linux_init_abi(), and xstormy16_gdbarch_init().
void set_gdbarch_software_single_step (struct gdbarch * gdbarch, gdbarch_software_single_step_ftype software_single_step)
Definition at line 3037 of file gdbarch.c.
References gdbarch::software_single_step.
Referenced by alpha_gdbarch_init(), alpha_osf1_init_abi(), alphanbsd_init_abi(), alphaobsd_init_abi(), arm_linux_init_abi(), arm_netbsd_init_abi_common(), arm_wince_init_abi(), armobsd_init_abi(), cris_gdbarch_init(), mips_linux_init_abi(), mipsnbsd_init_abi(), nios2_gdbarch_init(), rs6000_aix_init_osabi(), rs6000_gdbarch_init(), sparc32_gdbarch_init(), sparc32_sol2_init_abi(), sparc64_sol2_init_abi(), spu_gdbarch_init(), and tic6x_gdbarch_init().
void set_gdbarch_sofun_address_maybe_missing (struct gdbarch * gdbarch, int sofun_address_maybe_missing)
Definition at line 3833 of file gdbarch.c.
References gdbarch::sofun_address_maybe_missing.
Referenced by i386_linux_init_abi(), i386_sol2_init_abi(), rs6000_gdbarch_init(), sparc32_sol2_init_abi(), and sparc64_sol2_init_abi().
void set_gdbarch_solib_symbols_extension (struct gdbarch * gdbarch, const char * solib_symbols_extension)
Definition at line 4303 of file gdbarch.c.
References gdbarch::solib_symbols_extension.
Referenced by arm_symbian_init_abi().
void set_gdbarch_sp_regnum (struct gdbarch * gdbarch, int sp_regnum)
Definition at line 2019 of file gdbarch.c.
References sp_regnum, and gdbarch::sp_regnum.
Referenced by aarch64_gdbarch_init(), alpha_gdbarch_init(), amd64_init_abi(), arm_gdbarch_init(), avr_gdbarch_init(), bfin_gdbarch_init(), cris_gdbarch_init(), frv_gdbarch_init(), h8300_gdbarch_init(), hppa_gdbarch_init(), i386_gdbarch_init(), ia64_gdbarch_init(), iq2000_gdbarch_init(), lm32_gdbarch_init(), m32r_gdbarch_init(), m68hc11_gdbarch_init(), m68k_gdbarch_init(), m88k_gdbarch_init(), make_regs(), mep_gdbarch_init(), microblaze_gdbarch_init(), mips_gdbarch_init(), mn10300_gdbarch_init(), moxie_gdbarch_init(), msp430_gdbarch_init(), mt_gdbarch_init(), nios2_gdbarch_init(), rl78_gdbarch_init(), rs6000_gdbarch_init(), rx_gdbarch_init(), s390_gdbarch_init(), score_gdbarch_init(), sh64_gdbarch_init(), sh_gdbarch_init(), sparc32_gdbarch_init(), spu_gdbarch_init(), tic6x_gdbarch_init(), tilegx_gdbarch_init(), v850_gdbarch_init(), vax_gdbarch_init(), xstormy16_gdbarch_init(), and xtensa_gdbarch_init().
void set_gdbarch_stab_reg_to_regnum (struct gdbarch * gdbarch, gdbarch_stab_reg_to_regnum_ftype stab_reg_to_regnum)
Definition at line 2087 of file gdbarch.c.
References gdbarch::stab_reg_to_regnum, and stab_reg_to_regnum().
Referenced by amd64_init_abi(), h8300_gdbarch_init(), i386_elf_init_abi(), i386_gdbarch_init(), i386_go32_init_abi(), make_regs(), mep_gdbarch_init(), mips_gdbarch_init(), nios2_gdbarch_init(), rs6000_gdbarch_init(), s390_gdbarch_init(), and xtensa_gdbarch_init().
void set_gdbarch_stabs_argument_has_addr (struct gdbarch * gdbarch, gdbarch_stabs_argument_has_addr_ftype stabs_argument_has_addr)
Definition at line 2963 of file gdbarch.c.
References gdbarch::stabs_argument_has_addr.
Referenced by microblaze_gdbarch_init(), sparc32_gdbarch_init(), and sparc64_init_abi().
void set_gdbarch_stap_gdb_register_prefix (struct gdbarch * gdbarch, const char * stap_gdb_register_prefix)
Definition at line 4120 of file gdbarch.c.
References gdbarch::stap_gdb_register_prefix.
Referenced by arm_linux_init_abi(), ia64_linux_init_abi(), and ppc_linux_init_abi().
void set_gdbarch_stap_gdb_register_suffix (struct gdbarch * gdbarch, const char * stap_gdb_register_suffix)
Definition at line 4137 of file gdbarch.c.
References gdbarch::stap_gdb_register_suffix.
void set_gdbarch_stap_integer_prefix (struct gdbarch * gdbarch, const char * stap_integer_prefix)
Definition at line 4018 of file gdbarch.c.
References gdbarch::stap_integer_prefix.
Referenced by amd64_init_abi(), arm_linux_init_abi(), i386_elf_init_abi(), and ppc_linux_init_abi().
void set_gdbarch_stap_integer_suffix (struct gdbarch * gdbarch, const char * stap_integer_suffix)
Definition at line 4035 of file gdbarch.c.
References gdbarch::stap_integer_suffix.
void set_gdbarch_stap_is_single_operand (struct gdbarch * gdbarch, gdbarch_stap_is_single_operand_ftype stap_is_single_operand)
Definition at line 4161 of file gdbarch.c.
References gdbarch::stap_is_single_operand.
Referenced by amd64_init_abi(), arm_linux_init_abi(), i386_elf_init_abi(), ia64_linux_init_abi(), ppc_linux_init_abi(), and s390_gdbarch_init().
void set_gdbarch_stap_parse_special_token (struct gdbarch * gdbarch, gdbarch_stap_parse_special_token_ftype stap_parse_special_token)
Definition at line 4185 of file gdbarch.c.
References gdbarch::stap_parse_special_token.
Referenced by amd64_init_abi(), arm_linux_init_abi(), i386_elf_init_abi(), and ppc_linux_init_abi().
void set_gdbarch_stap_register_indirection_prefix (struct gdbarch * gdbarch, const char * stap_register_indirection_prefix)
Definition at line 4086 of file gdbarch.c.
References gdbarch::stap_register_indirection_prefix.
Referenced by amd64_init_abi(), arm_linux_init_abi(), i386_elf_init_abi(), ia64_linux_init_abi(), ppc_linux_init_abi(), and s390_gdbarch_init().
void set_gdbarch_stap_register_indirection_suffix (struct gdbarch * gdbarch, const char * stap_register_indirection_suffix)
Definition at line 4103 of file gdbarch.c.
References gdbarch::stap_register_indirection_suffix.
Referenced by amd64_init_abi(), arm_linux_init_abi(), i386_elf_init_abi(), ia64_linux_init_abi(), ppc_linux_init_abi(), and s390_gdbarch_init().
void set_gdbarch_stap_register_prefix (struct gdbarch * gdbarch, const char * stap_register_prefix)
Definition at line 4052 of file gdbarch.c.
References gdbarch::stap_register_prefix.
Referenced by amd64_init_abi(), arm_linux_init_abi(), i386_elf_init_abi(), ia64_linux_init_abi(), and s390_gdbarch_init().
void set_gdbarch_stap_register_suffix (struct gdbarch * gdbarch, const char * stap_register_suffix)
Definition at line 4069 of file gdbarch.c.
References gdbarch::stap_register_suffix.
void set_gdbarch_static_transform_name (struct gdbarch * gdbarch, gdbarch_static_transform_name_ftype static_transform_name)
Definition at line 3816 of file gdbarch.c.
References gdbarch::static_transform_name.
Referenced by i386_sol2_init_abi(), sparc32_sol2_init_abi(), and sparc64_sol2_init_abi().
void set_gdbarch_unwind_pc (struct gdbarch * gdbarch, gdbarch_unwind_pc_ftype unwind_pc)
Definition at line 2874 of file gdbarch.c.
References gdbarch::unwind_pc.
Referenced by aarch64_gdbarch_init(), alpha_gdbarch_init(), arm_gdbarch_init(), avr_gdbarch_init(), bfin_gdbarch_init(), cris_gdbarch_init(), frv_gdbarch_init(), h8300_gdbarch_init(), hppa_gdbarch_init(), hppa_hpux_init_abi(), i386_gdbarch_init(), ia64_gdbarch_init(), iq2000_gdbarch_init(), lm32_gdbarch_init(), m32c_gdbarch_init(), m32r_gdbarch_init(), m68hc11_gdbarch_init(), m68k_gdbarch_init(), m88k_gdbarch_init(), mep_gdbarch_init(), microblaze_gdbarch_init(), mips_gdbarch_init(), mn10300_frame_unwind_init(), moxie_gdbarch_init(), msp430_gdbarch_init(), mt_gdbarch_init(), nios2_gdbarch_init(), rl78_gdbarch_init(), rs6000_gdbarch_init(), rx_gdbarch_init(), s390_gdbarch_init(), score_gdbarch_init(), sh64_gdbarch_init(), sh_gdbarch_init(), sparc32_gdbarch_init(), spu_gdbarch_init(), tic6x_gdbarch_init(), tilegx_gdbarch_init(), v850_gdbarch_init(), vax_gdbarch_init(), xstormy16_gdbarch_init(), and xtensa_gdbarch_init().
void set_gdbarch_unwind_sp (struct gdbarch * gdbarch, gdbarch_unwind_sp_ftype unwind_sp)
Definition at line 2898 of file gdbarch.c.
References gdbarch::unwind_sp.
Referenced by aarch64_gdbarch_init(), arm_gdbarch_init(), avr_gdbarch_init(), cris_gdbarch_init(), frv_gdbarch_init(), h8300_gdbarch_init(), iq2000_gdbarch_init(), lm32_gdbarch_init(), m32c_gdbarch_init(), m32r_gdbarch_init(), m68hc11_gdbarch_init(), mep_gdbarch_init(), mips_gdbarch_init(), mn10300_frame_unwind_init(), moxie_gdbarch_init(), msp430_gdbarch_init(), mt_gdbarch_init(), nios2_gdbarch_init(), rl78_gdbarch_init(), rx_gdbarch_init(), s390_gdbarch_init(), score_gdbarch_init(), sh64_gdbarch_init(), sh_gdbarch_init(), spu_gdbarch_init(), tic6x_gdbarch_init(), tilegx_gdbarch_init(), v850_gdbarch_init(), and xstormy16_gdbarch_init().
void set_gdbarch_value_from_register (struct gdbarch * gdbarch, gdbarch_value_from_register_ftype value_from_register)
Definition at line 2509 of file gdbarch.c.
References gdbarch::value_from_register, and value_from_register().
Referenced by s390_gdbarch_init(), and spu_gdbarch_init().
void set_gdbarch_value_to_register (struct gdbarch * gdbarch, gdbarch_value_to_register_ftype value_to_register)
Definition at line 2492 of file gdbarch.c.
References gdbarch::value_to_register.
Referenced by alpha_gdbarch_init(), amd64_init_abi(), i386_gdbarch_init(), ia64_gdbarch_init(), m68k_gdbarch_init(), mips_gdbarch_init(), and rs6000_gdbarch_init().
void set_gdbarch_vbit_in_delta (struct gdbarch * gdbarch, int vbit_in_delta)
Definition at line 3570 of file gdbarch.c.
References gdbarch::vbit_in_delta.
Referenced by aarch64_gdbarch_init(), arm_gdbarch_init(), m32c_gdbarch_init(), mips_gdbarch_init(), msp430_gdbarch_init(), rl78_gdbarch_init(), and rx_gdbarch_init().
void set_gdbarch_virtual_frame_pointer (struct gdbarch * gdbarch, gdbarch_virtual_frame_pointer_ftype virtual_frame_pointer)
Definition at line 1847 of file gdbarch.c.
References gdbarch::virtual_frame_pointer.
Referenced by m32c_gdbarch_init(), mips_gdbarch_init(), and spu_gdbarch_init().
void set_gdbarch_vtable_function_descriptors (struct gdbarch * gdbarch, int vtable_function_descriptors)
Definition at line 3553 of file gdbarch.c.
References gdbarch::vtable_function_descriptors.
Referenced by ia64_gdbarch_init().
void set_gdbarch_write_pc (struct gdbarch * gdbarch, gdbarch_write_pc_ftype write_pc)
Definition at line 1830 of file gdbarch.c.
References gdbarch::write_pc.
Referenced by amd64_linux_init_abi_common(), arm_gdbarch_init(), avr_gdbarch_init(), hppa_gdbarch_init(), hppa_hpux_init_abi(), hppa_linux_init_abi(), i386_linux_init_abi(), ia64_gdbarch_init(), ia64_linux_init_abi(), m88k_gdbarch_init(), microblaze_gdbarch_init(), mips_gdbarch_init(), mips_linux_init_abi(), mn10300_gdbarch_init(), moxie_gdbarch_init(), ppc_linux_init_abi(), s390_gdbarch_init(), sparc32_gdbarch_init(), sparc32_linux_init_abi(), sparc64_linux_init_abi(), spu_gdbarch_init(), and tilegx_gdbarch_init().
void set_target_gdbarch (struct gdbarch * new_gdbarch)
Definition at line 4800 of file gdbarch.c.
References current_inferior(), gdb_assert, inferior::gdbarch, gdbarch::initialized_p, observer_notify_architecture_changed(), and registers_changed().
Referenced by gdbarch_update_p(), and set_gdbarch_from_file().
static void show_gdbarch_debug (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 65 of file gdbarch.c.
References _, and fprintf_filtered().
struct gdbarch* target_gdbarch (void) [read]
Definition at line 4812 of file gdbarch.c.
References current_inferior(), and inferior::gdbarch.
Referenced by ada_tag_value_at_base_address(), ada_tasks_inferior_data_sniffer(), add_vsyscall_page(), agent_capability_check(), agent_get_helper_thread_id(), append_resumption(), arm_show_abi(), arm_show_force_mode(), arm_update_current_architecture(), attach_command(), bpfinishpy_handle_exit(), breakpoint_address_match(), breakpoint_address_match_range(), breakpoint_init_inferior(), bsd_uthread_activate(), bsd_uthread_check_magic(), bsd_uthread_extra_thread_info(), bsd_uthread_lookup_offset(), bsd_uthread_read_memory_address(), bsd_uthread_thread_alive(), bsd_uthread_wait(), btrace_insn_history(), build_traceframe_info(), check_for_saved(), clear_so(), clear_solib(), compare_sections_command(), current_me_module(), darwin_bfd_open(), darwin_check_osabi(), darwin_current_sos(), darwin_debug_regions(), darwin_debug_regions_recurse(), darwin_load_image_infos(), darwin_read_exec_load_addr(), darwin_solib_create_inferior_hook(), darwin_solib_get_all_image_info_addr_at_init(), darwin_solib_read_all_image_info_addr(), dcache_info(), dcache_print_line(), decode_loadmap(), default_auxv_parse(), default_gcore_arch(), default_gcore_mach(), default_gcore_target(), default_region_ok_for_hw_watchpoint(), default_thread_architecture(), deprecated_debug_xfer_memory(), detach_command(), disable_break(), display_one_tib(), dsbt_current_sos(), dsbt_print_loadmap(), effective_target_file_system_kind(), elf_locate_base(), enable_break(), enable_break2(), enable_thread_event(), exec_entry_point(), fbsd_find_memory_regions(), fetch_lm_info(), fetch_loadmap(), find_canonical_descriptor_in_load_object(), fprint_target_auxv(), free_so(), frv_current_sos(), frv_relocate_main_executable(), gcore_copy_callback(), gcore_create_callback(), gcore_memory_sections(), gdbarch_update_p(), gdbsim_xfer_memory(), generic_load(), get_current_arch(), get_remote_arch_state(), get_running_thread_id(), gnu_xfer_memory(), handle_solib_event(), i386_darwin_sstep_at_sigreturn(), i386_show_dr(), ia64_hpux_get_load_info_addr(), in_solib_dynsym_resolve_code(), info_cb(), info_mappings_callback(), info_proc_mappings(), info_sharedlibrary_command(), info_static_tracepoint_markers_command(), info_task(), insert_breakpoint_locations(), invalidate_cache(), irix_current_sos(), irix_open_symbol_file_object(), jit_breakpoint_re_set(), jit_inferior_created_hook(), jit_object_close_impl(), ld_so_xfer_auxv(), link_map_start(), linux_nat_make_corefile_notes(), linux_spu_make_corefile_notes(), linux_xfer_partial(), lm_addr(), lm_addr_check(), lm_base(), lm_info_read(), load_progress(), load_srec(), lookup_symbol_global(), m32r_insert_watchpoint(), m32r_load(), m32r_load_section(), m32r_remove_watchpoint(), m32r_resume(), m32r_upload_command(), m32r_wait(), m32r_xfer_memory(), make_srec(), maybe_new_address_space(), me_module_register_set(), mem_info_command(), memory_error(), mi_cmd_trace_frame_collected(), mi_memory_changed(), mi_solib_loaded(), mi_solib_unloaded(), microblaze_fetch_instruction(), mips_check_lsi_error(), mips_common_breakpoint(), mips_linux_in_dynsym_stub(), mips_request(), mips_show_dr(), mips_xfer_memory(), monitor_error(), monitor_read_memory(), monitor_read_memory_single(), monitor_vsprintf(), monitor_write_memory(), moxie_process_readu(), moxie_process_record(), nto_find_and_open_solib(), nto_init_solib_absolute_prefix(), nto_truncate_ptr(), open_symbol_file_object(), packet_reg_from_pnum(), packet_reg_from_regnum(), parse_spufs_run(), parse_static_tracepoint_marker_definition(), pd_enable(), post_create_inferior(), ppc_linux_auxv_parse(), print_one_breakpoint_location(), proc_watchpoint_address(), process_stop_reply(), procfs_can_use_hw_breakpoint(), procfs_insert_watchpoint(), procfs_mourn_inferior(), procfs_open(), program_info(), ps_get_thread_area(), ps_lgetfpregs(), ps_lgetregs(), ps_lsetfpregs(), ps_lsetregs(), python_inferior_exit(), python_on_resume(), read_program_header(), record_full_arch_list_add_mem(), record_full_open_1(), record_full_xfer_partial(), release_program_space(), reload_shared_libraries(), remote_add_inferior(), remote_address_masked(), remote_check_symbols(), remote_download_tracepoint(), remote_flash_erase(), remote_get_noisy_reply(), remote_insert_breakpoint(), remote_insert_hw_breakpoint(), remote_insert_watchpoint(), remote_parse_stop_reply(), remote_read_description(), remote_read_description_p(), remote_remove_breakpoint(), remote_remove_hw_breakpoint(), remote_remove_watchpoint(), remote_search_memory(), remote_start_remote(), remove_dbx_link_breakpoint(), restore_section_callback(), rl78_analyze_prologue(), rs6000_xfer_shared_libraries(), rx_analyze_prologue(), s390_auxv_parse(), scan_dyntag(), scan_dyntag_auxv(), send_srec(), show_fp_model(), show_mask_address(), show_mips_abi(), show_mipsfpu_command(), solib_add(), solib_bfd_open(), solib_create_inferior_hook(), solib_find(), solib_global_lookup(), solib_keep_data_in_core(), solib_map_sections(), solib_svr4_r_brk(), solib_svr4_r_ldsomap(), solib_svr4_r_map(), som_current_sos(), som_open_symbol_file_object(), som_solib_create_inferior_hook(), spu2ppu_sniffer(), spu_current_sos(), spu_enable_break(), spu_enumerate_spu_ids(), spu_thread_architecture(), svr4_exec_displacement(), svr4_fetch_link_map_offsets(), svr4_have_link_map_offsets(), svr4_read_so_list(), svr4_truncate_ptr(), target_detach(), target_find_description(), target_pre_inferior(), target_translate_tls_address(), target_verify_memory(), tfile_get_trace_state_variable_value(), tfile_get_traceframe_address(), tfile_trace_find(), tfile_xfer_partial(), trace_save(), traceframe_walk_blocks(), update_address_spaces(), update_global_location_list(), update_inserted_breakpoint_locations(), update_solib_breakpoints(), update_solib_list(), VEC(), windows_xfer_shared_libraries(), and write_gcore_file().
static void verify_gdbarch (struct gdbarch * gdbarch) [static]
Definition at line 595 of file gdbarch.c.
References _, gdbarch::addr_bit, gdbarch::bfd_arch_info, gdbarch::breakpoint_from_pc, gdbarch::byte_order, gdbarch::char_signed, gdbarch::displaced_step_copy_insn, gdbarch::displaced_step_free_closure, gdbarch::displaced_step_location, do_cleanups(), gdbarch::double_format, gdbarch::dwarf2_addr_size, gdbarch::float_format, floatformats_ieee_double, floatformats_ieee_half, floatformats_ieee_single, fprintf_unfiltered(), gdbarch_ptr_bit(), gdbarch::half_format, gdbarch::inner_than, internal_error(), cleanup_check::log(), gdbarch::long_double_format, make_cleanup(), make_cleanup_ui_file_delete(), mem_fileopen(), gdbarch::num_regs, gdbarch::print_insn, gdbarch::register_name, gdbarch::skip_prologue, ui_file_xstrdup(), and xfree().
Referenced by gdbarch_find_by_info().
Variable Documentation
struct bfd_arch_info bfd_default_arch_struct
struct gdbarch_data_registry gdbarch_data_registry
Initial value:
{
  0, NULL,
}
Definition at line 4449 of file gdbarch.c.
unsigned int gdbarch_debug = GDBARCH_DEBUG
Definition at line 63 of file gdbarch.c.
Referenced by gdbarch_addr_bit(), gdbarch_addr_bits_remove(), gdbarch_address_class_name_to_type_flags(), gdbarch_address_class_type_flags(), gdbarch_address_class_type_flags_to_name(), gdbarch_address_to_pointer(), gdbarch_adjust_breakpoint_address(), gdbarch_auto_charset(), gdbarch_auto_wide_charset(), gdbarch_ax_pseudo_register_collect(), gdbarch_ax_pseudo_register_push_stack(), gdbarch_believe_pcc_promotion(), gdbarch_bfd_arch_info(), gdbarch_bits_big_endian(), gdbarch_breakpoint_from_pc(), gdbarch_byte_order(), gdbarch_byte_order_for_code(), gdbarch_call_dummy_location(), gdbarch_cannot_fetch_register(), gdbarch_cannot_step_breakpoint(), gdbarch_cannot_store_register(), gdbarch_char_signed(), gdbarch_coff_make_msymbol_special(), gdbarch_convert_from_func_ptr_addr(), gdbarch_convert_register_p(), gdbarch_core_info_proc(), gdbarch_core_pid_to_str(), gdbarch_core_read_description(), gdbarch_core_regset_sections(), gdbarch_core_xfer_shared_libraries(), gdbarch_core_xfer_shared_libraries_aix(), gdbarch_decr_pc_after_break(), gdbarch_deprecated_fp_regnum(), gdbarch_deprecated_function_start_offset(), gdbarch_displaced_step_copy_insn(), gdbarch_displaced_step_fixup(), gdbarch_displaced_step_free_closure(), gdbarch_displaced_step_hw_singlestep(), gdbarch_displaced_step_location(), gdbarch_double_bit(), gdbarch_double_format(), gdbarch_dummy_id(), gdbarch_dwarf2_addr_size(), gdbarch_dwarf2_reg_to_regnum(), gdbarch_ecoff_reg_to_regnum(), gdbarch_elf_make_msymbol_special(), gdbarch_elfcore_write_linux_prpsinfo(), gdbarch_fast_tracepoint_valid_at(), gdbarch_fetch_pointer_argument(), gdbarch_fetch_tls_load_module_address(), gdbarch_find_by_info(), gdbarch_find_memory_regions(), gdbarch_float_bit(), gdbarch_float_format(), gdbarch_fp0_regnum(), gdbarch_frame_align(), gdbarch_frame_args_skip(), gdbarch_frame_num_args(), gdbarch_frame_red_zone_size(), gdbarch_gcore_bfd_target(), gdbarch_gdb_signal_from_target(), gdbarch_gdb_signal_to_target(), gdbarch_gen_return_address(), gdbarch_get_longjmp_target(), gdbarch_get_siginfo_type(), gdbarch_get_syscall_number(), gdbarch_half_bit(), gdbarch_half_format(), gdbarch_has_dos_based_file_system(), gdbarch_has_global_breakpoints(), gdbarch_has_global_solist(), gdbarch_has_shared_address_space(), gdbarch_have_nonsteppable_watchpoint(), gdbarch_in_function_epilogue_p(), gdbarch_in_solib_return_trampoline(), gdbarch_info_proc(), gdbarch_inner_than(), gdbarch_int_bit(), gdbarch_integer_to_address(), gdbarch_iterate_over_objfiles_in_search_order(), gdbarch_long_bit(), gdbarch_long_double_bit(), gdbarch_long_double_format(), gdbarch_long_long_align_bit(), gdbarch_long_long_bit(), gdbarch_make_corefile_notes(), gdbarch_max_insn_length(), gdbarch_memory_insert_breakpoint(), gdbarch_memory_remove_breakpoint(), gdbarch_num_pseudo_regs(), gdbarch_num_regs(), gdbarch_osabi(), gdbarch_overlay_update(), gdbarch_pc_regnum(), gdbarch_pointer_to_address(), gdbarch_print_float_info(), gdbarch_print_insn(), gdbarch_print_registers_info(), gdbarch_print_vector_info(), gdbarch_process_record(), gdbarch_process_record_signal(), gdbarch_ps_regnum(), gdbarch_pseudo_register_read(), gdbarch_pseudo_register_read_value(), gdbarch_pseudo_register_write(), gdbarch_ptr_bit(), gdbarch_push_dummy_call(), gdbarch_push_dummy_code(), gdbarch_ravenscar_ops(), gdbarch_read_pc(), gdbarch_record_special_symbol(), gdbarch_register(), gdbarch_register_name(), gdbarch_register_reggroup_p(), gdbarch_register_sim_regno(), gdbarch_register_to_value(), gdbarch_register_type(), gdbarch_regset_from_core_section(), gdbarch_relocate_instruction(), gdbarch_remote_breakpoint_from_pc(), gdbarch_remote_register_number(), gdbarch_return_in_first_hidden_param_p(), gdbarch_return_value(), gdbarch_sdb_reg_to_regnum(), gdbarch_short_bit(), gdbarch_single_step_through_delay(), gdbarch_skip_main_prologue(), gdbarch_skip_permanent_breakpoint(), gdbarch_skip_prologue(), gdbarch_skip_solib_resolver(), gdbarch_skip_trampoline_code(), gdbarch_software_single_step(), gdbarch_sofun_address_maybe_missing(), gdbarch_solib_symbols_extension(), gdbarch_sp_regnum(), gdbarch_stab_reg_to_regnum(), gdbarch_stabs_argument_has_addr(), gdbarch_stap_gdb_register_prefix(), gdbarch_stap_gdb_register_suffix(), gdbarch_stap_integer_prefix(), gdbarch_stap_integer_suffix(), gdbarch_stap_is_single_operand(), gdbarch_stap_parse_special_token(), gdbarch_stap_register_indirection_prefix(), gdbarch_stap_register_indirection_suffix(), gdbarch_stap_register_prefix(), gdbarch_stap_register_suffix(), gdbarch_static_transform_name(), gdbarch_target_desc(), gdbarch_tdep(), gdbarch_unwind_pc(), gdbarch_unwind_sp(), gdbarch_update_p(), gdbarch_value_from_register(), gdbarch_value_to_register(), gdbarch_vbit_in_delta(), gdbarch_virtual_frame_pointer(), gdbarch_vtable_function_descriptors(), gdbarch_write_pc(), ia64_dummy_id(), ia64_frame_this_id(), ia64_sigtramp_frame_this_id(), and mips_gdbarch_init().
struct gdbarch_registration* gdbarch_registry = NULL [static]
Definition at line 4561 of file gdbarch.c.
struct gdbarch startup_gdbarch
Definition at line 299 of file gdbarch.c.