GDB (xrefs): /home/stan/gdb/src/gdb/gdbtk/generic/gdbtk-cmds.c File Reference
/home/stan/gdb/src/gdb/gdbtk/generic/gdbtk-cmds.c File Reference
#include "defs.h"
#include "inferior.h"
#include "source.h"
#include "symfile.h"
#include "objfiles.h"
#include "gdbcore.h"
#include "demangle.h"
#include "linespec.h"
#include "top.h"
#include "annotate.h"
#include "block.h"
#include "dictionary.h"
#include "filenames.h"
#include "disasm.h"
#include "value.h"
#include "varobj.h"
#include "exceptions.h"
#include "language.h"
#include "target.h"
#include "valprint.h"
#include "regcache.h"
#include "arch-utils.h"
#include "psymtab.h"
#include <ctype.h>
#include <tcl.h>
#include <tk.h>
#include "guitcl.h"
#include "gdbtk.h"
#include "gdbtk-wrapper.h"
#include "gdbtk-cmds.h"
#include <signal.h>
#include <fcntl.h>
#include <sys/time.h>
#include "gdb_stat.h"
#include "gdb_string.h"
#include "dis-asm.h"
#include "gdbcmd.h"
Classes
struct my_line_entry
struct disassembly_client_data
struct listfiles_info
Defines
#define HAS_STDARG 1
#define INDEX(row, col) sprintf (index, "%d,%d",(row),(col))
#define LTABLE_SIZE 20000
Functions
int gdb_variable_init (Tcl_Interp *interp)
int Gdbtk_Init (Tcl_Interp *interp)
static int compare_lines (const PTR, const PTR)
static int comp_files (const void *, const void *)
static int gdb_clear_file (ClientData, Tcl_Interp *interp, int, Tcl_Obj *CONST[])
static int gdb_cmd (ClientData, Tcl_Interp *, int, Tcl_Obj *CONST[])
static int gdb_confirm_quit (ClientData, Tcl_Interp *, int, Tcl_Obj *CONST[])
static int gdb_entry_point (ClientData, Tcl_Interp *, int, Tcl_Obj *CONST[])
static int gdb_eval (ClientData, Tcl_Interp *, int, Tcl_Obj *CONST[])
static int gdb_find_file_command (ClientData, Tcl_Interp *, int, Tcl_Obj *CONST objv[])
static int gdb_force_quit (ClientData, Tcl_Interp *, int, Tcl_Obj *CONST[])
static int gdb_get_file_command (ClientData, Tcl_Interp *, int, Tcl_Obj *CONST objv[])
static int gdb_get_function_command (ClientData, Tcl_Interp *, int, Tcl_Obj *CONST objv[])
static int gdb_get_line_command (ClientData, Tcl_Interp *, int, Tcl_Obj *CONST objv[])
static int gdb_update_mem (ClientData, Tcl_Interp *, int, Tcl_Obj *CONST[])
static int gdb_set_mem (ClientData, Tcl_Interp *, int, Tcl_Obj *CONST[])
static int gdb_immediate_command (ClientData, Tcl_Interp *, int, Tcl_Obj *CONST[])
static int gdb_incr_addr (ClientData, Tcl_Interp *, int, Tcl_Obj *CONST[])
static int gdb_CA_to_TAS (ClientData, Tcl_Interp *, int, Tcl_Obj *CONST[])
static int gdb_listfiles (ClientData, Tcl_Interp *, int, Tcl_Obj *CONST[])
static int gdb_listfuncs (ClientData, Tcl_Interp *, int, Tcl_Obj *CONST[])
static int gdb_loadfile (ClientData, Tcl_Interp *, int, Tcl_Obj *CONST objv[])
static int gdb_load_disassembly (ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[])
static int gdb_get_inferior_args (ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[])
static int gdb_set_inferior_args (ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[])
static int gdb_load_info (ClientData, Tcl_Interp *, int, Tcl_Obj *CONST objv[])
static int gdb_loc (ClientData, Tcl_Interp *, int, Tcl_Obj *CONST[])
static int gdb_path_conv (ClientData, Tcl_Interp *, int, Tcl_Obj *CONST[])
static int gdb_prompt_command (ClientData, Tcl_Interp *, int, Tcl_Obj *CONST objv[])
static int gdb_restore_fputs (ClientData, Tcl_Interp *, int, Tcl_Obj *CONST[])
static int gdb_search (ClientData, Tcl_Interp *, int, Tcl_Obj *CONST objv[])
static int gdb_stop (ClientData, Tcl_Interp *, int, Tcl_Obj *CONST[])
static int gdb_target_has_execution_command (ClientData, Tcl_Interp *, int, Tcl_Obj *CONST[])
static void gdbtk_load_source (ClientData clientData, struct symtab *symtab, int start_line, int end_line)
static CORE_ADDR gdbtk_load_asm (ClientData clientData, CORE_ADDR pc, struct disassemble_info *di)
static int gdb_disassemble_driver (CORE_ADDR low, CORE_ADDR high, int mixed_source_and_assembly, ClientData clientData, void(*print_source_fn)(ClientData, structsymtab *, int, int), CORE_ADDR(*print_asm_fn)(ClientData, CORE_ADDR, structdisassemble_info *))
static int perror_with_name_wrapper (PTR args)
static int wrapped_call (PTR opaque_args)
static int hex2bin (const char *hex, char *bin, int count)
static int fromhex (int a)
static int gdb_list_processes (ClientData, Tcl_Interp *, int, Tcl_Obj *CONST[])
int gdbtk_call_wrapper (ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[])
static int gdb_clear_file (ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[])
static int gdb_confirm_quit (ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[])
static int gdb_force_quit (ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[])
static int gdb_stop (ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[])
static int gdb_list_processes (ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[])
static int gdb_eval (ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[])
static int gdb_cmd (ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[])
static int gdb_immediate_command (ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[])
static int gdb_target_has_execution_command (ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[])
static void do_listfiles (const char *filename, const char *fullname, void *data)
static int gdb_listfiles (ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[])
static int gdb_listfuncs (ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[])
static int gdb_restore_fputs (ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[])
static int gdb_disassemble_driver (CORE_ADDR low, CORE_ADDR high, int mixed_source_and_assembly, ClientData clientData, void(*print_source_fn)(ClientData, struct symtab *, int, int), CORE_ADDR(*print_asm_fn)(ClientData, CORE_ADDR, struct disassemble_info *))
static int gdb_loc (ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[])
static int gdb_entry_point (ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[])
static int gdb_set_mem (ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[])
static int gdb_update_mem (ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[])
static int gdb_path_conv (ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[])
const char * pc_function_name (CORE_ADDR pc)
void gdbtk_set_result (Tcl_Interp *interp, const char *fmt,...)
static int gdb_incr_addr (ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[])
static int gdb_CA_to_TAS (ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[])
char * symtab_to_filename (struct symtab *s)
Variables
char * source_path
static Tcl_Obj * mangled
static Tcl_Obj * not_mangled
int No_Update = 0
int load_in_progress = 0
int disassemble_from_exec = -1
Define Documentation
#define HAS_STDARG 1
Definition at line 52 of file gdbtk-cmds.c.
#define INDEX (row, col) sprintf (index, "%d,%d",(row),(col))
Referenced by gdb_update_mem().
#define LTABLE_SIZE 20000
Definition at line 2712 of file gdbtk-cmds.c.
Referenced by gdb_loadfile().
Function Documentation
static int comp_files (const void * file1, const void * file2) [static]
Definition at line 1303 of file gdbtk-cmds.c.
Referenced by gdb_listfiles().
static int compare_lines (const PTR mle1p, const PTR mle2p) [static]
Definition at line 2188 of file gdbtk-cmds.c.
References my_line_entry::line, and my_line_entry::start_pc.
Referenced by gdb_disassemble_driver().
static void do_listfiles (const char * filename, const char * fullname, void * data) [static]
Definition at line 1193 of file gdbtk-cmds.c.
References listfiles_info::files_sizep, listfiles_info::filesp, listfiles_info::len, listfiles_info::numfilesp, listfiles_info::pathname, and xrealloc().
Referenced by gdb_listfiles().
static int fromhex (int a) [static]
Definition at line 2346 of file gdbtk-cmds.c.
Referenced by hex2bin().
static int gdb_CA_to_TAS (ClientData , Tcl_Interp * , int , Tcl_Obj * CONST[]) [static]
Referenced by Gdbtk_Init().
static int gdb_CA_to_TAS (ClientData clientData, Tcl_Interp * interp, int objc, Tcl_Obj *CONST objv[]) [static]
Definition at line 3086 of file gdbtk-cmds.c.
References get_current_arch(), gdbtk_result::obj_ptr, paddress(), and result_ptr.
static int gdb_clear_file (ClientData , Tcl_Interp * interp, int , Tcl_Obj * CONST[]) [static]
Referenced by Gdbtk_Init().
static int gdb_clear_file (ClientData clientData, Tcl_Interp * interp, int objc, Tcl_Obj *CONST objv[]) [static]
Definition at line 472 of file gdbtk-cmds.c.
References inferior::attach_flag, current_inferior(), delete_command(), exec_file_clear(), inferior_ptid, null_ptid, ptid_equal(), symbol_file_clear(), target_detach(), target_has_execution, and target_kill().
static int gdb_cmd (ClientData , Tcl_Interp * , int , Tcl_Obj * CONST[]) [static]
Referenced by Gdbtk_Init().
static int gdb_cmd (ClientData clientData, Tcl_Interp * interp, int objc, Tcl_Obj *CONST objv[]) [static]
Definition at line 739 of file gdbtk-cmds.c.
References bpstat_do_actions(), execute_command(), gdbtk_result::flags, gdbtk_set_result(), GDBTK_TO_RESULT, load_in_progress, No_Update, result_ptr, and running_now.
static int gdb_confirm_quit (ClientData , Tcl_Interp * , int , Tcl_Obj * CONST[]) [static]
Referenced by Gdbtk_Init().
static int gdb_confirm_quit (ClientData clientData, Tcl_Interp * interp, int objc, Tcl_Obj *CONST objv[]) [static]
Definition at line 507 of file gdbtk-cmds.c.
References gdbtk_result::obj_ptr, quit_confirm(), and result_ptr.
static int gdb_disassemble_driver (CORE_ADDR low, CORE_ADDR high, int mixed_source_and_assembly, ClientData clientData, void(*)(ClientData, structsymtab *, int, int) print_source_fn, CORE_ADDR(*)(ClientData, CORE_ADDR, structdisassemble_info *) print_asm_fn) [static]
Referenced by gdb_load_disassembly().
static int gdb_disassemble_driver (CORE_ADDR low, CORE_ADDR high, int mixed_source_and_assembly, ClientData clientData, void(*)(ClientData, struct symtab *, int, int) print_source_fn, CORE_ADDR(*)(ClientData, CORE_ADDR, struct disassemble_info *) print_asm_fn) [static]
Definition at line 2049 of file gdbtk-cmds.c.
References compare_lines(), symtab_and_line::end, my_line_entry::end_pc, find_pc_line(), find_pc_symtab(), linetable::item, my_line_entry::line, linetable_entry::line, line, symtab::linetable, linetable::nitems, linetable_entry::pc, qsort, QUIT, and my_line_entry::start_pc.
static int gdb_entry_point (ClientData , Tcl_Interp * , int , Tcl_Obj * CONST[]) [static]
Referenced by Gdbtk_Init().
static int gdb_entry_point (ClientData clientData, Tcl_Interp * interp, int objc, Tcl_Obj *CONST objv[]) [static]
Definition at line 2325 of file gdbtk-cmds.c.
References core_addr_to_string(), current_target, dummy_stratum, entry_point_address(), gdbtk_result::obj_ptr, result_ptr, and target_ops::to_stratum.
static int gdb_eval (ClientData , Tcl_Interp * , int , Tcl_Obj * CONST[]) [static]
Referenced by Gdbtk_Init().
static int gdb_eval (ClientData clientData, Tcl_Interp * interp, int objc, Tcl_Obj *CONST objv[]) [static]
Definition at line 683 of file gdbtk-cmds.c.
References common_val_print(), current_language, do_cleanups(), dummy, evaluate_expression(), gdbtk_result::flags, free_current_contents(), GDBTK_IN_TCL_RESULT, get_formatted_print_options(), make_cleanup(), make_cleanup_ui_file_delete(), mem_fileopen(), parse_expression(), result_ptr, ui_file_xstrdup(), and xfree().
static int gdb_find_file_command (ClientData clientData, Tcl_Interp * interp, int objc, Tcl_Obj *CONST objv[]) [static]
Definition at line 1119 of file gdbtk-cmds.c.
References symtab::filename, symtab::fullname, gdbtk_set_result(), lookup_symtab(), gdbtk_result::obj_ptr, result_ptr, exsummary::status, and symtab_to_filename().
Referenced by Gdbtk_Init().
static int gdb_force_quit (ClientData , Tcl_Interp * , int , Tcl_Obj * CONST[]) [static]
Referenced by Gdbtk_Init().
static int gdb_force_quit (ClientData clientData, Tcl_Interp * interp, int objc, Tcl_Obj *CONST objv[]) [static]
Definition at line 533 of file gdbtk-cmds.c.
References quit_force().
static int gdb_get_file_command (ClientData clientData, Tcl_Interp * interp, int objc, Tcl_Obj *CONST objv[]) [static]
Definition at line 1045 of file gdbtk-cmds.c.
References decode_line_1(), DECODE_LINE_FUNFIRSTLINE, symtab::filename, symtabs_and_lines::nelts, gdbtk_result::obj_ptr, result_ptr, symtabs_and_lines::sals, and symtab_and_line::symtab.
Referenced by Gdbtk_Init().
static int gdb_get_function_command (ClientData clientData, Tcl_Interp * interp, int objc, Tcl_Obj *CONST objv[]) [static]
Definition at line 1080 of file gdbtk-cmds.c.
References decode_line_1(), DECODE_LINE_FUNFIRSTLINE, symtabs_and_lines::nelts, gdbtk_result::obj_ptr, symtab_and_line::pc, pc_function_name(), resolve_sal_pc(), result_ptr, and symtabs_and_lines::sals.
Referenced by Gdbtk_Init().
static int gdb_get_inferior_args (ClientData clientData, Tcl_Interp * interp, int objc, Tcl_Obj *CONST objv[]) [static]
Definition at line 897 of file gdbtk-cmds.c.
References get_inferior_args(), gdbtk_result::obj_ptr, and result_ptr.
Referenced by Gdbtk_Init().
static int gdb_get_line_command (ClientData clientData, Tcl_Interp * interp, int objc, Tcl_Obj *CONST objv[]) [static]
Definition at line 1009 of file gdbtk-cmds.c.
References decode_line_1(), DECODE_LINE_FUNFIRSTLINE, symtab_and_line::line, symtabs_and_lines::nelts, gdbtk_result::obj_ptr, result_ptr, and symtabs_and_lines::sals.
Referenced by Gdbtk_Init().
static int gdb_immediate_command (ClientData , Tcl_Interp * , int , Tcl_Obj * CONST[]) [static]
Referenced by Gdbtk_Init().
static int gdb_immediate_command (ClientData clientData, Tcl_Interp * interp, int objc, Tcl_Obj *CONST objv[]) [static]
Definition at line 804 of file gdbtk-cmds.c.
References bpstat_do_actions(), execute_command(), gdbtk_result::flags, gdbtk_set_result(), GDBTK_TO_RESULT, load_in_progress, No_Update, result_ptr, and running_now.
static int gdb_incr_addr (ClientData , Tcl_Interp * , int , Tcl_Obj * CONST[]) [static]
Referenced by Gdbtk_Init().
static int gdb_incr_addr (ClientData clientData, Tcl_Interp * interp, int objc, Tcl_Obj *CONST objv[]) [static]
Definition at line 3039 of file gdbtk-cmds.c.
References core_addr_to_string(), gdbtk_result::obj_ptr, result_ptr, and string_to_core_addr().
static int gdb_list_processes (ClientData , Tcl_Interp * , int , Tcl_Obj * CONST[]) [static]
Referenced by Gdbtk_Init().
static int gdb_list_processes (ClientData clientData, Tcl_Interp * interp, int objc, Tcl_Obj *CONST objv[]) [static]
Definition at line 613 of file gdbtk-cmds.c.
References gdbtk_result::obj_ptr, and result_ptr.
static int gdb_listfiles (ClientData , Tcl_Interp * , int , Tcl_Obj * CONST[]) [static]
Referenced by Gdbtk_Init().
static int gdb_listfiles (ClientData clientData, Tcl_Interp * interp, int objc, Tcl_Obj *CONST objv[]) [static]
Definition at line 1234 of file gdbtk-cmds.c.
References ALL_SYMTABS, comp_files(), do_listfiles(), symtab::filename, listfiles_info::files_sizep, listfiles_info::filesp, free(), len, listfiles_info::len, symtab::linetable, map_partial_symbol_filenames(), linetable::nitems, listfiles_info::numfilesp, gdbtk_result::obj_ptr, listfiles_info::pathname, qsort, result_ptr, xmalloc(), and xrealloc().
static int gdb_listfuncs (ClientData , Tcl_Interp * , int , Tcl_Obj * CONST[]) [static]
Referenced by Gdbtk_Init().
static int gdb_listfuncs (ClientData clientData, Tcl_Interp * interp, int objc, Tcl_Obj *CONST objv[]) [static]
Definition at line 1528 of file gdbtk-cmds.c.
References ALL_BLOCK_SYMBOLS, BLOCKVECTOR, BLOCKVECTOR_BLOCK, gdbtk_set_result(), GLOBAL_BLOCK, LOC_BLOCK, lookup_symtab(), mangled, name, not_mangled, gdbtk_result::obj_ptr, result_ptr, STATIC_BLOCK, SYMBOL_CLASS, SYMBOL_DEMANGLED_NAME, and SYMBOL_PRINT_NAME.
static int gdb_load_disassembly (ClientData clientData, Tcl_Interp * interp, int objc, Tcl_Obj *CONST objv[]) [static]
Definition at line 1641 of file gdbtk-cmds.c.
References disassembly_client_data::asm_argv, disassembly_client_data::cmd, core_addr_to_string(), error(), disassembly_client_data::file_opened_p, find_pc_partial_function(), gdb_disassemble_driver(), gdbtk_load_asm(), gdbtk_load_source(), gdbtk_set_result(), disassembly_client_data::interp, disassembly_client_data::line_to_pc_prefix, disassembly_client_data::map_arr, gdbtk_result::obj_ptr, disassembly_client_data::pc_to_line_prefix, disassembly_client_data::result_obj, result_ptr, disassembly_client_data::source_argv, disassembly_client_data::src_to_line_prefix, disassembly_client_data::widget, and disassembly_client_data::widget_line_no.
Referenced by Gdbtk_Init().
static int gdb_load_info (ClientData clientData, Tcl_Interp * interp, int objc, Tcl_Obj *CONST objv[]) [static]
Definition at line 949 of file gdbtk-cmds.c.
References do_cleanups(), gdbtk_set_result(), gnutarget, make_cleanup_bfd_unref(), gdbtk_result::obj_ptr, result_ptr, and size.
Referenced by Gdbtk_Init().
static int gdb_loadfile (ClientData clientData, Tcl_Interp * interp, int objc, Tcl_Obj *CONST objv[]) [static]
Definition at line 2714 of file gdbtk-cmds.c.
References catch_errors(), exec_bfd, free(), gdbtk_ignorable_warning(), gdbtk_set_result(), linetable::item, linetable_entry::line, line, symtab::linetable, lookup_symtab(), LTABLE_SIZE, malloc(), memset(), linetable::nitems, objfile::obfd, symtab::objfile, perror_with_name_wrapper(), realloc(), RETURN_MASK_ALL, strrchr(), and symtab_to_filename().
Referenced by Gdbtk_Init().
static int gdb_loc (ClientData , Tcl_Interp * , int , Tcl_Obj * CONST[]) [static]
Referenced by Gdbtk_Init().
static int gdb_loc (ClientData clientData, Tcl_Interp * interp, int objc, Tcl_Obj *CONST objv[]) [static]
Definition at line 2214 of file gdbtk-cmds.c.
References core_addr_to_string(), decode_line_with_current_source(), entry_point_address(), symtab::filename, find_frame_sal(), find_pc_line(), free(), gdbtk_set_result(), get_current_regcache(), get_frame_pc(), get_selected_frame(), symtab_and_line::line, symtabs_and_lines::nelts, gdbtk_result::obj_ptr, symtab_and_line::pc, pc_function_name(), regcache_read_pc(), resolve_sal_pc(), result_ptr, symtabs_and_lines::sals, stop_pc, symtab_and_line::symtab, symtab_to_filename(), and target_has_registers.
static int gdb_path_conv (ClientData , Tcl_Interp * , int , Tcl_Obj * CONST[]) [static]
Referenced by Gdbtk_Init().
static int gdb_path_conv (ClientData clientData, Tcl_Interp * interp, int objc, Tcl_Obj *CONST objv[]) [static]
Definition at line 2933 of file gdbtk-cmds.c.
References gdbtk_result::obj_ptr, and result_ptr.
static int gdb_prompt_command (ClientData clientData, Tcl_Interp * interp, int objc, Tcl_Obj *CONST objv[]) [static]
Definition at line 851 of file gdbtk-cmds.c.
References get_prompt(), gdbtk_result::obj_ptr, and result_ptr.
Referenced by Gdbtk_Init().
static int gdb_restore_fputs (ClientData , Tcl_Interp * , int , Tcl_Obj * CONST[]) [static]
Referenced by Gdbtk_Init().
static int gdb_restore_fputs (ClientData clientData, Tcl_Interp * interp, int objc, Tcl_Obj *CONST objv[]) [static]
Definition at line 1615 of file gdbtk-cmds.c.
References gdbtk_disable_fputs.
static int gdb_search (ClientData clientData, Tcl_Interp * interp, int objc, Tcl_Obj *CONST objv[]) [static]
Definition at line 1326 of file gdbtk-cmds.c.
References symbol_search::block, do_cleanups(), symtab::filename, gdbtk_result::flags, FUNCTIONS_DOMAIN, GDBTK_IN_TCL_RESULT, make_cleanup_free_search_symbols(), bound_minimal_symbol::minsym, symbol_search::msymbol, symbol_search::next, gdbtk_result::obj_ptr, p, result_ptr, search_symbols(), STATIC_BLOCK, symbol_search::symbol, SYMBOL_LINKAGE_NAME, SYMBOL_PRINT_NAME, symbol_search::symtab, TYPES_DOMAIN, VARIABLES_DOMAIN, and xmalloc().
Referenced by Gdbtk_Init().
static int gdb_set_inferior_args (ClientData clientData, Tcl_Interp * interp, int objc, Tcl_Obj *CONST objv[]) [static]
Definition at line 921 of file gdbtk-cmds.c.
References set_inferior_args().
Referenced by Gdbtk_Init().
static int gdb_set_mem (ClientData , Tcl_Interp * , int , Tcl_Obj * CONST[]) [static]
Referenced by Gdbtk_Init().
static int gdb_set_mem (ClientData clientData, Tcl_Interp * interp, int objc, Tcl_Obj *CONST objv[]) [static]
Definition at line 2402 of file gdbtk-cmds.c.
References gdbtk_set_result(), hex2bin(), len, size, string_to_core_addr(), and target_write_memory().
static int gdb_stop (ClientData , Tcl_Interp * , int , Tcl_Obj * CONST[]) [static]
Referenced by Gdbtk_Init().
static int gdb_stop (ClientData clientData, Tcl_Interp * interp, int objc, Tcl_Obj *CONST objv[]) [static]
Definition at line 571 of file gdbtk-cmds.c.
References current_target, gdbtk_force_detach, gdbtk_get_ptid(), set_quit_flag(), target_ignore(), target_stop(), and target_ops::to_stop.
static int gdb_target_has_execution_command (ClientData , Tcl_Interp * , int , Tcl_Obj * CONST[]) [static]
Referenced by Gdbtk_Init().
static int gdb_target_has_execution_command (ClientData clientData, Tcl_Interp * interp, int objc, Tcl_Obj *CONST objv[]) [static]
Definition at line 874 of file gdbtk-cmds.c.
References inferior_ptid, null_ptid, gdbtk_result::obj_ptr, ptid_equal(), result_ptr, and target_has_execution.
static int gdb_update_mem (ClientData , Tcl_Interp * , int , Tcl_Obj * CONST[]) [static]
Referenced by Gdbtk_Init().
static int gdb_update_mem (ClientData clientData, Tcl_Interp * interp, int objc, Tcl_Obj *CONST objv[]) [static]
Definition at line 2463 of file gdbtk-cmds.c.
References target_ops::beneath, builtin_type::builtin_int16, builtin_type::builtin_int32, builtin_type::builtin_int64, builtin_type::builtin_int8, builtin_type(), core_addr_to_string(), current_target, do_cleanups(), dummy, gdbtk_set_result(), get_current_arch(), get_formatted_print_options(), INDEX, make_cleanup_ui_file_delete(), mem_fileopen(), memset(), gdbtk_result::obj_ptr, print_scalar_formatted(), result_ptr, size, string_to_core_addr(), TARGET_OBJECT_MEMORY, target_read(), ui_file_rewind(), ui_file_xstrdup(), xfree(), and xmalloc().
int gdb_variable_init (Tcl_Interp * interp)
Definition at line 84 of file gdbtk-varobj.c.
References gdb_variable_command(), and gdbtk_call_wrapper().
Referenced by Gdbtk_Init().
int gdbtk_call_wrapper (ClientData clientData, Tcl_Interp * interp, int objc, Tcl_Obj *CONST objv[])
Definition at line 361 of file gdbtk-cmds.c.
References catch_errors(), gdbtk_result::flags, wrapped_call_args::func, gdb_flush(), gdb_stderr, gdb_stdout, GDBTK_IN_TCL_RESULT, gdbtk_stop_timer(), GDBTK_TO_RESULT, wrapped_call_args::interp, load_in_progress, gdbtk_result::obj_ptr, wrapped_call_args::objc, wrapped_call_args::objv, result_ptr, RETURN_MASK_ALL, running_now, wrapped_call_args::val, and wrapped_call().
Referenced by gdb_variable_init(), Gdbtk_Breakpoint_Init(), Gdbtk_Init(), Gdbtk_Register_Init(), and Gdbtk_Stack_Init().
int Gdbtk_Init (Tcl_Interp * interp)
Definition at line 248 of file gdbtk-cmds.c.
References current_directory, disassemble_from_exec, gdb_CA_to_TAS(), gdb_clear_file(), gdb_cmd(), gdb_confirm_quit(), gdb_context, gdb_entry_point(), gdb_eval(), gdb_find_file_command(), gdb_force_quit(), gdb_get_file_command(), gdb_get_function_command(), gdb_get_inferior_args(), gdb_get_line_command(), gdb_immediate_command(), gdb_incr_addr(), gdb_list_processes(), gdb_listfiles(), gdb_listfuncs(), gdb_load_disassembly(), gdb_load_info(), gdb_loadfile(), gdb_loc(), gdb_path_conv(), gdb_prompt_command(), gdb_restore_fputs(), gdb_search(), gdb_set_inferior_args(), gdb_set_mem(), gdb_stop(), gdb_target_has_execution_command(), gdb_update_mem(), gdb_variable_init(), Gdbtk_Breakpoint_Init(), gdbtk_call_wrapper(), gdbtk_interp, Gdbtk_Register_Init(), Gdbtk_Stack_Init(), GDBTK_VERSION, and source_path.
Referenced by gdbtk_init().
static CORE_ADDR gdbtk_load_asm (ClientData clientData, CORE_ADDR pc, struct disassemble_info * di) [static]
Definition at line 1960 of file gdbtk-cmds.c.
References disassembly_client_data::asm_argv, disassembly_client_data::cmd, core_addr_to_string(), do_cleanups(), fputs_filtered(), gdb_flush(), gdb_print_insn(), gdb_stdout, gdbtk_restore_result_ptr(), GDBTK_TO_RESULT, get_current_arch(), disassembly_client_data::interp, disassembly_client_data::line_to_pc_prefix, make_cleanup(), disassembly_client_data::map_arr, gdbtk_result::obj_ptr, paddress(), disassembly_client_data::pc_to_line_prefix, print_address_symbolic(), disassembly_client_data::result_obj, result_ptr, disassembly_client_data::widget_line_no, xfree(), and xstrprintf().
Referenced by gdb_load_disassembly().
static void gdbtk_load_source (ClientData clientData, struct symtab * symtab, int start_line, int end_line) [static]
Definition at line 1826 of file gdbtk-cmds.c.
References disassembly_client_data::cmd, disassembly_client_data::file_opened_p, find_source_lines(), disassembly_client_data::fp, free(), disassembly_client_data::interp, line, symtab::line_charpos, disassembly_client_data::map_arr, symtab::nlines, open_source_file(), disassembly_client_data::source_argv, disassembly_client_data::src_to_line_prefix, strrchr(), disassembly_client_data::widget_line_no, and xstrprintf().
Referenced by gdb_load_disassembly().
void gdbtk_set_result (Tcl_Interp * interp, const char * fmt, ...)
Definition at line 3006 of file gdbtk-cmds.c.
References xfree(), and xstrvprintf().
Referenced by gdb_actions_command(), gdb_cmd(), gdb_find_file_command(), gdb_get_breakpoint_info(), gdb_get_tracepoint_info(), gdb_get_vars_command(), gdb_immediate_command(), gdb_listfuncs(), gdb_load_disassembly(), gdb_load_info(), gdb_loadfile(), gdb_loc(), gdb_regformat(), gdb_reggroup(), gdb_set_bp(), gdb_set_mem(), gdb_update_mem(), variable_format(), and variable_value().
static int hex2bin (const char * hex, char * bin, int count) [static]
Definition at line 2359 of file gdbtk-cmds.c.
References fromhex(), gdbarch_byte_order(), get_current_arch(), and arm-linux::m.
Referenced by gdb_set_mem(), parse_static_tracepoint_marker_definition(), parse_trace_status(), parse_tracepoint_definition(), parse_tsv_definition(), remote_check_symbols(), remote_get_raw_trace_data(), remote_parse_stop_reply(), remote_read_bytes(), and remote_threads_extra_info().
const char* pc_function_name (CORE_ADDR pc)
Definition at line 2980 of file gdbtk-cmds.c.
References find_pc_function(), GDBTK_SYMBOL_SOURCE_NAME, and lookup_minimal_symbol_by_pc().
Referenced by gdb_get_breakpoint_info(), gdb_get_function_command(), gdb_get_tracepoint_info(), and gdb_loc().
static int perror_with_name_wrapper (PTR args) [static]
Definition at line 2968 of file gdbtk-cmds.c.
References perror_with_name().
Referenced by gdb_loadfile().
char* symtab_to_filename (struct symtab * s)
Definition at line 3119 of file gdbtk-cmds.c.
References symtab::filename, symtab::fullname, and open_source_file().
Referenced by gdb_find_file_command(), gdb_get_breakpoint_info(), gdb_get_tracepoint_info(), gdb_loadfile(), and gdb_loc().
static int wrapped_call (PTR opaque_args) [static]
Definition at line 445 of file gdbtk-cmds.c.
References wrapped_call_args::func, wrapped_call_args::interp, wrapped_call_args::objc, wrapped_call_args::objv, and wrapped_call_args::val.
Referenced by gdbtk_call_wrapper().
Variable Documentation
int disassemble_from_exec = -1
Definition at line 147 of file gdbtk-cmds.c.
Referenced by Gdbtk_Init().
int load_in_progress = 0
Definition at line 110 of file gdbtk-cmds.c.
Referenced by gdb_cmd(), gdb_immediate_command(), gdbtk_call_wrapper(), and x_event().
Tcl_Obj* mangled [static]
Definition at line 104 of file gdbtk-cmds.c.
Referenced by dwarf2_physname(), and gdb_listfuncs().
int No_Update = 0
Definition at line 109 of file gdbtk-cmds.c.
Referenced by gdb_cmd(), gdb_immediate_command(), and gdbtk_call_command().
Tcl_Obj * not_mangled [static]
Definition at line 104 of file gdbtk-cmds.c.
Referenced by gdb_listfuncs().
char* source_path
Definition at line 70 of file source.c.