GDB (xrefs): /home/stan/gdb/src/gdb/gdbtk/generic/gdbtk-cmds.h File Reference
/home/stan/gdb/src/gdb/gdbtk/generic/gdbtk-cmds.h File Reference
Classes
struct wrapped_call_args
Functions
int gdbtk_call_wrapper (ClientData, Tcl_Interp *, int, Tcl_Obj *CONST[])
const char * pc_function_name (CORE_ADDR pc)
void sprintf_append_element_to_obj (Tcl_Obj *objp, char *format,...)
void gdbtk_set_result (Tcl_Interp *interp, const char *fmt,...)
int Gdbtk_Breakpoint_Init (Tcl_Interp *interp)
int Gdbtk_Stack_Init (Tcl_Interp *interp)
int Gdbtk_Register_Init (Tcl_Interp *interp)
char * symtab_to_filename (struct symtab *s)
Function Documentation
int Gdbtk_Breakpoint_Init (Tcl_Interp * interp)
Definition at line 115 of file gdbtk-bp.c.
References gdb_actions_command(), gdb_find_bp_at_addr(), gdb_find_bp_at_line(), gdb_get_breakpoint_info(), gdb_get_breakpoint_list(), gdb_get_trace_frame_num(), gdb_get_tracepoint_info(), gdb_get_tracepoint_list(), gdb_set_bp(), gdb_trace_status(), gdb_tracepoint_exists_command(), and gdbtk_call_wrapper().
Referenced by Gdbtk_Init().
int gdbtk_call_wrapper (ClientData , Tcl_Interp * , int , Tcl_Obj * CONST[])
int Gdbtk_Register_Init (Tcl_Interp * interp)
Definition at line 71 of file gdbtk-register.c.
References gdb_register_info(), gdbtk_call_wrapper(), and setup_architecture_data().
Referenced by Gdbtk_Init().
void gdbtk_set_result (Tcl_Interp * interp, const char * fmt, ...)
Definition at line 3006 of file gdbtk-cmds.c.
References xfree(), and xstrvprintf().
Referenced by gdb_actions_command(), gdb_cmd(), gdb_find_file_command(), gdb_get_breakpoint_info(), gdb_get_tracepoint_info(), gdb_get_vars_command(), gdb_immediate_command(), gdb_listfuncs(), gdb_load_disassembly(), gdb_load_info(), gdb_loadfile(), gdb_loc(), gdb_regformat(), gdb_reggroup(), gdb_set_bp(), gdb_set_mem(), gdb_update_mem(), variable_format(), and variable_value().
int Gdbtk_Stack_Init (Tcl_Interp * interp)
Definition at line 60 of file gdbtk-stack.c.
References gdb_block_vars(), gdb_get_args_command(), gdb_get_blocks(), gdb_get_locals_command(), gdb_selected_block(), gdb_selected_frame(), gdb_stack(), and gdbtk_call_wrapper().
Referenced by Gdbtk_Init().
const char* pc_function_name (CORE_ADDR pc)
Definition at line 2980 of file gdbtk-cmds.c.
References find_pc_function(), GDBTK_SYMBOL_SOURCE_NAME, and lookup_minimal_symbol_by_pc().
Referenced by gdb_get_breakpoint_info(), gdb_get_function_command(), gdb_get_tracepoint_info(), and gdb_loc().
void sprintf_append_element_to_obj (Tcl_Obj * objp, char * format, ...)
char* symtab_to_filename (struct symtab * s)
Definition at line 3119 of file gdbtk-cmds.c.
References symtab::filename, symtab::fullname, and open_source_file().
Referenced by gdb_find_file_command(), gdb_get_breakpoint_info(), gdb_get_tracepoint_info(), gdb_loadfile(), and gdb_loc().