GDB (xrefs): /home/stan/gdb/src/gdb/gdbtk/generic/gdbtk-wrapper.c File Reference
/home/stan/gdb/src/gdb/gdbtk/generic/gdbtk-wrapper.c File Reference
#include "defs.h"
#include "frame.h"
#include "value.h"
#include "varobj.h"
#include "block.h"
#include "exceptions.h"
#include "language.h"
#include "valprint.h"
#include "gdbtk-wrapper.h"
Functions
gdb_result GDB_value_fetch_lazy (value_ptr)
gdb_result GDB_evaluate_expression (struct expression *, value_ptr *)
gdb_result GDB_type_print (value_ptr, char *, struct ui_file *, int)
gdb_result GDB_val_print (struct type *type, char *valaddr, CORE_ADDR address, struct ui_file *stream, int format, int deref_ref, int recurse, enum val_prettyformat pretty)
gdb_result GDB_value_equal (value_ptr, value_ptr, int *)
gdb_result GDB_evaluate_type (struct expression *exp, value_ptr *result)
gdb_result GDB_block_for_pc (CORE_ADDR pc, struct block **result)
gdb_result GDB_block_innermost_frame (struct block *block, struct frame_info **result)
gdb_result GDB_reinit_frame_cache (void)
gdb_result GDB_value_ind (value_ptr val, value_ptr *rval)
gdb_result GDB_value_slice (value_ptr val, int low, int num, value_ptr *rval)
gdb_result GDB_value_coerce_array (value_ptr val, value_ptr *rval)
gdb_result GDB_value_struct_elt (value_ptr *argp, value_ptr *args, char *name, int *static_memfunc, char *err, value_ptr *rval)
gdb_result GDB_value_cast (struct type *type, value_ptr val, value_ptr *rval)
gdb_result GDB_get_frame_block (struct frame_info *fi, struct block **rval)
gdb_result GDB_get_prev_frame (struct frame_info *fi, struct frame_info **result)
gdb_result GDB_get_next_frame (struct frame_info *fi, struct frame_info **result)
gdb_result GDB_find_relative_frame (struct frame_info *fi, int *start, struct frame_info **result)
gdb_result GDB_get_current_frame (struct frame_info **result)
gdb_result GDB_varobj_update (struct varobj **varp, int explicit, VEC(varobj_update_result)**changes)
static gdb_result call_wrapped_function (catch_errors_ftype *, struct gdb_wrapper_arguments *)
static int wrap_type_print (char *)
static int wrap_evaluate_expression (char *)
static int wrap_value_fetch_lazy (char *)
static int wrap_val_print (char *)
static int wrap_value_equal (char *)
static int wrap_evaluate_type (char *opaque_arg)
static int wrap_block_for_pc (char *opaque_arg)
static int wrap_block_innermost_frame (char *opaque_arg)
static int wrap_reinit_frame_cache (char *opaque_arg)
static int wrap_value_ind (char *opaque_arg)
static int wrap_value_slice (char *opaque_arg)
static int wrap_value_coerce_array (char *opaque_arg)
static int wrap_value_struct_elt (char *opaque_arg)
static int wrap_value_cast (char *opaque_arg)
static int wrap_get_frame_block (char *opaque_arg)
static int wrap_get_prev_frame (char *opaque_arg)
static int wrap_get_next_frame (char *opaque_arg)
static int wrap_find_relative_frame (char *opaque_arg)
static int wrap_get_current_frame (char *opaque_arg)
static int wrap_varobj_update (char *opaque_arg)
Function Documentation
static gdb_result call_wrapped_function (catch_errors_ftype * fn, struct gdb_wrapper_arguments * arg) [static]
Definition at line 143 of file gdbtk-wrapper.c.
References catch_errors(), GDB_ERROR, GDB_OK, and RETURN_MASK_ERROR.
Referenced by GDB_block_for_pc(), GDB_block_innermost_frame(), GDB_evaluate_expression(), GDB_evaluate_type(), GDB_find_relative_frame(), GDB_get_current_frame(), GDB_get_frame_block(), GDB_get_next_frame(), GDB_get_prev_frame(), GDB_reinit_frame_cache(), GDB_type_print(), GDB_val_print(), GDB_value_cast(), GDB_value_coerce_array(), GDB_value_equal(), GDB_value_fetch_lazy(), GDB_value_ind(), GDB_value_slice(), GDB_value_struct_elt(), and GDB_varobj_update().
gdb_result GDB_block_for_pc (CORE_ADDR pc, struct block ** result)
Definition at line 368 of file gdbtk-wrapper.c.
References gdb_wrapper_arguments::args, call_wrapped_function(), GDB_OK, gdb_wrapper_arguments::ptr, gdb_wrapper_arguments::result, and wrap_block_for_pc().
gdb_result GDB_block_innermost_frame (struct block * block, struct frame_info ** result)
Definition at line 395 of file gdbtk-wrapper.c.
References gdb_wrapper_arguments::args, call_wrapped_function(), GDB_OK, gdb_wrapper_arguments::ptr, gdb_wrapper_arguments::result, and wrap_block_innermost_frame().
gdb_result GDB_evaluate_expression (struct expression * exp, value_ptr * value)
Definition at line 249 of file gdbtk-wrapper.c.
References gdb_wrapper_arguments::args, call_wrapped_function(), GDB_OK, gdb_wrapper_arguments::ptr, gdb_wrapper_arguments::result, and wrap_evaluate_expression().
gdb_result GDB_evaluate_type (struct expression * exp, value_ptr * result)
Definition at line 341 of file gdbtk-wrapper.c.
References gdb_wrapper_arguments::args, call_wrapped_function(), GDB_OK, gdb_wrapper_arguments::ptr, gdb_wrapper_arguments::result, and wrap_evaluate_type().
gdb_result GDB_find_relative_frame (struct frame_info * fi, int * start, struct frame_info ** result)
Definition at line 680 of file gdbtk-wrapper.c.
References gdb_wrapper_arguments::args, call_wrapped_function(), GDB_OK, gdb_wrapper_arguments::ptr, gdb_wrapper_arguments::result, and wrap_find_relative_frame().
Referenced by gdb_stack().
gdb_result GDB_get_current_frame (struct frame_info ** result)
Definition at line 710 of file gdbtk-wrapper.c.
References call_wrapped_function(), GDB_OK, gdb_wrapper_arguments::ptr, gdb_wrapper_arguments::result, and wrap_get_current_frame().
Referenced by gdb_stack().
gdb_result GDB_get_frame_block (struct frame_info * fi, struct block ** rval)
Definition at line 602 of file gdbtk-wrapper.c.
References gdb_wrapper_arguments::args, call_wrapped_function(), GDB_OK, gdb_wrapper_arguments::ptr, gdb_wrapper_arguments::result, and wrap_get_frame_block().
gdb_result GDB_get_next_frame (struct frame_info * fi, struct frame_info ** result)
Definition at line 655 of file gdbtk-wrapper.c.
References gdb_wrapper_arguments::args, call_wrapped_function(), GDB_OK, gdb_wrapper_arguments::ptr, gdb_wrapper_arguments::result, and wrap_get_next_frame().
Referenced by gdb_stack().
gdb_result GDB_get_prev_frame (struct frame_info * fi, struct frame_info ** result)
Definition at line 630 of file gdbtk-wrapper.c.
References gdb_wrapper_arguments::args, call_wrapped_function(), GDB_OK, gdb_wrapper_arguments::ptr, gdb_wrapper_arguments::result, and wrap_get_prev_frame().
Referenced by gdb_stack().
gdb_result GDB_reinit_frame_cache (void)
Definition at line 422 of file gdbtk-wrapper.c.
References call_wrapped_function(), GDB_OK, and wrap_reinit_frame_cache().
gdb_result GDB_type_print (value_ptr val, char * varstring, struct ui_file * stream, int show)
Definition at line 155 of file gdbtk-wrapper.c.
References gdb_wrapper_arguments::args, call_wrapped_function(), gdb_wrapper_arguments::integer, gdb_wrapper_arguments::ptr, and wrap_type_print().
gdb_result GDB_val_print (struct type * type, char * valaddr, CORE_ADDR address, struct ui_file * stream, int format, int deref_ref, int recurse, enum val_prettyformat pretty)
Definition at line 180 of file gdbtk-wrapper.c.
References gdb_wrapper_arguments::args, call_wrapped_function(), gdb_wrapper_arguments::integer, gdb_wrapper_arguments::ptr, type, and wrap_val_print().
gdb_result GDB_value_cast (struct type * type, value_ptr val, value_ptr * rval)
Definition at line 571 of file gdbtk-wrapper.c.
References gdb_wrapper_arguments::args, call_wrapped_function(), GDB_OK, gdb_wrapper_arguments::ptr, gdb_wrapper_arguments::result, type, and wrap_value_cast().
gdb_result GDB_value_coerce_array (value_ptr val, value_ptr * rval)
Definition at line 500 of file gdbtk-wrapper.c.
References gdb_wrapper_arguments::args, call_wrapped_function(), GDB_OK, gdb_wrapper_arguments::ptr, gdb_wrapper_arguments::result, and wrap_value_coerce_array().
gdb_result GDB_value_equal (value_ptr val1, value_ptr val2, int * result)
Definition at line 274 of file gdbtk-wrapper.c.
References gdb_wrapper_arguments::args, call_wrapped_function(), GDB_OK, gdb_wrapper_arguments::integer, gdb_wrapper_arguments::ptr, gdb_wrapper_arguments::result, and wrap_value_equal().
gdb_result GDB_value_fetch_lazy (value_ptr value)
Definition at line 231 of file gdbtk-wrapper.c.
References gdb_wrapper_arguments::args, call_wrapped_function(), gdb_wrapper_arguments::ptr, and wrap_value_fetch_lazy().
gdb_result GDB_value_ind (value_ptr val, value_ptr * rval)
Definition at line 441 of file gdbtk-wrapper.c.
References gdb_wrapper_arguments::args, call_wrapped_function(), GDB_OK, gdb_wrapper_arguments::ptr, gdb_wrapper_arguments::result, and wrap_value_ind().
gdb_result GDB_value_slice (value_ptr val, int low, int num, value_ptr * rval)
Definition at line 468 of file gdbtk-wrapper.c.
References gdb_wrapper_arguments::args, call_wrapped_function(), GDB_OK, gdb_wrapper_arguments::integer, gdb_wrapper_arguments::ptr, gdb_wrapper_arguments::result, and wrap_value_slice().
gdb_result GDB_value_struct_elt (value_ptr * argp, value_ptr * args, char * name, int * static_memfunc, char * err, value_ptr * rval)
Definition at line 528 of file gdbtk-wrapper.c.
References gdb_wrapper_arguments::args, call_wrapped_function(), GDB_OK, name, gdb_wrapper_arguments::ptr, gdb_wrapper_arguments::result, and wrap_value_struct_elt().
gdb_result GDB_varobj_update (struct varobj ** varp, int explicit, VEC(varobj_update_result)** changes)
Definition at line 734 of file gdbtk-wrapper.c.
References gdb_wrapper_arguments::args, call_wrapped_function(), GDB_OK, gdb_wrapper_arguments::integer, gdb_wrapper_arguments::ptr, gdb_wrapper_arguments::result, and wrap_varobj_update().
Referenced by variable_update().
static int wrap_block_for_pc (char * opaque_arg) [static]
Definition at line 384 of file gdbtk-wrapper.c.
References gdb_wrapper_arguments::args, and block_for_pc().
Referenced by GDB_block_for_pc().
static int wrap_block_innermost_frame (char * opaque_arg) [static]
Definition at line 411 of file gdbtk-wrapper.c.
References gdb_wrapper_arguments::args, and block_innermost_frame().
Referenced by GDB_block_innermost_frame().
static int wrap_evaluate_expression (char * a) [static]
Definition at line 264 of file gdbtk-wrapper.c.
References gdb_wrapper_arguments::args, and evaluate_expression().
Referenced by GDB_evaluate_expression().
static int wrap_evaluate_type (char * opaque_arg) [static]
Definition at line 357 of file gdbtk-wrapper.c.
References gdb_wrapper_arguments::args, and evaluate_type().
Referenced by GDB_evaluate_type().
static int wrap_find_relative_frame (char * opaque_arg) [static]
Definition at line 699 of file gdbtk-wrapper.c.
References gdb_wrapper_arguments::args, and find_relative_frame().
Referenced by GDB_find_relative_frame().
static int wrap_get_current_frame (char * opaque_arg) [static]
Definition at line 725 of file gdbtk-wrapper.c.
References gdb_wrapper_arguments::args, and get_current_frame().
Referenced by GDB_get_current_frame().
static int wrap_get_frame_block (char * opaque_arg) [static]
Definition at line 618 of file gdbtk-wrapper.c.
References gdb_wrapper_arguments::args, and get_frame_block().
Referenced by GDB_get_frame_block().
static int wrap_get_next_frame (char * opaque_arg) [static]
Definition at line 670 of file gdbtk-wrapper.c.
References gdb_wrapper_arguments::args, and get_next_frame().
Referenced by GDB_get_next_frame().
static int wrap_get_prev_frame (char * opaque_arg) [static]
Definition at line 645 of file gdbtk-wrapper.c.
References gdb_wrapper_arguments::args, and get_prev_frame().
Referenced by GDB_get_prev_frame().
static int wrap_reinit_frame_cache (char * opaque_arg) [static]
Definition at line 434 of file gdbtk-wrapper.c.
References reinit_frame_cache().
Referenced by GDB_reinit_frame_cache().
static int wrap_type_print (char * a) [static]
Definition at line 168 of file gdbtk-wrapper.c.
References gdb_wrapper_arguments::args, type_print(), and value_type().
Referenced by GDB_type_print().
static int wrap_val_print (char * a) [static]
Definition at line 204 of file gdbtk-wrapper.c.
References gdb_wrapper_arguments::args, current_language, value_print_options::deref_ref, get_formatted_print_options(), value_print_options::prettyformat, type, and val_print().
Referenced by GDB_val_print().
static int wrap_value_cast (char * opaque_arg) [static]
Definition at line 588 of file gdbtk-wrapper.c.
References gdb_wrapper_arguments::args, type, and value_cast().
Referenced by GDB_value_cast().
static int wrap_value_coerce_array (char * opaque_arg) [static]
Definition at line 517 of file gdbtk-wrapper.c.
References gdb_wrapper_arguments::args, and value_coerce_array().
Referenced by GDB_value_coerce_array().
static int wrap_value_equal (char * a) [static]
Definition at line 291 of file gdbtk-wrapper.c.
References gdb_wrapper_arguments::args, and value_equal().
Referenced by GDB_value_equal().
static int wrap_value_fetch_lazy (char * a) [static]
Definition at line 240 of file gdbtk-wrapper.c.
References gdb_wrapper_arguments::args, and value_fetch_lazy().
Referenced by GDB_value_fetch_lazy().
static int wrap_value_ind (char * opaque_arg) [static]
Definition at line 457 of file gdbtk-wrapper.c.
References gdb_wrapper_arguments::args, and value_ind().
Referenced by GDB_value_ind().
static int wrap_value_slice (char * opaque_arg) [static]
Definition at line 486 of file gdbtk-wrapper.c.
References gdb_wrapper_arguments::args, and value_slice().
Referenced by GDB_value_slice().
static int wrap_value_struct_elt (char * opaque_arg) [static]
Definition at line 552 of file gdbtk-wrapper.c.
References gdb_wrapper_arguments::args, name, and value_struct_elt().
Referenced by GDB_value_struct_elt().
static int wrap_varobj_update (char * opaque_arg) [static]
Definition at line 751 of file gdbtk-wrapper.c.
References gdb_wrapper_arguments::args.
Referenced by GDB_varobj_update().