GDB (xrefs): /home/stan/gdb/src/gdb/gdbtk/generic/gdbtk-register.c File Reference
/home/stan/gdb/src/gdb/gdbtk/generic/gdbtk-register.c File Reference
#include "defs.h"
#include "frame.h"
#include "regcache.h"
#include "reggroups.h"
#include "value.h"
#include "target.h"
#include "gdb_string.h"
#include "language.h"
#include "valprint.h"
#include "arch-utils.h"
#include <tcl.h>
#include "gdbtk.h"
#include "gdbtk-cmds.h"
Classes
union map_arg
Typedefs
typedef void(* map_func)(int, map_arg)
Functions
static int gdb_register_info (ClientData, Tcl_Interp *, int, Tcl_Obj **)
static void get_register (int, map_arg)
static void get_register_name (int, map_arg)
static void get_register_size (int, map_arg)
static int map_arg_registers (Tcl_Interp *, int, Tcl_Obj **, map_func, map_arg)
static void register_changed_p (int, map_arg)
static void setup_architecture_data (void)
static int gdb_regformat (ClientData, Tcl_Interp *, int, Tcl_Obj **)
static int gdb_reggroup (ClientData, Tcl_Interp *, int, Tcl_Obj **)
static int gdb_reggrouplist (ClientData, Tcl_Interp *, int, Tcl_Obj **)
static void get_register_types (int regnum, map_arg)
int Gdbtk_Register_Init (Tcl_Interp *interp)
Variables
static char * old_regs = NULL
static int old_regs_count = 0
static int * regformat = (int *)NULL
static struct type ** regtype = (struct type **)NULL
Typedef Documentation
typedef void(* map_func)(int, map_arg)
Definition at line 44 of file gdbtk-register.c.
Function Documentation
static int gdb_regformat (ClientData clientData, Tcl_Interp * interp, int objc, Tcl_Obj ** objv) [static]
Definition at line 493 of file gdbtk-register.c.
References gdbarch_num_pseudo_regs(), gdbarch_num_regs(), gdbtk_set_result(), get_current_arch(), int, regformat, and type.
Referenced by gdb_register_info().
static int gdb_reggroup (ClientData clientData, Tcl_Interp * interp, int objc, Tcl_Obj ** objv) [static]
Definition at line 562 of file gdbtk-register.c.
References gdbarch_num_pseudo_regs(), gdbarch_num_regs(), gdbarch_register_reggroup_p(), gdbtk_set_result(), get_current_arch(), gdbtk_result::obj_ptr, reggroup_name(), reggroup_next(), regnum, and result_ptr.
Referenced by gdb_register_info().
static int gdb_reggrouplist (ClientData clientData, Tcl_Interp * interp, int objc, Tcl_Obj ** objv) [static]
Definition at line 535 of file gdbtk-register.c.
References get_current_arch(), gdbtk_result::obj_ptr, reggroup_name(), reggroup_next(), result_ptr, and USER_REGGROUP.
Referenced by gdb_register_info().
static int gdb_register_info (ClientData clientData, Tcl_Interp * interp, int objc, Tcl_Obj ** objv) [static]
Definition at line 129 of file gdbtk-register.c.
References gdbtk_result::flags, func, gdb_regformat(), gdb_reggroup(), gdb_reggrouplist(), GDBTK_IN_TCL_RESULT, get_register(), get_register_name(), get_register_size(), get_register_types(), map_arg::integer, len, map_arg_registers(), map_arg::ptr, register_changed_p(), and result_ptr.
Referenced by Gdbtk_Register_Init().
int Gdbtk_Register_Init (Tcl_Interp * interp)
Definition at line 71 of file gdbtk-register.c.
References gdb_register_info(), gdbtk_call_wrapper(), and setup_architecture_data().
Referenced by Gdbtk_Init().
static void get_register (int regnum, map_arg arg) [static]
Definition at line 275 of file gdbtk-register.c.
References current_language, value_print_options::deref_ref, do_cleanups(), dummy, gdbtk_result::flags, fputs_unfiltered(), gdbarch_byte_order(), GDBTK_MAKES_LIST, get_current_arch(), get_formatted_print_options(), get_frame_arch(), get_frame_register_value(), get_selected_frame(), make_cleanup_ui_file_delete(), mem_fileopen(), gdbtk_result::obj_ptr, value_print_options::prettyformat, regformat, register_size(), register_type(), regnum, result_ptr, target_has_registers, ui_file_xstrdup(), Val_prettyformat_default, val_print(), value_contents_for_printing(), value_embedded_offset(), value_optimized_out(), and xfree().
Referenced by gdb_register_info().
static void get_register_name (int regnum, map_arg arg) [static]
Definition at line 362 of file gdbtk-register.c.
References gdbarch_register_name(), get_current_arch(), map_arg::integer, name, gdbtk_result::obj_ptr, and result_ptr.
Referenced by gdb_register_info().
static void get_register_size (int regnum, map_arg arg) [static]
Definition at line 213 of file gdbtk-register.c.
References gdbtk_interp, get_current_arch(), gdbtk_result::obj_ptr, register_size(), and result_ptr.
Referenced by gdb_register_info().
static void get_register_types (int regnum, map_arg arg) [static]
Definition at line 225 of file gdbtk-register.c.
References gdbtk_interp, get_current_arch(), host_address_to_string(), gdbtk_result::obj_ptr, register_type(), result_ptr, TYPE_CODE, TYPE_CODE_FLT, TYPE_CODE_UNION, TYPE_FIELD_NAME, TYPE_FIELD_TYPE, TYPE_NAME, TYPE_NFIELDS, xfree(), and xstrprintf().
Referenced by gdb_register_info().
static int map_arg_registers (Tcl_Interp * interp, int objc, Tcl_Obj ** objv, map_func func, map_arg arg) [static]
Definition at line 389 of file gdbtk-register.c.
References gdbtk_result::flags, func, gdbarch_num_pseudo_regs(), gdbarch_num_regs(), gdbarch_register_name(), GDBTK_IN_TCL_RESULT, GDBTK_MAKES_LIST, get_current_arch(), gdbtk_result::obj_ptr, regnum, and result_ptr.
Referenced by gdb_register_info().
static void register_changed_p (int regnum, map_arg arg) [static]
Definition at line 444 of file gdbtk-register.c.
References gdb_assert, get_current_arch(), get_frame_register_value(), get_selected_frame(), MAX_REGISTER_SIZE, memcmp(), memcpy(), gdbtk_result::obj_ptr, old_regs, old_regs_count, register_size(), result_ptr, target_has_registers, value_contents_all(), value_entirely_available(), and value_optimized_out().
Referenced by gdb_register_info().
static void setup_architecture_data (void) [static]
Definition at line 471 of file gdbtk-register.c.
References gdbarch_num_pseudo_regs(), gdbarch_num_regs(), get_current_arch(), MAX_REGISTER_SIZE, old_regs, old_regs_count, regformat, xcalloc(), and xfree().
Referenced by Gdbtk_Register_Init().
Variable Documentation
char* old_regs = NULL [static]
Definition at line 65 of file gdbtk-register.c.
Referenced by register_changed_p(), and setup_architecture_data().
int old_regs_count = 0 [static]
Definition at line 66 of file gdbtk-register.c.
Referenced by register_changed_p(), and setup_architecture_data().
int* regformat = (int *)NULL [static]
Definition at line 67 of file gdbtk-register.c.
Referenced by gdb_regformat(), get_register(), and setup_architecture_data().
struct type** regtype = (struct type **)NULL [static]
Definition at line 68 of file gdbtk-register.c.
Referenced by default_print_one_register_info(), do_ppc_sysv_return_value(), ppc64_sysv_abi_push_dummy_call(), ppc64_sysv_abi_push_float(), ppc64_sysv_abi_return_value(), ppc_sysv_abi_push_dummy_call(), rs6000_lynx178_return_value(), and rs6000_return_value().