GDB (xrefs): /home/stan/gdb/src/gdb/gdbtk/generic/gdbtk-varobj.c File Reference
/home/stan/gdb/src/gdb/gdbtk/generic/gdbtk-varobj.c File Reference
#include "defs.h"
#include "value.h"
#include "gdb_string.h"
#include "varobj.h"
#include "exceptions.h"
#include <tcl.h>
#include "gdbtk.h"
#include "gdbtk-cmds.h"
#include "gdbtk-wrapper.h"
Functions
int gdb_variable_init (Tcl_Interp *)
static int gdb_variable_command (ClientData, Tcl_Interp *, int, Tcl_Obj *CONST[])
static int variable_obj_command (ClientData, Tcl_Interp *, int, Tcl_Obj *CONST[])
static int variable_create (Tcl_Interp *, int, Tcl_Obj *CONST[])
static void variable_delete (Tcl_Interp *, struct varobj *, int)
static Tcl_Obj * variable_children (Tcl_Interp *, struct varobj *)
static int variable_format (Tcl_Interp *, int, Tcl_Obj *CONST[], struct varobj *)
static int variable_type (Tcl_Interp *, int, Tcl_Obj *CONST[], struct varobj *)
static int variable_value (Tcl_Interp *, int, Tcl_Obj *CONST[], struct varobj *)
static Tcl_Obj * variable_update (Tcl_Interp *interp, struct varobj **var)
static void install_variable (Tcl_Interp *, char *)
static void uninstall_variable (Tcl_Interp *, char *)
static int gdb_variable_command (ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[])
static int variable_obj_command (ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[])
static int variable_create (Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[])
static int variable_format (Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[], struct varobj *var)
static int variable_type (Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[], struct varobj *var)
static int variable_value (Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[], struct varobj *var)
Variables
static char * format_string []
Function Documentation
static int gdb_variable_command (ClientData , Tcl_Interp * , int , Tcl_Obj * CONST[]) [static]
Referenced by gdb_variable_init().
static int gdb_variable_command (ClientData clientData, Tcl_Interp * interp, int objc, Tcl_Obj *CONST objv[]) [static]
Definition at line 118 of file gdbtk-varobj.c.
References variable_create().
int gdb_variable_init (Tcl_Interp * interp)
Definition at line 84 of file gdbtk-varobj.c.
References gdb_variable_command(), and gdbtk_call_wrapper().
Referenced by Gdbtk_Init().
static void install_variable (Tcl_Interp * interp, char * name) [static]
Definition at line 619 of file gdbtk-varobj.c.
References variable_obj_command().
Referenced by variable_children(), and variable_create().
static void uninstall_variable (Tcl_Interp * interp, char * varname) [static]
Definition at line 627 of file gdbtk-varobj.c.
Referenced by variable_delete().
static Tcl_Obj * variable_children (Tcl_Interp * interp, struct varobj * var) [static]
Definition at line 415 of file gdbtk-varobj.c.
References from, install_variable(), to, varobj_get_objname(), VEC, and VEC_iterate.
Referenced by variable_obj_command().
static int variable_create (Tcl_Interp * , int , Tcl_Obj * CONST[]) [static]
Referenced by gdb_variable_command().
static int variable_create (Tcl_Interp * interp, int objc, Tcl_Obj *CONST objv[]) [static]
Definition at line 293 of file gdbtk-varobj.c.
References gdbtk_result::flags, GDBTK_IN_TCL_RESULT, varobj::index, install_variable(), name, varobj::obj_name, result_ptr, string_to_core_addr(), USE_SELECTED_FRAME, USE_SPECIFIED_FRAME, varobj_create(), varobj_gen_name(), and xfree().
static void variable_delete (Tcl_Interp * interp, struct varobj * var, int only_children_p) [static]
Definition at line 394 of file gdbtk-varobj.c.
References uninstall_variable(), varobj_delete(), and xfree().
Referenced by variable_obj_command().
static int variable_format (Tcl_Interp * , int , Tcl_Obj * CONST[], struct varobj *) [static]
Referenced by variable_obj_command().
static int variable_format (Tcl_Interp * interp, int objc, Tcl_Obj *CONST objv[], struct varobj * var) [static]
Definition at line 482 of file gdbtk-varobj.c.
References FORMAT_BINARY, FORMAT_DECIMAL, FORMAT_HEXADECIMAL, FORMAT_NATURAL, FORMAT_OCTAL, format_string, gdbtk_set_result(), len, varobj_get_display_format(), and varobj_set_display_format().
static int variable_obj_command (ClientData , Tcl_Interp * , int , Tcl_Obj * CONST[]) [static]
Referenced by install_variable().
static int variable_obj_command (ClientData clientData, Tcl_Interp * interp, int objc, Tcl_Obj *CONST objv[]) [static]
Definition at line 169 of file gdbtk-varobj.c.
References varobj::index, len, name, variable_children(), variable_delete(), variable_format(), variable_type(), variable_update(), variable_value(), varobj_get_attributes(), varobj_get_expression(), varobj_get_handle(), varobj_get_num_children(), and xfree().
static int variable_type (Tcl_Interp * , int , Tcl_Obj * CONST[], struct varobj *) [static]
Referenced by variable_obj_command().
static int variable_type (Tcl_Interp * interp, int objc, Tcl_Obj *CONST objv[], struct varobj * var) [static]
Definition at line 525 of file gdbtk-varobj.c.
References string, varobj_get_type(), and xfree().
static Tcl_Obj * variable_update (Tcl_Interp * interp, struct varobj ** var) [static]
Definition at line 446 of file gdbtk-varobj.c.
References GDB_OK, GDB_varobj_update(), varobj_update_result_t::status, varobj_update_result_t::varobj, varobj_get_objname(), VAROBJ_IN_SCOPE, VAROBJ_INVALID, VAROBJ_NOT_IN_SCOPE, VEC, and VEC_iterate.
Referenced by variable_obj_command().
static int variable_value (Tcl_Interp * , int , Tcl_Obj * CONST[], struct varobj *) [static]
Referenced by variable_obj_command().
static int variable_value (Tcl_Interp * interp, int objc, Tcl_Obj *CONST objv[], struct varobj * var) [static]
Definition at line 565 of file gdbtk-varobj.c.
References gdbtk_set_result(), gdb_exception::reason, RETURN_MASK_ERROR, TRY_CATCH, varobj_get_attributes(), varobj_get_value(), varobj_set_value(), and xfree().
Variable Documentation
char* format_string[] [static]
Initial value:
  {"natural", "binary", "decimal", "hexadecimal", "octal"}
Definition at line 77 of file gdbtk-varobj.c.
Referenced by variable_format().