GDB (xrefs): /home/stan/gdb/src/gdb/gdbtk/generic/gdbtk-stack.c File Reference
/home/stan/gdb/src/gdb/gdbtk/generic/gdbtk-stack.c File Reference
#include "defs.h"
#include "target.h"
#include "breakpoint.h"
#include "linespec.h"
#include "block.h"
#include "dictionary.h"
#include "varobj.h"
#include "arch-utils.h"
#include "stack.h"
#include "solib.h"
#include <tcl.h>
#include "gdbtk.h"
#include "gdbtk-cmds.h"
#include "gdbtk-wrapper.h"
Functions
static int gdb_block_vars (ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[])
static int gdb_get_args_command (ClientData, Tcl_Interp *, int, Tcl_Obj *CONST objv[])
static int gdb_get_blocks (ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[])
static int gdb_get_locals_command (ClientData, Tcl_Interp *, int, Tcl_Obj *CONST objv[])
static int gdb_get_vars_command (ClientData, Tcl_Interp *, int, Tcl_Obj *CONST objv[])
static int gdb_selected_block (ClientData clientData, Tcl_Interp *interp, int argc, Tcl_Obj *CONST objv[])
static int gdb_selected_frame (ClientData clientData, Tcl_Interp *interp, int argc, Tcl_Obj *CONST objv[])
static int gdb_stack (ClientData, Tcl_Interp *, int, Tcl_Obj *CONST[])
static void get_frame_name (Tcl_Interp *interp, Tcl_Obj *list, struct frame_info *fi)
int Gdbtk_Stack_Init (Tcl_Interp *interp)
static int gdb_stack (ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[])
Function Documentation
static int gdb_block_vars (ClientData clientData, Tcl_Interp * interp, int objc, Tcl_Obj *CONST objv[]) [static]
Definition at line 89 of file gdbtk-stack.c.
References ALL_BLOCK_SYMBOLS, BLOCK_END, BLOCK_FUNCTION, BLOCK_START, BLOCK_SUPERBLOCK, get_frame_block(), get_selected_frame(), LOC_ARG, LOC_COMPUTED, LOC_LOCAL, LOC_REF_ARG, LOC_REGISTER, LOC_REGPARM_ADDR, LOC_STATIC, gdbtk_result::obj_ptr, result_ptr, string_to_core_addr(), SYMBOL_CLASS, SYMBOL_PRINT_NAME, and target_has_registers.
Referenced by Gdbtk_Stack_Init().
static int gdb_get_args_command (ClientData clientData, Tcl_Interp * interp, int objc, Tcl_Obj *CONST objv[]) [static]
Definition at line 246 of file gdbtk-stack.c.
References gdb_get_vars_command().
Referenced by Gdbtk_Stack_Init().
static int gdb_get_blocks (ClientData clientData, Tcl_Interp * interp, int objc, Tcl_Obj *CONST objv[]) [static]
Definition at line 159 of file gdbtk-stack.c.
References frame_info::addr, ALL_BLOCK_SYMBOLS, BLOCK_END, BLOCK_FUNCTION, BLOCK_START, BLOCK_SUPERBLOCK, free(), get_current_arch(), get_frame_block(), get_frame_pc(), get_selected_frame(), junk, LOC_ARG, LOC_BLOCK, LOC_COMPUTED, LOC_CONST, LOC_CONST_BYTES, LOC_LABEL, LOC_LOCAL, LOC_OPTIMIZED_OUT, LOC_REF_ARG, LOC_REGISTER, LOC_REGPARM_ADDR, LOC_STATIC, LOC_TYPEDEF, LOC_UNDEF, LOC_UNRESOLVED, gdbtk_result::obj_ptr, paddress(), result_ptr, SYMBOL_CLASS, target_has_registers, and xstrprintf().
Referenced by Gdbtk_Stack_Init().
static int gdb_get_locals_command (ClientData clientData, Tcl_Interp * interp, int objc, Tcl_Obj *CONST objv[]) [static]
Definition at line 254 of file gdbtk-stack.c.
References gdb_get_vars_command().
Referenced by Gdbtk_Stack_Init().
static int gdb_get_vars_command (ClientData clientData, Tcl_Interp * interp, int objc, Tcl_Obj *CONST objv[]) [static]
Definition at line 276 of file gdbtk-stack.c.
References ALL_BLOCK_SYMBOLS, arguments, block_for_pc(), BLOCK_FUNCTION, BLOCK_SUPERBLOCK, decode_line_1(), DECODE_LINE_FUNFIRSTLINE, gdbtk_set_result(), get_frame_block(), get_selected_frame(), LOC_ARG, LOC_BLOCK, LOC_COMPUTED, LOC_CONST, LOC_CONST_BYTES, LOC_LABEL, LOC_LOCAL, LOC_OPTIMIZED_OUT, LOC_REF_ARG, LOC_REGISTER, LOC_REGPARM_ADDR, LOC_STATIC, LOC_TYPEDEF, LOC_UNDEF, LOC_UNRESOLVED, symtabs_and_lines::nelts, gdbtk_result::obj_ptr, symtab_and_line::pc, resolve_sal_pc(), result_ptr, symtabs_and_lines::sals, SYMBOL_CLASS, SYMBOL_PRINT_NAME, and target_has_registers.
Referenced by gdb_get_args_command(), and gdb_get_locals_command().
static int gdb_selected_block (ClientData clientData, Tcl_Interp * interp, int argc, Tcl_Obj *CONST objv[]) [static]
Definition at line 377 of file gdbtk-stack.c.
References BLOCK_END, BLOCK_START, free(), get_current_arch(), get_frame_block(), get_selected_frame(), gdbtk_result::obj_ptr, paddress(), result_ptr, target_has_registers, and xstrprintf().
Referenced by Gdbtk_Stack_Init().
static int gdb_selected_frame (ClientData clientData, Tcl_Interp * interp, int argc, Tcl_Obj *CONST objv[]) [static]
Definition at line 420 of file gdbtk-stack.c.
References free(), get_current_arch(), get_frame_base(), get_selected_frame(), gdbtk_result::obj_ptr, paddress(), result_ptr, target_has_registers, and xstrprintf().
Referenced by Gdbtk_Stack_Init().
static int gdb_stack (ClientData , Tcl_Interp * , int , Tcl_Obj * CONST[]) [static]
Referenced by Gdbtk_Stack_Init().
static int gdb_stack (ClientData clientData, Tcl_Interp * interp, int objc, Tcl_Obj *CONST objv[]) [static]
Definition at line 449 of file gdbtk-stack.c.
References gdbtk_result::flags, GDB_find_relative_frame(), GDB_get_current_frame(), GDB_get_next_frame(), GDB_get_prev_frame(), GDB_OK, GDBTK_IN_TCL_RESULT, get_frame_name(), gdbtk_result::obj_ptr, result_ptr, and target_has_stack.
int Gdbtk_Stack_Init (Tcl_Interp * interp)
Definition at line 60 of file gdbtk-stack.c.
References gdb_block_vars(), gdb_get_args_command(), gdb_get_blocks(), gdb_get_locals_command(), gdb_selected_block(), gdb_selected_frame(), gdb_stack(), and gdbtk_call_wrapper().
Referenced by Gdbtk_Init().
static void get_frame_name (Tcl_Interp * interp, Tcl_Obj * list, struct frame_info * fi) [static]
Definition at line 524 of file gdbtk-stack.c.
References ARCH_FRAME, DUMMY_FRAME, find_frame_funname(), func, get_frame_pc(), get_frame_program_space(), get_frame_type(), language_unknown, SIGTRAMP_FRAME, solib_name_from_address(), and xfree().
Referenced by gdb_stack().