GDB (xrefs): /home/stan/gdb/src/gdb/gdbtk/generic/gdbtk-hooks.c File Reference
/home/stan/gdb/src/gdb/gdbtk/generic/gdbtk-hooks.c File Reference
#include "defs.h"
#include "inferior.h"
#include "symfile.h"
#include "objfiles.h"
#include "gdbcore.h"
#include "tracepoint.h"
#include "demangle.h"
#include "top.h"
#include "annotate.h"
#include "cli/cli-decode.h"
#include "observer.h"
#include "gdbthread.h"
#include <tcl.h>
#include <tk.h>
#include "guitcl.h"
#include "gdbtk.h"
#include <signal.h>
#include <fcntl.h>
#include <sys/time.h>
#include "gdb_string.h"
#include "dis-asm.h"
#include "gdbcmd.h"
Defines
#define HAS_STDARG 1
Functions
void gdbtk_create_breakpoint (struct breakpoint *)
void gdbtk_delete_breakpoint (struct breakpoint *)
void gdbtk_modify_breakpoint (struct breakpoint *)
static void gdbtk_architecture_changed (struct gdbarch *)
static void gdbtk_trace_find (char *arg, int from_tty)
static void gdbtk_trace_start_stop (int, int)
static void gdbtk_attach (void)
static void gdbtk_detach (void)
static void gdbtk_file_changed (char *)
static void gdbtk_exec_file_display (char *)
static void gdbtk_call_command (struct cmd_list_element *, char *, int)
static ptid_t gdbtk_wait (ptid_t, struct target_waitstatus *, int)
int x_event (int)
static int gdbtk_query (const char *, va_list)
static void gdbtk_warning (const char *, va_list)
static char * gdbtk_readline (char *)
static void gdbtk_readline_begin (char *format,...)
static void gdbtk_readline_end (void)
static void gdbtk_pre_add_symbol (const char *)
static void gdbtk_print_frame_info (struct symtab *, int, int, int)
static void gdbtk_post_add_symbol (void)
static void gdbtk_register_changed (int regno)
static void gdbtk_memory_changed (struct inferior *inferior, CORE_ADDR addr, ssize_t len, const bfd_byte *data)
static void gdbtk_selected_frame_changed (int)
static void gdbtk_context_change (int)
static void gdbtk_error_begin (void)
void report_error (void)
static void gdbtk_annotate_signal (void)
static void gdbtk_set_hook (struct cmd_list_element *cmdblk)
long gdbtk_read (struct ui_file *, char *, long)
void gdbtk_fputs (const char *, struct ui_file *)
static int gdbtk_load_hash (const char *, unsigned long)
void gdbtk_add_hooks (void)
void gdbtk_restore_result_ptr (void *old_result_ptr)
int gdbtk_two_elem_cmd (char *cmd_name, char *argv1)
struct ui_file * gdbtk_fileopenin (void)
struct ui_file * gdbtk_fileopen (void)
void gdbtk_ignorable_warning (const char *class, const char *warning)
ptid_t gdbtk_get_ptid (void)
Variables
volatile int in_fputs = 0
int gdbtk_force_detach = 0
static ptid_t gdbtk_ptid
gdbtk_result * result_ptr = NULL
Define Documentation
#define HAS_STDARG 1
Definition at line 45 of file gdbtk-hooks.c.
Function Documentation
void gdbtk_add_hooks (void)
Definition at line 120 of file gdbtk-hooks.c.
References deprecated_annotate_signal_hook, deprecated_annotate_signalled_hook, deprecated_attach_hook, deprecated_call_command_hook, deprecated_context_hook, deprecated_detach_hook, deprecated_error_begin_hook, deprecated_file_changed_hook, deprecated_interactive_hook, deprecated_post_add_symbol_hook, deprecated_pre_add_symbol_hook, deprecated_print_frame_info_listing_hook, deprecated_query_hook, deprecated_readline_begin_hook, deprecated_readline_end_hook, deprecated_readline_hook, deprecated_register_changed_hook, deprecated_selected_frame_level_changed_hook, deprecated_set_hook, deprecated_target_wait_hook, deprecated_trace_find_hook, deprecated_trace_start_stop_hook, deprecated_ui_load_progress_hook, deprecated_ui_loop_hook, deprecated_warning_hook, gdbtk_annotate_signal(), gdbtk_architecture_changed(), gdbtk_attach(), gdbtk_call_command(), gdbtk_context_change(), gdbtk_create_breakpoint(), gdbtk_delete_breakpoint(), gdbtk_detach(), gdbtk_error_begin(), gdbtk_exec_file_display(), gdbtk_file_changed(), gdbtk_interactive(), gdbtk_load_hash(), gdbtk_memory_changed(), gdbtk_modify_breakpoint(), gdbtk_post_add_symbol(), gdbtk_pre_add_symbol(), gdbtk_print_frame_info(), gdbtk_query(), gdbtk_readline(), gdbtk_readline_begin(), gdbtk_readline_end(), gdbtk_register_changed(), gdbtk_selected_frame_changed(), gdbtk_set_hook(), gdbtk_trace_find(), gdbtk_trace_start_stop(), gdbtk_wait(), gdbtk_warning(), observer_attach_architecture_changed(), observer_attach_breakpoint_created(), observer_attach_breakpoint_deleted(), observer_attach_breakpoint_modified(), observer_attach_memory_changed(), specify_exec_file_hook(), and x_event().
Referenced by gdbtk_interpreter_resume().
static void gdbtk_annotate_signal (void) [static]
Definition at line 792 of file gdbtk-hooks.c.
References free(), gdb_signal_to_name(), gdb_signal_to_string(), gdbtk_interp, inferior_ptid, inferior_thread(), null_ptid, ptid_equal(), report_error(), thread_suspend_state::stop_signal, thread_info::suspend, and xstrprintf().
Referenced by gdbtk_add_hooks().
static void gdbtk_architecture_changed (struct gdbarch * ignore) [static]
Definition at line 836 of file gdbtk-hooks.c.
References gdbtk_interp.
Referenced by gdbtk_add_hooks().
static void gdbtk_attach (void) [static]
Definition at line 817 of file gdbtk-hooks.c.
References gdbtk_interp, and report_error().
Referenced by gdbtk_add_hooks().
static void gdbtk_call_command (struct cmd_list_element * cmdblk, char * arg, int from_tty) [static]
Definition at line 526 of file gdbtk-hooks.c.
References cmd_list_element::class, class_run, class_trace, cmd_func(), gdbtk_interp, No_Update, and running_now.
Referenced by gdbtk_add_hooks().
static void gdbtk_context_change (int num) [static]
Definition at line 762 of file gdbtk-hooks.c.
References gdb_context.
Referenced by gdbtk_add_hooks().
void gdbtk_create_breakpoint (struct breakpoint *)
Definition at line 562 of file gdbtk-bp.c.
References BREAKPOINT_IS_INTERESTING, breakpoint_notify(), and breakpoint::number.
Referenced by gdbtk_add_hooks().
void gdbtk_delete_breakpoint (struct breakpoint *)
Definition at line 571 of file gdbtk-bp.c.
References breakpoint_notify(), and breakpoint::number.
Referenced by gdbtk_add_hooks().
static void gdbtk_detach (void) [static]
Definition at line 826 of file gdbtk-hooks.c.
References gdbtk_interp, and report_error().
Referenced by gdbtk_add_hooks().
static void gdbtk_error_begin (void) [static]
Definition at line 784 of file gdbtk-hooks.c.
References gdbtk_result::flags, and GDBTK_ERROR_ONLY.
Referenced by gdbtk_add_hooks().
static void gdbtk_exec_file_display (char * filename) [static]
Definition at line 776 of file gdbtk-hooks.c.
References gdbtk_two_elem_cmd().
Referenced by gdbtk_add_hooks().
static void gdbtk_file_changed (char * filename) [static]
Definition at line 769 of file gdbtk-hooks.c.
References gdbtk_two_elem_cmd().
Referenced by gdbtk_add_hooks().
struct ui_file* gdbtk_fileopen (void) [read]
Definition at line 226 of file gdbtk-hooks.c.
References gdbtk_fputs(), set_ui_file_fputs(), and ui_file_new().
Referenced by gdbtk_interpreter_init().
struct ui_file* gdbtk_fileopenin (void) [read]
Definition at line 218 of file gdbtk-hooks.c.
References gdbtk_read(), set_ui_file_read(), and ui_file_new().
Referenced by gdbtk_interpreter_init().
void gdbtk_fputs (const char * ptr, struct ui_file * stream)
Definition at line 295 of file gdbtk-hooks.c.
References gdbtk_result::flags, gdb_stderr, gdb_stdlog, gdb_stdtarg, gdbtk_disable_fputs, GDBTK_ERROR_ONLY, GDBTK_ERROR_STARTED, GDBTK_MAKES_LIST, GDBTK_TO_RESULT, gdbtk_two_elem_cmd(), in_fputs, and gdbtk_result::obj_ptr.
Referenced by gdbtk_fileopen(), and gdbtk_readline().
ptid_t gdbtk_get_ptid (void)
Definition at line 842 of file gdbtk-hooks.c.
References gdbtk_ptid.
Referenced by gdb_stop().
void gdbtk_ignorable_warning (const char * class, const char * warning)
Definition at line 377 of file gdbtk-hooks.c.
References free(), gdbtk_interp, report_error(), and xstrprintf().
Referenced by gdb_loadfile().
int gdbtk_load_hash (const char * section, unsigned long num) [static]
Definition at line 623 of file gdbtk-hooks.c.
References free(), gdbtk_interp, report_error(), and xstrprintf().
Referenced by gdbtk_add_hooks().
static void gdbtk_memory_changed (struct inferior * inferior, CORE_ADDR addr, ssize_t len, const bfd_byte * data) [static]
Definition at line 394 of file gdbtk-hooks.c.
References gdbtk_interp, and report_error().
Referenced by gdbtk_add_hooks().
void gdbtk_modify_breakpoint (struct breakpoint *)
Definition at line 577 of file gdbtk-bp.c.
References breakpoint_notify(), and breakpoint::number.
Referenced by gdbtk_add_hooks().
static void gdbtk_post_add_symbol (void) [static]
Definition at line 645 of file gdbtk-hooks.c.
References gdbtk_interp, and report_error().
Referenced by gdbtk_add_hooks().
static void gdbtk_pre_add_symbol (const char * name) [static]
Definition at line 638 of file gdbtk-hooks.c.
References gdbtk_two_elem_cmd().
Referenced by gdbtk_add_hooks().
static void gdbtk_print_frame_info (struct symtab * s, int line, int stopline, int noerror) [static]
Definition at line 691 of file gdbtk-hooks.c.
Referenced by gdbtk_add_hooks().
static int gdbtk_query (const char * query, va_list args) [static]
Definition at line 676 of file gdbtk-hooks.c.
References free(), gdbtk_interp, gdbtk_two_elem_cmd(), and xstrvprintf().
Referenced by gdbtk_add_hooks().
long gdbtk_read (struct ui_file * stream, char * buf, long sizeof_buf)
Definition at line 237 of file gdbtk-hooks.c.
References gdb_stdtargin, gdbtk_interp, memcpy(), and report_error().
Referenced by gdbtk_fileopenin().
static char * gdbtk_readline (char * prompt) [static]
Definition at line 496 of file gdbtk-hooks.c.
References gdb_stdout, gdbtk_fputs(), gdbtk_interp, and gdbtk_two_elem_cmd().
Referenced by gdbtk_add_hooks().
static void gdbtk_readline_begin (char * format, ...) [static]
Definition at line 484 of file gdbtk-hooks.c.
References free(), gdbtk_two_elem_cmd(), and xstrvprintf().
Referenced by gdbtk_add_hooks().
static void gdbtk_readline_end (void) [static]
Definition at line 519 of file gdbtk-hooks.c.
References gdbtk_interp, and report_error().
Referenced by gdbtk_add_hooks().
static void gdbtk_register_changed (int regno) [static]
Definition at line 387 of file gdbtk-hooks.c.
References gdbtk_interp, and report_error().
Referenced by gdbtk_add_hooks().
void gdbtk_restore_result_ptr (void * old_result_ptr)
Definition at line 189 of file gdbtk-hooks.c.
Referenced by gdbtk_load_asm().
static void gdbtk_selected_frame_changed (int level) [static]
Definition at line 746 of file gdbtk-hooks.c.
References gdbtk_interp, xfree(), and xstrprintf().
Referenced by gdbtk_add_hooks().
static void gdbtk_set_hook (struct cmd_list_element * cmdblk) [static]
Definition at line 550 of file gdbtk-hooks.c.
References free(), gdbtk_interp, cmd_list_element::name, p, cmd_list_element::prefixname, report_error(), Session::save(), strchr(), cmd_list_element::var, var_boolean, var_enum, var_filename, var_integer, var_string, var_string_noescape, cmd_list_element::var_type, var_uinteger, var_zinteger, and xstrprintf().
Referenced by gdbtk_add_hooks().
static void gdbtk_trace_find (char * arg, int from_tty) [static]
Definition at line 707 of file gdbtk-hooks.c.
References gdbtk_interp, and report_error().
Referenced by gdbtk_add_hooks().
static void gdbtk_trace_start_stop (int start, int from_tty) [static]
Definition at line 735 of file gdbtk-hooks.c.
References gdbtk_interp.
Referenced by gdbtk_add_hooks().
int gdbtk_two_elem_cmd (char * cmd_name, char * argv1)
Definition at line 197 of file gdbtk-hooks.c.
References free(), gdbtk_interp, malloc(), and report_error().
Referenced by gdbtk_exec_file_display(), gdbtk_file_changed(), gdbtk_fputs(), gdbtk_pre_add_symbol(), gdbtk_query(), gdbtk_readline(), gdbtk_readline_begin(), and gdbtk_warning().
static ptid_t gdbtk_wait (ptid_t ptid, struct target_waitstatus * ourstatus, int options) [static]
Definition at line 655 of file gdbtk-hooks.c.
References gdbtk_force_detach, gdbtk_start_timer(), gdbtk_stop_timer(), and target_wait().
Referenced by gdbtk_add_hooks().
static void gdbtk_warning (const char * warning, va_list args) [static]
Definition at line 346 of file gdbtk-hooks.c.
References free(), gdbtk_two_elem_cmd(), and xstrvprintf().
Referenced by gdbtk_add_hooks().
void report_error (void)
Definition at line 365 of file gdbtk-hooks.c.
References gdbtk_interp, and TclDebug().
Referenced by breakpoint_notify(), gdbtk_annotate_signal(), gdbtk_attach(), gdbtk_detach(), gdbtk_ignorable_warning(), gdbtk_load_hash(), gdbtk_memory_changed(), gdbtk_post_add_symbol(), gdbtk_read(), gdbtk_readline_end(), gdbtk_register_changed(), gdbtk_set_hook(), gdbtk_trace_find(), and gdbtk_two_elem_cmd().
int x_event (int signo)
Definition at line 430 of file gdbtk-hooks.c.
References gdbtk_force_detach, gdbtk_interp, immediate_quit, in_fputs, load_in_progress, quit(), running_now, and set_quit_flag().
Referenced by gdbtk_add_hooks(), and x_event_wrapper().
Variable Documentation
int gdbtk_force_detach = 0
Definition at line 68 of file gdbtk-hooks.c.
Referenced by gdb_stop(), gdbtk_wait(), and x_event().
ptid_t gdbtk_ptid [static]
Definition at line 112 of file gdbtk-hooks.c.
Referenced by gdbtk_get_ptid().
volatile int in_fputs = 0
Definition at line 64 of file gdbtk-hooks.c.
Referenced by gdbtk_fputs(), and x_event().
gdbtk_result* result_ptr = NULL
Definition at line 183 of file gdbtk-hooks.c.
Referenced by gdb_actions_command(), gdb_block_vars(), gdb_CA_to_TAS(), gdb_cmd(), gdb_confirm_quit(), gdb_entry_point(), gdb_eval(), gdb_find_bp_at_addr(), gdb_find_bp_at_line(), gdb_find_file_command(), gdb_get_blocks(), gdb_get_breakpoint_info(), gdb_get_breakpoint_list(), gdb_get_file_command(), gdb_get_function_command(), gdb_get_inferior_args(), gdb_get_line_command(), gdb_get_trace_frame_num(), gdb_get_tracepoint_info(), gdb_get_tracepoint_list(), gdb_get_vars_command(), gdb_immediate_command(), gdb_incr_addr(), gdb_list_processes(), gdb_listfiles(), gdb_listfuncs(), gdb_load_disassembly(), gdb_load_info(), gdb_loc(), gdb_path_conv(), gdb_prompt_command(), gdb_reggroup(), gdb_reggrouplist(), gdb_register_info(), gdb_search(), gdb_selected_block(), gdb_selected_frame(), gdb_set_bp(), gdb_stack(), gdb_target_has_execution_command(), gdb_trace_status(), gdb_tracepoint_exists_command(), gdb_update_mem(), gdbtk_call_wrapper(), gdbtk_load_asm(), get_register(), get_register_name(), get_register_size(), get_register_types(), lookup_symtab_callback(), map_arg_registers(), register_changed_p(), and variable_create().