GDB (xrefs): /home/stan/gdb/src/gdb/gdbtk/generic/gdbtk-interp.c File Reference
/home/stan/gdb/src/gdb/gdbtk/generic/gdbtk-interp.c File Reference
#include "defs.h"
#include "interps.h"
#include "ui-file.h"
#include "ui-out.h"
#include "cli-out.h"
#include "gdb_string.h"
#include "cli/cli-cmds.h"
#include "cli/cli-decode.h"
#include "exceptions.h"
#include "tcl.h"
#include "tk.h"
#include "gdbtk.h"
Classes
struct gdbtk_interp_data
Functions
static void gdbtk_command_loop (void *)
static void hack_disable_interpreter_exec (char *, int)
void _initialize_gdbtk_interp (void)
static void * gdbtk_interpreter_init (struct interp *interp, int top_level)
static int gdbtk_interpreter_resume (void *data)
static int gdbtk_interpreter_suspend (void *data)
static int gdbtk_interpreter_display_prompt_p (void *data)
static struct gdb_exception gdbtk_interpreter_exec (void *data, const char *command_str)
static struct ui_out * gdbtk_interpreter_ui_out (struct interp *interp)
Function Documentation
void _initialize_gdbtk_interp (void)
static void gdbtk_command_loop (void * data) [static]
Definition at line 143 of file gdbtk-interp.c.
References fputs_unfiltered(), gdb_stderr, gdbtk_interp, and instream.
static int gdbtk_interpreter_display_prompt_p (void * data) [static]
Definition at line 126 of file gdbtk-interp.c.
static struct gdb_exception gdbtk_interpreter_exec (void * data, const char * command_str) [static, read]
Definition at line 132 of file gdbtk-interp.c.
References exception_none.
static void* gdbtk_interpreter_init (struct interp * interp, int top_level) [static]
Definition at line 65 of file gdbtk-interp.c.
References gdbtk_interp_data::_stderr, gdbtk_interp_data::_stdlog, gdbtk_interp_data::_stdout, gdbtk_interp_data::_stdtarg, gdbtk_interp_data::_stdtargin, cli_out_new(), gdbtk_fileopen(), gdbtk_fileopenin(), gdbtk_init(), hack_disable_interpreter_exec(), lookup_cmd_composition(), cmd_list_element::prefix, set_cmd_cfunc(), gdbtk_interp_data::uiout, and XZALLOC.
static int gdbtk_interpreter_resume (void * data) [static]
Definition at line 92 of file gdbtk-interp.c.
References gdbtk_interp_data::_stderr, gdbtk_interp_data::_stdlog, gdbtk_interp_data::_stdout, gdbtk_interp_data::_stdtarg, gdbtk_interp_data::_stdtargin, gdb_stderr, gdb_stdlog, gdb_stdout, gdb_stdtarg, gdb_stdtargin, gdbtk_add_hooks(), and gdbtk_source_start_file().
static int gdbtk_interpreter_suspend (void * data) [static]
Definition at line 120 of file gdbtk-interp.c.
static struct ui_out* gdbtk_interpreter_ui_out (struct interp * interp) [static, read]
Definition at line 173 of file gdbtk-interp.c.
References interp_data(), and gdbtk_interp_data::uiout.
static void hack_disable_interpreter_exec (char * args, int from_tty) [static]
Definition at line 59 of file gdbtk-interp.c.
References error().
Referenced by gdbtk_interpreter_init().