GDB (xrefs): /home/stan/gdb/src/gdb/gdbtk/generic/gdbtk.c File Reference
/home/stan/gdb/src/gdb/gdbtk/generic/gdbtk.c File Reference
#include "defs.h"
#include "inferior.h"
#include "symfile.h"
#include "objfiles.h"
#include "gdbcore.h"
#include "tracepoint.h"
#include "demangle.h"
#include "version.h"
#include "top.h"
#include "annotate.h"
#include "exceptions.h"
#include "main.h"
#include <tcl.h>
#include <tk.h>
#include "guitcl.h"
#include "gdbtk.h"
#include <fcntl.h>
#include "gdb_stat.h"
#include <sys/time.h>
#include <signal.h>
#include "gdb_string.h"
#include "dis-asm.h"
#include "gdbcmd.h"
Defines
#define HAS_STDARG 1
Functions
void _initialize_gdbtk (void)
static void x_event_wrapper (int signo)
int Tktable_Init (Tcl_Interp *interp)
void gdbtk_init (void)
void gdbtk_interactive (void)
static void cleanup_init (void *ignore)
static void tk_command (char *, int)
static int target_should_use_timer (struct target_ops *t)
int target_is_native (struct target_ops *t)
int gdbtk_test (char *)
static void view_command (char *, int)
void TclDebug (char level, const char *fmt,...)
void gdbtk_start_timer (void)
void gdbtk_stop_timer (void)
static void gdbtk_cleanup (PTR dummy)
void gdbtk_source_start_file (void)
Variables
static sigset_t nullsigmask
static struct sigaction act1 act2
static struct itimerval it_on it_off
char * external_editor_command = NULL
Tcl_Interp * gdbtk_interp = NULL
static int gdbtk_timer_going = 0
int gdb_context = 0
int running_now
static char * gdbtk_source_filename = NULL
int gdbtk_disable_fputs = 1
Define Documentation
#define HAS_STDARG 1
Definition at line 43 of file gdbtk.c.
Function Documentation
void _initialize_gdbtk (void)
static void cleanup_init (void * ignore) [static]
Definition at line 239 of file gdbtk.c.
References gdbtk_interp.
Referenced by gdbtk_init().
static void gdbtk_cleanup (PTR dummy) [static]
Definition at line 344 of file gdbtk.c.
References gdbtk_interp.
Referenced by gdbtk_init().
void gdbtk_init (void)
Definition at line 359 of file gdbtk.c.
References add_com(), class_obscure, cleanup_init(), discard_cleanups(), error(), external_editor_command, free(), gdbtk_cleanup(), Gdbtk_Init(), gdbtk_interp, get_gdb_program_name(), host_name, inhibit_gdbinit, make_cleanup(), make_final_cleanup(), target_name, tk_command(), Tktable_Init(), view_command(), xfree(), and xstrprintf().
Referenced by gdbtk_interpreter_init().
void gdbtk_interactive (void)
Definition at line 250 of file gdbtk.c.
Referenced by gdbtk_add_hooks().
void gdbtk_source_start_file (void)
Definition at line 590 of file gdbtk.c.
References gdb_exception::error, free(), gdbtk_disable_fputs, gdbtk_interp, gdbtk_source_filename, GENERIC_ERROR, gdb_exception::message, gdb_exception::reason, RETURN_ERROR, and throw_exception().
Referenced by gdbtk_interpreter_resume().
void gdbtk_start_timer (void)
Definition at line 257 of file gdbtk.c.
References act2, current_target, gdbtk_timer_going, it_off, nullsigmask, target_should_use_timer(), and x_event_wrapper().
Referenced by gdbtk_wait().
void gdbtk_stop_timer (void)
Definition at line 304 of file gdbtk.c.
References act2, gdbtk_timer_going, and it_off.
Referenced by gdbtk_call_wrapper(), and gdbtk_wait().
int gdbtk_test (char * filename)
Definition at line 669 of file gdbtk.c.
References gdbtk_source_filename.
Referenced by captured_main().
int target_is_native (struct target_ops * t)
Definition at line 327 of file gdbtk.c.
References name, and target_ops::to_shortname.
Referenced by target_should_use_timer().
static int target_should_use_timer (struct target_ops * t) [static]
Definition at line 320 of file gdbtk.c.
References target_is_native().
Referenced by gdbtk_start_timer().
void TclDebug (char level, const char * fmt, ...)
Definition at line 188 of file gdbtk.c.
References free(), gdbtk_interp, and xstrvprintf().
Referenced by report_error().
static void tk_command (char * cmd, int from_tty) [static]
Definition at line 715 of file gdbtk.c.
References do_cleanups(), error(), error_no_arg(), gdbtk_interp, make_cleanup(), printf_unfiltered(), and xfree().
Referenced by gdbtk_init().
int Tktable_Init (Tcl_Interp * interp)
Referenced by gdbtk_init().
static void view_command (char * args, int from_tty) [static]
Definition at line 741 of file gdbtk.c.
References do_cleanups(), error(), gdbtk_interp, make_cleanup(), xfree(), and xstrprintf().
Referenced by gdbtk_init().
static void x_event_wrapper (int signo) [static]
Definition at line 76 of file gdbtk.c.
References x_event().
Referenced by gdbtk_start_timer().
Variable Documentation
struct sigaction act1 act2 [static]
Definition at line 72 of file gdbtk.c.
Referenced by gdbtk_start_timer(), and gdbtk_stop_timer().
char* external_editor_command = NULL
Definition at line 86 of file gdbtk.c.
Referenced by captured_main(), and gdbtk_init().
int gdb_context = 0
Definition at line 112 of file gdbtk.c.
Referenced by gdbtk_context_change(), and Gdbtk_Init().
int gdbtk_disable_fputs = 1
Definition at line 123 of file gdbtk.c.
Referenced by gdb_restore_fputs(), gdbtk_fputs(), and gdbtk_source_start_file().
Tcl_Interp* gdbtk_interp = NULL
Definition at line 107 of file gdbtk.c.
Referenced by breakpoint_notify(), cleanup_init(), gdbtk_annotate_signal(), gdbtk_architecture_changed(), gdbtk_attach(), gdbtk_call_command(), gdbtk_cleanup(), gdbtk_command_loop(), gdbtk_detach(), gdbtk_ignorable_warning(), Gdbtk_Init(), gdbtk_init(), gdbtk_load_hash(), gdbtk_memory_changed(), gdbtk_post_add_symbol(), gdbtk_query(), gdbtk_read(), gdbtk_readline(), gdbtk_readline_end(), gdbtk_register_changed(), gdbtk_selected_frame_changed(), gdbtk_set_hook(), gdbtk_source_start_file(), gdbtk_trace_find(), gdbtk_trace_start_stop(), gdbtk_two_elem_cmd(), get_register_size(), get_register_types(), report_error(), TclDebug(), tk_command(), view_command(), and x_event().
char* gdbtk_source_filename = NULL [static]
Definition at line 121 of file gdbtk.c.
Referenced by gdbtk_source_start_file(), and gdbtk_test().
int gdbtk_timer_going = 0 [static]
Definition at line 109 of file gdbtk.c.
Referenced by gdbtk_start_timer(), and gdbtk_stop_timer().
struct itimerval it_on it_off [static]
Definition at line 73 of file gdbtk.c.
Referenced by gdbtk_start_timer(), and gdbtk_stop_timer().
sigset_t nullsigmask [static]
Definition at line 71 of file gdbtk.c.
Referenced by gdbtk_start_timer().
int running_now
Definition at line 117 of file gdbtk.c.
Referenced by gdb_cmd(), gdb_immediate_command(), gdbtk_call_command(), gdbtk_call_wrapper(), and x_event().