GDB (xrefs): /home/stan/gdb/src/gdb/gdbtk/generic/gdbtk.h File Reference
/home/stan/gdb/src/gdb/gdbtk/generic/gdbtk.h File Reference
Classes
struct gdbtk_result
Defines
#define GDBTK_PATH_SEP ":"
#define GDBTK_MAJOR_VERSION "1"
#define GDBTK_MINOR_VERSION "0"
#define GDBTK_VERSION "1.0"
#define GDBTK_TO_RESULT
#define GDBTK_MAKES_LIST
#define GDBTK_IN_TCL_RESULT
#define GDBTK_ERROR_STARTED
#define GDBTK_ERROR_ONLY
#define GDBTK_SYMBOL_SOURCE_NAME(symbol)
Typedefs
typedef struct gdbtk_result gdbtk_result
Functions
void gdbtk_restore_result_ptr (void *)
int Gdbtk_Init (Tcl_Interp *interp)
void gdbtk_stop_timer (void)
void gdbtk_start_timer (void)
void gdbtk_ignorable_warning (const char *, const char *)
void gdbtk_interactive (void)
int x_event (int)
int gdbtk_two_elem_cmd (char *, char *)
int target_is_native (struct target_ops *t)
void gdbtk_fputs (const char *, struct ui_file *)
struct ui_file * gdbtk_fileopen (void)
struct ui_file * gdbtk_fileopenin (void)
ptid_t gdbtk_get_ptid (void)
void TclDebug (char level, const char *fmt,...)
void gdbtk_add_hooks (void)
void gdbtk_init (void)
void gdbtk_source_start_file (void)
Variables
int disassemble_from_exec
int running_now
int No_Update
int load_in_progress
Tcl_Interp * gdbtk_interp
gdbtk_result * result_ptr
int gdb_context
int gdbtk_force_detach
int gdbtk_disable_fputs
Define Documentation
#define GDBTK_ERROR_ONLY
Value:
16      /* Indicates that all incoming I/O is
                                   to be treated as if it had arrived for gdb_stderr. This is
                                   used to help error_begin in utils.c. */
Definition at line 109 of file gdbtk.h.
Referenced by gdbtk_error_begin(), and gdbtk_fputs().
#define GDBTK_ERROR_STARTED
Value:
8       /* This one is just used in gdbtk_fputs.  If we
                                   see some output on stderr, we need to clear
                                   the result we have been accumulating, or the
                                   error and the previous successful output
                                   will get mixed, which would be confusing. */
Definition at line 108 of file gdbtk.h.
Referenced by gdbtk_fputs().
#define GDBTK_IN_TCL_RESULT
Value:
4       /* Indicates that the result is already in the
                                   Tcl result.  You can use this to preserve
                                   error messages from functions like
                                   Tcl_GetIntFromObj.  You can also store the
                                   output of a call wrapped command directly in
                                   the Tcl result if you want, but beware, it will
                                   not then be preserved across recursive
                                   gdbtk_call_wrapper invocations. */
Definition at line 107 of file gdbtk.h.
Referenced by gdb_actions_command(), gdb_eval(), gdb_find_bp_at_line(), gdb_get_breakpoint_info(), gdb_get_tracepoint_info(), gdb_register_info(), gdb_search(), gdb_set_bp(), gdb_stack(), gdbtk_call_wrapper(), map_arg_registers(), and variable_create().
#define GDBTK_MAJOR_VERSION "1"
Definition at line 48 of file gdbtk.h.
#define GDBTK_MAKES_LIST
Value:
2       /* whether gdbtk_fputs adds the
                                   element it is outputting as a string, or
                                   as a separate list element. */
Definition at line 106 of file gdbtk.h.
Referenced by gdbtk_fputs(), get_register(), and map_arg_registers().
#define GDBTK_MINOR_VERSION "0"
Definition at line 49 of file gdbtk.h.
#define GDBTK_PATH_SEP ":"
Definition at line 31 of file gdbtk.h.
#define GDBTK_SYMBOL_SOURCE_NAME (symbol)
Value:
(SYMBOL_DEMANGLED_NAME (symbol) != NULL \
       ? SYMBOL_DEMANGLED_NAME (symbol)       \
       : SYMBOL_PRINT_NAME (symbol))
Definition at line 159 of file gdbtk.h.
Referenced by pc_function_name().
#define GDBTK_TO_RESULT
Value:
1       /* This controls whether output from
                                   gdbtk_fputs goes to the command result, or
                                   to gdbtk_tcl_fputs. */
Definition at line 105 of file gdbtk.h.
Referenced by gdb_cmd(), gdb_immediate_command(), gdbtk_call_wrapper(), gdbtk_fputs(), and gdbtk_load_asm().
#define GDBTK_VERSION "1.0"
Definition at line 50 of file gdbtk.h.
Referenced by Gdbtk_Init().
Typedef Documentation
typedef struct gdbtk_result gdbtk_result
Function Documentation
void gdbtk_add_hooks (void)
Definition at line 120 of file gdbtk-hooks.c.
References deprecated_annotate_signal_hook, deprecated_annotate_signalled_hook, deprecated_attach_hook, deprecated_call_command_hook, deprecated_context_hook, deprecated_detach_hook, deprecated_error_begin_hook, deprecated_file_changed_hook, deprecated_interactive_hook, deprecated_post_add_symbol_hook, deprecated_pre_add_symbol_hook, deprecated_print_frame_info_listing_hook, deprecated_query_hook, deprecated_readline_begin_hook, deprecated_readline_end_hook, deprecated_readline_hook, deprecated_register_changed_hook, deprecated_selected_frame_level_changed_hook, deprecated_set_hook, deprecated_target_wait_hook, deprecated_trace_find_hook, deprecated_trace_start_stop_hook, deprecated_ui_load_progress_hook, deprecated_ui_loop_hook, deprecated_warning_hook, gdbtk_annotate_signal(), gdbtk_architecture_changed(), gdbtk_attach(), gdbtk_call_command(), gdbtk_context_change(), gdbtk_create_breakpoint(), gdbtk_delete_breakpoint(), gdbtk_detach(), gdbtk_error_begin(), gdbtk_exec_file_display(), gdbtk_file_changed(), gdbtk_interactive(), gdbtk_load_hash(), gdbtk_memory_changed(), gdbtk_modify_breakpoint(), gdbtk_post_add_symbol(), gdbtk_pre_add_symbol(), gdbtk_print_frame_info(), gdbtk_query(), gdbtk_readline(), gdbtk_readline_begin(), gdbtk_readline_end(), gdbtk_register_changed(), gdbtk_selected_frame_changed(), gdbtk_set_hook(), gdbtk_trace_find(), gdbtk_trace_start_stop(), gdbtk_wait(), gdbtk_warning(), observer_attach_architecture_changed(), observer_attach_breakpoint_created(), observer_attach_breakpoint_deleted(), observer_attach_breakpoint_modified(), observer_attach_memory_changed(), specify_exec_file_hook(), and x_event().
Referenced by gdbtk_interpreter_resume().
struct ui_file* gdbtk_fileopen (void) [read]
Definition at line 226 of file gdbtk-hooks.c.
References gdbtk_fputs(), set_ui_file_fputs(), and ui_file_new().
Referenced by gdbtk_interpreter_init().
struct ui_file* gdbtk_fileopenin (void) [read]
Definition at line 218 of file gdbtk-hooks.c.
References gdbtk_read(), set_ui_file_read(), and ui_file_new().
Referenced by gdbtk_interpreter_init().
void gdbtk_fputs (const char * , struct ui_file *)
Definition at line 295 of file gdbtk-hooks.c.
References gdbtk_result::flags, gdb_stderr, gdb_stdlog, gdb_stdtarg, gdbtk_disable_fputs, GDBTK_ERROR_ONLY, GDBTK_ERROR_STARTED, GDBTK_MAKES_LIST, GDBTK_TO_RESULT, gdbtk_two_elem_cmd(), in_fputs, and gdbtk_result::obj_ptr.
Referenced by gdbtk_fileopen(), and gdbtk_readline().
ptid_t gdbtk_get_ptid (void)
Definition at line 842 of file gdbtk-hooks.c.
References gdbtk_ptid.
Referenced by gdb_stop().
void gdbtk_ignorable_warning (const char * , const char *)
Definition at line 377 of file gdbtk-hooks.c.
References free(), gdbtk_interp, report_error(), and xstrprintf().
Referenced by gdb_loadfile().
int Gdbtk_Init (Tcl_Interp * interp)
Definition at line 248 of file gdbtk-cmds.c.
References current_directory, disassemble_from_exec, gdb_CA_to_TAS(), gdb_clear_file(), gdb_cmd(), gdb_confirm_quit(), gdb_context, gdb_entry_point(), gdb_eval(), gdb_find_file_command(), gdb_force_quit(), gdb_get_file_command(), gdb_get_function_command(), gdb_get_inferior_args(), gdb_get_line_command(), gdb_immediate_command(), gdb_incr_addr(), gdb_list_processes(), gdb_listfiles(), gdb_listfuncs(), gdb_load_disassembly(), gdb_load_info(), gdb_loadfile(), gdb_loc(), gdb_path_conv(), gdb_prompt_command(), gdb_restore_fputs(), gdb_search(), gdb_set_inferior_args(), gdb_set_mem(), gdb_stop(), gdb_target_has_execution_command(), gdb_update_mem(), gdb_variable_init(), Gdbtk_Breakpoint_Init(), gdbtk_call_wrapper(), gdbtk_interp, Gdbtk_Register_Init(), Gdbtk_Stack_Init(), GDBTK_VERSION, and source_path.
Referenced by gdbtk_init().
void gdbtk_init (void)
Definition at line 359 of file gdbtk.c.
References add_com(), class_obscure, cleanup_init(), discard_cleanups(), error(), external_editor_command, free(), gdbtk_cleanup(), Gdbtk_Init(), gdbtk_interp, get_gdb_program_name(), host_name, inhibit_gdbinit, make_cleanup(), make_final_cleanup(), target_name, tk_command(), Tktable_Init(), view_command(), xfree(), and xstrprintf().
Referenced by gdbtk_interpreter_init().
void gdbtk_interactive (void)
Definition at line 250 of file gdbtk.c.
Referenced by gdbtk_add_hooks().
void gdbtk_restore_result_ptr (void *)
Definition at line 189 of file gdbtk-hooks.c.
Referenced by gdbtk_load_asm().
void gdbtk_source_start_file (void)
Definition at line 590 of file gdbtk.c.
References gdb_exception::error, free(), gdbtk_disable_fputs, gdbtk_interp, gdbtk_source_filename, GENERIC_ERROR, gdb_exception::message, gdb_exception::reason, RETURN_ERROR, and throw_exception().
Referenced by gdbtk_interpreter_resume().
void gdbtk_start_timer (void)
Definition at line 257 of file gdbtk.c.
References act2, current_target, gdbtk_timer_going, it_off, nullsigmask, target_should_use_timer(), and x_event_wrapper().
Referenced by gdbtk_wait().
void gdbtk_stop_timer (void)
Definition at line 304 of file gdbtk.c.
References act2, gdbtk_timer_going, and it_off.
Referenced by gdbtk_call_wrapper(), and gdbtk_wait().
int gdbtk_two_elem_cmd (char * , char *)
Definition at line 197 of file gdbtk-hooks.c.
References free(), gdbtk_interp, malloc(), and report_error().
Referenced by gdbtk_exec_file_display(), gdbtk_file_changed(), gdbtk_fputs(), gdbtk_pre_add_symbol(), gdbtk_query(), gdbtk_readline(), gdbtk_readline_begin(), and gdbtk_warning().
int target_is_native (struct target_ops * t)
Definition at line 327 of file gdbtk.c.
References name, and target_ops::to_shortname.
Referenced by target_should_use_timer().
void TclDebug (char level, const char * fmt, ...)
Definition at line 188 of file gdbtk.c.
References free(), gdbtk_interp, and xstrvprintf().
Referenced by report_error().
int x_event (int)
Definition at line 430 of file gdbtk-hooks.c.
References gdbtk_force_detach, gdbtk_interp, immediate_quit, in_fputs, load_in_progress, quit(), running_now, and set_quit_flag().
Referenced by gdbtk_add_hooks(), and x_event_wrapper().
Variable Documentation
int disassemble_from_exec
Definition at line 147 of file gdbtk-cmds.c.
Referenced by Gdbtk_Init().
int gdb_context
Definition at line 112 of file gdbtk.c.
Referenced by gdbtk_context_change(), and Gdbtk_Init().
int gdbtk_disable_fputs
Definition at line 123 of file gdbtk.c.
Referenced by gdb_restore_fputs(), gdbtk_fputs(), and gdbtk_source_start_file().
int gdbtk_force_detach
Definition at line 68 of file gdbtk-hooks.c.
Referenced by gdb_stop(), gdbtk_wait(), and x_event().
Tcl_Interp* gdbtk_interp
Definition at line 107 of file gdbtk.c.
Referenced by breakpoint_notify(), cleanup_init(), gdbtk_annotate_signal(), gdbtk_architecture_changed(), gdbtk_attach(), gdbtk_call_command(), gdbtk_cleanup(), gdbtk_command_loop(), gdbtk_detach(), gdbtk_ignorable_warning(), Gdbtk_Init(), gdbtk_init(), gdbtk_load_hash(), gdbtk_memory_changed(), gdbtk_post_add_symbol(), gdbtk_query(), gdbtk_read(), gdbtk_readline(), gdbtk_readline_end(), gdbtk_register_changed(), gdbtk_selected_frame_changed(), gdbtk_set_hook(), gdbtk_source_start_file(), gdbtk_trace_find(), gdbtk_trace_start_stop(), gdbtk_two_elem_cmd(), get_register_size(), get_register_types(), report_error(), TclDebug(), tk_command(), view_command(), and x_event().
int load_in_progress
Definition at line 110 of file gdbtk-cmds.c.
Referenced by gdb_cmd(), gdb_immediate_command(), gdbtk_call_wrapper(), and x_event().
int No_Update
Definition at line 109 of file gdbtk-cmds.c.
Referenced by gdb_cmd(), gdb_immediate_command(), and gdbtk_call_command().
gdbtk_result* result_ptr
Definition at line 183 of file gdbtk-hooks.c.
Referenced by gdb_actions_command(), gdb_block_vars(), gdb_CA_to_TAS(), gdb_cmd(), gdb_confirm_quit(), gdb_entry_point(), gdb_eval(), gdb_find_bp_at_addr(), gdb_find_bp_at_line(), gdb_find_file_command(), gdb_get_blocks(), gdb_get_breakpoint_info(), gdb_get_breakpoint_list(), gdb_get_file_command(), gdb_get_function_command(), gdb_get_inferior_args(), gdb_get_line_command(), gdb_get_trace_frame_num(), gdb_get_tracepoint_info(), gdb_get_tracepoint_list(), gdb_get_vars_command(), gdb_immediate_command(), gdb_incr_addr(), gdb_list_processes(), gdb_listfiles(), gdb_listfuncs(), gdb_load_disassembly(), gdb_load_info(), gdb_loc(), gdb_path_conv(), gdb_prompt_command(), gdb_reggroup(), gdb_reggrouplist(), gdb_register_info(), gdb_search(), gdb_selected_block(), gdb_selected_frame(), gdb_set_bp(), gdb_stack(), gdb_target_has_execution_command(), gdb_trace_status(), gdb_tracepoint_exists_command(), gdb_update_mem(), gdbtk_call_wrapper(), gdbtk_load_asm(), get_register(), get_register_name(), get_register_size(), get_register_types(), lookup_symtab_callback(), map_arg_registers(), register_changed_p(), and variable_create().
int running_now
Definition at line 117 of file gdbtk.c.
Referenced by gdb_cmd(), gdb_immediate_command(), gdbtk_call_command(), gdbtk_call_wrapper(), and x_event().