GDB (xrefs): /home/stan/gdb/src/gdb/glibc-tdep.h File Reference
/home/stan/gdb/src/gdb/glibc-tdep.h File Reference
Functions
CORE_ADDR glibc_skip_solib_resolver (struct gdbarch *gdbarch, CORE_ADDR)
Function Documentation
CORE_ADDR glibc_skip_solib_resolver (struct gdbarch * gdbarch, CORE_ADDR)
Definition at line 38 of file glibc-tdep.c.
References frame_unwind_caller_pc(), get_current_frame(), lookup_minimal_symbol(), lookup_minimal_symbol_and_objfile(), bound_minimal_symbol::minsym, bound_minimal_symbol::objfile, and SYMBOL_VALUE_ADDRESS.
Referenced by amd64_linux_init_abi_common(), arm_linux_init_abi(), hppa_linux_init_abi(), i386_linux_init_abi(), m68k_linux_init_abi(), mips_linux_skip_resolver(), nios2_linux_init_abi(), ppc_linux_init_abi(), sh_linux_init_abi(), and tilegx_linux_init_abi().