GDB (xrefs): /home/stan/gdb/src/gdb/gnu-nat.c File Reference
/home/stan/gdb/src/gdb/gnu-nat.c File Reference
#include "defs.h"
#include <ctype.h>
#include <errno.h>
#include <limits.h>
#include <setjmp.h>
#include <signal.h>
#include <stdio.h>
#include "gdb_string.h"
#include <sys/ptrace.h>
#include <mach.h>
#include <mach_error.h>
#include <mach/exception.h>
#include <mach/message.h>
#include <mach/notify.h>
#include <mach/vm_attributes.h>
#include <hurd.h>
#include <hurd/interrupt.h>
#include <hurd/msg.h>
#include <hurd/msg_request.h>
#include <hurd/process.h>
#include <hurd/process_request.h>
#include <hurd/signal.h>
#include <hurd/sigpreempt.h>
#include <portinfo.h>
#include "inferior.h"
#include "symtab.h"
#include "value.h"
#include "language.h"
#include "target.h"
#include "gdb_wait.h"
#include "gdbcmd.h"
#include "gdbcore.h"
#include "gdbthread.h"
#include "gdb_assert.h"
#include "gdb_obstack.h"
#include "gnu-nat.h"
#include "inf-child.h"
#include "exc_request_S.h"
#include "notify_S.h"
#include "process_reply_S.h"
#include "msg_reply_S.h"
#include "exc_request_U.h"
#include "msg_U.h"
Classes
struct exc_state
struct inf_wait
struct inf
struct vm_region_list
Defines
#define inf_debug(_inf, msg, args...)
#define INF_MSGPORT_RPC(inf, rpc_expr)
#define INF_RESUME_MSGPORT_RPC(inf, rpc_expr)
#define NAME gdb_signal_to_name (sig)
#define CHK_GOTO_OUT(str, ret) do if (ret != KERN_SUCCESS) { errstr = #str; goto out; } while(0)
#define parse_bool_arg(args, cmd_prefix) _parse_bool_arg (args, "on", "off", cmd_prefix)
Functions
struct inf * make_inf ()
void inf_clear_wait (struct inf *inf)
void inf_cleanup (struct inf *inf)
void inf_startup (struct inf *inf, int pid)
int inf_update_suspends (struct inf *inf)
void inf_set_pid (struct inf *inf, pid_t pid)
void inf_validate_procs (struct inf *inf)
void inf_steal_exc_ports (struct inf *inf)
void inf_restore_exc_ports (struct inf *inf)
struct proc * inf_tid_to_proc (struct inf *inf, int tid)
void inf_set_threads_resume_sc (struct inf *inf, struct proc *run_thread, int run_others)
int inf_set_threads_resume_sc_for_signal_thread (struct inf *inf)
void inf_suspend (struct inf *inf)
void inf_resume (struct inf *inf)
void inf_set_step_thread (struct inf *inf, struct proc *proc)
void inf_detach (struct inf *inf)
void inf_attach (struct inf *inf, int pid)
void inf_signal (struct inf *inf, enum gdb_signal sig)
void inf_continue (struct inf *inf)
void proc_abort (struct proc *proc, int force)
struct proc * make_proc (struct inf *inf, mach_port_t port, int tid)
struct proc * _proc_free (struct proc *proc)
int proc_update_sc (struct proc *proc)
error_t proc_get_exception_port (struct proc *proc, mach_port_t *port)
error_t proc_set_exception_port (struct proc *proc, mach_port_t port)
static mach_port_t _proc_get_exc_port (struct proc *proc)
void proc_steal_exc_port (struct proc *proc, mach_port_t exc_port)
void proc_restore_exc_port (struct proc *proc)
int proc_trace (struct proc *proc, int set)
int __proc_pid (struct proc *proc)
thread_state_t proc_get_state (struct proc *proc, int will_modify)
static void inf_validate_procinfo (struct inf *inf)
static void inf_validate_task_sc (struct inf *inf)
void inf_set_traced (struct inf *inf, int on)
struct proc * inf_tid_to_thread (struct inf *inf, int tid)
struct proc * inf_port_to_thread (struct inf *inf, mach_port_t port)
int inf_update_procs (struct inf *inf)
static void inf_update_signal_thread (struct inf *inf)
static ptid_t gnu_wait (struct target_ops *ops, ptid_t ptid, struct target_waitstatus *status, int options)
error_t S_exception_raise_request (mach_port_t port, mach_port_t reply_port, thread_t thread_port, task_t task_port, int exception, int code, int subcode)
void inf_task_died_status (struct inf *inf)
error_t do_mach_notify_dead_name (mach_port_t notify, mach_port_t dead_port)
static error_t ill_rpc (char *fun)
error_t do_mach_notify_no_senders (mach_port_t notify, mach_port_mscount_t count)
error_t do_mach_notify_port_deleted (mach_port_t notify, mach_port_t name)
error_t do_mach_notify_msg_accepted (mach_port_t notify, mach_port_t name)
error_t do_mach_notify_port_destroyed (mach_port_t notify, mach_port_t name)
error_t do_mach_notify_send_once (mach_port_t notify)
error_t S_proc_wait_reply (mach_port_t reply, error_t err, int status, int sigcode, rusage_t rusage, pid_t pid)
error_t S_proc_setmsgport_reply (mach_port_t reply, error_t err, mach_port_t old_msg_port)
error_t S_proc_getmsgport_reply (mach_port_t reply, error_t err, mach_port_t msg_port)
error_t S_msg_sig_post_untraced_reply (mach_port_t reply, error_t err)
error_t S_msg_sig_post_reply (mach_port_t reply, error_t err)
static mach_port_msgcount_t port_msgs_queued (mach_port_t port)
static void gnu_resume (struct target_ops *ops, ptid_t ptid, int step, enum gdb_signal sig)
static void gnu_kill_inferior (struct target_ops *ops)
static void gnu_mourn_inferior (struct target_ops *ops)
static int inf_pick_first_thread (void)
static struct inf * cur_inf (void)
static void gnu_create_inferior (struct target_ops *ops, char *exec_file, char *allargs, char **env, int from_tty)
static void gnu_attach (struct target_ops *ops, char *args, int from_tty)
static void gnu_detach (struct target_ops *ops, char *args, int from_tty)
static void gnu_terminal_init_inferior (void)
static void gnu_stop (ptid_t ptid)
static int gnu_thread_alive (struct target_ops *ops, ptid_t ptid)
static int gnu_read_inferior (task_t task, CORE_ADDR addr, gdb_byte *myaddr, int length)
static int gnu_write_inferior (task_t task, CORE_ADDR addr, const gdb_byte *myaddr, int length)
static LONGEST gnu_xfer_memory (gdb_byte *readbuf, const gdb_byte *writebuf, CORE_ADDR memaddr, LONGEST len)
static LONGEST gnu_xfer_partial (struct target_ops *ops, enum target_object object, const char *annex, gdb_byte *readbuf, const gdb_byte *writebuf, ULONGEST offset, LONGEST len)
static int gnu_find_memory_regions (find_memory_region_ftype func, void *data)
char * proc_string (struct proc *proc)
static char * gnu_pid_to_str (struct target_ops *ops, ptid_t ptid)
struct target_ops * gnu_target (void)
static void set_thread_cmd (char *args, int from_tty)
static void show_thread_cmd (char *args, int from_tty)
static void set_thread_default_cmd (char *args, int from_tty)
static void show_thread_default_cmd (char *args, int from_tty)
static int parse_int_arg (char *args, char *cmd_prefix)
static int _parse_bool_arg (char *args, char *t_val, char *f_val, char *cmd_prefix)
static void check_empty (char *args, char *cmd_prefix)
static struct proc * cur_thread (void)
static struct inf * active_inf (void)
static void set_task_pause_cmd (char *args, int from_tty)
static void show_task_pause_cmd (char *args, int from_tty)
static void set_task_detach_sc_cmd (char *args, int from_tty)
static void show_task_detach_sc_cmd (char *args, int from_tty)
static void set_thread_default_pause_cmd (char *args, int from_tty)
static void show_thread_default_pause_cmd (char *args, int from_tty)
static void set_thread_default_run_cmd (char *args, int from_tty)
static void show_thread_default_run_cmd (char *args, int from_tty)
static void set_thread_default_detach_sc_cmd (char *args, int from_tty)
static void show_thread_default_detach_sc_cmd (char *args, int from_tty)
static void steal_exc_port (struct proc *proc, mach_port_t name)
static void set_task_exc_port_cmd (char *args, int from_tty)
static void set_stopped_cmd (char *args, int from_tty)
static void show_stopped_cmd (char *args, int from_tty)
static void set_sig_thread_cmd (char *args, int from_tty)
static void show_sig_thread_cmd (char *args, int from_tty)
static void set_signals_cmd (char *args, int from_tty)
static void show_signals_cmd (char *args, int from_tty)
static void set_exceptions_cmd (char *args, int from_tty)
static void show_exceptions_cmd (char *args, int from_tty)
static void set_task_cmd (char *args, int from_tty)
static void show_task_cmd (char *args, int from_tty)
static void set_noninvasive_cmd (char *args, int from_tty)
static void info_port_rights (char *args, mach_port_type_t only)
static void info_send_rights_cmd (char *args, int from_tty)
static void info_recv_rights_cmd (char *args, int from_tty)
static void info_port_sets_cmd (char *args, int from_tty)
static void info_dead_names_cmd (char *args, int from_tty)
static void info_port_rights_cmd (char *args, int from_tty)
static void add_task_commands (void)
static void set_thread_pause_cmd (char *args, int from_tty)
static void show_thread_pause_cmd (char *args, int from_tty)
static void set_thread_run_cmd (char *args, int from_tty)
static void show_thread_run_cmd (char *args, int from_tty)
static void set_thread_detach_sc_cmd (char *args, int from_tty)
static void show_thread_detach_sc_cmd (char *args, int from_tty)
static void set_thread_exc_port_cmd (char *args, int from_tty)
static void thread_takeover_sc_cmd (char *args, int from_tty)
static void add_thread_commands (void)
void _initialize_gnu_nat (void)
Variables
static process_t proc_server = MACH_PORT_NULL
int proc_wait_pid = 0
int proc_waits_pending = 0
int gnu_debug_flag = 0
static int next_thread_id = 1
struct inf * gnu_current_inf = 0
struct inf * waiting_inf
struct obstack region_obstack
static struct cmd_list_element * set_task_cmd_list = 0
static struct cmd_list_element * show_task_cmd_list = 0
struct cmd_list_element * thread_cmd_list
struct cmd_list_element * set_thread_cmd_list = NULL
struct cmd_list_element * show_thread_cmd_list = NULL
struct cmd_list_element * set_thread_default_cmd_list = NULL
struct cmd_list_element * show_thread_default_cmd_list = NULL
Define Documentation
#define CHK_GOTO_OUT (str, ret) do if (ret != KERN_SUCCESS) { errstr = #str; goto out; } while(0)
Definition at line 2303 of file gnu-nat.c.
Referenced by gnu_write_inferior().
#define inf_debug (_inf, msg, args...)
Value:
do { struct inf *__inf = (_inf); \
       debug ("{inf %d %s}: " msg, __inf->pid, \
       host_address_to_string (__inf) , ##args); } while (0)
Definition at line 112 of file gnu-nat.c.
Referenced by do_mach_notify_dead_name(), gnu_attach(), gnu_create_inferior(), gnu_mourn_inferior(), gnu_resume(), gnu_wait(), gnu_xfer_memory(), inf_attach(), inf_cleanup(), inf_clear_wait(), inf_continue(), inf_detach(), inf_restore_exc_ports(), inf_set_pid(), inf_set_step_thread(), inf_signal(), inf_startup(), inf_steal_exc_ports(), inf_update_suspends(), inf_validate_procs(), S_exception_raise_request(), and S_proc_wait_reply().
#define INF_MSGPORT_RPC (inf, rpc_expr)
Value:
HURD_MSGPORT_RPC (proc_getmsgport (proc_server, inf->pid, &msgport), \
                    (refport = inf->task->port, 0), 0, \
                    msgport ? (rpc_expr) : EIEIO)
Definition at line 131 of file gnu-nat.c.
Referenced by inf_signal().
#define INF_RESUME_MSGPORT_RPC (inf, rpc_expr)
Value:
(inf_set_threads_resume_sc_for_signal_thread (inf) \
   ? ({ error_t __e; \
        inf_resume (inf); \
        __e = INF_MSGPORT_RPC (inf, rpc_expr); \
        inf_suspend (inf); \
        __e; }) \
   : EIEIO)
Definition at line 139 of file gnu-nat.c.
Referenced by inf_set_traced(), and inf_signal().
#define NAME gdb_signal_to_name (sig)
Referenced by c_print_token(), classify_inner_name(), classify_name(), classify_packaged_name(), inf_signal(), lex_one_token(), and yylex().
#define parse_bool_arg (args, cmd_prefix) _parse_bool_arg (args, "on", "off", cmd_prefix)
Definition at line 2743 of file gnu-nat.c.
Referenced by set_exceptions_cmd(), set_noninvasive_cmd(), set_signals_cmd(), set_task_pause_cmd(), set_thread_default_pause_cmd(), set_thread_default_run_cmd(), set_thread_pause_cmd(), and set_thread_run_cmd().
Function Documentation
int __proc_pid (struct proc * proc)
Definition at line 247 of file gnu-nat.c.
References proc::inf, and inf::pid.
void _initialize_gnu_nat (void)
Definition at line 3443 of file gnu-nat.c.
References _, add_setshow_boolean_cmd(), add_task_commands(), add_thread_commands(), class_maintenance, gnu_debug_flag, proc_server, setdebuglist, and showdebuglist.
static int _parse_bool_arg (char * args, char * t_val, char * f_val, char * cmd_prefix) [static]
Definition at line 2731 of file gnu-nat.c.
References _, and error().
Referenced by set_stopped_cmd().
struct proc * _proc_free (struct proc * proc) [read]
Definition at line 607 of file gnu-nat.c.
References proc::cur_sc, proc::exc_port, proc::inf, inf_clear_wait(), inf_set_step_thread(), proc::next, proc::port, proc_debug, proc_restore_exc_port(), proc_update_sc(), proc::sc, inf::signal_thread, inf::step_thread, inf_wait::thread, inf::wait, and xfree().
Referenced by inf_set_pid(), and inf_validate_procs().
static mach_port_t _proc_get_exc_port (struct proc * proc) [static]
Definition at line 417 of file gnu-nat.c.
References proc::exc_port, proc_get_exception_port(), and proc::saved_exc_port.
Referenced by proc_restore_exc_port(), and proc_steal_exc_port().
static struct inf* active_inf (void) [static, read]
Definition at line 2767 of file gnu-nat.c.
References _, cur_inf(), error(), arm-linux::inf, and inf::task.
Referenced by info_port_rights(), show_sig_thread_cmd(), and show_stopped_cmd().
static void add_task_commands (void) [static]
Definition at line 3139 of file gnu-nat.c.
References _, add_alias_cmd(), add_cmd(), add_info_alias(), add_prefix_cmd(), class_info, class_run, info_dead_names_cmd(), info_port_rights_cmd(), info_port_sets_cmd(), info_recv_rights_cmd(), info_send_rights_cmd(), infolist, no_class, set_exceptions_cmd(), set_noninvasive_cmd(), set_sig_thread_cmd(), set_signals_cmd(), set_stopped_cmd(), set_task_cmd(), set_task_detach_sc_cmd(), set_task_exc_port_cmd(), set_task_pause_cmd(), set_thread_default_detach_sc_cmd(), set_thread_default_pause_cmd(), set_thread_default_run_cmd(), setlist, show_exceptions_cmd(), show_sig_thread_cmd(), show_signals_cmd(), show_stopped_cmd(), show_task_cmd(), show_task_detach_sc_cmd(), show_task_pause_cmd(), show_thread_default_detach_sc_cmd(), show_thread_default_pause_cmd(), show_thread_default_run_cmd(), and showlist.
Referenced by _initialize_gnu_nat().
static void add_thread_commands (void) [static]
Definition at line 3378 of file gnu-nat.c.
References _, add_alias_cmd(), add_cmd(), add_prefix_cmd(), class_run, no_class, set_thread_cmd(), set_thread_default_cmd(), set_thread_detach_sc_cmd(), set_thread_exc_port_cmd(), set_thread_pause_cmd(), set_thread_run_cmd(), setlist, show_thread_cmd(), show_thread_default_cmd(), show_thread_detach_sc_cmd(), show_thread_pause_cmd(), show_thread_run_cmd(), showlist, and thread_takeover_sc_cmd().
Referenced by _initialize_gnu_nat().
static void check_empty (char * args, char * cmd_prefix) [static]
Definition at line 2747 of file gnu-nat.c.
References _, and error().
Referenced by show_exceptions_cmd(), show_sig_thread_cmd(), show_signals_cmd(), show_stopped_cmd(), show_task_cmd(), show_task_detach_sc_cmd(), show_task_pause_cmd(), show_thread_default_detach_sc_cmd(), show_thread_default_pause_cmd(), show_thread_default_run_cmd(), show_thread_detach_sc_cmd(), show_thread_pause_cmd(), and show_thread_run_cmd().
static struct inf* cur_inf (void) [static, read]
Definition at line 2092 of file gnu-nat.c.
References gnu_current_inf, and make_inf().
Referenced by active_inf(), cur_thread(), gnu_attach(), gnu_create_inferior(), set_exceptions_cmd(), set_sig_thread_cmd(), set_signals_cmd(), set_stopped_cmd(), set_task_detach_sc_cmd(), set_task_exc_port_cmd(), set_task_pause_cmd(), set_thread_default_detach_sc_cmd(), set_thread_default_pause_cmd(), set_thread_default_run_cmd(), show_exceptions_cmd(), show_signals_cmd(), show_task_cmd(), show_task_detach_sc_cmd(), show_task_pause_cmd(), show_thread_default_detach_sc_cmd(), show_thread_default_pause_cmd(), and show_thread_default_run_cmd().
static struct proc* cur_thread (void) [static, read]
Definition at line 2755 of file gnu-nat.c.
References _, cur_inf(), error(), inf_tid_to_thread(), inferior_ptid, and ptid_get_lwp().
Referenced by set_thread_detach_sc_cmd(), set_thread_exc_port_cmd(), set_thread_pause_cmd(), set_thread_run_cmd(), show_thread_detach_sc_cmd(), show_thread_pause_cmd(), show_thread_run_cmd(), and thread_takeover_sc_cmd().
error_t do_mach_notify_dead_name (mach_port_t notify, mach_port_t dead_port)
Definition at line 1757 of file gnu-nat.c.
References proc::dead, inf_debug, inf_port_to_thread(), inf_task_died_status(), inf::pid, proc::port, proc_debug, proc_wait_pid, inf_wait::suppress, inf::task, inf::threads_up_to_date, inf::wait, and waiting_inf.
error_t do_mach_notify_msg_accepted (mach_port_t notify, mach_port_t name)
Definition at line 1818 of file gnu-nat.c.
References ill_rpc().
error_t do_mach_notify_no_senders (mach_port_t notify, mach_port_mscount_t count)
Definition at line 1806 of file gnu-nat.c.
References ill_rpc().
error_t do_mach_notify_port_deleted (mach_port_t notify, mach_port_t name)
Definition at line 1812 of file gnu-nat.c.
References ill_rpc().
error_t do_mach_notify_port_destroyed (mach_port_t notify, mach_port_t name)
Definition at line 1824 of file gnu-nat.c.
References ill_rpc().
error_t do_mach_notify_send_once (mach_port_t notify)
Definition at line 1830 of file gnu-nat.c.
References ill_rpc().
static void gnu_attach (struct target_ops * ops, char * args, int from_tty) [static]
Definition at line 2157 of file gnu-nat.c.
References _, inferior::attach_flag, cur_inf(), current_inferior(), error(), gdb_flush(), gdb_stdout, get_exec_file(), inf_attach(), inf_debug, inf_pick_first_thread(), inf_set_traced(), inf_update_procs(), inf_update_signal_thread(), inf_validate_procinfo(), inferior_appeared(), inferior_ptid, parse_pid_to_attach(), inf::pid, printf_unfiltered(), ptid_build(), push_target(), target_terminal_init, and inf::want_signals.
Referenced by gnu_target().
static void gnu_create_inferior (struct target_ops * ops, char * exec_file, char * allargs, char ** env, int from_tty) [static]
Definition at line 2100 of file gnu-nat.c.
References _, cur_inf(), error(), fork_inferior(), inf_attach(), inf_debug, inf_pick_first_thread(), inf_restore_exc_ports(), inf_resume(), inf_set_traced(), inf_steal_exc_ports(), inf_update_signal_thread(), inf_validate_procinfo(), inferior_ptid, inf::nomsg, inf::pending_execs, inf::pid, ptid_build(), ptrace(), push_target(), startup_inferior(), thread_change_ptid(), inf::traced, inf::want_exceptions, and inf::want_signals.
Referenced by gnu_target().
static void gnu_detach (struct target_ops * ops, char * args, int from_tty) [static]
Definition at line 2221 of file gnu-nat.c.
References detach_inferior(), gdb_flush(), gdb_stdout, get_exec_file(), inf_detach(), inferior_ptid, null_ptid, inf::pid, inferior::pid, printf_unfiltered(), and unpush_target().
Referenced by gnu_target().
static int gnu_find_memory_regions (find_memory_region_ftype func, void * data) [static]
Definition at line 2530 of file gnu-nat.c.
References _, offset, proc::port, vm_region_list::protection, inf::task, VM_MIN_ADDRESS, and warning().
Referenced by gnu_target().
static void gnu_kill_inferior (struct target_ops * ops) [static]
Definition at line 2053 of file gnu-nat.c.
References inf_set_pid(), proc::port, proc_debug, target_mourn_inferior(), and inf::task.
Referenced by gnu_target().
static void gnu_mourn_inferior (struct target_ops * ops) [static]
Definition at line 2068 of file gnu-nat.c.
References generic_mourn_inferior(), inf_debug, inf_detach(), and unpush_target().
Referenced by gnu_target().
static char* gnu_pid_to_str (struct target_ops * ops, ptid_t ptid) [static]
Definition at line 2623 of file gnu-nat.c.
References gnu_current_inf, inf_tid_to_thread(), proc_string(), ptid_get_lwp(), and xsnprintf().
Referenced by gnu_target().
static int gnu_read_inferior (task_t task, CORE_ADDR addr, gdb_byte * myaddr, int length) [static]
Definition at line 2273 of file gnu-nat.c.
References _, safe_strerror(), and warning().
Referenced by gnu_xfer_memory().
static void gnu_resume (struct target_ops * ops, ptid_t ptid, int step, enum gdb_signal sig) [static]
Definition at line 1976 of file gnu-nat.c.
References _, error(), inf::event_port, inf_wait::exc, gdb_signal_to_name(), gnu_current_inf, inf_continue(), inf_debug, inf_resume(), inf_set_step_thread(), inf_set_threads_resume_sc(), inf_signal(), inf_tid_to_thread(), inf_update_procs(), inf_validate_procinfo(), inferior_ptid, minus_one_ptid, inf::nomsg, port_msgs_queued(), proc_abort(), proc_string(), ptid_equal(), ptid_get_lwp(), ptid_get_pid(), exc_state::reply, target_waitstatus::sig, inf_wait::status, inf::step_thread, inf::stopped, target_pid_to_str(), inf_wait::thread, target_waitstatus::value, inf::wait, and warning().
Referenced by gnu_target().
static void gnu_stop (ptid_t ptid) [static]
Definition at line 2255 of file gnu-nat.c.
References _, and error().
Referenced by gnu_target().
struct target_ops* gnu_target (void) [read]
Definition at line 2645 of file gnu-nat.c.
References gnu_attach(), gnu_create_inferior(), gnu_detach(), gnu_find_memory_regions(), gnu_kill_inferior(), gnu_mourn_inferior(), gnu_pid_to_str(), gnu_resume(), gnu_stop(), gnu_terminal_init_inferior(), gnu_thread_alive(), gnu_wait(), gnu_xfer_partial(), inf_child_target(), target_ops::to_attach, target_ops::to_attach_no_wait, target_ops::to_create_inferior, target_ops::to_detach, target_ops::to_doc, target_ops::to_find_memory_regions, target_ops::to_kill, target_ops::to_longname, target_ops::to_mourn_inferior, target_ops::to_pid_to_str, target_ops::to_resume, target_ops::to_shortname, target_ops::to_stop, target_ops::to_terminal_init, target_ops::to_thread_alive, target_ops::to_wait, and target_ops::to_xfer_partial.
Referenced by _initialize_i386gnu_nat().
static void gnu_terminal_init_inferior (void) [static]
Definition at line 2248 of file gnu-nat.c.
References gdb_assert, inf::pid, and terminal_init_inferior_with_pgrp().
Referenced by gnu_target().
static int gnu_thread_alive (struct target_ops * ops, ptid_t ptid) [static]
Definition at line 2261 of file gnu-nat.c.
References inf_tid_to_thread(), inf_update_procs(), and ptid_get_lwp().
Referenced by gnu_target().
static ptid_t gnu_wait (struct target_ops * ops, ptid_t ptid, struct target_waitstatus * status, int options) [static]
Definition at line 1446 of file gnu-nat.c.
References _, proc::dead, error(), inf::event_port, exc_server(), gdb_assert, gnu_current_inf, arm-linux::inf, inf_clear_wait(), inf_debug, inf_resume(), inf_set_pid(), inf_suspend(), inf_tid_to_thread(), inf_update_procs(), inf_update_suspends(), inf_validate_procs(), inf_validate_task_sc(), inferior_ptid, target_waitstatus::integer, target_waitstatus::kind, memcpy(), minus_one_ptid, inf::no_wait, proc::pause_sc, inf::pause_sc, inf::pending_execs, inf::pid, proc::port, proc_server, proc_wait_pid, proc_waits_pending, prune_threads(), ptid_build(), ptid_equal(), ptid_get_lwp(), safe_strerror(), proc::sc, target_waitstatus::sig, inf_wait::status, inf_wait::suppress, target_pid_to_str(), TARGET_WAITKIND_EXITED, TARGET_WAITKIND_LOADED, TARGET_WAITKIND_SIGNALLED, TARGET_WAITKIND_SPURIOUS, TARGET_WAITKIND_STOPPED, inf::task, inf_wait::thread, inf::threads, proc::tid, type, target_waitstatus::value, inf::wait, and warning().
Referenced by gnu_target().
static int gnu_write_inferior (task_t task, CORE_ADDR addr, const gdb_byte * myaddr, int length) [static]
Definition at line 2319 of file gnu-nat.c.
References _, CHK_GOTO_OUT, vm_region_list::length, vm_region_list::next, offset, vm_region_list::protection, region_obstack, scan(), vm_region_list::start, and warning().
Referenced by gnu_xfer_memory().
static LONGEST gnu_xfer_memory (gdb_byte * readbuf, const gdb_byte * writebuf, CORE_ADDR memaddr, LONGEST len) [static]
Definition at line 2480 of file gnu-nat.c.
References gnu_read_inferior(), gnu_write_inferior(), host_address_to_string(), inf_debug, paddress(), plongest(), proc::port, target_gdbarch(), TARGET_XFER_E_IO, and inf::task.
Referenced by gnu_xfer_partial().
static LONGEST gnu_xfer_partial (struct target_ops * ops, enum target_object object, const char * annex, gdb_byte * readbuf, const gdb_byte * writebuf, ULONGEST offset, LONGEST len) [static]
Definition at line 2514 of file gnu-nat.c.
References gnu_xfer_memory(), and TARGET_OBJECT_MEMORY.
Referenced by gnu_target().
static error_t ill_rpc (char * fun) [static]
Definition at line 1799 of file gnu-nat.c.
References _, and warning().
Referenced by do_mach_notify_msg_accepted(), do_mach_notify_no_senders(), do_mach_notify_port_deleted(), do_mach_notify_port_destroyed(), do_mach_notify_send_once(), S_msg_sig_post_reply(), S_proc_getmsgport_reply(), and S_proc_setmsgport_reply().
void inf_attach (struct inf * inf, int pid)
Definition at line 1277 of file gnu-nat.c.
References inf_debug, inf_detach(), inf_startup(), and inf::pid.
Referenced by gnu_attach(), and gnu_create_inferior().
void inf_cleanup (struct inf * inf)
Definition at line 696 of file gnu-nat.c.
References inf::event_port, inf_clear_wait(), inf_debug, inf_set_pid(), inf::no_wait, inf::nomsg, inf::pending_execs, inf::pid, inf::running, inf::stopped, and inf::traced.
Referenced by inf_detach(), and inf_startup().
void inf_clear_wait (struct inf * inf)
Definition at line 676 of file gnu-nat.c.
References inf_wait::exc, exc_state::handler, inf_debug, target_waitstatus::kind, exc_state::reply, inf_wait::status, inf_wait::suppress, TARGET_WAITKIND_SPURIOUS, inf_wait::thread, and inf::wait.
Referenced by _proc_free(), gnu_wait(), inf_cleanup(), and inf_detach().
void inf_continue (struct inf * inf)
Definition at line 1411 of file gnu-nat.c.
References _, inf_debug, proc::next, inf::pid, proc::port, proc_server, safe_strerror(), inf::stopped, inf::threads, and warning().
Referenced by gnu_resume(), and inf_detach().
void inf_detach (struct inf * inf)
Definition at line 1235 of file gnu-nat.c.
References proc::detach_sc, inf::detach_sc, inf_cleanup(), inf_clear_wait(), inf_continue(), inf_debug, inf_set_step_thread(), inf_set_traced(), inf_signal(), inf_update_suspends(), inf_validate_procinfo(), proc::next, inf::nomsg, proc_restore_exc_port(), proc::sc, inf::stopped, inf::task, and inf::threads.
Referenced by gnu_detach(), gnu_mourn_inferior(), and inf_attach().
static int inf_pick_first_thread (void) [static]
Definition at line 2081 of file gnu-nat.c.
References next_thread_id, inf::task, inf::threads, and proc::tid.
Referenced by gnu_attach(), and gnu_create_inferior().
struct proc* inf_port_to_thread (struct inf * inf, mach_port_t port) [read]
Definition at line 979 of file gnu-nat.c.
References proc::next, proc::port, and inf::threads.
Referenced by do_mach_notify_dead_name(), and S_exception_raise_request().
void inf_restore_exc_ports (struct inf * inf)
Definition at line 1305 of file gnu-nat.c.
References inf_debug, inf_set_step_thread(), proc::next, proc_restore_exc_port(), inf::task, and inf::threads.
Referenced by gnu_create_inferior().
void inf_resume (struct inf * inf)
Definition at line 1142 of file gnu-nat.c.
References inf_update_procs(), inf_update_suspends(), inf_validate_task_sc(), proc::next, inf::pending_execs, proc::resume_sc, proc::sc, inf::task, and inf::threads.
Referenced by gnu_create_inferior(), gnu_resume(), and gnu_wait().
void inf_set_pid (struct inf * inf, pid_t pid)
Definition at line 742 of file gnu-nat.c.
References _, _proc_free(), proc::cur_sc, error(), inf_debug, inf_validate_procs(), make_proc(), inf::pause_sc, inf::pid, proc::port, proc_server, PROC_TID_TASK, safe_strerror(), proc::sc, inf::task, and inf::threads_up_to_date.
Referenced by gnu_kill_inferior(), gnu_wait(), inf_cleanup(), and inf_startup().
void inf_set_step_thread (struct inf * inf, struct proc * proc)
Definition at line 1187 of file gnu-nat.c.
References gdb_assert, inf_debug, inf::pid, proc::port, proc_is_thread, proc_trace(), inf::step_thread, and proc::tid.
Referenced by _proc_free(), gnu_resume(), inf_detach(), inf_restore_exc_ports(), and inf_steal_exc_ports().
void inf_set_threads_resume_sc (struct inf * inf, struct proc * run_thread, int run_others)
Definition at line 1123 of file gnu-nat.c.
References inf_update_procs(), proc::next, proc::pause_sc, proc::resume_sc, proc::run_sc, and inf::threads.
Referenced by gnu_resume(), and inf_set_threads_resume_sc_for_signal_thread().
int inf_set_threads_resume_sc_for_signal_thread (struct inf * inf)
Definition at line 1213 of file gnu-nat.c.
References inf_set_threads_resume_sc(), and inf::signal_thread.
void inf_set_traced (struct inf * inf, int on)
Definition at line 878 of file gnu-nat.c.
References _, proc::dead, INF_RESUME_MSGPORT_RPC, inf::pid, safe_strerror(), inf::task, inf::traced, and warning().
Referenced by gnu_attach(), gnu_create_inferior(), inf_detach(), S_proc_wait_reply(), and set_signals_cmd().
void inf_signal (struct inf * inf, enum gdb_signal sig)
Definition at line 1323 of file gnu-nat.c.
References _, proc::aborted, exc_state::code, error(), inf::event_port, inf_wait::exc, exc_state::exception, gdb_signal_to_host(), exc_state::handler, inf_debug, INF_MSGPORT_RPC, INF_RESUME_MSGPORT_RPC, target_waitstatus::kind, NAME, proc::port, exc_state::reply, safe_strerror(), target_waitstatus::sig, inf_wait::status, inf::stopped, exc_state::subcode, TARGET_WAITKIND_STOPPED, inf::task, inf_wait::thread, target_waitstatus::value, inf::wait, and warning().
Referenced by gnu_resume(), and inf_detach().
void inf_startup (struct inf * inf, int pid)
Definition at line 719 of file gnu-nat.c.
References _, error(), inf::event_port, inf_cleanup(), inf_debug, inf_set_pid(), and safe_strerror().
Referenced by inf_attach().
void inf_steal_exc_ports (struct inf * inf)
Definition at line 1290 of file gnu-nat.c.
References inf::event_port, inf_debug, inf_set_step_thread(), proc::next, proc_steal_exc_port(), inf::task, and inf::threads.
Referenced by gnu_create_inferior().
void inf_suspend (struct inf * inf)
Definition at line 1167 of file gnu-nat.c.
References inf_update_procs(), inf_update_suspends(), proc::next, proc::pause_sc, inf::pause_sc, proc::sc, inf::task, and inf::threads.
Referenced by gnu_wait(), set_task_pause_cmd(), and set_thread_pause_cmd().
void inf_task_died_status (struct inf * inf)
Definition at line 1747 of file gnu-nat.c.
References _, target_waitstatus::kind, inf::pid, target_waitstatus::sig, inf_wait::status, TARGET_WAITKIND_SIGNALLED, target_waitstatus::value, inf::wait, and warning().
Referenced by do_mach_notify_dead_name(), and S_proc_wait_reply().
struct proc* inf_tid_to_proc (struct inf * inf, int tid) [read]
struct proc* inf_tid_to_thread (struct inf * inf, int tid) [read]
Definition at line 965 of file gnu-nat.c.
References proc::next, inf::threads, and proc::tid.
Referenced by cur_thread(), gnu_fetch_registers(), gnu_pid_to_str(), gnu_resume(), gnu_store_registers(), gnu_thread_alive(), gnu_wait(), and set_sig_thread_cmd().
int inf_update_procs (struct inf * inf)
Definition at line 1110 of file gnu-nat.c.
References inf_validate_procs(), inf::task, and inf::threads_up_to_date.
Referenced by gnu_attach(), gnu_fetch_registers(), gnu_resume(), gnu_store_registers(), gnu_thread_alive(), gnu_wait(), inf_resume(), inf_set_threads_resume_sc(), inf_suspend(), and S_exception_raise_request().
static void inf_update_signal_thread (struct inf * inf) [static]
Definition at line 1225 of file gnu-nat.c.
References proc::next, inf::signal_thread, and inf::threads.
Referenced by gnu_attach(), and gnu_create_inferior().
int inf_update_suspends (struct inf * inf)
Definition at line 914 of file gnu-nat.c.
References proc::cur_sc, inf_debug, proc::next, inf::pending_execs, proc_update_sc(), inf::running, proc::sc, inf::task, inf::threads, and inf::threads_up_to_date.
Referenced by gnu_wait(), inf_detach(), inf_resume(), inf_suspend(), and proc_abort().
static void inf_validate_procinfo (struct inf * inf) [static]
Definition at line 795 of file gnu-nat.c.
References inf::nomsg, inf::pid, proc_server, inf::stopped, and inf::traced.
Referenced by gnu_attach(), gnu_create_inferior(), gnu_resume(), and inf_detach().
void inf_validate_procs (struct inf * inf)
Definition at line 994 of file gnu-nat.c.
References _proc_free(), add_thread(), add_thread_silent(), proc::dead, inf_debug, inferior_ptid, make_proc(), memset(), proc::next, next_thread_id, inf::pending_execs, inf::pid, pid_to_ptid(), proc::port, proc_debug, ptid_build(), ptid_equal(), inf::running, inf::task, thread_change_ptid(), inf::threads, inf::threads_up_to_date, and proc::tid.
Referenced by gnu_wait(), inf_set_pid(), and inf_update_procs().
static void inf_validate_task_sc (struct inf * inf) [static]
Definition at line 821 of file gnu-nat.c.
References _, proc::cur_sc, proc::dead, error(), inf::pid, proc_server, query(), target_terminal_inferior(), target_terminal_ours, and inf::task.
Referenced by gnu_wait(), and inf_resume().
static void info_dead_names_cmd (char * args, int from_tty) [static]
Definition at line 3126 of file gnu-nat.c.
References info_port_rights().
Referenced by add_task_commands().
static void info_port_rights (char * args, mach_port_type_t only) [static]
Definition at line 3074 of file gnu-nat.c.
References _, active_inf(), error(), parse_to_comma_and_eval(), proc::port, safe_strerror(), inf::task, value_as_long(), value_free_to_mark(), and value_mark().
Referenced by info_dead_names_cmd(), info_port_rights_cmd(), info_port_sets_cmd(), info_recv_rights_cmd(), and info_send_rights_cmd().
static void info_port_rights_cmd (char * args, int from_tty) [static]
Definition at line 3132 of file gnu-nat.c.
References info_port_rights().
Referenced by add_task_commands().
static void info_port_sets_cmd (char * args, int from_tty) [static]
Definition at line 3120 of file gnu-nat.c.
References info_port_rights().
Referenced by add_task_commands().
static void info_recv_rights_cmd (char * args, int from_tty) [static]
Definition at line 3114 of file gnu-nat.c.
References info_port_rights().
Referenced by add_task_commands().
static void info_send_rights_cmd (char * args, int from_tty) [static]
Definition at line 3108 of file gnu-nat.c.
References info_port_rights().
Referenced by add_task_commands().
struct inf * make_inf (void) [read]
Definition at line 642 of file gnu-nat.c.
References inf::default_thread_detach_sc, inf::default_thread_pause_sc, inf::default_thread_run_sc, inf::detach_sc, inf::event_port, inf_wait::exc, exc_state::handler, arm-linux::inf, target_waitstatus::kind, inf::no_wait, inf::nomsg, inf::pause_sc, inf::pending_execs, inf::pid, exc_state::reply, inf::running, inf::signal_thread, inf_wait::status, inf::step_thread, inf::stopped, TARGET_WAITKIND_SPURIOUS, inf::task, inf_wait::thread, inf::threads, inf::threads_up_to_date, inf::traced, inf::wait, inf::want_exceptions, inf::want_signals, and xmalloc().
Referenced by cur_inf().
struct proc * make_proc (struct inf * inf, mach_port_t port, int tid) [read]
Definition at line 543 of file gnu-nat.c.
References _, proc::aborted, proc::cur_sc, proc::dead, inf::default_thread_detach_sc, inf::default_thread_pause_sc, inf::default_thread_run_sc, proc::detach_sc, inf::event_port, proc::exc_port, arm-linux::inf, proc::inf, proc::next, proc::pause_sc, proc::port, proc_debug, proc_is_task, proc_steal_exc_port(), proc::resume_sc, proc::run_sc, safe_strerror(), proc::saved_exc_port, proc::sc, proc::state_changed, proc::state_valid, proc::tid, inf::want_exceptions, warning(), and xmalloc().
Referenced by inf_set_pid(), and inf_validate_procs().
static int parse_int_arg (char * args, char * cmd_prefix) [static]
Definition at line 2716 of file gnu-nat.c.
References _, and error().
Referenced by set_task_detach_sc_cmd(), set_thread_default_detach_sc_cmd(), and set_thread_detach_sc_cmd().
static mach_port_msgcount_t port_msgs_queued (mach_port_t port) [static]
Definition at line 1946 of file gnu-nat.c.
Referenced by gnu_resume().
void proc_abort (struct proc * proc, int force)
Definition at line 322 of file gnu-nat.c.
References _, proc::aborted, proc::cur_sc, inf_wait::exc, gdb_assert, proc::inf, inf_update_suspends(), proc::port, proc_debug, proc_is_thread, proc_string(), exc_state::reply, inf::running, proc::sc, inf::task, inf_wait::thread, inf::wait, and warning().
Referenced by gnu_resume(), and proc_get_state().
error_t proc_get_exception_port (struct proc * proc, mach_port_t * port)
Definition at line 396 of file gnu-nat.c.
References proc::port, and proc_is_task.
Referenced by _proc_get_exc_port().
thread_state_t proc_get_state (struct proc * proc, int will_modify)
Definition at line 359 of file gnu-nat.c.
References proc::aborted, proc::port, proc_abort(), proc_debug, proc::state, proc::state_changed, proc::state_valid, THREAD_STATE_FLAVOR, and THREAD_STATE_SIZE.
Referenced by gnu_fetch_registers(), gnu_store_registers(), and proc_trace().
void proc_restore_exc_port (struct proc * proc)
Definition at line 483 of file gnu-nat.c.
References _, _proc_get_exc_port(), proc::exc_port, proc_debug, proc_set_exception_port(), proc_string(), safe_strerror(), proc::saved_exc_port, and warning().
Referenced by _proc_free(), inf_detach(), and inf_restore_exc_ports().
error_t proc_set_exception_port (struct proc * proc, mach_port_t port)
Definition at line 406 of file gnu-nat.c.
References proc::port, proc_debug, and proc_is_task.
Referenced by proc_restore_exc_port(), proc_steal_exc_port(), and steal_exc_port().
void proc_steal_exc_port (struct proc * proc, mach_port_t exc_port)
Definition at line 440 of file gnu-nat.c.
References _, _proc_get_exc_port(), proc::exc_port, proc_debug, proc_set_exception_port(), proc_string(), safe_strerror(), proc::saved_exc_port, and warning().
Referenced by inf_steal_exc_ports(), make_proc(), and proc_trace().
char* proc_string (struct proc * proc)
Definition at line 2610 of file gnu-nat.c.
References proc::inf, inf::pid, proc_is_task, proc::tid, and xsnprintf().
Referenced by fetch_fpregs(), gnu_fetch_registers(), gnu_pid_to_str(), gnu_resume(), gnu_store_registers(), proc_abort(), proc_restore_exc_port(), proc_steal_exc_port(), show_sig_thread_cmd(), show_thread_detach_sc_cmd(), show_thread_pause_cmd(), show_thread_run_cmd(), steal_exc_port(), and store_fpregs().
int proc_trace (struct proc * proc, int set)
Definition at line 513 of file gnu-nat.c.
References inf::event_port, proc::exc_port, proc::inf, proc_debug, proc_get_state(), proc_steal_exc_port(), THREAD_STATE_CLEAR_TRACED, and THREAD_STATE_SET_TRACED.
Referenced by inf_set_step_thread().
int proc_update_sc (struct proc * proc)
Definition at line 256 of file gnu-nat.c.
References proc::aborted, proc::cur_sc, proc::fetched_regs, gdb_assert, proc::port, proc_debug, proc_is_task, proc_is_thread, safe_strerror(), proc::sc, proc::state, proc::state_changed, proc::state_valid, THREAD_STATE_FLAVOR, and THREAD_STATE_SIZE.
Referenced by _proc_free(), and inf_update_suspends().
error_t S_exception_raise_request (mach_port_t port, mach_port_t reply_port, thread_t thread_port, task_t task_port, int exception, int code, int subcode)
Definition at line 1660 of file gnu-nat.c.
References proc::aborted, exc_state::code, code, inf_wait::exc, proc::exc_port, exc_state::exception, gdb_assert, gdb_signal_from_host(), exc_state::handler, inf_debug, inf_port_to_thread(), inf_update_procs(), target_waitstatus::kind, exc_state::reply, proc::saved_exc_port, target_waitstatus::sig, inf_wait::status, exc_state::subcode, inf_wait::suppress, TARGET_WAITKIND_STOPPED, inf::task, inf_wait::thread, target_waitstatus::value, inf::wait, and waiting_inf.
error_t S_msg_sig_post_reply (mach_port_t reply, error_t err)
Definition at line 1938 of file gnu-nat.c.
References ill_rpc().
error_t S_msg_sig_post_untraced_reply (mach_port_t reply, error_t err)
Definition at line 1908 of file gnu-nat.c.
References _, target_waitstatus::kind, safe_strerror(), target_waitstatus::sig, inf_wait::status, inf::stopped, inf_wait::suppress, TARGET_WAITKIND_STOPPED, target_waitstatus::value, inf::wait, waiting_inf, and warning().
error_t S_proc_getmsgport_reply (mach_port_t reply, error_t err, mach_port_t msg_port)
Definition at line 1899 of file gnu-nat.c.
References ill_rpc().
error_t S_proc_setmsgport_reply (mach_port_t reply, error_t err, mach_port_t old_msg_port)
Definition at line 1892 of file gnu-nat.c.
References ill_rpc().
error_t S_proc_wait_reply (mach_port_t reply, error_t err, int status, int sigcode, rusage_t rusage, pid_t pid)
Definition at line 1839 of file gnu-nat.c.
References _, inf_debug, inf_set_traced(), inf_task_died_status(), target_waitstatus::kind, inf::no_wait, inf::pid, proc::port, proc_wait_pid, proc_waits_pending, safe_strerror(), inf_wait::status, inf::stopped, store_waitstatus(), inf_wait::suppress, TARGET_WAITKIND_STOPPED, inf::task, inf::wait, waiting_inf, and warning().
static void set_exceptions_cmd (char * args, int from_tty) [static]
Definition at line 3001 of file gnu-nat.c.
References cur_inf(), parse_bool_arg, inf::task, and inf::want_exceptions.
Referenced by add_task_commands(), and set_noninvasive_cmd().
static void set_noninvasive_cmd (char * args, int from_tty) [static]
Definition at line 3062 of file gnu-nat.c.
References parse_bool_arg, set_exceptions_cmd(), set_signals_cmd(), and set_task_pause_cmd().
Referenced by add_task_commands().
static void set_sig_thread_cmd (char * args, int from_tty) [static]
Definition at line 2940 of file gnu-nat.c.
References _, cur_inf(), error(), inf_tid_to_thread(), minus_one_ptid, ptid_equal(), ptid_get_lwp(), inf::signal_thread, and thread_id_to_pid().
Referenced by add_task_commands().
static void set_signals_cmd (char * args, int from_tty) [static]
Definition at line 2977 of file gnu-nat.c.
References cur_inf(), inf_set_traced(), parse_bool_arg, inf::task, inf::traced, and inf::want_signals.
Referenced by add_task_commands(), and set_noninvasive_cmd().
static void set_stopped_cmd (char * args, int from_tty) [static]
Definition at line 2924 of file gnu-nat.c.
References _parse_bool_arg(), cur_inf(), and inf::stopped.
Referenced by add_task_commands().
static void set_task_cmd (char * args, int from_tty) [static]
Definition at line 3027 of file gnu-nat.c.
References printf_unfiltered().
Referenced by add_task_commands().
static void set_task_detach_sc_cmd (char * args, int from_tty) [static]
Definition at line 2804 of file gnu-nat.c.
References cur_inf(), inf::detach_sc, and parse_int_arg().
Referenced by add_task_commands().
static void set_task_exc_port_cmd (char * args, int from_tty) [static]
Definition at line 2914 of file gnu-nat.c.
References _, cur_inf(), error(), parse_and_eval_address(), steal_exc_port(), and inf::task.
Referenced by add_task_commands().
static void set_task_pause_cmd (char * args, int from_tty) [static]
Definition at line 2778 of file gnu-nat.c.
References cur_inf(), inf_suspend(), parse_bool_arg, and inf::pause_sc.
Referenced by add_task_commands(), and set_noninvasive_cmd().
static void set_thread_cmd (char * args, int from_tty) [static]
Definition at line 2688 of file gnu-nat.c.
References printf_unfiltered().
Referenced by add_thread_commands().
static void set_thread_default_cmd (char * args, int from_tty) [static]
Definition at line 2702 of file gnu-nat.c.
References printf_unfiltered().
Referenced by add_thread_commands().
static void set_thread_default_detach_sc_cmd (char * args, int from_tty) [static]
Definition at line 2861 of file gnu-nat.c.
References cur_inf(), inf::default_thread_detach_sc, and parse_int_arg().
Referenced by add_task_commands().
static void set_thread_default_pause_cmd (char * args, int from_tty) [static]
Definition at line 2821 of file gnu-nat.c.
References cur_inf(), inf::default_thread_pause_sc, and parse_bool_arg.
Referenced by add_task_commands().
static void set_thread_default_run_cmd (char * args, int from_tty) [static]
Definition at line 2842 of file gnu-nat.c.
References cur_inf(), inf::default_thread_run_sc, and parse_bool_arg.
Referenced by add_task_commands().
static void set_thread_detach_sc_cmd (char * args, int from_tty) [static]
Definition at line 3314 of file gnu-nat.c.
References cur_thread(), proc::detach_sc, and parse_int_arg().
Referenced by add_thread_commands().
static void set_thread_exc_port_cmd (char * args, int from_tty) [static]
Definition at line 3333 of file gnu-nat.c.
References _, cur_thread(), error(), parse_and_eval_address(), and steal_exc_port().
Referenced by add_thread_commands().
static void set_thread_pause_cmd (char * args, int from_tty) [static]
Definition at line 3269 of file gnu-nat.c.
References cur_thread(), proc::inf, inf_suspend(), parse_bool_arg, proc::pause_sc, and inf::pause_sc.
Referenced by add_thread_commands().
static void set_thread_run_cmd (char * args, int from_tty) [static]
Definition at line 3295 of file gnu-nat.c.
References cur_thread(), parse_bool_arg, and proc::run_sc.
Referenced by add_thread_commands().
static void show_exceptions_cmd (char * args, int from_tty) [static]
Definition at line 3014 of file gnu-nat.c.
References check_empty(), cur_inf(), printf_unfiltered(), inf::task, and inf::want_exceptions.
Referenced by add_task_commands(), and show_task_cmd().
static void show_sig_thread_cmd (char * args, int from_tty) [static]
Definition at line 2963 of file gnu-nat.c.
References active_inf(), check_empty(), printf_unfiltered(), proc_string(), and inf::signal_thread.
Referenced by add_task_commands(), and show_task_cmd().
static void show_signals_cmd (char * args, int from_tty) [static]
Definition at line 2989 of file gnu-nat.c.
References check_empty(), cur_inf(), printf_unfiltered(), inf::task, inf::traced, and inf::want_signals.
Referenced by add_task_commands(), and show_task_cmd().
static void show_stopped_cmd (char * args, int from_tty) [static]
Definition at line 2930 of file gnu-nat.c.
References active_inf(), check_empty(), printf_unfiltered(), and inf::stopped.
Referenced by add_task_commands(), and show_task_cmd().
static void show_task_cmd (char * args, int from_tty) [static]
Definition at line 3034 of file gnu-nat.c.
References check_empty(), cur_inf(), inf::default_thread_detach_sc, inf::detach_sc, inf::pause_sc, show_exceptions_cmd(), show_sig_thread_cmd(), show_signals_cmd(), show_stopped_cmd(), show_task_detach_sc_cmd(), show_task_pause_cmd(), show_thread_default_detach_sc_cmd(), show_thread_default_pause_cmd(), show_thread_default_run_cmd(), and inf::task.
Referenced by add_task_commands().
static void show_task_detach_sc_cmd (char * args, int from_tty) [static]
Definition at line 2811 of file gnu-nat.c.
References check_empty(), cur_inf(), inf::detach_sc, and printf_unfiltered().
Referenced by add_task_commands(), and show_task_cmd().
static void show_task_pause_cmd (char * args, int from_tty) [static]
Definition at line 2792 of file gnu-nat.c.
References check_empty(), cur_inf(), inf::pause_sc, printf_unfiltered(), and inf::task.
Referenced by add_task_commands(), and show_task_cmd().
static void show_thread_cmd (char * args, int from_tty) [static]
Definition at line 2695 of file gnu-nat.c.
References printf_unfiltered().
Referenced by add_thread_commands().
static void show_thread_default_cmd (char * args, int from_tty) [static]
Definition at line 2709 of file gnu-nat.c.
References printf_unfiltered().
Referenced by add_thread_commands().
static void show_thread_default_detach_sc_cmd (char * args, int from_tty) [static]
Definition at line 2868 of file gnu-nat.c.
References check_empty(), cur_inf(), inf::default_thread_detach_sc, and printf_unfiltered().
Referenced by add_task_commands(), and show_task_cmd().
static void show_thread_default_pause_cmd (char * args, int from_tty) [static]
Definition at line 2830 of file gnu-nat.c.
References check_empty(), cur_inf(), inf::default_thread_pause_sc, inf::pause_sc, and printf_unfiltered().
Referenced by add_task_commands(), and show_task_cmd().
static void show_thread_default_run_cmd (char * args, int from_tty) [static]
Definition at line 2851 of file gnu-nat.c.
References check_empty(), cur_inf(), inf::default_thread_run_sc, and printf_unfiltered().
Referenced by add_task_commands(), and show_task_cmd().
static void show_thread_detach_sc_cmd (char * args, int from_tty) [static]
Definition at line 3321 of file gnu-nat.c.
References check_empty(), cur_thread(), proc::detach_sc, printf_unfiltered(), and proc_string().
Referenced by add_thread_commands().
static void show_thread_pause_cmd (char * args, int from_tty) [static]
Definition at line 3282 of file gnu-nat.c.
References check_empty(), cur_thread(), proc::inf, proc::pause_sc, inf::pause_sc, printf_unfiltered(), proc_string(), and proc::sc.
Referenced by add_thread_commands().
static void show_thread_run_cmd (char * args, int from_tty) [static]
Definition at line 3303 of file gnu-nat.c.
References check_empty(), cur_thread(), printf_unfiltered(), proc_string(), and proc::run_sc.
Referenced by add_thread_commands().
static void steal_exc_port (struct proc * proc, mach_port_t name) [static]
Definition at line 2879 of file gnu-nat.c.
References _, error(), inf::event_port, proc::exc_port, proc::inf, proc::port, proc_set_exception_port(), proc_string(), safe_strerror(), proc::saved_exc_port, and inf::task.
Referenced by set_task_exc_port_cmd(), and set_thread_exc_port_cmd().
static void thread_takeover_sc_cmd (char * args, int from_tty) [static]
Definition at line 3357 of file gnu-nat.c.
References cur_thread(), error(), proc::port, printf_unfiltered(), safe_strerror(), and proc::sc.
Referenced by add_thread_commands().
Variable Documentation
struct inf* gnu_current_inf = 0
Definition at line 1438 of file gnu-nat.c.
Referenced by cur_inf(), gnu_fetch_registers(), gnu_pid_to_str(), gnu_resume(), gnu_store_registers(), and gnu_wait().
int gnu_debug_flag = 0
Definition at line 86 of file gnu-nat.c.
Referenced by _initialize_gnu_nat().
int next_thread_id = 1 [static]
Definition at line 538 of file gnu-nat.c.
Referenced by inf_pick_first_thread(), and inf_validate_procs().
process_t proc_server = MACH_PORT_NULL [static]
Definition at line 77 of file gnu-nat.c.
Referenced by _initialize_gnu_nat(), gnu_wait(), inf_continue(), inf_set_pid(), inf_validate_procinfo(), and inf_validate_task_sc().
int proc_wait_pid = 0
Definition at line 81 of file gnu-nat.c.
Referenced by do_mach_notify_dead_name(), gnu_wait(), and S_proc_wait_reply().
int proc_waits_pending = 0
Definition at line 84 of file gnu-nat.c.
Referenced by gnu_wait(), and S_proc_wait_reply().
struct obstack region_obstack
Definition at line 2314 of file gnu-nat.c.
Referenced by gnu_write_inferior().
struct cmd_list_element* set_task_cmd_list = 0 [static]
Definition at line 2674 of file gnu-nat.c.
struct cmd_list_element* set_thread_cmd_list = NULL
Definition at line 2680 of file gnu-nat.c.
struct cmd_list_element* set_thread_default_cmd_list = NULL
Definition at line 2684 of file gnu-nat.c.
struct cmd_list_element* show_task_cmd_list = 0 [static]
Definition at line 2675 of file gnu-nat.c.
struct cmd_list_element* show_thread_cmd_list = NULL
Definition at line 2681 of file gnu-nat.c.
struct cmd_list_element* show_thread_default_cmd_list = NULL
Definition at line 2685 of file gnu-nat.c.
struct cmd_list_element* thread_cmd_list
Definition at line 1510 of file thread.c.
struct inf* waiting_inf
Definition at line 1442 of file gnu-nat.c.
Referenced by do_mach_notify_dead_name(), S_exception_raise_request(), S_msg_sig_post_untraced_reply(), and S_proc_wait_reply().