GDB (xrefs): /home/stan/gdb/src/gdb/go-lang.h File Reference
/home/stan/gdb/src/gdb/go-lang.h File Reference
#include "gdbtypes.h"
#include "symtab.h"
#include "value.h"
Classes
struct builtin_go_type
Enumerations
enum go_type { GO_TYPE_NONE, GO_TYPE_STRING }
Functions
int go_parse (void)
void go_error (char *)
const char * go_main_name (void)
enum go_type go_classify_struct_type (struct type *type)
char * go_demangle (const char *mangled, int options)
char * go_symbol_package_name (const struct symbol *sym)
char * go_block_package_name (const struct block *block)
struct builtin_go_type * builtin_go_type (struct gdbarch *)
void go_print_type (struct type *type, const char *varstring, struct ui_file *stream, int show, int level, const struct type_print_options *flags)
void go_val_print (struct type *type, const gdb_byte *valaddr, int embedded_offset, CORE_ADDR address, struct ui_file *stream, int recurse, const struct value *val, const struct value_print_options *options)
Enumeration Type Documentation
enum go_type
Enumerator:
GO_TYPE_NONE
GO_TYPE_STRING
Definition at line 51 of file go-lang.h.
Function Documentation
struct builtin_go_type* builtin_go_type (struct gdbarch *) [read]
Definition at line 653 of file go-lang.c.
References gdbarch_data().
Referenced by build_go_types(), go_language_arch_info(), and parse_go_float().
char* go_block_package_name (const struct block * block)
Definition at line 422 of file go-lang.c.
References BLOCK_FUNCTION, BLOCK_SUPERBLOCK, and go_symbol_package_name().
Referenced by classify_name().
enum go_type go_classify_struct_type (struct type * type)
Definition at line 121 of file go-lang.c.
References CHECK_TYPEDEF, gccgo_string_p(), GO_TYPE_NONE, GO_TYPE_STRING, and sixg_string_p().
Referenced by go_val_print().
char* go_demangle (const char * mangled, int options)
Definition at line 337 of file go-lang.c.
References obstack_grow_str, obstack_grow_str0, unpack_mangled_go_symbol(), and xfree().
Referenced by demangle_for_lookup(), and symbol_find_demangled_name().
void go_error (char *)
const char* go_main_name (void)
Definition at line 56 of file go-lang.c.
References GO_MAIN_MAIN, and lookup_minimal_symbol().
Referenced by find_main_name().
int go_parse (void)
Definition at line 3452 of file go-exp.c.
References do_cleanups(), make_cleanup(), make_cleanup_obstack_free(), make_cleanup_restore_integer(), null_cleanup(), parser_debug, VEC_free, and yyparse.
void go_print_type (struct type * type, const char * varstring, struct ui_file * stream, int show, int level, const struct type_print_options * flags)
Definition at line 45 of file go-typeprint.c.
References c_print_type(), CHECK_TYPEDEF, fputs_filtered(), TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_CHAR, and TYPE_TARGET_TYPE.
char* go_symbol_package_name (const struct symbol * sym)
Definition at line 393 of file go-lang.c.
References gdb_assert, language_go, SYMBOL_LANGUAGE, SYMBOL_LINKAGE_NAME, unpack_mangled_go_symbol(), and xfree().
Referenced by fixup_go_packaging(), and go_block_package_name().
void go_val_print (struct type * type, const gdb_byte * valaddr, int embedded_offset, CORE_ADDR address, struct ui_file * stream, int recurse, const struct value * val, const struct value_print_options * options)
Definition at line 89 of file go-valprint.c.
References c_val_print(), CHECK_TYPEDEF, go_classify_struct_type(), GO_TYPE_STRING, print_go_string(), value_print_options::raw, TYPE_CODE, and TYPE_CODE_STRUCT.