GDB (xrefs): /home/stan/gdb/src/gdb/go-valprint.c File Reference
/home/stan/gdb/src/gdb/go-valprint.c File Reference
#include "defs.h"
#include "gdbtypes.h"
#include "gdbcore.h"
#include "go-lang.h"
#include "c-lang.h"
#include "valprint.h"
Functions
static void print_go_string (struct type *type, const gdb_byte *valaddr, int embedded_offset, CORE_ADDR address, struct ui_file *stream, int recurse, const struct value *val, const struct value_print_options *options)
void go_val_print (struct type *type, const gdb_byte *valaddr, int embedded_offset, CORE_ADDR address, struct ui_file *stream, int recurse, const struct value *val, const struct value_print_options *options)
Function Documentation
void go_val_print (struct type * type, const gdb_byte * valaddr, int embedded_offset, CORE_ADDR address, struct ui_file * stream, int recurse, const struct value * val, const struct value_print_options * options)
Definition at line 89 of file go-valprint.c.
References c_val_print(), CHECK_TYPEDEF, go_classify_struct_type(), GO_TYPE_STRING, print_go_string(), value_print_options::raw, TYPE_CODE, and TYPE_CODE_STRUCT.
static void print_go_string (struct type * type, const gdb_byte * valaddr, int embedded_offset, CORE_ADDR address, struct ui_file * stream, int recurse, const struct value * val, const struct value_print_options * options) [static]
Definition at line 39 of file go-valprint.c.
References _, value_print_options::addressprint, error(), fputs_filtered(), gdb_assert, get_type_arch(), type::length, LONGEST, paddress(), plongest(), TYPE_FIELD_TYPE, TYPE_TARGET_TYPE, unpack_value_field_as_long(), val_print_string(), and value_contents_for_printing_const().
Referenced by go_val_print().