GDB (xrefs): /home/stan/gdb/src/gdb/go32-nat.c File Reference
/home/stan/gdb/src/gdb/go32-nat.c File Reference
#include "defs.h"
#include <fcntl.h>
#include "i386-nat.h"
#include "inferior.h"
#include "gdbthread.h"
#include "gdb_wait.h"
#include "gdbcore.h"
#include "command.h"
#include "gdbcmd.h"
#include "floatformat.h"
#include "buildsym.h"
#include "i387-tdep.h"
#include "i386-tdep.h"
#include "i386-cpuid.h"
#include "value.h"
#include "regcache.h"
#include "gdb_string.h"
#include "top.h"
#include "cli/cli-utils.h"
#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include <errno.h>
#include <unistd.h>
#include <sys/utsname.h>
#include <io.h>
#include <dos.h>
#include <dpmi.h>
#include <go32.h>
#include <sys/farptr.h>
#include <debug/v2load.h>
#include <debug/dbgcom.h>
#include <langinfo.h>
Classes
struct NPXREG
struct NPX
struct cmdline_t
struct seg_descr
struct gate_descr
struct dtr_reg
Defines
#define SOME_PID 42
#define r_ofs(x) (offsetof(TSS,x))
#define D_REGS edi.dr
#define CONTROL D_REGS[7]
#define STATUS D_REGS[6]
Enumerations
enum wp_op { wp_insert, wp_remove, wp_count }
Functions
static void save_npx (void)
static void load_npx (void)
void redir_cmdline_delete (cmdline_t *ptr)
int redir_cmdline_parse (const char *args, cmdline_t *ptr)
int redir_to_child (cmdline_t *ptr)
int redir_to_debugger (cmdline_t *ptr)
int redir_debug_init (cmdline_t *ptr)
static void go32_open (char *name, int from_tty)
static void go32_close (void)
static void go32_attach (struct target_ops *ops, char *args, int from_tty)
static void go32_detach (struct target_ops *ops, char *args, int from_tty)
static void go32_resume (struct target_ops *ops, ptid_t ptid, int step, enum gdb_signal siggnal)
static void go32_fetch_registers (struct target_ops *ops, struct regcache *, int regno)
static void store_register (const struct regcache *, int regno)
static void go32_store_registers (struct target_ops *ops, struct regcache *, int regno)
static void go32_prepare_to_store (struct regcache *)
static int go32_xfer_memory (CORE_ADDR memaddr, gdb_byte *myaddr, int len, int write, struct mem_attrib *attrib, struct target_ops *target)
static void go32_files_info (struct target_ops *target)
static void go32_kill_inferior (struct target_ops *ops)
static void go32_create_inferior (struct target_ops *ops, char *exec_file, char *args, char **env, int from_tty)
static void go32_mourn_inferior (struct target_ops *ops)
static int go32_can_run (void)
static void go32_terminal_init (void)
static void go32_terminal_inferior (void)
static void go32_terminal_ours (void)
static ptid_t go32_wait (struct target_ops *ops, ptid_t ptid, struct target_waitstatus *status, int options)
static void fetch_register (struct regcache *regcache, int regno)
static void go32_set_dr (int i, CORE_ADDR addr)
static void go32_set_dr7 (unsigned long val)
static unsigned long go32_get_dr6 (void)
static unsigned long go32_get_dr7 (void)
static CORE_ADDR go32_get_dr (int i)
static int device_mode (int fd, int raw_p)
static void go32_terminal_info (const char *args, int from_tty)
static int go32_thread_alive (struct target_ops *ops, ptid_t ptid)
static char * go32_pid_to_str (struct target_ops *ops, ptid_t ptid)
static void init_go32_ops (void)
static int dos_codepage (void)
char * nl_langinfo (nl_item item)
static void go32_get_windows_version (void)
static void print_mem (unsigned long datum, const char *header, int in_pages_p)
static void go32_sysinfo (char *arg, int from_tty)
struct seg_descr __attribute__ ((packed))
static int read_memory_region (unsigned long addr, void *dest, size_t len)
static int get_descriptor (unsigned long table_base, int idx, void *descr)
static void display_descriptor (unsigned type, unsigned long base_addr, int idx, int force)
static void go32_sldt (char *arg, int from_tty)
static void go32_sgdt (char *arg, int from_tty)
static void go32_sidt (char *arg, int from_tty)
static unsigned long get_cr3 (void)
static unsigned long get_pde (int n)
static unsigned long get_pte (unsigned long pde, int n)
static void display_ptable_entry (unsigned long entry, int is_dir, int force, unsigned off)
static void go32_pde (char *arg, int from_tty)
static void display_page_table (long n, int force)
static void go32_pte (char *arg, int from_tty)
static void go32_pte_for_address (char *arg, int from_tty)
static void go32_info_dos_command (char *args, int from_tty)
void _initialize_go32_nat (void)
pid_t tcgetpgrp (int fd)
int tcsetpgrp (int fd, pid_t pgid)
Variables
static NPX npx
static int dr_ref_count [4]
static int prog_has_started = 0
static struct target_ops go32_ops
struct {
size_t tss_ofs
size_t size
} regno_mapping []
struct {
int go32_sig
enum gdb_signal gdb_sig
} sig_map []
struct {
enum gdb_signal gdb_sig
int djgpp_excepno
} excepn_map []
static int resume_is_step
static int resume_signal = -1
static char child_cwd [FILENAME_MAX]
static cmdline_t child_cmd
static int inf_mode_valid = 0
static int inf_terminal_mode
static int terminal_is_ours = 1
unsigned short windows_major
unsigned short windows_minor
unsigned short limit0
unsigned short base0
unsigned char base1
unsigned stype
unsigned dpl
unsigned present
unsigned limit1
unsigned available
unsigned dummy
unsigned bit32
unsigned page_granular
unsigned char base2
unsigned short offset0
unsigned short selector
unsigned param_count
unsigned short offset1
struct dtr_reg __attribute__
static unsigned long pdbr
static struct cmd_list_element * info_dos_cmdlist = NULL
initialize_file_ftype _initialize_go32_nat
Define Documentation
#define CONTROL D_REGS[7]
Definition at line 773 of file go32-nat.c.
Referenced by go32_get_dr7(), and go32_set_dr7().
#define D_REGS edi.dr
Definition at line 772 of file go32-nat.c.
Referenced by go32_get_dr(), and go32_set_dr().
#define r_ofs (x) (offsetof(TSS,x))
Definition at line 266 of file go32-nat.c.
#define SOME_PID 42
Definition at line 234 of file go32-nat.c.
Referenced by go32_create_inferior(), go32_wait(), tcgetpgrp(), and tcsetpgrp().
#define STATUS D_REGS[6]
Definition at line 774 of file go32-nat.c.
Referenced by go32_get_dr6().
Enumeration Type Documentation
enum wp_op
Enumerator:
wp_insert
wp_remove
wp_count
Definition at line 229 of file go32-nat.c.
Function Documentation
struct seg_descr __attribute__ ((packed))
void _initialize_go32_nat (void)
Definition at line 2118 of file go32-nat.c.
References _, add_cmd(), add_prefix_cmd(), add_target(), class_info, go32_info_dos_command(), go32_ops, go32_pde(), go32_pte(), go32_pte_for_address(), go32_sgdt(), go32_sidt(), go32_sldt(), go32_sysinfo(), infolist, and init_go32_ops().
static int device_mode (int fd, int raw_p) [static]
Definition at line 833 of file go32-nat.c.
Referenced by go32_terminal_inferior(), and go32_terminal_ours().
static void display_descriptor (unsigned type, unsigned long base_addr, int idx, int force) [static]
Definition at line 1576 of file go32-nat.c.
References seg_descr::base0, seg_descr::base1, seg_descr::base2, seg_descr::bit32, get_descriptor(), L, seg_descr::limit0, seg_descr::limit1, memcpy(), gate_descr::offset0, gate_descr::offset1, seg_descr::page_granular, gate_descr::param_count, seg_descr::present, printf_filtered(), printfi_filtered(), prog_has_started, puts_filtered(), gate_descr::selector, and seg_descr::stype.
Referenced by go32_sgdt(), go32_sidt(), and go32_sldt().
static void display_page_table (long n, int force) [static]
Definition at line 2031 of file go32-nat.c.
References display_ptable_entry(), get_pde(), get_pte(), printf_filtered(), and puts_filtered().
Referenced by go32_pte().
static void display_ptable_entry (unsigned long entry, int is_dir, int force, unsigned off) [static]
Definition at line 1976 of file go32-nat.c.
References printf_filtered(), and puts_filtered().
Referenced by display_page_table(), go32_pde(), and go32_pte_for_address().
static int dos_codepage (void) [static]
Definition at line 1035 of file go32-nat.c.
Referenced by nl_langinfo().
static void fetch_register (struct regcache * regcache, int regno) [static]
Definition at line 539 of file go32-nat.c.
References _, gdbarch_fp0_regnum(), get_regcache_arch(), i386_fp_regnum_p(), i386_fpc_regnum_p(), i387_supply_fsave(), internal_error(), regcache_raw_supply(), regno_mapping, and tss_ofs.
Referenced by go32_fetch_registers().
static unsigned long get_cr3 (void) [static]
Definition at line 1874 of file go32-nat.c.
References offset, and pdbr.
Referenced by go32_pde(), go32_pte(), and go32_pte_for_address().
static int get_descriptor (unsigned long table_base, int idx, void * descr) [static]
Definition at line 1558 of file go32-nat.c.
References read_memory_region().
Referenced by display_descriptor(), and go32_sldt().
static unsigned long get_pde (int n) [static]
Definition at line 1943 of file go32-nat.c.
Referenced by display_page_table(), go32_pde(), and go32_pte_for_address().
static unsigned long get_pte (unsigned long pde, int n) [static]
Definition at line 1957 of file go32-nat.c.
Referenced by display_page_table(), and go32_pte_for_address().
static void go32_attach (struct target_ops * ops, char * args, int from_tty) [static]
Definition at line 379 of file go32-nat.c.
References _, and error().
Referenced by init_go32_ops().
static int go32_can_run (void) [static]
Definition at line 765 of file go32-nat.c.
Referenced by init_go32_ops().
static void go32_close (void) [static]
Definition at line 374 of file go32-nat.c.
Referenced by init_go32_ops().
static void go32_create_inferior (struct target_ops * ops, char * exec_file, char * args, char ** env, int from_tty) [static]
Definition at line 648 of file go32-nat.c.
References _, add_thread_silent(), child_cwd, clear_proceed_status(), cmdline_t::command, current_inferior(), environ, error(), get_exec_file(), go32_ops, arm-linux::inf, inferior_appeared(), inferior_ptid, insert_breakpoints(), internal_error(), pid_to_ptid(), printf_unfiltered(), prog_has_started, push_target(), redir_cmdline_parse(), redir_debug_init(), resume_is_step, resume_signal, save_npx(), SOME_PID, xfree(), and xmalloc().
Referenced by init_go32_ops().
static void go32_detach (struct target_ops * ops, char * args, int from_tty) [static]
Definition at line 387 of file go32-nat.c.
Referenced by init_go32_ops().
static void go32_fetch_registers (struct target_ops * ops, struct regcache * regcache, int regno) [static]
Definition at line 554 of file go32-nat.c.
References fetch_register(), gdbarch_fp0_regnum(), get_regcache_arch(), and i387_supply_fsave().
Referenced by init_go32_ops().
static void go32_files_info (struct target_ops * target) [static]
Definition at line 636 of file go32-nat.c.
References printf_unfiltered().
Referenced by init_go32_ops().
static CORE_ADDR go32_get_dr (int i) [static]
Definition at line 821 of file go32-nat.c.
References _, D_REGS, and internal_error().
Referenced by init_go32_ops().
static unsigned long go32_get_dr6 (void) [static]
Definition at line 801 of file go32-nat.c.
References STATUS.
Referenced by init_go32_ops().
static unsigned long go32_get_dr7 (void) [static]
Definition at line 811 of file go32-nat.c.
References CONTROL.
Referenced by init_go32_ops().
static void go32_get_windows_version (void) [static]
Definition at line 1078 of file go32-nat.c.
References windows_major, and windows_minor.
Referenced by go32_sysinfo().
static void go32_info_dos_command (char * args, int from_tty) [static]
Definition at line 2109 of file go32-nat.c.
References class_info, gdb_stdout, and help_list().
Referenced by _initialize_go32_nat().
static void go32_kill_inferior (struct target_ops * ops) [static]
Definition at line 642 of file go32-nat.c.
References go32_mourn_inferior().
Referenced by init_go32_ops().
static void go32_mourn_inferior (struct target_ops * ops) [static]
Definition at line 736 of file go32-nat.c.
References delete_thread_silent(), generic_mourn_inferior(), i386_cleanup_dregs(), inferior_ptid, null_ptid, prog_has_started, redir_cmdline_delete(), resume_is_step, resume_signal, and unpush_target().
Referenced by go32_kill_inferior(), and init_go32_ops().
static void go32_open (char * name, int from_tty) [static]
Definition at line 368 of file go32-nat.c.
References printf_unfiltered().
Referenced by init_go32_ops().
static void go32_pde (char * arg, int from_tty) [static]
Definition at line 2000 of file go32-nat.c.
References _, display_ptable_entry(), error(), get_cr3(), get_pde(), parse_and_eval_long(), puts_filtered(), and skip_spaces().
Referenced by _initialize_go32_nat().
static char* go32_pid_to_str (struct target_ops * ops, ptid_t ptid) [static]
Definition at line 964 of file go32-nat.c.
References normal_pid_to_str().
Referenced by init_go32_ops().
static void go32_prepare_to_store (struct regcache * regcache) [static]
Definition at line 601 of file go32-nat.c.
Referenced by init_go32_ops().
static void go32_pte (char * arg, int from_tty) [static]
Definition at line 2050 of file go32-nat.c.
References _, display_page_table(), error(), get_cr3(), L, parse_and_eval_long(), puts_filtered(), and skip_spaces().
Referenced by _initialize_go32_nat().
static void go32_pte_for_address (char * arg, int from_tty) [static]
Definition at line 2077 of file go32-nat.c.
References _, display_ptable_entry(), error_no_arg(), get_cr3(), get_pde(), get_pte(), hex_string(), parse_and_eval_address(), printf_filtered(), puts_filtered(), and skip_spaces().
Referenced by _initialize_go32_nat().
static void go32_resume (struct target_ops * ops, ptid_t ptid, int step, enum gdb_signal siggnal) [static]
Definition at line 395 of file go32-nat.c.
References excepn_map, gdb_sig, gdb_signal_to_name(), printf_unfiltered(), resume_is_step, and resume_signal.
Referenced by init_go32_ops().
static void go32_set_dr (int i, CORE_ADDR addr) [static]
Definition at line 780 of file go32-nat.c.
References _, D_REGS, and internal_error().
Referenced by init_go32_ops().
static void go32_set_dr7 (unsigned long val) [static]
Definition at line 792 of file go32-nat.c.
References CONTROL.
Referenced by init_go32_ops().
static void go32_sgdt (char * arg, int from_tty) [static]
Definition at line 1787 of file go32-nat.c.
References _, display_descriptor(), error(), L, parse_and_eval_long(), and skip_spaces().
Referenced by _initialize_go32_nat().
static void go32_sidt (char * arg, int from_tty) [static]
Definition at line 1828 of file go32-nat.c.
References _, display_descriptor(), error(), L, parse_and_eval_long(), and skip_spaces().
Referenced by _initialize_go32_nat().
static void go32_sldt (char * arg, int from_tty) [static]
Definition at line 1714 of file go32-nat.c.
References _, seg_descr::base0, seg_descr::base1, seg_descr::base2, display_descriptor(), error(), get_descriptor(), L, seg_descr::limit0, seg_descr::limit1, seg_descr::page_granular, parse_and_eval_long(), printf_filtered(), prog_has_started, puts_filtered(), skip_spaces(), and seg_descr::stype.
Referenced by _initialize_go32_nat().
static void go32_store_registers (struct target_ops * ops, struct regcache * regcache, int regno) [static]
Definition at line 585 of file go32-nat.c.
References gdbarch_fp0_regnum(), get_regcache_arch(), i387_collect_fsave(), and store_register().
Referenced by init_go32_ops().
static void go32_sysinfo (char * arg, int from_tty) [static]
Definition at line 1117 of file go32-nat.c.
References go32_get_windows_version(), i386_cpuid(), int, memcmp(), memcpy(), print_mem(), printf_filtered(), printfi_filtered(), prog_has_started, puts_filtered(), windows_major, windows_minor, and xsnprintf().
Referenced by _initialize_go32_nat().
static void go32_terminal_inferior (void) [static]
Definition at line 910 of file go32-nat.c.
References _, device_mode(), error(), inf_mode_valid, inf_terminal_mode, redir_to_child(), redir_to_debugger(), safe_strerror(), and terminal_is_ours.
Referenced by init_go32_ops().
static void go32_terminal_info (const char * args, int from_tty) [static]
Definition at line 880 of file go32-nat.c.
References inf_mode_valid, inf_terminal_mode, and printf_unfiltered().
Referenced by init_go32_ops().
static void go32_terminal_init (void) [static]
Definition at line 873 of file go32-nat.c.
References inf_mode_valid, and terminal_is_ours.
Referenced by init_go32_ops().
static void go32_terminal_ours (void) [static]
Definition at line 931 of file go32-nat.c.
References _, device_mode(), error(), inf_mode_valid, inf_terminal_mode, redir_to_child(), redir_to_debugger(), safe_strerror(), and terminal_is_ours.
Referenced by init_go32_ops().
static int go32_thread_alive (struct target_ops * ops, ptid_t ptid) [static]
Definition at line 958 of file go32-nat.c.
References inferior_ptid, null_ptid, and ptid_equal().
Referenced by init_go32_ops().
static ptid_t go32_wait (struct target_ops * ops, ptid_t ptid, struct target_waitstatus * status, int options) [static]
Definition at line 420 of file go32-nat.c.
References child_cwd, current_directory, target_waitstatus::integer, target_waitstatus::kind, load_npx(), pid_to_ptid(), resume_is_step, resume_signal, save_npx(), target_waitstatus::sig, sig_map, SOME_PID, TARGET_WAITKIND_EXITED, TARGET_WAITKIND_SIGNALLED, TARGET_WAITKIND_STOPPED, and target_waitstatus::value.
Referenced by init_go32_ops().
static int go32_xfer_memory (CORE_ADDR memaddr, gdb_byte * myaddr, int len, int write, struct mem_attrib * attrib, struct target_ops * target) [static]
Definition at line 606 of file go32-nat.c.
References len.
Referenced by init_go32_ops().
static void init_go32_ops (void) [static]
Definition at line 970 of file go32-nat.c.
References _, child_cwd, default_child_has_all_memory(), default_child_has_execution(), default_child_has_memory(), default_child_has_registers(), default_child_has_stack(), target_ops::deprecated_xfer_memory, i386_dr_low_type::get_addr, i386_dr_low_type::get_control, i386_dr_low_type::get_status, go32_attach(), go32_can_run(), go32_close(), go32_create_inferior(), go32_detach(), go32_fetch_registers(), go32_files_info(), go32_get_dr(), go32_get_dr6(), go32_get_dr7(), go32_kill_inferior(), go32_mourn_inferior(), go32_open(), go32_ops, go32_pid_to_str(), go32_prepare_to_store(), go32_resume(), go32_set_dr(), go32_set_dr7(), go32_store_registers(), go32_terminal_inferior(), go32_terminal_info(), go32_terminal_init(), go32_terminal_ours(), go32_thread_alive(), go32_wait(), go32_xfer_memory(), i386_dr_low, i386_set_debug_register_length(), i386_use_watchpoints(), internal_error(), memory_insert_breakpoint(), memory_remove_breakpoint(), OPS_MAGIC, process_stratum, processing_gcc_compilation, redir_debug_init(), i386_dr_low_type::set_addr, i386_dr_low_type::set_control, target_ops::to_attach, target_ops::to_can_run, target_ops::to_close, target_ops::to_create_inferior, target_ops::to_detach, target_ops::to_doc, target_ops::to_fetch_registers, target_ops::to_files_info, target_ops::to_has_all_memory, target_ops::to_has_execution, target_ops::to_has_memory, target_ops::to_has_registers, target_ops::to_has_stack, target_ops::to_insert_breakpoint, target_ops::to_kill, target_ops::to_longname, target_ops::to_magic, target_ops::to_mourn_inferior, target_ops::to_open, target_ops::to_pid_to_str, target_ops::to_prepare_to_store, target_ops::to_remove_breakpoint, target_ops::to_resume, target_ops::to_shortname, target_ops::to_store_registers, target_ops::to_stratum, target_ops::to_terminal_inferior, target_ops::to_terminal_info, target_ops::to_terminal_init, target_ops::to_terminal_ours, target_ops::to_terminal_ours_for_output, target_ops::to_thread_alive, and target_ops::to_wait.
Referenced by _initialize_go32_nat().
static void load_npx (void) [static]
Definition at line 187 of file go32-nat.c.
References npx.
Referenced by go32_wait().
char* nl_langinfo (nl_item item)
Definition at line 1049 of file go32-nat.c.
References CODESET, and dos_codepage().
Referenced by _initialize_charset().
static void print_mem (unsigned long datum, const char * header, int in_pages_p) [static]
Definition at line 1096 of file go32-nat.c.
References printf_filtered(), and puts_filtered().
Referenced by go32_sysinfo().
static int read_memory_region (unsigned long addr, void * dest, size_t len) [static]
Definition at line 1501 of file go32-nat.c.
Referenced by get_descriptor().
void redir_cmdline_delete (cmdline_t * ptr)
Definition at line 199 of file go32-nat.c.
References cmdline_t::redirected.
Referenced by go32_mourn_inferior().
int redir_cmdline_parse (const char * args, cmdline_t * ptr)
Definition at line 205 of file go32-nat.c.
Referenced by go32_create_inferior().
int redir_debug_init (cmdline_t * ptr)
Definition at line 223 of file go32-nat.c.
Referenced by go32_create_inferior(), and init_go32_ops().
int redir_to_child (cmdline_t * ptr)
Definition at line 211 of file go32-nat.c.
Referenced by go32_terminal_inferior(), and go32_terminal_ours().
int redir_to_debugger (cmdline_t * ptr)
Definition at line 217 of file go32-nat.c.
Referenced by go32_terminal_inferior(), and go32_terminal_ours().
static void save_npx (void) [static]
Definition at line 162 of file go32-nat.c.
References npx.
Referenced by go32_create_inferior(), and go32_wait().
static void store_register (const struct regcache * regcache, int regno) [static]
Definition at line 570 of file go32-nat.c.
References _, gdbarch_fp0_regnum(), get_regcache_arch(), i386_fp_regnum_p(), i386_fpc_regnum_p(), i387_collect_fsave(), internal_error(), regcache_raw_collect(), regno_mapping, and tss_ofs.
Referenced by go32_store_registers().
pid_t tcgetpgrp (int fd)
Definition at line 2164 of file go32-nat.c.
References SOME_PID.
int tcsetpgrp (int fd, pid_t pgid)
Definition at line 2173 of file go32-nat.c.
References SOME_PID.
Referenced by terminal_inferior(), and terminal_ours_1().
Variable Documentation
struct gate_descr __attribute__
initialize_file_ftype _initialize_go32_nat
unsigned available
Definition at line 1493 of file go32-nat.c.
Referenced by arm_linux_get_hwbp_cap(), memory_xfer_partial_1(), mi_cmd_list_thread_groups(), net_windows_wait_handle(), and pipe_windows_read().
unsigned short base0
Definition at line 1487 of file go32-nat.c.
unsigned char base1
Definition at line 1488 of file go32-nat.c.
unsigned char base2
Definition at line 1497 of file go32-nat.c.
unsigned bit32
Definition at line 1495 of file go32-nat.c.
cmdline_t child_cmd [static]
Definition at line 633 of file go32-nat.c.
char child_cwd[FILENAME_MAX] [static]
Definition at line 417 of file go32-nat.c.
Referenced by go32_create_inferior(), go32_wait(), and init_go32_ops().
int djgpp_excepno
Definition at line 349 of file go32-nat.c.
unsigned dpl
Definition at line 1490 of file go32-nat.c.
int dr_ref_count[4] [static]
Definition at line 232 of file go32-nat.c.
Referenced by aarch64_dr_state_insert_one_point(), and aarch64_dr_state_remove_one_point().
unsigned dummy
Definition at line 1494 of file go32-nat.c.
Referenced by aarch64_stub_unwind_sniffer(), arm_stub_unwind_sniffer(), dwarf2_ranges_read(), gdb_eval(), gdb_update_mem(), get_register(), hppa_linux_sigtramp_find_sigcontext(), linux_is_uclinux(), mips_stub_frame_sniffer(), nios2_stub_frame_sniffer(), parse_pid_to_attach(), pop_dummy_frame(), pop_dummy_frame_bpt(), print_decimal_chars(), remove_dummy_frame(), s390_analyze_prologue(), var_decode_location(), varobj_get_num_children(), and VEC().
struct { ... } excepn_map[] [static]
Referenced by go32_resume().
enum gdb_signal gdb_sig
Definition at line 314 of file go32-nat.c.
Referenced by go32_resume().
struct target_ops go32_ops [static]
Definition at line 261 of file go32-nat.c.
Referenced by _initialize_go32_nat(), go32_create_inferior(), and init_go32_ops().
int go32_sig
Definition at line 313 of file go32-nat.c.
int inf_mode_valid = 0 [static]
Definition at line 863 of file go32-nat.c.
Referenced by go32_terminal_inferior(), go32_terminal_info(), go32_terminal_init(), and go32_terminal_ours().
int inf_terminal_mode [static]
Definition at line 864 of file go32-nat.c.
Referenced by go32_terminal_inferior(), go32_terminal_info(), and go32_terminal_ours().
struct cmd_list_element* info_dos_cmdlist = NULL [static]
Definition at line 2106 of file go32-nat.c.
unsigned short limit0
Definition at line 1486 of file go32-nat.c.
unsigned limit1
Definition at line 1492 of file go32-nat.c.
NPX npx [static]
Definition at line 152 of file go32-nat.c.
Referenced by load_npx(), and save_npx().
unsigned short offset0
Definition at line 1497 of file go32-nat.c.
unsigned short offset1
Definition at line 1504 of file go32-nat.c.
Referenced by value_available_contents_eq().
unsigned page_granular
Definition at line 1496 of file go32-nat.c.
unsigned param_count
Definition at line 1499 of file go32-nat.c.
unsigned long pdbr [static]
Definition at line 1871 of file go32-nat.c.
Referenced by get_cr3().
unsigned present
Definition at line 1491 of file go32-nat.c.
int prog_has_started = 0 [static]
Definition at line 236 of file go32-nat.c.
Referenced by display_descriptor(), go32_create_inferior(), go32_mourn_inferior(), go32_sldt(), and go32_sysinfo().
struct { ... } regno_mapping[] [static]
Referenced by fetch_register(), and store_register().
int resume_is_step [static]
Definition at line 391 of file go32-nat.c.
Referenced by go32_create_inferior(), go32_mourn_inferior(), go32_resume(), and go32_wait().
int resume_signal = -1 [static]
Definition at line 392 of file go32-nat.c.
Referenced by go32_create_inferior(), go32_mourn_inferior(), go32_resume(), go32_wait(), and startup_inferior().
unsigned short selector
Definition at line 1498 of file go32-nat.c.
Referenced by completion_list_objc_symbol(), evaluate_subexp_standard(), print_subexp_standard(), and select_event_lwp_callback().
struct { ... } sig_map[] [static]
Referenced by go32_wait().
size_t size
Definition at line 271 of file go32-nat.c.
Referenced by ada_to_fixed_type_1(), add_component_interval(), add_piece(), alloc_section_addr_info(), arm_displaced_init_closure(), arm_obj_section_from_vma(), ax_const_l(), bad_GetConsoleFontSize(), bfd_open_from_target_memory(), bfd_uses_spe_extensions(), buffer_grow(), build_id_to_debug_bfd(), catcher_list_size(), cmd_record_call_history(), cmd_record_insn_history(), command_size_to_target_size(), compare_sections_command(), complete_command(), complete_symtab(), compute_enum_values(), core_xfer_partial(), cp_lookup_nested_symbol(), create_dwo_unit_in_dwp_v2(), create_dwp_v2_section(), ctf_save_write(), darwin_debug_regions(), darwin_dump_message(), debug_print_register(), decode_locdesc(), display_one_tib(), do_examine(), dwarf2_add_member_fn(), dwarf2_compile_expr_to_ax(), dwarf2_fetch_die_loc_sect_off(), dwarf2_frame_state_alloc_regs(), dwarf2_frame_state_copy_regs(), dwarf_alloc_die(), dwarf_entry_parameter_to_value(), dwarf_expr_push_dwarf_reg_entry_value(), elf_symtab_read(), execute_cfa_program(), execute_stack_op(), fbsd_find_memory_regions(), fbsd_make_corefile_notes(), fill_gregset(), finalize_symtab(), find_linenos(), find_source_lines(), frame_unwind_register_signed(), frame_unwind_register_unsigned(), gcore_copy_callback(), gdb_load_info(), gdb_set_mem(), gdb_update_mem(), get_core_register_section(), get_data_from_address(), get_image_name(), get_memory_read_packet_size(), gnuv3_make_method_ptr(), handle_inc_and_index_mode_for_aritm_op(), handle_stap_probe(), hppa_frame_prev_register_helper(), hppa_hpux_core_osabi_sniffer(), hppa_hpux_fetch_register(), hppa_hpux_save_state_offset(), hppa_hpux_store_register(), hppa_hpux_supply_save_state(), i386_handle_nonaligned_watchpoint(), i386_linux_core_read_xcr0(), i386_stap_parse_special_token(), ia64_linux_fetch_register(), ia64_linux_store_register(), inf_ptrace_fetch_register(), inf_ptrace_store_register(), init_lineno(), install_load_store(), iq2000_extract_return_value(), iq2000_store_return_value(), jit_unwind_reg_get_impl(), linux_spu_make_corefile_notes(), linux_xfer_osdata_modules(), linux_xfer_osdata_shm(), list_overlays_command(), load_section_callback(), load_srec(), locexpr_describe_location_1(), loclist_read_variable(), loclist_read_variable_at_entry(), loclist_tracepoint_var_ref(), m32c_analyze_prologue(), m32c_decode_sd23(), m32c_decode_srcdest4(), m68hc11_scan_prologue(), mark_common_block_symbol_computed(), mep_analyze_prologue(), mep_pseudo_csr_write(), mep_register_type(), mips_breakpoint_from_pc(), mips_remote_breakpoint_from_pc(), mips_single_step_through_delay(), msp430_analyze_prologue(), msp430_push_dummy_call(), msp430_return_value(), new_bvect(), new_linetable(), objfile_find_memory_regions(), parse_find_args(), pc_in_unmapped_range(), proc_get_traced_sysentry(), proc_get_traced_sysexit(), procfs_breakpoint(), procfs_meminfo(), psymtab_to_symtab_1(), pv_area_store(), read_base_type(), read_call_site_scope(), read_common_block(), read_frame_register_unsigned(), read_map(), record_linux_system_call(), regcache_raw_collect(), regcache_raw_supply(), register_size(), remote_get_tracepoint_status(), remote_query_attached(), remote_trace_set_readonly_regions(), restore_section_callback(), s390_prologue_frame_unwind_cache(), sdata_make_value(), set_memory_packet_size(), set_process_privilege(), simple_overlay_update(), simple_overlay_update_1(), spu_current_sos(), spu_get_overlay_table(), syms_from_objfile_1(), sysset_t_alloc(), tdesc_create_flags(), tdesc_set_struct_size(), tfile_xfer_partial(), thumb2_copy_load_literal(), var_decode_location(), VEC(), xcoff_initial_scan(), xstormy16_push_dummy_call(), xtensa_push_dummy_call(), xtensa_register_read_masked(), xtensa_register_type(), and xtensa_register_write_masked().
unsigned stype
Definition at line 1489 of file go32-nat.c.
Referenced by execute_stack_op().
int terminal_is_ours = 1 [static]
Definition at line 870 of file go32-nat.c.
Referenced by go32_terminal_inferior(), go32_terminal_init(), and go32_terminal_ours().
size_t tss_ofs
Definition at line 270 of file go32-nat.c.
Referenced by fetch_register(), and store_register().
unsigned short windows_major
Definition at line 1074 of file go32-nat.c.
Referenced by go32_get_windows_version(), and go32_sysinfo().
unsigned short windows_minor
Definition at line 1074 of file go32-nat.c.
Referenced by go32_get_windows_version(), and go32_sysinfo().