GDB (xrefs): /home/stan/gdb/src/gdb/gregset.h File Reference
/home/stan/gdb/src/gdb/gregset.h File Reference
Typedefs
typedef GDB_GREGSET_T gdb_gregset_t
typedef GDB_FPREGSET_T gdb_fpregset_t
Functions
void supply_gregset (struct regcache *regcache, const gdb_gregset_t *gregs)
void supply_fpregset (struct regcache *regcache, const gdb_fpregset_t *fpregs)
void fill_gregset (const struct regcache *regcache, gdb_gregset_t *gregs, int regno)
void fill_fpregset (const struct regcache *regcache, gdb_fpregset_t *fpregs, int regno)
Typedef Documentation
typedef GDB_FPREGSET_T gdb_fpregset_t
Definition at line 35 of file gregset.h.
typedef GDB_GREGSET_T gdb_gregset_t
Definition at line 34 of file gregset.h.
Function Documentation
void fill_fpregset (const struct regcache * regcache, gdb_fpregset_t * fpregs, int regno)
Definition at line 639 of file aarch64-linux-nat.c.
References AARCH64_FPCR_REGNUM, AARCH64_FPSR_REGNUM, AARCH64_V0_REGNUM, AARCH64_V31_REGNUM, alpha_fill_fp_regs(), arm_linux_collect_nwfpe(), get_regcache_arch(), HPPA_FP0_REGNUM, mips64_fill_fpregset(), mips_fill_fpregset(), mips_isa_regsize(), ppc_collect_fpregset(), ppc_fbsd_fpregset(), ppc_linux_fpregset(), regcache_raw_collect(), sparc32_collect_fpregset(), sparc64_bsd_fpregset, sparc64_collect_fpregset(), sparc_collect_fpregset, sparc_sol2_fpregset, to, and V_REGISTER_SIZE.
Referenced by dec_thread_store_registers(), linux_nat_collect_thread_registers(), ppcfbsd_store_inferior_registers(), ps_lgetfpregs(), sol_thread_store_registers(), store_all_fp_regs(), and store_fpregs().
void fill_gregset (const struct regcache * regcache, gdb_gregset_t * gregs, int regno)
Definition at line 612 of file aarch64-linux-nat.c.
References AARCH64_CPSR_REGNUM, AARCH64_X0_REGNUM, alpha_fill_int_regs(), xtensa_elf_gregset_t::ar, gdbarch_tdep::ar_base, arm_linux_collect_gregset(), gdbarch_pc_regnum(), gdbarch_ps_regnum(), gdbarch_tdep(), get_regcache_arch(), greg_map, xtensa_elf_gregset_t::lbeg, xtensa_elf_gregset_t::lcount, xtensa_elf_gregset_t::lend, memset(), mips64_fill_gregset(), mips_fill_gregset(), mips_isa_regsize(), gdbarch_tdep::num_aregs, xtensa_elf_gregset_t::pc, ppc_collect_gregset(), ppc_fbsd_gregset(), ppc_linux_gregset(), xtensa_elf_gregset_t::ps, regcache_raw_collect(), xtensa_elf_gregset_t::sar, sparc32_collect_gregset(), sparc64_collect_gregset(), sparc_collect_gregset, sparc_sol2_gregset, xtensa_elf_gregset_t::windowbase, xtensa_elf_gregset_t::windowstart, and X_REGISTER_SIZE.
Referenced by dec_thread_store_registers(), linux_nat_collect_thread_registers(), ppcfbsd_store_inferior_registers(), ps_lgetregs(), sol_thread_store_registers(), store_all_gp_regs(), store_gregs(), store_inferior_registers(), and store_regs().
void supply_fpregset (struct regcache * regcache, const gdb_fpregset_t * fpregs)
Definition at line 664 of file aarch64-linux-nat.c.
References aarch64_linux_supply_fpregset(), alpha_supply_fp_regs(), arm_linux_supply_nwfpe(), from, get_regcache_arch(), HPPA_FP0_REGNUM, mips64_supply_fpregset(), mips_isa_regsize(), mips_supply_fpregset(), ppc_fbsd_fpregset(), ppc_linux_fpregset(), ppc_supply_fpregset(), regcache_raw_supply(), sparc32_supply_fpregset(), sparc64_bsd_fpregset, sparc64_supply_fpregset(), sparc_sol2_fpregset, and sparc_supply_fpregset.
Referenced by dec_thread_fetch_registers(), fetch_all_fp_regs(), fetch_core_registers(), fetch_fpregs(), procfs_fetch_registers(), ps_lsetfpregs(), and sol_thread_fetch_registers().
void supply_gregset (struct regcache * regcache, const gdb_gregset_t * gregs)
Definition at line 629 of file aarch64-linux-nat.c.
References aarch64_linux_supply_gregset(), alpha_supply_int_regs(), arm_linux_supply_gregset(), get_regcache_arch(), greg_map, mips64_supply_gregset(), mips_isa_regsize(), mips_supply_gregset(), ppc_fbsd_gregset(), ppc_linux_gregset(), ppc_supply_gregset(), regcache_raw_supply(), sparc32_supply_gregset(), sparc64_supply_gregset(), sparc_sol2_gregset, sparc_supply_gregset, and supply_gregset_reg().
Referenced by dec_thread_fetch_registers(), fetch_all_gp_regs(), fetch_core_registers(), fetch_inferior_registers(), fetch_regs(), ppcfbsd_fetch_inferior_registers(), procfs_fetch_registers(), ps_lsetregs(), and sol_thread_fetch_registers().