GDB (xrefs): /home/stan/gdb/src/gdb/hppa-tdep.h File Reference
/home/stan/gdb/src/gdb/hppa-tdep.h File Reference
Classes
struct gdbarch_tdep
struct unwind_table_entry
struct hppa_unwind_info
struct hppa_objfile_private
Defines
#define HPPA_INSN_SIZE 4
Enumerations
enum hppa_regnum {
HPPA_R0_REGNUM = 0, HPPA_R1_REGNUM = 1, HPPA_FLAGS_REGNUM = 0, HPPA_RP_REGNUM = 2,
HPPA_FP_REGNUM = 3, HPPA_DP_REGNUM = 27, HPPA_RET0_REGNUM = 28, HPPA_RET1_REGNUM = 29,
HPPA_SP_REGNUM = 30, HPPA_R31_REGNUM = 31, HPPA_SAR_REGNUM = 32, HPPA_IPSW_REGNUM = 41,
HPPA_PCOQ_HEAD_REGNUM = 33, HPPA_PCSQ_HEAD_REGNUM = 34, HPPA_PCOQ_TAIL_REGNUM = 35, HPPA_PCSQ_TAIL_REGNUM = 36,
HPPA_EIEM_REGNUM = 37, HPPA_IIR_REGNUM = 38, HPPA_ISR_REGNUM = 39, HPPA_IOR_REGNUM = 40,
HPPA_SR4_REGNUM = 43, HPPA_SR0_REGNUM = 44, HPPA_SR1_REGNUM = 45, HPPA_SR2_REGNUM = 46,
HPPA_SR3_REGNUM = 47, HPPA_SR5_REGNUM = 48, HPPA_SR6_REGNUM = 49, HPPA_SR7_REGNUM = 50,
HPPA_RCR_REGNUM = 51, HPPA_PID0_REGNUM = 52, HPPA_PID1_REGNUM = 53, HPPA_PID2_REGNUM = 55,
HPPA_PID3_REGNUM = 56, HPPA_CCR_REGNUM = 54, HPPA_TR0_REGNUM = 57, HPPA_CR26_REGNUM = 59,
HPPA_CR27_REGNUM = 60, HPPA_FP0_REGNUM = 64, HPPA_FP4_REGNUM = 72, HPPA64_FP4_REGNUM = 68,
HPPA_FP31R_REGNUM = 127, HPPA_ARG0_REGNUM = 26, HPPA_ARG1_REGNUM = 25, HPPA_ARG2_REGNUM = 24,
HPPA_ARG3_REGNUM = 23
}
enum unwind_stub_types {
LONG_BRANCH = 1, PARAMETER_RELOCATION = 2, EXPORT = 10, IMPORT = 11,
IMPORT_SHLIB = 12
}
Functions
struct unwind_table_entry * find_unwind_entry (CORE_ADDR)
int hppa_get_field (unsigned word, int from, int to)
int hppa_extract_5_load (unsigned int)
unsigned hppa_extract_5R_store (unsigned int)
unsigned hppa_extract_5r_store (unsigned int)
int hppa_extract_17 (unsigned int)
int hppa_extract_21 (unsigned)
int hppa_extract_14 (unsigned)
CORE_ADDR hppa_symbol_address (const char *sym)
struct value * hppa_frame_prev_register_helper (struct frame_info *this_frame, struct trad_frame_saved_reg *saved_regs, int regnum)
CORE_ADDR hppa_read_pc (struct regcache *regcache)
void hppa_write_pc (struct regcache *regcache, CORE_ADDR pc)
CORE_ADDR hppa_unwind_pc (struct gdbarch *gdbarch, struct frame_info *next_frame)
struct minimal_symbol * hppa_lookup_stub_minimal_symbol (const char *name, enum unwind_stub_types stub_type)
struct hppa_objfile_private * hppa_init_objfile_priv_data (struct objfile *objfile)
int hppa_in_solib_call_trampoline (struct gdbarch *gdbarch, CORE_ADDR pc)
CORE_ADDR hppa_skip_trampoline_code (struct frame_info *, CORE_ADDR pc)
Variables
struct objfile_data * hppa_objfile_priv_data
Define Documentation
#define HPPA_INSN_SIZE 4
Definition at line 82 of file hppa-tdep.h.
Referenced by hppa64_hpux_search_dummy_call_sequence(), hppa_hpux_search_pattern(), hppa_hpux_sigtramp_unwind_sniffer(), hppa_match_insns(), and hppa_match_insns_relaxed().
Enumeration Type Documentation
enum hppa_regnum
Enumerator:
HPPA_R0_REGNUM
HPPA_R1_REGNUM
HPPA_FLAGS_REGNUM
HPPA_RP_REGNUM
HPPA_FP_REGNUM
HPPA_DP_REGNUM
HPPA_RET0_REGNUM
HPPA_RET1_REGNUM
HPPA_SP_REGNUM
HPPA_R31_REGNUM
HPPA_SAR_REGNUM
HPPA_IPSW_REGNUM
HPPA_PCOQ_HEAD_REGNUM
HPPA_PCSQ_HEAD_REGNUM
HPPA_PCOQ_TAIL_REGNUM
HPPA_PCSQ_TAIL_REGNUM
HPPA_EIEM_REGNUM
HPPA_IIR_REGNUM
HPPA_ISR_REGNUM
HPPA_IOR_REGNUM
HPPA_SR4_REGNUM
HPPA_SR0_REGNUM
HPPA_SR1_REGNUM
HPPA_SR2_REGNUM
HPPA_SR3_REGNUM
HPPA_SR5_REGNUM
HPPA_SR6_REGNUM
HPPA_SR7_REGNUM
HPPA_RCR_REGNUM
HPPA_PID0_REGNUM
HPPA_PID1_REGNUM
HPPA_PID2_REGNUM
HPPA_PID3_REGNUM
HPPA_CCR_REGNUM
HPPA_TR0_REGNUM
HPPA_CR26_REGNUM
HPPA_CR27_REGNUM
HPPA_FP0_REGNUM
HPPA_FP4_REGNUM
HPPA64_FP4_REGNUM
HPPA_FP31R_REGNUM
HPPA_ARG0_REGNUM
HPPA_ARG1_REGNUM
HPPA_ARG2_REGNUM
HPPA_ARG3_REGNUM
Definition at line 29 of file hppa-tdep.h.
enum unwind_stub_types
Enumerator:
LONG_BRANCH
PARAMETER_RELOCATION
EXPORT
IMPORT
IMPORT_SHLIB
Definition at line 180 of file hppa-tdep.h.
Function Documentation
struct unwind_table_entry* find_unwind_entry (CORE_ADDR) [read]
Definition at line 455 of file hppa-tdep.c.
References _, ALL_OBJFILES, hppa_unwind_info::cache, error(), fprintf_unfiltered(), gdb_stdlog, hex_string(), hppa_debug, hppa_objfile_priv_data, hppa_unwind_info::last, read_unwind_info(), unwind_table_entry::region_start, and hppa_unwind_info::table.
Referenced by hppa32_hpux_in_solib_call_trampoline(), hppa32_hpux_search_dummy_call_sequence(), hppa_find_unwind_entry_in_block(), hppa_hpux_find_dummy_bpaddr(), hppa_hpux_find_import_stub_for_addr(), hppa_hpux_in_solib_return_trampoline(), hppa_hpux_sigtramp_unwind_sniffer(), hppa_hpux_skip_trampoline_code(), hppa_hpux_unwind_adjust_stub(), hppa_in_dyncall(), hppa_in_solib_call_trampoline(), hppa_lookup_stub_minimal_symbol(), hppa_stub_frame_unwind_cache(), skip_prologue_hard_way(), som_in_dynsym_resolve_code(), som_solib_desire_dynamic_linker_symbols(), and unwind_command().
int hppa_extract_14 (unsigned)
Definition at line 124 of file hppa-tdep.c.
References hppa_low_hppa_sign_extend(), and MASK_14.
Referenced by hppa_frame_cache(), hppa_in_function_epilogue_p(), hppa_skip_trampoline_code(), and prologue_inst_adjust_sp().
int hppa_extract_17 (unsigned int)
Definition at line 154 of file hppa-tdep.c.
References hppa_get_field(), and hppa_sign_extend().
Referenced by hppa_hpux_sigtramp_unwind_sniffer(), and hppa_hpux_skip_trampoline_code().
int hppa_extract_21 (unsigned)
Definition at line 132 of file hppa-tdep.c.
References hppa_get_field(), hppa_sign_extend(), and MASK_21.
Referenced by hppa_hpux_skip_trampoline_code(), hppa_skip_trampoline_code(), and prologue_inst_adjust_sp().
int hppa_extract_5_load (unsigned int)
Definition at line 100 of file hppa-tdep.c.
References hppa_low_hppa_sign_extend(), and MASK_5.
Referenced by prologue_inst_adjust_sp().
unsigned hppa_extract_5R_store (unsigned int)
Definition at line 116 of file hppa-tdep.c.
References MASK_5.
Referenced by inst_saves_fr(), and inst_saves_gr().
unsigned hppa_extract_5r_store (unsigned int)
Definition at line 108 of file hppa-tdep.c.
References MASK_5.
Referenced by inst_saves_fr().
struct value* hppa_frame_prev_register_helper (struct frame_info * this_frame, struct trad_frame_saved_reg * saved_regs, int regnum) [read]
int hppa_get_field (unsigned word, int from, int to)
Definition at line 92 of file hppa-tdep.c.
Referenced by hppa_extract_17(), and hppa_extract_21().
int hppa_in_solib_call_trampoline (struct gdbarch * gdbarch, CORE_ADDR pc)
Definition at line 2858 of file hppa-tdep.c.
References find_unwind_entry(), hppa_in_dyncall(), hppa_match_insns_relaxed(), HPPA_MAX_INSN_PATTERN_LEN, and in_plt_section().
Referenced by hppa_linux_init_abi(), and hppabsd_init_abi().
struct hppa_objfile_private* hppa_init_objfile_priv_data (struct objfile * objfile) [read]
Definition at line 175 of file hppa-tdep.c.
References hppa_objfile_priv_data, memset(), and objfile::objfile_obstack.
Referenced by hppa32_hpux_search_dummy_call_sequence(), hppa64_hpux_search_dummy_call_sequence(), and read_unwind_info().
struct minimal_symbol* hppa_lookup_stub_minimal_symbol (const char * name, enum unwind_stub_types stub_type) [read]
Definition at line 2467 of file hppa-tdep.c.
References ALL_MSYMBOLS, find_unwind_entry(), unwind_table_entry::stub_type, unwind_table_entry::stub_unwind, SYMBOL_LINKAGE_NAME, and SYMBOL_VALUE.
Referenced by som_solib_create_inferior_hook().
CORE_ADDR hppa_read_pc (struct regcache * regcache)
Definition at line 1279 of file hppa-tdep.c.
References HPPA_IPSW_REGNUM, HPPA_PCOQ_HEAD_REGNUM, regcache_cooked_read_unsigned(), and ULONGEST.
Referenced by hppa_gdbarch_init(), and hppa_hpux_read_pc().
CORE_ADDR hppa_skip_trampoline_code (struct frame_info * , CORE_ADDR pc)
Definition at line 2886 of file hppa-tdep.c.
References _, builtin_type::builtin_func_ptr, builtin_type(), get_frame_arch(), get_frame_register_unsigned(), HPPA_DP_REGNUM, hppa_extract_14(), hppa_extract_21(), hppa_in_dyncall(), hppa_match_insns(), HPPA_MAX_INSN_PATTERN_LEN, HPPA_R0_REGNUM, in_plt_section(), paddress(), read_memory_typed_address(), and warning().
Referenced by hppa_linux_init_abi(), and hppabsd_init_abi().
CORE_ADDR hppa_symbol_address (const char * sym)
Definition at line 163 of file hppa-tdep.c.
References lookup_minimal_symbol(), and SYMBOL_VALUE_ADDRESS.
Referenced by hppa32_hpux_in_solib_call_trampoline(), hppa32_hpux_search_dummy_call_sequence(), hppa_hpux_skip_trampoline_code(), hppa_hpux_unwind_adjust_stub(), and hppa_in_dyncall().
CORE_ADDR hppa_unwind_pc (struct gdbarch * gdbarch, struct frame_info * next_frame)
Definition at line 2444 of file hppa-tdep.c.
References frame_unwind_register_unsigned(), HPPA_IPSW_REGNUM, HPPA_PCOQ_HEAD_REGNUM, and ULONGEST.
Referenced by hppa_gdbarch_init(), and hppa_hpux_unwind_pc().
void hppa_write_pc (struct regcache * regcache, CORE_ADDR pc)
Definition at line 1299 of file hppa-tdep.c.
References HPPA_PCOQ_HEAD_REGNUM, HPPA_PCOQ_TAIL_REGNUM, and regcache_cooked_write_unsigned().
Referenced by hppa_gdbarch_init(), and hppa_hpux_write_pc().
Variable Documentation
struct objfile_data* hppa_objfile_priv_data
Definition at line 56 of file hppa-tdep.c.
Referenced by _initialize_hppa_tdep(), find_unwind_entry(), hppa32_hpux_search_dummy_call_sequence(), hppa64_hpux_search_dummy_call_sequence(), hppa_init_objfile_priv_data(), and read_unwind_info().