GDB (xrefs): /home/stan/gdb/src/gdb/hppanbsd-nat.c File Reference
/home/stan/gdb/src/gdb/hppanbsd-nat.c File Reference
#include "defs.h"
#include "inferior.h"
#include "regcache.h"
#include <sys/types.h>
#include <sys/ptrace.h>
#include <machine/reg.h>
#include "hppa-tdep.h"
#include "inf-ptrace.h"
#include "nbsd-nat.h"
Functions
static int hppanbsd_gregset_supplies_p (int regnum)
static int hppanbsd_fpregset_supplies_p (int regnum)
static void hppanbsd_supply_gregset (struct regcache *regcache, const void *gregs)
static void hppanbsd_supply_fpregset (struct regcache *regcache, const void *fpregs)
static void hppanbsd_collect_gregset (const struct regcache *regcache, void *gregs, int regnum)
static void hppanbsd_collect_fpregset (struct regcache *regcache, void *fpregs, int regnum)
static void hppanbsd_fetch_registers (struct target_ops *ops, struct regcache *regcache, int regnum)
static void hppanbsd_store_registers (struct target_ops *ops, struct regcache *regcache, int regnum)
void _initialize_hppanbsd_nat (void)
Function Documentation
void _initialize_hppanbsd_nat (void)
Definition at line 232 of file hppanbsd-nat.c.
References add_target(), hppanbsd_fetch_registers(), hppanbsd_store_registers(), inf_ptrace_target(), nbsd_pid_to_exec_file(), target_ops::to_fetch_registers, target_ops::to_pid_to_exec_file, and target_ops::to_store_registers.
static void hppanbsd_collect_fpregset (struct regcache * regcache, void * fpregs, int regnum) [static]
Definition at line 141 of file hppanbsd-nat.c.
References HPPA_FP0_REGNUM, HPPA_FP31R_REGNUM, regcache_raw_collect(), and gdbarch_tdep::regs.
Referenced by hppanbsd_store_registers().
static void hppanbsd_collect_gregset (const struct regcache * regcache, void * gregs, int regnum) [static]
Definition at line 93 of file hppanbsd-nat.c.
References HPPA_IPSW_REGNUM, HPPA_PCOQ_HEAD_REGNUM, HPPA_PCOQ_TAIL_REGNUM, HPPA_PCSQ_HEAD_REGNUM, HPPA_PCSQ_TAIL_REGNUM, HPPA_R1_REGNUM, HPPA_R31_REGNUM, HPPA_SAR_REGNUM, HPPA_SR4_REGNUM, regcache_raw_collect(), and gdbarch_tdep::regs.
Referenced by hppanbsd_store_registers().
static void hppanbsd_fetch_registers (struct target_ops * ops, struct regcache * regcache, int regnum) [static]
Definition at line 162 of file hppanbsd-nat.c.
References _, hppanbsd_fpregset_supplies_p(), hppanbsd_gregset_supplies_p(), hppanbsd_supply_fpregset(), hppanbsd_supply_gregset(), inferior_ptid, perror_with_name(), ptid_get_pid(), ptrace(), and PTRACE_TYPE_ARG3.
Referenced by _initialize_hppanbsd_nat().
static int hppanbsd_fpregset_supplies_p (int regnum) [static]
Definition at line 43 of file hppanbsd-nat.c.
References HPPA_FP0_REGNUM, and HPPA_FP31R_REGNUM.
Referenced by hppanbsd_fetch_registers(), and hppanbsd_store_registers().
static int hppanbsd_gregset_supplies_p (int regnum) [static]
Definition at line 34 of file hppanbsd-nat.c.
References HPPA_IPSW_REGNUM, HPPA_PCSQ_TAIL_REGNUM, HPPA_R0_REGNUM, HPPA_R31_REGNUM, HPPA_SAR_REGNUM, and HPPA_SR4_REGNUM.
Referenced by hppanbsd_fetch_registers(), and hppanbsd_store_registers().
static void hppanbsd_store_registers (struct target_ops * ops, struct regcache * regcache, int regnum) [static]
Definition at line 193 of file hppanbsd-nat.c.
References _, hppanbsd_collect_fpregset(), hppanbsd_collect_gregset(), hppanbsd_fpregset_supplies_p(), hppanbsd_gregset_supplies_p(), inferior_ptid, perror_with_name(), ptid_get_pid(), ptrace(), and PTRACE_TYPE_ARG3.
Referenced by _initialize_hppanbsd_nat().
static void hppanbsd_supply_fpregset (struct regcache * regcache, const void * fpregs) [static]
Definition at line 76 of file hppanbsd-nat.c.
References HPPA_FP0_REGNUM, HPPA_FP31R_REGNUM, regcache_raw_supply(), regnum, and gdbarch_tdep::regs.
Referenced by hppanbsd_fetch_registers().
static void hppanbsd_supply_gregset (struct regcache * regcache, const void * gregs) [static]
Definition at line 51 of file hppanbsd-nat.c.
References HPPA_IPSW_REGNUM, HPPA_PCOQ_HEAD_REGNUM, HPPA_PCOQ_TAIL_REGNUM, HPPA_PCSQ_HEAD_REGNUM, HPPA_PCSQ_TAIL_REGNUM, HPPA_R1_REGNUM, HPPA_R31_REGNUM, HPPA_SAR_REGNUM, HPPA_SR4_REGNUM, regcache_raw_supply(), regnum, and gdbarch_tdep::regs.
Referenced by hppanbsd_fetch_registers().