GDB (xrefs): /home/stan/gdb/src/gdb/hppabsd-nat.c File Reference
/home/stan/gdb/src/gdb/hppabsd-nat.c File Reference
#include "defs.h"
#include "inferior.h"
#include "regcache.h"
#include "target.h"
#include <sys/types.h>
#include <sys/ptrace.h>
#include <machine/reg.h>
#include "hppa-tdep.h"
#include "inf-ptrace.h"
Functions
static int hppabsd_gregset_supplies_p (int regnum)
static int hppabsd_fpregset_supplies_p (int regnum)
static void hppabsd_supply_gregset (struct regcache *regcache, const void *gregs)
static void hppabsd_supply_fpregset (struct regcache *regcache, const void *fpregs)
static void hppabsd_collect_gregset (const struct regcache *regcache, void *gregs, int regnum)
static void hppabsd_collect_fpregset (struct regcache *regcache, void *fpregs, int regnum)
static void hppabsd_fetch_registers (struct target_ops *ops, struct regcache *regcache, int regnum)
static void hppabsd_store_registers (struct target_ops *ops, struct regcache *regcache, int regnum)
void _initialize_hppabsd_nat (void)
Function Documentation
void _initialize_hppabsd_nat (void)
Definition at line 255 of file hppabsd-nat.c.
References add_target(), hppabsd_fetch_registers(), hppabsd_store_registers(), inf_ptrace_target(), target_ops::to_fetch_registers, and target_ops::to_store_registers.
static void hppabsd_collect_fpregset (struct regcache * regcache, void * fpregs, int regnum) [static]
Definition at line 166 of file hppabsd-nat.c.
References HPPA_FP0_REGNUM, HPPA_FP31R_REGNUM, and regcache_raw_collect().
Referenced by hppabsd_store_registers().
static void hppabsd_collect_gregset (const struct regcache * regcache, void * gregs, int regnum) [static]
Definition at line 104 of file hppabsd-nat.c.
References HPPA_CR26_REGNUM, HPPA_CR27_REGNUM, HPPA_IPSW_REGNUM, HPPA_PCOQ_HEAD_REGNUM, HPPA_PCOQ_TAIL_REGNUM, HPPA_PCSQ_HEAD_REGNUM, HPPA_PCSQ_TAIL_REGNUM, HPPA_R1_REGNUM, HPPA_R31_REGNUM, HPPA_SAR_REGNUM, HPPA_SR0_REGNUM, HPPA_SR1_REGNUM, HPPA_SR2_REGNUM, HPPA_SR3_REGNUM, HPPA_SR4_REGNUM, HPPA_SR5_REGNUM, HPPA_SR6_REGNUM, HPPA_SR7_REGNUM, and regcache_raw_collect().
Referenced by hppabsd_store_registers().
static void hppabsd_fetch_registers (struct target_ops * ops, struct regcache * regcache, int regnum) [static]
Definition at line 187 of file hppabsd-nat.c.
References _, hppabsd_fpregset_supplies_p(), hppabsd_gregset_supplies_p(), hppabsd_supply_fpregset(), hppabsd_supply_gregset(), inferior_ptid, perror_with_name(), ptid_get_pid(), ptrace(), and PTRACE_TYPE_ARG3.
Referenced by _initialize_hppabsd_nat().
static int hppabsd_fpregset_supplies_p (int regnum) [static]
Definition at line 39 of file hppabsd-nat.c.
References HPPA_FP0_REGNUM, and HPPA_FP31R_REGNUM.
Referenced by hppabsd_fetch_registers(), and hppabsd_store_registers().
static int hppabsd_gregset_supplies_p (int regnum) [static]
Definition at line 33 of file hppabsd-nat.c.
References HPPA_CR27_REGNUM, and HPPA_R0_REGNUM.
Referenced by hppabsd_fetch_registers(), and hppabsd_store_registers().
static void hppabsd_store_registers (struct target_ops * ops, struct regcache * regcache, int regnum) [static]
Definition at line 217 of file hppabsd-nat.c.
References _, hppabsd_collect_fpregset(), hppabsd_collect_gregset(), hppabsd_fpregset_supplies_p(), hppabsd_gregset_supplies_p(), inferior_ptid, perror_with_name(), ptid_get_pid(), ptrace(), and PTRACE_TYPE_ARG3.
Referenced by _initialize_hppabsd_nat().
static void hppabsd_supply_fpregset (struct regcache * regcache, const void * fpregs) [static]
Definition at line 87 of file hppabsd-nat.c.
References HPPA_FP0_REGNUM, HPPA_FP31R_REGNUM, regcache_raw_supply(), and regnum.
Referenced by hppabsd_fetch_registers().
static void hppabsd_supply_gregset (struct regcache * regcache, const void * gregs) [static]
Definition at line 47 of file hppabsd-nat.c.
References HPPA_CR26_REGNUM, HPPA_CR27_REGNUM, HPPA_IPSW_REGNUM, HPPA_PCOQ_HEAD_REGNUM, HPPA_PCOQ_TAIL_REGNUM, HPPA_PCSQ_HEAD_REGNUM, HPPA_PCSQ_TAIL_REGNUM, HPPA_R0_REGNUM, HPPA_R1_REGNUM, HPPA_R31_REGNUM, HPPA_SAR_REGNUM, HPPA_SR0_REGNUM, HPPA_SR1_REGNUM, HPPA_SR2_REGNUM, HPPA_SR3_REGNUM, HPPA_SR4_REGNUM, HPPA_SR5_REGNUM, HPPA_SR6_REGNUM, HPPA_SR7_REGNUM, regcache_raw_supply(), and regnum.
Referenced by hppabsd_fetch_registers().