GDB (xrefs): /home/stan/gdb/src/gdb/hppaobsd-tdep.c File Reference
/home/stan/gdb/src/gdb/hppaobsd-tdep.c File Reference
#include "defs.h"
#include "osabi.h"
#include "regcache.h"
#include "regset.h"
#include "gdb_assert.h"
#include "gdb_string.h"
#include "hppa-tdep.h"
#include "hppabsd-tdep.h"
Defines
#define HPPAOBSD_SIZEOF_GREGS (34 * 4) /* OpenBSD 5.1 and earlier. */
#define HPPANBSD_SIZEOF_GREGS (46 * 4) /* NetBSD and OpenBSD 5.2 and later. */
#define HPPAOBSD_SIZEOF_FPREGS (32 * 8)
#define GDB_OSABI_NETBSD_CORE GDB_OSABI_OPENBSD_ELF
Functions
static void hppaobsd_supply_gregset (const struct regset *regset, struct regcache *regcache, int regnum, const void *gregs, size_t len)
static void hppaobsd_supply_fpregset (const struct regset *regset, struct regcache *regcache, int regnum, const void *fpregs, size_t len)
static struct regset * hppaobsd_regset_from_core_section (struct gdbarch *gdbarch, const char *sect_name, size_t sect_size)
static void hppaobsd_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
static enum gdb_osabi hppaobsd_core_osabi_sniffer (bfd *abfd)
void _initialize_hppabsd_tdep (void)
Variables
static struct regset hppaobsd_gregset
static struct regset hppaobsd_fpregset
Define Documentation
#define GDB_OSABI_NETBSD_CORE GDB_OSABI_OPENBSD_ELF
Definition at line 177 of file hppaobsd-tdep.c.
Referenced by hppaobsd_core_osabi_sniffer().
#define HPPANBSD_SIZEOF_GREGS (46 * 4) /* NetBSD and OpenBSD 5.2 and later. */
Definition at line 35 of file hppaobsd-tdep.c.
Referenced by hppaobsd_supply_gregset().
#define HPPAOBSD_SIZEOF_FPREGS (32 * 8)
Definition at line 38 of file hppaobsd-tdep.c.
Referenced by hppaobsd_regset_from_core_section(), and hppaobsd_supply_fpregset().
#define HPPAOBSD_SIZEOF_GREGS (34 * 4) /* OpenBSD 5.1 and earlier. */
Definition at line 34 of file hppaobsd-tdep.c.
Referenced by hppaobsd_regset_from_core_section(), and hppaobsd_supply_gregset().
Function Documentation
void _initialize_hppabsd_tdep (void)
static enum gdb_osabi hppaobsd_core_osabi_sniffer (bfd * abfd) [static]
Definition at line 180 of file hppaobsd-tdep.c.
References GDB_OSABI_NETBSD_CORE, and GDB_OSABI_UNKNOWN.
static void hppaobsd_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch) [static]
Definition at line 164 of file hppaobsd-tdep.c.
References hppabsd_init_abi(), hppaobsd_regset_from_core_section(), and set_gdbarch_regset_from_core_section().
static struct regset* hppaobsd_regset_from_core_section (struct gdbarch * gdbarch, const char * sect_name, size_t sect_size) [static, read]
Definition at line 150 of file hppaobsd-tdep.c.
References hppaobsd_fpregset, hppaobsd_gregset, HPPAOBSD_SIZEOF_FPREGS, and HPPAOBSD_SIZEOF_GREGS.
Referenced by hppaobsd_init_abi().
static void hppaobsd_supply_fpregset (const struct regset * regset, struct regcache * regcache, int regnum, const void * fpregs, size_t len) [static]
Definition at line 115 of file hppaobsd-tdep.c.
References gdb_assert, get_regcache_arch(), HPPA_FP0_REGNUM, HPPA_FP31R_REGNUM, HPPAOBSD_SIZEOF_FPREGS, and regcache_raw_supply().
static void hppaobsd_supply_gregset (const struct regset * regset, struct regcache * regcache, int regnum, const void * gregs, size_t len) [static]
Definition at line 45 of file hppaobsd-tdep.c.
References gdb_assert, HPPA_CR26_REGNUM, HPPA_CR27_REGNUM, HPPA_IPSW_REGNUM, HPPA_PCOQ_HEAD_REGNUM, HPPA_PCOQ_TAIL_REGNUM, HPPA_PCSQ_HEAD_REGNUM, HPPA_PCSQ_TAIL_REGNUM, HPPA_R0_REGNUM, HPPA_R1_REGNUM, HPPA_R31_REGNUM, HPPA_SAR_REGNUM, HPPA_SR0_REGNUM, HPPA_SR1_REGNUM, HPPA_SR2_REGNUM, HPPA_SR3_REGNUM, HPPA_SR4_REGNUM, HPPA_SR5_REGNUM, HPPA_SR6_REGNUM, HPPA_SR7_REGNUM, HPPANBSD_SIZEOF_GREGS, HPPAOBSD_SIZEOF_GREGS, offset, and regcache_raw_supply().
Variable Documentation
struct regset hppaobsd_fpregset [static]
Initial value:
{
  NULL,
  hppaobsd_supply_fpregset
}
Definition at line 140 of file hppaobsd-tdep.c.
Referenced by hppaobsd_regset_from_core_section().
struct regset hppaobsd_gregset [static]
Initial value:
{
  NULL,
  hppaobsd_supply_gregset
}
Definition at line 134 of file hppaobsd-tdep.c.
Referenced by hppaobsd_regset_from_core_section().