GDB (xrefs): /home/stan/gdb/src/gdb/hppa-hpux-nat.c File Reference
/home/stan/gdb/src/gdb/hppa-hpux-nat.c File Reference
#include "defs.h"
#include "inferior.h"
#include "regcache.h"
#include "target.h"
#include "gdb_assert.h"
#include <sys/ptrace.h>
#include <sys/utsname.h>
#include <machine/save_state.h>
#include "hppa-tdep.h"
#include "solib-som.h"
#include "inf-ptrace.h"
#include "inf-ttrace.h"
Defines
#define PTRACE_TYPE_RET void
Functions
static LONGEST hppa_hpux_save_state_offset (struct regcache *regcache, int regnum)
static void hppa_hpux_fetch_register (struct regcache *regcache, int regnum)
static void hppa_hpux_fetch_inferior_registers (struct target_ops *ops, struct regcache *regcache, int regnum)
static void hppa_hpux_store_register (struct regcache *regcache, int regnum)
static void hppa_hpux_store_inferior_registers (struct target_ops *ops, struct regcache *regcache, int regnum)
static void set_hpux_major_release (void)
void _initialize_hppa_hpux_nat (void)
Define Documentation
#define PTRACE_TYPE_RET void
Definition at line 83 of file hppa-hpux-nat.c.
Referenced by fetch_ppc_memory(), fetch_ppc_register(), hppa_hpux_fetch_register(), hppa_hpux_store_register(), ia64_linux_fetch_register(), ia64_linux_store_register(), inf_ptrace_fetch_register(), inf_ptrace_store_register(), inf_ptrace_xfer_partial(), rs6000_xfer_partial(), and store_ppc_memory().
Function Documentation
void _initialize_hppa_hpux_nat (void)
Definition at line 258 of file hppa-hpux-nat.c.
References add_target(), hppa_hpux_fetch_inferior_registers(), hppa_hpux_store_inferior_registers(), inf_ptrace_target(), inf_ttrace_target(), set_hpux_major_release(), target_ops::to_fetch_registers, and target_ops::to_store_registers.
static void hppa_hpux_fetch_inferior_registers (struct target_ops * ops, struct regcache * regcache, int regnum) [static]
Definition at line 147 of file hppa-hpux-nat.c.
References gdbarch_num_regs(), get_regcache_arch(), and hppa_hpux_fetch_register().
Referenced by _initialize_hppa_hpux_nat().
static void hppa_hpux_fetch_register (struct regcache * regcache, int regnum) [static]
Definition at line 87 of file hppa-hpux-nat.c.
References _, gdbarch::byte_order, error(), extract_unsigned_integer(), flags, gdb_assert, gdbarch_byte_order(), gdbarch_register_name(), get_regcache_arch(), HPPA_FLAGS_REGNUM, hppa_hpux_save_state_offset(), inferior_ptid, ptid_get_lwp(), ptid_get_pid(), ptrace(), PTRACE_TYPE_ARG3, PTRACE_TYPE_RET, regcache_raw_supply(), register_size(), safe_strerror(), size, store_unsigned_integer(), and ULONGEST.
Referenced by hppa_hpux_fetch_inferior_registers().
static LONGEST hppa_hpux_save_state_offset (struct regcache * regcache, int regnum) [static]
Definition at line 45 of file hppa-hpux-nat.c.
References flags, gdb_assert, get_regcache_arch(), HPPA_FLAGS_REGNUM, HPPA_FP0_REGNUM, HPPA_R0_REGNUM, HPPA_R1_REGNUM, LONGEST, offset, regcache_cooked_read_unsigned(), register_size(), size, and ULONGEST.
Referenced by hppa_hpux_fetch_register(), and hppa_hpux_store_register().
static void hppa_hpux_store_inferior_registers (struct target_ops * ops, struct regcache * regcache, int regnum) [static]
Definition at line 225 of file hppa-hpux-nat.c.
References gdbarch_num_regs(), get_regcache_arch(), and hppa_hpux_store_register().
Referenced by _initialize_hppa_hpux_nat().
static void hppa_hpux_store_register (struct regcache * regcache, int regnum) [static]
Definition at line 162 of file hppa-hpux-nat.c.
References _, gdbarch::byte_order, error(), extract_unsigned_integer(), flags, gdb_assert, gdbarch_byte_order(), gdbarch_register_name(), get_regcache_arch(), HPPA_FLAGS_REGNUM, hppa_hpux_save_state_offset(), inferior_ptid, ptid_get_lwp(), ptid_get_pid(), ptrace(), PTRACE_TYPE_ARG3, PTRACE_TYPE_RET, regcache_raw_collect(), register_size(), safe_strerror(), size, store_unsigned_integer(), and ULONGEST.
Referenced by hppa_hpux_store_inferior_registers().
static void set_hpux_major_release (void) [static]
Definition at line 241 of file hppa-hpux-nat.c.
References hpux_major_release, p, and strchr().
Referenced by _initialize_hppa_hpux_nat().