GDB (xrefs): /home/stan/gdb/src/gdb/hppanbsd-tdep.c File Reference
/home/stan/gdb/src/gdb/hppanbsd-tdep.c File Reference
#include "defs.h"
#include "osabi.h"
#include "regcache.h"
#include "regset.h"
#include "trad-frame.h"
#include "tramp-frame.h"
#include "gdb_assert.h"
#include "gdb_string.h"
#include "hppa-tdep.h"
#include "hppabsd-tdep.h"
Defines
#define HPPANBSD_SIZEOF_GREGS (44 * 4)
Functions
static void hppanbsd_sigtramp_cache_init (const struct tramp_frame *, struct frame_info *, struct trad_frame_cache *, CORE_ADDR)
static void hppanbsd_supply_gregset (const struct regset *regset, struct regcache *regcache, int regnum, const void *gregs, size_t len)
static struct regset * hppanbsd_regset_from_core_section (struct gdbarch *gdbarch, const char *sect_name, size_t sect_size)
static void hppanbsd_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
void _initialize_hppanbsd_tdep (void)
Variables
static int hppanbsd_mc_reg_offset []
static struct tramp_frame hppanbsd_sigtramp_si4
static int hppanbsd_reg_offset []
static struct regset hppanbsd_gregset
initialize_file_ftype _initialize_hppanbsd_tdep
Define Documentation
#define HPPANBSD_SIZEOF_GREGS (44 * 4)
Definition at line 136 of file hppanbsd-tdep.c.
Referenced by hppanbsd_regset_from_core_section(), and hppanbsd_supply_gregset().
Function Documentation
void _initialize_hppanbsd_tdep (void)
Definition at line 221 of file hppanbsd-tdep.c.
References _initialize_hppanbsd_tdep, GDB_OSABI_NETBSD_ELF, gdbarch_register_osabi(), and hppanbsd_init_abi().
static void hppanbsd_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch) [static]
Definition at line 204 of file hppanbsd-tdep.c.
References hppabsd_init_abi(), hppanbsd_regset_from_core_section(), set_gdbarch_regset_from_core_section(), and tramp_frame_prepend_unwinder().
Referenced by _initialize_hppanbsd_tdep().
static struct regset* hppanbsd_regset_from_core_section (struct gdbarch * gdbarch, const char * sect_name, size_t sect_size) [static, read]
Definition at line 194 of file hppanbsd-tdep.c.
References hppanbsd_gregset, and HPPANBSD_SIZEOF_GREGS.
Referenced by hppanbsd_init_abi().
static void hppanbsd_sigtramp_cache_init (const struct tramp_frame * self, struct frame_info * this_frame, struct trad_frame_cache * this_cache, CORE_ADDR func) [static]
Definition at line 102 of file hppanbsd-tdep.c.
References frame_id_build(), gdbarch_tdep(), get_frame_arch(), get_frame_register_unsigned(), HPPA_SP_REGNUM, hppanbsd_mc_reg_offset, gdbarch_tdep::num_regs, reg_offset, gdbarch_tdep::sp, trad_frame_set_id(), and trad_frame_set_reg_addr().
static void hppanbsd_supply_gregset (const struct regset * regset, struct regcache * regcache, int regnum, const void * gregs, size_t len) [static]
Definition at line 167 of file hppanbsd-tdep.c.
References gdb_assert, hppanbsd_reg_offset, HPPANBSD_SIZEOF_GREGS, regcache_raw_supply(), and gdbarch_tdep::regs.
Variable Documentation
initialize_file_ftype _initialize_hppanbsd_tdep
Referenced by _initialize_hppanbsd_tdep(), and initialize_all_files().
struct regset hppanbsd_gregset [static]
Initial value:
{
  NULL,
  hppanbsd_supply_gregset
}
Definition at line 184 of file hppanbsd-tdep.c.
Referenced by hppanbsd_regset_from_core_section().
int hppanbsd_mc_reg_offset[] [static]
Definition at line 35 of file hppanbsd-tdep.c.
Referenced by hppanbsd_sigtramp_cache_init().
int hppanbsd_reg_offset[] [static]
Initial value:
{
      -1,   1 * 4,   2 * 4,   3 * 4,
   4 * 4,   5 * 4,   6 * 4,   7 * 4,
   8 * 4,   9 * 4,  10 * 4,  11 * 4,
  12 * 4,  13 * 4,  14 * 4,  15 * 4,
  16 * 4,  17 * 4,  18 * 4,  19 * 4,
  20 * 4,  21 * 4,  22 * 4,  23 * 4,
  24 * 4,  25 * 4,  26 * 4,  27 * 4,
  28 * 4,  29 * 4,  30 * 4,  31 * 4,
  32 * 4,
  35 * 4,
  33 * 4,
  36 * 4,
  34 * 4,
  -1,
  -1,
  -1,
  -1,
  0 * 4,
}
Definition at line 138 of file hppanbsd-tdep.c.
Referenced by hppanbsd_supply_gregset().
struct tramp_frame hppanbsd_sigtramp_si4 [static]
Initial value:
{
  SIGTRAMP_FRAME,
  4,
  {
    { 0xc7d7c012, -1 },
    { 0xd6e01c1e, -1 },
    { 0x0ee81093, -1 },
    { 0x0ee01097, -1 },
    { 0xe8404000, -1 },
    { 0xeae0c002, -1 },
    { 0x08000240, -1 },
    { 0x0803025a, -1 },
    { 0x20200801, -1 },
    { 0xe420e008, -1 },
    { 0x34160268, -1 },
    { 0x081c025a, -1 },
    { 0x20200801, -1 },
    { 0xe420e008, -1 },
    { 0x34160002, -1 },
    { TRAMP_SENTINEL_INSN, -1 }
  },
  hppanbsd_sigtramp_cache_init
}
Definition at line 72 of file hppanbsd-tdep.c.