GDB (xrefs): /home/stan/gdb/src/gdb/i386bsd-nat.h File Reference
/home/stan/gdb/src/gdb/i386bsd-nat.h File Reference
Functions
struct target_ops * i386bsd_target (void)
void i386bsd_dr_set_control (unsigned long control)
void i386bsd_dr_set_addr (int regnum, CORE_ADDR addr)
CORE_ADDR i386bsd_dr_get_addr (int regnum)
unsigned long i386bsd_dr_get_status (void)
unsigned long i386bsd_dr_get_control (void)
Function Documentation
CORE_ADDR i386bsd_dr_get_addr (int regnum)
Referenced by _initialize_i386fbsd_nat().
unsigned long i386bsd_dr_get_control (void)
Referenced by _initialize_i386fbsd_nat().
unsigned long i386bsd_dr_get_status (void)
Referenced by _initialize_i386fbsd_nat().
void i386bsd_dr_set_addr (int regnum, CORE_ADDR addr)
Referenced by _initialize_i386fbsd_nat().
void i386bsd_dr_set_control (unsigned long control)
Referenced by _initialize_i386fbsd_nat().
struct target_ops* i386bsd_target (void) [read]
Definition at line 245 of file i386bsd-nat.c.
References i386bsd_fetch_inferior_registers(), i386bsd_store_inferior_registers(), inf_ptrace_target(), target_ops::to_fetch_registers, and target_ops::to_store_registers.
Referenced by _initialize_i386fbsd_nat(), _initialize_i386nbsd_nat(), and _initialize_i386obsd_nat().