GDB (xrefs): /home/stan/gdb/src/gdb/i386fbsd-tdep.c File Reference
/home/stan/gdb/src/gdb/i386fbsd-tdep.c File Reference
#include "defs.h"
#include "arch-utils.h"
#include "gdbcore.h"
#include "osabi.h"
#include "regcache.h"
#include "gdb_assert.h"
#include "i386-tdep.h"
#include "i387-tdep.h"
#include "bsd-uthread.h"
#include "solib-svr4.h"
Functions
static void i386fbsd_supply_uthread (struct regcache *regcache, int regnum, CORE_ADDR addr)
static void i386fbsd_collect_uthread (const struct regcache *regcache, int regnum, CORE_ADDR addr)
static void i386fbsdaout_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
static void i386fbsd_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
static void i386fbsd4_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
void _initialize_i386fbsd_tdep (void)
Variables
static int i386fbsd_r_reg_offset []
CORE_ADDR i386fbsd_sigtramp_start_addr = 0xbfbfdf20
CORE_ADDR i386fbsd_sigtramp_end_addr = 0xbfbfdff0
int i386fbsd_sc_reg_offset []
static int i386fbsd_jmp_buf_reg_offset []
static int i386fbsd4_r_reg_offset []
int i386fbsd4_sc_reg_offset []
Function Documentation
void _initialize_i386fbsd_tdep (void)
static void i386fbsd4_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch) [static]
Definition at line 205 of file i386fbsd-tdep.c.
References gdbarch_tdep(), gdbarch_tdep::gregset_num_regs, gdbarch_tdep::gregset_reg_offset, i386fbsd4_r_reg_offset, i386fbsd4_sc_reg_offset, i386fbsd_init_abi(), gdbarch_tdep::sc_num_regs, gdbarch_tdep::sc_reg_offset, and gdbarch_tdep::sizeof_gregset.
static void i386fbsd_collect_uthread (const struct regcache * regcache, int regnum, CORE_ADDR addr) [static]
Definition at line 106 of file i386fbsd-tdep.c.
References gdb_assert, i386fbsd_jmp_buf_reg_offset, regcache_raw_collect(), and write_memory().
Referenced by i386fbsdaout_init_abi().
static void i386fbsd_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch) [static]
Definition at line 157 of file i386fbsd-tdep.c.
References i386_elf_init_abi(), i386fbsdaout_init_abi(), set_solib_svr4_fetch_link_map_offsets(), and svr4_ilp32_fetch_link_map_offsets().
Referenced by i386fbsd4_init_abi().
static void i386fbsd_supply_uthread (struct regcache * regcache, int regnum, CORE_ADDR addr) [static]
Definition at line 86 of file i386fbsd-tdep.c.
References gdb_assert, i386fbsd_jmp_buf_reg_offset, read_memory(), and regcache_raw_supply().
Referenced by i386fbsdaout_init_abi().
static void i386fbsdaout_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch) [static]
Definition at line 126 of file i386fbsd-tdep.c.
References bsd_uthread_set_collect_uthread(), bsd_uthread_set_supply_uthread(), gdbarch_tdep(), gdbarch_tdep::gregset_num_regs, gdbarch_tdep::gregset_reg_offset, i386bsd_init_abi(), i386fbsd_collect_uthread(), i386fbsd_r_reg_offset, i386fbsd_sc_reg_offset, i386fbsd_sigtramp_end_addr, i386fbsd_sigtramp_start_addr, i386fbsd_supply_uthread(), reg_struct_return, gdbarch_tdep::sc_num_regs, gdbarch_tdep::sc_reg_offset, gdbarch_tdep::sigtramp_end, gdbarch_tdep::sigtramp_start, gdbarch_tdep::sizeof_fpregset, gdbarch_tdep::sizeof_gregset, and gdbarch_tdep::struct_return.
Referenced by i386fbsd_init_abi().
Variable Documentation
int i386fbsd4_r_reg_offset[] [static]
Initial value:
{
  10 * 4, 9 * 4, 8 * 4, 7 * 4,
  16 * 4, 5 * 4,
  4 * 4, 3 * 4,
  13 * 4, 15 * 4,
  14 * 4, 17 * 4,
  2 * 4, 1 * 4, 0 * 4, 18 * 4
}
Definition at line 173 of file i386fbsd-tdep.c.
Referenced by i386fbsd4_init_abi().
int i386fbsd4_sc_reg_offset[]
Initial value:
{
  20 + 11 * 4,
  20 + 10 * 4,
  20 + 9 * 4,
  20 + 8 * 4,
  20 + 17 * 4,
  20 + 6 * 4,
  20 + 5 * 4,
  20 + 4 * 4,
  20 + 14 * 4,
  20 + 16 * 4,
  20 + 15 * 4,
  20 + 18 * 4,
  20 + 3 * 4,
  20 + 2 * 4,
  20 + 1 * 4,
  20 + 0 * 4
}
Definition at line 184 of file i386fbsd-tdep.c.
Referenced by i386fbsd4_init_abi().
int i386fbsd_jmp_buf_reg_offset[] [static]
Initial value:
{
  -1,
  -1,
  -1,
  1 * 4,
  2 * 4,
  3 * 4,
  4 * 4,
  5 * 4,
  0 * 4
}
Definition at line 72 of file i386fbsd-tdep.c.
Referenced by i386fbsd_collect_uthread(), and i386fbsd_supply_uthread().
int i386fbsd_r_reg_offset[] [static]
Initial value:
{
  9 * 4, 8 * 4, 7 * 4, 6 * 4,
  15 * 4, 4 * 4,
  3 * 4, 2 * 4,
  12 * 4, 14 * 4,
  13 * 4, 16 * 4,
  1 * 4, 0 * 4, -1, -1
}
Definition at line 36 of file i386fbsd-tdep.c.
Referenced by i386fbsdaout_init_abi().
int i386fbsd_sc_reg_offset[]
Initial value:
{
  8 + 14 * 4,
  8 + 13 * 4,
  8 + 12 * 4,
  8 + 11 * 4,
  8 + 0 * 4,
  8 + 1 * 4,
  8 + 10 * 4,
  8 + 9 * 4,
  8 + 3 * 4,
  8 + 4 * 4,
  8 + 7 * 4,
  8 + 8 * 4,
  8 + 6 * 4,
  8 + 5 * 4,
  8 + 15 * 4,
  8 + 16 * 4
}
Definition at line 51 of file i386fbsd-tdep.c.
Referenced by i386fbsdaout_init_abi().
CORE_ADDR i386fbsd_sigtramp_end_addr = 0xbfbfdff0
Definition at line 48 of file i386fbsd-tdep.c.
Referenced by _initialize_i386fbsd_nat(), and i386fbsdaout_init_abi().
CORE_ADDR i386fbsd_sigtramp_start_addr = 0xbfbfdf20
Definition at line 47 of file i386fbsd-tdep.c.
Referenced by _initialize_i386fbsd_nat(), and i386fbsdaout_init_abi().