GDB (xrefs): /home/stan/gdb/src/gdb/i386-sol2-tdep.c File Reference
/home/stan/gdb/src/gdb/i386-sol2-tdep.c File Reference
#include "defs.h"
#include "value.h"
#include "osabi.h"
#include "gdb_string.h"
#include "sol2-tdep.h"
#include "i386-tdep.h"
#include "solib-svr4.h"
Functions
static int i386_sol2_sigtramp_p (struct frame_info *this_frame)
static CORE_ADDR i386_sol2_mcontext_addr (struct frame_info *this_frame)
static const char * i386_sol2_static_transform_name (const char *name)
static void i386_sol2_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
static enum gdb_osabi i386_sol2_osabi_sniffer (bfd *abfd)
void _initialize_i386_sol2_tdep (void)
Variables
static int i386_sol2_gregset_reg_offset []
Function Documentation
void _initialize_i386_sol2_tdep (void)
static void i386_sol2_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch) [static]
Definition at line 105 of file i386-sol2-tdep.c.
References gdbarch_tdep(), gdbarch_tdep::gregset_num_regs, gdbarch_tdep::gregset_reg_offset, i386_sol2_gregset_reg_offset, i386_sol2_mcontext_addr(), i386_sol2_sigtramp_p(), i386_sol2_static_transform_name(), i386_svr4_init_abi(), gdbarch_tdep::sc_num_regs, gdbarch_tdep::sc_reg_offset, set_gdbarch_core_pid_to_str(), set_gdbarch_skip_solib_resolver(), set_gdbarch_sofun_address_maybe_missing(), set_gdbarch_static_transform_name(), set_solib_svr4_fetch_link_map_offsets(), gdbarch_tdep::sigcontext_addr, gdbarch_tdep::sigtramp_p, gdbarch_tdep::sizeof_fpregset, gdbarch_tdep::sizeof_gregset, sol2_core_pid_to_str(), sol2_skip_solib_resolver(), and svr4_ilp32_fetch_link_map_offsets().
static CORE_ADDR i386_sol2_mcontext_addr (struct frame_info * this_frame) [static]
Definition at line 69 of file i386-sol2-tdep.c.
References get_frame_memory_unsigned(), get_frame_register_unsigned(), I386_ESP_REGNUM, and sp.
Referenced by i386_sol2_init_abi().
static enum gdb_osabi i386_sol2_osabi_sniffer (bfd * abfd) [static]
Definition at line 144 of file i386-sol2-tdep.c.
References GDB_OSABI_SOLARIS, and GDB_OSABI_UNKNOWN.
static int i386_sol2_sigtramp_p (struct frame_info * this_frame) [static]
Definition at line 55 of file i386-sol2-tdep.c.
References find_pc_partial_function(), get_frame_pc(), and name.
Referenced by i386_sol2_init_abi().
static const char* i386_sol2_static_transform_name (const char * name) [static]
Definition at line 83 of file i386-sol2-tdep.c.
References name, p, and strrchr().
Referenced by i386_sol2_init_abi().
Variable Documentation
int i386_sol2_gregset_reg_offset[] [static]
Initial value:
{
  11 * 4,
  10 * 4,
  9 * 4,
  8 * 4,
  17 * 4,
  6 * 4,
  5 * 4,
  4 * 4,
  14 * 4,
  16 * 4,
  15 * 4,
  18 * 4,
  3 * 4,
  2 * 4,
  1 * 4,
  0 * 4
}
Definition at line 31 of file i386-sol2-tdep.c.
Referenced by i386_sol2_init_abi().