GDB (xrefs): /home/stan/gdb/src/gdb/i386nbsd-tdep.c File Reference
/home/stan/gdb/src/gdb/i386nbsd-tdep.c File Reference
#include "defs.h"
#include "arch-utils.h"
#include "frame.h"
#include "gdbcore.h"
#include "regcache.h"
#include "regset.h"
#include "osabi.h"
#include "symtab.h"
#include "trad-frame.h"
#include "tramp-frame.h"
#include "gdb_assert.h"
#include "gdb_string.h"
#include "i386-tdep.h"
#include "i387-tdep.h"
#include "nbsd-tdep.h"
#include "solib-svr4.h"
Functions
static void i386nbsd_sigtramp_cache_init (const struct tramp_frame *, struct frame_info *, struct trad_frame_cache *, CORE_ADDR)
static void i386nbsd_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
static void i386nbsdelf_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
void _initialize_i386nbsd_tdep (void)
Variables
static int i386nbsd_r_reg_offset []
int i386nbsd_sc_reg_offset []
int i386nbsd_mc_reg_offset []
static struct tramp_frame i386nbsd_sigtramp_sc16
static struct tramp_frame i386nbsd_sigtramp_sc2
static struct tramp_frame i386nbsd_sigtramp_si2
static struct tramp_frame i386nbsd_sigtramp_si31
static struct tramp_frame i386nbsd_sigtramp_si4
initialize_file_ftype _initialize_i386nbsd_tdep
Function Documentation
void _initialize_i386nbsd_tdep (void)
Definition at line 327 of file i386nbsd-tdep.c.
References _initialize_i386nbsd_tdep, GDB_OSABI_NETBSD_ELF, gdbarch_register_osabi(), and i386nbsdelf_init_abi().
static void i386nbsd_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch) [static]
Definition at line 272 of file i386nbsd-tdep.c.
References gdbarch_tdep(), gdbarch_tdep::gregset_num_regs, gdbarch_tdep::gregset_reg_offset, i386bsd_init_abi(), i386nbsd_r_reg_offset, reg_struct_return, gdbarch_tdep::sc_num_regs, gdbarch_tdep::sc_reg_offset, gdbarch_tdep::sigcontext_addr, gdbarch_tdep::sigtramp_end, gdbarch_tdep::sigtramp_p, gdbarch_tdep::sigtramp_start, gdbarch_tdep::sizeof_gregset, gdbarch_tdep::struct_return, and tramp_frame_prepend_unwinder().
Referenced by i386nbsdelf_init_abi().
static void i386nbsd_sigtramp_cache_init (const struct tramp_frame * self, struct frame_info * this_frame, struct trad_frame_cache * this_cache, CORE_ADDR func) [static]
Definition at line 229 of file i386nbsd-tdep.c.
References frame_id_build(), gdbarch_byte_order(), gdbarch_tdep(), get_frame_arch(), get_frame_register_unsigned(), I386_ESP_REGNUM, i386nbsd_mc_reg_offset, i386nbsd_sc_reg_offset, gdbarch_tdep::num_regs, read_memory_unsigned_integer(), reg_offset, gdbarch_tdep::sp, trad_frame_set_id(), and trad_frame_set_reg_addr().
static void i386nbsdelf_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch) [static]
Definition at line 305 of file i386nbsd-tdep.c.
References gdbarch_tdep(), i386_elf_init_abi(), i386nbsd_init_abi(), pcc_struct_return, set_solib_svr4_fetch_link_map_offsets(), gdbarch_tdep::struct_return, and svr4_ilp32_fetch_link_map_offsets().
Referenced by _initialize_i386nbsd_tdep().
Variable Documentation
initialize_file_ftype _initialize_i386nbsd_tdep
Referenced by _initialize_i386nbsd_tdep(), and initialize_all_files().
int i386nbsd_mc_reg_offset[]
Initial value:
{
  11 * 4,
  10 * 4,
  9 * 4,
  8 * 4,
  7 * 4,
  6 * 4,
  5 * 4,
  4 * 4,
  14 * 4,
  16 * 4,
  15 * 4,
  18 * 4,
  3 * 4,
  2 * 4,
  1 * 4,
  0 * 4
}
Definition at line 82 of file i386nbsd-tdep.c.
Referenced by i386nbsd_sigtramp_cache_init().
int i386nbsd_r_reg_offset[] [static]
Initial value:
{
  0 * 4,
  1 * 4,
  2 * 4,
  3 * 4,
  4 * 4,
  5 * 4,
  6 * 4,
  7 * 4,
  8 * 4,
  9 * 4,
  10 * 4,
  11 * 4,
  12 * 4,
  13 * 4,
  14 * 4,
  15 * 4
}
Definition at line 40 of file i386nbsd-tdep.c.
Referenced by i386nbsd_init_abi().
int i386nbsd_sc_reg_offset[]
Initial value:
{
  10 * 4,
  9 * 4,
  8 * 4,
  7 * 4,
  14 * 4,
  6 * 4,
  5 * 4,
  4 * 4,
  11 * 4,
  13 * 4,
  12 * 4,
  15 * 4,
  3 * 4,
  2 * 4,
  1 * 4,
  0 * 4
}
Definition at line 61 of file i386nbsd-tdep.c.
Referenced by i386nbsd_sigtramp_cache_init().
struct tramp_frame i386nbsd_sigtramp_sc16 [static]
Initial value:
{
  SIGTRAMP_FRAME,
  1,
  {
    { 0x8d, -1 }, { 0x44, -1 }, { 0x24, -1 }, { 0x10, -1 },
    { 0x50, -1 },
    { 0x50, -1 },
    { 0xb8, -1 }, { 0x27, -1 }, {0x01, -1 }, {0x00, -1 }, {0x00, -1 },
    { 0xcd, -1 }, { 0x80, -1},
    { 0xb8, -1 }, { 0x01, -1 }, {0x00, -1 }, {0x00, -1 }, {0x00, -1 },
    { 0xcd, -1 }, { 0x80, -1},
    { TRAMP_SENTINEL_INSN, -1 }
  },
  i386nbsd_sigtramp_cache_init
}
Definition at line 107 of file i386nbsd-tdep.c.
struct tramp_frame i386nbsd_sigtramp_sc2 [static]
Initial value:
{
  SIGTRAMP_FRAME,
  1,
  {
    { 0x8d, -1 }, { 0x44, -1 }, { 0x24, -1 }, { 0x0c, -1 },
    { 0x89, -1 }, { 0x44, -1 }, { 0x24, -1 }, { 0x04, -1 },
    { 0xb8, -1 }, { 0x27, -1 }, {0x01, -1 }, {0x00, -1 }, {0x00, -1 },
    { 0xcd, -1 }, { 0x80, -1},
    { 0x89, -1 }, { 0x44, -1 }, { 0x24, -1 }, { 0x04, -1 },
    { 0xb8, -1 }, { 0x01, -1 }, {0x00, -1 }, {0x00, -1 }, {0x00, -1 },
    { 0xcd, -1 }, { 0x80, -1},
    { TRAMP_SENTINEL_INSN, -1 }
  },
  i386nbsd_sigtramp_cache_init
}
Definition at line 129 of file i386nbsd-tdep.c.
struct tramp_frame i386nbsd_sigtramp_si2 [static]
Initial value:
{
  SIGTRAMP_FRAME,
  1,
  {
    { 0x8b, -1 }, { 0x44, -1 }, { 0x24, -1 }, { 0x08, -1 },
    { 0x89, -1 }, { 0x44, -1 }, { 0x24, -1 }, { 0x04, -1 },
    { 0xb8, -1 }, { 0x34, -1 }, { 0x01, -1 }, { 0x00, -1 }, { 0x00, -1 },
    { 0xcd, -1 }, { 0x80, -1 },
    { 0x89, -1 }, { 0x44, -1 }, { 0x24, -1 }, { 0x04, -1 },
    { 0xb8, -1 }, { 0x01, -1 }, { 0x00, -1 }, { 0x00, -1 }, { 0x00, -1 },
    { 0xcd, -1 }, { 0x80, -1 },
    { TRAMP_SENTINEL_INSN, -1 }
  },
  i386nbsd_sigtramp_cache_init
}
Definition at line 153 of file i386nbsd-tdep.c.
struct tramp_frame i386nbsd_sigtramp_si31 [static]
Initial value:
{
  SIGTRAMP_FRAME,
  1,
  {
    { 0x8d, -1 }, { 0x84, -1 }, { 0x24, -1 },
        { 0x8c, -1 }, { 0x00, -1 }, { 0x00, -1 }, { 0x00, -1 },
    { 0x89, -1 }, { 0x44, -1 }, { 0x24, -1 }, { 0x04, -1 },
    { 0xb8, -1 }, { 0x34, -1 }, { 0x01, -1 }, { 0x00, -1 }, { 0x00, -1 },
    { 0xcd, -1 }, { 0x80, -1},
    { 0x89, -1 }, { 0x44, -1 }, { 0x24, -1 }, { 0x04, -1 },
    { 0xb8, -1 }, { 0x01, -1 }, {0x00, -1 }, {0x00, -1 }, {0x00, -1 },
    { 0xcd, -1 }, { 0x80, -1},
    { TRAMP_SENTINEL_INSN, -1 }
  },
  i386nbsd_sigtramp_cache_init
}
Definition at line 177 of file i386nbsd-tdep.c.
struct tramp_frame i386nbsd_sigtramp_si4 [static]
Initial value:
{
  SIGTRAMP_FRAME,
  1,
  {
    { 0x8d, -1 }, { 0x84, -1 }, { 0x24, -1 },
        { 0x8c, -1 }, { 0x00, -1 }, { 0x00, -1 }, { 0x00, -1 },
    { 0x89, -1 }, { 0x44, -1 }, { 0x24, -1 }, { 0x04, -1 },
    { 0xb8, -1 }, { 0x34, -1 }, { 0x01, -1 }, { 0x00, -1 }, { 0x00, -1 },
    { 0xcd, -1 }, { 0x80, -1},
    { 0xc7, -1 }, { 0x44, -1 }, { 0x24, -1 }, { 0x04, -1 },
        { 0xff, -1 }, { 0xff, -1 }, { 0xff, -1 }, { 0xff, -1 },
    { 0xb8, -1 }, { 0x01, -1 }, {0x00, -1 }, {0x00, -1 }, {0x00, -1 },
    { 0xcd, -1 }, { 0x80, -1},
    { TRAMP_SENTINEL_INSN, -1 }
  },
  i386nbsd_sigtramp_cache_init
}
Definition at line 202 of file i386nbsd-tdep.c.