GDB (xrefs): /home/stan/gdb/src/gdb/i386fbsd-nat.c File Reference
/home/stan/gdb/src/gdb/i386fbsd-nat.c File Reference
#include "defs.h"
#include "inferior.h"
#include "regcache.h"
#include "target.h"
#include <sys/types.h>
#include <sys/ptrace.h>
#include <sys/sysctl.h>
#include "fbsd-nat.h"
#include "i386-tdep.h"
#include "i386-nat.h"
#include "i386bsd-nat.h"
#include <machine/pcb.h>
#include "bsd-kvm.h"
Functions
static void i386fbsd_resume (struct target_ops *ops, ptid_t ptid, int step, enum gdb_signal signal)
static int i386fbsd_supply_pcb (struct regcache *regcache, struct pcb *pcb)
void _initialize_i386fbsd_nat (void)
Function Documentation
void _initialize_i386fbsd_nat (void)
Definition at line 123 of file i386fbsd-nat.c.
References add_target(), bsd_kvm_add_target(), fbsd_find_memory_regions(), fbsd_make_corefile_notes(), fbsd_pid_to_exec_file(), i386_dr_low_type::get_addr, i386_dr_low_type::get_control, i386_dr_low_type::get_status, i386_dr_low, i386_set_debug_register_length(), i386_use_watchpoints(), i386bsd_dr_get_addr(), i386bsd_dr_get_control(), i386bsd_dr_get_status(), i386bsd_dr_set_addr(), i386bsd_dr_set_control(), i386bsd_target(), i386fbsd_resume(), i386fbsd_sigtramp_end_addr, i386fbsd_sigtramp_start_addr, i386fbsd_supply_pcb(), len, i386_dr_low_type::set_addr, i386_dr_low_type::set_control, target_ops::to_find_memory_regions, target_ops::to_make_corefile_notes, target_ops::to_pid_to_exec_file, and target_ops::to_resume.
static void i386fbsd_resume (struct target_ops * ops, ptid_t ptid, int step, enum gdb_signal signal) [static]
Definition at line 38 of file i386fbsd-nat.c.
References gdb_signal_to_host(), get_current_regcache(), I386_EFLAGS_REGNUM, inferior_ptid, perror_with_name(), PT_CONTINUE, PT_STEP, ptid_get_pid(), ptrace(), regcache_cooked_read_unsigned(), regcache_cooked_write_unsigned(), and ULONGEST.
Referenced by _initialize_i386fbsd_nat().
static int i386fbsd_supply_pcb (struct regcache * regcache, struct pcb * pcb) [static]
Definition at line 91 of file i386fbsd-nat.c.
References I386_EBP_REGNUM, I386_EBX_REGNUM, I386_EDI_REGNUM, I386_EIP_REGNUM, I386_ESI_REGNUM, I386_ESP_REGNUM, I386_GS_REGNUM, and regcache_raw_supply().
Referenced by _initialize_i386fbsd_nat().