GDB (xrefs): /home/stan/gdb/src/gdb/i386-tdep.h File Reference
/home/stan/gdb/src/gdb/i386-tdep.h File Reference
Classes
struct gdbarch_tdep
Defines
#define I386_NUM_GREGS 16
#define I386_NUM_XREGS 9
#define I386_SSE_NUM_REGS (I386_MXCSR_REGNUM + 1)
#define I386_AVX_NUM_REGS (I386_YMM7H_REGNUM + 1)
#define I386_MAX_REGISTER_SIZE 16
#define I386_SEL_RPL 0x0003 /* Requester's Privilege Level mask. */
#define I386_SEL_UPL 0x0003 /* User Privilige Level. */
#define I386_SEL_KPL 0x0000 /* Kernel Privilige Level. */
#define I386_MAX_INSN_LEN (16)
Enumerations
enum struct_return {
pcc_struct_return, reg_struct_return, pcc_struct_return, reg_struct_return,
pcc_struct_return, reg_struct_return
}
enum i386_regnum {
I386_EAX_REGNUM, I386_ECX_REGNUM, I386_EDX_REGNUM, I386_EBX_REGNUM,
I386_ESP_REGNUM, I386_EBP_REGNUM, I386_ESI_REGNUM, I386_EDI_REGNUM,
I386_EIP_REGNUM, I386_EFLAGS_REGNUM, I386_CS_REGNUM, I386_SS_REGNUM,
I386_DS_REGNUM, I386_ES_REGNUM, I386_FS_REGNUM, I386_GS_REGNUM,
I386_ST0_REGNUM, I386_MXCSR_REGNUM = 40, I386_YMM0H_REGNUM, I386_YMM7H_REGNUM = I386_YMM0H_REGNUM + 7
}
enum record_i386_regnum {
X86_RECORD_REAX_REGNUM, X86_RECORD_RECX_REGNUM, X86_RECORD_REDX_REGNUM, X86_RECORD_REBX_REGNUM,
X86_RECORD_RESP_REGNUM, X86_RECORD_REBP_REGNUM, X86_RECORD_RESI_REGNUM, X86_RECORD_REDI_REGNUM,
X86_RECORD_R8_REGNUM, X86_RECORD_R9_REGNUM, X86_RECORD_R10_REGNUM, X86_RECORD_R11_REGNUM,
X86_RECORD_R12_REGNUM, X86_RECORD_R13_REGNUM, X86_RECORD_R14_REGNUM, X86_RECORD_R15_REGNUM,
X86_RECORD_REIP_REGNUM, X86_RECORD_EFLAGS_REGNUM, X86_RECORD_CS_REGNUM, X86_RECORD_SS_REGNUM,
X86_RECORD_DS_REGNUM, X86_RECORD_ES_REGNUM, X86_RECORD_FS_REGNUM, X86_RECORD_GS_REGNUM
}
Functions
int i386_fp_regnum_p (struct gdbarch *, int)
int i386_fpc_regnum_p (struct gdbarch *, int)
struct type * i387_ext_type (struct gdbarch *gdbarch)
int i386_byte_regnum_p (struct gdbarch *gdbarch, int regnum)
int i386_word_regnum_p (struct gdbarch *gdbarch, int regnum)
int i386_dword_regnum_p (struct gdbarch *gdbarch, int regnum)
int i386_xmm_regnum_p (struct gdbarch *gdbarch, int regnum)
int i386_ymm_regnum_p (struct gdbarch *gdbarch, int regnum)
const char * i386_pseudo_register_name (struct gdbarch *gdbarch, int regnum)
struct type * i386_pseudo_register_type (struct gdbarch *gdbarch, int regnum)
void i386_pseudo_register_read_into_value (struct gdbarch *gdbarch, struct regcache *regcache, int regnum, struct value *result)
void i386_pseudo_register_write (struct gdbarch *gdbarch, struct regcache *regcache, int regnum, const gdb_byte *buf)
CORE_ADDR i386_pe_skip_trampoline_code (struct frame_info *frame, CORE_ADDR pc, char *name)
CORE_ADDR i386_skip_main_prologue (struct gdbarch *gdbarch, CORE_ADDR pc)
int i386_sigtramp_p (struct frame_info *this_frame)
int i386_register_reggroup_p (struct gdbarch *gdbarch, int regnum, struct reggroup *group)
void i386_supply_gregset (const struct regset *regset, struct regcache *regcache, int regnum, const void *gregs, size_t len)
void i386_collect_gregset (const struct regset *regset, const struct regcache *regcache, int regnum, void *gregs, size_t len)
struct regset * i386_regset_from_core_section (struct gdbarch *gdbarch, const char *sect_name, size_t sect_size)
struct displaced_step_closure * i386_displaced_step_copy_insn (struct gdbarch *gdbarch, CORE_ADDR from, CORE_ADDR to, struct regcache *regs)
void i386_displaced_step_fixup (struct gdbarch *gdbarch, struct displaced_step_closure *closure, CORE_ADDR from, CORE_ADDR to, struct regcache *regs)
void i386_elf_init_abi (struct gdbarch_info, struct gdbarch *)
void i386_svr4_init_abi (struct gdbarch_info, struct gdbarch *)
int i386_process_record (struct gdbarch *gdbarch, struct regcache *regcache, CORE_ADDR addr)
void i386bsd_init_abi (struct gdbarch_info, struct gdbarch *)
int i386_stap_is_single_operand (struct gdbarch *gdbarch, const char *s)
int i386_stap_parse_special_token (struct gdbarch *gdbarch, struct stap_parse_info *p)
Variables
CORE_ADDR i386fbsd_sigtramp_start_addr
CORE_ADDR i386fbsd_sigtramp_end_addr
CORE_ADDR i386obsd_sigtramp_start_addr
CORE_ADDR i386obsd_sigtramp_end_addr
int i386fbsd4_sc_reg_offset []
int i386fbsd_sc_reg_offset []
int i386nbsd_sc_reg_offset []
int i386obsd_sc_reg_offset []
int i386bsd_sc_reg_offset []
Define Documentation
#define I386_AVX_NUM_REGS (I386_YMM7H_REGNUM + 1)
Definition at line 252 of file i386-tdep.h.
Referenced by i386_gdbarch_init().
#define I386_MAX_INSN_LEN (16)
Definition at line 288 of file i386-tdep.h.
Referenced by i386_gdbarch_init(), and i386_relocate_instruction().
#define I386_MAX_REGISTER_SIZE 16
Definition at line 255 of file i386-tdep.h.
Referenced by i386_extract_return_value(), i386_store_return_value(), i387_collect_xsave(), i387_register_to_value(), and i387_value_to_register().
#define I386_NUM_GREGS 16
Definition at line 248 of file i386-tdep.h.
Referenced by fill_gregset(), gnu_fetch_registers(), gnu_store_registers(), i386_darwin_fetch_inferior_registers(), i386_darwin_store_inferior_registers(), i386_gdbarch_init(), i386nto_regset_id(), and supply_gregset().
#define I386_NUM_XREGS 9
Definition at line 249 of file i386-tdep.h.
Referenced by i386_darwin_init_abi(), and i386_gdbarch_init().
#define I386_SEL_KPL 0x0000 /* Kernel Privilige Level. */
Definition at line 284 of file i386-tdep.h.
#define I386_SEL_RPL 0x0003 /* Requester's Privilege Level mask. */
Definition at line 282 of file i386-tdep.h.
Referenced by amd64obsd_trapframe_cache(), amd64obsd_trapframe_sniffer(), i386obsd_trapframe_cache(), and i386obsd_trapframe_sniffer().
#define I386_SEL_UPL 0x0003 /* User Privilige Level. */
Definition at line 283 of file i386-tdep.h.
Referenced by amd64obsd_trapframe_cache(), amd64obsd_trapframe_sniffer(), i386obsd_trapframe_cache(), and i386obsd_trapframe_sniffer().
#define I386_SSE_NUM_REGS (I386_MXCSR_REGNUM + 1)
Definition at line 251 of file i386-tdep.h.
Referenced by i386_darwin_fetch_inferior_registers(), i386_darwin_init_abi(), i386_darwin_store_inferior_registers(), and i386nto_regset_id().
Enumeration Type Documentation
enum i386_regnum
Enumerator:
I386_EAX_REGNUM
I386_ECX_REGNUM
I386_EDX_REGNUM
I386_EBX_REGNUM
I386_ESP_REGNUM
I386_EBP_REGNUM
I386_ESI_REGNUM
I386_EDI_REGNUM
I386_EIP_REGNUM
I386_EFLAGS_REGNUM
I386_CS_REGNUM
I386_SS_REGNUM
I386_DS_REGNUM
I386_ES_REGNUM
I386_FS_REGNUM
I386_GS_REGNUM
I386_ST0_REGNUM
I386_MXCSR_REGNUM
I386_YMM0H_REGNUM
I386_YMM7H_REGNUM
Definition at line 194 of file i386-tdep.h.
enum record_i386_regnum
Enumerator:
X86_RECORD_REAX_REGNUM
X86_RECORD_RECX_REGNUM
X86_RECORD_REDX_REGNUM
X86_RECORD_REBX_REGNUM
X86_RECORD_RESP_REGNUM
X86_RECORD_REBP_REGNUM
X86_RECORD_RESI_REGNUM
X86_RECORD_REDI_REGNUM
X86_RECORD_R8_REGNUM
X86_RECORD_R9_REGNUM
X86_RECORD_R10_REGNUM
X86_RECORD_R11_REGNUM
X86_RECORD_R12_REGNUM
X86_RECORD_R13_REGNUM
X86_RECORD_R14_REGNUM
X86_RECORD_R15_REGNUM
X86_RECORD_REIP_REGNUM
X86_RECORD_EFLAGS_REGNUM
X86_RECORD_CS_REGNUM
X86_RECORD_SS_REGNUM
X86_RECORD_DS_REGNUM
X86_RECORD_ES_REGNUM
X86_RECORD_FS_REGNUM
X86_RECORD_GS_REGNUM
Definition at line 220 of file i386-tdep.h.
enum struct_return
Enumerator:
pcc_struct_return
reg_struct_return
pcc_struct_return
reg_struct_return
pcc_struct_return
reg_struct_return
Definition at line 49 of file i386-tdep.h.
Function Documentation
int i386_byte_regnum_p (struct gdbarch * gdbarch, int regnum)
Definition at line 143 of file i386-tdep.c.
References gdbarch_tdep::al_regnum, gdbarch_tdep(), and gdbarch_tdep::num_byte_regs.
Referenced by amd64_pseudo_register_name(), amd64_pseudo_register_read_value(), amd64_pseudo_register_write(), i386_pseudo_register_name(), i386_pseudo_register_read_into_value(), i386_pseudo_register_type(), i386_pseudo_register_write(), and i386_register_reggroup_p().
void i386_collect_gregset (const struct regset * regset, const struct regcache * regcache, int regnum, void * gregs, size_t len)
Definition at line 3218 of file i386-tdep.c.
References regset::arch, gdb_assert, gdbarch_tdep(), gdbarch_tdep::gregset_num_regs, gdbarch_tdep::gregset_reg_offset, regcache_raw_collect(), gdbarch_tdep::regs, and gdbarch_tdep::sizeof_gregset.
Referenced by i386_regset_from_core_section(), i386_windows_regset_from_core_section(), and i386nto_supply_gregset().
struct displaced_step_closure* i386_displaced_step_copy_insn (struct gdbarch * gdbarch, CORE_ADDR from, CORE_ADDR to, struct regcache * regs) [read]
Definition at line 550 of file i386-tdep.c.
References debug_displaced, displaced_step_dump_bytes(), fprintf_unfiltered(), gdb_stdlog, gdbarch_max_insn_length(), i386_skip_prefixes(), i386_syscall_p(), len, paddress(), read_memory(), write_memory(), and xmalloc().
Referenced by i386_linux_displaced_step_copy_insn().
void i386_displaced_step_fixup (struct gdbarch * gdbarch, struct displaced_step_closure * closure, CORE_ADDR from, CORE_ADDR to, struct regcache * regs)
Definition at line 587 of file i386-tdep.c.
References debug_displaced, fprintf_unfiltered(), from, gdb_stdlog, gdbarch_byte_order(), gdbarch_max_insn_length(), i386_absolute_call_p(), i386_absolute_jmp_p(), i386_call_p(), I386_EIP_REGNUM, I386_ESP_REGNUM, i386_ret_p(), i386_skip_prefixes(), i386_syscall_p(), paddress(), read_memory_unsigned_integer(), regcache_cooked_read_unsigned(), regcache_cooked_write_unsigned(), ULONGEST, and write_memory_unsigned_integer().
Referenced by i386_linux_init_abi().
int i386_dword_regnum_p (struct gdbarch * gdbarch, int regnum)
Definition at line 165 of file i386-tdep.c.
References gdbarch_tdep::eax_regnum, gdbarch_tdep(), and gdbarch_tdep::num_dword_regs.
Referenced by amd64_pseudo_register_name(), amd64_pseudo_register_read_value(), amd64_pseudo_register_write(), i386_pseudo_register_type(), and i386_register_reggroup_p().
void i386_elf_init_abi (struct gdbarch_info , struct gdbarch *)
Definition at line 3772 of file i386-tdep.c.
References i386_stap_is_single_operand(), i386_stap_parse_special_token(), i386_svr4_reg_to_regnum(), set_gdbarch_stab_reg_to_regnum(), set_gdbarch_stap_integer_prefix(), set_gdbarch_stap_is_single_operand(), set_gdbarch_stap_parse_special_token(), set_gdbarch_stap_register_indirection_prefix(), set_gdbarch_stap_register_indirection_suffix(), and set_gdbarch_stap_register_prefix().
Referenced by i386_linux_init_abi(), i386_svr4_init_abi(), i386fbsd_init_abi(), i386gnu_init_abi(), i386nbsdelf_init_abi(), i386nto_init_abi(), and i386obsd_elf_init_abi().
int i386_fp_regnum_p (struct gdbarch * , int)
Definition at line 234 of file i386-tdep.c.
References gdbarch_tdep(), I387_FCTRL_REGNUM, and I387_ST0_REGNUM.
Referenced by fetch_register(), i386_process_record(), i386_register_reggroup_p(), i386_register_to_value(), i386_value_to_register(), i387_convert_register_p(), i387_register_to_value(), i387_value_to_register(), and store_register().
int i386_fpc_regnum_p (struct gdbarch * , int)
Definition at line 246 of file i386-tdep.c.
References gdbarch_tdep(), I387_FCTRL_REGNUM, I387_ST0_REGNUM, and I387_XMM0_REGNUM.
Referenced by fetch_register(), i386_process_record(), i386_register_reggroup_p(), and store_register().
CORE_ADDR i386_pe_skip_trampoline_code (struct frame_info * frame, CORE_ADDR pc, char * name)
Definition at line 3342 of file i386-tdep.c.
References gdbarch::byte_order, gdbarch_byte_order(), get_frame_arch(), lookup_minimal_symbol_by_pc(), bound_minimal_symbol::minsym, read_memory_unsigned_integer(), and SYMBOL_LINKAGE_NAME.
Referenced by i386_cygwin_skip_trampoline_code().
int i386_process_record (struct gdbarch * gdbarch, struct regcache * regcache, CORE_ADDR addr)
Definition at line 4342 of file i386-tdep.c.
References _, i386_record_s::addr, i386_record_s::aflag, i386_record_s::dflag, extract_unsigned_integer(), fprintf_unfiltered(), gdb_stdlog, i386_record_s::gdbarch, gdbarch_byte_order(), gdbarch_tdep(), I386_EAX_REGNUM, i386_fp_regnum_p(), i386_fpc_regnum_p(), gdbarch_tdep::i386_intx80_record, i386_mmx_regnum_p(), i386_mxcsr_regnum_p(), i386_record_floats(), I386_RECORD_FULL_ARCH_LIST_ADD_REG, i386_record_lea_modrm(), i386_record_lea_modrm_addr(), i386_record_modrm(), i386_record_push(), I386_SAVE_FPU_ENV, I386_SAVE_FPU_ENV_REG_STACK, I386_SAVE_FPU_REGS, gdbarch_tdep::i386_syscall_record, gdbarch_tdep::i386_sysenter_record, i386_xmm_regnum_p(), I387_FCTRL_REGNUM, I387_FTAG_REGNUM, I387_MM0_REGNUM, I387_MXCSR_REGNUM, I387_ST0_REGNUM, I387_XMM0_REGNUM, MAX_REGISTER_SIZE, memset(), i386_record_s::mod, i386_record_s::modrm, OP_CMPL, i386_record_s::orig_addr, i386_record_s::ot, OT_BYTE, OT_DQUAD, OT_LONG, OT_QUAD, OT_WORD, i386_record_s::override, paddress(), i386_record_s::popl_esp_hack, PREFIX_ADDR, PREFIX_DATA, PREFIX_LOCK, PREFIX_REPNZ, PREFIX_REPZ, printf_unfiltered(), record_debug, record_full_arch_list_add_end(), record_full_arch_list_add_mem(), record_full_arch_list_add_reg(), record_full_memory_query, record_read_memory(), gdbarch_tdep::record_regmap, i386_record_s::reg, i386_record_s::regcache, regcache_raw_read_unsigned(), i386_record_s::regmap, regnum, i386_record_s::rex_b, i386_record_s::rex_x, i386_record_s::rip_offset, i386_record_s::rm, target_terminal_inferior(), target_terminal_ours, ULONGEST, X86_RECORD_CS_REGNUM, X86_RECORD_DS_REGNUM, X86_RECORD_EFLAGS_REGNUM, X86_RECORD_ES_REGNUM, X86_RECORD_FS_REGNUM, X86_RECORD_GS_REGNUM, X86_RECORD_R8_REGNUM, X86_RECORD_REAX_REGNUM, X86_RECORD_REBP_REGNUM, X86_RECORD_REBX_REGNUM, X86_RECORD_RECX_REGNUM, X86_RECORD_REDI_REGNUM, X86_RECORD_REDX_REGNUM, X86_RECORD_REIP_REGNUM, X86_RECORD_RESI_REGNUM, X86_RECORD_RESP_REGNUM, X86_RECORD_SS_REGNUM, and yquery().
Referenced by amd64_linux_init_abi_common(), and i386_linux_init_abi().
const char* i386_pseudo_register_name (struct gdbarch * gdbarch, int regnum)
Definition at line 273 of file i386-tdep.c.
References _, gdbarch_tdep::al_regnum, gdbarch_tdep::ax_regnum, gdbarch_tdep(), i386_byte_names, i386_byte_regnum_p(), i386_mmx_names, i386_mmx_regnum_p(), i386_word_names, i386_word_regnum_p(), i386_ymm_names, i386_ymm_regnum_p(), I387_MM0_REGNUM, internal_error(), and gdbarch_tdep::ymm0_regnum.
Referenced by amd64_pseudo_register_name(), and i386_gdbarch_init().
void i386_pseudo_register_read_into_value (struct gdbarch * gdbarch, struct regcache * regcache, int regnum, struct value * result)
Definition at line 2896 of file i386-tdep.c.
References _, gdbarch_tdep::al_regnum, gdbarch_tdep::ax_regnum, gdbarch_tdep(), i386_byte_regnum_p(), i386_mmx_regnum_p(), i386_mmx_regnum_to_fp_regnum(), i386_word_regnum_p(), i386_ymm_regnum_p(), I387_XMM0_REGNUM, internal_error(), mark_value_bytes_unavailable(), MAX_REGISTER_SIZE, memcpy(), REG_VALID, regcache_raw_read(), register_size(), exsummary::status, TYPE_LENGTH, value_contents_raw(), value_type(), gdbarch_tdep::ymm0_regnum, and gdbarch_tdep::ymm0h_regnum.
Referenced by amd64_pseudo_register_read_value(), and i386_pseudo_register_read_value().
struct type* i386_pseudo_register_type (struct gdbarch * gdbarch, int regnum) [read]
Definition at line 2852 of file i386-tdep.c.
References _, builtin_type::builtin_int16, builtin_type::builtin_int32, builtin_type::builtin_int8, builtin_type(), i386_byte_regnum_p(), i386_dword_regnum_p(), i386_mmx_regnum_p(), i386_mmx_type(), i386_word_regnum_p(), i386_ymm_regnum_p(), i386_ymm_type(), and internal_error().
Referenced by amd64_x32_pseudo_register_type(), and i386_gdbarch_init().
void i386_pseudo_register_write (struct gdbarch * gdbarch, struct regcache * regcache, int regnum, const gdb_byte * buf)
Definition at line 2994 of file i386-tdep.c.
References _, gdbarch_tdep::al_regnum, gdbarch_tdep::ax_regnum, gdbarch_tdep(), i386_byte_regnum_p(), i386_mmx_regnum_p(), i386_mmx_regnum_to_fp_regnum(), i386_word_regnum_p(), i386_ymm_regnum_p(), I387_XMM0_REGNUM, internal_error(), MAX_REGISTER_SIZE, memcpy(), regcache_raw_read(), regcache_raw_write(), register_size(), gdbarch_tdep::ymm0_regnum, and gdbarch_tdep::ymm0h_regnum.
Referenced by amd64_pseudo_register_write(), and i386_gdbarch_init().
int i386_register_reggroup_p (struct gdbarch * gdbarch, int regnum, struct reggroup * group)
Definition at line 3864 of file i386-tdep.c.
References all_reggroup, default_register_reggroup_p(), float_reggroup, gdbarch_tdep(), general_reggroup, i386_byte_regnum_p(), i386_dword_regnum_p(), i386_fp_regnum_p(), i386_fpc_regnum_p(), i386_mmx_regnum_p(), i386_mxcsr_regnum_p(), i386_word_regnum_p(), i386_xmm_regnum_p(), I386_XSTATE_AVX, I386_XSTATE_AVX_MASK, I386_XSTATE_SSE_MASK, i386_ymm_regnum_p(), i386_ymmh_regnum_p(), vector_reggroup, and gdbarch_tdep::xcr0.
Referenced by amd64_linux_register_reggroup_p(), i386_gdbarch_init(), and i386_linux_register_reggroup_p().
struct regset* i386_regset_from_core_section (struct gdbarch * gdbarch, const char * sect_name, size_t sect_size) [read]
Definition at line 3302 of file i386-tdep.c.
References gdbarch_tdep::fpregset, gdbarch_tdep(), gdbarch_tdep::gregset, i386_collect_fpregset(), i386_collect_gregset(), i386_collect_xstateregset(), i386_supply_fpregset(), i386_supply_gregset(), i386_supply_xstateregset(), I387_SIZEOF_FXSAVE, regset_alloc(), gdbarch_tdep::sizeof_fpregset, gdbarch_tdep::sizeof_gregset, and gdbarch_tdep::xstateregset.
Referenced by amd64_regset_from_core_section(), and i386_gdbarch_init().
int i386_sigtramp_p (struct frame_info * this_frame)
Definition at line 3373 of file i386-tdep.c.
References find_pc_partial_function(), get_frame_pc(), and name.
Referenced by darwin_dwarf_signal_frame_p(), i386_darwin_init_abi(), i386_gdbarch_init(), and x86_darwin_init_abi_64().
CORE_ADDR i386_skip_main_prologue (struct gdbarch * gdbarch, CORE_ADDR pc)
Definition at line 1675 of file i386-tdep.c.
References extract_signed_integer(), gdbarch_byte_order(), lookup_minimal_symbol_by_pc(), bound_minimal_symbol::minsym, SYMBOL_LINKAGE_NAME, and target_read_memory().
Referenced by i386_cygwin_init_abi().
int i386_stap_is_single_operand (struct gdbarch * gdbarch, const char * s)
Definition at line 3445 of file i386-tdep.c.
Referenced by amd64_init_abi(), and i386_elf_init_abi().
int i386_stap_parse_special_token (struct gdbarch * gdbarch, struct stap_parse_info * p)
Definition at line 3457 of file i386-tdep.c.
References _, stap_parse_info::arg, stap_parse_info::arg_type, error(), len, stoken::length, lookup_pointer_type(), offset, stoken::ptr, stap_parse_info::saved_arg, size, user_reg_map_name_to_regnum(), write_exp_elt_longcst(), write_exp_elt_opcode(), write_exp_elt_type(), and write_exp_string().
Referenced by amd64_init_abi(), and i386_elf_init_abi().
void i386_supply_gregset (const struct regset * regset, struct regcache * regcache, int regnum, const void * gregs, size_t len)
Definition at line 3195 of file i386-tdep.c.
References regset::arch, gdb_assert, gdbarch_tdep(), gdbarch_tdep::gregset_num_regs, gdbarch_tdep::gregset_reg_offset, regcache_raw_supply(), gdbarch_tdep::regs, and gdbarch_tdep::sizeof_gregset.
Referenced by amd64obsd_supply_regset(), i386_regset_from_core_section(), i386_windows_regset_from_core_section(), i386nto_supply_gregset(), and i386obsd_aout_supply_regset().
void i386_svr4_init_abi (struct gdbarch_info , struct gdbarch *)
Definition at line 3791 of file i386-tdep.c.
References find_solib_trampoline_target(), gdbarch_tdep(), i386_elf_init_abi(), i386_svr4_sigcontext_addr(), i386_svr4_sigtramp_p(), gdbarch_tdep::jb_pc_offset, gdbarch_tdep::sc_pc_offset, gdbarch_tdep::sc_sp_offset, set_gdbarch_skip_trampoline_code(), gdbarch_tdep::sigcontext_addr, and gdbarch_tdep::sigtramp_p.
Referenced by i386_sol2_init_abi().
int i386_word_regnum_p (struct gdbarch * gdbarch, int regnum)
Definition at line 154 of file i386-tdep.c.
References gdbarch_tdep::ax_regnum, gdbarch_tdep(), and gdbarch_tdep::num_word_regs.
Referenced by amd64_pseudo_register_name(), i386_pseudo_register_name(), i386_pseudo_register_read_into_value(), i386_pseudo_register_type(), i386_pseudo_register_write(), and i386_register_reggroup_p().
int i386_xmm_regnum_p (struct gdbarch * gdbarch, int regnum)
Definition at line 208 of file i386-tdep.c.
References gdbarch_tdep(), I387_NUM_XMM_REGS, I387_XMM0_REGNUM, and gdbarch_tdep::num_xmm_regs.
Referenced by amd64_dwarf_reg_to_regnum(), i386_dbx_reg_to_regnum(), i386_process_record(), and i386_register_reggroup_p().
int i386_ymm_regnum_p (struct gdbarch * gdbarch, int regnum)
Definition at line 193 of file i386-tdep.c.
References gdbarch_tdep(), gdbarch_tdep::num_ymm_regs, and gdbarch_tdep::ymm0_regnum.
Referenced by amd64_pseudo_register_name(), i386_pseudo_register_name(), i386_pseudo_register_read_into_value(), i386_pseudo_register_type(), i386_pseudo_register_write(), and i386_register_reggroup_p().
void i386bsd_init_abi (struct gdbarch_info , struct gdbarch *)
Definition at line 77 of file i386bsd-tdep.c.
References gdbarch_tdep(), i386bsd_sc_reg_offset, i386bsd_sigcontext_addr(), gdbarch_tdep::jb_pc_offset, gdbarch_tdep::sc_num_regs, gdbarch_tdep::sc_reg_offset, gdbarch_tdep::sigcontext_addr, gdbarch_tdep::sigtramp_end, and gdbarch_tdep::sigtramp_start.
Referenced by amd64fbsd_init_abi(), i386fbsdaout_init_abi(), i386nbsd_init_abi(), and i386obsd_init_abi().
struct type* i387_ext_type (struct gdbarch * gdbarch) [read]
Definition at line 2740 of file i386-tdep.c.
References gdb_assert, gdbarch_tdep(), gdbarch_tdep::i387_ext_type, and tdesc_find_type().
Referenced by i386_extract_return_value(), i386_store_return_value(), i387_convert_register_p(), i387_register_to_value(), i387_value_to_register(), and print_i387_value().
Variable Documentation
int i386bsd_sc_reg_offset[]
Definition at line 56 of file i386bsd-tdep.c.
Referenced by i386bsd_init_abi().
int i386fbsd4_sc_reg_offset[]
Definition at line 184 of file i386fbsd-tdep.c.
Referenced by i386fbsd4_init_abi().
int i386fbsd_sc_reg_offset[]
Definition at line 51 of file i386fbsd-tdep.c.
Referenced by i386fbsdaout_init_abi().
CORE_ADDR i386fbsd_sigtramp_end_addr
Definition at line 48 of file i386fbsd-tdep.c.
Referenced by _initialize_i386fbsd_nat(), and i386fbsdaout_init_abi().
CORE_ADDR i386fbsd_sigtramp_start_addr
Definition at line 47 of file i386fbsd-tdep.c.
Referenced by _initialize_i386fbsd_nat(), and i386fbsdaout_init_abi().
int i386nbsd_sc_reg_offset[]
Definition at line 61 of file i386nbsd-tdep.c.
Referenced by i386nbsd_sigtramp_cache_init().
int i386obsd_sc_reg_offset[]
Definition at line 181 of file i386obsd-tdep.c.
Referenced by i386obsd_init_abi().
CORE_ADDR i386obsd_sigtramp_end_addr
Definition at line 178 of file i386obsd-tdep.c.
Referenced by _initialize_i386obsd_nat(), and i386obsd_init_abi().
CORE_ADDR i386obsd_sigtramp_start_addr
Definition at line 177 of file i386obsd-tdep.c.
Referenced by _initialize_i386obsd_nat(), and i386obsd_init_abi().