GDB (xrefs): /home/stan/gdb/src/gdb/i386-darwin-tdep.c File Reference
/home/stan/gdb/src/gdb/i386-darwin-tdep.c File Reference
#include "defs.h"
#include "frame.h"
#include "inferior.h"
#include "gdbcore.h"
#include "target.h"
#include "floatformat.h"
#include "symtab.h"
#include "regcache.h"
#include "libbfd.h"
#include "objfiles.h"
#include "i387-tdep.h"
#include "i386-tdep.h"
#include "osabi.h"
#include "ui-out.h"
#include "gdb_assert.h"
#include "i386-darwin-tdep.h"
#include "solib.h"
#include "solib-darwin.h"
#include "dwarf2-frame.h"
Functions
static CORE_ADDR i386_darwin_sigcontext_addr (struct frame_info *this_frame)
int darwin_dwarf_signal_frame_p (struct gdbarch *gdbarch, struct frame_info *this_frame)
static int i386_m128_p (struct type *type)
static int i386_darwin_arg_type_alignment (struct type *type)
static CORE_ADDR i386_darwin_push_dummy_call (struct gdbarch *gdbarch, struct value *function, struct regcache *regcache, CORE_ADDR bp_addr, int nargs, struct value **args, CORE_ADDR sp, int struct_return, CORE_ADDR struct_addr)
static void i386_darwin_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
static enum gdb_osabi i386_mach_o_osabi_sniffer (bfd *abfd)
void _initialize_i386_darwin_tdep (void)
Variables
int i386_darwin_thread_state_reg_offset []
const int i386_darwin_thread_state_num_regs
initialize_file_ftype _initialize_i386_darwin_tdep
Function Documentation
void _initialize_i386_darwin_tdep (void)
Definition at line 293 of file i386-darwin-tdep.c.
References _initialize_i386_darwin_tdep, GDB_OSABI_DARWIN, gdbarch_register_osabi(), gdbarch_register_osabi_sniffer(), i386_darwin_init_abi(), and i386_mach_o_osabi_sniffer().
int darwin_dwarf_signal_frame_p (struct gdbarch * gdbarch, struct frame_info * this_frame)
Definition at line 105 of file i386-darwin-tdep.c.
References i386_sigtramp_p().
Referenced by i386_darwin_init_abi(), and x86_darwin_init_abi_64().
static int i386_darwin_arg_type_alignment (struct type * type) [static]
Definition at line 123 of file i386-darwin-tdep.c.
References check_typedef(), max, TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_STRUCT, TYPE_CODE_UNION, TYPE_FIELD_TYPE, TYPE_LENGTH, TYPE_NFIELDS, and TYPE_VECTOR.
Referenced by i386_darwin_push_dummy_call().
static void i386_darwin_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch) [static]
Definition at line 249 of file i386-darwin-tdep.c.
References darwin_dwarf_signal_frame_p(), darwin_so_ops, dwarf2_frame_set_signal_frame_p(), gdbarch_tdep(), i386_darwin_push_dummy_call(), i386_darwin_sigcontext_addr(), i386_darwin_thread_state_num_regs, i386_darwin_thread_state_reg_offset, I386_NUM_XREGS, i386_sigtramp_p(), I386_SSE_NUM_REGS, gdbarch_tdep::jb_pc_offset, gdbarch_tdep::num_xmm_regs, reg_struct_return, gdbarch_tdep::sc_num_regs, gdbarch_tdep::sc_reg_offset, set_gdbarch_long_double_bit(), set_gdbarch_num_regs(), set_gdbarch_push_dummy_call(), set_solib_ops(), gdbarch_tdep::sigcontext_addr, gdbarch_tdep::sigtramp_p, and gdbarch_tdep::struct_return.
Referenced by _initialize_i386_darwin_tdep().
static CORE_ADDR i386_darwin_push_dummy_call (struct gdbarch * gdbarch, struct value * function, struct regcache * regcache, CORE_ADDR bp_addr, int nargs, struct value ** args, CORE_ADDR sp, int struct_return, CORE_ADDR struct_addr) [static]
Definition at line 153 of file i386-darwin-tdep.c.
References align_down(), align_up(), gdbarch_byte_order(), gdbarch_tdep(), i386_darwin_arg_type_alignment(), I386_EBP_REGNUM, I386_ESP_REGNUM, i386_m128_p(), I387_MM0_REGNUM, regcache_cooked_write(), regcache_raw_write(), store_unsigned_integer(), TYPE_LENGTH, value_contents_all(), value_enclosing_type(), and write_memory().
Referenced by i386_darwin_init_abi().
static CORE_ADDR i386_darwin_sigcontext_addr (struct frame_info * this_frame) [static]
Definition at line 73 of file i386-darwin-tdep.c.
References gdbarch::byte_order, extract_unsigned_integer(), gdbarch_byte_order(), get_frame_arch(), get_frame_register(), I386_EBP_REGNUM, and read_memory().
Referenced by i386_darwin_init_abi().
static int i386_m128_p (struct type * type) [static]
Definition at line 114 of file i386-darwin-tdep.c.
References TYPE_CODE, TYPE_CODE_ARRAY, TYPE_LENGTH, and TYPE_VECTOR.
Referenced by i386_darwin_push_dummy_call().
static enum gdb_osabi i386_mach_o_osabi_sniffer (bfd * abfd) [static]
Definition at line 278 of file i386-darwin-tdep.c.
References GDB_OSABI_DARWIN, and GDB_OSABI_UNKNOWN.
Referenced by _initialize_i386_darwin_tdep().
Variable Documentation
initialize_file_ftype _initialize_i386_darwin_tdep
Referenced by _initialize_i386_darwin_tdep(), and initialize_all_files().
const int i386_darwin_thread_state_num_regs
Initial value:
  ARRAY_SIZE (i386_darwin_thread_state_reg_offset)
Definition at line 66 of file i386-darwin-tdep.c.
Referenced by darwin_complete_target(), and i386_darwin_init_abi().
int i386_darwin_thread_state_reg_offset[]
Initial value:
{
   0 * 4,
   2 * 4,
   3 * 4,
   1 * 4,
   7 * 4,
   6 * 4,
   5 * 4,
   4 * 4,
  10 * 4,
   9 * 4,
  11 * 4,
   8 * 4,
  12 * 4,
  13 * 4,
  14 * 4,
  15 * 4
}
Definition at line 46 of file i386-darwin-tdep.c.
Referenced by darwin_complete_target(), i386_darwin_fetch_inferior_registers(), i386_darwin_init_abi(), and i386_darwin_store_inferior_registers().