GDB (xrefs): /home/stan/gdb/src/gdb/i386bsd-tdep.c File Reference
/home/stan/gdb/src/gdb/i386bsd-tdep.c File Reference
#include "defs.h"
#include "arch-utils.h"
#include "frame.h"
#include "gdbcore.h"
#include "regcache.h"
#include "osabi.h"
#include "gdb_string.h"
#include "i386-tdep.h"
Functions
static CORE_ADDR i386bsd_sigcontext_addr (struct frame_info *this_frame)
void i386bsd_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
static enum gdb_osabi i386bsd_aout_osabi_sniffer (bfd *abfd)
static enum gdb_osabi i386bsd_core_osabi_sniffer (bfd *abfd)
void _initialize_i386bsd_tdep (void)
Variables
int i386bsd_sc_reg_offset []
Function Documentation
void _initialize_i386bsd_tdep (void)
static enum gdb_osabi i386bsd_aout_osabi_sniffer (bfd * abfd) [static]
Definition at line 92 of file i386bsd-tdep.c.
References GDB_OSABI_FREEBSD_AOUT, GDB_OSABI_NETBSD_AOUT, and GDB_OSABI_UNKNOWN.
static enum gdb_osabi i386bsd_core_osabi_sniffer (bfd * abfd) [static]
Definition at line 104 of file i386bsd-tdep.c.
References GDB_OSABI_NETBSD_AOUT, and GDB_OSABI_UNKNOWN.
void i386bsd_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch)
Definition at line 77 of file i386bsd-tdep.c.
References gdbarch_tdep(), i386bsd_sc_reg_offset, i386bsd_sigcontext_addr(), gdbarch_tdep::jb_pc_offset, gdbarch_tdep::sc_num_regs, gdbarch_tdep::sc_reg_offset, gdbarch_tdep::sigcontext_addr, gdbarch_tdep::sigtramp_end, and gdbarch_tdep::sigtramp_start.
Referenced by amd64fbsd_init_abi(), i386fbsdaout_init_abi(), i386nbsd_init_abi(), and i386obsd_init_abi().
static CORE_ADDR i386bsd_sigcontext_addr (struct frame_info * this_frame) [static]
Definition at line 37 of file i386bsd-tdep.c.
References gdbarch::byte_order, extract_unsigned_integer(), gdbarch_byte_order(), get_frame_arch(), get_frame_register(), I386_ESP_REGNUM, read_memory_unsigned_integer(), and sp.
Referenced by i386bsd_init_abi().
Variable Documentation
int i386bsd_sc_reg_offset[]
Initial value:
{
  -1,
  -1,
  -1,
  -1,
  8 + 0 * 4,
  8 + 1 * 4,
  -1,
  -1,
  8 + 3 * 4,
  8 + 4 * 4,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1
}
Definition at line 56 of file i386bsd-tdep.c.
Referenced by i386bsd_init_abi().