GDB (xrefs): /home/stan/gdb/src/gdb/i386-darwin-nat.c File Reference
/home/stan/gdb/src/gdb/i386-darwin-nat.c File Reference
#include "defs.h"
#include "frame.h"
#include "inferior.h"
#include "target.h"
#include "symfile.h"
#include "symtab.h"
#include "objfiles.h"
#include "gdbcmd.h"
#include "regcache.h"
#include "gdb_assert.h"
#include "i386-tdep.h"
#include "i387-tdep.h"
#include "gdbarch.h"
#include "arch-utils.h"
#include "gdbcore.h"
#include "i386-nat.h"
#include "darwin-nat.h"
#include "i386-darwin-tdep.h"
Defines
#define X86_EFLAGS_T 0x100UL
Functions
static void i386_darwin_fetch_inferior_registers (struct target_ops *ops, struct regcache *regcache, int regno)
static void i386_darwin_store_inferior_registers (struct target_ops *ops, struct regcache *regcache, int regno)
static void i386_darwin_dr_set (int regnum, CORE_ADDR value)
static CORE_ADDR i386_darwin_dr_get (int regnum)
static void i386_darwin_dr_set_control (unsigned long control)
static void i386_darwin_dr_set_addr (int regnum, CORE_ADDR addr)
static CORE_ADDR i386_darwin_dr_get_addr (int regnum)
static unsigned long i386_darwin_dr_get_status (void)
static unsigned long i386_darwin_dr_get_control (void)
void darwin_check_osabi (darwin_inferior *inf, thread_t thread)
static int i386_darwin_sstep_at_sigreturn (x86_thread_state_t *regs)
void darwin_set_sstep (thread_t thread, int enable)
void darwin_complete_target (struct target_ops *target)
Define Documentation
#define X86_EFLAGS_T 0x100UL
Definition at line 494 of file i386-darwin-nat.c.
Referenced by darwin_set_sstep(), and i386_darwin_sstep_at_sigreturn().
Function Documentation
void darwin_check_osabi (darwin_inferior * inf, thread_t thread)
Definition at line 462 of file i386-darwin-nat.c.
References gdbarch_info::bfd_arch_info, gdbarch_info::byte_order, GDB_OSABI_DARWIN, GDB_OSABI_UNKNOWN, gdbarch_byte_order(), gdbarch_info_fill(), gdbarch_info_init(), gdbarch_osabi(), gdbarch_update_p(), MACH_CHECK_ERROR, gdbarch_info::osabi, and target_gdbarch().
Referenced by darwin_attach().
void darwin_complete_target (struct target_ops * target)
Definition at line 623 of file i386-darwin-nat.c.
References amd64_darwin_thread_state_num_regs, amd64_darwin_thread_state_reg_offset, amd64_native_gregset32_num_regs, amd64_native_gregset32_reg_offset, amd64_native_gregset64_num_regs, amd64_native_gregset64_reg_offset, i386_dr_low_type::get_addr, i386_dr_low_type::get_control, i386_dr_low_type::get_status, i386_darwin_dr_get_addr(), i386_darwin_dr_get_control(), i386_darwin_dr_get_status(), i386_darwin_dr_set_addr(), i386_darwin_dr_set_control(), i386_darwin_fetch_inferior_registers(), i386_darwin_store_inferior_registers(), i386_darwin_thread_state_num_regs, i386_darwin_thread_state_reg_offset, i386_dr_low, i386_set_debug_register_length(), i386_use_watchpoints(), i386_dr_low_type::set_addr, i386_dr_low_type::set_control, target_ops::to_fetch_registers, and target_ops::to_store_registers.
Referenced by _initialize_darwin_inferior().
void darwin_set_sstep (thread_t thread, int enable)
Definition at line 568 of file i386-darwin-nat.c.
References _, bit, error(), i386_darwin_sstep_at_sigreturn(), MACH_CHECK_ERROR, printf_unfiltered(), and X86_EFLAGS_T.
Referenced by darwin_resume_thread().
static CORE_ADDR i386_darwin_dr_get (int regnum) [static]
Definition at line 356 of file i386-darwin-nat.c.
References current_thread, DR_CONTROL, gdb_assert, inferior_ptid, MACH_CHECK_ERROR, and ptid_get_tid().
Referenced by i386_darwin_dr_get_addr(), i386_darwin_dr_get_control(), and i386_darwin_dr_get_status().
static CORE_ADDR i386_darwin_dr_get_addr (int regnum) [static]
Definition at line 444 of file i386-darwin-nat.c.
References i386_darwin_dr_get().
Referenced by darwin_complete_target().
static unsigned long i386_darwin_dr_get_control (void) [static]
Definition at line 456 of file i386-darwin-nat.c.
References DR_CONTROL, and i386_darwin_dr_get().
Referenced by darwin_complete_target().
static unsigned long i386_darwin_dr_get_status (void) [static]
Definition at line 450 of file i386-darwin-nat.c.
References DR_STATUS, and i386_darwin_dr_get().
Referenced by darwin_complete_target().
static void i386_darwin_dr_set (int regnum, CORE_ADDR value) [static]
Definition at line 266 of file i386-darwin-nat.c.
References current_thread, DR_CONTROL, gdb_assert, inferior_ptid, MACH_CHECK_ERROR, and ptid_get_tid().
Referenced by i386_darwin_dr_set_addr(), and i386_darwin_dr_set_control().
static void i386_darwin_dr_set_addr (int regnum, CORE_ADDR addr) [static]
Definition at line 436 of file i386-darwin-nat.c.
References DR_FIRSTADDR, DR_LASTADDR, gdb_assert, and i386_darwin_dr_set().
Referenced by darwin_complete_target().
static void i386_darwin_dr_set_control (unsigned long control) [static]
Definition at line 430 of file i386-darwin-nat.c.
References DR_CONTROL, and i386_darwin_dr_set().
Referenced by darwin_complete_target().
static void i386_darwin_fetch_inferior_registers (struct target_ops * ops, struct regcache * regcache, int regno) [static]
Definition at line 51 of file i386-darwin-nat.c.
References _, amd64_native_gregset_supplies_p(), amd64_supply_fxsave(), amd64_supply_native_gregset(), current_thread, gdbarch_ptr_bit(), get_regcache_arch(), i386_darwin_thread_state_reg_offset, I386_NUM_GREGS, I386_SSE_NUM_REGS, I386_ST0_REGNUM, i387_supply_fxsave(), inferior_ptid, MACH_CHECK_ERROR, printf_unfiltered(), ptid_get_tid(), regcache_raw_supply(), and warning().
Referenced by darwin_complete_target().
static int i386_darwin_sstep_at_sigreturn (x86_thread_state_t * regs) [static]
Definition at line 504 of file i386-darwin-nat.c.
References gdbarch_info::byte_order, gdbarch_byte_order(), memcmp(), read_memory(), read_memory_unsigned_integer(), target_gdbarch(), target_read_memory(), ULONGEST, write_memory(), and X86_EFLAGS_T.
Referenced by darwin_set_sstep().
static void i386_darwin_store_inferior_registers (struct target_ops * ops, struct regcache * regcache, int regno) [static]
Definition at line 163 of file i386-darwin-nat.c.
References amd64_collect_fxsave(), amd64_collect_native_gregset(), amd64_native_gregset_supplies_p(), current_thread, gdb_assert, gdbarch_ptr_bit(), get_regcache_arch(), i386_darwin_thread_state_reg_offset, I386_NUM_GREGS, I386_SSE_NUM_REGS, I386_ST0_REGNUM, i387_collect_fxsave(), inferior_ptid, MACH_CHECK_ERROR, ptid_get_tid(), and regcache_raw_collect().
Referenced by darwin_complete_target().