GDB (xrefs): /home/stan/gdb/src/gdb/i386-nat.h File Reference
/home/stan/gdb/src/gdb/i386-nat.h File Reference
Classes
struct i386_dr_low_type
struct i386_debug_reg_state
Defines
#define DR_FIRSTADDR 0
#define DR_LASTADDR 3
#define DR_NADDR 4 /* The number of debug address registers. */
#define DR_STATUS 6 /* Index of debug status register (DR6). */
#define DR_CONTROL 7 /* Index of debug control register (DR7). */
Functions
void i386_use_watchpoints (struct target_ops *)
void i386_set_debug_register_length (int len)
void i386_cleanup_dregs (void)
struct i386_debug_reg_state * i386_debug_reg_state (pid_t pid)
void i386_forget_process (pid_t pid)
Variables
struct i386_dr_low_type i386_dr_low
Define Documentation
#define DR_CONTROL 7 /* Index of debug control register (DR7). */
Definition at line 84 of file i386-nat.h.
Referenced by amd64_linux_dr_get_control(), amd64_linux_prepare_to_resume(), i386_darwin_dr_get(), i386_darwin_dr_get_control(), i386_darwin_dr_set(), i386_darwin_dr_set_control(), i386_linux_dr_get_control(), and i386_linux_prepare_to_resume().
#define DR_FIRSTADDR 0
Definition at line 80 of file i386-nat.h.
Referenced by amd64_linux_dr_get_addr(), amd64_linux_dr_set_addr(), amd64_linux_prepare_to_resume(), i386_darwin_dr_set_addr(), i386_linux_dr_get_addr(), i386_linux_dr_set_addr(), and i386_linux_prepare_to_resume().
#define DR_LASTADDR 3
Definition at line 81 of file i386-nat.h.
Referenced by amd64_linux_dr_get_addr(), amd64_linux_dr_set_addr(), amd64_linux_prepare_to_resume(), i386_darwin_dr_set_addr(), i386_linux_dr_get_addr(), i386_linux_dr_set_addr(), and i386_linux_prepare_to_resume().
#define DR_NADDR 4 /* The number of debug address registers. */
Definition at line 82 of file i386-nat.h.
Referenced by i386_insert_aligned_watchpoint(), and i386_region_ok_for_watchpoint().
#define DR_STATUS 6 /* Index of debug status register (DR6). */
Definition at line 83 of file i386-nat.h.
Referenced by amd64_linux_dr_get_status(), amd64_linux_prepare_to_resume(), i386_darwin_dr_get_status(), i386_linux_dr_get_status(), and i386_linux_prepare_to_resume().
Function Documentation
void i386_cleanup_dregs (void)
Definition at line 302 of file i386-nat.c.
References i386_forget_process(), inferior_ptid, and ptid_get_pid().
Referenced by amd64_linux_child_post_startup_inferior(), amd64fbsd_mourn_inferior(), go32_mourn_inferior(), i386_linux_child_post_startup_inferior(), windows_detach(), and windows_mourn_inferior().
struct i386_debug_reg_state* i386_debug_reg_state (pid_t pid) [read]
Definition at line 224 of file i386-nat.c.
References i386_process_info_get(), and i386_process_info::state.
Referenced by amd64_linux_new_fork(), amd64_linux_prepare_to_resume(), i386_insert_hw_breakpoint(), i386_insert_watchpoint(), i386_linux_new_fork(), i386_linux_prepare_to_resume(), i386_region_ok_for_watchpoint(), i386_remove_hw_breakpoint(), i386_remove_watchpoint(), i386_stopped_data_address(), and i386_update_inferior_debug_regs().
void i386_forget_process (pid_t pid)
Definition at line 232 of file i386-nat.c.
References i386_process_list, i386_process_info::next, i386_process_info::pid, and xfree().
Referenced by _initialize_amd64_linux_nat(), _initialize_i386_linux_nat(), and i386_cleanup_dregs().
void i386_set_debug_register_length (int len)
Definition at line 879 of file i386-nat.c.
References add_show_debug_regs_command(), i386_dr_low_type::debug_register_length, gdb_assert, i386_dr_low, and len.
Referenced by _initialize_amd64_linux_nat(), _initialize_amd64_windows_nat(), _initialize_amd64fbsd_nat(), _initialize_i386_linux_nat(), _initialize_i386_windows_nat(), _initialize_i386fbsd_nat(), darwin_complete_target(), and init_go32_ops().
void i386_use_watchpoints (struct target_ops *)
Definition at line 861 of file i386-nat.c.
References i386_can_use_hw_breakpoint(), i386_insert_hw_breakpoint(), i386_insert_watchpoint(), i386_region_ok_for_watchpoint(), i386_remove_hw_breakpoint(), i386_remove_watchpoint(), i386_stopped_by_watchpoint(), i386_stopped_data_address(), target_ops::to_can_use_hw_breakpoint, target_ops::to_have_continuable_watchpoint, target_ops::to_insert_hw_breakpoint, target_ops::to_insert_watchpoint, target_ops::to_region_ok_for_hw_watchpoint, target_ops::to_remove_hw_breakpoint, target_ops::to_remove_watchpoint, target_ops::to_stopped_by_watchpoint, and target_ops::to_stopped_data_address.
Referenced by _initialize_amd64_linux_nat(), _initialize_amd64fbsd_nat(), _initialize_i386_linux_nat(), _initialize_i386fbsd_nat(), darwin_complete_target(), init_go32_ops(), and init_windows_ops().
Variable Documentation
struct i386_dr_low_type i386_dr_low
Definition at line 40 of file i386-nat.c.
Referenced by _initialize_amd64_linux_nat(), _initialize_amd64fbsd_nat(), _initialize_i386_linux_nat(), _initialize_i386fbsd_nat(), darwin_complete_target(), i386_insert_aligned_watchpoint(), i386_set_debug_register_length(), i386_stopped_data_address(), i386_update_inferior_debug_regs(), init_go32_ops(), and init_windows_ops().