GDB (xrefs): /home/stan/gdb/src/gdb/i386-cygwin-tdep.c File Reference
/home/stan/gdb/src/gdb/i386-cygwin-tdep.c File Reference
#include "defs.h"
#include "osabi.h"
#include "gdb_string.h"
#include "i386-tdep.h"
#include "windows-tdep.h"
#include "regset.h"
#include "gdb_obstack.h"
#include "xml-support.h"
#include "gdbcore.h"
#include "inferior.h"
Classes
struct cpms_data
Defines
#define I386_WINDOWS_SIZEOF_GREGSET 716
Functions
static struct regset * i386_windows_regset_from_core_section (struct gdbarch *gdbarch, const char *sect_name, size_t sect_size)
static void core_process_module_section (bfd *abfd, asection *sect, void *obj)
static LONGEST windows_core_xfer_shared_libraries (struct gdbarch *gdbarch, gdb_byte *readbuf, ULONGEST offset, LONGEST len)
static char * i386_windows_core_pid_to_str (struct gdbarch *gdbarch, ptid_t ptid)
static CORE_ADDR i386_cygwin_skip_trampoline_code (struct frame_info *frame, CORE_ADDR pc)
static const char * i386_cygwin_auto_wide_charset (void)
static void i386_cygwin_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
static enum gdb_osabi i386_cygwin_osabi_sniffer (bfd *abfd)
void _initialize_i386_cygwin_tdep (void)
Variables
static int i386_windows_gregset_reg_offset []
Define Documentation
#define I386_WINDOWS_SIZEOF_GREGSET 716
Definition at line 90 of file i386-cygwin-tdep.c.
Referenced by i386_cygwin_init_abi(), i386_cygwin_osabi_sniffer(), and i386_windows_regset_from_core_section().
Function Documentation
void _initialize_i386_cygwin_tdep (void)
static void core_process_module_section (bfd * abfd, asection * sect, void * obj) [static]
Definition at line 121 of file i386-cygwin-tdep.c.
References extract_unsigned_integer(), cpms_data::gdbarch, gdbarch_byte_order(), cpms_data::module_count, cpms_data::obstack, printf_unfiltered(), windows_xfer_shared_library(), xfree(), and xmalloc().
Referenced by windows_core_xfer_shared_libraries().
static const char* i386_cygwin_auto_wide_charset (void) [static]
Definition at line 224 of file i386-cygwin-tdep.c.
Referenced by i386_cygwin_init_abi().
static void i386_cygwin_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch) [static]
Definition at line 230 of file i386-cygwin-tdep.c.
References gdbarch_tdep(), gdbarch_tdep::gregset_num_regs, gdbarch_tdep::gregset_reg_offset, i386_cygwin_auto_wide_charset(), i386_cygwin_skip_trampoline_code(), i386_skip_main_prologue(), i386_windows_core_pid_to_str(), i386_windows_gregset_reg_offset, i386_windows_regset_from_core_section(), I386_WINDOWS_SIZEOF_GREGSET, reg_struct_return, set_gdbarch_auto_wide_charset(), set_gdbarch_core_pid_to_str(), set_gdbarch_core_xfer_shared_libraries(), set_gdbarch_regset_from_core_section(), set_gdbarch_skip_main_prologue(), set_gdbarch_skip_trampoline_code(), gdbarch_tdep::sizeof_gregset, gdbarch_tdep::struct_return, windows_core_xfer_shared_libraries(), and windows_init_abi().
static enum gdb_osabi i386_cygwin_osabi_sniffer (bfd * abfd) [static]
Definition at line 257 of file i386-cygwin-tdep.c.
References GDB_OSABI_CYGWIN, GDB_OSABI_UNKNOWN, I386_WINDOWS_SIZEOF_GREGSET, and target_name.
static CORE_ADDR i386_cygwin_skip_trampoline_code (struct frame_info * frame, CORE_ADDR pc) [static]
Definition at line 218 of file i386-cygwin-tdep.c.
References i386_pe_skip_trampoline_code().
Referenced by i386_cygwin_init_abi().
static char* i386_windows_core_pid_to_str (struct gdbarch * gdbarch, ptid_t ptid) [static]
Definition at line 204 of file i386-cygwin-tdep.c.
References normal_pid_to_str(), and ptid_get_lwp().
Referenced by i386_cygwin_init_abi().
static struct regset* i386_windows_regset_from_core_section (struct gdbarch * gdbarch, const char * sect_name, size_t sect_size) [static, read]
Definition at line 96 of file i386-cygwin-tdep.c.
References gdbarch_tdep(), gdbarch_tdep::gregset, i386_collect_gregset(), i386_supply_gregset(), I386_WINDOWS_SIZEOF_GREGSET, and regset_alloc().
Referenced by i386_cygwin_init_abi().
static LONGEST windows_core_xfer_shared_libraries (struct gdbarch * gdbarch, gdb_byte * readbuf, ULONGEST offset, LONGEST len) [static]
Definition at line 172 of file i386-cygwin-tdep.c.
References core_bfd, core_process_module_section(), cpms_data::gdbarch, len, LONGEST, memcpy(), cpms_data::obstack, obstack_grow_str, obstack_grow_str0, and offset.
Referenced by i386_cygwin_init_abi().
Variable Documentation
int i386_windows_gregset_reg_offset[] [static]
Definition at line 36 of file i386-cygwin-tdep.c.
Referenced by i386_cygwin_init_abi().