GDB (xrefs): /home/stan/gdb/src/gdb/i386-dicos-tdep.c File Reference
/home/stan/gdb/src/gdb/i386-dicos-tdep.c File Reference
#include "defs.h"
#include "osabi.h"
#include "gdb_string.h"
#include "dicos-tdep.h"
Functions
static void i386_dicos_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
static enum gdb_osabi i386_dicos_osabi_sniffer (bfd *abfd)
void _initialize_i386_dicos_tdep (void)
Function Documentation
void _initialize_i386_dicos_tdep (void)
static void i386_dicos_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch) [static]
Definition at line 26 of file i386-dicos-tdep.c.
References dicos_init_abi(), and gdbarch_tdep().
static enum gdb_osabi i386_dicos_osabi_sniffer (bfd * abfd) [static]
Definition at line 34 of file i386-dicos-tdep.c.
References dicos_load_module_p(), GDB_OSABI_DICOS, GDB_OSABI_UNKNOWN, and target_name.