GDB (xrefs): /home/stan/gdb/src/gdb/i386bsd-nat.c File Reference
/home/stan/gdb/src/gdb/i386bsd-nat.c File Reference
#include "defs.h"
#include "inferior.h"
#include "regcache.h"
#include "gdb_assert.h"
#include <signal.h>
#include <stddef.h>
#include <sys/types.h>
#include <sys/ptrace.h>
#include <machine/reg.h>
#include <machine/frame.h>
#include "i386-tdep.h"
#include "i387-tdep.h"
#include "i386bsd-nat.h"
#include "inf-ptrace.h"
Defines
#define REG_OFFSET(member) offsetof (struct reg, member)
#define GETREGS_SUPPLIES(regnum) ((0 <= (regnum) && (regnum) <= 15))
Functions
static void i386bsd_supply_gregset (struct regcache *regcache, const void *gregs)
static void i386bsd_collect_gregset (const struct regcache *regcache, void *gregs, int regnum)
static void i386bsd_fetch_inferior_registers (struct target_ops *ops, struct regcache *regcache, int regnum)
static void i386bsd_store_inferior_registers (struct target_ops *ops, struct regcache *regcache, int regnum)
struct target_ops * i386bsd_target (void)
void _initialize_i386bsd_nat (void)
Variables
static int i386bsd_r_reg_offset []
Define Documentation
#define GETREGS_SUPPLIES (regnum) ((0 <= (regnum) && (regnum) <= 15))
Definition at line 78 of file i386bsd-nat.c.
Referenced by i386bsd_fetch_inferior_registers(), and i386bsd_store_inferior_registers().
#define REG_OFFSET (member) offsetof (struct reg, member)
Definition at line 44 of file i386bsd-nat.c.
Function Documentation
void _initialize_i386bsd_nat (void)
Definition at line 338 of file i386bsd-nat.c.
References _, offset, and warning().
static void i386bsd_collect_gregset (const struct regcache * regcache, void * gregs, int regnum) [static]
Definition at line 110 of file i386bsd-nat.c.
References i386bsd_r_reg_offset, offset, and regcache_raw_collect().
Referenced by i386bsd_store_inferior_registers().
static void i386bsd_fetch_inferior_registers (struct target_ops * ops, struct regcache * regcache, int regnum) [static]
Definition at line 132 of file i386bsd-nat.c.
References _, GETREGS_SUPPLIES, I386_ST0_REGNUM, i386bsd_supply_gregset(), i387_supply_fsave(), i387_supply_fxsave(), inferior_ptid, perror_with_name(), ptid_get_pid(), ptrace(), and PTRACE_TYPE_ARG3.
Referenced by i386bsd_target().
static void i386bsd_store_inferior_registers (struct target_ops * ops, struct regcache * regcache, int regnum) [static]
Definition at line 183 of file i386bsd-nat.c.
References _, GETREGS_SUPPLIES, I386_ST0_REGNUM, i386bsd_collect_gregset(), i387_collect_fsave(), i387_collect_fxsave(), inferior_ptid, perror_with_name(), ptid_get_pid(), ptrace(), and PTRACE_TYPE_ARG3.
Referenced by i386bsd_target().
static void i386bsd_supply_gregset (struct regcache * regcache, const void * gregs) [static]
Definition at line 91 of file i386bsd-nat.c.
References i386bsd_r_reg_offset, offset, regcache_raw_supply(), and regnum.
Referenced by i386bsd_fetch_inferior_registers().
struct target_ops* i386bsd_target (void) [read]
Definition at line 245 of file i386bsd-nat.c.
References i386bsd_fetch_inferior_registers(), i386bsd_store_inferior_registers(), inf_ptrace_target(), target_ops::to_fetch_registers, and target_ops::to_store_registers.
Referenced by _initialize_i386fbsd_nat(), _initialize_i386nbsd_nat(), and _initialize_i386obsd_nat().
Variable Documentation
int i386bsd_r_reg_offset[] [static]
Initial value:
{
  REG_OFFSET (r_eax),
  REG_OFFSET (r_ecx),
  REG_OFFSET (r_edx),
  REG_OFFSET (r_ebx),
  REG_OFFSET (r_esp),
  REG_OFFSET (r_ebp),
  REG_OFFSET (r_esi),
  REG_OFFSET (r_edi),
  REG_OFFSET (r_eip),
  REG_OFFSET (r_eflags),
  REG_OFFSET (r_cs),
  REG_OFFSET (r_ss),
  REG_OFFSET (r_ds),
  REG_OFFSET (r_es),
  -1,
  -1
}
Definition at line 49 of file i386bsd-nat.c.
Referenced by i386bsd_collect_gregset(), and i386bsd_supply_gregset().