GDB (xrefs): /home/stan/gdb/src/gdb/i386-nto-tdep.c File Reference
/home/stan/gdb/src/gdb/i386-nto-tdep.c File Reference
#include "defs.h"
#include "frame.h"
#include "osabi.h"
#include "regcache.h"
#include "target.h"
#include "gdb_assert.h"
#include "gdb_string.h"
#include "i386-tdep.h"
#include "i387-tdep.h"
#include "nto-tdep.h"
#include "solib.h"
#include "solib-svr4.h"
Defines
#define X86_CPU_FXSR (1L << 12)
#define NUM_GPREGS 13
Functions
static int nto_reg_offset (int regnum)
static void i386nto_supply_gregset (struct regcache *regcache, char *gpregs)
static void i386nto_supply_fpregset (struct regcache *regcache, char *fpregs)
static void i386nto_supply_regset (struct regcache *regcache, int regset, char *data)
static int i386nto_regset_id (int regno)
static int i386nto_register_area (struct gdbarch *gdbarch, int regno, int regset, unsigned *off)
static int i386nto_regset_fill (const struct regcache *regcache, int regset, char *data)
static int i386nto_sigtramp_p (struct frame_info *this_frame)
static CORE_ADDR i386nto_sigcontext_addr (struct frame_info *this_frame)
static void init_i386nto_ops (void)
static void i386nto_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
void _initialize_i386nto_tdep (void)
Variables
static int i386nto_gregset_reg_offset []
initialize_file_ftype _initialize_i386nto_tdep
Define Documentation
#define NUM_GPREGS 13
Definition at line 44 of file i386-nto-tdep.c.
Referenced by i386nto_init_abi(), i386nto_register_area(), i386nto_regset_fill(), and i386nto_supply_gregset().
#define X86_CPU_FXSR (1L << 12)
Definition at line 38 of file i386-nto-tdep.c.
Referenced by i386nto_register_area(), i386nto_regset_fill(), and i386nto_supply_fpregset().
Function Documentation
void _initialize_i386nto_tdep (void)
Definition at line 378 of file i386-nto-tdep.c.
References _initialize_i386nto_tdep, GDB_OSABI_QNXNTO, gdbarch_register_osabi(), gdbarch_register_osabi_sniffer(), i386nto_init_abi(), init_i386nto_ops(), and nto_elf_osabi_sniffer().
static void i386nto_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch) [static]
Definition at line 323 of file i386-nto-tdep.c.
References target_so_ops::find_and_open_solib, gdbarch_tdep(), gdbarch_tdep::gregset_num_regs, gdbarch_tdep::gregset_reg_offset, i386_elf_init_abi(), i386nto_gregset_reg_offset, i386nto_sigcontext_addr(), i386nto_sigtramp_p(), target_so_ops::in_dynsym_resolve_code, gdbarch_tdep::jb_pc_offset, nto_find_and_open_solib(), nto_in_dynsym_resolve_code(), nto_initialize_signals(), nto_relocate_section_addresses(), NUM_GPREGS, target_so_ops::relocate_section_addresses, gdbarch_tdep::sc_num_regs, gdbarch_tdep::sc_reg_offset, set_gdbarch_decr_pc_after_break(), set_solib_ops(), set_solib_svr4_fetch_link_map_offsets(), gdbarch_tdep::sigcontext_addr, gdbarch_tdep::sigtramp_p, gdbarch_tdep::sizeof_gregset, svr4_ilp32_fetch_link_map_offsets(), and svr4_so_ops.
Referenced by _initialize_i386nto_tdep().
static int i386nto_register_area (struct gdbarch * gdbarch, int regno, int regset, unsigned * off) [static]
Definition at line 133 of file i386-nto-tdep.c.
References gdb_assert, gdbarch_tdep(), I387_FCTRL_REGNUM, I387_FISEG_REGNUM, I387_FOP_REGNUM, I387_MXCSR_REGNUM, I387_ST0_REGNUM, I387_XMM0_REGNUM, nto_cpuinfo_flags, nto_cpuinfo_valid, NTO_REG_FLOAT, NTO_REG_GENERAL, nto_reg_offset(), NUM_GPREGS, and X86_CPU_FXSR.
Referenced by init_i386nto_ops().
static int i386nto_regset_fill (const struct regcache * regcache, int regset, char * data) [static]
Definition at line 250 of file i386-nto-tdep.c.
References i387_collect_fsave(), i387_collect_fxsave(), nto_cpuinfo_flags, nto_cpuinfo_valid, NTO_REG_FLOAT, NTO_REG_GENERAL, nto_reg_offset(), NUM_GPREGS, offset, regcache_raw_collect(), and X86_CPU_FXSR.
Referenced by init_i386nto_ops().
static int i386nto_regset_id (int regno) [static]
Definition at line 118 of file i386-nto-tdep.c.
References I386_NUM_GREGS, I386_SSE_NUM_REGS, I387_NUM_REGS, NTO_REG_END, NTO_REG_FLOAT, and NTO_REG_GENERAL.
Referenced by init_i386nto_ops().
static CORE_ADDR i386nto_sigcontext_addr (struct frame_info * this_frame) [static]
Definition at line 293 of file i386-nto-tdep.c.
References gdbarch::byte_order, extract_unsigned_integer(), gdbarch_byte_order(), get_frame_arch(), get_frame_register(), and I386_EDI_REGNUM.
Referenced by i386nto_init_abi().
static int i386nto_sigtramp_p (struct frame_info * this_frame) [static]
Definition at line 280 of file i386-nto-tdep.c.
References find_pc_partial_function(), get_frame_pc(), name, and gdbarch_tdep::pc.
Referenced by i386nto_init_abi().
static void i386nto_supply_fpregset (struct regcache * regcache, char * fpregs) [static]
Definition at line 95 of file i386-nto-tdep.c.
References i387_supply_fsave(), i387_supply_fxsave(), nto_cpuinfo_flags, nto_cpuinfo_valid, and X86_CPU_FXSR.
Referenced by i386nto_supply_regset(), and init_i386nto_ops().
static void i386nto_supply_gregset (struct regcache * regcache, char * gpregs) [static]
Definition at line 80 of file i386-nto-tdep.c.
References gdb_assert, gdbarch_tdep(), get_regcache_arch(), gdbarch_tdep::gregset, gdbarch_tdep::gregset_reg_offset, i386_collect_gregset(), i386_supply_gregset(), i386nto_gregset_reg_offset, NUM_GPREGS, regset_alloc(), and regset::supply_regset.
Referenced by i386nto_supply_regset(), and init_i386nto_ops().
static void i386nto_supply_regset (struct regcache * regcache, int regset, char * data) [static]
Definition at line 104 of file i386-nto-tdep.c.
References i386nto_supply_fpregset(), i386nto_supply_gregset(), NTO_REG_FLOAT, and NTO_REG_GENERAL.
Referenced by init_i386nto_ops().
static void init_i386nto_ops (void) [static]
Definition at line 309 of file i386-nto-tdep.c.
References i386nto_register_area(), i386nto_regset_fill(), i386nto_regset_id(), i386nto_supply_fpregset(), i386nto_supply_gregset(), i386nto_supply_regset(), nto_dummy_supply_regset(), nto_fetch_link_map_offsets, nto_register_area, nto_regset_fill, nto_regset_id, nto_supply_altregset, nto_supply_fpregset, nto_supply_gregset, nto_supply_regset, and svr4_ilp32_fetch_link_map_offsets().
Referenced by _initialize_i386nto_tdep().
static int nto_reg_offset (int regnum) [static]
Definition at line 71 of file i386-nto-tdep.c.
References i386nto_gregset_reg_offset, and regnum.
Referenced by i386nto_register_area(), and i386nto_regset_fill().
Variable Documentation
initialize_file_ftype _initialize_i386nto_tdep
Referenced by _initialize_i386nto_tdep(), and initialize_all_files().
int i386nto_gregset_reg_offset[] [static]
Initial value:
{
  7 * 4,
  6 * 4,
  5 * 4,
  4 * 4,
  11 * 4,
  2 * 4,
  1 * 4,
  0 * 4,
  8 * 4,
  10 * 4,
  9 * 4,
  12 * 4,
  -1
}
Definition at line 50 of file i386-nto-tdep.c.
Referenced by i386nto_init_abi(), i386nto_supply_gregset(), and nto_reg_offset().