GDB (xrefs): /home/stan/gdb/src/gdb/ia64-vms-tdep.c File Reference
/home/stan/gdb/src/gdb/ia64-vms-tdep.c File Reference
#include "defs.h"
#include "frame-unwind.h"
#include "ia64-tdep.h"
#include "osabi.h"
#include "gdbtypes.h"
#include "gdbcore.h"
Functions
static void ia64_openvms_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
void _initialize_ia64_vms_tdep (void)
Variables
initialize_file_ftype _initialize_ia64_vms_tdep
Function Documentation
void _initialize_ia64_vms_tdep (void)
Definition at line 161 of file ia64-vms-tdep.c.
References GDB_OSABI_OPENVMS, gdbarch_register_osabi(), and ia64_openvms_init_abi().
static void ia64_openvms_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch) [static]
Definition at line 133 of file ia64-vms-tdep.c.
References floatformats_ia64_quad, libunwind_frame_set_descr(), and set_gdbarch_long_double_format().
Referenced by _initialize_ia64_vms_tdep().
Variable Documentation
initialize_file_ftype _initialize_ia64_vms_tdep