GDB (xrefs): /home/stan/gdb/src/gdb/ia64-linux-tdep.c File Reference
/home/stan/gdb/src/gdb/ia64-linux-tdep.c File Reference
#include "defs.h"
#include "ia64-tdep.h"
#include "arch-utils.h"
#include "gdbcore.h"
#include "regcache.h"
#include "osabi.h"
#include "solib-svr4.h"
#include "symtab.h"
#include "linux-tdep.h"
#include <ctype.h>
Defines
#define GATE_AREA_START 0xa000000000000100LL
#define GATE_AREA_END 0xa000000000020000LL
#define IA64_LINUX_SIGCONTEXT_OFFSET 192
Functions
static int ia64_linux_pc_in_sigtramp (CORE_ADDR pc)
static CORE_ADDR ia64_linux_sigcontext_register_address (struct gdbarch *gdbarch, CORE_ADDR sp, int regno)
static void ia64_linux_write_pc (struct regcache *regcache, CORE_ADDR pc)
static int ia64_linux_stap_is_single_operand (struct gdbarch *gdbarch, const char *s)
static void ia64_linux_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
void _initialize_ia64_linux_tdep (void)
Variables
initialize_file_ftype _initialize_ia64_linux_tdep
Define Documentation
#define GATE_AREA_END 0xa000000000020000LL
Definition at line 38 of file ia64-linux-tdep.c.
Referenced by ia64_linux_pc_in_sigtramp().
#define GATE_AREA_START 0xa000000000000100LL
Definition at line 37 of file ia64-linux-tdep.c.
Referenced by ia64_linux_pc_in_sigtramp().
#define IA64_LINUX_SIGCONTEXT_OFFSET 192
Definition at line 41 of file ia64-linux-tdep.c.
Function Documentation
void _initialize_ia64_linux_tdep (void)
Definition at line 172 of file ia64-linux-tdep.c.
References _initialize_ia64_linux_tdep, GDB_OSABI_LINUX, gdbarch_register_osabi(), and ia64_linux_init_abi().
static void ia64_linux_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch) [static]
Definition at line 135 of file ia64-linux-tdep.c.
References find_solib_trampoline_target(), gdbarch_tdep(), ia64_linux_pc_in_sigtramp(), ia64_linux_sigcontext_register_address(), ia64_linux_stap_is_single_operand(), ia64_linux_write_pc(), linux_init_abi(), gdbarch_tdep::pc_in_sigtramp, set_gdbarch_fetch_tls_load_module_address(), set_gdbarch_skip_trampoline_code(), set_gdbarch_stap_gdb_register_prefix(), set_gdbarch_stap_is_single_operand(), set_gdbarch_stap_register_indirection_prefix(), set_gdbarch_stap_register_indirection_suffix(), set_gdbarch_stap_register_prefix(), set_gdbarch_write_pc(), set_solib_svr4_fetch_link_map_offsets(), gdbarch_tdep::sigcontext_register_address, svr4_fetch_objfile_link_map(), and svr4_lp64_fetch_link_map_offsets().
Referenced by _initialize_ia64_linux_tdep().
static int ia64_linux_pc_in_sigtramp (CORE_ADDR pc) [static]
Definition at line 44 of file ia64-linux-tdep.c.
References GATE_AREA_END, and GATE_AREA_START.
Referenced by ia64_linux_init_abi().
static CORE_ADDR ia64_linux_sigcontext_register_address (struct gdbarch * gdbarch, CORE_ADDR sp, int regno) [static]
Definition at line 55 of file ia64-linux-tdep.c.
References extract_unsigned_integer(), gdbarch_byte_order(), IA64_BR0_REGNUM, IA64_BR7_REGNUM, IA64_BSP_REGNUM, IA64_CCV_REGNUM, IA64_CFM_REGNUM, IA64_FPSR_REGNUM, IA64_FR0_REGNUM, IA64_FR127_REGNUM, IA64_GR0_REGNUM, IA64_GR31_REGNUM, IA64_IP_REGNUM, IA64_LC_REGNUM, IA64_PFS_REGNUM, IA64_PR_REGNUM, IA64_PSR_REGNUM, IA64_RNAT_REGNUM, IA64_UNAT_REGNUM, and read_memory().
Referenced by ia64_linux_init_abi().
static int ia64_linux_stap_is_single_operand (struct gdbarch * gdbarch, const char * s) [static]
Definition at line 127 of file ia64-linux-tdep.c.
Referenced by ia64_linux_init_abi().
static void ia64_linux_write_pc (struct regcache * regcache, CORE_ADDR pc) [static]
Definition at line 107 of file ia64-linux-tdep.c.
References IA64_GR10_REGNUM, ia64_write_pc(), and regcache_cooked_write_unsigned().
Referenced by ia64_linux_init_abi().
Variable Documentation
initialize_file_ftype _initialize_ia64_linux_tdep
Referenced by _initialize_ia64_linux_tdep().