GDB (xrefs): /home/stan/gdb/src/gdb/ia64-libunwind-tdep.h File Reference
/home/stan/gdb/src/gdb/ia64-libunwind-tdep.h File Reference
#include "libunwind-ia64.h"
Classes
struct libunwind_descr
Functions
int libunwind_frame_sniffer (const struct frame_unwind *self, struct frame_info *this_frame, void **this_cache)
int libunwind_sigtramp_frame_sniffer (const struct frame_unwind *self, struct frame_info *this_frame, void **this_cache)
void libunwind_frame_set_descr (struct gdbarch *arch, struct libunwind_descr *descr)
void libunwind_frame_this_id (struct frame_info *this_frame, void **this_cache, struct frame_id *this_id)
struct value * libunwind_frame_prev_register (struct frame_info *this_frame, void **this_cache, int regnum)
void libunwind_frame_dealloc_cache (struct frame_info *self, void *cache)
int libunwind_is_initialized (void)
int libunwind_search_unwind_table (void *as, long ip, void *di, void *pi, int need_unwind_info, void *args)
unw_word_t libunwind_find_dyn_list (unw_addr_space_t, unw_dyn_info_t *, void *)
int libunwind_get_reg_special (struct gdbarch *gdbarch, struct regcache *regcache, int regnum, void *buf)
Function Documentation
unw_word_t libunwind_find_dyn_list (unw_addr_space_t , unw_dyn_info_t * , void *)
Definition at line 243 of file ia64-libunwind-tdep.c.
References unw_find_dyn_list_p.
void libunwind_frame_dealloc_cache (struct frame_info * self, void * cache)
Definition at line 234 of file ia64-libunwind-tdep.c.
References libunwind_frame_cache::as, and unw_destroy_addr_space_p.
struct value* libunwind_frame_prev_register (struct frame_info * this_frame, void ** this_cache, int regnum) [read]
Definition at line 308 of file ia64-libunwind-tdep.c.
References _, frame_info::addr, libunwind_frame_cache::cursor, error(), frame_unwind_got_bytes(), frame_unwind_got_constant(), frame_unwind_got_memory(), frame_unwind_got_register(), libunwind_descr::gdb2uw, gdb_assert, get_frame_arch(), libunwind_descr::is_fpreg, libunwind_descr(), libunwind_frame_cache(), target_has_registers, unw_get_fpreg_p, unw_get_reg_p, unw_get_saveloc_p, and libunwind_descr::uw2gdb.
void libunwind_frame_set_descr (struct gdbarch * arch, struct libunwind_descr * descr)
Definition at line 133 of file ia64-libunwind-tdep.c.
References libunwind_descr::accessors, deprecated_set_gdbarch_data(), libunwind_descr::gdb2uw, gdb_assert, gdbarch_data(), libunwind_descr::is_fpreg, libunwind_descr_init(), libunwind_descr::special_accessors, and libunwind_descr::uw2gdb.
Referenced by ia64_gdbarch_init(), and ia64_openvms_init_abi().
int libunwind_frame_sniffer (const struct frame_unwind * self, struct frame_info * this_frame, void ** this_cache)
Definition at line 251 of file ia64-libunwind-tdep.c.
References __BIG_ENDIAN, __LITTLE_ENDIAN, libunwind_descr::accessors, libunwind_frame_cache::as, libunwind_frame_cache::cursor, gdbarch_byte_order(), get_frame_arch(), libunwind_descr(), unw_create_addr_space_p, unw_destroy_addr_space_p, unw_init_remote_p, and unw_is_signal_frame_p.
void libunwind_frame_this_id (struct frame_info * this_frame, void ** this_cache, struct frame_id * this_id)
Definition at line 297 of file ia64-libunwind-tdep.c.
References libunwind_frame_cache::base, frame_id_build(), libunwind_frame_cache::func_addr, and libunwind_frame_cache().
int libunwind_get_reg_special (struct gdbarch * gdbarch, struct regcache * regcache, int regnum, void * buf)
Definition at line 441 of file ia64-libunwind-tdep.c.
References __BIG_ENDIAN, __LITTLE_ENDIAN, libunwind_descr::gdb2uw, gdbarch_byte_order(), libunwind_descr::is_fpreg, libunwind_descr(), memcpy(), register_size(), libunwind_descr::special_accessors, unw_create_addr_space_p, unw_destroy_addr_space_p, unw_get_fpreg_p, unw_get_reg_p, and unw_init_remote_p.
Referenced by ia64_pseudo_register_read().
int libunwind_is_initialized (void)
Definition at line 567 of file ia64-libunwind-tdep.c.
References libunwind_initialized.
Referenced by ia64_pseudo_register_read().
int libunwind_search_unwind_table (void * as, long ip, void * di, void * pi, int need_unwind_info, void * args)
Definition at line 383 of file ia64-libunwind-tdep.c.
References unw_search_unwind_table_p.
int libunwind_sigtramp_frame_sniffer (const struct frame_unwind * self, struct frame_info * this_frame, void ** this_cache)
Definition at line 392 of file ia64-libunwind-tdep.c.
References __BIG_ENDIAN, __LITTLE_ENDIAN, libunwind_descr::accessors, gdbarch_byte_order(), get_frame_arch(), libunwind_descr(), unw_create_addr_space_p, unw_destroy_addr_space_p, unw_init_remote_p, and unw_is_signal_frame_p.