GDB (xrefs): /home/stan/gdb/src/gdb/ia64-hpux-nat.c File Reference
/home/stan/gdb/src/gdb/ia64-hpux-nat.c File Reference
#include "defs.h"
#include "ia64-tdep.h"
#include "inferior.h"
#include "inf-ttrace.h"
#include "regcache.h"
#include "solib-ia64-hpux.h"
#include <ia64/sys/uregs.h>
#include <sys/ttrace.h>
Functions
static ptid_t ia64_hpux_wait (struct target_ops *ops, ptid_t ptid, struct target_waitstatus *ourstatus, int options)
static void ia64_hpux_fetch_rnat_register (struct regcache *regcache)
static int ia64_hpux_read_register_from_save_state_t (int offset, gdb_byte *buf, int len)
static void ia64_hpux_fetch_register (struct regcache *regcache, int regnum)
static void ia64_hpux_fetch_registers (struct target_ops *ops, struct regcache *regcache, int regnum)
static int ia64_hpux_write_register_to_saved_state_t (int offset, gdb_byte *buf, int len)
static void ia64_hpux_store_register (const struct regcache *regcache, int regnum)
static void ia64_hpux_store_registers (struct target_ops *ops, struct regcache *regcache, int regnum)
static LONGEST ia64_hpux_xfer_memory_no_bs (struct target_ops *ops, const char *annex, gdb_byte *readbuf, const gdb_byte *writebuf, CORE_ADDR addr, LONGEST len)
static int ia64_hpux_read_memory_bs (gdb_byte *buf, CORE_ADDR addr, int len)
static int ia64_hpux_write_memory_bs (const gdb_byte *buf, CORE_ADDR addr, int len)
static LONGEST ia64_hpux_xfer_memory_bs (struct target_ops *ops, const char *annex, gdb_byte *readbuf, const gdb_byte *writebuf, CORE_ADDR addr, LONGEST len)
static ULONGEST ia64_hpux_get_register_from_save_state_t (int regnum, int reg_size)
static LONGEST ia64_hpux_xfer_memory (struct target_ops *ops, const char *annex, gdb_byte *readbuf, const gdb_byte *writebuf, CORE_ADDR addr, LONGEST len)
static LONGEST ia64_hpux_xfer_uregs (struct target_ops *ops, const char *annex, gdb_byte *readbuf, const gdb_byte *writebuf, ULONGEST offset, LONGEST len)
static LONGEST ia64_hpux_xfer_solib_got (struct target_ops *ops, const char *annex, gdb_byte *readbuf, const gdb_byte *writebuf, ULONGEST offset, LONGEST len)
static LONGEST ia64_hpux_xfer_partial (struct target_ops *ops, enum target_object object, const char *annex, gdb_byte *readbuf, const gdb_byte *writebuf, ULONGEST offset, LONGEST len)
static int ia64_hpux_can_use_hw_breakpoint (int type, int cnt, int othertype)
static void ia64_hpux_mourn_inferior (struct target_ops *ops)
void _initialize_ia64_hpux_nat (void)
Variables
static int u_offsets []
static const char r0_value [8]
static const char f0_value [16]
static const char f1_value [16]
static ptid_t(* super_to_wait)(struct target_ops *, ptid_t, struct target_waitstatus *, int)
static LONGEST(* super_xfer_partial)(struct target_ops *, enum target_object, const char *, gdb_byte *, const gdb_byte *, ULONGEST, LONGEST)
static void(* super_mourn_inferior)(struct target_ops *)
Function Documentation
void _initialize_ia64_hpux_nat (void)
Definition at line 731 of file ia64-hpux-nat.c.
References add_target(), ia64_hpux_can_use_hw_breakpoint(), ia64_hpux_fetch_registers(), ia64_hpux_mourn_inferior(), ia64_hpux_store_registers(), ia64_hpux_wait(), ia64_hpux_xfer_partial(), inf_ttrace_target(), super_mourn_inferior, super_to_wait, super_xfer_partial, target_ops::to_attach_no_wait, target_ops::to_can_use_hw_breakpoint, target_ops::to_fetch_registers, target_ops::to_mourn_inferior, target_ops::to_store_registers, target_ops::to_wait, and target_ops::to_xfer_partial.
static int ia64_hpux_can_use_hw_breakpoint (int type, int cnt, int othertype) [static]
Definition at line 699 of file ia64-hpux-nat.c.
Referenced by _initialize_ia64_hpux_nat().
static void ia64_hpux_fetch_register (struct regcache * regcache, int regnum) [static]
Definition at line 212 of file ia64-hpux-nat.c.
References _, f0_value, f1_value, gdbarch_register_name(), get_regcache_arch(), IA64_FR0_REGNUM, IA64_FR1_REGNUM, IA64_GR0_REGNUM, ia64_hpux_fetch_rnat_register(), ia64_hpux_read_register_from_save_state_t(), IA64_RNAT_REGNUM, len, offset, r0_value, regcache_raw_supply(), register_size(), regnum, exsummary::status, u_offsets, and warning().
Referenced by ia64_hpux_fetch_registers().
static void ia64_hpux_fetch_registers (struct target_ops * ops, struct regcache * regcache, int regnum) [static]
Definition at line 264 of file ia64-hpux-nat.c.
References gdbarch_num_regs(), get_regcache_arch(), and ia64_hpux_fetch_register().
Referenced by _initialize_ia64_hpux_nat().
static void ia64_hpux_fetch_rnat_register (struct regcache * regcache) [static]
Definition at line 172 of file ia64-hpux-nat.c.
References _, error(), get_regcache_arch(), IA64_BSP_REGNUM, IA64_RNAT_REGNUM, inferior_ptid, paddress(), ptid_get_lwp(), ptid_get_pid(), regcache_raw_read_unsigned(), regcache_raw_supply(), and exsummary::status.
Referenced by ia64_hpux_fetch_register().
static ULONGEST ia64_hpux_get_register_from_save_state_t (int regnum, int reg_size) [static]
Definition at line 495 of file ia64-hpux-nat.c.
References _, extract_unsigned_integer(), gdb_assert, ia64_hpux_read_register_from_save_state_t(), offset, regnum, exsummary::status, u_offsets, and warning().
Referenced by ia64_hpux_xfer_memory().
static void ia64_hpux_mourn_inferior (struct target_ops * ops) [static]
Definition at line 712 of file ia64-hpux-nat.c.
References inferior_ptid, ptid_get_pid(), exsummary::status, and super_mourn_inferior.
Referenced by _initialize_ia64_hpux_nat().
static int ia64_hpux_read_memory_bs (gdb_byte * buf, CORE_ADDR addr, int len) [static]
Definition at line 391 of file ia64-hpux-nat.c.
References inferior_ptid, len, memcpy(), ptid_get_lwp(), ptid_get_pid(), and exsummary::status.
Referenced by ia64_hpux_write_memory_bs(), and ia64_hpux_xfer_memory_bs().
static int ia64_hpux_read_register_from_save_state_t (int offset, gdb_byte * buf, int len) [static]
Definition at line 199 of file ia64-hpux-nat.c.
References inferior_ptid, ptid_get_lwp(), ptid_get_pid(), and exsummary::status.
Referenced by ia64_hpux_fetch_register(), ia64_hpux_get_register_from_save_state_t(), and ia64_hpux_xfer_uregs().
static void ia64_hpux_store_register (const struct regcache * regcache, int regnum) [static]
Definition at line 292 of file ia64-hpux-nat.c.
References _, error(), gdbarch_register_name(), get_regcache_arch(), ia64_hpux_write_register_to_saved_state_t(), IA64_PSR_REGNUM, len, offset, regcache_raw_collect(), register_size(), regnum, exsummary::status, and u_offsets.
Referenced by ia64_hpux_store_registers().
static void ia64_hpux_store_registers (struct target_ops * ops, struct regcache * regcache, int regnum) [static]
Definition at line 322 of file ia64-hpux-nat.c.
References gdbarch_num_regs(), get_regcache_arch(), and ia64_hpux_store_register().
Referenced by _initialize_ia64_hpux_nat().
static ptid_t ia64_hpux_wait (struct target_ops * ops, ptid_t ptid, struct target_waitstatus * ourstatus, int options) [static]
Definition at line 145 of file ia64-hpux-nat.c.
References ia64_hpux_at_dld_breakpoint_p(), ia64_hpux_handle_dld_breakpoint(), target_waitstatus::kind, target_waitstatus::sig, super_to_wait, target_resume(), TARGET_WAITKIND_IGNORE, TARGET_WAITKIND_STOPPED, and target_waitstatus::value.
Referenced by _initialize_ia64_hpux_nat().
static int ia64_hpux_write_memory_bs (const gdb_byte * buf, CORE_ADDR addr, int len) [static]
Definition at line 430 of file ia64-hpux-nat.c.
References ia64_hpux_read_memory_bs(), inferior_ptid, memcpy(), ptid_get_lwp(), ptid_get_pid(), and exsummary::status.
Referenced by ia64_hpux_xfer_memory_bs().
static int ia64_hpux_write_register_to_saved_state_t (int offset, gdb_byte * buf, int len) [static]
Definition at line 283 of file ia64-hpux-nat.c.
References inferior_ptid, ptid_get_lwp(), and ptid_get_pid().
Referenced by ia64_hpux_store_register().
static LONGEST ia64_hpux_xfer_memory (struct target_ops * ops, const char * annex, gdb_byte * readbuf, const gdb_byte * writebuf, CORE_ADDR addr, LONGEST len) [static]
Definition at line 523 of file ia64-hpux-nat.c.
References gdb_assert, get_current_regcache(), IA64_BSP_REGNUM, IA64_BSPSTORE_REGNUM, ia64_hpux_get_register_from_save_state_t(), ia64_hpux_xfer_memory_bs(), ia64_hpux_xfer_memory_no_bs(), in_inferior_list(), inferior_ptid, len, ptid_get_pid(), regcache_raw_read_unsigned(), and exsummary::status.
Referenced by ia64_hpux_xfer_partial().
static LONGEST ia64_hpux_xfer_memory_bs (struct target_ops * ops, const char * annex, gdb_byte * readbuf, const gdb_byte * writebuf, CORE_ADDR addr, LONGEST len) [static]
Definition at line 471 of file ia64-hpux-nat.c.
References ia64_hpux_read_memory_bs(), ia64_hpux_write_memory_bs(), and len.
Referenced by ia64_hpux_xfer_memory().
static LONGEST ia64_hpux_xfer_memory_no_bs (struct target_ops * ops, const char * annex, gdb_byte * readbuf, const gdb_byte * writebuf, CORE_ADDR addr, LONGEST len) [static]
Definition at line 348 of file ia64-hpux-nat.c.
References LONGEST, memcpy(), exsummary::status, super_xfer_partial, and TARGET_OBJECT_MEMORY.
Referenced by ia64_hpux_xfer_memory().
static LONGEST ia64_hpux_xfer_partial (struct target_ops * ops, enum target_object object, const char * annex, gdb_byte * readbuf, const gdb_byte * writebuf, ULONGEST offset, LONGEST len) [static]
Definition at line 676 of file ia64-hpux-nat.c.
References ia64_hpux_xfer_memory(), ia64_hpux_xfer_solib_got(), ia64_hpux_xfer_uregs(), LONGEST, super_xfer_partial, TARGET_OBJECT_HPUX_SOLIB_GOT, TARGET_OBJECT_HPUX_UREGS, and TARGET_OBJECT_MEMORY.
Referenced by _initialize_ia64_hpux_nat().
static LONGEST ia64_hpux_xfer_solib_got (struct target_ops * ops, const char * annex, gdb_byte * readbuf, const gdb_byte * writebuf, ULONGEST offset, LONGEST len) [static]
Definition at line 646 of file ia64-hpux-nat.c.
References gdb_assert, ia64_hpux_get_solib_linkage_addr(), len, memcpy(), and string_to_core_addr().
Referenced by ia64_hpux_xfer_partial().
static LONGEST ia64_hpux_xfer_uregs (struct target_ops * ops, const char * annex, gdb_byte * readbuf, const gdb_byte * writebuf, ULONGEST offset, LONGEST len) [static]
Definition at line 625 of file ia64-hpux-nat.c.
References gdb_assert, ia64_hpux_read_register_from_save_state_t(), len, and exsummary::status.
Referenced by ia64_hpux_xfer_partial().
Variable Documentation
const char f0_value[16] [static]
Initial value:
 {0x00, 0x00, 0x00, 0x00,
                                  0x00, 0x00, 0x00, 0x00,
                                  0x00, 0x00, 0x00, 0x00,
                                  0x00, 0x00, 0x00, 0x00}
Definition at line 128 of file ia64-hpux-nat.c.
Referenced by ia64_hpux_fetch_register().
const char f1_value[16] [static]
Initial value:
 {0x00, 0x00, 0x00, 0x00,
                                  0x00, 0x00, 0xff, 0xff,
                                  0x80, 0x00, 0x00, 0x00,
                                  0x00, 0x00, 0x00, 0x00}
Definition at line 132 of file ia64-hpux-nat.c.
Referenced by ia64_hpux_fetch_register().
const char r0_value[8] [static]
Initial value:
 {0x00, 0x00, 0x00, 0x00,
                                 0x00, 0x00, 0x00, 0x00}
Definition at line 126 of file ia64-hpux-nat.c.
Referenced by ia64_hpux_fetch_register().
void(* super_mourn_inferior)(struct target_ops *) [static]
Definition at line 707 of file ia64-hpux-nat.c.
Referenced by _initialize_ia64_hpux_nat(), and ia64_hpux_mourn_inferior().
ptid_t(* super_to_wait)(struct target_ops *, ptid_t, struct target_waitstatus *, int) [static]
Definition at line 139 of file ia64-hpux-nat.c.
Referenced by _initialize_ia64_hpux_nat(), and ia64_hpux_wait().
LONGEST(* super_xfer_partial)(struct target_ops *, enum target_object, const char *, gdb_byte *, const gdb_byte *, ULONGEST, LONGEST) [static]
Definition at line 340 of file ia64-hpux-nat.c.
Referenced by _initialize_ia64_hpux_nat(), ia64_hpux_xfer_memory_no_bs(), and ia64_hpux_xfer_partial().
int u_offsets[] [static]
Definition at line 30 of file ia64-hpux-nat.c.
Referenced by ia64_hpux_fetch_register(), ia64_hpux_get_register_from_save_state_t(), and ia64_hpux_store_register().