GDB (xrefs): /home/stan/gdb/src/gdb/ia64-hpux-tdep.c File Reference
/home/stan/gdb/src/gdb/ia64-hpux-tdep.c File Reference
#include "defs.h"
#include "ia64-tdep.h"
#include "ia64-hpux-tdep.h"
#include "osabi.h"
#include "gdbtypes.h"
#include "solib.h"
#include "target.h"
#include "frame.h"
#include "regcache.h"
#include "gdbcore.h"
#include "inferior.h"
Defines
#define IA64_HPUX_UREG_REASON 0x00070000
Functions
static int ia64_hpux_can_store_ar_register (int regnum)
static int ia64_hpux_cannot_store_register (struct gdbarch *gdbarch, int regnum)
static int ia64_hpux_stopped_in_syscall (struct gdbarch *gdbarch)
static int ia64_hpux_size_of_register_frame (struct frame_info *this_frame, ULONGEST cfm)
static CORE_ADDR ia64_hpux_push_dummy_code (struct gdbarch *gdbarch, CORE_ADDR sp, CORE_ADDR funaddr, struct value **args, int nargs, struct type *value_type, CORE_ADDR *real_pc, CORE_ADDR *bp_addr, struct regcache *regcache)
static void ia64_hpux_allocate_new_rse_frame (struct regcache *regcache, ULONGEST bsp, int sof)
static void ia64_hpux_store_argument_in_slot (struct regcache *regcache, CORE_ADDR bsp, int slotnum, gdb_byte *buf)
static void ia64_hpux_set_function_addr (struct regcache *regcache, CORE_ADDR func_addr)
static struct frame_id ia64_hpux_dummy_id (struct gdbarch *gdbarch, struct frame_info *this_frame)
static CORE_ADDR ia64_hpux_find_global_pointer_from_solib (struct gdbarch *gdbarch, CORE_ADDR faddr)
static void ia64_hpux_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
void _initialize_ia64_hpux_tdep (void)
Variables
static const gdb_byte ia64_hpux_dummy_code []
static struct ia64_infcall_ops ia64_hpux_infcall_ops
struct target_so_ops * ia64_hpux_so_ops = NULL
initialize_file_ftype _initialize_ia64_hpux_tdep
Define Documentation
#define IA64_HPUX_UREG_REASON 0x00070000
Definition at line 163 of file ia64-hpux-tdep.c.
Referenced by ia64_hpux_stopped_in_syscall().
Function Documentation
void _initialize_ia64_hpux_tdep (void)
Definition at line 430 of file ia64-hpux-tdep.c.
References _initialize_ia64_hpux_tdep, GDB_OSABI_HPUX_ELF, gdbarch_register_osabi(), and ia64_hpux_init_abi().
static void ia64_hpux_allocate_new_rse_frame (struct regcache * regcache, ULONGEST bsp, int sof) [static]
Definition at line 314 of file ia64-hpux-tdep.c.
static int ia64_hpux_can_store_ar_register (int regnum) [static]
Definition at line 169 of file ia64-hpux-tdep.c.
References IA64_CCV_REGNUM, IA64_CSD_REGNUM, IA64_EC_REGNUM, IA64_FPSR_REGNUM, IA64_LC_REGNUM, IA64_PFS_REGNUM, IA64_RNAT_REGNUM, IA64_RSC_REGNUM, IA64_SSD_REGNUM, and IA64_UNAT_REGNUM.
Referenced by ia64_hpux_cannot_store_register().
static int ia64_hpux_cannot_store_register (struct gdbarch * gdbarch, int regnum) [static]
Definition at line 195 of file ia64-hpux-tdep.c.
References IA64_AR0_REGNUM, IA64_FR0_REGNUM, IA64_FR1_REGNUM, IA64_GR0_REGNUM, and ia64_hpux_can_store_ar_register().
Referenced by ia64_hpux_init_abi().
static struct frame_id ia64_hpux_dummy_id (struct gdbarch * gdbarch, struct frame_info * this_frame) [static, read]
Definition at line 354 of file ia64-hpux-tdep.c.
References frame_id_build_special(), get_frame_pc(), get_frame_register_unsigned(), IA64_BSP_REGNUM, IA64_GR12_REGNUM, IA64_GR5_REGNUM, ia64_hpux_dummy_code, null_frame_id, and sp.
Referenced by ia64_hpux_init_abi().
static CORE_ADDR ia64_hpux_find_global_pointer_from_solib (struct gdbarch * gdbarch, CORE_ADDR faddr) [static]
Definition at line 390 of file ia64-hpux-tdep.c.
References current_target, extract_unsigned_integer(), gdbarch_byte_order(), len, LONGEST, paddress(), TARGET_OBJECT_HPUX_SOLIB_GOT, and target_read().
Referenced by ia64_hpux_init_abi().
static void ia64_hpux_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch) [static]
Definition at line 405 of file ia64-hpux-tdep.c.
References gdbarch_tdep::find_global_pointer_from_solib, floatformats_ia64_quad, gdbarch_tdep(), ia64_hpux_cannot_store_register(), ia64_hpux_dummy_id(), ia64_hpux_find_global_pointer_from_solib(), ia64_hpux_infcall_ops, ia64_hpux_push_dummy_code(), ia64_hpux_size_of_register_frame(), gdbarch_tdep::infcall_ops, ON_STACK, set_gdbarch_call_dummy_location(), set_gdbarch_cannot_store_register(), set_gdbarch_dummy_id(), set_gdbarch_long_double_format(), set_gdbarch_push_dummy_code(), set_solib_ops(), and gdbarch_tdep::size_of_register_frame.
Referenced by _initialize_ia64_hpux_tdep().
static CORE_ADDR ia64_hpux_push_dummy_code (struct gdbarch * gdbarch, CORE_ADDR sp, CORE_ADDR funaddr, struct value ** args, int nargs, struct type * value_type, CORE_ADDR * real_pc, CORE_ADDR * bp_addr, struct regcache * regcache) [static]
Definition at line 261 of file ia64-hpux-tdep.c.
References IA64_CFM_REGNUM, ia64_hpux_dummy_code, memcpy(), regcache_cooked_read_unsigned(), ULONGEST, and write_memory().
Referenced by ia64_hpux_init_abi().
static void ia64_hpux_set_function_addr (struct regcache * regcache, CORE_ADDR func_addr) [static]
Definition at line 335 of file ia64-hpux-tdep.c.
References IA64_BR1_REGNUM, and regcache_cooked_write_unsigned().
static int ia64_hpux_size_of_register_frame (struct frame_info * this_frame, ULONGEST cfm) [static]
Definition at line 239 of file ia64-hpux-tdep.c.
References frame_relative_level(), get_frame_arch(), and ia64_hpux_stopped_in_syscall().
Referenced by ia64_hpux_init_abi().
static int ia64_hpux_stopped_in_syscall (struct gdbarch * gdbarch) [static]
Definition at line 218 of file ia64-hpux-tdep.c.
References current_target, extract_unsigned_integer(), gdb_assert, gdbarch_byte_order(), IA64_HPUX_UREG_REASON, len, TARGET_OBJECT_HPUX_UREGS, and target_read().
Referenced by ia64_hpux_size_of_register_frame().
static void ia64_hpux_store_argument_in_slot (struct regcache * regcache, CORE_ADDR bsp, int slotnum, gdb_byte * buf) [static]
Definition at line 324 of file ia64-hpux-tdep.c.
References IA64_GR0_REGNUM, and regcache_cooked_write().
Variable Documentation
initialize_file_ftype _initialize_ia64_hpux_tdep
Referenced by _initialize_ia64_hpux_tdep().
const gdb_byte ia64_hpux_dummy_code[] [static]
Definition at line 124 of file ia64-hpux-tdep.c.
Referenced by ia64_hpux_dummy_id(), and ia64_hpux_push_dummy_code().
struct ia64_infcall_ops ia64_hpux_infcall_ops [static]
Initial value:
{
  ia64_hpux_allocate_new_rse_frame,
  ia64_hpux_store_argument_in_slot,
  ia64_hpux_set_function_addr
}
Definition at line 344 of file ia64-hpux-tdep.c.
Referenced by ia64_hpux_init_abi().
struct target_so_ops* ia64_hpux_so_ops = NULL
Definition at line 384 of file ia64-hpux-tdep.c.
Referenced by _initialize_solib_ia64_hpux().