GDB (xrefs): /home/stan/gdb/src/gdb/inf-loop.h File Reference
/home/stan/gdb/src/gdb/inf-loop.h File Reference
Functions
void inferior_event_handler (enum inferior_event_type event_type, void *client_data)
Function Documentation
void inferior_event_handler (enum inferior_event_type event_type, void * client_data)
Definition at line 41 of file inf-loop.c.
References _, async_enable_stdin(), bpstat_clear_actions(), bpstat_do_actions(), catch_errors(), check_frame_language_change(), discard_cleanups(), display_gdb_prompt(), do_all_continuations(), do_all_continuations_thread(), do_all_inferior_continuations(), do_all_intermediate_continuations(), do_all_intermediate_continuations_thread(), exception_print(), fetch_inferior_event_wrapper(), gdb_stderr, INF_EXEC_COMPLETE, INF_EXEC_CONTINUE, INF_REG_EVENT, INF_TIMER, inferior_ptid, inferior_thread(), interpreter_async, make_bpstat_clear_actions_cleanup(), non_stop, null_ptid, printf_unfiltered(), ptid_equal(), RETURN_MASK_ALL, target_async, target_has_execution, and TRY_CATCH.
Referenced by extended_remote_attach_1(), extended_remote_create_inferior_1(), fetch_inferior_event(), linux_nat_attach(), linux_nat_resume(), linux_nat_wait(), proceed(), record_full_async_inferior_event_handler(), record_full_core_resume(), record_full_resume(), remote_async_inferior_event_handler(), remote_resume(), remote_start_remote(), and step_once().