GDB (xrefs): /home/stan/gdb/src/gdb/inf-child.h File Reference
/home/stan/gdb/src/gdb/inf-child.h File Reference
Functions
struct target_ops * inf_child_target (void)
void store_waitstatus (struct target_waitstatus *, int)
Function Documentation
struct target_ops* inf_child_target (void) [read]
Definition at line 387 of file inf-child.c.
References child_terminal_info(), default_child_has_all_memory(), default_child_has_execution(), default_child_has_memory(), default_child_has_registers(), default_child_has_stack(), inf_child_can_run(), inf_child_can_use_agent(), inf_child_fetch_inferior_registers(), inf_child_fileio_close(), inf_child_fileio_open(), inf_child_fileio_pread(), inf_child_fileio_pwrite(), inf_child_fileio_readlink(), inf_child_fileio_unlink(), inf_child_follow_fork(), inf_child_open(), inf_child_pid_to_exec_file(), inf_child_post_attach(), inf_child_post_startup_inferior(), inf_child_prepare_to_store(), inf_child_store_inferior_registers(), inf_child_use_agent(), memory_insert_breakpoint(), memory_remove_breakpoint(), OPS_MAGIC, process_stratum, terminal_inferior(), terminal_init_inferior(), terminal_ours(), terminal_ours_for_output(), terminal_save_ours(), target_ops::to_can_run, target_ops::to_can_use_agent, target_ops::to_doc, target_ops::to_fetch_registers, target_ops::to_fileio_close, target_ops::to_fileio_open, target_ops::to_fileio_pread, target_ops::to_fileio_pwrite, target_ops::to_fileio_readlink, target_ops::to_fileio_unlink, target_ops::to_follow_fork, target_ops::to_has_all_memory, target_ops::to_has_execution, target_ops::to_has_memory, target_ops::to_has_registers, target_ops::to_has_stack, target_ops::to_insert_breakpoint, target_ops::to_longname, target_ops::to_magic, target_ops::to_open, target_ops::to_pid_to_exec_file, target_ops::to_post_attach, target_ops::to_post_startup_inferior, target_ops::to_prepare_to_store, target_ops::to_remove_breakpoint, target_ops::to_shortname, target_ops::to_store_registers, target_ops::to_stratum, target_ops::to_terminal_inferior, target_ops::to_terminal_info, target_ops::to_terminal_init, target_ops::to_terminal_ours, target_ops::to_terminal_ours_for_output, target_ops::to_terminal_save_ours, target_ops::to_use_agent, and XZALLOC.
Referenced by _initialize_darwin_inferior(), gnu_target(), inf_ptrace_target(), and procfs_target().
void store_waitstatus (struct target_waitstatus * , int)
Definition at line 43 of file inf-child.c.
References gdb_signal_from_host(), target_waitstatus::integer, target_waitstatus::kind, target_waitstatus::sig, TARGET_WAITKIND_EXITED, TARGET_WAITKIND_SIGNALLED, TARGET_WAITKIND_STOPPED, and target_waitstatus::value.
Referenced by inf_ptrace_wait(), linux_nat_wait_1(), procfs_wait(), rs6000_wait(), S_proc_wait_reply(), and spu_child_wait().