GDB (xrefs): /home/stan/gdb/src/gdb/inf-ptrace.h File Reference
/home/stan/gdb/src/gdb/inf-ptrace.h File Reference
Functions
struct target_ops * inf_ptrace_target (void)
struct target_ops * inf_ptrace_trad_target (CORE_ADDR(*register_u_offset)(struct gdbarch *, int, int))
Function Documentation
struct target_ops* inf_ptrace_target (void) [read]
Definition at line 678 of file inf-ptrace.c.
References inf_child_target(), inf_ptrace_attach(), inf_ptrace_create_inferior(), inf_ptrace_detach(), inf_ptrace_files_info(), inf_ptrace_kill(), inf_ptrace_mourn_inferior(), inf_ptrace_pid_to_str(), inf_ptrace_resume(), inf_ptrace_stop(), inf_ptrace_thread_alive(), inf_ptrace_wait(), inf_ptrace_xfer_partial, target_ops::to_attach, target_ops::to_auxv_parse, target_ops::to_create_inferior, target_ops::to_detach, target_ops::to_files_info, target_ops::to_follow_fork, target_ops::to_kill, target_ops::to_mourn_inferior, target_ops::to_pid_to_str, target_ops::to_post_attach, target_ops::to_post_startup_inferior, target_ops::to_resume, target_ops::to_stop, target_ops::to_thread_alive, target_ops::to_wait, and target_ops::to_xfer_partial.
Referenced by _initialize_alphabsd_nat(), _initialize_arm_netbsd_nat(), _initialize_hppa_hpux_nat(), _initialize_hppabsd_nat(), _initialize_hppanbsd_nat(), _initialize_m68kbsd_nat(), _initialize_m88kbsd_nat(), _initialize_mips64obsd_nat(), _initialize_mipsnbsd_nat(), _initialize_ppcfbsd_nat(), _initialize_ppcnbsd_nat(), _initialize_ppcobsd_nat(), _initialize_rs6000_nat(), _initialize_shnbsd_nat(), _initialize_spu_nat(), _initialize_vaxbsd_nat(), amd64bsd_target(), i386bsd_target(), inf_ptrace_trad_target(), linux_target(), and sparc_target().
struct target_ops* inf_ptrace_trad_target (CORE_ADDR(*)(struct gdbarch *, int, int) register_u_offset) [read]
Definition at line 835 of file inf-ptrace.c.
References gdb_assert, inf_ptrace_fetch_registers(), inf_ptrace_register_u_offset, inf_ptrace_store_registers(), inf_ptrace_target(), target_ops::to_fetch_registers, and target_ops::to_store_registers.
Referenced by _initialize_vax_nat(), and linux_trad_target().