GDB (xrefs): /home/stan/gdb/src/gdb/inf-child.c File Reference
/home/stan/gdb/src/gdb/inf-child.c File Reference
#include "defs.h"
#include "regcache.h"
#include "memattr.h"
#include "symtab.h"
#include "target.h"
#include "inferior.h"
#include "gdb_string.h"
#include "gdb_stat.h"
#include "inf-child.h"
#include "gdb/fileio.h"
#include "agent.h"
#include "gdb_wait.h"
#include "filestuff.h"
#include <sys/types.h>
#include <fcntl.h>
#include <unistd.h>
Functions
void store_waitstatus (struct target_waitstatus *ourstatus, int hoststatus)
static void inf_child_fetch_inferior_registers (struct target_ops *ops, struct regcache *regcache, int regnum)
static void inf_child_store_inferior_registers (struct target_ops *ops, struct regcache *regcache, int regnum)
static void inf_child_post_attach (int pid)
static void inf_child_prepare_to_store (struct regcache *regcache)
static void inf_child_open (char *arg, int from_tty)
static void inf_child_post_startup_inferior (ptid_t ptid)
static int inf_child_follow_fork (struct target_ops *ops, int follow_child, int detach_fork)
static int inf_child_can_run (void)
static char * inf_child_pid_to_exec_file (int pid)
static int inf_child_fileio_open_flags_to_host (int fileio_open_flags, int *open_flags_p)
static int inf_child_errno_to_fileio_error (int errnum)
static int inf_child_fileio_open (const char *filename, int flags, int mode, int *target_errno)
static int inf_child_fileio_pwrite (int fd, const gdb_byte *write_buf, int len, ULONGEST offset, int *target_errno)
static int inf_child_fileio_pread (int fd, gdb_byte *read_buf, int len, ULONGEST offset, int *target_errno)
static int inf_child_fileio_close (int fd, int *target_errno)
static int inf_child_fileio_unlink (const char *filename, int *target_errno)
static char * inf_child_fileio_readlink (const char *filename, int *target_errno)
static int inf_child_use_agent (int use)
static int inf_child_can_use_agent (void)
struct target_ops * inf_child_target (void)
Function Documentation
static int inf_child_can_run (void) [static]
Definition at line 130 of file inf-child.c.
Referenced by inf_child_target().
static int inf_child_can_use_agent (void) [static]
Definition at line 381 of file inf-child.c.
References agent_loaded_p().
Referenced by inf_child_target().
static int inf_child_errno_to_fileio_error (int errnum) [static]
Definition at line 179 of file inf-child.c.
Referenced by inf_child_fileio_close(), inf_child_fileio_open(), inf_child_fileio_pread(), inf_child_fileio_pwrite(), inf_child_fileio_readlink(), and inf_child_fileio_unlink().
static void inf_child_fetch_inferior_registers (struct target_ops * ops, struct regcache * regcache, int regnum) [static]
Definition at line 66 of file inf-child.c.
References gdbarch_num_regs(), get_regcache_arch(), and regcache_raw_supply().
Referenced by inf_child_target().
static int inf_child_fileio_close (int fd, int * target_errno) [static]
Definition at line 313 of file inf-child.c.
References inf_child_errno_to_fileio_error().
Referenced by inf_child_target().
static int inf_child_fileio_open (const char * filename, int flags, int mode, int * target_errno) [static]
Definition at line 233 of file inf-child.c.
References gdb_open_cloexec(), inf_child_errno_to_fileio_error(), and inf_child_fileio_open_flags_to_host().
Referenced by inf_child_target().
static int inf_child_fileio_open_flags_to_host (int fileio_open_flags, int * open_flags_p) [static]
Definition at line 147 of file inf-child.c.
Referenced by inf_child_fileio_open().
static int inf_child_fileio_pread (int fd, gdb_byte * read_buf, int len, ULONGEST offset, int * target_errno) [static]
Definition at line 286 of file inf-child.c.
References inf_child_errno_to_fileio_error(), and read().
Referenced by inf_child_target().
static int inf_child_fileio_pwrite (int fd, const gdb_byte * write_buf, int len, ULONGEST offset, int * target_errno) [static]
Definition at line 258 of file inf-child.c.
References inf_child_errno_to_fileio_error().
Referenced by inf_child_target().
static char* inf_child_fileio_readlink (const char * filename, int * target_errno) [static]
Definition at line 342 of file inf-child.c.
References inf_child_errno_to_fileio_error(), len, memcpy(), and xmalloc().
Referenced by inf_child_target().
static int inf_child_fileio_unlink (const char * filename, int * target_errno) [static]
Definition at line 327 of file inf-child.c.
References inf_child_errno_to_fileio_error().
Referenced by inf_child_target().
static int inf_child_follow_fork (struct target_ops * ops, int follow_child, int detach_fork) [static]
Definition at line 121 of file inf-child.c.
Referenced by inf_child_target().
static void inf_child_open (char * arg, int from_tty) [static]
Definition at line 108 of file inf-child.c.
References _, and error().
Referenced by inf_child_target().
static char* inf_child_pid_to_exec_file (int pid) [static]
Definition at line 136 of file inf-child.c.
Referenced by inf_child_target().
static void inf_child_post_attach (int pid) [static]
Definition at line 90 of file inf-child.c.
Referenced by inf_child_target().
static void inf_child_post_startup_inferior (ptid_t ptid) [static]
Definition at line 114 of file inf-child.c.
Referenced by inf_child_target().
static void inf_child_prepare_to_store (struct regcache * regcache) [static]
Definition at line 103 of file inf-child.c.
Referenced by inf_child_target().
static void inf_child_store_inferior_registers (struct target_ops * ops, struct regcache * regcache, int regnum) [static]
Definition at line 84 of file inf-child.c.
Referenced by inf_child_target().
struct target_ops* inf_child_target (void) [read]
Definition at line 387 of file inf-child.c.
References child_terminal_info(), default_child_has_all_memory(), default_child_has_execution(), default_child_has_memory(), default_child_has_registers(), default_child_has_stack(), inf_child_can_run(), inf_child_can_use_agent(), inf_child_fetch_inferior_registers(), inf_child_fileio_close(), inf_child_fileio_open(), inf_child_fileio_pread(), inf_child_fileio_pwrite(), inf_child_fileio_readlink(), inf_child_fileio_unlink(), inf_child_follow_fork(), inf_child_open(), inf_child_pid_to_exec_file(), inf_child_post_attach(), inf_child_post_startup_inferior(), inf_child_prepare_to_store(), inf_child_store_inferior_registers(), inf_child_use_agent(), memory_insert_breakpoint(), memory_remove_breakpoint(), OPS_MAGIC, process_stratum, terminal_inferior(), terminal_init_inferior(), terminal_ours(), terminal_ours_for_output(), terminal_save_ours(), target_ops::to_can_run, target_ops::to_can_use_agent, target_ops::to_doc, target_ops::to_fetch_registers, target_ops::to_fileio_close, target_ops::to_fileio_open, target_ops::to_fileio_pread, target_ops::to_fileio_pwrite, target_ops::to_fileio_readlink, target_ops::to_fileio_unlink, target_ops::to_follow_fork, target_ops::to_has_all_memory, target_ops::to_has_execution, target_ops::to_has_memory, target_ops::to_has_registers, target_ops::to_has_stack, target_ops::to_insert_breakpoint, target_ops::to_longname, target_ops::to_magic, target_ops::to_open, target_ops::to_pid_to_exec_file, target_ops::to_post_attach, target_ops::to_post_startup_inferior, target_ops::to_prepare_to_store, target_ops::to_remove_breakpoint, target_ops::to_shortname, target_ops::to_store_registers, target_ops::to_stratum, target_ops::to_terminal_inferior, target_ops::to_terminal_info, target_ops::to_terminal_init, target_ops::to_terminal_ours, target_ops::to_terminal_ours_for_output, target_ops::to_terminal_save_ours, target_ops::to_use_agent, and XZALLOC.
Referenced by _initialize_darwin_inferior(), gnu_target(), inf_ptrace_target(), and procfs_target().
static int inf_child_use_agent (int use) [static]
Definition at line 369 of file inf-child.c.
References agent_loaded_p(), and use_agent.
Referenced by inf_child_target().
void store_waitstatus (struct target_waitstatus * ourstatus, int hoststatus)
Definition at line 43 of file inf-child.c.
References gdb_signal_from_host(), target_waitstatus::integer, target_waitstatus::kind, target_waitstatus::sig, TARGET_WAITKIND_EXITED, TARGET_WAITKIND_SIGNALLED, TARGET_WAITKIND_STOPPED, and target_waitstatus::value.
Referenced by inf_ptrace_wait(), linux_nat_wait_1(), procfs_wait(), rs6000_wait(), S_proc_wait_reply(), and spu_child_wait().