GDB (xrefs): /home/stan/gdb/src/gdb/infcmd.c File Reference
/home/stan/gdb/src/gdb/infcmd.c File Reference
#include "defs.h"
#include "arch-utils.h"
#include <signal.h>
#include "gdb_string.h"
#include "symtab.h"
#include "gdbtypes.h"
#include "frame.h"
#include "inferior.h"
#include "environ.h"
#include "value.h"
#include "gdbcmd.h"
#include "symfile.h"
#include "gdbcore.h"
#include "target.h"
#include "language.h"
#include "objfiles.h"
#include "completer.h"
#include "ui-out.h"
#include "event-top.h"
#include "parser-defs.h"
#include "regcache.h"
#include "reggroups.h"
#include "block.h"
#include "solib.h"
#include <ctype.h>
#include "gdb_assert.h"
#include "observer.h"
#include "target-descriptions.h"
#include "user-regs.h"
#include "exceptions.h"
#include "cli/cli-decode.h"
#include "gdbthread.h"
#include "valprint.h"
#include "inline-frame.h"
#include "tracepoint.h"
#include "inf-loop.h"
#include "continuations.h"
#include "linespec.h"
#include "cli/cli-utils.h"
Classes
struct step_1_continuation_args
struct until_next_continuation_args
struct finish_command_continuation_args
struct attach_command_continuation_args
Defines
#define ERROR_NO_INFERIOR if (!target_has_execution) error (_("The program is not being run."));
Functions
static void nofp_registers_info (char *, int)
static void print_return_value (struct value *function, struct type *value_type)
static void until_next_command (int)
static void until_command (char *, int)
static void path_info (char *, int)
static void path_command (char *, int)
static void unset_command (char *, int)
static void float_info (char *, int)
static void disconnect_command (char *, int)
static void unset_environment_command (char *, int)
static void set_environment_command (char *, int)
static void environment_info (char *, int)
static void program_info (char *, int)
static void finish_command (char *, int)
static void signal_command (char *, int)
static void jump_command (char *, int)
static void step_1 (int, int, char *)
static void step_once (int skip_subroutines, int single_inst, int count, int thread)
static void next_command (char *, int)
static void step_command (char *, int)
static void run_command (char *, int)
static void run_no_args_command (char *args, int from_tty)
static void go_command (char *line_no, int from_tty)
static int strip_bg_char (char **)
void _initialize_infcmd (void)
void set_inferior_io_terminal (const char *terminal_name)
const char * get_inferior_io_terminal (void)
static void set_inferior_tty_command (char *args, int from_tty, struct cmd_list_element *c)
static void show_inferior_tty_command (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
char * get_inferior_args (void)
void set_inferior_args (char *newargs)
void set_inferior_args_vector (int argc, char **argv)
static void set_args_command (char *args, int from_tty, struct cmd_list_element *c)
static void show_args_command (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
char * construct_inferior_arguments (int argc, char **argv)
void post_create_inferior (struct target_ops *target, int from_tty)
static void kill_if_already_running (int from_tty)
static void run_command_1 (char *args, int from_tty, int tbreak_at_main)
static void start_command (char *args, int from_tty)
static int proceed_thread_callback (struct thread_info *thread, void *arg)
static void ensure_valid_thread (void)
static void ensure_not_tfind_mode (void)
static void error_is_running (void)
static void ensure_not_running (void)
void continue_1 (int all_threads)
static void continue_command (char *args, int from_tty)
static void set_step_frame (void)
static void stepi_command (char *count_string, int from_tty)
static void nexti_command (char *count_string, int from_tty)
void delete_longjmp_breakpoint_cleanup (void *arg)
static void step_1_continuation (void *args, int err)
static void until_next_continuation (void *arg, int err)
static void advance_command (char *arg, int from_tty)
struct value * get_return_value (struct value *function, struct type *value_type)
static void finish_command_continuation (void *arg, int err)
static void finish_command_continuation_free_arg (void *arg)
static void finish_backward (struct symbol *function)
static void finish_forward (struct symbol *function, struct frame_info *frame)
static void default_print_one_register_info (struct ui_file *file, const char *name, struct value *val)
void default_print_registers_info (struct gdbarch *gdbarch, struct ui_file *file, struct frame_info *frame, int regnum, int print_all)
void registers_info (char *addr_exp, int fpregs)
static void all_registers_info (char *addr_exp, int from_tty)
static void print_vector_info (struct ui_file *file, struct frame_info *frame, const char *args)
static void vector_info (char *args, int from_tty)
static void kill_command (char *arg, int from_tty)
static int proceed_after_attach_callback (struct thread_info *thread, void *arg)
static void proceed_after_attach (int pid)
static void attach_command_post_wait (char *args, int from_tty, int async_exec)
static void attach_command_continuation (void *args, int err)
static void attach_command_continuation_free_args (void *args)
void attach_command (char *args, int from_tty)
void notice_new_inferior (ptid_t ptid, int leave_running, int from_tty)
void detach_command (char *args, int from_tty)
void interrupt_target_1 (int all_threads)
static void interrupt_target_command (char *args, int from_tty)
static void print_float_info (struct ui_file *file, struct frame_info *frame, const char *args)
static void info_proc_cmd_1 (char *args, enum info_proc_what what, int from_tty)
static void info_proc_cmd (char *args, int from_tty)
static void info_proc_cmd_mappings (char *args, int from_tty)
static void info_proc_cmd_stat (char *args, int from_tty)
static void info_proc_cmd_status (char *args, int from_tty)
static void info_proc_cmd_cwd (char *args, int from_tty)
static void info_proc_cmd_cmdline (char *args, int from_tty)
static void info_proc_cmd_exe (char *args, int from_tty)
static void info_proc_cmd_all (char *args, int from_tty)
Variables
static char * inferior_args_scratch
static char * inferior_io_terminal_scratch
ptid_t inferior_ptid
CORE_ADDR stop_pc
enum stop_stack_kind stop_stack_dummy
int stopped_by_random_signal
static const char path_var_name [] = "PATH"
Define Documentation
#define ERROR_NO_INFERIOR if (!target_has_execution) error (_("The program is not being run."));
Definition at line 114 of file infcmd.c.
Referenced by advance_command(), continue_1(), continue_command(), finish_command(), jump_command(), signal_command(), step_1(), and until_command().
Function Documentation
void _initialize_infcmd (void)
static void advance_command (char * arg, int from_tty) [static]
Definition at line 1404 of file infcmd.c.
References _, async_disable_stdin(), ensure_not_running(), ensure_not_tfind_mode(), ensure_valid_thread(), error(), error_no_arg(), ERROR_NO_INFERIOR, strip_bg_char(), target_can_async_p, and until_break_command().
static void all_registers_info (char * addr_exp, int from_tty) [static]
Definition at line 2258 of file infcmd.c.
References registers_info().
void attach_command (char * args, int from_tty)
Definition at line 2516 of file infcmd.c.
References _, add_inferior_continuation(), attach_command_continuation_args::args, async_disable_stdin(), async_enable_stdin(), attach_command_continuation_args::async_exec, attach_command_continuation(), attach_command_continuation_free_args(), attach_command_post_wait(), clear_proceed_status(), inferior::control, current_inferior(), discard_cleanups(), dont_repeat(), error(), attach_command_continuation_args::from_tty, gdbarch_has_global_solist(), init_wait_for_inferior(), make_cleanup(), non_stop, null_cleanup(), pid_to_ptid(), ptid_get_pid(), query(), STOP_QUIETLY_NO_SIGSTOP, inferior_control_state::stop_soon, strip_bg_char(), target_attach(), target_attach_no_wait, target_can_async_p, target_gdbarch(), target_has_execution, target_kill(), target_pre_inferior(), target_stop(), target_supports_non_stop(), target_terminal_init, wait_for_inferior(), and xmalloc().
Referenced by captured_main().
static void attach_command_continuation (void * args, int err) [static]
Definition at line 2496 of file infcmd.c.
References attach_command_continuation_args::args, attach_command_continuation_args::async_exec, attach_command_post_wait(), and attach_command_continuation_args::from_tty.
Referenced by attach_command(), and notice_new_inferior().
static void attach_command_continuation_free_args (void * args) [static]
Definition at line 2507 of file infcmd.c.
References attach_command_continuation_args::args, and xfree().
Referenced by attach_command(), and notice_new_inferior().
static void attach_command_post_wait (char * args, int from_tty, int async_exec) [static]
Definition at line 2397 of file infcmd.c.
References async_enable_stdin(), clear_proceed_status(), inferior::control, current_inferior(), current_target, deprecated_attach_hook, exec_file_attach(), get_exec_file(), inferior_thread(), NO_STOP_QUIETLY, non_stop, normal_stop(), inferior::pid, pid_to_ptid(), post_create_inferior(), proceed(), proceed_after_attach(), ptid_get_pid(), reopen_exec_file(), reread_symbols(), source_full_path_of(), inferior_control_state::stop_soon, symbol_file_add_main(), target_can_async_p, target_pid_to_exec_file, target_post_attach, target_stop(), and target_terminal_inferior().
Referenced by attach_command(), attach_command_continuation(), and notice_new_inferior().
char* construct_inferior_arguments (int argc, char ** argv)
Definition at line 254 of file infcmd.c.
References _, error(), STARTUP_WITH_SHELL, strchr(), and xmalloc().
Referenced by get_inferior_args().
void continue_1 (int all_threads)
Definition at line 702 of file infcmd.c.
References clear_proceed_status(), do_cleanups(), ensure_not_running(), ensure_not_tfind_mode(), ensure_valid_thread(), ERROR_NO_INFERIOR, iterate_over_threads(), make_cleanup_restore_current_thread(), non_stop, proceed(), and proceed_thread_callback().
Referenced by continue_command(), and exec_continue().
static void continue_command (char * args, int from_tty) [static]
Definition at line 732 of file infcmd.c.
References _, async_disable_stdin(), bpstat_num(), continue_1(), thread_info::control, error(), ERROR_NO_INFERIOR, find_thread_ptid(), get_last_target_status(), non_stop, parse_and_eval_long(), printf_filtered(), set_ignore_count(), thread_control_state::stop_bpstat, strip_bg_char(), and target_can_async_p.
static void default_print_one_register_info (struct ui_file * file, const char * name, struct value * val) [static]
Definition at line 2022 of file infcmd.c.
References current_language, value_print_options::deref_ref, fprintf_filtered(), fputs_filtered(), gdbarch_byte_order(), get_formatted_print_options(), get_type_arch(), get_user_print_options(), print_hex_chars(), print_spaces_filtered(), regtype, TYPE_CODE, TYPE_CODE_DECFLOAT, TYPE_CODE_FLT, TYPE_LENGTH, TYPE_VECTOR, val_print(), val_print_optimized_out(), value_contents_for_printing(), value_embedded_offset(), value_entirely_available(), value_optimized_out(), and value_type().
Referenced by default_print_registers_info(), and registers_info().
void default_print_registers_info (struct gdbarch * gdbarch, struct ui_file * file, struct frame_info * frame, int regnum, int print_all)
Definition at line 2105 of file infcmd.c.
References all_reggroup, default_print_one_register_info(), gdbarch_num_pseudo_regs(), gdbarch_num_regs(), gdbarch_register_name(), gdbarch_register_reggroup_p(), general_reggroup, and value_of_register().
Referenced by gdbarch_alloc(), and mt_registers_info().
void delete_longjmp_breakpoint_cleanup (void * arg)
Definition at line 863 of file infcmd.c.
References delete_longjmp_breakpoint().
Referenced by finish_forward(), step_1(), until_break_command(), and until_next_command().
void detach_command (char * args, int from_tty)
Definition at line 2700 of file infcmd.c.
References _, deprecated_detach_hook, disconnect_tracing(), dont_repeat(), error(), gdbarch_has_global_solist(), have_inferiors(), init_thread_list(), no_shared_libraries(), null_ptid, ptid_equal(), query_if_trace_running(), target_detach(), and target_gdbarch().
Referenced by detach_inferior_command(), and mi_cmd_target_detach().
static void disconnect_command (char * args, int from_tty) [static]
Definition at line 2736 of file infcmd.c.
References deprecated_detach_hook, disconnect_tracing(), dont_repeat(), init_thread_list(), no_shared_libraries(), query_if_trace_running(), and target_disconnect().
static void ensure_not_running (void) [static]
Definition at line 695 of file infcmd.c.
References error_is_running(), and is_running().
Referenced by advance_command(), continue_1(), finish_command(), jump_command(), signal_command(), step_1(), and until_command().
static void ensure_not_tfind_mode (void) [static]
Definition at line 677 of file infcmd.c.
References _, error(), and get_traceframe_number().
Referenced by advance_command(), continue_1(), finish_command(), jump_command(), signal_command(), step_1(), and until_command().
static void ensure_valid_thread (void) [static]
Definition at line 665 of file infcmd.c.
References _, error(), is_exited(), null_ptid, and ptid_equal().
Referenced by advance_command(), continue_1(), finish_command(), jump_command(), signal_command(), step_1(), and until_command().
static void environment_info (char * var, int from_tty) [static]
Definition at line 1871 of file infcmd.c.
References current_inferior(), environ_vector(), get_in_environ(), and puts_filtered().
static void error_is_running (void) [static]
Definition at line 686 of file infcmd.c.
References _, and error().
Referenced by ensure_not_running().
static void finish_backward (struct symbol * function) [static]
Definition at line 1606 of file infcmd.c.
References _, thread_info::control, find_pc_line(), find_pc_partial_function(), get_current_frame(), get_frame_arch(), get_frame_pc(), get_frame_program_space(), get_selected_frame(), inferior_thread(), init_sal(), insert_step_resume_breakpoint_at_sal(), internal_error(), null_frame_id, symtab_and_line::pc, proceed(), thread_control_state::proceed_to_finish, symtab_and_line::pspace, thread_control_state::step_range_end, and thread_control_state::step_range_start.
Referenced by finish_command().
static void finish_command (char * arg, int from_tty) [static]
Definition at line 1705 of file infcmd.c.
References _, async_disable_stdin(), clear_proceed_status(), thread_info::control, ensure_not_running(), ensure_not_tfind_mode(), ensure_valid_thread(), error(), ERROR_NO_INFERIOR, EXEC_REVERSE, execution_direction, find_pc_function(), finish_backward(), finish_forward(), get_frame_pc(), get_frame_type(), get_prev_frame(), get_selected_frame(), inferior_thread(), init_sal(), INLINE_FRAME, LOCATION, print_stack_frame(), printf_filtered(), proceed(), set_step_info(), STEP_OVER_ALL, thread_control_state::step_over_calls, thread_control_state::step_range_end, thread_control_state::step_range_start, strip_bg_char(), TAILCALL_FRAME, and target_can_async_p.
static void finish_command_continuation (void * arg, int err) [static]
Definition at line 1541 of file infcmd.c.
References _, bpstat_find_breakpoint(), finish_command_continuation_args::breakpoint, thread_info::control, delete_breakpoint(), delete_longjmp_breakpoint(), exception_print(), func, finish_command_continuation_args::function, gdb_stdout, get_current_frame(), inferior_thread(), internal_error(), is_stopped(), null_ptid, observer_notify_normal_stop(), print_return_value(), thread_control_state::proceed_to_finish, ptid_equal(), read_var_value(), gdb_exception::reason, RETURN_MASK_ALL, thread_control_state::stop_bpstat, SYMBOL_TYPE, target_has_execution, finish_command_continuation_args::thread, TRY_CATCH, TYPE_CODE, TYPE_CODE_VOID, TYPE_TARGET_TYPE, and value_type().
Referenced by finish_forward().
static void finish_command_continuation_free_arg (void * arg) [static]
Definition at line 1598 of file infcmd.c.
References xfree().
Referenced by finish_forward().
static void finish_forward (struct symbol * function, struct frame_info * frame) [static]
Definition at line 1659 of file infcmd.c.
References add_continuation(), bp_finish, finish_command_continuation_args::breakpoint, thread_info::control, delete_longjmp_breakpoint_cleanup(), discard_cleanups(), do_all_continuations(), find_pc_line(), finish_command_continuation(), finish_command_continuation_free_arg(), finish_command_continuation_args::function, get_frame_arch(), get_frame_id(), get_frame_pc(), get_stack_frame_id(), inferior_thread(), make_cleanup(), make_cleanup_delete_breakpoint(), thread_info::num, symtab_and_line::pc, proceed(), thread_control_state::proceed_to_finish, set_longjmp_breakpoint(), set_momentary_breakpoint(), target_can_async_p, finish_command_continuation_args::thread, and xmalloc().
Referenced by finish_command().
static void float_info (char * args, int from_tty) [static]
Definition at line 2826 of file infcmd.c.
References _, error(), gdb_stdout, get_selected_frame(), print_float_info(), and target_has_registers.
char* get_inferior_args (void)
Definition at line 194 of file infcmd.c.
References inferior::args, construct_inferior_arguments(), current_inferior(), set_inferior_args(), and xfree().
Referenced by fbsd_make_corefile_notes(), gdb_get_inferior_args(), linux_fill_prpsinfo(), run_command_1(), and show_args_command().
const char* get_inferior_io_terminal (void)
Definition at line 164 of file infcmd.c.
References current_inferior(), and inferior::terminal.
Referenced by fork_inferior(), mi_cmd_inferior_tty_show(), procfs_create_inferior(), show_inferior_tty_command(), and windows_create_inferior().
struct value* get_return_value (struct value * function, struct type * value_type) [read]
Definition at line 1440 of file infcmd.c.
References _, allocate_value(), CHECK_TYPEDEF, do_cleanups(), gdb_assert, gdbarch_return_value(), get_current_regcache(), get_regcache_arch(), internal_error(), make_cleanup(), make_cleanup_regcache_xfree(), null_cleanup(), regcache_dup(), RETURN_VALUE_ABI_PRESERVES_ADDRESS, RETURN_VALUE_ABI_RETURNS_ADDRESS, RETURN_VALUE_REGISTER_CONVENTION, RETURN_VALUE_STRUCT_CONVENTION, stop_registers, TYPE_CODE, TYPE_CODE_VOID, and value_contents_raw().
Referenced by bpfinishpy_pre_stop_hook(), and print_return_value().
static void go_command (char * line_no, int from_tty) [static]
Definition at line 1204 of file infcmd.c.
References _, jump_command(), printf_filtered(), and tbreak_command().
static void info_proc_cmd (char * args, int from_tty) [static]
Definition at line 2861 of file infcmd.c.
References info_proc_cmd_1(), and IP_MINIMAL.
static void info_proc_cmd_1 (char * args, enum info_proc_what what, int from_tty) [static]
Definition at line 2845 of file infcmd.c.
References _, error(), gdbarch_info_proc(), gdbarch_info_proc_p(), get_current_arch(), and target_info_proc().
Referenced by info_proc_cmd(), info_proc_cmd_all(), info_proc_cmd_cmdline(), info_proc_cmd_cwd(), info_proc_cmd_exe(), info_proc_cmd_mappings(), info_proc_cmd_stat(), and info_proc_cmd_status().
static void info_proc_cmd_all (char * args, int from_tty) [static]
Definition at line 2917 of file infcmd.c.
References info_proc_cmd_1(), and IP_ALL.
static void info_proc_cmd_cmdline (char * args, int from_tty) [static]
Definition at line 2901 of file infcmd.c.
References info_proc_cmd_1(), and IP_CMDLINE.
static void info_proc_cmd_cwd (char * args, int from_tty) [static]
Definition at line 2893 of file infcmd.c.
References info_proc_cmd_1(), and IP_CWD.
static void info_proc_cmd_exe (char * args, int from_tty) [static]
Definition at line 2909 of file infcmd.c.
References info_proc_cmd_1(), and IP_EXE.
static void info_proc_cmd_mappings (char * args, int from_tty) [static]
Definition at line 2869 of file infcmd.c.
References info_proc_cmd_1(), and IP_MAPPINGS.
static void info_proc_cmd_stat (char * args, int from_tty) [static]
Definition at line 2877 of file infcmd.c.
References info_proc_cmd_1(), and IP_STAT.
static void info_proc_cmd_status (char * args, int from_tty) [static]
Definition at line 2885 of file infcmd.c.
References info_proc_cmd_1(), and IP_STATUS.
void interrupt_target_1 (int all_threads)
Definition at line 2749 of file infcmd.c.
References inferior_ptid, minus_one_ptid, non_stop, set_stop_requested(), and target_stop().
Referenced by interrupt_target_command(), and mi_cmd_exec_interrupt().
static void interrupt_target_command (char * args, int from_tty) [static]
Definition at line 2776 of file infcmd.c.
References _, dont_repeat(), error(), interrupt_target_1(), non_stop, and target_can_async_p.
static void jump_command (char * arg, int from_tty) [static]
Definition at line 1111 of file infcmd.c.
References _, async_disable_stdin(), clear_proceed_status(), DECODE_LINE_FUNFIRSTLINE, decode_line_with_last_displayed(), ensure_not_running(), ensure_not_tfind_mode(), ensure_valid_thread(), error(), error_no_arg(), ERROR_NO_INFERIOR, find_pc_function(), fixup_symbol_section(), fputs_filtered(), gdb_stdout, get_current_arch(), get_current_frame(), get_frame_function(), symtab_and_line::line, symtabs_and_lines::nelts, paddress(), symtab_and_line::pc, printf_filtered(), proceed(), query(), resolve_sal_pc(), symtabs_and_lines::sals, section_is_mapped(), section_is_overlay(), strip_bg_char(), SYMBOL_OBJ_SECTION, SYMBOL_OBJFILE, SYMBOL_PRINT_NAME, symtab_and_line::symtab, target_can_async_p, and xfree().
Referenced by go_command().
static void kill_command (char * arg, int from_tty) [static]
Definition at line 2310 of file infcmd.c.
References _, error(), get_selected_frame(), have_inferiors(), init_thread_list(), null_ptid, print_stack_frame(), printf_filtered(), ptid_equal(), query(), SRC_AND_LOC, target_has_stack, target_kill(), and target_longname.
static void kill_if_already_running (int from_tty) [static]
Definition at line 476 of file infcmd.c.
References _, error(), null_ptid, ptid_equal(), query(), target_has_execution, target_kill(), and target_require_runnable().
Referenced by run_command_1().
static void next_command (char * count_string, int from_tty) [static]
Definition at line 843 of file infcmd.c.
References step_1().
static void nexti_command (char * count_string, int from_tty) [static]
Definition at line 857 of file infcmd.c.
References step_1().
static void nofp_registers_info (char * addr_exp, int from_tty) [static]
Definition at line 2264 of file infcmd.c.
References registers_info().
void notice_new_inferior (ptid_t ptid, int leave_running, int from_tty)
Definition at line 2631 of file infcmd.c.
References add_inferior_continuation(), attach_command_continuation_args::args, attach_command_continuation_args::async_exec, attach_command_continuation(), attach_command_continuation_free_args(), attach_command_post_wait(), inferior::control, current_inferior(), do_cleanups(), attach_command_continuation_args::from_tty, is_executing(), make_cleanup(), make_cleanup_restore_current_thread(), non_stop, null_cleanup(), null_ptid, ptid_equal(), STOP_QUIETLY_REMOTE, inferior_control_state::stop_soon, switch_to_thread(), target_can_async_p, target_stop(), wait_for_inferior(), and xmalloc().
Referenced by remote_notice_new_inferior().
static void path_command (char * dirname, int from_tty) [static]
Definition at line 1999 of file infcmd.c.
References current_inferior(), dont_repeat(), get_in_environ(), mod_path(), path_info(), path_var_name, set_in_environ(), and xfree().
static void path_info (char * args, int from_tty) [static]
Definition at line 1988 of file infcmd.c.
References current_inferior(), get_in_environ(), path_var_name, and puts_filtered().
Referenced by path_command().
void post_create_inferior (struct target_ops * target, int from_tty)
Definition at line 404 of file infcmd.c.
References _, auto_solib_add, breakpoint_re_set(), current_program_space, gdb_exception::error, exec_bfd, gdbarch_has_global_solist(), get_current_regcache(), info_verbose, NOT_AVAILABLE_ERROR, observer_notify_inferior_created(), gdb_exception::reason, regcache_read_pc(), RETURN_MASK_ERROR, solib_add(), program_space::solib_add_generation, solib_create_inferior_hook(), stop_pc, target_find_description(), target_gdbarch(), target_terminal_ours, throw_exception(), TRY_CATCH, and warning().
Referenced by attach_command_post_wait(), core_open(), run_command_1(), and start_remote().
static void print_float_info (struct ui_file * file, struct frame_info * frame, const char * args) [static]
Definition at line 2796 of file infcmd.c.
References float_reggroup, fprintf_filtered(), gdbarch_num_pseudo_regs(), gdbarch_num_regs(), gdbarch_print_float_info(), gdbarch_print_float_info_p(), gdbarch_print_registers_info(), gdbarch_register_reggroup_p(), get_frame_arch(), and regnum.
Referenced by float_info(), and set_gdbarch_print_float_info().
static void print_return_value (struct value * function, struct type * value_type) [static]
Definition at line 1491 of file infcmd.c.
References current_uiout, do_cleanups(), get_no_prettyformat_print_options(), get_return_value(), make_cleanup_ui_file_delete(), mem_fileopen(), record_latest_value(), TYPE_NAME, ui_out_field_fmt(), ui_out_field_stream(), ui_out_field_string(), ui_out_text(), and value_print().
Referenced by finish_command_continuation().
static void print_vector_info (struct ui_file * file, struct frame_info * frame, const char * args) [static]
Definition at line 2270 of file infcmd.c.
References fprintf_filtered(), gdbarch_num_pseudo_regs(), gdbarch_num_regs(), gdbarch_print_registers_info(), gdbarch_print_vector_info(), gdbarch_print_vector_info_p(), gdbarch_register_reggroup_p(), get_frame_arch(), regnum, and vector_reggroup.
Referenced by set_gdbarch_print_vector_info(), and vector_info().
static void proceed_after_attach (int pid) [static]
Definition at line 2366 of file infcmd.c.
References do_cleanups(), iterate_over_threads(), make_cleanup_restore_current_thread(), and proceed_after_attach_callback().
Referenced by attach_command_post_wait().
static int proceed_after_attach_callback (struct thread_info * thread, void * arg) [static]
Definition at line 2346 of file infcmd.c.
References clear_proceed_status(), is_executing(), is_exited(), proceed(), thread_info::ptid, ptid_get_pid(), thread_info::stop_requested, thread_suspend_state::stop_signal, thread_info::suspend, and switch_to_thread().
Referenced by proceed_after_attach().
static int proceed_thread_callback (struct thread_info * thread, void * arg) [static]
Definition at line 644 of file infcmd.c.
References clear_proceed_status(), is_stopped(), proceed(), thread_info::ptid, and switch_to_thread().
Referenced by continue_1().
static void program_info (char * args, int from_tty) [static]
Definition at line 1804 of file infcmd.c.
References _, bpstat_num(), thread_info::control, error(), find_thread_ptid(), gdb_signal_to_name(), gdb_signal_to_string(), get_last_target_status(), inferior_ptid, is_exited(), is_running(), non_stop, null_ptid, paddress(), printf_filtered(), thread_info::ptid, ptid_equal(), thread_control_state::stop_bpstat, stop_pc, thread_suspend_state::stop_signal, thread_control_state::stop_step, thread_info::suspend, target_files_info, target_gdbarch(), and target_has_execution.
void registers_info (char * addr_exp, int fpregs)
Definition at line 2150 of file infcmd.c.
References _, default_print_one_register_info(), error(), gdb_stdout, gdbarch_num_pseudo_regs(), gdbarch_num_regs(), gdbarch_print_registers_info(), gdbarch_register_reggroup_p(), get_frame_arch(), get_selected_frame(), reggroup_name(), reggroup_next(), regnum, skip_spaces(), target_has_registers, user_reg_map_name_to_regnum(), user_reg_map_regnum_to_name(), and value_of_user_reg().
Referenced by all_registers_info(), nofp_registers_info(), and trace_dump_actions().
static void run_command (char * args, int from_tty) [static]
Definition at line 615 of file infcmd.c.
References run_command_1().
static void run_command_1 (char * args, int from_tty, int tbreak_at_main) [static]
Definition at line 497 of file infcmd.c.
References _, async_disable_stdin(), clear_breakpoint_hit_counts(), current_inferior(), current_target, current_uiout, discard_cleanups(), dont_repeat(), environ_vector(), error(), finish_thread_state_cleanup(), get_current_regcache(), get_exec_file(), get_inferior_args(), init_wait_for_inferior(), kill_if_already_running(), main_name(), make_cleanup(), minus_one_ptid, non_stop, pid_to_ptid(), post_create_inferior(), proceed(), ptid_get_pid(), regcache_read_pc(), reopen_exec_file(), reread_symbols(), set_inferior_args(), strip_bg_char(), target_can_async_p, target_create_inferior(), target_pre_inferior(), target_supports_non_stop(), tbreak_command(), ui_out_field_string(), ui_out_flush(), ui_out_spaces(), and ui_out_text().
Referenced by run_command(), and start_command().
static void run_no_args_command (char * args, int from_tty) [static]
Definition at line 621 of file infcmd.c.
References set_inferior_args().
static void set_args_command (char * args, int from_tty, struct cmd_list_element * c) [static]
Definition at line 233 of file infcmd.c.
References inferior_args_scratch, and set_inferior_args().
static void set_environment_command (char * arg, int from_tty) [static]
Definition at line 1904 of file infcmd.c.
References _, current_inferior(), error_no_arg(), p, printf_filtered(), savestring(), set_in_environ(), strchr(), and xfree().
void set_inferior_args (char * newargs)
Definition at line 216 of file infcmd.c.
References inferior::argc, inferior::args, inferior::argv, current_inferior(), and xfree().
Referenced by gdb_set_inferior_args(), get_inferior_args(), run_command_1(), run_no_args_command(), and set_args_command().
void set_inferior_args_vector (int argc, char ** argv)
Definition at line 225 of file infcmd.c.
References inferior::argc, inferior::argv, and current_inferior().
Referenced by captured_main().
void set_inferior_io_terminal (const char * terminal_name)
Definition at line 157 of file infcmd.c.
References current_inferior(), inferior::terminal, and xfree().
Referenced by captured_main(), mi_cmd_inferior_tty_set(), and set_inferior_tty_command().
static void set_inferior_tty_command (char * args, int from_tty, struct cmd_list_element * c) [static]
Definition at line 170 of file infcmd.c.
References inferior_io_terminal_scratch, and set_inferior_io_terminal().
static void set_step_frame (void) [static]
Definition at line 824 of file infcmd.c.
References find_frame_sal(), get_current_frame(), and set_step_info().
Referenced by step_once(), and until_next_command().
static void show_args_command (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 242 of file infcmd.c.
References deprecated_show_value_hack, and get_inferior_args().
static void show_inferior_tty_command (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 179 of file infcmd.c.
References _, fprintf_filtered(), gdb_stdout, and get_inferior_io_terminal().
static void signal_command (char * signum_exp, int from_tty) [static]
Definition at line 1219 of file infcmd.c.
References _, async_disable_stdin(), clear_proceed_status(), dont_repeat(), ensure_not_running(), ensure_not_tfind_mode(), ensure_valid_thread(), error(), error_no_arg(), ERROR_NO_INFERIOR, gdb_signal_from_command(), gdb_signal_from_name(), gdb_signal_to_name(), parse_and_eval_long(), printf_filtered(), proceed(), strip_bg_char(), and target_can_async_p.
static void start_command (char * args, int from_tty) [static]
Definition at line 631 of file infcmd.c.
References _, error(), have_minimal_symbols(), and run_command_1().
static void step_1 (int skip_subroutines, int single_inst, char * count_string) [static]
Definition at line 870 of file infcmd.c.
References _, async_disable_stdin(), thread_info::control, delete_longjmp_breakpoint_cleanup(), discard_cleanups(), do_cleanups(), ensure_not_running(), ensure_not_tfind_mode(), ensure_valid_thread(), error(), ERROR_NO_INFERIOR, get_current_frame(), get_frame_id(), in_thread_list(), inferior_thread(), make_cleanup(), null_cleanup(), parse_and_eval_long(), pid_to_thread_id(), set_longjmp_breakpoint(), thread_info::step_multi, step_once(), thread_control_state::stop_step, strip_bg_char(), target_can_async_p, and target_has_execution.
Referenced by next_command(), nexti_command(), step_command(), and stepi_command().
static void step_1_continuation (void * args, int err) [static]
Definition at line 966 of file infcmd.c.
References thread_info::control, step_1_continuation_args::count, delete_longjmp_breakpoint(), inferior_thread(), step_1_continuation_args::single_inst, step_1_continuation_args::skip_subroutines, thread_info::step_multi, step_once(), thread_control_state::stop_step, target_has_execution, and step_1_continuation_args::thread.
Referenced by step_once().
static void step_command (char * count_string, int from_tty) [static]
Definition at line 835 of file infcmd.c.
References step_1().
static void step_once (int skip_subroutines, int single_inst, int count, int thread) [static]
Definition at line 1001 of file infcmd.c.
References _, add_intermediate_continuation(), clear_proceed_status(), thread_info::control, step_1_continuation_args::count, error(), find_pc_line_pc_range(), find_pc_partial_function(), get_current_frame(), get_frame_pc(), INF_EXEC_COMPLETE, inferior_event_handler(), inferior_thread(), inline_skipped_frames(), thread_control_state::may_range_step, name, normal_stop(), printf_filtered(), proceed(), set_running(), set_step_frame(), step_1_continuation_args::single_inst, step_1_continuation_args::skip_subroutines, step_1_continuation(), step_into_inline_frame(), thread_info::step_multi, STEP_OVER_ALL, thread_control_state::step_over_calls, STEP_OVER_NONE, thread_control_state::step_range_end, thread_control_state::step_range_start, step_stop_if_no_debug, target_can_async_p, target_terminal_ours, step_1_continuation_args::thread, user_visible_resume_ptid(), xfree(), and xmalloc().
Referenced by step_1(), and step_1_continuation().
static void stepi_command (char * count_string, int from_tty) [static]
Definition at line 851 of file infcmd.c.
References step_1().
static int strip_bg_char (char ** args) [static]
Definition at line 374 of file infcmd.c.
References p, and strchr().
Referenced by advance_command(), attach_command(), continue_command(), finish_command(), jump_command(), run_command_1(), signal_command(), step_1(), and until_command().
static void unset_command (char * args, int from_tty) [static]
Definition at line 2835 of file infcmd.c.
References _, gdb_stdout, help_list(), printf_filtered(), and unsetlist.
static void unset_environment_command (char * var, int from_tty) [static]
Definition at line 1967 of file infcmd.c.
References _, current_inferior(), inferior::environment, free_environ(), make_environ(), query(), and unset_in_environ().
static void until_command (char * arg, int from_tty) [static]
Definition at line 1371 of file infcmd.c.
References _, async_disable_stdin(), ensure_not_running(), ensure_not_tfind_mode(), ensure_valid_thread(), error(), ERROR_NO_INFERIOR, strip_bg_char(), target_can_async_p, until_break_command(), and until_next_command().
static void until_next_command (int from_tty) [static]
Definition at line 1306 of file infcmd.c.
References _, add_continuation(), BLOCK_START, clear_proceed_status(), thread_info::control, delete_longjmp_breakpoint_cleanup(), discard_cleanups(), do_cleanups(), symtab_and_line::end, error(), find_pc_function(), find_pc_line(), func, get_current_frame(), get_frame_id(), get_frame_pc(), inferior_thread(), is_running(), lookup_minimal_symbol_by_pc(), make_cleanup(), thread_control_state::may_range_step, bound_minimal_symbol::minsym, thread_info::num, proceed(), set_longjmp_breakpoint(), set_step_frame(), thread_info::step_multi, STEP_OVER_ALL, thread_control_state::step_over_calls, thread_control_state::step_range_end, thread_control_state::step_range_start, SYMBOL_BLOCK_VALUE, SYMBOL_VALUE_ADDRESS, target_can_async_p, until_next_continuation_args::thread, until_next_continuation(), and xfree().
Referenced by until_command().
static void until_next_continuation (void * arg, int err) [static]
Definition at line 1290 of file infcmd.c.
References delete_longjmp_breakpoint(), and until_next_continuation_args::thread.
Referenced by until_next_command().
static void vector_info (char * args, int from_tty) [static]
Definition at line 2299 of file infcmd.c.
References _, error(), gdb_stdout, get_selected_frame(), print_vector_info(), and target_has_registers.
Variable Documentation
char* inferior_args_scratch [static]
Definition at line 123 of file infcmd.c.
Referenced by set_args_command().
char* inferior_io_terminal_scratch [static]
Definition at line 128 of file infcmd.c.
Referenced by set_inferior_tty_command().
ptid_t inferior_ptid
Definition at line 135 of file infcmd.c.
Referenced by aarch64_handle_aligned_watchpoint(), aarch64_handle_breakpoint(), aarch64_handle_unaligned_watchpoint(), aarch64_linux_get_debug_reg_capacity(), aarch64_linux_insert_hw_breakpoint(), aarch64_linux_insert_watchpoint(), aarch64_linux_remove_hw_breakpoint(), aarch64_linux_remove_watchpoint(), aarch64_linux_stopped_data_address(), aarch64_notify_debug_reg_change(), ada_exception_support_info_sniffer(), add_current_inferior_and_thread(), add_fork(), add_thread_db_info(), add_thread_silent(), add_to_thread_list(), adjust_pc_after_break(), aix_thread_fetch_registers(), aix_thread_get_ada_task_ptid(), aix_thread_resume(), aix_thread_store_registers(), aix_thread_wait(), aix_thread_xfer_partial(), alphabsd_fetch_inferior_registers(), alphabsd_store_inferior_registers(), amd64_linux_dr_get_addr(), amd64_linux_dr_get_control(), amd64_linux_dr_get_status(), amd64_linux_dr_set_addr(), amd64_linux_dr_set_control(), amd64_linux_fetch_inferior_registers(), amd64_linux_read_description(), amd64_linux_store_inferior_registers(), amd64bsd_fetch_inferior_registers(), amd64bsd_store_inferior_registers(), append_pending_thread_resumptions(), arm_linux_get_hwbp_cap(), arm_linux_read_description(), arm_linux_stopped_data_address(), async_remote_interrupt(), bpfinishpy_init(), bpstat_clear_actions(), bpstat_do_actions(), breakpoint_about_to_proceed(), breakpoint_re_set_thread(), bsd_kvm_close(), bsd_kvm_open(), bsd_uthread_fetch_registers(), bsd_uthread_find_new_threads(), bsd_uthread_store_registers(), bsd_uthread_thread_alive(), bsd_uthread_wait(), call_function_by_hand(), can_use_watchpoint_cond_accel(), check_for_thread_db(), checkpoint_command(), child_terminal_info(), clear_proceed_status(), cmd_record_save(), context_switch(), core_close(), core_open(), cur_thread(), darwin_attach(), darwin_create_inferior(), darwin_detach(), darwin_get_ada_task_ptid(), darwin_init_thread_list(), darwin_kill_inferior(), darwin_resume(), darwin_stop_inferior(), dcache_xfer_memory(), dec_thread_fetch_registers(), dec_thread_get_ada_task_ptid(), dec_thread_store_registers(), default_child_has_all_memory(), default_child_has_memory(), default_child_has_registers(), default_child_has_stack(), default_get_ada_task_ptid(), delete_checkpoint_command(), delete_fork(), delete_step_thread_step_resume_breakpoint(), delete_thread_1(), detach_breakpoints(), detach_checkpoint_command(), displaced_step_prepare(), display_current_task_id(), display_tib(), do_all_continuations_ptid(), do_captured_list_thread_ids(), do_captured_thread_select(), do_detach(), do_initial_windows_stuff(), do_restore_current_thread_cleanup(), elf_gnu_ifunc_resolver_return_stop(), elf_gnu_ifunc_resolver_stop(), enable_break(), enable_thread_event(), enable_thread_event_reporting(), exec_one_dummy_insn(), extended_remote_attach_1(), extended_remote_kill(), extended_remote_mourn_1(), fbsd_find_memory_regions(), fbsd_make_corefile_notes(), fetch_fp_register(), fetch_fp_regs(), fetch_fpregister(), fetch_fpregs(), fetch_fpregs_from_thread(), fetch_gregs(), fetch_gregs_from_thread(), fetch_inferior_event(), fetch_inferior_registers(), fetch_ppc_memory(), fetch_ppc_register(), fetch_register(), fetch_regs(), fetch_vfp_regs(), fetch_wmmx_regs(), fetch_xtregs(), find_frame_sal(), find_signalled_thread(), follow_exec(), follow_fork(), fork_inferior(), frame_inlined_callees(), frame_show_address(), gcore_command(), gdb_clear_file(), gdb_target_has_execution_command(), gdbpy_selected_thread(), gdbsim_create_inferior(), gdbsim_open(), gdbsim_wait(), gdbtk_annotate_signal(), generic_mourn_inferior(), get_core_register_section(), get_core_siginfo(), get_current_frame(), get_current_regcache(), get_displaced_step_closure_by_addr(), get_event_thread(), get_signaled_thread(), get_task_from_args(), get_windows_debug_event(), gnu_attach(), gnu_create_inferior(), gnu_detach(), gnu_fetch_registers(), gnu_resume(), gnu_store_registers(), gnu_wait(), go32_create_inferior(), go32_mourn_inferior(), go32_thread_alive(), handle_inferior_event(), handle_syscall_event(), handle_vfork_child_exec_or_exit(), has_stack_frames(), hppa_hpux_fetch_register(), hppa_hpux_store_register(), hppabsd_fetch_registers(), hppabsd_store_registers(), hppanbsd_fetch_registers(), hppanbsd_store_registers(), i386_cleanup_dregs(), i386_darwin_dr_get(), i386_darwin_dr_set(), i386_darwin_fetch_inferior_registers(), i386_darwin_store_inferior_registers(), i386_insert_hw_breakpoint(), i386_insert_watchpoint(), i386_linux_dr_get_addr(), i386_linux_dr_get_control(), i386_linux_dr_get_status(), i386_linux_dr_set_addr(), i386_linux_dr_set_control(), i386_linux_fetch_inferior_registers(), i386_linux_read_description(), i386_linux_store_inferior_registers(), i386_region_ok_for_watchpoint(), i386_remove_hw_breakpoint(), i386_remove_watchpoint(), i386_stopped_data_address(), i386_update_inferior_debug_regs(), i386bsd_fetch_inferior_registers(), i386bsd_store_inferior_registers(), i386fbsd_resume(), ia64_hpux_at_dld_breakpoint_p(), ia64_hpux_fetch_rnat_register(), ia64_hpux_get_load_info_addr(), ia64_hpux_handle_dld_breakpoint(), ia64_hpux_mourn_inferior(), ia64_hpux_read_memory_bs(), ia64_hpux_read_register_from_save_state_t(), ia64_hpux_write_memory_bs(), ia64_hpux_write_register_to_saved_state_t(), ia64_hpux_xfer_memory(), ia64_linux_fetch_register(), ia64_linux_stopped_data_address(), ia64_linux_store_register(), inf_ptrace_attach(), inf_ptrace_detach(), inf_ptrace_fetch_register(), inf_ptrace_files_info(), inf_ptrace_kill(), inf_ptrace_mourn_inferior(), inf_ptrace_resume(), inf_ptrace_store_register(), inf_ptrace_wait(), inf_ptrace_xfer_partial(), inf_validate_procs(), inferior_call_waitpid(), inferior_command(), inferior_event_handler(), inferior_thread(), info_checkpoints_command(), info_mach_exceptions_command(), info_mach_ports_command(), info_mach_region_command(), infrun_thread_ptid_changed(), init_wait_for_inferior(), inline_frame_sniffer(), insert_breakpoint_locations(), insert_catch_exec(), insert_catch_fork(), insert_catch_syscall(), insert_catch_vfork(), interrupt_target_1(), linux_child_follow_fork(), linux_corefile_thread_callback(), linux_fill_prpsinfo(), linux_fork_context(), linux_fork_detach(), linux_fork_mourn_inferior(), linux_make_corefile_notes(), linux_nat_attach(), linux_nat_detach(), linux_nat_kill(), linux_nat_mourn_inferior(), linux_nat_resume(), linux_nat_stopped_by_watchpoint(), linux_nat_stopped_data_address(), linux_nat_switch_fork(), linux_nat_wait_1(), linux_nat_xfer_partial(), linux_proc_xfer_partial(), linux_proc_xfer_spu(), linux_xfer_siginfo(), m32r_close(), m32r_detach(), m32r_kill(), m32r_linux_fetch_inferior_registers(), m32r_linux_store_inferior_registers(), m32r_load(), m32r_resume(), m32r_upload_command(), m32r_wait(), m68k_linux_fetch_inferior_registers(), m68k_linux_store_inferior_registers(), m68kbsd_fetch_inferior_registers(), m68kbsd_store_inferior_registers(), m88kbsd_fetch_inferior_registers(), m88kbsd_store_inferior_registers(), make_cleanup_restore_current_thread(), maybe_software_singlestep(), memory_xfer_partial_1(), mi_about_to_proceed(), mi_cmd_var_update_iter(), mi_execute_command(), mi_on_normal_stop(), mips64_linux_regsets_fetch_registers(), mips64_linux_regsets_store_registers(), mips64obsd_fetch_inferior_registers(), mips64obsd_store_inferior_registers(), mips_error(), mips_linux_can_use_hw_breakpoint(), mips_linux_insert_watchpoint(), mips_linux_new_thread(), mips_linux_read_description(), mips_linux_region_ok_for_hw_watchpoint(), mips_linux_stopped_by_watchpoint(), mipsnbsd_fetch_inferior_registers(), mipsnbsd_store_inferior_registers(), monitor_interrupt(), monitor_open(), monitor_wait(), normal_stop(), nto_interrupt(), open_map(), pass_signal(), pd_activate(), pd_deactivate(), pd_update(), pop_dummy_frame_bpt(), ppc_linux_can_use_hw_breakpoint(), ppc_linux_fetch_inferior_registers(), ppc_linux_read_description(), ppc_linux_spe_context(), ppc_linux_stopped_data_address(), ppc_linux_store_inferior_registers(), ppc_linux_target_wordsize(), ppc_ravenscar_generic_fetch_registers(), ppc_ravenscar_generic_store_registers(), ppcfbsd_fetch_inferior_registers(), ppcfbsd_store_inferior_registers(), ppcnbsd_fetch_inferior_registers(), ppcnbsd_store_inferior_registers(), ppcobsd_fetch_registers(), ppcobsd_store_registers(), prepare_to_proceed(), print_ada_task_info(), print_thread_info(), proc_find_memory_regions(), proc_set_current_signal(), proc_trace_syscalls(), proceed(), process_stop_reply(), procfs_attach(), procfs_create_inferior(), procfs_detach(), procfs_fetch_registers(), procfs_files_info(), procfs_find_new_threads(), procfs_inferior_created(), procfs_info_proc(), procfs_insert_watchpoint(), procfs_kill_inferior(), procfs_mourn_inferior(), procfs_pass_signals(), procfs_remove_watchpoint(), procfs_resume(), procfs_set_watchpoint(), procfs_stopped_by_watchpoint(), procfs_stopped_data_address(), procfs_store_registers(), procfs_wait(), procfs_xfer_auxv(), procfs_xfer_memory(), program_info(), ps_lgetfpregs(), ps_lgetregs(), ps_lsetfpregs(), ps_lsetregs(), ps_xfer_memory(), ptid_build_from_info(), python_on_normal_stop(), ravenscar_fetch_registers(), ravenscar_inferior_created(), ravenscar_prepare_to_store(), ravenscar_resume(), ravenscar_store_registers(), ravenscar_update_inferior_ptid(), ravenscar_wait(), read_ptid(), reattach_breakpoints(), record_btrace_info(), record_full_wait_1(), regcache_raw_read(), regcache_raw_write(), registers_changed_ptid(), remote_close(), remote_detach_1(), remote_fetch_registers(), remote_get_ada_task_ptid(), remote_newthread_step(), remote_notice_new_inferior(), remote_parse_stop_reply(), remote_read_description(), remote_start_remote(), remote_store_registers(), remote_vcont_resume(), remote_wait_as(), remote_xfer_partial(), remove_catch_exec(), remove_catch_fork(), remove_catch_syscall(), remove_catch_vfork(), require_btrace(), restore_inferior_ptid(), resume(), rs6000_wait(), rs6000_xfer_partial(), rs6000_xfer_shared_libraries(), run_inferior_call(), run_one_inferior(), rw_common(), s390_inferior_tid(), save_inferior_ptid(), save_sigtrap(), sdireset_command(), set_enable_mach_exceptions(), set_general_process(), set_longjmp_breakpoint_for_call_dummy(), set_momentary_breakpoint(), shnbsd_fetch_inferior_registers(), shnbsd_store_inferior_registers(), siginfo_make_value(), sol_find_new_threads_callback(), sol_thread_detach(), sol_thread_fetch_registers(), sol_thread_resume(), sol_thread_store_registers(), sol_thread_wait(), sol_thread_xfer_partial(), som_solib_create_inferior_hook(), sparc_fetch_inferior_registers(), sparc_ravenscar_fetch_registers(), sparc_ravenscar_store_registers(), sparc_store_inferior_registers(), sparc_xfer_wcookie(), spu2ppu_sniffer(), spu_child_wait(), spu_fetch_registers(), spu_memory_remove_breakpoint(), spu_proc_xfer_spu(), spu_skip_standalone_loader(), spu_store_registers(), startup_inferior(), store_fp_register(), store_fp_regs(), store_fpregister(), store_fpregs(), store_fpregs_to_thread(), store_gregs(), store_gregs_to_thread(), store_inferior_registers(), store_ppc_memory(), store_register(), store_regs(), store_vfp_regs(), store_wmmx_regs(), store_xtregs(), switch_to_thread(), sync_threadlists(), target_detach(), target_has_execution_current(), target_translate_tls_address(), terminal_init_inferior(), thread_apply_all_command(), thread_apply_command(), thread_command(), thread_db_detach(), thread_db_get_ada_task_ptid(), thread_db_load(), thread_db_mourn_inferior(), thread_db_resume(), thread_id_make_value(), thread_name_command(), tlb_make_value(), tlb_value_read(), try_thread_db_load(), try_thread_db_load_1(), tui_make_status_line(), until_break_command(), update_inserted_breakpoint_locations(), update_solib_list(), user_visible_resume_ptid(), validate_siginfo_access(), varobj_create(), vax_register_u_offset(), vaxbsd_fetch_inferior_registers(), vaxbsd_store_inferior_registers(), VEC(), watch_command_1(), watchpoint_in_thread_scope(), windows_close(), windows_detach(), windows_fetch_inferior_registers(), windows_files_info(), windows_get_ada_task_ptid(), windows_resume(), windows_store_inferior_registers(), and write_memory_ptid().
const char path_var_name[] = "PATH" [static]
Definition at line 1985 of file infcmd.c.
Referenced by path_command(), and path_info().
CORE_ADDR stop_pc
Definition at line 139 of file infcmd.c.
Referenced by check_event(), cplus_skip_trampoline(), fill_in_stop_func(), fork_load_infrun_state(), gdb_loc(), gnuv3_skip_trampoline(), handle_inferior_event(), handle_step_into_function(), handle_step_into_function_backward(), handle_syscall_event(), normal_stop(), post_create_inferior(), proceed(), program_info(), restore_infcall_suspend_state(), save_infcall_suspend_state(), and switch_to_thread().
enum stop_stack_kind stop_stack_dummy
Definition at line 143 of file infcmd.c.
Referenced by call_function_by_hand(), handle_inferior_event(), normal_stop(), restore_infcall_control_state(), and save_infcall_control_state().
int stopped_by_random_signal
Definition at line 148 of file infcmd.c.
Referenced by call_function_by_hand(), handle_inferior_event(), normal_stop(), restore_infcall_control_state(), and save_infcall_control_state().