GDB (xrefs): /home/stan/gdb/src/gdb/inferior.c File Reference
/home/stan/gdb/src/gdb/inferior.c File Reference
#include "defs.h"
#include "exec.h"
#include "inferior.h"
#include "target.h"
#include "command.h"
#include "completer.h"
#include "gdbcmd.h"
#include "gdbthread.h"
#include "ui-out.h"
#include "observer.h"
#include "gdbcore.h"
#include "symfile.h"
#include "environ.h"
#include "cli/cli-utils.h"
#include "continuations.h"
#include "arch-utils.h"
#include "target-descriptions.h"
#include "readline/tilde.h"
Classes
struct delete_thread_of_inferior_arg
Functions
void _initialize_inferiors (void)
struct inferior * current_inferior (void)
void set_current_inferior (struct inferior *inf)
static void restore_inferior (void *arg)
struct cleanup * save_current_inferior (void)
static void free_inferior (struct inferior *inf)
void init_inferior_list (void)
struct inferior * add_inferior_silent (int pid)
struct inferior * add_inferior (int pid)
static int delete_thread_of_inferior (struct thread_info *tp, void *data)
void delete_inferior_1 (struct inferior *todel, int silent)
void delete_inferior (int pid)
void delete_inferior_silent (int pid)
static void exit_inferior_1 (struct inferior *inftoex, int silent)
void exit_inferior (int pid)
void exit_inferior_silent (int pid)
void exit_inferior_num_silent (int num)
void detach_inferior (int pid)
void inferior_appeared (struct inferior *inf, int pid)
void discard_all_inferiors (void)
struct inferior * find_inferior_id (int num)
struct inferior * find_inferior_pid (int pid)
struct inferior * find_inferior_for_program_space (struct program_space *pspace)
struct inferior * iterate_over_inferiors (int(*callback)(struct inferior *, void *), void *data)
int valid_gdb_inferior_id (int num)
int pid_to_gdb_inferior_id (int pid)
int gdb_inferior_id_to_pid (int num)
int in_inferior_list (int pid)
int have_inferiors (void)
int have_live_inferiors (void)
void prune_inferiors (void)
int number_of_inferiors (void)
static char * inferior_pid_to_str (int pid)
static void print_inferior (struct ui_out *uiout, char *requested_inferiors)
static void detach_inferior_command (char *args, int from_tty)
static void kill_inferior_command (char *args, int from_tty)
static void inferior_command (char *args, int from_tty)
static void info_inferiors_command (char *args, int from_tty)
static void remove_inferior_command (char *args, int from_tty)
struct inferior * add_inferior_with_spaces (void)
static void add_inferior_command (char *args, int from_tty)
static void clone_inferior_command (char *args, int from_tty)
static void show_print_inferior_events (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
void initialize_inferiors (void)
Variables
struct inferior * inferior_list = NULL
static int highest_inferior_num
static int print_inferior_events = 0
static struct inferior * current_inferior_ = NULL
Function Documentation
void _initialize_inferiors (void)
struct inferior* add_inferior (int pid) [read]
Definition at line 156 of file inferior.c.
References _, add_inferior_silent(), arm-linux::inf, print_inferior_events, and printf_unfiltered().
Referenced by add_inferior_with_spaces(), clone_inferior_command(), follow_exec(), initialize_inferiors(), linux_child_follow_fork(), and remote_add_inferior().
static void add_inferior_command (char * args, int from_tty) [static]
Definition at line 825 of file inferior.c.
References _, add_inferior_with_spaces(), do_cleanups(), error(), exec_file_attach(), gdb_buildargv(), make_cleanup(), make_cleanup_freeargv(), null_cleanup(), null_ptid, inferior::num, parse_and_eval_long(), printf_filtered(), inferior::pspace, save_current_space_and_thread(), set_current_inferior(), set_current_program_space(), switch_to_thread(), symbol_file_add_main(), and xfree().
Referenced by initialize_inferiors().
struct inferior* add_inferior_silent (int pid) [read]
Definition at line 128 of file inferior.c.
References inferior::control, inferior::environment, highest_inferior_num, arm-linux::inf, inferior_appeared(), inferior_list, init_environ(), make_environ(), memset(), inferior::next, NO_STOP_QUIETLY, inferior::num, observer_notify_inferior_added(), inferior::pid, inferior_control_state::stop_soon, and xmalloc().
Referenced by add_inferior().
struct inferior* add_inferior_with_spaces (void) [read]
Definition at line 795 of file inferior.c.
References add_inferior(), add_program_space(), program_space::aspace, inferior::aspace, gdb_assert, inferior::gdbarch, gdbarch_find_by_info(), gdbarch_info_init(), arm-linux::inf, maybe_new_address_space(), and inferior::pspace.
Referenced by add_inferior_command(), and mi_cmd_add_inferior().
static void clone_inferior_command (char * args, int from_tty) [static]
Definition at line 889 of file inferior.c.
References _, add_inferior(), add_program_space(), inferior::argv, program_space::aspace, inferior::aspace, clone_program_space(), copy_inferior_target_desc_info(), current_inferior(), do_cleanups(), error(), find_inferior_id(), gdb_buildargv(), inferior::gdbarch, arm-linux::inf, make_cleanup(), make_cleanup_freeargv(), maybe_new_address_space(), null_cleanup(), null_ptid, inferior::num, parse_and_eval_long(), printf_filtered(), inferior::pspace, save_current_space_and_thread(), set_current_inferior(), switch_to_thread(), target_desc_info_from_user_p(), and inferior::tdesc_info.
Referenced by initialize_inferiors().
struct inferior* current_inferior (void) [read]
Definition at line 58 of file inferior.c.
References current_inferior_.
Referenced by ada_build_task_list(), ada_exception_name_addr_1(), ada_exception_support_info_sniffer(), ada_exception_sym_name(), ada_get_tsd_from_tag(), ada_normal_stop_observer(), ada_unhandled_exception_name_addr_from_raise(), add_inferior_continuation(), add_to_thread_list(), alpha_heuristic_proc_start(), attach_command(), attach_command_post_wait(), bpfinishpy_detect_out_scope_cb(), catch_syscall_enabled(), child_terminal_info(), clear_proceed_status(), clone_inferior_command(), cmd_record_stop(), core_open(), ctrl_c_handler(), darwin_attach(), darwin_detach(), darwin_get_ada_task_ptid(), darwin_kill_inferior(), darwin_mourn_inferior(), darwin_ptrace_him(), darwin_solib_get_all_image_info_addr_at_init(), darwin_stop(), darwin_xfer_partial(), detach_breakpoints(), do_all_inferior_continuations(), do_attach(), do_initial_windows_stuff(), elf_gnu_ifunc_resolver_stop(), enable_break(), environment_info(), follow_exec(), fork_inferior(), gdb_clear_file(), gdbpy_selected_inferior(), gdbsim_close(), gdbsim_create_inferior(), gdbsim_fetch_register(), gdbsim_files_info(), gdbsim_has_all_memory(), gdbsim_has_memory(), gdbsim_load(), gdbsim_mourn_inferior(), gdbsim_open(), gdbsim_store_register(), gdbsim_wait(), gdbsim_xfer_memory(), get_auxv_inferior_data(), get_inferior_args(), get_inferior_io_terminal(), get_other_inferior(), get_task_from_args(), gnu_attach(), go32_create_inferior(), handle_inferior_event(), handle_solib_event(), handle_vfork_child_exec_or_exit(), heuristic_proc_start(), ia64_hpux_solib_create_inferior_hook(), inf_has_multiple_thread_cb(), inf_ptrace_attach(), inf_ptrace_files_info(), info_mach_exceptions_command(), info_mach_ports_command(), info_mach_region_command(), info_tasks_command(), insert_catch_syscall(), invalidate_auxv_cache(), irix_solib_create_inferior_hook(), iterate_over_live_ada_tasks(), linux_child_follow_fork(), linux_find_memory_regions_full(), linux_handle_extended_wait(), linux_info_proc(), make_cleanup_restore_current_thread(), memory_xfer_auxv(), mi_cmd_ada_task_info(), mi_cmd_env_path(), mi_cmd_remove_inferior(), mi_solib_loaded(), mi_solib_unloaded(), monitor_open(), new_tty_postfork(), notice_new_inferior(), osf_solib_create_inferior_hook(), path_command(), path_info(), prepare_for_detach(), print_exited_reason(), print_inferior(), procfs_attach(), procfs_create_inferior(), procfs_files_info(), procfs_inferior_created(), prune_inferiors(), ravenscar_inferior_created(), read_known_tasks(), read_known_tasks_array(), read_known_tasks_list(), record_btrace_open(), record_full_open(), remote_add_inferior(), remove_catch_syscall(), remove_inferior_command(), restore_infcall_control_state(), restore_infcall_suspend_state(), resume(), run_command_1(), save_infcall_control_state(), save_infcall_suspend_state(), set_enable_mach_exceptions(), set_environment_command(), set_inferior_args(), set_inferior_args_vector(), set_inferior_io_terminal(), set_sigint_trap(), set_target_gdbarch(), simulator_command(), solib_aix_current_sos(), solib_aix_normal_stop_observer(), solib_aix_solib_create_inferior_hook(), solib_find(), solib_read_symbols(), spu_memory_remove_breakpoint(), spu_skip_standalone_loader(), start_remote(), symbol_file_add_main_1(), target_gdbarch(), task_command(), terminal_inferior(), terminal_init_inferior_with_pgrp(), terminal_ours_1(), unset_environment_command(), update_solib_list(), valid_task_id(), VEC(), windows_files_info(), and write_memory_with_notification().
void delete_inferior (int pid)
Definition at line 222 of file inferior.c.
References _, delete_inferior_1(), find_inferior_pid(), print_inferior_events, and printf_unfiltered().
void delete_inferior_1 (struct inferior * todel, int silent)
Definition at line 192 of file inferior.c.
References delete_thread_of_inferior(), free_inferior(), arm-linux::inf, inferior_list, iterate_over_threads(), observer_notify_inferior_removed(), delete_thread_of_inferior_arg::pid, inf::pid, and delete_thread_of_inferior_arg::silent.
Referenced by delete_inferior(), delete_inferior_silent(), mi_cmd_remove_inferior(), prune_inferiors(), and remove_inferior_command().
void delete_inferior_silent (int pid)
Definition at line 233 of file inferior.c.
References delete_inferior_1(), and find_inferior_pid().
Referenced by monitor_close().
static int delete_thread_of_inferior (struct thread_info * tp, void * data) [static]
Definition at line 173 of file inferior.c.
References delete_thread(), delete_thread_silent(), delete_thread_of_inferior_arg::pid, thread_info::ptid, ptid_get_pid(), and delete_thread_of_inferior_arg::silent.
Referenced by delete_inferior_1(), and exit_inferior_1().
void detach_inferior (int pid)
Definition at line 312 of file inferior.c.
References _, exit_inferior_1(), find_inferior_pid(), print_inferior_events, and printf_unfiltered().
Referenced by gnu_detach(), inf_ptrace_detach(), procfs_detach(), and windows_detach().
static void detach_inferior_command (char * args, int from_tty) [static]
Definition at line 618 of file inferior.c.
References _, any_thread_of_process(), detach_command(), error(), get_number_or_range_state::finished, gdb_inferior_id_to_pid(), get_number_or_range(), init_number_or_range(), thread_info::ptid, switch_to_thread(), valid_gdb_inferior_id(), and warning().
Referenced by initialize_inferiors().
void discard_all_inferiors (void)
Definition at line 331 of file inferior.c.
References exit_inferior_silent(), arm-linux::inf, inferior_list, inferior::next, and inferior::pid.
Referenced by remote_close().
void exit_inferior (int pid)
Definition at line 285 of file inferior.c.
References _, exit_inferior_1(), find_inferior_pid(), print_inferior_events, and printf_unfiltered().
Referenced by generic_mourn_inferior().
static void exit_inferior_1 (struct inferior * inftoex, int silent) [static]
Definition at line 245 of file inferior.c.
References delete_thread_of_inferior(), inferior::exit_code, inferior::fake_pid_p, inferior::has_exit_code, arm-linux::inf, inferior_list, iterate_over_threads(), inferior::next, observer_notify_inferior_exit(), inferior::pending_detach, delete_thread_of_inferior_arg::pid, inferior::pid, delete_thread_of_inferior_arg::silent, inferior::vfork_child, and inferior::vfork_parent.
Referenced by detach_inferior(), exit_inferior(), exit_inferior_num_silent(), and exit_inferior_silent().
void exit_inferior_num_silent (int num)
Definition at line 304 of file inferior.c.
References exit_inferior_1(), and find_inferior_id().
Referenced by follow_exec().
void exit_inferior_silent (int pid)
Definition at line 296 of file inferior.c.
References exit_inferior_1(), and find_inferior_pid().
Referenced by core_close(), and discard_all_inferiors().
struct inferior* find_inferior_for_program_space (struct program_space * pspace) [read]
Definition at line 374 of file inferior.c.
References arm-linux::inf, inferior_list, inferior::next, and inferior::pspace.
Referenced by pspace_empty_p(), and switch_to_program_space_and_thread().
struct inferior* find_inferior_id (int num) [read]
Definition at line 343 of file inferior.c.
References arm-linux::inf, inferior_list, inferior::next, and inferior::num.
Referenced by clone_inferior_command(), do_restore_current_thread_cleanup(), exec_continue(), exit_inferior_num_silent(), gdb_inferior_id_to_pid(), inferior_command(), mi_cmd_exec_interrupt(), mi_cmd_execute(), mi_cmd_list_thread_groups(), mi_cmd_remove_inferior(), mi_cmd_target_detach(), remove_inferior_command(), and restore_current_thread_cleanup_dtor().
struct inferior* find_inferior_pid (int pid) [read]
Definition at line 355 of file inferior.c.
References gdb_assert, arm-linux::inf, inferior_list, inferior::next, and inferior::pid.
Referenced by ada_get_task_number(), core_pid_to_str(), darwin_resume(), delete_inferior(), delete_inferior_silent(), detach_inferior(), do_restore_current_thread_cleanup(), exit_inferior(), exit_inferior_silent(), fetch_inferior_event(), find_inferior_object(), gdbsim_close_inferior(), gdbsim_resume(), gdbsim_stop(), get_sim_inferior_data_by_ptid(), get_windows_debug_event(), handle_inferior_event(), linux_nat_thread_address_space(), memory_xfer_partial_1(), mi_new_thread(), mi_thread_exit(), procfs_wait(), ps_pglobal_lookup(), reattach_breakpoints(), remove_breakpoints_pid(), resume_lwp(), sol2_core_pid_to_str(), stop_wait_callback(), switch_to_thread(), target_thread_address_space(), and thread_change_ptid().
static void free_inferior (struct inferior * inf) [static]
Definition at line 97 of file inferior.c.
References inferior::args, discard_all_inferior_continuations(), inferior::environment, free_environ(), inferior::private, target_desc_info_free(), inferior::tdesc_info, inferior::terminal, and xfree().
Referenced by delete_inferior_1(), and init_inferior_list().
int gdb_inferior_id_to_pid (int num)
Definition at line 428 of file inferior.c.
References find_inferior_id(), and inferior::pid.
Referenced by detach_inferior_command(), and kill_inferior_command().
int have_inferiors (void)
Definition at line 450 of file inferior.c.
References arm-linux::inf, inferior_list, inferior::next, and inferior::pid.
Referenced by detach_command(), extended_remote_create_inferior_1(), extended_remote_mourn_1(), fork_inferior(), gdbsim_create_inferior(), inf_ptrace_detach(), inf_ptrace_mourn_inferior(), kill_command(), remote_open_1(), and target_preopen().
int have_live_inferiors (void)
Definition at line 462 of file inferior.c.
References any_thread_of_process(), arm-linux::inf, inferior_list, inferior::next, inferior::pid, thread_info::ptid, and target_has_execution_1().
Referenced by quit_confirm(), set_target_async_command(), target_preopen(), and update_global_location_list().
int in_inferior_list (int pid)
Definition at line 438 of file inferior.c.
References arm-linux::inf, inferior_list, inferior::next, and inferior::pid.
Referenced by ia64_hpux_xfer_memory(), and remote_notice_new_inferior().
void inferior_appeared (struct inferior * inf, int pid)
Definition at line 323 of file inferior.c.
References observer_notify_inferior_appeared(), and inferior::pid.
Referenced by add_inferior_silent(), add_to_thread_list(), core_open(), darwin_attach(), do_attach(), do_initial_windows_stuff(), fork_inferior(), gdbsim_create_inferior(), gnu_attach(), go32_create_inferior(), inf_ptrace_attach(), monitor_open(), procfs_attach(), procfs_create_inferior(), and remote_add_inferior().
static void inferior_command (char * args, int from_tty) [static]
Definition at line 692 of file inferior.c.
References _, any_thread_of_process(), current_uiout, error(), find_inferior_id(), get_selected_frame(), arm-linux::inf, inferior_pid_to_str(), inferior_ptid, is_running(), null_ptid, inferior::num, parse_and_eval_long(), inferior::pid, pid_to_thread_id(), print_stack_frame(), printf_filtered(), inferior::pspace, program_space::pspace_exec_filename, thread_info::ptid, ptid_get_pid(), set_current_inferior(), set_current_program_space(), SRC_AND_LOC, switch_to_thread(), target_pid_to_str(), and ui_out_text().
Referenced by initialize_inferiors().
static char* inferior_pid_to_str (int pid) [static]
Definition at line 527 of file inferior.c.
References _, pid_to_ptid(), and target_pid_to_str().
Referenced by inferior_command(), and print_inferior().
static void info_inferiors_command (char * args, int from_tty) [static]
Definition at line 749 of file inferior.c.
References current_uiout, and print_inferior().
Referenced by initialize_inferiors().
void init_inferior_list (void)
Definition at line 110 of file inferior.c.
References free_inferior(), highest_inferior_num, arm-linux::inf, inferior_list, and inferior::next.
void initialize_inferiors (void)
Definition at line 986 of file inferior.c.
References _, add_cmd(), add_com(), add_inferior(), add_inferior_command(), add_info(), add_setshow_boolean_cmd(), program_space::aspace, inferior::aspace, class_run, clone_inferior_command(), cmdlist, current_inferior_, current_program_space, detach_inferior_command(), detachlist, inferior_command(), info_inferiors_command(), kill_inferior_command(), killlist, no_class, print_inferior_events, inferior::pspace, remove_inferior_command(), setprintlist, show_print_inferior_events(), and showprintlist.
Referenced by gdb_init().
struct inferior* iterate_over_inferiors (int(*)(struct inferior *, void *) callback, void * data) [read]
Definition at line 388 of file inferior.c.
References arm-linux::inf, inferior_list, and inferior::next.
Referenced by darwin_find_inferior_by_notify(), darwin_find_inferior_by_task(), darwin_resume(), darwin_wait(), gdbpy_inferiors(), gdbsim_close(), gdbsim_resume(), gdbsim_stop(), get_sim_inferior_data(), mi_cmd_exec_run(), mi_cmd_list_thread_groups(), mi_cmd_remove_inferior(), mi_interpreter_init(), mi_on_resume(), quit_confirm(), quit_force(), and target_preopen().
static void kill_inferior_command (char * args, int from_tty) [static]
Definition at line 654 of file inferior.c.
References _, any_thread_of_process(), error(), get_number_or_range_state::finished, gdb_inferior_id_to_pid(), get_number_or_range(), init_number_or_range(), thread_info::ptid, switch_to_thread(), target_kill(), valid_gdb_inferior_id(), and warning().
Referenced by initialize_inferiors().
int number_of_inferiors (void)
Definition at line 512 of file inferior.c.
References arm-linux::inf, inferior_list, and inferior::next.
Referenced by print_one_breakpoint_location().
int pid_to_gdb_inferior_id (int pid)
Definition at line 416 of file inferior.c.
References arm-linux::inf, inferior_list, inferior::next, inferior::num, and inferior::pid.
static void print_inferior (struct ui_out * uiout, char * requested_inferiors) [static]
Definition at line 543 of file inferior.c.
References _, current_inferior(), do_cleanups(), arm-linux::inf, inferior_list, inferior_pid_to_str(), make_cleanup_ui_out_table_begin_end(), make_cleanup_ui_out_tuple_begin_end(), inferior::next, inferior::num, number_is_in_list(), inferior::pid, inferior::pspace, program_space::pspace_exec_filename, ui_left, ui_out_field_int(), ui_out_field_skip(), ui_out_field_string(), ui_out_message(), ui_out_table_body(), ui_out_table_header(), ui_out_text(), inferior::vfork_child, and inferior::vfork_parent.
Referenced by info_inferiors_command().
void prune_inferiors (void)
Definition at line 483 of file inferior.c.
References current_inferior(), delete_inferior_1(), inferior_list, inferior::next, inferior::pid, prune_program_spaces(), and inferior::removable.
Referenced by normal_stop().
static void remove_inferior_command (char * args, int from_tty) [static]
Definition at line 757 of file inferior.c.
References _, current_inferior(), delete_inferior_1(), error(), find_inferior_id(), get_number_or_range_state::finished, get_number_or_range(), arm-linux::inf, init_number_or_range(), inferior::num, inferior::pid, and warning().
Referenced by initialize_inferiors().
static void restore_inferior (void * arg) [static]
Definition at line 76 of file inferior.c.
References set_current_inferior().
Referenced by save_current_inferior().
struct cleanup* save_current_inferior (void) [read]
Definition at line 88 of file inferior.c.
References current_inferior_, make_cleanup(), and restore_inferior().
Referenced by handle_vfork_child_exec_or_exit().
void set_current_inferior (struct inferior * inf)
Definition at line 64 of file inferior.c.
References current_inferior_, gdb_assert, and arm-linux::inf.
Referenced by add_inferior_command(), clone_inferior_command(), do_restore_current_thread_cleanup(), extended_remote_attach_1(), follow_exec(), handle_inferior_event(), inferior_command(), mi_cmd_execute(), mi_cmd_remove_inferior(), restore_inferior(), run_one_inferior(), and switch_to_thread().
static void show_print_inferior_events (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 977 of file inferior.c.
References _, and fprintf_filtered().
Referenced by initialize_inferiors().
int valid_gdb_inferior_id (int num)
Definition at line 404 of file inferior.c.
References arm-linux::inf, inferior_list, inferior::next, and inferior::num.
Referenced by detach_inferior_command(), and kill_inferior_command().
Variable Documentation
struct inferior* current_inferior_ = NULL [static]
Definition at line 55 of file inferior.c.
Referenced by current_inferior(), initialize_inferiors(), save_current_inferior(), and set_current_inferior().
int highest_inferior_num [static]
Definition at line 48 of file inferior.c.
Referenced by add_inferior_silent(), and init_inferior_list().
struct inferior* inferior_list = NULL
Definition at line 47 of file inferior.c.
Referenced by ada_new_objfile_observer(), add_inferior_silent(), delete_inferior_1(), discard_all_inferiors(), exit_inferior_1(), find_inferior_for_program_space(), find_inferior_id(), find_inferior_pid(), have_inferiors(), have_live_inferiors(), in_inferior_list(), init_inferior_list(), iterate_over_inferiors(), number_of_inferiors(), pid_to_gdb_inferior_id(), print_inferior(), print_program_space(), prune_inferiors(), update_address_spaces(), and valid_gdb_inferior_id().
int print_inferior_events = 0 [static]
Definition at line 52 of file inferior.c.
Referenced by add_inferior(), delete_inferior(), detach_inferior(), exit_inferior(), and initialize_inferiors().