GDB (xrefs): /home/stan/gdb/src/gdb/inferior.h File Reference
/home/stan/gdb/src/gdb/inferior.h File Reference
#include "ptid.h"
#include "breakpoint.h"
#include "target.h"
#include "frame.h"
#include "progspace.h"
#include "registry.h"
Classes
struct inferior_control_state
struct inferior
Defines
#define ON_STACK 1
#define AT_ENTRY_POINT 4
#define STARTUP_WITH_SHELL 1
#define ALL_INFERIORS(I) for ((I) = inferior_list; (I); (I) = (I)->next)
Enumerations
enum step_over_calls_kind { STEP_OVER_NONE, STEP_OVER_ALL, STEP_OVER_UNDEBUGGABLE }
enum stop_kind { NO_STOP_QUIETLY = 0, STOP_QUIETLY, STOP_QUIETLY_REMOTE, STOP_QUIETLY_NO_SIGSTOP }
enum exec_direction_kind { EXEC_FORWARD, EXEC_REVERSE }
Functions
struct infcall_suspend_state * save_infcall_suspend_state (void)
struct infcall_control_state * save_infcall_control_state (void)
void restore_infcall_suspend_state (struct infcall_suspend_state *)
void restore_infcall_control_state (struct infcall_control_state *)
struct cleanup * make_cleanup_restore_infcall_suspend_state (struct infcall_suspend_state *)
struct cleanup * make_cleanup_restore_infcall_control_state (struct infcall_control_state *)
void discard_infcall_suspend_state (struct infcall_suspend_state *)
void discard_infcall_control_state (struct infcall_control_state *)
struct regcache * get_infcall_suspend_state_regcache (struct infcall_suspend_state *)
int ptid_match (ptid_t ptid, ptid_t filter)
struct cleanup * save_inferior_ptid (void)
void set_sigint_trap (void)
void clear_sigint_trap (void)
void set_inferior_io_terminal (const char *terminal_name)
const char * get_inferior_io_terminal (void)
void clear_proceed_status (void)
void proceed (CORE_ADDR, enum gdb_signal, int)
void generic_mourn_inferior (void)
void terminal_save_ours (void)
void terminal_ours (void)
CORE_ADDR unsigned_pointer_to_address (struct gdbarch *gdbarch, struct type *type, const gdb_byte *buf)
void unsigned_address_to_pointer (struct gdbarch *gdbarch, struct type *type, gdb_byte *buf, CORE_ADDR addr)
CORE_ADDR signed_pointer_to_address (struct gdbarch *gdbarch, struct type *type, const gdb_byte *buf)
void address_to_signed_pointer (struct gdbarch *gdbarch, struct type *type, gdb_byte *buf, CORE_ADDR addr)
void wait_for_inferior (void)
void prepare_for_detach (void)
void fetch_inferior_event (void *)
void init_wait_for_inferior (void)
void reopen_exec_file (void)
void resume (int, enum gdb_signal)
ptid_t user_visible_resume_ptid (int step)
void insert_step_resume_breakpoint_at_sal (struct gdbarch *, struct symtab_and_line, struct frame_id)
void default_print_registers_info (struct gdbarch *gdbarch, struct ui_file *file, struct frame_info *frame, int regnum, int all)
void child_terminal_info (const char *, int)
void term_info (char *, int)
void terminal_ours_for_output (void)
void terminal_inferior (void)
void terminal_init_inferior (void)
void terminal_init_inferior_with_pgrp (int pgrp)
int fork_inferior (char *, char *, char **, void(*)(void), void(*)(int), void(*)(void), char *, void(*)(const char *, char *const *, char *const *))
void startup_inferior (int)
char * construct_inferior_arguments (int, char **)
void start_remote (int from_tty)
void normal_stop (void)
int signal_stop_state (int)
int signal_print_state (int)
int signal_pass_state (int)
int signal_stop_update (int, int)
int signal_print_update (int, int)
int signal_pass_update (int, int)
void get_last_target_status (ptid_t *ptid, struct target_waitstatus *status)
void follow_inferior_reset_breakpoints (void)
void set_step_info (struct frame_info *frame, struct symtab_and_line sal)
void clear_exit_convenience_vars (void)
void post_create_inferior (struct target_ops *, int)
void attach_command (char *, int)
char * get_inferior_args (void)
void set_inferior_args (char *)
void set_inferior_args_vector (int, char **)
void registers_info (char *, int)
void continue_1 (int all_threads)
void interrupt_target_1 (int all_threads)
void delete_longjmp_breakpoint_cleanup (void *arg)
void detach_command (char *, int)
void notice_new_inferior (ptid_t, int, int)
struct value * get_return_value (struct value *function, struct type *value_type)
void displaced_step_dump_bytes (struct ui_file *file, const gdb_byte *buf, size_t len)
struct displaced_step_closure * get_displaced_step_closure_by_addr (CORE_ADDR addr)
DECLARE_REGISTRY (inferior)
void init_inferior_list (void)
struct inferior * add_inferior (int pid)
struct inferior * add_inferior_silent (int pid)
void delete_inferior (int pid)
void delete_inferior_1 (struct inferior *todel, int silent)
void delete_inferior_silent (int pid)
void detach_inferior (int pid)
void exit_inferior (int pid)
void exit_inferior_silent (int pid)
void exit_inferior_num_silent (int num)
void inferior_appeared (struct inferior *inf, int pid)
void discard_all_inferiors (void)
int gdb_inferior_id_to_pid (int)
int pid_to_gdb_inferior_id (int pid)
int in_inferior_list (int pid)
int valid_gdb_inferior_id (int num)
struct inferior * find_inferior_pid (int pid)
struct inferior * find_inferior_id (int num)
struct inferior * find_inferior_for_program_space (struct program_space *pspace)
struct inferior * iterate_over_inferiors (int(*)(struct inferior *, void *), void *)
int have_inferiors (void)
int have_live_inferiors (void)
struct inferior * current_inferior (void)
void set_current_inferior (struct inferior *)
struct cleanup * save_current_inferior (void)
void prune_inferiors (void)
int number_of_inferiors (void)
struct inferior * add_inferior_with_spaces (void)
void update_observer_mode (void)
void update_signals_program_target (void)
void signal_catch_update (const unsigned int *)
enum gdb_signal gdb_signal_from_command (int num)
Variables
ptid_t inferior_ptid
int sync_execution
int sched_multi
int step_stop_if_no_debug
int non_stop
int disable_randomization
unsigned int debug_infrun
int stop_on_solib_events
CORE_ADDR stop_pc
enum stop_stack_kind stop_stack_dummy
int stopped_by_random_signal
int execution_direction
struct regcache * stop_registers
int debug_displaced
struct inferior * inferior_list
Define Documentation
#define ALL_INFERIORS (I) for ((I) = inferior_list; (I); (I) = (I)->next)
Definition at line 619 of file inferior.h.
Referenced by check_zombie_leaders(), print_one_breakpoint_location(), and thread_db_find_new_threads().
#define AT_ENTRY_POINT 4
Definition at line 347 of file inferior.h.
Referenced by call_function_by_hand(), gdbarch_alloc(), score_gdbarch_init(), and sparc64_init_abi().
#define ON_STACK 1
Definition at line 346 of file inferior.h.
Referenced by call_function_by_hand(), hppa_hpux_init_abi(), i386_gdbarch_init(), ia64_hpux_init_abi(), microblaze_gdbarch_init(), mips_gdbarch_init(), sparc32_gdbarch_init(), and spu_gdbarch_init().
#define STARTUP_WITH_SHELL 1
Definition at line 365 of file inferior.h.
Referenced by construct_inferior_arguments(), and fork_inferior().
Enumeration Type Documentation
enum exec_direction_kind
Enumerator:
EXEC_FORWARD
EXEC_REVERSE
Definition at line 318 of file inferior.h.
enum step_over_calls_kind
Enumerator:
STEP_OVER_NONE
STEP_OVER_ALL
STEP_OVER_UNDEBUGGABLE
Definition at line 277 of file inferior.h.
enum stop_kind
Enumerator:
NO_STOP_QUIETLY
STOP_QUIETLY
STOP_QUIETLY_REMOTE
STOP_QUIETLY_NO_SIGSTOP
Definition at line 309 of file inferior.h.
Function Documentation
struct inferior* add_inferior (int pid) [read]
Definition at line 156 of file inferior.c.
References _, add_inferior_silent(), arm-linux::inf, print_inferior_events, and printf_unfiltered().
Referenced by add_inferior_with_spaces(), clone_inferior_command(), follow_exec(), initialize_inferiors(), linux_child_follow_fork(), and remote_add_inferior().
struct inferior* add_inferior_silent (int pid) [read]
Definition at line 128 of file inferior.c.
References inferior::control, inferior::environment, highest_inferior_num, arm-linux::inf, inferior_appeared(), inferior_list, init_environ(), make_environ(), memset(), inferior::next, NO_STOP_QUIETLY, inferior::num, observer_notify_inferior_added(), inferior::pid, inferior_control_state::stop_soon, and xmalloc().
Referenced by add_inferior().
struct inferior* add_inferior_with_spaces (void) [read]
Definition at line 795 of file inferior.c.
References add_inferior(), add_program_space(), program_space::aspace, inferior::aspace, gdb_assert, inferior::gdbarch, gdbarch_find_by_info(), gdbarch_info_init(), arm-linux::inf, maybe_new_address_space(), and inferior::pspace.
Referenced by add_inferior_command(), and mi_cmd_add_inferior().
void address_to_signed_pointer (struct gdbarch * gdbarch, struct type * type, gdb_byte * buf, CORE_ADDR addr)
Definition at line 333 of file findvar.c.
References gdbarch_byte_order(), store_signed_integer(), and TYPE_LENGTH.
Referenced by mips_gdbarch_init().
void attach_command (char * , int)
Definition at line 2516 of file infcmd.c.
References _, add_inferior_continuation(), attach_command_continuation_args::args, async_disable_stdin(), async_enable_stdin(), attach_command_continuation_args::async_exec, attach_command_continuation(), attach_command_continuation_free_args(), attach_command_post_wait(), clear_proceed_status(), inferior::control, current_inferior(), discard_cleanups(), dont_repeat(), error(), attach_command_continuation_args::from_tty, gdbarch_has_global_solist(), init_wait_for_inferior(), make_cleanup(), non_stop, null_cleanup(), pid_to_ptid(), ptid_get_pid(), query(), STOP_QUIETLY_NO_SIGSTOP, inferior_control_state::stop_soon, strip_bg_char(), target_attach(), target_attach_no_wait, target_can_async_p, target_gdbarch(), target_has_execution, target_kill(), target_pre_inferior(), target_stop(), target_supports_non_stop(), target_terminal_init, wait_for_inferior(), and xmalloc().
Referenced by captured_main().
void child_terminal_info (const char * , int)
Definition at line 569 of file inflow.c.
References _, current_inferior(), flags, gdb_has_a_terminal(), gdb_stdout, get_inflow_inferior_data(), arm-linux::inf, inferior_ptid, null_ptid, O_ACCMODE, printf_filtered(), ptid_equal(), serial_print_tty_state(), terminal_info::tflags, and terminal_info::ttystate.
Referenced by inf_child_target(), init_procfs_ops(), and init_windows_ops().
void clear_exit_convenience_vars (void)
Definition at line 7098 of file infrun.c.
References clear_internalvar(), and lookup_internalvar().
Referenced by core_open(), and handle_inferior_event().
void clear_proceed_status (void)
Definition at line 2015 of file infrun.c.
References clear_proceed_status_callback(), clear_proceed_status_thread(), inferior::control, current_inferior(), inferior_ptid, inferior_thread(), iterate_over_threads(), NO_STOP_QUIETLY, non_stop, null_ptid, observer_notify_about_to_proceed(), ptid_equal(), regcache_xfree(), stop_after_trap, and inferior_control_state::stop_soon.
Referenced by attach_command(), attach_command_post_wait(), continue_1(), do_initial_windows_stuff(), finish_command(), gdbsim_create_inferior(), go32_create_inferior(), init_wait_for_inferior(), irix_solib_create_inferior_hook(), jump_command(), m32r_create_inferior(), monitor_create_inferior(), osf_solib_create_inferior_hook(), proceed_after_attach_callback(), proceed_after_vfork_done(), proceed_thread(), proceed_thread_callback(), run_inferior_call(), signal_command(), step_once(), until_break_command(), and until_next_command().
void clear_sigint_trap (void)
Definition at line 795 of file inflow.c.
References osig.
Referenced by inf_ptrace_wait(), linux_nat_terminal_ours(), linux_nat_wait_1(), rs6000_wait(), and spu_child_wait().
char* construct_inferior_arguments (int , char **)
Definition at line 254 of file infcmd.c.
References _, error(), STARTUP_WITH_SHELL, strchr(), and xmalloc().
Referenced by get_inferior_args().
void continue_1 (int all_threads)
Definition at line 702 of file infcmd.c.
References clear_proceed_status(), do_cleanups(), ensure_not_running(), ensure_not_tfind_mode(), ensure_valid_thread(), ERROR_NO_INFERIOR, iterate_over_threads(), make_cleanup_restore_current_thread(), non_stop, proceed(), and proceed_thread_callback().
Referenced by continue_command(), and exec_continue().
struct inferior* current_inferior (void) [read]
Definition at line 58 of file inferior.c.
References current_inferior_.
Referenced by ada_build_task_list(), ada_exception_name_addr_1(), ada_exception_support_info_sniffer(), ada_exception_sym_name(), ada_get_tsd_from_tag(), ada_normal_stop_observer(), ada_unhandled_exception_name_addr_from_raise(), add_inferior_continuation(), add_to_thread_list(), alpha_heuristic_proc_start(), attach_command(), attach_command_post_wait(), bpfinishpy_detect_out_scope_cb(), catch_syscall_enabled(), child_terminal_info(), clear_proceed_status(), clone_inferior_command(), cmd_record_stop(), core_open(), ctrl_c_handler(), darwin_attach(), darwin_detach(), darwin_get_ada_task_ptid(), darwin_kill_inferior(), darwin_mourn_inferior(), darwin_ptrace_him(), darwin_solib_get_all_image_info_addr_at_init(), darwin_stop(), darwin_xfer_partial(), detach_breakpoints(), do_all_inferior_continuations(), do_attach(), do_initial_windows_stuff(), elf_gnu_ifunc_resolver_stop(), enable_break(), environment_info(), follow_exec(), fork_inferior(), gdb_clear_file(), gdbpy_selected_inferior(), gdbsim_close(), gdbsim_create_inferior(), gdbsim_fetch_register(), gdbsim_files_info(), gdbsim_has_all_memory(), gdbsim_has_memory(), gdbsim_load(), gdbsim_mourn_inferior(), gdbsim_open(), gdbsim_store_register(), gdbsim_wait(), gdbsim_xfer_memory(), get_auxv_inferior_data(), get_inferior_args(), get_inferior_io_terminal(), get_other_inferior(), get_task_from_args(), gnu_attach(), go32_create_inferior(), handle_inferior_event(), handle_solib_event(), handle_vfork_child_exec_or_exit(), heuristic_proc_start(), ia64_hpux_solib_create_inferior_hook(), inf_has_multiple_thread_cb(), inf_ptrace_attach(), inf_ptrace_files_info(), info_mach_exceptions_command(), info_mach_ports_command(), info_mach_region_command(), info_tasks_command(), insert_catch_syscall(), invalidate_auxv_cache(), irix_solib_create_inferior_hook(), iterate_over_live_ada_tasks(), linux_child_follow_fork(), linux_find_memory_regions_full(), linux_handle_extended_wait(), linux_info_proc(), make_cleanup_restore_current_thread(), memory_xfer_auxv(), mi_cmd_ada_task_info(), mi_cmd_env_path(), mi_cmd_remove_inferior(), mi_solib_loaded(), mi_solib_unloaded(), monitor_open(), new_tty_postfork(), notice_new_inferior(), osf_solib_create_inferior_hook(), path_command(), path_info(), prepare_for_detach(), print_exited_reason(), print_inferior(), procfs_attach(), procfs_create_inferior(), procfs_files_info(), procfs_inferior_created(), prune_inferiors(), ravenscar_inferior_created(), read_known_tasks(), read_known_tasks_array(), read_known_tasks_list(), record_btrace_open(), record_full_open(), remote_add_inferior(), remove_catch_syscall(), remove_inferior_command(), restore_infcall_control_state(), restore_infcall_suspend_state(), resume(), run_command_1(), save_infcall_control_state(), save_infcall_suspend_state(), set_enable_mach_exceptions(), set_environment_command(), set_inferior_args(), set_inferior_args_vector(), set_inferior_io_terminal(), set_sigint_trap(), set_target_gdbarch(), simulator_command(), solib_aix_current_sos(), solib_aix_normal_stop_observer(), solib_aix_solib_create_inferior_hook(), solib_find(), solib_read_symbols(), spu_memory_remove_breakpoint(), spu_skip_standalone_loader(), start_remote(), symbol_file_add_main_1(), target_gdbarch(), task_command(), terminal_inferior(), terminal_init_inferior_with_pgrp(), terminal_ours_1(), unset_environment_command(), update_solib_list(), valid_task_id(), VEC(), windows_files_info(), and write_memory_with_notification().
DECLARE_REGISTRY (inferior)
void default_print_registers_info (struct gdbarch * gdbarch, struct ui_file * file, struct frame_info * frame, int regnum, int all)
Definition at line 2105 of file infcmd.c.
References all_reggroup, default_print_one_register_info(), gdbarch_num_pseudo_regs(), gdbarch_num_regs(), gdbarch_register_name(), gdbarch_register_reggroup_p(), general_reggroup, and value_of_register().
Referenced by gdbarch_alloc(), and mt_registers_info().
void delete_inferior (int pid)
Definition at line 222 of file inferior.c.
References _, delete_inferior_1(), find_inferior_pid(), print_inferior_events, and printf_unfiltered().
void delete_inferior_1 (struct inferior * todel, int silent)
Definition at line 192 of file inferior.c.
References delete_thread_of_inferior(), free_inferior(), arm-linux::inf, inferior_list, iterate_over_threads(), observer_notify_inferior_removed(), delete_thread_of_inferior_arg::pid, inf::pid, and delete_thread_of_inferior_arg::silent.
Referenced by delete_inferior(), delete_inferior_silent(), mi_cmd_remove_inferior(), prune_inferiors(), and remove_inferior_command().
void delete_inferior_silent (int pid)
Definition at line 233 of file inferior.c.
References delete_inferior_1(), and find_inferior_pid().
Referenced by monitor_close().
void delete_longjmp_breakpoint_cleanup (void * arg)
Definition at line 863 of file infcmd.c.
References delete_longjmp_breakpoint().
Referenced by finish_forward(), step_1(), until_break_command(), and until_next_command().
void detach_command (char * , int)
Definition at line 2700 of file infcmd.c.
References _, deprecated_detach_hook, disconnect_tracing(), dont_repeat(), error(), gdbarch_has_global_solist(), have_inferiors(), init_thread_list(), no_shared_libraries(), null_ptid, ptid_equal(), query_if_trace_running(), target_detach(), and target_gdbarch().
Referenced by detach_inferior_command(), and mi_cmd_target_detach().
void detach_inferior (int pid)
Definition at line 312 of file inferior.c.
References _, exit_inferior_1(), find_inferior_pid(), print_inferior_events, and printf_unfiltered().
Referenced by gnu_detach(), inf_ptrace_detach(), procfs_detach(), and windows_detach().
void discard_all_inferiors (void)
Definition at line 331 of file inferior.c.
References exit_inferior_silent(), arm-linux::inf, inferior_list, inferior::next, and inferior::pid.
Referenced by remote_close().
void discard_infcall_control_state (struct infcall_control_state *)
Definition at line 7038 of file infrun.c.
References bpstat_clear(), disp_del_at_next_stop, breakpoint::disposition, thread_control_state::exception_resume_breakpoint, thread_control_state::step_resume_breakpoint, thread_control_state::stop_bpstat, infcall_control_state::thread_control, and xfree().
Referenced by call_function_by_hand().
void discard_infcall_suspend_state (struct infcall_suspend_state *)
Definition at line 6897 of file infrun.c.
References regcache_xfree(), infcall_suspend_state::registers, infcall_suspend_state::siginfo_data, and xfree().
Referenced by remove_dummy_frame(), and restore_infcall_suspend_state().
void displaced_step_dump_bytes (struct ui_file * file, const gdb_byte * buf, size_t len)
Definition at line 1270 of file infrun.c.
References fprintf_unfiltered(), fputs_unfiltered(), and len.
Referenced by amd64_displaced_step_copy_insn(), displaced_step_fixup(), displaced_step_prepare(), i386_displaced_step_copy_insn(), resume(), and simple_displaced_step_copy_insn().
void exit_inferior (int pid)
Definition at line 285 of file inferior.c.
References _, exit_inferior_1(), find_inferior_pid(), print_inferior_events, and printf_unfiltered().
Referenced by generic_mourn_inferior().
void exit_inferior_num_silent (int num)
Definition at line 304 of file inferior.c.
References exit_inferior_1(), and find_inferior_id().
Referenced by follow_exec().
void exit_inferior_silent (int pid)
Definition at line 296 of file inferior.c.
References exit_inferior_1(), and find_inferior_pid().
Referenced by core_close(), and discard_all_inferiors().
void fetch_inferior_event (void *)
Definition at line 2770 of file infrun.c.
References _, thread_info::control, inferior::control, debug_infrun, delete_step_thread_step_resume_breakpoint(), deprecated_target_wait_hook, discard_cleanups(), display_gdb_prompt(), do_cleanups(), execution_control_state::event_thread, exec_done_display_p, execution_direction, find_inferior_pid(), finish_thread_state_cleanup(), handle_inferior_event(), INF_EXEC_COMPLETE, INF_EXEC_CONTINUE, inferior_event_handler(), inferior_ptid, interpreter_async, is_running(), target_waitstatus::kind, make_bpstat_clear_actions_cleanup(), make_cleanup(), make_cleanup_restore_current_thread(), make_cleanup_restore_current_traceframe(), make_cleanup_restore_integer(), memset(), minus_one_ptid, NO_STOP_QUIETLY, non_stop, normal_stop(), null_cleanup(), null_ptid, overlay_cache_invalid, print_target_wait_results(), printf_unfiltered(), execution_control_state::ptid, ptid_equal(), ptid_get_pid(), set_current_traceframe(), thread_info::step_multi, inferior_control_state::stop_soon, thread_control_state::stop_step, sync_execution, target_execution_direction, target_has_execution, target_wait(), TARGET_WAITKIND_EXITED, TARGET_WAITKIND_NO_RESUMED, TARGET_WAITKIND_SIGNALLED, TARGET_WNOHANG, execution_control_state::wait_some_more, and execution_control_state::ws.
Referenced by fetch_inferior_event_wrapper().
struct inferior* find_inferior_for_program_space (struct program_space * pspace) [read]
Definition at line 374 of file inferior.c.
References arm-linux::inf, inferior_list, inferior::next, and inferior::pspace.
Referenced by pspace_empty_p(), and switch_to_program_space_and_thread().
struct inferior* find_inferior_id (int num) [read]
Definition at line 343 of file inferior.c.
References arm-linux::inf, inferior_list, inferior::next, and inferior::num.
Referenced by clone_inferior_command(), do_restore_current_thread_cleanup(), exec_continue(), exit_inferior_num_silent(), gdb_inferior_id_to_pid(), inferior_command(), mi_cmd_exec_interrupt(), mi_cmd_execute(), mi_cmd_list_thread_groups(), mi_cmd_remove_inferior(), mi_cmd_target_detach(), remove_inferior_command(), and restore_current_thread_cleanup_dtor().
struct inferior* find_inferior_pid (int pid) [read]
Definition at line 355 of file inferior.c.
References gdb_assert, arm-linux::inf, inferior_list, inferior::next, and inferior::pid.
Referenced by ada_get_task_number(), core_pid_to_str(), darwin_resume(), delete_inferior(), delete_inferior_silent(), detach_inferior(), do_restore_current_thread_cleanup(), exit_inferior(), exit_inferior_silent(), fetch_inferior_event(), find_inferior_object(), gdbsim_close_inferior(), gdbsim_resume(), gdbsim_stop(), get_sim_inferior_data_by_ptid(), get_windows_debug_event(), handle_inferior_event(), linux_nat_thread_address_space(), memory_xfer_partial_1(), mi_new_thread(), mi_thread_exit(), procfs_wait(), ps_pglobal_lookup(), reattach_breakpoints(), remove_breakpoints_pid(), resume_lwp(), sol2_core_pid_to_str(), stop_wait_callback(), switch_to_thread(), target_thread_address_space(), and thread_change_ptid().
void follow_inferior_reset_breakpoints (void)
Definition at line 576 of file infrun.c.
References breakpoint_re_set(), breakpoint_re_set_thread(), thread_info::control, thread_control_state::exception_resume_breakpoint, inferior_thread(), insert_breakpoints(), and thread_control_state::step_resume_breakpoint.
Referenced by follow_fork().
int fork_inferior (char * , char * , char ** , void(*)(void) , void(*)(int) , void(*)(void) , char * , void(*)(const char *, char *const *, char *const *))
int gdb_inferior_id_to_pid (int)
Definition at line 428 of file inferior.c.
References find_inferior_id(), and inferior::pid.
Referenced by detach_inferior_command(), and kill_inferior_command().
enum gdb_signal gdb_signal_from_command (int num)
Definition at line 6615 of file infrun.c.
References _, and error().
Referenced by handle_command(), signal_command(), signals_info(), and VEC().
void generic_mourn_inferior (void)
Definition at line 3652 of file target.c.
References breakpoint_init_inferior(), deprecated_detach_hook, exit_inferior(), inf_exited, inferior_ptid, mark_breakpoints_out(), null_ptid, ptid_equal(), ptid_get_pid(), registers_changed(), reinit_frame_cache(), and reopen_exec_file().
Referenced by darwin_mourn_inferior(), extended_remote_mourn_1(), gdbsim_close_inferior(), gdbsim_mourn_inferior(), gnu_mourn_inferior(), go32_mourn_inferior(), inf_ptrace_mourn_inferior(), m32r_mourn_inferior(), monitor_mourn_inferior(), procfs_mourn_inferior(), remote_mourn_1(), and windows_mourn_inferior().
struct displaced_step_closure* get_displaced_step_closure_by_addr (CORE_ADDR addr) [read]
Definition at line 1163 of file infrun.c.
References get_displaced_stepping_state(), inferior_ptid, null_ptid, ptid_equal(), ptid_get_pid(), displaced_step_inferior_state::step_closure, displaced_step_inferior_state::step_copy, and displaced_step_inferior_state::step_ptid.
Referenced by arm_pc_is_thumb().
struct regcache* get_infcall_suspend_state_regcache (struct infcall_suspend_state *) [read]
Definition at line 6905 of file infrun.c.
References infcall_suspend_state::registers.
Referenced by dummy_frame_sniffer().
char* get_inferior_args (void)
Definition at line 194 of file infcmd.c.
References inferior::args, construct_inferior_arguments(), current_inferior(), set_inferior_args(), and xfree().
Referenced by fbsd_make_corefile_notes(), gdb_get_inferior_args(), linux_fill_prpsinfo(), run_command_1(), and show_args_command().
const char* get_inferior_io_terminal (void)
Definition at line 164 of file infcmd.c.
References current_inferior(), and inferior::terminal.
Referenced by fork_inferior(), mi_cmd_inferior_tty_show(), procfs_create_inferior(), show_inferior_tty_command(), and windows_create_inferior().
void get_last_target_status (ptid_t * ptid, struct target_waitstatus * status)
Definition at line 2899 of file infrun.c.
References target_last_wait_ptid, and target_last_waitstatus.
Referenced by checkpoint_command(), continue_command(), follow_fork(), get_pending_status(), linux_nat_kill(), mi_on_normal_stop(), normal_stop(), prepare_to_proceed(), print_it_catch_syscall(), proc_set_current_signal(), proceed(), program_info(), and signal_catchpoint_print_it().
struct value* get_return_value (struct value * function, struct type * value_type) [read]
Definition at line 1440 of file infcmd.c.
References _, allocate_value(), CHECK_TYPEDEF, do_cleanups(), gdb_assert, gdbarch_return_value(), get_current_regcache(), get_regcache_arch(), internal_error(), make_cleanup(), make_cleanup_regcache_xfree(), null_cleanup(), regcache_dup(), RETURN_VALUE_ABI_PRESERVES_ADDRESS, RETURN_VALUE_ABI_RETURNS_ADDRESS, RETURN_VALUE_REGISTER_CONVENTION, RETURN_VALUE_STRUCT_CONVENTION, stop_registers, TYPE_CODE, TYPE_CODE_VOID, and value_contents_raw().
Referenced by bpfinishpy_pre_stop_hook(), and print_return_value().
int have_inferiors (void)
Definition at line 450 of file inferior.c.
References arm-linux::inf, inferior_list, inferior::next, and inferior::pid.
Referenced by detach_command(), extended_remote_create_inferior_1(), extended_remote_mourn_1(), fork_inferior(), gdbsim_create_inferior(), inf_ptrace_detach(), inf_ptrace_mourn_inferior(), kill_command(), remote_open_1(), and target_preopen().
int have_live_inferiors (void)
Definition at line 462 of file inferior.c.
References any_thread_of_process(), arm-linux::inf, inferior_list, inferior::next, inferior::pid, thread_info::ptid, and target_has_execution_1().
Referenced by quit_confirm(), set_target_async_command(), target_preopen(), and update_global_location_list().
int in_inferior_list (int pid)
Definition at line 438 of file inferior.c.
References arm-linux::inf, inferior_list, inferior::next, and inferior::pid.
Referenced by ia64_hpux_xfer_memory(), and remote_notice_new_inferior().
void inferior_appeared (struct inferior * inf, int pid)
Definition at line 323 of file inferior.c.
References observer_notify_inferior_appeared(), and inferior::pid.
Referenced by add_inferior_silent(), add_to_thread_list(), core_open(), darwin_attach(), do_attach(), do_initial_windows_stuff(), fork_inferior(), gdbsim_create_inferior(), gnu_attach(), go32_create_inferior(), inf_ptrace_attach(), monitor_open(), procfs_attach(), procfs_create_inferior(), and remote_add_inferior().
void init_inferior_list (void)
Definition at line 110 of file inferior.c.
References free_inferior(), highest_inferior_num, arm-linux::inf, inferior_list, and inferior::next.
void init_wait_for_inferior (void)
Definition at line 2371 of file infrun.c.
References breakpoint_init_inferior(), clear_inline_frame_state(), clear_proceed_status(), inf_starting, inferior_ptid, init_infwait_state(), minus_one_ptid, null_ptid, and stepping_past_singlestep_breakpoint.
Referenced by attach_command(), do_initial_windows_stuff(), extended_remote_create_inferior_1(), gdbsim_create_inferior(), m32r_create_inferior(), monitor_open(), remote_start_remote(), and run_command_1().
void insert_step_resume_breakpoint_at_sal (struct gdbarch * , struct symtab_and_line , struct frame_id)
Definition at line 5467 of file infrun.c.
References bp_step_resume, and insert_step_resume_breakpoint_at_sal_1().
Referenced by finish_backward(), handle_inferior_event(), handle_step_into_function(), and insert_step_resume_breakpoint_at_caller().
void interrupt_target_1 (int all_threads)
Definition at line 2749 of file infcmd.c.
References inferior_ptid, minus_one_ptid, non_stop, set_stop_requested(), and target_stop().
Referenced by interrupt_target_command(), and mi_cmd_exec_interrupt().
struct inferior* iterate_over_inferiors (int(*)(struct inferior *, void *) , void *) [read]
Definition at line 388 of file inferior.c.
References arm-linux::inf, inferior_list, and inferior::next.
Referenced by darwin_find_inferior_by_notify(), darwin_find_inferior_by_task(), darwin_resume(), darwin_wait(), gdbpy_inferiors(), gdbsim_close(), gdbsim_resume(), gdbsim_stop(), get_sim_inferior_data(), mi_cmd_exec_run(), mi_cmd_list_thread_groups(), mi_cmd_remove_inferior(), mi_interpreter_init(), mi_on_resume(), quit_confirm(), quit_force(), and target_preopen().
struct cleanup* make_cleanup_restore_infcall_control_state (struct infcall_control_state *) [read]
Definition at line 7032 of file infrun.c.
References do_restore_infcall_control_state_cleanup(), and make_cleanup().
Referenced by call_function_by_hand().
struct cleanup* make_cleanup_restore_infcall_suspend_state (struct infcall_suspend_state *) [read]
Definition at line 6891 of file infrun.c.
References do_restore_infcall_suspend_state_cleanup(), and make_cleanup().
Referenced by call_function_by_hand().
void normal_stop (void)
Definition at line 5969 of file infrun.c.
References _, annotate_stopped(), annotate_thread_changed(), async_enable_stdin(), batch_silent, bpstat_print(), breakpoint_auto_delete(), breakpoints_always_inserted_mode(), catch_errors(), thread_info::control, disable_current_display(), do_cleanups(), do_displays(), DUMMY_FRAME, EXEC_REVERSE, execution_direction, find_pc_function(), finish_thread_state_cleanup(), frame_id_eq(), frame_pop(), gdb_assert, get_current_frame(), get_current_regcache(), get_frame_id(), get_frame_type(), get_last_target_status(), get_selected_frame(), has_stack_frames(), hook_stop_stub(), inferior_ptid, inferior_thread(), internal_error(), target_waitstatus::kind, make_cleanup(), minus_one_ptid, non_stop, null_cleanup(), null_ptid, observer_notify_normal_stop(), PRINT_NOTHING, PRINT_SRC_AND_LOC, PRINT_SRC_ONLY, print_stack_frame(), PRINT_UNKNOWN, printf_filtered(), thread_control_state::proceed_to_finish, prune_inferiors(), ptid_equal(), regcache_dup(), regcache_xfree(), remove_breakpoints(), RETURN_MASK_ALL, select_frame(), set_current_sal_from_frame(), SRC_AND_LOC, SRC_LINE, thread_control_state::step_frame_id, thread_control_state::stop_bpstat, stop_pc, stop_print_frame, stop_stack_dummy, STOP_STACK_DUMMY, thread_control_state::stop_step, stopped_by_random_signal, sync_execution, target_can_async_p, target_has_execution, target_pid_to_str(), target_terminal_ours, target_terminal_ours_for_output, TARGET_WAITKIND_EXITED, TARGET_WAITKIND_NO_RESUMED, and TARGET_WAITKIND_SIGNALLED.
Referenced by attach_command_post_wait(), fetch_inferior_event(), infrun_thread_stop_requested_callback(), proceed(), resume_cleanups(), run_inferior_call(), start_remote(), and step_once().
void notice_new_inferior (ptid_t , int , int)
Definition at line 2631 of file infcmd.c.
References add_inferior_continuation(), attach_command_continuation_args::args, attach_command_continuation_args::async_exec, attach_command_continuation(), attach_command_continuation_free_args(), attach_command_post_wait(), inferior::control, current_inferior(), do_cleanups(), attach_command_continuation_args::from_tty, is_executing(), make_cleanup(), make_cleanup_restore_current_thread(), non_stop, null_cleanup(), null_ptid, ptid_equal(), STOP_QUIETLY_REMOTE, inferior_control_state::stop_soon, switch_to_thread(), target_can_async_p, target_stop(), wait_for_inferior(), and xmalloc().
Referenced by remote_notice_new_inferior().
int number_of_inferiors (void)
Definition at line 512 of file inferior.c.
References arm-linux::inf, inferior_list, and inferior::next.
Referenced by print_one_breakpoint_location().
int pid_to_gdb_inferior_id (int pid)
Definition at line 416 of file inferior.c.
References arm-linux::inf, inferior_list, inferior::next, inferior::num, and inferior::pid.
void post_create_inferior (struct target_ops * , int)
Definition at line 404 of file infcmd.c.
References _, auto_solib_add, breakpoint_re_set(), current_program_space, gdb_exception::error, exec_bfd, gdbarch_has_global_solist(), get_current_regcache(), info_verbose, NOT_AVAILABLE_ERROR, observer_notify_inferior_created(), gdb_exception::reason, regcache_read_pc(), RETURN_MASK_ERROR, solib_add(), program_space::solib_add_generation, solib_create_inferior_hook(), stop_pc, target_find_description(), target_gdbarch(), target_terminal_ours, throw_exception(), TRY_CATCH, and warning().
Referenced by attach_command_post_wait(), core_open(), run_command_1(), and start_remote().
void prepare_for_detach (void)
Definition at line 2640 of file infrun.c.
References _, current_inferior(), debug_infrun, deprecated_target_wait_hook, inferior::detaching, discard_cleanups(), error(), finish_thread_state_cleanup(), fprintf_unfiltered(), gdb_stdlog, get_displaced_stepping_state(), handle_inferior_event(), make_cleanup(), make_cleanup_restore_integer(), memset(), minus_one_ptid, null_ptid, overlay_cache_invalid, inferior::pid, pid_to_ptid(), print_target_wait_results(), execution_control_state::ptid, ptid_equal(), displaced_step_inferior_state::step_ptid, target_wait(), execution_control_state::wait_some_more, and execution_control_state::ws.
Referenced by target_detach().
void proceed (CORE_ADDR , enum gdb_signal, int)
Definition at line 2140 of file infrun.c.
References annotate_starting(), bpstat_should_step(), breakpoint_here_p(), thread_info::control, debug_infrun, EXEC_REVERSE, execution_direction, find_pc_function(), find_thread_ptid(), follow_fork(), fprintf_unfiltered(), gdb_flush(), gdb_stdlog, gdb_stdout, gdbarch_single_step_through_delay(), gdbarch_single_step_through_delay_p(), get_current_frame(), get_current_regcache(), get_last_target_status(), get_regcache_arch(), get_regcache_aspace(), INF_EXEC_COMPLETE, inferior_event_handler(), inferior_ptid, inferior_thread(), init_infwait_state(), init_thread_stepping_state(), insert_breakpoints(), minus_one_ptid, non_stop, normal_stop(), null_ptid, paddress(), prepare_to_proceed(), thread_info::prev_pc, ptid_equal(), regcache_read_pc(), regcache_write_pc(), remove_breakpoints(), resume(), signal_program, stop_after_trap, stop_pc, thread_suspend_state::stop_signal, thread_info::suspend, target_can_async_p, thread_control_state::trap_expected, use_displaced_stepping(), and wait_for_inferior().
Referenced by attach_command_post_wait(), continue_1(), finish_backward(), finish_command(), finish_forward(), jump_command(), proceed_after_attach_callback(), proceed_after_vfork_done(), proceed_thread(), proceed_thread_callback(), run_command_1(), run_inferior_call(), signal_command(), step_once(), until_break_command(), and until_next_command().
void prune_inferiors (void)
Definition at line 483 of file inferior.c.
References current_inferior(), delete_inferior_1(), inferior_list, inferior::next, inferior::pid, prune_program_spaces(), and inferior::removable.
Referenced by normal_stop().
int ptid_match (ptid_t ptid, ptid_t filter)
Definition at line 7055 of file infrun.c.
References minus_one_ptid, ptid_equal(), ptid_get_pid(), and ptid_is_pid().
Referenced by append_pending_thread_resumptions(), infrun_thread_stop_requested(), iterate_over_lwps(), linux_nat_wait_1(), registers_changed_ptid(), remote_notif_remove_once_on_match(), and resume_stopped_resumed_lwps().
void registers_info (char * , int)
Definition at line 2150 of file infcmd.c.
References _, default_print_one_register_info(), error(), gdb_stdout, gdbarch_num_pseudo_regs(), gdbarch_num_regs(), gdbarch_print_registers_info(), gdbarch_register_reggroup_p(), get_frame_arch(), get_selected_frame(), reggroup_name(), reggroup_next(), regnum, skip_spaces(), target_has_registers, user_reg_map_name_to_regnum(), user_reg_map_regnum_to_name(), and value_of_user_reg().
Referenced by all_registers_info(), nofp_registers_info(), and trace_dump_actions().
void reopen_exec_file (void)
Definition at line 136 of file corefile.c.
References do_cleanups(), exec_bfd, exec_bfd_mtime, exec_file_attach(), make_cleanup(), and xfree().
Referenced by attach_command_post_wait(), generic_mourn_inferior(), load_command(), remote_open_1(), and run_command_1().
void restore_infcall_control_state (struct infcall_control_state *)
Definition at line 6984 of file infrun.c.
References bpstat_clear(), catch_errors(), thread_info::control, inferior::control, current_inferior(), disp_del_at_next_stop, breakpoint::disposition, thread_control_state::exception_resume_breakpoint, get_current_frame(), infcall_control_state::inferior_control, inferior_thread(), restore_selected_frame(), RETURN_MASK_ERROR, select_frame(), infcall_control_state::selected_frame_id, thread_control_state::step_resume_breakpoint, stop_after_trap, infcall_control_state::stop_after_trap, thread_control_state::stop_bpstat, stop_stack_dummy, infcall_control_state::stop_stack_dummy, stopped_by_random_signal, infcall_control_state::stopped_by_random_signal, target_has_stack, infcall_control_state::thread_control, and xfree().
Referenced by call_function_by_hand(), and do_restore_infcall_control_state_cleanup().
void restore_infcall_suspend_state (struct infcall_suspend_state *)
Definition at line 6849 of file infrun.c.
References current_inferior(), current_target, discard_infcall_suspend_state(), gdbarch_get_siginfo_type(), get_current_regcache(), get_regcache_arch(), inferior_thread(), regcache_cpy(), infcall_suspend_state::registers, infcall_suspend_state::siginfo_data, infcall_suspend_state::siginfo_gdbarch, stop_pc, infcall_suspend_state::stop_pc, thread_info::suspend, target_has_execution, TARGET_OBJECT_SIGNAL_INFO, target_write(), infcall_suspend_state::thread_suspend, and TYPE_LENGTH.
Referenced by do_restore_infcall_suspend_state_cleanup(), and pop_dummy_frame().
void resume (int , enum gdb_signal)
Definition at line 1719 of file infrun.c.
References _, bpstat_should_step(), breakpoint_here_p(), breakpoint_inserted_here_p(), thread_info::control, current_inferior(), debug_displaced, debug_infrun, discard_cleanups(), displaced_step_dump_bytes(), displaced_step_prepare(), error(), fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_cannot_step_breakpoint(), gdbarch_displaced_step_hw_singlestep(), gdbarch_skip_permanent_breakpoint(), gdbarch_skip_permanent_breakpoint_p(), gdbarch_software_single_step_p(), get_current_frame(), get_current_regcache(), get_displaced_stepping_state(), get_regcache_arch(), get_regcache_aspace(), get_thread_regcache(), inferior_ptid, inferior_thread(), insert_breakpoints(), insert_hp_step_resume_breakpoint_at_frame(), make_cleanup(), thread_control_state::may_range_step, maybe_software_singlestep(), paddress(), pc_in_thread_step_range(), permanent_breakpoint_here, ptid_get_pid(), QUIT, read_memory(), regcache_read_pc(), remove_single_step_breakpoints(), resume_cleanups(), set_running(), signal_pass, singlestep_breakpoints_inserted_p, thread_info::step_after_step_resume_breakpoint, displaced_step_inferior_state::step_closure, thread_control_state::step_resume_breakpoint, stepping_past_singlestep_breakpoint, thread_suspend_state::stop_signal, thread_info::suspend, target_pass_signals(), target_pid_to_str(), target_resume(), target_terminal_inferior(), thread_control_state::trap_expected, use_displaced_stepping(), and user_visible_resume_ptid().
Referenced by do_initial_windows_stuff(), handle_inferior_event(), keep_going(), and proceed().
struct cleanup* save_current_inferior (void) [read]
Definition at line 88 of file inferior.c.
References current_inferior_, make_cleanup(), and restore_inferior().
Referenced by handle_vfork_child_exec_or_exit().
struct infcall_control_state* save_infcall_control_state (void) [read]
Definition at line 6932 of file infrun.c.
References bpstat_copy(), thread_info::control, inferior::control, current_inferior(), thread_control_state::exception_resume_breakpoint, get_frame_id(), get_selected_frame(), infcall_control_state::inferior_control, inferior_thread(), infcall_control_state::selected_frame_id, thread_control_state::step_resume_breakpoint, stop_after_trap, infcall_control_state::stop_after_trap, thread_control_state::stop_bpstat, stop_stack_dummy, infcall_control_state::stop_stack_dummy, stopped_by_random_signal, infcall_control_state::stopped_by_random_signal, infcall_control_state::thread_control, and xmalloc().
Referenced by call_function_by_hand().
struct infcall_suspend_state* save_infcall_suspend_state (void) [read]
Definition at line 6791 of file infrun.c.
References current_inferior(), current_target, discard_cleanups(), do_cleanups(), gdbarch_get_siginfo_type(), gdbarch_get_siginfo_type_p(), get_current_regcache(), get_regcache_arch(), inferior_thread(), len, make_cleanup(), regcache_dup(), infcall_suspend_state::registers, infcall_suspend_state::siginfo_data, infcall_suspend_state::siginfo_gdbarch, stop_pc, infcall_suspend_state::stop_pc, thread_suspend_state::stop_signal, thread_info::suspend, TARGET_OBJECT_SIGNAL_INFO, target_read(), infcall_suspend_state::thread_suspend, TYPE_LENGTH, xfree(), xmalloc(), and XZALLOC.
Referenced by call_function_by_hand().
struct cleanup* save_inferior_ptid (void) [read]
Definition at line 7086 of file infrun.c.
References inferior_ptid, make_cleanup(), restore_inferior_ptid(), and xmalloc().
Referenced by aix_thread_resume(), aix_thread_wait(), aix_thread_xfer_partial(), detach_breakpoints(), displaced_step_prepare(), handle_inferior_event(), handle_vfork_child_exec_or_exit(), linux_child_follow_fork(), linux_corefile_thread_callback(), linux_nat_xfer_partial(), ps_lgetfpregs(), ps_lgetregs(), ps_lsetfpregs(), ps_lsetregs(), ps_xfer_memory(), reattach_breakpoints(), regcache_raw_read(), regcache_raw_write(), rw_common(), save_sigtrap(), sol_thread_resume(), sol_thread_wait(), sol_thread_xfer_partial(), and write_memory_ptid().
void set_current_inferior (struct inferior *)
Definition at line 64 of file inferior.c.
References current_inferior_, gdb_assert, and arm-linux::inf.
Referenced by add_inferior_command(), clone_inferior_command(), do_restore_current_thread_cleanup(), extended_remote_attach_1(), follow_exec(), handle_inferior_event(), inferior_command(), mi_cmd_execute(), mi_cmd_remove_inferior(), restore_inferior(), run_one_inferior(), and switch_to_thread().
void set_inferior_args (char *)
Definition at line 216 of file infcmd.c.
References inferior::argc, inferior::args, inferior::argv, current_inferior(), and xfree().
Referenced by gdb_set_inferior_args(), get_inferior_args(), run_command_1(), run_no_args_command(), and set_args_command().
void set_inferior_args_vector (int , char **)
Definition at line 225 of file infcmd.c.
References inferior::argc, inferior::argv, and current_inferior().
Referenced by captured_main().
void set_inferior_io_terminal (const char * terminal_name)
Definition at line 157 of file infcmd.c.
References current_inferior(), inferior::terminal, and xfree().
Referenced by captured_main(), mi_cmd_inferior_tty_set(), and set_inferior_tty_command().
void set_sigint_trap (void)
Definition at line 780 of file inflow.c.
References inferior::attach_flag, current_inferior(), get_inflow_inferior_data(), osig, pass_signal(), and terminal_info::run_terminal.
Referenced by inf_ptrace_wait(), linux_nat_terminal_inferior(), linux_nat_wait_1(), rs6000_wait(), and spu_child_wait().
void set_step_info (struct frame_info * frame, struct symtab_and_line sal)
Definition at line 2873 of file infrun.c.
References thread_info::control, thread_info::current_line, thread_info::current_symtab, get_frame_id(), get_stack_frame_id(), inferior_thread(), symtab_and_line::line, thread_control_state::step_frame_id, thread_control_state::step_stack_frame_id, and symtab_and_line::symtab.
Referenced by finish_command(), handle_inferior_event(), and set_step_frame().
void signal_catch_update (const unsigned int *)
Definition at line 6301 of file infrun.c.
References signal_cache_update(), signal_catch, signal_pass, and target_pass_signals().
Referenced by signal_catchpoint_insert_location(), and signal_catchpoint_remove_location().
int signal_pass_state (int)
Definition at line 6245 of file infrun.c.
References signal_program.
Referenced by append_pending_thread_resumptions(), get_pending_status(), linux_nat_resume_callback(), linux_nat_wait_1(), and remote_program_signals().
int signal_pass_update (int , int)
Definition at line 6288 of file infrun.c.
References signal_cache_update(), and signal_program.
Referenced by nto_initialize_signals().
int signal_print_state (int)
Definition at line 6239 of file infrun.c.
References signal_print.
int signal_print_update (int , int)
Definition at line 6278 of file infrun.c.
References signal_cache_update(), and signal_print.
Referenced by check_thread_signals(), and nto_initialize_signals().
int signal_stop_state (int)
Definition at line 6233 of file infrun.c.
References signal_stop.
Referenced by handle_inferior_event().
int signal_stop_update (int , int)
Definition at line 6268 of file infrun.c.
References signal_cache_update(), and signal_stop.
Referenced by check_thread_signals(), and nto_initialize_signals().
CORE_ADDR signed_pointer_to_address (struct gdbarch * gdbarch, struct type * type, const gdb_byte * buf)
Definition at line 313 of file findvar.c.
References extract_signed_integer(), gdbarch_byte_order(), and TYPE_LENGTH.
Referenced by mips_gdbarch_init().
void start_remote (int from_tty)
Definition at line 2337 of file infrun.c.
References inferior::control, current_inferior(), current_target, normal_stop(), post_create_inferior(), STOP_QUIETLY_REMOTE, inferior_control_state::stop_soon, and wait_for_inferior().
Referenced by monitor_open(), and remote_start_remote().
void startup_inferior (int)
Definition at line 416 of file fork-child.c.
References _, error(), exec_wrapper, target_waitstatus::execd_pathname, gdb_signal_to_name(), gdb_signal_to_string(), inferior_ptid, target_waitstatus::integer, target_waitstatus::kind, memset(), minus_one_ptid, pid_to_ptid(), ptid_get_pid(), resume_signal, set_executing(), target_waitstatus::sig, switch_to_thread(), target_mourn_inferior(), target_resume(), target_supports_multi_process, target_terminal_inferior(), target_terminal_init, target_terminal_ours, target_wait(), TARGET_WAITKIND_EXECD, TARGET_WAITKIND_EXITED, TARGET_WAITKIND_FORKED, TARGET_WAITKIND_IGNORE, TARGET_WAITKIND_LOADED, TARGET_WAITKIND_SIGNALLED, TARGET_WAITKIND_SPURIOUS, TARGET_WAITKIND_STOPPED, TARGET_WAITKIND_SYSCALL_ENTRY, TARGET_WAITKIND_SYSCALL_RETURN, TARGET_WAITKIND_VFORKED, target_waitstatus::value, and xfree().
Referenced by darwin_ptrace_him(), gnu_create_inferior(), inf_ptrace_create_inferior(), and procfs_init_inferior().
void term_info (char * , int)
Definition at line 563 of file inflow.c.
References target_terminal_info.
void terminal_inferior (void)
Definition at line 275 of file inflow.c.
References inferior::attach_flag, current_inferior(), gdb_has_a_terminal(), get_inflow_inferior_data(), arm-linux::inf, job_control, OOPSY, terminal_info::run_terminal, serial_set_tty_state(), sigint_ours, sigquit_ours, tcsetpgrp(), terminal_info::tflags, and terminal_info::ttystate.
Referenced by inf_child_target(), init_procfs_ops(), init_windows_ops(), and linux_nat_terminal_inferior().
void terminal_init_inferior (void)
Definition at line 258 of file inflow.c.
References inferior_ptid, ptid_get_pid(), and terminal_init_inferior_with_pgrp().
Referenced by inf_child_target(), init_procfs_ops(), and init_windows_ops().
void terminal_init_inferior_with_pgrp (int pgrp)
Definition at line 218 of file inflow.c.
References current_inferior(), gdb_has_a_terminal(), get_inflow_inferior_data(), our_terminal_info, serial_copy_tty_state(), terminal_info::ttystate, and xfree().
Referenced by do_initial_windows_stuff(), gnu_terminal_init_inferior(), and terminal_init_inferior().
void terminal_ours (void)
Definition at line 366 of file inflow.c.
References terminal_ours_1().
Referenced by inf_child_target(), init_procfs_ops(), init_windows_ops(), and linux_nat_terminal_ours().
void terminal_ours_for_output (void)
Definition at line 356 of file inflow.c.
References terminal_ours_1().
Referenced by inf_child_target(), init_procfs_ops(), and init_windows_ops().
void terminal_save_ours (void)
Definition at line 248 of file inflow.c.
References gdb_has_a_terminal(), our_terminal_info, serial_get_tty_state(), terminal_info::ttystate, and xfree().
Referenced by inf_child_target(), and init_windows_ops().
void unsigned_address_to_pointer (struct gdbarch * gdbarch, struct type * type, gdb_byte * buf, CORE_ADDR addr)
Definition at line 324 of file findvar.c.
References gdbarch_byte_order(), store_unsigned_integer(), and TYPE_LENGTH.
Referenced by gdbarch_alloc().
CORE_ADDR unsigned_pointer_to_address (struct gdbarch * gdbarch, struct type * type, const gdb_byte * buf)
Definition at line 304 of file findvar.c.
References extract_unsigned_integer(), gdbarch_byte_order(), and TYPE_LENGTH.
Referenced by gdbarch_alloc().
void update_observer_mode (void)
Definition at line 273 of file infrun.c.
References _, may_insert_breakpoints, may_insert_fast_tracepoints, may_insert_tracepoints, may_stop, non_stop, observer_mode, observer_mode_1, and printf_filtered().
Referenced by set_target_permissions(), and set_write_memory_permission().
void update_signals_program_target (void)
Definition at line 328 of file infrun.c.
References signal_program, and target_program_signals().
Referenced by remote_start_remote().
ptid_t user_visible_resume_ptid (int step)
Definition at line 1681 of file infrun.c.
References inferior_ptid, non_stop, pid_to_ptid(), ptid_get_pid(), RESUME_ALL, sched_multi, schedlock_on, schedlock_step, scheduler_mode, singlestep_breakpoints_inserted_p, and target_supports_multi_process.
Referenced by resume(), and step_once().
int valid_gdb_inferior_id (int num)
Definition at line 404 of file inferior.c.
References arm-linux::inf, inferior_list, inferior::next, and inferior::num.
Referenced by detach_inferior_command(), and kill_inferior_command().
void wait_for_inferior (void)
Definition at line 2713 of file infrun.c.
References debug_infrun, delete_step_thread_step_resume_breakpoint_cleanup(), deprecated_target_wait_hook, discard_cleanups(), do_cleanups(), finish_thread_state_cleanup(), fprintf_unfiltered(), gdb_stdlog, handle_inferior_event(), make_cleanup(), memset(), minus_one_ptid, overlay_cache_invalid, print_target_wait_results(), execution_control_state::ptid, target_wait(), execution_control_state::wait_some_more, and execution_control_state::ws.
Referenced by attach_command(), do_initial_windows_stuff(), irix_solib_create_inferior_hook(), notice_new_inferior(), osf_solib_create_inferior_hook(), proceed(), run_inferior_call(), and start_remote().
Variable Documentation
int debug_displaced
Definition at line 142 of file infrun.c.
Referenced by amd64_displaced_step_copy_insn(), amd64_displaced_step_fixup(), amd64_relocate_instruction(), arm_copy_alu_imm(), arm_copy_alu_reg(), arm_copy_alu_shifted_reg(), arm_copy_b_bl_blx(), arm_copy_block_xfer(), arm_copy_bx_blx_reg(), arm_copy_copro_load_store(), arm_copy_extra_ld_st(), arm_copy_ldr_str_ldrb_strb(), arm_copy_preload(), arm_copy_preload_reg(), arm_copy_svc(), arm_copy_undef(), arm_copy_unmodified(), arm_copy_unpred(), arm_displaced_init_closure(), arm_linux_cleanup_svc(), arm_linux_copy_svc(), arm_linux_displaced_step_copy_insn(), arm_pc_is_thumb(), arm_process_displaced_insn(), cleanup_block_load_all(), cleanup_block_load_pc(), cleanup_block_store_pc(), cleanup_svc(), displaced_read_reg(), displaced_step_fixup(), displaced_step_prepare(), displaced_step_restore(), displaced_write_reg(), fixup_riprel(), handle_inferior_event(), i386_displaced_step_copy_insn(), i386_displaced_step_fixup(), i386_relocate_instruction(), ppc_displaced_step_fixup(), resume(), s390_displaced_step_fixup(), simple_displaced_step_copy_insn(), thumb2_copy_alu_imm(), thumb2_copy_b_bl_blx(), thumb2_copy_block_xfer(), thumb2_copy_copro_load_store(), thumb2_copy_load_literal(), thumb2_copy_load_reg_imm(), thumb2_copy_preload(), thumb2_copy_table_branch(), thumb_32bit_copy_undef(), thumb_copy_16bit_ldr_literal(), thumb_copy_alu_reg(), thumb_copy_b(), thumb_copy_bx_blx_reg(), thumb_copy_cbnz_cbz(), thumb_copy_pc_relative_32bit(), thumb_copy_pop_pc_16bit(), thumb_copy_svc(), thumb_copy_unmodified_16bit(), thumb_copy_unmodified_32bit(), thumb_decode_pc_relative_16bit(), and thumb_process_displaced_insn().
unsigned int debug_infrun
Definition at line 150 of file infrun.c.
Referenced by bpstat_what(), clear_proceed_status_thread(), context_switch(), fetch_inferior_event(), handle_inferior_event(), handle_syscall_event(), handle_vfork_child_exec_or_exit(), insert_exception_resume_breakpoint(), insert_exception_resume_from_probe(), insert_longjmp_resume_breakpoint(), insert_step_resume_breakpoint_at_sal_1(), prepare_for_detach(), prepare_to_proceed(), prepare_to_wait(), proceed(), proceed_after_vfork_done(), resume(), stop_stepping(), and wait_for_inferior().
int disable_randomization
Definition at line 161 of file infrun.c.
Referenced by extended_remote_create_inferior_1(), and linux_nat_create_inferior().
int execution_direction
Definition at line 7109 of file infrun.c.
Referenced by adjust_pc_after_break(), call_function_by_hand(), exec_direction_default(), exec_direction_forward(), exec_reverse_continue(), exec_reverse_once(), fetch_inferior_event(), finish_command(), handle_inferior_event(), maybe_software_singlestep(), normal_stop(), proceed(), record_full_core_resume(), record_full_resume(), record_full_wait_1(), record_full_wait_cleanups(), and remote_resume().
struct inferior* inferior_list
Definition at line 47 of file inferior.c.
Referenced by ada_new_objfile_observer(), add_inferior_silent(), delete_inferior_1(), discard_all_inferiors(), exit_inferior_1(), find_inferior_for_program_space(), find_inferior_id(), find_inferior_pid(), have_inferiors(), have_live_inferiors(), in_inferior_list(), init_inferior_list(), iterate_over_inferiors(), number_of_inferiors(), pid_to_gdb_inferior_id(), print_inferior(), print_program_space(), prune_inferiors(), update_address_spaces(), and valid_gdb_inferior_id().
ptid_t inferior_ptid
Definition at line 135 of file infcmd.c.
Referenced by aarch64_handle_aligned_watchpoint(), aarch64_handle_breakpoint(), aarch64_handle_unaligned_watchpoint(), aarch64_linux_get_debug_reg_capacity(), aarch64_linux_insert_hw_breakpoint(), aarch64_linux_insert_watchpoint(), aarch64_linux_remove_hw_breakpoint(), aarch64_linux_remove_watchpoint(), aarch64_linux_stopped_data_address(), aarch64_notify_debug_reg_change(), ada_exception_support_info_sniffer(), add_current_inferior_and_thread(), add_fork(), add_thread_db_info(), add_thread_silent(), add_to_thread_list(), adjust_pc_after_break(), aix_thread_fetch_registers(), aix_thread_get_ada_task_ptid(), aix_thread_resume(), aix_thread_store_registers(), aix_thread_wait(), aix_thread_xfer_partial(), alphabsd_fetch_inferior_registers(), alphabsd_store_inferior_registers(), amd64_linux_dr_get_addr(), amd64_linux_dr_get_control(), amd64_linux_dr_get_status(), amd64_linux_dr_set_addr(), amd64_linux_dr_set_control(), amd64_linux_fetch_inferior_registers(), amd64_linux_read_description(), amd64_linux_store_inferior_registers(), amd64bsd_fetch_inferior_registers(), amd64bsd_store_inferior_registers(), append_pending_thread_resumptions(), arm_linux_get_hwbp_cap(), arm_linux_read_description(), arm_linux_stopped_data_address(), async_remote_interrupt(), bpfinishpy_init(), bpstat_clear_actions(), bpstat_do_actions(), breakpoint_about_to_proceed(), breakpoint_re_set_thread(), bsd_kvm_close(), bsd_kvm_open(), bsd_uthread_fetch_registers(), bsd_uthread_find_new_threads(), bsd_uthread_store_registers(), bsd_uthread_thread_alive(), bsd_uthread_wait(), call_function_by_hand(), can_use_watchpoint_cond_accel(), check_for_thread_db(), checkpoint_command(), child_terminal_info(), clear_proceed_status(), cmd_record_save(), context_switch(), core_close(), core_open(), cur_thread(), darwin_attach(), darwin_create_inferior(), darwin_detach(), darwin_get_ada_task_ptid(), darwin_init_thread_list(), darwin_kill_inferior(), darwin_resume(), darwin_stop_inferior(), dcache_xfer_memory(), dec_thread_fetch_registers(), dec_thread_get_ada_task_ptid(), dec_thread_store_registers(), default_child_has_all_memory(), default_child_has_memory(), default_child_has_registers(), default_child_has_stack(), default_get_ada_task_ptid(), delete_checkpoint_command(), delete_fork(), delete_step_thread_step_resume_breakpoint(), delete_thread_1(), detach_breakpoints(), detach_checkpoint_command(), displaced_step_prepare(), display_current_task_id(), display_tib(), do_all_continuations_ptid(), do_captured_list_thread_ids(), do_captured_thread_select(), do_detach(), do_initial_windows_stuff(), do_restore_current_thread_cleanup(), elf_gnu_ifunc_resolver_return_stop(), elf_gnu_ifunc_resolver_stop(), enable_break(), enable_thread_event(), enable_thread_event_reporting(), exec_one_dummy_insn(), extended_remote_attach_1(), extended_remote_kill(), extended_remote_mourn_1(), fbsd_find_memory_regions(), fbsd_make_corefile_notes(), fetch_fp_register(), fetch_fp_regs(), fetch_fpregister(), fetch_fpregs(), fetch_fpregs_from_thread(), fetch_gregs(), fetch_gregs_from_thread(), fetch_inferior_event(), fetch_inferior_registers(), fetch_ppc_memory(), fetch_ppc_register(), fetch_register(), fetch_regs(), fetch_vfp_regs(), fetch_wmmx_regs(), fetch_xtregs(), find_frame_sal(), find_signalled_thread(), follow_exec(), follow_fork(), fork_inferior(), frame_inlined_callees(), frame_show_address(), gcore_command(), gdb_clear_file(), gdb_target_has_execution_command(), gdbpy_selected_thread(), gdbsim_create_inferior(), gdbsim_open(), gdbsim_wait(), gdbtk_annotate_signal(), generic_mourn_inferior(), get_core_register_section(), get_core_siginfo(), get_current_frame(), get_current_regcache(), get_displaced_step_closure_by_addr(), get_event_thread(), get_signaled_thread(), get_task_from_args(), get_windows_debug_event(), gnu_attach(), gnu_create_inferior(), gnu_detach(), gnu_fetch_registers(), gnu_resume(), gnu_store_registers(), gnu_wait(), go32_create_inferior(), go32_mourn_inferior(), go32_thread_alive(), handle_inferior_event(), handle_syscall_event(), handle_vfork_child_exec_or_exit(), has_stack_frames(), hppa_hpux_fetch_register(), hppa_hpux_store_register(), hppabsd_fetch_registers(), hppabsd_store_registers(), hppanbsd_fetch_registers(), hppanbsd_store_registers(), i386_cleanup_dregs(), i386_darwin_dr_get(), i386_darwin_dr_set(), i386_darwin_fetch_inferior_registers(), i386_darwin_store_inferior_registers(), i386_insert_hw_breakpoint(), i386_insert_watchpoint(), i386_linux_dr_get_addr(), i386_linux_dr_get_control(), i386_linux_dr_get_status(), i386_linux_dr_set_addr(), i386_linux_dr_set_control(), i386_linux_fetch_inferior_registers(), i386_linux_read_description(), i386_linux_store_inferior_registers(), i386_region_ok_for_watchpoint(), i386_remove_hw_breakpoint(), i386_remove_watchpoint(), i386_stopped_data_address(), i386_update_inferior_debug_regs(), i386bsd_fetch_inferior_registers(), i386bsd_store_inferior_registers(), i386fbsd_resume(), ia64_hpux_at_dld_breakpoint_p(), ia64_hpux_fetch_rnat_register(), ia64_hpux_get_load_info_addr(), ia64_hpux_handle_dld_breakpoint(), ia64_hpux_mourn_inferior(), ia64_hpux_read_memory_bs(), ia64_hpux_read_register_from_save_state_t(), ia64_hpux_write_memory_bs(), ia64_hpux_write_register_to_saved_state_t(), ia64_hpux_xfer_memory(), ia64_linux_fetch_register(), ia64_linux_stopped_data_address(), ia64_linux_store_register(), inf_ptrace_attach(), inf_ptrace_detach(), inf_ptrace_fetch_register(), inf_ptrace_files_info(), inf_ptrace_kill(), inf_ptrace_mourn_inferior(), inf_ptrace_resume(), inf_ptrace_store_register(), inf_ptrace_wait(), inf_ptrace_xfer_partial(), inf_validate_procs(), inferior_call_waitpid(), inferior_command(), inferior_event_handler(), inferior_thread(), info_checkpoints_command(), info_mach_exceptions_command(), info_mach_ports_command(), info_mach_region_command(), infrun_thread_ptid_changed(), init_wait_for_inferior(), inline_frame_sniffer(), insert_breakpoint_locations(), insert_catch_exec(), insert_catch_fork(), insert_catch_syscall(), insert_catch_vfork(), interrupt_target_1(), linux_child_follow_fork(), linux_corefile_thread_callback(), linux_fill_prpsinfo(), linux_fork_context(), linux_fork_detach(), linux_fork_mourn_inferior(), linux_make_corefile_notes(), linux_nat_attach(), linux_nat_detach(), linux_nat_kill(), linux_nat_mourn_inferior(), linux_nat_resume(), linux_nat_stopped_by_watchpoint(), linux_nat_stopped_data_address(), linux_nat_switch_fork(), linux_nat_wait_1(), linux_nat_xfer_partial(), linux_proc_xfer_partial(), linux_proc_xfer_spu(), linux_xfer_siginfo(), m32r_close(), m32r_detach(), m32r_kill(), m32r_linux_fetch_inferior_registers(), m32r_linux_store_inferior_registers(), m32r_load(), m32r_resume(), m32r_upload_command(), m32r_wait(), m68k_linux_fetch_inferior_registers(), m68k_linux_store_inferior_registers(), m68kbsd_fetch_inferior_registers(), m68kbsd_store_inferior_registers(), m88kbsd_fetch_inferior_registers(), m88kbsd_store_inferior_registers(), make_cleanup_restore_current_thread(), maybe_software_singlestep(), memory_xfer_partial_1(), mi_about_to_proceed(), mi_cmd_var_update_iter(), mi_execute_command(), mi_on_normal_stop(), mips64_linux_regsets_fetch_registers(), mips64_linux_regsets_store_registers(), mips64obsd_fetch_inferior_registers(), mips64obsd_store_inferior_registers(), mips_error(), mips_linux_can_use_hw_breakpoint(), mips_linux_insert_watchpoint(), mips_linux_new_thread(), mips_linux_read_description(), mips_linux_region_ok_for_hw_watchpoint(), mips_linux_stopped_by_watchpoint(), mipsnbsd_fetch_inferior_registers(), mipsnbsd_store_inferior_registers(), monitor_interrupt(), monitor_open(), monitor_wait(), normal_stop(), nto_interrupt(), open_map(), pass_signal(), pd_activate(), pd_deactivate(), pd_update(), pop_dummy_frame_bpt(), ppc_linux_can_use_hw_breakpoint(), ppc_linux_fetch_inferior_registers(), ppc_linux_read_description(), ppc_linux_spe_context(), ppc_linux_stopped_data_address(), ppc_linux_store_inferior_registers(), ppc_linux_target_wordsize(), ppc_ravenscar_generic_fetch_registers(), ppc_ravenscar_generic_store_registers(), ppcfbsd_fetch_inferior_registers(), ppcfbsd_store_inferior_registers(), ppcnbsd_fetch_inferior_registers(), ppcnbsd_store_inferior_registers(), ppcobsd_fetch_registers(), ppcobsd_store_registers(), prepare_to_proceed(), print_ada_task_info(), print_thread_info(), proc_find_memory_regions(), proc_set_current_signal(), proc_trace_syscalls(), proceed(), process_stop_reply(), procfs_attach(), procfs_create_inferior(), procfs_detach(), procfs_fetch_registers(), procfs_files_info(), procfs_find_new_threads(), procfs_inferior_created(), procfs_info_proc(), procfs_insert_watchpoint(), procfs_kill_inferior(), procfs_mourn_inferior(), procfs_pass_signals(), procfs_remove_watchpoint(), procfs_resume(), procfs_set_watchpoint(), procfs_stopped_by_watchpoint(), procfs_stopped_data_address(), procfs_store_registers(), procfs_wait(), procfs_xfer_auxv(), procfs_xfer_memory(), program_info(), ps_lgetfpregs(), ps_lgetregs(), ps_lsetfpregs(), ps_lsetregs(), ps_xfer_memory(), ptid_build_from_info(), python_on_normal_stop(), ravenscar_fetch_registers(), ravenscar_inferior_created(), ravenscar_prepare_to_store(), ravenscar_resume(), ravenscar_store_registers(), ravenscar_update_inferior_ptid(), ravenscar_wait(), read_ptid(), reattach_breakpoints(), record_btrace_info(), record_full_wait_1(), regcache_raw_read(), regcache_raw_write(), registers_changed_ptid(), remote_close(), remote_detach_1(), remote_fetch_registers(), remote_get_ada_task_ptid(), remote_newthread_step(), remote_notice_new_inferior(), remote_parse_stop_reply(), remote_read_description(), remote_start_remote(), remote_store_registers(), remote_vcont_resume(), remote_wait_as(), remote_xfer_partial(), remove_catch_exec(), remove_catch_fork(), remove_catch_syscall(), remove_catch_vfork(), require_btrace(), restore_inferior_ptid(), resume(), rs6000_wait(), rs6000_xfer_partial(), rs6000_xfer_shared_libraries(), run_inferior_call(), run_one_inferior(), rw_common(), s390_inferior_tid(), save_inferior_ptid(), save_sigtrap(), sdireset_command(), set_enable_mach_exceptions(), set_general_process(), set_longjmp_breakpoint_for_call_dummy(), set_momentary_breakpoint(), shnbsd_fetch_inferior_registers(), shnbsd_store_inferior_registers(), siginfo_make_value(), sol_find_new_threads_callback(), sol_thread_detach(), sol_thread_fetch_registers(), sol_thread_resume(), sol_thread_store_registers(), sol_thread_wait(), sol_thread_xfer_partial(), som_solib_create_inferior_hook(), sparc_fetch_inferior_registers(), sparc_ravenscar_fetch_registers(), sparc_ravenscar_store_registers(), sparc_store_inferior_registers(), sparc_xfer_wcookie(), spu2ppu_sniffer(), spu_child_wait(), spu_fetch_registers(), spu_memory_remove_breakpoint(), spu_proc_xfer_spu(), spu_skip_standalone_loader(), spu_store_registers(), startup_inferior(), store_fp_register(), store_fp_regs(), store_fpregister(), store_fpregs(), store_fpregs_to_thread(), store_gregs(), store_gregs_to_thread(), store_inferior_registers(), store_ppc_memory(), store_register(), store_regs(), store_vfp_regs(), store_wmmx_regs(), store_xtregs(), switch_to_thread(), sync_threadlists(), target_detach(), target_has_execution_current(), target_translate_tls_address(), terminal_init_inferior(), thread_apply_all_command(), thread_apply_command(), thread_command(), thread_db_detach(), thread_db_get_ada_task_ptid(), thread_db_load(), thread_db_mourn_inferior(), thread_db_resume(), thread_id_make_value(), thread_name_command(), tlb_make_value(), tlb_value_read(), try_thread_db_load(), try_thread_db_load_1(), tui_make_status_line(), until_break_command(), update_inserted_breakpoint_locations(), update_solib_list(), user_visible_resume_ptid(), validate_siginfo_access(), varobj_create(), vax_register_u_offset(), vaxbsd_fetch_inferior_registers(), vaxbsd_store_inferior_registers(), VEC(), watch_command_1(), watchpoint_in_thread_scope(), windows_close(), windows_detach(), windows_fetch_inferior_registers(), windows_files_info(), windows_get_ada_task_ptid(), windows_resume(), windows_store_inferior_registers(), and write_memory_ptid().
int non_stop
Definition at line 190 of file infrun.c.
Referenced by adjust_pc_after_break(), agent_run_command(), attach_command(), attach_command_post_wait(), breakpoints_always_inserted_mode(), clear_proceed_status(), continue_1(), continue_command(), delete_step_thread_step_resume_breakpoint(), exec_continue(), extended_remote_attach_1(), fetch_inferior_event(), follow_fork(), get_event_thread(), get_pending_status(), handle_inferior_event(), handle_notification(), handle_vfork_child_exec_or_exit(), inferior_event_handler(), interrupt_target_1(), interrupt_target_command(), linux_child_follow_fork(), linux_handle_extended_wait(), linux_nat_stop(), linux_nat_wait(), linux_nat_wait_1(), mi_cmd_exec_interrupt(), mi_on_normal_stop(), normal_stop(), notice_new_inferior(), prepare_execute_command(), prepare_to_proceed(), proceed(), program_info(), putpkt_binary(), record_full_open_1(), remote_async_get_pending_events_handler(), remote_parse_stop_reply(), remote_resume(), remote_start_remote(), remote_stop(), remote_threads_info(), remote_vcont_resume(), remote_wait(), run_command_1(), set_non_stop(), set_observer_mode(), show_can_use_displaced_stepping(), update_global_location_list(), update_observer_mode(), use_displaced_stepping(), and user_visible_resume_ptid().
int sched_multi
Definition at line 1644 of file infrun.c.
Referenced by exec_continue(), linux_child_follow_fork(), prepare_to_proceed(), and user_visible_resume_ptid().
int step_stop_if_no_debug
Definition at line 117 of file infrun.c.
Referenced by handle_inferior_event(), and step_once().
int stop_on_solib_events
Definition at line 347 of file infrun.c.
Referenced by handle_inferior_event(), internal_bkpt_check_status(), and svr4_update_solib_event_breakpoint().
CORE_ADDR stop_pc
Definition at line 139 of file infcmd.c.
Referenced by check_event(), cplus_skip_trampoline(), fill_in_stop_func(), fork_load_infrun_state(), gdb_loc(), gnuv3_skip_trampoline(), handle_inferior_event(), handle_step_into_function(), handle_step_into_function_backward(), handle_syscall_event(), normal_stop(), post_create_inferior(), proceed(), program_info(), restore_infcall_suspend_state(), save_infcall_suspend_state(), and switch_to_thread().
struct regcache* stop_registers
Definition at line 376 of file infrun.c.
Referenced by call_function_by_hand(), and get_return_value().
enum stop_stack_kind stop_stack_dummy
Definition at line 143 of file infcmd.c.
Referenced by call_function_by_hand(), handle_inferior_event(), normal_stop(), restore_infcall_control_state(), and save_infcall_control_state().
int stopped_by_random_signal
Definition at line 148 of file infcmd.c.
Referenced by call_function_by_hand(), handle_inferior_event(), normal_stop(), restore_infcall_control_state(), and save_infcall_control_state().
int sync_execution
Definition at line 127 of file infrun.c.
Referenced by async_background_execution_p(), async_disable_stdin(), async_enable_stdin(), display_gdb_prompt(), execute_command(), fetch_inferior_event(), handle_inferior_event(), linux_child_follow_fork(), mi_interpreter_resume(), normal_stop(), and target_terminal_inferior().