GDB (xrefs): /home/stan/gdb/src/gdb/inflow.c File Reference
/home/stan/gdb/src/gdb/inflow.c File Reference
#include "defs.h"
#include "frame.h"
#include "inferior.h"
#include "command.h"
#include "serial.h"
#include "terminal.h"
#include "target.h"
#include "gdbthread.h"
#include "observer.h"
#include "gdb_string.h"
#include <signal.h>
#include <fcntl.h>
#include "gdb_select.h"
#include "inflow.h"
#include "gdbcmd.h"
Classes
struct terminal_info
Defines
#define O_NOCTTY 0
#define OOPSY(what)
#define O_ACCMODE (O_RDONLY | O_WRONLY | O_RDWR)
Enumerations
enum { yes, no, have_not_checked }
Functions
void _initialize_inflow (void)
static void pass_signal (int)
static void terminal_ours_1 (int)
static struct terminal_info * get_inflow_inferior_data (struct inferior *)
static void show_interactive_mode (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
int gdb_has_a_terminal (void)
void terminal_init_inferior_with_pgrp (int pgrp)
void terminal_save_ours (void)
void terminal_init_inferior (void)
void terminal_inferior (void)
void terminal_ours_for_output (void)
void terminal_ours (void)
static void inflow_inferior_data_cleanup (struct inferior *inf, void *arg)
static void inflow_inferior_exit (struct inferior *inf)
void copy_terminal_info (struct inferior *to, struct inferior *from)
void term_info (char *arg, int from_tty)
void child_terminal_info (const char *args, int from_tty)
void new_tty_prefork (const char *ttyname)
static void check_syscall (const char *msg, int result)
void new_tty (void)
void new_tty_postfork (void)
void set_sigint_trap (void)
void clear_sigint_trap (void)
pid_t create_tty_session (void)
int gdb_setpgid (void)
void initialize_stdin_serial (void)
Variables
static struct serial * stdin_serial
static struct terminal_info our_terminal_info
static void(* sigint_ours)()
static void(* sigquit_ours)()
static const char * inferior_thisrun_terminal
int terminal_is_ours
enum { ... } gdb_has_a_terminal_flag
static enum auto_boolean interactive_mode = AUTO_BOOLEAN_AUTO
static struct inferior_data * inflow_inferior_data
static void(* osig)()
static int osig_set
Define Documentation
#define O_ACCMODE (O_RDONLY | O_WRONLY | O_RDWR)
Referenced by child_terminal_info().
#define O_NOCTTY 0
Definition at line 42 of file inflow.c.
Referenced by new_tty(), and windows_create_inferior().
#define OOPSY (what)
Value:
if (result == -1)       \
    fprintf_unfiltered(gdb_stderr, "[%s failed in terminal_inferior: %s]\n", \
            what, safe_strerror (errno))
Definition at line 207 of file inflow.c.
Referenced by terminal_inferior().
Enumeration Type Documentation
anonymous enum
Enumerator:
yes
no
have_not_checked
Definition at line 137 of file inflow.c.
Function Documentation
void _initialize_inflow (void)
static void check_syscall (const char * msg, int result) [static]
Definition at line 674 of file inflow.c.
References print_sys_errmsg().
Referenced by new_tty().
void child_terminal_info (const char * args, int from_tty)
Definition at line 569 of file inflow.c.
References _, current_inferior(), flags, gdb_has_a_terminal(), gdb_stdout, get_inflow_inferior_data(), arm-linux::inf, inferior_ptid, null_ptid, O_ACCMODE, printf_filtered(), ptid_equal(), serial_print_tty_state(), terminal_info::tflags, and terminal_info::ttystate.
Referenced by inf_child_target(), init_procfs_ops(), and init_windows_ops().
void clear_sigint_trap (void)
Definition at line 795 of file inflow.c.
References osig.
Referenced by inf_ptrace_wait(), linux_nat_terminal_ours(), linux_nat_wait_1(), rs6000_wait(), and spu_child_wait().
void copy_terminal_info (struct inferior * to, struct inferior * from)
Definition at line 541 of file inflow.c.
References get_inflow_inferior_data(), terminal_info::run_terminal, serial_copy_tty_state(), terminal_info::ttystate, and xfree().
Referenced by linux_child_follow_fork().
pid_t create_tty_session (void)
Definition at line 813 of file inflow.c.
References _, job_control, safe_strerror(), and warning().
Referenced by fork_inferior().
int gdb_has_a_terminal (void)
Definition at line 163 of file inflow.c.
References AUTO_BOOLEAN_AUTO, AUTO_BOOLEAN_TRUE, gdb_has_a_terminal_flag, have_not_checked, no, our_terminal_info, serial_get_tty_state(), terminal_info::tflags, terminal_info::ttystate, and yes.
Referenced by child_terminal_info(), input_from_terminal_p(), show_interactive_mode(), terminal_inferior(), terminal_init_inferior_with_pgrp(), terminal_ours_1(), and terminal_save_ours().
int gdb_setpgid (void)
Definition at line 842 of file inflow.c.
References job_control.
Referenced by fork_inferior().
static struct terminal_info * get_inflow_inferior_data (struct inferior * inf) [static, read]
Definition at line 505 of file inflow.c.
References XZALLOC.
Referenced by child_terminal_info(), copy_terminal_info(), new_tty_postfork(), set_sigint_trap(), terminal_inferior(), terminal_init_inferior_with_pgrp(), and terminal_ours_1().
static void inflow_inferior_data_cleanup (struct inferior * inf, void * arg) [static]
Definition at line 488 of file inflow.c.
References terminal_info::run_terminal, terminal_info::ttystate, and xfree().
static void inflow_inferior_exit (struct inferior * inf) [static]
Definition at line 526 of file inflow.c.
References terminal_info::run_terminal, terminal_info::ttystate, and xfree().
void initialize_stdin_serial (void)
Definition at line 876 of file inflow.c.
References serial_fdopen().
Referenced by gdb_init().
void new_tty (void)
Definition at line 685 of file inflow.c.
References _, check_syscall(), O_NOCTTY, safe_strerror(), and warning().
Referenced by fork_inferior().
void new_tty_postfork (void)
Definition at line 748 of file inflow.c.
References current_inferior(), get_inflow_inferior_data(), and terminal_info::run_terminal.
Referenced by fork_inferior().
void new_tty_prefork (const char * ttyname)
Definition at line 662 of file inflow.c.
Referenced by fork_inferior().
static void pass_signal (int signo) [static]
Definition at line 769 of file inflow.c.
References inferior_ptid, and ptid_get_pid().
Referenced by set_sigint_trap().
void set_sigint_trap (void)
Definition at line 780 of file inflow.c.
References inferior::attach_flag, current_inferior(), get_inflow_inferior_data(), osig, pass_signal(), and terminal_info::run_terminal.
Referenced by inf_ptrace_wait(), linux_nat_terminal_inferior(), linux_nat_wait_1(), rs6000_wait(), and spu_child_wait().
static void show_interactive_mode (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 149 of file inflow.c.
References AUTO_BOOLEAN_AUTO, fprintf_filtered(), and gdb_has_a_terminal().
void term_info (char * arg, int from_tty)
Definition at line 563 of file inflow.c.
References target_terminal_info.
void terminal_inferior (void)
Definition at line 275 of file inflow.c.
References inferior::attach_flag, current_inferior(), gdb_has_a_terminal(), get_inflow_inferior_data(), arm-linux::inf, job_control, OOPSY, terminal_info::run_terminal, serial_set_tty_state(), sigint_ours, sigquit_ours, tcsetpgrp(), terminal_info::tflags, and terminal_info::ttystate.
Referenced by inf_child_target(), init_procfs_ops(), init_windows_ops(), and linux_nat_terminal_inferior().
void terminal_init_inferior (void)
Definition at line 258 of file inflow.c.
References inferior_ptid, ptid_get_pid(), and terminal_init_inferior_with_pgrp().
Referenced by inf_child_target(), init_procfs_ops(), and init_windows_ops().
void terminal_init_inferior_with_pgrp (int pgrp)
Definition at line 218 of file inflow.c.
References current_inferior(), gdb_has_a_terminal(), get_inflow_inferior_data(), our_terminal_info, serial_copy_tty_state(), terminal_info::ttystate, and xfree().
Referenced by do_initial_windows_stuff(), gnu_terminal_init_inferior(), and terminal_init_inferior().
void terminal_ours (void)
Definition at line 366 of file inflow.c.
References terminal_ours_1().
Referenced by inf_child_target(), init_procfs_ops(), init_windows_ops(), and linux_nat_terminal_ours().
static void terminal_ours_1 (int output_only) [static]
Definition at line 376 of file inflow.c.
References inferior::attach_flag, current_inferior(), fprintf_unfiltered(), gdb_has_a_terminal(), gdb_stderr, get_inflow_inferior_data(), arm-linux::inf, job_control, our_terminal_info, terminal_info::run_terminal, safe_strerror(), serial_get_tty_state(), serial_noflush_set_tty_state(), sigint_ours, sigquit_ours, tcsetpgrp(), terminal_info::tflags, terminal_info::ttystate, and xfree().
Referenced by terminal_ours(), and terminal_ours_for_output().
void terminal_ours_for_output (void)
Definition at line 356 of file inflow.c.
References terminal_ours_1().
Referenced by inf_child_target(), init_procfs_ops(), and init_windows_ops().
void terminal_save_ours (void)
Definition at line 248 of file inflow.c.
References gdb_has_a_terminal(), our_terminal_info, serial_get_tty_state(), terminal_info::ttystate, and xfree().
Referenced by inf_child_target(), and init_windows_ops().
Variable Documentation
enum { ... } gdb_has_a_terminal_flag
Referenced by gdb_has_a_terminal().
const char* inferior_thisrun_terminal [static]
Definition at line 110 of file inflow.c.
struct inferior_data* inflow_inferior_data [static]
Definition at line 485 of file inflow.c.
enum auto_boolean interactive_mode = AUTO_BOOLEAN_AUTO [static]
Definition at line 144 of file inflow.c.
void(* osig)() [static]
Definition at line 776 of file inflow.c.
Referenced by clear_sigint_trap(), and set_sigint_trap().
int osig_set [static]
Definition at line 777 of file inflow.c.
struct terminal_info our_terminal_info [static]
Definition at line 82 of file inflow.c.
Referenced by gdb_has_a_terminal(), terminal_init_inferior_with_pgrp(), terminal_ours_1(), and terminal_save_ours().
void(* sigint_ours)() [static]
Definition at line 102 of file inflow.c.
Referenced by terminal_inferior(), and terminal_ours_1().
void(* sigquit_ours)() [static]
Definition at line 103 of file inflow.c.
Referenced by terminal_inferior(), and terminal_ours_1().
struct serial* stdin_serial [static]
Definition at line 53 of file inflow.c.
int terminal_is_ours
Definition at line 116 of file inflow.c.