GDB (xrefs): /home/stan/gdb/src/gdb/infrun.c File Reference
/home/stan/gdb/src/gdb/infrun.c File Reference
#include "defs.h"
#include "gdb_string.h"
#include <ctype.h>
#include "symtab.h"
#include "frame.h"
#include "inferior.h"
#include "exceptions.h"
#include "breakpoint.h"
#include "gdb_wait.h"
#include "gdbcore.h"
#include "gdbcmd.h"
#include "cli/cli-script.h"
#include "target.h"
#include "gdbthread.h"
#include "annotate.h"
#include "symfile.h"
#include "top.h"
#include <signal.h>
#include "inf-loop.h"
#include "regcache.h"
#include "value.h"
#include "observer.h"
#include "language.h"
#include "solib.h"
#include "main.h"
#include "dictionary.h"
#include "block.h"
#include "gdb_assert.h"
#include "mi/mi-common.h"
#include "event-top.h"
#include "record.h"
#include "record-full.h"
#include "inline-frame.h"
#include "jit.h"
#include "tracepoint.h"
#include "continuations.h"
#include "interps.h"
#include "skip.h"
#include "probe.h"
#include "objfiles.h"
#include "completer.h"
#include "target-descriptions.h"
Classes
struct displaced_step_request
struct displaced_step_inferior_state
struct execution_control_state
struct infcall_suspend_state
struct infcall_control_state
Defines
#define SET_SIGS(nsigs, sigs, flags)
#define UNSET_SIGS(nsigs, sigs, flags)
#define RESUME_ALL minus_one_ptid
Enumerations
enum infwait_states { infwait_normal_state, infwait_thread_hop_state, infwait_step_watch_state, infwait_nonstep_watch_state }
Functions
static void signals_info (char *, int)
static void handle_command (char *, int)
static void sig_print_info (enum gdb_signal)
static void sig_print_header (void)
static void resume_cleanups (void *)
static int hook_stop_stub (void *)
static int restore_selected_frame (void *)
static int follow_fork (void)
static void set_schedlock_func (char *args, int from_tty, struct cmd_list_element *c)
static int currently_stepping (struct thread_info *tp)
static int currently_stepping_or_nexting_callback (struct thread_info *tp, void *data)
static void xdb_handle_command (char *args, int from_tty)
static int prepare_to_proceed (int)
static void print_exited_reason (int exitstatus)
static void print_signal_exited_reason (enum gdb_signal siggnal)
static void print_no_history_reason (void)
static void print_signal_received_reason (enum gdb_signal siggnal)
static void print_end_stepping_range_reason (void)
void _initialize_infrun (void)
void nullify_last_target_wait_ptid (void)
static void insert_hp_step_resume_breakpoint_at_frame (struct frame_info *)
static void insert_step_resume_breakpoint_at_caller (struct frame_info *)
static void insert_longjmp_resume_breakpoint (struct gdbarch *, CORE_ADDR)
static void show_step_stop_if_no_debug (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static void show_debug_displaced (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static void show_debug_infrun (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static void show_disable_randomization (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static void set_disable_randomization (char *args, int from_tty, struct cmd_list_element *c)
static void set_non_stop (char *args, int from_tty, struct cmd_list_element *c)
static void show_non_stop (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static void set_observer_mode (char *args, int from_tty, struct cmd_list_element *c)
static void show_observer_mode (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
void update_observer_mode (void)
void update_signals_program_target (void)
static void set_stop_on_solib_events (char *args, int from_tty, struct cmd_list_element *c)
static void show_stop_on_solib_events (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static void context_switch (ptid_t ptid)
void init_thread_stepping_state (struct thread_info *tss)
static void init_infwait_state (void)
static void show_follow_fork_mode_string (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
void follow_inferior_reset_breakpoints (void)
static int proceed_after_vfork_done (struct thread_info *thread, void *arg)
static void handle_vfork_child_exec_or_exit (int exec)
static void show_follow_exec_mode_string (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static void follow_exec (ptid_t pid, char *execd_pathname)
static struct
displaced_step_inferior_state * get_displaced_stepping_state (int pid)
static struct
displaced_step_inferior_state * add_displaced_stepping_state (int pid)
struct displaced_step_closure * get_displaced_step_closure_by_addr (CORE_ADDR addr)
static void remove_displaced_stepping_state (int pid)
static void infrun_inferior_exit (struct inferior *inf)
static void show_can_use_displaced_stepping (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static int use_displaced_stepping (struct gdbarch *gdbarch)
static void displaced_step_clear (struct displaced_step_inferior_state *displaced)
static void displaced_step_clear_cleanup (void *arg)
void displaced_step_dump_bytes (struct ui_file *file, const gdb_byte *buf, size_t len)
static int displaced_step_prepare (ptid_t ptid)
static void write_memory_ptid (ptid_t ptid, CORE_ADDR memaddr, const gdb_byte *myaddr, int len)
static void displaced_step_restore (struct displaced_step_inferior_state *displaced, ptid_t ptid)
static void displaced_step_fixup (ptid_t event_ptid, enum gdb_signal signal)
static void infrun_thread_ptid_changed (ptid_t old_ptid, ptid_t new_ptid)
static void show_scheduler_mode (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static int maybe_software_singlestep (struct gdbarch *gdbarch, CORE_ADDR pc)
ptid_t user_visible_resume_ptid (int step)
void resume (int step, enum gdb_signal sig)
static void clear_proceed_status_thread (struct thread_info *tp)
static int clear_proceed_status_callback (struct thread_info *tp, void *data)
void clear_proceed_status (void)
void proceed (CORE_ADDR addr, enum gdb_signal siggnal, int step)
void start_remote (int from_tty)
void init_wait_for_inferior (void)
static void handle_inferior_event (struct execution_control_state *ecs)
static void handle_step_into_function (struct gdbarch *gdbarch, struct execution_control_state *ecs)
static void handle_step_into_function_backward (struct gdbarch *gdbarch, struct execution_control_state *ecs)
static void check_exception_resume (struct execution_control_state *, struct frame_info *)
static void stop_stepping (struct execution_control_state *ecs)
static void prepare_to_wait (struct execution_control_state *ecs)
static void keep_going (struct execution_control_state *ecs)
static int infrun_thread_stop_requested_callback (struct thread_info *info, void *arg)
static void infrun_thread_stop_requested (ptid_t ptid)
static void infrun_thread_thread_exit (struct thread_info *tp, int silent)
static int delete_step_resume_breakpoint_callback (struct thread_info *info, void *data)
static void delete_step_thread_step_resume_breakpoint (void)
static void delete_step_thread_step_resume_breakpoint_cleanup (void *arg)
static void print_target_wait_results (ptid_t waiton_ptid, ptid_t result_ptid, const struct target_waitstatus *ws)
void prepare_for_detach (void)
void wait_for_inferior (void)
void fetch_inferior_event (void *client_data)
void set_step_info (struct frame_info *frame, struct symtab_and_line sal)
void get_last_target_status (ptid_t *ptidp, struct target_waitstatus *status)
static void adjust_pc_after_break (struct execution_control_state *ecs)
static int stepped_in_from (struct frame_info *frame, struct frame_id step_frame_id)
static int handle_syscall_event (struct execution_control_state *ecs)
static void clear_stop_func (struct execution_control_state *ecs)
static void fill_in_stop_func (struct gdbarch *gdbarch, struct execution_control_state *ecs)
static void insert_step_resume_breakpoint_at_sal_1 (struct gdbarch *gdbarch, struct symtab_and_line sr_sal, struct frame_id sr_id, enum bptype sr_type)
void insert_step_resume_breakpoint_at_sal (struct gdbarch *gdbarch, struct symtab_and_line sr_sal, struct frame_id sr_id)
static void insert_exception_resume_breakpoint (struct thread_info *tp, struct block *b, struct frame_info *frame, struct symbol *sym)
static void insert_exception_resume_from_probe (struct thread_info *tp, const struct probe *probe, struct frame_info *frame)
void normal_stop (void)
int signal_stop_state (int signo)
int signal_print_state (int signo)
int signal_pass_state (int signo)
static void signal_cache_update (int signo)
int signal_stop_update (int signo, int state)
int signal_print_update (int signo, int state)
int signal_pass_update (int signo, int state)
void signal_catch_update (const unsigned int *info)
static VEC (char_ptr)
enum gdb_signal gdb_signal_from_command (int num)
static void validate_siginfo_access (void)
static void siginfo_value_read (struct value *v)
static void siginfo_value_write (struct value *v, struct value *fromval)
static struct value * siginfo_make_value (struct gdbarch *gdbarch, struct internalvar *var, void *ignore)
struct infcall_suspend_state * save_infcall_suspend_state (void)
void restore_infcall_suspend_state (struct infcall_suspend_state *inf_state)
static void do_restore_infcall_suspend_state_cleanup (void *state)
struct cleanup * make_cleanup_restore_infcall_suspend_state (struct infcall_suspend_state *inf_state)
void discard_infcall_suspend_state (struct infcall_suspend_state *inf_state)
struct regcache * get_infcall_suspend_state_regcache (struct infcall_suspend_state *inf_state)
struct infcall_control_state * save_infcall_control_state (void)
void restore_infcall_control_state (struct infcall_control_state *inf_status)
static void do_restore_infcall_control_state_cleanup (void *sts)
struct cleanup * make_cleanup_restore_infcall_control_state (struct infcall_control_state *inf_status)
void discard_infcall_control_state (struct infcall_control_state *inf_status)
int ptid_match (ptid_t ptid, ptid_t filter)
static void restore_inferior_ptid (void *arg)
struct cleanup * save_inferior_ptid (void)
void clear_exit_convenience_vars (void)
static void set_exec_direction_func (char *args, int from_tty, struct cmd_list_element *cmd)
static void show_exec_direction_func (struct ui_file *out, int from_tty, struct cmd_list_element *cmd, const char *value)
static void show_schedule_multiple (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
Variables
int step_stop_if_no_debug = 0
int sync_execution = 0
static ptid_t previous_inferior_ptid
static int detach_fork = 1
int debug_displaced = 0
unsigned int debug_infrun = 0
int disable_randomization = 1
int non_stop = 0
static int non_stop_1 = 0
int observer_mode = 0
static int observer_mode_1 = 0
static unsigned char * signal_stop
static unsigned char * signal_print
static unsigned char * signal_program
static unsigned char * signal_catch
static unsigned char * signal_pass
static struct cmd_list_element * stop_command
static struct symbol * step_start_function
int stop_on_solib_events
int stop_after_trap
struct regcache * stop_registers
static int stop_print_frame
static ptid_t target_last_wait_ptid
static struct target_waitstatus target_last_waitstatus
static const char follow_fork_mode_child [] = "child"
static const char follow_fork_mode_parent [] = "parent"
static const char *const follow_fork_mode_kind_names []
static const char * follow_fork_mode_string = follow_fork_mode_parent
static const char follow_exec_mode_new [] = "new"
static const char follow_exec_mode_same [] = "same"
static const char *const follow_exec_mode_names []
static const char * follow_exec_mode_string = follow_exec_mode_same
static int singlestep_breakpoints_inserted_p = 0
static ptid_t singlestep_ptid
static CORE_ADDR singlestep_pc
static ptid_t saved_singlestep_ptid
static int stepping_past_singlestep_breakpoint
static ptid_t deferred_step_ptid
static struct
displaced_step_inferior_state * displaced_step_inferior_states
static enum auto_boolean can_use_displaced_stepping = AUTO_BOOLEAN_AUTO
static const char schedlock_off [] = "off"
static const char schedlock_on [] = "on"
static const char schedlock_step [] = "step"
static const char *const scheduler_enums []
static const char * scheduler_mode = schedlock_off
int sched_multi = 0
ptid_t waiton_ptid
static enum infwait_states infwait_state
static struct lval_funcs siginfo_value_funcs
int execution_direction = EXEC_FORWARD
static const char exec_forward [] = "forward"
static const char exec_reverse [] = "reverse"
static const char * exec_direction = exec_forward
static const char *const exec_direction_names []
static struct internalvar_funcs siginfo_funcs
Define Documentation
#define RESUME_ALL minus_one_ptid
Definition at line 335 of file infrun.c.
Referenced by user_visible_resume_ptid().
#define SET_SIGS (nsigs, sigs, flags)
Value:
do { \
    int signum = (nsigs); \
    while (signum-- > 0) \
      if ((sigs)[signum]) \
        (flags)[signum] = 1; \
  } while (0)
Definition at line 308 of file infrun.c.
Referenced by handle_command().
#define UNSET_SIGS (nsigs, sigs, flags)
Value:
do { \
    int signum = (nsigs); \
    while (signum-- > 0) \
      if ((sigs)[signum]) \
        (flags)[signum] = 0; \
  } while (0)
Definition at line 316 of file infrun.c.
Referenced by handle_command().
Enumeration Type Documentation
enum infwait_states
Enumerator:
infwait_normal_state
infwait_thread_hop_state
infwait_step_watch_state
infwait_nonstep_watch_state
Definition at line 2396 of file infrun.c.
Function Documentation
void _initialize_infrun (void)
static struct displaced_step_inferior_state* add_displaced_stepping_state (int pid) [static, read]
Definition at line 1140 of file infrun.c.
References displaced_step_inferior_states, displaced_step_inferior_state::next, displaced_step_inferior_state::pid, and xcalloc().
Referenced by displaced_step_prepare().
static void adjust_pc_after_break (struct execution_control_state * ecs) [static]
Definition at line 2928 of file infrun.c.
References currently_stepping(), do_cleanups(), execution_control_state::event_thread, EXEC_REVERSE, execution_direction, gdbarch_decr_pc_after_break(), get_regcache_arch(), get_regcache_aspace(), get_thread_regcache(), inferior_ptid, target_waitstatus::kind, make_cleanup(), moribund_breakpoint_here_p(), non_stop, null_cleanup(), thread_info::prev_pc, execution_control_state::ptid, ptid_equal(), record_full_gdb_operation_disable_set(), RECORD_IS_USED, regcache_read_pc(), regcache_write_pc(), target_waitstatus::sig, singlestep_breakpoints_inserted_p, software_breakpoint_inserted_here_p(), TARGET_WAITKIND_STOPPED, target_waitstatus::value, and execution_control_state::ws.
Referenced by handle_inferior_event().
static void check_exception_resume (struct execution_control_state * ecs, struct frame_info * frame) [static]
Definition at line 5641 of file infrun.c.
References ALL_BLOCK_SYMBOLS, execution_control_state::event_thread, find_probe_by_pc(), func, get_frame_function(), get_frame_pc(), insert_exception_resume_breakpoint(), insert_exception_resume_from_probe(), RETURN_MASK_ERROR, SYMBOL_BLOCK_VALUE, SYMBOL_IS_ARGUMENT, and TRY_CATCH.
Referenced by handle_inferior_event().
void clear_exit_convenience_vars (void)
Definition at line 7098 of file infrun.c.
References clear_internalvar(), and lookup_internalvar().
Referenced by core_open(), and handle_inferior_event().
void clear_proceed_status (void)
Definition at line 2015 of file infrun.c.
References clear_proceed_status_callback(), clear_proceed_status_thread(), inferior::control, current_inferior(), inferior_ptid, inferior_thread(), iterate_over_threads(), NO_STOP_QUIETLY, non_stop, null_ptid, observer_notify_about_to_proceed(), ptid_equal(), regcache_xfree(), stop_after_trap, and inferior_control_state::stop_soon.
Referenced by attach_command(), attach_command_post_wait(), continue_1(), do_initial_windows_stuff(), finish_command(), gdbsim_create_inferior(), go32_create_inferior(), init_wait_for_inferior(), irix_solib_create_inferior_hook(), jump_command(), m32r_create_inferior(), monitor_create_inferior(), osf_solib_create_inferior_hook(), proceed_after_attach_callback(), proceed_after_vfork_done(), proceed_thread(), proceed_thread_callback(), run_inferior_call(), signal_command(), step_once(), until_break_command(), and until_next_command().
static int clear_proceed_status_callback (struct thread_info * tp, void * data) [static]
Definition at line 2005 of file infrun.c.
References clear_proceed_status_thread(), is_exited(), and thread_info::ptid.
Referenced by clear_proceed_status().
static void clear_proceed_status_thread (struct thread_info * tp) [static]
Definition at line 1980 of file infrun.c.
References bpstat_clear(), thread_info::control, debug_infrun, fprintf_unfiltered(), gdb_stdlog, thread_control_state::may_range_step, null_frame_id, thread_control_state::proceed_to_finish, thread_info::ptid, thread_control_state::step_frame_id, thread_control_state::step_over_calls, STEP_OVER_UNDEBUGGABLE, thread_control_state::step_range_end, thread_control_state::step_range_start, thread_control_state::step_stack_frame_id, thread_control_state::stop_bpstat, thread_info::stop_requested, thread_control_state::stop_step, target_pid_to_str(), and thread_control_state::trap_expected.
Referenced by clear_proceed_status(), and clear_proceed_status_callback().
static void clear_stop_func (struct execution_control_state * ecs) [static]
Definition at line 3124 of file infrun.c.
References execution_control_state::stop_func_end, execution_control_state::stop_func_filled_in, execution_control_state::stop_func_name, and execution_control_state::stop_func_start.
Referenced by handle_inferior_event().
static void context_switch (ptid_t ptid) [static]
Definition at line 2914 of file infrun.c.
References debug_infrun, fprintf_unfiltered(), gdb_stdlog, inferior_ptid, ptid_equal(), switch_to_thread(), and target_pid_to_str().
Referenced by displaced_step_fixup(), handle_inferior_event(), and handle_syscall_event().
static int currently_stepping (struct thread_info * tp) [static]
Definition at line 5300 of file infrun.c.
References bpstat_should_step(), thread_info::control, thread_control_state::step_range_end, thread_control_state::step_resume_breakpoint, and thread_control_state::trap_expected.
Referenced by adjust_pc_after_break(), displaced_step_fixup(), handle_inferior_event(), and keep_going().
static int currently_stepping_or_nexting_callback (struct thread_info * tp, void * data) [static]
Definition at line 5312 of file infrun.c.
References thread_info::control, thread_control_state::step_range_end, and thread_control_state::trap_expected.
Referenced by handle_inferior_event().
static int delete_step_resume_breakpoint_callback (struct thread_info * info, void * data) [static]
Definition at line 2547 of file infrun.c.
References delete_exception_resume_breakpoint(), delete_step_resume_breakpoint(), is_exited(), and thread_info::ptid.
Referenced by delete_step_thread_step_resume_breakpoint().
static void delete_step_thread_step_resume_breakpoint (void) [static]
Definition at line 2562 of file infrun.c.
References delete_exception_resume_breakpoint(), delete_step_resume_breakpoint(), delete_step_resume_breakpoint_callback(), inferior_ptid, inferior_thread(), iterate_over_threads(), non_stop, null_ptid, ptid_equal(), and target_has_execution.
Referenced by delete_step_thread_step_resume_breakpoint_cleanup(), and fetch_inferior_event().
static void delete_step_thread_step_resume_breakpoint_cleanup (void * arg) [static]
Definition at line 2589 of file infrun.c.
References delete_step_thread_step_resume_breakpoint().
Referenced by wait_for_inferior().
void discard_infcall_control_state (struct infcall_control_state * inf_status)
Definition at line 7038 of file infrun.c.
References bpstat_clear(), disp_del_at_next_stop, breakpoint::disposition, thread_control_state::exception_resume_breakpoint, thread_control_state::step_resume_breakpoint, thread_control_state::stop_bpstat, infcall_control_state::thread_control, and xfree().
Referenced by call_function_by_hand().
void discard_infcall_suspend_state (struct infcall_suspend_state * inf_state)
Definition at line 6897 of file infrun.c.
References regcache_xfree(), infcall_suspend_state::registers, infcall_suspend_state::siginfo_data, and xfree().
Referenced by remove_dummy_frame(), and restore_infcall_suspend_state().
static void displaced_step_clear (struct displaced_step_inferior_state * displaced) [static]
Definition at line 1247 of file infrun.c.
References gdbarch_displaced_step_free_closure(), null_ptid, displaced_step_inferior_state::step_closure, displaced_step_inferior_state::step_gdbarch, and displaced_step_inferior_state::step_ptid.
Referenced by displaced_step_clear_cleanup(), and displaced_step_prepare().
static void displaced_step_clear_cleanup (void * arg) [static]
Definition at line 1261 of file infrun.c.
References displaced_step_clear().
Referenced by displaced_step_fixup(), and displaced_step_prepare().
void displaced_step_dump_bytes (struct ui_file * file, const gdb_byte * buf, size_t len)
Definition at line 1270 of file infrun.c.
References fprintf_unfiltered(), fputs_unfiltered(), and len.
Referenced by amd64_displaced_step_copy_insn(), displaced_step_fixup(), displaced_step_prepare(), i386_displaced_step_copy_insn(), resume(), and simple_displaced_step_copy_insn().
static void displaced_step_fixup (ptid_t event_ptid, enum gdb_signal signal) [static]
Definition at line 1447 of file infrun.c.
References breakpoint_here_p(), context_switch(), thread_info::control, currently_stepping(), debug_displaced, displaced_step_clear_cleanup(), displaced_step_dump_bytes(), displaced_step_prepare(), displaced_step_restore(), do_cleanups(), fprintf_unfiltered(), gdb_stdlog, gdbarch_displaced_step_fixup(), gdbarch_displaced_step_hw_singlestep(), get_displaced_stepping_state(), get_regcache_arch(), get_regcache_aspace(), get_thread_regcache(), inferior_thread(), make_cleanup(), displaced_step_request::next, null_ptid, paddress(), thread_info::ptid, displaced_step_request::ptid, ptid_equal(), ptid_get_pid(), read_memory(), regcache_read_pc(), regcache_write_pc(), displaced_step_inferior_state::step_closure, displaced_step_inferior_state::step_copy, displaced_step_inferior_state::step_gdbarch, displaced_step_inferior_state::step_original, displaced_step_inferior_state::step_ptid, displaced_step_inferior_state::step_request_queue, thread_suspend_state::stop_signal, thread_info::suspend, target_pid_to_str(), target_resume(), thread_control_state::trap_expected, and xfree().
Referenced by handle_inferior_event(), and set_gdbarch_displaced_step_fixup().
static int displaced_step_prepare (ptid_t ptid) [static]
Definition at line 1296 of file infrun.c.
References _, add_displaced_stepping_state(), thread_info::control, debug_displaced, discard_cleanups(), displaced_step_clear(), displaced_step_clear_cleanup(), displaced_step_dump_bytes(), do_cleanups(), find_thread_ptid(), fprintf_unfiltered(), free_current_contents(), gdb_assert, gdb_stdlog, gdbarch_displaced_step_copy_insn(), gdbarch_displaced_step_copy_insn_p(), gdbarch_displaced_step_location(), gdbarch_max_insn_length(), get_regcache_arch(), get_thread_regcache(), inferior_ptid, len, make_cleanup(), thread_control_state::may_range_step, MEMORY_ERROR, displaced_step_request::next, null_ptid, paddress(), displaced_step_request::ptid, ptid_equal(), ptid_get_pid(), regcache_read_pc(), regcache_write_pc(), safe_strerror(), save_inferior_ptid(), exsummary::status, displaced_step_inferior_state::step_closure, displaced_step_inferior_state::step_copy, displaced_step_inferior_state::step_gdbarch, displaced_step_inferior_state::step_original, displaced_step_inferior_state::step_ptid, displaced_step_inferior_state::step_request_queue, displaced_step_inferior_state::step_saved_copy, target_pid_to_str(), target_read_memory(), throw_error(), ULONGEST, and xmalloc().
Referenced by displaced_step_fixup(), and resume().
static void displaced_step_restore (struct displaced_step_inferior_state * displaced, ptid_t ptid) [static]
Definition at line 1432 of file infrun.c.
References debug_displaced, fprintf_unfiltered(), gdb_stdlog, gdbarch_max_insn_length(), len, paddress(), displaced_step_inferior_state::step_copy, displaced_step_inferior_state::step_gdbarch, displaced_step_inferior_state::step_saved_copy, target_pid_to_str(), ULONGEST, and write_memory_ptid().
Referenced by displaced_step_fixup(), and handle_inferior_event().
static void do_restore_infcall_control_state_cleanup (void * sts) [static]
Definition at line 7025 of file infrun.c.
References restore_infcall_control_state().
Referenced by make_cleanup_restore_infcall_control_state().
static void do_restore_infcall_suspend_state_cleanup (void * state) [static]
Definition at line 6884 of file infrun.c.
References restore_infcall_suspend_state().
Referenced by make_cleanup_restore_infcall_suspend_state().
void fetch_inferior_event (void * client_data)
Definition at line 2770 of file infrun.c.
References _, thread_info::control, inferior::control, debug_infrun, delete_step_thread_step_resume_breakpoint(), deprecated_target_wait_hook, discard_cleanups(), display_gdb_prompt(), do_cleanups(), execution_control_state::event_thread, exec_done_display_p, execution_direction, find_inferior_pid(), finish_thread_state_cleanup(), handle_inferior_event(), INF_EXEC_COMPLETE, INF_EXEC_CONTINUE, inferior_event_handler(), inferior_ptid, interpreter_async, is_running(), target_waitstatus::kind, make_bpstat_clear_actions_cleanup(), make_cleanup(), make_cleanup_restore_current_thread(), make_cleanup_restore_current_traceframe(), make_cleanup_restore_integer(), memset(), minus_one_ptid, NO_STOP_QUIETLY, non_stop, normal_stop(), null_cleanup(), null_ptid, overlay_cache_invalid, print_target_wait_results(), printf_unfiltered(), execution_control_state::ptid, ptid_equal(), ptid_get_pid(), set_current_traceframe(), thread_info::step_multi, inferior_control_state::stop_soon, thread_control_state::stop_step, sync_execution, target_execution_direction, target_has_execution, target_wait(), TARGET_WAITKIND_EXITED, TARGET_WAITKIND_NO_RESUMED, TARGET_WAITKIND_SIGNALLED, TARGET_WNOHANG, execution_control_state::wait_some_more, and execution_control_state::ws.
Referenced by fetch_inferior_event_wrapper().
static void fill_in_stop_func (struct gdbarch * gdbarch, struct execution_control_state * ecs) [static]
Definition at line 3135 of file infrun.c.
References find_pc_partial_function(), gdbarch_deprecated_function_start_offset(), execution_control_state::stop_func_end, execution_control_state::stop_func_filled_in, execution_control_state::stop_func_name, execution_control_state::stop_func_start, and stop_pc.
Referenced by handle_inferior_event(), handle_step_into_function(), and handle_step_into_function_backward().
static void follow_exec (ptid_t pid, char * execd_pathname) [static]
Definition at line 816 of file infrun.c.
References _, add_inferior(), add_program_space(), program_space::aspace, inferior::aspace, breakpoint_init_inferior(), breakpoint_re_set(), thread_info::control, current_inferior(), current_program_space, thread_control_state::exception_resume_breakpoint, exec_file_attach(), exit_inferior_num_silent(), follow_exec_mode_new, follow_exec_mode_string, gdb_assert, gdb_flush(), gdb_stdout, gdb_sysroot, inf_execd, inferior_ptid, inferior_thread(), insert_breakpoints(), jit_inferior_created_hook(), mark_breakpoints_out(), maybe_new_address_space(), name, no_shared_libraries(), program_space::num, printf_unfiltered(), inferior::pspace, set_current_inferior(), set_current_program_space(), set_initial_language(), solib_create_inferior_hook(), thread_control_state::step_range_end, thread_control_state::step_range_start, thread_control_state::step_resume_breakpoint, thread_info::stop_requested, symbol_file_add(), SYMFILE_DEFER_BP_RESET, inferior::symfile_flags, SYMFILE_MAINLINE, SYMFILE_NO_READ, target_clear_description(), target_find_description(), target_pid_to_str(), and update_breakpoints_after_exec().
Referenced by handle_inferior_event().
static int follow_fork (void) [static]
Definition at line 420 of file infrun.c.
References _, clone_momentary_breakpoint(), thread_info::control, delete_exception_resume_breakpoint(), delete_step_resume_breakpoint(), detach_fork, thread_control_state::exception_resume_breakpoint, find_thread_ptid(), follow_fork_mode_child, follow_fork_mode_string, follow_inferior_reset_breakpoints(), get_last_target_status(), inferior_ptid, inferior_thread(), internal_error(), target_waitstatus::kind, minus_one_ptid, non_stop, null_frame_id, nullify_last_target_wait_ptid(), thread_info::pending_follow, ptid_equal(), target_waitstatus::related_pid, thread_control_state::step_frame_id, thread_control_state::step_range_end, thread_control_state::step_range_start, thread_control_state::step_resume_breakpoint, switch_to_thread(), target_follow_fork(), TARGET_WAITKIND_FORKED, TARGET_WAITKIND_SPURIOUS, TARGET_WAITKIND_VFORKED, target_waitstatus::value, and warning().
Referenced by handle_inferior_event(), and proceed().
void follow_inferior_reset_breakpoints (void)
Definition at line 576 of file infrun.c.
References breakpoint_re_set(), breakpoint_re_set_thread(), thread_info::control, thread_control_state::exception_resume_breakpoint, inferior_thread(), insert_breakpoints(), and thread_control_state::step_resume_breakpoint.
Referenced by follow_fork().
enum gdb_signal gdb_signal_from_command (int num)
Definition at line 6615 of file infrun.c.
References _, and error().
Referenced by handle_command(), signal_command(), signals_info(), and VEC().
struct displaced_step_closure* get_displaced_step_closure_by_addr (CORE_ADDR addr) [read]
Definition at line 1163 of file infrun.c.
References get_displaced_stepping_state(), inferior_ptid, null_ptid, ptid_equal(), ptid_get_pid(), displaced_step_inferior_state::step_closure, displaced_step_inferior_state::step_copy, and displaced_step_inferior_state::step_ptid.
Referenced by arm_pc_is_thumb().
static struct displaced_step_inferior_state* get_displaced_stepping_state (int pid) [static, read]
Definition at line 1122 of file infrun.c.
References displaced_step_inferior_state::next, and displaced_step_inferior_state::pid.
Referenced by displaced_step_fixup(), get_displaced_step_closure_by_addr(), handle_inferior_event(), prepare_for_detach(), and resume().
struct regcache* get_infcall_suspend_state_regcache (struct infcall_suspend_state * inf_state) [read]
Definition at line 6905 of file infrun.c.
References infcall_suspend_state::registers.
Referenced by dummy_frame_sniffer().
void get_last_target_status (ptid_t * ptidp, struct target_waitstatus * status)
Definition at line 2899 of file infrun.c.
References target_last_wait_ptid, and target_last_waitstatus.
Referenced by checkpoint_command(), continue_command(), follow_fork(), get_pending_status(), linux_nat_kill(), mi_on_normal_stop(), normal_stop(), prepare_to_proceed(), print_it_catch_syscall(), proc_set_current_signal(), proceed(), program_info(), and signal_catchpoint_print_it().
static void handle_command (char * args, int from_tty) [static]
Definition at line 6338 of file infrun.c.
References _, do_cleanups(), error(), error_no_arg(), gdb_buildargv(), gdb_flush(), gdb_signal_from_command(), gdb_signal_from_name(), gdb_signal_to_name(), gdb_stdout, int, make_cleanup_freeargv(), memset(), printf_unfiltered(), query(), SET_SIGS, sig_print_header(), sig_print_info(), signal_cache_update(), signal_pass, signal_print, signal_program, signal_stop, target_pass_signals(), target_program_signals(), and UNSET_SIGS.
Referenced by xdb_handle_command().
static void handle_inferior_event (struct execution_control_state * ecs) [static]
Definition at line 3156 of file infrun.c.
References _, add_thread(), adjust_pc_after_break(), inferior::aspace, bpstat_causes_stop(), bpstat_clear(), bpstat_explains_signal(), BPSTAT_SIGNAL_HIDE, BPSTAT_SIGNAL_NO, bpstat_stop_status(), bpstat_what(), BPSTAT_WHAT_CLEAR_LONGJMP_RESUME, BPSTAT_WHAT_HP_STEP_RESUME, BPSTAT_WHAT_KEEP_CHECKING, BPSTAT_WHAT_SET_LONGJMP_RESUME, BPSTAT_WHAT_SINGLE, BPSTAT_WHAT_STEP_RESUME, BPSTAT_WHAT_STOP_NOISY, BPSTAT_WHAT_STOP_SILENT, breakpoint_inserted_here_p(), breakpoint_retire_moribund(), breakpoint_thread_match(), breakpoints_always_inserted_mode(), program_space::breakpoints_not_allowed, cancel_single_step_breakpoints(), check_exception_resume(), check_longjmp_breakpoint_for_call_dummy(), clear_exit_convenience_vars(), clear_stop_func(), context_switch(), thread_info::control, inferior::control, current_inferior(), thread_info::current_line, thread_info::current_symtab, current_target, currently_stepping(), currently_stepping_or_nexting_callback(), debug_displaced, debug_infrun, delete_exception_resume_breakpoint(), delete_step_resume_breakpoint(), delete_thread(), deprecated_context_hook, detach_breakpoints(), detach_fork, inferior::detaching, displaced_step_fixup(), displaced_step_restore(), do_cleanups(), symtab_and_line::end, error(), execution_control_state::event_thread, thread_control_state::exception_resume_breakpoint, EXEC_REVERSE, target_waitstatus::execd_pathname, execution_direction, inferior::exit_code, fill_in_stop_func(), find_frame_sal(), find_inferior_pid(), find_pc_function(), find_pc_line(), find_pc_overlay(), find_thread_ptid(), follow_exec(), follow_fork(), follow_fork_mode_child, follow_fork_mode_string, fprintf_filtered(), fprintf_unfiltered(), frame_find_by_id(), frame_id_eq(), frame_id_p(), frame_unwind_caller_id(), function_name_is_marked_for_skip(), gdb_assert, gdb_flush(), gdb_stdlog, gdb_stdout, gdbarch_gdb_signal_to_target(), gdbarch_gdb_signal_to_target_p(), gdbarch_get_longjmp_target(), gdbarch_get_longjmp_target_p(), gdbarch_have_nonsteppable_watchpoint(), gdbarch_in_solib_return_trampoline(), gdbarch_single_step_through_delay(), gdbarch_single_step_through_delay_p(), gdbarch_skip_solib_resolver(), gdbarch_skip_trampoline_code(), get_current_frame(), get_current_regcache(), get_displaced_stepping_state(), get_frame_arch(), get_frame_id(), get_frame_program_space(), get_frame_type(), get_regcache_arch(), get_regcache_aspace(), get_stack_frame_id(), get_thread_arch_aspace_regcache(), get_thread_regcache(), handle_solib_event(), handle_step_into_function(), handle_step_into_function_backward(), handle_syscall_event(), handle_vfork_child_exec_or_exit(), inferior::has_exit_code, in_prologue(), in_solib_dynsym_resolve_code(), in_thread_list(), inferior_ptid, inferior_thread(), infwait_nonstep_watch_state, infwait_normal_state, infwait_state, infwait_step_watch_state, infwait_thread_hop_state, init_sal(), thread_info::initiating_frame, INLINE_FRAME, inline_skipped_frames(), insert_breakpoints(), insert_hp_step_resume_breakpoint_at_frame(), insert_longjmp_resume_breakpoint(), insert_step_resume_breakpoint_at_caller(), insert_step_resume_breakpoint_at_sal(), target_waitstatus::integer, internal_error(), is_exited(), iterate_over_threads(), keep_going(), target_waitstatus::kind, symtab_and_line::line, LONGEST, lookup_internalvar(), thread_control_state::may_range_step, maybe_software_singlestep(), minus_one_ptid, NO_STOP_QUIETLY, non_stop, null_frame_id, null_ptid, thread_info::num, outer_frame_id, paddress(), symtab_and_line::pc, pc_at_non_inline_function(), pc_in_thread_step_range(), thread_info::pending_follow, pid_to_ptid(), pid_to_thread_id(), prepare_to_wait(), thread_info::prev_pc, print_end_stepping_range_reason(), print_exited_reason(), print_no_history_reason(), print_signal_exited_reason(), print_signal_received_reason(), probe_safe_evaluate_at_pc(), thread_control_state::proceed_to_finish, inferior::pspace, symtab_and_line::pspace, thread_info::ptid, execution_control_state::ptid, ptid_equal(), ptid_get_pid(), execution_control_state::random_signal, regcache_read_pc(), regcache_write_pc(), regular_breakpoint_inserted_here_p(), reinit_frame_cache(), target_waitstatus::related_pid, remove_breakpoints(), remove_single_step_breakpoints(), resume(), save_inferior_ptid(), symtab_and_line::section, set_current_inferior(), set_current_program_space(), set_executing(), set_internalvar_integer(), set_step_info(), target_waitstatus::sig, signal_print, signal_program, signal_stop_state(), SIGTRAMP_FRAME, singlestep_breakpoints_inserted_p, singlestep_pc, singlestep_ptid, skip_inline_frames(), skip_language_trampoline(), thread_info::step_after_step_resume_breakpoint, thread_control_state::step_frame_id, step_into_inline_frame(), STEP_OVER_ALL, thread_control_state::step_over_calls, STEP_OVER_NONE, STEP_OVER_UNDEBUGGABLE, displaced_step_inferior_state::step_ptid, thread_control_state::step_range_end, thread_control_state::step_range_start, thread_control_state::step_resume_breakpoint, thread_control_state::step_stack_frame_id, step_stop_if_no_debug, stepped_in_from(), thread_info::stepping_over_breakpoint, stepping_past_singlestep_breakpoint, stop_after_trap, thread_control_state::stop_bpstat, execution_control_state::stop_func_name, execution_control_state::stop_func_start, STOP_NONE, stop_on_solib_events, stop_pc, stop_print_frame, STOP_QUIETLY, STOP_QUIETLY_NO_SIGSTOP, STOP_QUIETLY_REMOTE, thread_info::stop_requested, thread_suspend_state::stop_signal, inferior_control_state::stop_soon, stop_stack_dummy, thread_control_state::stop_step, stop_stepping(), stopped_by_random_signal, thread_info::suspend, switch_to_thread(), symtab_and_line::symtab, sync_execution, target_can_async_p, target_have_steppable_watchpoint, target_last_waitstatus, target_mourn_inferior(), target_pass_signals(), target_pid_to_str(), target_resume(), target_stopped_by_watchpoint, target_stopped_data_address, target_terminal_inferior(), target_terminal_ours, target_terminal_ours_for_output, target_thread_alive(), TARGET_WAITKIND_EXECD, TARGET_WAITKIND_EXITED, TARGET_WAITKIND_FORKED, TARGET_WAITKIND_IGNORE, TARGET_WAITKIND_LOADED, TARGET_WAITKIND_NO_HISTORY, TARGET_WAITKIND_NO_RESUMED, TARGET_WAITKIND_SIGNALLED, TARGET_WAITKIND_SPURIOUS, TARGET_WAITKIND_STOPPED, TARGET_WAITKIND_SYSCALL_ENTRY, TARGET_WAITKIND_SYSCALL_RETURN, TARGET_WAITKIND_VFORK_DONE, TARGET_WAITKIND_VFORKED, thread_control_state::trap_expected, use_displaced_stepping(), target_waitstatus::value, value_as_address(), inferior::waiting_for_vfork_done, watchpoints_triggered(), execution_control_state::ws, and xfree().
Referenced by fetch_inferior_event(), infrun_thread_stop_requested_callback(), prepare_for_detach(), and wait_for_inferior().
static void handle_step_into_function (struct gdbarch * gdbarch, struct execution_control_state * ecs) [static]
Definition at line 5326 of file infrun.c.
References thread_info::control, symtab_and_line::end, execution_control_state::event_thread, fill_in_stop_func(), find_pc_line(), find_pc_overlay(), find_pc_symtab(), gdbarch_adjust_breakpoint_address(), gdbarch_adjust_breakpoint_address_p(), gdbarch_skip_prologue(), get_current_frame(), get_frame_program_space(), init_sal(), insert_step_resume_breakpoint_at_sal(), keep_going(), symtab::language, language_asm, null_frame_id, symtab_and_line::pc, print_end_stepping_range_reason(), symtab_and_line::pspace, symtab_and_line::section, thread_control_state::step_range_end, thread_control_state::step_range_start, execution_control_state::stop_func_end, execution_control_state::stop_func_start, stop_pc, thread_control_state::stop_step, and stop_stepping().
Referenced by handle_inferior_event().
static void handle_step_into_function_backward (struct gdbarch * gdbarch, struct execution_control_state * ecs) [static]
Definition at line 5407 of file infrun.c.
References thread_info::control, symtab_and_line::end, execution_control_state::event_thread, fill_in_stop_func(), find_pc_line(), find_pc_symtab(), gdbarch_skip_prologue(), keep_going(), symtab::language, language_asm, symtab_and_line::pc, print_end_stepping_range_reason(), thread_control_state::step_range_end, thread_control_state::step_range_start, execution_control_state::stop_func_start, stop_pc, thread_control_state::stop_step, and stop_stepping().
Referenced by handle_inferior_event().
static int handle_syscall_event (struct execution_control_state * ecs) [static]
Definition at line 3078 of file infrun.c.
References bpstat_explains_signal(), BPSTAT_SIGNAL_NO, bpstat_stop_status(), catch_syscall_enabled(), catching_syscall_number(), context_switch(), thread_info::control, debug_infrun, execution_control_state::event_thread, fprintf_unfiltered(), gdb_stdlog, get_regcache_aspace(), get_thread_regcache(), inferior_ptid, keep_going(), execution_control_state::ptid, ptid_equal(), execution_control_state::random_signal, regcache_read_pc(), thread_control_state::stop_bpstat, stop_pc, thread_suspend_state::stop_signal, thread_info::suspend, target_waitstatus::syscall_number, target_waitstatus::value, and execution_control_state::ws.
Referenced by handle_inferior_event().
static void handle_vfork_child_exec_or_exit (int exec) [static]
Definition at line 638 of file infrun.c.
References add_program_space(), any_live_thread_of_process(), program_space::aspace, inferior::aspace, clone_program_space(), current_inferior(), current_program_space, debug_infrun, do_cleanups(), fprintf_filtered(), fprintf_unfiltered(), gdb_assert, gdb_stdlog, inferior_ptid, info_verbose, iterate_over_threads(), make_cleanup_restore_current_thread(), maybe_new_address_space(), non_stop, null_ptid, inferior::pending_detach, inferior::pid, proceed_after_vfork_done(), inferior::pspace, thread_info::ptid, inferior::removable, save_current_inferior(), save_current_program_space(), save_current_space_and_thread(), save_inferior_ptid(), set_current_program_space(), switch_to_thread(), inferior::symfile_flags, SYMFILE_NO_READ, target_detach(), target_terminal_ours, inferior::vfork_child, and inferior::vfork_parent.
Referenced by handle_inferior_event().
static int hook_stop_stub (void * cmd) [static]
Definition at line 6226 of file infrun.c.
References execute_cmd_pre_hook().
Referenced by normal_stop().
static void infrun_inferior_exit (struct inferior * inf) [static]
Definition at line 1202 of file infrun.c.
References inferior::pid, and remove_displaced_stepping_state().
static void infrun_thread_ptid_changed (ptid_t old_ptid, ptid_t new_ptid) [static]
Definition at line 1574 of file infrun.c.
References inferior_ptid, displaced_step_request::next, displaced_step_inferior_state::next, displaced_step_request::ptid, ptid_equal(), displaced_step_inferior_state::step_ptid, and displaced_step_inferior_state::step_request_queue.
static void infrun_thread_stop_requested (ptid_t ptid) [static]
Definition at line 2502 of file infrun.c.
References infrun_thread_stop_requested_callback(), iterate_over_threads(), displaced_step_request::next, displaced_step_inferior_state::next, displaced_step_request::ptid, ptid_match(), displaced_step_inferior_state::step_request_queue, and xfree().
static int infrun_thread_stop_requested_callback (struct thread_info * info, void * arg) [static]
Definition at line 2450 of file infrun.c.
References do_all_continuations_thread(), do_all_intermediate_continuations_thread(), do_cleanups(), execution_control_state::event_thread, find_thread_ptid(), handle_inferior_event(), inferior_thread(), is_executing(), is_running(), target_waitstatus::kind, make_cleanup_restore_current_thread(), memset(), minus_one_ptid, normal_stop(), thread_info::ptid, execution_control_state::ptid, ptid_equal(), ptid_get_pid(), ptid_is_pid(), target_waitstatus::sig, TARGET_WAITKIND_STOPPED, target_waitstatus::value, execution_control_state::wait_some_more, and execution_control_state::ws.
Referenced by infrun_thread_stop_requested().
static void infrun_thread_thread_exit (struct thread_info * tp, int silent) [static]
Definition at line 2538 of file infrun.c.
References nullify_last_target_wait_ptid(), thread_info::ptid, and ptid_equal().
static void init_infwait_state (void) [static]
Definition at line 3050 of file infrun.c.
References infwait_normal_state, infwait_state, and pid_to_ptid().
Referenced by init_wait_for_inferior(), and proceed().
void init_thread_stepping_state (struct thread_info * tss)
Definition at line 2887 of file infrun.c.
References thread_info::step_after_step_resume_breakpoint, and thread_info::stepping_over_breakpoint.
Referenced by proceed().
void init_wait_for_inferior (void)
Definition at line 2371 of file infrun.c.
References breakpoint_init_inferior(), clear_inline_frame_state(), clear_proceed_status(), inf_starting, inferior_ptid, init_infwait_state(), minus_one_ptid, null_ptid, and stepping_past_singlestep_breakpoint.
Referenced by attach_command(), do_initial_windows_stuff(), extended_remote_create_inferior_1(), gdbsim_create_inferior(), m32r_create_inferior(), monitor_open(), remote_start_remote(), and run_command_1().
static void insert_exception_resume_breakpoint (struct thread_info * tp, struct block * b, struct frame_info * frame, struct symbol * sym) [static]
Definition at line 5567 of file infrun.c.
References bp_exception_resume, thread_info::control, debug_infrun, thread_control_state::exception_resume_breakpoint, fprintf_unfiltered(), gdb_stdlog, get_frame_arch(), inferior_thread(), lookup_symbol(), thread_info::num, read_var_value(), RETURN_MASK_ERROR, set_momentary_breakpoint_at_pc(), SYMBOL_LINKAGE_NAME, breakpoint::thread, TRY_CATCH, value_as_address(), value_optimized_out(), and VAR_DOMAIN.
Referenced by check_exception_resume().
static void insert_exception_resume_from_probe (struct thread_info * tp, const struct probe * probe, struct frame_info * frame) [static]
Definition at line 5610 of file infrun.c.
References bp_exception_resume, thread_info::control, debug_infrun, thread_control_state::exception_resume_breakpoint, fprintf_unfiltered(), gdb_stdlog, get_frame_arch(), get_objfile_arch(), inferior_thread(), thread_info::num, probe::objfile, paddress(), probe_safe_evaluate_at_pc(), set_momentary_breakpoint_at_pc(), breakpoint::thread, and value_as_address().
Referenced by check_exception_resume().
static void insert_hp_step_resume_breakpoint_at_frame (struct frame_info * return_frame) [static]
Definition at line 5484 of file infrun.c.
References bp_hp_step_resume, find_pc_overlay(), gdb_assert, gdbarch_addr_bits_remove(), get_frame_arch(), get_frame_pc(), get_frame_program_space(), get_stack_frame_id(), init_sal(), insert_step_resume_breakpoint_at_sal_1(), symtab_and_line::pc, symtab_and_line::pspace, and symtab_and_line::section.
Referenced by handle_inferior_event(), and resume().
static void insert_longjmp_resume_breakpoint (struct gdbarch * gdbarch, CORE_ADDR pc) [static]
Definition at line 5544 of file infrun.c.
References bp_longjmp_resume, thread_info::control, debug_infrun, thread_control_state::exception_resume_breakpoint, fprintf_unfiltered(), gdb_assert, gdb_stdlog, inferior_thread(), paddress(), and set_momentary_breakpoint_at_pc().
Referenced by handle_inferior_event().
static void insert_step_resume_breakpoint_at_caller (struct frame_info * next_frame) [static]
Definition at line 5517 of file infrun.c.
References find_pc_overlay(), frame_id_p(), frame_unwind_caller_arch(), frame_unwind_caller_id(), frame_unwind_caller_pc(), frame_unwind_program_space(), gdb_assert, gdbarch_addr_bits_remove(), init_sal(), insert_step_resume_breakpoint_at_sal(), symtab_and_line::pc, symtab_and_line::pspace, and symtab_and_line::section.
Referenced by handle_inferior_event().
void insert_step_resume_breakpoint_at_sal (struct gdbarch * gdbarch, struct symtab_and_line sr_sal, struct frame_id sr_id)
Definition at line 5467 of file infrun.c.
References bp_step_resume, and insert_step_resume_breakpoint_at_sal_1().
Referenced by finish_backward(), handle_inferior_event(), handle_step_into_function(), and insert_step_resume_breakpoint_at_caller().
static void insert_step_resume_breakpoint_at_sal_1 (struct gdbarch * gdbarch, struct symtab_and_line sr_sal, struct frame_id sr_id, enum bptype sr_type) [static]
Definition at line 5446 of file infrun.c.
References bp_hp_step_resume, bp_step_resume, thread_info::control, debug_infrun, fprintf_unfiltered(), gdb_assert, gdb_stdlog, inferior_thread(), paddress(), symtab_and_line::pc, set_momentary_breakpoint(), and thread_control_state::step_resume_breakpoint.
Referenced by insert_hp_step_resume_breakpoint_at_frame(), and insert_step_resume_breakpoint_at_sal().
static void keep_going (struct execution_control_state * ecs) [static]
Definition at line 5717 of file infrun.c.
References thread_info::control, currently_stepping(), discard_cleanups(), execution_control_state::event_thread, exception_print(), gdb_stderr, get_regcache_arch(), get_thread_regcache(), insert_breakpoints(), make_cleanup(), prepare_to_wait(), thread_info::prev_pc, execution_control_state::ptid, gdb_exception::reason, regcache_read_pc(), remove_breakpoints(), resume(), resume_cleanups(), RETURN_MASK_ERROR, signal_program, thread_info::stepping_over_breakpoint, thread_suspend_state::stop_signal, stop_stepping(), thread_info::suspend, thread_control_state::trap_expected, TRY_CATCH, and use_displaced_stepping().
Referenced by handle_inferior_event(), handle_step_into_function(), handle_step_into_function_backward(), handle_syscall_event(), recursively_search_psymtabs(), and som_solib_create_inferior_hook().
struct cleanup* make_cleanup_restore_infcall_control_state (struct infcall_control_state * inf_status) [read]
Definition at line 7032 of file infrun.c.
References do_restore_infcall_control_state_cleanup(), and make_cleanup().
Referenced by call_function_by_hand().
struct cleanup* make_cleanup_restore_infcall_suspend_state (struct infcall_suspend_state * inf_state) [read]
Definition at line 6891 of file infrun.c.
References do_restore_infcall_suspend_state_cleanup(), and make_cleanup().
Referenced by call_function_by_hand().
static int maybe_software_singlestep (struct gdbarch * gdbarch, CORE_ADDR pc) [static]
Definition at line 1653 of file infrun.c.
References EXEC_FORWARD, execution_direction, gdbarch_software_single_step(), gdbarch_software_single_step_p(), get_current_frame(), inferior_ptid, singlestep_breakpoints_inserted_p, and singlestep_pc.
Referenced by handle_inferior_event(), and resume().
void normal_stop (void)
Definition at line 5969 of file infrun.c.
References _, annotate_stopped(), annotate_thread_changed(), async_enable_stdin(), batch_silent, bpstat_print(), breakpoint_auto_delete(), breakpoints_always_inserted_mode(), catch_errors(), thread_info::control, disable_current_display(), do_cleanups(), do_displays(), DUMMY_FRAME, EXEC_REVERSE, execution_direction, find_pc_function(), finish_thread_state_cleanup(), frame_id_eq(), frame_pop(), gdb_assert, get_current_frame(), get_current_regcache(), get_frame_id(), get_frame_type(), get_last_target_status(), get_selected_frame(), has_stack_frames(), hook_stop_stub(), inferior_ptid, inferior_thread(), internal_error(), target_waitstatus::kind, make_cleanup(), minus_one_ptid, non_stop, null_cleanup(), null_ptid, observer_notify_normal_stop(), PRINT_NOTHING, PRINT_SRC_AND_LOC, PRINT_SRC_ONLY, print_stack_frame(), PRINT_UNKNOWN, printf_filtered(), thread_control_state::proceed_to_finish, prune_inferiors(), ptid_equal(), regcache_dup(), regcache_xfree(), remove_breakpoints(), RETURN_MASK_ALL, select_frame(), set_current_sal_from_frame(), SRC_AND_LOC, SRC_LINE, thread_control_state::step_frame_id, thread_control_state::stop_bpstat, stop_pc, stop_print_frame, stop_stack_dummy, STOP_STACK_DUMMY, thread_control_state::stop_step, stopped_by_random_signal, sync_execution, target_can_async_p, target_has_execution, target_pid_to_str(), target_terminal_ours, target_terminal_ours_for_output, TARGET_WAITKIND_EXITED, TARGET_WAITKIND_NO_RESUMED, and TARGET_WAITKIND_SIGNALLED.
Referenced by attach_command_post_wait(), fetch_inferior_event(), infrun_thread_stop_requested_callback(), proceed(), resume_cleanups(), run_inferior_call(), start_remote(), and step_once().
void nullify_last_target_wait_ptid (void)
Definition at line 2906 of file infrun.c.
References minus_one_ptid.
Referenced by follow_fork(), fork_load_infrun_state(), and infrun_thread_thread_exit().
void prepare_for_detach (void)
Definition at line 2640 of file infrun.c.
References _, current_inferior(), debug_infrun, deprecated_target_wait_hook, inferior::detaching, discard_cleanups(), error(), finish_thread_state_cleanup(), fprintf_unfiltered(), gdb_stdlog, get_displaced_stepping_state(), handle_inferior_event(), make_cleanup(), make_cleanup_restore_integer(), memset(), minus_one_ptid, null_ptid, overlay_cache_invalid, inferior::pid, pid_to_ptid(), print_target_wait_results(), execution_control_state::ptid, ptid_equal(), displaced_step_inferior_state::step_ptid, target_wait(), execution_control_state::wait_some_more, and execution_control_state::ws.
Referenced by target_detach().
static int prepare_to_proceed (int step) [static]
Definition at line 2059 of file infrun.c.
References breakpoint_here_p(), debug_infrun, fprintf_unfiltered(), gdb_assert, gdb_stdlog, get_last_target_status(), get_regcache_aspace(), get_thread_regcache(), inferior_ptid, target_waitstatus::kind, minus_one_ptid, non_stop, ptid_equal(), ptid_get_pid(), regcache_read_pc(), sched_multi, schedlock_on, schedlock_step, scheduler_mode, target_waitstatus::sig, switch_to_thread(), target_pid_to_str(), TARGET_WAITKIND_STOPPED, and target_waitstatus::value.
Referenced by proceed().
static void prepare_to_wait (struct execution_control_state * ecs) [static]
Definition at line 5816 of file infrun.c.
References debug_infrun, fprintf_unfiltered(), gdb_stdlog, and execution_control_state::wait_some_more.
Referenced by handle_inferior_event(), and keep_going().
static void print_end_stepping_range_reason (void) [static]
Definition at line 5840 of file infrun.c.
References async_reason_lookup(), current_uiout, EXEC_ASYNC_END_STEPPING_RANGE, inferior_thread(), ui_out_field_string(), and ui_out_is_mi_like_p().
Referenced by handle_inferior_event(), handle_step_into_function(), and handle_step_into_function_backward().
static void print_exited_reason (int exitstatus) [static]
Definition at line 5877 of file infrun.c.
References annotate_exited(), async_reason_lookup(), current_inferior(), current_uiout, EXEC_ASYNC_EXITED, EXEC_ASYNC_EXITED_NORMALLY, inferior::num, inferior::pid, pid_to_ptid(), plongest(), return_child_result_value, target_pid_to_str(), ui_out_field_fmt(), ui_out_field_string(), ui_out_is_mi_like_p(), and ui_out_text().
Referenced by handle_inferior_event().
static void print_no_history_reason (void) [static]
Definition at line 5955 of file infrun.c.
References current_uiout, and ui_out_text().
Referenced by handle_inferior_event().
static void print_signal_exited_reason (enum gdb_signal siggnal) [static]
Definition at line 5852 of file infrun.c.
References annotate_signal_name(), annotate_signal_name_end(), annotate_signal_string(), annotate_signal_string_end(), annotate_signalled(), async_reason_lookup(), current_uiout, EXEC_ASYNC_EXITED_SIGNALLED, gdb_signal_to_name(), gdb_signal_to_string(), ui_out_field_string(), ui_out_is_mi_like_p(), and ui_out_text().
Referenced by handle_inferior_event().
static void print_signal_received_reason (enum gdb_signal siggnal) [static]
Definition at line 5916 of file infrun.c.
References annotate_signal(), annotate_signal_name(), annotate_signal_name_end(), annotate_signal_string(), annotate_signal_string_end(), async_reason_lookup(), current_uiout, EXEC_ASYNC_SIGNAL_RECEIVED, gdb_signal_to_name(), gdb_signal_to_string(), inferior_thread(), thread_info::num, thread_info::ptid, target_pid_to_str(), ui_out_field_fmt(), ui_out_field_string(), ui_out_is_mi_like_p(), and ui_out_text().
Referenced by handle_inferior_event().
static void print_target_wait_results (ptid_t waiton_ptid, ptid_t result_ptid, const struct target_waitstatus * ws) [static]
Definition at line 2597 of file infrun.c.
References fprintf_unfiltered(), gdb_stdlog, mem_fileopen(), ptid_get_pid(), target_pid_to_str(), target_waitstatus_to_string(), ui_file_delete(), ui_file_xstrdup(), and xfree().
Referenced by fetch_inferior_event(), prepare_for_detach(), and wait_for_inferior().
void proceed (CORE_ADDR addr, enum gdb_signal siggnal, int step)
Definition at line 2140 of file infrun.c.
References annotate_starting(), bpstat_should_step(), breakpoint_here_p(), thread_info::control, debug_infrun, EXEC_REVERSE, execution_direction, find_pc_function(), find_thread_ptid(), follow_fork(), fprintf_unfiltered(), gdb_flush(), gdb_stdlog, gdb_stdout, gdbarch_single_step_through_delay(), gdbarch_single_step_through_delay_p(), get_current_frame(), get_current_regcache(), get_last_target_status(), get_regcache_arch(), get_regcache_aspace(), INF_EXEC_COMPLETE, inferior_event_handler(), inferior_ptid, inferior_thread(), init_infwait_state(), init_thread_stepping_state(), insert_breakpoints(), minus_one_ptid, non_stop, normal_stop(), null_ptid, paddress(), prepare_to_proceed(), thread_info::prev_pc, ptid_equal(), regcache_read_pc(), regcache_write_pc(), remove_breakpoints(), resume(), signal_program, stop_after_trap, stop_pc, thread_suspend_state::stop_signal, thread_info::suspend, target_can_async_p, thread_control_state::trap_expected, use_displaced_stepping(), and wait_for_inferior().
Referenced by attach_command_post_wait(), continue_1(), finish_backward(), finish_command(), finish_forward(), jump_command(), proceed_after_attach_callback(), proceed_after_vfork_done(), proceed_thread(), proceed_thread_callback(), run_command_1(), run_inferior_call(), signal_command(), step_once(), until_break_command(), and until_next_command().
static int proceed_after_vfork_done (struct thread_info * thread, void * arg) [static]
Definition at line 610 of file infrun.c.
References clear_proceed_status(), debug_infrun, fprintf_unfiltered(), gdb_stdlog, is_executing(), is_running(), proceed(), thread_info::ptid, ptid_get_pid(), thread_info::stop_requested, thread_suspend_state::stop_signal, thread_info::suspend, switch_to_thread(), and target_pid_to_str().
Referenced by handle_vfork_child_exec_or_exit().
int ptid_match (ptid_t ptid, ptid_t filter)
Definition at line 7055 of file infrun.c.
References minus_one_ptid, ptid_equal(), ptid_get_pid(), and ptid_is_pid().
Referenced by append_pending_thread_resumptions(), infrun_thread_stop_requested(), iterate_over_lwps(), linux_nat_wait_1(), registers_changed_ptid(), remote_notif_remove_once_on_match(), and resume_stopped_resumed_lwps().
static void remove_displaced_stepping_state (int pid) [static]
Definition at line 1179 of file infrun.c.
References displaced_step_inferior_states, gdb_assert, displaced_step_inferior_state::next, displaced_step_inferior_state::pid, and xfree().
Referenced by infrun_inferior_exit().
void restore_infcall_control_state (struct infcall_control_state * inf_status)
Definition at line 6984 of file infrun.c.
References bpstat_clear(), catch_errors(), thread_info::control, inferior::control, current_inferior(), disp_del_at_next_stop, breakpoint::disposition, thread_control_state::exception_resume_breakpoint, get_current_frame(), infcall_control_state::inferior_control, inferior_thread(), restore_selected_frame(), RETURN_MASK_ERROR, select_frame(), infcall_control_state::selected_frame_id, thread_control_state::step_resume_breakpoint, stop_after_trap, infcall_control_state::stop_after_trap, thread_control_state::stop_bpstat, stop_stack_dummy, infcall_control_state::stop_stack_dummy, stopped_by_random_signal, infcall_control_state::stopped_by_random_signal, target_has_stack, infcall_control_state::thread_control, and xfree().
Referenced by call_function_by_hand(), and do_restore_infcall_control_state_cleanup().
void restore_infcall_suspend_state (struct infcall_suspend_state * inf_state)
Definition at line 6849 of file infrun.c.
References current_inferior(), current_target, discard_infcall_suspend_state(), gdbarch_get_siginfo_type(), get_current_regcache(), get_regcache_arch(), inferior_thread(), regcache_cpy(), infcall_suspend_state::registers, infcall_suspend_state::siginfo_data, infcall_suspend_state::siginfo_gdbarch, stop_pc, infcall_suspend_state::stop_pc, thread_info::suspend, target_has_execution, TARGET_OBJECT_SIGNAL_INFO, target_write(), infcall_suspend_state::thread_suspend, and TYPE_LENGTH.
Referenced by do_restore_infcall_suspend_state_cleanup(), and pop_dummy_frame().
static void restore_inferior_ptid (void * arg) [static]
Definition at line 7073 of file infrun.c.
References cleanup::arg, inferior_ptid, and xfree().
Referenced by save_inferior_ptid().
static int restore_selected_frame (void * args) [static]
Definition at line 6961 of file infrun.c.
References _, frame_find_by_id(), select_frame(), and warning().
Referenced by restore_infcall_control_state().
void resume (int step, enum gdb_signal sig)
Definition at line 1719 of file infrun.c.
References _, bpstat_should_step(), breakpoint_here_p(), breakpoint_inserted_here_p(), thread_info::control, current_inferior(), debug_displaced, debug_infrun, discard_cleanups(), displaced_step_dump_bytes(), displaced_step_prepare(), error(), fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_cannot_step_breakpoint(), gdbarch_displaced_step_hw_singlestep(), gdbarch_skip_permanent_breakpoint(), gdbarch_skip_permanent_breakpoint_p(), gdbarch_software_single_step_p(), get_current_frame(), get_current_regcache(), get_displaced_stepping_state(), get_regcache_arch(), get_regcache_aspace(), get_thread_regcache(), inferior_ptid, inferior_thread(), insert_breakpoints(), insert_hp_step_resume_breakpoint_at_frame(), make_cleanup(), thread_control_state::may_range_step, maybe_software_singlestep(), paddress(), pc_in_thread_step_range(), permanent_breakpoint_here, ptid_get_pid(), QUIT, read_memory(), regcache_read_pc(), remove_single_step_breakpoints(), resume_cleanups(), set_running(), signal_pass, singlestep_breakpoints_inserted_p, thread_info::step_after_step_resume_breakpoint, displaced_step_inferior_state::step_closure, thread_control_state::step_resume_breakpoint, stepping_past_singlestep_breakpoint, thread_suspend_state::stop_signal, thread_info::suspend, target_pass_signals(), target_pid_to_str(), target_resume(), target_terminal_inferior(), thread_control_state::trap_expected, use_displaced_stepping(), and user_visible_resume_ptid().
Referenced by do_initial_windows_stuff(), handle_inferior_event(), keep_going(), and proceed().
static void resume_cleanups (void * ignore) [static]
Definition at line 1606 of file infrun.c.
References normal_stop().
Referenced by keep_going(), and resume().
struct infcall_control_state* save_infcall_control_state (void) [read]
Definition at line 6932 of file infrun.c.
References bpstat_copy(), thread_info::control, inferior::control, current_inferior(), thread_control_state::exception_resume_breakpoint, get_frame_id(), get_selected_frame(), infcall_control_state::inferior_control, inferior_thread(), infcall_control_state::selected_frame_id, thread_control_state::step_resume_breakpoint, stop_after_trap, infcall_control_state::stop_after_trap, thread_control_state::stop_bpstat, stop_stack_dummy, infcall_control_state::stop_stack_dummy, stopped_by_random_signal, infcall_control_state::stopped_by_random_signal, infcall_control_state::thread_control, and xmalloc().
Referenced by call_function_by_hand().
struct infcall_suspend_state* save_infcall_suspend_state (void) [read]
Definition at line 6791 of file infrun.c.
References current_inferior(), current_target, discard_cleanups(), do_cleanups(), gdbarch_get_siginfo_type(), gdbarch_get_siginfo_type_p(), get_current_regcache(), get_regcache_arch(), inferior_thread(), len, make_cleanup(), regcache_dup(), infcall_suspend_state::registers, infcall_suspend_state::siginfo_data, infcall_suspend_state::siginfo_gdbarch, stop_pc, infcall_suspend_state::stop_pc, thread_suspend_state::stop_signal, thread_info::suspend, TARGET_OBJECT_SIGNAL_INFO, target_read(), infcall_suspend_state::thread_suspend, TYPE_LENGTH, xfree(), xmalloc(), and XZALLOC.
Referenced by call_function_by_hand().
struct cleanup* save_inferior_ptid (void) [read]
Definition at line 7086 of file infrun.c.
References inferior_ptid, make_cleanup(), restore_inferior_ptid(), and xmalloc().
Referenced by aix_thread_resume(), aix_thread_wait(), aix_thread_xfer_partial(), detach_breakpoints(), displaced_step_prepare(), handle_inferior_event(), handle_vfork_child_exec_or_exit(), linux_child_follow_fork(), linux_corefile_thread_callback(), linux_nat_xfer_partial(), ps_lgetfpregs(), ps_lgetregs(), ps_lsetfpregs(), ps_lsetregs(), ps_xfer_memory(), reattach_breakpoints(), regcache_raw_read(), regcache_raw_write(), rw_common(), save_sigtrap(), sol_thread_resume(), sol_thread_wait(), sol_thread_xfer_partial(), and write_memory_ptid().
static void set_disable_randomization (char * args, int from_tty, struct cmd_list_element * c) [static]
Definition at line 179 of file infrun.c.
References _, error(), and target_supports_disable_randomization().
static void set_exec_direction_func (char * args, int from_tty, struct cmd_list_element * cmd) [static]
Definition at line 7120 of file infrun.c.
References _, error(), EXEC_FORWARD, exec_forward, EXEC_REVERSE, and target_can_execute_reverse.
static void set_non_stop (char * args, int from_tty, struct cmd_list_element * c) [static]
Definition at line 194 of file infrun.c.
References _, error(), non_stop, non_stop_1, and target_has_execution.
static void set_observer_mode (char * args, int from_tty, struct cmd_list_element * c) [static]
Definition at line 223 of file infrun.c.
References _, error(), may_insert_breakpoints, may_insert_fast_tracepoints, may_insert_tracepoints, may_stop, may_write_memory, may_write_registers, non_stop, non_stop_1, observer_mode, observer_mode_1, pagination_enabled, printf_filtered(), target_async_permitted, target_has_execution, and update_target_permissions().
static void set_schedlock_func (char * args, int from_tty, struct cmd_list_element * c) [static]
Definition at line 1632 of file infrun.c.
References _, error(), schedlock_off, scheduler_mode, target_can_lock_scheduler, and target_shortname.
void set_step_info (struct frame_info * frame, struct symtab_and_line sal)
Definition at line 2873 of file infrun.c.
References thread_info::control, thread_info::current_line, thread_info::current_symtab, get_frame_id(), get_stack_frame_id(), inferior_thread(), symtab_and_line::line, thread_control_state::step_frame_id, thread_control_state::step_stack_frame_id, and symtab_and_line::symtab.
Referenced by finish_command(), handle_inferior_event(), and set_step_frame().
static void set_stop_on_solib_events (char * args, int from_tty, struct cmd_list_element * c) [static]
Definition at line 353 of file infrun.c.
References update_solib_breakpoints().
static void show_can_use_displaced_stepping (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 1218 of file infrun.c.
References _, AUTO_BOOLEAN_AUTO, can_use_displaced_stepping, fprintf_filtered(), and non_stop.
static void show_debug_displaced (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 144 of file infrun.c.
References _, and fprintf_filtered().
static void show_debug_infrun (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 152 of file infrun.c.
References _, and fprintf_filtered().
static void show_disable_randomization (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 164 of file infrun.c.
References _, fprintf_filtered(), fputs_filtered(), and target_supports_disable_randomization().
static void show_exec_direction_func (struct ui_file * out, int from_tty, struct cmd_list_element * cmd, const char * value) [static]
Definition at line 7138 of file infrun.c.
References _, EXEC_FORWARD, EXEC_REVERSE, fprintf_filtered(), and internal_error().
static void show_follow_exec_mode_string (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 807 of file infrun.c.
References _, and fprintf_filtered().
static void show_follow_fork_mode_string (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 405 of file infrun.c.
References _, and fprintf_filtered().
static void show_non_stop (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 207 of file infrun.c.
References _, and fprintf_filtered().
static void show_observer_mode (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 260 of file infrun.c.
References _, and fprintf_filtered().
static void show_schedule_multiple (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 7156 of file infrun.c.
References _, and fprintf_filtered().
static void show_scheduler_mode (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 1622 of file infrun.c.
References _, and fprintf_filtered().
static void show_step_stop_if_no_debug (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 119 of file infrun.c.
References _, and fprintf_filtered().
static void show_stop_on_solib_events (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 359 of file infrun.c.
References _, and fprintf_filtered().
static void sig_print_header (void) [static]
Definition at line 6312 of file infrun.c.
References _, and printf_filtered().
Referenced by handle_command(), and signals_info().
static void sig_print_info (enum gdb_signal oursig) [static]
Definition at line 6319 of file infrun.c.
References gdb_signal_to_name(), gdb_signal_to_string(), name, printf_filtered(), signal_print, signal_program, and signal_stop.
Referenced by handle_command(), and signals_info().
static struct value* siginfo_make_value (struct gdbarch * gdbarch, struct internalvar * var, void * ignore) [static, read]
Definition at line 6748 of file infrun.c.
References allocate_computed_value(), allocate_value(), gdbarch_get_siginfo_type(), gdbarch_get_siginfo_type_p(), inferior_ptid, null_ptid, ptid_equal(), and target_has_stack.
static void siginfo_value_read (struct value * v) [static]
Definition at line 6699 of file infrun.c.
References _, current_target, error(), LONGEST, TARGET_OBJECT_SIGNAL_INFO, target_read(), TYPE_LENGTH, validate_siginfo_access(), value_contents_all_raw(), value_offset(), and value_type().
static void siginfo_value_write (struct value * v, struct value * fromval) [static]
Definition at line 6720 of file infrun.c.
References _, current_target, error(), LONGEST, TARGET_OBJECT_SIGNAL_INFO, target_write(), TYPE_LENGTH, validate_siginfo_access(), value_contents_all_raw(), value_offset(), and value_type().
static void signal_cache_update (int signo) [static]
Definition at line 6251 of file infrun.c.
References int, signal_catch, signal_pass, signal_print, signal_program, and signal_stop.
Referenced by handle_command(), signal_catch_update(), signal_pass_update(), signal_print_update(), and signal_stop_update().
void signal_catch_update (const unsigned int * info)
Definition at line 6301 of file infrun.c.
References signal_cache_update(), signal_catch, signal_pass, and target_pass_signals().
Referenced by signal_catchpoint_insert_location(), and signal_catchpoint_remove_location().
int signal_pass_state (int signo)
Definition at line 6245 of file infrun.c.
References signal_program.
Referenced by append_pending_thread_resumptions(), get_pending_status(), linux_nat_resume_callback(), linux_nat_wait_1(), and remote_program_signals().
int signal_pass_update (int signo, int state)
Definition at line 6288 of file infrun.c.
References signal_cache_update(), and signal_program.
Referenced by nto_initialize_signals().
int signal_print_state (int signo)
Definition at line 6239 of file infrun.c.
References signal_print.
int signal_print_update (int signo, int state)
Definition at line 6278 of file infrun.c.
References signal_cache_update(), and signal_print.
Referenced by check_thread_signals(), and nto_initialize_signals().
int signal_stop_state (int signo)
Definition at line 6233 of file infrun.c.
References signal_stop.
Referenced by handle_inferior_event().
int signal_stop_update (int signo, int state)
Definition at line 6268 of file infrun.c.
References signal_cache_update(), and signal_stop.
Referenced by check_thread_signals(), and nto_initialize_signals().
static void signals_info (char * signum_exp, int from_tty) [static]
Definition at line 6629 of file infrun.c.
References _, GDB_SIGNAL_FIRST, gdb_signal_from_command(), gdb_signal_from_name(), int, parse_and_eval_long(), printf_filtered(), QUIT, sig_print_header(), and sig_print_info().
void start_remote (int from_tty)
Definition at line 2337 of file infrun.c.
References inferior::control, current_inferior(), current_target, normal_stop(), post_create_inferior(), STOP_QUIETLY_REMOTE, inferior_control_state::stop_soon, and wait_for_inferior().
Referenced by monitor_open(), and remote_start_remote().
static int stepped_in_from (struct frame_info * frame, struct frame_id step_frame_id) [static]
Definition at line 3057 of file infrun.c.
References frame_id_eq(), get_frame_id(), get_frame_type(), get_prev_frame(), and INLINE_FRAME.
Referenced by handle_inferior_event().
static void stop_stepping (struct execution_control_state * ecs) [static]
Definition at line 5703 of file infrun.c.
References debug_infrun, fprintf_unfiltered(), gdb_stdlog, and execution_control_state::wait_some_more.
Referenced by handle_inferior_event(), handle_step_into_function(), handle_step_into_function_backward(), and keep_going().
void update_observer_mode (void)
Definition at line 273 of file infrun.c.
References _, may_insert_breakpoints, may_insert_fast_tracepoints, may_insert_tracepoints, may_stop, non_stop, observer_mode, observer_mode_1, and printf_filtered().
Referenced by set_target_permissions(), and set_write_memory_permission().
void update_signals_program_target (void)
Definition at line 328 of file infrun.c.
References signal_program, and target_program_signals().
Referenced by remote_start_remote().
static int use_displaced_stepping (struct gdbarch * gdbarch) [static]
Definition at line 1237 of file infrun.c.
References AUTO_BOOLEAN_AUTO, AUTO_BOOLEAN_TRUE, can_use_displaced_stepping, gdbarch_displaced_step_copy_insn_p(), non_stop, and RECORD_IS_USED.
Referenced by handle_inferior_event(), keep_going(), proceed(), and resume().
ptid_t user_visible_resume_ptid (int step)
Definition at line 1681 of file infrun.c.
References inferior_ptid, non_stop, pid_to_ptid(), ptid_get_pid(), RESUME_ALL, sched_multi, schedlock_on, schedlock_step, scheduler_mode, singlestep_breakpoints_inserted_p, and target_supports_multi_process.
Referenced by resume(), and step_once().
static void validate_siginfo_access (void) [static]
Definition at line 6670 of file infrun.c.
References _, error(), inferior_ptid, is_exited(), is_running(), null_ptid, and ptid_equal().
Referenced by siginfo_value_read(), and siginfo_value_write().
static VEC (char_ptr) [static]
Definition at line 6520 of file infrun.c.
References VEC, VEC_free, and VEC_merge.
void wait_for_inferior (void)
Definition at line 2713 of file infrun.c.
References debug_infrun, delete_step_thread_step_resume_breakpoint_cleanup(), deprecated_target_wait_hook, discard_cleanups(), do_cleanups(), finish_thread_state_cleanup(), fprintf_unfiltered(), gdb_stdlog, handle_inferior_event(), make_cleanup(), memset(), minus_one_ptid, overlay_cache_invalid, print_target_wait_results(), execution_control_state::ptid, target_wait(), execution_control_state::wait_some_more, and execution_control_state::ws.
Referenced by attach_command(), do_initial_windows_stuff(), irix_solib_create_inferior_hook(), notice_new_inferior(), osf_solib_create_inferior_hook(), proceed(), run_inferior_call(), and start_remote().
static void write_memory_ptid (ptid_t ptid, CORE_ADDR memaddr, const gdb_byte * myaddr, int len) [static]
Definition at line 1419 of file infrun.c.
References do_cleanups(), inferior_ptid, save_inferior_ptid(), and write_memory().
Referenced by displaced_step_restore().
static void xdb_handle_command (char * args, int from_tty) [static]
Definition at line 6549 of file infrun.c.
References _, do_cleanups(), error_no_arg(), gdb_buildargv(), gdb_signal_from_name(), handle_command(), make_cleanup_freeargv(), memset(), printf_filtered(), signal_print, signal_program, signal_stop, xfree(), and xmalloc().
Variable Documentation
enum auto_boolean can_use_displaced_stepping = AUTO_BOOLEAN_AUTO [static]
Definition at line 1215 of file infrun.c.
Referenced by show_can_use_displaced_stepping(), and use_displaced_stepping().
int debug_displaced = 0
Definition at line 142 of file infrun.c.
Referenced by amd64_displaced_step_copy_insn(), amd64_displaced_step_fixup(), amd64_relocate_instruction(), arm_copy_alu_imm(), arm_copy_alu_reg(), arm_copy_alu_shifted_reg(), arm_copy_b_bl_blx(), arm_copy_block_xfer(), arm_copy_bx_blx_reg(), arm_copy_copro_load_store(), arm_copy_extra_ld_st(), arm_copy_ldr_str_ldrb_strb(), arm_copy_preload(), arm_copy_preload_reg(), arm_copy_svc(), arm_copy_undef(), arm_copy_unmodified(), arm_copy_unpred(), arm_displaced_init_closure(), arm_linux_cleanup_svc(), arm_linux_copy_svc(), arm_linux_displaced_step_copy_insn(), arm_pc_is_thumb(), arm_process_displaced_insn(), cleanup_block_load_all(), cleanup_block_load_pc(), cleanup_block_store_pc(), cleanup_svc(), displaced_read_reg(), displaced_step_fixup(), displaced_step_prepare(), displaced_step_restore(), displaced_write_reg(), fixup_riprel(), handle_inferior_event(), i386_displaced_step_copy_insn(), i386_displaced_step_fixup(), i386_relocate_instruction(), ppc_displaced_step_fixup(), resume(), s390_displaced_step_fixup(), simple_displaced_step_copy_insn(), thumb2_copy_alu_imm(), thumb2_copy_b_bl_blx(), thumb2_copy_block_xfer(), thumb2_copy_copro_load_store(), thumb2_copy_load_literal(), thumb2_copy_load_reg_imm(), thumb2_copy_preload(), thumb2_copy_table_branch(), thumb_32bit_copy_undef(), thumb_copy_16bit_ldr_literal(), thumb_copy_alu_reg(), thumb_copy_b(), thumb_copy_bx_blx_reg(), thumb_copy_cbnz_cbz(), thumb_copy_pc_relative_32bit(), thumb_copy_pop_pc_16bit(), thumb_copy_svc(), thumb_copy_unmodified_16bit(), thumb_copy_unmodified_32bit(), thumb_decode_pc_relative_16bit(), and thumb_process_displaced_insn().
unsigned int debug_infrun = 0
Definition at line 150 of file infrun.c.
Referenced by bpstat_what(), clear_proceed_status_thread(), context_switch(), fetch_inferior_event(), handle_inferior_event(), handle_syscall_event(), handle_vfork_child_exec_or_exit(), insert_exception_resume_breakpoint(), insert_exception_resume_from_probe(), insert_longjmp_resume_breakpoint(), insert_step_resume_breakpoint_at_sal_1(), prepare_for_detach(), prepare_to_proceed(), prepare_to_wait(), proceed(), proceed_after_vfork_done(), resume(), stop_stepping(), and wait_for_inferior().
ptid_t deferred_step_ptid [static]
Definition at line 986 of file infrun.c.
int detach_fork = 1 [static]
Definition at line 140 of file infrun.c.
Referenced by follow_fork(), handle_inferior_event(), and linux_child_follow_fork().
int disable_randomization = 1
Definition at line 161 of file infrun.c.
Referenced by extended_remote_create_inferior_1(), and linux_nat_create_inferior().
struct displaced_step_inferior_state* displaced_step_inferior_states [static]
Definition at line 1117 of file infrun.c.
Referenced by add_displaced_stepping_state(), and remove_displaced_stepping_state().
const char* exec_direction = exec_forward [static]
Definition at line 7112 of file infrun.c.
const char* const exec_direction_names[] [static]
Initial value:
 {
  exec_forward,
  exec_reverse,
  NULL
}
Definition at line 7113 of file infrun.c.
const char exec_forward[] = "forward" [static]
Definition at line 7110 of file infrun.c.
Referenced by set_exec_direction_func().
const char exec_reverse[] = "reverse" [static]
Definition at line 7111 of file infrun.c.
int execution_direction = EXEC_FORWARD
Definition at line 7109 of file infrun.c.
Referenced by adjust_pc_after_break(), call_function_by_hand(), exec_direction_default(), exec_direction_forward(), exec_reverse_continue(), exec_reverse_once(), fetch_inferior_event(), finish_command(), handle_inferior_event(), maybe_software_singlestep(), normal_stop(), proceed(), record_full_core_resume(), record_full_resume(), record_full_wait_1(), record_full_wait_cleanups(), and remote_resume().
const char* const follow_exec_mode_names[] [static]
Initial value:
{
  follow_exec_mode_new,
  follow_exec_mode_same,
  NULL,
}
Definition at line 798 of file infrun.c.
const char follow_exec_mode_new[] = "new" [static]
Definition at line 796 of file infrun.c.
Referenced by follow_exec().
const char follow_exec_mode_same[] = "same" [static]
Definition at line 797 of file infrun.c.
const char* follow_exec_mode_string = follow_exec_mode_same [static]
Definition at line 805 of file infrun.c.
Referenced by follow_exec().
const char follow_fork_mode_child[] = "child" [static]
Definition at line 394 of file infrun.c.
Referenced by follow_fork(), and handle_inferior_event().
const char* const follow_fork_mode_kind_names[] [static]
Initial value:
 {
  follow_fork_mode_child,
  follow_fork_mode_parent,
  NULL
}
Definition at line 397 of file infrun.c.
const char follow_fork_mode_parent[] = "parent" [static]
Definition at line 395 of file infrun.c.
const char* follow_fork_mode_string = follow_fork_mode_parent [static]
Definition at line 403 of file infrun.c.
Referenced by follow_fork(), and handle_inferior_event().
enum infwait_states infwait_state [static]
Definition at line 2408 of file infrun.c.
Referenced by handle_inferior_event(), and init_infwait_state().
int non_stop = 0
Definition at line 190 of file infrun.c.
Referenced by adjust_pc_after_break(), agent_run_command(), attach_command(), attach_command_post_wait(), breakpoints_always_inserted_mode(), clear_proceed_status(), continue_1(), continue_command(), delete_step_thread_step_resume_breakpoint(), exec_continue(), extended_remote_attach_1(), fetch_inferior_event(), follow_fork(), get_event_thread(), get_pending_status(), handle_inferior_event(), handle_notification(), handle_vfork_child_exec_or_exit(), inferior_event_handler(), interrupt_target_1(), interrupt_target_command(), linux_child_follow_fork(), linux_handle_extended_wait(), linux_nat_stop(), linux_nat_wait(), linux_nat_wait_1(), mi_cmd_exec_interrupt(), mi_on_normal_stop(), normal_stop(), notice_new_inferior(), prepare_execute_command(), prepare_to_proceed(), proceed(), program_info(), putpkt_binary(), record_full_open_1(), remote_async_get_pending_events_handler(), remote_parse_stop_reply(), remote_resume(), remote_start_remote(), remote_stop(), remote_threads_info(), remote_vcont_resume(), remote_wait(), run_command_1(), set_non_stop(), set_observer_mode(), show_can_use_displaced_stepping(), update_global_location_list(), update_observer_mode(), use_displaced_stepping(), and user_visible_resume_ptid().
int non_stop_1 = 0 [static]
Definition at line 191 of file infrun.c.
Referenced by set_non_stop(), and set_observer_mode().
int observer_mode = 0
Definition at line 219 of file infrun.c.
Referenced by set_observer_mode(), and update_observer_mode().
int observer_mode_1 = 0 [static]
Definition at line 220 of file infrun.c.
Referenced by set_observer_mode(), and update_observer_mode().
ptid_t previous_inferior_ptid [static]
Definition at line 133 of file infrun.c.
ptid_t saved_singlestep_ptid [static]
Definition at line 976 of file infrun.c.
int sched_multi = 0
Definition at line 1644 of file infrun.c.
Referenced by exec_continue(), linux_child_follow_fork(), prepare_to_proceed(), and user_visible_resume_ptid().
const char schedlock_off[] = "off" [static]
Definition at line 1611 of file infrun.c.
Referenced by set_schedlock_func().
const char schedlock_on[] = "on" [static]
Definition at line 1612 of file infrun.c.
Referenced by prepare_to_proceed(), and user_visible_resume_ptid().
const char schedlock_step[] = "step" [static]
Definition at line 1613 of file infrun.c.
Referenced by prepare_to_proceed(), and user_visible_resume_ptid().
const char* const scheduler_enums[] [static]
Initial value:
 {
  schedlock_off,
  schedlock_on,
  schedlock_step,
  NULL
}
Definition at line 1614 of file infrun.c.
const char* scheduler_mode = schedlock_off [static]
Definition at line 1620 of file infrun.c.
Referenced by prepare_to_proceed(), set_schedlock_func(), and user_visible_resume_ptid().
struct internalvar_funcs siginfo_funcs [static]
Initial value:
{
  siginfo_make_value,
  NULL,
  NULL
}
Definition at line 7165 of file infrun.c.
struct lval_funcs siginfo_value_funcs [static]
Initial value:
  {
    siginfo_value_read,
    siginfo_value_write
  }
Definition at line 6737 of file infrun.c.
unsigned char* signal_catch [static]
Definition at line 301 of file infrun.c.
Referenced by signal_cache_update(), and signal_catch_update().
unsigned char* signal_pass [static]
Definition at line 306 of file infrun.c.
Referenced by handle_command(), resume(), signal_cache_update(), and signal_catch_update().
unsigned char* signal_print [static]
Definition at line 294 of file infrun.c.
Referenced by handle_command(), handle_inferior_event(), sig_print_info(), signal_cache_update(), signal_print_state(), signal_print_update(), and xdb_handle_command().
unsigned char* signal_program [static]
Definition at line 295 of file infrun.c.
Referenced by handle_command(), handle_inferior_event(), keep_going(), proceed(), sig_print_info(), signal_cache_update(), signal_pass_state(), signal_pass_update(), update_signals_program_target(), and xdb_handle_command().
unsigned char* signal_stop [static]
Definition at line 293 of file infrun.c.
Referenced by handle_command(), sig_print_info(), signal_cache_update(), signal_stop_state(), signal_stop_update(), and xdb_handle_command().
int singlestep_breakpoints_inserted_p = 0 [static]
Definition at line 966 of file infrun.c.
Referenced by adjust_pc_after_break(), handle_inferior_event(), maybe_software_singlestep(), resume(), and user_visible_resume_ptid().
CORE_ADDR singlestep_pc [static]
Definition at line 972 of file infrun.c.
Referenced by handle_inferior_event(), and maybe_software_singlestep().
ptid_t singlestep_ptid [static]
Definition at line 969 of file infrun.c.
Referenced by handle_inferior_event().
struct symbol* step_start_function [static]
Definition at line 343 of file infrun.c.
int step_stop_if_no_debug = 0
Definition at line 117 of file infrun.c.
Referenced by handle_inferior_event(), and step_once().
int stepping_past_singlestep_breakpoint [static]
Definition at line 977 of file infrun.c.
Referenced by handle_inferior_event(), init_wait_for_inferior(), and resume().
int stop_after_trap
Definition at line 369 of file infrun.c.
Referenced by clear_proceed_status(), do_initial_windows_stuff(), handle_inferior_event(), proceed(), restore_infcall_control_state(), and save_infcall_control_state().
struct cmd_list_element* stop_command [static]
Definition at line 339 of file infrun.c.
int stop_on_solib_events
Definition at line 347 of file infrun.c.
Referenced by handle_inferior_event(), internal_bkpt_check_status(), and svr4_update_solib_event_breakpoint().
int stop_print_frame [static]
Definition at line 380 of file infrun.c.
Referenced by handle_inferior_event(), and normal_stop().
struct regcache* stop_registers
Definition at line 376 of file infrun.c.
Referenced by call_function_by_hand(), and get_return_value().
int sync_execution = 0
Definition at line 127 of file infrun.c.
Referenced by async_background_execution_p(), async_disable_stdin(), async_enable_stdin(), display_gdb_prompt(), execute_command(), fetch_inferior_event(), handle_inferior_event(), linux_child_follow_fork(), mi_interpreter_resume(), normal_stop(), and target_terminal_inferior().
ptid_t target_last_wait_ptid [static]
Definition at line 385 of file infrun.c.
Referenced by get_last_target_status().
struct target_waitstatus target_last_waitstatus [static]
Definition at line 386 of file infrun.c.
Referenced by get_last_target_status(), and handle_inferior_event().
ptid_t waiton_ptid
Definition at line 2405 of file infrun.c.