GDB (xrefs): /home/stan/gdb/src/gdb/inline-frame.h File Reference
/home/stan/gdb/src/gdb/inline-frame.h File Reference
Functions
void skip_inline_frames (ptid_t ptid)
void clear_inline_frame_state (ptid_t ptid)
void step_into_inline_frame (ptid_t ptid)
int inline_skipped_frames (ptid_t ptid)
struct symbol * inline_skipped_symbol (ptid_t ptid)
int frame_inlined_callees (struct frame_info *this_frame)
Variables
struct frame_unwind inline_frame_unwind
Function Documentation
void clear_inline_frame_state (ptid_t ptid)
Definition at line 114 of file inline-frame.c.
References minus_one_ptid, inline_state::ptid, ptid_equal(), ptid_get_pid(), ptid_is_pid(), VEC, VEC_free, VEC_iterate, VEC_safe_push, and VEC_unordered_remove.
Referenced by init_wait_for_inferior(), and target_resume().
int frame_inlined_callees (struct frame_info * this_frame)
Definition at line 392 of file inline-frame.c.
References get_frame_type(), get_next_frame(), inferior_ptid, INLINE_FRAME, and inline_skipped_frames().
Referenced by find_frame_sal(), and get_frame_block().
int inline_skipped_frames (ptid_t ptid)
Definition at line 365 of file inline-frame.c.
References inline_state::skipped_frames.
Referenced by frame_inlined_callees(), frame_show_address(), handle_inferior_event(), and step_once().
struct symbol* inline_skipped_symbol (ptid_t ptid) [read]
Definition at line 379 of file inline-frame.c.
References gdb_assert, and inline_state::skipped_symbol.
Referenced by find_frame_sal().
void skip_inline_frames (ptid_t ptid)
Definition at line 303 of file inline-frame.c.
References allocate_inline_frame_state(), block_for_pc(), BLOCK_FUNCTION, block_inlined_p(), BLOCK_START, block_starting_point_at(), BLOCK_SUPERBLOCK, gdb_assert, get_current_frame(), get_frame_pc(), reinit_frame_cache(), inline_state::saved_pc, inline_state::skipped_frames, and inline_state::skipped_symbol.
Referenced by handle_inferior_event().
void step_into_inline_frame (ptid_t ptid)
Definition at line 352 of file inline-frame.c.
References gdb_assert, reinit_frame_cache(), and inline_state::skipped_frames.
Referenced by handle_inferior_event(), and step_once().
Variable Documentation
struct frame_unwind inline_frame_unwind
Definition at line 262 of file inline-frame.c.
Referenced by frame_unwind_init().