GDB (xrefs): /home/stan/gdb/src/gdb/interps.h File Reference
/home/stan/gdb/src/gdb/interps.h File Reference
#include "exceptions.h"
Classes
struct interp_procs
Defines
#define INTERP_CONSOLE "console"
#define INTERP_MI1 "mi1"
#define INTERP_MI2 "mi2"
#define INTERP_MI3 "mi3"
#define INTERP_MI "mi"
#define INTERP_TUI "tui"
#define INTERP_INSIGHT "insight"
Typedefs
typedef void *(interp_init_ftype)(struct interp *self, int top_level)
typedef int(interp_resume_ftype)(void *data)
typedef int(interp_suspend_ftype)(void *data)
typedef int(interp_prompt_p_ftype)(void *data)
typedef void(interp_command_loop_ftype)(void *data)
typedef struct ui_out *(interp_ui_out_ftype)(struct interp *self)
typedef int(interp_set_logging_ftype)(struct interp *self, int start_log, struct ui_file *out, struct ui_file *logfile)
Functions
int interp_resume (struct interp *interp)
int interp_suspend (struct interp *interp)
int interp_prompt_p (struct interp *interp)
int interp_exec_p (struct interp *interp)
struct gdb_exception interp_exec (struct interp *interp, const char *command)
int interp_quiet_p (struct interp *interp)
struct gdb_exception() interp_exec_ftype (void *data, const char *command)
struct interp * interp_new (const char *name, const struct interp_procs *procs)
void interp_add (struct interp *interp)
int interp_set (struct interp *interp, int top_level)
struct interp * interp_lookup (const char *name)
struct ui_out * interp_ui_out (struct interp *interp)
void * interp_data (struct interp *interp)
const char * interp_name (struct interp *interp)
struct interp * interp_set_temp (const char *name)
int current_interp_named_p (const char *name)
int current_interp_display_prompt_p (void)
void current_interp_command_loop (void)
int current_interp_set_logging (int start_log, struct ui_file *out, struct ui_file *logfile)
void * top_level_interpreter_data (void)
struct interp * top_level_interpreter (void)
void clear_interpreter_hooks (void)
Variables
int interpreter_async
Define Documentation
#define INTERP_CONSOLE "console"
Definition at line 112 of file interps.h.
Referenced by _initialize_cli_interp(), _initialize_tui_interp(), captured_main(), main(), and read_command_lines().
#define INTERP_INSIGHT "insight"
Definition at line 118 of file interps.h.
Referenced by captured_main().
#define INTERP_MI "mi"
Definition at line 116 of file interps.h.
Referenced by _initialize_mi_interp(), captured_mi_execute_command(), mi_interpreter_init(), and mi_load_progress().
#define INTERP_MI1 "mi1"
Definition at line 113 of file interps.h.
Referenced by _initialize_mi_interp(), captured_main(), captured_mi_execute_command(), mi_interpreter_init(), and mi_load_progress().
#define INTERP_MI2 "mi2"
Definition at line 114 of file interps.h.
Referenced by _initialize_mi_interp(), captured_mi_execute_command(), mi_interpreter_init(), and mi_load_progress().
#define INTERP_MI3 "mi3"
Definition at line 115 of file interps.h.
Referenced by _initialize_mi_interp(), captured_mi_execute_command(), mi_interpreter_init(), and mi_load_progress().
#define INTERP_TUI "tui"
Definition at line 117 of file interps.h.
Referenced by _initialize_tui_interp(), and captured_main().
Typedef Documentation
typedef void(interp_command_loop_ftype)(void *data)
Definition at line 44 of file interps.h.
typedef void*(interp_init_ftype)(struct interp *self, int top_level)
Definition at line 38 of file interps.h.
typedef int(interp_prompt_p_ftype)(void *data)
Definition at line 41 of file interps.h.
typedef int(interp_resume_ftype)(void *data)
Definition at line 39 of file interps.h.
typedef int(interp_set_logging_ftype)(struct interp *self, int start_log, struct ui_file *out, struct ui_file *logfile)
Definition at line 47 of file interps.h.
typedef int(interp_suspend_ftype)(void *data)
Definition at line 40 of file interps.h.
typedef struct ui_out*(interp_ui_out_ftype)(struct interp *self)
Definition at line 45 of file interps.h.
Function Documentation
void clear_interpreter_hooks (void)
Definition at line 369 of file interps.c.
References deprecated_call_command_hook, deprecated_context_hook, deprecated_error_begin_hook, deprecated_init_ui_hook, deprecated_interactive_hook, deprecated_print_frame_info_listing_hook, deprecated_query_hook, deprecated_readline_begin_hook, deprecated_readline_end_hook, deprecated_readline_hook, deprecated_register_changed_hook, deprecated_target_wait_hook, and deprecated_warning_hook.
Referenced by interp_set(), and mi_interpreter_resume().
void current_interp_command_loop (void)
Definition at line 323 of file interps.c.
References interp_procs::command_loop_proc, interp::data, gdb_assert, and interp::procs.
Referenced by captured_command_loop().
int current_interp_display_prompt_p (void)
Definition at line 311 of file interps.c.
References interp::data, interp::procs, and interp_procs::prompt_proc_p.
Referenced by display_gdb_prompt().
int current_interp_named_p (const char * name)
Definition at line 299 of file interps.c.
References interp::name.
Referenced by captured_main(), captured_mi_execute_command(), mi_load_progress(), and read_command_lines().
int current_interp_set_logging (int start_log, struct ui_file * out, struct ui_file * logfile)
Definition at line 257 of file interps.c.
References interp::procs, and interp_procs::set_logging_proc.
Referenced by handle_redirections(), pop_output_files(), and set_logging_redirect().
void interp_add (struct interp * interp)
Definition at line 113 of file interps.c.
References gdb_assert, initialize_interps(), interp_list, interp_lookup(), interpreter_initialized, interp::name, and interp::next.
Referenced by _initialize_cli_interp(), _initialize_mi_interp(), and _initialize_tui_interp().
void* interp_data (struct interp * interp)
Definition at line 284 of file interps.c.
References interp::data.
Referenced by gdbtk_interpreter_ui_out(), mi_set_logging(), and mi_ui_out().
struct gdb_exception interp_exec (struct interp * interp, const char * command) [read]
Definition at line 357 of file interps.c.
References exception_none.
Referenced by interpreter_exec_cmd(), and mi_cmd_interpreter_exec().
struct gdb_exception() interp_exec_ftype (void * data, const char * command) [read]
int interp_exec_p (struct interp * interp)
Definition at line 351 of file interps.c.
References interp_procs::exec_proc, and interp::procs.
Referenced by mi_cmd_interpreter_exec().
struct interp* interp_lookup (const char * name) [read]
Definition at line 229 of file interps.c.
References interp::name, and interp::next.
Referenced by captured_main(), interp_add(), interp_set_temp(), interpreter_exec_cmd(), and mi_cmd_interpreter_exec().
const char* interp_name (struct interp * interp)
Definition at line 292 of file interps.c.
References interp::name.
Referenced by darwin_solib_get_all_image_info_addr_at_init(), enable_break(), mi_interpreter_init(), and restore_interp().
struct interp* interp_new (const char * name, const struct interp_procs * procs) [read]
Definition at line 92 of file interps.c.
References interp_procs::command_loop_proc, interp::data, gdb_assert, interp::inited, interp::name, interp::procs, interp::quiet_p, and XMALLOC.
Referenced by _initialize_cli_interp(), _initialize_mi_interp(), and _initialize_tui_interp().
int interp_prompt_p (struct interp * interp)
int interp_quiet_p (struct interp * interp)
Definition at line 331 of file interps.c.
References interp::quiet_p.
Referenced by cli_interpreter_display_prompt_p(), interp_set(), and tui_display_prompt_p().
int interp_resume (struct interp * interp)
int interp_set (struct interp * interp, int top_level)
Definition at line 139 of file interps.c.
References _, clear_interpreter_hooks(), current_interpreter, current_uiout, interp::data, display_gdb_prompt(), error(), first_time, gdb_assert, interp_procs::init_proc, interp::inited, internal_error(), interp_quiet_p(), interp_set(), interpreter_p, interp::name, interp::procs, interp_procs::resume_proc, interp_procs::suspend_proc, ui_out_flush(), interp_procs::ui_out_proc, ui_out_text(), xfree(), and xsnprintf().
Referenced by captured_main(), interp_set(), and interpreter_exec_cmd().
struct interp* interp_set_temp (const char * name) [read]
Definition at line 271 of file interps.c.
References current_interpreter, and interp_lookup().
Referenced by read_command_lines(), and restore_interp().
int interp_suspend (struct interp * interp)
struct ui_out* interp_ui_out (struct interp * interp) [read]
Definition at line 248 of file interps.c.
References interp::procs, and interp_procs::ui_out_proc.
Referenced by decode_line_full(), fputs_maybe_filtered(), info_sharedlibrary_command(), mi_breakpoint_created(), mi_breakpoint_modified(), mi_command_param_changed(), mi_execute_command(), mi_memory_changed(), mi_on_normal_stop(), and mi_tsv_modified().
struct interp* top_level_interpreter (void) [read]
Definition at line 494 of file interps.c.
References top_level_interpreter_ptr.
Referenced by decode_line_full(), fputs_maybe_filtered(), info_sharedlibrary_command(), mi_breakpoint_created(), mi_breakpoint_modified(), mi_command_param_changed(), mi_execute_command(), mi_memory_changed(), mi_on_normal_stop(), and mi_tsv_modified().
void* top_level_interpreter_data (void)
Definition at line 500 of file interps.c.
References interp::data, and gdb_assert.
Referenced by mi_breakpoint_created(), mi_breakpoint_deleted(), mi_breakpoint_modified(), mi_command_param_changed(), mi_execute_command(), mi_inferior_added(), mi_inferior_appeared(), mi_inferior_exit(), mi_inferior_removed(), mi_memory_changed(), mi_new_thread(), mi_record_changed(), mi_solib_loaded(), mi_solib_unloaded(), mi_thread_exit(), mi_traceframe_changed(), mi_tsv_created(), mi_tsv_deleted(), and mi_tsv_modified().
Variable Documentation
int interpreter_async
Definition at line 49 of file interps.c.
Referenced by captured_command_loop(), execute_command(), execute_command_to_string(), execute_user_command(), fetch_inferior_event(), if_command(), inferior_event_handler(), and while_command().