GDB (xrefs): /home/stan/gdb/src/gdb/jit.c File Reference
/home/stan/gdb/src/gdb/jit.c File Reference
#include "defs.h"
#include "jit.h"
#include "jit-reader.h"
#include "block.h"
#include "breakpoint.h"
#include "command.h"
#include "dictionary.h"
#include "filenames.h"
#include "frame-unwind.h"
#include "gdbcmd.h"
#include "gdbcore.h"
#include "inferior.h"
#include "observer.h"
#include "objfiles.h"
#include "regcache.h"
#include "symfile.h"
#include "symtab.h"
#include "target.h"
#include "gdb-dlfcn.h"
#include "gdb_stat.h"
#include "exceptions.h"
#include "gdb_bfd.h"
Classes
struct target_buffer
struct jit_reader
struct jit_program_space_data
struct jit_objfile_data
struct gdb_block
struct gdb_symtab
struct gdb_object
struct jit_unwind_private
struct jit_gdbarch_data_type
Typedefs
typedef struct gdb_reader_funcs *(reader_init_fn_type)(void)
typedef CORE_ADDR jit_dbg_reader_data
Functions
static void jit_inferior_init (struct gdbarch *gdbarch)
static void show_jit_debug (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static void * mem_bfd_iovec_open (struct bfd *abfd, void *open_closure)
static int mem_bfd_iovec_close (struct bfd *abfd, void *stream)
static file_ptr mem_bfd_iovec_pread (struct bfd *abfd, void *stream, void *buf, file_ptr nbytes, file_ptr offset)
static int mem_bfd_iovec_stat (struct bfd *abfd, void *stream, struct stat *sb)
static struct bfd * bfd_open_from_target_memory (CORE_ADDR addr, ULONGEST size, char *target)
static struct jit_reader * jit_reader_load (const char *file_name)
static void jit_reader_load_command (char *args, int from_tty)
static void jit_reader_unload_command (char *args, int from_tty)
static struct jit_objfile_data * get_jit_objfile_data (struct objfile *objf)
static void add_objfile_entry (struct objfile *objfile, CORE_ADDR entry)
static struct
jit_program_space_data * get_jit_program_space_data (void)
static void jit_program_space_data_cleanup (struct program_space *ps, void *arg)
static int jit_read_descriptor (struct gdbarch *gdbarch, struct jit_descriptor *descriptor, struct jit_program_space_data *ps_data)
static void jit_read_code_entry (struct gdbarch *gdbarch, CORE_ADDR code_addr, struct jit_code_entry *code_entry)
static enum gdb_status jit_target_read_impl (GDB_CORE_ADDR target_mem, void *gdb_buf, int len)
static struct gdb_object * jit_object_open_impl (struct gdb_symbol_callbacks *cb)
static struct gdb_symtab * jit_symtab_open_impl (struct gdb_symbol_callbacks *cb, struct gdb_object *object, const char *file_name)
static int compare_block (const struct gdb_block *const old, const struct gdb_block *const new)
static struct gdb_block * jit_block_open_impl (struct gdb_symbol_callbacks *cb, struct gdb_symtab *symtab, struct gdb_block *parent, GDB_CORE_ADDR begin, GDB_CORE_ADDR end, const char *name)
static void jit_symtab_line_mapping_add_impl (struct gdb_symbol_callbacks *cb, struct gdb_symtab *stab, int nlines, struct gdb_line_mapping *map)
static void jit_symtab_close_impl (struct gdb_symbol_callbacks *cb, struct gdb_symtab *stab)
static void finalize_symtab (struct gdb_symtab *stab, struct objfile *objfile)
static void jit_object_close_impl (struct gdb_symbol_callbacks *cb, struct gdb_object *obj)
static int jit_reader_try_read_symtab (struct jit_code_entry *code_entry, CORE_ADDR entry_addr)
static void jit_bfd_try_read_symtab (struct jit_code_entry *code_entry, CORE_ADDR entry_addr, struct gdbarch *gdbarch)
static void jit_register_code (struct gdbarch *gdbarch, CORE_ADDR entry_addr, struct jit_code_entry *code_entry)
static void jit_unregister_code (struct objfile *objfile)
static struct objfile * jit_find_objf_with_entry_addr (CORE_ADDR entry_addr)
static void jit_breakpoint_deleted (struct breakpoint *b)
static int jit_breakpoint_re_set_internal (struct gdbarch *gdbarch, struct jit_program_space_data *ps_data)
static void jit_unwind_reg_set_impl (struct gdb_unwind_callbacks *cb, int dwarf_regnum, struct gdb_reg_value *value)
static void reg_value_free_impl (struct gdb_reg_value *value)
static struct gdb_reg_value * jit_unwind_reg_get_impl (struct gdb_unwind_callbacks *cb, int regnum)
static void jit_dealloc_cache (struct frame_info *this_frame, void *cache)
static int jit_frame_sniffer (const struct frame_unwind *self, struct frame_info *this_frame, void **cache)
static void jit_frame_this_id (struct frame_info *this_frame, void **cache, struct frame_id *this_id)
static struct value * jit_frame_prev_register (struct frame_info *this_frame, void **cache, int reg)
static void jit_prepend_unwinder (struct gdbarch *gdbarch)
void jit_inferior_created_hook (void)
void jit_breakpoint_re_set (void)
static void jit_inferior_exit_hook (struct inferior *inf)
void jit_event_handler (struct gdbarch *gdbarch)
static void free_objfile_data (struct objfile *objfile, void *data)
static void * jit_gdbarch_data_init (struct obstack *obstack)
void _initialize_jit (void)
Variables
static const char * jit_reader_dir = NULL
static struct objfile_data * jit_objfile_data
static const char *const jit_break_name = "__jit_debug_register_code"
static const char *const jit_descriptor_name = "__jit_debug_descriptor"
static struct program_space_data * jit_program_space_data = NULL
static struct gdbarch_data * jit_gdbarch_data
static unsigned int jit_debug = 0
static struct jit_reader * loaded_jit_reader
static const char * reader_init_fn_sym = "gdb_init_reader"
static struct frame_unwind jit_frame_unwind
Typedef Documentation
typedef CORE_ADDR jit_dbg_reader_data
Definition at line 482 of file jit.c.
typedef struct gdb_reader_funcs*(reader_init_fn_type)(void)
Definition at line 160 of file jit.c.
Function Documentation
void _initialize_jit (void)
static void add_objfile_entry (struct objfile * objfile, CORE_ADDR entry) [static]
Definition at line 302 of file jit.c.
References jit_objfile_data::addr, and get_jit_objfile_data().
Referenced by jit_bfd_try_read_symtab(), and jit_object_close_impl().
static struct bfd* bfd_open_from_target_memory (CORE_ADDR addr, ULONGEST size, char * target) [static, read]
Definition at line 137 of file jit.c.
References target_buffer::base, gdb_bfd_openr_iovec(), mem_bfd_iovec_close(), mem_bfd_iovec_open(), mem_bfd_iovec_pread(), mem_bfd_iovec_stat(), target_buffer::size, size, and xmalloc().
Referenced by jit_bfd_try_read_symtab().
static int compare_block (const struct gdb_block *const old, const struct gdb_block *const new) [static]
Definition at line 533 of file jit.c.
References gdb_block::begin, and gdb_block::end.
Referenced by jit_block_open_impl().
static void finalize_symtab (struct gdb_symtab * stab, struct objfile * objfile) [static]
Definition at line 633 of file jit.c.
References allocate_block(), allocate_global_block(), allocate_symbol(), allocate_symtab(), arch_type(), gdb_block::begin, BLOCK_DICT, BLOCK_END, BLOCK_FUNCTION, BLOCK_START, BLOCK_SUPERBLOCK, gdb_symtab::blocks, symtab::blockvector, BLOCKVECTOR_BLOCK, BLOCKVECTOR_MAP, BLOCKVECTOR_NBLOCKS, dict_create_linear(), symtab::dirname, gdb_block::end, gdb_symtab::file_name, FIRST_LOCAL_BLOCK, get_objfile_arch(), symbol::ginfo, GLOBAL_BLOCK, gdb_symtab::linetable, LINETABLE, LOC_BLOCK, lookup_function_type(), memcpy(), general_symbol_info::name, gdb_block::name, gdb_symtab::nblocks, new_block(), gdb_block::next, linetable::nitems, objfile::objfile_obstack, gdb_block::parent, symtab::primary, gdb_block::real_block, set_block_symtab(), size, STATIC_BLOCK, SYMBOL_ACLASS_INDEX, SYMBOL_BLOCK_VALUE, SYMBOL_DOMAIN, SYMBOL_SYMTAB, SYMBOL_TYPE, TYPE_CODE_VOID, VAR_DOMAIN, and xfree().
Referenced by jit_object_close_impl().
static void free_objfile_data (struct objfile * objfile, void * data) [static]
Definition at line 1430 of file jit.c.
References jit_program_space_data::objfile, objfile::pspace, jit_objfile_data::register_code, and xfree().
static struct jit_objfile_data* get_jit_objfile_data (struct objfile * objf) [static, read]
Definition at line 284 of file jit.c.
References XZALLOC.
Referenced by add_objfile_entry(), jit_breakpoint_re_set_internal(), and jit_read_descriptor().
static struct jit_program_space_data* get_jit_program_space_data (void) [static, read]
Definition at line 314 of file jit.c.
References current_program_space, and XZALLOC.
Referenced by jit_breakpoint_re_set(), jit_event_handler(), and jit_inferior_init().
static void jit_bfd_try_read_symtab (struct jit_code_entry * code_entry, CORE_ADDR entry_addr, struct gdbarch * gdbarch) [static]
Definition at line 865 of file jit.c.
References _, add_objfile_entry(), section_addr_info::other_sections::addr, alloc_section_addr_info(), bfd_open_from_target_memory(), do_cleanups(), fprintf_unfiltered(), gdb_bfd_unref(), gdb_stdlog, gdbarch_bfd_arch_info(), gnutarget, jit_debug, make_cleanup_bfd_unref(), make_cleanup_free_section_addr_info(), section_addr_info::other_sections::name, section_addr_info::num_sections, OBJF_NOT_FILENAME, OBJF_SHARED, section_addr_info::other, paddress(), printf_unfiltered(), pulongest(), puts_unfiltered(), section_addr_info::other_sections::sectindex, symbol_file_add_from_bfd(), jit_code_entry::symfile_addr, jit_code_entry::symfile_size, and warning().
Referenced by jit_register_code().
static struct gdb_block* jit_block_open_impl (struct gdb_symbol_callbacks * cb, struct gdb_symtab * symtab, struct gdb_block * parent, GDB_CORE_ADDR begin, GDB_CORE_ADDR end, const char * name) [static, read]
Definition at line 556 of file jit.c.
References gdb_block::begin, gdb_symtab::blocks, compare_block(), gdb_block::end, gdb_block::name, gdb_symtab::nblocks, gdb_block::next, gdb_block::parent, and XZALLOC.
Referenced by jit_reader_try_read_symtab().
static void jit_breakpoint_deleted (struct breakpoint * b) [static]
Definition at line 991 of file jit.c.
References bp_jit_event, jit_program_space_data::cached_code_address, jit_program_space_data::jit_breakpoint, breakpoint::loc, bp_location::next, bp_location::owner, bp_location::pspace, and breakpoint::type.
void jit_breakpoint_re_set (void)
Definition at line 1362 of file jit.c.
References get_jit_program_space_data(), jit_breakpoint_re_set_internal(), and target_gdbarch().
Referenced by breakpoint_re_set().
static int jit_breakpoint_re_set_internal (struct gdbarch * gdbarch, struct jit_program_space_data * ps_data) [static]
Definition at line 1015 of file jit.c.
References jit_objfile_data::addr, jit_program_space_data::cached_code_address, create_jit_event_breakpoint(), delete_breakpoint(), jit_objfile_data::descriptor, fprintf_unfiltered(), gdb_stdlog, get_jit_objfile_data(), jit_break_name, jit_program_space_data::jit_breakpoint, jit_debug, jit_descriptor_name, lookup_minimal_symbol(), lookup_minimal_symbol_and_objfile(), bound_minimal_symbol::minsym, bound_minimal_symbol::objfile, jit_program_space_data::objfile, paddress(), jit_objfile_data::register_code, and SYMBOL_VALUE_ADDRESS.
Referenced by jit_breakpoint_re_set(), and jit_inferior_init().
static void jit_dealloc_cache (struct frame_info * this_frame, void * cache) [static]
Definition at line 1140 of file jit.c.
References gdb_reg_value::free, gdb_assert, gdbarch_num_regs(), get_frame_arch(), jit_unwind_private::registers, jit_unwind_private::this_frame, and xfree().
Referenced by jit_frame_sniffer().
void jit_event_handler (struct gdbarch * gdbarch)
Definition at line 1389 of file jit.c.
References _, jit_descriptor::action_flag, error(), get_jit_program_space_data(), jit_find_objf_with_entry_addr(), JIT_NOACTION, jit_read_code_entry(), jit_read_descriptor(), JIT_REGISTER, jit_register_code(), JIT_UNREGISTER, jit_unregister_code(), paddress(), printf_unfiltered(), and jit_descriptor::relevant_entry.
Referenced by handle_jit_event().
static struct objfile* jit_find_objf_with_entry_addr (CORE_ADDR entry_addr) [static, read]
Definition at line 972 of file jit.c.
References jit_objfile_data::addr, and ALL_OBJFILES.
Referenced by jit_event_handler(), and jit_inferior_init().
static struct value* jit_frame_prev_register (struct frame_info * this_frame, void ** cache, int reg) [static, read]
Definition at line 1245 of file jit.c.
References gdb_reg_value::defined, frame_unwind_got_bytes(), frame_unwind_got_optimized(), gdb_assert, jit_unwind_private::registers, and gdb_reg_value::value.
static int jit_frame_sniffer (const struct frame_unwind * self, struct frame_info * this_frame, void ** cache) [static]
Definition at line 1166 of file jit.c.
References _, fprintf_unfiltered(), jit_reader::functions, gdb_assert, gdb_stdlog, GDB_SUCCESS, gdbarch_num_regs(), get_frame_arch(), jit_dealloc_cache(), jit_debug, jit_target_read_impl(), jit_unwind_reg_get_impl(), jit_unwind_reg_set_impl(), loaded_jit_reader, gdb_unwind_callbacks::priv_data, gdb_reader_funcs::priv_data, gdb_unwind_callbacks::reg_get, gdb_unwind_callbacks::reg_set, jit_unwind_private::registers, gdb_unwind_callbacks::target_read, jit_unwind_private::this_frame, gdb_reader_funcs::unwind, XCALLOC, and XZALLOC.
static void jit_frame_this_id (struct frame_info * this_frame, void ** cache, struct frame_id * this_id) [static]
Definition at line 1216 of file jit.c.
References gdb_frame_id::code_address, frame_id_build(), jit_reader::functions, gdb_assert, gdb_reader_funcs::get_frame_id, jit_target_read_impl(), jit_unwind_reg_get_impl(), loaded_jit_reader, gdb_unwind_callbacks::priv_data, gdb_unwind_callbacks::reg_get, gdb_unwind_callbacks::reg_set, gdb_frame_id::stack_address, and gdb_unwind_callbacks::target_read.
static void* jit_gdbarch_data_init (struct obstack * obstack) [static]
Definition at line 1450 of file jit.c.
References jit_gdbarch_data_type::unwinder_registered.
void jit_inferior_created_hook (void)
Definition at line 1353 of file jit.c.
References jit_inferior_init(), and target_gdbarch().
Referenced by follow_exec().
static void jit_inferior_exit_hook (struct inferior * inf) [static]
Definition at line 1373 of file jit.c.
References jit_objfile_data::addr, ALL_OBJFILES_SAFE, and jit_unregister_code().
static void jit_inferior_init (struct gdbarch * gdbarch) [static]
Definition at line 1303 of file jit.c.
References _, jit_descriptor::first_entry, fprintf_unfiltered(), gdb_stdlog, get_jit_program_space_data(), jit_breakpoint_re_set_internal(), jit_debug, jit_find_objf_with_entry_addr(), jit_prepend_unwinder(), jit_read_code_entry(), jit_read_descriptor(), jit_register_code(), jit_code_entry::next_entry, printf_unfiltered(), and jit_descriptor::version.
Referenced by jit_inferior_created_hook().
static void jit_object_close_impl (struct gdb_symbol_callbacks * cb, struct gdb_object * obj) [static]
Definition at line 779 of file jit.c.
References add_objfile_entry(), allocate_objfile(), finalize_symtab(), objfile_per_bfd_storage::gdbarch, gdb_symtab::next, OBJF_NOT_FILENAME, objfile::per_bfd, gdb_symbol_callbacks::priv_data, gdb_object::symtabs, target_gdbarch(), terminate_minimal_symbol_table(), and xfree().
Referenced by jit_reader_try_read_symtab().
static struct gdb_object* jit_object_open_impl (struct gdb_symbol_callbacks * cb) [static, read]
Definition at line 502 of file jit.c.
References XZALLOC.
Referenced by jit_reader_try_read_symtab().
static void jit_prepend_unwinder (struct gdbarch * gdbarch) [static]
Definition at line 1288 of file jit.c.
References frame_unwind_prepend_unwinder(), gdbarch_data(), and jit_gdbarch_data_type::unwinder_registered.
Referenced by jit_inferior_init().
static void jit_program_space_data_cleanup (struct program_space * ps, void * arg) [static]
Definition at line 330 of file jit.c.
References xfree().
static void jit_read_code_entry (struct gdbarch * gdbarch, CORE_ADDR code_addr, struct jit_code_entry * code_entry) [static]
Definition at line 392 of file jit.c.
References _, builtin_type::builtin_data_ptr, builtin_type(), error(), extract_typed_address(), extract_unsigned_integer(), gdbarch_byte_order(), gdbarch_long_long_align_bit(), jit_code_entry::next_entry, jit_code_entry::prev_entry, jit_code_entry::symfile_addr, jit_code_entry::symfile_size, target_read_memory(), and TYPE_LENGTH.
Referenced by jit_event_handler(), and jit_inferior_init().
static int jit_read_descriptor (struct gdbarch * gdbarch, struct jit_descriptor * descriptor, struct jit_program_space_data * ps_data) [static]
Definition at line 339 of file jit.c.
References _, jit_descriptor::action_flag, builtin_type::builtin_data_ptr, builtin_type(), jit_objfile_data::descriptor, extract_typed_address(), extract_unsigned_integer(), jit_descriptor::first_entry, fprintf_unfiltered(), gdb_stdlog, gdbarch_byte_order(), get_jit_objfile_data(), jit_debug, jit_program_space_data::objfile, paddress(), printf_unfiltered(), jit_descriptor::relevant_entry, SYMBOL_VALUE_ADDRESS, target_read_memory(), TYPE_LENGTH, and jit_descriptor::version.
Referenced by jit_event_handler(), and jit_inferior_init().
static struct jit_reader* jit_reader_load (const char * file_name) [static, read]
Definition at line 166 of file jit.c.
References _, discard_cleanups(), error(), fprintf_unfiltered(), jit_reader::functions, gdb_dlopen(), gdb_dlsym(), GDB_READER_INTERFACE_VERSION, gdb_stdlog, jit_reader::handle, jit_debug, make_cleanup_dlclose(), gdb_reader_funcs::reader_version, and XZALLOC.
Referenced by jit_reader_load_command().
static void jit_reader_load_command (char * args, int from_tty) [static]
Definition at line 203 of file jit.c.
References _, do_cleanups(), error(), jit_reader_dir, jit_reader_load(), loaded_jit_reader, make_cleanup(), xfree(), and xstrprintf().
static int jit_reader_try_read_symtab (struct jit_code_entry * code_entry, CORE_ADDR entry_addr) [static]
Definition at line 809 of file jit.c.
References fprintf_unfiltered(), jit_reader::functions, gdb_stdlog, GDB_SUCCESS, jit_block_open_impl(), jit_debug, jit_object_close_impl(), jit_object_open_impl(), jit_symtab_close_impl(), jit_symtab_line_mapping_add_impl(), jit_symtab_open_impl(), jit_target_read_impl(), loaded_jit_reader, gdb_reader_funcs::read, gdb_exception::reason, RETURN_MASK_ALL, exsummary::status, jit_code_entry::symfile_addr, jit_code_entry::symfile_size, target_read_memory(), TRY_CATCH, xfree(), and xmalloc().
Referenced by jit_register_code().
static void jit_reader_unload_command (char * args, int from_tty) [static]
Definition at line 227 of file jit.c.
References _, gdb_reader_funcs::destroy, error(), jit_reader::functions, gdb_dlclose(), jit_reader::handle, loaded_jit_reader, and xfree().
static void jit_register_code (struct gdbarch * gdbarch, CORE_ADDR entry_addr, struct jit_code_entry * code_entry) [static]
Definition at line 942 of file jit.c.
References fprintf_unfiltered(), gdb_stdlog, jit_bfd_try_read_symtab(), jit_debug, jit_reader_try_read_symtab(), paddress(), pulongest(), jit_code_entry::symfile_addr, and jit_code_entry::symfile_size.
Referenced by jit_event_handler(), and jit_inferior_init().
static void jit_symtab_close_impl (struct gdb_symbol_callbacks * cb, struct gdb_symtab * stab) [static]
Definition at line 622 of file jit.c.
Referenced by jit_reader_try_read_symtab().
static void jit_symtab_line_mapping_add_impl (struct gdb_symbol_callbacks * cb, struct gdb_symtab * stab, int nlines, struct gdb_line_mapping * map) [static]
Definition at line 599 of file jit.c.
References linetable::item, gdb_line_mapping::line, linetable_entry::line, gdb_symtab::linetable, linetable::nitems, linetable_entry::pc, and xmalloc().
Referenced by jit_reader_try_read_symtab().
static struct gdb_symtab* jit_symtab_open_impl (struct gdb_symbol_callbacks * cb, struct gdb_object * object, const char * file_name) [static, read]
Definition at line 514 of file jit.c.
References gdb_symtab::file_name, gdb_symtab::next, and XZALLOC.
Referenced by jit_reader_try_read_symtab().
static enum gdb_status jit_target_read_impl (GDB_CORE_ADDR target_mem, void * gdb_buf, int len) [static]
Definition at line 488 of file jit.c.
References GDB_FAIL, GDB_SUCCESS, and target_read_memory().
Referenced by jit_frame_sniffer(), jit_frame_this_id(), and jit_reader_try_read_symtab().
static void jit_unregister_code (struct objfile * objfile) [static]
Definition at line 964 of file jit.c.
References free_objfile().
Referenced by jit_event_handler(), and jit_inferior_exit_hook().
static struct gdb_reg_value* jit_unwind_reg_get_impl (struct gdb_unwind_callbacks * cb, int regnum) [static, read]
Definition at line 1116 of file jit.c.
References gdb_reg_value::defined, deprecated_frame_register_read(), gdb_reg_value::free, gdbarch_dwarf2_reg_to_regnum(), get_frame_arch(), gdb_unwind_callbacks::priv_data, reg_value_free_impl(), register_size(), gdb_reg_value::size, size, jit_unwind_private::this_frame, gdb_reg_value::value, and xmalloc().
Referenced by jit_frame_sniffer(), and jit_frame_this_id().
static void jit_unwind_reg_set_impl (struct gdb_unwind_callbacks * cb, int dwarf_regnum, struct gdb_reg_value * value) [static]
Definition at line 1084 of file jit.c.
References _, fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_dwarf2_reg_to_regnum(), get_frame_arch(), jit_debug, gdb_unwind_callbacks::priv_data, jit_unwind_private::registers, and jit_unwind_private::this_frame.
Referenced by jit_frame_sniffer().
static int mem_bfd_iovec_close (struct bfd * abfd, void * stream) [static]
Definition at line 90 of file jit.c.
References xfree().
Referenced by bfd_open_from_target_memory().
static void* mem_bfd_iovec_open (struct bfd * abfd, void * open_closure) [static]
Definition at line 82 of file jit.c.
Referenced by bfd_open_from_target_memory().
static file_ptr mem_bfd_iovec_pread (struct bfd * abfd, void * stream, void * buf, file_ptr nbytes, file_ptr offset) [static]
Definition at line 102 of file jit.c.
References target_buffer::base, offset, target_buffer::size, and target_read_memory().
Referenced by bfd_open_from_target_memory().
static int mem_bfd_iovec_stat (struct bfd * abfd, void * stream, struct stat * sb) [static]
Definition at line 126 of file jit.c.
References target_buffer::size.
Referenced by bfd_open_from_target_memory().
static void reg_value_free_impl (struct gdb_reg_value * value) [static]
Definition at line 1108 of file jit.c.
References xfree().
Referenced by jit_unwind_reg_get_impl().
static void show_jit_debug (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 67 of file jit.c.
References _, and fprintf_filtered().
Variable Documentation
const char* const jit_break_name = "__jit_debug_register_code" [static]
Definition at line 48 of file jit.c.
Referenced by jit_breakpoint_re_set_internal().
unsigned int jit_debug = 0 [static]
Definition at line 64 of file jit.c.
Referenced by jit_bfd_try_read_symtab(), jit_breakpoint_re_set_internal(), jit_frame_sniffer(), jit_inferior_init(), jit_read_descriptor(), jit_reader_load(), jit_reader_try_read_symtab(), jit_register_code(), and jit_unwind_reg_set_impl().
const char* const jit_descriptor_name = "__jit_debug_descriptor" [static]
Definition at line 50 of file jit.c.
Referenced by jit_breakpoint_re_set_internal().
struct frame_unwind jit_frame_unwind [static]
Initial value:
{
  NORMAL_FRAME,
  default_frame_unwind_stop_reason,
  jit_frame_this_id,
  jit_frame_prev_register,
  NULL,
  jit_frame_sniffer,
  jit_dealloc_cache
}
Definition at line 1264 of file jit.c.
struct gdbarch_data* jit_gdbarch_data [static]
Definition at line 60 of file jit.c.
struct objfile_data* jit_objfile_data [static]
Definition at line 46 of file jit.c.
struct program_space_data* jit_program_space_data = NULL [static]
Definition at line 52 of file jit.c.
const char* jit_reader_dir = NULL [static]
Definition at line 44 of file jit.c.
Referenced by jit_reader_load_command().
struct jit_reader * loaded_jit_reader [static]
Referenced by jit_frame_sniffer(), jit_frame_this_id(), jit_reader_load_command(), jit_reader_try_read_symtab(), and jit_reader_unload_command().
const char* reader_init_fn_sym = "gdb_init_reader" [static]
Definition at line 161 of file jit.c.