GDB (xrefs): /home/stan/gdb/src/gdb/jit.h File Reference
/home/stan/gdb/src/gdb/jit.h File Reference
Classes
struct jit_code_entry
struct jit_descriptor
Enumerations
enum jit_actions_t { JIT_NOACTION = 0, JIT_REGISTER, JIT_UNREGISTER }
Functions
void jit_inferior_created_hook (void)
void jit_breakpoint_re_set (void)
void jit_event_handler (struct gdbarch *gdbarch)
Enumeration Type Documentation
enum jit_actions_t
Enumerator:
JIT_NOACTION
JIT_REGISTER
JIT_UNREGISTER
Definition at line 27 of file jit.h.
Function Documentation
void jit_breakpoint_re_set (void)
Definition at line 1362 of file jit.c.
References get_jit_program_space_data(), jit_breakpoint_re_set_internal(), and target_gdbarch().
Referenced by breakpoint_re_set().
void jit_event_handler (struct gdbarch * gdbarch)
Definition at line 1389 of file jit.c.
References _, jit_descriptor::action_flag, error(), get_jit_program_space_data(), jit_find_objf_with_entry_addr(), JIT_NOACTION, jit_read_code_entry(), jit_read_descriptor(), JIT_REGISTER, jit_register_code(), JIT_UNREGISTER, jit_unregister_code(), paddress(), printf_unfiltered(), and jit_descriptor::relevant_entry.
Referenced by handle_jit_event().
void jit_inferior_created_hook (void)
Definition at line 1353 of file jit.c.
References jit_inferior_init(), and target_gdbarch().
Referenced by follow_exec().