GDB (xrefs): /home/stan/gdb/src/gdb/jv-lang.h File Reference
/home/stan/gdb/src/gdb/jv-lang.h File Reference
Classes
struct builtin_java_type
Functions
int java_parse (void)
void java_error (char *)
struct builtin_java_type * builtin_java_type (struct gdbarch *)
void java_val_print (struct type *, const gdb_byte *, int, CORE_ADDR, struct ui_file *, int, const struct value *, const struct value_print_options *)
void java_value_print (struct value *, struct ui_file *, const struct value_print_options *)
struct value * java_class_from_object (struct value *)
struct type * type_from_class (struct gdbarch *, struct value *)
struct type * java_primitive_type (struct gdbarch *, int signature)
struct type * java_primitive_type_from_name (struct gdbarch *, const char *, int)
struct type * java_array_type (struct type *, int)
struct type * get_java_object_type (void)
int get_java_object_header_size (struct gdbarch *)
struct type * java_lookup_class (char *)
int is_object_type (struct type *)
void java_print_type (struct type *, const char *, struct ui_file *, int, int, const struct type_print_options *)
char * java_demangle_type_signature (const char *)
Function Documentation
struct builtin_java_type* builtin_java_type (struct gdbarch *) [read]
Definition at line 1233 of file jv-lang.c.
References gdbarch_data().
Referenced by build_java_types(), java_language_arch_info(), java_primitive_type(), java_primitive_type_from_name(), and java_value_print().
int get_java_object_header_size (struct gdbarch *)
Definition at line 601 of file jv-lang.c.
References gdbarch_ptr_bit(), get_java_object_type(), and TYPE_LENGTH.
Referenced by evaluate_subexp_java(), and java_value_print().
struct type* get_java_object_type (void) [read]
Definition at line 590 of file jv-lang.c.
References _, error(), lookup_symbol(), STRUCT_DOMAIN, and SYMBOL_TYPE.
Referenced by get_java_object_header_size(), java_class_from_object(), and java_link_class_type().
int is_object_type (struct type *)
Definition at line 612 of file jv-lang.c.
References check_typedef(), CHECK_TYPEDEF, name, TYPE_BASECLASS, TYPE_CODE, TYPE_CODE_PTR, TYPE_CODE_STRUCT, TYPE_FIELD_NAME, TYPE_N_BASECLASSES, TYPE_NFIELDS, TYPE_TAG_NAME, and TYPE_TARGET_TYPE.
Referenced by evaluate_subexp_java(), and java_value_print().
struct type* java_array_type (struct type * , int) [read]
Definition at line 820 of file jv-lang.c.
References lookup_array_range_type(), and type.
struct value* java_class_from_object (struct value *) [read]
Definition at line 234 of file jv-lang.c.
References get_java_object_type(), TYPE_CODE, TYPE_CODE_PTR, TYPE_LENGTH, TYPE_TARGET_TYPE, value_as_address(), value_at(), value_struct_elt(), and value_type().
Referenced by evaluate_subexp_java(), and java_value_print().
char* java_demangle_type_signature (const char *)
Definition at line 806 of file jv-lang.c.
References java_demangled_signature_copy(), java_demangled_signature_length(), and xmalloc().
Referenced by java_type_print_base().
void java_error (char *)
struct type* java_lookup_class (char *) [read]
Definition at line 202 of file jv-lang.c.
References expression_context_block, lookup_symbol(), STRUCT_DOMAIN, and SYMBOL_TYPE.
Referenced by java_type_from_name(), push_expression_name(), push_qualified_expression_name(), and type_from_class().
int java_parse (void)
struct type* java_primitive_type (struct gdbarch * , int signature) [read]
Definition at line 635 of file jv-lang.c.
References _, builtin_java_type::builtin_boolean, builtin_java_type::builtin_byte, builtin_java_type::builtin_char, builtin_java_type::builtin_double, builtin_java_type::builtin_float, builtin_java_type::builtin_int, builtin_java_type(), builtin_java_type::builtin_long, builtin_java_type::builtin_short, builtin_java_type::builtin_void, and error().
Referenced by type_from_class().
struct type* java_primitive_type_from_name (struct gdbarch * , const char * , int) [read]
Definition at line 667 of file jv-lang.c.
References builtin_java_type::builtin_boolean, builtin_java_type::builtin_byte, builtin_java_type::builtin_char, builtin_java_type::builtin_double, builtin_java_type::builtin_float, builtin_java_type::builtin_int, builtin_java_type(), builtin_java_type::builtin_long, builtin_java_type::builtin_short, builtin_java_type::builtin_void, and memcmp().
Referenced by java_value_print().
void java_print_type (struct type * , const char * , struct ui_file * , int , int , const struct type_print_options *)
Definition at line 337 of file jv-typeprint.c.
References c_type_print_varspec_suffix(), fputs_filtered(), java_type_print_base(), and strchr().
Referenced by c_type_print_args(), dwarf2_compute_name(), and java_type_print_base().
void java_val_print (struct type * , const gdb_byte * , int , CORE_ADDR , struct ui_file * , int , const struct value * , const struct value_print_options *)
Definition at line 467 of file jv-valprint.c.
References value_print_options::addressprint, c_val_print(), check_typedef(), CHECK_TYPEDEF, demangle, value_print_options::format, fputs_filtered(), get_type_arch(), java_print_value_fields(), LA_PRINT_CHAR, value_print_options::output_format, print_address_demangle(), print_longest(), TYPE_CODE, TYPE_CODE_CHAR, TYPE_CODE_FUNC, TYPE_CODE_INT, TYPE_CODE_PTR, TYPE_CODE_STRUCT, TYPE_LENGTH, TYPE_NAME, TYPE_TARGET_TYPE, ULONGEST, unpack_long(), unpack_pointer(), val_print_scalar_formatted(), and val_print_type_code_int().
void java_value_print (struct value * , struct ui_file * , const struct value_print_options *)
Definition at line 37 of file jv-valprint.c.
References allocate_value(), builtin_java_type::builtin_char, builtin_java_type(), gdbarch::byte_order, common_val_print(), current_language, value_print_options::deref_ref, extract_signed_integer(), extract_unsigned_integer(), value_print_options::format, fprintf_filtered(), fputs_filtered(), gdbarch_byte_order(), gdbarch_ptr_bit(), get_java_object_header_size(), get_type_arch(), HOST_CHAR_BIT, is_object_type(), java_class_from_object(), java_primitive_type_from_name(), type::length, gdb::printing::long, lookup_pointer_type(), n_spaces(), name, paddress(), read_memory(), set_value_address(), set_value_lazy(), set_value_offset(), type, TYPE_CODE, TYPE_CODE_PTR, TYPE_CODE_STRUCT, type_from_class(), TYPE_LENGTH, type_print(), TYPE_TAG_NAME, TYPE_TARGET_TYPE, val_print_string(), value_address(), value_as_address(), value_at(), value_available_contents_eq(), value_embedded_offset(), value_fetch_lazy(), value_free_to_mark(), value_ind(), value_logical_not(), value_mark(), value_offset(), value_raw_address(), value_struct_elt(), value_type(), and wrap_here().
struct type* type_from_class (struct gdbarch * , struct value *) [read]
Definition at line 263 of file jv-lang.c.
References add_class_symbol(), add_class_symtab_symbol(), alloc_type(), ALLOCATE_CPLUS_STRUCT_TYPE, check_typedef(), deprecated_set_value_type(), get_dynamics_objfile(), get_java_utf8_name(), INIT_CPLUS_SPECIFIC, java_class_is_primitive(), java_demangled_signature_copy(), java_demangled_signature_length(), java_link_class_type(), java_lookup_class(), java_primitive_type(), lookup_pointer_type(), name, objfile::objfile_obstack, type, TYPE_CODE, TYPE_CODE_PTR, TYPE_CODE_STRUCT, type_from_class(), TYPE_TAG_NAME, TYPE_TARGET_TYPE, value_address(), value_as_long(), value_ind(), value_logical_not(), value_struct_elt(), and value_type().
Referenced by evaluate_subexp_java(), java_link_class_type(), java_value_print(), and type_from_class().