GDB (xrefs): /home/stan/gdb/src/gdb/jv-typeprint.c File Reference
/home/stan/gdb/src/gdb/jv-typeprint.c File Reference
#include "defs.h"
#include "symtab.h"
#include "gdbtypes.h"
#include "value.h"
#include "demangle.h"
#include "gdb-demangle.h"
#include "jv-lang.h"
#include "gdb_string.h"
#include "typeprint.h"
#include "c-lang.h"
#include "cp-abi.h"
#include "cp-support.h"
#include "gdb_assert.h"
Functions
static void java_type_print_base (struct type *type, struct ui_file *stream, int show, int level, const struct type_print_options *flags)
static void java_type_print_derivation_info (struct ui_file *stream, struct type *type)
void java_print_type (struct type *type, const char *varstring, struct ui_file *stream, int show, int level, const struct type_print_options *flags)
Function Documentation
void java_print_type (struct type * type, const char * varstring, struct ui_file * stream, int show, int level, const struct type_print_options * flags)
Definition at line 337 of file jv-typeprint.c.
References c_type_print_varspec_suffix(), fputs_filtered(), java_type_print_base(), and strchr().
Referenced by c_type_print_args(), dwarf2_compute_name(), and java_type_print_base().
static void java_type_print_base (struct type * type, struct ui_file * stream, int show, int level, const struct type_print_options * flags) [static]
Definition at line 88 of file jv-typeprint.c.
References c_type_print_base(), CHECK_TYPEDEF, field_is_static(), fprintf_filtered(), fprintfi_filtered(), fputs_filtered(), gdb_assert, gdb_demangle(), gdb_mangle_name(), HAVE_CPLUS_STRUCT, cleanup_check::is_constructor(), is_constructor_name(), is_cplus_marker(), is_destructor_name(), java_demangle_type_signature(), java_print_type(), java_type_print_derivation_info(), len, memcpy(), name, p, print_spaces_filtered(), QUIT, strrchr(), TYPE_CODE, TYPE_CODE_PTR, TYPE_CODE_STRUCT, TYPE_FIELD, TYPE_FIELD_NAME, TYPE_FIELD_PRIVATE, TYPE_FIELD_PROTECTED, TYPE_FIELD_TYPE, TYPE_FN_FIELD_ABSTRACT, TYPE_FN_FIELD_CONSTRUCTOR, TYPE_FN_FIELD_FINAL, TYPE_FN_FIELD_NATIVE, TYPE_FN_FIELD_PHYSNAME, TYPE_FN_FIELD_PRIVATE, TYPE_FN_FIELD_PROTECTED, TYPE_FN_FIELD_PUBLIC, TYPE_FN_FIELD_STATIC, TYPE_FN_FIELD_STUB, TYPE_FN_FIELD_SYNCHRONIZED, TYPE_FN_FIELD_TYPE, TYPE_FN_FIELDLIST1, TYPE_FN_FIELDLIST_LENGTH, TYPE_FN_FIELDLIST_NAME, TYPE_N_BASECLASSES, TYPE_NAME, type_name_no_tag(), TYPE_NFIELDS, TYPE_NFN_FIELDS, type_print(), TYPE_STUB, TYPE_TAG_NAME, TYPE_TARGET_TYPE, wrap_here(), and xfree().
Referenced by java_print_type().
static void java_type_print_derivation_info (struct ui_file * stream, struct type * type) [static]
Definition at line 42 of file jv-typeprint.c.
References BASETYPE_VIA_VIRTUAL, fprintf_filtered(), fputs_filtered(), name, TYPE_BASECLASS, TYPE_N_BASECLASSES, and type_name_no_tag().
Referenced by java_type_print_base().