GDB (xrefs): /home/stan/gdb/src/gdb/jv-valprint.c File Reference
/home/stan/gdb/src/gdb/jv-valprint.c File Reference
#include "defs.h"
#include "symtab.h"
#include "gdbtypes.h"
#include "gdbcore.h"
#include "expression.h"
#include "value.h"
#include "demangle.h"
#include "valprint.h"
#include "language.h"
#include "jv-lang.h"
#include "c-lang.h"
#include "annotate.h"
#include "gdb_string.h"
Functions
void java_value_print (struct value *val, struct ui_file *stream, const struct value_print_options *options)
static void java_print_value_fields (struct type *type, const gdb_byte *valaddr, int offset, CORE_ADDR address, struct ui_file *stream, int recurse, const struct value *val, const struct value_print_options *options)
void java_val_print (struct type *type, const gdb_byte *valaddr, int embedded_offset, CORE_ADDR address, struct ui_file *stream, int recurse, const struct value *val, const struct value_print_options *options)
Function Documentation
static void java_print_value_fields (struct type * type, const gdb_byte * valaddr, int offset, CORE_ADDR address, struct ui_file * stream, int recurse, const struct value * val, const struct value_print_options * options) [static]
Definition at line 268 of file jv-valprint.c.
References _, annotate_field_begin(), annotate_field_end(), annotate_field_name_end(), annotate_field_value(), BASETYPE_VIA_VIRTUAL, check_typedef(), CHECK_TYPEDEF, common_val_print(), current_language, value_print_options::deref_ref, field_is_static(), fprintf_filtered(), fprintf_symbol_filtered(), fputs_filtered(), language_cplus, len, n_spaces(), name, value_print_options::prettyformat, print_spaces_filtered(), value_print_options::static_field_print, TYPE_BASECLASS, TYPE_CODE, TYPE_CODE_STRUCT, TYPE_FIELD, TYPE_FIELD_BITPOS, TYPE_FIELD_BITSIZE, TYPE_FIELD_IGNORE, TYPE_FIELD_NAME, TYPE_FIELD_PACKED, TYPE_FIELD_TYPE, TYPE_N_BASECLASSES, TYPE_NAME, type_name_no_tag(), TYPE_NFIELDS, val_print(), val_print_optimized_out(), value_addr(), value_bits_synthetic_pointer(), value_bits_valid(), value_field_bitfield(), value_static_field(), value_type(), and wrap_here().
Referenced by java_val_print().
void java_val_print (struct type * type, const gdb_byte * valaddr, int embedded_offset, CORE_ADDR address, struct ui_file * stream, int recurse, const struct value * val, const struct value_print_options * options)
Definition at line 467 of file jv-valprint.c.
References value_print_options::addressprint, c_val_print(), check_typedef(), CHECK_TYPEDEF, demangle, value_print_options::format, fputs_filtered(), get_type_arch(), java_print_value_fields(), LA_PRINT_CHAR, value_print_options::output_format, print_address_demangle(), print_longest(), TYPE_CODE, TYPE_CODE_CHAR, TYPE_CODE_FUNC, TYPE_CODE_INT, TYPE_CODE_PTR, TYPE_CODE_STRUCT, TYPE_LENGTH, TYPE_NAME, TYPE_TARGET_TYPE, ULONGEST, unpack_long(), unpack_pointer(), val_print_scalar_formatted(), and val_print_type_code_int().
void java_value_print (struct value * val, struct ui_file * stream, const struct value_print_options * options)
Definition at line 37 of file jv-valprint.c.
References allocate_value(), builtin_java_type::builtin_char, builtin_java_type(), gdbarch::byte_order, common_val_print(), current_language, value_print_options::deref_ref, extract_signed_integer(), extract_unsigned_integer(), value_print_options::format, fprintf_filtered(), fputs_filtered(), gdbarch_byte_order(), gdbarch_ptr_bit(), get_java_object_header_size(), get_type_arch(), HOST_CHAR_BIT, is_object_type(), java_class_from_object(), java_primitive_type_from_name(), type::length, gdb::printing::long, lookup_pointer_type(), n_spaces(), name, paddress(), read_memory(), set_value_address(), set_value_lazy(), set_value_offset(), type, TYPE_CODE, TYPE_CODE_PTR, TYPE_CODE_STRUCT, type_from_class(), TYPE_LENGTH, type_print(), TYPE_TAG_NAME, TYPE_TARGET_TYPE, val_print_string(), value_address(), value_as_address(), value_at(), value_available_contents_eq(), value_embedded_offset(), value_fetch_lazy(), value_free_to_mark(), value_ind(), value_logical_not(), value_mark(), value_offset(), value_raw_address(), value_struct_elt(), value_type(), and wrap_here().