GDB (xrefs): /home/stan/gdb/src/gdb/language.h File Reference
/home/stan/gdb/src/gdb/language.h File Reference
Classes
struct language_arch_info
struct language_defn
Defines
#define MAX_FORTRAN_DIMS 7 /* Maximum number of F77 array dims. */
#define LANG_MAGIC 910823L
#define RANGE_CHECK (range_check != range_check_off)
#define CAST_IS_CONVERSION(LANG)
#define LA_PRINT_TYPE(type, varstring, stream, show, level, flags) (current_language->la_print_type(type,varstring,stream,show,level,flags))
#define LA_PRINT_TYPEDEF(type, new_symbol, stream) (current_language->la_print_typedef(type,new_symbol,stream))
#define LA_VAL_PRINT(type, valaddr, offset, addr, stream, val, recurse, options)
#define LA_VALUE_PRINT(val, stream, options) (current_language->la_value_print(val,stream,options))
#define LA_PRINT_CHAR(ch, type, stream) (current_language->la_printchar(ch, type, stream))
#define LA_PRINT_STRING(stream, elttype, string, length, encoding, force_ellipses, options)
#define LA_EMIT_CHAR(ch, type, stream, quoter) (current_language->la_emitchar(ch, type, stream, quoter))
#define LA_GET_STRING(value, buffer, length, chartype, encoding) (current_language->la_get_string(value, buffer, length, chartype, encoding))
#define LA_PRINT_ARRAY_INDEX(index_value, stream, options) (current_language->la_print_array_index(index_value, stream, options))
#define LA_ITERATE_OVER_SYMBOLS(BLOCK, NAME, DOMAIN, CALLBACK, DATA)
#define PRINT_LITERAL_FORM(c)
#define unop_type_check(v, o) binop_type_check((v),NULL,(o))
Typedefs
typedef int(* symbol_name_cmp_ftype)(const char *symbol_search_name, const char *lookup_name)
Enumerations
enum range_mode { range_mode_auto, range_mode_manual }
enum range_check { range_check_off, range_check_warn, range_check_on }
enum case_mode { case_mode_auto, case_mode_manual }
enum array_ordering { array_row_major, array_column_major }
enum case_sensitivity { case_sensitive_on, case_sensitive_off }
enum macro_expansion { macro_expansion_no, macro_expansion_c }
enum language_mode { language_mode_auto, language_mode_manual }
Functions
struct type * language_bool_type (const struct language_defn *l, struct gdbarch *gdbarch)
struct type * language_string_char_type (const struct language_defn *l, struct gdbarch *gdbarch)
struct type * language_lookup_primitive_type_by_name (const struct language_defn *l, struct gdbarch *gdbarch, const char *name)
void language_info (int)
enum language set_language (enum language)
int pointer_type (struct type *)
void binop_type_check (struct value *, struct value *, int)
void range_error (const char *,...) ATTRIBUTE_PRINTF(1
void int value_true (struct value *)
enum language language_enum (char *str)
struct language_defn * language_def (enum language)
char * language_str (enum language)
void add_language (const struct language_defn *)
enum language get_frame_language (void)
CORE_ADDR skip_language_trampoline (struct frame_info *, CORE_ADDR pc)
char * language_demangle (const struct language_defn *current_language, const char *mangled, int options)
char * language_class_name_from_physname (const struct language_defn *, const char *physname)
char * default_word_break_characters (void)
void default_print_array_index (struct value *index_value, struct ui_file *stream, const struct value_print_options *options)
int language_pass_by_reference (struct type *type)
int default_pass_by_reference (struct type *type)
void default_print_typedef (struct type *type, struct symbol *new_symbol, struct ui_file *stream)
void default_get_string (struct value *value, gdb_byte **buffer, int *length, struct type **char_type, const char **charset)
void c_get_string (struct value *value, gdb_byte **buffer, int *length, struct type **char_type, const char **charset)
Variables
enum range_mode range_mode
enum range_check range_check
enum case_mode case_mode
enum array_ordering array_ordering
enum case_sensitivity case_sensitivity
struct language_defn * current_language
struct language_defn * expected_language
enum language_mode language_mode
Define Documentation
#define CAST_IS_CONVERSION (LANG)
Value:
((LANG)->la_language == language_c  || \
                                  (LANG)->la_language == language_cplus || \
                                  (LANG)->la_language == language_objc)
Definition at line 409 of file language.h.
Referenced by evaluate_subexp_with_coercion().
#define LA_EMIT_CHAR (ch, type, stream, quoter) (current_language->la_emitchar(ch, type, stream, quoter))
Definition at line 440 of file language.h.
Referenced by c_printchar(), f_printchar(), java_printchar(), m2_printchar(), m2_printstr(), and print_char_chars().
#define LA_GET_STRING (value, buffer, length, chartype, encoding) (current_language->la_get_string(value, buffer, length, chartype, encoding))
Definition at line 442 of file language.h.
#define LA_ITERATE_OVER_SYMBOLS (BLOCK, NAME, DOMAIN, CALLBACK, DATA)
Value:
(current_language->la_iterate_over_symbols (BLOCK, NAME, DOMAIN, CALLBACK, \
                                              DATA))
Definition at line 448 of file language.h.
Referenced by iterate_over_file_blocks().
#define LA_PRINT_ARRAY_INDEX (index_value, stream, options) (current_language->la_print_array_index(index_value, stream, options))
Definition at line 445 of file language.h.
Referenced by maybe_print_array_index().
#define LA_PRINT_CHAR (ch, type, stream) (current_language->la_printchar(ch, type, stream))
Definition at line 435 of file language.h.
Referenced by ada_print_scalar(), c_val_print(), f_val_print(), generic_val_print(), java_val_print(), and print_type_scalar().
#define LA_PRINT_STRING (stream, elttype, string, length, encoding, force_ellipses, options)
Value:
(current_language->la_printstr(stream, elttype, string, length, \
                                 encoding, force_ellipses,options))
Definition at line 437 of file language.h.
Referenced by c_val_print(), f_val_print(), m2_val_print(), pascal_val_print(), print_subexp_standard(), val_print_string(), and value_get_print_value().
#define LA_PRINT_TYPE (type, varstring, stream, show, level, flags) (current_language->la_print_type(type,varstring,stream,show,level,flags))
Definition at line 423 of file language.h.
Referenced by ada_print_subexp(), print_symbol(), type_print(), typy_str(), and whatis_exp().
#define LA_PRINT_TYPEDEF (type, new_symbol, stream) (current_language->la_print_typedef(type,new_symbol,stream))
Definition at line 426 of file language.h.
Referenced by typedef_print().
#define LA_VAL_PRINT (type, valaddr, offset, addr, stream, val, recurse, options)
Value:
(current_language->la_val_print(type,valaddr,offset,addr,stream, \
                                  val,recurse,options))
Definition at line 429 of file language.h.
#define LA_VALUE_PRINT (val, stream, options) (current_language->la_value_print(val,stream,options))
Definition at line 432 of file language.h.
Referenced by ada_print_array_index(), default_print_array_index(), and value_print().
#define LANG_MAGIC 910823L
Definition at line 354 of file language.h.
Referenced by add_language().
#define MAX_FORTRAN_DIMS 7 /* Maximum number of F77 array dims. */
Definition at line 35 of file language.h.
Referenced by evaluate_subexp_standard(), and f77_print_array().
#define PRINT_LITERAL_FORM (c)
Value:
((c) >= 0x20                            \
   && ((c) < 0x7F || (c) >= 0xA0)       \
   && (!sevenbit_strings || (c) < 0x80))
Definition at line 458 of file language.h.
Referenced by m2_emit_char(), pascal_one_char(), and pascal_printstr().
#define RANGE_CHECK (range_check != range_check_off)
Definition at line 405 of file language.h.
Referenced by parse_number().
#define unop_type_check (v, o) binop_type_check((v),NULL,(o))
Definition at line 469 of file language.h.
Typedef Documentation
typedef int(* symbol_name_cmp_ftype)(const char *symbol_search_name, const char *lookup_name)
Definition at line 125 of file language.h.
Enumeration Type Documentation
enum array_ordering
Enumerator:
array_row_major
array_column_major
Definition at line 72 of file language.h.
enum case_mode
Enumerator:
case_mode_auto
case_mode_manual
Definition at line 62 of file language.h.
enum case_sensitivity
Enumerator:
case_sensitive_on
case_sensitive_off
Definition at line 83 of file language.h.
enum language_mode
Enumerator:
language_mode_auto
language_mode_manual
Definition at line 384 of file language.h.
enum macro_expansion
Enumerator:
macro_expansion_no
macro_expansion_c
Definition at line 94 of file language.h.
enum range_check
Enumerator:
range_check_off
range_check_warn
range_check_on
Definition at line 52 of file language.h.
enum range_mode
Enumerator:
range_mode_auto
range_mode_manual
Definition at line 41 of file language.h.
Function Documentation
void add_language (const struct language_defn *)
Definition at line 519 of file language.c.
References _, add_setshow_enum_cmd(), class_support, DEFAULT_ALLOCSIZE, fprintf_unfiltered(), gdb_stderr, internal_error(), language_defn::la_language, language_defn::la_magic, language_defn::la_name, LANG_MAGIC, language_auto, language_unknown, languages, languages_allocsize, languages_size, mem_fileopen(), set_language_command(), setlist, show_language_command(), showlist, ui_file_delete(), ui_file_xstrdup(), xfree(), xmalloc(), and xrealloc().
Referenced by _initialize_ada_language(), _initialize_d_language(), _initialize_go_language(), and _initialize_objc_language().
void binop_type_check (struct value * , struct value * , int)
void c_get_string (struct value * value, gdb_byte ** buffer, int * length, struct type ** char_type, const char ** charset)
Definition at line 237 of file c-lang.c.
References _, c_textual_element_type(), check_typedef(), classify_type(), error(), extract_unsigned_integer(), gdbarch_byte_order(), get_discrete_bounds(), get_type_arch(), type::length, LONGEST, lval_internalvar, make_cleanup(), memcpy(), memory_error(), not_lval, read_string(), TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_PTR, TYPE_CODE_RANGE, TYPE_FIELD_TYPE, TYPE_LENGTH, TYPE_NFIELDS, TYPE_TARGET_TYPE, type_to_string(), value_as_address(), value_contents(), VALUE_LVAL, value_type(), xfree(), and xmalloc().
void default_get_string (struct value * value, gdb_byte ** buffer, int * length, struct type ** char_type, const char ** charset)
Definition at line 687 of file language.c.
References _, and error().
int default_pass_by_reference (struct type * type)
Definition at line 660 of file language.c.
void default_print_array_index (struct value * index_value, struct ui_file * stream, const struct value_print_options * options)
Definition at line 678 of file language.c.
References fprintf_filtered(), and LA_VALUE_PRINT.
void default_print_typedef (struct type * type, struct symbol * new_symbol, struct ui_file * stream)
Definition at line 349 of file typeprint.c.
References _, and error().
char* default_word_break_characters (void)
Definition at line 670 of file language.c.
Referenced by f_word_break_characters(), and init_main().
enum language get_frame_language (void)
Definition at line 2542 of file stack.c.
References deprecated_safe_get_selected_frame(), gdb_exception::error, find_pc_symtab(), get_frame_address_in_block(), symtab::language, language_unknown, NOT_AVAILABLE_ERROR, gdb_exception::reason, RETURN_MASK_ERROR, throw_exception(), and TRY_CATCH.
Referenced by check_frame_language_change(), set_language_command(), and show_language_command().
struct type* language_bool_type (const struct language_defn * l, struct gdbarch * gdbarch) [read]
Definition at line 955 of file language.c.
References language_gdbarch::arch_info, language_arch_info::bool_type_default, language_arch_info::bool_type_symbol, gdbarch_data(), language_defn::la_language, lookup_symbol(), SYMBOL_TYPE, type, TYPE_CODE, TYPE_CODE_BOOL, and VAR_DOMAIN.
Referenced by evaluate_subexp_opencl(), evaluate_subexp_standard(), opencl_logical_not(), and opencl_relop().
char* language_class_name_from_physname (const struct language_defn * , const char * physname)
Definition at line 640 of file language.c.
References language_defn::la_class_name_from_physname.
Referenced by guess_full_die_structure_name(), and guess_partial_die_structure_name().
struct language_defn* language_def (enum language) [read]
Definition at line 472 of file language.c.
References language_defn::la_language, and languages_size.
Referenced by cp_lookup_symbol_imports_or_template(), extract_sym(), fprintf_symbol_filtered(), gen_expr(), list_arg_or_local(), lookup_symbol_aux(), lookup_symbol_file(), parse_exp_in_context_1(), prepare_one_comp_unit(), print_frame_arg(), process_full_comp_unit(), process_full_type_unit(), py_print_single_arg(), read_var_value(), and set_cu_language().
char* language_demangle (const struct language_defn * current_language, const char * mangled, int options)
Definition at line 630 of file language.c.
References language_defn::la_demangle.
Referenced by fprintf_symbol_filtered(), and maintenance_demangle().
enum language language_enum (char * str)
Definition at line 458 of file language.c.
References language_defn::la_language, language_defn::la_name, language_unknown, and languages_size.
Referenced by set_ext_lang_command().
void language_info (int)
Definition at line 372 of file language.c.
References _, case_sensitive, current_language, printf_unfiltered(), show_case_command(), show_language_command(), and show_range_command().
Referenced by check_frame_language_change().
struct type* language_lookup_primitive_type_by_name (const struct language_defn * l, struct gdbarch * gdbarch, const char * name) [read]
Definition at line 980 of file language.c.
References language_gdbarch::arch_info, gdbarch_data(), language_defn::la_language, p, language_arch_info::primitive_type_vector, and TYPE_NAME.
Referenced by classify_name(), find_primitive_type(), lookup_typename(), type_system_address(), and yylex().
int language_pass_by_reference (struct type * type)
Definition at line 651 of file language.c.
References language_defn::la_pass_by_reference.
Referenced by aarch64_push_dummy_call(), call_function_by_hand(), default_return_in_first_hidden_param_p(), and tic6x_return_value().
char* language_str (enum language)
Definition at line 488 of file language.c.
References language_defn::la_language, language_defn::la_name, and languages_size.
Referenced by dump_symtab_1(), frame_info(), info_ext_lang_command(), and source_info().
struct type* language_string_char_type (const struct language_defn * l, struct gdbarch * gdbarch) [read]
Definition at line 945 of file language.c.
References language_gdbarch::arch_info, gdbarch_data(), language_defn::la_language, and language_arch_info::string_char_type.
Referenced by evaluate_subexp_c(), evaluate_subexp_standard(), read_tag_string_type(), and type_char().
int pointer_type (struct type *)
Definition at line 393 of file language.c.
References TYPE_CODE, TYPE_CODE_PTR, and TYPE_CODE_REF.
Referenced by gen_deref(), gen_equal(), gen_expr(), gen_expr_binop_rest(), gen_less(), gen_ptradd(), gen_ptrdiff(), gen_ptrsub(), gen_struct_ref(), and x_command().
void range_error (const char * , ...)
enum language set_language (enum language)
Definition at line 347 of file language.c.
References language_defn::la_language, languages_size, and set_range_case().
Referenced by breakpoint_re_set(), do_restore_current_language(), dump_symtab(), gdb_init(), get_current_search_block(), parse_exp_in_context_1(), prepare_re_set_context(), select_frame(), set_initial_language(), and set_language_command().
CORE_ADDR skip_language_trampoline (struct frame_info * , CORE_ADDR pc)
Definition at line 605 of file language.c.
References languages_size, and language_defn::skip_trampoline.
Referenced by handle_inferior_event().
void int value_true (struct value *)
Definition at line 405 of file language.c.
References value_logical_not().
Referenced by breakpoint_cond_eval(), execute_control_command(), and should_stop_exception().
Variable Documentation
enum array_ordering array_ordering
enum case_mode case_mode
enum case_sensitivity case_sensitivity
struct language_defn* current_language
Definition at line 86 of file language.c.
Referenced by ada_val_print_1(), ada_value_print(), ada_varobj_get_value_image(), address_info(), allocate_repeat_value(), apply_frame_filter(), bpfinishpy_handle_exit(), bpfinishpy_handle_stop(), breakpoint_re_set(), c_type_print_varspec_suffix(), c_val_print(), c_value_print(), check_frame_language_change(), cmdpy_destroyer(), cmdpy_function(), coerce_array(), cp_print_static_field(), cp_print_value(), cp_print_value_fields(), cp_type_print_method_args(), decode_line_1(), decode_line_full(), default_print_one_register_info(), extract_sym(), f77_print_array_1(), f_val_print(), find_slot_in_mapped_hash(), gdb_eval(), gdb_init(), gdbpy_breakpoint_has_py_cond(), gdbpy_should_stop(), generic_val_print(), get_current_search_block(), get_register(), get_set_value(), get_show_value(), init_raw_breakpoint_without_location(), java_print_value_fields(), java_value_print(), language_info(), language_search_unquoted_string(), line_completion_function(), lookup_minimal_symbol_internal(), lookup_symbol(), lookup_symbol_in_objfile_from_linkage_name(), lookup_transparent_type(), m2_print_array_contents(), m2_val_print(), maintenance_demangle(), make_cleanup_restore_current_language(), mi_cmd_data_evaluate_expression(), mt_registers_info(), op_string(), output_register(), parse_exp_in_context_1(), pascal_object_print_static_field(), pascal_object_print_value_fields(), pascal_val_print(), pascal_value_print(), print_field_values(), print_frame_arg(), print_variable_and_value(), print_variable_at_address(), print_variable_or_computed(), printf_wide_c_string(), psymtab_search_name(), py_free_objfile(), py_free_pspace(), python_inferior_exit(), python_new_objfile(), python_on_normal_stop(), python_on_resume(), save_objfile_types(), select_frame(), set_initial_language(), set_language_command(), sh64_do_register(), skip_quoted_chars(), stap_parse_argument(), tic6x_return_value(), ui_printf(), val_print_array_elements(), val_print_packed_array_elements(), val_print_scalar_formatted(), value_arg_coerce(), value_array(), value_cast(), value_cstring(), value_get_print_value(), value_print(), value_string(), value_subscript(), value_user_defined_op(), VEC(), and wrap_val_print().
struct language_defn* expected_language
Definition at line 92 of file language.c.
Referenced by check_frame_language_change(), gdb_init(), and set_initial_language().
enum language_mode language_mode
enum range_check range_check
enum range_mode range_mode