GDB (xrefs): /home/stan/gdb/src/gdb/linespec.h File Reference
/home/stan/gdb/src/gdb/linespec.h File Reference
#include "vec.h"
Classes
struct linespec_sals
struct linespec_result
Typedefs
typedef struct linespec_sals linespec_sals
Enumerations
enum decode_line_flags { DECODE_LINE_FUNFIRSTLINE = 1, DECODE_LINE_LIST_MODE = 2 }
Functions
DEF_VEC_O (linespec_sals)
void init_linespec_result (struct linespec_result *)
void destroy_linespec_result (struct linespec_result *)
struct cleanup * make_cleanup_destroy_linespec_result (struct linespec_result *)
struct symtabs_and_lines decode_line_1 (char **argptr, int flags, struct symtab *default_symtab, int default_line)
void decode_line_full (char **argptr, int flags, struct symtab *default_symtab, int default_line, struct linespec_result *canonical, const char *select_mode, const char *filter)
struct symtabs_and_lines decode_line_with_current_source (char *, int)
struct symtabs_and_lines decode_line_with_last_displayed (char *, int)
Typedef Documentation
typedef struct linespec_sals linespec_sals
Definition at line 53 of file linespec.h.
Enumeration Type Documentation
enum decode_line_flags
Enumerator:
DECODE_LINE_FUNFIRSTLINE
DECODE_LINE_LIST_MODE
Definition at line 26 of file linespec.h.
Function Documentation
struct symtabs_and_lines decode_line_1 (char ** argptr, int flags, struct symtab * default_symtab, int default_line) [read]
Definition at line 2495 of file linespec.c.
References current_language, do_cleanups(), linespec_parser_delete(), linespec_parser_new(), make_cleanup(), parse_linespec(), and save_current_program_space().
Referenced by decode_line_with_current_source(), decode_line_with_last_displayed(), edit_command(), gdb_get_file_command(), gdb_get_function_command(), gdb_get_line_command(), gdb_get_vars_command(), list_command(), scope_info(), tracepoint_exists(), and until_break_command().
void decode_line_full (char ** argptr, int flags, struct symtab * default_symtab, int default_line, struct linespec_result * canonical, const char * select_mode, const char * filter)
Definition at line 2418 of file linespec.c.
References linespec_result::addr_string, linespec_state::canonical_names, convert_results_to_lsals(), current_language, decode_line_2(), DECODE_LINE_LIST_MODE, do_cleanups(), filter_results(), gdb_assert, interp_ui_out(), linespec_parser_delete(), linespec_parser_new(), make_cleanup(), multiple_symbols_all, multiple_symbols_ask, multiple_symbols_cancel, multiple_symbols_select_mode(), symtabs_and_lines::nelts, parse_linespec(), PARSER_STATE, linespec_result::pre_expanded, save_current_program_space(), linespec_canonical_name::suffix, top_level_interpreter(), ui_out_is_mi_like_p(), VEC, VEC_cleanup, VEC_safe_push, and xfree().
Referenced by agent_command_1(), break_range_command(), decode_linespec_default(), and parse_breakpoint_sals().
struct symtabs_and_lines decode_line_with_current_source (char * , int) [read]
Definition at line 2520 of file linespec.c.
References _, decode_line_1(), error(), get_current_source_symtab_and_line(), symtab_and_line::line, and symtab_and_line::symtab.
Referenced by clear_command(), func_command(), gdb_loc(), info_macros_command(), mi_cmd_trace_find(), select_source_symtab(), and trace_find_line_command().
struct symtabs_and_lines decode_line_with_last_displayed (char * , int) [read]
Definition at line 2543 of file linespec.c.
References _, decode_line_1(), error(), get_last_displayed_line(), get_last_displayed_symtab(), last_displayed_sal_is_valid(), and symtabs_and_lines::sals.
Referenced by jump_command(), and line_info().
DEF_VEC_O (linespec_sals)
void destroy_linespec_result (struct linespec_result *)
Definition at line 3686 of file linespec.c.
References linespec_result::addr_string, linespec_sals::canonical, linespec_sals::sals, symtabs_and_lines::sals, VEC_free, VEC_iterate, and xfree().
Referenced by cleanup_linespec_result(), and decode_linespec_default().
void init_linespec_result (struct linespec_result *)
Definition at line 3678 of file linespec.c.
References memset().
Referenced by agent_command_1(), break_range_command(), create_breakpoint(), and decode_linespec_default().
struct cleanup* make_cleanup_destroy_linespec_result (struct linespec_result *) [read]
Definition at line 3711 of file linespec.c.
References cleanup_linespec_result(), and make_cleanup().
Referenced by agent_command_1(), break_range_command(), and create_breakpoint().