GDB (xrefs): /home/stan/gdb/src/gdb/common/linux-osdata.h File Reference
/home/stan/gdb/src/gdb/common/linux-osdata.h File Reference
#include "ptid.h"
Functions
int linux_common_core_of_thread (ptid_t ptid)
LONGEST linux_common_xfer_osdata (const char *annex, gdb_byte *readbuf, ULONGEST offset, LONGEST len)
Function Documentation
int linux_common_core_of_thread (ptid_t ptid)
Definition at line 67 of file linux-osdata.c.
References gdb_fopen_cloexec(), MAX_PID_T_STRLEN, p, ptid_get_lwp(), ptid_get_pid(), strchr(), xfree(), and xrealloc().
Referenced by get_cores_used_by_process(), linux_nat_wait_1(), linux_xfer_osdata_threads(), and update_thread_core().
LONGEST linux_common_xfer_osdata (const char * annex, gdb_byte * readbuf, ULONGEST offset, LONGEST len)
Definition at line 1551 of file linux-osdata.c.
References buffer_finish(), buffer_free(), buffer_grow_str, buffer_grow_str0, buffer_init(), buffer_xml_printf(), gdb_assert, len, LONGEST, memcpy(), offset, osdata_table, and osdata_type::type.
Referenced by linux_nat_xfer_osdata().