GDB (xrefs): /home/stan/gdb/src/gdb/linux-record.c File Reference
/home/stan/gdb/src/gdb/linux-record.c File Reference
#include "defs.h"
#include "target.h"
#include "gdbtypes.h"
#include "regcache.h"
#include "record.h"
#include "record-full.h"
#include "linux-record.h"
Defines
#define RECORD_PTRACE_PEEKTEXT 1
#define RECORD_PTRACE_PEEKDATA 2
#define RECORD_PTRACE_PEEKUSR 3
#define RECORD_SYS_SOCKET 1
#define RECORD_SYS_BIND 2
#define RECORD_SYS_CONNECT 3
#define RECORD_SYS_LISTEN 4
#define RECORD_SYS_ACCEPT 5
#define RECORD_SYS_GETSOCKNAME 6
#define RECORD_SYS_GETPEERNAME 7
#define RECORD_SYS_SOCKETPAIR 8
#define RECORD_SYS_SEND 9
#define RECORD_SYS_RECV 10
#define RECORD_SYS_SENDTO 11
#define RECORD_SYS_RECVFROM 12
#define RECORD_SYS_SHUTDOWN 13
#define RECORD_SYS_SETSOCKOPT 14
#define RECORD_SYS_GETSOCKOPT 15
#define RECORD_SYS_SENDMSG 16
#define RECORD_SYS_RECVMSG 17
#define RECORD_SEMOP 1
#define RECORD_SEMGET 2
#define RECORD_SEMCTL 3
#define RECORD_SEMTIMEDOP 4
#define RECORD_MSGSND 11
#define RECORD_MSGRCV 12
#define RECORD_MSGGET 13
#define RECORD_MSGCTL 14
#define RECORD_SHMAT 21
#define RECORD_SHMDT 22
#define RECORD_SHMGET 23
#define RECORD_SHMCTL 24
#define RECORD_Q_GETFMT 0x800004
#define RECORD_Q_GETINFO 0x800005
#define RECORD_Q_GETQUOTA 0x800007
#define RECORD_Q_XGETQSTAT (('5' << 8) + 5)
#define RECORD_Q_XGETQUOTA (('3' << 8) + 3)
#define OUTPUT_REG(val, num)
Functions
static int record_linux_sockaddr (struct regcache *regcache, struct linux_record_tdep *tdep, ULONGEST addr, ULONGEST len)
static int record_linux_msghdr (struct regcache *regcache, struct linux_record_tdep *tdep, ULONGEST addr)
int record_linux_system_call (enum gdb_syscall syscall, struct regcache *regcache, struct linux_record_tdep *tdep)
Define Documentation
#define OUTPUT_REG (val, num)
Value:
phex_nz ((val), \
    TYPE_LENGTH (gdbarch_register_type (get_regcache_arch (regcache), (num))))
Definition at line 85 of file linux-record.c.
Referenced by record_linux_system_call().
#define RECORD_MSGCTL 14
Definition at line 69 of file linux-record.c.
Referenced by record_linux_system_call().
#define RECORD_MSGGET 13
Definition at line 68 of file linux-record.c.
Referenced by record_linux_system_call().
#define RECORD_MSGRCV 12
Definition at line 67 of file linux-record.c.
Referenced by record_linux_system_call().
#define RECORD_MSGSND 11
Definition at line 66 of file linux-record.c.
Referenced by record_linux_system_call().
#define RECORD_PTRACE_PEEKDATA 2
Definition at line 33 of file linux-record.c.
Referenced by record_linux_system_call().
#define RECORD_PTRACE_PEEKTEXT 1
Definition at line 32 of file linux-record.c.
Referenced by record_linux_system_call().
#define RECORD_PTRACE_PEEKUSR 3
Definition at line 34 of file linux-record.c.
Referenced by record_linux_system_call().
#define RECORD_Q_GETFMT 0x800004
Definition at line 79 of file linux-record.c.
Referenced by record_linux_system_call().
#define RECORD_Q_GETINFO 0x800005
Definition at line 80 of file linux-record.c.
Referenced by record_linux_system_call().
#define RECORD_Q_GETQUOTA 0x800007
Definition at line 81 of file linux-record.c.
Referenced by record_linux_system_call().
#define RECORD_Q_XGETQSTAT (('5' << 8) + 5)
Definition at line 82 of file linux-record.c.
Referenced by record_linux_system_call().
#define RECORD_Q_XGETQUOTA (('3' << 8) + 3)
Definition at line 83 of file linux-record.c.
Referenced by record_linux_system_call().
#define RECORD_SEMCTL 3
Definition at line 64 of file linux-record.c.
#define RECORD_SEMGET 2
Definition at line 63 of file linux-record.c.
Referenced by record_linux_system_call().
#define RECORD_SEMOP 1
Definition at line 62 of file linux-record.c.
Referenced by record_linux_system_call().
#define RECORD_SEMTIMEDOP 4
Definition at line 65 of file linux-record.c.
Referenced by record_linux_system_call().
#define RECORD_SHMAT 21
Definition at line 70 of file linux-record.c.
Referenced by record_linux_system_call().
#define RECORD_SHMCTL 24
Definition at line 73 of file linux-record.c.
Referenced by record_linux_system_call().
#define RECORD_SHMDT 22
Definition at line 71 of file linux-record.c.
Referenced by record_linux_system_call().
#define RECORD_SHMGET 23
Definition at line 72 of file linux-record.c.
Referenced by record_linux_system_call().
#define RECORD_SYS_ACCEPT 5
Definition at line 44 of file linux-record.c.
Referenced by record_linux_system_call().
#define RECORD_SYS_BIND 2
Definition at line 41 of file linux-record.c.
Referenced by record_linux_system_call().
#define RECORD_SYS_CONNECT 3
Definition at line 42 of file linux-record.c.
Referenced by record_linux_system_call().
#define RECORD_SYS_GETPEERNAME 7
Definition at line 46 of file linux-record.c.
Referenced by record_linux_system_call().
#define RECORD_SYS_GETSOCKNAME 6
Definition at line 45 of file linux-record.c.
Referenced by record_linux_system_call().
#define RECORD_SYS_GETSOCKOPT 15
Definition at line 54 of file linux-record.c.
Referenced by record_linux_system_call().
#define RECORD_SYS_LISTEN 4
Definition at line 43 of file linux-record.c.
Referenced by record_linux_system_call().
#define RECORD_SYS_RECV 10
Definition at line 49 of file linux-record.c.
Referenced by record_linux_system_call().
#define RECORD_SYS_RECVFROM 12
Definition at line 51 of file linux-record.c.
Referenced by record_linux_system_call().
#define RECORD_SYS_RECVMSG 17
Definition at line 56 of file linux-record.c.
Referenced by record_linux_system_call().
#define RECORD_SYS_SEND 9
Definition at line 48 of file linux-record.c.
Referenced by record_linux_system_call().
#define RECORD_SYS_SENDMSG 16
Definition at line 55 of file linux-record.c.
Referenced by record_linux_system_call().
#define RECORD_SYS_SENDTO 11
Definition at line 50 of file linux-record.c.
Referenced by record_linux_system_call().
#define RECORD_SYS_SETSOCKOPT 14
Definition at line 53 of file linux-record.c.
Referenced by record_linux_system_call().
#define RECORD_SYS_SHUTDOWN 13
Definition at line 52 of file linux-record.c.
Referenced by record_linux_system_call().
#define RECORD_SYS_SOCKET 1
Definition at line 40 of file linux-record.c.
Referenced by record_linux_system_call().
#define RECORD_SYS_SOCKETPAIR 8
Definition at line 47 of file linux-record.c.
Referenced by record_linux_system_call().
Function Documentation
static int record_linux_msghdr (struct regcache * regcache, struct linux_record_tdep * tdep, ULONGEST addr) [static]
Definition at line 128 of file linux-record.c.
References gdbarch::byte_order, extract_unsigned_integer(), fprintf_unfiltered(), gdb_stdlog, gdbarch_byte_order(), get_regcache_arch(), int, len, phex_nz(), record_debug, record_full_arch_list_add_mem(), linux_record_tdep::size_int, linux_record_tdep::size_iovec, linux_record_tdep::size_msghdr, linux_record_tdep::size_pointer, linux_record_tdep::size_size_t, target_read_memory(), and ULONGEST.
Referenced by record_linux_system_call().
static int record_linux_sockaddr (struct regcache * regcache, struct linux_record_tdep * tdep, ULONGEST addr, ULONGEST len) [static]
Definition at line 89 of file linux-record.c.
References gdbarch::byte_order, extract_unsigned_integer(), fprintf_unfiltered(), gdb_stdlog, gdbarch_byte_order(), get_regcache_arch(), int, phex_nz(), record_debug, record_full_arch_list_add_mem(), linux_record_tdep::size_int, linux_record_tdep::size_pointer, linux_record_tdep::size_sockaddr, and target_read_memory().
Referenced by record_linux_system_call().
int record_linux_system_call (enum gdb_syscall syscall, struct regcache * regcache, struct linux_record_tdep * tdep)
Definition at line 227 of file linux-record.c.
References _, linux_record_tdep::arg1, linux_record_tdep::arg2, linux_record_tdep::arg3, linux_record_tdep::arg4, linux_record_tdep::arg5, gdbarch::byte_order, extract_signed_integer(), extract_unsigned_integer(), linux_record_tdep::fcntl_F_GETLK, linux_record_tdep::fcntl_F_GETLK64, linux_record_tdep::fcntl_F_SETLK64, linux_record_tdep::fcntl_F_SETLKW64, fprintf_unfiltered(), gdb_old_mmap, gdb_old_readdir, gdb_old_select, gdb_stdlog, gdb_sys_accept, gdb_sys_access, gdb_sys_acct, gdb_sys_add_key, gdb_sys_adjtimex, gdb_sys_alarm, gdb_sys_bdflush, gdb_sys_bind, gdb_sys_brk, gdb_sys_capget, gdb_sys_capset, gdb_sys_chdir, gdb_sys_chmod, gdb_sys_chown, gdb_sys_chown16, gdb_sys_chroot, gdb_sys_clock_getres, gdb_sys_clock_gettime, gdb_sys_clock_nanosleep, gdb_sys_clock_settime, gdb_sys_clone, gdb_sys_close, gdb_sys_connect, gdb_sys_creat, gdb_sys_delete_module, gdb_sys_dup, gdb_sys_dup2, gdb_sys_epoll_create, gdb_sys_epoll_ctl, gdb_sys_epoll_pwait, gdb_sys_epoll_wait, gdb_sys_execve, gdb_sys_exit, gdb_sys_exit_group, gdb_sys_faccessat, gdb_sys_fadvise64, gdb_sys_fadvise64_64, gdb_sys_fchdir, gdb_sys_fchmod, gdb_sys_fchmodat, gdb_sys_fchown, gdb_sys_fchown16, gdb_sys_fchownat, gdb_sys_fcntl, gdb_sys_fcntl64, gdb_sys_fdatasync, gdb_sys_fgetxattr, gdb_sys_flistxattr, gdb_sys_flock, gdb_sys_fork, gdb_sys_fremovexattr, gdb_sys_fsetxattr, gdb_sys_fstat, gdb_sys_fstat64, gdb_sys_fstatat64, gdb_sys_fstatfs, gdb_sys_fstatfs64, gdb_sys_fsync, gdb_sys_ftruncate, gdb_sys_ftruncate64, gdb_sys_futex, gdb_sys_futimesat, gdb_sys_get_mempolicy, gdb_sys_get_robust_list, gdb_sys_get_thread_area, gdb_sys_getcpu, gdb_sys_getcwd, gdb_sys_getdents, gdb_sys_getdents64, gdb_sys_getegid, gdb_sys_getegid16, gdb_sys_geteuid, gdb_sys_geteuid16, gdb_sys_getgid, gdb_sys_getgid16, gdb_sys_getgroups, gdb_sys_getgroups16, gdb_sys_getitimer, gdb_sys_getpeername, gdb_sys_getpgid, gdb_sys_getpgrp, gdb_sys_getpid, gdb_sys_getppid, gdb_sys_getpriority, gdb_sys_getresgid, gdb_sys_getresgid16, gdb_sys_getresuid, gdb_sys_getresuid16, gdb_sys_getrlimit, gdb_sys_getrusage, gdb_sys_getsid, gdb_sys_getsockname, gdb_sys_getsockopt, gdb_sys_gettid, gdb_sys_gettimeofday, gdb_sys_getuid, gdb_sys_getuid16, gdb_sys_getxattr, gdb_sys_init_module, gdb_sys_inotify_add_watch, gdb_sys_inotify_init, gdb_sys_inotify_rm_watch, gdb_sys_io_cancel, gdb_sys_io_destroy, gdb_sys_io_getevents, gdb_sys_io_setup, gdb_sys_io_submit, gdb_sys_ioctl, gdb_sys_ioperm, gdb_sys_iopl, gdb_sys_ioprio_get, gdb_sys_ioprio_set, gdb_sys_ipc, gdb_sys_kexec_load, gdb_sys_keyctl, gdb_sys_kill, gdb_sys_lchown, gdb_sys_lchown16, gdb_sys_lgetxattr, gdb_sys_link, gdb_sys_linkat, gdb_sys_listen, gdb_sys_listxattr, gdb_sys_llistxattr, gdb_sys_llseek, gdb_sys_lookup_dcookie, gdb_sys_lremovexattr, gdb_sys_lseek, gdb_sys_lsetxattr, gdb_sys_lstat, gdb_sys_lstat64, gdb_sys_madvise, gdb_sys_mbind, gdb_sys_migrate_pages, gdb_sys_mincore, gdb_sys_mkdir, gdb_sys_mkdirat, gdb_sys_mknod, gdb_sys_mknodat, gdb_sys_mlock, gdb_sys_mlockall, gdb_sys_mmap2, gdb_sys_modify_ldt, gdb_sys_mount, gdb_sys_move_pages, gdb_sys_mprotect, gdb_sys_mq_getsetattr, gdb_sys_mq_notify, gdb_sys_mq_open, gdb_sys_mq_timedreceive, gdb_sys_mq_timedsend, gdb_sys_mq_unlink, gdb_sys_mremap, gdb_sys_msgctl, gdb_sys_msgget, gdb_sys_msgrcv, gdb_sys_msgsnd, gdb_sys_msync, gdb_sys_munlock, gdb_sys_munlockall, gdb_sys_munmap, gdb_sys_nanosleep, gdb_sys_newfstat, gdb_sys_newfstatat, gdb_sys_newlstat, gdb_sys_newstat, gdb_sys_newuname, gdb_sys_nfsservctl, gdb_sys_ni_syscall112, gdb_sys_ni_syscall127, gdb_sys_ni_syscall130, gdb_sys_ni_syscall137, gdb_sys_ni_syscall167, gdb_sys_ni_syscall17, gdb_sys_ni_syscall188, gdb_sys_ni_syscall189, gdb_sys_ni_syscall222, gdb_sys_ni_syscall223, gdb_sys_ni_syscall251, gdb_sys_ni_syscall273, gdb_sys_ni_syscall285, gdb_sys_ni_syscall31, gdb_sys_ni_syscall32, gdb_sys_ni_syscall35, gdb_sys_ni_syscall44, gdb_sys_ni_syscall53, gdb_sys_ni_syscall56, gdb_sys_ni_syscall58, gdb_sys_ni_syscall98, gdb_sys_nice, gdb_sys_old_getrlimit, gdb_sys_oldumount, gdb_sys_olduname, gdb_sys_open, gdb_sys_openat, gdb_sys_pause, gdb_sys_personality, gdb_sys_pipe, gdb_sys_pivot_root, gdb_sys_poll, gdb_sys_ppoll, gdb_sys_prctl, gdb_sys_pread64, gdb_sys_pselect6, gdb_sys_ptrace, gdb_sys_pwrite64, gdb_sys_quotactl, gdb_sys_read, gdb_sys_readahead, gdb_sys_readlink, gdb_sys_readlinkat, gdb_sys_readv, gdb_sys_reboot, gdb_sys_recv, gdb_sys_recvfrom, gdb_sys_recvmsg, gdb_sys_remap_file_pages, gdb_sys_removexattr, gdb_sys_rename, gdb_sys_renameat, gdb_sys_request_key, gdb_sys_restart_syscall, gdb_sys_rmdir, gdb_sys_rt_sigaction, gdb_sys_rt_sigpending, gdb_sys_rt_sigprocmask, gdb_sys_rt_sigqueueinfo, gdb_sys_rt_sigreturn, gdb_sys_rt_sigsuspend, gdb_sys_rt_sigtimedwait, gdb_sys_sched_get_priority_max, gdb_sys_sched_get_priority_min, gdb_sys_sched_getaffinity, gdb_sys_sched_getparam, gdb_sys_sched_getscheduler, gdb_sys_sched_rr_get_interval, gdb_sys_sched_setaffinity, gdb_sys_sched_setparam, gdb_sys_sched_setscheduler, gdb_sys_sched_yield, gdb_sys_select, gdb_sys_semget, gdb_sys_semop, gdb_sys_semtimedop, gdb_sys_sendfile, gdb_sys_sendfile64, gdb_sys_sendmsg, gdb_sys_sendto, gdb_sys_set_mempolicy, gdb_sys_set_robust_list, gdb_sys_set_thread_area, gdb_sys_set_tid_address, gdb_sys_setdomainname, gdb_sys_setfsgid, gdb_sys_setfsgid16, gdb_sys_setfsuid, gdb_sys_setfsuid16, gdb_sys_setgid, gdb_sys_setgid16, gdb_sys_setgroups, gdb_sys_setgroups16, gdb_sys_sethostname, gdb_sys_setitimer, gdb_sys_setpgid, gdb_sys_setpriority, gdb_sys_setregid, gdb_sys_setregid16, gdb_sys_setresgid, gdb_sys_setresgid16, gdb_sys_setresuid, gdb_sys_setresuid16, gdb_sys_setreuid, gdb_sys_setreuid16, gdb_sys_setrlimit, gdb_sys_setsid, gdb_sys_setsockopt, gdb_sys_settimeofday, gdb_sys_setuid, gdb_sys_setuid16, gdb_sys_setxattr, gdb_sys_sgetmask, gdb_sys_shmat, gdb_sys_shmctl, gdb_sys_shmdt, gdb_sys_shmget, gdb_sys_shutdown, gdb_sys_sigaction, gdb_sys_sigaltstack, gdb_sys_signal, gdb_sys_sigpending, gdb_sys_sigprocmask, gdb_sys_sigreturn, gdb_sys_sigsuspend, gdb_sys_socket, gdb_sys_socketcall, gdb_sys_socketpair, gdb_sys_splice, gdb_sys_ssetmask, gdb_sys_stat, gdb_sys_stat64, gdb_sys_statfs, gdb_sys_statfs64, gdb_sys_stime, gdb_sys_swapoff, gdb_sys_swapon, gdb_sys_symlink, gdb_sys_symlinkat, gdb_sys_sync, gdb_sys_sync_file_range, gdb_sys_sysctl, gdb_sys_sysfs, gdb_sys_sysinfo, gdb_sys_syslog, gdb_sys_tee, gdb_sys_tgkill, gdb_sys_time, gdb_sys_timer_create, gdb_sys_timer_delete, gdb_sys_timer_getoverrun, gdb_sys_timer_gettime, gdb_sys_timer_settime, gdb_sys_times, gdb_sys_tkill, gdb_sys_truncate, gdb_sys_truncate64, gdb_sys_umask, gdb_sys_umount, gdb_sys_uname, gdb_sys_unlink, gdb_sys_unlinkat, gdb_sys_unshare, gdb_sys_uselib, gdb_sys_ustat, gdb_sys_utime, gdb_sys_utimes, gdb_sys_vfork, gdb_sys_vhangup, gdb_sys_vm86, gdb_sys_vm86old, gdb_sys_vmsplice, gdb_sys_wait4, gdb_sys_waitid, gdb_sys_waitpid, gdb_sys_write, gdb_sys_writev, gdbarch_byte_order(), get_regcache_arch(), int, linux_record_tdep::ioctl_FIOASYNC, linux_record_tdep::ioctl_FIOCLEX, linux_record_tdep::ioctl_FIONBIO, linux_record_tdep::ioctl_FIONCLEX, linux_record_tdep::ioctl_FIONREAD, linux_record_tdep::ioctl_FIOQSIZE, linux_record_tdep::ioctl_TCFLSH, linux_record_tdep::ioctl_TCGETA, linux_record_tdep::ioctl_TCGETS, linux_record_tdep::ioctl_TCGETS2, linux_record_tdep::ioctl_TCSBRK, linux_record_tdep::ioctl_TCSBRKP, linux_record_tdep::ioctl_TCSETA, linux_record_tdep::ioctl_TCSETAF, linux_record_tdep::ioctl_TCSETAW, linux_record_tdep::ioctl_TCSETS, linux_record_tdep::ioctl_TCSETS2, linux_record_tdep::ioctl_TCSETSF, linux_record_tdep::ioctl_TCSETSF2, linux_record_tdep::ioctl_TCSETSW, linux_record_tdep::ioctl_TCSETSW2, linux_record_tdep::ioctl_TCXONC, linux_record_tdep::ioctl_TIOCCBRK, linux_record_tdep::ioctl_TIOCCONS, linux_record_tdep::ioctl_TIOCEXCL, linux_record_tdep::ioctl_TIOCGETD, linux_record_tdep::ioctl_TIOCGHAYESESP, linux_record_tdep::ioctl_TIOCGICOUNT, linux_record_tdep::ioctl_TIOCGLCKTRMIOS, linux_record_tdep::ioctl_TIOCGPGRP, linux_record_tdep::ioctl_TIOCGPTN, linux_record_tdep::ioctl_TIOCGSERIAL, linux_record_tdep::ioctl_TIOCGSID, linux_record_tdep::ioctl_TIOCGSOFTCAR, linux_record_tdep::ioctl_TIOCGWINSZ, linux_record_tdep::ioctl_TIOCINQ, linux_record_tdep::ioctl_TIOCLINUX, linux_record_tdep::ioctl_TIOCMBIC, linux_record_tdep::ioctl_TIOCMBIS, linux_record_tdep::ioctl_TIOCMGET, linux_record_tdep::ioctl_TIOCMIWAIT, linux_record_tdep::ioctl_TIOCMSET, linux_record_tdep::ioctl_TIOCNOTTY, linux_record_tdep::ioctl_TIOCNXCL, linux_record_tdep::ioctl_TIOCOUTQ, linux_record_tdep::ioctl_TIOCPKT, linux_record_tdep::ioctl_TIOCSBRK, linux_record_tdep::ioctl_TIOCSCTTY, linux_record_tdep::ioctl_TIOCSERCONFIG, linux_record_tdep::ioctl_TIOCSERGETLSR, linux_record_tdep::ioctl_TIOCSERGETMULTI, linux_record_tdep::ioctl_TIOCSERGSTRUCT, linux_record_tdep::ioctl_TIOCSERGWILD, linux_record_tdep::ioctl_TIOCSERSETMULTI, linux_record_tdep::ioctl_TIOCSERSWILD, linux_record_tdep::ioctl_TIOCSETD, linux_record_tdep::ioctl_TIOCSHAYESESP, linux_record_tdep::ioctl_TIOCSLCKTRMIOS, linux_record_tdep::ioctl_TIOCSPGRP, linux_record_tdep::ioctl_TIOCSPTLCK, linux_record_tdep::ioctl_TIOCSSERIAL, linux_record_tdep::ioctl_TIOCSSOFTCAR, linux_record_tdep::ioctl_TIOCSTI, linux_record_tdep::ioctl_TIOCSWINSZ, linux_record_tdep::ioctl_TIOCTTYGSTRUCT, len, LONGEST, OUTPUT_REG, phex_nz(), printf_unfiltered(), pulongest(), record_debug, record_full_arch_list_add_mem(), record_full_memory_query, record_linux_msghdr(), record_linux_sockaddr(), RECORD_MSGCTL, RECORD_MSGGET, RECORD_MSGRCV, RECORD_MSGSND, RECORD_PTRACE_PEEKDATA, RECORD_PTRACE_PEEKTEXT, RECORD_PTRACE_PEEKUSR, RECORD_Q_GETFMT, RECORD_Q_GETINFO, RECORD_Q_GETQUOTA, RECORD_Q_XGETQSTAT, RECORD_Q_XGETQUOTA, RECORD_SEMGET, RECORD_SEMOP, RECORD_SEMTIMEDOP, RECORD_SHMAT, RECORD_SHMCTL, RECORD_SHMDT, RECORD_SHMGET, RECORD_SYS_ACCEPT, RECORD_SYS_BIND, RECORD_SYS_CONNECT, RECORD_SYS_GETPEERNAME, RECORD_SYS_GETSOCKNAME, RECORD_SYS_GETSOCKOPT, RECORD_SYS_LISTEN, RECORD_SYS_RECV, RECORD_SYS_RECVFROM, RECORD_SYS_RECVMSG, RECORD_SYS_SEND, RECORD_SYS_SENDMSG, RECORD_SYS_SENDTO, RECORD_SYS_SETSOCKOPT, RECORD_SYS_SHUTDOWN, RECORD_SYS_SOCKET, RECORD_SYS_SOCKETPAIR, regcache_raw_read_signed(), regcache_raw_read_unsigned(), size, linux_record_tdep::size__old_kernel_stat, linux_record_tdep::size_cap_user_data_t, linux_record_tdep::size_dirent, linux_record_tdep::size_dirent64, linux_record_tdep::size_epoll_event, linux_record_tdep::size_fd_set, linux_record_tdep::size_flock, linux_record_tdep::size_flock64, linux_record_tdep::size_fs_quota_stat, linux_record_tdep::size_gid_t, linux_record_tdep::size_hayes_esp_config, linux_record_tdep::size_if_dqblk, linux_record_tdep::size_int, linux_record_tdep::size_io_event, linux_record_tdep::size_iocb, linux_record_tdep::size_iovec, linux_record_tdep::size_itimerspec, linux_record_tdep::size_itimerval, linux_record_tdep::size_knfsd_fh, linux_record_tdep::size_loff_t, linux_record_tdep::size_long, linux_record_tdep::size_mem_dqinfo, linux_record_tdep::size_mq_attr, linux_record_tdep::size_msqid_ds, linux_record_tdep::size_new_utsname, linux_record_tdep::size_NFS_FHSIZE, linux_record_tdep::size_off_t, linux_record_tdep::size_old_gid_t, linux_record_tdep::size_old_sigaction, linux_record_tdep::size_old_sigset_t, linux_record_tdep::size_old_uid_t, linux_record_tdep::size_old_utsname, linux_record_tdep::size_oldold_utsname, linux_record_tdep::size_PAGE_SIZE, linux_record_tdep::size_pid_t, linux_record_tdep::size_pointer, linux_record_tdep::size_pollfd, linux_record_tdep::size_rlimit, linux_record_tdep::size_rusage, linux_record_tdep::size_serial_icounter_struct, linux_record_tdep::size_serial_struct, linux_record_tdep::size_shmid_ds, linux_record_tdep::size_sigaction, linux_record_tdep::size_siginfo, linux_record_tdep::size_siginfo_t, linux_record_tdep::size_sigset_t, linux_record_tdep::size_size_t, linux_record_tdep::size_stack_t, linux_record_tdep::size_stat, linux_record_tdep::size_stat64, linux_record_tdep::size_statfs, linux_record_tdep::size_statfs64, linux_record_tdep::size_sysinfo, linux_record_tdep::size_TASK_COMM_LEN, linux_record_tdep::size_termios, linux_record_tdep::size_termios2, linux_record_tdep::size_timespec, linux_record_tdep::size_timeval, linux_record_tdep::size_timex, linux_record_tdep::size_timezone, linux_record_tdep::size_tms, linux_record_tdep::size_uid_t, linux_record_tdep::size_ulong, linux_record_tdep::size_user_desc, linux_record_tdep::size_ustat, linux_record_tdep::size_winsize, target_read_memory(), target_terminal_inferior(), target_terminal_ours, ULONGEST, and yquery().
Referenced by amd64_linux_syscall_record(), and i386_linux_intx80_sysenter_syscall_record().