GDB (xrefs): /home/stan/gdb/src/gdb/linux-nat.h File Reference
/home/stan/gdb/src/gdb/linux-nat.h File Reference
#include "target.h"
#include <signal.h>
Classes
struct lwp_info
Defines
#define ALL_LWPS(LP)
Typedefs
typedef void(linux_nat_new_fork_ftype)(struct lwp_info *parent, pid_t child_pid)
typedef void(linux_nat_forget_process_ftype)(pid_t pid)
Functions
void check_for_thread_db (void)
int thread_db_attach_lwp (ptid_t ptid)
void lin_thread_get_thread_signals (sigset_t *mask)
void linux_proc_pending_signals (int pid, sigset_t *pending, sigset_t *blocked, sigset_t *ignored)
int lin_lwp_attach_lwp (ptid_t ptid)
void linux_stop_lwp (struct lwp_info *lwp)
struct lwp_info * iterate_over_lwps (ptid_t filter, int(*callback)(struct lwp_info *, void *), void *data)
struct target_ops * linux_target (void)
struct target_ops * linux_trad_target (CORE_ADDR(*register_u_offset)(struct gdbarch *, int, int))
void linux_nat_add_target (struct target_ops *)
void linux_nat_set_new_thread (struct target_ops *, void(*)(struct lwp_info *))
void linux_nat_set_new_fork (struct target_ops *ops, linux_nat_new_fork_ftype *fn)
void linux_nat_set_forget_process (struct target_ops *ops, linux_nat_forget_process_ftype *fn)
void linux_nat_forget_process (pid_t pid)
void linux_nat_set_siginfo_fixup (struct target_ops *, int(*)(siginfo_t *, gdb_byte *, int))
void linux_nat_set_prepare_to_resume (struct target_ops *, void(*)(struct lwp_info *))
void linux_nat_switch_fork (ptid_t new_ptid)
int linux_nat_get_siginfo (ptid_t ptid, siginfo_t *siginfo)
void linux_nat_set_status_is_event (struct target_ops *t, int(*status_is_event)(int status))
Variables
struct lwp_info * lwp_list
Define Documentation
#define ALL_LWPS (LP)
Value:
for ((LP) = lwp_list;                                                   \
       (LP) != NULL;                                                    \
       (LP) = (LP)->next)
Definition at line 108 of file linux-nat.h.
Referenced by arm_linux_insert_hw_breakpoint(), arm_linux_insert_watchpoint(), arm_linux_remove_hw_breakpoint(), arm_linux_remove_watchpoint(), ia64_linux_insert_watchpoint(), ia64_linux_remove_watchpoint(), ppc_linux_insert_hw_breakpoint(), ppc_linux_insert_mask_watchpoint(), ppc_linux_insert_watchpoint(), ppc_linux_remove_hw_breakpoint(), ppc_linux_remove_mask_watchpoint(), ppc_linux_remove_watchpoint(), s390_insert_watchpoint(), s390_remove_watchpoint(), and write_watchpoint_regs().
Typedef Documentation
typedef void(linux_nat_forget_process_ftype)(pid_t pid)
Definition at line 160 of file linux-nat.h.
typedef void(linux_nat_new_fork_ftype)(struct lwp_info *parent, pid_t child_pid)
Definition at line 153 of file linux-nat.h.
Function Documentation
void check_for_thread_db (void)
Definition at line 1175 of file linux-thread-db.c.
References thread_db_load().
Referenced by linux_child_follow_fork(), sol_thread_new_objfile(), thread_db_inferior_created(), and thread_db_new_objfile().
struct lwp_info* iterate_over_lwps (ptid_t filter, int(*)(struct lwp_info *, void *) callback, void * data) [read]
Definition at line 1029 of file linux-nat.c.
References lwp_info::next, lwp_info::ptid, and ptid_match().
Referenced by aarch64_notify_debug_reg_change(), amd64_linux_dr_set_addr(), amd64_linux_dr_set_control(), i386_linux_dr_set_addr(), i386_linux_dr_set_control(), linux_nat_detach(), linux_nat_filter_event(), linux_nat_kill(), linux_nat_resume(), linux_nat_stop(), linux_nat_wait(), linux_nat_wait_1(), select_event_lwp(), and thread_db_find_new_threads().
int lin_lwp_attach_lwp (ptid_t ptid)
Definition at line 1173 of file linux-nat.c.
References _, add_lwp(), add_to_pid_list(), lwp_info::cloned, debug_linux_nat, find_lwp_pid(), fprintf_unfiltered(), gdb_assert, gdb_stdlog, in_pid_list_p(), lwp_info::last_resume_kind, linux_nat_post_attach_wait(), linux_supports_tracefork(), my_waitpid(), lwp_info::ptid, ptid_get_lwp(), ptid_get_pid(), ptid_lwp_p(), ptrace(), resume_stop, lwp_info::resumed, safe_strerror(), lwp_info::signalled, lwp_info::status, exsummary::status, status_to_str(), lwp_info::stopped, target_pid_to_str(), target_post_attach, and warning().
Referenced by attach_thread().
void lin_thread_get_thread_signals (sigset_t * mask)
Definition at line 5014 of file linux-nat.c.
References get_signo(), and sigchld_handler().
Referenced by check_thread_signals().
void linux_nat_add_target (struct target_ops *)
Definition at line 4814 of file linux-nat.c.
References add_target(), linux_nat_async(), linux_nat_attach(), linux_nat_can_async_p(), linux_nat_close(), linux_nat_core_of_thread(), linux_nat_create_inferior(), linux_nat_detach(), linux_nat_is_async_p(), linux_nat_kill(), linux_nat_mourn_inferior(), linux_nat_pass_signals(), linux_nat_pid_to_str(), linux_nat_resume(), linux_nat_stop(), linux_nat_stopped_by_watchpoint(), linux_nat_stopped_data_address(), linux_nat_supports_disable_randomization(), linux_nat_supports_multi_process(), linux_nat_supports_non_stop(), linux_nat_terminal_inferior(), linux_nat_terminal_ours(), linux_nat_thread_address_space(), linux_nat_thread_alive(), linux_nat_thread_name(), linux_nat_wait(), linux_nat_xfer_partial(), linux_ops_saved, tc_schedlock, target_ops::to_async, target_ops::to_attach, target_ops::to_can_async_p, target_ops::to_close, target_ops::to_core_of_thread, target_ops::to_create_inferior, target_ops::to_detach, target_ops::to_has_thread_control, target_ops::to_is_async_p, target_ops::to_kill, target_ops::to_mourn_inferior, target_ops::to_pass_signals, target_ops::to_pid_to_str, target_ops::to_resume, target_ops::to_stop, target_ops::to_stopped_by_watchpoint, target_ops::to_stopped_data_address, target_ops::to_supports_disable_randomization, target_ops::to_supports_multi_process, target_ops::to_supports_non_stop, target_ops::to_terminal_inferior, target_ops::to_terminal_ours, target_ops::to_thread_address_space, target_ops::to_thread_alive, target_ops::to_thread_name, target_ops::to_wait, and target_ops::to_xfer_partial.
Referenced by _initialize_aarch64_linux_nat(), _initialize_alpha_linux_nat(), _initialize_amd64_linux_nat(), _initialize_arm_linux_nat(), _initialize_hppa_linux_nat(), _initialize_i386_linux_nat(), _initialize_ia64_linux_nat(), _initialize_m32r_linux_nat(), _initialize_m68k_linux_nat(), _initialize_mips_linux_nat(), _initialize_ppc_linux_nat(), _initialize_s390_nat(), _initialize_sparc64_linux_nat(), _initialize_sparc_linux_nat(), _initialize_tile_linux_nat(), and _initialize_xtensa_linux_nat().
void linux_nat_forget_process (pid_t pid)
Definition at line 4902 of file linux-nat.c.
References linux_nat_forget_process_hook.
Referenced by delete_fork(), linux_nat_kill(), and linux_nat_mourn_inferior().
int linux_nat_get_siginfo (ptid_t ptid, siginfo_t * siginfo)
Definition at line 4934 of file linux-nat.c.
References memset(), ptid_get_lwp(), ptid_get_pid(), ptrace(), PTRACE_GETSIGINFO, and PTRACE_TYPE_ARG3.
Referenced by aarch64_linux_stopped_data_address(), arm_linux_stopped_data_address(), ia64_linux_stopped_data_address(), and ppc_linux_stopped_data_address().
void linux_nat_set_forget_process (struct target_ops * ops, linux_nat_forget_process_ftype * fn)
Definition at line 4892 of file linux-nat.c.
References linux_nat_forget_process_hook.
Referenced by _initialize_aarch64_linux_nat(), _initialize_amd64_linux_nat(), and _initialize_i386_linux_nat().
void linux_nat_set_new_fork (struct target_ops * ops, linux_nat_new_fork_ftype * fn)
Definition at line 4882 of file linux-nat.c.
References linux_nat_new_fork.
Referenced by _initialize_aarch64_linux_nat(), _initialize_amd64_linux_nat(), and _initialize_i386_linux_nat().
void linux_nat_set_new_thread (struct target_ops * , void(*)(struct lwp_info *))
Definition at line 4870 of file linux-nat.c.
References linux_nat_new_thread, and new_thread().
Referenced by _initialize_aarch64_linux_nat(), _initialize_amd64_linux_nat(), _initialize_arm_linux_nat(), _initialize_i386_linux_nat(), _initialize_ia64_linux_nat(), _initialize_mips_linux_nat(), _initialize_ppc_linux_nat(), and _initialize_s390_nat().
void linux_nat_set_prepare_to_resume (struct target_ops * , void(*)(struct lwp_info *))
Definition at line 4924 of file linux-nat.c.
References linux_nat_prepare_to_resume.
Referenced by _initialize_aarch64_linux_nat(), _initialize_amd64_linux_nat(), and _initialize_i386_linux_nat().
void linux_nat_set_siginfo_fixup (struct target_ops * , int(*)(siginfo_t *, gdb_byte *, int))
Definition at line 4912 of file linux-nat.c.
References linux_nat_siginfo_fixup, and siginfo_fixup().
Referenced by _initialize_amd64_linux_nat().
void linux_nat_set_status_is_event (struct target_ops * t, int(*)(int status) status_is_event)
Definition at line 2560 of file linux-nat.c.
References linux_nat_status_is_event.
Referenced by _initialize_ia64_linux_nat().
void linux_nat_switch_fork (ptid_t new_ptid)
Definition at line 1055 of file linux-nat.c.
References add_lwp(), inferior_ptid, ptid_get_pid(), purge_lwp_list(), registers_changed(), lwp_info::stopped, and thread_change_ptid().
Referenced by fork_load_infrun_state().
void linux_proc_pending_signals (int pid, sigset_t * pending, sigset_t * blocked, sigset_t * ignored)
Definition at line 4295 of file linux-nat.c.
References _, add_line_to_sigset(), do_cleanups(), error(), gdb_fopen_cloexec(), and make_cleanup_fclose().
Referenced by linux_nat_has_pending_sigint().
void linux_stop_lwp (struct lwp_info * lwp)
Definition at line 2402 of file linux-nat.c.
References stop_callback().
Referenced by debug_reg_change_callback(), and update_debug_registers_callback().
struct target_ops* linux_target (void) [read]
Definition at line 4480 of file linux-nat.c.
References inf_ptrace_target(), and linux_target_install_ops().
Referenced by _initialize_aarch64_linux_nat(), _initialize_amd64_linux_nat(), _initialize_arm_linux_nat(), _initialize_hppa_linux_nat(), _initialize_i386_linux_nat(), _initialize_ia64_linux_nat(), _initialize_m32r_linux_nat(), _initialize_m68k_linux_nat(), _initialize_ppc_linux_nat(), _initialize_s390_nat(), _initialize_sparc64_linux_nat(), _initialize_sparc_linux_nat(), _initialize_tile_linux_nat(), and _initialize_xtensa_linux_nat().
struct target_ops* linux_trad_target (CORE_ADDR(*)(struct gdbarch *, int, int) register_u_offset) [read]
Definition at line 4491 of file linux-nat.c.
References inf_ptrace_trad_target(), and linux_target_install_ops().
Referenced by _initialize_alpha_linux_nat(), and _initialize_mips_linux_nat().
int thread_db_attach_lwp (ptid_t ptid)
Definition at line 478 of file linux-thread-db.c.
References _, attach_thread(), gdb_assert, get_thread_db_info(), have_threads(), thread_db_info::proc_handle, ps_prochandle::ptid, ptid_get_lwp(), ptid_get_pid(), TD_OK, thread_db_info::td_ta_map_lwp2thr_p, thread_db_info::td_thr_get_info_p, thread_db_info::thread_agent, thread_db_err_str(), thread_db_find_new_threads_1(), and warning().
Referenced by linux_handle_extended_wait().
Variable Documentation
struct lwp_info* lwp_list
Definition at line 793 of file linux-nat.c.
Referenced by add_initial_lwp(), and num_lwps().