GDB (xrefs): /home/stan/gdb/src/gdb/common/linux-btrace.h File Reference
/home/stan/gdb/src/gdb/common/linux-btrace.h File Reference
#include "btrace-common.h"
#include "config.h"
#include "vec.h"
#include "ptid.h"
#include <stddef.h>
#include <stdint.h>
Classes
struct btrace_target_info
Functions
int linux_supports_btrace (void)
struct btrace_target_info * linux_enable_btrace (ptid_t ptid)
int linux_disable_btrace (struct btrace_target_info *tinfo)
VEC (btrace_block_s)*linux_read_btrace(struct btrace_target_info *
Function Documentation
int linux_disable_btrace (struct btrace_target_info * tinfo)
Definition at line 573 of file linux-btrace.c.
Referenced by amd64_linux_disable_btrace(), amd64_linux_teardown_btrace(), i386_linux_disable_btrace(), and i386_linux_teardown_btrace().
struct btrace_target_info* linux_enable_btrace (ptid_t ptid) [read]
Definition at line 565 of file linux-btrace.c.
Referenced by amd64_linux_enable_btrace(), and i386_linux_enable_btrace().
int linux_supports_btrace (void)
Definition at line 557 of file linux-btrace.c.
Referenced by _initialize_amd64_linux_nat(), and _initialize_i386_linux_nat().
VEC (btrace_block_s)