GDB (xrefs): /home/stan/gdb/src/gdb/linux-fork.h File Reference
/home/stan/gdb/src/gdb/linux-fork.h File Reference
Functions
struct fork_info * add_fork (pid_t)
struct fork_info * find_fork_pid (pid_t)
void linux_fork_killall (void)
void linux_fork_mourn_inferior (void)
void linux_fork_detach (char *, int)
int forks_exist_p (void)
int linux_fork_checkpointing_p (int)
Function Documentation
struct fork_info* add_fork (pid_t) [read]
Definition at line 70 of file linux-fork.c.
References add_fork(), fork_list, highest_fork_num, inferior_ptid, fork_info::next, fork_info::num, fork_info::ptid, ptid_build(), ptid_get_pid(), and XZALLOC.
Referenced by add_fork(), and linux_handle_extended_wait().
struct fork_info* find_fork_pid (pid_t) [read]
Definition at line 181 of file linux-fork.c.
References fork_info::next, fork_info::ptid, and ptid_get_pid().
Referenced by checkpoint_command(), and linux_handle_extended_wait().
int forks_exist_p (void)
Definition at line 62 of file linux-fork.c.
Referenced by linux_nat_detach(), linux_nat_kill(), and linux_nat_mourn_inferior().
int linux_fork_checkpointing_p (int)
Definition at line 617 of file linux-fork.c.
References checkpointing_pid.
Referenced by linux_handle_extended_wait().
void linux_fork_detach (char * , int)
Definition at line 390 of file linux-fork.c.
References _, delete_fork(), error(), fork_load_infrun_state(), gdb_assert, inferior_ptid, fork_info::next, printf_filtered(), ptid_get_pid(), ptrace(), and target_pid_to_str().
Referenced by linux_nat_detach().
void linux_fork_killall (void)
Definition at line 324 of file linux-fork.c.
References init_fork_list(), fork_info::next, fork_info::ptid, ptid_get_pid(), and exsummary::status.
Referenced by linux_nat_kill().
void linux_fork_mourn_inferior (void)
Definition at line 356 of file linux-fork.c.
References _, delete_fork(), fork_load_infrun_state(), gdb_assert, inferior_ptid, fork_info::next, printf_filtered(), ptid_get_pid(), exsummary::status, and target_pid_to_str().
Referenced by linux_nat_mourn_inferior().