GDB (xrefs): /home/stan/gdb/src/gdb/linux-tdep.h File Reference
/home/stan/gdb/src/gdb/linux-tdep.h File Reference
#include "bfd.h"
Typedefs
typedef char *(* linux_collect_thread_registers_ftype)(const struct regcache *, ptid_t, bfd *, char *, int *, enum gdb_signal)
Functions
char * linux_make_corefile_notes (struct gdbarch *, bfd *, int *, linux_collect_thread_registers_ftype)
struct type * linux_get_siginfo_type (struct gdbarch *)
enum gdb_signal linux_gdb_signal_from_target (struct gdbarch *gdbarch, int signal)
int linux_gdb_signal_to_target (struct gdbarch *gdbarch, enum gdb_signal signal)
void linux_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
int linux_is_uclinux (void)
Typedef Documentation
typedef char*(* linux_collect_thread_registers_ftype)(const struct regcache *, ptid_t, bfd *, char *, int *, enum gdb_signal)
Definition at line 27 of file linux-tdep.h.
Function Documentation
enum gdb_signal linux_gdb_signal_from_target (struct gdbarch * gdbarch, int signal)
Definition at line 1523 of file linux-tdep.c.
References int, LINUX_SIGABRT, LINUX_SIGALRM, LINUX_SIGBUS, LINUX_SIGCHLD, LINUX_SIGCONT, LINUX_SIGFPE, LINUX_SIGHUP, LINUX_SIGILL, LINUX_SIGINT, LINUX_SIGIO, LINUX_SIGKILL, LINUX_SIGPIPE, LINUX_SIGPROF, LINUX_SIGPWR, LINUX_SIGQUIT, LINUX_SIGRTMAX, LINUX_SIGRTMIN, LINUX_SIGSEGV, LINUX_SIGSTOP, LINUX_SIGSYS, LINUX_SIGTERM, LINUX_SIGTRAP, LINUX_SIGTSTP, LINUX_SIGTTIN, LINUX_SIGTTOU, LINUX_SIGURG, LINUX_SIGUSR1, LINUX_SIGUSR2, LINUX_SIGVTALRM, LINUX_SIGWINCH, LINUX_SIGXCPU, LINUX_SIGXFSZ, and offset.
Referenced by alpha_linux_gdb_signal_from_target(), linux_init_abi(), mips_gdb_signal_from_target(), sparc32_linux_gdb_signal_from_target(), and xtensa_linux_gdb_signal_from_target().
int linux_gdb_signal_to_target (struct gdbarch * gdbarch, enum gdb_signal signal)
Definition at line 1646 of file linux-tdep.c.
References LINUX_SIGABRT, LINUX_SIGALRM, LINUX_SIGBUS, LINUX_SIGCHLD, LINUX_SIGCONT, LINUX_SIGFPE, LINUX_SIGHUP, LINUX_SIGILL, LINUX_SIGINT, LINUX_SIGIO, LINUX_SIGKILL, LINUX_SIGPIPE, LINUX_SIGPOLL, LINUX_SIGPROF, LINUX_SIGPWR, LINUX_SIGQUIT, LINUX_SIGRTMAX, LINUX_SIGRTMIN, LINUX_SIGSEGV, LINUX_SIGSTOP, LINUX_SIGSYS, LINUX_SIGTERM, LINUX_SIGTRAP, LINUX_SIGTSTP, LINUX_SIGTTIN, LINUX_SIGTTOU, LINUX_SIGURG, LINUX_SIGUSR1, LINUX_SIGUSR2, LINUX_SIGVTALRM, LINUX_SIGWINCH, LINUX_SIGXCPU, LINUX_SIGXFSZ, and offset.
Referenced by alpha_linux_gdb_signal_to_target(), linux_init_abi(), mips_gdb_signal_to_target(), sparc32_linux_gdb_signal_to_target(), and xtensa_linux_gdb_signal_to_target().
struct type* linux_get_siginfo_type (struct gdbarch *) [read]
Definition at line 127 of file linux-tdep.c.
References append_composite_type_field(), append_composite_type_field_aligned(), arch_composite_type(), arch_integer_type(), arch_type(), gdbarch_int_bit(), gdbarch_long_bit(), gdbarch_ptr_bit(), get_linux_gdbarch_data(), HOST_CHAR_BIT, init_vector_type(), lookup_pointer_type(), linux_gdbarch_data::siginfo_type, type, TYPE_CODE_STRUCT, TYPE_CODE_TYPEDEF, TYPE_CODE_UNION, TYPE_LENGTH, TYPE_NAME, TYPE_TARGET_STUB, and TYPE_TARGET_TYPE.
Referenced by aarch64_linux_init_abi(), amd64_linux_init_abi_common(), arm_linux_init_abi(), i386_linux_init_abi(), m68k_linux_init_abi(), ppc_linux_init_abi(), s390_gdbarch_init(), and tilegx_linux_init_abi().
void linux_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch)
Definition at line 1773 of file linux-tdep.c.
References linux_core_info_proc(), linux_core_pid_to_str(), linux_find_memory_regions(), linux_gdb_signal_from_target(), linux_gdb_signal_to_target(), linux_has_shared_address_space(), linux_info_proc(), linux_make_corefile_notes_1(), set_gdbarch_core_info_proc(), set_gdbarch_core_pid_to_str(), set_gdbarch_find_memory_regions(), set_gdbarch_gdb_signal_from_target(), set_gdbarch_gdb_signal_to_target(), set_gdbarch_has_shared_address_space(), set_gdbarch_info_proc(), and set_gdbarch_make_corefile_notes().
Referenced by aarch64_linux_init_abi(), alpha_linux_init_abi(), am33_linux_init_osabi(), amd64_linux_init_abi_common(), arm_linux_init_abi(), bfin_linux_init_abi(), cris_linux_init_abi(), frv_linux_init_abi(), hppa_linux_init_abi(), i386_linux_init_abi(), ia64_linux_init_abi(), m32r_linux_init_abi(), m68k_linux_init_abi(), microblaze_linux_init_abi(), mips_linux_init_abi(), nios2_linux_init_abi(), ppc_linux_init_abi(), s390_gdbarch_init(), sh_linux_init_abi(), sparc32_linux_init_abi(), sparc64_linux_init_abi(), tic6x_uclinux_init_abi(), tilegx_linux_init_abi(), and xtensa_linux_init_abi().
int linux_is_uclinux (void)
Definition at line 248 of file linux-tdep.c.
References current_target, dummy, and target_auxv_search().
Referenced by linux_has_shared_address_space(), and m68k_linux_get_sigtramp_info().
char* linux_make_corefile_notes (struct gdbarch * , bfd * , int * , linux_collect_thread_registers_ftype)
Definition at line 1434 of file linux-tdep.c.
References linux_corefile_thread_data::collect, current_target, find_stop_signal(), linux_corefile_thread_data::gdbarch, gdbarch_elfcore_write_linux_prpsinfo(), gdbarch_elfcore_write_linux_prpsinfo_p(), gdbarch_ptr_bit(), inferior_ptid, iterate_over_threads(), linux_corefile_thread_callback(), linux_fill_prpsinfo(), linux_make_mappings_corefile_notes(), linux_spu_make_corefile_notes(), make_cleanup(), linux_corefile_thread_data::note_data, linux_corefile_thread_data::note_size, linux_corefile_thread_data::num_notes, linux_corefile_thread_data::obfd, linux_corefile_thread_data::pid, ptid_get_pid(), linux_corefile_thread_data::stop_signal, TARGET_OBJECT_AUXV, target_read_alloc(), and xfree().
Referenced by linux_make_corefile_notes_1(), and linux_nat_make_corefile_notes().