GDB (xrefs): /home/stan/gdb/src/gdb/common/linux-btrace.c File Reference
/home/stan/gdb/src/gdb/common/linux-btrace.c File Reference
#include "defs.h"
#include "linux-btrace.h"
#include "common-utils.h"
#include "gdb_assert.h"
#include "regcache.h"
#include "gdbthread.h"
#include "gdb_wait.h"
#include "i386-cpuid.h"
Functions
int linux_supports_btrace (void)
struct btrace_target_info * linux_enable_btrace (ptid_t ptid)
int linux_disable_btrace (struct btrace_target_info *tinfo)
VEC (btrace_block_s)
Function Documentation
int linux_disable_btrace (struct btrace_target_info * tinfo)
Definition at line 573 of file linux-btrace.c.
Referenced by amd64_linux_disable_btrace(), amd64_linux_teardown_btrace(), i386_linux_disable_btrace(), and i386_linux_teardown_btrace().
struct btrace_target_info* linux_enable_btrace (ptid_t ptid) [read]
Definition at line 565 of file linux-btrace.c.
Referenced by amd64_linux_enable_btrace(), and i386_linux_enable_btrace().
int linux_supports_btrace (void)
Definition at line 557 of file linux-btrace.c.
Referenced by _initialize_amd64_linux_nat(), and _initialize_i386_linux_nat().
VEC (btrace_block_s)
Definition at line 580 of file linux-btrace.c.