GDB (xrefs): /home/stan/gdb/src/gdb/linux-thread-db.c File Reference
/home/stan/gdb/src/gdb/linux-thread-db.c File Reference
#include "defs.h"
#include "gdb_assert.h"
#include <dlfcn.h>
#include "gdb_proc_service.h"
#include "gdb_thread_db.h"
#include "gdb_vecs.h"
#include "bfd.h"
#include "command.h"
#include "exceptions.h"
#include "gdbcmd.h"
#include "gdbthread.h"
#include "inferior.h"
#include "symfile.h"
#include "objfiles.h"
#include "target.h"
#include "regcache.h"
#include "solib.h"
#include "solib-svr4.h"
#include "gdbcore.h"
#include "observer.h"
#include "linux-nat.h"
#include "linux-procfs.h"
#include "linux-osdata.h"
#include "auto-load.h"
#include "cli/cli-utils.h"
#include <signal.h>
#include <ctype.h>
Classes
struct thread_db_info
struct private_thread_info
struct thread_get_info_inout
struct callback_data
Functions
static void show_auto_load_thread_db (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static void set_libthread_db_search_path (char *ignored, int from_tty, struct cmd_list_element *c)
static void show_libthread_db_debug (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static void thread_db_find_new_threads_1 (ptid_t ptid)
static void thread_db_find_new_threads_2 (ptid_t ptid, int until_no_new)
static struct thread_db_info * add_thread_db_info (void *handle)
static struct thread_db_info * get_thread_db_info (int pid)
static void delete_thread_db_info (int pid)
static int attach_thread (ptid_t ptid, const td_thrhandle_t *th_p, const td_thrinfo_t *ti_p)
static void detach_thread (ptid_t ptid)
static char * thread_db_err_str (td_err_e err)
static int have_threads_callback (struct thread_info *thread, void *args)
static int have_threads (ptid_t ptid)
static int thread_get_info_callback (const td_thrhandle_t *thp, void *argp)
static void thread_from_lwp (ptid_t ptid)
int thread_db_attach_lwp (ptid_t ptid)
static void * verbose_dlsym (void *handle, const char *name)
static td_err_e enable_thread_event (int event, CORE_ADDR *bp)
static int inferior_has_bug (const char *ver_symbol, int ver_major_min, int ver_minor_min)
static void enable_thread_event_reporting (void)
static int thread_db_find_new_threads_silently (ptid_t ptid)
static const char * dladdr_to_soname (const void *addr)
static int try_thread_db_load_1 (struct thread_db_info *info)
static int try_thread_db_load (const char *library)
static int try_thread_db_load_from_pdir_1 (struct objfile *obj, const char *subdir)
static int try_thread_db_load_from_pdir (const char *subdir)
static int try_thread_db_load_from_sdir (void)
static int try_thread_db_load_from_dir (const char *dir, size_t dir_len)
static int thread_db_load_search (void)
static int has_libpthread (void)
static int thread_db_load (void)
static void disable_thread_event_reporting (struct thread_db_info *info)
static void check_thread_signals (void)
void check_for_thread_db (void)
static void thread_db_new_objfile (struct objfile *objfile)
static void thread_db_inferior_created (struct target_ops *target, int from_tty)
static void thread_db_detach (struct target_ops *ops, char *args, int from_tty)
static void check_event (ptid_t ptid)
static ptid_t thread_db_wait (struct target_ops *ops, ptid_t ptid, struct target_waitstatus *ourstatus, int options)
static void thread_db_mourn_inferior (struct target_ops *ops)
static int find_new_threads_callback (const td_thrhandle_t *th_p, void *data)
static int find_new_threads_once (struct thread_db_info *info, int iteration, td_err_e *errp)
static int update_thread_core (struct lwp_info *info, void *closure)
static void thread_db_find_new_threads (struct target_ops *ops)
static char * thread_db_pid_to_str (struct target_ops *ops, ptid_t ptid)
static char * thread_db_extra_thread_info (struct thread_info *info)
static CORE_ADDR thread_db_get_thread_local_address (struct target_ops *ops, ptid_t ptid, CORE_ADDR lm, CORE_ADDR offset)
static int thread_db_find_thread_from_tid (struct thread_info *thread, void *data)
static ptid_t thread_db_get_ada_task_ptid (long lwp, long thread)
static void thread_db_resume (struct target_ops *ops, ptid_t ptid, int step, enum gdb_signal signo)
static int info_auto_load_libthread_db_compare (const void *ap, const void *bp)
static void info_auto_load_libthread_db (char *args, int from_tty)
static void init_thread_db_ops (void)
void _initialize_thread_db (void)
Variables
static char * libthread_db_search_path
static int auto_load_thread_db = 1
static unsigned int libthread_db_debug
static struct target_ops thread_db_ops
static int thread_signals
static sigset_t thread_stop_set
static sigset_t thread_print_set
struct thread_db_info * thread_db_list
initialize_file_ftype _initialize_thread_db
Function Documentation
void _initialize_thread_db (void)
Definition at line 2072 of file linux-thread-db.c.
References _, _initialize_thread_db, add_cmd(), add_setshow_boolean_cmd(), add_setshow_optional_filename_cmd(), add_setshow_zuinteger_cmd(), auto_load_info_cmdlist_get(), auto_load_set_cmdlist_get(), auto_load_show_cmdlist_get(), auto_load_thread_db, class_info, class_maintenance, class_support, info_auto_load_libthread_db(), init_thread_db_ops(), libthread_db_debug, LIBTHREAD_DB_SEARCH_PATH, libthread_db_search_path, observer_attach_inferior_created(), observer_attach_new_objfile(), set_libthread_db_search_path(), setdebuglist, setlist, show_auto_load_thread_db(), show_libthread_db_debug(), showdebuglist, showlist, thread_db_inferior_created(), and thread_db_new_objfile().
static struct thread_db_info* add_thread_db_info (void * handle) [static, read]
Definition at line 214 of file linux-thread-db.c.
References thread_db_info::handle, inferior_ptid, thread_db_info::need_stale_parent_threads_check, thread_db_info::next, thread_db_info::pid, ptid_get_pid(), target_has_execution, thread_db_list, and xcalloc().
Referenced by try_thread_db_load().
static int attach_thread (ptid_t ptid, const td_thrhandle_t * th_p, const td_thrinfo_t * ti_p) [static]
Definition at line 1224 of file linux-thread-db.c.
References _, add_thread_with_info(), check_thread_signals(), delete_thread(), private_thread_info::dying, error(), find_thread_ptid(), gdb_assert, get_thread_db_info(), lin_lwp_attach_lwp(), memset(), thread_info::private, ptid_build(), ptid_get_pid(), target_has_execution, target_pid_to_str(), TD_OK, thread_db_info::td_thr_event_enable_p, TD_THR_UNKNOWN, TD_THR_ZOMBIE, thread_db_err_str(), td_thrinfo::ti_lid, td_thrinfo::ti_state, td_thrinfo::ti_tid, and xmalloc().
Referenced by check_event(), find_new_threads_callback(), thread_db_attach_lwp(), and thread_get_info_callback().
static void check_event (ptid_t ptid) [static]
Definition at line 1382 of file linux-thread-db.c.
References _, attach_thread(), detach_thread(), error(), td_event_msg::event, gdbarch_decr_pc_after_break(), get_regcache_arch(), get_thread_db_info(), get_thread_regcache(), have_threads(), in_thread_list(), thread_db_info::proc_handle, ps_prochandle::ptid, ptid_build(), ptid_get_pid(), regcache_read_pc(), stop_pc, TD_CREATE, thread_db_info::td_create_bp_addr, TD_DEATH, thread_db_info::td_death_bp_addr, TD_NOMSG, TD_OK, thread_db_info::td_ta_event_getmsg_p, thread_db_info::td_thr_get_info_p, td_event_msg::th_p, thread_db_info::thread_agent, thread_db_err_str(), thread_db_find_new_threads_1(), and td_thrinfo::ti_lid.
Referenced by thread_db_wait().
void check_for_thread_db (void)
Definition at line 1175 of file linux-thread-db.c.
References thread_db_load().
Referenced by linux_child_follow_fork(), sol_thread_new_objfile(), thread_db_inferior_created(), and thread_db_new_objfile().
static void check_thread_signals (void) [static]
Definition at line 1145 of file linux-thread-db.c.
References gdb_signal_from_host(), lin_thread_get_thread_signals(), signal_print_update(), signal_stop_update(), thread_print_set, thread_signals, and thread_stop_set.
Referenced by attach_thread().
static void delete_thread_db_info (int pid) [static]
Definition at line 254 of file linux-thread-db.c.
References thread_db_info::next, and xfree().
Referenced by thread_db_detach(), thread_db_mourn_inferior(), thread_db_wait(), and try_thread_db_load().
static void detach_thread (ptid_t ptid) [static]
Definition at line 1325 of file linux-thread-db.c.
References private_thread_info::dying, find_thread_ptid(), gdb_assert, and thread_info::private.
Referenced by check_event().
static void disable_thread_event_reporting (struct thread_db_info * info) [static]
Definition at line 1128 of file linux-thread-db.c.
References thread_db_info::td_create_bp_addr, thread_db_info::td_death_bp_addr, td_event_fillset, thread_db_info::td_ta_clear_event_p, and thread_db_info::thread_agent.
Referenced by thread_db_detach().
static const char* dladdr_to_soname (const void * addr) [static]
Definition at line 708 of file linux-thread-db.c.
Referenced by try_thread_db_load(), and try_thread_db_load_1().
static td_err_e enable_thread_event (int event, CORE_ADDR * bp) [static]
Definition at line 531 of file linux-thread-db.c.
References td_notify::bptaddr, create_thread_event_breakpoint(), current_target, exec_bfd, gdb_assert, gdbarch_convert_from_func_ptr_addr(), get_thread_db_info(), inferior_ptid, thread_db_info::proc_handle, ps_prochandle::ptid, ptid_get_pid(), target_gdbarch(), TD_OK, thread_db_info::td_ta_event_addr_p, thread_db_info::thread_agent, and td_notify::u.
Referenced by enable_thread_event_reporting().
static void enable_thread_event_reporting (void) [static]
Definition at line 593 of file linux-thread-db.c.
References _, enable_thread_event(), get_thread_db_info(), inferior_has_bug(), inferior_ptid, ptid_get_pid(), remove_thread_event_breakpoints(), TD_CREATE, thread_db_info::td_create_bp_addr, TD_DEATH, thread_db_info::td_death_bp_addr, td_event_addset, td_event_emptyset, TD_OK, thread_db_info::td_ta_event_addr_p, thread_db_info::td_ta_event_getmsg_p, thread_db_info::td_ta_set_event_p, thread_db_info::td_thr_event_enable_p, thread_db_info::thread_agent, thread_db_err_str(), and warning().
Referenced by try_thread_db_load_1().
static int find_new_threads_callback (const td_thrhandle_t * th_p, void * data) [static]
Definition at line 1551 of file linux-thread-db.c.
References _, attach_thread(), error(), find_thread_ptid(), callback_data::info, linux_proc_get_tgid(), thread_db_info::need_stale_parent_threads_check, callback_data::new_threads, thread_db_info::pid, thread_info::private, ptid_build(), target_has_execution, TD_OK, thread_db_info::td_thr_event_enable_p, thread_db_info::td_thr_get_info_p, thread_db_err_str(), td_thrinfo::ti_lid, and td_thrinfo::ti_tid.
Referenced by find_new_threads_once().
static int find_new_threads_once (struct thread_db_info * info, int iteration, td_err_e * errp) [static]
Definition at line 1622 of file linux-thread-db.c.
References _, exception_fprintf(), find_new_threads_callback(), gdb_stderr, callback_data::info, libthread_db_debug, callback_data::new_threads, printf_filtered(), gdb_exception::reason, RETURN_MASK_ERROR, TD_ERR, TD_SIGNO_MASK, thread_db_info::td_ta_thr_iter_p, TD_THR_ANY_STATE, TD_THR_ANY_USER_FLAGS, TD_THR_LOWEST_PRIORITY, thread_db_info::thread_agent, and TRY_CATCH.
Referenced by thread_db_find_new_threads_2().
static struct thread_db_info* get_thread_db_info (int pid) [static, read]
Definition at line 237 of file linux-thread-db.c.
References thread_db_info::next, and thread_db_info::pid.
Referenced by attach_thread(), check_event(), enable_thread_event(), enable_thread_event_reporting(), thread_db_attach_lwp(), thread_db_detach(), thread_db_find_new_threads(), thread_db_find_new_threads_2(), thread_db_get_thread_local_address(), thread_db_load(), thread_db_resume(), thread_db_wait(), and thread_from_lwp().
static int has_libpthread (void) [static]
Definition at line 1076 of file linux-thread-db.c.
References ALL_OBJFILES, libpthread_name_p(), and objfile_name().
Referenced by thread_db_load().
static int have_threads (ptid_t ptid) [static]
Definition at line 382 of file linux-thread-db.c.
References have_threads_callback(), iterate_over_threads(), and ptid_get_pid().
Referenced by check_event(), thread_db_attach_lwp(), thread_db_get_thread_local_address(), thread_db_wait(), and thread_get_info_callback().
static int have_threads_callback (struct thread_info * thread, void * args) [static]
Definition at line 371 of file linux-thread-db.c.
References thread_info::private, thread_info::ptid, and ptid_get_pid().
Referenced by have_threads().
static int inferior_has_bug (const char * ver_symbol, int ver_major_min, int ver_minor_min) [static]
Definition at line 566 of file linux-thread-db.c.
References lookup_minimal_symbol(), SYMBOL_VALUE_ADDRESS, target_read_string(), version, and xfree().
Referenced by enable_thread_event_reporting(), and thread_db_find_new_threads_silently().
static void info_auto_load_libthread_db (char * args, int from_tty) [static]
Definition at line 1923 of file linux-thread-db.c.
References _, auto_load_info_scripts_pattern_nl, current_uiout, do_cleanups(), error(), thread_db_info::filename, gdb_assert, info_auto_load_libthread_db_compare(), make_cleanup(), make_cleanup_ui_out_table_begin_end(), make_cleanup_ui_out_tuple_begin_end(), max, thread_db_info::next, thread_db_info::pid, qsort, skip_spaces_const(), ui_left, ui_out_field_string(), ui_out_message(), ui_out_table_body(), ui_out_table_header(), ui_out_text(), xfree(), xmalloc(), and xsnprintf().
Referenced by _initialize_thread_db().
static int info_auto_load_libthread_db_compare (const void * ap, const void * bp) [static]
Definition at line 1907 of file linux-thread-db.c.
References thread_db_info::filename, and thread_db_info::pid.
Referenced by info_auto_load_libthread_db().
static void init_thread_db_ops (void) [static]
Definition at line 2046 of file linux-thread-db.c.
References complete_target_initialization(), OPS_MAGIC, tc_schedlock, thread_db_detach(), thread_db_extra_thread_info(), thread_db_find_new_threads(), thread_db_get_ada_task_ptid(), thread_db_get_thread_local_address(), thread_db_mourn_inferior(), thread_db_ops, thread_db_pid_to_str(), thread_db_resume(), thread_db_wait(), thread_stratum, target_ops::to_detach, target_ops::to_doc, target_ops::to_extra_thread_info, target_ops::to_find_new_threads, target_ops::to_get_ada_task_ptid, target_ops::to_get_thread_local_address, target_ops::to_has_thread_control, target_ops::to_longname, target_ops::to_magic, target_ops::to_mourn_inferior, target_ops::to_pid_to_str, target_ops::to_resume, target_ops::to_shortname, target_ops::to_stratum, and target_ops::to_wait.
Referenced by _initialize_thread_db().
static void set_libthread_db_search_path (char * ignored, int from_tty, struct cmd_list_element * c) [static]
Definition at line 94 of file linux-thread-db.c.
References LIBTHREAD_DB_SEARCH_PATH, libthread_db_search_path, and xfree().
Referenced by _initialize_thread_db().
static void show_auto_load_thread_db (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 85 of file linux-thread-db.c.
References _, and fprintf_filtered().
Referenced by _initialize_thread_db().
static void show_libthread_db_debug (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 109 of file linux-thread-db.c.
References _, and fprintf_filtered().
Referenced by _initialize_thread_db().
int thread_db_attach_lwp (ptid_t ptid)
Definition at line 478 of file linux-thread-db.c.
References _, attach_thread(), gdb_assert, get_thread_db_info(), have_threads(), thread_db_info::proc_handle, ps_prochandle::ptid, ptid_get_lwp(), ptid_get_pid(), TD_OK, thread_db_info::td_ta_map_lwp2thr_p, thread_db_info::td_thr_get_info_p, thread_db_info::thread_agent, thread_db_err_str(), thread_db_find_new_threads_1(), and warning().
Referenced by linux_handle_extended_wait().
static void thread_db_detach (struct target_ops * ops, char * args, int from_tty) [static]
Definition at line 1343 of file linux-thread-db.c.
References delete_thread_db_info(), disable_thread_event_reporting(), find_target_beneath(), get_thread_db_info(), inferior_ptid, ptid_get_pid(), remove_thread_event_breakpoints(), target_has_execution, thread_db_ops, target_ops::to_detach, and unpush_target().
Referenced by init_thread_db_ops().
static char* thread_db_err_str (td_err_e err) [static]
Definition at line 301 of file linux-thread-db.c.
References TD_BADKEY, TD_BADPH, TD_BADSH, TD_BADTA, TD_BADTH, TD_DBERR, TD_ERR, TD_MALLOC, TD_NOAPLIC, TD_NOCAPAB, TD_NOEVENT, TD_NOFPREGS, TD_NOLIBTHREAD, TD_NOLWP, TD_NOMSG, TD_NOSV, TD_NOTALLOC, TD_NOTHR, TD_NOTLS, TD_NOTSD, TD_NOXREGS, TD_OK, TD_PARTIALREG, and TD_VERSION.
Referenced by attach_thread(), check_event(), enable_thread_event_reporting(), find_new_threads_callback(), thread_db_attach_lwp(), thread_db_find_new_threads_2(), thread_db_get_thread_local_address(), thread_from_lwp(), thread_get_info_callback(), and try_thread_db_load_1().
static char* thread_db_extra_thread_info (struct thread_info * info) [static]
Definition at line 1767 of file linux-thread-db.c.
References private_thread_info::dying, and thread_info::private.
Referenced by init_thread_db_ops().
static void thread_db_find_new_threads (struct target_ops * ops) [static]
Definition at line 1710 of file linux-thread-db.c.
References ALL_INFERIORS, any_live_thread_of_process(), thread_info::executing, get_thread_db_info(), arm-linux::inf, iterate_over_lwps(), minus_one_ptid, inferior::pid, thread_info::ptid, target_has_execution, thread_db_find_new_threads_1(), and update_thread_core().
Referenced by init_thread_db_ops().
static void thread_db_find_new_threads_1 (ptid_t ptid) [static]
Definition at line 1697 of file linux-thread-db.c.
References thread_db_find_new_threads_2().
Referenced by check_event(), thread_db_attach_lwp(), thread_db_find_new_threads(), thread_db_get_ada_task_ptid(), thread_db_get_thread_local_address(), thread_db_wait(), and thread_get_info_callback().
static void thread_db_find_new_threads_2 (ptid_t ptid, int until_no_new) [static]
Definition at line 1665 of file linux-thread-db.c.
References _, error(), find_new_threads_once(), get_thread_db_info(), thread_db_info::proc_handle, ps_prochandle::ptid, ptid_get_pid(), TD_OK, and thread_db_err_str().
Referenced by thread_db_find_new_threads_1(), and thread_db_find_new_threads_silently().
static int thread_db_find_new_threads_silently (ptid_t ptid) [static]
Definition at line 661 of file linux-thread-db.c.
References _, exception_fprintf(), gdb_stderr, inferior_has_bug(), libthread_db_debug, gdb_exception::reason, RETURN_MASK_ERROR, target_has_execution, thread_db_find_new_threads_2(), and TRY_CATCH.
Referenced by try_thread_db_load_1().
static int thread_db_find_thread_from_tid (struct thread_info * thread, void * data) [static]
Definition at line 1856 of file linux-thread-db.c.
References thread_info::private, and private_thread_info::tid.
Referenced by thread_db_get_ada_task_ptid().
static ptid_t thread_db_get_ada_task_ptid (long lwp, long thread) [static]
Definition at line 1869 of file linux-thread-db.c.
References gdb_assert, inferior_ptid, iterate_over_threads(), thread_info::ptid, thread_db_find_new_threads_1(), and thread_db_find_thread_from_tid().
Referenced by init_thread_db_ops().
static CORE_ADDR thread_db_get_thread_local_address (struct target_ops * ops, ptid_t ptid, CORE_ADDR lm, CORE_ADDR offset) [static]
Definition at line 1782 of file linux-thread-db.c.
References _, target_ops::beneath, exec_bfd, find_target_beneath(), find_thread_ptid(), gdb_assert, get_thread_db_info(), have_threads(), thread_info::private, ptid_get_pid(), TD_NOTALLOC, TD_OK, thread_db_info::td_thr_tls_get_addr_p, private_thread_info::th, thread_db_err_str(), thread_db_find_new_threads_1(), throw_error(), TLS_GENERIC_ERROR, TLS_NO_LIBRARY_SUPPORT_ERROR, TLS_NOT_ALLOCATED_YET_ERROR, and target_ops::to_get_thread_local_address.
Referenced by init_thread_db_ops().
static void thread_db_inferior_created (struct target_ops * target, int from_tty) [static]
Definition at line 1214 of file linux-thread-db.c.
References check_for_thread_db().
Referenced by _initialize_thread_db().
static int thread_db_load (void) [static]
Definition at line 1091 of file linux-thread-db.c.
References _, core_bfd, current_target, get_thread_db_info(), has_libpthread(), inferior_ptid, ptid_get_pid(), target_can_run, target_has_registers, thread_db_load_search(), and warning().
Referenced by check_for_thread_db().
static int thread_db_load_search (void) [static]
Definition at line 1013 of file linux-thread-db.c.
References _, do_cleanups(), libthread_db_debug, libthread_db_search_path, make_cleanup(), make_cleanup_free_char_ptr_vec(), null_cleanup(), printf_unfiltered(), try_thread_db_load_from_dir(), try_thread_db_load_from_pdir(), try_thread_db_load_from_sdir(), VEC, VEC_iterate, xfree(), and xmalloc().
Referenced by thread_db_load().
static void thread_db_mourn_inferior (struct target_ops * ops) [static]
Definition at line 1527 of file linux-thread-db.c.
References delete_thread_db_info(), find_target_beneath(), inferior_ptid, ptid_get_pid(), remove_thread_event_breakpoints(), target_ops::to_mourn_inferior, and unpush_target().
Referenced by init_thread_db_ops().
static void thread_db_new_objfile (struct objfile * objfile) [static]
Definition at line 1185 of file linux-thread-db.c.
References check_for_thread_db(), objfile::flags, libpthread_name_p(), OBJF_MAINLINE, objfile_name(), and objfile::separate_debug_objfile_backlink.
Referenced by _initialize_thread_db().
static char* thread_db_pid_to_str (struct target_ops * ops, ptid_t ptid) [static]
Definition at line 1739 of file linux-thread-db.c.
References target_ops::beneath, find_target_beneath(), find_thread_ptid(), normal_pid_to_str(), thread_info::private, ptid_get_lwp(), private_thread_info::tid, and target_ops::to_pid_to_str.
Referenced by init_thread_db_ops().
static void thread_db_resume (struct target_ops * ops, ptid_t ptid, int step, enum gdb_signal signo) [static]
Definition at line 1882 of file linux-thread-db.c.
References target_ops::beneath, find_target_beneath(), get_thread_db_info(), inferior_ptid, minus_one_ptid, thread_db_info::need_stale_parent_threads_check, ptid_equal(), ptid_get_pid(), and target_ops::to_resume.
Referenced by init_thread_db_ops().
static ptid_t thread_db_wait (struct target_ops * ops, ptid_t ptid, struct target_waitstatus * ourstatus, int options) [static]
Definition at line 1471 of file linux-thread-db.c.
References target_ops::beneath, check_event(), delete_thread_db_info(), find_target_beneath(), get_thread_db_info(), have_threads(), target_waitstatus::kind, ptid_get_pid(), target_waitstatus::sig, TARGET_WAITKIND_EXECD, TARGET_WAITKIND_EXITED, TARGET_WAITKIND_IGNORE, TARGET_WAITKIND_SIGNALLED, TARGET_WAITKIND_STOPPED, thread_db_find_new_threads_1(), thread_db_ops, thread_from_lwp(), target_ops::to_wait, unpush_target(), and target_waitstatus::value.
Referenced by init_thread_db_ops().
static void thread_from_lwp (ptid_t ptid) [static]
Definition at line 443 of file linux-thread-db.c.
References _, error(), gdb_assert, get_thread_db_info(), thread_db_info::proc_handle, ps_prochandle::ptid, ptid_get_lwp(), ptid_get_pid(), TD_OK, thread_db_info::td_ta_map_lwp2thr_p, td_thrhandle::th_unique, thread_db_info::thread_agent, thread_db_err_str(), thread_get_info_inout::thread_db_info, thread_get_info_callback(), and thread_get_info_inout::thread_info.
Referenced by thread_db_wait().
static int thread_get_info_callback (const td_thrhandle_t * thp, void * argp) [static]
Definition at line 406 of file linux-thread-db.c.
References _, attach_thread(), error(), find_thread_ptid(), gdb_assert, have_threads(), thread_db_info::pid, ptid_build(), TD_OK, thread_db_info::td_thr_get_info_p, thread_db_err_str(), thread_db_find_new_threads_1(), thread_get_info_inout::thread_db_info, thread_get_info_inout::thread_info, and td_thrinfo::ti_lid.
Referenced by thread_from_lwp().
static int try_thread_db_load (const char * library) [static]
Definition at line 841 of file linux-thread-db.c.
References _, add_thread_db_info(), delete_thread_db_info(), dladdr_to_soname(), thread_db_info::filename, gdb_realpath(), inferior_ptid, libthread_db_debug, printf_unfiltered(), ptid_get_pid(), strchr(), td_init(), and try_thread_db_load_1().
Referenced by try_thread_db_load_from_dir(), try_thread_db_load_from_pdir_1(), and try_thread_db_load_from_sdir().
static int try_thread_db_load_1 (struct thread_db_info * info) [static]
Definition at line 724 of file linux-thread-db.c.
References _, dladdr_to_soname(), enable_thread_event_reporting(), thread_db_info::handle, inferior_ptid, libthread_db_debug, libthread_db_search_path, LIBTHREAD_DB_SO, thread_db_info::next, printf_unfiltered(), thread_db_info::proc_handle, ps_prochandle::ptid, push_target(), target_has_execution, thread_db_info::td_init_p, TD_NOLIBTHREAD, TD_OK, thread_db_info::td_ta_clear_event_p, thread_db_info::td_ta_event_addr_p, thread_db_info::td_ta_event_getmsg_p, thread_db_info::td_ta_map_id2thr_p, thread_db_info::td_ta_map_lwp2thr_p, thread_db_info::td_ta_new_p, thread_db_info::td_ta_set_event_p, thread_db_info::td_ta_thr_iter_p, thread_db_info::td_thr_event_enable_p, thread_db_info::td_thr_get_info_p, thread_db_info::td_thr_tls_get_addr_p, thread_db_info::td_thr_validate_p, TD_VERSION, thread_db_info::thread_agent, thread_db_err_str(), thread_db_find_new_threads_silently(), thread_db_ops, verbose_dlsym(), and warning().
Referenced by try_thread_db_load().
static int try_thread_db_load_from_dir (const char * dir, size_t dir_len) [static]
Definition at line 980 of file linux-thread-db.c.
References _, auto_load_thread_db, do_cleanups(), file_is_auto_load_safe(), LIBTHREAD_DB_SO, make_cleanup(), memcpy(), try_thread_db_load(), xfree(), and xmalloc().
Referenced by thread_db_load_search().
static int try_thread_db_load_from_pdir (const char * subdir) [static]
Definition at line 939 of file linux-thread-db.c.
References ALL_OBJFILES, auto_load_thread_db, libpthread_name_p(), objfile_name(), objfile::separate_debug_objfile_backlink, and try_thread_db_load_from_pdir_1().
Referenced by thread_db_load_search().
static int try_thread_db_load_from_pdir_1 (struct objfile * obj, const char * subdir) [static]
Definition at line 892 of file linux-thread-db.c.
References _, do_cleanups(), file_is_auto_load_safe(), gdb_assert, LIBTHREAD_DB_SO, make_cleanup(), objfile_name(), strrchr(), try_thread_db_load(), warning(), xfree(), and xmalloc().
Referenced by try_thread_db_load_from_pdir().
static int try_thread_db_load_from_sdir (void) [static]
Definition at line 971 of file linux-thread-db.c.
References LIBTHREAD_DB_SO, and try_thread_db_load().
Referenced by thread_db_load_search().
static int update_thread_core (struct lwp_info * info, void * closure) [static]
Definition at line 1703 of file linux-thread-db.c.
References lwp_info::core, linux_common_core_of_thread(), and lwp_info::ptid.
Referenced by thread_db_find_new_threads().
static void* verbose_dlsym (void * handle, const char * name) [static]
Definition at line 521 of file linux-thread-db.c.
References _, and warning().
Referenced by try_thread_db_load_1().
Variable Documentation
initialize_file_ftype _initialize_thread_db
Referenced by _initialize_thread_db(), and initialize_all_files().
int auto_load_thread_db = 1 [static]
Definition at line 80 of file linux-thread-db.c.
Referenced by _initialize_thread_db(), try_thread_db_load_from_dir(), and try_thread_db_load_from_pdir().
unsigned int libthread_db_debug [static]
Definition at line 106 of file linux-thread-db.c.
Referenced by _initialize_thread_db(), find_new_threads_once(), thread_db_find_new_threads_silently(), thread_db_load_search(), try_thread_db_load(), and try_thread_db_load_1().
char* libthread_db_search_path [static]
Definition at line 76 of file linux-thread-db.c.
Referenced by _initialize_thread_db(), set_libthread_db_search_path(), thread_db_load_search(), and try_thread_db_load_1().
struct thread_db_info* thread_db_list
Definition at line 203 of file linux-thread-db.c.
Referenced by add_thread_db_info().
struct target_ops thread_db_ops [static]
Definition at line 119 of file linux-thread-db.c.
Referenced by init_thread_db_ops(), thread_db_detach(), thread_db_wait(), and try_thread_db_load_1().
sigset_t thread_print_set [static]
Definition at line 125 of file linux-thread-db.c.
Referenced by check_thread_signals().
int thread_signals [static]
Definition at line 123 of file linux-thread-db.c.
Referenced by check_thread_signals().
sigset_t thread_stop_set [static]
Definition at line 124 of file linux-thread-db.c.
Referenced by check_thread_signals().