GDB (xrefs): /home/stan/gdb/src/gdb/common/linux-procfs.c File Reference
/home/stan/gdb/src/gdb/common/linux-procfs.c File Reference
#include "defs.h"
#include "gdb_string.h"
#include "linux-procfs.h"
#include "filestuff.h"
Functions
static int linux_proc_get_int (pid_t lwpid, const char *field)
int linux_proc_get_tgid (pid_t lwpid)
pid_t linux_proc_get_tracerpid (pid_t lwpid)
static int linux_proc_pid_has_state (pid_t pid, const char *state)
int linux_proc_pid_is_stopped (pid_t pid)
int linux_proc_pid_is_zombie (pid_t pid)
Function Documentation
static int linux_proc_get_int (pid_t lwpid, const char * field) [static]
Definition at line 33 of file linux-procfs.c.
References _, gdb_fopen_cloexec(), and warning().
Referenced by linux_proc_get_tgid(), and linux_proc_get_tracerpid().
int linux_proc_get_tgid (pid_t lwpid)
Definition at line 63 of file linux-procfs.c.
References linux_proc_get_int().
Referenced by find_new_threads_callback().
pid_t linux_proc_get_tracerpid (pid_t lwpid)
Definition at line 71 of file linux-procfs.c.
References linux_proc_get_int().
Referenced by linux_ptrace_attach_warnings().
static int linux_proc_pid_has_state (pid_t pid, const char * state) [static]
Definition at line 79 of file linux-procfs.c.
References _, gdb_fopen_cloexec(), strstr(), warning(), and xsnprintf().
Referenced by linux_proc_pid_is_stopped(), and linux_proc_pid_is_zombie().
int linux_proc_pid_is_stopped (pid_t pid)
Definition at line 110 of file linux-procfs.c.
References linux_proc_pid_has_state().
Referenced by linux_nat_post_attach_wait().
int linux_proc_pid_is_zombie (pid_t pid)
Definition at line 118 of file linux-procfs.c.
References linux_proc_pid_has_state().
Referenced by check_zombie_leaders(), linux_ptrace_attach_warnings(), and wait_lwp().