GDB (xrefs): /home/stan/gdb/src/gdb/m2-lang.c File Reference
/home/stan/gdb/src/gdb/m2-lang.c File Reference
#include "defs.h"
#include "symtab.h"
#include "gdbtypes.h"
#include "expression.h"
#include "parser-defs.h"
#include "language.h"
#include "m2-lang.h"
#include "c-lang.h"
#include "valprint.h"
Enumerations
enum m2_primitive_types {
m2_primitive_type_char, m2_primitive_type_int, m2_primitive_type_card, m2_primitive_type_real,
m2_primitive_type_bool, nr_m2_primitive_types
}
Functions
void _initialize_m2_language (void)
static void m2_printchar (int, struct type *, struct ui_file *)
static void m2_emit_char (int, struct type *, struct ui_file *, int)
static void m2_printstr (struct ui_file *stream, struct type *type, const gdb_byte *string, unsigned int length, const char *encoding, int force_ellipses, const struct value_print_options *options)
static struct value * evaluate_subexp_modula2 (struct type *expect_type, struct expression *exp, int *pos, enum noside noside)
static void m2_language_arch_info (struct gdbarch *gdbarch, struct language_arch_info *lai)
static void * build_m2_types (struct gdbarch *gdbarch)
struct builtin_m2_type * builtin_m2_type (struct gdbarch *gdbarch)
Variables
static struct op_print m2_op_print_tab []
struct exp_descriptor exp_descriptor_modula2
struct language_defn m2_language_defn
static struct gdbarch_data * m2_type_data
Enumeration Type Documentation
enum m2_primitive_types
Enumerator:
m2_primitive_type_char
m2_primitive_type_int
m2_primitive_type_card
m2_primitive_type_real
m2_primitive_type_bool
nr_m2_primitive_types
Definition at line 311 of file m2-lang.c.
Function Documentation
void _initialize_m2_language (void)
static void* build_m2_types (struct gdbarch * gdbarch) [static]
Definition at line 398 of file m2-lang.c.
References arch_boolean_type(), arch_character_type(), arch_float_type(), arch_integer_type(), builtin_m2_type::builtin_bool, builtin_m2_type::builtin_card, builtin_m2_type::builtin_char, builtin_m2_type::builtin_int, builtin_m2_type(), builtin_m2_type::builtin_real, gdbarch_float_bit(), gdbarch_int_bit(), and GDBARCH_OBSTACK_ZALLOC.
struct builtin_m2_type* builtin_m2_type (struct gdbarch * gdbarch) [read]
Definition at line 421 of file m2-lang.c.
References gdbarch_data().
Referenced by build_m2_types(), and m2_language_arch_info().
static struct value* evaluate_subexp_modula2 (struct type * expect_type, struct expression * exp, int * pos, enum noside noside) [static, read]
Definition at line 178 of file m2-lang.c.
References _, builtin_type::builtin_int, check_typedef(), coerce_ref(), expression::elts, error(), EVAL_AVOID_SIDE_EFFECTS, EVAL_SKIP, evaluate_subexp_standard(), evaluate_subexp_with_coercion(), expression::gdbarch, m2_is_unbounded_array(), exp_element::opcode, type, TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_PTR, TYPE_FIELD_TYPE, TYPE_NAME, TYPE_TARGET_TYPE, value_as_long(), value_cast(), value_from_longest(), value_ind(), VALUE_LVAL, value_ptradd(), value_struct_elt(), value_subscript(), value_type(), value_zero(), and warning().
static void m2_emit_char (int c, struct type * type, struct ui_file * stream, int quoter) [static]
Definition at line 41 of file m2-lang.c.
References fprintf_filtered(), fputs_filtered(), and PRINT_LITERAL_FORM.
static void m2_language_arch_info (struct gdbarch * gdbarch, struct language_arch_info * lai) [static]
Definition at line 321 of file m2-lang.c.
References language_arch_info::bool_type_default, language_arch_info::bool_type_symbol, builtin_m2_type::builtin_bool, builtin_m2_type::builtin_card, builtin_m2_type::builtin_char, builtin_m2_type::builtin_int, builtin_m2_type(), builtin_m2_type::builtin_real, GDBARCH_OBSTACK_CALLOC, m2_primitive_type_bool, m2_primitive_type_card, m2_primitive_type_char, m2_primitive_type_int, m2_primitive_type_real, nr_m2_primitive_types, language_arch_info::primitive_type_vector, and language_arch_info::string_char_type.
static void m2_printchar (int c, struct type * type, struct ui_file * stream) [static]
Definition at line 90 of file m2-lang.c.
References fputs_filtered(), and LA_EMIT_CHAR.
Referenced by m2_printstr().
static void m2_printstr (struct ui_file * stream, struct type * type, const gdb_byte * string, unsigned int length, const char * encoding, int force_ellipses, const struct value_print_options * options) [static]
Definition at line 105 of file m2-lang.c.
References fprintf_filtered(), fputs_filtered(), gdb_stdout, LA_EMIT_CHAR, m2_printchar(), value_print_options::print_max, QUIT, and value_print_options::repeat_count_threshold.
Variable Documentation
struct exp_descriptor exp_descriptor_modula2
Initial value:
{
  print_subexp_standard,
  operator_length_standard,
  operator_check_standard,
  op_name_standard,
  dump_subexp_body_standard,
  evaluate_subexp_modula2
}
Definition at line 346 of file m2-lang.c.
struct language_defn m2_language_defn
Definition at line 356 of file m2-lang.c.
struct op_print m2_op_print_tab[] [static]
Definition at line 275 of file m2-lang.c.
struct gdbarch_data* m2_type_data [static]
Definition at line 418 of file m2-lang.c.