GDB (xrefs): /home/stan/gdb/src/gdb/m2-typeprint.c File Reference
/home/stan/gdb/src/gdb/m2-typeprint.c File Reference
#include "defs.h"
#include "gdb_obstack.h"
#include "bfd.h"
#include "symtab.h"
#include "gdbtypes.h"
#include "expression.h"
#include "value.h"
#include "gdbcore.h"
#include "m2-lang.h"
#include "target.h"
#include "language.h"
#include "demangle.h"
#include "c-lang.h"
#include "typeprint.h"
#include "cp-abi.h"
#include "gdb_string.h"
#include <errno.h>
Functions
static void m2_print_bounds (struct type *type, struct ui_file *stream, int show, int level, int print_high)
static void m2_typedef (struct type *, struct ui_file *, int, int, const struct type_print_options *)
static void m2_array (struct type *, struct ui_file *, int, int, const struct type_print_options *)
static void m2_pointer (struct type *, struct ui_file *, int, int, const struct type_print_options *)
static void m2_ref (struct type *, struct ui_file *, int, int, const struct type_print_options *)
static void m2_procedure (struct type *, struct ui_file *, int, int, const struct type_print_options *)
static void m2_union (struct type *, struct ui_file *)
static void m2_enum (struct type *, struct ui_file *, int, int)
static void m2_range (struct type *, struct ui_file *, int, int, const struct type_print_options *)
static void m2_type_name (struct type *type, struct ui_file *stream)
static void m2_short_set (struct type *type, struct ui_file *stream, int show, int level)
static int m2_long_set (struct type *type, struct ui_file *stream, int show, int level, const struct type_print_options *flags)
static int m2_unbounded_array (struct type *type, struct ui_file *stream, int show, int level, const struct type_print_options *flags)
static void m2_record_fields (struct type *type, struct ui_file *stream, int show, int level, const struct type_print_options *flags)
static void m2_unknown (const char *s, struct type *type, struct ui_file *stream, int show, int level)
int m2_is_long_set (struct type *type)
int m2_is_long_set_of_type (struct type *type, struct type **of_type)
int m2_is_unbounded_array (struct type *type)
void m2_print_type (struct type *type, const char *varstring, struct ui_file *stream, int show, int level, const struct type_print_options *flags)
void m2_print_typedef (struct type *type, struct symbol *new_symbol, struct ui_file *stream)
static int m2_get_discrete_bounds (struct type *type, LONGEST *lowp, LONGEST *highp)
Function Documentation
static void m2_array (struct type * type, struct ui_file * stream, int show, int level, const struct type_print_options * flags) [static]
Definition at line 222 of file m2-typeprint.c.
References fprintf_filtered(), m2_print_bounds(), m2_print_type(), TYPE_ARRAY_UPPER_BOUND_IS_UNDEFINED, TYPE_INDEX_TYPE, TYPE_LENGTH, and TYPE_TARGET_TYPE.
Referenced by m2_print_type().
void m2_enum (struct type * type, struct ui_file * stream, int show, int level) [static]
Definition at line 594 of file m2-typeprint.c.
References fprintf_filtered(), fputs_filtered(), len, LONGEST, plongest(), QUIT, TYPE_FIELD_ENUMVAL, TYPE_FIELD_NAME, TYPE_NFIELDS, TYPE_TAG_NAME, and wrap_here().
Referenced by m2_print_type().
static int m2_get_discrete_bounds (struct type * type, LONGEST * lowp, LONGEST * highp) [static]
Definition at line 373 of file m2-typeprint.c.
References CHECK_TYPEDEF, get_discrete_bounds(), LONGEST, TYPE_CODE, TYPE_CODE_CHAR, TYPE_LENGTH, and TYPE_UNSIGNED.
Referenced by m2_is_long_set_of_type().
int m2_is_long_set (struct type * type)
Definition at line 334 of file m2-typeprint.c.
References len, LONGEST, range, TYPE_CODE, TYPE_CODE_SET, TYPE_CODE_STRUCT, TYPE_FIELD_NAME, TYPE_FIELD_TYPE, TYPE_HIGH_BOUND, TYPE_INDEX_TYPE, TYPE_LOW_BOUND, TYPE_N_BASECLASSES, and TYPE_NFIELDS.
Referenced by m2_long_set(), and m2_val_print().
int m2_is_long_set_of_type (struct type * type, struct type ** of_type)
Definition at line 399 of file m2-typeprint.c.
References _, error(), len, LONGEST, m2_get_discrete_bounds(), range, TYPE_CODE, TYPE_CODE_STRUCT, TYPE_FIELD_TYPE, TYPE_HIGH_BOUND, TYPE_INDEX_TYPE, TYPE_LOW_BOUND, TYPE_N_BASECLASSES, TYPE_NFIELDS, and TYPE_TARGET_TYPE.
Referenced by m2_long_set().
int m2_is_unbounded_array (struct type * type)
Definition at line 488 of file m2-typeprint.c.
References TYPE_CODE, TYPE_CODE_PTR, TYPE_CODE_STRUCT, TYPE_FIELD_NAME, TYPE_FIELD_TYPE, and TYPE_NFIELDS.
Referenced by evaluate_subexp_modula2(), m2_unbounded_array(), and m2_val_print().
static int m2_long_set (struct type * type, struct ui_file * stream, int show, int level, const struct type_print_options * flags) [static]
Definition at line 429 of file m2-typeprint.c.
References _, fprintf_filtered(), fputs_filtered(), get_long_set_bounds(), len, LONGEST, m2_is_long_set(), m2_is_long_set_of_type(), m2_print_bounds(), m2_print_type(), TYPE_FIELD_TYPE, TYPE_INDEX_TYPE, TYPE_N_BASECLASSES, TYPE_NAME, TYPE_NFIELDS, and TYPE_TAG_NAME.
Referenced by m2_print_type().
static void m2_pointer (struct type * type, struct ui_file * stream, int show, int level, const struct type_print_options * flags) [static]
Definition at line 245 of file m2-typeprint.c.
References fprintf_filtered(), m2_print_type(), TYPE_CONST, and TYPE_TARGET_TYPE.
Referenced by m2_print_type().
static void m2_print_bounds (struct type * type, struct ui_file * stream, int show, int level, int print_high) [static]
Definition at line 305 of file m2-typeprint.c.
References print_type_scalar(), TYPE_HIGH_BOUND, TYPE_LOW_BOUND, TYPE_NFIELDS, and TYPE_TARGET_TYPE.
Referenced by m2_array(), m2_long_set(), and m2_short_set().
void m2_print_type (struct type * type, const char * varstring, struct ui_file * stream, int show, int level, const struct type_print_options * flags)
Definition at line 75 of file m2-typeprint.c.
References _, CHECK_TYPEDEF, fputs_filtered(), m2_array(), m2_enum(), m2_long_set(), m2_pointer(), m2_procedure(), m2_range(), m2_record_fields(), m2_ref(), m2_short_set(), m2_type_name(), m2_typedef(), m2_unbounded_array(), m2_union(), m2_unknown(), QUIT, TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_ENUM, TYPE_CODE_ERROR, TYPE_CODE_FUNC, TYPE_CODE_METHOD, TYPE_CODE_PTR, TYPE_CODE_RANGE, TYPE_CODE_REF, TYPE_CODE_SET, TYPE_CODE_STRUCT, TYPE_CODE_TYPEDEF, TYPE_CODE_UNDEF, TYPE_CODE_UNION, TYPE_CODE_VOID, and wrap_here().
Referenced by m2_array(), m2_long_set(), m2_pointer(), m2_procedure(), m2_range(), m2_record_fields(), m2_ref(), m2_typedef(), and m2_unbounded_array().
void m2_print_typedef (struct type * type, struct symbol * new_symbol, struct ui_file * stream)
Definition at line 163 of file m2-typeprint.c.
References CHECK_TYPEDEF, fprintf_filtered(), SYMBOL_LINKAGE_NAME, SYMBOL_PRINT_NAME, SYMBOL_TYPE, TYPE_NAME, and type_print().
static void m2_procedure (struct type * type, struct ui_file * stream, int show, int level, const struct type_print_options * flags) [static]
Definition at line 277 of file m2-typeprint.c.
References fprintf_filtered(), fputs_filtered(), len, m2_print_type(), m2_type_name(), TYPE_CODE, TYPE_CODE_VOID, TYPE_FIELD_TYPE, TYPE_NFIELDS, TYPE_TARGET_TYPE, and wrap_here().
Referenced by m2_print_type().
void m2_range (struct type * type, struct ui_file * stream, int show, int level, const struct type_print_options * flags) [static]
Definition at line 190 of file m2-typeprint.c.
References fprintf_filtered(), m2_print_type(), print_type_scalar(), TYPE_DOMAIN_TYPE, TYPE_HIGH_BOUND, TYPE_LOW_BOUND, and TYPE_TARGET_TYPE.
Referenced by m2_print_type().
void m2_record_fields (struct type * type, struct ui_file * stream, int show, int level, const struct type_print_options * flags) [static]
Definition at line 534 of file m2-typeprint.c.
References _, fprintf_filtered(), fprintfi_filtered(), fputs_filtered(), len, m2_print_type(), print_spaces_filtered(), QUIT, TYPE_CODE, TYPE_CODE_STRUCT, TYPE_CODE_UNION, TYPE_FIELD_BITSIZE, TYPE_FIELD_NAME, TYPE_FIELD_PACKED, TYPE_FIELD_TYPE, TYPE_N_BASECLASSES, TYPE_NFIELDS, TYPE_TAG_NAME, and wrap_here().
Referenced by m2_print_type().
static void m2_ref (struct type * type, struct ui_file * stream, int show, int level, const struct type_print_options * flags) [static]
Definition at line 257 of file m2-typeprint.c.
References fprintf_filtered(), m2_print_type(), and TYPE_TARGET_TYPE.
Referenced by m2_print_type().
static void m2_short_set (struct type * type, struct ui_file * stream, int show, int level) [static]
Definition at line 321 of file m2-typeprint.c.
References fprintf_filtered(), m2_print_bounds(), and TYPE_INDEX_TYPE.
Referenced by m2_print_type().
void m2_type_name (struct type * type, struct ui_file * stream) [static]
Definition at line 181 of file m2-typeprint.c.
References fputs_filtered(), and TYPE_NAME.
Referenced by m2_print_type(), and m2_procedure().
static void m2_typedef (struct type * type, struct ui_file * stream, int show, int level, const struct type_print_options * flags) [static]
Definition at line 209 of file m2-typeprint.c.
References fputs_filtered(), m2_print_type(), TYPE_NAME, and TYPE_TARGET_TYPE.
Referenced by m2_print_type().
static int m2_unbounded_array (struct type * type, struct ui_file * stream, int show, int level, const struct type_print_options * flags) [static]
Definition at line 517 of file m2-typeprint.c.
References fputs_filtered(), m2_is_unbounded_array(), m2_print_type(), TYPE_FIELD_TYPE, and TYPE_TARGET_TYPE.
Referenced by m2_print_type().
static void m2_union (struct type * type, struct ui_file * stream) [static]
Definition at line 271 of file m2-typeprint.c.
References fprintf_filtered().
Referenced by m2_print_type().
static void m2_unknown (const char * s, struct type * type, struct ui_file * stream, int show, int level) [static]
Definition at line 265 of file m2-typeprint.c.
References _, and fprintf_filtered().
Referenced by m2_print_type().