GDB (xrefs): /home/stan/gdb/src/gdb/m2-valprint.c File Reference
/home/stan/gdb/src/gdb/m2-valprint.c File Reference
#include "defs.h"
#include "symtab.h"
#include "gdbtypes.h"
#include "expression.h"
#include "value.h"
#include "valprint.h"
#include "language.h"
#include "typeprint.h"
#include "c-lang.h"
#include "m2-lang.h"
#include "target.h"
Functions
static int print_unpacked_pointer (struct type *type, CORE_ADDR address, CORE_ADDR addr, const struct value_print_options *options, struct ui_file *stream)
static void m2_print_array_contents (struct type *type, const gdb_byte *valaddr, int embedded_offset, CORE_ADDR address, struct ui_file *stream, int recurse, const struct value *val, const struct value_print_options *options, int len)
int get_long_set_bounds (struct type *type, LONGEST *low, LONGEST *high)
static void m2_print_long_set (struct type *type, const gdb_byte *valaddr, int embedded_offset, CORE_ADDR address, struct ui_file *stream)
static void m2_print_unbounded_array (struct type *type, const gdb_byte *valaddr, int embedded_offset, CORE_ADDR address, struct ui_file *stream, int recurse, const struct value_print_options *options)
static void print_variable_at_address (struct type *type, const gdb_byte *valaddr, struct ui_file *stream, int recurse, const struct value_print_options *options)
void m2_val_print (struct type *type, const gdb_byte *valaddr, int embedded_offset, CORE_ADDR address, struct ui_file *stream, int recurse, const struct value *original_value, const struct value_print_options *options)
Variables
static struct
generic_val_print_decorations m2_decorations
Function Documentation
int get_long_set_bounds (struct type * type, LONGEST * low, LONGEST * high)
Definition at line 49 of file m2-valprint.c.
References _, error(), len, TYPE_CODE, TYPE_CODE_STRUCT, TYPE_FIELD_TYPE, TYPE_HIGH_BOUND, TYPE_INDEX_TYPE, TYPE_LOW_BOUND, TYPE_N_BASECLASSES, and TYPE_NFIELDS.
Referenced by m2_long_set(), and m2_print_long_set().
static void m2_print_array_contents (struct type * type, const gdb_byte * valaddr, int embedded_offset, CORE_ADDR address, struct ui_file * stream, int recurse, const struct value * val, const struct value_print_options * options, int len) [static]
Definition at line 264 of file m2-valprint.c.
References CHECK_TYPEDEF, current_language, value_print_options::format, fprintf_filtered(), language_defn::la_language, language_m2, value_print_options::prettyformat_arrays, print_spaces_filtered(), TYPE_CODE, TYPE_CODE_CHAR, TYPE_CODE_INT, TYPE_LENGTH, val_print_array_elements(), and val_print_string().
Referenced by m2_print_unbounded_array().
static void m2_print_long_set (struct type * type, const gdb_byte * valaddr, int embedded_offset, CORE_ADDR address, struct ui_file * stream) [static]
Definition at line 69 of file m2-valprint.c.
References _, CHECK_TYPEDEF, error(), fprintf_filtered(), get_discrete_bounds(), get_long_set_bounds(), len, LONGEST, print_type_scalar(), range, TYPE_FIELD_BITPOS, TYPE_FIELD_TYPE, TYPE_INDEX_TYPE, TYPE_N_BASECLASSES, TYPE_NFIELDS, TYPE_TARGET_TYPE, and value_bit_index().
Referenced by m2_val_print().
static void m2_print_unbounded_array (struct type * type, const gdb_byte * valaddr, int embedded_offset, CORE_ADDR address, struct ui_file * stream, int recurse, const struct value_print_options * options) [static]
Definition at line 160 of file m2-valprint.c.
References CHECK_TYPEDEF, fprintf_filtered(), len, LONGEST, m2_print_array_contents(), TYPE_FIELD_BITPOS, TYPE_FIELD_TYPE, TYPE_TARGET_TYPE, unpack_field_as_long(), unpack_pointer(), value_at_lazy(), value_contents_for_printing(), value_embedded_offset(), and value_type().
Referenced by m2_val_print().
void m2_val_print (struct type * type, const gdb_byte * valaddr, int embedded_offset, CORE_ADDR address, struct ui_file * stream, int recurse, const struct value * original_value, const struct value_print_options * options)
Definition at line 311 of file m2-valprint.c.
References _, check_typedef(), CHECK_TYPEDEF, cp_print_value_fields(), current_language, value_print_options::format, fprintf_filtered(), fputs_filtered(), gdb_flush(), generic_val_print(), get_discrete_bounds(), get_type_arch(), language_defn::la_language, LA_PRINT_STRING, language_m2, len, LONGEST, m2_is_long_set(), m2_is_unbounded_array(), m2_print_long_set(), m2_print_unbounded_array(), m2_val_print(), value_print_options::prettyformat_arrays, print_spaces_filtered(), print_type_scalar(), print_unpacked_pointer(), print_variable_at_address(), value_print_options::stop_print_at_null, TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_BOOL, TYPE_CODE_CHAR, TYPE_CODE_ENUM, TYPE_CODE_ERROR, TYPE_CODE_FLT, TYPE_CODE_FUNC, TYPE_CODE_INT, TYPE_CODE_METHOD, TYPE_CODE_PTR, TYPE_CODE_RANGE, TYPE_CODE_REF, TYPE_CODE_SET, TYPE_CODE_STRUCT, TYPE_CODE_UNDEF, TYPE_CODE_UNION, TYPE_CODE_VOID, TYPE_CONST, TYPE_INDEX_TYPE, TYPE_LENGTH, TYPE_STUB, TYPE_TARGET_TYPE, value_print_options::unionprint, unpack_pointer(), val_print_array_elements(), val_print_scalar_formatted(), and value_bit_index().
Referenced by m2_val_print().
static int print_unpacked_pointer (struct type * type, CORE_ADDR address, CORE_ADDR addr, const struct value_print_options * options, struct ui_file * stream) [static]
Definition at line 190 of file m2-valprint.c.
References value_print_options::addressprint, check_typedef(), value_print_options::format, fputs_filtered(), get_type_arch(), paddress(), print_function_pointer_address(), TYPE_CODE, TYPE_CODE_FUNC, TYPE_CODE_INT, TYPE_LENGTH, TYPE_TARGET_TYPE, and val_print_string().
Referenced by c_val_print(), generic_val_print(), m2_val_print(), and pascal_val_print().
static void print_variable_at_address (struct type * type, const gdb_byte * valaddr, struct ui_file * stream, int recurse, const struct value_print_options * options) [static]
Definition at line 231 of file m2-valprint.c.
References check_typedef(), common_val_print(), current_language, fprintf_filtered(), fputs_filtered(), get_type_arch(), paddress(), TYPE_CODE, TYPE_CODE_UNDEF, TYPE_TARGET_TYPE, unpack_pointer(), and value_at().
Referenced by m2_val_print().
Variable Documentation
struct generic_val_print_decorations m2_decorations [static]
Initial value:
{
  "",
  " + ",
  " * I",
  "TRUE",
  "FALSE",
  "void"
}
Definition at line 297 of file m2-valprint.c.