GDB (xrefs): /home/stan/gdb/src/gdb/m32r-rom.c File Reference
/home/stan/gdb/src/gdb/m32r-rom.c File Reference
#include "defs.h"
#include "gdbcore.h"
#include "target.h"
#include "exceptions.h"
#include "monitor.h"
#include "serial.h"
#include "symtab.h"
#include "command.h"
#include "gdbcmd.h"
#include "symfile.h"
#include <sys/time.h>
#include <time.h>
#include "gdb_string.h"
#include "objfiles.h"
#include "inferior.h"
#include <ctype.h>
#include "regcache.h"
#include "gdb_bfd.h"
#include "cli/cli-utils.h"
#include <sys/types.h>
#include <netdb.h>
#include <netinet/in.h>
#include <arpa/inet.h>
Defines
#define PSW_REGNUM 16
#define SPI_REGNUM 18
#define SPU_REGNUM 19
#define ACCL_REGNUM 22
#define ACCH_REGNUM 23
Functions
static void m32r_load_section (bfd *abfd, asection *s, void *obj)
static int m32r_load_1 (void *dummy)
static void m32r_load (char *filename, int from_tty)
static void m32r_load_gen (char *filename, int from_tty)
static void m32r_open (char *args, int from_tty)
static void mon2000_open (char *args, int from_tty)
static void m32r_supply_register (struct regcache *regcache, char *regname, int regnamelen, char *val, int vallen)
static void init_m32r_cmds (void)
static void init_mon2000_cmds (void)
static void m32r_upload_command (char *args, int from_tty)
void _initialize_m32r_rom (void)
Variables
static char * board_addr
static char * server_addr
static char * download_path
static char * m32r_regnames []
static struct target_ops m32r_ops
static char * m32r_inits [] = { "\r", NULL }
static struct monitor_ops m32r_cmds
static struct target_ops mon2000_ops
static struct monitor_ops mon2000_cmds
initialize_file_ftype _initialize_m32r_rom
Define Documentation
#define ACCH_REGNUM 23
Definition at line 69 of file m32r-rom.c.
Referenced by m32r_supply_register().
#define ACCL_REGNUM 22
Definition at line 68 of file m32r-rom.c.
Referenced by m32r_supply_register().
#define PSW_REGNUM 16
Definition at line 65 of file m32r-rom.c.
Referenced by m32r_supply_register().
#define SPI_REGNUM 18
Definition at line 66 of file m32r-rom.c.
Referenced by m32r_supply_register().
#define SPU_REGNUM 19
Definition at line 67 of file m32r-rom.c.
Referenced by m32r_supply_register().
Function Documentation
void _initialize_m32r_rom (void)
Definition at line 579 of file m32r-rom.c.
References _, _initialize_m32r_rom, add_com(), add_setshow_string_cmd(), add_target(), board_addr, class_obscure, download_path, init_m32r_cmds(), init_mon2000_cmds(), init_monitor_ops(), m32r_load(), m32r_load_gen(), m32r_open(), m32r_ops, m32r_upload_command(), mon2000_open(), mon2000_ops, server_addr, setlist, showlist, target_ops::to_doc, target_ops::to_load, target_ops::to_longname, target_ops::to_open, and target_ops::to_shortname.
static void init_m32r_cmds (void) [static]
Definition at line 316 of file m32r-rom.c.
References monitor_ops::clr_all_break, monitor_ops::clr_break, regrw_cmd::cmd, monitor_ops::cmd_end, memrw_cmd::cmdb, memrw_cmd::cmdl, memrw_cmd::cmdll, memrw_cmd::cmdw, monitor_ops::cont, monitor_ops::dump_registers, monitor_ops::fill, monitor_ops::flags, monitor_ops::getmem, monitor_ops::getreg, monitor_ops::init, monitor_ops::line_term, monitor_ops::load, monitor_ops::loadresp, m32r_cmds, m32r_inits, m32r_ops, m32r_regnames, m32r_supply_register(), monitor_ops::magic, MO_CLR_BREAK_USES_ADDR, MO_REGISTER_VALUE_FIRST, MONITOR_OPS_MAGIC, monitor_ops::prompt, monitor_ops::register_pattern, monitor_ops::regnames, memrw_cmd::resp_delim, regrw_cmd::resp_delim, SERIAL_1_STOPBITS, monitor_ops::set_break, monitor_ops::setmem, monitor_ops::setreg, monitor_ops::step, monitor_ops::stop, monitor_ops::stopbits, monitor_ops::supply_register, monitor_ops::target, memrw_cmd::term, regrw_cmd::term, memrw_cmd::term_cmd, and regrw_cmd::term_cmd.
Referenced by _initialize_m32r_rom().
static void init_mon2000_cmds (void) [static]
Definition at line 376 of file m32r-rom.c.
References monitor_ops::clr_all_break, monitor_ops::clr_break, regrw_cmd::cmd, monitor_ops::cmd_end, memrw_cmd::cmdb, memrw_cmd::cmdl, memrw_cmd::cmdll, memrw_cmd::cmdw, monitor_ops::cont, monitor_ops::dump_registers, monitor_ops::fill, monitor_ops::flags, monitor_ops::getmem, monitor_ops::getreg, monitor_ops::init, monitor_ops::line_term, monitor_ops::load, monitor_ops::loadresp, m32r_inits, m32r_regnames, m32r_supply_register(), monitor_ops::magic, MO_CLR_BREAK_USES_ADDR, MO_REGISTER_VALUE_FIRST, mon2000_cmds, mon2000_ops, MONITOR_OPS_MAGIC, monitor_ops::prompt, monitor_ops::register_pattern, monitor_ops::regnames, memrw_cmd::resp_delim, regrw_cmd::resp_delim, SERIAL_1_STOPBITS, monitor_ops::set_break, monitor_ops::setmem, monitor_ops::setreg, monitor_ops::step, monitor_ops::stop, monitor_ops::stopbits, monitor_ops::supply_register, monitor_ops::target, memrw_cmd::term, regrw_cmd::term, memrw_cmd::term_cmd, and regrw_cmd::term_cmd.
Referenced by _initialize_m32r_rom().
static void m32r_load (char * filename, int from_tty) [static]
Definition at line 123 of file m32r-rom.c.
References _, catch_errors(), clear_symtab_users(), do_cleanups(), error(), exec_bfd, fputs_filtered(), gdb_bfd_open(), gdb_flush(), gdb_stdout, get_current_regcache(), get_exec_file(), inferior_ptid, m32r_load_1(), make_cleanup_bfd_unref(), monitor_expect(), monitor_expect_prompt(), monitor_printf(), null_ptid, paddress(), print_transfer_performance(), printf_filtered(), regcache_write_pc(), RETURN_MASK_ALL, and target_gdbarch().
Referenced by _initialize_m32r_rom().
static int m32r_load_1 (void * dummy) [static]
Definition at line 110 of file m32r-rom.c.
References m32r_load_section().
Referenced by m32r_load().
static void m32r_load_gen (char * filename, int from_tty) [static]
Definition at line 199 of file m32r-rom.c.
References generic_load().
Referenced by _initialize_m32r_rom().
static void m32r_load_section (bfd * abfd, asection * s, void * obj) [static]
Definition at line 77 of file m32r-rom.c.
References fputs_filtered(), gdb_flush(), gdb_stdout, gdbarch_addr_bit(), monitor_expect(), monitor_expect_prompt(), monitor_printf(), paddress(), phex_nz(), printf_filtered(), QUIT, and target_gdbarch().
Referenced by m32r_load_1().
static void m32r_open (char * args, int from_tty) [static]
Definition at line 365 of file m32r-rom.c.
References m32r_cmds, and monitor_open().
Referenced by _initialize_m32r_rom().
static void m32r_supply_register (struct regcache * regcache, char * regname, int regnamelen, char * val, int vallen) [static]
Definition at line 219 of file m32r-rom.c.
References ACCH_REGNUM, ACCL_REGNUM, CBR_REGNUM, gdbarch_sp_regnum(), get_regcache_arch(), m32r_regnames, monitor_supply_register(), gdbarch::num_regs, PSW_REGNUM, regcache_cooked_read_unsigned(), SPI_REGNUM, SPU_REGNUM, strchr(), and ULONGEST.
Referenced by init_m32r_cmds(), and init_mon2000_cmds().
static void m32r_upload_command (char * args, int from_tty) [static]
Definition at line 431 of file m32r-rom.c.
References _, board_addr, clear_symtab_users(), current_directory, do_cleanups(), download_path, error(), fputs_filtered(), gdb_bfd_open(), gdb_flush(), gdb_stdout, get_current_regcache(), get_exec_file(), inferior_ptid, make_cleanup_bfd_unref(), memcpy(), monitor_expect_prompt(), monitor_printf(), null_ptid, paddress(), print_transfer_performance(), printf_filtered(), regcache_write_pc(), server_addr, skip_spaces(), strchr(), strrchr(), strstr(), and target_gdbarch().
Referenced by _initialize_m32r_rom().
static void mon2000_open (char * args, int from_tty) [static]
Definition at line 425 of file m32r-rom.c.
References mon2000_cmds, and monitor_open().
Referenced by _initialize_m32r_rom().
Variable Documentation
initialize_file_ftype _initialize_m32r_rom
Referenced by _initialize_m32r_rom(), and initialize_all_files().
char* board_addr [static]
Definition at line 59 of file m32r-rom.c.
Referenced by _initialize_m32r_rom(), and m32r_upload_command().
char* download_path [static]
Definition at line 61 of file m32r-rom.c.
Referenced by _initialize_m32r_rom(), and m32r_upload_command().
struct monitor_ops m32r_cmds [static]
Definition at line 313 of file m32r-rom.c.
Referenced by init_m32r_cmds(), and m32r_open().
char* m32r_inits[] = { "\r", NULL } [static]
Definition at line 311 of file m32r-rom.c.
Referenced by init_m32r_cmds(), and init_mon2000_cmds().
struct target_ops m32r_ops [static]
Definition at line 309 of file m32r-rom.c.
Referenced by _initialize_m32r_rom(), and init_m32r_cmds().
char* m32r_regnames[] [static]
Initial value:
  { "r0", "r1", "r2", "r3", "r4", "r5", "r6", "r7",
  "r8", "r9", "r10", "r11", "r12", "r13", "r14", "r15",
  "psw", "cbr", "spi", "spu", "bpc", "pc", "accl", "acch",
}
Definition at line 212 of file m32r-rom.c.
Referenced by init_m32r_cmds(), init_mon2000_cmds(), and m32r_supply_register().
struct monitor_ops mon2000_cmds [static]
Definition at line 373 of file m32r-rom.c.
Referenced by init_mon2000_cmds(), and mon2000_open().
struct target_ops mon2000_ops [static]
Definition at line 372 of file m32r-rom.c.
Referenced by _initialize_m32r_rom(), and init_mon2000_cmds().
char* server_addr [static]
Definition at line 60 of file m32r-rom.c.
Referenced by _initialize_m32r_rom(), and m32r_upload_command().