GDB (xrefs): /home/stan/gdb/src/gdb/m32r-linux-tdep.c File Reference
/home/stan/gdb/src/gdb/m32r-linux-tdep.c File Reference
#include "defs.h"
#include "gdbcore.h"
#include "frame.h"
#include "value.h"
#include "regcache.h"
#include "inferior.h"
#include "osabi.h"
#include "reggroups.h"
#include "regset.h"
#include "gdb_string.h"
#include "glibc-tdep.h"
#include "solib-svr4.h"
#include "symtab.h"
#include "trad-frame.h"
#include "frame-unwind.h"
#include "m32r-tdep.h"
#include "linux-tdep.h"
Classes
struct m32r_frame_cache
Defines
#define PSW_OFFSET (4 * 19)
#define BBPSW_OFFSET (4 * 21)
#define SPU_OFFSET (4 * 23)
#define SPI_OFFSET (4 * 26)
Functions
static CORE_ADDR m32r_linux_sigtramp_start (CORE_ADDR pc, struct frame_info *this_frame)
static CORE_ADDR m32r_linux_rt_sigtramp_start (CORE_ADDR pc, struct frame_info *this_frame)
static int m32r_linux_pc_in_sigtramp (CORE_ADDR pc, const char *name, struct frame_info *this_frame)
static struct m32r_frame_cache * m32r_linux_sigtramp_frame_cache (struct frame_info *this_frame, void **this_cache)
static void m32r_linux_sigtramp_frame_this_id (struct frame_info *this_frame, void **this_cache, struct frame_id *this_id)
static struct value * m32r_linux_sigtramp_frame_prev_register (struct frame_info *this_frame, void **this_cache, int regnum)
static int m32r_linux_sigtramp_frame_sniffer (const struct frame_unwind *self, struct frame_info *this_frame, void **this_cache)
static void m32r_linux_supply_gregset (const struct regset *regset, struct regcache *regcache, int regnum, const void *gregs, size_t size)
static struct regset * m32r_linux_regset_from_core_section (struct gdbarch *core_arch, const char *sect_name, size_t sect_size)
static void m32r_linux_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
void _initialize_m32r_linux_tdep (void)
Variables
static const gdb_byte linux_sigtramp_code []
static const gdb_byte linux_rt_sigtramp_code []
static int m32r_linux_sc_reg_offset []
static struct frame_unwind m32r_linux_sigtramp_frame_unwind
static int m32r_pt_regs_offset []
static struct regset m32r_linux_gregset
Define Documentation
#define BBPSW_OFFSET (4 * 21)
Definition at line 345 of file m32r-linux-tdep.c.
Referenced by m32r_linux_supply_gregset().
#define PSW_OFFSET (4 * 19)
Definition at line 344 of file m32r-linux-tdep.c.
Referenced by m32r_linux_supply_gregset().
#define SPI_OFFSET (4 * 26)
Definition at line 347 of file m32r-linux-tdep.c.
Referenced by m32r_linux_supply_gregset().
#define SPU_OFFSET (4 * 23)
Definition at line 346 of file m32r-linux-tdep.c.
Referenced by m32r_linux_supply_gregset().
Function Documentation
void _initialize_m32r_linux_tdep (void)
static void m32r_linux_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch) [static]
Definition at line 406 of file m32r-linux-tdep.c.
References find_solib_trampoline_target(), frame_unwind_append_unwinder(), gdbarch_tdep(), linux_init_abi(), m32r_linux_regset_from_core_section(), M32R_NUM_REGS, set_gdbarch_fetch_tls_load_module_address(), set_gdbarch_num_regs(), set_gdbarch_regset_from_core_section(), set_gdbarch_skip_trampoline_code(), set_solib_svr4_fetch_link_map_offsets(), svr4_fetch_objfile_link_map(), and svr4_ilp32_fetch_link_map_offsets().
static int m32r_linux_pc_in_sigtramp (CORE_ADDR pc, const char * name, struct frame_info * this_frame) [static]
Definition at line 176 of file m32r-linux-tdep.c.
References m32r_linux_rt_sigtramp_start(), m32r_linux_sigtramp_start(), and strstr().
Referenced by m32r_linux_sigtramp_frame_sniffer().
static struct regset* m32r_linux_regset_from_core_section (struct gdbarch * core_arch, const char * sect_name, size_t sect_size) [static, read]
Definition at line 396 of file m32r-linux-tdep.c.
References gdbarch_tdep(), and m32r_linux_gregset.
Referenced by m32r_linux_init_abi().
static CORE_ADDR m32r_linux_rt_sigtramp_start (CORE_ADDR pc, struct frame_info * this_frame) [static]
Definition at line 137 of file m32r-linux-tdep.c.
References linux_rt_sigtramp_code, memcmp(), and safe_frame_unwind_memory().
Referenced by m32r_linux_pc_in_sigtramp(), and m32r_linux_sigtramp_frame_cache().
static struct m32r_frame_cache* m32r_linux_sigtramp_frame_cache (struct frame_info * this_frame, void ** this_cache) [static, read]
Definition at line 227 of file m32r-linux-tdep.c.
References trad_frame_saved_reg::addr, m32r_frame_cache::base, FRAME_OBSTACK_ZALLOC, get_frame_func(), get_frame_pc(), get_frame_register_unsigned(), m32r_linux_rt_sigtramp_start(), m32r_linux_sc_reg_offset, m32r_linux_sigtramp_start(), M32R_SP_REGNUM, m32r_frame_cache::pc, regnum, m32r_frame_cache::saved_regs, and trad_frame_alloc_saved_regs().
Referenced by m32r_linux_sigtramp_frame_prev_register(), and m32r_linux_sigtramp_frame_this_id().
static struct value* m32r_linux_sigtramp_frame_prev_register (struct frame_info * this_frame, void ** this_cache, int regnum) [static, read]
Definition at line 281 of file m32r-linux-tdep.c.
References m32r_linux_sigtramp_frame_cache(), m32r_frame_cache::saved_regs, and trad_frame_get_prev_register().
static int m32r_linux_sigtramp_frame_sniffer (const struct frame_unwind * self, struct frame_info * this_frame, void ** this_cache) [static]
Definition at line 291 of file m32r-linux-tdep.c.
References find_pc_partial_function(), get_frame_pc(), m32r_linux_pc_in_sigtramp(), name, and m32r_frame_cache::pc.
static void m32r_linux_sigtramp_frame_this_id (struct frame_info * this_frame, void ** this_cache, struct frame_id * this_id) [static]
Definition at line 270 of file m32r-linux-tdep.c.
References m32r_frame_cache::base, frame_id_build(), m32r_linux_sigtramp_frame_cache(), and m32r_frame_cache::pc.
static CORE_ADDR m32r_linux_sigtramp_start (CORE_ADDR pc, struct frame_info * this_frame) [static]
Definition at line 89 of file m32r-linux-tdep.c.
References linux_sigtramp_code, memcmp(), and safe_frame_unwind_memory().
Referenced by m32r_linux_pc_in_sigtramp(), and m32r_linux_sigtramp_frame_cache().
static void m32r_linux_supply_gregset (const struct regset * regset, struct regcache * regcache, int regnum, const void * gregs, size_t size) [static]
Definition at line 350 of file m32r-linux-tdep.c.
References BBPSW_OFFSET, CBR_REGNUM, m32r_pt_regs_offset, M32R_SP_REGNUM, PSW_OFFSET, PSW_REGNUM, regcache_raw_supply(), SPI_OFFSET, and SPU_OFFSET.
Variable Documentation
const gdb_byte linux_rt_sigtramp_code[] [static]
Initial value:
 {
  0x97, 0xf0, 0x00, 0xad, 0x10, 0xf2, 0xf0, 0x00,
}
Definition at line 129 of file m32r-linux-tdep.c.
Referenced by m32r_linux_rt_sigtramp_start().
const gdb_byte linux_sigtramp_code[] [static]
Initial value:
 {
  0x67, 0x77, 0x10, 0xf2,
}
Definition at line 81 of file m32r-linux-tdep.c.
Referenced by m32r_linux_sigtramp_start().
struct regset m32r_linux_gregset [static]
Initial value:
 {
  NULL, m32r_linux_supply_gregset
}
Definition at line 391 of file m32r-linux-tdep.c.
Referenced by m32r_linux_regset_from_core_section().
int m32r_linux_sc_reg_offset[] [static]
Initial value:
 {
  4 * 4,
  5 * 4,
  6 * 4,
  7 * 4,
  0 * 4,
  1 * 4,
  2 * 4,
  8 * 4,
  9 * 4,
  10 * 4,
  11 * 4,
  12 * 4,
  13 * 4,
  21 * 4,
  22 * 4,
  -1 * 4,
  16 * 4,
  -1 * 4,
  23 * 4,
  20 * 4,
  19 * 4,
  17 * 4,
  15 * 4,
  14 * 4
}
Definition at line 193 of file m32r-linux-tdep.c.
Referenced by m32r_linux_sigtramp_frame_cache().
struct frame_unwind m32r_linux_sigtramp_frame_unwind [static]
Initial value:
 {
  SIGTRAMP_FRAME,
  default_frame_unwind_stop_reason,
  m32r_linux_sigtramp_frame_this_id,
  m32r_linux_sigtramp_frame_prev_register,
  NULL,
  m32r_linux_sigtramp_frame_sniffer
}
Definition at line 305 of file m32r-linux-tdep.c.
int m32r_pt_regs_offset[] [static]
Initial value:
 {
  4 * 4,
  4 * 5,
  4 * 6,
  4 * 7,
  4 * 0,
  4 * 1,
  4 * 2,
  4 * 8,
  4 * 9,
  4 * 10,
  4 * 11,
  4 * 12,
  4 * 13,
  4 * 24,
  4 * 25,
  4 * 23,
  4 * 19,
  4 * 19,
  4 * 26,
  4 * 23,
  4 * 22,
  4 * 20,
  4 * 16,
  4 * 15
}
Definition at line 317 of file m32r-linux-tdep.c.
Referenced by m32r_linux_supply_gregset().