GDB (xrefs): /home/stan/gdb/src/gdb/m68kbsd-nat.c File Reference
/home/stan/gdb/src/gdb/m68kbsd-nat.c File Reference
#include "defs.h"
#include "gdbcore.h"
#include "inferior.h"
#include "regcache.h"
#include "gdb_assert.h"
#include <sys/types.h>
#include <sys/ptrace.h>
#include <machine/reg.h>
#include "m68k-tdep.h"
#include "inf-ptrace.h"
#include <machine/pcb.h>
#include "bsd-kvm.h"
Defines
#define PCB_REGS_FP 10
#define PCB_REGS_SP 11
Functions
static int m68kbsd_gregset_supplies_p (int regnum)
static int m68kbsd_fpregset_supplies_p (int regnum)
static void m68kbsd_supply_gregset (struct regcache *regcache, const void *gregs)
static void m68kbsd_supply_fpregset (struct regcache *regcache, const void *fpregs)
static void m68kbsd_collect_gregset (const struct regcache *regcache, void *gregs, int regnum)
static void m68kbsd_collect_fpregset (struct regcache *regcache, void *fpregs, int regnum)
static void m68kbsd_fetch_inferior_registers (struct target_ops *ops, struct regcache *regcache, int regnum)
static void m68kbsd_store_inferior_registers (struct target_ops *ops, struct regcache *regcache, int regnum)
static int m68kbsd_supply_pcb (struct regcache *regcache, struct pcb *pcb)
void _initialize_m68kbsd_nat (void)
Define Documentation
#define PCB_REGS_FP 10
Definition at line 186 of file m68kbsd-nat.c.
Referenced by m68kbsd_supply_pcb().
#define PCB_REGS_SP 11
Definition at line 189 of file m68kbsd-nat.c.
Referenced by m68kbsd_supply_pcb().
Function Documentation
void _initialize_m68kbsd_nat (void)
Definition at line 228 of file m68kbsd-nat.c.
References add_target(), bsd_kvm_add_target(), inf_ptrace_target(), m68kbsd_fetch_inferior_registers(), m68kbsd_store_inferior_registers(), m68kbsd_supply_pcb(), target_ops::to_fetch_registers, and target_ops::to_store_registers.
static void m68kbsd_collect_fpregset (struct regcache * regcache, void * fpregs, int regnum) [static]
Definition at line 92 of file m68kbsd-nat.c.
References get_regcache_arch(), M68K_FP0_REGNUM, M68K_FPI_REGNUM, m68kbsd_fpreg_offset(), and regcache_raw_collect().
Referenced by m68kbsd_store_inferior_registers().
static void m68kbsd_collect_gregset (const struct regcache * regcache, void * gregs, int regnum) [static]
Definition at line 75 of file m68kbsd-nat.c.
References M68K_D0_REGNUM, M68K_PC_REGNUM, and regcache_raw_collect().
Referenced by m68kbsd_store_inferior_registers().
static void m68kbsd_fetch_inferior_registers (struct target_ops * ops, struct regcache * regcache, int regnum) [static]
Definition at line 112 of file m68kbsd-nat.c.
References _, inferior_ptid, m68kbsd_fpregset_supplies_p(), m68kbsd_gregset_supplies_p(), m68kbsd_supply_fpregset(), m68kbsd_supply_gregset(), perror_with_name(), ptid_get_pid(), ptrace(), and PTRACE_TYPE_ARG3.
Referenced by _initialize_m68kbsd_nat().
static int m68kbsd_fpregset_supplies_p (int regnum) [static]
Definition at line 40 of file m68kbsd-nat.c.
References M68K_FP0_REGNUM, and M68K_FPI_REGNUM.
Referenced by m68kbsd_fetch_inferior_registers(), and m68kbsd_store_inferior_registers().
static int m68kbsd_gregset_supplies_p (int regnum) [static]
Definition at line 34 of file m68kbsd-nat.c.
References M68K_D0_REGNUM, and M68K_PC_REGNUM.
Referenced by m68kbsd_fetch_inferior_registers(), and m68kbsd_store_inferior_registers().
static void m68kbsd_store_inferior_registers (struct target_ops * ops, struct regcache * regcache, int regnum) [static]
Definition at line 142 of file m68kbsd-nat.c.
References _, inferior_ptid, m68kbsd_collect_fpregset(), m68kbsd_collect_gregset(), m68kbsd_fpregset_supplies_p(), m68kbsd_gregset_supplies_p(), perror_with_name(), ptid_get_pid(), ptrace(), and PTRACE_TYPE_ARG3.
Referenced by _initialize_m68kbsd_nat().
static void m68kbsd_supply_fpregset (struct regcache * regcache, const void * fpregs) [static]
Definition at line 60 of file m68kbsd-nat.c.
References get_regcache_arch(), M68K_FP0_REGNUM, M68K_FPI_REGNUM, m68kbsd_fpreg_offset(), regcache_raw_supply(), and regnum.
Referenced by m68kbsd_fetch_inferior_registers().
static void m68kbsd_supply_gregset (struct regcache * regcache, const void * gregs) [static]
Definition at line 48 of file m68kbsd-nat.c.
References M68K_D0_REGNUM, M68K_PC_REGNUM, regcache_raw_supply(), and regnum.
Referenced by m68kbsd_fetch_inferior_registers().
static int m68kbsd_supply_pcb (struct regcache * regcache, struct pcb * pcb) [static]
Definition at line 193 of file m68kbsd-nat.c.
References M68K_A2_REGNUM, M68K_D2_REGNUM, M68K_D7_REGNUM, M68K_PC_REGNUM, M68K_PS_REGNUM, M68K_SP_REGNUM, PCB_REGS_FP, PCB_REGS_SP, read_memory(), regcache_raw_supply(), and regnum.
Referenced by _initialize_m68kbsd_nat().