GDB (xrefs): /home/stan/gdb/src/gdb/m68kbsd-tdep.c File Reference
/home/stan/gdb/src/gdb/m68kbsd-tdep.c File Reference
#include "defs.h"
#include "arch-utils.h"
#include "frame.h"
#include "osabi.h"
#include "regcache.h"
#include "regset.h"
#include "trad-frame.h"
#include "tramp-frame.h"
#include "gdbtypes.h"
#include "gdb_assert.h"
#include "gdb_string.h"
#include "m68k-tdep.h"
#include "solib-svr4.h"
Defines
#define M68KBSD_SIZEOF_GREGS (18 * 4)
#define M68KBSD_SIZEOF_FPREGS (((8 * 3) + 3) * 4)
Functions
int m68kbsd_fpreg_offset (struct gdbarch *gdbarch, int regnum)
static void m68kbsd_supply_fpregset (const struct regset *regset, struct regcache *regcache, int regnum, const void *fpregs, size_t len)
static void m68kbsd_supply_gregset (const struct regset *regset, struct regcache *regcache, int regnum, const void *gregs, size_t len)
static struct regset * m68kbsd_regset_from_core_section (struct gdbarch *gdbarch, const char *sect_name, size_t sect_size)
static void m68kobsd_sigtramp_cache_init (const struct tramp_frame *self, struct frame_info *this_frame, struct trad_frame_cache *this_cache, CORE_ADDR func)
static void m68kbsd_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
static void m68kbsd_aout_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
static void m68kbsd_elf_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
static enum gdb_osabi m68kbsd_aout_osabi_sniffer (bfd *abfd)
static enum gdb_osabi m68kbsd_core_osabi_sniffer (bfd *abfd)
void _initialize_m68kbsd_tdep (void)
Variables
static struct regset m68kbsd_gregset
static struct regset m68kbsd_fpregset
static struct tramp_frame m68kobsd_sigtramp
Define Documentation
#define M68KBSD_SIZEOF_FPREGS (((8 * 3) + 3) * 4)
Definition at line 42 of file m68kbsd-tdep.c.
Referenced by m68kbsd_regset_from_core_section(), m68kbsd_supply_fpregset(), and m68kbsd_supply_gregset().
#define M68KBSD_SIZEOF_GREGS (18 * 4)
Definition at line 39 of file m68kbsd-tdep.c.
Referenced by m68kbsd_regset_from_core_section(), and m68kbsd_supply_gregset().
Function Documentation
void _initialize_m68kbsd_tdep (void)
static void m68kbsd_aout_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch) [static]
Definition at line 208 of file m68kbsd-tdep.c.
References gdbarch_tdep(), m68kbsd_init_abi(), reg_struct_return, gdbarch_tdep::struct_return, and tramp_frame_prepend_unwinder().
static enum gdb_osabi m68kbsd_aout_osabi_sniffer (bfd * abfd) [static]
Definition at line 239 of file m68kbsd-tdep.c.
References GDB_OSABI_NETBSD_AOUT, and GDB_OSABI_UNKNOWN.
static enum gdb_osabi m68kbsd_core_osabi_sniffer (bfd * abfd) [static]
Definition at line 249 of file m68kbsd-tdep.c.
References GDB_OSABI_NETBSD_AOUT, and GDB_OSABI_UNKNOWN.
static void m68kbsd_elf_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch) [static]
Definition at line 222 of file m68kbsd-tdep.c.
References gdbarch_tdep(), m68k_svr4_init_abi(), m68kbsd_init_abi(), pcc_struct_return, set_solib_svr4_fetch_link_map_offsets(), gdbarch_tdep::struct_return, and svr4_ilp32_fetch_link_map_offsets().
int m68kbsd_fpreg_offset (struct gdbarch * gdbarch, int regnum)
Definition at line 45 of file m68kbsd-tdep.c.
References gdbarch_register_type(), M68K_FP0_REGNUM, M68K_FPC_REGNUM, and TYPE_LENGTH.
Referenced by m68kbsd_collect_fpregset(), and m68kbsd_supply_fpregset().
static void m68kbsd_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch) [static]
Definition at line 192 of file m68kbsd-tdep.c.
References gdbarch_tdep(), gdbarch_tdep::jb_elt_size, gdbarch_tdep::jb_pc, m68kbsd_regset_from_core_section(), set_gdbarch_decr_pc_after_break(), and set_gdbarch_regset_from_core_section().
Referenced by m68kbsd_aout_init_abi(), and m68kbsd_elf_init_abi().
static struct regset* m68kbsd_regset_from_core_section (struct gdbarch * gdbarch, const char * sect_name, size_t sect_size) [static, read]
Definition at line 124 of file m68kbsd-tdep.c.
References m68kbsd_fpregset, m68kbsd_gregset, M68KBSD_SIZEOF_FPREGS, and M68KBSD_SIZEOF_GREGS.
Referenced by m68kbsd_init_abi().
static void m68kbsd_supply_fpregset (const struct regset * regset, struct regcache * regcache, int regnum, const void * fpregs, size_t len) [static]
Definition at line 60 of file m68kbsd-tdep.c.
References gdb_assert, get_regcache_arch(), M68K_FP0_REGNUM, M68K_PC_REGNUM, m68kbsd_fpreg_offset(), M68KBSD_SIZEOF_FPREGS, and regcache_raw_supply().
Referenced by m68kbsd_supply_gregset().
static void m68kbsd_supply_gregset (const struct regset * regset, struct regcache * regcache, int regnum, const void * gregs, size_t len) [static]
Definition at line 83 of file m68kbsd-tdep.c.
References gdb_assert, M68K_D0_REGNUM, M68K_PC_REGNUM, M68KBSD_SIZEOF_FPREGS, M68KBSD_SIZEOF_GREGS, m68kbsd_supply_fpregset(), and regcache_raw_supply().
static void m68kobsd_sigtramp_cache_init (const struct tramp_frame * self, struct frame_info * this_frame, struct trad_frame_cache * this_cache, CORE_ADDR func) [static]
Definition at line 140 of file m68kbsd-tdep.c.
References frame_id_build(), get_frame_memory_unsigned(), get_frame_register_unsigned(), M68K_D0_REGNUM, M68K_FP_REGNUM, M68K_PC_REGNUM, M68K_PS_REGNUM, M68K_SP_REGNUM, regnum, trad_frame_set_id(), and trad_frame_set_reg_addr().
Variable Documentation
struct regset m68kbsd_fpregset [static]
Initial value:
{
  NULL,
  m68kbsd_supply_fpregset
}
Definition at line 114 of file m68kbsd-tdep.c.
Referenced by m68kbsd_regset_from_core_section().
struct regset m68kbsd_gregset [static]
Initial value:
{
  NULL,
  m68kbsd_supply_gregset
}
Definition at line 108 of file m68kbsd-tdep.c.
Referenced by m68kbsd_regset_from_core_section().
struct tramp_frame m68kobsd_sigtramp [static]
Initial value:
 {
  SIGTRAMP_FRAME,
  2,
  {
    { 0x206f, -1 }, { 0x000c, -1},
    { 0x4e90, -1 },
    { 0x588f, -1 },
    { 0x4e41, -1 },
    { 0x2f40, -1 }, { 0x0004, -1 },
    { 0x7001, -1 },
    { 0x4e40, -1 },
    { TRAMP_SENTINEL_INSN, -1 }
  },
  m68kobsd_sigtramp_cache_init
}
Definition at line 174 of file m68kbsd-tdep.c.