GDB (xrefs): /home/stan/gdb/src/gdb/m88kbsd-nat.c File Reference
/home/stan/gdb/src/gdb/m88kbsd-nat.c File Reference
#include "defs.h"
#include "inferior.h"
#include "regcache.h"
#include "target.h"
#include <sys/types.h>
#include <sys/ptrace.h>
#include <machine/reg.h>
#include "m88k-tdep.h"
#include "inf-ptrace.h"
Functions
static void m88kbsd_supply_gregset (struct regcache *regcache, const void *gregs)
static void m88kbsd_collect_gregset (const struct regcache *regcache, void *gregs, int regnum)
static void m88kbsd_fetch_inferior_registers (struct target_ops *ops, struct regcache *regcache, int regnum)
static void m88kbsd_store_inferior_registers (struct target_ops *ops, struct regcache *regcache, int regnum)
void _initialize_m88kbsd_nat (void)
Function Documentation
void _initialize_m88kbsd_nat (void)
Definition at line 103 of file m88kbsd-nat.c.
References add_target(), inf_ptrace_target(), m88kbsd_fetch_inferior_registers(), m88kbsd_store_inferior_registers(), target_ops::to_fetch_registers, and target_ops::to_store_registers.
static void m88kbsd_collect_gregset (const struct regcache * regcache, void * gregs, int regnum) [static]
Definition at line 48 of file m88kbsd-nat.c.
References M88K_NUM_REGS, and regcache_raw_collect().
Referenced by m88kbsd_store_inferior_registers().
static void m88kbsd_fetch_inferior_registers (struct target_ops * ops, struct regcache * regcache, int regnum) [static]
Definition at line 66 of file m88kbsd-nat.c.
References _, inferior_ptid, m88kbsd_supply_gregset(), perror_with_name(), ptid_get_pid(), ptrace(), and PTRACE_TYPE_ARG3.
Referenced by _initialize_m88kbsd_nat().
static void m88kbsd_store_inferior_registers (struct target_ops * ops, struct regcache * regcache, int regnum) [static]
Definition at line 82 of file m88kbsd-nat.c.
References _, inferior_ptid, m88kbsd_collect_gregset(), perror_with_name(), ptid_get_pid(), ptrace(), and PTRACE_TYPE_ARG3.
Referenced by _initialize_m88kbsd_nat().
static void m88kbsd_supply_gregset (struct regcache * regcache, const void * gregs) [static]
Definition at line 35 of file m88kbsd-nat.c.
References M88K_NUM_REGS, regcache_raw_supply(), and regnum.
Referenced by m88kbsd_fetch_inferior_registers().