GDB (xrefs): /home/stan/gdb/src/gdb/macroscope.h File Reference
/home/stan/gdb/src/gdb/macroscope.h File Reference
#include "macrotab.h"
#include "symtab.h"
Classes
struct macro_scope
Functions
struct macro_scope * sal_macro_scope (struct symtab_and_line sal)
struct macro_scope * user_macro_scope (void)
struct macro_scope * default_macro_scope (void)
struct macro_definition * standard_macro_lookup (const char *name, void *baton)
Variables
struct macro_table * macro_user_macros
Function Documentation
struct macro_scope* default_macro_scope (void) [read]
Definition at line 99 of file macroscope.c.
References deprecated_safe_get_selected_frame(), find_pc_line(), get_current_source_symtab_and_line(), get_frame_pc_if_available(), symtab_and_line::line, sal_macro_scope(), symtab_and_line::symtab, and user_macro_scope().
Referenced by c_parse(), info_macro_command(), info_macros_command(), macro_expand_command(), and macro_expand_once_command().
struct macro_scope* sal_macro_scope (struct symtab_and_line sal) [read]
Definition at line 39 of file macroscope.c.
References _, complaint(), macro_scope::file, symtab::filename, macro_scope::line, symtab_and_line::line, macro_lookup_inclusion(), macro_main(), symtab::macro_table, symfile_complaints, symtab_and_line::symtab, symtab_to_filename_for_display(), and xmalloc().
Referenced by c_parse(), default_macro_scope(), and info_macros_command().
struct macro_definition* standard_macro_lookup (const char * name, void * baton) [read]
Definition at line 144 of file macroscope.c.
References macro_scope::file, macro_scope::line, macro_lookup_definition(), and macro_main().
Referenced by lex_one_token(), macro_expand_command(), and macro_expand_once_command().
struct macro_scope* user_macro_scope (void) [read]
Definition at line 88 of file macroscope.c.
References macro_scope::file, macro_scope::line, and macro_main().
Referenced by c_parse(), and default_macro_scope().
Variable Documentation
struct macro_table* macro_user_macros
Definition at line 35 of file macroscope.c.
Referenced by macro_define_command(), macro_list_command(), and macro_undef_command().