GDB (xrefs): /home/stan/gdb/src/gdb/macrotab.h File Reference
/home/stan/gdb/src/gdb/macrotab.h File Reference
Classes
struct macro_source_file
struct macro_definition
Typedefs
typedef void(* macro_callback_fn)(const char *name, const struct macro_definition *definition, struct macro_source_file *source, int line, void *user_data)
Enumerations
enum macro_kind { macro_object_like, macro_function_like }
enum macro_special_kind { macro_ordinary, macro_FILE, macro_LINE }
Functions
struct macro_table * new_macro_table (struct obstack *obstack, struct bcache *bcache, const char *comp_dir)
void free_macro_table (struct macro_table *table)
struct macro_source_file * macro_set_main (struct macro_table *table, const char *filename)
struct macro_source_file * macro_main (struct macro_table *table)
void macro_allow_redefinitions (struct macro_table *table)
struct macro_source_file * macro_include (struct macro_source_file *source, int line, const char *included)
void macro_define_special (struct macro_table *table)
struct macro_source_file * macro_lookup_inclusion (struct macro_source_file *source, const char *name))
void macro_define_object (struct macro_source_file *source, int line, const char *name, const char *replacement)
void macro_define_function (struct macro_source_file *source, int line, const char *name, int argc, const char **argv, const char *replacement)
void macro_undef (struct macro_source_file *source, int line, const char *name)
struct macro_definition * macro_lookup_definition (struct macro_source_file *source, int line, const char *name))
struct macro_source_file * macro_definition_location (struct macro_source_file *source, int line, const char *name, int *definition_line))
void macro_for_each (struct macro_table *table, macro_callback_fn fn, void *user_data)
void macro_for_each_in_scope (struct macro_source_file *file, int line, macro_callback_fn fn, void *user_data)
char * macro_source_fullname (struct macro_source_file *file)
Typedef Documentation
typedef void(* macro_callback_fn)(const char *name, const struct macro_definition *definition, struct macro_source_file *source, int line, void *user_data)
Definition at line 336 of file macrotab.h.
Enumeration Type Documentation
enum macro_kind
Enumerator:
macro_object_like
macro_function_like
Definition at line 266 of file macrotab.h.
enum macro_special_kind
Enumerator:
macro_ordinary
macro_FILE
macro_LINE
Definition at line 274 of file macrotab.h.
Function Documentation
void free_macro_table (struct macro_table * table)
Definition at line 1082 of file macrotab.c.
References macro_table::definitions, free_macro_source_file(), and macro_table::main_source.
Referenced by really_free_pendings().
void macro_allow_redefinitions (struct macro_table * table)
Definition at line 443 of file macrotab.c.
References gdb_assert, macro_table::obstack, and macro_table::redef_ok.
Referenced by _initialize_macroscope().
void macro_define_function (struct macro_source_file * source, int line, const char * name, int argc, const char ** argv, const char * replacement)
Definition at line 802 of file macrotab.c.
References check_for_redefinition(), macro_table::definitions, key_compare(), macro_function_like, new_macro_definition(), new_macro_key(), macro_table::redef_ok, and macro_source_file::table.
Referenced by macro_define_command(), and parse_macro_definition().
void macro_define_object (struct macro_source_file * source, int line, const char * name, const char * replacement)
Definition at line 783 of file macrotab.c.
References macro_define_object_internal(), and macro_ordinary.
Referenced by macro_define_command(), and parse_macro_definition().
void macro_define_special (struct macro_table * table)
Definition at line 793 of file macrotab.c.
References macro_define_object_internal(), macro_FILE, macro_LINE, and macro_table::main_source.
Referenced by macro_start_file().
struct macro_source_file* macro_definition_location (struct macro_source_file * source, int line, const char * name, int * definition_line) [read]
Definition at line 943 of file macrotab.c.
References find_definition(), macro_key::start_file, and macro_key::start_line.
Referenced by info_macro_command().
void macro_for_each (struct macro_table * table, macro_callback_fn fn, void * user_data)
Definition at line 994 of file macrotab.c.
References macro_table::definitions, macro_for_each_data::file, macro_for_each_data::fn, foreach_macro(), macro_for_each_data::line, and macro_for_each_data::user_data.
Referenced by info_macro_command(), and macro_list_command().
void macro_for_each_in_scope (struct macro_source_file * file, int line, macro_callback_fn fn, void * user_data)
Definition at line 1033 of file macrotab.c.
References macro_table::definitions, macro_for_each_data::file, macro_for_each_data::fn, foreach_macro_in_scope(), macro_for_each_data::line, line, macro_source_file::table, and macro_for_each_data::user_data.
Referenced by info_macros_command().
struct macro_source_file* macro_include (struct macro_source_file * source, int line, const char * included) [read]
Definition at line 451 of file macrotab.c.
References _, complaint(), macro_source_file::included_at_line, macro_source_file::includes, line, macro_source_fullname(), new_source_file(), macro_source_file::next_included, symfile_complaints, macro_source_file::table, and xfree().
Referenced by macro_start_file().
struct macro_definition* macro_lookup_definition (struct macro_source_file * source, int line, const char * name) [read]
Definition at line 921 of file macrotab.c.
References find_definition(), fixup_definition(), macro_source_fullname(), and xfree().
Referenced by info_macro_command(), and standard_macro_lookup().
struct macro_source_file* macro_lookup_inclusion (struct macro_source_file * source, const char * name) [read]
Definition at line 512 of file macrotab.c.
References macro_source_file::filename, macro_source_file::includes, inclusion_depth(), macro_lookup_inclusion(), and macro_source_file::next_included.
Referenced by macro_lookup_inclusion(), and sal_macro_scope().
struct macro_source_file* macro_main (struct macro_table * table) [read]
Definition at line 434 of file macrotab.c.
References gdb_assert, and macro_table::main_source.
Referenced by macro_define_command(), macro_undef_command(), sal_macro_scope(), standard_macro_lookup(), and user_macro_scope().
struct macro_source_file* macro_set_main (struct macro_table * table, const char * filename) [read]
Definition at line 420 of file macrotab.c.
References gdb_assert, macro_table::main_source, and new_source_file().
Referenced by _initialize_macroscope(), and macro_start_file().
char* macro_source_fullname (struct macro_source_file * file)
Definition at line 1094 of file macrotab.c.
References macro_table::comp_dir, macro_source_file::filename, and macro_source_file::table.
Referenced by check_for_redefinition(), foreach_macro(), foreach_macro_in_scope(), macro_include(), macro_lookup_definition(), macro_undef(), and show_pp_source_pos().
void macro_undef (struct macro_source_file * source, int line, const char * name)
Definition at line 830 of file macrotab.c.
References _, complaint(), macro_table::definitions, macro_key::end_file, macro_key::end_line, macro_source_file::filename, find_definition(), line, macro_source_fullname(), macro_key::start_file, macro_key::start_line, symfile_complaints, macro_source_file::table, and xfree().
Referenced by dwarf_decode_macro_bytes(), and macro_undef_command().
struct macro_table* new_macro_table (struct obstack * obstack, struct bcache * bcache, const char * comp_dir) [read]
Definition at line 1052 of file macrotab.c.
References macro_table::bcache, macro_table::comp_dir, macro_table::definitions, macro_alloc(), macro_free(), macro_tree_compare(), macro_tree_delete_key(), macro_tree_delete_value(), macro_table::main_source, memset(), macro_table::obstack, macro_table::redef_ok, and xmalloc().
Referenced by _initialize_macroscope(), and get_macro_table().