GDB (xrefs): /home/stan/gdb/src/gdb/macrocmd.c File Reference
/home/stan/gdb/src/gdb/macrocmd.c File Reference
#include "defs.h"
#include "macrotab.h"
#include "macroexp.h"
#include "macroscope.h"
#include "cli/cli-utils.h"
#include "command.h"
#include "gdbcmd.h"
#include "gdb_string.h"
#include "linespec.h"
Functions
static void macro_command (char *arg, int from_tty)
static void macro_inform_no_debuginfo (void)
static void macro_expand_command (char *exp, int from_tty)
static void macro_expand_once_command (char *exp, int from_tty)
static void show_pp_source_pos (struct ui_file *stream, struct macro_source_file *file, int line)
static void print_macro_definition (const char *name, const struct macro_definition *d, struct macro_source_file *file, int line)
static void print_macro_callback (const char *name, const struct macro_definition *macro, struct macro_source_file *source, int line, void *user_data)
static void info_macro_command (char *args, int from_tty)
static void info_macros_command (char *args, int from_tty)
static void skip_ws (char **expp)
static char * extract_identifier (char **expp, int is_parameter)
static void free_macro_definition_ptr (void *ptr)
static void macro_define_command (char *exp, int from_tty)
static void macro_undef_command (char *exp, int from_tty)
static void print_one_macro (const char *name, const struct macro_definition *macro, struct macro_source_file *source, int line, void *ignore)
static void macro_list_command (char *exp, int from_tty)
void _initialize_macrocmd (void)
Variables
static struct cmd_list_element * macrolist
initialize_file_ftype _initialize_macrocmd
Function Documentation
void _initialize_macrocmd (void)
Definition at line 499 of file macrocmd.c.
References _, _initialize_macrocmd, add_alias_cmd(), add_cmd(), add_prefix_cmd(), class_info, cmdlist, info_macro_command(), info_macros_command(), infolist, macro_command(), macro_define_command(), macro_expand_command(), macro_expand_once_command(), macro_list_command(), macro_undef_command(), and no_class.
static char* extract_identifier (char ** expp, int is_parameter) [static]
Definition at line 323 of file macrocmd.c.
References len, macro_is_digit(), macro_is_identifier_nondigit(), memcpy(), p, and xmalloc().
Referenced by macro_define_command(), and macro_undef_command().
static void free_macro_definition_ptr (void * ptr) [static]
Definition at line 357 of file macrocmd.c.
References macro_definition::argc, macro_definition::argv, and xfree().
Referenced by macro_define_command().
static void info_macro_command (char * args, int from_tty) [static]
Definition at line 206 of file macrocmd.c.
References _, cleanup_chain, default_macro_scope(), do_cleanups(), error(), macro_scope::file, fprintf_filtered(), free_current_contents(), gdb_stdout, macro_scope::line, line, macro_definition_location(), macro_for_each(), macro_inform_no_debuginfo(), macro_lookup_definition(), make_cleanup(), name, p, print_macro_callback(), print_macro_definition(), show_pp_source_pos(), skip_spaces(), skip_to_space, and macro_source_file::table.
Referenced by _initialize_macrocmd().
static void info_macros_command (char * args, int from_tty) [static]
Definition at line 281 of file macrocmd.c.
References cleanup_chain, decode_line_with_current_source(), default_macro_scope(), do_cleanups(), macro_scope::file, free_current_contents(), macro_scope::line, macro_for_each_in_scope(), macro_inform_no_debuginfo(), make_cleanup(), symtabs_and_lines::nelts, print_macro_callback(), sal_macro_scope(), symtabs_and_lines::sals, and macro_source_file::table.
Referenced by _initialize_macrocmd().
static void macro_command (char * arg, int from_tty) [static]
Definition at line 37 of file macrocmd.c.
References gdb_stdout, help_list(), and printf_unfiltered().
Referenced by _initialize_macrocmd().
static void macro_define_command (char * exp, int from_tty) [static]
Definition at line 369 of file macrocmd.c.
References _, macro_definition::argc, macro_definition::argv, cleanup_chain, do_cleanups(), error(), extract_identifier(), free_current_contents(), free_macro_definition_ptr(), macro_define_function(), macro_define_object(), macro_function_like, macro_main(), macro_user_macros, make_cleanup(), memset(), name, skip_ws(), xmalloc(), and xrealloc().
Referenced by _initialize_macrocmd().
static void macro_expand_command (char * exp, int from_tty) [static]
Definition at line 57 of file macrocmd.c.
References _, cleanup_chain, default_macro_scope(), do_cleanups(), error(), fputs_filtered(), free_current_contents(), gdb_stdout, macro_expand(), macro_inform_no_debuginfo(), make_cleanup(), and standard_macro_lookup().
Referenced by _initialize_macrocmd().
static void macro_expand_once_command (char * exp, int from_tty) [static]
Definition at line 92 of file macrocmd.c.
References _, cleanup_chain, default_macro_scope(), do_cleanups(), error(), fputs_filtered(), free_current_contents(), gdb_stdout, macro_expand_once(), macro_inform_no_debuginfo(), make_cleanup(), and standard_macro_lookup().
Referenced by _initialize_macrocmd().
static void macro_inform_no_debuginfo (void) [static]
Definition at line 51 of file macrocmd.c.
References puts_filtered().
Referenced by info_macro_command(), info_macros_command(), macro_expand_command(), and macro_expand_once_command().
static void macro_list_command (char * exp, int from_tty) [static]
Definition at line 488 of file macrocmd.c.
References macro_for_each(), macro_user_macros, and print_one_macro().
Referenced by _initialize_macrocmd().
static void macro_undef_command (char * exp, int from_tty) [static]
Definition at line 451 of file macrocmd.c.
References _, error(), extract_identifier(), macro_main(), macro_undef(), macro_user_macros, name, skip_ws(), and xfree().
Referenced by _initialize_macrocmd().
static void print_macro_callback (const char * name, const struct macro_definition * macro, struct macro_source_file * source, int line, void * user_data) [static]
Definition at line 196 of file macrocmd.c.
References print_macro_definition().
Referenced by info_macro_command(), and info_macros_command().
static void print_macro_definition (const char * name, const struct macro_definition * d, struct macro_source_file * file, int line) [static]
Definition at line 157 of file macrocmd.c.
References macro_definition::argc, macro_definition::argv, fprintf_filtered(), fputs_filtered(), gdb_stdout, macro_function_like, macro_definition::replacement, and show_pp_source_pos().
Referenced by info_macro_command(), and print_macro_callback().
static void print_one_macro (const char * name, const struct macro_definition * macro, struct macro_source_file * source, int line, void * ignore) [static]
Definition at line 468 of file macrocmd.c.
References macro_definition::argc, macro_definition::argv, fprintf_filtered(), gdb_stdout, macro_function_like, and macro_definition::replacement.
Referenced by macro_list_command().
static void show_pp_source_pos (struct ui_file * stream, struct macro_source_file * file, int line) [static]
Definition at line 129 of file macrocmd.c.
References fprintf_filtered(), gdb_stdout, macro_source_file::included_at_line, macro_source_file::included_by, macro_source_fullname(), and xfree().
Referenced by info_macro_command(), and print_macro_definition().
static void skip_ws (char ** expp) [static]
Definition at line 309 of file macrocmd.c.
References macro_is_whitespace().
Referenced by macro_define_command(), and macro_undef_command().
Variable Documentation
initialize_file_ftype _initialize_macrocmd
Referenced by _initialize_macrocmd(), and initialize_all_files().
struct cmd_list_element* macrolist [static]
Definition at line 34 of file macrocmd.c.