GDB (xrefs): /home/stan/gdb/src/gdb/maint.h File Reference
/home/stan/gdb/src/gdb/maint.h File Reference
Functions
void set_per_command_time (int)
void set_per_command_space (int)
struct cleanup * make_command_stats_cleanup (int)
Function Documentation
struct cleanup* make_command_stats_cleanup (int) [read]
Definition at line 895 of file maint.c.
References count_symtabs_and_blocks(), lim_at_start, make_cleanup(), make_cleanup_dtor(), cmd_stats::msg_type, null_cleanup(), report_command_stats(), reset_prompt_for_continue_wait_time(), cmd_stats::space_enabled, cmd_stats::start_cpu_time, cmd_stats::start_nr_blocks, cmd_stats::start_nr_primary_symtabs, cmd_stats::start_nr_symtabs, cmd_stats::start_space, cmd_stats::start_wall_time, cmd_stats::symtab_enabled, cmd_stats::time_enabled, xfree(), and XZALLOC.
Referenced by captured_main(), command_handler(), and command_loop().
void set_per_command_space (int)
Definition at line 792 of file maint.c.
Referenced by captured_main(), and maintenance_space_display().
void set_per_command_time (int)
Definition at line 783 of file maint.c.
Referenced by captured_main(), and maintenance_time_display().