GDB (xrefs): /home/stan/gdb/src/gdb/memattr.c File Reference
/home/stan/gdb/src/gdb/memattr.c File Reference
#include "defs.h"
#include "command.h"
#include "gdbcmd.h"
#include "memattr.h"
#include "target.h"
#include "value.h"
#include "language.h"
#include "vec.h"
#include "gdb_string.h"
#include "breakpoint.h"
#include "cli/cli-utils.h"
Functions
VEC (mem_region_s)
static int mem_region_lessthan (const struct mem_region *lhs, const struct mem_region *rhs)
int mem_region_cmp (const void *untyped_lhs, const void *untyped_rhs)
void mem_region_init (struct mem_region *new)
static void require_user_regions (int from_tty)
static void require_target_regions (void)
static void create_mem_region (CORE_ADDR lo, CORE_ADDR hi, const struct mem_attrib *attrib)
struct mem_region * lookup_mem_region (CORE_ADDR addr)
void invalidate_target_mem_regions (void)
static void mem_clear (void)
static void mem_command (char *args, int from_tty)
static void mem_info_command (char *args, int from_tty)
static void mem_enable (int num)
static void mem_enable_command (char *args, int from_tty)
static void mem_disable (int num)
static void mem_disable_command (char *args, int from_tty)
static void mem_delete (int num)
static void mem_delete_command (char *args, int from_tty)
static void dummy_cmd (char *args, int from_tty)
void _initialize_mem (void)
Variables
struct mem_attrib default_mem_attrib
struct mem_attrib unknown_mem_attrib
initialize_file_ftype _initialize_mem
static struct cmd_list_element * mem_set_cmdlist
static struct cmd_list_element * mem_show_cmdlist
Function Documentation
void _initialize_mem (void)
Definition at line 705 of file memattr.c.
References _, _initialize_mem, add_cmd(), add_com(), add_info(), add_prefix_cmd(), add_setshow_boolean_cmd(), class_vars, deletelist, disablelist, dummy_cmd(), enablelist, mem_command(), mem_delete_command(), mem_disable_command(), mem_enable_command(), mem_info_command(), no_class, setlist, and showlist.
static void create_mem_region (CORE_ADDR lo, CORE_ADDR hi, const struct mem_attrib * attrib) [static]
Definition at line 174 of file memattr.c.
References _, mem_region::attrib, mem_region::hi, mem_region::lo, mem_region_init(), mem_region_lessthan(), printf_unfiltered(), VEC_index, VEC_length, VEC_lower_bound, and VEC_safe_insert.
Referenced by mem_command().
static void dummy_cmd (char * args, int from_tty) [static]
Definition at line 695 of file memattr.c.
Referenced by _initialize_mem().
void invalidate_target_mem_regions (void)
Definition at line 295 of file memattr.c.
References VEC_free.
Referenced by target_pre_inferior().
struct mem_region* lookup_mem_region (CORE_ADDR addr) [read]
Definition at line 226 of file memattr.c.
References mem_region::attrib, mem_region::enabled_p, mem_region::hi, mem_region::lo, arm-linux::m, require_target_regions(), VEC_empty, and VEC_iterate.
Referenced by block_boundaries(), dcache_read_line(), insert_bp_location(), memory_xfer_partial_1(), split_regular_and_flash_blocks(), and VEC().
static void mem_clear (void) [static]
Definition at line 309 of file memattr.c.
References VEC_free.
Referenced by mem_command(), and mem_delete_command().
static void mem_command (char * args, int from_tty) [static]
Definition at line 316 of file memattr.c.
References _, mem_attrib::cache, create_mem_region(), default_mem_attrib, error(), error_no_arg(), mem_region::hi, mem_attrib::hwbreak, mem_region::lo, mem_clear(), MEM_RO, MEM_RW, MEM_WIDTH_16, MEM_WIDTH_32, MEM_WIDTH_64, MEM_WIDTH_8, MEM_WO, mem_attrib::mode, parse_and_eval_address(), require_user_regions(), strtok(), mem_attrib::verify, and mem_attrib::width.
Referenced by _initialize_mem().
static void mem_delete (int num) [static]
Definition at line 642 of file memattr.c.
References _, arm-linux::m, mem_region::number, printf_unfiltered(), VEC_iterate, and VEC_ordered_remove.
Referenced by mem_delete_command().
static void mem_delete_command (char * args, int from_tty) [static]
Definition at line 667 of file memattr.c.
References _, dont_repeat(), get_number_or_range_state::finished, get_number_or_range(), init_number_or_range(), mem_clear(), mem_delete(), query(), require_user_regions(), and target_dcache_invalidate().
Referenced by _initialize_mem().
static void mem_disable (int num) [static]
Definition at line 596 of file memattr.c.
References _, mem_region::enabled_p, arm-linux::m, mem_region::number, printf_unfiltered(), and VEC_iterate.
Referenced by mem_disable_command().
static void mem_disable_command (char * args, int from_tty) [static]
Definition at line 611 of file memattr.c.
References mem_region::enabled_p, get_number_or_range_state::finished, get_number_or_range(), init_number_or_range(), arm-linux::m, mem_disable(), require_user_regions(), target_dcache_invalidate(), and VEC_iterate.
Referenced by _initialize_mem().
static void mem_enable (int num) [static]
Definition at line 549 of file memattr.c.
References _, mem_region::enabled_p, arm-linux::m, mem_region::number, printf_unfiltered(), and VEC_iterate.
Referenced by mem_enable_command().
static void mem_enable_command (char * args, int from_tty) [static]
Definition at line 564 of file memattr.c.
References mem_region::enabled_p, get_number_or_range_state::finished, get_number_or_range(), init_number_or_range(), arm-linux::m, mem_enable(), require_user_regions(), target_dcache_invalidate(), and VEC_iterate.
Referenced by _initialize_mem().
static void mem_info_command (char * args, int from_tty) [static]
Definition at line 412 of file memattr.c.
References _, mem_region::attrib, mem_attrib::blocksize, mem_attrib::cache, mem_region::enabled_p, gdb_flush(), gdb_stdout, gdbarch_addr_bit(), hex_string_custom(), mem_region::hi, mem_attrib::hwbreak, mem_region::lo, arm-linux::m, MEM_FLASH, MEM_RO, MEM_RW, MEM_WIDTH_16, MEM_WIDTH_32, MEM_WIDTH_64, MEM_WIDTH_8, MEM_WIDTH_UNSPECIFIED, MEM_WO, mem_attrib::mode, mem_region::number, printf_filtered(), printf_unfiltered(), require_target_regions(), target_gdbarch(), VEC_iterate, mem_attrib::verify, and mem_attrib::width.
Referenced by _initialize_mem().
int mem_region_cmp (const void * untyped_lhs, const void * untyped_rhs)
Definition at line 99 of file memattr.c.
References mem_region::lo.
Referenced by VEC().
void mem_region_init (struct mem_region * new)
Definition at line 115 of file memattr.c.
References default_mem_attrib, and memset().
Referenced by create_mem_region().
static int mem_region_lessthan (const struct mem_region * lhs, const struct mem_region * rhs) [static]
Definition at line 89 of file memattr.c.
References mem_region::lo.
Referenced by create_mem_region().
static void require_target_regions (void) [static]
Definition at line 163 of file memattr.c.
Referenced by lookup_mem_region(), and mem_info_command().
static void require_user_regions (int from_tty) [static]
Definition at line 127 of file memattr.c.
References _, arm-linux::m, VEC_alloc, VEC_iterate, VEC_length, VEC_quick_push, and warning().
Referenced by mem_command(), mem_delete_command(), mem_disable_command(), and mem_enable_command().
VEC (mem_region_s)
Definition at line 53 of file memattr.c.
Variable Documentation
initialize_file_ftype _initialize_mem
Referenced by _initialize_mem(), and initialize_all_files().
struct mem_attrib default_mem_attrib
Initial value:
{
  MEM_RW,
  MEM_WIDTH_UNSPECIFIED,
  0,
  0,
  0,
  -1
}
Definition at line 32 of file memattr.c.
Referenced by mem_command(), and mem_region_init().
struct cmd_list_element* mem_set_cmdlist [static]
Definition at line 701 of file memattr.c.
struct cmd_list_element* mem_show_cmdlist [static]
Definition at line 702 of file memattr.c.
struct mem_attrib unknown_mem_attrib
Initial value:
{
  MEM_NONE,
  MEM_WIDTH_UNSPECIFIED,
  0,
  0,
  0,
  -1
}
Definition at line 42 of file memattr.c.