GDB (xrefs): /home/stan/gdb/src/gdb/memattr.h File Reference
/home/stan/gdb/src/gdb/memattr.h File Reference
#include "vec.h"
Classes
struct mem_attrib
struct mem_region
Typedefs
typedef struct mem_region mem_region_s
Enumerations
enum mem_access_mode {
MEM_NONE, MEM_RW, MEM_RO, MEM_WO,
MEM_FLASH
}
enum mem_access_width {
MEM_WIDTH_UNSPECIFIED, MEM_WIDTH_8, MEM_WIDTH_16, MEM_WIDTH_32,
MEM_WIDTH_64
}
Functions
DEF_VEC_O (mem_region_s)
struct mem_region * lookup_mem_region (CORE_ADDR)
void invalidate_target_mem_regions (void)
void mem_region_init (struct mem_region *)
int mem_region_cmp (const void *, const void *)
Typedef Documentation
typedef struct mem_region mem_region_s
Definition at line 98 of file memattr.h.
Enumeration Type Documentation
enum mem_access_mode
Enumerator:
MEM_NONE
MEM_RW
MEM_RO
MEM_WO
MEM_FLASH
Definition at line 25 of file memattr.h.
enum mem_access_width
Enumerator:
MEM_WIDTH_UNSPECIFIED
MEM_WIDTH_8
MEM_WIDTH_16
MEM_WIDTH_32
MEM_WIDTH_64
Definition at line 36 of file memattr.h.
Function Documentation
DEF_VEC_O (mem_region_s)
void invalidate_target_mem_regions (void)
Definition at line 295 of file memattr.c.
References VEC_free.
Referenced by target_pre_inferior().
struct mem_region* lookup_mem_region (CORE_ADDR) [read]
Definition at line 226 of file memattr.c.
References mem_region::attrib, mem_region::enabled_p, mem_region::hi, mem_region::lo, arm-linux::m, require_target_regions(), VEC_empty, and VEC_iterate.
Referenced by block_boundaries(), dcache_read_line(), insert_bp_location(), memory_xfer_partial_1(), split_regular_and_flash_blocks(), and VEC().
int mem_region_cmp (const void * , const void *)
Definition at line 99 of file memattr.c.
References mem_region::lo.
Referenced by VEC().
void mem_region_init (struct mem_region *)
Definition at line 115 of file memattr.c.
References default_mem_attrib, and memset().
Referenced by create_mem_region().