GDB (xrefs): /home/stan/gdb/src/gdb/memrange.h File Reference
/home/stan/gdb/src/gdb/memrange.h File Reference
#include "vec.h"
Classes
struct mem_range
Typedefs
typedef struct mem_range mem_range_s
Functions
DEF_VEC_O (mem_range_s)
int mem_ranges_overlap (CORE_ADDR start1, int len1, CORE_ADDR start2, int len2)
void normalize_mem_ranges (VEC(mem_range_s)*memory)
Typedef Documentation
typedef struct mem_range mem_range_s
Definition at line 36 of file memrange.h.
Function Documentation
DEF_VEC_O (mem_range_s)
int mem_ranges_overlap (CORE_ADDR start1, int len1, CORE_ADDR start2, int len2)
Definition at line 24 of file memrange.c.
References max, min, and ULONGEST.
Referenced by read_value_memory(), traceframe_available_memory(), and VEC().
void normalize_mem_ranges (VEC(mem_range_s)* memory)
Definition at line 52 of file memrange.c.
References compare_mem_ranges(), mem_range::length, max, qsort, mem_range::start, VEC_address, VEC_empty, VEC_index, VEC_iterate, VEC_length, and VEC_truncate.
Referenced by read_value_memory(), and traceframe_available_memory().