GDB (xrefs): /home/stan/gdb/src/gdb/mi/mi-cmd-stack.c File Reference
/home/stan/gdb/src/gdb/mi/mi-cmd-stack.c File Reference
#include "defs.h"
#include "target.h"
#include "frame.h"
#include "value.h"
#include "mi-cmds.h"
#include "ui-out.h"
#include "symtab.h"
#include "block.h"
#include "stack.h"
#include "dictionary.h"
#include "gdb_string.h"
#include "language.h"
#include "valprint.h"
#include "exceptions.h"
#include "utils.h"
#include "mi-getopt.h"
#include "python/python.h"
#include <ctype.h>
#include "mi-parse.h"
Enumerations
enum what_to_list { locals, arguments, all }
Functions
static void list_args_or_locals (enum what_to_list what, enum print_values values, struct frame_info *fi, int skip_unavailable)
void mi_cmd_enable_frame_filters (char *command, char **argv, int argc)
void mi_cmd_stack_list_frames (char *command, char **argv, int argc)
void mi_cmd_stack_info_depth (char *command, char **argv, int argc)
void mi_cmd_stack_list_locals (char *command, char **argv, int argc)
void mi_cmd_stack_list_args (char *command, char **argv, int argc)
void mi_cmd_stack_list_variables (char *command, char **argv, int argc)
static void list_arg_or_local (const struct frame_arg *arg, enum what_to_list what, enum print_values values, int skip_unavailable)
void mi_cmd_stack_select_frame (char *command, char **argv, int argc)
void mi_cmd_stack_info_frame (char *command, char **argv, int argc)
Variables
static int frame_filters = 0
Enumeration Type Documentation
enum what_to_list
Enumerator:
locals
arguments
all
Definition at line 40 of file mi-cmd-stack.c.
Function Documentation
static void list_arg_or_local (const struct frame_arg * arg, enum what_to_list what, enum print_values values, int skip_unavailable) [static]
Definition at line 474 of file mi-cmd-stack.c.
References _, all, check_typedef(), common_val_print(), current_uiout, value_print_options::deref_ref, do_cleanups(), frame_arg::entry_kind, frame_arg::error, fprintf_filtered(), fputs_filtered(), gdb_assert, get_no_prettyformat_print_options(), language_def(), make_cleanup_ui_file_delete(), make_cleanup_ui_out_tuple_begin_end(), mem_fileopen(), gdb_exception::message, PRINT_ALL_VALUES, print_entry_values_no, print_entry_values_only, PRINT_NO_VALUES, PRINT_SIMPLE_VALUES, RETURN_MASK_ERROR, frame_arg::sym, SYMBOL_IS_ARGUMENT, SYMBOL_LANGUAGE, SYMBOL_PRINT_NAME, TRY_CATCH, symbol::type, TYPE_LENGTH, type_print(), ui_out_field_int(), ui_out_field_stream(), frame_arg::val, val_print_scalar_type_p(), value_bytes_available(), value_embedded_offset(), value_entirely_unavailable(), and value_type().
Referenced by list_args_or_locals().
static void list_args_or_locals (enum what_to_list what, enum print_values values, struct frame_info * fi, int skip_unavailable) [static]
Definition at line 559 of file mi-cmd-stack.c.
References all, ALL_BLOCK_SYMBOLS, arguments, BLOCK_FUNCTION, BLOCK_SUPERBLOCK, check_typedef(), current_uiout, do_cleanups(), frame_arg::entry_kind, frame_arg::error, gdb_assert, get_frame_block(), internal_error(), list_arg_or_local(), LOC_ARG, LOC_BLOCK, LOC_COMPUTED, LOC_CONST, LOC_CONST_BYTES, LOC_LABEL, LOC_LOCAL, LOC_OPTIMIZED_OUT, LOC_REF_ARG, LOC_REGISTER, LOC_REGPARM_ADDR, LOC_STATIC, LOC_TYPEDEF, LOC_UNDEF, LOC_UNRESOLVED, locals, lookup_symbol(), make_cleanup_ui_out_list_begin_end(), memset(), PRINT_ALL_VALUES, print_entry_values_no, print_entry_values_only, PRINT_SIMPLE_VALUES, read_frame_arg(), read_frame_local(), frame_arg::sym, SYMBOL_CLASS, SYMBOL_IS_ARGUMENT, SYMBOL_LINKAGE_NAME, type, symbol::type, TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_STRUCT, TYPE_CODE_UNION, VAR_DOMAIN, and xfree().
Referenced by mi_cmd_stack_list_args(), mi_cmd_stack_list_locals(), and mi_cmd_stack_list_variables().
void mi_cmd_enable_frame_filters (char * command, char ** argv, int argc)
Definition at line 51 of file mi-cmd-stack.c.
References _, error(), frame_filters, and mi_cmd_enable_frame_filters.
void mi_cmd_stack_info_depth (char * command, char ** argv, int argc)
Definition at line 170 of file mi-cmd-stack.c.
References _, current_uiout, error(), get_current_frame(), get_prev_frame(), mi_cmd_stack_info_depth, QUIT, and ui_out_field_int().
void mi_cmd_stack_info_frame (char * command, char ** argv, int argc)
Definition at line 689 of file mi-cmd-stack.c.
References _, error(), get_selected_frame(), LOC_AND_ADDRESS, mi_cmd_stack_info_frame, and print_frame_info().
void mi_cmd_stack_list_args (char * command, char ** argv, int argc)
Definition at line 275 of file mi-cmd-stack.c.
References _, apply_frame_filter(), arguments, current_uiout, do_cleanups(), error(), flags, frame_filters, get_current_frame(), get_prev_frame(), list_args_or_locals(), make_cleanup_ui_out_list_begin_end(), make_cleanup_ui_out_tuple_begin_end(), mi_cmd_stack_list_args, mi_getopt_allow_unknown(), mi_parse_print_values(), PRINT_ARGS, PRINT_LEVEL, PY_BT_ERROR, PY_BT_NO_FILTERS, QUIT, and ui_out_field_int().
void mi_cmd_stack_list_frames (char * command, char ** argv, int argc)
Definition at line 65 of file mi-cmd-stack.c.
References _, apply_frame_filter(), current_uiout, do_cleanups(), error(), flags, frame_filters, get_current_frame(), get_prev_frame(), LOC_AND_ADDRESS, make_cleanup_ui_out_list_begin_end(), mi_cmd_stack_list_frames, mi_getopt(), NO_VALUES, PRINT_FRAME_INFO, print_frame_info(), PRINT_LEVEL, PY_BT_ERROR, PY_BT_NO_FILTERS, and QUIT.
void mi_cmd_stack_list_locals (char * command, char ** argv, int argc)
Definition at line 199 of file mi-cmd-stack.c.
References _, apply_frame_filter(), current_uiout, error(), flags, frame_filters, get_selected_frame(), list_args_or_locals(), locals, mi_cmd_stack_list_locals, mi_getopt(), mi_parse_print_values(), PRINT_LEVEL, PRINT_LOCALS, PY_BT_ERROR, and PY_BT_NO_FILTERS.
void mi_cmd_stack_list_variables (char * command, char ** argv, int argc)
Definition at line 396 of file mi-cmd-stack.c.
References _, all, apply_frame_filter(), current_uiout, error(), flags, frame_filters, get_selected_frame(), list_args_or_locals(), mi_cmd_stack_list_variables, mi_getopt(), mi_parse_print_values(), PRINT_ARGS, PRINT_LEVEL, PRINT_LOCALS, PY_BT_ERROR, and PY_BT_NO_FILTERS.
void mi_cmd_stack_select_frame (char * command, char ** argv, int argc)
Definition at line 680 of file mi-cmd-stack.c.
References _, error(), mi_cmd_stack_select_frame, and select_frame_command().
Variable Documentation
int frame_filters = 0 [static]
Definition at line 48 of file mi-cmd-stack.c.
Referenced by mi_cmd_enable_frame_filters(), mi_cmd_stack_list_args(), mi_cmd_stack_list_frames(), mi_cmd_stack_list_locals(), and mi_cmd_stack_list_variables().