GDB (xrefs): /home/stan/gdb/src/gdb/mi/mi-cmd-break.c File Reference
/home/stan/gdb/src/gdb/mi/mi-cmd-break.c File Reference
#include "defs.h"
#include "arch-utils.h"
#include "mi-cmds.h"
#include "ui-out.h"
#include "mi-out.h"
#include "breakpoint.h"
#include "gdb_string.h"
#include "mi-getopt.h"
#include "gdb.h"
#include "exceptions.h"
#include "observer.h"
#include "mi-main.h"
#include "mi-cmd-break.h"
#include "gdb_obstack.h"
#include <ctype.h>
Enumerations
enum { FROM_TTY = 0 }
enum bp_type { REG_BP, HW_BP, REGEXP_BP }
enum wp_type { REG_WP, READ_WP, ACCESS_WP }
Functions
static void breakpoint_notify (struct breakpoint *b)
struct cleanup * setup_breakpoint_reporting (void)
static char * mi_argv_to_format (char **argv, int argc)
static void mi_cmd_break_insert_1 (int dprintf, char *command, char **argv, int argc)
void mi_cmd_break_insert (char *command, char **argv, int argc)
void mi_cmd_dprintf_insert (char *command, char **argv, int argc)
void mi_cmd_break_passcount (char *command, char **argv, int argc)
void mi_cmd_break_watch (char *command, char **argv, int argc)
static char * mi_read_next_line (void)
void mi_cmd_break_commands (char *command, char **argv, int argc)
Variables
static int mi_breakpoint_observers_installed
static int mi_can_breakpoint_notify
static char ** mi_command_line_array
static int mi_command_line_array_cnt
static int mi_command_line_array_ptr
Enumeration Type Documentation
anonymous enum
Enumerator:
FROM_TTY
Definition at line 36 of file mi-cmd-break.c.
enum bp_type
Enumerator:
REG_BP
HW_BP
REGEXP_BP
Definition at line 58 of file mi-cmd-break.c.
enum wp_type
Enumerator:
REG_WP
READ_WP
ACCESS_WP
Definition at line 320 of file mi-cmd-break.c.
Function Documentation
static void breakpoint_notify (struct breakpoint * b) [static]
Definition at line 52 of file mi-cmd-break.c.
References current_uiout, gdb_breakpoint_query(), mi_can_breakpoint_notify, and breakpoint::number.
Referenced by setup_breakpoint_reporting().
static char* mi_argv_to_format (char ** argv, int argc) [static]
Definition at line 93 of file mi-cmd-break.c.
References xsnprintf().
Referenced by mi_cmd_break_insert_1().
void mi_cmd_break_commands (char * command, char ** argv, int argc)
Definition at line 437 of file mi-cmd-break.c.
References _, break_command(), breakpoint_set_commands(), check_tracepoint_command(), error(), get_breakpoint(), is_tracepoint(), mi_cmd_break_commands, mi_command_line_array, mi_command_line_array_cnt, mi_command_line_array_ptr, mi_read_next_line(), and read_command_lines_1().
void mi_cmd_break_insert (char * command, char ** argv, int argc)
Definition at line 306 of file mi-cmd-break.c.
References mi_cmd_break_insert, and mi_cmd_break_insert_1().
static void mi_cmd_break_insert_1 (int dprintf, char * command, char ** argv, int argc) [static]
Definition at line 169 of file mi-cmd-break.c.
References _, AUTO_BOOLEAN_FALSE, AUTO_BOOLEAN_TRUE, bkpt_breakpoint_ops, bp_breakpoint, bp_dprintf, bp_fast_tracepoint, bp_hardware_breakpoint, bp_tracepoint, create_breakpoint(), do_cleanups(), dprintf_breakpoint_ops, error(), get_current_arch(), make_cleanup(), mi_argv_to_format(), mi_getopt(), null_cleanup(), setup_breakpoint_reporting(), tracepoint_breakpoint_ops, and xfree().
Referenced by mi_cmd_break_insert(), and mi_cmd_dprintf_insert().
void mi_cmd_break_passcount (char * command, char ** argv, int argc)
Definition at line 328 of file mi-cmd-break.c.
References _, tracepoint::base, error(), get_tracepoint(), mi_cmd_break_passcount, observer_notify_breakpoint_modified(), p, and tracepoint::pass_count.
void mi_cmd_break_watch (char * command, char ** argv, int argc)
Definition at line 359 of file mi-cmd-break.c.
References _, ACCESS_WP, awatch_command_wrapper(), error(), FROM_TTY, mi_cmd_break_watch, mi_getopt(), READ_WP, REG_WP, rwatch_command_wrapper(), and watch_command_wrapper().
void mi_cmd_dprintf_insert (char * command, char ** argv, int argc)
Definition at line 315 of file mi-cmd-break.c.
References mi_cmd_break_insert_1(), and mi_cmd_dprintf_insert.
static char* mi_read_next_line (void) [static]
Definition at line 428 of file mi-cmd-break.c.
References mi_command_line_array, mi_command_line_array_cnt, and mi_command_line_array_ptr.
Referenced by mi_cmd_break_commands().
struct cleanup* setup_breakpoint_reporting (void) [read]
Definition at line 72 of file mi-cmd-break.c.
References breakpoint_notify(), make_cleanup_restore_integer(), mi_breakpoint_observers_installed, mi_can_breakpoint_notify, and observer_attach_breakpoint_created().
Referenced by mi_catch_load_unload(), mi_cmd_break_insert_1(), mi_cmd_catch_assert(), and mi_cmd_catch_exception().
Variable Documentation
int mi_breakpoint_observers_installed [static]
Definition at line 43 of file mi-cmd-break.c.
Referenced by setup_breakpoint_reporting().
int mi_can_breakpoint_notify [static]
Definition at line 47 of file mi-cmd-break.c.
Referenced by breakpoint_notify(), and setup_breakpoint_reporting().
char** mi_command_line_array [static]
Definition at line 423 of file mi-cmd-break.c.
Referenced by mi_cmd_break_commands(), and mi_read_next_line().
int mi_command_line_array_cnt [static]
Definition at line 424 of file mi-cmd-break.c.
Referenced by mi_cmd_break_commands(), and mi_read_next_line().
int mi_command_line_array_ptr [static]
Definition at line 425 of file mi-cmd-break.c.
Referenced by mi_cmd_break_commands(), and mi_read_next_line().