GDB (xrefs): /home/stan/gdb/src/gdb/mi/mi-cmd-file.c File Reference
/home/stan/gdb/src/gdb/mi/mi-cmd-file.c File Reference
#include "defs.h"
#include "mi-cmds.h"
#include "mi-getopt.h"
#include "ui-out.h"
#include "symtab.h"
#include "source.h"
#include "objfiles.h"
#include "psymtab.h"
Functions
void mi_cmd_file_list_exec_source_file (char *command, char **argv, int argc)
static void print_partial_file_name (const char *filename, const char *fullname, void *ignore)
void mi_cmd_file_list_exec_source_files (char *command, char **argv, int argc)
Function Documentation
void mi_cmd_file_list_exec_source_file (char * command, char ** argv, int argc)
Definition at line 33 of file mi-cmd-file.c.
References _, current_uiout, error(), get_current_source_symtab_and_line(), symtab_and_line::line, symtab::macro_table, mi_cmd_file_list_exec_source_file, mi_valid_noargs(), set_default_source_symtab_and_line(), symtab_and_line::symtab, symtab_to_filename_for_display(), symtab_to_fullname(), ui_out_field_int(), and ui_out_field_string().
void mi_cmd_file_list_exec_source_files (char * command, char ** argv, int argc)
Definition at line 80 of file mi-cmd-file.c.
References _, ALL_SYMTABS, current_uiout, error(), map_partial_symbol_filenames(), mi_cmd_file_list_exec_source_files, mi_valid_noargs(), print_partial_file_name(), symtab_to_filename_for_display(), symtab_to_fullname(), ui_out_begin(), ui_out_end(), ui_out_field_string(), ui_out_type_list, and ui_out_type_tuple.
static void print_partial_file_name (const char * filename, const char * fullname, void * ignore) [static]
Definition at line 64 of file mi-cmd-file.c.
References current_uiout, ui_out_begin(), ui_out_end(), ui_out_field_string(), and ui_out_type_tuple.
Referenced by mi_cmd_file_list_exec_source_files().