GDB (xrefs): /home/stan/gdb/src/gdb/mi/mi-console.h File Reference
/home/stan/gdb/src/gdb/mi/mi-console.h File Reference
Functions
struct ui_file * mi_console_file_new (struct ui_file *raw, const char *prefix, char quote)
void mi_console_set_raw (struct ui_file *console, struct ui_file *raw)
Function Documentation
struct ui_file* mi_console_file_new (struct ui_file * raw, const char * prefix, char quote) [read]
Definition at line 52 of file mi-console.c.
References mi_console_file::buffer, mi_console_file::magic, mem_fileopen(), mi_console_file_delete, mi_console_file_flush, mi_console_file_fputs, mi_console_file_magic, mi_console_file::prefix, mi_console_file::quote, mi_console_file::raw, set_ui_file_data(), set_ui_file_flush(), set_ui_file_fputs(), ui_file_new(), and XMALLOC.
Referenced by mi_interpreter_init().
void mi_console_set_raw (struct ui_file * console, struct ui_file * raw)
Definition at line 146 of file mi-console.c.
References _, internal_error(), mi_console_file::magic, mi_console_file_magic, mi_console_file::raw, and ui_file_data().
Referenced by mi_set_logging().