GDB (xrefs): /home/stan/gdb/src/gdb/mi/mi-cmd-break.h File Reference
/home/stan/gdb/src/gdb/mi/mi-cmd-break.h File Reference
Functions
struct cleanup * setup_breakpoint_reporting (void)
Function Documentation
struct cleanup* setup_breakpoint_reporting (void) [read]
Definition at line 72 of file mi-cmd-break.c.
References breakpoint_notify(), make_cleanup_restore_integer(), mi_breakpoint_observers_installed, mi_can_breakpoint_notify, and observer_attach_breakpoint_created().
Referenced by mi_catch_load_unload(), mi_cmd_break_insert_1(), mi_cmd_catch_assert(), and mi_cmd_catch_exception().