GDB (xrefs): /home/stan/gdb/src/gdb/mi/mi-cmd-catch.c File Reference
/home/stan/gdb/src/gdb/mi/mi-cmd-catch.c File Reference
#include "defs.h"
#include "arch-utils.h"
#include "breakpoint.h"
#include "gdb.h"
#include "libiberty.h"
#include "ada-lang.h"
#include "mi-cmds.h"
#include "mi-getopt.h"
#include "mi-cmd-break.h"
Functions
void mi_cmd_catch_assert (char *cmd, char *argv[], int argc)
void mi_cmd_catch_exception (char *cmd, char *argv[], int argc)
static void mi_catch_load_unload (int load, char *argv[], int argc)
void mi_cmd_catch_load (char *cmd, char *argv[], int argc)
void mi_cmd_catch_unload (char *cmd, char *argv[], int argc)
Function Documentation
static void mi_catch_load_unload (int load, char * argv[], int argc) [static]
Definition at line 165 of file mi-cmd-catch.c.
References _, add_solib_catchpoint(), do_cleanups(), error(), mi_getopt(), and setup_breakpoint_reporting().
Referenced by mi_cmd_catch_load(), and mi_cmd_catch_unload().
void mi_cmd_catch_assert (char * cmd, char * argv[], int argc)
Definition at line 34 of file mi-cmd-catch.c.
References _, ada_catch_assert, create_ada_exception_catchpoint(), error(), get_current_arch(), mi_cmd_catch_assert, mi_getopt(), and setup_breakpoint_reporting().
void mi_cmd_catch_exception (char * cmd, char * argv[], int argc)
Definition at line 91 of file mi-cmd-catch.c.
References _, ada_catch_exception, ada_catch_exception_unhandled, create_ada_exception_catchpoint(), error(), get_current_arch(), mi_cmd_catch_exception, mi_getopt(), and setup_breakpoint_reporting().
void mi_cmd_catch_load (char * cmd, char * argv[], int argc)
Definition at line 219 of file mi-cmd-catch.c.
References mi_catch_load_unload(), and mi_cmd_catch_load.
void mi_cmd_catch_unload (char * cmd, char * argv[], int argc)
Definition at line 228 of file mi-cmd-catch.c.
References mi_catch_load_unload(), and mi_cmd_catch_unload.