GDB (xrefs): /home/stan/gdb/src/gdb/mi/mi-console.c File Reference
/home/stan/gdb/src/gdb/mi/mi-console.c File Reference
#include "defs.h"
#include "mi-console.h"
#include "gdb_string.h"
Classes
struct mi_console_file
Functions
struct ui_file * mi_console_file_new (struct ui_file *raw, const char *prefix, char quote)
static void mi_console_file_delete (struct ui_file *file)
static void mi_console_file_fputs (const char *buf, struct ui_file *file)
static void mi_console_raw_packet (void *data, const char *buf, long length_buf)
static void mi_console_file_flush (struct ui_file *file)
void mi_console_set_raw (struct ui_file *file, struct ui_file *raw)
Variables
static ui_file_fputs_ftype mi_console_file_fputs
static ui_file_flush_ftype mi_console_file_flush
static ui_file_delete_ftype mi_console_file_delete
static int mi_console_file_magic
Function Documentation
static void mi_console_file_delete (struct ui_file * file) [static]
Definition at line 70 of file mi-console.c.
References _, internal_error(), mi_console_file::magic, mi_console_file_magic, ui_file_data(), and xfree().
static void mi_console_file_flush (struct ui_file * file) [static]
Definition at line 128 of file mi-console.c.
References _, mi_console_file::buffer, internal_error(), mi_console_file::magic, mi_console_file_magic, mi_console_raw_packet(), ui_file_data(), ui_file_put(), and ui_file_rewind().
static void mi_console_file_fputs (const char * buf, struct ui_file * file) [static]
Definition at line 82 of file mi-console.c.
References mi_console_file::buffer, fputs_unfiltered(), gdb_flush(), internal_error(), mi_console_file::magic, mi_console_file_magic, strchr(), and ui_file_data().
struct ui_file* mi_console_file_new (struct ui_file * raw, const char * prefix, char quote) [read]
Definition at line 52 of file mi-console.c.
References mi_console_file::buffer, mi_console_file::magic, mem_fileopen(), mi_console_file_delete, mi_console_file_flush, mi_console_file_fputs, mi_console_file_magic, mi_console_file::prefix, mi_console_file::quote, mi_console_file::raw, set_ui_file_data(), set_ui_file_flush(), set_ui_file_fputs(), ui_file_new(), and XMALLOC.
Referenced by mi_interpreter_init().
static void mi_console_raw_packet (void * data, const char * buf, long length_buf) [static]
Definition at line 100 of file mi-console.c.
References _, fputs_unfiltered(), fputstrn_unfiltered(), gdb_flush(), internal_error(), mi_console_file::magic, mi_console_file_magic, mi_console_file::prefix, mi_console_file::quote, and mi_console_file::raw.
Referenced by mi_console_file_flush().
void mi_console_set_raw (struct ui_file * file, struct ui_file * raw)
Definition at line 146 of file mi-console.c.
References _, internal_error(), mi_console_file::magic, mi_console_file_magic, mi_console_file::raw, and ui_file_data().
Referenced by mi_set_logging().
Variable Documentation
ui_file_delete_ftype mi_console_file_delete [static]
Definition at line 33 of file mi-console.c.
Referenced by mi_console_file_new().
ui_file_flush_ftype mi_console_file_flush [static]
Definition at line 32 of file mi-console.c.
Referenced by mi_console_file_new().
ui_file_fputs_ftype mi_console_file_fputs [static]
Definition at line 31 of file mi-console.c.
Referenced by mi_console_file_new().
int mi_console_file_magic [static]
Definition at line 46 of file mi-console.c.
Referenced by mi_console_file_delete(), mi_console_file_flush(), mi_console_file_fputs(), mi_console_file_new(), mi_console_raw_packet(), and mi_console_set_raw().