GDB (xrefs): /home/stan/gdb/src/gdb/mi/mi-common.c File Reference
/home/stan/gdb/src/gdb/mi/mi-common.c File Reference
#include "defs.h"
#include "gdb_assert.h"
#include "mi-common.h"
Functions
gdb_static_assert (ARRAY_SIZE(async_reason_string_lookup)==EXEC_ASYNC_LAST+1)
const char * async_reason_lookup (enum async_reply_reason reason)
Variables
static const char *const async_reason_string_lookup []
Function Documentation
const char* async_reason_lookup (enum async_reply_reason reason)
Definition at line 50 of file mi-common.c.
References async_reason_string_lookup.
Referenced by bkpt_print_it(), momentary_bkpt_print_it(), print_end_stepping_range_reason(), print_exited_reason(), print_it_catch_exec(), print_it_catch_fork(), print_it_catch_syscall(), print_it_catch_vfork(), print_it_exception(), print_it_exception_catchpoint(), print_it_masked_watchpoint(), print_it_ranged_breakpoint(), print_it_watchpoint(), print_signal_exited_reason(), print_signal_received_reason(), print_solib_event(), and watchpoint_check().
gdb_static_assert (ARRAY_SIZE(async_reason_string_lookup) = =EXEC_ASYNC_LAST+1)
Variable Documentation
const char* const async_reason_string_lookup[] [static]
Initial value:
{
  "breakpoint-hit",
  "watchpoint-trigger",
  "read-watchpoint-trigger",
  "access-watchpoint-trigger",
  "function-finished",
  "location-reached",
  "watchpoint-scope",
  "end-stepping-range",
  "exited-signalled",
  "exited",
  "exited-normally",
  "signal-received",
  "solib-event",
  "fork",
  "vfork",
  "syscall-entry",
  "syscall-return",
  "exec",
  NULL
}
Definition at line 23 of file mi-common.c.
Referenced by async_reason_lookup().