GDB (xrefs): /home/stan/gdb/src/gdb/mi/mi-cmd-var.c File Reference
/home/stan/gdb/src/gdb/mi/mi-cmd-var.c File Reference
#include "defs.h"
#include "mi-cmds.h"
#include "mi-main.h"
#include "ui-out.h"
#include "mi-out.h"
#include "varobj.h"
#include "value.h"
#include <ctype.h>
#include "gdb_string.h"
#include "mi-getopt.h"
#include "gdbthread.h"
#include "mi-parse.h"
Classes
struct mi_cmd_var_update
Functions
static void varobj_update_one (struct varobj *var, enum print_values print_values, int explicit)
static int mi_print_value_p (struct varobj *var, enum print_values print_values)
static void print_varobj (struct varobj *var, enum print_values print_values, int print_expression)
void mi_cmd_var_create (char *command, char **argv, int argc)
void mi_cmd_var_delete (char *command, char **argv, int argc)
static enum varobj_display_formats mi_parse_format (const char *arg)
void mi_cmd_var_set_format (char *command, char **argv, int argc)
void mi_cmd_var_set_visualizer (char *command, char **argv, int argc)
void mi_cmd_var_set_frozen (char *command, char **argv, int argc)
void mi_cmd_var_show_format (char *command, char **argv, int argc)
void mi_cmd_var_info_num_children (char *command, char **argv, int argc)
static int mi_print_value_p (struct varobj *var, enum print_values print_values)
void mi_cmd_var_list_children (char *command, char **argv, int argc)
void mi_cmd_var_info_type (char *command, char **argv, int argc)
void mi_cmd_var_info_path_expression (char *command, char **argv, int argc)
void mi_cmd_var_info_expression (char *command, char **argv, int argc)
void mi_cmd_var_show_attributes (char *command, char **argv, int argc)
void mi_cmd_var_evaluate_expression (char *command, char **argv, int argc)
void mi_cmd_var_assign (char *command, char **argv, int argc)
static void mi_cmd_var_update_iter (struct varobj *var, void *data_pointer)
void mi_cmd_var_update (char *command, char **argv, int argc)
static void varobj_update_one (struct varobj *var, enum print_values print_values, int explicit)
void mi_cmd_enable_pretty_printing (char *command, char **argv, int argc)
void mi_cmd_var_set_update_range (char *command, char **argv, int argc)
Variables
unsigned int varobjdebug
Function Documentation
void mi_cmd_enable_pretty_printing (char * command, char ** argv, int argc)
Definition at line 814 of file mi-cmd-var.c.
References _, error(), mi_cmd_enable_pretty_printing, and varobj_enable_pretty_printing().
void mi_cmd_var_assign (char * command, char ** argv, int argc)
Definition at line 591 of file mi-cmd-var.c.
References _, current_uiout, do_cleanups(), error(), make_cleanup_restore_integer(), mi_suppress_notification::memory, mi_cmd_var_assign, ui_out_field_string(), varobj_editable_p(), varobj_get_handle(), varobj_get_value(), varobj_set_value(), and xfree().
void mi_cmd_var_create (char * command, char ** argv, int argc)
Definition at line 97 of file mi-cmd-var.c.
References _, current_uiout, do_cleanups(), error(), fprintf_unfiltered(), free_current_contents(), gdb_stdlog, hex_string(), make_cleanup(), mi_cmd_var_create, name, PRINT_ALL_VALUES, print_varobj(), string_to_core_addr(), ui_out_field_int(), USE_CURRENT_FRAME, USE_SELECTED_FRAME, USE_SPECIFIED_FRAME, varobj_create(), varobj_gen_name(), varobj_has_more(), varobjdebug, and xfree().
void mi_cmd_var_delete (char * command, char ** argv, int argc)
Definition at line 158 of file mi-cmd-var.c.
References _, current_uiout, do_cleanups(), error(), free_current_contents(), make_cleanup(), mi_cmd_var_delete, name, ui_out_field_int(), varobj_delete(), and varobj_get_handle().
void mi_cmd_var_evaluate_expression (char * command, char ** argv, int argc)
Definition at line 522 of file mi-cmd-var.c.
References _, current_uiout, error(), FORMAT_NATURAL, mi_cmd_var_evaluate_expression, mi_getopt(), mi_parse_format(), ui_out_field_string(), varobj_get_formatted_value(), varobj_get_handle(), varobj_get_value(), and xfree().
void mi_cmd_var_info_expression (char * command, char ** argv, int argc)
Definition at line 479 of file mi-cmd-var.c.
References _, current_uiout, error(), mi_cmd_var_info_expression, ui_out_field_string(), varobj_get_expression(), varobj_get_handle(), varobj_get_language(), and varobj_language_string.
void mi_cmd_var_info_num_children (char * command, char ** argv, int argc)
Definition at line 326 of file mi-cmd-var.c.
References _, current_uiout, error(), mi_cmd_var_info_num_children, ui_out_field_int(), varobj_get_handle(), and varobj_get_num_children().
void mi_cmd_var_info_path_expression (char * command, char ** argv, int argc)
Definition at line 461 of file mi-cmd-var.c.
References _, current_uiout, error(), mi_cmd_var_info_path_expression, varobj::path_expr, ui_out_field_string(), varobj_get_handle(), and varobj_get_path_expr().
void mi_cmd_var_info_type (char * command, char ** argv, int argc)
Definition at line 446 of file mi-cmd-var.c.
References _, current_uiout, error(), mi_cmd_var_info_type, ui_out_field_string(), varobj_get_handle(), and varobj_get_type().
void mi_cmd_var_list_children (char * command, char ** argv, int argc)
Definition at line 373 of file mi-cmd-var.c.
References _, current_uiout, do_cleanups(), error(), from, make_cleanup_ui_out_list_begin_end(), make_cleanup_ui_out_tuple_begin_end(), mi_cmd_var_list_children, mi_parse_print_values(), mi_version(), PRINT_NO_VALUES, print_varobj(), to, ui_out_field_int(), ui_out_field_string(), varobj_get_display_hint(), varobj_get_handle(), varobj_has_more(), VEC, VEC_iterate, and xfree().
void mi_cmd_var_set_format (char * command, char ** argv, int argc)
Definition at line 238 of file mi-cmd-var.c.
References _, current_uiout, error(), mi_cmd_var_set_format, mi_parse_format(), ui_out_field_string(), varobj_format_string, varobj_get_handle(), varobj_get_value(), varobj_set_display_format(), and xfree().
void mi_cmd_var_set_frozen (char * command, char ** argv, int argc)
Definition at line 282 of file mi-cmd-var.c.
References _, error(), mi_cmd_var_set_frozen, varobj_get_handle(), and varobj_set_frozen().
void mi_cmd_var_set_update_range (char * command, char ** argv, int argc)
Definition at line 823 of file mi-cmd-var.c.
References _, error(), from, mi_cmd_var_set_update_range, to, varobj_get_handle(), and varobj_set_child_range().
void mi_cmd_var_set_visualizer (char * command, char ** argv, int argc)
Definition at line 266 of file mi-cmd-var.c.
References _, error(), mi_cmd_var_set_visualizer, varobj_get_handle(), and varobj_set_visualizer().
void mi_cmd_var_show_attributes (char * command, char ** argv, int argc)
Definition at line 498 of file mi-cmd-var.c.
References _, current_uiout, error(), mi_cmd_var_show_attributes, ui_out_field_string(), varobj_get_attributes(), and varobj_get_handle().
void mi_cmd_var_show_format (char * command, char ** argv, int argc)
Definition at line 307 of file mi-cmd-var.c.
References _, current_uiout, error(), mi_cmd_var_show_format, ui_out_field_string(), varobj_format_string, varobj_get_display_format(), and varobj_get_handle().
void mi_cmd_var_update (char * command, char ** argv, int argc)
Definition at line 662 of file mi-cmd-var.c.
References _, all_root_varobjs(), current_uiout, do_cleanups(), error(), make_cleanup_ui_out_list_begin_end(), make_cleanup_ui_out_tuple_begin_end(), mi_cmd_var_update_iter(), mi_parse_print_values(), mi_version(), name, mi_cmd_var_update::only_floating, PRINT_NO_VALUES, mi_cmd_var_update::print_values, varobj_get_handle(), and varobj_update_one().
static void mi_cmd_var_update_iter (struct varobj * var, void * data_pointer) [static]
Definition at line 637 of file mi-cmd-var.c.
References find_thread_id(), inferior_ptid, is_stopped(), mi_cmd_var_update::only_floating, mi_cmd_var_update::print_values, thread_info::ptid, varobj_floating_p(), varobj_get_thread_id(), and varobj_update_one().
Referenced by mi_cmd_var_update().
static enum varobj_display_formats mi_parse_format (const char * arg) [static]
Definition at line 213 of file mi-cmd-var.c.
References _, error(), FORMAT_BINARY, FORMAT_DECIMAL, FORMAT_HEXADECIMAL, FORMAT_NATURAL, FORMAT_OCTAL, and len.
Referenced by mi_cmd_var_evaluate_expression(), and mi_cmd_var_set_format().
static int mi_print_value_p (struct varobj * var, enum print_values print_values) [static]
Referenced by print_varobj(), and varobj_update_one().
static int mi_print_value_p (struct varobj * var, enum print_values print_values) [static]
Definition at line 344 of file mi-cmd-var.c.
References check_typedef(), PRINT_ALL_VALUES, PRINT_NO_VALUES, type, TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_STRUCT, TYPE_CODE_UNION, varobj_get_gdb_type(), and varobj_pretty_printed_p().
static void print_varobj (struct varobj * var, enum print_values print_values, int print_expression) [static]
Definition at line 48 of file mi-cmd-var.c.
References current_uiout, mi_print_value_p(), type, ui_out_field_int(), ui_out_field_string(), varobj_get_display_hint(), varobj_get_expression(), varobj_get_frozen(), varobj_get_num_children(), varobj_get_objname(), varobj_get_thread_id(), varobj_get_type(), varobj_get_value(), varobj_pretty_printed_p(), and xfree().
Referenced by mi_cmd_var_create(), mi_cmd_var_list_children(), and varobj_update_one().
static void varobj_update_one (struct varobj * var, enum print_values print_values, int explicit) [static]
Referenced by mi_cmd_var_update(), and mi_cmd_var_update_iter().
static void varobj_update_one (struct varobj * var, enum print_values print_values, int explicit) [static]
Definition at line 717 of file mi-cmd-var.c.
References varobj_update_result_t::children_changed, current_uiout, do_cleanups(), from, make_cleanup(), make_cleanup_ui_out_list_begin_end(), make_cleanup_ui_out_tuple_begin_end(), mi_print_value_p(), mi_version(), null_cleanup(), print_varobj(), varobj_update_result_t::status, to, varobj_update_result_t::type_changed, ui_out_field_int(), ui_out_field_string(), varobj_update_result_t::varobj, varobj_get_child_range(), varobj_get_display_hint(), varobj_get_num_children(), varobj_get_objname(), varobj_get_type(), varobj_get_value(), varobj_has_more(), VAROBJ_IN_SCOPE, VAROBJ_INVALID, VAROBJ_NOT_IN_SCOPE, varobj_pretty_printed_p(), VEC, VEC_free, VEC_iterate, and xfree().
Variable Documentation
unsigned int varobjdebug
Definition at line 52 of file varobj.c.
Referenced by mi_cmd_var_create(), and uninstall_variable().