GDB (xrefs): /home/stan/gdb/src/gdb/mi/mi-cmds.c File Reference
/home/stan/gdb/src/gdb/mi/mi-cmds.c File Reference
#include "defs.h"
#include "top.h"
#include "mi-cmds.h"
#include "gdb_string.h"
#include "mi-main.h"
Classes
struct mi_cmd_stats
Defines
#define DEF_MI_CMD_CLI_1(NAME, CLI_NAME, ARGS_P, CALLED) { NAME, { CLI_NAME, ARGS_P}, NULL, CALLED }
#define DEF_MI_CMD_CLI(NAME, CLI_NAME, ARGS_P) DEF_MI_CMD_CLI_1(NAME, CLI_NAME, ARGS_P, NULL)
#define DEF_MI_CMD_MI_1(NAME, MI_FUNC, CALLED) { NAME, {NULL, 0}, MI_FUNC, CALLED }
#define DEF_MI_CMD_MI(NAME, MI_FUNC) DEF_MI_CMD_MI_1(NAME, MI_FUNC, NULL)
Enumerations
enum { MI_TABLE_SIZE = 227 }
Functions
void _initialize_mi_cmds (void)
static struct mi_cmd ** lookup_table (const char *command)
static void build_table (struct mi_cmd *commands)
struct mi_cmd * mi_lookup (const char *command)
Variables
static struct mi_cmd mi_cmds []
static struct mi_cmd ** mi_table
struct mi_cmd_stats stats
Define Documentation
#define DEF_MI_CMD_CLI (NAME, CLI_NAME, ARGS_P) DEF_MI_CMD_CLI_1(NAME, CLI_NAME, ARGS_P, NULL)
#define DEF_MI_CMD_CLI_1 (NAME, CLI_NAME, ARGS_P, CALLED) { NAME, { CLI_NAME, ARGS_P}, NULL, CALLED }
#define DEF_MI_CMD_MI (NAME, MI_FUNC) DEF_MI_CMD_MI_1(NAME, MI_FUNC, NULL)
#define DEF_MI_CMD_MI_1 (NAME, MI_FUNC, CALLED) { NAME, {NULL, 0}, MI_FUNC, CALLED }
Enumeration Type Documentation
anonymous enum
Enumerator:
MI_TABLE_SIZE
Definition at line 186 of file mi-cmds.c.
Function Documentation
void _initialize_mi_cmds (void)
static void build_table (struct mi_cmd * commands) [static]
Definition at line 243 of file mi-cmds.c.
References _, fprintf_filtered(), fprintf_unfiltered(), gdb_stdlog, internal_error(), lookup_table(), memset(), MI_TABLE_SIZE, mi_cmd::name, mi_cmd_stats::rehash, stats, and xmalloc().
static struct mi_cmd ** lookup_table (const char * command) [static, read]
Definition at line 211 of file mi-cmds.c.
References mi_cmd_stats::hit, MI_TABLE_SIZE, mi_cmd_stats::miss, mi_cmd_stats::rehash, and stats.
Referenced by build_table(), and mi_lookup().
struct mi_cmd* mi_lookup (const char * command) [read]
Definition at line 193 of file mi-cmds.c.
References lookup_table().
Referenced by mi_parse().
Variable Documentation
struct mi_cmd mi_cmds[] [static]
Definition at line 33 of file mi-cmds.c.
struct mi_cmd** mi_table [static]
Definition at line 183 of file mi-cmds.c.
struct mi_cmd_stats stats
Definition at line 206 of file mi-cmds.c.
Referenced by build_table(), and lookup_table().