GDB (xrefs): /home/stan/gdb/src/gdb/mi/mi-cmd-env.c File Reference
/home/stan/gdb/src/gdb/mi/mi-cmd-env.c File Reference
#include "defs.h"
#include "inferior.h"
#include "value.h"
#include "mi-out.h"
#include "mi-cmds.h"
#include "mi-getopt.h"
#include "symtab.h"
#include "target.h"
#include "environ.h"
#include "command.h"
#include "ui-out.h"
#include "top.h"
#include "gdb_string.h"
#include "gdb_stat.h"
Functions
static void env_mod_path (char *dirname, char **which_path)
void _initialize_mi_cmd_env (void)
static void env_execute_cli_command (const char *cmd, const char *args)
void mi_cmd_env_pwd (char *command, char **argv, int argc)
void mi_cmd_env_cd (char *command, char **argv, int argc)
void mi_cmd_env_path (char *command, char **argv, int argc)
void mi_cmd_env_dir (char *command, char **argv, int argc)
void mi_cmd_inferior_tty_set (char *command, char **argv, int argc)
void mi_cmd_inferior_tty_show (char *command, char **argv, int argc)
Variables
static const char path_var_name [] = "PATH"
static char * orig_path = NULL
Function Documentation
void _initialize_mi_cmd_env (void)
static void env_execute_cli_command (const char * cmd, const char * args) [static]
Definition at line 49 of file mi-cmd-env.c.
References do_cleanups(), execute_command(), make_cleanup(), run, xfree(), and xstrprintf().
Referenced by mi_cmd_env_cd(), mi_cmd_env_dir(), mi_cmd_env_path(), and mi_cmd_env_pwd().
static void env_mod_path (char * dirname, char ** which_path) [static]
Definition at line 104 of file mi-cmd-env.c.
References add_path().
Referenced by mi_cmd_env_dir(), and mi_cmd_env_path().
void mi_cmd_env_cd (char * command, char ** argv, int argc)
Definition at line 95 of file mi-cmd-env.c.
References _, env_execute_cli_command(), error(), and mi_cmd_env_cd.
void mi_cmd_env_dir (char * command, char ** argv, int argc)
Definition at line 192 of file mi-cmd-env.c.
References current_uiout, dont_repeat(), env_execute_cli_command(), env_mod_path(), forget_cached_source_info(), init_source_path(), mi_cmd_env_dir, mi_getopt(), mi_version(), source_path, ui_out_field_string(), and xfree().
void mi_cmd_env_path (char * command, char ** argv, int argc)
Definition at line 117 of file mi-cmd-env.c.
References current_inferior(), current_uiout, dont_repeat(), env_execute_cli_command(), env_mod_path(), get_in_environ(), mi_cmd_env_path, mi_getopt(), mi_version(), orig_path, path_var_name, set_in_environ(), ui_out_field_string(), and xfree().
void mi_cmd_env_pwd (char * command, char ** argv, int argc)
Definition at line 70 of file mi-cmd-env.c.
References _, current_uiout, env_execute_cli_command(), error(), gdb_dirbuf, mi_cmd_env_pwd, mi_version(), safe_strerror(), and ui_out_field_string().
void mi_cmd_inferior_tty_set (char * command, char ** argv, int argc)
Definition at line 253 of file mi-cmd-env.c.
References mi_cmd_inferior_tty_set, and set_inferior_io_terminal().
void mi_cmd_inferior_tty_show (char * command, char ** argv, int argc)
Definition at line 261 of file mi-cmd-env.c.
References _, current_uiout, error(), get_inferior_io_terminal(), mi_cmd_inferior_tty_show, mi_valid_noargs(), and ui_out_field_string().
Variable Documentation
char* orig_path = NULL [static]
Definition at line 42 of file mi-cmd-env.c.
Referenced by mi_cmd_env_path().
const char path_var_name[] = "PATH" [static]
Definition at line 41 of file mi-cmd-env.c.
Referenced by mi_cmd_env_path().