GDB (xrefs): /home/stan/gdb/src/gdb/mi/mi-getopt.c File Reference
/home/stan/gdb/src/gdb/mi/mi-getopt.c File Reference
#include "defs.h"
#include "mi-getopt.h"
#include "gdb_string.h"
Functions
static int mi_getopt_1 (const char *prefix, int argc, char **argv, const struct mi_opt *opts, int *oind, char **oarg, int error_on_unknown)
int mi_getopt (const char *prefix, int argc, char **argv, const struct mi_opt *opts, int *oind, char **oarg)
int mi_getopt_allow_unknown (const char *prefix, int argc, char **argv, const struct mi_opt *opts, int *oind, char **oarg)
int mi_valid_noargs (const char *prefix, int argc, char **argv)
Function Documentation
int mi_getopt (const char * prefix, int argc, char ** argv, const struct mi_opt * opts, int * oind, char ** oarg)
Definition at line 85 of file mi-getopt.c.
References mi_getopt_1().
Referenced by mi_catch_load_unload(), mi_cmd_break_insert_1(), mi_cmd_break_watch(), mi_cmd_catch_assert(), mi_cmd_catch_exception(), mi_cmd_data_list_register_values(), mi_cmd_data_read_memory(), mi_cmd_data_read_memory_bytes(), mi_cmd_data_write_memory(), mi_cmd_disassemble(), mi_cmd_env_dir(), mi_cmd_env_path(), mi_cmd_exec_run(), mi_cmd_list_thread_groups(), mi_cmd_stack_list_frames(), mi_cmd_stack_list_locals(), mi_cmd_stack_list_variables(), mi_cmd_target_file_delete(), mi_cmd_target_file_get(), mi_cmd_target_file_put(), mi_cmd_trace_frame_collected(), mi_cmd_trace_save(), mi_cmd_var_evaluate_expression(), and mi_valid_noargs().
static int mi_getopt_1 (const char * prefix, int argc, char ** argv, const struct mi_opt * opts, int * oind, char ** oarg, int error_on_unknown) [static]
Definition at line 29 of file mi-getopt.c.
References _, mi_opt::arg_p, error(), mi_opt::index, internal_error(), and mi_opt::name.
Referenced by mi_getopt(), and mi_getopt_allow_unknown().
int mi_getopt_allow_unknown (const char * prefix, int argc, char ** argv, const struct mi_opt * opts, int * oind, char ** oarg)
Definition at line 94 of file mi-getopt.c.
References mi_getopt_1().
Referenced by mi_cmd_stack_list_args().
int mi_valid_noargs (const char * prefix, int argc, char ** argv)
Definition at line 101 of file mi-getopt.c.
References mi_getopt().
Referenced by mi_cmd_file_list_exec_source_file(), mi_cmd_file_list_exec_source_files(), and mi_cmd_inferior_tty_show().