GDB (xrefs): /home/stan/gdb/src/gdb/mi/mi-interp.c File Reference
/home/stan/gdb/src/gdb/mi/mi-interp.c File Reference
#include "defs.h"
#include "gdb_string.h"
#include "interps.h"
#include "event-top.h"
#include "event-loop.h"
#include "inferior.h"
#include "ui-out.h"
#include "top.h"
#include "exceptions.h"
#include "mi-main.h"
#include "mi-cmds.h"
#include "mi-out.h"
#include "mi-console.h"
#include "mi-common.h"
#include "observer.h"
#include "gdbthread.h"
#include "solist.h"
#include "gdb.h"
#include "objfiles.h"
#include "tracepoint.h"
Functions
static void mi_execute_command_wrapper (const char *cmd)
static void mi_execute_command_input_handler (char *cmd)
static void mi_command_loop (void *data)
static int mi_interp_query_hook (const char *ctlstr, va_list ap) ATTRIBUTE_PRINTF(1
static int static void mi_insert_notify_hooks (void)
static void mi_remove_notify_hooks (void)
static void mi_on_normal_stop (struct bpstats *bs, int print_frame)
static void mi_new_thread (struct thread_info *t)
static void mi_thread_exit (struct thread_info *t, int silent)
static void mi_record_changed (struct inferior *, int)
static void mi_inferior_added (struct inferior *inf)
static void mi_inferior_appeared (struct inferior *inf)
static void mi_inferior_exit (struct inferior *inf)
static void mi_inferior_removed (struct inferior *inf)
static void mi_on_resume (ptid_t ptid)
static void mi_solib_loaded (struct so_list *solib)
static void mi_solib_unloaded (struct so_list *solib)
static void mi_about_to_proceed (void)
static void mi_traceframe_changed (int tfnum, int tpnum)
static void mi_tsv_created (const struct trace_state_variable *tsv)
static void mi_tsv_deleted (const struct trace_state_variable *tsv)
static void mi_tsv_modified (const struct trace_state_variable *tsv)
static void mi_breakpoint_created (struct breakpoint *b)
static void mi_breakpoint_deleted (struct breakpoint *b)
static void mi_breakpoint_modified (struct breakpoint *b)
static void mi_command_param_changed (const char *param, const char *value)
static void mi_memory_changed (struct inferior *inf, CORE_ADDR memaddr, ssize_t len, const bfd_byte *myaddr)
static int report_initial_inferior (struct inferior *inf, void *closure)
static void * mi_interpreter_init (struct interp *interp, int top_level)
static int mi_interpreter_resume (void *data)
static int mi_interpreter_suspend (void *data)
static struct gdb_exception mi_interpreter_exec (void *data, const char *command)
static int mi_interpreter_prompt_p (void *data)
void mi_cmd_interpreter_exec (char *command, char **argv, int argc)
static int mi_output_running_pid (struct thread_info *info, void *arg)
static int mi_inferior_count (struct inferior *inf, void *arg)
static struct ui_out * mi_ui_out (struct interp *interp)
static int mi_set_logging (struct interp *interp, int start_log, struct ui_file *out, struct ui_file *logfile)
void _initialize_mi_interp (void)
Variables
struct mi_suppress_notification mi_suppress_notification
static struct ui_file * saved_raw_stdout
initialize_file_ftype _initialize_mi_interp
Function Documentation
void _initialize_mi_interp (void)
Definition at line 957 of file mi-interp.c.
References _initialize_mi_interp, interp_add(), INTERP_MI, INTERP_MI1, INTERP_MI2, INTERP_MI3, interp_new(), mi_command_loop(), mi_interpreter_exec(), mi_interpreter_init(), mi_interpreter_prompt_p(), mi_interpreter_resume(), mi_interpreter_suspend(), mi_set_logging(), and mi_ui_out().
static void mi_about_to_proceed (void) [static]
Definition at line 483 of file mi-interp.c.
References thread_info::control, thread_control_state::in_infcall, inferior_ptid, inferior_thread(), mi_proceeded, null_ptid, and ptid_equal().
Referenced by mi_interpreter_init().
static void mi_breakpoint_created (struct breakpoint * b) [static]
Definition at line 593 of file mi-interp.c.
References mi_suppress_notification::breakpoint, mi_interp::event_channel, fprintf_unfiltered(), gdb_breakpoint_query(), gdb_flush(), interp_ui_out(), breakpoint::number, RETURN_MASK_ERROR, target_terminal_ours, top_level_interpreter(), top_level_interpreter_data(), TRY_CATCH, and ui_out_redirect().
Referenced by mi_interpreter_init().
static void mi_breakpoint_deleted (struct breakpoint * b) [static]
Definition at line 626 of file mi-interp.c.
References mi_suppress_notification::breakpoint, mi_interp::event_channel, fprintf_unfiltered(), gdb_flush(), breakpoint::number, target_terminal_ours, and top_level_interpreter_data().
Referenced by mi_interpreter_init().
static void mi_breakpoint_modified (struct breakpoint * b) [static]
Definition at line 647 of file mi-interp.c.
References mi_suppress_notification::breakpoint, mi_interp::event_channel, fprintf_unfiltered(), gdb_breakpoint_query(), gdb_flush(), interp_ui_out(), breakpoint::number, RETURN_MASK_ERROR, target_terminal_ours, top_level_interpreter(), top_level_interpreter_data(), TRY_CATCH, and ui_out_redirect().
Referenced by mi_interpreter_init().
void mi_cmd_interpreter_exec (char * command, char ** argv, int argc)
Definition at line 218 of file mi-interp.c.
References _, do_cleanups(), error(), interp_exec(), interp_exec_p(), interp_lookup(), make_cleanup(), gdb_exception::message, mi_cmd_interpreter_exec, mi_insert_notify_hooks(), mi_remove_notify_hooks(), null_cleanup(), gdb_exception::reason, and xfree().
static void mi_command_loop (void * data) [static]
Definition at line 311 of file mi-interp.c.
References fputs_unfiltered(), gdb_flush(), raw_stdout, sevenbit_strings, and start_event_loop().
Referenced by _initialize_mi_interp().
static void mi_command_param_changed (const char * param, const char * value) [static]
Definition at line 817 of file mi-interp.c.
References mi_suppress_notification::cmd_param_changed, mi_interp::event_channel, fprintf_unfiltered(), gdb_flush(), interp_ui_out(), target_terminal_ours, top_level_interpreter(), top_level_interpreter_data(), ui_out_field_string(), and ui_out_redirect().
Referenced by mi_interpreter_init().
static void mi_execute_command_input_handler (char * cmd) [static]
Definition at line 302 of file mi-interp.c.
References fputs_unfiltered(), gdb_flush(), mi_execute_command_wrapper(), and raw_stdout.
Referenced by mi_interpreter_resume().
static void mi_execute_command_wrapper (const char * cmd) [static]
Definition at line 294 of file mi-interp.c.
References instream, and mi_execute_command().
Referenced by mi_execute_command_input_handler(), and mi_interpreter_exec().
static void mi_inferior_added (struct inferior * inf) [static]
Definition at line 371 of file mi-interp.c.
References mi_interp::event_channel, fprintf_unfiltered(), gdb_flush(), inferior::num, target_terminal_ours, and top_level_interpreter_data().
Referenced by mi_interpreter_init().
static void mi_inferior_appeared (struct inferior * inf) [static]
Definition at line 383 of file mi-interp.c.
References mi_interp::event_channel, fprintf_unfiltered(), gdb_flush(), inferior::num, inferior::pid, target_terminal_ours, and top_level_interpreter_data().
Referenced by mi_interpreter_init().
static int mi_inferior_count (struct inferior * inf, void * arg) [static]
Definition at line 691 of file mi-interp.c.
References inferior::pid.
Referenced by mi_on_resume().
static void mi_inferior_exit (struct inferior * inf) [static]
Definition at line 395 of file mi-interp.c.
References mi_interp::event_channel, inferior::exit_code, fprintf_unfiltered(), gdb_flush(), inferior::has_exit_code, int_string(), inferior::num, target_terminal_ours, and top_level_interpreter_data().
Referenced by mi_interpreter_init().
static void mi_inferior_removed (struct inferior * inf) [static]
Definition at line 412 of file mi-interp.c.
References mi_interp::event_channel, fprintf_unfiltered(), gdb_flush(), inferior::num, target_terminal_ours, and top_level_interpreter_data().
Referenced by mi_interpreter_init().
static void mi_insert_notify_hooks (void) [static]
Definition at line 276 of file mi-interp.c.
References deprecated_query_hook, and mi_interp_query_hook().
Referenced by mi_cmd_interpreter_exec().
static int mi_interp_query_hook (const char * ctlstr, va_list ap) [static]
Definition at line 288 of file mi-interp.c.
Referenced by mi_insert_notify_hooks().
static struct gdb_exception mi_interpreter_exec (void * data, const char * command) [static, read]
Definition at line 203 of file mi-interp.c.
References exception_none, and mi_execute_command_wrapper().
Referenced by _initialize_mi_interp().
static void* mi_interpreter_init (struct interp * interp, int top_level) [static]
Definition at line 84 of file mi-interp.c.
References mi_interp::err, mi_interp::event_channel, gdb_assert_not_reached, gdb_stdout, INTERP_MI, INTERP_MI1, INTERP_MI2, INTERP_MI3, interp_name(), iterate_over_inferiors(), mi_interp::log, mi_about_to_proceed(), mi_breakpoint_created(), mi_breakpoint_deleted(), mi_breakpoint_modified(), mi_command_param_changed(), mi_console_file_new(), mi_inferior_added(), mi_inferior_appeared(), mi_inferior_exit(), mi_inferior_removed(), mi_memory_changed(), mi_new_thread(), mi_on_normal_stop(), mi_on_resume(), mi_out_new(), mi_record_changed(), mi_solib_loaded(), mi_solib_unloaded(), mi_thread_exit(), mi_traceframe_changed(), mi_tsv_created(), mi_tsv_deleted(), mi_tsv_modified(), mi_version(), name, observer_attach_about_to_proceed(), observer_attach_breakpoint_created(), observer_attach_breakpoint_deleted(), observer_attach_breakpoint_modified(), observer_attach_command_param_changed(), observer_attach_inferior_added(), observer_attach_inferior_appeared(), observer_attach_inferior_exit(), observer_attach_inferior_removed(), observer_attach_memory_changed(), observer_attach_new_thread(), observer_attach_normal_stop(), observer_attach_record_changed(), observer_attach_solib_loaded(), observer_attach_solib_unloaded(), observer_attach_target_resumed(), observer_attach_thread_exit(), observer_attach_traceframe_changed(), observer_attach_tsv_created(), observer_attach_tsv_deleted(), observer_attach_tsv_modified(), mi_interp::out, raw_stdout, report_initial_inferior(), mi_interp::targ, mi_interp::uiout, and XMALLOC.
Referenced by _initialize_mi_interp().
static int mi_interpreter_prompt_p (void * data) [static]
Definition at line 212 of file mi-interp.c.
Referenced by _initialize_mi_interp().
static int mi_interpreter_resume (void * data) [static]
Definition at line 156 of file mi-interp.c.
References async_command_editing_p, call_readline, clear_interpreter_hooks(), deprecated_show_load_progress, mi_interp::err, gdb_readline2(), gdb_setup_readline(), gdb_stderr, gdb_stdlog, gdb_stdout, gdb_stdtarg, gdb_stdtargerr, input_handler, mi_interp::log, mi_execute_command_input_handler(), mi_load_progress(), mi_interp::out, sync_execution, and mi_interp::targ.
Referenced by _initialize_mi_interp().
static int mi_interpreter_suspend (void * data) [static]
Definition at line 196 of file mi-interp.c.
References gdb_disable_readline().
Referenced by _initialize_mi_interp().
static void mi_memory_changed (struct inferior * inf, CORE_ADDR memaddr, ssize_t len, const bfd_byte * myaddr) [static]
Definition at line 843 of file mi-interp.c.
References mi_interp::event_channel, find_pc_section(), flags, fprintf_unfiltered(), gdb_flush(), interp_ui_out(), mi_suppress_notification::memory, inferior::num, objfile::obfd, obj_section::objfile, target_gdbarch(), target_terminal_ours, obj_section::the_bfd_section, top_level_interpreter(), top_level_interpreter_data(), ui_out_field_core_addr(), ui_out_field_fmt(), ui_out_field_string(), and ui_out_redirect().
Referenced by mi_interpreter_init().
static void mi_new_thread (struct thread_info * t) [static]
Definition at line 325 of file mi-interp.c.
References mi_interp::event_channel, find_inferior_pid(), fprintf_unfiltered(), gdb_assert, gdb_flush(), thread_info::num, inferior::num, thread_info::ptid, ptid_get_pid(), and top_level_interpreter_data().
Referenced by mi_interpreter_init().
static void mi_on_normal_stop (struct bpstats * bs, int print_frame) [static]
Definition at line 424 of file mi-interp.c.
References bpstat_print(), current_uiout, do_cleanups(), fputs_unfiltered(), gdb_flush(), get_last_target_status(), get_selected_frame(), inferior_ptid, interp_ui_out(), target_waitstatus::kind, make_cleanup_ui_out_list_begin_end(), mi_out_put(), mi_out_rewind(), mi_print_timing_maybe(), non_stop, pid_to_thread_id(), print_stack_frame(), raw_stdout, SRC_AND_LOC, target_core_of_thread(), top_level_interpreter(), ui_out_field_int(), and ui_out_field_string().
Referenced by mi_interpreter_init().
static void mi_on_resume (ptid_t ptid) [static]
Definition at line 703 of file mi-interp.c.
References thread_info::control, current_token, find_thread_ptid(), fprintf_unfiltered(), fputs_unfiltered(), gdb_assert, gdb_flush(), thread_control_state::in_infcall, inferior_thread(), iterate_over_inferiors(), iterate_over_threads(), mi_inferior_count(), mi_output_running_pid(), mi_proceeded, minus_one_ptid, thread_info::num, ptid_equal(), ptid_get_pid(), ptid_is_pid(), raw_stdout, running_result_record_printed, and target_is_async_p.
Referenced by mi_interpreter_init().
static int mi_output_running_pid (struct thread_info * info, void * arg) [static]
Definition at line 678 of file mi-interp.c.
References fprintf_unfiltered(), thread_info::num, thread_info::ptid, ptid_get_pid(), and raw_stdout.
Referenced by mi_on_resume().
static void mi_record_changed (struct inferior * inferior, int started) [static]
Definition at line 360 of file mi-interp.c.
References mi_interp::event_channel, fprintf_unfiltered(), gdb_flush(), inferior::num, and top_level_interpreter_data().
Referenced by mi_interpreter_init().
static void mi_remove_notify_hooks (void) [static]
Definition at line 282 of file mi-interp.c.
References deprecated_query_hook.
Referenced by mi_cmd_interpreter_exec().
static int mi_set_logging (struct interp * interp, int start_log, struct ui_file * out, struct ui_file * logfile) [static]
Definition at line 915 of file mi-interp.c.
References mi_interp::err, mi_interp::event_channel, interp_data(), mi_interp::log, mi_console_set_raw(), mi_interp::out, raw_stdout, saved_raw_stdout, mi_interp::targ, tee_file_new(), and ui_file_delete().
Referenced by _initialize_mi_interp().
static void mi_solib_loaded (struct so_list * solib) [static]
Definition at line 769 of file mi-interp.c.
References current_inferior(), mi_interp::event_channel, fprintf_unfiltered(), gdb_flush(), gdbarch_has_global_solist(), so_list::so_name, so_list::so_original_name, so_list::symbols_loaded, target_gdbarch(), target_terminal_ours, and top_level_interpreter_data().
Referenced by mi_interpreter_init().
static void mi_solib_unloaded (struct so_list * solib) [static]
Definition at line 793 of file mi-interp.c.
References current_inferior(), mi_interp::event_channel, fprintf_unfiltered(), gdb_flush(), gdbarch_has_global_solist(), so_list::so_name, so_list::so_original_name, target_gdbarch(), target_terminal_ours, and top_level_interpreter_data().
Referenced by mi_interpreter_init().
static void mi_thread_exit (struct thread_info * t, int silent) [static]
Definition at line 339 of file mi-interp.c.
References mi_interp::event_channel, find_inferior_pid(), fprintf_unfiltered(), gdb_flush(), arm-linux::inf, thread_info::num, inferior::num, thread_info::ptid, ptid_get_pid(), target_terminal_ours, and top_level_interpreter_data().
Referenced by mi_interpreter_init().
static void mi_traceframe_changed (int tfnum, int tpnum) [static]
Definition at line 511 of file mi-interp.c.
References mi_interp::event_channel, fprintf_unfiltered(), gdb_flush(), target_terminal_ours, top_level_interpreter_data(), and mi_suppress_notification::traceframe.
Referenced by mi_interpreter_init().
static void mi_tsv_created (const struct trace_state_variable * tsv) [static]
Definition at line 533 of file mi-interp.c.
References mi_interp::event_channel, fprintf_unfiltered(), gdb_flush(), trace_state_variable::initial_value, trace_state_variable::name, plongest(), target_terminal_ours, and top_level_interpreter_data().
Referenced by mi_interpreter_init().
static void mi_tsv_deleted (const struct trace_state_variable * tsv) [static]
Definition at line 549 of file mi-interp.c.
References mi_interp::event_channel, fprintf_unfiltered(), gdb_flush(), trace_state_variable::name, target_terminal_ours, and top_level_interpreter_data().
Referenced by mi_interpreter_init().
static void mi_tsv_modified (const struct trace_state_variable * tsv) [static]
Definition at line 567 of file mi-interp.c.
References mi_interp::event_channel, fprintf_unfiltered(), gdb_flush(), trace_state_variable::initial_value, interp_ui_out(), trace_state_variable::name, plongest(), target_terminal_ours, top_level_interpreter(), top_level_interpreter_data(), ui_out_field_string(), ui_out_redirect(), trace_state_variable::value, and trace_state_variable::value_known.
Referenced by mi_interpreter_init().
static struct ui_out* mi_ui_out (struct interp * interp) [static, read]
Definition at line 899 of file mi-interp.c.
References interp_data(), and mi_interp::uiout.
Referenced by _initialize_mi_interp().
static int report_initial_inferior (struct inferior * inf, void * closure) [static]
Definition at line 882 of file mi-interp.c.
References mi_interp::event_channel, fprintf_unfiltered(), gdb_flush(), inferior::num, and target_terminal_ours.
Referenced by mi_interpreter_init().
Variable Documentation
initialize_file_ftype _initialize_mi_interp
Referenced by _initialize_mi_interp(), and initialize_all_files().
struct mi_suppress_notification mi_suppress_notification
Initial value:
  {
    0,
    0,
    0,
  }
Definition at line 501 of file mi-interp.c.
struct ui_file* saved_raw_stdout [static]
Definition at line 909 of file mi-interp.c.
Referenced by mi_set_logging().