GDB (xrefs): /home/stan/gdb/src/gdb/mi/mi-main.c File Reference
/home/stan/gdb/src/gdb/mi/mi-main.c File Reference
#include "defs.h"
#include "arch-utils.h"
#include "target.h"
#include "inferior.h"
#include "gdb_string.h"
#include "exceptions.h"
#include "top.h"
#include "gdbthread.h"
#include "mi-cmds.h"
#include "mi-parse.h"
#include "mi-getopt.h"
#include "mi-console.h"
#include "ui-out.h"
#include "mi-out.h"
#include "interps.h"
#include "event-loop.h"
#include "event-top.h"
#include "gdbcore.h"
#include "value.h"
#include "regcache.h"
#include "gdb.h"
#include "frame.h"
#include "mi-main.h"
#include "mi-common.h"
#include "language.h"
#include "valprint.h"
#include "osdata.h"
#include "splay-tree.h"
#include "tracepoint.h"
#include "ctf.h"
#include "ada-lang.h"
#include "linespec.h"
#include <ctype.h>
#include <sys/time.h>
Classes
struct collect_cores_data
struct print_one_inferior_data
Enumerations
enum { FROM_TTY = 0 }
Functions
void _initialize_mi_main (void)
static void mi_cmd_execute (struct mi_parse *parse)
static void mi_execute_cli_command (const char *cmd, int args_p, const char *args)
static void mi_execute_async_cli_command (char *cli_command, char **argv, int argc)
static int register_changed_p (int regnum, struct regcache *, struct regcache *)
static void output_register (struct frame_info *, int regnum, int format, int skip_unavailable)
static void timestamp (struct mi_timestamp *tv)
static void print_diff_now (struct mi_timestamp *start)
static void print_diff (struct mi_timestamp *start, struct mi_timestamp *end)
void mi_cmd_gdb_exit (char *command, char **argv, int argc)
void mi_cmd_exec_next (char *command, char **argv, int argc)
void mi_cmd_exec_next_instruction (char *command, char **argv, int argc)
void mi_cmd_exec_step (char *command, char **argv, int argc)
void mi_cmd_exec_step_instruction (char *command, char **argv, int argc)
void mi_cmd_exec_finish (char *command, char **argv, int argc)
void mi_cmd_exec_return (char *command, char **argv, int argc)
void mi_cmd_exec_jump (char *args, char **argv, int argc)
static void proceed_thread (struct thread_info *thread, int pid)
static int proceed_thread_callback (struct thread_info *thread, void *arg)
static void exec_continue (char **argv, int argc)
static void exec_direction_forward (void *notused)
static void exec_reverse_continue (char **argv, int argc)
void mi_cmd_exec_continue (char *command, char **argv, int argc)
static int interrupt_thread_callback (struct thread_info *thread, void *arg)
void mi_cmd_exec_interrupt (char *command, char **argv, int argc)
static int run_one_inferior (struct inferior *inf, void *arg)
void mi_cmd_exec_run (char *command, char **argv, int argc)
static int find_thread_of_process (struct thread_info *ti, void *p)
void mi_cmd_target_detach (char *command, char **argv, int argc)
void mi_cmd_thread_select (char *command, char **argv, int argc)
void mi_cmd_thread_list_ids (char *command, char **argv, int argc)
void mi_cmd_thread_info (char *command, char **argv, int argc)
static int collect_cores (struct thread_info *ti, void *xdata)
static int * unique (int *b, int *e)
static int print_one_inferior (struct inferior *inferior, void *xdata)
static void output_cores (struct ui_out *uiout, const char *field_name, const char *xcores)
static void free_vector_of_ints (void *xvector)
static void do_nothing (splay_tree_key k)
static void free_vector_of_osdata_items (splay_tree_value xvalue)
static int splay_tree_int_comparator (splay_tree_key xa, splay_tree_key xb)
static void free_splay_tree (void *xt)
static void list_available_thread_groups (VEC(int)*ids, int recurse)
void mi_cmd_list_thread_groups (char *command, char **argv, int argc)
void mi_cmd_data_list_register_names (char *command, char **argv, int argc)
void mi_cmd_data_list_changed_registers (char *command, char **argv, int argc)
void mi_cmd_data_list_register_values (char *command, char **argv, int argc)
void mi_cmd_data_write_register_values (char *command, char **argv, int argc)
void mi_cmd_data_evaluate_expression (char *command, char **argv, int argc)
void mi_cmd_data_read_memory (char *command, char **argv, int argc)
void mi_cmd_data_read_memory_bytes (char *command, char **argv, int argc)
void mi_cmd_data_write_memory (char *command, char **argv, int argc)
void mi_cmd_data_write_memory_bytes (char *command, char **argv, int argc)
void mi_cmd_enable_timings (char *command, char **argv, int argc)
void mi_cmd_list_features (char *command, char **argv, int argc)
void mi_cmd_list_target_features (char *command, char **argv, int argc)
void mi_cmd_add_inferior (char *command, char **argv, int argc)
static int get_other_inferior (struct inferior *inf, void *arg)
void mi_cmd_remove_inferior (char *command, char **argv, int argc)
static void captured_mi_execute_command (struct ui_out *uiout, struct mi_parse *context)
static void mi_print_exception (const char *token, struct gdb_exception exception)
void mi_execute_command (const char *cmd, int from_tty)
void mi_load_progress (const char *section_name, unsigned long sent_so_far, unsigned long total_section, unsigned long total_sent, unsigned long grand_total)
void mi_print_timing_maybe (void)
static long timeval_diff (struct timeval start, struct timeval end)
void mi_cmd_trace_define_variable (char *command, char **argv, int argc)
void mi_cmd_trace_list_variables (char *command, char **argv, int argc)
void mi_cmd_trace_find (char *command, char **argv, int argc)
void mi_cmd_trace_save (char *command, char **argv, int argc)
void mi_cmd_trace_start (char *command, char **argv, int argc)
void mi_cmd_trace_status (char *command, char **argv, int argc)
void mi_cmd_trace_stop (char *command, char **argv, int argc)
void mi_cmd_ada_task_info (char *command, char **argv, int argc)
static void print_variable_or_computed (char *expression, enum print_values values)
void mi_cmd_trace_frame_collected (char *command, char **argv, int argc)
Variables
int mi_debug_p
struct ui_file * raw_stdout
static struct mi_timestamp * current_command_ts
static int do_timings = 0
char * current_token
static struct mi_parse * current_context
int running_result_record_printed = 1
int mi_proceeded
Enumeration Type Documentation
anonymous enum
Enumerator:
FROM_TTY
Definition at line 70 of file mi-main.c.
Function Documentation
void _initialize_mi_main (void)
static void captured_mi_execute_command (struct ui_out * uiout, struct mi_parse * context) [static]
Definition at line 1925 of file mi-main.c.
References mi_parse::args, CLI_COMMAND, mi_parse::cmd_start, mi_parse::command, current_interp_named_p(), current_token, do_cleanups(), do_timings, fprintf_unfiltered(), fputs_unfiltered(), free_current_contents(), gdb_stdlog, INTERP_MI, INTERP_MI1, INTERP_MI2, INTERP_MI3, make_cleanup(), mi_cmd_execute(), mi_cmd_interpreter_exec, MI_COMMAND, mi_debug_p, mi_out_put(), mi_out_rewind(), mi_print_timing_maybe(), mi_proceeded, mi_parse::op, running_result_record_printed, and mi_parse::token.
Referenced by mi_execute_command().
static int collect_cores (struct thread_info * ti, void * xdata) [static]
Definition at line 572 of file mi-main.c.
References collect_cores_data::pid, thread_info::ptid, ptid_get_pid(), target_core_of_thread(), and VEC_safe_push.
Referenced by print_one_inferior().
static void do_nothing (splay_tree_key k) [static]
Definition at line 695 of file mi-main.c.
Referenced by list_available_thread_groups().
static void exec_continue (char ** argv, int argc) [static]
Definition at line 231 of file mi-main.c.
References mi_parse::all, continue_1(), do_cleanups(), find_inferior_id(), iterate_over_threads(), make_cleanup_restore_current_thread(), make_cleanup_restore_integer(), non_stop, inferior::pid, proceed_thread_callback(), sched_multi, and mi_parse::thread_group.
Referenced by exec_reverse_continue(), and mi_cmd_exec_continue().
static void exec_direction_forward (void * notused) [static]
Definition at line 283 of file mi-main.c.
References EXEC_FORWARD, and execution_direction.
Referenced by exec_reverse_continue().
static void exec_reverse_continue (char ** argv, int argc) [static]
Definition at line 289 of file mi-main.c.
References _, do_cleanups(), error(), exec_continue(), exec_direction_forward(), EXEC_REVERSE, execution_direction, make_cleanup(), target_can_execute_reverse, and target_shortname.
Referenced by mi_cmd_exec_continue().
static int find_thread_of_process (struct thread_info * ti, void * p) [static]
Definition at line 461 of file mi-main.c.
References is_exited(), thread_info::ptid, and ptid_get_pid().
Referenced by mi_cmd_target_detach().
static void free_splay_tree (void * xt) [static]
Definition at line 718 of file mi-main.c.
Referenced by list_available_thread_groups().
static void free_vector_of_ints (void * xvector) [static]
Definition at line 687 of file mi-main.c.
References VEC, and VEC_free.
Referenced by mi_cmd_list_thread_groups().
static void free_vector_of_osdata_items (splay_tree_value xvalue) [static]
Definition at line 700 of file mi-main.c.
References VEC, and VEC_free.
Referenced by list_available_thread_groups().
static int get_other_inferior (struct inferior * inf, void * arg) [static]
Definition at line 1869 of file mi-main.c.
References current_inferior().
Referenced by mi_cmd_remove_inferior().
static int interrupt_thread_callback (struct thread_info * thread, void * arg) [static]
Definition at line 316 of file mi-main.c.
References is_running(), thread_info::ptid, ptid_get_pid(), and target_stop().
Referenced by mi_cmd_exec_interrupt().
static void list_available_thread_groups (VEC(int)* ids, int recurse) [static]
Definition at line 725 of file mi-main.c.
References compare_positive_ints(), current_uiout, do_cleanups(), do_nothing(), free_splay_tree(), free_vector_of_osdata_items(), get_osdata(), get_osdata_column(), make_cleanup(), make_cleanup_osdata_free(), make_cleanup_ui_out_list_begin_end(), make_cleanup_ui_out_tuple_begin_end(), output_cores(), splay_tree_int_comparator(), ui_out_field_fmt(), ui_out_field_string(), VEC, VEC_address, VEC_iterate, VEC_length, and VEC_safe_push.
Referenced by mi_cmd_list_thread_groups().
void mi_cmd_ada_task_info (char * command, char ** argv, int argc)
Definition at line 2605 of file mi-main.c.
References _, current_inferior(), current_uiout, error(), mi_cmd_ada_task_info, and print_ada_task_info().
void mi_cmd_add_inferior (char * command, char ** argv, int argc)
Definition at line 1853 of file mi-main.c.
References _, add_inferior_with_spaces(), current_uiout, error(), arm-linux::inf, mi_cmd_add_inferior, inferior::num, and ui_out_field_fmt().
void mi_cmd_data_evaluate_expression (char * command, char ** argv, int argc)
Definition at line 1305 of file mi-main.c.
References _, common_val_print(), current_language, current_uiout, value_print_options::deref_ref, do_cleanups(), error(), evaluate_expression(), free_current_contents(), get_user_print_options(), make_cleanup(), make_cleanup_ui_file_delete(), mem_fileopen(), mi_cmd_data_evaluate_expression, parse_expression(), and ui_out_field_stream().
void mi_cmd_data_list_changed_registers (char * command, char ** argv, int argc)
Definition at line 1004 of file mi-main.c.
References _, current_uiout, do_cleanups(), error(), frame_save_as_regcache(), gdbarch_num_pseudo_regs(), gdbarch_num_regs(), gdbarch_register_name(), get_regcache_arch(), get_selected_frame(), make_cleanup_regcache_xfree(), make_cleanup_ui_out_list_begin_end(), mi_cmd_data_list_changed_registers, register_changed_p(), regnum, and ui_out_field_int().
void mi_cmd_data_list_register_names (char * command, char ** argv, int argc)
Definition at line 951 of file mi-main.c.
References _, current_uiout, do_cleanups(), error(), gdbarch_num_pseudo_regs(), gdbarch_num_regs(), gdbarch_register_name(), get_current_arch(), make_cleanup_ui_out_list_begin_end(), mi_cmd_data_list_register_names, regnum, and ui_out_field_string().
void mi_cmd_data_list_register_values (char * command, char ** argv, int argc)
Definition at line 1115 of file mi-main.c.
References _, current_uiout, do_cleanups(), error(), gdbarch_num_pseudo_regs(), gdbarch_num_regs(), gdbarch_register_name(), get_frame_arch(), get_selected_frame(), int, make_cleanup_ui_out_list_begin_end(), mi_cmd_data_list_register_values, mi_getopt(), output_register(), and regnum.
void mi_cmd_data_read_memory (char * command, char ** argv, int argc)
Definition at line 1357 of file mi-main.c.
References _, target_ops::beneath, builtin_type::builtin_int16, builtin_type::builtin_int32, builtin_type::builtin_int64, builtin_type::builtin_int8, builtin_type(), current_target, current_uiout, do_cleanups(), error(), fputc_unfiltered(), get_current_arch(), get_formatted_print_options(), make_cleanup(), make_cleanup_ui_file_delete(), make_cleanup_ui_out_list_begin_end(), make_cleanup_ui_out_tuple_begin_end(), mem_fileopen(), mi_cmd_data_read_memory, mi_getopt(), null_cleanup(), offset, parse_and_eval_address(), print_scalar_formatted(), TARGET_OBJECT_MEMORY, target_read(), ui_file_rewind(), ui_out_field_core_addr(), ui_out_field_int(), ui_out_field_stream(), ui_out_field_string(), xcalloc(), and xfree().
void mi_cmd_data_read_memory_bytes (char * command, char ** argv, int argc)
Definition at line 1545 of file mi-main.c.
References _, memory_read_result::begin, target_ops::beneath, current_target, current_uiout, memory_read_result::data, do_cleanups(), memory_read_result::end, error(), free_memory_read_result_vector(), get_current_arch(), LONGEST, make_cleanup(), make_cleanup_ui_out_list_begin_end(), make_cleanup_ui_out_tuple_begin_end(), mi_cmd_data_read_memory_bytes, mi_getopt(), offset, p, parse_and_eval_address(), ui_out_field_core_addr(), ui_out_field_string(), VEC, VEC_iterate, VEC_length, xfree(), and xmalloc().
void mi_cmd_data_write_memory (char * command, char ** argv, int argc)
Definition at line 1644 of file mi-main.c.
References _, gdbarch::byte_order, do_cleanups(), error(), gdbarch_byte_order(), get_current_arch(), LONGEST, make_cleanup(), mi_cmd_data_write_memory, mi_getopt(), offset, parse_and_eval_address(), store_signed_integer(), write_memory_with_notification(), xfree(), and xmalloc().
void mi_cmd_data_write_memory_bytes (char * command, char ** argv, int argc)
Definition at line 1717 of file mi-main.c.
References _, do_cleanups(), error(), len, make_cleanup(), memcpy(), mi_cmd_data_write_memory_bytes, parse_and_eval_address(), write_memory_with_notification(), xfree(), and xmalloc().
void mi_cmd_data_write_register_values (char * command, char ** argv, int argc)
Definition at line 1248 of file mi-main.c.
References _, error(), gdbarch_num_pseudo_regs(), gdbarch_num_regs(), gdbarch_register_name(), get_current_regcache(), get_regcache_arch(), LONGEST, mi_cmd_data_write_register_values, parse_and_eval_address(), regcache_cooked_write_signed(), regnum, and target_has_registers.
void mi_cmd_enable_timings (char * command, char ** argv, int argc)
Definition at line 1781 of file mi-main.c.
References _, do_timings, error(), and mi_cmd_enable_timings.
void mi_cmd_exec_continue (char * command, char ** argv, int argc)
Definition at line 307 of file mi-main.c.
References exec_continue(), exec_reverse_continue(), and mi_cmd_exec_continue.
void mi_cmd_exec_finish (char * command, char ** argv, int argc)
Definition at line 172 of file mi-main.c.
References mi_cmd_exec_finish, and mi_execute_async_cli_command().
void mi_cmd_exec_interrupt (char * command, char ** argv, int argc)
Definition at line 337 of file mi-main.c.
References mi_parse::all, find_inferior_id(), interrupt_target_1(), interrupt_thread_callback(), iterate_over_threads(), mi_cmd_exec_interrupt, non_stop, inferior::pid, and mi_parse::thread_group.
void mi_cmd_exec_jump (char * args, char ** argv, int argc)
Definition at line 201 of file mi-main.c.
References mi_cmd_exec_jump, and mi_execute_async_cli_command().
void mi_cmd_exec_next (char * command, char ** argv, int argc)
Definition at line 132 of file mi-main.c.
References mi_cmd_exec_next, and mi_execute_async_cli_command().
void mi_cmd_exec_next_instruction (char * command, char ** argv, int argc)
Definition at line 142 of file mi-main.c.
References mi_cmd_exec_next_instruction, and mi_execute_async_cli_command().
void mi_cmd_exec_return (char * command, char ** argv, int argc)
Definition at line 182 of file mi-main.c.
References get_selected_frame(), LOC_AND_ADDRESS, mi_cmd_exec_return, print_stack_frame(), and return_command().
void mi_cmd_exec_run (char * command, char ** argv, int argc)
Definition at line 405 of file mi-main.c.
References _, mi_parse::all, do_cleanups(), error(), iterate_over_inferiors(), mi_cmd_exec_run, mi_execute_cli_command(), mi_getopt(), run_one_inferior(), save_current_space_and_thread(), and target_can_async_p.
void mi_cmd_exec_step (char * command, char ** argv, int argc)
Definition at line 152 of file mi-main.c.
References mi_cmd_exec_step, and mi_execute_async_cli_command().
void mi_cmd_exec_step_instruction (char * command, char ** argv, int argc)
Definition at line 162 of file mi-main.c.
References mi_cmd_exec_step_instruction, and mi_execute_async_cli_command().
static void mi_cmd_execute (struct mi_parse * parse) [static]
Definition at line 2121 of file mi-main.c.
References _, mi_parse::all, any_live_thread_of_process(), mi_parse::argc, mi_parse::args, mi_cli::args_p, mi_parse::argv, mi_cmd::argv_func, mi_cmd::cli, mi_parse::cmd, mi_cli::cmd, mi_parse::command, do_cleanups(), error(), error_stream(), find_inferior_id(), find_relative_frame(), find_thread_id(), fputs_unfiltered(), fputstr_unfiltered(), mi_parse::frame, get_current_frame(), is_exited(), make_cleanup_restore_integer(), make_cleanup_ui_file_delete(), mem_fileopen(), mi_execute_cli_command(), null_ptid, parse(), inferior::pid, prepare_execute_command(), inferior::pspace, thread_info::ptid, select_frame(), set_current_inferior(), set_current_program_space(), mi_cmd::suppress_notification, switch_to_thread(), mi_parse::thread, and mi_parse::thread_group.
Referenced by captured_mi_execute_command().
void mi_cmd_gdb_exit (char * command, char ** argv, int argc)
Definition at line 119 of file mi-main.c.
References current_token, current_uiout, fputs_unfiltered(), FROM_TTY, gdb_flush(), mi_cmd_gdb_exit, mi_out_put(), and quit_force().
void mi_cmd_list_features (char * command, char ** argv, int argc)
Definition at line 1804 of file mi-main.c.
References _, current_uiout, do_cleanups(), error(), gdb_python_initialized, make_cleanup_ui_out_list_begin_end(), mi_cmd_list_features, and ui_out_field_string().
void mi_cmd_list_target_features (char * command, char ** argv, int argc)
Definition at line 1832 of file mi-main.c.
References _, current_uiout, do_cleanups(), error(), make_cleanup_ui_out_list_begin_end(), mi_cmd_list_target_features, target_can_async_p, target_can_execute_reverse, and ui_out_field_string().
void mi_cmd_list_thread_groups (char * command, char ** argv, int argc)
Definition at line 849 of file mi-main.c.
References _, available, compare_positive_ints(), current_uiout, do_cleanups(), error(), find_inferior_id(), free_vector_of_ints(), arm-linux::inf, iterate_over_inferiors(), list_available_thread_groups(), make_cleanup(), make_cleanup_ui_out_list_begin_end(), mi_cmd_list_thread_groups, mi_getopt(), inferior::pid, print_one_inferior(), print_thread_info(), qsort, print_one_inferior_data::recurse, update_thread_list(), VEC, VEC_address, VEC_length, and VEC_safe_push.
void mi_cmd_remove_inferior (char * command, char ** argv, int argc)
Definition at line 1878 of file mi-main.c.
References _, any_thread_of_process(), current_inferior(), delete_inferior_1(), error(), find_inferior_id(), get_other_inferior(), arm-linux::inf, iterate_over_inferiors(), mi_cmd_remove_inferior, null_ptid, inferior::pid, inferior::pspace, thread_info::ptid, set_current_inferior(), set_current_program_space(), and switch_to_thread().
void mi_cmd_target_detach (char * command, char ** argv, int argc)
Definition at line 472 of file mi-main.c.
References _, detach_command(), error(), find_inferior_id(), find_thread_of_process(), arm-linux::inf, iterate_over_threads(), mi_cmd_target_detach, inferior::pid, thread_info::ptid, and switch_to_thread().
void mi_cmd_thread_info (char * command, char ** argv, int argc)
Definition at line 556 of file mi-main.c.
References _, current_uiout, error(), mi_cmd_thread_info, and print_thread_info().
void mi_cmd_thread_list_ids (char * command, char ** argv, int argc)
Definition at line 538 of file mi-main.c.
References _, current_uiout, error(), gdb_list_thread_ids(), GDB_RC_FAIL, make_cleanup(), mi_cmd_thread_list_ids, and xfree().
void mi_cmd_thread_select (char * command, char ** argv, int argc)
Definition at line 520 of file mi-main.c.
References _, current_uiout, error(), GDB_RC_FAIL, gdb_thread_select(), make_cleanup(), mi_cmd_thread_select, and xfree().
void mi_cmd_trace_define_variable (char * command, char ** argv, int argc)
Definition at line 2419 of file mi-main.c.
References _, create_trace_state_variable(), error(), find_trace_state_variable(), trace_state_variable::initial_value, LONGEST, mi_cmd_trace_define_variable, name, parse_and_eval(), validate_trace_state_variable_name(), and value_as_long().
void mi_cmd_trace_find (char * command, char ** argv, int argc)
Definition at line 2455 of file mi-main.c.
References _, current_trace_status(), DECODE_LINE_FUNFIRSTLINE, decode_line_with_current_source(), do_cleanups(), error(), find_line_pc_range(), get_selected_frame(), get_traceframe_number(), has_stack_frames(), symtab_and_line::line, LOC_AND_ADDRESS, make_cleanup(), mi_cmd_trace_find, parse_and_eval_address(), print_stack_frame(), symtabs_and_lines::sals, symtab_and_line::symtab, tfind_1(), tfind_number, tfind_outside, tfind_pc, tfind_range, tfind_tp, and xfree().
void mi_cmd_trace_frame_collected (char * command, char ** argv, int argc)
Definition at line 2678 of file mi-main.c.
References _, current_uiout, do_cleanups(), encode_actions_and_make_cleanup(), error(), find_trace_state_variable_by_number(), free_current_contents(), gdbarch_num_pseudo_regs(), gdbarch_num_regs(), gdbarch_register_name(), get_current_frame(), get_frame_arch(), get_selected_frame(), get_traceframe_info(), get_traceframe_location(), mem_range::length, arm-linux::m, make_cleanup(), make_cleanup_restore_current_thread(), make_cleanup_ui_out_list_begin_end(), make_cleanup_ui_out_tuple_begin_end(), mi_cmd_trace_frame_collected, mi_getopt(), mi_parse_print_values(), trace_state_variable::name, trace_state_variable::number, output_register(), p, PRINT_ALL_VALUES, print_variable_or_computed(), regnum, select_frame(), mem_range::start, target_gdbarch(), target_get_trace_state_variable_value, target_read_memory(), traceframe_available_memory(), ui_out_field_core_addr(), ui_out_field_int(), ui_out_field_skip(), ui_out_field_string(), trace_state_variable::value, trace_state_variable::value_known, VEC, VEC_cleanup, VEC_iterate, xfree(), xmalloc(), and xrealloc().
void mi_cmd_trace_list_variables (char * command, char ** argv, int argc)
Definition at line 2446 of file mi-main.c.
References _, error(), mi_cmd_trace_list_variables, and tvariables_info_1().
void mi_cmd_trace_save (char * command, char ** argv, int argc)
Definition at line 2539 of file mi-main.c.
References mi_cmd_trace_save, mi_getopt(), trace_save_ctf(), and trace_save_tfile().
void mi_cmd_trace_start (char * command, char ** argv, int argc)
Definition at line 2584 of file mi-main.c.
References mi_cmd_trace_start, and start_tracing().
void mi_cmd_trace_status (char * command, char ** argv, int argc)
Definition at line 2590 of file mi-main.c.
References mi_cmd_trace_status, and trace_status_mi().
void mi_cmd_trace_stop (char * command, char ** argv, int argc)
Definition at line 2596 of file mi-main.c.
References mi_cmd_trace_stop, stop_tracing(), and trace_status_mi().
void mi_execute_async_cli_command (char * cli_command, char ** argv, int argc) [static]
Definition at line 2250 of file mi-main.c.
References do_cleanups(), execute_command(), make_cleanup(), run, target_can_async_p, xfree(), and xstrprintf().
Referenced by mi_cmd_exec_finish(), mi_cmd_exec_jump(), mi_cmd_exec_next(), mi_cmd_exec_next_instruction(), mi_cmd_exec_step(), and mi_cmd_exec_step_instruction().
void mi_execute_cli_command (const char * cmd, int args_p, const char * args) [static]
Definition at line 2227 of file mi-main.c.
References do_cleanups(), execute_command(), fprintf_unfiltered(), gdb_stdout, make_cleanup(), mi_debug_p, run, xfree(), and xstrprintf().
Referenced by mi_cmd_exec_run(), mi_cmd_execute(), and run_one_inferior().
void mi_execute_command (const char * cmd, int from_tty)
Definition at line 2027 of file mi-main.c.
References bpstat_do_actions(), captured_mi_execute_command(), mi_parse::cmd_start, mi_parse::command, current_uiout, do_timings, mi_interp::event_channel, fprintf_unfiltered(), gdb_flush(), inferior_ptid, inferior_thread(), interp_ui_out(), mi_out_rewind(), mi_parse(), mi_parse_free(), mi_print_exception(), null_ptid, thread_info::num, ptid_equal(), quit_force(), gdb_exception::reason, RETURN_MASK_ALL, target_log_command, target_terminal_ours, mi_parse::thread, thread_count(), timestamp(), mi_parse::token, token, top_level_interpreter(), top_level_interpreter_data(), TRY_CATCH, ui_out_is_mi_like_p(), xfree(), and xmalloc().
Referenced by mi_execute_command_wrapper().
void mi_load_progress (const char * section_name, unsigned long sent_so_far, unsigned long total_section, unsigned long total_sent, unsigned long grand_total)
Definition at line 2269 of file mi-main.c.
References current_interp_named_p(), current_token, current_uiout, do_cleanups(), fputs_unfiltered(), gdb_flush(), INTERP_MI, INTERP_MI1, INTERP_MI2, INTERP_MI3, L, make_cleanup_ui_out_tuple_begin_end(), mi_out_new(), mi_out_put(), ui_out_field_int(), ui_out_field_string(), and xfree().
Referenced by mi_interpreter_resume().
static void mi_print_exception (const char * token, struct gdb_exception exception) [static]
Definition at line 2015 of file mi-main.c.
References fputs_unfiltered(), fputstr_unfiltered(), and gdb_exception::message.
Referenced by mi_execute_command().
void mi_print_timing_maybe (void)
Definition at line 2392 of file mi-main.c.
References do_timings, and print_diff_now().
Referenced by captured_mi_execute_command(), and mi_on_normal_stop().
static void output_cores (struct ui_out * uiout, const char * field_name, const char * xcores) [static]
Definition at line 671 of file mi-main.c.
References do_cleanups(), make_cleanup(), make_cleanup_ui_out_list_begin_end(), p, strtok(), ui_out_field_string(), and xfree().
Referenced by list_available_thread_groups().
static void output_register (struct frame_info * frame, int regnum, int format, int skip_unavailable) [static]
Definition at line 1207 of file mi-main.c.
References current_language, current_uiout, value_print_options::deref_ref, do_cleanups(), get_formatted_print_options(), get_frame_arch(), make_cleanup_ui_file_delete(), make_cleanup_ui_out_tuple_begin_end(), mem_fileopen(), ui_out_field_int(), ui_out_field_stream(), val_print(), value_contents_for_printing(), value_embedded_offset(), value_entirely_available(), value_of_register(), and value_type().
Referenced by mi_cmd_data_list_register_values(), and mi_cmd_trace_frame_collected().
static void print_diff (struct mi_timestamp * start, struct mi_timestamp * end) [static]
Definition at line 2408 of file mi-main.c.
References fprintf_unfiltered(), mi_timestamp::stime, timeval_diff(), mi_timestamp::utime, and mi_timestamp::wallclock.
Referenced by print_diff_now().
static void print_diff_now (struct mi_timestamp * start) [static]
Definition at line 2383 of file mi-main.c.
References print_diff(), and timestamp().
Referenced by mi_print_timing_maybe().
static int print_one_inferior (struct inferior * inferior, void * xdata) [static]
Definition at line 605 of file mi-main.c.
References collect_cores(), compare_positive_ints(), current_uiout, do_cleanups(), iterate_over_threads(), make_cleanup_ui_out_list_begin_end(), make_cleanup_ui_out_tuple_begin_end(), inferior::num, inferior::pid, collect_cores_data::pid, print_thread_info(), inferior::pspace, program_space::pspace_exec_filename, qsort, print_one_inferior_data::recurse, ui_out_field_fmt(), ui_out_field_int(), ui_out_field_string(), unique(), VEC_address, VEC_empty, and VEC_length.
Referenced by mi_cmd_list_thread_groups().
static void print_variable_or_computed (char * expression, enum print_values values) [static]
Definition at line 2616 of file mi-main.c.
References check_typedef(), common_val_print(), current_language, current_uiout, value_print_options::deref_ref, do_cleanups(), evaluate_expression(), evaluate_type(), free_current_contents(), get_no_prettyformat_print_options(), make_cleanup(), make_cleanup_ui_file_delete(), make_cleanup_ui_out_tuple_begin_end(), mem_fileopen(), parse_expression(), PRINT_ALL_VALUES, PRINT_NO_VALUES, PRINT_SIMPLE_VALUES, type, TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_STRUCT, TYPE_CODE_UNION, type_print(), ui_out_field_stream(), ui_out_field_string(), and value_type().
Referenced by mi_cmd_trace_frame_collected().
static void proceed_thread (struct thread_info * thread, int pid) [static]
Definition at line 208 of file mi-main.c.
References clear_proceed_status(), is_stopped(), proceed(), thread_info::ptid, ptid_get_pid(), and switch_to_thread().
Referenced by proceed_thread_callback().
static int proceed_thread_callback (struct thread_info * thread, void * arg) [static]
Definition at line 222 of file mi-main.c.
References proceed_thread().
Referenced by exec_continue().
static int register_changed_p (int regnum, struct regcache * prev_regs, struct regcache * this_regs) [static]
Definition at line 1078 of file mi-main.c.
References get_regcache_arch(), MAX_REGISTER_SIZE, memcmp(), REG_VALID, regcache_cooked_read(), and register_size().
Referenced by mi_cmd_data_list_changed_registers().
static int run_one_inferior (struct inferior * inf, void * arg) [static]
Definition at line 375 of file mi-main.c.
References _, any_thread_of_process(), error(), inferior_ptid, mi_execute_cli_command(), null_ptid, inferior::pid, inferior::pspace, thread_info::ptid, ptid_get_pid(), set_current_inferior(), set_current_program_space(), switch_to_thread(), and target_can_async_p.
Referenced by mi_cmd_exec_run().
static int splay_tree_int_comparator (splay_tree_key xa, splay_tree_key xb) [static]
Definition at line 709 of file mi-main.c.
Referenced by list_available_thread_groups().
static void timestamp (struct mi_timestamp * tv) [static]
Definition at line 2361 of file mi-main.c.
References L, mi_timestamp::stime, mi_timestamp::utime, and mi_timestamp::wallclock.
Referenced by mi_execute_command(), print_diff_now(), and vfprintf_unfiltered().
static long timeval_diff (struct timeval start, struct timeval end) [static]
Definition at line 2401 of file mi-main.c.
References L.
Referenced by print_diff().
static int* unique (int * b, int * e) [static]
Definition at line 588 of file mi-main.c.
Referenced by print_one_inferior().
Variable Documentation
struct mi_timestamp* current_command_ts [static]
Definition at line 81 of file mi-main.c.
struct mi_parse* current_context [static]
Definition at line 89 of file mi-main.c.
char* current_token
Definition at line 85 of file mi-main.c.
Referenced by captured_mi_execute_command(), mi_cmd_gdb_exit(), mi_load_progress(), and mi_on_resume().
int do_timings = 0 [static]
Definition at line 83 of file mi-main.c.
Referenced by captured_mi_execute_command(), mi_cmd_enable_timings(), mi_execute_command(), and mi_print_timing_maybe().
int mi_debug_p
Definition at line 75 of file mi-main.c.
Referenced by captured_mi_execute_command(), and mi_execute_cli_command().
int mi_proceeded
Definition at line 95 of file mi-main.c.
Referenced by captured_mi_execute_command(), mi_about_to_proceed(), and mi_on_resume().
struct ui_file* raw_stdout
Definition at line 77 of file mi-main.c.
Referenced by mi_command_loop(), mi_execute_command_input_handler(), mi_interpreter_init(), mi_on_normal_stop(), mi_on_resume(), mi_output_running_pid(), and mi_set_logging().
int running_result_record_printed = 1
Definition at line 91 of file mi-main.c.
Referenced by captured_mi_execute_command(), and mi_on_resume().