GDB (xrefs): /home/stan/gdb/src/gdb/mi/mi-main.h File Reference
/home/stan/gdb/src/gdb/mi/mi-main.h File Reference
Classes
struct mi_suppress_notification
Functions
void mi_load_progress (const char *section_name, unsigned long sent_so_far, unsigned long total_section, unsigned long total_sent, unsigned long grand_total)
void mi_print_timing_maybe (void)
Variables
char * current_token
int running_result_record_printed
int mi_proceeded
struct mi_suppress_notification mi_suppress_notification
Function Documentation
void mi_load_progress (const char * section_name, unsigned long sent_so_far, unsigned long total_section, unsigned long total_sent, unsigned long grand_total)
Definition at line 2269 of file mi-main.c.
References current_interp_named_p(), current_token, current_uiout, do_cleanups(), fputs_unfiltered(), gdb_flush(), INTERP_MI, INTERP_MI1, INTERP_MI2, INTERP_MI3, L, make_cleanup_ui_out_tuple_begin_end(), mi_out_new(), mi_out_put(), ui_out_field_int(), ui_out_field_string(), and xfree().
Referenced by mi_interpreter_resume().
void mi_print_timing_maybe (void)
Definition at line 2392 of file mi-main.c.
References do_timings, and print_diff_now().
Referenced by captured_mi_execute_command(), and mi_on_normal_stop().
Variable Documentation
char* current_token
Definition at line 85 of file mi-main.c.
Referenced by captured_mi_execute_command(), mi_cmd_gdb_exit(), mi_load_progress(), and mi_on_resume().
int mi_proceeded
Definition at line 95 of file mi-main.c.
Referenced by captured_mi_execute_command(), mi_about_to_proceed(), and mi_on_resume().
struct mi_suppress_notification mi_suppress_notification
Definition at line 501 of file mi-interp.c.
int running_result_record_printed
Definition at line 91 of file mi-main.c.
Referenced by captured_mi_execute_command(), and mi_on_resume().