GDB (xrefs): /home/stan/gdb/src/gdb/mi/mi-out.h File Reference
/home/stan/gdb/src/gdb/mi/mi-out.h File Reference
Functions
struct ui_out * mi_out_new (int mi_version)
void mi_out_put (struct ui_out *uiout, struct ui_file *stream)
void mi_out_rewind (struct ui_out *uiout)
void mi_out_buffered (struct ui_out *uiout, char *string)
int mi_version (struct ui_out *uiout)
Function Documentation
void mi_out_buffered (struct ui_out * uiout, char * string)
Definition at line 363 of file mi-out.c.
References ui_out_data::buffer, fprintf_unfiltered(), and ui_out_data().
struct ui_out* mi_out_new (int mi_version) [read]
Definition at line 410 of file mi-out.c.
References ui_out_data::buffer, ui_out::data, flags, mem_fileopen(), ui_out_data::mi_version, mi_version(), ui_out_data::suppress_field_separator, ui_out_data::suppress_output, ui_out_new(), and XMALLOC.
Referenced by mi_interpreter_init(), and mi_load_progress().
void mi_out_put (struct ui_out * uiout, struct ui_file * stream)
Definition at line 389 of file mi-out.c.
References ui_out_data::buffer, do_write(), ui_file_put(), ui_file_rewind(), and ui_out_data().
Referenced by captured_mi_execute_command(), mi_cmd_gdb_exit(), mi_load_progress(), and mi_on_normal_stop().
void mi_out_rewind (struct ui_out * uiout)
Definition at line 373 of file mi-out.c.
References ui_out_data::buffer, ui_file_rewind(), and ui_out_data().
Referenced by captured_mi_execute_command(), mi_execute_command(), and mi_on_normal_stop().
int mi_version (struct ui_out * uiout)
Definition at line 400 of file mi-out.c.
References ui_out_data::mi_version, and ui_out_data().
Referenced by mi_cmd_env_dir(), mi_cmd_env_path(), mi_cmd_env_pwd(), mi_cmd_var_list_children(), mi_cmd_var_update(), mi_interpreter_init(), mi_out_new(), and varobj_update_one().