GDB (xrefs): /home/stan/gdb/src/gdb/mi/mi-out.c File Reference
/home/stan/gdb/src/gdb/mi/mi-out.c File Reference
#include "defs.h"
#include "ui-out.h"
#include "mi-out.h"
Classes
struct ui_out_data
Typedefs
typedef struct ui_out_data mi_out_data
Functions
static void mi_table_begin (struct ui_out *uiout, int nbrofcols, int nr_rows, const char *tblid)
static void mi_table_body (struct ui_out *uiout)
static void mi_table_end (struct ui_out *uiout)
static void mi_table_header (struct ui_out *uiout, int width, enum ui_align alig, const char *col_name, const char *colhdr)
static void mi_begin (struct ui_out *uiout, enum ui_out_type type, int level, const char *id)
static void mi_end (struct ui_out *uiout, enum ui_out_type type, int level)
static void mi_field_int (struct ui_out *uiout, int fldno, int width, enum ui_align alig, const char *fldname, int value)
static void mi_field_skip (struct ui_out *uiout, int fldno, int width, enum ui_align alig, const char *fldname)
static void mi_field_string (struct ui_out *uiout, int fldno, int width, enum ui_align alig, const char *fldname, const char *string)
static void mi_field_fmt (struct ui_out *uiout, int fldno, int width, enum ui_align align, const char *fldname, const char *format, va_list args) ATTRIBUTE_PRINTF(6
static void static void mi_spaces (struct ui_out *uiout, int numspaces)
static void mi_text (struct ui_out *uiout, const char *string)
static void mi_message (struct ui_out *uiout, int verbosity, const char *format, va_list args) ATTRIBUTE_PRINTF(3
static void static void mi_wrap_hint (struct ui_out *uiout, char *identstring)
static void mi_flush (struct ui_out *uiout)
static int mi_redirect (struct ui_out *uiout, struct ui_file *outstream)
void _initialize_mi_out (void)
static void field_separator (struct ui_out *uiout)
static void mi_open (struct ui_out *uiout, const char *name, enum ui_out_type type)
static void mi_close (struct ui_out *uiout, enum ui_out_type type)
void mi_out_buffered (struct ui_out *uiout, char *string)
void mi_out_rewind (struct ui_out *uiout)
static void do_write (void *data, const char *buffer, long length_buffer)
void mi_out_put (struct ui_out *uiout, struct ui_file *stream)
int mi_version (struct ui_out *uiout)
struct ui_out * mi_out_new (int mi_version)
Variables
struct ui_out_impl mi_ui_out_impl
Typedef Documentation
typedef struct ui_out_data mi_out_data
Definition at line 34 of file mi-out.c.
Function Documentation
void _initialize_mi_out (void)
static void do_write (void * data, const char * buffer, long length_buffer) [static]
Definition at line 383 of file mi-out.c.
References ui_file_write().
Referenced by mi_out_put().
static void field_separator (struct ui_out * uiout) [static]
Definition at line 309 of file mi-out.c.
References ui_out_data::buffer, fputc_unfiltered(), ui_out_data::suppress_field_separator, and ui_out_data().
Referenced by mi_field_fmt(), mi_field_string(), and mi_open().
void mi_begin (struct ui_out * uiout, enum ui_out_type type, int level, const char * id) [static]
Definition at line 165 of file mi-out.c.
References mi_open(), ui_out_data::suppress_output, and ui_out_data().
static void mi_close (struct ui_out * uiout, enum ui_out_type type) [static]
Definition at line 342 of file mi-out.c.
References _, ui_out_data::buffer, fputc_unfiltered(), internal_error(), ui_out_data::suppress_field_separator, ui_out_data(), ui_out_type_list, and ui_out_type_tuple.
Referenced by mi_end(), mi_table_body(), mi_table_end(), and mi_table_header().
void mi_end (struct ui_out * uiout, enum ui_out_type type, int level) [static]
Definition at line 179 of file mi-out.c.
References mi_close(), ui_out_data::suppress_output, and ui_out_data().
void mi_field_fmt (struct ui_out * uiout, int fldno, int width, enum ui_align align, const char * fldname, const char * format, va_list args) [static]
Definition at line 237 of file mi-out.c.
References ui_out_data::buffer, field_separator(), fprintf_unfiltered(), fputs_unfiltered(), ui_out_data::suppress_output, ui_out_data(), and vfprintf_unfiltered().
static void mi_field_int (struct ui_out * uiout, int fldno, int width, enum ui_align alig, const char * fldname, int value) [static]
Definition at line 192 of file mi-out.c.
References mi_field_string(), ui_out_data::suppress_output, ui_out_data(), and xsnprintf().
Referenced by mi_table_begin(), and mi_table_header().
void mi_field_skip (struct ui_out * uiout, int fldno, int width, enum ui_align alig, const char * fldname) [static]
Definition at line 208 of file mi-out.c.
void mi_field_string (struct ui_out * uiout, int fldno, int width, enum ui_align alig, const char * fldname, const char * string) [static]
Definition at line 217 of file mi-out.c.
References ui_out_data::buffer, field_separator(), fprintf_unfiltered(), fputstr_unfiltered(), ui_out_data::suppress_output, and ui_out_data().
Referenced by mi_field_int(), and mi_table_header().
void mi_flush (struct ui_out * uiout) [static]
Definition at line 278 of file mi-out.c.
References ui_out_data::buffer, gdb_flush(), and ui_out_data().
void mi_message (struct ui_out * uiout, int verbosity, const char * format, va_list args) [static]
Definition at line 266 of file mi-out.c.
static void mi_open (struct ui_out * uiout, const char * name, enum ui_out_type type) [static]
Definition at line 320 of file mi-out.c.
References _, ui_out_data::buffer, field_separator(), fprintf_unfiltered(), fputc_unfiltered(), internal_error(), ui_out_data::suppress_field_separator, ui_out_data(), ui_out_type_list, and ui_out_type_tuple.
Referenced by mi_begin(), mi_table_begin(), mi_table_body(), and mi_table_header().
void mi_out_buffered (struct ui_out * uiout, char * string)
Definition at line 363 of file mi-out.c.
References ui_out_data::buffer, fprintf_unfiltered(), and ui_out_data().
struct ui_out* mi_out_new (int mi_version) [read]
Definition at line 410 of file mi-out.c.
References ui_out_data::buffer, ui_out::data, flags, mem_fileopen(), ui_out_data::mi_version, mi_version(), ui_out_data::suppress_field_separator, ui_out_data::suppress_output, ui_out_new(), and XMALLOC.
Referenced by mi_interpreter_init(), and mi_load_progress().
void mi_out_put (struct ui_out * uiout, struct ui_file * stream)
Definition at line 389 of file mi-out.c.
References ui_out_data::buffer, do_write(), ui_file_put(), ui_file_rewind(), and ui_out_data().
Referenced by captured_mi_execute_command(), mi_cmd_gdb_exit(), mi_load_progress(), and mi_on_normal_stop().
void mi_out_rewind (struct ui_out * uiout)
Definition at line 373 of file mi-out.c.
References ui_out_data::buffer, ui_file_rewind(), and ui_out_data().
Referenced by captured_mi_execute_command(), mi_execute_command(), and mi_on_normal_stop().
int mi_redirect (struct ui_out * uiout, struct ui_file * outstream) [static]
Definition at line 286 of file mi-out.c.
References ui_out_data::buffer, ui_out_data::original_buffer, and ui_out_data().
void mi_spaces (struct ui_out * uiout, int numspaces) [static]
Definition at line 256 of file mi-out.c.
void mi_table_begin (struct ui_out * uiout, int nbrofcols, int nr_rows, const char * tblid) [static]
Definition at line 106 of file mi-out.c.
References mi_field_int(), mi_open(), ui_out_type_list, and ui_out_type_tuple.
void mi_table_body (struct ui_out * uiout) [static]
Definition at line 120 of file mi-out.c.
References mi_close(), mi_open(), ui_out_data::suppress_output, ui_out_data(), and ui_out_type_list.
void mi_table_end (struct ui_out * uiout) [static]
Definition at line 134 of file mi-out.c.
References mi_close(), ui_out_data::suppress_output, ui_out_data(), ui_out_type_list, and ui_out_type_tuple.
void mi_table_header (struct ui_out * uiout, int width, enum ui_align alig, const char * col_name, const char * colhdr) [static]
Definition at line 146 of file mi-out.c.
References mi_close(), mi_field_int(), mi_field_string(), mi_open(), ui_out_data::suppress_output, ui_out_data(), and ui_out_type_tuple.
void mi_text (struct ui_out * uiout, const char * string) [static]
Definition at line 261 of file mi-out.c.
int mi_version (struct ui_out * uiout)
Definition at line 400 of file mi-out.c.
References ui_out_data::mi_version, and ui_out_data().
Referenced by mi_cmd_env_dir(), mi_cmd_env_path(), mi_cmd_env_pwd(), mi_cmd_var_list_children(), mi_cmd_var_update(), mi_interpreter_init(), mi_out_new(), and varobj_update_one().
void mi_wrap_hint (struct ui_out * uiout, char * identstring) [static]
Definition at line 272 of file mi-out.c.
References wrap_here().
Variable Documentation
struct ui_out_impl mi_ui_out_impl
Initial value:
{
  mi_table_begin,
  mi_table_body,
  mi_table_end,
  mi_table_header,
  mi_begin,
  mi_end,
  mi_field_int,
  mi_field_skip,
  mi_field_string,
  mi_field_fmt,
  mi_spaces,
  mi_text,
  mi_message,
  mi_wrap_hint,
  mi_flush,
  mi_redirect,
  0,
  1,
}
Definition at line 73 of file mi-out.c.