GDB (xrefs): /home/stan/gdb/src/gdb/mi/mi-parse.h File Reference
/home/stan/gdb/src/gdb/mi/mi-parse.h File Reference
#include <sys/time.h>
Classes
struct mi_timestamp
struct mi_parse
Enumerations
enum mi_command_type { MI_COMMAND, CLI_COMMAND }
Functions
struct mi_parse * mi_parse (const char *cmd, char **token)
void mi_parse_free (struct mi_parse *cmd)
enum print_values mi_parse_print_values (const char *name)
Enumeration Type Documentation
enum mi_command_type
Enumerator:
MI_COMMAND
CLI_COMMAND
Definition at line 34 of file mi-parse.h.
Function Documentation
struct mi_parse* mi_parse (const char * cmd, char ** token) [read]
Definition at line 236 of file mi-parse.c.
References _, mi_parse::all, mi_parse::args, mi_parse::argv, mi_cmd::argv_func, mi_cmd::cli, CLI_COMMAND, mi_parse::cmd, mi_cli::cmd, mi_parse::command, discard_cleanups(), error(), mi_parse::frame, make_cleanup(), memcpy(), memset(), MI_COMMAND, mi_lookup(), mi_parse_argv(), mi_parse_cleanup(), mi_parse::op, parse(), skip_spaces_const(), mi_parse::thread, mi_parse::thread_group, xmalloc(), and XMALLOC.
Referenced by mi_execute_command().
void mi_parse_free (struct mi_parse * cmd)
Definition at line 212 of file mi-parse.c.
References mi_parse::args, mi_parse::argv, mi_parse::command, mi_parse::token, and xfree().
Referenced by mi_execute_command(), and mi_parse_cleanup().
enum print_values mi_parse_print_values (const char * name)
Definition at line 382 of file mi-parse.c.
References _, error(), mi_all_values, mi_no_values, mi_simple_values, PRINT_ALL_VALUES, PRINT_NO_VALUES, and PRINT_SIMPLE_VALUES.
Referenced by mi_cmd_stack_list_args(), mi_cmd_stack_list_locals(), mi_cmd_stack_list_variables(), mi_cmd_trace_frame_collected(), mi_cmd_var_list_children(), and mi_cmd_var_update().