GDB (xrefs): /home/stan/gdb/src/gdb/mi/mi-symbol-cmds.c File Reference
/home/stan/gdb/src/gdb/mi/mi-symbol-cmds.c File Reference
#include "defs.h"
#include "mi-cmds.h"
#include "symtab.h"
#include "objfiles.h"
#include "ui-out.h"
Functions
void mi_cmd_symbol_list_lines (char *command, char **argv, int argc)
Function Documentation
void mi_cmd_symbol_list_lines (char * command, char ** argv, int argc)
Definition at line 30 of file mi-symbol-cmds.c.
References _, current_uiout, do_cleanups(), error(), get_objfile_arch(), line, LINETABLE, lookup_symtab(), make_cleanup_ui_out_list_begin_end(), make_cleanup_ui_out_tuple_begin_end(), mi_cmd_symbol_list_lines, symtab::objfile, ui_out_field_core_addr(), and ui_out_field_int().