GDB (xrefs): /home/stan/gdb/src/gdb/microblaze-rom.c File Reference
/home/stan/gdb/src/gdb/microblaze-rom.c File Reference
#include "defs.h"
#include "gdbcore.h"
#include "target.h"
#include "monitor.h"
#include "gdb_string.h"
#include "serial.h"
#include "regcache.h"
Functions
void _initialize_picobug_rom (void)
static void picobug_open (char *args, int from_tty)
static int picobug_dumpregs (struct regcache *regcache)
static void init_picobug_cmds (void)
Variables
static char * picobug_inits []
static struct target_ops picobug_ops
static struct monitor_ops picobug_cmds
static char * picobug_regnames []
Function Documentation
void _initialize_picobug_rom (void)
Definition at line 179 of file microblaze-rom.c.
References add_target(), init_monitor_ops(), init_picobug_cmds(), picobug_open(), picobug_ops, target_ops::to_doc, target_ops::to_longname, target_ops::to_open, and target_ops::to_shortname.
static void init_picobug_cmds (void) [static]
Definition at line 146 of file microblaze-rom.c.
References monitor_ops::clr_all_break, monitor_ops::clr_break, regrw_cmd::cmd, memrw_cmd::cmdb, memrw_cmd::cmdl, memrw_cmd::cmdw, monitor_ops::cont, monitor_ops::dump_registers, monitor_ops::dumpregs, monitor_ops::flags, monitor_ops::getmem, monitor_ops::getreg, monitor_ops::init, monitor_ops::line_term, monitor_ops::load, monitor_ops::magic, MO_CLR_BREAK_USES_ADDR, MO_GETMEM_NEEDS_RANGE, MO_PRINT_PROGRAM_OUTPUT, MONITOR_OPS_MAGIC, monitor_ops::num_breakpoints, picobug_cmds, picobug_dumpregs(), picobug_inits, picobug_ops, picobug_regnames, monitor_ops::prompt, monitor_ops::regnames, memrw_cmd::resp_delim, regrw_cmd::resp_delim, SERIAL_1_STOPBITS, monitor_ops::set_break, monitor_ops::setmem, monitor_ops::setreg, monitor_ops::step, monitor_ops::stopbits, and monitor_ops::target.
Referenced by _initialize_picobug_rom().
static int picobug_dumpregs (struct regcache * regcache) [static]
Definition at line 69 of file microblaze-rom.c.
References monitor_ops::dump_registers, gdbarch_num_regs(), get_regcache_arch(), monitor_expect_prompt(), monitor_printf(), monitor_supply_register(), name, p, picobug_cmds, picobug_regnames, strchr(), and strtok().
Referenced by init_picobug_cmds().
static void picobug_open (char * args, int from_tty) [static]
Definition at line 52 of file microblaze-rom.c.
References monitor_open(), and picobug_cmds.
Referenced by _initialize_picobug_rom().
Variable Documentation
struct monitor_ops picobug_cmds [static]
Definition at line 34 of file microblaze-rom.c.
Referenced by init_picobug_cmds(), picobug_dumpregs(), and picobug_open().
char* picobug_inits[] [static]
Initial value:
{"\r", NULL}
Definition at line 30 of file microblaze-rom.c.
Referenced by init_picobug_cmds().
struct target_ops picobug_ops [static]
Definition at line 33 of file microblaze-rom.c.
Referenced by _initialize_picobug_rom(), and init_picobug_cmds().
char* picobug_regnames[] [static]
Initial value:
 {
  "r0",   "r1",   "r2",   "r3",   "r4",   "r5",   "r6",   "r7",
  "r8",   "r9",   "r10",  "r11",  "r12",  "r13",  "r14",  "r15",
  0,      0,      0,      0,      0,      0,      0,      0,
  0,      0,      0,      0,      0,      0,      0,      0,
  "psr",  "vbr",  "epsr", "fpsr", "epc",  "fpc",  0,      "ss1",
  "ss2",  "ss3",  "ss4",  0,      0,      0,      0,      0,
  0,      0,      0,      0,      0,      0,      0,      0,
  0,      0,      0,      0,      0,      0,      0,      0,
  "pc" }
Definition at line 38 of file microblaze-rom.c.
Referenced by init_picobug_cmds(), and picobug_dumpregs().