GDB (xrefs): /home/stan/gdb/src/gdb/mingw-hdep.c File Reference
/home/stan/gdb/src/gdb/mingw-hdep.c File Reference
#include "defs.h"
#include "main.h"
#include "serial.h"
#include "event-loop.h"
#include "gdb_assert.h"
#include "gdb_select.h"
#include "gdb_string.h"
#include "readline/readline.h"
#include <windows.h>
Functions
char * safe_strerror (int errnum)
char * windows_get_absolute_argv0 (const char *argv0)
int gdb_select (int n, fd_set *readfds, fd_set *writefds, fd_set *exceptfds, struct timeval *timeout)
void gdb_call_async_signal_handler (struct async_signal_handler *handler, int immediate_p)
void _initialize_mingw_hdep (void)
Variables
static HANDLE sigint_event
struct async_signal_handler * sigint_handler
initialize_file_ftype _initialize_mingw_hdep
Function Documentation
void _initialize_mingw_hdep (void)
Definition at line 272 of file mingw-hdep.c.
References _initialize_mingw_hdep, and sigint_event.
void gdb_call_async_signal_handler (struct async_signal_handler * handler, int immediate_p)
Definition at line 255 of file mingw-hdep.c.
References mark_async_signal_handler(), and sigint_event.
int gdb_select (int n, fd_set * readfds, fd_set * writefds, fd_set * exceptfds, struct timeval * timeout)
Definition at line 105 of file mingw-hdep.c.
References call_async_signal_handler(), serial::fd, gdb_assert, read(), serial_for_fd(), and sigint_event.
char* safe_strerror (int)
A host-specific version of strerror.
This is defined in *-hdep.c, e.g., posix-hdep.c.
Definition at line 50 of file mingw-hdep.c.
Referenced by amd64_linux_disable_btrace(), amd64_linux_enable_btrace(), captured_main(), close_with_trace(), create_tty_session(), ctf_save_fseek(), ctf_save_write(), ctf_save_write_metadata(), ctf_start(), darwin_attach(), darwin_decode_message(), darwin_detach(), darwin_kill_inferior(), darwin_pre_ptrace(), darwin_ptrace(), darwin_stop_inferior(), detach_callback(), displaced_step_prepare(), do_attach(), dsbt_current_sos(), fetch_register(), fork_inferior(), frv_current_sos(), gnu_read_inferior(), gnu_wait(), go32_terminal_inferior(), go32_terminal_ours(), hardwire_raw(), hppa_hpux_fetch_register(), hppa_hpux_store_register(), i386_linux_disable_btrace(), i386_linux_enable_btrace(), ia64_linux_fetch_register(), ia64_linux_store_register(), inf_continue(), inf_ptrace_fetch_register(), inf_ptrace_store_register(), inf_ptrace_wait(), inf_set_pid(), inf_set_traced(), inf_signal(), inf_startup(), info_port_rights(), ioctl_with_trace(), irix_current_sos(), irix_open_symbol_file_object(), kill_callback(), lin_lwp_attach_lwp(), linux_nat_create_inferior(), linux_nat_wait_1(), linux_thread_alive(), make_proc(), mi_cmd_env_pwd(), mips_readchar(), mips_receive_packet(), monitor_write(), new_tty(), open_symbol_file_object(), open_with_trace(), perror_string(), pipe_windows_open(), print_sys_errmsg(), proc_restore_exc_port(), proc_steal_exc_port(), proc_update_sc(), procfs_create_inferior(), procfs_meminfo(), procfs_open(), procfs_pidlist(), procfs_store_registers(), ptrace_check(), pwd_command(), remote_hostio_error(), restore_binary_file(), restore_section_callback(), rs6000_wait(), S_msg_sig_post_untraced_reply(), S_proc_wait_reply(), save_breakpoints(), scalar_binop(), serial_logchar(), shell_escape(), som_current_sos(), som_open_symbol_file_object(), spu_child_wait(), steal_exc_port(), stop_callback(), stop_wait_callback(), store_register(), svr4_read_so_list(), terminal_ours_1(), tfile_start(), thread_takeover_sc_cmd(), unpush_and_perror(), wait_for(), and wait_with_trace().
char* windows_get_absolute_argv0 (const char * argv0)
Definition at line 88 of file mingw-hdep.c.
Referenced by captured_main().
Variable Documentation
initialize_file_ftype _initialize_mingw_hdep
Referenced by _initialize_mingw_hdep().
HANDLE sigint_event [static]
Definition at line 34 of file mingw-hdep.c.
Referenced by _initialize_mingw_hdep(), gdb_call_async_signal_handler(), and gdb_select().
struct async_signal_handler* sigint_handler
Definition at line 38 of file mingw-hdep.c.