GDB (xrefs): /home/stan/gdb/src/gdb/mips-tdep.c File Reference
/home/stan/gdb/src/gdb/mips-tdep.c File Reference
#include "defs.h"
#include "gdb_string.h"
#include "gdb_assert.h"
#include "frame.h"
#include "inferior.h"
#include "symtab.h"
#include "value.h"
#include "gdbcmd.h"
#include "language.h"
#include "gdbcore.h"
#include "symfile.h"
#include "objfiles.h"
#include "gdbtypes.h"
#include "target.h"
#include "arch-utils.h"
#include "regcache.h"
#include "osabi.h"
#include "mips-tdep.h"
#include "block.h"
#include "reggroups.h"
#include "opcode/mips.h"
#include "elf/mips.h"
#include "elf-bfd.h"
#include "symcat.h"
#include "sim-regno.h"
#include "dis-asm.h"
#include "frame-unwind.h"
#include "frame-base.h"
#include "trad-frame.h"
#include "infcall.h"
#include "floatformat.h"
#include "remote.h"
#include "target-descriptions.h"
#include "dwarf2-frame.h"
#include "user-regs.h"
#include "valprint.h"
#include "ax.h"
Classes
struct register_alias
struct upk_mips16
struct mips_frame_cache
struct mips_objfile_private
Defines
#define ST0_FR (1 << 26)
#define R(n) { "r" #n, n }
#define R(n) { #n, n }
#define MIPS_DEFAULT_FPU_TYPE MIPS_FPU_DOUBLE
#define PROPERTY_GP32 "internal: transfers-32bit-registers"
#define PROPERTY_GP64 "internal: transfers-64bit-registers"
#define MIPS_EABI(gdbarch)
#define MIPS_LAST_FP_ARG_REGNUM(gdbarch) (gdbarch_tdep (gdbarch)->mips_last_fp_arg_regnum)
#define MIPS_LAST_ARG_REGNUM(gdbarch) (gdbarch_tdep (gdbarch)->mips_last_arg_regnum)
#define MIPS_FPU_TYPE(gdbarch) (gdbarch_tdep (gdbarch)->mips_fpu_type)
#define VM_MIN_ADDRESS (CORE_ADDR)0x400000
#define mips32_op(x) (x >> 26)
#define itype_op(x) (x >> 26)
#define itype_rs(x) ((x >> 21) & 0x1f)
#define itype_rt(x) ((x >> 16) & 0x1f)
#define itype_immediate(x) (x & 0xffff)
#define jtype_op(x) (x >> 26)
#define jtype_target(x) (x & 0x03ffffff)
#define rtype_op(x) (x >> 26)
#define rtype_rs(x) ((x >> 21) & 0x1f)
#define rtype_rt(x) ((x >> 16) & 0x1f)
#define rtype_rd(x) ((x >> 11) & 0x1f)
#define rtype_shamt(x) ((x >> 6) & 0x1f)
#define rtype_funct(x) (x & 0x3f)
#define micromips_op(x) ((x) >> 10)
#define b0s4_imm(x) ((x) & 0xf)
#define b0s5_imm(x) ((x) & 0x1f)
#define b0s5_reg(x) ((x) & 0x1f)
#define b0s7_imm(x) ((x) & 0x7f)
#define b0s10_imm(x) ((x) & 0x3ff)
#define b1s4_imm(x) (((x) >> 1) & 0xf)
#define b1s9_imm(x) (((x) >> 1) & 0x1ff)
#define b2s3_cc(x) (((x) >> 2) & 0x7)
#define b4s2_regl(x) (((x) >> 4) & 0x3)
#define b5s5_op(x) (((x) >> 5) & 0x1f)
#define b5s5_reg(x) (((x) >> 5) & 0x1f)
#define b6s4_op(x) (((x) >> 6) & 0xf)
#define b7s3_reg(x) (((x) >> 7) & 0x7)
#define b0s6_op(x) ((x) & 0x3f)
#define b0s11_op(x) ((x) & 0x7ff)
#define b0s12_imm(x) ((x) & 0xfff)
#define b0s16_imm(x) ((x) & 0xffff)
#define b0s26_imm(x) ((x) & 0x3ffffff)
#define b6s10_ext(x) (((x) >> 6) & 0x3ff)
#define b11s5_reg(x) (((x) >> 11) & 0x1f)
#define b12s4_op(x) (((x) >> 12) & 0xf)
#define LL_OPCODE 0x30
#define LLD_OPCODE 0x34
#define SC_OPCODE 0x38
#define SCD_OPCODE 0x3c
Enumerations
enum { MIPS_FPU_SINGLE_REGSIZE = 4, MIPS_FPU_DOUBLE_REGSIZE = 8 }
enum { MIPS32_REGSIZE = 4, MIPS64_REGSIZE = 8 }
enum { NUM_MIPS_PROCESSOR_REGS = (90 - 32) }
enum mips16_inst_fmts {
itype, ritype, rrtype, rritype,
rrrtype, rriatype, shifttype, i8type,
i8movtype, i8mov32rtype, i64type, ri64type,
jalxtype, exiItype, extRitype, extRRItype,
extRRIAtype, EXTshifttype, extI8type, extI64type,
extRi64type, extshift64type
}
enum mips_fval_reg { mips_fval_fpr, mips_fval_gpr, mips_fval_both }
Functions
static struct type * mips_register_type (struct gdbarch *gdbarch, int regnum)
static int mips32_instruction_has_delay_slot (struct gdbarch *, CORE_ADDR)
static int micromips_instruction_has_delay_slot (struct gdbarch *, CORE_ADDR, int)
static int mips16_instruction_has_delay_slot (struct gdbarch *, CORE_ADDR, int)
struct mips_regnum * mips_regnum (struct gdbarch *gdbarch)
static int mips_fpa0_regnum (struct gdbarch *gdbarch)
static int mips_float_register_p (struct gdbarch *gdbarch, int regnum)
enum mips_abi mips_abi (struct gdbarch *gdbarch)
int mips_isa_regsize (struct gdbarch *gdbarch)
unsigned int mips_abi_regsize (struct gdbarch *gdbarch)
static int is_mips16_isa (struct gdbarch *gdbarch)
static int is_micromips_isa (struct gdbarch *gdbarch)
static int is_compact_addr (CORE_ADDR addr)
static int is_mips_addr (CORE_ADDR addr)
static int is_mips16_addr (struct gdbarch *gdbarch, CORE_ADDR addr)
static int is_micromips_addr (struct gdbarch *gdbarch, CORE_ADDR addr)
static CORE_ADDR unmake_compact_addr (CORE_ADDR addr)
static CORE_ADDR make_compact_addr (CORE_ADDR addr)
static void mips_elf_make_msymbol_special (asymbol *sym, struct minimal_symbol *msym)
static int msymbol_is_mips (struct minimal_symbol *msym)
static int msymbol_is_mips16 (struct minimal_symbol *msym)
static int msymbol_is_micromips (struct minimal_symbol *msym)
static void mips_xfer_register (struct gdbarch *gdbarch, struct regcache *regcache, int reg_num, int length, enum bfd_endian endian, gdb_byte *in, const gdb_byte *out, int buf_offset)
static int mips2_fp_compat (struct frame_info *frame)
static CORE_ADDR heuristic_proc_start (struct gdbarch *, CORE_ADDR)
static void reinit_frame_cache_sfunc (char *, int, struct cmd_list_element *)
static const char * mips_register_name (struct gdbarch *gdbarch, int regno)
static int mips_register_reggroup_p (struct gdbarch *gdbarch, int regnum, struct reggroup *reggroup)
static int mips_tdesc_register_reggroup_p (struct gdbarch *gdbarch, int regnum, struct reggroup *reggroup)
static enum register_status mips_pseudo_register_read (struct gdbarch *gdbarch, struct regcache *regcache, int cookednum, gdb_byte *buf)
static void mips_pseudo_register_write (struct gdbarch *gdbarch, struct regcache *regcache, int cookednum, const gdb_byte *buf)
static int mips_ax_pseudo_register_collect (struct gdbarch *gdbarch, struct agent_expr *ax, int reg)
static int mips_ax_pseudo_register_push_stack (struct gdbarch *gdbarch, struct agent_expr *ax, int reg)
static void set_mips64_transfers_32bit_regs (char *args, int from_tty, struct cmd_list_element *c)
static int mips_convert_register_float_case_p (struct gdbarch *gdbarch, int regnum, struct type *type)
static int mips_convert_register_gpreg_case_p (struct gdbarch *gdbarch, int regnum, struct type *type)
static int mips_convert_register_p (struct gdbarch *gdbarch, int regnum, struct type *type)
static int mips_register_to_value (struct frame_info *frame, int regnum, struct type *type, gdb_byte *to, int *optimizedp, int *unavailablep)
static void mips_value_to_register (struct frame_info *frame, int regnum, struct type *type, const gdb_byte *from)
static struct type * mips_pseudo_register_type (struct gdbarch *gdbarch, int regnum)
static int mips_mask_address_p (struct gdbarch_tdep *tdep)
static void show_mask_address (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
int mips_pc_is_mips (CORE_ADDR memaddr)
int mips_pc_is_mips16 (struct gdbarch *gdbarch, CORE_ADDR memaddr)
int mips_pc_is_micromips (struct gdbarch *gdbarch, CORE_ADDR memaddr)
static enum mips_isa mips_pc_isa (struct gdbarch *gdbarch, CORE_ADDR memaddr)
static int mips_in_frame_stub (CORE_ADDR pc)
static CORE_ADDR mips_read_pc (struct regcache *regcache)
static CORE_ADDR mips_unwind_pc (struct gdbarch *gdbarch, struct frame_info *next_frame)
static CORE_ADDR mips_unwind_sp (struct gdbarch *gdbarch, struct frame_info *next_frame)
static struct frame_id mips_dummy_id (struct gdbarch *gdbarch, struct frame_info *this_frame)
void mips_write_pc (struct regcache *regcache, CORE_ADDR pc)
static ULONGEST mips_fetch_instruction (struct gdbarch *gdbarch, enum mips_isa isa, CORE_ADDR addr, int *statusp)
static int mips_insn_size (enum mips_isa isa, ULONGEST insn)
static LONGEST mips32_relative_offset (ULONGEST inst)
static CORE_ADDR mips32_bc1_pc (struct gdbarch *gdbarch, struct frame_info *frame, ULONGEST inst, CORE_ADDR pc, int count)
static int is_octeon (struct gdbarch *gdbarch)
static int is_octeon_bbit_op (int op, struct gdbarch *gdbarch)
static CORE_ADDR mips32_next_pc (struct frame_info *frame, CORE_ADDR pc)
static LONGEST micromips_relative_offset7 (ULONGEST insn)
static LONGEST micromips_relative_offset10 (ULONGEST insn)
static LONGEST micromips_relative_offset16 (ULONGEST insn)
static int micromips_pc_insn_size (struct gdbarch *gdbarch, CORE_ADDR pc)
static CORE_ADDR micromips_bc1_pc (struct gdbarch *gdbarch, struct frame_info *frame, ULONGEST insn, CORE_ADDR pc, int count)
static CORE_ADDR micromips_next_pc (struct frame_info *frame, CORE_ADDR pc)
static CORE_ADDR extended_offset (unsigned int extension)
static unsigned int fetch_mips_16 (struct gdbarch *gdbarch, CORE_ADDR pc)
static void unpack_mips16 (struct gdbarch *gdbarch, CORE_ADDR pc, unsigned int extension, unsigned int inst, enum mips16_inst_fmts insn_format, struct upk_mips16 *upk)
static CORE_ADDR add_offset_16 (CORE_ADDR pc, int offset)
static CORE_ADDR extended_mips16_next_pc (struct frame_info *frame, CORE_ADDR pc, unsigned int extension, unsigned int insn)
static CORE_ADDR mips16_next_pc (struct frame_info *frame, CORE_ADDR pc)
static CORE_ADDR mips_next_pc (struct frame_info *frame, CORE_ADDR pc)
static void set_reg_offset (struct gdbarch *gdbarch, struct mips_frame_cache *this_cache, int regnum, CORE_ADDR offset)
static int mips16_get_imm (unsigned short prev_inst, unsigned short inst, int nbits, int scale, int is_signed)
static CORE_ADDR mips16_scan_prologue (struct gdbarch *gdbarch, CORE_ADDR start_pc, CORE_ADDR limit_pc, struct frame_info *this_frame, struct mips_frame_cache *this_cache)
static struct mips_frame_cache * mips_insn16_frame_cache (struct frame_info *this_frame, void **this_cache)
static void mips_insn16_frame_this_id (struct frame_info *this_frame, void **this_cache, struct frame_id *this_id)
static struct value * mips_insn16_frame_prev_register (struct frame_info *this_frame, void **this_cache, int regnum)
static int mips_insn16_frame_sniffer (const struct frame_unwind *self, struct frame_info *this_frame, void **this_cache)
static CORE_ADDR mips_insn16_frame_base_address (struct frame_info *this_frame, void **this_cache)
static struct frame_base * mips_insn16_frame_base_sniffer (struct frame_info *this_frame)
static int micromips_decode_imm9 (int imm)
static CORE_ADDR micromips_scan_prologue (struct gdbarch *gdbarch, CORE_ADDR start_pc, CORE_ADDR limit_pc, struct frame_info *this_frame, struct mips_frame_cache *this_cache)
static struct mips_frame_cache * mips_micro_frame_cache (struct frame_info *this_frame, void **this_cache)
static void mips_micro_frame_this_id (struct frame_info *this_frame, void **this_cache, struct frame_id *this_id)
static struct value * mips_micro_frame_prev_register (struct frame_info *this_frame, void **this_cache, int regnum)
static int mips_micro_frame_sniffer (const struct frame_unwind *self, struct frame_info *this_frame, void **this_cache)
static CORE_ADDR mips_micro_frame_base_address (struct frame_info *this_frame, void **this_cache)
static struct frame_base * mips_micro_frame_base_sniffer (struct frame_info *this_frame)
static void reset_saved_regs (struct gdbarch *gdbarch, struct mips_frame_cache *this_cache)
static CORE_ADDR mips32_scan_prologue (struct gdbarch *gdbarch, CORE_ADDR start_pc, CORE_ADDR limit_pc, struct frame_info *this_frame, struct mips_frame_cache *this_cache)
static struct mips_frame_cache * mips_insn32_frame_cache (struct frame_info *this_frame, void **this_cache)
static void mips_insn32_frame_this_id (struct frame_info *this_frame, void **this_cache, struct frame_id *this_id)
static struct value * mips_insn32_frame_prev_register (struct frame_info *this_frame, void **this_cache, int regnum)
static int mips_insn32_frame_sniffer (const struct frame_unwind *self, struct frame_info *this_frame, void **this_cache)
static CORE_ADDR mips_insn32_frame_base_address (struct frame_info *this_frame, void **this_cache)
static struct frame_base * mips_insn32_frame_base_sniffer (struct frame_info *this_frame)
static struct trad_frame_cache * mips_stub_frame_cache (struct frame_info *this_frame, void **this_cache)
static void mips_stub_frame_this_id (struct frame_info *this_frame, void **this_cache, struct frame_id *this_id)
static struct value * mips_stub_frame_prev_register (struct frame_info *this_frame, void **this_cache, int regnum)
static int mips_stub_frame_sniffer (const struct frame_unwind *self, struct frame_info *this_frame, void **this_cache)
static CORE_ADDR mips_stub_frame_base_address (struct frame_info *this_frame, void **this_cache)
static struct frame_base * mips_stub_frame_base_sniffer (struct frame_info *this_frame)
static CORE_ADDR mips_addr_bits_remove (struct gdbarch *gdbarch, CORE_ADDR addr)
static int mips_deal_with_atomic_sequence (struct gdbarch *gdbarch, struct address_space *aspace, CORE_ADDR pc)
static int micromips_deal_with_atomic_sequence (struct gdbarch *gdbarch, struct address_space *aspace, CORE_ADDR pc)
static int deal_with_atomic_sequence (struct gdbarch *gdbarch, struct address_space *aspace, CORE_ADDR pc)
int mips_software_single_step (struct frame_info *frame)
static int mips_about_to_return (struct gdbarch *gdbarch, CORE_ADDR pc)
static int fp_register_arg_p (struct gdbarch *gdbarch, enum type_code typecode, struct type *arg_type)
static int mips_type_needs_double_align (struct type *type)
static CORE_ADDR mips_frame_align (struct gdbarch *gdbarch, CORE_ADDR addr)
static CORE_ADDR mips_push_dummy_code (struct gdbarch *gdbarch, CORE_ADDR sp, CORE_ADDR funaddr, struct value **args, int nargs, struct type *value_type, CORE_ADDR *real_pc, CORE_ADDR *bp_addr, struct regcache *regcache)
static CORE_ADDR mips_eabi_push_dummy_call (struct gdbarch *gdbarch, struct value *function, struct regcache *regcache, CORE_ADDR bp_addr, int nargs, struct value **args, CORE_ADDR sp, int struct_return, CORE_ADDR struct_addr)
static enum return_value_convention mips_eabi_return_value (struct gdbarch *gdbarch, struct value *function, struct type *type, struct regcache *regcache, gdb_byte *readbuf, const gdb_byte *writebuf)
static int mips_n32n64_fp_arg_chunk_p (struct gdbarch *gdbarch, struct type *arg_type, int offset)
static CORE_ADDR mips_n32n64_push_dummy_call (struct gdbarch *gdbarch, struct value *function, struct regcache *regcache, CORE_ADDR bp_addr, int nargs, struct value **args, CORE_ADDR sp, int struct_return, CORE_ADDR struct_addr)
static enum return_value_convention mips_n32n64_return_value (struct gdbarch *gdbarch, struct value *function, struct type *type, struct regcache *regcache, gdb_byte *readbuf, const gdb_byte *writebuf)
static CORE_ADDR mips_o32_push_dummy_call (struct gdbarch *gdbarch, struct value *function, struct regcache *regcache, CORE_ADDR bp_addr, int nargs, struct value **args, CORE_ADDR sp, int struct_return, CORE_ADDR struct_addr)
static enum return_value_convention mips_o32_return_value (struct gdbarch *gdbarch, struct value *function, struct type *type, struct regcache *regcache, gdb_byte *readbuf, const gdb_byte *writebuf)
static CORE_ADDR mips_o64_push_dummy_call (struct gdbarch *gdbarch, struct value *function, struct regcache *regcache, CORE_ADDR bp_addr, int nargs, struct value **args, CORE_ADDR sp, int struct_return, CORE_ADDR struct_addr)
static enum return_value_convention mips_o64_return_value (struct gdbarch *gdbarch, struct value *function, struct type *type, struct regcache *regcache, gdb_byte *readbuf, const gdb_byte *writebuf)
static void mips_read_fp_register_single (struct frame_info *frame, int regno, gdb_byte *rare_buffer)
static void mips_read_fp_register_double (struct frame_info *frame, int regno, gdb_byte *rare_buffer)
static void mips_print_fp_register (struct ui_file *file, struct frame_info *frame, int regnum)
static void mips_print_register (struct ui_file *file, struct frame_info *frame, int regnum)
static int print_fp_register_row (struct ui_file *file, struct frame_info *frame, int regnum)
static int print_gp_register_row (struct ui_file *file, struct frame_info *frame, int start_regnum)
static void mips_print_registers_info (struct gdbarch *gdbarch, struct ui_file *file, struct frame_info *frame, int regnum, int all)
static int mips_single_step_through_delay (struct gdbarch *gdbarch, struct frame_info *frame)
static CORE_ADDR mips_skip_prologue (struct gdbarch *gdbarch, CORE_ADDR pc)
static int mips32_in_function_epilogue_p (struct gdbarch *gdbarch, CORE_ADDR pc)
static int micromips_in_function_epilogue_p (struct gdbarch *gdbarch, CORE_ADDR pc)
static int mips16_in_function_epilogue_p (struct gdbarch *gdbarch, CORE_ADDR pc)
static int mips_in_function_epilogue_p (struct gdbarch *gdbarch, CORE_ADDR pc)
static void show_mips_command (char *args, int from_tty)
static void set_mips_command (char *args, int from_tty)
static void show_mipsfpu_command (char *args, int from_tty)
static void set_mipsfpu_command (char *args, int from_tty)
static void set_mipsfpu_single_command (char *args, int from_tty)
static void set_mipsfpu_double_command (char *args, int from_tty)
static void set_mipsfpu_none_command (char *args, int from_tty)
static void set_mipsfpu_auto_command (char *args, int from_tty)
void deprecated_mips_set_processor_regs_hack (void)
static int gdb_print_insn_mips (bfd_vma memaddr, struct disassemble_info *info)
static int gdb_print_insn_mips_n32 (bfd_vma memaddr, struct disassemble_info *info)
static int gdb_print_insn_mips_n64 (bfd_vma memaddr, struct disassemble_info *info)
static const gdb_byte * mips_breakpoint_from_pc (struct gdbarch *gdbarch, CORE_ADDR *pcptr, int *lenptr)
static void mips_remote_breakpoint_from_pc (struct gdbarch *gdbarch, CORE_ADDR *pcptr, int *kindptr)
static CORE_ADDR mips_segment_boundary (CORE_ADDR bpaddr)
static CORE_ADDR mips_adjust_breakpoint_address (struct gdbarch *gdbarch, CORE_ADDR bpaddr)
static int mips_is_stub_suffix (const char *suffix, int zero)
static int mips_is_stub_mode (const char *mode)
static CORE_ADDR mips_get_mips16_fn_stub_pc (struct frame_info *frame, CORE_ADDR pc)
static CORE_ADDR mips_skip_mips16_trampoline_code (struct frame_info *frame, CORE_ADDR pc)
static int mips_in_return_stub (struct gdbarch *gdbarch, CORE_ADDR pc, const char *name)
static CORE_ADDR mips_skip_pic_trampoline_code (struct frame_info *frame, CORE_ADDR pc)
static CORE_ADDR mips_skip_trampoline_code (struct frame_info *frame, CORE_ADDR pc)
static int mips_stab_reg_to_regnum (struct gdbarch *gdbarch, int num)
static int mips_dwarf_dwarf2_ecoff_reg_to_regnum (struct gdbarch *gdbarch, int num)
static int mips_register_sim_regno (struct gdbarch *gdbarch, int regnum)
static CORE_ADDR mips_integer_to_address (struct gdbarch *gdbarch, struct type *type, const gdb_byte *buf)
static void mips_virtual_frame_pointer (struct gdbarch *gdbarch, CORE_ADDR pc, int *reg, LONGEST *offset)
static void mips_find_abi_section (bfd *abfd, asection *sect, void *obj)
static void mips_find_long_section (bfd *abfd, asection *sect, void *obj)
static enum mips_abi global_mips_abi (void)
static enum mips_isa global_mips_compression (void)
static void mips_register_g_packet_guesses (struct gdbarch *gdbarch)
static struct value * value_of_mips_user_reg (struct frame_info *frame, const void *baton)
static struct gdbarch * mips_gdbarch_init (struct gdbarch_info info, struct gdbarch_list *arches)
static void mips_abi_update (char *ignore_args, int from_tty, struct cmd_list_element *c)
static void show_mips_abi (struct ui_file *file, int from_tty, struct cmd_list_element *ignored_cmd, const char *ignored_value)
static void show_mips_compression (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static void mips_dump_tdep (struct gdbarch *gdbarch, struct ui_file *file)
void _initialize_mips_tdep (void)
Variables
static struct objfile_data * mips_pdr_data
static const char * mips_abi_string
static const char *const mips_abi_strings []
static const char mips_compression_mips16 [] = "mips16"
static const char mips_compression_micromips [] = "micromips"
static const char *const mips_compression_strings []
static const char * mips_compression_string = mips_compression_mips16
struct register_alias mips_o32_aliases []
struct register_alias mips_n32_n64_aliases []
struct register_alias mips_register_aliases []
struct register_alias mips_numeric_register_aliases []
static int mips_fpu_type_auto = 1
static enum mips_fpu_type mips_fpu_type = MIPS_DEFAULT_FPU_TYPE
static unsigned int mips_debug = 0
struct target_desc * mips_tdesc_gp32
struct target_desc * mips_tdesc_gp64
static struct cmd_list_element * setmipscmdlist = NULL
static struct cmd_list_element * showmipscmdlist = NULL
static const char * mips_generic_reg_names [NUM_MIPS_PROCESSOR_REGS]
static const char * mips_r3041_reg_names []
static const char * mips_tx39_reg_names [NUM_MIPS_PROCESSOR_REGS]
static const char * mips_irix_reg_names [NUM_MIPS_PROCESSOR_REGS]
static const char * mips_linux_reg_names [NUM_MIPS_PROCESSOR_REGS]
static const signed char mips_reg3_to_reg [8] = { 16, 17, 2, 3, 4, 5, 6, 7 }
static int heuristic_fence_post = 0
static int mips64_transfers_32bit_regs_p = 0
enum auto_boolean mask_address_var = AUTO_BOOLEAN_AUTO
static const char mips_str_mips16_call_stub [] = "__mips16_call_stub_"
static const char mips_str_mips16_ret_stub [] = "__mips16_ret_"
static const char mips_str_call_fp_stub [] = "__call_stub_fp_"
static const char mips_str_call_stub [] = "__call_stub_"
static const char mips_str_fn_stub [] = "__fn_stub_"
static const char mips_str_pic [] = ".pic."
static struct frame_unwind mips_insn16_frame_unwind
static struct frame_base mips_insn16_frame_base
static struct frame_unwind mips_micro_frame_unwind
static struct frame_base mips_micro_frame_base
static struct frame_unwind mips_insn32_frame_unwind
static struct frame_base mips_insn32_frame_base
static struct frame_unwind mips_stub_frame_unwind
static struct frame_base mips_stub_frame_base
initialize_file_ftype _initialize_mips_tdep
Define Documentation
#define b0s10_imm (x) ((x) & 0x3ff)
Definition at line 1391 of file mips-tdep.c.
Referenced by micromips_relative_offset10().
#define b0s11_op (x) ((x) & 0x7ff)
Definition at line 1404 of file mips-tdep.c.
Referenced by micromips_scan_prologue().
#define b0s12_imm (x) ((x) & 0xfff)
Definition at line 1405 of file mips-tdep.c.
Referenced by micromips_scan_prologue().
#define b0s16_imm (x) ((x) & 0xffff)
Definition at line 1406 of file mips-tdep.c.
Referenced by heuristic_proc_start(), micromips_in_function_epilogue_p(), micromips_relative_offset16(), and micromips_scan_prologue().
#define b0s26_imm (x) ((x) & 0x3ffffff)
Definition at line 1407 of file mips-tdep.c.
Referenced by micromips_next_pc().
#define b0s4_imm (x) ((x) & 0xf)
Definition at line 1387 of file mips-tdep.c.
Referenced by micromips_scan_prologue().
#define b0s5_imm (x) ((x) & 0x1f)
Definition at line 1388 of file mips-tdep.c.
Referenced by micromips_scan_prologue().
#define b0s5_reg (x) ((x) & 0x1f)
Definition at line 1389 of file mips-tdep.c.
Referenced by heuristic_proc_start(), micromips_in_function_epilogue_p(), micromips_next_pc(), and micromips_scan_prologue().
#define b0s6_op (x) ((x) & 0x3f)
Definition at line 1403 of file mips-tdep.c.
Referenced by micromips_deal_with_atomic_sequence(), micromips_instruction_has_delay_slot(), and micromips_next_pc().
#define b0s7_imm (x) ((x) & 0x7f)
Definition at line 1390 of file mips-tdep.c.
Referenced by micromips_relative_offset7().
#define b11s5_reg (x) (((x) >> 11) & 0x1f)
Definition at line 1409 of file mips-tdep.c.
Referenced by micromips_scan_prologue().
#define b12s4_op (x) (((x) >> 12) & 0xf)
Definition at line 1410 of file mips-tdep.c.
Referenced by micromips_deal_with_atomic_sequence(), and micromips_scan_prologue().
#define b1s4_imm (x) (((x) >> 1) & 0xf)
Definition at line 1392 of file mips-tdep.c.
Referenced by heuristic_proc_start(), and micromips_scan_prologue().
#define b1s9_imm (x) (((x) >> 1) & 0x1ff)
Definition at line 1393 of file mips-tdep.c.
Referenced by heuristic_proc_start(), micromips_in_function_epilogue_p(), and micromips_scan_prologue().
#define b2s3_cc (x) (((x) >> 2) & 0x7)
Definition at line 1394 of file mips-tdep.c.
Referenced by micromips_bc1_pc().
#define b4s2_regl (x) (((x) >> 4) & 0x3)
Definition at line 1395 of file mips-tdep.c.
Referenced by micromips_scan_prologue().
#define b5s5_op (x) (((x) >> 5) & 0x1f)
Definition at line 1396 of file mips-tdep.c.
Referenced by heuristic_proc_start(), micromips_bc1_pc(), micromips_deal_with_atomic_sequence(), micromips_in_function_epilogue_p(), micromips_instruction_has_delay_slot(), micromips_next_pc(), and micromips_scan_prologue().
#define b5s5_reg (x) (((x) >> 5) & 0x1f)
Definition at line 1397 of file mips-tdep.c.
Referenced by heuristic_proc_start(), micromips_in_function_epilogue_p(), micromips_next_pc(), and micromips_scan_prologue().
#define b6s10_ext (x) (((x) >> 6) & 0x3ff)
Definition at line 1408 of file mips-tdep.c.
Referenced by micromips_deal_with_atomic_sequence(), micromips_instruction_has_delay_slot(), and micromips_next_pc().
#define b6s4_op (x) (((x) >> 6) & 0xf)
Definition at line 1398 of file mips-tdep.c.
Referenced by micromips_scan_prologue().
#define b7s3_reg (x) (((x) >> 7) & 0x7)
Definition at line 1399 of file mips-tdep.c.
Referenced by micromips_next_pc().
#define itype_immediate (x) (x & 0xffff)
Definition at line 1370 of file mips-tdep.c.
Referenced by mips32_relative_offset(), and mips_get_mips16_fn_stub_pc().
#define itype_op (x) (x >> 26)
Definition at line 1367 of file mips-tdep.c.
Referenced by mips32_instruction_has_delay_slot(), mips32_next_pc(), mips32_scan_prologue(), mips_deal_with_atomic_sequence(), and mips_get_mips16_fn_stub_pc().
#define itype_rs (x) ((x >> 21) & 0x1f)
Definition at line 1368 of file mips-tdep.c.
Referenced by mips32_instruction_has_delay_slot(), mips32_next_pc(), mips_deal_with_atomic_sequence(), and mips_get_mips16_fn_stub_pc().
#define itype_rt (x) ((x >> 16) & 0x1f)
Definition at line 1369 of file mips-tdep.c.
Referenced by mips32_bc1_pc(), mips32_instruction_has_delay_slot(), mips32_next_pc(), mips_deal_with_atomic_sequence(), and mips_get_mips16_fn_stub_pc().
#define jtype_op (x) (x >> 26)
Definition at line 1372 of file mips-tdep.c.
#define jtype_target (x) (x & 0x03ffffff)
Definition at line 1373 of file mips-tdep.c.
Referenced by mips32_next_pc(), and mips_get_mips16_fn_stub_pc().
#define LL_OPCODE 0x30
Definition at line 3687 of file mips-tdep.c.
Referenced by mips_deal_with_atomic_sequence().
#define LLD_OPCODE 0x34
Definition at line 3688 of file mips-tdep.c.
Referenced by mips_deal_with_atomic_sequence().
#define micromips_op (x) ((x) >> 10)
Definition at line 1383 of file mips-tdep.c.
Referenced by heuristic_proc_start(), micromips_deal_with_atomic_sequence(), micromips_in_function_epilogue_p(), micromips_instruction_has_delay_slot(), micromips_next_pc(), micromips_scan_prologue(), and mips_insn_size().
#define mips32_op (x) (x >> 26)
Definition at line 1366 of file mips-tdep.c.
#define MIPS_DEFAULT_FPU_TYPE MIPS_FPU_DOUBLE
Definition at line 175 of file mips-tdep.c.
Referenced by mips_dump_tdep().
#define MIPS_EABI (gdbarch)
Value:
(gdbarch_tdep (gdbarch)->mips_abi \
                     == MIPS_ABI_EABI32 \
                   || gdbarch_tdep (gdbarch)->mips_abi == MIPS_ABI_EABI64)
Definition at line 214 of file mips-tdep.c.
Referenced by fp_register_arg_p(), and mips_dump_tdep().
#define MIPS_FPU_TYPE (gdbarch) (gdbarch_tdep (gdbarch)->mips_fpu_type)
Definition at line 224 of file mips-tdep.c.
Referenced by fp_register_arg_p(), mips_dump_tdep(), mips_n32n64_fp_arg_chunk_p(), and show_mipsfpu_command().
#define MIPS_LAST_ARG_REGNUM (gdbarch) (gdbarch_tdep (gdbarch)->mips_last_arg_regnum)
Definition at line 221 of file mips-tdep.c.
Referenced by mips_eabi_push_dummy_call(), mips_n32n64_push_dummy_call(), mips_o32_push_dummy_call(), and mips_o64_push_dummy_call().
#define MIPS_LAST_FP_ARG_REGNUM (gdbarch) (gdbarch_tdep (gdbarch)->mips_last_fp_arg_regnum)
Definition at line 218 of file mips-tdep.c.
Referenced by mips_eabi_push_dummy_call(), mips_o32_push_dummy_call(), and mips_o64_push_dummy_call().
#define PROPERTY_GP32 "internal: transfers-32bit-registers"
Definition at line 184 of file mips-tdep.c.
Referenced by _initialize_mips_tdep(), and mips_gdbarch_init().
#define PROPERTY_GP64 "internal: transfers-64bit-registers"
Definition at line 185 of file mips-tdep.c.
Referenced by _initialize_mips_tdep(), and mips_gdbarch_init().
#define R (n) { "r" #n, n }
#define R (n) { #n, n }
#define rtype_funct (x) (x & 0x3f)
Definition at line 1380 of file mips-tdep.c.
Referenced by mips32_instruction_has_delay_slot(), mips32_next_pc(), mips32_scan_prologue(), mips_deal_with_atomic_sequence(), and mips_get_mips16_fn_stub_pc().
#define rtype_op (x) (x >> 26)
Definition at line 1375 of file mips-tdep.c.
#define rtype_rd (x) ((x >> 11) & 0x1f)
Definition at line 1378 of file mips-tdep.c.
Referenced by mips_get_mips16_fn_stub_pc().
#define rtype_rs (x) ((x >> 21) & 0x1f)
Definition at line 1376 of file mips-tdep.c.
Referenced by mips32_next_pc(), and mips_get_mips16_fn_stub_pc().
#define rtype_rt (x) ((x >> 16) & 0x1f)
Definition at line 1377 of file mips-tdep.c.
Referenced by mips_get_mips16_fn_stub_pc().
#define rtype_shamt (x) ((x >> 6) & 0x1f)
Definition at line 1379 of file mips-tdep.c.
#define SC_OPCODE 0x38
Definition at line 3689 of file mips-tdep.c.
Referenced by mips_deal_with_atomic_sequence().
#define SCD_OPCODE 0x3c
Definition at line 3690 of file mips-tdep.c.
Referenced by mips_deal_with_atomic_sequence().
#define ST0_FR (1 << 26)
Definition at line 73 of file mips-tdep.c.
Referenced by mips2_fp_compat().
#define VM_MIN_ADDRESS (CORE_ADDR)0x400000
Definition at line 480 of file mips-tdep.c.
Referenced by gnu_find_memory_regions(), and heuristic_proc_start().
Enumeration Type Documentation
anonymous enum
Enumerator:
MIPS_FPU_SINGLE_REGSIZE
MIPS_FPU_DOUBLE_REGSIZE
Definition at line 77 of file mips-tdep.c.
anonymous enum
Enumerator:
MIPS32_REGSIZE
MIPS64_REGSIZE
Definition at line 83 of file mips-tdep.c.
anonymous enum
Enumerator:
NUM_MIPS_PROCESSOR_REGS
Definition at line 495 of file mips-tdep.c.
enum mips16_inst_fmts
Enumerator:
itype
ritype
rrtype
rritype
rrrtype
rriatype
shifttype
i8type
i8movtype
i8mov32rtype
i64type
ri64type
jalxtype
exiItype
extRitype
extRRItype
extRRIAtype
EXTshifttype
extI8type
extI64type
extRi64type
extshift64type
Definition at line 1981 of file mips-tdep.c.
enum mips_fval_reg
Enumerator:
mips_fval_fpr
mips_fval_gpr
mips_fval_both
Definition at line 5134 of file mips-tdep.c.
Function Documentation
void _initialize_mips_tdep (void)
Definition at line 8795 of file mips-tdep.c.
References _, add_alias_cmd(), add_cmd(), add_prefix_cmd(), add_setshow_auto_boolean_cmd(), add_setshow_boolean_cmd(), add_setshow_enum_cmd(), add_setshow_zinteger_cmd(), add_setshow_zuinteger_cmd(), allocate_target_description(), class_maintenance, class_obscure, class_support, gdbarch_register(), internal_error(), MIPS_ABI_LAST, mips_abi_string, mips_abi_strings, MIPS_ABI_UNKNOWN, mips_abi_update(), mips_compression_string, mips_compression_strings, mips_debug, mips_dump_tdep(), mips_gdbarch_init(), mips_pdr_data, no_class, PROPERTY_GP32, PROPERTY_GP64, reinit_frame_cache_sfunc(), set_mips64_transfers_32bit_regs(), set_mips_command(), set_mipsfpu_auto_command(), set_mipsfpu_command(), set_mipsfpu_double_command(), set_mipsfpu_none_command(), set_mipsfpu_single_command(), set_tdesc_property(), setdebuglist, setlist, show_mask_address(), show_mips_abi(), show_mips_command(), show_mips_compression(), show_mipsfpu_command(), showdebuglist, and showlist.
static CORE_ADDR add_offset_16 (CORE_ADDR pc, int offset) [static]
Definition at line 2125 of file mips-tdep.c.
Referenced by extended_mips16_next_pc().
static int deal_with_atomic_sequence (struct gdbarch * gdbarch, struct address_space * aspace, CORE_ADDR pc) [static]
Definition at line 3952 of file mips-tdep.c.
References micromips_deal_with_atomic_sequence(), mips_deal_with_atomic_sequence(), mips_pc_is_micromips(), and mips_pc_is_mips().
Referenced by mips_software_single_step().
void deprecated_mips_set_processor_regs_hack (void)
Definition at line 6751 of file mips-tdep.c.
References gdbarch_tdep(), get_current_regcache(), get_regcache_arch(), MIPS_PRID_REGNUM, gdbarch_tdep::mips_processor_reg_names, mips_r3041_reg_names, regcache_cooked_read_unsigned(), and ULONGEST.
static CORE_ADDR extended_mips16_next_pc (struct frame_info * frame, CORE_ADDR pc, unsigned int extension, unsigned int insn) [static]
Definition at line 2131 of file mips-tdep.c.
References add_offset_16(), fetch_mips_16(), get_frame_arch(), get_frame_register_signed(), i8type, itype, jalxtype, upk_mips16::offset, upk_mips16::regx, upk_mips16::regy, ritype, and unpack_mips16().
Referenced by mips16_next_pc().
static CORE_ADDR extended_offset (unsigned int extension) [static]
Definition at line 2020 of file mips-tdep.c.
Referenced by unpack_mips16().
static unsigned int fetch_mips_16 (struct gdbarch * gdbarch, CORE_ADDR pc) [static]
Definition at line 2041 of file mips-tdep.c.
References extract_unsigned_integer(), gdbarch_byte_order(), target_read_memory(), and unmake_compact_addr().
Referenced by extended_mips16_next_pc(), and mips16_next_pc().
static int fp_register_arg_p (struct gdbarch * gdbarch, enum type_code typecode, struct type * arg_type) [static]
Definition at line 4191 of file mips-tdep.c.
References check_typedef(), MIPS_EABI, MIPS_FPU_NONE, MIPS_FPU_TYPE, TYPE_CODE, TYPE_CODE_FLT, TYPE_CODE_STRUCT, TYPE_CODE_UNION, TYPE_FIELD_TYPE, and TYPE_NFIELDS.
Referenced by mips_eabi_push_dummy_call(), mips_n32n64_push_dummy_call(), mips_o32_push_dummy_call(), mips_o64_push_dummy_call(), and mips_o64_return_value().
static int gdb_print_insn_mips (bfd_vma memaddr, struct disassemble_info * info) [static]
Definition at line 6774 of file mips-tdep.c.
References mips_pc_is_micromips(), and mips_pc_is_mips16().
Referenced by gdb_print_insn_mips_n32(), gdb_print_insn_mips_n64(), and mips_gdbarch_init().
static int gdb_print_insn_mips_n32 (bfd_vma memaddr, struct disassemble_info * info) [static]
Definition at line 6808 of file mips-tdep.c.
References gdb_print_insn_mips().
Referenced by mips_gdbarch_init().
static int gdb_print_insn_mips_n64 (bfd_vma memaddr, struct disassemble_info * info) [static]
Definition at line 6819 of file mips-tdep.c.
References gdb_print_insn_mips().
Referenced by mips_gdbarch_init().
static enum mips_abi global_mips_abi (void) [static]
Definition at line 7851 of file mips-tdep.c.
References _, internal_error(), mips_abi_string, and mips_abi_strings.
Referenced by mips_gdbarch_init(), and show_mips_abi().
static enum mips_isa global_mips_compression (void) [static]
Definition at line 7868 of file mips-tdep.c.
References _, internal_error(), mips_compression_string, and mips_compression_strings.
Referenced by mips_gdbarch_init().
static CORE_ADDR heuristic_proc_start (struct gdbarch * gdbarch, CORE_ADDR pc) [static]
Definition at line 4009 of file mips-tdep.c.
References _, b0s16_imm, b0s5_reg, b1s4_imm, b1s9_imm, b5s5_op, b5s5_reg, inferior::control, current_inferior(), gdbarch_addr_bits_remove(), heuristic_fence_post, arm-linux::inf, ISA_MICROMIPS, ISA_MIPS16, micromips_decode_imm9(), micromips_op, mips_about_to_return(), mips_fetch_instruction(), MIPS_INSN16_SIZE, MIPS_INSN32_SIZE, mips_pc_is_micromips(), mips_pc_is_mips(), mips_pc_is_mips16(), MIPS_SP_REGNUM, NO_STOP_QUIETLY, offset, paddress(), printf_filtered(), inferior_control_state::stop_soon, ULONGEST, VM_MIN_ADDRESS, and warning().
Referenced by mips_insn16_frame_cache(), mips_insn32_frame_cache(), and mips_micro_frame_cache().
static int is_compact_addr (CORE_ADDR addr) [static]
Definition at line 293 of file mips-tdep.c.
Referenced by is_micromips_addr(), is_mips16_addr(), is_mips_addr(), mips_addr_bits_remove(), mips_read_pc(), mips_skip_trampoline_code(), and mips_unwind_pc().
static int is_micromips_addr (struct gdbarch * gdbarch, CORE_ADDR addr) [static]
Definition at line 317 of file mips-tdep.c.
References is_compact_addr(), and is_micromips_isa().
Referenced by mips_pc_is_micromips(), and mips_pc_isa().
static int is_micromips_isa (struct gdbarch * gdbarch) [static]
Definition at line 285 of file mips-tdep.c.
References gdbarch_tdep(), ISA_MICROMIPS, and gdbarch_tdep::mips_isa.
Referenced by is_micromips_addr().
static int is_mips16_addr (struct gdbarch * gdbarch, CORE_ADDR addr) [static]
Definition at line 309 of file mips-tdep.c.
References is_compact_addr(), and is_mips16_isa().
Referenced by mips_pc_is_mips16().
static int is_mips16_isa (struct gdbarch * gdbarch) [static]
Definition at line 277 of file mips-tdep.c.
References gdbarch_tdep(), ISA_MIPS16, and gdbarch_tdep::mips_isa.
Referenced by is_mips16_addr().
static int is_mips_addr (CORE_ADDR addr) [static]
Definition at line 301 of file mips-tdep.c.
References is_compact_addr().
Referenced by mips_pc_is_mips(), and mips_pc_isa().
static int is_octeon (struct gdbarch * gdbarch) [static]
Definition at line 1478 of file mips-tdep.c.
References gdbarch_bfd_arch_info().
Referenced by is_octeon_bbit_op().
static int is_octeon_bbit_op (int op, struct gdbarch * gdbarch) [static]
Definition at line 1490 of file mips-tdep.c.
References is_octeon().
Referenced by mips32_instruction_has_delay_slot(), and mips32_next_pc().
static CORE_ADDR make_compact_addr (CORE_ADDR addr) [static]
Definition at line 333 of file mips-tdep.c.
Referenced by mips_eabi_push_dummy_call(), mips_o64_push_dummy_call(), mips_push_dummy_code(), and mips_write_pc().
static CORE_ADDR micromips_bc1_pc (struct gdbarch * gdbarch, struct frame_info * frame, ULONGEST insn, CORE_ADDR pc, int count) [static]
Definition at line 1746 of file mips-tdep.c.
References b2s3_cc, b5s5_op, mips_regnum::fp_control_status, get_frame_register_unsigned(), micromips_pc_insn_size(), micromips_relative_offset16(), mips_regnum(), gdbarch_tdep::pc, and ULONGEST.
Referenced by micromips_next_pc().
static int micromips_deal_with_atomic_sequence (struct gdbarch * gdbarch, struct address_space * aspace, CORE_ADDR pc) [static]
Definition at line 3792 of file mips-tdep.c.
References b0s6_op, b12s4_op, b5s5_op, b6s10_ext, insert_single_step_breakpoint(), is_branch(), ISA_MICROMIPS, micromips_op, micromips_relative_offset16(), micromips_relative_offset7(), mips_fetch_instruction(), MIPS_INSN16_SIZE, mips_insn_size(), gdbarch_tdep::pc, and ULONGEST.
Referenced by deal_with_atomic_sequence().
static int micromips_decode_imm9 (int imm) [static]
Definition at line 2748 of file mips-tdep.c.
Referenced by heuristic_proc_start(), micromips_in_function_epilogue_p(), and micromips_scan_prologue().
static int micromips_in_function_epilogue_p (struct gdbarch * gdbarch, CORE_ADDR pc) [static]
Definition at line 6482 of file mips-tdep.c.
References b0s16_imm, b0s5_reg, b1s9_imm, b5s5_op, b5s5_reg, find_pc_partial_function(), ISA_MICROMIPS, micromips_decode_imm9(), micromips_op, mips_fetch_instruction(), MIPS_INSN16_SIZE, mips_insn_size(), MIPS_RA_REGNUM, MIPS_SP_REGNUM, offset, and ULONGEST.
Referenced by mips_in_function_epilogue_p().
static int micromips_instruction_has_delay_slot (struct gdbarch * gdbarch, CORE_ADDR addr, int mustbe32) [static]
Definition at line 7036 of file mips-tdep.c.
References b0s6_op, b5s5_op, b6s10_ext, ISA_MICROMIPS, micromips_op, mips_fetch_instruction(), exsummary::status, and ULONGEST.
Referenced by mips_adjust_breakpoint_address(), and mips_single_step_through_delay().
static CORE_ADDR micromips_next_pc (struct frame_info * frame, CORE_ADDR pc) [static]
Definition at line 1775 of file mips-tdep.c.
References b0s26_imm, b0s5_reg, b0s6_op, b5s5_op, b5s5_reg, b6s10_ext, b7s3_reg, mips_regnum::dspctl, get_frame_arch(), get_frame_register_signed(), get_frame_register_unsigned(), ISA_MICROMIPS, micromips_bc1_pc(), micromips_op, micromips_pc_insn_size(), micromips_relative_offset10(), micromips_relative_offset16(), micromips_relative_offset7(), mips_fetch_instruction(), MIPS_INSN16_SIZE, mips_insn_size(), MIPS_RA_REGNUM, mips_regnum(), and ULONGEST.
Referenced by mips_next_pc().
static int micromips_pc_insn_size (struct gdbarch * gdbarch, CORE_ADDR pc) [static]
Definition at line 1732 of file mips-tdep.c.
References ISA_MICROMIPS, mips_fetch_instruction(), mips_insn_size(), and ULONGEST.
Referenced by micromips_bc1_pc(), and micromips_next_pc().
static LONGEST micromips_relative_offset10 (ULONGEST insn) [static]
Definition at line 1715 of file mips-tdep.c.
References b0s10_imm.
Referenced by micromips_next_pc().
static LONGEST micromips_relative_offset16 (ULONGEST insn) [static]
Definition at line 1724 of file mips-tdep.c.
References b0s16_imm.
Referenced by micromips_bc1_pc(), micromips_deal_with_atomic_sequence(), and micromips_next_pc().
static LONGEST micromips_relative_offset7 (ULONGEST insn) [static]
Definition at line 1706 of file mips-tdep.c.
References b0s7_imm.
Referenced by micromips_deal_with_atomic_sequence(), and micromips_next_pc().
static CORE_ADDR micromips_scan_prologue (struct gdbarch * gdbarch, CORE_ADDR start_pc, CORE_ADDR limit_pc, struct frame_info * this_frame, struct mips_frame_cache * this_cache) [static]
Definition at line 2760 of file mips-tdep.c.
References b0s11_op, b0s12_imm, b0s16_imm, b0s4_imm, b0s5_imm, b0s5_reg, b11s5_reg, b12s4_op, b1s4_imm, b1s9_imm, b4s2_regl, b5s5_op, b5s5_reg, b6s4_op, mips_frame_cache::base, gdbarch_num_regs(), get_frame_register_signed(), ISA_MICROMIPS, micromips_decode_imm9(), micromips_op, min, mips_fetch_instruction(), MIPS_INSN16_SIZE, mips_insn_size(), MIPS_RA_REGNUM, mips_regnum(), MIPS_SP_REGNUM, MIPS_T9_REGNUM, offset, mips_regnum::pc, mips_frame_cache::saved_regs, set_reg_offset(), sp, and ULONGEST.
Referenced by mips_micro_frame_cache(), and mips_skip_prologue().
static int mips16_get_imm (unsigned short prev_inst, unsigned short inst, int nbits, int scale, int is_signed) [static]
Definition at line 2299 of file mips-tdep.c.
References offset.
Referenced by mips16_scan_prologue().
static int mips16_in_function_epilogue_p (struct gdbarch * gdbarch, CORE_ADDR pc) [static]
Definition at line 6582 of file mips-tdep.c.
References find_pc_partial_function(), ISA_MIPS16, mips_fetch_instruction(), and MIPS_INSN16_SIZE.
Referenced by mips_in_function_epilogue_p().
static int mips16_instruction_has_delay_slot (struct gdbarch * gdbarch, CORE_ADDR addr, int mustbe32) [static]
Definition at line 7103 of file mips-tdep.c.
References ISA_MIPS16, mips_fetch_instruction(), and exsummary::status.
Referenced by mips_adjust_breakpoint_address(), and mips_single_step_through_delay().
static CORE_ADDR mips16_next_pc (struct frame_info * frame, CORE_ADDR pc) [static]
Definition at line 2236 of file mips-tdep.c.
References extended_mips16_next_pc(), fetch_mips_16(), and get_frame_arch().
Referenced by mips_next_pc().
static CORE_ADDR mips16_scan_prologue (struct gdbarch * gdbarch, CORE_ADDR start_pc, CORE_ADDR limit_pc, struct frame_info * this_frame, struct mips_frame_cache * this_cache) [static]
Definition at line 2333 of file mips-tdep.c.
References _, mips_frame_cache::base, gdbarch_num_regs(), get_frame_register_signed(), ISA_MIPS16, mips16_get_imm(), MIPS_A0_REGNUM, mips_abi_regsize(), mips_fetch_instruction(), MIPS_INSN16_SIZE, MIPS_RA_REGNUM, mips_regnum(), MIPS_SP_REGNUM, offset, mips_regnum::pc, mips_frame_cache::saved_regs, set_reg_offset(), sp, and warning().
Referenced by mips_insn16_frame_cache(), and mips_skip_prologue().
static int mips2_fp_compat (struct frame_info * frame) [static]
Definition at line 459 of file mips-tdep.c.
References get_frame_arch(), get_frame_register_unsigned(), MIPS_PS_REGNUM, register_size(), and ST0_FR.
Referenced by mips_print_fp_register(), and mips_read_fp_register_double().
static CORE_ADDR mips32_bc1_pc (struct gdbarch * gdbarch, struct frame_info * frame, ULONGEST inst, CORE_ADDR pc, int count) [static]
Definition at line 1450 of file mips-tdep.c.
References mips_regnum::fp_control_status, get_frame_register_unsigned(), itype_rt, mips32_relative_offset(), mips_regnum(), and ULONGEST.
Referenced by mips32_next_pc().
static int mips32_in_function_epilogue_p (struct gdbarch * gdbarch, CORE_ADDR pc) [static]
Definition at line 6443 of file mips-tdep.c.
References find_pc_partial_function(), ISA_MIPS, mips_fetch_instruction(), and MIPS_INSN32_SIZE.
Referenced by mips_in_function_epilogue_p().
static int mips32_instruction_has_delay_slot (struct gdbarch * gdbarch, CORE_ADDR addr) [static]
Definition at line 6980 of file mips-tdep.c.
References is_octeon_bbit_op(), ISA_MIPS, itype_op, itype_rs, itype_rt, mips_fetch_instruction(), rtype_funct, and exsummary::status.
Referenced by mips_adjust_breakpoint_address(), and mips_single_step_through_delay().
static CORE_ADDR mips32_next_pc (struct frame_info * frame, CORE_ADDR pc) [static]
Definition at line 1508 of file mips-tdep.c.
References bit, mips_regnum::dspctl, gdbarch_tdep(), get_frame_arch(), get_frame_register_signed(), get_frame_register_unsigned(), is_octeon_bbit_op(), ISA_MIPS, itype_op, itype_rs, itype_rt, jtype_target, mips32_bc1_pc(), mips32_relative_offset(), mips_fetch_instruction(), mips_regnum(), gdbarch_tdep::pc, rtype_funct, rtype_rs, and gdbarch_tdep::syscall_next_pc.
Referenced by mips_next_pc().
static LONGEST mips32_relative_offset (ULONGEST inst) [static]
Definition at line 1440 of file mips-tdep.c.
References itype_immediate.
Referenced by mips32_bc1_pc(), mips32_next_pc(), and mips_deal_with_atomic_sequence().
static CORE_ADDR mips32_scan_prologue (struct gdbarch * gdbarch, CORE_ADDR start_pc, CORE_ADDR limit_pc, struct frame_info * this_frame, struct mips_frame_cache * this_cache) [static]
Definition at line 3200 of file mips-tdep.c.
References mips_frame_cache::base, gdbarch_num_regs(), get_frame_register_signed(), ISA_MIPS, itype_op, gdb::printing::long, mips_abi_regsize(), mips_fetch_instruction(), MIPS_INSN32_SIZE, MIPS_RA_REGNUM, mips_regnum(), MIPS_SP_REGNUM, mips_regnum::pc, reset_saved_regs(), rtype_funct, mips_frame_cache::saved_regs, set_reg_offset(), and sp.
Referenced by mips_insn32_frame_cache(), and mips_skip_prologue().
enum mips_abi mips_abi (struct gdbarch * gdbarch)
Definition at line 228 of file mips-tdep.c.
References gdbarch_tdep(), and gdbarch_tdep::mips_abi.
unsigned int mips_abi_regsize (struct gdbarch * gdbarch)
Definition at line 250 of file mips-tdep.c.
References _, internal_error(), MIPS_ABI_EABI32, MIPS_ABI_EABI64, MIPS_ABI_LAST, MIPS_ABI_N32, MIPS_ABI_N64, MIPS_ABI_O32, MIPS_ABI_O64, and MIPS_ABI_UNKNOWN.
Referenced by mips16_scan_prologue(), mips32_scan_prologue(), mips_eabi_push_dummy_call(), mips_eabi_return_value(), mips_linux_register_u_offset(), mips_pseudo_register_type(), mips_register_type(), and print_gp_register_row().
static void mips_abi_update (char * ignore_args, int from_tty, struct cmd_list_element * c) [static]
Definition at line 8667 of file mips-tdep.c.
References gdbarch_info_init(), and gdbarch_update_p().
Referenced by _initialize_mips_tdep().
static int mips_about_to_return (struct gdbarch * gdbarch, CORE_ADDR pc) [static]
Definition at line 3989 of file mips-tdep.c.
References gdb_assert, ISA_MIPS, mips_fetch_instruction(), mips_pc_is_mips(), and ULONGEST.
Referenced by heuristic_proc_start().
static CORE_ADDR mips_addr_bits_remove (struct gdbarch * gdbarch, CORE_ADDR addr) [static]
Definition at line 3651 of file mips-tdep.c.
References gdbarch_tdep(), is_compact_addr(), mips_mask_address_p(), ULONGEST, and unmake_compact_addr().
Referenced by mips_gdbarch_init().
static CORE_ADDR mips_adjust_breakpoint_address (struct gdbarch * gdbarch, CORE_ADDR bpaddr) [static]
Definition at line 7158 of file mips-tdep.c.
References find_pc_partial_function(), int, micromips_instruction_has_delay_slot(), mips16_instruction_has_delay_slot(), mips32_instruction_has_delay_slot(), MIPS_INSN16_SIZE, mips_pc_is_micromips(), mips_pc_is_mips(), mips_segment_boundary(), and unmake_compact_addr().
Referenced by mips_gdbarch_init().
static int mips_ax_pseudo_register_collect (struct gdbarch * gdbarch, struct agent_expr * ax, int reg) [static]
Definition at line 748 of file mips-tdep.c.
References ax_reg_mask(), gdb_assert, and gdbarch_num_regs().
Referenced by mips_gdbarch_init().
static int mips_ax_pseudo_register_push_stack (struct gdbarch * gdbarch, struct agent_expr * ax, int reg) [static]
Definition at line 761 of file mips-tdep.c.
References _, ax_const_l(), ax_reg(), ax_simple(), gdb_assert, gdbarch_byte_order(), gdbarch_num_regs(), internal_error(), mips64_transfers_32bit_regs_p, and register_size().
Referenced by mips_gdbarch_init().
static const gdb_byte* mips_breakpoint_from_pc (struct gdbarch * gdbarch, CORE_ADDR * pcptr, int * lenptr) [static]
Definition at line 6837 of file mips-tdep.c.
References GDB_OSABI_IRIX, gdbarch_byte_order(), gdbarch_osabi(), ISA_MICROMIPS, mips_fetch_instruction(), mips_insn_size(), mips_pc_is_micromips(), mips_pc_is_mips16(), size, exsummary::status, target_shortname, ULONGEST, and unmake_compact_addr().
Referenced by mips_gdbarch_init().
static int mips_convert_register_float_case_p (struct gdbarch * gdbarch, int regnum, struct type * type) [static]
Definition at line 827 of file mips-tdep.c.
References gdbarch_byte_order(), mips_float_register_p(), register_size(), TYPE_CODE, TYPE_CODE_FLT, and TYPE_LENGTH.
Referenced by mips_convert_register_p(), mips_register_to_value(), and mips_value_to_register().
static int mips_convert_register_gpreg_case_p (struct gdbarch * gdbarch, int regnum, struct type * type) [static]
Definition at line 840 of file mips-tdep.c.
References gdbarch_num_regs(), register_size(), and TYPE_LENGTH.
Referenced by mips_convert_register_p(), mips_register_to_value(), and mips_value_to_register().
static int mips_convert_register_p (struct gdbarch * gdbarch, int regnum, struct type * type) [static]
Definition at line 851 of file mips-tdep.c.
References mips_convert_register_float_case_p(), and mips_convert_register_gpreg_case_p().
Referenced by mips_gdbarch_init().
static int mips_deal_with_atomic_sequence (struct gdbarch * gdbarch, struct address_space * aspace, CORE_ADDR pc) [static]
Definition at line 3693 of file mips-tdep.c.
References insert_single_step_breakpoint(), is_branch(), ISA_MIPS, itype_op, itype_rs, itype_rt, LL_OPCODE, LLD_OPCODE, mips32_relative_offset(), mips_fetch_instruction(), MIPS_INSN32_SIZE, gdbarch_tdep::pc, rtype_funct, SC_OPCODE, SCD_OPCODE, and ULONGEST.
Referenced by deal_with_atomic_sequence().
static struct frame_id mips_dummy_id (struct gdbarch * gdbarch, struct frame_info * this_frame) [static, read]
Definition at line 1305 of file mips-tdep.c.
References frame_id_build(), gdbarch_num_regs(), get_frame_pc(), get_frame_register_signed(), and MIPS_SP_REGNUM.
Referenced by mips_gdbarch_init().
static void mips_dump_tdep (struct gdbarch * gdbarch, struct ui_file * file) [static]
Definition at line 8728 of file mips-tdep.c.
References gdbarch_tdep::default_mask_address_p, gdbarch_tdep::elf_flags, fprintf_unfiltered(), gdbarch_tdep(), gdbarch_tdep::mips_abi, mips_abi_strings, MIPS_DEFAULT_FPU_TYPE, MIPS_EABI, MIPS_FPU_DOUBLE, MIPS_FPU_NONE, MIPS_FPU_SINGLE, MIPS_FPU_TYPE, and mips_mask_address_p().
Referenced by _initialize_mips_tdep().
static int mips_dwarf_dwarf2_ecoff_reg_to_regnum (struct gdbarch * gdbarch, int num) [static]
Definition at line 7745 of file mips-tdep.c.
References mips_regnum::dspacc, mips_regnum::fp0, gdbarch_num_pseudo_regs(), gdbarch_num_regs(), mips_regnum::hi, mips_regnum::lo, mips_regnum(), and regnum.
Referenced by mips_gdbarch_init().
static CORE_ADDR mips_eabi_push_dummy_call (struct gdbarch * gdbarch, struct value * function, struct regcache * regcache, CORE_ADDR bp_addr, int nargs, struct value ** args, CORE_ADDR sp, int struct_return, CORE_ADDR struct_addr) [static]
Definition at line 4281 of file mips-tdep.c.
References align_down(), align_up(), check_typedef(), extract_signed_integer(), find_function_addr(), fp_register_arg_p(), fprintf_filtered(), fprintf_unfiltered(), gdb_stdlog, gdbarch_byte_order(), len, LONGEST, make_compact_addr(), MAX_REGISTER_SIZE, MIPS_A0_REGNUM, MIPS_ABI_EABI32, mips_abi_regsize(), mips_debug, mips_fpa0_regnum(), MIPS_LAST_ARG_REGNUM, MIPS_LAST_FP_ARG_REGNUM, mips_pc_is_mips(), MIPS_RA_REGNUM, MIPS_SP_REGNUM, MIPS_T9_REGNUM, paddress(), phex(), regcache_cooked_write_signed(), regcache_cooked_write_unsigned(), store_signed_integer(), store_unsigned_integer(), TYPE_CODE, TYPE_CODE_FLT, TYPE_CODE_FUNC, TYPE_CODE_INT, TYPE_CODE_PTR, TYPE_CODE_STRUCT, TYPE_CODE_UNION, TYPE_LENGTH, TYPE_TARGET_TYPE, value_address(), value_contents(), value_type(), and write_memory().
Referenced by mips_gdbarch_init().
static enum return_value_convention mips_eabi_return_value (struct gdbarch * gdbarch, struct value * function, struct type * type, struct regcache * regcache, gdb_byte * readbuf, const gdb_byte * writebuf) [static]
Definition at line 4570 of file mips-tdep.c.
References check_typedef(), mips_regnum::fp0, fprintf_unfiltered(), gdb_stderr, gdbarch_byte_order(), gdbarch_num_regs(), gdbarch_tdep(), mips_abi_regsize(), mips_debug, MIPS_FPU_NONE, gdbarch_tdep::mips_fpu_type, mips_regnum(), MIPS_V0_REGNUM, mips_xfer_register(), offset, regnum, RETURN_VALUE_REGISTER_CONVENTION, RETURN_VALUE_STRUCT_CONVENTION, TYPE_CODE, TYPE_CODE_FLT, TYPE_CODE_STRUCT, TYPE_CODE_UNION, TYPE_FIELD_TYPE, TYPE_LENGTH, and TYPE_NFIELDS.
Referenced by mips_gdbarch_init().
static void mips_elf_make_msymbol_special (asymbol * sym, struct minimal_symbol * msym) [static]
Definition at line 354 of file mips-tdep.c.
References MSYMBOL_TARGET_FLAG_1, and MSYMBOL_TARGET_FLAG_2.
Referenced by mips_gdbarch_init().
static ULONGEST mips_fetch_instruction (struct gdbarch * gdbarch, enum mips_isa isa, CORE_ADDR addr, int * statusp) [static]
Definition at line 1331 of file mips-tdep.c.
References _, extract_unsigned_integer(), gdbarch_byte_order(), internal_error(), ISA_MICROMIPS, ISA_MIPS, ISA_MIPS16, memory_error(), MIPS_INSN16_SIZE, MIPS_INSN32_SIZE, exsummary::status, target_read_memory(), and unmake_compact_addr().
Referenced by heuristic_proc_start(), micromips_deal_with_atomic_sequence(), micromips_in_function_epilogue_p(), micromips_instruction_has_delay_slot(), micromips_next_pc(), micromips_pc_insn_size(), micromips_scan_prologue(), mips16_in_function_epilogue_p(), mips16_instruction_has_delay_slot(), mips16_scan_prologue(), mips32_in_function_epilogue_p(), mips32_instruction_has_delay_slot(), mips32_next_pc(), mips32_scan_prologue(), mips_about_to_return(), mips_breakpoint_from_pc(), mips_deal_with_atomic_sequence(), mips_get_mips16_fn_stub_pc(), mips_remote_breakpoint_from_pc(), mips_single_step_through_delay(), and unpack_mips16().
static void mips_find_abi_section (bfd * abfd, asection * sect, void * obj) [static]
Definition at line 7809 of file mips-tdep.c.
References _, MIPS_ABI_EABI32, MIPS_ABI_EABI64, MIPS_ABI_N32, MIPS_ABI_N64, MIPS_ABI_O32, MIPS_ABI_O64, MIPS_ABI_UNKNOWN, name, and warning().
Referenced by mips_gdbarch_init().
static void mips_find_long_section (bfd * abfd, asection * sect, void * obj) [static]
Definition at line 7837 of file mips-tdep.c.
References _, name, and warning().
Referenced by mips_gdbarch_init().
static int mips_float_register_p (struct gdbarch * gdbarch, int regnum) [static]
Definition at line 206 of file mips-tdep.c.
References mips_regnum::fp0, and gdbarch_num_regs().
Referenced by mips_convert_register_float_case_p(), mips_print_register(), mips_print_registers_info(), mips_pseudo_register_type(), mips_register_type(), and print_gp_register_row().
static int mips_fpa0_regnum (struct gdbarch * gdbarch) [static]
Definition at line 197 of file mips-tdep.c.
References mips_regnum::fp0, and mips_regnum().
Referenced by mips_eabi_push_dummy_call(), mips_n32n64_push_dummy_call(), mips_o32_push_dummy_call(), and mips_o64_push_dummy_call().
static CORE_ADDR mips_frame_align (struct gdbarch * gdbarch, CORE_ADDR addr) [static]
Definition at line 4236 of file mips-tdep.c.
References align_down().
Referenced by mips_gdbarch_init(), and mips_push_dummy_code().
static struct gdbarch* mips_gdbarch_init (struct gdbarch_info info, struct gdbarch_list * arches) [static, read]
Definition at line 7904 of file mips-tdep.c.
References _, gdbarch_info::abfd, address_to_signed_pointer(), mips_regnum::badvaddr, gdbarch_info::bfd_arch_info, mips_regnum::cause, core_addr_lessthan(), gdbarch_tdep::default_mask_address_p, mips_regnum::dspacc, mips_regnum::dspctl, dwarf2_append_unwinders(), dwarf2_frame_base_sniffer(), gdbarch_tdep::elf_flags, floatformats_ibm_long_double, gdbarch_tdep::found_abi, mips_regnum::fp0, mips_regnum::fp_control_status, mips_regnum::fp_implementation_revision, gdbarch_tdep::fpregset, gdbarch_tdep::fpregset64, fprintf_unfiltered(), frame_base_append_sniffer(), frame_unwind_append_unwinder(), GDB_OSABI_IRIX, GDB_OSABI_LINUX, gdb_print_insn_mips(), gdb_print_insn_mips_n32(), gdb_print_insn_mips_n64(), gdb_stdlog, gdbarch_list::gdbarch, gdbarch_alloc(), gdbarch_debug, gdbarch_init_osabi(), gdbarch_list_lookup_by_info(), gdbarch_num_regs(), GDBARCH_OBSTACK_ZALLOC, gdbarch_tdep(), global_mips_abi(), global_mips_compression(), gdbarch_tdep::gregset, gdbarch_tdep::gregset64, mips_regnum::hi, internal_error(), ISA_MICROMIPS, ISA_MIPS16, mips_regnum::lo, gdbarch_tdep::mips64_transfers_32bit_regs_p, mips64_transfers_32bit_regs_p, MIPS_A0_REGNUM, gdbarch_tdep::mips_abi, MIPS_ABI_EABI32, MIPS_ABI_EABI64, MIPS_ABI_N32, MIPS_ABI_N64, MIPS_ABI_O32, MIPS_ABI_O64, MIPS_ABI_UNKNOWN, mips_addr_bits_remove(), mips_adjust_breakpoint_address(), mips_ax_pseudo_register_collect(), mips_ax_pseudo_register_push_stack(), mips_breakpoint_from_pc(), mips_compression_string, mips_compression_strings, mips_convert_register_p(), mips_dummy_id(), mips_dwarf_dwarf2_ecoff_reg_to_regnum(), mips_eabi_push_dummy_call(), mips_eabi_return_value(), mips_elf_make_msymbol_special(), MIPS_EMBED_BADVADDR_REGNUM, MIPS_EMBED_CAUSE_REGNUM, MIPS_EMBED_FP0_REGNUM, MIPS_EMBED_HI_REGNUM, MIPS_EMBED_LO_REGNUM, MIPS_EMBED_PC_REGNUM, mips_find_abi_section(), mips_find_long_section(), MIPS_FPU_DOUBLE, MIPS_FPU_NONE, MIPS_FPU_SINGLE, gdbarch_tdep::mips_fpu_type, mips_fpu_type_auto, mips_frame_align(), mips_generic_reg_names, mips_in_function_epilogue_p(), mips_in_return_stub(), mips_insn16_frame_base_sniffer(), mips_insn32_frame_base_sniffer(), mips_integer_to_address(), mips_irix_reg_names, gdbarch_tdep::mips_isa, gdbarch_tdep::mips_last_arg_regnum, MIPS_LAST_EMBED_REGNUM, gdbarch_tdep::mips_last_fp_arg_regnum, mips_linux_reg_names, mips_micro_frame_base_sniffer(), mips_n32n64_push_dummy_call(), mips_n32n64_return_value(), mips_o32_push_dummy_call(), mips_o32_return_value(), mips_o64_push_dummy_call(), mips_o64_return_value(), mips_print_registers_info(), gdbarch_tdep::mips_processor_reg_names, MIPS_PS_REGNUM, mips_pseudo_register_read(), mips_pseudo_register_type(), mips_pseudo_register_write(), mips_push_dummy_code(), MIPS_RA_REGNUM, mips_read_pc(), mips_register_g_packet_guesses(), mips_register_name(), mips_register_reggroup_p(), mips_register_sim_regno(), mips_register_to_value(), mips_register_type(), mips_regnum(), mips_remote_breakpoint_from_pc(), mips_single_step_through_delay(), mips_skip_prologue(), mips_skip_trampoline_code(), MIPS_SP_REGNUM, mips_stab_reg_to_regnum(), mips_stub_frame_base_sniffer(), mips_tdesc_register_reggroup_p(), mips_tx39_reg_names, mips_unwind_pc(), mips_unwind_sp(), mips_value_to_register(), mips_virtual_frame_pointer(), mips_write_pc(), MIPS_ZERO_REGNUM, name, gdbarch_list::next, gdbarch_tdep::num_regs, ON_STACK, gdbarch_info::osabi, mips_regnum::pc, PROPERTY_GP32, PROPERTY_GP64, gdbarch_tdep::register_size, gdbarch_tdep::register_size_valid_p, regnum, gdbarch_tdep::regnum, set_gdbarch_addr_bits_remove(), set_gdbarch_address_to_pointer(), set_gdbarch_adjust_breakpoint_address(), set_gdbarch_ax_pseudo_register_collect(), set_gdbarch_ax_pseudo_register_push_stack(), set_gdbarch_breakpoint_from_pc(), set_gdbarch_call_dummy_location(), set_gdbarch_convert_register_p(), set_gdbarch_double_bit(), set_gdbarch_dummy_id(), set_gdbarch_dwarf2_reg_to_regnum(), set_gdbarch_ecoff_reg_to_regnum(), set_gdbarch_elf_make_msymbol_special(), set_gdbarch_float_bit(), set_gdbarch_fp0_regnum(), set_gdbarch_frame_align(), set_gdbarch_have_nonsteppable_watchpoint(), set_gdbarch_in_function_epilogue_p(), set_gdbarch_in_solib_return_trampoline(), set_gdbarch_inner_than(), set_gdbarch_int_bit(), set_gdbarch_integer_to_address(), set_gdbarch_long_bit(), set_gdbarch_long_double_bit(), set_gdbarch_long_double_format(), set_gdbarch_long_long_bit(), set_gdbarch_num_pseudo_regs(), set_gdbarch_num_regs(), set_gdbarch_pc_regnum(), set_gdbarch_pointer_to_address(), set_gdbarch_print_insn(), set_gdbarch_print_registers_info(), set_gdbarch_pseudo_register_read(), set_gdbarch_pseudo_register_write(), set_gdbarch_ptr_bit(), set_gdbarch_push_dummy_call(), set_gdbarch_push_dummy_code(), set_gdbarch_read_pc(), set_gdbarch_register_name(), set_gdbarch_register_reggroup_p(), set_gdbarch_register_sim_regno(), set_gdbarch_register_to_value(), set_gdbarch_register_type(), set_gdbarch_remote_breakpoint_from_pc(), set_gdbarch_return_value(), set_gdbarch_short_bit(), set_gdbarch_single_step_through_delay(), set_gdbarch_skip_prologue(), set_gdbarch_skip_trampoline_code(), set_gdbarch_sp_regnum(), set_gdbarch_stab_reg_to_regnum(), set_gdbarch_unwind_pc(), set_gdbarch_unwind_sp(), set_gdbarch_value_to_register(), set_gdbarch_vbit_in_delta(), set_gdbarch_virtual_frame_pointer(), set_gdbarch_write_pc(), set_tdesc_pseudo_register_type(), signed_pointer_to_address(), gdbarch_info::target_desc, gdbarch_info::tdep_info, tdesc_data, tdesc_data_alloc(), tdesc_data_cleanup(), tdesc_find_feature(), tdesc_has_registers(), tdesc_numbered_register(), tdesc_property(), tdesc_use_registers(), user_reg_add(), value_of_mips_user_reg(), and xmalloc().
Referenced by _initialize_mips_tdep().
static CORE_ADDR mips_get_mips16_fn_stub_pc (struct frame_info * frame, CORE_ADDR pc) [static]
Definition at line 7373 of file mips-tdep.c.
References gdbarch::byte_order, extract_signed_integer(), gdbarch_byte_order(), get_frame_arch(), ISA_MIPS, itype_immediate, itype_op, itype_rs, itype_rt, jtype_target, memset(), mips_fetch_instruction(), MIPS_GP_REGNUM, MIPS_INSN32_SIZE, MIPS_T9_REGNUM, MIPS_ZERO_REGNUM, rtype_funct, rtype_rd, rtype_rs, rtype_rt, exsummary::status, target_read_memory(), and ULONGEST.
Referenced by mips_skip_mips16_trampoline_code().
static int mips_in_frame_stub (CORE_ADDR pc) [static]
Definition at line 1224 of file mips-tdep.c.
References find_pc_partial_function(), and name.
Referenced by mips_unwind_pc().
static int mips_in_function_epilogue_p (struct gdbarch * gdbarch, CORE_ADDR pc) [static]
Definition at line 6622 of file mips-tdep.c.
References micromips_in_function_epilogue_p(), mips16_in_function_epilogue_p(), mips32_in_function_epilogue_p(), mips_pc_is_micromips(), and mips_pc_is_mips16().
Referenced by mips_gdbarch_init().
static int mips_in_return_stub (struct gdbarch * gdbarch, CORE_ADDR pc, const char * name) [static]
Definition at line 7574 of file mips-tdep.c.
References find_pc_partial_function(), mips_is_stub_mode(), and mips_is_stub_suffix().
Referenced by mips_gdbarch_init().
static CORE_ADDR mips_insn16_frame_base_address (struct frame_info * this_frame, void ** this_cache) [static]
Definition at line 2716 of file mips-tdep.c.
References mips_frame_cache::base, and mips_insn16_frame_cache().
static struct frame_base* mips_insn16_frame_base_sniffer (struct frame_info * this_frame) [static, read]
Definition at line 2733 of file mips-tdep.c.
References get_frame_arch(), get_frame_pc(), mips_insn16_frame_base, and mips_pc_is_mips16().
Referenced by mips_gdbarch_init().
static struct mips_frame_cache* mips_insn16_frame_cache (struct frame_info * this_frame, void ** this_cache) [static, read]
Definition at line 2638 of file mips-tdep.c.
References mips_frame_cache::base, find_pc_partial_function(), FRAME_OBSTACK_ZALLOC, gdbarch_num_regs(), get_frame_address_in_block(), get_frame_arch(), heuristic_proc_start(), mips16_scan_prologue(), MIPS_SP_REGNUM, mips_frame_cache::saved_regs, trad_frame_alloc_saved_regs(), and trad_frame_set_value().
Referenced by mips_insn16_frame_base_address(), mips_insn16_frame_prev_register(), and mips_insn16_frame_this_id().
static struct value* mips_insn16_frame_prev_register (struct frame_info * this_frame, void ** this_cache, int regnum) [static, read]
Definition at line 2686 of file mips-tdep.c.
References mips_insn16_frame_cache(), mips_frame_cache::saved_regs, and trad_frame_get_prev_register().
static int mips_insn16_frame_sniffer (const struct frame_unwind * self, struct frame_info * this_frame, void ** this_cache) [static]
Definition at line 2695 of file mips-tdep.c.
References get_frame_arch(), get_frame_pc(), and mips_pc_is_mips16().
static void mips_insn16_frame_this_id (struct frame_info * this_frame, void ** this_cache, struct frame_id * this_id) [static]
Definition at line 2674 of file mips-tdep.c.
References mips_frame_cache::base, frame_id_build(), get_frame_func(), and mips_insn16_frame_cache().
static CORE_ADDR mips_insn32_frame_base_address (struct frame_info * this_frame, void ** this_cache) [static]
Definition at line 3506 of file mips-tdep.c.
References mips_frame_cache::base, and mips_insn32_frame_cache().
static struct frame_base* mips_insn32_frame_base_sniffer (struct frame_info * this_frame) [static, read]
Definition at line 3523 of file mips-tdep.c.
References get_frame_pc(), mips_insn32_frame_base, and mips_pc_is_mips().
Referenced by mips_gdbarch_init().
static struct mips_frame_cache* mips_insn32_frame_cache (struct frame_info * this_frame, void ** this_cache) [static, read]
Definition at line 3428 of file mips-tdep.c.
References mips_frame_cache::base, find_pc_partial_function(), FRAME_OBSTACK_ZALLOC, gdbarch_num_regs(), get_frame_address_in_block(), get_frame_arch(), heuristic_proc_start(), mips32_scan_prologue(), MIPS_SP_REGNUM, mips_frame_cache::saved_regs, trad_frame_alloc_saved_regs(), and trad_frame_set_value().
Referenced by mips_insn32_frame_base_address(), mips_insn32_frame_prev_register(), and mips_insn32_frame_this_id().
static struct value* mips_insn32_frame_prev_register (struct frame_info * this_frame, void ** this_cache, int regnum) [static, read]
Definition at line 3477 of file mips-tdep.c.
References mips_insn32_frame_cache(), mips_frame_cache::saved_regs, and trad_frame_get_prev_register().
static int mips_insn32_frame_sniffer (const struct frame_unwind * self, struct frame_info * this_frame, void ** this_cache) [static]
Definition at line 3486 of file mips-tdep.c.
References get_frame_pc(), and mips_pc_is_mips().
static void mips_insn32_frame_this_id (struct frame_info * this_frame, void ** this_cache, struct frame_id * this_id) [static]
Definition at line 3465 of file mips-tdep.c.
References mips_frame_cache::base, frame_id_build(), get_frame_func(), and mips_insn32_frame_cache().
static int mips_insn_size (enum mips_isa isa, ULONGEST insn) [static]
Definition at line 1416 of file mips-tdep.c.
References _, internal_error(), ISA_MICROMIPS, ISA_MIPS, ISA_MIPS16, micromips_op, MIPS_INSN16_SIZE, and MIPS_INSN32_SIZE.
Referenced by micromips_deal_with_atomic_sequence(), micromips_in_function_epilogue_p(), micromips_next_pc(), micromips_pc_insn_size(), micromips_scan_prologue(), mips_breakpoint_from_pc(), mips_remote_breakpoint_from_pc(), and mips_single_step_through_delay().
static CORE_ADDR mips_integer_to_address (struct gdbarch * gdbarch, struct type * type, const gdb_byte * buf) [static]
Definition at line 7788 of file mips-tdep.c.
References extract_signed_integer(), gdbarch_byte_order(), and TYPE_LENGTH.
Referenced by mips_gdbarch_init().
static int mips_is_stub_mode (const char * mode) [static]
Definition at line 7314 of file mips-tdep.c.
Referenced by mips_in_return_stub(), and mips_skip_mips16_trampoline_code().
static int mips_is_stub_suffix (const char * suffix, int zero) [static]
Definition at line 7292 of file mips-tdep.c.
Referenced by mips_in_return_stub(), and mips_skip_mips16_trampoline_code().
int mips_isa_regsize (struct gdbarch * gdbarch)
Definition at line 234 of file mips-tdep.c.
References bits_per_byte, gdbarch_bfd_arch_info(), gdbarch_tdep(), gdbarch_tdep::register_size, and gdbarch_tdep::register_size_valid_p.
Referenced by fetch_core_registers(), fill_fpregset(), fill_gregset(), mips_register_type(), mipsnbsd_fill_fpreg(), mipsnbsd_fill_reg(), mipsnbsd_regset_from_core_section(), mipsnbsd_supply_fpreg(), mipsnbsd_supply_fpregset(), mipsnbsd_supply_gregset(), mipsnbsd_supply_reg(), supply_fpregset(), and supply_gregset().
static int mips_mask_address_p (struct gdbarch_tdep * tdep) [static]
Definition at line 1074 of file mips-tdep.c.
References _, AUTO_BOOLEAN_AUTO, AUTO_BOOLEAN_FALSE, AUTO_BOOLEAN_TRUE, gdbarch_tdep::default_mask_address_p, and internal_error().
Referenced by mips_addr_bits_remove(), mips_dump_tdep(), and show_mask_address().
static CORE_ADDR mips_micro_frame_base_address (struct frame_info * this_frame, void ** this_cache) [static]
Definition at line 3147 of file mips-tdep.c.
References mips_frame_cache::base, and mips_micro_frame_cache().
static struct frame_base* mips_micro_frame_base_sniffer (struct frame_info * this_frame) [static, read]
Definition at line 3164 of file mips-tdep.c.
References get_frame_arch(), get_frame_pc(), mips_micro_frame_base, and mips_pc_is_micromips().
Referenced by mips_gdbarch_init().
static struct mips_frame_cache* mips_micro_frame_cache (struct frame_info * this_frame, void ** this_cache) [static, read]
Definition at line 3067 of file mips-tdep.c.
References mips_frame_cache::base, find_pc_partial_function(), FRAME_OBSTACK_ZALLOC, gdbarch_num_regs(), get_frame_address_in_block(), get_frame_arch(), heuristic_proc_start(), micromips_scan_prologue(), MIPS_SP_REGNUM, mips_frame_cache::saved_regs, trad_frame_alloc_saved_regs(), and trad_frame_set_value().
Referenced by mips_micro_frame_base_address(), mips_micro_frame_prev_register(), and mips_micro_frame_this_id().
static struct value* mips_micro_frame_prev_register (struct frame_info * this_frame, void ** this_cache, int regnum) [static, read]
Definition at line 3116 of file mips-tdep.c.
References mips_micro_frame_cache(), mips_frame_cache::saved_regs, and trad_frame_get_prev_register().
static int mips_micro_frame_sniffer (const struct frame_unwind * self, struct frame_info * this_frame, void ** this_cache) [static]
Definition at line 3125 of file mips-tdep.c.
References get_frame_arch(), get_frame_pc(), and mips_pc_is_micromips().
static void mips_micro_frame_this_id (struct frame_info * this_frame, void ** this_cache, struct frame_id * this_id) [static]
Definition at line 3104 of file mips-tdep.c.
References mips_frame_cache::base, frame_id_build(), get_frame_func(), and mips_micro_frame_cache().
static int mips_n32n64_fp_arg_chunk_p (struct gdbarch * gdbarch, struct type * arg_type, int offset) [static]
Definition at line 4638 of file mips-tdep.c.
References check_typedef(), field_is_static(), MIPS64_REGSIZE, MIPS_FPU_DOUBLE, MIPS_FPU_TYPE, TYPE_CODE, TYPE_CODE_FLT, TYPE_CODE_STRUCT, TYPE_FIELD, TYPE_FIELD_BITPOS, TYPE_FIELD_TYPE, TYPE_LENGTH, and TYPE_NFIELDS.
Referenced by mips_n32n64_push_dummy_call().
static CORE_ADDR mips_n32n64_push_dummy_call (struct gdbarch * gdbarch, struct value * function, struct regcache * regcache, CORE_ADDR bp_addr, int nargs, struct value ** args, CORE_ADDR sp, int struct_return, CORE_ADDR struct_addr) [static]
Definition at line 4688 of file mips-tdep.c.
References align_down(), align_up(), check_typedef(), extract_signed_integer(), extract_unsigned_integer(), find_function_addr(), fp_register_arg_p(), fprintf_filtered(), fprintf_unfiltered(), gdb_assert, gdb_stdlog, gdbarch_byte_order(), len, LONGEST, MIPS64_REGSIZE, MIPS_A0_REGNUM, mips_debug, mips_fpa0_regnum(), MIPS_LAST_ARG_REGNUM, mips_n32n64_fp_arg_chunk_p(), MIPS_RA_REGNUM, MIPS_SP_REGNUM, MIPS_T9_REGNUM, paddress(), phex(), regcache_cooked_write_signed(), regcache_cooked_write_unsigned(), TYPE_CODE, TYPE_CODE_INT, TYPE_CODE_PTR, TYPE_CODE_STRUCT, TYPE_CODE_UNION, TYPE_LENGTH, TYPE_UNSIGNED, value_contents(), value_type(), and write_memory().
Referenced by mips_gdbarch_init().
static enum return_value_convention mips_n32n64_return_value (struct gdbarch * gdbarch, struct value * function, struct type * type, struct regcache * regcache, gdb_byte * readbuf, const gdb_byte * writebuf) [static]
Definition at line 4959 of file mips-tdep.c.
References check_typedef(), FIELD_BITPOS, fprintf_unfiltered(), gdb_stderr, gdbarch_byte_order(), gdbarch_num_regs(), gdbarch_tdep(), MIPS64_REGSIZE, mips_debug, MIPS_FPU_NONE, gdbarch_tdep::mips_fpu_type, MIPS_V0_REGNUM, mips_xfer_register(), offset, register_size(), regnum, RETURN_VALUE_REGISTER_CONVENTION, RETURN_VALUE_STRUCT_CONVENTION, TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_FLT, TYPE_CODE_STRUCT, TYPE_CODE_UNION, TYPE_FIELD_TYPE, TYPE_FIELDS, TYPE_LENGTH, and TYPE_NFIELDS.
Referenced by mips_gdbarch_init().
static CORE_ADDR mips_next_pc (struct frame_info * frame, CORE_ADDR pc) [static]
Definition at line 2249 of file mips-tdep.c.
References get_frame_arch(), micromips_next_pc(), mips16_next_pc(), mips32_next_pc(), mips_pc_is_micromips(), and mips_pc_is_mips16().
Referenced by mips_software_single_step().
static CORE_ADDR mips_o32_push_dummy_call (struct gdbarch * gdbarch, struct value * function, struct regcache * regcache, CORE_ADDR bp_addr, int nargs, struct value ** args, CORE_ADDR sp, int struct_return, CORE_ADDR struct_addr) [static]
Definition at line 5144 of file mips-tdep.c.
References align_down(), align_up(), check_typedef(), extract_signed_integer(), extract_unsigned_integer(), find_function_addr(), fp_register_arg_p(), fprintf_filtered(), fprintf_unfiltered(), gdb_stdlog, gdbarch_byte_order(), len, LONGEST, MIPS32_REGSIZE, MIPS_A0_REGNUM, mips_debug, mips_fpa0_regnum(), MIPS_LAST_ARG_REGNUM, MIPS_LAST_FP_ARG_REGNUM, MIPS_RA_REGNUM, MIPS_SP_REGNUM, MIPS_T9_REGNUM, mips_type_needs_double_align(), paddress(), phex(), regcache_cooked_write_signed(), regcache_cooked_write_unsigned(), register_size(), TYPE_CODE, TYPE_CODE_STRUCT, TYPE_CODE_UNION, TYPE_LENGTH, value_contents(), value_type(), and write_memory().
Referenced by mips_gdbarch_init().
static enum return_value_convention mips_o32_return_value (struct gdbarch * gdbarch, struct value * function, struct type * type, struct regcache * regcache, gdb_byte * readbuf, const gdb_byte * writebuf) [static]
Definition at line 5454 of file mips-tdep.c.
References _, FIELD_BITPOS, find_function_addr(), fprintf_unfiltered(), gdb_assert, gdb_stderr, gdbarch_byte_order(), gdbarch_num_regs(), gdbarch_tdep(), internal_error(), MAX_REGISTER_SIZE, MIPS32_REGSIZE, mips_debug, MIPS_FPU_NONE, gdbarch_tdep::mips_fpu_type, mips_fval_both, mips_fval_fpr, mips_fval_gpr, mips_pc_is_mips16(), MIPS_V0_REGNUM, mips_xfer_register(), offset, register_size(), regnum, RETURN_VALUE_REGISTER_CONVENTION, RETURN_VALUE_STRUCT_CONVENTION, TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_FLT, TYPE_CODE_STRUCT, TYPE_CODE_UNION, TYPE_FIELD_TYPE, TYPE_FIELDS, TYPE_LENGTH, and TYPE_NFIELDS.
Referenced by mips_gdbarch_init().
static CORE_ADDR mips_o64_push_dummy_call (struct gdbarch * gdbarch, struct value * function, struct regcache * regcache, CORE_ADDR bp_addr, int nargs, struct value ** args, CORE_ADDR sp, int struct_return, CORE_ADDR struct_addr) [static]
Definition at line 5671 of file mips-tdep.c.
References align_down(), align_up(), check_typedef(), extract_signed_integer(), extract_unsigned_integer(), find_function_addr(), fp_register_arg_p(), fprintf_filtered(), fprintf_unfiltered(), gdb_stdlog, gdbarch_byte_order(), len, LONGEST, make_compact_addr(), MAX_REGISTER_SIZE, MIPS64_REGSIZE, MIPS_A0_REGNUM, mips_debug, mips_fpa0_regnum(), MIPS_LAST_ARG_REGNUM, MIPS_LAST_FP_ARG_REGNUM, mips_pc_is_mips(), MIPS_RA_REGNUM, MIPS_SP_REGNUM, MIPS_T9_REGNUM, paddress(), phex(), regcache_cooked_write_signed(), regcache_cooked_write_unsigned(), store_signed_integer(), TYPE_CODE, TYPE_CODE_FLT, TYPE_CODE_FUNC, TYPE_CODE_INT, TYPE_CODE_PTR, TYPE_CODE_STRUCT, TYPE_CODE_UNION, TYPE_LENGTH, TYPE_TARGET_TYPE, value_contents(), value_type(), and write_memory().
Referenced by mips_gdbarch_init().
static enum return_value_convention mips_o64_return_value (struct gdbarch * gdbarch, struct value * function, struct type * type, struct regcache * regcache, gdb_byte * readbuf, const gdb_byte * writebuf) [static]
Definition at line 5920 of file mips-tdep.c.
References find_function_addr(), fp_register_arg_p(), fprintf_unfiltered(), gdb_assert, gdb_stderr, gdbarch_byte_order(), gdbarch_num_regs(), gdbarch_tdep(), MIPS64_REGSIZE, mips_debug, mips_fval_both, mips_fval_fpr, mips_fval_gpr, mips_pc_is_mips16(), MIPS_V0_REGNUM, mips_xfer_register(), offset, regnum, RETURN_VALUE_REGISTER_CONVENTION, RETURN_VALUE_STRUCT_CONVENTION, TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_STRUCT, TYPE_CODE_UNION, and TYPE_LENGTH.
Referenced by mips_gdbarch_init().
int mips_pc_is_micromips (struct gdbarch * gdbarch, CORE_ADDR memaddr)
Definition at line 1158 of file mips-tdep.c.
References is_micromips_addr(), lookup_minimal_symbol_by_pc(), and msymbol_is_micromips().
Referenced by deal_with_atomic_sequence(), gdb_print_insn_mips(), heuristic_proc_start(), mips_adjust_breakpoint_address(), mips_breakpoint_from_pc(), mips_in_function_epilogue_p(), mips_micro_frame_base_sniffer(), mips_micro_frame_sniffer(), mips_next_pc(), mips_push_dummy_code(), mips_remote_breakpoint_from_pc(), mips_single_step_through_delay(), and mips_skip_prologue().
int mips_pc_is_mips (CORE_ADDR memaddr)
Definition at line 1122 of file mips-tdep.c.
References is_mips_addr(), lookup_minimal_symbol_by_pc(), and msymbol_is_mips().
Referenced by deal_with_atomic_sequence(), heuristic_proc_start(), mips_about_to_return(), mips_adjust_breakpoint_address(), mips_eabi_push_dummy_call(), mips_insn32_frame_base_sniffer(), mips_insn32_frame_sniffer(), mips_o64_push_dummy_call(), mips_single_step_through_delay(), and mips_write_pc().
int mips_pc_is_mips16 (struct gdbarch * gdbarch, CORE_ADDR memaddr)
Definition at line 1140 of file mips-tdep.c.
References is_mips16_addr(), lookup_minimal_symbol_by_pc(), and msymbol_is_mips16().
Referenced by gdb_print_insn_mips(), heuristic_proc_start(), mips_breakpoint_from_pc(), mips_in_function_epilogue_p(), mips_insn16_frame_base_sniffer(), mips_insn16_frame_sniffer(), mips_next_pc(), mips_o32_return_value(), mips_o64_return_value(), mips_remote_breakpoint_from_pc(), mips_single_step_through_delay(), and mips_skip_prologue().
static enum mips_isa mips_pc_isa (struct gdbarch * gdbarch, CORE_ADDR memaddr) [static]
Definition at line 1178 of file mips-tdep.c.
References is_micromips_addr(), is_mips_addr(), ISA_MICROMIPS, ISA_MIPS, ISA_MIPS16, lookup_minimal_symbol_by_pc(), msymbol_is_micromips(), and msymbol_is_mips16().
Referenced by mips_single_step_through_delay().
static void mips_print_fp_register (struct ui_file * file, struct frame_info * frame, int regnum) [static]
Definition at line 6102 of file mips-tdep.c.
References fprintf_filtered(), gdbarch_num_regs(), gdbarch_register_name(), get_formatted_print_options(), get_frame_arch(), mips2_fp_compat(), mips_read_fp_register_double(), mips_read_fp_register_single(), print_scalar_formatted(), register_size(), and unpack_double().
Referenced by mips_print_register(), and print_fp_register_row().
static void mips_print_register (struct ui_file * file, struct frame_info * frame, int regnum) [static]
Definition at line 6185 of file mips-tdep.c.
References fprintf_filtered(), fputs_filtered(), gdbarch_register_name(), get_formatted_print_options(), get_frame_arch(), get_frame_register_value(), mips_float_register_p(), MIPS_NUMREGS, mips_print_fp_register(), val_print_scalar_formatted(), value_contents_for_printing(), value_embedded_offset(), value_optimized_out(), and value_type().
Referenced by mips_print_registers_info(), and print_gp_register_row().
static void mips_print_registers_info (struct gdbarch * gdbarch, struct ui_file * file, struct frame_info * frame, int regnum, int all) [static]
Definition at line 6336 of file mips-tdep.c.
References _, error(), fprintf_filtered(), gdb_assert, gdbarch_num_pseudo_regs(), gdbarch_num_regs(), gdbarch_register_name(), mips_float_register_p(), MIPS_NUMREGS, mips_print_register(), print_fp_register_row(), and print_gp_register_row().
Referenced by mips_gdbarch_init().
static enum register_status mips_pseudo_register_read (struct gdbarch * gdbarch, struct regcache * regcache, int cookednum, gdb_byte * buf) [static]
Definition at line 689 of file mips-tdep.c.
References _, gdb_assert, gdbarch_byte_order(), gdbarch_num_regs(), internal_error(), LONGEST, mips64_transfers_32bit_regs_p, REG_VALID, regcache_raw_read(), regcache_raw_read_part(), regcache_raw_read_signed(), register_size(), exsummary::status, and store_signed_integer().
Referenced by mips_gdbarch_init().
static struct type* mips_pseudo_register_type (struct gdbarch * gdbarch, int regnum) [static, read]
Definition at line 1010 of file mips-tdep.c.
References builtin_type::builtin_data_ptr, builtin_type::builtin_func_ptr, builtin_type::builtin_int32, builtin_type(), gdb_assert, GDB_OSABI_IRIX, GDB_OSABI_LINUX, gdbarch_num_regs(), gdbarch_osabi(), gdbarch_register_type(), mips_abi_regsize(), MIPS_EMBED_FP0_REGNUM, mips_float_register_p(), MIPS_LAST_EMBED_REGNUM, MIPS_PS_REGNUM, MIPS_SP_REGNUM, MIPS_ZERO_REGNUM, and TYPE_LENGTH.
Referenced by mips_gdbarch_init().
static void mips_pseudo_register_write (struct gdbarch * gdbarch, struct regcache * regcache, int cookednum, const gdb_byte * buf) [static]
Definition at line 719 of file mips-tdep.c.
References _, extract_signed_integer(), gdb_assert, gdbarch_byte_order(), gdbarch_num_regs(), internal_error(), LONGEST, mips64_transfers_32bit_regs_p, regcache_raw_write(), regcache_raw_write_part(), regcache_raw_write_signed(), and register_size().
Referenced by mips_gdbarch_init().
static CORE_ADDR mips_push_dummy_code (struct gdbarch * gdbarch, CORE_ADDR sp, CORE_ADDR funaddr, struct value ** args, int nargs, struct type * value_type, CORE_ADDR * real_pc, CORE_ADDR * bp_addr, struct regcache * regcache) [static]
Definition at line 4244 of file mips-tdep.c.
References make_compact_addr(), mips_frame_align(), mips_pc_is_micromips(), and write_memory().
Referenced by mips_gdbarch_init().
static void mips_read_fp_register_double (struct frame_info * frame, int regno, gdb_byte * rare_buffer) [static]
Definition at line 6063 of file mips-tdep.c.
References _, deprecated_frame_register_read(), error(), gdbarch_byte_order(), gdbarch_num_regs(), gdbarch_register_name(), get_frame_arch(), internal_error(), mips2_fp_compat(), mips_read_fp_register_single(), and register_size().
Referenced by mips_print_fp_register().
static void mips_read_fp_register_single (struct frame_info * frame, int regno, gdb_byte * rare_buffer) [static]
Definition at line 6029 of file mips-tdep.c.
References _, deprecated_frame_register_read(), error(), gdbarch_byte_order(), gdbarch_register_name(), get_frame_arch(), memcpy(), offset, and register_size().
Referenced by mips_print_fp_register(), and mips_read_fp_register_double().
static CORE_ADDR mips_read_pc (struct regcache * regcache) [static]
Definition at line 1251 of file mips-tdep.c.
References gdbarch_pc_regnum(), get_regcache_arch(), is_compact_addr(), LONGEST, regcache_cooked_read_signed(), regnum, and unmake_compact_addr().
Referenced by mips_gdbarch_init().
static void mips_register_g_packet_guesses (struct gdbarch * gdbarch) [static]
Definition at line 7880 of file mips-tdep.c.
References register_remote_g_packet_guess().
Referenced by mips_gdbarch_init().
static const char* mips_register_name (struct gdbarch * gdbarch, int regno) [static]
Definition at line 557 of file mips-tdep.c.
References _, gdbarch_tdep::abi, gdb_assert, gdbarch_num_regs(), gdbarch_target_desc(), gdbarch_tdep(), internal_error(), MIPS_ABI_N32, MIPS_ABI_N64, gdbarch_tdep::mips_processor_reg_names, NUM_MIPS_PROCESSOR_REGS, tdesc_has_registers(), and tdesc_register_name().
Referenced by mips_gdbarch_init().
static int mips_register_reggroup_p (struct gdbarch * gdbarch, int regnum, struct reggroup * reggroup) [static]
Definition at line 620 of file mips-tdep.c.
References all_reggroup, float_reggroup, gdbarch_num_regs(), gdbarch_register_name(), general_reggroup, register_type(), restore_reggroup, save_reggroup, TYPE_CODE, TYPE_CODE_FLT, TYPE_VECTOR, and vector_reggroup.
Referenced by mips_gdbarch_init(), and mips_tdesc_register_reggroup_p().
static int mips_register_sim_regno (struct gdbarch * gdbarch, int regnum) [static]
Definition at line 7766 of file mips-tdep.c.
References gdb_assert, gdbarch_num_regs(), gdbarch_register_name(), LEGACY_SIM_REGNO_IGNORE, and regnum.
Referenced by mips_gdbarch_init().
static int mips_register_to_value (struct frame_info * frame, int regnum, struct type * type, gdb_byte * to, int * optimizedp, int * unavailablep) [static]
Definition at line 859 of file mips-tdep.c.
References _, gdbarch_byte_order(), get_frame_arch(), get_frame_register(), get_frame_register_bytes(), internal_error(), len, mips_convert_register_float_case_p(), mips_convert_register_gpreg_case_p(), offset, and TYPE_LENGTH.
Referenced by mips_gdbarch_init().
static struct type * mips_register_type (struct gdbarch * gdbarch, int regnum) [static, read]
Definition at line 952 of file mips-tdep.c.
References builtin_type::builtin_double, builtin_type::builtin_float, builtin_type::builtin_int32, builtin_type::builtin_int64, builtin_type(), gdb_assert, GDB_OSABI_IRIX, GDB_OSABI_LINUX, gdbarch_num_regs(), gdbarch_osabi(), mips_abi_regsize(), MIPS_FIRST_EMBED_REGNUM, mips_float_register_p(), mips_isa_regsize(), and MIPS_LAST_EMBED_REGNUM.
Referenced by mips_gdbarch_init().
struct mips_regnum* mips_regnum (struct gdbarch * gdbarch) [read]
Definition at line 191 of file mips-tdep.c.
References gdbarch_tdep(), and gdbarch_tdep::regnum.
Referenced by fill_gregset(), micromips_bc1_pc(), micromips_next_pc(), micromips_scan_prologue(), mips16_scan_prologue(), mips32_bc1_pc(), mips32_next_pc(), mips32_scan_prologue(), mips64_linux_register_addr(), mips64_linux_regsets_fetch_registers(), mips64_linux_regsets_store_registers(), mips64obsd_sigframe_init(), mips_dwarf_dwarf2_ecoff_reg_to_regnum(), mips_eabi_return_value(), mips_fpa0_regnum(), mips_gdbarch_init(), mips_irix_n32_tramp_frame_init(), mips_linux_n32n64_sigframe_init(), mips_linux_o32_sigframe_init(), mips_linux_register_addr(), mips_map_regno(), mips_stab_reg_to_regnum(), mipsnbsd_fill_fpreg(), and mipsnbsd_supply_fpreg().
static void mips_remote_breakpoint_from_pc (struct gdbarch * gdbarch, CORE_ADDR * pcptr, int * kindptr) [static]
Definition at line 6950 of file mips-tdep.c.
References ISA_MICROMIPS, mips_fetch_instruction(), mips_insn_size(), mips_pc_is_micromips(), mips_pc_is_mips16(), size, exsummary::status, ULONGEST, and unmake_compact_addr().
Referenced by mips_gdbarch_init().
static CORE_ADDR mips_segment_boundary (CORE_ADDR bpaddr) [static]
Definition at line 7122 of file mips-tdep.c.
References CORE_ADDR_MAX.
Referenced by mips_adjust_breakpoint_address().
static int mips_single_step_through_delay (struct gdbarch * gdbarch, struct frame_info * frame) [static]
Definition at line 6369 of file mips-tdep.c.
References breakpoint_here_p(), gdbarch::byte_order, gdbarch_byte_order(), get_frame_address_space(), get_frame_pc(), micromips_instruction_has_delay_slot(), mips16_instruction_has_delay_slot(), mips32_instruction_has_delay_slot(), mips_fetch_instruction(), mips_insn_size(), mips_pc_is_micromips(), mips_pc_is_mips(), mips_pc_is_mips16(), mips_pc_isa(), no_breakpoint_here, size, exsummary::status, and ULONGEST.
Referenced by mips_gdbarch_init().
static CORE_ADDR mips_skip_mips16_trampoline_code (struct frame_info * frame, CORE_ADDR pc) [static]
Definition at line 7496 of file mips-tdep.c.
References find_pc_partial_function(), gdbarch_num_regs(), get_frame_arch(), get_frame_register_signed(), mips_get_mips16_fn_stub_pc(), mips_is_stub_mode(), mips_is_stub_suffix(), MIPS_RA_REGNUM, MIPS_S2_REGNUM, MIPS_V0_REGNUM, and name.
Referenced by mips_skip_trampoline_code().
static CORE_ADDR mips_skip_pic_trampoline_code (struct frame_info * frame, CORE_ADDR pc) [static]
Definition at line 7624 of file mips-tdep.c.
References gdbarch::byte_order, extract_unsigned_integer(), gdbarch_byte_order(), get_frame_arch(), lookup_minimal_symbol_by_pc(), bound_minimal_symbol::minsym, MSYMBOL_SIZE, SYMBOL_LINKAGE_NAME, SYMBOL_VALUE_ADDRESS, and target_read_memory().
Referenced by mips_skip_trampoline_code().
static CORE_ADDR mips_skip_prologue (struct gdbarch * gdbarch, CORE_ADDR pc) [static]
Definition at line 6406 of file mips-tdep.c.
References find_pc_partial_function(), max, micromips_scan_prologue(), mips16_scan_prologue(), mips32_scan_prologue(), mips_pc_is_micromips(), mips_pc_is_mips16(), and skip_prologue_using_sal().
Referenced by mips_gdbarch_init().
static CORE_ADDR mips_skip_trampoline_code (struct frame_info * frame, CORE_ADDR pc) [static]
Definition at line 7677 of file mips-tdep.c.
References find_solib_trampoline_target(), is_compact_addr(), mips_skip_mips16_trampoline_code(), mips_skip_pic_trampoline_code(), and unmake_compact_addr().
Referenced by mips_gdbarch_init().
int mips_software_single_step (struct frame_info * frame)
Definition at line 3969 of file mips-tdep.c.
References deal_with_atomic_sequence(), get_frame_address_space(), get_frame_arch(), get_frame_pc(), insert_single_step_breakpoint(), and mips_next_pc().
Referenced by mips_linux_init_abi(), and mipsnbsd_init_abi().
static int mips_stab_reg_to_regnum (struct gdbarch * gdbarch, int num) [static]
Definition at line 7720 of file mips-tdep.c.
References mips_regnum::dspacc, mips_regnum::fp0, gdbarch_num_pseudo_regs(), gdbarch_num_regs(), mips_regnum::hi, mips_regnum::lo, mips_regnum(), and regnum.
Referenced by mips_gdbarch_init().
static CORE_ADDR mips_stub_frame_base_address (struct frame_info * this_frame, void ** this_cache) [static]
Definition at line 3623 of file mips-tdep.c.
References mips_stub_frame_cache(), and trad_frame_get_this_base().
static struct frame_base* mips_stub_frame_base_sniffer (struct frame_info * this_frame) [static, read]
Definition at line 3640 of file mips-tdep.c.
References mips_stub_frame_base, and mips_stub_frame_sniffer().
Referenced by mips_gdbarch_init().
static struct trad_frame_cache* mips_stub_frame_cache (struct frame_info * this_frame, void ** this_cache) [static, read]
Definition at line 3533 of file mips-tdep.c.
References find_pc_partial_function(), frame_id_build(), gdbarch_num_regs(), gdbarch_pc_regnum(), get_frame_arch(), get_frame_pc(), get_frame_register_signed(), MIPS_RA_REGNUM, MIPS_SP_REGNUM, gdbarch::num_regs, trad_frame_cache_zalloc(), trad_frame_set_id(), trad_frame_set_reg_realreg(), and trad_frame_set_this_base().
Referenced by mips_stub_frame_base_address(), mips_stub_frame_prev_register(), and mips_stub_frame_this_id().
static struct value* mips_stub_frame_prev_register (struct frame_info * this_frame, void ** this_cache, int regnum) [static, read]
Definition at line 3577 of file mips-tdep.c.
References mips_stub_frame_cache(), and trad_frame_get_register().
static int mips_stub_frame_sniffer (const struct frame_unwind * self, struct frame_info * this_frame, void ** this_cache) [static]
Definition at line 3586 of file mips-tdep.c.
References dummy, get_frame_address_in_block(), get_frame_pc(), in_mips_stubs_section(), in_plt_section(), lookup_minimal_symbol_by_pc(), bound_minimal_symbol::minsym, SYMBOL_LINKAGE_NAME, and target_read_memory().
Referenced by mips_stub_frame_base_sniffer().
static void mips_stub_frame_this_id (struct frame_info * this_frame, void ** this_cache, struct frame_id * this_id) [static]
Definition at line 3568 of file mips-tdep.c.
References mips_stub_frame_cache(), and trad_frame_get_id().
static int mips_tdesc_register_reggroup_p (struct gdbarch * gdbarch, int regnum, struct reggroup * reggroup) [static]
Definition at line 660 of file mips-tdep.c.
References gdbarch_num_regs(), mips_register_reggroup_p(), and tdesc_register_in_reggroup_p().
Referenced by mips_gdbarch_init().
static int mips_type_needs_double_align (struct type * type) [static]
Definition at line 4208 of file mips-tdep.c.
References TYPE_CODE, TYPE_CODE_FLT, TYPE_CODE_STRUCT, TYPE_CODE_UNION, TYPE_FIELD_TYPE, TYPE_LENGTH, and TYPE_NFIELDS.
Referenced by mips_o32_push_dummy_call().
static CORE_ADDR mips_unwind_pc (struct gdbarch * gdbarch, struct frame_info * next_frame) [static]
Definition at line 1263 of file mips-tdep.c.
References frame_relative_level(), frame_unwind_register_signed(), gdbarch_num_regs(), gdbarch_pc_regnum(), is_compact_addr(), mips_in_frame_stub(), MIPS_RA_REGNUM, MIPS_S2_REGNUM, and unmake_compact_addr().
Referenced by mips_gdbarch_init().
static CORE_ADDR mips_unwind_sp (struct gdbarch * gdbarch, struct frame_info * next_frame) [static]
Definition at line 1293 of file mips-tdep.c.
References frame_unwind_register_signed(), gdbarch_num_regs(), and MIPS_SP_REGNUM.
Referenced by mips_gdbarch_init().
static void mips_value_to_register (struct frame_info * frame, int regnum, struct type * type, const gdb_byte * from) [static]
Definition at line 901 of file mips-tdep.c.
References _, gdbarch_byte_order(), get_frame_arch(), internal_error(), len, mips_convert_register_float_case_p(), mips_convert_register_gpreg_case_p(), put_frame_register(), put_frame_register_bytes(), store_signed_integer(), and TYPE_LENGTH.
Referenced by mips_gdbarch_init().
static void mips_virtual_frame_pointer (struct gdbarch * gdbarch, CORE_ADDR pc, int * reg, LONGEST * offset) [static]
Definition at line 7801 of file mips-tdep.c.
References MIPS_SP_REGNUM.
Referenced by mips_gdbarch_init().
void mips_write_pc (struct regcache * regcache, CORE_ADDR pc)
Definition at line 1317 of file mips-tdep.c.
References gdbarch_pc_regnum(), get_regcache_arch(), make_compact_addr(), mips_pc_is_mips(), regcache_cooked_write_unsigned(), and regnum.
Referenced by mips_gdbarch_init(), and mips_linux_write_pc().
static void mips_xfer_register (struct gdbarch * gdbarch, struct regcache * regcache, int reg_num, int length, enum bfd_endian endian, gdb_byte * in, const gdb_byte * out, int buf_offset) [static]
Definition at line 402 of file mips-tdep.c.
References _, fprintf_unfiltered(), gdb_assert, gdb_stderr, gdb_stdlog, gdbarch_num_regs(), internal_error(), mips_debug, reg_offset, regcache_cooked_read_part(), regcache_cooked_write_part(), and register_size().
Referenced by mips_eabi_return_value(), mips_n32n64_return_value(), mips_o32_return_value(), and mips_o64_return_value().
static int msymbol_is_micromips (struct minimal_symbol * msym) [static]
Definition at line 391 of file mips-tdep.c.
References MSYMBOL_TARGET_FLAG_2.
Referenced by mips_pc_is_micromips(), and mips_pc_isa().
static int msymbol_is_mips (struct minimal_symbol * msym) [static]
Definition at line 375 of file mips-tdep.c.
References MSYMBOL_TARGET_FLAG_1, and MSYMBOL_TARGET_FLAG_2.
Referenced by mips_pc_is_mips().
static int msymbol_is_mips16 (struct minimal_symbol * msym) [static]
Definition at line 383 of file mips-tdep.c.
References MSYMBOL_TARGET_FLAG_1.
Referenced by mips_pc_is_mips16(), and mips_pc_isa().
static int print_fp_register_row (struct ui_file * file, struct frame_info * frame, int regnum) [static]
Definition at line 6229 of file mips-tdep.c.
References fprintf_filtered(), and mips_print_fp_register().
Referenced by mips_print_registers_info().
static int print_gp_register_row (struct ui_file * file, struct frame_info * frame, int start_regnum) [static]
Definition at line 6242 of file mips-tdep.c.
References _, deprecated_frame_register_read(), error(), fprintf_filtered(), gdbarch_byte_order(), gdbarch_num_pseudo_regs(), gdbarch_num_regs(), gdbarch_register_name(), get_frame_arch(), MAX_REGISTER_SIZE, mips_abi_regsize(), mips_float_register_p(), MIPS_NUMREGS, mips_print_register(), printf_filtered(), register_size(), and regnum.
Referenced by mips_print_registers_info().
static void reinit_frame_cache_sfunc (char * args, int from_tty, struct cmd_list_element * c) [static]
Definition at line 6767 of file mips-tdep.c.
References reinit_frame_cache().
Referenced by _initialize_mips_tdep().
static void reset_saved_regs (struct gdbarch * gdbarch, struct mips_frame_cache * this_cache) [static]
Definition at line 3179 of file mips-tdep.c.
References trad_frame_saved_reg::addr, gdbarch_num_regs(), gdbarch::num_regs, and mips_frame_cache::saved_regs.
Referenced by mips32_scan_prologue().
static void set_mips64_transfers_32bit_regs (char * args, int from_tty, struct cmd_list_element * c) [static]
Definition at line 805 of file mips-tdep.c.
References _, error(), gdbarch_info_init(), and gdbarch_update_p().
Referenced by _initialize_mips_tdep().
static void set_mips_command (char * args, int from_tty) [static]
Definition at line 6642 of file mips-tdep.c.
References all_commands, gdb_stdout, help_list(), and printf_unfiltered().
Referenced by _initialize_mips_tdep().
static void set_mipsfpu_auto_command (char * args, int from_tty) [static]
Definition at line 6739 of file mips-tdep.c.
References mips_fpu_type_auto.
Referenced by _initialize_mips_tdep().
static void set_mipsfpu_command (char * args, int from_tty) [static]
Definition at line 6689 of file mips-tdep.c.
References printf_unfiltered(), and show_mipsfpu_command().
Referenced by _initialize_mips_tdep().
static void set_mipsfpu_double_command (char * args, int from_tty) [static]
Definition at line 6711 of file mips-tdep.c.
References _, gdbarch_info_init(), gdbarch_update_p(), internal_error(), MIPS_FPU_DOUBLE, and mips_fpu_type_auto.
Referenced by _initialize_mips_tdep().
static void set_mipsfpu_none_command (char * args, int from_tty) [static]
Definition at line 6725 of file mips-tdep.c.
References _, gdbarch_info_init(), gdbarch_update_p(), internal_error(), MIPS_FPU_NONE, and mips_fpu_type_auto.
Referenced by _initialize_mips_tdep().
static void set_mipsfpu_single_command (char * args, int from_tty) [static]
Definition at line 6697 of file mips-tdep.c.
References _, gdbarch_info_init(), gdbarch_update_p(), internal_error(), MIPS_FPU_SINGLE, and mips_fpu_type_auto.
Referenced by _initialize_mips_tdep().
static void set_reg_offset (struct gdbarch * gdbarch, struct mips_frame_cache * this_cache, int regnum, CORE_ADDR offset) [static]
Definition at line 2279 of file mips-tdep.c.
References trad_frame_saved_reg::addr, gdbarch_num_regs(), offset, and mips_frame_cache::saved_regs.
Referenced by micromips_scan_prologue(), mips16_scan_prologue(), and mips32_scan_prologue().
static void show_mask_address (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 1093 of file mips-tdep.c.
References _, AUTO_BOOLEAN_AUTO, AUTO_BOOLEAN_FALSE, AUTO_BOOLEAN_TRUE, deprecated_show_value_hack, gdbarch_tdep(), internal_error(), mips_mask_address_p(), printf_filtered(), and target_gdbarch().
Referenced by _initialize_mips_tdep().
static void show_mips_abi (struct ui_file * file, int from_tty, struct cmd_list_element * ignored_cmd, const char * ignored_value) [static]
Definition at line 8680 of file mips-tdep.c.
References fprintf_filtered(), gdbarch_bfd_arch_info(), global_mips_abi(), mips_abi_strings, MIPS_ABI_UNKNOWN, and target_gdbarch().
Referenced by _initialize_mips_tdep().
static void show_mips_command (char * args, int from_tty) [static]
Definition at line 6636 of file mips-tdep.c.
References all_commands, gdb_stdout, and help_list().
Referenced by _initialize_mips_tdep().
static void show_mips_compression (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 8720 of file mips-tdep.c.
References _, and fprintf_filtered().
Referenced by _initialize_mips_tdep().
static void show_mipsfpu_command (char * args, int from_tty) [static]
Definition at line 6652 of file mips-tdep.c.
References _, gdbarch_bfd_arch_info(), internal_error(), MIPS_FPU_DOUBLE, MIPS_FPU_NONE, MIPS_FPU_SINGLE, MIPS_FPU_TYPE, mips_fpu_type_auto, printf_unfiltered(), and target_gdbarch().
Referenced by _initialize_mips_tdep(), and set_mipsfpu_command().
static CORE_ADDR unmake_compact_addr (CORE_ADDR addr) [static]
Definition at line 325 of file mips-tdep.c.
Referenced by fetch_mips_16(), mips_addr_bits_remove(), mips_adjust_breakpoint_address(), mips_breakpoint_from_pc(), mips_fetch_instruction(), mips_read_pc(), mips_remote_breakpoint_from_pc(), mips_skip_trampoline_code(), and mips_unwind_pc().
static void unpack_mips16 (struct gdbarch * gdbarch, CORE_ADDR pc, unsigned int extension, unsigned int inst, enum mips16_inst_fmts insn_format, struct upk_mips16 * upk) [static]
Definition at line 2052 of file mips-tdep.c.
References _, extended_offset(), i8type, internal_error(), ISA_MIPS16, itype, jalxtype, mips_fetch_instruction(), offset, upk_mips16::offset, upk_mips16::regx, upk_mips16::regy, and ritype.
Referenced by extended_mips16_next_pc().
static struct value* value_of_mips_user_reg (struct frame_info * frame, const void * baton) [static, read]
Definition at line 7897 of file mips-tdep.c.
References value_of_register().
Referenced by mips_gdbarch_init().
Variable Documentation
initialize_file_ftype _initialize_mips_tdep
Referenced by initialize_all_files().
int heuristic_fence_post = 0 [static]
Definition at line 796 of file mips-tdep.c.
Referenced by heuristic_proc_start().
enum auto_boolean mask_address_var = AUTO_BOOLEAN_AUTO
Definition at line 1071 of file mips-tdep.c.
int mips64_transfers_32bit_regs_p = 0 [static]
Definition at line 802 of file mips-tdep.c.
Referenced by mips_ax_pseudo_register_push_stack(), mips_gdbarch_init(), mips_pseudo_register_read(), and mips_pseudo_register_write().
const char* mips_abi_string [static]
Definition at line 89 of file mips-tdep.c.
Referenced by _initialize_mips_tdep(), and global_mips_abi().
const char* const mips_abi_strings[] [static]
Initial value:
 {
  "auto",
  "n32",
  "o32",
  "n64",
  "o64",
  "eabi32",
  "eabi64",
  NULL
}
Definition at line 91 of file mips-tdep.c.
Referenced by _initialize_mips_tdep(), global_mips_abi(), mips_dump_tdep(), and show_mips_abi().
const char mips_compression_micromips[] = "micromips" [static]
Definition at line 106 of file mips-tdep.c.
const char mips_compression_mips16[] = "mips16" [static]
Definition at line 105 of file mips-tdep.c.
const char* mips_compression_string = mips_compression_mips16 [static]
Definition at line 114 of file mips-tdep.c.
Referenced by _initialize_mips_tdep(), global_mips_compression(), and mips_gdbarch_init().
const char* const mips_compression_strings[] [static]
Initial value:
{
  mips_compression_mips16,
  mips_compression_micromips,
  NULL
}
Definition at line 107 of file mips-tdep.c.
Referenced by _initialize_mips_tdep(), global_mips_compression(), and mips_gdbarch_init().
unsigned int mips_debug = 0 [static]
Definition at line 180 of file mips-tdep.c.
Referenced by _initialize_mips_tdep(), mips_eabi_push_dummy_call(), mips_eabi_return_value(), mips_n32n64_push_dummy_call(), mips_n32n64_return_value(), mips_o32_push_dummy_call(), mips_o32_return_value(), mips_o64_push_dummy_call(), mips_o64_return_value(), and mips_xfer_register().
enum mips_fpu_type mips_fpu_type = MIPS_DEFAULT_FPU_TYPE [static]
Definition at line 178 of file mips-tdep.c.
int mips_fpu_type_auto = 1 [static]
Definition at line 177 of file mips-tdep.c.
Referenced by mips_gdbarch_init(), set_mipsfpu_auto_command(), set_mipsfpu_double_command(), set_mipsfpu_none_command(), set_mipsfpu_single_command(), and show_mipsfpu_command().
const char* mips_generic_reg_names[NUM_MIPS_PROCESSOR_REGS] [static]
Initial value:
 {
  "sr", "lo", "hi", "bad", "cause", "pc",
  "f0", "f1", "f2", "f3", "f4", "f5", "f6", "f7",
  "f8", "f9", "f10", "f11", "f12", "f13", "f14", "f15",
  "f16", "f17", "f18", "f19", "f20", "f21", "f22", "f23",
  "f24", "f25", "f26", "f27", "f28", "f29", "f30", "f31",
  "fsr", "fir",
}
Definition at line 500 of file mips-tdep.c.
Referenced by mips_gdbarch_init().
struct frame_base mips_insn16_frame_base [static]
Initial value:
{
  &mips_insn16_frame_unwind,
  mips_insn16_frame_base_address,
  mips_insn16_frame_base_address,
  mips_insn16_frame_base_address
}
Definition at line 2724 of file mips-tdep.c.
Referenced by mips_insn16_frame_base_sniffer().
struct frame_unwind mips_insn16_frame_unwind [static]
Initial value:
{
  NORMAL_FRAME,
  default_frame_unwind_stop_reason,
  mips_insn16_frame_this_id,
  mips_insn16_frame_prev_register,
  NULL,
  mips_insn16_frame_sniffer
}
Definition at line 2705 of file mips-tdep.c.
struct frame_base mips_insn32_frame_base [static]
Initial value:
{
  &mips_insn32_frame_unwind,
  mips_insn32_frame_base_address,
  mips_insn32_frame_base_address,
  mips_insn32_frame_base_address
}
Definition at line 3514 of file mips-tdep.c.
Referenced by mips_insn32_frame_base_sniffer().
struct frame_unwind mips_insn32_frame_unwind [static]
Initial value:
{
  NORMAL_FRAME,
  default_frame_unwind_stop_reason,
  mips_insn32_frame_this_id,
  mips_insn32_frame_prev_register,
  NULL,
  mips_insn32_frame_sniffer
}
Definition at line 3495 of file mips-tdep.c.
const char* mips_irix_reg_names[NUM_MIPS_PROCESSOR_REGS] [static]
Initial value:
 {
  "f0", "f1", "f2", "f3", "f4", "f5", "f6", "f7",
  "f8", "f9", "f10", "f11", "f12", "f13", "f14", "f15",
  "f16", "f17", "f18", "f19", "f20", "f21", "f22", "f23",
  "f24", "f25", "f26", "f27", "f28", "f29", "f30", "f31",
  "pc", "cause", "bad", "hi", "lo", "fsr", "fir"
}
Definition at line 536 of file mips-tdep.c.
Referenced by mips_gdbarch_init().
const char* mips_linux_reg_names[NUM_MIPS_PROCESSOR_REGS] [static]
Initial value:
 {
  "sr", "lo", "hi", "bad", "cause", "pc",
  "f0", "f1", "f2", "f3", "f4", "f5", "f6", "f7",
  "f8", "f9", "f10", "f11", "f12", "f13", "f14", "f15",
  "f16", "f17", "f18", "f19", "f20", "f21", "f22", "f23",
  "f24", "f25", "f26", "f27", "f28", "f29", "f30", "f31",
  "fsr", "fir"
}
Definition at line 545 of file mips-tdep.c.
Referenced by mips_gdbarch_init().
struct frame_base mips_micro_frame_base [static]
Initial value:
{
  &mips_micro_frame_unwind,
  mips_micro_frame_base_address,
  mips_micro_frame_base_address,
  mips_micro_frame_base_address
}
Definition at line 3155 of file mips-tdep.c.
Referenced by mips_micro_frame_base_sniffer().
struct frame_unwind mips_micro_frame_unwind [static]
Initial value:
{
  NORMAL_FRAME,
  default_frame_unwind_stop_reason,
  mips_micro_frame_this_id,
  mips_micro_frame_prev_register,
  NULL,
  mips_micro_frame_sniffer
}
Definition at line 3136 of file mips-tdep.c.
struct register_alias mips_n32_n64_aliases[]
Initial value:
 {
  { "ta0", 8 },
  { "ta1", 9 },
  { "ta2", 10 },
  { "ta3", 11 }
}
Definition at line 132 of file mips-tdep.c.
struct register_alias mips_numeric_register_aliases[]
Initial value:
 {
#define R(n)
  R(0), R(1), R(2), R(3), R(4), R(5), R(6), R(7),
  R(8), R(9), R(10), R(11), R(12), R(13), R(14), R(15),
  R(16), R(17), R(18), R(19), R(20), R(21), R(22), R(23),
  R(24), R(25), R(26), R(27), R(28), R(29), R(30), R(31),
}
Definition at line 165 of file mips-tdep.c.
struct register_alias mips_o32_aliases[]
Initial value:
 {
  { "ta0", 12 },
  { "ta1", 13 },
  { "ta2", 14 },
  { "ta3", 15 }
}
Definition at line 124 of file mips-tdep.c.
struct objfile_data* mips_pdr_data [static]
Definition at line 61 of file mips-tdep.c.
Referenced by _initialize_mips_tdep().
const char* mips_r3041_reg_names[] [static]
Initial value:
 {
  "sr", "lo", "hi", "bad", "cause", "pc",
  "f0", "f1", "f2", "f3", "f4", "f5", "f6", "f7",
  "f8", "f9", "f10", "f11", "f12", "f13", "f14", "f15",
  "f16", "f17", "f18", "f19", "f20", "f21", "f22", "f23",
  "f24", "f25", "f26", "f27", "f28", "f29", "f30", "f31",
  "fsr", "fir", "",  "",
  "", "", "bus", "ccfg", "", "", "", "",
  "", "", "port", "cmp", "", "", "epc", "prid",
}
Definition at line 511 of file mips-tdep.c.
Referenced by deprecated_mips_set_processor_regs_hack().
const signed char mips_reg3_to_reg[8] = { 16, 17, 2, 3, 4, 5, 6, 7 } [static]
Definition at line 790 of file mips-tdep.c.
struct register_alias mips_register_aliases[]
Initial value:
 {
#define R(n)
  R(0), R(1), R(2), R(3), R(4), R(5), R(6), R(7),
  R(8), R(9), R(10), R(11), R(12), R(13), R(14), R(15),
  R(16), R(17), R(18), R(19), R(20), R(21), R(22), R(23),
  R(24), R(25), R(26), R(27), R(28), R(29), R(30), R(31),
  { "kt0", 26 },
  { "kt1", 27 },
  { "sr", MIPS_PS_REGNUM },
  { "bad", MIPS_EMBED_BADVADDR_REGNUM },
  { "fsr", MIPS_EMBED_FP0_REGNUM + 32 }
}
Definition at line 140 of file mips-tdep.c.
const char mips_str_call_fp_stub[] = "__call_stub_fp_" [static]
Definition at line 1212 of file mips-tdep.c.
const char mips_str_call_stub[] = "__call_stub_" [static]
Definition at line 1213 of file mips-tdep.c.
const char mips_str_fn_stub[] = "__fn_stub_" [static]
Definition at line 1214 of file mips-tdep.c.
const char mips_str_mips16_call_stub[] = "__mips16_call_stub_" [static]
Definition at line 1210 of file mips-tdep.c.
const char mips_str_mips16_ret_stub[] = "__mips16_ret_" [static]
Definition at line 1211 of file mips-tdep.c.
const char mips_str_pic[] = ".pic." [static]
Definition at line 1218 of file mips-tdep.c.
struct frame_base mips_stub_frame_base [static]
Initial value:
{
  &mips_stub_frame_unwind,
  mips_stub_frame_base_address,
  mips_stub_frame_base_address,
  mips_stub_frame_base_address
}
Definition at line 3631 of file mips-tdep.c.
Referenced by mips_stub_frame_base_sniffer().
struct frame_unwind mips_stub_frame_unwind [static]
Initial value:
{
  NORMAL_FRAME,
  default_frame_unwind_stop_reason,
  mips_stub_frame_this_id,
  mips_stub_frame_prev_register,
  NULL,
  mips_stub_frame_sniffer
}
Definition at line 3612 of file mips-tdep.c.
struct target_desc* mips_tdesc_gp32
Definition at line 187 of file mips-tdep.c.
Referenced by mips_linux_core_read_description().
struct target_desc* mips_tdesc_gp64
Definition at line 188 of file mips-tdep.c.
Referenced by mips_linux_core_read_description().
const char* mips_tx39_reg_names[NUM_MIPS_PROCESSOR_REGS] [static]
Initial value:
 {
  "sr", "lo", "hi", "bad", "cause", "pc",
  "", "", "", "", "", "", "", "",
  "", "", "", "", "", "", "", "",
  "", "", "", "", "", "", "", "",
  "", "", "", "", "", "", "", "",
  "", "", "", "",
  "", "", "", "", "", "", "", "",
  "", "", "config", "cache", "debug", "depc", "epc",
}
Definition at line 524 of file mips-tdep.c.
Referenced by mips_gdbarch_init().
struct cmd_list_element* setmipscmdlist = NULL [static]
Definition at line 488 of file mips-tdep.c.
struct cmd_list_element* showmipscmdlist = NULL [static]
Definition at line 489 of file mips-tdep.c.