GDB (xrefs): /home/stan/gdb/src/gdb/mipsnbsd-nat.c File Reference
/home/stan/gdb/src/gdb/mipsnbsd-nat.c File Reference
#include "defs.h"
#include "inferior.h"
#include "regcache.h"
#include "target.h"
#include <sys/types.h>
#include <sys/ptrace.h>
#include <machine/reg.h>
#include "mips-tdep.h"
#include "mipsnbsd-tdep.h"
#include "inf-ptrace.h"
Functions
static int getregs_supplies (struct gdbarch *gdbarch, int regno)
static void mipsnbsd_fetch_inferior_registers (struct target_ops *ops, struct regcache *regcache, int regno)
static void mipsnbsd_store_inferior_registers (struct target_ops *ops, struct regcache *regcache, int regno)
void _initialize_mipsnbsd_nat (void)
Function Documentation
void _initialize_mipsnbsd_nat (void)
Definition at line 117 of file mipsnbsd-nat.c.
References add_target(), inf_ptrace_target(), mipsnbsd_fetch_inferior_registers(), mipsnbsd_store_inferior_registers(), target_ops::to_fetch_registers, and target_ops::to_store_registers.
static int getregs_supplies (struct gdbarch * gdbarch, int regno) [static]
Definition at line 35 of file mipsnbsd-nat.c.
References gdbarch_pc_regnum(), and MIPS_ZERO_REGNUM.
Referenced by mipsnbsd_fetch_inferior_registers(), and mipsnbsd_store_inferior_registers().
static void mipsnbsd_fetch_inferior_registers (struct target_ops * ops, struct regcache * regcache, int regno) [static]
Definition at line 42 of file mipsnbsd-nat.c.
References _, gdbarch_fp0_regnum(), get_regcache_arch(), getregs_supplies(), inferior_ptid, mipsnbsd_supply_fpreg(), mipsnbsd_supply_reg(), perror_with_name(), ptid_get_pid(), ptrace(), and PTRACE_TYPE_ARG3.
Referenced by _initialize_mipsnbsd_nat().
static void mipsnbsd_store_inferior_registers (struct target_ops * ops, struct regcache * regcache, int regno) [static]
Definition at line 73 of file mipsnbsd-nat.c.
References _, gdbarch_fp0_regnum(), get_regcache_arch(), getregs_supplies(), inferior_ptid, mipsnbsd_fill_fpreg(), mipsnbsd_fill_reg(), perror_with_name(), ptid_get_pid(), ptrace(), and PTRACE_TYPE_ARG3.
Referenced by _initialize_mipsnbsd_nat().