GDB (xrefs): /home/stan/gdb/src/gdb/mipsread.c File Reference
/home/stan/gdb/src/gdb/mipsread.c File Reference
#include "defs.h"
#include "gdb_string.h"
#include "bfd.h"
#include "symtab.h"
#include "objfiles.h"
#include "buildsym.h"
#include "stabsread.h"
#include "coff/sym.h"
#include "coff/internal.h"
#include "coff/ecoff.h"
#include "libcoff.h"
#include "libecoff.h"
#include "elf/common.h"
#include "elf/internal.h"
#include "elf/mips.h"
#include "psymtab.h"
Classes
struct Elfalpha_External_Sym
struct Elfalpha_External_Dyn
struct alphacoff_dynsecinfo
Functions
static void read_alphacoff_dynamic_symtab (struct section_offsets *, struct objfile *objfile)
static void mipscoff_new_init (struct objfile *ignore)
static void mipscoff_symfile_init (struct objfile *objfile)
static void mipscoff_symfile_read (struct objfile *objfile, int symfile_flags)
static void mipscoff_symfile_finish (struct objfile *objfile)
static void alphacoff_locate_sections (bfd *ignore_abfd, asection *sectp, void *sip)
void _initialize_mipsread (void)
Variables
static struct sym_fns ecoff_sym_fns
Function Documentation
void _initialize_mipsread (void)
static void alphacoff_locate_sections (bfd * ignore_abfd, asection * sectp, void * sip) [static]
Definition at line 160 of file mipsread.c.
References alphacoff_dynsecinfo::dyninfo_sect, alphacoff_dynsecinfo::got_sect, alphacoff_dynsecinfo::str_sect, and alphacoff_dynsecinfo::sym_sect.
Referenced by read_alphacoff_dynamic_symtab().
static void mipscoff_new_init (struct objfile * ignore) [static]
Definition at line 54 of file mipsread.c.
References buildsym_new_init(), and stabsread_new_init().
static void mipscoff_symfile_finish (struct objfile * objfile) [static]
Definition at line 103 of file mipsread.c.
static void mipscoff_symfile_init (struct objfile * objfile) [static]
Definition at line 63 of file mipsread.c.
static void mipscoff_symfile_read (struct objfile * objfile, int symfile_flags) [static]
Definition at line 70 of file mipsread.c.
References _, debug_info, debug_swap, do_cleanups(), error(), init_minimal_symbol_collection(), install_minimal_symbols(), make_cleanup_discard_minimal_symbols(), mdebug_build_psymtabs(), objfile::obfd, read_alphacoff_dynamic_symtab(), and objfile::section_offsets.
static void read_alphacoff_dynamic_symtab (struct section_offsets * section_offsets, struct objfile * objfile) [static]
Definition at line 180 of file mipsread.c.
References alphacoff_locate_sections(), ANOFFSET, Elfalpha_External_Dyn::d_tag, Elfalpha_External_Dyn::d_un, Elfalpha_External_Dyn::d_val, do_cleanups(), make_cleanup(), memset(), mst_abs, mst_bss, mst_data, mst_file_bss, mst_file_data, mst_file_text, mst_solib_trampoline, mst_text, name, objfile::obfd, prim_record_minimal_symbol(), SECT_OFF_BSS, SECT_OFF_DATA, SECT_OFF_TEXT, Elfalpha_External_Sym::st_info, Elfalpha_External_Sym::st_name, Elfalpha_External_Sym::st_shndx, Elfalpha_External_Sym::st_value, sym_info(), xfree(), and xmalloc().
Referenced by mipscoff_symfile_read().
Variable Documentation
struct sym_fns ecoff_sym_fns [static]
Initial value:
{
  mipscoff_new_init,
  mipscoff_symfile_init,
  mipscoff_symfile_read,
  NULL,
  mipscoff_symfile_finish,
  default_symfile_offsets,
  default_symfile_segments,
  NULL,
  default_symfile_relocate,
  NULL,
  &psym_functions
}
Definition at line 406 of file mipsread.c.