GDB (xrefs): /home/stan/gdb/src/gdb/mips-tdep.h File Reference
/home/stan/gdb/src/gdb/mips-tdep.h File Reference
#include "objfiles.h"
Classes
struct mips_regnum
struct gdbarch_tdep
Enumerations
enum mips_abi {
MIPS_ABI_UNKNOWN = 0, MIPS_ABI_N32, MIPS_ABI_O32, MIPS_ABI_N64,
MIPS_ABI_O64, MIPS_ABI_EABI32, MIPS_ABI_EABI64, MIPS_ABI_LAST
}
enum mips_isa { ISA_MIPS = -1, ISA_MIPS16, ISA_MICROMIPS }
enum mips_fpu_type { MIPS_FPU_DOUBLE, MIPS_FPU_SINGLE, MIPS_FPU_NONE }
enum {
MIPS_ZERO_REGNUM = 0, MIPS_AT_REGNUM = 1, MIPS_V0_REGNUM = 2, MIPS_A0_REGNUM = 4,
MIPS_S2_REGNUM = 18, MIPS_T9_REGNUM = 25, MIPS_GP_REGNUM = 28, MIPS_SP_REGNUM = 29,
MIPS_RA_REGNUM = 31, MIPS_PS_REGNUM = 32, MIPS_EMBED_LO_REGNUM = 33, MIPS_EMBED_HI_REGNUM = 34,
MIPS_EMBED_BADVADDR_REGNUM = 35, MIPS_EMBED_CAUSE_REGNUM = 36, MIPS_EMBED_PC_REGNUM = 37, MIPS_EMBED_FP0_REGNUM = 38,
MIPS_UNUSED_REGNUM = 73, MIPS_FIRST_EMBED_REGNUM = 74, MIPS_PRID_REGNUM = 89, MIPS_LAST_EMBED_REGNUM = 89
}
enum { MIPS_INSN16_SIZE = 2, MIPS_INSN32_SIZE = 4, MIPS_NUMREGS = 32 }
Functions
enum mips_abi mips_abi (struct gdbarch *gdbarch)
int mips_isa_regsize (struct gdbarch *gdbarch)
struct mips_regnum * mips_regnum (struct gdbarch *gdbarch)
void deprecated_mips_set_processor_regs_hack (void)
int mips_software_single_step (struct frame_info *frame)
int mips_pc_is_mips (bfd_vma memaddr)
int mips_pc_is_mips16 (struct gdbarch *gdbarch, bfd_vma memaddr)
int mips_pc_is_micromips (struct gdbarch *gdbarch, bfd_vma memaddr)
unsigned int mips_abi_regsize (struct gdbarch *gdbarch)
void mips_write_pc (struct regcache *regcache, CORE_ADDR pc)
static int in_mips_stubs_section (CORE_ADDR pc)
Variables
struct target_desc * mips_tdesc_gp32
struct target_desc * mips_tdesc_gp64
Enumeration Type Documentation
anonymous enum
Enumerator:
MIPS_ZERO_REGNUM
MIPS_AT_REGNUM
MIPS_V0_REGNUM
MIPS_A0_REGNUM
MIPS_S2_REGNUM
MIPS_T9_REGNUM
MIPS_GP_REGNUM
MIPS_SP_REGNUM
MIPS_RA_REGNUM
MIPS_PS_REGNUM
MIPS_EMBED_LO_REGNUM
MIPS_EMBED_HI_REGNUM
MIPS_EMBED_BADVADDR_REGNUM
MIPS_EMBED_CAUSE_REGNUM
MIPS_EMBED_PC_REGNUM
MIPS_EMBED_FP0_REGNUM
MIPS_UNUSED_REGNUM
MIPS_FIRST_EMBED_REGNUM
MIPS_PRID_REGNUM
MIPS_LAST_EMBED_REGNUM
Definition at line 127 of file mips-tdep.h.
anonymous enum
Enumerator:
MIPS_INSN16_SIZE
MIPS_INSN32_SIZE
MIPS_NUMREGS
Definition at line 155 of file mips-tdep.h.
enum mips_abi
Enumerator:
MIPS_ABI_UNKNOWN
MIPS_ABI_N32
MIPS_ABI_O32
MIPS_ABI_N64
MIPS_ABI_O64
MIPS_ABI_EABI32
MIPS_ABI_EABI64
MIPS_ABI_LAST
Definition at line 28 of file mips-tdep.h.
enum mips_fpu_type
Enumerator:
MIPS_FPU_DOUBLE
MIPS_FPU_SINGLE
MIPS_FPU_NONE
Definition at line 74 of file mips-tdep.h.
enum mips_isa
Enumerator:
ISA_MIPS
ISA_MIPS16
ISA_MICROMIPS
Definition at line 44 of file mips-tdep.h.
Function Documentation
void deprecated_mips_set_processor_regs_hack (void)
Definition at line 6751 of file mips-tdep.c.
References gdbarch_tdep(), get_current_regcache(), get_regcache_arch(), MIPS_PRID_REGNUM, gdbarch_tdep::mips_processor_reg_names, mips_r3041_reg_names, regcache_cooked_read_unsigned(), and ULONGEST.
static int in_mips_stubs_section (CORE_ADDR pc) [inline, static]
Definition at line 192 of file mips-tdep.h.
References pc_in_section().
Referenced by mips_linux_in_dynsym_stub(), and mips_stub_frame_sniffer().
enum mips_abi mips_abi (struct gdbarch * gdbarch)
Definition at line 228 of file mips-tdep.c.
References gdbarch_tdep(), and gdbarch_tdep::mips_abi.
unsigned int mips_abi_regsize (struct gdbarch * gdbarch)
Definition at line 250 of file mips-tdep.c.
References _, internal_error(), MIPS_ABI_EABI32, MIPS_ABI_EABI64, MIPS_ABI_LAST, MIPS_ABI_N32, MIPS_ABI_N64, MIPS_ABI_O32, MIPS_ABI_O64, and MIPS_ABI_UNKNOWN.
Referenced by mips16_scan_prologue(), mips32_scan_prologue(), mips_eabi_push_dummy_call(), mips_eabi_return_value(), mips_linux_register_u_offset(), mips_pseudo_register_type(), mips_register_type(), and print_gp_register_row().
int mips_isa_regsize (struct gdbarch * gdbarch)
Definition at line 234 of file mips-tdep.c.
References bits_per_byte, gdbarch_bfd_arch_info(), gdbarch_tdep(), gdbarch_tdep::register_size, and gdbarch_tdep::register_size_valid_p.
Referenced by fetch_core_registers(), fill_fpregset(), fill_gregset(), mips_register_type(), mipsnbsd_fill_fpreg(), mipsnbsd_fill_reg(), mipsnbsd_regset_from_core_section(), mipsnbsd_supply_fpreg(), mipsnbsd_supply_fpregset(), mipsnbsd_supply_gregset(), mipsnbsd_supply_reg(), supply_fpregset(), and supply_gregset().
int mips_pc_is_micromips (struct gdbarch * gdbarch, bfd_vma memaddr)
Definition at line 1158 of file mips-tdep.c.
References is_micromips_addr(), lookup_minimal_symbol_by_pc(), and msymbol_is_micromips().
Referenced by deal_with_atomic_sequence(), gdb_print_insn_mips(), heuristic_proc_start(), mips_adjust_breakpoint_address(), mips_breakpoint_from_pc(), mips_in_function_epilogue_p(), mips_micro_frame_base_sniffer(), mips_micro_frame_sniffer(), mips_next_pc(), mips_push_dummy_code(), mips_remote_breakpoint_from_pc(), mips_single_step_through_delay(), and mips_skip_prologue().
int mips_pc_is_mips (bfd_vma memaddr)
Definition at line 1122 of file mips-tdep.c.
References is_mips_addr(), lookup_minimal_symbol_by_pc(), and msymbol_is_mips().
Referenced by deal_with_atomic_sequence(), heuristic_proc_start(), mips_about_to_return(), mips_adjust_breakpoint_address(), mips_eabi_push_dummy_call(), mips_insn32_frame_base_sniffer(), mips_insn32_frame_sniffer(), mips_o64_push_dummy_call(), mips_single_step_through_delay(), and mips_write_pc().
int mips_pc_is_mips16 (struct gdbarch * gdbarch, bfd_vma memaddr)
Definition at line 1140 of file mips-tdep.c.
References is_mips16_addr(), lookup_minimal_symbol_by_pc(), and msymbol_is_mips16().
Referenced by gdb_print_insn_mips(), heuristic_proc_start(), mips_breakpoint_from_pc(), mips_in_function_epilogue_p(), mips_insn16_frame_base_sniffer(), mips_insn16_frame_sniffer(), mips_next_pc(), mips_o32_return_value(), mips_o64_return_value(), mips_remote_breakpoint_from_pc(), mips_single_step_through_delay(), and mips_skip_prologue().
struct mips_regnum* mips_regnum (struct gdbarch * gdbarch) [read]
Definition at line 191 of file mips-tdep.c.
References gdbarch_tdep(), and gdbarch_tdep::regnum.
Referenced by fill_gregset(), micromips_bc1_pc(), micromips_next_pc(), micromips_scan_prologue(), mips16_scan_prologue(), mips32_bc1_pc(), mips32_next_pc(), mips32_scan_prologue(), mips64_linux_register_addr(), mips64_linux_regsets_fetch_registers(), mips64_linux_regsets_store_registers(), mips64obsd_sigframe_init(), mips_dwarf_dwarf2_ecoff_reg_to_regnum(), mips_eabi_return_value(), mips_fpa0_regnum(), mips_gdbarch_init(), mips_irix_n32_tramp_frame_init(), mips_linux_n32n64_sigframe_init(), mips_linux_o32_sigframe_init(), mips_linux_register_addr(), mips_map_regno(), mips_stab_reg_to_regnum(), mipsnbsd_fill_fpreg(), and mipsnbsd_supply_fpreg().
int mips_software_single_step (struct frame_info * frame)
Definition at line 3969 of file mips-tdep.c.
References deal_with_atomic_sequence(), get_frame_address_space(), get_frame_arch(), get_frame_pc(), insert_single_step_breakpoint(), and mips_next_pc().
Referenced by mips_linux_init_abi(), and mipsnbsd_init_abi().
void mips_write_pc (struct regcache * regcache, CORE_ADDR pc)
Definition at line 1317 of file mips-tdep.c.
References gdbarch_pc_regnum(), get_regcache_arch(), make_compact_addr(), mips_pc_is_mips(), regcache_cooked_write_unsigned(), and regnum.
Referenced by mips_gdbarch_init(), and mips_linux_write_pc().
Variable Documentation
struct target_desc* mips_tdesc_gp32
Definition at line 187 of file mips-tdep.c.
Referenced by mips_linux_core_read_description().
struct target_desc* mips_tdesc_gp64
Definition at line 188 of file mips-tdep.c.
Referenced by mips_linux_core_read_description().