GDB (xrefs): /home/stan/gdb/src/gdb/mips-irix-tdep.c File Reference
/home/stan/gdb/src/gdb/mips-irix-tdep.c File Reference
#include "defs.h"
#include "osabi.h"
#include "gdb_string.h"
#include "solib.h"
#include "solib-irix.h"
#include "elf-bfd.h"
#include "mips-tdep.h"
#include "trad-frame.h"
#include "tramp-frame.h"
Defines
#define SIGTRAMP_FRAME_SIZE 48
#define SIGCONTEXT_PC_OFF 8
#define SIGCONTEXT_REGS_OFF (SIGCONTEXT_PC_OFF + 8)
#define SIGCONTEXT_FPREGS_OFF (SIGCONTEXT_REGS_OFF + 32 * 8)
#define SIGCONTEXT_FPCSR_OFF (SIGCONTEXT_FPREGS_OFF + 32 * 8 + 4)
#define SIGCONTEXT_HI_OFF (SIGCONTEXT_FPCSR_OFF + 2 * 4)
#define SIGCONTEXT_LO_OFF (SIGCONTEXT_HI_OFF + 4)
Functions
static void mips_irix_elf_osabi_sniff_abi_tag_sections (bfd *abfd, asection *sect, void *obj)
static enum gdb_osabi mips_irix_elf_osabi_sniffer (bfd *abfd)
static void mips_irix_n32_tramp_frame_init (const struct tramp_frame *self, struct frame_info *this_frame, struct trad_frame_cache *this_cache, CORE_ADDR func)
static void mips_irix_n32_stack_tramp_frame_init (const struct tramp_frame *self, struct frame_info *this_frame, struct trad_frame_cache *this_cache, CORE_ADDR func)
static void mips_irix_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
void _initialize_mips_irix_tdep (void)
Variables
static struct tramp_frame mips_irix_n32_tramp_frame
static struct tramp_frame mips_irix_n32_stack_tramp_frame
initialize_file_ftype _initialize_mips_irix_tdep
Define Documentation
#define SIGCONTEXT_FPCSR_OFF (SIGCONTEXT_FPREGS_OFF + 32 * 8 + 4)
Definition at line 131 of file mips-irix-tdep.c.
Referenced by mips_irix_n32_tramp_frame_init().
#define SIGCONTEXT_FPREGS_OFF (SIGCONTEXT_REGS_OFF + 32 * 8)
Definition at line 129 of file mips-irix-tdep.c.
Referenced by mips_irix_n32_tramp_frame_init().
#define SIGCONTEXT_HI_OFF (SIGCONTEXT_FPCSR_OFF + 2 * 4)
Definition at line 133 of file mips-irix-tdep.c.
Referenced by mips_irix_n32_tramp_frame_init().
#define SIGCONTEXT_LO_OFF (SIGCONTEXT_HI_OFF + 4)
Definition at line 135 of file mips-irix-tdep.c.
Referenced by mips_irix_n32_tramp_frame_init().
#define SIGCONTEXT_PC_OFF 8
Definition at line 125 of file mips-irix-tdep.c.
Referenced by mips_irix_n32_tramp_frame_init().
#define SIGCONTEXT_REGS_OFF (SIGCONTEXT_PC_OFF + 8)
Definition at line 127 of file mips-irix-tdep.c.
Referenced by mips_irix_n32_tramp_frame_init().
#define SIGTRAMP_FRAME_SIZE 48
Definition at line 123 of file mips-irix-tdep.c.
Function Documentation
void _initialize_mips_irix_tdep (void)
Definition at line 282 of file mips-irix-tdep.c.
References _initialize_mips_irix_tdep, GDB_OSABI_IRIX, gdbarch_register_osabi(), gdbarch_register_osabi_sniffer(), mips_irix_elf_osabi_sniffer(), and mips_irix_init_abi().
static void mips_irix_elf_osabi_sniff_abi_tag_sections (bfd * abfd, asection * sect, void * obj) [static]
Definition at line 32 of file mips-irix-tdep.c.
References GDB_OSABI_IRIX, and name.
Referenced by mips_irix_elf_osabi_sniffer().
static enum gdb_osabi mips_irix_elf_osabi_sniffer (bfd * abfd) [static]
Definition at line 51 of file mips-irix-tdep.c.
References GDB_OSABI_UNKNOWN, generic_elf_osabi_sniff_abi_tag_sections(), and mips_irix_elf_osabi_sniff_abi_tag_sections().
Referenced by _initialize_mips_irix_tdep().
static void mips_irix_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch) [static]
Definition at line 270 of file mips-irix-tdep.c.
References irix_so_ops, set_solib_ops(), and tramp_frame_prepend_unwinder().
Referenced by _initialize_mips_irix_tdep().
static void mips_irix_n32_stack_tramp_frame_init (const struct tramp_frame * self, struct frame_info * this_frame, struct trad_frame_cache * this_cache, CORE_ADDR func) [static]
Definition at line 234 of file mips-irix-tdep.c.
References frame_id_build(), gdbarch_num_regs(), gdbarch_pc_regnum(), get_frame_arch(), get_frame_register_signed(), MIPS_RA_REGNUM, MIPS_SP_REGNUM, gdbarch::num_regs, sp, trad_frame_set_id(), and trad_frame_set_reg_realreg().
static void mips_irix_n32_tramp_frame_init (const struct tramp_frame * self, struct frame_info * this_frame, struct trad_frame_cache * this_cache, CORE_ADDR func) [static]
Definition at line 140 of file mips-irix-tdep.c.
References mips_regnum::fp0, mips_regnum::fp_control_status, frame_id_build(), gdbarch_num_regs(), get_frame_arch(), get_frame_register_signed(), mips_regnum::hi, mips_regnum::lo, mips_regnum(), MIPS_SP_REGNUM, MIPS_ZERO_REGNUM, gdbarch::num_regs, mips_regnum::pc, SIGCONTEXT_FPCSR_OFF, SIGCONTEXT_FPREGS_OFF, SIGCONTEXT_HI_OFF, SIGCONTEXT_LO_OFF, SIGCONTEXT_PC_OFF, SIGCONTEXT_REGS_OFF, sp, trad_frame_set_id(), and trad_frame_set_reg_addr().
Variable Documentation
initialize_file_ftype _initialize_mips_irix_tdep
Referenced by _initialize_mips_irix_tdep(), and initialize_all_files().
struct tramp_frame mips_irix_n32_stack_tramp_frame [static]
Initial value:
{
  SIGTRAMP_FRAME,
  4,
  {
   { 0x8f210000, 0xffff0000 },
   { 0x8f2f0000, 0xffff0000 },
   { 0x00200008, 0xffffffff },
   { 0x0020c82d, 0xffffffff },
   { TRAMP_SENTINEL_INSN, -1 }
  },
  mips_irix_n32_stack_tramp_frame_init
}
Definition at line 255 of file mips-irix-tdep.c.
struct tramp_frame mips_irix_n32_tramp_frame [static]
Definition at line 187 of file mips-irix-tdep.c.