GDB (xrefs): /home/stan/gdb/src/gdb/mips64obsd-tdep.c File Reference
/home/stan/gdb/src/gdb/mips64obsd-tdep.c File Reference
#include "defs.h"
#include "gdbtypes.h"
#include "osabi.h"
#include "regcache.h"
#include "regset.h"
#include "trad-frame.h"
#include "tramp-frame.h"
#include "gdb_assert.h"
#include "gdb_string.h"
#include "mips-tdep.h"
#include "solib-svr4.h"
Defines
#define floatformats_mips64_quad floatformats_ia64_quad
#define MIPS64OBSD_NUM_REGS 73
Functions
static void mips64obsd_supply_gregset (const struct regset *regset, struct regcache *regcache, int regnum, const void *gregs, size_t len)
static struct regset * mips64obsd_regset_from_core_section (struct gdbarch *gdbarch, const char *sect_name, size_t sect_size)
static void mips64obsd_sigframe_init (const struct tramp_frame *self, struct frame_info *this_frame, struct trad_frame_cache *cache, CORE_ADDR func)
static void mips64obsd_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
void _initialize_mips64obsd_tdep (void)
Variables
static struct regset mips64obsd_gregset
static struct tramp_frame mips64obsd_sigframe
Define Documentation
#define floatformats_mips64_quad floatformats_ia64_quad
Definition at line 36 of file mips64obsd-tdep.c.
Referenced by mips64obsd_init_abi().
#define MIPS64OBSD_NUM_REGS 73
Definition at line 38 of file mips64obsd-tdep.c.
Referenced by mips64obsd_regset_from_core_section(), and mips64obsd_supply_gregset().
Function Documentation
void _initialize_mips64obsd_tdep (void)
Definition at line 168 of file mips64obsd-tdep.c.
References GDB_OSABI_OPENBSD_ELF, gdbarch_register_osabi(), and mips64obsd_init_abi().
static void mips64obsd_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch) [static]
Definition at line 145 of file mips64obsd-tdep.c.
References floatformats_mips64_quad, mips64obsd_regset_from_core_section(), set_gdbarch_long_double_bit(), set_gdbarch_long_double_format(), set_gdbarch_regset_from_core_section(), set_solib_svr4_fetch_link_map_offsets(), svr4_lp64_fetch_link_map_offsets(), and tramp_frame_prepend_unwinder().
Referenced by _initialize_mips64obsd_tdep().
static struct regset* mips64obsd_regset_from_core_section (struct gdbarch * gdbarch, const char * sect_name, size_t sect_size) [static, read]
Definition at line 73 of file mips64obsd-tdep.c.
References mips64obsd_gregset, and MIPS64OBSD_NUM_REGS.
Referenced by mips64obsd_init_abi().
static void mips64obsd_sigframe_init (const struct tramp_frame * self, struct frame_info * this_frame, struct trad_frame_cache * cache, CORE_ADDR func) [static]
Definition at line 86 of file mips64obsd-tdep.c.
References frame_id_build(), gdbarch_num_regs(), get_frame_arch(), get_frame_register_signed(), mips_regnum::hi, mips_regnum::lo, MIPS_AT_REGNUM, MIPS_RA_REGNUM, mips_regnum(), MIPS_SP_REGNUM, mips_regnum::pc, regnum, sp, trad_frame_set_id(), and trad_frame_set_reg_addr().
static void mips64obsd_supply_gregset (const struct regset * regset, struct regcache * regcache, int regnum, const void * gregs, size_t len) [static]
Definition at line 47 of file mips64obsd-tdep.c.
References MIPS64OBSD_NUM_REGS, and regcache_raw_supply().
Variable Documentation
struct regset mips64obsd_gregset [static]
Initial value:
{
  NULL,
  mips64obsd_supply_gregset
}
Definition at line 63 of file mips64obsd-tdep.c.
Referenced by mips64obsd_regset_from_core_section().
struct tramp_frame mips64obsd_sigframe [static]
Initial value:
{
  SIGTRAMP_FRAME,
  MIPS_INSN32_SIZE,
  {
    { 0x67a40020, -1 },
    { 0x24020067, -1 },
    { 0x0000000c, -1 },
    { 0x0000000d, -1 },
    { TRAMP_SENTINEL_INSN, -1 }
  },
  mips64obsd_sigframe_init
}
Definition at line 129 of file mips64obsd-tdep.c.