GDB (xrefs): /home/stan/gdb/src/gdb/common/mips-linux-watch.c File Reference
/home/stan/gdb/src/gdb/common/mips-linux-watch.c File Reference
#include <sys/ptrace.h>
#include "mips-linux-watch.h"
#include "gdb_assert.h"
Functions
uint32_t mips_linux_watch_get_irw_mask (struct pt_watch_regs *regs, int n)
static uint32_t get_reg_mask (struct pt_watch_regs *regs, int n)
uint32_t mips_linux_watch_get_num_valid (struct pt_watch_regs *regs)
CORE_ADDR mips_linux_watch_get_watchlo (struct pt_watch_regs *regs, int n)
void mips_linux_watch_set_watchlo (struct pt_watch_regs *regs, int n, CORE_ADDR value)
uint32_t mips_linux_watch_get_watchhi (struct pt_watch_regs *regs, int n)
void mips_linux_watch_set_watchhi (struct pt_watch_regs *regs, int n, uint16_t value)
int mips_linux_read_watch_registers (long lwpid, struct pt_watch_regs *watch_readback, int *watch_readback_valid, int force)
uint32_t mips_linux_watch_type_to_irw (int type)
static CORE_ADDR fill_mask (CORE_ADDR mask)
int mips_linux_watch_try_one_watch (struct pt_watch_regs *regs, CORE_ADDR addr, int len, uint32_t irw)
void mips_linux_watch_populate_regs (struct mips_watchpoint *current_watches, struct pt_watch_regs *regs)
Function Documentation
static CORE_ADDR fill_mask (CORE_ADDR mask) [static]
Definition at line 219 of file mips-linux-watch.c.
Referenced by mips_linux_watch_try_one_watch().
static uint32_t get_reg_mask (struct pt_watch_regs * regs, int n) [static]
Definition at line 44 of file mips-linux-watch.c.
References _, internal_error(), and IRW_MASK.
Referenced by mips_linux_watch_try_one_watch().
int mips_linux_read_watch_registers (long lwpid, struct pt_watch_regs * watch_readback, int * watch_readback_valid, int force)
Definition at line 161 of file mips-linux-watch.c.
References ptrace().
Referenced by mips_linux_can_use_hw_breakpoint(), mips_linux_insert_watchpoint(), mips_linux_new_thread(), mips_linux_region_ok_for_hw_watchpoint(), and mips_linux_stopped_by_watchpoint().
uint32_t mips_linux_watch_get_irw_mask (struct pt_watch_regs * regs, int n)
Definition at line 26 of file mips-linux-watch.c.
References _, internal_error(), and IRW_MASK.
Referenced by mips_linux_can_use_hw_breakpoint(), and mips_linux_watch_try_one_watch().
uint32_t mips_linux_watch_get_num_valid (struct pt_watch_regs * regs)
Definition at line 61 of file mips-linux-watch.c.
References _, and internal_error().
Referenced by mips_linux_can_use_hw_breakpoint(), mips_linux_region_ok_for_hw_watchpoint(), mips_linux_stopped_by_watchpoint(), mips_linux_watch_populate_regs(), and mips_linux_watch_try_one_watch().
uint32_t mips_linux_watch_get_watchhi (struct pt_watch_regs * regs, int n)
Definition at line 120 of file mips-linux-watch.c.
References _, and internal_error().
Referenced by mips_linux_stopped_by_watchpoint(), mips_linux_watch_try_one_watch(), and mips_show_dr().
CORE_ADDR mips_linux_watch_get_watchlo (struct pt_watch_regs * regs, int n)
Definition at line 79 of file mips-linux-watch.c.
References _, and internal_error().
Referenced by mips_linux_watch_try_one_watch(), and mips_show_dr().
void mips_linux_watch_populate_regs (struct mips_watchpoint * current_watches, struct pt_watch_regs * regs)
Definition at line 325 of file mips-linux-watch.c.
References mips_watchpoint::addr, current_watches, gdb_assert, mips_watchpoint::len, mips_linux_watch_get_num_valid(), mips_linux_watch_set_watchhi(), mips_linux_watch_set_watchlo(), mips_linux_watch_try_one_watch(), mips_linux_watch_type_to_irw(), mips_watchpoint::next, and mips_watchpoint::type.
Referenced by mips_linux_insert_watchpoint(), and mips_linux_remove_watchpoint().
void mips_linux_watch_set_watchhi (struct pt_watch_regs * regs, int n, uint16_t value)
Definition at line 138 of file mips-linux-watch.c.
References _, and internal_error().
Referenced by mips_linux_watch_populate_regs(), and mips_linux_watch_try_one_watch().
void mips_linux_watch_set_watchlo (struct pt_watch_regs * regs, int n, CORE_ADDR value)
Definition at line 97 of file mips-linux-watch.c.
References _, and internal_error().
Referenced by mips_linux_region_ok_for_hw_watchpoint(), mips_linux_watch_populate_regs(), and mips_linux_watch_try_one_watch().
int mips_linux_watch_try_one_watch (struct pt_watch_regs * regs, CORE_ADDR addr, int len, uint32_t irw)
Definition at line 236 of file mips-linux-watch.c.
References fill_mask(), get_reg_mask(), IRW_MASK, len, mips_linux_watch_get_irw_mask(), mips_linux_watch_get_num_valid(), mips_linux_watch_get_watchhi(), mips_linux_watch_get_watchlo(), mips_linux_watch_set_watchhi(), and mips_linux_watch_set_watchlo().
Referenced by mips_linux_insert_watchpoint(), mips_linux_region_ok_for_hw_watchpoint(), and mips_linux_watch_populate_regs().
uint32_t mips_linux_watch_type_to_irw (int type)
Definition at line 201 of file mips-linux-watch.c.
References hw_access, hw_read, hw_write, R_MASK, and W_MASK.
Referenced by mips_linux_insert_watchpoint(), and mips_linux_watch_populate_regs().