GDB (xrefs): /home/stan/gdb/src/gdb/mipsnbsd-tdep.h File Reference
/home/stan/gdb/src/gdb/mipsnbsd-tdep.h File Reference
Functions
void mipsnbsd_supply_reg (struct regcache *, const char *, int)
void mipsnbsd_fill_reg (const struct regcache *, char *, int)
void mipsnbsd_supply_fpreg (struct regcache *, const char *, int)
void mipsnbsd_fill_fpreg (const struct regcache *, char *, int)
Function Documentation
void mipsnbsd_fill_fpreg (const struct regcache * , char * , int)
Definition at line 199 of file mipsnbsd-tdep.c.
References mips_regnum::fp_control_status, gdbarch_cannot_store_register(), gdbarch_fp0_regnum(), get_regcache_arch(), mips_isa_regsize(), mips_regnum(), and regcache_raw_collect().
Referenced by mipsnbsd_store_inferior_registers().
void mipsnbsd_fill_reg (const struct regcache * , char * , int)
Definition at line 162 of file mipsnbsd-tdep.c.
References gdbarch_cannot_store_register(), gdbarch_pc_regnum(), get_regcache_arch(), mips_isa_regsize(), and regcache_raw_collect().
Referenced by mipsnbsd_store_inferior_registers().
void mipsnbsd_supply_fpreg (struct regcache * , const char * , int)
Definition at line 175 of file mipsnbsd-tdep.c.
References mips_regnum::fp_implementation_revision, gdbarch_cannot_fetch_register(), gdbarch_fp0_regnum(), get_regcache_arch(), mips_isa_regsize(), mips_regnum(), and regcache_raw_supply().
Referenced by mipsnbsd_fetch_inferior_registers().
void mipsnbsd_supply_reg (struct regcache * , const char * , int)
Definition at line 143 of file mipsnbsd-tdep.c.
References gdbarch_cannot_fetch_register(), gdbarch_pc_regnum(), get_regcache_arch(), mips_isa_regsize(), and regcache_raw_supply().
Referenced by mipsnbsd_fetch_inferior_registers().