GDB (xrefs): /home/stan/gdb/src/gdb/monitor.h File Reference
/home/stan/gdb/src/gdb/monitor.h File Reference
Classes
struct memrw_cmd
struct regrw_cmd
struct monitor_ops
Defines
#define MONITOR_OPS_MAGIC 600925
#define MO_CLR_BREAK_USES_ADDR 0x1
#define MO_FILL_USES_ADDR 0x2
#define MO_NEED_REGDUMP_AFTER_CONT 0x4
#define MO_GETMEM_NEEDS_RANGE 0x8
#define MO_GETMEM_READ_SINGLE 0x10
#define MO_HANDLE_NL 0x20
#define MO_NO_ECHO_ON_OPEN 0x40
#define MO_SEND_BREAK_ON_STOP 0x80
#define MO_SREC_ACK 0x100
#define MO_HEX_PREFIX 0x200
#define MO_RUN_FIRST_TIME 0x400
#define MO_NO_ECHO_ON_SETMEM 0x800
#define MO_REGISTER_VALUE_FIRST 0x1000
#define MO_32_REGS_PAIRED 0x2000
#define MO_SETREG_INTERACTIVE 0x4000
#define MO_SETMEM_INTERACTIVE 0x8000
#define MO_GETMEM_16_BOUNDARY 0x10000
#define MO_CLR_BREAK_1_BASED 0x20000
#define MO_SREC_ACK_PLUS 0x40000
#define MO_SREC_ACK_ROTATE 0x80000
#define MO_ADDR_BITS_REMOVE 0x100000
#define MO_PRINT_PROGRAM_OUTPUT 0x200000
#define MO_EXACT_DUMPADDR 0x400000
#define MO_HAS_BLOCKWRITES 0x800000
#define SREC_SIZE 160
Functions
void monitor_open (char *args, struct monitor_ops *ops, int from_tty)
void monitor_close (void)
char * monitor_supply_register (struct regcache *regcache, int regno, char *valstr)
int monitor_expect (char *prompt, char *buf, int buflen)
int monitor_expect_prompt (char *buf, int buflen)
void monitor_printf (char *,...)
void monitor_printf_noecho (char *,...)
void monitor_write (char *buf, int buflen)
int monitor_readchar (void)
char * monitor_get_dev_name (void)
void init_monitor_ops (struct target_ops *)
int monitor_dump_reg_block (struct regcache *regcache, char *dump_cmd)
Define Documentation
#define MO_32_REGS_PAIRED 0x2000
Definition at line 191 of file monitor.h.
Referenced by _initialize_dink32_rom(), and monitor_fetch_register().
#define MO_ADDR_BITS_REMOVE 0x100000
Definition at line 220 of file monitor.h.
Referenced by monitor_insert_breakpoint(), monitor_read_memory(), and monitor_write_memory().
#define MO_CLR_BREAK_1_BASED 0x20000
Definition at line 208 of file monitor.h.
Referenced by _initialize_dink32_rom(), and monitor_remove_breakpoint().
#define MO_CLR_BREAK_USES_ADDR 0x1
Definition at line 137 of file monitor.h.
Referenced by init_dbug_cmds(), init_m32r_cmds(), init_mon2000_cmds(), init_picobug_cmds(), init_ppc_cmds(), and monitor_remove_breakpoint().
#define MO_EXACT_DUMPADDR 0x400000
Definition at line 230 of file monitor.h.
Referenced by monitor_read_memory().
#define MO_FILL_USES_ADDR 0x2
Definition at line 142 of file monitor.h.
Referenced by _initialize_dink32_rom(), init_dbug_cmds(), and monitor_write_memory().
#define MO_GETMEM_16_BOUNDARY 0x10000
Definition at line 204 of file monitor.h.
Referenced by _initialize_dink32_rom(), and monitor_read_memory().
#define MO_GETMEM_NEEDS_RANGE 0x8
Definition at line 151 of file monitor.h.
Referenced by _initialize_dink32_rom(), init_dbug_cmds(), init_picobug_cmds(), and monitor_read_memory().
#define MO_GETMEM_READ_SINGLE 0x10
Definition at line 155 of file monitor.h.
Referenced by monitor_read_memory().
#define MO_HANDLE_NL 0x20
Definition at line 159 of file monitor.h.
Referenced by _initialize_dink32_rom(), init_ppc_cmds(), and readchar().
#define MO_HAS_BLOCKWRITES 0x800000
Definition at line 238 of file monitor.h.
Referenced by monitor_xfer_memory().
#define MO_HEX_PREFIX 0x200
Definition at line 175 of file monitor.h.
Referenced by _initialize_dink32_rom(), monitor_fetch_register(), and monitor_read_memory_single().
#define MO_NEED_REGDUMP_AFTER_CONT 0x4
Definition at line 147 of file monitor.h.
Referenced by monitor_resume().
#define MO_NO_ECHO_ON_OPEN 0x40
Definition at line 163 of file monitor.h.
Referenced by monitor_open().
#define MO_NO_ECHO_ON_SETMEM 0x800
Definition at line 183 of file monitor.h.
Referenced by monitor_write_memory().
#define MO_PRINT_PROGRAM_OUTPUT 0x200000
Definition at line 224 of file monitor.h.
Referenced by init_picobug_cmds(), monitor_wait(), and monitor_wait_filter().
#define MO_REGISTER_VALUE_FIRST 0x1000
Definition at line 187 of file monitor.h.
Referenced by init_m32r_cmds(), init_mon2000_cmds(), and monitor_store_register().
#define MO_RUN_FIRST_TIME 0x400
Definition at line 179 of file monitor.h.
Referenced by monitor_resume().
#define MO_SEND_BREAK_ON_STOP 0x80
Definition at line 167 of file monitor.h.
Referenced by monitor_stop().
#define MO_SETMEM_INTERACTIVE 0x8000
Definition at line 199 of file monitor.h.
Referenced by _initialize_dink32_rom(), and monitor_write_memory().
#define MO_SETREG_INTERACTIVE 0x4000
Definition at line 195 of file monitor.h.
Referenced by _initialize_dink32_rom(), and monitor_store_register().
#define MO_SREC_ACK 0x100
Definition at line 171 of file monitor.h.
Referenced by _initialize_dink32_rom(), and monitor_load().
#define MO_SREC_ACK_PLUS 0x40000
Definition at line 212 of file monitor.h.
Referenced by monitor_wait_srec_ack().
#define MO_SREC_ACK_ROTATE 0x80000
Definition at line 216 of file monitor.h.
Referenced by _initialize_dink32_rom(), and monitor_wait_srec_ack().
#define MONITOR_OPS_MAGIC 600925
Definition at line 130 of file monitor.h.
Referenced by _initialize_dink32_rom(), init_dbug_cmds(), init_m32r_cmds(), init_mon2000_cmds(), init_picobug_cmds(), init_ppc_cmds(), and monitor_open().
#define SREC_SIZE 160
Definition at line 240 of file monitor.h.
Function Documentation
void init_monitor_ops (struct target_ops *)
Definition at line 2390 of file monitor.c.
References init_base_monitor_ops(), memcpy(), and OPS_MAGIC.
Referenced by _initialize_dbug_rom(), _initialize_dink32_rom(), _initialize_m32r_rom(), _initialize_picobug_rom(), and _initialize_ppcbug_rom().
void monitor_close (void)
Definition at line 856 of file monitor.c.
References breakaddr, delete_inferior_silent(), delete_thread_silent(), ptid_get_pid(), serial_close(), and xfree().
Referenced by init_base_monitor_ops().
int monitor_dump_reg_block (struct regcache * regcache, char * dump_cmd)
Definition at line 1291 of file monitor.c.
References monitor_expect_prompt(), monitor_printf(), parse_register_dump(), and TARGET_BUF_SIZE.
int monitor_expect (char * prompt, char * buf, int buflen)
Definition at line 502 of file monitor.c.
References fprintf_unfiltered(), gdb_stdlog, immediate_quit, memcmp(), monitor_debug_p, monitor_printable_string(), p, QUIT, readchar(), string, and timeout.
Referenced by m32r_load(), m32r_load_section(), monitor_expect_prompt(), monitor_fetch_register(), monitor_load(), monitor_printf(), monitor_read_memory(), monitor_read_memory_single(), monitor_store_register(), and monitor_write_memory().
int monitor_expect_prompt (char * buf, int buflen)
Definition at line 653 of file monitor.c.
References monitor_debug(), monitor_expect(), and monitor_ops::prompt.
Referenced by m32r_load(), m32r_load_section(), m32r_upload_command(), monitor_dump_reg_block(), monitor_dump_regs(), monitor_fetch_register(), monitor_insert_breakpoint(), monitor_load(), monitor_open(), monitor_rcmd(), monitor_read_memory(), monitor_read_memory_single(), monitor_remove_breakpoint(), monitor_store_register(), monitor_wait(), monitor_wait_filter(), monitor_write_memory(), monitor_write_memory_bytes(), monitor_write_memory_longlongs(), and picobug_dumpregs().
char* monitor_get_dev_name (void)
Definition at line 2319 of file monitor.c.
References dev_name.
void monitor_open (char * args, struct monitor_ops * ops, int from_tty)
Definition at line 715 of file monitor.c.
References _, add_thread_silent(), baud_rate, breakaddr, monitor_ops::clr_all_break, compile_pattern(), current_inferior(), dev_name, error(), monitor_ops::flags, monitor_ops::getmem, getmem_resp_delim_fastmap, getmem_resp_delim_pattern, arm-linux::inf, inferior_appeared(), inferior_ptid, monitor_ops::init, init_thread_list(), init_wait_for_inferior(), monitor_ops::line_term, monitor_ops::magic, memset(), MO_NO_ECHO_ON_OPEN, monitor_debug(), monitor_expect_prompt(), MONITOR_OPS_MAGIC, monitor_printf(), monitor_printf_noecho(), monitor_ptid, monitor_stop(), name, monitor_ops::num_breakpoints, p, perror_with_name(), printf_unfiltered(), ptid_get_pid(), push_target(), register_fastmap, register_pattern, monitor_ops::register_pattern, memrw_cmd::resp_delim, regrw_cmd::resp_delim, serial_close(), serial_flush_input(), serial_open(), serial_raw(), serial_setbaudrate(), serial_setstopbits(), monitor_ops::set_break, monitor_ops::setmem, setmem_resp_delim_fastmap, setmem_resp_delim_pattern, monitor_ops::setreg, setreg_resp_delim_fastmap, setreg_resp_delim_pattern, start_remote(), monitor_ops::stop, monitor_ops::stopbits, monitor_ops::target, target_preopen(), target_ops::to_shortname, unpush_target(), xfree(), and xmalloc().
Referenced by dbug_open(), dink32_open(), m32r_open(), mon2000_open(), picobug_open(), ppcbug_open0(), and ppcbug_open1().
void monitor_printf (char * , ...)
Definition at line 343 of file monitor.c.
References _, fprintf_unfiltered(), gdb_stdlog, internal_error(), len, monitor_debug(), monitor_debug_p, monitor_expect(), monitor_printable_string(), monitor_vsprintf(), and monitor_write().
Referenced by m32r_load(), m32r_load_section(), m32r_upload_command(), monitor_dump_reg_block(), monitor_dump_regs(), monitor_fetch_register(), monitor_insert_breakpoint(), monitor_load(), monitor_open(), monitor_rcmd(), monitor_read_memory(), monitor_read_memory_single(), monitor_remove_breakpoint(), monitor_resume(), monitor_store_register(), monitor_wait(), monitor_write_memory(), monitor_write_memory_bytes(), monitor_write_memory_longlongs(), and picobug_dumpregs().
void monitor_printf_noecho (char * , ...)
Definition at line 313 of file monitor.c.
References _, fprintf_unfiltered(), gdb_stdlog, internal_error(), len, monitor_debug_p, monitor_printable_string(), monitor_vsprintf(), and monitor_write().
Referenced by monitor_open(), monitor_stop(), and monitor_write_memory().
int monitor_readchar (void)
Definition at line 394 of file monitor.c.
References _, error(), perror_with_name(), serial_readchar(), SERIAL_TIMEOUT, and timeout.
char* monitor_supply_register (struct regcache * regcache, int regno, char * valstr)
Definition at line 888 of file monitor.c.
References _, gdbarch::byte_order, error(), fromhex(), gdbarch_byte_order(), get_regcache_arch(), MAX_REGISTER_SIZE, monitor_debug(), p, regcache_raw_supply(), register_size(), store_unsigned_integer(), and ULONGEST.
Referenced by dbug_supply_register(), dink32_supply_register(), m32r_supply_register(), monitor_fetch_register(), picobug_dumpregs(), and ppcbug_supply_register().
void monitor_write (char * buf, int buflen)
Definition at line 381 of file monitor.c.
References fprintf_unfiltered(), gdb_stderr, safe_strerror(), and serial_write().
Referenced by monitor_printf(), and monitor_printf_noecho().