GDB (xrefs): /home/stan/gdb/src/gdb/moxie-tdep.c File Reference
/home/stan/gdb/src/gdb/moxie-tdep.c File Reference
#include "defs.h"
#include "frame.h"
#include "frame-unwind.h"
#include "frame-base.h"
#include "symtab.h"
#include "gdbtypes.h"
#include "gdbcmd.h"
#include "gdbcore.h"
#include "gdb_string.h"
#include "value.h"
#include "inferior.h"
#include "symfile.h"
#include "objfiles.h"
#include "osabi.h"
#include "language.h"
#include "arch-utils.h"
#include "regcache.h"
#include "trad-frame.h"
#include "dis-asm.h"
#include "record.h"
#include "record-full.h"
#include "gdb_assert.h"
#include "moxie-tdep.h"
Classes
struct moxie_frame_cache
struct moxie_unwind_cache
Enumerations
enum { REG_UNAVAIL = (CORE_ADDR) -1 }
Functions
void _initialize_moxie_tdep (void)
static CORE_ADDR moxie_frame_align (struct gdbarch *gdbarch, CORE_ADDR sp)
static const unsigned char * moxie_breakpoint_from_pc (struct gdbarch *gdbarch, CORE_ADDR *pcptr, int *lenptr)
static const char * moxie_register_name (struct gdbarch *gdbarch, int reg_nr)
static struct type * moxie_register_type (struct gdbarch *gdbarch, int reg_nr)
static void moxie_store_return_value (struct type *type, struct regcache *regcache, const void *valbuf)
static CORE_ADDR moxie_analyze_prologue (CORE_ADDR start_addr, CORE_ADDR end_addr, struct moxie_frame_cache *cache, struct gdbarch *gdbarch)
static CORE_ADDR moxie_skip_prologue (struct gdbarch *gdbarch, CORE_ADDR pc)
static CORE_ADDR moxie_read_pc (struct regcache *regcache)
static void moxie_write_pc (struct regcache *regcache, CORE_ADDR val)
static CORE_ADDR moxie_unwind_sp (struct gdbarch *gdbarch, struct frame_info *next_frame)
static void moxie_extract_return_value (struct type *type, struct regcache *regcache, void *dst)
static enum return_value_convention moxie_return_value (struct gdbarch *gdbarch, struct value *function, struct type *valtype, struct regcache *regcache, gdb_byte *readbuf, const gdb_byte *writebuf)
static struct moxie_frame_cache * moxie_alloc_frame_cache (void)
static struct moxie_frame_cache * moxie_frame_cache (struct frame_info *this_frame, void **this_cache)
static CORE_ADDR moxie_unwind_pc (struct gdbarch *gdbarch, struct frame_info *next_frame)
static void moxie_frame_this_id (struct frame_info *this_frame, void **this_prologue_cache, struct frame_id *this_id)
static struct value * moxie_frame_prev_register (struct frame_info *this_frame, void **this_prologue_cache, int regnum)
static CORE_ADDR moxie_frame_base_address (struct frame_info *this_frame, void **this_cache)
static struct frame_id moxie_dummy_id (struct gdbarch *gdbarch, struct frame_info *this_frame)
static ULONGEST moxie_process_readu (CORE_ADDR addr, gdb_byte *buf, int length, enum bfd_endian byte_order)
static int moxie_process_record (struct gdbarch *gdbarch, struct regcache *regcache, CORE_ADDR addr)
static struct gdbarch * moxie_gdbarch_init (struct gdbarch_info info, struct gdbarch_list *arches)
Variables
char * moxie_register_names []
static struct frame_unwind moxie_frame_unwind
static struct frame_base moxie_frame_base
Enumeration Type Documentation
anonymous enum
Enumerator:
REG_UNAVAIL
Definition at line 51 of file moxie-tdep.c.
Function Documentation
void _initialize_moxie_tdep (void)
static struct moxie_frame_cache* moxie_alloc_frame_cache (void) [static, read]
Definition at line 364 of file moxie-tdep.c.
References moxie_frame_cache::base, FRAME_OBSTACK_ZALLOC, moxie_frame_cache::framesize, MOXIE_NUM_REGS, moxie_frame_cache::pc, REG_UNAVAIL, moxie_frame_cache::saved_regs, and moxie_frame_cache::saved_sp.
Referenced by moxie_frame_cache().
static CORE_ADDR moxie_analyze_prologue (CORE_ADDR start_addr, CORE_ADDR end_addr, struct moxie_frame_cache * cache, struct gdbarch * gdbarch) [static]
Definition at line 148 of file moxie-tdep.c.
References gdbarch::byte_order, moxie_frame_cache::framesize, gdbarch_byte_order(), LONGEST, MOXIE_FP_REGNUM, MOXIE_PC_REGNUM, offset, read_memory_integer(), read_memory_unsigned_integer(), regnum, moxie_frame_cache::saved_regs, and ULONGEST.
Referenced by moxie_frame_cache(), and moxie_skip_prologue().
static const unsigned char* moxie_breakpoint_from_pc (struct gdbarch * gdbarch, CORE_ADDR * pcptr, int * lenptr) [static]
Definition at line 76 of file moxie-tdep.c.
Referenced by moxie_gdbarch_init().
static struct frame_id moxie_dummy_id (struct gdbarch * gdbarch, struct frame_info * this_frame) [static, read]
Definition at line 491 of file moxie-tdep.c.
References frame_id_build(), get_frame_pc(), get_frame_register_unsigned(), MOXIE_SP_REGNUM, and sp.
Referenced by moxie_gdbarch_init().
static void moxie_extract_return_value (struct type * type, struct regcache * regcache, void * dst) [static]
Definition at line 319 of file moxie-tdep.c.
References gdbarch::byte_order, gdbarch_byte_order(), get_regcache_arch(), len, regcache_cooked_read_unsigned(), RET1_REGNUM, store_unsigned_integer(), TYPE_LENGTH, and ULONGEST.
Referenced by moxie_return_value().
static CORE_ADDR moxie_frame_align (struct gdbarch * gdbarch, CORE_ADDR sp) [static]
Definition at line 66 of file moxie-tdep.c.
Referenced by moxie_gdbarch_init().
static CORE_ADDR moxie_frame_base_address (struct frame_info * this_frame, void ** this_cache) [static]
Definition at line 475 of file moxie-tdep.c.
References moxie_frame_cache::base, and moxie_frame_cache().
static struct moxie_frame_cache* moxie_frame_cache (struct frame_info * this_frame, void ** this_cache) [static, read]
Definition at line 384 of file moxie-tdep.c.
References moxie_frame_cache::base, moxie_frame_cache::framesize, get_frame_arch(), get_frame_func(), get_frame_pc(), get_frame_register_unsigned(), moxie_alloc_frame_cache(), moxie_analyze_prologue(), MOXIE_FP_REGNUM, MOXIE_NUM_REGS, moxie_frame_cache::pc, REG_UNAVAIL, moxie_frame_cache::saved_regs, and moxie_frame_cache::saved_sp.
Referenced by moxie_frame_base_address(), moxie_frame_prev_register(), and moxie_frame_this_id().
static struct value* moxie_frame_prev_register (struct frame_info * this_frame, void ** this_prologue_cache, int regnum) [static, read]
Definition at line 445 of file moxie-tdep.c.
References frame_unwind_got_constant(), frame_unwind_got_memory(), frame_unwind_got_register(), gdb_assert, moxie_frame_cache(), MOXIE_SP_REGNUM, REG_UNAVAIL, moxie_frame_cache::saved_regs, and moxie_frame_cache::saved_sp.
static void moxie_frame_this_id (struct frame_info * this_frame, void ** this_prologue_cache, struct frame_id * this_id) [static]
Definition at line 429 of file moxie-tdep.c.
References moxie_frame_cache::base, frame_id_build(), moxie_frame_cache(), moxie_frame_cache::pc, and moxie_frame_cache::saved_sp.
static struct gdbarch* moxie_gdbarch_init (struct gdbarch_info info, struct gdbarch_list * arches) [static, read]
Definition at line 941 of file moxie-tdep.c.
References core_addr_lessthan(), frame_base_set_default(), frame_unwind_append_unwinder(), gdbarch_list::gdbarch, gdbarch_alloc(), gdbarch_init_osabi(), gdbarch_list_lookup_by_info(), moxie_breakpoint_from_pc(), moxie_dummy_id(), moxie_frame_align(), MOXIE_NUM_REGS, MOXIE_PC_REGNUM, moxie_process_record(), moxie_read_pc(), moxie_register_name(), moxie_register_type(), moxie_return_value(), moxie_skip_prologue(), MOXIE_SP_REGNUM, moxie_unwind_pc(), moxie_unwind_sp(), moxie_write_pc(), set_gdbarch_breakpoint_from_pc(), set_gdbarch_dummy_id(), set_gdbarch_frame_align(), set_gdbarch_inner_than(), set_gdbarch_num_regs(), set_gdbarch_overlay_update(), set_gdbarch_pc_regnum(), set_gdbarch_print_insn(), set_gdbarch_process_record(), set_gdbarch_read_pc(), set_gdbarch_register_name(), set_gdbarch_register_type(), set_gdbarch_return_value(), set_gdbarch_skip_prologue(), set_gdbarch_sp_regnum(), set_gdbarch_unwind_pc(), set_gdbarch_unwind_sp(), set_gdbarch_write_pc(), simple_overlay_update(), and XMALLOC.
static ULONGEST moxie_process_readu (CORE_ADDR addr, gdb_byte * buf, int length, enum bfd_endian byte_order) [static]
Definition at line 501 of file moxie-tdep.c.
References _, extract_unsigned_integer(), paddress(), printf_unfiltered(), record_debug, target_gdbarch(), and target_read_memory().
Referenced by moxie_process_record().
static int moxie_process_record (struct gdbarch * gdbarch, struct regcache * regcache, CORE_ADDR addr) [static]
Definition at line 521 of file moxie-tdep.c.
References extract_unsigned_integer(), fprintf_unfiltered(), gdb_stdlog, gdbarch_byte_order(), MOXIE_CC_REGNUM, MOXIE_FP_REGNUM, MOXIE_PC_REGNUM, moxie_process_readu(), MOXIE_SP_REGNUM, offset, paddress(), record_debug, record_full_arch_list_add_end(), record_full_arch_list_add_mem(), record_full_arch_list_add_reg(), regcache_raw_read(), RET1_REGNUM, and target_gdbarch().
Referenced by moxie_gdbarch_init().
static CORE_ADDR moxie_read_pc (struct regcache * regcache) [static]
Definition at line 291 of file moxie-tdep.c.
References MOXIE_PC_REGNUM, regcache_cooked_read_unsigned(), and ULONGEST.
Referenced by moxie_gdbarch_init().
static const char* moxie_register_name (struct gdbarch * gdbarch, int reg_nr) [static]
Definition at line 96 of file moxie-tdep.c.
References MOXIE_NUM_REGS.
Referenced by moxie_gdbarch_init().
static struct type* moxie_register_type (struct gdbarch * gdbarch, int reg_nr) [static, read]
Definition at line 108 of file moxie-tdep.c.
References builtin_type::builtin_data_ptr, builtin_type::builtin_func_ptr, builtin_type::builtin_int32, builtin_type(), MOXIE_FP_REGNUM, MOXIE_PC_REGNUM, and MOXIE_SP_REGNUM.
Referenced by moxie_gdbarch_init().
static enum return_value_convention moxie_return_value (struct gdbarch * gdbarch, struct value * function, struct type * valtype, struct regcache * regcache, gdb_byte * readbuf, const gdb_byte * writebuf) [static]
Definition at line 345 of file moxie-tdep.c.
References moxie_extract_return_value(), moxie_store_return_value(), RETURN_VALUE_REGISTER_CONVENTION, RETURN_VALUE_STRUCT_CONVENTION, and TYPE_LENGTH.
Referenced by moxie_gdbarch_init().
static CORE_ADDR moxie_skip_prologue (struct gdbarch * gdbarch, CORE_ADDR pc) [static]
Definition at line 219 of file moxie-tdep.c.
References symtab_and_line::end, find_pc_line(), find_pc_partial_function(), language_asm, lookup_symbol(), max, memset(), moxie_analyze_prologue(), moxie_frame_cache::pc, skip_prologue_using_sal(), SYMBOL_LANGUAGE, and VAR_DOMAIN.
Referenced by moxie_gdbarch_init().
static void moxie_store_return_value (struct type * type, struct regcache * regcache, const void * valbuf) [static]
Definition at line 122 of file moxie-tdep.c.
References gdbarch::byte_order, extract_unsigned_integer(), gdbarch_byte_order(), get_regcache_arch(), len, regcache_cooked_write_unsigned(), RET1_REGNUM, and TYPE_LENGTH.
Referenced by moxie_return_value().
static CORE_ADDR moxie_unwind_pc (struct gdbarch * gdbarch, struct frame_info * next_frame) [static]
Definition at line 420 of file moxie-tdep.c.
References frame_unwind_register_unsigned(), and MOXIE_PC_REGNUM.
Referenced by moxie_gdbarch_init().
static CORE_ADDR moxie_unwind_sp (struct gdbarch * gdbarch, struct frame_info * next_frame) [static]
Definition at line 310 of file moxie-tdep.c.
References frame_unwind_register_unsigned(), and MOXIE_SP_REGNUM.
Referenced by moxie_gdbarch_init().
static void moxie_write_pc (struct regcache * regcache, CORE_ADDR val) [static]
Definition at line 302 of file moxie-tdep.c.
References MOXIE_PC_REGNUM, and regcache_cooked_write_unsigned().
Referenced by moxie_gdbarch_init().
Variable Documentation
struct frame_base moxie_frame_base [static]
Initial value:
 {
  &moxie_frame_unwind,
  moxie_frame_base_address,
  moxie_frame_base_address,
  moxie_frame_base_address
}
Definition at line 483 of file moxie-tdep.c.
struct frame_unwind moxie_frame_unwind [static]
Initial value:
 {
  NORMAL_FRAME,
  default_frame_unwind_stop_reason,
  moxie_frame_this_id,
  moxie_frame_prev_register,
  NULL,
  default_frame_sniffer
}
Definition at line 463 of file moxie-tdep.c.
char* moxie_register_names[]
Initial value:
 {
  "$fp",  "$sp",  "$r0",  "$r1",  "$r2",
  "$r3",  "$r4",  "$r5", "$r6", "$r7",
  "$r8", "$r9", "$r10", "$r11", "$r12",
  "$r13", "$pc", "$cc" }
Definition at line 87 of file moxie-tdep.c.