GDB (xrefs): gdb::prompt Namespace Reference
gdb::prompt Namespace Reference
Functions
def _prompt_pwd
def _prompt_object_attr
def _prompt_frame
def _prompt_thread
def _prompt_version
def _prompt_esc
def _prompt_bs
def _prompt_n
def _prompt_r
def _prompt_param
def _prompt_noprint_begin
def _prompt_noprint_end
def prompt_help
def substitute_prompt
Variables
dictionary prompt_substitutions
Function Documentation
def gdb::prompt::_prompt_bs (attr) [private]
Definition at line 58 of file prompt.py.
def gdb::prompt::_prompt_esc (attr) [private]
Definition at line 54 of file prompt.py.
def gdb::prompt::_prompt_frame (attr) [private]
Definition at line 42 of file prompt.py.
References _prompt_object_attr().
def gdb::prompt::_prompt_n (attr) [private]
Definition at line 62 of file prompt.py.
def gdb::prompt::_prompt_noprint_begin (attr) [private]
Definition at line 74 of file prompt.py.
def gdb::prompt::_prompt_noprint_end (attr) [private]
Definition at line 78 of file prompt.py.
def gdb::prompt::_prompt_object_attr (func, what, attr, nattr) [private]
Internal worker for fetching GDB attributes.
Definition at line 26 of file prompt.py.
References func.
Referenced by _prompt_frame(), and _prompt_thread().
def gdb::prompt::_prompt_param (attr) [private]
Definition at line 70 of file prompt.py.
def gdb::prompt::_prompt_pwd (ignore) [private]
Definition at line 22 of file prompt.py.
def gdb::prompt::_prompt_r (attr) [private]
Definition at line 66 of file prompt.py.
def gdb::prompt::_prompt_thread (attr) [private]
Definition at line 46 of file prompt.py.
References _prompt_object_attr().
def gdb::prompt::_prompt_version (attr) [private]
Definition at line 50 of file prompt.py.
def gdb::prompt::prompt_help ()
Generate help dynamically from the __doc__ strings of attribute
functions.
Definition at line 96 of file prompt.py.
def gdb::prompt::substitute_prompt (prompt)
Definition at line 110 of file prompt.py.
References len.
Variable Documentation
dictionary gdb::prompt::prompt_substitutions
Initial value:
{
    'e': _prompt_esc,
    '\\': _prompt_bs,
    'n': _prompt_n,
    'r': _prompt_r,
    'v': _prompt_version,
    'w': _prompt_pwd,
    'f': _prompt_frame,
    't': _prompt_thread,
    'p': _prompt_param,
    '[': _prompt_noprint_begin,
    ']': _prompt_noprint_end
}
Definition at line 82 of file prompt.py.