GDB (xrefs): /home/stan/gdb/src/gdb/nbsd-nat.h File Reference
/home/stan/gdb/src/gdb/nbsd-nat.h File Reference
Functions
char * nbsd_pid_to_exec_file (int pid)
Function Documentation
char* nbsd_pid_to_exec_file (int pid)
Definition at line 28 of file nbsd-nat.c.
References len, xcalloc(), xfree(), and xstrprintf().
Referenced by _initialize_amd64nbsd_nat(), _initialize_hppanbsd_nat(), and _initialize_i386nbsd_nat().