GDB (xrefs): /home/stan/gdb/src/gdb/nios2-linux-tdep.c File Reference
/home/stan/gdb/src/gdb/nios2-linux-tdep.c File Reference
#include "defs.h"
#include "frame.h"
#include "gdb_assert.h"
#include "gdb_string.h"
#include "osabi.h"
#include "solib-svr4.h"
#include "trad-frame.h"
#include "tramp-frame.h"
#include "symtab.h"
#include "regset.h"
#include "regcache.h"
#include "linux-tdep.h"
#include "glibc-tdep.h"
#include "nios2-tdep.h"
#include "features/nios2-linux.c"
Functions
static void nios2_supply_gregset (const struct regset *regset, struct regcache *regcache, int regnum, const void *gregs_buf, size_t len)
static struct regset * nios2_regset_from_core_section (struct gdbarch *gdbarch, const char *sect_name, size_t sect_size)
static void nios2_linux_sigreturn_init (const struct tramp_frame *self, struct frame_info *next_frame, struct trad_frame_cache *this_cache, CORE_ADDR func)
static void nios2_linux_rt_sigreturn_init (const struct tramp_frame *self, struct frame_info *next_frame, struct trad_frame_cache *this_cache, CORE_ADDR func)
static CORE_ADDR nios2_linux_syscall_next_pc (struct frame_info *frame)
static void nios2_linux_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
void _initialize_nios2_linux_tdep (void)
Variables
static const int reg_offsets [NIOS2_NUM_REGS]
static struct regset nios2_core_regset
static struct tramp_frame nios2_linux_sigreturn_tramp_frame
static struct tramp_frame nios2_linux_rt_sigreturn_tramp_frame
initialize_file_ftype _initialize_nios2_linux_tdep
Function Documentation
void _initialize_nios2_linux_tdep (void)
Definition at line 227 of file nios2-linux-tdep.c.
References GDB_OSABI_LINUX, gdbarch_register_osabi(), initialize_tdesc_nios2_linux(), and nios2_linux_init_abi().
static void nios2_linux_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch) [static]
Definition at line 192 of file nios2-linux-tdep.c.
References find_solib_trampoline_target(), gdbarch_tdep(), glibc_skip_solib_resolver(), gdbarch_tdep::jb_pc, linux_init_abi(), nios2_linux_syscall_next_pc(), nios2_regset_from_core_section(), set_gdbarch_fetch_tls_load_module_address(), set_gdbarch_regset_from_core_section(), set_gdbarch_skip_solib_resolver(), set_gdbarch_skip_trampoline_code(), set_solib_svr4_fetch_link_map_offsets(), svr4_fetch_objfile_link_map(), svr4_ilp32_fetch_link_map_offsets(), gdbarch_tdep::syscall_next_pc, and tramp_frame_prepend_unwinder().
Referenced by _initialize_nios2_linux_tdep().
static void nios2_linux_rt_sigreturn_init (const struct tramp_frame * self, struct frame_info * next_frame, struct trad_frame_cache * this_cache, CORE_ADDR func) [static]
Definition at line 127 of file nios2-linux-tdep.c.
References frame_id_build(), NIOS2_FP_REGNUM, NIOS2_GP_REGNUM, NIOS2_PC_REGNUM, NIOS2_RA_REGNUM, NIOS2_SP_REGNUM, trad_frame_set_id(), and trad_frame_set_reg_addr().
static void nios2_linux_sigreturn_init (const struct tramp_frame * self, struct frame_info * next_frame, struct trad_frame_cache * this_cache, CORE_ADDR func) [static]
Definition at line 100 of file nios2-linux-tdep.c.
References frame_id_build(), NIOS2_ESTATUS_REGNUM, NIOS2_FP_REGNUM, NIOS2_GP_REGNUM, NIOS2_PC_REGNUM, NIOS2_RA_REGNUM, NIOS2_SP_REGNUM, trad_frame_set_id(), and trad_frame_set_reg_addr().
static CORE_ADDR nios2_linux_syscall_next_pc (struct frame_info * frame) [static]
Definition at line 175 of file nios2-linux-tdep.c.
References frame_unwind_caller_pc(), get_frame_pc(), get_frame_register_unsigned(), NIOS2_OPCODE_SIZE, NIOS2_R2_REGNUM, and ULONGEST.
Referenced by nios2_linux_init_abi().
static struct regset* nios2_regset_from_core_section (struct gdbarch * gdbarch, const char * sect_name, size_t sect_size) [static, read]
Definition at line 87 of file nios2-linux-tdep.c.
References nios2_core_regset.
Referenced by nios2_linux_init_abi().
static void nios2_supply_gregset (const struct regset * regset, struct regcache * regcache, int regnum, const void * gregs_buf, size_t len) [static]
Definition at line 57 of file nios2-linux-tdep.c.
References NIOS2_MPUACC_REGNUM, NIOS2_Z_REGNUM, reg_offsets, and regcache_raw_supply().
Variable Documentation
initialize_file_ftype _initialize_nios2_linux_tdep
Referenced by initialize_all_files().
struct regset nios2_core_regset [static]
Initial value:
{
  NULL,
  nios2_supply_gregset,
  NULL,
  NULL
}
Definition at line 76 of file nios2-linux-tdep.c.
Referenced by nios2_regset_from_core_section().
struct tramp_frame nios2_linux_rt_sigreturn_tramp_frame [static]
Initial value:
{
  SIGTRAMP_FRAME,
  4,
  {
    { 0x00800004 | (173 << 6), -1 },
    { 0x003b683a, -1 },
    { TRAMP_SENTINEL_INSN }
  },
  nios2_linux_rt_sigreturn_init
}
Definition at line 159 of file nios2-linux-tdep.c.
struct tramp_frame nios2_linux_sigreturn_tramp_frame [static]
Initial value:
{
  SIGTRAMP_FRAME,
  4,
  {
    { 0x00800004 | (119 << 6), -1 },
    { 0x003b683a, -1 },
    { TRAMP_SENTINEL_INSN }
  },
  nios2_linux_sigreturn_init
}
Definition at line 147 of file nios2-linux-tdep.c.
const int reg_offsets[NIOS2_NUM_REGS] [static]
Initial value:
{
  -1,  8,  9, 10, 11, 12, 13, 14,
  0,  1,  2,  3,  4,  5,  6,  7,
  23, 24, 25, 26, 27, 28, 29, 30,
  -1, -1, 19, 18, 17, 21, -1, 16,
  21,
  -1, 20, -1, -1, -1, -1, -1, -1,
  -1, -1, -1, -1, -1, -1, -1, -1
}
Definition at line 43 of file nios2-linux-tdep.c.
Referenced by nios2_supply_gregset().