GDB (xrefs): /home/stan/gdb/src/gdb/nto-tdep.c File Reference
/home/stan/gdb/src/gdb/nto-tdep.c File Reference
#include "defs.h"
#include "gdb_stat.h"
#include "gdb_string.h"
#include "nto-tdep.h"
#include "top.h"
#include "inferior.h"
#include "gdbarch.h"
#include "bfd.h"
#include "elf-bfd.h"
#include "solib-svr4.h"
#include "gdbcore.h"
#include "objfiles.h"
#include <string.h>
Classes
struct lm_info
Defines
#define PATH_FMT "%s/lib:%s/usr/lib:%s/usr/photon/lib:%s/usr/photon/dll:%s/lib/dll"
Functions
static char * nto_target (void)
int nto_map_arch_to_cputype (const char *arch)
int nto_find_and_open_solib (char *solib, unsigned o_flags, char **temp_pathname)
void nto_init_solib_absolute_prefix (void)
char ** nto_parse_redirection (char *pargv[], const char **pin, const char **pout, const char **perr)
static CORE_ADDR lm_addr (struct so_list *so)
static CORE_ADDR nto_truncate_ptr (CORE_ADDR addr)
static Elf_Internal_Phdr * find_load_phdr (bfd *abfd)
void nto_relocate_section_addresses (struct so_list *so, struct target_section *sec)
int nto_in_dynsym_resolve_code (CORE_ADDR pc)
void nto_dummy_supply_regset (struct regcache *regcache, char *regs)
enum gdb_osabi nto_elf_osabi_sniffer (bfd *abfd)
char * nto_extra_thread_info (struct thread_info *ti)
void nto_initialize_signals (void)
Variables
static char default_nto_target [] = ""
struct nto_target_ops current_nto_target
static const char * nto_thread_state_str []
Define Documentation
#define PATH_FMT "%s/lib:%s/usr/lib:%s/usr/photon/lib:%s/usr/photon/dll:%s/lib/dll"
Referenced by nto_find_and_open_solib().
Function Documentation
static Elf_Internal_Phdr* find_load_phdr (bfd * abfd) [static]
Definition at line 287 of file nto-tdep.c.
Referenced by nto_relocate_section_addresses().
static CORE_ADDR lm_addr (struct so_list * so) [static]
Definition at line 262 of file nto-tdep.c.
References builtin_type::builtin_data_ptr, builtin_type(), extract_typed_address(), lm_info::l_addr, link_map_offsets::l_addr_offset, lm_info::lm, so_list::lm_info, nto_fetch_link_map_offsets, and target_gdbarch().
Referenced by dsbt_current_sos(), frv_current_sos(), lm_info_read(), nto_relocate_section_addresses(), and target_translate_tls_address().
void nto_dummy_supply_regset (struct regcache * regcache, char * regs)
Definition at line 328 of file nto-tdep.c.
Referenced by init_i386nto_ops().
enum gdb_osabi nto_elf_osabi_sniffer (bfd * abfd)
Definition at line 334 of file nto-tdep.c.
References GDB_OSABI_UNKNOWN, and nto_is_nto_target.
Referenced by _initialize_i386nto_tdep().
char* nto_extra_thread_info (struct thread_info * ti)
Definition at line 367 of file nto-tdep.c.
References nto_thread_state_str, thread_info::private, and private_thread_info::state.
Referenced by init_procfs_ops().
int nto_find_and_open_solib (char * solib, unsigned o_flags, char ** temp_pathname)
Definition at line 87 of file nto-tdep.c.
References gdb_realpath(), gdbarch_bfd_arch_info(), gdbarch_byte_order(), len, nto_target(), openp(), OPF_RETURN_REALPATH, OPF_TRY_CWD_FIRST, PATH_FMT, target_gdbarch(), and xsnprintf().
Referenced by i386nto_init_abi().
int nto_in_dynsym_resolve_code (CORE_ADDR pc)
Definition at line 320 of file nto-tdep.c.
References in_plt_section().
Referenced by i386nto_init_abi().
void nto_init_solib_absolute_prefix (void)
Definition at line 149 of file nto-tdep.c.
References execute_command(), gdbarch_bfd_arch_info(), gdbarch_byte_order(), nto_target(), target_gdbarch(), and xsnprintf().
Referenced by do_attach().
void nto_initialize_signals (void)
Definition at line 376 of file nto-tdep.c.
References gdb_signal_from_name(), signal_pass_update(), signal_print_update(), and signal_stop_update().
Referenced by i386nto_init_abi().
int nto_map_arch_to_cputype (const char * arch)
Definition at line 71 of file nto-tdep.c.
References CPUTYPE_ARM, CPUTYPE_MIPS, CPUTYPE_PPC, CPUTYPE_SH, CPUTYPE_UNKNOWN, and CPUTYPE_X86.
Referenced by procfs_open().
char** nto_parse_redirection (char * pargv[], const char ** pin, const char ** pout, const char ** perr)
Definition at line 183 of file nto-tdep.c.
References p, and xcalloc().
Referenced by procfs_create_inferior().
void nto_relocate_section_addresses (struct so_list * so, struct target_section * sec)
Definition at line 305 of file nto-tdep.c.
References target_section::addr, target_section::endaddr, find_load_phdr(), lm_addr(), nto_truncate_ptr(), and target_section::the_bfd_section.
Referenced by i386nto_init_abi().
static char* nto_target (void) [static]
Definition at line 52 of file nto-tdep.c.
References default_nto_target, and p.
Referenced by nto_find_and_open_solib(), and nto_init_solib_absolute_prefix().
static CORE_ADDR nto_truncate_ptr (CORE_ADDR addr) [static]
Definition at line 276 of file nto-tdep.c.
References gdbarch_ptr_bit(), and target_gdbarch().
Referenced by nto_relocate_section_addresses().
Variable Documentation
struct nto_target_ops current_nto_target
Definition at line 49 of file nto-tdep.c.
char default_nto_target[] = "" [static]
Definition at line 46 of file nto-tdep.c.
Referenced by nto_target().
const char* nto_thread_state_str[] [static]
Initial value:
{
  "DEAD",
  "RUNNING",
  "READY",
  "STOPPED",
  "SEND",
  "RECEIVE",
  "REPLY",
  "STACK",
  "WAITTHREAD",
  "WAITPAGE",
  "SIGSUSPEND",
  "SIGWAITINFO",
  "NANOSLEEP",
  "MUTEX",
  "CONDVAR",
  "JOIN",
  "INTR",
  "SEM",
  "WAITCTX",
  "NET_SEND",
  "NET_REPLY"
}
Definition at line 341 of file nto-tdep.c.
Referenced by nto_extra_thread_info().