GDB (xrefs): /home/stan/gdb/src/gdb/objc-lang.h File Reference
/home/stan/gdb/src/gdb/objc-lang.h File Reference
#include "cp-support.h"
Functions
CORE_ADDR lookup_objc_class (struct gdbarch *gdbarch, char *classname)
CORE_ADDR lookup_child_selector (struct gdbarch *gdbarch, char *methodname)
char * objc_demangle (const char *mangled, int options)
int find_objc_msgcall (CORE_ADDR pc, CORE_ADDR *new_pc)
const char * find_imps (const char *method, VEC(const_char_ptr)**symbol_names)
struct value * value_nsstring (struct gdbarch *gdbarch, char *ptr, int len)
void start_msglist (void)
void add_msglist (struct stoken *str, int addcolon)
int end_msglist (void)
struct symbol * lookup_struct_typedef (char *name, const struct block *block, int noerr)
Function Documentation
void add_msglist (struct stoken * str, int addcolon)
Definition at line 427 of file objc-lang.c.
References len, stoken::length, msglist_len, msglist_sel, p, stoken::ptr, xfree(), and xmalloc().
int end_msglist (void)
Definition at line 465 of file objc-lang.c.
References _, error(), lookup_child_selector(), selname::msglist_len, msglist_len, selname::msglist_sel, msglist_sel, selname::next, p, parse_gdbarch, selname_chain, write_exp_elt_longcst(), and xfree().
const char* find_imps (const char * method, VEC(const_char_ptr)** symbol_names)
Definition at line 1105 of file objc-lang.c.
References find_methods(), gdb_assert, lookup_minimal_symbol(), lookup_symbol(), parse_method(), parse_selector(), SYMBOL_NATURAL_NAME, uniquify_strings(), VAR_DOMAIN, VEC_empty, and VEC_safe_push.
Referenced by decode_objc(), and find_function_symbols().
int find_objc_msgcall (CORE_ADDR pc, CORE_ADDR * new_pc)
Definition at line 1332 of file objc-lang.c.
References find_objc_msgcall_submethod(), find_objc_msgsend(), and nmethcalls.
Referenced by objc_skip_trampoline().
CORE_ADDR lookup_child_selector (struct gdbarch * gdbarch, char * methodname)
Definition at line 140 of file objc-lang.c.
References _, builtin_type::builtin_char, builtin_type(), call_function_by_hand(), complaint(), find_function_in_inferior(), lookup_minimal_symbol(), symfile_complaints, target_has_execution, value_as_long(), value_coerce_array(), and value_string().
Referenced by end_msglist(), evaluate_subexp_standard(), and value_nsstring().
CORE_ADDR lookup_objc_class (struct gdbarch * gdbarch, char * classname)
Definition at line 111 of file objc-lang.c.
References _, builtin_type::builtin_char, builtin_type(), call_function_by_hand(), complaint(), find_function_in_inferior(), lookup_minimal_symbol(), symfile_complaints, target_has_execution, value_as_long(), value_coerce_array(), and value_string().
Referenced by value_nsstring().
struct symbol* lookup_struct_typedef (char * name, const struct block * block, int noerr) [read]
Definition at line 86 of file objc-lang.c.
References _, error(), lookup_symbol(), STRUCT_DOMAIN, SYMBOL_TYPE, TYPE_CODE, and TYPE_CODE_STRUCT.
Referenced by value_nsstring().
char* objc_demangle (const char * mangled, int options)
Definition at line 223 of file objc-lang.c.
References strchr(), xfree(), and xmalloc().
Referenced by symbol_find_demangled_name().
void start_msglist (void)
Definition at line 412 of file objc-lang.c.
References selname::msglist_len, msglist_len, msglist_sel, selname_chain, and xmalloc().
struct value* value_nsstring (struct gdbarch * gdbarch, char * ptr, int len) [read]
Definition at line 169 of file objc-lang.c.
References _, builtin_type::builtin_char, builtin_type::builtin_data_ptr, builtin_type::builtin_long, builtin_type(), call_function_by_hand(), deprecated_set_value_type(), error(), find_function_in_inferior(), lookup_child_selector(), lookup_minimal_symbol(), lookup_objc_class(), lookup_pointer_type(), lookup_struct_typedef(), SYMBOL_TYPE, target_has_execution, type, value_coerce_array(), value_from_longest(), and value_string().
Referenced by evaluate_subexp_standard().