GDB (xrefs): /home/stan/gdb/src/gdb/objfiles.c File Reference
/home/stan/gdb/src/gdb/objfiles.c File Reference
#include "defs.h"
#include "bfd.h"
#include "symtab.h"
#include "symfile.h"
#include "objfiles.h"
#include "gdb-stabs.h"
#include "target.h"
#include "bcache.h"
#include "expression.h"
#include "parser-defs.h"
#include "gdb_assert.h"
#include <sys/types.h>
#include "gdb_stat.h"
#include <fcntl.h>
#include "gdb_obstack.h"
#include "gdb_string.h"
#include "hashtab.h"
#include "breakpoint.h"
#include "block.h"
#include "dictionary.h"
#include "source.h"
#include "addrmap.h"
#include "arch-utils.h"
#include "exec.h"
#include "observer.h"
#include "complaints.h"
#include "psymtab.h"
#include "solist.h"
#include "gdb_bfd.h"
#include "btrace.h"
Classes
struct objfile_pspace_info
Functions
static void objfiles_pspace_data_cleanup (struct program_space *pspace, void *arg)
static struct objfile_pspace_info * get_objfile_pspace_data (struct program_space *pspace)
static struct
objfile_per_bfd_storage * get_objfile_bfd_data (struct objfile *objfile, struct bfd *abfd)
static void free_objfile_per_bfd_storage (struct objfile_per_bfd_storage *storage)
static void objfile_bfd_data_free (struct bfd *unused, void *d)
void set_objfile_per_bfd (struct objfile *objfile)
static void add_to_objfile_sections_full (struct bfd *abfd, struct bfd_section *asect, struct objfile *objfile, int force)
static void add_to_objfile_sections (struct bfd *abfd, struct bfd_section *asect, void *objfilep)
void build_objfile_section_table (struct objfile *objfile)
struct objfile * allocate_objfile (bfd *abfd, const char *name, int flags)
struct gdbarch * get_objfile_arch (struct objfile *objfile)
int entry_point_address_query (CORE_ADDR *entry_p)
CORE_ADDR entry_point_address (void)
struct objfile * objfile_separate_debug_iterate (const struct objfile *parent, const struct objfile *objfile)
void put_objfile_before (struct objfile *objfile, struct objfile *before_this)
void objfile_to_front (struct objfile *objfile)
void unlink_objfile (struct objfile *objfile)
void add_separate_debug_objfile (struct objfile *objfile, struct objfile *parent)
void free_objfile_separate_debug (struct objfile *objfile)
void free_objfile (struct objfile *objfile)
static void do_free_objfile_cleanup (void *obj)
struct cleanup * make_cleanup_free_objfile (struct objfile *obj)
void free_all_objfiles (void)
static void relocate_one_symbol (struct symbol *sym, struct objfile *objfile, struct section_offsets *delta)
static int objfile_relocate1 (struct objfile *objfile, const struct section_offsets *new_offsets)
void objfile_relocate (struct objfile *objfile, const struct section_offsets *new_offsets)
static int objfile_rebase1 (struct objfile *objfile, CORE_ADDR slide)
void objfile_rebase (struct objfile *objfile, CORE_ADDR slide)
int objfile_has_partial_symbols (struct objfile *objfile)
int objfile_has_full_symbols (struct objfile *objfile)
int objfile_has_symbols (struct objfile *objfile)
int have_partial_symbols (void)
int have_full_symbols (void)
void objfile_purge_solibs (void)
int have_minimal_symbols (void)
static int qsort_cmp (const void *a, const void *b)
static struct obj_section * preferred_obj_section (struct obj_section *a, struct obj_section *b)
static int insert_section_p (const struct bfd *abfd, const struct bfd_section *section)
static int filter_debuginfo_sections (struct obj_section **map, int map_size)
static int filter_overlapping_sections (struct obj_section **map, int map_size)
static void update_section_map (struct program_space *pspace, struct obj_section ***pmap, int *pmap_size)
static int bsearch_cmp (const void *key, const void *elt)
struct obj_section * find_pc_section (CORE_ADDR pc)
int pc_in_section (CORE_ADDR pc, char *name)
void objfiles_changed (void)
void inhibit_section_map_updates (struct program_space *pspace)
void resume_section_map_updates (struct program_space *pspace)
void resume_section_map_updates_cleanup (void *arg)
void default_iterate_over_objfiles_in_search_order (struct gdbarch *gdbarch, iterate_over_objfiles_in_search_order_cb_ftype *cb, void *cb_data, struct objfile *current_objfile)
const char * objfile_name (const struct objfile *objfile)
void _initialize_objfiles (void)
Variables
static struct program_space_data * objfiles_pspace_data
static struct bfd_data * objfiles_bfd_data
initialize_file_ftype _initialize_objfiles
Function Documentation
void _initialize_objfiles (void)
Definition at line 1511 of file objfiles.c.
References objfile_bfd_data_free(), objfiles_bfd_data, objfiles_pspace_data, and objfiles_pspace_data_cleanup().
void add_separate_debug_objfile (struct objfile * objfile, struct objfile * parent)
Definition at line 500 of file objfiles.c.
References gdb_assert, put_objfile_before(), objfile::separate_debug_objfile, objfile::separate_debug_objfile_backlink, and objfile::separate_debug_objfile_link.
Referenced by symbol_file_add_with_addrs().
static void add_to_objfile_sections (struct bfd * abfd, struct bfd_section * asect, void * objfilep) [static]
Definition at line 222 of file objfiles.c.
References add_to_objfile_sections_full().
Referenced by build_objfile_section_table().
static void add_to_objfile_sections_full (struct bfd * abfd, struct bfd_section * asect, struct objfile * objfile, int force) [static]
Definition at line 201 of file objfiles.c.
References gdb_bfd_section_index(), obj_section::objfile, obj_section::ovly_mapped, objfile::sections, and obj_section::the_bfd_section.
Referenced by add_to_objfile_sections(), and build_objfile_section_table().
struct objfile* allocate_objfile (bfd * abfd, const char * name, int flags) [read]
Definition at line 276 of file objfiles.c.
References build_objfile_section_table(), current_program_space, flags, objfile::flags, gdb_assert, gdb_bfd_ref(), get_objfile_bfd_data(), get_objfile_pspace_data(), objfile::mtime, objfile_pspace_info::new_objfiles_available, objfile::next, objfile::obfd, object_files, OBJF_NOT_FILENAME, objfile::objfile_obstack, objfile::original_name, objfile::per_bfd, objfile::pspace, psymbol_bcache_init(), objfile::psymbol_cache, objfile::sect_index_bss, objfile::sect_index_data, objfile::sect_index_rodata, objfile::sect_index_text, terminate_minimal_symbol_table(), and xzalloc().
Referenced by get_dynamics_objfile(), jit_object_close_impl(), and symbol_file_add_with_addrs().
static int bsearch_cmp (const void * key, const void * elt) [static]
Definition at line 1361 of file objfiles.c.
References obj_section_addr, and obj_section_endaddr.
Referenced by find_pc_section().
void build_objfile_section_table (struct objfile * objfile)
Definition at line 234 of file objfiles.c.
References add_to_objfile_sections(), add_to_objfile_sections_full(), gdb_bfd_count_sections(), objfile::obfd, objfile::objfile_obstack, OBSTACK_CALLOC, objfile::sections, and objfile::sections_end.
Referenced by allocate_objfile(), and reread_symbols().
void default_iterate_over_objfiles_in_search_order (struct gdbarch * gdbarch, iterate_over_objfiles_in_search_order_cb_ftype * cb, void * cb_data, struct objfile * current_objfile)
Definition at line 1481 of file objfiles.c.
References ALL_OBJFILES.
Referenced by gdbarch_alloc().
static void do_free_objfile_cleanup (void * obj) [static]
Definition at line 671 of file objfiles.c.
References free_objfile().
Referenced by make_cleanup_free_objfile().
CORE_ADDR entry_point_address (void)
Definition at line 371 of file objfiles.c.
References _, entry_point_address_query(), and error().
Referenced by call_function_by_hand(), displaced_step_at_entry_point(), gdb_entry_point(), and gdb_loc().
int entry_point_address_query (CORE_ADDR * entry_p)
Definition at line 358 of file objfiles.c.
References symfile_objfile.
Referenced by enable_break(), entry_point_address(), and inside_entry_func().
static int filter_debuginfo_sections (struct obj_section ** map, int map_size) [static]
Definition at line 1200 of file objfiles.c.
References gdb_assert, obj_section_addr, obj_section::objfile, preferred_obj_section(), and objfile::separate_debug_objfile.
Referenced by update_section_map().
static int filter_overlapping_sections (struct obj_section ** map, int map_size) [static]
Definition at line 1242 of file objfiles.c.
References _, complaint(), gdb_assert, get_objfile_arch(), obj_section_addr, obj_section_endaddr, obj_section::objfile, objfile_name(), paddress(), symfile_complaints, and obj_section::the_bfd_section.
Referenced by update_section_map().
struct obj_section* find_pc_section (CORE_ADDR pc) [read]
Definition at line 1376 of file objfiles.c.
References bsearch_cmp(), current_program_space, find_pc_mapped_section(), gdb_assert, get_objfile_pspace_data(), objfile_pspace_info::inhibit_updates, objfile_pspace_info::new_objfiles_available, objfile_pspace_info::num_sections, objfile_pspace_info::section_map_dirty, objfile_pspace_info::sections, sp, and update_section_map().
Referenced by amd64_windows_find_unwind_info(), amd64obsd_sigtramp_p(), arm_find_exidx_entry(), arm_find_mapping_symbol(), arm_skip_stub(), convert_code_addr_to_desc_addr(), enable_break(), find_extant_func_descr(), find_pc_partial_function_gnu_ifunc(), get_pc_function_start(), gnuv3_skip_trampoline(), hppa32_hpux_search_dummy_call_sequence(), hppa64_convert_code_addr_to_fptr(), hppa64_hpux_search_dummy_call_sequence(), hppa_hpux_find_dummy_bpaddr(), hppa_linux_find_global_pointer(), hppabsd_find_global_pointer(), i386obsd_sigtramp_p(), ia64_convert_from_func_ptr_addr(), ia64_find_global_pointer_from_dynamic_section(), lookup_minimal_symbol_by_pc(), lookup_minimal_symbol_by_pc_section(), lookup_solib_trampoline_symbol_by_pc(), mep_gdb_print_insn(), mep_pc_in_vliw_section(), mi_memory_changed(), objfile_relocate1(), pc_in_section(), rs6000_convert_from_func_ptr_addr(), solib_aix_get_toc_value(), svr4_create_solib_event_breakpoints(), tilegx_skip_prologue(), xstormy16_find_jmp_table_entry(), and xstormy16_resolve_jmp_table_entry().
void free_all_objfiles (void)
Definition at line 685 of file objfiles.c.
References ALL_OBJFILES_SAFE, clear_symtab_users(), free_objfile(), gdb_assert, master_so_list(), so_list::next, and so_list::objfile.
Referenced by release_program_space(), and symbol_file_clear().
void free_objfile (struct objfile * objfile)
Definition at line 553 of file objfiles.c.
References breakpoint_free_objfile(), btrace_free_objfile(), clear_current_source_symtab_and_line(), clear_pc_function_cache(), expression_context_block, forget_cached_source_info_for_objfile(), free_objfile_per_bfd_storage(), free_objfile_separate_debug(), gdb_assert, gdb_bfd_unref(), get_current_source_symtab_and_line(), get_objfile_pspace_data(), objfile::global_psymbols, innermost_block, psymbol_allocation_list::list, objfile::obfd, symtab::objfile, objfile::objfile_obstack, objfile::per_bfd, preserve_values(), objfile::pspace, psymbol_bcache_free(), objfile::psymbol_cache, objfile_pspace_info::section_map_dirty, objfile::separate_debug_objfile, objfile::separate_debug_objfile_backlink, objfile::separate_debug_objfile_link, objfile::sf, objfile::static_psymbols, sym_fns::sym_finish, symfile_objfile, symtab_and_line::symtab, unlink_objfile(), and xfree().
Referenced by do_free_objfile_cleanup(), free_all_objfiles(), free_objfile_separate_debug(), jit_unregister_code(), objfile_purge_solibs(), reload_shared_libraries_1(), syms_from_objfile_1(), and update_solib_list().
static void free_objfile_per_bfd_storage (struct objfile_per_bfd_storage * storage) [static]
Definition at line 167 of file objfiles.c.
References bcache_xfree(), objfile_per_bfd_storage::demangled_names_hash, objfile_per_bfd_storage::filename_cache, objfile_per_bfd_storage::macro_cache, and objfile_per_bfd_storage::storage_obstack.
Referenced by free_objfile(), and objfile_bfd_data_free().
void free_objfile_separate_debug (struct objfile * objfile)
Definition at line 524 of file objfiles.c.
References free_objfile(), objfile::separate_debug_objfile, and objfile::separate_debug_objfile_link.
Referenced by free_objfile(), and reread_symbols().
struct gdbarch* get_objfile_arch (struct objfile * objfile) [read]
Definition at line 349 of file objfiles.c.
References objfile_per_bfd_storage::gdbarch, and objfile::per_bfd.
Referenced by add_class_symtab_symbol(), add_minsym(), address_info(), basic_type(), call_target_sbrk(), checkpoint_command(), coff_read_enum_type(), coff_symtab_read(), cp_lookup_symbol_imports_or_template(), create_exception_master_breakpoint(), create_longjmp_master_breakpoint(), create_overlay_event_breakpoint(), create_std_terminate_master_breakpoint(), decode_base_type(), decode_frame_entry_1(), default_read_var_value(), define_symbol(), dump_msymbols(), dump_psymtab(), dump_symtab_1(), dw2_find_pc_sect_symtab(), dwarf2_add_field(), dwarf2_evaluate_loc_desc_full(), dwarf2_find_location_expression(), dwarf2_loc_desc_needs_frame(), dwarf_decode_lines_1(), dwarf_expr_push_dwarf_reg_entry_value(), edit_command(), elf_gnu_ifunc_record_cache(), elf_gnu_ifunc_resolve_by_got(), elf_rel_plt_read(), elf_symtab_read(), end_psymtab(), enter_line_range(), enter_linenos(), filter_overlapping_sections(), finalize_symtab(), find_function_in_inferior(), find_pc_sect_symtab_from_partial(), find_solib_trampoline_target(), finish_block_internal(), get_sal_arch(), get_type_arch(), handle_stap_probe(), ia64_hpux_solib_add_after_attach(), identify_source_line(), info_probes_for_ops(), init_entry_point_info(), insert_exception_resume_from_probe(), internalize_unwinds(), line_info(), list_command(), list_overlays_command(), locexpr_describe_location_1(), locexpr_describe_location_piece(), loclist_describe_location(), lookup_symbol_global(), macho_add_oso_symfile(), maintenance_check_psymtabs(), maintenance_info_psymtabs(), mark_common_block_symbol_computed(), mi_cmd_symbol_list_lines(), minsym_found(), objfile_type(), ocl_enable_break(), parse_partial_symbols(), parse_symbol(), print_msymbol_info(), process_one_symbol(), process_psymtab_comp_unit_reader(), psymtab_to_symtab_1(), py_free_objfile(), python_new_objfile(), read_call_site_scope(), read_dbx_symtab(), read_enum_type(), read_one_struct_field(), read_partial_die(), read_range_type(), read_subrange_type(), read_tag_pointer_type(), read_tag_string_type(), record_minimal_symbol(), save_objfile_types(), scan_xcoff_symtab(), scope_info(), section_is_mapped(), simple_overlay_update_1(), simple_read_overlay_table(), skip_prologue_sal(), som_symtab_read(), spu_catch_start(), stap_can_evaluate_probe_arguments(), stap_gen_info_probes_table_values(), stap_parse_probe_arguments(), tui_set_source_content(), tui_update_source_windows_with_line(), value_allocate_space_in_inferior(), value_fn_field(), and write_exp_msymbol().
static struct objfile_per_bfd_storage* get_objfile_bfd_data (struct objfile * objfile, struct bfd * abfd) [static, read]
Definition at line 131 of file objfiles.c.
References bcache_xmalloc(), objfile_per_bfd_storage::filename_cache, gdb_bfd_requires_relocations(), objfile_per_bfd_storage::gdbarch, gdbarch_from_bfd(), objfile_per_bfd_storage::macro_cache, objfile::objfile_obstack, objfiles_bfd_data, OBSTACK_ZALLOC, and objfile_per_bfd_storage::storage_obstack.
Referenced by allocate_objfile(), and set_objfile_per_bfd().
static struct objfile_pspace_info* get_objfile_pspace_data (struct program_space * pspace) [static, read]
Definition at line 102 of file objfiles.c.
References objfiles_pspace_data, and XZALLOC.
Referenced by allocate_objfile(), find_pc_section(), free_objfile(), inhibit_section_map_updates(), objfile_relocate1(), objfiles_changed(), resume_section_map_updates(), and update_section_map().
int have_full_symbols (void)
Definition at line 1021 of file objfiles.c.
References ALL_OBJFILES, and objfile_has_full_symbols().
Referenced by list_command(), push_expression_name(), set_default_source_symtab_and_line(), sources_info(), symbol_file_add_with_addrs(), symbol_file_clear(), symbol_not_found_error(), and write_var_or_type().
int have_minimal_symbols (void)
Definition at line 1060 of file objfiles.c.
References ALL_OBJFILES, and objfile::minimal_symbol_count.
Referenced by start_command(), and symbol_not_found_error().
int have_partial_symbols (void)
Definition at line 1004 of file objfiles.c.
References ALL_OBJFILES, and objfile_has_partial_symbols().
Referenced by list_command(), push_expression_name(), set_default_source_symtab_and_line(), sources_info(), symbol_file_add_with_addrs(), symbol_file_clear(), symbol_not_found_error(), and write_var_or_type().
void inhibit_section_map_updates (struct program_space * pspace)
Definition at line 1450 of file objfiles.c.
References get_objfile_pspace_data(), and objfile_pspace_info::inhibit_updates.
Referenced by svr4_handle_solib_event().
static int insert_section_p (const struct bfd * abfd, const struct bfd_section * section) [static]
Definition at line 1177 of file objfiles.c.
References overlay_debugging.
Referenced by update_section_map().
struct cleanup* make_cleanup_free_objfile (struct objfile * obj) [read]
Definition at line 677 of file objfiles.c.
References do_free_objfile_cleanup(), and make_cleanup().
Referenced by reread_symbols(), and syms_from_objfile_1().
static void objfile_bfd_data_free (struct bfd * unused, void * d) [static]
Definition at line 180 of file objfiles.c.
References free_objfile_per_bfd_storage().
Referenced by _initialize_objfiles().
int objfile_has_full_symbols (struct objfile * objfile)
Definition at line 979 of file objfiles.c.
References objfile::symtabs.
Referenced by have_full_symbols(), and objfile_has_symbols().
int objfile_has_partial_symbols (struct objfile * objfile)
Definition at line 960 of file objfiles.c.
References objfile::flags, quick_symbol_functions::has_symbols, OBJF_PSYMTABS_READ, sym_fns::qf, objfile::sf, and sym_fns::sym_read_psymbols.
Referenced by coff_symfile_read(), elf_symfile_read(), have_partial_symbols(), objfile_has_symbols(), and read_symbols().
int objfile_has_symbols (struct objfile * objfile)
Definition at line 988 of file objfiles.c.
References objfile_has_full_symbols(), objfile_has_partial_symbols(), and objfile_separate_debug_iterate().
Referenced by info_sharedlibrary_command(), require_partial_symbols(), reread_symbols(), and symbol_file_add_with_addrs().
const char* objfile_name (const struct objfile * objfile)
Definition at line 1499 of file objfiles.c.
References objfile::obfd, and objfile::original_name.
Referenced by address_info(), allocate_psymtab(), allocate_symtab(), auto_load_objfile_script(), build_error_marker_type(), clone_program_space(), coff_symtab_read(), compare_probes(), create_dwo_cu(), create_dwp_v2_section(), dbx_symfile_read(), die_containing_type(), dump_msymbols(), dump_objfile(), dump_psymtab(), dump_subexp_body_standard(), dump_symtab_1(), dw2_expand_symtabs_matching(), dw2_symtab_iter_next(), dwarf2_build_frame_info(), dwarf2_build_psymtabs_hard(), dwarf2_fetch_constant_bytes(), dwarf2_fetch_die_loc_sect_off(), dwarf2_get_dwz_file(), dwarf2_physname(), dwarf2_ranges_read(), dwarf2_read_index(), dwarf2_record_block_ranges(), dwarf_decode_lines_1(), elf_symfile_read(), filter_overlapping_sections(), find_separate_debug_file_by_buildid(), find_separate_debug_file_by_debuglink(), find_separate_debug_file_in_section(), fixup_go_packaging(), follow_die_ref(), follow_die_ref_or_sig(), follow_die_sig(), get_DW_AT_signature_type(), get_signatured_type(), handle_stap_probe(), has_libpthread(), info_probes_for_ops(), install_minimal_symbols(), is_known_support_routine(), load_partial_dies(), locexpr_describe_location_piece(), lookup_die_type(), lookup_dwo_cutu(), lookup_dwo_unit(), lookup_dwp_signatured_type(), macho_check_dsym(), macho_symfile_relocate(), macho_symtab_read(), maintenance_check_symtabs(), maintenance_info_psymtabs(), maintenance_info_symtabs(), maintenance_print_msymbols(), maintenance_print_objfiles(), maintenance_translate_address(), match_main(), objfpy_get_filename(), open_and_init_dwp_file(), parse_probes(), print_objfile_statistics(), print_symbol_bcache_statistics(), process_imported_unit_die(), process_queue(), pspy_get_filename(), read_addr_index_1(), read_call_site_scope(), read_common_block(), read_import_statement(), read_one_sym(), read_partial_die(), read_str_index(), read_subrange_type(), read_typedef(), require_partial_symbols(), reread_symbols(), save_gdb_index_command(), scan_file_globals(), scan_partial_symbols(), separate_debug_file_exists(), solib_aix_get_toc_value(), solib_read_symbols(), som_solib_section_offsets(), source_gdb_script_for_objfile(), sym_info(), symbol_file_clear(), target_info(), target_translate_tls_address(), thread_db_new_objfile(), try_thread_db_load_from_pdir(), try_thread_db_load_from_pdir_1(), type_name_no_tag_or_error(), write_psymtabs_to_index(), and xcoff_initial_scan().
void objfile_purge_solibs (void)
Definition at line 1039 of file objfiles.c.
References ALL_OBJFILES_SAFE, objfile::flags, free_objfile(), OBJF_SHARED, and OBJF_USERLOADED.
Referenced by no_shared_libraries().
void objfile_rebase (struct objfile * objfile, CORE_ADDR slide)
Definition at line 940 of file objfiles.c.
References breakpoint_re_set(), objfile_rebase1(), objfile_separate_debug_iterate(), and objfile::separate_debug_objfile.
Referenced by darwin_solib_create_inferior_hook().
static int objfile_rebase1 (struct objfile * objfile, CORE_ADDR slide) [static]
Definition at line 923 of file objfiles.c.
References objfile::num_sections, objfile_relocate1(), section_offsets::offsets, and SIZEOF_N_SECTION_OFFSETS.
Referenced by objfile_rebase().
void objfile_relocate (struct objfile * objfile, const struct section_offsets * new_offsets)
Definition at line 875 of file objfiles.c.
References addr_info_make_relative(), breakpoint_re_set(), build_section_addr_info_from_objfile(), do_cleanups(), gdb_assert, gdb_bfd_count_sections(), make_cleanup(), objfile::num_sections, objfile::obfd, objfile_relocate1(), objfile_separate_debug_iterate(), relative_addr_info_to_section_offsets(), objfile::separate_debug_objfile, SIZEOF_N_SECTION_OFFSETS, xfree(), and xmalloc().
Referenced by dsbt_relocate_main_executable(), frv_relocate_main_executable(), get_offsets(), solib_aix_solib_create_inferior_hook(), spu_relocate_main_executable(), and svr4_relocate_main_executable().
static int objfile_relocate1 (struct objfile * objfile, const struct section_offsets * new_offsets) [static]
Definition at line 727 of file objfiles.c.
References addrmap_relocate(), ALL_DICT_SYMBOLS, ALL_OBJFILE_MSYMBOLS, ALL_OBJFILE_OSECTIONS, ALL_OBJFILE_SYMTABS, ANOFFSET, BLOCK_DICT, BLOCK_END, symtab::block_line_section, BLOCK_START, BLOCKVECTOR, BLOCKVECTOR_BLOCK, BLOCKVECTOR_MAP, BLOCKVECTOR_NBLOCKS, objfile::ei, entry_info::entry_point, entry_info::entry_point_p, exec_set_section_address(), find_pc_section(), gdb_bfd_section_index(), get_objfile_pspace_data(), symbol::hash_next, linetable::item, LINETABLE, msymbols_sort(), linetable::nitems, objfile::num_sections, objfile::obfd, obj_section_addr, section_offsets::offsets, linetable_entry::pc, symtab::primary, objfile::pspace, objfile::psymtabs_addrmap, sym_fns::qf, quick_symbol_functions::relocate, relocate_one_symbol(), SECT_OFF_TEXT, objfile_pspace_info::section_map_dirty, objfile::section_offsets, objfile::sections, objfile::sf, SIZEOF_N_SECTION_OFFSETS, sym_fns::sym_probe_fns, sym_probe_fns::sym_relocate_probe, SYMBOL_SECTION, SYMBOL_VALUE_ADDRESS, objfile::template_symbols, and obj_section::the_bfd_section.
Referenced by objfile_rebase1(), and objfile_relocate().
struct objfile* objfile_separate_debug_iterate (const struct objfile * parent, const struct objfile * objfile) [read]
Definition at line 390 of file objfiles.c.
References gdb_assert, objfile::separate_debug_objfile, objfile::separate_debug_objfile_backlink, and objfile::separate_debug_objfile_link.
Referenced by lookup_global_symbol_from_objfile(), lookup_minimal_symbol_by_pc_section_1(), lookup_symbol_in_objfile_from_linkage_name(), objfile_has_symbols(), objfile_rebase(), and objfile_relocate().
void objfile_to_front (struct objfile * objfile)
Definition at line 448 of file objfiles.c.
References objfile::next, and object_files.
void objfiles_changed (void)
Definition at line 1441 of file objfiles.c.
References current_program_space, get_objfile_pspace_data(), and objfile_pspace_info::section_map_dirty.
Referenced by reread_symbols().
static void objfiles_pspace_data_cleanup (struct program_space * pspace, void * arg) [static]
Definition at line 86 of file objfiles.c.
References objfiles_pspace_data, objfile_pspace_info::sections, and xfree().
Referenced by _initialize_objfiles().
int pc_in_section (CORE_ADDR pc, char * name)
Definition at line 1423 of file objfiles.c.
References find_pc_section(), and obj_section::the_bfd_section.
Referenced by hppa64_hpux_find_global_pointer(), in_mips_stubs_section(), and in_plt_section().
static struct obj_section* preferred_obj_section (struct obj_section * a, struct obj_section * b) [static, read]
Definition at line 1160 of file objfiles.c.
References gdb_assert, obj_section_addr, obj_section::objfile, objfile::separate_debug_objfile, and objfile::separate_debug_objfile_backlink.
Referenced by filter_debuginfo_sections().
void put_objfile_before (struct objfile * objfile, struct objfile * before_this)
Definition at line 425 of file objfiles.c.
References _, internal_error(), objfile::next, object_files, and unlink_objfile().
Referenced by add_separate_debug_objfile().
static int qsort_cmp (const void * a, const void * b) [static]
Definition at line 1077 of file objfiles.c.
References ALL_OBJFILE_OSECTIONS, ALL_OBJFILES, gdb_assert_not_reached, obj_section_addr, obj_section::objfile, and objfile::separate_debug_objfile.
Referenced by update_section_map().
static void relocate_one_symbol (struct symbol * sym, struct objfile * objfile, struct section_offsets * delta) [static]
Definition at line 705 of file objfiles.c.
References ANOFFSET, fixup_symbol_section(), LOC_LABEL, LOC_STATIC, SYMBOL_CLASS, SYMBOL_SECTION, and SYMBOL_VALUE_ADDRESS.
Referenced by objfile_relocate1().
void resume_section_map_updates (struct program_space * pspace)
Definition at line 1458 of file objfiles.c.
References get_objfile_pspace_data(), and objfile_pspace_info::inhibit_updates.
Referenced by resume_section_map_updates_cleanup().
void resume_section_map_updates_cleanup (void * arg)
Definition at line 1466 of file objfiles.c.
References resume_section_map_updates().
Referenced by svr4_handle_solib_event().
void set_objfile_per_bfd (struct objfile * objfile)
Definition at line 188 of file objfiles.c.
References get_objfile_bfd_data(), objfile::obfd, and objfile::per_bfd.
Referenced by reread_symbols().
void unlink_objfile (struct objfile * objfile)
Definition at line 479 of file objfiles.c.
References _, internal_error(), objfile::next, and object_files.
Referenced by free_objfile(), and put_objfile_before().
static void update_section_map (struct program_space * pspace, struct obj_section *** pmap, int * pmap_size) [static]
Definition at line 1307 of file objfiles.c.
References ALL_OBJFILE_OSECTIONS, ALL_PSPACE_OBJFILES, filter_debuginfo_sections(), filter_overlapping_sections(), gdb_assert, get_objfile_pspace_data(), insert_section_p(), objfile_pspace_info::new_objfiles_available, objfile::obfd, qsort, qsort_cmp(), objfile_pspace_info::section_map_dirty, obj_section::the_bfd_section, xfree(), xmalloc(), and xrealloc().
Referenced by find_pc_section().
Variable Documentation
initialize_file_ftype _initialize_objfiles
Referenced by initialize_all_files().
struct bfd_data* objfiles_bfd_data [static]
Definition at line 120 of file objfiles.c.
Referenced by _initialize_objfiles(), and get_objfile_bfd_data().
struct program_space_data* objfiles_pspace_data [static]
Definition at line 83 of file objfiles.c.
Referenced by _initialize_objfiles(), get_objfile_pspace_data(), and objfiles_pspace_data_cleanup().