GDB (xrefs): /home/stan/gdb/src/gdb/objfiles.h File Reference
/home/stan/gdb/src/gdb/objfiles.h File Reference
#include "gdb_obstack.h"
#include "symfile.h"
#include "progspace.h"
#include "registry.h"
#include "gdb_bfd.h"
Classes
struct entry_info
struct obj_section
struct objstats
struct objfile_per_bfd_storage
struct objfile
Defines
#define obj_section_offset(s) (((s)->objfile->section_offsets)->offsets[gdb_bfd_section_index ((s)->objfile->obfd, (s)->the_bfd_section)])
#define obj_section_addr(s)
#define obj_section_endaddr(s)
#define OBJSTAT(objfile, expr) (objfile -> stats.expr)
#define OBJSTATS struct objstats stats
#define MINIMAL_SYMBOL_HASH_SIZE 2039
#define OBJF_REORDERED (1 << 0) /* Functions are reordered */
#define OBJF_SHARED (1 << 1) /* From a shared library */
#define OBJF_READNOW (1 << 2) /* Immediate full read */
#define OBJF_USERLOADED (1 << 3) /* User loaded */
#define OBJF_PSYMTABS_READ (1 << 4)
#define OBJF_MAINLINE (1 << 5)
#define OBJF_NOT_FILENAME (1 << 6)
#define ALL_PSPACE_OBJFILES(ss, obj) for ((obj) = ss->objfiles; (obj) != NULL; (obj) = (obj)->next)
#define ALL_PSPACE_OBJFILES_SAFE(ss, obj, nxt)
#define ALL_OBJFILES(obj)
#define ALL_OBJFILES_SAFE(obj, nxt)
#define ALL_OBJFILE_SYMTABS(objfile, s) for ((s) = (objfile) -> symtabs; (s) != NULL; (s) = (s) -> next)
#define ALL_OBJFILE_PRIMARY_SYMTABS(objfile, s)
#define ALL_OBJFILE_MSYMBOLS(objfile, m) for ((m) = (objfile) -> msymbols; SYMBOL_LINKAGE_NAME(m) != NULL; (m)++)
#define ALL_SYMTABS(objfile, s)
#define ALL_PSPACE_SYMTABS(ss, objfile, s)
#define ALL_PRIMARY_SYMTABS(objfile, s)
#define ALL_PSPACE_PRIMARY_SYMTABS(pspace, objfile, s)
#define ALL_MSYMBOLS(objfile, m)
#define ALL_OBJFILE_OSECTIONS(objfile, osect)
#define ALL_OBJSECTIONS(objfile, osect)
#define SECT_OFF_DATA(objfile)
#define SECT_OFF_RODATA(objfile)
#define SECT_OFF_TEXT(objfile)
#define SECT_OFF_BSS(objfile) (objfile)->sect_index_bss
#define MULTI_OBJFILE_P() (object_files && object_files->next)
Functions
void print_objfile_statistics (void)
void print_symbol_bcache_statistics (void)
struct objfile * allocate_objfile (bfd *, const char *name, int)
struct gdbarch * get_objfile_arch (struct objfile *)
int entry_point_address_query (CORE_ADDR *entry_p)
CORE_ADDR entry_point_address (void)
void build_objfile_section_table (struct objfile *)
void terminate_minimal_symbol_table (struct objfile *objfile)
struct objfile * objfile_separate_debug_iterate (const struct objfile *, const struct objfile *)
void put_objfile_before (struct objfile *, struct objfile *)
void objfile_to_front (struct objfile *)
void add_separate_debug_objfile (struct objfile *, struct objfile *)
void unlink_objfile (struct objfile *)
void free_objfile (struct objfile *)
void free_objfile_separate_debug (struct objfile *)
struct cleanup * make_cleanup_free_objfile (struct objfile *)
void free_all_objfiles (void)
void objfile_relocate (struct objfile *, const struct section_offsets *)
void objfile_rebase (struct objfile *, CORE_ADDR)
int objfile_has_partial_symbols (struct objfile *objfile)
int objfile_has_full_symbols (struct objfile *objfile)
int objfile_has_symbols (struct objfile *objfile)
int have_partial_symbols (void)
int have_full_symbols (void)
void objfile_set_sym_fns (struct objfile *objfile, const struct sym_fns *sf)
void objfiles_changed (void)
void objfile_purge_solibs (void)
int have_minimal_symbols (void)
struct obj_section * find_pc_section (CORE_ADDR pc)
int pc_in_section (CORE_ADDR, char *)
static int in_plt_section (CORE_ADDR pc)
DECLARE_REGISTRY (objfile)
void inhibit_section_map_updates (struct program_space *pspace)
void resume_section_map_updates (struct program_space *pspace)
void resume_section_map_updates_cleanup (void *arg)
void default_iterate_over_objfiles_in_search_order (struct gdbarch *gdbarch, iterate_over_objfiles_in_search_order_cb_ftype *cb, void *cb_data, struct objfile *current_objfile)
void set_objfile_per_bfd (struct objfile *obj)
const char * objfile_name (const struct objfile *objfile)
Define Documentation
#define ALL_MSYMBOLS (objfile, m)
Value:
ALL_OBJFILES (objfile)   \
    ALL_OBJFILE_MSYMBOLS (objfile, m)
Definition at line 605 of file objfiles.h.
Referenced by ada_lookup_simple_minsym(), classes_info(), find_solib_trampoline_target(), hppa_hpux_skip_trampoline_code(), hppa_lookup_stub_minimal_symbol(), search_symbols(), selectors_info(), and VEC().
#define ALL_OBJFILE_MSYMBOLS (objfile, m) for ((m) = (objfile) -> msymbols; SYMBOL_LINKAGE_NAME(m) != NULL; (m)++)
Definition at line 576 of file objfiles.h.
Referenced by coff_symfile_read(), dump_msymbols(), find_methods(), hppa64_hpux_search_dummy_call_sequence(), hppa_hpux_find_dummy_bpaddr(), objfile_relocate1(), and scan_file_globals().
#define ALL_OBJFILE_OSECTIONS (objfile, osect)
Value:
for (osect = objfile->sections; osect < objfile->sections_end; osect++) \
    if (osect->the_bfd_section == NULL)                                 \
      {                                                                 \
        /* Nothing.  */                                                 \
      }                                                                 \
    else
Definition at line 609 of file objfiles.h.
Referenced by arm_obj_section_from_vma(), data_obj_section_from_objfile(), dsbt_relocate_main_executable(), find_extant_func_descr(), fixup_section(), frv_relocate_main_executable(), hppa64_convert_code_addr_to_fptr(), hppa_linux_find_global_pointer(), hppabsd_find_global_pointer(), ia64_find_global_pointer_from_dynamic_section(), macho_symfile_offsets(), maintenance_info_sections(), objfile_relocate1(), qsort_cmp(), som_solib_section_offsets(), som_symtab_read(), spu_get_overlay_table(), spu_overlay_new_objfile(), update_section_map(), and xstormy16_find_jmp_table_entry().
#define ALL_OBJFILE_PRIMARY_SYMTABS (objfile, s)
Value:
ALL_OBJFILE_SYMTABS ((objfile), (s)) \
    if ((s)->primary)
Definition at line 570 of file objfiles.h.
Referenced by basic_lookup_transparent_type(), iterate_over_all_matching_symtabs(), lookup_global_symbol_from_objfile(), and lookup_symbol_aux_objfile().
#define ALL_OBJFILE_SYMTABS (objfile, s) for ((s) = (objfile) -> symtabs; (s) != NULL; (s) = (s) -> next)
Definition at line 565 of file objfiles.h.
Referenced by coff_symtab_read(), end_symtab_from_static_block(), find_pc_sect_line(), forget_cached_source_info_for_objfile(), maintenance_check_symtabs(), maintenance_info_symtabs(), objfile_relocate1(), and print_objfile_statistics().
#define ALL_OBJFILES (obj)
Value:
for ((obj) = current_program_space->objfiles; \
       (obj) != NULL;                               \
       (obj) = (obj)->next)
Definition at line 553 of file objfiles.h.
Referenced by add_nonlocal_symbols(), append_ocl_sos(), basic_lookup_transparent_type(), captured_main(), create_exception_master_breakpoint(), create_longjmp_master_breakpoint(), create_overlay_event_breakpoint(), create_std_terminate_master_breakpoint(), default_iterate_over_objfiles_in_search_order(), dwarf2_frame_find_fde(), expand_partial_symbol_names(), find_line_symtab(), find_methods(), find_pc_partial_function_gnu_ifunc(), find_pc_sect_symtab(), find_pc_sect_symtab_via_partial(), find_probe_by_pc(), find_unwind_entry(), has_libpthread(), have_full_symbols(), have_minimal_symbols(), have_partial_symbols(), hppa_hpux_find_import_stub_for_addr(), iterate_over_all_matching_symtabs(), iterate_over_symtabs(), jit_find_objf_with_entry_addr(), lookup_minimal_symbol_and_objfile(), lookup_static_symbol_aux(), lookup_symbol_aux_symtabs(), maintenance_info_sections(), make_symbol_overload_list_qualified(), map_partial_symbol_filenames(), matching_obj_sections(), ppc_linux_spe_context_inferior_created(), qsort_cmp(), save_gdb_index_command(), search_minsyms_for_name(), search_symbols(), select_source_symtab(), solib_read_symbols(), som_solib_desire_dynamic_linker_symbols(), spu_objfile_from_frame(), try_thread_db_load_from_pdir(), and windows_iterate_over_objfiles_in_search_order().
#define ALL_OBJFILES_SAFE (obj, nxt)
Value:
for ((obj) = current_program_space->objfiles;   \
       (obj) != NULL? ((nxt)=(obj)->next,1) :0; \
       (obj) = (nxt))
Definition at line 558 of file objfiles.h.
Referenced by free_all_objfiles(), jit_inferior_exit_hook(), and objfile_purge_solibs().
#define ALL_OBJSECTIONS (objfile, osect)
Value:
for ((objfile) = current_program_space->objfiles,                       \
         (objfile) != NULL ? ((osect) = (objfile)->sections_end) : 0;   \
       (objfile) != NULL                                                \
         && (osect) == (objfile)->sections_end;                         \
       ((osect) == (objfile)->sections_end                              \
        ? ((objfile) = (objfile)->next,                                 \
           (objfile) != NULL ? (osect) = (objfile)->sections_end : 0)   \
        : 0))                                                           \
    ALL_OBJFILE_OSECTIONS (objfile, osect)
Definition at line 642 of file objfiles.h.
Referenced by find_pc_mapped_section(), find_pc_overlay(), gcore_create_callback(), list_overlays_command(), maintenance_translate_address(), map_overlay_command(), objfile_find_memory_regions(), overlay_invalidate_all(), simple_overlay_update(), spu_overlay_update(), sym_info(), and unmap_overlay_command().
#define ALL_PRIMARY_SYMTABS (objfile, s)
Value:
ALL_OBJFILES (objfile)          \
    ALL_OBJFILE_PRIMARY_SYMTABS (objfile, s)
Definition at line 594 of file objfiles.h.
Referenced by find_pc_sect_symtab(), make_symbol_overload_list_qualified(), and search_symbols().
#define ALL_PSPACE_OBJFILES (ss, obj) for ((obj) = ss->objfiles; (obj) != NULL; (obj) = (obj)->next)
Definition at line 545 of file objfiles.h.
Referenced by elf_gnu_ifunc_resolve_by_cache(), elf_gnu_ifunc_resolve_by_got(), forget_cached_source_info(), maintenance_check_symtabs(), maintenance_expand_symtabs(), maintenance_info_psymtabs(), maintenance_info_symtabs(), maintenance_print_msymbols(), maintenance_print_objfiles(), parse_probes(), print_objfile_statistics(), print_symbol_bcache_statistics(), set_debug_symfile(), and update_section_map().
#define ALL_PSPACE_OBJFILES_SAFE (ss, obj, nxt)
Value:
for ((obj) = ss->objfiles;                      \
       (obj) != NULL? ((nxt)=(obj)->next,1) :0; \
       (obj) = (nxt))
Definition at line 548 of file objfiles.h.
#define ALL_PSPACE_PRIMARY_SYMTABS (pspace, objfile, s)
Value:
ALL_PSPACE_OBJFILES (ss, objfile)                       \
    ALL_OBJFILE_PRIMARY_SYMTABS (objfile, s)
Definition at line 598 of file objfiles.h.
#define ALL_PSPACE_SYMTABS (ss, objfile, s)
Value:
ALL_PSPACE_OBJFILES (ss, objfile)                       \
    ALL_OBJFILE_SYMTABS (objfile, s)
Definition at line 586 of file objfiles.h.
#define ALL_SYMTABS (objfile, s)
Value:
ALL_OBJFILES (objfile)   \
    ALL_OBJFILE_SYMTABS (objfile, s)
Definition at line 582 of file objfiles.h.
Referenced by count_symtabs_and_blocks(), find_line_symtab(), gdb_listfiles(), lookup_objfile_from_block(), maintenance_print_symbols(), mi_cmd_file_list_exec_source_files(), sources_info(), and VEC().
#define MINIMAL_SYMBOL_HASH_SIZE 2039
Definition at line 162 of file objfiles.h.
Referenced by add_minsym_to_demangled_hash_table(), add_minsym_to_hash_table(), build_minimal_symbol_hash_tables(), iterate_over_minimal_symbols(), lookup_minimal_symbol_and_objfile(), lookup_minimal_symbol_by_pc_name(), lookup_minimal_symbol_internal(), lookup_minimal_symbol_solib_trampoline(), and lookup_minimal_symbol_text().
#define MULTI_OBJFILE_P () (object_files && object_files->next)
Definition at line 678 of file objfiles.h.
Referenced by maintenance_translate_address(), and sym_info().
#define obj_section_addr (s)
Value:
(bfd_get_section_vma ((s)->objfile->obfd, s->the_bfd_section)           \
   + obj_section_offset (s))
Definition at line 130 of file objfiles.h.
Referenced by arm_find_exidx_entry(), arm_find_mapping_symbol(), bsearch_cmp(), dsbt_relocate_main_executable(), filter_debuginfo_sections(), filter_overlapping_sections(), find_extant_func_descr(), fixup_section(), frv_relocate_main_executable(), gcore_create_callback(), hppa64_convert_code_addr_to_fptr(), hppa_hpux_find_dummy_bpaddr(), hppa_linux_find_global_pointer(), hppabsd_find_global_pointer(), ia64_find_global_pointer_from_dynamic_section(), objfile_find_memory_regions(), objfile_relocate1(), pc_in_mapped_range(), preferred_obj_section(), print_objfile_section_info(), qsort_cmp(), sections_overlap(), solib_aix_get_toc_value(), som_symtab_read(), spu_gdbarch_id(), spu_objfile_from_frame(), spu_overlay_update_osect(), sym_info(), and xstormy16_find_jmp_table_entry().
#define obj_section_endaddr (s)
Value:
(bfd_get_section_vma ((s)->objfile->obfd, s->the_bfd_section)           \
   + bfd_get_section_size ((s)->the_bfd_section)                        \
   + obj_section_offset (s))
Definition at line 136 of file objfiles.h.
Referenced by bsearch_cmp(), filter_overlapping_sections(), find_extant_func_descr(), find_pc_partial_function_gnu_ifunc(), fixup_section(), gcore_create_callback(), hppa64_convert_code_addr_to_fptr(), hppa_linux_find_global_pointer(), hppabsd_find_global_pointer(), ia64_find_global_pointer_from_dynamic_section(), pc_in_mapped_range(), print_objfile_section_info(), sections_overlap(), som_symtab_read(), sym_info(), tilegx_skip_prologue(), and xstormy16_find_jmp_table_entry().
#define obj_section_offset (s) (((s)->objfile->section_offsets)->offsets[gdb_bfd_section_index ((s)->objfile->obfd, (s)->the_bfd_section)])
Definition at line 126 of file objfiles.h.
Referenced by arm_exidx_new_objfile(), macho_symfile_offsets(), and pc_in_unmapped_range().
#define OBJF_MAINLINE (1 << 5)
Definition at line 430 of file objfiles.h.
Referenced by symbol_file_add_with_addrs(), and thread_db_new_objfile().
#define OBJF_NOT_FILENAME (1 << 6)
Definition at line 435 of file objfiles.h.
Referenced by allocate_objfile(), get_dynamics_objfile(), jit_bfd_try_read_symtab(), jit_object_close_impl(), and load_auto_scripts_for_objfile().
#define OBJF_PSYMTABS_READ (1 << 4)
Definition at line 425 of file objfiles.h.
Referenced by objfile_has_partial_symbols(), require_partial_symbols(), and reread_symbols().
#define OBJF_READNOW (1 << 2) /* Immediate full read */
Definition at line 411 of file objfiles.h.
Referenced by add_symbol_file_command(), dwarf2_initialize_objfile(), macho_add_oso_symfile(), symbol_file_add_separate(), symbol_file_add_with_addrs(), and symbol_file_command().
#define OBJF_REORDERED (1 << 0) /* Functions are reordered */
Definition at line 397 of file objfiles.h.
Referenced by coff_symfile_init(), elf_symfile_init(), end_symtab_from_static_block(), end_symtab_get_static_block(), find_pc_sect_psymtab_closer(), find_pc_sect_symtab(), macho_add_oso_symfile(), macho_symfile_init(), parse_partial_symbols(), som_symfile_init(), symbol_file_add_separate(), and xcoff_symfile_init().
#define OBJF_SHARED (1 << 1) /* From a shared library */
Definition at line 407 of file objfiles.h.
Referenced by dll_symbol_command(), get_dynamics_objfile(), jit_bfd_try_read_symtab(), macho_add_oso_symfile(), objfile_purge_solibs(), solib_read_symbols(), symbol_file_add_from_memory(), symbol_file_add_separate(), and target_translate_tls_address().
#define OBJF_USERLOADED (1 << 3) /* User loaded */
Definition at line 420 of file objfiles.h.
Referenced by add_symbol_file_command(), dll_symbol_command(), macho_add_oso_symfile(), objfile_purge_solibs(), reload_shared_libraries_1(), symbol_file_add_separate(), symbol_file_command(), and update_solib_list().
#define OBJSTAT (objfile, expr) (objfile -> stats.expr)
Definition at line 156 of file objfiles.h.
Referenced by alloc_type(), append_psymbol_to_list(), coffstab_build_psymtabs(), dbx_next_symbol_text(), dbx_symfile_init(), elfstab_build_psymtabs(), new_symbol_full(), prim_record_minimal_symbol_full(), print_objfile_statistics(), read_dbx_symtab(), read_ofile_symtab(), and stabsect_build_psymtabs().
#define OBJSTATS struct objstats stats
Definition at line 157 of file objfiles.h.
#define SECT_OFF_BSS (objfile) (objfile)->sect_index_bss
Definition at line 674 of file objfiles.h.
Referenced by elf_symtab_read(), get_offsets(), parse_partial_symbols(), parse_symbol(), prim_record_minimal_symbol(), process_one_symbol(), read_alphacoff_dynamic_symtab(), read_dbx_dynamic_symtab(), read_dbx_symtab(), record_minimal_symbol(), and som_solib_section_offsets().
#define SECT_OFF_DATA (objfile)
Value:
((objfile->sect_index_data == -1) \
      ? (internal_error (__FILE__, __LINE__, \
                         _("sect_index_data not initialized")), -1)     \
      : objfile->sect_index_data)
Definition at line 653 of file objfiles.h.
Referenced by elf_symtab_read(), find_targ_sec(), get_offsets(), handle_stap_probe(), parse_partial_symbols(), parse_symbol(), prim_record_minimal_symbol(), process_one_symbol(), read_alphacoff_dynamic_symtab(), read_dbx_dynamic_symtab(), read_dbx_symtab(), record_minimal_symbol(), scan_xcoff_symtab(), and som_solib_section_offsets().
#define SECT_OFF_RODATA (objfile)
Value:
((objfile->sect_index_rodata == -1) \
      ? (internal_error (__FILE__, __LINE__, \
                         _("sect_index_rodata not initialized")), -1)   \
      : objfile->sect_index_rodata)
Definition at line 659 of file objfiles.h.
Referenced by elf_symtab_read(), process_one_symbol(), and read_dbx_symtab().
#define SECT_OFF_TEXT (objfile)
Value:
((objfile->sect_index_text == -1) \
      ? (internal_error (__FILE__, __LINE__, \
                         _("sect_index_text not initialized")), -1)     \
      : objfile->sect_index_text)
Definition at line 665 of file objfiles.h.
Referenced by add_address_entry(), add_partial_subprogram(), add_partial_symbol(), amd64_windows_find_unwind_info(), coff_end_symtab(), coff_symtab_read(), create_addrmap_from_index(), cs_to_section(), dwarf2_frame_find_fde(), dwarf2_per_cu_text_offset(), dwarf2_ranges_read(), dwarf_decode_lines_1(), elf_symfile_relocate_probe(), enable_break(), enter_line_range(), enter_linenos(), execute_cfa_program(), find_targ_sec(), get_offsets(), handle_stap_probe(), hppabsd_find_global_pointer(), new_symbol_full(), objfile_relocate1(), parse_partial_symbols(), parse_symbol(), prim_record_minimal_symbol(), process_coff_symbol(), process_full_comp_unit(), process_full_type_unit(), process_one_symbol(), process_psymtab_comp_unit_reader(), psymtab_to_symtab_1(), read_alphacoff_dynamic_symtab(), read_call_site_scope(), read_dbx_dynamic_symtab(), read_dbx_symtab(), read_file_scope(), read_func_scope(), read_lexical_block_scope(), read_ofile_symtab(), read_pe_exported_syms(), read_unwind_info(), read_xcoff_symtab(), record_minimal_symbol(), relocate_psymtabs(), scan_xcoff_symtab(), som_solib_section_offsets(), and xcoff_secnum_to_sections().
Function Documentation
void add_separate_debug_objfile (struct objfile * , struct objfile *)
Definition at line 500 of file objfiles.c.
References gdb_assert, put_objfile_before(), objfile::separate_debug_objfile, objfile::separate_debug_objfile_backlink, and objfile::separate_debug_objfile_link.
Referenced by symbol_file_add_with_addrs().
struct objfile* allocate_objfile (bfd * , const char * name, int) [read]
Definition at line 276 of file objfiles.c.
References build_objfile_section_table(), current_program_space, flags, objfile::flags, gdb_assert, gdb_bfd_ref(), get_objfile_bfd_data(), get_objfile_pspace_data(), objfile::mtime, objfile_pspace_info::new_objfiles_available, objfile::next, objfile::obfd, object_files, OBJF_NOT_FILENAME, objfile::objfile_obstack, objfile::original_name, objfile::per_bfd, objfile::pspace, psymbol_bcache_init(), objfile::psymbol_cache, objfile::sect_index_bss, objfile::sect_index_data, objfile::sect_index_rodata, objfile::sect_index_text, terminate_minimal_symbol_table(), and xzalloc().
Referenced by get_dynamics_objfile(), jit_object_close_impl(), and symbol_file_add_with_addrs().
void build_objfile_section_table (struct objfile *)
Definition at line 234 of file objfiles.c.
References add_to_objfile_sections(), add_to_objfile_sections_full(), gdb_bfd_count_sections(), objfile::obfd, objfile::objfile_obstack, OBSTACK_CALLOC, objfile::sections, and objfile::sections_end.
Referenced by allocate_objfile(), and reread_symbols().
DECLARE_REGISTRY (objfile)
void default_iterate_over_objfiles_in_search_order (struct gdbarch * gdbarch, iterate_over_objfiles_in_search_order_cb_ftype * cb, void * cb_data, struct objfile * current_objfile)
Definition at line 1481 of file objfiles.c.
References ALL_OBJFILES.
Referenced by gdbarch_alloc().
CORE_ADDR entry_point_address (void)
Definition at line 371 of file objfiles.c.
References _, entry_point_address_query(), and error().
Referenced by call_function_by_hand(), displaced_step_at_entry_point(), gdb_entry_point(), and gdb_loc().
int entry_point_address_query (CORE_ADDR * entry_p)
Definition at line 358 of file objfiles.c.
References symfile_objfile.
Referenced by enable_break(), entry_point_address(), and inside_entry_func().
struct obj_section* find_pc_section (CORE_ADDR pc) [read]
Definition at line 1376 of file objfiles.c.
References bsearch_cmp(), current_program_space, find_pc_mapped_section(), gdb_assert, get_objfile_pspace_data(), objfile_pspace_info::inhibit_updates, objfile_pspace_info::new_objfiles_available, objfile_pspace_info::num_sections, objfile_pspace_info::section_map_dirty, objfile_pspace_info::sections, sp, and update_section_map().
Referenced by amd64_windows_find_unwind_info(), amd64obsd_sigtramp_p(), arm_find_exidx_entry(), arm_find_mapping_symbol(), arm_skip_stub(), convert_code_addr_to_desc_addr(), enable_break(), find_extant_func_descr(), find_pc_partial_function_gnu_ifunc(), get_pc_function_start(), gnuv3_skip_trampoline(), hppa32_hpux_search_dummy_call_sequence(), hppa64_convert_code_addr_to_fptr(), hppa64_hpux_search_dummy_call_sequence(), hppa_hpux_find_dummy_bpaddr(), hppa_linux_find_global_pointer(), hppabsd_find_global_pointer(), i386obsd_sigtramp_p(), ia64_convert_from_func_ptr_addr(), ia64_find_global_pointer_from_dynamic_section(), lookup_minimal_symbol_by_pc(), lookup_minimal_symbol_by_pc_section(), lookup_solib_trampoline_symbol_by_pc(), mep_gdb_print_insn(), mep_pc_in_vliw_section(), mi_memory_changed(), objfile_relocate1(), pc_in_section(), rs6000_convert_from_func_ptr_addr(), solib_aix_get_toc_value(), svr4_create_solib_event_breakpoints(), tilegx_skip_prologue(), xstormy16_find_jmp_table_entry(), and xstormy16_resolve_jmp_table_entry().
void free_all_objfiles (void)
Definition at line 685 of file objfiles.c.
References ALL_OBJFILES_SAFE, clear_symtab_users(), free_objfile(), gdb_assert, master_so_list(), so_list::next, and so_list::objfile.
Referenced by release_program_space(), and symbol_file_clear().
void free_objfile (struct objfile *)
Definition at line 553 of file objfiles.c.
References breakpoint_free_objfile(), btrace_free_objfile(), clear_current_source_symtab_and_line(), clear_pc_function_cache(), expression_context_block, forget_cached_source_info_for_objfile(), free_objfile_per_bfd_storage(), free_objfile_separate_debug(), gdb_assert, gdb_bfd_unref(), get_current_source_symtab_and_line(), get_objfile_pspace_data(), objfile::global_psymbols, innermost_block, psymbol_allocation_list::list, objfile::obfd, symtab::objfile, objfile::objfile_obstack, objfile::per_bfd, preserve_values(), objfile::pspace, psymbol_bcache_free(), objfile::psymbol_cache, objfile_pspace_info::section_map_dirty, objfile::separate_debug_objfile, objfile::separate_debug_objfile_backlink, objfile::separate_debug_objfile_link, objfile::sf, objfile::static_psymbols, sym_fns::sym_finish, symfile_objfile, symtab_and_line::symtab, unlink_objfile(), and xfree().
Referenced by do_free_objfile_cleanup(), free_all_objfiles(), free_objfile_separate_debug(), jit_unregister_code(), objfile_purge_solibs(), reload_shared_libraries_1(), syms_from_objfile_1(), and update_solib_list().
void free_objfile_separate_debug (struct objfile *)
Definition at line 524 of file objfiles.c.
References free_objfile(), objfile::separate_debug_objfile, and objfile::separate_debug_objfile_link.
Referenced by free_objfile(), and reread_symbols().
struct gdbarch* get_objfile_arch (struct objfile *) [read]
Definition at line 349 of file objfiles.c.
References objfile_per_bfd_storage::gdbarch, and objfile::per_bfd.
Referenced by add_class_symtab_symbol(), add_minsym(), address_info(), basic_type(), call_target_sbrk(), checkpoint_command(), coff_read_enum_type(), coff_symtab_read(), cp_lookup_symbol_imports_or_template(), create_exception_master_breakpoint(), create_longjmp_master_breakpoint(), create_overlay_event_breakpoint(), create_std_terminate_master_breakpoint(), decode_base_type(), decode_frame_entry_1(), default_read_var_value(), define_symbol(), dump_msymbols(), dump_psymtab(), dump_symtab_1(), dw2_find_pc_sect_symtab(), dwarf2_add_field(), dwarf2_evaluate_loc_desc_full(), dwarf2_find_location_expression(), dwarf2_loc_desc_needs_frame(), dwarf_decode_lines_1(), dwarf_expr_push_dwarf_reg_entry_value(), edit_command(), elf_gnu_ifunc_record_cache(), elf_gnu_ifunc_resolve_by_got(), elf_rel_plt_read(), elf_symtab_read(), end_psymtab(), enter_line_range(), enter_linenos(), filter_overlapping_sections(), finalize_symtab(), find_function_in_inferior(), find_pc_sect_symtab_from_partial(), find_solib_trampoline_target(), finish_block_internal(), get_sal_arch(), get_type_arch(), handle_stap_probe(), ia64_hpux_solib_add_after_attach(), identify_source_line(), info_probes_for_ops(), init_entry_point_info(), insert_exception_resume_from_probe(), internalize_unwinds(), line_info(), list_command(), list_overlays_command(), locexpr_describe_location_1(), locexpr_describe_location_piece(), loclist_describe_location(), lookup_symbol_global(), macho_add_oso_symfile(), maintenance_check_psymtabs(), maintenance_info_psymtabs(), mark_common_block_symbol_computed(), mi_cmd_symbol_list_lines(), minsym_found(), objfile_type(), ocl_enable_break(), parse_partial_symbols(), parse_symbol(), print_msymbol_info(), process_one_symbol(), process_psymtab_comp_unit_reader(), psymtab_to_symtab_1(), py_free_objfile(), python_new_objfile(), read_call_site_scope(), read_dbx_symtab(), read_enum_type(), read_one_struct_field(), read_partial_die(), read_range_type(), read_subrange_type(), read_tag_pointer_type(), read_tag_string_type(), record_minimal_symbol(), save_objfile_types(), scan_xcoff_symtab(), scope_info(), section_is_mapped(), simple_overlay_update_1(), simple_read_overlay_table(), skip_prologue_sal(), som_symtab_read(), spu_catch_start(), stap_can_evaluate_probe_arguments(), stap_gen_info_probes_table_values(), stap_parse_probe_arguments(), tui_set_source_content(), tui_update_source_windows_with_line(), value_allocate_space_in_inferior(), value_fn_field(), and write_exp_msymbol().
int have_full_symbols (void)
Definition at line 1021 of file objfiles.c.
References ALL_OBJFILES, and objfile_has_full_symbols().
Referenced by list_command(), push_expression_name(), set_default_source_symtab_and_line(), sources_info(), symbol_file_add_with_addrs(), symbol_file_clear(), symbol_not_found_error(), and write_var_or_type().
int have_minimal_symbols (void)
Definition at line 1060 of file objfiles.c.
References ALL_OBJFILES, and objfile::minimal_symbol_count.
Referenced by start_command(), and symbol_not_found_error().
int have_partial_symbols (void)
Definition at line 1004 of file objfiles.c.
References ALL_OBJFILES, and objfile_has_partial_symbols().
Referenced by list_command(), push_expression_name(), set_default_source_symtab_and_line(), sources_info(), symbol_file_add_with_addrs(), symbol_file_clear(), symbol_not_found_error(), and write_var_or_type().
static int in_plt_section (CORE_ADDR pc) [inline, static]
Definition at line 508 of file objfiles.h.
References pc_in_section().
Referenced by aarch64_stub_unwind_sniffer(), arm_stub_unwind_sniffer(), arm_symbian_skip_trampoline_code(), dsbt_in_dynsym_resolve_code(), frv_in_dynsym_resolve_code(), hppa_in_solib_call_trampoline(), hppa_linux_find_global_pointer(), hppa_skip_trampoline_code(), hppabsd_find_global_pointer(), mips_stub_frame_sniffer(), nios2_stub_frame_sniffer(), nto_in_dynsym_resolve_code(), s390_stub_frame_sniffer(), sh_stub_unwind_sniffer(), solib_target_in_dynsym_resolve_code(), sparc_analyze_prologue(), svr4_in_dynsym_resolve_code(), and tic6x_stub_unwind_sniffer().
void inhibit_section_map_updates (struct program_space * pspace)
Definition at line 1450 of file objfiles.c.
References get_objfile_pspace_data(), and objfile_pspace_info::inhibit_updates.
Referenced by svr4_handle_solib_event().
struct cleanup* make_cleanup_free_objfile (struct objfile *) [read]
Definition at line 677 of file objfiles.c.
References do_free_objfile_cleanup(), and make_cleanup().
Referenced by reread_symbols(), and syms_from_objfile_1().
int objfile_has_full_symbols (struct objfile * objfile)
Definition at line 979 of file objfiles.c.
References objfile::symtabs.
Referenced by have_full_symbols(), and objfile_has_symbols().
int objfile_has_partial_symbols (struct objfile * objfile)
Definition at line 960 of file objfiles.c.
References objfile::flags, quick_symbol_functions::has_symbols, OBJF_PSYMTABS_READ, sym_fns::qf, objfile::sf, and sym_fns::sym_read_psymbols.
Referenced by coff_symfile_read(), elf_symfile_read(), have_partial_symbols(), objfile_has_symbols(), and read_symbols().
int objfile_has_symbols (struct objfile * objfile)
Definition at line 988 of file objfiles.c.
References objfile_has_full_symbols(), objfile_has_partial_symbols(), and objfile_separate_debug_iterate().
Referenced by info_sharedlibrary_command(), require_partial_symbols(), reread_symbols(), and symbol_file_add_with_addrs().
const char* objfile_name (const struct objfile * objfile)
Definition at line 1499 of file objfiles.c.
References objfile::obfd, and objfile::original_name.
Referenced by address_info(), allocate_psymtab(), allocate_symtab(), auto_load_objfile_script(), build_error_marker_type(), clone_program_space(), coff_symtab_read(), compare_probes(), create_dwo_cu(), create_dwp_v2_section(), dbx_symfile_read(), die_containing_type(), dump_msymbols(), dump_objfile(), dump_psymtab(), dump_subexp_body_standard(), dump_symtab_1(), dw2_expand_symtabs_matching(), dw2_symtab_iter_next(), dwarf2_build_frame_info(), dwarf2_build_psymtabs_hard(), dwarf2_fetch_constant_bytes(), dwarf2_fetch_die_loc_sect_off(), dwarf2_get_dwz_file(), dwarf2_physname(), dwarf2_ranges_read(), dwarf2_read_index(), dwarf2_record_block_ranges(), dwarf_decode_lines_1(), elf_symfile_read(), filter_overlapping_sections(), find_separate_debug_file_by_buildid(), find_separate_debug_file_by_debuglink(), find_separate_debug_file_in_section(), fixup_go_packaging(), follow_die_ref(), follow_die_ref_or_sig(), follow_die_sig(), get_DW_AT_signature_type(), get_signatured_type(), handle_stap_probe(), has_libpthread(), info_probes_for_ops(), install_minimal_symbols(), is_known_support_routine(), load_partial_dies(), locexpr_describe_location_piece(), lookup_die_type(), lookup_dwo_cutu(), lookup_dwo_unit(), lookup_dwp_signatured_type(), macho_check_dsym(), macho_symfile_relocate(), macho_symtab_read(), maintenance_check_symtabs(), maintenance_info_psymtabs(), maintenance_info_symtabs(), maintenance_print_msymbols(), maintenance_print_objfiles(), maintenance_translate_address(), match_main(), objfpy_get_filename(), open_and_init_dwp_file(), parse_probes(), print_objfile_statistics(), print_symbol_bcache_statistics(), process_imported_unit_die(), process_queue(), pspy_get_filename(), read_addr_index_1(), read_call_site_scope(), read_common_block(), read_import_statement(), read_one_sym(), read_partial_die(), read_str_index(), read_subrange_type(), read_typedef(), require_partial_symbols(), reread_symbols(), save_gdb_index_command(), scan_file_globals(), scan_partial_symbols(), separate_debug_file_exists(), solib_aix_get_toc_value(), solib_read_symbols(), som_solib_section_offsets(), source_gdb_script_for_objfile(), sym_info(), symbol_file_clear(), target_info(), target_translate_tls_address(), thread_db_new_objfile(), try_thread_db_load_from_pdir(), try_thread_db_load_from_pdir_1(), type_name_no_tag_or_error(), write_psymtabs_to_index(), and xcoff_initial_scan().
void objfile_purge_solibs (void)
Definition at line 1039 of file objfiles.c.
References ALL_OBJFILES_SAFE, objfile::flags, free_objfile(), OBJF_SHARED, and OBJF_USERLOADED.
Referenced by no_shared_libraries().
void objfile_rebase (struct objfile * , CORE_ADDR)
Definition at line 940 of file objfiles.c.
References breakpoint_re_set(), objfile_rebase1(), objfile_separate_debug_iterate(), and objfile::separate_debug_objfile.
Referenced by darwin_solib_create_inferior_hook().
void objfile_relocate (struct objfile * , const struct section_offsets *)
Definition at line 875 of file objfiles.c.
References addr_info_make_relative(), breakpoint_re_set(), build_section_addr_info_from_objfile(), do_cleanups(), gdb_assert, gdb_bfd_count_sections(), make_cleanup(), objfile::num_sections, objfile::obfd, objfile_relocate1(), objfile_separate_debug_iterate(), relative_addr_info_to_section_offsets(), objfile::separate_debug_objfile, SIZEOF_N_SECTION_OFFSETS, xfree(), and xmalloc().
Referenced by dsbt_relocate_main_executable(), frv_relocate_main_executable(), get_offsets(), solib_aix_solib_create_inferior_hook(), spu_relocate_main_executable(), and svr4_relocate_main_executable().
struct objfile* objfile_separate_debug_iterate (const struct objfile * , const struct objfile *) [read]
Definition at line 390 of file objfiles.c.
References gdb_assert, objfile::separate_debug_objfile, objfile::separate_debug_objfile_backlink, and objfile::separate_debug_objfile_link.
Referenced by lookup_global_symbol_from_objfile(), lookup_minimal_symbol_by_pc_section_1(), lookup_symbol_in_objfile_from_linkage_name(), objfile_has_symbols(), objfile_rebase(), and objfile_relocate().
void objfile_set_sym_fns (struct objfile * objfile, const struct sym_fns * sf)
Definition at line 710 of file symfile-debug.c.
References debug_symfile, gdb_assert, install_symfile_debug_logging(), objfile::sf, symfile_debug_installed(), and uninstall_symfile_debug_logging().
Referenced by elf_symfile_read(), reread_symbols(), and syms_from_objfile_1().
void objfile_to_front (struct objfile *)
Definition at line 448 of file objfiles.c.
References objfile::next, and object_files.
void objfiles_changed (void)
Definition at line 1441 of file objfiles.c.
References current_program_space, get_objfile_pspace_data(), and objfile_pspace_info::section_map_dirty.
Referenced by reread_symbols().
int pc_in_section (CORE_ADDR , char *)
Definition at line 1423 of file objfiles.c.
References find_pc_section(), and obj_section::the_bfd_section.
Referenced by hppa64_hpux_find_global_pointer(), in_mips_stubs_section(), and in_plt_section().
void print_objfile_statistics (void)
Definition at line 99 of file symmisc.c.
References _, ALL_OBJFILE_SYMTABS, ALL_PSPACE_OBJFILES, ALL_PSPACES, bcache_memory_used(), objfile_per_bfd_storage::filename_cache, symtab::linetable, objfile_per_bfd_storage::macro_cache, objfile_name(), objfile::objfile_obstack, OBJSTAT, objfile::per_bfd, symtab::primary, quick_symbol_functions::print_stats, printf_filtered(), psymbol_bcache_get_bcache(), objfile::psymbol_cache, sym_fns::qf, QUIT, objfile::sf, and objfile_per_bfd_storage::storage_obstack.
Referenced by maintenance_print_statistics().
void print_symbol_bcache_statistics (void)
Definition at line 78 of file symmisc.c.
References _, ALL_PSPACE_OBJFILES, ALL_PSPACES, objfile_per_bfd_storage::filename_cache, objfile_per_bfd_storage::macro_cache, objfile_name(), objfile::per_bfd, print_bcache_statistics(), printf_filtered(), psymbol_bcache_get_bcache(), objfile::psymbol_cache, and QUIT.
Referenced by maintenance_print_statistics().
void put_objfile_before (struct objfile * , struct objfile *)
Definition at line 425 of file objfiles.c.
References _, internal_error(), objfile::next, object_files, and unlink_objfile().
Referenced by add_separate_debug_objfile().
void resume_section_map_updates (struct program_space * pspace)
Definition at line 1458 of file objfiles.c.
References get_objfile_pspace_data(), and objfile_pspace_info::inhibit_updates.
Referenced by resume_section_map_updates_cleanup().
void resume_section_map_updates_cleanup (void * arg)
Definition at line 1466 of file objfiles.c.
References resume_section_map_updates().
Referenced by svr4_handle_solib_event().
void set_objfile_per_bfd (struct objfile * obj)
Definition at line 188 of file objfiles.c.
References get_objfile_bfd_data(), objfile::obfd, and objfile::per_bfd.
Referenced by reread_symbols().
void terminate_minimal_symbol_table (struct objfile * objfile)
Create the terminating entry of OBJFILE's minimal symbol table. If OBJFILE->msymbols is zero, allocate a single entry from OBJFILE->objfile_obstack; otherwise, just initialize OBJFILE->msymbols[OBJFILE->minimal_symbol_count].
Definition at line 1268 of file minsyms.c.
References language_unknown, arm-linux::m, memset(), objfile::minimal_symbol_count, mst_unknown, MSYMBOL_TYPE, objfile::msymbols, objfile::objfile_obstack, and SYMBOL_SET_LANGUAGE.
Referenced by allocate_objfile(), jit_object_close_impl(), and reread_symbols().
void unlink_objfile (struct objfile *)
Definition at line 479 of file objfiles.c.
References _, internal_error(), objfile::next, and object_files.
Referenced by free_objfile(), and put_objfile_before().