GDB (xrefs): /home/stan/gdb/linux/gdb/observer.h File Reference
/home/stan/gdb/linux/gdb/observer.h File Reference
Typedefs
typedef void(observer_normal_stop_ftype)(struct bpstats *bs, int print_frame)
typedef void(observer_target_changed_ftype)(struct target_ops *target)
typedef void(observer_executable_changed_ftype)(void)
typedef void(observer_inferior_created_ftype)(struct target_ops *objfile, int from_tty)
typedef void(observer_record_changed_ftype)(struct inferior *inferior, int started)
typedef void(observer_solib_loaded_ftype)(struct so_list *solib)
typedef void(observer_solib_unloaded_ftype)(struct so_list *solib)
typedef void(observer_new_objfile_ftype)(struct objfile *objfile)
typedef void(observer_new_thread_ftype)(struct thread_info *t)
typedef void(observer_thread_exit_ftype)(struct thread_info *t, int silent)
typedef void(observer_thread_stop_requested_ftype)(ptid_t ptid)
typedef void(observer_target_resumed_ftype)(ptid_t ptid)
typedef void(observer_about_to_proceed_ftype)(void)
typedef void(observer_breakpoint_created_ftype)(struct breakpoint *b)
typedef void(observer_breakpoint_deleted_ftype)(struct breakpoint *b)
typedef void(observer_breakpoint_modified_ftype)(struct breakpoint *b)
typedef void(observer_traceframe_changed_ftype)(int tfnum, int tpnum)
typedef void(observer_architecture_changed_ftype)(struct gdbarch *newarch)
typedef void(observer_thread_ptid_changed_ftype)(ptid_t old_ptid, ptid_t new_ptid)
typedef void(observer_inferior_added_ftype)(struct inferior *inf)
typedef void(observer_inferior_appeared_ftype)(struct inferior *inf)
typedef void(observer_inferior_exit_ftype)(struct inferior *inf)
typedef void(observer_inferior_removed_ftype)(struct inferior *inf)
typedef void(observer_memory_changed_ftype)(struct inferior *inferior, CORE_ADDR addr, ssize_t len, const bfd_byte *data)
typedef void(observer_before_prompt_ftype)(const char *current_prompt)
typedef void(observer_gdb_datadir_changed_ftype)(void)
typedef void(observer_command_param_changed_ftype)(const char *param, const char *value)
typedef void(observer_tsv_created_ftype)(const struct trace_state_variable *tsv)
typedef void(observer_tsv_deleted_ftype)(const struct trace_state_variable *tsv)
typedef void(observer_tsv_modified_ftype)(const struct trace_state_variable *tsv)
typedef void(observer_test_notification_ftype)(int somearg)
Functions
struct observer * observer_attach_normal_stop (observer_normal_stop_ftype *f)
void observer_detach_normal_stop (struct observer *observer)
void observer_notify_normal_stop (struct bpstats *bs, int print_frame)
struct observer * observer_attach_target_changed (observer_target_changed_ftype *f)
void observer_detach_target_changed (struct observer *observer)
void observer_notify_target_changed (struct target_ops *target)
struct observer * observer_attach_executable_changed (observer_executable_changed_ftype *f)
void observer_detach_executable_changed (struct observer *observer)
void observer_notify_executable_changed (void)
struct observer * observer_attach_inferior_created (observer_inferior_created_ftype *f)
void observer_detach_inferior_created (struct observer *observer)
void observer_notify_inferior_created (struct target_ops *objfile, int from_tty)
struct observer * observer_attach_record_changed (observer_record_changed_ftype *f)
void observer_detach_record_changed (struct observer *observer)
void observer_notify_record_changed (struct inferior *inferior, int started)
struct observer * observer_attach_solib_loaded (observer_solib_loaded_ftype *f)
void observer_detach_solib_loaded (struct observer *observer)
void observer_notify_solib_loaded (struct so_list *solib)
struct observer * observer_attach_solib_unloaded (observer_solib_unloaded_ftype *f)
void observer_detach_solib_unloaded (struct observer *observer)
void observer_notify_solib_unloaded (struct so_list *solib)
struct observer * observer_attach_new_objfile (observer_new_objfile_ftype *f)
void observer_detach_new_objfile (struct observer *observer)
void observer_notify_new_objfile (struct objfile *objfile)
struct observer * observer_attach_new_thread (observer_new_thread_ftype *f)
void observer_detach_new_thread (struct observer *observer)
void observer_notify_new_thread (struct thread_info *t)
struct observer * observer_attach_thread_exit (observer_thread_exit_ftype *f)
void observer_detach_thread_exit (struct observer *observer)
void observer_notify_thread_exit (struct thread_info *t, int silent)
struct observer * observer_attach_thread_stop_requested (observer_thread_stop_requested_ftype *f)
void observer_detach_thread_stop_requested (struct observer *observer)
void observer_notify_thread_stop_requested (ptid_t ptid)
struct observer * observer_attach_target_resumed (observer_target_resumed_ftype *f)
void observer_detach_target_resumed (struct observer *observer)
void observer_notify_target_resumed (ptid_t ptid)
struct observer * observer_attach_about_to_proceed (observer_about_to_proceed_ftype *f)
void observer_detach_about_to_proceed (struct observer *observer)
void observer_notify_about_to_proceed (void)
struct observer * observer_attach_breakpoint_created (observer_breakpoint_created_ftype *f)
void observer_detach_breakpoint_created (struct observer *observer)
void observer_notify_breakpoint_created (struct breakpoint *b)
struct observer * observer_attach_breakpoint_deleted (observer_breakpoint_deleted_ftype *f)
void observer_detach_breakpoint_deleted (struct observer *observer)
void observer_notify_breakpoint_deleted (struct breakpoint *b)
struct observer * observer_attach_breakpoint_modified (observer_breakpoint_modified_ftype *f)
void observer_detach_breakpoint_modified (struct observer *observer)
void observer_notify_breakpoint_modified (struct breakpoint *b)
struct observer * observer_attach_traceframe_changed (observer_traceframe_changed_ftype *f)
void observer_detach_traceframe_changed (struct observer *observer)
void observer_notify_traceframe_changed (int tfnum, int tpnum)
struct observer * observer_attach_architecture_changed (observer_architecture_changed_ftype *f)
void observer_detach_architecture_changed (struct observer *observer)
void observer_notify_architecture_changed (struct gdbarch *newarch)
struct observer * observer_attach_thread_ptid_changed (observer_thread_ptid_changed_ftype *f)
void observer_detach_thread_ptid_changed (struct observer *observer)
void observer_notify_thread_ptid_changed (ptid_t old_ptid, ptid_t new_ptid)
struct observer * observer_attach_inferior_added (observer_inferior_added_ftype *f)
void observer_detach_inferior_added (struct observer *observer)
void observer_notify_inferior_added (struct inferior *inf)
struct observer * observer_attach_inferior_appeared (observer_inferior_appeared_ftype *f)
void observer_detach_inferior_appeared (struct observer *observer)
void observer_notify_inferior_appeared (struct inferior *inf)
struct observer * observer_attach_inferior_exit (observer_inferior_exit_ftype *f)
void observer_detach_inferior_exit (struct observer *observer)
void observer_notify_inferior_exit (struct inferior *inf)
struct observer * observer_attach_inferior_removed (observer_inferior_removed_ftype *f)
void observer_detach_inferior_removed (struct observer *observer)
void observer_notify_inferior_removed (struct inferior *inf)
struct observer * observer_attach_memory_changed (observer_memory_changed_ftype *f)
void observer_detach_memory_changed (struct observer *observer)
void observer_notify_memory_changed (struct inferior *inferior, CORE_ADDR addr, ssize_t len, const bfd_byte *data)
struct observer * observer_attach_before_prompt (observer_before_prompt_ftype *f)
void observer_detach_before_prompt (struct observer *observer)
void observer_notify_before_prompt (const char *current_prompt)
struct observer * observer_attach_gdb_datadir_changed (observer_gdb_datadir_changed_ftype *f)
void observer_detach_gdb_datadir_changed (struct observer *observer)
void observer_notify_gdb_datadir_changed (void)
struct observer * observer_attach_command_param_changed (observer_command_param_changed_ftype *f)
void observer_detach_command_param_changed (struct observer *observer)
void observer_notify_command_param_changed (const char *param, const char *value)
struct observer * observer_attach_tsv_created (observer_tsv_created_ftype *f)
void observer_detach_tsv_created (struct observer *observer)
void observer_notify_tsv_created (const struct trace_state_variable *tsv)
struct observer * observer_attach_tsv_deleted (observer_tsv_deleted_ftype *f)
void observer_detach_tsv_deleted (struct observer *observer)
void observer_notify_tsv_deleted (const struct trace_state_variable *tsv)
struct observer * observer_attach_tsv_modified (observer_tsv_modified_ftype *f)
void observer_detach_tsv_modified (struct observer *observer)
void observer_notify_tsv_modified (const struct trace_state_variable *tsv)
struct observer * observer_attach_test_notification (observer_test_notification_ftype *f)
void observer_detach_test_notification (struct observer *observer)
void observer_notify_test_notification (int somearg)
Typedef Documentation
typedef void(observer_about_to_proceed_ftype)(void)
Definition at line 133 of file observer.h.
typedef void(observer_architecture_changed_ftype)(struct gdbarch *newarch)
Definition at line 173 of file observer.h.
typedef void(observer_before_prompt_ftype)(const char *current_prompt)
Definition at line 229 of file observer.h.
typedef void(observer_breakpoint_created_ftype)(struct breakpoint *b)
Definition at line 141 of file observer.h.
typedef void(observer_breakpoint_deleted_ftype)(struct breakpoint *b)
Definition at line 149 of file observer.h.
typedef void(observer_breakpoint_modified_ftype)(struct breakpoint *b)
Definition at line 157 of file observer.h.
typedef void(observer_command_param_changed_ftype)(const char *param, const char *value)
Definition at line 245 of file observer.h.
typedef void(observer_executable_changed_ftype)(void)
Definition at line 53 of file observer.h.
typedef void(observer_gdb_datadir_changed_ftype)(void)
Definition at line 237 of file observer.h.
typedef void(observer_inferior_added_ftype)(struct inferior *inf)
Definition at line 189 of file observer.h.
typedef void(observer_inferior_appeared_ftype)(struct inferior *inf)
Definition at line 197 of file observer.h.
typedef void(observer_inferior_created_ftype)(struct target_ops *objfile, int from_tty)
Definition at line 61 of file observer.h.
typedef void(observer_inferior_exit_ftype)(struct inferior *inf)
Definition at line 205 of file observer.h.
typedef void(observer_inferior_removed_ftype)(struct inferior *inf)
Definition at line 213 of file observer.h.
typedef void(observer_memory_changed_ftype)(struct inferior *inferior, CORE_ADDR addr, ssize_t len, const bfd_byte *data)
Definition at line 221 of file observer.h.
typedef void(observer_new_objfile_ftype)(struct objfile *objfile)
Definition at line 93 of file observer.h.
typedef void(observer_new_thread_ftype)(struct thread_info *t)
Definition at line 101 of file observer.h.
typedef void(observer_normal_stop_ftype)(struct bpstats *bs, int print_frame)
Definition at line 37 of file observer.h.
typedef void(observer_record_changed_ftype)(struct inferior *inferior, int started)
Definition at line 69 of file observer.h.
typedef void(observer_solib_loaded_ftype)(struct so_list *solib)
Definition at line 77 of file observer.h.
typedef void(observer_solib_unloaded_ftype)(struct so_list *solib)
Definition at line 85 of file observer.h.
typedef void(observer_target_changed_ftype)(struct target_ops *target)
Definition at line 45 of file observer.h.
typedef void(observer_target_resumed_ftype)(ptid_t ptid)
Definition at line 125 of file observer.h.
typedef void(observer_test_notification_ftype)(int somearg)
Definition at line 277 of file observer.h.
typedef void(observer_thread_exit_ftype)(struct thread_info *t, int silent)
Definition at line 109 of file observer.h.
typedef void(observer_thread_ptid_changed_ftype)(ptid_t old_ptid, ptid_t new_ptid)
Definition at line 181 of file observer.h.
typedef void(observer_thread_stop_requested_ftype)(ptid_t ptid)
Definition at line 117 of file observer.h.
typedef void(observer_traceframe_changed_ftype)(int tfnum, int tpnum)
Definition at line 165 of file observer.h.
typedef void(observer_tsv_created_ftype)(const struct trace_state_variable *tsv)
Definition at line 253 of file observer.h.
typedef void(observer_tsv_deleted_ftype)(const struct trace_state_variable *tsv)
Definition at line 261 of file observer.h.
typedef void(observer_tsv_modified_ftype)(const struct trace_state_variable *tsv)
Definition at line 269 of file observer.h.
Function Documentation
struct observer* observer_attach_about_to_proceed (observer_about_to_proceed_ftype * f) [read]
Referenced by mi_interpreter_init(), and tui_install_hooks().
struct observer* observer_attach_architecture_changed (observer_architecture_changed_ftype * f) [read]
Referenced by gdbtk_add_hooks().
struct observer* observer_attach_before_prompt (observer_before_prompt_ftype * f) [read]
Referenced by _initialize_python().
struct observer* observer_attach_breakpoint_created (observer_breakpoint_created_ftype * f) [read]
Referenced by gdbpy_initialize_breakpoints(), gdbtk_add_hooks(), mi_interpreter_init(), setup_breakpoint_reporting(), and tui_install_hooks().
struct observer* observer_attach_breakpoint_deleted (observer_breakpoint_deleted_ftype * f) [read]
Referenced by gdbpy_initialize_breakpoints(), gdbtk_add_hooks(), mi_interpreter_init(), and tui_install_hooks().
struct observer* observer_attach_breakpoint_modified (observer_breakpoint_modified_ftype * f) [read]
Referenced by gdbtk_add_hooks(), mi_interpreter_init(), and tui_install_hooks().
struct observer* observer_attach_command_param_changed (observer_command_param_changed_ftype * f) [read]
Referenced by mi_interpreter_init().
struct observer* observer_attach_executable_changed (observer_executable_changed_ftype * f) [read]
Referenced by _initialize_auxv().
struct observer* observer_attach_gdb_datadir_changed (observer_gdb_datadir_changed_ftype * f) [read]
struct observer* observer_attach_inferior_added (observer_inferior_added_ftype * f) [read]
Referenced by mi_interpreter_init().
struct observer* observer_attach_inferior_appeared (observer_inferior_appeared_ftype * f) [read]
Referenced by _initialize_auxv(), and mi_interpreter_init().
struct observer* observer_attach_inferior_created (observer_inferior_created_ftype * f) [read]
Referenced by _initialize_bsd_uthread(), _initialize_m68k_linux_tdep(), _initialize_ppc_linux_tdep(), _initialize_spu_multiarch(), _initialize_symfile_mem(), and _initialize_thread_db().
struct observer* observer_attach_inferior_exit (observer_inferior_exit_ftype * f) [read]
Referenced by _initialize_ada_language(), _initialize_auxv(), gdbpy_initialize_finishbreakpoints(), gdbpy_initialize_inferior(), mi_interpreter_init(), and tui_install_hooks().
struct observer* observer_attach_inferior_removed (observer_inferior_removed_ftype * f) [read]
Referenced by mi_interpreter_init().
struct observer* observer_attach_memory_changed (observer_memory_changed_ftype * f) [read]
Referenced by gdbtk_add_hooks(), and mi_interpreter_init().
struct observer* observer_attach_new_objfile (observer_new_objfile_ftype * f) [read]
Referenced by _initialize_agent(), _initialize_aix_thread(), _initialize_arm_tdep(), _initialize_dec_thread(), _initialize_sol_thread(), _initialize_spu_tdep(), _initialize_tasks(), _initialize_thread_db(), and gdbpy_initialize_inferior().
struct observer* observer_attach_new_thread (observer_new_thread_ftype * f) [read]
Referenced by gdbpy_initialize_inferior(), mi_interpreter_init(), and record_btrace_auto_enable().
struct observer* observer_attach_normal_stop (observer_normal_stop_ftype * f) [read]
Referenced by _initialize_solib_aix(), _initialize_spu_tdep(), _initialize_tasks(), gdbpy_initialize_finishbreakpoints(), gdbpy_initialize_inferior(), and mi_interpreter_init().
struct observer* observer_attach_record_changed (observer_record_changed_ftype * f) [read]
Referenced by mi_interpreter_init().
struct observer* observer_attach_solib_loaded (observer_solib_loaded_ftype * f) [read]
Referenced by _initialize_bsd_uthread(), _initialize_ppc_linux_tdep(), _initialize_spu_multiarch(), _initialize_spu_solib(), and mi_interpreter_init().
struct observer* observer_attach_solib_unloaded (observer_solib_unloaded_ftype * f) [read]
Referenced by _initialize_bsd_uthread(), _initialize_ppc_linux_tdep(), _initialize_spu_multiarch(), and mi_interpreter_init().
struct observer* observer_attach_target_changed (observer_target_changed_ftype * f) [read]
Referenced by _initialize_frame(), and _initialize_regcache().
struct observer* observer_attach_target_resumed (observer_target_resumed_ftype * f) [read]
Referenced by gdbpy_initialize_inferior(), and mi_interpreter_init().
struct observer* observer_attach_test_notification (observer_test_notification_ftype * f) [read]
struct observer* observer_attach_thread_exit (observer_thread_exit_ftype * f) [read]
Referenced by _initialize_arm_linux_nat(), _initialize_ppc_linux_nat(), gdbpy_initialize_inferior(), and mi_interpreter_init().
struct observer* observer_attach_thread_ptid_changed (observer_thread_ptid_changed_ftype * f) [read]
Referenced by _initialize_regcache().
struct observer* observer_attach_thread_stop_requested (observer_thread_stop_requested_ftype * f) [read]
struct observer* observer_attach_traceframe_changed (observer_traceframe_changed_ftype * f) [read]
Referenced by mi_interpreter_init().
struct observer* observer_attach_tsv_created (observer_tsv_created_ftype * f) [read]
Referenced by mi_interpreter_init().
struct observer* observer_attach_tsv_deleted (observer_tsv_deleted_ftype * f) [read]
Referenced by mi_interpreter_init().
struct observer* observer_attach_tsv_modified (observer_tsv_modified_ftype * f) [read]
Referenced by mi_interpreter_init().
void observer_detach_about_to_proceed (struct observer * observer)
Referenced by tui_remove_hooks().
void observer_detach_architecture_changed (struct observer * observer)
void observer_detach_before_prompt (struct observer * observer)
void observer_detach_breakpoint_created (struct observer * observer)
Referenced by tui_remove_hooks().
void observer_detach_breakpoint_deleted (struct observer * observer)
Referenced by tui_remove_hooks().
void observer_detach_breakpoint_modified (struct observer * observer)
Referenced by tui_remove_hooks().
void observer_detach_command_param_changed (struct observer * observer)
void observer_detach_executable_changed (struct observer * observer)
void observer_detach_gdb_datadir_changed (struct observer * observer)
void observer_detach_inferior_added (struct observer * observer)
void observer_detach_inferior_appeared (struct observer * observer)
void observer_detach_inferior_created (struct observer * observer)
void observer_detach_inferior_exit (struct observer * observer)
Referenced by tui_remove_hooks().
void observer_detach_inferior_removed (struct observer * observer)
void observer_detach_memory_changed (struct observer * observer)
void observer_detach_new_objfile (struct observer * observer)
void observer_detach_new_thread (struct observer * observer)
Referenced by record_btrace_auto_disable().
void observer_detach_normal_stop (struct observer * observer)
void observer_detach_record_changed (struct observer * observer)
void observer_detach_solib_loaded (struct observer * observer)
void observer_detach_solib_unloaded (struct observer * observer)
void observer_detach_target_changed (struct observer * observer)
void observer_detach_target_resumed (struct observer * observer)
void observer_detach_test_notification (struct observer * observer)
void observer_detach_thread_exit (struct observer * observer)
void observer_detach_thread_ptid_changed (struct observer * observer)
void observer_detach_thread_stop_requested (struct observer * observer)
void observer_detach_traceframe_changed (struct observer * observer)
void observer_detach_tsv_created (struct observer * observer)
void observer_detach_tsv_deleted (struct observer * observer)
void observer_detach_tsv_modified (struct observer * observer)
void observer_notify_about_to_proceed (void)
Referenced by clear_proceed_status().
void observer_notify_architecture_changed (struct gdbarch * newarch)
Referenced by set_target_gdbarch().
void observer_notify_before_prompt (const char * current_prompt)
Referenced by top_level_prompt().
void observer_notify_breakpoint_created (struct breakpoint * b)
Referenced by break_range_command(), and install_breakpoint().
void observer_notify_breakpoint_deleted (struct breakpoint * b)
Referenced by delete_breakpoint().
void observer_notify_breakpoint_modified (struct breakpoint * b)
Referenced by bpstat_check_breakpoint_conditions(), bpstat_stop_status(), breakpoint_set_commands(), breakpoint_set_silent(), breakpoint_set_task(), breakpoint_set_thread(), disable_breakpoint(), disable_breakpoints_in_unloaded_shlib(), do_map_commands_command(), download_tracepoint_locations(), enable_breakpoint_disp(), insert_bp_location(), merge_uploaded_tracepoints(), mi_cmd_break_passcount(), set_breakpoint_condition(), set_ignore_count(), start_tracing(), trace_pass_set_count(), and update_breakpoint_locations().
void observer_notify_command_param_changed (const char * param, const char * value)
Referenced by do_set_command().
void observer_notify_executable_changed (void)
Referenced by exec_file_attach(), and reread_symbols().
void observer_notify_gdb_datadir_changed (void)
Referenced by set_gdb_datadir().
void observer_notify_inferior_added (struct inferior * inf)
Referenced by add_inferior_silent().
void observer_notify_inferior_appeared (struct inferior * inf)
Referenced by inferior_appeared().
void observer_notify_inferior_created (struct target_ops * objfile, int from_tty)
Referenced by post_create_inferior().
void observer_notify_inferior_exit (struct inferior * inf)
Referenced by exit_inferior_1().
void observer_notify_inferior_removed (struct inferior * inf)
Referenced by delete_inferior_1().
void observer_notify_memory_changed (struct inferior * inferior, CORE_ADDR addr, ssize_t len, const bfd_byte * data)
Referenced by write_memory_with_notification().
void observer_notify_new_objfile (struct objfile * objfile)
Referenced by clear_symtab_users(), reread_symbols(), and symbol_file_add_with_addrs().
void observer_notify_new_thread (struct thread_info * t)
Referenced by add_thread_silent().
void observer_notify_normal_stop (struct bpstats * bs, int print_frame)
Referenced by finish_command_continuation(), and normal_stop().
void observer_notify_record_changed (struct inferior * inferior, int started)
Referenced by cmd_record_stop(), record_btrace_open(), and record_full_open().
void observer_notify_solib_loaded (struct so_list * solib)
Referenced by update_solib_list().
void observer_notify_solib_unloaded (struct so_list * solib)
Referenced by clear_solib(), and update_solib_list().
void observer_notify_target_changed (struct target_ops * target)
Referenced by value_assign().
void observer_notify_target_resumed (ptid_t ptid)
Referenced by finish_thread_state(), and set_running().
void observer_notify_test_notification (int somearg)
void observer_notify_thread_exit (struct thread_info * t, int silent)
Referenced by delete_thread_1().
void observer_notify_thread_ptid_changed (ptid_t old_ptid, ptid_t new_ptid)
Referenced by thread_change_ptid().
void observer_notify_thread_stop_requested (ptid_t ptid)
Referenced by set_stop_requested().
void observer_notify_traceframe_changed (int tfnum, int tpnum)
Referenced by tfind_1().
void observer_notify_tsv_created (const struct trace_state_variable * tsv)
Referenced by create_tsv_from_upload(), and trace_variable_command().
void observer_notify_tsv_deleted (const struct trace_state_variable * tsv)
Referenced by delete_trace_state_variable(), and delete_trace_variable_command().
void observer_notify_tsv_modified (const struct trace_state_variable * tsv)
Referenced by trace_variable_command().