GDB (xrefs): /home/stan/gdb/src/gdb/osabi.h File Reference
/home/stan/gdb/src/gdb/osabi.h File Reference
Functions
void gdbarch_register_osabi_sniffer (enum bfd_architecture, enum bfd_flavour, enum gdb_osabi(*)(bfd *))
void gdbarch_register_osabi (enum bfd_architecture, unsigned long, enum gdb_osabi, void(*)(struct gdbarch_info, struct gdbarch *))
enum gdb_osabi gdbarch_lookup_osabi (bfd *)
enum gdb_osabi osabi_from_tdesc_string (const char *text)
void gdbarch_init_osabi (struct gdbarch_info, struct gdbarch *)
const char * gdbarch_osabi_name (enum gdb_osabi)
void generic_elf_osabi_sniff_abi_tag_sections (bfd *, asection *, void *)
Function Documentation
void gdbarch_init_osabi (struct gdbarch_info , struct gdbarch *)
Definition at line 320 of file osabi.c.
References gdb_osabi_handler::arch_info, gdbarch_info::bfd_arch_info, can_run_code_for(), GDB_OSABI_UNKNOWN, gdbarch_osabi_name(), gdb_osabi_handler::init_osabi, gdb_osabi_handler::next, gdb_osabi_handler::osabi, gdbarch_info::osabi, and warning().
Referenced by aarch64_gdbarch_init(), alpha_gdbarch_init(), arm_gdbarch_init(), bfin_gdbarch_init(), cris_gdbarch_init(), frv_gdbarch_init(), hppa_gdbarch_init(), i386_gdbarch_init(), ia64_gdbarch_init(), iq2000_gdbarch_init(), m32r_gdbarch_init(), m68k_gdbarch_init(), microblaze_gdbarch_init(), mips_gdbarch_init(), mn10300_gdbarch_init(), moxie_gdbarch_init(), nios2_gdbarch_init(), rs6000_gdbarch_init(), sh64_gdbarch_init(), sh_gdbarch_init(), sparc32_gdbarch_init(), tic6x_gdbarch_init(), tilegx_gdbarch_init(), v850_gdbarch_init(), vax_gdbarch_init(), and xstormy16_gdbarch_init().
enum gdb_osabi gdbarch_lookup_osabi (bfd *)
Definition at line 222 of file osabi.c.
References _, gdb_osabi_sniffer::arch, gdb_osabi_sniffer::flavour, GDB_OSABI_INVALID, GDB_OSABI_UNKNOWN, gdbarch_osabi_name(), internal_error(), gdb_osabi_sniffer::next, osabi_user, gdb_osabi_sniffer::sniffer, user_osabi_state, and user_selected_osabi.
Referenced by gdbarch_info_fill().
const char* gdbarch_osabi_name (enum gdb_osabi)
Definition at line 82 of file osabi.c.
References GDB_OSABI_INVALID, gdb_osabi_names, and GDB_OSABI_UNKNOWN.
Referenced by gdbarch_find_by_info(), gdbarch_init_osabi(), gdbarch_lookup_osabi(), gdbarch_register_osabi(), maint_print_c_tdesc_cmd(), set_osabi(), and show_osabi().
void gdbarch_register_osabi (enum bfd_architecture, unsigned long, enum gdb_osabi, void(*)(struct gdbarch_info, struct gdbarch *))
Definition at line 127 of file osabi.c.
References _, gdb_osabi_handler::arch_info, gdb_assert, gdb_osabi_available_names, GDB_OSABI_UNKNOWN, gdbarch_osabi_name(), gdb_osabi_handler::init_osabi, internal_error(), gdb_osabi_handler::next, gdb_osabi_handler::osabi, and xmalloc().
Referenced by _initialize_aarch64_linux_tdep(), _initialize_aarch64_newlib_tdep(), _initialize_alpha_linux_tdep(), _initialize_alpha_osf1_tdep(), _initialize_alphafbsd_tdep(), _initialize_alphanbsd_tdep(), _initialize_alphaobsd_tdep(), _initialize_amd64_darwin_tdep(), _initialize_amd64_dicos_tdep(), _initialize_amd64_linux_tdep(), _initialize_amd64_sol2_tdep(), _initialize_amd64_windows_tdep(), _initialize_amd64fbsd_tdep(), _initialize_amd64nbsd_tdep(), _initialize_amd64obsd_tdep(), _initialize_arm_linux_tdep(), _initialize_arm_netbsd_tdep(), _initialize_arm_symbian_tdep(), _initialize_armobsd_tdep(), _initialize_bfin_linux_tdep(), _initialize_cris_linux_tdep(), _initialize_hppa_linux_tdep(), _initialize_hppanbsd_tdep(), _initialize_i386_darwin_tdep(), _initialize_i386nbsd_tdep(), _initialize_i386nto_tdep(), _initialize_ia64_hpux_tdep(), _initialize_ia64_linux_tdep(), _initialize_ia64_vms_tdep(), _initialize_m68k_linux_tdep(), _initialize_microblaze_linux_tdep(), _initialize_mips64obsd_tdep(), _initialize_mips_irix_tdep(), _initialize_mips_linux_tdep(), _initialize_mipsnbsd_tdep(), _initialize_mn10300_linux_tdep(), _initialize_nios2_linux_tdep(), _initialize_ppc_linux_tdep(), _initialize_rs6000_aix_tdep(), _initialize_rs6000_lynx178_tdep(), _initialize_shnbsd_tdep(), _initialize_sparc64_linux_tdep(), _initialize_sparc64_sol2_tdep(), _initialize_sparc64fbsd_tdep(), _initialize_sparc64nbsd_tdep(), _initialize_sparc64obsd_tdep(), _initialize_tic6x_linux_tdep(), _initialize_tilegx_linux_tdep(), and _initialize_xtensa_linux_tdep().
void gdbarch_register_osabi_sniffer (enum bfd_architecture, enum bfd_flavour, enum gdb_osabi*)(bfd *)
void generic_elf_osabi_sniff_abi_tag_sections (bfd * , asection * , void *)
Definition at line 423 of file osabi.c.
References _, check_note(), GDB_OSABI_FREEBSD_ELF, GDB_OSABI_HURD, GDB_OSABI_LINUX, GDB_OSABI_NETBSD_ELF, GDB_OSABI_OPENBSD_ELF, GDB_OSABI_SOLARIS, internal_error(), MAX_NOTESZ, and name.
Referenced by arm_elf_osabi_sniffer(), generic_elf_osabi_sniffer(), and mips_irix_elf_osabi_sniffer().
enum gdb_osabi osabi_from_tdesc_string (const char * text)
Definition at line 94 of file osabi.c.
References GDB_OSABI_INVALID, gdb_osabi_names, and GDB_OSABI_UNKNOWN.
Referenced by initialize_tdesc_amd64_avx_linux(), initialize_tdesc_amd64_linux(), initialize_tdesc_i386_avx_linux(), initialize_tdesc_i386_linux(), initialize_tdesc_i386_mmx_linux(), initialize_tdesc_mips_dsp_linux(), initialize_tdesc_mips_linux(), initialize_tdesc_nios2_linux(), initialize_tdesc_tic6x_c62x_linux(), initialize_tdesc_tic6x_c64x_linux(), initialize_tdesc_tic6x_c64xp_linux(), initialize_tdesc_x32_avx_linux(), and initialize_tdesc_x32_linux().