GDB (xrefs): /home/stan/gdb/src/gdb/osdata.h File Reference
/home/stan/gdb/src/gdb/osdata.h File Reference
#include "vec.h"
Classes
struct osdata_column
struct osdata_item
struct osdata
Typedefs
typedef struct osdata_column osdata_column_s
typedef struct osdata_item osdata_item_s
typedef struct osdata * osdata_p
Functions
DEF_VEC_O (osdata_column_s)
DEF_VEC_O (osdata_item_s)
DEF_VEC_P (osdata_p)
struct osdata * osdata_parse (const char *xml)
void osdata_free (struct osdata *)
struct cleanup * make_cleanup_osdata_free (struct osdata *data)
struct osdata * get_osdata (const char *type)
const char * get_osdata_column (struct osdata_item *item, const char *name)
void info_osdata_command (char *type, int from_tty)
Typedef Documentation
typedef struct osdata_column osdata_column_s
typedef struct osdata_item osdata_item_s
typedef struct osdata* osdata_p
Definition at line 44 of file osdata.h.
Function Documentation
DEF_VEC_O (osdata_column_s)
DEF_VEC_O (osdata_item_s)
DEF_VEC_P (osdata_p)
struct osdata* get_osdata (const char * type) [read]
Definition at line 247 of file osdata.c.
References _, do_cleanups(), error(), make_cleanup(), osdata_parse(), target_get_osdata(), warning(), and xfree().
Referenced by info_osdata_command(), and list_available_thread_groups().
const char* get_osdata_column (struct osdata_item * item, const char * name)
Definition at line 276 of file osdata.c.
References osdata_column::name, osdata_column::value, and VEC_iterate.
Referenced by list_available_thread_groups().
void info_osdata_command (char * type, int from_tty)
Definition at line 292 of file osdata.c.
References _, current_uiout, do_cleanups(), error(), get_osdata(), make_cleanup_osdata_free(), make_cleanup_ui_out_table_begin_end(), make_cleanup_ui_out_tuple_begin_end(), osdata_column::name, ui_left, ui_out_field_string(), ui_out_is_mi_like_p(), ui_out_table_body(), ui_out_table_header(), ui_out_text(), osdata_column::value, VEC_empty, VEC_iterate, VEC_last, and VEC_length.
Referenced by _initialize_osdata(), and mi_cmd_info_os().
struct cleanup* make_cleanup_osdata_free (struct osdata * data) [read]
Definition at line 241 of file osdata.c.
References make_cleanup(), and osdata_free_cleanup().
Referenced by info_osdata_command(), and list_available_thread_groups().
void osdata_free (struct osdata *)
Definition at line 211 of file osdata.c.
References osdata_item_clear(), VEC_free, VEC_iterate, and xfree().
Referenced by osdata_free_cleanup().
struct osdata* osdata_parse (const char * xml) [read]
Definition at line 32 of file osdata.c.
References _, and warning().
Referenced by get_osdata().