GDB (xrefs): /home/stan/gdb/linux/gdb/p-exp.c File Reference
/home/stan/gdb/linux/gdb/p-exp.c File Reference
#include "defs.h"
#include "gdb_string.h"
#include <ctype.h>
#include "expression.h"
#include "value.h"
#include "parser-defs.h"
#include "language.h"
#include "p-lang.h"
#include "bfd.h"
#include "symfile.h"
#include "objfiles.h"
#include "block.h"
#include "completer.h"
Classes
union YYSTYPE
union yyalloc
struct type_push
struct token
Defines
#define YYBISON 1
#define YYBISON_VERSION "2.5"
#define YYSKELETON_NAME "yacc.c"
#define YYPURE 0
#define YYPUSH 0
#define YYPULL 1
#define YYLSP_NEEDED 0
#define parse_type builtin_type (parse_gdbarch)
#define yymaxdepth pascal_maxdepth
#define yyparse pascal_parse
#define yylex pascal_lex
#define yyerror pascal_error
#define yylval pascal_lval
#define yychar pascal_char
#define yydebug pascal_debug
#define yypact pascal_pact
#define yyr1 pascal_r1
#define yyr2 pascal_r2
#define yydef pascal_def
#define yychk pascal_chk
#define yypgo pascal_pgo
#define yyact pascal_act
#define yyexca pascal_exca
#define yyerrflag pascal_errflag
#define yynerrs pascal_nerrs
#define yyps pascal_ps
#define yypv pascal_pv
#define yys pascal_s
#define yy_yys pascal_yys
#define yystate pascal_state
#define yytmp pascal_tmp
#define yyv pascal_v
#define yy_yyv pascal_yyv
#define yyval pascal_val
#define yylloc pascal_lloc
#define yyreds pascal_reds /* With YYDEBUG defined */
#define yytoks pascal_toks /* With YYDEBUG defined */
#define yyname pascal_name /* With YYDEBUG defined */
#define yyrule pascal_rule /* With YYDEBUG defined */
#define yylhs pascal_yylhs
#define yylen pascal_yylen
#define yydefred pascal_yydefred
#define yydgoto pascal_yydgoto
#define yysindex pascal_yysindex
#define yyrindex pascal_yyrindex
#define yygindex pascal_yygindex
#define yytable pascal_yytable
#define yycheck pascal_yycheck
#define yyss pascal_yyss
#define yysslim pascal_yysslim
#define yyssp pascal_yyssp
#define yystacksize pascal_yystacksize
#define yyvs pascal_yyvs
#define yyvsp pascal_yyvsp
#define YYDEBUG 1 /* Default to yydebug support */
#define YYFPRINTF parser_fprintf
#define YYERROR_VERBOSE 0
#define YYTOKEN_TABLE 0
#define YYTOKENTYPE
#define INT 258
#define FLOAT 259
#define STRING 260
#define FIELDNAME 261
#define COMPLETE 262
#define NAME 263
#define TYPENAME 264
#define NAME_OR_INT 265
#define STRUCT 266
#define CLASS 267
#define SIZEOF 268
#define COLONCOLON 269
#define ERROR 270
#define VARIABLE 271
#define THIS 272
#define TRUEKEYWORD 273
#define FALSEKEYWORD 274
#define ABOVE_COMMA 275
#define ASSIGN 276
#define NOT 277
#define OR 278
#define XOR 279
#define ANDAND 280
#define NOTEQUAL 281
#define GEQ 282
#define LEQ 283
#define MOD 284
#define DIV 285
#define RSH 286
#define LSH 287
#define DECREMENT 288
#define INCREMENT 289
#define UNARY 290
#define ARROW 291
#define BLOCKNAME 292
#define YYSTYPE_IS_TRIVIAL 1
#define yystype YYSTYPE /* obsolescent; will be withdrawn */
#define YYSTYPE_IS_DECLARED 1
#define YYSIZE_T unsigned int
#define YYSIZE_MAXIMUM ((YYSIZE_T) -1)
#define YY_(msgid) msgid
#define YYUSE(e) ((void) (e))
#define YYID(n) (n)
#define YYSTACK_ALLOC YYMALLOC
#define YYSTACK_FREE YYFREE
#define YYSTACK_ALLOC_MAXIMUM YYSIZE_MAXIMUM
#define YYMALLOC xmalloc
#define YYFREE xfree
#define YYSTACK_GAP_MAXIMUM (sizeof (union yyalloc) - 1)
#define YYSTACK_BYTES(N)
#define YYCOPY_NEEDED 1
#define YYSTACK_RELOCATE(Stack_alloc, Stack)
#define YYCOPY(To, From, Count)
#define YYFINAL 3
#define YYLAST 382
#define YYNTOKENS 53
#define YYNNTS 20
#define YYNRULES 76
#define YYNSTATES 125
#define YYUNDEFTOK 2
#define YYMAXUTOK 292
#define YYTRANSLATE(YYX) ((unsigned int) (YYX) <= YYMAXUTOK ? yytranslate[YYX] : YYUNDEFTOK)
#define YYPACT_NINF -43
#define YYTABLE_NINF -60
#define yypact_value_is_default(yystate) ((yystate) == (-43))
#define yytable_value_is_error(yytable_value) YYID (0)
#define yyerrok (yyerrstatus = 0)
#define yyclearin (yychar = YYEMPTY)
#define YYEMPTY (-2)
#define YYEOF 0
#define YYACCEPT goto yyacceptlab
#define YYABORT goto yyabortlab
#define YYERROR goto yyerrorlab
#define YYFAIL goto yyerrlab
#define YYRECOVERING() (!!yyerrstatus)
#define YYBACKUP(Token, Value)
#define YYTERROR 1
#define YYERRCODE 256
#define YYRHSLOC(Rhs, K) ((Rhs)[K])
#define YYLLOC_DEFAULT(Current, Rhs, N)
#define YY_LOCATION_PRINT(File, Loc) ((void) 0)
#define YYLEX yylex ()
#define YYDPRINTF(Args)
#define YY_SYMBOL_PRINT(Title, Type, Value, Location)
#define YY_STACK_PRINT(Bottom, Top)
#define YY_REDUCE_PRINT(Rule)
#define YYINITDEPTH 200
#define YYMAXDEPTH 10000
#define YYPOPSTACK(N) (yyvsp -= (N), yyssp -= (N))
Typedefs
typedef union YYSTYPE YYSTYPE
typedef unsigned char yytype_uint8
typedef short int yytype_int8
typedef unsigned short int yytype_uint16
typedef short int yytype_int16
Enumerations
enum yytokentype {
INT = 258, NULL_PTR = 259, CHARLIT = 260, FLOAT = 261,
TRUEKEYWORD = 262, FALSEKEYWORD = 263, COLONCOLON = 264, STRING = 265,
NAME = 266, DOT_ID = 267, DOT_ALL = 268, SPECIAL_VARIABLE = 269,
ASSIGN = 270, ELSE = 271, THEN = 272, XOR = 273,
OR = 274, _AND_ = 275, DOTDOT = 276, IN = 277,
GEQ = 278, LEQ = 279, NOTEQUAL = 280, UNARY = 281,
REM = 282, MOD = 283, NOT = 284, ABS = 285,
STARSTAR = 286, VAR = 287, ARROW = 288, TICK_LENGTH = 289,
TICK_LAST = 290, TICK_FIRST = 291, TICK_ADDRESS = 292, TICK_ACCESS = 293,
TICK_MODULUS = 294, TICK_MIN = 295, TICK_MAX = 296, TICK_VAL = 297,
TICK_TAG = 298, TICK_SIZE = 299, TICK_RANGE = 300, TICK_POS = 301,
NEW = 302, OTHERS = 303, INT = 258, FLOAT = 259,
DECFLOAT = 260, STRING = 261, NSSTRING = 262, SELECTOR = 263,
CHAR = 264, NAME = 265, UNKNOWN_CPP_NAME = 266, COMPLETE = 267,
TYPENAME = 268, CLASSNAME = 269, OBJC_LBRAC = 270, NAME_OR_INT = 271,
OPERATOR = 272, STRUCT = 273, CLASS = 274, UNION = 275,
ENUM = 276, SIZEOF = 277, UNSIGNED = 278, COLONCOLON = 279,
TEMPLATE = 280, ERROR = 281, NEW = 282, DELETE = 283,
REINTERPRET_CAST = 284, DYNAMIC_CAST = 285, STATIC_CAST = 286, CONST_CAST = 287,
ENTRY = 288, TYPEOF = 289, DECLTYPE = 290, TYPEID = 291,
SIGNED_KEYWORD = 292, LONG = 293, SHORT = 294, INT_KEYWORD = 295,
CONST_KEYWORD = 296, VOLATILE_KEYWORD = 297, DOUBLE_KEYWORD = 298, VARIABLE = 299,
ASSIGN_MODIFY = 300, TRUEKEYWORD = 301, FALSEKEYWORD = 302, ABOVE_COMMA = 303,
OROR = 304, ANDAND = 305, NOTEQUAL = 306, EQUAL = 307,
GEQ = 308, LEQ = 309, RSH = 310, LSH = 311,
DECREMENT = 312, INCREMENT = 313, UNARY = 314, DOT_STAR = 315,
ARROW_STAR = 316, ARROW = 317, BLOCKNAME = 318, FILENAME = 319,
DOTDOTDOT = 320, INT = 258, FLOAT = 259, NAME = 260,
STRUCT = 261, CLASS = 262, UNION = 263, ENUM = 264,
SIZEOF = 265, UNSIGNED = 266, COLONCOLON = 267, TEMPLATE = 268,
ERROR = 269, NEW = 270, DELETE = 271, OPERATOR = 272,
STATIC_CAST = 273, REINTERPRET_CAST = 274, DYNAMIC_CAST = 275, SIGNED_KEYWORD = 276,
LONG = 277, SHORT = 278, INT_KEYWORD = 279, CONST_KEYWORD = 280,
VOLATILE_KEYWORD = 281, DOUBLE_KEYWORD = 282, BOOL = 283, ELLIPSIS = 284,
RESTRICT = 285, VOID = 286, FLOAT_KEYWORD = 287, CHAR = 288,
WCHAR_T = 289, ASSIGN_MODIFY = 290, TRUEKEYWORD = 291, FALSEKEYWORD = 292,
DEMANGLER_SPECIAL = 293, CONSTRUCTION_VTABLE = 294, CONSTRUCTION_IN = 295, OROR = 296,
ANDAND = 297, NOTEQUAL = 298, EQUAL = 299, GEQ = 300,
LEQ = 301, RSH = 302, LSH = 303, DECREMENT = 304,
INCREMENT = 305, UNARY = 306, ARROW = 307, INT = 258,
FLOAT = 259, STRING_LITERAL = 260, BOOLEAN_LITERAL = 261, NAME = 262,
TYPENAME = 263, NAME_OR_INT = 264, SIZEOF = 265, ERROR = 266,
INT_KEYWORD = 267, INT_S2_KEYWORD = 268, LOGICAL_S1_KEYWORD = 269, LOGICAL_S2_KEYWORD = 270,
LOGICAL_S8_KEYWORD = 271, LOGICAL_KEYWORD = 272, REAL_KEYWORD = 273, REAL_S8_KEYWORD = 274,
REAL_S16_KEYWORD = 275, COMPLEX_S8_KEYWORD = 276, COMPLEX_S16_KEYWORD = 277, COMPLEX_S32_KEYWORD = 278,
BOOL_AND = 279, BOOL_OR = 280, BOOL_NOT = 281, CHARACTER = 282,
VARIABLE = 283, ASSIGN_MODIFY = 284, ABOVE_COMMA = 285, NOTEQUAL = 286,
EQUAL = 287, GEQ = 288, LEQ = 289, GREATERTHAN = 290,
LESSTHAN = 291, RSH = 292, LSH = 293, STARSTAR = 294,
UNARY = 295, INT = 258, FLOAT = 259, RAW_STRING = 260,
STRING = 261, CHAR = 262, NAME = 263, TYPENAME = 264,
COMPLETE = 265, NAME_OR_INT = 266, TRUE_KEYWORD = 267, FALSE_KEYWORD = 268,
STRUCT_KEYWORD = 269, INTERFACE_KEYWORD = 270, TYPE_KEYWORD = 271, CHAN_KEYWORD = 272,
SIZEOF_KEYWORD = 273, LEN_KEYWORD = 274, CAP_KEYWORD = 275, NEW_KEYWORD = 276,
IOTA_KEYWORD = 277, NIL_KEYWORD = 278, CONST_KEYWORD = 279, DOTDOTDOT = 280,
ENTRY = 281, ERROR = 282, BYTE_KEYWORD = 283, DOLLAR_VARIABLE = 284,
ASSIGN_MODIFY = 285, ABOVE_COMMA = 286, OROR = 287, ANDAND = 288,
ANDNOT = 289, NOTEQUAL = 290, EQUAL = 291, GEQ = 292,
LEQ = 293, RSH = 294, LSH = 295, DECREMENT = 296,
INCREMENT = 297, UNARY = 298, LEFT_ARROW = 299, INTEGER_LITERAL = 258,
FLOATING_POINT_LITERAL = 259, IDENTIFIER = 260, STRING_LITERAL = 261, BOOLEAN_LITERAL = 262,
TYPENAME = 263, NAME_OR_INT = 264, ERROR = 265, LONG = 266,
SHORT = 267, BYTE = 268, INT = 269, CHAR = 270,
BOOLEAN = 271, DOUBLE = 272, FLOAT = 273, VARIABLE = 274,
ASSIGN_MODIFY = 275, SUPER = 276, NEW = 277, OROR = 278,
ANDAND = 279, NOTEQUAL = 280, EQUAL = 281, GEQ = 282,
LEQ = 283, RSH = 284, LSH = 285, DECREMENT = 286,
INCREMENT = 287, INT = 258, HEX = 259, ERROR = 260,
UINT = 261, M2_TRUE = 262, M2_FALSE = 263, CHAR = 264,
FLOAT = 265, STRING = 266, NAME = 267, BLOCKNAME = 268,
IDENT = 269, VARNAME = 270, TYPENAME = 271, SIZE = 272,
CAP = 273, ORD = 274, HIGH = 275, ABS = 276,
MIN_FUNC = 277, MAX_FUNC = 278, FLOAT_FUNC = 279, VAL = 280,
CHR = 281, ODD = 282, TRUNC = 283, TSIZE = 284,
INC = 285, DEC = 286, INCL = 287, EXCL = 288,
COLONCOLON = 289, INTERNAL_VAR = 290, ABOVE_COMMA = 291, ASSIGN = 292,
IN = 293, NOTEQUAL = 294, GEQ = 295, LEQ = 296,
OROR = 297, LOGICAL_AND = 298, MOD = 299, DIV = 300,
UNARY = 301, DOT = 302, NOT = 303, QID = 304,
INT = 258, FLOAT = 259, STRING = 260, FIELDNAME = 261,
COMPLETE = 262, NAME = 263, TYPENAME = 264, NAME_OR_INT = 265,
STRUCT = 266, CLASS = 267, SIZEOF = 268, COLONCOLON = 269,
ERROR = 270, VARIABLE = 271, THIS = 272, TRUEKEYWORD = 273,
FALSEKEYWORD = 274, ABOVE_COMMA = 275, ASSIGN = 276, NOT = 277,
OR = 278, XOR = 279, ANDAND = 280, NOTEQUAL = 281,
GEQ = 282, LEQ = 283, MOD = 284, DIV = 285,
RSH = 286, LSH = 287, DECREMENT = 288, INCREMENT = 289,
UNARY = 290, ARROW = 291, BLOCKNAME = 292
}
Functions
int yyparse (void)
static int yylex (void)
void yyerror (char *)
static char * uptok (char *, int)
static int parse_number (const char *, int, int, YYSTYPE *)
static void push_current_type (void)
static void pop_current_type (void)
static void yy_symbol_value_print (FILE *yyoutput, int yytype, YYSTYPE const *const yyvaluep)
static void yy_symbol_print (FILE *yyoutput, int yytype, YYSTYPE const *const yyvaluep)
static void yy_stack_print (yytype_int16 *yybottom, yytype_int16 *yytop)
static void yy_reduce_print (YYSTYPE *yyvsp, int yyrule)
static void yydestruct (char *yymsg, int yytype, YYSTYPE *yyvaluep) const
Variables
static struct type * current_type
static struct internalvar * intvar
static int leftdiv_is_integer
static int search_field
static const yytype_uint8 yytranslate []
static const yytype_uint8 yyprhs []
static const yytype_int8 yyrhs []
static const yytype_uint16 yyrline []
static const char *const yytname []
static const yytype_uint8 yyr1 []
static const yytype_uint8 yyr2 []
static const yytype_uint8 yydefact []
static const yytype_int8 yydefgoto []
static const yytype_int16 yypact []
static const yytype_int8 yypgoto []
static const yytype_int8 yytable []
static const yytype_int8 yycheck []
static const yytype_uint8 yystos []
int yydebug
int yychar
YYSTYPE yylval
int yynerrs
static struct type_push * tp_top = NULL
static struct token tokentab3 []
static struct token tokentab2 []
static int last_was_structop
Define Documentation
#define ABOVE_COMMA 275
Definition at line 240 of file p-exp.c.
#define ANDAND 280
Definition at line 245 of file p-exp.c.
#define ARROW 291
Definition at line 256 of file p-exp.c.
#define ASSIGN 276
Definition at line 241 of file p-exp.c.
#define BLOCKNAME 292
Definition at line 257 of file p-exp.c.
#define CLASS 267
Definition at line 232 of file p-exp.c.
#define COLONCOLON 269
Definition at line 234 of file p-exp.c.
#define COMPLETE 262
Definition at line 227 of file p-exp.c.
#define DECREMENT 288
Definition at line 253 of file p-exp.c.
#define DIV 285
Definition at line 250 of file p-exp.c.
#define ERROR 270
Definition at line 235 of file p-exp.c.
#define FALSEKEYWORD 274
Definition at line 239 of file p-exp.c.
#define FIELDNAME 261
Definition at line 226 of file p-exp.c.
Referenced by yylex().
#define FLOAT 259
Definition at line 224 of file p-exp.c.
#define GEQ 282
Definition at line 247 of file p-exp.c.
#define INCREMENT 289
Definition at line 254 of file p-exp.c.
#define INT 258
Definition at line 223 of file p-exp.c.
#define LEQ 283
Definition at line 248 of file p-exp.c.
#define LSH 287
Definition at line 252 of file p-exp.c.
#define MOD 284
Definition at line 249 of file p-exp.c.
#define NAME 263
Definition at line 228 of file p-exp.c.
#define NAME_OR_INT 265
Definition at line 230 of file p-exp.c.
#define NOT 277
Definition at line 242 of file p-exp.c.
#define NOTEQUAL 281
Definition at line 246 of file p-exp.c.
#define OR 278
Definition at line 243 of file p-exp.c.
#define parse_type builtin_type (parse_gdbarch)
Definition at line 86 of file p-exp.c.
Referenced by parse_number(), and yylex().
#define RSH 286
Definition at line 251 of file p-exp.c.
#define SIZEOF 268
Definition at line 233 of file p-exp.c.
#define STRING 260
Definition at line 225 of file p-exp.c.
#define STRUCT 266
Definition at line 231 of file p-exp.c.
#define THIS 272
Definition at line 237 of file p-exp.c.
Referenced by yylex().
#define TRUEKEYWORD 273
Definition at line 238 of file p-exp.c.
#define TYPENAME 264
Definition at line 229 of file p-exp.c.
#define UNARY 290
Definition at line 255 of file p-exp.c.
#define VARIABLE 271
Definition at line 236 of file p-exp.c.
#define XOR 279
Definition at line 244 of file p-exp.c.
#define YY_ (msgid) msgid
Definition at line 376 of file p-exp.c.
#define YY_LOCATION_PRINT (File, Loc) ((void) 0)
Definition at line 953 of file p-exp.c.
#define YY_REDUCE_PRINT (Rule)
Value:
do {                                    \
  if (yydebug)                          \
    yy_reduce_print (yyvsp, Rule); \
} while (YYID (0))
Definition at line 1112 of file p-exp.c.
#define YY_STACK_PRINT (Bottom, Top)
Value:
do {                                                            \
  if (yydebug)                                                  \
    yy_stack_print ((Bottom), (Top));                           \
} while (YYID (0))
Definition at line 1074 of file p-exp.c.
#define YY_SYMBOL_PRINT (Title, Type, Value, Location)
Value:
do {                                                                      \
  if (yydebug)                                                            \
    {                                                                     \
      YYFPRINTF (stderr, "%s ", Title);                                   \
      yy_symbol_print (stderr,                                            \
                  Type, Value); \
      YYFPRINTF (stderr, "\n");                                           \
    }                                                                     \
} while (YYID (0))
Definition at line 979 of file p-exp.c.
Referenced by yydestruct().
#define yy_yys pascal_yys
Definition at line 115 of file p-exp.c.
#define yy_yyv pascal_yyv
Definition at line 119 of file p-exp.c.
#define YYABORT goto yyabortlab
Definition at line 882 of file p-exp.c.
#define YYACCEPT goto yyacceptlab
Definition at line 881 of file p-exp.c.
#define yyact pascal_act
Definition at line 108 of file p-exp.c.
#define YYBACKUP (Token, Value)
Value:
do                                                              \
  if (yychar == YYEMPTY && yylen == 1)                          \
    {                                                           \
      yychar = (Token);                                         \
      yylval = (Value);                                         \
      YYPOPSTACK (1);                                           \
      goto yybackup;                                            \
    }                                                           \
  else                                                          \
    {                                                           \
      yyerror (YY_("syntax error: cannot back up")); \
      YYERROR;                                                  \
    }                                                           \
while (YYID (0))
Definition at line 903 of file p-exp.c.
#define YYBISON 1
Definition at line 44 of file p-exp.c.
#define YYBISON_VERSION "2.5"
Definition at line 47 of file p-exp.c.
#define yychar pascal_char
Definition at line 100 of file p-exp.c.
#define yycheck pascal_yycheck
Definition at line 134 of file p-exp.c.
#define yychk pascal_chk
Definition at line 106 of file p-exp.c.
#define yyclearin (yychar = YYEMPTY)
Definition at line 877 of file p-exp.c.
#define YYCOPY (To, From, Count)
Value:
do                                      \
        {                                       \
          YYSIZE_T yyi;                         \
          for (yyi = 0; yyi < (Count); yyi++)   \
            (To)[yyi] = (From)[yyi];            \
        }                                       \
      while (YYID (0))
Definition at line 522 of file p-exp.c.
#define YYCOPY_NEEDED 1
Definition at line 494 of file p-exp.c.
#define yydebug pascal_debug
Definition at line 101 of file p-exp.c.
#define YYDEBUG 1 /* Default to yydebug support */
Definition at line 143 of file p-exp.c.
#define yydef pascal_def
Definition at line 105 of file p-exp.c.
#define yydefred pascal_yydefred
Definition at line 128 of file p-exp.c.
#define yydgoto pascal_yydgoto
Definition at line 129 of file p-exp.c.
#define YYDPRINTF (Args)
Value:
do {                                            \
  if (yydebug)                                  \
    YYFPRINTF Args;                             \
} while (YYID (0))
Definition at line 973 of file p-exp.c.
#define YYEMPTY (-2)
Definition at line 878 of file p-exp.c.
#define YYEOF 0
Definition at line 879 of file p-exp.c.
#define YYERRCODE 256
Definition at line 921 of file p-exp.c.
#define yyerrflag pascal_errflag
Definition at line 110 of file p-exp.c.
#define yyerrok (yyerrstatus = 0)
Definition at line 876 of file p-exp.c.
#define yyerror pascal_error
Definition at line 98 of file p-exp.c.
#define YYERROR goto yyerrorlab
Definition at line 883 of file p-exp.c.
#define YYERROR_VERBOSE 0
Definition at line 170 of file p-exp.c.
#define yyexca pascal_exca
Definition at line 109 of file p-exp.c.
#define YYFAIL goto yyerrlab
Definition at line 893 of file p-exp.c.
#define YYFINAL 3
Definition at line 535 of file p-exp.c.
#define YYFPRINTF parser_fprintf
Definition at line 146 of file p-exp.c.
Referenced by yy_reduce_print(), yy_stack_print(), and yy_symbol_print().
#define YYFREE xfree
Definition at line 464 of file p-exp.c.
#define yygindex pascal_yygindex
Definition at line 132 of file p-exp.c.
#define YYID (n) (n)
Definition at line 389 of file p-exp.c.
#define YYINITDEPTH 200
Definition at line 1131 of file p-exp.c.
#define YYLAST 382
Definition at line 537 of file p-exp.c.
#define yylen pascal_yylen
Definition at line 127 of file p-exp.c.
#define yylex pascal_lex
Definition at line 97 of file p-exp.c.
#define YYLEX yylex ()
Definition at line 962 of file p-exp.c.
#define yylhs pascal_yylhs
Definition at line 126 of file p-exp.c.
#define yylloc pascal_lloc
Definition at line 121 of file p-exp.c.
#define YYLLOC_DEFAULT (Current, Rhs, N)
Value:
do                                                                      \
      if (YYID (N))                                                    \
        {                                                               \
          (Current).first_line   = YYRHSLOC (Rhs, 1).first_line;        \
          (Current).first_column = YYRHSLOC (Rhs, 1).first_column;      \
          (Current).last_line    = YYRHSLOC (Rhs, N).last_line;         \
          (Current).last_column  = YYRHSLOC (Rhs, N).last_column;       \
        }                                                               \
      else                                                              \
        {                                                               \
          (Current).first_line   = (Current).last_line   =              \
            YYRHSLOC (Rhs, 0).last_line;                                \
          (Current).first_column = (Current).last_column =              \
            YYRHSLOC (Rhs, 0).last_column;                              \
        }                                                               \
    while (YYID (0))
Definition at line 930 of file p-exp.c.
#define YYLSP_NEEDED 0
Definition at line 62 of file p-exp.c.
#define yylval pascal_lval
Definition at line 99 of file p-exp.c.
#define YYMALLOC xmalloc
Definition at line 457 of file p-exp.c.
#define yymaxdepth pascal_maxdepth
Definition at line 95 of file p-exp.c.
#define YYMAXDEPTH 10000
Definition at line 1142 of file p-exp.c.
#define YYMAXUTOK 292
Definition at line 550 of file p-exp.c.
#define yyname pascal_name /* With YYDEBUG defined */
Definition at line 124 of file p-exp.c.
#define yynerrs pascal_nerrs
Definition at line 111 of file p-exp.c.
#define YYNNTS 20
Definition at line 542 of file p-exp.c.
#define YYNRULES 76
Definition at line 544 of file p-exp.c.
#define YYNSTATES 125
Definition at line 546 of file p-exp.c.
#define YYNTOKENS 53
Definition at line 540 of file p-exp.c.
Referenced by yy_symbol_print(), and yy_symbol_value_print().
#define yypact pascal_pact
Definition at line 102 of file p-exp.c.
#define YYPACT_NINF -43
Definition at line 736 of file p-exp.c.
#define yypact_value_is_default (yystate) ((yystate) == (-43))
Definition at line 808 of file p-exp.c.
#define yyparse pascal_parse
Definition at line 96 of file p-exp.c.
#define yypgo pascal_pgo
Definition at line 107 of file p-exp.c.
#define YYPOPSTACK (N) (yyvsp -= (N), yyssp -= (N))
#define yyps pascal_ps
Definition at line 112 of file p-exp.c.
#define YYPULL 1
Definition at line 59 of file p-exp.c.
#define YYPURE 0
Definition at line 53 of file p-exp.c.
#define YYPUSH 0
Definition at line 56 of file p-exp.c.
#define yypv pascal_pv
Definition at line 113 of file p-exp.c.
#define yyr1 pascal_r1
Definition at line 103 of file p-exp.c.
#define yyr2 pascal_r2
Definition at line 104 of file p-exp.c.
#define YYRECOVERING () (!!yyerrstatus)
Definition at line 901 of file p-exp.c.
#define yyreds pascal_reds /* With YYDEBUG defined */
Definition at line 122 of file p-exp.c.
#define YYRHSLOC (Rhs, K) ((Rhs)[K])
Definition at line 928 of file p-exp.c.
#define yyrindex pascal_yyrindex
Definition at line 131 of file p-exp.c.
#define yyrule pascal_rule /* With YYDEBUG defined */
Definition at line 125 of file p-exp.c.
Referenced by yy_reduce_print().
#define yys pascal_s
Definition at line 114 of file p-exp.c.
#define yysindex pascal_yysindex
Definition at line 130 of file p-exp.c.
#define YYSIZE_MAXIMUM ((YYSIZE_T) -1)
Definition at line 366 of file p-exp.c.
#define YYSIZE_T unsigned int
Definition at line 362 of file p-exp.c.
#define YYSKELETON_NAME "yacc.c"
Definition at line 50 of file p-exp.c.
#define yyss pascal_yyss
Definition at line 135 of file p-exp.c.
#define yysslim pascal_yysslim
Definition at line 136 of file p-exp.c.
#define yyssp pascal_yyssp
Definition at line 137 of file p-exp.c.
#define YYSTACK_ALLOC YYMALLOC
Definition at line 443 of file p-exp.c.
#define YYSTACK_ALLOC_MAXIMUM YYSIZE_MAXIMUM
Definition at line 446 of file p-exp.c.
#define YYSTACK_BYTES (N)
Value:
((N) * (sizeof (yytype_int16) + sizeof (YYSTYPE)) \
      + YYSTACK_GAP_MAXIMUM)
Definition at line 490 of file p-exp.c.
#define YYSTACK_FREE YYFREE
Definition at line 444 of file p-exp.c.
#define YYSTACK_GAP_MAXIMUM (sizeof (union yyalloc) - 1)
Definition at line 486 of file p-exp.c.
#define YYSTACK_RELOCATE (Stack_alloc, Stack)
Value:
do                                                                      \
      {                                                                 \
        YYSIZE_T yynewbytes;                                            \
        YYCOPY (&yyptr->Stack_alloc, Stack, yysize);                    \
        Stack = &yyptr->Stack_alloc;                                    \
        yynewbytes = yystacksize * sizeof (*Stack) + YYSTACK_GAP_MAXIMUM; \
        yyptr += yynewbytes / sizeof (*yyptr);                          \
      }                                                                 \
    while (YYID (0))
Definition at line 501 of file p-exp.c.
#define yystacksize pascal_yystacksize
Definition at line 138 of file p-exp.c.
#define yystate pascal_state
Definition at line 116 of file p-exp.c.
#define yystype YYSTYPE /* obsolescent; will be withdrawn */
Definition at line 297 of file p-exp.c.
#define YYSTYPE_IS_DECLARED 1
Definition at line 298 of file p-exp.c.
#define YYSTYPE_IS_TRIVIAL 1
Definition at line 296 of file p-exp.c.
#define yytable pascal_yytable
Definition at line 133 of file p-exp.c.
#define YYTABLE_NINF -60
Definition at line 764 of file p-exp.c.
#define yytable_value_is_error (yytable_value) YYID (0)
Definition at line 811 of file p-exp.c.
#define YYTERROR 1
Definition at line 920 of file p-exp.c.
#define yytmp pascal_tmp
Definition at line 117 of file p-exp.c.
#define YYTOKEN_TABLE 0
Definition at line 175 of file p-exp.c.
#define YYTOKENTYPE
Definition at line 181 of file p-exp.c.
#define yytoks pascal_toks /* With YYDEBUG defined */
Definition at line 123 of file p-exp.c.
#define YYTRANSLATE (YYX) ((unsigned int) (YYX) <= YYMAXUTOK ? yytranslate[YYX] : YYUNDEFTOK)
Definition at line 552 of file p-exp.c.
#define YYUNDEFTOK 2
Definition at line 549 of file p-exp.c.
#define YYUSE (e) ((void) (e))
Definition at line 382 of file p-exp.c.
Referenced by yy_symbol_value_print(), and yydestruct().
#define yyv pascal_v
Definition at line 118 of file p-exp.c.
#define yyval pascal_val
Definition at line 120 of file p-exp.c.
#define yyvs pascal_yyvs
Definition at line 139 of file p-exp.c.
#define yyvsp pascal_yyvsp
Definition at line 140 of file p-exp.c.
Typedef Documentation
typedef union YYSTYPE YYSTYPE
typedef short int yytype_int16
Definition at line 349 of file p-exp.c.
typedef short int yytype_int8
Definition at line 337 of file p-exp.c.
typedef unsigned short int yytype_uint16
Definition at line 343 of file p-exp.c.
typedef unsigned char yytype_uint8
Definition at line 328 of file p-exp.c.
Enumeration Type Documentation
enum yytokentype
Enumerator:
INT
NULL_PTR
CHARLIT
FLOAT
TRUEKEYWORD
FALSEKEYWORD
COLONCOLON
STRING
NAME
DOT_ID
DOT_ALL
SPECIAL_VARIABLE
ASSIGN
ELSE
THEN
XOR
OR
_AND_
DOTDOT
IN
GEQ
LEQ
NOTEQUAL
UNARY
REM
MOD
NOT
ABS
STARSTAR
VAR
ARROW
TICK_LENGTH
TICK_LAST
TICK_FIRST
TICK_ADDRESS
TICK_ACCESS
TICK_MODULUS
TICK_MIN
TICK_MAX
TICK_VAL
TICK_TAG
TICK_SIZE
TICK_RANGE
TICK_POS
NEW
OTHERS
INT
FLOAT
DECFLOAT
STRING
NSSTRING
SELECTOR
CHAR
NAME
UNKNOWN_CPP_NAME
COMPLETE
TYPENAME
CLASSNAME
OBJC_LBRAC
NAME_OR_INT
OPERATOR
STRUCT
CLASS
UNION
ENUM
SIZEOF
UNSIGNED
COLONCOLON
TEMPLATE
ERROR
NEW
DELETE
REINTERPRET_CAST
DYNAMIC_CAST
STATIC_CAST
CONST_CAST
ENTRY
TYPEOF
DECLTYPE
TYPEID
SIGNED_KEYWORD
LONG
SHORT
INT_KEYWORD
CONST_KEYWORD
VOLATILE_KEYWORD
DOUBLE_KEYWORD
VARIABLE
ASSIGN_MODIFY
TRUEKEYWORD
FALSEKEYWORD
ABOVE_COMMA
OROR
ANDAND
NOTEQUAL
EQUAL
GEQ
LEQ
RSH
LSH
DECREMENT
INCREMENT
UNARY
DOT_STAR
ARROW_STAR
ARROW
BLOCKNAME
FILENAME
DOTDOTDOT
INT
FLOAT
NAME
STRUCT
CLASS
UNION
ENUM
SIZEOF
UNSIGNED
COLONCOLON
TEMPLATE
ERROR
NEW
DELETE
OPERATOR
STATIC_CAST
REINTERPRET_CAST
DYNAMIC_CAST
SIGNED_KEYWORD
LONG
SHORT
INT_KEYWORD
CONST_KEYWORD
VOLATILE_KEYWORD
DOUBLE_KEYWORD
BOOL
ELLIPSIS
RESTRICT
VOID
FLOAT_KEYWORD
CHAR
WCHAR_T
ASSIGN_MODIFY
TRUEKEYWORD
FALSEKEYWORD
DEMANGLER_SPECIAL
CONSTRUCTION_VTABLE
CONSTRUCTION_IN
OROR
ANDAND
NOTEQUAL
EQUAL
GEQ
LEQ
RSH
LSH
DECREMENT
INCREMENT
UNARY
ARROW
INT
FLOAT
STRING_LITERAL
BOOLEAN_LITERAL
NAME
TYPENAME
NAME_OR_INT
SIZEOF
ERROR
INT_KEYWORD
INT_S2_KEYWORD
LOGICAL_S1_KEYWORD
LOGICAL_S2_KEYWORD
LOGICAL_S8_KEYWORD
LOGICAL_KEYWORD
REAL_KEYWORD
REAL_S8_KEYWORD
REAL_S16_KEYWORD
COMPLEX_S8_KEYWORD
COMPLEX_S16_KEYWORD
COMPLEX_S32_KEYWORD
BOOL_AND
BOOL_OR
BOOL_NOT
CHARACTER
VARIABLE
ASSIGN_MODIFY
ABOVE_COMMA
NOTEQUAL
EQUAL
GEQ
LEQ
GREATERTHAN
LESSTHAN
RSH
LSH
STARSTAR
UNARY
INT
FLOAT
RAW_STRING
STRING
CHAR
NAME
TYPENAME
COMPLETE
NAME_OR_INT
TRUE_KEYWORD
FALSE_KEYWORD
STRUCT_KEYWORD
INTERFACE_KEYWORD
TYPE_KEYWORD
CHAN_KEYWORD
SIZEOF_KEYWORD
LEN_KEYWORD
CAP_KEYWORD
NEW_KEYWORD
IOTA_KEYWORD
NIL_KEYWORD
CONST_KEYWORD
DOTDOTDOT
ENTRY
ERROR
BYTE_KEYWORD
DOLLAR_VARIABLE
ASSIGN_MODIFY
ABOVE_COMMA
OROR
ANDAND
ANDNOT
NOTEQUAL
EQUAL
GEQ
LEQ
RSH
LSH
DECREMENT
INCREMENT
UNARY
LEFT_ARROW
INTEGER_LITERAL
FLOATING_POINT_LITERAL
IDENTIFIER
STRING_LITERAL
BOOLEAN_LITERAL
TYPENAME
NAME_OR_INT
ERROR
LONG
SHORT
BYTE
INT
CHAR
BOOLEAN
DOUBLE
FLOAT
VARIABLE
ASSIGN_MODIFY
SUPER
NEW
OROR
ANDAND
NOTEQUAL
EQUAL
GEQ
LEQ
RSH
LSH
DECREMENT
INCREMENT
INT
HEX
ERROR
UINT
M2_TRUE
M2_FALSE
CHAR
FLOAT
STRING
NAME
BLOCKNAME
IDENT
VARNAME
TYPENAME
SIZE
CAP
ORD
HIGH
ABS
MIN_FUNC
MAX_FUNC
FLOAT_FUNC
VAL
CHR
ODD
TRUNC
TSIZE
INC
DEC
INCL
EXCL
COLONCOLON
INTERNAL_VAR
ABOVE_COMMA
ASSIGN
IN
NOTEQUAL
GEQ
LEQ
OROR
LOGICAL_AND
MOD
DIV
UNARY
DOT
NOT
QID
INT
FLOAT
STRING
FIELDNAME
COMPLETE
NAME
TYPENAME
NAME_OR_INT
STRUCT
CLASS
SIZEOF
COLONCOLON
ERROR
VARIABLE
THIS
TRUEKEYWORD
FALSEKEYWORD
ABOVE_COMMA
ASSIGN
NOT
OR
XOR
ANDAND
NOTEQUAL
GEQ
LEQ
MOD
DIV
RSH
LSH
DECREMENT
INCREMENT
UNARY
ARROW
BLOCKNAME
Definition at line 184 of file p-exp.c.
Function Documentation
static int parse_number (const char * p, int len, int parsed_float, YYSTYPE * putithere) [static]
Definition at line 2733 of file p-exp.c.
References _, YYSTYPE::dval, ERROR, error(), FLOAT, gdbarch_int_bit(), gdbarch_long_bit(), gdbarch_long_long_bit(), HOST_CHAR_BIT, input_radix, INT, LONGEST, parse_c_float(), parse_gdbarch, parse_type, YYSTYPE::type, YYSTYPE::typed_val_float, YYSTYPE::typed_val_int, ULONGEST, and YYSTYPE::val.
Referenced by yylex().
static void pop_current_type (void) [static]
Definition at line 2936 of file p-exp.c.
References type_push::next, type_push::stored, tp_top, and xfree().
static void push_current_type (void) [static]
Definition at line 2925 of file p-exp.c.
References current_type, type_push::next, type_push::stored, tp_top, and xmalloc().
static char * uptok (char * tokstart, int namelen) [static]
Definition at line 2979 of file p-exp.c.
References xmalloc().
Referenced by yylex().
static void yy_reduce_print (YYSTYPE * yyvsp, int yyrule) [static]
Definition at line 1091 of file p-exp.c.
References yy_symbol_print(), YYFPRINTF, and yyrule.
static void yy_stack_print (yytype_int16 * yybottom, yytype_int16 * yytop) [static]
Definition at line 1060 of file p-exp.c.
References YYFPRINTF.
static void yy_symbol_print (FILE * yyoutput, int yytype, YYSTYPE const * const yyvaluep) [static]
Definition at line 1034 of file p-exp.c.
References yy_symbol_value_print(), YYFPRINTF, and YYNTOKENS.
Referenced by yy_reduce_print().
static void yy_symbol_value_print (FILE * yyoutput, int yytype, YYSTYPE const * const yyvaluep) [static]
Definition at line 1002 of file p-exp.c.
References YYNTOKENS, YYPRINT, and YYUSE.
Referenced by yy_symbol_print().
static void yydestruct (char * yymsg, int yytype, YYSTYPE * yyvaluep) const [static]
Definition at line 1395 of file p-exp.c.
References YY_SYMBOL_PRINT, and YYUSE.
void yyerror (char * msg)
static int yylex (void) [static]
Definition at line 3002 of file p-exp.c.
References _, BLOCKNAME, CLASS, comma_terminates, COMPLETE, copy_name(), ERROR, error(), expression_context_block, FALSEKEYWORD, FIELDNAME, input_radix, INT, symtoken::is_a_field_of_this, language_lookup_primitive_type_by_name(), last_was_structop, stoken::length, lexptr, LOC_BLOCK, LOC_TYPEDEF, lookup_only_internalvar(), lookup_struct_elt_type(), lookup_symbol(), lookup_symtab(), YYSTYPE::lval, memcpy(), NAME, NAME_OR_INT, YYSTYPE::opcode, token::opcode, p, paren_depth, parse_completion, parse_escape(), parse_gdbarch, parse_language, parse_number(), parse_type, prev_lexptr, stoken::ptr, search_field, SIZEOF, skip_quoted(), YYSTYPE::ssym, STRING, STRUCT, YYSTYPE::sval, symtoken::sym, SYMBOL_CLASS, SYMBOL_TYPE, tempbuf, tempbufindex, tempbufsize, THIS, token::token, tokentab2, tokentab3, TRUEKEYWORD, YYSTYPE::tsym, ttype::type, YYSTYPE::type, field_of_this_result::type, YYSTYPE::typed_val_int, TYPENAME, uptok(), YYSTYPE::val, VAR_DOMAIN, VARIABLE, write_dollar_variable(), xfree(), and xrealloc().
int yyparse (void)
Variable Documentation
struct type* current_type [static]
Definition at line 310 of file p-exp.c.
Referenced by push_current_type().
struct internalvar* intvar [static]
Definition at line 311 of file p-exp.c.
Referenced by init_if_undefined_command().
int last_was_structop [static]
Definition at line 2997 of file p-exp.c.
Referenced by yylex().
int leftdiv_is_integer [static]
Definition at line 312 of file p-exp.c.
int search_field [static]
Definition at line 315 of file p-exp.c.
Referenced by yylex().
struct token tokentab2[] [static]
Initial value:
  {
    {"or", OR, BINOP_END},
    {"<>", NOTEQUAL, BINOP_END},
    {"<=", LEQ, BINOP_END},
    {">=", GEQ, BINOP_END},
    {":=", ASSIGN, BINOP_END},
    {"::", COLONCOLON, BINOP_END} }
Definition at line 2967 of file p-exp.c.
Referenced by yylex().
struct token tokentab3[] [static]
Initial value:
  {
    {"shr", RSH, BINOP_END},
    {"shl", LSH, BINOP_END},
    {"and", ANDAND, BINOP_END},
    {"div", DIV, BINOP_END},
    {"not", NOT, BINOP_END},
    {"mod", MOD, BINOP_END},
    {"inc", INCREMENT, BINOP_END},
    {"dec", DECREMENT, BINOP_END},
    {"xor", XOR, BINOP_END}
  }
Definition at line 2954 of file p-exp.c.
Referenced by yylex().
struct type_push* tp_top = NULL [static]
Definition at line 2922 of file p-exp.c.
Referenced by pop_current_type(), and push_current_type().
int yychar
Definition at line 1433 of file p-exp.c.
const yytype_int8 yycheck[] [static]
Definition at line 814 of file p-exp.c.
int yydebug
Definition at line 1120 of file p-exp.c.
const yytype_uint8 yydefact[] [static]
Initial value:
{
       2,     0,     0,     1,    49,    51,    56,    75,    68,    50,
       0,     0,     0,     0,    53,    57,    47,    48,     0,     0,
       0,     0,     0,     0,     0,    76,     3,     5,     4,     7,
       0,     0,    52,    62,    66,     6,    65,    64,    71,    73,
      74,    72,    69,    70,     0,    63,    12,     0,    10,    11,
       0,     0,     0,    67,     0,     0,     0,     0,     0,     0,
       0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
       0,     0,    29,    15,    19,    21,     9,    16,    18,    17,
       0,     0,     0,     0,     0,     0,     0,    27,     8,    46,
      45,    44,    43,    37,    38,    41,    42,    40,    39,    32,
      31,    36,    35,    33,    34,    28,     0,     0,    23,    60,
       0,    61,    55,    54,    14,    13,    30,     0,    24,     0,
      26,    20,     0,    22,    25
}
Definition at line 710 of file p-exp.c.
const yytype_int8 yydefgoto[] [static]
Initial value:
{
      -1,     1,     2,    26,    27,    28,    29,    30,   107,   108,
     119,   106,    31,    32,    33,    34,    47,    36,    42,    37
}
Definition at line 728 of file p-exp.c.
YYSTYPE yylval
Definition at line 1436 of file p-exp.c.
int yynerrs
Definition at line 1439 of file p-exp.c.
const yytype_int16 yypact[] [static]
Initial value:
{
     -43,     8,    89,   -43,   -43,   -43,   -43,   -43,   -43,   -43,
       7,     7,   -40,     7,   -43,   -43,   -43,   -43,    89,    89,
      89,   -27,   -23,    89,    10,    13,   -43,   -43,    14,   230,
       4,    21,   -43,   -43,   -43,   -19,    41,   -43,   -43,   -43,
     -43,   -43,   -43,   -43,    89,   -43,    36,   -19,    36,    36,
      89,    89,     5,   -43,    89,    89,    89,    89,    89,    89,
      89,    89,    89,    89,    89,    89,    89,    89,    89,    89,
      89,    89,   -43,   -43,   -43,   -43,   -43,   -43,   -43,   -43,
       7,    89,     7,   118,   -42,   146,   174,   -43,   230,   230,
     255,   279,   302,   323,   323,    31,    31,    31,    31,    75,
      75,    75,    75,   333,   333,    36,    89,    89,    89,    44,
     202,   -43,   -43,   -43,   -43,   -43,    36,     9,   230,    11,
     -43,   -43,    89,   -43,   230
}
Definition at line 737 of file p-exp.c.
const yytype_int8 yypgoto[] [static]
Initial value:
{
     -43,   -43,   -43,   -43,   -43,   -20,   -18,   -43,   -43,   -43,
     -43,   -43,   -43,   -43,   -43,   -43,    16,     6,    -7,   -43
}
Definition at line 755 of file p-exp.c.
const yytype_uint8 yyprhs[] [static]
Initial value:
{
       0,     0,     3,     4,     7,     9,    11,    13,    15,    19,
      22,    25,    28,    31,    36,    41,    44,    47,    50,    53,
      54,    60,    61,    67,    68,    70,    74,    79,    83,    87,
      88,    93,    97,   101,   105,   109,   113,   117,   121,   125,
     129,   133,   137,   141,   145,   149,   153,   157,   159,   161,
     163,   165,   167,   169,   171,   176,   181,   183,   185,   187,
     191,   195,   199,   201,   204,   206,   208,   210,   213,   215,
     218,   221,   223,   225,   227,   229,   231
}
Definition at line 593 of file p-exp.c.
const yytype_uint8 yyr1[] [static]
Initial value:
{
       0,    53,    55,    54,    56,    56,    57,    58,    58,    59,
      59,    59,    59,    59,    59,    60,    59,    59,    59,    61,
      59,    62,    59,    63,    63,    63,    59,    59,    59,    64,
      59,    59,    59,    59,    59,    59,    59,    59,    59,    59,
      59,    59,    59,    59,    59,    59,    59,    59,    59,    59,
      59,    59,    59,    59,    59,    59,    59,    59,    65,    65,
      66,    67,    66,    66,    66,    68,    69,    70,    70,    70,
      70,    71,    71,    71,    71,    72,    72
}
Definition at line 682 of file p-exp.c.
const yytype_uint8 yyr2[] [static]
Initial value:
{
       0,     2,     0,     2,     1,     1,     1,     1,     3,     2,
       2,     2,     2,     4,     4,     2,     2,     2,     2,     0,
       5,     0,     5,     0,     1,     3,     4,     3,     3,     0,
       4,     3,     3,     3,     3,     3,     3,     3,     3,     3,
       3,     3,     3,     3,     3,     3,     3,     1,     1,     1,
       1,     1,     1,     1,     4,     4,     1,     1,     1,     3,
       3,     3,     1,     2,     1,     1,     1,     2,     1,     2,
       2,     1,     1,     1,     1,     1,     1
}
Definition at line 695 of file p-exp.c.
const yytype_int8 yyrhs[] [static]
Initial value:
{
      54,     0,    -1,    -1,    55,    56,    -1,    58,    -1,    57,
      -1,    69,    -1,    59,    -1,    58,    20,    59,    -1,    59,
      49,    -1,    37,    59,    -1,    39,    59,    -1,    23,    59,
      -1,    43,    47,    59,    51,    -1,    42,    47,    59,    51,
      -1,    59,    45,    -1,    60,     6,    -1,    60,    71,    -1,
      60,     7,    -1,    -1,    59,    46,    61,    58,    52,    -1,
      -1,    59,    47,    62,    63,    51,    -1,    -1,    59,    -1,
      63,    20,    59,    -1,    69,    47,    59,    51,    -1,    47,
      58,    51,    -1,    59,    40,    59,    -1,    -1,    59,    41,
      64,    59,    -1,    59,    34,    59,    -1,    59,    33,    59,
      -1,    59,    38,    59,    -1,    59,    39,    59,    -1,    59,
      36,    59,    -1,    59,    35,    59,    -1,    59,    27,    59,
      -1,    59,    28,    59,    -1,    59,    32,    59,    -1,    59,
      31,    59,    -1,    59,    29,    59,    -1,    59,    30,    59,
      -1,    59,    26,    59,    -1,    59,    25,    59,    -1,    59,
      24,    59,    -1,    59,    22,    59,    -1,    18,    -1,    19,
      -1,     3,    -1,    10,    -1,     4,    -1,    66,    -1,    16,
      -1,    13,    47,    69,    51,    -1,    13,    47,    59,    51,
      -1,     5,    -1,    17,    -1,    50,    -1,    65,    14,    71,
      -1,    65,    14,    71,    -1,    70,    14,    71,    -1,    67,
      -1,    14,    71,    -1,    72,    -1,    70,    -1,    68,    -1,
      49,    70,    -1,     9,    -1,    11,    71,    -1,    12,    71,
      -1,     8,    -1,    50,    -1,     9,    -1,    10,    -1,     8,
      -1,    50,    -1
}
Definition at line 606 of file p-exp.c.
const yytype_uint16 yyrline[] [static]
Initial value:
{
       0,   241,   241,   241,   250,   251,   254,   261,   262,   267,
     273,   279,   283,   287,   291,   296,   300,   318,   336,   348,
     346,   379,   376,   391,   392,   394,   398,   413,   419,   423,
     423,   443,   447,   451,   455,   459,   463,   467,   473,   479,
     485,   491,   497,   503,   507,   511,   515,   519,   526,   533,
     541,   555,   563,   566,   581,   589,   592,   618,   645,   663,
     673,   688,   703,   704,   735,   806,   817,   821,   823,   825,
     828,   836,   837,   838,   839,   842,   843
}
Definition at line 635 of file p-exp.c.
const yytype_uint8 yystos[] [static]
Initial value:
{
       0,    54,    55,     0,     3,     4,     5,     8,     9,    10,
      11,    12,    13,    14,    16,    17,    18,    19,    23,    37,
      39,    42,    43,    47,    49,    50,    56,    57,    58,    59,
      60,    65,    66,    67,    68,    69,    70,    72,     8,     9,
      10,    50,    71,    71,    47,    71,    59,    69,    59,    59,
      47,    47,    58,    70,    20,    22,    24,    25,    26,    27,
      28,    29,    30,    31,    32,    33,    34,    35,    36,    38,
      39,    40,    41,    45,    46,    47,    49,     6,     7,    71,
      14,    47,    14,    59,    69,    59,    59,    51,    59,    59,
      59,    59,    59,    59,    59,    59,    59,    59,    59,    59,
      59,    59,    59,    59,    59,    59,    64,    61,    62,    71,
      59,    71,    51,    51,    51,    51,    59,    58,    59,    63,
      51,    52,    20,    51,    59
}
Definition at line 859 of file p-exp.c.
const yytype_int8 yytable[] [static]
Definition at line 765 of file p-exp.c.
const char* const yytname[] [static]
Initial value:
{
  "$end", "error", "$undefined", "INT", "FLOAT", "STRING", "FIELDNAME",
  "COMPLETE", "NAME", "TYPENAME", "NAME_OR_INT", "STRUCT", "CLASS",
  "SIZEOF", "COLONCOLON", "ERROR", "VARIABLE", "THIS", "TRUEKEYWORD",
  "FALSEKEYWORD", "','", "ABOVE_COMMA", "ASSIGN", "NOT", "OR", "XOR",
  "ANDAND", "'='", "NOTEQUAL", "'<'", "'>'", "GEQ", "LEQ", "MOD", "DIV",
  "RSH", "LSH", "'@'", "'+'", "'-'", "'*'", "'/'", "DECREMENT",
  "INCREMENT", "UNARY", "'.'", "'['", "'('", "ARROW", "'^'", "BLOCKNAME",
  "')'", "']'", "$accept", "start", "$@1", "normal_start", "type_exp",
  "exp1", "exp", "field_exp", "$@2", "$@3", "arglist", "$@4", "block",
  "variable", "qualified_name", "ptype", "type", "typebase", "name",
  "name_not_typename", 0
}
Definition at line 651 of file p-exp.c.
const yytype_uint8 yytranslate[] [static]
Definition at line 556 of file p-exp.c.