GDB (xrefs): /home/stan/gdb/src/gdb/p-lang.h File Reference
/home/stan/gdb/src/gdb/p-lang.h File Reference
Functions
const char * pascal_main_name (void)
int pascal_parse (void)
void pascal_error (char *)
void pascal_print_type (struct type *, const char *, struct ui_file *, int, int, const struct type_print_options *)
void pascal_print_typedef (struct type *, struct symbol *, struct ui_file *)
void pascal_val_print (struct type *, const gdb_byte *, int, CORE_ADDR, struct ui_file *, int, const struct value *, const struct value_print_options *)
void pascal_value_print (struct value *, struct ui_file *, const struct value_print_options *)
void pascal_type_print_method_args (const char *, const char *, struct ui_file *)
int is_pascal_string_type (struct type *, int *, int *, int *, struct type **, const char **)
void pascal_printchar (int, struct type *, struct ui_file *)
void pascal_printstr (struct ui_file *, struct type *, const gdb_byte *, unsigned int, const char *, int, const struct value_print_options *)
struct type ** const (pascal_builtin_types[])
void pascal_type_print_base (struct type *, struct ui_file *, int, int, const struct type_print_options *)
void pascal_type_print_varspec_prefix (struct type *, struct ui_file *, int, int, const struct type_print_options *)
void pascal_object_print_value_fields (struct type *, const gdb_byte *, int, CORE_ADDR, struct ui_file *, int, const struct value *, const struct value_print_options *, struct type **, int)
int pascal_object_is_vtbl_ptr_type (struct type *)
int pascal_object_is_vtbl_member (struct type *)
Function Documentation
struct type** const (pascal_builtin_types []) [read]
int is_pascal_string_type (struct type * , int * , int * , int * , struct type ** , const char **)
Definition at line 98 of file p-lang.c.
References TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_STRUCT, TYPE_FIELD_BITPOS, TYPE_FIELD_NAME, TYPE_FIELD_TYPE, TYPE_LENGTH, TYPE_NFIELDS, and TYPE_TARGET_TYPE.
Referenced by pascal_val_print().
void pascal_error (char *)
const char* pascal_main_name (void)
Definition at line 59 of file p-lang.c.
References GPC_MAIN_PROGRAM_NAME_1, GPC_MAIN_PROGRAM_NAME_2, GPC_P_INITIALIZE, and lookup_minimal_symbol().
Referenced by find_main_name().
int pascal_object_is_vtbl_member (struct type *)
Definition at line 496 of file p-valprint.c.
References pascal_object_is_vtbl_ptr_type(), TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_PTR, TYPE_CODE_STRUCT, and TYPE_TARGET_TYPE.
Referenced by pascal_val_print().
int pascal_object_is_vtbl_ptr_type (struct type *)
Definition at line 484 of file p-valprint.c.
References pascal_vtbl_ptr_name, and type_name_no_tag().
Referenced by pascal_object_is_vtbl_member(), and pascal_val_print().
void pascal_object_print_value_fields (struct type * , const gdb_byte * , int , CORE_ADDR , struct ui_file * , int , const struct value * , const struct value_print_options * , struct type ** , int)
Definition at line 528 of file p-valprint.c.
References _, annotate_field_begin(), annotate_field_end(), annotate_field_name_end(), annotate_field_value(), CHECK_TYPEDEF, common_val_print(), current_language, value_print_options::deref_ref, dont_print_statmem_obstack, field_is_static(), fprintf_filtered(), fprintf_symbol_filtered(), fputs_filtered(), language_cplus, len, n_spaces(), pascal_object_print_static_field(), pascal_object_print_value(), value_print_options::pascal_static_field_print, value_print_options::prettyformat, print_spaces_filtered(), TYPE_FIELD, TYPE_FIELD_BITPOS, TYPE_FIELD_BITSIZE, TYPE_FIELD_IGNORE, TYPE_FIELD_NAME, TYPE_FIELD_PACKED, TYPE_FIELD_TYPE, TYPE_N_BASECLASSES, type_name_no_tag(), TYPE_NFIELDS, val_print(), val_print_optimized_out(), value_bits_synthetic_pointer(), value_bits_valid(), value_field_bitfield(), and wrap_here().
Referenced by pascal_object_print_static_field(), pascal_object_print_value(), and pascal_val_print().
int pascal_parse (void)
void pascal_print_type (struct type * , const char * , struct ui_file * , int , int , const struct type_print_options *)
Definition at line 50 of file p-typeprint.c.
References CHECK_TYPEDEF, code, fputs_filtered(), pascal_type_print_base(), pascal_type_print_varspec_prefix(), pascal_type_print_varspec_suffix(), strchr(), TYPE_CODE, TYPE_CODE_FUNC, and TYPE_CODE_METHOD.
Referenced by pascal_print_func_args(), and pascal_type_print_base().
void pascal_print_typedef (struct type * , struct symbol * , struct ui_file *)
Definition at line 98 of file p-typeprint.c.
References CHECK_TYPEDEF, fprintf_filtered(), SYMBOL_PRINT_NAME, and type_print().
void pascal_printchar (int , struct type * , struct ui_file *)
Definition at line 203 of file p-lang.c.
References fputs_filtered(), and pascal_one_char().
Referenced by pascal_printstr().
void pascal_printstr (struct ui_file * , struct type * , const gdb_byte * , unsigned int, const char * , int , const struct value_print_options *)
Definition at line 218 of file p-lang.c.
References check_typedef(), extract_unsigned_integer(), fprintf_filtered(), fputs_filtered(), gdbarch_byte_order(), get_type_arch(), pascal_one_char(), pascal_printchar(), PRINT_LITERAL_FORM, value_print_options::print_max, QUIT, value_print_options::repeat_count_threshold, and TYPE_LENGTH.
void pascal_type_print_base (struct type * , struct ui_file * , int , int , const struct type_print_options *)
Definition at line 446 of file p-typeprint.c.
References CHECK_TYPEDEF, field_is_static(), fprintf_filtered(), fprintfi_filtered(), fputs_filtered(), HAVE_CPLUS_STRUCT, cleanup_check::is_constructor(), is_cplus_marker(), cleanup_check::is_destructor(), len, LONGEST, pascal_print_type(), pascal_type_print_base(), pascal_type_print_derivation_info(), pascal_type_print_method_args(), plongest(), print_spaces_filtered(), print_type_scalar(), QUIT, TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_ENUM, TYPE_CODE_ERROR, TYPE_CODE_FUNC, TYPE_CODE_METHOD, TYPE_CODE_PTR, TYPE_CODE_RANGE, TYPE_CODE_REF, TYPE_CODE_SET, TYPE_CODE_STRING, TYPE_CODE_STRUCT, TYPE_CODE_TYPEDEF, TYPE_CODE_UNDEF, TYPE_CODE_UNION, TYPE_CODE_VOID, TYPE_ERROR_NAME, TYPE_FIELD, TYPE_FIELD_BITSIZE, TYPE_FIELD_ENUMVAL, TYPE_FIELD_NAME, TYPE_FIELD_PACKED, TYPE_FIELD_PRIVATE, TYPE_FIELD_PROTECTED, TYPE_FIELD_TYPE, TYPE_FN_FIELD_PHYSNAME, TYPE_FN_FIELD_PRIVATE, TYPE_FN_FIELD_PROTECTED, TYPE_FN_FIELD_STATIC_P, TYPE_FN_FIELD_TYPE, TYPE_FN_FIELD_VIRTUAL_P, TYPE_FN_FIELDLIST1, TYPE_FN_FIELDLIST_LENGTH, TYPE_FN_FIELDLIST_NAME, TYPE_HIGH_BOUND, TYPE_INDEX_TYPE, TYPE_LOW_BOUND, TYPE_N_BASECLASSES, TYPE_NAME, TYPE_NFIELDS, TYPE_NFN_FIELDS, type_print(), TYPE_STUB, TYPE_TAG_NAME, TYPE_TARGET_TYPE, and wrap_here().
Referenced by pascal_print_type(), pascal_type_print_base(), pascal_type_print_varspec_prefix(), and pascal_type_print_varspec_suffix().
void pascal_type_print_method_args (const char * , const char * , struct ui_file *)
Definition at line 156 of file p-typeprint.c.
References fputc_filtered(), fputs_filtered(), cleanup_check::is_constructor(), cleanup_check::is_destructor(), and len.
Referenced by pascal_type_print_base(), and pascal_type_print_varspec_suffix().
void pascal_type_print_varspec_prefix (struct type * , struct ui_file * , int , int , const struct type_print_options *)
Definition at line 208 of file p-typeprint.c.
References _, error(), fprintf_filtered(), pascal_type_print_base(), pascal_type_print_varspec_prefix(), plongest(), QUIT, TYPE_ARRAY_LOWER_BOUND_VALUE, TYPE_ARRAY_UPPER_BOUND_IS_UNDEFINED, TYPE_ARRAY_UPPER_BOUND_VALUE, TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_BOOL, TYPE_CODE_CHAR, TYPE_CODE_COMPLEX, TYPE_CODE_ENUM, TYPE_CODE_ERROR, TYPE_CODE_FLT, TYPE_CODE_FUNC, TYPE_CODE_INT, TYPE_CODE_METHOD, TYPE_CODE_PTR, TYPE_CODE_RANGE, TYPE_CODE_REF, TYPE_CODE_SET, TYPE_CODE_STRING, TYPE_CODE_STRUCT, TYPE_CODE_TYPEDEF, TYPE_CODE_UNDEF, TYPE_CODE_UNION, TYPE_CODE_VOID, TYPE_DOMAIN_TYPE, TYPE_LENGTH, TYPE_NAME, and TYPE_TARGET_TYPE.
Referenced by pascal_print_type(), pascal_type_print_varspec_prefix(), and pascal_type_print_varspec_suffix().
void pascal_val_print (struct type * , const gdb_byte * , int , CORE_ADDR , struct ui_file * , int , const struct value * , const struct value_print_options *)
Definition at line 59 of file p-valprint.c.
References _, value_print_options::addressprint, gdbarch::byte_order, check_typedef(), CHECK_TYPEDEF, common_val_print(), current_language, demangle, error(), extract_unsigned_integer(), value_print_options::format, fprintf_filtered(), fputs_filtered(), gdb_flush(), gdbarch_byte_order(), generic_val_print(), get_array_bounds(), get_discrete_bounds(), get_type_arch(), is_pascal_string_type(), LA_PRINT_STRING, len, LONGEST, lookup_minimal_symbol_by_pc(), lookup_symbol(), bound_minimal_symbol::minsym, paddress(), pascal_object_is_vtbl_member(), pascal_object_is_vtbl_ptr_type(), pascal_object_print_value_fields(), value_print_options::prettyformat, value_print_options::prettyformat_arrays, print_address_demangle(), value_print_options::print_max, print_spaces_filtered(), print_type_scalar(), print_unpacked_pointer(), read_memory(), value_print_options::stop_print_at_null, SYMBOL_LINKAGE_NAME, value_print_options::symbol_print, SYMBOL_PRINT_NAME, SYMBOL_TYPE, SYMBOL_VALUE_ADDRESS, TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_BOOL, TYPE_CODE_CHAR, TYPE_CODE_ENUM, TYPE_CODE_ERROR, TYPE_CODE_FLAGS, TYPE_CODE_FLT, TYPE_CODE_FUNC, TYPE_CODE_INT, TYPE_CODE_PTR, TYPE_CODE_RANGE, TYPE_CODE_REF, TYPE_CODE_SET, TYPE_CODE_STRUCT, TYPE_CODE_UNDEF, TYPE_CODE_UNION, TYPE_CODE_VOID, TYPE_FIELD_BITPOS, TYPE_FIELD_TYPE, TYPE_HIGH_BOUND, TYPE_INDEX_TYPE, TYPE_LENGTH, TYPE_STUB, TYPE_TARGET_TYPE, ULONGEST, value_print_options::unionprint, unpack_pointer(), val_print_array_elements(), val_print_scalar_formatted(), val_print_string(), value_at(), value_bit_index(), VAR_DOMAIN, VTBL_FNADDR_OFFSET, value_print_options::vtblprint, xfree(), and xmalloc().
void pascal_value_print (struct value * , struct ui_file * , const struct value_print_options *)
Definition at line 417 of file p-valprint.c.
References common_val_print(), current_language, value_print_options::deref_ref, fprintf_filtered(), TYPE_CODE, TYPE_CODE_PTR, TYPE_CODE_REF, TYPE_NAME, type_print(), TYPE_TARGET_TYPE, and value_type().