GDB (xrefs): /home/stan/gdb/src/gdb/p-typeprint.c File Reference
/home/stan/gdb/src/gdb/p-typeprint.c File Reference
#include "defs.h"
#include "gdb_obstack.h"
#include "bfd.h"
#include "symtab.h"
#include "gdbtypes.h"
#include "expression.h"
#include "value.h"
#include "gdbcore.h"
#include "target.h"
#include "language.h"
#include "p-lang.h"
#include "typeprint.h"
#include "gdb-demangle.h"
#include "gdb_string.h"
#include <errno.h>
#include <ctype.h>
Functions
static void pascal_type_print_varspec_suffix (struct type *, struct ui_file *, int, int, int, const struct type_print_options *)
static void pascal_type_print_derivation_info (struct ui_file *, struct type *)
void pascal_print_type (struct type *type, const char *varstring, struct ui_file *stream, int show, int level, const struct type_print_options *flags)
void pascal_print_typedef (struct type *type, struct symbol *new_symbol, struct ui_file *stream)
void pascal_type_print_method_args (const char *physname, const char *methodname, struct ui_file *stream)
void pascal_type_print_varspec_prefix (struct type *type, struct ui_file *stream, int show, int passed_a_ptr, const struct type_print_options *flags)
static void pascal_print_func_args (struct type *type, struct ui_file *stream, const struct type_print_options *flags)
void pascal_type_print_base (struct type *type, struct ui_file *stream, int show, int level, const struct type_print_options *flags)
Function Documentation
static void pascal_print_func_args (struct type * type, struct ui_file * stream, const struct type_print_options * flags) [static]
Definition at line 308 of file p-typeprint.c.
References fprintf_filtered(), fputs_filtered(), len, pascal_print_type(), TYPE_FIELD_TYPE, TYPE_NFIELDS, and wrap_here().
Referenced by pascal_type_print_varspec_suffix().
void pascal_print_type (struct type * type, const char * varstring, struct ui_file * stream, int show, int level, const struct type_print_options * flags)
Definition at line 50 of file p-typeprint.c.
References CHECK_TYPEDEF, code, fputs_filtered(), pascal_type_print_base(), pascal_type_print_varspec_prefix(), pascal_type_print_varspec_suffix(), strchr(), TYPE_CODE, TYPE_CODE_FUNC, and TYPE_CODE_METHOD.
Referenced by pascal_print_func_args(), and pascal_type_print_base().
void pascal_print_typedef (struct type * type, struct symbol * new_symbol, struct ui_file * stream)
Definition at line 98 of file p-typeprint.c.
References CHECK_TYPEDEF, fprintf_filtered(), SYMBOL_PRINT_NAME, and type_print().
void pascal_type_print_base (struct type * type, struct ui_file * stream, int show, int level, const struct type_print_options * flags)
Definition at line 446 of file p-typeprint.c.
References CHECK_TYPEDEF, field_is_static(), fprintf_filtered(), fprintfi_filtered(), fputs_filtered(), HAVE_CPLUS_STRUCT, cleanup_check::is_constructor(), is_cplus_marker(), cleanup_check::is_destructor(), len, LONGEST, pascal_print_type(), pascal_type_print_base(), pascal_type_print_derivation_info(), pascal_type_print_method_args(), plongest(), print_spaces_filtered(), print_type_scalar(), QUIT, TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_ENUM, TYPE_CODE_ERROR, TYPE_CODE_FUNC, TYPE_CODE_METHOD, TYPE_CODE_PTR, TYPE_CODE_RANGE, TYPE_CODE_REF, TYPE_CODE_SET, TYPE_CODE_STRING, TYPE_CODE_STRUCT, TYPE_CODE_TYPEDEF, TYPE_CODE_UNDEF, TYPE_CODE_UNION, TYPE_CODE_VOID, TYPE_ERROR_NAME, TYPE_FIELD, TYPE_FIELD_BITSIZE, TYPE_FIELD_ENUMVAL, TYPE_FIELD_NAME, TYPE_FIELD_PACKED, TYPE_FIELD_PRIVATE, TYPE_FIELD_PROTECTED, TYPE_FIELD_TYPE, TYPE_FN_FIELD_PHYSNAME, TYPE_FN_FIELD_PRIVATE, TYPE_FN_FIELD_PROTECTED, TYPE_FN_FIELD_STATIC_P, TYPE_FN_FIELD_TYPE, TYPE_FN_FIELD_VIRTUAL_P, TYPE_FN_FIELDLIST1, TYPE_FN_FIELDLIST_LENGTH, TYPE_FN_FIELDLIST_NAME, TYPE_HIGH_BOUND, TYPE_INDEX_TYPE, TYPE_LOW_BOUND, TYPE_N_BASECLASSES, TYPE_NAME, TYPE_NFIELDS, TYPE_NFN_FIELDS, type_print(), TYPE_STUB, TYPE_TAG_NAME, TYPE_TARGET_TYPE, and wrap_here().
Referenced by pascal_print_type(), pascal_type_print_base(), pascal_type_print_varspec_prefix(), and pascal_type_print_varspec_suffix().
static void pascal_type_print_derivation_info (struct ui_file * stream, struct type * type) [static]
Definition at line 133 of file p-typeprint.c.
References BASETYPE_VIA_PUBLIC, BASETYPE_VIA_VIRTUAL, fprintf_filtered(), fputs_filtered(), name, TYPE_BASECLASS, TYPE_N_BASECLASSES, and type_name_no_tag().
Referenced by pascal_type_print_base().
void pascal_type_print_method_args (const char * physname, const char * methodname, struct ui_file * stream)
Definition at line 156 of file p-typeprint.c.
References fputc_filtered(), fputs_filtered(), cleanup_check::is_constructor(), cleanup_check::is_destructor(), and len.
Referenced by pascal_type_print_base(), and pascal_type_print_varspec_suffix().
void pascal_type_print_varspec_prefix (struct type * type, struct ui_file * stream, int show, int passed_a_ptr, const struct type_print_options * flags)
Definition at line 208 of file p-typeprint.c.
References _, error(), fprintf_filtered(), pascal_type_print_base(), pascal_type_print_varspec_prefix(), plongest(), QUIT, TYPE_ARRAY_LOWER_BOUND_VALUE, TYPE_ARRAY_UPPER_BOUND_IS_UNDEFINED, TYPE_ARRAY_UPPER_BOUND_VALUE, TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_BOOL, TYPE_CODE_CHAR, TYPE_CODE_COMPLEX, TYPE_CODE_ENUM, TYPE_CODE_ERROR, TYPE_CODE_FLT, TYPE_CODE_FUNC, TYPE_CODE_INT, TYPE_CODE_METHOD, TYPE_CODE_PTR, TYPE_CODE_RANGE, TYPE_CODE_REF, TYPE_CODE_SET, TYPE_CODE_STRING, TYPE_CODE_STRUCT, TYPE_CODE_TYPEDEF, TYPE_CODE_UNDEF, TYPE_CODE_UNION, TYPE_CODE_VOID, TYPE_DOMAIN_TYPE, TYPE_LENGTH, TYPE_NAME, and TYPE_TARGET_TYPE.
Referenced by pascal_print_type(), pascal_type_print_varspec_prefix(), and pascal_type_print_varspec_suffix().
static void pascal_type_print_varspec_suffix (struct type * type, struct ui_file * stream, int show, int passed_a_ptr, int demangled_args, const struct type_print_options * flags) [static]
Definition at line 344 of file p-typeprint.c.
References _, error(), fprintf_filtered(), pascal_print_func_args(), pascal_type_print_base(), pascal_type_print_method_args(), pascal_type_print_varspec_prefix(), QUIT, TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_BOOL, TYPE_CODE_CHAR, TYPE_CODE_COMPLEX, TYPE_CODE_ENUM, TYPE_CODE_ERROR, TYPE_CODE_FLT, TYPE_CODE_FUNC, TYPE_CODE_INT, TYPE_CODE_METHOD, TYPE_CODE_PTR, TYPE_CODE_RANGE, TYPE_CODE_REF, TYPE_CODE_SET, TYPE_CODE_STRING, TYPE_CODE_STRUCT, TYPE_CODE_TYPEDEF, TYPE_CODE_UNDEF, TYPE_CODE_UNION, TYPE_CODE_VOID, TYPE_NAME, and TYPE_TARGET_TYPE.
Referenced by pascal_print_type().