GDB (xrefs): /home/stan/gdb/src/gdb/parser-defs.h File Reference
/home/stan/gdb/src/gdb/parser-defs.h File Reference
#include "doublest.h"
#include "vec.h"
#include "expression.h"
Classes
struct stoken
struct typed_stoken
struct stoken_vector
struct ttype
struct symtoken
struct objc_class_str
union type_stack_elt
struct type_stack
struct op_print
struct exp_descriptor
Defines
#define parse_gdbarch (expout->gdbarch)
#define parse_language (expout->language_defn)
Typedefs
typedef struct type * type_ptr
Enumerations
enum type_pieces {
tp_end = -1, tp_pointer, tp_reference, tp_array,
tp_function, tp_function_with_arguments, tp_const, tp_volatile,
tp_space_identifier, tp_type_stack
}
enum precedence {
PREC_NULL, PREC_COMMA, PREC_ABOVE_COMMA, PREC_ASSIGN,
PREC_LOGICAL_OR, PREC_LOGICAL_AND, PREC_BITWISE_IOR, PREC_BITWISE_AND,
PREC_BITWISE_XOR, PREC_EQUAL, PREC_ORDER, PREC_SHIFT,
PREC_ADD, PREC_MUL, PREC_REPEAT, PREC_HYPER,
PREC_PREFIX, PREC_SUFFIX, PREC_BUILTIN_FUNCTION
}
Functions
DEF_VEC_P (type_ptr)
void initialize_expout (int, const struct language_defn *, struct gdbarch *)
void reallocate_expout (void)
int prefixify_expression (struct expression *expr)
void write_exp_elt_opcode (enum exp_opcode)
void write_exp_elt_sym (struct symbol *)
void write_exp_elt_longcst (LONGEST)
void write_exp_elt_dblcst (DOUBLEST)
void write_exp_elt_decfloatcst (gdb_byte *)
void write_exp_elt_type (struct type *)
void write_exp_elt_intern (struct internalvar *)
void write_exp_string (struct stoken)
void write_exp_string_vector (int type, struct stoken_vector *vec)
void write_exp_bitstring (struct stoken)
void write_exp_elt_block (const struct block *)
void write_exp_elt_objfile (struct objfile *objfile)
void write_exp_msymbol (struct bound_minimal_symbol)
void write_dollar_variable (struct stoken str)
void mark_struct_expression (void)
const char * find_template_name_end (const char *)
void start_arglist (void)
int end_arglist (void)
char * copy_name (struct stoken)
void insert_type (enum type_pieces)
void push_type (enum type_pieces)
void push_type_int (int)
void insert_type_address_space (char *)
enum type_pieces pop_type (void)
int pop_type_int (void)
struct type_stack * get_type_stack (void)
struct type_stack * append_type_stack (struct type_stack *to, struct type_stack *from)
void push_type_stack (struct type_stack *stack)
void type_stack_cleanup (void *arg)
void push_typelist (VEC(type_ptr)*typelist)
int length_of_subexp (struct expression *, int)
int dump_subexp (struct expression *, struct ui_file *, int)
int dump_subexp_body_standard (struct expression *, struct ui_file *, int)
void operator_length (const struct expression *, int, int *, int *)
void operator_length_standard (const struct expression *, int, int *, int *)
int operator_check_standard (struct expression *exp, int pos, int(*objfile_func)(struct objfile *objfile, void *data), void *data)
char * op_name_standard (enum exp_opcode)
struct type * follow_types (struct type *)
void null_post_parser (struct expression **, int)
int parse_float (const char *p, int len, DOUBLEST *d, const char **suffix)
int parse_c_float (struct gdbarch *gdbarch, const char *p, int len, DOUBLEST *d, struct type **t)
void print_subexp (struct expression *, int *, struct ui_file *, enum precedence)
void print_subexp_standard (struct expression *, int *, struct ui_file *, enum precedence)
void parser_fprintf (FILE *, const char *,...) ATTRIBUTE_PRINTF(2
void int exp_uses_objfile (struct expression *exp, struct objfile *objfile)
void mark_completion_tag (enum type_code, const char *ptr, int length)
Variables
int parser_debug
struct expression * expout
int expout_size
int expout_ptr
struct block * expression_context_block
CORE_ADDR expression_context_pc
struct block * innermost_block
struct block * block_found
int arglist_len
const char * lexptr
const char * prev_lexptr
int paren_depth
int comma_terminates
struct exp_descriptor exp_descriptor_standard
Define Documentation
#define parse_gdbarch (expout->gdbarch)
Definition at line 38 of file parser-defs.h.
Referenced by classify_name(), end_msglist(), find_primitive_type(), insert_type_address_space(), parse_number(), processInt(), processReal(), type_char(), type_system_address(), write_dollar_variable(), and yylex().
#define parse_language (expout->language_defn)
Definition at line 39 of file parser-defs.h.
Referenced by classify_name(), find_primitive_type(), lex_one_token(), type_char(), type_system_address(), and yylex().
Typedef Documentation
typedef struct type* type_ptr
Definition at line 111 of file parser-defs.h.
Enumeration Type Documentation
enum precedence
Enumerator:
PREC_NULL
PREC_COMMA
PREC_ABOVE_COMMA
PREC_ASSIGN
PREC_LOGICAL_OR
PREC_LOGICAL_AND
PREC_BITWISE_IOR
PREC_BITWISE_AND
PREC_BITWISE_XOR
PREC_EQUAL
PREC_ORDER
PREC_SHIFT
PREC_ADD
PREC_MUL
PREC_REPEAT
PREC_HYPER
PREC_PREFIX
PREC_SUFFIX
PREC_BUILTIN_FUNCTION
Definition at line 289 of file parser-defs.h.
enum type_pieces
Enumerator:
tp_end
tp_pointer
tp_reference
tp_array
tp_function
tp_function_with_arguments
tp_const
tp_volatile
tp_space_identifier
tp_type_stack
Definition at line 116 of file parser-defs.h.
Function Documentation
struct type_stack* append_type_stack (struct type_stack * to, struct type_stack * from) [read]
Definition at line 1573 of file parse.c.
References type_stack::depth, type_stack::elements, memcpy(), to, and type_stack_reserve().
char* copy_name (struct stoken)
Definition at line 808 of file parse.c.
References stoken::length, memcpy(), stoken::ptr, and xrealloc().
Referenced by c_print_token(), classify_inner_name(), classify_name(), classify_packaged_name(), classify_unsafe_function(), java_type_from_name(), lex_one_token(), push_expression_name(), push_qualified_expression_name(), push_variable(), write_dollar_variable(), and yylex().
DEF_VEC_P (type_ptr)
int dump_subexp (struct expression * , struct ui_file * , int)
Definition at line 730 of file expprint.c.
References dump_subexp_body(), expression::elts, fprintf_filtered(), op_name(), and exp_element::opcode.
Referenced by ada_dump_subexp_body(), dump_prefix_expression(), and dump_subexp_body_standard().
int dump_subexp_body_standard (struct expression * , struct ui_file * , int)
Definition at line 764 of file expprint.c.
References exp_element::block, BYTES_TO_EXP_ELEM, exp_element::doubleconst, dump_subexp(), expression::elts, fprintf_filtered(), fputs_filtered(), gdb_print_host_address(), exp_element::internalvar, internalvar_name(), len, exp_element::longconst, LONGEST, longest_to_int(), exp_element::objfile, objfile_name(), exp_element::opcode, op_print::opcode, plongest(), exp_element::string, exp_element::symbol, SYMBOL_PRINT_NAME, exp_element::type, and type_print().
Referenced by ada_dump_subexp_body().
int end_arglist (void)
Definition at line 162 of file parse.c.
References arglist_len, funcall::arglist_len, funcall_chain, funcall::next, and xfree().
void int exp_uses_objfile (struct expression * exp, struct objfile * objfile)
Definition at line 1905 of file parse.c.
References exp_iterate(), exp_uses_objfile_iter(), gdb_assert, and objfile::separate_debug_objfile_backlink.
Referenced by clear_dangling_display_expressions().
const char* find_template_name_end (const char *)
Definition at line 737 of file parse.c.
Referenced by lex_one_token().
struct type* follow_types (struct type *) [read]
Definition at line 1637 of file parse.c.
References type_stack::depth, follow_types(), gdb_assert, gdb_assert_not_reached, lookup_array_range_type(), lookup_function_type(), lookup_function_type_with_arguments(), lookup_pointer_type(), lookup_reference_type(), make_cv_type(), make_type_with_address_space(), pop_type(), pop_type_int(), pop_type_stack(), Session::save(), tp_array, tp_const, tp_end, tp_function, tp_function_with_arguments, tp_pointer, tp_reference, tp_space_identifier, tp_type_stack, tp_volatile, TYPE_ARRAY_UPPER_BOUND_IS_UNDEFINED, TYPE_CONST, type_stack, TYPE_VOLATILE, VEC, VEC_address, VEC_free, and VEC_length.
Referenced by follow_types().
struct type_stack* get_type_stack (void) [read]
Definition at line 1599 of file parse.c.
References type_stack::depth, type_stack::elements, type_stack::size, and type_stack.
void initialize_expout (int , const struct language_defn * , struct gdbarch *)
Definition at line 194 of file parse.c.
References EXP_ELEM_TO_BYTES, expout_ptr, expout_size, expression::gdbarch, expression::language_defn, and xmalloc().
Referenced by parse_exp_in_context_1(), and stap_parse_argument().
void insert_type (enum type_pieces)
Definition at line 1472 of file parse.c.
References type_stack::depth, gdb_assert, insert_into_type_stack(), type_stack_elt::piece, tp_const, tp_pointer, tp_reference, and tp_volatile.
void insert_type_address_space (char *)
Definition at line 1515 of file parse.c.
References address_space_name_to_int(), type_stack::depth, insert_into_type_stack(), type_stack_elt::int_val, parse_gdbarch, type_stack_elt::piece, and tp_space_identifier.
int length_of_subexp (struct expression * , int)
Definition at line 854 of file parse.c.
References length_of_subexp(), and operator_length().
Referenced by copy_exp(), length_of_subexp(), and prefixify_subexp().
void mark_completion_tag (enum type_code, const char * ptr, int length)
Definition at line 602 of file parse.c.
References expout_completion_name, expout_last_struct, expout_tag_completion_type, gdb_assert, memcpy(), parse_completion, TYPE_CODE_CLASS, TYPE_CODE_ENUM, TYPE_CODE_STRUCT, TYPE_CODE_UNDEF, TYPE_CODE_UNION, and xmalloc().
void mark_struct_expression (void)
Definition at line 590 of file parse.c.
References expout_last_struct, expout_ptr, expout_tag_completion_type, gdb_assert, parse_completion, and TYPE_CODE_UNDEF.
void null_post_parser (struct expression ** , int)
Definition at line 1353 of file parse.c.
char* op_name_standard (enum exp_opcode)
Definition at line 664 of file expprint.c.
References xsnprintf().
Referenced by ada_op_name().
int operator_check_standard (struct expression * exp, int pos, int(*)(struct objfile *objfile, void *data) objfile_func, void * data)
Definition at line 1775 of file parse.c.
References exp_element::block, expression::elts, gdb_assert, exp_element::longconst, LONGEST, lookup_objfile_from_block(), exp_element::objfile, exp_element::symbol, SYMBOL_SYMTAB, SYMBOL_TYPE, exp_element::type, and TYPE_OBJFILE.
Referenced by ada_operator_check().
void operator_length (const struct expression * , int , int * , int *)
Definition at line 874 of file parse.c.
References language_defn::la_exp_desc, expression::language_defn, and exp_descriptor::operator_length.
Referenced by exp_iterate(), length_of_subexp(), prefixify_subexp(), and watchpoint_exp_is_const().
void operator_length_standard (const struct expression * , int , int * , int *)
Definition at line 884 of file parse.c.
References _, BOTH_BOUND_DEFAULT, BYTES_TO_EXP_ELEM, expression::elts, error(), HIGH_BOUND_DEFAULT, int, exp_element::longconst, longest_to_int(), LOW_BOUND_DEFAULT, NONE_BOUND_DEFAULT, and exp_element::opcode.
Referenced by ada_operator_length().
int parse_c_float (struct gdbarch * gdbarch, const char * p, int len, DOUBLEST * d, struct type ** t)
Definition at line 1393 of file parse.c.
References builtin_type::builtin_double, builtin_type::builtin_float, builtin_type::builtin_long_double, builtin_type(), and parse_float().
Referenced by parse_go_float(), and parse_number().
int parse_float (const char * p, int len, DOUBLEST * d, const char ** suffix)
Definition at line 1365 of file parse.c.
References DOUBLEST_SCAN_FORMAT, len, memcpy(), xfree(), and xmalloc().
Referenced by parse_c_float(), and parse_number().
void parser_fprintf (FILE * , const char * , ...)
enum type_pieces pop_type (void)
Definition at line 1535 of file parse.c.
References type_stack::depth, type_stack::elements, type_stack_elt::piece, and tp_end.
Referenced by follow_types().
int pop_type_int (void)
Definition at line 1543 of file parse.c.
References type_stack::depth, type_stack::elements, and type_stack_elt::int_val.
Referenced by follow_types().
int prefixify_expression (struct expression * expr)
Definition at line 836 of file parse.c.
References len, memcpy(), expression::nelts, and prefixify_subexp().
Referenced by parse_exp_in_context_1(), and stap_parse_probe_arguments().
void print_subexp (struct expression * , int * , struct ui_file * , enum precedence)
Definition at line 51 of file expprint.c.
References language_defn::la_exp_desc, expression::language_defn, and exp_descriptor::print_subexp.
Referenced by ada_print_subexp(), print_expression(), and print_subexp_standard().
void print_subexp_standard (struct expression * , int * , struct ui_file * , enum precedence)
Definition at line 60 of file expprint.c.
References _, exp_element::block, BLOCK_FUNCTION, builtin_type::builtin_char, BYTES_TO_EXP_ELEM, exp_element::doubleconst, expression::elts, error(), fprintf_filtered(), fprintf_unfiltered(), fputs_filtered(), fputs_unfiltered(), gdb_assert, expression::gdbarch, get_no_prettyformat_print_options(), get_user_print_options(), exp_element::internalvar, internalvar_name(), language_defn::la_language, language_defn::la_name, language_defn::la_name_of_this, language_defn::la_op_print_tab, LA_PRINT_STRING, language_c, expression::language_defn, exp_element::longconst, LONGEST, longest_to_int(), name, exp_element::opcode, op_print::opcode, PREC_ABOVE_COMMA, PREC_ASSIGN, PREC_BUILTIN_FUNCTION, PREC_COMMA, PREC_HYPER, PREC_NULL, PREC_PREFIX, PREC_SUFFIX, op_print::precedence, print_subexp(), op_print::right_assoc, selector, strchr(), exp_element::string, op_print::string, exp_element::symbol, SYMBOL_PRINT_NAME, target_read_string(), exp_element::type, TYPE_CODE, TYPE_CODE_FUNC, type_name_no_tag(), type_print(), value_at_lazy(), value_from_double(), value_from_longest(), value_print(), and xfree().
Referenced by ada_print_subexp().
void push_type (enum type_pieces)
Definition at line 1493 of file parse.c.
References check_type_stack_depth(), type_stack::depth, type_stack::elements, and type_stack_elt::piece.
Referenced by push_type_stack(), and push_typelist().
void push_type_int (int)
Definition at line 1500 of file parse.c.
References check_type_stack_depth(), type_stack::depth, type_stack::elements, and type_stack_elt::int_val.
void push_type_stack (struct type_stack * stack)
Definition at line 1587 of file parse.c.
References check_type_stack_depth(), type_stack::depth, type_stack::elements, push_type(), type_stack_elt::stack_val, and tp_type_stack.
void push_typelist (VEC(type_ptr)* typelist)
Definition at line 1627 of file parse.c.
References check_type_stack_depth(), type_stack::depth, type_stack::elements, push_type(), and tp_function_with_arguments.
void reallocate_expout (void)
Definition at line 208 of file parse.c.
References EXP_ELEM_TO_BYTES, expout_ptr, expression::nelts, and xrealloc().
Referenced by parse_exp_in_context_1(), and stap_parse_argument().
void start_arglist (void)
Definition at line 147 of file parse.c.
References arglist_len, funcall::arglist_len, funcall_chain, and xmalloc().
void type_stack_cleanup (void * arg)
Definition at line 1614 of file parse.c.
References type_stack::elements, and xfree().
void write_dollar_variable (struct stoken str)
Definition at line 641 of file parse.c.
References block_found, copy_name(), create_internalvar(), stoken::length, LONGEST, lookup_bound_minimal_symbol(), lookup_only_internalvar(), lookup_symbol(), bound_minimal_symbol::minsym, parse_gdbarch, stoken::ptr, user_reg_map_name_to_regnum(), VAR_DOMAIN, write_exp_elt_block(), write_exp_elt_intern(), write_exp_elt_longcst(), write_exp_elt_opcode(), write_exp_elt_sym(), write_exp_msymbol(), and write_exp_string().
Referenced by yylex().
void write_exp_bitstring (struct stoken)
Definition at line 460 of file parse.c.
References bits, BYTES_TO_EXP_ELEM, expression::elts, expout, expout_ptr, expout_size, HOST_CHAR_BIT, len, stoken::length, LONGEST, max, memcpy(), stoken::ptr, write_exp_elt_longcst(), and xrealloc().
void write_exp_elt_block (const struct block *)
Definition at line 259 of file parse.c.
References exp_element::block, memset(), and write_exp_elt().
Referenced by push_variable(), write_ambiguous_var(), write_dollar_variable(), and write_var_from_sym().
void write_exp_elt_dblcst (DOUBLEST)
Definition at line 289 of file parse.c.
References exp_element::doubleconst, memset(), and write_exp_elt().
void write_exp_elt_decfloatcst (gdb_byte *)
void write_exp_elt_intern (struct internalvar *)
Definition at line 321 of file parse.c.
References exp_element::internalvar, memset(), and write_exp_elt().
Referenced by write_dollar_variable().
void write_exp_elt_longcst (LONGEST)
Definition at line 279 of file parse.c.
References exp_element::longconst, memset(), and write_exp_elt().
Referenced by arm_stap_parse_special_token(), end_msglist(), i386_stap_parse_special_token(), stap_parse_register_operand(), stap_parse_single_operand(), write_dollar_variable(), write_exp_bitstring(), write_exp_msymbol(), write_exp_string(), write_exp_string_vector(), write_int(), and write_object_renaming().
void write_exp_elt_objfile (struct objfile * objfile)
Definition at line 269 of file parse.c.
References memset(), exp_element::objfile, and write_exp_elt().
Referenced by write_exp_msymbol().
void write_exp_elt_opcode (enum exp_opcode)
Definition at line 239 of file parse.c.
References memset(), exp_element::opcode, and write_exp_elt().
Referenced by arm_stap_parse_special_token(), i386_stap_parse_special_token(), ppc_stap_parse_special_token(), push_expression_name(), push_fieldnames(), push_qualified_expression_name(), push_variable(), stap_parse_argument(), stap_parse_argument_1(), stap_parse_register_operand(), stap_parse_single_operand(), write_ambiguous_var(), write_dollar_variable(), write_exp_msymbol(), write_exp_op_with_string(), write_exp_string_vector(), write_int(), write_object_renaming(), and write_var_from_sym().
void write_exp_elt_sym (struct symbol *)
Definition at line 249 of file parse.c.
References memset(), exp_element::symbol, and write_exp_elt().
Referenced by push_variable(), write_ambiguous_var(), write_dollar_variable(), and write_var_from_sym().
void write_exp_elt_type (struct type *)
Definition at line 311 of file parse.c.
References memset(), exp_element::type, and write_exp_elt().
Referenced by arm_stap_parse_special_token(), i386_stap_parse_special_token(), push_expression_name(), push_qualified_expression_name(), stap_parse_argument(), stap_parse_register_operand(), stap_parse_single_operand(), write_exp_msymbol(), write_int(), and write_object_renaming().
void write_exp_msymbol (struct bound_minimal_symbol)
Definition at line 499 of file parse.c.
References current_target, gdbarch_convert_from_func_ptr_addr(), get_objfile_arch(), LONGEST, lookup_minimal_symbol_by_pc(), bound_minimal_symbol::minsym, mst_bss, mst_data, mst_file_bss, mst_file_data, mst_file_text, mst_slot_got_plt, mst_solib_trampoline, mst_text, mst_text_gnu_ifunc, MSYMBOL_TYPE, bound_minimal_symbol::objfile, overlay_debugging, SYMBOL_OBJ_SECTION, symbol_overlayed_address(), SYMBOL_VALUE_ADDRESS, obj_section::the_bfd_section, write_exp_elt_longcst(), write_exp_elt_objfile(), write_exp_elt_opcode(), and write_exp_elt_type().
Referenced by push_expression_name(), write_dollar_variable(), and write_var_or_type().
void write_exp_string (struct stoken)
Definition at line 352 of file parse.c.
References BYTES_TO_EXP_ELEM, expression::elts, expout, expout_ptr, expout_size, len, stoken::length, LONGEST, max, memcpy(), stoken::ptr, write_exp_elt_longcst(), and xrealloc().
Referenced by arm_stap_parse_special_token(), i386_stap_parse_special_token(), ppc_stap_parse_special_token(), push_fieldnames(), push_qualified_expression_name(), push_variable(), stap_parse_register_operand(), write_destructor_name(), write_dollar_variable(), and write_exp_op_with_string().
void write_exp_string_vector (int type, struct stoken_vector * vec)
Definition at line 403 of file parse.c.
References BYTES_TO_EXP_ELEM, expression::elts, EXP_ELEM_TO_BYTES, expout, expout_ptr, expout_size, len, stoken_vector::len, typed_stoken::length, max, memcpy(), typed_stoken::ptr, stoken_vector::tokens, write_exp_elt_longcst(), write_exp_elt_opcode(), and xrealloc().
Variable Documentation
int arglist_len
Definition at line 76 of file parse.c.
Referenced by end_arglist(), and start_arglist().
struct block* block_found
Definition at line 144 of file symtab.c.
Referenced by push_variable(), standard_lookup(), and write_dollar_variable().
int comma_terminates
Definition at line 81 of file parse.c.
Referenced by lex_one_token(), parse_exp_in_context_1(), and yylex().
struct exp_descriptor exp_descriptor_standard
Definition at line 59 of file parse.c.
struct expression* expout
Definition at line 70 of file parse.c.
Referenced by insert_exp(), parse_exp_in_context_1(), stap_parse_argument(), write_exp_bitstring(), write_exp_elt(), write_exp_string(), and write_exp_string_vector().
int expout_ptr
Definition at line 72 of file parse.c.
Referenced by initialize_expout(), insert_exp(), mark_struct_expression(), reallocate_expout(), write_exp_bitstring(), write_exp_elt(), write_exp_string(), and write_exp_string_vector().
int expout_size
Definition at line 71 of file parse.c.
Referenced by initialize_expout(), insert_exp(), write_exp_bitstring(), write_exp_elt(), write_exp_string(), and write_exp_string_vector().
struct block* expression_context_block
Definition at line 73 of file parse.c.
Referenced by c_parse(), clear_symtab_users(), free_objfile(), java_lookup_class(), lex_one_token(), push_variable(), write_name_assoc(), write_var_or_type(), and yylex().
CORE_ADDR expression_context_pc
Definition at line 74 of file parse.c.
Referenced by c_parse(), and parse_exp_in_context_1().
struct block* innermost_block
Definition at line 75 of file parse.c.
const char* lexptr
Definition at line 78 of file parse.c.
Referenced by cp_demangled_name_to_comp(), finished_macro_expansion(), lex_one_token(), match_string_literal(), parse_exp_in_context_1(), parse_number(), rewind_to_char(), scan_macro_expansion(), symbol_end(), yyerror(), and yylex().
int paren_depth
Definition at line 80 of file parse.c.
Referenced by lex_one_token(), parse_exp_in_context_1(), and yylex().
int parser_debug
Definition at line 108 of file parse.c.
Referenced by c_parse(), and go_parse().
const char* prev_lexptr
Definition at line 79 of file parse.c.
Referenced by cp_demangled_name_to_comp(), lex_one_token(), parse_exp_in_context_1(), and yylex().