GDB (xrefs): /home/stan/gdb/src/gdb/features/rs6000/powerpc-32.c File Reference
/home/stan/gdb/src/gdb/features/rs6000/powerpc-32.c File Reference
#include "defs.h"
#include "osabi.h"
#include "target-descriptions.h"
Functions
static void initialize_tdesc_powerpc_32 (void)
Variables
struct target_desc * tdesc_powerpc_32
Function Documentation
static void initialize_tdesc_powerpc_32 (void) [static]
Definition at line 10 of file powerpc-32.c.
References allocate_target_description(), set_tdesc_architecture(), tdesc_create_feature(), and tdesc_create_reg().
Referenced by _initialize_rs6000_tdep().
Variable Documentation
struct target_desc* tdesc_powerpc_32
Definition at line 8 of file powerpc-32.c.