GDB (xrefs): /home/stan/gdb/src/gdb/ppc-linux-tdep.c File Reference
/home/stan/gdb/src/gdb/ppc-linux-tdep.c File Reference
#include "defs.h"
#include "frame.h"
#include "inferior.h"
#include "symtab.h"
#include "target.h"
#include "gdbcore.h"
#include "gdbcmd.h"
#include "symfile.h"
#include "objfiles.h"
#include "regcache.h"
#include "value.h"
#include "osabi.h"
#include "regset.h"
#include "solib-svr4.h"
#include "solib-spu.h"
#include "solib.h"
#include "solist.h"
#include "ppc-tdep.h"
#include "ppc64-tdep.h"
#include "ppc-linux-tdep.h"
#include "glibc-tdep.h"
#include "trad-frame.h"
#include "frame-unwind.h"
#include "tramp-frame.h"
#include "observer.h"
#include "auxv.h"
#include "elf/common.h"
#include "exceptions.h"
#include "arch-utils.h"
#include "spu-tdep.h"
#include "xml-syscall.h"
#include "linux-tdep.h"
#include "stap-probe.h"
#include "ax.h"
#include "ax-gdb.h"
#include "cli/cli-utils.h"
#include "parser-defs.h"
#include "user-regs.h"
#include <ctype.h>
#include "elf-bfd.h"
#include "features/rs6000/powerpc-32l.c"
#include "features/rs6000/powerpc-altivec32l.c"
#include "features/rs6000/powerpc-cell32l.c"
#include "features/rs6000/powerpc-vsx32l.c"
#include "features/rs6000/powerpc-isa205-32l.c"
#include "features/rs6000/powerpc-isa205-altivec32l.c"
#include "features/rs6000/powerpc-isa205-vsx32l.c"
#include "features/rs6000/powerpc-64l.c"
#include "features/rs6000/powerpc-altivec64l.c"
#include "features/rs6000/powerpc-cell64l.c"
#include "features/rs6000/powerpc-vsx64l.c"
#include "features/rs6000/powerpc-isa205-64l.c"
#include "features/rs6000/powerpc-isa205-altivec64l.c"
#include "features/rs6000/powerpc-isa205-vsx64l.c"
#include "features/rs6000/powerpc-e500l.c"
Classes
struct ppu2spu_cache
struct ppu2spu_data
Defines
#define XML_SYSCALL_FILENAME_PPC "syscalls/ppc-linux.xml"
#define XML_SYSCALL_FILENAME_PPC64 "syscalls/ppc64-linux.xml"
#define POWERPC32_PLT_STUB_LEN ARRAY_SIZE (powerpc32_plt_stub)
Functions
static int ppc_linux_memory_remove_breakpoint (struct gdbarch *gdbarch, struct bp_target_info *bp_tgt)
static enum return_value_convention ppc_linux_return_value (struct gdbarch *gdbarch, struct value *function, struct type *valtype, struct regcache *regcache, gdb_byte *readbuf, const gdb_byte *writebuf)
static int powerpc_linux_in_dynsym_resolve_code (CORE_ADDR pc)
static CORE_ADDR ppc_skip_trampoline_code (struct frame_info *frame, CORE_ADDR pc)
static void ppc_linux_supply_gregset (const struct regset *regset, struct regcache *regcache, int regnum, const void *gregs, size_t len)
static void ppc_linux_collect_gregset (const struct regset *regset, const struct regcache *regcache, int regnum, void *gregs, size_t len)
struct regset * ppc_linux_gregset (int wordsize)
struct regset * ppc_linux_fpregset (void)
static struct regset * ppc_linux_regset_from_core_section (struct gdbarch *core_arch, const char *sect_name, size_t sect_size)
static void ppc_linux_sigtramp_cache (struct frame_info *this_frame, struct trad_frame_cache *this_cache, CORE_ADDR func, LONGEST offset, int bias)
static void ppc32_linux_sigaction_cache_init (const struct tramp_frame *self, struct frame_info *this_frame, struct trad_frame_cache *this_cache, CORE_ADDR func)
static void ppc64_linux_sigaction_cache_init (const struct tramp_frame *self, struct frame_info *this_frame, struct trad_frame_cache *this_cache, CORE_ADDR func)
static void ppc32_linux_sighandler_cache_init (const struct tramp_frame *self, struct frame_info *this_frame, struct trad_frame_cache *this_cache, CORE_ADDR func)
static void ppc64_linux_sighandler_cache_init (const struct tramp_frame *self, struct frame_info *this_frame, struct trad_frame_cache *this_cache, CORE_ADDR func)
static void ppc_linux_inferior_created (struct target_ops *target, int from_tty)
static CORE_ADDR ppc_linux_displaced_step_location (struct gdbarch *gdbarch)
int ppc_linux_trap_reg_p (struct gdbarch *gdbarch)
static LONGEST ppc_linux_get_syscall_number (struct gdbarch *gdbarch, ptid_t ptid)
static void ppc_linux_write_pc (struct regcache *regcache, CORE_ADDR pc)
static int ppc_linux_spu_section (bfd *abfd, asection *asect, void *user_data)
static struct target_desc * ppc_linux_core_read_description (struct gdbarch *gdbarch, struct target_ops *target, bfd *abfd)
static int ppc_stap_is_single_operand (struct gdbarch *gdbarch, const char *s)
static int ppc_stap_parse_special_token (struct gdbarch *gdbarch, struct stap_parse_info *p)
static void ppc_linux_spe_context_lookup (struct objfile *objfile)
static void ppc_linux_spe_context_inferior_created (struct target_ops *t, int from_tty)
static void ppc_linux_spe_context_solib_loaded (struct so_list *so)
static void ppc_linux_spe_context_solib_unloaded (struct so_list *so)
static CORE_ADDR ppc_linux_spe_context (int wordsize, enum bfd_endian byte_order, int n, int *id, unsigned int *npc)
static struct gdbarch * ppu2spu_prev_arch (struct frame_info *this_frame, void **this_cache)
static void ppu2spu_this_id (struct frame_info *this_frame, void **this_cache, struct frame_id *this_id)
static struct value * ppu2spu_prev_register (struct frame_info *this_frame, void **this_cache, int regnum)
static int ppu2spu_unwind_register (void *src, int regnum, gdb_byte *buf)
static int ppu2spu_sniffer (const struct frame_unwind *self, struct frame_info *this_frame, void **this_prologue_cache)
static void ppu2spu_dealloc_cache (struct frame_info *self, void *this_cache)
static void ppc_linux_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
void _initialize_ppc_linux_tdep (void)
Variables
static struct target_so_ops powerpc_so_ops
static struct core_regset_section ppc_linux_vsx_regset_sections []
static struct core_regset_section ppc_linux_vmx_regset_sections []
static struct core_regset_section ppc_linux_fp_regset_sections []
static struct core_regset_section ppc64_linux_vsx_regset_sections []
static struct core_regset_section ppc64_linux_vmx_regset_sections []
static struct core_regset_section ppc64_linux_fp_regset_sections []
static struct ppc_insn_pattern powerpc32_plt_stub []
static struct ppc_insn_pattern powerpc32_plt_stub_so []
static struct ppc_reg_offsets ppc32_linux_reg_offsets
static struct ppc_reg_offsets ppc64_linux_reg_offsets
static struct regset ppc32_linux_gregset
static struct regset ppc64_linux_gregset
static struct regset ppc32_linux_fpregset
static struct regset ppc32_linux_vrregset
static struct regset ppc32_linux_vsxregset
static struct tramp_frame ppc32_linux_sigaction_tramp_frame
static struct tramp_frame ppc64_linux_sigaction_tramp_frame
static struct tramp_frame ppc32_linux_sighandler_tramp_frame
static struct tramp_frame ppc64_linux_sighandler_tramp_frame
static CORE_ADDR ppc_linux_entry_point_addr = 0
static struct objfile * spe_context_objfile = NULL
static CORE_ADDR spe_context_lm_addr = 0
static CORE_ADDR spe_context_offset = 0
static ptid_t spe_context_cache_ptid
static CORE_ADDR spe_context_cache_address
static struct frame_unwind ppu2spu_unwind
initialize_file_ftype _initialize_ppc_linux_tdep
Define Documentation
#define POWERPC32_PLT_STUB_LEN ARRAY_SIZE (powerpc32_plt_stub)
Definition at line 326 of file ppc-linux-tdep.c.
Referenced by ppc_skip_trampoline_code().
#define XML_SYSCALL_FILENAME_PPC "syscalls/ppc-linux.xml"
Definition at line 82 of file ppc-linux-tdep.c.
Referenced by ppc_linux_init_abi().
#define XML_SYSCALL_FILENAME_PPC64 "syscalls/ppc64-linux.xml"
Definition at line 83 of file ppc-linux-tdep.c.
Referenced by ppc_linux_init_abi().
Function Documentation
void _initialize_ppc_linux_tdep (void)
Definition at line 1436 of file ppc-linux-tdep.c.
References _initialize_ppc_linux_tdep, GDB_OSABI_LINUX, gdbarch_register_osabi(), initialize_tdesc_powerpc_32l(), initialize_tdesc_powerpc_64l(), initialize_tdesc_powerpc_altivec32l(), initialize_tdesc_powerpc_altivec64l(), initialize_tdesc_powerpc_cell32l(), initialize_tdesc_powerpc_cell64l(), initialize_tdesc_powerpc_e500l(), initialize_tdesc_powerpc_isa205_32l(), initialize_tdesc_powerpc_isa205_64l(), initialize_tdesc_powerpc_isa205_altivec32l(), initialize_tdesc_powerpc_isa205_altivec64l(), initialize_tdesc_powerpc_isa205_vsx32l(), initialize_tdesc_powerpc_isa205_vsx64l(), initialize_tdesc_powerpc_vsx32l(), initialize_tdesc_powerpc_vsx64l(), observer_attach_inferior_created(), observer_attach_solib_loaded(), observer_attach_solib_unloaded(), ppc_linux_inferior_created(), ppc_linux_init_abi(), ppc_linux_spe_context_inferior_created(), ppc_linux_spe_context_solib_loaded(), and ppc_linux_spe_context_solib_unloaded().
static int powerpc_linux_in_dynsym_resolve_code (CORE_ADDR pc) [static]
Definition at line 333 of file ppc-linux-tdep.c.
References lookup_minimal_symbol_by_pc(), bound_minimal_symbol::minsym, svr4_in_dynsym_resolve_code(), and SYMBOL_LINKAGE_NAME.
Referenced by ppc_linux_init_abi().
static void ppc32_linux_sigaction_cache_init (const struct tramp_frame * self, struct frame_info * this_frame, struct trad_frame_cache * this_cache, CORE_ADDR func) [static]
Definition at line 637 of file ppc-linux-tdep.c.
References ppc_linux_sigtramp_cache().
static void ppc32_linux_sighandler_cache_init (const struct tramp_frame * self, struct frame_info * this_frame, struct trad_frame_cache * this_cache, CORE_ADDR func) [static]
Definition at line 661 of file ppc-linux-tdep.c.
References ppc_linux_sigtramp_cache().
static void ppc64_linux_sigaction_cache_init (const struct tramp_frame * self, struct frame_info * this_frame, struct trad_frame_cache * this_cache, CORE_ADDR func) [static]
Definition at line 649 of file ppc-linux-tdep.c.
References ppc_linux_sigtramp_cache().
static void ppc64_linux_sighandler_cache_init (const struct tramp_frame * self, struct frame_info * this_frame, struct trad_frame_cache * this_cache, CORE_ADDR func) [static]
Definition at line 673 of file ppc-linux-tdep.c.
References ppc_linux_sigtramp_cache().
static void ppc_linux_collect_gregset (const struct regset * regset, const struct regcache * regcache, int regnum, void * gregs, size_t len) [static]
Definition at line 418 of file ppc-linux-tdep.c.
References regset::descr, get_regcache_arch(), ppc_reg_offsets::gpr_size, memset(), ppc_reg_offsets::pc_offset, ppc_collect_gregset(), ppc_collect_reg(), ppc_linux_trap_reg_p(), PPC_ORIG_R3_REGNUM, and PPC_TRAP_REGNUM.
static struct target_desc* ppc_linux_core_read_description (struct gdbarch * gdbarch, struct target_ops * target, bfd * abfd) [static, read]
Definition at line 841 of file ppc-linux-tdep.c.
References ppc_linux_spu_section(), tdesc_powerpc_32l, tdesc_powerpc_64l, tdesc_powerpc_altivec32l, tdesc_powerpc_altivec64l, tdesc_powerpc_cell32l, tdesc_powerpc_cell64l, tdesc_powerpc_vsx32l, and tdesc_powerpc_vsx64l.
Referenced by ppc_linux_init_abi().
static CORE_ADDR ppc_linux_displaced_step_location (struct gdbarch * gdbarch) [static]
Definition at line 743 of file ppc-linux-tdep.c.
References _, current_target, error(), gdbarch_convert_from_func_ptr_addr(), PPC_INSN_SIZE, ppc_linux_entry_point_addr, and target_auxv_search().
Referenced by ppc_linux_init_abi().
struct regset* ppc_linux_fpregset (void) [read]
Definition at line 539 of file ppc-linux-tdep.c.
References ppc32_linux_fpregset.
Referenced by fill_fpregset(), and supply_fpregset().
static LONGEST ppc_linux_get_syscall_number (struct gdbarch * gdbarch, ptid_t ptid) [static]
Definition at line 785 of file ppc-linux-tdep.c.
References do_cleanups(), extract_signed_integer(), gdb_assert, gdbarch_byte_order(), gdbarch_tdep(), get_thread_regcache(), LONGEST, make_cleanup(), gdbarch_tdep::ppc_gp0_regnum, regcache_cooked_read(), gdbarch_tdep::wordsize, xfree(), and xmalloc().
Referenced by ppc_linux_init_abi().
struct regset* ppc_linux_gregset (int wordsize) [read]
Definition at line 533 of file ppc-linux-tdep.c.
References ppc32_linux_gregset.
Referenced by fill_gregset(), and supply_gregset().
static void ppc_linux_inferior_created (struct target_ops * target, int from_tty) [static]
Definition at line 737 of file ppc-linux-tdep.c.
References ppc_linux_entry_point_addr.
Referenced by _initialize_ppc_linux_tdep().
static void ppc_linux_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch) [static]
Definition at line 1243 of file ppc-linux-tdep.c.
References floatformats_ibm_long_double, frame_unwind_prepend_unwinder(), gdb_assert, gdbarch_byte_order(), gdbarch_num_regs(), gdbarch_tdep(), glibc_skip_solib_resolver(), target_so_ops::in_dynsym_resolve_code, linux_get_siginfo_type(), linux_init_abi(), powerpc_linux_in_dynsym_resolve_code(), powerpc_so_ops, ppc64_convert_from_func_ptr_addr(), ppc64_elf_make_msymbol_special(), ppc64_skip_trampoline_code(), ppc_linux_core_read_description(), ppc_linux_displaced_step_location(), ppc_linux_get_syscall_number(), ppc_linux_memory_remove_breakpoint(), ppc_linux_regset_from_core_section(), ppc_linux_return_value(), ppc_linux_write_pc(), PPC_ORIG_R3_REGNUM, ppc_skip_trampoline_code(), ppc_stap_is_single_operand(), ppc_stap_parse_special_token(), PPC_TRAP_REGNUM, set_gdbarch_convert_from_func_ptr_addr(), set_gdbarch_core_read_description(), set_gdbarch_core_regset_sections(), set_gdbarch_displaced_step_location(), set_gdbarch_elf_make_msymbol_special(), set_gdbarch_elfcore_write_linux_prpsinfo(), set_gdbarch_fetch_tls_load_module_address(), set_gdbarch_gcore_bfd_target(), set_gdbarch_get_siginfo_type(), set_gdbarch_get_syscall_number(), set_gdbarch_long_double_bit(), set_gdbarch_long_double_format(), set_gdbarch_memory_remove_breakpoint(), set_gdbarch_num_regs(), set_gdbarch_regset_from_core_section(), set_gdbarch_return_value(), set_gdbarch_skip_solib_resolver(), set_gdbarch_skip_trampoline_code(), set_gdbarch_stap_gdb_register_prefix(), set_gdbarch_stap_integer_prefix(), set_gdbarch_stap_is_single_operand(), set_gdbarch_stap_parse_special_token(), set_gdbarch_stap_register_indirection_prefix(), set_gdbarch_stap_register_indirection_suffix(), set_gdbarch_write_pc(), set_solib_ops(), set_solib_svr4_fetch_link_map_offsets(), set_spu_solib_ops(), set_xml_syscall_file_name(), svr4_fetch_objfile_link_map(), svr4_ilp32_fetch_link_map_offsets(), svr4_lp64_fetch_link_map_offsets(), svr4_so_ops, gdbarch_info::target_desc, gdbarch_info::tdep_info, tdesc_compatible_p(), tdesc_data, tdesc_find_feature(), tdesc_numbered_register(), tramp_frame_prepend_unwinder(), gdbarch_tdep::wordsize, XML_SYSCALL_FILENAME_PPC, and XML_SYSCALL_FILENAME_PPC64.
Referenced by _initialize_ppc_linux_tdep().
static int ppc_linux_memory_remove_breakpoint (struct gdbarch * gdbarch, struct bp_target_info * bp_tgt) [static]
Definition at line 210 of file ppc-linux-tdep.c.
References _, BREAKPOINT_MAX, do_cleanups(), error(), gdbarch_breakpoint_from_pc(), make_show_memory_breakpoints_cleanup(), memcmp(), bp_target_info::placed_address, bp_target_info::shadow_contents, target_read_memory(), and target_write_raw_memory().
Referenced by ppc_linux_init_abi().
static struct regset* ppc_linux_regset_from_core_section (struct gdbarch * core_arch, const char * sect_name, size_t sect_size) [static, read]
Definition at line 545 of file ppc-linux-tdep.c.
References gdbarch_tdep(), ppc32_linux_fpregset, ppc32_linux_gregset, ppc32_linux_vrregset, ppc32_linux_vsxregset, ppc64_linux_gregset, and gdbarch_tdep::wordsize.
Referenced by ppc_linux_init_abi().
static enum return_value_convention ppc_linux_return_value (struct gdbarch * gdbarch, struct value * function, struct type * valtype, struct regcache * regcache, gdb_byte * readbuf, const gdb_byte * writebuf) [static]
Definition at line 245 of file ppc-linux-tdep.c.
References ppc_sysv_abi_return_value(), RETURN_VALUE_STRUCT_CONVENTION, TYPE_CODE, TYPE_CODE_STRUCT, TYPE_CODE_UNION, TYPE_LENGTH, and TYPE_VECTOR.
Referenced by ppc_linux_init_abi().
static void ppc_linux_sigtramp_cache (struct frame_info * this_frame, struct trad_frame_cache * this_cache, CORE_ADDR func, LONGEST offset, int bias) [static]
Definition at line 566 of file ppc-linux-tdep.c.
References frame_id_build(), gdbarch_byte_order(), gdbarch_fp0_regnum(), gdbarch_pc_regnum(), gdbarch_sp_regnum(), gdbarch_tdep(), get_frame_arch(), get_frame_pc(), get_frame_register_unsigned(), offset, gdbarch_tdep::ppc_cr_regnum, gdbarch_tdep::ppc_ctr_regnum, ppc_floating_point_unit_p(), gdbarch_tdep::ppc_fpscr_regnum, gdbarch_tdep::ppc_gp0_regnum, ppc_linux_trap_reg_p(), gdbarch_tdep::ppc_lr_regnum, PPC_ORIG_R3_REGNUM, PPC_TRAP_REGNUM, gdbarch_tdep::ppc_xer_regnum, read_memory_unsigned_integer(), regnum, gdbarch_tdep::regs, trad_frame_set_id(), trad_frame_set_reg_addr(), and gdbarch_tdep::wordsize.
Referenced by ppc32_linux_sigaction_cache_init(), ppc32_linux_sighandler_cache_init(), ppc64_linux_sigaction_cache_init(), and ppc64_linux_sighandler_cache_init().
static CORE_ADDR ppc_linux_spe_context (int wordsize, enum bfd_endian byte_order, int n, int * id, unsigned int * npc) [static]
Definition at line 1019 of file ppc-linux-tdep.c.
References align_up(), current_target, extract_signed_integer(), extract_unsigned_integer(), find_target_beneath(), inferior_ptid, ptid_equal(), gdb_exception::reason, RETURN_MASK_ERROR, spe_context_cache_address, spe_context_lm_addr, spe_context_offset, target_read_memory(), target_ops::to_get_thread_local_address, and TRY_CATCH.
Referenced by ppu2spu_sniffer().
static void ppc_linux_spe_context_inferior_created (struct target_ops * t, int from_tty) [static]
Definition at line 989 of file ppc-linux-tdep.c.
References ALL_OBJFILES, and ppc_linux_spe_context_lookup().
Referenced by _initialize_ppc_linux_tdep().
static void ppc_linux_spe_context_lookup (struct objfile * objfile) [static]
Definition at line 962 of file ppc-linux-tdep.c.
References lookup_minimal_symbol(), minus_one_ptid, spe_context_cache_address, spe_context_lm_addr, spe_context_offset, svr4_fetch_objfile_link_map(), and SYMBOL_VALUE_ADDRESS.
Referenced by ppc_linux_spe_context_inferior_created(), ppc_linux_spe_context_solib_loaded(), and ppc_linux_spe_context_solib_unloaded().
static void ppc_linux_spe_context_solib_loaded (struct so_list * so) [static]
Definition at line 999 of file ppc-linux-tdep.c.
References so_list::objfile, ppc_linux_spe_context_lookup(), so_list::so_original_name, solib_read_symbols(), and strstr().
Referenced by _initialize_ppc_linux_tdep().
static void ppc_linux_spe_context_solib_unloaded (struct so_list * so) [static]
Definition at line 1009 of file ppc-linux-tdep.c.
References so_list::objfile, and ppc_linux_spe_context_lookup().
Referenced by _initialize_ppc_linux_tdep().
static int ppc_linux_spu_section (bfd * abfd, asection * asect, void * user_data) [static]
Definition at line 835 of file ppc-linux-tdep.c.
Referenced by ppc_linux_core_read_description().
static void ppc_linux_supply_gregset (const struct regset * regset, struct regcache * regcache, int regnum, const void * gregs, size_t len) [static]
Definition at line 393 of file ppc-linux-tdep.c.
References regset::descr, get_regcache_arch(), ppc_reg_offsets::gpr_size, ppc_reg_offsets::pc_offset, ppc_linux_trap_reg_p(), PPC_ORIG_R3_REGNUM, ppc_supply_gregset(), ppc_supply_reg(), and PPC_TRAP_REGNUM.
int ppc_linux_trap_reg_p (struct gdbarch * gdbarch)
Definition at line 770 of file ppc-linux-tdep.c.
References gdbarch_target_desc(), PPC_ORIG_R3_REGNUM, PPC_TRAP_REGNUM, register_size(), and tdesc_has_registers().
Referenced by fetch_ppc_registers(), ppc_linux_collect_gregset(), ppc_linux_sigtramp_cache(), ppc_linux_supply_gregset(), ppc_linux_write_pc(), and store_ppc_registers().
static void ppc_linux_write_pc (struct regcache * regcache, CORE_ADDR pc) [static]
Definition at line 816 of file ppc-linux-tdep.c.
References gdbarch_pc_regnum(), get_regcache_arch(), ppc_linux_trap_reg_p(), PPC_TRAP_REGNUM, and regcache_cooked_write_unsigned().
Referenced by ppc_linux_init_abi().
static CORE_ADDR ppc_skip_trampoline_code (struct frame_info * frame, CORE_ADDR pc) [static]
Definition at line 356 of file ppc-linux-tdep.c.
References gdbarch_byte_order(), gdbarch_tdep(), get_frame_arch(), get_frame_register_unsigned(), POWERPC32_PLT_STUB_LEN, gdbarch_tdep::ppc_gp0_regnum, ppc_insn_d_field(), ppc_insns_match_pattern(), and read_memory_unsigned_integer().
Referenced by ppc_linux_init_abi().
static int ppc_stap_is_single_operand (struct gdbarch * gdbarch, const char * s) [static]
Definition at line 883 of file ppc-linux-tdep.c.
Referenced by ppc_linux_init_abi().
static int ppc_stap_parse_special_token (struct gdbarch * gdbarch, struct stap_parse_info * p) [static]
Definition at line 896 of file ppc-linux-tdep.c.
References _, stap_parse_info::arg, error(), len, stoken::length, stoken::ptr, stap_parse_info::saved_arg, user_reg_map_name_to_regnum(), write_exp_elt_opcode(), and write_exp_string().
Referenced by ppc_linux_init_abi().
static void ppu2spu_dealloc_cache (struct frame_info * self, void * this_cache) [static]
Definition at line 1224 of file ppc-linux-tdep.c.
References ppu2spu_cache::regcache, and regcache_xfree().
static struct gdbarch* ppu2spu_prev_arch (struct frame_info * this_frame, void ** this_cache) [static, read]
Definition at line 1099 of file ppc-linux-tdep.c.
References get_regcache_arch(), and ppu2spu_cache::regcache.
static struct value* ppu2spu_prev_register (struct frame_info * this_frame, void ** this_cache, int regnum) [static, read]
Definition at line 1114 of file ppc-linux-tdep.c.
References frame_unwind_got_bytes(), gdbarch_num_regs(), gdbarch_pseudo_register_read(), get_regcache_arch(), ppu2spu_cache::regcache, regcache_raw_read(), and register_size().
static int ppu2spu_sniffer (const struct frame_unwind * self, struct frame_info * this_frame, void ** this_prologue_cache) [static]
Definition at line 1158 of file ppc-linux-tdep.c.
References ARCH_FRAME, frame_info::base, gdbarch_info::bfd_arch_info, gdbarch_info::byte_order, current_target, discard_cleanups(), extract_unsigned_integer(), ppu2spu_cache::frame_id, frame_id_build(), FRAME_OBSTACK_CALLOC, func, GDB_OSABI_LINUX, ppu2spu_data::gdbarch, gdbarch_bfd_arch_info(), gdbarch_byte_order(), gdbarch_find_by_info(), gdbarch_info_init(), gdbarch_tdep(), get_frame_address_space(), get_frame_arch(), get_frame_pc(), get_frame_sp(), get_frame_type(), get_next_frame(), ppu2spu_data::gprs, ppu2spu_data::id, make_cleanup_regcache_xfree(), ppu2spu_data::npc, gdbarch_info::osabi, ppc_linux_spe_context(), ppu2spu_unwind_register(), ppu2spu_cache::regcache, regcache_save(), regcache_xmalloc(), TARGET_OBJECT_SPU, target_read(), target_read_memory(), gdbarch_info::tdep_info, gdbarch_tdep::wordsize, and xsnprintf().
static void ppu2spu_this_id (struct frame_info * this_frame, void ** this_cache, struct frame_id * this_id) [static]
Definition at line 1106 of file ppc-linux-tdep.c.
References ppu2spu_cache::frame_id.
static int ppu2spu_unwind_register (void * src, int regnum, gdb_byte * buf) [static]
Definition at line 1140 of file ppc-linux-tdep.c.
References ppu2spu_data::gdbarch, gdbarch_byte_order(), ppu2spu_data::gprs, ppu2spu_data::id, memcpy(), ppu2spu_data::npc, REG_UNAVAILABLE, REG_VALID, SPU_ID_REGNUM, SPU_NUM_GPRS, SPU_PC_REGNUM, and store_unsigned_integer().
Referenced by ppu2spu_sniffer().
Variable Documentation
initialize_file_ftype _initialize_ppc_linux_tdep
Referenced by _initialize_ppc_linux_tdep(), and initialize_all_files().
struct ppc_insn_pattern powerpc32_plt_stub[] [static]
Initial value:
  {
    { 0xffff0000, 0x3d600000, 0 },
    { 0xffff0000, 0x816b0000, 0 },
    { 0xffffffff, 0x7d6903a6, 0 },
    { 0xffffffff, 0x4e800420, 0 },
    {          0,          0, 0 }
  }
Definition at line 308 of file ppc-linux-tdep.c.
struct ppc_insn_pattern powerpc32_plt_stub_so[] [static]
Initial value:
  {
    { 0xffff0000, 0x817e0000, 0 },
    { 0xffffffff, 0x7d6903a6, 0 },
    { 0xffffffff, 0x4e800420, 0 },
    { 0xffffffff, 0x60000000, 0 },
    {          0,          0, 0 }
  }
Definition at line 318 of file ppc-linux-tdep.c.
struct target_so_ops powerpc_so_ops [static]
Definition at line 79 of file ppc-linux-tdep.c.
Referenced by ppc_linux_init_abi().
struct regset ppc32_linux_fpregset [static]
Initial value:
 {
  &ppc32_linux_reg_offsets,
  ppc_supply_fpregset,
  ppc_collect_fpregset,
  NULL
}
Definition at line 511 of file ppc-linux-tdep.c.
Referenced by ppc_linux_fpregset(), and ppc_linux_regset_from_core_section().
struct regset ppc32_linux_gregset [static]
Initial value:
 {
  &ppc32_linux_reg_offsets,
  ppc_linux_supply_gregset,
  ppc_linux_collect_gregset,
  NULL
}
Definition at line 497 of file ppc-linux-tdep.c.
Referenced by ppc_linux_gregset(), and ppc_linux_regset_from_core_section().
struct ppc_reg_offsets ppc32_linux_reg_offsets [static]
Initial value:
  {
     0,
     4,
     4,
     128,
     132,
     152,
     144,
     140,
     148,
     156,
     0,
     256,
     8,
     0,
     512 + 12,
     528
  }
Definition at line 447 of file ppc-linux-tdep.c.
struct tramp_frame ppc32_linux_sigaction_tramp_frame [static]
Initial value:
 {
  SIGTRAMP_FRAME,
  4,
  {
    { 0x380000ac, -1 },
    { 0x44000002, -1 },
    { TRAMP_SENTINEL_INSN },
  },
  ppc32_linux_sigaction_cache_init
}
Definition at line 684 of file ppc-linux-tdep.c.
struct tramp_frame ppc32_linux_sighandler_tramp_frame [static]
Initial value:
 {
  SIGTRAMP_FRAME,
  4,
  {
    { 0x38000077, -1 },
    { 0x44000002, -1 },
    { TRAMP_SENTINEL_INSN },
  },
  ppc32_linux_sighandler_cache_init
}
Definition at line 705 of file ppc-linux-tdep.c.
struct regset ppc32_linux_vrregset [static]
Initial value:
 {
  &ppc32_linux_reg_offsets,
  ppc_supply_vrregset,
  ppc_collect_vrregset,
  NULL
}
Definition at line 518 of file ppc-linux-tdep.c.
Referenced by ppc_linux_regset_from_core_section().
struct regset ppc32_linux_vsxregset [static]
Initial value:
 {
  &ppc32_linux_reg_offsets,
  ppc_supply_vsxregset,
  ppc_collect_vsxregset,
  NULL
}
Definition at line 525 of file ppc-linux-tdep.c.
Referenced by ppc_linux_regset_from_core_section().
struct core_regset_section ppc64_linux_fp_regset_sections[] [static]
Initial value:
{
  { ".reg", 48 * 8, "general-purpose" },
  { ".reg2", 264, "floating-point" },
  { NULL, 0}
}
Definition at line 300 of file ppc-linux-tdep.c.
struct regset ppc64_linux_gregset [static]
Initial value:
 {
  &ppc64_linux_reg_offsets,
  ppc_linux_supply_gregset,
  ppc_linux_collect_gregset,
  NULL
}
Definition at line 504 of file ppc-linux-tdep.c.
Referenced by ppc_linux_regset_from_core_section().
struct ppc_reg_offsets ppc64_linux_reg_offsets [static]
Initial value:
  {
     0,
     8,
     8,
     256,
     264,
     304,
     288,
     280,
     296,
     312,
     0,
     256,
     8,
     0,
     512 + 12,
     528
  }
Definition at line 472 of file ppc-linux-tdep.c.
struct tramp_frame ppc64_linux_sigaction_tramp_frame [static]
Initial value:
 {
  SIGTRAMP_FRAME,
  4,
  {
    { 0x38210080, -1 },
    { 0x380000ac, -1 },
    { 0x44000002, -1 },
    { TRAMP_SENTINEL_INSN },
  },
  ppc64_linux_sigaction_cache_init
}
Definition at line 694 of file ppc-linux-tdep.c.
struct tramp_frame ppc64_linux_sighandler_tramp_frame [static]
Initial value:
 {
  SIGTRAMP_FRAME,
  4,
  {
    { 0x38210080, -1 },
    { 0x38000077, -1 },
    { 0x44000002, -1 },
    { TRAMP_SENTINEL_INSN },
  },
  ppc64_linux_sighandler_cache_init
}
Definition at line 715 of file ppc-linux-tdep.c.
struct core_regset_section ppc64_linux_vmx_regset_sections[] [static]
Initial value:
{
  { ".reg", 48 * 8, "general-purpose" },
  { ".reg2", 264, "floating-point" },
  { ".reg-ppc-vmx", 544, "ppc Altivec" },
  { NULL, 0}
}
Definition at line 292 of file ppc-linux-tdep.c.
struct core_regset_section ppc64_linux_vsx_regset_sections[] [static]
Initial value:
{
  { ".reg", 48 * 8, "general-purpose" },
  { ".reg2", 264, "floating-point" },
  { ".reg-ppc-vmx", 544, "ppc Altivec" },
  { ".reg-ppc-vsx", 256, "POWER7 VSX" },
  { NULL, 0}
}
Definition at line 283 of file ppc-linux-tdep.c.
CORE_ADDR ppc_linux_entry_point_addr = 0 [static]
Definition at line 734 of file ppc-linux-tdep.c.
Referenced by ppc_linux_displaced_step_location(), and ppc_linux_inferior_created().
struct core_regset_section ppc_linux_fp_regset_sections[] [static]
Initial value:
{
  { ".reg", 48 * 4, "general-purpose" },
  { ".reg2", 264, "floating-point" },
  { NULL, 0}
}
Definition at line 276 of file ppc-linux-tdep.c.
struct core_regset_section ppc_linux_vmx_regset_sections[] [static]
Initial value:
{
  { ".reg", 48 * 4, "general-purpose" },
  { ".reg2", 264, "floating-point" },
  { ".reg-ppc-vmx", 544, "ppc Altivec" },
  { NULL, 0}
}
Definition at line 268 of file ppc-linux-tdep.c.
struct core_regset_section ppc_linux_vsx_regset_sections[] [static]
Initial value:
{
  { ".reg", 48 * 4, "general-purpose" },
  { ".reg2", 264, "floating-point" },
  { ".reg-ppc-vmx", 544, "ppc Altivec" },
  { ".reg-ppc-vsx", 256, "POWER7 VSX" },
  { NULL, 0}
}
Definition at line 259 of file ppc-linux-tdep.c.
struct frame_unwind ppu2spu_unwind [static]
Initial value:
 {
  ARCH_FRAME,
  default_frame_unwind_stop_reason,
  ppu2spu_this_id,
  ppu2spu_prev_register,
  NULL,
  ppu2spu_sniffer,
  ppu2spu_dealloc_cache,
  ppu2spu_prev_arch,
}
Definition at line 1230 of file ppc-linux-tdep.c.
CORE_ADDR spe_context_cache_address [static]
Definition at line 956 of file ppc-linux-tdep.c.
Referenced by ppc_linux_spe_context(), and ppc_linux_spe_context_lookup().
ptid_t spe_context_cache_ptid [static]
Definition at line 955 of file ppc-linux-tdep.c.
CORE_ADDR spe_context_lm_addr = 0 [static]
Definition at line 952 of file ppc-linux-tdep.c.
Referenced by ppc_linux_spe_context(), and ppc_linux_spe_context_lookup().
struct objfile* spe_context_objfile = NULL [static]
Definition at line 951 of file ppc-linux-tdep.c.
CORE_ADDR spe_context_offset = 0 [static]
Definition at line 953 of file ppc-linux-tdep.c.
Referenced by ppc_linux_spe_context(), and ppc_linux_spe_context_lookup().