GDB (xrefs): /home/stan/gdb/src/gdb/ppc-ravenscar-thread.c File Reference
/home/stan/gdb/src/gdb/ppc-ravenscar-thread.c File Reference
#include "defs.h"
#include "gdbcore.h"
#include "regcache.h"
#include "ppc-tdep.h"
#include "inferior.h"
#include "ravenscar-thread.h"
#include "ppc-ravenscar-thread.h"
Classes
struct ravenscar_reg_info
Defines
#define NO_OFFSET -1
Functions
static void supply_register_at_address (struct regcache *regcache, int regnum, CORE_ADDR register_addr)
static int register_in_thread_descriptor_p (const struct ravenscar_reg_info *reg_info, int regnum)
static void ppc_ravenscar_generic_fetch_registers (const struct ravenscar_reg_info *reg_info, struct regcache *regcache, int regnum)
static void ppc_ravenscar_generic_prepare_to_store (struct regcache *regcache)
static void ppc_ravenscar_generic_store_registers (const struct ravenscar_reg_info *reg_info, struct regcache *regcache, int regnum)
static void ppc_ravenscar_powerpc_fetch_registers (struct regcache *regcache, int regnum)
static void ppc_ravenscar_powerpc_store_registers (struct regcache *regcache, int regnum)
void register_ppc_ravenscar_ops (struct gdbarch *gdbarch)
static void ppc_ravenscar_e500_fetch_registers (struct regcache *regcache, int regnum)
static void ppc_ravenscar_e500_store_registers (struct regcache *regcache, int regnum)
void register_e500_ravenscar_ops (struct gdbarch *gdbarch)
Variables
static const int powerpc_context_offsets []
static const int e500_context_offsets []
static struct ravenscar_reg_info ppc_reg_info
static struct ravenscar_arch_ops ppc_ravenscar_powerpc_ops
static struct ravenscar_reg_info e500_reg_info
static struct ravenscar_arch_ops ppc_ravenscar_e500_ops
Define Documentation
#define NO_OFFSET -1
Definition at line 28 of file ppc-ravenscar-thread.c.
Referenced by register_in_thread_descriptor_p().
Function Documentation
static void ppc_ravenscar_e500_fetch_registers (struct regcache * regcache, int regnum) [static]
Definition at line 262 of file ppc-ravenscar-thread.c.
References ppc_ravenscar_generic_fetch_registers().
static void ppc_ravenscar_e500_store_registers (struct regcache * regcache, int regnum) [static]
Definition at line 271 of file ppc-ravenscar-thread.c.
References ppc_ravenscar_generic_store_registers().
static void ppc_ravenscar_generic_fetch_registers (const struct ravenscar_reg_info * reg_info, struct regcache * regcache, int regnum) [static]
Definition at line 147 of file ppc-ravenscar-thread.c.
References ravenscar_reg_info::context_offsets, gdbarch_num_regs(), gdbarch_sp_regnum(), get_regcache_arch(), inferior_ptid, gdbarch::num_regs, ptid_get_tid(), register_in_thread_descriptor_p(), sp_regnum, and supply_register_at_address().
Referenced by ppc_ravenscar_e500_fetch_registers(), and ppc_ravenscar_powerpc_fetch_registers().
static void ppc_ravenscar_generic_prepare_to_store (struct regcache * regcache) [static]
Definition at line 177 of file ppc-ravenscar-thread.c.
static void ppc_ravenscar_generic_store_registers (const struct ravenscar_reg_info * reg_info, struct regcache * regcache, int regnum) [static]
Definition at line 187 of file ppc-ravenscar-thread.c.
References ravenscar_reg_info::context_offsets, get_regcache_arch(), inferior_ptid, ptid_get_tid(), regcache_raw_collect(), register_in_thread_descriptor_p(), register_size(), regnum, ULONGEST, and write_memory().
Referenced by ppc_ravenscar_e500_store_registers(), and ppc_ravenscar_powerpc_store_registers().
static void ppc_ravenscar_powerpc_fetch_registers (struct regcache * regcache, int regnum) [static]
Definition at line 219 of file ppc-ravenscar-thread.c.
References ppc_ravenscar_generic_fetch_registers().
static void ppc_ravenscar_powerpc_store_registers (struct regcache * regcache, int regnum) [static]
Definition at line 228 of file ppc-ravenscar-thread.c.
References ppc_ravenscar_generic_store_registers().
void register_e500_ravenscar_ops (struct gdbarch * gdbarch)
Definition at line 288 of file ppc-ravenscar-thread.c.
References set_gdbarch_ravenscar_ops().
Referenced by rs6000_gdbarch_init().
static int register_in_thread_descriptor_p (const struct ravenscar_reg_info * reg_info, int regnum) [static]
Definition at line 135 of file ppc-ravenscar-thread.c.
References ravenscar_reg_info::context_offsets, and NO_OFFSET.
Referenced by ppc_ravenscar_generic_fetch_registers(), and ppc_ravenscar_generic_store_registers().
void register_ppc_ravenscar_ops (struct gdbarch * gdbarch)
Definition at line 245 of file ppc-ravenscar-thread.c.
References set_gdbarch_ravenscar_ops().
Referenced by rs6000_gdbarch_init().
static void supply_register_at_address (struct regcache * regcache, int regnum, CORE_ADDR register_addr) [static]
Definition at line 119 of file ppc-ravenscar-thread.c.
References get_regcache_arch(), read_memory(), regcache_raw_supply(), and register_size().
Referenced by ppc_ravenscar_generic_fetch_registers().
Variable Documentation
const int e500_context_offsets[] [static]
Definition at line 61 of file ppc-ravenscar-thread.c.
struct ravenscar_reg_info e500_reg_info [static]
Initial value:
{
  e500_context_offsets,
  ARRAY_SIZE (e500_context_offsets),
}
Definition at line 252 of file ppc-ravenscar-thread.c.
const int powerpc_context_offsets[] [static]
Initial value:
{
  NO_OFFSET, 0,         4,         NO_OFFSET,
  NO_OFFSET, NO_OFFSET, NO_OFFSET, NO_OFFSET,
  NO_OFFSET, NO_OFFSET, NO_OFFSET, NO_OFFSET,
  NO_OFFSET, 8,         12,        16,
  20,        24,        28,        32,
  36,        40,        44,        48,
  52,        56,        60,        64,
  68,        72,        76,        80,
  NO_OFFSET, NO_OFFSET, NO_OFFSET, NO_OFFSET,
  NO_OFFSET, NO_OFFSET, NO_OFFSET, NO_OFFSET,
  NO_OFFSET, NO_OFFSET, NO_OFFSET, NO_OFFSET,
  NO_OFFSET, NO_OFFSET, 96,        104,
  112,       120,       128,       136,
  144,       152,       160,       168,
  176,       184,       192,       200,
  208,       216,       224,       232,
  88,        NO_OFFSET, 84,        NO_OFFSET,
  NO_OFFSET, NO_OFFSET, 240
}
Definition at line 32 of file ppc-ravenscar-thread.c.
struct ravenscar_arch_ops ppc_ravenscar_e500_ops [static]
Initial value:
{
  ppc_ravenscar_e500_fetch_registers,
  ppc_ravenscar_e500_store_registers,
  ppc_ravenscar_generic_prepare_to_store
}
Definition at line 278 of file ppc-ravenscar-thread.c.
struct ravenscar_arch_ops ppc_ravenscar_powerpc_ops [static]
Initial value:
{
  ppc_ravenscar_powerpc_fetch_registers,
  ppc_ravenscar_powerpc_store_registers,
  ppc_ravenscar_generic_prepare_to_store
}
Definition at line 235 of file ppc-ravenscar-thread.c.
struct ravenscar_reg_info ppc_reg_info [static]
Initial value:
{
  powerpc_context_offsets,
  ARRAY_SIZE (powerpc_context_offsets),
}
Definition at line 209 of file ppc-ravenscar-thread.c.