GDB (xrefs): /home/stan/gdb/src/gdb/ppc64-tdep.c File Reference
/home/stan/gdb/src/gdb/ppc64-tdep.c File Reference
#include "defs.h"
#include "frame.h"
#include "gdbcore.h"
#include "ppc-tdep.h"
#include "ppc64-tdep.h"
#include "elf-bfd.h"
Defines
#define insn_d(opcd, rts, ra, d)
#define insn_ds(opcd, rts, ra, d, xo)
#define insn_xfx(opcd, rts, spr, xo)
#define MAX(a, b) ((a) > (b) ? (a) : (b))
Functions
static CORE_ADDR ppc64_desc_entry_point (struct gdbarch *gdbarch, CORE_ADDR desc)
static CORE_ADDR ppc64_standard_linkage1_target (struct frame_info *frame, CORE_ADDR pc, unsigned int *insn)
static CORE_ADDR ppc64_standard_linkage2_target (struct frame_info *frame, CORE_ADDR pc, unsigned int *insn)
static CORE_ADDR ppc64_standard_linkage3_target (struct frame_info *frame, CORE_ADDR pc, unsigned int *insn)
CORE_ADDR ppc64_skip_trampoline_code (struct frame_info *frame, CORE_ADDR pc)
CORE_ADDR ppc64_convert_from_func_ptr_addr (struct gdbarch *gdbarch, CORE_ADDR addr, struct target_ops *targ)
void ppc64_elf_make_msymbol_special (asymbol *sym, struct minimal_symbol *msym)
Variables
static struct ppc_insn_pattern ppc64_standard_linkage1 []
static struct ppc_insn_pattern ppc64_standard_linkage2 []
static struct ppc_insn_pattern ppc64_standard_linkage3 []
Define Documentation
#define insn_d (opcd, rts, ra, d)
Value:
((((opcd) & 0x3f) << 26)                      \
   | (((rts) & 0x1f) << 21)                     \
   | (((ra) & 0x1f) << 16)                      \
   | ((d) & 0xffff))
Definition at line 31 of file ppc64-tdep.c.
#define insn_ds (opcd, rts, ra, d, xo)
Value:
((((opcd) & 0x3f) << 26)                      \
   | (((rts) & 0x1f) << 21)                     \
   | (((ra) & 0x1f) << 16)                      \
   | ((d) & 0xfffc)                             \
   | ((xo) & 0x3))
Definition at line 37 of file ppc64-tdep.c.
#define insn_xfx (opcd, rts, spr, xo)
Value:
((((opcd) & 0x3f) << 26)                      \
   | (((rts) & 0x1f) << 21)                     \
   | (((spr) & 0x1f) << 16)                     \
   | (((spr) & 0x3e0) << 6)                     \
   | (((xo) & 0x3ff) << 1))
Definition at line 44 of file ppc64-tdep.c.
#define MAX (a, b) ((a) > (b) ? (a) : (b))
Referenced by ppc64_skip_trampoline_code().
Function Documentation
CORE_ADDR ppc64_convert_from_func_ptr_addr (struct gdbarch * gdbarch, CORE_ADDR addr, struct target_ops * targ)
Definition at line 353 of file ppc64-tdep.c.
References target_section::addr, extract_unsigned_integer(), gdbarch_byte_order(), target_section_by_addr(), and target_section::the_bfd_section.
Referenced by ppc_linux_init_abi(), and ppcfbsd_init_abi().
static CORE_ADDR ppc64_desc_entry_point (struct gdbarch * gdbarch, CORE_ADDR desc) [static]
Definition at line 55 of file ppc64-tdep.c.
References gdbarch_byte_order(), and read_memory_unsigned_integer().
Referenced by ppc64_standard_linkage1_target(), ppc64_standard_linkage2_target(), and ppc64_standard_linkage3_target().
void ppc64_elf_make_msymbol_special (asymbol * sym, struct minimal_symbol * msym)
Definition at line 402 of file ppc64-tdep.c.
References SET_MSYMBOL_SIZE.
Referenced by ppc_linux_init_abi(), and ppcfbsd_init_abi().
CORE_ADDR ppc64_skip_trampoline_code (struct frame_info * frame, CORE_ADDR pc)
Definition at line 300 of file ppc64-tdep.c.
References find_solib_trampoline_target(), MAX, gdbarch_tdep::pc, ppc64_standard_linkage1_target(), ppc64_standard_linkage2_target(), ppc64_standard_linkage3_target(), and ppc_insns_match_pattern().
Referenced by ppc_linux_init_abi(), and ppcfbsd_init_abi().
static CORE_ADDR ppc64_standard_linkage1_target (struct frame_info * frame, CORE_ADDR pc, unsigned int * insn) [static]
Definition at line 240 of file ppc64-tdep.c.
References gdbarch_tdep(), get_frame_arch(), get_frame_register_unsigned(), ppc64_desc_entry_point(), gdbarch_tdep::ppc_gp0_regnum, ppc_insn_d_field(), and ppc_insn_ds_field().
Referenced by ppc64_skip_trampoline_code().
static CORE_ADDR ppc64_standard_linkage2_target (struct frame_info * frame, CORE_ADDR pc, unsigned int * insn) [static]
Definition at line 259 of file ppc64-tdep.c.
References gdbarch_tdep(), get_frame_arch(), get_frame_register_unsigned(), ppc64_desc_entry_point(), gdbarch_tdep::ppc_gp0_regnum, ppc_insn_d_field(), and ppc_insn_ds_field().
Referenced by ppc64_skip_trampoline_code().
static CORE_ADDR ppc64_standard_linkage3_target (struct frame_info * frame, CORE_ADDR pc, unsigned int * insn) [static]
Definition at line 278 of file ppc64-tdep.c.
References gdbarch_tdep(), get_frame_arch(), get_frame_register_unsigned(), ppc64_desc_entry_point(), gdbarch_tdep::ppc_gp0_regnum, and ppc_insn_ds_field().
Referenced by ppc64_skip_trampoline_code().
Variable Documentation
struct ppc_insn_pattern ppc64_standard_linkage1[] [static]
Definition at line 67 of file ppc64-tdep.c.
struct ppc_insn_pattern ppc64_standard_linkage2[] [static]
Definition at line 106 of file ppc64-tdep.c.
struct ppc_insn_pattern ppc64_standard_linkage3[] [static]
Definition at line 149 of file ppc64-tdep.c.