GDB (xrefs): /home/stan/gdb/src/gdb/ppcfbsd-tdep.c File Reference
/home/stan/gdb/src/gdb/ppcfbsd-tdep.c File Reference
#include "defs.h"
#include "arch-utils.h"
#include "frame.h"
#include "gdbcore.h"
#include "frame-unwind.h"
#include "gdbtypes.h"
#include "osabi.h"
#include "regcache.h"
#include "regset.h"
#include "symtab.h"
#include "target.h"
#include "trad-frame.h"
#include "gdb_assert.h"
#include "gdb_string.h"
#include "ppc-tdep.h"
#include "ppc64-tdep.h"
#include "ppcfbsd-tdep.h"
#include "solib-svr4.h"
Functions
struct regset * ppc_fbsd_gregset (int wordsize)
struct regset * ppc_fbsd_fpregset (void)
static struct regset * ppcfbsd_regset_from_core_section (struct gdbarch *gdbarch, const char *sect_name, size_t sect_size)
static int ppcfbsd_sigtramp_frame_sniffer (const struct frame_unwind *self, struct frame_info *this_frame, void **this_cache)
static struct trad_frame_cache * ppcfbsd_sigtramp_frame_cache (struct frame_info *this_frame, void **this_cache)
static void ppcfbsd_sigtramp_frame_this_id (struct frame_info *this_frame, void **this_cache, struct frame_id *this_id)
static struct value * ppcfbsd_sigtramp_frame_prev_register (struct frame_info *this_frame, void **this_cache, int regnum)
static enum return_value_convention ppcfbsd_return_value (struct gdbarch *gdbarch, struct value *function, struct type *valtype, struct regcache *regcache, gdb_byte *readbuf, const gdb_byte *writebuf)
static void ppcfbsd_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
void _initialize_ppcfbsd_tdep (void)
Variables
static struct ppc_reg_offsets ppc32_fbsd_reg_offsets
static struct ppc_reg_offsets ppc64_fbsd_reg_offsets
static struct regset ppc32_fbsd_gregset
static struct regset ppc64_fbsd_gregset
static struct regset ppc32_fbsd_fpregset
static const int ppcfbsd_page_size = 4096
static const int ppcfbsd_sigreturn_offset []
static struct frame_unwind ppcfbsd_sigtramp_frame_unwind
Function Documentation
void _initialize_ppcfbsd_tdep (void)
struct regset* ppc_fbsd_fpregset (void) [read]
Definition at line 131 of file ppcfbsd-tdep.c.
References ppc32_fbsd_fpregset.
Referenced by fill_fpregset(), ppcfbsd_fetch_inferior_registers(), and supply_fpregset().
struct regset* ppc_fbsd_gregset (int wordsize) [read]
Definition at line 125 of file ppcfbsd-tdep.c.
References ppc32_fbsd_gregset.
Referenced by fill_gregset(), and supply_gregset().
static void ppcfbsd_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch) [static]
Definition at line 304 of file ppcfbsd-tdep.c.
References find_solib_trampoline_target(), floatformats_ieee_double, frame_unwind_append_unwinder(), gdbarch_tdep(), ppc64_convert_from_func_ptr_addr(), ppc64_elf_make_msymbol_special(), ppc64_skip_trampoline_code(), ppcfbsd_regset_from_core_section(), ppcfbsd_return_value(), set_gdbarch_convert_from_func_ptr_addr(), set_gdbarch_elf_make_msymbol_special(), set_gdbarch_fetch_tls_load_module_address(), set_gdbarch_gcore_bfd_target(), set_gdbarch_long_double_bit(), set_gdbarch_long_double_format(), set_gdbarch_regset_from_core_section(), set_gdbarch_return_value(), set_gdbarch_skip_trampoline_code(), set_solib_svr4_fetch_link_map_offsets(), svr4_fetch_objfile_link_map(), svr4_ilp32_fetch_link_map_offsets(), svr4_lp64_fetch_link_map_offsets(), and gdbarch_tdep::wordsize.
static struct regset* ppcfbsd_regset_from_core_section (struct gdbarch * gdbarch, const char * sect_name, size_t sect_size) [static, read]
Definition at line 140 of file ppcfbsd-tdep.c.
References gdbarch_tdep(), ppc32_fbsd_fpregset, ppc32_fbsd_gregset, ppc64_fbsd_gregset, and gdbarch_tdep::wordsize.
Referenced by ppcfbsd_init_abi().
static enum return_value_convention ppcfbsd_return_value (struct gdbarch * gdbarch, struct value * function, struct type * valtype, struct regcache * regcache, gdb_byte * readbuf, const gdb_byte * writebuf) [static]
Definition at line 294 of file ppcfbsd-tdep.c.
References ppc_sysv_abi_broken_return_value().
Referenced by ppcfbsd_init_abi().
static struct trad_frame_cache* ppcfbsd_sigtramp_frame_cache (struct frame_info * this_frame, void ** this_cache) [static, read]
Definition at line 218 of file ppcfbsd-tdep.c.
References frame_id_build(), func, gdbarch_byte_order(), gdbarch_pc_regnum(), gdbarch_sp_regnum(), gdbarch_tdep(), get_frame_arch(), get_frame_pc(), get_frame_register_unsigned(), gdbarch_tdep::ppc_cr_regnum, gdbarch_tdep::ppc_ctr_regnum, gdbarch_tdep::ppc_gp0_regnum, PPC_INSN_SIZE, gdbarch_tdep::ppc_lr_regnum, ppc_num_gprs, gdbarch_tdep::ppc_xer_regnum, ppcfbsd_page_size, regnum, safe_frame_unwind_memory(), trad_frame_cache_zalloc(), trad_frame_set_id(), trad_frame_set_reg_addr(), and gdbarch_tdep::wordsize.
Referenced by ppcfbsd_sigtramp_frame_prev_register(), and ppcfbsd_sigtramp_frame_this_id().
static struct value* ppcfbsd_sigtramp_frame_prev_register (struct frame_info * this_frame, void ** this_cache, int regnum) [static, read]
Definition at line 275 of file ppcfbsd-tdep.c.
References ppcfbsd_sigtramp_frame_cache(), and trad_frame_get_register().
static int ppcfbsd_sigtramp_frame_sniffer (const struct frame_unwind * self, struct frame_info * this_frame, void ** this_cache) [static]
Definition at line 170 of file ppcfbsd-tdep.c.
References gdbarch::byte_order, extract_unsigned_integer(), find_pc_partial_function(), gdbarch_byte_order(), get_frame_arch(), get_frame_pc(), name, offset, PPC_INSN_SIZE, ppcfbsd_page_size, ppcfbsd_sigreturn_offset, and safe_frame_unwind_memory().
static void ppcfbsd_sigtramp_frame_this_id (struct frame_info * this_frame, void ** this_cache, struct frame_id * this_id) [static]
Definition at line 265 of file ppcfbsd-tdep.c.
References ppcfbsd_sigtramp_frame_cache(), and trad_frame_get_id().
Variable Documentation
struct regset ppc32_fbsd_fpregset [static]
Initial value:
 {
  &ppc32_fbsd_reg_offsets,
  ppc_supply_fpregset,
  ppc_collect_fpregset
}
Definition at line 118 of file ppcfbsd-tdep.c.
Referenced by ppc_fbsd_fpregset(), and ppcfbsd_regset_from_core_section().
struct regset ppc32_fbsd_gregset [static]
Initial value:
 {
  &ppc32_fbsd_reg_offsets,
  ppc_supply_gregset,
  ppc_collect_gregset,
  NULL
}
Definition at line 100 of file ppcfbsd-tdep.c.
Referenced by ppc_fbsd_gregset(), and ppcfbsd_regset_from_core_section().
struct ppc_reg_offsets ppc32_fbsd_reg_offsets [static]
Initial value:
  {
             0,
              4,
               4,
             144,
             -1,
             132,
             128,
            140,
            136,
             -1,
             0,
          256,
            8,
  }
Definition at line 44 of file ppcfbsd-tdep.c.
struct regset ppc64_fbsd_gregset [static]
Initial value:
 {
  &ppc64_fbsd_reg_offsets,
  ppc_supply_gregset,
  ppc_collect_gregset,
  NULL
}
Definition at line 109 of file ppcfbsd-tdep.c.
Referenced by ppcfbsd_regset_from_core_section().
struct ppc_reg_offsets ppc64_fbsd_reg_offsets [static]
Initial value:
  {
             0,
              8,
               8,
             288,
             -1,
             264,
             256,
            280,
            272,
             -1,
             0,
          256,
            8,
  }
Definition at line 72 of file ppcfbsd-tdep.c.
const int ppcfbsd_page_size = 4096 [static]
Definition at line 158 of file ppcfbsd-tdep.c.
Referenced by ppcfbsd_sigtramp_frame_cache(), and ppcfbsd_sigtramp_frame_sniffer().
const int ppcfbsd_sigreturn_offset[] [static]
Initial value:
 {
  0xc,
  -1
}
Definition at line 162 of file ppcfbsd-tdep.c.
Referenced by ppcfbsd_sigtramp_frame_sniffer().
struct frame_unwind ppcfbsd_sigtramp_frame_unwind [static]
Initial value:
 {
  SIGTRAMP_FRAME,
  default_frame_unwind_stop_reason,
  ppcfbsd_sigtramp_frame_this_id,
  ppcfbsd_sigtramp_frame_prev_register,
  NULL,
  ppcfbsd_sigtramp_frame_sniffer
}
Definition at line 284 of file ppcfbsd-tdep.c.