GDB (xrefs): /home/stan/gdb/src/gdb/ppcnbsd-tdep.c File Reference
/home/stan/gdb/src/gdb/ppcnbsd-tdep.c File Reference
#include "defs.h"
#include "gdbtypes.h"
#include "osabi.h"
#include "regcache.h"
#include "regset.h"
#include "trad-frame.h"
#include "tramp-frame.h"
#include "gdb_assert.h"
#include "gdb_string.h"
#include "ppc-tdep.h"
#include "ppcnbsd-tdep.h"
#include "solib-svr4.h"
Functions
static struct regset * ppcnbsd_regset_from_core_section (struct gdbarch *gdbarch, const char *sect_name, size_t sect_size)
static enum return_value_convention ppcnbsd_return_value (struct gdbarch *gdbarch, struct value *function, struct type *valtype, struct regcache *regcache, gdb_byte *readbuf, const gdb_byte *writebuf)
static void ppcnbsd_sigtramp_cache_init (const struct tramp_frame *self, struct frame_info *this_frame, struct trad_frame_cache *this_cache, CORE_ADDR func)
static void ppcnbsd_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
void _initialize_ppcnbsd_tdep (void)
Variables
struct ppc_reg_offsets ppcnbsd_reg_offsets
struct regset ppcnbsd_gregset
struct regset ppcnbsd_fpregset
static struct tramp_frame ppcnbsd2_sigtramp
static struct tramp_frame ppcnbsd_sigtramp
Function Documentation
void _initialize_ppcnbsd_tdep (void)
static void ppcnbsd_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch) [static]
Definition at line 180 of file ppcnbsd-tdep.c.
References ppcnbsd_regset_from_core_section(), ppcnbsd_return_value(), set_gdbarch_regset_from_core_section(), set_gdbarch_return_value(), set_solib_svr4_fetch_link_map_offsets(), svr4_ilp32_fetch_link_map_offsets(), and tramp_frame_prepend_unwinder().
static struct regset* ppcnbsd_regset_from_core_section (struct gdbarch * gdbarch, const char * sect_name, size_t sect_size) [static, read]
Definition at line 61 of file ppcnbsd-tdep.c.
References ppcnbsd_fpregset, and ppcnbsd_gregset.
Referenced by ppcnbsd_init_abi().
static enum return_value_convention ppcnbsd_return_value (struct gdbarch * gdbarch, struct value * function, struct type * valtype, struct regcache * regcache, gdb_byte * readbuf, const gdb_byte * writebuf) [static]
Definition at line 79 of file ppcnbsd-tdep.c.
References ppc_sysv_abi_broken_return_value(), RETURN_VALUE_STRUCT_CONVENTION, TYPE_CODE, TYPE_CODE_STRUCT, TYPE_CODE_UNION, TYPE_LENGTH, and TYPE_VECTOR.
Referenced by ppcnbsd_init_abi().
static void ppcnbsd_sigtramp_cache_init (const struct tramp_frame * self, struct frame_info * this_frame, struct trad_frame_cache * this_cache, CORE_ADDR func) [static]
Definition at line 105 of file ppcnbsd-tdep.c.
References frame_id_build(), gdbarch_pc_regnum(), gdbarch_sp_regnum(), gdbarch_tdep(), get_frame_arch(), get_frame_register_unsigned(), gdbarch_tdep::ppc_cr_regnum, gdbarch_tdep::ppc_ctr_regnum, gdbarch_tdep::ppc_gp0_regnum, gdbarch_tdep::ppc_lr_regnum, ppc_num_gprs, gdbarch_tdep::ppc_xer_regnum, ppcnbsd2_sigtramp, regnum, trad_frame_set_id(), trad_frame_set_reg_addr(), and gdbarch_tdep::wordsize.
Variable Documentation
static struct tramp_frame ppcnbsd2_sigtramp [static]
Initial value:
{
  SIGTRAMP_FRAME,
  4,
  {
    { 0x3821fff0, -1 },
    { 0x4e800021, -1 },
    { 0x38610010, -1 },
    { 0x38000127, -1 },
    { 0x44000002, -1 },
    { 0x38000001, -1 },
    { 0x44000002, -1 },
    { TRAMP_SENTINEL_INSN, -1 }
  },
  ppcnbsd_sigtramp_cache_init
}
Definition at line 102 of file ppcnbsd-tdep.c.
Referenced by ppcnbsd_sigtramp_cache_init().
struct regset ppcnbsd_fpregset
Initial value:
{
  &ppcnbsd_reg_offsets,
  ppc_supply_fpregset
}
Definition at line 51 of file ppcnbsd-tdep.c.
Referenced by ppcnbsd_fetch_inferior_registers(), ppcnbsd_regset_from_core_section(), and ppcnbsd_store_inferior_registers().
struct regset ppcnbsd_gregset
Initial value:
{
  &ppcnbsd_reg_offsets,
  ppc_supply_gregset
}
Definition at line 45 of file ppcnbsd-tdep.c.
Referenced by ppcnbsd_fetch_inferior_registers(), ppcnbsd_regset_from_core_section(), and ppcnbsd_store_inferior_registers().
struct ppc_reg_offsets ppcnbsd_reg_offsets
Definition at line 38 of file ppcnbsd-tdep.c.
struct tramp_frame ppcnbsd_sigtramp [static]
Initial value:
{
  SIGTRAMP_FRAME,
  4,
  {
    { 0x3821fff0, -1 },
    { 0x4e800021, -1 },
    { 0x38610018, -1 },
    { 0x38000127, -1 },
    { 0x44000002, -1 },
    { 0x38000001, -1 },
    { 0x44000002, -1 },
    { TRAMP_SENTINEL_INSN, -1 }
  },
  ppcnbsd_sigtramp_cache_init
}
Definition at line 142 of file ppcnbsd-tdep.c.