GDB (xrefs): /home/stan/gdb/src/gdb/ppcnbsd-nat.c File Reference
/home/stan/gdb/src/gdb/ppcnbsd-nat.c File Reference
#include "defs.h"
#include <sys/types.h>
#include <sys/ptrace.h>
#include <machine/reg.h>
#include <machine/frame.h>
#include <machine/pcb.h>
#include "gdbcore.h"
#include "inferior.h"
#include "regcache.h"
#include "gdb_assert.h"
#include "ppc-tdep.h"
#include "ppcnbsd-tdep.h"
#include "bsd-kvm.h"
#include "inf-ptrace.h"
Functions
static int getregs_supplies (struct gdbarch *gdbarch, int regnum)
static int getfpregs_supplies (struct gdbarch *gdbarch, int regnum)
static void ppcnbsd_fetch_inferior_registers (struct target_ops *ops, struct regcache *regcache, int regnum)
static void ppcnbsd_store_inferior_registers (struct target_ops *ops, struct regcache *regcache, int regnum)
static int ppcnbsd_supply_pcb (struct regcache *regcache, struct pcb *pcb)
void _initialize_ppcnbsd_nat (void)
Function Documentation
void _initialize_ppcnbsd_nat (void)
Definition at line 187 of file ppcnbsd-nat.c.
References add_target(), bsd_kvm_add_target(), inf_ptrace_target(), ppcnbsd_fetch_inferior_registers(), ppcnbsd_store_inferior_registers(), ppcnbsd_supply_pcb(), target_ops::to_fetch_registers, and target_ops::to_store_registers.
static int getfpregs_supplies (struct gdbarch * gdbarch, int regnum) [static]
Definition at line 60 of file ppcnbsd-nat.c.
References gdb_assert, gdbarch_tdep(), ppc_floating_point_unit_p(), gdbarch_tdep::ppc_fp0_regnum, gdbarch_tdep::ppc_fpscr_regnum, and ppc_num_fprs.
Referenced by ppcnbsd_fetch_inferior_registers(), and ppcnbsd_store_inferior_registers().
static int getregs_supplies (struct gdbarch * gdbarch, int regnum) [static]
Definition at line 44 of file ppcnbsd-nat.c.
References gdbarch_pc_regnum(), gdbarch_tdep(), gdbarch_tdep::ppc_cr_regnum, gdbarch_tdep::ppc_ctr_regnum, gdbarch_tdep::ppc_gp0_regnum, gdbarch_tdep::ppc_lr_regnum, ppc_num_gprs, and gdbarch_tdep::ppc_xer_regnum.
Referenced by ppcnbsd_fetch_inferior_registers(), and ppcnbsd_store_inferior_registers().
static void ppcnbsd_fetch_inferior_registers (struct target_ops * ops, struct regcache * regcache, int regnum) [static]
Definition at line 82 of file ppcnbsd-nat.c.
References _, get_regcache_arch(), getfpregs_supplies(), getregs_supplies(), inferior_ptid, perror_with_name(), ppc_supply_fpregset(), ppc_supply_gregset(), ppcnbsd_fpregset, ppcnbsd_gregset, ptid_get_pid(), ptrace(), and PTRACE_TYPE_ARG3.
Referenced by _initialize_ppcnbsd_nat().
static void ppcnbsd_store_inferior_registers (struct target_ops * ops, struct regcache * regcache, int regnum) [static]
Definition at line 113 of file ppcnbsd-nat.c.
References _, get_regcache_arch(), getfpregs_supplies(), getregs_supplies(), inferior_ptid, perror_with_name(), ppc_collect_fpregset(), ppc_collect_gregset(), ppcnbsd_fpregset, ppcnbsd_gregset, ptid_get_pid(), ptrace(), and PTRACE_TYPE_ARG3.
Referenced by _initialize_ppcnbsd_nat().
static int ppcnbsd_supply_pcb (struct regcache * regcache, struct pcb * pcb) [static]
Definition at line 152 of file ppcnbsd-nat.c.
References gdbarch_pc_regnum(), gdbarch_tdep(), get_regcache_arch(), gdbarch_tdep::ppc_cr_regnum, gdbarch_tdep::ppc_gp0_regnum, gdbarch_tdep::ppc_lr_regnum, read_memory(), and regcache_raw_supply().
Referenced by _initialize_ppcnbsd_nat().