GDB (xrefs): /home/stan/gdb/src/gdb/ppcobsd-tdep.h File Reference
/home/stan/gdb/src/gdb/ppcobsd-tdep.h File Reference
#include <stddef.h>
Functions
void ppcobsd_supply_gregset (const struct regset *regset, struct regcache *regcache, int regnum, const void *gregs, size_t len)
void ppcobsd_collect_gregset (const struct regset *regset, const struct regcache *regcache, int regnum, void *gregs, size_t len)
Variables
struct ppc_reg_offsets ppcobsd_reg_offsets
struct ppc_reg_offsets ppcobsd_fpreg_offsets
struct regset ppcobsd_gregset
struct regset ppcobsd_fpregset
Function Documentation
void ppcobsd_collect_gregset (const struct regset * regset, const struct regcache * regcache, int regnum, void * gregs, size_t len)
Definition at line 64 of file ppcobsd-tdep.c.
References ppc_collect_fpregset(), and ppc_collect_gregset().
void ppcobsd_supply_gregset (const struct regset * regset, struct regcache * regcache, int regnum, const void * gregs, size_t len)
Definition at line 50 of file ppcobsd-tdep.c.
References ppc_supply_fpregset(), and ppc_supply_gregset().
Variable Documentation
struct ppc_reg_offsets ppcobsd_fpreg_offsets
Definition at line 40 of file ppcobsd-tdep.c.
Referenced by _initialize_ppcobsd_nat().
struct regset ppcobsd_fpregset
Definition at line 80 of file ppcobsd-tdep.c.
Referenced by ppcobsd_fetch_registers(), and ppcobsd_store_registers().
struct regset ppcobsd_gregset
Definition at line 74 of file ppcobsd-tdep.c.
Referenced by ppcobsd_fetch_registers(), ppcobsd_regset_from_core_section(), and ppcobsd_store_registers().
struct ppc_reg_offsets ppcobsd_reg_offsets
Definition at line 39 of file ppcobsd-tdep.c.
Referenced by _initialize_ppcobsd_nat().