GDB (xrefs): /home/stan/gdb/src/gdb/ppcobsd-tdep.c File Reference
/home/stan/gdb/src/gdb/ppcobsd-tdep.c File Reference
#include "defs.h"
#include "arch-utils.h"
#include "frame.h"
#include "frame-unwind.h"
#include "gdbtypes.h"
#include "osabi.h"
#include "regcache.h"
#include "regset.h"
#include "symtab.h"
#include "trad-frame.h"
#include "gdb_assert.h"
#include "gdb_string.h"
#include "ppc-tdep.h"
#include "ppcobsd-tdep.h"
#include "solib-svr4.h"
Defines
#define GDB_OSABI_NETBSD_CORE GDB_OSABI_OPENBSD_ELF
Functions
void ppcobsd_supply_gregset (const struct regset *regset, struct regcache *regcache, int regnum, const void *gregs, size_t len)
void ppcobsd_collect_gregset (const struct regset *regset, const struct regcache *regcache, int regnum, void *gregs, size_t len)
static struct regset * ppcobsd_regset_from_core_section (struct gdbarch *gdbarch, const char *sect_name, size_t sect_size)
static int ppcobsd_sigtramp_frame_sniffer (const struct frame_unwind *self, struct frame_info *this_frame, void **this_cache)
static struct trad_frame_cache * ppcobsd_sigtramp_frame_cache (struct frame_info *this_frame, void **this_cache)
static void ppcobsd_sigtramp_frame_this_id (struct frame_info *this_frame, void **this_cache, struct frame_id *this_id)
static struct value * ppcobsd_sigtramp_frame_prev_register (struct frame_info *this_frame, void **this_cache, int regnum)
static void ppcobsd_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
static enum gdb_osabi ppcobsd_core_osabi_sniffer (bfd *abfd)
void _initialize_ppcobsd_tdep (void)
Variables
struct ppc_reg_offsets ppcobsd_reg_offsets
struct ppc_reg_offsets ppcobsd_fpreg_offsets
struct regset ppcobsd_gregset
struct regset ppcobsd_fpregset
static const int ppcobsd_page_size = 4096
static const int ppcobsd_sigreturn_offset []
static struct frame_unwind ppcobsd_sigtramp_frame_unwind
Define Documentation
#define GDB_OSABI_NETBSD_CORE GDB_OSABI_OPENBSD_ELF
Definition at line 272 of file ppcobsd-tdep.c.
Referenced by ppcobsd_core_osabi_sniffer().
Function Documentation
void _initialize_ppcobsd_tdep (void)
void ppcobsd_collect_gregset (const struct regset * regset, const struct regcache * regcache, int regnum, void * gregs, size_t len)
Definition at line 64 of file ppcobsd-tdep.c.
References ppc_collect_fpregset(), and ppc_collect_gregset().
static enum gdb_osabi ppcobsd_core_osabi_sniffer (bfd * abfd) [static]
Definition at line 275 of file ppcobsd-tdep.c.
References GDB_OSABI_NETBSD_CORE, and GDB_OSABI_UNKNOWN.
static void ppcobsd_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch) [static]
Definition at line 250 of file ppcobsd-tdep.c.
References floatformats_ieee_double, frame_unwind_append_unwinder(), ppc_sysv_abi_broken_return_value(), ppcobsd_regset_from_core_section(), set_gdbarch_long_double_bit(), set_gdbarch_long_double_format(), set_gdbarch_regset_from_core_section(), set_gdbarch_return_value(), set_solib_svr4_fetch_link_map_offsets(), and svr4_ilp32_fetch_link_map_offsets().
static struct regset* ppcobsd_regset_from_core_section (struct gdbarch * gdbarch, const char * sect_name, size_t sect_size) [static, read]
Definition at line 90 of file ppcobsd-tdep.c.
References ppcobsd_gregset.
Referenced by ppcobsd_init_abi().
static struct trad_frame_cache* ppcobsd_sigtramp_frame_cache (struct frame_info * this_frame, void ** this_cache) [static, read]
Definition at line 166 of file ppcobsd-tdep.c.
References extract_unsigned_integer(), frame_id_build(), func, gdbarch_byte_order(), gdbarch_pc_regnum(), gdbarch_sp_regnum(), gdbarch_tdep(), get_frame_arch(), get_frame_pc(), get_frame_register_unsigned(), gdbarch_tdep::ppc_cr_regnum, gdbarch_tdep::ppc_ctr_regnum, gdbarch_tdep::ppc_gp0_regnum, PPC_INSN_SIZE, gdbarch_tdep::ppc_lr_regnum, ppc_num_gprs, gdbarch_tdep::ppc_xer_regnum, ppcobsd_page_size, regnum, safe_frame_unwind_memory(), trad_frame_cache_zalloc(), trad_frame_set_id(), trad_frame_set_reg_addr(), and gdbarch_tdep::wordsize.
Referenced by ppcobsd_sigtramp_frame_prev_register(), and ppcobsd_sigtramp_frame_this_id().
static struct value* ppcobsd_sigtramp_frame_prev_register (struct frame_info * this_frame, void ** this_cache, int regnum) [static, read]
Definition at line 230 of file ppcobsd-tdep.c.
References ppcobsd_sigtramp_frame_cache(), and trad_frame_get_register().
static int ppcobsd_sigtramp_frame_sniffer (const struct frame_unwind * self, struct frame_info * this_frame, void ** this_cache) [static]
Definition at line 124 of file ppcobsd-tdep.c.
References gdbarch::byte_order, extract_unsigned_integer(), find_pc_partial_function(), gdbarch_byte_order(), get_frame_arch(), get_frame_pc(), name, offset, PPC_INSN_SIZE, ppcobsd_page_size, ppcobsd_sigreturn_offset, and safe_frame_unwind_memory().
static void ppcobsd_sigtramp_frame_this_id (struct frame_info * this_frame, void ** this_cache, struct frame_id * this_id) [static]
Definition at line 220 of file ppcobsd-tdep.c.
References ppcobsd_sigtramp_frame_cache(), and trad_frame_get_id().
void ppcobsd_supply_gregset (const struct regset * regset, struct regcache * regcache, int regnum, const void * gregs, size_t len)
Definition at line 50 of file ppcobsd-tdep.c.
References ppc_supply_fpregset(), and ppc_supply_gregset().
Variable Documentation
struct ppc_reg_offsets ppcobsd_fpreg_offsets
Definition at line 40 of file ppcobsd-tdep.c.
Referenced by _initialize_ppcobsd_nat().
struct regset ppcobsd_fpregset
Initial value:
{
  &ppcobsd_fpreg_offsets,
  ppc_supply_fpregset
}
Definition at line 80 of file ppcobsd-tdep.c.
Referenced by ppcobsd_fetch_registers(), and ppcobsd_store_registers().
struct regset ppcobsd_gregset
Initial value:
{
  &ppcobsd_reg_offsets,
  ppcobsd_supply_gregset
}
Definition at line 74 of file ppcobsd-tdep.c.
Referenced by ppcobsd_fetch_registers(), ppcobsd_regset_from_core_section(), and ppcobsd_store_registers().
const int ppcobsd_page_size = 4096 [static]
Definition at line 114 of file ppcobsd-tdep.c.
Referenced by ppcobsd_sigtramp_frame_cache(), and ppcobsd_sigtramp_frame_sniffer().
struct ppc_reg_offsets ppcobsd_reg_offsets
Definition at line 39 of file ppcobsd-tdep.c.
Referenced by _initialize_ppcobsd_nat().
const int ppcobsd_sigreturn_offset[] [static]
Initial value:
 {
  0x98,
  0x0c,
  -1
}
Definition at line 117 of file ppcobsd-tdep.c.
Referenced by ppcobsd_sigtramp_frame_sniffer().
struct frame_unwind ppcobsd_sigtramp_frame_unwind [static]
Initial value:
 {
  SIGTRAMP_FRAME,
  default_frame_unwind_stop_reason,
  ppcobsd_sigtramp_frame_this_id,
  ppcobsd_sigtramp_frame_prev_register,
  NULL,
  ppcobsd_sigtramp_frame_sniffer
}
Definition at line 239 of file ppcobsd-tdep.c.