GDB (xrefs): /home/stan/gdb/src/gdb/ppcobsd-nat.c File Reference
/home/stan/gdb/src/gdb/ppcobsd-nat.c File Reference
#include "defs.h"
#include "gdbcore.h"
#include "inferior.h"
#include "regcache.h"
#include "gdb_assert.h"
#include <stddef.h>
#include <sys/types.h>
#include <sys/ptrace.h>
#include <sys/signal.h>
#include <machine/frame.h>
#include <machine/pcb.h>
#include <machine/reg.h>
#include "ppc-tdep.h"
#include "ppcobsd-tdep.h"
#include "inf-ptrace.h"
#include "bsd-kvm.h"
Functions
static void ppcobsd_fetch_registers (struct target_ops *ops, struct regcache *regcache, int regnum)
static void ppcobsd_store_registers (struct target_ops *ops, struct regcache *regcache, int regnum)
static int ppcobsd_supply_pcb (struct regcache *regcache, struct pcb *pcb)
void _initialize_ppcobsd_nat (void)
Function Documentation
void _initialize_ppcobsd_nat (void)
Definition at line 194 of file ppcobsd-nat.c.
References add_target(), bsd_kvm_add_target(), ppc_reg_offsets::cr_offset, ppc_reg_offsets::ctr_offset, ppc_reg_offsets::f0_offset, ppc_reg_offsets::fpscr_offset, ppc_reg_offsets::fpscr_size, ppc_reg_offsets::gpr_size, inf_ptrace_target(), ppc_reg_offsets::lr_offset, ppc_reg_offsets::mq_offset, ppc_reg_offsets::pc_offset, ppcobsd_fetch_registers(), ppcobsd_fpreg_offsets, ppcobsd_reg_offsets, ppcobsd_store_registers(), ppcobsd_supply_pcb(), cleanup_check::ps, ppc_reg_offsets::ps_offset, ppc_reg_offsets::r0_offset, target_ops::to_fetch_registers, target_ops::to_store_registers, ppc_reg_offsets::vr0_offset, ppc_reg_offsets::vrsave_offset, ppc_reg_offsets::vscr_offset, ppc_reg_offsets::xer_offset, and ppc_reg_offsets::xr_size.
static void ppcobsd_fetch_registers (struct target_ops * ops, struct regcache * regcache, int regnum) [static]
Definition at line 75 of file ppcobsd-nat.c.
References _, get_regcache_arch(), getfpregs_supplies(), inferior_ptid, perror_with_name(), ppc_supply_fpregset(), ppc_supply_gregset(), ppcobsd_fpregset, ppcobsd_gregset, ptid_get_pid(), ptrace(), and PTRACE_TYPE_ARG3.
Referenced by _initialize_ppcobsd_nat().
static void ppcobsd_store_registers (struct target_ops * ops, struct regcache * regcache, int regnum) [static]
Definition at line 111 of file ppcobsd-nat.c.
References _, get_regcache_arch(), getfpregs_supplies(), inferior_ptid, perror_with_name(), ppc_collect_fpregset(), ppc_collect_gregset(), ppcobsd_fpregset, ppcobsd_gregset, ptid_get_pid(), ptrace(), and PTRACE_TYPE_ARG3.
Referenced by _initialize_ppcobsd_nat().
static int ppcobsd_supply_pcb (struct regcache * regcache, struct pcb * pcb) [static]
Definition at line 153 of file ppcobsd-nat.c.
References gdbarch_pc_regnum(), gdbarch_sp_regnum(), gdbarch_tdep(), get_regcache_arch(), gdbarch_tdep::ppc_cr_regnum, gdbarch_tdep::ppc_gp0_regnum, read_memory(), regcache_raw_supply(), and regnum.
Referenced by _initialize_ppcobsd_nat().