GDB (xrefs): /home/stan/gdb/src/gdb/printcmd.c File Reference
/home/stan/gdb/src/gdb/printcmd.c File Reference
#include "defs.h"
#include "gdb_string.h"
#include "frame.h"
#include "symtab.h"
#include "gdbtypes.h"
#include "value.h"
#include "language.h"
#include "expression.h"
#include "gdbcore.h"
#include "gdbcmd.h"
#include "target.h"
#include "breakpoint.h"
#include "demangle.h"
#include "gdb-demangle.h"
#include "valprint.h"
#include "annotate.h"
#include "symfile.h"
#include "objfiles.h"
#include "completer.h"
#include "ui-out.h"
#include "gdb_assert.h"
#include "block.h"
#include "disasm.h"
#include "dfp.h"
#include "exceptions.h"
#include "observer.h"
#include "solist.h"
#include "parser-defs.h"
#include "charset.h"
#include "arch-utils.h"
#include "cli/cli-utils.h"
#include "format.h"
#include "source.h"
Classes
struct format_data
struct display
Defines
#define ALL_DISPLAYS(B) for (B = display_chain; B; B = B->next)
#define ALL_DISPLAYS_SAFE(B, TMP)
Functions
static void show_max_symbolic_offset (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static void show_print_symbol_filename (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
void _initialize_printcmd (void)
static void do_one_display (struct display *)
static struct format_data decode_format (const char **string_ptr, int oformat, int osize)
static void print_formatted (struct value *val, int size, const struct value_print_options *options, struct ui_file *stream)
static struct type * float_type_from_length (struct type *type)
void print_scalar_formatted (const void *valaddr, struct type *type, const struct value_print_options *options, int size, struct ui_file *stream)
void set_next_address (struct gdbarch *gdbarch, CORE_ADDR addr)
int print_address_symbolic (struct gdbarch *gdbarch, CORE_ADDR addr, struct ui_file *stream, int do_demangle, char *leadin)
int build_address_symbolic (struct gdbarch *gdbarch, CORE_ADDR addr, int do_demangle, char **name, int *offset, char **filename, int *line, int *unmapped)
void print_address (struct gdbarch *gdbarch, CORE_ADDR addr, struct ui_file *stream)
const char * pc_prefix (CORE_ADDR addr)
int print_address_demangle (const struct value_print_options *opts, struct gdbarch *gdbarch, CORE_ADDR addr, struct ui_file *stream, int do_demangle)
static void do_examine (struct format_data fmt, struct gdbarch *gdbarch, CORE_ADDR addr)
static void validate_format (struct format_data fmt, char *cmdname)
static void print_command_1 (const char *exp, int voidprint)
static void print_command (char *exp, int from_tty)
static void call_command (char *exp, int from_tty)
static void output_command (char *exp, int from_tty)
void output_command_const (const char *exp, int from_tty)
static void set_command (char *exp, int from_tty)
static void sym_info (char *arg, int from_tty)
static void address_info (char *exp, int from_tty)
static void x_command (char *exp, int from_tty)
static void display_command (char *arg, int from_tty)
static void free_display (struct display *d)
void clear_displays (void)
static void delete_display (struct display *display)
static void map_display_numbers (char *args, void(*function)(struct display *, void *), void *data)
static void do_delete_display (struct display *d, void *data)
static void undisplay_command (char *args, int from_tty)
void do_displays (void)
void disable_display (int num)
void disable_current_display (void)
static void display_info (char *ignore, int from_tty)
static void do_enable_disable_display (struct display *d, void *data)
static void enable_disable_display_command (char *args, int from_tty, int enable)
static void enable_display_command (char *args, int from_tty)
static void disable_display_command (char *args, int from_tty)
static void clear_dangling_display_expressions (struct so_list *solib)
void print_variable_and_value (const char *name, struct symbol *var, struct frame_info *frame, struct ui_file *stream, int indent)
static void printf_c_string (struct ui_file *stream, const char *format, struct value *value)
static void printf_wide_c_string (struct ui_file *stream, const char *format, struct value *value)
static void printf_decfloat (struct ui_file *stream, const char *format, struct value *value)
static void printf_pointer (struct ui_file *stream, const char *format, struct value *value)
static void ui_printf (const char *arg, struct ui_file *stream)
static void printf_command (char *arg, int from_tty)
static void eval_command (char *arg, int from_tty)
Variables
static char last_format = 0
static char last_size = 'w'
static struct gdbarch * next_gdbarch
static CORE_ADDR next_address
static int branch_delay_insns
static CORE_ADDR last_examine_address
static struct value * last_examine_value
static unsigned int max_symbolic_offset = UINT_MAX
static int print_symbol_filename = 0
static int current_display_number
static struct display * display_chain
static int display_number
Define Documentation
#define ALL_DISPLAYS (B) for (B = display_chain; B; B = B->next)
Definition at line 166 of file printcmd.c.
Referenced by delete_display(), and enable_disable_display_command().
#define ALL_DISPLAYS_SAFE (B, TMP)
Value:
for (B = display_chain;                 \
       B ? (TMP = B->next, 1): 0;               \
       B = TMP)
Definition at line 169 of file printcmd.c.
Referenced by map_display_numbers().
Function Documentation
void _initialize_printcmd (void)
static void address_info (char * exp, int from_tty) [static]
Definition at line 1199 of file printcmd.c.
References _, BLOCK_START, current_language, error(), fprintf_symbol_filtered(), fputs_filtered(), gdb_assert_not_reached, gdb_stdout, gdbarch_register_name(), get_objfile_arch(), get_selected_block(), language_defn::la_language, language_objc, LOC_ARG, LOC_BLOCK, LOC_COMPUTED, LOC_CONST, LOC_CONST_BYTES, LOC_LABEL, LOC_LOCAL, LOC_OPTIMIZED_OUT, LOC_REF_ARG, LOC_REGISTER, LOC_REGPARM_ADDR, LOC_STATIC, LOC_TYPEDEF, LOC_UNRESOLVED, lookup_bound_minimal_symbol(), lookup_minimal_symbol_and_objfile(), lookup_symbol(), bound_minimal_symbol::minsym, bound_minimal_symbol::objfile, obj_section::objfile, objfile_name(), overlay_unmapped_address(), paddress(), printf_filtered(), section_is_overlay(), SYMBOL_BLOCK_VALUE, SYMBOL_CLASS, SYMBOL_COMPUTED_OPS, SYMBOL_IS_ARGUMENT, SYMBOL_LINKAGE_NAME, SYMBOL_OBJ_SECTION, SYMBOL_OBJFILE, SYMBOL_PRINT_NAME, SYMBOL_REGISTER_OPS, SYMBOL_SYMTAB, SYMBOL_VALUE, SYMBOL_VALUE_ADDRESS, obj_section::the_bfd_section, field_of_this_result::type, and VAR_DOMAIN.
int build_address_symbolic (struct gdbarch * gdbarch, CORE_ADDR addr, int do_demangle, char ** name, int * offset, char ** filename, int * line, int * unmapped)
Definition at line 626 of file printcmd.c.
References asm_demangle, BLOCK_START, find_pc_overlay(), find_pc_sect_function(), find_pc_sect_line(), gdbarch_addr_bits_remove(), lookup_minimal_symbol_by_pc_section(), max_symbolic_offset, bound_minimal_symbol::minsym, mst_file_text, mst_solib_trampoline, mst_text, mst_text_gnu_ifunc, MSYMBOL_HAS_SIZE, MSYMBOL_SIZE, MSYMBOL_TYPE, overlay_debugging, overlay_mapped_address(), pc_in_unmapped_range(), print_symbol_filename, SYMBOL_BLOCK_VALUE, SYMBOL_LINKAGE_NAME, SYMBOL_PRINT_NAME, SYMBOL_VALUE_ADDRESS, and symtab_to_filename_for_display().
Referenced by dump_insns(), and print_address_symbolic().
static void call_command (char * exp, int from_tty) [static]
Definition at line 1023 of file printcmd.c.
References print_command_1().
static void clear_dangling_display_expressions (struct so_list * solib) [static]
Definition at line 1943 of file printcmd.c.
References display::block, display::exp, exp_uses_objfile(), gdb_assert, lookup_objfile_from_block(), display::next, so_list::objfile, so_list::pspace, display::pspace, objfile::pspace, objfile::separate_debug_objfile_backlink, and xfree().
void clear_displays (void)
Definition at line 1578 of file printcmd.c.
References free_display(), and display::next.
Referenced by clear_symtab_users(), and undisplay_command().
static struct format_data decode_format (const char ** string_ptr, int oformat, int osize) [static, read]
Definition at line 194 of file printcmd.c.
References format_data::count, format_data::format, p, format_data::raw, and format_data::size.
Referenced by display_command(), output_command_const(), print_command_1(), and x_command().
static void delete_display (struct display * display) [static]
Definition at line 1592 of file printcmd.c.
References ALL_DISPLAYS, free_display(), gdb_assert, and display::next.
Referenced by do_delete_display().
void disable_current_display (void)
Definition at line 1851 of file printcmd.c.
References _, current_display_number, disable_display(), fprintf_unfiltered(), and gdb_stderr.
Referenced by normal_stop().
void disable_display (int num)
Definition at line 1837 of file printcmd.c.
References _, display::enabled_p, display::next, display::number, and printf_unfiltered().
Referenced by disable_current_display().
static void disable_display_command (char * args, int from_tty) [static]
Definition at line 1929 of file printcmd.c.
References enable_disable_display_command().
static void display_command (char * arg, int from_tty) [static]
Definition at line 1504 of file printcmd.c.
References format_data::count, current_program_space, decode_format(), display_chain, display_number, do_displays(), do_one_display(), dont_repeat(), display::exp, format_data::format, innermost_block, program_space::next, display::number, parse_expression(), format_data::raw, format_data::size, target_has_execution, tui_active, TUI_FAILURE, tui_set_layout_for_display_command(), and xmalloc().
static void display_info (char * ignore, int from_tty) [static]
Definition at line 1865 of file printcmd.c.
References _, display::block, contained_in(), format_data::count, display::enabled_p, display::exp_string, format_data::format, display::format, gdb_flush(), gdb_stdout, get_selected_block(), display::next, display::number, printf_filtered(), printf_unfiltered(), puts_filtered(), and format_data::size.
Referenced by tui_check_register_values(), tui_display_registers_from(), tui_show_register_group(), and tui_show_registers().
static void do_delete_display (struct display * d, void * data) [static]
Definition at line 1653 of file printcmd.c.
References delete_display().
Referenced by undisplay_command().
void do_displays (void)
Definition at line 1825 of file printcmd.c.
References do_one_display(), and display::next.
Referenced by display_command(), normal_stop(), and tfind_1().
static void do_enable_disable_display (struct display * d, void * data) [static]
Definition at line 1895 of file printcmd.c.
References display::enabled_p.
Referenced by enable_disable_display_command().
static void do_examine (struct format_data fmt, struct gdbarch * gdbarch, CORE_ADDR addr) [static]
Definition at line 807 of file printcmd.c.
References _, branch_delay_insns, builtin_type::builtin_char16, builtin_type::builtin_char32, builtin_type::builtin_int16, builtin_type::builtin_int32, builtin_type::builtin_int64, builtin_type::builtin_int8, builtin_type(), format_data::count, format_data::format, fputs_filtered(), gdb_flush(), gdb_stdout, gdbarch_ptr_bit(), get_formatted_print_options(), internal_error(), last_examine_address, next_address, pc_prefix(), print_address(), print_formatted(), printf_filtered(), QUIT, release_value(), format_data::size, size, value_at_lazy(), value_free(), and warning().
Referenced by do_one_display(), and x_command().
static void do_one_display (struct display * d) [static]
Definition at line 1680 of file printcmd.c.
References _, annotate_display_begin(), annotate_display_end(), annotate_display_expression(), annotate_display_expression_end(), annotate_display_format(), annotate_display_number_end(), annotate_display_value(), display::block, contained_in(), format_data::count, current_display_number, current_program_space, do_cleanups(), do_examine(), display::enabled_p, evaluate_expression(), display::exp, display::exp_string, format_data::format, display::format, fprintf_filtered(), gdb_flush(), gdb_stdout, expression::gdbarch, gdbarch_addr_bits_remove(), get_current_arch(), get_formatted_print_options(), get_selected_block(), innermost_block, make_cleanup_restore_integer(), gdb_exception::message, display::number, parse_expression(), print_formatted(), printf_filtered(), display::pspace, puts_filtered(), format_data::raw, value_print_options::raw, gdb_exception::reason, RETURN_MASK_ALL, RETURN_MASK_ERROR, format_data::size, TRY_CATCH, value_as_address(), warning(), and xfree().
Referenced by display_command(), and do_displays().
static void enable_disable_display_command (char * args, int from_tty, int enable) [static]
Definition at line 1904 of file printcmd.c.
References ALL_DISPLAYS, do_enable_disable_display(), enable, display::enabled_p, and map_display_numbers().
Referenced by disable_display_command(), and enable_display_command().
static void enable_display_command (char * args, int from_tty) [static]
Definition at line 1921 of file printcmd.c.
References enable_disable_display_command().
static void eval_command (char * arg, int from_tty) [static]
Definition at line 2466 of file printcmd.c.
References do_cleanups(), execute_command(), make_cleanup(), make_cleanup_ui_file_delete(), mem_fileopen(), ui_file_xstrdup(), ui_printf(), and xfree().
static struct type* float_type_from_length (struct type * type) [static, read]
Definition at line 344 of file printcmd.c.
References builtin_type::builtin_double, builtin_type::builtin_float, builtin_type::builtin_long_double, builtin_type(), get_type_arch(), type, and TYPE_LENGTH.
Referenced by print_scalar_formatted(), and ui_printf().
static void free_display (struct display * d) [static]
Definition at line 1567 of file printcmd.c.
References display::exp, display::exp_string, and xfree().
Referenced by clear_displays(), and delete_display().
static void map_display_numbers (char * args, void(*)(struct display *, void *) function, void * data) [static]
Definition at line 1615 of file printcmd.c.
References _, ALL_DISPLAYS_SAFE, error_no_arg(), get_number_or_range_state::finished, get_number_or_range(), init_number_or_range(), display::number, p, printf_unfiltered(), get_number_or_range_state::string, and warning().
Referenced by enable_disable_display_command(), and undisplay_command().
static void output_command (char * exp, int from_tty) [static]
Definition at line 1031 of file printcmd.c.
References output_command_const().
void output_command_const (const char * exp, int from_tty)
Definition at line 1039 of file printcmd.c.
References annotate_value_begin(), annotate_value_end(), decode_format(), do_cleanups(), evaluate_expression(), format_data::format, free_current_contents(), gdb_flush(), gdb_stdout, get_formatted_print_options(), make_cleanup(), parse_expression(), print_formatted(), format_data::raw, value_print_options::raw, format_data::size, validate_format(), value_type(), and wrap_here().
Referenced by output_command(), and trace_dump_actions().
const char* pc_prefix (CORE_ADDR addr)
Definition at line 767 of file printcmd.c.
References get_frame_pc_if_available(), get_selected_frame(), and has_stack_frames().
Referenced by do_examine(), and dump_insns().
void print_address (struct gdbarch * gdbarch, CORE_ADDR addr, struct ui_file * stream)
Definition at line 756 of file printcmd.c.
References asm_demangle, fputs_filtered(), paddress(), and print_address_symbolic().
Referenced by dis_asm_print_address(), do_examine(), find_command(), line_info(), print_scalar_formatted(), spu_dis_asm_print_address(), trace_find_line_command(), and tui_disassemble().
int print_address_demangle (const struct value_print_options * opts, struct gdbarch * gdbarch, CORE_ADDR addr, struct ui_file * stream, int do_demangle)
Definition at line 786 of file printcmd.c.
References value_print_options::addressprint, fputs_filtered(), paddress(), and print_address_symbolic().
Referenced by c_val_print(), f_val_print(), generic_val_print(), gnuv3_print_method_ptr(), java_val_print(), pascal_val_print(), and print_function_pointer_address().
int print_address_symbolic (struct gdbarch * gdbarch, CORE_ADDR addr, struct ui_file * stream, int do_demangle, char * leadin)
Definition at line 571 of file printcmd.c.
References build_address_symbolic(), cleanup_chain, do_cleanups(), fprintf_filtered(), fputs_filtered(), free_current_contents(), line, make_cleanup(), name, offset, and print_symbol_filename.
Referenced by gdbtk_load_asm(), print_address(), print_address_demangle(), print_breakpoint_location(), and tui_get_function_from_frame().
static void print_command (char * exp, int from_tty) [static]
Definition at line 1016 of file printcmd.c.
References print_command_1().
static void print_command_1 (const char * exp, int voidprint) [static]
Definition at line 951 of file printcmd.c.
References access_value_history(), annotate_value_begin(), annotate_value_end(), annotate_value_history_begin(), annotate_value_history_end(), annotate_value_history_value(), format_data::count, decode_format(), do_cleanups(), evaluate_expression(), format_data::format, free_current_contents(), gdb_stdout, get_formatted_print_options(), last_format, make_cleanup(), null_cleanup(), parse_expression(), print_formatted(), printf_filtered(), format_data::raw, value_print_options::raw, record_latest_value(), format_data::size, TYPE_CODE, TYPE_CODE_VOID, validate_format(), and value_type().
Referenced by call_command(), and print_command().
static void print_formatted (struct value * val, int size, const struct value_print_options * options, struct ui_file * stream) [static]
Definition at line 287 of file printcmd.c.
References branch_delay_insns, check_typedef(), value_print_options::format, gdb_print_insn(), get_type_arch(), len, lval_memory, next_address, TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_NAMESPACE, TYPE_CODE_REF, TYPE_CODE_STRING, TYPE_CODE_STRUCT, TYPE_CODE_UNION, TYPE_LENGTH, val_print_scalar_formatted(), val_print_string(), value_address(), value_contents_for_printing(), value_embedded_offset(), VALUE_LVAL, value_print(), value_type(), and wrap_here().
Referenced by do_examine(), do_one_display(), output_command_const(), and print_command_1().
void print_scalar_formatted (const void * valaddr, struct type * type, const struct value_print_options * options, int size, struct ui_file * stream)
Definition at line 364 of file printcmd.c.
References _, bits, builtin_type::builtin_true_char, builtin_type::builtin_true_unsigned_char, builtin_type(), gdbarch::byte_order, error(), float_type_from_length(), value_print_options::format, fprintf_filtered(), fputs_filtered(), gdb_assert, gdbarch_addr_bit(), gdbarch_byte_order(), get_type_arch(), HOST_CHAR_BIT, internal_error(), len, LONGEST, print_address(), print_binary_chars(), print_char_chars(), print_decimal_chars(), print_floating(), print_hex_chars(), print_longest(), print_octal_chars(), TYPE_CODE, TYPE_CODE_ENUM, TYPE_CODE_INT, TYPE_CODE_PTR, TYPE_LENGTH, TYPE_UNSIGNED, unpack_long(), unpack_pointer(), value_from_longest(), and value_print().
Referenced by gdb_update_mem(), mi_cmd_data_read_memory(), mips_print_fp_register(), and val_print_scalar_formatted().
void print_variable_and_value (const char * name, struct symbol * var, struct frame_info * frame, struct ui_file * stream, int indent)
Definition at line 1980 of file printcmd.c.
References common_val_print(), current_language, value_print_options::deref_ref, fprintf_filtered(), get_user_print_options(), gdb_exception::message, n_spaces(), read_var_value(), gdb_exception::reason, RETURN_MASK_ERROR, SYMBOL_PRINT_NAME, and TRY_CATCH.
Referenced by do_print_variable_and_value().
static void printf_c_string (struct ui_file * stream, const char * format, struct value * value) [static]
Definition at line 2015 of file printcmd.c.
References fprintf_filtered(), QUIT, read_memory(), and value_as_address().
Referenced by ui_printf().
static void printf_command (char * arg, int from_tty) [static]
Definition at line 2458 of file printcmd.c.
References gdb_stdout, and ui_printf().
static void printf_decfloat (struct ui_file * stream, const char * format, struct value * value) [static]
Definition at line 2098 of file printcmd.c.
References builtin_type::builtin_decdouble, builtin_type::builtin_decfloat, builtin_type::builtin_declong, builtin_type(), gdbarch::byte_order, decimal_convert(), decimal_from_string(), decimal_to_string(), fprintf_filtered(), gdbarch_byte_order(), get_type_arch(), MAX_DECIMAL_STRING, p, TYPE_CODE, TYPE_CODE_DECFLOAT, TYPE_LENGTH, value_contents(), value_from_decfloat(), and value_type().
Referenced by ui_printf().
static void printf_pointer (struct ui_file * stream, const char * format, struct value * value) [static]
Definition at line 2183 of file printcmd.c.
References fprintf_filtered(), gdb_assert, p, and value_as_long().
Referenced by ui_printf().
static void printf_wide_c_string (struct ui_file * stream, const char * format, struct value * value) [static]
Definition at line 2049 of file printcmd.c.
References gdbarch::byte_order, convert_between_encodings(), current_language, do_cleanups(), extract_unsigned_integer(), fprintf_filtered(), gdbarch_byte_order(), get_type_arch(), host_charset(), lookup_typename(), make_cleanup_obstack_free(), memset(), obstack_grow_str0, QUIT, read_memory(), target_wide_charset(), translit_char, TYPE_LENGTH, value_as_address(), and value_type().
Referenced by ui_printf().
static void set_command (char * exp, int from_tty) [static]
Definition at line 1079 of file printcmd.c.
References _, do_cleanups(), expression::elts, evaluate_expression(), free_current_contents(), make_cleanup(), expression::nelts, exp_element::opcode, parse_expression(), and warning().
void set_next_address (struct gdbarch * gdbarch, CORE_ADDR addr)
Definition at line 549 of file printcmd.c.
References builtin_type::builtin_data_ptr, builtin_type(), lookup_internalvar(), next_address, set_internalvar(), and value_from_pointer().
Referenced by breakpoint_1(), and line_info().
static void show_max_symbolic_offset (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 101 of file printcmd.c.
References _, and fprintf_filtered().
static void show_print_symbol_filename (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 114 of file printcmd.c.
References _, and fprintf_filtered().
static void sym_info (char * arg, int from_tty) [static]
Definition at line 1106 of file printcmd.c.
References _, ALL_OBJSECTIONS, do_cleanups(), error_no_arg(), gdb_assert, lookup_minimal_symbol_by_pc_section(), make_cleanup(), MULTI_OBJFILE_P, obj_section_addr, obj_section_endaddr, obj_section::objfile, objfile_name(), offset, overlay_mapped_address(), parse_and_eval_address(), pc_in_unmapped_range(), printf_filtered(), section_is_mapped(), section_is_overlay(), objfile::separate_debug_objfile_backlink, SYMBOL_PRINT_NAME, SYMBOL_VALUE_ADDRESS, obj_section::the_bfd_section, xfree(), and xstrprintf().
Referenced by read_alphacoff_dynamic_symtab().
static void ui_printf (const char * arg, struct ui_file * stream) [static]
Definition at line 2247 of file printcmd.c.
References _, convert_between_encodings(), current_language, decfloat_arg, do_cleanups(), double_arg, error(), error_no_arg(), float_type_from_length(), fprintf_filtered(), free_current_contents(), free_format_pieces_cleanup(), get_type_arch(), host_charset(), int_arg, internal_error(), literal_piece, long_arg, long_double_arg, long_long_arg, lookup_typename(), make_cleanup(), make_cleanup_obstack_free(), obstack_grow_str0, parse_format_string(), parse_to_comma_and_eval(), printf_c_string(), printf_decfloat(), printf_pointer(), printf_wide_c_string(), ptr_arg, skip_spaces_const(), format_piece::string, string_arg, target_wide_charset(), translit_char, TYPE_CODE, TYPE_CODE_INT, TYPE_LENGTH, unpack_double(), value_as_long(), value_contents(), value_type(), wide_char_arg, wide_string_arg, xmalloc(), and xrealloc().
Referenced by eval_command(), and printf_command().
static void undisplay_command (char * args, int from_tty) [static]
Definition at line 1661 of file printcmd.c.
References _, clear_displays(), do_delete_display(), dont_repeat(), map_display_numbers(), and query().
static void validate_format (struct format_data fmt, char * cmdname) [static]
Definition at line 934 of file printcmd.c.
References _, format_data::count, error(), format_data::format, and format_data::size.
Referenced by output_command_const(), and print_command_1().
static void x_command (char * exp, int from_tty) [static]
Definition at line 1417 of file printcmd.c.
References _, clear_internalvar(), coerce_ref(), format_data::count, decode_format(), do_cleanups(), do_examine(), error_no_arg(), evaluate_expression(), format_data::format, free_current_contents(), expression::gdbarch, last_examine_address, last_format, last_size, lookup_internalvar(), lookup_pointer_type(), lval_memory, make_cleanup(), next_address, parse_expression(), pointer_type(), format_data::raw, set_internalvar(), format_data::size, TYPE_CODE, TYPE_CODE_FUNC, TYPE_CODE_REF, value_address(), value_as_address(), value_from_pointer(), value_lazy(), VALUE_LVAL, and value_type().
Variable Documentation
int branch_delay_insns [static]
Definition at line 85 of file printcmd.c.
Referenced by do_examine(), and print_formatted().
int current_display_number [static]
Definition at line 126 of file printcmd.c.
Referenced by disable_current_display(), and do_one_display().
struct display* display_chain [static]
Definition at line 158 of file printcmd.c.
Referenced by display_command().
int display_number [static]
Definition at line 160 of file printcmd.c.
Referenced by display_command().
CORE_ADDR last_examine_address [static]
Definition at line 89 of file printcmd.c.
Referenced by do_examine(), and x_command().
struct value* last_examine_value [static]
Definition at line 94 of file printcmd.c.
char last_format = 0 [static]
Definition at line 72 of file printcmd.c.
Referenced by print_command_1(), and x_command().
char last_size = 'w' [static]
Definition at line 76 of file printcmd.c.
Referenced by x_command().
unsigned int max_symbolic_offset = UINT_MAX [static]
Definition at line 99 of file printcmd.c.
Referenced by build_address_symbolic().
CORE_ADDR next_address [static]
Definition at line 81 of file printcmd.c.
Referenced by do_examine(), print_formatted(), set_next_address(), and x_command().
struct gdbarch* next_gdbarch [static]
Definition at line 80 of file printcmd.c.
int print_symbol_filename = 0 [static]
Definition at line 112 of file printcmd.c.
Referenced by build_address_symbolic(), and print_address_symbolic().