GDB (xrefs): /home/stan/gdb/src/gdb/probe.c File Reference
/home/stan/gdb/src/gdb/probe.c File Reference
#include "defs.h"
#include "probe.h"
#include "command.h"
#include "cli/cli-cmds.h"
#include "cli/cli-utils.h"
#include "objfiles.h"
#include "symtab.h"
#include "progspace.h"
#include "filenames.h"
#include "exceptions.h"
#include "linespec.h"
#include "gdb_regex.h"
#include "frame.h"
#include "arch-utils.h"
#include <ctype.h>
Functions
struct symtabs_and_lines parse_probes (char **argptr, struct linespec_result *canonical)
VEC (probe_p)
struct probe * find_probe_by_pc (CORE_ADDR pc)
static int compare_probes (const void *a, const void *b)
static void gen_ui_out_table_header_info (VEC(probe_p)*probes, const struct probe_ops *p)
static void print_ui_out_info (struct probe *probe)
static int get_number_extra_fields (const struct probe_ops *pops)
void info_probes_for_ops (char *arg, int from_tty, const struct probe_ops *pops)
static void info_probes_command (char *arg, int from_tty)
unsigned get_probe_argument_count (struct probe *probe)
int can_evaluate_probe_arguments (struct probe *probe)
struct value * evaluate_probe_argument (struct probe *probe, unsigned n)
struct value * probe_safe_evaluate_at_pc (struct frame_info *frame, unsigned n)
struct probe_ops * probe_linespec_to_ops (const char **linespecp)
int probe_is_linespec_by_keyword (const char **linespecp, const char *const *keywords)
static int probe_any_is_linespec (const char **linespecp)
static void probe_any_get_probes (VEC(probe_p)**probesp, struct objfile *objfile)
struct cmd_list_element ** info_probes_cmdlist_get (void)
VEC (probe_ops_cp)
Variables
struct probe_ops probe_ops_any
Function Documentation
int can_evaluate_probe_arguments (struct probe * probe)
Definition at line 634 of file probe.c.
References sym_probe_fns::can_evaluate_probe_arguments, gdb_assert, probe::objfile, objfile::sf, and sym_fns::sym_probe_fns.
Referenced by create_exception_master_breakpoint(), create_longjmp_master_breakpoint(), and svr4_create_solib_event_breakpoints().
static int compare_probes (const void * a, const void * b) [static]
Definition at line 298 of file probe.c.
References probe::address, probe::name, probe::objfile, objfile_name(), and probe::provider.
Referenced by info_probes_for_ops().
struct value* evaluate_probe_argument (struct probe * probe, unsigned n) [read]
Definition at line 651 of file probe.c.
References gdb_assert, probe::objfile, objfile::sf, sym_probe_fns::sym_evaluate_probe_argument, and sym_fns::sym_probe_fns.
Referenced by probe_safe_evaluate_at_pc(), and svr4_handle_solib_event().
struct probe* find_probe_by_pc (CORE_ADDR pc) [read]
Definition at line 208 of file probe.c.
References probe::address, ALL_OBJFILES, objfile::sf, sym_fns::sym_probe_fns, VEC, and VEC_iterate.
Referenced by check_exception_resume(), compile_probe_arg(), compute_probe_arg(), fetch_probe_arguments(), and probe_safe_evaluate_at_pc().
static void gen_ui_out_table_header_info (VEC(probe_p)* probes, const struct probe_ops * p) [static]
Definition at line 324 of file probe.c.
References current_uiout, do_cleanups(), info_probe_column::field_name, gdb_assert, probe_ops::gen_info_probes_table_header, probe_ops::gen_info_probes_table_values, make_cleanup(), max, probe::pops, info_probe_column::print_name, ui_left, ui_out_table_header(), VEC, VEC_cleanup, VEC_iterate, and VEC_length.
Referenced by info_probes_for_ops().
static int get_number_extra_fields (const struct probe_ops * pops) [static]
Definition at line 449 of file probe.c.
References do_cleanups(), probe_ops::gen_info_probes_table_header, make_cleanup(), VEC, VEC_cleanup, and VEC_length.
Referenced by info_probes_for_ops().
unsigned get_probe_argument_count (struct probe * probe)
Definition at line 617 of file probe.c.
References gdb_assert, probe::objfile, objfile::sf, sym_probe_fns::sym_get_probe_argument_count, and sym_fns::sym_probe_fns.
Referenced by probe_safe_evaluate_at_pc(), and solib_event_probe_action().
struct cmd_list_element** info_probes_cmdlist_get (void) [read]
Definition at line 751 of file probe.c.
References _, add_prefix_cmd(), class_info, info_probes_command(), and infolist.
static void info_probes_command (char * arg, int from_tty) [static]
Definition at line 609 of file probe.c.
References info_probes_for_ops().
Referenced by info_probes_cmdlist_get().
void info_probes_for_ops (char * arg, int from_tty, const struct probe_ops * pops)
Definition at line 471 of file probe.c.
References _, probe::address, compare_probes(), current_uiout, do_cleanups(), extract_arg(), gdbarch_addr_bit(), gen_ui_out_table_header_info(), get_current_arch(), get_number_extra_fields(), get_objfile_arch(), make_cleanup(), make_cleanup_ui_out_table_begin_end(), make_cleanup_ui_out_tuple_begin_end(), max, probe::name, null_cleanup(), probe::objfile, objfile_name(), probe::pops, print_ui_out_info(), probe::provider, provider, qsort, ui_left, ui_out_field_core_addr(), ui_out_field_string(), ui_out_message(), ui_out_table_body(), ui_out_table_header(), ui_out_text(), VEC, VEC_address, VEC_cleanup, VEC_empty, VEC_iterate, VEC_length, and xfree().
Referenced by info_probes_command(), and info_probes_stap_command().
struct symtabs_and_lines parse_probes (char ** argptr, struct linespec_result * canonical) [read]
Definition at line 41 of file probe.c.
References _, probe::address, ALL_PSPACE_OBJFILES, ALL_PSPACES, do_cleanups(), error(), symtab_and_line::explicit_pc, find_pc_overlay(), gdb_assert, init_sal(), make_cleanup(), name, probe::name, symtabs_and_lines::nelts, NOT_FOUND_ERROR, objfile_name(), p, symtab_and_line::pc, probe::pops, symtab_and_line::probe, probe_linespec_to_ops(), probe_ops_any, probe::provider, provider, symtab_and_line::pspace, symtabs_and_lines::sals, savestring(), symtab_and_line::section, objfile::sf, skip_spaces(), skip_to_space, strchr(), sym_fns::sym_probe_fns, throw_error(), VEC, VEC_iterate, xfree(), and xrealloc().
Referenced by bkpt_probe_create_sals_from_address(), bkpt_probe_decode_linespec(), and re_set_exception_catchpoint().
static void print_ui_out_info (struct probe * probe) [static]
Definition at line 400 of file probe.c.
References current_uiout, do_cleanups(), info_probe_column::field_name, gdb_assert, probe_ops::gen_info_probes_table_header, probe_ops::gen_info_probes_table_values, make_cleanup(), probe::pops, ui_out_field_skip(), ui_out_field_string(), VEC, VEC_cleanup, VEC_index, VEC_iterate, and VEC_length.
Referenced by info_probes_for_ops().
static void probe_any_get_probes (VEC(probe_p)** probesp, struct objfile * objfile) [static]
Definition at line 735 of file probe.c.
static int probe_any_is_linespec (const char ** linespecp) [static]
Definition at line 725 of file probe.c.
References probe_is_linespec_by_keyword().
int probe_is_linespec_by_keyword (const char ** linespecp, const char *const * keywords)
Definition at line 702 of file probe.c.
References len.
Referenced by probe_any_is_linespec(), and stap_probe_is_linespec().
struct probe_ops* probe_linespec_to_ops (const char ** linespecp) [read]
Definition at line 687 of file probe.c.
References probe_ops::is_linespec, and VEC_iterate.
Referenced by break_command_1(), parse_probes(), and trace_command().
struct value* probe_safe_evaluate_at_pc (struct frame_info * frame, unsigned n) [read]
Definition at line 668 of file probe.c.
References evaluate_probe_argument(), find_probe_by_pc(), get_frame_pc(), and get_probe_argument_count().
Referenced by handle_inferior_event(), and insert_exception_resume_from_probe().
static VEC (probe_p)
Definition at line 179 of file probe.c.
References probe::name, probe::provider, objfile::sf, sym_fns::sym_probe_fns, VEC, VEC_iterate, and VEC_safe_push.
VEC (probe_ops_cp)
Definition at line 772 of file probe.c.
References _initialize_probe.
Variable Documentation
struct probe_ops probe_ops_any
Initial value:
{
  probe_any_is_linespec,
  probe_any_get_probes,
}
Definition at line 742 of file probe.c.
Referenced by parse_probes().