GDB (xrefs): /home/stan/gdb/src/gdb/proc-api.c File Reference
/home/stan/gdb/src/gdb/proc-api.c File Reference
#include "defs.h"
#include "gdbcmd.h"
#include "completer.h"
#include <stdio.h>
#include <sys/types.h>
#include <sys/procfs.h>
#include <fcntl.h>
#include "gdb_wait.h"
#include "proc-utils.h"
Classes
struct trans
Functions
static void prepare_to_trace (void)
static void set_procfs_trace_cmd (char *args, int from_tty, struct cmd_list_element *c)
static void set_procfs_file_cmd (char *args, int from_tty, struct cmd_list_element *c)
int ioctl_with_trace (int fd, long opcode, void *ptr, char *file, int line)
int open_with_trace (char *filename, int mode, char *file, int line)
int close_with_trace (int fd, char *file, int line)
pid_t wait_with_trace (int *wstat, char *file, int line)
void procfs_note (char *msg, char *file, int line)
void proc_prettyfprint_status (long flags, int why, int what, int thread)
void _initialize_proc_api (void)
Variables
static int procfs_trace = 0
static FILE * procfs_file = NULL
static char * procfs_filename = "procfs_trace"
static struct trans ioctl_table []
Function Documentation
void _initialize_proc_api (void)
Definition at line 778 of file proc-api.c.
References _, add_setshow_boolean_cmd(), add_setshow_filename_cmd(), no_class, procfs_filename, procfs_trace, set_procfs_file_cmd(), set_procfs_trace_cmd(), setlist, and showlist.
int close_with_trace (int fd, char * file, int line)
Definition at line 677 of file proc-api.c.
References info_verbose, prepare_to_trace(), procfs_file, procfs_trace, and safe_strerror().
int ioctl_with_trace (int fd, long opcode, void * ptr, char * file, int line)
Definition at line 224 of file proc-api.c.
References trans::desc, info_verbose, trans::name, name, prepare_to_trace(), proc_prettyfprint_faultset(), proc_prettyfprint_signal(), proc_prettyfprint_signalset(), proc_prettyfprint_syscalls(), procfs_file, procfs_trace, and safe_strerror().
int open_with_trace (char * filename, int mode, char * file, int line)
Definition at line 636 of file proc-api.c.
References info_verbose, prepare_to_trace(), procfs_file, procfs_trace, and safe_strerror().
static void prepare_to_trace (void) [static]
Definition at line 67 of file proc-api.c.
References procfs_file, procfs_filename, and procfs_trace.
Referenced by close_with_trace(), ioctl_with_trace(), open_with_trace(), proc_prettyfprint_status(), procfs_note(), and wait_with_trace().
void proc_prettyfprint_status (long flags, int why, int what, int thread)
Definition at line 753 of file proc-api.c.
References prepare_to_trace(), proc_prettyfprint_flags(), proc_prettyfprint_why(), procfs_file, and procfs_trace.
void procfs_note (char * msg, char * file, int line)
Definition at line 738 of file proc-api.c.
References info_verbose, prepare_to_trace(), procfs_file, and procfs_trace.
static void set_procfs_file_cmd (char * args, int from_tty, struct cmd_list_element * c) [static]
Definition at line 85 of file proc-api.c.
References procfs_file.
Referenced by _initialize_proc_api().
static void set_procfs_trace_cmd (char * args, int from_tty, struct cmd_list_element * c) [static]
Definition at line 76 of file proc-api.c.
References procfs_file.
Referenced by _initialize_proc_api().
pid_t wait_with_trace (int * wstat, char * file, int line)
Definition at line 703 of file proc-api.c.
References info_verbose, prepare_to_trace(), procfs_file, procfs_trace, and safe_strerror().
Variable Documentation
struct trans ioctl_table[] [static]
Definition at line 97 of file proc-api.c.
FILE* procfs_file = NULL [static]
Definition at line 63 of file proc-api.c.
Referenced by close_with_trace(), ioctl_with_trace(), open_with_trace(), prepare_to_trace(), proc_prettyfprint_status(), procfs_note(), set_procfs_file_cmd(), set_procfs_trace_cmd(), and wait_with_trace().
char* procfs_filename = "procfs_trace" [static]
Definition at line 64 of file proc-api.c.
Referenced by _initialize_proc_api(), and prepare_to_trace().
int procfs_trace = 0 [static]
Definition at line 62 of file proc-api.c.
Referenced by _initialize_proc_api(), close_with_trace(), ioctl_with_trace(), open_with_trace(), prepare_to_trace(), proc_prettyfprint_status(), procfs_note(), and wait_with_trace().