GDB (xrefs): /home/stan/gdb/src/gdb/procfs.h File Reference
/home/stan/gdb/src/gdb/procfs.h File Reference
Functions
struct target_ops * procfs_target (void)
void procfs_use_watchpoints (struct target_ops *t)
ptid_t procfs_first_available (void)
Function Documentation
ptid_t procfs_first_available (void)
Definition at line 5368 of file procfs.c.
References procinfo::pid, and pid_to_ptid().
Referenced by rw_common(), sol_thread_resume(), sol_thread_wait(), and sol_thread_xfer_partial().
struct target_ops* procfs_target (void) [read]
Definition at line 183 of file procfs.c.
References target_ops::deprecated_xfer_memory, inf_child_target(), OPS_MAGIC, proc_find_memory_regions(), procfs_attach(), procfs_create_inferior(), procfs_detach(), procfs_fetch_registers(), procfs_files_info(), procfs_find_new_threads(), procfs_info_proc(), procfs_kill_inferior(), procfs_make_note_section(), procfs_mourn_inferior(), procfs_pass_signals(), procfs_pid_to_str(), procfs_resume(), procfs_stop(), procfs_store_registers(), procfs_thread_alive(), procfs_wait(), procfs_xfer_memory(), procfs_xfer_partial(), tc_schedlock, target_ops::to_attach, target_ops::to_auxv_parse, target_ops::to_create_inferior, target_ops::to_detach, target_ops::to_doc, target_ops::to_fetch_registers, target_ops::to_files_info, target_ops::to_find_memory_regions, target_ops::to_find_new_threads, target_ops::to_has_thread_control, target_ops::to_info_proc, target_ops::to_kill, target_ops::to_longname, target_ops::to_magic, target_ops::to_make_corefile_notes, target_ops::to_mourn_inferior, target_ops::to_pass_signals, target_ops::to_pid_to_str, target_ops::to_resume, target_ops::to_shortname, target_ops::to_stop, target_ops::to_store_registers, target_ops::to_thread_alive, target_ops::to_wait, and target_ops::to_xfer_partial.
Referenced by _initialize_alpha_nat(), _initialize_amd64_sol2_nat(), _initialize_irix5_nat(), and _initialize_sparc_sol2_nat().
void procfs_use_watchpoints (struct target_ops * t)
Definition at line 4945 of file procfs.c.
References procfs_can_use_hw_breakpoint(), procfs_insert_watchpoint(), procfs_region_ok_for_hw_watchpoint(), procfs_remove_watchpoint(), procfs_stopped_by_watchpoint(), procfs_stopped_data_address(), target_ops::to_can_use_hw_breakpoint, target_ops::to_insert_watchpoint, target_ops::to_region_ok_for_hw_watchpoint, target_ops::to_remove_watchpoint, target_ops::to_stopped_by_watchpoint, and target_ops::to_stopped_data_address.
Referenced by _initialize_amd64_sol2_nat(), _initialize_irix5_nat(), and _initialize_sparc_sol2_nat().