GDB (xrefs): /home/stan/gdb/src/gdb/proc-utils.h File Reference
/home/stan/gdb/src/gdb/proc-utils.h File Reference
Defines
#define PROCFS_NOTE(X) procfs_note (X, __FILE__, __LINE__)
#define PROC_PRETTYFPRINT_STATUS(X, Y, Z, T) proc_prettyfprint_status (X, Y, Z, T)
Typedefs
typedef long procfs_ctl_t
Functions
void proc_prettyprint_why (unsigned long why, unsigned long what, int verbose)
void proc_prettyprint_syscalls (sysset_t *sysset, int verbose)
void proc_prettyprint_syscall (int num, int verbose)
void proc_prettyprint_signalset (sigset_t *sigset, int verbose)
void proc_prettyprint_signal (int signo, int verbose)
void proc_prettyprint_faultset (fltset_t *fltset, int verbose)
void proc_prettyprint_fault (int faultno, int verbose)
void proc_prettyprint_actionset (struct sigaction *actions, int verbose)
void proc_prettyfprint_signalset (FILE *file, sigset_t *sigset, int verbose)
void proc_prettyfprint_faultset (FILE *file, fltset_t *fltset, int verbose)
void proc_prettyfprint_syscall (FILE *file, int num, int verbose)
void proc_prettyfprint_signal (FILE *file, int signo, int verbose)
void proc_prettyfprint_flags (FILE *file, unsigned long flags, int verbose)
void proc_prettyfprint_why (FILE *file, unsigned long why, unsigned long what, int verbose)
void proc_prettyfprint_fault (FILE *file, int faultno, int verbose)
void proc_prettyfprint_syscalls (FILE *file, sysset_t *sysset, int verbose)
void proc_prettyfprint_status (long, int, int, int)
void proc_prettyprint_flags (unsigned long flags, int verbose)
int write_with_trace (int, void *, size_t, char *, int)
off_t lseek_with_trace (int, off_t, int, char *, int)
int ioctl_with_trace (int, long, void *, char *, int)
pid_t wait_with_trace (int *, char *, int)
int open_with_trace (char *, int, char *, int)
int close_with_trace (int, char *, int)
void procfs_note (char *, char *, int)
Define Documentation
#define PROC_PRETTYFPRINT_STATUS (X, Y, Z, T) proc_prettyfprint_status (X, Y, Z, T)
Definition at line 110 of file proc-utils.h.
Referenced by proc_get_status(), proc_stop_process(), and proc_wait_for_stop().
#define PROCFS_NOTE (X) procfs_note (X, __FILE__, __LINE__)
Definition at line 109 of file proc-utils.h.
Referenced by procfs_xfer_memory().
Typedef Documentation
typedef long procfs_ctl_t
Definition at line 118 of file proc-utils.h.
Function Documentation
int close_with_trace (int , char * , int)
Definition at line 677 of file proc-api.c.
References info_verbose, prepare_to_trace(), procfs_file, procfs_trace, and safe_strerror().
int ioctl_with_trace (int , long , void * , char * , int)
Definition at line 224 of file proc-api.c.
References trans::desc, info_verbose, trans::name, name, prepare_to_trace(), proc_prettyfprint_faultset(), proc_prettyfprint_signal(), proc_prettyfprint_signalset(), proc_prettyfprint_syscalls(), procfs_file, procfs_trace, and safe_strerror().
off_t lseek_with_trace (int , off_t , int , char * , int)
int open_with_trace (char * , int , char * , int)
Definition at line 636 of file proc-api.c.
References info_verbose, prepare_to_trace(), procfs_file, procfs_trace, and safe_strerror().
void proc_prettyfprint_fault (FILE * file, int faultno, int verbose)
Definition at line 1668 of file proc-events.c.
References prettyfprint_faulttable_entry().
Referenced by proc_prettyfprint_why(), and proc_prettyprint_fault().
void proc_prettyfprint_faultset (FILE * file, fltset_t * fltset, int verbose)
Definition at line 1692 of file proc-events.c.
References prettyfprint_faulttable_entry().
Referenced by ioctl_with_trace(), and proc_prettyprint_faultset().
void proc_prettyfprint_flags (FILE * file, unsigned long flags, int verbose)
Definition at line 273 of file proc-flags.c.
References trans::desc, name, and pr_flag_table.
Referenced by proc_prettyfprint_status(), and proc_prettyprint_flags().
void proc_prettyfprint_signal (FILE * file, int signo, int verbose)
Definition at line 1550 of file proc-events.c.
References trans::desc, name, and signal_table.
Referenced by ioctl_with_trace(), proc_prettyfprint_signalset(), proc_prettyfprint_why(), and proc_prettyprint_signal().
void proc_prettyfprint_signalset (FILE * file, sigset_t * sigset, int verbose)
Definition at line 1576 of file proc-events.c.
References proc_prettyfprint_signal().
Referenced by ioctl_with_trace(), and proc_prettyprint_signalset().
void proc_prettyfprint_status (long , int , int , int)
Definition at line 753 of file proc-api.c.
References prepare_to_trace(), proc_prettyfprint_flags(), proc_prettyfprint_why(), procfs_file, and procfs_trace.
void proc_prettyfprint_syscall (FILE * file, int num, int verbose)
Definition at line 1362 of file proc-events.c.
References syscall_table.
Referenced by proc_prettyfprint_syscalls(), proc_prettyfprint_why(), and proc_prettyprint_syscall().
void proc_prettyfprint_syscalls (FILE * file, sysset_t * sysset, int verbose)
Definition at line 1379 of file proc-events.c.
References MAX_SYSCALLS, and proc_prettyfprint_syscall().
Referenced by ioctl_with_trace(), and proc_prettyprint_syscalls().
void proc_prettyfprint_why (FILE * file, unsigned long why, unsigned long what, int verbose)
Definition at line 106 of file proc-why.c.
References trans::desc, name, proc_prettyfprint_fault(), proc_prettyfprint_signal(), and proc_prettyfprint_syscall().
Referenced by proc_prettyfprint_status(), and proc_prettyprint_why().
void proc_prettyprint_actionset (struct sigaction * actions, int verbose)
Definition at line 1717 of file proc-events.c.
void proc_prettyprint_fault (int faultno, int verbose)
Definition at line 1684 of file proc-events.c.
References proc_prettyfprint_fault().
void proc_prettyprint_faultset (fltset_t * fltset, int verbose)
Definition at line 1709 of file proc-events.c.
References proc_prettyfprint_faultset().
void proc_prettyprint_flags (unsigned long flags, int verbose)
Definition at line 289 of file proc-flags.c.
References proc_prettyfprint_flags().
Referenced by procfs_info_proc(), and procfs_wait().
void proc_prettyprint_signal (int signo, int verbose)
Definition at line 1568 of file proc-events.c.
References proc_prettyfprint_signal().
void proc_prettyprint_signalset (sigset_t * sigset, int verbose)
Definition at line 1593 of file proc-events.c.
References proc_prettyfprint_signalset().
void proc_prettyprint_syscall (int num, int verbose)
Definition at line 1371 of file proc-events.c.
References proc_prettyfprint_syscall().
Referenced by procfs_wait().
void proc_prettyprint_syscalls (sysset_t * sysset, int verbose)
Definition at line 1392 of file proc-events.c.
References proc_prettyfprint_syscalls().
void proc_prettyprint_why (unsigned long why, unsigned long what, int verbose)
Definition at line 171 of file proc-why.c.
References proc_prettyfprint_why().
Referenced by do_attach(), procfs_info_proc(), and procfs_wait().
void procfs_note (char * , char * , int)
Definition at line 738 of file proc-api.c.
References info_verbose, prepare_to_trace(), procfs_file, and procfs_trace.
pid_t wait_with_trace (int * , char * , int)
Definition at line 703 of file proc-api.c.
References info_verbose, prepare_to_trace(), procfs_file, procfs_trace, and safe_strerror().
int write_with_trace (int , void * , size_t , char * , int)