GDB (xrefs): /home/stan/gdb/src/gdb/proc-service.c File Reference
/home/stan/gdb/src/gdb/proc-service.c File Reference
#include "defs.h"
#include "gdbcore.h"
#include "inferior.h"
#include "symtab.h"
#include "target.h"
#include "regcache.h"
#include "gdb_proc_service.h"
#include <sys/procfs.h>
#include "gregset.h"
Typedefs
typedef struct ps_prochandle * gdb_ps_prochandle_t
typedef void * gdb_ps_read_buf_t
typedef const void * gdb_ps_write_buf_t
typedef size_t gdb_ps_size_t
Functions
static CORE_ADDR ps_addr_to_core_addr (psaddr_t addr)
static psaddr_t core_addr_to_ps_addr (CORE_ADDR addr)
static ps_err_e ps_xfer_memory (const struct ps_prochandle *ph, psaddr_t addr, gdb_byte *buf, size_t len, int write)
ps_err_e ps_pstop (gdb_ps_prochandle_t ph)
ps_err_e ps_pcontinue (gdb_ps_prochandle_t ph)
ps_err_e ps_lstop (gdb_ps_prochandle_t ph, lwpid_t lwpid)
ps_err_e ps_lcontinue (gdb_ps_prochandle_t ph, lwpid_t lwpid)
ps_err_e ps_lgetxregsize (gdb_ps_prochandle_t ph, lwpid_t lwpid, int *xregsize)
ps_err_e ps_lgetxregs (gdb_ps_prochandle_t ph, lwpid_t lwpid, caddr_t xregset)
ps_err_e ps_lsetxregs (gdb_ps_prochandle_t ph, lwpid_t lwpid, caddr_t xregset)
void ps_plog (const char *fmt,...)
ps_err_e ps_pglobal_lookup (gdb_ps_prochandle_t ph, const char *obj, const char *name, psaddr_t *sym_addr)
ps_err_e ps_pdread (gdb_ps_prochandle_t ph, psaddr_t addr, gdb_ps_read_buf_t buf, gdb_ps_size_t size)
ps_err_e ps_pdwrite (gdb_ps_prochandle_t ph, psaddr_t addr, gdb_ps_write_buf_t buf, gdb_ps_size_t size)
ps_err_e ps_ptread (gdb_ps_prochandle_t ph, psaddr_t addr, gdb_ps_read_buf_t buf, gdb_ps_size_t size)
ps_err_e ps_ptwrite (gdb_ps_prochandle_t ph, psaddr_t addr, gdb_ps_write_buf_t buf, gdb_ps_size_t size)
ps_err_e ps_lgetregs (gdb_ps_prochandle_t ph, lwpid_t lwpid, prgregset_t gregset)
ps_err_e ps_lsetregs (gdb_ps_prochandle_t ph, lwpid_t lwpid, const prgregset_t gregset)
ps_err_e ps_lgetfpregs (gdb_ps_prochandle_t ph, lwpid_t lwpid, gdb_prfpregset_t *fpregset)
ps_err_e ps_lsetfpregs (gdb_ps_prochandle_t ph, lwpid_t lwpid, const gdb_prfpregset_t *fpregset)
pid_t ps_getpid (gdb_ps_prochandle_t ph)
void _initialize_proc_service (void)
Variables
initialize_file_ftype _initialize_proc_service
Typedef Documentation
typedef struct ps_prochandle* gdb_ps_prochandle_t
Definition at line 47 of file proc-service.c.
typedef void* gdb_ps_read_buf_t
Definition at line 48 of file proc-service.c.
typedef size_t gdb_ps_size_t
Definition at line 50 of file proc-service.c.
typedef const void* gdb_ps_write_buf_t
Definition at line 49 of file proc-service.c.
Function Documentation
void _initialize_proc_service (void)
Definition at line 347 of file proc-service.c.
References _initialize_proc_service.
static psaddr_t core_addr_to_ps_addr (CORE_ADDR addr) [static]
Definition at line 70 of file proc-service.c.
References exec_bfd.
Referenced by ps_pglobal_lookup().
static CORE_ADDR ps_addr_to_core_addr (psaddr_t addr) [static]
Definition at line 59 of file proc-service.c.
References exec_bfd.
Referenced by ps_xfer_memory().
pid_t ps_getpid (gdb_ps_prochandle_t ph)
Definition at line 338 of file proc-service.c.
References ps_prochandle::ptid, and ptid_get_pid().
ps_err_e ps_lcontinue (gdb_ps_prochandle_t ph, lwpid_t lwpid)
Definition at line 139 of file proc-service.c.
References PS_OK.
ps_err_e ps_lgetfpregs (gdb_ps_prochandle_t ph, lwpid_t lwpid, gdb_prfpregset_t * fpregset)
Definition at line 298 of file proc-service.c.
References do_cleanups(), fill_fpregset(), get_thread_arch_regcache(), inferior_ptid, PS_OK, ps_prochandle::ptid, ptid_build(), ptid_get_pid(), save_inferior_ptid(), target_fetch_registers(), and target_gdbarch().
ps_err_e ps_lgetregs (gdb_ps_prochandle_t ph, lwpid_t lwpid, prgregset_t gregset)
Definition at line 260 of file proc-service.c.
References do_cleanups(), fill_gregset(), get_thread_arch_regcache(), inferior_ptid, PS_OK, ps_prochandle::ptid, ptid_build(), ptid_get_pid(), save_inferior_ptid(), target_fetch_registers(), and target_gdbarch().
ps_err_e ps_lgetxregs (gdb_ps_prochandle_t ph, lwpid_t lwpid, caddr_t xregset)
Definition at line 161 of file proc-service.c.
References PS_OK.
ps_err_e ps_lgetxregsize (gdb_ps_prochandle_t ph, lwpid_t lwpid, int * xregsize)
Definition at line 151 of file proc-service.c.
References PS_OK.
ps_err_e ps_lsetfpregs (gdb_ps_prochandle_t ph, lwpid_t lwpid, const gdb_prfpregset_t * fpregset)
Definition at line 318 of file proc-service.c.
References do_cleanups(), get_thread_arch_regcache(), inferior_ptid, PS_OK, ps_prochandle::ptid, ptid_build(), ptid_get_pid(), save_inferior_ptid(), supply_fpregset(), target_gdbarch(), and target_store_registers().
ps_err_e ps_lsetregs (gdb_ps_prochandle_t ph, lwpid_t lwpid, const prgregset_t gregset)
Definition at line 279 of file proc-service.c.
References do_cleanups(), get_thread_arch_regcache(), inferior_ptid, PS_OK, ps_prochandle::ptid, ptid_build(), ptid_get_pid(), save_inferior_ptid(), supply_gregset(), target_gdbarch(), and target_store_registers().
ps_err_e ps_lsetxregs (gdb_ps_prochandle_t ph, lwpid_t lwpid, caddr_t xregset)
Definition at line 171 of file proc-service.c.
References PS_OK.
ps_err_e ps_lstop (gdb_ps_prochandle_t ph, lwpid_t lwpid)
Definition at line 129 of file proc-service.c.
References PS_OK.
ps_err_e ps_pcontinue (gdb_ps_prochandle_t ph)
Definition at line 119 of file proc-service.c.
References PS_OK.
ps_err_e ps_pdread (gdb_ps_prochandle_t ph, psaddr_t addr, gdb_ps_read_buf_t buf, gdb_ps_size_t size)
Definition at line 222 of file proc-service.c.
References ps_xfer_memory().
ps_err_e ps_pdwrite (gdb_ps_prochandle_t ph, psaddr_t addr, gdb_ps_write_buf_t buf, gdb_ps_size_t size)
Definition at line 231 of file proc-service.c.
References ps_xfer_memory().
ps_err_e ps_pglobal_lookup (gdb_ps_prochandle_t ph, const char * obj, const char * name, psaddr_t * sym_addr)
Definition at line 194 of file proc-service.c.
References core_addr_to_ps_addr(), do_cleanups(), find_inferior_pid(), lookup_minimal_symbol(), PS_NOSYM, PS_OK, inferior::pspace, ps_prochandle::ptid, ptid_get_pid(), save_current_program_space(), set_current_program_space(), and SYMBOL_VALUE_ADDRESS.
void ps_plog (const char * fmt, ...)
Definition at line 180 of file proc-service.c.
References gdb_stderr, and vfprintf_filtered().
ps_err_e ps_pstop (gdb_ps_prochandle_t ph)
Definition at line 110 of file proc-service.c.
References PS_OK.
ps_err_e ps_ptread (gdb_ps_prochandle_t ph, psaddr_t addr, gdb_ps_read_buf_t buf, gdb_ps_size_t size)
Definition at line 241 of file proc-service.c.
References ps_xfer_memory().
ps_err_e ps_ptwrite (gdb_ps_prochandle_t ph, psaddr_t addr, gdb_ps_write_buf_t buf, gdb_ps_size_t size)
Definition at line 250 of file proc-service.c.
References ps_xfer_memory().
static ps_err_e ps_xfer_memory (const struct ps_prochandle * ph, psaddr_t addr, gdb_byte * buf, size_t len, int write) [static]
Definition at line 87 of file proc-service.c.
References do_cleanups(), inferior_ptid, ps_addr_to_core_addr(), PS_ERR, PS_OK, ps_prochandle::ptid, save_inferior_ptid(), target_read_memory(), and target_write_memory().
Referenced by ps_pdread(), ps_pdwrite(), ps_ptread(), and ps_ptwrite().
Variable Documentation
initialize_file_ftype _initialize_proc_service
Referenced by _initialize_proc_service(), and initialize_all_files().