GDB (xrefs): /home/stan/gdb/src/gdb/proc-events.c File Reference
/home/stan/gdb/src/gdb/proc-events.c File Reference
#include "defs.h"
#include <stdio.h>
#include <sys/types.h>
#include <sys/procfs.h>
#include "proc-utils.h"
Classes
struct trans
Defines
#define MAX_SYSCALLS 262 /* Pretty arbitrary. */
Functions
static void init_syscall_table (void)
void proc_prettyfprint_syscall (FILE *file, int num, int verbose)
void proc_prettyprint_syscall (int num, int verbose)
void proc_prettyfprint_syscalls (FILE *file, sysset_t *sysset, int verbose)
void proc_prettyprint_syscalls (sysset_t *sysset, int verbose)
void proc_prettyfprint_signal (FILE *file, int signo, int verbose)
void proc_prettyprint_signal (int signo, int verbose)
void proc_prettyfprint_signalset (FILE *file, sigset_t *sigset, int verbose)
void proc_prettyprint_signalset (sigset_t *sigset, int verbose)
static void prettyfprint_faulttable_entry (FILE *file, int i, int verbose)
void proc_prettyfprint_fault (FILE *file, int faultno, int verbose)
void proc_prettyprint_fault (int faultno, int verbose)
void proc_prettyfprint_faultset (FILE *file, fltset_t *fltset, int verbose)
void proc_prettyprint_faultset (fltset_t *fltset, int verbose)
void proc_prettyprint_actionset (struct sigaction *actions, int verbose)
void _initialize_proc_events (void)
Variables
static char * syscall_table [MAX_SYSCALLS]
static struct trans signal_table []
static struct trans fault_table []
Define Documentation
#define MAX_SYSCALLS 262 /* Pretty arbitrary. */
Definition at line 67 of file proc-events.c.
Referenced by proc_prettyfprint_syscalls().
Function Documentation
void _initialize_proc_events (void)
Definition at line 1726 of file proc-events.c.
References init_syscall_table().
static void init_syscall_table (void) [static]
Definition at line 71 of file proc-events.c.
References SYS_sigreturn, and syscall_table.
Referenced by _initialize_proc_events().
static void prettyfprint_faulttable_entry (FILE * file, int i, int verbose) [static]
Definition at line 1656 of file proc-events.c.
References trans::desc, and name.
Referenced by proc_prettyfprint_fault(), and proc_prettyfprint_faultset().
void proc_prettyfprint_fault (FILE * file, int faultno, int verbose)
Definition at line 1668 of file proc-events.c.
References prettyfprint_faulttable_entry().
Referenced by proc_prettyfprint_why(), and proc_prettyprint_fault().
void proc_prettyfprint_faultset (FILE * file, fltset_t * fltset, int verbose)
Definition at line 1692 of file proc-events.c.
References prettyfprint_faulttable_entry().
Referenced by ioctl_with_trace(), and proc_prettyprint_faultset().
void proc_prettyfprint_signal (FILE * file, int signo, int verbose)
Definition at line 1550 of file proc-events.c.
References trans::desc, name, and signal_table.
Referenced by ioctl_with_trace(), proc_prettyfprint_signalset(), proc_prettyfprint_why(), and proc_prettyprint_signal().
void proc_prettyfprint_signalset (FILE * file, sigset_t * sigset, int verbose)
Definition at line 1576 of file proc-events.c.
References proc_prettyfprint_signal().
Referenced by ioctl_with_trace(), and proc_prettyprint_signalset().
void proc_prettyfprint_syscall (FILE * file, int num, int verbose)
Definition at line 1362 of file proc-events.c.
References syscall_table.
Referenced by proc_prettyfprint_syscalls(), proc_prettyfprint_why(), and proc_prettyprint_syscall().
void proc_prettyfprint_syscalls (FILE * file, sysset_t * sysset, int verbose)
Definition at line 1379 of file proc-events.c.
References MAX_SYSCALLS, and proc_prettyfprint_syscall().
Referenced by ioctl_with_trace(), and proc_prettyprint_syscalls().
void proc_prettyprint_actionset (struct sigaction * actions, int verbose)
Definition at line 1717 of file proc-events.c.
void proc_prettyprint_fault (int faultno, int verbose)
Definition at line 1684 of file proc-events.c.
References proc_prettyfprint_fault().
void proc_prettyprint_faultset (fltset_t * fltset, int verbose)
Definition at line 1709 of file proc-events.c.
References proc_prettyfprint_faultset().
void proc_prettyprint_signal (int signo, int verbose)
Definition at line 1568 of file proc-events.c.
References proc_prettyfprint_signal().
void proc_prettyprint_signalset (sigset_t * sigset, int verbose)
Definition at line 1593 of file proc-events.c.
References proc_prettyfprint_signalset().
void proc_prettyprint_syscall (int num, int verbose)
Definition at line 1371 of file proc-events.c.
References proc_prettyfprint_syscall().
Referenced by procfs_wait().
void proc_prettyprint_syscalls (sysset_t * sysset, int verbose)
Definition at line 1392 of file proc-events.c.
References proc_prettyfprint_syscalls().
Variable Documentation
struct trans fault_table[] [static]
Definition at line 1603 of file proc-events.c.
struct trans signal_table[] [static]
Definition at line 1401 of file proc-events.c.
Referenced by proc_prettyfprint_signal().
char* syscall_table[MAX_SYSCALLS] [static]
Definition at line 68 of file proc-events.c.
Referenced by init_syscall_table(), and proc_prettyfprint_syscall().