GDB (xrefs): /home/stan/gdb/src/gdb/progspace.h File Reference
/home/stan/gdb/src/gdb/progspace.h File Reference
#include "target.h"
#include "vec.h"
#include "gdb_vecs.h"
#include "registry.h"
Classes
struct program_space
Defines
#define symfile_objfile current_program_space->symfile_object_file
#define object_files current_program_space->objfiles
#define current_target_sections (&current_program_space->target_sections)
#define ALL_PSPACES(pspace) for ((pspace) = program_spaces; (pspace) != NULL; (pspace) = (pspace)->next)
Typedefs
typedef struct so_list * so_list_ptr
Functions
DEF_VEC_P (so_list_ptr)
struct program_space * add_program_space (struct address_space *aspace)
void remove_program_space (struct program_space *pspace)
int number_of_program_spaces (void)
struct program_space * clone_program_space (struct program_space *dest, struct program_space *src)
struct cleanup * save_current_program_space (void)
void set_current_program_space (struct program_space *pspace)
struct cleanup * save_current_space_and_thread (void)
void switch_to_program_space_and_thread (struct program_space *pspace)
struct address_space * new_address_space (void)
struct address_space * maybe_new_address_space (void)
int address_space_num (struct address_space *aspace)
void update_address_spaces (void)
void prune_program_spaces (void)
void clear_program_space_solib_cache (struct program_space *)
DECLARE_REGISTRY (program_space)
Variables
struct program_space * program_spaces
struct program_space * current_program_space
Define Documentation
#define ALL_PSPACES (pspace) for ((pspace) = program_spaces; (pspace) != NULL; (pspace) = (pspace)->next)
Definition at line 231 of file progspace.h.
Referenced by create_longjmp_master_breakpoint(), create_std_terminate_master_breakpoint(), exec_close_1(), forget_cached_source_info(), iterate_over_all_matching_symtabs(), maintenance_check_symtabs(), maintenance_expand_symtabs(), maintenance_info_psymtabs(), maintenance_info_symtabs(), maintenance_print_msymbols(), maintenance_print_objfiles(), number_of_program_spaces(), parse_probes(), print_objfile_statistics(), print_program_space(), print_symbol_bcache_statistics(), remove_target_sections(), search_minsyms_for_name(), set_debug_symfile(), update_address_spaces(), valid_program_space_id(), and VEC().
#define current_target_sections (&current_program_space->target_sections)
Definition at line 223 of file progspace.h.
Referenced by add_target_sections(), exec_close_1(), exec_files_info(), exec_get_section_table(), exec_has_memory(), exec_set_section_address(), remove_target_sections(), scan_dyntag(), and set_section_command().
#define object_files current_program_space->objfiles
Definition at line 219 of file progspace.h.
Referenced by allocate_objfile(), lookup_minimal_symbol_by_pc_name(), lookup_minimal_symbol_internal(), lookup_minimal_symbol_solib_trampoline(), lookup_minimal_symbol_text(), objfile_to_front(), put_objfile_before(), reread_symbols(), and unlink_objfile().
#define symfile_objfile current_program_space->symfile_object_file
Definition at line 215 of file progspace.h.
Referenced by add_symbol_file_from_memory_command(), darwin_solib_create_inferior_hook(), dsbt_relocate_main_executable(), elf_locate_base(), elf_lookup_lib_symbol(), enable_break(), entry_point_address_query(), free_objfile(), frv_fdpic_find_canonical_descriptor(), frv_fetch_objfile_link_map(), frv_relocate_main_executable(), get_offsets(), get_symbol_leading_char(), ia64_hpux_solib_add_after_attach(), inside_main_func(), irix_open_symbol_file_object(), lm_base(), locate_base(), main_got(), match_main(), new_symfile_objfile(), open_symbol_file_object(), osf_open_symbol_file_object(), osf_solib_create_inferior_hook(), procfs_create_inferior(), reread_symbols(), scan_file_globals(), solib_aix_solib_create_inferior_hook(), som_open_symbol_file_object(), som_solib_create_inferior_hook(), spu_catch_start(), spu_gdbarch_id(), spu_relocate_main_executable(), svr4_fetch_objfile_link_map(), svr4_relocate_main_executable(), symbol_file_clear(), syms_from_objfile_1(), target_info(), and update_solib_list().
Typedef Documentation
typedef struct so_list* so_list_ptr
Definition at line 37 of file progspace.h.
Function Documentation
struct program_space* add_program_space (struct address_space * aspace) [read]
Definition at line 115 of file progspace.c.
References program_space::aspace, last_program_space_num, program_space::next, program_space::num, program_spaces, and XZALLOC.
Referenced by add_inferior_with_spaces(), clone_inferior_command(), follow_exec(), handle_vfork_child_exec_or_exit(), initialize_progspace(), and linux_child_follow_fork().
int address_space_num (struct address_space * aspace)
Definition at line 96 of file progspace.c.
References address_space::num.
Referenced by target_thread_address_space().
void clear_program_space_solib_cache (struct program_space *)
Definition at line 513 of file progspace.c.
References free_char_ptr_vec(), and VEC_free.
Referenced by handle_solib_event(), and release_program_space().
struct program_space* clone_program_space (struct program_space * dest, struct program_space * src) [read]
Definition at line 191 of file progspace.c.
References do_cleanups(), exec_file_attach(), objfile_name(), program_space::pspace_exec_filename, save_current_program_space(), set_current_program_space(), symbol_file_add_main(), and program_space::symfile_object_file.
Referenced by clone_inferior_command(), handle_vfork_child_exec_or_exit(), and linux_child_follow_fork().
DECLARE_REGISTRY (program_space)
DEF_VEC_P (so_list_ptr)
struct address_space* maybe_new_address_space (void) [read]
Definition at line 76 of file progspace.c.
References program_space::aspace, gdbarch_has_shared_address_space(), new_address_space(), and target_gdbarch().
Referenced by add_inferior_with_spaces(), clone_inferior_command(), follow_exec(), handle_vfork_child_exec_or_exit(), remote_add_inferior(), and update_address_spaces().
struct address_space* new_address_space (void) [read]
Definition at line 61 of file progspace.c.
References highest_address_space_num, address_space::num, and XZALLOC.
Referenced by initialize_progspace(), linux_child_follow_fork(), maybe_new_address_space(), and update_address_spaces().
int number_of_program_spaces (void)
Definition at line 409 of file progspace.c.
References ALL_PSPACES.
Referenced by print_one_breakpoint_location().
void prune_program_spaces (void)
Definition at line 266 of file progspace.c.
References current_program_space, program_space::next, program_spaces, pspace_empty_p(), and release_program_space().
Referenced by print_program_space(), and prune_inferiors().
void remove_program_space (struct program_space * pspace)
Definition at line 166 of file progspace.c.
References program_space::next, program_spaces, and release_program_space().
struct cleanup* save_current_program_space (void) [read]
Definition at line 243 of file progspace.c.
References make_cleanup(), and restore_program_space().
Referenced by breakpoint_re_set(), clone_program_space(), create_longjmp_master_breakpoint(), create_std_terminate_master_breakpoint(), decode_line_1(), decode_line_full(), exec_close_1(), handle_vfork_child_exec_or_exit(), linux_child_follow_fork(), print_breakpoint_location(), ps_pglobal_lookup(), release_program_space(), and save_current_space_and_thread().
struct cleanup* save_current_space_and_thread (void) [read]
Definition at line 467 of file progspace.c.
References make_cleanup_restore_current_thread(), and save_current_program_space().
Referenced by add_inferior_command(), bp_loc_is_permanent(), clone_inferior_command(), download_tracepoint_locations(), handle_vfork_child_exec_or_exit(), insert_breakpoint_locations(), mi_cmd_exec_run(), prepare_re_set_context(), remove_breakpoint(), resolve_sal_pc(), skip_prologue_sal(), and update_inserted_breakpoint_locations().
void set_current_program_space (struct program_space * pspace)
Definition at line 214 of file progspace.c.
References gdb_assert, and reinit_frame_cache().
Referenced by add_inferior_command(), add_matching_symbols_to_info(), clone_program_space(), convert_linespec_to_sals(), create_longjmp_master_breakpoint(), create_sals_line_offset(), create_std_terminate_master_breakpoint(), decode_digits_list_mode(), decode_digits_ordinary(), exec_close_1(), find_method(), follow_exec(), handle_inferior_event(), handle_vfork_child_exec_or_exit(), inferior_command(), iterate_over_all_matching_symtabs(), linux_child_follow_fork(), mi_cmd_execute(), mi_cmd_remove_inferior(), print_breakpoint_location(), ps_pglobal_lookup(), release_program_space(), restore_program_space(), run_one_inferior(), search_minsyms_for_name(), switch_to_program_space_and_thread(), switch_to_thread(), and VEC().
void switch_to_program_space_and_thread (struct program_space * pspace)
Definition at line 485 of file progspace.c.
References any_live_thread_of_process(), find_inferior_for_program_space(), arm-linux::inf, null_ptid, inferior::pid, thread_info::ptid, set_current_program_space(), and switch_to_thread().
Referenced by bp_loc_is_permanent(), download_tracepoint_locations(), insert_breakpoint_locations(), prepare_re_set_context(), remove_breakpoint(), resolve_sal_pc(), skip_prologue_sal(), update_breakpoint_locations(), and update_inserted_breakpoint_locations().
void update_address_spaces (void)
Definition at line 432 of file progspace.c.
References ALL_PSPACES, program_space::aspace, inferior::aspace, free_address_space(), gdbarch_has_global_solist(), gdbarch_has_shared_address_space(), arm-linux::inf, inferior_list, init_address_spaces(), maybe_new_address_space(), new_address_space(), inferior::next, inferior::pspace, and target_gdbarch().
Referenced by remote_start_remote().
Variable Documentation
struct program_space* current_program_space
Definition at line 35 of file progspace.c.
Referenced by allocate_objfile(), auto_load_info_scripts(), bpfinishpy_init(), breakpoint_init_inferior(), breakpoint_re_set_thread(), breakpoint_xfer_memory(), call_function_by_hand(), check_status_catch_solib(), clear_section_scripts(), create_breakpoint(), create_internal_breakpoint(), create_new_frame(), disable_breakpoints_before_startup(), disable_breakpoints_in_shlibs(), display_command(), do_one_display(), elf_gnu_ifunc_resolve_by_cache(), elf_gnu_ifunc_resolve_by_got(), elf_gnu_ifunc_resolver_return_stop(), enable_breakpoints_after_startup(), filter_sals(), find_function_start_sal(), find_pc_sect_line(), find_pc_section(), follow_exec(), func_command(), get_current_frame(), get_darwin_info(), get_dsbt_info(), get_dynamics_objfile(), get_jit_program_space_data(), get_svr4_info(), get_tcb_types_info(), handle_vfork_child_exec_or_exit(), init_catchpoint(), initialize_inferiors(), jv_per_objfile_free(), line_info(), linespec_expression_to_pc(), linespec_state_constructor(), mark_breakpoints_out(), objfiles_changed(), post_create_inferior(), print_solib_event(), prune_program_spaces(), ptid_from_atcb_common(), read_atcb(), read_known_tasks_list(), remote_add_inferior(), remove_jit_event_breakpoints(), remove_solib_event_breakpoints(), remove_thread_event_breakpoints(), select_source_symtab(), set_breakpoint_location_function(), set_longjmp_breakpoint(), set_longjmp_breakpoint_for_call_dummy(), set_std_terminate_breakpoint(), solib_add(), source_gdb_script_for_objfile(), svr4_handle_solib_event(), tui_set_disassem_content(), update_breakpoints_after_exec(), update_solib_list(), watch_command_1(), and watchpoint_in_thread_scope().
struct program_space* program_spaces
Definition at line 32 of file progspace.c.
Referenced by ada_new_objfile_observer(), add_program_space(), prune_program_spaces(), and remove_program_space().