GDB (xrefs): /home/stan/gdb/src/gdb/progspace.c File Reference
/home/stan/gdb/src/gdb/progspace.c File Reference
#include "defs.h"
#include "gdbcmd.h"
#include "objfiles.h"
#include "arch-utils.h"
#include "gdbcore.h"
#include "solib.h"
#include "gdbthread.h"
Classes
struct address_space
Functions
struct address_space * new_address_space (void)
struct address_space * maybe_new_address_space (void)
static void free_address_space (struct address_space *aspace)
int address_space_num (struct address_space *aspace)
static void init_address_spaces (void)
struct program_space * add_program_space (struct address_space *aspace)
static void release_program_space (struct program_space *pspace)
void remove_program_space (struct program_space *pspace)
struct program_space * clone_program_space (struct program_space *dest, struct program_space *src)
void set_current_program_space (struct program_space *pspace)
static void restore_program_space (void *arg)
struct cleanup * save_current_program_space (void)
static int pspace_empty_p (struct program_space *pspace)
void prune_program_spaces (void)
static void print_program_space (struct ui_out *uiout, int requested)
static int valid_program_space_id (int num)
static void maintenance_info_program_spaces_command (char *args, int from_tty)
int number_of_program_spaces (void)
void update_address_spaces (void)
struct cleanup * save_current_space_and_thread (void)
void switch_to_program_space_and_thread (struct program_space *pspace)
void clear_program_space_solib_cache (struct program_space *pspace)
void initialize_progspace (void)
Variables
int last_program_space_num = 0
struct program_space * program_spaces
struct program_space * current_program_space
static int highest_address_space_num
Function Documentation
struct program_space* add_program_space (struct address_space * aspace) [read]
Definition at line 115 of file progspace.c.
References program_space::aspace, last_program_space_num, program_space::next, program_space::num, program_spaces, and XZALLOC.
Referenced by add_inferior_with_spaces(), clone_inferior_command(), follow_exec(), handle_vfork_child_exec_or_exit(), initialize_progspace(), and linux_child_follow_fork().
int address_space_num (struct address_space * aspace)
Definition at line 96 of file progspace.c.
References address_space::num.
Referenced by target_thread_address_space().
void clear_program_space_solib_cache (struct program_space * pspace)
Definition at line 513 of file progspace.c.
References free_char_ptr_vec(), and VEC_free.
Referenced by handle_solib_event(), and release_program_space().
struct program_space* clone_program_space (struct program_space * dest, struct program_space * src) [read]
Definition at line 191 of file progspace.c.
References do_cleanups(), exec_file_attach(), objfile_name(), program_space::pspace_exec_filename, save_current_program_space(), set_current_program_space(), symbol_file_add_main(), and program_space::symfile_object_file.
Referenced by clone_inferior_command(), handle_vfork_child_exec_or_exit(), and linux_child_follow_fork().
static void free_address_space (struct address_space * aspace) [static]
Definition at line 90 of file progspace.c.
References xfree().
Referenced by release_program_space(), and update_address_spaces().
static void init_address_spaces (void) [static]
Definition at line 104 of file progspace.c.
References highest_address_space_num.
Referenced by update_address_spaces().
void initialize_progspace (void)
Definition at line 524 of file progspace.c.
References _, add_cmd(), add_program_space(), class_maintenance, maintenance_info_program_spaces_command(), maintenanceinfolist, and new_address_space().
Referenced by gdb_init().
static void maintenance_info_program_spaces_command (char * args, int from_tty) [static]
Definition at line 392 of file progspace.c.
References _, current_uiout, error(), parse_and_eval_long(), print_program_space(), and valid_program_space_id().
Referenced by initialize_progspace().
struct address_space* maybe_new_address_space (void) [read]
Definition at line 76 of file progspace.c.
References program_space::aspace, gdbarch_has_shared_address_space(), new_address_space(), and target_gdbarch().
Referenced by add_inferior_with_spaces(), clone_inferior_command(), follow_exec(), handle_vfork_child_exec_or_exit(), remote_add_inferior(), and update_address_spaces().
struct address_space* new_address_space (void) [read]
Definition at line 61 of file progspace.c.
References highest_address_space_num, address_space::num, and XZALLOC.
Referenced by initialize_progspace(), linux_child_follow_fork(), maybe_new_address_space(), and update_address_spaces().
int number_of_program_spaces (void)
Definition at line 409 of file progspace.c.
References ALL_PSPACES.
Referenced by print_one_breakpoint_location().
static void print_program_space (struct ui_out * uiout, int requested) [static]
Definition at line 293 of file progspace.c.
References ALL_PSPACES, do_cleanups(), gdb_assert, arm-linux::inf, inferior_list, make_cleanup_ui_out_table_begin_end(), make_cleanup_ui_out_tuple_begin_end(), inferior::next, program_space::num, inferior::num, inferior::pid, pid_to_ptid(), printf_filtered(), prune_program_spaces(), inferior::pspace, program_space::pspace_exec_filename, target_pid_to_str(), ui_left, ui_out_field_int(), ui_out_field_skip(), ui_out_field_string(), ui_out_table_body(), ui_out_table_header(), and ui_out_text().
Referenced by maintenance_info_program_spaces_command().
void prune_program_spaces (void)
Definition at line 266 of file progspace.c.
References current_program_space, program_space::next, program_spaces, pspace_empty_p(), and release_program_space().
Referenced by print_program_space(), and prune_inferiors().
static int pspace_empty_p (struct program_space * pspace) [static]
Definition at line 254 of file progspace.c.
References find_inferior_for_program_space().
Referenced by prune_program_spaces().
static void release_program_space (struct program_space * pspace) [static]
Definition at line 139 of file progspace.c.
References program_space::aspace, breakpoint_program_space_exit(), clear_program_space_solib_cache(), do_cleanups(), exec_close(), free_address_space(), free_all_objfiles(), gdb_assert, gdbarch_has_shared_address_space(), no_shared_libraries(), resize_section_table(), save_current_program_space(), set_current_program_space(), target_gdbarch(), program_space::target_sections, and xfree().
Referenced by prune_program_spaces(), and remove_program_space().
void remove_program_space (struct program_space * pspace)
Definition at line 166 of file progspace.c.
References program_space::next, program_spaces, and release_program_space().
static void restore_program_space (void * arg) [static]
Definition at line 231 of file progspace.c.
References set_current_program_space().
Referenced by save_current_program_space().
struct cleanup* save_current_program_space (void) [read]
Definition at line 243 of file progspace.c.
References make_cleanup(), and restore_program_space().
Referenced by breakpoint_re_set(), clone_program_space(), create_longjmp_master_breakpoint(), create_std_terminate_master_breakpoint(), decode_line_1(), decode_line_full(), exec_close_1(), handle_vfork_child_exec_or_exit(), linux_child_follow_fork(), print_breakpoint_location(), ps_pglobal_lookup(), release_program_space(), and save_current_space_and_thread().
struct cleanup* save_current_space_and_thread (void) [read]
Definition at line 467 of file progspace.c.
References make_cleanup_restore_current_thread(), and save_current_program_space().
Referenced by add_inferior_command(), bp_loc_is_permanent(), clone_inferior_command(), download_tracepoint_locations(), handle_vfork_child_exec_or_exit(), insert_breakpoint_locations(), mi_cmd_exec_run(), prepare_re_set_context(), remove_breakpoint(), resolve_sal_pc(), skip_prologue_sal(), and update_inserted_breakpoint_locations().
void set_current_program_space (struct program_space * pspace)
Definition at line 214 of file progspace.c.
References gdb_assert, and reinit_frame_cache().
Referenced by add_inferior_command(), add_matching_symbols_to_info(), clone_program_space(), convert_linespec_to_sals(), create_longjmp_master_breakpoint(), create_sals_line_offset(), create_std_terminate_master_breakpoint(), decode_digits_list_mode(), decode_digits_ordinary(), exec_close_1(), find_method(), follow_exec(), handle_inferior_event(), handle_vfork_child_exec_or_exit(), inferior_command(), iterate_over_all_matching_symtabs(), linux_child_follow_fork(), mi_cmd_execute(), mi_cmd_remove_inferior(), print_breakpoint_location(), ps_pglobal_lookup(), release_program_space(), restore_program_space(), run_one_inferior(), search_minsyms_for_name(), switch_to_program_space_and_thread(), switch_to_thread(), and VEC().
void switch_to_program_space_and_thread (struct program_space * pspace)
Definition at line 485 of file progspace.c.
References any_live_thread_of_process(), find_inferior_for_program_space(), arm-linux::inf, null_ptid, inferior::pid, thread_info::ptid, set_current_program_space(), and switch_to_thread().
Referenced by bp_loc_is_permanent(), download_tracepoint_locations(), insert_breakpoint_locations(), prepare_re_set_context(), remove_breakpoint(), resolve_sal_pc(), skip_prologue_sal(), update_breakpoint_locations(), and update_inserted_breakpoint_locations().
void update_address_spaces (void)
Definition at line 432 of file progspace.c.
References ALL_PSPACES, program_space::aspace, inferior::aspace, free_address_space(), gdbarch_has_global_solist(), gdbarch_has_shared_address_space(), arm-linux::inf, inferior_list, init_address_spaces(), maybe_new_address_space(), new_address_space(), inferior::next, inferior::pspace, and target_gdbarch().
Referenced by remote_start_remote().
static int valid_program_space_id (int num) [static]
Definition at line 376 of file progspace.c.
References ALL_PSPACES, and program_space::num.
Referenced by maintenance_info_program_spaces_command().
Variable Documentation
struct program_space* current_program_space
Definition at line 35 of file progspace.c.
Referenced by allocate_objfile(), auto_load_info_scripts(), bpfinishpy_init(), breakpoint_init_inferior(), breakpoint_re_set_thread(), breakpoint_xfer_memory(), call_function_by_hand(), check_status_catch_solib(), clear_section_scripts(), create_breakpoint(), create_internal_breakpoint(), create_new_frame(), disable_breakpoints_before_startup(), disable_breakpoints_in_shlibs(), display_command(), do_one_display(), elf_gnu_ifunc_resolve_by_cache(), elf_gnu_ifunc_resolve_by_got(), elf_gnu_ifunc_resolver_return_stop(), enable_breakpoints_after_startup(), filter_sals(), find_function_start_sal(), find_pc_sect_line(), find_pc_section(), follow_exec(), func_command(), get_current_frame(), get_darwin_info(), get_dsbt_info(), get_dynamics_objfile(), get_jit_program_space_data(), get_svr4_info(), get_tcb_types_info(), handle_vfork_child_exec_or_exit(), init_catchpoint(), initialize_inferiors(), jv_per_objfile_free(), line_info(), linespec_expression_to_pc(), linespec_state_constructor(), mark_breakpoints_out(), objfiles_changed(), post_create_inferior(), print_solib_event(), prune_program_spaces(), ptid_from_atcb_common(), read_atcb(), read_known_tasks_list(), remote_add_inferior(), remove_jit_event_breakpoints(), remove_solib_event_breakpoints(), remove_thread_event_breakpoints(), select_source_symtab(), set_breakpoint_location_function(), set_longjmp_breakpoint(), set_longjmp_breakpoint_for_call_dummy(), set_std_terminate_breakpoint(), solib_add(), source_gdb_script_for_objfile(), svr4_handle_solib_event(), tui_set_disassem_content(), update_breakpoints_after_exec(), update_solib_list(), watch_command_1(), and watchpoint_in_thread_scope().
int highest_address_space_num [static]
Definition at line 38 of file progspace.c.
Referenced by init_address_spaces(), and new_address_space().
int last_program_space_num = 0
Definition at line 29 of file progspace.c.
Referenced by add_program_space().
struct program_space* program_spaces
Definition at line 32 of file progspace.c.
Referenced by ada_new_objfile_observer(), add_program_space(), prune_program_spaces(), and remove_program_space().