GDB (xrefs): /home/stan/gdb/src/gdb/prologue-value.h File Reference
/home/stan/gdb/src/gdb/prologue-value.h File Reference
Classes
struct prologue_value
Typedefs
typedef struct prologue_value pv_t
Enumerations
enum pv_boolean { pv_maybe, pv_definite_yes, pv_definite_no }
Functions
pv_t pv_unknown (void)
pv_t pv_constant (CORE_ADDR k)
pv_t pv_register (int reg, CORE_ADDR k)
pv_t pv_add (pv_t a, pv_t b)
pv_t pv_add_constant (pv_t v, CORE_ADDR k)
pv_t pv_subtract (pv_t a, pv_t b)
pv_t pv_logical_and (pv_t a, pv_t b)
int pv_is_identical (pv_t a, pv_t b)
int pv_is_constant (pv_t a)
int pv_is_register (pv_t a, int r)
int pv_is_register_k (pv_t a, int r, CORE_ADDR k)
enum pv_boolean pv_is_array_ref (pv_t addr, CORE_ADDR size, pv_t array_addr, CORE_ADDR array_len, CORE_ADDR elt_size, int *i)
struct pv_area * make_pv_area (int base_reg, int addr_bit)
void free_pv_area (struct pv_area *area)
struct cleanup * make_cleanup_free_pv_area (struct pv_area *area)
void pv_area_store (struct pv_area *area, pv_t addr, CORE_ADDR size, pv_t value)
pv_t pv_area_fetch (struct pv_area *area, pv_t addr, CORE_ADDR size)
int pv_area_store_would_trash (struct pv_area *area, pv_t addr)
int pv_area_find_reg (struct pv_area *area, struct gdbarch *gdbarch, int reg, CORE_ADDR *offset_p)
void pv_area_scan (struct pv_area *area, void(*func)(void *closure, pv_t addr, CORE_ADDR size, pv_t value), void *closure)
Typedef Documentation
typedef struct prologue_value pv_t
Definition at line 149 of file prologue-value.h.
Enumeration Type Documentation
enum pv_boolean
Enumerator:
pv_maybe
pv_definite_yes
pv_definite_no
Definition at line 198 of file prologue-value.h.
Function Documentation
void free_pv_area (struct pv_area * area)
Definition at line 360 of file prologue-value.c.
References clear_entries(), and xfree().
Referenced by do_free_pv_area_cleanup(), and s390_analyze_prologue().
struct cleanup* make_cleanup_free_pv_area (struct pv_area * area) [read]
Definition at line 375 of file prologue-value.c.
References do_free_pv_area_cleanup(), and make_cleanup().
Referenced by aarch64_analyze_prologue(), arm_analyze_prologue(), m32c_analyze_prologue(), mep_analyze_prologue(), mn10300_analyze_prologue(), msp430_analyze_prologue(), rl78_analyze_prologue(), rx_analyze_prologue(), and thumb_analyze_prologue().
struct pv_area* make_pv_area (int base_reg, int addr_bit) [read]
Definition at line 317 of file prologue-value.c.
References pv_area::addr_mask, pv_area::base_reg, pv_area::entry, memset(), and xmalloc().
Referenced by aarch64_analyze_prologue(), arm_analyze_prologue(), m32c_analyze_prologue(), mep_analyze_prologue(), mn10300_analyze_prologue(), msp430_analyze_prologue(), rl78_analyze_prologue(), rx_analyze_prologue(), s390_analyze_prologue(), and thumb_analyze_prologue().
pv_t pv_add (pv_t a, pv_t b)
Definition at line 84 of file prologue-value.c.
References constant_last(), prologue_value::k, prologue_value::kind, pv_constant(), pv_register(), pv_unknown(), and prologue_value::reg.
Referenced by mn10300_analyze_prologue(), pv_add_constant(), s390_addr(), s390_analyze_prologue(), and thumb_analyze_prologue().
pv_t pv_add_constant (pv_t v, CORE_ADDR k)
Definition at line 107 of file prologue-value.c.
References pv_add(), and pv_constant().
Referenced by aarch64_analyze_prologue(), arm_analyze_prologue(), m32c_decode_sd23(), m32c_decode_srcdest4(), m32c_pv_enter(), m32c_pv_push(), mep_analyze_prologue(), mn10300_analyze_prologue(), msp430_analyze_prologue(), push_reg(), rl78_analyze_prologue(), rx_analyze_prologue(), s390_analyze_prologue(), and thumb_analyze_prologue().
pv_t pv_area_fetch (struct pv_area * area, pv_t addr, CORE_ADDR size)
Definition at line 517 of file prologue-value.c.
References pv_area::entry, find_entry(), prologue_value::k, offset, area_entry::offset, pv_area_store_would_trash(), pv_unknown(), area_entry::size, and area_entry::value.
Referenced by m32c_srcdest_fetch(), mep_analyze_prologue(), and s390_load().
int pv_area_find_reg (struct pv_area * area, struct gdbarch * gdbarch, int reg, CORE_ADDR * offset_p)
Definition at line 540 of file prologue-value.c.
References pv_area::entry, prologue_value::k, prologue_value::kind, area_entry::next, area_entry::offset, prologue_value::reg, register_size(), area_entry::size, and area_entry::value.
Referenced by aarch64_analyze_prologue(), arm_analyze_prologue(), is_arg_spill(), m32c_is_arg_spill(), m32c_is_struct_return(), and thumb_analyze_prologue().
void pv_area_scan (struct pv_area * area, void(*)(void *closure, pv_t addr, CORE_ADDR size, pv_t value) func, void * closure)
Definition at line 569 of file prologue-value.c.
References pv_area::base_reg, pv_area::entry, func, prologue_value::k, prologue_value::kind, area_entry::next, area_entry::offset, prologue_value::reg, area_entry::size, and area_entry::value.
Referenced by m32c_analyze_prologue(), mep_analyze_prologue(), mn10300_analyze_prologue(), msp430_analyze_prologue(), rl78_analyze_prologue(), rx_analyze_prologue(), and s390_analyze_prologue().
void pv_area_store (struct pv_area * area, pv_t addr, CORE_ADDR size, pv_t value)
Definition at line 454 of file prologue-value.c.
References clear_entries(), pv_area::entry, find_entry(), prologue_value::k, prologue_value::kind, area_entry::next, offset, area_entry::offset, overlaps(), area_entry::prev, pv_area_store_would_trash(), size, area_entry::size, area_entry::value, xfree(), and xmalloc().
Referenced by aarch64_analyze_prologue(), arm_analyze_prologue(), m32c_pv_push(), m32c_srcdest_store(), mep_analyze_prologue(), mn10300_analyze_prologue(), msp430_analyze_prologue(), push_reg(), rl78_analyze_prologue(), rx_analyze_prologue(), s390_store(), and thumb_analyze_prologue().
int pv_area_store_would_trash (struct pv_area * area, pv_t addr)
Definition at line 382 of file prologue-value.c.
References pv_area::base_reg, prologue_value::kind, and prologue_value::reg.
Referenced by aarch64_analyze_prologue(), arm_analyze_prologue(), m32c_pv_enter(), m32c_pv_push(), m32c_srcdest_store(), mep_analyze_prologue(), pv_area_fetch(), pv_area_store(), s390_store(), and thumb_analyze_prologue().
pv_t pv_constant (CORE_ADDR k)
Definition at line 38 of file prologue-value.c.
References prologue_value::k, prologue_value::kind, and prologue_value::reg.
Referenced by m32c_analyze_prologue(), m32c_decode_sd23(), m32c_decode_srcdest4(), mn10300_analyze_prologue(), pv_add(), pv_add_constant(), pv_logical_and(), pv_subtract(), s390_addr(), s390_analyze_prologue(), s390_load(), and thumb_analyze_prologue().
enum pv_boolean pv_is_array_ref (pv_t addr, CORE_ADDR size, pv_t array_addr, CORE_ADDR array_len, CORE_ADDR elt_size, int * i)
Definition at line 235 of file prologue-value.c.
References prologue_value::k, prologue_value::kind, offset, pv_definite_no, pv_definite_yes, pv_maybe, and pv_subtract().
int pv_is_constant (pv_t a)
Definition at line 211 of file prologue-value.c.
References prologue_value::kind.
Referenced by m32c_analyze_prologue(), s390_load(), s390_store(), and thumb_analyze_prologue().
int pv_is_identical (pv_t a, pv_t b)
Definition at line 191 of file prologue-value.c.
References gdb_assert_not_reached, prologue_value::k, prologue_value::kind, and prologue_value::reg.
Referenced by m32c_analyze_prologue(), mep_analyze_prologue(), s390_analyze_prologue(), and s390_prologue_frame_unwind_cache().
int pv_is_register (pv_t a, int r)
Definition at line 218 of file prologue-value.c.
References prologue_value::kind, and prologue_value::reg.
Referenced by aarch64_analyze_prologue(), arm_analyze_prologue(), check_for_saved(), is_arg_spill(), m32c_analyze_prologue(), m32c_is_arg_spill(), m32c_is_struct_return(), m32c_pushm_is_reg_save(), mep_analyze_prologue(), mn10300_analyze_prologue(), msp430_analyze_prologue(), rl78_analyze_prologue(), rx_analyze_prologue(), s390_check_for_saved(), s390_prologue_frame_unwind_cache(), and thumb_analyze_prologue().
int pv_is_register_k (pv_t a, int r, CORE_ADDR k)
Definition at line 226 of file prologue-value.c.
References prologue_value::k, prologue_value::kind, and prologue_value::reg.
Referenced by m32c_analyze_prologue(), m32c_pushm_is_reg_save(), mep_analyze_prologue(), s390_analyze_prologue(), s390_check_for_saved(), and s390_store().
pv_t pv_logical_and (pv_t a, pv_t b)
Definition at line 155 of file prologue-value.c.
References constant_last(), prologue_value::k, prologue_value::kind, pv_constant(), pv_unknown(), and prologue_value::reg.
pv_t pv_register (int reg, CORE_ADDR k)
Definition at line 51 of file prologue-value.c.
References prologue_value::k, prologue_value::kind, and prologue_value::reg.
Referenced by aarch64_analyze_prologue(), arm_analyze_prologue(), m32c_analyze_prologue(), mep_analyze_prologue(), mn10300_analyze_prologue(), msp430_analyze_prologue(), pv_add(), pv_subtract(), rl78_analyze_prologue(), rx_analyze_prologue(), s390_analyze_prologue(), and thumb_analyze_prologue().
pv_t pv_subtract (pv_t a, pv_t b)
Definition at line 116 of file prologue-value.c.
References constant_last(), prologue_value::k, prologue_value::kind, pv_constant(), pv_register(), pv_unknown(), and prologue_value::reg.
Referenced by pv_is_array_ref(), s390_analyze_prologue(), and s390_store().
pv_t pv_unknown (void)
Definition at line 29 of file prologue-value.c.
Referenced by aarch64_analyze_prologue(), m32c_decode_sd23(), m32c_decode_srcdest4(), m32c_srcdest_fetch(), m32c_srcdest_store(), pv_add(), pv_area_fetch(), pv_logical_and(), and pv_subtract().