GDB (xrefs): /home/stan/gdb/src/gdb/psymtab.h File Reference
/home/stan/gdb/src/gdb/psymtab.h File Reference
#include "symfile.h"
Functions
struct psymbol_bcache * psymbol_bcache_init (void)
void psymbol_bcache_free (struct psymbol_bcache *)
struct bcache * psymbol_bcache_get_bcache (struct psymbol_bcache *)
void expand_partial_symbol_names (int(*fun)(const char *, void *), void *data)
void map_partial_symbol_filenames (symbol_filename_ftype *fun, void *data, int need_fullname)
struct objfile * require_partial_symbols (struct objfile *objfile, int verbose)
Variables
struct quick_symbol_functions psym_functions
struct quick_symbol_functions dwarf2_gdb_index_functions
Function Documentation
void expand_partial_symbol_names (int(*)(const char *, void *) fun, void * data)
Definition at line 2092 of file psymtab.c.
References ALL_DOMAIN, ALL_OBJFILES, quick_symbol_functions::expand_symtabs_matching, sym_fns::qf, and objfile::sf.
Referenced by VEC().
void map_partial_symbol_filenames (symbol_filename_ftype * fun, void * data, int need_fullname)
Definition at line 2106 of file psymtab.c.
References ALL_OBJFILES, quick_symbol_functions::map_symbol_filenames, sym_fns::qf, and objfile::sf.
Referenced by gdb_listfiles(), mi_cmd_file_list_exec_source_files(), and sources_info().
void psymbol_bcache_free (struct psymbol_bcache *)
Definition at line 1540 of file psymtab.c.
References psymbol_bcache::bcache, bcache_xfree(), and xfree().
Referenced by free_objfile(), and reread_symbols().
struct bcache* psymbol_bcache_get_bcache (struct psymbol_bcache *) [read]
Definition at line 1552 of file psymtab.c.
References psymbol_bcache::bcache.
Referenced by print_objfile_statistics(), and print_symbol_bcache_statistics().
struct psymbol_bcache* psymbol_bcache_init (void) [read]
Definition at line 1531 of file psymtab.c.
References psymbol_bcache::bcache, bcache(), bcache_xmalloc(), psymbol_compare(), psymbol_hash(), and XCALLOC.
Referenced by allocate_objfile(), and reread_symbols().
struct objfile* require_partial_symbols (struct objfile * objfile, int verbose) [read]
Definition at line 78 of file psymtab.c.
References _, objfile::flags, gdb_flush(), gdb_stdout, OBJF_PSYMTABS_READ, objfile_has_symbols(), objfile_name(), printf_unfiltered(), objfile::sf, sym_fns::sym_read_psymbols, and wrap_here().
Referenced by read_symbols().
Variable Documentation
struct quick_symbol_functions dwarf2_gdb_index_functions
Definition at line 4047 of file dwarf2read.c.
struct quick_symbol_functions psym_functions
Definition at line 1420 of file psymtab.c.