GDB (xrefs): /home/stan/gdb/src/gdb/common/ptid.h File Reference
/home/stan/gdb/src/gdb/common/ptid.h File Reference
Classes
struct ptid
Typedefs
typedef struct ptid ptid_t
Functions
ptid_t ptid_build (int pid, long lwp, long tid)
ptid_t pid_to_ptid (int pid)
int ptid_get_pid (ptid_t ptid)
long ptid_get_lwp (ptid_t ptid)
long ptid_get_tid (ptid_t ptid)
int ptid_equal (ptid_t ptid1, ptid_t ptid2)
int ptid_is_pid (ptid_t ptid)
int ptid_lwp_p (ptid_t ptid)
int ptid_tid_p (ptid_t ptid)
Variables
ptid_t null_ptid
ptid_t minus_one_ptid
Typedef Documentation
typedef struct ptid ptid_t
Definition at line 42 of file ptid.h.
Function Documentation
ptid_t pid_to_ptid (int pid)
Definition at line 43 of file ptid.c.
References ptid_build().
Referenced by aarch64_notify_debug_reg_change(), aix_thread_resume(), aix_thread_wait(), aix_thread_xfer_partial(), amd64_linux_dr_set_addr(), amd64_linux_dr_set_control(), attach_command(), attach_command_post_wait(), check_zombie_leaders(), core_open(), core_pid_to_str(), darwin_attach(), darwin_detach(), do_initial_windows_stuff(), extended_remote_attach_1(), fork_id_to_ptid(), fork_inferior(), go32_create_inferior(), go32_wait(), handle_inferior_event(), i386_linux_dr_set_addr(), i386_linux_dr_set_control(), i386_linux_resume(), inf_ptrace_attach(), inf_ptrace_create_inferior(), inf_ptrace_detach(), inf_ptrace_wait(), inf_validate_procs(), inferior_pid_to_str(), init_infwait_state(), irix_solib_create_inferior_hook(), linux_child_follow_fork(), linux_handle_extended_wait(), linux_handle_syscall_trap(), linux_nat_detach(), linux_nat_filter_event(), linux_nat_kill(), linux_nat_resume(), linux_nat_wait_1(), linux_nat_xfer_partial(), lwp_to_thread(), pid_to_prc(), prepare_for_detach(), print_exited_reason(), print_inferior_quit_action(), print_program_space(), procfs_attach(), procfs_create_inferior(), procfs_detach(), procfs_first_available(), procfs_init_inferior(), procfs_wait(), remote_detach_1(), remote_notice_new_inferior(), remote_parse_stop_reply(), resume_lwp(), resume_stopped_resumed_lwps(), rs6000_wait(), run_command_1(), sol_thread_detach(), spu_child_wait(), startup_inferior(), thread_id_to_pid(), thread_to_lwp(), user_visible_resume_ptid(), and windows_attach().
ptid_t ptid_build (int pid, long lwp, long tid)
Definition at line 30 of file ptid.c.
References ptid::lwp, ptid::pid, and ptid::tid.
Referenced by _initialize_remote_m32r(), _initialize_remote_mips(), _initialize_remote_monitors(), add_fork(), add_to_thread_list(), agent_run_command(), aix_thread_get_ada_task_ptid(), append_resumption(), attach_thread(), bsd_kvm_add_target(), bsd_uthread_find_new_threads(), bsd_uthread_wait(), check_event(), darwin_check_new_threads(), darwin_decode_message(), darwin_get_ada_task_ptid(), darwin_init_thread_list(), darwin_wait(), default_get_ada_task_ptid(), do_attach(), fake_create_process(), find_new_threads_callback(), get_cores_used_by_process(), get_sim_inferior_data(), get_windows_debug_event(), gnu_attach(), gnu_create_inferior(), gnu_wait(), inf_validate_procs(), linux_child_follow_fork(), linux_handle_extended_wait(), linux_nat_attach(), linux_nat_filter_event(), linux_nat_wait_1(), linux_xfer_osdata_threads(), lwp_to_thread(), pid_to_ptid(), procfs_find_new_threads(), procfs_init_inferior(), procfs_notice_thread(), procfs_wait(), ps_lgetfpregs(), ps_lgetregs(), ps_lsetfpregs(), ps_lsetregs(), ptid_build_from_info(), ravenscar_get_ada_task_ptid(), ravenscar_running_thread(), read_ptid(), remote_get_ada_task_ptid(), remote_newthread_step(), remote_stop_ns(), sol_find_new_threads_callback(), sync_threadlists(), thread_get_info_callback(), thread_to_lwp(), VEC(), windows_get_ada_task_ptid(), and windows_wait().
int ptid_equal (ptid_t ptid1, ptid_t ptid2)
Definition at line 75 of file ptid.c.
References ptid::lwp, ptid::pid, and ptid::tid.
Referenced by ada_get_task_number(), add_current_inferior_and_thread(), add_thread_silent(), adjust_pc_after_break(), agent_run_command(), append_pending_thread_resumptions(), append_resumption(), bpstat_clear_actions(), bpstat_do_actions(), breakpoint_about_to_proceed(), call_function_by_hand(), child_terminal_info(), clear_inline_frame_state(), clear_proceed_status(), context_switch(), core_open(), darwin_create_inferior(), darwin_kill_inferior(), darwin_resume(), dcache_info(), dcache_xfer_memory(), dec_thread_fetch_registers(), dec_thread_store_registers(), dec_thread_wait(), default_child_has_all_memory(), default_child_has_execution(), default_child_has_memory(), default_child_has_registers(), default_child_has_stack(), delete_checkpoint_command(), delete_fork(), delete_lwp(), delete_step_thread_step_resume_breakpoint(), delete_thread_1(), detach_checkpoint_command(), detach_command(), displaced_step_fixup(), displaced_step_prepare(), display_tib(), do_captured_list_thread_ids(), do_restore_current_thread_cleanup(), ensure_valid_thread(), fetch_inferior_event(), find_fork_ptid(), find_thread_object(), find_thread_ptid(), finish_command_continuation(), finish_thread_state(), follow_fork(), gdb_clear_file(), gdb_target_has_execution_command(), gdbsim_create_inferior(), gdbsim_resume(), gdbsim_stop(), gdbsim_thread_alive(), gdbsim_wait(), gdbtk_annotate_signal(), generic_mourn_inferior(), get_current_frame(), get_displaced_step_closure_by_addr(), get_task_from_args(), get_thread_arch_aspace_regcache(), get_thread_arch_regcache(), get_thread_regcache(), gnu_resume(), gnu_wait(), go32_thread_alive(), handle_inferior_event(), handle_syscall_event(), has_stack_frames(), in_thread_list(), inf_validate_procs(), inferior_call_waitpid(), inferior_event_handler(), info_checkpoints_command(), info_mach_exceptions_command(), info_mach_ports_command(), info_mach_region_command(), infrun_thread_ptid_changed(), infrun_thread_stop_requested_callback(), infrun_thread_thread_exit(), insert_breakpoint_locations(), kill_command(), kill_if_already_running(), linux_nat_resume(), linux_nat_wait(), linux_nat_wait_1(), linux_nat_xfer_partial(), m32r_pid_to_str(), m32r_thread_alive(), make_cleanup_restore_current_thread(), memory_xfer_partial_1(), mi_about_to_proceed(), mi_execute_command(), mi_on_resume(), mips_error(), monitor_pid_to_str(), monitor_thread_alive(), normal_stop(), notice_new_inferior(), pid_to_thread_id(), ppc_linux_spe_context(), prepare_for_detach(), prepare_to_proceed(), print_ada_task_info(), print_one_catch_fork(), print_one_catch_vfork(), print_thread_info(), proc_set_current_signal(), proceed(), process_stop_reply(), procfs_kill_inferior(), procfs_mourn_inferior(), procfs_resume(), procfs_store_registers(), procfs_wait(), program_info(), ptid_is_pid(), ptid_lwp_p(), ptid_match(), ptid_tid_p(), ravenscar_fetch_registers(), ravenscar_prepare_to_store(), ravenscar_runtime_initialized(), ravenscar_store_registers(), ravenscar_update_inferior_ptid(), read_ptid(), regcache_thread_ptid_changed(), remote_notice_new_inferior(), remote_parse_stop_reply(), remote_pid_to_str(), remote_read_description(), remote_resume(), remote_start_remote(), remote_stop_ns(), remote_thread_alive(), remote_threads_extra_info(), remote_threads_info(), remote_vcont_resume(), remote_wait_as(), set_enable_mach_exceptions(), set_executing(), set_running(), set_sig_thread_cmd(), set_stop_requested(), set_thread(), siginfo_make_value(), sol_thread_wait(), stop_reply_match_ptid_and_ws(), switch_to_thread(), thread_command(), thread_db_resume(), thread_name_command(), tlb_make_value(), tui_make_status_line(), update_inserted_breakpoint_locations(), update_solib_list(), validate_siginfo_access(), VEC(), watchpoint_in_thread_scope(), and windows_resume().
long ptid_get_lwp (ptid_t ptid)
Definition at line 59 of file ptid.c.
References ptid::lwp.
Referenced by aarch64_linux_prepare_to_resume(), aix_thread_resume(), amd64_linux_dr_get(), amd64_linux_dr_set(), amd64_linux_fetch_inferior_registers(), amd64_linux_read_description(), amd64_linux_store_inferior_registers(), arm_linux_insert_hw_breakpoint(), arm_linux_insert_watchpoint(), arm_linux_new_thread(), arm_linux_read_description(), arm_linux_remove_hw_breakpoint(), arm_linux_remove_watchpoint(), arm_linux_thread_exit(), can_use_watchpoint_cond_accel(), checkpoint_command(), core_pid_to_str(), cur_thread(), detach_callback(), fetch_inferior_registers(), fetch_ppc_memory(), fetch_ppc_register(), fetch_register(), find_lwp_pid(), get_core_register_section(), get_core_siginfo(), get_pending_status(), get_thread_id(), gnu_fetch_registers(), gnu_pid_to_str(), gnu_resume(), gnu_store_registers(), gnu_thread_alive(), gnu_wait(), hppa_hpux_fetch_register(), hppa_hpux_store_register(), i386_linux_dr_get(), i386_linux_dr_set(), i386_linux_fetch_inferior_registers(), i386_linux_read_description(), i386_linux_store_inferior_registers(), i386_windows_core_pid_to_str(), ia64_hpux_fetch_rnat_register(), ia64_hpux_read_memory_bs(), ia64_hpux_read_register_from_save_state_t(), ia64_hpux_write_memory_bs(), ia64_hpux_write_register_to_saved_state_t(), ia64_linux_fetch_register(), ia64_linux_store_register(), inf_ptrace_fetch_register(), inf_ptrace_store_register(), info_task(), kill_callback(), kill_wait_callback(), lin_lwp_attach_lwp(), linux_child_follow_fork(), linux_collect_thread_registers(), linux_common_core_of_thread(), linux_core_pid_to_str(), linux_handle_extended_wait(), linux_handle_syscall_trap(), linux_nat_attach(), linux_nat_collect_thread_registers(), linux_nat_filter_event(), linux_nat_get_siginfo(), linux_nat_pid_to_str(), linux_nat_post_attach_wait(), linux_nat_resume(), linux_nat_stop_lwp(), linux_nat_thread_address_space(), linux_nat_thread_name(), linux_nat_wait_1(), linux_nat_xfer_partial(), linux_thread_alive(), linux_xfer_siginfo(), lwp_to_thread(), m32r_linux_fetch_inferior_registers(), m32r_linux_store_inferior_registers(), m68k_linux_fetch_inferior_registers(), m68k_linux_store_inferior_registers(), maybe_clear_ignore_sigint(), mips64_linux_regsets_fetch_registers(), mips64_linux_regsets_store_registers(), mips_linux_can_use_hw_breakpoint(), mips_linux_insert_watchpoint(), mips_linux_new_thread(), mips_linux_read_description(), mips_linux_region_ok_for_hw_watchpoint(), mips_linux_stopped_by_watchpoint(), ppc_linux_can_use_hw_breakpoint(), ppc_linux_fetch_inferior_registers(), ppc_linux_insert_hw_breakpoint(), ppc_linux_insert_mask_watchpoint(), ppc_linux_insert_watchpoint(), ppc_linux_new_thread(), ppc_linux_read_description(), ppc_linux_remove_hw_breakpoint(), ppc_linux_remove_mask_watchpoint(), ppc_linux_remove_watchpoint(), ppc_linux_stopped_data_address(), ppc_linux_store_inferior_registers(), ppc_linux_target_wordsize(), ppc_linux_thread_exit(), procfs_fetch_registers(), procfs_pid_to_str(), procfs_resume(), procfs_thread_alive(), procfs_wait(), ptid_cmp(), ptid_is_pid(), ptid_lwp_p(), resume_lwp(), resume_stopped_resumed_lwps(), s390_fix_watch_points(), s390_inferior_tid(), set_sig_thread_cmd(), sol2_core_pid_to_str(), solaris_pid_to_str(), sparc_fetch_inferior_registers(), sparc_store_inferior_registers(), sparc_xfer_wcookie(), spu_child_post_startup_inferior(), stop_and_resume_callback(), stop_callback(), stop_wait_callback(), store_debug_register(), store_inferior_registers(), store_ppc_memory(), store_register(), thpy_get_ptid(), thread_db_attach_lwp(), thread_db_pid_to_str(), thread_from_lwp(), VEC(), wait_lwp(), and write_watchpoint_regs().
int ptid_get_pid (ptid_t ptid)
Definition at line 51 of file ptid.c.
References ptid::pid.
Referenced by aarch64_handle_aligned_watchpoint(), aarch64_handle_breakpoint(), aarch64_handle_unaligned_watchpoint(), aarch64_linux_child_post_startup_inferior(), aarch64_linux_insert_hw_breakpoint(), aarch64_linux_insert_watchpoint(), aarch64_linux_new_fork(), aarch64_linux_prepare_to_resume(), aarch64_linux_remove_hw_breakpoint(), aarch64_linux_remove_watchpoint(), aarch64_linux_stopped_data_address(), aarch64_notify_debug_reg_change(), ada_exception_support_info_sniffer(), ada_get_task_number(), add_current_inferior_and_thread(), add_fork(), add_thread_db_info(), aix_thread_get_ada_task_ptid(), aix_thread_resume(), aix_thread_wait(), aix_thread_xfer_partial(), alphabsd_fetch_inferior_registers(), alphabsd_store_inferior_registers(), amd64_linux_dr_get(), amd64_linux_dr_set(), amd64_linux_dr_set_addr(), amd64_linux_dr_set_control(), amd64_linux_fetch_inferior_registers(), amd64_linux_new_fork(), amd64_linux_prepare_to_resume(), amd64_linux_read_description(), amd64_linux_store_inferior_registers(), amd64bsd_fetch_inferior_registers(), amd64bsd_store_inferior_registers(), any_live_thread_of_process(), any_thread_of_process(), append_resumption(), attach_command(), attach_command_post_wait(), attach_thread(), bsd_uthread_find_new_threads(), bsd_uthread_pid_to_str(), bsd_uthread_wait(), check_event(), check_for_thread_db(), checkpoint_command(), clear_inline_frame_state(), cmd_record_save(), collect_cores(), core_close(), core_pid_to_str(), create_thread_object(), darwin_detach(), darwin_get_ada_task_ptid(), darwin_pid_to_str(), darwin_resume(), darwin_wait(), debug_to_post_startup_inferior(), default_get_ada_task_ptid(), delete_checkpoint_command(), delete_fork(), delete_thread_object(), delete_thread_of_inferior(), detach_breakpoints(), detach_callback(), detach_checkpoint_command(), discard_pending_stop_replies(), displaced_step_fixup(), displaced_step_prepare(), do_attach(), do_detach(), do_restore_current_thread_cleanup(), enable_thread_event(), enable_thread_event_reporting(), exec_one_dummy_insn(), extended_remote_kill(), fbsd_find_memory_regions(), fbsd_make_corefile_notes(), fetch_fp_register(), fetch_fp_regs(), fetch_inferior_event(), fetch_inferior_registers(), fetch_ppc_memory(), fetch_ppc_register(), fetch_register(), fetch_regs(), find_fork_pid(), find_lwp_pid(), find_signalled_thread(), find_thread_object(), find_thread_of_process(), finish_thread_state(), first_thread_of_process(), fork_save_infrun_state(), gcore_command(), gdbsim_close_inferior(), gdbsim_create_inferior(), gdbsim_resume(), gdbsim_stop(), gdbsim_wait(), generic_mourn_inferior(), get_displaced_step_closure_by_addr(), get_signaled_thread(), get_sim_inferior_data_by_ptid(), get_thread_id(), gnu_resume(), handle_inferior_event(), have_threads(), have_threads_callback(), hppa_hpux_fetch_register(), hppa_hpux_store_register(), hppabsd_fetch_registers(), hppabsd_store_registers(), hppanbsd_fetch_registers(), hppanbsd_store_registers(), i386_cleanup_dregs(), i386_insert_hw_breakpoint(), i386_insert_watchpoint(), i386_linux_dr_get(), i386_linux_dr_set(), i386_linux_dr_set_addr(), i386_linux_dr_set_control(), i386_linux_fetch_inferior_registers(), i386_linux_new_fork(), i386_linux_prepare_to_resume(), i386_linux_read_description(), i386_linux_resume(), i386_linux_store_inferior_registers(), i386_region_ok_for_watchpoint(), i386_remove_hw_breakpoint(), i386_remove_watchpoint(), i386_stopped_data_address(), i386_update_inferior_debug_regs(), i386bsd_fetch_inferior_registers(), i386bsd_store_inferior_registers(), i386fbsd_resume(), ia64_hpux_fetch_rnat_register(), ia64_hpux_get_load_info_addr(), ia64_hpux_mourn_inferior(), ia64_hpux_read_memory_bs(), ia64_hpux_read_register_from_save_state_t(), ia64_hpux_write_memory_bs(), ia64_hpux_write_register_to_saved_state_t(), ia64_hpux_xfer_memory(), ia64_linux_fetch_register(), ia64_linux_store_register(), inf_has_multiple_thread_cb(), inf_ptrace_detach(), inf_ptrace_fetch_register(), inf_ptrace_kill(), inf_ptrace_mourn_inferior(), inf_ptrace_resume(), inf_ptrace_store_register(), inf_ptrace_thread_alive(), inf_ptrace_wait(), inf_ptrace_xfer_partial(), inferior_command(), infrun_thread_stop_requested_callback(), insert_catch_exec(), insert_catch_fork(), insert_catch_syscall(), insert_catch_vfork(), interrupt_thread_callback(), lin_lwp_attach_lwp(), linux_child_follow_fork(), linux_child_post_startup_inferior(), linux_common_core_of_thread(), linux_corefile_thread_callback(), linux_fill_prpsinfo(), linux_fork_detach(), linux_fork_killall(), linux_fork_mourn_inferior(), linux_handle_extended_wait(), linux_make_corefile_notes(), linux_nat_attach(), linux_nat_detach(), linux_nat_filter_event(), linux_nat_get_siginfo(), linux_nat_kill(), linux_nat_mourn_inferior(), linux_nat_pid_to_str(), linux_nat_switch_fork(), linux_nat_thread_address_space(), linux_nat_thread_name(), linux_nat_wait_1(), linux_proc_xfer_partial(), linux_proc_xfer_spu(), linux_xfer_siginfo(), lwp_to_thread(), m32r_linux_fetch_inferior_registers(), m32r_linux_store_inferior_registers(), m68k_linux_fetch_inferior_registers(), m68k_linux_store_inferior_registers(), m68kbsd_fetch_inferior_registers(), m68kbsd_store_inferior_registers(), m88kbsd_fetch_inferior_registers(), m88kbsd_store_inferior_registers(), memory_xfer_partial_1(), mi_new_thread(), mi_on_resume(), mi_output_running_pid(), mi_thread_exit(), mips64_linux_regsets_fetch_registers(), mips64_linux_regsets_store_registers(), mips64obsd_fetch_inferior_registers(), mips64obsd_store_inferior_registers(), mips_linux_read_description(), mipsnbsd_fetch_inferior_registers(), mipsnbsd_store_inferior_registers(), monitor_close(), monitor_open(), normal_pid_to_str(), num_lwps(), open_map(), pass_signal(), pid_to_prc(), ppc_linux_can_use_hw_breakpoint(), ppc_linux_fetch_inferior_registers(), ppc_linux_read_description(), ppc_linux_store_inferior_registers(), ppc_linux_target_wordsize(), ppcfbsd_fetch_inferior_registers(), ppcfbsd_store_inferior_registers(), ppcnbsd_fetch_inferior_registers(), ppcnbsd_store_inferior_registers(), ppcobsd_fetch_registers(), ppcobsd_store_registers(), prepare_to_proceed(), print_it_catch_fork(), print_it_catch_vfork(), print_one_catch_fork(), print_one_catch_vfork(), print_target_wait_results(), print_thread_info(), proc_find_memory_regions(), proc_trace_syscalls(), proceed_after_attach_callback(), proceed_after_vfork_done(), proceed_thread(), procfs_detach(), procfs_fetch_registers(), procfs_find_new_threads(), procfs_inferior_created(), procfs_info_proc(), procfs_kill_inferior(), procfs_mourn_inferior(), procfs_pass_signals(), procfs_pid_to_str(), procfs_resume(), procfs_set_watchpoint(), procfs_stopped_by_watchpoint(), procfs_stopped_data_address(), procfs_thread_alive(), procfs_wait(), procfs_xfer_auxv(), procfs_xfer_memory(), ps_getpid(), ps_lgetfpregs(), ps_lgetregs(), ps_lsetfpregs(), ps_lsetregs(), ps_pglobal_lookup(), ptid_build_from_info(), ptid_cmp(), ptid_match(), purge_lwp_list(), ravenscar_get_ada_task_ptid(), ravenscar_running_thread(), read_ptid(), remote_detach_1(), remote_get_ada_task_ptid(), remote_newthread_step(), remote_notice_new_inferior(), remote_parse_stop_reply(), remote_pid_to_str(), remote_stop_ns(), remote_thread_alive(), remote_threads_extra_info(), remove_catch_exec(), remove_catch_fork(), remove_catch_syscall(), remove_catch_vfork(), remove_stop_reply_for_inferior(), resume(), resume_lwp(), rs6000_ptrace_ldinfo(), rs6000_wait(), rs6000_xfer_partial(), run_command_1(), run_one_inferior(), s390_fix_watch_points(), s390_inferior_tid(), set_executing(), set_general_process(), set_running(), set_stop_requested(), shnbsd_fetch_inferior_registers(), shnbsd_store_inferior_registers(), sol2_core_pid_to_str(), sol_find_new_threads_callback(), sol_thread_detach(), sol_thread_resume(), sol_thread_wait(), solaris_pid_to_str(), som_solib_create_inferior_hook(), sparc_fetch_inferior_registers(), sparc_store_inferior_registers(), sparc_xfer_wcookie(), spu_child_post_startup_inferior(), spu_child_wait(), spu_memory_remove_breakpoint(), spu_proc_xfer_spu(), startup_inferior(), stop_wait_callback(), store_debug_register(), store_fp_register(), store_fp_regs(), store_inferior_registers(), store_ppc_memory(), store_register(), store_regs(), switch_to_thread(), sync_threadlists(), target_core_of_thread(), target_detach(), target_resume(), target_thread_address_space(), target_thread_alive(), target_wait(), terminal_init_inferior(), thpy_get_ptid(), thread_change_ptid(), thread_db_attach_lwp(), thread_db_detach(), thread_db_find_new_threads_2(), thread_db_get_thread_local_address(), thread_db_load(), thread_db_mourn_inferior(), thread_db_resume(), thread_db_wait(), thread_from_lwp(), thread_to_lwp(), try_thread_db_load(), user_visible_resume_ptid(), vax_register_u_offset(), vaxbsd_fetch_inferior_registers(), vaxbsd_store_inferior_registers(), VEC(), wait_lwp(), windows_close(), windows_get_ada_task_ptid(), windows_pid_to_str(), windows_resume(), and write_ptid().
long ptid_get_tid (ptid_t ptid)
Definition at line 67 of file ptid.c.
References ptid::tid.
Referenced by aix_thread_pid_to_str(), bsd_uthread_extra_thread_info(), bsd_uthread_fetch_registers(), bsd_uthread_find_new_threads(), bsd_uthread_pid_to_str(), bsd_uthread_store_registers(), bsd_uthread_thread_alive(), bsd_uthread_wait(), cancel_breakpoint(), darwin_attach(), darwin_pid_to_str(), darwin_resume(), darwin_wait(), dec_thread_fetch_registers(), dec_thread_pid_to_str(), dec_thread_ptid_is_alive(), dec_thread_store_registers(), dec_thread_thread_alive(), i386_darwin_dr_get(), i386_darwin_dr_set(), i386_darwin_fetch_inferior_registers(), i386_darwin_store_inferior_registers(), info_task(), linux_collect_thread_registers(), ppc_ravenscar_generic_fetch_registers(), ppc_ravenscar_generic_store_registers(), procfs_pid_to_str(), procfs_set_thread(), procfs_thread_alive(), ptid_cmp(), ptid_is_pid(), ptid_tid_p(), ravenscar_pid_to_str(), remote_pid_to_str(), remote_thread_alive(), remote_threads_extra_info(), sol_thread_alive(), sol_thread_fetch_registers(), sol_thread_resume(), sol_thread_store_registers(), sol_thread_wait(), solaris_pid_to_str(), sparc_ravenscar_fetch_registers(), sparc_ravenscar_store_registers(), thpy_get_ptid(), thread_db_find_thread_from_tid(), thread_to_lwp(), windows_add_thread(), windows_delete_thread(), windows_fetch_inferior_registers(), windows_get_tib_address(), windows_pid_to_str(), windows_resume(), windows_store_inferior_registers(), windows_thread_alive(), and write_ptid().
int ptid_is_pid (ptid_t ptid)
Definition at line 85 of file ptid.c.
References ptid_equal(), ptid_get_lwp(), and ptid_get_tid().
Referenced by append_resumption(), clear_inline_frame_state(), finish_thread_state(), infrun_thread_stop_requested_callback(), linux_nat_resume(), linux_nat_wait_1(), mi_on_resume(), ptid_match(), remote_notice_new_inferior(), remote_pid_to_str(), remote_stop_ns(), remote_vcont_resume(), set_executing(), set_running(), and set_stop_requested().
int ptid_lwp_p (ptid_t ptid)
Definition at line 97 of file ptid.c.
References ptid_equal(), and ptid_get_lwp().
Referenced by add_initial_lwp(), find_lwp_pid(), lin_lwp_attach_lwp(), linux_nat_pid_to_str(), linux_nat_wait_1(), linux_nat_xfer_partial(), linux_thread_alive(), and thread_to_lwp().
int ptid_tid_p (ptid_t ptid)
Definition at line 109 of file ptid.c.
References ptid_equal(), and ptid_get_tid().
Referenced by lwp_to_thread(), rw_common(), sol_thread_alive(), sol_thread_fetch_registers(), sol_thread_store_registers(), sol_thread_wait(), sol_thread_xfer_partial(), and solaris_pid_to_str().
Variable Documentation
ptid_t minus_one_ptid
Definition at line 25 of file ptid.c.
Referenced by append_resumption(), clear_inline_frame_state(), darwin_decode_message(), darwin_resume(), darwin_wait(), delete_checkpoint_command(), detach_checkpoint_command(), extended_remote_attach_1(), extended_remote_mourn_1(), fetch_inferior_event(), finish_thread_state(), follow_fork(), gdbsim_cntrl_c(), gdbsim_resume(), gdbsim_stop(), gdbsim_wait(), get_windows_debug_event(), gnu_resume(), gnu_wait(), handle_inferior_event(), infrun_thread_stop_requested_callback(), init_wait_for_inferior(), interrupt_target_1(), linux_nat_resume(), linux_nat_wait(), linux_nat_wait_1(), mi_on_resume(), normal_stop(), nullify_last_target_wait_ptid(), osf_solib_create_inferior_hook(), ppc_linux_spe_context_lookup(), prepare_for_detach(), prepare_to_proceed(), proceed(), procfs_resume(), ptid_match(), record_full_wait_1(), regcache_xmalloc_1(), registers_changed(), remote_resume(), remote_start_remote(), remote_stop_ns(), remote_vcont_resume(), remote_wait_as(), remote_wait_ns(), run_command_1(), set_executing(), set_running(), set_sig_thread_cmd(), set_stop_requested(), set_thread(), spu_skip_standalone_loader(), startup_inferior(), thread_db_find_new_threads(), thread_db_resume(), wait_for_inferior(), and windows_resume().
ptid_t null_ptid
Definition at line 24 of file ptid.c.
Referenced by add_current_inferior_and_thread(), add_inferior_command(), add_thread_silent(), agent_run_command(), bpstat_clear_actions(), bpstat_do_actions(), breakpoint_about_to_proceed(), bsd_kvm_close(), child_terminal_info(), clear_proceed_status(), clone_inferior_command(), core_close(), core_open(), create_fork_vfork_event_catchpoint(), darwin_create_inferior(), darwin_get_ada_task_ptid(), darwin_kill_inferior(), dcache_info(), dcache_init(), dcache_invalidate(), dec_thread_wait(), default_child_has_all_memory(), default_child_has_execution(), default_child_has_memory(), default_child_has_registers(), default_child_has_stack(), delete_step_thread_step_resume_breakpoint(), detach_command(), displaced_step_clear(), displaced_step_fixup(), displaced_step_prepare(), display_tib(), do_restore_current_thread_cleanup(), ensure_valid_thread(), fetch_inferior_event(), finish_command_continuation(), gdb_clear_file(), gdb_target_has_execution_command(), gdbsim_open(), gdbtk_annotate_signal(), generic_mourn_inferior(), get_active_ptid(), get_current_frame(), get_displaced_step_closure_by_addr(), get_task_from_args(), get_thread_arch_regcache(), gnu_detach(), go32_mourn_inferior(), go32_thread_alive(), handle_inferior_event(), handle_vfork_child_exec_or_exit(), has_stack_frames(), inf_ptrace_detach(), inferior_command(), inferior_event_handler(), info_mach_exceptions_command(), info_mach_ports_command(), info_mach_region_command(), init_wait_for_inferior(), insert_breakpoint_locations(), kill_command(), kill_if_already_running(), linux_nat_xfer_partial(), m32r_close(), m32r_kill(), m32r_load(), m32r_upload_command(), make_cleanup_restore_current_thread(), memory_xfer_partial_1(), mi_about_to_proceed(), mi_cmd_execute(), mi_cmd_remove_inferior(), mi_execute_command(), mips_error(), normal_stop(), notice_new_inferior(), prepare_for_detach(), print_one_catch_fork(), print_one_catch_vfork(), print_thread_info(), proceed(), process_stop_reply(), procfs_detach(), procfs_kill_inferior(), procfs_mourn_inferior(), procfs_resume(), procfs_store_registers(), procfs_wait(), program_info(), ravenscar_mourn_inferior(), ravenscar_running_thread(), ravenscar_runtime_initialized(), ravenscar_update_inferior_ptid(), read_atcb(), read_ptid(), registers_changed_ptid(), remote_close(), remote_parse_stop_reply(), remote_pid_to_str(), remote_read_description(), remote_start_remote(), remote_threads_info(), remote_wait_as(), run_one_inferior(), sdireset_command(), set_enable_mach_exceptions(), siginfo_make_value(), stop_reply_extract_thread(), switch_to_program_space_and_thread(), switch_to_thread(), thread_command(), thread_name_command(), tlb_make_value(), tui_make_status_line(), update_inserted_breakpoint_locations(), update_solib_list(), validate_siginfo_access(), watch_command_1(), watchpoint_in_thread_scope(), and windows_detach().