GDB (xrefs): /home/stan/gdb/src/gdb/python/py-breakpoint.c File Reference
/home/stan/gdb/src/gdb/python/py-breakpoint.c File Reference
#include "defs.h"
#include "value.h"
#include "exceptions.h"
#include "python-internal.h"
#include "python.h"
#include "charset.h"
#include "breakpoint.h"
#include "gdbcmd.h"
#include "gdbthread.h"
#include "observer.h"
#include "cli/cli-script.h"
#include "ada-lang.h"
#include "arch-utils.h"
#include "language.h"
Classes
struct pybp_code
Functions
static PyObject * bppy_is_valid (PyObject *self, PyObject *args)
static PyObject * bppy_get_enabled (PyObject *self, void *closure)
static PyObject * bppy_get_silent (PyObject *self, void *closure)
static int bppy_set_enabled (PyObject *self, PyObject *newvalue, void *closure)
static int bppy_set_silent (PyObject *self, PyObject *newvalue, void *closure)
static int bppy_set_thread (PyObject *self, PyObject *newvalue, void *closure)
static int bppy_set_task (PyObject *self, PyObject *newvalue, void *closure)
static PyObject * bppy_delete_breakpoint (PyObject *self, PyObject *args)
static int bppy_set_ignore_count (PyObject *self, PyObject *newvalue, void *closure)
static int bppy_set_hit_count (PyObject *self, PyObject *newvalue, void *closure)
static PyObject * bppy_get_location (PyObject *self, void *closure)
static PyObject * bppy_get_expression (PyObject *self, void *closure)
static PyObject * bppy_get_condition (PyObject *self, void *closure)
static int bppy_set_condition (PyObject *self, PyObject *newvalue, void *closure)
static PyObject * bppy_get_commands (PyObject *self, void *closure)
static PyObject * bppy_get_type (PyObject *self, void *closure)
static PyObject * bppy_get_visibility (PyObject *self, void *closure)
static PyObject * bppy_get_number (PyObject *self, void *closure)
static PyObject * bppy_get_thread (PyObject *self, void *closure)
static PyObject * bppy_get_task (PyObject *self, void *closure)
static PyObject * bppy_get_hit_count (PyObject *self, void *closure)
static PyObject * bppy_get_ignore_count (PyObject *self, void *closure)
static int bppy_init (PyObject *self, PyObject *args, PyObject *kwargs)
static int build_bp_list (struct breakpoint *b, void *arg)
PyObject * gdbpy_breakpoints (PyObject *self, PyObject *args)
int gdbpy_should_stop (struct breakpoint_object *bp_obj)
int gdbpy_breakpoint_has_py_cond (struct breakpoint_object *bp_obj)
static void gdbpy_breakpoint_created (struct breakpoint *bp)
static void gdbpy_breakpoint_deleted (struct breakpoint *b)
int gdbpy_initialize_breakpoints (void)
static int local_setattro (PyObject *self, PyObject *name, PyObject *v)
Variables
static int bppy_live
breakpoint_object * bppy_pending_object
static char *const stop_func = "stop"
static struct pybp_code pybp_codes []
static struct pybp_code pybp_watch_types []
static PyGetSetDef breakpoint_object_getset []
static PyMethodDef breakpoint_object_methods []
PyTypeObject breakpoint_object_type
Function Documentation
static PyObject* bppy_delete_breakpoint (PyObject * self, PyObject * args) [static]
Definition at line 279 of file py-breakpoint.c.
References breakpoint_object::bp, BPPY_REQUIRE_VALID, delete_breakpoint(), GDB_PY_HANDLE_EXCEPTION, RETURN_MASK_ALL, and TRY_CATCH.
static PyObject* bppy_get_commands (PyObject * self, void * closure) [static]
Definition at line 467 of file py-breakpoint.c.
References breakpoint_object::bp, BPPY_REQUIRE_VALID, breakpoint_commands(), breakpoint::commands, current_uiout, do_cleanups(), gdbpy_convert_exception(), host_charset(), make_cleanup(), make_cleanup_ui_file_delete(), mem_fileopen(), print_command_lines(), gdb_exception::reason, RETURN_MASK_ALL, TRY_CATCH, ui_file_xstrdup(), ui_out_redirect(), and xfree().
static PyObject* bppy_get_condition (PyObject * self, void * closure) [static]
Definition at line 411 of file py-breakpoint.c.
References breakpoint_object::bp, BPPY_REQUIRE_VALID, breakpoint::cond_string, and host_charset().
static PyObject* bppy_get_enabled (PyObject * self, void * closure) [static]
Definition at line 88 of file py-breakpoint.c.
References breakpoint_object::bp, bp_enabled, BPPY_REQUIRE_VALID, and breakpoint::enable_state.
static PyObject* bppy_get_expression (PyObject * self, void * closure) [static]
Definition at line 389 of file py-breakpoint.c.
References breakpoint_object::bp, BPPY_REQUIRE_VALID, watchpoint::exp_string, host_charset(), and is_watchpoint().
static PyObject* bppy_get_hit_count (PyObject * self, void * closure) [static]
Definition at line 573 of file py-breakpoint.c.
References breakpoint_object::bp, BPPY_REQUIRE_VALID, and breakpoint::hit_count.
static PyObject* bppy_get_ignore_count (PyObject * self, void * closure) [static]
Definition at line 584 of file py-breakpoint.c.
References breakpoint_object::bp, BPPY_REQUIRE_VALID, and breakpoint::ignore_count.
static PyObject* bppy_get_location (PyObject * self, void * closure) [static]
Definition at line 370 of file py-breakpoint.c.
References breakpoint::addr_string, breakpoint_object::bp, bp_breakpoint, BPPY_REQUIRE_VALID, host_charset(), and breakpoint::type.
static PyObject* bppy_get_number (PyObject * self, void * closure) [static]
Definition at line 534 of file py-breakpoint.c.
References BPPY_REQUIRE_VALID, and breakpoint_object::number.
static PyObject* bppy_get_silent (PyObject * self, void * closure) [static]
Definition at line 102 of file py-breakpoint.c.
References breakpoint_object::bp, BPPY_REQUIRE_VALID, and breakpoint::silent.
static PyObject* bppy_get_task (PyObject * self, void * closure) [static]
Definition at line 559 of file py-breakpoint.c.
References breakpoint_object::bp, BPPY_REQUIRE_VALID, and breakpoint::task.
static PyObject* bppy_get_thread (PyObject * self, void * closure) [static]
Definition at line 545 of file py-breakpoint.c.
References breakpoint_object::bp, BPPY_REQUIRE_VALID, and breakpoint::thread.
static PyObject* bppy_get_type (PyObject * self, void * closure) [static]
Definition at line 508 of file py-breakpoint.c.
References breakpoint_object::bp, BPPY_REQUIRE_VALID, and breakpoint::type.
static PyObject* bppy_get_visibility (PyObject * self, void * closure) [static]
Definition at line 520 of file py-breakpoint.c.
References breakpoint_object::bp, BPPY_REQUIRE_VALID, and breakpoint::number.
static int bppy_init (PyObject * self, PyObject * args, PyObject * kwargs) [static]
Definition at line 595 of file py-breakpoint.c.
References _, AUTO_BOOLEAN_TRUE, awatch_command_wrapper(), bkpt_breakpoint_ops, breakpoint_object::bp, bp_breakpoint, bp_watchpoint, BPPY_SET_REQUIRE_VALID, create_breakpoint(), do_cleanups(), error(), hw_access, hw_read, hw_write, make_cleanup(), gdb_exception::message, breakpoint_object::number, python_gdbarch, gdb_exception::reason, RETURN_MASK_ALL, RETURN_QUIT, rwatch_command_wrapper(), TRY_CATCH, watch_command_wrapper(), and xfree().
static PyObject* bppy_is_valid (PyObject * self, PyObject * args) [static]
Definition at line 77 of file py-breakpoint.c.
References breakpoint_object::bp.
static int bppy_set_condition (PyObject * self, PyObject * newvalue, void * closure) [static]
Definition at line 429 of file py-breakpoint.c.
References _, breakpoint_object::bp, BPPY_SET_REQUIRE_VALID, watchpoint::exp, GDB_PY_SET_HANDLE_EXCEPTION, python_string_to_host_string(), RETURN_MASK_ALL, set_breakpoint_condition(), TRY_CATCH, and xfree().
static int bppy_set_enabled (PyObject * self, PyObject * newvalue, void * closure) [static]
Definition at line 114 of file py-breakpoint.c.
References _, breakpoint_object::bp, BPPY_SET_REQUIRE_VALID, disable_breakpoint(), enable_breakpoint(), GDB_PY_SET_HANDLE_EXCEPTION, RETURN_MASK_ALL, and TRY_CATCH.
static int bppy_set_hit_count (PyObject * self, PyObject * newvalue, void * closure) [static]
Definition at line 336 of file py-breakpoint.c.
References _, breakpoint_object::bp, BPPY_SET_REQUIRE_VALID, gdb_py_int_as_long(), and breakpoint::hit_count.
static int bppy_set_ignore_count (PyObject * self, PyObject * newvalue, void * closure) [static]
Definition at line 298 of file py-breakpoint.c.
References _, BPPY_SET_REQUIRE_VALID, gdb_py_int_as_long(), GDB_PY_SET_HANDLE_EXCEPTION, breakpoint_object::number, RETURN_MASK_ALL, set_ignore_count(), and TRY_CATCH.
static int bppy_set_silent (PyObject * self, PyObject * newvalue, void * closure) [static]
Definition at line 154 of file py-breakpoint.c.
References _, breakpoint_object::bp, BPPY_SET_REQUIRE_VALID, and breakpoint_set_silent().
static int bppy_set_task (PyObject * self, PyObject * newvalue, void * closure) [static]
Definition at line 226 of file py-breakpoint.c.
References _, breakpoint_object::bp, BPPY_SET_REQUIRE_VALID, breakpoint_set_task(), gdb_py_int_as_long(), GDB_PY_SET_HANDLE_EXCEPTION, RETURN_MASK_ALL, TRY_CATCH, and valid_task_id().
static int bppy_set_thread (PyObject * self, PyObject * newvalue, void * closure) [static]
Definition at line 185 of file py-breakpoint.c.
References _, breakpoint_object::bp, BPPY_SET_REQUIRE_VALID, breakpoint_set_thread(), gdb_py_int_as_long(), and valid_thread_id().
static int build_bp_list (struct breakpoint * b, void * arg) [static]
Definition at line 672 of file py-breakpoint.c.
References cleanup::arg, and breakpoint::py_bp_object.
Referenced by gdbpy_breakpoints().
static void gdbpy_breakpoint_created (struct breakpoint * bp) [static]
Definition at line 796 of file py-breakpoint.c.
References _, breakpoint_object::bp, bp_access_watchpoint, bp_breakpoint, bp_hardware_watchpoint, bp_read_watchpoint, bp_watchpoint, bppy_live, bppy_pending_object, breakpoint_object_type, gdbpy_print_stack(), breakpoint_object::is_finish_bp, breakpoint_object::number, breakpoint::number, breakpoint::py_bp_object, PyGILState_Ensure, PyGILState_Release, and breakpoint::type.
Referenced by gdbpy_initialize_breakpoints().
static void gdbpy_breakpoint_deleted (struct breakpoint * b) [static]
Definition at line 842 of file py-breakpoint.c.
References breakpoint_object::bp, bppy_live, get_breakpoint(), breakpoint::number, breakpoint::py_bp_object, Py_DECREF, PyGILState_Ensure, and PyGILState_Release.
Referenced by gdbpy_initialize_breakpoints().
int gdbpy_breakpoint_has_py_cond (struct breakpoint_object * bp_obj)
Definition at line 773 of file py-breakpoint.c.
Referenced by condition_command().
PyObject* gdbpy_breakpoints (PyObject * self, PyObject * args)
Definition at line 694 of file py-breakpoint.c.
References bppy_live, build_bp_list(), iterate_over_breakpoints(), and Py_DECREF.
int gdbpy_initialize_breakpoints (void)
Definition at line 868 of file py-breakpoint.c.
References breakpoint_object_type, code, gdb_module, gdb_pymodule_addobject(), gdbpy_breakpoint_created(), gdbpy_breakpoint_deleted(), pybp_code::name, name, observer_attach_breakpoint_created(), and observer_attach_breakpoint_deleted().
Referenced by _initialize_python().
int gdbpy_should_stop (struct breakpoint_object * bp_obj)
Definition at line 726 of file py-breakpoint.c.
Referenced by bpstat_check_breakpoint_conditions().
static int local_setattro (PyObject * self, PyObject * name, PyObject * v) [static]
Definition at line 913 of file py-breakpoint.c.
References _, breakpoint_object::bp, breakpoint::cond_string, python_string_to_host_string(), stop_func, and xfree().
Variable Documentation
int bppy_live [static]
Definition at line 36 of file py-breakpoint.c.
Referenced by gdbpy_breakpoint_created(), gdbpy_breakpoint_deleted(), and gdbpy_breakpoints().
breakpoint_object* bppy_pending_object
Definition at line 40 of file py-breakpoint.c.
Referenced by bpfinishpy_init(), and gdbpy_breakpoint_created().
PyGetSetDef breakpoint_object_getset[] [static]
Definition at line 939 of file py-breakpoint.c.
PyMethodDef breakpoint_object_methods[] [static]
Initial value:
{
  { "is_valid", bppy_is_valid, METH_NOARGS,
    "Return true if this breakpoint is valid, false if not." },
  { "delete", bppy_delete_breakpoint, METH_NOARGS,
    "Delete the underlying GDB breakpoint." },
  { NULL }
}
Definition at line 979 of file py-breakpoint.c.
PyTypeObject breakpoint_object_type
Definition at line 988 of file py-breakpoint.c.
Referenced by gdbpy_breakpoint_created(), and gdbpy_initialize_breakpoints().
struct pybp_code pybp_codes[] [static]
Initial value:
{
  { "BP_NONE", bp_none},
  { "BP_BREAKPOINT", bp_breakpoint},
  { "BP_WATCHPOINT", bp_watchpoint},
  { "BP_HARDWARE_WATCHPOINT", bp_hardware_watchpoint},
  { "BP_READ_WATCHPOINT", bp_read_watchpoint},
  { "BP_ACCESS_WATCHPOINT", bp_access_watchpoint},
  {NULL}
}
Definition at line 55 of file py-breakpoint.c.
struct pybp_code pybp_watch_types[] [static]
Initial value:
{
  { "WP_READ", hw_read},
  { "WP_WRITE", hw_write},
  { "WP_ACCESS", hw_access},
  {NULL}
}
Definition at line 67 of file py-breakpoint.c.
char* const stop_func = "stop" [static]
Definition at line 43 of file py-breakpoint.c.
Referenced by gdbpy_breakpoint_has_py_cond(), gdbpy_should_stop(), and local_setattro().