GDB (xrefs): /home/stan/gdb/src/gdb/python/py-bpevent.c File Reference
/home/stan/gdb/src/gdb/python/py-bpevent.c File Reference
#include "defs.h"
#include "py-stopevent.h"
Functions
static PyTypeObject
breakpoint_event_object_type CPYCHECKER_TYPE_OBJECT_FOR_TYPEDEF ("event_object")
PyObject * create_breakpoint_event_object (PyObject *breakpoint_list, PyObject *first_bp)
GDBPY_NEW_EVENT_TYPE (breakpoint,"gdb.BreakpointEvent","BreakpointEvent","GDB breakpoint stop event object", stop_event_object_type, static)
Function Documentation
static PyTypeObject breakpoint_event_object_type CPYCHECKER_TYPE_OBJECT_FOR_TYPEDEF ("event_object") [static]
PyObject* create_breakpoint_event_object (PyObject * breakpoint_list, PyObject * first_bp)
Definition at line 30 of file py-bpevent.c.
References create_stop_event_object(), and evpy_add_attribute().
Referenced by emit_stop_event().
GDBPY_NEW_EVENT_TYPE (breakpoint , "gdb.BreakpointEvent" , "BreakpointEvent" , "GDB breakpoint stop event object" , stop_event_object_type , static)