GDB (xrefs): /home/stan/gdb/src/gdb/python/py-cmd.c File Reference
/home/stan/gdb/src/gdb/python/py-cmd.c File Reference
#include "defs.h"
#include "arch-utils.h"
#include "value.h"
#include "exceptions.h"
#include "python-internal.h"
#include "charset.h"
#include "gdbcmd.h"
#include "cli/cli-decode.h"
#include "completer.h"
#include "language.h"
Classes
struct cmdpy_completer
struct cmdpy_object
Defines
#define N_COMPLETERS (sizeof (completers) / sizeof (completers[0]))
Typedefs
typedef struct cmdpy_object cmdpy_object
Functions
static PyTypeObject
cmdpy_object_type CPYCHECKER_TYPE_OBJECT_FOR_TYPEDEF ("cmdpy_object")
static PyObject * cmdpy_dont_repeat (PyObject *self, PyObject *args)
static void cmdpy_destroyer (struct cmd_list_element *self, void *context)
static void cmdpy_function (struct cmd_list_element *command, char *args, int from_tty)
static VEC (char_ptr)
char * gdbpy_parse_command_name (const char *name, struct cmd_list_element ***base_list, struct cmd_list_element **start_list)
static int cmdpy_init (PyObject *self, PyObject *args, PyObject *kw)
int gdbpy_initialize_commands (void)
PyObject * gdbpy_string_to_argv (PyObject *self, PyObject *args)
Variables
static struct cmdpy_completer completers []
static PyObject * invoke_cst
static PyObject * complete_cst
static PyMethodDef cmdpy_object_methods []
static PyTypeObject cmdpy_object_type
Define Documentation
#define N_COMPLETERS (sizeof (completers) / sizeof (completers[0]))
Definition at line 50 of file py-cmd.c.
Referenced by cmdpy_init(), gdbpy_initialize_commands(), and VEC().
Typedef Documentation
typedef struct cmdpy_object cmdpy_object
Definition at line 69 of file py-cmd.c.
Function Documentation
static void cmdpy_destroyer (struct cmd_list_element * self, void * context) [static]
Definition at line 93 of file py-cmd.c.
References cmdpy_object::command, current_language, do_cleanups(), ensure_python_env(), get_current_arch(), Py_DECREF, and xfree().
Referenced by cmdpy_init().
static PyObject* cmdpy_dont_repeat (PyObject * self, PyObject * args) [static]
Definition at line 82 of file py-cmd.c.
References dont_repeat().
static void cmdpy_function (struct cmd_list_element * command, char * args, int from_tty) [static]
Definition at line 117 of file py-cmd.c.
References _, current_language, do_cleanups(), ensure_python_env(), error(), gdbpy_exception_to_string(), gdbpy_gdberror_exc, gdbpy_print_stack(), get_cmd_context(), get_current_arch(), host_charset(), invoke_cst, make_cleanup(), printf_filtered(), Py_DECREF, and xfree().
Referenced by cmdpy_init().
static int cmdpy_init (PyObject * self, PyObject * args, PyObject * kw) [static]
Definition at line 414 of file py-cmd.c.
References _, add_cmd(), add_prefix_cmd(), cmd_list_element::allow_unknown, class_breakpoint, class_files, class_info, class_maintenance, class_obscure, class_run, class_stack, class_support, class_trace, class_user, class_vars, cmdlist, cmdpy_destroyer(), cmdpy_function(), cmdpy_object::command, cmd_list_element::completer, cmd_list_element::destroyer, cmd_list_element::func, gdbpy_doc_cst, gdbpy_is_string(), gdbpy_parse_command_name(), invoke_cst, gdb_exception::message, N_COMPLETERS, name, no_class, Py_DECREF, python_string_to_host_string(), gdb_exception::reason, RETURN_MASK_ALL, RETURN_QUIT, set_cmd_context(), cmdpy_object::sub_list, TRY_CATCH, xfree(), and xmalloc().
static PyTypeObject cmdpy_object_type CPYCHECKER_TYPE_OBJECT_FOR_TYPEDEF ("cmdpy_object") [static]
int gdbpy_initialize_commands (void)
Definition at line 568 of file py-cmd.c.
References class_breakpoint, class_files, class_info, class_maintenance, class_obscure, class_run, class_stack, class_support, class_trace, class_user, class_vars, cmdpy_object_type, complete_cst, gdb_module, gdb_pymodule_addobject(), invoke_cst, N_COMPLETERS, name, and no_class.
Referenced by _initialize_python().
char* gdbpy_parse_command_name (const char * name, struct cmd_list_element *** base_list, struct cmd_list_element ** start_list)
Definition at line 324 of file py-cmd.c.
References _, len, lookup_cmd_1(), memcpy(), cmd_list_element::prefixlist, xfree(), and xmalloc().
Referenced by cmdpy_init(), and parmpy_init().
PyObject* gdbpy_string_to_argv (PyObject * self, PyObject * args)
Definition at line 678 of file py-cmd.c.
References gdb_buildargv(), and Py_DECREF.
static VEC (char_ptr) [static]
Definition at line 210 of file py-cmd.c.
References _, complete_cst, cmdpy_completer::completer, current_language, do_cleanups(), ensure_python_env(), error(), gdb_py_int_as_long(), gdbpy_is_string(), get_cmd_context(), get_current_arch(), host_charset(), N_COMPLETERS, Py_DECREF, python_string_to_host_string(), VEC, and VEC_safe_push.
Variable Documentation
PyMethodDef cmdpy_object_methods[] [static]
Initial value:
{
  { "dont_repeat", cmdpy_dont_repeat, METH_NOARGS,
    "Prevent command repetition when user enters empty line." },
  { 0 }
}
Definition at line 619 of file py-cmd.c.
PyTypeObject cmdpy_object_type [static]
Definition at line 627 of file py-cmd.c.
Referenced by gdbpy_initialize_commands().
PyObject* complete_cst [static]
Definition at line 76 of file py-cmd.c.
Referenced by gdbpy_initialize_commands(), and VEC().
struct cmdpy_completer completers[] [static]
Initial value:
{
  { "COMPLETE_NONE", noop_completer },
  { "COMPLETE_FILENAME", filename_completer },
  { "COMPLETE_LOCATION", location_completer },
  { "COMPLETE_COMMAND", command_completer },
  { "COMPLETE_SYMBOL", make_symbol_completion_list_fn },
}
Definition at line 41 of file py-cmd.c.
PyObject* invoke_cst [static]
Definition at line 75 of file py-cmd.c.
Referenced by cmdpy_function(), cmdpy_init(), and gdbpy_initialize_commands().