GDB (xrefs): /home/stan/gdb/src/gdb/python/py-evts.c File Reference
/home/stan/gdb/src/gdb/python/py-evts.c File Reference
#include "defs.h"
#include "py-events.h"
Functions
static int
CPYCHECKER_NEGATIVE_RESULT_SETS_EXCEPTION add_new_registry (eventregistry_object **registryp, char *name)
int gdbpy_initialize_py_events (void)
Function Documentation
static int CPYCHECKER_NEGATIVE_RESULT_SETS_EXCEPTION add_new_registry (eventregistry_object ** registryp, char * name) [static]
Definition at line 41 of file py-evts.c.
References create_eventregistry_object(), gdb_py_events, gdb_pymodule_addobject(), and events_object::module.
Referenced by gdbpy_initialize_py_events().
int gdbpy_initialize_py_events (void)
Definition at line 56 of file py-evts.c.
References add_new_registry(), events_object::cont, events_object::exited, gdb_module, gdb_py_events, gdb_pymodule_addobject(), events_object::module, events_object::new_objfile, and events_object::stop.
Referenced by _initialize_python().