GDB (xrefs): /home/stan/gdb/src/gdb/python/py-evtregistry.c File Reference
/home/stan/gdb/src/gdb/python/py-evtregistry.c File Reference
#include "defs.h"
#include "command.h"
#include "py-events.h"
Functions
static PyTypeObject
eventregistry_object_type CPYCHECKER_TYPE_OBJECT_FOR_TYPEDEF ("eventregistry_object")
static PyObject * evregpy_connect (PyObject *self, PyObject *function)
static PyObject * evregpy_disconnect (PyObject *self, PyObject *function)
eventregistry_object * create_eventregistry_object (void)
static void evregpy_dealloc (PyObject *self)
int gdbpy_initialize_eventregistry (void)
int evregpy_no_listeners_p (eventregistry_object *registry)
Variables
events_object gdb_py_events
static PyMethodDef eventregistry_object_methods []
static PyTypeObject eventregistry_object_type
Function Documentation
static PyTypeObject eventregistry_object_type CPYCHECKER_TYPE_OBJECT_FOR_TYPEDEF ("eventregistry_object") [static]
eventregistry_object* create_eventregistry_object (void)
Definition at line 80 of file py-evtregistry.c.
References eventregistry_object::callbacks, eventregistry_object_type, and Py_DECREF.
Referenced by add_new_registry().
static PyObject* evregpy_connect (PyObject * self, PyObject * function) [static]
Definition at line 33 of file py-evtregistry.c.
References func.
static void evregpy_dealloc (PyObject * self) [static]
Definition at line 101 of file py-evtregistry.c.
static PyObject* evregpy_disconnect (PyObject * self, PyObject * function) [static]
Definition at line 57 of file py-evtregistry.c.
References func.
int evregpy_no_listeners_p (eventregistry_object * registry)
Definition at line 123 of file py-evtregistry.c.
References eventregistry_object::callbacks.
Referenced by emit_continue_event(), emit_exited_event(), emit_new_objfile_event(), and emit_stop_event().
int gdbpy_initialize_eventregistry (void)
Definition at line 110 of file py-evtregistry.c.
References eventregistry_object_type, gdb_module, and gdb_pymodule_addobject().
Referenced by _initialize_python().
Variable Documentation
PyMethodDef eventregistry_object_methods[] [static]
Initial value:
{
  { "connect", evregpy_connect, METH_VARARGS, "Add function" },
  { "disconnect", evregpy_disconnect, METH_VARARGS, "Remove function" },
  { NULL }
}
Definition at line 128 of file py-evtregistry.c.
PyTypeObject eventregistry_object_type [static]
Definition at line 135 of file py-evtregistry.c.
Referenced by create_eventregistry_object(), and gdbpy_initialize_eventregistry().
events_object gdb_py_events
Definition at line 24 of file py-evtregistry.c.
Referenced by add_new_registry(), emit_continue_event(), emit_exited_event(), emit_new_objfile_event(), emit_stop_event(), and gdbpy_initialize_py_events().