GDB (xrefs): /home/stan/gdb/src/gdb/python/py-event.h File Reference
/home/stan/gdb/src/gdb/python/py-event.h File Reference
#include "py-events.h"
#include "command.h"
#include "python-internal.h"
#include "inferior.h"
Classes
struct event_object
Defines
#define GDBPY_NEW_EVENT_TYPE(name, py_path, py_name, doc, base, qual)
Functions
int emit_continue_event (ptid_t ptid)
int emit_exited_event (const LONGEST *exit_code, struct inferior *inf)
int evpy_emit_event (PyObject *event, eventregistry_object *registry) CPYCHECKER_STEALS_REFERENCE_TO_ARG(1)
PyObject * create_event_object (PyTypeObject *py_type)
PyObject * create_thread_event_object (PyTypeObject *py_type)
int emit_new_objfile_event (struct objfile *objfile)
void evpy_dealloc (PyObject *self)
int evpy_add_attribute (PyObject *event, char *name, PyObject *attr) CPYCHECKER_NEGATIVE_RESULT_SETS_EXCEPTION
int gdbpy_initialize_event_generic (PyTypeObject *type, char *name) CPYCHECKER_NEGATIVE_RESULT_SETS_EXCEPTION
Define Documentation
#define GDBPY_NEW_EVENT_TYPE (name, py_path, py_name, doc, base, qual)
Definition at line 47 of file py-event.h.
Function Documentation
PyObject* create_event_object (PyTypeObject * py_type)
Definition at line 31 of file py-event.c.
References event_object::dict.
Referenced by create_exited_event_object(), create_new_objfile_event_object(), and create_thread_event_object().
PyObject* create_thread_event_object (PyTypeObject * py_type)
Definition at line 50 of file py-threadevent.c.
References create_event_object(), evpy_add_attribute(), and get_event_thread().
Referenced by create_continue_event_object(), and create_stop_event_object().
int emit_continue_event (ptid_t ptid)
Definition at line 37 of file py-continueevent.c.
References events_object::cont, create_continue_event_object(), evpy_emit_event(), evregpy_no_listeners_p(), and gdb_py_events.
Referenced by python_on_resume().
int emit_exited_event (const LONGEST * exit_code, struct inferior * inf)
Definition at line 71 of file py-exitedevent.c.
References create_exited_event_object(), evpy_emit_event(), evregpy_no_listeners_p(), events_object::exited, and gdb_py_events.
Referenced by python_inferior_exit().
int emit_new_objfile_event (struct objfile * objfile)
Definition at line 56 of file py-newobjfileevent.c.
References create_new_objfile_event_object(), evpy_emit_event(), evregpy_no_listeners_p(), gdb_py_events, and events_object::new_objfile.
Referenced by python_new_objfile().
int evpy_add_attribute (PyObject * event, char * name, PyObject * attr)
Definition at line 56 of file py-event.c.
Referenced by create_breakpoint_event_object(), create_exited_event_object(), create_new_objfile_event_object(), create_signal_event_object(), and create_thread_event_object().
void evpy_dealloc (PyObject * self)
Definition at line 24 of file py-event.c.
int evpy_emit_event (PyObject * event, eventregistry_object * registry)
Definition at line 89 of file py-event.c.
References eventregistry_object::callbacks, func, gdbpy_print_stack(), and Py_DECREF.
Referenced by emit_continue_event(), emit_exited_event(), emit_new_objfile_event(), and emit_stop_event().
int gdbpy_initialize_event_generic (PyTypeObject * type, char * name)
Definition at line 75 of file py-event.c.
References gdb_module, and gdb_pymodule_addobject().
Referenced by gdbpy_initialize_event().