GDB (xrefs): /home/stan/gdb/src/gdb/python/py-event.c File Reference
/home/stan/gdb/src/gdb/python/py-event.c File Reference
#include "defs.h"
#include "py-event.h"
Functions
void evpy_dealloc (PyObject *self)
PyObject * create_event_object (PyTypeObject *py_type)
int evpy_add_attribute (PyObject *event, char *name, PyObject *attr)
int gdbpy_initialize_event (void)
int gdbpy_initialize_event_generic (PyTypeObject *type, char *name)
int evpy_emit_event (PyObject *event, eventregistry_object *registry)
Variables
static PyGetSetDef event_object_getset []
PyTypeObject event_object_type
Function Documentation
PyObject* create_event_object (PyTypeObject * py_type)
Definition at line 31 of file py-event.c.
References event_object::dict.
Referenced by create_exited_event_object(), create_new_objfile_event_object(), and create_thread_event_object().
int evpy_add_attribute (PyObject * event, char * name, PyObject * attr)
Definition at line 56 of file py-event.c.
Referenced by create_breakpoint_event_object(), create_exited_event_object(), create_new_objfile_event_object(), create_signal_event_object(), and create_thread_event_object().
void evpy_dealloc (PyObject * self)
Definition at line 24 of file py-event.c.
int evpy_emit_event (PyObject * event, eventregistry_object * registry)
Definition at line 89 of file py-event.c.
References eventregistry_object::callbacks, func, gdbpy_print_stack(), and Py_DECREF.
Referenced by emit_continue_event(), emit_exited_event(), emit_new_objfile_event(), and emit_stop_event().
int gdbpy_initialize_event (void)
Definition at line 64 of file py-event.c.
References event_object_type, and gdbpy_initialize_event_generic().
Referenced by _initialize_python().
int gdbpy_initialize_event_generic (PyTypeObject * type, char * name)
Definition at line 75 of file py-event.c.
References gdb_module, and gdb_pymodule_addobject().
Referenced by gdbpy_initialize_event().
Variable Documentation
PyGetSetDef event_object_getset[] [static]
Initial value:
{
  { "__dict__", gdb_py_generic_dict, NULL,
    "The __dict__ for this event.", &event_object_type },
  { NULL }
}
Definition at line 136 of file py-event.c.
PyTypeObject event_object_type
Definition at line 143 of file py-event.c.
Referenced by gdbpy_initialize_event().