GDB (xrefs): /home/stan/gdb/src/gdb/python/py-frame.c File Reference
/home/stan/gdb/src/gdb/python/py-frame.c File Reference
#include "defs.h"
#include "charset.h"
#include "block.h"
#include "frame.h"
#include "exceptions.h"
#include "symtab.h"
#include "stack.h"
#include "value.h"
#include "python-internal.h"
#include "symfile.h"
#include "objfiles.h"
#include "unwind_stop_reasons.def"
Classes
struct frame_object
Defines
#define FRAPY_REQUIRE_VALID(frame_obj, frame)
#define SET(name, description)
#define FIRST_ERROR(name)
Functions
struct frame_info * frame_object_to_frame_info (PyObject *obj)
static PyObject * frapy_str (PyObject *self)
static PyObject * frapy_is_valid (PyObject *self, PyObject *args)
static PyObject * frapy_name (PyObject *self, PyObject *args)
static PyObject * frapy_type (PyObject *self, PyObject *args)
static PyObject * frapy_arch (PyObject *self, PyObject *args)
static PyObject * frapy_unwind_stop_reason (PyObject *self, PyObject *args)
static PyObject * frapy_pc (PyObject *self, PyObject *args)
static PyObject * frapy_block (PyObject *self, PyObject *args)
static PyObject * frapy_function (PyObject *self, PyObject *args)
PyObject * frame_info_to_frame_object (struct frame_info *frame)
static PyObject * frapy_older (PyObject *self, PyObject *args)
static PyObject * frapy_newer (PyObject *self, PyObject *args)
static PyObject * frapy_find_sal (PyObject *self, PyObject *args)
static PyObject * frapy_read_var (PyObject *self, PyObject *args)
static PyObject * frapy_select (PyObject *self, PyObject *args)
PyObject * gdbpy_newest_frame (PyObject *self, PyObject *args)
PyObject * gdbpy_selected_frame (PyObject *self, PyObject *args)
PyObject * gdbpy_frame_stop_reason_string (PyObject *self, PyObject *args)
static PyObject * frapy_richcompare (PyObject *self, PyObject *other, int op)
int gdbpy_initialize_frames (void)
Variables
static PyMethodDef frame_object_methods []
PyTypeObject frame_object_type
Define Documentation
#define FIRST_ERROR (name)
Value:
if (PyModule_AddIntConstant (gdb_module, "FRAME_"#name, name) < 0) \
    return -1;
#define FRAPY_REQUIRE_VALID (frame_obj, frame)
Value:
do {                                            \
      frame = frame_object_to_frame_info (frame_obj);   \
      if (frame == NULL)                                \
        error (_("Frame is invalid."));                 \
    } while (0)
Definition at line 50 of file py-frame.c.
Referenced by frapy_arch(), frapy_block(), frapy_find_sal(), frapy_function(), frapy_name(), frapy_newer(), frapy_older(), frapy_pc(), frapy_read_var(), frapy_select(), frapy_type(), and frapy_unwind_stop_reason().
#define SET (name, description)
Value:
if (PyModule_AddIntConstant (gdb_module, "FRAME_"#name, name) < 0) \
    return -1;
Function Documentation
PyObject* frame_info_to_frame_object (struct frame_info * frame)
Definition at line 307 of file py-frame.c.
References frame_object_type, gdbpy_convert_exception(), get_frame_arch(), get_frame_id(), get_frame_unwind_stop_reason(), get_next_frame(), get_prev_frame(), Py_DECREF, gdb_exception::reason, RETURN_MASK_ALL, and TRY_CATCH.
Referenced by bootstrap_python_frame_filters(), frapy_newer(), frapy_older(), gdbpy_newest_frame(), and gdbpy_selected_frame().
struct frame_info* frame_object_to_frame_info (PyObject * obj) [read]
Definition at line 62 of file py-frame.c.
References frame_find_by_id(), frame_object::frame_id, frame_object::frame_id_is_next, and get_prev_frame().
Referenced by bpfinishpy_init(), frapy_is_valid(), py_print_frame(), and sympy_value().
static PyObject* frapy_arch (PyObject * self, PyObject * args) [static]
Definition at line 181 of file py-frame.c.
References FRAPY_REQUIRE_VALID, GDB_PY_HANDLE_EXCEPTION, frame_object::gdbarch, gdbarch_to_arch_object(), RETURN_MASK_ALL, and TRY_CATCH.
static PyObject* frapy_block (PyObject * self, PyObject * args) [static]
Definition at line 242 of file py-frame.c.
References _, BLOCK_FUNCTION, BLOCK_SUPERBLOCK, block_to_block_object(), FRAPY_REQUIRE_VALID, GDB_PY_HANDLE_EXCEPTION, get_frame_block(), symtab::objfile, RETURN_MASK_ALL, SYMBOL_SYMTAB, and TRY_CATCH.
static PyObject* frapy_find_sal (PyObject * self, PyObject * args) [static]
Definition at line 409 of file py-frame.c.
References find_frame_sal(), FRAPY_REQUIRE_VALID, GDB_PY_HANDLE_EXCEPTION, RETURN_MASK_ALL, symtab_and_line_to_sal_object(), and TRY_CATCH.
static PyObject* frapy_function (PyObject * self, PyObject * args) [static]
Definition at line 283 of file py-frame.c.
References find_pc_function(), FRAPY_REQUIRE_VALID, GDB_PY_HANDLE_EXCEPTION, get_frame_address_in_block(), RETURN_MASK_ALL, symbol_to_symbol_object(), and TRY_CATCH.
static PyObject* frapy_is_valid (PyObject * self, PyObject * args) [static]
Definition at line 101 of file py-frame.c.
References frame_object_to_frame_info(), GDB_PY_HANDLE_EXCEPTION, RETURN_MASK_ALL, and TRY_CATCH.
static PyObject* frapy_name (PyObject * self, PyObject * args) [static]
Definition at line 122 of file py-frame.c.
References find_frame_funname(), FRAPY_REQUIRE_VALID, GDB_PY_HANDLE_EXCEPTION, host_charset(), name, gdb_exception::reason, RETURN_MASK_ALL, TRY_CATCH, and xfree().
static PyObject* frapy_newer (PyObject * self, PyObject * args) [static]
Definition at line 380 of file py-frame.c.
References frame_info_to_frame_object(), FRAPY_REQUIRE_VALID, GDB_PY_HANDLE_EXCEPTION, get_next_frame(), frame_info::next, RETURN_MASK_ALL, and TRY_CATCH.
static PyObject* frapy_older (PyObject * self, PyObject * args) [static]
Definition at line 350 of file py-frame.c.
References frame_info_to_frame_object(), FRAPY_REQUIRE_VALID, GDB_PY_HANDLE_EXCEPTION, get_prev_frame(), frame_info::prev, RETURN_MASK_ALL, and TRY_CATCH.
static PyObject* frapy_pc (PyObject * self, PyObject * args) [static]
Definition at line 221 of file py-frame.c.
References FRAPY_REQUIRE_VALID, GDB_PY_HANDLE_EXCEPTION, gdb_py_long_from_ulongest, get_frame_pc(), RETURN_MASK_ALL, and TRY_CATCH.
static PyObject* frapy_read_var (PyObject * self, PyObject * args) [static]
Definition at line 436 of file py-frame.c.
References _, block_object_to_block(), do_cleanups(), FRAPY_REQUIRE_VALID, GDB_PY_HANDLE_EXCEPTION, gdbpy_convert_exception(), gdbpy_is_string(), get_frame_block(), lookup_symbol(), make_cleanup(), python_string_to_target_string(), read_var_value(), gdb_exception::reason, RETURN_MASK_ALL, symbol_object_to_symbol(), symbol_object_type, TRY_CATCH, value_to_value_object(), VAR_DOMAIN, and xfree().
static PyObject* frapy_richcompare (PyObject * self, PyObject * other, int op) [static]
Definition at line 600 of file py-frame.c.
References frame_id_eq(), and frame_object_type.
static PyObject* frapy_select (PyObject * self, PyObject * args) [static]
Definition at line 520 of file py-frame.c.
References FRAPY_REQUIRE_VALID, GDB_PY_HANDLE_EXCEPTION, RETURN_MASK_ALL, select_frame(), and TRY_CATCH.
static PyObject* frapy_str (PyObject * self) [static]
Definition at line 81 of file py-frame.c.
References fprint_frame_id(), mem_fileopen(), ui_file_xstrdup(), and xfree().
static PyObject* frapy_type (PyObject * self, PyObject * args) [static]
Definition at line 160 of file py-frame.c.
References FRAPY_REQUIRE_VALID, GDB_PY_HANDLE_EXCEPTION, get_frame_type(), NORMAL_FRAME, RETURN_MASK_ALL, and TRY_CATCH.
static PyObject* frapy_unwind_stop_reason (PyObject * self, PyObject * args) [static]
Definition at line 200 of file py-frame.c.
References FRAPY_REQUIRE_VALID, GDB_PY_HANDLE_EXCEPTION, get_frame_unwind_stop_reason(), RETURN_MASK_ALL, and TRY_CATCH.
PyObject* gdbpy_frame_stop_reason_string (PyObject * self, PyObject * args)
Definition at line 576 of file py-frame.c.
References _, frame_stop_reason_string(), host_charset(), and gdb_exception::reason.
int gdbpy_initialize_frames (void)
Definition at line 625 of file py-frame.c.
References ARCH_FRAME, DUMMY_FRAME, frame_object_type, gdb_module, gdb_pymodule_addobject(), INLINE_FRAME, NORMAL_FRAME, SENTINEL_FRAME, SIGTRAMP_FRAME, and TAILCALL_FRAME.
Referenced by _initialize_python().
PyObject* gdbpy_newest_frame (PyObject * self, PyObject * args)
Definition at line 540 of file py-frame.c.
References frame_info_to_frame_object(), GDB_PY_HANDLE_EXCEPTION, get_current_frame(), RETURN_MASK_ALL, and TRY_CATCH.
PyObject* gdbpy_selected_frame (PyObject * self, PyObject * args)
Definition at line 558 of file py-frame.c.
References frame_info_to_frame_object(), GDB_PY_HANDLE_EXCEPTION, get_selected_frame(), RETURN_MASK_ALL, and TRY_CATCH.
Variable Documentation
PyMethodDef frame_object_methods[] [static]
Definition at line 662 of file py-frame.c.
PyTypeObject frame_object_type
Definition at line 704 of file py-frame.c.
Referenced by frame_info_to_frame_object(), frapy_richcompare(), gdbpy_initialize_frames(), and sympy_value().