GDB (xrefs): /home/stan/gdb/src/gdb/python/py-function.c File Reference
/home/stan/gdb/src/gdb/python/py-function.c File Reference
#include "defs.h"
#include "value.h"
#include "exceptions.h"
#include "python-internal.h"
#include "charset.h"
#include "gdbcmd.h"
#include "cli/cli-decode.h"
#include "completer.h"
#include "expression.h"
#include "language.h"
Functions
static PyTypeObject
fnpy_object_type CPYCHECKER_TYPE_OBJECT_FOR_TYPEDEF ("PyObject")
static PyObject * convert_values_to_python (int argc, struct value **argv)
static struct value * fnpy_call (struct gdbarch *gdbarch, const struct language_defn *language, void *cookie, int argc, struct value **argv)
static int fnpy_init (PyObject *self, PyObject *args, PyObject *kwds)
int gdbpy_initialize_functions (void)
Variables
static PyTypeObject fnpy_object_type
Function Documentation
static PyObject* convert_values_to_python (int argc, struct value ** argv) [static]
Definition at line 38 of file py-function.c.
References Py_DECREF, and value_to_value_object().
Referenced by fnpy_call().
static PyTypeObject fnpy_object_type CPYCHECKER_TYPE_OBJECT_FOR_TYPEDEF ("PyObject") [static]
static struct value* fnpy_call (struct gdbarch * gdbarch, const struct language_defn * language, void * cookie, int argc, struct value ** argv) [static, read]
Definition at line 62 of file py-function.c.
References _, convert_value_from_python(), convert_values_to_python(), do_cleanups(), ensure_python_env(), error(), gdbpy_exception_to_string(), gdbpy_gdberror_exc, gdbpy_print_stack(), make_cleanup(), printf_filtered(), Py_DECREF, and xfree().
Referenced by fnpy_init().
static int fnpy_init (PyObject * self, PyObject * args, PyObject * kwds) [static]
Definition at line 166 of file py-function.c.
References _, add_internal_function(), fnpy_call(), gdbpy_is_string(), name, Py_DECREF, and python_string_to_host_string().
int gdbpy_initialize_functions (void)
Definition at line 204 of file py-function.c.
References fnpy_object_type, gdb_module, and gdb_pymodule_addobject().
Referenced by _initialize_python().
Variable Documentation
PyTypeObject fnpy_object_type [static]
Definition at line 216 of file py-function.c.
Referenced by gdbpy_initialize_functions().