GDB (xrefs): /home/stan/gdb/src/gdb/python/py-gdb-readline.c File Reference
/home/stan/gdb/src/gdb/python/py-gdb-readline.c File Reference
#include "defs.h"
#include "python-internal.h"
#include "exceptions.h"
#include "top.h"
#include "cli/cli-utils.h"
#include "gdb_string.h"
#include <stddef.h>
Functions
static char * gdbpy_readline_wrapper (FILE *sys_stdin, FILE *sys_stdout, char *prompt)
void gdbpy_initialize_gdb_readline (void)
Function Documentation
void gdbpy_initialize_gdb_readline (void)
Definition at line 88 of file py-gdb-readline.c.
References gdbpy_readline_wrapper().
Referenced by _initialize_python().
static char* gdbpy_readline_wrapper (FILE * sys_stdin, FILE * sys_stdout, char * prompt) [static]
Definition at line 36 of file py-gdb-readline.c.
References command_line_input(), gdbpy_convert_exception(), p, gdb_exception::reason, RETURN_MASK_ALL, RETURN_QUIT, and TRY_CATCH.
Referenced by gdbpy_initialize_gdb_readline().