GDB (xrefs): /home/stan/gdb/src/gdb/python/py-newobjfileevent.c File Reference
/home/stan/gdb/src/gdb/python/py-newobjfileevent.c File Reference
#include "defs.h"
#include "py-event.h"
Functions
static PyTypeObject
new_objfile_event_object_type CPYCHECKER_TYPE_OBJECT_FOR_TYPEDEF ("event_object")
static PyObject * create_new_objfile_event_object (struct objfile *objfile)
int emit_new_objfile_event (struct objfile *objfile)
GDBPY_NEW_EVENT_TYPE (new_objfile,"gdb.NewObjFileEvent","NewObjFileEvent","GDB new object file event object", event_object_type, static)
Function Documentation
static PyTypeObject new_objfile_event_object_type CPYCHECKER_TYPE_OBJECT_FOR_TYPEDEF ("event_object") [static]
static PyObject* create_new_objfile_event_object (struct objfile * objfile) [static]
Definition at line 27 of file py-newobjfileevent.c.
References create_event_object(), evpy_add_attribute(), and objfile_to_objfile_object().
Referenced by emit_new_objfile_event().
int emit_new_objfile_event (struct objfile * objfile)
Definition at line 56 of file py-newobjfileevent.c.
References create_new_objfile_event_object(), evpy_emit_event(), evregpy_no_listeners_p(), gdb_py_events, and events_object::new_objfile.
Referenced by python_new_objfile().
GDBPY_NEW_EVENT_TYPE (new_objfile , "gdb.NewObjFileEvent" , "NewObjFileEvent" , "GDB new object file event object" , event_object_type , static)