GDB (xrefs): /home/stan/gdb/src/gdb/python/py-objfile.c File Reference
/home/stan/gdb/src/gdb/python/py-objfile.c File Reference
#include "defs.h"
#include "python-internal.h"
#include "charset.h"
#include "objfiles.h"
#include "language.h"
Classes
struct objfile_object
Functions
static PyTypeObject
objfile_object_type CPYCHECKER_TYPE_OBJECT_FOR_TYPEDEF ("objfile_object")
static PyObject * objfpy_get_filename (PyObject *self, void *closure)
static void objfpy_dealloc (PyObject *o)
static PyObject * objfpy_new (PyTypeObject *type, PyObject *args, PyObject *keywords)
PyObject * objfpy_get_printers (PyObject *o, void *ignore)
static int objfpy_set_printers (PyObject *o, PyObject *value, void *ignore)
PyObject * objfpy_get_frame_filters (PyObject *o, void *ignore)
static int objfpy_set_frame_filters (PyObject *o, PyObject *filters, void *ignore)
static PyObject * objfpy_get_type_printers (PyObject *o, void *ignore)
static int objfpy_set_type_printers (PyObject *o, PyObject *value, void *ignore)
static PyObject * objfpy_is_valid (PyObject *self, PyObject *args)
static void py_free_objfile (struct objfile *objfile, void *datum)
PyObject * objfile_to_objfile_object (struct objfile *objfile)
int gdbpy_initialize_objfile (void)
Variables
static struct objfile_data * objfpy_objfile_data_key
static PyMethodDef objfile_object_methods []
static PyGetSetDef objfile_getset []
static PyTypeObject objfile_object_type
Function Documentation
static PyTypeObject objfile_object_type CPYCHECKER_TYPE_OBJECT_FOR_TYPEDEF ("objfile_object") [static]
int gdbpy_initialize_objfile (void)
Definition at line 303 of file py-objfile.c.
References gdb_module, gdb_pymodule_addobject(), objfile_object_type, objfpy_objfile_data_key, and py_free_objfile().
Referenced by _initialize_python().
PyObject* objfile_to_objfile_object (struct objfile * objfile)
Definition at line 262 of file py-objfile.c.
References objfile_object::frame_filters, objfile_object_type, objfpy_objfile_data_key, objfile_object::printers, Py_DECREF, and objfile_object::type_printers.
Referenced by create_new_objfile_event_object(), and stpy_get_objfile().
static void objfpy_dealloc (PyObject * o) [static]
Definition at line 63 of file py-objfile.c.
static PyObject* objfpy_get_filename (PyObject * self, void * closure) [static]
Definition at line 51 of file py-objfile.c.
References host_charset(), objfile_object::objfile, and objfile_name().
PyObject* objfpy_get_frame_filters (PyObject * o, void * ignore)
Definition at line 147 of file py-objfile.c.
PyObject* objfpy_get_printers (PyObject * o, void * ignore)
Definition at line 107 of file py-objfile.c.
static PyObject* objfpy_get_type_printers (PyObject * o, void * ignore) [static]
Definition at line 188 of file py-objfile.c.
static PyObject* objfpy_is_valid (PyObject * self, PyObject * args) [static]
Definition at line 231 of file py-objfile.c.
References objfile_object::objfile.
static PyObject* objfpy_new (PyTypeObject * type, PyObject * args, PyObject * keywords) [static]
Definition at line 74 of file py-objfile.c.
References objfile_object::objfile, and Py_DECREF.
static int objfpy_set_frame_filters (PyObject * o, PyObject * filters, void * ignore) [static]
Definition at line 157 of file py-objfile.c.
References _.
static int objfpy_set_printers (PyObject * o, PyObject * value, void * ignore) [static]
Definition at line 116 of file py-objfile.c.
References _.
static int objfpy_set_type_printers (PyObject * o, PyObject * value, void * ignore) [static]
Definition at line 199 of file py-objfile.c.
References _.
static void py_free_objfile (struct objfile * objfile, void * datum) [static]
Definition at line 246 of file py-objfile.c.
References current_language, do_cleanups(), ensure_python_env(), get_objfile_arch(), and Py_DECREF.
Referenced by gdbpy_initialize_objfile().
Variable Documentation
PyGetSetDef objfile_getset[] [static]
Initial value:
{
  { "filename", objfpy_get_filename, NULL,
    "The objfile's filename, or None.", NULL },
  { "pretty_printers", objfpy_get_printers, objfpy_set_printers,
    "Pretty printers.", NULL },
  { "frame_filters", objfpy_get_frame_filters,
    objfpy_set_frame_filters, "Frame Filters.", NULL },
  { "type_printers", objfpy_get_type_printers, objfpy_set_type_printers,
    "Type printers.", NULL },
  { NULL }
}
Definition at line 326 of file py-objfile.c.
PyMethodDef objfile_object_methods[] [static]
Initial value:
{
  { "is_valid", objfpy_is_valid, METH_NOARGS,
    "is_valid () -> Boolean.\n\
Return true if this object file is valid, false if not." },
  { NULL }
}
Definition at line 317 of file py-objfile.c.
PyTypeObject objfile_object_type [static]
Definition at line 339 of file py-objfile.c.
Referenced by gdbpy_initialize_objfile(), and objfile_to_objfile_object().
struct objfile_data* objfpy_objfile_data_key [static]
Definition at line 45 of file py-objfile.c.
Referenced by gdbpy_initialize_objfile(), and objfile_to_objfile_object().