GDB (xrefs): /home/stan/gdb/src/gdb/python/py-progspace.c File Reference
/home/stan/gdb/src/gdb/python/py-progspace.c File Reference
#include "defs.h"
#include "python-internal.h"
#include "charset.h"
#include "progspace.h"
#include "objfiles.h"
#include "language.h"
#include "arch-utils.h"
Classes
struct pspace_object
Functions
static PyTypeObject
pspace_object_type CPYCHECKER_TYPE_OBJECT_FOR_TYPEDEF ("pspace_object")
static PyObject * pspy_get_filename (PyObject *self, void *closure)
static void pspy_dealloc (PyObject *self)
static PyObject * pspy_new (PyTypeObject *type, PyObject *args, PyObject *keywords)
PyObject * pspy_get_printers (PyObject *o, void *ignore)
static int pspy_set_printers (PyObject *o, PyObject *value, void *ignore)
PyObject * pspy_get_frame_filters (PyObject *o, void *ignore)
static int pspy_set_frame_filters (PyObject *o, PyObject *frame, void *ignore)
static PyObject * pspy_get_type_printers (PyObject *o, void *ignore)
static int pspy_set_type_printers (PyObject *o, PyObject *value, void *ignore)
static void py_free_pspace (struct program_space *pspace, void *datum)
PyObject * pspace_to_pspace_object (struct program_space *pspace)
int gdbpy_initialize_pspace (void)
Variables
static struct program_space_data * pspy_pspace_data_key
static PyGetSetDef pspace_getset []
static PyTypeObject pspace_object_type
Function Documentation
static PyTypeObject pspace_object_type CPYCHECKER_TYPE_OBJECT_FOR_TYPEDEF ("pspace_object") [static]
int gdbpy_initialize_pspace (void)
Definition at line 299 of file py-progspace.c.
References gdb_module, gdb_pymodule_addobject(), pspace_object_type, pspy_pspace_data_key, and py_free_pspace().
Referenced by _initialize_python().
PyObject* pspace_to_pspace_object (struct program_space * pspace)
Definition at line 258 of file py-progspace.c.
References pspace_object::frame_filters, pspace_object::printers, pspace_object_type, pspy_pspace_data_key, Py_DECREF, and pspace_object::type_printers.
static void pspy_dealloc (PyObject * self) [static]
Definition at line 71 of file py-progspace.c.
References pspace_object::frame_filters, pspace_object::printers, and pspace_object::type_printers.
static PyObject* pspy_get_filename (PyObject * self, void * closure) [static]
Definition at line 54 of file py-progspace.c.
References host_charset(), objfile_name(), pspace_object::pspace, and program_space::symfile_object_file.
PyObject* pspy_get_frame_filters (PyObject * o, void * ignore)
Definition at line 155 of file py-progspace.c.
PyObject* pspy_get_printers (PyObject * o, void * ignore)
Definition at line 115 of file py-progspace.c.
static PyObject* pspy_get_type_printers (PyObject * o, void * ignore) [static]
Definition at line 196 of file py-progspace.c.
static PyObject* pspy_new (PyTypeObject * type, PyObject * args, PyObject * keywords) [static]
Definition at line 82 of file py-progspace.c.
References pspace_object::pspace, and Py_DECREF.
static int pspy_set_frame_filters (PyObject * o, PyObject * frame, void * ignore) [static]
Definition at line 165 of file py-progspace.c.
static int pspy_set_printers (PyObject * o, PyObject * value, void * ignore) [static]
Definition at line 124 of file py-progspace.c.
static int pspy_set_type_printers (PyObject * o, PyObject * value, void * ignore) [static]
Definition at line 207 of file py-progspace.c.
static void py_free_pspace (struct program_space * pspace, void * datum) [static]
Definition at line 240 of file py-progspace.c.
References current_language, do_cleanups(), ensure_python_env(), get_current_arch(), and Py_DECREF.
Referenced by gdbpy_initialize_pspace().
Variable Documentation
PyGetSetDef pspace_getset[] [static]
Initial value:
{
  { "filename", pspy_get_filename, NULL,
    "The progspace's main filename, or None.", NULL },
  { "pretty_printers", pspy_get_printers, pspy_set_printers,
    "Pretty printers.", NULL },
  { "frame_filters", pspy_get_frame_filters, pspy_set_frame_filters,
    "Frame filters.", NULL },
  { "type_printers", pspy_get_type_printers, pspy_set_type_printers,
    "Type printers.", NULL },
  { NULL }
}
Definition at line 313 of file py-progspace.c.
PyTypeObject pspace_object_type [static]
Definition at line 326 of file py-progspace.c.
Referenced by gdbpy_initialize_pspace(), and pspace_to_pspace_object().
struct program_space_data* pspy_pspace_data_key [static]
Definition at line 47 of file py-progspace.c.
Referenced by gdbpy_initialize_pspace(), and pspace_to_pspace_object().