GDB (xrefs): /home/stan/gdb/src/gdb/python/py-param.c File Reference
/home/stan/gdb/src/gdb/python/py-param.c File Reference
#include "defs.h"
#include "value.h"
#include "exceptions.h"
#include "python-internal.h"
#include "charset.h"
#include "gdbcmd.h"
#include "cli/cli-decode.h"
#include "completer.h"
#include "language.h"
#include "arch-utils.h"
Classes
struct parm_constant
union parmpy_variable
struct parmpy_object
Typedefs
typedef struct parmpy_object parmpy_object
Functions
static PyTypeObject
parmpy_object_type CPYCHECKER_TYPE_OBJECT_FOR_TYPEDEF ("parmpy_object")
static PyObject * get_attr (PyObject *obj, PyObject *attr_name)
static int set_parameter_value (parmpy_object *self, PyObject *value)
static int set_attr (PyObject *obj, PyObject *attr_name, PyObject *val)
static char * get_doc_string (PyObject *object, PyObject *attr)
static char * call_doc_function (PyObject *obj, PyObject *method, PyObject *arg)
static void get_set_value (char *args, int from_tty, struct cmd_list_element *c)
static void get_show_value (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static void add_setshow_generic (int parmclass, enum command_class cmdclass, char *cmd_name, parmpy_object *self, char *set_doc, char *show_doc, char *help_doc, struct cmd_list_element **set_list, struct cmd_list_element **show_list)
static int compute_enum_values (parmpy_object *self, PyObject *enum_values)
static int parmpy_init (PyObject *self, PyObject *args, PyObject *kwds)
int gdbpy_initialize_parameters (void)
Variables
struct parm_constant parm_constants []
static PyObject * set_doc_cst
static PyObject * show_doc_cst
static PyTypeObject parmpy_object_type
Typedef Documentation
typedef struct parmpy_object parmpy_object
Definition at line 90 of file py-param.c.
Function Documentation
static void add_setshow_generic (int parmclass, enum command_class cmdclass, char * cmd_name, parmpy_object * self, char * set_doc, char * show_doc, char * help_doc, struct cmd_list_element ** set_list, struct cmd_list_element ** show_list) [static]
Definition at line 466 of file py-param.c.
References add_setshow_auto_boolean_cmd(), add_setshow_boolean_cmd(), add_setshow_enum_cmd(), add_setshow_filename_cmd(), add_setshow_integer_cmd(), add_setshow_optional_filename_cmd(), add_setshow_string_cmd(), add_setshow_string_noescape_cmd(), add_setshow_uinteger_cmd(), add_setshow_zinteger_cmd(), get_set_value(), get_show_value(), lookup_cmd(), set_cmd_context(), var_auto_boolean, var_boolean, var_enum, var_filename, var_integer, var_optional_filename, var_string, var_string_noescape, var_uinteger, and var_zinteger.
Referenced by parmpy_init().
static char* call_doc_function (PyObject * obj, PyObject * method, PyObject * arg) [static]
Definition at line 332 of file py-param.c.
References _, gdbpy_is_string(), Py_DECREF, and python_string_to_host_string().
Referenced by get_set_value(), and get_show_value().
static int compute_enum_values (parmpy_object * self, PyObject * enum_values) [static]
Definition at line 569 of file py-param.c.
References _, discard_cleanups(), do_cleanups(), free_current_contents(), gdbpy_is_string(), make_cleanup(), memset(), Py_DECREF, python_string_to_host_string(), size, xfree(), and xmalloc().
Referenced by parmpy_init().
static PyTypeObject parmpy_object_type CPYCHECKER_TYPE_OBJECT_FOR_TYPEDEF ("parmpy_object") [static]
int gdbpy_initialize_parameters (void)
Definition at line 754 of file py-param.c.
References gdb_module, gdb_pymodule_addobject(), parm_constant::name, name, parmpy_object_type, set_doc_cst, and show_doc_cst.
Referenced by _initialize_python().
static PyObject* get_attr (PyObject * obj, PyObject * attr_name) [static]
Definition at line 103 of file py-param.c.
References gdbpy_parameter_value().
static char* get_doc_string (PyObject * object, PyObject * attr) [static]
Definition at line 306 of file py-param.c.
References _, gdbpy_is_string(), gdbpy_print_stack(), and python_string_to_host_string().
Referenced by get_set_value(), get_show_value(), and parmpy_init().
static void get_set_value (char * args, int from_tty, struct cmd_list_element * c) [static]
Definition at line 365 of file py-param.c.
References call_doc_function(), current_language, do_cleanups(), ensure_python_env(), error(), fprintf_filtered(), gdb_stdout, gdbpy_print_stack(), get_cmd_context(), get_current_arch(), get_doc_string(), make_cleanup(), set_doc_cst, and xfree().
Referenced by add_setshow_generic().
static void get_show_value (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 412 of file py-param.c.
References call_doc_function(), current_language, do_cleanups(), ensure_python_env(), error(), fprintf_filtered(), gdbpy_print_stack(), get_cmd_context(), get_current_arch(), get_doc_string(), make_cleanup(), Py_DECREF, show_doc_cst, and xfree().
Referenced by add_setshow_generic().
static int parmpy_init (PyObject * self, PyObject * args, PyObject * kwds) [static]
Definition at line 657 of file py-param.c.
References _, add_setshow_generic(), class_breakpoint, class_files, class_info, class_maintenance, class_obscure, class_run, class_stack, class_support, class_trace, class_vars, compute_enum_values(), parmpy_object::enumeration, gdbpy_doc_cst, gdbpy_parse_command_name(), get_doc_string(), memset(), gdb_exception::message, name, no_class, Py_DECREF, gdb_exception::reason, RETURN_MASK_ALL, RETURN_QUIT, set_doc_cst, setlist, show_doc_cst, showlist, TRY_CATCH, parmpy_object::type, parmpy_object::value, var_auto_boolean, var_boolean, var_enum, var_filename, var_integer, var_optional_filename, var_string, var_string_noescape, var_uinteger, var_zinteger, and xfree().
static int set_attr (PyObject * obj, PyObject * attr_name, PyObject * val) [static]
Definition at line 281 of file py-param.c.
References _, and set_parameter_value().
static int set_parameter_value (parmpy_object * self, PyObject * value) [static]
Definition at line 123 of file py-param.c.
References _, AUTO_BOOLEAN_AUTO, AUTO_BOOLEAN_FALSE, AUTO_BOOLEAN_TRUE, gdb_py_int_as_long(), gdbpy_is_string(), int, python_string_to_host_string(), string, var_auto_boolean, var_boolean, var_enum, var_filename, var_integer, var_optional_filename, var_string, var_string_noescape, var_uinteger, var_zinteger, and xfree().
Referenced by set_attr().
Variable Documentation
struct parm_constant parm_constants[]
Initial value:
{
  { "PARAM_BOOLEAN", var_boolean },
  { "PARAM_AUTO_BOOLEAN", var_auto_boolean },
  { "PARAM_UINTEGER", var_uinteger },
  { "PARAM_INTEGER", var_integer },
  { "PARAM_STRING", var_string },
  { "PARAM_STRING_NOESCAPE", var_string_noescape },
  { "PARAM_OPTIONAL_FILENAME", var_optional_filename },
  { "PARAM_FILENAME", var_filename },
  { "PARAM_ZINTEGER", var_zinteger },
  { "PARAM_ENUM", var_enum },
  { NULL, 0 }
}
Definition at line 39 of file py-param.c.
PyTypeObject parmpy_object_type [static]
Definition at line 783 of file py-param.c.
Referenced by gdbpy_initialize_parameters().
PyObject* set_doc_cst [static]
Definition at line 96 of file py-param.c.
Referenced by gdbpy_initialize_parameters(), get_set_value(), and parmpy_init().
PyObject* show_doc_cst [static]
Definition at line 97 of file py-param.c.
Referenced by gdbpy_initialize_parameters(), get_show_value(), and parmpy_init().