GDB (xrefs): /home/stan/gdb/src/gdb/python/py-signalevent.c File Reference
/home/stan/gdb/src/gdb/python/py-signalevent.c File Reference
#include "defs.h"
#include "py-stopevent.h"
Functions
static PyTypeObject
signal_event_object_type CPYCHECKER_TYPE_OBJECT_FOR_TYPEDEF ("event_object")
PyObject * create_signal_event_object (enum gdb_signal stop_signal)
GDBPY_NEW_EVENT_TYPE (signal,"gdb.SignalEvent","SignalEvent","GDB signal event object", stop_event_object_type, static)
Function Documentation
static PyTypeObject signal_event_object_type CPYCHECKER_TYPE_OBJECT_FOR_TYPEDEF ("event_object") [static]
PyObject* create_signal_event_object (enum gdb_signal stop_signal)
Definition at line 27 of file py-signalevent.c.
References create_stop_event_object(), evpy_add_attribute(), gdb_signal_to_name(), and Py_DECREF.
Referenced by emit_stop_event().
GDBPY_NEW_EVENT_TYPE (signal , "gdb.SignalEvent" , "SignalEvent" , "GDB signal event object" , stop_event_object_type , static)