GDB (xrefs): /home/stan/gdb/src/gdb/python/py-threadevent.c File Reference
/home/stan/gdb/src/gdb/python/py-threadevent.c File Reference
#include "defs.h"
#include "py-event.h"
Functions
static PyObject * get_event_thread (void)
PyObject * create_thread_event_object (PyTypeObject *py_type)
GDBPY_NEW_EVENT_TYPE (thread,"gdb.ThreadEvent","ThreadEvent","GDB thread event object", event_object_type,)
Function Documentation
PyObject* create_thread_event_object (PyTypeObject * py_type)
Definition at line 50 of file py-threadevent.c.
References create_event_object(), evpy_add_attribute(), and get_event_thread().
Referenced by create_continue_event_object(), and create_stop_event_object().
GDBPY_NEW_EVENT_TYPE (thread , "gdb.ThreadEvent" , "ThreadEvent" , "GDB thread event object" , event_object_type)
static PyObject* get_event_thread (void) [static]
Definition at line 27 of file py-threadevent.c.
References find_thread_object(), inferior_ptid, and non_stop.
Referenced by create_thread_event_object().