GDB (xrefs): /home/stan/gdb/src/gdb/python/py-utils.c File Reference
/home/stan/gdb/src/gdb/python/py-utils.c File Reference
#include "defs.h"
#include "charset.h"
#include "value.h"
#include "python-internal.h"
Functions
static void py_decref (void *p)
struct cleanup * make_cleanup_py_decref (PyObject *py)
static void py_xdecref (void *p)
struct cleanup * make_cleanup_py_xdecref (PyObject *py)
PyObject * python_string_to_unicode (PyObject *obj)
static char * unicode_to_encoded_string (PyObject *unicode_str, const char *charset)
static PyObject * unicode_to_encoded_python_string (PyObject *unicode_str, const char *charset)
char * unicode_to_target_string (PyObject *unicode_str)
static PyObject * unicode_to_target_python_string (PyObject *unicode_str)
char * python_string_to_target_string (PyObject *obj)
PyObject * python_string_to_target_python_string (PyObject *obj)
char * python_string_to_host_string (PyObject *obj)
int gdbpy_is_string (PyObject *obj)
char * gdbpy_obj_to_string (PyObject *obj)
char * gdbpy_exception_to_string (PyObject *ptype, PyObject *pvalue)
void gdbpy_convert_exception (struct gdb_exception exception)
int get_addr_from_python (PyObject *obj, CORE_ADDR *addr)
PyObject * gdb_py_object_from_longest (LONGEST l)
PyObject * gdb_py_object_from_ulongest (ULONGEST l)
int gdb_py_int_as_long (PyObject *obj, long *result)
PyObject * gdb_py_generic_dict (PyObject *self, void *closure)
int gdb_pymodule_addobject (PyObject *module, const char *name, PyObject *object)
Function Documentation
PyObject* gdb_py_generic_dict (PyObject * self, void * closure)
Definition at line 417 of file py-utils.c.
int gdb_py_int_as_long (PyObject * obj, long * result)
Definition at line 404 of file py-utils.c.
Referenced by bppy_set_hit_count(), bppy_set_ignore_count(), bppy_set_task(), bppy_set_thread(), set_parameter_value(), typy_array_1(), and VEC().
PyObject* gdb_py_object_from_longest (LONGEST l)
Definition at line 357 of file py-utils.c.
References LONGEST.
PyObject* gdb_py_object_from_ulongest (ULONGEST l)
Definition at line 379 of file py-utils.c.
Referenced by blpy_get_end(), and blpy_get_start().
int gdb_pymodule_addobject (PyObject * module, const char * name, PyObject * object)
Definition at line 434 of file py-utils.c.
References Py_DECREF.
Referenced by _initialize_python(), add_new_registry(), gdbpy_initialize_arch(), gdbpy_initialize_blocks(), gdbpy_initialize_breakpoints(), gdbpy_initialize_commands(), gdbpy_initialize_event_generic(), gdbpy_initialize_eventregistry(), gdbpy_initialize_finishbreakpoints(), gdbpy_initialize_frames(), gdbpy_initialize_functions(), gdbpy_initialize_inferior(), gdbpy_initialize_objfile(), gdbpy_initialize_parameters(), gdbpy_initialize_pspace(), gdbpy_initialize_py_events(), gdbpy_initialize_symbols(), gdbpy_initialize_symtabs(), gdbpy_initialize_thread(), and gdbpy_initialize_types().
void gdbpy_convert_exception (struct gdb_exception exception)
Definition at line 295 of file py-utils.c.
References gdb_exception::error, gdbpy_gdb_error, gdbpy_gdb_memory_error, MEMORY_ERROR, gdb_exception::message, gdb_exception::reason, and RETURN_QUIT.
Referenced by apply_frame_filter(), archpy_disassemble(), bpfinishpy_detect_out_scope_cb(), bpfinishpy_init(), bpfinishpy_post_stop_hook(), bpfinishpy_pre_stop_hook(), bppy_get_commands(), enumerate_args(), enumerate_locals(), frame_info_to_frame_object(), frapy_read_var(), gdbpy_readline_wrapper(), py_print_args(), py_print_frame(), py_print_single_arg(), py_print_type(), and py_print_value().
char* gdbpy_exception_to_string (PyObject * ptype, PyObject * pvalue)
Definition at line 268 of file py-utils.c.
References gdbpy_obj_to_string().
Referenced by cmdpy_function(), fnpy_call(), and update_dynamic_varobj_children().
int gdbpy_is_string (PyObject * obj)
Definition at line 228 of file py-utils.c.
Referenced by call_doc_function(), cmdpy_init(), compute_enum_values(), extract_sym(), fnpy_init(), frapy_read_var(), get_doc_string(), py_print_frame(), set_parameter_value(), thpy_set_name(), and VEC().
char* gdbpy_obj_to_string (PyObject * obj)
Definition at line 242 of file py-utils.c.
References Py_DECREF, and python_string_to_host_string().
Referenced by gdbpy_exception_to_string().
int get_addr_from_python (PyObject * obj, CORE_ADDR * addr)
Definition at line 315 of file py-utils.c.
References _, gdb_py_long_as_ulongest, GDB_PY_SET_HANDLE_EXCEPTION, gdbpy_is_value_object(), RETURN_MASK_ALL, TRY_CATCH, value_as_address(), and value_object_to_value().
Referenced by infpy_read_memory(), infpy_search_memory(), and infpy_write_memory().
struct cleanup* make_cleanup_py_decref (PyObject * py) [read]
Definition at line 41 of file py-utils.c.
References make_cleanup(), and py_decref().
Referenced by apply_frame_filter(), bootstrap_python_frame_filters(), enumerate_locals(), py_mi_print_variables(), py_print_frame(), update_dynamic_varobj_children(), value_get_print_value(), and varobj_set_visualizer().
struct cleanup* make_cleanup_py_xdecref (PyObject * py) [read]
Definition at line 63 of file py-utils.c.
References make_cleanup(), and py_xdecref().
Referenced by py_mi_print_variables(), py_print_args(), and py_print_locals().
static void py_decref (void * p) [static]
Definition at line 30 of file py-utils.c.
References Py_DECREF.
Referenced by make_cleanup_py_decref().
static void py_xdecref (void * p) [static]
Definition at line 51 of file py-utils.c.
Referenced by make_cleanup_py_xdecref().
char* python_string_to_host_string (PyObject * obj)
Definition at line 210 of file py-utils.c.
References host_charset(), Py_DECREF, python_string_to_unicode(), and unicode_to_encoded_string().
Referenced by bppy_set_condition(), call_doc_function(), cmdpy_init(), compute_enum_values(), extract_sym(), fnpy_init(), gdbpy_obj_to_string(), get_doc_string(), local_setattro(), py_print_frame(), set_parameter_value(), thpy_set_name(), typy_getitem(), and VEC().
PyObject* python_string_to_target_python_string (PyObject * obj)
Definition at line 191 of file py-utils.c.
References Py_DECREF, python_string_to_unicode(), and unicode_to_target_python_string().
char* python_string_to_target_string (PyObject * obj)
Definition at line 171 of file py-utils.c.
References Py_DECREF, python_string_to_unicode(), and unicode_to_target_string().
Referenced by frapy_read_var(), and value_get_print_value().
PyObject* python_string_to_unicode (PyObject * obj)
Definition at line 80 of file py-utils.c.
References _, and host_charset().
Referenced by python_string_to_host_string(), python_string_to_target_python_string(), and python_string_to_target_string().
static PyObject* unicode_to_encoded_python_string (PyObject * unicode_str, const char * charset) [static]
Definition at line 137 of file py-utils.c.
Referenced by unicode_to_target_python_string().
static char* unicode_to_encoded_string (PyObject * unicode_str, const char * charset) [static]
Definition at line 111 of file py-utils.c.
References Py_DECREF, and string.
Referenced by python_string_to_host_string(), and unicode_to_target_string().
static PyObject* unicode_to_target_python_string (PyObject * unicode_str) [static]
Definition at line 160 of file py-utils.c.
References python_gdbarch, target_charset(), and unicode_to_encoded_python_string().
Referenced by python_string_to_target_python_string().
char* unicode_to_target_string (PyObject * unicode_str)
Definition at line 149 of file py-utils.c.
References python_gdbarch, target_charset(), and unicode_to_encoded_string().
Referenced by python_string_to_target_string().