GDB (xrefs): /home/stan/gdb/src/gdb/python/python.c File Reference
/home/stan/gdb/src/gdb/python/python.c File Reference
#include "defs.h"
#include "arch-utils.h"
#include "command.h"
#include "ui-out.h"
#include "cli/cli-script.h"
#include "gdbcmd.h"
#include "progspace.h"
#include "objfiles.h"
#include "value.h"
#include "language.h"
#include "exceptions.h"
#include "event-loop.h"
#include "serial.h"
#include "readline/tilde.h"
#include "python.h"
#include "cli/cli-utils.h"
#include <ctype.h>
Functions
static void python_interactive_command (char *arg, int from_tty)
static void python_command (char *arg, int from_tty)
void eval_python_from_control_command (struct command_line *cmd)
void source_python_script (FILE *file, const char *filename)
int gdbpy_should_stop (struct breakpoint_object *bp_obj)
int gdbpy_breakpoint_has_py_cond (struct breakpoint_object *bp_obj)
void * start_type_printers (void)
char * apply_type_printers (void *ignore, struct type *type)
void free_type_printers (void *arg)
enum py_bt_status apply_frame_filter (struct frame_info *frame, int flags, enum py_frame_args args_type, struct ui_out *out, int frame_low, int frame_high)
static void user_set_python (char *args, int from_tty)
static void user_show_python (char *args, int from_tty)
void _initialize_python (void)
Variables
static const char python_excp_none [] = "none"
static const char python_excp_full [] = "full"
static const char python_excp_message [] = "message"
static const char *const python_excp_enums []
static const char * gdbpy_should_print_stack = python_excp_message
static struct cmd_list_element * user_set_python_list
static struct cmd_list_element * user_show_python_list
initialize_file_ftype _initialize_python
Function Documentation
void _initialize_python (void)
Definition at line 1492 of file python.c.
References _, add_com(), add_com_alias(), add_prefix_cmd(), add_setshow_enum_cmd(), class_obscure, gdb_module, gdb_pymodule_addobject(), gdb_python_initialized, gdbpy_children_cst, gdbpy_display_hint_cst, gdbpy_doc_cst, gdbpy_enabled_cst, gdbpy_gdb_error, gdbpy_gdb_memory_error, gdbpy_gdberror_exc, gdbpy_initialize_arch(), gdbpy_initialize_auto_load(), gdbpy_initialize_blocks(), gdbpy_initialize_breakpoint_event(), gdbpy_initialize_breakpoints(), gdbpy_initialize_commands(), gdbpy_initialize_continue_event(), gdbpy_initialize_event(), gdbpy_initialize_eventregistry(), gdbpy_initialize_exited_event(), gdbpy_initialize_finishbreakpoints(), gdbpy_initialize_frames(), gdbpy_initialize_functions(), gdbpy_initialize_gdb_readline(), gdbpy_initialize_inferior(), gdbpy_initialize_lazy_string(), gdbpy_initialize_new_objfile_event(), gdbpy_initialize_objfile(), gdbpy_initialize_parameters(), gdbpy_initialize_pspace(), gdbpy_initialize_py_events(), gdbpy_initialize_signal_event(), gdbpy_initialize_stop_event(), gdbpy_initialize_symbols(), gdbpy_initialize_symtabs(), gdbpy_initialize_thread(), gdbpy_initialize_thread_event(), gdbpy_initialize_types(), gdbpy_initialize_values(), gdbpy_print_stack(), gdbpy_should_print_stack, gdbpy_to_string_cst, gdbpy_value_cst, host_name, ldirname(), make_final_cleanup(), no_class, observer_attach_before_prompt(), PyEval_InitThreads, PyEval_ReleaseLock, python_command(), python_excp_enums, python_interactive_command(), python_libdir, PyThreadState_Swap, setlist, showlist, target_name, user_set_python(), user_show_python(), and version.
enum py_bt_status apply_frame_filter (struct frame_info * frame, int flags, enum py_frame_args args_type, struct ui_out * out, int frame_low, int frame_high)
Definition at line 1431 of file python.c.
References bootstrap_python_frame_filters(), current_language, do_cleanups(), ensure_python_env(), error(), gdb_python_initialized, gdbpy_convert_exception(), gdbpy_print_stack(), get_frame_arch(), make_cleanup_htab_delete(), make_cleanup_py_decref(), PY_BT_ERROR, PY_BT_NO_FILTERS, Py_DECREF, py_print_frame(), gdb_exception::reason, RETURN_MASK_ALL, and TRY_CATCH.
char* apply_type_printers (void * ignore, struct type * type)
Definition at line 1420 of file python.c.
Referenced by find_global_typedef().
void eval_python_from_control_command (struct command_line * cmd)
Definition at line 1385 of file python.c.
References _, and error().
Referenced by execute_control_command().
void free_type_printers (void * arg)
Definition at line 1426 of file python.c.
Referenced by do_free_global_table().
int gdbpy_breakpoint_has_py_cond (struct breakpoint_object * bp_obj)
Definition at line 1406 of file python.c.
References _, breakpoint_object::bp, current_language, do_cleanups(), ensure_python_env(), breakpoint::gdbarch, get_current_arch(), internal_error(), and stop_func.
int gdbpy_should_stop (struct breakpoint_object * bp_obj)
Definition at line 1398 of file python.c.
References _, breakpoint_object::bp, bpfinishpy_post_stop_hook(), bpfinishpy_pre_stop_hook(), current_language, do_cleanups(), ensure_python_env(), breakpoint::gdbarch, gdbpy_print_stack(), get_current_arch(), internal_error(), breakpoint_object::is_finish_bp, Py_DECREF, and stop_func.
static void python_command (char * arg, int from_tty) [static]
Definition at line 1379 of file python.c.
References python_interactive_command().
Referenced by _initialize_python().
static void python_interactive_command (char * arg, int from_tty) [static]
Definition at line 1363 of file python.c.
References _, do_cleanups(), error(), execute_control_command_untraced(), get_command_line(), make_cleanup_free_command_lines(), python_control, and skip_spaces().
Referenced by _initialize_python(), and python_command().
void source_python_script (FILE * file, const char * filename)
Definition at line 1391 of file python.c.
References _, throw_error(), and UNSUPPORTED_ERROR.
Referenced by source_script_from_stream().
void* start_type_printers (void)
Definition at line 1414 of file python.c.
Referenced by create_global_typedef_table().
static void user_set_python (char * args, int from_tty) [static]
Definition at line 1451 of file python.c.
References all_commands, gdb_stdout, and help_list().
Referenced by _initialize_python().
static void user_show_python (char * args, int from_tty) [static]
Definition at line 1460 of file python.c.
References cmd_show_list().
Referenced by _initialize_python().
Variable Documentation
initialize_file_ftype _initialize_python
Referenced by initialize_all_files().
const char* gdbpy_should_print_stack = python_excp_message [static]
Definition at line 57 of file python.c.
Referenced by _initialize_python().
const char* const python_excp_enums[] [static]
Initial value:
  {
    python_excp_none,
    python_excp_full,
    python_excp_message,
    NULL
  }
Definition at line 45 of file python.c.
Referenced by _initialize_python().
const char python_excp_full[] = "full" [static]
Definition at line 41 of file python.c.
const char python_excp_message[] = "message" [static]
Definition at line 42 of file python.c.
const char python_excp_none[] = "none" [static]
Definition at line 40 of file python.c.
struct cmd_list_element* user_set_python_list [static]
Definition at line 1445 of file python.c.
struct cmd_list_element* user_show_python_list [static]
Definition at line 1446 of file python.c.