GDB (xrefs): /home/stan/gdb/src/gdb/python/python.h File Reference
/home/stan/gdb/src/gdb/python/python.h File Reference
#include "value.h"
#include "mi/mi-cmds.h"
Defines
#define GDBPY_AUTO_FILE_NAME "-gdb.py"
Typedefs
typedef enum py_frame_args py_frame_args
Enumerations
enum py_bt_status { PY_BT_ERROR = -1, PY_BT_OK = 1, PY_BT_COMPLETED = 2, PY_BT_NO_FILTERS = 3 }
enum frame_filter_flags { PRINT_LEVEL = 1, PRINT_FRAME_INFO = 2, PRINT_ARGS = 4, PRINT_LOCALS = 8 }
enum py_frame_args {
NO_VALUES = PRINT_NO_VALUES, MI_PRINT_ALL_VALUES = PRINT_ALL_VALUES, MI_PRINT_SIMPLE_VALUES = PRINT_SIMPLE_VALUES, CLI_SCALAR_VALUES,
CLI_ALL_VALUES
}
Functions
void finish_python_initialization (void)
void eval_python_from_control_command (struct command_line *)
void source_python_script (FILE *file, const char *filename)
int apply_val_pretty_printer (struct type *type, const gdb_byte *valaddr, int embedded_offset, CORE_ADDR address, struct ui_file *stream, int recurse, const struct value *val, const struct value_print_options *options, const struct language_defn *language)
enum py_bt_status apply_frame_filter (struct frame_info *frame, int flags, enum py_frame_args args_type, struct ui_out *out, int frame_low, int frame_high)
void preserve_python_values (struct objfile *objfile, htab_t copied_types)
void gdbpy_load_auto_scripts_for_objfile (struct objfile *objfile)
int gdbpy_should_stop (struct breakpoint_object *bp_obj)
int gdbpy_breakpoint_has_py_cond (struct breakpoint_object *bp_obj)
void * start_type_printers (void)
char * apply_type_printers (void *, struct type *type)
void free_type_printers (void *arg)
Define Documentation
#define GDBPY_AUTO_FILE_NAME "-gdb.py"
Definition at line 30 of file python.h.
Typedef Documentation
typedef enum py_frame_args py_frame_args
Enumeration Type Documentation
enum frame_filter_flags
Enumerator:
PRINT_LEVEL
PRINT_FRAME_INFO
PRINT_ARGS
PRINT_LOCALS
Definition at line 54 of file python.h.
enum py_bt_status
Enumerator:
PY_BT_ERROR
PY_BT_OK
PY_BT_COMPLETED
PY_BT_NO_FILTERS
Definition at line 33 of file python.h.
enum py_frame_args
Enumerator:
NO_VALUES
MI_PRINT_ALL_VALUES
MI_PRINT_SIMPLE_VALUES
CLI_SCALAR_VALUES
CLI_ALL_VALUES
Definition at line 71 of file python.h.
Function Documentation
enum py_bt_status apply_frame_filter (struct frame_info * frame, int flags, enum py_frame_args args_type, struct ui_out * out, int frame_low, int frame_high)
Definition at line 1463 of file py-framefilter.c.
References bootstrap_python_frame_filters(), current_language, do_cleanups(), ensure_python_env(), error(), gdb_python_initialized, gdbpy_convert_exception(), gdbpy_print_stack(), get_frame_arch(), make_cleanup_htab_delete(), make_cleanup_py_decref(), PY_BT_ERROR, PY_BT_NO_FILTERS, Py_DECREF, py_print_frame(), gdb_exception::reason, RETURN_MASK_ALL, and TRY_CATCH.
Referenced by backtrace_command_1(), mi_cmd_stack_list_args(), mi_cmd_stack_list_frames(), mi_cmd_stack_list_locals(), and mi_cmd_stack_list_variables().
char* apply_type_printers (void * , struct type * type)
Definition at line 1420 of file python.c.
Referenced by find_global_typedef().
int apply_val_pretty_printer (struct type * type, const gdb_byte * valaddr, int embedded_offset, CORE_ADDR address, struct ui_file * stream, int recurse, const struct value * val, const struct value_print_options * options, const struct language_defn * language)
Definition at line 845 of file py-prettyprint.c.
Referenced by cp_print_value(), val_print(), and value_print().
void eval_python_from_control_command (struct command_line *)
Definition at line 1385 of file python.c.
References _, and error().
Referenced by execute_control_command().
void finish_python_initialization (void)
Referenced by gdb_init().
void free_type_printers (void * arg)
Definition at line 1426 of file python.c.
Referenced by do_free_global_table().
int gdbpy_breakpoint_has_py_cond (struct breakpoint_object * bp_obj)
Definition at line 773 of file py-breakpoint.c.
References _, breakpoint_object::bp, current_language, do_cleanups(), ensure_python_env(), breakpoint::gdbarch, get_current_arch(), internal_error(), and stop_func.
Referenced by condition_command().
void gdbpy_load_auto_scripts_for_objfile (struct objfile * objfile)
Definition at line 291 of file py-auto-load.c.
Referenced by load_auto_scripts_for_objfile().
int gdbpy_should_stop (struct breakpoint_object * bp_obj)
Definition at line 726 of file py-breakpoint.c.
References _, breakpoint_object::bp, bpfinishpy_post_stop_hook(), bpfinishpy_pre_stop_hook(), current_language, do_cleanups(), ensure_python_env(), breakpoint::gdbarch, gdbpy_print_stack(), get_current_arch(), internal_error(), breakpoint_object::is_finish_bp, Py_DECREF, and stop_func.
Referenced by bpstat_check_breakpoint_conditions().
void preserve_python_values (struct objfile * objfile, htab_t copied_types)
Definition at line 1548 of file py-value.c.
Referenced by preserve_values().
void source_python_script (FILE * file, const char * filename)
Definition at line 1391 of file python.c.
References _, throw_error(), and UNSUPPORTED_ERROR.
Referenced by source_script_from_stream().
void* start_type_printers (void)
Definition at line 1414 of file python.c.
Referenced by create_global_typedef_table().