GDB (xrefs): /home/stan/gdb/src/gdb/python/python-internal.h File Reference
/home/stan/gdb/src/gdb/python/python-internal.h File Reference
#include <stdio.h>
#include <stdint.h>
#include <Python.h>
#include <frameobject.h>
#include "symtab.h"
#include "command.h"
#include "breakpoint.h"
#include "exceptions.h"
Classes
struct breakpoint_object
struct thread_object
Defines
#define CPYCHECKER_RETURNS_BORROWED_REF
#define CPYCHECKER_TYPE_OBJECT_FOR_TYPEDEF(ARG)
#define CPYCHECKER_STEALS_REFERENCE_TO_ARG(n)
#define CPYCHECKER_SETS_EXCEPTION
#define CPYCHECKER_NEGATIVE_RESULT_SETS_EXCEPTION
#define PY_SSIZE_T_CLEAN
#define PyGILState_Ensure() ((PyGILState_STATE) 0)
#define PyGILState_Release(ARG) ((void)(ARG))
#define PyEval_InitThreads()
#define PyThreadState_Swap(ARG) ((void)(ARG))
#define PyEval_ReleaseLock()
#define GDB_PY_LL_ARG "L"
#define GDB_PY_LLU_ARG "K"
#define gdb_py_long_from_longest PyLong_FromLong
#define gdb_py_long_from_ulongest PyLong_FromUnsignedLong
#define gdb_py_long_as_ulongest PyLong_AsUnsignedLong
#define Py_DECREF(op) gdb_Py_DECREF (op)
#define BPPY_REQUIRE_VALID(Breakpoint)
#define BPPY_SET_REQUIRE_VALID(Breakpoint)
#define GDB_PY_HANDLE_EXCEPTION(Exception)
#define GDB_PY_SET_HANDLE_EXCEPTION(Exception)
Typedefs
typedef long gdb_py_longest
typedef unsigned long gdb_py_ulongest
typedef struct breakpoint_object breakpoint_object
Enumerations
enum gdbpy_iter_kind { iter_keys, iter_values, iter_items }
Functions
static void gdb_Py_DECREF (void *op)
PyTypeObject value_object_type CPYCHECKER_TYPE_OBJECT_FOR_TYPEDEF ("value_object")
PyTypeObject block_object_type CPYCHECKER_TYPE_OBJECT_FOR_TYPEDEF ("block_object")
PyTypeObject symbol_object_type CPYCHECKER_TYPE_OBJECT_FOR_TYPEDEF ("symbol_object")
PyTypeObject event_object_type CPYCHECKER_TYPE_OBJECT_FOR_TYPEDEF ("event_object")
PyTypeObject breakpoint_object_type CPYCHECKER_TYPE_OBJECT_FOR_TYPEDEF ("breakpoint_object")
PyTypeObject frame_object_type CPYCHECKER_TYPE_OBJECT_FOR_TYPEDEF ("frame_object")
PyObject * gdbpy_history (PyObject *self, PyObject *args)
PyObject * gdbpy_breakpoints (PyObject *, PyObject *)
PyObject * gdbpy_frame_stop_reason_string (PyObject *, PyObject *)
PyObject * gdbpy_lookup_symbol (PyObject *self, PyObject *args, PyObject *kw)
PyObject * gdbpy_lookup_global_symbol (PyObject *self, PyObject *args, PyObject *kw)
PyObject * gdbpy_newest_frame (PyObject *self, PyObject *args)
PyObject * gdbpy_selected_frame (PyObject *self, PyObject *args)
PyObject * gdbpy_block_for_pc (PyObject *self, PyObject *args)
PyObject * gdbpy_lookup_type (PyObject *self, PyObject *args, PyObject *kw)
PyObject * gdbpy_create_lazy_string_object (CORE_ADDR address, long length, const char *encoding, struct type *type)
PyObject * gdbpy_inferiors (PyObject *unused, PyObject *unused2)
PyObject * gdbpy_selected_thread (PyObject *self, PyObject *args)
PyObject * gdbpy_selected_inferior (PyObject *self, PyObject *args)
PyObject * gdbpy_string_to_argv (PyObject *self, PyObject *args)
PyObject * gdbpy_parameter (PyObject *self, PyObject *args)
PyObject * gdbpy_parameter_value (enum var_types type, void *var)
char * gdbpy_parse_command_name (const char *name, struct cmd_list_element ***base_list, struct cmd_list_element **start_list)
PyObject * symtab_and_line_to_sal_object (struct symtab_and_line sal)
PyObject * symtab_to_symtab_object (struct symtab *symtab)
PyObject * symbol_to_symbol_object (struct symbol *sym)
PyObject * block_to_block_object (const struct block *block, struct objfile *objfile)
PyObject * value_to_value_object (struct value *v)
PyObject * type_to_type_object (struct type *)
PyObject * frame_info_to_frame_object (struct frame_info *frame)
PyObject * pspace_to_pspace_object (struct program_space *) CPYCHECKER_RETURNS_BORROWED_REF
PyObject * pspy_get_printers (PyObject *, void *)
PyObject * pspy_get_frame_filters (PyObject *, void *)
PyObject * objfile_to_objfile_object (struct objfile *) CPYCHECKER_RETURNS_BORROWED_REF
PyObject * objfpy_get_printers (PyObject *, void *)
PyObject * objfpy_get_frame_filters (PyObject *, void *)
PyObject * gdbarch_to_arch_object (struct gdbarch *gdbarch)
thread_object * create_thread_object (struct thread_info *tp)
thread_object * find_thread_object (ptid_t ptid) CPYCHECKER_RETURNS_BORROWED_REF
PyObject * find_inferior_object (int pid)
PyObject * inferior_to_inferior_object (struct inferior *inferior)
struct block * block_object_to_block (PyObject *obj)
struct symbol * symbol_object_to_symbol (PyObject *obj)
struct value * value_object_to_value (PyObject *self)
struct value * convert_value_from_python (PyObject *obj)
struct type * type_object_to_type (PyObject *obj)
struct symtab * symtab_object_to_symtab (PyObject *obj)
struct symtab_and_line * sal_object_to_symtab_and_line (PyObject *obj)
struct frame_info * frame_object_to_frame_info (PyObject *frame_obj)
struct gdbarch * arch_object_to_gdbarch (PyObject *obj)
void gdbpy_initialize_gdb_readline (void)
int gdbpy_initialize_auto_load (void) CPYCHECKER_NEGATIVE_RESULT_SETS_EXCEPTION
int gdbpy_initialize_values (void) CPYCHECKER_NEGATIVE_RESULT_SETS_EXCEPTION
int gdbpy_initialize_frames (void) CPYCHECKER_NEGATIVE_RESULT_SETS_EXCEPTION
int gdbpy_initialize_symtabs (void) CPYCHECKER_NEGATIVE_RESULT_SETS_EXCEPTION
int gdbpy_initialize_commands (void) CPYCHECKER_NEGATIVE_RESULT_SETS_EXCEPTION
int gdbpy_initialize_symbols (void) CPYCHECKER_NEGATIVE_RESULT_SETS_EXCEPTION
int gdbpy_initialize_blocks (void) CPYCHECKER_NEGATIVE_RESULT_SETS_EXCEPTION
int gdbpy_initialize_types (void) CPYCHECKER_NEGATIVE_RESULT_SETS_EXCEPTION
int gdbpy_initialize_functions (void) CPYCHECKER_NEGATIVE_RESULT_SETS_EXCEPTION
int gdbpy_initialize_pspace (void) CPYCHECKER_NEGATIVE_RESULT_SETS_EXCEPTION
int gdbpy_initialize_objfile (void) CPYCHECKER_NEGATIVE_RESULT_SETS_EXCEPTION
int gdbpy_initialize_breakpoints (void) CPYCHECKER_NEGATIVE_RESULT_SETS_EXCEPTION
int gdbpy_initialize_finishbreakpoints (void) CPYCHECKER_NEGATIVE_RESULT_SETS_EXCEPTION
int gdbpy_initialize_lazy_string (void) CPYCHECKER_NEGATIVE_RESULT_SETS_EXCEPTION
int gdbpy_initialize_parameters (void) CPYCHECKER_NEGATIVE_RESULT_SETS_EXCEPTION
int gdbpy_initialize_thread (void) CPYCHECKER_NEGATIVE_RESULT_SETS_EXCEPTION
int gdbpy_initialize_inferior (void) CPYCHECKER_NEGATIVE_RESULT_SETS_EXCEPTION
int gdbpy_initialize_eventregistry (void) CPYCHECKER_NEGATIVE_RESULT_SETS_EXCEPTION
int gdbpy_initialize_event (void) CPYCHECKER_NEGATIVE_RESULT_SETS_EXCEPTION
int gdbpy_initialize_py_events (void) CPYCHECKER_NEGATIVE_RESULT_SETS_EXCEPTION
int gdbpy_initialize_stop_event (void) CPYCHECKER_NEGATIVE_RESULT_SETS_EXCEPTION
int gdbpy_initialize_signal_event (void) CPYCHECKER_NEGATIVE_RESULT_SETS_EXCEPTION
int gdbpy_initialize_breakpoint_event (void) CPYCHECKER_NEGATIVE_RESULT_SETS_EXCEPTION
int gdbpy_initialize_continue_event (void) CPYCHECKER_NEGATIVE_RESULT_SETS_EXCEPTION
int gdbpy_initialize_exited_event (void) CPYCHECKER_NEGATIVE_RESULT_SETS_EXCEPTION
int gdbpy_initialize_thread_event (void) CPYCHECKER_NEGATIVE_RESULT_SETS_EXCEPTION
int gdbpy_initialize_new_objfile_event (void) CPYCHECKER_NEGATIVE_RESULT_SETS_EXCEPTION
int gdbpy_initialize_arch (void) CPYCHECKER_NEGATIVE_RESULT_SETS_EXCEPTION
struct cleanup * make_cleanup_py_decref (PyObject *py)
struct cleanup * make_cleanup_py_xdecref (PyObject *py)
struct cleanup * ensure_python_env (struct gdbarch *gdbarch, const struct language_defn *language)
void gdbpy_print_stack (void)
void source_python_script_for_objfile (struct objfile *objfile, FILE *file, const char *filename)
PyObject * python_string_to_unicode (PyObject *obj)
char * unicode_to_target_string (PyObject *unicode_str)
char * python_string_to_target_string (PyObject *obj)
PyObject * python_string_to_target_python_string (PyObject *obj)
char * python_string_to_host_string (PyObject *obj)
int gdbpy_is_string (PyObject *obj)
char * gdbpy_obj_to_string (PyObject *obj)
char * gdbpy_exception_to_string (PyObject *ptype, PyObject *pvalue)
int gdbpy_is_lazy_string (PyObject *result)
void gdbpy_extract_lazy_string (PyObject *string, CORE_ADDR *addr, struct type **str_type, long *length, char **encoding)
int gdbpy_is_value_object (PyObject *obj)
PyObject * apply_varobj_pretty_printer (PyObject *print_obj, struct value **replacement, struct ui_file *stream)
PyObject * gdbpy_get_varobj_pretty_printer (struct value *value)
char * gdbpy_get_display_hint (PyObject *printer)
PyObject * gdbpy_default_visualizer (PyObject *self, PyObject *args)
void bpfinishpy_pre_stop_hook (struct breakpoint_object *bp_obj)
void bpfinishpy_post_stop_hook (struct breakpoint_object *bp_obj)
void gdbpy_convert_exception (struct gdb_exception) CPYCHECKER_SETS_EXCEPTION
int get_addr_from_python (PyObject *obj, CORE_ADDR *addr) CPYCHECKER_NEGATIVE_RESULT_SETS_EXCEPTION
PyObject * gdb_py_object_from_longest (LONGEST l)
PyObject * gdb_py_object_from_ulongest (ULONGEST l)
int gdb_py_int_as_long (PyObject *, long *)
PyObject * gdb_py_generic_dict (PyObject *self, void *closure)
int gdb_pymodule_addobject (PyObject *module, const char *name, PyObject *object) CPYCHECKER_NEGATIVE_RESULT_SETS_EXCEPTION
Variables
int gdb_python_initialized
PyObject * gdb_module
PyObject * gdb_python_module
breakpoint_object * bppy_pending_object
struct cmd_list_element * set_python_list
struct cmd_list_element * show_python_list
struct gdbarch * python_gdbarch
struct language_defn * python_language
PyObject * gdbpy_doc_cst
PyObject * gdbpy_children_cst
PyObject * gdbpy_to_string_cst
PyObject * gdbpy_display_hint_cst
PyObject * gdbpy_enabled_cst
PyObject * gdbpy_value_cst
PyObject * gdbpy_gdb_error
PyObject * gdbpy_gdb_memory_error
PyObject * gdbpy_gdberror_exc
Define Documentation
#define BPPY_REQUIRE_VALID (Breakpoint)
Value:
do {                                                                \
      if ((Breakpoint)->bp == NULL)                                     \
        return PyErr_Format (PyExc_RuntimeError,                        \
                             _("Breakpoint %d is invalid."),            \
                             (Breakpoint)->number);                     \
    } while (0)
Definition at line 243 of file python-internal.h.
Referenced by bppy_delete_breakpoint(), bppy_get_commands(), bppy_get_condition(), bppy_get_enabled(), bppy_get_expression(), bppy_get_hit_count(), bppy_get_ignore_count(), bppy_get_location(), bppy_get_number(), bppy_get_silent(), bppy_get_task(), bppy_get_thread(), bppy_get_type(), and bppy_get_visibility().
#define BPPY_SET_REQUIRE_VALID (Breakpoint)
Value:
do {                                                                \
      if ((Breakpoint)->bp == NULL)                                     \
        {                                                               \
          PyErr_Format (PyExc_RuntimeError, _("Breakpoint %d is invalid."), \
                        (Breakpoint)->number);                          \
          return -1;                                                    \
        }                                                               \
    } while (0)
Definition at line 253 of file python-internal.h.
Referenced by bppy_init(), bppy_set_condition(), bppy_set_enabled(), bppy_set_hit_count(), bppy_set_ignore_count(), bppy_set_silent(), bppy_set_task(), and bppy_set_thread().
#define CPYCHECKER_NEGATIVE_RESULT_SETS_EXCEPTION
Definition at line 60 of file python-internal.h.
#define CPYCHECKER_RETURNS_BORROWED_REF
Definition at line 33 of file python-internal.h.
#define CPYCHECKER_SETS_EXCEPTION
Definition at line 53 of file python-internal.h.
#define CPYCHECKER_STEALS_REFERENCE_TO_ARG (n)
Definition at line 47 of file python-internal.h.
#define CPYCHECKER_TYPE_OBJECT_FOR_TYPEDEF (ARG)
Definition at line 40 of file python-internal.h.
#define GDB_PY_HANDLE_EXCEPTION (Exception)
Value:
do {                                            \
    if (Exception.reason < 0)                   \
      {                                         \
        gdbpy_convert_exception (Exception);    \
        return NULL;                            \
      }                                         \
  } while (0)
Definition at line 414 of file python-internal.h.
Referenced by bppy_delete_breakpoint(), frapy_arch(), frapy_block(), frapy_find_sal(), frapy_function(), frapy_is_valid(), frapy_name(), frapy_newer(), frapy_older(), frapy_pc(), frapy_read_var(), frapy_select(), frapy_type(), frapy_unwind_stop_reason(), gdbpy_block_for_pc(), gdbpy_lookup_global_symbol(), gdbpy_lookup_symbol(), gdbpy_newest_frame(), gdbpy_selected_frame(), infpy_read_memory(), infpy_search_memory(), infpy_threads(), infpy_write_memory(), stpy_convert_to_value(), sympy_needs_frame(), sympy_value(), thpy_switch(), typy_array_1(), typy_const(), typy_fields_items(), typy_get_composite(), typy_legacy_template_argument(), typy_lookup_type(), typy_lookup_typename(), typy_pointer(), typy_reference(), typy_richcompare(), typy_str(), typy_strip_typedefs(), typy_template_argument(), typy_unqualified(), and typy_volatile().
#define GDB_PY_LL_ARG "L"
Definition at line 162 of file python-internal.h.
#define GDB_PY_LLU_ARG "K"
Definition at line 163 of file python-internal.h.
Referenced by archpy_disassemble(), and gdbpy_block_for_pc().
#define gdb_py_long_as_ulongest PyLong_AsUnsignedLong
Definition at line 168 of file python-internal.h.
Referenced by get_addr_from_python().
#define gdb_py_long_from_longest PyLong_FromLong
Definition at line 166 of file python-internal.h.
Referenced by convert_field(), and typy_get_sizeof().
#define gdb_py_long_from_ulongest PyLong_FromUnsignedLong
Definition at line 167 of file python-internal.h.
Referenced by archpy_disassemble(), frapy_pc(), salpy_get_last(), salpy_get_pc(), and stpy_get_address().
#define GDB_PY_SET_HANDLE_EXCEPTION (Exception)
Value:
do {                                                            \
      if (Exception.reason < 0)                                         \
        {                                                               \
          gdbpy_convert_exception (Exception);                          \
          return -1;                                                    \
        }                                                               \
    } while (0)
Definition at line 425 of file python-internal.h.
Referenced by bpfinishpy_init(), bppy_set_condition(), bppy_set_enabled(), bppy_set_ignore_count(), bppy_set_task(), and get_addr_from_python().
#define Py_DECREF (op) gdb_Py_DECREF (op)
Definition at line 186 of file python-internal.h.
Referenced by apply_frame_filter(), archpy_disassemble(), bootstrap_python_frame_filters(), build_inferior_list(), call_doc_function(), cmdpy_destroyer(), cmdpy_function(), cmdpy_init(), compute_enum_values(), convert_field(), convert_values_to_python(), create_eventregistry_object(), create_exited_event_object(), create_signal_event_object(), del_objfile_sal(), delete_thread_object(), emit_stop_event(), enumerate_args(), evpy_emit_event(), extract_sym(), extract_value(), field_new(), find_thread_object(), fnpy_call(), fnpy_init(), frame_info_to_frame_object(), gdb_Py_DECREF(), gdb_pymodule_addobject(), gdbpy_breakpoint_deleted(), gdbpy_breakpoints(), gdbpy_inferiors(), gdbpy_lookup_symbol(), gdbpy_obj_to_string(), gdbpy_should_stop(), gdbpy_string_to_argv(), get_py_iter_from_func(), get_show_value(), infpy_read_memory(), objfile_to_objfile_object(), objfpy_new(), parmpy_init(), pspace_to_pspace_object(), pspy_new(), py_decref(), py_free_inferior(), py_free_objfile(), py_free_pspace(), py_print_frame(), python_string_to_host_string(), python_string_to_target_python_string(), python_string_to_target_string(), salpy_dealloc(), symtab_and_line_to_sal_object(), thpy_dealloc(), typy_fields(), typy_fields_items(), typy_iterator_dealloc(), typy_range(), unicode_to_encoded_string(), and VEC().
#define PY_SSIZE_T_CLEAN
Definition at line 90 of file python-internal.h.
#define PyEval_InitThreads ()
Definition at line 142 of file python-internal.h.
Referenced by _initialize_python().
#define PyEval_ReleaseLock ()
Definition at line 144 of file python-internal.h.
Referenced by _initialize_python().
#define PyGILState_Ensure () ((PyGILState_STATE) 0)
Definition at line 140 of file python-internal.h.
Referenced by gdbpy_breakpoint_created(), and gdbpy_breakpoint_deleted().
#define PyGILState_Release (ARG) ((void)(ARG))
Definition at line 141 of file python-internal.h.
Referenced by gdbpy_breakpoint_created(), and gdbpy_breakpoint_deleted().
#define PyThreadState_Swap (ARG) ((void)(ARG))
Definition at line 143 of file python-internal.h.
Referenced by _initialize_python().
Typedef Documentation
typedef struct breakpoint_object breakpoint_object
typedef long gdb_py_longest
Definition at line 164 of file python-internal.h.
typedef unsigned long gdb_py_ulongest
Definition at line 165 of file python-internal.h.
Enumeration Type Documentation
enum gdbpy_iter_kind
Enumerator:
iter_keys
iter_values
iter_items
Definition at line 198 of file python-internal.h.
Function Documentation
PyObject* apply_varobj_pretty_printer (PyObject * print_obj, struct value ** replacement, struct ui_file * stream)
Referenced by value_get_print_value().
struct gdbarch* arch_object_to_gdbarch (PyObject * obj) [read]
Definition at line 68 of file py-arch.c.
References arch_object_type_object::gdbarch.
struct block* block_object_to_block (PyObject * obj) [read]
Definition at line 284 of file py-block.c.
References block_object_type.
Referenced by blpy_is_valid(), frapy_read_var(), gdbpy_lookup_symbol(), gdbpy_lookup_type(), and typy_template_argument().
PyObject* block_to_block_object (const struct block * block, struct objfile * objfile)
Definition at line 271 of file py-block.c.
References block_object_type, and set_block().
Referenced by blpy_get_global_block(), blpy_get_static_block(), blpy_get_superblock(), frapy_block(), gdbpy_block_for_pc(), stpy_global_block(), and stpy_static_block().
void bpfinishpy_post_stop_hook (struct breakpoint_object * bp_obj)
Definition at line 136 of file py-finishbreakpoint.c.
References breakpoint_object::bp, disable_breakpoint(), disp_del, breakpoint::disposition, gdb_assert, gdbpy_convert_exception(), gdbpy_print_stack(), gdb_exception::reason, RETURN_MASK_ALL, and TRY_CATCH.
Referenced by gdbpy_should_stop().
void bpfinishpy_pre_stop_hook (struct breakpoint_object * bp_obj)
Definition at line 93 of file py-finishbreakpoint.c.
References finish_breakpoint_object::function_value, gdb_assert, gdbpy_convert_exception(), gdbpy_print_stack(), get_return_value(), gdb_exception::reason, RETURN_MASK_ALL, finish_breakpoint_object::return_type, finish_breakpoint_object::return_value, TRY_CATCH, type_object_to_type(), value_object_to_value(), value_to_value_object(), and value_type().
Referenced by gdbpy_should_stop().
struct value* convert_value_from_python (PyObject * obj) [read]
Referenced by extract_value(), fnpy_call(), and update_dynamic_varobj_children().
PyTypeObject value_object_type CPYCHECKER_TYPE_OBJECT_FOR_TYPEDEF ("value_object")
PyTypeObject block_object_type CPYCHECKER_TYPE_OBJECT_FOR_TYPEDEF ("block_object")
PyTypeObject symbol_object_type CPYCHECKER_TYPE_OBJECT_FOR_TYPEDEF ("symbol_object")
PyTypeObject event_object_type CPYCHECKER_TYPE_OBJECT_FOR_TYPEDEF ("event_object")
PyTypeObject breakpoint_object_type CPYCHECKER_TYPE_OBJECT_FOR_TYPEDEF ("breakpoint_object")
PyTypeObject frame_object_type CPYCHECKER_TYPE_OBJECT_FOR_TYPEDEF ("frame_object")
thread_object* create_thread_object (struct thread_info * tp)
Definition at line 43 of file py-infthread.c.
References find_inferior_object(), thread_object::inf_obj, thread_info::ptid, ptid_get_pid(), thread_object::thread, threadlist_entry::thread_obj, and thread_object_type.
Referenced by add_thread_object().
struct cleanup* ensure_python_env (struct gdbarch * gdbarch, const struct language_defn * language) [read]
Referenced by add_thread_object(), apply_frame_filter(), bpfinishpy_handle_exit(), bpfinishpy_handle_stop(), cmdpy_destroyer(), cmdpy_function(), delete_thread_object(), fnpy_call(), gdbpy_breakpoint_has_py_cond(), gdbpy_should_stop(), get_set_value(), get_show_value(), py_free_inferior(), py_free_objfile(), py_free_pspace(), python_inferior_exit(), python_new_objfile(), python_on_normal_stop(), python_on_resume(), save_objfile_types(), and VEC().
PyObject* find_inferior_object (int pid)
Definition at line 195 of file py-inferior.c.
References find_inferior_pid(), and inferior_to_inferior_object().
Referenced by create_thread_object(), delete_thread_object(), and find_thread_object().
thread_object* find_thread_object (ptid_t ptid)
Definition at line 206 of file py-inferior.c.
References find_inferior_object(), threadlist_entry::next, inferior::pid, thread_info::ptid, ptid_equal(), ptid_get_pid(), Py_DECREF, thread_object::thread, and threadlist_entry::thread_obj.
Referenced by gdbpy_selected_thread(), and get_event_thread().
PyObject* frame_info_to_frame_object (struct frame_info * frame)
Definition at line 307 of file py-frame.c.
References frame_object_type, gdbpy_convert_exception(), get_frame_arch(), get_frame_id(), get_frame_unwind_stop_reason(), get_next_frame(), get_prev_frame(), Py_DECREF, gdb_exception::reason, RETURN_MASK_ALL, and TRY_CATCH.
Referenced by bootstrap_python_frame_filters(), frapy_newer(), frapy_older(), gdbpy_newest_frame(), and gdbpy_selected_frame().
struct frame_info* frame_object_to_frame_info (PyObject * frame_obj) [read]
Definition at line 62 of file py-frame.c.
References frame_find_by_id(), frame_object::frame_id, frame_object::frame_id_is_next, and get_prev_frame().
Referenced by bpfinishpy_init(), frapy_is_valid(), py_print_frame(), and sympy_value().
static void gdb_Py_DECREF (void * op) [inline, static]
Definition at line 177 of file python-internal.h.
References Py_DECREF.
PyObject* gdb_py_generic_dict (PyObject * self, void * closure)
Definition at line 417 of file py-utils.c.
int gdb_py_int_as_long (PyObject * , long *)
Definition at line 404 of file py-utils.c.
Referenced by bppy_set_hit_count(), bppy_set_ignore_count(), bppy_set_task(), bppy_set_thread(), set_parameter_value(), typy_array_1(), and VEC().
PyObject* gdb_py_object_from_longest (LONGEST l)
Definition at line 357 of file py-utils.c.
References LONGEST.
PyObject* gdb_py_object_from_ulongest (ULONGEST l)
Definition at line 379 of file py-utils.c.
Referenced by blpy_get_end(), and blpy_get_start().
int gdb_pymodule_addobject (PyObject * module, const char * name, PyObject * object)
Definition at line 434 of file py-utils.c.
References Py_DECREF.
Referenced by _initialize_python(), add_new_registry(), gdbpy_initialize_arch(), gdbpy_initialize_blocks(), gdbpy_initialize_breakpoints(), gdbpy_initialize_commands(), gdbpy_initialize_event_generic(), gdbpy_initialize_eventregistry(), gdbpy_initialize_finishbreakpoints(), gdbpy_initialize_frames(), gdbpy_initialize_functions(), gdbpy_initialize_inferior(), gdbpy_initialize_objfile(), gdbpy_initialize_parameters(), gdbpy_initialize_pspace(), gdbpy_initialize_py_events(), gdbpy_initialize_symbols(), gdbpy_initialize_symtabs(), gdbpy_initialize_thread(), and gdbpy_initialize_types().
PyObject* gdbarch_to_arch_object (struct gdbarch * gdbarch)
Definition at line 80 of file py-arch.c.
Referenced by frapy_arch().
PyObject* gdbpy_block_for_pc (PyObject * self, PyObject * args)
Definition at line 371 of file py-block.c.
References _, block_for_pc(), block_to_block_object(), find_pc_mapped_section(), find_pc_sect_symtab(), GDB_PY_HANDLE_EXCEPTION, GDB_PY_LLU_ARG, symtab::objfile, RETURN_MASK_ALL, and TRY_CATCH.
PyObject* gdbpy_breakpoints (PyObject * , PyObject *)
Definition at line 694 of file py-breakpoint.c.
References bppy_live, build_bp_list(), iterate_over_breakpoints(), and Py_DECREF.
void gdbpy_convert_exception (struct gdb_exception)
Definition at line 295 of file py-utils.c.
References gdb_exception::error, gdbpy_gdb_error, gdbpy_gdb_memory_error, MEMORY_ERROR, gdb_exception::message, gdb_exception::reason, and RETURN_QUIT.
Referenced by apply_frame_filter(), archpy_disassemble(), bpfinishpy_detect_out_scope_cb(), bpfinishpy_init(), bpfinishpy_post_stop_hook(), bpfinishpy_pre_stop_hook(), bppy_get_commands(), enumerate_args(), enumerate_locals(), frame_info_to_frame_object(), frapy_read_var(), gdbpy_readline_wrapper(), py_print_args(), py_print_frame(), py_print_single_arg(), py_print_type(), and py_print_value().
PyObject* gdbpy_create_lazy_string_object (CORE_ADDR address, long length, const char * encoding, struct type * type)
Definition at line 128 of file py-lazy-string.c.
References _, lazy_string_object::address, lazy_string_object::encoding, lazy_string_object_type, lazy_string_object::length, lazy_string_object::type, and type.
PyObject* gdbpy_default_visualizer (PyObject * self, PyObject * args)
char* gdbpy_exception_to_string (PyObject * ptype, PyObject * pvalue)
Definition at line 268 of file py-utils.c.
References gdbpy_obj_to_string().
Referenced by cmdpy_function(), fnpy_call(), and update_dynamic_varobj_children().
void gdbpy_extract_lazy_string (PyObject * string, CORE_ADDR * addr, struct type ** str_type, long * length, char ** encoding)
Definition at line 187 of file py-lazy-string.c.
References lazy_string_object::address, lazy_string_object::encoding, gdb_assert, gdbpy_is_lazy_string(), lazy_string_object::length, and lazy_string_object::type.
Referenced by value_get_print_value().
PyObject* gdbpy_frame_stop_reason_string (PyObject * , PyObject *)
Definition at line 576 of file py-frame.c.
References _, frame_stop_reason_string(), host_charset(), and gdb_exception::reason.
char* gdbpy_get_display_hint (PyObject * printer)
Referenced by value_get_print_value(), and varobj_get_display_hint().
PyObject* gdbpy_get_varobj_pretty_printer (struct value * value)
PyObject* gdbpy_history (PyObject * self, PyObject * args)
PyObject* gdbpy_inferiors (PyObject * unused, PyObject * unused2)
Definition at line 399 of file py-inferior.c.
References build_inferior_list(), iterate_over_inferiors(), and Py_DECREF.
int gdbpy_initialize_arch (void)
Definition at line 261 of file py-arch.c.
References arch_object_data_init(), arch_object_type, gdb_module, gdb_pymodule_addobject(), and gdbarch_data_register_post_init().
Referenced by _initialize_python().
int gdbpy_initialize_auto_load (void)
Referenced by _initialize_python().
int gdbpy_initialize_blocks (void)
Definition at line 429 of file py-block.c.
References block_object_type, block_syms_iterator_object_type, blpy_objfile_data_key, del_objfile_blocks(), gdb_module, and gdb_pymodule_addobject().
Referenced by _initialize_python().
int gdbpy_initialize_breakpoint_event (void)
Referenced by _initialize_python().
int gdbpy_initialize_breakpoints (void)
Definition at line 868 of file py-breakpoint.c.
References breakpoint_object_type, code, gdb_module, gdb_pymodule_addobject(), gdbpy_breakpoint_created(), gdbpy_breakpoint_deleted(), pybp_code::name, name, observer_attach_breakpoint_created(), and observer_attach_breakpoint_deleted().
Referenced by _initialize_python().
int gdbpy_initialize_commands (void)
Definition at line 568 of file py-cmd.c.
References class_breakpoint, class_files, class_info, class_maintenance, class_obscure, class_run, class_stack, class_support, class_trace, class_user, class_vars, cmdpy_object_type, complete_cst, gdb_module, gdb_pymodule_addobject(), invoke_cst, N_COMPLETERS, name, and no_class.
Referenced by _initialize_python().
int gdbpy_initialize_continue_event (void)
Referenced by _initialize_python().
int gdbpy_initialize_event (void)
Definition at line 64 of file py-event.c.
References event_object_type, and gdbpy_initialize_event_generic().
Referenced by _initialize_python().
int gdbpy_initialize_eventregistry (void)
Definition at line 110 of file py-evtregistry.c.
References eventregistry_object_type, gdb_module, and gdb_pymodule_addobject().
Referenced by _initialize_python().
int gdbpy_initialize_exited_event (void)
Referenced by _initialize_python().
int gdbpy_initialize_finishbreakpoints (void)
Definition at line 411 of file py-finishbreakpoint.c.
References bpfinishpy_handle_exit(), bpfinishpy_handle_stop(), finish_breakpoint_object_type, gdb_module, gdb_pymodule_addobject(), observer_attach_inferior_exit(), and observer_attach_normal_stop().
Referenced by _initialize_python().
int gdbpy_initialize_frames (void)
Definition at line 625 of file py-frame.c.
References ARCH_FRAME, DUMMY_FRAME, frame_object_type, gdb_module, gdb_pymodule_addobject(), INLINE_FRAME, NORMAL_FRAME, SENTINEL_FRAME, SIGTRAMP_FRAME, and TAILCALL_FRAME.
Referenced by _initialize_python().
int gdbpy_initialize_functions (void)
Definition at line 204 of file py-function.c.
References fnpy_object_type, gdb_module, and gdb_pymodule_addobject().
Referenced by _initialize_python().
void gdbpy_initialize_gdb_readline (void)
Definition at line 88 of file py-gdb-readline.c.
References gdbpy_readline_wrapper().
Referenced by _initialize_python().
int gdbpy_initialize_inferior (void)
Definition at line 781 of file py-inferior.c.
References add_thread_object(), delete_thread_object(), gdb_module, gdb_pymodule_addobject(), inferior_object_type, infpy_inf_data_key, membuf_object_type, observer_attach_inferior_exit(), observer_attach_new_objfile(), observer_attach_new_thread(), observer_attach_normal_stop(), observer_attach_target_resumed(), observer_attach_thread_exit(), py_free_inferior(), python_inferior_exit(), python_new_objfile(), python_on_normal_stop(), and python_on_resume().
Referenced by _initialize_python().
int gdbpy_initialize_lazy_string (void)
Definition at line 164 of file py-lazy-string.c.
References lazy_string_object_type.
Referenced by _initialize_python().
int gdbpy_initialize_new_objfile_event (void)
Referenced by _initialize_python().
int gdbpy_initialize_objfile (void)
Definition at line 303 of file py-objfile.c.
References gdb_module, gdb_pymodule_addobject(), objfile_object_type, objfpy_objfile_data_key, and py_free_objfile().
Referenced by _initialize_python().
int gdbpy_initialize_parameters (void)
Definition at line 754 of file py-param.c.
References gdb_module, gdb_pymodule_addobject(), parm_constant::name, name, parmpy_object_type, set_doc_cst, and show_doc_cst.
Referenced by _initialize_python().
int gdbpy_initialize_pspace (void)
Definition at line 299 of file py-progspace.c.
References gdb_module, gdb_pymodule_addobject(), pspace_object_type, pspy_pspace_data_key, and py_free_pspace().
Referenced by _initialize_python().
int gdbpy_initialize_py_events (void)
Definition at line 56 of file py-evts.c.
References add_new_registry(), events_object::cont, events_object::exited, gdb_module, gdb_py_events, gdb_pymodule_addobject(), events_object::module, events_object::new_objfile, and events_object::stop.
Referenced by _initialize_python().
int gdbpy_initialize_signal_event (void)
Referenced by _initialize_python().
int gdbpy_initialize_stop_event (void)
Referenced by _initialize_python().
int gdbpy_initialize_symbols (void)
Definition at line 478 of file py-symbol.c.
References del_objfile_symbols(), FUNCTIONS_DOMAIN, gdb_module, gdb_pymodule_addobject(), LABEL_DOMAIN, LOC_ARG, LOC_BLOCK, LOC_COMPUTED, LOC_CONST, LOC_CONST_BYTES, LOC_LABEL, LOC_LOCAL, LOC_OPTIMIZED_OUT, LOC_REF_ARG, LOC_REGISTER, LOC_REGPARM_ADDR, LOC_STATIC, LOC_TYPEDEF, LOC_UNDEF, LOC_UNRESOLVED, STRUCT_DOMAIN, symbol_object_type, sympy_objfile_data_key, TYPES_DOMAIN, UNDEF_DOMAIN, VAR_DOMAIN, and VARIABLES_DOMAIN.
Referenced by _initialize_python().
int gdbpy_initialize_symtabs (void)
Definition at line 485 of file py-symtab.c.
References del_objfile_sal(), del_objfile_symtab(), gdb_module, gdb_pymodule_addobject(), sal_object_type, salpy_objfile_data_key, stpy_objfile_data_key, and symtab_object_type.
Referenced by _initialize_python().
int gdbpy_initialize_thread (void)
Definition at line 259 of file py-infthread.c.
References gdb_module, gdb_pymodule_addobject(), and thread_object_type.
Referenced by _initialize_python().
int gdbpy_initialize_thread_event (void)
Referenced by _initialize_python().
int gdbpy_initialize_types (void)
Definition at line 1525 of file py-type.c.
References code, field_object_type, gdb_module, gdb_pymodule_addobject(), name, pyty_code::name, save_objfile_types(), type_iterator_object_type, and type_object_type.
Referenced by _initialize_python().
int gdbpy_initialize_values (void)
Referenced by _initialize_python().
int gdbpy_is_lazy_string (PyObject * result)
Definition at line 176 of file py-lazy-string.c.
References lazy_string_object_type.
Referenced by gdbpy_extract_lazy_string(), and value_get_print_value().
int gdbpy_is_string (PyObject * obj)
Definition at line 228 of file py-utils.c.
Referenced by call_doc_function(), cmdpy_init(), compute_enum_values(), extract_sym(), fnpy_init(), frapy_read_var(), get_doc_string(), py_print_frame(), set_parameter_value(), thpy_set_name(), and VEC().
int gdbpy_is_value_object (PyObject * obj)
Referenced by get_addr_from_python().
PyObject* gdbpy_lookup_global_symbol (PyObject * self, PyObject * args, PyObject * kw)
Definition at line 422 of file py-symbol.c.
References GDB_PY_HANDLE_EXCEPTION, lookup_symbol_global(), name, RETURN_MASK_ALL, symbol_to_symbol_object(), TRY_CATCH, and VAR_DOMAIN.
PyObject* gdbpy_lookup_symbol (PyObject * self, PyObject * args, PyObject * kw)
Definition at line 355 of file py-symbol.c.
References _, block_object_to_block(), block_object_type, GDB_PY_HANDLE_EXCEPTION, get_frame_block(), get_selected_frame(), lookup_symbol(), name, Py_DECREF, RETURN_MASK_ALL, selected_frame, symbol_to_symbol_object(), TRY_CATCH, field_of_this_result::type, and VAR_DOMAIN.
PyObject* gdbpy_lookup_type (PyObject * self, PyObject * args, PyObject * kw)
Definition at line 1494 of file py-type.c.
References _, block_object_to_block(), type_to_type_object(), and typy_lookup_typename().
PyObject* gdbpy_newest_frame (PyObject * self, PyObject * args)
Definition at line 540 of file py-frame.c.
References frame_info_to_frame_object(), GDB_PY_HANDLE_EXCEPTION, get_current_frame(), RETURN_MASK_ALL, and TRY_CATCH.
char* gdbpy_obj_to_string (PyObject * obj)
Definition at line 242 of file py-utils.c.
References Py_DECREF, and python_string_to_host_string().
Referenced by gdbpy_exception_to_string().
PyObject* gdbpy_parameter (PyObject * self, PyObject * args)
PyObject* gdbpy_parameter_value (enum var_types type, void * var)
Referenced by get_attr().
char* gdbpy_parse_command_name (const char * name, struct cmd_list_element *** base_list, struct cmd_list_element ** start_list)
Definition at line 324 of file py-cmd.c.
References _, len, lookup_cmd_1(), memcpy(), cmd_list_element::prefixlist, xfree(), and xmalloc().
Referenced by cmdpy_init(), and parmpy_init().
void gdbpy_print_stack (void)
Referenced by _initialize_python(), add_thread_object(), apply_frame_filter(), bpfinishpy_detect_out_scope_cb(), bpfinishpy_out_of_scope(), bpfinishpy_post_stop_hook(), bpfinishpy_pre_stop_hook(), cmdpy_function(), evpy_emit_event(), fnpy_call(), gdbpy_breakpoint_created(), gdbpy_should_stop(), get_doc_string(), get_set_value(), get_show_value(), python_inferior_exit(), python_new_objfile(), python_on_normal_stop(), python_on_resume(), update_dynamic_varobj_children(), value_get_print_value(), and varobj_set_visualizer().
PyObject* gdbpy_selected_frame (PyObject * self, PyObject * args)
Definition at line 558 of file py-frame.c.
References frame_info_to_frame_object(), GDB_PY_HANDLE_EXCEPTION, get_selected_frame(), RETURN_MASK_ALL, and TRY_CATCH.
PyObject* gdbpy_selected_inferior (PyObject * self, PyObject * args)
Definition at line 775 of file py-inferior.c.
References current_inferior(), and inferior_to_inferior_object().
PyObject* gdbpy_selected_thread (PyObject * self, PyObject * args)
Definition at line 242 of file py-infthread.c.
References find_thread_object(), and inferior_ptid.
PyObject* gdbpy_string_to_argv (PyObject * self, PyObject * args)
Definition at line 678 of file py-cmd.c.
References gdb_buildargv(), and Py_DECREF.
int get_addr_from_python (PyObject * obj, CORE_ADDR * addr)
Definition at line 315 of file py-utils.c.
References _, gdb_py_long_as_ulongest, GDB_PY_SET_HANDLE_EXCEPTION, gdbpy_is_value_object(), RETURN_MASK_ALL, TRY_CATCH, value_as_address(), and value_object_to_value().
Referenced by infpy_read_memory(), infpy_search_memory(), and infpy_write_memory().
PyObject* inferior_to_inferior_object (struct inferior * inferior)
Definition at line 167 of file py-inferior.c.
References inferior_object::inferior, inferior_object_type, infpy_inf_data_key, inferior_object::nthreads, and inferior_object::threads.
Referenced by build_inferior_list(), create_exited_event_object(), find_inferior_object(), and gdbpy_selected_inferior().
struct cleanup* make_cleanup_py_decref (PyObject * py) [read]
Definition at line 41 of file py-utils.c.
References make_cleanup(), and py_decref().
Referenced by apply_frame_filter(), bootstrap_python_frame_filters(), enumerate_locals(), py_mi_print_variables(), py_print_frame(), update_dynamic_varobj_children(), value_get_print_value(), and varobj_set_visualizer().
struct cleanup* make_cleanup_py_xdecref (PyObject * py) [read]
Definition at line 63 of file py-utils.c.
References make_cleanup(), and py_xdecref().
Referenced by py_mi_print_variables(), py_print_args(), and py_print_locals().
PyObject* objfile_to_objfile_object (struct objfile *)
Definition at line 262 of file py-objfile.c.
References objfile_object::frame_filters, objfile_object_type, objfpy_objfile_data_key, objfile_object::printers, Py_DECREF, and objfile_object::type_printers.
Referenced by create_new_objfile_event_object(), and stpy_get_objfile().
PyObject* objfpy_get_frame_filters (PyObject * , void *)
Definition at line 147 of file py-objfile.c.
PyObject* objfpy_get_printers (PyObject * , void *)
Definition at line 107 of file py-objfile.c.
PyObject* pspace_to_pspace_object (struct program_space *)
Definition at line 258 of file py-progspace.c.
References pspace_object::frame_filters, pspace_object::printers, pspace_object_type, pspy_pspace_data_key, Py_DECREF, and pspace_object::type_printers.
PyObject* pspy_get_frame_filters (PyObject * , void *)
Definition at line 155 of file py-progspace.c.
PyObject* pspy_get_printers (PyObject * , void *)
Definition at line 115 of file py-progspace.c.
char* python_string_to_host_string (PyObject * obj)
Definition at line 210 of file py-utils.c.
References host_charset(), Py_DECREF, python_string_to_unicode(), and unicode_to_encoded_string().
Referenced by bppy_set_condition(), call_doc_function(), cmdpy_init(), compute_enum_values(), extract_sym(), fnpy_init(), gdbpy_obj_to_string(), get_doc_string(), local_setattro(), py_print_frame(), set_parameter_value(), thpy_set_name(), typy_getitem(), and VEC().
PyObject* python_string_to_target_python_string (PyObject * obj)
Definition at line 191 of file py-utils.c.
References Py_DECREF, python_string_to_unicode(), and unicode_to_target_python_string().
char* python_string_to_target_string (PyObject * obj)
Definition at line 171 of file py-utils.c.
References Py_DECREF, python_string_to_unicode(), and unicode_to_target_string().
Referenced by frapy_read_var(), and value_get_print_value().
PyObject* python_string_to_unicode (PyObject * obj)
Definition at line 80 of file py-utils.c.
References _, and host_charset().
Referenced by python_string_to_host_string(), python_string_to_target_python_string(), and python_string_to_target_string().
struct symtab_and_line* sal_object_to_symtab_and_line (PyObject * obj) [read]
Definition at line 420 of file py-symtab.c.
References sal_object_type.
Referenced by salpy_is_valid().
void source_python_script_for_objfile (struct objfile * objfile, FILE * file, const char * filename)
struct symbol* symbol_object_to_symbol (PyObject * obj) [read]
Definition at line 324 of file py-symbol.c.
References symbol_object_type.
Referenced by extract_sym(), frapy_read_var(), and sympy_is_valid().
PyObject* symbol_to_symbol_object (struct symbol * sym)
Definition at line 311 of file py-symbol.c.
References set_symbol(), and symbol_object_type.
Referenced by blpy_block_syms_iternext(), blpy_get_function(), frapy_function(), gdbpy_lookup_global_symbol(), and gdbpy_lookup_symbol().
PyObject* symtab_and_line_to_sal_object (struct symtab_and_line sal)
Definition at line 399 of file py-symtab.c.
References Py_DECREF, sal_object_type, and set_sal().
Referenced by frapy_find_sal().
struct symtab* symtab_object_to_symtab (PyObject * obj) [read]
Definition at line 429 of file py-symtab.c.
References symtab_object_type.
Referenced by stpy_is_valid().
PyObject* symtab_to_symtab_object (struct symtab * symtab)
Definition at line 385 of file py-symtab.c.
References set_symtab(), and symtab_object_type.
Referenced by set_sal(), and sympy_get_symtab().
struct type* type_object_to_type (PyObject * obj) [read]
Definition at line 1483 of file py-type.c.
References type_object_type.
Referenced by bpfinishpy_pre_stop_hook(), typy_richcompare(), and typy_str().
PyObject* type_to_type_object (struct type *)
Definition at line 1471 of file py-type.c.
References set_type(), and type_object_type.
Referenced by bpfinishpy_init(), convert_field(), gdbpy_lookup_type(), stpy_get_type(), sympy_get_type(), typy_array_1(), typy_const(), typy_fields_items(), typy_legacy_template_argument(), typy_pointer(), typy_reference(), typy_strip_typedefs(), typy_target(), typy_template_argument(), typy_unqualified(), and typy_volatile().
char* unicode_to_target_string (PyObject * unicode_str)
Definition at line 149 of file py-utils.c.
References python_gdbarch, target_charset(), and unicode_to_encoded_string().
Referenced by python_string_to_target_string().
struct value* value_object_to_value (PyObject * self) [read]
Referenced by bpfinishpy_pre_stop_hook(), and get_addr_from_python().
PyObject* value_to_value_object (struct value * v)
Referenced by bpfinishpy_init(), bpfinishpy_pre_stop_hook(), convert_values_to_python(), frapy_read_var(), stpy_convert_to_value(), sympy_value(), and typy_template_argument().
Variable Documentation
breakpoint_object* bppy_pending_object
Definition at line 40 of file py-breakpoint.c.
Referenced by bpfinishpy_init(), and gdbpy_breakpoint_created().
PyObject* gdb_module
Referenced by _initialize_python(), gdbpy_initialize_arch(), gdbpy_initialize_blocks(), gdbpy_initialize_breakpoints(), gdbpy_initialize_commands(), gdbpy_initialize_event_generic(), gdbpy_initialize_eventregistry(), gdbpy_initialize_finishbreakpoints(), gdbpy_initialize_frames(), gdbpy_initialize_functions(), gdbpy_initialize_inferior(), gdbpy_initialize_objfile(), gdbpy_initialize_parameters(), gdbpy_initialize_pspace(), gdbpy_initialize_py_events(), gdbpy_initialize_symbols(), gdbpy_initialize_symtabs(), gdbpy_initialize_thread(), and gdbpy_initialize_types().
int gdb_python_initialized
Referenced by _initialize_python(), add_thread_object(), apply_frame_filter(), delete_thread_object(), install_new_value_visualizer(), mi_cmd_list_features(), py_free_inferior(), python_inferior_exit(), python_new_objfile(), python_on_normal_stop(), python_on_resume(), save_objfile_types(), update_dynamic_varobj_children(), value_get_print_value(), varobj_get_display_hint(), and varobj_set_visualizer().
PyObject* gdb_python_module
PyObject* gdbpy_children_cst
Referenced by _initialize_python(), and update_dynamic_varobj_children().
PyObject* gdbpy_display_hint_cst
Referenced by _initialize_python().
PyObject* gdbpy_doc_cst
Referenced by _initialize_python(), cmdpy_init(), and parmpy_init().
PyObject* gdbpy_enabled_cst
Referenced by _initialize_python().
PyObject* gdbpy_gdb_error
Referenced by _initialize_python(), and gdbpy_convert_exception().
PyObject* gdbpy_gdb_memory_error
Referenced by _initialize_python(), gdbpy_convert_exception(), and update_dynamic_varobj_children().
PyObject* gdbpy_gdberror_exc
Referenced by _initialize_python(), cmdpy_function(), and fnpy_call().
PyObject* gdbpy_to_string_cst
Referenced by _initialize_python(), and value_get_print_value().
PyObject* gdbpy_value_cst
Referenced by _initialize_python().
struct gdbarch* python_gdbarch
Referenced by add_thread_object(), bpfinishpy_init(), bppy_init(), delete_thread_object(), mbpy_str(), py_free_inferior(), typy_lookup_typename(), unicode_to_target_python_string(), and unicode_to_target_string().
struct language_defn* python_language
Referenced by add_thread_object(), delete_thread_object(), extract_sym(), py_free_inferior(), and typy_lookup_typename().
struct cmd_list_element* set_python_list
struct cmd_list_element* show_python_list