GDB (xrefs): /home/stan/gdb/src/gdb/record-full.h File Reference
/home/stan/gdb/src/gdb/record-full.h File Reference
Functions
int record_full_arch_list_add_reg (struct regcache *regcache, int num)
int record_full_arch_list_add_mem (CORE_ADDR addr, int len)
int record_full_arch_list_add_end (void)
struct cleanup * record_full_gdb_operation_disable_set (void)
Variables
int record_full_memory_query
Function Documentation
int record_full_arch_list_add_end (void)
Definition at line 540 of file record-full.c.
References record_full_entry::end, fprintf_unfiltered(), gdb_stdlog, record_full_end_entry::insn_num, record_debug, record_full_arch_list_add(), record_full_end_alloc(), record_full_insn_count, record_full_end_entry::sigval, and record_full_entry::u.
Referenced by amd64_linux_record_signal(), arm_process_record(), i386_linux_record_signal(), i386_process_record(), moxie_process_record(), record_full_registers_change(), and record_full_xfer_partial().
int record_full_arch_list_add_mem (CORE_ADDR addr, int len)
Definition at line 509 of file record-full.c.
References fprintf_unfiltered(), gdb_stdlog, paddress(), record_debug, record_full_arch_list_add(), record_full_get_loc(), record_full_mem_alloc(), record_full_mem_release(), record_read_memory(), and target_gdbarch().
Referenced by amd64_linux_record_signal(), amd64_linux_syscall_record(), arm_process_record(), i386_linux_record_signal(), i386_process_record(), i386_record_lea_modrm(), i386_record_push(), moxie_process_record(), record_full_xfer_partial(), record_linux_msghdr(), record_linux_sockaddr(), and record_linux_system_call().
int record_full_arch_list_add_reg (struct regcache * regcache, int num)
Definition at line 486 of file record-full.c.
References fprintf_unfiltered(), gdb_stdlog, record_debug, record_full_arch_list_add(), record_full_get_loc(), record_full_reg_alloc(), and regcache_raw_read().
Referenced by amd64_all_but_ip_registers_record(), amd64_linux_record_signal(), amd64_linux_syscall_record(), arm_process_record(), i386_all_but_ip_registers_record(), i386_linux_intx80_sysenter_syscall_record(), i386_linux_record_signal(), i386_process_record(), i386_record_floats(), i386_record_push(), moxie_process_record(), and record_full_registers_change().
struct cleanup* record_full_gdb_operation_disable_set (void) [read]
Definition at line 699 of file record-full.c.
References make_cleanup_restore_integer().
Referenced by adjust_pc_after_break(), record_full_goto_insn(), record_full_insert_breakpoint(), record_full_remove_breakpoint(), record_full_save(), and record_full_wait_1().
Variable Documentation
int record_full_memory_query
Definition at line 159 of file record-full.c.
Referenced by _initialize_record_full(), i386_process_record(), i386_record_lea_modrm(), and record_linux_system_call().