GDB (xrefs): /home/stan/gdb/src/gdb/record.h File Reference
/home/stan/gdb/src/gdb/record.h File Reference
Defines
#define RECORD_IS_USED (current_target.to_stratum == record_stratum)
Enumerations
enum record_print_flag { RECORD_PRINT_SRC_LINE = (1 << 0), RECORD_PRINT_INSN_RANGE = (1 << 1) }
Functions
int record_read_memory (struct gdbarch *gdbarch, CORE_ADDR memaddr, gdb_byte *myaddr, ssize_t len)
void cmd_record_goto (char *arg, int from_tty)
void record_disconnect (struct target_ops *, char *, int)
void record_detach (struct target_ops *, char *, int)
void record_mourn_inferior (struct target_ops *)
void record_kill (struct target_ops *)
Variables
unsigned int record_debug
struct cmd_list_element * record_cmdlist
struct cmd_list_element * set_record_cmdlist
struct cmd_list_element * show_record_cmdlist
struct cmd_list_element * info_record_cmdlist
Define Documentation
#define RECORD_IS_USED (current_target.to_stratum == record_stratum)
Definition at line 25 of file record.h.
Referenced by adjust_pc_after_break(), record_btrace_open(), and use_displaced_stepping().
Enumeration Type Documentation
enum record_print_flag
Enumerator:
RECORD_PRINT_SRC_LINE
RECORD_PRINT_INSN_RANGE
Definition at line 36 of file record.h.
Function Documentation
void cmd_record_goto (char * arg, int from_tty)
Definition at line 316 of file record.c.
References _, error(), parse_and_eval_long(), require_record_target(), target_goto_record(), and ULONGEST.
Referenced by _initialize_record(), and record_full_goto_bookmark().
void record_detach (struct target_ops * , char * , int)
Definition at line 144 of file record.c.
References DEBUG, gdb_assert, record_stop(), record_stratum, record_unpush(), target_detach(), target_ops::to_shortname, and target_ops::to_stratum.
Referenced by init_record_btrace_ops(), and init_record_full_ops().
void record_disconnect (struct target_ops * , char * , int)
Definition at line 129 of file record.c.
References DEBUG, gdb_assert, record_stop(), record_stratum, record_unpush(), target_disconnect(), target_ops::to_shortname, and target_ops::to_stratum.
Referenced by init_record_btrace_ops(), and init_record_full_ops().
void record_kill (struct target_ops *)
Definition at line 175 of file record.c.
References DEBUG, gdb_assert, record_stratum, record_unpush(), target_kill(), target_ops::to_shortname, and target_ops::to_stratum.
Referenced by init_record_btrace_ops(), and init_record_full_ops().
void record_mourn_inferior (struct target_ops *)
Definition at line 159 of file record.c.
References DEBUG, gdb_assert, record_stratum, record_unpush(), target_mourn_inferior(), target_ops::to_shortname, and target_ops::to_stratum.
Referenced by init_record_btrace_ops(), and init_record_full_ops().
int record_read_memory (struct gdbarch * gdbarch, CORE_ADDR memaddr, gdb_byte * myaddr, ssize_t len)
Definition at line 92 of file record.c.
References DEBUG, paddress(), and target_read_memory().
Referenced by i386_process_record(), i386_record_lea_modrm_addr(), i386_record_modrm(), record_full_arch_list_add_mem(), and record_full_exec_insn().
Variable Documentation
struct cmd_list_element* info_record_cmdlist
Definition at line 54 of file record.c.
struct cmd_list_element* record_cmdlist
Definition at line 50 of file record.c.
Referenced by _initialize_record_full().
unsigned int record_debug
Definition at line 33 of file record.c.
Referenced by _initialize_record(), arm_process_record(), decode_insn(), i386_process_record(), moxie_process_readu(), moxie_process_record(), record_full_arch_list_add(), record_full_arch_list_add_end(), record_full_arch_list_add_mem(), record_full_arch_list_add_reg(), record_full_close(), record_full_core_kill(), record_full_exec_insn(), record_full_get_bookmark(), record_full_goto_bookmark(), record_full_open(), record_full_open_1(), record_full_restore(), record_full_save(), record_full_sig_handler(), record_full_wait_1(), record_full_xfer_partial(), record_linux_msghdr(), record_linux_sockaddr(), and record_linux_system_call().
struct cmd_list_element* set_record_cmdlist
Definition at line 52 of file record.c.
Referenced by _initialize_record_full().
struct cmd_list_element* show_record_cmdlist
Definition at line 53 of file record.c.
Referenced by _initialize_record_full().