GDB (xrefs): /home/stan/gdb/src/gdb/record-btrace.c File Reference
/home/stan/gdb/src/gdb/record-btrace.c File Reference
#include "defs.h"
#include "record.h"
#include "gdbthread.h"
#include "target.h"
#include "gdbcmd.h"
#include "disasm.h"
#include "observer.h"
#include "exceptions.h"
#include "cli/cli-utils.h"
#include "source.h"
#include "ui-out.h"
#include "symtab.h"
#include "filenames.h"
Defines
#define DEBUG(msg, args...)
Functions
static struct btrace_thread_info * require_btrace (void)
static void record_btrace_enable_warn (struct thread_info *tp)
static void record_btrace_disable_callback (void *arg)
static void record_btrace_auto_enable (void)
static void record_btrace_auto_disable (void)
static void record_btrace_open (char *args, int from_tty)
static void record_btrace_stop_recording (void)
static void record_btrace_close (void)
static void record_btrace_info (void)
static void ui_out_field_uint (struct ui_out *uiout, const char *fld, unsigned int val)
static void btrace_insn_history (struct btrace_thread_info *btinfo, struct ui_out *uiout, unsigned int begin, unsigned int end, int flags)
static void record_btrace_insn_history (int size, int flags)
static void record_btrace_insn_history_range (ULONGEST from, ULONGEST to, int flags)
static void record_btrace_insn_history_from (ULONGEST from, int size, int flags)
static void btrace_func_history_insn_range (struct ui_out *uiout, struct btrace_func *bfun)
static void btrace_func_history_src_line (struct ui_out *uiout, struct btrace_func *bfun)
static void btrace_func_history (struct btrace_thread_info *btinfo, struct ui_out *uiout, unsigned int begin, unsigned int end, enum record_print_flag flags)
static void record_btrace_call_history (int size, int flags)
static void record_btrace_call_history_range (ULONGEST from, ULONGEST to, int flags)
static void record_btrace_call_history_from (ULONGEST from, int size, int flags)
static void init_record_btrace_ops (void)
static void cmd_record_btrace_start (char *args, int from_tty)
void _initialize_record_btrace (void)
Variables
static struct target_ops record_btrace_ops
static struct observer * record_btrace_thread_observer
Define Documentation
#define DEBUG (msg, args...)
Value:
do                                                                      \
    {                                                                   \
      if (record_debug != 0)                                            \
        fprintf_unfiltered (gdb_stdlog,                                 \
                            "[record-btrace] " msg "\n", ##args);       \
    }                                                                   \
  while (0)
Definition at line 45 of file record-btrace.c.
Referenced by btrace_func_history(), btrace_insn_history(), record_btrace_auto_disable(), record_btrace_auto_enable(), record_btrace_call_history(), record_btrace_call_history_range(), record_btrace_info(), record_btrace_insn_history(), record_btrace_insn_history_range(), record_btrace_open(), record_btrace_stop_recording(), and require_btrace().
Function Documentation
void _initialize_record_btrace (void)
static void btrace_func_history (struct btrace_thread_info * btinfo, struct ui_out * uiout, unsigned int begin, unsigned int end, enum record_print_flag flags) [static]
Definition at line 456 of file record-btrace.c.
References btrace_func_history_insn_range(), btrace_func_history_src_line(), DEBUG, btrace_func::msym, RECORD_PRINT_INSN_RANGE, RECORD_PRINT_SRC_LINE, btrace_func::sym, SYMBOL_PRINT_NAME, ui_out_field_string(), ui_out_field_uint(), ui_out_text(), and VEC_iterate.
Referenced by record_btrace_call_history(), and record_btrace_call_history_range().
static void btrace_func_history_insn_range (struct ui_out * uiout, struct btrace_func * bfun) [static]
Definition at line 415 of file record-btrace.c.
References btrace_func::ibegin, btrace_func::iend, ui_out_field_uint(), and ui_out_text().
Referenced by btrace_func_history().
static void btrace_func_history_src_line (struct ui_out * uiout, struct btrace_func * bfun) [static]
Definition at line 429 of file record-btrace.c.
References btrace_func::lbegin, btrace_func::lend, btrace_func::sym, symbol::symtab, symtab_to_filename_for_display(), ui_out_field_int(), ui_out_field_string(), and ui_out_text().
Referenced by btrace_func_history().
static void btrace_insn_history (struct btrace_thread_info * btinfo, struct ui_out * uiout, unsigned int begin, unsigned int end, int flags) [static]
Definition at line 239 of file record-btrace.c.
References DEBUG, gdb_disassembly(), btrace_inst::pc, target_gdbarch(), ui_out_field_uint(), ui_out_text(), and VEC_iterate.
Referenced by record_btrace_insn_history(), and record_btrace_insn_history_range().
static void cmd_record_btrace_start (char * args, int from_tty) [static]
Definition at line 674 of file record-btrace.c.
References _, error(), and execute_command().
static void init_record_btrace_ops (void) [static]
Definition at line 644 of file record-btrace.c.
References find_default_create_inferior(), OPS_MAGIC, record_btrace_call_history(), record_btrace_call_history_from(), record_btrace_call_history_range(), record_btrace_close(), record_btrace_info(), record_btrace_insn_history(), record_btrace_insn_history_from(), record_btrace_insn_history_range(), record_btrace_open(), record_btrace_ops, record_btrace_stop_recording(), record_detach(), record_disconnect(), record_kill(), record_mourn_inferior(), record_stratum, target_ops::to_call_history, target_ops::to_call_history_from, target_ops::to_call_history_range, target_ops::to_close, target_ops::to_create_inferior, target_ops::to_detach, target_ops::to_disconnect, target_ops::to_doc, target_ops::to_info_record, target_ops::to_insn_history, target_ops::to_insn_history_from, target_ops::to_insn_history_range, target_ops::to_kill, target_ops::to_longname, target_ops::to_magic, target_ops::to_mourn_inferior, target_ops::to_open, target_ops::to_shortname, target_ops::to_stop_recording, and target_ops::to_stratum.
static void record_btrace_auto_disable (void) [static]
Definition at line 123 of file record-btrace.c.
References DEBUG, and observer_detach_new_thread().
Referenced by record_btrace_close(), and record_btrace_stop_recording().
static void record_btrace_auto_enable (void) [static]
Definition at line 112 of file record-btrace.c.
References DEBUG, observer_attach_new_thread(), and record_btrace_enable_warn().
Referenced by record_btrace_open().
static void record_btrace_call_history (int size, int flags) [static]
Definition at line 495 of file record-btrace.c.
References _, btrace_func_iterator::begin, btrace_func_history(), current_uiout, DEBUG, do_cleanups(), btrace_func_iterator::end, error(), btrace_thread_info::func_iterator, make_cleanup_ui_out_tuple_begin_end(), min, printf_unfiltered(), require_btrace(), and VEC_length.
Referenced by init_record_btrace_ops().
static void record_btrace_call_history_from (ULONGEST from, int size, int flags) [static]
Definition at line 613 of file record-btrace.c.
References from, record_btrace_call_history_range(), and ULONGEST.
Referenced by init_record_btrace_ops().
static void record_btrace_call_history_range (ULONGEST from, ULONGEST to, int flags) [static]
Definition at line 570 of file record-btrace.c.
References _, btrace_func_iterator::begin, btrace_func_history(), current_uiout, DEBUG, do_cleanups(), btrace_func_iterator::end, error(), btrace_thread_info::func_iterator, int, make_cleanup_ui_out_tuple_begin_end(), require_btrace(), and VEC_length.
Referenced by init_record_btrace_ops(), and record_btrace_call_history_from().
static void record_btrace_close (void) [static]
Definition at line 193 of file record-btrace.c.
References record_btrace_auto_disable().
Referenced by init_record_btrace_ops().
static void record_btrace_disable_callback (void * arg) [static]
Definition at line 100 of file record-btrace.c.
References btrace_disable().
Referenced by record_btrace_open().
static void record_btrace_enable_warn (struct thread_info * tp) [static]
Definition at line 86 of file record-btrace.c.
References btrace_enable(), gdb_exception::message, RETURN_MASK_ERROR, TRY_CATCH, and warning().
Referenced by record_btrace_auto_enable().
static void record_btrace_info (void) [static]
Definition at line 205 of file record-btrace.c.
References _, thread_info::btrace, btrace_fetch(), DEBUG, error(), find_thread_ptid(), inferior_ptid, thread_info::num, printf_unfiltered(), thread_info::ptid, target_pid_to_str(), and VEC_length.
Referenced by init_record_btrace_ops().
static void record_btrace_insn_history (int size, int flags) [static]
Definition at line 266 of file record-btrace.c.
References _, btrace_insn_iterator::begin, btrace_insn_history(), current_uiout, DEBUG, do_cleanups(), btrace_insn_iterator::end, error(), btrace_thread_info::insn_iterator, make_cleanup_ui_out_tuple_begin_end(), min, printf_unfiltered(), require_btrace(), and VEC_length.
Referenced by init_record_btrace_ops().
static void record_btrace_insn_history_from (ULONGEST from, int size, int flags) [static]
Definition at line 384 of file record-btrace.c.
References from, record_btrace_insn_history_range(), and ULONGEST.
Referenced by init_record_btrace_ops().
static void record_btrace_insn_history_range (ULONGEST from, ULONGEST to, int flags) [static]
Definition at line 341 of file record-btrace.c.
References _, btrace_insn_iterator::begin, btrace_insn_history(), current_uiout, DEBUG, do_cleanups(), btrace_insn_iterator::end, error(), btrace_thread_info::insn_iterator, int, make_cleanup_ui_out_tuple_begin_end(), require_btrace(), and VEC_length.
Referenced by init_record_btrace_ops(), and record_btrace_insn_history_from().
static void record_btrace_open (char * args, int from_tty) [static]
Definition at line 138 of file record-btrace.c.
References _, ALL_THREADS, btrace_enable(), current_inferior(), DEBUG, discard_cleanups(), error(), gdb_assert, make_cleanup(), null_cleanup(), thread_info::num, number_is_in_list(), observer_notify_record_changed(), push_target(), record_btrace_auto_enable(), record_btrace_disable_callback(), record_btrace_ops, RECORD_IS_USED, target_has_execution, and target_supports_btrace().
Referenced by init_record_btrace_ops().
static void record_btrace_stop_recording (void) [static]
Definition at line 177 of file record-btrace.c.
References ALL_THREADS, thread_info::btrace, btrace_disable(), DEBUG, record_btrace_auto_disable(), and btrace_thread_info::target.
Referenced by init_record_btrace_ops().
static struct btrace_thread_info* require_btrace (void) [static, read]
Definition at line 62 of file record-btrace.c.
References _, thread_info::btrace, btrace_fetch(), DEBUG, error(), find_thread_ptid(), inferior_ptid, and VEC_empty.
Referenced by record_btrace_call_history(), record_btrace_call_history_range(), record_btrace_insn_history(), and record_btrace_insn_history_range().
static void ui_out_field_uint (struct ui_out * uiout, const char * fld, unsigned int val) [static]
Definition at line 231 of file record-btrace.c.
References ui_out_field_fmt().
Referenced by btrace_func_history(), btrace_func_history_insn_range(), and btrace_insn_history().
Variable Documentation
struct target_ops record_btrace_ops [static]
Definition at line 37 of file record-btrace.c.
Referenced by init_record_btrace_ops(), and record_btrace_open().
struct observer* record_btrace_thread_observer [static]
Definition at line 40 of file record-btrace.c.