GDB (xrefs): /home/stan/gdb/src/gdb/regcache.h File Reference
/home/stan/gdb/src/gdb/regcache.h File Reference
Enumerations
enum register_status { REG_UNKNOWN = 0, REG_VALID = 1, REG_UNAVAILABLE = -1 }
Functions
struct regcache * get_current_regcache (void)
struct regcache * get_thread_regcache (ptid_t ptid)
struct regcache * get_thread_arch_regcache (ptid_t, struct gdbarch *)
struct regcache * get_thread_arch_aspace_regcache (ptid_t, struct gdbarch *, struct address_space *)
void regcache_xfree (struct regcache *regcache)
struct cleanup * make_cleanup_regcache_xfree (struct regcache *regcache)
struct regcache * regcache_xmalloc (struct gdbarch *gdbarch, struct address_space *aspace)
struct gdbarch * get_regcache_arch (const struct regcache *regcache)
struct address_space * get_regcache_aspace (const struct regcache *)
enum register_status regcache_register_status (const struct regcache *regcache, int regnum)
enum register_status regcache_raw_read (struct regcache *regcache, int rawnum, gdb_byte *buf)
void regcache_raw_write (struct regcache *regcache, int rawnum, const gdb_byte *buf)
enum register_status regcache_raw_read_signed (struct regcache *regcache, int regnum, LONGEST *val)
enum register_status regcache_raw_read_unsigned (struct regcache *regcache, int regnum, ULONGEST *val)
void regcache_raw_write_signed (struct regcache *regcache, int regnum, LONGEST val)
void regcache_raw_write_unsigned (struct regcache *regcache, int regnum, ULONGEST val)
enum register_status regcache_raw_read_part (struct regcache *regcache, int regnum, int offset, int len, gdb_byte *buf)
void regcache_raw_write_part (struct regcache *regcache, int regnum, int offset, int len, const gdb_byte *buf)
void regcache_invalidate (struct regcache *regcache, int regnum)
enum register_status regcache_cooked_read (struct regcache *regcache, int rawnum, gdb_byte *buf)
void regcache_cooked_write (struct regcache *regcache, int rawnum, const gdb_byte *buf)
struct value * regcache_cooked_read_value (struct regcache *regcache, int regnum)
enum register_status regcache_cooked_read_signed (struct regcache *regcache, int regnum, LONGEST *val)
enum register_status regcache_cooked_read_unsigned (struct regcache *regcache, int regnum, ULONGEST *val)
void regcache_cooked_write_signed (struct regcache *regcache, int regnum, LONGEST val)
void regcache_cooked_write_unsigned (struct regcache *regcache, int regnum, ULONGEST val)
enum register_status regcache_cooked_read_part (struct regcache *regcache, int regnum, int offset, int len, gdb_byte *buf)
void regcache_cooked_write_part (struct regcache *regcache, int regnum, int offset, int len, const gdb_byte *buf)
CORE_ADDR regcache_read_pc (struct regcache *regcache)
void regcache_write_pc (struct regcache *regcache, CORE_ADDR pc)
void regcache_raw_supply (struct regcache *regcache, int regnum, const void *buf)
void regcache_raw_collect (const struct regcache *regcache, int regnum, void *buf)
struct type * register_type (struct gdbarch *gdbarch, int regnum)
int register_size (struct gdbarch *gdbarch, int regnum)
enum register_status() regcache_cooked_read_ftype (void *src, int regnum, gdb_byte *buf)
void regcache_save (struct regcache *dst, regcache_cooked_read_ftype *cooked_read, void *cooked_read_context)
struct regcache * regcache_dup (struct regcache *regcache)
void regcache_cpy (struct regcache *dest, struct regcache *src)
void regcache_cpy_no_passthrough (struct regcache *dest, struct regcache *src)
void registers_changed (void)
void registers_changed_ptid (ptid_t)
Enumeration Type Documentation
enum register_status
Enumerator:
REG_UNKNOWN
REG_VALID
REG_UNAVAILABLE
Definition at line 47 of file regcache.h.
Function Documentation
struct regcache* get_current_regcache (void) [read]
Definition at line 510 of file regcache.c.
References get_thread_regcache(), and inferior_ptid.
Referenced by bookmark_1(), bsd_kvm_open(), bsd_kvm_pcb_cmd(), bsd_kvm_proc_cmd(), call_function_by_hand(), core_open(), create_new_frame(), current_me_module(), current_options(), darwin_solib_get_all_image_info_addr_at_init(), deprecated_mips_set_processor_regs_hack(), fbsd_make_corefile_notes(), fork_load_infrun_state(), fork_save_infrun_state(), frame_pop(), frv_fdpic_loadmap_addresses(), gdb_loc(), generic_load(), get_current_frame(), get_return_value(), get_traceframe_location(), handle_inferior_event(), i386fbsd_resume(), ia64_hpux_xfer_memory(), ia64_linux_stopped_data_address(), info_checkpoints_command(), m32c_virtual_frame_pointer(), m32r_create_inferior(), m32r_load(), m32r_resume(), m32r_upload_command(), mi_cmd_data_write_register_values(), monitor_create_inferior(), monitor_load(), monitor_wait(), normal_stop(), post_create_inferior(), proceed(), procfs_wait(), put_frame_register(), record_full_core_open_1(), record_full_goto_insn(), record_full_restore(), record_full_resume(), record_full_save(), record_full_wait_1(), regcache_print(), restore_infcall_suspend_state(), resume(), return_command(), run_command_1(), save_bookmark_command(), save_infcall_suspend_state(), svr4_handle_solib_event(), trace_find_pc_command(), windows_resume(), xtensa_read_register(), and xtensa_write_register().
struct gdbarch* get_regcache_arch (const struct regcache * regcache) [read]
Definition at line 274 of file regcache.c.
References regcache::descr, and regcache_descr::gdbarch.
Referenced by aarch64_extract_return_value(), aarch64_store_return_value(), adjust_pc_after_break(), aix_thread_wait(), alpha_extract_return_value(), alpha_store_return_value(), alphabsd_fetch_inferior_registers(), alphabsd_store_inferior_registers(), amd64_collect_fxsave(), amd64_collect_native_gregset(), amd64_collect_xsave(), amd64_linux_fetch_inferior_registers(), amd64_linux_store_inferior_registers(), amd64_supply_fxsave(), amd64_supply_native_gregset(), amd64_supply_xsave(), amd64bsd_fetch_inferior_registers(), amd64bsd_store_inferior_registers(), amd64obsd_collect_uthread(), amd64obsd_supply_uthread(), arm_extract_return_value(), arm_linux_supply_gregset(), arm_store_return_value(), arm_supply_gregset(), arm_write_pc(), bfin_extract_return_value(), bookmark_1(), bsd_uthread_fetch_registers(), bsd_uthread_store_registers(), bx_write_pc(), cancel_breakpoint(), check_event(), cris_extract_return_value(), cris_store_return_value(), cris_supply_gregset(), dbug_supply_register(), debug_print_register(), deprecated_mips_set_processor_regs_hack(), displaced_in_arm_mode(), displaced_step_fixup(), displaced_step_prepare(), do_windows_fetch_inferior_registers(), do_windows_store_inferior_registers(), e500_move_ev_register(), exec_one_dummy_insn(), fbsd_make_corefile_notes(), fetch_all_gp_regs(), fetch_altivec_register(), fetch_core_registers(), fetch_fp_regs(), fetch_gp_regs(), fetch_osf_core_registers(), fetch_ppc_registers(), fetch_register(), fetch_register_using_p(), fetch_regs(), fetch_regs_kernel_thread(), fetch_regs_user_thread(), fetch_spe_register(), fetch_vsx_register(), fill_fpregset(), fill_fprs(), fill_gprs32(), fill_gprs64(), fill_gregset(), fill_sprs32(), fill_sprs64(), fill_vrregset(), fill_vsxregset(), find_func_descr(), frv_extract_return_value(), gdbsim_fetch_register(), gdbsim_store_register(), get_core_registers(), get_return_value(), get_thread_arch_aspace_regcache(), gnu_fetch_registers(), gnu_store_registers(), go32_fetch_registers(), go32_store_registers(), h8300_extract_return_value(), h8300_store_return_value(), h8300h_extract_return_value(), h8300h_store_return_value(), handle_inferior_event(), hppa_hpux_fetch_inferior_registers(), hppa_hpux_fetch_register(), hppa_hpux_save_state_offset(), hppa_hpux_store_inferior_registers(), hppa_hpux_store_register(), hppa_hpux_supply_save_state(), hppa_hpux_supply_ss_fpblock(), hppa_hpux_supply_ss_wide(), hppa_linux_fetch_inferior_registers(), hppa_linux_store_inferior_registers(), hppa_linux_supply_regset(), hppaobsd_supply_fpregset(), i386_darwin_fetch_inferior_registers(), i386_darwin_store_inferior_registers(), i386_linux_fetch_inferior_registers(), i386_linux_get_syscall_number_from_regcache(), i386_linux_resume(), i386_linux_store_inferior_registers(), i386_mmx_regnum_to_fp_regnum(), i386nto_supply_gregset(), i386obsd_collect_uthread(), i386obsd_supply_pcb(), i386obsd_supply_uthread(), i387_collect_fsave(), i387_collect_fxsave(), i387_collect_xsave(), i387_supply_fsave(), i387_supply_fxsave(), i387_supply_xsave(), ia64_extract_return_value(), ia64_hpux_at_dld_breakpoint_1_p(), ia64_hpux_fetch_register(), ia64_hpux_fetch_registers(), ia64_hpux_fetch_rnat_register(), ia64_hpux_store_register(), ia64_hpux_store_registers(), ia64_linux_fetch_register(), ia64_linux_fetch_registers(), ia64_linux_store_register(), ia64_linux_store_registers(), ia64_store_return_value(), inf_child_fetch_inferior_registers(), inf_ptrace_fetch_register(), inf_ptrace_fetch_registers(), inf_ptrace_store_register(), inf_ptrace_store_registers(), iq2000_extract_return_value(), keep_going(), linux_collect_thread_registers(), linux_nat_collect_thread_registers(), lm32_extract_return_value(), lm32_store_return_value(), m32c_pseudo_register_read(), m32c_pseudo_register_write(), m32c_read_flg(), m32r_extract_return_value(), m32r_fetch_register(), m32r_store_register(), m32r_store_return_value(), m32r_supply_register(), m68k_svr4_extract_return_value(), m68k_svr4_store_return_value(), m68kbsd_collect_fpregset(), m68kbsd_supply_fpregset(), m88k_store_arguments(), mi_cmd_data_list_changed_registers(), mi_cmd_data_write_register_values(), mips64_fill_fpregset(), mips64_fill_gregset(), mips64_linux_regsets_fetch_registers(), mips64_linux_regsets_store_registers(), mips64_supply_fpregset(), mips64_supply_gregset(), mips_fill_fpregset(), mips_fill_gregset(), mips_linux_write_pc(), mips_read_pc(), mips_supply_fpregset(), mips_supply_gregset(), mips_write_pc(), mipsnbsd_fetch_inferior_registers(), mipsnbsd_fill_fpreg(), mipsnbsd_fill_reg(), mipsnbsd_store_inferior_registers(), mipsnbsd_supply_fpreg(), mipsnbsd_supply_fpregset(), mipsnbsd_supply_gregset(), mipsnbsd_supply_reg(), monitor_fetch_register(), monitor_fetch_registers(), monitor_store_register(), monitor_store_registers(), monitor_supply_register(), moxie_extract_return_value(), moxie_store_return_value(), old_fetch_inferior_registers(), old_store_inferior_registers(), picobug_dumpregs(), ppc_collect_fpregset(), ppc_collect_gregset(), ppc_collect_reg(), ppc_collect_vrregset(), ppc_collect_vsxregset(), ppc_linux_collect_gregset(), ppc_linux_supply_gregset(), ppc_linux_write_pc(), ppc_ravenscar_generic_fetch_registers(), ppc_ravenscar_generic_store_registers(), ppc_supply_fpregset(), ppc_supply_gregset(), ppc_supply_reg(), ppc_supply_vrregset(), ppc_supply_vsxregset(), ppcfbsd_fetch_inferior_registers(), ppcfbsd_store_inferior_registers(), ppcfbsd_supply_pcb(), ppcnbsd_fetch_inferior_registers(), ppcnbsd_store_inferior_registers(), ppcnbsd_supply_pcb(), ppcobsd_fetch_registers(), ppcobsd_store_registers(), ppcobsd_supply_pcb(), ppu2spu_prev_arch(), ppu2spu_prev_register(), proceed(), process_g_packet(), procfs_fetch_registers(), procfs_store_registers(), ravenscar_fetch_registers(), ravenscar_prepare_to_store(), ravenscar_store_registers(), record_full_core_fetch_registers(), record_full_core_open_1(), record_full_goto_insn(), record_full_message(), record_full_reg_alloc(), record_full_registers_change(), record_full_save(), record_full_store_registers(), record_full_wait_1(), record_linux_msghdr(), record_linux_sockaddr(), record_linux_system_call(), regcache_dump(), regcache_raw_write(), regcache_read_pc(), regcache_write_pc(), register_changed_p(), remote_fetch_registers(), remote_prepare_to_store(), remote_store_registers(), restore_infcall_suspend_state(), resume(), resume_stopped_resumed_lwps(), return_command(), rs6000_fetch_inferior_registers(), rs6000_pseudo_register_read(), rs6000_pseudo_register_write(), rs6000_store_inferior_registers(), s390_linux_fetch_inferior_registers(), s390_write_pc(), save_bookmark_command(), save_infcall_suspend_state(), sentinel_frame_prev_arch(), sh64_extract_return_value(), sh64_store_return_value(), sh_corefile_collect_regset(), sh_corefile_supply_regset(), sh_extract_return_value_fpu(), sh_extract_return_value_nofpu(), sh_store_return_value_fpu(), sh_store_return_value_nofpu(), shnbsd_fetch_inferior_registers(), shnbsd_store_inferior_registers(), sparc32_store_arguments(), sparc32obsd_collect_uthread(), sparc32obsd_supply_uthread(), sparc64_collect_fpregset(), sparc64_collect_gregset(), sparc64_linux_write_pc(), sparc64_store_arguments(), sparc64_supply_fpregset(), sparc64_supply_gregset(), sparc64nbsd_collect_fpregset(), sparc64nbsd_collect_gregset(), sparc64nbsd_supply_fpregset(), sparc64nbsd_supply_gregset(), sparc64obsd_collect_uthread(), sparc64obsd_supply_uthread(), sparc_collect_rwindow(), sparc_fetch_inferior_registers(), sparc_linux_write_pc(), sparc_ravenscar_fetch_registers(), sparc_ravenscar_store_registers(), sparc_store_inferior_registers(), sparc_supply_rwindow(), sparc_write_pc(), spu2ppu_prev_arch(), spu2ppu_prev_register(), spu_fetch_inferior_registers(), spu_fetch_registers(), spu_pseudo_register_read_spu(), spu_pseudo_register_write_spu(), spu_read_pc(), spu_store_registers(), store_all_gp_regs(), store_altivec_register(), store_fp_regs(), store_gp_regs(), store_ppc_registers(), store_register(), store_register_using_P(), store_registers_using_G(), store_regs(), store_regs_kernel_thread(), store_regs_user_thread(), store_spe_register(), store_vsx_register(), supply_32bit_reg(), supply_64bit_reg(), supply_fpregset(), supply_fprs(), supply_gprs64(), supply_gregset(), supply_gregset_reg(), supply_register_at_address(), supply_sprs32(), supply_sprs64(), supply_vrregset(), supply_vsxregset(), tfile_fetch_registers(), tilegx_linux_supply_regset(), v850_extract_return_value(), v850_store_return_value(), vax_store_arguments(), windows_resume(), xtensa_extract_return_value(), xtensa_register_read_masked(), xtensa_register_write_masked(), xtensa_store_return_value(), and xtensa_supply_gregset().
struct address_space* get_regcache_aspace (const struct regcache *) [read]
Definition at line 280 of file regcache.c.
References regcache::aspace.
Referenced by adjust_pc_after_break(), call_function_by_hand(), cancel_breakpoint(), create_sentinel_frame(), displaced_step_fixup(), handle_inferior_event(), handle_syscall_event(), ia64_hpux_at_dld_breakpoint_1_p(), prepare_to_proceed(), proceed(), record_full_exec_insn(), record_full_wait_1(), regcache_dup(), resume(), and resume_stopped_resumed_lwps().
struct regcache* get_thread_arch_aspace_regcache (ptid_t , struct gdbarch * , struct address_space *) [read]
Definition at line 454 of file regcache.c.
References current_regcache, get_regcache_arch(), regcache_list::next, regcache::ptid, ptid_equal(), regcache_list::regcache, regcache_xmalloc_1(), and xmalloc().
Referenced by get_thread_arch_regcache(), and handle_inferior_event().
struct regcache* get_thread_arch_regcache (ptid_t , struct gdbarch *) [read]
Definition at line 477 of file regcache.c.
References get_thread_arch_aspace_regcache(), null_ptid, ptid_equal(), and target_thread_address_space().
Referenced by enable_break(), get_thread_regcache(), linux_corefile_thread_callback(), parse_spufs_run(), process_stop_reply(), ps_lgetfpregs(), ps_lgetregs(), ps_lsetfpregs(), ps_lsetregs(), and spu2ppu_sniffer().
struct regcache* get_thread_regcache (ptid_t ptid) [read]
Definition at line 498 of file regcache.c.
References get_thread_arch_regcache(), regcache::ptid, ptid_equal(), and target_thread_architecture.
Referenced by adjust_pc_after_break(), aix_thread_wait(), amd64_linux_get_syscall_number(), arm_linux_get_syscall_number(), bfin_linux_get_syscall_number(), cancel_breakpoint(), check_event(), displaced_step_fixup(), displaced_step_prepare(), elf_gnu_ifunc_resolver_return_stop(), enable_watchpoints_in_psr(), get_current_regcache(), handle_inferior_event(), handle_syscall_event(), i386_linux_get_syscall_number(), i386_linux_resume(), ia64_hpux_at_dld_breakpoint_1_p(), ia64_hpux_handle_dld_breakpoint_1(), keep_going(), mips_linux_get_syscall_number(), ppc_linux_get_syscall_number(), prepare_to_proceed(), resume(), resume_stopped_resumed_lwps(), sparc32_linux_get_syscall_number(), sparc64_linux_get_syscall_number(), switch_to_thread(), and VEC().
struct cleanup* make_cleanup_regcache_xfree (struct regcache * regcache) [read]
Definition at line 266 of file regcache.c.
References do_regcache_xfree(), and make_cleanup().
Referenced by call_function_by_hand(), frame_pop(), frame_save_as_regcache(), get_return_value(), mi_cmd_data_list_changed_registers(), and ppu2spu_sniffer().
enum register_status regcache_cooked_read (struct regcache * regcache, int rawnum, gdb_byte * buf)
Definition at line 699 of file regcache.c.
References value::computed, regcache::descr, gdb_assert, regcache_descr::gdbarch, gdbarch_pseudo_register_read(), gdbarch_pseudo_register_read_value(), gdbarch_pseudo_register_read_value_p(), memcpy(), memset(), regcache::readonly_p, REG_UNAVAILABLE, REG_UNKNOWN, REG_VALID, regcache_raw_read(), register_buffer(), regcache::register_status, regnum, regcache_descr::sizeof_register, value_contents_raw(), value_entirely_available(), value_free_to_mark(), and value_mark().
Referenced by aarch64_extract_return_value(), alpha_extract_return_value(), amd64_linux_get_syscall_number(), arm_extract_return_value(), arm_return_value(), avr_return_value(), bfin_linux_get_syscall_number(), do_cooked_read(), do_ppc_sysv_return_value(), dummy_frame_prev_register(), gdbsim_store_register(), get_decimal_float_return_value(), hppa32_return_value(), i386_linux_get_syscall_number_from_regcache(), ia64_extract_return_value(), m32c_cat_read(), m32c_r3r2r1r0_read(), m88k_return_value(), microblaze_extract_return_value(), mips_linux_get_syscall_number(), nios2_extract_return_value(), ppc64_sysv_abi_return_value(), ppc_linux_get_syscall_number(), record_full_exec_insn(), regcache_cooked_read_part(), regcache_cooked_read_signed(), regcache_cooked_read_unsigned(), regcache_cooked_read_value(), regcache_cooked_write_part(), regcache_dump(), register_changed_p(), rs6000_lynx178_return_value(), rs6000_return_value(), s390_return_value(), sh64_extract_return_value(), sparc32_extract_return_value(), sparc32_linux_get_syscall_number(), sparc64_extract_floating_fields(), sparc64_extract_return_value(), sparc64_linux_get_syscall_number(), spu2ppu_prev_register(), spu_push_dummy_call(), spu_regcache_to_value(), tic6x_extract_return_value(), and vax_return_value().
enum register_status() regcache_cooked_read_ftype (void * src, int regnum, gdb_byte * buf)
enum register_status regcache_cooked_read_part (struct regcache * regcache, int regnum, int offset, int len, gdb_byte * buf)
Definition at line 968 of file regcache.c.
References regcache::descr, gdb_assert, regcache_descr::nr_cooked_registers, regcache_cooked_read(), regcache_cooked_write(), and regcache_xfer_part().
Referenced by hppa32_return_value(), hppa64_return_value(), m32c_part_read(), mep_extract_return_value(), mips_xfer_register(), ppc64_sysv_abi_return_value(), s390_return_value(), score_xfer_register(), spu_regcache_to_value(), spu_return_value(), and tic6x_extract_return_value().
enum register_status regcache_cooked_read_signed (struct regcache * regcache, int regnum, LONGEST * val)
Definition at line 779 of file regcache.c.
References regcache::descr, extract_signed_integer(), gdb_assert, regcache_descr::gdbarch, gdbarch_byte_order(), REG_VALID, regcache_cooked_read(), regcache_descr::sizeof_register, and exsummary::status.
Referenced by mips_read_pc().
enum register_status regcache_cooked_read_unsigned (struct regcache * regcache, int regnum, ULONGEST * val)
Definition at line 799 of file regcache.c.
References regcache::descr, extract_unsigned_integer(), gdb_assert, regcache_descr::gdbarch, gdbarch_byte_order(), REG_VALID, regcache_cooked_read(), regcache_descr::sizeof_register, and exsummary::status.
Referenced by aarch64_extract_return_value(), alpha_extract_return_value(), amd64_displaced_step_fixup(), arm_extract_return_value(), arm_linux_cleanup_svc(), arm_linux_get_syscall_number(), arm_write_pc(), avr_read_pc(), bfin_extract_return_value(), bx_write_pc(), cris_extract_return_value(), current_me_module(), current_options(), deprecated_mips_set_processor_regs_hack(), displaced_in_arm_mode(), displaced_read_reg(), do_ppc_sysv_return_value(), enable_watchpoints_in_psr(), find_func_descr(), fixup_riprel(), frv_extract_return_value(), frv_fdpic_loadmap_addresses(), h8300_extract_return_value(), h8300h_extract_return_value(), hppa_hpux_read_pc(), hppa_hpux_save_state_offset(), hppa_hpux_write_pc(), hppa_read_pc(), hppa_skip_permanent_breakpoint(), i386_displaced_step_fixup(), i386_linux_resume(), i386fbsd_resume(), ia64_allocate_new_rse_frame(), ia64_extract_return_value(), ia64_hpux_handle_dld_breakpoint_1(), ia64_hpux_handle_load_event(), ia64_hpux_push_dummy_code(), ia64_linux_stopped_data_address(), ia64_pseudo_register_read(), ia64_pseudo_register_write(), ia64_push_dummy_call(), ia64_read_pc(), ia64_write_pc(), iq2000_extract_return_value(), lm32_extract_return_value(), m32c_return_value(), m32r_extract_return_value(), m32r_read_pc(), m32r_store_register(), m32r_supply_register(), m68hc11_pseudo_register_read(), mep_read_pc(), mn10300_read_pc(), monitor_store_register(), moxie_extract_return_value(), moxie_read_pc(), msp430_return_value(), mt_pseudo_register_read(), mt_return_value(), parse_spufs_run(), ppc64_sysv_abi_push_dummy_call(), ppc64_sysv_abi_return_value(), ppc_displaced_step_fixup(), ppc_sysv_abi_push_dummy_call(), regcache_read_pc(), rl78_return_value(), rs6000_lynx178_push_dummy_call(), rs6000_lynx178_return_value(), rs6000_push_dummy_call(), rs6000_return_value(), rx_return_value(), s390_displaced_step_fixup(), s390_push_dummy_call(), s390_supply_tdb_regset(), sh_extract_return_value_nofpu(), sparc32_return_value(), sparc32_supply_gregset(), sparc64_linux_write_pc(), sparc64_supply_gregset(), sparc_linux_write_pc(), sparc_ravenscar_fetch_registers(), sparc_ravenscar_store_registers(), sparc_store_inferior_registers(), spu_read_pc(), spu_write_pc(), v850_extract_return_value(), xtensa_register_read_masked(), and xtensa_register_write_masked().
struct value* regcache_cooked_read_value (struct regcache * regcache, int regnum) [read]
Definition at line 746 of file regcache.c.
References allocate_value(), regcache::descr, gdb_assert, regcache_descr::gdbarch, gdbarch_pseudo_register_read_value(), gdbarch_pseudo_register_read_value_p(), lval_register, mark_value_bytes_unavailable(), regcache::readonly_p, REG_UNAVAILABLE, REG_UNKNOWN, regcache_cooked_read(), regcache::register_status, register_type(), regnum, TYPE_LENGTH, value_contents_raw(), VALUE_LVAL, VALUE_REGNUM, and value_type().
Referenced by sentinel_frame_prev_register().
void regcache_cooked_write (struct regcache * regcache, int rawnum, const gdb_byte * buf)
Definition at line 881 of file regcache.c.
References regcache::descr, gdb_assert, regcache_descr::gdbarch, gdbarch_pseudo_register_write(), and regcache_raw_write().
Referenced by aarch64_store_return_value(), alpha_push_dummy_call(), alpha_store_return_value(), amd64_push_dummy_call(), amd64_windows_push_dummy_call(), amd64_windows_store_arg_in_reg(), arm_push_dummy_call(), arm_return_value(), arm_store_return_value(), avr_return_value(), bfin_store_return_value(), cris_push_dummy_call(), do_ppc_sysv_return_value(), frv_store_return_value(), get_decimal_float_return_value(), hppa32_push_dummy_call(), hppa32_return_value(), i386_darwin_push_dummy_call(), i386_push_dummy_call(), ia64_hpux_store_argument_in_slot(), ia64_push_dummy_call(), ia64_store_return_value(), m32c_cat_write(), m32c_push_dummy_call(), m32c_r3r2r1r0_write(), m68k_push_dummy_call(), m88k_return_value(), microblaze_store_return_value(), mt_return_value(), nios2_store_return_value(), pass_in_v(), ppc64_sysv_abi_push_dummy_call(), ppc64_sysv_abi_push_float(), ppc64_sysv_abi_return_value(), ppc_sysv_abi_push_dummy_call(), put_frame_register(), record_full_exec_insn(), regcache_cooked_read_part(), regcache_cooked_write_part(), regcache_cooked_write_signed(), regcache_cooked_write_unsigned(), regcache_restore(), rs6000_lynx178_push_dummy_call(), rs6000_lynx178_return_value(), rs6000_push_dummy_call(), rs6000_return_value(), s390_push_dummy_call(), s390_return_value(), sh64_push_dummy_call(), sparc32_store_arguments(), sparc32_store_return_value(), sparc64_store_arguments(), sparc64_store_floating_fields(), sparc64_store_return_value(), spu_push_dummy_call(), spu_value_to_regcache(), tic6x_push_dummy_call(), tic6x_store_return_value(), vax_push_dummy_call(), vax_return_value(), vax_store_arguments(), and xtensa_push_dummy_call().
void regcache_cooked_write_part (struct regcache * regcache, int regnum, int offset, int len, const gdb_byte * buf)
Definition at line 979 of file regcache.c.
References regcache::descr, gdb_assert, regcache_descr::nr_cooked_registers, regcache_cooked_read(), regcache_cooked_write(), and regcache_xfer_part().
Referenced by hppa32_return_value(), hppa64_push_dummy_call(), hppa64_return_value(), m32c_part_write(), mep_store_return_value(), mips_xfer_register(), ppc64_sysv_abi_return_value(), s390_push_dummy_call(), s390_return_value(), score_xfer_register(), spu_return_value(), spu_value_to_regcache(), tic6x_push_dummy_call(), and tic6x_store_return_value().
void regcache_cooked_write_signed (struct regcache * regcache, int regnum, LONGEST val)
Definition at line 819 of file regcache.c.
References regcache::descr, gdb_assert, regcache_descr::gdbarch, gdbarch_byte_order(), regcache_cooked_write(), regcache_descr::sizeof_register, and store_signed_integer().
Referenced by alpha_push_dummy_call(), lm32_push_dummy_call(), mi_cmd_data_write_register_values(), mips_eabi_push_dummy_call(), mips_n32n64_push_dummy_call(), mips_o32_push_dummy_call(), mips_o64_push_dummy_call(), nios2_push_dummy_call(), ppc64_sysv_abi_push_dummy_call(), ppc_sysv_abi_push_dummy_call(), s390_push_dummy_call(), s390_return_value(), and tic6x_push_dummy_call().
void regcache_cooked_write_unsigned (struct regcache * regcache, int regnum, ULONGEST val)
Definition at line 833 of file regcache.c.
References regcache::descr, gdb_assert, regcache_descr::gdbarch, gdbarch_byte_order(), regcache_cooked_write(), regcache_descr::sizeof_register, and store_unsigned_integer().
Referenced by aarch64_push_dummy_call(), alpha_store_return_value(), amd64_displaced_step_fixup(), amd64_linux_write_pc(), arm_displaced_step_fixup(), arm_push_dummy_call(), arm_write_pc(), avr_push_dummy_call(), avr_write_pc(), bfin_push_dummy_call(), branch_write_pc(), bx_write_pc(), cris_push_dummy_call(), cris_store_return_value(), displaced_write_reg(), do_ppc_sysv_return_value(), enable_watchpoints_in_psr(), fixup_riprel(), frv_push_dummy_call(), h8300_push_dummy_call(), h8300_store_return_value(), h8300h_store_return_value(), hppa32_push_dummy_call(), hppa64_push_dummy_call(), hppa_hpux_push_dummy_code(), hppa_hpux_write_pc(), hppa_linux_target_write_pc(), hppa_skip_permanent_breakpoint(), hppa_write_pc(), i386_displaced_step_fixup(), i386_linux_write_pc(), i386fbsd_resume(), ia64_allocate_new_rse_frame(), ia64_hpux_set_function_addr(), ia64_linux_stopped_data_address(), ia64_linux_write_pc(), ia64_pseudo_register_write(), ia64_push_dummy_call(), ia64_store_return_value(), ia64_write_pc(), iq2000_push_dummy_call(), lm32_push_dummy_call(), lm32_store_return_value(), m32c_push_dummy_call(), m32c_return_value(), m32r_push_dummy_call(), m32r_store_return_value(), m68hc11_pseudo_register_write(), m68hc11_push_dummy_call(), m88k_write_pc(), mep_push_dummy_call(), microblaze_write_pc(), mips_eabi_push_dummy_call(), mips_linux_write_pc(), mips_n32n64_push_dummy_call(), mips_o32_push_dummy_call(), mips_o64_push_dummy_call(), mips_write_pc(), mn10300_push_dummy_call(), mn10300_write_pc(), moxie_store_return_value(), moxie_write_pc(), msp430_push_dummy_call(), msp430_return_value(), mt_pseudo_register_write(), mt_push_dummy_call(), nios2_push_dummy_call(), pass_in_x(), ppc64_sysv_abi_push_dummy_call(), ppc64_sysv_abi_return_value(), ppc_displaced_step_fixup(), ppc_linux_write_pc(), ppc_sysv_abi_push_dummy_call(), regcache_write_pc(), rl78_push_dummy_call(), rl78_return_value(), rs6000_lynx178_return_value(), rs6000_return_value(), rx_push_dummy_call(), rx_return_value(), s390_displaced_step_fixup(), s390_push_dummy_call(), s390_return_value(), s390_write_pc(), score_push_dummy_call(), sh64_push_dummy_call(), sh_push_dummy_call_fpu(), sh_push_dummy_call_nofpu(), sh_store_return_value_nofpu(), sparc32_push_dummy_call(), sparc64_linux_write_pc(), sparc64_push_dummy_call(), sparc64_store_arguments(), sparc_linux_write_pc(), sparc_write_pc(), spu_write_pc(), tic6x_push_dummy_call(), tilegx_push_dummy_call(), tilegx_write_pc(), v850_push_dummy_call(), v850_store_return_value(), vax_push_dummy_call(), xstormy16_push_dummy_call(), xtensa_push_dummy_call(), and xtensa_register_write_masked().
void regcache_cpy (struct regcache * dest, struct regcache * src)
Definition at line 372 of file regcache.c.
References regcache::descr, do_cooked_read(), gdb_assert, regcache_descr::gdbarch, regcache::readonly_p, regcache_cpy_no_passthrough(), regcache_restore(), and regcache_save().
Referenced by fork_load_infrun_state(), frame_pop(), regcache_dup(), and restore_infcall_suspend_state().
void regcache_cpy_no_passthrough (struct regcache * dest, struct regcache * src)
Definition at line 388 of file regcache.c.
References regcache::descr, gdb_assert, regcache_descr::gdbarch, memcpy(), regcache::readonly_p, regcache::register_status, regcache::registers, regcache_descr::sizeof_cooked_register_status, and regcache_descr::sizeof_cooked_registers.
Referenced by call_function_by_hand(), and regcache_cpy().
struct regcache* regcache_dup (struct regcache * regcache) [read]
Definition at line 405 of file regcache.c.
References regcache::descr, regcache_descr::gdbarch, get_regcache_aspace(), regcache_cpy(), and regcache_xmalloc().
Referenced by fork_save_infrun_state(), get_return_value(), normal_stop(), save_infcall_suspend_state(), and spu2ppu_sniffer().
void regcache_invalidate (struct regcache * regcache, int regnum)
Definition at line 428 of file regcache.c.
References regcache::descr, gdb_assert, regcache_descr::nr_raw_registers, regcache::readonly_p, REG_UNKNOWN, regcache::register_status, and regnum.
Referenced by mt_pseudo_register_write(), mt_select_coprocessor(), record_full_store_registers(), and sh_pseudo_register_write().
void regcache_raw_collect (const struct regcache * regcache, int regnum, void * buf)
Definition at line 1022 of file regcache.c.
References regcache::descr, gdb_assert, memcpy(), register_buffer(), regnum, size, and regcache_descr::sizeof_register.
Referenced by alpha_fill_fp_regs(), alpha_fill_int_regs(), am33_collect_fpregset_method(), am33_collect_gregset_method(), amd64_collect_fxsave(), amd64_collect_native_gregset(), amd64_collect_xsave(), amd64fbsd_collect_uthread(), amd64obsd_collect_uthread(), arm_linux_collect_gregset(), arm_linux_collect_nwfpe(), arm_linux_collect_vfp(), collect_nwfpe_register(), debug_print_register(), do_windows_store_inferior_registers(), fill_fpregset(), fill_fprs(), fill_gprs32(), fill_gprs64(), fill_gregset(), fill_sprs32(), fill_sprs64(), fill_vrregset(), fill_vsxregset(), gnu_store_registers(), hppa_hpux_store_register(), hppabsd_collect_fpregset(), hppabsd_collect_gregset(), hppanbsd_collect_fpregset(), hppanbsd_collect_gregset(), i386_collect_gregset(), i386_darwin_store_inferior_registers(), i386bsd_collect_gregset(), i386fbsd_collect_uthread(), i386nto_regset_fill(), i386obsd_collect_uthread(), i387_collect_fsave(), i387_collect_fxsave(), i387_collect_xsave(), ia64_hpux_store_register(), ia64_linux_store_register(), inf_ptrace_store_register(), m68kbsd_collect_fpregset(), m68kbsd_collect_gregset(), m88kbsd_collect_gregset(), mips64_fill_fpregset(), mips64_fill_gregset(), mips64obsd_collect_gregset(), mips_fill_fpregset(), mips_fill_gregset(), mipsnbsd_fill_fpreg(), mipsnbsd_fill_reg(), ppc_collect_reg(), ppc_ravenscar_generic_store_registers(), procfs_store_registers(), record_full_core_open_1(), record_full_core_store_registers(), s390_collect_regset(), s390_native_collect(), sh_corefile_collect_regset(), sol_thread_store_registers(), sparc32_collect_fpregset(), sparc32_collect_gregset(), sparc32obsd_collect_uthread(), sparc64_collect_fpregset(), sparc64_collect_gregset(), sparc64obsd_collect_uthread(), sparc_collect_rwindow(), sparc_ravenscar_store_registers(), spu_store_inferior_registers(), spu_store_registers(), store_altivec_register(), store_fp_register(), store_fp_regs(), store_fpregister(), store_fpregs(), store_fpregs_to_thread(), store_gregs_to_thread(), store_register(), store_register_using_P(), store_registers_using_G(), store_regs(), store_regs_kernel_thread(), store_regs_user_thread(), store_spe_register(), store_vfp_regs(), store_vsx_register(), store_wmmx_regs(), store_xtregs(), and vaxbsd_collect_gregset().
enum register_status regcache_raw_read (struct regcache * regcache, int rawnum, gdb_byte * buf)
Definition at line 599 of file regcache.c.
References regcache::descr, do_cleanups(), gdb_assert, inferior_ptid, memcpy(), memset(), regcache::ptid, regcache::readonly_p, REG_UNAVAILABLE, REG_UNKNOWN, REG_VALID, regcache_register_status(), register_buffer(), regcache::register_status, regnum, save_inferior_ptid(), regcache_descr::sizeof_register, and target_fetch_registers().
Referenced by aarch64_pseudo_read_value(), amd64_pseudo_register_read_value(), amd64_pseudo_register_write(), amd64_return_value(), arm_neon_quad_read(), arm_pseudo_read(), arm_pseudo_write(), bfin_pseudo_register_read(), bfin_pseudo_register_write(), dfp_pseudo_register_read(), do_regcache_raw_read(), frv_pseudo_register_read(), frv_pseudo_register_write(), h8300_pseudo_register_read(), i386_extract_return_value(), i386_pseudo_register_read_into_value(), i386_pseudo_register_write(), m32c_banked_read(), m32c_raw_read(), m68hc11_extract_return_value(), m68k_extract_return_value(), m68k_svr4_extract_return_value(), mep_pseudo_cr32_read(), mep_pseudo_cr64_read(), mep_pseudo_register_read(), mips_pseudo_register_read(), mn10300_extract_return_value(), moxie_process_record(), mt_pseudo_register_read(), mt_select_coprocessor(), ppu2spu_prev_register(), pseudo_register_read_portions(), record_full_arch_list_add_reg(), regcache_cooked_read(), regcache_dump(), regcache_raw_read_part(), regcache_raw_read_signed(), regcache_raw_read_unsigned(), regcache_raw_write_part(), remote_prepare_to_store(), rl78_pseudo_register_read(), sh64_extract_return_value(), sh64_pseudo_register_read(), sh64_pseudo_register_write(), sh_extract_return_value_fpu(), sh_extract_return_value_nofpu(), sh_pseudo_register_read(), sparc32_pseudo_register_read(), sparc64_pseudo_register_read(), spu_pseudo_register_read(), spu_pseudo_register_write(), tilegx_extract_return_value(), v850_extract_return_value(), vsx_pseudo_register_read(), xstormy16_extract_return_value(), xtensa_extract_return_value(), xtensa_pseudo_register_read(), xtensa_pseudo_register_write(), and xtensa_push_dummy_call().
enum register_status regcache_raw_read_part (struct regcache * regcache, int regnum, int offset, int len, gdb_byte * buf)
Definition at line 946 of file regcache.c.
References regcache::descr, gdb_assert, regcache_descr::nr_raw_registers, regcache_raw_read(), regcache_raw_write(), and regcache_xfer_part().
Referenced by amd64_return_value(), amd64_windows_return_value(), efpr_pseudo_register_read(), mips_pseudo_register_read(), and xtensa_extract_return_value().
enum register_status regcache_raw_read_signed (struct regcache * regcache, int regnum, LONGEST * val)
Definition at line 633 of file regcache.c.
References regcache::descr, extract_signed_integer(), gdb_assert, regcache_descr::gdbarch, gdbarch_byte_order(), REG_VALID, regcache_raw_read(), regcache_descr::sizeof_register, and exsummary::status.
Referenced by arm_record_ld_st_reg_offset(), i386_linux_intx80_sysenter_syscall_record(), mips_pseudo_register_read(), and record_linux_system_call().
enum register_status regcache_raw_read_unsigned (struct regcache * regcache, int regnum, ULONGEST * val)
Definition at line 652 of file regcache.c.
References regcache::descr, extract_unsigned_integer(), gdb_assert, regcache_descr::gdbarch, gdbarch_byte_order(), REG_VALID, regcache_raw_read(), regcache_descr::sizeof_register, and exsummary::status.
Referenced by alpha_return_value(), amd64_linux_record_signal(), amd64_linux_syscall_record(), amd64_return_value(), amd64_windows_return_value(), arm_process_record(), arm_record_data_proc_misc_ld_str(), arm_record_extension_space(), arm_record_ld_st_imm_offset(), arm_record_ld_st_multiple(), arm_record_ld_st_reg_offset(), arm_record_strx(), avr_pseudo_register_read(), h8300h_return_value(), hppa_pseudo_register_read(), i386_linux_record_signal(), i386_mmx_regnum_to_fp_regnum(), i386_process_record(), i386_record_lea_modrm_addr(), i386_record_push(), i386_return_value(), i386_store_return_value(), i387_return_value(), ia64_hpux_fetch_rnat_register(), ia64_hpux_xfer_memory(), m32c_read_flg(), m68k_return_value(), m68k_svr4_return_value(), mep_pseudo_csr_write(), mep_return_value(), msp430_pseudo_register_read(), record_linux_system_call(), rl78_pseudo_register_read(), rl78_pseudo_register_write(), s390_pseudo_register_read(), s390_pseudo_register_write(), sparc64_pseudo_register_read(), sparc64_pseudo_register_write(), spu_pseudo_register_read(), spu_pseudo_register_read_spu(), spu_pseudo_register_write(), spu_pseudo_register_write_spu(), thumb_record_ld_st_imm_offset(), thumb_record_ld_st_reg_offset(), thumb_record_ld_st_stack(), thumb_record_ldm_stm_swi(), thumb_record_misc(), vax_return_value(), xtensa_extract_return_value(), xtensa_push_dummy_call(), xtensa_read_register(), and xtensa_store_return_value().
void regcache_raw_supply (struct regcache * regcache, int regnum, const void * buf)
Definition at line 992 of file regcache.c.
References regcache::descr, gdb_assert, memcpy(), memset(), regcache::readonly_p, REG_UNAVAILABLE, REG_VALID, register_buffer(), regcache::register_status, regnum, size, and regcache_descr::sizeof_register.
Referenced by aarch64_linux_supply_fpregset(), aarch64_linux_supply_gregset(), alpha_linux_supply_fpregset(), alpha_linux_supply_gregset(), alpha_supply_fp_regs(), alpha_supply_int_regs(), alphabsd_supply_pcb(), alphanbsd_aout_supply_gregset(), alphanbsd_supply_fpregset(), alphanbsd_supply_gregset(), am33_supply_fpregset_method(), am33_supply_gregset_method(), amd64_supply_fxsave(), amd64_supply_native_gregset(), amd64_supply_xsave(), amd64fbsd_supply_pcb(), amd64fbsd_supply_uthread(), amd64obsd_supply_pcb(), amd64obsd_supply_uthread(), arm_linux_supply_gregset(), arm_linux_supply_nwfpe(), arm_linux_supply_vfp(), arm_supply_fparegset(), arm_supply_gregset(), armbsd_supply_fpregset(), armbsd_supply_gregset(), cris_supply_gregset(), do_windows_fetch_inferior_registers(), fetch_altivec_register(), fetch_core_registers(), fetch_fp_register(), fetch_fpregister(), fetch_fpregs(), fetch_fpregs_from_thread(), fetch_gregs_from_thread(), fetch_osf_core_registers(), fetch_register(), fetch_register_using_p(), fetch_regs(), fetch_regs_kernel_thread(), fetch_spe_register(), fetch_vfp_regs(), fetch_vsx_register(), fetch_wmmx_regs(), fetch_xtregs(), frv_linux_supply_fpregset(), frv_linux_supply_gregset(), gdbsim_fetch_register(), get_core_registers(), gnu_fetch_registers(), gnu_store_registers(), hppa_hpux_fetch_register(), hppa_hpux_supply_save_state(), hppa_hpux_supply_ss_fpblock(), hppa_hpux_supply_ss_narrow(), hppa_hpux_supply_ss_wide(), hppa_linux_supply_fpregset(), hppa_linux_supply_regset(), hppabsd_supply_fpregset(), hppabsd_supply_gregset(), hppanbsd_supply_fpregset(), hppanbsd_supply_gregset(), hppaobsd_supply_fpregset(), hppaobsd_supply_gregset(), i386_darwin_fetch_inferior_registers(), i386_supply_gregset(), i386bsd_supply_gregset(), i386fbsd_supply_pcb(), i386fbsd_supply_uthread(), i386nbsd_supply_pcb(), i386obsd_supply_pcb(), i386obsd_supply_uthread(), i387_supply_fsave(), i387_supply_fxsave(), i387_supply_xsave(), ia64_hpux_fetch_register(), ia64_hpux_fetch_rnat_register(), ia64_linux_fetch_register(), inf_child_fetch_inferior_registers(), inf_ptrace_fetch_register(), m32r_fetch_register(), m32r_linux_supply_gregset(), m68kbsd_supply_fpregset(), m68kbsd_supply_gregset(), m68kbsd_supply_pcb(), m88k_supply_gregset(), m88kbsd_supply_gregset(), mips64_supply_fpregset(), mips64_supply_gregset(), mips64obsd_supply_gregset(), mips_supply_fpregset(), mips_supply_gregset(), mipsnbsd_supply_fpreg(), mipsnbsd_supply_fpregset(), mipsnbsd_supply_gregset(), mipsnbsd_supply_reg(), monitor_fetch_register(), monitor_supply_register(), nios2_supply_gregset(), ppc_supply_reg(), ppcfbsd_supply_pcb(), ppcnbsd_supply_pcb(), ppcobsd_supply_pcb(), process_g_packet(), process_stop_reply(), record_full_core_fetch_registers(), remote_fetch_registers(), s390_native_supply(), s390_supply_regset(), score7_linux_supply_gregset(), sh_corefile_supply_regset(), sol_thread_store_registers(), sparc32_supply_fpregset(), sparc32_supply_gregset(), sparc32nbsd_supply_pcb(), sparc32obsd_supply_uthread(), sparc64_supply_fpregset(), sparc64_supply_gregset(), sparc64fbsd_kvm_supply_pcb(), sparc64nbsd_supply_pcb(), sparc64obsd_supply_uthread(), sparc_fetch_inferior_registers(), sparc_supply_rwindow(), spu_fetch_inferior_registers(), spu_fetch_registers(), supply_32bit_reg(), supply_64bit_reg(), supply_fpregset(), supply_fprs(), supply_gprs64(), supply_gregset(), supply_gregset_reg(), supply_nwfpe_register(), supply_reg32(), supply_register_at_address(), supply_sprs32(), supply_sprs64(), supply_vrregset(), supply_vsxregset(), tfile_fetch_registers(), tilegx_linux_supply_regset(), vax_supply_gregset(), vaxbsd_supply_gregset(), vaxbsd_supply_pcb(), and xtensa_supply_gregset().
void regcache_raw_write (struct regcache * regcache, int rawnum, const gdb_byte * buf)
Definition at line 847 of file regcache.c.
References regcache::descr, do_cleanups(), gdb_assert, gdbarch_cannot_store_register(), get_regcache_arch(), inferior_ptid, memcmp(), memcpy(), regcache::ptid, regcache::readonly_p, REG_VALID, regcache_register_status(), register_buffer(), regcache::register_status, regnum, save_inferior_ptid(), regcache_descr::sizeof_register, target_prepare_to_store, and target_store_registers().
Referenced by aarch64_pseudo_write(), amd64_pseudo_register_write(), amd64_return_value(), arm_neon_quad_write(), arm_pseudo_write(), bfin_pseudo_register_write(), dfp_pseudo_register_write(), do_regcache_raw_write(), frv_pseudo_register_write(), h8300_pseudo_register_write(), i386_darwin_push_dummy_call(), i386_pseudo_register_write(), i386_store_return_value(), iq2000_push_dummy_call(), iq2000_store_return_value(), m32c_banked_write(), m32c_raw_write(), m68hc11_store_return_value(), m68k_store_return_value(), m68k_svr4_store_return_value(), m88k_store_arguments(), mep_pseudo_cr32_write(), mep_pseudo_cr64_write(), mep_pseudo_register_write(), mips_pseudo_register_write(), mn10300_store_return_value(), mt_pseudo_register_write(), mt_select_coprocessor(), regcache_cooked_write(), regcache_raw_read_part(), regcache_raw_write_part(), regcache_raw_write_signed(), regcache_raw_write_unsigned(), rl78_pseudo_register_write(), sh64_pseudo_register_write(), sh64_store_return_value(), sh_pseudo_register_write(), sh_store_return_value_fpu(), sh_store_return_value_nofpu(), sparc32_pseudo_register_write(), sparc64_pseudo_register_write(), spu_pseudo_register_write(), tilegx_store_return_value(), v850_store_return_value(), vsx_pseudo_register_write(), xstormy16_store_return_value(), xtensa_pseudo_register_write(), and xtensa_store_return_value().
void regcache_raw_write_part (struct regcache * regcache, int regnum, int offset, int len, const gdb_byte * buf)
Definition at line 957 of file regcache.c.
References regcache::descr, gdb_assert, regcache_descr::nr_raw_registers, regcache_raw_read(), regcache_raw_write(), and regcache_xfer_part().
Referenced by amd64_push_arguments(), amd64_return_value(), amd64_windows_return_value(), efpr_pseudo_register_write(), i386_store_return_value(), m68hc11_store_return_value(), m68k_store_return_value(), mips_pseudo_register_write(), mn10300_store_return_value(), and xtensa_store_return_value().
void regcache_raw_write_signed (struct regcache * regcache, int regnum, LONGEST val)
Definition at line 672 of file regcache.c.
References regcache::descr, gdb_assert, regcache_descr::gdbarch, gdbarch_byte_order(), regcache_raw_write(), regcache_descr::sizeof_register, and store_signed_integer().
Referenced by mips_pseudo_register_write(), rs6000_lynx178_push_dummy_call(), and rs6000_push_dummy_call().
void regcache_raw_write_unsigned (struct regcache * regcache, int regnum, ULONGEST val)
Definition at line 685 of file regcache.c.
References regcache::descr, gdb_assert, regcache_descr::gdbarch, gdbarch_byte_order(), regcache_raw_write(), regcache_descr::sizeof_register, and store_unsigned_integer().
Referenced by amd64_push_arguments(), amd64_return_value(), avr_pseudo_register_write(), i386_store_return_value(), i387_return_value(), m88k_push_dummy_call(), mep_pseudo_csr_write(), msp430_pseudo_register_write(), rs6000_lynx178_push_dummy_call(), rs6000_push_dummy_call(), s390_pseudo_register_write(), sparc64_pseudo_register_write(), and xtensa_write_register().
CORE_ADDR regcache_read_pc (struct regcache * regcache)
Definition at line 1039 of file regcache.c.
References _, gdbarch_addr_bits_remove(), gdbarch_pc_regnum(), gdbarch_read_pc(), gdbarch_read_pc_p(), get_regcache_arch(), internal_error(), NOT_AVAILABLE_ERROR, REG_UNAVAILABLE, regcache_cooked_read_unsigned(), throw_error(), and ULONGEST.
Referenced by adjust_pc_after_break(), aix_thread_wait(), cancel_breakpoint(), check_event(), darwin_solib_get_all_image_info_addr_at_init(), displaced_step_fixup(), displaced_step_prepare(), enable_break(), exec_one_dummy_insn(), fork_load_infrun_state(), gdb_loc(), get_traceframe_location(), handle_inferior_event(), handle_syscall_event(), hppa_hpux_push_dummy_code(), i386_skip_permanent_breakpoint(), ia64_hpux_at_dld_breakpoint_1_p(), ia64_hpux_move_pc_to_next_bundle(), info_checkpoints_command(), keep_going(), m32r_resume(), parse_spufs_run(), post_create_inferior(), prepare_to_proceed(), proceed(), procfs_wait(), record_full_message(), record_full_wait_1(), resume(), resume_stopped_resumed_lwps(), run_command_1(), s390_displaced_step_fixup(), save_bookmark_command(), svr4_handle_solib_event(), switch_to_thread(), trace_find_pc_command(), and VEC().
enum register_status regcache_register_status (const struct regcache * regcache, int regnum)
Definition at line 415 of file regcache.c.
References regcache::descr, gdb_assert, regcache_descr::nr_cooked_registers, regcache_descr::nr_raw_registers, regcache::readonly_p, regcache::register_status, and regnum.
Referenced by fill_fprs(), fill_gprs32(), fill_gprs64(), fill_sprs32(), fill_sprs64(), get_core_registers(), gnu_store_registers(), regcache_dump(), regcache_raw_read(), regcache_raw_write(), store_fpregister(), store_fpregs(), store_fpregs_to_thread(), store_gregs_to_thread(), store_register(), store_regs(), store_regs_kernel_thread(), store_regs_user_thread(), store_wmmx_regs(), and tfile_fetch_registers().
void regcache_save (struct regcache * dst, regcache_cooked_read_ftype * cooked_read, void * cooked_read_context)
Definition at line 294 of file regcache.c.
References regcache::descr, gdb_assert, regcache_descr::gdbarch, gdbarch_register_reggroup_p(), MAX_REGISTER_SIZE, memcpy(), memset(), regcache_descr::nr_cooked_registers, regcache::readonly_p, REG_UNKNOWN, REG_VALID, register_buffer(), register_size(), regcache::register_status, regcache::registers, regnum, save_reggroup, regcache_descr::sizeof_cooked_register_status, regcache_descr::sizeof_cooked_registers, and exsummary::status.
Referenced by frame_save_as_regcache(), ppu2spu_sniffer(), and regcache_cpy().
void regcache_write_pc (struct regcache * regcache, CORE_ADDR pc)
Definition at line 1066 of file regcache.c.
References _, gdbarch_pc_regnum(), gdbarch_write_pc(), gdbarch_write_pc_p(), get_regcache_arch(), internal_error(), regcache_cooked_write_unsigned(), and reinit_frame_cache().
Referenced by adjust_pc_after_break(), cancel_breakpoint(), displaced_step_fixup(), displaced_step_prepare(), exec_one_dummy_insn(), generic_load(), handle_inferior_event(), i386_skip_permanent_breakpoint(), m32r_create_inferior(), m32r_load(), m32r_upload_command(), monitor_create_inferior(), monitor_load(), proceed(), record_full_wait_1(), and s390_displaced_step_fixup().
void regcache_xfree (struct regcache * regcache)
Definition at line 250 of file regcache.c.
References regcache::register_status, regcache::registers, and xfree().
Referenced by clear_proceed_status(), discard_infcall_suspend_state(), do_regcache_xfree(), fork_save_infrun_state(), free_fork(), normal_stop(), ppu2spu_dealloc_cache(), registers_changed_ptid(), and spu2ppu_dealloc_cache().
struct regcache* regcache_xmalloc (struct gdbarch * gdbarch, struct address_space * aspace) [read]
Definition at line 244 of file regcache.c.
References regcache_xmalloc_1().
Referenced by call_function_by_hand(), frame_save_as_regcache(), ppu2spu_sniffer(), and regcache_dup().
int register_size (struct gdbarch * gdbarch, int regnum)
Definition at line 172 of file regcache.c.
References gdb_assert, gdbarch_num_pseudo_regs(), gdbarch_num_regs(), regcache_descr(), regnum, size, and regcache_descr::sizeof_register.
Referenced by alpha_register_to_value(), check_for_saved(), collect_symbol(), debug_print_register(), default_value_from_register(), efpr_pseudo_register_read(), efpr_pseudo_register_write(), execute_cfa_program(), fetch_altivec_register(), fetch_register(), fetch_spe_register(), fetch_vsx_register(), fill_gregset(), fill_sprs32(), fill_sprs64(), fill_vrregset(), fill_vsxregset(), frame_info(), frame_unwind_got_bytes(), frame_unwind_got_constant(), frame_unwind_register_signed(), frame_unwind_register_unsigned(), frame_unwind_register_value(), gdbsim_fetch_register(), gdbsim_store_register(), get_frame_register_bytes(), get_register(), get_register_size(), gnu_store_registers(), hppa_frame_prev_register_helper(), hppa_hpux_fetch_register(), hppa_hpux_save_state_offset(), hppa_hpux_store_register(), hppa_hpux_supply_save_state(), hppa_hpux_supply_ss_fpblock(), hppa_hpux_supply_ss_wide(), hppa_hpux_unwind_adjust_stub(), i386_extract_return_value(), i386_fast_tracepoint_valid_at(), i386_pseudo_register_read_into_value(), i386_pseudo_register_write(), i386_register_to_value(), i386_store_return_value(), i386_value_to_register(), ia64_frame_prev_register(), ia64_hpux_fetch_register(), ia64_hpux_store_register(), ia64_linux_fetch_register(), ia64_linux_store_register(), ia64_pseudo_register_read(), ia64_pseudo_register_write(), ia64_register_to_value(), ia64_sigtramp_frame_prev_register(), inf_ptrace_fetch_register(), inf_ptrace_store_register(), jit_unwind_reg_get_impl(), libunwind_get_reg_special(), m32c_prev_register(), m32r_push_dummy_call(), map_regcache_remote_table(), mep_pseudo_csr_write(), mips2_fp_compat(), mips64_fill_fpregset(), mips64_fill_gregset(), mips64_supply_fpregset(), mips_ax_pseudo_register_push_stack(), mips_convert_register_float_case_p(), mips_convert_register_gpreg_case_p(), mips_linux_get_syscall_number(), mips_linux_restart_reg_p(), mips_n32n64_return_value(), mips_o32_push_dummy_call(), mips_o32_return_value(), mips_print_fp_register(), mips_pseudo_register_read(), mips_pseudo_register_write(), mips_read_fp_register_double(), mips_read_fp_register_single(), mips_xfer_register(), mn10300_extract_return_value(), mn10300_frame_prev_register(), mn10300_push_dummy_call(), mn10300_store_return_value(), monitor_fetch_register(), monitor_store_register(), monitor_supply_register(), msp430_pseudo_register_read(), msp430_pseudo_register_write(), mt_registers_info(), nios2_extract_return_value(), nios2_store_return_value(), pd_enable(), ppc64_sysv_abi_return_value(), ppc_collect_reg(), ppc_linux_trap_reg_p(), ppc_ravenscar_generic_store_registers(), ppc_register_u_addr(), ppc_supply_reg(), ppu2spu_prev_register(), print_gp_register_row(), pseudo_register_read_portions(), put_frame_register(), put_frame_register_bytes(), pv_area_find_reg(), read_frame_register_unsigned(), read_frame_register_value(), read_pieced_value(), read_reg(), record_full_reg_alloc(), regcache_save(), register_changed_p(), remote_parse_stop_reply(), rs6000_frame_cache(), rs6000_lynx178_push_dummy_call(), rs6000_push_dummy_call(), rs6000_register_to_value(), rx_frame_prev_register(), s390_displaced_step_fixup(), s390_pseudo_register_read(), s390_pseudo_register_write(), s390_write_pc(), sh64_do_fp_register(), sh64_extract_return_value(), sh64_pseudo_register_write(), sh64_push_dummy_call(), sh64_register_convert_to_raw(), sh64_register_convert_to_virtual(), sh64_store_return_value(), sh_pseudo_register_write(), sh_push_dummy_call_fpu(), sh_push_dummy_call_nofpu(), sh_register_convert_to_raw(), sh_register_convert_to_virtual(), sparc_ravenscar_store_registers(), spu2ppu_prev_register(), store_altivec_register(), store_register(), store_register_using_P(), store_spe_register(), store_vsx_register(), supply_32bit_reg(), supply_64bit_reg(), supply_register_at_address(), supply_vrregset(), supply_vsxregset(), tfile_fetch_registers(), value_fetch_lazy(), and write_pieced_value().
struct type* register_type (struct gdbarch * gdbarch, int regnum) [read]
Definition at line 160 of file regcache.c.
References gdb_assert, regcache_descr::nr_cooked_registers, regcache_descr(), regcache_descr::register_type, and regnum.
Referenced by aarch64_pseudo_read_value(), amd64_gen_return_address(), amd64_pseudo_register_read_value(), check_for_saved(), default_register_reggroup_p(), do_ppc_sysv_return_value(), dummy_frame_prev_register(), evaluate_subexp_standard(), frame_unwind_got_address(), frame_unwind_got_bytes(), frame_unwind_got_constant(), frame_unwind_got_memory(), frame_unwind_got_optimized(), gen_expr(), get_register(), get_register_types(), i386_gen_return_address(), i386_pseudo_register_read_value(), ia64_extract_return_value(), ia64_register_reggroup_p(), ia64_store_return_value(), m68k_convert_register_p(), m68k_register_to_value(), m68k_svr4_extract_return_value(), m68k_svr4_store_return_value(), m68k_value_to_register(), mep_pseudo_cr32_read(), mep_pseudo_cr32_write(), mips_register_reggroup_p(), mt_registers_info(), ppc64_sysv_abi_push_dummy_call(), ppc64_sysv_abi_push_float(), ppc64_sysv_abi_return_value(), ppc_sysv_abi_push_dummy_call(), read_reg(), regcache_cooked_read_value(), regcache_dump(), rs6000_lynx178_push_dummy_call(), rs6000_lynx178_return_value(), rs6000_push_dummy_call(), rs6000_return_value(), s390_unwind_pseudo_register(), set_gdbarch_register_type(), sh64_do_register(), sh64_media_print_registers_info(), sh64_print_register(), sh64_pseudo_register_read(), sh64_pseudo_register_write(), sh_pseudo_register_read(), sh_pseudo_register_write(), and value_of_register_lazy().
void registers_changed (void)
Definition at line 586 of file regcache.c.
References minus_one_ptid, and registers_changed_ptid().
Referenced by core_open(), fork_load_infrun_state(), generic_mourn_inferior(), linux_handle_syscall_trap(), linux_nat_filter_event(), linux_nat_switch_fork(), linux_nat_wait_1(), record_full_goto_entry(), record_full_wait_1(), reg_flush_command(), regcache_observer_target_changed(), resume_stopped_resumed_lwps(), set_current_traceframe(), set_target_gdbarch(), simulator_command(), spu_multiarch_activate(), spu_multiarch_deactivate(), and windows_stop().
void registers_changed_ptid (ptid_t)
Definition at line 548 of file regcache.c.
References current_regcache, inferior_ptid, regcache_list::next, null_ptid, regcache::ptid, ptid_match(), regcache_list::regcache, regcache_xfree(), reinit_frame_cache(), and xfree().
Referenced by registers_changed(), and target_resume().