GDB (xrefs): /home/stan/gdb/src/gdb/regset.c File Reference
/home/stan/gdb/src/gdb/regset.c File Reference
#include "defs.h"
#include "regset.h"
#include "gdb_assert.h"
Functions
struct regset * regset_alloc (struct gdbarch *arch, supply_regset_ftype *supply_regset, collect_regset_ftype *collect_regset)
Function Documentation
struct regset* regset_alloc (struct gdbarch * arch, supply_regset_ftype * supply_regset, collect_regset_ftype * collect_regset) [read]
Definition at line 33 of file regset.c.
References regset::arch, regset::collect_regset, GDBARCH_OBSTACK_ZALLOC, and regset::supply_regset.
Referenced by aarch64_linux_regset_from_core_section(), am33_regset_from_core_section(), amd64_regset_from_core_section(), amd64obsd_regset_from_core_section(), arm_linux_regset_from_core_section(), i386_regset_from_core_section(), i386_windows_regset_from_core_section(), i386nto_supply_gregset(), i386obsd_aout_regset_from_core_section(), mips_linux_regset_from_core_section(), score7_linux_regset_from_core_section(), sparc32_linux_init_abi(), sparc32nbsd_init_abi(), sparc64_linux_init_abi(), sparc64fbsd_init_abi(), sparc64nbsd_init_abi(), and sparc64obsd_init_abi().