GDB (xrefs): /home/stan/gdb/src/gdb/remote-fileio.h File Reference
/home/stan/gdb/src/gdb/remote-fileio.h File Reference
Functions
void remote_fileio_request (char *buf, int ctrlc_pending_p)
void remote_fileio_reset (void)
void initialize_remote_fileio (struct cmd_list_element *remote_set_cmdlist, struct cmd_list_element *remote_show_cmdlist)
Function Documentation
void initialize_remote_fileio (struct cmd_list_element * remote_set_cmdlist, struct cmd_list_element * remote_show_cmdlist)
Definition at line 1466 of file remote-fileio.c.
References _, add_cmd(), async_remote_fileio_interrupt(), create_async_signal_handler(), no_class, set_system_call_allowed(), and show_system_call_allowed().
void remote_fileio_request (char * buf, int ctrlc_pending_p)
Definition at line 1399 of file remote-fileio.c.
References catch_exceptions(), current_uiout, do_remote_fileio_request(), remote_fileio_reply(), remote_fileio_sig_exit(), remote_fileio_sig_init(), remote_fio_ctrl_c_flag, remote_fio_no_longjmp, RETURN_ERROR, RETURN_MASK_ALL, and RETURN_QUIT.
Referenced by remote_wait_as().
void remote_fileio_reset (void)
Definition at line 1375 of file remote-fileio.c.
References remote_fio_data, and xfree().
Referenced by extended_remote_restart(), and remote_open_1().