GDB (xrefs): /home/stan/gdb/src/gdb/remote-notif.c File Reference
/home/stan/gdb/src/gdb/remote-notif.c File Reference
#include "defs.h"
#include "remote.h"
#include "remote-notif.h"
#include "observer.h"
#include "event-loop.h"
#include "target.h"
#include "inferior.h"
#include "gdbcmd.h"
#include <string.h>
Functions
gdb_static_assert (ARRAY_SIZE(notifs)==REMOTE_NOTIF_LAST)
static void do_notif_event_xfree (void *arg)
void remote_notif_ack (struct notif_client *nc, char *buf)
struct notif_event * remote_notif_parse (struct notif_client *nc, char *buf)
DEFINE_QUEUE_P (notif_client_p)
void remote_notif_process (struct remote_notif_state *state, struct notif_client *except)
static void remote_async_get_pending_events_handler (gdb_client_data data)
void handle_notification (struct remote_notif_state *state, char *buf)
void notif_event_xfree (struct notif_event *event)
struct remote_notif_state * remote_notif_state_allocate (void)
void remote_notif_state_xfree (struct remote_notif_state *state)
void _initialize_notif (void)
Variables
int notif_debug = 0
static struct notif_client * notifs []
initialize_file_ftype _initialize_notif
Function Documentation
void _initialize_notif (void)
Definition at line 275 of file remote-notif.c.
References _, add_setshow_boolean_cmd(), no_class, notif_debug, setdebuglist, and showdebuglist.
DEFINE_QUEUE_P (notif_client_p)
static void do_notif_event_xfree (void * arg) [static]
Definition at line 229 of file remote-notif.c.
References notif_event_xfree().
Referenced by remote_notif_ack(), and remote_notif_parse().
gdb_static_assert (ARRAY_SIZE(notifs) = =REMOTE_NOTIF_LAST)
void handle_notification (struct remote_notif_state * state, char * buf)
Definition at line 128 of file remote-notif.c.
References fprintf_unfiltered(), gdb_stdlog, remote_notif_state::get_pending_events_token, notif_client::id, mark_async_event_handler(), notif_client::name, non_stop, notif_debug, remote_notif_state::pending_event, QUEUE_enque, and remote_notif_parse().
Referenced by getpkt_or_notif_sane_1(), and putpkt_binary().
void notif_event_xfree (struct notif_event * event)
Definition at line 218 of file remote-notif.c.
References notif_event::dtr, and xfree().
Referenced by do_notif_event_xfree(), QUEUE(), and remote_notif_state_xfree().
static void remote_async_get_pending_events_handler (gdb_client_data data) [static]
Definition at line 118 of file remote-notif.c.
References gdb_assert, non_stop, and remote_notif_process().
Referenced by remote_notif_state_allocate().
void remote_notif_ack (struct notif_client * nc, char * buf)
Definition at line 62 of file remote-notif.c.
References notif_client::ack, notif_client::ack_command, notif_client::alloc_event, discard_cleanups(), do_notif_event_xfree(), fprintf_unfiltered(), gdb_stdlog, make_cleanup(), notif_debug, and notif_client::parse.
Referenced by remote_notif_get_pending_events().
struct notif_event* remote_notif_parse (struct notif_client * nc, char * buf) [read]
Definition at line 81 of file remote-notif.c.
References notif_client::alloc_event, discard_cleanups(), do_notif_event_xfree(), fprintf_unfiltered(), gdb_stdlog, make_cleanup(), notif_client::name, notif_debug, and notif_client::parse.
Referenced by extended_remote_attach_1(), handle_notification(), remote_start_remote(), and remote_wait_as().
void remote_notif_process (struct remote_notif_state * state, struct notif_client * except)
Definition at line 102 of file remote-notif.c.
References notif_client::can_get_pending_events, gdb_assert, QUEUE_deque, QUEUE_is_empty, and remote_notif_get_pending_events().
Referenced by remote_async_get_pending_events_handler(), and remote_resume().
struct remote_notif_state* remote_notif_state_allocate (void) [read]
Definition at line 237 of file remote-notif.c.
References create_async_event_handler(), remote_notif_state::get_pending_events_token, QUEUE_alloc, remote_async_get_pending_events_handler(), and xzalloc().
Referenced by remote_open_1().
void remote_notif_state_xfree (struct remote_notif_state * state)
Definition at line 255 of file remote-notif.c.
References delete_async_event_handler(), remote_notif_state::get_pending_events_token, notif_event_xfree(), remote_notif_state::pending_event, QUEUE_free, REMOTE_NOTIF_LAST, and xfree().
Referenced by remote_close().
Variable Documentation
initialize_file_ftype _initialize_notif
Referenced by initialize_all_files().
int notif_debug = 0
Definition at line 45 of file remote-notif.c.
Referenced by _initialize_notif(), handle_notification(), push_stop_reply(), remote_notif_ack(), remote_notif_get_pending_events(), remote_notif_parse(), and remote_notif_remove_queued_reply().
struct notif_client* notifs[] [static]
Initial value:
{
  &notif_client_stop,
}
Definition at line 49 of file remote-notif.c.