GDB (xrefs): /home/stan/gdb/src/gdb/remote.c File Reference
/home/stan/gdb/src/gdb/remote.c File Reference
#include "defs.h"
#include "gdb_string.h"
#include <ctype.h>
#include <fcntl.h>
#include "inferior.h"
#include "bfd.h"
#include "symfile.h"
#include "exceptions.h"
#include "target.h"
#include "gdbcmd.h"
#include "objfiles.h"
#include "gdb-stabs.h"
#include "gdbthread.h"
#include "remote.h"
#include "remote-notif.h"
#include "regcache.h"
#include "value.h"
#include "gdb_assert.h"
#include "observer.h"
#include "solib.h"
#include "cli/cli-decode.h"
#include "cli/cli-setshow.h"
#include "target-descriptions.h"
#include "gdb_bfd.h"
#include "filestuff.h"
#include <sys/time.h>
#include "event-loop.h"
#include "event-top.h"
#include "inf-loop.h"
#include <signal.h>
#include "serial.h"
#include "gdbcore.h"
#include "remote-fileio.h"
#include "gdb/fileio.h"
#include "gdb_stat.h"
#include "xml-support.h"
#include "memory-map.h"
#include "tracepoint.h"
#include "ax.h"
#include "ax-gdb.h"
#include "agent.h"
#include "btrace.h"
Classes
struct vCont_action_support
struct remote_state
struct private_thread_info
struct packet_reg
struct remote_arch_state
struct memory_packet_config
struct packet_config
struct gdb_ext_thread_info
struct protocol_feature
struct cached_reg
struct stop_reply
struct queue_iter_param
struct remote_g_packet_guess
struct remote_g_packet_data
struct btrace_target_info
Defines
#define OPAQUETHREADBYTES 8
#define MAXTHREADLISTRESULTS 32
#define MAX_REMOTE_PACKET_SIZE 16384
#define MIN_REMOTE_PACKET_SIZE 20
#define TAG_THREADID 1
#define TAG_EXISTS 2
#define TAG_DISPLAY 4
#define TAG_THREADNAME 8
#define TAG_MOREDISPLAY 16
#define BUF_THREAD_ID_SIZE (OPAQUETHREADBYTES * 2)
#define TAG_THREADID 1 /* Echo the thread identifier. */
#define TAG_EXISTS
#define TAG_DISPLAY 4 /* A short thing maybe to put on a window */
#define TAG_THREADNAME 8 /* string, maps 1-to-1 with a thread is. */
#define TAG_MOREDISPLAY
#define CRAZY_MAX_THREADS 1000
#define MAX_TRIES 3
#define BUF_SIZE 2048
Typedefs
typedef unsigned char threadref [OPAQUETHREADBYTES]
typedef int gdb_threadref
typedef int(* rmt_thread_action)(threadref *ref, void *context)
typedef struct cached_reg cached_reg_t
typedef struct stop_reply * stop_reply_p
typedef struct
remote_g_packet_guess remote_g_packet_guess_s
Enumerations
enum { REMOTE_ALIGN_WRITES = 16 }
enum packet_support { PACKET_SUPPORT_UNKNOWN = 0, PACKET_ENABLE, PACKET_DISABLE }
enum packet_result { PACKET_ERROR, PACKET_OK, PACKET_UNKNOWN }
enum {
PACKET_vCont = 0, PACKET_X, PACKET_qSymbol, PACKET_P,
PACKET_p, PACKET_Z0, PACKET_Z1, PACKET_Z2,
PACKET_Z3, PACKET_Z4, PACKET_vFile_open, PACKET_vFile_pread,
PACKET_vFile_pwrite, PACKET_vFile_close, PACKET_vFile_unlink, PACKET_vFile_readlink,
PACKET_qXfer_auxv, PACKET_qXfer_features, PACKET_qXfer_libraries, PACKET_qXfer_libraries_svr4,
PACKET_qXfer_memory_map, PACKET_qXfer_spu_read, PACKET_qXfer_spu_write, PACKET_qXfer_osdata,
PACKET_qXfer_threads, PACKET_qXfer_statictrace_read, PACKET_qXfer_traceframe_info, PACKET_qXfer_uib,
PACKET_qGetTIBAddr, PACKET_qGetTLSAddr, PACKET_qSupported, PACKET_qTStatus,
PACKET_QPassSignals, PACKET_QProgramSignals, PACKET_qSearch_memory, PACKET_vAttach,
PACKET_vRun, PACKET_QStartNoAckMode, PACKET_vKill, PACKET_qXfer_siginfo_read,
PACKET_qXfer_siginfo_write, PACKET_qAttached, PACKET_ConditionalTracepoints, PACKET_ConditionalBreakpoints,
PACKET_BreakpointCommands, PACKET_FastTracepoints, PACKET_StaticTracepoints, PACKET_InstallInTrace,
PACKET_bc, PACKET_bs, PACKET_TracepointSource, PACKET_QAllow,
PACKET_qXfer_fdpic, PACKET_QDisableRandomization, PACKET_QAgent, PACKET_QTBuffer_size,
PACKET_Qbtrace_off, PACKET_Qbtrace_bts, PACKET_qXfer_btrace, PACKET_MAX
}
enum Z_packet_type {
Z_PACKET_SOFTWARE_BP, Z_PACKET_HARDWARE_BP, Z_PACKET_WRITE_WP, Z_PACKET_READ_WP,
Z_PACKET_ACCESS_WP, NR_Z_PACKET_TYPES
}
Functions
static void async_cleanup_sigint_signal_handler (void *dummy)
static int getpkt_sane (char **buf, long *sizeof_buf, int forever)
static int getpkt_or_notif_sane (char **buf, long *sizeof_buf, int forever, int *is_notif)
static void async_handle_remote_sigint (int)
static void async_handle_remote_sigint_twice (int)
static void remote_files_info (struct target_ops *ignore)
static void remote_prepare_to_store (struct regcache *regcache)
static void remote_open (char *name, int from_tty)
static void extended_remote_open (char *name, int from_tty)
static void remote_open_1 (char *, int, struct target_ops *, int extended_p)
static void remote_close (void)
static void remote_mourn (struct target_ops *ops)
static void extended_remote_restart (void)
static void extended_remote_mourn (struct target_ops *)
static void remote_mourn_1 (struct target_ops *)
static void remote_send (char **buf, long *sizeof_buf_p)
static int readchar (int timeout)
static void remote_serial_write (const char *str, int len)
static void remote_kill (struct target_ops *ops)
static int tohex (int nib)
static int remote_can_async_p (void)
static int remote_is_async_p (void)
static void remote_async (void(*callback)(enum inferior_event_type event_type, void *context), void *context)
static void remote_detach (struct target_ops *ops, char *args, int from_tty)
static void sync_remote_interrupt_twice (int signo)
static void interrupt_query (void)
static void set_general_thread (struct ptid ptid)
static void set_continue_thread (struct ptid ptid)
static void get_offsets (void)
static void skip_frame (void)
static long read_frame (char **buf_p, long *sizeof_buf)
static int hexnumlen (ULONGEST num)
static void init_remote_ops (void)
static void init_extended_remote_ops (void)
static void remote_stop (ptid_t)
static int ishex (int ch, int *val)
static int stubhex (int ch)
static int hexnumstr (char *, ULONGEST)
static int hexnumnstr (char *, ULONGEST, int)
static CORE_ADDR remote_address_masked (CORE_ADDR)
static void print_packet (char *)
static void compare_sections_command (char *, int)
static void packet_command (char *, int)
static int stub_unpack_int (char *buff, int fieldlength)
static ptid_t remote_current_thread (ptid_t oldptid)
static void remote_find_new_threads (void)
static int fromhex (int a)
static int putpkt_binary (char *buf, int cnt)
static void check_binary_download (CORE_ADDR addr)
static void show_packet_config_cmd (struct packet_config *config)
static void update_packet_config (struct packet_config *config)
static void set_remote_protocol_packet_cmd (char *args, int from_tty, struct cmd_list_element *c)
static void show_remote_protocol_packet_cmd (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static char * write_ptid (char *buf, const char *endbuf, ptid_t ptid)
static ptid_t read_ptid (char *buf, char **obuf)
static void remote_set_permissions (void)
static int remote_get_trace_status (struct trace_status *ts)
static int remote_upload_tracepoints (struct uploaded_tp **utpp)
static int remote_upload_trace_state_variables (struct uploaded_tsv **utsvp)
static void remote_query_supported (void)
static void remote_check_symbols (void)
void _initialize_remote (void)
static void stop_reply_xfree (struct stop_reply *)
static void remote_parse_stop_reply (char *, struct stop_reply *)
static void push_stop_reply (struct stop_reply *)
static void discard_pending_stop_replies_in_queue (struct remote_state *)
static int peek_stop_reply (ptid_t ptid)
static void remote_async_inferior_event_handler (gdb_client_data)
static void remote_terminal_ours (void)
static int remote_read_description_p (struct target_ops *target)
static void remote_console_output (char *msg)
static int remote_supports_cond_breakpoints (void)
static int remote_can_run_breakpoint_commands (void)
static void free_private_thread_info (struct private_thread_info *info)
static int remote_multi_process_p (struct remote_state *rs)
static struct remote_state * get_remote_state_raw (void)
static struct remote_state * new_remote_state (void)
static void trace_error (char *buf)
static char * remote_get_noisy_reply (char **buf_p, long *sizeof_buf)
static struct remote_arch_state * get_remote_arch_state (void)
static struct remote_state * get_remote_state (void)
static int compare_pnums (const void *lhs_, const void *rhs_)
static int map_regcache_remote_table (struct gdbarch *gdbarch, struct packet_reg *regs)
int remote_register_number_and_offset (struct gdbarch *gdbarch, int regnum, int *pnum, int *poffset)
static void * init_remote_state (struct gdbarch *gdbarch)
static long get_remote_packet_size (void)
static struct packet_reg * packet_reg_from_regnum (struct remote_arch_state *rsa, long regnum)
static struct packet_reg * packet_reg_from_pnum (struct remote_arch_state *rsa, LONGEST pnum)
static void show_interrupt_sequence (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static void set_remotebreak (char *args, int from_tty, struct cmd_list_element *c)
static void show_remotebreak (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static long get_memory_packet_size (struct memory_packet_config *config)
static void set_memory_packet_size (char *args, struct memory_packet_config *config)
static void show_memory_packet_size (struct memory_packet_config *config)
static void set_memory_write_packet_size (char *args, int from_tty)
static void show_memory_write_packet_size (char *args, int from_tty)
static long get_memory_write_packet_size (void)
static void set_memory_read_packet_size (char *args, int from_tty)
static void show_memory_read_packet_size (char *args, int from_tty)
static long get_memory_read_packet_size (void)
static void add_packet_config_cmd (struct packet_config *config, const char *name, const char *title, int legacy)
static enum packet_result packet_check_result (const char *buf)
static enum packet_result packet_ok (const char *buf, struct packet_config *config)
static void set_remote_protocol_Z_packet_cmd (char *args, int from_tty, struct cmd_list_element *c)
static void show_remote_protocol_Z_packet_cmd (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static int remote_query_attached (int pid)
static struct inferior * remote_add_inferior (int fake_pid_p, int pid, int attached)
static void remote_add_thread (ptid_t ptid, int running)
static void remote_notice_new_inferior (ptid_t currthread, int running)
static struct private_thread_info * demand_private_info (ptid_t ptid)
static void record_currthread (struct remote_state *rs, ptid_t currthread)
static void remote_pass_signals (int numsigs, unsigned char *pass_signals)
static void remote_program_signals (int numsigs, unsigned char *signals)
static void set_thread (struct ptid ptid, int gen)
static void set_general_thread (struct ptid ptid)
static void set_continue_thread (struct ptid ptid)
static void set_general_process (void)
static int remote_thread_alive (struct target_ops *ops, ptid_t ptid)
char * unpack_varlen_hex (char *buff, ULONGEST *result)
static char * unpack_nibble (char *buf, int *val)
static char * pack_nibble (char *buf, int nibble)
static char * pack_hex_byte (char *pkt, intbyte)
static char * unpack_byte (char *buf, int *value)
static char * pack_int (char *buf, int value)
static char * unpack_int (char *buf, int *value)
static char * unpack_string (char *src, char *dest, int length)
static char * pack_threadid (char *pkt, threadref *id)
static char * unpack_threadid (char *inbuf, threadref *id)
void int_to_threadref (threadref *id, int value)
static int threadref_to_int (threadref *ref)
static void copy_threadref (threadref *dest, threadref *src)
static int threadmatch (threadref *dest, threadref *src)
static char * pack_threadinfo_request (char *pkt, int mode, threadref *id)
static int remote_unpack_thread_info_response (char *pkt, threadref *expectedref, struct gdb_ext_thread_info *info)
static int remote_get_threadinfo (threadref *threadid, int fieldset, struct gdb_ext_thread_info *info)
static char * pack_threadlist_request (char *pkt, int startflag, int threadcount, threadref *nextthread)
static int parse_threadlist_response (char *pkt, int result_limit, threadref *original_echo, threadref *resultlist, int *doneflag)
static int remote_get_threadlist (int startflag, threadref *nextthread, int result_limit, int *done, int *result_count, threadref *threadlist)
static int remote_threadlist_iterator (rmt_thread_action stepfunction, void *context, int looplimit)
static int remote_newthread_step (threadref *ref, void *context)
static void remote_threads_info (struct target_ops *ops)
static char * remote_threads_extra_info (struct thread_info *tp)
static int remote_static_tracepoint_marker_at (CORE_ADDR addr, struct static_tracepoint_marker *marker)
static VEC (static_tracepoint_marker_p)
static ptid_t remote_get_ada_task_ptid (long lwp, long thread)
static int set_stop_requested_callback (struct thread_info *thread, void *data)
static void send_interrupt_sequence (void)
static ptid_t stop_reply_extract_thread (char *stop_reply)
static void add_current_inferior_and_thread (char *wait_status)
static void remote_start_remote (int from_tty, struct target_ops *target, int extended_p)
static void init_all_packet_configs (void)
static struct serial * remote_serial_open (char *name)
static void remote_supported_packet (const struct protocol_feature *feature, enum packet_support support, const char *argument)
static void remote_packet_size (const struct protocol_feature *feature, enum packet_support support, const char *value)
static void remote_multi_process_feature (const struct protocol_feature *feature, enum packet_support support, const char *value)
static void remote_non_stop_feature (const struct protocol_feature *feature, enum packet_support support, const char *value)
static void remote_cond_tracepoint_feature (const struct protocol_feature *feature, enum packet_support support, const char *value)
static void remote_cond_breakpoint_feature (const struct protocol_feature *feature, enum packet_support support, const char *value)
static void remote_breakpoint_commands_feature (const struct protocol_feature *feature, enum packet_support support, const char *value)
static void remote_fast_tracepoint_feature (const struct protocol_feature *feature, enum packet_support support, const char *value)
static void remote_static_tracepoint_feature (const struct protocol_feature *feature, enum packet_support support, const char *value)
static void remote_install_in_trace_feature (const struct protocol_feature *feature, enum packet_support support, const char *value)
static void remote_disconnected_tracing_feature (const struct protocol_feature *feature, enum packet_support support, const char *value)
static void remote_enable_disable_tracepoint_feature (const struct protocol_feature *feature, enum packet_support support, const char *value)
static void remote_string_tracing_feature (const struct protocol_feature *feature, enum packet_support support, const char *value)
static void remote_augmented_libraries_svr4_read_feature (const struct protocol_feature *feature, enum packet_support support, const char *value)
void register_remote_support_xml (const char *xml)
static char * remote_query_supported_append (char *msg, const char *append)
static void remote_unpush_target (void)
static void remote_detach_1 (char *args, int from_tty, int extended)
static void extended_remote_detach (struct target_ops *ops, char *args, int from_tty)
static void remote_disconnect (struct target_ops *target, char *args, int from_tty)
static void extended_remote_attach_1 (struct target_ops *target, char *args, int from_tty)
static void extended_remote_attach (struct target_ops *ops, char *args, int from_tty)
int hex2bin (const char *hex, gdb_byte *bin, int count)
int bin2hex (const gdb_byte *bin, char *hex, int count)
static void remote_vcont_probe (struct remote_state *rs)
static char * append_resumption (char *p, char *endp, ptid_t ptid, int step, enum gdb_signal siggnal)
static char * append_pending_thread_resumptions (char *p, char *endp, ptid_t ptid)
static int remote_vcont_resume (ptid_t ptid, int step, enum gdb_signal siggnal)
static void remote_resume (struct target_ops *ops, ptid_t ptid, int step, enum gdb_signal siggnal)
static void async_initialize_sigint_signal_handler (void)
static void async_remote_interrupt (gdb_client_data arg)
static void async_remote_interrupt_twice (gdb_client_data arg)
static void sync_remote_interrupt (int signo)
static void remote_stop_ns (ptid_t ptid)
static void remote_stop_as (ptid_t ptid)
static void remote_terminal_inferior (void)
DEF_VEC_O (cached_reg_t)
DECLARE_QUEUE_P (stop_reply_p)
DEFINE_QUEUE_P (stop_reply_p)
static QUEUE (stop_reply_p)
static void remote_notif_stop_parse (struct notif_client *self, char *buf, struct notif_event *event)
static void remote_notif_stop_ack (struct notif_client *self, char *buf, struct notif_event *event)
static int remote_notif_stop_can_get_pending_events (struct notif_client *self)
static void stop_reply_dtr (struct notif_event *event)
static struct notif_event * remote_notif_stop_alloc_reply (void)
static int remove_stop_reply_for_inferior (QUEUE(stop_reply_p)*q, QUEUE_ITER(stop_reply_p)*iter, stop_reply_p event, void *data)
static void discard_pending_stop_replies (struct inferior *inf)
static int remove_stop_reply_of_remote_state (QUEUE(stop_reply_p)*q, QUEUE_ITER(stop_reply_p)*iter, stop_reply_p event, void *data)
static int remote_notif_remove_once_on_match (QUEUE(stop_reply_p)*q, QUEUE_ITER(stop_reply_p)*iter, stop_reply_p event, void *data)
static struct stop_reply * remote_notif_remove_queued_reply (ptid_t ptid)
static struct stop_reply * queued_stop_reply (ptid_t ptid)
static int stop_reply_match_ptid_and_ws (QUEUE(stop_reply_p)*q, QUEUE_ITER(stop_reply_p)*iter, struct stop_reply *event, void *data)
void remote_notif_get_pending_events (struct notif_client *nc)
static ptid_t process_stop_reply (struct stop_reply *stop_reply, struct target_waitstatus *status)
static ptid_t remote_wait_ns (ptid_t ptid, struct target_waitstatus *status, int options)
static ptid_t remote_wait_as (ptid_t ptid, struct target_waitstatus *status, int options)
static ptid_t remote_wait (struct target_ops *ops, ptid_t ptid, struct target_waitstatus *status, int options)
static int fetch_register_using_p (struct regcache *regcache, struct packet_reg *reg)
static int send_g_packet (void)
static void process_g_packet (struct regcache *regcache)
static void fetch_registers_using_g (struct regcache *regcache)
static void set_remote_traceframe (void)
static void remote_fetch_registers (struct target_ops *ops, struct regcache *regcache, int regnum)
static int store_register_using_P (const struct regcache *regcache, struct packet_reg *reg)
static void store_registers_using_G (const struct regcache *regcache)
static void remote_store_registers (struct target_ops *ops, struct regcache *regcache, int regnum)
static int remote_escape_output (const gdb_byte *buffer, int len, gdb_byte *out_buf, int *out_len, int out_maxlen)
static int remote_unescape_input (const gdb_byte *buffer, int len, gdb_byte *out_buf, int out_maxlen)
static LONGEST remote_write_bytes_aux (const char *header, CORE_ADDR memaddr, const gdb_byte *myaddr, ssize_t len, char packet_format, int use_length)
static LONGEST remote_write_bytes (CORE_ADDR memaddr, const gdb_byte *myaddr, ssize_t len)
static LONGEST remote_read_bytes (CORE_ADDR memaddr, gdb_byte *myaddr, int len)
static enum packet_result remote_send_printf (const char *format,...)
static void restore_remote_timeout (void *p)
static void remote_flash_erase (struct target_ops *ops, ULONGEST address, LONGEST length)
static LONGEST remote_flash_write (struct target_ops *ops, ULONGEST address, LONGEST length, const gdb_byte *data)
static void remote_flash_done (struct target_ops *ops)
static void unpush_and_perror (const char *string)
static char * escape_buffer (const char *buf, int n)
int putpkt (char *buf)
void getpkt (char **buf, long *sizeof_buf, int forever)
static int getpkt_or_notif_sane_1 (char **buf, long *sizeof_buf, int forever, int expecting_notif, int *is_notif)
static int putpkt_for_catch_errors (void *arg)
static int remote_vkill (int pid, struct remote_state *rs)
static void extended_remote_kill (struct target_ops *ops)
static void extended_remote_mourn_1 (struct target_ops *target)
static int extended_remote_supports_disable_randomization (void)
static void extended_remote_disable_randomization (int val)
static int extended_remote_run (char *args)
static void extended_remote_create_inferior_1 (char *exec_file, char *args, char **env, int from_tty)
static void extended_remote_create_inferior (struct target_ops *ops, char *exec_file, char *args, char **env, int from_tty)
static int remote_add_target_side_condition (struct gdbarch *gdbarch, struct bp_target_info *bp_tgt, char *buf, char *buf_end)
static void remote_add_target_side_commands (struct gdbarch *gdbarch, struct bp_target_info *bp_tgt, char *buf)
static int remote_insert_breakpoint (struct gdbarch *gdbarch, struct bp_target_info *bp_tgt)
static int remote_remove_breakpoint (struct gdbarch *gdbarch, struct bp_target_info *bp_tgt)
static int watchpoint_to_Z_packet (int type)
static int remote_insert_watchpoint (CORE_ADDR addr, int len, int type, struct expression *cond)
static int remote_watchpoint_addr_within_range (struct target_ops *target, CORE_ADDR addr, CORE_ADDR start, int length)
static int remote_remove_watchpoint (CORE_ADDR addr, int len, int type, struct expression *cond)
static int remote_region_ok_for_hw_watchpoint (CORE_ADDR addr, int len)
static int remote_check_watch_resources (int type, int cnt, int ot)
static int remote_stopped_by_watchpoint (void)
static int remote_stopped_data_address (struct target_ops *target, CORE_ADDR *addr_p)
static int remote_insert_hw_breakpoint (struct gdbarch *gdbarch, struct bp_target_info *bp_tgt)
static int remote_remove_hw_breakpoint (struct gdbarch *gdbarch, struct bp_target_info *bp_tgt)
static int remote_verify_memory (struct target_ops *ops, const gdb_byte *data, CORE_ADDR lma, ULONGEST size)
static LONGEST remote_write_qxfer (struct target_ops *ops, const char *object_name, const char *annex, const gdb_byte *writebuf, ULONGEST offset, LONGEST len, struct packet_config *packet)
static LONGEST remote_read_qxfer (struct target_ops *ops, const char *object_name, const char *annex, gdb_byte *readbuf, ULONGEST offset, LONGEST len, struct packet_config *packet)
static LONGEST remote_xfer_partial (struct target_ops *ops, enum target_object object, const char *annex, gdb_byte *readbuf, const gdb_byte *writebuf, ULONGEST offset, LONGEST len)
static int remote_search_memory (struct target_ops *ops, CORE_ADDR start_addr, ULONGEST search_space_len, const gdb_byte *pattern, ULONGEST pattern_len, CORE_ADDR *found_addrp)
static void remote_rcmd (char *command, struct ui_file *outbuf)
static VEC (mem_region_s)
static char * remote_pid_to_str (struct target_ops *ops, ptid_t ptid)
static CORE_ADDR remote_get_thread_local_address (struct target_ops *ops, ptid_t ptid, CORE_ADDR lm, CORE_ADDR offset)
static int remote_get_tib_address (ptid_t ptid, CORE_ADDR *addr)
DEF_VEC_O (remote_g_packet_guess_s)
static void * remote_g_packet_data_init (struct obstack *obstack)
void register_remote_g_packet_guess (struct gdbarch *gdbarch, int bytes, const struct target_desc *tdesc)
static struct target_desc * remote_read_description (struct target_ops *target)
static void remote_buffer_add_string (char **buffer, int *left, char *string)
static void remote_buffer_add_bytes (char **buffer, int *left, const gdb_byte *bytes, int len)
static void remote_buffer_add_int (char **buffer, int *left, ULONGEST value)
static int remote_hostio_parse_result (char *buffer, int *retcode, int *remote_errno, char **attachment)
static int remote_hostio_send_command (int command_bytes, int which_packet, int *remote_errno, char **attachment, int *attachment_len)
static int remote_hostio_open (const char *filename, int flags, int mode, int *remote_errno)
static int remote_hostio_pwrite (int fd, const gdb_byte *write_buf, int len, ULONGEST offset, int *remote_errno)
static int remote_hostio_pread (int fd, gdb_byte *read_buf, int len, ULONGEST offset, int *remote_errno)
static int remote_hostio_close (int fd, int *remote_errno)
static int remote_hostio_unlink (const char *filename, int *remote_errno)
static char * remote_hostio_readlink (const char *filename, int *remote_errno)
static int remote_fileio_errno_to_host (int errnum)
static char * remote_hostio_error (int errnum)
static void remote_hostio_close_cleanup (void *opaque)
static void * remote_bfd_iovec_open (struct bfd *abfd, void *open_closure)
static int remote_bfd_iovec_close (struct bfd *abfd, void *stream)
static file_ptr remote_bfd_iovec_pread (struct bfd *abfd, void *stream, void *buf, file_ptr nbytes, file_ptr offset)
static int remote_bfd_iovec_stat (struct bfd *abfd, void *stream, struct stat *sb)
int remote_filename_p (const char *filename)
bfd * remote_bfd_open (const char *remote_file, const char *target)
void remote_file_put (const char *local_file, const char *remote_file, int from_tty)
void remote_file_get (const char *remote_file, const char *local_file, int from_tty)
void remote_file_delete (const char *remote_file, int from_tty)
static void remote_put_command (char *args, int from_tty)
static void remote_get_command (char *args, int from_tty)
static void remote_delete_command (char *args, int from_tty)
static void remote_command (char *args, int from_tty)
static int remote_can_execute_reverse (void)
static int remote_supports_non_stop (void)
static int remote_supports_disable_randomization (void)
static int remote_supports_multi_process (void)
static int remote_supports_cond_tracepoints (void)
static int remote_supports_fast_tracepoints (void)
static int remote_supports_static_tracepoints (void)
static int remote_supports_install_in_trace (void)
static int remote_supports_enable_disable_tracepoint (void)
static int remote_supports_string_tracing (void)
static void remote_trace_init (void)
static void free_actions_list (char **actions_list)
static void free_actions_list_cleanup_wrapper (void *)
static void remote_download_command_source (int num, ULONGEST addr, struct command_line *cmds)
static void remote_download_tracepoint (struct bp_location *loc)
static int remote_can_download_tracepoint (void)
static void remote_download_trace_state_variable (struct trace_state_variable *tsv)
static void remote_enable_tracepoint (struct bp_location *location)
static void remote_disable_tracepoint (struct bp_location *location)
static void remote_trace_set_readonly_regions (void)
static void remote_trace_start (void)
static void remote_get_tracepoint_status (struct breakpoint *bp, struct uploaded_tp *utp)
static void remote_trace_stop (void)
static int remote_trace_find (enum trace_find_type type, int num, CORE_ADDR addr1, CORE_ADDR addr2, int *tpp)
static int remote_get_trace_state_variable_value (int tsvnum, LONGEST *val)
static int remote_save_trace_data (const char *filename)
static LONGEST remote_get_raw_trace_data (gdb_byte *buf, ULONGEST offset, LONGEST len)
static void remote_set_disconnected_tracing (int val)
static int remote_core_of_thread (struct target_ops *ops, ptid_t ptid)
static void remote_set_circular_trace_buffer (int val)
static struct traceframe_info * remote_traceframe_info (void)
static int remote_get_min_fast_tracepoint_insn_len (void)
static void remote_set_trace_buffer_size (LONGEST val)
static int remote_set_trace_notes (const char *user, const char *notes, const char *stop_notes)
static int remote_use_agent (int use)
static int remote_can_use_agent (void)
static int remote_supports_btrace (void)
static struct btrace_target_info * remote_enable_btrace (ptid_t ptid)
static void remote_disable_btrace (struct btrace_target_info *tinfo)
static void remote_teardown_btrace (struct btrace_target_info *tinfo)
static VEC (btrace_block_s)
static int remote_augmented_libraries_svr4_read (void)
static void remote_async_serial_handler (struct serial *scb, void *context)
static void set_remote_cmd (char *args, int from_tty)
static void show_remote_cmd (char *args, int from_tty)
static void remote_new_objfile (struct objfile *objfile)
static void show_range_stepping (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static void set_range_stepping (char *ignore_args, int from_tty, struct cmd_list_element *c)
Variables
static char * target_buf
static long target_buf_size
static struct cmd_list_element * remote_cmdlist
static struct cmd_list_element * remote_set_cmdlist
static struct cmd_list_element * remote_show_cmdlist
static int use_range_stepping = 1
static struct remote_state * remote_state
static struct gdbarch_data * remote_gdbarch_data_handle
static struct target_ops remote_ops
static struct target_ops extended_remote_ops
static int wait_forever_enabled_p = 1
const char interrupt_sequence_control_c [] = "Ctrl-C"
const char interrupt_sequence_break [] = "BREAK"
const char interrupt_sequence_break_g [] = "BREAK-g"
static const char *const interrupt_sequence_modes []
static const char * interrupt_sequence_mode = interrupt_sequence_control_c
static int interrupt_on_connect = 0
static int remote_break
static unsigned int remote_address_size
static int remote_async_terminal_ours_p
static char * remote_exec_file = ""
static struct memory_packet_config memory_write_packet_config
static struct memory_packet_config memory_read_packet_config
static struct packet_config remote_protocol_packets [PACKET_MAX]
static enum auto_boolean remote_Z_packet_detect
static struct
async_signal_handler * async_sigint_remote_twice_token
static struct
async_signal_handler * async_sigint_remote_token
static struct async_event_handler * remote_async_inferior_event_token
static ptid_t magic_null_ptid
static ptid_t not_sent_ptid
static ptid_t any_thread_ptid
static const char hexchars [] = "0123456789abcdef"
static struct protocol_feature remote_protocol_features []
static char * remote_support_xml
static void(* ofunc)(int)
struct notif_client notif_client_stop
static const int remote_flash_timeout = 1000
int remote_hw_watchpoint_limit = -1
int remote_hw_watchpoint_length_limit = -1
int remote_hw_breakpoint_limit = -1
static struct gdbarch_data * remote_g_packet_data_handle
static serial_event_ftype remote_async_serial_handler
Define Documentation
#define BUF_SIZE 2048
Referenced by remote_download_tracepoint().
#define BUF_THREAD_ID_SIZE (OPAQUETHREADBYTES * 2)
Definition at line 1927 of file remote.c.
Referenced by pack_threadid(), parse_threadlist_response(), remote_get_threadlist(), and unpack_threadid().
#define CRAZY_MAX_THREADS 1000
Definition at line 2615 of file remote.c.
Referenced by remote_find_new_threads().
#define MAX_REMOTE_PACKET_SIZE 16384
Referenced by get_memory_packet_size(), remote_packet_size(), and set_memory_packet_size().
#define MAX_TRIES 3
Referenced by getpkt_or_notif_sane_1().
#define MAXTHREADLISTRESULTS 32
Definition at line 272 of file remote.c.
Referenced by remote_threadlist_iterator().
#define MIN_REMOTE_PACKET_SIZE 20
Referenced by get_memory_packet_size().
#define OPAQUETHREADBYTES 8
Definition at line 265 of file remote.c.
#define TAG_DISPLAY 4
Definition at line 2339 of file remote.c.
Referenced by remote_threads_extra_info(), and remote_unpack_thread_info_response().
#define TAG_DISPLAY 4 /* A short thing maybe to put on a window */
Definition at line 2339 of file remote.c.
#define TAG_EXISTS 2
Definition at line 2338 of file remote.c.
Referenced by remote_threads_extra_info(), and remote_unpack_thread_info_response().
#define TAG_EXISTS
Value:
2               /* Is this process defined enough to
                                   fetch registers and its stack?  */
Definition at line 2338 of file remote.c.
#define TAG_MOREDISPLAY 16
Definition at line 2341 of file remote.c.
Referenced by remote_threads_extra_info(), and remote_unpack_thread_info_response().
#define TAG_MOREDISPLAY
Value:
16      /* Whatever the kernel wants to say about
                                   the process.  */
Definition at line 2341 of file remote.c.
#define TAG_THREADID 1
Definition at line 2337 of file remote.c.
Referenced by remote_threads_extra_info(), and remote_unpack_thread_info_response().
#define TAG_THREADID 1 /* Echo the thread identifier. */
Definition at line 2337 of file remote.c.
#define TAG_THREADNAME 8
Definition at line 2340 of file remote.c.
Referenced by remote_threads_extra_info(), and remote_unpack_thread_info_response().
#define TAG_THREADNAME 8 /* string, maps 1-to-1 with a thread is. */
Definition at line 2340 of file remote.c.
Typedef Documentation
typedef struct cached_reg cached_reg_t
typedef int gdb_threadref
Definition at line 1899 of file remote.c.
typedef struct remote_g_packet_guess remote_g_packet_guess_s
Definition at line 9478 of file remote.c.
typedef int(* rmt_thread_action)(threadref *ref, void *context)
Definition at line 1987 of file remote.c.
typedef struct stop_reply * stop_reply_p
typedef unsigned char threadref[OPAQUETHREADBYTES]
Definition at line 268 of file remote.c.
Enumeration Type Documentation
anonymous enum
Enumerator:
REMOTE_ALIGN_WRITES
Definition at line 88 of file remote.c.
anonymous enum
Enumerator:
PACKET_vCont
PACKET_X
PACKET_qSymbol
PACKET_P
PACKET_p
PACKET_Z0
PACKET_Z1
PACKET_Z2
PACKET_Z3
PACKET_Z4
PACKET_vFile_open
PACKET_vFile_pread
PACKET_vFile_pwrite
PACKET_vFile_close
PACKET_vFile_unlink
PACKET_vFile_readlink
PACKET_qXfer_auxv
PACKET_qXfer_features
PACKET_qXfer_libraries
PACKET_qXfer_libraries_svr4
PACKET_qXfer_memory_map
PACKET_qXfer_spu_read
PACKET_qXfer_spu_write
PACKET_qXfer_osdata
PACKET_qXfer_threads
PACKET_qXfer_statictrace_read
PACKET_qXfer_traceframe_info
PACKET_qXfer_uib
PACKET_qGetTIBAddr
PACKET_qGetTLSAddr
PACKET_qSupported
PACKET_qTStatus
PACKET_QPassSignals
PACKET_QProgramSignals
PACKET_qSearch_memory
PACKET_vAttach
PACKET_vRun
PACKET_QStartNoAckMode
PACKET_vKill
PACKET_qXfer_siginfo_read
PACKET_qXfer_siginfo_write
PACKET_qAttached
PACKET_ConditionalTracepoints
PACKET_ConditionalBreakpoints
PACKET_BreakpointCommands
PACKET_FastTracepoints
PACKET_StaticTracepoints
PACKET_InstallInTrace
PACKET_bc
PACKET_bs
PACKET_TracepointSource
PACKET_QAllow
PACKET_qXfer_fdpic
PACKET_QDisableRandomization
PACKET_QAgent
PACKET_QTBuffer_size
PACKET_Qbtrace_off
PACKET_Qbtrace_bts
PACKET_qXfer_btrace
PACKET_MAX
Definition at line 1312 of file remote.c.
enum packet_result
Enumerator:
PACKET_ERROR
PACKET_OK
PACKET_UNKNOWN
Definition at line 1130 of file remote.c.
enum packet_support
Enumerator:
PACKET_SUPPORT_UNKNOWN
PACKET_ENABLE
PACKET_DISABLE
Definition at line 1112 of file remote.c.
enum Z_packet_type
Enumerator:
Z_PACKET_SOFTWARE_BP
Z_PACKET_HARDWARE_BP
Z_PACKET_WRITE_WP
Z_PACKET_READ_WP
Z_PACKET_ACCESS_WP
NR_Z_PACKET_TYPES
Definition at line 1420 of file remote.c.
Function Documentation
void _initialize_remote (void)
static void add_current_inferior_and_thread (char * wait_status) [static]
Definition at line 3325 of file remote.c.
References add_thread_silent(), get_remote_state(), inferior_ptid, magic_null_ptid, null_ptid, ptid_equal(), ptid_get_pid(), remote_add_inferior(), remote_current_thread(), remote_multi_process_p(), and stop_reply_extract_thread().
Referenced by extended_remote_create_inferior_1(), and remote_start_remote().
static void add_packet_config_cmd (struct packet_config * config, const char * name, const char * title, int legacy) [static]
Definition at line 1187 of file remote.c.
References add_alias_cmd(), add_setshow_auto_boolean_cmd(), AUTO_BOOLEAN_AUTO, class_obscure, packet_config::detect, name, packet_config::name, PACKET_SUPPORT_UNKNOWN, set_remote_protocol_packet_cmd(), show_remote_protocol_packet_cmd(), packet_config::support, packet_config::title, xfree(), and xstrprintf().
static char* append_pending_thread_resumptions (char * p, char * endp, ptid_t ptid) [static]
Definition at line 4818 of file remote.c.
References ALL_THREADS, append_resumption(), inferior_ptid, thread_info::ptid, ptid_equal(), ptid_match(), signal_pass_state(), thread_suspend_state::stop_signal, and thread_info::suspend.
Referenced by remote_vcont_resume().
static char* append_resumption (char * p, char * endp, ptid_t ptid, int step, enum gdb_signal siggnal) [static]
Definition at line 4745 of file remote.c.
References thread_info::control, find_thread_ptid(), gdb_assert, gdbarch_addr_bit(), get_remote_state(), thread_control_state::may_range_step, minus_one_ptid, phex_nz(), ptid_build(), ptid_equal(), ptid_get_pid(), ptid_is_pid(), vCont_action_support::r, remote_multi_process_p(), thread_control_state::step_range_end, thread_control_state::step_range_start, remote_state::supports_vCont, target_gdbarch(), write_ptid(), and xsnprintf().
Referenced by append_pending_thread_resumptions(), and remote_vcont_resume().
static void async_cleanup_sigint_signal_handler (void * dummy) [static]
Definition at line 5054 of file remote.c.
References handle_sigint().
Referenced by remote_terminal_ours().
static void async_handle_remote_sigint (int sig) [static]
Definition at line 5013 of file remote.c.
References async_handle_remote_sigint_twice(), and mark_async_signal_handler().
Referenced by async_handle_remote_sigint_twice(), and async_initialize_sigint_signal_handler().
static void async_handle_remote_sigint_twice (int sig) [static]
Definition at line 5023 of file remote.c.
References async_handle_remote_sigint(), and mark_async_signal_handler().
Referenced by async_handle_remote_sigint().
static void async_initialize_sigint_signal_handler (void) [static]
Definition at line 5006 of file remote.c.
References async_handle_remote_sigint().
Referenced by remote_terminal_inferior().
static void async_remote_interrupt (gdb_client_data arg) [static]
Definition at line 5032 of file remote.c.
References fprintf_unfiltered(), gdb_stdlog, inferior_ptid, remote_debug, and target_stop().
static void async_remote_interrupt_twice (gdb_client_data arg) [static]
Definition at line 5043 of file remote.c.
References fprintf_unfiltered(), gdb_stdlog, interrupt_query(), and remote_debug.
int bin2hex (const gdb_byte * bin, char * hex, int count)
Definition at line 4664 of file remote.c.
References tohex().
Referenced by encode_source_string(), extended_remote_run(), remote_buffer_add_bytes(), remote_download_trace_state_variable(), remote_rcmd(), remote_save_trace_data(), remote_set_trace_notes(), remote_write_bytes_aux(), store_register_using_P(), store_registers_using_G(), tfile_write_status(), and tfile_write_uploaded_tsv().
static void check_binary_download (CORE_ADDR addr) [static]
Definition at line 6719 of file remote.c.
References remote_state::buf, remote_state::buf_size, fprintf_unfiltered(), gdb_stdlog, get_remote_state(), getpkt(), hexnumstr(), PACKET_DISABLE, PACKET_ENABLE, PACKET_SUPPORT_UNKNOWN, PACKET_X, putpkt_binary(), remote_debug, remote_protocol_packets, packet_config::support, and ULONGEST.
Referenced by remote_write_bytes().
static int compare_pnums (const void * lhs_, const void * rhs_) [static]
Definition at line 635 of file remote.c.
Referenced by map_regcache_remote_table().
static void compare_sections_command (char * args, int from_tty) [static]
Definition at line 8598 of file remote.c.
References _, do_cleanups(), error(), exec_bfd, make_cleanup(), paddress(), printf_filtered(), set_general_process(), size, target_gdbarch(), target_verify_memory(), warning(), xfree(), and xmalloc().
static void copy_threadref (threadref * dest, threadref * src) [static]
Definition at line 2282 of file remote.c.
Referenced by remote_threadlist_iterator(), and remote_unpack_thread_info_response().
DECLARE_QUEUE_P (stop_reply_p)
DEF_VEC_O (cached_reg_t)
DEF_VEC_O (remote_g_packet_guess_s)
DEFINE_QUEUE_P (stop_reply_p)
static struct private_thread_info* demand_private_info (ptid_t ptid) [static, read]
Definition at line 1654 of file remote.c.
References private_thread_info::core, private_thread_info::extra, find_thread_ptid(), free_private_thread_info(), gdb_assert, thread_info::private, thread_info::private_dtor, and xmalloc().
Referenced by process_stop_reply(), and remote_threads_info().
static void discard_pending_stop_replies (struct inferior * inf) [static]
Definition at line 5410 of file remote.c.
References get_remote_state(), notif_client::id, arm-linux::inf, queue_iter_param::input, remote_state::notif_state, queue_iter_param::output, remote_notif_state::pending_event, inferior::pid, stop_reply::ptid, ptid_get_pid(), QUEUE_iterate, remote_state::remote_desc, remove_stop_reply_for_inferior(), and stop_reply_xfree().
static void discard_pending_stop_replies_in_queue (struct remote_state * rs) [static]
Definition at line 5464 of file remote.c.
References queue_iter_param::input, queue_iter_param::output, QUEUE_iterate, and remove_stop_reply_of_remote_state().
Referenced by remote_close().
static char* escape_buffer (const char * buf, int n) [static]
Definition at line 7218 of file remote.c.
References do_cleanups(), fputstrn_unfiltered(), make_cleanup_ui_file_delete(), mem_fileopen(), and ui_file_xstrdup().
Referenced by getpkt_or_notif_sane_1(), putpkt_binary(), and read_frame().
static void extended_remote_attach (struct target_ops * ops, char * args, int from_tty) [static]
Definition at line 4613 of file remote.c.
References extended_remote_attach_1().
Referenced by init_extended_remote_ops().
static void extended_remote_attach_1 (struct target_ops * target, char * args, int from_tty) [static]
Definition at line 4502 of file remote.c.
References _, add_thread_silent(), remote_state::buf, remote_state::buf_size, remote_state::cached_wait_status, error(), first_thread_of_process(), gdb_assert, gdb_flush(), gdb_stdout, get_exec_file(), get_remote_packet_size(), get_remote_state(), getpkt(), inferior_event_handler(), inferior_ptid, minus_one_ptid, non_stop, notif_client_stop, PACKET_DISABLE, PACKET_OK, packet_ok(), PACKET_vAttach, parse_pid_to_attach(), pid_to_ptid(), printf_unfiltered(), thread_info::ptid, push_stop_reply(), putpkt(), record_currthread(), remote_add_inferior(), remote_current_thread(), remote_notif_parse(), remote_protocol_packets, remote_threads_info(), set_current_inferior(), target_async, target_can_async_p, target_find_description(), target_pid_to_str(), and xsnprintf().
Referenced by extended_remote_attach().
static void extended_remote_create_inferior (struct target_ops * ops, char * exec_file, char * args, char ** env, int from_tty) [static]
Definition at line 8103 of file remote.c.
References extended_remote_create_inferior_1().
Referenced by init_extended_remote_ops().
static void extended_remote_create_inferior_1 (char * exec_file, char * args, char ** env, int from_tty) [static]
Definition at line 8054 of file remote.c.
References _, add_current_inferior_and_thread(), remote_state::buf, disable_randomization, error(), extended_remote_disable_randomization(), extended_remote_restart(), extended_remote_run(), extended_remote_supports_disable_randomization(), get_offsets(), get_remote_state(), have_inferiors(), inferior_event_handler(), init_thread_list(), init_wait_for_inferior(), target_async, and target_can_async_p.
Referenced by extended_remote_create_inferior().
static void extended_remote_detach (struct target_ops * ops, char * args, int from_tty) [static]
Definition at line 4476 of file remote.c.
References remote_detach_1().
Referenced by init_extended_remote_ops().
static void extended_remote_disable_randomization (int val) [static]
Definition at line 7971 of file remote.c.
References _, remote_state::buf, error(), get_remote_packet_size(), get_remote_state(), putpkt(), remote_get_noisy_reply(), target_buf, target_buf_size, and xsnprintf().
Referenced by extended_remote_create_inferior_1().
static void extended_remote_kill (struct target_ops * ops) [static]
Definition at line 7850 of file remote.c.
References _, remote_state::buf, remote_state::buf_size, error(), remote_state::extended, get_remote_state(), getpkt(), inferior_ptid, ptid_get_pid(), putpkt(), remote_multi_process_p(), remote_vkill(), and target_mourn_inferior().
Referenced by init_extended_remote_ops().
static void extended_remote_mourn (struct target_ops * ops) [static]
Definition at line 7958 of file remote.c.
References extended_remote_mourn_1().
Referenced by init_extended_remote_ops().
static void extended_remote_mourn_1 (struct target_ops * target) [static]
Definition at line 7897 of file remote.c.
References remote_state::buf, remote_state::buf_size, generic_mourn_inferior(), get_remote_state(), getpkt(), have_inferiors(), inferior_ptid, magic_null_ptid, minus_one_ptid, putpkt(), record_currthread(), remote_multi_process_p(), and remote_state::waiting_for_stop_reply.
Referenced by extended_remote_mourn().
static void extended_remote_open (char * name, int from_tty) [static]
Definition at line 3660 of file remote.c.
References extended_remote_ops, and remote_open_1().
Referenced by init_extended_remote_ops().
static void extended_remote_restart (void) [static]
Definition at line 3032 of file remote.c.
References remote_state::buf, get_remote_packet_size(), get_remote_state(), putpkt(), remote_fileio_reset(), and xsnprintf().
Referenced by extended_remote_create_inferior_1().
static int extended_remote_run (char * args) [static]
Definition at line 7987 of file remote.c.
References _, bin2hex(), remote_state::buf, remote_state::buf_size, do_cleanups(), error(), gdb_assert, gdb_buildargv(), get_remote_packet_size(), get_remote_state(), getpkt(), len, make_cleanup(), PACKET_DISABLE, PACKET_OK, packet_ok(), PACKET_vRun, putpkt(), and remote_protocol_packets.
Referenced by extended_remote_create_inferior_1().
static int extended_remote_supports_disable_randomization (void) [static]
Definition at line 7964 of file remote.c.
References PACKET_ENABLE, PACKET_QDisableRandomization, and remote_protocol_packets.
Referenced by extended_remote_create_inferior_1(), and init_extended_remote_ops().
static int fetch_register_using_p (struct regcache * regcache, struct packet_reg * reg) [static]
Definition at line 6143 of file remote.c.
References _, remote_state::buf, remote_state::buf_size, error(), fromhex(), gdbarch_register_name(), get_regcache_arch(), get_remote_state(), getpkt(), hexnumstr(), MAX_REGISTER_SIZE, PACKET_DISABLE, PACKET_ERROR, PACKET_OK, packet_ok(), PACKET_p, PACKET_UNKNOWN, packet_reg::pnum, putpkt(), regcache_raw_supply(), packet_reg::regnum, and remote_protocol_packets.
Referenced by remote_fetch_registers().
static void fetch_registers_using_g (struct regcache * regcache) [static]
Definition at line 6325 of file remote.c.
References process_g_packet(), and send_g_packet().
Referenced by remote_fetch_registers().
static void free_actions_list (char ** actions_list) [static]
Definition at line 10443 of file remote.c.
References xfree().
static void free_actions_list_cleanup_wrapper (void * al) [static]
Definition at line 10437 of file remote.c.
Referenced by remote_download_tracepoint().
static void free_private_thread_info (struct private_thread_info * info) [static]
Definition at line 441 of file remote.c.
References private_thread_info::extra, and xfree().
Referenced by demand_private_info().
static int fromhex (int a) [static]
Definition at line 4621 of file remote.c.
References _, and error().
Referenced by fetch_register_using_p(), get_offsets(), hex2bin(), process_g_packet(), read_frame(), remote_console_output(), remote_parse_stop_reply(), remote_rcmd(), remote_verify_memory(), and unpack_nibble().
static long get_memory_packet_size (struct memory_packet_config * config) [static]
Definition at line 940 of file remote.c.
References remote_arch_state::actual_register_packet_size, remote_state::buf, remote_state::buf_size, remote_state::explicit_packet_size, memory_packet_config::fixed_p, get_remote_arch_state(), get_remote_packet_size(), get_remote_state(), MAX_REMOTE_PACKET_SIZE, MIN_REMOTE_PACKET_SIZE, memory_packet_config::size, and xrealloc().
Referenced by get_memory_read_packet_size(), get_memory_write_packet_size(), and show_memory_packet_size().
static long get_memory_read_packet_size (void) [static]
Definition at line 1095 of file remote.c.
References get_memory_packet_size(), get_remote_packet_size(), and size.
Referenced by remote_read_bytes().
static long get_memory_write_packet_size (void) [static]
Definition at line 1072 of file remote.c.
References get_memory_packet_size().
Referenced by remote_search_memory(), remote_write_bytes_aux(), and remote_write_qxfer().
static void get_offsets (void) [static]
Definition at line 3083 of file remote.c.
References _, remote_state::buf, remote_state::buf_size, error(), free_symfile_segment_data(), fromhex(), get_remote_state(), get_symfile_segment_data(), getpkt(), memcpy(), symfile_segment_data::num_segments, objfile_relocate(), section_offsets::offsets, putpkt(), SECT_OFF_BSS, SECT_OFF_DATA, SECT_OFF_TEXT, symfile_segment_data::segment_bases, SIZEOF_N_SECTION_OFFSETS, symfile_map_offsets_to_segments(), symfile_objfile, and warning().
Referenced by extended_remote_create_inferior_1(), and remote_start_remote().
static struct remote_arch_state* get_remote_arch_state (void) [static, read]
Definition at line 614 of file remote.c.
References gdbarch_data(), and target_gdbarch().
Referenced by get_memory_packet_size(), get_remote_packet_size(), get_remote_state(), process_g_packet(), remote_fetch_registers(), remote_get_trace_status(), remote_parse_stop_reply(), remote_prepare_to_store(), remote_store_registers(), and store_registers_using_G().
static long get_remote_packet_size (void) [static]
Definition at line 775 of file remote.c.
References remote_state::explicit_packet_size, get_remote_arch_state(), get_remote_state(), and remote_arch_state::remote_packet_size.
Referenced by extended_remote_attach_1(), extended_remote_disable_randomization(), extended_remote_restart(), extended_remote_run(), get_memory_packet_size(), get_memory_read_packet_size(), remote_check_symbols(), remote_detach_1(), remote_disable_btrace(), remote_disable_tracepoint(), remote_download_trace_state_variable(), remote_enable_btrace(), remote_enable_tracepoint(), remote_file_get(), remote_file_put(), remote_get_min_fast_tracepoint_insn_len(), remote_get_thread_local_address(), remote_get_threadlist(), remote_get_tib_address(), remote_get_trace_state_variable_value(), remote_get_tracepoint_status(), remote_hostio_close(), remote_hostio_open(), remote_hostio_pread(), remote_hostio_pwrite(), remote_hostio_readlink(), remote_hostio_unlink(), remote_insert_breakpoint(), remote_insert_hw_breakpoint(), remote_insert_watchpoint(), remote_query_attached(), remote_rcmd(), remote_read_qxfer(), remote_remove_breakpoint(), remote_remove_hw_breakpoint(), remote_remove_watchpoint(), remote_save_trace_data(), remote_send_printf(), remote_set_circular_trace_buffer(), remote_set_disconnected_tracing(), remote_set_permissions(), remote_set_trace_buffer_size(), remote_set_trace_notes(), remote_static_tracepoint_marker_at(), remote_stop_ns(), remote_thread_alive(), remote_threads_extra_info(), remote_trace_find(), remote_use_agent(), remote_vcont_resume(), remote_verify_memory(), remote_vkill(), remote_xfer_partial(), send_g_packet(), set_thread(), and store_register_using_P().
static struct remote_state* get_remote_state (void) [static, read]
Definition at line 622 of file remote.c.
References get_remote_arch_state(), and get_remote_state_raw().
Referenced by add_current_inferior_and_thread(), append_resumption(), check_binary_download(), discard_pending_stop_replies(), extended_remote_attach_1(), extended_remote_create_inferior_1(), extended_remote_disable_randomization(), extended_remote_kill(), extended_remote_mourn_1(), extended_remote_restart(), extended_remote_run(), fetch_register_using_p(), get_memory_packet_size(), get_offsets(), get_remote_packet_size(), getpkt_or_notif_sane_1(), packet_command(), parse_threadlist_response(), process_g_packet(), process_stop_reply(), putpkt_binary(), read_frame(), readchar(), remote_async(), remote_augmented_libraries_svr4_read(), remote_augmented_libraries_svr4_read_feature(), remote_breakpoint_commands_feature(), remote_can_async_p(), remote_can_download_tracepoint(), remote_can_run_breakpoint_commands(), remote_check_symbols(), remote_close(), remote_cond_breakpoint_feature(), remote_cond_tracepoint_feature(), remote_current_thread(), remote_detach_1(), remote_disable_btrace(), remote_disable_tracepoint(), remote_disconnected_tracing_feature(), remote_download_command_source(), remote_download_trace_state_variable(), remote_enable_btrace(), remote_enable_disable_tracepoint_feature(), remote_enable_tracepoint(), remote_fast_tracepoint_feature(), remote_file_delete(), remote_file_get(), remote_file_put(), remote_get_min_fast_tracepoint_insn_len(), remote_get_raw_trace_data(), remote_get_thread_local_address(), remote_get_threadinfo(), remote_get_threadlist(), remote_get_tib_address(), remote_get_trace_state_variable_value(), remote_get_tracepoint_status(), remote_hostio_close(), remote_hostio_open(), remote_hostio_pread(), remote_hostio_pwrite(), remote_hostio_readlink(), remote_hostio_send_command(), remote_hostio_unlink(), remote_insert_breakpoint(), remote_insert_hw_breakpoint(), remote_insert_watchpoint(), remote_install_in_trace_feature(), remote_is_async_p(), remote_multi_process_feature(), remote_new_objfile(), remote_non_stop_feature(), remote_notice_new_inferior(), remote_notif_get_pending_events(), remote_open_1(), remote_packet_size(), remote_parse_stop_reply(), remote_pass_signals(), remote_pid_to_str(), remote_program_signals(), remote_query_attached(), remote_query_supported(), remote_rcmd(), remote_read_bytes(), remote_read_qxfer(), remote_remove_breakpoint(), remote_remove_hw_breakpoint(), remote_remove_watchpoint(), remote_resume(), remote_save_trace_data(), remote_search_memory(), remote_send_printf(), remote_serial_write(), remote_set_circular_trace_buffer(), remote_set_disconnected_tracing(), remote_set_permissions(), remote_set_trace_buffer_size(), remote_set_trace_notes(), remote_start_remote(), remote_static_tracepoint_feature(), remote_static_tracepoint_marker_at(), remote_stop_as(), remote_stop_ns(), remote_stopped_by_watchpoint(), remote_stopped_data_address(), remote_string_tracing_feature(), remote_supports_cond_breakpoints(), remote_supports_cond_tracepoints(), remote_supports_enable_disable_tracepoint(), remote_supports_fast_tracepoints(), remote_supports_install_in_trace(), remote_supports_multi_process(), remote_supports_static_tracepoints(), remote_supports_string_tracing(), remote_thread_alive(), remote_threadlist_iterator(), remote_threads_extra_info(), remote_threads_info(), remote_trace_find(), remote_unpack_thread_info_response(), remote_upload_trace_state_variables(), remote_upload_tracepoints(), remote_use_agent(), remote_vcont_resume(), remote_verify_memory(), remote_wait_as(), remote_wait_ns(), remote_write_bytes_aux(), remote_write_qxfer(), remote_xfer_partial(), send_g_packet(), send_interrupt_sequence(), set_general_process(), set_range_stepping(), set_remote_traceframe(), set_thread(), store_register_using_P(), store_registers_using_G(), VEC(), and write_ptid().
static struct remote_state* get_remote_state_raw (void) [static, read]
Definition at line 461 of file remote.c.
References remote_state.
Referenced by get_remote_state(), and init_remote_state().
void getpkt (char ** buf, long * sizeof_buf, int forever)
Definition at line 7631 of file remote.c.
References getpkt_sane().
Referenced by check_binary_download(), extended_remote_attach_1(), extended_remote_kill(), extended_remote_mourn_1(), extended_remote_run(), fetch_register_using_p(), get_offsets(), packet_command(), remote_check_symbols(), remote_current_thread(), remote_detach_1(), remote_disable_btrace(), remote_enable_btrace(), remote_get_noisy_reply(), remote_get_thread_local_address(), remote_get_threadinfo(), remote_get_threadlist(), remote_get_tib_address(), remote_insert_breakpoint(), remote_insert_hw_breakpoint(), remote_insert_watchpoint(), remote_notif_get_pending_events(), remote_pass_signals(), remote_program_signals(), remote_query_attached(), remote_query_supported(), remote_read_bytes(), remote_remove_breakpoint(), remote_remove_hw_breakpoint(), remote_remove_watchpoint(), remote_send(), remote_send_printf(), remote_set_permissions(), remote_start_remote(), remote_static_tracepoint_marker_at(), remote_stop_ns(), remote_thread_alive(), remote_threads_extra_info(), remote_threads_info(), remote_trace_set_readonly_regions(), remote_upload_trace_state_variables(), remote_upload_tracepoints(), remote_use_agent(), remote_vcont_probe(), remote_vcont_resume(), remote_verify_memory(), remote_vkill(), remote_write_bytes_aux(), remote_xfer_partial(), send_g_packet(), set_thread(), store_register_using_P(), and store_registers_using_G().
static int getpkt_or_notif_sane (char ** buf, long * sizeof_buf, int forever, int * is_notif) [static]
Definition at line 7801 of file remote.c.
References getpkt_or_notif_sane_1().
Referenced by remote_wait_as(), and remote_wait_ns().
static int getpkt_or_notif_sane_1 (char ** buf, long * sizeof_buf, int forever, int expecting_notif, int * is_notif) [static]
Definition at line 7654 of file remote.c.
References _, remote_state::cached_wait_status, do_cleanups(), escape_buffer(), fprintf_unfiltered(), fputs_filtered(), gdb_assert, gdb_stdlog, get_remote_state(), handle_notification(), make_cleanup(), MAX_TRIES, remote_state::noack_mode, remote_state::notif_state, printf_unfiltered(), QUIT, read_frame(), readchar(), remote_debug, remote_serial_write(), remote_timeout, remote_unpush_target(), SERIAL_TIMEOUT, TARGET_CLOSE_ERROR, throw_error(), timeout, watchdog, and xfree().
Referenced by getpkt_or_notif_sane(), and getpkt_sane().
static int getpkt_sane (char ** buf, long * sizeof_buf, int forever) [static]
Definition at line 7795 of file remote.c.
References getpkt_or_notif_sane_1().
Referenced by getpkt(), remote_hostio_send_command(), remote_rcmd(), remote_read_qxfer(), remote_search_memory(), and remote_write_qxfer().
int hex2bin (const char * hex, gdb_byte * bin, int count)
Definition at line 4634 of file remote.c.
References fromhex().
static int hexnumlen (ULONGEST num) [static]
Definition at line 6559 of file remote.c.
References max.
Referenced by hexnumstr(), remote_buffer_add_int(), and remote_write_bytes_aux().
static int hexnumnstr (char * buf, ULONGEST num, int width) [static]
Definition at line 6583 of file remote.c.
Referenced by hexnumstr(), and remote_write_bytes_aux().
static int hexnumstr (char * buf, ULONGEST num) [static]
Definition at line 6572 of file remote.c.
References hexnumlen(), and hexnumnstr().
Referenced by check_binary_download(), fetch_register_using_p(), remote_buffer_add_int(), remote_get_raw_trace_data(), remote_get_thread_local_address(), remote_insert_breakpoint(), remote_insert_hw_breakpoint(), remote_insert_watchpoint(), remote_read_bytes(), remote_remove_breakpoint(), remote_remove_hw_breakpoint(), remote_remove_watchpoint(), remote_set_trace_buffer_size(), remote_static_tracepoint_marker_at(), and remote_write_bytes_aux().
static void init_all_packet_configs (void) [static]
Definition at line 3668 of file remote.c.
References PACKET_MAX, remote_protocol_packets, and update_packet_config().
Referenced by remote_open_1().
static void init_extended_remote_ops (void) [static]
Definition at line 11584 of file remote.c.
References extended_remote_attach(), extended_remote_create_inferior(), extended_remote_detach(), extended_remote_kill(), extended_remote_mourn(), extended_remote_open(), extended_remote_ops, extended_remote_supports_disable_randomization(), remote_ops, target_ops::to_attach, target_ops::to_create_inferior, target_ops::to_detach, target_ops::to_doc, target_ops::to_kill, target_ops::to_longname, target_ops::to_mourn_inferior, target_ops::to_open, target_ops::to_shortname, and target_ops::to_supports_disable_randomization.
static void init_remote_ops (void) [static]
Definition at line 11456 of file remote.c.
References default_child_has_all_memory(), default_child_has_execution(), default_child_has_memory(), default_child_has_registers(), default_child_has_stack(), generic_load(), OPS_MAGIC, process_stratum, remote_async(), remote_augmented_libraries_svr4_read(), remote_can_async_p(), remote_can_download_tracepoint(), remote_can_execute_reverse(), remote_can_run_breakpoint_commands(), remote_can_use_agent(), remote_check_watch_resources(), remote_close(), remote_core_of_thread(), remote_detach(), remote_disable_btrace(), remote_disable_tracepoint(), remote_disconnect(), remote_download_trace_state_variable(), remote_download_tracepoint(), remote_enable_btrace(), remote_enable_tracepoint(), remote_fetch_registers(), remote_files_info(), remote_flash_done(), remote_flash_erase(), remote_get_ada_task_ptid(), remote_get_min_fast_tracepoint_insn_len(), remote_get_raw_trace_data(), remote_get_thread_local_address(), remote_get_tib_address(), remote_get_trace_state_variable_value(), remote_get_trace_status(), remote_get_tracepoint_status(), remote_hostio_close(), remote_hostio_open(), remote_hostio_pread(), remote_hostio_pwrite(), remote_hostio_readlink(), remote_hostio_unlink(), remote_insert_breakpoint(), remote_insert_hw_breakpoint(), remote_insert_watchpoint(), remote_is_async_p(), remote_kill(), remote_mourn(), remote_open(), remote_ops, remote_pass_signals(), remote_pid_to_str(), remote_prepare_to_store(), remote_program_signals(), remote_rcmd(), remote_read_description(), remote_region_ok_for_hw_watchpoint(), remote_remove_breakpoint(), remote_remove_hw_breakpoint(), remote_remove_watchpoint(), remote_resume(), remote_save_trace_data(), remote_search_memory(), remote_set_circular_trace_buffer(), remote_set_disconnected_tracing(), remote_set_permissions(), remote_set_trace_buffer_size(), remote_set_trace_notes(), remote_static_tracepoint_marker_at(), remote_stop(), remote_stopped_by_watchpoint(), remote_stopped_data_address(), remote_store_registers(), remote_supports_btrace(), remote_supports_cond_breakpoints(), remote_supports_disable_randomization(), remote_supports_enable_disable_tracepoint(), remote_supports_multi_process(), remote_supports_non_stop(), remote_supports_string_tracing(), remote_teardown_btrace(), remote_terminal_inferior(), remote_terminal_ours(), remote_thread_alive(), remote_threads_extra_info(), remote_threads_info(), remote_trace_find(), remote_trace_init(), remote_trace_set_readonly_regions(), remote_trace_start(), remote_trace_stop(), remote_traceframe_info(), remote_upload_trace_state_variables(), remote_upload_tracepoints(), remote_use_agent(), remote_verify_memory(), remote_wait(), remote_watchpoint_addr_within_range(), remote_xfer_partial(), serial_log_command(), tc_schedlock, target_ops::to_async, target_ops::to_augmented_libraries_svr4_read, target_ops::to_can_async_p, target_ops::to_can_download_tracepoint, target_ops::to_can_execute_reverse, target_ops::to_can_run_breakpoint_commands, target_ops::to_can_use_agent, target_ops::to_can_use_hw_breakpoint, target_ops::to_close, target_ops::to_core_of_thread, target_ops::to_detach, target_ops::to_disable_btrace, target_ops::to_disable_tracepoint, target_ops::to_disconnect, target_ops::to_doc, target_ops::to_download_trace_state_variable, target_ops::to_download_tracepoint, target_ops::to_enable_btrace, target_ops::to_enable_tracepoint, target_ops::to_extra_thread_info, target_ops::to_fetch_registers, target_ops::to_fileio_close, target_ops::to_fileio_open, target_ops::to_fileio_pread, target_ops::to_fileio_pwrite, target_ops::to_fileio_readlink, target_ops::to_fileio_unlink, target_ops::to_files_info, target_ops::to_find_new_threads, target_ops::to_flash_done, target_ops::to_flash_erase, target_ops::to_get_ada_task_ptid, target_ops::to_get_min_fast_tracepoint_insn_len, target_ops::to_get_raw_trace_data, target_ops::to_get_thread_local_address, target_ops::to_get_tib_address, target_ops::to_get_trace_state_variable_value, target_ops::to_get_trace_status, target_ops::to_get_tracepoint_status, target_ops::to_has_all_memory, target_ops::to_has_execution, target_ops::to_has_memory, target_ops::to_has_registers, target_ops::to_has_stack, target_ops::to_has_thread_control, target_ops::to_insert_breakpoint, target_ops::to_insert_hw_breakpoint, target_ops::to_insert_watchpoint, target_ops::to_is_async_p, target_ops::to_kill, target_ops::to_load, target_ops::to_log_command, target_ops::to_longname, target_ops::to_magic, target_ops::to_mourn_inferior, target_ops::to_open, target_ops::to_pass_signals, target_ops::to_pid_to_str, target_ops::to_prepare_to_store, target_ops::to_program_signals, target_ops::to_rcmd, target_ops::to_read_description, target_ops::to_region_ok_for_hw_watchpoint, target_ops::to_remove_breakpoint, target_ops::to_remove_hw_breakpoint, target_ops::to_remove_watchpoint, target_ops::to_resume, target_ops::to_save_trace_data, target_ops::to_search_memory, target_ops::to_set_circular_trace_buffer, target_ops::to_set_disconnected_tracing, target_ops::to_set_permissions, target_ops::to_set_trace_buffer_size, target_ops::to_set_trace_notes, target_ops::to_shortname, target_ops::to_static_tracepoint_marker_at, target_ops::to_stop, target_ops::to_stopped_by_watchpoint, target_ops::to_stopped_data_address, target_ops::to_store_registers, target_ops::to_stratum, target_ops::to_supports_btrace, target_ops::to_supports_disable_randomization, target_ops::to_supports_enable_disable_tracepoint, target_ops::to_supports_evaluation_of_breakpoint_conditions, target_ops::to_supports_multi_process, target_ops::to_supports_non_stop, target_ops::to_supports_string_tracing, target_ops::to_teardown_btrace, target_ops::to_terminal_inferior, target_ops::to_terminal_ours, target_ops::to_thread_alive, target_ops::to_trace_find, target_ops::to_trace_init, target_ops::to_trace_set_readonly_regions, target_ops::to_trace_start, target_ops::to_trace_stop, target_ops::to_traceframe_info, target_ops::to_upload_trace_state_variables, target_ops::to_upload_tracepoints, target_ops::to_use_agent, target_ops::to_verify_memory, target_ops::to_wait, target_ops::to_watchpoint_addr_within_range, and target_ops::to_xfer_partial.
static void* init_remote_state (struct gdbarch * gdbarch) [static]
Definition at line 722 of file remote.c.
References remote_arch_state::actual_register_packet_size, remote_state::buf, remote_state::buf_size, gdbarch_num_regs(), GDBARCH_OBSTACK_CALLOC, GDBARCH_OBSTACK_ZALLOC, get_remote_state_raw(), map_regcache_remote_table(), remote_arch_state::regs, remote_arch_state::remote_packet_size, remote_arch_state::sizeof_g_packet, and xrealloc().
void int_to_threadref (threadref * id, int value)
Definition at line 2251 of file remote.c.
References scan().
Referenced by remote_threads_extra_info().
static void interrupt_query (void) [static]
Definition at line 5178 of file remote.c.
References _, handle_sigint(), query(), quit(), remote_unpush_target(), target_can_async_p, target_terminal_inferior(), and target_terminal_ours.
Referenced by async_remote_interrupt_twice(), and putpkt_binary().
static int ishex (int ch, int * val) [static]
Definition at line 2068 of file remote.c.
Referenced by unpack_varlen_hex().
static int map_regcache_remote_table (struct gdbarch * gdbarch, struct packet_reg * regs) [static]
Definition at line 649 of file remote.c.
References compare_pnums(), gdbarch_num_regs(), gdbarch_remote_register_number(), packet_reg::in_g_packet, offset, packet_reg::offset, packet_reg::pnum, qsort, register_size(), regnum, and packet_reg::regnum.
Referenced by init_remote_state(), and remote_register_number_and_offset().
static struct remote_state* new_remote_state (void) [static, read]
Definition at line 470 of file remote.c.
References remote_state::buf, remote_state::buf_size, remote_state::last_sent_signal, remote_state::remote_traceframe_number, and xmalloc().
static char * pack_hex_byte (char * pkt, int byte) [static]
Definition at line 2149 of file remote.c.
Referenced by pack_int(), pack_threadid(), pack_threadlist_request(), remote_add_target_side_commands(), remote_add_target_side_condition(), and remote_download_tracepoint().
static char * pack_int (char * buf, int value) [static]
Definition at line 2164 of file remote.c.
References remote_state::buf, and pack_hex_byte().
Referenced by pack_threadinfo_request().
static char * pack_nibble (char * buf, int nibble) [static]
Definition at line 2142 of file remote.c.
References remote_state::buf.
Referenced by pack_threadlist_request().
static char * pack_threadid (char * pkt, threadref * id) [static]
Definition at line 2214 of file remote.c.
References BUF_THREAD_ID_SIZE, and pack_hex_byte().
Referenced by pack_threadinfo_request(), and pack_threadlist_request().
static char * pack_threadinfo_request (char * pkt, int mode, threadref * id) [static]
Definition at line 2323 of file remote.c.
References pack_int(), and pack_threadid().
Referenced by remote_get_threadinfo().
static char * pack_threadlist_request (char * pkt, int startflag, int threadcount, threadref * nextthread) [static]
Definition at line 2458 of file remote.c.
References pack_hex_byte(), pack_nibble(), and pack_threadid().
Referenced by remote_get_threadlist().
static enum packet_result packet_check_result (const char * buf) [static]
Definition at line 1228 of file remote.c.
References PACKET_ERROR, PACKET_OK, and PACKET_UNKNOWN.
Referenced by packet_ok(), remote_send_printf(), and store_registers_using_G().
static void packet_command (char * args, int from_tty) [static]
Definition at line 9162 of file remote.c.
References _, remote_state::buf, remote_state::buf_size, error(), get_remote_state(), getpkt(), print_packet(), putpkt(), puts_filtered(), and remote_state::remote_desc.
static enum packet_result packet_ok (const char * buf, struct packet_config * config) [static]
Definition at line 1254 of file remote.c.
References _, AUTO_BOOLEAN_AUTO, packet_config::detect, error(), fprintf_unfiltered(), gdb_stdlog, internal_error(), packet_config::name, packet_check_result(), PACKET_DISABLE, PACKET_ENABLE, PACKET_ERROR, PACKET_OK, PACKET_SUPPORT_UNKNOWN, PACKET_UNKNOWN, remote_debug, packet_config::support, and packet_config::title.
Referenced by extended_remote_attach_1(), extended_remote_run(), fetch_register_using_p(), remote_check_symbols(), remote_disable_btrace(), remote_enable_btrace(), remote_get_thread_local_address(), remote_get_tib_address(), remote_get_trace_status(), remote_hostio_send_command(), remote_insert_breakpoint(), remote_insert_hw_breakpoint(), remote_insert_watchpoint(), remote_pass_signals(), remote_program_signals(), remote_query_attached(), remote_query_supported(), remote_read_qxfer(), remote_remove_hw_breakpoint(), remote_remove_watchpoint(), remote_search_memory(), remote_set_trace_buffer_size(), remote_start_remote(), remote_vcont_probe(), remote_vkill(), remote_write_qxfer(), and store_register_using_P().
static struct packet_reg* packet_reg_from_pnum (struct remote_arch_state * rsa, LONGEST pnum) [static, read]
Definition at line 801 of file remote.c.
References gdbarch_num_regs(), packet_reg::pnum, remote_arch_state::regs, and target_gdbarch().
Referenced by remote_parse_stop_reply().
static struct packet_reg* packet_reg_from_regnum (struct remote_arch_state * rsa, long regnum) [static, read]
Definition at line 787 of file remote.c.
References gdb_assert, gdbarch_num_regs(), regnum, packet_reg::regnum, remote_arch_state::regs, and target_gdbarch().
Referenced by remote_fetch_registers(), and remote_store_registers().
static int parse_threadlist_response (char * pkt, int result_limit, threadref * original_echo, threadref * resultlist, int * doneflag) [static]
Definition at line 2473 of file remote.c.
References remote_state::buf_size, BUF_THREAD_ID_SIZE, get_remote_state(), unpack_byte(), unpack_nibble(), and unpack_threadid().
Referenced by remote_get_threadlist().
static int peek_stop_reply (ptid_t ptid) [static]
Definition at line 5569 of file remote.c.
References QUEUE_iterate, and stop_reply_match_ptid_and_ws().
Referenced by remote_stop_ns(), and set_stop_requested_callback().
static void print_packet (char * buf) [static]
Definition at line 7237 of file remote.c.
References fputstr_filtered(), gdb_stdout, and puts_filtered().
Referenced by packet_command().
static void process_g_packet (struct regcache * regcache) [static]
Definition at line 6235 of file remote.c.
References _, remote_arch_state::actual_register_packet_size, remote_state::buf, error(), fromhex(), gdb_assert, gdbarch_num_regs(), get_regcache_arch(), get_remote_arch_state(), get_remote_state(), packet_reg::in_g_packet, internal_error(), memset(), packet_reg::offset, packet_reg::pnum, regcache_raw_supply(), packet_reg::regnum, remote_arch_state::regs, and remote_arch_state::sizeof_g_packet.
Referenced by fetch_registers_using_g().
static ptid_t process_stop_reply (struct stop_reply * stop_reply, struct target_waitstatus * status) [static]
Definition at line 5864 of file remote.c.
References private_thread_info::core, cached_reg::data, demand_private_info(), get_remote_state(), get_thread_arch_regcache(), inferior_ptid, target_waitstatus::kind, null_ptid, cached_reg::num, regcache::ptid, stop_reply::ptid, ptid_equal(), regcache_raw_supply(), remote_notice_new_inferior(), remote_state::remote_stopped_by_watchpoint_p, remote_state::remote_watch_data_address, stop_reply_xfree(), target_gdbarch(), TARGET_WAITKIND_EXITED, TARGET_WAITKIND_SIGNALLED, VEC_free, VEC_iterate, and stop_reply::ws.
Referenced by remote_wait_as(), and remote_wait_ns().
static void push_stop_reply (struct stop_reply * new_event) [static]
Definition at line 5540 of file remote.c.
References fprintf_unfiltered(), gdb_stdlog, mark_async_event_handler(), notif_debug, stop_reply::ptid, QUEUE_enque, QUEUE_length, and target_pid_to_str().
Referenced by extended_remote_attach_1(), and remote_notif_stop_ack().
int putpkt (char * buf)
Definition at line 7245 of file remote.c.
References putpkt_binary().
Referenced by extended_remote_attach_1(), extended_remote_disable_randomization(), extended_remote_kill(), extended_remote_mourn_1(), extended_remote_restart(), extended_remote_run(), fetch_register_using_p(), get_offsets(), packet_command(), putpkt_for_catch_errors(), remote_check_symbols(), remote_current_thread(), remote_detach_1(), remote_disable_btrace(), remote_disable_tracepoint(), remote_download_command_source(), remote_download_trace_state_variable(), remote_download_tracepoint(), remote_enable_btrace(), remote_enable_tracepoint(), remote_fileio_reply(), remote_get_min_fast_tracepoint_insn_len(), remote_get_noisy_reply(), remote_get_raw_trace_data(), remote_get_thread_local_address(), remote_get_threadinfo(), remote_get_threadlist(), remote_get_tib_address(), remote_get_trace_state_variable_value(), remote_get_trace_status(), remote_get_tracepoint_status(), remote_insert_breakpoint(), remote_insert_hw_breakpoint(), remote_insert_watchpoint(), remote_notif_stop_ack(), remote_pass_signals(), remote_program_signals(), remote_query_attached(), remote_query_supported(), remote_rcmd(), remote_read_bytes(), remote_read_qxfer(), remote_remove_breakpoint(), remote_remove_hw_breakpoint(), remote_remove_watchpoint(), remote_resume(), remote_save_trace_data(), remote_send(), remote_send_printf(), remote_set_circular_trace_buffer(), remote_set_disconnected_tracing(), remote_set_permissions(), remote_set_trace_buffer_size(), remote_set_trace_notes(), remote_start_remote(), remote_static_tracepoint_marker_at(), remote_stop_ns(), remote_thread_alive(), remote_threads_extra_info(), remote_threads_info(), remote_trace_find(), remote_trace_init(), remote_trace_set_readonly_regions(), remote_trace_start(), remote_trace_stop(), remote_upload_trace_state_variables(), remote_upload_tracepoints(), remote_use_agent(), remote_vcont_probe(), remote_vcont_resume(), remote_verify_memory(), remote_vkill(), remote_wait_as(), remote_xfer_partial(), set_thread(), store_register_using_P(), and store_registers_using_G().
static int putpkt_binary (char * buf, int cnt) [static]
Definition at line 7257 of file remote.c.
References _, remote_state::buf, remote_state::buf_size, remote_state::cached_wait_status, do_cleanups(), error(), escape_buffer(), fprintf_unfiltered(), fputc_unfiltered(), gdb_flush(), gdb_stdlog, get_remote_state(), handle_notification(), interrupt_query(), make_cleanup(), remote_state::noack_mode, non_stop, remote_state::notif_state, putchar_unfiltered(), read_frame(), readchar(), remote_debug, remote_serial_write(), remote_timeout, SERIAL_TIMEOUT, skip_frame(), target_can_async_p, tohex(), remote_state::waiting_for_stop_reply, and xfree().
Referenced by check_binary_download(), putpkt(), remote_hostio_send_command(), remote_search_memory(), remote_write_bytes_aux(), and remote_write_qxfer().
static int putpkt_for_catch_errors (void * arg) [static]
Definition at line 7812 of file remote.c.
References putpkt().
Referenced by remote_kill().
static QUEUE (stop_reply_p) [static]
Definition at line 5303 of file remote.c.
References notif_event_xfree().
static struct stop_reply* queued_stop_reply (ptid_t ptid) [static, read]
Definition at line 5524 of file remote.c.
References mark_async_event_handler(), QUEUE_is_empty, and remote_notif_remove_queued_reply().
Referenced by remote_wait_as(), and remote_wait_ns().
static long read_frame (char ** buf_p, long * sizeof_buf) [static]
Definition at line 7495 of file remote.c.
References _, do_cleanups(), escape_buffer(), fprintf_unfiltered(), fputs_filtered(), fromhex(), gdb_stdlog, get_remote_state(), make_cleanup(), memset(), remote_state::noack_mode, printf_filtered(), readchar(), remote_debug, remote_timeout, SERIAL_TIMEOUT, xfree(), and xrealloc().
Referenced by getpkt_or_notif_sane_1(), and putpkt_binary().
static ptid_t read_ptid (char * buf, char ** obuf) [static]
Definition at line 2026 of file remote.c.
References _, remote_state::buf, error(), inferior_ptid, null_ptid, p, ptid_build(), ptid_equal(), ptid_get_pid(), ULONGEST, and unpack_varlen_hex().
Referenced by remote_current_thread(), remote_parse_stop_reply(), remote_threads_info(), and stop_reply_extract_thread().
static int readchar (int timeout) [static]
Definition at line 7155 of file remote.c.
References _, get_remote_state(), remote_state::remote_desc, remote_unpush_target(), SERIAL_EOF, SERIAL_ERROR, serial_readchar(), SERIAL_TIMEOUT, TARGET_CLOSE_ERROR, throw_error(), and unpush_and_perror().
Referenced by getpkt_or_notif_sane_1(), putpkt_binary(), read_frame(), and skip_frame().
static void record_currthread (struct remote_state * rs, ptid_t currthread) [static]
Definition at line 1677 of file remote.c.
References remote_state::general_thread.
Referenced by extended_remote_attach_1(), extended_remote_mourn_1(), and remote_wait_as().
void register_remote_g_packet_guess (struct gdbarch * gdbarch, int bytes, const struct target_desc * tdesc)
Definition at line 9495 of file remote.c.
References _, remote_g_packet_guess::bytes, gdb_assert, gdbarch_data(), internal_error(), remote_g_packet_guess::tdesc, VEC_iterate, and VEC_safe_push.
Referenced by arm_register_g_packet_guesses(), and mips_register_g_packet_guesses().
void register_remote_support_xml (const char * xml)
Definition at line 4074 of file remote.c.
References strtok(), and xfree().
static struct inferior* remote_add_inferior (int fake_pid_p, int pid, int attached) [static, read]
Definition at line 1524 of file remote.c.
References add_inferior(), inferior::aspace, inferior::attach_flag, current_inferior(), current_program_space, inferior::fake_pid_p, gdbarch_has_global_solist(), arm-linux::inf, inferior_appeared(), maybe_new_address_space(), inferior::pspace, remote_query_attached(), and target_gdbarch().
Referenced by add_current_inferior_and_thread(), extended_remote_attach_1(), and remote_notice_new_inferior().
static void remote_add_target_side_commands (struct gdbarch * gdbarch, struct bp_target_info * bp_tgt, char * buf) [static]
Definition at line 8150 of file remote.c.
References agent_expr::buf, agent_expr::len, pack_hex_byte(), bp_target_info::persist, VEC_empty, VEC_free, and VEC_iterate.
Referenced by remote_insert_breakpoint(), and remote_insert_hw_breakpoint().
static int remote_add_target_side_condition (struct gdbarch * gdbarch, struct bp_target_info * bp_tgt, char * buf, char * buf_end) [static]
Definition at line 8117 of file remote.c.
References agent_expr::buf, agent_expr::len, pack_hex_byte(), VEC_empty, VEC_free, VEC_iterate, and xsnprintf().
Referenced by remote_insert_breakpoint(), and remote_insert_hw_breakpoint().
static void remote_add_thread (ptid_t ptid, int running) [static]
Definition at line 1565 of file remote.c.
References add_thread(), set_executing(), and set_running().
Referenced by remote_notice_new_inferior().
static CORE_ADDR remote_address_masked (CORE_ADDR addr) [static]
Definition at line 6601 of file remote.c.
References gdbarch_addr_bit(), remote_address_size, target_gdbarch(), and ULONGEST.
Referenced by remote_insert_breakpoint(), remote_insert_hw_breakpoint(), remote_insert_watchpoint(), remote_read_bytes(), remote_remove_breakpoint(), remote_remove_hw_breakpoint(), remote_remove_watchpoint(), remote_watchpoint_addr_within_range(), and remote_write_bytes_aux().
static void remote_async (void(*)(enum inferior_event_type event_type, void *context) callback, void * context) [static]
Definition at line 11653 of file remote.c.
References remote_state::async_client_callback, remote_state::async_client_context, get_remote_state(), remote_state::remote_desc, and serial_async().
Referenced by init_remote_ops().
static void remote_async_inferior_event_handler (gdb_client_data data) [static]
Definition at line 11647 of file remote.c.
References INF_REG_EVENT, and inferior_event_handler().
Referenced by remote_open_1().
static void remote_async_serial_handler (struct serial * scb, void * context) [static]
Definition at line 11637 of file remote.c.
References remote_state::async_client_callback, remote_state::async_client_context, and INF_REG_EVENT.
static int remote_augmented_libraries_svr4_read (void) [static]
Definition at line 11448 of file remote.c.
References remote_state::augmented_libraries_svr4_read, and get_remote_state().
Referenced by init_remote_ops().
static void remote_augmented_libraries_svr4_read_feature (const struct protocol_feature * feature, enum packet_support support, const char * value) [static]
Definition at line 3984 of file remote.c.
References remote_state::augmented_libraries_svr4_read, get_remote_state(), and PACKET_ENABLE.
static int remote_bfd_iovec_close (struct bfd * abfd, void * stream) [static]
Definition at line 10027 of file remote.c.
References remote_hostio_close(), and xfree().
Referenced by remote_bfd_open().
static void* remote_bfd_iovec_open (struct bfd * abfd, void * open_closure) [static]
Definition at line 10005 of file remote.c.
References gdb_assert, remote_fileio_errno_to_host(), remote_filename_p(), remote_hostio_open(), and xmalloc().
Referenced by remote_bfd_open().
static file_ptr remote_bfd_iovec_pread (struct bfd * abfd, void * stream, void * buf, file_ptr nbytes, file_ptr offset) [static]
Definition at line 10043 of file remote.c.
References remote_fileio_errno_to_host(), and remote_hostio_pread().
Referenced by remote_bfd_open().
static int remote_bfd_iovec_stat (struct bfd * abfd, void * stream, struct stat * sb) [static]
Definition at line 10072 of file remote.c.
Referenced by remote_bfd_open().
bfd* remote_bfd_open (const char * remote_file, const char * target)
Definition at line 10088 of file remote.c.
References gdb_bfd_openr_iovec(), remote_bfd_iovec_close(), remote_bfd_iovec_open(), remote_bfd_iovec_pread(), and remote_bfd_iovec_stat().
Referenced by gdb_bfd_open_maybe_remote(), solib_bfd_fopen(), and symfile_bfd_open().
static void remote_breakpoint_commands_feature (const struct protocol_feature * feature, enum packet_support support, const char * value) [static]
Definition at line 3913 of file remote.c.
References remote_state::breakpoint_commands, get_remote_state(), and PACKET_ENABLE.
static void remote_buffer_add_bytes (char ** buffer, int * left, const gdb_byte * bytes, int len) [static]
Definition at line 9594 of file remote.c.
References _, bin2hex(), error(), and len.
Referenced by remote_hostio_open(), remote_hostio_readlink(), and remote_hostio_unlink().
static void remote_buffer_add_int (char ** buffer, int * left, ULONGEST value) [static]
Definition at line 9615 of file remote.c.
References _, error(), hexnumlen(), hexnumstr(), and len.
Referenced by remote_hostio_close(), remote_hostio_open(), remote_hostio_pread(), and remote_hostio_pwrite().
static void remote_buffer_add_string (char ** buffer, int * left, char * string) [static]
Definition at line 9572 of file remote.c.
References _, error(), len, and memcpy().
Referenced by remote_hostio_close(), remote_hostio_open(), remote_hostio_pread(), remote_hostio_pwrite(), remote_hostio_readlink(), and remote_hostio_unlink().
static int remote_can_async_p (void) [static]
Definition at line 11605 of file remote.c.
References get_remote_state(), remote_state::remote_desc, serial_can_async_p(), and target_async_permitted.
Referenced by init_remote_ops().
static int remote_can_download_tracepoint (void) [static]
Definition at line 10674 of file remote.c.
References current_trace_status(), get_remote_state(), remote_get_trace_status(), remote_supports_install_in_trace(), trace_status::running, trace_status::running_known, remote_state::starting_up, and exsummary::status.
Referenced by init_remote_ops().
static int remote_can_execute_reverse (void) [static]
Definition at line 10327 of file remote.c.
References PACKET_bc, PACKET_bs, PACKET_ENABLE, and remote_protocol_packets.
Referenced by init_remote_ops().
static int remote_can_run_breakpoint_commands (void) [static]
Definition at line 10418 of file remote.c.
References remote_state::breakpoint_commands, and get_remote_state().
Referenced by init_remote_ops(), remote_insert_breakpoint(), and remote_insert_hw_breakpoint().
static int remote_can_use_agent (void) [static]
Definition at line 11298 of file remote.c.
References PACKET_DISABLE, PACKET_QAgent, and remote_protocol_packets.
Referenced by init_remote_ops().
static void remote_check_symbols (void) [static]
Definition at line 3679 of file remote.c.
References remote_state::buf, remote_state::buf_size, current_target, gdbarch_addr_bit(), gdbarch_convert_from_func_ptr_addr(), get_remote_packet_size(), get_remote_state(), getpkt(), hex2bin(), lookup_minimal_symbol(), PACKET_DISABLE, packet_ok(), PACKET_qSymbol, phex_nz(), putpkt(), remote_protocol_packets, set_general_process(), SYMBOL_VALUE_ADDRESS, target_gdbarch(), target_has_execution, and xsnprintf().
Referenced by remote_new_objfile(), and remote_start_remote().
static int remote_check_watch_resources (int type, int cnt, int ot) [static]
Definition at line 8403 of file remote.c.
References bp_hardware_breakpoint.
Referenced by init_remote_ops().
static void remote_close (void) [static]
Definition at line 3047 of file remote.c.
References delete_async_event_handler(), discard_all_inferiors(), discard_pending_stop_replies_in_queue(), get_remote_state(), inferior_ptid, remote_state::notif_state, null_ptid, remote_state::remote_desc, remote_notif_state_xfree(), remote_terminal_ours(), serial_close(), and trace_reset_local_state().
Referenced by init_remote_ops().
static void remote_command (char * args, int from_tty) [static]
Definition at line 10321 of file remote.c.
References gdb_stdout, and help_list().
static void remote_cond_breakpoint_feature (const struct protocol_feature * feature, enum packet_support support, const char * value) [static]
Definition at line 3903 of file remote.c.
References remote_state::cond_breakpoints, get_remote_state(), and PACKET_ENABLE.
static void remote_cond_tracepoint_feature (const struct protocol_feature * feature, enum packet_support support, const char * value) [static]
Definition at line 3893 of file remote.c.
References remote_state::cond_tracepoints, get_remote_state(), and PACKET_ENABLE.
static void remote_console_output (char * msg) [static]
Definition at line 5244 of file remote.c.
References fputs_unfiltered(), fromhex(), gdb_flush(), and gdb_stdtarg.
Referenced by remote_get_noisy_reply(), remote_rcmd(), remote_wait_as(), and remote_wait_ns().
static int remote_core_of_thread (struct target_ops * ops, ptid_t ptid) [static]
Definition at line 11119 of file remote.c.
References private_thread_info::core, find_thread_ptid(), and thread_info::private.
Referenced by init_remote_ops().
static ptid_t remote_current_thread (ptid_t oldptid) [static]
Definition at line 2618 of file remote.c.
References remote_state::buf, remote_state::buf_size, get_remote_state(), getpkt(), putpkt(), and read_ptid().
Referenced by add_current_inferior_and_thread(), extended_remote_attach_1(), and remote_start_remote().
static void remote_delete_command (char * args, int from_tty) [static]
Definition at line 10302 of file remote.c.
References _, do_cleanups(), error(), error_no_arg(), gdb_buildargv(), make_cleanup_freeargv(), and remote_file_delete().
static void remote_detach (struct target_ops * ops, char * args, int from_tty) [static]
Definition at line 4470 of file remote.c.
References remote_detach_1().
Referenced by init_remote_ops().
static void remote_detach_1 (char * args, int from_tty, int extended) [static]
Definition at line 4426 of file remote.c.
References _, remote_state::buf, remote_state::buf_size, error(), gdb_flush(), gdb_stdout, get_exec_file(), get_remote_packet_size(), get_remote_state(), getpkt(), inferior_ptid, pid_to_ptid(), printf_unfiltered(), ptid_get_pid(), putpkt(), puts_filtered(), remote_multi_process_p(), target_has_execution, target_mourn_inferior(), target_pid_to_str(), and xsnprintf().
Referenced by extended_remote_detach(), and remote_detach().
static void remote_disable_btrace (struct btrace_target_info * tinfo) [static]
Definition at line 11363 of file remote.c.
References _, remote_state::buf, remote_state::buf_size, error(), get_remote_packet_size(), get_remote_state(), getpkt(), packet_config::name, PACKET_ENABLE, PACKET_ERROR, packet_ok(), PACKET_Qbtrace_off, btrace_target_info::ptid, putpkt(), remote_protocol_packets, set_general_thread(), packet_config::support, target_pid_to_str(), xfree(), and xsnprintf().
Referenced by init_remote_ops().
static void remote_disable_tracepoint (struct bp_location * location) [static]
Definition at line 10741 of file remote.c.
References _, bp_location::address, remote_state::buf, remote_state::buf_size, error(), get_remote_packet_size(), get_remote_state(), breakpoint::number, bp_location::owner, putpkt(), remote_get_noisy_reply(), and xsnprintf().
Referenced by init_remote_ops().
static void remote_disconnect (struct target_ops * target, char * args, int from_tty) [static]
Definition at line 4484 of file remote.c.
References _, error(), puts_filtered(), and remote_mourn_1().
Referenced by init_remote_ops().
static void remote_disconnected_tracing_feature (const struct protocol_feature * feature, enum packet_support support, const char * value) [static]
Definition at line 3953 of file remote.c.
References remote_state::disconnected_tracing, get_remote_state(), and PACKET_ENABLE.
static void remote_download_command_source (int num, ULONGEST addr, struct command_line * cmds) [static]
Definition at line 10460 of file remote.c.
References _, command_line::body_list, remote_state::buf, remote_state::buf_size, command_line::control_type, encode_source_string(), get_remote_state(), command_line::line, command_line::next, putpkt(), QUIT, remote_get_noisy_reply(), target_buf, target_buf_size, warning(), while_control, and while_stepping_control.
Referenced by remote_download_tracepoint().
static void remote_download_trace_state_variable (struct trace_state_variable * tsv) [static]
Definition at line 10702 of file remote.c.
References _, bin2hex(), remote_state::buf, trace_state_variable::builtin, error(), get_remote_packet_size(), get_remote_state(), trace_state_variable::initial_value, trace_state_variable::name, trace_state_variable::number, phex(), putpkt(), remote_get_noisy_reply(), target_buf, target_buf_size, ULONGEST, and xsnprintf().
Referenced by init_remote_ops().
static void remote_download_tracepoint (struct bp_location * loc) [static]
Definition at line 10497 of file remote.c.
References _, breakpoint::addr_string, bp_location::address, bp_enabled, bp_fast_tracepoint, bp_static_tracepoint, breakpoint_commands(), agent_expr::buf, BUF_SIZE, breakpoint::commands, bp_location::cond, breakpoint::cond_string, default_collect, do_cleanups(), breakpoint::enable_state, encode_actions_rsp(), encode_source_string(), error(), free_actions_list_cleanup_wrapper(), gdbarch_fast_tracepoint_valid_at(), gen_eval_for_expr(), internal_error(), agent_expr::len, make_cleanup(), make_cleanup_free_agent_expr(), breakpoint::number, bp_location::owner, pack_hex_byte(), PACKET_ENABLE, PACKET_TracepointSource, tracepoint::pass_count, putpkt(), QUIT, remote_download_command_source(), remote_get_noisy_reply(), remote_protocol_packets, remote_supports_cond_tracepoints(), remote_supports_fast_tracepoints(), remote_supports_static_tracepoints(), tracepoint::step_count, target_buf, target_buf_size, target_gdbarch(), target_static_tracepoint_marker_at, breakpoint::type, warning(), and xsnprintf().
Referenced by init_remote_ops().
static struct btrace_target_info* remote_enable_btrace (ptid_t ptid) [static, read]
Definition at line 11327 of file remote.c.
References _, remote_state::buf, remote_state::buf_size, error(), get_remote_packet_size(), get_remote_state(), getpkt(), packet_config::name, PACKET_ENABLE, PACKET_ERROR, packet_ok(), PACKET_Qbtrace_bts, btrace_target_info::ptid, putpkt(), remote_protocol_packets, set_general_thread(), packet_config::support, target_pid_to_str(), xsnprintf(), and xzalloc().
Referenced by init_remote_ops().
static void remote_enable_disable_tracepoint_feature (const struct protocol_feature * feature, enum packet_support support, const char * value) [static]
Definition at line 3963 of file remote.c.
References remote_state::enable_disable_tracepoints, get_remote_state(), and PACKET_ENABLE.
static void remote_enable_tracepoint (struct bp_location * location) [static]
Definition at line 10724 of file remote.c.
References _, bp_location::address, remote_state::buf, remote_state::buf_size, error(), get_remote_packet_size(), get_remote_state(), breakpoint::number, bp_location::owner, putpkt(), remote_get_noisy_reply(), and xsnprintf().
Referenced by init_remote_ops().
static int remote_escape_output (const gdb_byte * buffer, int len, gdb_byte * out_buf, int * out_len, int out_maxlen) [static]
Definition at line 6630 of file remote.c.
References len.
Referenced by remote_hostio_pwrite(), remote_search_memory(), remote_write_bytes_aux(), and remote_write_qxfer().
static void remote_fast_tracepoint_feature (const struct protocol_feature * feature, enum packet_support support, const char * value) [static]
Definition at line 3923 of file remote.c.
References remote_state::fast_tracepoints, get_remote_state(), and PACKET_ENABLE.
static void remote_fetch_registers (struct target_ops * ops, struct regcache * regcache, int regnum) [static]
Definition at line 6355 of file remote.c.
References fetch_register_using_p(), fetch_registers_using_g(), gdb_assert, gdbarch_num_regs(), get_regcache_arch(), get_remote_arch_state(), packet_reg::in_g_packet, inferior_ptid, packet_reg_from_regnum(), regcache_raw_supply(), packet_reg::regnum, remote_arch_state::regs, set_general_thread(), and set_remote_traceframe().
Referenced by init_remote_ops().
void remote_file_delete (const char * remote_file, int from_tty)
Definition at line 10247 of file remote.c.
References _, error(), get_remote_state(), printf_filtered(), remote_state::remote_desc, remote_hostio_error(), and remote_hostio_unlink().
Referenced by mi_cmd_target_file_delete(), and remote_delete_command().
void remote_file_get (const char * remote_file, const char * local_file, int from_tty)
Definition at line 10191 of file remote.c.
References _, discard_cleanups(), do_cleanups(), error(), gdb_fopen_cloexec(), get_remote_packet_size(), get_remote_state(), make_cleanup(), make_cleanup_fclose(), offset, perror_with_name(), printf_filtered(), remote_state::remote_desc, remote_hostio_close(), remote_hostio_close_cleanup(), remote_hostio_error(), remote_hostio_open(), remote_hostio_pread(), ULONGEST, xfree(), and xmalloc().
Referenced by mi_cmd_target_file_get(), and remote_get_command().
void remote_file_put (const char * local_file, const char * remote_file, int from_tty)
Definition at line 10100 of file remote.c.
References _, discard_cleanups(), do_cleanups(), error(), gdb_fopen_cloexec(), get_remote_packet_size(), get_remote_state(), make_cleanup(), make_cleanup_fclose(), memmove(), offset, perror_with_name(), printf_filtered(), remote_state::remote_desc, remote_hostio_close(), remote_hostio_close_cleanup(), remote_hostio_error(), remote_hostio_open(), remote_hostio_pwrite(), ULONGEST, xfree(), and xmalloc().
Referenced by mi_cmd_target_file_put(), and remote_put_command().
static int remote_fileio_errno_to_host (int errnum) [static]
Definition at line 9933 of file remote.c.
Referenced by remote_bfd_iovec_open(), remote_bfd_iovec_pread(), and remote_hostio_error().
int remote_filename_p (const char * filename)
Definition at line 10080 of file remote.c.
References REMOTE_SYSROOT_PREFIX.
Referenced by gdb_bfd_open_maybe_remote(), remote_bfd_iovec_open(), solib_bfd_fopen(), solib_find(), and symfile_bfd_open().
static void remote_files_info (struct target_ops * ignore) [static]
Definition at line 7128 of file remote.c.
References puts_filtered().
Referenced by init_remote_ops().
static void remote_find_new_threads (void) [static]
Definition at line 2635 of file remote.c.
References CRAZY_MAX_THREADS, remote_newthread_step(), and remote_threadlist_iterator().
Referenced by remote_threads_info().
static void remote_flash_done (struct target_ops * ops) [static]
Definition at line 7105 of file remote.c.
References _, do_cleanups(), error(), make_cleanup(), PACKET_ERROR, PACKET_UNKNOWN, remote_flash_timeout, remote_send_printf(), remote_timeout, and restore_remote_timeout().
Referenced by init_remote_ops().
static void remote_flash_erase (struct target_ops * ops, ULONGEST address, LONGEST length) [static]
Definition at line 7060 of file remote.c.
References _, do_cleanups(), error(), gdbarch_addr_bit(), make_cleanup(), PACKET_ERROR, PACKET_UNKNOWN, phex(), remote_flash_timeout, remote_send_printf(), remote_timeout, restore_remote_timeout(), and target_gdbarch().
Referenced by init_remote_ops().
static LONGEST remote_flash_write (struct target_ops * ops, ULONGEST address, LONGEST length, const gdb_byte * data) [static]
Definition at line 7088 of file remote.c.
References do_cleanups(), LONGEST, make_cleanup(), remote_flash_timeout, remote_timeout, remote_write_bytes_aux(), and restore_remote_timeout().
Referenced by remote_xfer_partial().
static void* remote_g_packet_data_init (struct obstack * obstack) [static]
Definition at line 9489 of file remote.c.
References OBSTACK_ZALLOC.
static ptid_t remote_get_ada_task_ptid (long lwp, long thread) [static]
Definition at line 3023 of file remote.c.
References inferior_ptid, ptid_build(), and ptid_get_pid().
Referenced by init_remote_ops().
static void remote_get_command (char * args, int from_tty) [static]
Definition at line 10283 of file remote.c.
References _, do_cleanups(), error(), error_no_arg(), gdb_buildargv(), make_cleanup_freeargv(), and remote_file_get().
static int remote_get_min_fast_tracepoint_insn_len (void) [static]
Definition at line 11169 of file remote.c.
References remote_state::buf, get_remote_packet_size(), get_remote_state(), putpkt(), remote_get_noisy_reply(), set_general_process(), target_buf, target_buf_size, target_has_execution, ULONGEST, unpack_varlen_hex(), and xsnprintf().
Referenced by init_remote_ops().
static char* remote_get_noisy_reply (char ** buf_p, long * sizeof_buf) [static]
Definition at line 541 of file remote.c.
References _, gdb_exception::error, error(), exception_fprintf(), from, gdb_stderr, gdbarch_relocate_instruction(), getpkt(), MEMORY_ERROR, p, putpkt(), QUIT, gdb_exception::reason, remote_console_output(), RETURN_MASK_ALL, target_gdbarch(), to, trace_error(), TRY_CATCH, ULONGEST, unpack_varlen_hex(), and xsnprintf().
Referenced by extended_remote_disable_randomization(), remote_disable_tracepoint(), remote_download_command_source(), remote_download_trace_state_variable(), remote_download_tracepoint(), remote_enable_tracepoint(), remote_get_min_fast_tracepoint_insn_len(), remote_get_raw_trace_data(), remote_get_trace_state_variable_value(), remote_get_trace_status(), remote_get_tracepoint_status(), remote_save_trace_data(), remote_set_circular_trace_buffer(), remote_set_disconnected_tracing(), remote_set_trace_buffer_size(), remote_set_trace_notes(), remote_trace_find(), remote_trace_init(), remote_trace_start(), and remote_trace_stop().
static LONGEST remote_get_raw_trace_data (gdb_byte * buf, ULONGEST offset, LONGEST len) [static]
Definition at line 11060 of file remote.c.
References remote_state::buf, get_remote_state(), hex2bin(), hexnumstr(), putpkt(), remote_get_noisy_reply(), target_buf, and target_buf_size.
Referenced by init_remote_ops().
static CORE_ADDR remote_get_thread_local_address (struct target_ops * ops, ptid_t ptid, CORE_ADDR lm, CORE_ADDR offset) [static]
Definition at line 9381 of file remote.c.
References _, remote_state::buf, remote_state::buf_size, get_remote_packet_size(), get_remote_state(), getpkt(), hexnumstr(), PACKET_DISABLE, PACKET_OK, packet_ok(), PACKET_qGetTLSAddr, PACKET_UNKNOWN, putpkt(), remote_protocol_packets, throw_error(), TLS_GENERIC_ERROR, ULONGEST, unpack_varlen_hex(), and write_ptid().
Referenced by init_remote_ops().
static int remote_get_threadinfo (threadref * threadid, int fieldset, struct gdb_ext_thread_info * info) [static]
Definition at line 2437 of file remote.c.
References remote_state::buf, remote_state::buf_size, get_remote_state(), getpkt(), pack_threadinfo_request(), putpkt(), and remote_unpack_thread_info_response().
Referenced by remote_threads_extra_info().
static int remote_get_threadlist (int startflag, threadref * nextthread, int result_limit, int * done, int * result_count, threadref * threadlist) [static]
Definition at line 2501 of file remote.c.
References _, remote_state::buf, remote_state::buf_size, BUF_THREAD_ID_SIZE, remote_state::echo_nextthread, get_remote_packet_size(), get_remote_state(), getpkt(), pack_threadlist_request(), parse_threadlist_response(), putpkt(), threadmatch(), and warning().
Referenced by remote_threadlist_iterator().
static int remote_get_tib_address (ptid_t ptid, CORE_ADDR * addr) [static]
Definition at line 9429 of file remote.c.
References _, remote_state::buf, remote_state::buf_size, error(), get_remote_packet_size(), get_remote_state(), getpkt(), PACKET_DISABLE, PACKET_OK, packet_ok(), PACKET_qGetTIBAddr, PACKET_UNKNOWN, putpkt(), remote_protocol_packets, ULONGEST, unpack_varlen_hex(), and write_ptid().
Referenced by init_remote_ops().
static int remote_get_trace_state_variable_value (int tsvnum, LONGEST * val) [static]
Definition at line 11009 of file remote.c.
References remote_state::buf, get_remote_packet_size(), get_remote_state(), LONGEST, putpkt(), remote_get_noisy_reply(), set_remote_traceframe(), target_buf, target_buf_size, ULONGEST, unpack_varlen_hex(), and xsnprintf().
Referenced by init_remote_ops().
static int remote_get_trace_status (struct trace_status * ts) [static]
Definition at line 10819 of file remote.c.
References _, gdb_exception::error, error(), exception_fprintf(), trace_status::filename, gdb_stderr, get_remote_arch_state(), PACKET_DISABLE, packet_ok(), PACKET_qTStatus, PACKET_UNKNOWN, parse_trace_status(), putpkt(), gdb_exception::reason, remote_get_noisy_reply(), remote_protocol_packets, RETURN_MASK_ERROR, trace_status::running, remote_arch_state::sizeof_g_packet, target_buf, target_buf_size, TARGET_CLOSE_ERROR, throw_exception(), trace_regblock_size, and TRY_CATCH.
Referenced by init_remote_ops(), remote_can_download_tracepoint(), and remote_start_remote().
static void remote_get_tracepoint_status (struct breakpoint * bp, struct uploaded_tp * utp) [static]
Definition at line 10869 of file remote.c.
References uploaded_tp::addr, bp_location::address, tracepoint::base, remote_state::buf, get_remote_packet_size(), get_remote_state(), uploaded_tp::hit_count, breakpoint::hit_count, breakpoint::loc, bp_location::next, uploaded_tp::number, tracepoint::number_on_target, parse_tracepoint_status(), phex_nz(), putpkt(), remote_get_noisy_reply(), size, target_buf, target_buf_size, uploaded_tp::traceframe_usage, tracepoint::traceframe_usage, and xsnprintf().
Referenced by init_remote_ops().
static int remote_hostio_close (int fd, int * remote_errno) [static]
Definition at line 9861 of file remote.c.
References remote_state::buf, get_remote_packet_size(), get_remote_state(), PACKET_vFile_close, remote_buffer_add_int(), remote_buffer_add_string(), and remote_hostio_send_command().
Referenced by init_remote_ops(), remote_bfd_iovec_close(), remote_file_get(), remote_file_put(), and remote_hostio_close_cleanup().
static void remote_hostio_close_cleanup (void * opaque) [static]
Definition at line 9995 of file remote.c.
References remote_hostio_close().
Referenced by remote_file_get(), and remote_file_put().
static char* remote_hostio_error (int errnum) [static]
Definition at line 9984 of file remote.c.
References _, error(), remote_fileio_errno_to_host(), and safe_strerror().
Referenced by remote_file_delete(), remote_file_get(), and remote_file_put().
static int remote_hostio_open (const char * filename, int flags, int mode, int * remote_errno) [static]
Definition at line 9767 of file remote.c.
References remote_state::buf, get_remote_packet_size(), get_remote_state(), PACKET_vFile_open, remote_buffer_add_bytes(), remote_buffer_add_int(), remote_buffer_add_string(), and remote_hostio_send_command().
Referenced by init_remote_ops(), remote_bfd_iovec_open(), remote_file_get(), and remote_file_put().
static int remote_hostio_parse_result (char * buffer, int * retcode, int * remote_errno, char ** attachment) [static]
Definition at line 9642 of file remote.c.
Referenced by remote_hostio_send_command().
static int remote_hostio_pread (int fd, gdb_byte * read_buf, int len, ULONGEST offset, int * remote_errno) [static]
Definition at line 9822 of file remote.c.
References _, remote_state::buf, error(), get_remote_packet_size(), get_remote_state(), PACKET_vFile_pread, remote_buffer_add_int(), remote_buffer_add_string(), remote_hostio_send_command(), and remote_unescape_input().
Referenced by init_remote_ops(), remote_bfd_iovec_pread(), and remote_file_get().
static int remote_hostio_pwrite (int fd, const gdb_byte * write_buf, int len, ULONGEST offset, int * remote_errno) [static]
Definition at line 9794 of file remote.c.
References remote_state::buf, get_remote_packet_size(), get_remote_state(), PACKET_vFile_pwrite, remote_buffer_add_int(), remote_buffer_add_string(), remote_escape_output(), and remote_hostio_send_command().
Referenced by init_remote_ops(), and remote_file_put().
static char* remote_hostio_readlink (const char * filename, int * remote_errno) [static]
Definition at line 9899 of file remote.c.
References _, remote_state::buf, error(), get_remote_packet_size(), get_remote_state(), len, PACKET_vFile_readlink, remote_buffer_add_bytes(), remote_buffer_add_string(), remote_hostio_send_command(), remote_unescape_input(), and xmalloc().
Referenced by init_remote_ops().
static int remote_hostio_send_command (int command_bytes, int which_packet, int * remote_errno, char ** attachment, int * attachment_len) [static]
Definition at line 9698 of file remote.c.
References remote_state::buf, remote_state::buf_size, get_remote_state(), getpkt_sane(), PACKET_DISABLE, PACKET_ERROR, PACKET_OK, packet_ok(), PACKET_UNKNOWN, putpkt_binary(), remote_state::remote_desc, remote_hostio_parse_result(), remote_protocol_packets, and packet_config::support.
Referenced by remote_hostio_close(), remote_hostio_open(), remote_hostio_pread(), remote_hostio_pwrite(), remote_hostio_readlink(), and remote_hostio_unlink().
static int remote_hostio_unlink (const char * filename, int * remote_errno) [static]
Definition at line 9879 of file remote.c.
References remote_state::buf, get_remote_packet_size(), get_remote_state(), PACKET_vFile_unlink, remote_buffer_add_bytes(), remote_buffer_add_string(), and remote_hostio_send_command().
Referenced by init_remote_ops(), and remote_file_delete().
static int remote_insert_breakpoint (struct gdbarch * gdbarch, struct bp_target_info * bp_tgt) [static]
Definition at line 8185 of file remote.c.
References remote_state::buf, remote_state::buf_size, gdbarch_has_global_breakpoints(), gdbarch_remote_breakpoint_from_pc(), get_remote_packet_size(), get_remote_state(), getpkt(), hexnumstr(), memory_insert_breakpoint(), PACKET_DISABLE, PACKET_ERROR, PACKET_OK, packet_ok(), PACKET_UNKNOWN, PACKET_Z0, bp_target_info::placed_address, bp_target_info::placed_size, putpkt(), remote_add_target_side_commands(), remote_add_target_side_condition(), remote_address_masked(), remote_can_run_breakpoint_commands(), remote_protocol_packets, remote_supports_cond_breakpoints(), set_general_process(), target_gdbarch(), ULONGEST, and xsnprintf().
Referenced by init_remote_ops().
static int remote_insert_hw_breakpoint (struct gdbarch * gdbarch, struct bp_target_info * bp_tgt) [static]
Definition at line 8453 of file remote.c.
References _, remote_state::buf, remote_state::buf_size, error(), gdbarch_has_global_breakpoints(), gdbarch_remote_breakpoint_from_pc(), get_remote_packet_size(), get_remote_state(), getpkt(), hexnumstr(), internal_error(), PACKET_DISABLE, PACKET_ERROR, PACKET_OK, packet_ok(), PACKET_UNKNOWN, PACKET_Z1, bp_target_info::placed_address, bp_target_info::placed_size, putpkt(), remote_add_target_side_commands(), remote_add_target_side_condition(), remote_address_masked(), remote_can_run_breakpoint_commands(), remote_protocol_packets, remote_supports_cond_breakpoints(), set_general_process(), strchr(), target_gdbarch(), ULONGEST, and xsnprintf().
Referenced by init_remote_ops().
static int remote_insert_watchpoint (CORE_ADDR addr, int len, int type, struct expression * cond) [static]
Definition at line 8299 of file remote.c.
References _, remote_state::buf, remote_state::buf_size, gdbarch_has_global_breakpoints(), get_remote_packet_size(), get_remote_state(), getpkt(), hexnumstr(), internal_error(), PACKET_DISABLE, PACKET_ERROR, PACKET_OK, packet_ok(), PACKET_UNKNOWN, PACKET_Z0, putpkt(), remote_address_masked(), remote_protocol_packets, set_general_process(), strchr(), target_gdbarch(), ULONGEST, watchpoint_to_Z_packet(), and xsnprintf().
Referenced by init_remote_ops().
static void remote_install_in_trace_feature (const struct protocol_feature * feature, enum packet_support support, const char * value) [static]
Definition at line 3943 of file remote.c.
References get_remote_state(), remote_state::install_in_trace, and PACKET_ENABLE.
static int remote_is_async_p (void) [static]
Definition at line 11618 of file remote.c.
References get_remote_state(), remote_state::remote_desc, serial_is_async_p(), and target_async_permitted.
Referenced by init_remote_ops().
static void remote_kill (struct target_ops * ops) [static]
Definition at line 7818 of file remote.c.
References catch_errors(), putpkt_for_catch_errors(), RETURN_MASK_ERROR, and target_mourn_inferior().
Referenced by init_remote_ops().
static void remote_mourn (struct target_ops * ops) [static]
Definition at line 7881 of file remote.c.
References remote_mourn_1().
Referenced by init_remote_ops().
static void remote_mourn_1 (struct target_ops * target) [static]
Definition at line 7888 of file remote.c.
References generic_mourn_inferior(), and unpush_target().
Referenced by remote_disconnect(), and remote_mourn().
static void remote_multi_process_feature (const struct protocol_feature * feature, enum packet_support support, const char * value) [static]
Definition at line 3875 of file remote.c.
References get_remote_state(), remote_state::multi_process_aware, and PACKET_ENABLE.
static int remote_multi_process_p (struct remote_state * rs) [static]
Definition at line 449 of file remote.c.
References remote_state::multi_process_aware.
Referenced by add_current_inferior_and_thread(), append_resumption(), extended_remote_kill(), extended_remote_mourn_1(), remote_detach_1(), remote_notice_new_inferior(), remote_pid_to_str(), remote_query_attached(), remote_stop_ns(), remote_supports_multi_process(), set_general_process(), and write_ptid().
static void remote_new_objfile (struct objfile * objfile) [static]
Definition at line 11713 of file remote.c.
References get_remote_state(), remote_check_symbols(), and remote_state::remote_desc.
static int remote_newthread_step (threadref * ref, void * context) [static]
Definition at line 2605 of file remote.c.
References add_thread(), in_thread_list(), inferior_ptid, ptid_build(), ptid_get_pid(), and threadref_to_int().
Referenced by remote_find_new_threads().
static void remote_non_stop_feature (const struct protocol_feature * feature, enum packet_support support, const char * value) [static]
Definition at line 3884 of file remote.c.
References get_remote_state(), remote_state::non_stop_aware, and PACKET_ENABLE.
static void remote_notice_new_inferior (ptid_t currthread, int running) [static]
Definition at line 1580 of file remote.c.
References get_remote_state(), in_inferior_list(), in_thread_list(), inferior_ptid, is_exited(), notice_new_inferior(), inferior::pid, pid_to_ptid(), ptid_equal(), ptid_get_pid(), ptid_is_pid(), remote_add_inferior(), remote_add_thread(), remote_multi_process_p(), and thread_change_ptid().
Referenced by process_stop_reply(), and remote_threads_info().
void remote_notif_get_pending_events (struct notif_client * nc)
Definition at line 5826 of file remote.c.
References notif_client::ack, remote_state::buf, remote_state::buf_size, fprintf_unfiltered(), gdb_stdlog, get_remote_state(), getpkt(), notif_client::id, notif_client::name, notif_debug, remote_state::notif_state, remote_notif_state::pending_event, and remote_notif_ack().
Referenced by remote_notif_process(), remote_start_remote(), and remote_wait_ns().
static int remote_notif_remove_once_on_match (QUEUE(stop_reply_p)* q, QUEUE_ITER(stop_reply_p)* iter, stop_reply_p event, void * data) [static]
Definition at line 5479 of file remote.c.
References queue_iter_param::input, queue_iter_param::output, stop_reply::ptid, ptid_match(), and QUEUE_remove_elem.
Referenced by remote_notif_remove_queued_reply().
static struct stop_reply* remote_notif_remove_queued_reply (ptid_t ptid) [static, read]
Definition at line 5501 of file remote.c.
References fprintf_unfiltered(), gdb_stdlog, queue_iter_param::input, notif_debug, queue_iter_param::output, QUEUE_iterate, remote_notif_remove_once_on_match(), and target_pid_to_str().
Referenced by queued_stop_reply().
static void remote_notif_stop_ack (struct notif_client * self, char * buf, struct notif_event * event) [static]
Definition at line 5319 of file remote.c.
References _, error(), target_waitstatus::kind, push_stop_reply(), putpkt(), TARGET_WAITKIND_IGNORE, and stop_reply::ws.
static struct notif_event* remote_notif_stop_alloc_reply (void) [static, read]
Definition at line 5355 of file remote.c.
References notif_event::dtr, stop_reply_dtr(), and XMALLOC.
static int remote_notif_stop_can_get_pending_events (struct notif_client * self) [static]
Definition at line 5335 of file remote.c.
References mark_async_event_handler().
static void remote_notif_stop_parse (struct notif_client * self, char * buf, struct notif_event * event) [static]
Definition at line 5312 of file remote.c.
References remote_parse_stop_reply().
static void remote_open (char * name, int from_tty) [static]
Definition at line 3651 of file remote.c.
References remote_open_1(), and remote_ops.
Referenced by init_remote_ops().
static void remote_open_1 (char * name, int from_tty, struct target_ops * target, int extended_p) [static]
Definition at line 4263 of file remote.c.
References _, baud_rate, remote_state::cached_wait_status, remote_state::continue_thread, create_async_event_handler(), remote_state::ctrlc_pending_p, error(), remote_state::explicit_packet_size, remote_state::extended, remote_state::general_thread, get_remote_state(), have_inferiors(), init_all_packet_configs(), init_thread_list(), remote_state::last_pass_packet, remote_state::last_program_signals_packet, remote_state::multi_process_aware, no_shared_libraries(), remote_state::noack_mode, remote_state::non_stop_aware, not_sent_ptid, remote_state::notif_state, perror_with_name(), push_target(), puts_filtered(), query(), gdb_exception::reason, remote_async_inferior_event_handler(), remote_state::remote_desc, remote_fileio_reset(), remote_notif_state_allocate(), remote_serial_open(), remote_start_remote(), remote_state::remote_traceframe_number, remote_unpush_target(), reopen_exec_file(), reread_symbols(), RETURN_MASK_ALL, serial_close(), serial_flush_input(), serial_raw(), serial_setbaudrate(), target_async_permitted, target_preopen(), throw_exception(), TRY_CATCH, remote_state::use_threadextra_query, remote_state::use_threadinfo_query, remote_state::waiting_for_stop_reply, and xfree().
Referenced by extended_remote_open(), and remote_open().
static void remote_packet_size (const struct protocol_feature * feature, enum packet_support support, const char * value) [static]
Definition at line 3836 of file remote.c.
References _, remote_state::explicit_packet_size, get_remote_state(), MAX_REMOTE_PACKET_SIZE, protocol_feature::name, PACKET_ENABLE, and warning().
static void remote_parse_stop_reply (char * buf, struct stop_reply * event) [static]
Definition at line 5579 of file remote.c.
References _, cached_reg::data, error(), fromhex(), get_remote_arch_state(), get_remote_state(), hex2bin(), hex_string(), inferior_ptid, target_waitstatus::kind, LONGEST, non_stop, null_ptid, cached_reg::num, packet_reg_from_pnum(), pid_to_ptid(), stop_reply::ptid, ptid_equal(), ptid_get_pid(), read_ptid(), register_size(), packet_reg::regnum, strchr(), target_gdbarch(), TARGET_WAITKIND_EXITED, TARGET_WAITKIND_IGNORE, TARGET_WAITKIND_LOADED, TARGET_WAITKIND_NO_HISTORY, TARGET_WAITKIND_SIGNALLED, TARGET_WAITKIND_STOPPED, ULONGEST, unpack_varlen_hex(), VEC_safe_push, warning(), and stop_reply::ws.
Referenced by remote_notif_stop_parse().
static void remote_pass_signals (int numsigs, unsigned char * pass_signals) [static]
Definition at line 1686 of file remote.c.
References remote_state::buf, remote_state::buf_size, gdb_assert, get_remote_state(), getpkt(), remote_state::last_pass_packet, p, PACKET_DISABLE, packet_ok(), PACKET_QPassSignals, putpkt(), remote_protocol_packets, tohex(), xfree(), and xmalloc().
Referenced by init_remote_ops(), and remote_start_remote().
static char* remote_pid_to_str (struct target_ops * ops, ptid_t ptid) [static]
Definition at line 9335 of file remote.c.
References remote_state::buf, remote_state::extended, get_remote_state(), normal_pid_to_str(), null_ptid, ptid_equal(), ptid_get_pid(), ptid_get_tid(), ptid_is_pid(), remote_multi_process_p(), and xsnprintf().
Referenced by init_remote_ops().
static void remote_prepare_to_store (struct regcache * regcache) [static]
Definition at line 6406 of file remote.c.
References gdbarch_num_regs(), get_regcache_arch(), get_remote_arch_state(), packet_reg::in_g_packet, MAX_REGISTER_SIZE, PACKET_DISABLE, PACKET_ENABLE, PACKET_P, PACKET_SUPPORT_UNKNOWN, regcache_raw_read(), packet_reg::regnum, remote_arch_state::regs, and remote_protocol_packets.
Referenced by init_remote_ops().
static void remote_program_signals (int numsigs, unsigned char * signals) [static]
Definition at line 1738 of file remote.c.
References remote_state::buf, remote_state::buf_size, gdb_assert, get_remote_state(), getpkt(), remote_state::last_program_signals_packet, p, PACKET_DISABLE, packet_ok(), PACKET_QProgramSignals, putpkt(), remote_protocol_packets, signal_pass_state(), tohex(), xfree(), and xmalloc().
Referenced by init_remote_ops().
static void remote_put_command (char * args, int from_tty) [static]
Definition at line 10264 of file remote.c.
References _, do_cleanups(), error(), error_no_arg(), gdb_buildargv(), make_cleanup_freeargv(), and remote_file_put().
static int remote_query_attached (int pid) [static]
Definition at line 1481 of file remote.c.
References _, remote_state::buf, remote_state::buf_size, get_remote_packet_size(), get_remote_state(), getpkt(), PACKET_DISABLE, PACKET_ERROR, PACKET_OK, packet_ok(), PACKET_qAttached, PACKET_UNKNOWN, putpkt(), remote_multi_process_p(), remote_protocol_packets, size, warning(), and xsnprintf().
Referenced by remote_add_inferior().
static void remote_query_supported (void) [static]
Definition at line 4113 of file remote.c.
References _, remote_state::buf, remote_state::buf_size, protocol_feature::default_support, do_cleanups(), remote_state::explicit_packet_size, free_current_contents(), protocol_feature::func, get_remote_state(), getpkt(), make_cleanup(), memset(), name, cleanup::next, PACKET_DISABLE, PACKET_ENABLE, PACKET_ERROR, packet_ok(), PACKET_qSupported, PACKET_SUPPORT_UNKNOWN, putpkt(), remote_protocol_packets, remote_query_supported_append(), strchr(), warning(), and xrealloc().
Referenced by remote_start_remote().
static char* remote_query_supported_append (char * msg, const char * append) [static]
Definition at line 4104 of file remote.c.
Referenced by remote_query_supported().
static void remote_rcmd (char * command, struct ui_file * outbuf) [static]
Definition at line 9074 of file remote.c.
References _, bin2hex(), remote_state::buf, remote_state::buf_size, error(), fputc_unfiltered(), fromhex(), get_remote_packet_size(), get_remote_state(), getpkt_sane(), putpkt(), QUIT, remote_console_output(), remote_state::remote_desc, and strchr().
Referenced by init_remote_ops().
static LONGEST remote_read_bytes (CORE_ADDR memaddr, gdb_byte * myaddr, int len) [static]
Definition at line 6978 of file remote.c.
References remote_state::buf, remote_state::buf_size, get_memory_read_packet_size(), get_remote_state(), getpkt(), hex2bin(), hexnumstr(), min, putpkt(), remote_address_masked(), TARGET_XFER_E_IO, and ULONGEST.
Referenced by remote_xfer_partial().
static struct target_desc* remote_read_description (struct target_ops * target) [static, read]
Definition at line 9534 of file remote.c.
References remote_g_packet_guess::bytes, gdbarch_data(), inferior_ptid, null_ptid, ptid_equal(), send_g_packet(), target_gdbarch(), target_has_execution, remote_g_packet_guess::tdesc, VEC_empty, and VEC_iterate.
Referenced by init_remote_ops().
static int remote_read_description_p (struct target_ops * target) [static]
Definition at line 9522 of file remote.c.
References gdbarch_data(), target_gdbarch(), and VEC_empty.
Referenced by remote_start_remote().
static LONGEST remote_read_qxfer (struct target_ops * ops, const char * object_name, const char * annex, gdb_byte * readbuf, ULONGEST offset, LONGEST len, struct packet_config * packet) [static]
Definition at line 8709 of file remote.c.
References _, remote_state::buf, remote_state::buf_size, error(), remote_state::finished_annex, remote_state::finished_object, remote_state::finished_offset, get_remote_packet_size(), get_remote_state(), getpkt_sane(), LONGEST, min, PACKET_DISABLE, PACKET_OK, packet_ok(), phex_nz(), putpkt(), remote_unescape_input(), packet_config::support, and xfree().
Referenced by remote_xfer_partial().
static int remote_region_ok_for_hw_watchpoint (CORE_ADDR addr, int len) [static]
Definition at line 8390 of file remote.c.
Referenced by init_remote_ops().
int remote_register_number_and_offset (struct gdbarch * gdbarch, int regnum, int * pnum, int * poffset)
Definition at line 699 of file remote.c.
References do_cleanups(), gdb_assert, gdbarch_num_regs(), make_cleanup(), map_regcache_remote_table(), packet_reg::offset, packet_reg::pnum, regnum, xcalloc(), and xfree().
Referenced by regcache_dump().
static int remote_remove_breakpoint (struct gdbarch * gdbarch, struct bp_target_info * bp_tgt) [static]
Definition at line 8245 of file remote.c.
References remote_state::buf, remote_state::buf_size, gdbarch_has_global_breakpoints(), get_remote_packet_size(), get_remote_state(), getpkt(), hexnumstr(), memory_remove_breakpoint(), PACKET_DISABLE, PACKET_Z0, bp_target_info::placed_address, bp_target_info::placed_size, putpkt(), remote_address_masked(), remote_protocol_packets, set_general_process(), target_gdbarch(), ULONGEST, and xsnprintf().
Referenced by init_remote_ops().
static int remote_remove_hw_breakpoint (struct gdbarch * gdbarch, struct bp_target_info * bp_tgt) [static]
Definition at line 8517 of file remote.c.
References _, remote_state::buf, remote_state::buf_size, gdbarch_has_global_breakpoints(), get_remote_packet_size(), get_remote_state(), getpkt(), hexnumstr(), internal_error(), PACKET_DISABLE, PACKET_ERROR, PACKET_OK, packet_ok(), PACKET_UNKNOWN, PACKET_Z1, bp_target_info::placed_address, bp_target_info::placed_size, putpkt(), remote_address_masked(), remote_protocol_packets, set_general_process(), target_gdbarch(), ULONGEST, and xsnprintf().
Referenced by init_remote_ops().
static int remote_remove_watchpoint (CORE_ADDR addr, int len, int type, struct expression * cond) [static]
Definition at line 8348 of file remote.c.
References _, remote_state::buf, remote_state::buf_size, gdbarch_has_global_breakpoints(), get_remote_packet_size(), get_remote_state(), getpkt(), hexnumstr(), internal_error(), PACKET_DISABLE, PACKET_ERROR, PACKET_OK, packet_ok(), PACKET_UNKNOWN, PACKET_Z0, putpkt(), remote_address_masked(), remote_protocol_packets, set_general_process(), strchr(), target_gdbarch(), ULONGEST, watchpoint_to_Z_packet(), and xsnprintf().
Referenced by init_remote_ops().
static void remote_resume (struct target_ops * ops, ptid_t ptid, int step, enum gdb_signal siggnal) [static]
Definition at line 4920 of file remote.c.
References _, remote_state::buf, error(), EXEC_REVERSE, execution_direction, get_remote_state(), inferior_event_handler(), info_verbose, remote_state::last_sent_signal, remote_state::last_sent_step, minus_one_ptid, non_stop, notif_client_stop, remote_state::notif_state, PACKET_bc, PACKET_bs, PACKET_DISABLE, ptid_equal(), putpkt(), remote_notif_process(), remote_protocol_packets, remote_vcont_resume(), set_continue_thread(), target_async, target_can_async_p, tohex(), remote_state::waiting_for_stop_reply, and warning().
Referenced by init_remote_ops().
static int remote_save_trace_data (const char * filename) [static]
Definition at line 11033 of file remote.c.
References _, bin2hex(), remote_state::buf, error(), get_remote_packet_size(), get_remote_state(), putpkt(), remote_get_noisy_reply(), target_buf, and target_buf_size.
Referenced by init_remote_ops().
static int remote_search_memory (struct target_ops * ops, CORE_ADDR start_addr, ULONGEST search_space_len, const gdb_byte * pattern, ULONGEST pattern_len, CORE_ADDR * found_addrp) [static]
Definition at line 8983 of file remote.c.
References _, remote_state::buf, remote_state::buf_size, error(), gdbarch_addr_bit(), get_memory_write_packet_size(), get_remote_state(), getpkt_sane(), PACKET_DISABLE, PACKET_OK, packet_ok(), PACKET_qSearch_memory, phex_nz(), putpkt_binary(), remote_escape_output(), remote_protocol_packets, set_general_process(), simple_search_memory(), packet_config::support, target_gdbarch(), ULONGEST, and unpack_varlen_hex().
Referenced by init_remote_ops().
static void remote_send (char ** buf, long * sizeof_buf_p) [static]
Definition at line 7202 of file remote.c.
References _, error(), getpkt(), and putpkt().
Referenced by send_g_packet().
static enum packet_result remote_send_printf (const char * format, ...) [static]
Definition at line 7025 of file remote.c.
References _, remote_state::buf, remote_state::buf_size, error(), get_remote_packet_size(), get_remote_state(), getpkt(), internal_error(), packet_check_result(), and putpkt().
Referenced by remote_flash_done(), and remote_flash_erase().
static struct serial* remote_serial_open (char * name) [static, read]
Definition at line 3742 of file remote.c.
References _, serial_open(), and warning().
Referenced by remote_open_1().
static void remote_serial_write (const char * str, int len) [static]
Definition at line 7185 of file remote.c.
References _, get_remote_state(), remote_state::remote_desc, serial_write(), and unpush_and_perror().
Referenced by getpkt_or_notif_sane_1(), putpkt_binary(), and send_interrupt_sequence().
static void remote_set_circular_trace_buffer (int val) [static]
Definition at line 11129 of file remote.c.
References _, remote_state::buf, error(), get_remote_packet_size(), get_remote_state(), putpkt(), remote_get_noisy_reply(), target_buf, target_buf_size, and xsnprintf().
Referenced by init_remote_ops().
static void remote_set_disconnected_tracing (int val) [static]
Definition at line 11098 of file remote.c.
References _, remote_state::buf, remote_state::disconnected_tracing, error(), get_remote_packet_size(), get_remote_state(), putpkt(), remote_get_noisy_reply(), target_buf, target_buf_size, warning(), and xsnprintf().
Referenced by init_remote_ops().
void remote_set_permissions (void) [static]
Definition at line 3771 of file remote.c.
References _, remote_state::buf, remote_state::buf_size, get_remote_packet_size(), get_remote_state(), getpkt(), may_insert_breakpoints, may_insert_fast_tracepoints, may_insert_tracepoints, may_stop, may_write_memory, may_write_registers, putpkt(), warning(), and xsnprintf().
Referenced by init_remote_ops(), and remote_start_remote().
static void remote_set_trace_buffer_size (LONGEST val) [static]
Definition at line 11198 of file remote.c.
References _, remote_state::buf, remote_state::buf_size, gdb_assert, get_remote_packet_size(), get_remote_state(), hexnumstr(), PACKET_DISABLE, PACKET_OK, packet_ok(), PACKET_QTBuffer_size, putpkt(), remote_get_noisy_reply(), remote_protocol_packets, ULONGEST, warning(), and xsnprintf().
Referenced by init_remote_ops().
static int remote_set_trace_notes (const char * user, const char * notes, const char * stop_notes) [static]
Definition at line 11230 of file remote.c.
References _, bin2hex(), remote_state::buf, error(), get_remote_packet_size(), get_remote_state(), putpkt(), remote_get_noisy_reply(), target_buf, target_buf_size, and xsnprintf().
Referenced by init_remote_ops().
static void remote_start_remote (int from_tty, struct target_ops * target, int extended_p) [static]
Definition at line 3370 of file remote.c.
References _, add_current_inferior_and_thread(), AUTO_BOOLEAN_AUTO, AUTO_BOOLEAN_TRUE, auto_solib_add, breakpoints_always_inserted_mode(), remote_state::buf, remote_state::buf_size, remote_state::cached_wait_status, current_trace_status(), packet_config::detect, error(), exec_bfd, gdb_assert, gdbarch_has_global_breakpoints(), gdbarch_has_global_solist(), gdbarch_target_desc(), get_offsets(), get_remote_state(), getpkt(), notif_client::id, immediate_quit, arm-linux::inf, inferior_event_handler(), inferior_ptid, init_wait_for_inferior(), insert_breakpoints(), iterate_over_threads(), merge_uploaded_trace_state_variables(), merge_uploaded_tracepoints(), minus_one_ptid, remote_state::noack_mode, non_stop, remote_state::non_stop_aware, notif_client_stop, remote_state::notif_state, null_ptid, PACKET_DISABLE, PACKET_ENABLE, PACKET_OK, packet_ok(), PACKET_QAllow, PACKET_QStartNoAckMode, remote_notif_state::pending_event, printf_filtered(), ptid_equal(), putpkt(), QUIT, remote_check_symbols(), remote_current_thread(), remote_state::remote_desc, remote_get_trace_status(), remote_notif_get_pending_events(), remote_notif_parse(), remote_pass_signals(), remote_protocol_packets, remote_query_supported(), remote_read_description_p(), remote_set_permissions(), remote_threads_info(), remote_upload_trace_state_variables(), remote_upload_tracepoints(), send_interrupt_sequence(), serial_write(), set_continue_thread(), set_general_thread(), set_stop_requested_callback(), solib_add(), start_remote(), remote_state::starting_up, packet_config::support, target_async, target_can_async_p, target_clear_description(), target_find_description(), target_gdbarch(), target_has_execution, thread_count(), update_address_spaces(), and update_signals_program_target().
Referenced by remote_open_1().
static void remote_static_tracepoint_feature (const struct protocol_feature * feature, enum packet_support support, const char * value) [static]
Definition at line 3933 of file remote.c.
References get_remote_state(), PACKET_ENABLE, and remote_state::static_tracepoints.
static int remote_static_tracepoint_marker_at (CORE_ADDR addr, struct static_tracepoint_marker * marker) [static]
Definition at line 2943 of file remote.c.
References _, remote_state::buf, remote_state::buf_size, error(), get_remote_packet_size(), get_remote_state(), getpkt(), hexnumstr(), parse_static_tracepoint_marker_definition(), putpkt(), and xsnprintf().
Referenced by init_remote_ops().
static void remote_stop (ptid_t ptid) [static]
Definition at line 5164 of file remote.c.
References fprintf_unfiltered(), gdb_stdlog, non_stop, remote_debug, remote_stop_as(), and remote_stop_ns().
Referenced by init_remote_ops().
static void remote_stop_as (ptid_t ptid) [static]
Definition at line 5143 of file remote.c.
References remote_state::cached_wait_status, remote_state::ctrlc_pending_p, get_remote_state(), and send_interrupt_sequence().
Referenced by remote_stop().
static void remote_stop_ns (ptid_t ptid) [static]
Definition at line 5092 of file remote.c.
References _, remote_state::buf, remote_state::buf_size, error(), get_remote_packet_size(), get_remote_state(), getpkt(), minus_one_ptid, PACKET_SUPPORT_UNKNOWN, PACKET_vCont, peek_stop_reply(), ptid_build(), ptid_equal(), ptid_get_pid(), ptid_is_pid(), putpkt(), remote_multi_process_p(), remote_protocol_packets, remote_vcont_probe(), remote_state::supports_vCont, vCont_action_support::t, target_pid_to_str(), write_ptid(), and xsnprintf().
Referenced by remote_stop().
static int remote_stopped_by_watchpoint (void) [static]
Definition at line 8429 of file remote.c.
References get_remote_state(), and remote_state::remote_stopped_by_watchpoint_p.
Referenced by init_remote_ops(), and remote_stopped_data_address().
static int remote_stopped_data_address (struct target_ops * target, CORE_ADDR * addr_p) [static]
Definition at line 8437 of file remote.c.
References get_remote_state(), remote_stopped_by_watchpoint(), and remote_state::remote_watch_data_address.
Referenced by init_remote_ops().
static void remote_store_registers (struct target_ops * ops, struct regcache * regcache, int regnum) [static]
Definition at line 6513 of file remote.c.
References gdb_assert, gdbarch_num_regs(), get_regcache_arch(), get_remote_arch_state(), packet_reg::in_g_packet, inferior_ptid, packet_reg_from_regnum(), remote_arch_state::regs, set_general_thread(), set_remote_traceframe(), store_register_using_P(), and store_registers_using_G().
Referenced by init_remote_ops().
static void remote_string_tracing_feature (const struct protocol_feature * feature, enum packet_support support, const char * value) [static]
Definition at line 3973 of file remote.c.
References get_remote_state(), PACKET_ENABLE, and remote_state::string_tracing.
static void remote_supported_packet (const struct protocol_feature * feature, enum packet_support support, const char * argument) [static]
Definition at line 3819 of file remote.c.
References _, protocol_feature::name, protocol_feature::packet, PACKET_SUPPORT_UNKNOWN, remote_protocol_packets, packet_config::support, and warning().
static int remote_supports_btrace (void) [static]
Definition at line 11312 of file remote.c.
References PACKET_ENABLE, PACKET_Qbtrace_bts, PACKET_Qbtrace_off, PACKET_qXfer_btrace, and remote_protocol_packets.
Referenced by init_remote_ops().
static int remote_supports_cond_breakpoints (void) [static]
Definition at line 10370 of file remote.c.
References remote_state::cond_breakpoints, and get_remote_state().
Referenced by init_remote_ops(), remote_insert_breakpoint(), and remote_insert_hw_breakpoint().
static int remote_supports_cond_tracepoints (void) [static]
Definition at line 10362 of file remote.c.
References remote_state::cond_tracepoints, and get_remote_state().
Referenced by remote_download_tracepoint().
static int remote_supports_disable_randomization (void) [static]
Definition at line 10343 of file remote.c.
Referenced by init_remote_ops().
static int remote_supports_enable_disable_tracepoint (void) [static]
Definition at line 10402 of file remote.c.
References remote_state::enable_disable_tracepoints, and get_remote_state().
Referenced by init_remote_ops().
static int remote_supports_fast_tracepoints (void) [static]
Definition at line 10378 of file remote.c.
References remote_state::fast_tracepoints, and get_remote_state().
Referenced by remote_download_tracepoint().
static int remote_supports_install_in_trace (void) [static]
Definition at line 10394 of file remote.c.
References get_remote_state(), and remote_state::install_in_trace.
Referenced by remote_can_download_tracepoint().
static int remote_supports_multi_process (void) [static]
Definition at line 10350 of file remote.c.
References remote_state::extended, get_remote_state(), and remote_multi_process_p().
Referenced by init_remote_ops().
static int remote_supports_non_stop (void) [static]
Definition at line 10337 of file remote.c.
Referenced by init_remote_ops().
static int remote_supports_static_tracepoints (void) [static]
Definition at line 10386 of file remote.c.
References get_remote_state(), and remote_state::static_tracepoints.
Referenced by remote_download_tracepoint().
static int remote_supports_string_tracing (void) [static]
Definition at line 10410 of file remote.c.
References get_remote_state(), and remote_state::string_tracing.
Referenced by init_remote_ops().
static void remote_teardown_btrace (struct btrace_target_info * tinfo) [static]
Definition at line 11395 of file remote.c.
References xfree().
Referenced by init_remote_ops().
static void remote_terminal_inferior (void) [static]
Definition at line 5206 of file remote.c.
References async_initialize_sigint_signal_handler(), delete_file_handler(), input_fd, and target_async_permitted.
Referenced by init_remote_ops().
static void remote_terminal_ours (void) [static]
Definition at line 5229 of file remote.c.
References add_file_handler(), async_cleanup_sigint_signal_handler(), input_fd, stdin_event_handler(), and target_async_permitted.
Referenced by init_remote_ops(), and remote_close().
static int remote_thread_alive (struct target_ops * ops, ptid_t ptid) [static]
Definition at line 1860 of file remote.c.
References remote_state::buf, remote_state::buf_size, get_remote_packet_size(), get_remote_state(), getpkt(), p, ptid_equal(), ptid_get_pid(), ptid_get_tid(), putpkt(), and write_ptid().
Referenced by init_remote_ops().
static int remote_threadlist_iterator (rmt_thread_action stepfunction, void * context, int looplimit) [static]
Definition at line 2565 of file remote.c.
References _, copy_threadref(), get_remote_state(), MAXTHREADLISTRESULTS, remote_state::nextthread, remote_get_threadlist(), remote_state::resultthreadlist, and warning().
Referenced by remote_find_new_threads().
static char* remote_threads_extra_info (struct thread_info * tp) [static]
Definition at line 2862 of file remote.c.
References _, gdb_ext_thread_info::active, remote_state::buf, remote_state::buf_size, gdb_ext_thread_info::display, private_thread_info::extra, find_thread_ptid(), get_remote_packet_size(), get_remote_state(), getpkt(), hex2bin(), int_to_threadref(), internal_error(), min, gdb_ext_thread_info::more_display, PACKET_ENABLE, PACKET_qXfer_threads, thread_info::private, thread_info::ptid, ptid_equal(), ptid_get_pid(), ptid_get_tid(), putpkt(), remote_state::remote_desc, remote_get_threadinfo(), remote_protocol_packets, gdb_ext_thread_info::shortname, TAG_DISPLAY, TAG_EXISTS, TAG_MOREDISPLAY, TAG_THREADID, TAG_THREADNAME, remote_state::use_threadextra_query, write_ptid(), and xsnprintf().
Referenced by init_remote_ops().
static void remote_threads_info (struct target_ops * ops) [static]
Definition at line 2740 of file remote.c.
References _, remote_state::buf, remote_state::buf_size, private_thread_info::core, current_target, demand_private_info(), do_cleanups(), error(), private_thread_info::extra, free_current_contents(), gdb_xml_parse_quick(), get_remote_state(), getpkt(), make_cleanup(), new_thread(), non_stop, null_ptid, PACKET_ENABLE, PACKET_qXfer_threads, ptid_equal(), putpkt(), read_ptid(), remote_state::remote_desc, remote_find_new_threads(), remote_notice_new_inferior(), remote_protocol_packets, TARGET_OBJECT_THREADS, target_read_stralloc(), remote_state::use_threadinfo_query, VEC_iterate, and xfree().
Referenced by extended_remote_attach_1(), init_remote_ops(), and remote_start_remote().
static int remote_trace_find (enum trace_find_type type, int num, CORE_ADDR addr1, CORE_ADDR addr2, int * tpp) [static]
Definition at line 10927 of file remote.c.
References _, remote_state::buf, remote_state::buf_size, error(), get_remote_packet_size(), get_remote_state(), int, phex_nz(), putpkt(), remote_get_noisy_reply(), remote_state::remote_traceframe_number, set_remote_traceframe(), strchr(), tfind_number, tfind_outside, tfind_pc, tfind_range, tfind_tp, and xsnprintf().
Referenced by init_remote_ops().
static void remote_trace_init (void) [static]
Definition at line 10426 of file remote.c.
References _, error(), putpkt(), remote_get_noisy_reply(), target_buf, and target_buf_size.
Referenced by init_remote_ops().
static void remote_trace_set_readonly_regions (void) [static]
Definition at line 10758 of file remote.c.
References _, exec_bfd, getpkt(), offset, PACKET_ENABLE, PACKET_qXfer_traceframe_info, putpkt(), remote_protocol_packets, size, target_buf, target_buf_size, warning(), and xsnprintf().
Referenced by init_remote_ops().
static void remote_trace_start (void) [static]
Definition at line 10808 of file remote.c.
References _, error(), putpkt(), remote_get_noisy_reply(), target_buf, and target_buf_size.
Referenced by init_remote_ops().
static void remote_trace_stop (void) [static]
Definition at line 10916 of file remote.c.
References _, error(), putpkt(), remote_get_noisy_reply(), target_buf, and target_buf_size.
Referenced by init_remote_ops().
static struct traceframe_info* remote_traceframe_info (void) [static, read]
Definition at line 11144 of file remote.c.
References current_target, do_cleanups(), make_cleanup(), parse_traceframe_info(), TARGET_OBJECT_TRACEFRAME_INFO, target_read_stralloc(), and xfree().
Referenced by init_remote_ops().
static int remote_unescape_input (const gdb_byte * buffer, int len, gdb_byte * out_buf, int out_maxlen) [static]
Definition at line 6671 of file remote.c.
References _, error(), len, and warning().
Referenced by remote_hostio_pread(), remote_hostio_readlink(), and remote_read_qxfer().
static int remote_unpack_thread_info_response (char * pkt, threadref * expectedref, struct gdb_ext_thread_info * info) [static]
Definition at line 2344 of file remote.c.
References _, gdb_ext_thread_info::active, remote_state::buf_size, copy_threadref(), gdb_ext_thread_info::display, get_remote_state(), gdb_ext_thread_info::more_display, gdb_ext_thread_info::shortname, stub_unpack_int(), TAG_DISPLAY, TAG_EXISTS, TAG_MOREDISPLAY, TAG_THREADID, TAG_THREADNAME, gdb_ext_thread_info::threadid, threadmatch(), unpack_byte(), unpack_int(), unpack_string(), unpack_threadid(), and warning().
Referenced by remote_get_threadinfo().
static void remote_unpush_target (void) [static]
Definition at line 4257 of file remote.c.
References pop_all_targets_above(), and process_stratum.
Referenced by getpkt_or_notif_sane_1(), interrupt_query(), readchar(), remote_open_1(), and unpush_and_perror().
static int remote_upload_trace_state_variables (struct uploaded_tsv ** utsvp) [static]
Definition at line 11748 of file remote.c.
References remote_state::buf, remote_state::buf_size, get_remote_state(), getpkt(), parse_tsv_definition(), and putpkt().
Referenced by init_remote_ops(), and remote_start_remote().
static int remote_upload_tracepoints (struct uploaded_tp ** utpp) [static]
Definition at line 11727 of file remote.c.
References remote_state::buf, remote_state::buf_size, get_remote_state(), getpkt(), parse_tracepoint_definition(), and putpkt().
Referenced by init_remote_ops(), and remote_start_remote().
static int remote_use_agent (int use) [static]
Definition at line 11276 of file remote.c.
References remote_state::buf, remote_state::buf_size, get_remote_packet_size(), get_remote_state(), getpkt(), PACKET_DISABLE, PACKET_QAgent, putpkt(), remote_protocol_packets, use_agent, and xsnprintf().
Referenced by init_remote_ops().
static void remote_vcont_probe (struct remote_state * rs) [static]
Definition at line 4685 of file remote.c.
References remote_state::buf, remote_state::buf_size, getpkt(), packet_ok(), PACKET_vCont, putpkt(), vCont_action_support::r, remote_protocol_packets, strchr(), remote_state::supports_vCont, and vCont_action_support::t.
Referenced by remote_stop_ns(), remote_vcont_resume(), and set_range_stepping().
static int remote_vcont_resume (ptid_t ptid, int step, enum gdb_signal siggnal) [static]
Definition at line 4847 of file remote.c.
References _, append_pending_thread_resumptions(), append_resumption(), remote_state::buf, remote_state::buf_size, error(), gdb_assert, get_remote_packet_size(), get_remote_state(), getpkt(), inferior_ptid, minus_one_ptid, non_stop, PACKET_DISABLE, PACKET_SUPPORT_UNKNOWN, PACKET_vCont, ptid_equal(), ptid_is_pid(), putpkt(), remote_protocol_packets, remote_vcont_probe(), and xsnprintf().
Referenced by remote_resume().
static int remote_verify_memory (struct target_ops * ops, const gdb_byte * data, CORE_ADDR lma, ULONGEST size) [static]
Definition at line 8559 of file remote.c.
References _, remote_state::buf, remote_state::buf_size, error(), fromhex(), get_remote_packet_size(), get_remote_state(), getpkt(), putpkt(), set_general_process(), and xsnprintf().
Referenced by init_remote_ops().
static int remote_vkill (int pid, struct remote_state * rs) [static]
Definition at line 7830 of file remote.c.
References remote_state::buf, remote_state::buf_size, get_remote_packet_size(), getpkt(), PACKET_DISABLE, PACKET_OK, packet_ok(), PACKET_vKill, putpkt(), remote_protocol_packets, and xsnprintf().
Referenced by extended_remote_kill().
static ptid_t remote_wait (struct target_ops * ops, ptid_t ptid, struct target_waitstatus * status, int options) [static]
Definition at line 6119 of file remote.c.
References mark_async_event_handler(), non_stop, QUEUE_is_empty, remote_wait_as(), remote_wait_ns(), and target_can_async_p.
Referenced by init_remote_ops().
static ptid_t remote_wait_as (ptid_t ptid, struct target_waitstatus * status, int options) [static]
Definition at line 5970 of file remote.c.
References _, remote_state::buf, remote_state::buf_size, remote_state::cached_wait_status, check_quit_flag(), clear_quit_flag(), remote_state::ctrlc_pending_p, gdb_signal_to_name(), get_remote_state(), getpkt_or_notif_sane(), inferior_ptid, target_waitstatus::integer, target_waitstatus::kind, remote_state::last_sent_signal, remote_state::last_sent_step, minus_one_ptid, null_ptid, ofunc, printf_filtered(), process_stop_reply(), ptid_equal(), putpkt(), queued_stop_reply(), record_currthread(), remote_console_output(), remote_fileio_request(), remote_notif_parse(), remote_state::remote_stopped_by_watchpoint_p, target_waitstatus::sig, sync_remote_interrupt(), target_is_async_p, target_terminal_inferior(), target_terminal_ours_for_output, TARGET_WAITKIND_EXITED, TARGET_WAITKIND_IGNORE, TARGET_WAITKIND_SIGNALLED, TARGET_WAITKIND_STOPPED, TARGET_WNOHANG, target_waitstatus::value, remote_state::waiting_for_stop_reply, and warning().
Referenced by remote_wait().
static ptid_t remote_wait_ns (ptid_t ptid, struct target_waitstatus * status, int options) [static]
Definition at line 5911 of file remote.c.
References _, remote_state::buf, remote_state::buf_size, get_remote_state(), getpkt_or_notif_sane(), notif_client::id, target_waitstatus::kind, minus_one_ptid, remote_state::notif_state, remote_notif_state::pending_event, process_stop_reply(), queued_stop_reply(), remote_console_output(), remote_notif_get_pending_events(), TARGET_WAITKIND_IGNORE, TARGET_WNOHANG, and warning().
Referenced by remote_wait().
static int remote_watchpoint_addr_within_range (struct target_ops * target, CORE_ADDR addr, CORE_ADDR start, int length) [static]
Definition at line 8338 of file remote.c.
References remote_address_masked().
Referenced by init_remote_ops().
static LONGEST remote_write_bytes (CORE_ADDR memaddr, const gdb_byte * myaddr, ssize_t len) [static]
Definition at line 6942 of file remote.c.
References _, check_binary_download(), internal_error(), PACKET_DISABLE, PACKET_ENABLE, PACKET_SUPPORT_UNKNOWN, PACKET_X, remote_protocol_packets, and remote_write_bytes_aux().
Referenced by remote_xfer_partial().
static LONGEST remote_write_bytes_aux (const char * header, CORE_ADDR memaddr, const gdb_byte * myaddr, ssize_t len, char packet_format, int use_length) [static]
Definition at line 6786 of file remote.c.
References _, bin2hex(), remote_state::buf, remote_state::buf_size, get_memory_write_packet_size(), get_remote_state(), getpkt(), hexnumlen(), hexnumnstr(), hexnumstr(), internal_error(), min, putpkt_binary(), remote_address_masked(), REMOTE_ALIGN_WRITES, remote_escape_output(), TARGET_XFER_E_IO, and ULONGEST.
Referenced by remote_flash_write(), and remote_write_bytes().
static LONGEST remote_write_qxfer (struct target_ops * ops, const char * object_name, const char * annex, const gdb_byte * writebuf, ULONGEST offset, LONGEST len, struct packet_config * packet) [static]
Definition at line 8668 of file remote.c.
References remote_state::buf, remote_state::buf_size, get_memory_write_packet_size(), get_remote_state(), getpkt_sane(), PACKET_DISABLE, PACKET_OK, packet_ok(), phex_nz(), putpkt_binary(), remote_escape_output(), packet_config::support, ULONGEST, and unpack_varlen_hex().
Referenced by remote_xfer_partial().
static LONGEST remote_xfer_partial (struct target_ops * ops, enum target_object object, const char * annex, gdb_byte * readbuf, const gdb_byte * writebuf, ULONGEST offset, LONGEST len) [static]
Definition at line 8782 of file remote.c.
References _, remote_state::buf, remote_state::buf_size, error(), gdb_assert, get_remote_packet_size(), get_remote_state(), getpkt(), inferior_ptid, LONGEST, PACKET_qXfer_auxv, PACKET_qXfer_btrace, PACKET_qXfer_fdpic, PACKET_qXfer_features, PACKET_qXfer_libraries, PACKET_qXfer_libraries_svr4, PACKET_qXfer_memory_map, PACKET_qXfer_osdata, PACKET_qXfer_siginfo_read, PACKET_qXfer_siginfo_write, PACKET_qXfer_spu_read, PACKET_qXfer_spu_write, PACKET_qXfer_statictrace_read, PACKET_qXfer_threads, PACKET_qXfer_traceframe_info, PACKET_qXfer_uib, putpkt(), remote_state::remote_desc, remote_flash_write(), remote_protocol_packets, remote_read_bytes(), remote_read_qxfer(), remote_write_bytes(), remote_write_qxfer(), set_general_thread(), set_remote_traceframe(), target_has_execution, TARGET_OBJECT_AUXV, TARGET_OBJECT_AVAILABLE_FEATURES, TARGET_OBJECT_AVR, TARGET_OBJECT_BTRACE, TARGET_OBJECT_FDPIC, TARGET_OBJECT_FLASH, TARGET_OBJECT_LIBRARIES, TARGET_OBJECT_LIBRARIES_SVR4, TARGET_OBJECT_MEMORY, TARGET_OBJECT_MEMORY_MAP, TARGET_OBJECT_OPENVMS_UIB, TARGET_OBJECT_OSDATA, TARGET_OBJECT_SIGNAL_INFO, TARGET_OBJECT_SPU, TARGET_OBJECT_STATIC_TRACE_DATA, TARGET_OBJECT_THREADS, and TARGET_OBJECT_TRACEFRAME_INFO.
Referenced by init_remote_ops().
static int remove_stop_reply_for_inferior (QUEUE(stop_reply_p)* q, QUEUE_ITER(stop_reply_p)* iter, stop_reply_p event, void * data) [static]
Definition at line 5390 of file remote.c.
References queue_iter_param::input, inferior::pid, stop_reply::ptid, ptid_get_pid(), QUEUE_remove_elem, and stop_reply_xfree().
Referenced by discard_pending_stop_replies().
static int remove_stop_reply_of_remote_state (QUEUE(stop_reply_p)* q, QUEUE_ITER(stop_reply_p)* iter, stop_reply_p event, void * data) [static]
Definition at line 5444 of file remote.c.
References queue_iter_param::input, QUEUE_remove_elem, stop_reply::rs, and stop_reply_xfree().
Referenced by discard_pending_stop_replies_in_queue().
static void restore_remote_timeout (void * p) [static]
Definition at line 7047 of file remote.c.
References remote_timeout.
Referenced by remote_flash_done(), remote_flash_erase(), and remote_flash_write().
static int send_g_packet (void) [static]
Definition at line 6203 of file remote.c.
References _, remote_state::buf, remote_state::buf_size, error(), fprintf_unfiltered(), gdb_stdlog, get_remote_packet_size(), get_remote_state(), getpkt(), remote_debug, remote_send(), and xsnprintf().
Referenced by fetch_registers_using_g(), and remote_read_description().
static void send_interrupt_sequence (void) [static]
Definition at line 3256 of file remote.c.
References _, get_remote_state(), internal_error(), remote_state::remote_desc, remote_serial_write(), and serial_send_break().
Referenced by remote_start_remote(), and remote_stop_as().
static void set_continue_thread (struct ptid ptid) [static]
Referenced by remote_resume(), and remote_start_remote().
static void set_continue_thread (struct ptid ptid) [static]
Definition at line 1826 of file remote.c.
References set_thread().
static void set_general_process (void) [static]
Definition at line 1841 of file remote.c.
References remote_state::extended, remote_state::general_thread, get_remote_state(), inferior_ptid, ptid_get_pid(), remote_multi_process_p(), and set_general_thread().
Referenced by compare_sections_command(), remote_check_symbols(), remote_get_min_fast_tracepoint_insn_len(), remote_insert_breakpoint(), remote_insert_hw_breakpoint(), remote_insert_watchpoint(), remote_remove_breakpoint(), remote_remove_hw_breakpoint(), remote_remove_watchpoint(), remote_search_memory(), and remote_verify_memory().
static void set_general_thread (struct ptid ptid) [static]
Referenced by remote_disable_btrace(), remote_enable_btrace(), remote_fetch_registers(), remote_start_remote(), remote_store_registers(), remote_xfer_partial(), and set_general_process().
static void set_general_thread (struct ptid ptid) [static]
Definition at line 1820 of file remote.c.
References set_thread().
static void set_memory_packet_size (char * args, struct memory_packet_config * config) [static]
Definition at line 1000 of file remote.c.
References _, error(), memory_packet_config::fixed_p, MAX_REMOTE_PACKET_SIZE, memory_packet_config::name, query(), size, and memory_packet_config::size.
Referenced by set_memory_read_packet_size(), and set_memory_write_packet_size().
static void set_memory_read_packet_size (char * args, int from_tty) [static]
Definition at line 1083 of file remote.c.
References set_memory_packet_size().
static void set_memory_write_packet_size (char * args, int from_tty) [static]
Definition at line 1060 of file remote.c.
References set_memory_packet_size().
static void set_range_stepping (char * ignore_args, int from_tty, struct cmd_list_element * c) [static]
Definition at line 11783 of file remote.c.
References _, get_remote_state(), PACKET_ENABLE, PACKET_SUPPORT_UNKNOWN, PACKET_vCont, vCont_action_support::r, remote_state::remote_desc, remote_protocol_packets, remote_vcont_probe(), remote_state::supports_vCont, and warning().
static void set_remote_cmd (char * args, int from_tty) [static]
Definition at line 11669 of file remote.c.
References gdb_stdout, and help_list().
static void set_remote_protocol_packet_cmd (char * args, int from_tty, struct cmd_list_element * c) [static]
Definition at line 1378 of file remote.c.
References _, packet_config::detect, internal_error(), cmd_list_element::name, PACKET_MAX, remote_protocol_packets, update_packet_config(), and cmd_list_element::var.
Referenced by add_packet_config_cmd().
static void set_remote_protocol_Z_packet_cmd (char * args, int from_tty, struct cmd_list_element * c) [static]
Definition at line 1436 of file remote.c.
References packet_config::detect, NR_Z_PACKET_TYPES, PACKET_Z0, remote_protocol_packets, remote_Z_packet_detect, and update_packet_config().
static void set_remote_traceframe (void) [static]
Definition at line 6335 of file remote.c.
References _, get_remote_state(), get_traceframe_number(), remote_state::remote_traceframe_number, target_trace_find, tfind_number, and warning().
Referenced by remote_fetch_registers(), remote_get_trace_state_variable_value(), remote_store_registers(), remote_trace_find(), and remote_xfer_partial().
static void set_remotebreak (char * args, int from_tty, struct cmd_list_element * c) [static]
Definition at line 883 of file remote.c.
References interrupt_sequence_break, and interrupt_sequence_control_c.
static int set_stop_requested_callback (struct thread_info * thread, void * data) [static]
Definition at line 3245 of file remote.c.
References peek_stop_reply(), thread_info::ptid, and set_stop_requested().
Referenced by remote_start_remote().
static void set_thread (struct ptid ptid, int gen) [static]
Definition at line 1791 of file remote.c.
References remote_state::buf, remote_state::buf_size, remote_state::continue_thread, remote_state::general_thread, get_remote_packet_size(), get_remote_state(), getpkt(), minus_one_ptid, ptid_equal(), putpkt(), write_ptid(), and xsnprintf().
Referenced by set_continue_thread(), and set_general_thread().
static void show_interrupt_sequence (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 847 of file remote.c.
References _, fprintf_filtered(), and internal_error().
static void show_memory_packet_size (struct memory_packet_config * config) [static]
Definition at line 1043 of file remote.c.
References _, memory_packet_config::fixed_p, get_memory_packet_size(), memory_packet_config::name, printf_filtered(), and memory_packet_config::size.
Referenced by show_memory_read_packet_size(), and show_memory_write_packet_size().
static void show_memory_read_packet_size (char * args, int from_tty) [static]
Definition at line 1089 of file remote.c.
References show_memory_packet_size().
static void show_memory_write_packet_size (char * args, int from_tty) [static]
Definition at line 1066 of file remote.c.
References show_memory_packet_size().
static void show_packet_config_cmd (struct packet_config * config) [static]
Definition at line 1155 of file remote.c.
References _, AUTO_BOOLEAN_AUTO, AUTO_BOOLEAN_FALSE, AUTO_BOOLEAN_TRUE, packet_config::detect, packet_config::name, PACKET_DISABLE, PACKET_ENABLE, PACKET_SUPPORT_UNKNOWN, printf_filtered(), and packet_config::support.
Referenced by show_remote_protocol_packet_cmd(), and show_remote_protocol_Z_packet_cmd().
static void show_range_stepping (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 11771 of file remote.c.
References _, and fprintf_filtered().
static void show_remote_cmd (char * args, int from_tty) [static]
Definition at line 11675 of file remote.c.
References cmd_func(), current_uiout, do_cleanups(), do_show_command(), make_cleanup_ui_out_tuple_begin_end(), cmd_list_element::name, cmd_list_element::next, not_set_cmd, remote_show_cmdlist, show_cmd, cmd_list_element::type, ui_out_field_string(), and ui_out_text().
static void show_remote_protocol_packet_cmd (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 1398 of file remote.c.
References _, packet_config::detect, internal_error(), cmd_list_element::name, PACKET_MAX, remote_protocol_packets, show_packet_config_cmd(), and cmd_list_element::var.
Referenced by add_packet_config_cmd().
static void show_remote_protocol_Z_packet_cmd (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 1449 of file remote.c.
References NR_Z_PACKET_TYPES, PACKET_Z0, remote_protocol_packets, and show_packet_config_cmd().
static void show_remotebreak (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 892 of file remote.c.
static void skip_frame (void) [static]
Definition at line 7453 of file remote.c.
References readchar(), remote_timeout, and SERIAL_TIMEOUT.
Referenced by putpkt_binary().
static void stop_reply_dtr (struct notif_event * event) [static]
Definition at line 5347 of file remote.c.
References VEC_free.
Referenced by remote_notif_stop_alloc_reply().
static ptid_t stop_reply_extract_thread (char * stop_reply) [static]
Definition at line 3280 of file remote.c.
References null_ptid, read_ptid(), and strchr().
Referenced by add_current_inferior_and_thread().
static int stop_reply_match_ptid_and_ws (QUEUE(stop_reply_p)* q, QUEUE_ITER(stop_reply_p)* iter, struct stop_reply * event, void * data) [static]
Definition at line 5555 of file remote.c.
References stop_reply::ptid, ptid_equal(), and TARGET_WAITKIND_STOPPED.
Referenced by peek_stop_reply().
static void stop_reply_xfree (struct stop_reply *) [static]
Referenced by discard_pending_stop_replies(), process_stop_reply(), remove_stop_reply_for_inferior(), and remove_stop_reply_of_remote_state().
static int store_register_using_P (const struct regcache * regcache, struct packet_reg * reg) [static]
Definition at line 6431 of file remote.c.
References _, bin2hex(), remote_state::buf, remote_state::buf_size, error(), gdbarch_register_name(), get_regcache_arch(), get_remote_packet_size(), get_remote_state(), getpkt(), internal_error(), MAX_REGISTER_SIZE, PACKET_DISABLE, PACKET_ERROR, PACKET_OK, packet_ok(), PACKET_P, PACKET_UNKNOWN, phex_nz(), packet_reg::pnum, putpkt(), regcache_raw_collect(), register_size(), packet_reg::regnum, remote_protocol_packets, and xsnprintf().
Referenced by remote_store_registers().
static void store_registers_using_G (const struct regcache * regcache) [static]
Definition at line 6472 of file remote.c.
References _, bin2hex(), remote_state::buf, remote_state::buf_size, error(), gdbarch_num_regs(), get_regcache_arch(), get_remote_arch_state(), get_remote_state(), getpkt(), packet_reg::in_g_packet, memset(), packet_reg::offset, packet_check_result(), PACKET_ERROR, putpkt(), regcache_raw_collect(), packet_reg::regnum, remote_arch_state::regs, and remote_arch_state::sizeof_g_packet.
Referenced by remote_store_registers().
static int stub_unpack_int (char * buff, int fieldlength) [static]
Definition at line 2101 of file remote.c.
References stubhex().
Referenced by remote_unpack_thread_info_response(), unpack_byte(), and unpack_int().
static int stubhex (int ch) [static]
Definition at line 2089 of file remote.c.
Referenced by stub_unpack_int(), and unpack_threadid().
static void sync_remote_interrupt (int signo) [static]
Definition at line 5069 of file remote.c.
References gdb_call_async_signal_handler(), and sync_remote_interrupt_twice().
Referenced by remote_wait_as(), and sync_remote_interrupt_twice().
static void sync_remote_interrupt_twice (int signo) [static]
Definition at line 5080 of file remote.c.
References gdb_call_async_signal_handler(), ofunc, and sync_remote_interrupt().
Referenced by sync_remote_interrupt().
static int threadmatch (threadref * dest, threadref * src) [static]
Definition at line 2295 of file remote.c.
Referenced by remote_get_threadlist(), and remote_unpack_thread_info_response().
static int threadref_to_int (threadref * ref) [static]
Definition at line 2268 of file remote.c.
References scan().
Referenced by remote_newthread_step().
static int tohex (int nib) [static]
Definition at line 4655 of file remote.c.
Referenced by bin2hex(), putpkt_binary(), remote_pass_signals(), remote_program_signals(), and remote_resume().
static void trace_error (char * buf) [static]
Definition at line 522 of file remote.c.
References _, and error().
Referenced by remote_get_noisy_reply().
static char * unpack_byte (char * buf, int * value) [static]
Definition at line 2157 of file remote.c.
References stub_unpack_int().
Referenced by parse_threadlist_response(), and remote_unpack_thread_info_response().
static char * unpack_int (char * buf, int * value) [static]
Definition at line 2174 of file remote.c.
References stub_unpack_int().
Referenced by remote_unpack_thread_info_response().
static char * unpack_nibble (char * buf, int * val) [static]
Definition at line 2135 of file remote.c.
References remote_state::buf, and fromhex().
Referenced by parse_threadlist_response().
static char * unpack_string (char * src, char * dest, int length) [static]
Definition at line 2205 of file remote.c.
Referenced by remote_unpack_thread_info_response().
static char * unpack_threadid (char * inbuf, threadref * id) [static]
Definition at line 2228 of file remote.c.
References BUF_THREAD_ID_SIZE, and stubhex().
Referenced by parse_threadlist_response(), and remote_unpack_thread_info_response().
char * unpack_varlen_hex (char * buff, ULONGEST * result)
Definition at line 2118 of file remote.c.
References ishex(), and ULONGEST.
Referenced by parse_static_tracepoint_marker_definition(), parse_trace_status(), parse_tracepoint_definition(), parse_tracepoint_status(), parse_tsv_definition(), read_ptid(), remote_get_min_fast_tracepoint_insn_len(), remote_get_noisy_reply(), remote_get_thread_local_address(), remote_get_tib_address(), remote_get_trace_state_variable_value(), remote_parse_stop_reply(), remote_search_memory(), and remote_write_qxfer().
static void unpush_and_perror (const char * string) [static]
Definition at line 7143 of file remote.c.
References remote_unpush_target(), safe_strerror(), TARGET_CLOSE_ERROR, and throw_error().
Referenced by readchar(), and remote_serial_write().
static void update_packet_config (struct packet_config * config) [static]
Definition at line 1138 of file remote.c.
References AUTO_BOOLEAN_AUTO, AUTO_BOOLEAN_FALSE, AUTO_BOOLEAN_TRUE, packet_config::detect, PACKET_DISABLE, PACKET_ENABLE, PACKET_SUPPORT_UNKNOWN, and packet_config::support.
Referenced by init_all_packet_configs(), set_remote_protocol_packet_cmd(), and set_remote_protocol_Z_packet_cmd().
static VEC (static_tracepoint_marker_p) [static]
Definition at line 2968 of file remote.c.
static VEC (mem_region_s) [static]
Definition at line 9143 of file remote.c.
static VEC (btrace_block_s) [static]
Definition at line 11403 of file remote.c.
References _, btrace_read_all, btrace_read_new, current_target, do_cleanups(), error(), get_remote_state(), internal_error(), make_cleanup(), PACKET_ENABLE, PACKET_qXfer_btrace, remote_protocol_packets, packet_config::support, TARGET_OBJECT_BTRACE, target_read_stralloc(), VEC, and xfree().
static int watchpoint_to_Z_packet (int type) [static]
Definition at line 8279 of file remote.c.
References _, hw_access, hw_read, hw_write, internal_error(), Z_PACKET_ACCESS_WP, Z_PACKET_READ_WP, and Z_PACKET_WRITE_WP.
Referenced by remote_insert_watchpoint(), and remote_remove_watchpoint().
static char * write_ptid (char * buf, const char * endbuf, ptid_t ptid) [static]
Definition at line 2000 of file remote.c.
References remote_state::buf, get_remote_state(), ptid_get_pid(), ptid_get_tid(), remote_multi_process_p(), and xsnprintf().
Referenced by append_resumption(), remote_get_thread_local_address(), remote_get_tib_address(), remote_stop_ns(), remote_thread_alive(), remote_threads_extra_info(), and set_thread().
Variable Documentation
ptid_t any_thread_ptid [static]
Definition at line 1475 of file remote.c.
struct async_signal_handler* async_sigint_remote_token [static]
Definition at line 1463 of file remote.c.
struct async_signal_handler* async_sigint_remote_twice_token [static]
Definition at line 1462 of file remote.c.
struct target_ops extended_remote_ops [static]
Definition at line 817 of file remote.c.
Referenced by extended_remote_open(), and init_extended_remote_ops().
const char hexchars[] = "0123456789abcdef" [static]
Definition at line 2065 of file remote.c.
int interrupt_on_connect = 0 [static]
Definition at line 875 of file remote.c.
const char interrupt_sequence_break[] = "BREAK"
Definition at line 835 of file remote.c.
Referenced by set_remotebreak().
const char interrupt_sequence_break_g[] = "BREAK-g"
Definition at line 836 of file remote.c.
const char interrupt_sequence_control_c[] = "Ctrl-C"
Definition at line 834 of file remote.c.
Referenced by set_remotebreak().
const char* interrupt_sequence_mode = interrupt_sequence_control_c [static]
Definition at line 844 of file remote.c.
const char* const interrupt_sequence_modes[] [static]
Initial value:
  {
    interrupt_sequence_control_c,
    interrupt_sequence_break,
    interrupt_sequence_break_g,
    NULL
  }
Definition at line 837 of file remote.c.
ptid_t magic_null_ptid [static]
Definition at line 1473 of file remote.c.
Referenced by add_current_inferior_and_thread(), and extended_remote_mourn_1().
struct memory_packet_config memory_read_packet_config [static]
Initial value:
{
  "memory-read-packet-size",
}
Definition at line 1077 of file remote.c.
struct memory_packet_config memory_write_packet_config [static]
Initial value:
{
  "memory-write-packet-size",
}
Definition at line 1054 of file remote.c.
ptid_t not_sent_ptid [static]
Definition at line 1474 of file remote.c.
Referenced by remote_open_1().
struct notif_client notif_client_stop
Initial value:
{
  "Stop",
  "vStopped",
  remote_notif_stop_parse,
  remote_notif_stop_ack,
  remote_notif_stop_can_get_pending_events,
  remote_notif_stop_alloc_reply,
  REMOTE_NOTIF_STOP,
}
Definition at line 5367 of file remote.c.
Referenced by extended_remote_attach_1(), remote_resume(), and remote_start_remote().
void(* ofunc)(int) [static]
Definition at line 5061 of file remote.c.
Referenced by remote_wait_as(), and sync_remote_interrupt_twice().
unsigned int remote_address_size [static]
Definition at line 909 of file remote.c.
Referenced by remote_address_masked().
struct async_event_handler* remote_async_inferior_event_token [static]
Definition at line 1469 of file remote.c.
serial_event_ftype remote_async_serial_handler [static]
Definition at line 11634 of file remote.c.
int remote_async_terminal_ours_p [static]
Definition at line 914 of file remote.c.
int remote_break [static]
Definition at line 880 of file remote.c.
struct cmd_list_element* remote_cmdlist [static]
Definition at line 240 of file remote.c.
char* remote_exec_file = "" [static]
Definition at line 918 of file remote.c.
const int remote_flash_timeout = 1000 [static]
Definition at line 7057 of file remote.c.
Referenced by remote_flash_done(), remote_flash_erase(), and remote_flash_write().
struct gdbarch_data* remote_g_packet_data_handle [static]
Definition at line 9486 of file remote.c.
struct gdbarch_data* remote_gdbarch_data_handle [static]
Definition at line 611 of file remote.c.
int remote_hw_breakpoint_limit = -1
Definition at line 8387 of file remote.c.
int remote_hw_watchpoint_length_limit = -1
Definition at line 8386 of file remote.c.
int remote_hw_watchpoint_limit = -1
Definition at line 8385 of file remote.c.
struct target_ops remote_ops [static]
Definition at line 815 of file remote.c.
Referenced by init_extended_remote_ops(), init_remote_ops(), and remote_open().
struct protocol_feature remote_protocol_features[] [static]
Definition at line 3992 of file remote.c.
struct packet_config remote_protocol_packets[PACKET_MAX] [static]
Definition at line 1375 of file remote.c.
Referenced by check_binary_download(), extended_remote_attach_1(), extended_remote_run(), extended_remote_supports_disable_randomization(), fetch_register_using_p(), init_all_packet_configs(), remote_can_execute_reverse(), remote_can_use_agent(), remote_check_symbols(), remote_disable_btrace(), remote_download_tracepoint(), remote_enable_btrace(), remote_get_thread_local_address(), remote_get_tib_address(), remote_get_trace_status(), remote_hostio_send_command(), remote_insert_breakpoint(), remote_insert_hw_breakpoint(), remote_insert_watchpoint(), remote_pass_signals(), remote_prepare_to_store(), remote_program_signals(), remote_query_attached(), remote_query_supported(), remote_remove_breakpoint(), remote_remove_hw_breakpoint(), remote_remove_watchpoint(), remote_resume(), remote_search_memory(), remote_set_trace_buffer_size(), remote_start_remote(), remote_stop_ns(), remote_supported_packet(), remote_supports_btrace(), remote_threads_extra_info(), remote_threads_info(), remote_trace_set_readonly_regions(), remote_use_agent(), remote_vcont_probe(), remote_vcont_resume(), remote_vkill(), remote_write_bytes(), remote_xfer_partial(), set_range_stepping(), set_remote_protocol_packet_cmd(), set_remote_protocol_Z_packet_cmd(), show_remote_protocol_packet_cmd(), show_remote_protocol_Z_packet_cmd(), store_register_using_P(), and VEC().
struct cmd_list_element* remote_set_cmdlist [static]
Definition at line 244 of file remote.c.
struct cmd_list_element* remote_show_cmdlist [static]
Definition at line 245 of file remote.c.
Referenced by show_remote_cmd().
struct remote_state* remote_state [static]
Definition at line 458 of file remote.c.
Referenced by get_remote_state_raw().
char* remote_support_xml [static]
Definition at line 4069 of file remote.c.
enum auto_boolean remote_Z_packet_detect [static]
Definition at line 1433 of file remote.c.
Referenced by set_remote_protocol_Z_packet_cmd().
char* target_buf [static]
Definition at line 75 of file remote.c.
Referenced by extended_remote_disable_randomization(), remote_download_command_source(), remote_download_trace_state_variable(), remote_download_tracepoint(), remote_get_min_fast_tracepoint_insn_len(), remote_get_raw_trace_data(), remote_get_trace_state_variable_value(), remote_get_trace_status(), remote_get_tracepoint_status(), remote_save_trace_data(), remote_set_circular_trace_buffer(), remote_set_disconnected_tracing(), remote_set_trace_notes(), remote_trace_init(), remote_trace_set_readonly_regions(), remote_trace_start(), and remote_trace_stop().
long target_buf_size [static]
Definition at line 76 of file remote.c.
Referenced by extended_remote_disable_randomization(), remote_download_command_source(), remote_download_trace_state_variable(), remote_download_tracepoint(), remote_get_min_fast_tracepoint_insn_len(), remote_get_raw_trace_data(), remote_get_trace_state_variable_value(), remote_get_trace_status(), remote_get_tracepoint_status(), remote_save_trace_data(), remote_set_circular_trace_buffer(), remote_set_disconnected_tracing(), remote_set_trace_notes(), remote_trace_init(), remote_trace_set_readonly_regions(), remote_trace_start(), and remote_trace_stop().
int use_range_stepping = 1 [static]
Definition at line 263 of file remote.c.
int wait_forever_enabled_p = 1 [static]
Definition at line 826 of file remote.c.