GDB (xrefs): /home/stan/gdb/src/gdb/remote.h File Reference
/home/stan/gdb/src/gdb/remote.h File Reference
#include "remote-notif.h"
Defines
#define REMOTE_SYSROOT_PREFIX "remote:"
Functions
void getpkt (char **buf, long *sizeof_buf, int forever)
int putpkt (char *buf)
int hex2bin (const char *hex, gdb_byte *bin, int count)
int bin2hex (const gdb_byte *bin, char *hex, int count)
char * unpack_varlen_hex (char *buff, ULONGEST *result)
void register_remote_g_packet_guess (struct gdbarch *gdbarch, int bytes, const struct target_desc *tdesc)
void register_remote_support_xml (const char *)
void remote_file_put (const char *local_file, const char *remote_file, int from_tty)
void remote_file_get (const char *remote_file, const char *local_file, int from_tty)
void remote_file_delete (const char *remote_file, int from_tty)
bfd * remote_bfd_open (const char *remote_file, const char *target)
int remote_filename_p (const char *filename)
int remote_register_number_and_offset (struct gdbarch *gdbarch, int regnum, int *pnum, int *poffset)
void remote_notif_get_pending_events (struct notif_client *np)
Define Documentation
#define REMOTE_SYSROOT_PREFIX "remote:"
Definition at line 63 of file remote.h.
Referenced by remote_filename_p(), and solib_find().
Function Documentation
int bin2hex (const gdb_byte * bin, char * hex, int count)
Definition at line 4664 of file remote.c.
References tohex().
Referenced by encode_source_string(), extended_remote_run(), remote_buffer_add_bytes(), remote_download_trace_state_variable(), remote_rcmd(), remote_save_trace_data(), remote_set_trace_notes(), remote_write_bytes_aux(), store_register_using_P(), store_registers_using_G(), tfile_write_status(), and tfile_write_uploaded_tsv().
void getpkt (char ** buf, long * sizeof_buf, int forever)
Definition at line 7631 of file remote.c.
References getpkt_sane().
Referenced by check_binary_download(), extended_remote_attach_1(), extended_remote_kill(), extended_remote_mourn_1(), extended_remote_run(), fetch_register_using_p(), get_offsets(), packet_command(), remote_check_symbols(), remote_current_thread(), remote_detach_1(), remote_disable_btrace(), remote_enable_btrace(), remote_get_noisy_reply(), remote_get_thread_local_address(), remote_get_threadinfo(), remote_get_threadlist(), remote_get_tib_address(), remote_insert_breakpoint(), remote_insert_hw_breakpoint(), remote_insert_watchpoint(), remote_notif_get_pending_events(), remote_pass_signals(), remote_program_signals(), remote_query_attached(), remote_query_supported(), remote_read_bytes(), remote_remove_breakpoint(), remote_remove_hw_breakpoint(), remote_remove_watchpoint(), remote_send(), remote_send_printf(), remote_set_permissions(), remote_start_remote(), remote_static_tracepoint_marker_at(), remote_stop_ns(), remote_thread_alive(), remote_threads_extra_info(), remote_threads_info(), remote_trace_set_readonly_regions(), remote_upload_trace_state_variables(), remote_upload_tracepoints(), remote_use_agent(), remote_vcont_probe(), remote_vcont_resume(), remote_verify_memory(), remote_vkill(), remote_write_bytes_aux(), remote_xfer_partial(), send_g_packet(), set_thread(), store_register_using_P(), and store_registers_using_G().
int hex2bin (const char * hex, gdb_byte * bin, int count)
Definition at line 4634 of file remote.c.
References fromhex().
int putpkt (char * buf)
Definition at line 7245 of file remote.c.
References putpkt_binary().
Referenced by extended_remote_attach_1(), extended_remote_disable_randomization(), extended_remote_kill(), extended_remote_mourn_1(), extended_remote_restart(), extended_remote_run(), fetch_register_using_p(), get_offsets(), packet_command(), putpkt_for_catch_errors(), remote_check_symbols(), remote_current_thread(), remote_detach_1(), remote_disable_btrace(), remote_disable_tracepoint(), remote_download_command_source(), remote_download_trace_state_variable(), remote_download_tracepoint(), remote_enable_btrace(), remote_enable_tracepoint(), remote_fileio_reply(), remote_get_min_fast_tracepoint_insn_len(), remote_get_noisy_reply(), remote_get_raw_trace_data(), remote_get_thread_local_address(), remote_get_threadinfo(), remote_get_threadlist(), remote_get_tib_address(), remote_get_trace_state_variable_value(), remote_get_trace_status(), remote_get_tracepoint_status(), remote_insert_breakpoint(), remote_insert_hw_breakpoint(), remote_insert_watchpoint(), remote_notif_stop_ack(), remote_pass_signals(), remote_program_signals(), remote_query_attached(), remote_query_supported(), remote_rcmd(), remote_read_bytes(), remote_read_qxfer(), remote_remove_breakpoint(), remote_remove_hw_breakpoint(), remote_remove_watchpoint(), remote_resume(), remote_save_trace_data(), remote_send(), remote_send_printf(), remote_set_circular_trace_buffer(), remote_set_disconnected_tracing(), remote_set_permissions(), remote_set_trace_buffer_size(), remote_set_trace_notes(), remote_start_remote(), remote_static_tracepoint_marker_at(), remote_stop_ns(), remote_thread_alive(), remote_threads_extra_info(), remote_threads_info(), remote_trace_find(), remote_trace_init(), remote_trace_set_readonly_regions(), remote_trace_start(), remote_trace_stop(), remote_upload_trace_state_variables(), remote_upload_tracepoints(), remote_use_agent(), remote_vcont_probe(), remote_vcont_resume(), remote_verify_memory(), remote_vkill(), remote_wait_as(), remote_xfer_partial(), set_thread(), store_register_using_P(), and store_registers_using_G().
void register_remote_g_packet_guess (struct gdbarch * gdbarch, int bytes, const struct target_desc * tdesc)
Definition at line 9495 of file remote.c.
References _, remote_g_packet_guess::bytes, gdb_assert, gdbarch_data(), internal_error(), remote_g_packet_guess::tdesc, VEC_iterate, and VEC_safe_push.
Referenced by arm_register_g_packet_guesses(), and mips_register_g_packet_guesses().
void register_remote_support_xml (const char *)
Definition at line 4074 of file remote.c.
References strtok(), and xfree().
bfd* remote_bfd_open (const char * remote_file, const char * target)
Definition at line 10088 of file remote.c.
References gdb_bfd_openr_iovec(), remote_bfd_iovec_close(), remote_bfd_iovec_open(), remote_bfd_iovec_pread(), and remote_bfd_iovec_stat().
Referenced by gdb_bfd_open_maybe_remote(), solib_bfd_fopen(), and symfile_bfd_open().
void remote_file_delete (const char * remote_file, int from_tty)
Definition at line 10247 of file remote.c.
References _, error(), get_remote_state(), printf_filtered(), remote_state::remote_desc, remote_hostio_error(), and remote_hostio_unlink().
Referenced by mi_cmd_target_file_delete(), and remote_delete_command().
void remote_file_get (const char * remote_file, const char * local_file, int from_tty)
Definition at line 10191 of file remote.c.
References _, discard_cleanups(), do_cleanups(), error(), gdb_fopen_cloexec(), get_remote_packet_size(), get_remote_state(), make_cleanup(), make_cleanup_fclose(), offset, perror_with_name(), printf_filtered(), remote_state::remote_desc, remote_hostio_close(), remote_hostio_close_cleanup(), remote_hostio_error(), remote_hostio_open(), remote_hostio_pread(), ULONGEST, xfree(), and xmalloc().
Referenced by mi_cmd_target_file_get(), and remote_get_command().
void remote_file_put (const char * local_file, const char * remote_file, int from_tty)
Definition at line 10100 of file remote.c.
References _, discard_cleanups(), do_cleanups(), error(), gdb_fopen_cloexec(), get_remote_packet_size(), get_remote_state(), make_cleanup(), make_cleanup_fclose(), memmove(), offset, perror_with_name(), printf_filtered(), remote_state::remote_desc, remote_hostio_close(), remote_hostio_close_cleanup(), remote_hostio_error(), remote_hostio_open(), remote_hostio_pwrite(), ULONGEST, xfree(), and xmalloc().
Referenced by mi_cmd_target_file_put(), and remote_put_command().
int remote_filename_p (const char * filename)
Definition at line 10080 of file remote.c.
References REMOTE_SYSROOT_PREFIX.
Referenced by gdb_bfd_open_maybe_remote(), remote_bfd_iovec_open(), solib_bfd_fopen(), solib_find(), and symfile_bfd_open().
void remote_notif_get_pending_events (struct notif_client * np)
Definition at line 5826 of file remote.c.
References notif_client::ack, remote_state::buf, remote_state::buf_size, fprintf_unfiltered(), gdb_stdlog, get_remote_state(), getpkt(), notif_client::id, notif_client::name, notif_debug, remote_state::notif_state, remote_notif_state::pending_event, and remote_notif_ack().
Referenced by remote_notif_process(), remote_start_remote(), and remote_wait_ns().
int remote_register_number_and_offset (struct gdbarch * gdbarch, int regnum, int * pnum, int * poffset)
Definition at line 699 of file remote.c.
References do_cleanups(), gdb_assert, gdbarch_num_regs(), make_cleanup(), map_regcache_remote_table(), packet_reg::offset, packet_reg::pnum, regnum, xcalloc(), and xfree().
Referenced by regcache_dump().
char* unpack_varlen_hex (char * buff, ULONGEST * result)
Definition at line 2118 of file remote.c.
References ishex(), and ULONGEST.
Referenced by parse_static_tracepoint_marker_definition(), parse_trace_status(), parse_tracepoint_definition(), parse_tracepoint_status(), parse_tsv_definition(), read_ptid(), remote_get_min_fast_tracepoint_insn_len(), remote_get_noisy_reply(), remote_get_thread_local_address(), remote_get_tib_address(), remote_get_trace_state_variable_value(), remote_parse_stop_reply(), remote_search_memory(), and remote_write_qxfer().