GDB (xrefs): /home/stan/gdb/src/gdb/reverse.c File Reference
/home/stan/gdb/src/gdb/reverse.c File Reference
#include "defs.h"
#include "gdb_string.h"
#include "target.h"
#include "top.h"
#include "cli/cli-cmds.h"
#include "cli/cli-decode.h"
#include "cli/cli-utils.h"
#include "inferior.h"
#include "regcache.h"
Classes
struct bookmark
Defines
#define ALL_BOOKMARKS(B) for ((B) = bookmark_chain; (B); (B) = (B)->next)
#define ALL_BOOKMARKS_SAFE(B, TMP)
Functions
static void exec_direction_default (void *notused)
static void exec_reverse_once (char *cmd, char *args, int from_tty)
static void reverse_step (char *args, int from_tty)
static void reverse_stepi (char *args, int from_tty)
static void reverse_next (char *args, int from_tty)
static void reverse_nexti (char *args, int from_tty)
static void reverse_continue (char *args, int from_tty)
static void reverse_finish (char *args, int from_tty)
static void save_bookmark_command (char *args, int from_tty)
static int delete_one_bookmark (int num)
static void delete_all_bookmarks (void)
static void delete_bookmark_command (char *args, int from_tty)
static void goto_bookmark_command (char *args, int from_tty)
static int bookmark_1 (int bnum)
static void bookmarks_info (char *args, int from_tty)
void _initialize_reverse (void)
Variables
static struct bookmark * bookmark_chain
static int bookmark_count
initialize_file_ftype _initialize_reverse
Define Documentation
#define ALL_BOOKMARKS (B) for ((B) = bookmark_chain; (B); (B) = (B)->next)
Definition at line 116 of file reverse.c.
Referenced by bookmark_1(), delete_one_bookmark(), and goto_bookmark_command().
#define ALL_BOOKMARKS_SAFE (B, TMP)
Value:
for ((B) = bookmark_chain;             \
          (B) ? ((TMP) = (B)->next, 1) : 0; \
          (B) = (TMP))
Definition at line 118 of file reverse.c.
Referenced by delete_all_bookmarks().
Function Documentation
void _initialize_reverse (void)
Definition at line 345 of file reverse.c.
References _, _initialize_reverse, add_cmd(), add_com(), add_com_alias(), add_info(), bookmarks_info(), class_alias, class_bookmark, class_run, delete_bookmark_command(), deletelist, goto_bookmark_command(), reverse_continue(), reverse_finish(), reverse_next(), reverse_nexti(), reverse_step(), reverse_stepi(), and save_bookmark_command().
static int bookmark_1 (int bnum) [static]
Definition at line 292 of file reverse.c.
References ALL_BOOKMARKS, get_current_regcache(), get_regcache_arch(), bookmark::number, bookmark::opaque_data, paddress(), bookmark::pc, and printf_filtered().
Referenced by bookmarks_info().
static void bookmarks_info (char * args, int from_tty) [static]
Definition at line 319 of file reverse.c.
References _, bookmark_1(), get_number_or_range_state::finished, get_number_or_range(), init_number_or_range(), and printf_filtered().
Referenced by _initialize_reverse().
static void delete_all_bookmarks (void) [static]
Definition at line 204 of file reverse.c.
References ALL_BOOKMARKS_SAFE, bookmark::opaque_data, and xfree().
Referenced by delete_bookmark_command().
static void delete_bookmark_command (char * args, int from_tty) [static]
Definition at line 217 of file reverse.c.
References _, delete_all_bookmarks(), delete_one_bookmark(), get_number_or_range_state::finished, get_number_or_range(), init_number_or_range(), query(), and warning().
Referenced by _initialize_reverse().
static int delete_one_bookmark (int num) [static]
Definition at line 173 of file reverse.c.
References ALL_BOOKMARKS, bookmark::next, bookmark::number, bookmark::opaque_data, and xfree().
Referenced by delete_bookmark_command().
static void exec_direction_default (void * notused) [static]
Definition at line 34 of file reverse.c.
References EXEC_FORWARD, and execution_direction.
Referenced by exec_reverse_once().
static void exec_reverse_once (char * cmd, char * args, int from_tty) [static]
Definition at line 46 of file reverse.c.
References _, do_cleanups(), error(), exec_direction_default(), EXEC_REVERSE, execute_command(), execution_direction, make_cleanup(), target_can_execute_reverse, target_shortname, xfree(), and xstrprintf().
Referenced by reverse_continue(), reverse_finish(), reverse_next(), reverse_nexti(), reverse_step(), and reverse_stepi().
static void goto_bookmark_command (char * args, int from_tty) [static]
Definition at line 249 of file reverse.c.
References _, ALL_BOOKMARKS, error(), get_number(), bookmark::number, bookmark::opaque_data, and target_goto_bookmark.
Referenced by _initialize_reverse().
static void reverse_continue (char * args, int from_tty) [static]
Definition at line 92 of file reverse.c.
References exec_reverse_once().
Referenced by _initialize_reverse().
static void reverse_finish (char * args, int from_tty) [static]
Definition at line 98 of file reverse.c.
References exec_reverse_once().
Referenced by _initialize_reverse().
static void reverse_next (char * args, int from_tty) [static]
Definition at line 80 of file reverse.c.
References exec_reverse_once().
Referenced by _initialize_reverse().
static void reverse_nexti (char * args, int from_tty) [static]
Definition at line 86 of file reverse.c.
References exec_reverse_once().
Referenced by _initialize_reverse().
static void reverse_step (char * args, int from_tty) [static]
Definition at line 68 of file reverse.c.
References exec_reverse_once().
Referenced by _initialize_reverse().
static void reverse_stepi (char * args, int from_tty) [static]
Definition at line 74 of file reverse.c.
References exec_reverse_once().
Referenced by _initialize_reverse().
static void save_bookmark_command (char * args, int from_tty) [static]
Definition at line 131 of file reverse.c.
References _, bookmark_chain, bookmark_count, dont_repeat(), error(), find_pc_line(), get_current_frame(), get_current_regcache(), get_frame_program_space(), get_regcache_arch(), init_sal(), bookmark::next, bookmark::number, bookmark::opaque_data, paddress(), bookmark::pc, symtab_and_line::pc, printf_filtered(), symtab_and_line::pspace, regcache_read_pc(), bookmark::sal, target_get_bookmark, and xcalloc().
Referenced by _initialize_reverse().
Variable Documentation
initialize_file_ftype _initialize_reverse
Referenced by _initialize_reverse(), and initialize_all_files().
struct bookmark* bookmark_chain [static]
Definition at line 113 of file reverse.c.
Referenced by save_bookmark_command().
int bookmark_count [static]
Definition at line 114 of file reverse.c.
Referenced by save_bookmark_command().