GDB (xrefs): /home/stan/gdb/src/gdb/rs6000-lynx178-tdep.c File Reference
/home/stan/gdb/src/gdb/rs6000-lynx178-tdep.c File Reference
#include "defs.h"
#include "osabi.h"
#include "regcache.h"
#include "gdbcore.h"
#include "gdbtypes.h"
#include "infcall.h"
#include "ppc-tdep.h"
#include "value.h"
#include "xcoffread.h"
Functions
static CORE_ADDR rs6000_lynx178_push_dummy_call (struct gdbarch *gdbarch, struct value *function, struct regcache *regcache, CORE_ADDR bp_addr, int nargs, struct value **args, CORE_ADDR sp, int struct_return, CORE_ADDR struct_addr)
static enum return_value_convention rs6000_lynx178_return_value (struct gdbarch *gdbarch, struct value *function, struct type *valtype, struct regcache *regcache, gdb_byte *readbuf, const gdb_byte *writebuf)
static enum gdb_osabi rs6000_lynx178_osabi_sniffer (bfd *abfd)
static void rs6000_lynx178_init_osabi (struct gdbarch_info info, struct gdbarch *gdbarch)
void _initialize_rs6000_lynx178_tdep (void)
Variables
initialize_file_ftype _initialize_rs6000_lynx178_tdep
Function Documentation
void _initialize_rs6000_lynx178_tdep (void)
Definition at line 420 of file rs6000-lynx178-tdep.c.
References _initialize_rs6000_lynx178_tdep, GDB_OSABI_LYNXOS178, gdbarch_register_osabi(), gdbarch_register_osabi_sniffer(), rs6000_lynx178_init_osabi(), and rs6000_lynx178_osabi_sniffer().
static void rs6000_lynx178_init_osabi (struct gdbarch_info info, struct gdbarch * gdbarch) [static]
Definition at line 409 of file rs6000-lynx178-tdep.c.
References rs6000_lynx178_push_dummy_call(), rs6000_lynx178_return_value(), set_gdbarch_long_double_bit(), set_gdbarch_push_dummy_call(), and set_gdbarch_return_value().
Referenced by _initialize_rs6000_lynx178_tdep().
static enum gdb_osabi rs6000_lynx178_osabi_sniffer (bfd * abfd) [static]
Definition at line 391 of file rs6000-lynx178-tdep.c.
References GDB_OSABI_LYNXOS178, GDB_OSABI_UNKNOWN, and xcoff_get_n_import_files().
Referenced by _initialize_rs6000_lynx178_tdep().
static CORE_ADDR rs6000_lynx178_push_dummy_call (struct gdbarch * gdbarch, struct value * function, struct regcache * regcache, CORE_ADDR bp_addr, int nargs, struct value ** args, CORE_ADDR sp, int struct_return, CORE_ADDR struct_addr) [static]
Definition at line 31 of file rs6000-lynx178-tdep.c.
References align_down(), align_up(), check_typedef(), convert_typed_floating(), find_function_addr(), fp_regnum, gdb_assert, gdbarch_byte_order(), gdbarch_sp_regnum(), gdbarch_tdep(), len, MAX_REGISTER_SIZE, memcpy(), memset(), ppc_floating_point_unit_p(), gdbarch_tdep::ppc_fp0_regnum, gdbarch_tdep::ppc_gp0_regnum, gdbarch_tdep::ppc_lr_regnum, regcache_cooked_read_unsigned(), regcache_cooked_write(), regcache_raw_write_signed(), regcache_raw_write_unsigned(), register_size(), register_type(), store_unsigned_integer(), target_store_registers(), type, TYPE_CODE, TYPE_CODE_FLT, TYPE_LENGTH, ULONGEST, value_contents(), value_type(), word, gdbarch_tdep::wordsize, and write_memory().
Referenced by rs6000_lynx178_init_osabi().
static enum return_value_convention rs6000_lynx178_return_value (struct gdbarch * gdbarch, struct value * function, struct type * valtype, struct regcache * regcache, gdb_byte * readbuf, const gdb_byte * writebuf) [static]
Definition at line 268 of file rs6000-lynx178-tdep.c.
References convert_typed_floating(), gdb_assert, gdbarch_byte_order(), gdbarch_tdep(), memcpy(), ppc_floating_point_unit_p(), gdbarch_tdep::ppc_fp0_regnum, gdbarch_tdep::ppc_gp0_regnum, gdbarch_tdep::ppc_vr0_regnum, regcache_cooked_read(), regcache_cooked_read_unsigned(), regcache_cooked_write(), regcache_cooked_write_unsigned(), register_type(), regtype, RETURN_VALUE_REGISTER_CONVENTION, RETURN_VALUE_STRUCT_CONVENTION, store_unsigned_integer(), TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_FLT, TYPE_CODE_STRUCT, TYPE_CODE_UNION, TYPE_LENGTH, TYPE_VECTOR, ULONGEST, unpack_long(), and gdbarch_tdep::wordsize.
Referenced by rs6000_lynx178_init_osabi().
Variable Documentation
initialize_file_ftype _initialize_rs6000_lynx178_tdep
Referenced by _initialize_rs6000_lynx178_tdep(), and initialize_all_files().