GDB (xrefs): /home/stan/gdb/src/gdb/rs6000-aix-tdep.h File Reference
/home/stan/gdb/src/gdb/rs6000-aix-tdep.h File Reference
Functions
LONGEST rs6000_aix_ld_info_to_xml (struct gdbarch *gdbarch, const gdb_byte *ldi_buf, gdb_byte *readbuf, ULONGEST offset, LONGEST len, int close_ldinfo_fd)
Function Documentation
LONGEST rs6000_aix_ld_info_to_xml (struct gdbarch * gdbarch, const gdb_byte * ldi_buf, gdb_byte * readbuf, ULONGEST offset, LONGEST len, int close_ldinfo_fd)
Definition at line 969 of file rs6000-aix-tdep.c.
References ld_info::fd, len, LONGEST, memcpy(), ld_info::next, obstack_grow_str, obstack_grow_str0, offset, rs6000_aix_extract_ld_info(), and rs6000_aix_shared_library_to_xml().
Referenced by rs6000_aix_core_xfer_shared_libraries_aix(), and rs6000_xfer_shared_libraries().