GDB (xrefs): /home/stan/gdb/src/gdb/s390-tdep.c File Reference
/home/stan/gdb/src/gdb/s390-tdep.c File Reference
#include "defs.h"
#include "arch-utils.h"
#include "frame.h"
#include "inferior.h"
#include "symtab.h"
#include "target.h"
#include "gdbcore.h"
#include "gdbcmd.h"
#include "objfiles.h"
#include "floatformat.h"
#include "regcache.h"
#include "trad-frame.h"
#include "frame-base.h"
#include "frame-unwind.h"
#include "dwarf2-frame.h"
#include "reggroups.h"
#include "regset.h"
#include "value.h"
#include "gdb_assert.h"
#include "dis-asm.h"
#include "solib-svr4.h"
#include "prologue-value.h"
#include "linux-tdep.h"
#include "s390-tdep.h"
#include "auxv.h"
#include "stap-probe.h"
#include "ax.h"
#include "ax-gdb.h"
#include "user-regs.h"
#include "cli/cli-utils.h"
#include <ctype.h>
#include "elf/common.h"
#include "features/s390-linux32.c"
#include "features/s390-linux32v1.c"
#include "features/s390-linux32v2.c"
#include "features/s390-linux64.c"
#include "features/s390-linux64v1.c"
#include "features/s390-linux64v2.c"
#include "features/s390-te-linux64.c"
#include "features/s390x-linux64.c"
#include "features/s390x-linux64v1.c"
#include "features/s390x-linux64v2.c"
#include "features/s390x-te-linux64.c"
Classes
struct gdbarch_tdep
struct s390_prologue_data
struct s390_unwind_cache
struct s390_stub_unwind_cache
struct s390_sigtramp_unwind_cache
Defines
#define S390_MAX_INSTR_SIZE 6
#define S390_NUM_GPRS 16
#define S390_NUM_FPRS 16
Enumerations
enum {
op1_lhi = 0xa7, op2_lhi = 0x08, op1_lghi = 0xa7, op2_lghi = 0x09,
op1_lgfi = 0xc0, op2_lgfi = 0x01, op_lr = 0x18, op_lgr = 0xb904,
op_l = 0x58, op1_ly = 0xe3, op2_ly = 0x58, op1_lg = 0xe3,
op2_lg = 0x04, op_lm = 0x98, op1_lmy = 0xeb, op2_lmy = 0x98,
op1_lmg = 0xeb, op2_lmg = 0x04, op_st = 0x50, op1_sty = 0xe3,
op2_sty = 0x50, op1_stg = 0xe3, op2_stg = 0x24, op_std = 0x60,
op_stm = 0x90, op1_stmy = 0xeb, op2_stmy = 0x90, op1_stmg = 0xeb,
op2_stmg = 0x24, op1_aghi = 0xa7, op2_aghi = 0x0b, op1_ahi = 0xa7,
op2_ahi = 0x0a, op1_agfi = 0xc2, op2_agfi = 0x08, op1_afi = 0xc2,
op2_afi = 0x09, op1_algfi = 0xc2, op2_algfi = 0x0a, op1_alfi = 0xc2,
op2_alfi = 0x0b, op_ar = 0x1a, op_agr = 0xb908, op_a = 0x5a,
op1_ay = 0xe3, op2_ay = 0x5a, op1_ag = 0xe3, op2_ag = 0x08,
op1_slgfi = 0xc2, op2_slgfi = 0x04, op1_slfi = 0xc2, op2_slfi = 0x05,
op_sr = 0x1b, op_sgr = 0xb909, op_s = 0x5b, op1_sy = 0xe3,
op2_sy = 0x5b, op1_sg = 0xe3, op2_sg = 0x09, op_nr = 0x14,
op_ngr = 0xb980, op_la = 0x41, op1_lay = 0xe3, op2_lay = 0x71,
op1_larl = 0xc0, op2_larl = 0x00, op_basr = 0x0d, op_bas = 0x4d,
op_bcr = 0x07, op_bc = 0x0d, op_bctr = 0x06, op_bctgr = 0xb946,
op_bct = 0x46, op1_bctg = 0xe3, op2_bctg = 0x46, op_bxh = 0x86,
op1_bxhg = 0xeb, op2_bxhg = 0x44, op_bxle = 0x87, op1_bxleg = 0xeb,
op2_bxleg = 0x45, op1_bras = 0xa7, op2_bras = 0x05, op1_brasl = 0xc0,
op2_brasl = 0x05, op1_brc = 0xa7, op2_brc = 0x04, op1_brcl = 0xc0,
op2_brcl = 0x04, op1_brct = 0xa7, op2_brct = 0x06, op1_brctg = 0xa7,
op2_brctg = 0x07, op_brxh = 0x84, op1_brxhg = 0xec, op2_brxhg = 0x44,
op_brxle = 0x85, op1_brxlg = 0xec, op2_brxlg = 0x45
}
Functions
static int s390_register_call_saved (struct gdbarch *gdbarch, int regnum)
static int s390_cannot_store_register (struct gdbarch *gdbarch, int regnum)
static void s390_write_pc (struct regcache *regcache, CORE_ADDR pc)
static int s390_dwarf_reg_to_regnum (struct gdbarch *gdbarch, int reg)
static int s390_adjust_frame_regnum (struct gdbarch *gdbarch, int num, int eh_frame_p)
static int regnum_is_gpr_full (struct gdbarch_tdep *tdep, int regnum)
static const char * s390_pseudo_register_name (struct gdbarch *gdbarch, int regnum)
static struct type * s390_pseudo_register_type (struct gdbarch *gdbarch, int regnum)
static enum register_status s390_pseudo_register_read (struct gdbarch *gdbarch, struct regcache *regcache, int regnum, gdb_byte *buf)
static void s390_pseudo_register_write (struct gdbarch *gdbarch, struct regcache *regcache, int regnum, const gdb_byte *buf)
static struct value * s390_value_from_register (struct type *type, int regnum, struct frame_info *frame)
static int s390_pseudo_register_reggroup_p (struct gdbarch *gdbarch, int regnum, struct reggroup *group)
static void s390_supply_regset (const struct regset *regset, struct regcache *regcache, int regnum, const void *regs, size_t len)
static void s390_supply_tdb_regset (const struct regset *regset, struct regcache *regcache, int regnum, const void *regs, size_t len)
static void s390_collect_regset (const struct regset *regset, const struct regcache *regcache, int regnum, void *regs, size_t len)
static struct regset * s390_regset_from_core_section (struct gdbarch *gdbarch, const char *sect_name, size_t sect_size)
static struct target_desc * s390_core_read_description (struct gdbarch *gdbarch, struct target_ops *target, bfd *abfd)
static int s390_readinstruction (bfd_byte instr[], CORE_ADDR at)
static int is_ri (bfd_byte *insn, int op1, int op2, unsigned int *r1, int *i2)
static int is_ril (bfd_byte *insn, int op1, int op2, unsigned int *r1, int *i2)
static int is_rr (bfd_byte *insn, int op, unsigned int *r1, unsigned int *r2)
static int is_rre (bfd_byte *insn, int op, unsigned int *r1, unsigned int *r2)
static int is_rs (bfd_byte *insn, int op, unsigned int *r1, unsigned int *r3, int *d2, unsigned int *b2)
static int is_rsy (bfd_byte *insn, int op1, int op2, unsigned int *r1, unsigned int *r3, int *d2, unsigned int *b2)
static int is_rsi (bfd_byte *insn, int op, unsigned int *r1, unsigned int *r3, int *i2)
static int is_rie (bfd_byte *insn, int op1, int op2, unsigned int *r1, unsigned int *r3, int *i2)
static int is_rx (bfd_byte *insn, int op, unsigned int *r1, int *d2, unsigned int *x2, unsigned int *b2)
static int is_rxy (bfd_byte *insn, int op1, int op2, unsigned int *r1, int *d2, unsigned int *x2, unsigned int *b2)
static pv_t s390_addr (struct s390_prologue_data *data, int d2, unsigned int x2, unsigned int b2)
static void s390_store (struct s390_prologue_data *data, int d2, unsigned int x2, unsigned int b2, CORE_ADDR size, pv_t value)
static pv_t s390_load (struct s390_prologue_data *data, int d2, unsigned int x2, unsigned int b2, CORE_ADDR size)
static void s390_check_for_saved (void *data_untyped, pv_t addr, CORE_ADDR size, pv_t value)
static CORE_ADDR s390_analyze_prologue (struct gdbarch *gdbarch, CORE_ADDR start_pc, CORE_ADDR current_pc, struct s390_prologue_data *data)
static CORE_ADDR s390_skip_prologue (struct gdbarch *gdbarch, CORE_ADDR pc)
static int s390_in_function_epilogue_p (struct gdbarch *gdbarch, CORE_ADDR pc)
static void s390_displaced_step_fixup (struct gdbarch *gdbarch, struct displaced_step_closure *closure, CORE_ADDR from, CORE_ADDR to, struct regcache *regs)
static struct value * s390_unwind_pseudo_register (struct frame_info *this_frame, int regnum)
static struct value * s390_trad_frame_prev_register (struct frame_info *this_frame, struct trad_frame_saved_reg saved_regs[], int regnum)
static int s390_prologue_frame_unwind_cache (struct frame_info *this_frame, struct s390_unwind_cache *info)
static void s390_backchain_frame_unwind_cache (struct frame_info *this_frame, struct s390_unwind_cache *info)
static struct s390_unwind_cache * s390_frame_unwind_cache (struct frame_info *this_frame, void **this_prologue_cache)
static void s390_frame_this_id (struct frame_info *this_frame, void **this_prologue_cache, struct frame_id *this_id)
static struct value * s390_frame_prev_register (struct frame_info *this_frame, void **this_prologue_cache, int regnum)
static struct
s390_stub_unwind_cache * s390_stub_frame_unwind_cache (struct frame_info *this_frame, void **this_prologue_cache)
static void s390_stub_frame_this_id (struct frame_info *this_frame, void **this_prologue_cache, struct frame_id *this_id)
static struct value * s390_stub_frame_prev_register (struct frame_info *this_frame, void **this_prologue_cache, int regnum)
static int s390_stub_frame_sniffer (const struct frame_unwind *self, struct frame_info *this_frame, void **this_prologue_cache)
static struct
s390_sigtramp_unwind_cache * s390_sigtramp_frame_unwind_cache (struct frame_info *this_frame, void **this_prologue_cache)
static void s390_sigtramp_frame_this_id (struct frame_info *this_frame, void **this_prologue_cache, struct frame_id *this_id)
static struct value * s390_sigtramp_frame_prev_register (struct frame_info *this_frame, void **this_prologue_cache, int regnum)
static int s390_sigtramp_frame_sniffer (const struct frame_unwind *self, struct frame_info *this_frame, void **this_prologue_cache)
static CORE_ADDR s390_frame_base_address (struct frame_info *this_frame, void **this_cache)
static CORE_ADDR s390_local_base_address (struct frame_info *this_frame, void **this_cache)
static CORE_ADDR s390_unwind_pc (struct gdbarch *gdbarch, struct frame_info *next_frame)
static CORE_ADDR s390_unwind_sp (struct gdbarch *gdbarch, struct frame_info *next_frame)
static struct value * s390_dwarf2_prev_register (struct frame_info *this_frame, void **this_cache, int regnum)
static void s390_dwarf2_frame_init_reg (struct gdbarch *gdbarch, int regnum, struct dwarf2_frame_state_reg *reg, struct frame_info *this_frame)
static int is_integer_like (struct type *type)
static int is_pointer_like (struct type *type)
static int is_float_singleton (struct type *type)
static int is_struct_like (struct type *type)
static int is_float_like (struct type *type)
static int is_power_of_two (unsigned int n)
static int s390_function_arg_pass_by_reference (struct type *type)
static int s390_function_arg_float (struct type *type)
static int s390_function_arg_integer (struct type *type)
static LONGEST extend_simple_arg (struct gdbarch *gdbarch, struct value *arg)
static int alignment_of (struct type *type)
static CORE_ADDR s390_push_dummy_call (struct gdbarch *gdbarch, struct value *function, struct regcache *regcache, CORE_ADDR bp_addr, int nargs, struct value **args, CORE_ADDR sp, int struct_return, CORE_ADDR struct_addr)
static struct frame_id s390_dummy_id (struct gdbarch *gdbarch, struct frame_info *this_frame)
static CORE_ADDR s390_frame_align (struct gdbarch *gdbarch, CORE_ADDR addr)
static enum return_value_convention s390_return_value_convention (struct gdbarch *gdbarch, struct type *type)
static enum return_value_convention s390_return_value (struct gdbarch *gdbarch, struct value *function, struct type *type, struct regcache *regcache, gdb_byte *out, const gdb_byte *in)
static const gdb_byte * s390_breakpoint_from_pc (struct gdbarch *gdbarch, CORE_ADDR *pcptr, int *lenptr)
static CORE_ADDR s390_addr_bits_remove (struct gdbarch *gdbarch, CORE_ADDR addr)
static int s390_address_class_type_flags (int byte_size, int dwarf2_addr_class)
static const char * s390_address_class_type_flags_to_name (struct gdbarch *gdbarch, int type_flags)
static int s390_address_class_name_to_type_flags (struct gdbarch *gdbarch, const char *name, int *type_flags_ptr)
static int s390_stap_is_single_operand (struct gdbarch *gdbarch, const char *s)
static struct gdbarch * s390_gdbarch_init (struct gdbarch_info info, struct gdbarch_list *arches)
void _initialize_s390_tdep (void)
Variables
static const short s390_dwarf_regmap []
const short s390_regmap_gregset []
const short s390x_regmap_gregset []
const short s390_regmap_fpregset []
const short s390_regmap_upper []
const short s390_regmap_last_break []
const short s390x_regmap_last_break []
const short s390_regmap_system_call []
const short s390_regmap_tdb []
static struct regset s390_gregset
static struct regset s390x_gregset
static struct regset s390_fpregset
static struct regset s390_upper_regset
static struct regset s390_last_break_regset
static struct regset s390x_last_break_regset
static struct regset s390_system_call_regset
static struct regset s390_tdb_regset
static struct core_regset_section s390_linux32_regset_sections []
static struct core_regset_section s390_linux32v1_regset_sections []
static struct core_regset_section s390_linux32v2_regset_sections []
static struct core_regset_section s390_linux64_regset_sections []
static struct core_regset_section s390_linux64v1_regset_sections []
static struct core_regset_section s390_linux64v2_regset_sections []
static struct core_regset_section s390x_linux64_regset_sections []
static struct core_regset_section s390x_linux64v1_regset_sections []
static struct core_regset_section s390x_linux64v2_regset_sections []
static struct frame_unwind s390_frame_unwind
static struct frame_unwind s390_stub_frame_unwind
static struct frame_unwind s390_sigtramp_frame_unwind
static struct frame_base s390_frame_base
initialize_file_ftype _initialize_s390_tdep
Define Documentation
#define S390_MAX_INSTR_SIZE 6
Definition at line 913 of file s390-tdep.c.
Referenced by s390_analyze_prologue(), s390_gdbarch_init(), and s390_stub_frame_sniffer().
#define S390_NUM_FPRS 16
Definition at line 1122 of file s390-tdep.c.
Referenced by s390_analyze_prologue(), and s390_check_for_saved().
#define S390_NUM_GPRS 16
Definition at line 1121 of file s390-tdep.c.
Referenced by s390_analyze_prologue(), and s390_check_for_saved().
Enumeration Type Documentation
anonymous enum
Enumerator:
op1_lhi
op2_lhi
op1_lghi
op2_lghi
op1_lgfi
op2_lgfi
op_lr
op_lgr
op_l
op1_ly
op2_ly
op1_lg
op2_lg
op_lm
op1_lmy
op2_lmy
op1_lmg
op2_lmg
op_st
op1_sty
op2_sty
op1_stg
op2_stg
op_std
op_stm
op1_stmy
op2_stmy
op1_stmg
op2_stmg
op1_aghi
op2_aghi
op1_ahi
op2_ahi
op1_agfi
op2_agfi
op1_afi
op2_afi
op1_algfi
op2_algfi
op1_alfi
op2_alfi
op_ar
op_agr
op_a
op1_ay
op2_ay
op1_ag
op2_ag
op1_slgfi
op2_slgfi
op1_slfi
op2_slfi
op_sr
op_sgr
op_s
op1_sy
op2_sy
op1_sg
op2_sg
op_nr
op_ngr
op_la
op1_lay
op2_lay
op1_larl
op2_larl
op_basr
op_bas
op_bcr
op_bc
op_bctr
op_bctgr
op_bct
op1_bctg
op2_bctg
op_bxh
op1_bxhg
op2_bxhg
op_bxle
op1_bxleg
op2_bxleg
op1_bras
op2_bras
op1_brasl
op2_brasl
op1_brc
op2_brc
op1_brcl
op2_brcl
op1_brct
op2_brct
op1_brctg
op2_brctg
op_brxh
op1_brxhg
op2_brxhg
op_brxle
op1_brxlg
op2_brxlg
Definition at line 843 of file s390-tdep.c.
Function Documentation
void _initialize_s390_tdep (void)
Definition at line 3373 of file s390-tdep.c.
References _initialize_s390_tdep, initialize_tdesc_s390_linux32(), initialize_tdesc_s390_linux32v1(), initialize_tdesc_s390_linux32v2(), initialize_tdesc_s390_linux64(), initialize_tdesc_s390_linux64v1(), initialize_tdesc_s390_linux64v2(), initialize_tdesc_s390_te_linux64(), initialize_tdesc_s390x_linux64(), initialize_tdesc_s390x_linux64v1(), initialize_tdesc_s390x_linux64v2(), initialize_tdesc_s390x_te_linux64(), register_gdbarch_init(), and s390_gdbarch_init().
static int alignment_of (struct type * type) [static]
Definition at line 2593 of file s390-tdep.c.
References check_typedef(), field_alignment(), gdb_assert, is_integer_like(), is_pointer_like(), TYPE_CODE, TYPE_CODE_DECFLOAT, TYPE_CODE_FLT, TYPE_CODE_STRUCT, TYPE_CODE_UNION, TYPE_FIELD_TYPE, TYPE_LENGTH, and TYPE_NFIELDS.
Referenced by s390_push_dummy_call().
static LONGEST extend_simple_arg (struct gdbarch * gdbarch, struct value * arg) [static]
Definition at line 2574 of file s390-tdep.c.
References check_typedef(), extract_signed_integer(), extract_unsigned_integer(), gdbarch_byte_order(), TYPE_LENGTH, TYPE_UNSIGNED, value_contents(), and value_type().
Referenced by s390_push_dummy_call().
static int is_float_like (struct type * type) [static]
Definition at line 2520 of file s390-tdep.c.
References is_float_singleton(), TYPE_CODE, TYPE_CODE_DECFLOAT, and TYPE_CODE_FLT.
Referenced by s390_function_arg_float().
static int is_float_singleton (struct type * type) [static]
Definition at line 2476 of file s390-tdep.c.
References CHECK_TYPEDEF, TYPE_CODE, TYPE_CODE_DECFLOAT, TYPE_CODE_FLT, TYPE_CODE_STRUCT, TYPE_FIELD_TYPE, and TYPE_NFIELDS.
Referenced by is_float_like(), and is_struct_like().
static int is_integer_like (struct type * type) [static]
Definition at line 2436 of file s390-tdep.c.
References code, TYPE_CODE, TYPE_CODE_BOOL, TYPE_CODE_CHAR, TYPE_CODE_ENUM, TYPE_CODE_INT, and TYPE_CODE_RANGE.
Referenced by alignment_of(), and s390_function_arg_integer().
static int is_pointer_like (struct type * type) [static]
Definition at line 2451 of file s390-tdep.c.
References code, TYPE_CODE, TYPE_CODE_PTR, and TYPE_CODE_REF.
Referenced by alignment_of(), and s390_function_arg_integer().
static int is_power_of_two (unsigned int n) [static]
Definition at line 2529 of file s390-tdep.c.
Referenced by s390_function_arg_integer(), and s390_function_arg_pass_by_reference().
static int is_ri (bfd_byte * insn, int op1, int op2, unsigned int * r1, int * i2) [static]
Definition at line 946 of file s390-tdep.c.
Referenced by s390_analyze_prologue(), and s390_displaced_step_fixup().
static int is_rie (bfd_byte * insn, int op1, int op2, unsigned int * r1, unsigned int * r3, int * i2) [static]
Definition at line 1065 of file s390-tdep.c.
Referenced by s390_displaced_step_fixup().
static int is_ril (bfd_byte * insn, int op1, int op2, unsigned int * r1, int * i2) [static]
Definition at line 961 of file s390-tdep.c.
Referenced by s390_analyze_prologue(), and s390_displaced_step_fixup().
static int is_rr (bfd_byte * insn, int op, unsigned int * r1, unsigned int * r2) [static]
Definition at line 982 of file s390-tdep.c.
Referenced by s390_analyze_prologue(), and s390_displaced_step_fixup().
static int is_rre (bfd_byte * insn, int op, unsigned int * r1, unsigned int * r2) [static]
Definition at line 996 of file s390-tdep.c.
Referenced by s390_analyze_prologue(), and s390_displaced_step_fixup().
static int is_rs (bfd_byte * insn, int op, unsigned int * r1, unsigned int * r3, int * d2, unsigned int * b2) [static]
Definition at line 1011 of file s390-tdep.c.
Referenced by s390_analyze_prologue(), s390_displaced_step_fixup(), and s390_in_function_epilogue_p().
static int is_rsi (bfd_byte * insn, int op, unsigned int * r1, unsigned int * r3, int * i2) [static]
Definition at line 1048 of file s390-tdep.c.
Referenced by s390_displaced_step_fixup().
static int is_rsy (bfd_byte * insn, int op1, int op2, unsigned int * r1, unsigned int * r3, int * d2, unsigned int * b2) [static]
Definition at line 1028 of file s390-tdep.c.
Referenced by s390_analyze_prologue(), s390_displaced_step_fixup(), and s390_in_function_epilogue_p().
static int is_rx (bfd_byte * insn, int op, unsigned int * r1, int * d2, unsigned int * x2, unsigned int * b2) [static]
Definition at line 1083 of file s390-tdep.c.
Referenced by s390_analyze_prologue(), and s390_displaced_step_fixup().
static int is_rxy (bfd_byte * insn, int op1, int op2, unsigned int * r1, int * d2, unsigned int * x2, unsigned int * b2) [static]
Definition at line 1100 of file s390-tdep.c.
Referenced by s390_analyze_prologue(), and s390_displaced_step_fixup().
static int is_struct_like (struct type * type) [static]
Definition at line 2501 of file s390-tdep.c.
References code, is_float_singleton(), TYPE_CODE, TYPE_CODE_STRUCT, and TYPE_CODE_UNION.
Referenced by s390_function_arg_integer(), and s390_function_arg_pass_by_reference().
static int regnum_is_gpr_full (struct gdbarch_tdep * tdep, int regnum) [static]
Definition at line 220 of file s390-tdep.c.
References gdbarch_tdep::gpr_full_regnum.
Referenced by s390_pseudo_register_name(), s390_pseudo_register_read(), s390_pseudo_register_type(), s390_pseudo_register_write(), and s390_unwind_pseudo_register().
static pv_t s390_addr (struct s390_prologue_data * data, int d2, unsigned int x2, unsigned int b2) [static]
Definition at line 1161 of file s390-tdep.c.
References s390_prologue_data::gpr, pv_add(), and pv_constant().
Referenced by s390_analyze_prologue(), s390_load(), and s390_store().
static CORE_ADDR s390_addr_bits_remove (struct gdbarch * gdbarch, CORE_ADDR addr) [static]
Definition at line 2966 of file s390-tdep.c.
Referenced by s390_gdbarch_init().
static int s390_address_class_name_to_type_flags (struct gdbarch * gdbarch, const char * name, int * type_flags_ptr) [static]
Definition at line 2990 of file s390-tdep.c.
References TYPE_INSTANCE_FLAG_ADDRESS_CLASS_1.
Referenced by s390_gdbarch_init().
static int s390_address_class_type_flags (int byte_size, int dwarf2_addr_class) [static]
Definition at line 2972 of file s390-tdep.c.
References TYPE_INSTANCE_FLAG_ADDRESS_CLASS_1.
Referenced by s390_gdbarch_init().
static const char* s390_address_class_type_flags_to_name (struct gdbarch * gdbarch, int type_flags) [static]
Definition at line 2981 of file s390-tdep.c.
References TYPE_INSTANCE_FLAG_ADDRESS_CLASS_1.
Referenced by s390_gdbarch_init().
static int s390_adjust_frame_regnum (struct gdbarch * gdbarch, int num, int eh_frame_p) [static]
Definition at line 210 of file s390-tdep.c.
Referenced by s390_gdbarch_init().
static CORE_ADDR s390_analyze_prologue (struct gdbarch * gdbarch, CORE_ADDR start_pc, CORE_ADDR current_pc, struct s390_prologue_data * data) [static]
Definition at line 1289 of file s390-tdep.c.
References s390_prologue_data::back_chain_saved_p, s390_prologue_data::byte_order, dummy, s390_prologue_data::fpr, s390_prologue_data::fpr_size, s390_prologue_data::fpr_slot, free_pv_area(), gdbarch_addr_bit(), gdbarch_byte_order(), gdbarch_ptr_bit(), s390_prologue_data::gpr, s390_prologue_data::gpr_size, s390_prologue_data::gpr_slot, is_ri(), is_ril(), is_rr(), is_rre(), is_rs(), is_rsy(), is_rx(), is_rxy(), prologue_value::kind, make_pv_area(), op1_afi, op1_ag, op1_agfi, op1_aghi, op1_ahi, op1_alfi, op1_algfi, op1_ay, op1_bras, op1_brasl, op1_brc, op1_brcl, op1_larl, op1_lay, op1_lg, op1_lgfi, op1_lghi, op1_lhi, op1_ly, op1_sg, op1_slfi, op1_slgfi, op1_stg, op1_stmg, op1_stmy, op1_sty, op1_sy, op2_afi, op2_ag, op2_agfi, op2_aghi, op2_ahi, op2_alfi, op2_algfi, op2_ay, op2_bras, op2_brasl, op2_brc, op2_brcl, op2_larl, op2_lay, op2_lg, op2_lgfi, op2_lghi, op2_lhi, op2_ly, op2_sg, op2_slfi, op2_slgfi, op2_stg, op2_stmg, op2_stmy, op2_sty, op2_sy, op_a, op_agr, op_ar, op_bas, op_basr, op_bc, op_bcr, op_l, op_la, op_lgr, op_lr, op_s, op_sgr, op_sr, op_st, op_std, op_stm, pv_add(), pv_add_constant(), pv_area_scan(), pv_constant(), pv_is_identical(), pv_is_register_k(), pv_register(), pv_subtract(), s390_addr(), s390_check_for_saved(), S390_F0_REGNUM, S390_FRAME_REGNUM, s390_load(), S390_MAX_INSTR_SIZE, S390_NUM_FPRS, S390_NUM_GPRS, S390_R0_REGNUM, s390_readinstruction(), S390_SP_REGNUM, s390_store(), sp, and s390_prologue_data::stack.
Referenced by s390_prologue_frame_unwind_cache(), and s390_skip_prologue().
static void s390_backchain_frame_unwind_cache (struct frame_info * this_frame, struct s390_unwind_cache * info) [static]
Definition at line 1987 of file s390-tdep.c.
References trad_frame_saved_reg::addr, gdbarch::byte_order, s390_unwind_cache::frame_base, s390_unwind_cache::func, gdbarch_byte_order(), gdbarch_ptr_bit(), get_frame_arch(), get_frame_pc(), get_frame_register_unsigned(), s390_unwind_cache::local_base, LONGEST, read_memory_unsigned_integer(), S390_NUM_REGS, S390_PSWA_REGNUM, S390_PSWM_REGNUM, s390_register_call_saved(), S390_RETADDR_REGNUM, S390_SP_REGNUM, safe_read_memory_integer(), s390_unwind_cache::saved_regs, sp, trad_frame_set_unknown(), and ULONGEST.
Referenced by s390_frame_unwind_cache().
static const gdb_byte* s390_breakpoint_from_pc (struct gdbarch * gdbarch, CORE_ADDR * pcptr, int * lenptr) [static]
Definition at line 2953 of file s390-tdep.c.
Referenced by s390_gdbarch_init().
static int s390_cannot_store_register (struct gdbarch * gdbarch, int regnum) [static]
Definition at line 120 of file s390-tdep.c.
References S390_LAST_BREAK_REGNUM.
Referenced by s390_gdbarch_init().
static void s390_check_for_saved (void * data_untyped, pv_t addr, CORE_ADDR size, pv_t value) [static]
Definition at line 1246 of file s390-tdep.c.
References s390_prologue_data::fpr_size, s390_prologue_data::fpr_slot, s390_prologue_data::gpr_size, s390_prologue_data::gpr_slot, prologue_value::k, offset, pv_is_register(), pv_is_register_k(), S390_F0_REGNUM, S390_NUM_FPRS, S390_NUM_GPRS, S390_R0_REGNUM, and S390_SP_REGNUM.
Referenced by s390_analyze_prologue().
static void s390_collect_regset (const struct regset * regset, const struct regcache * regcache, int regnum, void * regs, size_t len) [static]
Definition at line 636 of file s390-tdep.c.
References regset::descr, and regcache_raw_collect().
static struct target_desc* s390_core_read_description (struct gdbarch * gdbarch, struct target_ops * target, bfd * abfd) [static, read]
Definition at line 803 of file s390-tdep.c.
References s390_sizeof_gregset, s390x_sizeof_gregset, target_auxv_search(), tdesc_s390_linux32, tdesc_s390_linux32v1, tdesc_s390_linux32v2, tdesc_s390_linux64, tdesc_s390_linux64v1, tdesc_s390_linux64v2, tdesc_s390_te_linux64, tdesc_s390x_linux64, tdesc_s390x_linux64v1, tdesc_s390x_linux64v2, and tdesc_s390x_te_linux64.
Referenced by s390_gdbarch_init().
static void s390_displaced_step_fixup (struct gdbarch * gdbarch, struct displaced_step_closure * closure, CORE_ADDR from, CORE_ADDR to, struct regcache * regs) [static]
Definition at line 1615 of file s390-tdep.c.
References debug_displaced, fprintf_unfiltered(), gdb_stdlog, is_ri(), is_rie(), is_ril(), is_rr(), is_rre(), is_rs(), is_rsi(), is_rsy(), is_rx(), is_rxy(), op1_bctg, op1_bras, op1_brasl, op1_brc, op1_brcl, op1_brct, op1_brctg, op1_brxhg, op1_brxlg, op1_bxhg, op1_bxleg, op1_larl, op2_bras, op2_brasl, op2_brc, op2_brcl, op2_brct, op2_brctg, op2_brxhg, op2_brxlg, op2_bxhg, op2_bxleg, op2_larl, op_bas, op_basr, op_bc, op_bcr, op_bct, op_bctgr, op_bctr, op_brxh, op_brxle, op_bxh, op_bxle, paddress(), regcache_cooked_read_unsigned(), regcache_cooked_write_unsigned(), regcache_read_pc(), regcache_write_pc(), register_size(), S390_PSWA_REGNUM, S390_R0_REGNUM, and ULONGEST.
Referenced by s390_gdbarch_init().
static struct frame_id s390_dummy_id (struct gdbarch * gdbarch, struct frame_info * this_frame) [static, read]
Definition at line 2821 of file s390-tdep.c.
References frame_id_build(), gdbarch_addr_bits_remove(), gdbarch_ptr_bit(), get_frame_pc(), get_frame_register_unsigned(), S390_SP_REGNUM, and sp.
Referenced by s390_gdbarch_init().
static void s390_dwarf2_frame_init_reg (struct gdbarch * gdbarch, int regnum, struct dwarf2_frame_state_reg * reg, struct frame_info * this_frame) [static]
Definition at line 2397 of file s390-tdep.c.
References DWARF2_FRAME_REG_FN, DWARF2_FRAME_REG_RA, DWARF2_FRAME_REG_SAME_VALUE, DWARF2_FRAME_REG_UNDEFINED, dwarf2_frame_state_reg::fn, gdbarch_tdep(), dwarf2_frame_state_reg::how, dwarf2_frame_state_reg::loc, s390_dwarf2_prev_register(), S390_NUM_REGS, S390_PSWA_REGNUM, S390_PSWM_REGNUM, and s390_register_call_saved().
Referenced by s390_gdbarch_init().
static struct value* s390_dwarf2_prev_register (struct frame_info * this_frame, void ** this_cache, int regnum) [static, read]
Definition at line 2390 of file s390-tdep.c.
References s390_unwind_pseudo_register().
Referenced by s390_dwarf2_frame_init_reg().
static int s390_dwarf_reg_to_regnum (struct gdbarch * gdbarch, int reg) [static]
Definition at line 189 of file s390-tdep.c.
References _, gdbarch_tdep(), gdbarch_tdep::gpr_full_regnum, s390_dwarf_regmap, and warning().
Referenced by s390_gdbarch_init().
static CORE_ADDR s390_frame_align (struct gdbarch * gdbarch, CORE_ADDR addr) [static]
Definition at line 2832 of file s390-tdep.c.
Referenced by s390_gdbarch_init().
static CORE_ADDR s390_frame_base_address (struct frame_info * this_frame, void ** this_cache) [static]
Definition at line 2347 of file s390-tdep.c.
References s390_unwind_cache::frame_base, and s390_frame_unwind_cache().
static struct value* s390_frame_prev_register (struct frame_info * this_frame, void ** this_prologue_cache, int regnum) [static, read]
Definition at line 2076 of file s390-tdep.c.
References get_frame_arch(), s390_frame_unwind_cache(), s390_trad_frame_prev_register(), and s390_unwind_cache::saved_regs.
static void s390_frame_this_id (struct frame_info * this_frame, void ** this_prologue_cache, struct frame_id * this_id) [static]
Definition at line 2062 of file s390-tdep.c.
References s390_unwind_cache::frame_base, frame_id_build(), s390_unwind_cache::func, and s390_frame_unwind_cache().
static struct s390_unwind_cache* s390_frame_unwind_cache (struct frame_info * this_frame, void ** this_prologue_cache) [static, read]
Definition at line 2039 of file s390-tdep.c.
References s390_unwind_cache::frame_base, FRAME_OBSTACK_ZALLOC, s390_unwind_cache::func, s390_unwind_cache::local_base, s390_backchain_frame_unwind_cache(), s390_prologue_frame_unwind_cache(), s390_unwind_cache::saved_regs, and trad_frame_alloc_saved_regs().
Referenced by s390_frame_base_address(), s390_frame_prev_register(), s390_frame_this_id(), and s390_local_base_address().
static int s390_function_arg_float (struct type * type) [static]
Definition at line 2550 of file s390-tdep.c.
References is_float_like(), and TYPE_LENGTH.
Referenced by s390_push_dummy_call().
static int s390_function_arg_integer (struct type * type) [static]
Definition at line 2561 of file s390-tdep.c.
References is_integer_like(), is_pointer_like(), is_power_of_two(), is_struct_like(), and TYPE_LENGTH.
Referenced by s390_push_dummy_call().
static int s390_function_arg_pass_by_reference (struct type * type) [static]
Definition at line 2537 of file s390-tdep.c.
References is_power_of_two(), is_struct_like(), TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_COMPLEX, TYPE_LENGTH, and TYPE_VECTOR.
Referenced by s390_push_dummy_call().
static struct gdbarch* s390_gdbarch_init (struct gdbarch_info info, struct gdbarch_list * arches) [static, read]
Definition at line 3018 of file s390-tdep.c.
References gdbarch_tdep::abi, gdbarch_tdep::ABI_LINUX_S390, gdbarch_tdep::ABI_LINUX_ZSERIES, gdbarch_info::bfd_arch_info, gdbarch_tdep::cc_regnum, core_addr_lessthan(), displaced_step_at_entry_point(), dwarf2_append_unwinders(), dwarf2_frame_base_sniffer(), dwarf2_frame_set_adjust_regnum(), dwarf2_frame_set_init_reg(), find_solib_trampoline_target(), floatformats_ia64_quad, gdbarch_tdep::fpregset, frame_base_append_sniffer(), frame_base_set_default(), frame_unwind_append_unwinder(), gdbarch_list::gdbarch, gdbarch_alloc(), gdbarch_list_lookup_by_info(), gdbarch_num_regs(), gdbarch_tdep(), gdbarch_tdep::gpr_full_regnum, gdbarch_tdep::gregset, linux_get_siginfo_type(), linux_init_abi(), gdbarch_list::next, gdbarch_tdep::pc_regnum, S390_A0_REGNUM, s390_addr_bits_remove(), s390_address_class_name_to_type_flags(), s390_address_class_type_flags(), s390_address_class_type_flags_to_name(), s390_adjust_frame_regnum(), s390_breakpoint_from_pc(), s390_cannot_store_register(), s390_core_read_description(), s390_displaced_step_fixup(), s390_dummy_id(), s390_dwarf2_frame_init_reg(), s390_dwarf_reg_to_regnum(), S390_F0_REGNUM, S390_FPC_REGNUM, s390_fpregset, s390_frame_align(), s390_gregset, s390_in_function_epilogue_p(), S390_LAST_BREAK_REGNUM, S390_MAX_INSTR_SIZE, S390_NUM_REGS, S390_ORIG_R2_REGNUM, s390_pseudo_register_name(), s390_pseudo_register_read(), s390_pseudo_register_reggroup_p(), s390_pseudo_register_type(), s390_pseudo_register_write(), S390_PSWA_REGNUM, S390_PSWM_REGNUM, s390_push_dummy_call(), S390_R0_REGNUM, S390_R0_UPPER_REGNUM, s390_regset_from_core_section(), s390_return_value(), s390_sizeof_fpregset, s390_sizeof_gregset, s390_skip_prologue(), S390_SP_REGNUM, s390_stap_is_single_operand(), S390_SYSTEM_CALL_REGNUM, S390_TDB_DWORD0_REGNUM, s390_unwind_pc(), s390_unwind_sp(), s390_value_from_register(), s390_write_pc(), s390x_gregset, s390x_sizeof_gregset, set_gdbarch_addr_bits_remove(), set_gdbarch_address_class_name_to_type_flags(), set_gdbarch_address_class_type_flags(), set_gdbarch_address_class_type_flags_to_name(), set_gdbarch_believe_pcc_promotion(), set_gdbarch_breakpoint_from_pc(), set_gdbarch_cannot_store_register(), set_gdbarch_char_signed(), set_gdbarch_core_read_description(), set_gdbarch_core_regset_sections(), set_gdbarch_decr_pc_after_break(), set_gdbarch_displaced_step_copy_insn(), set_gdbarch_displaced_step_fixup(), set_gdbarch_displaced_step_free_closure(), set_gdbarch_displaced_step_location(), set_gdbarch_dummy_id(), set_gdbarch_dwarf2_reg_to_regnum(), set_gdbarch_fetch_tls_load_module_address(), set_gdbarch_fp0_regnum(), set_gdbarch_frame_align(), set_gdbarch_get_siginfo_type(), set_gdbarch_in_function_epilogue_p(), set_gdbarch_inner_than(), set_gdbarch_long_bit(), set_gdbarch_long_double_bit(), set_gdbarch_long_double_format(), set_gdbarch_long_long_bit(), set_gdbarch_max_insn_length(), set_gdbarch_num_pseudo_regs(), set_gdbarch_num_regs(), set_gdbarch_pc_regnum(), set_gdbarch_print_insn(), set_gdbarch_pseudo_register_read(), set_gdbarch_pseudo_register_write(), set_gdbarch_ptr_bit(), set_gdbarch_push_dummy_call(), set_gdbarch_regset_from_core_section(), set_gdbarch_return_value(), set_gdbarch_skip_prologue(), set_gdbarch_skip_trampoline_code(), set_gdbarch_sp_regnum(), set_gdbarch_stab_reg_to_regnum(), set_gdbarch_stap_is_single_operand(), set_gdbarch_stap_register_indirection_prefix(), set_gdbarch_stap_register_indirection_suffix(), set_gdbarch_stap_register_prefix(), set_gdbarch_unwind_pc(), set_gdbarch_unwind_sp(), set_gdbarch_value_from_register(), set_gdbarch_write_pc(), set_solib_svr4_fetch_link_map_offsets(), set_tdesc_pseudo_register_name(), set_tdesc_pseudo_register_reggroup_p(), set_tdesc_pseudo_register_type(), simple_displaced_step_copy_insn(), simple_displaced_step_free_closure(), gdbarch_tdep::sizeof_fpregset, gdbarch_tdep::sizeof_gregset, svr4_fetch_objfile_link_map(), svr4_ilp32_fetch_link_map_offsets(), svr4_lp64_fetch_link_map_offsets(), gdbarch_info::target_desc, tdesc_data, tdesc_data_alloc(), tdesc_data_cleanup(), tdesc_find_feature(), tdesc_has_registers(), tdesc_numbered_register(), tdesc_s390_linux32, tdesc_s390x_linux64, tdesc_unnumbered_register(), tdesc_use_registers(), and XCALLOC.
Referenced by _initialize_s390_tdep().
static int s390_in_function_epilogue_p (struct gdbarch * gdbarch, CORE_ADDR pc) [static]
Definition at line 1562 of file s390-tdep.c.
References gdbarch_ptr_bit(), is_rs(), is_rsy(), op1_lmg, op1_lmy, op2_lmg, op2_lmy, op_lm, S390_R0_REGNUM, S390_SP_REGNUM, and target_read_memory().
Referenced by s390_gdbarch_init(), and s390_prologue_frame_unwind_cache().
static pv_t s390_load (struct s390_prologue_data * data, int d2, unsigned int x2, unsigned int b2, CORE_ADDR size) [static]
Definition at line 1211 of file s390-tdep.c.
References s390_prologue_data::byte_order, current_target, prologue_value::k, pv_area_fetch(), pv_constant(), pv_is_constant(), read_memory_integer(), s390_addr(), s390_prologue_data::stack, target_section_by_addr(), and target_section::the_bfd_section.
Referenced by s390_analyze_prologue().
static CORE_ADDR s390_local_base_address (struct frame_info * this_frame, void ** this_cache) [static]
Definition at line 2355 of file s390-tdep.c.
References s390_unwind_cache::local_base, and s390_frame_unwind_cache().
static int s390_prologue_frame_unwind_cache (struct frame_info * this_frame, struct s390_unwind_cache * info) [static]
Definition at line 1804 of file s390-tdep.c.
References trad_frame_saved_reg::addr, s390_prologue_data::fpr_slot, s390_unwind_cache::frame_base, func, s390_unwind_cache::func, gdbarch_addr_bits_remove(), gdbarch_ptr_bit(), get_frame_arch(), get_frame_func(), get_frame_pc(), get_frame_register_unsigned(), get_frame_type(), get_next_frame(), get_pc_function_start(), s390_prologue_data::gpr, s390_prologue_data::gpr_slot, INLINE_FRAME, prologue_value::k, s390_unwind_cache::local_base, memset(), NORMAL_FRAME, pv_is_identical(), pv_is_register(), trad_frame_saved_reg::realreg, s390_analyze_prologue(), S390_F0_REGNUM, S390_FRAME_REGNUM, s390_in_function_epilogue_p(), S390_NUM_REGS, S390_PSWA_REGNUM, S390_PSWM_REGNUM, S390_R0_REGNUM, s390_register_call_saved(), S390_RETADDR_REGNUM, S390_SP_REGNUM, s390_unwind_cache::saved_regs, size, sp, trad_frame_addr_p(), trad_frame_set_unknown(), and ULONGEST.
Referenced by s390_frame_unwind_cache().
static const char* s390_pseudo_register_name (struct gdbarch * gdbarch, int regnum) [static]
Definition at line 228 of file s390-tdep.c.
References _, gdbarch_tdep::cc_regnum, gdbarch_tdep(), gdbarch_tdep::gpr_full_regnum, internal_error(), gdbarch_tdep::pc_regnum, and regnum_is_gpr_full().
Referenced by s390_gdbarch_init().
static enum register_status s390_pseudo_register_read (struct gdbarch * gdbarch, struct regcache * regcache, int regnum, gdb_byte * buf) [static]
Definition at line 268 of file s390-tdep.c.
References _, gdbarch_tdep::cc_regnum, gdbarch_byte_order(), gdbarch_tdep(), gdbarch_tdep::gpr_full_regnum, internal_error(), gdbarch_tdep::pc_regnum, REG_VALID, regcache_raw_read_unsigned(), register_size(), regnum_is_gpr_full(), S390_PSWA_REGNUM, S390_PSWM_REGNUM, S390_R0_REGNUM, S390_R0_UPPER_REGNUM, exsummary::status, store_unsigned_integer(), and ULONGEST.
Referenced by s390_gdbarch_init().
static int s390_pseudo_register_reggroup_p (struct gdbarch * gdbarch, int regnum, struct reggroup * group) [static]
Definition at line 396 of file s390-tdep.c.
References gdbarch_tdep::cc_regnum, default_register_reggroup_p(), gdbarch_tdep(), gdbarch_tdep::pc_regnum, restore_reggroup, and save_reggroup.
Referenced by s390_gdbarch_init().
static struct type* s390_pseudo_register_type (struct gdbarch * gdbarch, int regnum) [static, read]
Definition at line 251 of file s390-tdep.c.
References _, builtin_type::builtin_func_ptr, builtin_type::builtin_int, builtin_type(), builtin_type::builtin_uint64, gdbarch_tdep::cc_regnum, gdbarch_tdep(), internal_error(), gdbarch_tdep::pc_regnum, and regnum_is_gpr_full().
Referenced by s390_gdbarch_init().
static void s390_pseudo_register_write (struct gdbarch * gdbarch, struct regcache * regcache, int regnum, const gdb_byte * buf) [static]
Definition at line 329 of file s390-tdep.c.
References _, gdbarch_tdep::cc_regnum, extract_unsigned_integer(), gdbarch_byte_order(), gdbarch_tdep(), gdbarch_tdep::gpr_full_regnum, internal_error(), gdbarch_tdep::pc_regnum, regcache_raw_read_unsigned(), regcache_raw_write_unsigned(), register_size(), regnum_is_gpr_full(), S390_PSWA_REGNUM, S390_PSWM_REGNUM, S390_R0_REGNUM, S390_R0_UPPER_REGNUM, and ULONGEST.
Referenced by s390_gdbarch_init().
static CORE_ADDR s390_push_dummy_call (struct gdbarch * gdbarch, struct value * function, struct regcache * regcache, CORE_ADDR bp_addr, int nargs, struct value ** args, CORE_ADDR sp, int struct_return, CORE_ADDR struct_addr) [static]
Definition at line 2644 of file s390-tdep.c.
References _, gdbarch_tdep::abi, align_down(), align_up(), alignment_of(), check_typedef(), error(), extend_simple_arg(), gdbarch_addr_bits_remove(), gdbarch_byte_order(), gdbarch_ptr_bit(), gdbarch_tdep(), internal_error(), type::length, regcache_cooked_read_unsigned(), regcache_cooked_write(), regcache_cooked_write_part(), regcache_cooked_write_signed(), regcache_cooked_write_unsigned(), S390_F0_REGNUM, s390_function_arg_float(), s390_function_arg_integer(), s390_function_arg_pass_by_reference(), S390_PSWA_REGNUM, S390_R0_REGNUM, S390_RETADDR_REGNUM, S390_SP_REGNUM, TYPE_LENGTH, ULONGEST, value_contents(), value_type(), write_memory(), write_memory_signed_integer(), and write_memory_unsigned_integer().
Referenced by s390_gdbarch_init().
static int s390_readinstruction (bfd_byte instr[], CORE_ADDR at) [static]
Definition at line 915 of file s390-tdep.c.
References target_read_memory().
Referenced by s390_analyze_prologue(), and s390_stub_frame_sniffer().
static int s390_register_call_saved (struct gdbarch * gdbarch, int regnum) [static]
Definition at line 93 of file s390-tdep.c.
References gdbarch_tdep::abi, gdbarch_tdep::ABI_LINUX_S390, gdbarch_tdep::ABI_LINUX_ZSERIES, gdbarch_tdep(), S390_A0_REGNUM, S390_A1_REGNUM, S390_F15_REGNUM, S390_F4_REGNUM, S390_F6_REGNUM, S390_F8_REGNUM, S390_R15_REGNUM, and S390_R6_REGNUM.
Referenced by s390_backchain_frame_unwind_cache(), s390_dwarf2_frame_init_reg(), and s390_prologue_frame_unwind_cache().
static struct regset* s390_regset_from_core_section (struct gdbarch * gdbarch, const char * sect_name, size_t sect_size) [static, read]
Definition at line 775 of file s390-tdep.c.
References gdbarch_tdep::fpregset, gdbarch_ptr_bit(), gdbarch_tdep(), gdbarch_tdep::gregset, s390_system_call_regset, s390_tdb_regset, s390_upper_regset, gdbarch_tdep::sizeof_fpregset, and gdbarch_tdep::sizeof_gregset.
Referenced by s390_gdbarch_init().
static enum return_value_convention s390_return_value (struct gdbarch * gdbarch, struct value * function, struct type * type, struct regcache * regcache, gdb_byte * out, const gdb_byte * in) [static]
Definition at line 2862 of file s390-tdep.c.
References _, check_typedef(), error(), extract_signed_integer(), extract_unsigned_integer(), gdbarch_byte_order(), gdbarch_ptr_bit(), internal_error(), regcache_cooked_read(), regcache_cooked_read_part(), regcache_cooked_write(), regcache_cooked_write_part(), regcache_cooked_write_signed(), regcache_cooked_write_unsigned(), RETURN_VALUE_REGISTER_CONVENTION, RETURN_VALUE_STRUCT_CONVENTION, S390_F0_REGNUM, S390_R2_REGNUM, S390_R3_REGNUM, s390_return_value_convention(), TYPE_CODE, TYPE_CODE_DECFLOAT, TYPE_CODE_FLT, TYPE_LENGTH, and TYPE_UNSIGNED.
Referenced by s390_gdbarch_init().
static enum return_value_convention s390_return_value_convention (struct gdbarch * gdbarch, struct type * type) [static]
Definition at line 2843 of file s390-tdep.c.
References RETURN_VALUE_REGISTER_CONVENTION, RETURN_VALUE_STRUCT_CONVENTION, TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_COMPLEX, TYPE_CODE_STRUCT, TYPE_CODE_UNION, and TYPE_LENGTH.
Referenced by s390_return_value().
static struct value* s390_sigtramp_frame_prev_register (struct frame_info * this_frame, void ** this_prologue_cache, int regnum) [static, read]
Definition at line 2305 of file s390-tdep.c.
References s390_sigtramp_frame_unwind_cache(), s390_trad_frame_prev_register(), and s390_sigtramp_unwind_cache::saved_regs.
static int s390_sigtramp_frame_sniffer (const struct frame_unwind * self, struct frame_info * this_frame, void ** this_prologue_cache) [static]
Definition at line 2314 of file s390-tdep.c.
References get_frame_pc(), and target_read_memory().
static void s390_sigtramp_frame_this_id (struct frame_info * this_frame, void ** this_prologue_cache, struct frame_id * this_id) [static]
Definition at line 2295 of file s390-tdep.c.
References s390_sigtramp_unwind_cache::frame_base, frame_id_build(), get_frame_pc(), and s390_sigtramp_frame_unwind_cache().
static struct s390_sigtramp_unwind_cache* s390_sigtramp_frame_unwind_cache (struct frame_info * this_frame, void ** this_prologue_cache) [static, read]
Definition at line 2187 of file s390-tdep.c.
References trad_frame_saved_reg::addr, align_up(), s390_sigtramp_unwind_cache::frame_base, FRAME_OBSTACK_ZALLOC, gdbarch_byte_order(), gdbarch_ptr_bit(), gdbarch_tdep(), get_frame_arch(), get_frame_pc(), get_frame_register_unsigned(), gdbarch_tdep::gpr_full_regnum, read_memory_unsigned_integer(), S390_A0_REGNUM, S390_F0_REGNUM, S390_FPC_REGNUM, S390_PSWA_REGNUM, S390_PSWM_REGNUM, S390_R0_REGNUM, S390_R0_UPPER_REGNUM, S390_SP_REGNUM, s390_sigtramp_unwind_cache::saved_regs, trad_frame_alloc_saved_regs(), and ULONGEST.
Referenced by s390_sigtramp_frame_prev_register(), and s390_sigtramp_frame_this_id().
static CORE_ADDR s390_skip_prologue (struct gdbarch * gdbarch, CORE_ADDR pc) [static]
Definition at line 1551 of file s390-tdep.c.
References s390_analyze_prologue().
Referenced by s390_gdbarch_init().
static int s390_stap_is_single_operand (struct gdbarch * gdbarch, const char * s) [static]
Definition at line 3007 of file s390-tdep.c.
Referenced by s390_gdbarch_init().
static void s390_store (struct s390_prologue_data * data, int d2, unsigned int x2, unsigned int b2, CORE_ADDR size, pv_t value) [static]
Definition at line 1177 of file s390-tdep.c.
References s390_prologue_data::back_chain_saved_p, s390_prologue_data::gpr, s390_prologue_data::gpr_size, prologue_value::k, offset, pv_area_store(), pv_area_store_would_trash(), pv_is_constant(), pv_is_register_k(), pv_subtract(), s390_addr(), S390_R0_REGNUM, S390_SP_REGNUM, and s390_prologue_data::stack.
Referenced by s390_analyze_prologue().
static struct value* s390_stub_frame_prev_register (struct frame_info * this_frame, void ** this_prologue_cache, int regnum) [static, read]
Definition at line 2143 of file s390-tdep.c.
References s390_stub_frame_unwind_cache(), s390_trad_frame_prev_register(), and s390_stub_unwind_cache::saved_regs.
static int s390_stub_frame_sniffer (const struct frame_unwind * self, struct frame_info * this_frame, void ** this_prologue_cache) [static]
Definition at line 2152 of file s390-tdep.c.
References get_frame_address_in_block(), get_frame_pc(), in_plt_section(), S390_MAX_INSTR_SIZE, and s390_readinstruction().
static void s390_stub_frame_this_id (struct frame_info * this_frame, void ** this_prologue_cache, struct frame_id * this_id) [static]
Definition at line 2133 of file s390-tdep.c.
References s390_stub_unwind_cache::frame_base, frame_id_build(), get_frame_pc(), and s390_stub_frame_unwind_cache().
static struct s390_stub_unwind_cache* s390_stub_frame_unwind_cache (struct frame_info * this_frame, void ** this_prologue_cache) [static, read]
Definition at line 2107 of file s390-tdep.c.
References s390_stub_unwind_cache::frame_base, FRAME_OBSTACK_ZALLOC, gdbarch_ptr_bit(), get_frame_arch(), get_frame_register_unsigned(), trad_frame_saved_reg::realreg, S390_PSWA_REGNUM, S390_RETADDR_REGNUM, S390_SP_REGNUM, s390_stub_unwind_cache::saved_regs, trad_frame_alloc_saved_regs(), and ULONGEST.
Referenced by s390_stub_frame_prev_register(), and s390_stub_frame_this_id().
static void s390_supply_regset (const struct regset * regset, struct regcache * regcache, int regnum, const void * regs, size_t len) [static]
Definition at line 604 of file s390-tdep.c.
References regset::descr, and regcache_raw_supply().
Referenced by s390_supply_tdb_regset().
static void s390_supply_tdb_regset (const struct regset * regset, struct regcache * regcache, int regnum, const void * regs, size_t len) [static]
Definition at line 618 of file s390-tdep.c.
References REG_VALID, regcache_cooked_read_unsigned(), s390_supply_regset(), S390_TDB_DWORD0_REGNUM, and ULONGEST.
static struct value* s390_trad_frame_prev_register (struct frame_info * this_frame, struct trad_frame_saved_reg saved_regs[], int regnum) [static, read]
Definition at line 1781 of file s390-tdep.c.
References S390_NUM_REGS, s390_unwind_pseudo_register(), and trad_frame_get_prev_register().
Referenced by s390_frame_prev_register(), s390_sigtramp_frame_prev_register(), and s390_stub_frame_prev_register().
static CORE_ADDR s390_unwind_pc (struct gdbarch * gdbarch, struct frame_info * next_frame) [static]
Definition at line 2370 of file s390-tdep.c.
References frame_unwind_register_unsigned(), gdbarch_addr_bits_remove(), gdbarch_tdep(), gdbarch_tdep::pc, gdbarch_tdep::pc_regnum, and ULONGEST.
Referenced by s390_gdbarch_init().
static struct value* s390_unwind_pseudo_register (struct frame_info * this_frame, int regnum) [static, read]
Definition at line 1725 of file s390-tdep.c.
References allocate_optimized_out_value(), gdbarch_tdep::cc_regnum, frame_unwind_register_value(), gdbarch_tdep(), get_frame_arch(), gdbarch_tdep::gpr_full_regnum, LONGEST, gdbarch_tdep::pc_regnum, register_type(), regnum_is_gpr_full(), S390_PSWA_REGNUM, S390_PSWM_REGNUM, S390_R0_REGNUM, TYPE_LENGTH, value_as_long(), value_cast(), value_from_longest(), value_from_pointer(), and value_optimized_out().
Referenced by s390_dwarf2_prev_register(), and s390_trad_frame_prev_register().
static CORE_ADDR s390_unwind_sp (struct gdbarch * gdbarch, struct frame_info * next_frame) [static]
Definition at line 2379 of file s390-tdep.c.
References frame_unwind_register_unsigned(), gdbarch_addr_bits_remove(), S390_SP_REGNUM, gdbarch_tdep::sp, and ULONGEST.
Referenced by s390_gdbarch_init().
static struct value* s390_value_from_register (struct type * type, int regnum, struct frame_info * frame) [static, read]
Definition at line 379 of file s390-tdep.c.
References check_typedef(), default_value_from_register(), S390_F0_REGNUM, S390_F15_REGNUM, set_value_offset(), and TYPE_LENGTH.
Referenced by s390_gdbarch_init().
static void s390_write_pc (struct regcache * regcache, CORE_ADDR pc) [static]
Definition at line 127 of file s390-tdep.c.
References gdbarch_tdep(), get_regcache_arch(), gdbarch_tdep::pc_regnum, regcache_cooked_write_unsigned(), register_size(), and S390_SYSTEM_CALL_REGNUM.
Referenced by s390_gdbarch_init().
Variable Documentation
initialize_file_ftype _initialize_s390_tdep
Referenced by _initialize_s390_tdep(), and initialize_all_files().
const short s390_dwarf_regmap[] [static]
Definition at line 148 of file s390-tdep.c.
Referenced by s390_dwarf_reg_to_regnum().
struct regset s390_fpregset [static]
Initial value:
 {
  s390_regmap_fpregset,
  s390_supply_regset,
  s390_collect_regset
}
Definition at line 658 of file s390-tdep.c.
Referenced by s390_gdbarch_init().
struct frame_base s390_frame_base [static]
Initial value:
 {
  &s390_frame_unwind,
  s390_frame_base_address,
  s390_local_base_address,
  s390_local_base_address
}
Definition at line 2362 of file s390-tdep.c.
struct frame_unwind s390_frame_unwind [static]
Initial value:
 {
  NORMAL_FRAME,
  default_frame_unwind_stop_reason,
  s390_frame_this_id,
  s390_frame_prev_register,
  NULL,
  default_frame_sniffer
}
Definition at line 2086 of file s390-tdep.c.
struct regset s390_gregset [static]
Initial value:
 {
  s390_regmap_gregset,
  s390_supply_regset,
  s390_collect_regset
}
Definition at line 646 of file s390-tdep.c.
Referenced by s390_gdbarch_init().
struct regset s390_last_break_regset [static]
Initial value:
 {
  s390_regmap_last_break,
  s390_supply_regset,
  s390_collect_regset
}
Definition at line 670 of file s390-tdep.c.
struct core_regset_section s390_linux32_regset_sections[] [static]
Initial value:
{
  { ".reg", s390_sizeof_gregset, "general-purpose" },
  { ".reg2", s390_sizeof_fpregset, "floating-point" },
  { NULL, 0}
}
Definition at line 694 of file s390-tdep.c.
struct core_regset_section s390_linux32v1_regset_sections[] [static]
Initial value:
{
  { ".reg", s390_sizeof_gregset, "general-purpose" },
  { ".reg2", s390_sizeof_fpregset, "floating-point" },
  { ".reg-s390-last-break", 8, "s390 last-break address" },
  { NULL, 0}
}
Definition at line 701 of file s390-tdep.c.
struct core_regset_section s390_linux32v2_regset_sections[] [static]
Initial value:
{
  { ".reg", s390_sizeof_gregset, "general-purpose" },
  { ".reg2", s390_sizeof_fpregset, "floating-point" },
  { ".reg-s390-last-break", 8, "s390 last-break address" },
  { ".reg-s390-system-call", 4, "s390 system-call" },
  { NULL, 0}
}
Definition at line 709 of file s390-tdep.c.
struct core_regset_section s390_linux64_regset_sections[] [static]
Initial value:
{
  { ".reg", s390_sizeof_gregset, "general-purpose" },
  { ".reg2", s390_sizeof_fpregset, "floating-point" },
  { ".reg-s390-high-gprs", 16*4, "s390 GPR upper halves" },
  { NULL, 0}
}
Definition at line 718 of file s390-tdep.c.
struct core_regset_section s390_linux64v1_regset_sections[] [static]
Initial value:
{
  { ".reg", s390_sizeof_gregset, "general-purpose" },
  { ".reg2", s390_sizeof_fpregset, "floating-point" },
  { ".reg-s390-high-gprs", 16*4, "s390 GPR upper halves" },
  { ".reg-s390-last-break", 8, "s930 last-break address" },
  { NULL, 0}
}
Definition at line 726 of file s390-tdep.c.
struct core_regset_section s390_linux64v2_regset_sections[] [static]
Initial value:
{
  { ".reg", s390_sizeof_gregset, "general-purpose" },
  { ".reg2", s390_sizeof_fpregset, "floating-point" },
  { ".reg-s390-high-gprs", 16*4, "s390 GPR upper halves" },
  { ".reg-s390-last-break", 8, "s930 last-break address" },
  { ".reg-s390-system-call", 4, "s390 system-call" },
  { ".reg-s390-tdb", s390_sizeof_tdbregset, "s390 TDB" },
  { NULL, 0}
}
Definition at line 735 of file s390-tdep.c.
const short s390_regmap_fpregset[]
Initial value:
  {
    0x00, S390_FPC_REGNUM,
    0x08, S390_F0_REGNUM,
    0x10, S390_F1_REGNUM,
    0x18, S390_F2_REGNUM,
    0x20, S390_F3_REGNUM,
    0x28, S390_F4_REGNUM,
    0x30, S390_F5_REGNUM,
    0x38, S390_F6_REGNUM,
    0x40, S390_F7_REGNUM,
    0x48, S390_F8_REGNUM,
    0x50, S390_F9_REGNUM,
    0x58, S390_F10_REGNUM,
    0x60, S390_F11_REGNUM,
    0x68, S390_F12_REGNUM,
    0x70, S390_F13_REGNUM,
    0x78, S390_F14_REGNUM,
    0x80, S390_F15_REGNUM,
    -1, -1
  }
Definition at line 514 of file s390-tdep.c.
const short s390_regmap_gregset[]
Definition at line 418 of file s390-tdep.c.
const short s390_regmap_last_break[]
Initial value:
  {
    0x04, S390_LAST_BREAK_REGNUM,
    -1, -1
  }
Definition at line 557 of file s390-tdep.c.
Referenced by s390_linux_fetch_inferior_registers().
const short s390_regmap_system_call[]
Initial value:
  {
    0x00, S390_SYSTEM_CALL_REGNUM,
    -1, -1
  }
Definition at line 569 of file s390-tdep.c.
Referenced by s390_linux_fetch_inferior_registers(), and s390_linux_store_inferior_registers().
const short s390_regmap_tdb[]
Initial value:
  {
    0x00, S390_TDB_DWORD0_REGNUM,
    0x08, S390_TDB_ABORT_CODE_REGNUM,
    0x10, S390_TDB_CONFLICT_TOKEN_REGNUM,
    0x18, S390_TDB_ATIA_REGNUM,
    0x80, S390_TDB_R0_REGNUM,
    0x88, S390_TDB_R1_REGNUM,
    0x90, S390_TDB_R2_REGNUM,
    0x98, S390_TDB_R3_REGNUM,
    0xa0, S390_TDB_R4_REGNUM,
    0xa8, S390_TDB_R5_REGNUM,
    0xb0, S390_TDB_R6_REGNUM,
    0xb8, S390_TDB_R7_REGNUM,
    0xc0, S390_TDB_R8_REGNUM,
    0xc8, S390_TDB_R9_REGNUM,
    0xd0, S390_TDB_R10_REGNUM,
    0xd8, S390_TDB_R11_REGNUM,
    0xe0, S390_TDB_R12_REGNUM,
    0xe8, S390_TDB_R13_REGNUM,
    0xf0, S390_TDB_R14_REGNUM,
    0xf8, S390_TDB_R15_REGNUM,
    -1, -1
  }
Definition at line 575 of file s390-tdep.c.
Referenced by s390_linux_fetch_inferior_registers().
const short s390_regmap_upper[]
Initial value:
  {
    0x00, S390_R0_UPPER_REGNUM,
    0x04, S390_R1_UPPER_REGNUM,
    0x08, S390_R2_UPPER_REGNUM,
    0x0c, S390_R3_UPPER_REGNUM,
    0x10, S390_R4_UPPER_REGNUM,
    0x14, S390_R5_UPPER_REGNUM,
    0x18, S390_R6_UPPER_REGNUM,
    0x1c, S390_R7_UPPER_REGNUM,
    0x20, S390_R8_UPPER_REGNUM,
    0x24, S390_R9_UPPER_REGNUM,
    0x28, S390_R10_UPPER_REGNUM,
    0x2c, S390_R11_UPPER_REGNUM,
    0x30, S390_R12_UPPER_REGNUM,
    0x34, S390_R13_UPPER_REGNUM,
    0x38, S390_R14_UPPER_REGNUM,
    0x3c, S390_R15_UPPER_REGNUM,
    -1, -1
  }
Definition at line 536 of file s390-tdep.c.
struct frame_unwind s390_sigtramp_frame_unwind [static]
Initial value:
 {
  SIGTRAMP_FRAME,
  default_frame_unwind_stop_reason,
  s390_sigtramp_frame_this_id,
  s390_sigtramp_frame_prev_register,
  NULL,
  s390_sigtramp_frame_sniffer
}
Definition at line 2334 of file s390-tdep.c.
struct frame_unwind s390_stub_frame_unwind [static]
Initial value:
 {
  NORMAL_FRAME,
  default_frame_unwind_stop_reason,
  s390_stub_frame_this_id,
  s390_stub_frame_prev_register,
  NULL,
  s390_stub_frame_sniffer
}
Definition at line 2169 of file s390-tdep.c.
struct regset s390_system_call_regset [static]
Initial value:
 {
  s390_regmap_system_call,
  s390_supply_regset,
  s390_collect_regset
}
Definition at line 682 of file s390-tdep.c.
Referenced by s390_regset_from_core_section().
struct regset s390_tdb_regset [static]
Initial value:
 {
  s390_regmap_tdb,
  s390_supply_tdb_regset,
  s390_collect_regset
}
Definition at line 688 of file s390-tdep.c.
Referenced by s390_regset_from_core_section().
struct regset s390_upper_regset [static]
Initial value:
 {
  s390_regmap_upper,
  s390_supply_regset,
  s390_collect_regset
}
Definition at line 664 of file s390-tdep.c.
Referenced by s390_regset_from_core_section().
struct regset s390x_gregset [static]
Initial value:
 {
  s390x_regmap_gregset,
  s390_supply_regset,
  s390_collect_regset
}
Definition at line 652 of file s390-tdep.c.
Referenced by s390_gdbarch_init().
struct regset s390x_last_break_regset [static]
Initial value:
 {
  s390x_regmap_last_break,
  s390_supply_regset,
  s390_collect_regset
}
Definition at line 676 of file s390-tdep.c.
struct core_regset_section s390x_linux64_regset_sections[] [static]
Initial value:
{
  { ".reg", s390x_sizeof_gregset, "general-purpose" },
  { ".reg2", s390_sizeof_fpregset, "floating-point" },
  { NULL, 0}
}
Definition at line 746 of file s390-tdep.c.
struct core_regset_section s390x_linux64v1_regset_sections[] [static]
Initial value:
{
  { ".reg", s390x_sizeof_gregset, "general-purpose" },
  { ".reg2", s390_sizeof_fpregset, "floating-point" },
  { ".reg-s390-last-break", 8, "s930 last-break address" },
  { NULL, 0}
}
Definition at line 753 of file s390-tdep.c.
struct core_regset_section s390x_linux64v2_regset_sections[] [static]
Initial value:
{
  { ".reg", s390x_sizeof_gregset, "general-purpose" },
  { ".reg2", s390_sizeof_fpregset, "floating-point" },
  { ".reg-s390-last-break", 8, "s930 last-break address" },
  { ".reg-s390-system-call", 4, "s390 system-call" },
  { ".reg-s390-tdb", s390_sizeof_tdbregset, "s390 TDB" },
  { NULL, 0}
}
Definition at line 761 of file s390-tdep.c.
const short s390x_regmap_gregset[]
Definition at line 458 of file s390-tdep.c.
const short s390x_regmap_last_break[]
Initial value:
  {
    0x00, S390_LAST_BREAK_REGNUM,
    -1, -1
  }
Definition at line 563 of file s390-tdep.c.
Referenced by s390_linux_fetch_inferior_registers().