GDB (xrefs): /home/stan/gdb/src/gdb/sentinel-frame.c File Reference
/home/stan/gdb/src/gdb/sentinel-frame.c File Reference
#include "defs.h"
#include "regcache.h"
#include "sentinel-frame.h"
#include "inferior.h"
#include "frame-unwind.h"
Classes
struct frame_unwind_cache
Functions
void * sentinel_frame_cache (struct regcache *regcache)
static struct value * sentinel_frame_prev_register (struct frame_info *this_frame, void **this_prologue_cache, int regnum)
static void sentinel_frame_this_id (struct frame_info *this_frame, void **this_prologue_cache, struct frame_id *this_id)
static struct gdbarch * sentinel_frame_prev_arch (struct frame_info *this_frame, void **this_prologue_cache)
Variables
struct frame_unwind sentinel_frame_unwind
Function Documentation
void* sentinel_frame_cache (struct regcache * regcache)
Definition at line 33 of file sentinel-frame.c.
References FRAME_OBSTACK_ZALLOC, and frame_unwind_cache::regcache.
Referenced by create_sentinel_frame().
static struct gdbarch* sentinel_frame_prev_arch (struct frame_info * this_frame, void ** this_prologue_cache) [static, read]
Definition at line 70 of file sentinel-frame.c.
References get_regcache_arch(), and frame_unwind_cache::regcache.
static struct value* sentinel_frame_prev_register (struct frame_info * this_frame, void ** this_prologue_cache, int regnum) [static, read]
Definition at line 45 of file sentinel-frame.c.
References get_frame_id(), frame_unwind_cache::regcache, regcache_cooked_read_value(), and VALUE_FRAME_ID.
static void sentinel_frame_this_id (struct frame_info * this_frame, void ** this_prologue_cache, struct frame_id * this_id) [static]
Definition at line 59 of file sentinel-frame.c.
References _, and internal_error().
Variable Documentation
struct frame_unwind sentinel_frame_unwind
Initial value:
{
  SENTINEL_FRAME,
  default_frame_unwind_stop_reason,
  sentinel_frame_this_id,
  sentinel_frame_prev_register,
  NULL,
  NULL,
  NULL,
  sentinel_frame_prev_arch,
}
Definition at line 78 of file sentinel-frame.c.
Referenced by create_sentinel_frame().