GDB (xrefs): /home/stan/gdb/src/gdb/ser-pipe.c File Reference
/home/stan/gdb/src/gdb/ser-pipe.c File Reference
#include "defs.h"
#include "serial.h"
#include "ser-base.h"
#include "ser-unix.h"
#include "gdb_vfork.h"
#include <sys/types.h>
#include <sys/socket.h>
#include <sys/time.h>
#include <fcntl.h>
#include "gdb_string.h"
#include "filestuff.h"
#include <signal.h>
Classes
struct pipe_state
Defines
#define PIPE_CLOSE_TIMEOUT 5
#define SIGTERM_TIMEOUT INT_MAX
Functions
static int pipe_open (struct serial *scb, const char *name)
static void pipe_close (struct serial *scb)
void _initialize_ser_pipe (void)
int gdb_pipe (int pdes[2])
Define Documentation
#define PIPE_CLOSE_TIMEOUT 5
Referenced by pipe_close().
#define SIGTERM_TIMEOUT INT_MAX
Referenced by pipe_close().
Function Documentation
void _initialize_ser_pipe (void)
int gdb_pipe (int pdes[2])
Definition at line 192 of file ser-pipe.c.
References gdb_socketpair_cloexec().
static void pipe_close (struct serial * scb) [static]
Definition at line 150 of file ser-pipe.c.
References serial::error_fd, serial::fd, pipe_state::pid, PIPE_CLOSE_TIMEOUT, SIGTERM_TIMEOUT, serial::state, exsummary::status, and xfree().
static int pipe_open (struct serial * scb, const char * name) [static]
Definition at line 50 of file ser-pipe.c.
References close_most_fds(), serial::error_fd, serial::fd, gdb_socketpair_cloexec(), pipe_state::pid, serial::state, and XMALLOC.