GDB (xrefs): /home/stan/gdb/src/gdb/ser-base.c File Reference
/home/stan/gdb/src/gdb/ser-base.c File Reference
#include "defs.h"
#include "serial.h"
#include "ser-base.h"
#include "event-loop.h"
#include "gdb_select.h"
#include "gdb_string.h"
#include "gdb_assert.h"
#include <sys/time.h>
Enumerations
enum { FD_SCHEDULED = -1, NOTHING_SCHEDULED = -2 }
Functions
static void reschedule (struct serial *scb)
static void run_async_handler_and_reschedule (struct serial *scb)
static void fd_event (int error, void *context)
static void push_event (void *context)
static int ser_base_wait_for (struct serial *scb, int timeout)
static void ser_base_read_error_fd (struct serial *scb, int close_fd)
static int do_ser_base_readchar (struct serial *scb, int timeout)
int generic_readchar (struct serial *scb, int timeout, int(do_readchar)(struct serial *scb, int timeout))
int ser_base_readchar (struct serial *scb, int timeout)
int ser_base_write (struct serial *scb, const void *buf, size_t count)
int ser_base_flush_output (struct serial *scb)
int ser_base_flush_input (struct serial *scb)
int ser_base_send_break (struct serial *scb)
int ser_base_drain_output (struct serial *scb)
void ser_base_raw (struct serial *scb)
serial_ttystate ser_base_get_tty_state (struct serial *scb)
serial_ttystate ser_base_copy_tty_state (struct serial *scb, serial_ttystate ttystate)
int ser_base_set_tty_state (struct serial *scb, serial_ttystate ttystate)
int ser_base_noflush_set_tty_state (struct serial *scb, serial_ttystate new_ttystate, serial_ttystate old_ttystate)
void ser_base_print_tty_state (struct serial *scb, serial_ttystate ttystate, struct ui_file *stream)
int ser_base_setbaudrate (struct serial *scb, int rate)
int ser_base_setstopbits (struct serial *scb, int num)
void ser_base_async (struct serial *scb, int async_p)
Variables
static timer_handler_func push_event
static handler_func fd_event
Enumeration Type Documentation
anonymous enum
Enumerator:
FD_SCHEDULED
NOTHING_SCHEDULED
Definition at line 47 of file ser-base.c.
Function Documentation
static int do_ser_base_readchar (struct serial * scb, int timeout) [static]
Definition at line 309 of file ser-base.c.
References serial::buf, serial::bufcnt, serial::bufp, deprecated_ui_loop_hook, serial::ops, serial_ops::read_prim, ser_base_read_error_fd(), ser_base_wait_for(), SERIAL_EOF, SERIAL_ERROR, SERIAL_TIMEOUT, and exsummary::status.
Referenced by ser_base_readchar().
static void fd_event (int error, void * context) [static]
Definition at line 156 of file ser-base.c.
References serial::buf, serial::bufcnt, serial::bufp, serial::ops, serial_ops::read_prim, run_async_handler_and_reschedule(), SERIAL_EOF, and SERIAL_ERROR.
int generic_readchar (struct serial * scb, int timeout, int(do_readchar)(struct serial *scb, int timeout))
Definition at line 395 of file ser-base.c.
References serial::bufcnt, serial::bufp, reschedule(), ser_base_read_error_fd(), SERIAL_EOF, SERIAL_ERROR, and SERIAL_TIMEOUT.
Referenced by hardwire_readchar(), and ser_base_readchar().
static void push_event (void * context) [static]
Definition at line 193 of file ser-base.c.
References serial::async_state, NOTHING_SCHEDULED, and run_async_handler_and_reschedule().
static void reschedule (struct serial * scb) [static]
Definition at line 67 of file ser-base.c.
References add_file_handler(), serial::async_state, serial::bufcnt, create_timer(), delete_file_handler(), delete_timer(), serial::fd, fd_event, FD_SCHEDULED, fprintf_unfiltered(), gdb_stdlog, NOTHING_SCHEDULED, push_event, serial_debug_p(), and serial_is_async_p().
Referenced by generic_readchar(), run_async_handler_and_reschedule(), and ser_base_async().
static void run_async_handler_and_reschedule (struct serial * scb) [static]
Definition at line 130 of file ser-base.c.
References serial::async_context, serial::async_handler, reschedule(), serial_is_open(), serial_ref(), and serial_unref().
Referenced by fd_event(), and push_event().
void ser_base_async (struct serial * scb, int async_p)
Definition at line 549 of file ser-base.c.
References serial::async_state, delete_file_handler(), delete_timer(), serial::fd, FD_SCHEDULED, fprintf_unfiltered(), gdb_stdlog, NOTHING_SCHEDULED, reschedule(), and serial_debug_p().
Referenced by _initialize_ser_windows().
serial_ttystate ser_base_copy_tty_state (struct serial * scb, serial_ttystate ttystate)
Definition at line 505 of file ser-base.c.
References XMALLOC.
Referenced by _initialize_ser_windows().
int ser_base_drain_output (struct serial * scb)
Definition at line 486 of file ser-base.c.
Referenced by _initialize_ser_windows().
int ser_base_flush_input (struct serial * scb)
Definition at line 467 of file ser-base.c.
References serial::buf, serial::bufcnt, serial::bufp, and SERIAL_ERROR.
Referenced by _initialize_ser_windows(), and hardwire_flush_input().
int ser_base_flush_output (struct serial * scb)
Definition at line 461 of file ser-base.c.
Referenced by _initialize_ser_windows().
serial_ttystate ser_base_get_tty_state (struct serial * scb)
Definition at line 498 of file ser-base.c.
References XMALLOC.
Referenced by _initialize_ser_windows().
int ser_base_noflush_set_tty_state (struct serial * scb, serial_ttystate new_ttystate, serial_ttystate old_ttystate)
Definition at line 518 of file ser-base.c.
Referenced by _initialize_ser_windows().
void ser_base_print_tty_state (struct serial * scb, serial_ttystate ttystate, struct ui_file * stream)
Definition at line 526 of file ser-base.c.
Referenced by _initialize_ser_windows().
void ser_base_raw (struct serial * scb)
Definition at line 492 of file ser-base.c.
Referenced by _initialize_ser_windows().
static void ser_base_read_error_fd (struct serial * scb, int close_fd) [static]
Definition at line 248 of file ser-base.c.
References serial_ops::avail, serial::error_fd, fputs_unfiltered(), gdb_assert, GDB_MI_MSG_WIDTH, gdb_stderr, serial::ops, read(), and strstr().
Referenced by do_ser_base_readchar(), and generic_readchar().
int ser_base_readchar (struct serial * scb, int timeout)
Definition at line 437 of file ser-base.c.
References do_ser_base_readchar(), and generic_readchar().
Referenced by _initialize_ser_windows().
int ser_base_send_break (struct serial * scb)
Definition at line 480 of file ser-base.c.
Referenced by _initialize_ser_windows().
int ser_base_set_tty_state (struct serial * scb, serial_ttystate ttystate)
Definition at line 512 of file ser-base.c.
Referenced by _initialize_ser_windows().
int ser_base_setbaudrate (struct serial * scb, int rate)
Definition at line 535 of file ser-base.c.
Referenced by _initialize_ser_windows().
int ser_base_setstopbits (struct serial * scb, int num)
Definition at line 541 of file ser-base.c.
Referenced by _initialize_ser_windows().
static int ser_base_wait_for (struct serial * scb, int timeout) [static]
Definition at line 205 of file ser-base.c.
References serial::fd, gdb_select(), SERIAL_ERROR, SERIAL_TIMEOUT, and timeout.
Referenced by do_ser_base_readchar().
int ser_base_write (struct serial * scb, const void * buf, size_t count)
Definition at line 443 of file ser-base.c.
References serial::ops, and serial_ops::write_prim.
Referenced by _initialize_ser_windows().
Variable Documentation
handler_func fd_event [static]
Definition at line 35 of file ser-base.c.
Referenced by reschedule().
timer_handler_func push_event [static]
Definition at line 34 of file ser-base.c.
Referenced by reschedule().