GDB (xrefs): /home/stan/gdb/src/gdb/ser-tcp.c File Reference
/home/stan/gdb/src/gdb/ser-tcp.c File Reference
#include "defs.h"
#include "serial.h"
#include "ser-base.h"
#include "ser-tcp.h"
#include "gdbcmd.h"
#include "cli/cli-decode.h"
#include "cli/cli-setshow.h"
#include "filestuff.h"
#include <sys/types.h>
#include <sys/time.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <netdb.h>
#include <sys/socket.h>
#include <netinet/tcp.h>
#include <signal.h>
#include "gdb_string.h"
#include "gdb_select.h"
Defines
#define POLL_INTERVAL 5
Typedefs
typedef int socklen_t
Functions
void _initialize_ser_tcp (void)
static int wait_for_connect (struct serial *scb, unsigned int *polls)
int net_open (struct serial *scb, const char *name)
void net_close (struct serial *scb)
int net_read_prim (struct serial *scb, size_t count)
int net_write_prim (struct serial *scb, const void *buf, size_t count)
int ser_tcp_send_break (struct serial *scb)
static void set_tcp_cmd (char *args, int from_tty)
static void show_tcp_cmd (char *args, int from_tty)
Variables
static struct cmd_list_element * tcp_set_cmdlist
static struct cmd_list_element * tcp_show_cmdlist
static int tcp_auto_retry = 1
static unsigned int tcp_retry_limit = 15
Define Documentation
#define POLL_INTERVAL 5
Definition at line 80 of file ser-tcp.c.
Referenced by wait_for_connect().
Typedef Documentation
typedef int socklen_t
Definition at line 60 of file ser-tcp.c.
Function Documentation
void _initialize_ser_tcp (void)
void net_close (struct serial * scb)
Definition at line 330 of file ser-tcp.c.
References serial::fd.
Referenced by net_open(), and net_windows_close().
int net_open (struct serial * scb, const char * name)
Definition at line 157 of file ser-tcp.c.
References _, error(), serial::fd, fprintf_unfiltered(), gdb_socket_cloexec(), gdb_stderr, len, memcpy(), min, net_close(), strchr(), tcp_auto_retry, and wait_for_connect().
Referenced by net_windows_open().
int net_read_prim (struct serial * scb, size_t count)
Definition at line 340 of file ser-tcp.c.
References serial::buf, and serial::fd.
Referenced by _initialize_ser_windows().
int net_write_prim (struct serial * scb, const void * buf, size_t count)
Definition at line 349 of file ser-tcp.c.
References serial::fd.
Referenced by _initialize_ser_windows().
int ser_tcp_send_break (struct serial * scb)
Definition at line 355 of file ser-tcp.c.
References serial_write().
Referenced by _initialize_ser_windows().
static void set_tcp_cmd (char * args, int from_tty) [static]
Definition at line 364 of file ser-tcp.c.
References gdb_stdout, and help_list().
static void show_tcp_cmd (char * args, int from_tty) [static]
Definition at line 370 of file ser-tcp.c.
References gdb_stdout, and help_list().
static int wait_for_connect (struct serial * scb, unsigned int * polls) [static]
Definition at line 87 of file ser-tcp.c.
References deprecated_ui_loop_hook, serial::fd, gdb_select(), POLL_INTERVAL, and tcp_retry_limit.
Referenced by net_open().
Variable Documentation
int tcp_auto_retry = 1 [static]
Definition at line 72 of file ser-tcp.c.
Referenced by net_open().
unsigned int tcp_retry_limit = 15 [static]
Definition at line 76 of file ser-tcp.c.
Referenced by wait_for_connect().
struct cmd_list_element* tcp_set_cmdlist [static]
Definition at line 67 of file ser-tcp.c.
struct cmd_list_element* tcp_show_cmdlist [static]
Definition at line 68 of file ser-tcp.c.