GDB (xrefs): /home/stan/gdb/src/gdb/ser-unix.c File Reference
/home/stan/gdb/src/gdb/ser-unix.c File Reference
#include "defs.h"
#include "serial.h"
#include "ser-base.h"
#include "ser-unix.h"
#include <fcntl.h>
#include <sys/types.h>
#include "terminal.h"
#include <sys/socket.h>
#include <sys/time.h>
#include "gdb_select.h"
#include "gdb_string.h"
#include "gdbcmd.h"
#include "filestuff.h"
Defines
#define B19200 EXTA
#define B38400 EXTB
Functions
static int hardwire_open (struct serial *scb, const char *name)
static void hardwire_raw (struct serial *scb)
static int wait_for (struct serial *scb, int timeout)
static int hardwire_readchar (struct serial *scb, int timeout)
static int do_hardwire_readchar (struct serial *scb, int timeout)
static int rate_to_code (int rate)
static int hardwire_setbaudrate (struct serial *scb, int rate)
static void hardwire_close (struct serial *scb)
static int get_tty_state (struct serial *scb, struct hardwire_ttystate *state)
static int set_tty_state (struct serial *scb, struct hardwire_ttystate *state)
static serial_ttystate hardwire_get_tty_state (struct serial *scb)
static int hardwire_set_tty_state (struct serial *scb, serial_ttystate state)
static int hardwire_noflush_set_tty_state (struct serial *, serial_ttystate, serial_ttystate)
static void hardwire_print_tty_state (struct serial *, serial_ttystate, struct ui_file *)
static int hardwire_drain_output (struct serial *)
static int hardwire_flush_output (struct serial *)
static int hardwire_flush_input (struct serial *)
static int hardwire_send_break (struct serial *)
static int hardwire_setstopbits (struct serial *, int)
void _initialize_ser_hardwire (void)
static serial_ttystate hardwire_copy_tty_state (struct serial *scb, serial_ttystate ttystate)
int ser_unix_read_prim (struct serial *scb, size_t count)
int ser_unix_write_prim (struct serial *scb, const void *buf, size_t len)
Variables
struct {
int rate
int code
} baudtab []
Define Documentation
#define B19200 EXTA
Definition at line 671 of file ser-unix.c.
#define B38400 EXTB
Definition at line 675 of file ser-unix.c.
Function Documentation
void _initialize_ser_hardwire (void)
static int do_hardwire_readchar (struct serial * scb, int timeout) [static]
Definition at line 594 of file ser-unix.c.
References serial::buf, serial::bufcnt, serial::bufp, deprecated_ui_loop_hook, serial::fd, read(), SERIAL_ERROR, SERIAL_TIMEOUT, exsummary::status, serial::timeout_remaining, and wait_for().
Referenced by hardwire_readchar().
static int get_tty_state (struct serial * scb, struct hardwire_ttystate * state) [static]
Definition at line 119 of file ser-unix.c.
References serial::fd.
Referenced by hardwire_drain_output(), hardwire_get_tty_state(), hardwire_raw(), hardwire_setbaudrate(), hardwire_setstopbits(), and wait_for().
static void hardwire_close (struct serial * scb) [static]
Definition at line 898 of file ser-unix.c.
References serial::fd.
static serial_ttystate hardwire_copy_tty_state (struct serial * scb, serial_ttystate ttystate) [static]
Definition at line 195 of file ser-unix.c.
References xmalloc().
static int hardwire_drain_output (struct serial * scb) [static]
Definition at line 308 of file ser-unix.c.
References serial::fd, and get_tty_state().
static int hardwire_flush_input (struct serial * scb) [static]
Definition at line 355 of file ser-unix.c.
References serial::fd, and ser_base_flush_input().
static int hardwire_flush_output (struct serial * scb) [static]
Definition at line 338 of file ser-unix.c.
References serial::fd.
static serial_ttystate hardwire_get_tty_state (struct serial * scb) [static]
Definition at line 179 of file ser-unix.c.
References get_tty_state(), xfree(), and xmalloc().
static int hardwire_noflush_set_tty_state (struct serial * scb, serial_ttystate new_ttystate, serial_ttystate old_ttystate) [static]
Definition at line 216 of file ser-unix.c.
References set_tty_state().
static int hardwire_open (struct serial * scb, const char * name) [static]
Definition at line 109 of file ser-unix.c.
References serial::fd, and gdb_open_cloexec().
static void hardwire_print_tty_state (struct serial * scb, serial_ttystate ttystate, struct ui_file * stream) [static]
Definition at line 249 of file ser-unix.c.
References fprintf_filtered(), and int.
static void hardwire_raw (struct serial * scb) [static]
Definition at line 401 of file ser-unix.c.
References serial::current_timeout, fprintf_unfiltered(), gdb_stderr, get_tty_state(), safe_strerror(), and set_tty_state().
static int hardwire_readchar (struct serial * scb, int timeout) [static]
Definition at line 664 of file ser-unix.c.
References do_hardwire_readchar(), and generic_readchar().
static int hardwire_send_break (struct serial * scb) [static]
Definition at line 374 of file ser-unix.c.
References serial::fd, gdb_usleep(), and exsummary::status.
static int hardwire_set_tty_state (struct serial * scb, serial_ttystate state) [static]
Definition at line 206 of file ser-unix.c.
References set_tty_state().
static int hardwire_setbaudrate (struct serial * scb, int rate) [static]
Definition at line 816 of file ser-unix.c.
References get_tty_state(), rate_to_code(), and set_tty_state().
static int hardwire_setstopbits (struct serial * scb, int num) [static]
Definition at line 855 of file ser-unix.c.
References get_tty_state(), SERIAL_1_AND_A_HALF_STOPBITS, SERIAL_1_STOPBITS, SERIAL_2_STOPBITS, and set_tty_state().
static int rate_to_code (int rate) [static]
Definition at line 779 of file ser-unix.c.
References _, baudtab, and warning().
Referenced by hardwire_setbaudrate().
int ser_unix_read_prim (struct serial * scb, size_t count)
Definition at line 956 of file ser-unix.c.
References serial::buf, serial::fd, read(), and exsummary::status.
int ser_unix_write_prim (struct serial * scb, const void * buf, size_t len)
Definition at line 970 of file ser-unix.c.
References serial::fd, and serial_ops::write.
static int set_tty_state (struct serial * scb, struct hardwire_ttystate * state) [static]
Definition at line 149 of file ser-unix.c.
References serial::fd.
Referenced by hardwire_noflush_set_tty_state(), hardwire_raw(), hardwire_set_tty_state(), hardwire_setbaudrate(), hardwire_setstopbits(), and wait_for().
static int wait_for (struct serial * scb, int timeout) [static]
Definition at line 470 of file ser-unix.c.
References serial::current_timeout, serial::fd, fprintf_unfiltered(), gdb_select(), gdb_stderr, get_tty_state(), safe_strerror(), SERIAL_ERROR, SERIAL_TIMEOUT, set_tty_state(), timeout, and serial::timeout_remaining.
Referenced by do_hardwire_readchar().
Variable Documentation
struct { ... } baudtab[] [static]
Referenced by rate_to_code().
int code
Definition at line 684 of file ser-unix.c.
Referenced by aarch64_return_in_memory(), alpha_return_value(), alphafbsd_return_in_memory(), amd64_classify(), apropos_command(), arch_type(), arm_return_in_memory(), c_print_type(), compile_rx_or_error(), darwin_encode_reply(), evaluate_subexp_standard(), f_print_type(), fixed_type_info(), gdbpy_initialize_breakpoints(), gdbpy_initialize_types(), handle_exception(), hppa64_convert_code_addr_to_fptr(), i386_reg_struct_return_p(), i386_return_value(), init_type(), is_integer_like(), is_pointer_like(), is_struct_like(), lm32_return_value(), m32c_decode_sd23(), m32c_decode_srcdest4(), m32c_reg_arg_type(), m32c_return_by_passed_buf(), m68k_reg_struct_return_p(), m68k_return_value(), m68k_svr4_return_value(), pascal_print_type(), read_base_type(), read_sun_builtin_type(), read_type(), S_exception_raise_request(), sparc32_struct_return_from_sym(), struct_return_convention(), unpack_double(), unpack_long(), value_from_double(), and xtensa_window_interrupt_insn().
int rate
Definition at line 683 of file ser-unix.c.
Referenced by dos_setbaudrate(), print_transfer_performance(), and ser_windows_setbaudrate().