GDB (xrefs): /home/stan/gdb/src/gdb/ser-tcp.h File Reference
/home/stan/gdb/src/gdb/ser-tcp.h File Reference
Functions
int net_open (struct serial *scb, const char *name)
void net_close (struct serial *scb)
int net_read_prim (struct serial *scb, size_t count)
int net_write_prim (struct serial *scb, const void *buf, size_t count)
int ser_tcp_send_break (struct serial *scb)
Function Documentation
void net_close (struct serial * scb)
Definition at line 330 of file ser-tcp.c.
References serial::fd.
Referenced by net_open(), and net_windows_close().
int net_open (struct serial * scb, const char * name)
Definition at line 157 of file ser-tcp.c.
References _, error(), serial::fd, fprintf_unfiltered(), gdb_socket_cloexec(), gdb_stderr, len, memcpy(), min, net_close(), strchr(), tcp_auto_retry, and wait_for_connect().
Referenced by net_windows_open().
int net_read_prim (struct serial * scb, size_t count)
Definition at line 340 of file ser-tcp.c.
References serial::buf, and serial::fd.
Referenced by _initialize_ser_windows().
int net_write_prim (struct serial * scb, const void * buf, size_t count)
Definition at line 349 of file ser-tcp.c.
References serial::fd.
Referenced by _initialize_ser_windows().
int ser_tcp_send_break (struct serial * scb)
Definition at line 355 of file ser-tcp.c.
References serial_write().
Referenced by _initialize_ser_windows().