GDB (xrefs): /home/stan/gdb/src/gdb/serial.h File Reference
/home/stan/gdb/src/gdb/serial.h File Reference
Classes
struct serial
struct serial_ops
Defines
#define SERIAL_1_STOPBITS 1
#define SERIAL_1_AND_A_HALF_STOPBITS 2 /* 1.5 bits, snicker... */
#define SERIAL_2_STOPBITS 3
Typedefs
typedef void * serial_ttystate
typedef void(serial_event_ftype)(struct serial *scb, void *context)
Enumerations
enum serial_rc { SERIAL_ERROR = -1, SERIAL_TIMEOUT = -2, SERIAL_EOF = -3 }
Functions
struct serial * serial_open (const char *name)
int serial_is_open (struct serial *scb)
struct serial * serial_for_fd (int fd)
struct serial * serial_fdopen (const int fd)
void serial_close (struct serial *scb)
void serial_ref (struct serial *scb)
void serial_unref (struct serial *scb)
int gdb_pipe (int fildes[2])
int serial_pipe (struct serial *scbs[2])
void serial_un_fdopen (struct serial *scb)
int serial_readchar (struct serial *scb, int timeout)
int serial_write (struct serial *scb, const void *buf, size_t count)
void serial_printf (struct serial *desc, const char *,...) ATTRIBUTE_PRINTF(2
void int serial_drain_output (struct serial *)
int serial_flush_output (struct serial *)
int serial_flush_input (struct serial *)
int serial_send_break (struct serial *scb)
void serial_raw (struct serial *scb)
serial_ttystate serial_get_tty_state (struct serial *scb)
serial_ttystate serial_copy_tty_state (struct serial *scb, serial_ttystate ttystate)
int serial_set_tty_state (struct serial *scb, serial_ttystate ttystate)
void serial_print_tty_state (struct serial *scb, serial_ttystate ttystate, struct ui_file *)
int serial_noflush_set_tty_state (struct serial *scb, serial_ttystate new_ttystate, serial_ttystate old_ttystate)
int serial_setbaudrate (struct serial *scb, int rate)
int serial_setstopbits (struct serial *scb, int num)
int serial_can_async_p (struct serial *scb)
int serial_is_async_p (struct serial *scb)
void serial_async (struct serial *scb, serial_event_ftype *handler, void *context)
void serial_debug (struct serial *scb, int debug_p)
int serial_debug_p (struct serial *scb)
void serial_add_interface (struct serial_ops *optable)
void serial_log_command (const char *)
Define Documentation
#define SERIAL_1_AND_A_HALF_STOPBITS 2 /* 1.5 bits, snicker... */
Definition at line 184 of file serial.h.
Referenced by dos_setstopbits(), hardwire_setstopbits(), and ser_windows_setstopbits().
#define SERIAL_1_STOPBITS 1
Definition at line 183 of file serial.h.
Referenced by _initialize_dink32_rom(), dos_setstopbits(), hardwire_setstopbits(), init_dbug_cmds(), init_m32r_cmds(), init_mon2000_cmds(), init_picobug_cmds(), init_ppc_cmds(), and ser_windows_setstopbits().
#define SERIAL_2_STOPBITS 3
Definition at line 185 of file serial.h.
Referenced by dos_setstopbits(), hardwire_setstopbits(), and ser_windows_setstopbits().
Typedef Documentation
typedef void(serial_event_ftype)(struct serial *scb, void *context)
Definition at line 203 of file serial.h.
typedef void* serial_ttystate
Definition at line 27 of file serial.h.
Enumeration Type Documentation
enum serial_rc
Enumerator:
SERIAL_ERROR
SERIAL_TIMEOUT
SERIAL_EOF
Definition at line 94 of file serial.h.
Function Documentation
int gdb_pipe (int fildes[2])
Definition at line 876 of file ser-go32.c.
References gdb_socketpair_cloexec().
Referenced by serial_pipe().
void serial_add_interface (struct serial_ops * optable)
Definition at line 159 of file serial.c.
References serial_ops::next, and serial_ops_list.
Referenced by _initialize_ser_dos(), and _initialize_ser_windows().
void serial_async (struct serial * scb, serial_event_ftype * handler, void * context)
Definition at line 538 of file serial.c.
References serial_ops::async, serial::async_context, serial::async_handler, and serial::ops.
Referenced by do_serial_close(), and remote_async().
int serial_can_async_p (struct serial * scb)
Definition at line 526 of file serial.c.
References serial_ops::async, and serial::ops.
Referenced by remote_can_async_p().
void serial_close (struct serial * scb)
Definition at line 338 of file serial.c.
References do_serial_close().
Referenced by close_ports(), m32r_close(), monitor_close(), monitor_open(), remote_close(), and remote_open_1().
serial_ttystate serial_copy_tty_state (struct serial * scb, serial_ttystate ttystate)
Definition at line 486 of file serial.c.
References serial_ops::copy_tty_state, and serial::ops.
Referenced by copy_terminal_info(), and terminal_init_inferior_with_pgrp().
void serial_debug (struct serial * scb, int debug_p)
Definition at line 552 of file serial.c.
References serial::debug_p.
int serial_debug_p (struct serial * scb)
Definition at line 558 of file serial.c.
References serial::debug_p, and global_serial_debug_p.
Referenced by reschedule(), ser_base_async(), serial_readchar(), and serial_write().
void int serial_drain_output (struct serial *)
Definition at line 447 of file serial.c.
References serial_ops::drain_output, and serial::ops.
Referenced by print_flush().
struct serial* serial_fdopen (const int fd) [read]
Definition at line 289 of file serial.c.
References serial_fdopen_ops().
Referenced by initialize_stdin_serial(), and print_flush().
int serial_flush_input (struct serial *)
Definition at line 459 of file serial.c.
References serial_ops::flush_input, and serial::ops.
Referenced by load_srec(), monitor_open(), and remote_open_1().
int serial_flush_output (struct serial *)
Definition at line 453 of file serial.c.
References serial_ops::flush_output, and serial::ops.
struct serial* serial_for_fd (int fd) [read]
Definition at line 169 of file serial.c.
References serial::fd, and serial::next.
Referenced by gdb_select().
serial_ttystate serial_get_tty_state (struct serial * scb)
Definition at line 480 of file serial.c.
References serial_ops::get_tty_state, and serial::ops.
Referenced by gdb_has_a_terminal(), terminal_ours_1(), and terminal_save_ours().
int serial_is_async_p (struct serial * scb)
Definition at line 532 of file serial.c.
References serial_ops::async, serial::async_handler, and serial::ops.
Referenced by remote_is_async_p(), reschedule(), and serial_readchar().
int serial_is_open (struct serial * scb)
Definition at line 350 of file serial.c.
References serial::bufp.
Referenced by run_async_handler_and_reschedule().
void serial_log_command (const char *)
Definition at line 130 of file serial.c.
References fputs_unfiltered(), gdb_flush(), and serial_current_type.
Referenced by _initialize_remote_mips(), init_base_monitor_ops(), init_m32r_ops(), and init_remote_ops().
int serial_noflush_set_tty_state (struct serial * scb, serial_ttystate new_ttystate, serial_ttystate old_ttystate)
Definition at line 506 of file serial.c.
References serial_ops::noflush_set_tty_state, and serial::ops.
Referenced by terminal_ours_1().
struct serial* serial_open (const char * name) [read]
Definition at line 183 of file serial.c.
References serial::async_context, serial::async_handler, serial::async_state, serial::buf, serial::bufcnt, serial::bufp, serial::debug_p, serial::error_fd, gdb_fopen(), name, serial::name, serial::next, serial_ops::open, serial::ops, perror_with_name(), serial::refcnt, scb_base, serial_interface_lookup(), serial_logfile, skip_spaces_const(), strchr(), xfree(), and XMALLOC.
Referenced by m32r_open(), monitor_open(), and remote_serial_open().
int serial_pipe (struct serial * scbs[2])
Definition at line 585 of file serial.c.
References gdb_pipe(), serial_fdopen_ops(), and serial_interface_lookup().
void serial_print_tty_state (struct serial * scb, serial_ttystate ttystate, struct ui_file *)
Definition at line 498 of file serial.c.
References serial::ops, and serial_ops::print_tty_state.
Referenced by child_terminal_info().
void serial_printf (struct serial * desc, const char * , ...)
void serial_raw (struct serial * scb)
Definition at line 474 of file serial.c.
References serial_ops::go_raw, and serial::ops.
Referenced by monitor_open(), and remote_open_1().
int serial_readchar (struct serial * scb, int timeout)
Definition at line 370 of file serial.c.
References _, fprintf_unfiltered(), gdb_flush(), gdb_stdlog, internal_error(), serial::ops, serial_ops::readchar, serial_debug_p(), serial_is_async_p(), and serial_logchar().
Referenced by get_ack(), m32r_insert_breakpoint(), m32r_wait(), m32r_xfer_memory(), mips_expect_timeout(), mips_readchar(), monitor_readchar(), pmon_check_ack(), readchar(), recv_data(), and sdistatus_command().
void serial_ref (struct serial * scb)
Definition at line 356 of file serial.c.
References serial::refcnt.
Referenced by run_async_handler_and_reschedule().
int serial_send_break (struct serial * scb)
Definition at line 465 of file serial.c.
References serial::ops, serial_ops::send_break, SERIAL_BREAK, and serial_logchar().
Referenced by mips_kill(), monitor_stop(), and send_interrupt_sequence().
int serial_set_tty_state (struct serial * scb, serial_ttystate ttystate)
Definition at line 492 of file serial.c.
References serial::ops, and serial_ops::set_tty_state.
Referenced by terminal_inferior().
int serial_setbaudrate (struct serial * scb, int rate)
Definition at line 514 of file serial.c.
References serial::ops, and serial_ops::setbaudrate.
Referenced by monitor_open(), and remote_open_1().
int serial_setstopbits (struct serial * scb, int num)
Definition at line 520 of file serial.c.
References serial::ops, and serial_ops::setstopbits.
Referenced by monitor_open().
void serial_un_fdopen (struct serial * scb)
Definition at line 344 of file serial.c.
References do_serial_close().
Referenced by print_flush().
void serial_unref (struct serial * scb)
Definition at line 362 of file serial.c.
References serial::refcnt, and xfree().
Referenced by do_serial_close(), and run_async_handler_and_reschedule().
int serial_write (struct serial * scb, const void * buf, size_t count)
Definition at line 401 of file serial.c.
References serial::buf, fprintf_unfiltered(), gdb_flush(), gdb_stdlog, serial::ops, serial_debug_p(), serial_logchar(), and serial_ops::write.
Referenced by load_srec(), m32r_insert_breakpoint(), m32r_wait(), m32r_xfer_memory(), mips_kill(), mips_receive_packet(), monitor_read_memory(), monitor_write(), pmon_download(), remote_serial_write(), remote_start_remote(), send_data(), send_srec(), ser_tcp_send_break(), and serial_printf().