GDB (xrefs): /home/stan/gdb/src/gdb/shnbsd-nat.c File Reference
/home/stan/gdb/src/gdb/shnbsd-nat.c File Reference
#include "defs.h"
#include "inferior.h"
#include <sys/types.h>
#include <sys/ptrace.h>
#include <machine/reg.h>
#include "sh-tdep.h"
#include "inf-ptrace.h"
#include "regcache.h"
Defines
#define GETREGS_SUPPLIES(gdbarch, regno)
#define SHNBSD_SIZEOF_GREGS (21 * 4)
Functions
static void shnbsd_fetch_inferior_registers (struct target_ops *ops, struct regcache *regcache, int regno)
static void shnbsd_store_inferior_registers (struct target_ops *ops, struct regcache *regcache, int regno)
void _initialize_shnbsd_nat (void)
Define Documentation
#define GETREGS_SUPPLIES (gdbarch, regno)
Value:
(((regno) >= R0_REGNUM && (regno) <= (R0_REGNUM + 15)) \
|| (regno) == gdbarch_pc_regnum (gdbarch) || (regno) == PR_REGNUM \
|| (regno) == MACH_REGNUM || (regno) == MACL_REGNUM \
|| (regno) == SR_REGNUM)
Definition at line 35 of file shnbsd-nat.c.
Referenced by shnbsd_fetch_inferior_registers(), and shnbsd_store_inferior_registers().
#define SHNBSD_SIZEOF_GREGS (21 * 4)
Definition at line 42 of file shnbsd-nat.c.
Referenced by shnbsd_fetch_inferior_registers(), and shnbsd_store_inferior_registers().
Function Documentation
void _initialize_shnbsd_nat (void)
Definition at line 94 of file shnbsd-nat.c.
References add_target(), inf_ptrace_target(), shnbsd_fetch_inferior_registers(), shnbsd_store_inferior_registers(), target_ops::to_fetch_registers, and target_ops::to_store_registers.
static void shnbsd_fetch_inferior_registers (struct target_ops * ops, struct regcache * regcache, int regno) [static]
Definition at line 45 of file shnbsd-nat.c.
References _, get_regcache_arch(), GETREGS_SUPPLIES, inferior_ptid, perror_with_name(), ptid_get_pid(), ptrace(), PTRACE_TYPE_ARG3, sh_corefile_gregset, sh_corefile_supply_regset(), and SHNBSD_SIZEOF_GREGS.
Referenced by _initialize_shnbsd_nat().
static void shnbsd_store_inferior_registers (struct target_ops * ops, struct regcache * regcache, int regno) [static]
Definition at line 66 of file shnbsd-nat.c.
References _, get_regcache_arch(), GETREGS_SUPPLIES, inferior_ptid, perror_with_name(), ptid_get_pid(), ptrace(), PTRACE_TYPE_ARG3, sh_corefile_collect_regset(), sh_corefile_gregset, and SHNBSD_SIZEOF_GREGS.
Referenced by _initialize_shnbsd_nat().