GDB (xrefs): /home/stan/gdb/src/gdb/shnbsd-tdep.c File Reference
/home/stan/gdb/src/gdb/shnbsd-tdep.c File Reference
#include "defs.h"
#include "gdbcore.h"
#include "regset.h"
#include "value.h"
#include "osabi.h"
#include "gdb_string.h"
#include "sh-tdep.h"
#include "solib-svr4.h"
Defines
#define GDB_OSABI_NETBSD_CORE GDB_OSABI_OPENBSD_ELF
Functions
static void shnbsd_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
static enum gdb_osabi shnbsd_core_osabi_sniffer (bfd *abfd)
void _initialize_shnbsd_tdep (void)
Variables
static struct sh_corefile_regmap regmap []
initialize_file_ftype _initialize_shnbsd_tdep
Define Documentation
#define GDB_OSABI_NETBSD_CORE GDB_OSABI_OPENBSD_ELF
Definition at line 77 of file shnbsd-tdep.c.
Referenced by shnbsd_core_osabi_sniffer().
Function Documentation
void _initialize_shnbsd_tdep (void)
Definition at line 92 of file shnbsd-tdep.c.
References _initialize_shnbsd_tdep, GDB_OSABI_NETBSD_ELF, GDB_OSABI_OPENBSD_ELF, gdbarch_register_osabi(), gdbarch_register_osabi_sniffer(), shnbsd_core_osabi_sniffer(), and shnbsd_init_abi().
static enum gdb_osabi shnbsd_core_osabi_sniffer (bfd * abfd) [static]
Definition at line 80 of file shnbsd-tdep.c.
References GDB_OSABI_NETBSD_CORE, and GDB_OSABI_UNKNOWN.
Referenced by _initialize_shnbsd_tdep().
static void shnbsd_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch) [static]
Definition at line 63 of file shnbsd-tdep.c.
References gdbarch_tdep::core_gregmap, gdbarch_tdep(), set_solib_svr4_fetch_link_map_offsets(), and svr4_ilp32_fetch_link_map_offsets().
Referenced by _initialize_shnbsd_tdep().
Variable Documentation
initialize_file_ftype _initialize_shnbsd_tdep
Referenced by _initialize_shnbsd_tdep(), and initialize_all_files().
struct sh_corefile_regmap regmap[] [static]
Initial value:
{
  {R0_REGNUM,      20 * 4},
  {R0_REGNUM + 1,  19 * 4},
  {R0_REGNUM + 2,  18 * 4},
  {R0_REGNUM + 3,  17 * 4},
  {R0_REGNUM + 4,  16 * 4},
  {R0_REGNUM + 5,  15 * 4},
  {R0_REGNUM + 6,  14 * 4},
  {R0_REGNUM + 7,  13 * 4},
  {R0_REGNUM + 8,  12 * 4},
  {R0_REGNUM + 9,  11 * 4},
  {R0_REGNUM + 10, 10 * 4},
  {R0_REGNUM + 11,  9 * 4},
  {R0_REGNUM + 12,  8 * 4},
  {R0_REGNUM + 13,  7 * 4},
  {R0_REGNUM + 14,  6 * 4},
  {R0_REGNUM + 15,  5 * 4},
  {PC_REGNUM,       0 * 4},
  {SR_REGNUM,       1 * 4},
  {PR_REGNUM,       2 * 4},
  {MACH_REGNUM,     3 * 4},
  {MACL_REGNUM,     4 * 4},
  {-1 , 0}
}
Definition at line 35 of file shnbsd-tdep.c.