GDB (xrefs): /home/stan/gdb/src/gdb/common/signals.c File Reference
/home/stan/gdb/src/gdb/common/signals.c File Reference
#include "defs.h"
#include "gdb_string.h"
#include "gdb_signals.h"
#include "gdb/signals.def"
Defines
#define SET(symbol, constant, name, string) { name, string },
Functions
const char * gdb_signal_to_string (enum gdb_signal sig)
const char * gdb_signal_to_name (enum gdb_signal sig)
enum gdb_signal gdb_signal_from_name (const char *name)
enum gdb_signal gdb_signal_from_host (int hostsig)
static int do_gdb_signal_to_host (enum gdb_signal oursig, int *oursig_ok)
int gdb_signal_to_host_p (enum gdb_signal oursig)
int gdb_signal_to_host (enum gdb_signal oursig)
Variables
struct {
const char * name
const char * string
} signals []
Define Documentation
#define SET (symbol, constant, name, string) { name, string },
Function Documentation
static int do_gdb_signal_to_host (enum gdb_signal oursig, int * oursig_ok) [static]
Definition at line 364 of file signals.c.
References int, REALTIME_HI, and REALTIME_LO.
Referenced by gdb_signal_to_host(), and gdb_signal_to_host_p().
enum gdb_signal gdb_signal_from_host (int hostsig)
Definition at line 113 of file signals.c.
References _, error(), int, REALTIME_HI, and REALTIME_LO.
Referenced by check_thread_signals(), core_open(), darwin_decode_message(), get_pending_status(), handle_output_debug_string(), linux_nat_attach(), linux_nat_pass_signals(), linux_nat_resume(), linux_nat_wait_1(), proc_set_current_signal(), procfs_pass_signals(), procfs_wait(), S_exception_raise_request(), and store_waitstatus().
enum gdb_signal gdb_signal_from_name (const char * name)
Definition at line 88 of file signals.c.
References signals.
Referenced by handle_command(), nto_initialize_signals(), signal_command(), signals_info(), VEC(), and xdb_handle_command().
int gdb_signal_to_host (enum gdb_signal oursig)
Definition at line 637 of file signals.c.
References _, do_gdb_signal_to_host(), gdb_signal_to_name(), and warning().
Referenced by aix_thread_resume(), darwin_resume(), get_pending_status(), i386_linux_resume(), i386fbsd_resume(), inf_ptrace_resume(), inf_signal(), linux_collect_thread_registers(), linux_nat_collect_thread_registers(), linux_nat_resume(), linux_nat_wait_1(), procfs_resume(), and resume_lwp().
int gdb_signal_to_host_p (enum gdb_signal oursig)
Definition at line 629 of file signals.c.
References do_gdb_signal_to_host().
const char* gdb_signal_to_name (enum gdb_signal sig)
Definition at line 75 of file signals.c.
References GDB_SIGNAL_FIRST, name, and signals.
Referenced by core_open(), create_signal_event_object(), darwin_decode_message(), gdb_signal_to_host(), gdbtk_annotate_signal(), gnu_resume(), go32_resume(), handle_command(), linux_nat_attach(), print_signal_exited_reason(), print_signal_received_reason(), program_info(), remote_wait_as(), sig_print_info(), signal_command(), signal_to_name_or_int(), startup_inferior(), target_pass_signals(), target_program_signals(), target_resume(), and target_waitstatus_to_string().
const char* gdb_signal_to_string (enum gdb_signal sig)
Definition at line 65 of file signals.c.
References GDB_SIGNAL_FIRST, and signals.
Referenced by core_open(), gdbtk_annotate_signal(), get_pending_status(), linux_nat_attach(), print_signal_exited_reason(), print_signal_received_reason(), program_info(), sig_print_info(), and startup_inferior().
Variable Documentation
const char* name
Definition at line 53 of file signals.c.
struct { ... } signals[] [static]
Referenced by gdb_signal_from_name(), gdb_signal_to_name(), gdb_signal_to_string(), procfs_init_inferior(), and procfs_pass_signals().
const char* string
Definition at line 54 of file signals.c.
Referenced by append_string_as_wide(), define_symbol(), dict_hash(), init_number_or_range(), linespec_parse_line_offset(), macho_sym_hash_newfunc(), mips_expect_timeout(), monitor_expect(), msymbol_hash(), msymbol_hash_iw(), parse_format_string(), pstring(), set_parameter_value(), substitute_path_component(), symbol_reference_defined(), tui_make_status_line(), tui_show_locator_content(), unexpected_linespec_error(), unicode_to_encoded_string(), variable_type(), and vwarning().