GDB (xrefs): /home/stan/gdb/src/gdb/skip.h File Reference
/home/stan/gdb/src/gdb/skip.h File Reference
Functions
int function_name_is_marked_for_skip (const char *function_name, const struct symtab_and_line *function_sal)
Function Documentation
int function_name_is_marked_for_skip (const char * function_name, const struct symtab_and_line * function_sal)
Definition at line 335 of file skip.c.
References ALL_SKIPLIST_ENTRIES, basenames_may_differ, compare_filenames_for_search(), skiplist_entry::enabled, skiplist_entry::filename, symtab::filename, skiplist_entry::function_name, strcmp_iw(), symtab_and_line::symtab, and symtab_to_fullname().
Referenced by handle_inferior_event().