GDB (xrefs): /home/stan/gdb/src/gdb/skip.c File Reference
/home/stan/gdb/src/gdb/skip.c File Reference
#include "defs.h"
#include "skip.h"
#include "value.h"
#include "valprint.h"
#include "ui-out.h"
#include "gdb_string.h"
#include "symtab.h"
#include "gdbcmd.h"
#include "command.h"
#include "completer.h"
#include "stack.h"
#include "cli/cli-utils.h"
#include "arch-utils.h"
#include "linespec.h"
#include "objfiles.h"
#include "exceptions.h"
#include "breakpoint.h"
#include "source.h"
#include "filenames.h"
Classes
struct skiplist_entry
Defines
#define ALL_SKIPLIST_ENTRIES(E) for (E = skiplist_entry_chain; E; E = E->next)
#define ALL_SKIPLIST_ENTRIES_SAFE(E, TMP)
Functions
static void add_skiplist_entry (struct skiplist_entry *e)
static void skip_function (const char *name)
static void skip_file_command (char *arg, int from_tty)
static void skip_function_command (char *arg, int from_tty)
static void skip_info (char *arg, int from_tty)
static void skip_enable_command (char *arg, int from_tty)
static void skip_disable_command (char *arg, int from_tty)
static void skip_delete_command (char *arg, int from_tty)
int function_name_is_marked_for_skip (const char *function_name, const struct symtab_and_line *function_sal)
void _initialize_step_skip (void)
Variables
static struct skiplist_entry * skiplist_entry_chain
static int skiplist_entry_count
initialize_file_ftype _initialize_step_skip
Define Documentation
#define ALL_SKIPLIST_ENTRIES (E) for (E = skiplist_entry_chain; E; E = E->next)
Definition at line 62 of file skip.c.
Referenced by function_name_is_marked_for_skip(), skip_disable_command(), skip_enable_command(), and skip_info().
#define ALL_SKIPLIST_ENTRIES_SAFE (E, TMP)
Value:
for (E = skiplist_entry_chain;         \
       E ? (TMP = E->next, 1) : 0;       \
       E = TMP)
Definition at line 65 of file skip.c.
Referenced by skip_delete_command().
Function Documentation
void _initialize_step_skip (void)
Definition at line 393 of file skip.c.
References _, _initialize_step_skip, add_cmd(), add_info(), add_prefix_cmd(), class_breakpoint, cmdlist, skip_delete_command(), skip_disable_command(), skip_enable_command(), skip_file_command(), skip_function_command(), skip_info(), and skiplist_entry_count.
static void add_skiplist_entry (struct skiplist_entry * e) [static]
Definition at line 311 of file skip.c.
References skiplist_entry::next, skiplist_entry::number, skiplist_entry_chain, and skiplist_entry_count.
Referenced by skip_file_command(), and skip_function().
int function_name_is_marked_for_skip (const char * function_name, const struct symtab_and_line * function_sal)
Definition at line 335 of file skip.c.
References ALL_SKIPLIST_ENTRIES, basenames_may_differ, compare_filenames_for_search(), skiplist_entry::enabled, skiplist_entry::filename, symtab::filename, skiplist_entry::function_name, strcmp_iw(), symtab_and_line::symtab, and symtab_to_fullname().
Referenced by handle_inferior_event().
static void skip_delete_command (char * arg, int from_tty) [static]
Definition at line 264 of file skip.c.
References _, ALL_SKIPLIST_ENTRIES_SAFE, error(), skiplist_entry::filename, skiplist_entry::function_name, skiplist_entry::next, skiplist_entry::number, number_is_in_list(), and xfree().
Referenced by _initialize_step_skip().
static void skip_disable_command (char * arg, int from_tty) [static]
Definition at line 247 of file skip.c.
References _, ALL_SKIPLIST_ENTRIES, skiplist_entry::enabled, error(), skiplist_entry::number, and number_is_in_list().
Referenced by _initialize_step_skip().
static void skip_enable_command (char * arg, int from_tty) [static]
Definition at line 230 of file skip.c.
References _, ALL_SKIPLIST_ENTRIES, skiplist_entry::enabled, error(), skiplist_entry::number, and number_is_in_list().
Referenced by _initialize_step_skip().
static void skip_file_command (char * arg, int from_tty) [static]
Definition at line 71 of file skip.c.
References _, add_skiplist_entry(), skiplist_entry::enabled, error(), skiplist_entry::filename, symtab::filename, fprintf_filtered(), gdb_stderr, get_last_displayed_symtab(), lookup_symtab(), nquery(), printf_filtered(), symtab_to_fullname(), and XZALLOC.
Referenced by _initialize_step_skip().
static void skip_function (const char * name) [static]
Definition at line 296 of file skip.c.
References _, add_skiplist_entry(), skiplist_entry::enabled, skiplist_entry::function_name, printf_filtered(), and XZALLOC.
Referenced by skip_function_command().
static void skip_function_command (char * arg, int from_tty) [static]
Definition at line 114 of file skip.c.
References _, error(), find_pc_partial_function(), fprintf_filtered(), gdb_stderr, get_current_arch(), get_last_displayed_addr(), last_displayed_sal_is_valid(), lookup_symbol(), name, nquery(), paddress(), skip_function(), and VAR_DOMAIN.
Referenced by _initialize_step_skip().
static void skip_info (char * arg, int from_tty) [static]
Definition at line 155 of file skip.c.
References _, ALL_SKIPLIST_ENTRIES, current_uiout, do_cleanups(), skiplist_entry::enabled, skiplist_entry::filename, skiplist_entry::function_name, get_user_print_options(), internal_error(), make_cleanup_ui_out_table_begin_end(), make_cleanup_ui_out_tuple_begin_end(), skiplist_entry::number, number_is_in_list(), QUIT, ui_left, ui_noalign, ui_out_field_int(), ui_out_field_string(), ui_out_message(), ui_out_table_body(), ui_out_table_header(), and ui_out_text().
Referenced by _initialize_step_skip().
Variable Documentation
initialize_file_ftype _initialize_step_skip
Referenced by _initialize_step_skip(), and initialize_all_files().
struct skiplist_entry* skiplist_entry_chain [static]
Definition at line 59 of file skip.c.
Referenced by add_skiplist_entry().
int skiplist_entry_count [static]
Definition at line 60 of file skip.c.
Referenced by _initialize_step_skip(), and add_skiplist_entry().