GDB (xrefs): /home/stan/gdb/src/gdb/sol2-tdep.c File Reference
/home/stan/gdb/src/gdb/sol2-tdep.c File Reference
#include "defs.h"
#include "frame.h"
#include "symtab.h"
#include "inferior.h"
#include "sol2-tdep.h"
Functions
CORE_ADDR sol2_skip_solib_resolver (struct gdbarch *gdbarch, CORE_ADDR pc)
char * sol2_core_pid_to_str (struct gdbarch *gdbarch, ptid_t ptid)
Function Documentation
char* sol2_core_pid_to_str (struct gdbarch * gdbarch, ptid_t ptid)
Definition at line 43 of file sol2-tdep.c.
References inferior::fake_pid_p, find_inferior_pid(), arm-linux::inf, normal_pid_to_str(), inferior::pid, ptid_get_lwp(), ptid_get_pid(), and xsnprintf().
Referenced by amd64_sol2_init_abi(), i386_sol2_init_abi(), sparc32_sol2_init_abi(), and sparc64_sol2_init_abi().
CORE_ADDR sol2_skip_solib_resolver (struct gdbarch * gdbarch, CORE_ADDR pc)
Definition at line 28 of file sol2-tdep.c.
References frame_unwind_caller_pc(), get_current_frame(), lookup_minimal_symbol(), and SYMBOL_VALUE_ADDRESS.
Referenced by amd64_sol2_init_abi(), i386_sol2_init_abi(), sparc32_sol2_init_abi(), and sparc64_sol2_init_abi().