GDB (xrefs): /home/stan/gdb/src/gdb/solib-aix.c File Reference
/home/stan/gdb/src/gdb/solib-aix.c File Reference
#include "defs.h"
#include "solib-aix.h"
#include "solist.h"
#include "inferior.h"
#include "gdb_bfd.h"
#include "gdbcore.h"
#include "objfiles.h"
#include "symtab.h"
#include "xcoffread.h"
#include "observer.h"
#include "gdbcmd.h"
Classes
struct lm_info
struct solib_aix_inferior_data
Typedefs
typedef struct lm_info * lm_info_p
Functions
DEF_VEC_P (lm_info_p)
static struct lm_info * solib_aix_new_lm_info (struct lm_info *info)
static void solib_aix_xfree_lm_info (struct lm_info *info)
static struct
solib_aix_inferior_data * get_solib_aix_inferior_data (struct inferior *inf)
static VEC (lm_info_p)
static void solib_aix_free_library_list (void *p)
static CORE_ADDR solib_aix_bss_data_overlap (bfd *abfd)
static void solib_aix_relocate_section_addresses (struct so_list *so, struct target_section *sec)
static void solib_aix_free_so (struct so_list *so)
static void solib_aix_clear_solib (void)
static struct section_offsets * solib_aix_get_section_offsets (struct objfile *objfile, struct lm_info *info)
static void solib_aix_solib_create_inferior_hook (int from_tty)
static void solib_aix_special_symbol_handling (void)
static struct so_list * solib_aix_current_sos (void)
static int solib_aix_open_symbol_file_object (void *from_ttyp)
static int solib_aix_in_dynsym_resolve_code (CORE_ADDR pc)
static bfd * solib_aix_bfd_open (char *pathname)
static struct obj_section * data_obj_section_from_objfile (struct objfile *objfile)
CORE_ADDR solib_aix_get_toc_value (CORE_ADDR pc)
static void solib_aix_normal_stop_observer (struct bpstats *unused_1, int unused_2)
static void show_solib_aix_debug (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
void _initialize_solib_aix (void)
Variables
static int solib_aix_debug
static struct inferior_data * solib_aix_inferior_data_handle
struct target_so_ops solib_aix_so_ops
initialize_file_ftype _initialize_solib_aix
Typedef Documentation
typedef struct lm_info* lm_info_p
Definition at line 61 of file solib-aix.c.
Function Documentation
void _initialize_solib_aix (void)
Definition at line 811 of file solib-aix.c.
References _, add_setshow_boolean_cmd(), target_so_ops::bfd_open, class_maintenance, target_so_ops::clear_solib, target_so_ops::current_sos, target_so_ops::free_so, target_so_ops::in_dynsym_resolve_code, observer_attach_normal_stop(), target_so_ops::open_symbol_file_object, target_so_ops::relocate_section_addresses, setdebuglist, show_solib_aix_debug(), showdebuglist, solib_aix_bfd_open(), solib_aix_clear_solib(), solib_aix_current_sos(), solib_aix_debug, solib_aix_free_so(), solib_aix_in_dynsym_resolve_code(), solib_aix_inferior_data_handle, solib_aix_normal_stop_observer(), solib_aix_open_symbol_file_object(), solib_aix_relocate_section_addresses(), solib_aix_so_ops, solib_aix_solib_create_inferior_hook(), solib_aix_special_symbol_handling(), target_so_ops::solib_create_inferior_hook, and target_so_ops::special_symbol_handling.
static struct obj_section* data_obj_section_from_objfile (struct objfile * objfile) [static, read]
Definition at line 737 of file solib-aix.c.
References ALL_OBJFILE_OSECTIONS, objfile::obfd, and obj_section::the_bfd_section.
Referenced by solib_aix_get_toc_value().
DEF_VEC_P (lm_info_p)
static struct solib_aix_inferior_data* get_solib_aix_inferior_data (struct inferior * inf) [static, read]
Definition at line 111 of file solib-aix.c.
References solib_aix_inferior_data_handle, and XZALLOC.
Referenced by solib_aix_normal_stop_observer().
static void show_solib_aix_debug (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 798 of file solib-aix.c.
References _, and fprintf_filtered().
Referenced by _initialize_solib_aix().
static bfd* solib_aix_bfd_open (char * pathname) [static]
Definition at line 636 of file solib-aix.c.
References _, do_cleanups(), gdb_bfd_open(), gdb_bfd_openr_next_archived_file(), gdb_bfd_unref(), gnutarget, make_cleanup(), cleanup::next, solib_bfd_open(), strrchr(), warning(), xfree(), and xstrprintf().
Referenced by _initialize_solib_aix().
static CORE_ADDR solib_aix_bss_data_overlap (bfd * abfd) [static]
Definition at line 358 of file solib-aix.c.
Referenced by solib_aix_get_section_offsets(), and solib_aix_relocate_section_addresses().
static void solib_aix_clear_solib (void) [static]
Definition at line 454 of file solib-aix.c.
Referenced by _initialize_solib_aix().
static struct so_list* solib_aix_current_sos (void) [static, read]
Definition at line 562 of file solib-aix.c.
References current_inferior(), lm_info::filename, so_list::lm_info, lm_info::member_name, memcpy(), so_list::next, so_list::so_name, SO_NAME_MAX_PATH_SIZE, so_list::so_original_name, solib_aix_new_lm_info(), VEC, VEC_iterate, xstrprintf(), and XZALLOC.
Referenced by _initialize_solib_aix().
static void solib_aix_free_library_list (void * p) [static]
Definition at line 147 of file solib-aix.c.
Referenced by solib_aix_normal_stop_observer().
static void solib_aix_free_so (struct so_list * so) [static]
Definition at line 443 of file solib-aix.c.
References fprintf_unfiltered(), gdb_stdlog, so_list::lm_info, so_list::so_name, solib_aix_debug, and solib_aix_xfree_lm_info().
Referenced by _initialize_solib_aix().
static struct section_offsets* solib_aix_get_section_offsets (struct objfile * objfile, struct lm_info * info) [static, read]
Definition at line 466 of file solib-aix.c.
References lm_info::data_addr, objfile::num_sections, objfile::obfd, section_offsets::offsets, objfile::sect_index_bss, objfile::sect_index_data, objfile::sect_index_text, objfile::sections, solib_aix_bss_data_overlap(), lm_info::text_addr, obj_section::the_bfd_section, and XCALLOC.
Referenced by solib_aix_solib_create_inferior_hook().
CORE_ADDR solib_aix_get_toc_value (CORE_ADDR pc)
Definition at line 753 of file solib-aix.c.
References _, core_addr_to_string(), data_obj_section_from_objfile(), error(), find_pc_section(), fprintf_unfiltered(), gdb_stdlog, obj_section_addr, obj_section::objfile, objfile_name(), solib_aix_debug, and xcoff_get_toc_offset().
Referenced by rs6000_push_dummy_call().
static int solib_aix_in_dynsym_resolve_code (CORE_ADDR pc) [static]
Definition at line 628 of file solib-aix.c.
Referenced by _initialize_solib_aix().
static struct lm_info* solib_aix_new_lm_info (struct lm_info * info) [static, read]
Definition at line 67 of file solib-aix.c.
References lm_info::filename, lm_info::member_name, memcpy(), and xmalloc().
Referenced by solib_aix_current_sos().
static void solib_aix_normal_stop_observer (struct bpstats * unused_1, int unused_2) [static]
Definition at line 784 of file solib-aix.c.
References current_inferior(), get_solib_aix_inferior_data(), and solib_aix_free_library_list().
Referenced by _initialize_solib_aix().
static int solib_aix_open_symbol_file_object (void * from_ttyp) [static]
Definition at line 620 of file solib-aix.c.
Referenced by _initialize_solib_aix().
static void solib_aix_relocate_section_addresses (struct so_list * so, struct target_section * sec) [static]
Definition at line 390 of file solib-aix.c.
References target_section::addr, lm_info::data_addr, data_offset, lm_info::data_size, target_section::endaddr, so_list::lm_info, solib_aix_bss_data_overlap(), lm_info::text_addr, lm_info::text_size, and target_section::the_bfd_section.
Referenced by _initialize_solib_aix().
static void solib_aix_solib_create_inferior_hook (int from_tty) [static]
Definition at line 519 of file solib-aix.c.
References _, current_inferior(), do_cleanups(), exec_info, make_cleanup(), objfile_relocate(), section_offsets::offsets, solib_aix_get_section_offsets(), symfile_objfile, VEC, VEC_index, VEC_length, warning(), and xfree().
Referenced by _initialize_solib_aix().
static void solib_aix_special_symbol_handling (void) [static]
Definition at line 554 of file solib-aix.c.
Referenced by _initialize_solib_aix().
static void solib_aix_xfree_lm_info (struct lm_info * info) [static]
Definition at line 82 of file solib-aix.c.
References lm_info::filename, lm_info::member_name, and xfree().
Referenced by solib_aix_free_so().
static VEC (lm_info_p) [static]
Definition at line 129 of file solib-aix.c.
References _, and warning().
Variable Documentation
initialize_file_ftype _initialize_solib_aix
Referenced by initialize_all_files().
int solib_aix_debug [static]
Definition at line 32 of file solib-aix.c.
Referenced by _initialize_solib_aix(), solib_aix_free_so(), and solib_aix_get_toc_value().
struct inferior_data* solib_aix_inferior_data_handle [static]
Definition at line 105 of file solib-aix.c.
Referenced by _initialize_solib_aix(), and get_solib_aix_inferior_data().
struct target_so_ops solib_aix_so_ops
Definition at line 805 of file solib-aix.c.
Referenced by _initialize_solib_aix(), and rs6000_aix_init_osabi().