GDB (xrefs): /home/stan/gdb/src/gdb/solib-darwin.c File Reference
/home/stan/gdb/src/gdb/solib-darwin.c File Reference
#include "defs.h"
#include "symtab.h"
#include "bfd.h"
#include "symfile.h"
#include "objfiles.h"
#include "gdbcore.h"
#include "target.h"
#include "inferior.h"
#include "regcache.h"
#include "gdbthread.h"
#include "gdb_bfd.h"
#include "gdb_assert.h"
#include "solist.h"
#include "solib.h"
#include "solib-svr4.h"
#include "bfd-target.h"
#include "elf-bfd.h"
#include "exec.h"
#include "auxv.h"
#include "exceptions.h"
#include "mach-o.h"
#include "mach-o/external.h"
Classes
struct gdb_dyld_image_info
struct gdb_dyld_all_image_infos
struct darwin_info
struct lm_info
struct darwin_so_list
Defines
#define DYLD_VERSION_MIN 1
#define DYLD_VERSION_MAX 12
Functions
static void darwin_pspace_data_cleanup (struct program_space *pspace, void *arg)
static struct darwin_info * get_darwin_info (void)
static int darwin_dyld_version_ok (const struct darwin_info *info)
static void darwin_load_image_infos (struct darwin_info *info)
static CORE_ADDR lookup_symbol_from_bfd (bfd *abfd, char *symname)
static char * find_program_interpreter (void)
static int open_symbol_file_object (void *from_ttyp)
static struct so_list * darwin_current_sos (void)
static CORE_ADDR darwin_read_exec_load_addr (struct darwin_info *info)
static int darwin_in_dynsym_resolve_code (CORE_ADDR pc)
static void darwin_special_symbol_handling (void)
static bfd * gdb_bfd_mach_o_fat_extract (bfd *abfd, bfd_format format, const bfd_arch_info_type *arch)
static void darwin_solib_get_all_image_info_addr_at_init (struct darwin_info *info)
static void darwin_solib_read_all_image_info_addr (struct darwin_info *info)
static void darwin_solib_create_inferior_hook (int from_tty)
static void darwin_clear_solib (void)
static void darwin_free_so (struct so_list *so)
static void darwin_relocate_section_addresses (struct so_list *so, struct target_section *sec)
static struct symbol * darwin_lookup_lib_symbol (const struct objfile *objfile, const char *name, const domain_enum domain)
static bfd * darwin_bfd_open (char *pathname)
void _initialize_darwin_solib (void)
Variables
static struct program_space_data * solib_darwin_pspace_data
struct target_so_ops darwin_so_ops
initialize_file_ftype _initialize_darwin_solib
Define Documentation
#define DYLD_VERSION_MAX 12
Definition at line 73 of file solib-darwin.c.
Referenced by darwin_dyld_version_ok().
#define DYLD_VERSION_MIN 1
Definition at line 72 of file solib-darwin.c.
Referenced by darwin_dyld_version_ok().
Function Documentation
void _initialize_darwin_solib (void)
Definition at line 634 of file solib-darwin.c.
References _initialize_darwin_solib, target_so_ops::bfd_open, target_so_ops::clear_solib, target_so_ops::current_sos, darwin_bfd_open(), darwin_clear_solib(), darwin_current_sos(), darwin_free_so(), darwin_in_dynsym_resolve_code(), darwin_lookup_lib_symbol(), darwin_pspace_data_cleanup(), darwin_relocate_section_addresses(), darwin_so_ops, darwin_solib_create_inferior_hook(), darwin_special_symbol_handling(), target_so_ops::free_so, target_so_ops::in_dynsym_resolve_code, target_so_ops::lookup_lib_global_symbol, target_so_ops::open_symbol_file_object, open_symbol_file_object(), target_so_ops::relocate_section_addresses, target_so_ops::solib_create_inferior_hook, solib_darwin_pspace_data, and target_so_ops::special_symbol_handling.
static bfd* darwin_bfd_open (char * pathname) [static]
Definition at line 600 of file solib-darwin.c.
References _, error(), gdb_bfd_mach_o_fat_extract(), gdb_bfd_unref(), gdbarch_bfd_arch_info(), make_cleanup_bfd_unref(), perror_with_name(), solib_bfd_fopen(), solib_find(), and target_gdbarch().
Referenced by _initialize_darwin_solib().
static void darwin_clear_solib (void) [static]
Definition at line 555 of file solib-darwin.c.
References darwin_info::all_image, darwin_info::all_image_addr, get_darwin_info(), and gdb_dyld_all_image_infos::version.
Referenced by _initialize_darwin_solib().
static struct so_list* darwin_current_sos (void) [static, read]
Definition at line 246 of file solib-darwin.c.
References darwin_info::all_image, builtin_type::builtin_data_ptr, builtin_type(), gdb_dyld_all_image_infos::count, darwin_dyld_version_ok(), darwin_load_image_infos(), discard_cleanups(), extract_typed_address(), extract_unsigned_integer(), gdbarch_byte_order(), get_darwin_info(), gdb_dyld_all_image_infos::info, darwin_so_list::li, make_cleanup(), so_list::next, darwin_so_list::sl, SO_NAME_MAX_PATH_SIZE, target_gdbarch(), target_read_memory(), target_read_string(), TYPE_LENGTH, xfree(), and XZALLOC.
Referenced by _initialize_darwin_solib().
static int darwin_dyld_version_ok (const struct darwin_info * info) [static]
Definition at line 118 of file solib-darwin.c.
References darwin_info::all_image, DYLD_VERSION_MAX, DYLD_VERSION_MIN, and gdb_dyld_all_image_infos::version.
Referenced by darwin_current_sos(), darwin_load_image_infos(), and darwin_solib_create_inferior_hook().
static void darwin_free_so (struct so_list * so) [static]
Definition at line 564 of file solib-darwin.c.
Referenced by _initialize_darwin_solib().
static int darwin_in_dynsym_resolve_code (CORE_ADDR pc) [static]
Definition at line 383 of file solib-darwin.c.
Referenced by _initialize_darwin_solib().
static void darwin_load_image_infos (struct darwin_info * info) [static]
Definition at line 127 of file solib-darwin.c.
References darwin_info::all_image, darwin_info::all_image_addr, builtin_type::builtin_data_ptr, builtin_type(), gdb_dyld_all_image_infos::count, darwin_dyld_version_ok(), extract_typed_address(), extract_unsigned_integer(), gdb_assert, gdbarch_byte_order(), gdb_dyld_all_image_infos::info, len, type::length, memset(), gdb_dyld_all_image_infos::notifier, target_gdbarch(), target_read_memory(), and gdb_dyld_all_image_infos::version.
Referenced by darwin_current_sos(), and darwin_solib_create_inferior_hook().
static struct symbol* darwin_lookup_lib_symbol (const struct objfile * objfile, const char * name, const domain_enum domain) [static, read]
Definition at line 592 of file solib-darwin.c.
Referenced by _initialize_darwin_solib().
static void darwin_pspace_data_cleanup (struct program_space * pspace, void * arg) [static]
Definition at line 89 of file solib-darwin.c.
References solib_darwin_pspace_data, and xfree().
Referenced by _initialize_darwin_solib().
static CORE_ADDR darwin_read_exec_load_addr (struct darwin_info * info) [static]
Definition at line 338 of file solib-darwin.c.
References darwin_info::all_image, builtin_type::builtin_data_ptr, builtin_type(), gdb_dyld_all_image_infos::count, extract_typed_address(), extract_unsigned_integer(), gdbarch_byte_order(), gdb_dyld_all_image_infos::info, target_gdbarch(), target_read_memory(), and TYPE_LENGTH.
Referenced by darwin_solib_create_inferior_hook().
static void darwin_relocate_section_addresses (struct so_list * so, struct target_section * sec) [static]
Definition at line 572 of file solib-darwin.c.
References target_section::addr, so_list::addr_high, so_list::addr_low, target_section::endaddr, lm_info::lm_addr, and so_list::lm_info.
Referenced by _initialize_darwin_solib().
static void darwin_solib_create_inferior_hook (int from_tty) [static]
Definition at line 501 of file solib-darwin.c.
References darwin_info::all_image, darwin_info::all_image_addr, create_solib_event_breakpoint(), darwin_dyld_version_ok(), darwin_load_image_infos(), darwin_read_exec_load_addr(), darwin_solib_get_all_image_info_addr_at_init(), darwin_solib_read_all_image_info_addr(), exec_bfd, get_darwin_info(), gdb_dyld_all_image_infos::notifier, objfile_rebase(), symfile_objfile, and target_gdbarch().
Referenced by _initialize_darwin_solib().
static void darwin_solib_get_all_image_info_addr_at_init (struct darwin_info * info) [static]
Definition at line 421 of file solib-darwin.c.
References darwin_info::all_image_addr, current_inferior(), do_cleanups(), find_program_interpreter(), gdb_bfd_mach_o_fat_extract(), gdb_bfd_open(), gdbarch_bfd_arch_info(), get_current_regcache(), gnutarget, interp_name(), lookup_symbol_from_bfd(), make_cleanup(), make_cleanup_bfd_unref(), null_cleanup(), regcache_read_pc(), and target_gdbarch().
Referenced by darwin_solib_create_inferior_hook().
static void darwin_solib_read_all_image_info_addr (struct darwin_info * info) [static]
Definition at line 484 of file solib-darwin.c.
References darwin_info::all_image_addr, current_target, extract_unsigned_integer(), gdbarch_byte_order(), len, LONGEST, target_gdbarch(), TARGET_OBJECT_DARWIN_DYLD_INFO, and target_read().
Referenced by darwin_solib_create_inferior_hook().
static void darwin_special_symbol_handling (void) [static]
Definition at line 392 of file solib-darwin.c.
Referenced by _initialize_darwin_solib().
static char* find_program_interpreter (void) [static]
Definition at line 214 of file solib-darwin.c.
References exec_bfd.
Referenced by darwin_solib_get_all_image_info_addr_at_init().
static bfd* gdb_bfd_mach_o_fat_extract (bfd * abfd, bfd_format format, const bfd_arch_info_type * arch) [static]
Definition at line 401 of file solib-darwin.c.
References gdb_bfd_mark_parent(), and gdb_bfd_ref().
Referenced by darwin_bfd_open(), and darwin_solib_get_all_image_info_addr_at_init().
static struct darwin_info* get_darwin_info (void) [static, read]
Definition at line 101 of file solib-darwin.c.
References current_program_space, solib_darwin_pspace_data, and XZALLOC.
Referenced by darwin_clear_solib(), darwin_current_sos(), and darwin_solib_create_inferior_hook().
static CORE_ADDR lookup_symbol_from_bfd (bfd * abfd, char * symname) [static]
Definition at line 178 of file solib-darwin.c.
References xfree(), and xmalloc().
Referenced by darwin_solib_get_all_image_info_addr_at_init().
static int open_symbol_file_object (void * from_ttyp) [static]
Definition at line 238 of file solib-darwin.c.
Referenced by _initialize_darwin_solib().
Variable Documentation
initialize_file_ftype _initialize_darwin_solib
Referenced by _initialize_darwin_solib(), and initialize_all_files().
struct target_so_ops darwin_so_ops
Definition at line 628 of file solib-darwin.c.
Referenced by _initialize_darwin_solib(), i386_darwin_init_abi(), and x86_darwin_init_abi_64().
struct program_space_data* solib_darwin_pspace_data [static]
Definition at line 86 of file solib-darwin.c.
Referenced by _initialize_darwin_solib(), darwin_pspace_data_cleanup(), and get_darwin_info().