GDB (xrefs): /home/stan/gdb/src/gdb/solib-ia64-hpux.h File Reference
/home/stan/gdb/src/gdb/solib-ia64-hpux.h File Reference
Functions
int ia64_hpux_at_dld_breakpoint_p (ptid_t ptid)
void ia64_hpux_handle_dld_breakpoint (ptid_t ptid)
CORE_ADDR ia64_hpux_get_solib_linkage_addr (CORE_ADDR faddr)
Function Documentation
int ia64_hpux_at_dld_breakpoint_p (ptid_t ptid)
Definition at line 165 of file solib-ia64-hpux.c.
References _, ia64_hpux_at_dld_breakpoint_1_p(), inferior_ptid, gdb_exception::message, gdb_exception::reason, RETURN_MASK_ALL, TRY_CATCH, and warning().
Referenced by ia64_hpux_wait().
CORE_ADDR ia64_hpux_get_solib_linkage_addr (CORE_ADDR faddr)
Definition at line 656 of file solib-ia64-hpux.c.
References so_list::lm_info, lm_info::module_desc, so_list::next, and so_list_head.
Referenced by ia64_hpux_xfer_solib_got().
void ia64_hpux_handle_dld_breakpoint (ptid_t ptid)
Definition at line 279 of file solib-ia64-hpux.c.
References _, ia64_hpux_handle_dld_breakpoint_1(), inferior_ptid, gdb_exception::message, gdb_exception::reason, RETURN_MASK_ALL, TRY_CATCH, and warning().
Referenced by ia64_hpux_wait().