GDB (xrefs): /home/stan/gdb/src/gdb/solib-som.c File Reference
/home/stan/gdb/src/gdb/solib-som.c File Reference
#include "defs.h"
#include "symtab.h"
#include "bfd.h"
#include "symfile.h"
#include "objfiles.h"
#include "gdbcore.h"
#include "target.h"
#include "inferior.h"
#include "hppa-tdep.h"
#include "solist.h"
#include "solib.h"
#include "solib-som.h"
#include <string.h>
Classes
struct lm_info
struct addr_and_unwind_t
struct dld_list
Defines
#define DLD_FLAGS_MAPPRIVATE 0x1
#define DLD_FLAGS_HOOKVALID 0x2
#define DLD_FLAGS_LISTVALID 0x4
#define DLD_FLAGS_BOR_ENABLE 0x8
#define DEFAULT_HPUX_MAJOR_RELEASE 11
#define SHLIB_TEXT_PRIVATE_ENABLE 0x4000
#define EXTRACT(_fld)
Functions
static void som_relocate_section_addresses (struct so_list *so, struct target_section *sec)
static int get_hpux_major_release (void)
static void som_solib_create_inferior_hook (int from_tty)
static void som_special_symbol_handling (void)
static void som_solib_desire_dynamic_linker_symbols (void)
static int som_in_dynsym_resolve_code (CORE_ADDR pc)
static void som_clear_solib (void)
static CORE_ADDR link_map_start (void)
static int match_main (const char *name)
static struct so_list * som_current_sos (void)
static int som_open_symbol_file_object (void *from_ttyp)
static void som_free_so (struct so_list *so)
static CORE_ADDR som_solib_thread_start_addr (struct so_list *so)
static CORE_ADDR som_solib_get_got_by_pc (CORE_ADDR addr)
static CORE_ADDR som_solib_get_solib_by_pc (CORE_ADDR addr)
void _initialize_som_solib (void)
void som_solib_select (struct gdbarch *gdbarch)
int som_solib_section_offsets (struct objfile *objfile, struct section_offsets *offsets)
Variables
struct {
int is_valid
addr_and_unwind_t hook
addr_and_unwind_t hook_stub
addr_and_unwind_t load
addr_and_unwind_t load_stub
addr_and_unwind_t unload
addr_and_unwind_t unload2
addr_and_unwind_t unload_stub
} dld_cache
int hpux_major_release = DEFAULT_HPUX_MAJOR_RELEASE
struct {
short junk [37]
short flags
} dl_header
static struct target_so_ops som_so_ops
initialize_file_ftype _initialize_som_solib
Define Documentation
#define DEFAULT_HPUX_MAJOR_RELEASE 11
Definition at line 145 of file solib-som.c.
#define DLD_FLAGS_BOR_ENABLE 0x8
Definition at line 46 of file solib-som.c.
#define DLD_FLAGS_HOOKVALID 0x2
Definition at line 44 of file solib-som.c.
Referenced by som_solib_create_inferior_hook().
#define DLD_FLAGS_LISTVALID 0x4
Definition at line 45 of file solib-som.c.
Referenced by link_map_start().
#define DLD_FLAGS_MAPPRIVATE 0x1
Definition at line 43 of file solib-som.c.
Referenced by som_solib_create_inferior_hook().
#define EXTRACT (_fld)
Value:
extract_unsigned_integer ((gdb_byte *)&dbuf._fld, \
                            sizeof (dbuf._fld), byte_order);
Referenced by som_current_sos().
#define SHLIB_TEXT_PRIVATE_ENABLE 0x4000
Definition at line 155 of file solib-som.c.
Referenced by som_solib_create_inferior_hook().
Function Documentation
void _initialize_som_solib (void)
Definition at line 805 of file solib-som.c.
References _initialize_som_solib, target_so_ops::bfd_open, target_so_ops::clear_solib, target_so_ops::current_sos, target_so_ops::free_so, target_so_ops::in_dynsym_resolve_code, target_so_ops::open_symbol_file_object, target_so_ops::relocate_section_addresses, solib_bfd_open(), target_so_ops::solib_create_inferior_hook, som_clear_solib(), som_current_sos(), som_free_so(), som_in_dynsym_resolve_code(), som_open_symbol_file_object(), som_relocate_section_addresses(), som_so_ops, som_solib_create_inferior_hook(), som_special_symbol_handling(), and target_so_ops::special_symbol_handling.
static int get_hpux_major_release (void) [static]
Definition at line 149 of file solib-som.c.
References hpux_major_release.
Referenced by som_solib_create_inferior_hook().
static CORE_ADDR link_map_start (void) [static]
Definition at line 526 of file solib-som.c.
References _, DLD_FLAGS_LISTVALID, error(), extract_unsigned_integer(), gdbarch_byte_order(), lookup_minimal_symbol(), read_memory(), SYMBOL_VALUE_ADDRESS, and target_gdbarch().
Referenced by som_current_sos(), and som_open_symbol_file_object().
static int match_main (const char * name) [static]
Definition at line 570 of file solib-som.c.
References objfile_name(), and symfile_objfile.
Referenced by som_current_sos().
static void som_clear_solib (void) [static]
Definition at line 507 of file solib-som.c.
Referenced by _initialize_som_solib().
static struct so_list* som_current_sos (void) [static, read]
Definition at line 576 of file solib-som.c.
References _, lm_info::bind_mode, lm_info::bss_start, lm_info::data_end, lm_info::data_start, discard_cleanups(), EXTRACT, extract_unsigned_integer(), free_so(), gdbarch_byte_order(), lm_info::got_value, lm_info::library_version, link_map_start(), lm_info::lm, lm_info::lm_addr, make_cleanup(), match_main(), memset(), so_list::next, lm_info::next, paddress(), read_memory(), safe_strerror(), SO_NAME_MAX_PATH_SIZE, lm_info::struct_version, target_gdbarch(), target_read_string(), lm_info::text_addr, lm_info::text_end, lm_info::text_link_addr, lm_info::tsd_start_addr, warning(), xfree(), and xmalloc().
Referenced by _initialize_som_solib().
static void som_free_so (struct so_list * so) [static]
Definition at line 740 of file solib-som.c.
References so_list::lm_info, and xfree().
Referenced by _initialize_som_solib().
static int som_in_dynsym_resolve_code (CORE_ADDR pc) [static]
Definition at line 464 of file solib-som.c.
References dld_cache, find_unwind_entry(), and som_solib_desire_dynamic_linker_symbols().
Referenced by _initialize_som_solib().
static int som_open_symbol_file_object (void * from_ttyp) [static]
Definition at line 693 of file solib-som.c.
References _, do_cleanups(), extract_unsigned_integer(), lm_info::filename, gdbarch_byte_order(), lm_info::l_name, link_map_start(), lm_info::lm, make_cleanup(), name, query(), read_memory(), safe_strerror(), SO_NAME_MAX_PATH_SIZE, symbol_file_add_main(), symfile_objfile, target_gdbarch(), target_read_string(), warning(), and xfree().
Referenced by _initialize_som_solib().
static void som_relocate_section_addresses (struct so_list * so, struct target_section * sec) [static]
Definition at line 113 of file solib-som.c.
References so_list::abfd, target_section::addr, lm_info::data_start, target_section::endaddr, so_list::lm_info, lm_info::text_addr, lm_info::text_link_addr, and target_section::the_bfd_section.
Referenced by _initialize_som_solib().
static void som_solib_create_inferior_hook (int from_tty) [static]
Definition at line 186 of file solib-som.c.
References _, clear_symtab_users(), create_solib_event_breakpoint(), dl_header, dld_cache, DLD_FLAGS_HOOKVALID, DLD_FLAGS_MAPPRIVATE, error(), EXPORT, extract_unsigned_integer(), gdbarch_byte_order(), get_hpux_major_release(), hppa_lookup_stub_minimal_symbol(), inferior_ptid, keep_going(), lookup_minimal_symbol(), ptid_get_pid(), SHLIB_TEXT_PRIVATE_ENABLE, exsummary::status, store_unsigned_integer(), SYMBOL_LINKAGE_NAME, SYMBOL_VALUE, SYMBOL_VALUE_ADDRESS, symfile_objfile, target_gdbarch(), target_read_memory(), target_write_memory(), and warning().
Referenced by _initialize_som_solib().
static void som_solib_desire_dynamic_linker_symbols (void) [static]
Definition at line 367 of file solib-som.c.
References ALL_OBJFILES, dld_cache, EXPORT, find_unwind_entry(), lookup_minimal_symbol(), lookup_minimal_symbol_solib_trampoline(), mst_solib_trampoline, MSYMBOL_TYPE, unwind_table_entry::region_start, unwind_table_entry::stub_type, unwind_table_entry::stub_unwind, and SYMBOL_VALUE.
Referenced by som_in_dynsym_resolve_code().
static CORE_ADDR som_solib_get_got_by_pc (CORE_ADDR addr) [static]
Definition at line 755 of file solib-som.c.
References lm_info::got_value, so_list::lm_info, master_so_list(), so_list::next, lm_info::text_addr, and lm_info::text_end.
Referenced by som_solib_select().
static CORE_ADDR som_solib_get_solib_by_pc (CORE_ADDR addr) [static]
Definition at line 780 of file solib-som.c.
References lm_info::lm_addr, so_list::lm_info, master_so_list(), so_list::next, lm_info::text_addr, and lm_info::text_end.
Referenced by som_solib_select().
int som_solib_section_offsets (struct objfile * objfile, struct section_offsets * offsets)
Definition at line 833 of file solib-som.c.
References _, ALL_OBJFILE_OSECTIONS, ANOFFSET, lm_info::data_start, flags, so_list::lm_info, master_so_list(), so_list::next, objfile::obfd, objfile_name(), section_offsets::offsets, objfile::sect_index_bss, objfile::sect_index_data, SECT_OFF_BSS, SECT_OFF_DATA, SECT_OFF_TEXT, so_list::so_name, strstr(), lm_info::text_addr, lm_info::text_link_addr, obj_section::the_bfd_section, and warning().
Referenced by som_symfile_offsets().
void som_solib_select (struct gdbarch * gdbarch)
Definition at line 819 of file solib-som.c.
References gdbarch_tdep(), set_solib_ops(), gdbarch_tdep::solib_get_got_by_pc, gdbarch_tdep::solib_get_solib_by_pc, gdbarch_tdep::solib_thread_start_addr, som_so_ops, som_solib_get_got_by_pc(), som_solib_get_solib_by_pc(), and som_solib_thread_start_addr().
Referenced by hppa_hpux_som_init_abi().
static CORE_ADDR som_solib_thread_start_addr (struct so_list * so) [static]
Definition at line 746 of file solib-som.c.
References so_list::lm_info, and lm_info::tsd_start_addr.
Referenced by som_solib_select().
static void som_special_symbol_handling (void) [static]
Definition at line 362 of file solib-som.c.
Referenced by _initialize_som_solib().
Variable Documentation
initialize_file_ftype _initialize_som_solib
Referenced by _initialize_som_solib(), and initialize_all_files().
struct { ... } dl_header
Referenced by som_solib_create_inferior_hook().
struct { ... } dld_cache [static]
Referenced by som_in_dynsym_resolve_code(), som_solib_create_inferior_hook(), and som_solib_desire_dynamic_linker_symbols().
short flags
Definition at line 162 of file solib-som.c.
Referenced by add_symbol_file_command(), allocate_objfile(), backtrace_command_1(), c_type_print_base(), child_terminal_info(), cli_out_new(), cmd_record_call_history(), cmd_record_insn_history(), core_open(), disassemble_command(), do_free_global_table(), dwarf_parse_macro_header(), gcore_create_callback(), hppa_hpux_fetch_register(), hppa_hpux_read_pc(), hppa_hpux_save_state_offset(), hppa_hpux_store_register(), hppa_hpux_supply_save_state(), hppa_hpux_unwind_pc(), hppa_hpux_write_pc(), info_mach_thread_command(), lex_one_token(), m68hc11_elf_make_msymbol_special(), make_srec(), make_vector_type(), mi_cmd_stack_list_args(), mi_cmd_stack_list_frames(), mi_cmd_stack_list_locals(), mi_cmd_stack_list_variables(), mi_memory_changed(), mi_out_new(), microblaze_analyze_prologue(), mips_common_breakpoint(), objfile_find_memory_regions(), print_bfd_section_info(), print_objfile_section_info(), procfs_create_inferior(), procfs_meminfo(), procfs_wait(), reload_shared_libraries_1(), remote_fileio_func_open(), safe_symbol_file_add(), set_section_index(), solib_add(), som_solib_section_offsets(), som_symtab_read(), symbol_file_command(), tfile_open(), try_open_dwop_file(), tui_out_new(), ui_out_new(), windows_create_inferior(), xtensa_pseudo_register_read(), and xtensa_pseudo_register_write().
addr_and_unwind_t hook
Definition at line 102 of file solib-som.c.
Referenced by specify_exec_file_hook().
addr_and_unwind_t hook_stub
Definition at line 103 of file solib-som.c.
int hpux_major_release = DEFAULT_HPUX_MAJOR_RELEASE
Definition at line 146 of file solib-som.c.
Referenced by get_hpux_major_release(), and set_hpux_major_release().
int is_valid
Definition at line 101 of file solib-som.c.
short junk[37]
Definition at line 161 of file solib-som.c.
Referenced by gdb_get_blocks().
addr_and_unwind_t load
Definition at line 104 of file solib-som.c.
Referenced by arm_copy_block_xfer(), arm_copy_extra_ld_st(), and thumb2_copy_block_xfer().
addr_and_unwind_t load_stub
Definition at line 105 of file solib-som.c.
struct target_so_ops som_so_ops [static]
Definition at line 800 of file solib-som.c.
Referenced by _initialize_som_solib(), and som_solib_select().
addr_and_unwind_t unload
Definition at line 106 of file solib-som.c.
addr_and_unwind_t unload2
Definition at line 107 of file solib-som.c.
addr_and_unwind_t unload_stub
Definition at line 108 of file solib-som.c.