GDB (xrefs): /home/stan/gdb/src/gdb/solib-target.c File Reference
/home/stan/gdb/src/gdb/solib-target.c File Reference
#include "defs.h"
#include "objfiles.h"
#include "solist.h"
#include "symtab.h"
#include "symfile.h"
#include "target.h"
#include "vec.h"
#include "solib-target.h"
#include "gdb_string.h"
Classes
struct lm_info
Typedefs
typedef struct lm_info * lm_info_p
Functions
DEF_VEC_P (lm_info_p)
static VEC (lm_info_p)
static struct so_list * solib_target_current_sos (void)
static void solib_target_special_symbol_handling (void)
static void solib_target_solib_create_inferior_hook (int from_tty)
static void solib_target_clear_solib (void)
static void solib_target_free_so (struct so_list *so)
static void solib_target_relocate_section_addresses (struct so_list *so, struct target_section *sec)
static int solib_target_open_symbol_file_object (void *from_ttyp)
static int solib_target_in_dynsym_resolve_code (CORE_ADDR pc)
void _initialize_solib_target (void)
Variables
struct target_so_ops solib_target_so_ops
initialize_file_ftype _initialize_solib_target
Typedef Documentation
typedef struct lm_info* lm_info_p
Definition at line 54 of file solib-target.c.
Function Documentation
void _initialize_solib_target (void)
Definition at line 489 of file solib-target.c.
References target_so_ops::bfd_open, target_so_ops::clear_solib, target_so_ops::current_sos, current_target_so_ops, target_so_ops::free_so, target_so_ops::in_dynsym_resolve_code, target_so_ops::open_symbol_file_object, target_so_ops::relocate_section_addresses, solib_bfd_open(), target_so_ops::solib_create_inferior_hook, solib_target_clear_solib(), solib_target_current_sos(), solib_target_free_so(), solib_target_in_dynsym_resolve_code(), solib_target_open_symbol_file_object(), solib_target_relocate_section_addresses(), solib_target_so_ops, solib_target_solib_create_inferior_hook(), solib_target_special_symbol_handling(), and target_so_ops::special_symbol_handling.
DEF_VEC_P (lm_info_p)
static void solib_target_clear_solib (void) [static]
Definition at line 318 of file solib-target.c.
Referenced by _initialize_solib_target().
static struct so_list* solib_target_current_sos (void) [static, read]
Definition at line 246 of file solib-target.c.
References current_target, do_cleanups(), so_list::lm_info, make_cleanup(), lm_info::name, so_list::next, so_list::so_name, SO_NAME_MAX_PATH_SIZE, so_list::so_original_name, TARGET_OBJECT_LIBRARIES, target_read_stralloc(), VEC, VEC_free, VEC_iterate, xfree(), and XZALLOC.
Referenced by _initialize_solib_target().
static void solib_target_free_so (struct so_list * so) [static]
Definition at line 324 of file solib-target.c.
References gdb_assert, so_list::lm_info, lm_info::name, VEC_free, and xfree().
Referenced by _initialize_solib_target().
static int solib_target_in_dynsym_resolve_code (CORE_ADDR pc) [static]
Definition at line 475 of file solib-target.c.
References in_plt_section().
Referenced by _initialize_solib_target().
static int solib_target_open_symbol_file_object (void * from_ttyp) [static]
Definition at line 467 of file solib-target.c.
Referenced by _initialize_solib_target().
static void solib_target_relocate_section_addresses (struct so_list * so, struct target_section * sec) [static]
Definition at line 333 of file solib-target.c.
References _, so_list::abfd, target_section::addr, so_list::addr_high, so_list::addr_low, target_section::endaddr, free_symfile_segment_data(), gdb_assert, gdb_bfd_count_sections(), gdb_bfd_section_index(), get_symfile_segment_data(), so_list::lm_info, symfile_segment_data::num_segments, offset, symfile_segment_data::segment_bases, symfile_segment_data::segment_sizes, SIZEOF_N_SECTION_OFFSETS, so_list::so_name, symfile_map_offsets_to_segments(), target_section::the_bfd_section, ULONGEST, VEC_address, VEC_length, warning(), and xzalloc().
Referenced by _initialize_solib_target().
static void solib_target_solib_create_inferior_hook (int from_tty) [static]
Definition at line 312 of file solib-target.c.
Referenced by _initialize_solib_target().
static void solib_target_special_symbol_handling (void) [static]
Definition at line 306 of file solib-target.c.
Referenced by _initialize_solib_target().
static VEC (lm_info_p) [static]
Definition at line 59 of file solib-target.c.
References _, and warning().
Variable Documentation
initialize_file_ftype _initialize_solib_target
Referenced by initialize_all_files().
struct target_so_ops solib_target_so_ops
Definition at line 483 of file solib-target.c.
Referenced by _initialize_solib_target(), arm_symbian_init_abi(), dicos_init_abi(), and windows_init_abi().