GDB (xrefs): /home/stan/gdb/src/gdb/solib-som.h File Reference
/home/stan/gdb/src/gdb/solib-som.h File Reference
Functions
void som_solib_select (struct gdbarch *gdbarch)
int som_solib_section_offsets (struct objfile *objfile, struct section_offsets *offsets)
Variables
int hpux_major_release
Function Documentation
int som_solib_section_offsets (struct objfile * objfile, struct section_offsets * offsets)
Definition at line 833 of file solib-som.c.
References _, ALL_OBJFILE_OSECTIONS, ANOFFSET, lm_info::data_start, flags, so_list::lm_info, master_so_list(), so_list::next, objfile::obfd, objfile_name(), section_offsets::offsets, objfile::sect_index_bss, objfile::sect_index_data, SECT_OFF_BSS, SECT_OFF_DATA, SECT_OFF_TEXT, so_list::so_name, strstr(), lm_info::text_addr, lm_info::text_link_addr, obj_section::the_bfd_section, and warning().
Referenced by som_symfile_offsets().
void som_solib_select (struct gdbarch * gdbarch)
Definition at line 819 of file solib-som.c.
References gdbarch_tdep(), set_solib_ops(), gdbarch_tdep::solib_get_got_by_pc, gdbarch_tdep::solib_get_solib_by_pc, gdbarch_tdep::solib_thread_start_addr, som_so_ops, som_solib_get_got_by_pc(), som_solib_get_solib_by_pc(), and som_solib_thread_start_addr().
Referenced by hppa_hpux_som_init_abi().
Variable Documentation
int hpux_major_release
Definition at line 146 of file solib-som.c.
Referenced by get_hpux_major_release(), and set_hpux_major_release().