GDB (xrefs): /home/stan/gdb/src/gdb/solist.h File Reference
/home/stan/gdb/src/gdb/solist.h File Reference
#include "symtab.h"
Classes
struct so_list
struct target_so_ops
Defines
#define SO_NAME_MAX_PATH_SIZE 512 /* FIXME: Should be dynamic */
Functions
void free_so (struct so_list *so)
struct so_list * master_so_list (void)
char * solib_find (char *in_pathname, int *fd)
bfd * solib_bfd_fopen (char *pathname, int fd)
bfd * solib_bfd_open (char *in_pathname)
struct symbol * solib_global_lookup (const struct objfile *objfile, const char *name, const domain_enum domain)
Variables
struct target_so_ops * current_target_so_ops
Define Documentation
#define SO_NAME_MAX_PATH_SIZE 512 /* FIXME: Should be dynamic */
Definition at line 22 of file solist.h.
Referenced by darwin_current_sos(), dsbt_current_sos(), frv_current_sos(), init_so(), irix_current_sos(), irix_open_symbol_file_object(), new_so_list(), open_symbol_file_object(), solib_aix_current_sos(), solib_target_current_sos(), som_current_sos(), som_open_symbol_file_object(), svr4_default_sos(), svr4_read_so_list(), and windows_make_so().
Function Documentation
void free_so (struct so_list * so)
Definition at line 572 of file solib.c.
References clear_so(), target_so_ops::free_so, solib_ops(), target_gdbarch(), and xfree().
Referenced by clear_solib(), do_free_so(), som_current_sos(), svr4_free_library_list(), and update_solib_list().
struct so_list* master_so_list (void) [read]
Definition at line 585 of file solib.c.
References so_list_head.
Referenced by enable_break(), free_all_objfiles(), frv_fdpic_find_canonical_descriptor(), frv_fdpic_find_global_pointer(), frv_fetch_objfile_link_map(), som_solib_get_got_by_pc(), som_solib_get_solib_by_pc(), som_solib_section_offsets(), and svr4_fetch_objfile_link_map().
bfd* solib_bfd_fopen (char * pathname, int fd)
Definition at line 385 of file solib.c.
References _, error(), gdb_assert, gdb_bfd_open(), gnutarget, make_cleanup(), remote_bfd_open(), remote_filename_p(), and xfree().
Referenced by darwin_bfd_open(), and solib_bfd_open().
bfd* solib_bfd_open (char * in_pathname)
Definition at line 417 of file solib.c.
References _, error(), gdbarch_bfd_arch_info(), make_cleanup_bfd_unref(), perror_with_name(), solib_bfd_fopen(), solib_find(), target_gdbarch(), and warning().
Referenced by _initialize_dsbt_solib(), _initialize_frv_solib(), _initialize_irix_solib(), _initialize_osf_solib(), _initialize_solib_target(), _initialize_som_solib(), _initialize_svr4_solib(), enable_break(), enable_break2(), ia64_hpux_target_so_ops(), reload_shared_libraries_1(), and solib_aix_bfd_open().
char* solib_find (char * in_pathname, int * fd)
Definition at line 145 of file solib.c.
References current_inferior(), do_cleanups(), DOS_BASED_FILE_SYSTEM, effective_target_file_system_kind(), file_system_kind_dos_based, target_so_ops::find_and_open_solib, gdb_open_cloexec(), gdb_sysroot, gdbarch_solib_symbols_extension(), get_in_environ(), HAS_TARGET_DRIVE_SPEC, IS_TARGET_ABSOLUTE_PATH, IS_TARGET_DIR_SEPARATOR, make_cleanup(), memcpy(), null_cleanup(), openp(), OPF_RETURN_REALPATH, OPF_TRY_CWD_FIRST, p, remote_filename_p(), REMOTE_SYSROOT_PREFIX, savestring(), solib_ops(), solib_search_path, target_gdbarch(), target_lbasename(), and xfree().
Referenced by darwin_bfd_open(), and solib_bfd_open().
struct symbol* solib_global_lookup (const struct objfile * objfile, const char * name, const domain_enum domain) [read]
Definition at line 1391 of file solib.c.
References target_so_ops::lookup_lib_global_symbol, solib_ops(), and target_gdbarch().
Referenced by lookup_symbol_global().
Variable Documentation
struct target_so_ops* current_target_so_ops
Definition at line 90 of file solib.c.
Referenced by _initialize_osf_solib(), _initialize_solib_target(), and solib_init().