GDB (xrefs): /home/stan/gdb/src/gdb/solib.h File Reference
/home/stan/gdb/src/gdb/solib.h File Reference
Functions
void clear_solib (void)
void solib_add (char *, int, struct target_ops *, int)
int solib_read_symbols (struct so_list *, int)
void solib_create_inferior_hook (int from_tty)
char * solib_name_from_address (struct program_space *, CORE_ADDR)
int solib_contains_address_p (const struct so_list *, CORE_ADDR)
int solib_keep_data_in_core (CORE_ADDR vaddr, unsigned long size)
int in_solib_dynsym_resolve_code (CORE_ADDR)
void no_shared_libraries (char *ignored, int from_tty)
void set_solib_ops (struct gdbarch *gdbarch, const struct target_so_ops *new_ops)
int libpthread_name_p (const char *name)
CORE_ADDR gdb_bfd_lookup_symbol (bfd *abfd, int(*match_sym)(asymbol *, void *), void *data)
CORE_ADDR gdb_bfd_lookup_symbol_from_symtab (bfd *abfd, int(*match_sym)(asymbol *, void *), void *data)
void update_solib_breakpoints (void)
void handle_solib_event (void)
Function Documentation
void clear_solib (void)
Definition at line 1139 of file solib.c.
CORE_ADDR gdb_bfd_lookup_symbol (bfd * abfd, int(*)(asymbol *, void *) match_sym, void * data)
Definition at line 1485 of file solib.c.
References bfd_lookup_symbol_from_dyn_symtab(), and gdb_bfd_lookup_symbol_from_symtab().
Referenced by enable_break(), and enable_break2().
CORE_ADDR gdb_bfd_lookup_symbol_from_symtab (bfd * abfd, int(*)(asymbol *, void *) match_sym, void * data)
Definition at line 1408 of file solib.c.
References do_cleanups(), make_cleanup(), xfree(), and xmalloc().
Referenced by gdb_bfd_lookup_symbol().
void handle_solib_event (void)
Definition at line 1244 of file solib.c.
References auto_solib_add, clear_program_space_solib_cache(), current_inferior(), current_target, target_so_ops::handle_event, solib_add(), solib_ops(), target_gdbarch(), target_terminal_inferior(), and target_terminal_ours_for_output.
Referenced by bpstat_stop_status(), and handle_inferior_event().
int in_solib_dynsym_resolve_code (CORE_ADDR)
Definition at line 1197 of file solib.c.
References target_so_ops::in_dynsym_resolve_code, solib_ops(), and target_gdbarch().
Referenced by handle_inferior_event().
int libpthread_name_p (const char * name)
Definition at line 870 of file solib.c.
References strstr().
Referenced by has_libpthread(), libpthread_solib_p(), thread_db_new_objfile(), and try_thread_db_load_from_pdir().
void no_shared_libraries (char * ignored, int from_tty)
Definition at line 1219 of file solib.c.
References clear_solib(), and objfile_purge_solibs().
Referenced by _initialize_solib(), detach_command(), disconnect_command(), follow_exec(), release_program_space(), remote_open_1(), symbol_file_clear(), and target_pre_inferior().
void set_solib_ops (struct gdbarch * gdbarch, const struct target_so_ops * new_ops)
Definition at line 78 of file solib.c.
References gdbarch_data().
Referenced by arm_symbian_init_abi(), dicos_init_abi(), frv_gdbarch_init(), i386_darwin_init_abi(), i386nto_init_abi(), ia64_hpux_init_abi(), mips_irix_init_abi(), mips_linux_init_abi(), ppc_linux_init_abi(), rs6000_aix_init_osabi(), set_solib_svr4_fetch_link_map_offsets(), set_spu_solib_ops(), som_solib_select(), tic6x_uclinux_init_abi(), windows_init_abi(), and x86_darwin_init_abi_64().
void solib_add (char * , int , struct target_ops * , int)
Definition at line 893 of file solib.c.
References _, breakpoint_re_set(), current_program_space, error(), flags, info_verbose, libpthread_solib_p(), so_list::next, printf_unfiltered(), re_comp(), reinit_frame_cache(), so_list_head, so_list::so_name, program_space::solib_add_generation, solib_ops(), solib_read_symbols(), target_so_ops::special_symbol_handling, so_list::symbols_loaded, SYMFILE_DEFER_BP_RESET, SYMFILE_VERBOSE, target_gdbarch(), and update_solib_list().
Referenced by enable_break(), frv_fetch_objfile_link_map(), handle_solib_event(), ia64_hpux_handle_dld_breakpoint_1(), ia64_hpux_solib_add_after_attach(), irix_solib_create_inferior_hook(), osf_solib_create_inferior_hook(), post_create_inferior(), reload_shared_libraries(), remote_start_remote(), sharedlibrary_command(), and svr4_fetch_objfile_link_map().
int solib_contains_address_p (const struct so_list * , CORE_ADDR)
Definition at line 1084 of file solib.c.
References target_section::addr, target_section::endaddr, p, so_list::sections, and sections_end.
Referenced by disable_breakpoints_in_unloaded_shlib(), and solib_name_from_address().
void solib_create_inferior_hook (int from_tty)
Definition at line 1186 of file solib.c.
References target_so_ops::solib_create_inferior_hook, solib_ops(), and target_gdbarch().
Referenced by follow_exec(), linux_child_follow_fork(), post_create_inferior(), procfs_create_inferior(), procfs_post_attach(), and reload_shared_libraries().
int solib_keep_data_in_core (CORE_ADDR vaddr, unsigned long size)
Definition at line 1126 of file solib.c.
References target_so_ops::keep_data_in_core, solib_ops(), and target_gdbarch().
Referenced by gcore_create_callback().
char* solib_name_from_address (struct program_space * , CORE_ADDR)
Definition at line 1108 of file solib.c.
References so_list::next, program_space::so_list, so_list::so_name, and solib_contains_address_p().
Referenced by disable_breakpoints_in_shlibs(), get_frame_name(), insert_bp_location(), print_frame(), and remove_breakpoint_1().
int solib_read_symbols (struct so_list * , int)
Definition at line 595 of file solib.c.
References _, so_list::abfd, so_list::addr_low, objfile::addr_low, ALL_OBJFILES, build_section_addr_info_from_section_table(), current_inferior(), exception_fprintf(), free_section_addr_info(), gdb_stderr, info_verbose, OBJF_SHARED, so_list::objfile, objfile_name(), printf_unfiltered(), gdb_exception::reason, RETURN_MASK_ERROR, so_list::sections, so_list::sections_end, so_list::so_name, symbol_file_add_from_bfd(), so_list::symbols_loaded, inferior::symfile_flags, SYMFILE_VERBOSE, and TRY_CATCH.
Referenced by bsd_uthread_solib_loaded(), ppc_linux_spe_context_solib_loaded(), reload_shared_libraries_1(), solib_add(), and spu_solib_loaded().
void update_solib_breakpoints (void)
Definition at line 1233 of file solib.c.
References solib_ops(), target_gdbarch(), and target_so_ops::update_breakpoints.
Referenced by set_stop_on_solib_events().