GDB (xrefs): /home/stan/gdb/src/gdb/solib-irix.c File Reference
/home/stan/gdb/src/gdb/solib-irix.c File Reference
#include "defs.h"
#include "symtab.h"
#include "bfd.h"
#include "symfile.h"
#include "objfiles.h"
#include "gdbcore.h"
#include "target.h"
#include "inferior.h"
#include "gdbthread.h"
#include "solist.h"
#include "solib.h"
#include "solib-irix.h"
Classes
struct lm_info
struct gdb_int32_bytes
struct gdb_int64_bytes
struct irix_obj_list
struct irix_elf32_obj_info
struct irix_elf64_obj_info
union irix_obj_info
Defines
#define DEBUG_BASE "__rld_obj_head"
Functions
static CORE_ADDR extract_mips_address (void *addr, int len, enum bfd_endian byte_order)
static struct lm_info fetch_lm_info (CORE_ADDR addr)
static CORE_ADDR locate_base (void)
static int disable_break (void)
static int enable_break (void)
static void irix_solib_create_inferior_hook (int from_tty)
static struct so_list * irix_current_sos (void)
static int irix_open_symbol_file_object (void *from_ttyp)
static void irix_special_symbol_handling (void)
static void irix_relocate_section_addresses (struct so_list *so, struct target_section *sec)
static void irix_free_so (struct so_list *so)
static void irix_clear_solib (void)
static int irix_in_dynsym_resolve_code (CORE_ADDR pc)
void _initialize_irix_solib (void)
Variables
static void * base_breakpoint
static CORE_ADDR debug_base
struct target_so_ops irix_so_ops
initialize_file_ftype _initialize_irix_solib
Define Documentation
#define DEBUG_BASE "__rld_obj_head"
Definition at line 240 of file solib-irix.c.
Referenced by locate_base().
Function Documentation
void _initialize_irix_solib (void)
Definition at line 644 of file solib-irix.c.
References _initialize_irix_solib, target_so_ops::bfd_open, target_so_ops::clear_solib, target_so_ops::current_sos, target_so_ops::free_so, target_so_ops::in_dynsym_resolve_code, irix_clear_solib(), irix_current_sos(), irix_free_so(), irix_in_dynsym_resolve_code(), irix_open_symbol_file_object(), irix_relocate_section_addresses(), irix_so_ops, irix_solib_create_inferior_hook(), irix_special_symbol_handling(), target_so_ops::open_symbol_file_object, target_so_ops::relocate_section_addresses, solib_bfd_open(), target_so_ops::solib_create_inferior_hook, and target_so_ops::special_symbol_handling.
static int disable_break (void) [static]
Definition at line 301 of file solib-irix.c.
References base_breakpoint, deprecated_remove_raw_breakpoint(), exsummary::status, and target_gdbarch().
Referenced by irix_solib_create_inferior_hook().
static int enable_break (void) [static]
Definition at line 330 of file solib-irix.c.
References base_breakpoint, deprecated_insert_raw_breakpoint(), entry_point_address_query(), get_current_frame(), get_frame_address_space(), has_stack_frames(), symfile_objfile, and target_gdbarch().
Referenced by irix_solib_create_inferior_hook().
static CORE_ADDR extract_mips_address (void * addr, int len, enum bfd_endian byte_order) [static]
Definition at line 132 of file solib-irix.c.
References extract_signed_integer().
Referenced by fetch_lm_info(), irix_current_sos(), and irix_open_symbol_file_object().
static struct lm_info fetch_lm_info (CORE_ADDR addr) [static, read]
Definition at line 142 of file solib-irix.c.
References _, lm_info::addr, error(), extract_mips_address(), extract_unsigned_integer(), gdbarch_byte_order(), lm_info::next, lm_info::pathname_addr, lm_info::pathname_len, read_memory(), lm_info::reloc_offset, and target_gdbarch().
Referenced by irix_current_sos(), and irix_open_symbol_file_object().
static void irix_clear_solib (void) [static]
Definition at line 625 of file solib-irix.c.
References debug_base.
Referenced by _initialize_irix_solib().
static struct so_list* irix_current_sos (void) [static, read]
Definition at line 453 of file solib-irix.c.
References _, debug_base, discard_cleanups(), extract_mips_address(), fetch_lm_info(), gdbarch_addr_bit(), gdbarch_byte_order(), locate_base(), make_cleanup(), memset(), so_list::next, lm_info::next, lm_info::pathname_addr, lm_info::pathname_len, read_memory(), safe_strerror(), SO_NAME_MAX_PATH_SIZE, target_gdbarch(), target_read_string(), warning(), xfree(), and xmalloc().
Referenced by _initialize_irix_solib().
static void irix_free_so (struct so_list * so) [static]
Definition at line 617 of file solib-irix.c.
References so_list::lm_info, and xfree().
Referenced by _initialize_irix_solib().
static int irix_in_dynsym_resolve_code (CORE_ADDR pc) [static]
Definition at line 633 of file solib-irix.c.
Referenced by _initialize_irix_solib().
static int irix_open_symbol_file_object (void * from_ttyp) [static]
Definition at line 545 of file solib-irix.c.
References _, debug_base, do_cleanups(), extract_mips_address(), fetch_lm_info(), gdbarch_addr_bit(), gdbarch_byte_order(), locate_base(), make_cleanup(), lm_info::pathname_addr, query(), read_memory(), safe_strerror(), SO_NAME_MAX_PATH_SIZE, symbol_file_add_main(), symfile_objfile, target_gdbarch(), target_read_string(), warning(), and xfree().
Referenced by _initialize_irix_solib().
static void irix_relocate_section_addresses (struct so_list * so, struct target_section * sec) [static]
Definition at line 607 of file solib-irix.c.
References target_section::addr, target_section::endaddr, so_list::lm_info, and lm_info::reloc_offset.
Referenced by _initialize_irix_solib().
static void irix_solib_create_inferior_hook (int from_tty) [static]
Definition at line 388 of file solib-irix.c.
References _, inferior::attach_flag, auto_solib_add, clear_proceed_status(), inferior::control, current_inferior(), current_target, disable_break(), enable_break(), arm-linux::inf, inferior_thread(), NO_STOP_QUIETLY, pid_to_ptid(), solib_add(), STOP_QUIETLY, thread_suspend_state::stop_signal, inferior_control_state::stop_soon, thread_info::suspend, target_can_run, target_resume(), wait_for_inferior(), and warning().
Referenced by _initialize_irix_solib().
static void irix_special_symbol_handling (void) [static]
Definition at line 600 of file solib-irix.c.
Referenced by _initialize_irix_solib().
static CORE_ADDR locate_base (void) [static]
Definition at line 282 of file solib-irix.c.
References DEBUG_BASE, lookup_minimal_symbol(), SYMBOL_VALUE_ADDRESS, and symfile_objfile.
Referenced by irix_current_sos(), and irix_open_symbol_file_object().
Variable Documentation
initialize_file_ftype _initialize_irix_solib
Referenced by _initialize_irix_solib(), and initialize_all_files().
void* base_breakpoint [static]
Definition at line 242 of file solib-irix.c.
Referenced by disable_break(), and enable_break().
CORE_ADDR debug_base [static]
Definition at line 244 of file solib-irix.c.
Referenced by irix_clear_solib(), irix_current_sos(), irix_open_symbol_file_object(), and svr4_handle_solib_event().
struct target_so_ops irix_so_ops
Definition at line 638 of file solib-irix.c.
Referenced by _initialize_irix_solib(), and mips_irix_init_abi().