GDB (xrefs): /home/stan/gdb/src/gdb/solib-svr4.h File Reference
/home/stan/gdb/src/gdb/solib-svr4.h File Reference
Classes
struct link_map_offsets
Functions
void set_solib_svr4_fetch_link_map_offsets (struct gdbarch *gdbarch, struct link_map_offsets *(*func)(void))
CORE_ADDR svr4_fetch_objfile_link_map (struct objfile *objfile)
struct link_map_offsets * svr4_ilp32_fetch_link_map_offsets (void)
struct link_map_offsets * svr4_lp64_fetch_link_map_offsets (void)
int svr4_in_dynsym_resolve_code (CORE_ADDR pc)
Variables
struct target_so_ops svr4_so_ops
Function Documentation
void set_solib_svr4_fetch_link_map_offsets (struct gdbarch * gdbarch, struct link_map_offsets *(*)(void) func)
Definition at line 2966 of file solib-svr4.c.
References solib_svr4_ops::fetch_link_map_offsets, gdbarch_data(), set_solib_ops(), and svr4_so_ops.
Referenced by aarch64_linux_init_abi(), alpha_linux_init_abi(), alphafbsd_init_abi(), alphanbsd_init_abi(), alphaobsd_init_abi(), am33_linux_init_osabi(), amd64_linux_init_abi(), amd64_sol2_init_abi(), amd64_x32_linux_init_abi(), amd64fbsd_init_abi(), amd64nbsd_init_abi(), amd64obsd_init_abi(), arm_linux_init_abi(), arm_netbsd_elf_init_abi(), armobsd_init_abi(), cris_linux_init_abi(), hppa_linux_init_abi(), hppabsd_init_abi(), i386_linux_init_abi(), i386_sol2_init_abi(), i386fbsd_init_abi(), i386gnu_init_abi(), i386nbsdelf_init_abi(), i386nto_init_abi(), i386obsd_elf_init_abi(), ia64_linux_init_abi(), m32r_linux_init_abi(), m68k_linux_init_abi(), m68kbsd_elf_init_abi(), microblaze_linux_init_abi(), mips64obsd_init_abi(), mips_linux_init_abi(), mipsnbsd_init_abi(), nios2_linux_init_abi(), ppc_linux_init_abi(), ppcfbsd_init_abi(), ppcnbsd_init_abi(), ppcobsd_init_abi(), s390_gdbarch_init(), sh_linux_init_abi(), shnbsd_init_abi(), sparc32_linux_init_abi(), sparc32_sol2_init_abi(), sparc32nbsd_elf_init_abi(), sparc64_linux_init_abi(), sparc64_sol2_init_abi(), sparc64fbsd_init_abi(), sparc64nbsd_init_abi(), sparc64obsd_init_abi(), tilegx_linux_init_abi(), vaxnbsd_elf_init_abi(), xtensa_gdbarch_init(), and xtensa_linux_init_abi().
CORE_ADDR svr4_fetch_objfile_link_map (struct objfile * objfile)
Definition at line 1490 of file solib-svr4.c.
References auto_solib_add, current_target, get_svr4_info(), lm_info::lm_addr, so_list::lm_info, svr4_info::main_lm_addr, master_so_list(), so_list::next, so_list::objfile, solib_add(), and symfile_objfile.
Referenced by aarch64_linux_init_abi(), alpha_linux_init_abi(), amd64_linux_init_abi_common(), arm_linux_init_abi(), cris_linux_init_abi(), hppa_linux_init_abi(), i386_linux_init_abi(), ia64_linux_init_abi(), m32r_linux_init_abi(), m68k_linux_init_abi(), mips_linux_init_abi(), nios2_linux_init_abi(), ppc_linux_init_abi(), ppc_linux_spe_context_lookup(), ppcfbsd_init_abi(), s390_gdbarch_init(), sh_linux_init_abi(), sparc32_linux_init_abi(), sparc64_linux_init_abi(), and tilegx_linux_init_abi().
struct link_map_offsets* svr4_ilp32_fetch_link_map_offsets (void) [read]
Definition at line 3007 of file solib-svr4.c.
References link_map_offsets::l_addr_offset, link_map_offsets::l_ld_offset, link_map_offsets::l_name_offset, link_map_offsets::l_next_offset, link_map_offsets::l_prev_offset, link_map_offsets::link_map_size, link_map_offsets::r_brk_offset, link_map_offsets::r_ldsomap_offset, link_map_offsets::r_map_offset, link_map_offsets::r_version_offset, and link_map_offsets::r_version_size.
Referenced by am33_linux_init_osabi(), amd64_x32_linux_init_abi(), arm_linux_init_abi(), arm_netbsd_elf_init_abi(), armobsd_init_abi(), cris_linux_init_abi(), hppa_linux_init_abi(), hppabsd_init_abi(), i386_linux_init_abi(), i386_sol2_init_abi(), i386fbsd_init_abi(), i386gnu_init_abi(), i386nbsdelf_init_abi(), i386nto_init_abi(), i386obsd_elf_init_abi(), init_i386nto_ops(), m32r_linux_init_abi(), m68k_linux_init_abi(), m68kbsd_elf_init_abi(), microblaze_linux_init_abi(), mips_linux_init_abi(), nbsd_ilp32_solib_svr4_fetch_link_map_offsets(), nios2_linux_init_abi(), ppc_linux_init_abi(), ppcfbsd_init_abi(), ppcnbsd_init_abi(), ppcobsd_init_abi(), s390_gdbarch_init(), sh_linux_init_abi(), shnbsd_init_abi(), sparc32_linux_init_abi(), sparc32_sol2_init_abi(), sparc32nbsd_elf_init_abi(), tilegx_linux_init_abi(), vaxnbsd_elf_init_abi(), xtensa_gdbarch_init(), and xtensa_linux_init_abi().
int svr4_in_dynsym_resolve_code (CORE_ADDR pc)
Definition at line 1535 of file solib-svr4.c.
References get_svr4_info(), in_gnu_ifunc_stub(), in_plt_section(), interp_plt_sect_high, svr4_info::interp_plt_sect_low, interp_text_sect_high, and svr4_info::interp_text_sect_low.
Referenced by _initialize_svr4_solib(), mips_linux_in_dynsym_resolve_code(), and powerpc_linux_in_dynsym_resolve_code().
struct link_map_offsets* svr4_lp64_fetch_link_map_offsets (void) [read]
Definition at line 3038 of file solib-svr4.c.
References link_map_offsets::l_addr_offset, link_map_offsets::l_ld_offset, link_map_offsets::l_name_offset, link_map_offsets::l_next_offset, link_map_offsets::l_prev_offset, link_map_offsets::link_map_size, link_map_offsets::r_brk_offset, link_map_offsets::r_ldsomap_offset, link_map_offsets::r_map_offset, link_map_offsets::r_version_offset, and link_map_offsets::r_version_size.
Referenced by aarch64_linux_init_abi(), alpha_linux_init_abi(), alphafbsd_init_abi(), alphanbsd_init_abi(), alphaobsd_init_abi(), amd64_linux_init_abi(), amd64_sol2_init_abi(), amd64fbsd_init_abi(), amd64nbsd_init_abi(), amd64obsd_init_abi(), ia64_linux_init_abi(), mips64obsd_init_abi(), mips_linux_init_abi(), nbsd_lp64_solib_svr4_fetch_link_map_offsets(), ppc_linux_init_abi(), ppcfbsd_init_abi(), s390_gdbarch_init(), sparc64_linux_init_abi(), sparc64_sol2_init_abi(), sparc64fbsd_init_abi(), sparc64nbsd_init_abi(), sparc64obsd_init_abi(), and tilegx_linux_init_abi().
Variable Documentation
struct target_so_ops svr4_so_ops
Definition at line 3066 of file solib-svr4.c.
Referenced by _initialize_svr4_solib(), i386nto_init_abi(), mips_linux_init_abi(), ppc_linux_init_abi(), set_solib_svr4_fetch_link_map_offsets(), set_spu_solib_ops(), spu_bfd_open(), spu_current_sos(), spu_free_so(), spu_lookup_lib_symbol(), spu_relocate_section_addresses(), and spu_solib_create_inferior_hook().