GDB (xrefs): /home/stan/gdb/src/gdb/somread.c File Reference
/home/stan/gdb/src/gdb/somread.c File Reference
#include "defs.h"
#include "bfd.h"
#include "som/aout.h"
#include "symtab.h"
#include "symfile.h"
#include "objfiles.h"
#include "buildsym.h"
#include "stabsread.h"
#include "gdb-stabs.h"
#include "complaints.h"
#include "gdb_string.h"
#include "demangle.h"
#include "som.h"
#include "libhppa.h"
#include "psymtab.h"
#include "solib-som.h"
Classes
struct find_section_offset_arg
Defines
#define text_offset ANOFFSET (section_offsets, SECT_OFF_TEXT (objfile))
#define data_offset ANOFFSET (section_offsets, SECT_OFF_DATA (objfile))
Functions
static void som_symtab_read (bfd *abfd, struct objfile *objfile, struct section_offsets *section_offsets)
static void som_symfile_read (struct objfile *objfile, int symfile_flags)
static void som_new_init (struct objfile *ignore)
static void som_symfile_finish (struct objfile *objfile)
static void som_symfile_init (struct objfile *objfile)
static void find_section_offset (bfd *abfd, asection *sect, void *arg)
static void set_section_index (struct objfile *objfile, flagword invert, flagword flags, int *index_ptr)
static void som_symfile_offsets (struct objfile *objfile, const struct section_addr_info *addrs)
void _initialize_somread (void)
Variables
static struct sym_fns som_sym_fns
initialize_file_ftype _initialize_somread
Define Documentation
#define data_offset ANOFFSET (section_offsets, SECT_OFF_DATA (objfile))
Referenced by solib_aix_relocate_section_addresses(), and som_symtab_read().
#define text_offset ANOFFSET (section_offsets, SECT_OFF_TEXT (objfile))
Referenced by dwarf2_compile_cfa_to_ax(), read_ofile_symtab(), read_unwind_info(), som_symtab_read(), and windows_xfer_shared_library().
Function Documentation
void _initialize_somread (void)
Definition at line 553 of file somread.c.
References add_symtab_fns().
static void find_section_offset (bfd * abfd, asection * sect, void * arg) [static]
Definition at line 443 of file somread.c.
References find_section_offset_arg::best_section, find_section_offset_arg::empty_section, find_section_offset_arg::flags, and find_section_offset_arg::invert.
Referenced by set_section_index().
static void set_section_index (struct objfile * objfile, flagword invert, flagword flags, int * index_ptr) [static]
Definition at line 470 of file somread.c.
References find_section_offset_arg::best_section, find_section_offset_arg::empty_section, find_section_offset(), flags, find_section_offset_arg::flags, find_section_offset_arg::invert, objfile::obfd, and find_section_offset_arg::objfile.
Referenced by som_symfile_offsets().
static void som_new_init (struct objfile * ignore) [static]
Definition at line 387 of file somread.c.
References buildsym_new_init(), and stabsread_new_init().
static void som_symfile_finish (struct objfile * objfile) [static]
Definition at line 399 of file somread.c.
static void som_symfile_init (struct objfile * objfile) [static]
Definition at line 406 of file somread.c.
References objfile::flags, and OBJF_REORDERED.
static void som_symfile_offsets (struct objfile * objfile, const struct section_addr_info * addrs) [static]
Definition at line 493 of file somread.c.
References section_addr_info::other_sections::addr, section_addr_info::other_sections::name, section_addr_info::num_sections, objfile::num_sections, objfile::obfd, objfile::objfile_obstack, section_addr_info::other, objfile::sect_index_bss, objfile::sect_index_data, objfile::sect_index_rodata, objfile::sect_index_text, objfile::section_offsets, set_section_index(), SIZEOF_N_SECTION_OFFSETS, and som_solib_section_offsets().
static void som_symfile_read (struct objfile * objfile, int symfile_flags) [static]
Definition at line 351 of file somread.c.
References do_cleanups(), init_minimal_symbol_collection(), install_minimal_symbols(), make_cleanup_discard_minimal_symbols(), objfile::obfd, objfile::section_offsets, som_symtab_read(), and stabsect_build_psymtabs().
static void som_symtab_read (bfd * abfd, struct objfile * objfile, struct section_offsets * section_offsets) [static]
Definition at line 46 of file somread.c.
References _, ALL_OBJFILE_OSECTIONS, data_offset, do_cleanups(), error(), flags, gdb_bfd_section_index(), gdbarch_addr_bits_remove(), get_objfile_arch(), make_cleanup(), mst_data, mst_file_data, mst_file_text, mst_solib_trampoline, mst_text, objfile::obfd, obj_section_addr, obj_section_endaddr, plongest(), prim_record_minimal_symbol_and_info(), QUIT, stringtab, text_offset, obj_section::the_bfd_section, xfree(), and xmalloc().
Referenced by som_symfile_read().
Variable Documentation
initialize_file_ftype _initialize_somread
Definition at line 550 of file somread.c.
struct sym_fns som_sym_fns [static]
Initial value:
{
  som_new_init,
  som_symfile_init,
  som_symfile_read,
  NULL,
  som_symfile_finish,
  som_symfile_offsets,
  default_symfile_segments,
  NULL,
  default_symfile_relocate,
  NULL,
  &psym_functions
}
Definition at line 535 of file somread.c.