GDB (xrefs): /home/stan/gdb/src/gdb/source.h File Reference
/home/stan/gdb/src/gdb/source.h File Reference
Functions
int find_and_open_source (const char *filename, const char *dirname, char **fullname)
int open_source_file (struct symtab *s)
char * rewrite_source_path (const char *path)
const char * symtab_to_fullname (struct symtab *s)
const char * symtab_to_filename_for_display (struct symtab *symtab)
void find_source_lines (struct symtab *s, int desc)
int get_first_line_listed (void)
int get_lines_to_list (void)
struct symtab_and_line get_current_source_symtab_and_line (void)
void set_default_source_symtab_and_line (void)
struct symtab_and_line set_current_source_symtab_and_line (const struct symtab_and_line *)
void clear_current_source_symtab_and_line (void)
void add_substitute_path_rule (char *, char *)
Function Documentation
void add_substitute_path_rule (char * , char *)
Definition at line 1799 of file source.c.
References substitute_path_rule::from, substitute_path_rule::next, substitute_path_rules, substitute_path_rule::to, and xmalloc().
Referenced by captured_main(), and set_substitute_path_command().
void clear_current_source_symtab_and_line (void)
Definition at line 229 of file source.c.
References current_source_line.
Referenced by clear_symtab_users(), and free_objfile().
int find_and_open_source (const char * filename, const char * dirname, char ** fullname)
Definition at line 993 of file source.c.
References cdir_len, do_cleanups(), gdb_open_cloexec(), gdb_realpath(), len, make_cleanup(), null_cleanup(), OPEN_MODE, openp(), OPF_RETURN_REALPATH, OPF_SEARCH_IN_PATH, p, rewrite_source_path(), source_path, strstr(), and xfree().
Referenced by open_source_file(), psymtab_to_fullname(), and symtab_to_fullname().
void find_source_lines (struct symtab * s, int desc)
Definition at line 1176 of file source.c.
References _, do_cleanups(), exec_bfd, exec_bfd_mtime, gdb_assert, int, symtab::line_charpos, make_cleanup(), objfile::mtime, myread(), symtab::nlines, objfile::obfd, symtab::objfile, p, perror_with_name(), size, symtab_to_filename_for_display(), warning(), xfree(), xmalloc(), and xrealloc().
Referenced by forward_search_command(), gdbtk_load_source(), get_filename_and_charpos(), print_source_lines_base(), reverse_search_command(), and tui_set_source_content().
struct symtab_and_line get_current_source_symtab_and_line (void) [read]
Definition at line 171 of file source.c.
References current_source_line, current_source_pspace, current_source_symtab, symtab_and_line::end, symtab_and_line::line, symtab_and_line::pc, symtab_and_line::pspace, and symtab_and_line::symtab.
Referenced by decode_line_with_current_source(), default_macro_scope(), edit_command(), extract_display_start_addr(), free_objfile(), initialize_defaults(), list_command(), make_visible_with_new_height(), mi_cmd_file_list_exec_source_file(), parse_breakpoint_sals(), parse_exp_in_context_1(), tui_horizontal_source_scroll(), tui_show_source(), and tui_vertical_source_scroll().
int get_first_line_listed (void)
Definition at line 151 of file source.c.
References first_line_listed.
Referenced by list_command().
int get_lines_to_list (void)
Definition at line 162 of file source.c.
References lines_to_list.
Referenced by edit_command(), list_command(), and set_current_sal_from_frame().
int open_source_file (struct symtab * s)
Definition at line 1102 of file source.c.
References symtab::dirname, symtab::filename, find_and_open_source(), and symtab::fullname.
Referenced by forward_search_command(), gdbtk_load_source(), get_filename_and_charpos(), print_source_lines_base(), reverse_search_command(), symtab_to_filename(), and tui_set_source_content().
char* rewrite_source_path (const char * path)
Definition at line 971 of file source.c.
References substitute_path_rule::from, get_substitute_path_rule(), substitute_path_rule::to, and xmalloc().
Referenced by find_and_open_source(), psymtab_to_fullname(), and symtab_to_fullname().
struct symtab_and_line set_current_source_symtab_and_line (const struct symtab_and_line *) [read]
Definition at line 209 of file source.c.
References current_source_line, current_source_pspace, current_source_symtab, symtab_and_line::end, symtab_and_line::line, symtab_and_line::pc, symtab_and_line::pspace, and symtab_and_line::symtab.
Referenced by set_current_sal_from_frame(), tui_show_disassem_and_update_source(), and tui_update_source_window_as_is().
void set_default_source_symtab_and_line (void)
Definition at line 193 of file source.c.
References _, error(), have_full_symbols(), have_partial_symbols(), and select_source_symtab().
Referenced by create_sals_line_offset(), edit_command(), list_command(), and mi_cmd_file_list_exec_source_file().
const char* symtab_to_filename_for_display (struct symtab * symtab)
Definition at line 1158 of file source.c.
References _, symtab::filename, filename_display_absolute, filename_display_basename, filename_display_relative, filename_display_string, internal_error(), and symtab_to_fullname().
Referenced by ambiguous_line_spec(), btrace_func_history_src_line(), build_address_symbolic(), debug_symtab_name(), decode_line_2(), dump_objfile(), dump_symtab_1(), edit_command(), error_in_psymtab_expansion(), find_source_lines(), fixup_go_packaging(), forward_search_command(), frame_info(), ftrace_print_filename(), info_checkpoints_command(), line_info(), list_command(), maintenance_check_symtabs(), maintenance_info_symtabs(), maintenance_print_symbols(), mi_cmd_file_list_exec_source_file(), mi_cmd_file_list_exec_source_files(), print_breakpoint_location(), print_frame(), print_one_static_tracepoint_marker(), print_source_lines_base(), print_symbol_info(), psymtab_to_symtab_1(), rbreak_command(), resolve_sal_pc(), reverse_search_command(), sal_macro_scope(), salpy_str(), say_where(), set_traceframe_context(), stpy_get_filename(), stpy_str(), symtab_symbol_info(), trace_find_line_command(), tui_set_source_content(), update_static_tracepoint(), and user_select_syms().
const char* symtab_to_fullname (struct symtab * s)
Definition at line 1120 of file source.c.
References symtab::dirname, do_cleanups(), symtab::filename, find_and_open_source(), symtab::fullname, make_cleanup(), rewrite_source_path(), and xfree().
Referenced by add_sal_to_sals(), canonical_to_fullform(), clear_command(), convert_linespec_to_sals(), create_sals_line_offset(), edit_command(), find_line_symtab(), ftrace_function_switched(), ftrace_skip_file(), function_name_is_marked_for_skip(), is_known_support_routine(), iterate_over_some_symtabs(), mi_cmd_file_list_exec_source_file(), mi_cmd_file_list_exec_source_files(), print_breakpoint_location(), print_frame(), print_one_static_tracepoint_marker(), print_source_lines_base(), rbreak_command(), search_symbols(), skip_file_command(), sources_info(), stpy_fullname(), symtab_to_filename_for_display(), tui_display_main(), tui_set_source_content(), tui_show_disassem_and_update_source(), tui_show_frame_info(), tui_update_breakpoint_info(), update_static_tracepoint(), and VEC().