GDB (xrefs): /home/stan/gdb/src/gdb/sparc-sol2-tdep.c File Reference
/home/stan/gdb/src/gdb/sparc-sol2-tdep.c File Reference
#include "defs.h"
#include "frame.h"
#include "frame-unwind.h"
#include "gdbcore.h"
#include "symtab.h"
#include "objfiles.h"
#include "osabi.h"
#include "regcache.h"
#include "target.h"
#include "trad-frame.h"
#include "gdb_assert.h"
#include "gdb_string.h"
#include "sol2-tdep.h"
#include "sparc-tdep.h"
#include "solib-svr4.h"
Functions
int sparc_sol2_pc_in_sigtramp (CORE_ADDR pc, const char *name)
static struct sparc_frame_cache * sparc32_sol2_sigtramp_frame_cache (struct frame_info *this_frame, void **this_cache)
static void sparc32_sol2_sigtramp_frame_this_id (struct frame_info *this_frame, void **this_cache, struct frame_id *this_id)
static struct value * sparc32_sol2_sigtramp_frame_prev_register (struct frame_info *this_frame, void **this_cache, int regnum)
static int sparc32_sol2_sigtramp_frame_sniffer (const struct frame_unwind *self, struct frame_info *this_frame, void **this_cache)
const const char * sparc_sol2_static_transform_name (const char *name)
void sparc32_sol2_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
void _initialize_sparc_sol2_tdep (void)
Variables
struct sparc_gregset sparc32_sol2_gregset
struct sparc_fpregset sparc32_sol2_fpregset
static struct frame_unwind sparc32_sol2_sigtramp_frame_unwind
Function Documentation
void _initialize_sparc_sol2_tdep (void)
void sparc32_sol2_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch)
Definition at line 213 of file sparc-sol2-tdep.c.
References find_solib_trampoline_target(), frame_unwind_append_unwinder(), gdbarch_tdep(), gdbarch_tdep::plt_entry_size, set_gdbarch_core_pid_to_str(), set_gdbarch_skip_solib_resolver(), set_gdbarch_skip_trampoline_code(), set_gdbarch_software_single_step(), set_gdbarch_sofun_address_maybe_missing(), set_gdbarch_static_transform_name(), set_solib_svr4_fetch_link_map_offsets(), sol2_core_pid_to_str(), sol2_skip_solib_resolver(), sparc_sol2_static_transform_name(), and svr4_ilp32_fetch_link_map_offsets().
static struct sparc_frame_cache* sparc32_sol2_sigtramp_frame_cache (struct frame_info * this_frame, void ** this_cache) [static, read]
Definition at line 83 of file sparc-sol2-tdep.c.
References trad_frame_saved_reg::addr, sparc_frame_cache::copied_regs_mask, gdb_assert, get_frame_memory_unsigned(), get_frame_register_unsigned(), regnum, sparc_frame_cache::saved_regs, SPARC32_NPC_REGNUM, SPARC32_PC_REGNUM, SPARC32_PSR_REGNUM, SPARC32_Y_REGNUM, sparc_frame_cache(), SPARC_G1_REGNUM, SPARC_I2_REGNUM, SPARC_I7_REGNUM, SPARC_L0_REGNUM, SPARC_O2_REGNUM, SPARC_O7_REGNUM, SPARC_SP_REGNUM, trad_frame_alloc_saved_regs(), and trad_frame_set_unknown().
Referenced by sparc32_sol2_sigtramp_frame_prev_register(), and sparc32_sol2_sigtramp_frame_this_id().
static struct value* sparc32_sol2_sigtramp_frame_prev_register (struct frame_info * this_frame, void ** this_cache, int regnum) [static, read]
Definition at line 145 of file sparc-sol2-tdep.c.
References sparc_frame_cache::saved_regs, sparc32_sol2_sigtramp_frame_cache(), and trad_frame_get_prev_register().
static int sparc32_sol2_sigtramp_frame_sniffer (const struct frame_unwind * self, struct frame_info * this_frame, void ** this_cache) [static]
Definition at line 156 of file sparc-sol2-tdep.c.
References find_pc_partial_function(), get_frame_pc(), name, sparc_frame_cache::pc, and sparc_sol2_pc_in_sigtramp().
static void sparc32_sol2_sigtramp_frame_this_id (struct frame_info * this_frame, void ** this_cache, struct frame_id * this_id) [static]
Definition at line 134 of file sparc-sol2-tdep.c.
References sparc_frame_cache::base, frame_id_build(), sparc_frame_cache::pc, and sparc32_sol2_sigtramp_frame_cache().
int sparc_sol2_pc_in_sigtramp (CORE_ADDR pc, const char * name)
Definition at line 75 of file sparc-sol2-tdep.c.
Referenced by sparc32_sol2_sigtramp_frame_sniffer(), and sparc64_sol2_sigtramp_frame_sniffer().
const const char* sparc_sol2_static_transform_name (const char * name)
Definition at line 183 of file sparc-sol2-tdep.c.
References name, p, and strrchr().
Referenced by sparc32_sol2_init_abi(), and sparc64_sol2_init_abi().
Variable Documentation
struct sparc_fpregset sparc32_sol2_fpregset
Initial value:
{
  0 * 4,
  33 * 4,
}
Definition at line 51 of file sparc-sol2-tdep.c.
struct sparc_gregset sparc32_sol2_gregset
Initial value:
{
  32 * 4,
  33 * 4,
  34 * 4,
  35 * 4,
  36 * 4,
  37 * 4,
  1 * 4,
  16 * 4,
}
Definition at line 39 of file sparc-sol2-tdep.c.
struct frame_unwind sparc32_sol2_sigtramp_frame_unwind [static]
Initial value:
{
  SIGTRAMP_FRAME,
  default_frame_unwind_stop_reason,
  sparc32_sol2_sigtramp_frame_this_id,
  sparc32_sol2_sigtramp_frame_prev_register,
  NULL,
  sparc32_sol2_sigtramp_frame_sniffer
}
Definition at line 170 of file sparc-sol2-tdep.c.