GDB (xrefs): /home/stan/gdb/src/gdb/sparcnbsd-nat.c File Reference
/home/stan/gdb/src/gdb/sparcnbsd-nat.c File Reference
#include "defs.h"
#include "regcache.h"
#include "target.h"
#include "sparc-tdep.h"
#include "sparc-nat.h"
#include <sys/types.h>
#include <machine/pcb.h>
#include "bsd-kvm.h"
Functions
static int sparc32nbsd_supply_pcb (struct regcache *regcache, struct pcb *pcb)
void _initialize_sparcnbsd_nat (void)
Function Documentation
void _initialize_sparcnbsd_nat (void)
Definition at line 63 of file sparcnbsd-nat.c.
References add_target(), bsd_kvm_add_target(), sparc32_bsd_fpregset, sparc32nbsd_gregset, sparc32nbsd_supply_pcb(), and sparc_target().
static int sparc32nbsd_supply_pcb (struct regcache * regcache, struct pcb * pcb) [static]
Definition at line 35 of file sparcnbsd-nat.c.
References regcache_raw_supply(), SPARC32_PC_REGNUM, SPARC32_PSR_REGNUM, SPARC32_WIM_REGNUM, SPARC_O7_REGNUM, SPARC_SP_REGNUM, and sparc_supply_rwindow().
Referenced by _initialize_sparcnbsd_nat().