GDB (xrefs): /home/stan/gdb/src/gdb/sparc64-linux-tdep.c File Reference
/home/stan/gdb/src/gdb/sparc64-linux-tdep.c File Reference
#include "defs.h"
#include "frame.h"
#include "frame-unwind.h"
#include "dwarf2-frame.h"
#include "regset.h"
#include "regcache.h"
#include "gdbarch.h"
#include "gdbcore.h"
#include "osabi.h"
#include "solib-svr4.h"
#include "symtab.h"
#include "trad-frame.h"
#include "tramp-frame.h"
#include "xml-syscall.h"
#include "linux-tdep.h"
#include "sparc64-tdep.h"
Defines
#define XML_SYSCALL_FILENAME_SPARC64 "syscalls/sparc64-linux.xml"
#define TSTATE_SYSCALL 0x0000000000000020ULL
Functions
static void sparc64_linux_sigframe_init (const struct tramp_frame *self, struct frame_info *this_frame, struct trad_frame_cache *this_cache, CORE_ADDR func)
static CORE_ADDR sparc64_linux_step_trap (struct frame_info *frame, unsigned long insn)
static void sparc64_linux_supply_core_gregset (const struct regset *regset, struct regcache *regcache, int regnum, const void *gregs, size_t len)
static void sparc64_linux_collect_core_gregset (const struct regset *regset, const struct regcache *regcache, int regnum, void *gregs, size_t len)
static void sparc64_linux_supply_core_fpregset (const struct regset *regset, struct regcache *regcache, int regnum, const void *fpregs, size_t len)
static void sparc64_linux_collect_core_fpregset (const struct regset *regset, const struct regcache *regcache, int regnum, void *fpregs, size_t len)
static void sparc64_linux_write_pc (struct regcache *regcache, CORE_ADDR pc)
static LONGEST sparc64_linux_get_syscall_number (struct gdbarch *gdbarch, ptid_t ptid)
static void sparc64_linux_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
void _initialize_sparc64_linux_tdep (void)
Variables
static struct tramp_frame sparc64_linux_rt_sigframe
struct sparc_gregset sparc64_linux_core_gregset
Define Documentation
#define TSTATE_SYSCALL 0x0000000000000020ULL
Definition at line 190 of file sparc64-linux-tdep.c.
Referenced by sparc64_linux_write_pc().
#define XML_SYSCALL_FILENAME_SPARC64 "syscalls/sparc64-linux.xml"
Definition at line 37 of file sparc64-linux-tdep.c.
Referenced by sparc64_linux_init_abi().
Function Documentation
void _initialize_sparc64_linux_tdep (void)
Definition at line 288 of file sparc64-linux-tdep.c.
References GDB_OSABI_LINUX, gdbarch_register_osabi(), and sparc64_linux_init_abi().
static void sparc64_linux_collect_core_fpregset (const struct regset * regset, const struct regcache * regcache, int regnum, void * fpregs, size_t len) [static]
Definition at line 181 of file sparc64-linux-tdep.c.
References sparc64_bsd_fpregset, and sparc64_collect_fpregset().
Referenced by sparc64_linux_init_abi().
static void sparc64_linux_collect_core_gregset (const struct regset * regset, const struct regcache * regcache, int regnum, void * gregs, size_t len) [static]
Definition at line 164 of file sparc64-linux-tdep.c.
References sparc64_collect_gregset().
Referenced by sparc64_linux_init_abi().
static LONGEST sparc64_linux_get_syscall_number (struct gdbarch * gdbarch, ptid_t ptid) [static]
Definition at line 215 of file sparc64-linux-tdep.c.
References extract_signed_integer(), gdbarch_byte_order(), get_thread_regcache(), LONGEST, regcache_cooked_read(), and SPARC_G1_REGNUM.
Referenced by sparc64_linux_init_abi().
static void sparc64_linux_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch) [static]
Definition at line 238 of file sparc64-linux-tdep.c.
References dwarf2_append_unwinders(), find_solib_trampoline_target(), gdbarch_tdep::fpregset, gdbarch_tdep(), gdbarch_tdep::gregset, linux_init_abi(), gdbarch_tdep::plt_entry_size, regset_alloc(), set_gdbarch_fetch_tls_load_module_address(), set_gdbarch_get_syscall_number(), set_gdbarch_skip_trampoline_code(), set_gdbarch_write_pc(), set_solib_svr4_fetch_link_map_offsets(), set_xml_syscall_file_name(), gdbarch_tdep::sizeof_fpregset, gdbarch_tdep::sizeof_gregset, sparc64_init_abi(), sparc64_linux_collect_core_fpregset(), sparc64_linux_collect_core_gregset(), sparc64_linux_get_syscall_number(), sparc64_linux_step_trap(), sparc64_linux_supply_core_fpregset(), sparc64_linux_supply_core_gregset(), sparc64_linux_write_pc(), gdbarch_tdep::step_trap, svr4_fetch_objfile_link_map(), svr4_lp64_fetch_link_map_offsets(), tramp_frame_prepend_unwinder(), and XML_SYSCALL_FILENAME_SPARC64.
Referenced by _initialize_sparc64_linux_tdep().
static void sparc64_linux_sigframe_init (const struct tramp_frame * self, struct frame_info * this_frame, struct trad_frame_cache * this_cache, CORE_ADDR func) [static]
Definition at line 64 of file sparc64-linux-tdep.c.
References BIAS, frame_id_build(), get_frame_memory_unsigned(), get_frame_register_unsigned(), regnum, SPARC64_FPRS_REGNUM, SPARC64_NPC_REGNUM, SPARC64_PC_REGNUM, SPARC64_STATE_REGNUM, SPARC64_Y_REGNUM, SPARC_G0_REGNUM, SPARC_G1_REGNUM, SPARC_I7_REGNUM, SPARC_L0_REGNUM, SPARC_O1_REGNUM, SPARC_O7_REGNUM, SPARC_SP_REGNUM, trad_frame_set_id(), and trad_frame_set_reg_addr().
static CORE_ADDR sparc64_linux_step_trap (struct frame_info * frame, unsigned long insn) [static]
Definition at line 112 of file sparc64-linux-tdep.c.
References BIAS, gdbarch::byte_order, gdbarch_byte_order(), get_frame_arch(), get_frame_register_unsigned(), read_memory_unsigned_integer(), sp, SPARC_SP_REGNUM, and ULONGEST.
Referenced by sparc64_linux_init_abi().
static void sparc64_linux_supply_core_fpregset (const struct regset * regset, struct regcache * regcache, int regnum, const void * fpregs, size_t len) [static]
Definition at line 173 of file sparc64-linux-tdep.c.
References sparc64_bsd_fpregset, and sparc64_supply_fpregset().
Referenced by sparc64_linux_init_abi().
static void sparc64_linux_supply_core_gregset (const struct regset * regset, struct regcache * regcache, int regnum, const void * gregs, size_t len) [static]
Definition at line 155 of file sparc64-linux-tdep.c.
References sparc64_supply_gregset().
Referenced by sparc64_linux_init_abi().
static void sparc64_linux_write_pc (struct regcache * regcache, CORE_ADDR pc) [static]
Definition at line 193 of file sparc64-linux-tdep.c.
References gdbarch_tdep(), get_regcache_arch(), gdbarch_tdep::npc_regnum, gdbarch_tdep::pc_regnum, regcache_cooked_read_unsigned(), regcache_cooked_write_unsigned(), SPARC64_STATE_REGNUM, TSTATE_SYSCALL, and ULONGEST.
Referenced by sparc64_linux_init_abi().
Variable Documentation
struct sparc_gregset sparc64_linux_core_gregset
Initial value:
{
  32 * 8,
  33 * 8,
  34 * 8,
  35 * 8,
  -1,
  -1,
  1 * 8,
  16 * 8,
  8,
}
Definition at line 140 of file sparc64-linux-tdep.c.
struct tramp_frame sparc64_linux_rt_sigframe [static]
Initial value:
{
  SIGTRAMP_FRAME,
  4,
  {
    { 0x82102065, -1 },
    { 0x91d0206d, -1 },
    { TRAMP_SENTINEL_INSN, -1 }
  },
  sparc64_linux_sigframe_init
}
Definition at line 51 of file sparc64-linux-tdep.c.