GDB (xrefs): /home/stan/gdb/src/gdb/sparc64fbsd-nat.c File Reference
/home/stan/gdb/src/gdb/sparc64fbsd-nat.c File Reference
#include "defs.h"
#include "regcache.h"
#include "target.h"
#include "fbsd-nat.h"
#include "sparc64-tdep.h"
#include "sparc-nat.h"
#include <sys/types.h>
#include <machine/pcb.h>
#include "bsd-kvm.h"
Functions
static int sparc64fbsd_kvm_supply_pcb (struct regcache *regcache, struct pcb *pcb)
void _initialize_sparc64fbsd_nat (void)
Function Documentation
void _initialize_sparc64fbsd_nat (void)
Definition at line 67 of file sparc64fbsd-nat.c.
References add_target(), bsd_kvm_add_target(), fbsd_find_memory_regions(), fbsd_make_corefile_notes(), fbsd_pid_to_exec_file(), sparc64fbsd_gregset, sparc64fbsd_kvm_supply_pcb(), sparc_target(), target_ops::to_find_memory_regions, target_ops::to_make_corefile_notes, and target_ops::to_pid_to_exec_file.
static int sparc64fbsd_kvm_supply_pcb (struct regcache * regcache, struct pcb * pcb) [static]
Definition at line 37 of file sparc64fbsd-nat.c.
References regcache_raw_supply(), SPARC64_NPC_REGNUM, SPARC64_PC_REGNUM, SPARC_SP_REGNUM, and sparc_supply_rwindow().
Referenced by _initialize_sparc64fbsd_nat().