GDB (xrefs): /home/stan/gdb/src/gdb/sparc64-tdep.h File Reference
/home/stan/gdb/src/gdb/sparc64-tdep.h File Reference
#include "sparc-tdep.h"
Defines
#define BIAS 2047
#define r_tstate_offset r_psr_offset
#define r_fprs_offset r_wim_offset
#define SPARC64_PSTATE_AG 0x001
#define SPARC64_PSTATE_IE 0x002
#define SPARC64_PSTATE_PRIV 0x004
#define SPARC64_PSTATE_AM 0x008
#define SPARC64_PSTATE_PEF 0x010
#define SPARC64_PSTATE_RED 0x020
#define SPARC64_PSTATE_TLE 0x100
#define SPARC64_PSTATE_CLE 0x200
#define SPARC64_PSTATE_PID0 0x400
#define SPARC64_PSTATE_PID1 0x800
Enumerations
enum sparc64_regnum {
SPARC64_F32_REGNUM = SPARC_F0_REGNUM + 32, SPARC64_F62_REGNUM = SPARC64_F32_REGNUM + 15, SPARC64_PC_REGNUM, SPARC64_NPC_REGNUM,
SPARC64_STATE_REGNUM, SPARC64_FSR_REGNUM, SPARC64_FPRS_REGNUM, SPARC64_Y_REGNUM,
SPARC64_CWP_REGNUM, SPARC64_PSTATE_REGNUM, SPARC64_ASI_REGNUM, SPARC64_CCR_REGNUM,
SPARC64_D0_REGNUM, SPARC64_D10_REGNUM = SPARC64_D0_REGNUM + 5, SPARC64_D30_REGNUM = SPARC64_D0_REGNUM + 15, SPARC64_D32_REGNUM = SPARC64_D0_REGNUM + 16,
SPARC64_D62_REGNUM = SPARC64_D0_REGNUM + 31, SPARC64_Q0_REGNUM, SPARC64_Q8_REGNUM = SPARC64_Q0_REGNUM + 2, SPARC64_Q28_REGNUM = SPARC64_Q0_REGNUM + 7,
SPARC64_Q32_REGNUM = SPARC64_Q0_REGNUM + 8, SPARC64_Q60_REGNUM = SPARC64_Q0_REGNUM + 15
}
Functions
void sparc64_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
void sparc64_supply_gregset (const struct sparc_gregset *gregset, struct regcache *regcache, int regnum, const void *gregs)
void sparc64_collect_gregset (const struct sparc_gregset *gregset, const struct regcache *regcache, int regnum, void *gregs)
void sparc64_supply_fpregset (const struct sparc_fpregset *fpregset, struct regcache *regcache, int regnum, const void *fpregs)
void sparc64_collect_fpregset (const struct sparc_fpregset *fpregset, const struct regcache *regcache, int regnum, void *fpregs)
void sparc64_sol2_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
struct trad_frame_saved_reg * sparc64nbsd_sigcontext_saved_regs (CORE_ADDR sigcontext_addr, struct frame_info *next_frame)
Variables
struct sparc_gregset sparc64_sol2_gregset
struct sparc_fpregset sparc64_sol2_fpregset
struct sparc_gregset sparc64fbsd_gregset
struct sparc_gregset sparc64nbsd_gregset
struct sparc_fpregset sparc64_bsd_fpregset
Define Documentation
#define BIAS 2047
Definition at line 35 of file sparc64-tdep.h.
#define r_fprs_offset r_wim_offset
Definition at line 43 of file sparc64-tdep.h.
#define r_tstate_offset r_psr_offset
Definition at line 40 of file sparc64-tdep.h.
#define SPARC64_PSTATE_AG 0x001
Definition at line 86 of file sparc64-tdep.h.
#define SPARC64_PSTATE_AM 0x008
Definition at line 89 of file sparc64-tdep.h.
#define SPARC64_PSTATE_CLE 0x200
Definition at line 93 of file sparc64-tdep.h.
#define SPARC64_PSTATE_IE 0x002
Definition at line 87 of file sparc64-tdep.h.
#define SPARC64_PSTATE_PEF 0x010
Definition at line 90 of file sparc64-tdep.h.
#define SPARC64_PSTATE_PID0 0x400
Definition at line 94 of file sparc64-tdep.h.
#define SPARC64_PSTATE_PID1 0x800
Definition at line 95 of file sparc64-tdep.h.
#define SPARC64_PSTATE_PRIV 0x004
Definition at line 88 of file sparc64-tdep.h.
Referenced by sparc64obsd_trapframe_sniffer().
#define SPARC64_PSTATE_RED 0x020
Definition at line 91 of file sparc64-tdep.h.
#define SPARC64_PSTATE_TLE 0x100
Definition at line 92 of file sparc64-tdep.h.
Enumeration Type Documentation
enum sparc64_regnum
Enumerator:
SPARC64_F32_REGNUM
SPARC64_F62_REGNUM
SPARC64_PC_REGNUM
SPARC64_NPC_REGNUM
SPARC64_STATE_REGNUM
SPARC64_FSR_REGNUM
SPARC64_FPRS_REGNUM
SPARC64_Y_REGNUM
SPARC64_CWP_REGNUM
SPARC64_PSTATE_REGNUM
SPARC64_ASI_REGNUM
SPARC64_CCR_REGNUM
SPARC64_D0_REGNUM
SPARC64_D10_REGNUM
SPARC64_D30_REGNUM
SPARC64_D32_REGNUM
SPARC64_D62_REGNUM
SPARC64_Q0_REGNUM
SPARC64_Q8_REGNUM
SPARC64_Q28_REGNUM
SPARC64_Q32_REGNUM
SPARC64_Q60_REGNUM
Definition at line 47 of file sparc64-tdep.h.
Function Documentation
void sparc64_collect_fpregset (const struct sparc_fpregset * fpregset, const struct regcache * regcache, int regnum, void * fpregs)
Definition at line 1489 of file sparc64-tdep.c.
References gdbarch_ptr_bit(), get_regcache_arch(), sparc_fpregset::r_f0_offset, sparc_fpregset::r_fsr_offset, regcache_raw_collect(), SPARC32_FSR_REGNUM, SPARC64_F32_REGNUM, SPARC64_FSR_REGNUM, and SPARC_F0_REGNUM.
Referenced by _initialize_sparc64_nat(), fill_fpregset(), sparc64_linux_collect_core_fpregset(), sparc64fbsd_collect_fpregset(), and sparc64nbsd_collect_fpregset().
void sparc64_collect_gregset (const struct sparc_gregset * gregset, const struct regcache * regcache, int regnum, void * gregs)
Definition at line 1341 of file sparc64-tdep.c.
References gdbarch::byte_order, extract_unsigned_integer(), gdbarch_byte_order(), gdbarch_ptr_bit(), get_regcache_arch(), memcpy(), offset, PSR_ICC, PSR_IMPL, PSR_V8PLUS, PSR_VERS, PSR_XCC, sparc_gregset::r_g1_offset, sparc_gregset::r_l0_offset, sparc_gregset::r_npc_offset, sparc_gregset::r_pc_offset, sparc_gregset::r_y_offset, sparc_gregset::r_y_size, regcache_raw_collect(), SPARC32_NPC_REGNUM, SPARC32_PC_REGNUM, SPARC32_PSR_REGNUM, SPARC32_Y_REGNUM, SPARC64_FPRS_REGNUM, SPARC64_NPC_REGNUM, SPARC64_PC_REGNUM, SPARC64_STATE_REGNUM, SPARC64_Y_REGNUM, SPARC_G1_REGNUM, SPARC_I7_REGNUM, SPARC_L0_REGNUM, SPARC_O7_REGNUM, store_unsigned_integer(), and ULONGEST.
Referenced by _initialize_sparc64_nat(), fill_gregset(), sparc64_linux_collect_core_gregset(), sparc64fbsd_collect_gregset(), and sparc64nbsd_collect_gregset().
void sparc64_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch)
Definition at line 1166 of file sparc64-tdep.c.
References AT_ENTRY_POINT, default_stabs_argument_has_addr(), dwarf2_frame_set_init_reg(), frame_base_set_default(), frame_unwind_append_unwinder(), gdbarch_tdep(), gdbarch_tdep::npc_regnum, gdbarch_tdep::pc_regnum, set_gdbarch_call_dummy_location(), set_gdbarch_frame_align(), set_gdbarch_long_bit(), set_gdbarch_long_long_bit(), set_gdbarch_num_pseudo_regs(), set_gdbarch_num_regs(), set_gdbarch_pc_regnum(), set_gdbarch_pseudo_register_read(), set_gdbarch_pseudo_register_write(), set_gdbarch_ptr_bit(), set_gdbarch_push_dummy_call(), set_gdbarch_push_dummy_code(), set_gdbarch_register_name(), set_gdbarch_register_type(), set_gdbarch_return_value(), set_gdbarch_skip_prologue(), set_gdbarch_stabs_argument_has_addr(), sparc64_dwarf2_frame_init_reg(), sparc64_frame_align(), SPARC64_NPC_REGNUM, SPARC64_NUM_PSEUDO_REGS, SPARC64_NUM_REGS, SPARC64_PC_REGNUM, sparc64_pseudo_register_read(), sparc64_pseudo_register_write(), sparc64_push_dummy_call(), sparc64_register_name(), sparc64_register_type(), sparc64_return_value(), and sparc64_skip_prologue().
Referenced by sparc64_linux_init_abi(), sparc64_sol2_init_abi(), sparc64fbsd_init_abi(), sparc64nbsd_init_abi(), and sparc64obsd_init_abi().
void sparc64_sol2_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch)
Definition at line 160 of file sparc64-sol2-tdep.c.
References find_solib_trampoline_target(), frame_unwind_append_unwinder(), gdbarch_tdep(), gdbarch_tdep::plt_entry_size, set_gdbarch_core_pid_to_str(), set_gdbarch_skip_solib_resolver(), set_gdbarch_skip_trampoline_code(), set_gdbarch_software_single_step(), set_gdbarch_sofun_address_maybe_missing(), set_gdbarch_static_transform_name(), set_solib_svr4_fetch_link_map_offsets(), sol2_core_pid_to_str(), sol2_skip_solib_resolver(), sparc64_init_abi(), sparc_sol2_static_transform_name(), and svr4_lp64_fetch_link_map_offsets().
Referenced by _initialize_sparc64_sol2_tdep().
void sparc64_supply_fpregset (const struct sparc_fpregset * fpregset, struct regcache * regcache, int regnum, const void * fpregs)
Definition at line 1451 of file sparc64-tdep.c.
References gdbarch_ptr_bit(), get_regcache_arch(), sparc_fpregset::r_f0_offset, sparc_fpregset::r_fsr_offset, regcache_raw_supply(), SPARC32_FSR_REGNUM, SPARC64_F32_REGNUM, SPARC64_FSR_REGNUM, and SPARC_F0_REGNUM.
Referenced by _initialize_sparc64_nat(), sparc64_linux_supply_core_fpregset(), sparc64fbsd_supply_fpregset(), sparc64nbsd_supply_fpregset(), sparc64obsd_supply_gregset(), and supply_fpregset().
void sparc64_supply_gregset (const struct sparc_gregset * gregset, struct regcache * regcache, int regnum, const void * gregs)
Definition at line 1224 of file sparc64-tdep.c.
References gdbarch::byte_order, extract_unsigned_integer(), gdbarch_byte_order(), gdbarch_ptr_bit(), get_regcache_arch(), memcpy(), memset(), offset, PSR_S, PSR_V8PLUS, sparc_gregset::r_g1_offset, sparc_gregset::r_l0_offset, sparc_gregset::r_npc_offset, sparc_gregset::r_pc_offset, sparc_gregset::r_y_offset, sparc_gregset::r_y_size, regcache_cooked_read_unsigned(), regcache_raw_supply(), sp, SPARC32_NPC_REGNUM, SPARC32_PC_REGNUM, SPARC32_PSR_REGNUM, SPARC32_Y_REGNUM, SPARC64_FPRS_REGNUM, SPARC64_NPC_REGNUM, SPARC64_PC_REGNUM, SPARC64_STATE_REGNUM, SPARC64_Y_REGNUM, SPARC_G0_REGNUM, SPARC_G1_REGNUM, SPARC_I7_REGNUM, SPARC_L0_REGNUM, SPARC_O7_REGNUM, SPARC_SP_REGNUM, sparc_supply_rwindow(), store_unsigned_integer(), TSTATE_CWP, TSTATE_ICC, TSTATE_XCC, and ULONGEST.
Referenced by _initialize_sparc64_nat(), sparc64_linux_supply_core_gregset(), sparc64fbsd_supply_gregset(), sparc64nbsd_supply_gregset(), sparc64obsd_supply_gregset(), and supply_gregset().
struct trad_frame_saved_reg* sparc64nbsd_sigcontext_saved_regs (CORE_ADDR sigcontext_addr, struct frame_info * next_frame) [read]
Definition at line 91 of file sparc64nbsd-tdep.c.
References trad_frame_saved_reg::addr, BIAS, get_frame_arch(), get_frame_memory_unsigned(), trad_frame_saved_reg::realreg, regnum, sp, SPARC64_NPC_REGNUM, SPARC64_PC_REGNUM, SPARC64_STATE_REGNUM, SPARC64_Y_REGNUM, sparc_fetch_wcookie(), SPARC_G0_REGNUM, SPARC_G1_REGNUM, SPARC_G2_REGNUM, SPARC_G7_REGNUM, SPARC_I0_REGNUM, SPARC_I7_REGNUM, SPARC_L0_REGNUM, SPARC_L1_REGNUM, SPARC_O0_REGNUM, SPARC_O1_REGNUM, SPARC_O5_REGNUM, SPARC_O7_REGNUM, SPARC_SP_REGNUM, trad_frame_alloc_saved_regs(), trad_frame_set_value(), and ULONGEST.
Referenced by sparc64nbsd_sigcontext_frame_cache(), and sparc64obsd_frame_cache().
Variable Documentation
struct sparc_fpregset sparc64_bsd_fpregset
Definition at line 1526 of file sparc64-tdep.c.
Referenced by fill_fpregset(), sparc64_linux_collect_core_fpregset(), sparc64_linux_supply_core_fpregset(), sparc64fbsd_collect_fpregset(), sparc64fbsd_supply_fpregset(), sparc64nbsd_collect_fpregset(), sparc64nbsd_supply_fpregset(), sparc64obsd_supply_gregset(), and supply_fpregset().
struct sparc_fpregset sparc64_sol2_fpregset
Definition at line 49 of file sparc64-sol2-tdep.c.
struct sparc_gregset sparc64_sol2_gregset
Definition at line 36 of file sparc64-sol2-tdep.c.
struct sparc_gregset sparc64fbsd_gregset
Definition at line 37 of file sparc64fbsd-tdep.c.
Referenced by _initialize_sparc64fbsd_nat().
struct sparc_gregset sparc64nbsd_gregset
Definition at line 40 of file sparc64nbsd-tdep.c.
Referenced by sparc64nbsd_collect_gregset(), and sparc64nbsd_supply_gregset().