GDB (xrefs): /home/stan/gdb/src/gdb/sparc-nat.h File Reference
/home/stan/gdb/src/gdb/sparc-nat.h File Reference
Functions
int sparc32_gregset_supplies_p (struct gdbarch *gdbarch, int regnum)
int sparc32_fpregset_supplies_p (struct gdbarch *gdbarch, int regnum)
struct target_ops * sparc_target (void)
void sparc_fetch_inferior_registers (struct target_ops *, struct regcache *, int)
void sparc_store_inferior_registers (struct target_ops *, struct regcache *, int)
Variables
struct sparc_gregset * sparc_gregset
struct sparc_fpregset * sparc_fpregset
void(* sparc_supply_gregset)(const struct sparc_gregset *, struct regcache *, int, const void *)
void(* sparc_collect_gregset)(const struct sparc_gregset *, const struct regcache *, int, void *)
void(* sparc_supply_fpregset)(const struct sparc_fpregset *, struct regcache *, int, const void *)
void(* sparc_collect_fpregset)(const struct sparc_fpregset *, const struct regcache *, int, void *)
int(* sparc_gregset_supplies_p)(struct gdbarch *gdbarch, int)
int(* sparc_fpregset_supplies_p)(struct gdbarch *gdbarch, int)
Function Documentation
int sparc32_fpregset_supplies_p (struct gdbarch * gdbarch, int regnum)
Definition at line 122 of file sparc-nat.c.
References SPARC32_FSR_REGNUM, SPARC_F0_REGNUM, and SPARC_F31_REGNUM.
Referenced by _initialize_sparc_nat(), sparc64_fpregset_supplies_p(), and sparc64nbsd_fpregset_supplies_p().
int sparc32_gregset_supplies_p (struct gdbarch * gdbarch, int regnum)
Definition at line 100 of file sparc-nat.c.
References SPARC32_NPC_REGNUM, SPARC32_PC_REGNUM, SPARC32_PSR_REGNUM, SPARC32_Y_REGNUM, SPARC_G1_REGNUM, SPARC_G7_REGNUM, SPARC_I0_REGNUM, SPARC_I7_REGNUM, SPARC_L0_REGNUM, SPARC_L7_REGNUM, SPARC_O0_REGNUM, and SPARC_O7_REGNUM.
Referenced by _initialize_sparc_nat(), sparc64_gregset_supplies_p(), and sparc64nbsd_gregset_supplies_p().
void sparc_fetch_inferior_registers (struct target_ops * , struct regcache * , int)
Definition at line 139 of file sparc-nat.c.
References _, get_regcache_arch(), inferior_ptid, perror_with_name(), ptid_get_lwp(), ptid_get_pid(), ptrace(), PTRACE_GETFPREGS, PTRACE_GETREGS, PTRACE_TYPE_ARG3, regcache_raw_supply(), sparc_fpregset_supplies_p, SPARC_G0_REGNUM, sparc_gregset_supplies_p, sparc_supply_fpregset, and sparc_supply_gregset.
Referenced by _initialize_sparc64_linux_nat(), _initialize_sparc_linux_nat(), and sparc_target().
void sparc_store_inferior_registers (struct target_ops * , struct regcache * , int)
Definition at line 194 of file sparc-nat.c.
References _, get_regcache_arch(), inferior_ptid, memcmp(), memcpy(), perror_with_name(), ptid_get_lwp(), ptid_get_pid(), ptrace(), PTRACE_GETFPREGS, PTRACE_GETREGS, PTRACE_SETFPREGS, PTRACE_SETREGS, PTRACE_TYPE_ARG3, regcache_cooked_read_unsigned(), sp, sparc_collect_fpregset, sparc_collect_gregset, sparc_collect_rwindow(), sparc_fpregset_supplies_p, sparc_gregset_supplies_p, SPARC_I7_REGNUM, SPARC_L0_REGNUM, SPARC_SP_REGNUM, and ULONGEST.
Referenced by _initialize_sparc64_linux_nat(), _initialize_sparc_linux_nat(), and sparc_target().
struct target_ops* sparc_target (void) [read]
Definition at line 337 of file sparc-nat.c.
References inf_ptrace_target(), inf_ptrace_xfer_partial, sparc_fetch_inferior_registers(), sparc_store_inferior_registers(), sparc_xfer_partial(), target_ops::to_fetch_registers, target_ops::to_store_registers, and target_ops::to_xfer_partial.
Referenced by _initialize_sparc64fbsd_nat(), _initialize_sparc64nbsd_nat(), and _initialize_sparcnbsd_nat().
Variable Documentation
void(* sparc_collect_fpregset)(const struct sparc_fpregset *, const struct regcache *, int, void *)
Definition at line 92 of file sparc-nat.c.
void(* sparc_collect_gregset)(const struct sparc_gregset *, const struct regcache *, int, void *)
Definition at line 88 of file sparc-nat.c.
struct sparc_fpregset* sparc_fpregset
Definition at line 85 of file sparc-nat.c.
int(* sparc_fpregset_supplies_p)(struct gdbarch *gdbarch, int)
Definition at line 95 of file sparc-nat.c.
Referenced by _initialize_sparc64_nat(), _initialize_sparc64nbsd_nat(), _initialize_sparc_nat(), sparc_fetch_inferior_registers(), and sparc_store_inferior_registers().
struct sparc_gregset* sparc_gregset
Definition at line 84 of file sparc-nat.c.
int(* sparc_gregset_supplies_p)(struct gdbarch *gdbarch, int)
Definition at line 94 of file sparc-nat.c.
Referenced by _initialize_sparc64_nat(), _initialize_sparc64nbsd_nat(), _initialize_sparc_nat(), sparc_fetch_inferior_registers(), and sparc_store_inferior_registers().
void(* sparc_supply_fpregset)(const struct sparc_fpregset *, struct regcache *, int, const void *)
Definition at line 90 of file sparc-nat.c.
void(* sparc_supply_gregset)(const struct sparc_gregset *, struct regcache *, int, const void *)
Definition at line 86 of file sparc-nat.c.