GDB (xrefs): /home/stan/gdb/src/gdb/sparc64fbsd-tdep.c File Reference
/home/stan/gdb/src/gdb/sparc64fbsd-tdep.c File Reference
#include "defs.h"
#include "frame.h"
#include "frame-unwind.h"
#include "gdbcore.h"
#include "osabi.h"
#include "regcache.h"
#include "regset.h"
#include "target.h"
#include "trad-frame.h"
#include "gdb_assert.h"
#include "gdb_string.h"
#include "sparc64-tdep.h"
#include "solib-svr4.h"
Defines
#define FPRS_FEF (1 << 2)
Functions
static void sparc64fbsd_supply_gregset (const struct regset *regset, struct regcache *regcache, int regnum, const void *gregs, size_t len)
static void sparc64fbsd_collect_gregset (const struct regset *regset, const struct regcache *regcache, int regnum, void *gregs, size_t len)
static void sparc64fbsd_supply_fpregset (const struct regset *regset, struct regcache *regcache, int regnum, const void *fpregs, size_t len)
static void sparc64fbsd_collect_fpregset (const struct regset *regset, const struct regcache *regcache, int regnum, void *fpregs, size_t len)
static int sparc64fbsd_pc_in_sigtramp (CORE_ADDR pc, const char *name)
static struct sparc_frame_cache * sparc64fbsd_sigtramp_frame_cache (struct frame_info *this_frame, void **this_cache)
static void sparc64fbsd_sigtramp_frame_this_id (struct frame_info *this_frame, void **this_cache, struct frame_id *this_id)
static struct value * sparc64fbsd_sigtramp_frame_prev_register (struct frame_info *this_frame, void **this_cache, int regnum)
static int sparc64fbsd_sigtramp_frame_sniffer (const struct frame_unwind *self, struct frame_info *this_frame, void **this_cache)
static void sparc64fbsd_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
void _initialize_sparc64fbsd_tdep (void)
Variables
struct sparc_gregset sparc64fbsd_gregset
static struct frame_unwind sparc64fbsd_sigtramp_frame_unwind
Define Documentation
#define FPRS_FEF (1 << 2)
Referenced by sparc64fbsd_sigtramp_frame_cache().
Function Documentation
void _initialize_sparc64fbsd_tdep (void)
Definition at line 239 of file sparc64fbsd-tdep.c.
References GDB_OSABI_FREEBSD_ELF, gdbarch_register_osabi(), and sparc64fbsd_init_abi().
static void sparc64fbsd_collect_fpregset (const struct regset * regset, const struct regcache * regcache, int regnum, void * fpregs, size_t len) [static]
Definition at line 76 of file sparc64fbsd-tdep.c.
References sparc64_bsd_fpregset, and sparc64_collect_fpregset().
Referenced by sparc64fbsd_init_abi().
static void sparc64fbsd_collect_gregset (const struct regset * regset, const struct regcache * regcache, int regnum, void * gregs, size_t len) [static]
Definition at line 60 of file sparc64fbsd-tdep.c.
References sparc64_collect_gregset().
Referenced by sparc64fbsd_init_abi().
static void sparc64fbsd_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch) [static]
Definition at line 213 of file sparc64fbsd-tdep.c.
References find_solib_trampoline_target(), gdbarch_tdep::fpregset, frame_unwind_append_unwinder(), gdbarch_tdep(), gdbarch_tdep::gregset, regset_alloc(), set_gdbarch_skip_trampoline_code(), set_solib_svr4_fetch_link_map_offsets(), gdbarch_tdep::sizeof_fpregset, gdbarch_tdep::sizeof_gregset, sparc64_init_abi(), sparc64fbsd_collect_fpregset(), sparc64fbsd_collect_gregset(), sparc64fbsd_supply_fpregset(), sparc64fbsd_supply_gregset(), and svr4_lp64_fetch_link_map_offsets().
Referenced by _initialize_sparc64fbsd_tdep().
static int sparc64fbsd_pc_in_sigtramp (CORE_ADDR pc, const char * name) [static]
Definition at line 87 of file sparc64fbsd-tdep.c.
Referenced by sparc64fbsd_sigtramp_frame_sniffer().
static struct sparc_frame_cache* sparc64fbsd_sigtramp_frame_cache (struct frame_info * this_frame, void ** this_cache) [static, read]
Definition at line 93 of file sparc64fbsd-tdep.c.
References trad_frame_saved_reg::addr, BIAS, FPRS_FEF, gdb_assert, get_frame_memory_unsigned(), get_frame_register_unsigned(), LONGEST, regnum, sparc_frame_cache::saved_regs, sp, SPARC64_F32_REGNUM, SPARC64_F62_REGNUM, SPARC64_FPRS_REGNUM, SPARC64_FSR_REGNUM, SPARC64_NPC_REGNUM, SPARC64_PC_REGNUM, SPARC64_STATE_REGNUM, SPARC64_Y_REGNUM, SPARC_F0_REGNUM, SPARC_F31_REGNUM, sparc_frame_cache(), SPARC_G1_REGNUM, SPARC_I7_REGNUM, SPARC_L0_REGNUM, SPARC_O2_REGNUM, SPARC_O7_REGNUM, SPARC_SP_REGNUM, and trad_frame_alloc_saved_regs().
Referenced by sparc64fbsd_sigtramp_frame_prev_register(), and sparc64fbsd_sigtramp_frame_this_id().
static struct value* sparc64fbsd_sigtramp_frame_prev_register (struct frame_info * this_frame, void ** this_cache, int regnum) [static, read]
Definition at line 177 of file sparc64fbsd-tdep.c.
References sparc_frame_cache::saved_regs, sparc64fbsd_sigtramp_frame_cache(), and trad_frame_get_prev_register().
static int sparc64fbsd_sigtramp_frame_sniffer (const struct frame_unwind * self, struct frame_info * this_frame, void ** this_cache) [static]
Definition at line 187 of file sparc64fbsd-tdep.c.
References find_pc_partial_function(), get_frame_pc(), name, sparc_frame_cache::pc, and sparc64fbsd_pc_in_sigtramp().
static void sparc64fbsd_sigtramp_frame_this_id (struct frame_info * this_frame, void ** this_cache, struct frame_id * this_id) [static]
Definition at line 166 of file sparc64fbsd-tdep.c.
References sparc_frame_cache::base, frame_id_build(), sparc_frame_cache::pc, and sparc64fbsd_sigtramp_frame_cache().
static void sparc64fbsd_supply_fpregset (const struct regset * regset, struct regcache * regcache, int regnum, const void * fpregs, size_t len) [static]
Definition at line 68 of file sparc64fbsd-tdep.c.
References sparc64_bsd_fpregset, and sparc64_supply_fpregset().
Referenced by sparc64fbsd_init_abi().
static void sparc64fbsd_supply_gregset (const struct regset * regset, struct regcache * regcache, int regnum, const void * gregs, size_t len) [static]
Definition at line 52 of file sparc64fbsd-tdep.c.
References sparc64_supply_gregset().
Referenced by sparc64fbsd_init_abi().
Variable Documentation
struct sparc_gregset sparc64fbsd_gregset
Initial value:
{
  26 * 8,
  25 * 8,
  24 * 8,
  28 * 8,
  16 * 8,
  -1,
  1 * 8,
  -1,
  8
}
Definition at line 37 of file sparc64fbsd-tdep.c.
Referenced by _initialize_sparc64fbsd_nat().
struct frame_unwind sparc64fbsd_sigtramp_frame_unwind [static]
Initial value:
{
  SIGTRAMP_FRAME,
  default_frame_unwind_stop_reason,
  sparc64fbsd_sigtramp_frame_this_id,
  sparc64fbsd_sigtramp_frame_prev_register,
  NULL,
  sparc64fbsd_sigtramp_frame_sniffer
}
Definition at line 201 of file sparc64fbsd-tdep.c.