GDB (xrefs): /home/stan/gdb/src/gdb/sparc-tdep.h File Reference
/home/stan/gdb/src/gdb/sparc-tdep.h File Reference
Classes
struct sparc_gregset
struct sparc_fpregset
struct gdbarch_tdep
struct sparc_frame_cache
Enumerations
enum sparc_regnum {
SPARC_G0_REGNUM, SPARC_G1_REGNUM, SPARC_G2_REGNUM, SPARC_G3_REGNUM,
SPARC_G4_REGNUM, SPARC_G5_REGNUM, SPARC_G6_REGNUM, SPARC_G7_REGNUM,
SPARC_O0_REGNUM, SPARC_O1_REGNUM, SPARC_O2_REGNUM, SPARC_O3_REGNUM,
SPARC_O4_REGNUM, SPARC_O5_REGNUM, SPARC_SP_REGNUM, SPARC_O7_REGNUM,
SPARC_L0_REGNUM, SPARC_L1_REGNUM, SPARC_L2_REGNUM, SPARC_L3_REGNUM,
SPARC_L4_REGNUM, SPARC_L5_REGNUM, SPARC_L6_REGNUM, SPARC_L7_REGNUM,
SPARC_I0_REGNUM, SPARC_I1_REGNUM, SPARC_I2_REGNUM, SPARC_I3_REGNUM,
SPARC_I4_REGNUM, SPARC_I5_REGNUM, SPARC_FP_REGNUM, SPARC_I7_REGNUM,
SPARC_F0_REGNUM, SPARC_F1_REGNUM, SPARC_F2_REGNUM, SPARC_F3_REGNUM,
SPARC_F4_REGNUM, SPARC_F5_REGNUM, SPARC_F6_REGNUM, SPARC_F7_REGNUM,
SPARC_F31_REGNUM = SPARC_F0_REGNUM + 31
}
enum sparc32_regnum {
SPARC32_Y_REGNUM = SPARC_F31_REGNUM + 1, SPARC32_PSR_REGNUM, SPARC32_WIM_REGNUM, SPARC32_TBR_REGNUM,
SPARC32_PC_REGNUM, SPARC32_NPC_REGNUM, SPARC32_FSR_REGNUM, SPARC32_CSR_REGNUM,
SPARC32_D0_REGNUM, SPARC32_D30_REGNUM = SPARC32_D0_REGNUM + 15
}
Functions
unsigned long sparc_fetch_instruction (CORE_ADDR pc)
ULONGEST sparc_fetch_wcookie (struct gdbarch *gdbarch)
void sparc_record_save_insn (struct sparc_frame_cache *cache)
CORE_ADDR sparc_analyze_prologue (struct gdbarch *gdbarch, CORE_ADDR pc, CORE_ADDR current_pc, struct sparc_frame_cache *cache)
struct sparc_frame_cache * sparc_frame_cache (struct frame_info *this_frame, void **this_cache)
struct sparc_frame_cache * sparc32_frame_cache (struct frame_info *this_frame, void **this_cache)
int sparc_software_single_step (struct frame_info *frame)
void sparc_supply_rwindow (struct regcache *regcache, CORE_ADDR sp, int regnum)
void sparc_collect_rwindow (const struct regcache *regcache, CORE_ADDR sp, int regnum)
void sparc32_supply_gregset (const struct sparc_gregset *gregset, struct regcache *regcache, int regnum, const void *gregs)
void sparc32_collect_gregset (const struct sparc_gregset *gregset, const struct regcache *regcache, int regnum, void *gregs)
void sparc32_supply_fpregset (const struct sparc_fpregset *fpregset, struct regcache *regcache, int regnum, const void *fpregs)
void sparc32_collect_fpregset (const struct sparc_fpregset *fpregset, const struct regcache *regcache, int regnum, void *fpregs)
int sparc_sol2_pc_in_sigtramp (CORE_ADDR pc, const char *name)
const char * sparc_sol2_static_transform_name (const char *name)
void sparc32_sol2_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
CORE_ADDR sparcnbsd_step_trap (struct frame_info *frame, unsigned long insn)
void sparc32nbsd_elf_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
struct trad_frame_saved_reg * sparc32nbsd_sigcontext_saved_regs (struct frame_info *next_frame)
Variables
struct sparc_gregset sparc32_sunos4_gregset
struct sparc_fpregset sparc32_sunos4_fpregset
struct sparc_fpregset sparc32_bsd_fpregset
struct sparc_gregset sparc32_sol2_gregset
struct sparc_fpregset sparc32_sol2_fpregset
struct sparc_gregset sparc32nbsd_gregset
Enumeration Type Documentation
enum sparc32_regnum
Enumerator:
SPARC32_Y_REGNUM
SPARC32_PSR_REGNUM
SPARC32_WIM_REGNUM
SPARC32_TBR_REGNUM
SPARC32_PC_REGNUM
SPARC32_NPC_REGNUM
SPARC32_FSR_REGNUM
SPARC32_CSR_REGNUM
SPARC32_D0_REGNUM
SPARC32_D30_REGNUM
Definition at line 132 of file sparc-tdep.h.
enum sparc_regnum
Enumerator:
SPARC_G0_REGNUM
SPARC_G1_REGNUM
SPARC_G2_REGNUM
SPARC_G3_REGNUM
SPARC_G4_REGNUM
SPARC_G5_REGNUM
SPARC_G6_REGNUM
SPARC_G7_REGNUM
SPARC_O0_REGNUM
SPARC_O1_REGNUM
SPARC_O2_REGNUM
SPARC_O3_REGNUM
SPARC_O4_REGNUM
SPARC_O5_REGNUM
SPARC_SP_REGNUM
SPARC_O7_REGNUM
SPARC_L0_REGNUM
SPARC_L1_REGNUM
SPARC_L2_REGNUM
SPARC_L3_REGNUM
SPARC_L4_REGNUM
SPARC_L5_REGNUM
SPARC_L6_REGNUM
SPARC_L7_REGNUM
SPARC_I0_REGNUM
SPARC_I1_REGNUM
SPARC_I2_REGNUM
SPARC_I3_REGNUM
SPARC_I4_REGNUM
SPARC_I5_REGNUM
SPARC_FP_REGNUM
SPARC_I7_REGNUM
SPARC_F0_REGNUM
SPARC_F1_REGNUM
SPARC_F2_REGNUM
SPARC_F3_REGNUM
SPARC_F4_REGNUM
SPARC_F5_REGNUM
SPARC_F6_REGNUM
SPARC_F7_REGNUM
SPARC_F31_REGNUM
Definition at line 86 of file sparc-tdep.h.
Function Documentation
void sparc32_collect_fpregset (const struct sparc_fpregset * fpregset, const struct regcache * regcache, int regnum, void * fpregs)
Definition at line 1985 of file sparc-tdep.c.
References sparc_fpregset::r_f0_offset, sparc_fpregset::r_fsr_offset, regcache_raw_collect(), SPARC32_FSR_REGNUM, and SPARC_F0_REGNUM.
Referenced by _initialize_sparc_nat(), fill_fpregset(), sparc32_linux_collect_core_fpregset(), and sparc64nbsd_collect_fpregset().
void sparc32_collect_gregset (const struct sparc_gregset * gregset, const struct regcache * regcache, int regnum, void * gregs)
Definition at line 1910 of file sparc-tdep.c.
References offset, sparc_gregset::r_g1_offset, sparc_gregset::r_l0_offset, sparc_gregset::r_npc_offset, sparc_gregset::r_pc_offset, sparc_gregset::r_psr_offset, sparc_gregset::r_y_offset, regcache_raw_collect(), SPARC32_NPC_REGNUM, SPARC32_PC_REGNUM, SPARC32_PSR_REGNUM, SPARC32_Y_REGNUM, SPARC_G1_REGNUM, SPARC_I7_REGNUM, SPARC_L0_REGNUM, and SPARC_O7_REGNUM.
Referenced by _initialize_sparc_nat(), fill_gregset(), sparc32_linux_collect_core_gregset(), and sparc64nbsd_collect_gregset().
struct sparc_frame_cache* sparc32_frame_cache (struct frame_info * this_frame, void ** this_cache) [read]
Definition at line 1101 of file sparc-tdep.c.
References sparc_frame_cache::copied_regs_mask, find_pc_function(), get_frame_register_unsigned(), sparc_frame_cache::pc, regnum, sparc32_struct_return_from_sym(), sparc_frame_cache(), SPARC_I7_REGNUM, sparc_is_unimp_insn(), SPARC_O7_REGNUM, and sparc_frame_cache::struct_return_p.
Referenced by sparc32_frame_base_address(), sparc32_frame_prev_register(), and sparc32_frame_this_id().
void sparc32_sol2_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch)
Definition at line 213 of file sparc-sol2-tdep.c.
References find_solib_trampoline_target(), frame_unwind_append_unwinder(), gdbarch_tdep(), gdbarch_tdep::plt_entry_size, set_gdbarch_core_pid_to_str(), set_gdbarch_skip_solib_resolver(), set_gdbarch_skip_trampoline_code(), set_gdbarch_software_single_step(), set_gdbarch_sofun_address_maybe_missing(), set_gdbarch_static_transform_name(), set_solib_svr4_fetch_link_map_offsets(), sol2_core_pid_to_str(), sol2_skip_solib_resolver(), sparc_sol2_static_transform_name(), and svr4_ilp32_fetch_link_map_offsets().
void sparc32_supply_fpregset (const struct sparc_fpregset * fpregset, struct regcache * regcache, int regnum, const void * fpregs)
Definition at line 1965 of file sparc-tdep.c.
References sparc_fpregset::r_f0_offset, sparc_fpregset::r_fsr_offset, regcache_raw_supply(), SPARC32_FSR_REGNUM, and SPARC_F0_REGNUM.
Referenced by _initialize_sparc_nat(), sparc32_linux_supply_core_fpregset(), sparc32nbsd_supply_fpregset(), sparc32nbsd_supply_gregset(), sparc64nbsd_supply_fpregset(), and supply_fpregset().
void sparc32_supply_gregset (const struct sparc_gregset * gregset, struct regcache * regcache, int regnum, const void * gregs)
Definition at line 1845 of file sparc-tdep.c.
References offset, sparc_gregset::r_g1_offset, sparc_gregset::r_l0_offset, sparc_gregset::r_npc_offset, sparc_gregset::r_pc_offset, sparc_gregset::r_psr_offset, sparc_gregset::r_y_offset, regcache_cooked_read_unsigned(), regcache_raw_supply(), sp, SPARC32_NPC_REGNUM, SPARC32_PC_REGNUM, SPARC32_PSR_REGNUM, SPARC32_Y_REGNUM, SPARC_G0_REGNUM, SPARC_G1_REGNUM, SPARC_I7_REGNUM, SPARC_L0_REGNUM, SPARC_O7_REGNUM, SPARC_SP_REGNUM, sparc_supply_rwindow(), and ULONGEST.
Referenced by _initialize_sparc_nat(), sparc32_linux_supply_core_gregset(), sparc32nbsd_supply_gregset(), sparc64nbsd_supply_gregset(), and supply_gregset().
void sparc32nbsd_elf_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch)
Definition at line 314 of file sparcnbsd-tdep.c.
References set_solib_svr4_fetch_link_map_offsets(), sparc32nbsd_init_abi(), and svr4_ilp32_fetch_link_map_offsets().
Referenced by sparc32obsd_init_abi().
struct trad_frame_saved_reg* sparc32nbsd_sigcontext_saved_regs (struct frame_info * next_frame) [read]
Definition at line 100 of file sparcnbsd-tdep.c.
References trad_frame_saved_reg::addr, get_frame_arch(), get_frame_memory_unsigned(), get_frame_register_unsigned(), PSR_EF, trad_frame_saved_reg::realreg, regnum, sp, SPARC32_FSR_REGNUM, SPARC32_NPC_REGNUM, SPARC32_PC_REGNUM, SPARC32_PSR_REGNUM, SPARC32_Y_REGNUM, SPARC_F0_REGNUM, SPARC_F31_REGNUM, sparc_fetch_wcookie(), SPARC_FP_REGNUM, SPARC_G0_REGNUM, SPARC_G1_REGNUM, SPARC_G2_REGNUM, SPARC_G7_REGNUM, SPARC_I0_REGNUM, SPARC_I7_REGNUM, SPARC_L0_REGNUM, SPARC_L1_REGNUM, SPARC_O0_REGNUM, SPARC_O1_REGNUM, SPARC_O5_REGNUM, SPARC_O7_REGNUM, SPARC_SP_REGNUM, trad_frame_alloc_saved_regs(), trad_frame_set_value(), and ULONGEST.
Referenced by sparc32nbsd_sigcontext_frame_cache(), and sparc32obsd_sigtramp_frame_cache().
CORE_ADDR sparc_analyze_prologue (struct gdbarch * gdbarch, CORE_ADDR pc, CORE_ADDR current_pc, struct sparc_frame_cache * cache)
Definition at line 835 of file sparc-tdep.c.
References BIAS, sparc_frame_cache::copied_regs_mask, sparc_frame_cache::frame_offset, sparc_frame_cache::frameless_p, gdbarch_tdep(), in_plt_section(), offset, gdbarch_tdep::pc, gdbarch_tdep::plt_entry_size, regnum, sparc_frame_cache::saved_regs_mask, sparc_fetch_instruction(), SPARC_FP_REGNUM, SPARC_G0_REGNUM, SPARC_I7_REGNUM, SPARC_L0_REGNUM, SPARC_O7_REGNUM, sparc_record_save_insn(), sparc_skip_stack_check(), SPARC_SP_REGNUM, X_I, X_OP, X_OP2, X_OP3, X_RD, X_RS1, X_RS2, and X_SIMM13.
Referenced by sparc32_skip_prologue(), sparc64_skip_prologue(), and sparc_frame_cache().
void sparc_collect_rwindow (const struct regcache * regcache, CORE_ADDR sp, int regnum)
Definition at line 1774 of file sparc-tdep.c.
References BIAS, gdbarch::byte_order, extract_unsigned_integer(), gdbarch_byte_order(), gdbarch_ptr_bit(), get_regcache_arch(), offset, regcache_raw_collect(), sparc_fetch_wcookie(), SPARC_I7_REGNUM, SPARC_L0_REGNUM, SPARC_SP_REGNUM, store_unsigned_integer(), target_write_memory(), and ULONGEST.
Referenced by sparc32obsd_collect_uthread(), sparc64obsd_collect_uthread(), and sparc_store_inferior_registers().
unsigned long sparc_fetch_instruction (CORE_ADDR pc)
Definition at line 96 of file sparc-tdep.c.
References target_read_memory().
Referenced by sparc32_skip_prologue(), sparc32obsd_pc_in_sigtramp(), sparc64obsd_pc_in_sigtramp(), sparc_analyze_control_transfer(), sparc_analyze_prologue(), sparc_is_unimp_insn(), and sparc_skip_stack_check().
ULONGEST sparc_fetch_wcookie (struct gdbarch * gdbarch)
Definition at line 156 of file sparc-tdep.c.
References current_target, extract_unsigned_integer(), gdb_assert, gdbarch_byte_order(), len, TARGET_OBJECT_WCOOKIE, and target_read().
Referenced by sparc32_frame_prev_register(), sparc32nbsd_sigcontext_saved_regs(), sparc64_frame_prev_register(), sparc64nbsd_sigcontext_saved_regs(), sparc_collect_rwindow(), and sparc_supply_rwindow().
struct sparc_frame_cache* sparc_frame_cache (struct frame_info * this_frame, void ** this_cache) [read]
Definition at line 1044 of file sparc-tdep.c.
References sparc_frame_cache::base, BIAS, sparc_frame_cache::frame_offset, sparc_frame_cache::frameless_p, get_frame_arch(), get_frame_func(), get_frame_pc(), get_frame_register_unsigned(), sparc_frame_cache::pc, sparc_alloc_frame_cache(), sparc_analyze_prologue(), SPARC_FP_REGNUM, and SPARC_SP_REGNUM.
Referenced by sparc32_frame_cache(), sparc32_sol2_sigtramp_frame_cache(), sparc32nbsd_sigcontext_frame_cache(), sparc32obsd_sigtramp_frame_cache(), sparc64_frame_cache(), sparc64_sol2_sigtramp_frame_cache(), sparc64fbsd_sigtramp_frame_cache(), sparc64nbsd_sigcontext_frame_cache(), sparc64obsd_frame_cache(), and sparc64obsd_trapframe_cache().
void sparc_record_save_insn (struct sparc_frame_cache * cache)
Definition at line 812 of file sparc-tdep.c.
References sparc_frame_cache::copied_regs_mask, sparc_frame_cache::frame_offset, sparc_frame_cache::frameless_p, and sparc_frame_cache::saved_regs_mask.
Referenced by sparc32nbsd_sigcontext_frame_cache(), sparc32obsd_sigtramp_frame_cache(), sparc64nbsd_sigcontext_frame_cache(), sparc64obsd_frame_cache(), and sparc_analyze_prologue().
int sparc_software_single_step (struct frame_info * frame)
Definition at line 1556 of file sparc-tdep.c.
References gdb_assert, gdbarch_tdep(), get_frame_address_space(), get_frame_arch(), get_frame_register_unsigned(), insert_single_step_breakpoint(), gdbarch_tdep::npc_regnum, gdbarch_tdep::pc_regnum, and sparc_analyze_control_transfer().
Referenced by sparc32_gdbarch_init().
int sparc_sol2_pc_in_sigtramp (CORE_ADDR pc, const char * name)
Definition at line 75 of file sparc-sol2-tdep.c.
Referenced by sparc32_sol2_sigtramp_frame_sniffer(), and sparc64_sol2_sigtramp_frame_sniffer().
const char* sparc_sol2_static_transform_name (const char * name)
Definition at line 183 of file sparc-sol2-tdep.c.
References name, p, and strrchr().
Referenced by sparc32_sol2_init_abi(), and sparc64_sol2_init_abi().
void sparc_supply_rwindow (struct regcache * regcache, CORE_ADDR sp, int regnum)
Definition at line 1701 of file sparc-tdep.c.
References BIAS, gdbarch::byte_order, extract_unsigned_integer(), gdbarch_byte_order(), gdbarch_ptr_bit(), get_regcache_arch(), memset(), offset, regcache_raw_supply(), sparc_fetch_wcookie(), SPARC_I7_REGNUM, SPARC_L0_REGNUM, store_unsigned_integer(), target_read_memory(), and ULONGEST.
Referenced by sparc32_supply_gregset(), sparc32nbsd_supply_pcb(), sparc32obsd_supply_uthread(), sparc64_supply_gregset(), sparc64fbsd_kvm_supply_pcb(), sparc64nbsd_supply_pcb(), and sparc64obsd_supply_uthread().
CORE_ADDR sparcnbsd_step_trap (struct frame_info * frame, unsigned long insn)
Definition at line 268 of file sparcnbsd-tdep.c.
References get_frame_register_unsigned(), SPARC_G1_REGNUM, SPARC_G2_REGNUM, SPARC_G7_REGNUM, ULONGEST, X_I, X_RS1, and X_RS2.
Referenced by sparc32nbsd_init_abi(), sparc64nbsd_init_abi(), and sparc64obsd_init_abi().
Variable Documentation
struct sparc_fpregset sparc32_bsd_fpregset
Definition at line 2026 of file sparc-tdep.c.
Referenced by _initialize_sparc_linux_nat(), _initialize_sparcnbsd_nat(), sparc32_linux_collect_core_fpregset(), sparc32_linux_supply_core_fpregset(), sparc32nbsd_supply_fpregset(), sparc32nbsd_supply_gregset(), sparc64nbsd_collect_fpregset(), and sparc64nbsd_supply_fpregset().
struct sparc_fpregset sparc32_sol2_fpregset
Definition at line 51 of file sparc-sol2-tdep.c.
struct sparc_gregset sparc32_sol2_gregset
Definition at line 39 of file sparc-sol2-tdep.c.
struct sparc_fpregset sparc32_sunos4_fpregset
Definition at line 2020 of file sparc-tdep.c.
Referenced by _initialize_sparc_nat().
struct sparc_gregset sparc32_sunos4_gregset
Definition at line 2008 of file sparc-tdep.c.
Referenced by _initialize_sparc_nat().
struct sparc_gregset sparc32nbsd_gregset
Definition at line 44 of file sparcnbsd-tdep.c.
Referenced by _initialize_sparcnbsd_nat(), sparc64nbsd_collect_gregset(), and sparc64nbsd_supply_gregset().