GDB (xrefs): /home/stan/gdb/src/gdb/sparc64-tdep.c File Reference
/home/stan/gdb/src/gdb/sparc64-tdep.c File Reference
#include "defs.h"
#include "arch-utils.h"
#include "dwarf2-frame.h"
#include "floatformat.h"
#include "frame.h"
#include "frame-base.h"
#include "frame-unwind.h"
#include "gdbcore.h"
#include "gdbtypes.h"
#include "inferior.h"
#include "symtab.h"
#include "objfiles.h"
#include "osabi.h"
#include "regcache.h"
#include "target.h"
#include "value.h"
#include "gdb_assert.h"
#include "gdb_string.h"
#include "sparc64-tdep.h"
Defines
#define SPARC64_NUM_REGS ARRAY_SIZE (sparc64_register_names)
#define SPARC64_NUM_PSEUDO_REGS ARRAY_SIZE (sparc64_pseudo_register_names)
#define TSTATE_CWP 0x000000000000001fULL
#define TSTATE_ICC 0x0000000f00000000ULL
#define TSTATE_XCC 0x000000f000000000ULL
#define PSR_S 0x00000080
#define PSR_ICC 0x00f00000
#define PSR_VERS 0x0f000000
#define PSR_IMPL 0xf0000000
#define PSR_V8PLUS 0xff000000
#define PSR_XCC 0x000f0000
Functions
static int sparc64_integral_or_pointer_p (const struct type *type)
static int sparc64_floating_p (const struct type *type)
static int sparc64_complex_floating_p (const struct type *type)
static int sparc64_structure_or_union_p (const struct type *type)
static struct type * sparc64_pstate_type (struct gdbarch *gdbarch)
static struct type * sparc64_fsr_type (struct gdbarch *gdbarch)
static struct type * sparc64_fprs_type (struct gdbarch *gdbarch)
static const char * sparc64_register_name (struct gdbarch *gdbarch, int regnum)
static struct type * sparc64_register_type (struct gdbarch *gdbarch, int regnum)
static enum register_status sparc64_pseudo_register_read (struct gdbarch *gdbarch, struct regcache *regcache, int regnum, gdb_byte *buf)
static void sparc64_pseudo_register_write (struct gdbarch *gdbarch, struct regcache *regcache, int regnum, const gdb_byte *buf)
static CORE_ADDR sparc64_skip_prologue (struct gdbarch *gdbarch, CORE_ADDR start_pc)
static struct sparc_frame_cache * sparc64_frame_cache (struct frame_info *this_frame, void **this_cache)
static void sparc64_frame_this_id (struct frame_info *this_frame, void **this_cache, struct frame_id *this_id)
static struct value * sparc64_frame_prev_register (struct frame_info *this_frame, void **this_cache, int regnum)
static CORE_ADDR sparc64_frame_base_address (struct frame_info *this_frame, void **this_cache)
static int sparc64_16_byte_align_p (struct type *type)
static void sparc64_store_floating_fields (struct regcache *regcache, struct type *type, const gdb_byte *valbuf, int element, int bitpos)
static void sparc64_extract_floating_fields (struct regcache *regcache, struct type *type, gdb_byte *valbuf, int bitpos)
static CORE_ADDR sparc64_store_arguments (struct regcache *regcache, int nargs, struct value **args, CORE_ADDR sp, int struct_return, CORE_ADDR struct_addr)
static CORE_ADDR sparc64_frame_align (struct gdbarch *gdbarch, CORE_ADDR address)
static CORE_ADDR sparc64_push_dummy_call (struct gdbarch *gdbarch, struct value *function, struct regcache *regcache, CORE_ADDR bp_addr, int nargs, struct value **args, CORE_ADDR sp, int struct_return, CORE_ADDR struct_addr)
static void sparc64_extract_return_value (struct type *type, struct regcache *regcache, gdb_byte *valbuf)
static void sparc64_store_return_value (struct type *type, struct regcache *regcache, const gdb_byte *valbuf)
static enum return_value_convention sparc64_return_value (struct gdbarch *gdbarch, struct value *function, struct type *type, struct regcache *regcache, gdb_byte *readbuf, const gdb_byte *writebuf)
static void sparc64_dwarf2_frame_init_reg (struct gdbarch *gdbarch, int regnum, struct dwarf2_frame_state_reg *reg, struct frame_info *this_frame)
void sparc64_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
void sparc64_supply_gregset (const struct sparc_gregset *gregset, struct regcache *regcache, int regnum, const void *gregs)
void sparc64_collect_gregset (const struct sparc_gregset *gregset, const struct regcache *regcache, int regnum, void *gregs)
void sparc64_supply_fpregset (const struct sparc_fpregset *fpregset, struct regcache *regcache, int regnum, const void *fpregs)
void sparc64_collect_fpregset (const struct sparc_fpregset *fpregset, const struct regcache *regcache, int regnum, void *fpregs)
Variables
static const char * sparc64_register_names []
static const char * sparc64_pseudo_register_names []
static struct frame_unwind sparc64_frame_unwind
static struct frame_base sparc64_frame_base
struct sparc_fpregset sparc64_bsd_fpregset
Define Documentation
#define PSR_ICC 0x00f00000
Definition at line 1217 of file sparc64-tdep.c.
Referenced by sparc64_collect_gregset().
#define PSR_IMPL 0xf0000000
Definition at line 1219 of file sparc64-tdep.c.
Referenced by sparc64_collect_gregset().
#define PSR_S 0x00000080
Definition at line 1216 of file sparc64-tdep.c.
Referenced by sparc64_supply_gregset().
#define PSR_V8PLUS 0xff000000
Definition at line 1220 of file sparc64-tdep.c.
Referenced by sparc64_collect_gregset(), and sparc64_supply_gregset().
#define PSR_VERS 0x0f000000
Definition at line 1218 of file sparc64-tdep.c.
Referenced by sparc64_collect_gregset().
#define PSR_XCC 0x000f0000
Definition at line 1221 of file sparc64-tdep.c.
Referenced by sparc64_collect_gregset().
#define SPARC64_NUM_PSEUDO_REGS ARRAY_SIZE (sparc64_pseudo_register_names)
Definition at line 276 of file sparc64-tdep.c.
Referenced by sparc64_init_abi(), and sparc64_register_name().
#define SPARC64_NUM_REGS ARRAY_SIZE (sparc64_register_names)
Definition at line 257 of file sparc64-tdep.c.
Referenced by sparc64_init_abi(), sparc64_pseudo_register_read(), sparc64_pseudo_register_write(), and sparc64_register_name().
#define TSTATE_CWP 0x000000000000001fULL
Definition at line 1212 of file sparc64-tdep.c.
Referenced by sparc64_supply_gregset().
#define TSTATE_ICC 0x0000000f00000000ULL
Definition at line 1213 of file sparc64-tdep.c.
Referenced by sparc64_supply_gregset().
#define TSTATE_XCC 0x000000f000000000ULL
Definition at line 1214 of file sparc64-tdep.c.
Referenced by sparc64_supply_gregset().
Function Documentation
static int sparc64_16_byte_align_p (struct type * type) [static]
Definition at line 613 of file sparc64-tdep.c.
References check_typedef(), sparc64_floating_p(), sparc64_structure_or_union_p(), TYPE_FIELD_TYPE, TYPE_LENGTH, and TYPE_NFIELDS.
Referenced by sparc64_store_arguments().
void sparc64_collect_fpregset (const struct sparc_fpregset * fpregset, const struct regcache * regcache, int regnum, void * fpregs)
Definition at line 1489 of file sparc64-tdep.c.
References gdbarch_ptr_bit(), get_regcache_arch(), sparc_fpregset::r_f0_offset, sparc_fpregset::r_fsr_offset, regcache_raw_collect(), SPARC32_FSR_REGNUM, SPARC64_F32_REGNUM, SPARC64_FSR_REGNUM, and SPARC_F0_REGNUM.
Referenced by _initialize_sparc64_nat(), fill_fpregset(), sparc64_linux_collect_core_fpregset(), sparc64fbsd_collect_fpregset(), and sparc64nbsd_collect_fpregset().
void sparc64_collect_gregset (const struct sparc_gregset * gregset, const struct regcache * regcache, int regnum, void * gregs)
Definition at line 1341 of file sparc64-tdep.c.
References gdbarch::byte_order, extract_unsigned_integer(), gdbarch_byte_order(), gdbarch_ptr_bit(), get_regcache_arch(), memcpy(), offset, PSR_ICC, PSR_IMPL, PSR_V8PLUS, PSR_VERS, PSR_XCC, sparc_gregset::r_g1_offset, sparc_gregset::r_l0_offset, sparc_gregset::r_npc_offset, sparc_gregset::r_pc_offset, sparc_gregset::r_y_offset, sparc_gregset::r_y_size, regcache_raw_collect(), SPARC32_NPC_REGNUM, SPARC32_PC_REGNUM, SPARC32_PSR_REGNUM, SPARC32_Y_REGNUM, SPARC64_FPRS_REGNUM, SPARC64_NPC_REGNUM, SPARC64_PC_REGNUM, SPARC64_STATE_REGNUM, SPARC64_Y_REGNUM, SPARC_G1_REGNUM, SPARC_I7_REGNUM, SPARC_L0_REGNUM, SPARC_O7_REGNUM, store_unsigned_integer(), and ULONGEST.
Referenced by _initialize_sparc64_nat(), fill_gregset(), sparc64_linux_collect_core_gregset(), sparc64fbsd_collect_gregset(), and sparc64nbsd_collect_gregset().
static int sparc64_complex_floating_p (const struct type * type) [static]
Definition at line 108 of file sparc64-tdep.c.
References gdb_assert, len, TYPE_CODE, TYPE_CODE_COMPLEX, and TYPE_LENGTH.
Referenced by sparc64_extract_return_value(), sparc64_store_arguments(), sparc64_store_floating_fields(), and sparc64_store_return_value().
static void sparc64_dwarf2_frame_init_reg (struct gdbarch * gdbarch, int regnum, struct dwarf2_frame_state_reg * reg, struct frame_info * this_frame) [static]
Definition at line 1139 of file sparc64-tdep.c.
References DWARF2_FRAME_REG_CFA, DWARF2_FRAME_REG_RA_OFFSET, DWARF2_FRAME_REG_SAME_VALUE, dwarf2_frame_state_reg::how, dwarf2_frame_state_reg::loc, dwarf2_frame_state_reg::offset, SPARC64_NPC_REGNUM, SPARC64_PC_REGNUM, SPARC_G0_REGNUM, and SPARC_SP_REGNUM.
Referenced by sparc64_init_abi().
static void sparc64_extract_floating_fields (struct regcache * regcache, struct type * type, gdb_byte * valbuf, int bitpos) [static]
Definition at line 715 of file sparc64-tdep.c.
References check_typedef(), gdb_assert, len, regcache_cooked_read(), regnum, SPARC64_D0_REGNUM, sparc64_floating_p(), SPARC64_Q0_REGNUM, sparc64_structure_or_union_p(), SPARC_F0_REGNUM, TYPE_FIELD_BITPOS, TYPE_FIELD_TYPE, TYPE_LENGTH, and TYPE_NFIELDS.
Referenced by sparc64_extract_return_value().
static void sparc64_extract_return_value (struct type * type, struct regcache * regcache, gdb_byte * valbuf) [static]
Definition at line 1020 of file sparc64-tdep.c.
References gdb_assert, len, memcpy(), regcache_cooked_read(), sparc64_complex_floating_p(), sparc64_extract_floating_fields(), sparc64_floating_p(), sparc64_integral_or_pointer_p(), sparc64_structure_or_union_p(), SPARC_F0_REGNUM, SPARC_O0_REGNUM, TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_UNION, and TYPE_LENGTH.
Referenced by sparc64_return_value().
static int sparc64_floating_p (const struct type * type) [static]
Definition at line 88 of file sparc64-tdep.c.
References gdb_assert, len, TYPE_CODE, TYPE_CODE_FLT, and TYPE_LENGTH.
Referenced by sparc64_16_byte_align_p(), sparc64_extract_floating_fields(), sparc64_extract_return_value(), sparc64_store_arguments(), sparc64_store_floating_fields(), and sparc64_store_return_value().
static struct type* sparc64_fprs_type (struct gdbarch * gdbarch) [static, read]
Definition at line 211 of file sparc64-tdep.c.
References append_flags_type_flag(), arch_flags_type(), gdbarch_tdep(), gdbarch_tdep::sparc64_fprs_type, and type.
Referenced by sparc64_register_type().
static CORE_ADDR sparc64_frame_align (struct gdbarch * gdbarch, CORE_ADDR address) [static]
Definition at line 984 of file sparc64-tdep.c.
Referenced by sparc64_init_abi().
static CORE_ADDR sparc64_frame_base_address (struct frame_info * this_frame, void ** this_cache) [static]
Definition at line 594 of file sparc64-tdep.c.
References sparc_frame_cache::base, and sparc64_frame_cache().
static struct sparc_frame_cache* sparc64_frame_cache (struct frame_info * this_frame, void ** this_cache) [static, read]
Definition at line 511 of file sparc64-tdep.c.
References sparc_frame_cache().
Referenced by sparc64_frame_base_address(), sparc64_frame_prev_register(), and sparc64_frame_this_id().
static struct value* sparc64_frame_prev_register (struct frame_info * this_frame, void ** this_cache, int regnum) [static, read]
Definition at line 531 of file sparc64-tdep.c.
References sparc_frame_cache::base, sparc_frame_cache::copied_regs_mask, frame_unwind_got_constant(), frame_unwind_got_memory(), frame_unwind_got_register(), sparc_frame_cache::frameless_p, get_frame_arch(), get_frame_memory_unsigned(), get_frame_register_unsigned(), sparc_frame_cache::pc, sparc_frame_cache::saved_regs_mask, sparc64_frame_cache(), SPARC64_NPC_REGNUM, SPARC64_PC_REGNUM, sparc_fetch_wcookie(), SPARC_I0_REGNUM, SPARC_I7_REGNUM, SPARC_L0_REGNUM, SPARC_O0_REGNUM, SPARC_O7_REGNUM, and ULONGEST.
static void sparc64_frame_this_id (struct frame_info * this_frame, void ** this_cache, struct frame_id * this_id) [static]
Definition at line 517 of file sparc64-tdep.c.
References sparc_frame_cache::base, frame_id_build(), sparc_frame_cache::pc, and sparc64_frame_cache().
static struct type* sparc64_fsr_type (struct gdbarch * gdbarch) [static, read]
Definition at line 178 of file sparc64-tdep.c.
References append_flags_type_flag(), arch_flags_type(), gdbarch_tdep(), gdbarch_tdep::sparc64_fsr_type, and type.
Referenced by sparc64_register_type().
void sparc64_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch)
Definition at line 1166 of file sparc64-tdep.c.
References AT_ENTRY_POINT, default_stabs_argument_has_addr(), dwarf2_frame_set_init_reg(), frame_base_set_default(), frame_unwind_append_unwinder(), gdbarch_tdep(), gdbarch_tdep::npc_regnum, gdbarch_tdep::pc_regnum, set_gdbarch_call_dummy_location(), set_gdbarch_frame_align(), set_gdbarch_long_bit(), set_gdbarch_long_long_bit(), set_gdbarch_num_pseudo_regs(), set_gdbarch_num_regs(), set_gdbarch_pc_regnum(), set_gdbarch_pseudo_register_read(), set_gdbarch_pseudo_register_write(), set_gdbarch_ptr_bit(), set_gdbarch_push_dummy_call(), set_gdbarch_push_dummy_code(), set_gdbarch_register_name(), set_gdbarch_register_type(), set_gdbarch_return_value(), set_gdbarch_skip_prologue(), set_gdbarch_stabs_argument_has_addr(), sparc64_dwarf2_frame_init_reg(), sparc64_frame_align(), SPARC64_NPC_REGNUM, SPARC64_NUM_PSEUDO_REGS, SPARC64_NUM_REGS, SPARC64_PC_REGNUM, sparc64_pseudo_register_read(), sparc64_pseudo_register_write(), sparc64_push_dummy_call(), sparc64_register_name(), sparc64_register_type(), sparc64_return_value(), and sparc64_skip_prologue().
Referenced by sparc64_linux_init_abi(), sparc64_sol2_init_abi(), sparc64fbsd_init_abi(), sparc64nbsd_init_abi(), and sparc64obsd_init_abi().
static int sparc64_integral_or_pointer_p (const struct type * type) [static]
Definition at line 57 of file sparc64-tdep.c.
References gdb_assert, len, TYPE_CODE, TYPE_CODE_BOOL, TYPE_CODE_CHAR, TYPE_CODE_ENUM, TYPE_CODE_INT, TYPE_CODE_PTR, TYPE_CODE_RANGE, TYPE_CODE_REF, and TYPE_LENGTH.
Referenced by sparc64_extract_return_value(), sparc64_store_arguments(), and sparc64_store_return_value().
static enum register_status sparc64_pseudo_register_read (struct gdbarch * gdbarch, struct regcache * regcache, int regnum, gdb_byte * buf) [static]
Definition at line 343 of file sparc64-tdep.c.
References gdb_assert, gdbarch_byte_order(), REG_VALID, regcache_raw_read(), regcache_raw_read_unsigned(), SPARC64_ASI_REGNUM, SPARC64_CCR_REGNUM, SPARC64_CWP_REGNUM, SPARC64_D0_REGNUM, SPARC64_D30_REGNUM, SPARC64_D32_REGNUM, SPARC64_D62_REGNUM, SPARC64_F32_REGNUM, SPARC64_NUM_REGS, SPARC64_PSTATE_REGNUM, SPARC64_Q0_REGNUM, SPARC64_Q28_REGNUM, SPARC64_Q32_REGNUM, SPARC64_Q60_REGNUM, SPARC64_STATE_REGNUM, SPARC_F0_REGNUM, exsummary::status, store_unsigned_integer(), and ULONGEST.
Referenced by sparc64_init_abi().
static void sparc64_pseudo_register_write (struct gdbarch * gdbarch, struct regcache * regcache, int regnum, const gdb_byte * buf) [static]
Definition at line 422 of file sparc64-tdep.c.
References bits, extract_unsigned_integer(), gdb_assert, gdbarch_byte_order(), regcache_raw_read_unsigned(), regcache_raw_write(), regcache_raw_write_unsigned(), SPARC64_ASI_REGNUM, SPARC64_CCR_REGNUM, SPARC64_CWP_REGNUM, SPARC64_D0_REGNUM, SPARC64_D30_REGNUM, SPARC64_D32_REGNUM, SPARC64_D62_REGNUM, SPARC64_F32_REGNUM, SPARC64_NUM_REGS, SPARC64_PSTATE_REGNUM, SPARC64_Q0_REGNUM, SPARC64_Q28_REGNUM, SPARC64_Q32_REGNUM, SPARC64_Q60_REGNUM, SPARC64_STATE_REGNUM, SPARC_F0_REGNUM, and ULONGEST.
Referenced by sparc64_init_abi().
static struct type* sparc64_pstate_type (struct gdbarch * gdbarch) [static, read]
Definition at line 151 of file sparc64-tdep.c.
References append_flags_type_flag(), arch_flags_type(), gdbarch_tdep(), gdbarch_tdep::sparc64_pstate_type, and type.
Referenced by sparc64_register_type().
static CORE_ADDR sparc64_push_dummy_call (struct gdbarch * gdbarch, struct value * function, struct regcache * regcache, CORE_ADDR bp_addr, int nargs, struct value ** args, CORE_ADDR sp, int struct_return, CORE_ADDR struct_addr) [static]
Definition at line 991 of file sparc64-tdep.c.
References BIAS, gdb_assert, regcache_cooked_write_unsigned(), sparc64_store_arguments(), SPARC_O7_REGNUM, and SPARC_SP_REGNUM.
Referenced by sparc64_init_abi().
static const char* sparc64_register_name (struct gdbarch * gdbarch, int regnum) [static]
Definition at line 281 of file sparc64-tdep.c.
References regnum, SPARC64_NUM_PSEUDO_REGS, SPARC64_NUM_REGS, sparc64_pseudo_register_names, and sparc64_register_names.
Referenced by sparc64_init_abi().
static struct type* sparc64_register_type (struct gdbarch * gdbarch, int regnum) [static, read]
Definition at line 297 of file sparc64-tdep.c.
References _, builtin_type::builtin_data_ptr, builtin_type::builtin_double, builtin_type::builtin_float, builtin_type::builtin_func_ptr, builtin_type::builtin_int64, builtin_type::builtin_long_double, builtin_type(), internal_error(), SPARC64_ASI_REGNUM, SPARC64_CCR_REGNUM, SPARC64_CWP_REGNUM, SPARC64_D0_REGNUM, SPARC64_D62_REGNUM, SPARC64_F32_REGNUM, SPARC64_F62_REGNUM, SPARC64_FPRS_REGNUM, sparc64_fprs_type(), SPARC64_FSR_REGNUM, sparc64_fsr_type(), SPARC64_NPC_REGNUM, SPARC64_PC_REGNUM, SPARC64_PSTATE_REGNUM, sparc64_pstate_type(), SPARC64_Q0_REGNUM, SPARC64_Q60_REGNUM, SPARC64_STATE_REGNUM, SPARC64_Y_REGNUM, SPARC_F0_REGNUM, SPARC_F31_REGNUM, SPARC_FP_REGNUM, SPARC_G0_REGNUM, SPARC_I7_REGNUM, and SPARC_SP_REGNUM.
Referenced by sparc64_init_abi().
static enum return_value_convention sparc64_return_value (struct gdbarch * gdbarch, struct value * function, struct type * type, struct regcache * regcache, gdb_byte * readbuf, const gdb_byte * writebuf) [static]
Definition at line 1122 of file sparc64-tdep.c.
References RETURN_VALUE_REGISTER_CONVENTION, RETURN_VALUE_STRUCT_CONVENTION, sparc64_extract_return_value(), sparc64_store_return_value(), and TYPE_LENGTH.
Referenced by sparc64_init_abi().
static CORE_ADDR sparc64_skip_prologue (struct gdbarch * gdbarch, CORE_ADDR start_pc) [static]
Definition at line 487 of file sparc64-tdep.c.
References symtab_and_line::end, find_pc_line(), find_pc_partial_function(), and sparc_analyze_prologue().
Referenced by sparc64_init_abi().
static CORE_ADDR sparc64_store_arguments (struct regcache * regcache, int nargs, struct value ** args, CORE_ADDR sp, int struct_return, CORE_ADDR struct_addr) [static]
Definition at line 764 of file sparc64-tdep.c.
References BIAS, gdb_assert, get_regcache_arch(), len, lookup_pointer_type(), memcpy(), memset(), regcache_cooked_write(), regcache_cooked_write_unsigned(), regnum, sparc64_16_byte_align_p(), sparc64_complex_floating_p(), SPARC64_D0_REGNUM, SPARC64_D10_REGNUM, sparc64_floating_p(), sparc64_integral_or_pointer_p(), SPARC64_Q0_REGNUM, SPARC64_Q8_REGNUM, sparc64_store_floating_fields(), sparc64_structure_or_union_p(), SPARC_O0_REGNUM, TYPE_LENGTH, value_cast(), value_contents(), value_from_pointer(), value_type(), and write_memory().
Referenced by sparc64_push_dummy_call().
static void sparc64_store_floating_fields (struct regcache * regcache, struct type * type, const gdb_byte * valbuf, int element, int bitpos) [static]
Definition at line 641 of file sparc64-tdep.c.
References check_typedef(), gdb_assert, len, regcache_cooked_write(), regnum, sparc64_complex_floating_p(), SPARC64_D0_REGNUM, sparc64_floating_p(), SPARC64_Q0_REGNUM, sparc64_structure_or_union_p(), SPARC_F0_REGNUM, SPARC_F1_REGNUM, TYPE_FIELD_BITPOS, TYPE_FIELD_TYPE, TYPE_LENGTH, and TYPE_NFIELDS.
Referenced by sparc64_store_arguments(), and sparc64_store_return_value().
static void sparc64_store_return_value (struct type * type, struct regcache * regcache, const gdb_byte * valbuf) [static]
Definition at line 1070 of file sparc64-tdep.c.
References gdb_assert, len, memcpy(), memset(), regcache_cooked_write(), sparc64_complex_floating_p(), sparc64_floating_p(), sparc64_integral_or_pointer_p(), sparc64_store_floating_fields(), sparc64_structure_or_union_p(), SPARC_F0_REGNUM, SPARC_O0_REGNUM, TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_UNION, and TYPE_LENGTH.
Referenced by sparc64_return_value().
static int sparc64_structure_or_union_p (const struct type * type) [static]
Definition at line 132 of file sparc64-tdep.c.
References TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_STRUCT, and TYPE_CODE_UNION.
Referenced by sparc64_16_byte_align_p(), sparc64_extract_floating_fields(), sparc64_extract_return_value(), sparc64_store_arguments(), sparc64_store_floating_fields(), and sparc64_store_return_value().
void sparc64_supply_fpregset (const struct sparc_fpregset * fpregset, struct regcache * regcache, int regnum, const void * fpregs)
Definition at line 1451 of file sparc64-tdep.c.
References gdbarch_ptr_bit(), get_regcache_arch(), sparc_fpregset::r_f0_offset, sparc_fpregset::r_fsr_offset, regcache_raw_supply(), SPARC32_FSR_REGNUM, SPARC64_F32_REGNUM, SPARC64_FSR_REGNUM, and SPARC_F0_REGNUM.
Referenced by _initialize_sparc64_nat(), sparc64_linux_supply_core_fpregset(), sparc64fbsd_supply_fpregset(), sparc64nbsd_supply_fpregset(), sparc64obsd_supply_gregset(), and supply_fpregset().
void sparc64_supply_gregset (const struct sparc_gregset * gregset, struct regcache * regcache, int regnum, const void * gregs)
Definition at line 1224 of file sparc64-tdep.c.
References gdbarch::byte_order, extract_unsigned_integer(), gdbarch_byte_order(), gdbarch_ptr_bit(), get_regcache_arch(), memcpy(), memset(), offset, PSR_S, PSR_V8PLUS, sparc_gregset::r_g1_offset, sparc_gregset::r_l0_offset, sparc_gregset::r_npc_offset, sparc_gregset::r_pc_offset, sparc_gregset::r_y_offset, sparc_gregset::r_y_size, regcache_cooked_read_unsigned(), regcache_raw_supply(), sp, SPARC32_NPC_REGNUM, SPARC32_PC_REGNUM, SPARC32_PSR_REGNUM, SPARC32_Y_REGNUM, SPARC64_FPRS_REGNUM, SPARC64_NPC_REGNUM, SPARC64_PC_REGNUM, SPARC64_STATE_REGNUM, SPARC64_Y_REGNUM, SPARC_G0_REGNUM, SPARC_G1_REGNUM, SPARC_I7_REGNUM, SPARC_L0_REGNUM, SPARC_O7_REGNUM, SPARC_SP_REGNUM, sparc_supply_rwindow(), store_unsigned_integer(), TSTATE_CWP, TSTATE_ICC, TSTATE_XCC, and ULONGEST.
Referenced by _initialize_sparc64_nat(), sparc64_linux_supply_core_gregset(), sparc64fbsd_supply_gregset(), sparc64nbsd_supply_gregset(), sparc64obsd_supply_gregset(), and supply_gregset().
Variable Documentation
struct sparc_fpregset sparc64_bsd_fpregset
Initial value:
{
  0 * 8,
  32 * 8,
}
Definition at line 1526 of file sparc64-tdep.c.
Referenced by fill_fpregset(), sparc64_linux_collect_core_fpregset(), sparc64_linux_supply_core_fpregset(), sparc64fbsd_collect_fpregset(), sparc64fbsd_supply_fpregset(), sparc64nbsd_collect_fpregset(), sparc64nbsd_supply_fpregset(), sparc64obsd_supply_gregset(), and supply_fpregset().
struct frame_base sparc64_frame_base [static]
Initial value:
{
  &sparc64_frame_unwind,
  sparc64_frame_base_address,
  sparc64_frame_base_address,
  sparc64_frame_base_address
}
Definition at line 602 of file sparc64-tdep.c.
struct frame_unwind sparc64_frame_unwind [static]
Initial value:
{
  NORMAL_FRAME,
  default_frame_unwind_stop_reason,
  sparc64_frame_this_id,
  sparc64_frame_prev_register,
  NULL,
  default_frame_sniffer
}
Definition at line 582 of file sparc64-tdep.c.
const char* sparc64_pseudo_register_names[] [static]
Initial value:
{
  "cwp", "pstate", "asi", "ccr",
  "d0", "d2", "d4", "d6", "d8", "d10", "d12", "d14",
  "d16", "d18", "d20", "d22", "d24", "d26", "d28", "d30",
  "d32", "d34", "d36", "d38", "d40", "d42", "d44", "d46",
  "d48", "d50", "d52", "d54", "d56", "d58", "d60", "d62",
  "q0", "q4", "q8", "q12", "q16", "q20", "q24", "q28",
  "q32", "q36", "q40", "q44", "q48", "q52", "q56", "q60",
}
Definition at line 262 of file sparc64-tdep.c.
Referenced by sparc64_register_name().
const char* sparc64_register_names[] [static]
Initial value:
{
  "g0", "g1", "g2", "g3", "g4", "g5", "g6", "g7",
  "o0", "o1", "o2", "o3", "o4", "o5", "sp", "o7",
  "l0", "l1", "l2", "l3", "l4", "l5", "l6", "l7",
  "i0", "i1", "i2", "i3", "i4", "i5", "fp", "i7",
  "f0", "f1", "f2", "f3", "f4", "f5", "f6", "f7",
  "f8", "f9", "f10", "f11", "f12", "f13", "f14", "f15",
  "f16", "f17", "f18", "f19", "f20", "f21", "f22", "f23",
  "f24", "f25", "f26", "f27", "f28", "f29", "f30", "f31",
  "f32", "f34", "f36", "f38", "f40", "f42", "f44", "f46",
  "f48", "f50", "f52", "f54", "f56", "f58", "f60", "f62",
  "pc", "npc",
  "state",
  "fsr",
  "fprs",
  "y",
}
Definition at line 233 of file sparc64-tdep.c.
Referenced by sparc64_register_name().