GDB (xrefs): /home/stan/gdb/src/gdb/sparc-ravenscar-thread.c File Reference
/home/stan/gdb/src/gdb/sparc-ravenscar-thread.c File Reference
#include "defs.h"
#include "gdbcore.h"
#include "regcache.h"
#include "sparc-tdep.h"
#include "inferior.h"
#include "ravenscar-thread.h"
#include "sparc-ravenscar-thread.h"
Functions
static void sparc_ravenscar_fetch_registers (struct regcache *regcache, int regnum)
static void sparc_ravenscar_store_registers (struct regcache *regcache, int regnum)
static void sparc_ravenscar_prepare_to_store (struct regcache *regcache)
static void supply_register_at_address (struct regcache *regcache, int regnum, CORE_ADDR register_addr)
static int register_on_stack_p (int regnum)
static int register_in_thread_descriptor_p (int regnum)
void register_sparc_ravenscar_ops (struct gdbarch *gdbarch)
Variables
static const int sparc_register_offsets []
static struct ravenscar_arch_ops sparc_ravenscar_ops
Function Documentation
static int register_in_thread_descriptor_p (int regnum) [static]
Definition at line 88 of file sparc-ravenscar-thread.c.
References SPARC32_FSR_REGNUM, SPARC32_PC_REGNUM, SPARC32_PSR_REGNUM, SPARC32_WIM_REGNUM, SPARC32_Y_REGNUM, SPARC_F0_REGNUM, SPARC_G1_REGNUM, SPARC_G7_REGNUM, SPARC_O0_REGNUM, and SPARC_O7_REGNUM.
Referenced by sparc_ravenscar_fetch_registers(), and sparc_ravenscar_store_registers().
static int register_on_stack_p (int regnum) [static]
Definition at line 78 of file sparc-ravenscar-thread.c.
References SPARC_I0_REGNUM, SPARC_I7_REGNUM, SPARC_L0_REGNUM, and SPARC_L7_REGNUM.
Referenced by sparc_ravenscar_fetch_registers(), and sparc_ravenscar_store_registers().
void register_sparc_ravenscar_ops (struct gdbarch * gdbarch)
Definition at line 191 of file sparc-ravenscar-thread.c.
References set_gdbarch_ravenscar_ops().
Referenced by sparc32_gdbarch_init().
static void sparc_ravenscar_fetch_registers (struct regcache * regcache, int regnum) [static]
Definition at line 104 of file sparc-ravenscar-thread.c.
References gdbarch_num_regs(), gdbarch_sp_regnum(), get_regcache_arch(), inferior_ptid, gdbarch::num_regs, ptid_get_tid(), regcache_cooked_read_unsigned(), register_in_thread_descriptor_p(), register_on_stack_p(), sp_regnum, sparc_register_offsets, supply_register_at_address(), and ULONGEST.
static void sparc_ravenscar_prepare_to_store (struct regcache * regcache) [static]
Definition at line 147 of file sparc-ravenscar-thread.c.
static void sparc_ravenscar_store_registers (struct regcache * regcache, int regnum) [static]
Definition at line 156 of file sparc-ravenscar-thread.c.
References get_regcache_arch(), inferior_ptid, ptid_get_tid(), regcache_cooked_read_unsigned(), regcache_raw_collect(), register_in_thread_descriptor_p(), register_on_stack_p(), register_size(), regnum, sparc_register_offsets, SPARC_SP_REGNUM, ULONGEST, and write_memory().
static void supply_register_at_address (struct regcache * regcache, int regnum, CORE_ADDR register_addr) [static]
Definition at line 62 of file sparc-ravenscar-thread.c.
References get_regcache_arch(), read_memory(), regcache_raw_supply(), and register_size().
Referenced by sparc_ravenscar_fetch_registers().
Variable Documentation
struct ravenscar_arch_ops sparc_ravenscar_ops [static]
Initial value:
{
  sparc_ravenscar_fetch_registers,
  sparc_ravenscar_store_registers,
  sparc_ravenscar_prepare_to_store
}
Definition at line 181 of file sparc-ravenscar-thread.c.
const int sparc_register_offsets[] [static]
Initial value:
{
  -1,   0x24, 0x28, 0x2C, 0x30, 0x34, 0x38, 0x3C,
  0x00, 0x04, 0x08, 0x0C, 0x10, 0x14, 0x18, 0x1C,
  0x00, 0x04, 0x08, 0x0C, 0x10, 0x14, 0x18, 0x1C,
  0x20, 0x24, 0x28, 0x2C, 0x30, 0x34, 0x38, 0x3C,
  0x50, 0x54, 0x58, 0x5C, 0x60, 0x64, 0x68, 0x6C,
  0x70, 0x74, 0x78, 0x7C, 0x80, 0x84, 0x88, 0x8C,
  0x90, 0x94, 0x99, 0x9C, 0xA0, 0xA4, 0xA8, 0xAC,
  0xB0, 0xB4, 0xBB, 0xBC, 0xC0, 0xC4, 0xC8, 0xCC,
  0x40, 0x20, 0x44, -1,   0x1C, -1,   0x4C, -1
}
Definition at line 39 of file sparc-ravenscar-thread.c.
Referenced by sparc_ravenscar_fetch_registers(), and sparc_ravenscar_store_registers().