GDB (xrefs): /home/stan/gdb/src/gdb/sparc64nbsd-tdep.c File Reference
/home/stan/gdb/src/gdb/sparc64nbsd-tdep.c File Reference
#include "defs.h"
#include "frame.h"
#include "frame-unwind.h"
#include "gdbcore.h"
#include "osabi.h"
#include "regcache.h"
#include "regset.h"
#include "symtab.h"
#include "objfiles.h"
#include "solib-svr4.h"
#include "trad-frame.h"
#include "gdb_assert.h"
#include "gdb_string.h"
#include "sparc64-tdep.h"
#include "nbsd-tdep.h"
Functions
static void sparc64nbsd_supply_gregset (const struct regset *regset, struct regcache *regcache, int regnum, const void *gregs, size_t len)
static void sparc64nbsd_supply_fpregset (const struct regset *regset, struct regcache *regcache, int regnum, const void *fpregs, size_t len)
static int sparc64nbsd_pc_in_sigtramp (CORE_ADDR pc, const char *name)
struct trad_frame_saved_reg * sparc64nbsd_sigcontext_saved_regs (CORE_ADDR sigcontext_addr, struct frame_info *this_frame)
static struct sparc_frame_cache * sparc64nbsd_sigcontext_frame_cache (struct frame_info *this_frame, void **this_cache)
static void sparc64nbsd_sigcontext_frame_this_id (struct frame_info *this_frame, void **this_cache, struct frame_id *this_id)
static struct value * sparc64nbsd_sigcontext_frame_prev_register (struct frame_info *this_frame, void **this_cache, int regnum)
static int sparc64nbsd_sigtramp_frame_sniffer (const struct frame_unwind *self, struct frame_info *this_frame, void **this_cache)
static void sparc64nbsd_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
void _initialize_sparc64nbsd_tdep (void)
Variables
struct sparc_gregset sparc64nbsd_gregset
static const CORE_ADDR sparc64nbsd_sigtramp_start = 0xffffffffffffdee4ULL
static const CORE_ADDR sparc64nbsd_sigtramp_end = 0xffffffffffffe000ULL
static struct frame_unwind sparc64nbsd_sigcontext_frame_unwind
Function Documentation
void _initialize_sparc64nbsd_tdep (void)
Definition at line 269 of file sparc64nbsd-tdep.c.
References GDB_OSABI_NETBSD_ELF, gdbarch_register_osabi(), and sparc64nbsd_init_abi().
static void sparc64nbsd_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch) [static]
Definition at line 241 of file sparc64nbsd-tdep.c.
References find_solib_trampoline_target(), gdbarch_tdep::fpregset, frame_unwind_append_unwinder(), gdbarch_tdep(), gdbarch_tdep::gregset, regset_alloc(), set_gdbarch_skip_trampoline_code(), set_solib_svr4_fetch_link_map_offsets(), gdbarch_tdep::sizeof_fpregset, gdbarch_tdep::sizeof_gregset, sparc64_init_abi(), sparc64nbsd_supply_fpregset(), sparc64nbsd_supply_gregset(), sparcnbsd_step_trap(), gdbarch_tdep::step_trap, and svr4_lp64_fetch_link_map_offsets().
Referenced by _initialize_sparc64nbsd_tdep().
static int sparc64nbsd_pc_in_sigtramp (CORE_ADDR pc, const char * name) [static]
Definition at line 82 of file sparc64nbsd-tdep.c.
References nbsd_pc_in_sigtramp(), sparc64nbsd_sigtramp_end, and sparc64nbsd_sigtramp_start.
Referenced by sparc64nbsd_sigtramp_frame_sniffer().
static struct sparc_frame_cache* sparc64nbsd_sigcontext_frame_cache (struct frame_info * this_frame, void ** this_cache) [static, read]
Definition at line 155 of file sparc64nbsd-tdep.c.
References sparc_frame_cache::base, BIAS, gdb_assert, get_frame_register_unsigned(), sparc_frame_cache::pc, sparc_frame_cache::saved_regs, sparc64nbsd_sigcontext_saved_regs(), sparc64nbsd_sigtramp_start, SPARC_FP_REGNUM, sparc_frame_cache(), and sparc_record_save_insn().
Referenced by sparc64nbsd_sigcontext_frame_prev_register(), and sparc64nbsd_sigcontext_frame_this_id().
static struct value* sparc64nbsd_sigcontext_frame_prev_register (struct frame_info * this_frame, void ** this_cache, int regnum) [static, read]
Definition at line 202 of file sparc64nbsd-tdep.c.
References sparc_frame_cache::saved_regs, sparc64nbsd_sigcontext_frame_cache(), and trad_frame_get_prev_register().
static void sparc64nbsd_sigcontext_frame_this_id (struct frame_info * this_frame, void ** this_cache, struct frame_id * this_id) [static]
Definition at line 191 of file sparc64nbsd-tdep.c.
References sparc_frame_cache::base, frame_id_build(), sparc_frame_cache::pc, and sparc64nbsd_sigcontext_frame_cache().
struct trad_frame_saved_reg* sparc64nbsd_sigcontext_saved_regs (CORE_ADDR sigcontext_addr, struct frame_info * this_frame) [read]
Definition at line 91 of file sparc64nbsd-tdep.c.
References trad_frame_saved_reg::addr, BIAS, get_frame_arch(), get_frame_memory_unsigned(), trad_frame_saved_reg::realreg, regnum, sp, SPARC64_NPC_REGNUM, SPARC64_PC_REGNUM, SPARC64_STATE_REGNUM, SPARC64_Y_REGNUM, sparc_fetch_wcookie(), SPARC_G0_REGNUM, SPARC_G1_REGNUM, SPARC_G2_REGNUM, SPARC_G7_REGNUM, SPARC_I0_REGNUM, SPARC_I7_REGNUM, SPARC_L0_REGNUM, SPARC_L1_REGNUM, SPARC_O0_REGNUM, SPARC_O1_REGNUM, SPARC_O5_REGNUM, SPARC_O7_REGNUM, SPARC_SP_REGNUM, trad_frame_alloc_saved_regs(), trad_frame_set_value(), and ULONGEST.
Referenced by sparc64nbsd_sigcontext_frame_cache(), and sparc64obsd_frame_cache().
static int sparc64nbsd_sigtramp_frame_sniffer (const struct frame_unwind * self, struct frame_info * this_frame, void ** this_cache) [static]
Definition at line 212 of file sparc64nbsd-tdep.c.
References find_pc_partial_function(), get_frame_pc(), name, sparc_frame_cache::pc, and sparc64nbsd_pc_in_sigtramp().
static void sparc64nbsd_supply_fpregset (const struct regset * regset, struct regcache * regcache, int regnum, const void * fpregs, size_t len) [static]
Definition at line 63 of file sparc64nbsd-tdep.c.
References sparc64_bsd_fpregset, and sparc64_supply_fpregset().
Referenced by sparc64nbsd_init_abi().
static void sparc64nbsd_supply_gregset (const struct regset * regset, struct regcache * regcache, int regnum, const void * gregs, size_t len) [static]
Definition at line 55 of file sparc64nbsd-tdep.c.
References sparc64_supply_gregset().
Referenced by sparc64nbsd_init_abi().
Variable Documentation
struct sparc_gregset sparc64nbsd_gregset
Initial value:
{
  0 * 8,
  1 * 8,
  2 * 8,
  3 * 8,
  -1,
  -1,
  5 * 8,
  -1,
  4
}
Definition at line 40 of file sparc64nbsd-tdep.c.
Referenced by sparc64nbsd_collect_gregset(), and sparc64nbsd_supply_gregset().
struct frame_unwind sparc64nbsd_sigcontext_frame_unwind [static]
Initial value:
{
  SIGTRAMP_FRAME,
  default_frame_unwind_stop_reason,
  sparc64nbsd_sigcontext_frame_this_id,
  sparc64nbsd_sigcontext_frame_prev_register,
  NULL,
  sparc64nbsd_sigtramp_frame_sniffer
}
Definition at line 229 of file sparc64nbsd-tdep.c.
const CORE_ADDR sparc64nbsd_sigtramp_end = 0xffffffffffffe000ULL [static]
Definition at line 79 of file sparc64nbsd-tdep.c.
Referenced by sparc64nbsd_pc_in_sigtramp().
const CORE_ADDR sparc64nbsd_sigtramp_start = 0xffffffffffffdee4ULL [static]
Definition at line 78 of file sparc64nbsd-tdep.c.
Referenced by sparc64nbsd_pc_in_sigtramp(), and sparc64nbsd_sigcontext_frame_cache().