GDB (xrefs): /home/stan/gdb/src/gdb/sparc64nbsd-nat.c File Reference
/home/stan/gdb/src/gdb/sparc64nbsd-nat.c File Reference
#include "defs.h"
#include "gdbcore.h"
#include "regcache.h"
#include "target.h"
#include "sparc64-tdep.h"
#include "sparc-nat.h"
#include <sys/types.h>
#include <machine/pcb.h>
#include "bsd-kvm.h"
Functions
static void sparc64nbsd_supply_gregset (const struct sparc_gregset *gregset, struct regcache *regcache, int regnum, const void *gregs)
static void sparc64nbsd_collect_gregset (const struct sparc_gregset *gregset, const struct regcache *regcache, int regnum, void *gregs)
static void sparc64nbsd_supply_fpregset (const struct sparc_fpregset *fpregset, struct regcache *regcache, int regnum, const void *fpregs)
static void sparc64nbsd_collect_fpregset (const struct regcache *regcache, int regnum, void *fpregs)
static int sparc64nbsd_gregset_supplies_p (struct gdbarch *gdbarch, int regnum)
static int sparc64nbsd_fpregset_supplies_p (struct gdbarch *gdbarch, int regnum)
static int sparc64nbsd_supply_pcb (struct regcache *regcache, struct pcb *pcb)
void _initialize_sparc64nbsd_nat (void)
Function Documentation
void _initialize_sparc64nbsd_nat (void)
Definition at line 174 of file sparc64nbsd-nat.c.
References add_target(), bsd_kvm_add_target(), sparc64nbsd_collect_fpregset(), sparc64nbsd_collect_gregset(), sparc64nbsd_fpregset_supplies_p(), sparc64nbsd_gregset_supplies_p(), sparc64nbsd_supply_fpregset(), sparc64nbsd_supply_gregset(), sparc64nbsd_supply_pcb(), sparc_collect_fpregset, sparc_collect_gregset, sparc_fpregset_supplies_p, sparc_gregset_supplies_p, sparc_supply_fpregset, sparc_supply_gregset, and sparc_target().
static void sparc64nbsd_collect_fpregset (const struct regcache * regcache, int regnum, void * fpregs) [static]
Definition at line 72 of file sparc64nbsd-nat.c.
References gdbarch_ptr_bit(), get_regcache_arch(), sparc32_bsd_fpregset, sparc32_collect_fpregset(), sparc64_bsd_fpregset, and sparc64_collect_fpregset().
Referenced by _initialize_sparc64nbsd_nat().
static void sparc64nbsd_collect_gregset (const struct sparc_gregset * gregset, const struct regcache * regcache, int regnum, void * gregs) [static]
Definition at line 46 of file sparc64nbsd-nat.c.
References gdbarch_ptr_bit(), get_regcache_arch(), sparc32_collect_gregset(), sparc32nbsd_gregset, sparc64_collect_gregset(), and sparc64nbsd_gregset.
Referenced by _initialize_sparc64nbsd_nat().
static int sparc64nbsd_fpregset_supplies_p (struct gdbarch * gdbarch, int regnum) [static]
Definition at line 111 of file sparc64nbsd-nat.c.
References gdbarch_ptr_bit(), sparc32_fpregset_supplies_p(), SPARC64_F32_REGNUM, SPARC64_F62_REGNUM, SPARC64_FSR_REGNUM, SPARC_F0_REGNUM, and SPARC_F31_REGNUM.
Referenced by _initialize_sparc64nbsd_nat().
static int sparc64nbsd_gregset_supplies_p (struct gdbarch * gdbarch, int regnum) [static]
Definition at line 86 of file sparc64nbsd-nat.c.
References gdbarch_ptr_bit(), sparc32_gregset_supplies_p(), SPARC64_NPC_REGNUM, SPARC64_PC_REGNUM, SPARC64_STATE_REGNUM, SPARC64_Y_REGNUM, SPARC_G1_REGNUM, SPARC_G7_REGNUM, SPARC_I0_REGNUM, SPARC_I7_REGNUM, SPARC_L0_REGNUM, SPARC_L7_REGNUM, SPARC_O0_REGNUM, and SPARC_O7_REGNUM.
Referenced by _initialize_sparc64nbsd_nat().
static void sparc64nbsd_supply_fpregset (const struct sparc_fpregset * fpregset, struct regcache * regcache, int regnum, const void * fpregs) [static]
Definition at line 59 of file sparc64nbsd-nat.c.
References gdbarch_ptr_bit(), get_regcache_arch(), sparc32_bsd_fpregset, sparc32_supply_fpregset(), sparc64_bsd_fpregset, and sparc64_supply_fpregset().
Referenced by _initialize_sparc64nbsd_nat().
static void sparc64nbsd_supply_gregset (const struct sparc_gregset * gregset, struct regcache * regcache, int regnum, const void * gregs) [static]
Definition at line 33 of file sparc64nbsd-nat.c.
References gdbarch_ptr_bit(), get_regcache_arch(), sparc32_supply_gregset(), sparc32nbsd_gregset, sparc64_supply_gregset(), and sparc64nbsd_gregset.
Referenced by _initialize_sparc64nbsd_nat().
static int sparc64nbsd_supply_pcb (struct regcache * regcache, struct pcb * pcb) [static]
Definition at line 137 of file sparc64nbsd-nat.c.
References BIAS, read_memory(), regcache_raw_supply(), regnum, SPARC64_PC_REGNUM, SPARC64_STATE_REGNUM, SPARC_SP_REGNUM, and sparc_supply_rwindow().
Referenced by _initialize_sparc64nbsd_nat().