GDB (xrefs): /home/stan/gdb/src/gdb/sparcnbsd-tdep.c File Reference
/home/stan/gdb/src/gdb/sparcnbsd-tdep.c File Reference
#include "defs.h"
#include "frame.h"
#include "frame-unwind.h"
#include "gdbcore.h"
#include "gdbtypes.h"
#include "osabi.h"
#include "regcache.h"
#include "regset.h"
#include "solib-svr4.h"
#include "symtab.h"
#include "trad-frame.h"
#include "gdb_assert.h"
#include "gdb_string.h"
#include "sparc-tdep.h"
#include "nbsd-tdep.h"
Defines
#define X_RS1(i) (((i) >> 14) & 0x1f)
#define X_RS2(i) ((i) & 0x1f)
#define X_I(i) (((i) >> 13) & 1)
#define PSR_EF 0x00001000
#define GDB_OSABI_NETBSD_CORE GDB_OSABI_NETBSD_AOUT
Functions
static void sparc32nbsd_supply_gregset (const struct regset *regset, struct regcache *regcache, int regnum, const void *gregs, size_t len)
static void sparc32nbsd_supply_fpregset (const struct regset *regset, struct regcache *regcache, int regnum, const void *fpregs, size_t len)
static int sparc32nbsd_pc_in_sigtramp (CORE_ADDR pc, const char *name)
struct trad_frame_saved_reg * sparc32nbsd_sigcontext_saved_regs (struct frame_info *this_frame)
static struct sparc_frame_cache * sparc32nbsd_sigcontext_frame_cache (struct frame_info *this_frame, void **this_cache)
static void sparc32nbsd_sigcontext_frame_this_id (struct frame_info *this_frame, void **this_cache, struct frame_id *this_id)
static struct value * sparc32nbsd_sigcontext_frame_prev_register (struct frame_info *this_frame, void **this_cache, int regnum)
static int sparc32nbsd_sigcontext_frame_sniffer (const struct frame_unwind *self, struct frame_info *this_frame, void **this_cache)
CORE_ADDR sparcnbsd_step_trap (struct frame_info *frame, unsigned long insn)
static void sparc32nbsd_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
static void sparc32nbsd_aout_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
void sparc32nbsd_elf_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
static enum gdb_osabi sparcnbsd_aout_osabi_sniffer (bfd *abfd)
static enum gdb_osabi sparcnbsd_core_osabi_sniffer (bfd *abfd)
void _initialize_sparcnbsd_tdep (void)
Variables
struct sparc_gregset sparc32nbsd_gregset
static const CORE_ADDR sparc32nbsd_sigtramp_start = 0xeffffef0
static const CORE_ADDR sparc32nbsd_sigtramp_end = 0xeffffff0
static struct frame_unwind sparc32nbsd_sigcontext_frame_unwind
Define Documentation
#define GDB_OSABI_NETBSD_CORE GDB_OSABI_NETBSD_AOUT
Definition at line 341 of file sparcnbsd-tdep.c.
Referenced by sparcnbsd_core_osabi_sniffer().
#define PSR_EF 0x00001000
Referenced by sparc32nbsd_sigcontext_saved_regs().
#define X_I (i) (((i) >> 13) & 1)
Definition at line 42 of file sparcnbsd-tdep.c.
Referenced by sparcnbsd_step_trap().
#define X_RS1 (i) (((i) >> 14) & 0x1f)
Definition at line 40 of file sparcnbsd-tdep.c.
Referenced by sparcnbsd_step_trap().
#define X_RS2 (i) ((i) & 0x1f)
Definition at line 41 of file sparcnbsd-tdep.c.
Referenced by sparcnbsd_step_trap().
Function Documentation
void _initialize_sparcnbsd_tdep (void)
static void sparc32nbsd_aout_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch) [static]
Definition at line 308 of file sparcnbsd-tdep.c.
References sparc32nbsd_init_abi().
void sparc32nbsd_elf_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch)
Definition at line 314 of file sparcnbsd-tdep.c.
References set_solib_svr4_fetch_link_map_offsets(), sparc32nbsd_init_abi(), and svr4_ilp32_fetch_link_map_offsets().
Referenced by sparc32obsd_init_abi().
static void sparc32nbsd_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch) [static]
Definition at line 287 of file sparcnbsd-tdep.c.
References floatformats_ieee_double, gdbarch_tdep::fpregset, frame_unwind_append_unwinder(), gdbarch_tdep(), gdbarch_tdep::gregset, regset_alloc(), set_gdbarch_long_double_bit(), set_gdbarch_long_double_format(), gdbarch_tdep::sizeof_fpregset, gdbarch_tdep::sizeof_gregset, sparc32nbsd_supply_fpregset(), sparc32nbsd_supply_gregset(), sparcnbsd_step_trap(), and gdbarch_tdep::step_trap.
Referenced by sparc32nbsd_aout_init_abi(), and sparc32nbsd_elf_init_abi().
static int sparc32nbsd_pc_in_sigtramp (CORE_ADDR pc, const char * name) [static]
Definition at line 91 of file sparcnbsd-tdep.c.
References nbsd_pc_in_sigtramp(), sparc32nbsd_sigtramp_end, and sparc32nbsd_sigtramp_start.
Referenced by sparc32nbsd_sigcontext_frame_sniffer().
static struct sparc_frame_cache* sparc32nbsd_sigcontext_frame_cache (struct frame_info * this_frame, void ** this_cache) [static, read]
Definition at line 185 of file sparcnbsd-tdep.c.
References sparc_frame_cache::base, gdb_assert, get_frame_register_unsigned(), sparc_frame_cache::pc, sparc_frame_cache::saved_regs, sparc32nbsd_sigcontext_saved_regs(), sparc32nbsd_sigtramp_start, SPARC_FP_REGNUM, sparc_frame_cache(), and sparc_record_save_insn().
Referenced by sparc32nbsd_sigcontext_frame_prev_register(), and sparc32nbsd_sigcontext_frame_this_id().
static struct value* sparc32nbsd_sigcontext_frame_prev_register (struct frame_info * this_frame, void ** this_cache, int regnum) [static, read]
Definition at line 227 of file sparcnbsd-tdep.c.
References sparc_frame_cache::saved_regs, sparc32nbsd_sigcontext_frame_cache(), and trad_frame_get_prev_register().
static int sparc32nbsd_sigcontext_frame_sniffer (const struct frame_unwind * self, struct frame_info * this_frame, void ** this_cache) [static]
Definition at line 237 of file sparcnbsd-tdep.c.
References find_pc_partial_function(), get_frame_pc(), name, sparc_frame_cache::pc, and sparc32nbsd_pc_in_sigtramp().
static void sparc32nbsd_sigcontext_frame_this_id (struct frame_info * this_frame, void ** this_cache, struct frame_id * this_id) [static]
Definition at line 216 of file sparcnbsd-tdep.c.
References sparc_frame_cache::base, frame_id_build(), sparc_frame_cache::pc, and sparc32nbsd_sigcontext_frame_cache().
struct trad_frame_saved_reg* sparc32nbsd_sigcontext_saved_regs (struct frame_info * this_frame) [read]
Definition at line 100 of file sparcnbsd-tdep.c.
References trad_frame_saved_reg::addr, get_frame_arch(), get_frame_memory_unsigned(), get_frame_register_unsigned(), PSR_EF, trad_frame_saved_reg::realreg, regnum, sp, SPARC32_FSR_REGNUM, SPARC32_NPC_REGNUM, SPARC32_PC_REGNUM, SPARC32_PSR_REGNUM, SPARC32_Y_REGNUM, SPARC_F0_REGNUM, SPARC_F31_REGNUM, sparc_fetch_wcookie(), SPARC_FP_REGNUM, SPARC_G0_REGNUM, SPARC_G1_REGNUM, SPARC_G2_REGNUM, SPARC_G7_REGNUM, SPARC_I0_REGNUM, SPARC_I7_REGNUM, SPARC_L0_REGNUM, SPARC_L1_REGNUM, SPARC_O0_REGNUM, SPARC_O1_REGNUM, SPARC_O5_REGNUM, SPARC_O7_REGNUM, SPARC_SP_REGNUM, trad_frame_alloc_saved_regs(), trad_frame_set_value(), and ULONGEST.
Referenced by sparc32nbsd_sigcontext_frame_cache(), and sparc32obsd_sigtramp_frame_cache().
static void sparc32nbsd_supply_fpregset (const struct regset * regset, struct regcache * regcache, int regnum, const void * fpregs, size_t len) [static]
Definition at line 72 of file sparcnbsd-tdep.c.
References sparc32_bsd_fpregset, and sparc32_supply_fpregset().
Referenced by sparc32nbsd_init_abi().
static void sparc32nbsd_supply_gregset (const struct regset * regset, struct regcache * regcache, int regnum, const void * gregs, size_t len) [static]
Definition at line 57 of file sparcnbsd-tdep.c.
References sparc32_bsd_fpregset, sparc32_supply_fpregset(), and sparc32_supply_gregset().
Referenced by sparc32nbsd_init_abi().
static enum gdb_osabi sparcnbsd_aout_osabi_sniffer (bfd * abfd) [static]
Definition at line 323 of file sparcnbsd-tdep.c.
References GDB_OSABI_NETBSD_AOUT, and GDB_OSABI_UNKNOWN.
static enum gdb_osabi sparcnbsd_core_osabi_sniffer (bfd * abfd) [static]
Definition at line 345 of file sparcnbsd-tdep.c.
References GDB_OSABI_NETBSD_CORE, and GDB_OSABI_UNKNOWN.
CORE_ADDR sparcnbsd_step_trap (struct frame_info * frame, unsigned long insn)
Definition at line 268 of file sparcnbsd-tdep.c.
References get_frame_register_unsigned(), SPARC_G1_REGNUM, SPARC_G2_REGNUM, SPARC_G7_REGNUM, ULONGEST, X_I, X_RS1, and X_RS2.
Referenced by sparc32nbsd_init_abi(), sparc64nbsd_init_abi(), and sparc64obsd_init_abi().
Variable Documentation
struct sparc_gregset sparc32nbsd_gregset
Initial value:
{
  0 * 4,
  1 * 4,
  2 * 4,
  3 * 4,
  -1,
  -1,
  5 * 4,
  -1
}
Definition at line 44 of file sparcnbsd-tdep.c.
Referenced by _initialize_sparcnbsd_nat(), sparc64nbsd_collect_gregset(), and sparc64nbsd_supply_gregset().
struct frame_unwind sparc32nbsd_sigcontext_frame_unwind [static]
Initial value:
{
  SIGTRAMP_FRAME,
  default_frame_unwind_stop_reason,
  sparc32nbsd_sigcontext_frame_this_id,
  sparc32nbsd_sigcontext_frame_prev_register,
  NULL,
  sparc32nbsd_sigcontext_frame_sniffer
}
Definition at line 254 of file sparcnbsd-tdep.c.
const CORE_ADDR sparc32nbsd_sigtramp_end = 0xeffffff0 [static]
Definition at line 88 of file sparcnbsd-tdep.c.
Referenced by sparc32nbsd_pc_in_sigtramp().
const CORE_ADDR sparc32nbsd_sigtramp_start = 0xeffffef0 [static]
Definition at line 87 of file sparcnbsd-tdep.c.
Referenced by sparc32nbsd_pc_in_sigtramp(), and sparc32nbsd_sigcontext_frame_cache().