GDB (xrefs): /home/stan/gdb/src/gdb/stabsread.h File Reference
/home/stan/gdb/src/gdb/stabsread.h File Reference
Classes
struct pending_stabs
struct header_file
struct stab_section_list
Defines
#define EXTERN extern
#define HEADER_FILES(OBJFILE) (DBX_SYMFILE_INFO (OBJFILE)->header_files)
#define N_HEADER_FILES(OBJFILE) (DBX_SYMFILE_INFO (OBJFILE)->n_header_files)
#define N_ALLOCATED_HEADER_FILES(OBJFILE) (DBX_SYMFILE_INFO (OBJFILE)->n_allocated_header_files)
Functions
void common_block_start (char *, struct objfile *)
void common_block_end (struct objfile *)
void cleanup_undefined_stabs_types (struct objfile *)
long read_number (char **, int)
struct symbol * define_symbol (CORE_ADDR, char *, int, int, struct objfile *)
void stabsread_init (void)
void stabsread_new_init (void)
void start_stabs (void)
void end_stabs (void)
void finish_global_stabs (struct objfile *objfile)
struct partial_symtab * end_psymtab (struct objfile *objfile, struct partial_symtab *pst, const char **include_list, int num_includes, int capping_symbol_offset, CORE_ADDR capping_text, struct partial_symtab **dependency_list, int number_dependencies, int textlow_not_set)
void process_one_symbol (int, int, CORE_ADDR, char *, const struct section_offsets *, struct objfile *)
void elfstab_build_psymtabs (struct objfile *objfile, asection *stabsect, file_ptr stabstroffset, unsigned int stabstrsize)
void coffstab_build_psymtabs (struct objfile *objfile, CORE_ADDR textaddr, unsigned int textsize, struct stab_section_list *stabs, file_ptr stabstroffset, unsigned int stabstrsize)
void stabsect_build_psymtabs (struct objfile *objfile, char *stab_name, char *stabstr_name, char *text_name)
void elfstab_offset_sections (struct objfile *, struct partial_symtab *)
int symbol_reference_defined (char **)
void ref_add (int, struct symbol *, char *, CORE_ADDR)
struct symbol * ref_search (int)
void free_header_files (void)
void init_header_files (void)
Variables
EXTERN struct symbol * global_sym_chain [HASHSIZE]
EXTERN struct pending_stabs * global_stabs
EXTERN int previous_stab_code
EXTERN int * this_object_header_files
EXTERN int n_this_object_header_files
EXTERN int n_allocated_this_object_header_files
Define Documentation
#define EXTERN extern
Definition at line 30 of file stabsread.h.
#define HEADER_FILES (OBJFILE) (DBX_SYMFILE_INFO (OBJFILE)->header_files)
Definition at line 106 of file stabsread.h.
Referenced by add_new_header_file(), add_old_header_file(), and dbx_lookup_type().
#define N_ALLOCATED_HEADER_FILES (OBJFILE) (DBX_SYMFILE_INFO (OBJFILE)->n_allocated_header_files)
Definition at line 112 of file stabsread.h.
Referenced by add_new_header_file().
#define N_HEADER_FILES (OBJFILE) (DBX_SYMFILE_INFO (OBJFILE)->n_header_files)
Definition at line 109 of file stabsread.h.
Referenced by add_new_header_file(), add_old_header_file(), and dbx_lookup_type().
Function Documentation
void cleanup_undefined_stabs_types (struct objfile *)
Definition at line 4597 of file stabsread.c.
References cleanup_undefined_types_1(), and cleanup_undefined_types_noname().
Referenced by end_symtab_get_static_block().
void coffstab_build_psymtabs (struct objfile * objfile, CORE_ADDR textaddr, unsigned int textsize, struct stab_section_list * stabs, file_ptr stabstroffset, unsigned int stabstrsize)
Definition at line 3323 of file dbxread.c.
References _, buildsym_new_init(), COFF_STABS_SYMBOL_SIZE, DBX_STRINGTAB, DBX_STRINGTAB_SIZE, DBX_SYMBOL_SIZE, DBX_SYMCOUNT, DBX_SYMFILE_INFO, dbx_symfile_read(), DBX_SYMTAB_OFFSET, DBX_TEXT_ADDR, DBX_TEXT_SIZE, error(), free_header_files(), init_header_files(), name, stab_section_list::next, objfile::obfd, objfile::objfile_obstack, OBJSTAT, perror_with_name(), processing_acc_compilation, stab_section_list::section, and stabsread_new_init().
Referenced by coff_symfile_read().
void common_block_end (struct objfile *)
Definition at line 4338 of file stabsread.c.
References _, add_symbol_to_list(), allocate_symbol(), common_block, complaint(), global_sym_chain, hashname(), LOC_BLOCK, local_symbols, pending::next, pending::nsyms, pending::symbol, SYMBOL_ACLASS_INDEX, SYMBOL_LINKAGE_NAME, SYMBOL_SET_LINKAGE_NAME, SYMBOL_TYPE, SYMBOL_VALUE_CHAIN, and symfile_complaints.
Referenced by process_one_symbol(), and process_xcoff_symbol().
void common_block_start (char * , struct objfile *)
Definition at line 4322 of file stabsread.c.
References _, complaint(), local_symbols, pending::nsyms, objfile::objfile_obstack, and symfile_complaints.
Referenced by process_one_symbol(), and process_xcoff_symbol().
struct symbol* define_symbol (CORE_ADDR , char * , int , int , struct objfile *) [read]
Definition at line 626 of file stabsread.c.
References _, add_symbol_to_list(), allocate_symbol(), atof(), objfile_type::builtin_char, objfile_type::builtin_double, objfile_type::builtin_int, objfile_type::builtin_long, objfile_type::builtin_unsigned_int, complaint(), cp_canonicalize_string(), cp_scan_for_anonymous_namespaces(), create_array_type(), create_range_type(), current_subfile, error_type(), file_symbols, find_name_end(), gdbarch_believe_pcc_promotion(), gdbarch_byte_order(), gdbarch_int_bit(), gdbarch_stabs_argument_has_addr(), gdbarch_static_transform_name(), gdbarch_static_transform_name_p(), get_objfile_arch(), global_sym_chain, global_symbols, hashname(), is_cplus_marker(), subfile::language, language_ada, language_cplus, language_pascal, LOC_ARG, LOC_BLOCK, LOC_CONST, LOC_CONST_BYTES, LOC_LABEL, LOC_LOCAL, LOC_REF_ARG, LOC_REGISTER, LOC_REGPARM_ADDR, LOC_STATIC, LOC_TYPEDEF, local_symbols, lookup_function_type(), lookup_minimal_symbol(), lookup_pointer_type(), memcpy(), name, pending::nsyms, obconcat(), objfile::objfile_obstack, objfile_type(), p, processing_gcc_compilation, read_type(), stab_register_index, stab_regparm_index, store_typed_floating(), strchr(), string, STRUCT_DOMAIN, pending::symbol, SYMBOL_ACLASS_INDEX, SYMBOL_CLASS, SYMBOL_DOMAIN, SYMBOL_IS_ARGUMENT, SYMBOL_LANGUAGE, SYMBOL_LINE, SYMBOL_LINKAGE_NAME, SYMBOL_SET_LANGUAGE, SYMBOL_SET_LINKAGE_NAME, SYMBOL_SET_NAMES, SYMBOL_TYPE, SYMBOL_VALUE, SYMBOL_VALUE_ADDRESS, SYMBOL_VALUE_BYTES, SYMBOL_VALUE_CHAIN, symfile_complaints, TYPE_ALLOC, TYPE_BASECLASS, TYPE_BASECLASS_NAME, TYPE_CODE, TYPE_CODE_FUNC, TYPE_CODE_INT, TYPE_CODE_PTR, TYPE_CODE_STRUCT, TYPE_CODE_UNION, TYPE_CODE_VOID, TYPE_FIELD_ARTIFICIAL, TYPE_FIELD_TYPE, TYPE_FIELDS, TYPE_LENGTH, TYPE_N_BASECLASSES, TYPE_NAME, type_name_no_tag(), TYPE_NFIELDS, TYPE_PROTOTYPED, TYPE_TAG_NAME, TYPE_UNSIGNED, VAR_DOMAIN, vtbl_ptr_name, within_function, and xfree().
Referenced by process_one_symbol(), process_xcoff_symbol(), and read_xcoff_symtab().
void elfstab_build_psymtabs (struct objfile * objfile, asection * stabsect, file_ptr stabstroffset, unsigned int stabstrsize)
Definition at line 3414 of file dbxread.c.
References _, buildsym_new_init(), DBX_STAB_SECTION, DBX_STRINGTAB, DBX_STRINGTAB_SIZE, DBX_SYMBOL_SIZE, DBX_SYMCOUNT, DBX_SYMFILE_INFO, dbx_symfile_read(), DBX_SYMTAB_OFFSET, do_cleanups(), ELF_STABS_SYMBOL_SIZE, error(), find_text_range(), free_current_contents(), free_header_files(), init_header_files(), make_cleanup(), name, null_cleanup(), objfile::obfd, objfile::objfile_obstack, OBJSTAT, perror_with_name(), processing_acc_compilation, stabsread_new_init(), and symfile_relocate_debug_section().
Referenced by elf_symfile_read().
void elfstab_offset_sections (struct objfile * , struct partial_symtab *)
Definition at line 1426 of file elfread.c.
References _, complaint(), DBX_SYMFILE_INFO, stab_section_info::filename, partial_symtab::filename, stab_section_info::found, stab_section_info::next, stab_section_info::num_sections, objfile::num_sections, objfile::objfile_obstack, section_offsets::offsets, partial_symtab::section_offsets, stab_section_info::sections, SIZEOF_N_SECTION_OFFSETS, dbx_symfile_info::stab_section_info, and symfile_complaints.
Referenced by start_psymtab().
struct partial_symtab* end_psymtab (struct objfile * objfile, struct partial_symtab * pst, const char ** include_list, int num_includes, int capping_symbol_offset, CORE_ADDR capping_text, struct partial_symtab ** dependency_list, int number_dependencies, int textlow_not_set) [read]
Definition at line 2230 of file dbxread.c.
References ALL_OBJFILE_PSYMTABS, allocate_psymtab(), partial_symtab::dependencies, discard_psymtab(), partial_symtab::filename, gdbarch_sofun_address_maybe_missing(), get_objfile_arch(), objfile::global_psymbols, partial_symtab::globals_offset, has_line_numbers, last_function_name, LDSYMLEN, LDSYMOFF, psymbol_allocation_list::list, lookup_minimal_symbol(), memcpy(), MSYMBOL_SIZE, partial_symtab::n_global_syms, partial_symtab::n_static_syms, psymbol_allocation_list::next, partial_symtab::number_of_dependencies, objfile::objfile_obstack, p, partial_symtab::read_symtab, partial_symtab::read_symtab_private, partial_symtab::readin, partial_symtab::section_offsets, sort_pst_symbols(), objfile::static_psymbols, partial_symtab::statics_offset, strchr(), SYMBOL_VALUE_ADDRESS, partial_symtab::symtab, partial_symtab::texthigh, and partial_symtab::textlow.
Referenced by parse_partial_symbols(), and read_dbx_symtab().
void end_stabs (void)
Definition at line 4780 of file stabsread.c.
References previous_stab_code, type_vector_length, and xfree().
Referenced by process_one_symbol(), psymtab_to_symtab_1(), read_ofile_symtab(), and read_xcoff_symtab().
void finish_global_stabs (struct objfile * objfile)
Definition at line 4792 of file stabsread.c.
References global_stabs, global_symbols, patch_block_stabs(), and xfree().
Referenced by end_symtab_get_static_block().
void free_header_files (void)
Definition at line 311 of file dbxread.c.
References n_allocated_this_object_header_files, this_object_header_files, and xfree().
Referenced by coffstab_build_psymtabs(), dbx_symfile_finish(), elfstab_build_psymtabs(), mdebug_build_psymtabs(), and stabsect_build_psymtabs().
void init_header_files (void)
Definition at line 324 of file dbxread.c.
References n_allocated_this_object_header_files, this_object_header_files, and xmalloc().
Referenced by coffstab_build_psymtabs(), dbx_new_init(), elfstab_build_psymtabs(), mdebug_build_psymtabs(), and stabsect_build_psymtabs().
void process_one_symbol (int , int , CORE_ADDR , char * , const struct section_offsets * , struct objfile *)
Definition at line 2720 of file dbxread.c.
References _, add_new_header_file(), add_old_header_file(), ANOFFSET, block_address_function_relative, common_block_end(), common_block_start(), complaint(), context_stack_depth, cp_set_block_scope(), current_subfile, define_symbol(), subfile::dirname, end_stabs(), end_symtab(), find_stab_function_addr(), finish_block(), gdb_assert, gdbarch_addr_bits_remove(), gdbarch_sofun_address_maybe_missing(), get_last_source_file(), get_objfile_arch(), hex_string(), internal_error(), language_cplus, last_source_start_addr, lbrac_mismatch_complaint(), local_symbols, name, objfile::objfile_obstack, p, patch_subfile_names(), pop_context(), pop_subfile(), previous_stab_code, processing_gcc_compilation, push_context(), push_subfile(), record_debugformat(), record_line(), ref_add(), ref_search(), SECT_OFF_BSS, SECT_OFF_DATA, SECT_OFF_RODATA, SECT_OFF_TEXT, set_main_name(), start_stabs(), start_subfile(), start_symtab(), strchr(), SYMBOL_LANGUAGE, symbol_reference_defined(), symfile_complaints, symfile_relocatable, symnum, type, unknown_symtype_complaint(), and within_function.
Referenced by psymtab_to_symtab_1(), and read_ofile_symtab().
long read_number (char ** , int)
void ref_add (int , struct symbol * , char * , CORE_ADDR)
Definition at line 514 of file stabsread.c.
References MAX_CHUNK_REFS, memset(), ref_chunk, REF_CHUNK_SIZE, ref_count, REF_MAP_SIZE, ref_map::stabs, ref_map::sym, ref_map::value, and xrealloc().
Referenced by process_one_symbol().
struct symbol* ref_search (int) [read]
Definition at line 538 of file stabsread.c.
References ref_count, and ref_map::sym.
Referenced by process_one_symbol().
void stabsect_build_psymtabs (struct objfile * objfile, char * stab_name, char * stabstr_name, char * text_name)
Definition at line 3495 of file dbxread.c.
References _, buildsym_new_init(), dbx_objfile_data_key, DBX_STRINGTAB, DBX_STRINGTAB_SIZE, DBX_SYMBOL_SIZE, DBX_SYMCOUNT, dbx_symfile_read(), DBX_SYMTAB_OFFSET, DBX_TEXT_ADDR, DBX_TEXT_SIZE, error(), free_header_files(), init_header_files(), name, objfile::obfd, objfile::objfile_obstack, OBJSTAT, perror_with_name(), processing_acc_compilation, and stabsread_new_init().
Referenced by som_symfile_read().
void stabsread_init (void)
Definition at line 4746 of file stabsread.c.
Referenced by dbx_psymtab_to_symtab_1(), and xcoff_psymtab_to_symtab_1().
void stabsread_new_init (void)
Definition at line 4755 of file stabsread.c.
References global_sym_chain, and memset().
Referenced by coffstab_build_psymtabs(), dbx_new_init(), elf_new_init(), elfstab_build_psymtabs(), mdebug_build_psymtabs(), mipscoff_new_init(), som_new_init(), stabsect_build_psymtabs(), and xcoff_new_init().
void start_stabs (void)
Definition at line 4765 of file stabsread.c.
References global_stabs, n_this_object_header_files, and type_vector_length.
Referenced by process_one_symbol(), and read_xcoff_symtab().
int symbol_reference_defined (char **)
Definition at line 574 of file stabsread.c.
References p, process_reference(), and string.
Referenced by process_one_symbol().
Variable Documentation
EXTERN struct pending_stabs* global_stabs
Definition at line 55 of file stabsread.h.
Referenced by finish_global_stabs(), process_xcoff_symbol(), and start_stabs().
EXTERN struct symbol* global_sym_chain[HASHSIZE]
Definition at line 41 of file stabsread.h.
Referenced by common_block_end(), define_symbol(), parse_symbol(), scan_file_globals(), and stabsread_new_init().
EXTERN int n_allocated_this_object_header_files
Definition at line 129 of file stabsread.h.
Referenced by add_this_object_header_file(), free_header_files(), and init_header_files().
EXTERN int n_this_object_header_files
Definition at line 127 of file stabsread.h.
Referenced by add_this_object_header_file(), dbx_lookup_type(), and start_stabs().
EXTERN int previous_stab_code
Definition at line 60 of file stabsread.h.
Referenced by end_stabs(), process_one_symbol(), and psymtab_to_symtab_1().
EXTERN int* this_object_header_files
Definition at line 125 of file stabsread.h.
Referenced by add_this_object_header_file(), dbx_lookup_type(), free_header_files(), and init_header_files().