GDB (xrefs): /home/stan/gdb/src/gdb/stack.c File Reference
/home/stan/gdb/src/gdb/stack.c File Reference
#include "defs.h"
#include "value.h"
#include "symtab.h"
#include "gdbtypes.h"
#include "expression.h"
#include "language.h"
#include "frame.h"
#include "gdbcmd.h"
#include "gdbcore.h"
#include "target.h"
#include "source.h"
#include "breakpoint.h"
#include "demangle.h"
#include "inferior.h"
#include "annotate.h"
#include "ui-out.h"
#include "block.h"
#include "stack.h"
#include "dictionary.h"
#include "exceptions.h"
#include "reggroups.h"
#include "regcache.h"
#include "solib.h"
#include "valprint.h"
#include "gdbthread.h"
#include "cp-support.h"
#include "disasm.h"
#include "inline-frame.h"
#include "linespec.h"
#include "cli/cli-utils.h"
#include "gdb_assert.h"
#include <ctype.h>
#include "gdb_string.h"
#include "symfile.h"
#include "python/python.h"
Classes
struct print_variable_and_value_data
struct function_bounds
Functions
static void print_frame_local_vars (struct frame_info *, int, struct ui_file *)
static void print_frame (struct frame_info *frame, int print_level, enum print_what print_what, int print_args, struct symtab_and_line sal)
static void set_last_displayed_sal (int valid, struct program_space *pspace, CORE_ADDR addr, struct symtab *symtab, int line)
static int frame_show_address (struct frame_info *frame, struct symtab_and_line sal)
void print_stack_frame (struct frame_info *frame, int print_level, enum print_what print_what, int set_current_sal)
static void print_frame_nameless_args (struct frame_info *frame, long start, int num, int first, struct ui_file *stream)
static void print_frame_arg (const struct frame_arg *arg)
void read_frame_local (struct symbol *sym, struct frame_info *frame, struct frame_arg *argp)
void read_frame_arg (struct symbol *sym, struct frame_info *frame, struct frame_arg *argp, struct frame_arg *entryargp)
static void print_frame_args (struct symbol *func, struct frame_info *frame, int num, struct ui_file *stream)
void set_current_sal_from_frame (struct frame_info *frame, int center)
static void show_disassemble_next_line (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static void do_gdb_disassembly (struct gdbarch *gdbarch, int how_many, CORE_ADDR low, CORE_ADDR high)
void print_frame_info (struct frame_info *frame, int print_level, enum print_what print_what, int print_args, int set_current_sal)
void clear_last_displayed_sal (void)
int last_displayed_sal_is_valid (void)
struct program_space * get_last_displayed_pspace (void)
CORE_ADDR get_last_displayed_addr (void)
struct symtab * get_last_displayed_symtab (void)
int get_last_displayed_line (void)
void get_last_displayed_sal (struct symtab_and_line *sal)
void find_frame_funname (struct frame_info *frame, char **funname, enum language *funlang, struct symbol **funcp)
static void print_frame (struct frame_info *frame, int print_level, enum print_what print_what, int print_args, struct symtab_and_line sal)
static struct frame_info * parse_frame_specification_1 (const char *frame_exp, const char *message, int *selected_frame_p)
static struct frame_info * parse_frame_specification (char *frame_exp)
static void frame_info (char *addr_exp, int from_tty)
static void backtrace_command_1 (char *count_exp, int show_locals, int no_filters, int from_tty)
static void backtrace_command (char *arg, int from_tty)
static void backtrace_full_command (char *arg, int from_tty)
static void iterate_over_block_locals (struct block *b, iterate_over_block_arg_local_vars_cb cb, void *cb_data)
void iterate_over_block_local_vars (struct block *block, iterate_over_block_arg_local_vars_cb cb, void *cb_data)
static void do_print_variable_and_value (const char *print_name, struct symbol *sym, void *cb_data)
void locals_info (char *args, int from_tty)
void iterate_over_block_arg_vars (struct block *b, iterate_over_block_arg_local_vars_cb cb, void *cb_data)
static void print_frame_arg_vars (struct frame_info *frame, struct ui_file *stream)
void args_info (char *ignore, int from_tty)
static void args_plus_locals_info (char *ignore, int from_tty)
static void select_and_print_frame (struct frame_info *frame)
struct block * get_selected_block (CORE_ADDR *addr_in_block)
struct frame_info * find_relative_frame (struct frame_info *frame, int *level_offset_ptr)
void select_frame_command (char *level_exp, int from_tty)
static void frame_command (char *level_exp, int from_tty)
static void current_frame_command (char *level_exp, int from_tty)
static void up_silently_base (char *count_exp)
static void up_silently_command (char *count_exp, int from_tty)
static void up_command (char *count_exp, int from_tty)
static void down_silently_base (char *count_exp)
static void down_silently_command (char *count_exp, int from_tty)
static void down_command (char *count_exp, int from_tty)
void return_command (char *retval_exp, int from_tty)
static void func_command (char *arg, int from_tty)
enum language get_frame_language (void)
void _initialize_stack (void)
Variables
void(* deprecated_selected_frame_level_changed_hook)(int)
static const char *const print_frame_arguments_choices []
static const char * print_frame_arguments = "scalars"
static int print_raw_frame_arguments
const char print_entry_values_no [] = "no"
const char print_entry_values_only [] = "only"
const char print_entry_values_preferred [] = "preferred"
const char print_entry_values_if_needed [] = "if-needed"
const char print_entry_values_both [] = "both"
const char print_entry_values_compact [] = "compact"
const char print_entry_values_default [] = "default"
static const char *const print_entry_values_choices []
const char * print_entry_values = print_entry_values_default
int annotation_level = 0
static int last_displayed_sal_valid = 0
static struct program_space * last_displayed_pspace = 0
static CORE_ADDR last_displayed_addr = 0
static struct symtab * last_displayed_symtab = 0
static int last_displayed_line = 0
static enum auto_boolean disassemble_next_line
Function Documentation
void _initialize_stack (void)
void args_info (char * ignore, int from_tty)
Definition at line 2169 of file stack.c.
References _, gdb_stdout, get_selected_frame(), and print_frame_arg_vars().
Referenced by args_plus_locals_info(), and trace_dump_actions().
static void args_plus_locals_info (char * ignore, int from_tty) [static]
Definition at line 2177 of file stack.c.
References args_info(), and locals_info().
static void backtrace_command (char * arg, int from_tty) [static]
Definition at line 1834 of file stack.c.
References backtrace_command_1(), do_cleanups(), gdb_buildargv(), make_cleanup(), make_cleanup_freeargv(), null_cleanup(), subset_compare(), xfree(), and xmalloc().
static void backtrace_command_1 (char * count_exp, int show_locals, int no_filters, int from_tty) [static]
Definition at line 1683 of file stack.c.
References _, apply_frame_filter(), CLI_ALL_VALUES, CLI_SCALAR_VALUES, current_uiout, error(), find_pc_mapped_section(), find_pc_sect_symtab_via_partial(), flags, frame_find_by_id(), frame_stop_reason_string(), gdb_stdout, get_current_frame(), get_frame_address_in_block(), get_frame_id(), get_frame_unwind_stop_reason(), get_prev_frame(), info_verbose, LOCATION, NO_VALUES, parse_and_eval_long(), PRINT_ARGS, print_frame_arguments, PRINT_FRAME_INFO, print_frame_info(), print_frame_local_vars(), PRINT_LEVEL, PRINT_LOCALS, printf_filtered(), PY_BT_ERROR, PY_BT_NO_FILTERS, QUIT, target_has_stack, and warning().
Referenced by backtrace_command(), and backtrace_full_command().
static void backtrace_full_command (char * arg, int from_tty) [static]
Definition at line 1898 of file stack.c.
References backtrace_command_1().
void clear_last_displayed_sal (void)
Definition at line 952 of file stack.c.
References last_displayed_addr, last_displayed_line, and last_displayed_sal_valid.
Referenced by clear_symtab_users(), and set_last_displayed_sal().
static void current_frame_command (char * level_exp, int from_tty) [static]
Definition at line 2275 of file stack.c.
References _, get_selected_frame(), print_stack_frame(), and SRC_AND_LOC.
static void do_gdb_disassembly (struct gdbarch * gdbarch, int how_many, CORE_ADDR low, CORE_ADDR high) [static]
Definition at line 754 of file stack.c.
References current_uiout, DISASSEMBLY_RAW_INSN, exception_print(), gdb_disassembly(), gdb_stderr, gdb_exception::reason, RETURN_MASK_ERROR, and TRY_CATCH.
Referenced by print_frame_info().
static void do_print_variable_and_value (const char * print_name, struct symbol * sym, void * cb_data) [static]
Definition at line 2021 of file stack.c.
References _, frame_find_by_id(), print_variable_and_value_data::frame_id, print_variable_and_value_data::num_tabs, p, print_variable_and_value(), print_variable_and_value_data::stream, print_variable_and_value_data::values_printed, and warning().
Referenced by print_frame_arg_vars(), and print_frame_local_vars().
static void down_command (char * count_exp, int from_tty) [static]
Definition at line 2344 of file stack.c.
References down_silently_base(), get_selected_frame(), print_stack_frame(), and SRC_AND_LOC.
static void down_silently_base (char * count_exp) [static]
Definition at line 2315 of file stack.c.
References _, error(), find_relative_frame(), get_selected_frame(), parse_and_eval_long(), and select_frame().
Referenced by down_command(), and down_silently_command().
static void down_silently_command (char * count_exp, int from_tty) [static]
Definition at line 2338 of file stack.c.
References down_silently_base().
void find_frame_funname (struct frame_info * frame, char ** funname, enum language * funlang, struct symbol ** funcp)
Definition at line 1037 of file stack.c.
References block_inlined_p(), BLOCK_START, cp_remove_params(), func, get_frame_address_in_block(), get_frame_address_in_block_if_available(), get_frame_function(), language_cplus, language_unknown, lookup_minimal_symbol_by_pc(), memset(), bound_minimal_symbol::minsym, SYMBOL_BLOCK_VALUE, SYMBOL_LANGUAGE, SYMBOL_PRINT_NAME, SYMBOL_VALUE_ADDRESS, and xfree().
Referenced by ada_unhandled_exception_name_addr_from_raise(), frapy_name(), get_frame_name(), is_known_support_routine(), and print_frame().
struct frame_info* find_relative_frame (struct frame_info * frame, int * level_offset_ptr) [read]
Definition at line 2220 of file stack.c.
References get_next_frame(), get_prev_frame(), frame_info::next, and frame_info::prev.
Referenced by down_silently_base(), func_command(), mi_cmd_execute(), parse_frame_specification_1(), restore_selected_frame(), up_silently_base(), and wrap_find_relative_frame().
static void frame_command (char * level_exp, int from_tty) [static]
Definition at line 2266 of file stack.c.
References get_selected_frame(), print_stack_frame(), select_frame_command(), and SRC_AND_LOC.
Referenced by return_command().
static void frame_info (char * addr_exp, int from_tty) [static]
Definition at line 1394 of file stack.c.
References _, all_reggroup, cp_remove_params(), do_cleanups(), extract_unsigned_integer(), find_frame_sal(), fprintf_symbol_filtered(), fputs_filtered(), frame_register_unwind(), frame_relative_level(), frame_stop_reason_string(), frame_unwind_caller_pc_if_available(), func, gdb_assert, gdb_stdout, gdbarch_byte_order(), gdbarch_frame_num_args(), gdbarch_frame_num_args_p(), gdbarch_num_pseudo_regs(), gdbarch_num_regs(), gdbarch_pc_regnum(), gdbarch_register_name(), gdbarch_register_reggroup_p(), gdbarch_sp_regnum(), get_frame_arch(), get_frame_args_address(), get_frame_base(), get_frame_function(), get_frame_locals_address(), get_frame_pc(), get_frame_pc_if_available(), get_frame_type(), get_frame_unwind_stop_reason(), get_next_frame(), get_prev_frame(), INLINE_FRAME, symtab::language, language_cplus, language_str(), language_unknown, symtab_and_line::line, lookup_minimal_symbol_by_pc(), lval_memory, lval_register, make_cleanup(), MAX_REGISTER_SIZE, not_lval, null_cleanup(), paddress(), parse_frame_specification_1(), print_frame_args(), printf_filtered(), puts_filtered(), register_size(), sp, SYMBOL_LANGUAGE, SYMBOL_PRINT_NAME, symtab_and_line::symtab, symtab_to_filename_for_display(), TAILCALL_FRAME, wrap_here(), and xfree().
static int frame_show_address (struct frame_info * frame, struct symtab_and_line sal) [static]
Definition at line 129 of file stack.c.
References symtab_and_line::end, gdb_assert, get_frame_pc(), get_frame_type(), get_next_frame(), inferior_ptid, INLINE_FRAME, inline_skipped_frames(), symtab_and_line::line, and symtab_and_line::pc.
Referenced by print_frame(), and print_frame_info().
static void func_command (char * arg, int from_tty) [static]
Definition at line 2486 of file stack.c.
References _, current_program_space, DECODE_LINE_FUNFIRSTLINE, decode_line_with_current_source(), do_cleanups(), find_pc_partial_function(), find_relative_frame(), get_frame_pc(), get_selected_frame(), function_bounds::high, function_bounds::low, make_cleanup(), symtabs_and_lines::nelts, parse_frame_specification(), symtab_and_line::pc, printf_filtered(), symtab_and_line::pspace, symtabs_and_lines::sals, select_and_print_frame(), xfree(), and xmalloc().
enum language get_frame_language (void)
Definition at line 2542 of file stack.c.
References deprecated_safe_get_selected_frame(), gdb_exception::error, find_pc_symtab(), get_frame_address_in_block(), symtab::language, language_unknown, NOT_AVAILABLE_ERROR, gdb_exception::reason, RETURN_MASK_ERROR, throw_exception(), and TRY_CATCH.
Referenced by check_frame_language_change(), set_language_command(), and show_language_command().
CORE_ADDR get_last_displayed_addr (void)
Definition at line 984 of file stack.c.
References last_displayed_addr, and last_displayed_sal_valid.
Referenced by skip_function_command().
int get_last_displayed_line (void)
Definition at line 1004 of file stack.c.
References last_displayed_line, and last_displayed_sal_valid.
Referenced by decode_line_with_last_displayed(), parse_breakpoint_sals(), and until_break_command().
struct program_space* get_last_displayed_pspace (void) [read]
Definition at line 974 of file stack.c.
References last_displayed_pspace, and last_displayed_sal_valid.
void get_last_displayed_sal (struct symtab_and_line * sal)
Definition at line 1014 of file stack.c.
References last_displayed_addr, last_displayed_line, last_displayed_pspace, last_displayed_sal_valid, last_displayed_symtab, symtab_and_line::line, symtab_and_line::pc, symtab_and_line::pspace, and symtab_and_line::symtab.
Referenced by clear_command(), and parse_breakpoint_sals().
struct symtab* get_last_displayed_symtab (void) [read]
Definition at line 994 of file stack.c.
References last_displayed_sal_valid, and last_displayed_symtab.
Referenced by decode_line_with_last_displayed(), parse_breakpoint_sals(), skip_file_command(), and until_break_command().
struct block* get_selected_block (CORE_ADDR * addr_in_block) [read]
Definition at line 2202 of file stack.c.
References get_frame_block(), get_selected_frame(), and has_stack_frames().
Referenced by ada_find_any_type_symbol(), address_info(), cp_lookup_transparent_type(), display_info(), do_one_display(), evaluate_subexp_standard(), get_current_search_block(), get_var_value(), make_symbol_overload_list_namespace(), make_symbol_overload_list_qualified(), make_symbol_overload_list_using(), parse_exp_in_context_1(), VEC(), and write_object_renaming().
void iterate_over_block_arg_vars (struct block * b, iterate_over_block_arg_local_vars_cb cb, void * cb_data)
Definition at line 2098 of file stack.c.
References ALL_BLOCK_SYMBOLS, lookup_symbol(), SYMBOL_IS_ARGUMENT, SYMBOL_LINKAGE_NAME, SYMBOL_PRINT_NAME, and VAR_DOMAIN.
Referenced by add_local_symbols(), and print_frame_arg_vars().
void iterate_over_block_local_vars (struct block * block, iterate_over_block_arg_local_vars_cb cb, void * cb_data)
Definition at line 1991 of file stack.c.
References BLOCK_FUNCTION, BLOCK_SUPERBLOCK, and iterate_over_block_locals().
Referenced by add_local_symbols(), and print_frame_local_vars().
static void iterate_over_block_locals (struct block * b, iterate_over_block_arg_local_vars_cb cb, void * cb_data) [static]
Definition at line 1908 of file stack.c.
References ALL_BLOCK_SYMBOLS, COMMON_BLOCK_DOMAIN, LOC_COMPUTED, LOC_LOCAL, LOC_REGISTER, LOC_STATIC, SYMBOL_CLASS, SYMBOL_DOMAIN, SYMBOL_IS_ARGUMENT, and SYMBOL_PRINT_NAME.
Referenced by iterate_over_block_local_vars().
int last_displayed_sal_is_valid (void)
Definition at line 966 of file stack.c.
References last_displayed_sal_valid.
Referenced by decode_line_with_last_displayed(), parse_breakpoint_sals(), skip_function_command(), and until_break_command().
void locals_info (char * args, int from_tty)
Definition at line 2087 of file stack.c.
References _, gdb_stdout, get_selected_frame(), and print_frame_local_vars().
Referenced by args_plus_locals_info(), and trace_dump_actions().
static struct frame_info* parse_frame_specification (char * frame_exp) [static, read]
Definition at line 1385 of file stack.c.
References parse_frame_specification_1().
Referenced by func_command().
static struct frame_info* parse_frame_specification_1 (const char * frame_exp, const char * message, int * selected_frame_p) [static, read]
Definition at line 1263 of file stack.c.
References _, create_new_frame(), do_cleanups(), error(), find_relative_frame(), frame_id_build_wild(), frame_id_eq(), get_current_frame(), get_frame_id(), get_prev_frame(), get_selected_frame(), frame_info::level, make_cleanup(), p, parse_and_eval(), savestring(), skip_spaces_const(), value_as_address(), value_as_long(), and xfree().
Referenced by frame_info(), parse_frame_specification(), and select_frame_command().
static void print_frame (struct frame_info * frame, int print_level, enum print_what print_what, int print_args, struct symtab_and_line sal) [static]
Referenced by print_frame_info().
static void print_frame (struct frame_info * frame, int print_level, enum print_what print_what, int print_args, struct symtab_and_line sal) [static]
Definition at line 1129 of file stack.c.
References value_print_options::addressprint, annotate_frame_address(), annotate_frame_address_end(), annotate_frame_args(), annotate_frame_begin(), annotate_frame_function_name(), annotate_frame_source_begin(), annotate_frame_source_end(), annotate_frame_source_file(), annotate_frame_source_file_end(), annotate_frame_source_line(), annotate_frame_where(), current_uiout, do_cleanups(), find_frame_funname(), fprintf_symbol_filtered(), frame_relative_level(), frame_show_address(), func, gdb_assert, gdb_stdout, gdbarch_frame_num_args(), gdbarch_frame_num_args_p(), get_frame_arch(), get_frame_pc(), get_frame_pc_if_available(), get_frame_program_space(), get_user_print_options(), language_unknown, symtab_and_line::line, LOC_AND_ADDRESS, make_cleanup(), make_cleanup_ui_file_delete(), make_cleanup_ui_out_list_begin_end(), make_cleanup_ui_out_tuple_begin_end(), mem_fileopen(), print_frame_args(), QUIT, RETURN_MASK_ERROR, solib_name_from_address(), symtab_and_line::symtab, symtab_to_filename_for_display(), symtab_to_fullname(), TRY_CATCH, ui_left, ui_out_field_core_addr(), ui_out_field_fmt_int(), ui_out_field_int(), ui_out_field_stream(), ui_out_field_string(), ui_out_is_mi_like_p(), ui_out_text(), ui_out_wrap_hint(), and xfree().
static void print_frame_arg (const struct frame_arg * arg) [static]
Definition at line 215 of file stack.c.
References _, annotate_arg_begin(), annotate_arg_end(), annotate_arg_name_end(), annotate_arg_value(), common_val_print(), current_language, current_uiout, value_print_options::deref_ref, do_cleanups(), frame_arg::entry_kind, frame_arg::error, fprintf_filtered(), fprintf_symbol_filtered(), fputs_filtered(), gdb_assert, get_no_prettyformat_print_options(), language_def(), language_mode_auto, make_cleanup_ui_file_delete(), make_cleanup_ui_out_tuple_begin_end(), mem_fileopen(), gdb_exception::message, print_entry_values_compact, print_entry_values_no, print_entry_values_only, print_frame_arguments, print_raw_frame_arguments, value_print_options::raw, RETURN_MASK_ERROR, value_print_options::summary, frame_arg::sym, SYMBOL_LANGUAGE, SYMBOL_PRINT_NAME, TRY_CATCH, ui_out_field_stream(), ui_out_is_mi_like_p(), ui_out_text(), frame_arg::val, and value_type().
Referenced by print_frame_args().
static void print_frame_arg_vars (struct frame_info * frame, struct ui_file * stream) [static]
Definition at line 2134 of file stack.c.
References _, do_print_variable_and_value(), fprintf_filtered(), print_variable_and_value_data::frame_id, func, gdb_stdout, get_frame_function(), get_frame_id(), get_frame_pc_if_available(), iterate_over_block_arg_vars(), print_variable_and_value_data::num_tabs, print_variable_and_value_data::stream, SYMBOL_BLOCK_VALUE, and print_variable_and_value_data::values_printed.
Referenced by args_info().
static void print_frame_args (struct symbol * func, struct frame_info * frame, int num, struct ui_file * stream) [static]
Definition at line 521 of file stack.c.
References ALL_BLOCK_SYMBOLS, current_uiout, do_cleanups(), frame_arg::entry_kind, frame_arg::error, gdb_assert, gdbarch_frame_args_skip(), get_frame_arch(), int, LOC_ARG, LOC_COMPUTED, LOC_OPTIMIZED_OUT, LOC_REF_ARG, LOC_REGISTER, LOC_REGPARM_ADDR, lookup_symbol(), make_cleanup_ui_file_delete(), mem_fileopen(), memset(), print_entry_values_no, print_entry_values_only, print_frame_arg(), print_frame_arguments, print_frame_nameless_args(), QUIT, read_frame_arg(), frame_arg::sym, SYMBOL_BLOCK_VALUE, SYMBOL_CLASS, SYMBOL_IS_ARGUMENT, SYMBOL_LINKAGE_NAME, SYMBOL_TYPE, SYMBOL_VALUE, TYPE_LENGTH, ui_out_text(), ui_out_wrap_hint(), VAR_DOMAIN, and xfree().
Referenced by frame_info(), and print_frame().
void print_frame_info (struct frame_info * frame, int print_level, enum print_what print_what , int print_args, int set_current_sal)
Definition at line 785 of file stack.c.
References value_print_options::addressprint, annotate_frame_address(), annotate_frame_address_end(), annotate_frame_begin(), annotate_frame_end(), annotate_function_call(), annotate_signal_handler_caller(), annotation_level, ARCH_FRAME, AUTO_BOOLEAN_AUTO, AUTO_BOOLEAN_TRUE, current_uiout, deprecated_print_frame_info_listing_hook, disassemble_next_line, do_cleanups(), do_gdb_disassembly(), DUMMY_FRAME, symtab_and_line::end, find_frame_sal(), frame_relative_level(), frame_show_address(), gdb_flush(), gdb_stdout, get_frame_arch(), get_frame_pc(), get_frame_pc_if_available(), get_frame_type(), get_user_print_options(), identify_source_line(), symtab_and_line::line, LOC_AND_ADDRESS, LOCATION, make_cleanup_ui_out_tuple_begin_end(), symtab_and_line::pc, print_frame(), print_source_lines(), symtab_and_line::pspace, set_last_displayed_sal(), SIGTRAMP_FRAME, SRC_AND_LOC, SRC_LINE, symtab_and_line::symtab, ui_left, ui_out_field_core_addr(), ui_out_field_fmt_int(), ui_out_field_string(), ui_out_is_mi_like_p(), and ui_out_text().
Referenced by backtrace_command_1(), mi_cmd_stack_info_frame(), mi_cmd_stack_list_frames(), print_stack_frame(), and py_print_frame().
static void print_frame_local_vars (struct frame_info * frame, int num_tabs, struct ui_file * stream) [static]
Definition at line 2049 of file stack.c.
References _, do_print_variable_and_value(), fprintf_filtered(), print_variable_and_value_data::frame_id, get_frame_block(), get_frame_id(), get_frame_pc_if_available(), iterate_over_block_local_vars(), print_variable_and_value_data::num_tabs, print_variable_and_value_data::stream, and print_variable_and_value_data::values_printed.
Referenced by backtrace_command_1(), and locals_info().
static void print_frame_nameless_args (struct frame_info * frame, long start, int num, int first, struct ui_file * stream) [static]
Definition at line 183 of file stack.c.
References gdbarch::byte_order, fprintf_filtered(), gdbarch_byte_order(), get_frame_arch(), get_frame_args_address(), int, QUIT, and read_memory_integer().
Referenced by print_frame_args().
void print_stack_frame (struct frame_info * frame, int print_level, enum print_what print_what , int set_current_sal)
Definition at line 156 of file stack.c.
References current_uiout, LOC_AND_ADDRESS, print_frame_info(), RETURN_MASK_ERROR, set_current_sal_from_frame(), SRC_AND_LOC, SRC_LINE, TRY_CATCH, and ui_out_is_mi_like_p().
Referenced by bsd_kvm_open(), bsd_kvm_pcb_cmd(), bsd_kvm_proc_cmd(), core_open(), current_frame_command(), do_captured_thread_select(), down_command(), finish_command(), frame_command(), inferior_command(), kill_command(), linux_fork_context(), mi_cmd_exec_return(), mi_cmd_trace_find(), mi_on_normal_stop(), normal_stop(), print_thread_info(), record_full_goto_entry(), record_full_restore(), restore_selected_frame(), select_and_print_frame(), task_command_1(), tfind_1(), and up_command().
void read_frame_arg (struct symbol * sym, struct frame_info * frame, struct frame_arg * argp, struct frame_arg * entryargp)
Definition at line 332 of file stack.c.
References allocate_optimized_out_value(), coerce_ref(), current_uiout, frame_arg::entry_kind, gdb_exception::error, frame_arg::error, gdb_assert, gdb_exception::message, NO_ENTRY_VALUE_ERROR, print_entry_values, print_entry_values_both, print_entry_values_compact, print_entry_values_default, print_entry_values_if_needed, print_entry_values_no, print_entry_values_only, print_entry_values_preferred, read_var_value(), symbol_computed_ops::read_variable_at_entry, RETURN_MASK_ERROR, frame_arg::sym, SYMBOL_COMPUTED_OPS, SYMBOL_TYPE, TRY_CATCH, TYPE_LENGTH, ui_out_is_mi_like_p(), frame_arg::val, value_available_contents_eq(), value_fetch_lazy(), value_lazy(), value_optimized_out(), and value_type().
Referenced by enumerate_args(), list_args_or_locals(), and print_frame_args().
void read_frame_local (struct symbol * sym, struct frame_info * frame, struct frame_arg * argp)
Definition at line 311 of file stack.c.
References frame_arg::error, gdb_exception::message, read_var_value(), RETURN_MASK_ERROR, frame_arg::sym, TRY_CATCH, and frame_arg::val.
Referenced by list_args_or_locals().
void return_command (char * retval_exp, int from_tty)
Definition at line 2352 of file stack.c.
References _, CHECK_TYPEDEF, do_cleanups(), DUMMY_FRAME, expression::elts, error(), evaluate_expression(), frame_command(), frame_pop(), gdb_assert, gdbarch_return_value(), get_current_frame(), get_current_regcache(), get_frame_arch(), get_frame_function(), get_frame_type(), get_regcache_arch(), get_selected_frame(), INLINE_FRAME, make_cleanup(), exp_element::opcode, parse_expression(), query(), read_var_value(), RETURN_VALUE_ABI_RETURNS_ADDRESS, RETURN_VALUE_REGISTER_CONVENTION, RETURN_VALUE_STRUCT_CONVENTION, select_frame_command(), struct_return_convention(), SYMBOL_PRINT_NAME, SYMBOL_TYPE, TYPE_CODE, TYPE_CODE_VOID, TYPE_TARGET_TYPE, value_cast(), value_contents(), value_fetch_lazy(), value_lazy(), value_type(), and xfree().
Referenced by mi_cmd_exec_return().
static void select_and_print_frame (struct frame_info * frame) [static]
Definition at line 2187 of file stack.c.
References print_stack_frame(), select_frame(), and SRC_AND_LOC.
Referenced by func_command().
void select_frame_command (char * level_exp, int from_tty)
Definition at line 2256 of file stack.c.
References parse_frame_specification_1(), and select_frame().
Referenced by frame_command(), mi_cmd_stack_select_frame(), and return_command().
void set_current_sal_from_frame (struct frame_info * frame, int center)
Definition at line 718 of file stack.c.
References find_frame_sal(), get_lines_to_list(), symtab_and_line::line, max, set_current_source_symtab_and_line(), and symtab_and_line::symtab.
Referenced by normal_stop(), and print_stack_frame().
static void set_last_displayed_sal (int valid, struct program_space * pspace, CORE_ADDR addr, struct symtab * symtab, int line) [static]
Definition at line 932 of file stack.c.
References _, clear_last_displayed_sal(), internal_error(), last_displayed_addr, last_displayed_line, last_displayed_sal_valid, and line.
Referenced by print_frame_info().
static void show_disassemble_next_line (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 740 of file stack.c.
References _, and fprintf_filtered().
static void up_command (char * count_exp, int from_tty) [static]
Definition at line 2305 of file stack.c.
References get_selected_frame(), print_stack_frame(), SRC_AND_LOC, and up_silently_base().
static void up_silently_base (char * count_exp) [static]
Definition at line 2284 of file stack.c.
References _, error(), find_relative_frame(), get_selected_frame(), parse_and_eval_long(), and select_frame().
Referenced by up_command(), and up_silently_command().
static void up_silently_command (char * count_exp, int from_tty) [static]
Definition at line 2299 of file stack.c.
References up_silently_base().
Variable Documentation
int annotation_level = 0
Definition at line 114 of file stack.c.
Referenced by annotate_arg_begin(), annotate_arg_end(), annotate_arg_name_end(), annotate_arg_value(), annotate_array_section_begin(), annotate_array_section_end(), annotate_breakpoint(), annotate_breakpoints_headers(), annotate_breakpoints_invalid(), annotate_breakpoints_table(), annotate_breakpoints_table_end(), annotate_catchpoint(), annotate_display_begin(), annotate_display_end(), annotate_display_expression(), annotate_display_expression_end(), annotate_display_format(), annotate_display_number_end(), annotate_display_value(), annotate_elt(), annotate_elt_rep(), annotate_elt_rep_end(), annotate_error(), annotate_error_begin(), annotate_exited(), annotate_field(), annotate_field_begin(), annotate_field_end(), annotate_field_name_end(), annotate_field_value(), annotate_frame_address(), annotate_frame_address_end(), annotate_frame_args(), annotate_frame_begin(), annotate_frame_end(), annotate_frame_function_name(), annotate_frame_source_begin(), annotate_frame_source_end(), annotate_frame_source_file(), annotate_frame_source_file_end(), annotate_frame_source_line(), annotate_frame_where(), annotate_frames_invalid(), annotate_function_call(), annotate_new_thread(), annotate_quit(), annotate_record(), annotate_signal(), annotate_signal_handler_caller(), annotate_signal_name(), annotate_signal_name_end(), annotate_signal_string(), annotate_signal_string_end(), annotate_signalled(), annotate_source(), annotate_starting(), annotate_stopped(), annotate_thread_changed(), annotate_value_begin(), annotate_value_end(), annotate_value_history_begin(), annotate_value_history_end(), annotate_value_history_value(), annotate_watchpoint(), ATTRIBUTE_PRINTF(), captured_main(), command_line_handler(), command_line_input(), init_main(), line_info(), print_frame_info(), prompt_for_continue(), and top_level_prompt().
void(* deprecated_selected_frame_level_changed_hook)(int)
Definition at line 58 of file stack.c.
Referenced by gdbtk_add_hooks(), select_frame(), tui_install_hooks(), and tui_remove_hooks().
enum auto_boolean disassemble_next_line [static]
Definition at line 737 of file stack.c.
Referenced by print_frame_info().
CORE_ADDR last_displayed_addr = 0 [static]
Definition at line 120 of file stack.c.
Referenced by clear_last_displayed_sal(), get_last_displayed_addr(), get_last_displayed_sal(), and set_last_displayed_sal().
int last_displayed_line = 0 [static]
Definition at line 122 of file stack.c.
Referenced by clear_last_displayed_sal(), get_last_displayed_line(), get_last_displayed_sal(), and set_last_displayed_sal().
struct program_space* last_displayed_pspace = 0 [static]
Definition at line 119 of file stack.c.
Referenced by get_last_displayed_pspace(), and get_last_displayed_sal().
int last_displayed_sal_valid = 0 [static]
Definition at line 118 of file stack.c.
Referenced by clear_last_displayed_sal(), get_last_displayed_addr(), get_last_displayed_line(), get_last_displayed_pspace(), get_last_displayed_sal(), get_last_displayed_symtab(), last_displayed_sal_is_valid(), and set_last_displayed_sal().
struct symtab* last_displayed_symtab = 0 [static]
Definition at line 121 of file stack.c.
Referenced by get_last_displayed_sal(), and get_last_displayed_symtab().
const char* print_entry_values = print_entry_values_default
Definition at line 91 of file stack.c.
Referenced by read_frame_arg().
const char print_entry_values_both[] = "both"
Definition at line 77 of file stack.c.
Referenced by read_frame_arg().
const char* const print_entry_values_choices[] [static]
Initial value:
{
  print_entry_values_no,
  print_entry_values_only,
  print_entry_values_preferred,
  print_entry_values_if_needed,
  print_entry_values_both,
  print_entry_values_compact,
  print_entry_values_default,
  NULL
}
Definition at line 80 of file stack.c.
const char print_entry_values_compact[] = "compact"
Definition at line 78 of file stack.c.
Referenced by print_frame_arg(), py_print_single_arg(), and read_frame_arg().
const char print_entry_values_default[] = "default"
Definition at line 79 of file stack.c.
Referenced by read_frame_arg().
const char print_entry_values_if_needed[] = "if-needed"
Definition at line 76 of file stack.c.
Referenced by read_frame_arg().
const char print_entry_values_no[] = "no"
Definition at line 73 of file stack.c.
Referenced by enumerate_args(), list_arg_or_local(), list_args_or_locals(), print_frame_arg(), print_frame_args(), and read_frame_arg().
const char print_entry_values_only[] = "only"
Definition at line 74 of file stack.c.
Referenced by enumerate_args(), list_arg_or_local(), list_args_or_locals(), print_frame_arg(), print_frame_args(), py_print_single_arg(), and read_frame_arg().
const char print_entry_values_preferred[] = "preferred"
Definition at line 75 of file stack.c.
Referenced by read_frame_arg().
const char* print_frame_arguments = "scalars" [static]
Definition at line 65 of file stack.c.
Referenced by backtrace_command_1(), print_frame_arg(), and print_frame_args().
const char* const print_frame_arguments_choices[] [static]
Initial value:
  {"all", "scalars", "none", NULL}
Definition at line 63 of file stack.c.
int print_raw_frame_arguments [static]
Definition at line 68 of file stack.c.
Referenced by print_frame_arg().