GDB (xrefs): /home/stan/gdb/src/gdb/stack.h File Reference
/home/stan/gdb/src/gdb/stack.h File Reference
Typedefs
typedef void(* iterate_over_block_arg_local_vars_cb)(const char *print_name, struct symbol *sym, void *cb_data)
Functions
void select_frame_command (char *level_exp, int from_tty)
void find_frame_funname (struct frame_info *frame, char **funname, enum language *funlang, struct symbol **funcp)
void iterate_over_block_arg_vars (struct block *block, iterate_over_block_arg_local_vars_cb cb, void *cb_data)
void iterate_over_block_local_vars (struct block *block, iterate_over_block_arg_local_vars_cb cb, void *cb_data)
void clear_last_displayed_sal (void)
int last_displayed_sal_is_valid (void)
struct program_space * get_last_displayed_pspace (void)
CORE_ADDR get_last_displayed_addr (void)
struct symtab * get_last_displayed_symtab (void)
int get_last_displayed_line (void)
void get_last_displayed_sal (struct symtab_and_line *sal)
Typedef Documentation
typedef void(* iterate_over_block_arg_local_vars_cb)(const char *print_name, struct symbol *sym, void *cb_data)
Definition at line 28 of file stack.h.
Function Documentation
void clear_last_displayed_sal (void)
Definition at line 952 of file stack.c.
References last_displayed_addr, last_displayed_line, and last_displayed_sal_valid.
Referenced by clear_symtab_users(), and set_last_displayed_sal().
void find_frame_funname (struct frame_info * frame, char ** funname, enum language * funlang, struct symbol ** funcp)
Definition at line 1037 of file stack.c.
References block_inlined_p(), BLOCK_START, cp_remove_params(), func, get_frame_address_in_block(), get_frame_address_in_block_if_available(), get_frame_function(), language_cplus, language_unknown, lookup_minimal_symbol_by_pc(), memset(), bound_minimal_symbol::minsym, SYMBOL_BLOCK_VALUE, SYMBOL_LANGUAGE, SYMBOL_PRINT_NAME, SYMBOL_VALUE_ADDRESS, and xfree().
Referenced by ada_unhandled_exception_name_addr_from_raise(), frapy_name(), get_frame_name(), is_known_support_routine(), and print_frame().
CORE_ADDR get_last_displayed_addr (void)
Definition at line 984 of file stack.c.
References last_displayed_addr, and last_displayed_sal_valid.
Referenced by skip_function_command().
int get_last_displayed_line (void)
Definition at line 1004 of file stack.c.
References last_displayed_line, and last_displayed_sal_valid.
Referenced by decode_line_with_last_displayed(), parse_breakpoint_sals(), and until_break_command().
struct program_space* get_last_displayed_pspace (void) [read]
Definition at line 974 of file stack.c.
References last_displayed_pspace, and last_displayed_sal_valid.
void get_last_displayed_sal (struct symtab_and_line * sal)
Definition at line 1014 of file stack.c.
References last_displayed_addr, last_displayed_line, last_displayed_pspace, last_displayed_sal_valid, last_displayed_symtab, symtab_and_line::line, symtab_and_line::pc, symtab_and_line::pspace, and symtab_and_line::symtab.
Referenced by clear_command(), and parse_breakpoint_sals().
struct symtab* get_last_displayed_symtab (void) [read]
Definition at line 994 of file stack.c.
References last_displayed_sal_valid, and last_displayed_symtab.
Referenced by decode_line_with_last_displayed(), parse_breakpoint_sals(), skip_file_command(), and until_break_command().
void iterate_over_block_arg_vars (struct block * block, iterate_over_block_arg_local_vars_cb cb, void * cb_data)
Definition at line 2098 of file stack.c.
References ALL_BLOCK_SYMBOLS, lookup_symbol(), SYMBOL_IS_ARGUMENT, SYMBOL_LINKAGE_NAME, SYMBOL_PRINT_NAME, and VAR_DOMAIN.
Referenced by add_local_symbols(), and print_frame_arg_vars().
void iterate_over_block_local_vars (struct block * block, iterate_over_block_arg_local_vars_cb cb, void * cb_data)
Definition at line 1991 of file stack.c.
References BLOCK_FUNCTION, BLOCK_SUPERBLOCK, and iterate_over_block_locals().
Referenced by add_local_symbols(), and print_frame_local_vars().
int last_displayed_sal_is_valid (void)
Definition at line 966 of file stack.c.
References last_displayed_sal_valid.
Referenced by decode_line_with_last_displayed(), parse_breakpoint_sals(), skip_function_command(), and until_break_command().
void select_frame_command (char * level_exp, int from_tty)
Definition at line 2256 of file stack.c.
References parse_frame_specification_1(), and select_frame().
Referenced by frame_command(), mi_cmd_stack_select_frame(), and return_command().