GDB (xrefs): /home/stan/gdb/src/gdb/std-regs.c File Reference
/home/stan/gdb/src/gdb/std-regs.c File Reference
#include "defs.h"
#include "user-regs.h"
#include "frame.h"
#include "gdbtypes.h"
#include "value.h"
#include "gdb_string.h"
Functions
static struct value * value_of_builtin_frame_fp_reg (struct frame_info *frame, const void *baton)
static struct value * value_of_builtin_frame_pc_reg (struct frame_info *frame, const void *baton)
static struct value * value_of_builtin_frame_sp_reg (struct frame_info *frame, const void *baton)
static struct value * value_of_builtin_frame_ps_reg (struct frame_info *frame, const void *baton)
void _initialize_frame_reg (void)
Variables
initialize_file_ftype _initialize_frame_reg
Function Documentation
void _initialize_frame_reg (void)
Definition at line 98 of file std-regs.c.
References _initialize_frame_reg, user_reg_add_builtin(), value_of_builtin_frame_fp_reg(), value_of_builtin_frame_pc_reg(), value_of_builtin_frame_ps_reg(), and value_of_builtin_frame_sp_reg().
static struct value* value_of_builtin_frame_fp_reg (struct frame_info * frame, const void * baton) [static, read]
Definition at line 31 of file std-regs.c.
References allocate_value(), builtin_type::builtin_data_ptr, builtin_type(), gdbarch_address_to_pointer(), gdbarch_deprecated_fp_regnum(), get_frame_arch(), get_frame_base_address(), value_contents_raw(), and value_of_register().
Referenced by _initialize_frame_reg().
static struct value* value_of_builtin_frame_pc_reg (struct frame_info * frame, const void * baton) [static, read]
Definition at line 57 of file std-regs.c.
References allocate_value(), builtin_type::builtin_func_ptr, builtin_type(), gdbarch_address_to_pointer(), gdbarch_pc_regnum(), get_frame_arch(), get_frame_pc(), value_contents_raw(), and value_of_register().
Referenced by _initialize_frame_reg().
static struct value* value_of_builtin_frame_ps_reg (struct frame_info * frame, const void * baton) [static, read]
Definition at line 86 of file std-regs.c.
References _, error(), gdbarch_ps_regnum(), get_frame_arch(), and value_of_register().
Referenced by _initialize_frame_reg().
static struct value* value_of_builtin_frame_sp_reg (struct frame_info * frame, const void * baton) [static, read]
Definition at line 76 of file std-regs.c.
References _, error(), gdbarch_sp_regnum(), get_frame_arch(), and value_of_register().
Referenced by _initialize_frame_reg().
Variable Documentation
initialize_file_ftype _initialize_frame_reg
Referenced by _initialize_frame_reg(), and initialize_all_files().