GDB (xrefs): target_so_ops Struct Reference
target_so_ops Struct Reference
#include "solist.h"
Public Attributes
void(* relocate_section_addresses)(struct so_list *so, struct target_section *)
void(* free_so)(struct so_list *so)
void(* clear_so)(struct so_list *so)
void(* clear_solib)(void)
void(* solib_create_inferior_hook)(int from_tty)
void(* special_symbol_handling)(void)
struct so_list *(* current_sos)(void)
int(* open_symbol_file_object)(void *from_ttyp)
int(* in_dynsym_resolve_code)(CORE_ADDR pc)
bfd *(* bfd_open)(char *pathname)
int(* find_and_open_solib)(char *soname, unsigned o_flags, char **temp_pathname)
struct symbol *(* lookup_lib_global_symbol)(const struct objfile *objfile, const char *name, const domain_enum domain)
int(* same)(struct so_list *gdb, struct so_list *inferior)
int(* keep_data_in_core)(CORE_ADDR vaddr, unsigned long size)
void(* update_breakpoints)(void)
void(* handle_event)(void)
Detailed Description
Definition at line 80 of file solist.h.
Member Data Documentation
bfd*(* target_so_ops::bfd_open)(char *pathname)
Definition at line 130 of file solist.h.
Referenced by _initialize_darwin_solib(), _initialize_dsbt_solib(), _initialize_frv_solib(), _initialize_irix_solib(), _initialize_osf_solib(), _initialize_solib_aix(), _initialize_solib_target(), _initialize_som_solib(), _initialize_svr4_solib(), ia64_hpux_target_so_ops(), set_spu_solib_ops(), solib_map_sections(), and spu_bfd_open().
void(* target_so_ops::clear_so)(struct so_list *so)
Definition at line 94 of file solist.h.
Referenced by _initialize_svr4_solib(), and clear_so().
void(* target_so_ops::clear_solib)(void)
Definition at line 98 of file solist.h.
Referenced by _initialize_darwin_solib(), _initialize_dsbt_solib(), _initialize_frv_solib(), _initialize_irix_solib(), _initialize_osf_solib(), _initialize_solib_aix(), _initialize_solib_target(), _initialize_som_solib(), _initialize_svr4_solib(), clear_solib(), ia64_hpux_target_so_ops(), and reload_shared_libraries().
struct so_list*(* target_so_ops::current_sos)(void) [read]
Definition at line 116 of file solist.h.
Referenced by _initialize_darwin_solib(), _initialize_dsbt_solib(), _initialize_frv_solib(), _initialize_irix_solib(), _initialize_osf_solib(), _initialize_solib_aix(), _initialize_solib_target(), _initialize_som_solib(), _initialize_svr4_solib(), ia64_hpux_target_so_ops(), set_spu_solib_ops(), spu_current_sos(), and update_solib_list().
int(* target_so_ops::find_and_open_solib)(char *soname, unsigned o_flags, char **temp_pathname)
Definition at line 136 of file solist.h.
Referenced by i386nto_init_abi(), and solib_find().
void(* target_so_ops::free_so)(struct so_list *so)
Definition at line 89 of file solist.h.
Referenced by _initialize_darwin_solib(), _initialize_dsbt_solib(), _initialize_frv_solib(), _initialize_irix_solib(), _initialize_osf_solib(), _initialize_solib_aix(), _initialize_solib_target(), _initialize_som_solib(), _initialize_svr4_solib(), free_so(), ia64_hpux_target_so_ops(), set_spu_solib_ops(), and spu_free_so().
void(* target_so_ops::handle_event)(void)
Definition at line 170 of file solist.h.
Referenced by _initialize_svr4_solib(), and handle_solib_event().
int(* target_so_ops::in_dynsym_resolve_code)(CORE_ADDR pc)
Definition at line 127 of file solist.h.
Referenced by _initialize_darwin_solib(), _initialize_dsbt_solib(), _initialize_frv_solib(), _initialize_irix_solib(), _initialize_osf_solib(), _initialize_solib_aix(), _initialize_solib_target(), _initialize_som_solib(), _initialize_svr4_solib(), i386nto_init_abi(), ia64_hpux_target_so_ops(), in_solib_dynsym_resolve_code(), mips_linux_init_abi(), and ppc_linux_init_abi().
int(* target_so_ops::keep_data_in_core)(CORE_ADDR vaddr, unsigned long size)
Definition at line 156 of file solist.h.
Referenced by _initialize_svr4_solib(), and solib_keep_data_in_core().
struct symbol*(* target_so_ops::lookup_lib_global_symbol)(const struct objfile *objfile, const char *name, const domain_enum domain) [read]
Definition at line 140 of file solist.h.
Referenced by _initialize_darwin_solib(), _initialize_svr4_solib(), set_spu_solib_ops(), solib_global_lookup(), and spu_lookup_lib_symbol().
int(* target_so_ops::open_symbol_file_object)(void *from_ttyp)
Definition at line 123 of file solist.h.
Referenced by _initialize_darwin_solib(), _initialize_dsbt_solib(), _initialize_frv_solib(), _initialize_irix_solib(), _initialize_osf_solib(), _initialize_solib_aix(), _initialize_solib_target(), _initialize_som_solib(), _initialize_svr4_solib(), ia64_hpux_target_so_ops(), and update_solib_list().
void(* target_so_ops::relocate_section_addresses)(struct so_list *so, struct target_section *)
Definition at line 84 of file solist.h.
Referenced by _initialize_darwin_solib(), _initialize_dsbt_solib(), _initialize_frv_solib(), _initialize_irix_solib(), _initialize_osf_solib(), _initialize_solib_aix(), _initialize_solib_target(), _initialize_som_solib(), _initialize_svr4_solib(), i386nto_init_abi(), ia64_hpux_target_so_ops(), set_spu_solib_ops(), solib_map_sections(), and spu_relocate_section_addresses().
int(* target_so_ops::same)(struct so_list *gdb, struct so_list *inferior)
Definition at line 149 of file solist.h.
Referenced by _initialize_svr4_solib(), and update_solib_list().
void(* target_so_ops::solib_create_inferior_hook)(int from_tty)
Definition at line 101 of file solist.h.
Referenced by _initialize_darwin_solib(), _initialize_dsbt_solib(), _initialize_frv_solib(), _initialize_irix_solib(), _initialize_osf_solib(), _initialize_solib_aix(), _initialize_solib_target(), _initialize_som_solib(), _initialize_svr4_solib(), ia64_hpux_target_so_ops(), set_spu_solib_ops(), solib_create_inferior_hook(), and spu_solib_create_inferior_hook().
void(* target_so_ops::special_symbol_handling)(void)
Definition at line 107 of file solist.h.
Referenced by _initialize_darwin_solib(), _initialize_dsbt_solib(), _initialize_frv_solib(), _initialize_irix_solib(), _initialize_osf_solib(), _initialize_solib_aix(), _initialize_solib_target(), _initialize_som_solib(), _initialize_svr4_solib(), ia64_hpux_target_so_ops(), reload_shared_libraries(), and solib_add().
void(* target_so_ops::update_breakpoints)(void)
Definition at line 164 of file solist.h.
Referenced by _initialize_svr4_solib(), and update_solib_breakpoints().
The documentation for this struct was generated from the following file:
/home/stan/gdb/src/gdb/solist.h