GDB (xrefs): quick_symbol_functions Struct Reference
quick_symbol_functions Struct Reference
#include "symfile.h"
Public Attributes
int(* has_symbols)(struct objfile *objfile)
struct symtab *(* find_last_source_symtab)(struct objfile *objfile)
void(* forget_cached_source_info)(struct objfile *objfile)
int(* map_symtabs_matching_filename)(struct objfile *objfile, const char *name, const char *real_path, int(*callback)(struct symtab *, void *), void *data)
struct symtab *(* lookup_symbol)(struct objfile *objfile, int kind, const char *name, domain_enum domain)
void(* print_stats)(struct objfile *objfile)
void(* dump)(struct objfile *objfile)
void(* relocate)(struct objfile *objfile, const struct section_offsets *new_offsets, const struct section_offsets *delta)
void(* expand_symtabs_for_function)(struct objfile *objfile, const char *func_name)
void(* expand_all_symtabs)(struct objfile *objfile)
void(* expand_symtabs_with_fullname)(struct objfile *objfile, const char *fullname)
void(* map_matching_symbols)(struct objfile *, const char *name, domain_enum namespace, int global, int(*callback)(struct block *, struct symbol *, void *), void *data, symbol_compare_ftype *match, symbol_compare_ftype *ordered_compare)
void(* expand_symtabs_matching)(struct objfile *objfile, int(*file_matcher)(const char *, void *, int basenames), int(*name_matcher)(const char *, void *), enum search_domain kind, void *data)
struct symtab *(* find_pc_sect_symtab)(struct objfile *objfile, struct minimal_symbol *msymbol, CORE_ADDR pc, struct obj_section *section, int warn_if_readin)
void(* map_symbol_filenames)(struct objfile *objfile, symbol_filename_ftype *fun, void *data, int need_fullname)
Detailed Description
Definition at line 146 of file symfile.h.
Member Data Documentation
void(* quick_symbol_functions::dump)(struct objfile *objfile)
Definition at line 199 of file symfile.h.
Referenced by debug_qf_dump(), and dump_objfile().
void(* quick_symbol_functions::expand_all_symtabs)(struct objfile *objfile)
Definition at line 213 of file symfile.h.
Referenced by debug_qf_expand_all_symtabs(), and symbol_file_add_with_addrs().
void(* quick_symbol_functions::expand_symtabs_for_function)(struct objfile *objfile, const char *func_name)
Definition at line 209 of file symfile.h.
Referenced by debug_qf_expand_symtabs_for_function(), and make_symbol_overload_list_qualified().
void(* quick_symbol_functions::expand_symtabs_matching)(struct objfile *objfile, int(*file_matcher)(const char *, void *, int basenames), int(*name_matcher)(const char *, void *), enum search_domain kind, void *data)
Definition at line 270 of file symfile.h.
Referenced by debug_qf_expand_symtabs_matching(), expand_partial_symbol_names(), iterate_over_all_matching_symtabs(), maintenance_expand_symtabs(), and search_symbols().
void(* quick_symbol_functions::expand_symtabs_with_fullname)(struct objfile *objfile, const char *fullname)
Definition at line 220 of file symfile.h.
Referenced by debug_qf_expand_symtabs_with_fullname(), and find_line_symtab().
struct symtab*(* quick_symbol_functions::find_last_source_symtab)(struct objfile *objfile) [read]
Definition at line 154 of file symfile.h.
Referenced by debug_qf_find_last_source_symtab(), and select_source_symtab().
struct symtab*(* quick_symbol_functions::find_pc_sect_symtab)(struct objfile *objfile, struct minimal_symbol *msymbol, CORE_ADDR pc, struct obj_section *section, int warn_if_readin) [read]
Definition at line 282 of file symfile.h.
Referenced by debug_qf_find_pc_sect_symtab(), find_pc_partial_function_gnu_ifunc(), find_pc_sect_symtab(), and find_pc_sect_symtab_via_partial().
void(* quick_symbol_functions::forget_cached_source_info)(struct objfile *objfile)
Definition at line 157 of file symfile.h.
Referenced by debug_qf_forget_cached_source_info(), and forget_cached_source_info_for_objfile().
int(* quick_symbol_functions::has_symbols)(struct objfile *objfile)
Definition at line 150 of file symfile.h.
Referenced by debug_qf_has_symbols(), and objfile_has_partial_symbols().
struct symtab*(* quick_symbol_functions::lookup_symbol)(struct objfile *objfile, int kind, const char *name, domain_enum domain) [read]
Definition at line 188 of file symfile.h.
Referenced by basic_lookup_transparent_type_quick(), debug_qf_lookup_symbol(), and lookup_symbol_aux_quick().
void(* quick_symbol_functions::map_matching_symbols)(struct objfile *, const char *name, domain_enum namespace, int global, int(*callback)(struct block *,struct symbol *, void *), void *data, symbol_compare_ftype *match, symbol_compare_ftype *ordered_compare)
Definition at line 240 of file symfile.h.
Referenced by add_nonlocal_symbols(), and debug_qf_map_matching_symbols().
void(* quick_symbol_functions::map_symbol_filenames)(struct objfile *objfile, symbol_filename_ftype *fun, void *data, int need_fullname)
Definition at line 292 of file symfile.h.
Referenced by debug_qf_map_symbol_filenames(), and map_partial_symbol_filenames().
int(* quick_symbol_functions::map_symtabs_matching_filename)(struct objfile *objfile, const char *name, const char *real_path, int(*callback)(struct symtab *,void *), void *data)
Definition at line 171 of file symfile.h.
Referenced by debug_qf_map_symtabs_matching_filename(), and iterate_over_symtabs().
void(* quick_symbol_functions::print_stats)(struct objfile *objfile)
Definition at line 195 of file symfile.h.
Referenced by debug_qf_print_stats(), and print_objfile_statistics().
void(* quick_symbol_functions::relocate)(struct objfile *objfile, const struct section_offsets *new_offsets, const struct section_offsets *delta)
Definition at line 203 of file symfile.h.
Referenced by debug_qf_relocate(), and objfile_relocate1().
The documentation for this struct was generated from the following file:
/home/stan/gdb/src/gdb/symfile.h