GDB (xrefs): sym_probe_fns Struct Reference
sym_probe_fns Struct Reference
#include "symfile.h"
Public Member Functions
VEC (probe_p)*(*sym_get_probes)(struct objfile *)
Public Attributes
unsigned(* sym_get_probe_argument_count)(struct probe *probe)
int(* can_evaluate_probe_arguments)(struct probe *probe)
struct value *(* sym_evaluate_probe_argument)(struct probe *probe, unsigned n)
void(* sym_compile_to_ax)(struct probe *probe, struct agent_expr *expr, struct axs_value *value, unsigned n)
void(* sym_relocate_probe)(struct objfile *objfile, const struct section_offsets *new_offsets, const struct section_offsets *delta)
Detailed Description
Definition at line 300 of file symfile.h.
Member Function Documentation
sym_probe_fns::VEC (probe_p)
Member Data Documentation
int(* sym_probe_fns::can_evaluate_probe_arguments)(struct probe *probe)
Definition at line 320 of file symfile.h.
Referenced by can_evaluate_probe_arguments(), and debug_can_evaluate_probe_arguments().
void(* sym_probe_fns::sym_compile_to_ax)(struct probe *probe, struct agent_expr *expr, struct axs_value *value, unsigned n)
Definition at line 337 of file symfile.h.
Referenced by compile_probe_arg(), and debug_sym_compile_to_ax().
struct value*(* sym_probe_fns::sym_evaluate_probe_argument)(struct probe *probe, unsigned n) [read]
Definition at line 329 of file symfile.h.
Referenced by compute_probe_arg(), debug_sym_evaluate_probe_argument(), evaluate_probe_argument(), and fetch_probe_arguments().
unsigned(* sym_probe_fns::sym_get_probe_argument_count)(struct probe *probe)
Definition at line 312 of file symfile.h.
Referenced by compile_probe_arg(), compute_probe_arg(), debug_sym_get_probe_argument_count(), fetch_probe_arguments(), and get_probe_argument_count().
void(* sym_probe_fns::sym_relocate_probe)(struct objfile *objfile, const struct section_offsets *new_offsets, const struct section_offsets *delta)
Definition at line 343 of file symfile.h.
Referenced by debug_sym_relocate_probe(), and objfile_relocate1().
The documentation for this struct was generated from the following file:
/home/stan/gdb/src/gdb/symfile.h