GDB (xrefs): dwarf_expr_context_funcs Struct Reference
dwarf_expr_context_funcs Struct Reference
#include "dwarf2expr.h"
Public Attributes
CORE_ADDR(* read_reg)(void *baton, int regnum)
void(* read_mem)(void *baton, gdb_byte *buf, CORE_ADDR addr, size_t length)
void(* get_frame_base)(void *baton, const gdb_byte **start, size_t *length)
CORE_ADDR(* get_frame_cfa)(void *baton)
CORE_ADDR(* get_frame_pc)(void *baton)
CORE_ADDR(* get_tls_address)(void *baton, CORE_ADDR offset)
void(* dwarf_call)(struct dwarf_expr_context *ctx, cu_offset die_offset)
struct type *(* get_base_type)(struct dwarf_expr_context *ctx, cu_offset die)
void(* push_dwarf_reg_entry_value)(struct dwarf_expr_context *ctx, enum call_site_parameter_kind kind, union call_site_parameter_u kind_u, int deref_size)
CORE_ADDR(* get_addr_index)(void *baton, unsigned int index)
Detailed Description
Definition at line 32 of file dwarf2expr.h.
Member Data Documentation
void(* dwarf_expr_context_funcs::dwarf_call)(struct dwarf_expr_context *ctx, cu_offset die_offset)
Definition at line 58 of file dwarf2expr.h.
Referenced by execute_stack_op().
CORE_ADDR(* dwarf_expr_context_funcs::get_addr_index)(void *baton, unsigned int index)
Definition at line 78 of file dwarf2expr.h.
Referenced by execute_stack_op().
struct type*(* dwarf_expr_context_funcs::get_base_type)(struct dwarf_expr_context *ctx, cu_offset die) [read]
Definition at line 65 of file dwarf2expr.h.
Referenced by dwarf_get_base_type().
void(* dwarf_expr_context_funcs::get_frame_base)(void *baton, const gdb_byte **start, size_t *length)
Definition at line 43 of file dwarf2expr.h.
Referenced by execute_stack_op().
CORE_ADDR(* dwarf_expr_context_funcs::get_frame_cfa)(void *baton)
Definition at line 46 of file dwarf2expr.h.
Referenced by execute_stack_op().
CORE_ADDR(* dwarf_expr_context_funcs::get_frame_pc)(void *baton)
Definition at line 49 of file dwarf2expr.h.
Referenced by dwarf_expr_dwarf_call(), and needs_frame_dwarf_call().
CORE_ADDR(* dwarf_expr_context_funcs::get_tls_address)(void *baton, CORE_ADDR offset)
Definition at line 53 of file dwarf2expr.h.
Referenced by execute_stack_op().
void(* dwarf_expr_context_funcs::push_dwarf_reg_entry_value)(struct dwarf_expr_context *ctx, enum call_site_parameter_kind kind, union call_site_parameter_u kind_u, int deref_size)
Definition at line 71 of file dwarf2expr.h.
Referenced by execute_stack_op().
void(* dwarf_expr_context_funcs::read_mem)(void *baton, gdb_byte *buf, CORE_ADDR addr, size_t length)
Definition at line 38 of file dwarf2expr.h.
Referenced by execute_stack_op().
CORE_ADDR(* dwarf_expr_context_funcs::read_reg)(void *baton, int regnum)
Definition at line 35 of file dwarf2expr.h.
Referenced by execute_stack_op().
The documentation for this struct was generated from the following file:
/home/stan/gdb/src/gdb/dwarf2expr.h