GDB (xrefs): cp_abi_ops Struct Reference
cp_abi_ops Struct Reference
#include "cp-abi.h"
Public Attributes
const char * shortname
const char * longname
const char * doc
enum ctor_kinds(* is_constructor_name)(const char *name)
enum dtor_kinds(* is_destructor_name)(const char *name)
int(* is_vtable_name)(const char *name)
int(* is_operator_name)(const char *name)
struct value *(* virtual_fn_field)(struct value **arg1p, struct fn_field *f, int j, struct type *type, int offset)
struct type *(* rtti_type)(struct value *v, int *full, int *top, int *using_enc)
int(* baseclass_offset)(struct type *type, int index, const bfd_byte *valaddr, int embedded_offset, CORE_ADDR address, const struct value *val)
void(* print_method_ptr)(const gdb_byte *contents, struct type *type, struct ui_file *stream)
int(* method_ptr_size)(struct type *)
void(* make_method_ptr)(struct type *, gdb_byte *, CORE_ADDR, int)
struct value *(* method_ptr_to_value)(struct value **, struct value *)
void(* print_vtable)(struct value *)
struct value *(* get_typeid)(struct value *value)
struct type *(* get_typeid_type)(struct gdbarch *gdbarch)
struct type *(* get_type_from_type_info)(struct value *value)
char *(* get_typename_from_type_info)(struct value *value)
CORE_ADDR(* skip_trampoline)(struct frame_info *, CORE_ADDR)
int(* pass_by_reference)(struct type *type)
Detailed Description
Definition at line 215 of file cp-abi.h.
Member Data Documentation
int(* cp_abi_ops::baseclass_offset)(struct type *type, int index, const bfd_byte *valaddr, int embedded_offset, CORE_ADDR address, const struct value *val)
Definition at line 233 of file cp-abi.h.
Referenced by baseclass_offset(), init_gnuv2_ops(), and init_gnuv3_ops().
const char* cp_abi_ops::doc
Definition at line 219 of file cp-abi.h.
Referenced by init_gnuv2_ops(), init_gnuv3_ops(), and set_cp_abi_as_auto_default().
struct type*(* cp_abi_ops::get_type_from_type_info)(struct value *value) [read]
Definition at line 247 of file cp-abi.h.
Referenced by cplus_type_from_type_info(), and init_gnuv3_ops().
struct value*(* cp_abi_ops::get_typeid)(struct value *value) [read]
Definition at line 245 of file cp-abi.h.
Referenced by cplus_typeid(), and init_gnuv3_ops().
struct type*(* cp_abi_ops::get_typeid_type)(struct gdbarch *gdbarch) [read]
Definition at line 246 of file cp-abi.h.
Referenced by cplus_typeid_type(), and init_gnuv3_ops().
char*(* cp_abi_ops::get_typename_from_type_info)(struct value *value)
Definition at line 248 of file cp-abi.h.
Referenced by cplus_typename_from_type_info(), and init_gnuv3_ops().
enum ctor_kinds(* cp_abi_ops::is_constructor_name)(const char *name)
Definition at line 223 of file cp-abi.h.
Referenced by init_gnuv2_ops(), init_gnuv3_ops(), and is_constructor_name().
enum dtor_kinds(* cp_abi_ops::is_destructor_name)(const char *name)
Definition at line 224 of file cp-abi.h.
Referenced by init_gnuv2_ops(), init_gnuv3_ops(), and is_destructor_name().
int(* cp_abi_ops::is_operator_name)(const char *name)
Definition at line 226 of file cp-abi.h.
Referenced by init_gnuv2_ops(), init_gnuv3_ops(), and is_operator_name().
int(* cp_abi_ops::is_vtable_name)(const char *name)
Definition at line 225 of file cp-abi.h.
Referenced by init_gnuv2_ops(), init_gnuv3_ops(), and is_vtable_name().
const char* cp_abi_ops::longname
Definition at line 218 of file cp-abi.h.
Referenced by init_gnuv2_ops(), init_gnuv3_ops(), set_cp_abi_as_auto_default(), and show_cp_abi_cmd().
void(* cp_abi_ops::make_method_ptr)(struct type *, gdb_byte *, CORE_ADDR, int)
Definition at line 240 of file cp-abi.h.
Referenced by cplus_make_method_ptr(), and init_gnuv3_ops().
int(* cp_abi_ops::method_ptr_size)(struct type *)
Definition at line 239 of file cp-abi.h.
Referenced by cplus_method_ptr_size(), and init_gnuv3_ops().
struct value*(* cp_abi_ops::method_ptr_to_value)(struct value **, struct value *) [read]
Definition at line 242 of file cp-abi.h.
Referenced by cplus_method_ptr_to_value(), and init_gnuv3_ops().
int(* cp_abi_ops::pass_by_reference)(struct type *type)
Definition at line 250 of file cp-abi.h.
Referenced by cp_pass_by_reference(), and init_gnuv3_ops().
void(* cp_abi_ops::print_method_ptr)(const gdb_byte *contents, struct type *type, struct ui_file *stream)
Definition at line 236 of file cp-abi.h.
Referenced by cplus_print_method_ptr(), and init_gnuv3_ops().
void(* cp_abi_ops::print_vtable)(struct value *)
Definition at line 244 of file cp-abi.h.
Referenced by cplus_print_vtable(), and init_gnuv3_ops().
struct type*(* cp_abi_ops::rtti_type)(struct value *v, int *full, int *top, int *using_enc) [read]
Definition at line 231 of file cp-abi.h.
Referenced by init_gnuv2_ops(), init_gnuv3_ops(), and value_rtti_type().
const char* cp_abi_ops::shortname
Definition at line 217 of file cp-abi.h.
Referenced by _initialize_gnu_v3_abi(), find_cp_abi(), init_gnuv2_ops(), init_gnuv3_ops(), set_cp_abi_as_auto_default(), and show_cp_abi_cmd().
CORE_ADDR(* cp_abi_ops::skip_trampoline)(struct frame_info *, CORE_ADDR)
Definition at line 249 of file cp-abi.h.
Referenced by cplus_skip_trampoline(), and init_gnuv3_ops().
struct value*(* cp_abi_ops::virtual_fn_field)(struct value **arg1p, struct fn_field *f, int j, struct type *type, int offset) [read]
Definition at line 227 of file cp-abi.h.
Referenced by init_gnuv2_ops(), init_gnuv3_ops(), and value_virtual_fn_field().
The documentation for this struct was generated from the following file:
/home/stan/gdb/src/gdb/cp-abi.h