GDB (xrefs): thread_db_info Struct Reference
thread_db_info Struct Reference
Public Attributes
struct thread_db_info * next
int pid
void * handle
char * filename
struct ps_prochandle proc_handle
td_thragent_t * thread_agent
int need_stale_parent_threads_check
CORE_ADDR td_create_bp_addr
CORE_ADDR td_death_bp_addr
td_err_e(* td_init_p)(void)
td_err_e(* td_ta_new_p)(struct ps_prochandle *ps, td_thragent_t **ta)
td_err_e(* td_ta_map_id2thr_p)(const td_thragent_t *ta, thread_t pt, td_thrhandle_t *__th)
td_err_e(* td_ta_map_lwp2thr_p)(const td_thragent_t *ta, lwpid_t lwpid, td_thrhandle_t *th)
td_err_e(* td_ta_thr_iter_p)(const td_thragent_t *ta, td_thr_iter_f *callback, void *cbdata_p, td_thr_state_e state, int ti_pri, sigset_t *ti_sigmask_p, unsigned int ti_user_flags)
td_err_e(* td_ta_event_addr_p)(const td_thragent_t *ta, td_event_e event, td_notify_t *ptr)
td_err_e(* td_ta_set_event_p)(const td_thragent_t *ta, td_thr_events_t *event)
td_err_e(* td_ta_clear_event_p)(const td_thragent_t *ta, td_thr_events_t *event)
td_err_e(* td_ta_event_getmsg_p)(const td_thragent_t *ta, td_event_msg_t *msg)
td_err_e(* td_thr_validate_p)(const td_thrhandle_t *th)
td_err_e(* td_thr_get_info_p)(const td_thrhandle_t *th, td_thrinfo_t *infop)
td_err_e(* td_thr_event_enable_p)(const td_thrhandle_t *th, int event)
td_err_e(* td_thr_tls_get_addr_p)(const td_thrhandle_t *th, psaddr_t map_address, size_t offset, psaddr_t *address)
Detailed Description
Definition at line 127 of file linux-thread-db.c.
Member Data Documentation
char* thread_db_info::filename
Definition at line 139 of file linux-thread-db.c.
Referenced by info_auto_load_libthread_db(), info_auto_load_libthread_db_compare(), and try_thread_db_load().
void* thread_db_info::handle
Definition at line 135 of file linux-thread-db.c.
Referenced by add_thread_db_info(), and try_thread_db_load_1().
int thread_db_info::need_stale_parent_threads_check
Definition at line 153 of file linux-thread-db.c.
Referenced by add_thread_db_info(), find_new_threads_callback(), and thread_db_resume().
struct thread_db_info* thread_db_info::next
Definition at line 129 of file linux-thread-db.c.
Referenced by gdb.FrameIterator.FrameIterator::__next__(), add_thread_db_info(), delete_thread_db_info(), get_thread_db_info(), info_auto_load_libthread_db(), and try_thread_db_load_1().
int thread_db_info::pid
Definition at line 132 of file linux-thread-db.c.
Referenced by add_thread_db_info(), find_new_threads_callback(), get_thread_db_info(), info_auto_load_libthread_db(), info_auto_load_libthread_db_compare(), and thread_get_info_callback().
struct ps_prochandle thread_db_info::proc_handle
Definition at line 143 of file linux-thread-db.c.
Referenced by check_event(), enable_thread_event(), thread_db_attach_lwp(), thread_db_find_new_threads_2(), thread_from_lwp(), and try_thread_db_load_1().
CORE_ADDR thread_db_info::td_create_bp_addr
Definition at line 161 of file linux-thread-db.c.
Referenced by check_event(), disable_thread_event_reporting(), and enable_thread_event_reporting().
CORE_ADDR thread_db_info::td_death_bp_addr
Definition at line 164 of file linux-thread-db.c.
Referenced by check_event(), disable_thread_event_reporting(), and enable_thread_event_reporting().
td_err_e(* thread_db_info::td_init_p)(void)
Definition at line 168 of file linux-thread-db.c.
Referenced by try_thread_db_load_1().
td_err_e(* thread_db_info::td_ta_clear_event_p)(const td_thragent_t *ta, td_thr_events_t *event)
Definition at line 185 of file linux-thread-db.c.
Referenced by disable_thread_event_reporting(), and try_thread_db_load_1().
td_err_e(* thread_db_info::td_ta_event_addr_p)(const td_thragent_t *ta, td_event_e event, td_notify_t *ptr)
Definition at line 181 of file linux-thread-db.c.
Referenced by enable_thread_event(), enable_thread_event_reporting(), and try_thread_db_load_1().
td_err_e(* thread_db_info::td_ta_event_getmsg_p)(const td_thragent_t *ta, td_event_msg_t *msg)
Definition at line 187 of file linux-thread-db.c.
Referenced by check_event(), enable_thread_event_reporting(), and try_thread_db_load_1().
td_err_e(* thread_db_info::td_ta_map_id2thr_p)(const td_thragent_t *ta, thread_t pt, td_thrhandle_t *__th)
Definition at line 172 of file linux-thread-db.c.
Referenced by try_thread_db_load_1().
td_err_e(* thread_db_info::td_ta_map_lwp2thr_p)(const td_thragent_t *ta, lwpid_t lwpid, td_thrhandle_t *th)
Definition at line 174 of file linux-thread-db.c.
Referenced by thread_db_attach_lwp(), thread_from_lwp(), and try_thread_db_load_1().
td_err_e(* thread_db_info::td_ta_new_p)(struct ps_prochandle *ps, td_thragent_t **ta)
Definition at line 170 of file linux-thread-db.c.
Referenced by try_thread_db_load_1().
td_err_e(* thread_db_info::td_ta_set_event_p)(const td_thragent_t *ta, td_thr_events_t *event)
Definition at line 183 of file linux-thread-db.c.
Referenced by enable_thread_event_reporting(), and try_thread_db_load_1().
td_err_e(* thread_db_info::td_ta_thr_iter_p)(const td_thragent_t *ta, td_thr_iter_f *callback, void *cbdata_p, td_thr_state_e state, int ti_pri, sigset_t *ti_sigmask_p, unsigned int ti_user_flags)
Definition at line 176 of file linux-thread-db.c.
Referenced by find_new_threads_once(), and try_thread_db_load_1().
td_err_e(* thread_db_info::td_thr_event_enable_p)(const td_thrhandle_t *th, int event)
Definition at line 193 of file linux-thread-db.c.
Referenced by attach_thread(), enable_thread_event_reporting(), find_new_threads_callback(), and try_thread_db_load_1().
td_err_e(* thread_db_info::td_thr_get_info_p)(const td_thrhandle_t *th, td_thrinfo_t *infop)
Definition at line 191 of file linux-thread-db.c.
Referenced by check_event(), find_new_threads_callback(), thread_db_attach_lwp(), thread_get_info_callback(), and try_thread_db_load_1().
td_err_e(* thread_db_info::td_thr_tls_get_addr_p)(const td_thrhandle_t *th, psaddr_t map_address, size_t offset, psaddr_t *address)
Definition at line 196 of file linux-thread-db.c.
Referenced by thread_db_get_thread_local_address(), and try_thread_db_load_1().
td_err_e(* thread_db_info::td_thr_validate_p)(const td_thrhandle_t *th)
Definition at line 190 of file linux-thread-db.c.
Referenced by try_thread_db_load_1().
td_thragent_t* thread_db_info::thread_agent
Definition at line 146 of file linux-thread-db.c.
Referenced by check_event(), disable_thread_event_reporting(), enable_thread_event(), enable_thread_event_reporting(), find_new_threads_once(), thread_db_attach_lwp(), thread_from_lwp(), and try_thread_db_load_1().
The documentation for this struct was generated from the following file:
/home/stan/gdb/src/gdb/linux-thread-db.c