GDB (xrefs): probe_ops Struct Reference
probe_ops Struct Reference
#include "probe.h"
Public Attributes
int(* is_linespec)(const char **linespecp)
void(* get_probes)(VEC(probe_p)**probes, struct objfile *objfile)
void(* relocate)(struct probe *probe, CORE_ADDR delta)
unsigned(* get_probe_argument_count)(struct probe *probe)
int(* can_evaluate_probe_arguments)(struct probe *probe)
struct value *(* evaluate_probe_argument)(struct probe *probe, unsigned n)
void(* compile_to_ax)(struct probe *probe, struct agent_expr *aexpr, struct axs_value *axs_value, unsigned n)
void(* set_semaphore)(struct probe *probe, struct gdbarch *gdbarch)
void(* clear_semaphore)(struct probe *probe, struct gdbarch *gdbarch)
void(* destroy)(struct probe *probe)
void(* gen_info_probes_table_header)(VEC(info_probe_column_s)**heads)
void(* gen_info_probes_table_values)(struct probe *probe, VEC(const_char_ptr)**values)
Detailed Description
Definition at line 52 of file probe.h.
Member Data Documentation
int(* probe_ops::can_evaluate_probe_arguments)(struct probe *probe)
Definition at line 80 of file probe.h.
Referenced by elf_can_evaluate_probe_arguments(), and stap_get_probe_argument_count().
void(* probe_ops::clear_semaphore)(struct probe *probe, struct gdbarch *gdbarch)
Definition at line 104 of file probe.h.
Referenced by bkpt_probe_remove_location(), and stop_tracing().
void(* probe_ops::compile_to_ax)(struct probe *probe, struct agent_expr *aexpr, struct axs_value *axs_value, unsigned n)
Definition at line 91 of file probe.h.
Referenced by elf_compile_to_ax().
void(* probe_ops::destroy)(struct probe *probe)
Definition at line 109 of file probe.h.
Referenced by probe_key_free().
struct value*(* probe_ops::evaluate_probe_argument)(struct probe *probe, unsigned n) [read]
Definition at line 85 of file probe.h.
Referenced by elf_evaluate_probe_argument().
void(* probe_ops::gen_info_probes_table_header)(VEC(info_probe_column_s)**heads)
Definition at line 116 of file probe.h.
Referenced by gen_ui_out_table_header_info(), get_number_extra_fields(), and print_ui_out_info().
void(* probe_ops::gen_info_probes_table_values)(struct probe *probe, VEC(const_char_ptr)**values)
Definition at line 128 of file probe.h.
Referenced by gen_ui_out_table_header_info(), and print_ui_out_info().
unsigned(* probe_ops::get_probe_argument_count)(struct probe *probe)
Definition at line 74 of file probe.h.
Referenced by elf_get_probe_argument_count().
void(* probe_ops::get_probes)(VEC(probe_p)**probes, struct objfile *objfile)
Definition at line 65 of file probe.h.
Referenced by VEC().
int(* probe_ops::is_linespec)(const char **linespecp)
Definition at line 61 of file probe.h.
Referenced by probe_linespec_to_ops().
void(* probe_ops::relocate)(struct probe *probe, CORE_ADDR delta)
Definition at line 70 of file probe.h.
Referenced by elf_symfile_relocate_probe().
void(* probe_ops::set_semaphore)(struct probe *probe, struct gdbarch *gdbarch)
Definition at line 98 of file probe.h.
Referenced by bkpt_probe_insert_location(), and start_tracing().
The documentation for this struct was generated from the following file:
/home/stan/gdb/src/gdb/probe.h