GDB (xrefs): target_ops Struct Reference
target_ops Struct Reference
#include "target.h"
Public Member Functions
VEC (mem_region_s)*(*to_memory_map)(struct target_ops *)
VEC (static_tracepoint_marker_p)*(*to_static_tracepoint_markers_by_strid)(const char *id)
VEC (btrace_block_s)*(*to_read_btrace)(struct btrace_target_info *
Public Attributes
struct target_ops * beneath
char * to_shortname
char * to_longname
char * to_doc
void * to_data
void(* to_open)(char *, int)
void(* to_xclose)(struct target_ops *targ)
void(* to_close)(void)
void(* to_attach)(struct target_ops *ops, char *, int)
void(* to_post_attach)(int)
void(* to_detach)(struct target_ops *ops, char *, int)
void(* to_disconnect)(struct target_ops *, char *, int)
void(* to_resume)(struct target_ops *, ptid_t, int, enum gdb_signal)
ptid_t(* to_wait)(struct target_ops *, ptid_t, struct target_waitstatus *, int)
void(* to_fetch_registers)(struct target_ops *, struct regcache *, int)
void(* to_store_registers)(struct target_ops *, struct regcache *, int)
void(* to_prepare_to_store)(struct regcache *)
int(* deprecated_xfer_memory)(CORE_ADDR memaddr, gdb_byte *myaddr, int len, int write, struct mem_attrib *attrib, struct target_ops *target)
void(* to_files_info)(struct target_ops *)
int(* to_insert_breakpoint)(struct gdbarch *, struct bp_target_info *)
int(* to_remove_breakpoint)(struct gdbarch *, struct bp_target_info *)
int(* to_can_use_hw_breakpoint)(int, int, int)
int(* to_ranged_break_num_registers)(struct target_ops *)
int(* to_insert_hw_breakpoint)(struct gdbarch *, struct bp_target_info *)
int(* to_remove_hw_breakpoint)(struct gdbarch *, struct bp_target_info *)
int(* to_remove_watchpoint)(CORE_ADDR, int, int, struct expression *)
int(* to_insert_watchpoint)(CORE_ADDR, int, int, struct expression *)
int(* to_insert_mask_watchpoint)(struct target_ops *, CORE_ADDR, CORE_ADDR, int)
int(* to_remove_mask_watchpoint)(struct target_ops *, CORE_ADDR, CORE_ADDR, int)
int(* to_stopped_by_watchpoint)(void)
int to_have_steppable_watchpoint
int to_have_continuable_watchpoint
int(* to_stopped_data_address)(struct target_ops *, CORE_ADDR *)
int(* to_watchpoint_addr_within_range)(struct target_ops *, CORE_ADDR, CORE_ADDR, int)
int(* to_region_ok_for_hw_watchpoint)(CORE_ADDR, int)
int(* to_can_accel_watchpoint_condition)(CORE_ADDR, int, int, struct expression *)
int(* to_masked_watch_num_registers)(struct target_ops *, CORE_ADDR, CORE_ADDR)
void(* to_terminal_init)(void)
void(* to_terminal_inferior)(void)
void(* to_terminal_ours_for_output)(void)
void(* to_terminal_ours)(void)
void(* to_terminal_save_ours)(void)
void(* to_terminal_info)(const char *, int)
void(* to_kill)(struct target_ops *)
void(* to_load)(char *, int)
void(* to_create_inferior)(struct target_ops *, char *, char *, char **, int)
void(* to_post_startup_inferior)(ptid_t)
int(* to_insert_fork_catchpoint)(int)
int(* to_remove_fork_catchpoint)(int)
int(* to_insert_vfork_catchpoint)(int)
int(* to_remove_vfork_catchpoint)(int)
int(* to_follow_fork)(struct target_ops *, int, int)
int(* to_insert_exec_catchpoint)(int)
int(* to_remove_exec_catchpoint)(int)
int(* to_set_syscall_catchpoint)(int, int, int, int, int *)
int(* to_has_exited)(int, int, int *)
void(* to_mourn_inferior)(struct target_ops *)
int(* to_can_run)(void)
void(* to_pass_signals)(int, unsigned char *)
void(* to_program_signals)(int, unsigned char *)
int(* to_thread_alive)(struct target_ops *, ptid_t ptid)
void(* to_find_new_threads)(struct target_ops *)
char *(* to_pid_to_str)(struct target_ops *, ptid_t)
char *(* to_extra_thread_info)(struct thread_info *)
char *(* to_thread_name)(struct thread_info *)
void(* to_stop)(ptid_t)
void(* to_rcmd)(char *command, struct ui_file *output)
char *(* to_pid_to_exec_file)(int pid)
void(* to_log_command)(const char *)
struct target_section_table *(* to_get_section_table)(struct target_ops *)
enum strata to_stratum
int(* to_has_all_memory)(struct target_ops *)
int(* to_has_memory)(struct target_ops *)
int(* to_has_stack)(struct target_ops *)
int(* to_has_registers)(struct target_ops *)
int(* to_has_execution)(struct target_ops *, ptid_t)
int to_has_thread_control
int to_attach_no_wait
int(* to_can_async_p)(void)
int(* to_is_async_p)(void)
void(* to_async)(void(*)(enum inferior_event_type, void *), void *)
int(* to_supports_non_stop)(void)
int(* to_find_memory_regions)(find_memory_region_ftype func, void *data)
char *(* to_make_corefile_notes)(bfd *, int *)
gdb_byte *(* to_get_bookmark)(char *, int)
void(* to_goto_bookmark)(gdb_byte *, int)
CORE_ADDR(* to_get_thread_local_address)(struct target_ops *ops, ptid_t ptid, CORE_ADDR load_module_addr, CORE_ADDR offset)
LONGEST(* to_xfer_partial)(struct target_ops *ops, enum target_object object, const char *annex, gdb_byte *readbuf, const gdb_byte *writebuf, ULONGEST offset, LONGEST len)
void(* to_flash_erase)(struct target_ops *, ULONGEST address, LONGEST length)
void(* to_flash_done)(struct target_ops *)
struct target_desc *(* to_read_description)(struct target_ops *ops)
ptid_t(* to_get_ada_task_ptid)(long lwp, long thread)
int(* to_auxv_parse)(struct target_ops *ops, gdb_byte **readptr, gdb_byte *endptr, CORE_ADDR *typep, CORE_ADDR *valp)
int(* to_search_memory)(struct target_ops *ops, CORE_ADDR start_addr, ULONGEST search_space_len, const gdb_byte *pattern, ULONGEST pattern_len, CORE_ADDR *found_addrp)
int(* to_can_execute_reverse)(void)
enum exec_direction_kind(* to_execution_direction)(void)
int(* to_supports_multi_process)(void)
int(* to_supports_enable_disable_tracepoint)(void)
int(* to_supports_disable_randomization)(void)
int(* to_supports_string_tracing)(void)
int(* to_supports_evaluation_of_breakpoint_conditions)(void)
int(* to_can_run_breakpoint_commands)(void)
struct gdbarch *(* to_thread_architecture)(struct target_ops *, ptid_t)
struct address_space *(* to_thread_address_space)(struct target_ops *, ptid_t)
int(* to_fileio_open)(const char *filename, int flags, int mode, int *target_errno)
int(* to_fileio_pwrite)(int fd, const gdb_byte *write_buf, int len, ULONGEST offset, int *target_errno)
int(* to_fileio_pread)(int fd, gdb_byte *read_buf, int len, ULONGEST offset, int *target_errno)
int(* to_fileio_close)(int fd, int *target_errno)
int(* to_fileio_unlink)(const char *filename, int *target_errno)
char *(* to_fileio_readlink)(const char *filename, int *target_errno)
void(* to_info_proc)(struct target_ops *, char *, enum info_proc_what)
void(* to_trace_init)(void)
void(* to_download_tracepoint)(struct bp_location *location)
int(* to_can_download_tracepoint)(void)
void(* to_download_trace_state_variable)(struct trace_state_variable *tsv)
void(* to_enable_tracepoint)(struct bp_location *location)
void(* to_disable_tracepoint)(struct bp_location *location)
void(* to_trace_set_readonly_regions)(void)
void(* to_trace_start)(void)
int(* to_get_trace_status)(struct trace_status *ts)
void(* to_get_tracepoint_status)(struct breakpoint *tp, struct uploaded_tp *utp)
void(* to_trace_stop)(void)
int(* to_trace_find)(enum trace_find_type type, int num, CORE_ADDR addr1, CORE_ADDR addr2, int *tpp)
int(* to_get_trace_state_variable_value)(int tsv, LONGEST *val)
int(* to_save_trace_data)(const char *filename)
int(* to_upload_tracepoints)(struct uploaded_tp **utpp)
int(* to_upload_trace_state_variables)(struct uploaded_tsv **utsvp)
LONGEST(* to_get_raw_trace_data)(gdb_byte *buf, ULONGEST offset, LONGEST len)
int(* to_get_min_fast_tracepoint_insn_len)(void)
void(* to_set_disconnected_tracing)(int val)
void(* to_set_circular_trace_buffer)(int val)
void(* to_set_trace_buffer_size)(LONGEST val)
int(* to_set_trace_notes)(const char *user, const char *notes, const char *stopnotes)
int(* to_core_of_thread)(struct target_ops *, ptid_t ptid)
int(* to_verify_memory)(struct target_ops *, const gdb_byte *data, CORE_ADDR memaddr, ULONGEST size)
int(* to_get_tib_address)(ptid_t ptid, CORE_ADDR *addr)
void(* to_set_permissions)(void)
int(* to_static_tracepoint_marker_at)(CORE_ADDR, struct static_tracepoint_marker *marker)
struct traceframe_info *(* to_traceframe_info)(void)
int(* to_use_agent)(int use)
int(* to_can_use_agent)(void)
int(* to_supports_btrace)(void)
struct btrace_target_info *(* to_enable_btrace)(ptid_t ptid)
void(* to_disable_btrace)(struct btrace_target_info *tinfo)
void(* to_teardown_btrace)(struct btrace_target_info *tinfo)
enum btrace_read_type void(* to_stop_recording)(void)
void(* to_info_record)(void)
void(* to_save_record)(const char *filename)
void(* to_delete_record)(void)
int(* to_record_is_replaying)(void)
void(* to_goto_record_begin)(void)
void(* to_goto_record_end)(void)
void(* to_goto_record)(ULONGEST insn)
void(* to_insn_history)(int size, int flags)
void(* to_insn_history_from)(ULONGEST from, int size, int flags)
void(* to_insn_history_range)(ULONGEST begin, ULONGEST end, int flags)
void(* to_call_history)(int size, int flags)
void(* to_call_history_from)(ULONGEST begin, int size, int flags)
void(* to_call_history_range)(ULONGEST begin, ULONGEST end, int flags)
int(* to_augmented_libraries_svr4_read)(void)
int to_magic
Detailed Description
Definition at line 340 of file target.h.
Member Function Documentation
target_ops::VEC (mem_region_s)
target_ops::VEC (static_tracepoint_marker_p) const
target_ops::VEC (btrace_block_s)
Member Data Documentation
struct target_ops* target_ops::beneath
Definition at line 342 of file target.h.
Referenced by aix_thread_attach(), aix_thread_detach(), aix_thread_fetch_registers(), aix_thread_mourn_inferior(), aix_thread_pid_to_str(), aix_thread_resume(), aix_thread_store_registers(), aix_thread_thread_alive(), aix_thread_wait(), aix_thread_xfer_partial(), bsd_uthread_fetch_registers(), bsd_uthread_mourn_inferior(), bsd_uthread_resume(), bsd_uthread_store_registers(), bsd_uthread_thread_alive(), bsd_uthread_wait(), bsd_uthread_xfer_partial(), core_xfer_partial(), current_xfer_partial(), dec_thread_detach(), dec_thread_fetch_registers(), dec_thread_mourn_inferior(), dec_thread_pid_to_str(), dec_thread_store_registers(), dec_thread_wait(), default_fileio_target(), default_xfer_partial(), find_record_target(), find_target_beneath(), gdb_update_mem(), maintenance_print_target_stack(), memory_xfer_partial_1(), mi_cmd_data_read_memory(), mi_cmd_data_read_memory_bytes(), procfs_xfer_partial(), push_target(), ravenscar_fetch_registers(), ravenscar_mourn_inferior(), ravenscar_prepare_to_store(), ravenscar_resume(), ravenscar_store_registers(), ravenscar_wait(), read_memory(), record_full_open(), sol_find_new_threads(), sol_thread_alive(), sol_thread_detach(), sol_thread_fetch_registers(), sol_thread_mourn_inferior(), sol_thread_resume(), sol_thread_store_registers(), sol_thread_wait(), sol_thread_xfer_partial(), target_attach(), target_auxv_parse(), target_call_history(), target_call_history_from(), target_call_history_range(), target_core_of_thread(), target_create_inferior(), target_delete_record(), target_detach(), target_disable_btrace(), target_disconnect(), target_enable_btrace(), target_fetch_registers(), target_fileio_close(), target_fileio_open(), target_fileio_pread(), target_fileio_pwrite(), target_fileio_readlink(), target_fileio_unlink(), target_find_new_threads(), target_flash_done(), target_flash_erase(), target_follow_fork(), target_get_osdata(), target_get_section_table(), target_goto_record(), target_goto_record_begin(), target_goto_record_end(), target_has_all_memory_1(), target_has_execution_1(), target_has_memory_1(), target_has_registers_1(), target_has_stack_1(), target_info(), target_info_proc(), target_info_record(), target_insert_mask_watchpoint(), target_insn_history(), target_insn_history_from(), target_insn_history_range(), target_is_pushed(), target_kill(), target_masked_watch_num_registers(), target_mourn_inferior(), target_pass_signals(), target_pid_to_str(), target_program_signals(), target_ranged_break_num_registers(), target_read_description(), target_read_live_memory(), target_read_memory(), target_read_stack(), target_record_is_replaying(), target_remove_mask_watchpoint(), target_require_runnable(), target_resume(), target_save_record(), target_search_memory(), target_stop_recording(), target_store_registers(), target_supports_btrace(), target_supports_delete_record(), target_supports_disable_randomization(), target_supports_non_stop(), target_teardown_btrace(), target_thread_address_space(), target_thread_alive(), target_thread_name(), target_translate_tls_address(), target_verify_memory(), target_wait(), target_write_memory(), target_write_memory_blocks(), target_write_raw_memory(), thread_db_get_thread_local_address(), thread_db_pid_to_str(), thread_db_resume(), thread_db_wait(), unpush_target(), update_current_target(), VEC(), and windows_xfer_partial().
int(* target_ops::deprecated_xfer_memory)(CORE_ADDR memaddr, gdb_byte *myaddr, int len, int write, struct mem_attrib *attrib, struct target_ops *target)
Definition at line 392 of file target.h.
Referenced by _initialize_remote_mips(), default_xfer_partial(), init_go32_ops(), init_m32r_ops(), init_procfs_ops(), procfs_target(), procfs_xfer_partial(), setup_target_debug(), and update_current_target().
void(* target_ops::to_async)(void(*)(enum inferior_event_type, void *), void *)
Definition at line 481 of file target.h.
Referenced by init_record_full_core_ops(), init_record_full_ops(), init_remote_ops(), linux_nat_add_target(), record_full_open(), and update_current_target().
void(* target_ops::to_attach)(struct target_ops *ops, char *, int)
Definition at line 360 of file target.h.
Referenced by _initialize_darwin_inferior(), aix_thread_attach(), find_default_attach(), gnu_target(), inf_ptrace_target(), init_aix_thread_ops(), init_core_ops(), init_exec_ops(), init_extended_remote_ops(), init_go32_ops(), init_procfs_ops(), init_windows_ops(), linux_nat_add_target(), linux_nat_attach(), procfs_target(), and target_attach().
int target_ops::to_attach_no_wait
Definition at line 477 of file target.h.
Referenced by _initialize_darwin_inferior(), _initialize_ia64_hpux_nat(), gnu_target(), init_windows_ops(), and update_current_target().
int(* target_ops::to_augmented_libraries_svr4_read)(void)
Definition at line 888 of file target.h.
Referenced by init_remote_ops(), and update_current_target().
int(* target_ops::to_auxv_parse)(struct target_ops *ops, gdb_byte **readptr, gdb_byte *endptr, CORE_ADDR *typep, CORE_ADDR *valp)
Definition at line 578 of file target.h.
Referenced by _initialize_ppc_linux_nat(), _initialize_s390_nat(), inf_ptrace_target(), procfs_target(), and target_auxv_parse().
void(* target_ops::to_call_history)(int size, int flags)
Definition at line 874 of file target.h.
Referenced by init_record_btrace_ops(), and target_call_history().
void(* target_ops::to_call_history_from)(ULONGEST begin, int size, int flags)
Definition at line 880 of file target.h.
Referenced by init_record_btrace_ops(), and target_call_history_from().
void(* target_ops::to_call_history_range)(ULONGEST begin, ULONGEST end, int flags)
Definition at line 884 of file target.h.
Referenced by init_record_btrace_ops(), and target_call_history_range().
int(* target_ops::to_can_accel_watchpoint_condition)(CORE_ADDR, int, int, struct expression *)
Definition at line 425 of file target.h.
Referenced by _initialize_ppc_linux_nat(), setup_target_debug(), and update_current_target().
int(* target_ops::to_can_async_p)(void)
Definition at line 479 of file target.h.
Referenced by find_default_can_async_p(), init_record_full_core_ops(), init_record_full_ops(), init_remote_ops(), linux_nat_add_target(), and update_current_target().
int(* target_ops::to_can_download_tracepoint)(void)
Definition at line 688 of file target.h.
Referenced by init_remote_ops(), and update_current_target().
int(* target_ops::to_can_execute_reverse)(void)
Definition at line 593 of file target.h.
Referenced by init_record_full_core_ops(), init_record_full_ops(), init_remote_ops(), and update_current_target().
int(* target_ops::to_can_run)(void)
Definition at line 450 of file target.h.
Referenced by inf_child_target(), init_go32_ops(), init_procfs_ops(), init_windows_ops(), setup_target_debug(), and update_current_target().
int(* target_ops::to_can_run_breakpoint_commands)(void)
Definition at line 620 of file target.h.
Referenced by init_remote_ops(), and update_current_target().
int(* target_ops::to_can_use_agent)(void)
Definition at line 809 of file target.h.
Referenced by inf_child_target(), init_remote_ops(), and update_current_target().
int(* target_ops::to_can_use_hw_breakpoint)(int, int, int)
Definition at line 400 of file target.h.
Referenced by _initialize_aarch64_linux_nat(), _initialize_arm_linux_nat(), _initialize_ia64_hpux_nat(), _initialize_ia64_linux_nat(), _initialize_mips_linux_nat(), _initialize_ppc_linux_nat(), _initialize_remote_mips(), _initialize_s390_nat(), _initialize_spu_nat(), i386_use_watchpoints(), init_m32r_ops(), init_procfs_ops(), init_remote_ops(), procfs_use_watchpoints(), setup_target_debug(), and update_current_target().
void(* target_ops::to_close)(void)
Definition at line 359 of file target.h.
Referenced by _initialize_mips_linux_nat(), _initialize_remote_mips(), bsd_kvm_add_target(), bsd_uthread_target(), init_core_ops(), init_exec_ops(), init_gdbsim_ops(), init_go32_ops(), init_m32r_ops(), init_record_btrace_ops(), init_record_full_core_ops(), init_record_full_ops(), init_remote_ops(), init_tfile_ops(), init_windows_ops(), linux_nat_add_target(), linux_nat_close(), target_close(), and update_current_target().
int(* target_ops::to_core_of_thread)(struct target_ops *, ptid_t ptid)
Definition at line 763 of file target.h.
Referenced by init_remote_ops(), linux_nat_add_target(), and target_core_of_thread().
void(* target_ops::to_create_inferior)(struct target_ops *, char *, char *, char **, int)
Definition at line 437 of file target.h.
Referenced by _initialize_darwin_inferior(), _initialize_remote_mips(), _initialize_rs6000_nat(), find_default_create_inferior(), gnu_target(), inf_ptrace_target(), init_core_ops(), init_exec_ops(), init_extended_remote_ops(), init_gdbsim_ops(), init_go32_ops(), init_m32r_ops(), init_procfs_ops(), init_record_btrace_ops(), init_record_full_ops(), init_windows_ops(), linux_nat_add_target(), linux_nat_create_inferior(), procfs_target(), target_create_inferior(), and target_require_runnable().
void* target_ops::to_data
Definition at line 349 of file target.h.
Referenced by target_bfd_get_section_table(), target_bfd_reopen(), target_bfd_xclose(), and target_bfd_xfer_partial().
void(* target_ops::to_delete_record)(void)
Definition at line 841 of file target.h.
Referenced by init_record_full_core_ops(), init_record_full_ops(), target_delete_record(), and target_supports_delete_record().
void(* target_ops::to_detach)(struct target_ops *ops, char *, int)
Definition at line 362 of file target.h.
Referenced by _initialize_darwin_inferior(), _initialize_remote_mips(), aix_thread_detach(), core_file_command(), dec_thread_detach(), gnu_target(), inf_ptrace_target(), init_aix_thread_ops(), init_core_ops(), init_dec_thread_ops(), init_extended_remote_ops(), init_gdbsim_ops(), init_go32_ops(), init_m32r_ops(), init_procfs_ops(), init_record_btrace_ops(), init_record_full_ops(), init_remote_ops(), init_sol_thread_ops(), init_thread_db_ops(), init_windows_ops(), linux_nat_add_target(), linux_nat_detach(), procfs_target(), sol_thread_detach(), target_detach(), and thread_db_detach().
void(* target_ops::to_disable_btrace)(struct btrace_target_info *tinfo)
Definition at line 819 of file target.h.
Referenced by _initialize_amd64_linux_nat(), _initialize_i386_linux_nat(), init_remote_ops(), and target_disable_btrace().
void(* target_ops::to_disable_tracepoint)(struct bp_location *location)
Definition at line 697 of file target.h.
Referenced by init_remote_ops(), and update_current_target().
void(* target_ops::to_disconnect)(struct target_ops *, char *, int)
Definition at line 363 of file target.h.
Referenced by init_record_btrace_ops(), init_record_full_ops(), init_remote_ops(), and target_disconnect().
char* target_ops::to_doc
Definition at line 345 of file target.h.
Referenced by _initialize_darwin_inferior(), _initialize_dbug_rom(), _initialize_dink32_rom(), _initialize_m32r_rom(), _initialize_picobug_rom(), _initialize_ppcbug_rom(), _initialize_remote_mips(), add_deprecated_target_alias(), add_target_with_completer(), bsd_kvm_add_target(), bsd_uthread_target(), gnu_target(), inf_child_target(), init_aix_thread_ops(), init_core_ops(), init_dec_thread_ops(), init_exec_ops(), init_extended_remote_ops(), init_gdbsim_ops(), init_go32_ops(), init_m32r_ops(), init_procfs_ops(), init_ravenscar_thread_ops(), init_record_btrace_ops(), init_record_full_core_ops(), init_record_full_ops(), init_remote_ops(), init_sol_thread_ops(), init_spu_ops(), init_tfile_ops(), init_thread_db_ops(), init_windows_ops(), procfs_target(), target_bfd_reopen(), and update_current_target().
void(* target_ops::to_download_trace_state_variable)(struct trace_state_variable *tsv)
Definition at line 691 of file target.h.
Referenced by init_remote_ops(), and update_current_target().
void(* target_ops::to_download_tracepoint)(struct bp_location *location)
Definition at line 684 of file target.h.
Referenced by init_remote_ops(), and update_current_target().
struct btrace_target_info*(* target_ops::to_enable_btrace)(ptid_t ptid) [read]
Definition at line 816 of file target.h.
Referenced by _initialize_amd64_linux_nat(), _initialize_i386_linux_nat(), init_remote_ops(), and target_enable_btrace().
void(* target_ops::to_enable_tracepoint)(struct bp_location *location)
Definition at line 694 of file target.h.
Referenced by init_remote_ops(), and update_current_target().
enum exec_direction_kind(* target_ops::to_execution_direction)(void)
Definition at line 598 of file target.h.
Referenced by init_record_full_core_ops(), init_record_full_ops(), and update_current_target().
char*(* target_ops::to_extra_thread_info)(struct thread_info *)
Definition at line 463 of file target.h.
Referenced by bsd_uthread_target(), init_aix_thread_ops(), init_procfs_ops(), init_ravenscar_thread_ops(), init_remote_ops(), init_thread_db_ops(), and update_current_target().
void(* target_ops::to_fetch_registers)(struct target_ops *, struct regcache *, int)
Definition at line 367 of file target.h.
Referenced by _initialize_aarch64_linux_nat(), _initialize_alphabsd_nat(), _initialize_amd64_linux_nat(), _initialize_arm_linux_nat(), _initialize_arm_netbsd_nat(), _initialize_hppa_hpux_nat(), _initialize_hppa_linux_nat(), _initialize_hppabsd_nat(), _initialize_hppanbsd_nat(), _initialize_i386_linux_nat(), _initialize_i386gnu_nat(), _initialize_ia64_hpux_nat(), _initialize_ia64_linux_nat(), _initialize_m32r_linux_nat(), _initialize_m68k_linux_nat(), _initialize_m68kbsd_nat(), _initialize_m88kbsd_nat(), _initialize_mips64obsd_nat(), _initialize_mips_linux_nat(), _initialize_mipsnbsd_nat(), _initialize_ppc_linux_nat(), _initialize_ppcfbsd_nat(), _initialize_ppcnbsd_nat(), _initialize_ppcobsd_nat(), _initialize_remote_mips(), _initialize_rs6000_nat(), _initialize_s390_nat(), _initialize_shnbsd_nat(), _initialize_sparc64_linux_nat(), _initialize_sparc_linux_nat(), _initialize_spu_nat(), _initialize_tile_linux_nat(), _initialize_vaxbsd_nat(), _initialize_xtensa_linux_nat(), aix_thread_fetch_registers(), amd64bsd_target(), bsd_kvm_add_target(), bsd_uthread_fetch_registers(), bsd_uthread_target(), darwin_complete_target(), dec_thread_fetch_registers(), i386bsd_target(), inf_child_target(), inf_ptrace_trad_target(), init_aix_thread_ops(), init_core_ops(), init_dec_thread_ops(), init_gdbsim_ops(), init_go32_ops(), init_m32r_ops(), init_procfs_ops(), init_ravenscar_thread_ops(), init_record_full_core_ops(), init_remote_ops(), init_sol_thread_ops(), init_spu_ops(), init_tfile_ops(), init_windows_ops(), procfs_target(), ravenscar_fetch_registers(), sol_thread_fetch_registers(), sparc_target(), spu_fetch_registers(), spu_store_registers(), and target_fetch_registers().
int(* target_ops::to_fileio_close)(int fd, int *target_errno)
Definition at line 663 of file target.h.
Referenced by inf_child_target(), init_remote_ops(), and target_fileio_close().
int(* target_ops::to_fileio_open)(const char *filename, int flags, int mode, int *target_errno)
Definition at line 646 of file target.h.
Referenced by inf_child_target(), init_remote_ops(), and target_fileio_open().
int(* target_ops::to_fileio_pread)(int fd, gdb_byte *read_buf, int len, ULONGEST offset, int *target_errno)
Definition at line 658 of file target.h.
Referenced by inf_child_target(), init_remote_ops(), and target_fileio_pread().
int(* target_ops::to_fileio_pwrite)(int fd, const gdb_byte *write_buf, int len, ULONGEST offset, int *target_errno)
Definition at line 652 of file target.h.
Referenced by inf_child_target(), init_remote_ops(), and target_fileio_pwrite().
char*(* target_ops::to_fileio_readlink)(const char *filename, int *target_errno)
Definition at line 672 of file target.h.
Referenced by inf_child_target(), init_remote_ops(), and target_fileio_readlink().
int(* target_ops::to_fileio_unlink)(const char *filename, int *target_errno)
Definition at line 667 of file target.h.
Referenced by inf_child_target(), init_remote_ops(), and target_fileio_unlink().
void(* target_ops::to_files_info)(struct target_ops *)
Definition at line 397 of file target.h.
Referenced by _initialize_darwin_inferior(), _initialize_remote_mips(), bsd_kvm_add_target(), inf_ptrace_target(), init_core_ops(), init_exec_ops(), init_gdbsim_ops(), init_go32_ops(), init_m32r_ops(), init_procfs_ops(), init_remote_ops(), init_tfile_ops(), init_windows_ops(), procfs_target(), setup_target_debug(), target_info(), and update_current_target().
int(* target_ops::to_find_memory_regions)(find_memory_region_ftype func, void *data)
Definition at line 484 of file target.h.
Referenced by _initialize_amd64fbsd_nat(), _initialize_i386fbsd_nat(), _initialize_ppcfbsd_nat(), _initialize_sparc64fbsd_nat(), exec_set_find_memory_regions(), gnu_target(), procfs_target(), and update_current_target().
void(* target_ops::to_find_new_threads)(struct target_ops *)
Definition at line 461 of file target.h.
Referenced by bsd_uthread_target(), init_dec_thread_ops(), init_procfs_ops(), init_ravenscar_thread_ops(), init_remote_ops(), init_sol_thread_ops(), init_thread_db_ops(), procfs_target(), sol_find_new_threads(), and target_find_new_threads().
void(* target_ops::to_flash_done)(struct target_ops *)
Definition at line 561 of file target.h.
Referenced by init_remote_ops(), and target_flash_done().
void(* target_ops::to_flash_erase)(struct target_ops *, ULONGEST address, LONGEST length)
Definition at line 554 of file target.h.
Referenced by init_remote_ops(), and target_flash_erase().
int(* target_ops::to_follow_fork)(struct target_ops *, int, int)
Definition at line 444 of file target.h.
Referenced by inf_child_target(), inf_ptrace_target(), linux_target_install_ops(), and target_follow_fork().
ptid_t(* target_ops::to_get_ada_task_ptid)(long lwp, long thread)
Definition at line 572 of file target.h.
Referenced by _initialize_darwin_inferior(), init_aix_thread_ops(), init_dec_thread_ops(), init_ravenscar_thread_ops(), init_remote_ops(), init_sol_thread_ops(), init_thread_db_ops(), init_windows_ops(), and update_current_target().
gdb_byte*(* target_ops::to_get_bookmark)(char *, int)
Definition at line 488 of file target.h.
Referenced by init_record_full_core_ops(), init_record_full_ops(), and update_current_target().
int(* target_ops::to_get_min_fast_tracepoint_insn_len)(void)
Definition at line 742 of file target.h.
Referenced by init_remote_ops(), and update_current_target().
LONGEST(* target_ops::to_get_raw_trace_data)(gdb_byte *buf, ULONGEST offset, LONGEST len)
Definition at line 735 of file target.h.
Referenced by init_remote_ops(), and update_current_target().
struct target_section_table*(* target_ops::to_get_section_table)(struct target_ops *) [read]
Definition at line 469 of file target.h.
Referenced by init_exec_ops(), target_bfd_reopen(), and target_get_section_table().
CORE_ADDR(* target_ops::to_get_thread_local_address)(struct target_ops *ops, ptid_t ptid, CORE_ADDR load_module_addr, CORE_ADDR offset)
Definition at line 496 of file target.h.
Referenced by init_remote_ops(), init_thread_db_ops(), ppc_linux_spe_context(), target_translate_tls_address(), and thread_db_get_thread_local_address().
int(* target_ops::to_get_tib_address)(ptid_t ptid, CORE_ADDR *addr)
Definition at line 774 of file target.h.
Referenced by init_remote_ops(), init_windows_ops(), and update_current_target().
int(* target_ops::to_get_trace_state_variable_value)(int tsv, LONGEST *val)
Definition at line 727 of file target.h.
Referenced by init_remote_ops(), init_tfile_ops(), and update_current_target().
int(* target_ops::to_get_trace_status)(struct trace_status *ts)
Definition at line 708 of file target.h.
Referenced by init_remote_ops(), init_tfile_ops(), and update_current_target().
void(* target_ops::to_get_tracepoint_status)(struct breakpoint *tp, struct uploaded_tp *utp)
Definition at line 710 of file target.h.
Referenced by init_remote_ops(), init_tfile_ops(), and update_current_target().
void(* target_ops::to_goto_bookmark)(gdb_byte *, int)
Definition at line 490 of file target.h.
Referenced by init_record_full_core_ops(), init_record_full_ops(), and update_current_target().
void(* target_ops::to_goto_record)(ULONGEST insn)
Definition at line 853 of file target.h.
Referenced by init_record_full_core_ops(), init_record_full_ops(), and target_goto_record().
void(* target_ops::to_goto_record_begin)(void)
Definition at line 847 of file target.h.
Referenced by init_record_full_core_ops(), init_record_full_ops(), and target_goto_record_begin().
void(* target_ops::to_goto_record_end)(void)
Definition at line 850 of file target.h.
Referenced by init_record_full_core_ops(), init_record_full_ops(), and target_goto_record_end().
int(* target_ops::to_has_all_memory)(struct target_ops *)
Definition at line 471 of file target.h.
Referenced by _initialize_remote_mips(), complete_target_initialization(), inf_child_target(), init_gdbsim_ops(), init_go32_ops(), init_m32r_ops(), init_procfs_ops(), init_ravenscar_thread_ops(), init_remote_ops(), init_tfile_ops(), init_windows_ops(), memory_xfer_partial_1(), target_has_all_memory_1(), and target_info().
int(* target_ops::to_has_execution)(struct target_ops *, ptid_t)
Definition at line 475 of file target.h.
Referenced by _initialize_remote_mips(), complete_target_initialization(), inf_child_target(), init_gdbsim_ops(), init_go32_ops(), init_m32r_ops(), init_procfs_ops(), init_ravenscar_thread_ops(), init_record_full_core_ops(), init_remote_ops(), init_windows_ops(), and target_has_execution_1().
int(* target_ops::to_has_exited)(int, int, int *)
Definition at line 448 of file target.h.
Referenced by setup_target_debug(), and update_current_target().
int(* target_ops::to_has_memory)(struct target_ops *)
Definition at line 472 of file target.h.
Referenced by _initialize_remote_mips(), bsd_kvm_add_target(), complete_target_initialization(), gdbsim_xfer_memory(), inf_child_target(), init_core_ops(), init_exec_ops(), init_gdbsim_ops(), init_go32_ops(), init_m32r_ops(), init_procfs_ops(), init_ravenscar_thread_ops(), init_remote_ops(), init_tfile_ops(), init_windows_ops(), target_has_memory_1(), and target_info().
int(* target_ops::to_has_registers)(struct target_ops *)
Definition at line 474 of file target.h.
Referenced by _initialize_remote_mips(), bsd_kvm_add_target(), complete_target_initialization(), inf_child_target(), init_core_ops(), init_gdbsim_ops(), init_go32_ops(), init_m32r_ops(), init_procfs_ops(), init_ravenscar_thread_ops(), init_remote_ops(), init_tfile_ops(), init_windows_ops(), and target_has_registers_1().
int(* target_ops::to_has_stack)(struct target_ops *)
Definition at line 473 of file target.h.
Referenced by _initialize_remote_mips(), bsd_kvm_add_target(), complete_target_initialization(), inf_child_target(), init_core_ops(), init_gdbsim_ops(), init_go32_ops(), init_m32r_ops(), init_procfs_ops(), init_ravenscar_thread_ops(), init_remote_ops(), init_tfile_ops(), init_windows_ops(), and target_has_stack_1().
int target_ops::to_has_thread_control
Definition at line 476 of file target.h.
Referenced by init_remote_ops(), init_thread_db_ops(), linux_nat_add_target(), procfs_target(), and update_current_target().
int target_ops::to_have_continuable_watchpoint
Definition at line 416 of file target.h.
Referenced by _initialize_s390_nat(), i386_use_watchpoints(), init_procfs_ops(), and update_current_target().
int target_ops::to_have_steppable_watchpoint
Definition at line 415 of file target.h.
Referenced by _initialize_ia64_linux_nat(), and update_current_target().
void(* target_ops::to_info_proc)(struct target_ops *, char *, enum info_proc_what)
Definition at line 676 of file target.h.
Referenced by init_core_ops(), procfs_target(), and target_info_proc().
void(* target_ops::to_info_record)(void)
Definition at line 835 of file target.h.
Referenced by info_record_command(), init_record_btrace_ops(), init_record_full_core_ops(), init_record_full_ops(), and target_info_record().
int(* target_ops::to_insert_breakpoint)(struct gdbarch *, struct bp_target_info *)
Definition at line 398 of file target.h.
Referenced by _initialize_remote_mips(), inf_child_target(), init_core_ops(), init_exec_ops(), init_gdbsim_ops(), init_go32_ops(), init_m32r_ops(), init_procfs_ops(), init_record_full_core_ops(), init_record_full_ops(), init_remote_ops(), init_windows_ops(), record_full_open(), setup_target_debug(), target_insert_breakpoint(), and update_current_target().
int(* target_ops::to_insert_exec_catchpoint)(int)
Definition at line 445 of file target.h.
Referenced by linux_target_install_ops(), setup_target_debug(), and update_current_target().
int(* target_ops::to_insert_fork_catchpoint)(int)
Definition at line 440 of file target.h.
Referenced by linux_target_install_ops(), setup_target_debug(), and update_current_target().
int(* target_ops::to_insert_hw_breakpoint)(struct gdbarch *, struct bp_target_info *)
Definition at line 402 of file target.h.
Referenced by _initialize_aarch64_linux_nat(), _initialize_arm_linux_nat(), _initialize_ppc_linux_nat(), i386_use_watchpoints(), init_procfs_ops(), init_remote_ops(), setup_target_debug(), and update_current_target().
int(* target_ops::to_insert_mask_watchpoint)(struct target_ops *, CORE_ADDR, CORE_ADDR, int)
Definition at line 410 of file target.h.
Referenced by _initialize_ppc_linux_nat(), and target_insert_mask_watchpoint().
int(* target_ops::to_insert_vfork_catchpoint)(int)
Definition at line 442 of file target.h.
Referenced by linux_target_install_ops(), setup_target_debug(), and update_current_target().
int(* target_ops::to_insert_watchpoint)(CORE_ADDR, int, int, struct expression *)
Definition at line 408 of file target.h.
Referenced by _initialize_aarch64_linux_nat(), _initialize_arm_linux_nat(), _initialize_ia64_linux_nat(), _initialize_mips_linux_nat(), _initialize_ppc_linux_nat(), _initialize_remote_mips(), _initialize_s390_nat(), i386_use_watchpoints(), init_m32r_ops(), init_procfs_ops(), init_remote_ops(), procfs_use_watchpoints(), setup_target_debug(), and update_current_target().
void(* target_ops::to_insn_history)(int size, int flags)
Definition at line 859 of file target.h.
Referenced by init_record_btrace_ops(), and target_insn_history().
void(* target_ops::to_insn_history_from)(ULONGEST from, int size, int flags)
Definition at line 865 of file target.h.
Referenced by init_record_btrace_ops(), and target_insn_history_from().
void(* target_ops::to_insn_history_range)(ULONGEST begin, ULONGEST end, int flags)
Definition at line 869 of file target.h.
Referenced by init_record_btrace_ops(), and target_insn_history_range().
int(* target_ops::to_is_async_p)(void)
Definition at line 480 of file target.h.
Referenced by find_default_is_async_p(), init_record_full_core_ops(), init_record_full_ops(), init_remote_ops(), linux_nat_add_target(), and update_current_target().
void(* target_ops::to_kill)(struct target_ops *)
Definition at line 435 of file target.h.
Referenced by _initialize_darwin_inferior(), _initialize_remote_mips(), gnu_target(), inf_ptrace_target(), init_extended_remote_ops(), init_gdbsim_ops(), init_go32_ops(), init_m32r_ops(), init_procfs_ops(), init_record_btrace_ops(), init_record_full_core_ops(), init_record_full_ops(), init_remote_ops(), init_windows_ops(), linux_nat_add_target(), procfs_target(), and target_kill().
void(* target_ops::to_load)(char *, int)
Definition at line 436 of file target.h.
Referenced by _initialize_darwin_inferior(), _initialize_m32r_rom(), _initialize_remote_mips(), init_gdbsim_ops(), init_m32r_ops(), init_remote_ops(), setup_target_debug(), target_load(), and update_current_target().
void(* target_ops::to_log_command)(const char *)
Definition at line 468 of file target.h.
Referenced by _initialize_remote_mips(), init_m32r_ops(), init_remote_ops(), and update_current_target().
char* target_ops::to_longname
Definition at line 344 of file target.h.
Referenced by _initialize_darwin_inferior(), _initialize_dbug_rom(), _initialize_dink32_rom(), _initialize_m32r_rom(), _initialize_picobug_rom(), _initialize_ppcbug_rom(), _initialize_remote_mips(), bsd_kvm_add_target(), bsd_uthread_target(), gnu_target(), inf_child_target(), init_aix_thread_ops(), init_core_ops(), init_dec_thread_ops(), init_exec_ops(), init_extended_remote_ops(), init_gdbsim_ops(), init_go32_ops(), init_m32r_ops(), init_procfs_ops(), init_ravenscar_thread_ops(), init_record_btrace_ops(), init_record_full_core_ops(), init_record_full_ops(), init_remote_ops(), init_sol_thread_ops(), init_spu_ops(), init_tfile_ops(), init_thread_db_ops(), init_windows_ops(), maintenance_print_target_stack(), procfs_target(), target_bfd_reopen(), target_info(), and update_current_target().
int target_ops::to_magic
Definition at line 890 of file target.h.
Referenced by _initialize_remote_mips(), bsd_kvm_add_target(), bsd_uthread_target(), inf_child_target(), init_aix_thread_ops(), init_core_ops(), init_dec_thread_ops(), init_exec_ops(), init_gdbsim_ops(), init_go32_ops(), init_m32r_ops(), init_procfs_ops(), init_ravenscar_thread_ops(), init_record_btrace_ops(), init_record_full_core_ops(), init_record_full_ops(), init_remote_ops(), init_sol_thread_ops(), init_spu_ops(), init_tfile_ops(), init_thread_db_ops(), init_windows_ops(), procfs_target(), push_target(), target_bfd_reopen(), target_is_pushed(), and update_current_target().
char*(* target_ops::to_make_corefile_notes)(bfd *, int *)
Definition at line 486 of file target.h.
Referenced by _initialize_amd64fbsd_nat(), _initialize_i386fbsd_nat(), _initialize_ppcfbsd_nat(), _initialize_sparc64fbsd_nat(), init_exec_ops(), linux_target_install_ops(), procfs_target(), and update_current_target().
int(* target_ops::to_masked_watch_num_registers)(struct target_ops *, CORE_ADDR, CORE_ADDR)
Definition at line 427 of file target.h.
Referenced by _initialize_ppc_linux_nat(), and target_masked_watch_num_registers().
void(* target_ops::to_mourn_inferior)(struct target_ops *)
Definition at line 449 of file target.h.
Referenced by _initialize_amd64fbsd_nat(), _initialize_darwin_inferior(), _initialize_ia64_hpux_nat(), _initialize_remote_mips(), aix_thread_mourn_inferior(), bsd_uthread_mourn_inferior(), bsd_uthread_target(), dec_thread_mourn_inferior(), gnu_target(), inf_ptrace_target(), init_aix_thread_ops(), init_dec_thread_ops(), init_extended_remote_ops(), init_gdbsim_ops(), init_go32_ops(), init_m32r_ops(), init_procfs_ops(), init_ravenscar_thread_ops(), init_record_btrace_ops(), init_record_full_ops(), init_remote_ops(), init_sol_thread_ops(), init_spu_ops(), init_thread_db_ops(), init_windows_ops(), linux_nat_add_target(), linux_nat_mourn_inferior(), procfs_target(), ravenscar_mourn_inferior(), sol_thread_mourn_inferior(), spu_mourn_inferior(), target_mourn_inferior(), and thread_db_mourn_inferior().
void(* target_ops::to_open)(char *, int)
Definition at line 354 of file target.h.
Referenced by _initialize_dbug_rom(), _initialize_dink32_rom(), _initialize_m32r_rom(), _initialize_picobug_rom(), _initialize_ppcbug_rom(), _initialize_remote_mips(), add_deprecated_target_alias(), add_target_with_completer(), bsd_kvm_add_target(), core_file_command(), inf_child_target(), init_core_ops(), init_exec_ops(), init_extended_remote_ops(), init_gdbsim_ops(), init_go32_ops(), init_m32r_ops(), init_procfs_ops(), init_record_btrace_ops(), init_record_full_core_ops(), init_record_full_ops(), init_remote_ops(), init_tfile_ops(), init_windows_ops(), setup_target_debug(), and update_current_target().
void(* target_ops::to_pass_signals)(int, unsigned char *)
Definition at line 454 of file target.h.
Referenced by init_procfs_ops(), init_remote_ops(), linux_nat_add_target(), procfs_target(), and target_pass_signals().
char*(* target_ops::to_pid_to_exec_file)(int pid)
Definition at line 467 of file target.h.
Referenced by _initialize_amd64fbsd_nat(), _initialize_amd64nbsd_nat(), _initialize_darwin_inferior(), _initialize_hppanbsd_nat(), _initialize_i386fbsd_nat(), _initialize_i386nbsd_nat(), _initialize_ppcfbsd_nat(), _initialize_sparc64fbsd_nat(), inf_child_target(), init_windows_ops(), linux_target_install_ops(), setup_target_debug(), and update_current_target().
char*(* target_ops::to_pid_to_str)(struct target_ops *, ptid_t)
Definition at line 462 of file target.h.
Referenced by _initialize_darwin_inferior(), _initialize_remote_mips(), aix_thread_pid_to_str(), bsd_kvm_add_target(), bsd_uthread_target(), dec_thread_pid_to_str(), gnu_target(), inf_ptrace_target(), init_aix_thread_ops(), init_core_ops(), init_dec_thread_ops(), init_gdbsim_ops(), init_go32_ops(), init_m32r_ops(), init_procfs_ops(), init_ravenscar_thread_ops(), init_remote_ops(), init_sol_thread_ops(), init_thread_db_ops(), init_windows_ops(), linux_nat_add_target(), procfs_target(), target_pid_to_str(), and thread_db_pid_to_str().
void(* target_ops::to_post_attach)(int)
Definition at line 361 of file target.h.
Referenced by _initialize_spu_nat(), inf_child_target(), inf_ptrace_target(), init_procfs_ops(), linux_target_install_ops(), setup_target_debug(), and update_current_target().
void(* target_ops::to_post_startup_inferior)(ptid_t)
Definition at line 439 of file target.h.
Referenced by _initialize_aarch64_linux_nat(), _initialize_amd64_linux_nat(), _initialize_i386_linux_nat(), _initialize_spu_nat(), inf_child_target(), inf_ptrace_target(), linux_target_install_ops(), setup_target_debug(), and update_current_target().
void(* target_ops::to_prepare_to_store)(struct regcache *)
Definition at line 369 of file target.h.
Referenced by _initialize_remote_mips(), inf_child_target(), init_gdbsim_ops(), init_go32_ops(), init_m32r_ops(), init_procfs_ops(), init_ravenscar_thread_ops(), init_record_full_core_ops(), init_remote_ops(), init_windows_ops(), ravenscar_prepare_to_store(), setup_target_debug(), and update_current_target().
void(* target_ops::to_program_signals)(int, unsigned char *)
Definition at line 458 of file target.h.
Referenced by init_remote_ops(), and target_program_signals().
int(* target_ops::to_ranged_break_num_registers)(struct target_ops *)
Definition at line 401 of file target.h.
Referenced by _initialize_ppc_linux_nat(), and target_ranged_break_num_registers().
void(* target_ops::to_rcmd)(char *command, struct ui_file *output)
Definition at line 466 of file target.h.
Referenced by do_monitor_command(), init_remote_ops(), setup_target_debug(), and update_current_target().
struct target_desc*(* target_ops::to_read_description)(struct target_ops *ops) [read]
Definition at line 566 of file target.h.
Referenced by _initialize_aarch64_linux_nat(), _initialize_amd64_linux_nat(), _initialize_arm_linux_nat(), _initialize_i386_linux_nat(), _initialize_mips_linux_nat(), _initialize_ppc_linux_nat(), _initialize_s390_nat(), init_core_ops(), init_remote_ops(), target_read_description(), and update_current_target().
int(* target_ops::to_record_is_replaying)(void)
Definition at line 844 of file target.h.
Referenced by init_record_full_core_ops(), init_record_full_ops(), and target_record_is_replaying().
int(* target_ops::to_region_ok_for_hw_watchpoint)(CORE_ADDR, int)
Definition at line 423 of file target.h.
Referenced by _initialize_aarch64_linux_nat(), _initialize_arm_linux_nat(), _initialize_mips_linux_nat(), _initialize_ppc_linux_nat(), _initialize_s390_nat(), i386_use_watchpoints(), init_remote_ops(), init_spu_ops(), procfs_use_watchpoints(), setup_target_debug(), spu_region_ok_for_hw_watchpoint(), and update_current_target().
int(* target_ops::to_remove_breakpoint)(struct gdbarch *, struct bp_target_info *)
Definition at line 399 of file target.h.
Referenced by _initialize_remote_mips(), inf_child_target(), init_core_ops(), init_exec_ops(), init_gdbsim_ops(), init_go32_ops(), init_m32r_ops(), init_procfs_ops(), init_record_full_core_ops(), init_record_full_ops(), init_remote_ops(), init_windows_ops(), record_full_open(), setup_target_debug(), target_remove_breakpoint(), and update_current_target().
int(* target_ops::to_remove_exec_catchpoint)(int)
Definition at line 446 of file target.h.
Referenced by linux_target_install_ops(), setup_target_debug(), and update_current_target().
int(* target_ops::to_remove_fork_catchpoint)(int)
Definition at line 441 of file target.h.
Referenced by linux_target_install_ops(), setup_target_debug(), and update_current_target().
int(* target_ops::to_remove_hw_breakpoint)(struct gdbarch *, struct bp_target_info *)
Definition at line 403 of file target.h.
Referenced by _initialize_aarch64_linux_nat(), _initialize_arm_linux_nat(), _initialize_ppc_linux_nat(), i386_use_watchpoints(), init_procfs_ops(), init_remote_ops(), setup_target_debug(), and update_current_target().
int(* target_ops::to_remove_mask_watchpoint)(struct target_ops *, CORE_ADDR, CORE_ADDR, int)
Definition at line 412 of file target.h.
Referenced by _initialize_ppc_linux_nat(), and target_remove_mask_watchpoint().
int(* target_ops::to_remove_vfork_catchpoint)(int)
Definition at line 443 of file target.h.
Referenced by linux_target_install_ops(), setup_target_debug(), and update_current_target().
int(* target_ops::to_remove_watchpoint)(CORE_ADDR, int, int, struct expression *)
Definition at line 407 of file target.h.
Referenced by _initialize_aarch64_linux_nat(), _initialize_arm_linux_nat(), _initialize_ia64_linux_nat(), _initialize_mips_linux_nat(), _initialize_ppc_linux_nat(), _initialize_remote_mips(), _initialize_s390_nat(), i386_use_watchpoints(), init_m32r_ops(), init_procfs_ops(), init_remote_ops(), procfs_use_watchpoints(), setup_target_debug(), and update_current_target().
void(* target_ops::to_resume)(struct target_ops *, ptid_t, int, enum gdb_signal)
Definition at line 364 of file target.h.
Referenced by _initialize_darwin_inferior(), _initialize_i386_linux_nat(), _initialize_i386fbsd_nat(), _initialize_remote_mips(), aix_thread_resume(), bsd_uthread_resume(), bsd_uthread_target(), gnu_target(), inf_ptrace_target(), init_aix_thread_ops(), init_gdbsim_ops(), init_go32_ops(), init_m32r_ops(), init_procfs_ops(), init_ravenscar_thread_ops(), init_record_full_core_ops(), init_record_full_ops(), init_remote_ops(), init_sol_thread_ops(), init_thread_db_ops(), init_windows_ops(), linux_handle_extended_wait(), linux_handle_syscall_trap(), linux_nat_add_target(), linux_nat_filter_event(), linux_nat_resume(), linux_nat_wait_1(), procfs_target(), ravenscar_resume(), record_full_open(), resume_lwp(), resume_stopped_resumed_lwps(), sol_thread_resume(), target_resume(), and thread_db_resume().
void(* target_ops::to_save_record)(const char *filename)
Definition at line 838 of file target.h.
Referenced by init_record_full_ops(), and target_save_record().
int(* target_ops::to_save_trace_data)(const char *filename)
Definition at line 729 of file target.h.
Referenced by init_remote_ops(), and update_current_target().
int(* target_ops::to_search_memory)(struct target_ops *ops, CORE_ADDR start_addr, ULONGEST search_space_len, const gdb_byte *pattern, ULONGEST pattern_len, CORE_ADDR *found_addrp)
Definition at line 587 of file target.h.
Referenced by init_remote_ops(), init_spu_ops(), spu_search_memory(), and target_search_memory().
void(* target_ops::to_set_circular_trace_buffer)(int val)
Definition at line 747 of file target.h.
Referenced by init_remote_ops(), and update_current_target().
void(* target_ops::to_set_disconnected_tracing)(int val)
Definition at line 746 of file target.h.
Referenced by init_remote_ops(), and update_current_target().
void(* target_ops::to_set_permissions)(void)
Definition at line 777 of file target.h.
Referenced by init_remote_ops(), and update_current_target().
int(* target_ops::to_set_syscall_catchpoint)(int, int, int, int, int *)
Definition at line 447 of file target.h.
Referenced by linux_target_install_ops(), and update_current_target().
void(* target_ops::to_set_trace_buffer_size)(LONGEST val)
Definition at line 749 of file target.h.
Referenced by init_remote_ops(), and update_current_target().
int(* target_ops::to_set_trace_notes)(const char *user, const char *notes, const char *stopnotes)
Definition at line 753 of file target.h.
Referenced by init_remote_ops(), and update_current_target().
char* target_ops::to_shortname
Definition at line 343 of file target.h.
Referenced by _initialize_darwin_inferior(), _initialize_dbug_rom(), _initialize_dink32_rom(), _initialize_m32r_rom(), _initialize_picobug_rom(), _initialize_ppcbug_rom(), _initialize_remote_mips(), add_deprecated_target_alias(), add_target_with_completer(), bsd_kvm_add_target(), bsd_uthread_target(), gnu_target(), inf_child_target(), info_record_command(), init_aix_thread_ops(), init_core_ops(), init_dec_thread_ops(), init_exec_ops(), init_extended_remote_ops(), init_gdbsim_ops(), init_go32_ops(), init_m32r_ops(), init_procfs_ops(), init_ravenscar_thread_ops(), init_record_btrace_ops(), init_record_full_core_ops(), init_record_full_ops(), init_remote_ops(), init_sol_thread_ops(), init_spu_ops(), init_tfile_ops(), init_thread_db_ops(), init_windows_ops(), maintenance_print_target_stack(), monitor_open(), pop_all_targets_above(), procfs_target(), push_target(), record_detach(), record_disconnect(), record_kill(), record_mourn_inferior(), record_stop(), record_unpush(), target_bfd_reopen(), target_is_native(), target_is_pushed(), target_require_runnable(), target_xfer_partial(), and update_current_target().
int(* target_ops::to_static_tracepoint_marker_at)(CORE_ADDR, struct static_tracepoint_marker *marker)
Definition at line 781 of file target.h.
Referenced by init_remote_ops(), and update_current_target().
void(* target_ops::to_stop)(ptid_t)
Definition at line 465 of file target.h.
Referenced by _initialize_darwin_inferior(), gdb_stop(), gnu_target(), inf_ptrace_target(), init_gdbsim_ops(), init_m32r_ops(), init_procfs_ops(), init_remote_ops(), init_windows_ops(), linux_nat_add_target(), linux_nat_stop(), procfs_target(), setup_target_debug(), target_stop(), and update_current_target().
enum btrace_read_type void(* target_ops::to_stop_recording)(void)
Definition at line 832 of file target.h.
Referenced by init_record_btrace_ops(), record_stop(), and target_stop_recording().
int(* target_ops::to_stopped_by_watchpoint)(void)
Definition at line 414 of file target.h.
Referenced by _initialize_aarch64_linux_nat(), _initialize_arm_linux_nat(), _initialize_ia64_linux_nat(), _initialize_mips_linux_nat(), _initialize_ppc_linux_nat(), _initialize_remote_mips(), _initialize_s390_nat(), i386_use_watchpoints(), init_m32r_ops(), init_procfs_ops(), init_record_full_core_ops(), init_record_full_ops(), init_remote_ops(), linux_nat_add_target(), procfs_use_watchpoints(), record_full_open(), save_sigtrap(), setup_target_debug(), and update_current_target().
int(* target_ops::to_stopped_data_address)(struct target_ops *, CORE_ADDR *)
Definition at line 417 of file target.h.
Referenced by _initialize_aarch64_linux_nat(), _initialize_arm_linux_nat(), _initialize_ia64_linux_nat(), _initialize_mips_linux_nat(), _initialize_ppc_linux_nat(), i386_use_watchpoints(), init_m32r_ops(), init_record_full_core_ops(), init_record_full_ops(), init_remote_ops(), linux_nat_add_target(), procfs_use_watchpoints(), record_full_open(), save_sigtrap(), setup_target_debug(), and update_current_target().
void(* target_ops::to_store_registers)(struct target_ops *, struct regcache *, int)
Definition at line 368 of file target.h.
Referenced by _initialize_aarch64_linux_nat(), _initialize_alphabsd_nat(), _initialize_amd64_linux_nat(), _initialize_arm_linux_nat(), _initialize_arm_netbsd_nat(), _initialize_hppa_hpux_nat(), _initialize_hppa_linux_nat(), _initialize_hppabsd_nat(), _initialize_hppanbsd_nat(), _initialize_i386_linux_nat(), _initialize_i386gnu_nat(), _initialize_ia64_hpux_nat(), _initialize_ia64_linux_nat(), _initialize_m32r_linux_nat(), _initialize_m68k_linux_nat(), _initialize_m68kbsd_nat(), _initialize_m88kbsd_nat(), _initialize_mips64obsd_nat(), _initialize_mips_linux_nat(), _initialize_mipsnbsd_nat(), _initialize_ppc_linux_nat(), _initialize_ppcfbsd_nat(), _initialize_ppcnbsd_nat(), _initialize_ppcobsd_nat(), _initialize_remote_mips(), _initialize_rs6000_nat(), _initialize_s390_nat(), _initialize_shnbsd_nat(), _initialize_sparc64_linux_nat(), _initialize_sparc_linux_nat(), _initialize_spu_nat(), _initialize_tile_linux_nat(), _initialize_vaxbsd_nat(), _initialize_xtensa_linux_nat(), aix_thread_store_registers(), amd64bsd_target(), bsd_uthread_store_registers(), bsd_uthread_target(), darwin_complete_target(), dec_thread_store_registers(), i386bsd_target(), inf_child_target(), inf_ptrace_trad_target(), init_aix_thread_ops(), init_dec_thread_ops(), init_gdbsim_ops(), init_go32_ops(), init_m32r_ops(), init_procfs_ops(), init_ravenscar_thread_ops(), init_record_full_core_ops(), init_record_full_ops(), init_remote_ops(), init_sol_thread_ops(), init_spu_ops(), init_windows_ops(), procfs_target(), ravenscar_store_registers(), record_full_open(), sol_thread_store_registers(), sparc_target(), spu_store_registers(), and target_store_registers().
enum strata target_ops::to_stratum
Definition at line 470 of file target.h.
Referenced by _initialize_remote_mips(), bsd_kvm_add_target(), bsd_uthread_target(), default_fileio_target(), find_record_target(), gdb_entry_point(), inf_child_target(), init_aix_thread_ops(), init_core_ops(), init_dec_thread_ops(), init_exec_ops(), init_gdbsim_ops(), init_go32_ops(), init_m32r_ops(), init_procfs_ops(), init_ravenscar_thread_ops(), init_record_btrace_ops(), init_record_full_core_ops(), init_record_full_ops(), init_remote_ops(), init_sol_thread_ops(), init_spu_ops(), init_tfile_ops(), init_thread_db_ops(), init_windows_ops(), pop_all_targets_above(), push_target(), record_detach(), record_disconnect(), record_full_open(), record_kill(), record_mourn_inferior(), target_get_osdata(), target_info(), target_info_proc(), target_require_runnable(), unpush_target(), and update_current_target().
int(* target_ops::to_supports_btrace)(void)
Definition at line 812 of file target.h.
Referenced by _initialize_amd64_linux_nat(), _initialize_i386_linux_nat(), init_remote_ops(), and target_supports_btrace().
int(* target_ops::to_supports_disable_randomization)(void)
Definition at line 609 of file target.h.
Referenced by find_default_supports_disable_randomization(), init_extended_remote_ops(), init_remote_ops(), linux_nat_add_target(), and target_supports_disable_randomization().
int(* target_ops::to_supports_enable_disable_tracepoint)(void)
Definition at line 606 of file target.h.
Referenced by init_remote_ops(), and update_current_target().
int(* target_ops::to_supports_evaluation_of_breakpoint_conditions)(void)
Definition at line 616 of file target.h.
Referenced by init_remote_ops(), and update_current_target().
int(* target_ops::to_supports_multi_process)(void)
Definition at line 602 of file target.h.
Referenced by _initialize_darwin_inferior(), init_remote_ops(), linux_nat_add_target(), and update_current_target().
int(* target_ops::to_supports_non_stop)(void)
Definition at line 482 of file target.h.
Referenced by find_default_supports_non_stop(), init_remote_ops(), linux_nat_add_target(), and target_supports_non_stop().
int(* target_ops::to_supports_string_tracing)(void)
Definition at line 612 of file target.h.
Referenced by init_remote_ops(), and update_current_target().
void(* target_ops::to_teardown_btrace)(struct btrace_target_info *tinfo)
Definition at line 825 of file target.h.
Referenced by _initialize_amd64_linux_nat(), _initialize_i386_linux_nat(), init_remote_ops(), and target_teardown_btrace().
void(* target_ops::to_terminal_inferior)(void)
Definition at line 430 of file target.h.
Referenced by inf_child_target(), init_go32_ops(), init_procfs_ops(), init_remote_ops(), init_windows_ops(), linux_nat_add_target(), setup_target_debug(), target_terminal_inferior(), and update_current_target().
void(* target_ops::to_terminal_info)(const char *, int)
Definition at line 434 of file target.h.
Referenced by inf_child_target(), init_go32_ops(), init_procfs_ops(), init_windows_ops(), setup_target_debug(), and update_current_target().
void(* target_ops::to_terminal_init)(void)
Definition at line 429 of file target.h.
Referenced by gnu_target(), inf_child_target(), init_go32_ops(), init_procfs_ops(), init_windows_ops(), setup_target_debug(), and update_current_target().
void(* target_ops::to_terminal_ours)(void)
Definition at line 432 of file target.h.
Referenced by inf_child_target(), init_go32_ops(), init_procfs_ops(), init_remote_ops(), init_windows_ops(), linux_nat_add_target(), quit(), setup_target_debug(), and update_current_target().
void(* target_ops::to_terminal_ours_for_output)(void)
Definition at line 431 of file target.h.
Referenced by inf_child_target(), init_go32_ops(), init_procfs_ops(), init_windows_ops(), setup_target_debug(), and update_current_target().
void(* target_ops::to_terminal_save_ours)(void)
Definition at line 433 of file target.h.
Referenced by inf_child_target(), init_windows_ops(), setup_target_debug(), and update_current_target().
struct address_space*(* target_ops::to_thread_address_space)(struct target_ops *, ptid_t) [read]
Definition at line 638 of file target.h.
Referenced by linux_nat_add_target(), and target_thread_address_space().
int(* target_ops::to_thread_alive)(struct target_ops *, ptid_t ptid)
Definition at line 460 of file target.h.
Referenced by _initialize_darwin_inferior(), _initialize_remote_mips(), aix_thread_thread_alive(), bsd_kvm_add_target(), bsd_uthread_target(), bsd_uthread_thread_alive(), gnu_target(), inf_ptrace_target(), init_aix_thread_ops(), init_core_ops(), init_dec_thread_ops(), init_gdbsim_ops(), init_go32_ops(), init_m32r_ops(), init_procfs_ops(), init_ravenscar_thread_ops(), init_remote_ops(), init_sol_thread_ops(), init_windows_ops(), linux_nat_add_target(), procfs_target(), sol_thread_alive(), and target_thread_alive().
struct gdbarch*(* target_ops::to_thread_architecture)(struct target_ops *, ptid_t) [read]
Definition at line 632 of file target.h.
Referenced by init_spu_ops(), setup_target_debug(), and update_current_target().
char*(* target_ops::to_thread_name)(struct thread_info *)
Definition at line 464 of file target.h.
Referenced by linux_nat_add_target(), target_thread_name(), and update_current_target().
int(* target_ops::to_trace_find)(enum trace_find_type type, int num, CORE_ADDR addr1, CORE_ADDR addr2, int *tpp)
Definition at line 721 of file target.h.
Referenced by init_remote_ops(), init_tfile_ops(), and update_current_target().
void(* target_ops::to_trace_init)(void)
Definition at line 681 of file target.h.
Referenced by init_remote_ops(), and update_current_target().
void(* target_ops::to_trace_set_readonly_regions)(void)
Definition at line 702 of file target.h.
Referenced by init_remote_ops(), and update_current_target().
void(* target_ops::to_trace_start)(void)
Definition at line 705 of file target.h.
Referenced by init_remote_ops(), and update_current_target().
void(* target_ops::to_trace_stop)(void)
Definition at line 714 of file target.h.
Referenced by init_remote_ops(), and update_current_target().
struct traceframe_info*(* target_ops::to_traceframe_info)(void) [read]
Definition at line 802 of file target.h.
Referenced by init_remote_ops(), init_tfile_ops(), and update_current_target().
int(* target_ops::to_upload_trace_state_variables)(struct uploaded_tsv **utsvp)
Definition at line 733 of file target.h.
Referenced by init_remote_ops(), and update_current_target().
int(* target_ops::to_upload_tracepoints)(struct uploaded_tp **utpp)
Definition at line 731 of file target.h.
Referenced by init_remote_ops(), and update_current_target().
int(* target_ops::to_use_agent)(int use)
Definition at line 806 of file target.h.
Referenced by inf_child_target(), init_remote_ops(), and update_current_target().
int(* target_ops::to_verify_memory)(struct target_ops *, const gdb_byte *data, CORE_ADDR memaddr, ULONGEST size)
Definition at line 769 of file target.h.
Referenced by init_remote_ops(), and target_verify_memory().
ptid_t(* target_ops::to_wait)(struct target_ops *, ptid_t, struct target_waitstatus *, int)
Definition at line 365 of file target.h.
Referenced by _initialize_darwin_inferior(), _initialize_ia64_hpux_nat(), _initialize_remote_mips(), _initialize_rs6000_nat(), _initialize_spu_nat(), aix_thread_wait(), bsd_uthread_target(), bsd_uthread_wait(), dec_thread_wait(), gnu_target(), inf_ptrace_target(), init_aix_thread_ops(), init_dec_thread_ops(), init_gdbsim_ops(), init_go32_ops(), init_m32r_ops(), init_procfs_ops(), init_ravenscar_thread_ops(), init_record_full_core_ops(), init_record_full_ops(), init_remote_ops(), init_sol_thread_ops(), init_thread_db_ops(), init_windows_ops(), linux_nat_add_target(), procfs_target(), ravenscar_wait(), record_full_open(), sol_thread_wait(), target_wait(), and thread_db_wait().
int(* target_ops::to_watchpoint_addr_within_range)(struct target_ops *, CORE_ADDR, CORE_ADDR, int)
Definition at line 418 of file target.h.
Referenced by _initialize_aarch64_linux_nat(), _initialize_arm_linux_nat(), _initialize_ppc_linux_nat(), init_remote_ops(), setup_target_debug(), and update_current_target().
void(* target_ops::to_xclose)(struct target_ops *targ)
Definition at line 358 of file target.h.
Referenced by target_bfd_reopen(), and target_close().
LONGEST(* target_ops::to_xfer_partial)(struct target_ops *ops, enum target_object object, const char *annex, gdb_byte *readbuf, const gdb_byte *writebuf, ULONGEST offset, LONGEST len)
Definition at line 529 of file target.h.
Referenced by _initialize_darwin_inferior(), _initialize_ia64_hpux_nat(), _initialize_ia64_linux_nat(), _initialize_rs6000_nat(), _initialize_spu_nat(), aix_thread_xfer_partial(), bsd_kvm_add_target(), bsd_uthread_target(), bsd_uthread_xfer_partial(), complete_target_initialization(), core_xfer_partial(), current_xfer_partial(), default_xfer_partial(), gnu_target(), inf_ptrace_target(), init_aix_thread_ops(), init_core_ops(), init_exec_ops(), init_gdbsim_ops(), init_record_full_core_ops(), init_record_full_ops(), init_remote_ops(), init_sol_thread_ops(), init_spu_ops(), init_tfile_ops(), init_windows_ops(), linux_nat_add_target(), linux_nat_xfer_partial(), linux_target_install_ops(), memory_xfer_partial_1(), procfs_target(), procfs_xfer_partial(), record_full_open(), sol_thread_xfer_partial(), sparc_target(), spu_xfer_partial(), target_bfd_reopen(), target_xfer_partial(), update_current_target(), and windows_xfer_partial().
The documentation for this struct was generated from the following file:
/home/stan/gdb/src/gdb/target.h