GDB (xrefs): breakpoint_ops Struct Reference
breakpoint_ops Struct Reference
#include "breakpoint.h"
Public Attributes
void(* dtor)(struct breakpoint *self)
struct bp_location *(* allocate_location)(struct breakpoint *)
void(* re_set)(struct breakpoint *self)
int(* insert_location)(struct bp_location *)
int(* remove_location)(struct bp_location *)
int(* breakpoint_hit)(const struct bp_location *bl, struct address_space *aspace, CORE_ADDR bp_addr, const struct target_waitstatus *ws)
void(* check_status)(struct bpstats *bs)
int(* resources_needed)(const struct bp_location *)
int(* works_in_software_mode)(const struct breakpoint *)
enum print_stop_action(* print_it)(struct bpstats *bs)
void(* print_one)(struct breakpoint *, struct bp_location **)
void(* print_one_detail)(const struct breakpoint *, struct ui_out *)
void(* print_mention)(struct breakpoint *)
void(* print_recreate)(struct breakpoint *, struct ui_file *fp)
void(* create_sals_from_address)(char **, struct linespec_result *, enum bptype, char *, char **)
void(* create_breakpoints_sal)(struct gdbarch *, struct linespec_result *, char *, char *, enum bptype, enum bpdisp, int, int, int, const struct breakpoint_ops *, int, int, int, unsigned)
void(* decode_linespec)(struct breakpoint *, char **, struct symtabs_and_lines *)
enum bpstat_signal_value(* explains_signal)(struct breakpoint *, enum gdb_signal)
void(* after_condition_true)(struct bpstats *bs)
Detailed Description
Definition at line 493 of file breakpoint.h.
Member Data Documentation
void(* breakpoint_ops::after_condition_true)(struct bpstats *bs)
Definition at line 612 of file breakpoint.h.
Referenced by bpstat_stop_status(), and initialize_breakpoint_ops().
struct bp_location*(* breakpoint_ops::allocate_location)(struct breakpoint *) [read]
Definition at line 500 of file breakpoint.h.
Referenced by allocate_bp_location(), and initialize_ada_catchpoint_ops().
int(* breakpoint_ops::breakpoint_hit)(const struct bp_location *bl, struct address_space *aspace, CORE_ADDR bp_addr, const struct target_waitstatus *ws)
Definition at line 524 of file breakpoint.h.
Referenced by bpstat_check_location(), initialize_breakpoint_ops(), and initialize_signal_catchpoint_ops().
void(* breakpoint_ops::check_status)(struct bpstats *bs)
Definition at line 531 of file breakpoint.h.
Referenced by bpstat_stop_status(), check_status_exception_catchpoint(), initialize_ada_catchpoint_ops(), initialize_breakpoint_ops(), and initialize_throw_catchpoint_ops().
void(* breakpoint_ops::create_breakpoints_sal)(struct gdbarch *, struct linespec_result *, char *, char *, enum bptype, enum bpdisp, int, int, int, const struct breakpoint_ops *, int, int, int, unsigned)
Definition at line 588 of file breakpoint.h.
Referenced by create_breakpoint(), and initialize_breakpoint_ops().
void(* breakpoint_ops::create_sals_from_address)(char **, struct linespec_result *, enum bptype, char *, char **)
Definition at line 578 of file breakpoint.h.
Referenced by create_breakpoint(), and initialize_breakpoint_ops().
void(* breakpoint_ops::decode_linespec)(struct breakpoint *, char **, struct symtabs_and_lines *)
Definition at line 600 of file breakpoint.h.
Referenced by initialize_breakpoint_ops().
void(* breakpoint_ops::dtor)(struct breakpoint *self)
Definition at line 497 of file breakpoint.h.
Referenced by delete_breakpoint(), dtor_catch_exec(), dtor_catch_solib(), dtor_catch_syscall(), dtor_exception(), dtor_exception_catchpoint(), dtor_watchpoint(), initialize_ada_catchpoint_ops(), initialize_breakpoint_ops(), initialize_signal_catchpoint_ops(), initialize_throw_catchpoint_ops(), longjmp_bkpt_dtor(), and signal_catchpoint_dtor().
enum bpstat_signal_value(* breakpoint_ops::explains_signal)(struct breakpoint *, enum gdb_signal)
Definition at line 607 of file breakpoint.h.
Referenced by bpstat_explains_signal(), initialize_breakpoint_ops(), and initialize_signal_catchpoint_ops().
int(* breakpoint_ops::insert_location)(struct bp_location *)
Definition at line 510 of file breakpoint.h.
Referenced by initialize_breakpoint_ops(), initialize_signal_catchpoint_ops(), and insert_bp_location().
enum print_stop_action(* breakpoint_ops::print_it)(struct bpstats *bs)
Definition at line 545 of file breakpoint.h.
Referenced by initialize_ada_catchpoint_ops(), initialize_breakpoint_ops(), initialize_signal_catchpoint_ops(), initialize_throw_catchpoint_ops(), and print_bp_stop_message().
void(* breakpoint_ops::print_mention)(struct breakpoint *)
Definition at line 567 of file breakpoint.h.
Referenced by initialize_ada_catchpoint_ops(), initialize_breakpoint_ops(), initialize_signal_catchpoint_ops(), initialize_throw_catchpoint_ops(), and mention().
void(* breakpoint_ops::print_one)(struct breakpoint *, struct bp_location **)
Definition at line 549 of file breakpoint.h.
Referenced by initialize_ada_catchpoint_ops(), initialize_breakpoint_ops(), initialize_signal_catchpoint_ops(), initialize_throw_catchpoint_ops(), print_one_breakpoint(), and print_one_breakpoint_location().
void(* breakpoint_ops::print_one_detail)(const struct breakpoint *, struct ui_out *)
Definition at line 563 of file breakpoint.h.
Referenced by initialize_breakpoint_ops(), initialize_throw_catchpoint_ops(), and print_one_breakpoint_location().
void(* breakpoint_ops::print_recreate)(struct breakpoint *, struct ui_file *fp)
Definition at line 570 of file breakpoint.h.
Referenced by initialize_ada_catchpoint_ops(), initialize_breakpoint_ops(), initialize_signal_catchpoint_ops(), initialize_throw_catchpoint_ops(), and save_breakpoints().
void(* breakpoint_ops::re_set)(struct breakpoint *self)
Definition at line 505 of file breakpoint.h.
Referenced by breakpoint_re_set_one(), initialize_ada_catchpoint_ops(), initialize_breakpoint_ops(), initialize_throw_catchpoint_ops(), and re_set_exception().
int(* breakpoint_ops::remove_location)(struct bp_location *)
Definition at line 516 of file breakpoint.h.
Referenced by initialize_breakpoint_ops(), initialize_signal_catchpoint_ops(), and remove_breakpoint_1().
int(* breakpoint_ops::resources_needed)(const struct bp_location *)
Definition at line 536 of file breakpoint.h.
Referenced by hw_breakpoint_used_count(), hw_watchpoint_use_count(), and initialize_breakpoint_ops().
int(* breakpoint_ops::works_in_software_mode)(const struct breakpoint *)
Definition at line 541 of file breakpoint.h.
Referenced by initialize_breakpoint_ops(), and update_watchpoint().
The documentation for this struct was generated from the following file:
/home/stan/gdb/src/gdb/breakpoint.h