GDB (xrefs): trace_file_write_ops Struct Reference
trace_file_write_ops Struct Reference
#include "tracepoint.h"
Public Attributes
void(* dtor)(struct trace_file_writer *self)
int(* target_save)(struct trace_file_writer *self, const char *name)
void(* start)(struct trace_file_writer *self, const char *name)
void(* write_header)(struct trace_file_writer *self)
void(* write_regblock_type)(struct trace_file_writer *self, int size)
void(* write_status)(struct trace_file_writer *self, struct trace_status *ts)
void(* write_uploaded_tsv)(struct trace_file_writer *self, struct uploaded_tsv *tsv)
void(* write_uploaded_tp)(struct trace_file_writer *self, struct uploaded_tp *tp)
void(* write_definition_end)(struct trace_file_writer *self)
void(* write_trace_buffer)(struct trace_file_writer *self, gdb_byte *buf, LONGEST len)
struct trace_frame_write_ops * frame_ops
void(* end)(struct trace_file_writer *self)
Detailed Description
Definition at line 266 of file tracepoint.h.
Member Data Documentation
void(* trace_file_write_ops::dtor)(struct trace_file_writer *self)
Definition at line 270 of file tracepoint.h.
Referenced by trace_file_writer_xfree().
void(* trace_file_write_ops::end)(struct trace_file_writer *self)
Definition at line 316 of file tracepoint.h.
Referenced by trace_save().
struct trace_frame_write_ops* trace_file_write_ops::frame_ops
Definition at line 313 of file tracepoint.h.
Referenced by trace_save().
void(* trace_file_write_ops::start)(struct trace_file_writer *self, const char *name)
Definition at line 279 of file tracepoint.h.
Referenced by trace_save().
int(* trace_file_write_ops::target_save)(struct trace_file_writer *self, const char *name)
Definition at line 275 of file tracepoint.h.
Referenced by trace_save().
void(* trace_file_write_ops::write_definition_end)(struct trace_file_writer *self)
Definition at line 303 of file tracepoint.h.
Referenced by trace_save().
void(* trace_file_write_ops::write_header)(struct trace_file_writer *self)
Definition at line 283 of file tracepoint.h.
Referenced by trace_save().
void(* trace_file_write_ops::write_regblock_type)(struct trace_file_writer *self, int size)
Definition at line 287 of file tracepoint.h.
Referenced by trace_save().
void(* trace_file_write_ops::write_status)(struct trace_file_writer *self, struct trace_status *ts)
Definition at line 291 of file tracepoint.h.
Referenced by trace_save().
void(* trace_file_write_ops::write_trace_buffer)(struct trace_file_writer *self, gdb_byte *buf, LONGEST len)
Definition at line 307 of file tracepoint.h.
Referenced by trace_save().
void(* trace_file_write_ops::write_uploaded_tp)(struct trace_file_writer *self, struct uploaded_tp *tp)
Definition at line 299 of file tracepoint.h.
Referenced by trace_save().
void(* trace_file_write_ops::write_uploaded_tsv)(struct trace_file_writer *self, struct uploaded_tsv *tsv)
Definition at line 295 of file tracepoint.h.
Referenced by trace_save().
The documentation for this struct was generated from the following file:
/home/stan/gdb/src/gdb/tracepoint.h