GDB (xrefs): /home/stan/gdb/src/gdb/symfile.h File Reference
/home/stan/gdb/src/gdb/symfile.h File Reference
#include "symtab.h"
#include "probe.h"
Classes
struct psymbol_allocation_list
struct section_addr_info
struct section_addr_info::other_sections
struct symfile_segment_data
struct quick_symbol_functions
struct sym_probe_fns
struct sym_fns
struct dwarf2_section_names
struct dwarf2_debug_sections
Typedefs
typedef int(symbol_compare_ftype)(const char *string1, const char *string2)
typedef void(symbol_filename_ftype)(const char *filename, const char *fullname, void *data)
Enumerations
enum symfile_add_flags { SYMFILE_VERBOSE = 1 << 1, SYMFILE_MAINLINE = 1 << 2, SYMFILE_DEFER_BP_RESET = 1 << 3, SYMFILE_NO_READ = 1 << 4 }
enum overlay_debugging_state { ovly_off, ovly_on, ovly_auto }
enum dwarf2_section_enum { DWARF2_DEBUG_FRAME, DWARF2_EH_FRAME }
Functions
struct section_addr_info * build_section_addr_info_from_objfile (const struct objfile *objfile)
void relative_addr_info_to_section_offsets (struct section_offsets *section_offsets, int num_sections, const struct section_addr_info *addrs)
void addr_info_make_relative (struct section_addr_info *addrs, bfd *abfd)
void default_symfile_offsets (struct objfile *objfile, const struct section_addr_info *)
struct symfile_segment_data * default_symfile_segments (bfd *abfd)
bfd_byte * default_symfile_relocate (struct objfile *objfile, asection *sectp, bfd_byte *buf)
struct symtab * allocate_symtab (const char *, struct objfile *) ATTRIBUTE_NONNULL(1)
void add_symtab_fns (enum bfd_flavour flavour, const struct sym_fns *)
void new_symfile_objfile (struct objfile *, int)
struct objfile * symbol_file_add (const char *, int, struct section_addr_info *, int)
struct objfile * symbol_file_add_from_bfd (bfd *, const char *, int, struct section_addr_info *, int, struct objfile *parent)
void symbol_file_add_separate (bfd *, const char *, int, struct objfile *)
char * find_separate_debug_file_by_debuglink (struct objfile *)
struct section_addr_info * alloc_section_addr_info (size_t num_sections)
struct section_addr_info * build_section_addr_info_from_section_table (const struct target_section *start, const struct target_section *end)
void free_section_addr_info (struct section_addr_info *)
void set_initial_language (void)
void find_lowest_section (bfd *, asection *, void *)
bfd * symfile_bfd_open (const char *)
bfd * gdb_bfd_open_maybe_remote (const char *)
int get_section_index (struct objfile *, char *)
struct obj_section * find_pc_mapped_section (CORE_ADDR)
struct obj_section * find_pc_overlay (CORE_ADDR)
int section_is_overlay (struct obj_section *)
int section_is_mapped (struct obj_section *)
CORE_ADDR pc_in_mapped_range (CORE_ADDR, struct obj_section *)
CORE_ADDR pc_in_unmapped_range (CORE_ADDR, struct obj_section *)
CORE_ADDR overlay_mapped_address (CORE_ADDR, struct obj_section *)
CORE_ADDR overlay_unmapped_address (CORE_ADDR, struct obj_section *)
CORE_ADDR symbol_overlayed_address (CORE_ADDR, struct obj_section *)
void symbol_file_add_main (const char *args, int from_tty)
void symbol_file_clear (int from_tty)
void simple_overlay_update (struct obj_section *)
bfd_byte * symfile_relocate_debug_section (struct objfile *, asection *, bfd_byte *)
int symfile_map_offsets_to_segments (bfd *, const struct symfile_segment_data *, struct section_offsets *, int, const CORE_ADDR *)
struct symfile_segment_data * get_symfile_segment_data (bfd *abfd)
void free_symfile_segment_data (struct symfile_segment_data *data)
struct cleanup * increment_reading_symtab (void)
int dwarf2_has_info (struct objfile *, const struct dwarf2_debug_sections *)
void dwarf2_get_section_info (struct objfile *, enum dwarf2_section_enum, asection **, const gdb_byte **, bfd_size_type *)
int dwarf2_initialize_objfile (struct objfile *)
void dwarf2_build_psymtabs (struct objfile *)
void dwarf2_build_frame_info (struct objfile *)
void dwarf2_free_objfile (struct objfile *)
void mdebug_build_psymtabs (struct objfile *, const struct ecoff_debug_swap *, struct ecoff_debug_info *)
void elfmdebug_build_psymtabs (struct objfile *, const struct ecoff_debug_swap *, asection *)
bfd * find_separate_debug_file_in_section (struct objfile *)
Variables
int auto_solib_add
enum overlay_debugging_state overlay_debugging
int overlay_cache_invalid
Typedef Documentation
typedef int(symbol_compare_ftype)(const char *string1, const char *string2)
Definition at line 41 of file symfile.h.
typedef void(symbol_filename_ftype)(const char *filename, const char *fullname, void *data)
Definition at line 125 of file symfile.h.
Enumeration Type Documentation
enum dwarf2_section_enum
Enumerator:
DWARF2_DEBUG_FRAME
DWARF2_EH_FRAME
Definition at line 636 of file symfile.h.
enum overlay_debugging_state
Enumerator:
ovly_off
ovly_on
ovly_auto
Definition at line 534 of file symfile.h.
enum symfile_add_flags
Enumerator:
SYMFILE_VERBOSE
SYMFILE_MAINLINE
SYMFILE_DEFER_BP_RESET
SYMFILE_NO_READ
Definition at line 456 of file symfile.h.
Function Documentation
void add_symtab_fns (enum bfd_flavour flavour, const struct sym_fns *)
Definition at line 1764 of file symfile.c.
References VEC_safe_push.
Referenced by _initialize_machoread(), _initialize_somread(), and _initialize_xcoffread().
void addr_info_make_relative (struct section_addr_info * addrs, bfd * abfd)
Definition at line 536 of file symfile.c.
References _, section_addr_info::other_sections::addr, addr_section_name(), addrs_section_sort(), build_section_addr_info_from_bfd(), do_cleanups(), find_lowest_section(), gdb_assert, make_cleanup(), make_cleanup_free_section_addr_info(), section_addr_info::other_sections::name, section_addr_info::num_sections, section_addr_info::other, section_addr_info::other_sections::sectindex, warning(), xfree(), and xzalloc().
Referenced by objfile_relocate(), and syms_from_objfile_1().
struct section_addr_info* alloc_section_addr_info (size_t num_sections) [read]
Definition at line 212 of file symfile.c.
References memset(), size, and xmalloc().
Referenced by add_symbol_file_command(), build_section_addr_info_from_bfd(), build_section_addr_info_from_section_table(), jit_bfd_try_read_symtab(), symbol_file_add_from_memory(), and syms_from_objfile_1().
struct symtab* allocate_symtab (const char * , struct objfile *) [read]
Definition at line 2795 of file symfile.c.
References symtab::debugformat, deduce_language_from_filename(), symtab::filename, objfile_per_bfd_storage::filename_cache, fprintf_unfiltered(), symtab::fullname, gdb_stdlog, host_address_to_string(), symtab::language, memset(), symtab::next, symtab::objfile, objfile_name(), objfile::objfile_obstack, objfile::per_bfd, symtab_create_debug, objfile::symtabs, and xfree().
Referenced by dwarf_decode_lines(), end_symtab_from_static_block(), finalize_symtab(), get_java_class_symtab(), new_symtab(), and setup_type_unit_groups().
struct section_addr_info* build_section_addr_info_from_objfile (const struct objfile * objfile) [read]
Definition at line 285 of file symfile.c.
References section_addr_info::other_sections::addr, build_section_addr_info_from_bfd(), section_addr_info::num_sections, objfile::obfd, section_offsets::offsets, section_addr_info::other, section_addr_info::other_sections::sectindex, and objfile::section_offsets.
Referenced by objfile_relocate(), and symbol_file_add_separate().
struct section_addr_info* build_section_addr_info_from_section_table (const struct target_section * start, const struct target_section * end) [read]
Definition at line 229 of file symfile.c.
References section_addr_info::other_sections::addr, target_section::addr, alloc_section_addr_info(), gdb_bfd_section_index(), section_addr_info::other_sections::name, section_addr_info::num_sections, section_addr_info::other, section_addr_info::other_sections::sectindex, and target_section::the_bfd_section.
Referenced by solib_read_symbols().
void default_symfile_offsets (struct objfile * objfile, const struct section_addr_info *)
Definition at line 685 of file symfile.c.
References exec_set_section_address(), gdb_bfd_count_sections(), init_objfile_sect_indices(), place_section_arg::lowest, objfile::num_sections, objfile::obfd, objfile::objfile_obstack, place_section_arg::offsets, section_offsets::offsets, place_section(), relative_addr_info_to_section_offsets(), objfile::section_offsets, and SIZEOF_N_SECTION_OFFSETS.
Referenced by xcoff_symfile_offsets().
bfd_byte* default_symfile_relocate (struct objfile * objfile, asection * sectp, bfd_byte * buf)
Definition at line 3584 of file symfile.c.
References symfile_dummy_outputs().
struct symfile_segment_data* default_symfile_segments (bfd * abfd) [read]
Definition at line 775 of file symfile.c.
References symfile_segment_data::num_segments, symfile_segment_data::segment_bases, symfile_segment_data::segment_info, symfile_segment_data::segment_sizes, XCALLOC, and XZALLOC.
void dwarf2_build_frame_info (struct objfile *)
Definition at line 2248 of file dwarf2-frame.c.
References _, comp_unit::abfd, dwarf2_fde::address_range, comp_unit::dbase, decode_frame_entry(), DWARF2_DEBUG_FRAME, DWARF2_EH_FRAME, dwarf2_get_section_info(), comp_unit::dwarf_frame_buffer, comp_unit::dwarf_frame_section, comp_unit::dwarf_frame_size, EH_CIE_OR_FDE_TYPE_ID, dwarf2_cie_table::entries, dwarf2_fde_table::entries, dwarf2_fde::initial_location, gdb_exception::message, dwarf2_cie_table::num_entries, dwarf2_fde_table::num_entries, objfile::obfd, comp_unit::objfile, objfile_name(), objfile::objfile_obstack, qsort, qsort_fde_cmp(), gdb_exception::reason, RETURN_MASK_ERROR, objfile::separate_debug_objfile_backlink, comp_unit::tbase, TRY_CATCH, warning(), xfree(), and xrealloc().
Referenced by coff_symfile_read(), dwarf2_frame_find_fde(), macho_symfile_read(), and xcoff_initial_scan().
void dwarf2_build_psymtabs (struct objfile *)
Definition at line 4112 of file dwarf2read.c.
References discard_cleanups(), dwarf2_build_psymtabs_hard(), exception_print(), gdb_stderr, objfile::global_psymbols, init_psymbol_list(), make_cleanup_discard_psymtabs(), gdb_exception::reason, RETURN_MASK_ERROR, psymbol_allocation_list::size, objfile::static_psymbols, and TRY_CATCH.
Referenced by coff_symfile_read(), macho_symfile_read(), read_psyms(), and xcoff_initial_scan().
void dwarf2_free_objfile (struct objfile *)
Definition at line 21107 of file dwarf2read.c.
References dwarf2_objfile_data_key, free_cached_comp_units(), and dwarf2_per_objfile::quick_file_names_table.
Referenced by coff_symfile_finish(), elf_symfile_finish(), and xcoff_symfile_finish().
void dwarf2_get_section_info (struct objfile * , enum dwarf2_section_enum, asection ** , const gdb_byte ** , bfd_size_type *)
Definition at line 2278 of file dwarf2read.c.
References dwarf2_section_info::buffer, DWARF2_DEBUG_FRAME, DWARF2_EH_FRAME, dwarf2_objfile_data_key, dwarf2_read_section(), dwarf2_per_objfile::eh_frame, dwarf2_per_objfile::frame, gdb_assert_not_reached, get_section_bfd_section(), and dwarf2_section_info::size.
Referenced by dwarf2_build_frame_info().
int dwarf2_has_info (struct objfile * , const struct dwarf2_debug_sections *)
Definition at line 1948 of file dwarf2read.c.
References dwarf2_per_objfile::abbrev, dwarf2_section_info::asection, dwarf2_locate_sections(), dwarf2_objfile_data_key, dwarf2_per_objfile::info, dwarf2_section_info::is_virtual, memset(), objfile::obfd, objfile::objfile_obstack, and dwarf2_section_info::s.
Referenced by coff_symfile_read(), elf_symfile_read(), macho_symfile_read(), read_psyms(), and xcoff_initial_scan().
int dwarf2_initialize_objfile (struct objfile *)
Definition at line 4070 of file dwarf2read.c.
References create_all_comp_units(), create_all_type_units(), create_quick_file_names_table(), dw2_get_cu(), dwarf2_read_index(), objfile::flags, OBJF_READNOW, objfile::objfile_obstack, OBSTACK_ZALLOC, dwarf2_per_cu_data::quick, dwarf2_per_objfile::quick_file_names_table, dwarf2_per_objfile::using_index, and dwarf2_per_cu_data::v.
Referenced by elf_symfile_read().
void elfmdebug_build_psymtabs (struct objfile * , const struct ecoff_debug_swap * , asection *)
Definition at line 4889 of file mdebugread.c.
References _, do_cleanups(), error(), init_minimal_symbol_collection(), install_minimal_symbols(), make_cleanup_discard_minimal_symbols(), mdebug_build_psymtabs(), objfile::obfd, and objfile::objfile_obstack.
Referenced by elf_symfile_read().
void find_lowest_section (bfd * , asection * , void *)
Definition at line 191 of file symfile.c.
Referenced by addr_info_make_relative().
struct obj_section* find_pc_mapped_section (CORE_ADDR) [read]
Definition at line 3158 of file symfile.c.
References ALL_OBJSECTIONS, overlay_debugging, pc_in_mapped_range(), and section_is_mapped().
Referenced by backtrace_command_1(), block_for_pc(), blockvector_for_pc(), find_pc_function(), find_pc_section(), find_pc_symtab(), and gdbpy_block_for_pc().
struct obj_section* find_pc_overlay (CORE_ADDR) [read]
Definition at line 3131 of file symfile.c.
References ALL_OBJSECTIONS, overlay_debugging, pc_in_mapped_range(), pc_in_unmapped_range(), section_is_mapped(), and section_is_overlay().
Referenced by arm_linux_copy_svc(), build_address_symbolic(), call_function_by_hand(), convert_linespec_to_sals(), create_internal_breakpoint(), elf_gnu_ifunc_resolver_stop(), find_pc_line(), find_pc_partial_function_gnu_ifunc(), handle_inferior_event(), handle_step_into_function(), insert_hp_step_resume_breakpoint_at_frame(), insert_step_resume_breakpoint_at_caller(), memory_xfer_partial_1(), parse_probes(), and set_momentary_breakpoint_at_pc().
char* find_separate_debug_file_by_debuglink (struct objfile *)
Definition at line 1500 of file symfile.c.
References do_cleanups(), find_separate_debug_file(), make_cleanup(), objfile::obfd, objfile_name(), terminate_after_last_dir_separator(), and xfree().
Referenced by coff_symfile_read(), and elf_symfile_read().
bfd* find_separate_debug_file_in_section (struct objfile *)
Definition at line 259 of file minidebug.c.
References _, gdb_bfd_openr_iovec(), gdb_bfd_unref(), gnutarget, objfile::obfd, objfile_name(), and warning().
Referenced by read_symbols().
void free_section_addr_info (struct section_addr_info *)
Definition at line 306 of file symfile.c.
References section_addr_info::other_sections::name, section_addr_info::num_sections, section_addr_info::other, and xfree().
Referenced by do_free_section_addr_info(), and solib_read_symbols().
void free_symfile_segment_data (struct symfile_segment_data * data)
Definition at line 3638 of file symfile.c.
References symfile_segment_data::segment_bases, symfile_segment_data::segment_info, symfile_segment_data::segment_sizes, and xfree().
Referenced by get_offsets(), solib_target_relocate_section_addresses(), and symfile_find_segment_sections().
bfd* gdb_bfd_open_maybe_remote (const char *)
Definition at line 1658 of file symfile.c.
References gdb_bfd_open(), gnutarget, remote_bfd_open(), and remote_filename_p().
Referenced by build_id_to_debug_bfd(), reread_symbols(), separate_debug_file_exists(), and windows_xfer_shared_library().
int get_section_index (struct objfile * , char *)
Definition at line 1747 of file symfile.c.
References objfile::obfd.
Referenced by parse_partial_symbols(), and record_minimal_symbol().
struct symfile_segment_data* get_symfile_segment_data (bfd * abfd) [read]
Definition at line 3627 of file symfile.c.
References find_sym_fns(), and sym_fns::sym_segments.
Referenced by get_offsets(), solib_target_relocate_section_addresses(), and symfile_find_segment_sections().
struct cleanup* increment_reading_symtab (void) [read]
Definition at line 174 of file symfile.c.
References currently_reading_symtab, decrement_reading_symtab(), gdb_assert, and make_cleanup().
Referenced by dw2_instantiate_symtab(), and psymtab_to_symtab().
void mdebug_build_psymtabs (struct objfile * , const struct ecoff_debug_swap * , struct ecoff_debug_info *)
Definition at line 341 of file mdebugread.c.
References _, buildsym_new_init(), compare_glevel, cur_bfd, debug_info, debug_swap, free_header_files(), gdb_flush(), gdb_stdout, init_header_files(), max_gdbinfo, max_glevel, objfile::obfd, objfile::objfile_obstack, parse_partial_symbols(), printf_unfiltered(), and stabsread_new_init().
Referenced by elfmdebug_build_psymtabs(), and mipscoff_symfile_read().
void new_symfile_objfile (struct objfile * , int)
Definition at line 1038 of file symfile.c.
References breakpoint_re_set(), clear_complaints(), clear_symtab_users(), symfile_complaints, SYMFILE_DEFER_BP_RESET, SYMFILE_MAINLINE, symfile_objfile, and SYMFILE_VERBOSE.
Referenced by symbol_file_add_with_addrs().
CORE_ADDR overlay_mapped_address (CORE_ADDR , struct obj_section *)
Definition at line 3082 of file symfile.c.
References objfile::obfd, obj_section::objfile, pc_in_unmapped_range(), section_is_overlay(), and obj_section::the_bfd_section.
Referenced by build_address_symbolic(), find_pc_line(), find_pc_partial_function_gnu_ifunc(), memory_xfer_partial_1(), skip_prologue_sal(), and sym_info().
CORE_ADDR overlay_unmapped_address (CORE_ADDR , struct obj_section *)
Definition at line 3063 of file symfile.c.
References objfile::obfd, obj_section::objfile, pc_in_mapped_range(), section_is_overlay(), and obj_section::the_bfd_section.
Referenced by address_info(), find_pc_partial_function_gnu_ifunc(), insert_bp_location(), skip_prologue_sal(), and symbol_overlayed_address().
CORE_ADDR pc_in_mapped_range (CORE_ADDR , struct obj_section *)
Definition at line 3032 of file symfile.c.
References obj_section_addr, obj_section_endaddr, and section_is_overlay().
Referenced by find_pc_mapped_section(), find_pc_overlay(), and overlay_unmapped_address().
CORE_ADDR pc_in_unmapped_range (CORE_ADDR , struct obj_section *)
Definition at line 3009 of file symfile.c.
References objfile::obfd, obj_section_offset, obj_section::objfile, offset, section_is_overlay(), size, and obj_section::the_bfd_section.
Referenced by build_address_symbolic(), find_pc_line(), find_pc_overlay(), find_pc_partial_function_gnu_ifunc(), memory_xfer_partial_1(), overlay_mapped_address(), and sym_info().
void relative_addr_info_to_section_offsets (struct section_offsets * section_offsets, int num_sections, const struct section_addr_info * addrs)
Definition at line 453 of file symfile.c.
References memset(), section_addr_info::num_sections, section_offsets::offsets, section_addr_info::other, and SIZEOF_N_SECTION_OFFSETS.
Referenced by default_symfile_offsets(), and objfile_relocate().
int section_is_mapped (struct obj_section *)
Definition at line 2973 of file symfile.c.
References gdbarch_overlay_update(), gdbarch_overlay_update_p(), get_objfile_arch(), obj_section::objfile, overlay_cache_invalid, overlay_debugging, overlay_invalidate_all(), ovly_auto, obj_section::ovly_mapped, ovly_off, ovly_on, and section_is_overlay().
Referenced by bkpt_breakpoint_hit(), breakpoint_here_p(), breakpoint_thread_match(), find_pc_mapped_section(), find_pc_overlay(), insert_bp_location(), jump_command(), list_overlays_command(), regular_breakpoint_inserted_here_p(), remove_breakpoint_1(), skip_prologue_sal(), software_breakpoint_inserted_here_p(), sym_info(), and symbol_overlayed_address().
int section_is_overlay (struct obj_section *)
Definition at line 2933 of file symfile.c.
References objfile::obfd, obj_section::objfile, overlay_debugging, and obj_section::the_bfd_section.
Referenced by address_info(), bkpt_breakpoint_hit(), breakpoint_here_p(), breakpoint_thread_match(), clear_command(), find_pc_overlay(), insert_bp_location(), jump_command(), map_overlay_command(), overlay_invalidate_all(), overlay_mapped_address(), overlay_unmapped_address(), pc_in_mapped_range(), pc_in_unmapped_range(), regular_breakpoint_inserted_here_p(), remove_breakpoint_1(), section_is_mapped(), simple_overlay_update(), skip_prologue_sal(), software_breakpoint_inserted_here_p(), spu_overlay_update(), sym_info(), and symbol_overlayed_address().
void set_initial_language (void)
Definition at line 1628 of file symfile.c.
References current_language, expected_language, language_c, language_of_main, language_unknown, lookup_symbol(), main_name(), name, set_language(), SYMBOL_LANGUAGE, and VAR_DOMAIN.
Referenced by follow_exec(), set_language_command(), and symbol_file_add_main_1().
void simple_overlay_update (struct obj_section *)
Definition at line 3515 of file symfile.c.
References _, ALL_OBJSECTIONS, cache_novlys, cache_ovly_table, cache_ovly_table_base, error(), LMA, lookup_minimal_symbol(), MAPPED, objfile::obfd, obj_section::objfile, obj_section::ovly_mapped, section_is_overlay(), simple_overlay_update_1(), simple_read_overlay_table(), size, SYMBOL_VALUE_ADDRESS, obj_section::the_bfd_section, and VMA.
Referenced by m32r_gdbarch_init(), and moxie_gdbarch_init().
struct objfile* symbol_file_add (const char * , int , struct section_addr_info * , int) [read]
Definition at line 1223 of file symfile.c.
References do_cleanups(), make_cleanup_bfd_unref(), symbol_file_add_from_bfd(), and symfile_bfd_open().
Referenced by add_symbol_file_command(), follow_exec(), safe_symbol_file_add_stub(), and symbol_file_add_main_1().
struct objfile* symbol_file_add_from_bfd (bfd * , const char * , int , struct section_addr_info * , int , struct objfile * parent) [read]
Definition at line 1211 of file symfile.c.
References symbol_file_add_with_addrs().
Referenced by jit_bfd_try_read_symtab(), macho_add_oso_symfile(), solib_read_symbols(), spu_symbol_file_add_from_memory(), symbol_file_add(), and symbol_file_add_from_memory().
void symbol_file_add_main (const char * args, int from_tty)
Definition at line 1244 of file symfile.c.
References symbol_file_add_main_1().
Referenced by add_inferior_command(), attach_command_post_wait(), captured_main(), clone_program_space(), irix_open_symbol_file_object(), open_symbol_file_object(), osf_open_symbol_file_object(), and som_open_symbol_file_object().
void symbol_file_add_separate (bfd * , const char * , int , struct objfile *)
Definition at line 1184 of file symfile.c.
References build_section_addr_info_from_objfile(), do_cleanups(), objfile::flags, make_cleanup_free_section_addr_info(), new_objfile(), OBJF_READNOW, OBJF_REORDERED, OBJF_SHARED, OBJF_USERLOADED, and symbol_file_add_with_addrs().
Referenced by coff_symfile_read(), elf_symfile_read(), macho_symfile_read(), and read_symbols().
void symbol_file_clear (int from_tty)
Definition at line 1266 of file symfile.c.
References _, error(), free_all_objfiles(), gdb_assert, have_full_symbols(), have_partial_symbols(), no_shared_libraries(), objfile_name(), printf_unfiltered(), query(), and symfile_objfile.
Referenced by gdb_clear_file(), and symbol_file_command().
CORE_ADDR symbol_overlayed_address (CORE_ADDR , struct obj_section *)
Definition at line 3101 of file symfile.c.
bfd* symfile_bfd_open (const char *)
Definition at line 1676 of file symfile.c.
References _, do_cleanups(), error(), gdb_bfd_open(), gnutarget, make_cleanup(), make_cleanup_bfd_unref(), name, openp(), OPF_RETURN_REALPATH, OPF_TRY_CWD_FIRST, perror_with_name(), remote_bfd_open(), remote_filename_p(), and xfree().
Referenced by coff_symfile_read(), elf_symfile_read(), and symbol_file_add().
int symfile_map_offsets_to_segments (bfd * , const struct symfile_segment_data * , struct section_offsets * , int , const CORE_ADDR *)
Definition at line 3662 of file symfile.c.
References gdb_assert, symfile_segment_data::num_segments, section_offsets::offsets, symfile_segment_data::segment_bases, and symfile_segment_data::segment_info.
Referenced by get_offsets(), and solib_target_relocate_section_addresses().
bfd_byte* symfile_relocate_debug_section (struct objfile * , asection * , bfd_byte *)
Definition at line 3618 of file symfile.c.
References gdb_assert, objfile::sf, and sym_fns::sym_relocate.
Referenced by dbx_read_symtab(), dwarf2_read_section(), and elfstab_build_psymtabs().
Variable Documentation
int auto_solib_add
Referenced by _initialize_solib(), enable_break(), handle_solib_event(), ia64_hpux_handle_dld_breakpoint_1(), ia64_hpux_solib_add_after_attach(), irix_solib_create_inferior_hook(), osf_solib_create_inferior_hook(), post_create_inferior(), reload_shared_libraries(), reload_shared_libraries_1(), remote_start_remote(), svr4_fetch_objfile_link_map(), and VEC().
int overlay_cache_invalid
Definition at line 2926 of file symfile.c.
Referenced by fetch_inferior_event(), load_command(), prepare_for_detach(), section_is_mapped(), and wait_for_inferior().
enum overlay_debugging_state overlay_debugging