GDB (xrefs): /home/stan/gdb/src/gdb/symfile-mem.c File Reference
/home/stan/gdb/src/gdb/symfile-mem.c File Reference
#include "defs.h"
#include "symtab.h"
#include "gdbcore.h"
#include "objfiles.h"
#include "exceptions.h"
#include "gdbcmd.h"
#include "target.h"
#include "value.h"
#include "symfile.h"
#include "observer.h"
#include "auxv.h"
#include "elf/common.h"
#include "gdb_bfd.h"
Classes
struct symbol_file_add_from_memory_args
Functions
gdb_static_assert (sizeof(CORE_ADDR)==sizeof(bfd_vma))
gdb_static_assert (sizeof(gdb_byte)==sizeof(bfd_byte))
gdb_static_assert (sizeof(ssize_t)<=sizeof(bfd_size_type))
static int target_read_memory_bfd (bfd_vma memaddr, bfd_byte *myaddr, bfd_size_type len)
static struct objfile * symbol_file_add_from_memory (struct bfd *templ, CORE_ADDR addr, char *name, int from_tty)
static void add_symbol_file_from_memory_command (char *args, int from_tty)
static int symbol_file_add_from_memory_wrapper (struct ui_out *uiout, void *data)
static void add_vsyscall_page (struct target_ops *target, int from_tty)
void _initialize_symfile_mem (void)
Variables
initialize_file_ftype _initialize_symfile_mem
Function Documentation
void _initialize_symfile_mem (void)
Definition at line 240 of file symfile-mem.c.
References _, add_cmd(), add_symbol_file_from_memory_command(), add_vsyscall_page(), class_files, cmdlist, and observer_attach_inferior_created().
static void add_symbol_file_from_memory_command (char * args, int from_tty) [static]
Definition at line 145 of file symfile-mem.c.
References _, error(), exec_bfd, parse_and_eval_address(), symbol_file_add_from_memory(), and symfile_objfile.
Referenced by _initialize_symfile_mem().
static void add_vsyscall_page (struct target_ops * target, int from_tty) [static]
Definition at line 194 of file symfile-mem.c.
References _, symbol_file_add_from_memory_args::bfd, catch_exceptions(), core_bfd, current_uiout, exec_bfd, symbol_file_add_from_memory_args::from_tty, symbol_file_add_from_memory_args::name, paddress(), RETURN_MASK_ALL, symbol_file_add_from_memory_wrapper(), symbol_file_add_from_memory_args::sysinfo_ehdr, target_auxv_search(), target_gdbarch(), warning(), and xstrprintf().
Referenced by _initialize_symfile_mem().
gdb_static_assert (sizeof(CORE_ADDR) = =sizeof(bfd_vma))
gdb_static_assert (sizeof(gdb_byte) = =sizeof(bfd_byte))
gdb_static_assert (sizeof(ssize_t)<=sizeof(bfd_size_type))
static struct objfile* symbol_file_add_from_memory (struct bfd * templ, CORE_ADDR addr, char * name, int from_tty) [static, read]
Definition at line 84 of file symfile-mem.c.
References _, section_addr_info::other_sections::addr, alloc_section_addr_info(), do_cleanups(), error(), gdb_bfd_ref(), gdb_bfd_stash_filename(), make_cleanup(), make_cleanup_bfd_unref(), name, section_addr_info::other_sections::name, section_addr_info::num_sections, OBJF_SHARED, section_addr_info::other, reinit_frame_cache(), section_addr_info::other_sections::sectindex, symbol_file_add_from_bfd(), SYMFILE_VERBOSE, target_read_memory_bfd(), and xfree().
Referenced by add_symbol_file_from_memory_command(), and symbol_file_add_from_memory_wrapper().
static int symbol_file_add_from_memory_wrapper (struct ui_out * uiout, void * data) [static]
Definition at line 181 of file symfile-mem.c.
References symbol_file_add_from_memory_args::bfd, symbol_file_add_from_memory_args::from_tty, symbol_file_add_from_memory_args::name, symbol_file_add_from_memory(), and symbol_file_add_from_memory_args::sysinfo_ehdr.
Referenced by add_vsyscall_page().
static int target_read_memory_bfd (bfd_vma memaddr, bfd_byte * myaddr, bfd_size_type len) [static]
Definition at line 69 of file symfile-mem.c.
References gdb_assert, and target_read_memory().
Referenced by symbol_file_add_from_memory().
Variable Documentation
initialize_file_ftype _initialize_symfile_mem
Referenced by initialize_all_files().