GDB (xrefs): /home/stan/gdb/src/gdb/symfile-debug.c File Reference
/home/stan/gdb/src/gdb/symfile-debug.c File Reference
#include "defs.h"
#include "gdbcmd.h"
#include "objfiles.h"
#include "observer.h"
#include "source.h"
#include "symtab.h"
#include "symfile.h"
Classes
struct debug_sym_fns_data
Defines
#define COPY_SF_PTR(from, to, name, func)
Functions
static int symfile_debug_installed (struct objfile *objfile)
static const char * debug_objfile_name (const struct objfile *objfile)
static const char * debug_symtab_name (struct symtab *symtab)
static int debug_qf_has_symbols (struct objfile *objfile)
static struct symtab * debug_qf_find_last_source_symtab (struct objfile *objfile)
static void debug_qf_forget_cached_source_info (struct objfile *objfile)
static int debug_qf_map_symtabs_matching_filename (struct objfile *objfile, const char *name, const char *real_path, int(*callback)(struct symtab *, void *), void *data)
static struct symtab * debug_qf_lookup_symbol (struct objfile *objfile, int kind, const char *name, domain_enum domain)
static void debug_qf_print_stats (struct objfile *objfile)
static void debug_qf_dump (struct objfile *objfile)
static void debug_qf_relocate (struct objfile *objfile, const struct section_offsets *new_offsets, const struct section_offsets *delta)
static void debug_qf_expand_symtabs_for_function (struct objfile *objfile, const char *func_name)
static void debug_qf_expand_all_symtabs (struct objfile *objfile)
static void debug_qf_expand_symtabs_with_fullname (struct objfile *objfile, const char *fullname)
static void debug_qf_map_matching_symbols (struct objfile *objfile, const char *name, domain_enum namespace, int global, int(*callback)(struct block *, struct symbol *, void *), void *data, symbol_compare_ftype *match, symbol_compare_ftype *ordered_compare)
static void debug_qf_expand_symtabs_matching (struct objfile *objfile, int(*file_matcher)(const char *, void *, int basenames), int(*name_matcher)(const char *, void *), enum search_domain kind, void *data)
static struct symtab * debug_qf_find_pc_sect_symtab (struct objfile *objfile, struct minimal_symbol *msymbol, CORE_ADDR pc, struct obj_section *section, int warn_if_readin)
static void debug_qf_map_symbol_filenames (struct objfile *objfile, symbol_filename_ftype *fun, void *data, int need_fullname)
static VEC (probe_p)
static unsigned debug_sym_get_probe_argument_count (struct probe *probe)
static int debug_can_evaluate_probe_arguments (struct probe *probe)
static struct value * debug_sym_evaluate_probe_argument (struct probe *probe, unsigned n)
static void debug_sym_compile_to_ax (struct probe *probe, struct agent_expr *expr, struct axs_value *value, unsigned n)
static void debug_sym_relocate_probe (struct objfile *objfile, const struct section_offsets *new_offsets, const struct section_offsets *delta)
static void debug_sym_new_init (struct objfile *objfile)
static void debug_sym_init (struct objfile *objfile)
static void debug_sym_read (struct objfile *objfile, int symfile_flags)
static void debug_sym_read_psymbols (struct objfile *objfile)
static void debug_sym_finish (struct objfile *objfile)
static void debug_sym_offsets (struct objfile *objfile, const struct section_addr_info *info)
static struct
symfile_segment_data * debug_sym_segments (bfd *abfd)
static void debug_sym_read_linetable (struct objfile *objfile)
static bfd_byte * debug_sym_relocate (struct objfile *objfile, asection *sectp, bfd_byte *buf)
static void symfile_debug_free_objfile (struct objfile *objfile, void *datum)
static void install_symfile_debug_logging (struct objfile *objfile)
static void uninstall_symfile_debug_logging (struct objfile *objfile)
void objfile_set_sym_fns (struct objfile *objfile, const struct sym_fns *sf)
static void set_debug_symfile (char *args, int from_tty, struct cmd_list_element *c)
static void show_debug_symfile (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
void _initialize_symfile_debug (void)
Variables
static struct objfile_data * symfile_debug_objfile_data_key
static int debug_symfile = 0
static struct
quick_symbol_functions debug_sym_quick_functions
static struct sym_probe_fns debug_sym_probe_fns
static struct sym_fns debug_sym_fns
initialize_file_ftype _initialize_symfile_debug
Define Documentation
#define COPY_SF_PTR (from, to, name, func)
Value:
do {                                            \
    if ((from)->name)                           \
      (to)->debug_sf.name = func;               \
  } while (0)
Referenced by install_symfile_debug_logging().
Function Documentation
void _initialize_symfile_debug (void)
Definition at line 759 of file symfile-debug.c.
References _, add_setshow_boolean_cmd(), debug_symfile, no_class, set_debug_symfile(), setdebuglist, show_debug_symfile(), showdebuglist, symfile_debug_free_objfile(), and symfile_debug_objfile_data_key.
static int debug_can_evaluate_probe_arguments (struct probe * probe) [static]
Definition at line 414 of file symfile-debug.c.
References sym_probe_fns::can_evaluate_probe_arguments, fprintf_filtered(), gdb_stdlog, host_address_to_string(), probe::objfile, debug_sym_fns_data::real_sf, sym_fns::sym_probe_fns, and symfile_debug_objfile_data_key.
static const char* debug_objfile_name (const struct objfile * objfile) [static]
Definition at line 65 of file symfile-debug.c.
References objfile::original_name.
Referenced by debug_qf_dump(), debug_qf_expand_all_symtabs(), debug_qf_expand_symtabs_for_function(), debug_qf_expand_symtabs_matching(), debug_qf_expand_symtabs_with_fullname(), debug_qf_find_last_source_symtab(), debug_qf_find_pc_sect_symtab(), debug_qf_forget_cached_source_info(), debug_qf_has_symbols(), debug_qf_lookup_symbol(), debug_qf_map_matching_symbols(), debug_qf_map_symbol_filenames(), debug_qf_map_symtabs_matching_filename(), debug_qf_print_stats(), debug_qf_relocate(), debug_sym_finish(), debug_sym_init(), debug_sym_new_init(), debug_sym_offsets(), debug_sym_read(), debug_sym_read_linetable(), debug_sym_read_psymbols(), debug_sym_relocate(), debug_sym_relocate_probe(), and VEC().
static void debug_qf_dump (struct objfile * objfile) [static]
Definition at line 189 of file symfile-debug.c.
References debug_objfile_name(), quick_symbol_functions::dump, fprintf_filtered(), gdb_stdlog, sym_fns::qf, debug_sym_fns_data::real_sf, and symfile_debug_objfile_data_key.
static void debug_qf_expand_all_symtabs (struct objfile * objfile) [static]
Definition at line 231 of file symfile-debug.c.
References debug_objfile_name(), quick_symbol_functions::expand_all_symtabs, fprintf_filtered(), gdb_stdlog, sym_fns::qf, debug_sym_fns_data::real_sf, and symfile_debug_objfile_data_key.
static void debug_qf_expand_symtabs_for_function (struct objfile * objfile, const char * func_name) [static]
Definition at line 217 of file symfile-debug.c.
References debug_objfile_name(), quick_symbol_functions::expand_symtabs_for_function, fprintf_filtered(), gdb_stdlog, sym_fns::qf, debug_sym_fns_data::real_sf, and symfile_debug_objfile_data_key.
static void debug_qf_expand_symtabs_matching (struct objfile * objfile, int(*)(const char *, void *, int basenames) file_matcher, int(*)(const char *, void *) name_matcher, enum search_domain kind, void * data) [static]
Definition at line 286 of file symfile-debug.c.
References debug_objfile_name(), quick_symbol_functions::expand_symtabs_matching, fprintf_filtered(), gdb_stdlog, host_address_to_string(), sym_fns::qf, debug_sym_fns_data::real_sf, search_domain_name(), and symfile_debug_objfile_data_key.
static void debug_qf_expand_symtabs_with_fullname (struct objfile * objfile, const char * fullname) [static]
Definition at line 243 of file symfile-debug.c.
References debug_objfile_name(), quick_symbol_functions::expand_symtabs_with_fullname, fprintf_filtered(), gdb_stdlog, sym_fns::qf, debug_sym_fns_data::real_sf, and symfile_debug_objfile_data_key.
static struct symtab* debug_qf_find_last_source_symtab (struct objfile * objfile) [static, read]
Definition at line 96 of file symfile-debug.c.
References debug_objfile_name(), debug_symtab_name(), quick_symbol_functions::find_last_source_symtab, fprintf_filtered(), gdb_stdlog, sym_fns::qf, debug_sym_fns_data::real_sf, and symfile_debug_objfile_data_key.
static struct symtab* debug_qf_find_pc_sect_symtab (struct objfile * objfile, struct minimal_symbol * msymbol, CORE_ADDR pc, struct obj_section * section, int warn_if_readin) [static, read]
Definition at line 311 of file symfile-debug.c.
References debug_objfile_name(), debug_symtab_name(), quick_symbol_functions::find_pc_sect_symtab, fprintf_filtered(), gdb_stdlog, hex_string(), host_address_to_string(), sym_fns::qf, debug_sym_fns_data::real_sf, and symfile_debug_objfile_data_key.
static void debug_qf_forget_cached_source_info (struct objfile * objfile) [static]
Definition at line 114 of file symfile-debug.c.
References debug_objfile_name(), quick_symbol_functions::forget_cached_source_info, fprintf_filtered(), gdb_stdlog, sym_fns::qf, debug_sym_fns_data::real_sf, and symfile_debug_objfile_data_key.
static int debug_qf_has_symbols (struct objfile * objfile) [static]
Definition at line 81 of file symfile-debug.c.
References debug_objfile_name(), fprintf_filtered(), gdb_stdlog, quick_symbol_functions::has_symbols, sym_fns::qf, debug_sym_fns_data::real_sf, and symfile_debug_objfile_data_key.
static struct symtab* debug_qf_lookup_symbol (struct objfile * objfile, int kind, const char * name, domain_enum domain) [static, read]
Definition at line 155 of file symfile-debug.c.
References debug_objfile_name(), debug_symtab_name(), domain_name(), fprintf_filtered(), gdb_stdlog, quick_symbol_functions::lookup_symbol, sym_fns::qf, debug_sym_fns_data::real_sf, and symfile_debug_objfile_data_key.
static void debug_qf_map_matching_symbols (struct objfile * objfile, const char * name, domain_enum namespace, int global, int(*)(struct block *, struct symbol *, void *) callback, void * data, symbol_compare_ftype * match, symbol_compare_ftype * ordered_compare) [static]
Definition at line 257 of file symfile-debug.c.
References debug_objfile_name(), domain_name(), fprintf_filtered(), gdb_stdlog, host_address_to_string(), quick_symbol_functions::map_matching_symbols, sym_fns::qf, debug_sym_fns_data::real_sf, and symfile_debug_objfile_data_key.
static void debug_qf_map_symbol_filenames (struct objfile * objfile, symbol_filename_ftype * fun, void * data, int need_fullname) [static]
Definition at line 340 of file symfile-debug.c.
References debug_objfile_name(), fprintf_filtered(), gdb_stdlog, host_address_to_string(), quick_symbol_functions::map_symbol_filenames, sym_fns::qf, debug_sym_fns_data::real_sf, and symfile_debug_objfile_data_key.
static int debug_qf_map_symtabs_matching_filename (struct objfile * objfile, const char * name, const char * real_path, int(*)(struct symtab *, void *) callback, void * data) [static]
Definition at line 126 of file symfile-debug.c.
References debug_objfile_name(), fprintf_filtered(), gdb_stdlog, host_address_to_string(), quick_symbol_functions::map_symtabs_matching_filename, sym_fns::qf, debug_sym_fns_data::real_sf, and symfile_debug_objfile_data_key.
static void debug_qf_print_stats (struct objfile * objfile) [static]
Definition at line 177 of file symfile-debug.c.
References debug_objfile_name(), fprintf_filtered(), gdb_stdlog, quick_symbol_functions::print_stats, sym_fns::qf, debug_sym_fns_data::real_sf, and symfile_debug_objfile_data_key.
static void debug_qf_relocate (struct objfile * objfile, const struct section_offsets * new_offsets, const struct section_offsets * delta) [static]
Definition at line 201 of file symfile-debug.c.
References debug_objfile_name(), fprintf_filtered(), gdb_stdlog, host_address_to_string(), sym_fns::qf, debug_sym_fns_data::real_sf, quick_symbol_functions::relocate, and symfile_debug_objfile_data_key.
static void debug_sym_compile_to_ax (struct probe * probe, struct agent_expr * expr, struct axs_value * value, unsigned n) [static]
Definition at line 454 of file symfile-debug.c.
References fprintf_filtered(), gdb_stdlog, host_address_to_string(), probe::objfile, debug_sym_fns_data::real_sf, sym_probe_fns::sym_compile_to_ax, sym_fns::sym_probe_fns, and symfile_debug_objfile_data_key.
static struct value* debug_sym_evaluate_probe_argument (struct probe * probe, unsigned n) [static, read]
Definition at line 432 of file symfile-debug.c.
References fprintf_filtered(), gdb_stdlog, host_address_to_string(), probe::objfile, debug_sym_fns_data::real_sf, sym_probe_fns::sym_evaluate_probe_argument, sym_fns::sym_probe_fns, and symfile_debug_objfile_data_key.
static void debug_sym_finish (struct objfile * objfile) [static]
Definition at line 550 of file symfile-debug.c.
References debug_objfile_name(), fprintf_filtered(), gdb_stdlog, debug_sym_fns_data::real_sf, sym_fns::sym_finish, and symfile_debug_objfile_data_key.
Referenced by install_symfile_debug_logging().
static unsigned debug_sym_get_probe_argument_count (struct probe * probe) [static]
Definition at line 396 of file symfile-debug.c.
References fprintf_filtered(), gdb_stdlog, host_address_to_string(), probe::objfile, debug_sym_fns_data::real_sf, sym_probe_fns::sym_get_probe_argument_count, sym_fns::sym_probe_fns, and symfile_debug_objfile_data_key.
static void debug_sym_init (struct objfile * objfile) [static]
Definition at line 514 of file symfile-debug.c.
References debug_objfile_name(), fprintf_filtered(), gdb_stdlog, debug_sym_fns_data::real_sf, sym_fns::sym_init, and symfile_debug_objfile_data_key.
Referenced by install_symfile_debug_logging().
static void debug_sym_new_init (struct objfile * objfile) [static]
Definition at line 502 of file symfile-debug.c.
References debug_objfile_name(), fprintf_filtered(), gdb_stdlog, debug_sym_fns_data::real_sf, sym_fns::sym_new_init, and symfile_debug_objfile_data_key.
Referenced by install_symfile_debug_logging().
static void debug_sym_offsets (struct objfile * objfile, const struct section_addr_info * info) [static]
Definition at line 562 of file symfile-debug.c.
References debug_objfile_name(), fprintf_filtered(), gdb_stdlog, host_address_to_string(), debug_sym_fns_data::real_sf, sym_fns::sym_offsets, and symfile_debug_objfile_data_key.
Referenced by install_symfile_debug_logging().
static void debug_sym_read (struct objfile * objfile, int symfile_flags) [static]
Definition at line 526 of file symfile-debug.c.
References debug_objfile_name(), fprintf_filtered(), gdb_stdlog, debug_sym_fns_data::real_sf, sym_fns::sym_read, and symfile_debug_objfile_data_key.
Referenced by install_symfile_debug_logging().
static void debug_sym_read_linetable (struct objfile * objfile) [static]
Definition at line 585 of file symfile-debug.c.
References debug_objfile_name(), fprintf_filtered(), gdb_stdlog, debug_sym_fns_data::real_sf, sym_fns::sym_read_linetable, and symfile_debug_objfile_data_key.
Referenced by install_symfile_debug_logging().
static void debug_sym_read_psymbols (struct objfile * objfile) [static]
Definition at line 538 of file symfile-debug.c.
References debug_objfile_name(), fprintf_filtered(), gdb_stdlog, debug_sym_fns_data::real_sf, sym_fns::sym_read_psymbols, and symfile_debug_objfile_data_key.
Referenced by install_symfile_debug_logging().
static bfd_byte* debug_sym_relocate (struct objfile * objfile, asection * sectp, bfd_byte * buf) [static]
Definition at line 597 of file symfile-debug.c.
References debug_objfile_name(), fprintf_filtered(), gdb_stdlog, host_address_to_string(), debug_sym_fns_data::real_sf, sym_fns::sym_relocate, and symfile_debug_objfile_data_key.
Referenced by install_symfile_debug_logging().
static void debug_sym_relocate_probe (struct objfile * objfile, const struct section_offsets * new_offsets, const struct section_offsets * delta) [static]
Definition at line 472 of file symfile-debug.c.
References debug_objfile_name(), fprintf_filtered(), gdb_stdlog, host_address_to_string(), debug_sym_fns_data::real_sf, sym_fns::sym_probe_fns, sym_probe_fns::sym_relocate_probe, and symfile_debug_objfile_data_key.
static struct symfile_segment_data* debug_sym_segments (bfd * abfd) [static, read]
Definition at line 576 of file symfile-debug.c.
References gdb_assert_not_reached.
Referenced by install_symfile_debug_logging().
static const char* debug_symtab_name (struct symtab * symtab) [static]
Definition at line 73 of file symfile-debug.c.
References symtab_to_filename_for_display().
Referenced by debug_qf_find_last_source_symtab(), debug_qf_find_pc_sect_symtab(), and debug_qf_lookup_symbol().
static void install_symfile_debug_logging (struct objfile * objfile) [static]
Definition at line 647 of file symfile-debug.c.
References COPY_SF_PTR, debug_sym_fns_data::debug_sf, debug_sym_finish(), debug_sym_init(), debug_sym_new_init(), debug_sym_offsets(), debug_sym_probe_fns, debug_sym_quick_functions, debug_sym_read(), debug_sym_read_linetable(), debug_sym_read_psymbols(), debug_sym_relocate(), debug_sym_segments(), gdb_assert, sym_fns::qf, debug_sym_fns_data::real_sf, objfile::sf, sym_fns::sym_probe_fns, symfile_debug_installed(), symfile_debug_objfile_data_key, and XZALLOC.
Referenced by objfile_set_sym_fns(), and set_debug_symfile().
void objfile_set_sym_fns (struct objfile * objfile, const struct sym_fns * sf)
Definition at line 710 of file symfile-debug.c.
References debug_symfile, gdb_assert, install_symfile_debug_logging(), objfile::sf, symfile_debug_installed(), and uninstall_symfile_debug_logging().
Referenced by elf_symfile_read(), reread_symbols(), and syms_from_objfile_1().
static void set_debug_symfile (char * args, int from_tty, struct cmd_list_element * c) [static]
Definition at line 728 of file symfile-debug.c.
References ALL_PSPACE_OBJFILES, ALL_PSPACES, debug_symfile, install_symfile_debug_logging(), symfile_debug_installed(), and uninstall_symfile_debug_logging().
Referenced by _initialize_symfile_debug().
static void show_debug_symfile (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 750 of file symfile-debug.c.
References _, and fprintf_filtered().
Referenced by _initialize_symfile_debug().
static void symfile_debug_free_objfile (struct objfile * objfile, void * datum) [static]
Definition at line 638 of file symfile-debug.c.
References xfree().
Referenced by _initialize_symfile_debug().
static int symfile_debug_installed (struct objfile * objfile) [static]
Definition at line 56 of file symfile-debug.c.
References objfile::sf, and symfile_debug_objfile_data_key.
Referenced by install_symfile_debug_logging(), objfile_set_sym_fns(), set_debug_symfile(), and uninstall_symfile_debug_logging().
static void uninstall_symfile_debug_logging (struct objfile * objfile) [static]
Definition at line 692 of file symfile-debug.c.
References gdb_assert, debug_sym_fns_data::real_sf, objfile::sf, symfile_debug_installed(), symfile_debug_objfile_data_key, and xfree().
Referenced by objfile_set_sym_fns(), and set_debug_symfile().
static VEC (probe_p) [static]
Definition at line 378 of file symfile-debug.c.
References debug_objfile_name(), fprintf_filtered(), gdb_stdlog, host_address_to_string(), debug_sym_fns_data::real_sf, sym_fns::sym_probe_fns, symfile_debug_objfile_data_key, and VEC.
Variable Documentation
initialize_file_ftype _initialize_symfile_debug
Definition at line 756 of file symfile-debug.c.
Referenced by initialize_all_files().
struct sym_fns debug_sym_fns [static]
Initial value:
{
  debug_sym_new_init,
  debug_sym_init,
  debug_sym_read,
  debug_sym_read_psymbols,
  debug_sym_finish,
  debug_sym_offsets,
  debug_sym_segments,
  debug_sym_read_linetable,
  debug_sym_relocate,
  &debug_sym_probe_fns,
  &debug_sym_quick_functions
}
Definition at line 620 of file symfile-debug.c.
struct sym_probe_fns debug_sym_probe_fns [static]
Initial value:
{
  debug_sym_get_probes,
  debug_sym_get_probe_argument_count,
  debug_can_evaluate_probe_arguments,
  debug_sym_evaluate_probe_argument,
  debug_sym_compile_to_ax,
  debug_sym_relocate_probe
}
Definition at line 489 of file symfile-debug.c.
Referenced by install_symfile_debug_logging().
struct quick_symbol_functions debug_sym_quick_functions [static]
Initial value:
{
  debug_qf_has_symbols,
  debug_qf_find_last_source_symtab,
  debug_qf_forget_cached_source_info,
  debug_qf_map_symtabs_matching_filename,
  debug_qf_lookup_symbol,
  debug_qf_print_stats,
  debug_qf_dump,
  debug_qf_relocate,
  debug_qf_expand_symtabs_for_function,
  debug_qf_expand_all_symtabs,
  debug_qf_expand_symtabs_with_fullname,
  debug_qf_map_matching_symbols,
  debug_qf_expand_symtabs_matching,
  debug_qf_find_pc_sect_symtab,
  debug_qf_map_symbol_filenames
}
Definition at line 357 of file symfile-debug.c.
Referenced by install_symfile_debug_logging().
int debug_symfile = 0 [static]
Definition at line 51 of file symfile-debug.c.
Referenced by _initialize_symfile_debug(), objfile_set_sym_fns(), and set_debug_symfile().
struct objfile_data* symfile_debug_objfile_data_key [static]
Definition at line 48 of file symfile-debug.c.
Referenced by _initialize_symfile_debug(), debug_can_evaluate_probe_arguments(), debug_qf_dump(), debug_qf_expand_all_symtabs(), debug_qf_expand_symtabs_for_function(), debug_qf_expand_symtabs_matching(), debug_qf_expand_symtabs_with_fullname(), debug_qf_find_last_source_symtab(), debug_qf_find_pc_sect_symtab(), debug_qf_forget_cached_source_info(), debug_qf_has_symbols(), debug_qf_lookup_symbol(), debug_qf_map_matching_symbols(), debug_qf_map_symbol_filenames(), debug_qf_map_symtabs_matching_filename(), debug_qf_print_stats(), debug_qf_relocate(), debug_sym_compile_to_ax(), debug_sym_evaluate_probe_argument(), debug_sym_finish(), debug_sym_get_probe_argument_count(), debug_sym_init(), debug_sym_new_init(), debug_sym_offsets(), debug_sym_read(), debug_sym_read_linetable(), debug_sym_read_psymbols(), debug_sym_relocate(), debug_sym_relocate_probe(), install_symfile_debug_logging(), symfile_debug_installed(), uninstall_symfile_debug_logging(), and VEC().