GDB (xrefs): /home/stan/gdb/src/gdb/symfile.c File Reference
/home/stan/gdb/src/gdb/symfile.c File Reference
#include "defs.h"
#include "arch-utils.h"
#include "bfdlink.h"
#include "symtab.h"
#include "gdbtypes.h"
#include "gdbcore.h"
#include "frame.h"
#include "target.h"
#include "value.h"
#include "symfile.h"
#include "objfiles.h"
#include "source.h"
#include "gdbcmd.h"
#include "breakpoint.h"
#include "language.h"
#include "complaints.h"
#include "demangle.h"
#include "inferior.h"
#include "regcache.h"
#include "filenames.h"
#include "gdb-stabs.h"
#include "gdb_obstack.h"
#include "completer.h"
#include "bcache.h"
#include "hashtab.h"
#include "readline/readline.h"
#include "gdb_assert.h"
#include "block.h"
#include "observer.h"
#include "exec.h"
#include "parser-defs.h"
#include "varobj.h"
#include "elf-bfd.h"
#include "solib.h"
#include "remote.h"
#include "stack.h"
#include "gdb_bfd.h"
#include "cli/cli-utils.h"
#include <sys/types.h>
#include <fcntl.h>
#include "gdb_string.h"
#include "gdb_stat.h"
#include <ctype.h>
#include <time.h>
#include <sys/time.h>
#include "psymtab.h"
Classes
struct registered_sym_fns
struct place_section_arg
struct load_section_data
struct load_progress_data
struct load_progress_section_data
struct filename_language
Defines
#define DEBUG_SUBDIRECTORY ".debug"
Typedefs
typedef struct objfile * objfilep
Enumerations
enum ovly_index { VMA, SIZE, LMA, MAPPED }
Functions
static void clear_symtab_users_cleanup (void *ignore)
static void load_command (char *, int)
static void symbol_file_add_main_1 (const char *args, int from_tty, int flags)
static void add_symbol_file_command (char *, int)
static struct sym_fns * find_sym_fns (bfd *)
static void decrement_reading_symtab (void *)
static void overlay_invalidate_all (void)
static void overlay_auto_command (char *, int)
static void overlay_manual_command (char *, int)
static void overlay_off_command (char *, int)
static void overlay_load_command (char *, int)
static void overlay_command (char *, int)
static void simple_free_overlay_table (void)
static void read_target_long_array (CORE_ADDR, unsigned int *, int, int, enum bfd_endian)
static int simple_read_overlay_table (void)
static int simple_overlay_update_1 (struct obj_section *)
static void add_filename_language (char *ext, enum language lang)
static void info_ext_lang_command (char *args, int from_tty)
static void init_filename_language_table (void)
static void symfile_find_segment_sections (struct objfile *objfile)
void _initialize_symfile (void)
DEF_VEC_O (registered_sym_fns)
static VEC (registered_sym_fns)
struct cleanup * increment_reading_symtab (void)
void find_lowest_section (bfd *abfd, asection *sect, void *obj)
struct section_addr_info * alloc_section_addr_info (size_t num_sections)
struct section_addr_info * build_section_addr_info_from_section_table (const struct target_section *start, const struct target_section *end)
static struct section_addr_info * build_section_addr_info_from_bfd (bfd *abfd)
struct section_addr_info * build_section_addr_info_from_objfile (const struct objfile *objfile)
void free_section_addr_info (struct section_addr_info *sap)
static void init_objfile_sect_indices (struct objfile *objfile)
static void place_section (bfd *abfd, asection *sect, void *obj)
void relative_addr_info_to_section_offsets (struct section_offsets *section_offsets, int num_sections, const struct section_addr_info *addrs)
static const char * addr_section_name (const char *s)
static int addrs_section_compar (const void *ap, const void *bp)
static struct other_sections ** addrs_section_sort (struct section_addr_info *addrs)
void addr_info_make_relative (struct section_addr_info *addrs, bfd *abfd)
void default_symfile_offsets (struct objfile *objfile, const struct section_addr_info *addrs)
struct symfile_segment_data * default_symfile_segments (bfd *abfd)
static void read_symbols (struct objfile *objfile, int add_flags)
static void init_entry_point_info (struct objfile *objfile)
static void syms_from_objfile_1 (struct objfile *objfile, struct section_addr_info *addrs, int add_flags)
static void syms_from_objfile (struct objfile *objfile, struct section_addr_info *addrs, int add_flags)
void new_symfile_objfile (struct objfile *objfile, int add_flags)
static struct objfile * symbol_file_add_with_addrs (bfd *abfd, const char *name, int add_flags, struct section_addr_info *addrs, int flags, struct objfile *parent)
void symbol_file_add_separate (bfd *bfd, const char *name, int symfile_flags, struct objfile *objfile)
struct objfile * symbol_file_add_from_bfd (bfd *abfd, const char *name, int add_flags, struct section_addr_info *addrs, int flags, struct objfile *parent)
struct objfile * symbol_file_add (const char *name, int add_flags, struct section_addr_info *addrs, int flags)
void symbol_file_add_main (const char *args, int from_tty)
void symbol_file_clear (int from_tty)
static int separate_debug_file_exists (const char *name, unsigned long crc, struct objfile *parent_objfile)
static void show_debug_file_directory (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static char * find_separate_debug_file (const char *dir, const char *canon_dir, const char *debuglink, unsigned long crc32, struct objfile *objfile)
static void terminate_after_last_dir_separator (char *path)
char * find_separate_debug_file_by_debuglink (struct objfile *objfile)
void symbol_file_command (char *args, int from_tty)
void set_initial_language (void)
bfd * gdb_bfd_open_maybe_remote (const char *name)
bfd * symfile_bfd_open (const char *cname)
int get_section_index (struct objfile *objfile, char *section_name)
void add_symtab_fns (enum bfd_flavour flavour, const struct sym_fns *sf)
static void add_section_size_callback (bfd *abfd, asection *asec, void *data)
static void load_progress (ULONGEST bytes, void *untyped_arg)
static void load_section_callback (bfd *abfd, asection *asec, void *data)
static void clear_memory_write_data (void *arg)
void generic_load (char *args, int from_tty)
void print_transfer_performance (struct ui_file *stream, unsigned long data_count, unsigned long write_count, const struct timeval *start_time, const struct timeval *end_time)
DEF_VEC_P (objfilep)
void reread_symbols (void)
static void show_ext_args (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static void set_ext_lang_command (char *args, int from_tty, struct cmd_list_element *e)
enum language deduce_language_from_filename (const char *filename)
struct symtab * allocate_symtab (const char *filename, struct objfile *objfile)
void clear_symtab_users (int add_flags)
int section_is_overlay (struct obj_section *section)
int section_is_mapped (struct obj_section *osect)
CORE_ADDR pc_in_unmapped_range (CORE_ADDR pc, struct obj_section *section)
CORE_ADDR pc_in_mapped_range (CORE_ADDR pc, struct obj_section *section)
static int sections_overlap (struct obj_section *a, struct obj_section *b)
CORE_ADDR overlay_unmapped_address (CORE_ADDR pc, struct obj_section *section)
CORE_ADDR overlay_mapped_address (CORE_ADDR pc, struct obj_section *section)
CORE_ADDR symbol_overlayed_address (CORE_ADDR address, struct obj_section *section)
struct obj_section * find_pc_overlay (CORE_ADDR pc)
struct obj_section * find_pc_mapped_section (CORE_ADDR pc)
static void list_overlays_command (char *args, int from_tty)
static void map_overlay_command (char *args, int from_tty)
static void unmap_overlay_command (char *args, int from_tty)
void simple_overlay_update (struct obj_section *osect)
static void symfile_dummy_outputs (bfd *abfd, asection *sectp, void *dummy)
bfd_byte * default_symfile_relocate (struct objfile *objfile, asection *sectp, bfd_byte *buf)
bfd_byte * symfile_relocate_debug_section (struct objfile *objfile, asection *sectp, bfd_byte *buf)
struct symfile_segment_data * get_symfile_segment_data (bfd *abfd)
void free_symfile_segment_data (struct symfile_segment_data *data)
int symfile_map_offsets_to_segments (bfd *abfd, const struct symfile_segment_data *data, struct section_offsets *offsets, int num_segment_bases, const CORE_ADDR *segment_bases)
Variables
int(* deprecated_ui_load_progress_hook)(const char *section, unsigned long num)
void(* deprecated_show_load_progress)(const char *section, unsigned long section_sent, unsigned long section_size, unsigned long total_sent, unsigned long total_size)
void(* deprecated_pre_add_symbol_hook)(const char *)
void(* deprecated_post_add_symbol_hook)(void)
int readnow_symbol_files
char * debug_file_directory = NULL
static int validate_download = 0
static filename_language * filename_language_table
static int fl_table_size
static int fl_table_next
static char * ext_args
enum overlay_debugging_state overlay_debugging = ovly_off
int overlay_cache_invalid = 0
static struct cmd_list_element * overlaylist
static unsigned(* cache_ovly_table)[4] = 0
static unsigned cache_novlys = 0
static CORE_ADDR cache_ovly_table_base = 0
Define Documentation
#define DEBUG_SUBDIRECTORY ".debug"
Definition at line 1380 of file symfile.c.
Referenced by find_separate_debug_file().
Typedef Documentation
typedef struct objfile* objfilep
Definition at line 2345 of file symfile.c.
Enumeration Type Documentation
enum ovly_index
Enumerator:
VMA
SIZE
LMA
MAPPED
Definition at line 3386 of file symfile.c.
Function Documentation
void _initialize_symfile (void)
static void add_filename_language (char * ext, enum language lang) [static]
Definition at line 2619 of file symfile.c.
References filename_language::ext, fl_table_next, fl_table_size, filename_language::lang, and xrealloc().
Referenced by init_filename_language_table(), and set_ext_lang_command().
static void add_section_size_callback (bfd * abfd, asection * asec, void * data) [static]
Definition at line 1871 of file symfile.c.
Referenced by generic_load().
static void add_symbol_file_command (char * args, int from_tty) [static]
Definition at line 2196 of file symfile.c.
References _, section_addr_info::other_sections::addr, alloc_section_addr_info(), do_cleanups(), dont_repeat(), error(), flags, gdb_buildargv(), get_current_arch(), make_cleanup(), make_cleanup_freeargv(), name, section_addr_info::other_sections::name, null_cleanup(), section_addr_info::num_sections, OBJF_READNOW, OBJF_USERLOADED, section_addr_info::other, paddress(), parse_and_eval_address(), printf_unfiltered(), query(), reinit_frame_cache(), symbol_file_add(), SYMFILE_VERBOSE, xfree(), xmalloc(), and xrealloc().
void add_symtab_fns (enum bfd_flavour flavour, const struct sym_fns * sf)
Definition at line 1764 of file symfile.c.
References VEC_safe_push.
Referenced by _initialize_machoread(), _initialize_somread(), and _initialize_xcoffread().
void addr_info_make_relative (struct section_addr_info * addrs, bfd * abfd)
Definition at line 536 of file symfile.c.
References _, section_addr_info::other_sections::addr, addr_section_name(), addrs_section_sort(), build_section_addr_info_from_bfd(), do_cleanups(), find_lowest_section(), gdb_assert, make_cleanup(), make_cleanup_free_section_addr_info(), section_addr_info::other_sections::name, section_addr_info::num_sections, section_addr_info::other, section_addr_info::other_sections::sectindex, warning(), xfree(), and xzalloc().
Referenced by objfile_relocate(), and syms_from_objfile_1().
static const char* addr_section_name (const char * s) [static]
Definition at line 484 of file symfile.c.
Referenced by addr_info_make_relative(), and addrs_section_compar().
static int addrs_section_compar (const void * ap, const void * bp) [static]
Definition at line 498 of file symfile.c.
References addr_section_name().
Referenced by addrs_section_sort().
static struct other_sections** addrs_section_sort (struct section_addr_info * addrs) [static, read]
Definition at line 515 of file symfile.c.
References addrs_section_compar(), section_addr_info::num_sections, section_addr_info::other, qsort, and xmalloc().
Referenced by addr_info_make_relative().
struct section_addr_info* alloc_section_addr_info (size_t num_sections) [read]
Definition at line 212 of file symfile.c.
References memset(), size, and xmalloc().
Referenced by add_symbol_file_command(), build_section_addr_info_from_bfd(), build_section_addr_info_from_section_table(), jit_bfd_try_read_symtab(), symbol_file_add_from_memory(), and syms_from_objfile_1().
struct symtab* allocate_symtab (const char * filename, struct objfile * objfile) [read]
Definition at line 2795 of file symfile.c.
References symtab::debugformat, deduce_language_from_filename(), symtab::filename, objfile_per_bfd_storage::filename_cache, fprintf_unfiltered(), symtab::fullname, gdb_stdlog, host_address_to_string(), symtab::language, memset(), symtab::next, symtab::objfile, objfile_name(), objfile::objfile_obstack, objfile::per_bfd, symtab_create_debug, objfile::symtabs, and xfree().
Referenced by dwarf_decode_lines(), end_symtab_from_static_block(), finalize_symtab(), get_java_class_symtab(), new_symtab(), and setup_type_unit_groups().
static struct section_addr_info* build_section_addr_info_from_bfd (bfd * abfd) [static, read]
Definition at line 261 of file symfile.c.
References section_addr_info::other_sections::addr, alloc_section_addr_info(), gdb_bfd_section_index(), section_addr_info::other_sections::name, section_addr_info::num_sections, section_addr_info::other, and section_addr_info::other_sections::sectindex.
Referenced by addr_info_make_relative(), and build_section_addr_info_from_objfile().
struct section_addr_info* build_section_addr_info_from_objfile (const struct objfile * objfile) [read]
Definition at line 285 of file symfile.c.
References section_addr_info::other_sections::addr, build_section_addr_info_from_bfd(), section_addr_info::num_sections, objfile::obfd, section_offsets::offsets, section_addr_info::other, section_addr_info::other_sections::sectindex, and objfile::section_offsets.
Referenced by objfile_relocate(), and symbol_file_add_separate().
struct section_addr_info* build_section_addr_info_from_section_table (const struct target_section * start, const struct target_section * end) [read]
Definition at line 229 of file symfile.c.
References section_addr_info::other_sections::addr, target_section::addr, alloc_section_addr_info(), gdb_bfd_section_index(), section_addr_info::other_sections::name, section_addr_info::num_sections, section_addr_info::other, section_addr_info::other_sections::sectindex, and target_section::the_bfd_section.
Referenced by solib_read_symbols().
static void clear_memory_write_data (void * arg) [static]
Definition at line 2012 of file symfile.c.
References memory_write_request::baton, memory_write_request::data, VEC, VEC_free, VEC_iterate, and xfree().
Referenced by generic_load().
void clear_symtab_users (int add_flags)
Definition at line 2842 of file symfile.c.
References breakpoint_re_set(), clear_current_source_symtab_and_line(), clear_displays(), clear_last_displayed_sal(), clear_pc_function_cache(), expression_context_block, innermost_block, observer_notify_new_objfile(), SYMFILE_DEFER_BP_RESET, and varobj_invalidate().
Referenced by clear_symtab_users_cleanup(), free_all_objfiles(), m32r_load(), m32r_upload_command(), new_symfile_objfile(), reread_symbols(), and som_solib_create_inferior_hook().
static void clear_symtab_users_cleanup (void * ignore) [static]
Definition at line 2870 of file symfile.c.
References clear_symtab_users().
Referenced by reread_symbols(), and syms_from_objfile_1().
static void decrement_reading_symtab (void *) [static]
Referenced by increment_reading_symtab().
enum language deduce_language_from_filename (const char * filename)
Definition at line 2767 of file symfile.c.
References fl_table_next, filename_language::lang, language_unknown, and strrchr().
Referenced by allocate_symtab(), parse_partial_symbols(), patch_subfile_names(), read_dbx_symtab(), scan_xcoff_symtab(), start_psymtab(), start_subfile(), and xcoff_start_psymtab().
DEF_VEC_O (registered_sym_fns)
DEF_VEC_P (objfilep)
void default_symfile_offsets (struct objfile * objfile, const struct section_addr_info * addrs)
Definition at line 685 of file symfile.c.
References exec_set_section_address(), gdb_bfd_count_sections(), init_objfile_sect_indices(), place_section_arg::lowest, objfile::num_sections, objfile::obfd, objfile::objfile_obstack, place_section_arg::offsets, section_offsets::offsets, place_section(), relative_addr_info_to_section_offsets(), objfile::section_offsets, and SIZEOF_N_SECTION_OFFSETS.
Referenced by xcoff_symfile_offsets().
bfd_byte* default_symfile_relocate (struct objfile * objfile, asection * sectp, bfd_byte * buf)
Definition at line 3584 of file symfile.c.
References symfile_dummy_outputs().
struct symfile_segment_data* default_symfile_segments (bfd * abfd) [read]
Definition at line 775 of file symfile.c.
References symfile_segment_data::num_segments, symfile_segment_data::segment_bases, symfile_segment_data::segment_info, symfile_segment_data::segment_sizes, XCALLOC, and XZALLOC.
void find_lowest_section (bfd * abfd, asection * sect, void * obj)
Definition at line 191 of file symfile.c.
Referenced by addr_info_make_relative().
struct obj_section* find_pc_mapped_section (CORE_ADDR pc) [read]
Definition at line 3158 of file symfile.c.
References ALL_OBJSECTIONS, overlay_debugging, pc_in_mapped_range(), and section_is_mapped().
Referenced by backtrace_command_1(), block_for_pc(), blockvector_for_pc(), find_pc_function(), find_pc_section(), find_pc_symtab(), and gdbpy_block_for_pc().
struct obj_section* find_pc_overlay (CORE_ADDR pc) [read]
Definition at line 3131 of file symfile.c.
References ALL_OBJSECTIONS, overlay_debugging, pc_in_mapped_range(), pc_in_unmapped_range(), section_is_mapped(), and section_is_overlay().
Referenced by arm_linux_copy_svc(), build_address_symbolic(), call_function_by_hand(), convert_linespec_to_sals(), create_internal_breakpoint(), elf_gnu_ifunc_resolver_stop(), find_pc_line(), find_pc_partial_function_gnu_ifunc(), handle_inferior_event(), handle_step_into_function(), insert_hp_step_resume_breakpoint_at_frame(), insert_step_resume_breakpoint_at_caller(), memory_xfer_partial_1(), parse_probes(), and set_momentary_breakpoint_at_pc().
static char* find_separate_debug_file (const char * dir, const char * canon_dir, const char * debuglink, unsigned long crc32, struct objfile * objfile) [static]
Definition at line 1391 of file symfile.c.
References debug_file_directory, DEBUG_SUBDIRECTORY, do_cleanups(), gdb_sysroot, make_cleanup_free_char_ptr_vec(), separate_debug_file_exists(), VEC, VEC_iterate, xfree(), and xmalloc().
Referenced by find_separate_debug_file_by_debuglink().
char* find_separate_debug_file_by_debuglink (struct objfile * objfile)
Definition at line 1500 of file symfile.c.
References do_cleanups(), find_separate_debug_file(), make_cleanup(), objfile::obfd, objfile_name(), terminate_after_last_dir_separator(), and xfree().
Referenced by coff_symfile_read(), and elf_symfile_read().
static struct sym_fns * find_sym_fns (bfd * abfd) [static, read]
Definition at line 1777 of file symfile.c.
References _, error(), registered_sym_fns::sym_flavour, registered_sym_fns::sym_fns, and VEC_iterate.
Referenced by get_symfile_segment_data(), reread_symbols(), and syms_from_objfile_1().
void free_section_addr_info (struct section_addr_info * sap)
Definition at line 306 of file symfile.c.
References section_addr_info::other_sections::name, section_addr_info::num_sections, section_addr_info::other, and xfree().
Referenced by do_free_section_addr_info(), and solib_read_symbols().
void free_symfile_segment_data (struct symfile_segment_data * data)
Definition at line 3638 of file symfile.c.
References symfile_segment_data::segment_bases, symfile_segment_data::segment_info, symfile_segment_data::segment_sizes, and xfree().
Referenced by get_offsets(), solib_target_relocate_section_addresses(), and symfile_find_segment_sections().
bfd* gdb_bfd_open_maybe_remote (const char * name)
Definition at line 1658 of file symfile.c.
References gdb_bfd_open(), gnutarget, remote_bfd_open(), and remote_filename_p().
Referenced by build_id_to_debug_bfd(), reread_symbols(), separate_debug_file_exists(), and windows_xfer_shared_library().
void generic_load (char * args, int from_tty)
Definition at line 2028 of file symfile.c.
References _, add_section_size_callback(), breakpoint_re_set(), clear_memory_write_data(), current_uiout, load_progress_data::data_count, do_cleanups(), error(), error_no_arg(), flash_discard, gdb_bfd_open(), gdb_buildargv(), gdb_stdout, gdbarch_addr_bits_remove(), get_current_regcache(), gnutarget, load_section_data::load_offset, load_progress(), load_section_callback(), make_cleanup(), make_cleanup_bfd_unref(), make_cleanup_freeargv(), memset(), null_cleanup(), paddress(), perror_with_name(), print_transfer_performance(), load_section_data::progress_data, regcache_write_pc(), strtoulst(), target_gdbarch(), target_write_memory_blocks(), load_progress_data::total_size, ui_out_field_fmt(), ui_out_text(), load_progress_data::write_count, and xfree().
Referenced by init_remote_ops(), and m32r_load_gen().
int get_section_index (struct objfile * objfile, char * section_name)
Definition at line 1747 of file symfile.c.
References objfile::obfd.
Referenced by parse_partial_symbols(), and record_minimal_symbol().
struct symfile_segment_data* get_symfile_segment_data (bfd * abfd) [read]
Definition at line 3627 of file symfile.c.
References find_sym_fns(), and sym_fns::sym_segments.
Referenced by get_offsets(), solib_target_relocate_section_addresses(), and symfile_find_segment_sections().
struct cleanup* increment_reading_symtab (void) [read]
Definition at line 174 of file symfile.c.
References currently_reading_symtab, decrement_reading_symtab(), gdb_assert, and make_cleanup().
Referenced by dw2_instantiate_symtab(), and psymtab_to_symtab().
static void info_ext_lang_command (char * args, int from_tty) [static]
Definition at line 2704 of file symfile.c.
References _, fl_table_next, language_str(), and printf_filtered().
static void init_entry_point_info (struct objfile * objfile) [static]
Definition at line 868 of file symfile.c.
References current_target, objfile::ei, entry_info::entry_point, entry_info::entry_point_p, gdbarch_addr_bits_remove(), gdbarch_convert_from_func_ptr_addr(), get_objfile_arch(), and objfile::obfd.
Referenced by reread_symbols(), and syms_from_objfile().
static void init_filename_language_table (void) [static]
Definition at line 2717 of file symfile.c.
References add_filename_language(), fl_table_next, fl_table_size, language_ada, language_asm, language_c, language_cplus, language_d, language_fortran, language_java, language_objc, language_pascal, and xmalloc().
static void init_objfile_sect_indices (struct objfile * objfile) [static]
Definition at line 318 of file symfile.c.
References ANOFFSET, objfile::num_sections, objfile::obfd, objfile::sect_index_bss, objfile::sect_index_data, objfile::sect_index_rodata, objfile::sect_index_text, objfile::section_offsets, and symfile_find_segment_sections().
Referenced by default_symfile_offsets().
static void list_overlays_command (char * args, int from_tty) [static]
Definition at line 3175 of file symfile.c.
References _, ALL_OBJSECTIONS, fputs_filtered(), gdb_stdout, get_objfile_arch(), name, objfile::obfd, overlay_debugging, paddress(), printf_filtered(), puts_filtered(), section_is_mapped(), size, and obj_section::the_bfd_section.
static void load_command (char * arg, int from_tty) [static]
Definition at line 1800 of file symfile.c.
References cleanup::arg, do_cleanups(), dont_repeat(), get_exec_file(), make_cleanup(), null_cleanup(), overlay_cache_invalid, reopen_exec_file(), reread_symbols(), target_load(), xfree(), and xmalloc().
static void load_progress (ULONGEST bytes, void * untyped_arg) [static]
Definition at line 1908 of file symfile.c.
References _, load_progress_section_data::buffer, check(), check_quit_flag(), load_progress_section_data::cumulative, current_uiout, load_progress_data::data_count, deprecated_show_load_progress, deprecated_ui_load_progress_hook, do_cleanups(), error(), hex_string(), load_progress_section_data::lma, make_cleanup(), memcmp(), paddress(), load_progress_section_data::section_name, load_progress_section_data::section_sent, load_progress_section_data::section_size, target_gdbarch(), target_read_memory(), load_progress_data::total_size, ui_out_message(), validate_download, load_progress_data::write_count, xfree(), and xmalloc().
Referenced by generic_load().
static void load_section_callback (bfd * abfd, asection * asec, void * data) [static]
Definition at line 1972 of file symfile.c.
References memory_write_request::baton, memory_write_request::begin, load_progress_section_data::buffer, load_progress_section_data::cumulative, memory_write_request::data, memory_write_request::end, load_progress_section_data::lma, load_section_data::load_offset, memset(), load_section_data::progress_data, load_progress_section_data::section_name, load_progress_section_data::section_size, size, VEC_safe_push, xcalloc(), and xmalloc().
Referenced by generic_load().
static void map_overlay_command (char * args, int from_tty) [static]
Definition at line 3215 of file symfile.c.
References _, ALL_OBJSECTIONS, error(), info_verbose, objfile::obfd, overlay_debugging, obj_section::ovly_mapped, printf_unfiltered(), section_is_overlay(), sections_overlap(), and obj_section::the_bfd_section.
void new_symfile_objfile (struct objfile * objfile, int add_flags)
Definition at line 1038 of file symfile.c.
References breakpoint_re_set(), clear_complaints(), clear_symtab_users(), symfile_complaints, SYMFILE_DEFER_BP_RESET, SYMFILE_MAINLINE, symfile_objfile, and SYMFILE_VERBOSE.
Referenced by symbol_file_add_with_addrs().
static void overlay_auto_command (char * args, int from_tty) [static]
Definition at line 3290 of file symfile.c.
References _, enable_overlay_breakpoints(), info_verbose, overlay_debugging, ovly_auto, and printf_unfiltered().
static void overlay_command (char * args, int from_tty) [static]
Definition at line 3342 of file symfile.c.
References gdb_stdout, help_list(), and printf_unfiltered().
static void overlay_invalidate_all (void) [static]
Definition at line 2953 of file symfile.c.
References ALL_OBJSECTIONS, obj_section::ovly_mapped, and section_is_overlay().
Referenced by section_is_mapped().
static void overlay_load_command (char * args, int from_tty) [static]
Definition at line 3325 of file symfile.c.
References _, error(), gdbarch_overlay_update(), gdbarch_overlay_update_p(), and get_current_arch().
static void overlay_manual_command (char * args, int from_tty) [static]
Definition at line 3303 of file symfile.c.
References _, disable_overlay_breakpoints(), info_verbose, overlay_debugging, ovly_on, and printf_unfiltered().
CORE_ADDR overlay_mapped_address (CORE_ADDR pc, struct obj_section * section)
Definition at line 3082 of file symfile.c.
References objfile::obfd, obj_section::objfile, pc_in_unmapped_range(), section_is_overlay(), and obj_section::the_bfd_section.
Referenced by build_address_symbolic(), find_pc_line(), find_pc_partial_function_gnu_ifunc(), memory_xfer_partial_1(), skip_prologue_sal(), and sym_info().
static void overlay_off_command (char * args, int from_tty) [static]
Definition at line 3316 of file symfile.c.
References _, disable_overlay_breakpoints(), info_verbose, overlay_debugging, ovly_off, and printf_unfiltered().
CORE_ADDR overlay_unmapped_address (CORE_ADDR pc, struct obj_section * section)
Definition at line 3063 of file symfile.c.
References objfile::obfd, obj_section::objfile, pc_in_mapped_range(), section_is_overlay(), and obj_section::the_bfd_section.
Referenced by address_info(), find_pc_partial_function_gnu_ifunc(), insert_bp_location(), skip_prologue_sal(), and symbol_overlayed_address().
CORE_ADDR pc_in_mapped_range (CORE_ADDR pc, struct obj_section * section)
Definition at line 3032 of file symfile.c.
References obj_section_addr, obj_section_endaddr, and section_is_overlay().
Referenced by find_pc_mapped_section(), find_pc_overlay(), and overlay_unmapped_address().
CORE_ADDR pc_in_unmapped_range (CORE_ADDR pc, struct obj_section * section)
Definition at line 3009 of file symfile.c.
References objfile::obfd, obj_section_offset, obj_section::objfile, offset, section_is_overlay(), size, and obj_section::the_bfd_section.
Referenced by build_address_symbolic(), find_pc_line(), find_pc_overlay(), find_pc_partial_function_gnu_ifunc(), memory_xfer_partial_1(), overlay_mapped_address(), and sym_info().
static void place_section (bfd * abfd, asection * sect, void * obj) [static]
Definition at line 388 of file symfile.c.
References gdb_bfd_section_index(), place_section_arg::lowest, place_section_arg::offsets, section_offsets::offsets, and ULONGEST.
Referenced by default_symfile_offsets().
void print_transfer_performance (struct ui_file * stream, unsigned long data_count, unsigned long write_count, const struct timeval * start_time, const struct timeval * end_time)
Definition at line 2137 of file symfile.c.
References current_uiout, rate, ui_out_field_fmt(), ui_out_is_mi_like_p(), ui_out_text(), and ULONGEST.
Referenced by generic_load(), load_srec(), m32r_load(), and m32r_upload_command().
static void read_symbols (struct objfile * objfile, int add_flags) [static]
Definition at line 836 of file symfile.c.
References do_cleanups(), find_separate_debug_file_in_section(), make_cleanup_bfd_unref(), objfile_has_partial_symbols(), objfile::original_name, require_partial_symbols(), objfile::separate_debug_objfile, objfile::separate_debug_objfile_backlink, objfile::sf, sym_fns::sym_read, symbol_file_add_separate(), and SYMFILE_NO_READ.
Referenced by reread_symbols(), and syms_from_objfile_1().
static void read_target_long_array (CORE_ADDR memaddr, unsigned int * myaddr, int len, int size, enum bfd_endian byte_order) [static]
Definition at line 3407 of file symfile.c.
References extract_unsigned_integer(), len, and read_memory().
Referenced by simple_overlay_update_1(), and simple_read_overlay_table().
void relative_addr_info_to_section_offsets (struct section_offsets * section_offsets, int num_sections, const struct section_addr_info * addrs)
Definition at line 453 of file symfile.c.
References memset(), section_addr_info::num_sections, section_offsets::offsets, section_addr_info::other, and SIZEOF_N_SECTION_OFFSETS.
Referenced by default_symfile_offsets(), and objfile_relocate().
void reread_symbols (void)
Definition at line 2352 of file symfile.c.
References _, all_cleanups(), build_objfile_section_table(), clear_complaints(), clear_symtab_users(), clear_symtab_users_cleanup(), discard_cleanups(), do_cleanups(), error(), exec_bfd, exec_file_attach(), find_sym_fns(), objfile::flags, free_objfile_separate_debug(), objfile::free_psymtabs, gdb_bfd_open_maybe_remote(), gdb_bfd_unref(), objfile::global_psymbols, init_entry_point_info(), psymbol_allocation_list::list, make_cleanup(), make_cleanup_bfd_unref(), make_cleanup_free_objfile(), memcpy(), memset(), objfile::minimal_symbol_count, objfile::msymbol_demangled_hash, objfile::msymbol_hash, objfile::msymbols, objfile::mtime, objfile::next, objfile::num_sections, objfile::obfd, object_files, OBJF_PSYMTABS_READ, objfile_has_symbols(), objfile_name(), objfile::objfile_obstack, objfile_set_sym_fns(), objfiles_changed(), observer_notify_executable_changed(), observer_notify_new_objfile(), section_offsets::offsets, objfile::original_name, preserve_values(), printf_unfiltered(), psymbol_bcache_free(), psymbol_bcache_init(), objfile::psymbol_cache, objfile::psymtabs, objfile::psymtabs_addrmap, read_symbols(), reinit_frame_cache(), objfile::section_offsets, objfile::sections, objfile::separate_debug_objfile_backlink, set_objfile_per_bfd(), objfile::sf, SIZEOF_N_SECTION_OFFSETS, objfile::static_psymbols, sym_fns::sym_finish, sym_fns::sym_init, sym_fns::sym_new_init, symfile_complaints, symfile_objfile, objfile::symtabs, objfile::template_symbols, terminate_minimal_symbol_table(), VEC, VEC_cleanup, VEC_iterate, VEC_safe_push, wrap_here(), and xfree().
Referenced by attach_command_post_wait(), load_command(), remote_open_1(), and run_command_1().
int section_is_mapped (struct obj_section * osect)
Definition at line 2973 of file symfile.c.
References gdbarch_overlay_update(), gdbarch_overlay_update_p(), get_objfile_arch(), obj_section::objfile, overlay_cache_invalid, overlay_debugging, overlay_invalidate_all(), ovly_auto, obj_section::ovly_mapped, ovly_off, ovly_on, and section_is_overlay().
Referenced by bkpt_breakpoint_hit(), breakpoint_here_p(), breakpoint_thread_match(), find_pc_mapped_section(), find_pc_overlay(), insert_bp_location(), jump_command(), list_overlays_command(), regular_breakpoint_inserted_here_p(), remove_breakpoint_1(), skip_prologue_sal(), software_breakpoint_inserted_here_p(), sym_info(), and symbol_overlayed_address().
int section_is_overlay (struct obj_section * section)
Definition at line 2933 of file symfile.c.
References objfile::obfd, obj_section::objfile, overlay_debugging, and obj_section::the_bfd_section.
Referenced by address_info(), bkpt_breakpoint_hit(), breakpoint_here_p(), breakpoint_thread_match(), clear_command(), find_pc_overlay(), insert_bp_location(), jump_command(), map_overlay_command(), overlay_invalidate_all(), overlay_mapped_address(), overlay_unmapped_address(), pc_in_mapped_range(), pc_in_unmapped_range(), regular_breakpoint_inserted_here_p(), remove_breakpoint_1(), section_is_mapped(), simple_overlay_update(), skip_prologue_sal(), software_breakpoint_inserted_here_p(), spu_overlay_update(), sym_info(), and symbol_overlayed_address().
static int sections_overlap (struct obj_section * a, struct obj_section * b) [static]
Definition at line 3048 of file symfile.c.
References obj_section_addr, and obj_section_endaddr.
Referenced by map_overlay_command().
static int separate_debug_file_exists (const char * name, unsigned long crc, struct objfile * parent_objfile) [static]
Definition at line 1288 of file symfile.c.
References _, gdb_bfd_crc(), gdb_bfd_open_maybe_remote(), gdb_bfd_unref(), objfile::obfd, objfile_name(), and warning().
Referenced by find_separate_debug_file().
static void set_ext_lang_command (char * args, int from_tty, struct cmd_list_element * e) [static]
Definition at line 2646 of file symfile.c.
References _, add_filename_language(), error(), filename_language::ext, ext_args, fl_table_next, filename_language::lang, language_enum(), skip_spaces(), and xfree().
void set_initial_language (void)
Definition at line 1628 of file symfile.c.
References current_language, expected_language, language_c, language_of_main, language_unknown, lookup_symbol(), main_name(), name, set_language(), SYMBOL_LANGUAGE, and VAR_DOMAIN.
Referenced by follow_exec(), set_language_command(), and symbol_file_add_main_1().
static void show_debug_file_directory (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 1370 of file symfile.c.
References _, and fprintf_filtered().
static void show_ext_args (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 2636 of file symfile.c.
References _, and fprintf_filtered().
static void simple_free_overlay_table (void) [static]
Definition at line 3394 of file symfile.c.
References cache_novlys, cache_ovly_table, cache_ovly_table_base, and xfree().
Referenced by simple_read_overlay_table().
void simple_overlay_update (struct obj_section * osect)
Definition at line 3515 of file symfile.c.
References _, ALL_OBJSECTIONS, cache_novlys, cache_ovly_table, cache_ovly_table_base, error(), LMA, lookup_minimal_symbol(), MAPPED, objfile::obfd, obj_section::objfile, obj_section::ovly_mapped, section_is_overlay(), simple_overlay_update_1(), simple_read_overlay_table(), size, SYMBOL_VALUE_ADDRESS, obj_section::the_bfd_section, and VMA.
Referenced by m32r_gdbarch_init(), and moxie_gdbarch_init().
static int simple_overlay_update_1 (struct obj_section * osect) [static]
Definition at line 3475 of file symfile.c.
References gdbarch::byte_order, cache_novlys, cache_ovly_table, cache_ovly_table_base, gdbarch_byte_order(), gdbarch_long_bit(), get_objfile_arch(), LMA, MAPPED, objfile::obfd, obj_section::objfile, obj_section::ovly_mapped, read_target_long_array(), size, obj_section::the_bfd_section, and VMA.
Referenced by simple_overlay_update().
static int simple_read_overlay_table (void) [static]
Definition at line 3423 of file symfile.c.
References _, gdbarch::byte_order, cache_novlys, cache_ovly_table, cache_ovly_table_base, error(), gdbarch_byte_order(), gdbarch_long_bit(), get_objfile_arch(), lookup_bound_minimal_symbol(), lookup_minimal_symbol(), bound_minimal_symbol::minsym, bound_minimal_symbol::objfile, read_memory_integer(), read_target_long_array(), simple_free_overlay_table(), SYMBOL_VALUE_ADDRESS, and xmalloc().
Referenced by simple_overlay_update().
struct objfile* symbol_file_add (const char * name, int add_flags, struct section_addr_info * addrs, int flags) [read]
Definition at line 1223 of file symfile.c.
References do_cleanups(), make_cleanup_bfd_unref(), symbol_file_add_from_bfd(), and symfile_bfd_open().
Referenced by add_symbol_file_command(), follow_exec(), safe_symbol_file_add_stub(), and symbol_file_add_main_1().
struct objfile* symbol_file_add_from_bfd (bfd * abfd, const char * name, int add_flags, struct section_addr_info * addrs, int flags, struct objfile * parent) [read]
Definition at line 1211 of file symfile.c.
References symbol_file_add_with_addrs().
Referenced by jit_bfd_try_read_symtab(), macho_add_oso_symfile(), solib_read_symbols(), spu_symbol_file_add_from_memory(), symbol_file_add(), and symbol_file_add_from_memory().
void symbol_file_add_main (const char * args, int from_tty)
Definition at line 1244 of file symfile.c.
References symbol_file_add_main_1().
Referenced by add_inferior_command(), attach_command_post_wait(), captured_main(), clone_program_space(), irix_open_symbol_file_object(), open_symbol_file_object(), osf_open_symbol_file_object(), and som_open_symbol_file_object().
static void symbol_file_add_main_1 (const char * args, int from_tty, int flags) [static]
Definition at line 1250 of file symfile.c.
References current_inferior(), reinit_frame_cache(), set_initial_language(), symbol_file_add(), inferior::symfile_flags, SYMFILE_MAINLINE, SYMFILE_NO_READ, and SYMFILE_VERBOSE.
Referenced by symbol_file_add_main(), and symbol_file_command().
void symbol_file_add_separate (bfd * bfd, const char * name, int symfile_flags, struct objfile * objfile)
Definition at line 1184 of file symfile.c.
References build_section_addr_info_from_objfile(), do_cleanups(), objfile::flags, make_cleanup_free_section_addr_info(), new_objfile(), OBJF_READNOW, OBJF_REORDERED, OBJF_SHARED, OBJF_USERLOADED, and symbol_file_add_with_addrs().
Referenced by coff_symfile_read(), elf_symfile_read(), macho_symfile_read(), and read_symbols().
static struct objfile* symbol_file_add_with_addrs (bfd * abfd, const char * name, int add_flags, struct section_addr_info * addrs, int flags, struct objfile * parent) [static, read]
Definition at line 1080 of file symfile.c.
References _, add_separate_debug_objfile(), allocate_objfile(), deprecated_post_add_symbol_hook, deprecated_pre_add_symbol_hook, error(), quick_symbol_functions::expand_all_symtabs, gdb_flush(), gdb_stdout, have_full_symbols(), have_partial_symbols(), info_verbose, name, new_symfile_objfile(), OBJF_MAINLINE, OBJF_READNOW, objfile_has_symbols(), observer_notify_new_objfile(), printf_unfiltered(), sym_fns::qf, query(), readnow_symbol_files, objfile::sf, SYMFILE_MAINLINE, SYMFILE_NO_READ, SYMFILE_VERBOSE, syms_from_objfile(), and wrap_here().
Referenced by symbol_file_add_from_bfd(), and symbol_file_add_separate().
void symbol_file_clear (int from_tty)
Definition at line 1266 of file symfile.c.
References _, error(), free_all_objfiles(), gdb_assert, have_full_symbols(), have_partial_symbols(), no_shared_libraries(), objfile_name(), printf_unfiltered(), query(), and symfile_objfile.
Referenced by gdb_clear_file(), and symbol_file_command().
void symbol_file_command (char * args, int from_tty)
Definition at line 1578 of file symfile.c.
References _, do_cleanups(), dont_repeat(), error(), flags, gdb_buildargv(), make_cleanup_freeargv(), name, OBJF_READNOW, OBJF_USERLOADED, symbol_file_add_main_1(), and symbol_file_clear().
Referenced by file_command().
CORE_ADDR symbol_overlayed_address (CORE_ADDR address, struct obj_section * section)
Definition at line 3101 of file symfile.c.
References overlay_debugging, overlay_unmapped_address(), section_is_mapped(), and section_is_overlay().
Referenced by default_read_var_value(), and write_exp_msymbol().
bfd* symfile_bfd_open (const char * cname)
Definition at line 1676 of file symfile.c.
References _, do_cleanups(), error(), gdb_bfd_open(), gnutarget, make_cleanup(), make_cleanup_bfd_unref(), name, openp(), OPF_RETURN_REALPATH, OPF_TRY_CWD_FIRST, perror_with_name(), remote_bfd_open(), remote_filename_p(), and xfree().
Referenced by coff_symfile_read(), elf_symfile_read(), and symbol_file_add().
static void symfile_dummy_outputs (bfd * abfd, asection * sectp, void * dummy) [static]
Definition at line 3575 of file symfile.c.
Referenced by default_symfile_relocate().
static void symfile_find_segment_sections (struct objfile * objfile) [static]
Definition at line 3704 of file symfile.c.
References free_symfile_segment_data(), get_symfile_segment_data(), symfile_segment_data::num_segments, objfile::obfd, objfile::sect_index_bss, objfile::sect_index_data, objfile::sect_index_rodata, objfile::sect_index_text, and symfile_segment_data::segment_info.
Referenced by init_objfile_sect_indices().
int symfile_map_offsets_to_segments (bfd * abfd, const struct symfile_segment_data * data, struct section_offsets * offsets, int num_segment_bases, const CORE_ADDR * segment_bases)
Definition at line 3662 of file symfile.c.
References gdb_assert, symfile_segment_data::num_segments, section_offsets::offsets, symfile_segment_data::segment_bases, and symfile_segment_data::segment_info.
Referenced by get_offsets(), and solib_target_relocate_section_addresses().
bfd_byte* symfile_relocate_debug_section (struct objfile * objfile, asection * sectp, bfd_byte * buf)
Definition at line 3618 of file symfile.c.
References gdb_assert, objfile::sf, and sym_fns::sym_relocate.
Referenced by dbx_read_symtab(), dwarf2_read_section(), and elfstab_build_psymtabs().
static void syms_from_objfile (struct objfile * objfile, struct section_addr_info * addrs, int add_flags) [static]
Definition at line 1025 of file symfile.c.
References init_entry_point_info(), and syms_from_objfile_1().
Referenced by symbol_file_add_with_addrs().
static void syms_from_objfile_1 (struct objfile * objfile, struct section_addr_info * addrs, int add_flags) [static]
Definition at line 935 of file symfile.c.
References addr_info_make_relative(), alloc_section_addr_info(), clear_complaints(), clear_symtab_users_cleanup(), discard_cleanups(), find_sym_fns(), free_objfile(), gdb_assert, gdb_bfd_count_sections(), make_cleanup(), make_cleanup_free_objfile(), memset(), section_addr_info::num_sections, objfile::num_sections, objfile::obfd, objfile::objfile_obstack, objfile_set_sym_fns(), read_symbols(), objfile::section_offsets, objfile::sf, size, SIZEOF_N_SECTION_OFFSETS, sym_fns::sym_init, sym_fns::sym_new_init, sym_fns::sym_offsets, symfile_complaints, SYMFILE_MAINLINE, symfile_objfile, SYMFILE_VERBOSE, and xfree().
Referenced by syms_from_objfile().
static void terminate_after_last_dir_separator (char * path) [static]
Definition at line 1482 of file symfile.c.
Referenced by find_separate_debug_file_by_debuglink().
static void unmap_overlay_command (char * args, int from_tty) [static]
Definition at line 3260 of file symfile.c.
References _, ALL_OBJSECTIONS, error(), objfile::obfd, overlay_debugging, obj_section::ovly_mapped, and obj_section::the_bfd_section.
static VEC (registered_sym_fns) [static]
Definition at line 144 of file symfile.c.
References auto_solib_add, currently_reading_symtab, and gdb_assert.
Variable Documentation
unsigned cache_novlys = 0 [static]
Definition at line 3384 of file symfile.c.
Referenced by simple_free_overlay_table(), simple_overlay_update(), simple_overlay_update_1(), and simple_read_overlay_table().
unsigned(* cache_ovly_table)[4] = 0 [static]
Definition at line 3383 of file symfile.c.
Referenced by simple_free_overlay_table(), simple_overlay_update(), simple_overlay_update_1(), and simple_read_overlay_table().
CORE_ADDR cache_ovly_table_base = 0 [static]
Definition at line 3385 of file symfile.c.
Referenced by simple_free_overlay_table(), simple_overlay_update(), simple_overlay_update_1(), and simple_read_overlay_table().
char* debug_file_directory = NULL
Definition at line 1368 of file symfile.c.
Referenced by build_id_to_debug_bfd(), captured_main(), find_separate_debug_file(), open_dwo_file(), open_dwp_file(), try_open_dwop_file(), and VEC().
void(* deprecated_post_add_symbol_hook)(void)
Definition at line 79 of file symfile.c.
Referenced by gdbtk_add_hooks(), and symbol_file_add_with_addrs().
void(* deprecated_pre_add_symbol_hook)(const char *)
Definition at line 78 of file symfile.c.
Referenced by gdbtk_add_hooks(), and symbol_file_add_with_addrs().
void(* deprecated_show_load_progress)(const char *section, unsigned long section_sent, unsigned long section_size, unsigned long total_sent, unsigned long total_size)
Definition at line 73 of file symfile.c.
Referenced by load_progress(), and mi_interpreter_resume().
int(* deprecated_ui_load_progress_hook)(const char *section, unsigned long num)
Definition at line 71 of file symfile.c.
Referenced by gdbtk_add_hooks(), load_progress(), and load_srec().
char* ext_args [static]
Definition at line 2634 of file symfile.c.
Referenced by set_ext_lang_command().
filename_language* filename_language_table [static]
Definition at line 2615 of file symfile.c.
int fl_table_next [static]
Definition at line 2616 of file symfile.c.
Referenced by add_filename_language(), deduce_language_from_filename(), info_ext_lang_command(), init_filename_language_table(), and set_ext_lang_command().
int fl_table_size [static]
Definition at line 2616 of file symfile.c.
Referenced by add_filename_language(), and init_filename_language_table().
int overlay_cache_invalid = 0
Definition at line 2926 of file symfile.c.
Referenced by fetch_inferior_event(), load_command(), prepare_for_detach(), section_is_mapped(), and wait_for_inferior().
enum overlay_debugging_state overlay_debugging = ovly_off
Definition at line 2925 of file symfile.c.
Referenced by agent_command_1(), bkpt_breakpoint_hit(), breakpoint_has_pc(), breakpoint_here_p(), breakpoint_thread_match(), build_address_symbolic(), create_overlay_event_breakpoint(), default_read_var_value(), find_pc_mapped_section(), find_pc_overlay(), find_pc_sect_psymtab(), insert_bp_location(), insert_section_p(), list_overlays_command(), maint_agent_printf_command(), map_overlay_command(), memory_xfer_partial_1(), overlay_auto_command(), overlay_manual_command(), overlay_off_command(), regular_breakpoint_inserted_here_p(), remove_breakpoint_1(), section_is_mapped(), section_is_overlay(), software_breakpoint_inserted_here_p(), symbol_overlayed_address(), unmap_overlay_command(), update_global_location_list(), and write_exp_msymbol().
struct cmd_list_element* overlaylist [static]
Definition at line 3339 of file symfile.c.
int readnow_symbol_files
Definition at line 84 of file symfile.c.
Referenced by captured_main(), and symbol_file_add_with_addrs().
int validate_download = 0 [static]
Definition at line 1866 of file symfile.c.
Referenced by load_progress().