GDB (xrefs): /home/stan/gdb/src/gdb/symmisc.c File Reference
/home/stan/gdb/src/gdb/symmisc.c File Reference
#include "defs.h"
#include "symtab.h"
#include "gdbtypes.h"
#include "bfd.h"
#include "filenames.h"
#include "symfile.h"
#include "objfiles.h"
#include "breakpoint.h"
#include "command.h"
#include "gdb_obstack.h"
#include "exceptions.h"
#include "language.h"
#include "bcache.h"
#include "block.h"
#include "gdb_regex.h"
#include "gdb_stat.h"
#include "dictionary.h"
#include "typeprint.h"
#include "gdbcmd.h"
#include "source.h"
#include "gdb_string.h"
#include "readline/readline.h"
#include "psymtab.h"
Classes
struct print_symbol_args
Defines
#define DEV_TTY "/dev/tty"
Functions
static int block_depth (struct block *)
void _initialize_symmisc (void)
static int print_symbol (void *)
void print_symbol_bcache_statistics (void)
void print_objfile_statistics (void)
static void dump_objfile (struct objfile *objfile)
static void dump_msymbols (struct objfile *objfile, struct ui_file *outfile)
static void dump_symtab_1 (struct objfile *objfile, struct symtab *symtab, struct ui_file *outfile)
static void dump_symtab (struct objfile *objfile, struct symtab *symtab, struct ui_file *outfile)
static void maintenance_print_symbols (char *args, int from_tty)
static void maintenance_print_msymbols (char *args, int from_tty)
static void maintenance_print_objfiles (char *regexp, int from_tty)
static void maintenance_info_symtabs (char *regexp, int from_tty)
static void maintenance_check_symtabs (char *ignore, int from_tty)
static int maintenance_expand_name_matcher (const char *symname, void *data)
static int maintenance_expand_file_matcher (const char *filename, void *data, int basenames)
static void maintenance_expand_symtabs (char *args, int from_tty)
Variables
FILE * std_in
FILE * std_out
FILE * std_err
Define Documentation
#define DEV_TTY "/dev/tty"
Definition at line 47 of file symmisc.c.
Referenced by maintenance_print_msymbols(), and maintenance_print_symbols().
Function Documentation
void _initialize_symmisc (void)
static int block_depth (struct block * block) [static]
Definition at line 911 of file symmisc.c.
References BLOCK_SUPERBLOCK.
Referenced by ada_add_local_symbols(), and dump_symtab_1().
static void dump_msymbols (struct objfile * objfile, struct ui_file * outfile) [static]
Definition at line 199 of file symmisc.c.
References _, ALL_OBJFILE_MSYMBOLS, minimal_symbol::filename, fprintf_filtered(), fputs_filtered(), get_objfile_arch(), objfile::minimal_symbol_count, mst_abs, mst_bss, mst_data, mst_file_bss, mst_file_data, mst_file_text, mst_solib_trampoline, mst_text, mst_text_gnu_ifunc, mst_unknown, MSYMBOL_TYPE, objfile::obfd, objfile_name(), paddress(), objfile::sections, SYMBOL_DEMANGLED_NAME, SYMBOL_LINKAGE_NAME, SYMBOL_OBJ_SECTION, SYMBOL_VALUE_ADDRESS, obj_section::the_bfd_section, and warning().
Referenced by maintenance_print_msymbols().
static void dump_objfile (struct objfile * objfile) [static]
Definition at line 161 of file symmisc.c.
References quick_symbol_functions::dump, gdb_print_host_address(), gdb_stdout, objfile::minimal_symbol_count, symtab::next, objfile::obfd, symtab::objfile, objfile_name(), printf_filtered(), sym_fns::qf, objfile::sf, symtab_to_filename_for_display(), objfile::symtabs, and wrap_here().
Referenced by maintenance_print_objfiles().
static void dump_symtab (struct objfile * objfile, struct symtab * symtab, struct ui_file * outfile) [static]
Definition at line 385 of file symmisc.c.
References dump_symtab_1(), symtab::language, language_auto, language_unknown, and set_language().
Referenced by maintenance_print_symbols().
static void dump_symtab_1 (struct objfile * objfile, struct symtab * symtab, struct ui_file * outfile) [static]
Definition at line 285 of file symmisc.c.
References ALL_DICT_SYMBOLS, block_depth(), BLOCK_DICT, BLOCK_END, BLOCK_FUNCTION, BLOCK_START, BLOCK_SUPERBLOCK, BLOCKVECTOR, BLOCKVECTOR_BLOCK, BLOCKVECTOR_NBLOCKS, catch_errors(), print_symbol_args::depth, dict_size(), symtab::dirname, fprintf_filtered(), fputs_filtered(), gdb_print_host_address(), print_symbol_args::gdbarch, get_objfile_arch(), linetable::item, symtab::language, language_str(), len, linetable_entry::line, LINETABLE, linetable::nitems, objfile_name(), print_symbol_args::outfile, paddress(), linetable_entry::pc, symtab::primary, print_spaces(), print_symbol(), RETURN_MASK_ERROR, print_symbol_args::symbol, SYMBOL_DEMANGLED_NAME, SYMBOL_LINKAGE_NAME, and symtab_to_filename_for_display().
Referenced by dump_symtab().
static void maintenance_check_symtabs (char * ignore, int from_tty) [static]
Definition at line 786 of file symmisc.c.
References ALL_OBJFILE_SYMTABS, ALL_PSPACE_OBJFILES, ALL_PSPACES, symtab::blockvector, host_address_to_string(), objfile_name(), printf_filtered(), QUIT, symtab_to_filename_for_display(), and wrap_here().
static int maintenance_expand_file_matcher (const char * filename, void * data, int basenames) [static]
Definition at line 847 of file symmisc.c.
References QUIT.
Referenced by maintenance_expand_symtabs().
static int maintenance_expand_name_matcher (const char * symname, void * data) [static]
Definition at line 837 of file symmisc.c.
Referenced by maintenance_expand_symtabs().
static void maintenance_expand_symtabs (char * args, int from_tty) [static]
Definition at line 867 of file symmisc.c.
References _, ALL_DOMAIN, ALL_PSPACE_OBJFILES, ALL_PSPACES, do_cleanups(), error(), quick_symbol_functions::expand_symtabs_matching, gdb_buildargv(), maintenance_expand_file_matcher(), maintenance_expand_name_matcher(), make_cleanup_freeargv(), sym_fns::qf, re_comp(), and objfile::sf.
static void maintenance_info_symtabs (char * regexp, int from_tty) [static]
Definition at line 715 of file symmisc.c.
References ALL_OBJFILE_SYMTABS, ALL_PSPACE_OBJFILES, ALL_PSPACES, symtab::blockvector, symtab::debugformat, symtab::dirname, dont_repeat(), symtab::fullname, host_address_to_string(), symtab::linetable, objfile_name(), symtab::primary, printf_filtered(), QUIT, re_comp(), symtab_to_filename_for_display(), and wrap_here().
static void maintenance_print_msymbols (char * args, int from_tty) [static]
Definition at line 635 of file symmisc.c.
References _, ALL_PSPACE_OBJFILES, ALL_PSPACES, DEV_TTY, do_cleanups(), dont_repeat(), dump_msymbols(), error(), fprintf_filtered(), gdb_buildargv(), gdb_fopen(), gdb_realpath(), make_cleanup(), make_cleanup_freeargv(), make_cleanup_ui_file_delete(), objfile_name(), perror_with_name(), QUIT, and xfree().
static void maintenance_print_objfiles (char * regexp, int from_tty) [static]
Definition at line 692 of file symmisc.c.
References ALL_PSPACE_OBJFILES, ALL_PSPACES, dont_repeat(), dump_objfile(), objfile_name(), QUIT, and re_comp().
static void maintenance_print_symbols (char * args, int from_tty) [static]
Definition at line 408 of file symmisc.c.
References _, ALL_SYMTABS, DEV_TTY, do_cleanups(), dont_repeat(), dump_symtab(), error(), gdb_buildargv(), gdb_fopen(), make_cleanup(), make_cleanup_freeargv(), make_cleanup_ui_file_delete(), perror_with_name(), QUIT, symtab_to_filename_for_display(), and xfree().
void print_objfile_statistics (void)
Definition at line 99 of file symmisc.c.
References _, ALL_OBJFILE_SYMTABS, ALL_PSPACE_OBJFILES, ALL_PSPACES, bcache_memory_used(), objfile_per_bfd_storage::filename_cache, symtab::linetable, objfile_per_bfd_storage::macro_cache, objfile_name(), objfile::objfile_obstack, OBJSTAT, objfile::per_bfd, symtab::primary, quick_symbol_functions::print_stats, printf_filtered(), psymbol_bcache_get_bcache(), objfile::psymbol_cache, sym_fns::qf, QUIT, objfile::sf, and objfile_per_bfd_storage::storage_obstack.
Referenced by maintenance_print_statistics().
static int print_symbol (void * args) [static]
Definition at line 462 of file symmisc.c.
References BLOCK_END, BLOCK_START, check_typedef(), print_symbol_args::depth, fprintf_filtered(), fputs_filtered(), gdb_print_host_address(), hex_string(), LA_PRINT_TYPE, LABEL_DOMAIN, LOC_ARG, LOC_BLOCK, LOC_COMPUTED, LOC_CONST, LOC_CONST_BYTES, LOC_LABEL, LOC_LOCAL, LOC_OPTIMIZED_OUT, LOC_REF_ARG, LOC_REGISTER, LOC_REGPARM_ADDR, LOC_STATIC, LOC_TYPEDEF, LOC_UNRESOLVED, paddress(), plongest(), print_spaces(), STRUCT_DOMAIN, SYMBOL_BLOCK_VALUE, SYMBOL_CLASS, SYMBOL_DOMAIN, SYMBOL_IS_ARGUMENT, SYMBOL_LINKAGE_NAME, SYMBOL_OBJ_SECTION, SYMBOL_OBJFILE, SYMBOL_PRINT_NAME, SYMBOL_TYPE, SYMBOL_VALUE, SYMBOL_VALUE_ADDRESS, SYMBOL_VALUE_BYTES, obj_section::the_bfd_section, TYPE_CODE, TYPE_CODE_ENUM, TYPE_CODE_STRUCT, TYPE_LENGTH, type_print_raw_options, and TYPE_TAG_NAME.
Referenced by dump_symtab_1().
void print_symbol_bcache_statistics (void)
Definition at line 78 of file symmisc.c.
References _, ALL_PSPACE_OBJFILES, ALL_PSPACES, objfile_per_bfd_storage::filename_cache, objfile_per_bfd_storage::macro_cache, objfile_name(), objfile::per_bfd, print_bcache_statistics(), printf_filtered(), psymbol_bcache_get_bcache(), objfile::psymbol_cache, and QUIT.
Referenced by maintenance_print_statistics().
Variable Documentation
FILE* std_err
Definition at line 58 of file symmisc.c.
FILE* std_in
Definition at line 56 of file symmisc.c.
FILE* std_out
Definition at line 57 of file symmisc.c.