GDB (xrefs): /home/stan/gdb/src/gdb/symtab.c File Reference
/home/stan/gdb/src/gdb/symtab.c File Reference
#include "defs.h"
#include "symtab.h"
#include "gdbtypes.h"
#include "gdbcore.h"
#include "frame.h"
#include "target.h"
#include "value.h"
#include "symfile.h"
#include "objfiles.h"
#include "gdbcmd.h"
#include "gdb_regex.h"
#include "expression.h"
#include "language.h"
#include "demangle.h"
#include "inferior.h"
#include "source.h"
#include "filenames.h"
#include "objc-lang.h"
#include "d-lang.h"
#include "ada-lang.h"
#include "go-lang.h"
#include "p-lang.h"
#include "addrmap.h"
#include "cli/cli-utils.h"
#include "hashtab.h"
#include "gdb_obstack.h"
#include "block.h"
#include "dictionary.h"
#include <sys/types.h>
#include <fcntl.h>
#include "gdb_string.h"
#include "gdb_stat.h"
#include <ctype.h>
#include "cp-abi.h"
#include "cp-support.h"
#include "observer.h"
#include "gdb_assert.h"
#include "solist.h"
#include "macrotab.h"
#include "macroscope.h"
#include "psymtab.h"
#include "parser-defs.h"
Classes
struct demangled_name_entry
struct global_sym_lookup_data
struct filename_seen_cache
struct output_source_filename_data
struct search_symbols_data
struct add_name_data
struct add_partial_filename_data
Defines
#define JAVA_PREFIX "##JAVA$$"
#define JAVA_PREFIX_LEN 8
#define INITIAL_FILENAME_SEEN_CACHE_SIZE 100
#define COMPLETION_LIST_ADD_SYMBOL(symbol, sym_text, len, text, word)
#define MAX_SYMBOL_IMPLS (LOC_FINAL_VALUE + 10)
Functions
static void rbreak_command (char *, int)
static void types_info (char *, int)
static void functions_info (char *, int)
static void variables_info (char *, int)
static void sources_info (char *, int)
static int find_line_common (struct linetable *, int, int *, int)
static struct symbol * lookup_symbol_aux (const char *name, const struct block *block, const domain_enum domain, enum language language, struct field_of_this_result *is_a_field_of_this)
static struct symbol * lookup_symbol_aux_local (const char *name, const struct block *block, const domain_enum domain, enum language language)
static struct symbol * lookup_symbol_aux_symtabs (int block_index, const char *name, const domain_enum domain)
static struct symbol * lookup_symbol_aux_quick (struct objfile *objfile, int block_index, const char *name, const domain_enum domain)
void _initialize_symtab (void)
const char * multiple_symbols_select_mode (void)
const char * domain_name (domain_enum e)
const char * search_domain_name (enum search_domain e)
int compare_filenames_for_search (const char *filename, const char *search_name)
int iterate_over_some_symtabs (const char *name, const char *real_path, int(*callback)(struct symtab *symtab, void *data), void *data, struct symtab *first, struct symtab *after_last)
void iterate_over_symtabs (const char *name, int(*callback)(struct symtab *symtab, void *data), void *data)
static int lookup_symtab_callback (struct symtab *symtab, void *data)
struct symtab * lookup_symtab (const char *name)
char * gdb_mangle_name (struct type *type, int method_id, int signature_id)
static void symbol_init_cplus_specific (struct general_symbol_info *gsymbol, struct obstack *obstack)
void symbol_set_demangled_name (struct general_symbol_info *gsymbol, const char *name, struct obstack *obstack)
const char * symbol_get_demangled_name (const struct general_symbol_info *gsymbol)
void symbol_set_language (struct general_symbol_info *gsymbol, enum language language, struct obstack *obstack)
static hashval_t hash_demangled_name_entry (const void *data)
static int eq_demangled_name_entry (const void *a, const void *b)
static void create_demangled_names_hash (struct objfile *objfile)
static char * symbol_find_demangled_name (struct general_symbol_info *gsymbol, const char *mangled)
void symbol_set_names (struct general_symbol_info *gsymbol, const char *linkage_name, int len, int copy_name, struct objfile *objfile)
const char * symbol_natural_name (const struct general_symbol_info *gsymbol)
const char * symbol_demangled_name (const struct general_symbol_info *gsymbol)
const char * symbol_search_name (const struct general_symbol_info *gsymbol)
void init_sal (struct symtab_and_line *sal)
int matching_obj_sections (struct obj_section *obj_first, struct obj_section *obj_second)
struct symtab * find_pc_sect_symtab_via_partial (CORE_ADDR pc, struct obj_section *section)
void fixup_section (struct general_symbol_info *ginfo, CORE_ADDR addr, struct objfile *objfile)
struct symbol * fixup_symbol_section (struct symbol *sym, struct objfile *objfile)
struct cleanup * demangle_for_lookup (const char *name, enum language lang, const char **result_name)
struct symbol * lookup_symbol_in_language (const char *name, const struct block *block, const domain_enum domain, enum language lang, struct field_of_this_result *is_a_field_of_this)
struct symbol * lookup_symbol (const char *name, const struct block *block, domain_enum domain, struct field_of_this_result *is_a_field_of_this)
struct symbol * lookup_language_this (const struct language_defn *lang, const struct block *block)
static int check_field (struct type *type, const char *name, struct field_of_this_result *is_a_field_of_this)
static struct symbol * lookup_symbol_aux (const char *name, const struct block *block, const domain_enum domain, enum language language, struct field_of_this_result *is_a_field_of_this)
struct symbol * lookup_static_symbol_aux (const char *name, const domain_enum domain)
static struct symbol * lookup_symbol_aux_local (const char *name, const struct block *block, const domain_enum domain, enum language language)
struct objfile * lookup_objfile_from_block (const struct block *block)
struct symbol * lookup_symbol_aux_block (const char *name, const struct block *block, const domain_enum domain)
struct symbol * lookup_global_symbol_from_objfile (const struct objfile *main_objfile, const char *name, const domain_enum domain)
static struct symbol * lookup_symbol_aux_objfile (struct objfile *objfile, int block_index, const char *name, const domain_enum domain)
static struct symbol * lookup_symbol_in_objfile_from_linkage_name (struct objfile *objfile, const char *linkage_name, domain_enum domain)
static void ATTRIBUTE_NORETURN error_in_psymtab_expansion (int kind, const char *name, struct symtab *symtab)
struct symbol * basic_lookup_symbol_nonlocal (const char *name, const struct block *block, const domain_enum domain)
struct symbol * lookup_symbol_static (const char *name, const struct block *block, const domain_enum domain)
static int lookup_symbol_global_iterator_cb (struct objfile *objfile, void *cb_data)
struct symbol * lookup_symbol_global (const char *name, const struct block *block, const domain_enum domain)
int symbol_matches_domain (enum language symbol_language, domain_enum symbol_domain, domain_enum domain)
struct type * lookup_transparent_type (const char *name)
static struct type * basic_lookup_transparent_type_quick (struct objfile *objfile, int kind, const char *name)
struct type * basic_lookup_transparent_type (const char *name)
struct symbol * lookup_block_symbol (const struct block *block, const char *name, const domain_enum domain)
void iterate_over_symbols (const struct block *block, const char *name, const domain_enum domain, symbol_found_callback_ftype *callback, void *data)
struct symtab * find_pc_sect_symtab (CORE_ADDR pc, struct obj_section *section)
struct symtab * find_pc_symtab (CORE_ADDR pc)
struct symtab_and_line find_pc_sect_line (CORE_ADDR pc, struct obj_section *section, int notcurrent)
struct symtab_and_line find_pc_line (CORE_ADDR pc, int notcurrent)
struct symtab * find_line_symtab (struct symtab *symtab, int line, int *index, int *exact_match)
VEC (CORE_ADDR)
int find_line_pc (struct symtab *symtab, int line, CORE_ADDR *pc)
int find_line_pc_range (struct symtab_and_line sal, CORE_ADDR *startptr, CORE_ADDR *endptr)
int find_pc_line_pc_range (CORE_ADDR pc, CORE_ADDR *startptr, CORE_ADDR *endptr)
static CORE_ADDR skip_prologue_using_lineinfo (CORE_ADDR func_addr, struct symtab *symtab)
struct symtab_and_line find_function_start_sal (struct symbol *sym, int funfirstline)
void skip_prologue_sal (struct symtab_and_line *sal)
static char * operator_chars (char *p, char **end)
static struct filename_seen_cache * create_filename_seen_cache (void)
static void clear_filename_seen_cache (struct filename_seen_cache *cache)
static void delete_filename_seen_cache (void *ptr)
static int filename_seen (struct filename_seen_cache *cache, const char *file, int add)
static void output_source_filename (const char *name, struct output_source_filename_data *data)
static void output_partial_symbol_filename (const char *filename, const char *fullname, void *data)
static int file_matches (const char *file, char *files[], int nfiles, int basenames)
void free_search_symbols (struct symbol_search *symbols)
static void do_free_search_symbols_cleanup (void *symbolsp)
struct cleanup * make_cleanup_free_search_symbols (struct symbol_search **symbolsp)
static int compare_search_syms (const void *sa, const void *sb)
static void sort_search_symbols_remove_dups (struct symbol_search *found, int nfound, struct symbol_search **new_head, struct symbol_search **new_tail)
static int search_symbols_file_matches (const char *filename, void *user_data, int basenames)
static int search_symbols_name_matches (const char *symname, void *user_data)
void search_symbols (char *regexp, enum search_domain kind, int nfiles, char *files[], struct symbol_search **matches)
static void print_symbol_info (enum search_domain kind, struct symtab *s, struct symbol *sym, int block, const char *last)
static void print_msymbol_info (struct bound_minimal_symbol msymbol)
static void symtab_symbol_info (char *regexp, enum search_domain kind, int from_tty)
void rbreak_command_wrapper (char *regexp, int from_tty)
static void do_end_rbreak_breakpoints (void *ignore)
static int compare_symbol_name (const char *name, const char *sym_text, int sym_text_len)
static void free_completion_list (VEC(char_ptr)**list_ptr)
static void do_free_completion_list (void *list)
static VEC (char_ptr)
static void completion_list_objc_symbol (struct minimal_symbol *msymbol, const char *sym_text, int sym_text_len, const char *text, const char *word)
static const char * language_search_unquoted_string (const char *text, const char *p)
static void completion_list_add_fields (struct symbol *sym, const char *sym_text, int sym_text_len, const char *text, const char *word)
static void add_macro_name (const char *name, const struct macro_definition *ignore, struct macro_source_file *ignore2, int ignore3, void *user_data)
static int expand_partial_symbol_name (const char *name, void *user_data)
static void add_filename_to_list (const char *fname, const char *text, const char *word, VEC(char_ptr)**list)
static int not_interesting_fname (const char *fname)
static void maybe_add_partial_symtab_filename (const char *filename, const char *fullname, void *user_data)
int in_prologue (struct gdbarch *gdbarch, CORE_ADDR pc, CORE_ADDR func_start)
CORE_ADDR skip_prologue_using_sal (struct gdbarch *gdbarch, CORE_ADDR func_addr)
void set_main_name (const char *name)
static void find_main_name (void)
char * main_name (void)
static void symtab_observer_executable_changed (void)
int producer_is_realview (const char *producer)
gdb_static_assert (MAX_SYMBOL_IMPLS<=(1<< SYMBOL_ACLASS_BITS))
int register_symbol_computed_impl (enum address_class aclass, const struct symbol_computed_ops *ops)
int register_symbol_block_impl (enum address_class aclass, const struct symbol_block_ops *ops)
int register_symbol_register_impl (enum address_class aclass, const struct symbol_register_ops *ops)
static void initialize_ordinary_address_classes (void)
void initialize_symbol (struct symbol *sym)
struct symbol * allocate_symbol (struct objfile *objfile)
struct template_symbol * allocate_template_symbol (struct objfile *objfile)
Variables
int symtab_create_debug = 0
int basenames_may_differ = 0
const char multiple_symbols_ask [] = "ask"
const char multiple_symbols_all [] = "all"
const char multiple_symbols_cancel [] = "cancel"
static const char *const multiple_symbols_modes []
static const char * multiple_symbols_mode = multiple_symbols_all
struct block * block_found
static char * name_of_main
enum language language_of_main = language_unknown
static int next_aclass_value = LOC_FINAL_VALUE
static struct symbol_impl symbol_impl [MAX_SYMBOL_IMPLS]
struct symbol_impl * symbol_impls = &symbol_impl[0]
Define Documentation
#define COMPLETION_LIST_ADD_SYMBOL (symbol, sym_text, len, text, word)
Value:
completion_list_add_name \
        (SYMBOL_NATURAL_NAME (symbol), (sym_text), (len), (text), (word))
#define INITIAL_FILENAME_SEEN_CACHE_SIZE 100
Definition at line 3123 of file symtab.c.
Referenced by create_filename_seen_cache().
#define JAVA_PREFIX "##JAVA$$"
Definition at line 709 of file symtab.c.
Referenced by symbol_set_names().
#define JAVA_PREFIX_LEN 8
Definition at line 710 of file symtab.c.
Referenced by symbol_set_names().
#define MAX_SYMBOL_IMPLS (LOC_FINAL_VALUE + 10)
Definition at line 5076 of file symtab.c.
Referenced by register_symbol_block_impl(), register_symbol_computed_impl(), and register_symbol_register_impl().
Function Documentation
void _initialize_symtab (void)
static void add_filename_to_list (const char * fname, const char * text, const char * word, VEC(char_ptr)** list) [static]
Definition at line 4617 of file symtab.c.
References VEC_safe_push, word, and xmalloc().
Referenced by maybe_add_partial_symtab_filename().
static void add_macro_name (const char * name, const struct macro_definition * ignore, struct macro_source_file * ignore2, int ignore3, void * user_data) [static]
Definition at line 4219 of file symtab.c.
References add_name_data::sym_text, add_name_data::sym_text_len, add_name_data::text, and add_name_data::word.
struct symbol* allocate_symbol (struct objfile * objfile) [read]
Definition at line 5188 of file symtab.c.
References objfile::objfile_obstack, OBSTACK_ZALLOC, and SYMBOL_SECTION.
Referenced by add_class_symbol(), coff_read_enum_type(), common_block_end(), define_symbol(), finalize_symtab(), fixup_go_packaging(), new_symbol(), new_symbol_full(), parse_symbol(), patch_block_stabs(), process_coff_symbol(), and read_enum_type().
struct template_symbol* allocate_template_symbol (struct objfile * objfile) [read]
Definition at line 5202 of file symtab.c.
References template_symbol::base, objfile::objfile_obstack, OBSTACK_ZALLOC, and SYMBOL_SECTION.
Referenced by read_func_scope().
struct symbol* basic_lookup_symbol_nonlocal (const char * name, const struct block * block, const domain_enum domain) [read]
Definition at line 1724 of file symtab.c.
References lookup_symbol_global(), and lookup_symbol_static().
struct type* basic_lookup_transparent_type (const char * name) [read]
Definition at line 1918 of file symtab.c.
References ALL_OBJFILE_PRIMARY_SYMTABS, ALL_OBJFILES, basic_lookup_transparent_type_quick(), BLOCKVECTOR, BLOCKVECTOR_BLOCK, GLOBAL_BLOCK, lookup_block_symbol(), STATIC_BLOCK, STRUCT_DOMAIN, SYMBOL_TYPE, and TYPE_IS_OPAQUE.
Referenced by cp_lookup_transparent_type(), and cp_lookup_transparent_type_loop().
static struct type* basic_lookup_transparent_type_quick (struct objfile * objfile, int kind, const char * name) [static, read]
Definition at line 1885 of file symtab.c.
References BLOCKVECTOR, BLOCKVECTOR_BLOCK, error_in_psymtab_expansion(), lookup_block_symbol(), quick_symbol_functions::lookup_symbol, sym_fns::qf, objfile::sf, STRUCT_DOMAIN, SYMBOL_TYPE, and TYPE_IS_OPAQUE.
Referenced by basic_lookup_transparent_type().
static int check_field (struct type * type, const char * name, struct field_of_this_result * is_a_field_of_this) [static]
Definition at line 1327 of file symtab.c.
References CHECK_TYPEDEF, field_of_this_result::field, field_of_this_result::fn_field, strcmp_iw(), type, field_of_this_result::type, TYPE_BASECLASS, TYPE_FIELD, TYPE_FIELD_NAME, TYPE_FN_FIELDLIST, TYPE_FN_FIELDLIST_NAME, TYPE_N_BASECLASSES, TYPE_NFIELDS, and TYPE_NFN_FIELDS.
Referenced by lookup_symbol_aux().
static void clear_filename_seen_cache (struct filename_seen_cache * cache) [static]
Definition at line 3144 of file symtab.c.
References filename_seen_cache::tab.
Referenced by sources_info().
int compare_filenames_for_search (const char * filename, const char * search_name)
Definition at line 183 of file symtab.c.
References len.
Referenced by dw2_map_symtabs_matching_filename(), file_matches(), function_name_is_marked_for_skip(), iterate_over_some_symtabs(), and partial_map_symtabs_matching_filename().
static int compare_search_syms (const void * sa, const void * sb) [static]
Definition at line 3334 of file symtab.c.
References symbol_search::block, symtab::filename, symbol_search::symbol, SYMBOL_PRINT_NAME, and symbol_search::symtab.
Referenced by sort_search_symbols_remove_dups().
static int compare_symbol_name (const char * name, const char * sym_text, int sym_text_len) [static]
Definition at line 3983 of file symtab.c.
References case_sensitive_on, and int.
Referenced by expand_partial_symbol_name(), and VEC().
static void completion_list_add_fields (struct symbol * sym, const char * sym_text, int sym_text_len, const char * text, const char * word) [static]
Definition at line 4186 of file symtab.c.
References LOC_TYPEDEF, SYMBOL_CLASS, SYMBOL_TYPE, TYPE_CODE, TYPE_CODE_STRUCT, TYPE_CODE_UNION, TYPE_FIELD_NAME, TYPE_N_BASECLASSES, TYPE_NFIELDS, and word.
static void completion_list_objc_symbol (struct minimal_symbol * msymbol, const char * sym_text, int sym_text_len, const char * text, const char * word) [static]
Definition at line 4083 of file symtab.c.
References memcpy(), selector, strchr(), SYMBOL_NATURAL_NAME, and xrealloc().
static void create_demangled_names_hash (struct objfile * objfile) [static]
Definition at line 588 of file symtab.c.
References objfile_per_bfd_storage::demangled_names_hash, eq_demangled_name_entry(), hash_demangled_name_entry(), objfile::per_bfd, xcalloc(), and xfree().
Referenced by symbol_set_names().
static struct filename_seen_cache* create_filename_seen_cache (void) [static, read]
Definition at line 3129 of file symtab.c.
References INITIAL_FILENAME_SEEN_CACHE_SIZE, filename_seen_cache::tab, xcalloc(), and xfree().
Referenced by sources_info().
static void delete_filename_seen_cache (void * ptr) [static]
Definition at line 3153 of file symtab.c.
References filename_seen_cache::tab, and xfree().
Referenced by sources_info().
struct cleanup* demangle_for_lookup (const char * name, enum language lang, const char ** result_name) [read]
Definition at line 1182 of file symtab.c.
References cp_canonicalize_string(), d_demangle(), gdb_demangle(), go_demangle(), language_cplus, language_d, language_go, language_java, make_cleanup(), name, null_cleanup(), and xfree().
Referenced by find_linespec_symbols(), lookup_symbol_in_language(), and lookup_symbol_in_objfile_from_linkage_name().
static void do_end_rbreak_breakpoints (void * ignore) [static]
Definition at line 3882 of file symtab.c.
References end_rbreak_breakpoints().
Referenced by rbreak_command().
static void do_free_completion_list (void * list) [static]
Definition at line 4023 of file symtab.c.
References free_completion_list().
static void do_free_search_symbols_cleanup (void * symbolsp) [static]
Definition at line 3317 of file symtab.c.
References free_search_symbols().
Referenced by make_cleanup_free_search_symbols().
const char* domain_name (domain_enum e)
Definition at line 149 of file symtab.c.
References COMMON_BLOCK_DOMAIN, gdb_assert_not_reached, LABEL_DOMAIN, STRUCT_DOMAIN, UNDEF_DOMAIN, and VAR_DOMAIN.
Referenced by debug_qf_lookup_symbol(), and debug_qf_map_matching_symbols().
static int eq_demangled_name_entry (const void * a, const void * b) [static]
Definition at line 575 of file symtab.c.
References demangled_name_entry::mangled.
Referenced by create_demangled_names_hash().
static void ATTRIBUTE_NORETURN error_in_psymtab_expansion (int kind, const char * name, struct symtab * symtab) [static]
Definition at line 1683 of file symtab.c.
References _, error(), GLOBAL_BLOCK, and symtab_to_filename_for_display().
Referenced by basic_lookup_transparent_type_quick(), and lookup_symbol_aux_quick().
static int expand_partial_symbol_name (const char * name, void * user_data) [static]
Definition at line 4233 of file symtab.c.
References compare_symbol_name(), add_name_data::sym_text, and add_name_data::sym_text_len.
static int file_matches (const char * file, char * files[], int nfiles, int basenames) [static]
Definition at line 3282 of file symtab.c.
References compare_filenames_for_search().
Referenced by search_symbols(), and search_symbols_file_matches().
static int filename_seen (struct filename_seen_cache * cache, const char * file, int add) [static]
Definition at line 3169 of file symtab.c.
References filename_seen_cache::tab.
Referenced by maybe_add_partial_symtab_filename(), and output_source_filename().
struct symtab_and_line find_function_start_sal (struct symbol * sym, int funfirstline) [read]
Definition at line 2778 of file symtab.c.
References BLOCK_START, current_program_space, find_pc_sect_line(), fixup_symbol_section(), init_sal(), symtab_and_line::pc, symtab_and_line::pspace, symtab_and_line::section, skip_prologue_sal(), SYMBOL_BLOCK_VALUE, SYMBOL_OBJ_SECTION, and SYMBOL_OBJFILE.
Referenced by ada_exception_sal(), spu_catch_start(), symbol_to_sal(), and user_select_syms().
static int find_line_common (struct linetable * l, int lineno, int * exact_match, int start) [static]
Definition at line 2678 of file symtab.c.
References linetable::item, len, linetable_entry::line, and linetable::nitems.
Referenced by find_line_symtab(), and VEC().
int find_line_pc (struct symtab * symtab, int line, CORE_ADDR * pc)
Definition at line 2611 of file symtab.c.
References find_line_symtab(), linetable::item, LINETABLE, and linetable_entry::pc.
Referenced by extract_display_start_addr(), find_line_pc_range(), make_visible_with_new_height(), mi_cmd_disassemble(), resolve_sal_pc(), tui_update_source_windows_with_line(), and update_static_tracepoint().
int find_line_pc_range (struct symtab_and_line sal, CORE_ADDR * startptr, CORE_ADDR * endptr)
Definition at line 2638 of file symtab.c.
References symtab_and_line::end, find_line_pc(), find_pc_sect_line(), symtab_and_line::line, symtab_and_line::pc, symtab_and_line::section, and symtab_and_line::symtab.
Referenced by find_breakpoint_range_end(), line_info(), mi_cmd_trace_find(), and trace_find_line_command().
struct symtab* find_line_symtab (struct symtab * symtab, int line, int * index, int * exact_match) [read]
Definition at line 2479 of file symtab.c.
References ALL_OBJFILES, ALL_SYMTABS, quick_symbol_functions::expand_symtabs_with_fullname, symtab::filename, find_line_common(), linetable::item, linetable_entry::line, LINETABLE, sym_fns::qf, objfile::sf, and symtab_to_fullname().
Referenced by decode_digits_list_mode(), and find_line_pc().
static void find_main_name (void) [static]
Definition at line 4978 of file symtab.c.
References ada_main_name(), go_main_name(), pascal_main_name(), and set_main_name().
Referenced by main_name().
struct symtab_and_line find_pc_line (CORE_ADDR pc, int notcurrent) [read]
Definition at line 2458 of file symtab.c.
References find_pc_overlay(), find_pc_sect_line(), overlay_mapped_address(), symtab_and_line::pc, pc_in_unmapped_range(), and symtab_and_line::section.
Referenced by aarch64_scan_prologue(), after_prologue(), alpha_after_prologue(), arm_linux_copy_svc(), c_parse(), call0_analyze_prologue(), convert_linespec_to_sals(), cris_skip_prologue(), decode_static_tracepoint_spec(), default_macro_scope(), do_mixed_source_and_assembly(), elf_gnu_ifunc_resolver_return_stop(), find_frame_sal(), find_last_line_symbol(), find_pc_line_pc_range(), find_pc_sect_line(), finish_backward(), finish_forward(), frv_skip_prologue(), gdb_disassemble_driver(), gdb_get_breakpoint_info(), gdb_get_tracepoint_info(), gdb_loc(), h8300_skip_prologue(), handle_inferior_event(), handle_step_into_function(), handle_step_into_function_backward(), in_prologue(), info_checkpoints_command(), iq2000_skip_prologue(), m32r_skip_prologue(), m68hc11_skip_prologue(), m88k_skip_prologue(), microblaze_skip_prologue(), moxie_skip_prologue(), mt_skip_prologue(), parse_breakpoint_sals(), print_one_static_tracepoint_marker(), refine_prologue_limit(), save_bookmark_command(), set_momentary_breakpoint_at_pc(), set_traceframe_context(), skip_prologue(), skip_prologue_using_sal(), sparc32_skip_prologue(), sparc64_skip_prologue(), trace_find_line_command(), tui_display_main(), tui_show_disassem_and_update_source(), tui_update_source_windows_with_addr(), until_break_command(), until_next_command(), update_static_tracepoint(), v850_skip_prologue(), VEC(), xstormy16_skip_prologue(), and xtensa_skip_prologue().
int find_pc_line_pc_range (CORE_ADDR pc, CORE_ADDR * startptr, CORE_ADDR * endptr)
Definition at line 2722 of file symtab.c.
References find_pc_line().
Referenced by step_once().
struct symtab_and_line find_pc_sect_line (CORE_ADDR pc, struct obj_section * section, int notcurrent) [read]
Definition at line 2214 of file symtab.c.
References ALL_OBJFILE_SYMTABS, BLOCK_END, BLOCKVECTOR, BLOCKVECTOR_BLOCK, current_program_space, symtab_and_line::end, find_pc_line(), find_pc_sect_symtab(), GLOBAL_BLOCK, init_sal(), linetable::item, len, linetable_entry::line, symtab_and_line::line, LINETABLE, lookup_minimal_symbol_by_pc(), lookup_minimal_symbol_text(), bound_minimal_symbol::minsym, mst_solib_trampoline, MSYMBOL_TYPE, linetable::nitems, symtab::objfile, linetable_entry::pc, symtab_and_line::pc, symtab_and_line::pspace, symtab_and_line::section, SYMBOL_LINKAGE_NAME, SYMBOL_VALUE_ADDRESS, and symtab_and_line::symtab.
Referenced by amd64_skip_xmm_prologue(), build_address_symbolic(), find_function_start_sal(), find_line_pc_range(), find_pc_line(), minsym_found(), and skip_prologue_sal().
struct symtab* find_pc_sect_symtab (CORE_ADDR pc, struct obj_section * section) [read]
Definition at line 2076 of file symtab.c.
References ALL_BLOCK_SYMBOLS, ALL_OBJFILES, ALL_PRIMARY_SYMTABS, BLOCK_END, BLOCK_START, BLOCKVECTOR, BLOCKVECTOR_BLOCK, quick_symbol_functions::find_pc_sect_symtab, fixup_symbol_section(), objfile::flags, GLOBAL_BLOCK, lookup_minimal_symbol_by_pc_section(), matching_obj_sections(), bound_minimal_symbol::minsym, mst_abs, mst_bss, mst_data, mst_file_bss, mst_file_data, MSYMBOL_TYPE, OBJF_REORDERED, sym_fns::qf, objfile::sf, and SYMBOL_OBJ_SECTION.
Referenced by blockvector_for_pc_sect(), find_pc_sect_line(), find_pc_symtab(), gdbpy_block_for_pc(), and spu_catch_start().
struct symtab* find_pc_sect_symtab_via_partial (CORE_ADDR pc, struct obj_section * section) [read]
Definition at line 1006 of file symtab.c.
References ALL_OBJFILES, quick_symbol_functions::find_pc_sect_symtab, lookup_minimal_symbol_by_pc_section(), bound_minimal_symbol::minsym, mst_abs, mst_bss, mst_data, mst_file_bss, mst_file_data, MSYMBOL_TYPE, sym_fns::qf, and objfile::sf.
Referenced by backtrace_command_1().
struct symtab* find_pc_symtab (CORE_ADDR pc) [read]
Definition at line 2190 of file symtab.c.
References find_pc_mapped_section(), and find_pc_sect_symtab().
Referenced by amd64_in_function_epilogue_p(), amd64_skip_prologue(), arm_skip_prologue(), call_site_for_pc(), dwarf2_frame_find_quirks(), gdb_disassemble_driver(), gdb_disassembly(), get_frame_language(), handle_step_into_function(), handle_step_into_function_backward(), i386_in_function_epilogue_p(), i386_skip_prologue(), make_visible_with_new_height(), search_symbols(), select_frame(), tui_horizontal_source_scroll(), tui_selected_frame_level_changed_hook(), tui_show_disassem(), and tui_vertical_source_scroll().
void fixup_section (struct general_symbol_info * ginfo, CORE_ADDR addr, struct objfile * objfile)
Definition at line 1041 of file symtab.c.
References ALL_OBJFILE_OSECTIONS, ANOFFSET, lookup_minimal_symbol_by_pc_name(), general_symbol_info::name, obj_section_addr, obj_section_endaddr, offset, general_symbol_info::section, objfile::section_offsets, objfile::sections, and SYMBOL_SECTION.
Referenced by fixup_psymbol_section(), and fixup_symbol_section().
struct symbol* fixup_symbol_section (struct symbol * sym, struct objfile * objfile) [read]
Definition at line 1122 of file symtab.c.
References BLOCK_START, fixup_section(), gdb_assert, symbol::ginfo, LOC_BLOCK, LOC_LABEL, LOC_STATIC, SYMBOL_BLOCK_VALUE, SYMBOL_CLASS, SYMBOL_OBJ_SECTION, SYMBOL_SYMTAB, and SYMBOL_VALUE_ADDRESS.
Referenced by ada_add_block_symbols(), ada_lookup_encoded_symbol(), aux_add_nonlocal_symbols(), find_function_start_sal(), find_pc_sect_symtab(), jump_command(), lookup_global_symbol_from_objfile(), lookup_symbol_aux_block(), lookup_symbol_aux_objfile(), lookup_symbol_aux_quick(), relocate_one_symbol(), resolve_sal_pc(), skip_prologue_sal(), spu_catch_start(), and var_decode_location().
static void free_completion_list (VEC(char_ptr)** list_ptr) [static]
Definition at line 4010 of file symtab.c.
References p, VEC_free, VEC_iterate, and xfree().
Referenced by do_free_completion_list().
void free_search_symbols (struct symbol_search * symbols)
Definition at line 3304 of file symtab.c.
References symbol_search::next, p, and xfree().
Referenced by do_free_search_symbols_cleanup().
static void functions_info (char * regexp, int from_tty) [static]
Definition at line 3859 of file symtab.c.
References FUNCTIONS_DOMAIN, and symtab_symbol_info().
char* gdb_mangle_name (struct type * type, int method_id, int signature_id)
Definition at line 369 of file symtab.c.
References field_name(), cleanup_check::is_constructor(), is_constructor_name(), cleanup_check::is_destructor(), is_destructor_name(), is_operator_name(), len, TYPE_FN_FIELD_PHYSNAME, TYPE_FN_FIELDLIST1, TYPE_FN_FIELDLIST_NAME, type_name_no_tag(), xmalloc(), and xsnprintf().
Referenced by c_type_print_base(), check_stub_method(), and java_type_print_base().
gdb_static_assert (MAX_SYMBOL_IMPLS<= 1<< SYMBOL_ACLASS_BITS)
static hashval_t hash_demangled_name_entry (const void * data) [static]
Definition at line 565 of file symtab.c.
References demangled_name_entry::mangled.
Referenced by create_demangled_names_hash().
int in_prologue (struct gdbarch * gdbarch, CORE_ADDR pc, CORE_ADDR func_start)
Definition at line 4775 of file symtab.c.
References symtab_and_line::end, find_pc_line(), find_pc_partial_function(), gdbarch_skip_prologue(), and symtab_and_line::line.
Referenced by handle_inferior_event().
void init_sal (struct symtab_and_line * sal)
Definition at line 926 of file symtab.c.
References symtab_and_line::end, symtab_and_line::explicit_line, symtab_and_line::explicit_pc, symtab_and_line::line, symtab_and_line::pc, symtab_and_line::probe, symtab_and_line::pspace, symtab_and_line::section, and symtab_and_line::symtab.
Referenced by call_function_by_hand(), clear_command(), create_breakpoint(), create_internal_breakpoint(), create_sals_line_offset(), decode_digits_ordinary(), decode_static_tracepoint_spec(), elf_gnu_ifunc_resolver_stop(), find_frame_sal(), find_function_start_sal(), find_pc_sect_line(), finish_backward(), finish_command(), handle_inferior_event(), handle_step_into_function(), init_catchpoint(), insert_hp_step_resume_breakpoint_at_frame(), insert_step_resume_breakpoint_at_caller(), line_info(), parse_breakpoint_sals(), parse_probes(), print_one_static_tracepoint_marker(), save_bookmark_command(), set_traceframe_context(), symbol_to_sal(), tui_update_source_window_as_is(), and update_static_tracepoint().
static void initialize_ordinary_address_classes (void) [static]
Definition at line 5165 of file symtab.c.
References symbol_impl::aclass, and LOC_FINAL_VALUE.
void initialize_symbol (struct symbol * sym)
Definition at line 5178 of file symtab.c.
References memset(), and SYMBOL_SECTION.
Referenced by process_xcoff_symbol().
int iterate_over_some_symtabs (const char * name, const char * real_path, int(*)(struct symtab *symtab, void *data) callback, void * data, struct symtab * first, struct symtab * after_last)
Definition at line 230 of file symtab.c.
References basenames_may_differ, compare_filenames_for_search(), symtab::filename, symtab::fullname, gdb_assert, symtab::next, and symtab_to_fullname().
Referenced by dw2_map_expand_apply(), iterate_over_symtabs(), and partial_map_expand_apply().
void iterate_over_symbols (const struct block * block, const char * name, const domain_enum domain, symbol_found_callback_ftype * callback, void * data)
Definition at line 2051 of file symtab.c.
References block_iter_name_first(), block_iter_name_next(), SYMBOL_DOMAIN, SYMBOL_LANGUAGE, and symbol_matches_domain().
void iterate_over_symtabs (const char * name, int(*)(struct symtab *symtab, void *data) callback, void * data)
Definition at line 291 of file symtab.c.
References ALL_OBJFILES, do_cleanups(), gdb_assert, gdb_realpath(), iterate_over_some_symtabs(), make_cleanup(), quick_symbol_functions::map_symtabs_matching_filename, null_cleanup(), sym_fns::qf, objfile::sf, objfile::symtabs, and xfree().
Referenced by lookup_symtab(), and VEC().
static const char* language_search_unquoted_string (const char * text, const char * p) [static]
Definition at line 4143 of file symtab.c.
References current_language, language_defn::la_language, and language_objc.
struct symbol* lookup_block_symbol (const struct block * block, const char * name, const domain_enum domain) [read]
Definition at line 1996 of file symtab.c.
References BLOCK_FUNCTION, block_iter_name_first(), block_iter_name_next(), SYMBOL_DOMAIN, SYMBOL_IS_ARGUMENT, SYMBOL_LANGUAGE, and symbol_matches_domain().
Referenced by basic_lookup_transparent_type(), basic_lookup_transparent_type_quick(), dw2_lookup_symbol(), lookup_global_symbol_from_objfile(), lookup_language_this(), lookup_symbol_aux_block(), lookup_symbol_aux_objfile(), lookup_symbol_aux_psymtabs(), lookup_symbol_aux_quick(), maintenance_check_psymtabs(), and spu_catch_start().
struct symbol* lookup_global_symbol_from_objfile (const struct objfile * main_objfile, const char * name, const domain_enum domain) [read]
Definition at line 1552 of file symtab.c.
References ALL_OBJFILE_PRIMARY_SYMTABS, BLOCKVECTOR, BLOCKVECTOR_BLOCK, fixup_symbol_section(), GLOBAL_BLOCK, lookup_block_symbol(), lookup_symbol_aux_quick(), symtab::objfile, and objfile_separate_debug_iterate().
Referenced by elf_lookup_lib_symbol(), and spu_lookup_lib_symbol().
struct symbol* lookup_language_this (const struct language_defn * lang, const struct block * block) [read]
Definition at line 1298 of file symtab.c.
References BLOCK_FUNCTION, BLOCK_SUPERBLOCK, language_defn::la_name_of_this, lookup_block_symbol(), and VAR_DOMAIN.
Referenced by gen_expr(), lookup_symbol_aux(), lookup_symbol_file(), and value_of_this().
struct objfile* lookup_objfile_from_block (const struct block * block) [read]
Definition at line 1507 of file symtab.c.
References ALL_SYMTABS, block_global_block(), BLOCKVECTOR, BLOCKVECTOR_BLOCK, GLOBAL_BLOCK, and objfile::separate_debug_objfile_backlink.
Referenced by clear_dangling_display_expressions(), lookup_symbol_global(), and operator_check_standard().
struct symbol* lookup_static_symbol_aux (const char * name, const domain_enum domain) [read]
Definition at line 1444 of file symtab.c.
References ALL_OBJFILES, lookup_symbol_aux_quick(), lookup_symbol_aux_symtabs(), and STATIC_BLOCK.
Referenced by cp_lookup_nested_symbol(), find_symbol_in_baseclass(), and lookup_symbol_aux().
struct symbol* lookup_symbol (const char * name, const struct block * block, domain_enum domain, struct field_of_this_result * is_a_field_of_this) [read]
Definition at line 1285 of file symtab.c.
References current_language, language_defn::la_language, and lookup_symbol_in_language().
Referenced by address_info(), c_val_print(), check_typedef(), classify_name(), classify_packaged_name(), cp_lookup_rtti_type(), find_function_in_inferior(), find_imps(), find_proc_desc(), frapy_read_var(), gdbpy_lookup_symbol(), gen_static_field(), get_java_object_type(), gnuv3_get_typeid_type(), insert_exception_resume_breakpoint(), inspect_type(), iterate_over_block_arg_vars(), java_lookup_class(), language_bool_type(), lex_one_token(), list_args_or_locals(), lookup_enum(), lookup_struct(), lookup_struct_typedef(), lookup_template_type(), lookup_typename(), lookup_union(), moxie_skip_prologue(), mt_skip_prologue(), package_name_p(), parse_procedure(), pascal_val_print(), print_frame_args(), push_variable(), replace_typedefs(), select_source_symtab(), set_initial_language(), skip_function_command(), value_fn_field(), value_static_field(), write_dollar_variable(), xstormy16_skip_prologue(), and yylex().
static struct symbol* lookup_symbol_aux (const char * name, const struct block * block, const domain_enum domain, enum language language, struct field_of_this_result * is_a_field_of_this) [static, read]
Referenced by lookup_symbol_in_language().
static struct symbol* lookup_symbol_aux (const char * name, const struct block * block, const domain_enum domain, enum language language, struct field_of_this_result * is_a_field_of_this) [static, read]
Definition at line 1371 of file symtab.c.
References _, check_field(), CHECK_TYPEDEF, error(), language_defn::la_lookup_symbol_nonlocal, language_defn::la_name_of_this, language_def(), lookup_language_this(), lookup_static_symbol_aux(), lookup_symbol_aux_local(), memset(), STRUCT_DOMAIN, symbol::type, TYPE_CODE, TYPE_CODE_PTR, TYPE_CODE_REF, TYPE_CODE_STRUCT, TYPE_CODE_UNION, and TYPE_TARGET_TYPE.
struct symbol* lookup_symbol_aux_block (const char * name, const struct block * block, const domain_enum domain) [read]
Definition at line 1533 of file symtab.c.
References fixup_symbol_section(), and lookup_block_symbol().
Referenced by lookup_symbol_aux_local(), lookup_symbol_file(), and lookup_symbol_static().
static struct symbol* lookup_symbol_aux_local (const char * name, const struct block * block, const domain_enum domain, enum language language) [static, read]
Referenced by lookup_symbol_aux().
static struct symbol* lookup_symbol_aux_local (const char * name, const struct block * block, const domain_enum domain, enum language language) [static, read]
Definition at line 1467 of file symtab.c.
References BLOCK_FUNCTION, block_inlined_p(), block_scope(), block_static_block(), BLOCK_SUPERBLOCK, cp_lookup_symbol_imports_or_template(), language_cplus, language_fortran, and lookup_symbol_aux_block().
static struct symbol* lookup_symbol_aux_objfile (struct objfile * objfile, int block_index, const char * name, const domain_enum domain) [static, read]
Definition at line 1594 of file symtab.c.
References ALL_OBJFILE_PRIMARY_SYMTABS, BLOCKVECTOR, BLOCKVECTOR_BLOCK, fixup_symbol_section(), and lookup_block_symbol().
Referenced by lookup_symbol_aux_symtabs(), lookup_symbol_global_iterator_cb(), and lookup_symbol_in_objfile_from_linkage_name().
static struct symbol * lookup_symbol_aux_quick (struct objfile * objfile, int block_index, const char * name, const domain_enum domain) [static, read]
Definition at line 1697 of file symtab.c.
References BLOCKVECTOR, BLOCKVECTOR_BLOCK, error_in_psymtab_expansion(), fixup_symbol_section(), lookup_block_symbol(), quick_symbol_functions::lookup_symbol, sym_fns::qf, and objfile::sf.
Referenced by lookup_global_symbol_from_objfile(), lookup_static_symbol_aux(), and lookup_symbol_global_iterator_cb().
static struct symbol * lookup_symbol_aux_symtabs (int block_index, const char * name, const domain_enum domain) [static, read]
Definition at line 1621 of file symtab.c.
References ALL_OBJFILES, and lookup_symbol_aux_objfile().
Referenced by lookup_static_symbol_aux().
struct symbol* lookup_symbol_global (const char * name, const struct block * block, const domain_enum domain) [read]
Definition at line 1825 of file symtab.c.
References global_sym_lookup_data::domain, gdbarch_iterate_over_objfiles_in_search_order(), get_objfile_arch(), lookup_objfile_from_block(), lookup_symbol_global_iterator_cb(), memset(), name, global_sym_lookup_data::name, global_sym_lookup_data::result, solib_global_lookup(), and target_gdbarch().
Referenced by basic_lookup_symbol_nonlocal(), gdbpy_lookup_global_symbol(), and lookup_symbol_file().
static int lookup_symbol_global_iterator_cb (struct objfile * objfile, void * cb_data) [static]
Definition at line 1802 of file symtab.c.
References global_sym_lookup_data::domain, gdb_assert, GLOBAL_BLOCK, lookup_symbol_aux_objfile(), lookup_symbol_aux_quick(), global_sym_lookup_data::name, and global_sym_lookup_data::result.
Referenced by lookup_symbol_global().
struct symbol* lookup_symbol_in_language (const char * name, const struct block * block, const domain_enum domain, enum language lang, struct field_of_this_result * is_a_field_of_this) [read]
Definition at line 1266 of file symtab.c.
References demangle_for_lookup(), do_cleanups(), and lookup_symbol_aux().
Referenced by ada_tasks_inferior_data_sniffer(), get_tcb_types_info(), lookup_symbol(), and standard_lookup().
static struct symbol* lookup_symbol_in_objfile_from_linkage_name (struct objfile * objfile, const char * linkage_name, domain_enum domain) [static, read]
Definition at line 1642 of file symtab.c.
References current_language, demangle_for_lookup(), do_cleanups(), GLOBAL_BLOCK, language_defn::la_language, lookup_symbol_aux_objfile(), objfile_separate_debug_iterate(), objfile::separate_debug_objfile_backlink, and STATIC_BLOCK.
Referenced by search_symbols().
struct symbol* lookup_symbol_static (const char * name, const struct block * block, const domain_enum domain) [read]
Definition at line 1769 of file symtab.c.
References block_static_block(), and lookup_symbol_aux_block().
Referenced by basic_lookup_symbol_nonlocal(), find_symbol_in_baseclass(), and lookup_symbol_file().
struct symtab* lookup_symtab (const char * name) [read]
Definition at line 354 of file symtab.c.
References iterate_over_symtabs(), and lookup_symtab_callback().
Referenced by block_lookup(), gdb_find_bp_at_line(), gdb_find_file_command(), gdb_listfuncs(), gdb_loadfile(), mi_cmd_disassemble(), mi_cmd_symbol_list_lines(), skip_file_command(), and yylex().
static int lookup_symtab_callback (struct symtab * symtab, void * data) [static]
Definition at line 342 of file symtab.c.
References result_ptr.
Referenced by lookup_symtab().
struct type* lookup_transparent_type (const char * name) [read]
Definition at line 1876 of file symtab.c.
References current_language, and language_defn::la_lookup_transparent_type.
Referenced by check_typedef().
char* main_name (void)
Definition at line 5025 of file symtab.c.
References find_main_name(), and name_of_main.
Referenced by inside_main_func(), run_command_1(), select_source_symtab(), set_initial_language(), and skip_prologue().
struct cleanup* make_cleanup_free_search_symbols (struct symbol_search ** symbolsp) [read]
Definition at line 3325 of file symtab.c.
References do_free_search_symbols_cleanup(), and make_cleanup().
Referenced by gdb_search(), rbreak_command(), search_symbols(), and symtab_symbol_info().
int matching_obj_sections (struct obj_section * obj_first, struct obj_section * obj_second)
Definition at line 945 of file symtab.c.
References ALL_OBJFILES, gdb_assert, objfile::obfd, objfile::separate_debug_objfile, objfile::separate_debug_objfile_backlink, and obj_section::the_bfd_section.
Referenced by find_pc_sect_psymbol(), find_pc_sect_symtab(), and lookup_minimal_symbol_by_pc_section_1().
static void maybe_add_partial_symtab_filename (const char * filename, const char * fullname, void * user_data) [static]
Definition at line 4677 of file symtab.c.
References add_filename_to_list(), filename_seen(), add_partial_filename_data::filename_seen_cache, not_interesting_fname(), add_partial_filename_data::text, add_partial_filename_data::text_len, and add_partial_filename_data::word.
const char* multiple_symbols_select_mode (void)
Definition at line 135 of file symtab.c.
References multiple_symbols_mode.
Referenced by decode_line_full(), and user_select_syms().
static int not_interesting_fname (const char * fname) [static]
Definition at line 4647 of file symtab.c.
Referenced by maybe_add_partial_symtab_filename().
static char* operator_chars (char * p, char ** end) [static]
Definition at line 2983 of file symtab.c.
References _, and error().
Referenced by search_symbols().
static void output_partial_symbol_filename (const char * filename, const char * fullname, void * data) [static]
Definition at line 3232 of file symtab.c.
References output_source_filename().
Referenced by sources_info().
static void output_source_filename (const char * name, struct output_source_filename_data * data) [static]
Definition at line 3201 of file symtab.c.
References filename_seen(), output_source_filename_data::filename_seen_cache, output_source_filename_data::first, fputs_filtered(), gdb_stdout, printf_filtered(), and wrap_here().
Referenced by output_partial_symbol_filename(), and sources_info().
static void print_msymbol_info (struct bound_minimal_symbol msymbol) [static]
Definition at line 3781 of file symtab.c.
References gdbarch_addr_bit(), get_objfile_arch(), hex_string_custom(), bound_minimal_symbol::minsym, bound_minimal_symbol::objfile, printf_filtered(), SYMBOL_PRINT_NAME, and SYMBOL_VALUE_ADDRESS.
Referenced by symtab_symbol_info().
static void print_symbol_info (enum search_domain kind, struct symtab * s, struct symbol * sym, int block, const char * last) [static]
Definition at line 3743 of file symtab.c.
References fputs_filtered(), gdb_stdout, LOC_TYPEDEF, printf_filtered(), STATIC_BLOCK, STRUCT_DOMAIN, SYMBOL_CLASS, SYMBOL_DOMAIN, SYMBOL_PRINT_NAME, SYMBOL_TYPE, symtab_to_filename_for_display(), type_print(), typedef_print(), and TYPES_DOMAIN.
Referenced by rbreak_command(), and symtab_symbol_info().
int producer_is_realview (const char * producer)
Definition at line 5046 of file symtab.c.
Referenced by dwarf2_frame_find_quirks(), prototyped_function_p(), and read_structure_type().
static void rbreak_command (char * regexp, int from_tty) [static]
Definition at line 3888 of file symtab.c.
References symbol_search::block, break_command(), do_cleanups(), do_end_rbreak_breakpoints(), free_current_contents(), FUNCTIONS_DOMAIN, len, make_cleanup(), make_cleanup_free_search_symbols(), memcpy(), bound_minimal_symbol::minsym, symbol_search::msymbol, symbol_search::next, p, print_symbol_info(), printf_filtered(), search_symbols(), skip_spaces(), start_rbreak_breakpoints(), strchr(), symbol_search::symbol, SYMBOL_LINKAGE_NAME, SYMBOL_PRINT_NAME, symbol_search::symtab, symtab_to_filename_for_display(), symtab_to_fullname(), and xrealloc().
Referenced by rbreak_command_wrapper().
void rbreak_command_wrapper (char * regexp, int from_tty)
Definition at line 3874 of file symtab.c.
References rbreak_command().
int register_symbol_block_impl (enum address_class aclass, const struct symbol_block_ops * ops)
Definition at line 5125 of file symtab.c.
References symbol_impl::aclass, symbol_block_ops::find_frame_base_location, gdb_assert, LOC_BLOCK, MAX_SYMBOL_IMPLS, and symbol_impl::ops_block.
int register_symbol_computed_impl (enum address_class aclass, const struct symbol_computed_ops * ops)
Definition at line 5099 of file symtab.c.
References symbol_impl::aclass, symbol_computed_ops::describe_location, gdb_assert, LOC_COMPUTED, MAX_SYMBOL_IMPLS, symbol_impl::ops_computed, symbol_computed_ops::read_needs_frame, symbol_computed_ops::read_variable, and symbol_computed_ops::tracepoint_var_ref.
int register_symbol_register_impl (enum address_class aclass, const struct symbol_register_ops * ops)
Definition at line 5148 of file symtab.c.
References symbol_impl::aclass, gdb_assert, LOC_REGISTER, LOC_REGPARM_ADDR, MAX_SYMBOL_IMPLS, and symbol_impl::ops_register.
const char* search_domain_name (enum search_domain e)
Definition at line 165 of file symtab.c.
References ALL_DOMAIN, FUNCTIONS_DOMAIN, gdb_assert_not_reached, TYPES_DOMAIN, and VARIABLES_DOMAIN.
Referenced by debug_qf_expand_symtabs_matching().
void search_symbols (char * regexp, enum search_domain kind, int nfiles, char * files[], struct symbol_search ** matches)
Definition at line 3452 of file symtab.c.
References _, ALL_BLOCK_SYMBOLS, ALL_MSYMBOLS, ALL_OBJFILES, ALL_PRIMARY_SYMTABS, basenames_may_differ, symbol_search::block, BLOCKVECTOR, BLOCKVECTOR_BLOCK, case_sensitive_off, minimal_symbol::created_by_gdb, discard_cleanups(), do_cleanups(), error(), quick_symbol_functions::expand_symtabs_matching, file_matches(), symtab::filename, search_symbols_data::files, find_pc_symtab(), FUNCTIONS_DOMAIN, gdb_assert, get_regcomp_error(), GLOBAL_BLOCK, LOC_BLOCK, LOC_CONST, LOC_TYPEDEF, LOC_UNRESOLVED, lookup_symbol_in_objfile_from_linkage_name(), make_cleanup(), make_cleanup_free_search_symbols(), make_regfree_cleanup(), memset(), bound_minimal_symbol::minsym, mst_abs, mst_bss, mst_data, mst_file_bss, mst_file_data, mst_file_text, mst_solib_trampoline, mst_text, mst_text_gnu_ifunc, symbol_search::msymbol, MSYMBOL_TYPE, symbol_search::next, search_symbols_data::nfiles, null_cleanup(), bound_minimal_symbol::objfile, operator_chars(), search_symbols_data::preg, search_symbols_data::preg_p, sym_fns::qf, QUIT, search_symbols_file_matches(), search_symbols_name_matches(), objfile::sf, sort_search_symbols_remove_dups(), STATIC_BLOCK, symbol_search::symbol, SYMBOL_CLASS, SYMBOL_LINKAGE_NAME, SYMBOL_NATURAL_NAME, SYMBOL_SYMTAB, SYMBOL_TYPE, SYMBOL_VALUE_ADDRESS, symbol_search::symtab, symtab_to_fullname(), TYPE_CODE, TYPE_CODE_ENUM, TYPES_DOMAIN, VAR_DOMAIN, VARIABLES_DOMAIN, xfree(), and xmalloc().
Referenced by gdb_search(), rbreak_command(), and symtab_symbol_info().
static int search_symbols_file_matches (const char * filename, void * user_data, int basenames) [static]
Definition at line 3417 of file symtab.c.
References file_matches(), search_symbols_data::files, and search_symbols_data::nfiles.
Referenced by search_symbols().
static int search_symbols_name_matches (const char * symname, void * user_data) [static]
Definition at line 3428 of file symtab.c.
References search_symbols_data::preg, and search_symbols_data::preg_p.
Referenced by search_symbols().
void set_main_name (const char * name)
Definition at line 4959 of file symtab.c.
References language_unknown, and xfree().
Referenced by find_main_name(), process_one_symbol(), read_partial_die(), and symtab_observer_executable_changed().
void skip_prologue_sal (struct symtab_and_line * sal)
Definition at line 2810 of file symtab.c.
References BLOCK_END, block_for_pc_sect(), BLOCK_FUNCTION, block_inlined_p(), BLOCK_START, BLOCK_SUPERBLOCK, do_cleanups(), symtab_and_line::end, symtab_and_line::explicit_line, symtab_and_line::explicit_pc, find_pc_sect_function(), find_pc_sect_line(), fixup_symbol_section(), gdbarch_deprecated_function_start_offset(), gdbarch_skip_main_prologue(), gdbarch_skip_main_prologue_p(), gdbarch_skip_prologue(), get_objfile_arch(), symtab_and_line::line, lookup_minimal_symbol_by_pc_section(), bound_minimal_symbol::minsym, name, bound_minimal_symbol::objfile, overlay_mapped_address(), overlay_unmapped_address(), symtab_and_line::pc, symtab_and_line::pspace, save_current_space_and_thread(), symtab_and_line::section, section_is_mapped(), section_is_overlay(), skip_prologue_using_lineinfo(), strcmp_iw(), switch_to_program_space_and_thread(), SYMBOL_BLOCK_VALUE, SYMBOL_LINE, SYMBOL_LINKAGE_NAME, SYMBOL_OBJ_SECTION, SYMBOL_OBJFILE, SYMBOL_SYMTAB, SYMBOL_VALUE_ADDRESS, and symtab_and_line::symtab.
Referenced by create_sals_line_offset(), find_function_start_sal(), minsym_found(), and resolve_sal_pc().
static CORE_ADDR skip_prologue_using_lineinfo (CORE_ADDR func_addr, struct symtab * symtab) [static]
Definition at line 2738 of file symtab.c.
References find_pc_partial_function(), linetable::item, linetable_entry::line, LINETABLE, linetable::nitems, and linetable_entry::pc.
Referenced by skip_prologue_sal().
CORE_ADDR skip_prologue_using_sal (struct gdbarch * gdbarch, CORE_ADDR func_addr)
Definition at line 4858 of file symtab.c.
References block_for_pc(), BLOCK_FUNCTION, block_inlined_p(), BLOCK_SUPERBLOCK, symtab_and_line::end, find_pc_line(), find_pc_partial_function(), gdbarch_deprecated_function_start_offset(), linetable::item, symtab::language, language_asm, linetable_entry::line, symtab_and_line::line, LINETABLE, linetable::nitems, linetable_entry::pc, symtab_and_line::pc, and symtab_and_line::symtab.
Referenced by aarch64_skip_prologue(), amd64_skip_prologue(), amd64_windows_skip_prologue(), arm_skip_prologue(), avr_skip_prologue(), frv_analyze_prologue(), i386_skip_prologue(), lm32_skip_prologue(), m32c_skip_prologue(), mips_skip_prologue(), moxie_skip_prologue(), mt_frame_unwind_cache(), nios2_skip_prologue(), rs6000_skip_prologue(), sh_skip_prologue(), tic6x_skip_prologue(), and tilegx_skip_prologue().
static void sort_search_symbols_remove_dups (struct symbol_search * found, int nfound, struct symbol_search ** new_head, struct symbol_search ** new_tail) [static]
Definition at line 3356 of file symtab.c.
References symbol_search::block, compare_search_syms(), gdb_assert, symbol_search::next, qsort, xfree(), and xmalloc().
Referenced by search_symbols().
static void sources_info (char * ignore, int from_tty) [static]
Definition at line 3239 of file symtab.c.
References _, ALL_SYMTABS, clear_filename_seen_cache(), create_filename_seen_cache(), delete_filename_seen_cache(), do_cleanups(), error(), output_source_filename_data::filename_seen_cache, output_source_filename_data::first, have_full_symbols(), have_partial_symbols(), make_cleanup(), map_partial_symbol_filenames(), output_partial_symbol_filename(), output_source_filename(), printf_filtered(), and symtab_to_fullname().
const char* symbol_demangled_name (const struct general_symbol_info * gsymbol)
Definition at line 886 of file symtab.c.
References ada_decode_symbol(), language_ada, language_cplus, language_d, language_fortran, language_go, language_java, language_objc, and symbol_get_demangled_name().
static char* symbol_find_demangled_name (struct general_symbol_info * gsymbol, const char * mangled) [static]
Definition at line 607 of file symtab.c.
References d_demangle(), demangled_name_entry::demangled, gdb_demangle(), go_demangle(), language_auto, language_cplus, language_d, language_go, language_java, language_objc, language_unknown, and objc_demangle().
Referenced by symbol_set_names().
const char* symbol_get_demangled_name (const struct general_symbol_info * gsymbol)
Definition at line 502 of file symtab.c.
References general_symbol_info::ada_mangled, general_symbol_info::cplus_specific, cplus_specific::demangled_name, language_ada, language_cplus, general_symbol_info::language_specific, and general_symbol_info::mangled_lang.
Referenced by new_symbol_full(), symbol_demangled_name(), and symbol_natural_name().
static void symbol_init_cplus_specific (struct general_symbol_info * gsymbol, struct obstack * obstack) [static]
Definition at line 453 of file symtab.c.
References general_symbol_info::cplus_specific, gdb_assert, general_symbol_info::language_specific, and OBSTACK_ZALLOC.
Referenced by symbol_set_demangled_name().
int symbol_matches_domain (enum language symbol_language, domain_enum symbol_domain, domain_enum domain)
Definition at line 1851 of file symtab.c.
References language_ada, language_cplus, language_d, language_java, STRUCT_DOMAIN, and VAR_DOMAIN.
Referenced by ada_add_block_symbols(), iterate_over_symbols(), lookup_block_symbol(), lookup_partial_symbol(), map_block(), and match_partial_symbol().
const char* symbol_natural_name (const struct general_symbol_info * gsymbol)
Definition at line 861 of file symtab.c.
References ada_decode_symbol(), language_ada, language_cplus, language_d, language_fortran, language_go, language_java, language_objc, general_symbol_info::name, and symbol_get_demangled_name().
Referenced by symbol_search_name().
const char* symbol_search_name (const struct general_symbol_info * gsymbol)
Definition at line 915 of file symtab.c.
References language_ada, general_symbol_info::name, and symbol_natural_name().
void symbol_set_demangled_name (struct general_symbol_info * gsymbol, const char * name, struct obstack * obstack)
Definition at line 471 of file symtab.c.
References general_symbol_info::ada_mangled, general_symbol_info::cplus_specific, cplus_specific::demangled_name, language_ada, language_cplus, general_symbol_info::language_specific, general_symbol_info::mangled_lang, name, general_symbol_info::obstack, and symbol_init_cplus_specific().
Referenced by new_symbol_full(), symbol_set_language(), and symbol_set_names().
void symbol_set_language (struct general_symbol_info * gsymbol, enum language language , struct obstack * obstack)
Definition at line 526 of file symtab.c.
References general_symbol_info::ada_mangled, general_symbol_info::cplus_specific, gdb_assert, language_ada, language_cplus, language_d, language_fortran, language_go, language_java, language_objc, general_symbol_info::language_specific, memset(), general_symbol_info::obstack, and symbol_set_demangled_name().
void symbol_set_names (struct general_symbol_info * gsymbol, const char * linkage_name, int len, int copy_name, struct objfile * objfile)
Definition at line 713 of file symtab.c.
References create_demangled_names_hash(), demangled_name_entry::demangled, objfile_per_bfd_storage::demangled_names_hash, JAVA_PREFIX, JAVA_PREFIX_LEN, language_ada, language_go, language_java, len, demangled_name_entry::mangled, memcpy(), name, general_symbol_info::name, objfile::per_bfd, objfile_per_bfd_storage::storage_obstack, symbol_find_demangled_name(), symbol_set_demangled_name(), and xfree().
static void symtab_observer_executable_changed (void) [static]
Definition at line 5036 of file symtab.c.
References set_main_name().
static void symtab_symbol_info (char * regexp, enum search_domain kind, int from_tty) [static]
Definition at line 3803 of file symtab.c.
References _, symbol_search::block, do_cleanups(), gdb_assert, make_cleanup_free_search_symbols(), bound_minimal_symbol::minsym, symbol_search::msymbol, symbol_search::next, p, print_msymbol_info(), print_symbol_info(), printf_filtered(), QUIT, search_symbols(), symbol_search::symbol, symbol_search::symtab, symtab_to_filename_for_display(), and TYPES_DOMAIN.
Referenced by functions_info(), types_info(), and variables_info().
static void types_info (char * regexp, int from_tty) [static]
Definition at line 3866 of file symtab.c.
References symtab_symbol_info(), and TYPES_DOMAIN.
static void variables_info (char * regexp, int from_tty) [static]
Definition at line 3853 of file symtab.c.
References symtab_symbol_info(), and VARIABLES_DOMAIN.
VEC (CORE_ADDR)
Definition at line 2571 of file symtab.c.
References find_line_common(), linetable_entry::line, LINETABLE, linetable_entry::pc, VEC, and VEC_safe_push.
static VEC (char_ptr) [static]
Definition at line 4030 of file symtab.c.
References compare_symbol_name(), VEC_safe_push, word, and xmalloc().
Variable Documentation
int basenames_may_differ = 0
Definition at line 114 of file symtab.c.
Referenced by dw2_expand_symtabs_matching(), dw2_map_symtabs_matching_filename(), expand_symtabs_matching_via_partial(), function_name_is_marked_for_skip(), iterate_over_some_symtabs(), partial_map_symtabs_matching_filename(), read_psymtabs_with_fullname(), and search_symbols().
struct block* block_found
Definition at line 144 of file symtab.c.
Referenced by push_variable(), standard_lookup(), and write_dollar_variable().
enum language language_of_main = language_unknown
Definition at line 4956 of file symtab.c.
Referenced by read_partial_die(), and set_initial_language().
const char multiple_symbols_all[] = "all"
Definition at line 121 of file symtab.c.
Referenced by decode_line_2(), decode_line_full(), decode_linespec_default(), and user_select_syms().
const char multiple_symbols_ask[] = "ask"
Definition at line 120 of file symtab.c.
Referenced by decode_line_full().
const char multiple_symbols_cancel[] = "cancel"
Definition at line 122 of file symtab.c.
Referenced by decode_line_2(), decode_line_full(), and user_select_syms().
const char* multiple_symbols_mode = multiple_symbols_all [static]
Definition at line 130 of file symtab.c.
Referenced by multiple_symbols_select_mode().
const char* const multiple_symbols_modes[] [static]
Initial value:
{
  multiple_symbols_ask,
  multiple_symbols_all,
  multiple_symbols_cancel,
  NULL
}
Definition at line 123 of file symtab.c.
char* name_of_main [static]
Definition at line 4955 of file symtab.c.
Referenced by main_name().
int next_aclass_value = LOC_FINAL_VALUE [static]
Definition at line 5072 of file symtab.c.
struct symbol_impl symbol_impl[MAX_SYMBOL_IMPLS] [static]
Definition at line 5082 of file symtab.c.
struct symbol_impl* symbol_impls = &symbol_impl[0]
Definition at line 5087 of file symtab.c.
int symtab_create_debug = 0
Definition at line 109 of file symtab.c.
Referenced by allocate_psymtab(), allocate_symtab(), elf_symfile_read(), and install_minimal_symbols().