GDB (xrefs): /home/stan/gdb/src/gdb/symtab.h File Reference
/home/stan/gdb/src/gdb/symtab.h File Reference
#include "vec.h"
#include "gdb_vecs.h"
#include "gdbtypes.h"
#include "minsyms.h"
Classes
struct cplus_specific
struct general_symbol_info
struct minimal_symbol
struct symbol_computed_ops
struct symbol_block_ops
struct symbol_register_ops
struct symbol_impl
struct symbol
struct template_symbol
struct linetable_entry
struct linetable
struct section_offsets
struct symtab
struct field_of_this_result
struct gnu_ifunc_fns
struct symtab_and_line
struct symtabs_and_lines
struct symbol_search
Defines
#define SYMBOL_VALUE(symbol) (symbol)->ginfo.value.ivalue
#define SYMBOL_VALUE_ADDRESS(symbol) (symbol)->ginfo.value.address
#define SYMBOL_VALUE_BYTES(symbol) (symbol)->ginfo.value.bytes
#define SYMBOL_VALUE_COMMON_BLOCK(symbol) (symbol)->ginfo.value.common_block
#define SYMBOL_BLOCK_VALUE(symbol) (symbol)->ginfo.value.block
#define SYMBOL_VALUE_CHAIN(symbol) (symbol)->ginfo.value.chain
#define SYMBOL_LANGUAGE(symbol) (symbol)->ginfo.language
#define SYMBOL_SECTION(symbol) (symbol)->ginfo.section
#define SYMBOL_OBJ_SECTION(objfile, symbol)
#define SYMBOL_SET_LANGUAGE(symbol, language, obstack) (symbol_set_language (&(symbol)->ginfo, (language), (obstack)))
#define SYMBOL_SET_LINKAGE_NAME(symbol, linkage_name) (symbol)->ginfo.name = (linkage_name)
#define SYMBOL_SET_NAMES(symbol, linkage_name, len, copy_name, objfile) symbol_set_names (&(symbol)->ginfo, linkage_name, len, copy_name, objfile)
#define SYMBOL_NATURAL_NAME(symbol) (symbol_natural_name (&(symbol)->ginfo))
#define SYMBOL_LINKAGE_NAME(symbol) (symbol)->ginfo.name
#define SYMBOL_DEMANGLED_NAME(symbol) (symbol_demangled_name (&(symbol)->ginfo))
#define SYMBOL_PRINT_NAME(symbol) (demangle ? SYMBOL_NATURAL_NAME (symbol) : SYMBOL_LINKAGE_NAME (symbol))
#define SYMBOL_SEARCH_NAME(symbol) (symbol_search_name (&(symbol)->ginfo))
#define SYMBOL_MATCHES_SEARCH_NAME(symbol, name) (strcmp_iw (SYMBOL_SEARCH_NAME (symbol), (name)) == 0)
#define MSYMBOL_TARGET_FLAG_1(msymbol) (msymbol)->target_flag_1
#define MSYMBOL_TARGET_FLAG_2(msymbol) (msymbol)->target_flag_2
#define MSYMBOL_SIZE(msymbol) ((msymbol)->size + 0)
#define SET_MSYMBOL_SIZE(msymbol, sz)
#define MSYMBOL_HAS_SIZE(msymbol) ((msymbol)->has_size + 0)
#define MSYMBOL_TYPE(msymbol) (msymbol)->type
#define SYMBOL_ACLASS_BITS 6
#define SYMBOL_DOMAIN(symbol) (symbol)->domain
#define SYMBOL_IMPL(symbol) (symbol_impls[(symbol)->aclass_index])
#define SYMBOL_ACLASS_INDEX(symbol) (symbol)->aclass_index
#define SYMBOL_CLASS(symbol) (SYMBOL_IMPL (symbol).aclass)
#define SYMBOL_IS_ARGUMENT(symbol) (symbol)->is_argument
#define SYMBOL_INLINED(symbol) (symbol)->is_inlined
#define SYMBOL_IS_CPLUS_TEMPLATE_FUNCTION(symbol) (symbol)->is_cplus_template_function
#define SYMBOL_TYPE(symbol) (symbol)->type
#define SYMBOL_LINE(symbol) (symbol)->line
#define SYMBOL_SYMTAB(symbol) (symbol)->symtab
#define SYMBOL_COMPUTED_OPS(symbol) (SYMBOL_IMPL (symbol).ops_computed)
#define SYMBOL_BLOCK_OPS(symbol) (SYMBOL_IMPL (symbol).ops_block)
#define SYMBOL_REGISTER_OPS(symbol) (SYMBOL_IMPL (symbol).ops_register)
#define SYMBOL_LOCATION_BATON(symbol) (symbol)->aux_value
#define SYMBOL_OBJFILE(symbol) (SYMBOL_SYMTAB (symbol)->objfile)
#define ANOFFSET(secoff, whichone)
#define SIZEOF_N_SECTION_OFFSETS(n)
#define BLOCKVECTOR(symtab) (symtab)->blockvector
#define LINETABLE(symtab) (symtab)->linetable
#define SYMTAB_PSPACE(symtab) (symtab)->objfile->pspace
#define VTBL_FNADDR_OFFSET 2
#define gnu_ifunc_resolve_addr gnu_ifunc_fns_p->gnu_ifunc_resolve_addr
#define gnu_ifunc_resolve_name gnu_ifunc_fns_p->gnu_ifunc_resolve_name
#define gnu_ifunc_resolver_stop gnu_ifunc_fns_p->gnu_ifunc_resolver_stop
#define gnu_ifunc_resolver_return_stop gnu_ifunc_fns_p->gnu_ifunc_resolver_return_stop
Typedefs
typedef enum domain_enum_tag domain_enum
typedef struct symtab * symtab_ptr
typedef int(symbol_found_callback_ftype)(struct symbol *sym, void *data)
Enumerations
enum minimal_symbol_type {
mst_unknown = 0, mst_text, mst_text_gnu_ifunc, mst_slot_got_plt,
mst_data, mst_bss, mst_abs, mst_solib_trampoline,
mst_file_text, mst_file_data, mst_file_bss
}
enum domain_enum_tag {
UNDEF_DOMAIN, VAR_DOMAIN, STRUCT_DOMAIN, LABEL_DOMAIN,
COMMON_BLOCK_DOMAIN
}
enum search_domain { VARIABLES_DOMAIN = 0, FUNCTIONS_DOMAIN = 1, TYPES_DOMAIN = 2, ALL_DOMAIN = 3 }
enum address_class {
LOC_UNDEF, LOC_CONST, LOC_STATIC, LOC_REGISTER,
LOC_ARG, LOC_REF_ARG, LOC_REGPARM_ADDR, LOC_LOCAL,
LOC_TYPEDEF, LOC_LABEL, LOC_BLOCK, LOC_CONST_BYTES,
LOC_UNRESOLVED, LOC_OPTIMIZED_OUT, LOC_COMPUTED, LOC_COMMON_BLOCK,
LOC_FINAL_VALUE
}
enum print_source_lines_flags { PRINT_SOURCE_LINES_NOERROR = (1 << 0), PRINT_SOURCE_LINES_FILENAME = (1 << 1) }
Functions
void symbol_set_demangled_name (struct general_symbol_info *, const char *, struct obstack *)
const char * symbol_get_demangled_name (const struct general_symbol_info *)
CORE_ADDR symbol_overlayed_address (CORE_ADDR, struct obj_section *)
void symbol_set_language (struct general_symbol_info *symbol, enum language language, struct obstack *obstack)
void symbol_set_names (struct general_symbol_info *symbol, const char *linkage_name, int len, int copy_name, struct objfile *objfile)
const char * symbol_natural_name (const struct general_symbol_info *symbol)
const char * symbol_demangled_name (const struct general_symbol_info *symbol)
const char * symbol_search_name (const struct general_symbol_info *)
const char * domain_name (domain_enum)
const char * search_domain_name (enum search_domain)
int register_symbol_computed_impl (enum address_class, const struct symbol_computed_ops *)
int register_symbol_block_impl (enum address_class aclass, const struct symbol_block_ops *ops)
int register_symbol_register_impl (enum address_class, const struct symbol_register_ops *)
DEF_VEC_P (symtab_ptr)
const char * multiple_symbols_select_mode (void)
int symbol_matches_domain (enum language symbol_language, domain_enum symbol_domain, domain_enum domain)
struct symtab * lookup_symtab (const char *)
struct symbol * lookup_symbol_in_language (const char *, const struct block *, const domain_enum, enum language, struct field_of_this_result *)
struct symbol * lookup_symbol (const char *, const struct block *, const domain_enum, struct field_of_this_result *)
struct symbol * basic_lookup_symbol_nonlocal (const char *, const struct block *, const domain_enum)
struct symbol * lookup_symbol_static (const char *name, const struct block *block, const domain_enum domain)
struct symbol * lookup_symbol_global (const char *name, const struct block *block, const domain_enum domain)
struct symbol * lookup_symbol_aux_block (const char *name, const struct block *block, const domain_enum domain)
struct symbol * lookup_language_this (const struct language_defn *lang, const struct block *block)
struct symbol * lookup_static_symbol_aux (const char *name, const domain_enum domain)
struct symbol * lookup_block_symbol (const struct block *, const char *, const domain_enum)
struct type * lookup_struct (const char *, const struct block *)
struct type * lookup_union (const char *, const struct block *)
struct type * lookup_enum (const char *, const struct block *)
struct symbol * find_pc_function (CORE_ADDR)
struct symbol * find_pc_sect_function (CORE_ADDR, struct obj_section *)
int find_pc_partial_function_gnu_ifunc (CORE_ADDR pc, const char **name, CORE_ADDR *address, CORE_ADDR *endaddr, int *is_gnu_ifunc_p)
int find_pc_partial_function (CORE_ADDR, const char **, CORE_ADDR *, CORE_ADDR *)
void clear_pc_function_cache (void)
struct symtab * find_pc_sect_symtab_via_partial (CORE_ADDR, struct obj_section *)
struct symtab * find_pc_symtab (CORE_ADDR)
struct symtab * find_pc_sect_symtab (CORE_ADDR, struct obj_section *)
int find_pc_line_pc_range (CORE_ADDR, CORE_ADDR *, CORE_ADDR *)
void reread_symbols (void)
struct type * lookup_transparent_type (const char *)
struct type * basic_lookup_transparent_type (const char *)
int in_gnu_ifunc_stub (CORE_ADDR pc)
CORE_ADDR find_solib_trampoline_target (struct frame_info *, CORE_ADDR)
void init_sal (struct symtab_and_line *sal)
struct symtab_and_line find_pc_line (CORE_ADDR, int)
struct symtab_and_line find_pc_sect_line (CORE_ADDR, struct obj_section *, int)
int find_line_pc (struct symtab *, int, CORE_ADDR *)
int find_line_pc_range (struct symtab_and_line, CORE_ADDR *, CORE_ADDR *)
void resolve_sal_pc (struct symtab_and_line *)
void clear_solib (void)
int identify_source_line (struct symtab *, int, int, CORE_ADDR)
void print_source_lines (struct symtab *, int, int, enum print_source_lines_flags)
void forget_cached_source_info_for_objfile (struct objfile *)
void forget_cached_source_info (void)
void select_source_symtab (struct symtab *)
VEC (char_ptr)*default_make_symbol_completion_list_break_on(const char *text
const char enum type_code
const char const char enum
type_code const char const
char const char const char
const char *int matching_obj_sections (struct obj_section *, struct obj_section *)
struct symtab * find_line_symtab (struct symtab *, int, int *, int *)
struct symtab_and_line find_function_start_sal (struct symbol *sym, int)
void skip_prologue_sal (struct symtab_and_line *)
void clear_symtab_users (int add_flags)
enum language deduce_language_from_filename (const char *)
int in_prologue (struct gdbarch *gdbarch, CORE_ADDR pc, CORE_ADDR func_start)
CORE_ADDR skip_prologue_using_sal (struct gdbarch *gdbarch, CORE_ADDR func_addr)
struct symbol * fixup_symbol_section (struct symbol *, struct objfile *)
void search_symbols (char *, enum search_domain, int, char **, struct symbol_search **)
void free_search_symbols (struct symbol_search *)
struct cleanup * make_cleanup_free_search_symbols (struct symbol_search **)
void set_main_name (const char *name)
char * main_name (void)
struct symbol * lookup_global_symbol_from_objfile (const struct objfile *, const char *name, const domain_enum domain)
int producer_is_realview (const char *producer)
void fixup_section (struct general_symbol_info *ginfo, CORE_ADDR addr, struct objfile *objfile)
struct objfile * lookup_objfile_from_block (const struct block *block)
int compare_filenames_for_search (const char *filename, const char *search_name)
int iterate_over_some_symtabs (const char *name, const char *real_path, int(*callback)(struct symtab *symtab, void *data), void *data, struct symtab *first, struct symtab *after_last)
void iterate_over_symtabs (const char *name, int(*callback)(struct symtab *symtab, void *data), void *data)
DEF_VEC_I (CORE_ADDR)
VEC (CORE_ADDR)*find_pcs_for_symtab_line(struct symtab *symtab
void iterate_over_symbols (const struct block *block, const char *name, const domain_enum domain, symbol_found_callback_ftype *callback, void *data)
struct cleanup * demangle_for_lookup (const char *name, enum language lang, const char **result_name)
struct symbol * allocate_symbol (struct objfile *)
void initialize_symbol (struct symbol *)
struct template_symbol * allocate_template_symbol (struct objfile *)
Variables
int demangle
struct symbol_impl * symbol_impls
int currently_reading_symtab
const char multiple_symbols_ask []
const char multiple_symbols_all []
const char multiple_symbols_cancel []
struct gnu_ifunc_fns * gnu_ifunc_fns_p
const char * word
const char const char * break_on
const char const char enum
type_code code
enum language language_of_main
int symtab_create_debug
int basenames_may_differ
int line
int struct linetable_entry ** best_entry
Define Documentation
#define ANOFFSET (secoff, whichone)
Value:
((whichone == -1)                         \
   ? (internal_error (__FILE__, __LINE__, \
                      _("Section index is uninitialized")), -1) \
   : secoff->offsets[whichone])
Definition at line 818 of file symtab.h.
Referenced by add_address_entry(), add_partial_subprogram(), add_partial_symbol(), amd64_windows_find_unwind_info(), coff_symtab_read(), create_addrmap_from_index(), dsbt_relocate_main_executable(), dump_psymtab(), dwarf2_frame_find_fde(), dwarf2_per_cu_text_offset(), dwarf2_ranges_read(), dwarf_decode_lines_1(), elf_symfile_relocate_probe(), elf_symtab_read(), enable_break(), enter_line_range(), enter_linenos(), execute_cfa_program(), fixup_section(), frv_relocate_main_executable(), handle_stap_probe(), hppabsd_find_global_pointer(), init_objfile_sect_indices(), macho_symtab_add_minsym(), new_symbol_full(), objfile_relocate1(), parse_partial_symbols(), parse_symbol(), process_coff_symbol(), process_full_comp_unit(), process_one_symbol(), process_psymtab_comp_unit_reader(), process_xcoff_symbol(), psymtab_to_symtab_1(), read_alphacoff_dynamic_symtab(), read_call_site_scope(), read_dbx_dynamic_symtab(), read_dbx_symtab(), read_file_scope(), read_func_scope(), read_lexical_block_scope(), read_pe_exported_syms(), read_unwind_info(), read_xcoff_symtab(), record_minimal_symbol(), relocate_one_symbol(), relocate_psymtabs(), scan_xcoff_symtab(), som_solib_section_offsets(), and var_decode_location().
#define BLOCKVECTOR (symtab) (symtab)->blockvector
Definition at line 940 of file symtab.h.
Referenced by add_block(), add_class_symtab_symbol(), basic_lookup_transparent_type(), basic_lookup_transparent_type_quick(), block_iter_match_step(), block_iter_name_step(), block_iterator_step(), block_lookup(), blockvector_for_pc_sect(), count_symtabs_and_blocks(), dump_symtab_1(), dw2_lookup_symbol(), find_pc_sect_line(), find_pc_sect_symtab(), gdb_listfuncs(), get_java_class_symtab(), iterate_over_all_matching_symtabs(), iterate_over_file_blocks(), lookup_global_symbol_from_objfile(), lookup_objfile_from_block(), lookup_symbol_aux_objfile(), lookup_symbol_aux_psymtabs(), lookup_symbol_aux_quick(), maintenance_check_psymtabs(), make_symbol_overload_list_qualified(), map_matching_symbols_psymtab(), new_symtab(), objfile_relocate1(), parse_exp_in_context_1(), parse_procedure(), parse_symbol(), patch_opaque_types(), psymtab_to_symtab_1(), recursively_find_pc_sect_symtab(), search_symbols(), sort_blocks(), spu_catch_start(), stpy_global_block(), stpy_static_block(), and VEC().
#define gnu_ifunc_resolve_addr gnu_ifunc_fns_p->gnu_ifunc_resolve_addr
Definition at line 1149 of file symtab.h.
Referenced by find_function_addr().
#define gnu_ifunc_resolve_name gnu_ifunc_fns_p->gnu_ifunc_resolve_name
Definition at line 1150 of file symtab.h.
Referenced by set_breakpoint_location_function().
#define gnu_ifunc_resolver_return_stop gnu_ifunc_fns_p->gnu_ifunc_resolver_return_stop
Definition at line 1152 of file symtab.h.
Referenced by bpstat_what().
#define gnu_ifunc_resolver_stop gnu_ifunc_fns_p->gnu_ifunc_resolver_stop
Definition at line 1151 of file symtab.h.
Referenced by bpstat_what().
#define LINETABLE (symtab) (symtab)->linetable
Definition at line 941 of file symtab.h.
Referenced by dump_symtab_1(), finalize_symtab(), find_line_pc(), find_line_symtab(), find_pc_sect_line(), mi_cmd_symbol_list_lines(), new_symtab(), objfile_relocate1(), psymtab_to_symtab_1(), skip_prologue_using_lineinfo(), skip_prologue_using_sal(), and VEC().
#define MSYMBOL_HAS_SIZE (msymbol) ((msymbol)->has_size + 0)
Definition at line 390 of file symtab.h.
Referenced by build_address_symbolic().
#define MSYMBOL_SIZE (msymbol) ((msymbol)->size + 0)
Definition at line 383 of file symtab.h.
Referenced by build_address_symbolic(), elf_gnu_ifunc_resolve_by_got(), elf_symtab_read(), end_psymtab(), find_pc_partial_function_gnu_ifunc(), ld_so_xfer_auxv(), lookup_minimal_symbol_by_pc_section_1(), mips_skip_pic_trampoline_code(), and spu_get_overlay_table().
#define MSYMBOL_TARGET_FLAG_1 (msymbol) (msymbol)->target_flag_1
Definition at line 381 of file symtab.h.
Referenced by mips_elf_make_msymbol_special(), msymbol_is_mips(), msymbol_is_mips16(), prim_record_minimal_symbol_full(), and sh64_elf_make_msymbol_special().
#define MSYMBOL_TARGET_FLAG_2 (msymbol) (msymbol)->target_flag_2
Definition at line 382 of file symtab.h.
Referenced by mips_elf_make_msymbol_special(), msymbol_is_micromips(), msymbol_is_mips(), and prim_record_minimal_symbol_full().
#define MSYMBOL_TYPE (msymbol) (msymbol)->type
Definition at line 391 of file symtab.h.
Referenced by ada_has_this_exception_support(), ada_lookup_simple_minsym(), add_pe_forwarded_sym(), build_address_symbolic(), coff_symfile_read(), compact_minimal_symbols(), compare_msyms(), create_std_terminate_master_breakpoint(), dump_msymbols(), elf_gnu_ifunc_resolve_by_got(), find_pc_partial_function_gnu_ifunc(), find_pc_sect_line(), find_pc_sect_symtab(), find_pc_sect_symtab_via_partial(), find_solib_trampoline_target(), hppa_hpux_skip_trampoline_code(), in_gnu_ifunc_stub(), lookup_minimal_symbol_by_pc_section_1(), lookup_minimal_symbol_internal(), lookup_minimal_symbol_solib_trampoline(), lookup_minimal_symbol_text(), lookup_solib_trampoline_symbol_by_pc(), prim_record_minimal_symbol_full(), scan_file_globals(), search_minsyms_for_name(), search_symbols(), som_solib_desire_dynamic_linker_symbols(), terminate_minimal_symbol_table(), and write_exp_msymbol().
#define SET_MSYMBOL_SIZE (msymbol, sz)
Value:
do                                              \
    {                                           \
      (msymbol)->size = sz;                     \
      (msymbol)->has_size = 1;                  \
    } while (0)
Definition at line 384 of file symtab.h.
Referenced by elf_rel_plt_read(), elf_symtab_read(), and ppc64_elf_make_msymbol_special().
#define SIZEOF_N_SECTION_OFFSETS (n)
Value:
(sizeof (struct section_offsets) \
   + sizeof (((struct section_offsets *) 0)->offsets) * ((n)-1))
Definition at line 825 of file symtab.h.
Referenced by default_symfile_offsets(), elfstab_offset_sections(), get_offsets(), macho_symfile_offsets(), objfile_rebase1(), objfile_relocate(), objfile_relocate1(), relative_addr_info_to_section_offsets(), reread_symbols(), solib_target_relocate_section_addresses(), som_symfile_offsets(), and syms_from_objfile_1().
#define SYMBOL_ACLASS_BITS 6
Definition at line 646 of file symtab.h.
#define SYMBOL_ACLASS_INDEX (symbol) (symbol)->aclass_index
Definition at line 721 of file symtab.h.
Referenced by add_class_symbol(), coff_read_enum_type(), common_block_end(), define_symbol(), dwarf2_const_value(), dwarf2_symbol_mark_computed(), finalize_symtab(), fixup_go_packaging(), mark_common_block_symbol_computed(), new_symbol_full(), parse_symbol(), patch_block_stabs(), process_coff_symbol(), process_xcoff_symbol(), psymtab_to_symtab_1(), read_enum_type(), scan_file_globals(), and var_decode_location().
#define SYMBOL_BLOCK_OPS (symbol) (SYMBOL_IMPL (symbol).ops_block)
Definition at line 731 of file symtab.h.
Referenced by dwarf_expr_frame_base_1().
#define SYMBOL_BLOCK_VALUE (symbol) (symbol)->ginfo.value.block
Definition at line 194 of file symtab.h.
Referenced by address_info(), block_lookup(), build_address_symbolic(), check_exception_resume(), default_read_var_value(), dwarf2_find_location_expression(), finalize_symtab(), find_frame_funname(), find_function_return_type(), find_function_start_sal(), find_pc_partial_function_gnu_ifunc(), finish_block_internal(), fixup_symbol_section(), func_addr_to_tail_call_list(), gen_var_ref(), get_pc_function_start(), inline_frame_this_id(), parse_procedure(), parse_symbol(), print_frame_arg_vars(), print_frame_args(), print_symbol(), scope_info(), skip_prologue_sal(), until_next_command(), value_fn_field(), and watchpoint_check().
#define SYMBOL_CLASS (symbol) (SYMBOL_IMPL (symbol).aclass)
Definition at line 722 of file symtab.h.
Referenced by ada_add_block_symbols(), ada_args_match(), ada_exception_sal(), ada_find_any_type_symbol(), ada_has_this_exception_support(), ada_parse_renaming(), add_template_parameters(), address_info(), aux_add_nonlocal_symbols(), block_lookup(), c_type_print_template_args(), classify_inner_name(), cleanup_undefined_types_1(), collect_one_symbol(), collect_symbol(), collect_symbols(), completion_list_add_fields(), const_var_ref(), cp_lookup_rtti_type(), default_read_var_value(), define_symbol(), find_function_in_inferior(), find_primitive_type(), fixup_go_packaging(), fixup_symbol_section(), gdb_block_vars(), gdb_get_blocks(), gdb_get_vars_command(), gdb_listfuncs(), gen_var_ref(), info_common_command_for_block(), is_nonfunction(), iterate_over_block_locals(), lesseq_defined_than(), list_args_or_locals(), lookup_typename(), mi_should_print(), mylookup_symbol(), new_symbol_full(), old_renaming_is_invisible(), package_name_p(), parse_procedure(), patch_opaque_types(), print_frame_args(), print_symbol(), print_symbol_info(), push_variable(), read_type(), relocate_one_symbol(), remove_extra_symbols(), remove_irrelevant_renamings(), resolve_subexp(), scan_file_globals(), scope_info(), search_symbols(), select_possible_type_sym(), symbol_read_needs_frame(), symbol_to_sal(), sympy_get_addr_class(), sympy_is_constant(), sympy_is_function(), sympy_is_variable(), sympy_value(), typy_template_argument(), user_select_syms(), validate_actionline(), watchpoint_exp_is_const(), write_name_assoc(), write_object_renaming(), and yylex().
#define SYMBOL_COMPUTED_OPS (symbol) (SYMBOL_IMPL (symbol).ops_computed)
Definition at line 730 of file symtab.h.
Referenced by address_info(), default_read_var_value(), evaluate_subexp_standard(), gen_var_ref(), read_frame_arg(), scope_info(), symbol_read_needs_frame(), and var_decode_location().
#define SYMBOL_DEMANGLED_NAME (symbol) (symbol_demangled_name (&(symbol)->ginfo))
Definition at line 254 of file symtab.h.
Referenced by cp_scan_for_anonymous_namespaces(), cp_set_block_scope(), dump_msymbols(), dump_symtab_1(), find_oload_champ(), gdb_listfuncs(), gnuv3_get_typename_from_type_info(), gnuv3_rtti_type(), gnuv3_skip_trampoline(), and print_partial_symbols().
#define SYMBOL_DOMAIN (symbol) (symbol)->domain
Definition at line 719 of file symtab.h.
Referenced by ada_add_block_symbols(), add_class_symbol(), cleanup_undefined_types_1(), coff_read_enum_type(), define_symbol(), finalize_symtab(), find_pc_sect_psymbol(), fixup_go_packaging(), info_common_command_for_block(), iterate_over_block_locals(), iterate_over_symbols(), lesseq_defined_than(), lookup_block_symbol(), lookup_partial_symbol(), maintenance_check_psymtabs(), map_block(), match_partial_symbol(), mylookup_symbol(), new_symbol_full(), parse_procedure(), parse_symbol(), patch_block_stabs(), patch_opaque_types(), print_partial_symbols(), print_symbol(), print_symbol_info(), process_coff_symbol(), process_xcoff_symbol(), psymtab_to_symtab_1(), read_enum_type(), read_type(), resolve_subexp(), and write_ambiguous_var().
#define SYMBOL_IMPL (symbol) (symbol_impls[(symbol)->aclass_index])
Definition at line 720 of file symtab.h.
#define SYMBOL_INLINED (symbol) (symbol)->is_inlined
Definition at line 724 of file symtab.h.
Referenced by block_inlined_p(), iterate_inline_only(), and new_symbol_full().
#define SYMBOL_IS_ARGUMENT (symbol) (symbol)->is_argument
Definition at line 723 of file symtab.h.
Referenced by ada_add_block_symbols(), address_info(), aux_add_nonlocal_symbols(), check_exception_resume(), define_symbol(), finish_block_internal(), iterate_over_block_arg_vars(), iterate_over_block_locals(), list_arg_or_local(), list_args_or_locals(), lookup_block_symbol(), mi_should_print(), new_symbol_full(), parse_symbol(), print_frame_args(), print_symbol(), process_coff_symbol(), scope_info(), sympy_is_argument(), and sympy_is_variable().
#define SYMBOL_IS_CPLUS_TEMPLATE_FUNCTION (symbol) (symbol)->is_cplus_template_function
Definition at line 725 of file symtab.h.
Referenced by cp_lookup_symbol_imports_or_template().
#define SYMBOL_LANGUAGE (symbol) (symbol)->ginfo.language
Definition at line 196 of file symtab.h.
Referenced by ada_add_block_symbols(), cp_lookup_symbol_imports_or_template(), define_symbol(), extract_sym(), find_frame_funname(), fixup_go_packaging(), frame_info(), gen_expr(), go_symbol_package_name(), iterate_over_symbols(), list_arg_or_local(), lookup_block_symbol(), lookup_partial_symbol(), map_block(), match_partial_symbol(), moxie_skip_prologue(), mt_skip_prologue(), parse_exp_in_context_1(), parse_symbol(), print_frame_arg(), process_one_symbol(), py_print_single_arg(), read_var_value(), set_initial_language(), write_ambiguous_var(), write_psymbols(), and xstormy16_skip_prologue().
#define SYMBOL_LINE (symbol) (symbol)->line
Definition at line 728 of file symtab.h.
Referenced by define_symbol(), find_frame_sal(), new_symbol_full(), skip_prologue_sal(), symbol_to_sal(), sympy_line(), and user_select_syms().
#define SYMBOL_LINKAGE_NAME (symbol) (symbol)->ginfo.name
Definition at line 250 of file symtab.h.
Referenced by ada_add_block_symbols(), ada_find_renaming_symbol(), ada_has_this_exception_support(), ada_lookup_simple_minsym(), ada_parse_renaming(), ada_read_renaming_var_value(), add_minsym_to_hash_table(), add_template_parameters(), address_info(), amd64_skip_main_prologue(), amd64_windows_skip_trampoline_code(), arm_pe_skip_trampoline_code(), arm_skip_stack_protector(), arm_wince_skip_main_prologue(), build_address_symbolic(), build_minimal_symbol_hash_tables(), c_print_typedef(), c_type_print_template_args(), c_val_print(), cleanup_undefined_types_1(), coff_read_enum_type(), coff_symfile_read(), common_block_end(), compact_minimal_symbols(), compare_minimal_symbols(), convert_code_addr_to_desc_addr(), default_read_var_value(), define_symbol(), dump_msymbols(), dump_symtab_1(), find_old_style_renaming_symbol(), find_pc_partial_function_gnu_ifunc(), find_pc_sect_line(), find_solib_trampoline_target(), find_symbol_in_list(), frv_fdpic_find_canonical_descriptor(), frv_skip_main_prologue(), ftrace_function_switched(), gdb_search(), gen_var_ref(), get_prev_frame_1(), gnuv2_value_rtti_type(), gnuv3_get_typename_from_type_info(), go_symbol_package_name(), hppa32_hpux_in_solib_call_trampoline(), hppa_hpux_find_import_stub_for_addr(), hppa_hpux_skip_trampoline_code(), hppa_lookup_stub_minimal_symbol(), i386_pe_skip_trampoline_code(), i386_skip_main_prologue(), ia64_convert_from_func_ptr_addr(), info_checkpoints_command(), info_common_command_for_block(), insert_exception_resume_breakpoint(), iterate_over_block_arg_vars(), iterate_over_minimal_symbols(), lesseq_defined_than(), list_args_or_locals(), lookup_minimal_symbol_and_objfile(), lookup_minimal_symbol_by_pc_name(), lookup_minimal_symbol_internal(), lookup_minimal_symbol_solib_trampoline(), lookup_minimal_symbol_text(), m2_print_typedef(), m32c_m16c_address_to_pointer(), m32c_m16c_pointer_to_address(), maintenance_check_psymtabs(), mips_skip_pic_trampoline_code(), mips_stub_frame_sniffer(), msp430_skip_trampoline_code(), mylookup_symbol(), overload_list_add_symbol(), parse_symbol(), pascal_val_print(), patch_opaque_types(), powerpc_linux_in_dynsym_resolve_code(), print_frame_args(), print_partial_symbols(), print_symbol(), process_coff_symbol(), process_enumeration_scope(), rbreak_command(), read_atcb(), read_enum_type(), read_type(), remove_extra_symbols(), remove_irrelevant_renamings(), resolve_subexp(), rs6000_skip_main_prologue(), rs6000_skip_trampoline_code(), scan_file_globals(), scope_info(), search_symbols(), set_traceframe_context(), skip_prologue_function(), skip_prologue_sal(), som_solib_create_inferior_hook(), sort_choices(), sympy_get_linkage_name(), VEC(), and write_ambiguous_var().
#define SYMBOL_LOCATION_BATON (symbol) (symbol)->aux_value
Definition at line 733 of file symtab.h.
Referenced by dwarf2_const_value(), dwarf2_symbol_mark_computed(), locexpr_describe_location(), locexpr_find_frame_base_location(), locexpr_read_needs_frame(), locexpr_read_variable(), locexpr_read_variable_at_entry(), locexpr_tracepoint_var_ref(), loclist_describe_location(), loclist_find_frame_base_location(), loclist_read_variable(), loclist_read_variable_at_entry(), loclist_tracepoint_var_ref(), and mark_common_block_symbol_computed().
#define SYMBOL_MATCHES_SEARCH_NAME (symbol, name) (strcmp_iw (SYMBOL_SEARCH_NAME (symbol), (name)) == 0)
Definition at line 285 of file symtab.h.
Referenced by iterate_over_minimal_symbols(), lookup_minimal_symbol_internal(), and lookup_partial_symbol().
#define SYMBOL_NATURAL_NAME (symbol) (symbol_natural_name (&(symbol)->ginfo))
Definition at line 240 of file symtab.h.
Referenced by ada_print_subexp(), aggregate_assign_from_choices(), canonicalize_linespec(), classes_info(), completion_list_objc_symbol(), convert_linespec_to_sals(), cp_lookup_symbol_imports_or_template(), create_sals_line_offset(), dwarf2_symbol_mark_computed(), dwarf_expr_frame_base_1(), encode_actions_1(), find_imps(), find_methods(), find_overload_match(), minsym_found(), overload_list_add_symbol(), search_symbol_list(), search_symbols(), selectors_info(), and sympy_get_name().
#define SYMBOL_OBJ_SECTION (objfile, symbol)
Value:
(((symbol)->ginfo.section >= 0)                         \
   ? (&(((objfile)->sections)[(symbol)->ginfo.section]))        \
   : NULL)
Definition at line 198 of file symtab.h.
Referenced by address_info(), default_read_var_value(), dump_msymbols(), elf_gnu_ifunc_record_cache(), find_function_start_sal(), find_pc_sect_psymbol(), find_pc_sect_symtab(), fixup_symbol_section(), hppa64_hpux_in_solib_call_trampoline(), jump_command(), lookup_minimal_symbol_by_pc_section_1(), maintenance_translate_address(), minsym_found(), print_symbol(), resolve_sal_pc(), skip_prologue_sal(), spu_catch_start(), and write_exp_msymbol().
#define SYMBOL_OBJFILE (symbol) (SYMBOL_SYMTAB (symbol)->objfile)
Definition at line 734 of file symtab.h.
Referenced by address_info(), default_read_var_value(), find_function_start_sal(), jump_command(), print_symbol(), and skip_prologue_sal().
#define SYMBOL_PRINT_NAME (symbol) (demangle ? SYMBOL_NATURAL_NAME (symbol) : SYMBOL_LINKAGE_NAME (symbol))
Definition at line 269 of file symtab.h.
Referenced by address_info(), address_of_variable(), btrace_func_history(), build_address_symbolic(), c_print_token(), c_print_typedef(), c_val_print(), call_site_find_chain_1(), call_site_for_pc(), call_site_to_target_addr(), collect_symbol(), compare_classes(), compare_search_syms(), compare_selectors(), default_read_var_value(), dump_subexp_body_standard(), dwarf2_const_value(), dwarf_expr_reg_to_entry_parameter(), edit_command(), evaluate_subexp_standard(), extract_sym(), find_frame_funname(), finish_block_internal(), frame_info(), ftrace_print_function_name(), func_verify_no_selftailcall(), gdb_block_vars(), gdb_get_vars_command(), gdb_listfuncs(), gdb_search(), gen_expr(), gen_maybe_namespace_elt(), gen_var_ref(), get_function_name(), hppa_hpux_skip_trampoline_code(), info_cb(), info_common_command_for_block(), iterate_over_block_arg_vars(), iterate_over_block_locals(), jump_command(), list_arg_or_local(), list_command(), locexpr_describe_location_1(), locexpr_describe_location_piece(), loclist_describe_location(), m2_print_typedef(), maintenance_translate_address(), pascal_print_typedef(), pascal_val_print(), print_breakpoint_location(), print_frame_arg(), print_msymbol_info(), print_one_static_tracepoint_marker(), print_subexp_standard(), print_symbol(), print_symbol_info(), print_variable_and_value(), py_print_frame(), py_print_single_arg(), rbreak_command(), resolve_subexp(), return_command(), scan_file_globals(), scope_info(), stab_reg_to_regnum(), sym_info(), sympy_str(), tailcall_dump(), update_static_tracepoint(), user_select_syms(), validate_actionline(), and value_of_variable().
#define SYMBOL_REGISTER_OPS (symbol) (SYMBOL_IMPL (symbol).ops_register)
Definition at line 732 of file symtab.h.
Referenced by address_info(), collect_symbol(), default_read_var_value(), gen_var_ref(), and scope_info().
#define SYMBOL_SEARCH_NAME (symbol) (symbol_search_name (&(symbol)->ginfo))
Definition at line 278 of file symtab.h.
Referenced by add_minsym_to_demangled_hash_table(), build_minimal_symbol_hash_tables(), compare_psymbols(), dw2_lookup_symbol(), insert_symbol_hashed(), iter_match_first_hashed(), iter_match_next_hashed(), iter_match_next_linear(), lookup_partial_symbol(), lookup_symbol_aux_psymtabs(), match_partial_symbol(), new_symbol_full(), recursively_search_psymtabs(), and write_psymbols().
#define SYMBOL_SECTION (symbol) (symbol)->ginfo.section
Definition at line 197 of file symtab.h.
Referenced by add_psymbol_to_bcache(), allocate_symbol(), allocate_template_symbol(), coff_symtab_read(), find_pc_partial_function_gnu_ifunc(), fixup_psymbol_section(), fixup_section(), initialize_symbol(), objfile_relocate1(), prim_record_minimal_symbol_full(), process_coff_symbol(), process_xcoff_symbol(), read_xcoff_symtab(), relocate_one_symbol(), relocate_psymtabs(), scan_file_globals(), and var_decode_location().
#define SYMBOL_SET_LANGUAGE (symbol, language, obstack) (symbol_set_language (&(symbol)->ginfo, (language), (obstack)))
Definition at line 205 of file symtab.h.
Referenced by add_class_symbol(), add_psymbol_to_bcache(), define_symbol(), fixup_go_packaging(), new_symbol(), new_symbol_full(), prim_record_minimal_symbol_full(), process_coff_symbol(), read_enum_type(), and terminate_minimal_symbol_table().
#define SYMBOL_SET_LINKAGE_NAME (symbol, linkage_name) (symbol)->ginfo.name = (linkage_name)
Definition at line 216 of file symtab.h.
Referenced by add_class_symbol(), coff_read_enum_type(), common_block_end(), define_symbol(), parse_symbol(), patch_block_stabs(), process_xcoff_symbol(), and read_enum_type().
#define SYMBOL_SET_NAMES (symbol, linkage_name, len, copy_name, objfile) symbol_set_names (&(symbol)->ginfo, linkage_name, len, copy_name, objfile)
Definition at line 221 of file symtab.h.
Referenced by add_psymbol_to_bcache(), define_symbol(), fixup_go_packaging(), new_symbol(), new_symbol_full(), prim_record_minimal_symbol_full(), and process_coff_symbol().
#define SYMBOL_SYMTAB (symbol) (symbol)->symtab
Definition at line 729 of file symtab.h.
Referenced by add_class_symtab_symbol(), add_symbol(), address_info(), compare_symbols(), convert_linespec_to_sals(), cp_lookup_symbol_imports_or_template(), default_read_var_value(), end_symtab_from_static_block(), finalize_symtab(), find_frame_sal(), find_function_in_inferior(), find_method(), fixup_go_packaging(), fixup_symbol_section(), frapy_block(), new_symbol_full(), operator_check_standard(), scope_info(), search_symbols(), set_missing_symtab(), set_symbol(), skip_prologue_sal(), symbol_to_sal(), sympy_dealloc(), sympy_get_symtab(), and user_select_syms().
#define SYMBOL_TYPE (symbol) (symbol)->type
Definition at line 727 of file symtab.h.
Referenced by ada_args_match(), ada_find_any_type(), ada_parse_renaming(), ada_resolve_function(), ada_tasks_inferior_data_sniffer(), add_class_symbol(), add_template_parameters(), address_of_variable(), basic_lookup_transparent_type(), basic_lookup_transparent_type_quick(), bpfinishpy_init(), c_print_typedef(), c_type_print_template_args(), c_val_print(), call_site_find_chain_1(), check_typedef(), classify_inner_name(), cleanup_undefined_types_1(), coff_read_enum_type(), collect_one_symbol(), collect_symbol(), common_block_end(), completion_list_add_fields(), const_var_ref(), cp_lookup_rtti_type(), default_read_var_value(), define_symbol(), dw2_lookup_symbol(), dwarf2_const_value(), evaluate_subexp_for_sizeof(), evaluate_subexp_standard(), evaluate_subexp_with_coercion(), finalize_symtab(), find_function_return_type(), find_method(), find_oload_champ(), find_overload_match(), find_pc_partial_function_gnu_ifunc(), find_primitive_type(), finish_block_internal(), finish_command_continuation(), fix_common_block(), fixup_go_packaging(), func_addr_to_tail_call_list(), func_verify_no_selftailcall(), gen_var_ref(), get_java_object_type(), get_symbol_field_type(), gnuv3_get_typeid_type(), inspect_type(), is_nonfunction(), java_lookup_class(), language_bool_type(), lesseq_defined_than(), locexpr_read_variable(), locexpr_read_variable_at_entry(), loclist_read_variable(), loclist_read_variable_at_entry(), lookup_enum(), lookup_struct(), lookup_struct_typedef(), lookup_symbol_aux_psymtabs(), lookup_symbol_file(), lookup_template_type(), lookup_typename(), lookup_union(), m2_print_typedef(), new_symbol_full(), old_renaming_is_invisible(), operator_check_standard(), overload_list_add_symbol(), package_name_p(), parse_procedure(), parse_symbol(), pascal_val_print(), patch_block_stabs(), patch_opaque_types(), print_frame_args(), print_symbol(), print_symbol_info(), process_coff_symbol(), process_xcoff_symbol(), psymtab_to_symtab_1(), read_enum_type(), read_frame_arg(), read_type(), remove_extra_symbols(), replace_typedefs(), resolve_subexp(), return_command(), scope_info(), search_symbols(), select_possible_type_sym(), sparc32_struct_return_from_sym(), symbols_are_identical_enums(), sympy_get_type(), typy_template_argument(), user_select_syms(), value_nsstring(), write_var_or_type(), and yylex().
#define SYMBOL_VALUE (symbol) (symbol)->ginfo.value.ivalue
Definition at line 190 of file symtab.h.
Referenced by add_psymbol_to_bcache(), address_info(), coff_read_enum_type(), coff_reg_to_regnum(), coff_symtab_read(), collect_symbol(), const_var_ref(), default_read_var_value(), define_symbol(), dwarf2_const_value(), gen_sym_offset(), gen_var_ref(), hppa_hpux_find_import_stub_for_addr(), hppa_hpux_skip_trampoline_code(), hppa_lookup_stub_minimal_symbol(), lesseq_defined_than(), mdebug_reg_to_regnum(), parse_symbol(), print_frame_args(), print_symbol(), process_coff_symbol(), process_enumeration_scope(), read_enum_type(), scope_info(), som_solib_create_inferior_hook(), som_solib_desire_dynamic_linker_symbols(), stab_reg_to_regnum(), symbols_are_identical_enums(), and validate_actionline().
#define SYMBOL_VALUE_ADDRESS (symbol) (symbol)->ginfo.value.address
Definition at line 191 of file symtab.h.
Referenced by ada_main_name(), ada_tasks_inferior_data_sniffer(), add_class_symbol(), add_minsym(), add_pe_forwarded_sym(), add_psymbol_to_bcache(), address_info(), agent_look_up_symbols(), arm_skip_stub(), avr_scan_prologue(), bsd_uthread_lookup_address(), build_address_symbolic(), c_val_print(), call_site_to_target_addr(), collect_symbol(), compact_minimal_symbols(), compare_minimal_symbols(), const_var_ref(), convert_code_addr_to_desc_addr(), create_exception_master_breakpoint(), create_longjmp_master_breakpoint(), create_overlay_event_breakpoint(), create_std_terminate_master_breakpoint(), default_read_var_value(), define_symbol(), dump_msymbols(), elf_gnu_ifunc_record_cache(), elf_gnu_ifunc_resolve_by_got(), elf_locate_base(), enable_break(), enable_dec_thread(), end_psymtab(), find_frame_funname(), find_function_in_inferior(), find_objc_msgsend(), find_pc_partial_function_gnu_ifunc(), find_pc_sect_line(), find_pc_sect_psymbol(), find_pc_sect_psymtab(), find_pc_sect_psymtab_closer(), find_solib_trampoline_target(), find_stab_function_addr(), fix_common_block(), fixup_psymbol_section(), fixup_symbol_section(), flush_ea_cache(), frv_frame_this_id(), gen_var_ref(), get_pc_function_start(), get_running_thread_id(), get_signo(), glibc_skip_solib_resolver(), gnuv3_get_typeid(), gnuv3_skip_trampoline(), hppa64_hpux_search_dummy_call_sequence(), hppa_hpux_find_dummy_bpaddr(), hppa_symbol_address(), inferior_has_bug(), inside_main_func(), jit_breakpoint_re_set_internal(), jit_read_descriptor(), ld_so_xfer_auxv(), link_map_start(), lm_base(), locate_base(), lookup_minimal_symbol_by_pc_name(), lookup_minimal_symbol_by_pc_section_1(), m32c_m16c_address_to_pointer(), m32c_m16c_pointer_to_address(), m32c_return_value(), m32r_frame_this_id(), m68hc11_get_register_info(), macho_resolve_oso_sym_with_minsym(), main_got(), maintenance_translate_address(), minsym_found(), mips_linux_skip_resolver(), mips_skip_pic_trampoline_code(), new_symbol_full(), objfile_relocate1(), obsd_skip_solib_resolver(), ocl_enable_break(), parse_symbol(), pascal_val_print(), pd_enable(), pdc_symbol_addrs(), ppc_linux_spe_context_lookup(), prim_record_minimal_symbol_full(), print_msymbol_info(), print_partial_symbols(), print_symbol(), process_coff_symbol(), process_xcoff_symbol(), ps_pglobal_lookup(), relocate_one_symbol(), relocate_psymtabs(), remote_check_symbols(), remove_extra_symbols(), scan_file_globals(), scope_info(), search_symbols(), sh64_elf_make_msymbol_special(), simple_overlay_update(), simple_read_overlay_table(), skip_prologue_function(), skip_prologue_sal(), sol2_skip_solib_resolver(), som_solib_create_inferior_hook(), spu_catch_start(), spu_enable_break(), spu_get_overlay_table(), sym_info(), symbol_to_sal(), tui_find_disassembly_address(), tui_get_begin_asm_address(), until_next_command(), value_fn_field(), value_static_field(), var_decode_location(), and write_exp_msymbol().
#define SYMBOL_VALUE_BYTES (symbol) (symbol)->ginfo.value.bytes
Definition at line 192 of file symtab.h.
Referenced by default_read_var_value(), define_symbol(), dwarf2_const_value(), find_proc_desc(), parse_procedure(), parse_symbol(), print_symbol(), psymtab_to_symtab_1(), and scope_info().
#define SYMBOL_VALUE_CHAIN (symbol) (symbol)->ginfo.value.chain
Definition at line 195 of file symtab.h.
Referenced by common_block_end(), define_symbol(), parse_symbol(), patch_opaque_types(), process_coff_symbol(), and scan_file_globals().
#define SYMBOL_VALUE_COMMON_BLOCK (symbol) (symbol)->ginfo.value.common_block
Definition at line 193 of file symtab.h.
Referenced by info_common_command_for_block(), and read_common_block().
#define SYMTAB_PSPACE (symtab) (symtab)->objfile->pspace
Definition at line 942 of file symtab.h.
Referenced by add_matching_symbols_to_info(), compare_symbols(), convert_linespec_to_sals(), decode_digits_list_mode(), decode_digits_ordinary(), find_method(), select_source_symtab(), symbol_to_sal(), and VEC().
#define VTBL_FNADDR_OFFSET 2
Definition at line 960 of file symtab.h.
Referenced by c_val_print(), and pascal_val_print().
Typedef Documentation
typedef enum domain_enum_tag domain_enum
typedef int(symbol_found_callback_ftype)(struct symbol *sym, void *data)
Definition at line 1370 of file symtab.h.
typedef struct symtab* symtab_ptr
Definition at line 944 of file symtab.h.
Enumeration Type Documentation
enum address_class
Enumerator:
LOC_UNDEF
LOC_CONST
LOC_STATIC
LOC_REGISTER
LOC_ARG
LOC_REF_ARG
LOC_REGPARM_ADDR
LOC_LOCAL
LOC_TYPEDEF
LOC_LABEL
LOC_BLOCK
LOC_CONST_BYTES
LOC_UNRESOLVED
LOC_OPTIMIZED_OUT
LOC_COMPUTED
LOC_COMMON_BLOCK
LOC_FINAL_VALUE
Definition at line 455 of file symtab.h.
enum domain_enum_tag
Enumerator:
UNDEF_DOMAIN
VAR_DOMAIN
STRUCT_DOMAIN
LABEL_DOMAIN
COMMON_BLOCK_DOMAIN
Definition at line 402 of file symtab.h.
enum minimal_symbol_type
Enumerator:
mst_unknown
mst_text
mst_text_gnu_ifunc
mst_slot_got_plt
mst_data
mst_bss
mst_abs
mst_solib_trampoline
mst_file_text
mst_file_data
mst_file_bss
Definition at line 296 of file symtab.h.
enum print_source_lines_flags
Enumerator:
PRINT_SOURCE_LINES_NOERROR
PRINT_SOURCE_LINES_FILENAME
Definition at line 1218 of file symtab.h.
enum search_domain
Enumerator:
VARIABLES_DOMAIN
FUNCTIONS_DOMAIN
TYPES_DOMAIN
ALL_DOMAIN
Definition at line 435 of file symtab.h.
Function Documentation
struct symbol* allocate_symbol (struct objfile *) [read]
Definition at line 5188 of file symtab.c.
References objfile::objfile_obstack, OBSTACK_ZALLOC, and SYMBOL_SECTION.
Referenced by add_class_symbol(), coff_read_enum_type(), common_block_end(), define_symbol(), finalize_symtab(), fixup_go_packaging(), new_symbol(), new_symbol_full(), parse_symbol(), patch_block_stabs(), process_coff_symbol(), and read_enum_type().
struct template_symbol* allocate_template_symbol (struct objfile *) [read]
Definition at line 5202 of file symtab.c.
References template_symbol::base, objfile::objfile_obstack, OBSTACK_ZALLOC, and SYMBOL_SECTION.
Referenced by read_func_scope().
struct symbol* basic_lookup_symbol_nonlocal (const char * , const struct block * , const domain_enum) [read]
Definition at line 1724 of file symtab.c.
References lookup_symbol_global(), and lookup_symbol_static().
struct type* basic_lookup_transparent_type (const char *) [read]
Definition at line 1918 of file symtab.c.
References ALL_OBJFILE_PRIMARY_SYMTABS, ALL_OBJFILES, basic_lookup_transparent_type_quick(), BLOCKVECTOR, BLOCKVECTOR_BLOCK, GLOBAL_BLOCK, lookup_block_symbol(), STATIC_BLOCK, STRUCT_DOMAIN, SYMBOL_TYPE, and TYPE_IS_OPAQUE.
Referenced by cp_lookup_transparent_type(), and cp_lookup_transparent_type_loop().
void clear_pc_function_cache (void)
Definition at line 168 of file blockframe.c.
References cache_pc_function_high, cache_pc_function_is_gnu_ifunc, cache_pc_function_low, and cache_pc_function_name.
Referenced by clear_symtab_users(), and free_objfile().
void clear_solib (void)
Definition at line 1139 of file solib.c.
References target_so_ops::clear_solib, disable_breakpoints_in_shlibs(), exec_bfd, free_so(), so_list::next, observer_notify_solib_unloaded(), remove_target_sections(), so_list_head, solib_ops(), and target_gdbarch().
Referenced by core_close(), and no_shared_libraries().
void clear_symtab_users (int add_flags)
Definition at line 2842 of file symfile.c.
References breakpoint_re_set(), clear_current_source_symtab_and_line(), clear_displays(), clear_last_displayed_sal(), clear_pc_function_cache(), expression_context_block, innermost_block, observer_notify_new_objfile(), SYMFILE_DEFER_BP_RESET, and varobj_invalidate().
Referenced by clear_symtab_users_cleanup(), free_all_objfiles(), m32r_load(), m32r_upload_command(), new_symfile_objfile(), reread_symbols(), and som_solib_create_inferior_hook().
int compare_filenames_for_search (const char * filename, const char * search_name)
Definition at line 183 of file symtab.c.
References len.
Referenced by dw2_map_symtabs_matching_filename(), file_matches(), function_name_is_marked_for_skip(), iterate_over_some_symtabs(), and partial_map_symtabs_matching_filename().
enum language deduce_language_from_filename (const char *)
Definition at line 2767 of file symfile.c.
References fl_table_next, filename_language::lang, language_unknown, and strrchr().
Referenced by allocate_symtab(), parse_partial_symbols(), patch_subfile_names(), read_dbx_symtab(), scan_xcoff_symtab(), start_psymtab(), start_subfile(), and xcoff_start_psymtab().
DEF_VEC_I (CORE_ADDR)
DEF_VEC_P (symtab_ptr)
struct cleanup* demangle_for_lookup (const char * name, enum language lang, const char ** result_name) [read]
Definition at line 1182 of file symtab.c.
References cp_canonicalize_string(), d_demangle(), gdb_demangle(), go_demangle(), language_cplus, language_d, language_go, language_java, make_cleanup(), name, null_cleanup(), and xfree().
Referenced by find_linespec_symbols(), lookup_symbol_in_language(), and lookup_symbol_in_objfile_from_linkage_name().
const char* domain_name (domain_enum)
Definition at line 149 of file symtab.c.
References COMMON_BLOCK_DOMAIN, gdb_assert_not_reached, LABEL_DOMAIN, STRUCT_DOMAIN, UNDEF_DOMAIN, and VAR_DOMAIN.
Referenced by debug_qf_lookup_symbol(), and debug_qf_map_matching_symbols().
struct symtab_and_line find_function_start_sal (struct symbol * sym, int) [read]
Definition at line 2778 of file symtab.c.
References BLOCK_START, current_program_space, find_pc_sect_line(), fixup_symbol_section(), init_sal(), symtab_and_line::pc, symtab_and_line::pspace, symtab_and_line::section, skip_prologue_sal(), SYMBOL_BLOCK_VALUE, SYMBOL_OBJ_SECTION, and SYMBOL_OBJFILE.
Referenced by ada_exception_sal(), spu_catch_start(), symbol_to_sal(), and user_select_syms().
int find_line_pc (struct symtab * , int , CORE_ADDR *)
Definition at line 2611 of file symtab.c.
References find_line_symtab(), linetable::item, LINETABLE, and linetable_entry::pc.
Referenced by extract_display_start_addr(), find_line_pc_range(), make_visible_with_new_height(), mi_cmd_disassemble(), resolve_sal_pc(), tui_update_source_windows_with_line(), and update_static_tracepoint().
int find_line_pc_range (struct symtab_and_line , CORE_ADDR * , CORE_ADDR *)
Definition at line 2638 of file symtab.c.
References symtab_and_line::end, find_line_pc(), find_pc_sect_line(), symtab_and_line::line, symtab_and_line::pc, symtab_and_line::section, and symtab_and_line::symtab.
Referenced by find_breakpoint_range_end(), line_info(), mi_cmd_trace_find(), and trace_find_line_command().
struct symtab* find_line_symtab (struct symtab * , int , int * , int *) [read]
Definition at line 2479 of file symtab.c.
References ALL_OBJFILES, ALL_SYMTABS, quick_symbol_functions::expand_symtabs_with_fullname, symtab::filename, find_line_common(), linetable::item, linetable_entry::line, LINETABLE, sym_fns::qf, objfile::sf, and symtab_to_fullname().
Referenced by decode_digits_list_mode(), and find_line_pc().
struct symbol* find_pc_function (CORE_ADDR) [read]
Definition at line 151 of file blockframe.c.
References find_pc_mapped_section(), and find_pc_sect_function().
Referenced by bpfinishpy_init(), edit_command(), evaluate_subexp_standard(), find_function_return_type(), finish_command(), frapy_function(), frv_fdpic_find_canonical_descriptor(), func_addr_to_tail_call_list(), get_function_name(), handle_inferior_event(), jump_command(), list_command(), normal_stop(), pc_function_name(), proceed(), set_traceframe_context(), sparc32_dwarf2_struct_return_p(), sparc32_frame_cache(), until_next_command(), and VEC().
struct symtab_and_line find_pc_line (CORE_ADDR , int) [read]
Definition at line 2458 of file symtab.c.
References find_pc_overlay(), find_pc_sect_line(), overlay_mapped_address(), symtab_and_line::pc, pc_in_unmapped_range(), and symtab_and_line::section.
Referenced by aarch64_scan_prologue(), after_prologue(), alpha_after_prologue(), arm_linux_copy_svc(), c_parse(), call0_analyze_prologue(), convert_linespec_to_sals(), cris_skip_prologue(), decode_static_tracepoint_spec(), default_macro_scope(), do_mixed_source_and_assembly(), elf_gnu_ifunc_resolver_return_stop(), find_frame_sal(), find_last_line_symbol(), find_pc_line_pc_range(), find_pc_sect_line(), finish_backward(), finish_forward(), frv_skip_prologue(), gdb_disassemble_driver(), gdb_get_breakpoint_info(), gdb_get_tracepoint_info(), gdb_loc(), h8300_skip_prologue(), handle_inferior_event(), handle_step_into_function(), handle_step_into_function_backward(), in_prologue(), info_checkpoints_command(), iq2000_skip_prologue(), m32r_skip_prologue(), m68hc11_skip_prologue(), m88k_skip_prologue(), microblaze_skip_prologue(), moxie_skip_prologue(), mt_skip_prologue(), parse_breakpoint_sals(), print_one_static_tracepoint_marker(), refine_prologue_limit(), save_bookmark_command(), set_momentary_breakpoint_at_pc(), set_traceframe_context(), skip_prologue(), skip_prologue_using_sal(), sparc32_skip_prologue(), sparc64_skip_prologue(), trace_find_line_command(), tui_display_main(), tui_show_disassem_and_update_source(), tui_update_source_windows_with_addr(), until_break_command(), until_next_command(), update_static_tracepoint(), v850_skip_prologue(), VEC(), xstormy16_skip_prologue(), and xtensa_skip_prologue().
int find_pc_line_pc_range (CORE_ADDR , CORE_ADDR * , CORE_ADDR *)
Definition at line 2722 of file symtab.c.
References find_pc_line().
Referenced by step_once().
int find_pc_partial_function (CORE_ADDR , const char ** , CORE_ADDR * , CORE_ADDR *)
Definition at line 348 of file blockframe.c.
References find_pc_partial_function_gnu_ifunc().
Referenced by aarch64_scan_prologue(), aarch64_skip_prologue(), after_prologue(), alpha_after_prologue(), alpha_sigtramp_frame_sniffer(), amd64_linux_sigtramp_p(), amd64_skip_prologue(), amd64_sol2_sigtramp_p(), amd64_windows_skip_prologue(), amd64nbsd_sigtramp_p(), amd64obsd_sigtramp_p(), amd64obsd_trapframe_cache(), amd64obsd_trapframe_sniffer(), arm_adjust_breakpoint_address(), arm_exidx_unwind_sniffer(), arm_in_function_epilogue_p(), arm_scan_prologue(), arm_skip_prologue(), arm_skip_stub(), avr_skip_prologue(), call0_analyze_prologue(), call0_frame_cache(), cris_skip_prologue(), disassemble_command(), disassemble_current_function(), elf_gnu_ifunc_resolve_addr(), fill_in_stop_func(), find_func_descr(), find_proc_desc(), finish_backward(), frv_linux_sigtramp_frame_sniffer(), frv_skip_prologue(), func_command(), gdb_load_disassembly(), h8300_skip_prologue(), handle_exception(), hppa32_hpux_search_dummy_call_sequence(), hppa64_hpux_search_dummy_call_sequence(), hppa_hpux_find_dummy_bpaddr(), i386_in_stack_tramp_p(), i386_linux_dwarf_signal_frame_p(), i386_linux_sigtramp_p(), i386_sigtramp_p(), i386_skip_prologue(), i386_sol2_sigtramp_p(), i386_svr4_sigtramp_p(), i386nto_sigtramp_p(), i386obsd_sigtramp_p(), i386obsd_trapframe_cache(), i386obsd_trapframe_sniffer(), in_prologue(), iq2000_frame_cache(), iq2000_skip_prologue(), lm32_skip_prologue(), m32c_skip_prologue(), m32c_skip_trampoline_code(), m32c_virtual_frame_pointer(), m32r_linux_sigtramp_frame_sniffer(), m32r_skip_prologue(), m68hc11_skip_prologue(), m88k_skip_prologue(), mep_skip_prologue(), mi_cmd_disassemble(), microblaze_analyze_prologue(), microblaze_skip_prologue(), micromips_in_function_epilogue_p(), mips16_in_function_epilogue_p(), mips32_in_function_epilogue_p(), mips_adjust_breakpoint_address(), mips_in_frame_stub(), mips_in_return_stub(), mips_insn16_frame_cache(), mips_insn32_frame_cache(), mips_micro_frame_cache(), mips_skip_mips16_trampoline_code(), mips_skip_prologue(), mips_stub_frame_cache(), mn10300_skip_prologue(), moxie_skip_prologue(), msp430_skip_prologue(), mt_skip_prologue(), nios2_in_function_epilogue_p(), nios2_skip_prologue(), nios2_stub_frame_cache(), ppcfbsd_sigtramp_frame_sniffer(), ppcobsd_sigtramp_frame_sniffer(), refine_prologue_limit(), rl78_skip_prologue(), rs6000_in_function_epilogue_p(), rs6000_skip_prologue(), rx_skip_prologue(), score_make_prologue_cache(), sh_in_function_epilogue_p(), sh_skip_prologue(), skip_function_command(), skip_prologue_using_lineinfo(), skip_prologue_using_sal(), sparc32_skip_prologue(), sparc32_sol2_sigtramp_frame_sniffer(), sparc32nbsd_sigcontext_frame_sniffer(), sparc32obsd_sigtramp_frame_sniffer(), sparc64_skip_prologue(), sparc64_sol2_sigtramp_frame_sniffer(), sparc64fbsd_sigtramp_frame_sniffer(), sparc64nbsd_sigtramp_frame_sniffer(), sparc64obsd_sigtramp_frame_sniffer(), sparc64obsd_trapframe_sniffer(), spu_in_function_epilogue_p(), step_once(), thumb_in_function_epilogue_p(), thumb_scan_prologue(), tic6x_skip_prologue(), tilegx_in_function_epilogue_p(), tilegx_skip_prologue(), tui_show_frame_info(), v850_skip_prologue(), vaxobsd_sigtramp_sniffer(), xstormy16_in_function_epilogue_p(), xstormy16_skip_prologue(), xtensa_scan_prologue(), and xtensa_skip_prologue().
int find_pc_partial_function_gnu_ifunc (CORE_ADDR pc, const char ** name, CORE_ADDR * address, CORE_ADDR * endaddr, int * is_gnu_ifunc_p)
Definition at line 192 of file blockframe.c.
References ALL_OBJFILES, BLOCK_END, BLOCK_START, cache_pc_function_high, cache_pc_function_is_gnu_ifunc, cache_pc_function_low, cache_pc_function_name, find_pc_overlay(), find_pc_sect_function(), quick_symbol_functions::find_pc_sect_symtab, find_pc_section(), lookup_minimal_symbol_by_pc_section(), bound_minimal_symbol::minsym, mst_text_gnu_ifunc, MSYMBOL_SIZE, MSYMBOL_TYPE, obj_section_endaddr, overlay_mapped_address(), overlay_unmapped_address(), pc_in_unmapped_range(), sym_fns::qf, objfile::sf, SYMBOL_BLOCK_VALUE, SYMBOL_LINKAGE_NAME, SYMBOL_SECTION, SYMBOL_TYPE, SYMBOL_VALUE_ADDRESS, and TYPE_GNU_IFUNC.
Referenced by find_pc_partial_function(), and set_breakpoint_location_function().
struct symbol* find_pc_sect_function (CORE_ADDR , struct obj_section *) [read]
Definition at line 137 of file blockframe.c.
References block_for_pc_sect(), and block_linkage_function().
Referenced by build_address_symbolic(), find_pc_function(), find_pc_partial_function_gnu_ifunc(), print_breakpoint_location(), print_one_static_tracepoint_marker(), skip_prologue_sal(), and update_static_tracepoint().
struct symtab_and_line find_pc_sect_line (CORE_ADDR , struct obj_section * , int) [read]
Definition at line 2214 of file symtab.c.
References ALL_OBJFILE_SYMTABS, BLOCK_END, BLOCKVECTOR, BLOCKVECTOR_BLOCK, current_program_space, symtab_and_line::end, find_pc_line(), find_pc_sect_symtab(), GLOBAL_BLOCK, init_sal(), linetable::item, len, linetable_entry::line, symtab_and_line::line, LINETABLE, lookup_minimal_symbol_by_pc(), lookup_minimal_symbol_text(), bound_minimal_symbol::minsym, mst_solib_trampoline, MSYMBOL_TYPE, linetable::nitems, symtab::objfile, linetable_entry::pc, symtab_and_line::pc, symtab_and_line::pspace, symtab_and_line::section, SYMBOL_LINKAGE_NAME, SYMBOL_VALUE_ADDRESS, and symtab_and_line::symtab.
Referenced by amd64_skip_xmm_prologue(), build_address_symbolic(), find_function_start_sal(), find_line_pc_range(), find_pc_line(), minsym_found(), and skip_prologue_sal().
struct symtab* find_pc_sect_symtab (CORE_ADDR , struct obj_section *) [read]
Definition at line 2076 of file symtab.c.
References ALL_BLOCK_SYMBOLS, ALL_OBJFILES, ALL_PRIMARY_SYMTABS, BLOCK_END, BLOCK_START, BLOCKVECTOR, BLOCKVECTOR_BLOCK, quick_symbol_functions::find_pc_sect_symtab, fixup_symbol_section(), objfile::flags, GLOBAL_BLOCK, lookup_minimal_symbol_by_pc_section(), matching_obj_sections(), bound_minimal_symbol::minsym, mst_abs, mst_bss, mst_data, mst_file_bss, mst_file_data, MSYMBOL_TYPE, OBJF_REORDERED, sym_fns::qf, objfile::sf, and SYMBOL_OBJ_SECTION.
Referenced by blockvector_for_pc_sect(), find_pc_sect_line(), find_pc_symtab(), gdbpy_block_for_pc(), and spu_catch_start().
struct symtab* find_pc_sect_symtab_via_partial (CORE_ADDR , struct obj_section *) [read]
Definition at line 1006 of file symtab.c.
References ALL_OBJFILES, quick_symbol_functions::find_pc_sect_symtab, lookup_minimal_symbol_by_pc_section(), bound_minimal_symbol::minsym, mst_abs, mst_bss, mst_data, mst_file_bss, mst_file_data, MSYMBOL_TYPE, sym_fns::qf, and objfile::sf.
Referenced by backtrace_command_1().
struct symtab* find_pc_symtab (CORE_ADDR) [read]
Definition at line 2190 of file symtab.c.
References find_pc_mapped_section(), and find_pc_sect_symtab().
Referenced by amd64_in_function_epilogue_p(), amd64_skip_prologue(), arm_skip_prologue(), call_site_for_pc(), dwarf2_frame_find_quirks(), gdb_disassemble_driver(), gdb_disassembly(), get_frame_language(), handle_step_into_function(), handle_step_into_function_backward(), i386_in_function_epilogue_p(), i386_skip_prologue(), make_visible_with_new_height(), search_symbols(), select_frame(), tui_horizontal_source_scroll(), tui_selected_frame_level_changed_hook(), tui_show_disassem(), and tui_vertical_source_scroll().
CORE_ADDR find_solib_trampoline_target (struct frame_info * , CORE_ADDR)
Definition at line 1327 of file minsyms.c.
References ALL_MSYMBOLS, current_target, func, gdbarch_convert_from_func_ptr_addr(), get_objfile_arch(), lookup_solib_trampoline_symbol_by_pc(), mst_data, mst_text, mst_text_gnu_ifunc, MSYMBOL_TYPE, SYMBOL_LINKAGE_NAME, and SYMBOL_VALUE_ADDRESS.
Referenced by aarch64_linux_init_abi(), alpha_gdbarch_init(), alpha_linux_init_abi(), amd64_linux_init_abi_common(), arm_linux_init_abi(), i386_linux_init_abi(), i386_svr4_init_abi(), ia64_linux_init_abi(), m32r_linux_init_abi(), m68k_linux_init_abi(), mips_skip_trampoline_code(), nios2_linux_init_abi(), obsd_skip_solib_resolver(), ppc64_skip_trampoline_code(), ppcfbsd_init_abi(), rs6000_skip_trampoline_code(), s390_gdbarch_init(), sh_linux_init_abi(), sparc32_linux_init_abi(), sparc32_sol2_init_abi(), sparc64_linux_init_abi(), sparc64_sol2_init_abi(), sparc64fbsd_init_abi(), sparc64nbsd_init_abi(), and tilegx_linux_init_abi().
void fixup_section (struct general_symbol_info * ginfo, CORE_ADDR addr, struct objfile * objfile)
Definition at line 1041 of file symtab.c.
References ALL_OBJFILE_OSECTIONS, ANOFFSET, lookup_minimal_symbol_by_pc_name(), general_symbol_info::name, obj_section_addr, obj_section_endaddr, offset, general_symbol_info::section, objfile::section_offsets, objfile::sections, and SYMBOL_SECTION.
Referenced by fixup_psymbol_section(), and fixup_symbol_section().
struct symbol* fixup_symbol_section (struct symbol * , struct objfile *) [read]
Definition at line 1122 of file symtab.c.
References BLOCK_START, fixup_section(), gdb_assert, symbol::ginfo, LOC_BLOCK, LOC_LABEL, LOC_STATIC, SYMBOL_BLOCK_VALUE, SYMBOL_CLASS, SYMBOL_OBJ_SECTION, SYMBOL_SYMTAB, and SYMBOL_VALUE_ADDRESS.
Referenced by ada_add_block_symbols(), ada_lookup_encoded_symbol(), aux_add_nonlocal_symbols(), find_function_start_sal(), find_pc_sect_symtab(), jump_command(), lookup_global_symbol_from_objfile(), lookup_symbol_aux_block(), lookup_symbol_aux_objfile(), lookup_symbol_aux_quick(), relocate_one_symbol(), resolve_sal_pc(), skip_prologue_sal(), spu_catch_start(), and var_decode_location().
void forget_cached_source_info (void)
Definition at line 387 of file source.c.
References ALL_PSPACE_OBJFILES, ALL_PSPACES, and forget_cached_source_info_for_objfile().
Referenced by cd_command(), directory_command(), init_source_path(), mi_cmd_env_dir(), set_substitute_path_command(), and unset_substitute_path_command().
void forget_cached_source_info_for_objfile (struct objfile *)
Definition at line 360 of file source.c.
References ALL_OBJFILE_SYMTABS, quick_symbol_functions::forget_cached_source_info, symtab::fullname, symtab::line_charpos, sym_fns::qf, objfile::sf, and xfree().
Referenced by forget_cached_source_info(), and free_objfile().
void free_search_symbols (struct symbol_search *)
Definition at line 3304 of file symtab.c.
References symbol_search::next, p, and xfree().
Referenced by do_free_search_symbols_cleanup().
int identify_source_line (struct symtab * , int , int , CORE_ADDR)
Definition at line 1285 of file source.c.
References annotate_source(), current_source_line, first_line_listed, symtab::fullname, get_filename_and_charpos(), get_objfile_arch(), last_line_listed, line, symtab::line_charpos, symtab::nlines, and symtab::objfile.
Referenced by line_info(), and print_frame_info().
int in_gnu_ifunc_stub (CORE_ADDR pc)
Definition at line 752 of file minsyms.c.
References lookup_minimal_symbol_by_pc(), bound_minimal_symbol::minsym, mst_text_gnu_ifunc, and MSYMBOL_TYPE.
Referenced by svr4_in_dynsym_resolve_code().
int in_prologue (struct gdbarch * gdbarch, CORE_ADDR pc, CORE_ADDR func_start)
Definition at line 4775 of file symtab.c.
References symtab_and_line::end, find_pc_line(), find_pc_partial_function(), gdbarch_skip_prologue(), and symtab_and_line::line.
Referenced by handle_inferior_event().
void init_sal (struct symtab_and_line * sal)
Definition at line 926 of file symtab.c.
References symtab_and_line::end, symtab_and_line::explicit_line, symtab_and_line::explicit_pc, symtab_and_line::line, symtab_and_line::pc, symtab_and_line::probe, symtab_and_line::pspace, symtab_and_line::section, and symtab_and_line::symtab.
Referenced by call_function_by_hand(), clear_command(), create_breakpoint(), create_internal_breakpoint(), create_sals_line_offset(), decode_digits_ordinary(), decode_static_tracepoint_spec(), elf_gnu_ifunc_resolver_stop(), find_frame_sal(), find_function_start_sal(), find_pc_sect_line(), finish_backward(), finish_command(), handle_inferior_event(), handle_step_into_function(), init_catchpoint(), insert_hp_step_resume_breakpoint_at_frame(), insert_step_resume_breakpoint_at_caller(), line_info(), parse_breakpoint_sals(), parse_probes(), print_one_static_tracepoint_marker(), save_bookmark_command(), set_traceframe_context(), symbol_to_sal(), tui_update_source_window_as_is(), and update_static_tracepoint().
void initialize_symbol (struct symbol *)
Definition at line 5178 of file symtab.c.
References memset(), and SYMBOL_SECTION.
Referenced by process_xcoff_symbol().
int iterate_over_some_symtabs (const char * name, const char * real_path, int(*)(struct symtab *symtab, void *data) callback, void * data, struct symtab * first, struct symtab * after_last)
Definition at line 230 of file symtab.c.
References basenames_may_differ, compare_filenames_for_search(), symtab::filename, symtab::fullname, gdb_assert, symtab::next, and symtab_to_fullname().
Referenced by dw2_map_expand_apply(), iterate_over_symtabs(), and partial_map_expand_apply().
void iterate_over_symbols (const struct block * block, const char * name, const domain_enum domain, symbol_found_callback_ftype * callback, void * data)
Definition at line 2051 of file symtab.c.
References block_iter_name_first(), block_iter_name_next(), SYMBOL_DOMAIN, SYMBOL_LANGUAGE, and symbol_matches_domain().
void iterate_over_symtabs (const char * name, int(*)(struct symtab *symtab, void *data) callback, void * data)
Definition at line 291 of file symtab.c.
References ALL_OBJFILES, do_cleanups(), gdb_assert, gdb_realpath(), iterate_over_some_symtabs(), make_cleanup(), quick_symbol_functions::map_symtabs_matching_filename, null_cleanup(), sym_fns::qf, objfile::sf, objfile::symtabs, and xfree().
Referenced by lookup_symtab(), and VEC().
struct symbol* lookup_block_symbol (const struct block * , const char * , const domain_enum) [read]
Definition at line 1996 of file symtab.c.
References BLOCK_FUNCTION, block_iter_name_first(), block_iter_name_next(), SYMBOL_DOMAIN, SYMBOL_IS_ARGUMENT, SYMBOL_LANGUAGE, and symbol_matches_domain().
Referenced by basic_lookup_transparent_type(), basic_lookup_transparent_type_quick(), dw2_lookup_symbol(), lookup_global_symbol_from_objfile(), lookup_language_this(), lookup_symbol_aux_block(), lookup_symbol_aux_objfile(), lookup_symbol_aux_psymtabs(), lookup_symbol_aux_quick(), maintenance_check_psymtabs(), and spu_catch_start().
struct type* lookup_enum (const char * , const struct block *) [read]
Definition at line 1296 of file gdbtypes.c.
References _, error(), lookup_symbol(), STRUCT_DOMAIN, SYMBOL_TYPE, TYPE_CODE, and TYPE_CODE_ENUM.
Referenced by typy_lookup_typename().
struct symbol* lookup_global_symbol_from_objfile (const struct objfile * , const char * name, const domain_enum domain) [read]
Definition at line 1552 of file symtab.c.
References ALL_OBJFILE_PRIMARY_SYMTABS, BLOCKVECTOR, BLOCKVECTOR_BLOCK, fixup_symbol_section(), GLOBAL_BLOCK, lookup_block_symbol(), lookup_symbol_aux_quick(), symtab::objfile, and objfile_separate_debug_iterate().
Referenced by elf_lookup_lib_symbol(), and spu_lookup_lib_symbol().
struct symbol* lookup_language_this (const struct language_defn * lang, const struct block * block) [read]
Definition at line 1298 of file symtab.c.
References BLOCK_FUNCTION, BLOCK_SUPERBLOCK, language_defn::la_name_of_this, lookup_block_symbol(), and VAR_DOMAIN.
Referenced by gen_expr(), lookup_symbol_aux(), lookup_symbol_file(), and value_of_this().
struct objfile* lookup_objfile_from_block (const struct block * block) [read]
Definition at line 1507 of file symtab.c.
References ALL_SYMTABS, block_global_block(), BLOCKVECTOR, BLOCKVECTOR_BLOCK, GLOBAL_BLOCK, and objfile::separate_debug_objfile_backlink.
Referenced by clear_dangling_display_expressions(), lookup_symbol_global(), and operator_check_standard().
struct symbol* lookup_static_symbol_aux (const char * name, const domain_enum domain) [read]
Definition at line 1444 of file symtab.c.
References ALL_OBJFILES, lookup_symbol_aux_quick(), lookup_symbol_aux_symtabs(), and STATIC_BLOCK.
Referenced by cp_lookup_nested_symbol(), find_symbol_in_baseclass(), and lookup_symbol_aux().
struct type* lookup_struct (const char * , const struct block *) [read]
Definition at line 1250 of file gdbtypes.c.
References _, error(), lookup_symbol(), STRUCT_DOMAIN, SYMBOL_TYPE, TYPE_CODE, and TYPE_CODE_STRUCT.
Referenced by typy_lookup_typename().
struct symbol* lookup_symbol (const char * , const struct block * , const domain_enum , struct field_of_this_result *) [read]
Definition at line 1285 of file symtab.c.
References current_language, language_defn::la_language, and lookup_symbol_in_language().
Referenced by address_info(), c_val_print(), check_typedef(), classify_name(), classify_packaged_name(), cp_lookup_rtti_type(), find_function_in_inferior(), find_imps(), find_proc_desc(), frapy_read_var(), gdbpy_lookup_symbol(), gen_static_field(), get_java_object_type(), gnuv3_get_typeid_type(), insert_exception_resume_breakpoint(), inspect_type(), iterate_over_block_arg_vars(), java_lookup_class(), language_bool_type(), lex_one_token(), list_args_or_locals(), lookup_enum(), lookup_struct(), lookup_struct_typedef(), lookup_template_type(), lookup_typename(), lookup_union(), moxie_skip_prologue(), mt_skip_prologue(), package_name_p(), parse_procedure(), pascal_val_print(), print_frame_args(), push_variable(), replace_typedefs(), select_source_symtab(), set_initial_language(), skip_function_command(), value_fn_field(), value_static_field(), write_dollar_variable(), xstormy16_skip_prologue(), and yylex().
struct symbol* lookup_symbol_aux_block (const char * name, const struct block * block, const domain_enum domain) [read]
Definition at line 1533 of file symtab.c.
References fixup_symbol_section(), and lookup_block_symbol().
Referenced by lookup_symbol_aux_local(), lookup_symbol_file(), and lookup_symbol_static().
struct symbol* lookup_symbol_global (const char * name, const struct block * block, const domain_enum domain) [read]
Definition at line 1825 of file symtab.c.
References global_sym_lookup_data::domain, gdbarch_iterate_over_objfiles_in_search_order(), get_objfile_arch(), lookup_objfile_from_block(), lookup_symbol_global_iterator_cb(), memset(), name, global_sym_lookup_data::name, global_sym_lookup_data::result, solib_global_lookup(), and target_gdbarch().
Referenced by basic_lookup_symbol_nonlocal(), gdbpy_lookup_global_symbol(), and lookup_symbol_file().
struct symbol* lookup_symbol_in_language (const char * , const struct block * , const domain_enum , enum language, struct field_of_this_result *) [read]
Definition at line 1266 of file symtab.c.
References demangle_for_lookup(), do_cleanups(), and lookup_symbol_aux().
Referenced by ada_tasks_inferior_data_sniffer(), get_tcb_types_info(), lookup_symbol(), and standard_lookup().
struct symbol* lookup_symbol_static (const char * name, const struct block * block, const domain_enum domain) [read]
Definition at line 1769 of file symtab.c.
References block_static_block(), and lookup_symbol_aux_block().
Referenced by basic_lookup_symbol_nonlocal(), find_symbol_in_baseclass(), and lookup_symbol_file().
struct symtab* lookup_symtab (const char *) [read]
Definition at line 354 of file symtab.c.
References iterate_over_symtabs(), and lookup_symtab_callback().
Referenced by block_lookup(), gdb_find_bp_at_line(), gdb_find_file_command(), gdb_listfuncs(), gdb_loadfile(), mi_cmd_disassemble(), mi_cmd_symbol_list_lines(), skip_file_command(), and yylex().
struct type* lookup_transparent_type (const char *) [read]
Definition at line 1876 of file symtab.c.
References current_language, and language_defn::la_lookup_transparent_type.
Referenced by check_typedef().
struct type* lookup_union (const char * , const struct block *) [read]
Definition at line 1272 of file gdbtypes.c.
References _, error(), lookup_symbol(), STRUCT_DOMAIN, SYMBOL_TYPE, TYPE_CODE, and TYPE_CODE_UNION.
Referenced by typy_lookup_typename().
char* main_name (void)
Definition at line 5025 of file symtab.c.
References find_main_name(), and name_of_main.
Referenced by inside_main_func(), run_command_1(), select_source_symtab(), set_initial_language(), and skip_prologue().
struct cleanup* make_cleanup_free_search_symbols (struct symbol_search **) [read]
Definition at line 3325 of file symtab.c.
References do_free_search_symbols_cleanup(), and make_cleanup().
Referenced by gdb_search(), rbreak_command(), search_symbols(), and symtab_symbol_info().
const char enum type_code const char const char enum type_code const char const char const char const char const char* int matching_obj_sections (struct obj_section * , struct obj_section *)
Definition at line 945 of file symtab.c.
References ALL_OBJFILES, gdb_assert, objfile::obfd, objfile::separate_debug_objfile, objfile::separate_debug_objfile_backlink, and obj_section::the_bfd_section.
Referenced by find_pc_sect_psymbol(), find_pc_sect_symtab(), and lookup_minimal_symbol_by_pc_section_1().
const char* multiple_symbols_select_mode (void)
Definition at line 135 of file symtab.c.
References multiple_symbols_mode.
Referenced by decode_line_full(), and user_select_syms().
void print_source_lines (struct symtab * , int , int , enum print_source_lines_flags)
Definition at line 1470 of file source.c.
References print_source_lines_base().
Referenced by do_mixed_source_and_assembly(), forward_search_command(), list_command(), print_frame_info(), reverse_search_command(), and tui_vertical_source_scroll().
int producer_is_realview (const char * producer)
Definition at line 5046 of file symtab.c.
Referenced by dwarf2_frame_find_quirks(), prototyped_function_p(), and read_structure_type().
int register_symbol_block_impl (enum address_class aclass, const struct symbol_block_ops * ops)
Definition at line 5125 of file symtab.c.
References symbol_impl::aclass, symbol_block_ops::find_frame_base_location, gdb_assert, LOC_BLOCK, MAX_SYMBOL_IMPLS, and symbol_impl::ops_block.
int register_symbol_computed_impl (enum address_class, const struct symbol_computed_ops *)
Definition at line 5099 of file symtab.c.
References symbol_impl::aclass, symbol_computed_ops::describe_location, gdb_assert, LOC_COMPUTED, MAX_SYMBOL_IMPLS, symbol_impl::ops_computed, symbol_computed_ops::read_needs_frame, symbol_computed_ops::read_variable, and symbol_computed_ops::tracepoint_var_ref.
int register_symbol_register_impl (enum address_class, const struct symbol_register_ops *)
Definition at line 5148 of file symtab.c.
References symbol_impl::aclass, gdb_assert, LOC_REGISTER, LOC_REGPARM_ADDR, MAX_SYMBOL_IMPLS, and symbol_impl::ops_register.
void reread_symbols (void)
Definition at line 2352 of file symfile.c.
References _, all_cleanups(), build_objfile_section_table(), clear_complaints(), clear_symtab_users(), clear_symtab_users_cleanup(), discard_cleanups(), do_cleanups(), error(), exec_bfd, exec_file_attach(), find_sym_fns(), objfile::flags, free_objfile_separate_debug(), objfile::free_psymtabs, gdb_bfd_open_maybe_remote(), gdb_bfd_unref(), objfile::global_psymbols, init_entry_point_info(), psymbol_allocation_list::list, make_cleanup(), make_cleanup_bfd_unref(), make_cleanup_free_objfile(), memcpy(), memset(), objfile::minimal_symbol_count, objfile::msymbol_demangled_hash, objfile::msymbol_hash, objfile::msymbols, objfile::mtime, objfile::next, objfile::num_sections, objfile::obfd, object_files, OBJF_PSYMTABS_READ, objfile_has_symbols(), objfile_name(), objfile::objfile_obstack, objfile_set_sym_fns(), objfiles_changed(), observer_notify_executable_changed(), observer_notify_new_objfile(), section_offsets::offsets, objfile::original_name, preserve_values(), printf_unfiltered(), psymbol_bcache_free(), psymbol_bcache_init(), objfile::psymbol_cache, objfile::psymtabs, objfile::psymtabs_addrmap, read_symbols(), reinit_frame_cache(), objfile::section_offsets, objfile::sections, objfile::separate_debug_objfile_backlink, set_objfile_per_bfd(), objfile::sf, SIZEOF_N_SECTION_OFFSETS, objfile::static_psymbols, sym_fns::sym_finish, sym_fns::sym_init, sym_fns::sym_new_init, symfile_complaints, symfile_objfile, objfile::symtabs, objfile::template_symbols, terminate_minimal_symbol_table(), VEC, VEC_cleanup, VEC_iterate, VEC_safe_push, wrap_here(), and xfree().
Referenced by attach_command_post_wait(), load_command(), remote_open_1(), and run_command_1().
void resolve_sal_pc (struct symtab_and_line *)
Definition at line 9816 of file breakpoint.c.
References _, block_linkage_function(), blockvector_for_pc_sect(), do_cleanups(), error(), symtab_and_line::explicit_line, find_line_pc(), fixup_symbol_section(), symtab_and_line::line, lookup_minimal_symbol_by_pc(), bound_minimal_symbol::minsym, bound_minimal_symbol::objfile, symtab::objfile, symtab_and_line::pc, symtab_and_line::pspace, save_current_space_and_thread(), symtab_and_line::section, skip_prologue_sal(), switch_to_program_space_and_thread(), SYMBOL_OBJ_SECTION, symtab_and_line::symtab, and symtab_to_filename_for_display().
Referenced by addr_string_to_sals(), breakpoint_sals_to_pc(), gdb_get_function_command(), gdb_get_vars_command(), gdb_loc(), jump_command(), scope_info(), tracepoint_exists(), and until_break_command().
const char* search_domain_name (enum search_domain)
Definition at line 165 of file symtab.c.
References ALL_DOMAIN, FUNCTIONS_DOMAIN, gdb_assert_not_reached, TYPES_DOMAIN, and VARIABLES_DOMAIN.
Referenced by debug_qf_expand_symtabs_matching().
void search_symbols (char * , enum search_domain, int , char ** , struct symbol_search **)
void select_source_symtab (struct symtab *)
Definition at line 244 of file source.c.
References _, ALL_OBJFILES, current_program_space, current_source_line, DECODE_LINE_FUNFIRSTLINE, decode_line_with_current_source(), error(), symtab::filename, quick_symbol_functions::find_last_source_symtab, len, symtab_and_line::line, lines_to_list, lookup_symbol(), main_name(), max, name, symtab::next, symtab_and_line::pspace, sym_fns::qf, symtabs_and_lines::sals, objfile::sf, symtab_and_line::symtab, SYMTAB_PSPACE, objfile::symtabs, VAR_DOMAIN, and xfree().
Referenced by forward_search_command(), reverse_search_command(), set_default_source_symtab_and_line(), tui_print_frame_info_listing_hook(), and tui_selected_frame_level_changed_hook().
void set_main_name (const char * name)
Definition at line 4959 of file symtab.c.
References language_unknown, and xfree().
Referenced by find_main_name(), process_one_symbol(), read_partial_die(), and symtab_observer_executable_changed().
void skip_prologue_sal (struct symtab_and_line *)
Definition at line 2810 of file symtab.c.
References BLOCK_END, block_for_pc_sect(), BLOCK_FUNCTION, block_inlined_p(), BLOCK_START, BLOCK_SUPERBLOCK, do_cleanups(), symtab_and_line::end, symtab_and_line::explicit_line, symtab_and_line::explicit_pc, find_pc_sect_function(), find_pc_sect_line(), fixup_symbol_section(), gdbarch_deprecated_function_start_offset(), gdbarch_skip_main_prologue(), gdbarch_skip_main_prologue_p(), gdbarch_skip_prologue(), get_objfile_arch(), symtab_and_line::line, lookup_minimal_symbol_by_pc_section(), bound_minimal_symbol::minsym, name, bound_minimal_symbol::objfile, overlay_mapped_address(), overlay_unmapped_address(), symtab_and_line::pc, symtab_and_line::pspace, save_current_space_and_thread(), symtab_and_line::section, section_is_mapped(), section_is_overlay(), skip_prologue_using_lineinfo(), strcmp_iw(), switch_to_program_space_and_thread(), SYMBOL_BLOCK_VALUE, SYMBOL_LINE, SYMBOL_LINKAGE_NAME, SYMBOL_OBJ_SECTION, SYMBOL_OBJFILE, SYMBOL_SYMTAB, SYMBOL_VALUE_ADDRESS, and symtab_and_line::symtab.
Referenced by create_sals_line_offset(), find_function_start_sal(), minsym_found(), and resolve_sal_pc().
CORE_ADDR skip_prologue_using_sal (struct gdbarch * gdbarch, CORE_ADDR func_addr)
Definition at line 4858 of file symtab.c.
References block_for_pc(), BLOCK_FUNCTION, block_inlined_p(), BLOCK_SUPERBLOCK, symtab_and_line::end, find_pc_line(), find_pc_partial_function(), gdbarch_deprecated_function_start_offset(), linetable::item, symtab::language, language_asm, linetable_entry::line, symtab_and_line::line, LINETABLE, linetable::nitems, linetable_entry::pc, symtab_and_line::pc, and symtab_and_line::symtab.
Referenced by aarch64_skip_prologue(), amd64_skip_prologue(), amd64_windows_skip_prologue(), arm_skip_prologue(), avr_skip_prologue(), frv_analyze_prologue(), i386_skip_prologue(), lm32_skip_prologue(), m32c_skip_prologue(), mips_skip_prologue(), moxie_skip_prologue(), mt_frame_unwind_cache(), nios2_skip_prologue(), rs6000_skip_prologue(), sh_skip_prologue(), tic6x_skip_prologue(), and tilegx_skip_prologue().
const char* symbol_demangled_name (const struct general_symbol_info * symbol)
Definition at line 886 of file symtab.c.
References ada_decode_symbol(), language_ada, language_cplus, language_d, language_fortran, language_go, language_java, language_objc, and symbol_get_demangled_name().
const char* symbol_get_demangled_name (const struct general_symbol_info *)
Definition at line 502 of file symtab.c.
References general_symbol_info::ada_mangled, general_symbol_info::cplus_specific, cplus_specific::demangled_name, language_ada, language_cplus, general_symbol_info::language_specific, and general_symbol_info::mangled_lang.
Referenced by new_symbol_full(), symbol_demangled_name(), and symbol_natural_name().
int symbol_matches_domain (enum language symbol_language, domain_enum symbol_domain, domain_enum domain)
Definition at line 1851 of file symtab.c.
References language_ada, language_cplus, language_d, language_java, STRUCT_DOMAIN, and VAR_DOMAIN.
Referenced by ada_add_block_symbols(), iterate_over_symbols(), lookup_block_symbol(), lookup_partial_symbol(), map_block(), and match_partial_symbol().
const char* symbol_natural_name (const struct general_symbol_info * symbol)
Definition at line 861 of file symtab.c.
References ada_decode_symbol(), language_ada, language_cplus, language_d, language_fortran, language_go, language_java, language_objc, general_symbol_info::name, and symbol_get_demangled_name().
Referenced by symbol_search_name().
CORE_ADDR symbol_overlayed_address (CORE_ADDR , struct obj_section *)
Definition at line 3101 of file symfile.c.
References overlay_debugging, overlay_unmapped_address(), section_is_mapped(), and section_is_overlay().
Referenced by default_read_var_value(), and write_exp_msymbol().
const char* symbol_search_name (const struct general_symbol_info *)
Definition at line 915 of file symtab.c.
References language_ada, general_symbol_info::name, and symbol_natural_name().
void symbol_set_demangled_name (struct general_symbol_info * , const char * , struct obstack *)
Definition at line 471 of file symtab.c.
References general_symbol_info::ada_mangled, general_symbol_info::cplus_specific, cplus_specific::demangled_name, language_ada, language_cplus, general_symbol_info::language_specific, general_symbol_info::mangled_lang, name, general_symbol_info::obstack, and symbol_init_cplus_specific().
Referenced by new_symbol_full(), symbol_set_language(), and symbol_set_names().
void symbol_set_language (struct general_symbol_info * symbol, enum language language, struct obstack * obstack)
Definition at line 526 of file symtab.c.
References general_symbol_info::ada_mangled, general_symbol_info::cplus_specific, gdb_assert, language_ada, language_cplus, language_d, language_fortran, language_go, language_java, language_objc, general_symbol_info::language_specific, memset(), general_symbol_info::obstack, and symbol_set_demangled_name().
void symbol_set_names (struct general_symbol_info * symbol, const char * linkage_name, int len, int copy_name, struct objfile * objfile)
Definition at line 713 of file symtab.c.
References create_demangled_names_hash(), demangled_name_entry::demangled, objfile_per_bfd_storage::demangled_names_hash, JAVA_PREFIX, JAVA_PREFIX_LEN, language_ada, language_go, language_java, len, demangled_name_entry::mangled, memcpy(), name, general_symbol_info::name, objfile::per_bfd, objfile_per_bfd_storage::storage_obstack, symbol_find_demangled_name(), symbol_set_demangled_name(), and xfree().
VEC (char_ptr) const
VEC (CORE_ADDR)
Variable Documentation
int basenames_may_differ
Definition at line 114 of file symtab.c.
Referenced by dw2_expand_symtabs_matching(), dw2_map_symtabs_matching_filename(), expand_symtabs_matching_via_partial(), function_name_is_marked_for_skip(), iterate_over_some_symtabs(), partial_map_symtabs_matching_filename(), read_psymtabs_with_fullname(), and search_symbols().
int struct linetable_entry** best_entry
Definition at line 1361 of file symtab.h.
Referenced by create_sals_line_offset().
const char const char* break_on
Definition at line 1236 of file symtab.h.
const char const char enum type_code code
Definition at line 1237 of file symtab.h.
int currently_reading_symtab
Referenced by check_typedef(), increment_reading_symtab(), and VEC().
int demangle
Definition at line 46 of file demangle.c.
Referenced by _initialize_demangler(), c_val_print(), f_val_print(), fprintf_symbol_filtered(), generic_val_print(), gnuv3_print_method_ptr(), java_val_print(), pascal_val_print(), print_breakpoint_location(), print_function_pointer_address(), and tui_get_function_from_frame().
struct gnu_ifunc_fns* gnu_ifunc_fns_p
Definition at line 810 of file minsyms.c.
enum language language_of_main
Definition at line 4956 of file symtab.c.
Referenced by read_partial_die(), and set_initial_language().
int line
Definition at line 1360 of file symtab.h.
Referenced by add_line_to_sigset(), arrange_linetable(), ATTRIBUTE_PRINTF(), decode_digits_ordinary(), do_mixed_source_and_assembly(), dump_insns(), dwarf_decode_lines_1(), dwarf_decode_macro_bytes(), dwarf_decode_macros(), execute_command(), find_definition(), forward_search_command(), gdb_disassemble_driver(), gdb_find_bp_at_line(), gdb_loadfile(), gdb_readline_wrapper_line(), gdbtk_load_source(), identify_source_line(), info_macro_command(), insert_args(), linux_find_memory_regions_full(), linux_info_proc(), linux_nat_thread_name(), lookup_cmd_1(), macro_for_each_in_scope(), macro_include(), macro_undef(), mi_cmd_symbol_list_lines(), new_macro_key(), parse_static_tracepoint_marker_definition(), parse_trace_status(), parse_tracepoint_definition(), parse_tsv_definition(), print_address_symbolic(), print_source_lines_base(), py_print_frame(), read_mapping(), record_line(), reverse_search_command(), set_last_displayed_sal(), show_commands(), tfile_interp_line(), tui_display_registers_from_line(), tui_line_from_reg_element_no(), tui_line_is_displayed(), tui_redisplay_readline(), tui_set_disassem_content(), tui_show_source_line(), tui_update_breakpoint_info(), and tui_update_source_windows_with_line().
const char multiple_symbols_all[]
Definition at line 121 of file symtab.c.
Referenced by decode_line_2(), decode_line_full(), decode_linespec_default(), and user_select_syms().
const char multiple_symbols_ask[]
Definition at line 120 of file symtab.c.
Referenced by decode_line_full().
const char multiple_symbols_cancel[]
Definition at line 122 of file symtab.c.
Referenced by decode_line_2(), decode_line_full(), and user_select_syms().
struct symbol_impl* symbol_impls
Definition at line 5087 of file symtab.c.
int symtab_create_debug
Definition at line 109 of file symtab.c.
Referenced by allocate_psymtab(), allocate_symtab(), elf_symfile_read(), and install_minimal_symbols().
const char* word
Definition at line 1236 of file symtab.h.
Referenced by add_filename_to_list(), alpha_heuristic_frame_unwind_cache(), arm_exidx_new_objfile(), completion_list_add_fields(), h8300_push_dummy_call(), inf_ptrace_xfer_partial(), mips_xfer_memory(), ppc64_sysv_abi_push_dummy_call(), ppc_sysv_abi_push_dummy_call(), rs6000_lynx178_push_dummy_call(), rs6000_push_dummy_call(), rs6000_xfer_partial(), symbol_completion_add(), value_bit_index(), and VEC().