GDB (xrefs): /home/stan/gdb/src/gdb/target-descriptions.h File Reference
/home/stan/gdb/src/gdb/target-descriptions.h File Reference
Functions
void target_find_description (void)
void target_clear_description (void)
struct target_desc * target_current_description (void)
void copy_inferior_target_desc_info (struct inferior *destinf, struct inferior *srcinf)
void target_desc_info_free (struct target_desc_info *tdesc_info)
int target_desc_info_from_user_p (struct target_desc_info *info)
void set_tdesc_pseudo_register_name (struct gdbarch *gdbarch, gdbarch_register_name_ftype *pseudo_name)
void set_tdesc_pseudo_register_type (struct gdbarch *gdbarch, gdbarch_register_type_ftype *pseudo_type)
void set_tdesc_pseudo_register_reggroup_p (struct gdbarch *gdbarch, gdbarch_register_reggroup_p_ftype *pseudo_reggroup_p)
void tdesc_use_registers (struct gdbarch *gdbarch, const struct target_desc *target_desc, struct tdesc_arch_data *early_data)
struct tdesc_arch_data * tdesc_data_alloc (void)
void tdesc_data_cleanup (void *data_untyped)
int tdesc_numbered_register (const struct tdesc_feature *feature, struct tdesc_arch_data *data, int regno, const char *name)
int tdesc_unnumbered_register (const struct tdesc_feature *feature, const char *name)
int tdesc_register_size (const struct tdesc_feature *feature, const char *name)
int tdesc_numbered_register_choices (const struct tdesc_feature *feature, struct tdesc_arch_data *data, int regno, const char *const names[])
struct bfd_arch_info * tdesc_architecture (const struct target_desc *)
enum gdb_osabi tdesc_osabi (const struct target_desc *)
int tdesc_compatible_p (const struct target_desc *, const struct bfd_arch_info *)
const char * tdesc_property (const struct target_desc *, const char *key)
int tdesc_has_registers (const struct target_desc *)
struct tdesc_feature * tdesc_find_feature (const struct target_desc *, const char *name)
const char * tdesc_feature_name (const struct tdesc_feature *feature)
struct tdesc_type * tdesc_named_type (const struct tdesc_feature *feature, const char *id)
const char * tdesc_register_name (struct gdbarch *gdbarch, int regno)
struct type * tdesc_register_type (struct gdbarch *gdbarch, int regno)
struct type * tdesc_find_type (struct gdbarch *gdbarch, const char *id)
int tdesc_register_in_reggroup_p (struct gdbarch *gdbarch, int regno, struct reggroup *reggroup)
struct target_desc * allocate_target_description (void)
struct cleanup * make_cleanup_free_target_description (struct target_desc *)
void set_tdesc_architecture (struct target_desc *, const struct bfd_arch_info *)
void set_tdesc_osabi (struct target_desc *, enum gdb_osabi osabi)
void set_tdesc_property (struct target_desc *, const char *key, const char *value)
void tdesc_add_compatible (struct target_desc *, const struct bfd_arch_info *)
struct tdesc_feature * tdesc_create_feature (struct target_desc *tdesc, const char *name)
struct tdesc_type * tdesc_create_vector (struct tdesc_feature *feature, const char *name, struct tdesc_type *field_type, int count)
struct tdesc_type * tdesc_create_struct (struct tdesc_feature *feature, const char *name)
void tdesc_set_struct_size (struct tdesc_type *type, LONGEST size)
struct tdesc_type * tdesc_create_union (struct tdesc_feature *feature, const char *name)
struct tdesc_type * tdesc_create_flags (struct tdesc_feature *feature, const char *name, LONGEST size)
void tdesc_add_field (struct tdesc_type *type, const char *field_name, struct tdesc_type *field_type)
void tdesc_add_bitfield (struct tdesc_type *type, const char *field_name, int start, int end)
void tdesc_add_flag (struct tdesc_type *type, int start, const char *flag_name)
void tdesc_create_reg (struct tdesc_feature *feature, const char *name, int regnum, int save_restore, const char *group, int bitsize, const char *type)
Function Documentation
struct target_desc* allocate_target_description (void) [read]
Definition at line 1448 of file target-descriptions.c.
References XZALLOC.
Referenced by _initialize_mips_tdep(), initialize_tdesc_aarch64(), initialize_tdesc_amd64(), initialize_tdesc_amd64_avx(), initialize_tdesc_amd64_avx_linux(), initialize_tdesc_amd64_linux(), initialize_tdesc_arm_with_iwmmxt(), initialize_tdesc_arm_with_m(), initialize_tdesc_arm_with_m_fpa_layout(), initialize_tdesc_arm_with_m_vfp_d16(), initialize_tdesc_arm_with_neon(), initialize_tdesc_arm_with_vfpv2(), initialize_tdesc_arm_with_vfpv3(), initialize_tdesc_i386(), initialize_tdesc_i386_avx(), initialize_tdesc_i386_avx_linux(), initialize_tdesc_i386_linux(), initialize_tdesc_i386_mmx(), initialize_tdesc_i386_mmx_linux(), initialize_tdesc_mips64_dsp_linux(), initialize_tdesc_mips64_linux(), initialize_tdesc_mips_dsp_linux(), initialize_tdesc_mips_linux(), initialize_tdesc_nios2(), initialize_tdesc_nios2_linux(), initialize_tdesc_powerpc_32(), initialize_tdesc_powerpc_32l(), initialize_tdesc_powerpc_403(), initialize_tdesc_powerpc_403gc(), initialize_tdesc_powerpc_405(), initialize_tdesc_powerpc_505(), initialize_tdesc_powerpc_601(), initialize_tdesc_powerpc_602(), initialize_tdesc_powerpc_603(), initialize_tdesc_powerpc_604(), initialize_tdesc_powerpc_64(), initialize_tdesc_powerpc_64l(), initialize_tdesc_powerpc_7400(), initialize_tdesc_powerpc_750(), initialize_tdesc_powerpc_860(), initialize_tdesc_powerpc_altivec32(), initialize_tdesc_powerpc_altivec32l(), initialize_tdesc_powerpc_altivec64(), initialize_tdesc_powerpc_altivec64l(), initialize_tdesc_powerpc_cell32l(), initialize_tdesc_powerpc_cell64l(), initialize_tdesc_powerpc_e500(), initialize_tdesc_powerpc_e500l(), initialize_tdesc_powerpc_isa205_32l(), initialize_tdesc_powerpc_isa205_64l(), initialize_tdesc_powerpc_isa205_altivec32l(), initialize_tdesc_powerpc_isa205_altivec64l(), initialize_tdesc_powerpc_isa205_vsx32l(), initialize_tdesc_powerpc_isa205_vsx64l(), initialize_tdesc_powerpc_vsx32(), initialize_tdesc_powerpc_vsx32l(), initialize_tdesc_powerpc_vsx64(), initialize_tdesc_powerpc_vsx64l(), initialize_tdesc_rs6000(), initialize_tdesc_s390_linux32(), initialize_tdesc_s390_linux32v1(), initialize_tdesc_s390_linux32v2(), initialize_tdesc_s390_linux64(), initialize_tdesc_s390_linux64v1(), initialize_tdesc_s390_linux64v2(), initialize_tdesc_s390_te_linux64(), initialize_tdesc_s390x_linux64(), initialize_tdesc_s390x_linux64v1(), initialize_tdesc_s390x_linux64v2(), initialize_tdesc_s390x_te_linux64(), initialize_tdesc_tic6x_c62x(), initialize_tdesc_tic6x_c62x_linux(), initialize_tdesc_tic6x_c64x(), initialize_tdesc_tic6x_c64x_linux(), initialize_tdesc_tic6x_c64xp(), initialize_tdesc_tic6x_c64xp_linux(), initialize_tdesc_x32(), initialize_tdesc_x32_avx(), initialize_tdesc_x32_avx_linux(), and initialize_tdesc_x32_linux().
void copy_inferior_target_desc_info (struct inferior * destinf, struct inferior * srcinf)
Definition at line 286 of file target-descriptions.c.
References target_desc_info::fetched, target_desc_info::filename, get_tdesc_info(), and target_desc_info::tdesc.
Referenced by clone_inferior_command(), and linux_child_follow_fork().
struct cleanup* make_cleanup_free_target_description (struct target_desc *) [read]
Definition at line 1482 of file target-descriptions.c.
References free_target_description(), and make_cleanup().
void set_tdesc_architecture (struct target_desc * , const struct bfd_arch_info *)
Definition at line 1532 of file target-descriptions.c.
References target_desc::arch.
Referenced by initialize_tdesc_aarch64(), initialize_tdesc_amd64(), initialize_tdesc_amd64_avx(), initialize_tdesc_amd64_avx_linux(), initialize_tdesc_amd64_linux(), initialize_tdesc_arm_with_iwmmxt(), initialize_tdesc_i386(), initialize_tdesc_i386_avx(), initialize_tdesc_i386_avx_linux(), initialize_tdesc_i386_linux(), initialize_tdesc_i386_mmx(), initialize_tdesc_i386_mmx_linux(), initialize_tdesc_mips64_dsp_linux(), initialize_tdesc_mips64_linux(), initialize_tdesc_mips_dsp_linux(), initialize_tdesc_mips_linux(), initialize_tdesc_nios2(), initialize_tdesc_nios2_linux(), initialize_tdesc_powerpc_32(), initialize_tdesc_powerpc_32l(), initialize_tdesc_powerpc_64(), initialize_tdesc_powerpc_64l(), initialize_tdesc_powerpc_altivec32(), initialize_tdesc_powerpc_altivec32l(), initialize_tdesc_powerpc_altivec64(), initialize_tdesc_powerpc_altivec64l(), initialize_tdesc_powerpc_cell32l(), initialize_tdesc_powerpc_cell64l(), initialize_tdesc_powerpc_e500(), initialize_tdesc_powerpc_e500l(), initialize_tdesc_powerpc_isa205_32l(), initialize_tdesc_powerpc_isa205_64l(), initialize_tdesc_powerpc_isa205_altivec32l(), initialize_tdesc_powerpc_isa205_altivec64l(), initialize_tdesc_powerpc_isa205_vsx32l(), initialize_tdesc_powerpc_isa205_vsx64l(), initialize_tdesc_powerpc_vsx32(), initialize_tdesc_powerpc_vsx32l(), initialize_tdesc_powerpc_vsx64(), initialize_tdesc_powerpc_vsx64l(), initialize_tdesc_rs6000(), initialize_tdesc_s390_linux32(), initialize_tdesc_s390_linux32v1(), initialize_tdesc_s390_linux32v2(), initialize_tdesc_s390_linux64(), initialize_tdesc_s390_linux64v1(), initialize_tdesc_s390_linux64v2(), initialize_tdesc_s390_te_linux64(), initialize_tdesc_s390x_linux64(), initialize_tdesc_s390x_linux64v1(), initialize_tdesc_s390x_linux64v2(), initialize_tdesc_s390x_te_linux64(), initialize_tdesc_tic6x_c62x(), initialize_tdesc_tic6x_c62x_linux(), initialize_tdesc_tic6x_c64x(), initialize_tdesc_tic6x_c64x_linux(), initialize_tdesc_tic6x_c64xp(), initialize_tdesc_tic6x_c64xp_linux(), initialize_tdesc_x32(), initialize_tdesc_x32_avx(), initialize_tdesc_x32_avx_linux(), and initialize_tdesc_x32_linux().
void set_tdesc_osabi (struct target_desc * , enum gdb_osabi osabi)
Definition at line 1539 of file target-descriptions.c.
References target_desc::osabi.
Referenced by initialize_tdesc_amd64_avx_linux(), initialize_tdesc_amd64_linux(), initialize_tdesc_i386_avx_linux(), initialize_tdesc_i386_linux(), initialize_tdesc_i386_mmx_linux(), initialize_tdesc_mips_dsp_linux(), initialize_tdesc_mips_linux(), initialize_tdesc_nios2_linux(), initialize_tdesc_tic6x_c62x_linux(), initialize_tdesc_tic6x_c64x_linux(), initialize_tdesc_tic6x_c64xp_linux(), initialize_tdesc_x32_avx_linux(), and initialize_tdesc_x32_linux().
void set_tdesc_property (struct target_desc * , const char * key, const char * value)
Definition at line 1512 of file target-descriptions.c.
References _, gdb_assert, internal_error(), property::key, property::value, VEC_iterate, and VEC_safe_push.
Referenced by _initialize_mips_tdep().
void set_tdesc_pseudo_register_name (struct gdbarch * gdbarch, gdbarch_register_name_ftype * pseudo_name)
Definition at line 1120 of file target-descriptions.c.
References gdbarch_data().
Referenced by aarch64_gdbarch_init(), amd64_init_abi(), arm_gdbarch_init(), i386_gdbarch_init(), and s390_gdbarch_init().
void set_tdesc_pseudo_register_reggroup_p (struct gdbarch * gdbarch, gdbarch_register_reggroup_p_ftype * pseudo_reggroup_p)
Definition at line 1139 of file target-descriptions.c.
References gdbarch_data().
Referenced by aarch64_gdbarch_init(), rs6000_gdbarch_init(), and s390_gdbarch_init().
void set_tdesc_pseudo_register_type (struct gdbarch * gdbarch, gdbarch_register_type_ftype * pseudo_type)
Definition at line 1129 of file target-descriptions.c.
References gdbarch_data().
Referenced by aarch64_gdbarch_init(), amd64_x32_init_abi(), i386_gdbarch_init(), mips_gdbarch_init(), rs6000_gdbarch_init(), and s390_gdbarch_init().
void target_clear_description (void)
Definition at line 387 of file target-descriptions.c.
References _, current_target_desc, gdbarch_info_init(), gdbarch_update_p(), internal_error(), and target_desc_fetched.
Referenced by follow_exec(), remote_start_remote(), set_tdesc_filename_cmd(), target_pre_inferior(), and unset_tdesc_filename_cmd().
struct target_desc* target_current_description (void) [read]
Definition at line 408 of file target-descriptions.c.
References current_target_desc, and target_desc_fetched.
Referenced by gdbarch_update_p(), and set_gdbarch_from_file().
void target_desc_info_free (struct target_desc_info * tdesc_info)
Definition at line 299 of file target-descriptions.c.
References target_desc_info::filename, and xfree().
Referenced by free_inferior().
int target_desc_info_from_user_p (struct target_desc_info * info)
Definition at line 278 of file target-descriptions.c.
References target_desc_info::filename.
Referenced by clone_inferior_command().
void target_find_description (void)
Definition at line 325 of file target-descriptions.c.
References _, current_target, current_target_desc, file_read_description_xml(), gdb_assert, gdbarch_data(), gdbarch_info_init(), gdbarch_target_desc(), gdbarch_update_p(), gdbarch_info::target_desc, target_desc_fetched, target_description_filename, target_gdbarch(), target_read_description(), target_read_description_xml(), tdesc_has_registers(), and warning().
Referenced by extended_remote_attach_1(), follow_exec(), post_create_inferior(), remote_start_remote(), set_tdesc_filename_cmd(), and unset_tdesc_filename_cmd().
void tdesc_add_bitfield (struct tdesc_type * type, const char * field_name, int start, int end)
Definition at line 1389 of file target-descriptions.c.
References tdesc_type_field::end, gdb_assert, tdesc_type::kind, tdesc_type_field::name, tdesc_type_field::start, tdesc_type::u, and VEC_safe_push.
void tdesc_add_compatible (struct target_desc * , const struct bfd_arch_info *)
Definition at line 1488 of file target-descriptions.c.
References _, internal_error(), VEC_iterate, and VEC_safe_push.
Referenced by initialize_tdesc_powerpc_cell32l(), and initialize_tdesc_powerpc_cell64l().
void tdesc_add_field (struct tdesc_type * type, const char * field_name, struct tdesc_type * field_type)
Definition at line 1372 of file target-descriptions.c.
References gdb_assert, tdesc_type::kind, tdesc_type_field::name, tdesc_type_field::type, tdesc_type::u, and VEC_safe_push.
Referenced by initialize_tdesc_aarch64(), initialize_tdesc_amd64(), initialize_tdesc_amd64_avx(), initialize_tdesc_amd64_avx_linux(), initialize_tdesc_amd64_linux(), initialize_tdesc_arm_with_iwmmxt(), initialize_tdesc_i386(), initialize_tdesc_i386_avx(), initialize_tdesc_i386_avx_linux(), initialize_tdesc_i386_linux(), initialize_tdesc_powerpc_7400(), initialize_tdesc_powerpc_altivec32(), initialize_tdesc_powerpc_altivec32l(), initialize_tdesc_powerpc_altivec64(), initialize_tdesc_powerpc_altivec64l(), initialize_tdesc_powerpc_cell32l(), initialize_tdesc_powerpc_cell64l(), initialize_tdesc_powerpc_isa205_altivec32l(), initialize_tdesc_powerpc_isa205_altivec64l(), initialize_tdesc_powerpc_isa205_vsx32l(), initialize_tdesc_powerpc_isa205_vsx64l(), initialize_tdesc_powerpc_vsx32(), initialize_tdesc_powerpc_vsx32l(), initialize_tdesc_powerpc_vsx64(), initialize_tdesc_powerpc_vsx64l(), initialize_tdesc_x32(), initialize_tdesc_x32_avx(), initialize_tdesc_x32_avx_linux(), and initialize_tdesc_x32_linux().
void tdesc_add_flag (struct tdesc_type * type, int start, const char * flag_name)
Definition at line 1404 of file target-descriptions.c.
References gdb_assert, tdesc_type::kind, tdesc_type_flag::name, tdesc_type_flag::start, tdesc_type::u, and VEC_safe_push.
Referenced by initialize_tdesc_amd64(), initialize_tdesc_amd64_avx(), initialize_tdesc_amd64_avx_linux(), initialize_tdesc_amd64_linux(), initialize_tdesc_i386(), initialize_tdesc_i386_avx(), initialize_tdesc_i386_avx_linux(), initialize_tdesc_i386_linux(), initialize_tdesc_i386_mmx(), initialize_tdesc_i386_mmx_linux(), initialize_tdesc_x32(), initialize_tdesc_x32_avx(), initialize_tdesc_x32_avx_linux(), and initialize_tdesc_x32_linux().
struct bfd_arch_info* tdesc_architecture (const struct target_desc *) [read]
Definition at line 462 of file target-descriptions.c.
References target_desc::arch.
Referenced by choose_architecture_for_target(), and maint_print_c_tdesc_cmd().
int tdesc_compatible_p (const struct target_desc * , const struct bfd_arch_info *)
Definition at line 420 of file target-descriptions.c.
References VEC_iterate.
Referenced by choose_architecture_for_target(), and ppc_linux_init_abi().
struct tdesc_feature* tdesc_create_feature (struct target_desc * tdesc, const char * name) [read]
Definition at line 1437 of file target-descriptions.c.
References tdesc_feature::name, VEC_safe_push, and XZALLOC.
Referenced by initialize_tdesc_aarch64(), initialize_tdesc_amd64(), initialize_tdesc_amd64_avx(), initialize_tdesc_amd64_avx_linux(), initialize_tdesc_amd64_linux(), initialize_tdesc_arm_with_iwmmxt(), initialize_tdesc_arm_with_m(), initialize_tdesc_arm_with_m_fpa_layout(), initialize_tdesc_arm_with_m_vfp_d16(), initialize_tdesc_arm_with_neon(), initialize_tdesc_arm_with_vfpv2(), initialize_tdesc_arm_with_vfpv3(), initialize_tdesc_i386(), initialize_tdesc_i386_avx(), initialize_tdesc_i386_avx_linux(), initialize_tdesc_i386_linux(), initialize_tdesc_i386_mmx(), initialize_tdesc_i386_mmx_linux(), initialize_tdesc_mips64_dsp_linux(), initialize_tdesc_mips64_linux(), initialize_tdesc_mips_dsp_linux(), initialize_tdesc_mips_linux(), initialize_tdesc_nios2(), initialize_tdesc_nios2_linux(), initialize_tdesc_powerpc_32(), initialize_tdesc_powerpc_32l(), initialize_tdesc_powerpc_403(), initialize_tdesc_powerpc_403gc(), initialize_tdesc_powerpc_405(), initialize_tdesc_powerpc_505(), initialize_tdesc_powerpc_601(), initialize_tdesc_powerpc_602(), initialize_tdesc_powerpc_603(), initialize_tdesc_powerpc_604(), initialize_tdesc_powerpc_64(), initialize_tdesc_powerpc_64l(), initialize_tdesc_powerpc_7400(), initialize_tdesc_powerpc_750(), initialize_tdesc_powerpc_860(), initialize_tdesc_powerpc_altivec32(), initialize_tdesc_powerpc_altivec32l(), initialize_tdesc_powerpc_altivec64(), initialize_tdesc_powerpc_altivec64l(), initialize_tdesc_powerpc_cell32l(), initialize_tdesc_powerpc_cell64l(), initialize_tdesc_powerpc_e500(), initialize_tdesc_powerpc_e500l(), initialize_tdesc_powerpc_isa205_32l(), initialize_tdesc_powerpc_isa205_64l(), initialize_tdesc_powerpc_isa205_altivec32l(), initialize_tdesc_powerpc_isa205_altivec64l(), initialize_tdesc_powerpc_isa205_vsx32l(), initialize_tdesc_powerpc_isa205_vsx64l(), initialize_tdesc_powerpc_vsx32(), initialize_tdesc_powerpc_vsx32l(), initialize_tdesc_powerpc_vsx64(), initialize_tdesc_powerpc_vsx64l(), initialize_tdesc_rs6000(), initialize_tdesc_s390_linux32(), initialize_tdesc_s390_linux32v1(), initialize_tdesc_s390_linux32v2(), initialize_tdesc_s390_linux64(), initialize_tdesc_s390_linux64v1(), initialize_tdesc_s390_linux64v2(), initialize_tdesc_s390_te_linux64(), initialize_tdesc_s390x_linux64(), initialize_tdesc_s390x_linux64v1(), initialize_tdesc_s390x_linux64v2(), initialize_tdesc_s390x_te_linux64(), initialize_tdesc_tic6x_c62x(), initialize_tdesc_tic6x_c62x_linux(), initialize_tdesc_tic6x_c64x(), initialize_tdesc_tic6x_c64x_linux(), initialize_tdesc_tic6x_c64xp(), initialize_tdesc_tic6x_c64xp_linux(), initialize_tdesc_x32(), initialize_tdesc_x32_avx(), initialize_tdesc_x32_avx_linux(), and initialize_tdesc_x32_linux().
struct tdesc_type* tdesc_create_flags (struct tdesc_feature * feature, const char * name, LONGEST size) [read]
Definition at line 1354 of file target-descriptions.c.
References tdesc_type::kind, tdesc_type::name, size, tdesc_type::TDESC_TYPE_FLAGS, type, tdesc_type::u, VEC_safe_push, and XZALLOC.
Referenced by initialize_tdesc_amd64(), initialize_tdesc_amd64_avx(), initialize_tdesc_amd64_avx_linux(), initialize_tdesc_amd64_linux(), initialize_tdesc_i386(), initialize_tdesc_i386_avx(), initialize_tdesc_i386_avx_linux(), initialize_tdesc_i386_linux(), initialize_tdesc_i386_mmx(), initialize_tdesc_i386_mmx_linux(), initialize_tdesc_x32(), initialize_tdesc_x32_avx(), initialize_tdesc_x32_avx_linux(), and initialize_tdesc_x32_linux().
void tdesc_create_reg (struct tdesc_feature * feature, const char * name, int regnum, int save_restore, const char * group, int bitsize, const char * type)
Definition at line 1241 of file target-descriptions.c.
References tdesc_reg::bitsize, tdesc_reg::group, tdesc_reg::name, regnum, tdesc_reg::save_restore, tdesc_reg::target_regnum, tdesc_named_type(), tdesc_reg::tdesc_type, tdesc_reg::type, VEC_safe_push, and XZALLOC.
Referenced by initialize_tdesc_aarch64(), initialize_tdesc_amd64(), initialize_tdesc_amd64_avx(), initialize_tdesc_amd64_avx_linux(), initialize_tdesc_amd64_linux(), initialize_tdesc_arm_with_iwmmxt(), initialize_tdesc_arm_with_m(), initialize_tdesc_arm_with_m_fpa_layout(), initialize_tdesc_arm_with_m_vfp_d16(), initialize_tdesc_arm_with_neon(), initialize_tdesc_arm_with_vfpv2(), initialize_tdesc_arm_with_vfpv3(), initialize_tdesc_i386(), initialize_tdesc_i386_avx(), initialize_tdesc_i386_avx_linux(), initialize_tdesc_i386_linux(), initialize_tdesc_i386_mmx(), initialize_tdesc_i386_mmx_linux(), initialize_tdesc_mips64_dsp_linux(), initialize_tdesc_mips64_linux(), initialize_tdesc_mips_dsp_linux(), initialize_tdesc_mips_linux(), initialize_tdesc_nios2(), initialize_tdesc_nios2_linux(), initialize_tdesc_powerpc_32(), initialize_tdesc_powerpc_32l(), initialize_tdesc_powerpc_403(), initialize_tdesc_powerpc_403gc(), initialize_tdesc_powerpc_405(), initialize_tdesc_powerpc_505(), initialize_tdesc_powerpc_601(), initialize_tdesc_powerpc_602(), initialize_tdesc_powerpc_603(), initialize_tdesc_powerpc_604(), initialize_tdesc_powerpc_64(), initialize_tdesc_powerpc_64l(), initialize_tdesc_powerpc_7400(), initialize_tdesc_powerpc_750(), initialize_tdesc_powerpc_860(), initialize_tdesc_powerpc_altivec32(), initialize_tdesc_powerpc_altivec32l(), initialize_tdesc_powerpc_altivec64(), initialize_tdesc_powerpc_altivec64l(), initialize_tdesc_powerpc_cell32l(), initialize_tdesc_powerpc_cell64l(), initialize_tdesc_powerpc_e500(), initialize_tdesc_powerpc_e500l(), initialize_tdesc_powerpc_isa205_32l(), initialize_tdesc_powerpc_isa205_64l(), initialize_tdesc_powerpc_isa205_altivec32l(), initialize_tdesc_powerpc_isa205_altivec64l(), initialize_tdesc_powerpc_isa205_vsx32l(), initialize_tdesc_powerpc_isa205_vsx64l(), initialize_tdesc_powerpc_vsx32(), initialize_tdesc_powerpc_vsx32l(), initialize_tdesc_powerpc_vsx64(), initialize_tdesc_powerpc_vsx64l(), initialize_tdesc_rs6000(), initialize_tdesc_s390_linux32(), initialize_tdesc_s390_linux32v1(), initialize_tdesc_s390_linux32v2(), initialize_tdesc_s390_linux64(), initialize_tdesc_s390_linux64v1(), initialize_tdesc_s390_linux64v2(), initialize_tdesc_s390_te_linux64(), initialize_tdesc_s390x_linux64(), initialize_tdesc_s390x_linux64v1(), initialize_tdesc_s390x_linux64v2(), initialize_tdesc_s390x_te_linux64(), initialize_tdesc_tic6x_c62x(), initialize_tdesc_tic6x_c62x_linux(), initialize_tdesc_tic6x_c64x(), initialize_tdesc_tic6x_c64x_linux(), initialize_tdesc_tic6x_c64xp(), initialize_tdesc_tic6x_c64xp_linux(), initialize_tdesc_x32(), initialize_tdesc_x32_avx(), initialize_tdesc_x32_avx_linux(), and initialize_tdesc_x32_linux().
struct tdesc_type* tdesc_create_struct (struct tdesc_feature * feature, const char * name) [read]
Definition at line 1319 of file target-descriptions.c.
References tdesc_type::kind, tdesc_type::name, tdesc_type::TDESC_TYPE_STRUCT, type, VEC_safe_push, and XZALLOC.
struct tdesc_type* tdesc_create_union (struct tdesc_feature * feature, const char * name) [read]
Definition at line 1342 of file target-descriptions.c.
References tdesc_type::kind, tdesc_type::name, tdesc_type::TDESC_TYPE_UNION, type, VEC_safe_push, and XZALLOC.
Referenced by initialize_tdesc_aarch64(), initialize_tdesc_amd64(), initialize_tdesc_amd64_avx(), initialize_tdesc_amd64_avx_linux(), initialize_tdesc_amd64_linux(), initialize_tdesc_arm_with_iwmmxt(), initialize_tdesc_i386(), initialize_tdesc_i386_avx(), initialize_tdesc_i386_avx_linux(), initialize_tdesc_i386_linux(), initialize_tdesc_powerpc_7400(), initialize_tdesc_powerpc_altivec32(), initialize_tdesc_powerpc_altivec32l(), initialize_tdesc_powerpc_altivec64(), initialize_tdesc_powerpc_altivec64l(), initialize_tdesc_powerpc_cell32l(), initialize_tdesc_powerpc_cell64l(), initialize_tdesc_powerpc_isa205_altivec32l(), initialize_tdesc_powerpc_isa205_altivec64l(), initialize_tdesc_powerpc_isa205_vsx32l(), initialize_tdesc_powerpc_isa205_vsx64l(), initialize_tdesc_powerpc_vsx32(), initialize_tdesc_powerpc_vsx32l(), initialize_tdesc_powerpc_vsx64(), initialize_tdesc_powerpc_vsx64l(), initialize_tdesc_x32(), initialize_tdesc_x32_avx(), initialize_tdesc_x32_avx_linux(), and initialize_tdesc_x32_linux().
struct tdesc_type* tdesc_create_vector (struct tdesc_feature * feature, const char * name, struct tdesc_type * field_type, int count) [read]
Definition at line 1304 of file target-descriptions.c.
References tdesc_type::count, tdesc_type::kind, tdesc_type::name, tdesc_type::TDESC_TYPE_VECTOR, type, tdesc_type::u, VEC_safe_push, and XZALLOC.
Referenced by initialize_tdesc_aarch64(), initialize_tdesc_amd64(), initialize_tdesc_amd64_avx(), initialize_tdesc_amd64_avx_linux(), initialize_tdesc_amd64_linux(), initialize_tdesc_arm_with_iwmmxt(), initialize_tdesc_i386(), initialize_tdesc_i386_avx(), initialize_tdesc_i386_avx_linux(), initialize_tdesc_i386_linux(), initialize_tdesc_powerpc_7400(), initialize_tdesc_powerpc_altivec32(), initialize_tdesc_powerpc_altivec32l(), initialize_tdesc_powerpc_altivec64(), initialize_tdesc_powerpc_altivec64l(), initialize_tdesc_powerpc_cell32l(), initialize_tdesc_powerpc_cell64l(), initialize_tdesc_powerpc_isa205_altivec32l(), initialize_tdesc_powerpc_isa205_altivec64l(), initialize_tdesc_powerpc_isa205_vsx32l(), initialize_tdesc_powerpc_isa205_vsx64l(), initialize_tdesc_powerpc_vsx32(), initialize_tdesc_powerpc_vsx32l(), initialize_tdesc_powerpc_vsx64(), initialize_tdesc_powerpc_vsx64l(), initialize_tdesc_x32(), initialize_tdesc_x32_avx(), initialize_tdesc_x32_avx_linux(), and initialize_tdesc_x32_linux().
struct tdesc_arch_data* tdesc_data_alloc (void) [read]
Definition at line 805 of file target-descriptions.c.
References XZALLOC.
Referenced by aarch64_gdbarch_init(), arm_gdbarch_init(), i386_gdbarch_init(), m68k_gdbarch_init(), mips_gdbarch_init(), nios2_gdbarch_init(), rs6000_gdbarch_init(), s390_gdbarch_init(), and tic6x_gdbarch_init().
void tdesc_data_cleanup (void * data_untyped)
Definition at line 815 of file target-descriptions.c.
References VEC_free, and xfree().
Referenced by aarch64_gdbarch_init(), arm_gdbarch_init(), i386_gdbarch_init(), m68k_gdbarch_init(), mips_gdbarch_init(), nios2_gdbarch_init(), rs6000_gdbarch_init(), s390_gdbarch_init(), and tic6x_gdbarch_init().
const char* tdesc_feature_name (const struct tdesc_feature * feature)
Definition at line 520 of file target-descriptions.c.
References tdesc_feature::name.
struct tdesc_feature* tdesc_find_feature (const struct target_desc * , const char * name) [read]
Definition at line 502 of file target-descriptions.c.
References tdesc_feature::name, and VEC_iterate.
Referenced by aarch64_gdbarch_init(), amd64_init_abi(), amd64_linux_init_abi(), amd64_x32_linux_init_abi(), arm_gdbarch_init(), i386_linux_init_abi(), i386_validate_tdesc_p(), m68k_gdbarch_init(), mips_gdbarch_init(), mips_linux_init_abi(), nios2_gdbarch_init(), ppc_linux_init_abi(), rs6000_gdbarch_init(), s390_gdbarch_init(), and tic6x_gdbarch_init().
struct type* tdesc_find_type (struct gdbarch * gdbarch, const char * id) [read]
Definition at line 571 of file target-descriptions.c.
References gdbarch_data(), tdesc_type::name, tdesc_arch_reg::reg, tdesc_reg::tdesc_type, tdesc_arch_reg::type, VEC_index, and VEC_length.
Referenced by i387_ext_type(), and tdesc_gdb_type().
int tdesc_has_registers (const struct target_desc *)
Definition at line 481 of file target-descriptions.c.
References VEC_empty, and VEC_iterate.
Referenced by aarch64_gdbarch_init(), amd64_init_abi(), amd64_linux_init_abi(), amd64_x32_init_abi(), amd64_x32_linux_init_abi(), arm_gdbarch_init(), arm_register_type(), i386_gdbarch_init(), i386_go32_init_abi(), i386_linux_init_abi(), i386_validate_tdesc_p(), m68k_gdbarch_init(), mips_gdbarch_init(), mips_linux_restart_reg_p(), mips_register_name(), nios2_gdbarch_init(), nios2_register_type(), ppc_linux_trap_reg_p(), rs6000_gdbarch_init(), s390_gdbarch_init(), target_find_description(), tdesc_use_registers(), tic6x_gdbarch_init(), and tic6x_register_name().
struct tdesc_type* tdesc_named_type (const struct tdesc_feature * feature, const char * id) [read]
Definition at line 550 of file target-descriptions.c.
References name, tdesc_type::name, type, and VEC_iterate.
Referenced by initialize_tdesc_aarch64(), initialize_tdesc_amd64(), initialize_tdesc_amd64_avx(), initialize_tdesc_amd64_avx_linux(), initialize_tdesc_amd64_linux(), initialize_tdesc_arm_with_iwmmxt(), initialize_tdesc_i386(), initialize_tdesc_i386_avx(), initialize_tdesc_i386_avx_linux(), initialize_tdesc_i386_linux(), initialize_tdesc_powerpc_7400(), initialize_tdesc_powerpc_altivec32(), initialize_tdesc_powerpc_altivec32l(), initialize_tdesc_powerpc_altivec64(), initialize_tdesc_powerpc_altivec64l(), initialize_tdesc_powerpc_cell32l(), initialize_tdesc_powerpc_cell64l(), initialize_tdesc_powerpc_isa205_altivec32l(), initialize_tdesc_powerpc_isa205_altivec64l(), initialize_tdesc_powerpc_isa205_vsx32l(), initialize_tdesc_powerpc_isa205_vsx64l(), initialize_tdesc_powerpc_vsx32(), initialize_tdesc_powerpc_vsx32l(), initialize_tdesc_powerpc_vsx64(), initialize_tdesc_powerpc_vsx64l(), initialize_tdesc_x32(), initialize_tdesc_x32_avx(), initialize_tdesc_x32_avx_linux(), initialize_tdesc_x32_linux(), and tdesc_create_reg().
int tdesc_numbered_register (const struct tdesc_feature * feature, struct tdesc_arch_data * data, int regno, const char * name)
Definition at line 844 of file target-descriptions.c.
References tdesc_arch_reg::reg, tdesc_find_register_early(), VEC_length, VEC_replace, and VEC_safe_push.
Referenced by aarch64_gdbarch_init(), amd64_linux_init_abi(), amd64_x32_linux_init_abi(), arm_gdbarch_init(), i386_linux_init_abi(), i386_validate_tdesc_p(), m68k_gdbarch_init(), mips_gdbarch_init(), mips_linux_init_abi(), nios2_gdbarch_init(), ppc_linux_init_abi(), rs6000_gdbarch_init(), s390_gdbarch_init(), tdesc_numbered_register_choices(), and tic6x_gdbarch_init().
int tdesc_numbered_register_choices (const struct tdesc_feature * feature, struct tdesc_arch_data * data, int regno, const char *const names[])
Definition at line 882 of file target-descriptions.c.
References tdesc_numbered_register().
Referenced by arm_gdbarch_init(), and rs6000_gdbarch_init().
enum gdb_osabi tdesc_osabi (const struct target_desc *)
Definition at line 471 of file target-descriptions.c.
References target_desc::osabi.
Referenced by gdbarch_info_fill(), and maint_print_c_tdesc_cmd().
const char* tdesc_property (const struct target_desc * , const char * key)
Definition at line 445 of file target-descriptions.c.
References property::key, property::value, and VEC_iterate.
Referenced by mips_gdbarch_init().
int tdesc_register_in_reggroup_p (struct gdbarch * gdbarch, int regno, struct reggroup * reggroup)
Definition at line 1055 of file target-descriptions.c.
References float_reggroup, general_reggroup, tdesc_reg::group, restore_reggroup, save_reggroup, tdesc_reg::save_restore, tdesc_find_register(), and vector_reggroup.
Referenced by mips_tdesc_register_reggroup_p(), and tdesc_register_reggroup_p().
const char* tdesc_register_name (struct gdbarch * gdbarch, int regno)
Definition at line 934 of file target-descriptions.c.
References gdb_assert, gdbarch_data(), gdbarch_num_pseudo_regs(), gdbarch_num_regs(), tdesc_reg::name, and tdesc_find_register().
Referenced by i386_register_name(), mips_register_name(), nios2_register_name(), rs6000_register_name(), tdesc_use_registers(), and tic6x_register_name().
int tdesc_register_size (const struct tdesc_feature * feature, const char * name)
Definition at line 899 of file target-descriptions.c.
References tdesc_reg::bitsize, gdb_assert, and tdesc_find_register_early().
Referenced by rs6000_gdbarch_init().
struct type* tdesc_register_type (struct gdbarch * gdbarch, int regno) [read]
Definition at line 955 of file target-descriptions.c.
References _, tdesc_reg::bitsize, builtin_type::builtin_char, builtin_type::builtin_data_ptr, builtin_type::builtin_double, builtin_type::builtin_float, builtin_type::builtin_int, builtin_type::builtin_int0, builtin_type::builtin_long, builtin_type::builtin_long_double, builtin_type::builtin_long_long, builtin_type::builtin_short, builtin_type(), gdb_assert, gdbarch_data(), gdbarch_double_bit(), gdbarch_float_bit(), gdbarch_int_bit(), gdbarch_long_bit(), gdbarch_long_double_bit(), gdbarch_long_long_bit(), gdbarch_num_pseudo_regs(), gdbarch_num_regs(), gdbarch_ptr_bit(), gdbarch_short_bit(), internal_error(), tdesc_reg::name, tdesc_arch_reg::reg, tdesc_find_arch_register(), tdesc_gdb_type(), tdesc_reg::tdesc_type, tdesc_reg::type, tdesc_arch_reg::type, and warning().
Referenced by arm_register_type(), nios2_register_type(), and tdesc_use_registers().
void tdesc_set_struct_size (struct tdesc_type * type, LONGEST size)
Definition at line 1335 of file target-descriptions.c.
References gdb_assert, tdesc_type::kind, size, tdesc_type::TDESC_TYPE_STRUCT, and tdesc_type::u.
int tdesc_unnumbered_register (const struct tdesc_feature * feature, const char * name)
Definition at line 867 of file target-descriptions.c.
References tdesc_find_register_early().
Referenced by arm_gdbarch_init(), and s390_gdbarch_init().
void tdesc_use_registers (struct gdbarch * gdbarch, const struct target_desc * target_desc, struct tdesc_arch_data * early_data)
Definition at line 1150 of file target-descriptions.c.
References gdb_assert, gdbarch_data(), gdbarch_num_regs(), tdesc_arch_reg::reg, set_gdbarch_num_regs(), set_gdbarch_register_name(), set_gdbarch_register_reggroup_p(), set_gdbarch_register_type(), set_gdbarch_remote_register_number(), tdesc_has_registers(), tdesc_register_name(), tdesc_register_reggroup_p(), tdesc_register_type(), tdesc_remote_register_number(), VEC_iterate, VEC_length, VEC_safe_push, and xfree().
Referenced by aarch64_gdbarch_init(), arm_gdbarch_init(), i386_gdbarch_init(), m68k_gdbarch_init(), mips_gdbarch_init(), nios2_gdbarch_init(), rs6000_gdbarch_init(), s390_gdbarch_init(), and tic6x_gdbarch_init().