GDB (xrefs): /home/stan/gdb/src/gdb/target.h File Reference
/home/stan/gdb/src/gdb/target.h File Reference
#include "target/resume.h"
#include "target/wait.h"
#include "target/waitstatus.h"
#include "bfd.h"
#include "symtab.h"
#include "memattr.h"
#include "vec.h"
#include "gdb_signals.h"
#include "btrace.h"
#include "command.h"
Classes
struct syscall
struct memory_read_result
struct target_ops
struct memory_write_request
struct target_section
struct target_section_table
Defines
#define OPS_MAGIC 3840
#define target_shortname (current_target.to_shortname)
#define target_longname (current_target.to_longname)
#define target_attach_no_wait (current_target.to_attach_no_wait)
#define target_post_attach(pid) (*current_target.to_post_attach) (pid)
#define target_prepare_to_store(regcache) (*current_target.to_prepare_to_store) (regcache)
#define target_supports_multi_process() (*current_target.to_supports_multi_process) ()
#define target_supports_enable_disable_tracepoint() (*current_target.to_supports_enable_disable_tracepoint) ()
#define target_supports_string_tracing() (*current_target.to_supports_string_tracing) ()
#define target_supports_evaluation_of_breakpoint_conditions() (*current_target.to_supports_evaluation_of_breakpoint_conditions) ()
#define target_can_run_breakpoint_commands() (*current_target.to_can_run_breakpoint_commands) ()
#define target_files_info() (*current_target.to_files_info) (&current_target)
#define target_terminal_init() (*current_target.to_terminal_init) ()
#define target_terminal_ours_for_output() (*current_target.to_terminal_ours_for_output) ()
#define target_terminal_ours() (*current_target.to_terminal_ours) ()
#define target_terminal_save_ours() (*current_target.to_terminal_save_ours) ()
#define target_terminal_info(arg, from_tty) (*current_target.to_terminal_info) (arg, from_tty)
#define target_post_startup_inferior(ptid) (*current_target.to_post_startup_inferior) (ptid)
#define target_insert_fork_catchpoint(pid) (*current_target.to_insert_fork_catchpoint) (pid)
#define target_remove_fork_catchpoint(pid) (*current_target.to_remove_fork_catchpoint) (pid)
#define target_insert_vfork_catchpoint(pid) (*current_target.to_insert_vfork_catchpoint) (pid)
#define target_remove_vfork_catchpoint(pid) (*current_target.to_remove_vfork_catchpoint) (pid)
#define target_insert_exec_catchpoint(pid) (*current_target.to_insert_exec_catchpoint) (pid)
#define target_remove_exec_catchpoint(pid) (*current_target.to_remove_exec_catchpoint) (pid)
#define target_set_syscall_catchpoint(pid, needed, any_count, table_size, table)
#define target_has_exited(pid, wait_status, exit_status) (*current_target.to_has_exited) (pid,wait_status,exit_status)
#define target_can_run(t) ((t)->to_can_run) ()
#define target_rcmd(command, outbuf) (*current_target.to_rcmd) (command, outbuf)
#define target_has_all_memory target_has_all_memory_1 ()
#define target_has_memory target_has_memory_1 ()
#define target_has_stack target_has_stack_1 ()
#define target_has_registers target_has_registers_1 ()
#define target_has_execution target_has_execution_current ()
#define target_can_lock_scheduler (current_target.to_has_thread_control & tc_schedlock)
#define target_can_async_p() (current_target.to_can_async_p ())
#define target_is_async_p() (current_target.to_is_async_p ())
#define target_async(CALLBACK, CONTEXT) (current_target.to_async ((CALLBACK), (CONTEXT)))
#define target_execution_direction() (current_target.to_execution_direction ())
#define target_extra_thread_info(TP) (current_target.to_extra_thread_info (TP))
#define target_pid_to_exec_file(pid) (current_target.to_pid_to_exec_file) (pid)
#define target_thread_architecture(ptid) (current_target.to_thread_architecture (&current_target, ptid))
#define target_find_memory_regions(FUNC, DATA) (current_target.to_find_memory_regions) (FUNC, DATA)
#define target_make_corefile_notes(BFD, SIZE_P) (current_target.to_make_corefile_notes) (BFD, SIZE_P)
#define target_get_bookmark(ARGS, FROM_TTY) (current_target.to_get_bookmark) (ARGS, FROM_TTY)
#define target_goto_bookmark(ARG, FROM_TTY) (current_target.to_goto_bookmark) (ARG, FROM_TTY)
#define target_stopped_by_watchpoint (*current_target.to_stopped_by_watchpoint)
#define target_have_steppable_watchpoint (current_target.to_have_steppable_watchpoint)
#define target_have_continuable_watchpoint (current_target.to_have_continuable_watchpoint)
#define target_can_use_hardware_watchpoint(TYPE, CNT, OTHERTYPE) (*current_target.to_can_use_hw_breakpoint) (TYPE, CNT, OTHERTYPE);
#define target_region_ok_for_hw_watchpoint(addr, len) (*current_target.to_region_ok_for_hw_watchpoint) (addr, len)
#define target_insert_watchpoint(addr, len, type, cond) (*current_target.to_insert_watchpoint) (addr, len, type, cond)
#define target_remove_watchpoint(addr, len, type, cond) (*current_target.to_remove_watchpoint) (addr, len, type, cond)
#define target_insert_hw_breakpoint(gdbarch, bp_tgt) (*current_target.to_insert_hw_breakpoint) (gdbarch, bp_tgt)
#define target_remove_hw_breakpoint(gdbarch, bp_tgt) (*current_target.to_remove_hw_breakpoint) (gdbarch, bp_tgt)
#define target_stopped_data_address(target, addr_p) (*target.to_stopped_data_address) (target, addr_p)
#define target_watchpoint_addr_within_range(target, addr, start, length) (*target.to_watchpoint_addr_within_range) (target, addr, start, length)
#define target_can_accel_watchpoint_condition(addr, len, type, cond) (*current_target.to_can_accel_watchpoint_condition) (addr, len, type, cond)
#define target_can_execute_reverse
#define target_get_ada_task_ptid(lwp, tid) (*current_target.to_get_ada_task_ptid) (lwp,tid)
#define target_trace_init() (*current_target.to_trace_init) ()
#define target_download_tracepoint(t) (*current_target.to_download_tracepoint) (t)
#define target_can_download_tracepoint() (*current_target.to_can_download_tracepoint) ()
#define target_download_trace_state_variable(tsv) (*current_target.to_download_trace_state_variable) (tsv)
#define target_enable_tracepoint(loc) (*current_target.to_enable_tracepoint) (loc)
#define target_disable_tracepoint(loc) (*current_target.to_disable_tracepoint) (loc)
#define target_trace_start() (*current_target.to_trace_start) ()
#define target_trace_set_readonly_regions() (*current_target.to_trace_set_readonly_regions) ()
#define target_get_trace_status(ts) (*current_target.to_get_trace_status) (ts)
#define target_get_tracepoint_status(tp, utp) (*current_target.to_get_tracepoint_status) (tp, utp)
#define target_trace_stop() (*current_target.to_trace_stop) ()
#define target_trace_find(type, num, addr1, addr2, tpp) (*current_target.to_trace_find) ((type), (num), (addr1), (addr2), (tpp))
#define target_get_trace_state_variable_value(tsv, val) (*current_target.to_get_trace_state_variable_value) ((tsv), (val))
#define target_save_trace_data(filename) (*current_target.to_save_trace_data) (filename)
#define target_upload_tracepoints(utpp) (*current_target.to_upload_tracepoints) (utpp)
#define target_upload_trace_state_variables(utsvp) (*current_target.to_upload_trace_state_variables) (utsvp)
#define target_get_raw_trace_data(buf, offset, len) (*current_target.to_get_raw_trace_data) ((buf), (offset), (len))
#define target_get_min_fast_tracepoint_insn_len() (*current_target.to_get_min_fast_tracepoint_insn_len) ()
#define target_set_disconnected_tracing(val) (*current_target.to_set_disconnected_tracing) (val)
#define target_set_circular_trace_buffer(val) (*current_target.to_set_circular_trace_buffer) (val)
#define target_set_trace_buffer_size(val) (*current_target.to_set_trace_buffer_size) (val)
#define target_set_trace_notes(user, notes, stopnotes) (*current_target.to_set_trace_notes) ((user), (notes), (stopnotes))
#define target_get_tib_address(ptid, addr) (*current_target.to_get_tib_address) ((ptid), (addr))
#define target_set_permissions() (*current_target.to_set_permissions) ()
#define target_static_tracepoint_marker_at(addr, marker) (*current_target.to_static_tracepoint_marker_at) (addr, marker)
#define target_static_tracepoint_markers_by_strid(marker_id) (*current_target.to_static_tracepoint_markers_by_strid) (marker_id)
#define target_traceframe_info() (*current_target.to_traceframe_info) ()
#define target_use_agent(use) (*current_target.to_use_agent) (use)
#define target_can_use_agent() (*current_target.to_can_use_agent) ()
#define target_augmented_libraries_svr4_read() (*current_target.to_augmented_libraries_svr4_read) ()
#define target_log_command(p)
Typedefs
typedef struct
static_tracepoint_marker * static_tracepoint_marker_p
typedef struct memory_read_result memory_read_result_s
typedef struct memory_write_request memory_write_request_s
Enumerations
enum strata {
dummy_stratum, file_stratum, process_stratum, thread_stratum,
record_stratum, arch_stratum
}
enum thread_control_capabilities { tc_none = 0, tc_schedlock = 1 }
enum inferior_event_type { INF_REG_EVENT, INF_TIMER, INF_EXEC_COMPLETE, INF_EXEC_CONTINUE }
enum target_object {
TARGET_OBJECT_AVR, TARGET_OBJECT_SPU, TARGET_OBJECT_MEMORY, TARGET_OBJECT_RAW_MEMORY,
TARGET_OBJECT_STACK_MEMORY, TARGET_OBJECT_UNWIND_TABLE, TARGET_OBJECT_AUXV, TARGET_OBJECT_WCOOKIE,
TARGET_OBJECT_MEMORY_MAP, TARGET_OBJECT_FLASH, TARGET_OBJECT_AVAILABLE_FEATURES, TARGET_OBJECT_LIBRARIES,
TARGET_OBJECT_LIBRARIES_SVR4, TARGET_OBJECT_LIBRARIES_AIX, TARGET_OBJECT_OSDATA, TARGET_OBJECT_SIGNAL_INFO,
TARGET_OBJECT_THREADS, TARGET_OBJECT_STATIC_TRACE_DATA, TARGET_OBJECT_HPUX_UREGS, TARGET_OBJECT_HPUX_SOLIB_GOT,
TARGET_OBJECT_TRACEFRAME_INFO, TARGET_OBJECT_FDPIC, TARGET_OBJECT_DARWIN_DYLD_INFO, TARGET_OBJECT_OPENVMS_UIB,
TARGET_OBJECT_BTRACE
}
enum target_xfer_error { TARGET_XFER_E_IO = -1, TARGET_XFER_E_UNAVAILABLE = -2 }
enum trace_find_type {
tfind_number, tfind_pc, tfind_tp, tfind_range,
tfind_outside
}
enum flash_preserve_mode { flash_preserve, flash_discard }
Functions
char * target_waitstatus_to_string (const struct target_waitstatus *)
char * target_options_to_string (int target_options)
const char * target_xfer_error_to_string (enum target_xfer_error err)
DEF_VEC_P (static_tracepoint_marker_p)
LONGEST target_read (struct target_ops *ops, enum target_object object, const char *annex, gdb_byte *buf, ULONGEST offset, LONGEST len)
DEF_VEC_O (memory_read_result_s)
void free_memory_read_result_vector (void *)
VEC (memory_read_result_s)*read_memory_robust(struct target_ops *ops
LONGEST target_write (struct target_ops *ops, enum target_object object, const char *annex, const gdb_byte *buf, ULONGEST offset, LONGEST len)
LONGEST target_write_with_progress (struct target_ops *ops, enum target_object object, const char *annex, const gdb_byte *buf, ULONGEST offset, LONGEST len, void(*progress)(ULONGEST, void *), void *baton)
LONGEST target_read_alloc (struct target_ops *ops, enum target_object object, const char *annex, gdb_byte **buf_p)
char * target_read_stralloc (struct target_ops *ops, enum target_object object, const char *annex)
LONGEST target_xfer_partial (struct target_ops *ops, enum target_object object, const char *annex, void *readbuf, const void *writebuf, ULONGEST offset, LONGEST len)
void get_target_memory (struct target_ops *ops, CORE_ADDR addr, gdb_byte *buf, LONGEST len)
ULONGEST get_target_memory_unsigned (struct target_ops *ops, CORE_ADDR addr, int len, enum bfd_endian byte_order)
void target_close (struct target_ops *targ)
void target_attach (char *, int)
void target_detach (char *, int)
void target_disconnect (char *, int)
void target_resume (ptid_t ptid, int step, enum gdb_signal signal)
ptid_t target_wait (ptid_t ptid, struct target_waitstatus *status, int options)
void target_fetch_registers (struct regcache *regcache, int regno)
void target_store_registers (struct regcache *regcache, int regs)
struct address_space * target_thread_address_space (ptid_t)
int target_info_proc (char *, enum info_proc_what)
int target_supports_disable_randomization (void)
void target_dcache_invalidate (void)
int target_read_string (CORE_ADDR, char **, int, int *)
int target_read_memory (CORE_ADDR memaddr, gdb_byte *myaddr, ssize_t len)
int target_read_stack (CORE_ADDR memaddr, gdb_byte *myaddr, ssize_t len)
int target_write_memory (CORE_ADDR memaddr, const gdb_byte *myaddr, ssize_t len)
int target_write_raw_memory (CORE_ADDR memaddr, const gdb_byte *myaddr, ssize_t len)
VEC (mem_region_s)*target_memory_map(void)
void target_flash_erase (ULONGEST address, LONGEST length)
void target_flash_done (void)
DEF_VEC_O (memory_write_request_s)
int target_write_memory_blocks (VEC(memory_write_request_s)*requests, enum flash_preserve_mode preserve_flash_p, void(*progress_cb)(ULONGEST, void *))
int target_insert_breakpoint (struct gdbarch *gdbarch, struct bp_target_info *bp_tgt)
int target_remove_breakpoint (struct gdbarch *gdbarch, struct bp_target_info *bp_tgt)
void target_terminal_inferior (void)
void target_kill (void)
void target_load (char *arg, int from_tty)
void target_create_inferior (char *exec_file, char *args, char **env, int from_tty)
int target_follow_fork (int follow_child, int detach_fork)
void target_mourn_inferior (void)
void target_pass_signals (int nsig, unsigned char *pass_signals)
void target_program_signals (int nsig, unsigned char *program_signals)
int target_thread_alive (ptid_t ptid)
void target_find_new_threads (void)
void target_stop (ptid_t ptid)
int target_has_all_memory_1 (void)
int target_has_memory_1 (void)
int target_has_stack_1 (void)
int target_has_registers_1 (void)
int target_has_execution_1 (ptid_t)
int target_has_execution_current (void)
int default_child_has_all_memory (struct target_ops *ops)
int default_child_has_memory (struct target_ops *ops)
int default_child_has_stack (struct target_ops *ops)
int default_child_has_registers (struct target_ops *ops)
int default_child_has_execution (struct target_ops *ops, ptid_t the_ptid)
int target_supports_non_stop (void)
char * target_pid_to_str (ptid_t ptid)
char * normal_pid_to_str (ptid_t ptid)
char * target_thread_name (struct thread_info *)
int target_insert_mask_watchpoint (CORE_ADDR, CORE_ADDR, int)
int target_remove_mask_watchpoint (CORE_ADDR, CORE_ADDR, int)
int target_ranged_break_num_registers (void)
int target_masked_watch_num_registers (CORE_ADDR addr, CORE_ADDR mask)
struct target_desc * target_read_description (struct target_ops *)
int simple_search_memory (struct target_ops *ops, CORE_ADDR start_addr, ULONGEST search_space_len, const gdb_byte *pattern, ULONGEST pattern_len, CORE_ADDR *found_addrp)
int target_search_memory (CORE_ADDR start_addr, ULONGEST search_space_len, const gdb_byte *pattern, ULONGEST pattern_len, CORE_ADDR *found_addrp)
int target_fileio_open (const char *filename, int flags, int mode, int *target_errno)
int target_fileio_pwrite (int fd, const gdb_byte *write_buf, int len, ULONGEST offset, int *target_errno)
int target_fileio_pread (int fd, gdb_byte *read_buf, int len, ULONGEST offset, int *target_errno)
int target_fileio_close (int fd, int *target_errno)
int target_fileio_unlink (const char *filename, int *target_errno)
char * target_fileio_readlink (const char *filename, int *target_errno)
LONGEST target_fileio_read_alloc (const char *filename, gdb_byte **buf_p)
char * target_fileio_read_stralloc (const char *filename)
int target_core_of_thread (ptid_t ptid)
int target_verify_memory (const gdb_byte *data, CORE_ADDR memaddr, ULONGEST size)
void add_target (struct target_ops *)
void add_target_with_completer (struct target_ops *t, completer_ftype *completer)
void complete_target_initialization (struct target_ops *t)
void add_deprecated_target_alias (struct target_ops *t, char *alias)
void push_target (struct target_ops *)
int unpush_target (struct target_ops *)
void target_pre_inferior (int)
void target_preopen (int)
void pop_all_targets (void)
void pop_all_targets_above (enum strata above_stratum)
int target_is_pushed (struct target_ops *t)
CORE_ADDR target_translate_tls_address (struct objfile *objfile, CORE_ADDR offset)
struct target_section * target_section_by_addr (struct target_ops *target, CORE_ADDR addr)
struct target_section_table * target_get_section_table (struct target_ops *target)
int memory_remove_breakpoint (struct gdbarch *, struct bp_target_info *)
int memory_insert_breakpoint (struct gdbarch *, struct bp_target_info *)
int default_memory_remove_breakpoint (struct gdbarch *, struct bp_target_info *)
int default_memory_insert_breakpoint (struct gdbarch *, struct bp_target_info *)
void initialize_targets (void)
void noprocess (void) ATTRIBUTE_NORETURN
void target_require_runnable (void)
void find_default_attach (struct target_ops *, char *, int)
void find_default_create_inferior (struct target_ops *, char *, char *, char **, int)
struct target_ops * find_target_beneath (struct target_ops *)
char * target_get_osdata (const char *type)
struct cleanup * make_show_memory_breakpoints_cleanup (int show)
void update_target_permissions (void)
void target_ignore (void)
int target_supports_btrace (void)
struct btrace_target_info * target_enable_btrace (ptid_t ptid)
void target_disable_btrace (struct btrace_target_info *btinfo)
void target_teardown_btrace (struct btrace_target_info *btinfo)
VEC (btrace_block_s)*target_read_btrace(struct btrace_target_info *
enum btrace_read_type void target_stop_recording (void)
void target_info_record (void)
void target_save_record (const char *filename)
int target_supports_delete_record (void)
void target_delete_record (void)
int target_record_is_replaying (void)
void target_goto_record_begin (void)
void target_goto_record_end (void)
void target_goto_record (ULONGEST insn)
void target_insn_history (int size, int flags)
void target_insn_history_from (ULONGEST from, int size, int flags)
void target_insn_history_range (ULONGEST begin, ULONGEST end, int flags)
void target_call_history (int size, int flags)
void target_call_history_from (ULONGEST begin, int size, int flags)
void target_call_history_range (ULONGEST begin, ULONGEST end, int flags)
Variables
ULONGEST offset
ULONGEST LONGEST len
struct target_ops current_target
int target_async_permitted
int remote_debug
int baud_rate
int remote_timeout
int may_write_registers
int may_write_memory
int may_insert_breakpoints
int may_insert_tracepoints
int may_insert_fast_tracepoints
int may_stop
Define Documentation
#define OPS_MAGIC 3840
Definition at line 899 of file target.h.
Referenced by _initialize_remote_mips(), bsd_kvm_add_target(), bsd_uthread_target(), inf_child_target(), init_aix_thread_ops(), init_base_monitor_ops(), init_core_ops(), init_dec_thread_ops(), init_dummy_target(), init_exec_ops(), init_gdbsim_ops(), init_go32_ops(), init_m32r_ops(), init_monitor_ops(), init_procfs_ops(), init_ravenscar_thread_ops(), init_record_btrace_ops(), init_record_full_core_ops(), init_record_full_ops(), init_remote_ops(), init_sol_thread_ops(), init_spu_ops(), init_tfile_ops(), init_thread_db_ops(), init_windows_ops(), procfs_target(), push_target(), target_bfd_reopen(), and target_is_pushed().
#define target_async (CALLBACK, CONTEXT) (current_target.to_async ((CALLBACK), (CONTEXT)))
Definition at line 1416 of file target.h.
Referenced by extended_remote_attach_1(), extended_remote_create_inferior_1(), inferior_event_handler(), linux_nat_attach(), linux_nat_resume(), linux_nat_wait(), record_full_core_resume(), record_full_resume(), remote_resume(), and remote_start_remote().
#define target_attach_no_wait (current_target.to_attach_no_wait)
Definition at line 934 of file target.h.
Referenced by attach_command().
#define target_augmented_libraries_svr4_read () (*current_target.to_augmented_libraries_svr4_read) ()
Definition at line 1758 of file target.h.
Referenced by solist_update_incremental().
#define target_can_accel_watchpoint_condition (addr, len, type, cond) (*current_target.to_can_accel_watchpoint_condition) (addr, len, type, cond)
Definition at line 1582 of file target.h.
Referenced by watchpoint_locations_match().
#define target_can_async_p () (current_target.to_can_async_p ())
Definition at line 1408 of file target.h.
Referenced by advance_command(), async_background_execution_p(), attach_command(), attach_command_post_wait(), bpstat_do_actions_1(), continue_command(), default_execution_direction(), extended_remote_attach_1(), extended_remote_create_inferior_1(), finish_command(), finish_forward(), handle_inferior_event(), interrupt_query(), interrupt_target_command(), jump_command(), linux_child_follow_fork(), linux_nat_attach(), linux_nat_resume(), linux_nat_wait(), linux_nat_wait_1(), mi_cmd_exec_run(), mi_cmd_list_target_features(), mi_execute_async_cli_command(), normal_stop(), notice_new_inferior(), proceed(), putpkt_binary(), record_full_core_resume(), record_full_resume(), remote_resume(), remote_start_remote(), remote_wait(), run_command_1(), run_inferior_call(), run_one_inferior(), signal_command(), step_1(), step_once(), target_terminal_inferior(), until_break_command(), until_command(), and until_next_command().
#define target_can_download_tracepoint () (*current_target.to_can_download_tracepoint) ()
Definition at line 1677 of file target.h.
Referenced by download_tracepoint_locations().
#define target_can_execute_reverse
Value:
(current_target.to_can_execute_reverse ? \
      current_target.to_can_execute_reverse () : 0)
Definition at line 1592 of file target.h.
Referenced by default_execution_direction(), exec_reverse_continue(), exec_reverse_once(), mi_cmd_list_target_features(), and set_exec_direction_func().
#define target_can_lock_scheduler (current_target.to_has_thread_control & tc_schedlock)
Definition at line 1400 of file target.h.
Referenced by set_schedlock_func().
#define target_can_run (t) ((t)->to_can_run) ()
Definition at line 1293 of file target.h.
Referenced by find_default_run_target(), irix_solib_create_inferior_hook(), osf_solib_create_inferior_hook(), procfs_inferior_created(), and thread_db_load().
#define target_can_run_breakpoint_commands () (*current_target.to_can_run_breakpoint_commands) ()
Definition at line 1042 of file target.h.
Referenced by build_target_command_list(), and update_dprintf_command_list().
#define target_can_use_agent () (*current_target.to_can_use_agent) ()
Definition at line 1755 of file target.h.
#define target_can_use_hardware_watchpoint (TYPE, CNT, OTHERTYPE) (*current_target.to_can_use_hw_breakpoint) (TYPE, CNT, OTHERTYPE);
Definition at line 1514 of file target.h.
Referenced by break_range_command(), enable_breakpoint_disp(), init_breakpoint_sal(), and update_watchpoint().
#define target_disable_tracepoint (loc) (*current_target.to_disable_tracepoint) (loc)
Definition at line 1686 of file target.h.
Referenced by disable_breakpoint(), and disable_command().
#define target_download_trace_state_variable (tsv) (*current_target.to_download_trace_state_variable) (tsv)
Definition at line 1680 of file target.h.
Referenced by start_tracing().
#define target_download_tracepoint (t) (*current_target.to_download_tracepoint) (t)
Definition at line 1674 of file target.h.
Referenced by download_tracepoint_locations(), and start_tracing().
#define target_enable_tracepoint (loc) (*current_target.to_enable_tracepoint) (loc)
Definition at line 1683 of file target.h.
Referenced by enable_breakpoint_disp(), and enable_command().
#define target_execution_direction () (current_target.to_execution_direction ())
Definition at line 1419 of file target.h.
Referenced by fetch_inferior_event().
#define target_extra_thread_info (TP) (current_target.to_extra_thread_info (TP))
Definition at line 1434 of file target.h.
Referenced by print_thread_info(), and thread_find_command().
#define target_files_info () (*current_target.to_files_info) (&current_target)
Definition at line 1117 of file target.h.
Referenced by program_info().
#define target_find_memory_regions (FUNC, DATA) (current_target.to_find_memory_regions) (FUNC, DATA)
Definition at line 1469 of file target.h.
Referenced by gcore_memory_sections().
#define target_get_ada_task_ptid (lwp, tid) (*current_target.to_get_ada_task_ptid) (lwp,tid)
Definition at line 1598 of file target.h.
Referenced by ptid_from_atcb_common().
#define target_get_bookmark (ARGS, FROM_TTY) (current_target.to_get_bookmark) (ARGS, FROM_TTY)
Definition at line 1480 of file target.h.
Referenced by save_bookmark_command().
#define target_get_min_fast_tracepoint_insn_len () (*current_target.to_get_min_fast_tracepoint_insn_len) ()
Definition at line 1722 of file target.h.
Referenced by i386_fast_tracepoint_valid_at().
#define target_get_raw_trace_data (buf, offset, len) (*current_target.to_get_raw_trace_data) ((buf), (offset), (len))
Definition at line 1719 of file target.h.
Referenced by trace_save().
#define target_get_tib_address (ptid, addr) (*current_target.to_get_tib_address) ((ptid), (addr))
Definition at line 1737 of file target.h.
Referenced by display_one_tib(), and tlb_value_read().
#define target_get_trace_state_variable_value (tsv, val) (*current_target.to_get_trace_state_variable_value) ((tsv), (val))
Definition at line 1707 of file target.h.
Referenced by mi_cmd_trace_frame_collected(), tvariables_info_1(), and value_of_internalvar().
#define target_get_trace_status (ts) (*current_target.to_get_trace_status) (ts)
Definition at line 1695 of file target.h.
Referenced by query_if_trace_running(), trace_save(), trace_status_command(), and trace_status_mi().
#define target_get_tracepoint_status (tp, utp) (*current_target.to_get_tracepoint_status) (tp, utp)
Definition at line 1698 of file target.h.
Referenced by trace_save(), and trace_status_command().
#define target_goto_bookmark (ARG, FROM_TTY) (current_target.to_goto_bookmark) (ARG, FROM_TTY)
Definition at line 1483 of file target.h.
Referenced by goto_bookmark_command().
#define target_has_all_memory target_has_all_memory_1 ()
Definition at line 1353 of file target.h.
#define target_has_execution target_has_execution_current ()
Definition at line 1385 of file target.h.
Referenced by add_thread_db_info(), attach_command(), attach_thread(), bpstat_do_actions(), call_function_by_hand(), checkpoint_command(), delete_step_thread_step_resume_breakpoint(), derive_heap_segment(), display_command(), dispose_inferior(), enable_break(), exec_file_command(), fetch_inferior_event(), find_function_in_inferior(), find_new_threads_callback(), finish_command_continuation(), gcore_command(), gdb_clear_file(), gdb_target_has_execution_command(), inferior_event_handler(), kill_if_already_running(), kill_or_detach(), linux_info_proc(), lookup_child_selector(), lookup_objc_class(), normal_stop(), program_info(), read_atcb(), record_btrace_open(), record_full_open_1(), reload_shared_libraries(), remote_check_symbols(), remote_detach_1(), remote_get_min_fast_tracepoint_insn_len(), remote_read_description(), remote_start_remote(), remote_xfer_partial(), restore_command(), restore_infcall_suspend_state(), rs6000_xfer_shared_libraries(), score7_fetch_inst(), set_non_stop(), set_observer_mode(), set_target_permissions(), spu_skip_standalone_loader(), step_1(), step_1_continuation(), svr4_solib_create_inferior_hook(), task_command(), thread_db_detach(), thread_db_find_new_threads(), thread_db_find_new_threads_silently(), try_thread_db_load_1(), update_solib_list(), update_watchpoint(), value_allocate_space_in_inferior(), and value_nsstring().
#define target_has_exited (pid, wait_status, exit_status) (*current_target.to_has_exited) (pid,wait_status,exit_status)
Definition at line 1279 of file target.h.
#define target_has_memory target_has_memory_1 ()
Definition at line 1358 of file target.h.
Referenced by do_restore_current_thread_cleanup(), get_current_frame(), has_stack_frames(), make_cleanup_restore_current_thread(), and tui_show_registers().
#define target_has_registers target_has_registers_1 ()
Definition at line 1369 of file target.h.
Referenced by arm_pc_is_thumb(), bpfinishpy_detect_out_scope_cb(), current_me_module(), current_options(), derive_stack_segment(), do_restore_current_thread_cleanup(), float_info(), gdb_block_vars(), gdb_get_blocks(), gdb_get_vars_command(), gdb_loc(), gdb_selected_block(), gdb_selected_frame(), get_current_frame(), get_register(), has_stack_frames(), ia64_frame_prev_register(), ia64_sigtramp_frame_prev_register(), libunwind_frame_prev_register(), make_cleanup_restore_current_thread(), mi_cmd_data_write_register_values(), register_changed_p(), registers_info(), thread_db_load(), tui_get_register(), tui_show_registers(), and vector_info().
#define target_has_stack target_has_stack_1 ()
Definition at line 1364 of file target.h.
Referenced by ada_build_task_list(), backtrace_command_1(), derive_stack_segment(), do_restore_current_thread_cleanup(), gdb_stack(), get_current_frame(), has_stack_frames(), info_auxv_command(), kill_command(), make_cleanup_restore_current_thread(), restore_infcall_control_state(), siginfo_make_value(), thread_command(), tlb_make_value(), and tui_show_registers().
#define target_have_continuable_watchpoint (current_target.to_have_continuable_watchpoint)
Definition at line 1501 of file target.h.
#define target_have_steppable_watchpoint (current_target.to_have_steppable_watchpoint)
Definition at line 1496 of file target.h.
Referenced by handle_inferior_event(), and procfs_insert_watchpoint().
#define target_insert_exec_catchpoint (pid) (*current_target.to_insert_exec_catchpoint) (pid)
Definition at line 1246 of file target.h.
Referenced by insert_catch_exec().
#define target_insert_fork_catchpoint (pid) (*current_target.to_insert_fork_catchpoint) (pid)
Definition at line 1219 of file target.h.
Referenced by insert_catch_fork().
#define target_insert_hw_breakpoint (gdbarch, bp_tgt) (*current_target.to_insert_hw_breakpoint) (gdbarch, bp_tgt)
Definition at line 1550 of file target.h.
Referenced by bkpt_insert_location().
#define target_insert_vfork_catchpoint (pid) (*current_target.to_insert_vfork_catchpoint) (pid)
Definition at line 1225 of file target.h.
Referenced by insert_catch_vfork().
#define target_insert_watchpoint (addr, len, type, cond) (*current_target.to_insert_watchpoint) (addr, len, type, cond)
Definition at line 1530 of file target.h.
Referenced by insert_watchpoint().
#define target_is_async_p () (current_target.to_is_async_p ())
Definition at line 1411 of file target.h.
Referenced by linux_child_follow_fork(), linux_nat_terminal_inferior(), linux_nat_terminal_ours(), mi_on_resume(), and remote_wait_as().
#define target_log_command (p)
Value:
do                                                                      \
    if (current_target.to_log_command)                                  \
      (*current_target.to_log_command) (p);                             \
  while (0)
Definition at line 1763 of file target.h.
Referenced by execute_command(), and mi_execute_command().
#define target_longname (current_target.to_longname)
Definition at line 909 of file target.h.
Referenced by kill_command().
#define target_make_corefile_notes (BFD, SIZE_P) (current_target.to_make_corefile_notes) (BFD, SIZE_P)
Definition at line 1476 of file target.h.
Referenced by linux_make_corefile_notes_1(), and write_gcore_file().
#define target_pid_to_exec_file (pid) (current_target.to_pid_to_exec_file) (pid)
Definition at line 1454 of file target.h.
Referenced by attach_command_post_wait().
#define target_post_attach (pid) (*current_target.to_post_attach) (pid)
Definition at line 942 of file target.h.
Referenced by attach_command_post_wait(), lin_lwp_attach_lwp(), and linux_handle_extended_wait().
#define target_post_startup_inferior (ptid) (*current_target.to_post_startup_inferior) (ptid)
Definition at line 1211 of file target.h.
Referenced by inf_ptrace_create_inferior().
#define target_prepare_to_store (regcache) (*current_target.to_prepare_to_store) (regcache)
Definition at line 1000 of file target.h.
Referenced by regcache_raw_write().
#define target_rcmd (command, outbuf) (*current_target.to_rcmd) (command, outbuf)
Definition at line 1344 of file target.h.
Referenced by do_monitor_command().
#define target_region_ok_for_hw_watchpoint (addr, len) (*current_target.to_region_ok_for_hw_watchpoint) (addr, len)
Definition at line 1520 of file target.h.
Referenced by can_use_hardware_watchpoint(), and resources_needed_watchpoint().
#define target_remove_exec_catchpoint (pid) (*current_target.to_remove_exec_catchpoint) (pid)
Definition at line 1249 of file target.h.
Referenced by remove_catch_exec().
#define target_remove_fork_catchpoint (pid) (*current_target.to_remove_fork_catchpoint) (pid)
Definition at line 1222 of file target.h.
Referenced by remove_catch_fork().
#define target_remove_hw_breakpoint (gdbarch, bp_tgt) (*current_target.to_remove_hw_breakpoint) (gdbarch, bp_tgt)
Definition at line 1553 of file target.h.
Referenced by bkpt_remove_location(), and remove_breakpoint_1().
#define target_remove_vfork_catchpoint (pid) (*current_target.to_remove_vfork_catchpoint) (pid)
Definition at line 1228 of file target.h.
Referenced by remove_catch_vfork().
#define target_remove_watchpoint (addr, len, type, cond) (*current_target.to_remove_watchpoint) (addr, len, type, cond)
Definition at line 1533 of file target.h.
Referenced by remove_watchpoint().
#define target_save_trace_data (filename) (*current_target.to_save_trace_data) (filename)
Definition at line 1710 of file target.h.
Referenced by tfile_target_save().
#define target_set_circular_trace_buffer (val) (*current_target.to_set_circular_trace_buffer) (val)
Definition at line 1728 of file target.h.
Referenced by set_circular_trace_buffer(), and start_tracing().
#define target_set_disconnected_tracing (val) (*current_target.to_set_disconnected_tracing) (val)
Definition at line 1725 of file target.h.
Referenced by set_disconnected_tracing(), and start_tracing().
#define target_set_permissions () (*current_target.to_set_permissions) ()
Definition at line 1740 of file target.h.
#define target_set_syscall_catchpoint (pid, needed, any_count, table_size, table)
Value:
(*current_target.to_set_syscall_catchpoint) (pid, needed, any_count, \
                                                  table_size, table)
Definition at line 1272 of file target.h.
Referenced by insert_catch_syscall(), and remove_catch_syscall().
#define target_set_trace_buffer_size (val) (*current_target.to_set_trace_buffer_size) (val)
Definition at line 1731 of file target.h.
Referenced by set_trace_buffer_size(), and start_tracing().
#define target_set_trace_notes (user, notes, stopnotes) (*current_target.to_set_trace_notes) ((user), (notes), (stopnotes))
Definition at line 1734 of file target.h.
Referenced by set_trace_notes(), set_trace_stop_notes(), set_trace_user(), start_tracing(), and stop_tracing().
#define target_shortname (current_target.to_shortname)
Definition at line 908 of file target.h.
Referenced by bfin_breakpoint_from_pc(), exec_reverse_continue(), exec_reverse_once(), gdbsim_detach(), gdbsim_files_info(), m32r_detach(), m32r_open(), mips_breakpoint_from_pc(), mips_can_use_watchpoint(), monitor_detach(), set_schedlock_func(), sh_breakpoint_from_pc(), and tui_make_status_line().
#define target_static_tracepoint_marker_at (addr, marker) (*current_target.to_static_tracepoint_marker_at) (addr, marker)
Definition at line 1743 of file target.h.
Referenced by init_breakpoint_sal(), remote_download_tracepoint(), and update_static_tracepoint().
#define target_static_tracepoint_markers_by_strid (marker_id) (*current_target.to_static_tracepoint_markers_by_strid) (marker_id)
Definition at line 1746 of file target.h.
Referenced by decode_static_tracepoint_spec(), info_static_tracepoint_markers_command(), and update_static_tracepoint().
#define target_stopped_by_watchpoint (*current_target.to_stopped_by_watchpoint)
Definition at line 1491 of file target.h.
Referenced by handle_inferior_event(), record_full_wait_1(), and watchpoints_triggered().
#define target_stopped_data_address (target, addr_p) (*target.to_stopped_data_address) (target, addr_p)
Definition at line 1564 of file target.h.
Referenced by handle_inferior_event(), and watchpoints_triggered().
#define target_supports_enable_disable_tracepoint () (*current_target.to_supports_enable_disable_tracepoint) ()
Definition at line 1027 of file target.h.
Referenced by disable_breakpoint(), disable_command(), enable_breakpoint_disp(), enable_command(), and start_tracing().
#define target_supports_evaluation_of_breakpoint_conditions () (*current_target.to_supports_evaluation_of_breakpoint_conditions) ()
Definition at line 1036 of file target.h.
Referenced by bp_condition_evaluator(), bp_location_condition_evaluator(), build_target_condition_list(), force_breakpoint_reinsertion(), mark_breakpoint_location_modified(), mark_breakpoint_modified(), set_condition_evaluation_mode(), and translate_condition_evaluation_mode().
#define target_supports_multi_process () (*current_target.to_supports_multi_process) ()
Definition at line 1017 of file target.h.
Referenced by startup_inferior(), and user_visible_resume_ptid().
#define target_supports_string_tracing () (*current_target.to_supports_string_tracing) ()
Definition at line 1030 of file target.h.
Referenced by decode_agent_options().
#define target_terminal_info (arg, from_tty) (*current_target.to_terminal_info) (arg, from_tty)
Definition at line 1172 of file target.h.
Referenced by term_info().
#define target_terminal_init () (*current_target.to_terminal_init) ()
Definition at line 1135 of file target.h.
Referenced by attach_command(), gnu_attach(), m32r_create_inferior(), procfs_create_inferior(), and startup_inferior().
#define target_terminal_ours () (*current_target.to_terminal_ours) ()
Definition at line 1158 of file target.h.
Referenced by ada_lookup_struct_elt_type(), annotate_breakpoints_invalid(), annotate_frames_invalid(), async_enable_stdin(), ATTRIBUTE_PRINTF(), get_windows_debug_event(), handle_inferior_event(), handle_vfork_child_exec_or_exit(), i386_process_record(), i386_record_lea_modrm(), inf_validate_task_sc(), interrupt_query(), linux_child_follow_fork(), linux_nat_attach(), mi_breakpoint_created(), mi_breakpoint_deleted(), mi_breakpoint_modified(), mi_command_param_changed(), mi_execute_command(), mi_inferior_added(), mi_inferior_appeared(), mi_inferior_exit(), mi_inferior_removed(), mi_memory_changed(), mi_solib_loaded(), mi_solib_unloaded(), mi_thread_exit(), mi_traceframe_changed(), mi_tsv_created(), mi_tsv_deleted(), mi_tsv_modified(), mips_error(), mips_kill(), monitor_interrupt_query(), normal_stop(), post_create_inferior(), print_any_exception(), print_flush(), record_full_check_insn_num(), record_full_wait_1(), record_linux_system_call(), report_initial_inferior(), startup_inferior(), step_once(), tui_about_to_proceed(), vwarning(), windows_attach(), and windows_wait().
#define target_terminal_ours_for_output () (*current_target.to_terminal_ours_for_output) ()
Definition at line 1151 of file target.h.
Referenced by disable_breakpoints_in_unloaded_shlib(), handle_inferior_event(), handle_jit_event(), handle_solib_event(), insert_breakpoint_locations(), normal_stop(), remote_wait_as(), and update_inserted_breakpoint_locations().
#define target_terminal_save_ours () (*current_target.to_terminal_save_ours) ()
Definition at line 1166 of file target.h.
Referenced by tui_disable(), and tui_enable().
#define target_thread_architecture (ptid) (current_target.to_thread_architecture (&current_target, ptid))
Definition at line 1459 of file target.h.
Referenced by amd64_linux_enable_btrace(), get_thread_regcache(), i386_linux_enable_btrace(), linux_handle_syscall_trap(), record_full_resume(), and record_full_wait_1().
#define target_trace_find (type, num, addr1, addr2, tpp) (*current_target.to_trace_find) ((type), (num), (addr1), (addr2), (tpp))
Definition at line 1704 of file target.h.
Referenced by set_current_traceframe(), set_remote_traceframe(), and tfind_1().
#define target_trace_init () (*current_target.to_trace_init) ()
Definition at line 1671 of file target.h.
Referenced by start_tracing().
#define target_trace_set_readonly_regions () (*current_target.to_trace_set_readonly_regions) ()
Definition at line 1692 of file target.h.
Referenced by start_tracing().
#define target_trace_start () (*current_target.to_trace_start) ()
Definition at line 1689 of file target.h.
Referenced by start_tracing().
#define target_trace_stop () (*current_target.to_trace_stop) ()
Definition at line 1701 of file target.h.
Referenced by stop_tracing().
#define target_traceframe_info () (*current_target.to_traceframe_info) ()
Definition at line 1749 of file target.h.
Referenced by get_traceframe_info().
#define target_upload_trace_state_variables (utsvp) (*current_target.to_upload_trace_state_variables) (utsvp)
Definition at line 1716 of file target.h.
Referenced by trace_save().
#define target_upload_tracepoints (utpp) (*current_target.to_upload_tracepoints) (utpp)
Definition at line 1713 of file target.h.
Referenced by trace_save().
#define target_use_agent (use) (*current_target.to_use_agent) (use)
Definition at line 1752 of file target.h.
Referenced by set_can_use_agent().
#define target_watchpoint_addr_within_range (target, addr, start, length) (*target.to_watchpoint_addr_within_range) (target, addr, start, length)
Definition at line 1569 of file target.h.
Referenced by watchpoints_triggered().
Typedef Documentation
typedef struct memory_read_result memory_read_result_s
Definition at line 263 of file target.h.
typedef struct memory_write_request memory_write_request_s
Definition at line 1084 of file target.h.
typedef struct static_tracepoint_marker* static_tracepoint_marker_p
Definition at line 234 of file target.h.
Enumeration Type Documentation
enum flash_preserve_mode
Enumerator:
flash_preserve
flash_discard
Definition at line 1088 of file target.h.
enum inferior_event_type
Enumerator:
INF_REG_EVENT
INF_TIMER
INF_EXEC_COMPLETE
INF_EXEC_CONTINUE
Definition at line 112 of file target.h.
enum strata
Enumerator:
dummy_stratum
file_stratum
process_stratum
thread_stratum
record_stratum
arch_stratum
Definition at line 71 of file target.h.
enum target_object
Enumerator:
TARGET_OBJECT_AVR
TARGET_OBJECT_SPU
TARGET_OBJECT_MEMORY
TARGET_OBJECT_RAW_MEMORY
TARGET_OBJECT_STACK_MEMORY
TARGET_OBJECT_UNWIND_TABLE
TARGET_OBJECT_AUXV
TARGET_OBJECT_WCOOKIE
TARGET_OBJECT_MEMORY_MAP
TARGET_OBJECT_FLASH
TARGET_OBJECT_AVAILABLE_FEATURES
TARGET_OBJECT_LIBRARIES
TARGET_OBJECT_LIBRARIES_SVR4
TARGET_OBJECT_LIBRARIES_AIX
TARGET_OBJECT_OSDATA
TARGET_OBJECT_SIGNAL_INFO
TARGET_OBJECT_THREADS
TARGET_OBJECT_STATIC_TRACE_DATA
TARGET_OBJECT_HPUX_UREGS
TARGET_OBJECT_HPUX_SOLIB_GOT
TARGET_OBJECT_TRACEFRAME_INFO
TARGET_OBJECT_FDPIC
TARGET_OBJECT_DARWIN_DYLD_INFO
TARGET_OBJECT_OPENVMS_UIB
TARGET_OBJECT_BTRACE
Definition at line 131 of file target.h.
enum target_xfer_error
Enumerator:
TARGET_XFER_E_IO
TARGET_XFER_E_UNAVAILABLE
Definition at line 204 of file target.h.
enum thread_control_capabilities
Enumerator:
tc_none
tc_schedlock
Definition at line 81 of file target.h.
enum trace_find_type
Enumerator:
tfind_number
tfind_pc
tfind_tp
tfind_range
tfind_outside
Definition at line 225 of file target.h.
Function Documentation
void add_deprecated_target_alias (struct target_ops * t, char * alias)
Definition at line 456 of file target.c.
References add_cmd(), deprecate_cmd(), no_class, target_ops::to_doc, target_ops::to_open, target_ops::to_shortname, and xstrprintf().
Referenced by _initialize_record_full().
void add_target (struct target_ops *)
Definition at line 448 of file target.c.
References add_target_with_completer().
Referenced by _initialize_alpha_nat(), _initialize_alphabsd_nat(), _initialize_amd64_sol2_nat(), _initialize_amd64fbsd_nat(), _initialize_amd64nbsd_nat(), _initialize_amd64obsd_nat(), _initialize_arm_netbsd_nat(), _initialize_darwin_inferior(), _initialize_dbug_rom(), _initialize_dink32_rom(), _initialize_go32_nat(), _initialize_hppa_hpux_nat(), _initialize_hppabsd_nat(), _initialize_hppanbsd_nat(), _initialize_i386fbsd_nat(), _initialize_i386gnu_nat(), _initialize_i386nbsd_nat(), _initialize_i386obsd_nat(), _initialize_ia64_hpux_nat(), _initialize_irix5_nat(), _initialize_m32r_rom(), _initialize_m68kbsd_nat(), _initialize_m88kbsd_nat(), _initialize_mips64obsd_nat(), _initialize_mipsnbsd_nat(), _initialize_picobug_rom(), _initialize_ppcbug_rom(), _initialize_ppcfbsd_nat(), _initialize_ppcnbsd_nat(), _initialize_ppcobsd_nat(), _initialize_procfs(), _initialize_record_full(), _initialize_remote_m32r(), _initialize_remote_mips(), _initialize_remote_sim(), _initialize_rs6000_nat(), _initialize_shnbsd_nat(), _initialize_sparc64fbsd_nat(), _initialize_sparc64nbsd_nat(), _initialize_sparc_sol2_nat(), _initialize_sparcnbsd_nat(), _initialize_spu_nat(), _initialize_vax_nat(), _initialize_vaxbsd_nat(), _initialize_windows_nat(), bsd_kvm_add_target(), and linux_nat_add_target().
void add_target_with_completer (struct target_ops * t, completer_ftype * completer)
Definition at line 409 of file target.c.
References _, add_cmd(), add_prefix_cmd(), class_run, cmdlist, complete_target_initialization(), DEFAULT_ALLOCSIZE, no_class, target_command(), target_ops::to_doc, target_ops::to_open, target_ops::to_shortname, xmalloc(), and xrealloc().
Referenced by _initialize_ctf(), _initialize_tracepoint(), and add_target().
void complete_target_initialization (struct target_ops * t)
Definition at line 382 of file target.c.
References default_xfer_partial(), int, return_zero(), target_ops::to_has_all_memory, target_ops::to_has_execution, target_ops::to_has_memory, target_ops::to_has_registers, target_ops::to_has_stack, and target_ops::to_xfer_partial.
Referenced by _initialize_aix_thread(), _initialize_bsd_uthread(), _initialize_dec_thread(), _initialize_sol_thread(), _initialize_spu_multiarch(), add_target_with_completer(), and init_thread_db_ops().
DEF_VEC_O (memory_read_result_s)
DEF_VEC_O (memory_write_request_s)
DEF_VEC_P (static_tracepoint_marker_p)
int default_child_has_all_memory (struct target_ops * ops)
Definition at line 261 of file target.c.
References inferior_ptid, null_ptid, and ptid_equal().
Referenced by _initialize_remote_mips(), inf_child_target(), init_base_monitor_ops(), init_go32_ops(), init_procfs_ops(), init_ravenscar_thread_ops(), init_remote_ops(), and init_windows_ops().
int default_child_has_execution (struct target_ops * ops, ptid_t the_ptid)
Definition at line 301 of file target.c.
References null_ptid, and ptid_equal().
Referenced by _initialize_remote_mips(), inf_child_target(), init_base_monitor_ops(), init_gdbsim_ops(), init_go32_ops(), init_procfs_ops(), init_ravenscar_thread_ops(), init_remote_ops(), and init_windows_ops().
int default_child_has_memory (struct target_ops * ops)
Definition at line 271 of file target.c.
References inferior_ptid, null_ptid, and ptid_equal().
Referenced by _initialize_remote_mips(), inf_child_target(), init_base_monitor_ops(), init_go32_ops(), init_procfs_ops(), init_ravenscar_thread_ops(), init_remote_ops(), and init_windows_ops().
int default_child_has_registers (struct target_ops * ops)
Definition at line 291 of file target.c.
References inferior_ptid, null_ptid, and ptid_equal().
Referenced by _initialize_remote_mips(), inf_child_target(), init_base_monitor_ops(), init_gdbsim_ops(), init_go32_ops(), init_procfs_ops(), init_ravenscar_thread_ops(), init_remote_ops(), and init_windows_ops().
int default_child_has_stack (struct target_ops * ops)
Definition at line 281 of file target.c.
References inferior_ptid, null_ptid, and ptid_equal().
Referenced by _initialize_remote_mips(), inf_child_target(), init_base_monitor_ops(), init_gdbsim_ops(), init_go32_ops(), init_procfs_ops(), init_ravenscar_thread_ops(), init_remote_ops(), and init_windows_ops().
int default_memory_insert_breakpoint (struct gdbarch * , struct bp_target_info *)
Definition at line 40 of file mem-break.c.
References _, error(), gdbarch_breakpoint_from_pc(), memcpy(), bp_target_info::placed_address, bp_target_info::placed_size, bp_target_info::shadow_contents, bp_target_info::shadow_len, target_read_memory(), and target_write_raw_memory().
Referenced by gdbarch_alloc().
int default_memory_remove_breakpoint (struct gdbarch * , struct bp_target_info *)
Definition at line 71 of file mem-break.c.
References bp_target_info::placed_address, bp_target_info::placed_size, bp_target_info::shadow_contents, and target_write_raw_memory().
Referenced by gdbarch_alloc(), and spu_memory_remove_breakpoint().
void find_default_attach (struct target_ops * , char * , int)
Definition at line 3115 of file target.c.
References find_default_run_target(), and target_ops::to_attach.
Referenced by init_core_ops(), init_dummy_target(), and init_exec_ops().
void find_default_create_inferior (struct target_ops * , char * , char * , char ** , int)
Definition at line 3125 of file target.c.
References find_default_run_target(), and target_ops::to_create_inferior.
Referenced by init_core_ops(), init_dummy_target(), init_exec_ops(), init_record_btrace_ops(), and init_record_full_ops().
struct target_ops* find_target_beneath (struct target_ops *) [read]
Definition at line 3643 of file target.c.
References target_ops::beneath.
Referenced by aix_thread_attach(), aix_thread_detach(), aix_thread_fetch_registers(), aix_thread_mourn_inferior(), aix_thread_pid_to_str(), aix_thread_resume(), aix_thread_store_registers(), aix_thread_thread_alive(), aix_thread_wait(), aix_thread_xfer_partial(), bsd_uthread_fetch_registers(), bsd_uthread_mourn_inferior(), bsd_uthread_resume(), bsd_uthread_store_registers(), bsd_uthread_thread_alive(), bsd_uthread_wait(), dec_thread_detach(), dec_thread_fetch_registers(), dec_thread_mourn_inferior(), dec_thread_pid_to_str(), dec_thread_store_registers(), dec_thread_wait(), ppc_linux_spe_context(), ravenscar_fetch_registers(), ravenscar_mourn_inferior(), ravenscar_prepare_to_store(), ravenscar_resume(), ravenscar_store_registers(), ravenscar_wait(), sol_find_new_threads(), sol_thread_alive(), sol_thread_detach(), sol_thread_fetch_registers(), sol_thread_mourn_inferior(), sol_thread_resume(), sol_thread_store_registers(), sol_thread_wait(), sol_thread_xfer_partial(), spu_fetch_registers(), spu_mourn_inferior(), spu_region_ok_for_hw_watchpoint(), spu_search_memory(), spu_store_registers(), spu_xfer_partial(), thread_db_detach(), thread_db_get_thread_local_address(), thread_db_mourn_inferior(), thread_db_pid_to_str(), thread_db_resume(), and thread_db_wait().
void free_memory_read_result_vector (void *)
Definition at line 2204 of file target.c.
References memory_read_result::data, VEC, VEC_free, VEC_iterate, and xfree().
Referenced by mi_cmd_data_read_memory_bytes().
void get_target_memory (struct target_ops * ops, CORE_ADDR addr, gdb_byte * buf, LONGEST len)
Definition at line 2435 of file target.c.
References memory_error(), TARGET_OBJECT_RAW_MEMORY, target_read(), and TARGET_XFER_E_IO.
Referenced by get_target_memory_unsigned().
ULONGEST get_target_memory_unsigned (struct target_ops * ops, CORE_ADDR addr, int len, enum bfd_endian byte_order)
Definition at line 2448 of file target.c.
References extract_unsigned_integer(), gdb_assert, get_target_memory(), and ULONGEST.
Referenced by frv_convert_from_func_ptr_addr().
void initialize_targets (void)
Definition at line 5073 of file target.c.
References _, add_cmd(), add_com(), add_info(), add_setshow_boolean_cmd(), add_setshow_zuinteger_cmd(), class_maintenance, class_obscure, class_support, dcache_init(), do_monitor_command(), init_dummy_target(), maintenance_print_target_stack(), maintenanceprintlist, no_class, push_target(), set_stack_cache_enabled_p(), set_target_async_command(), set_target_permissions(), set_write_memory_permission(), setdebuglist, setlist, show_stack_cache_enabled_p(), show_target_async_command(), show_trust_readonly(), showdebuglist, showlist, and target_info().
Referenced by gdb_init().
struct cleanup* make_show_memory_breakpoints_cleanup (int show) [read]
Definition at line 1701 of file target.c.
References make_cleanup(), and restore_show_memory_breakpoints().
Referenced by bp_loc_is_permanent(), ia64_breakpoint_from_pc(), ia64_memory_insert_breakpoint(), ia64_memory_remove_breakpoint(), and ppc_linux_memory_remove_breakpoint().
int memory_insert_breakpoint (struct gdbarch * , struct bp_target_info *)
Definition at line 80 of file mem-break.c.
References gdbarch_memory_insert_breakpoint().
Referenced by inf_child_target(), init_gdbsim_ops(), init_go32_ops(), init_windows_ops(), remote_insert_breakpoint(), set_gdbarch_memory_insert_breakpoint(), and update_current_target().
int memory_remove_breakpoint (struct gdbarch * , struct bp_target_info *)
Definition at line 87 of file mem-break.c.
References gdbarch_memory_remove_breakpoint().
Referenced by inf_child_target(), init_gdbsim_ops(), init_go32_ops(), init_windows_ops(), remote_remove_breakpoint(), set_gdbarch_memory_remove_breakpoint(), and update_current_target().
void noprocess (void)
Definition at line 554 of file target.c.
References _, and error().
Referenced by call_function_by_hand(), gcore_command(), restore_command(), target_kill(), target_resume(), target_store_registers(), target_wait(), and update_current_target().
char* normal_pid_to_str (ptid_t ptid)
Definition at line 3688 of file target.c.
References ptid_get_pid(), and xsnprintf().
Referenced by bsd_uthread_pid_to_str(), core_pid_to_str(), darwin_pid_to_str(), dummy_pid_to_str(), gdbsim_pid_to_str(), go32_pid_to_str(), i386_windows_core_pid_to_str(), inf_ptrace_pid_to_str(), linux_core_pid_to_str(), linux_nat_pid_to_str(), m32r_pid_to_str(), monitor_pid_to_str(), remote_pid_to_str(), sol2_core_pid_to_str(), target_pid_to_str(), thread_db_pid_to_str(), and windows_pid_to_str().
void pop_all_targets (void)
Definition at line 1108 of file target.c.
References dummy_stratum, and pop_all_targets_above().
Referenced by quit_force().
void pop_all_targets_above (enum strata above_stratum)
Definition at line 1091 of file target.c.
References _, current_target, fprintf_unfiltered(), gdb_stderr, internal_error(), target_ops::to_shortname, target_ops::to_stratum, and unpush_target().
Referenced by pop_all_targets(), remote_unpush_target(), and target_preopen().
void push_target (struct target_ops *)
Definition at line 1005 of file target.c.
References _, target_ops::beneath, fprintf_unfiltered(), gdb_stderr, internal_error(), OPS_MAGIC, target_close(), target_ops::to_magic, target_ops::to_shortname, target_ops::to_stratum, and update_current_target().
Referenced by add_target_sections(), bsd_kvm_open(), bsd_uthread_activate(), check_for_thread_db(), core_open(), darwin_attach_pid(), do_initial_windows_stuff(), enable_dec_thread(), gdbsim_open(), gnu_attach(), gnu_create_inferior(), go32_create_inferior(), inf_ptrace_attach(), inf_ptrace_create_inferior(), initialize_targets(), m32r_open(), monitor_open(), pd_enable(), procfs_attach(), procfs_create_inferior(), procfs_init_inferior(), ravenscar_inferior_created(), record_btrace_open(), record_full_core_open_1(), record_full_open_1(), remote_open_1(), spu_multiarch_activate(), tfile_open(), and try_thread_db_load_1().
int simple_search_memory (struct target_ops * ops, CORE_ADDR start_addr, ULONGEST search_space_len, const gdb_byte * pattern, ULONGEST pattern_len, CORE_ADDR * found_addrp)
Definition at line 2892 of file target.c.
References _, do_cleanups(), error(), free_current_contents(), gdb_assert, hex_string(), make_cleanup(), malloc(), memcpy(), min, plongest(), pulongest(), SEARCH_CHUNK_SIZE, TARGET_OBJECT_MEMORY, target_read(), and warning().
Referenced by remote_search_memory(), spu_search_memory(), and target_search_memory().
void target_attach (char * , int)
Definition at line 3793 of file target.c.
References _, target_ops::beneath, current_target, fprintf_unfiltered(), gdb_stdlog, internal_error(), and target_ops::to_attach.
Referenced by attach_command().
void target_call_history (int size, int flags)
Definition at line 4404 of file target.c.
References target_ops::beneath, current_target, tcomplain(), and target_ops::to_call_history.
Referenced by cmd_record_call_history().
void target_call_history_from (ULONGEST begin, int size, int flags)
Definition at line 4421 of file target.c.
References target_ops::beneath, current_target, tcomplain(), and target_ops::to_call_history_from.
Referenced by cmd_record_call_history().
void target_call_history_range (ULONGEST begin, ULONGEST end, int flags)
Definition at line 4438 of file target.c.
References target_ops::beneath, current_target, tcomplain(), and target_ops::to_call_history_range.
Referenced by cmd_record_call_history().
void target_close (struct target_ops * targ)
Definition at line 3779 of file target.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, target_is_pushed(), target_ops::to_close, and target_ops::to_xclose.
Referenced by enable_break(), push_target(), and unpush_target().
int target_core_of_thread (ptid_t ptid)
Definition at line 4001 of file target.c.
References target_ops::beneath, current_target, fprintf_unfiltered(), gdb_stdlog, ptid_get_pid(), and target_ops::to_core_of_thread.
Referenced by collect_cores(), mi_on_normal_stop(), and print_thread_info().
void target_create_inferior (char * exec_file, char * args, char ** env, int from_tty)
Definition at line 501 of file target.c.
References _, target_ops::beneath, current_target, fprintf_unfiltered(), gdb_stdlog, internal_error(), and target_ops::to_create_inferior.
Referenced by run_command_1().
void target_dcache_invalidate (void)
Definition at line 244 of file target.c.
References dcache_invalidate().
Referenced by mem_delete_command(), mem_disable_command(), mem_enable_command(), prepare_execute_command(), set_stack_cache_enabled_p(), target_load(), target_resume(), and tfind_1().
void target_delete_record (void)
Definition at line 4271 of file target.c.
References target_ops::beneath, current_target, tcomplain(), and target_ops::to_delete_record.
Referenced by cmd_record_delete().
void target_detach (char * , int)
Definition at line 2608 of file target.c.
References _, target_ops::beneath, current_target, fprintf_unfiltered(), gdb_stdlog, gdbarch_has_global_breakpoints(), inferior_ptid, internal_error(), prepare_for_detach(), ptid_get_pid(), remove_breakpoints_pid(), target_gdbarch(), and target_ops::to_detach.
Referenced by detach_command(), dispose_inferior(), gdb_clear_file(), handle_vfork_child_exec_or_exit(), kill_or_detach(), linux_child_follow_fork(), and record_detach().
void target_disable_btrace (struct btrace_target_info * btinfo)
Definition at line 4162 of file target.c.
References target_ops::beneath, current_target, tcomplain(), and target_ops::to_disable_btrace.
Referenced by btrace_disable().
void target_disconnect (char * , int)
Definition at line 2639 of file target.c.
References target_ops::beneath, current_target, fprintf_unfiltered(), gdb_stdlog, remove_breakpoints(), tcomplain(), and target_ops::to_disconnect.
Referenced by disconnect_command(), and record_disconnect().
struct btrace_target_info* target_enable_btrace (ptid_t ptid) [read]
Definition at line 4147 of file target.c.
References target_ops::beneath, current_target, tcomplain(), and target_ops::to_enable_btrace.
Referenced by btrace_enable().
void target_fetch_registers (struct regcache * regcache, int regno)
Definition at line 3960 of file target.c.
References target_ops::beneath, current_target, debug_print_register(), and target_ops::to_fetch_registers.
Referenced by bsd_kvm_open(), bsd_kvm_pcb_cmd(), bsd_kvm_proc_cmd(), core_open(), linux_corefile_thread_callback(), ps_lgetfpregs(), ps_lgetregs(), record_full_core_open_1(), and regcache_raw_read().
int target_fileio_close (int fd, int * target_errno)
Definition at line 3405 of file target.c.
References target_ops::beneath, default_fileio_target(), fprintf_unfiltered(), gdb_stdlog, and target_ops::to_fileio_close.
Referenced by target_fileio_close_cleanup().
int target_fileio_open (const char * filename, int flags, int mode, int * target_errno)
Definition at line 3318 of file target.c.
References target_ops::beneath, default_fileio_target(), fprintf_unfiltered(), gdb_stdlog, and target_ops::to_fileio_open.
Referenced by target_fileio_read_alloc_1().
int target_fileio_pread (int fd, gdb_byte * read_buf, int len, ULONGEST offset, int * target_errno)
Definition at line 3376 of file target.c.
References target_ops::beneath, default_fileio_target(), fprintf_unfiltered(), gdb_stdlog, pulongest(), and target_ops::to_fileio_pread.
Referenced by target_fileio_read_alloc_1().
int target_fileio_pwrite (int fd, const gdb_byte * write_buf, int len, ULONGEST offset, int * target_errno)
Definition at line 3346 of file target.c.
References target_ops::beneath, default_fileio_target(), fprintf_unfiltered(), gdb_stdlog, pulongest(), and target_ops::to_fileio_pwrite.
LONGEST target_fileio_read_alloc (const char * filename, gdb_byte ** buf_p)
Definition at line 3557 of file target.c.
References target_fileio_read_alloc_1().
char* target_fileio_read_stralloc (const char * filename)
Definition at line 3569 of file target.c.
References _, LONGEST, target_fileio_read_alloc_1(), and warning().
Referenced by linux_fill_prpsinfo(), linux_find_memory_regions_full(), and linux_info_proc().
char* target_fileio_readlink (const char * filename, int * target_errno)
Definition at line 3456 of file target.c.
References target_ops::beneath, default_fileio_target(), fprintf_unfiltered(), gdb_stdlog, and target_ops::to_fileio_readlink.
Referenced by linux_info_proc().
int target_fileio_unlink (const char * filename, int * target_errno)
Definition at line 3430 of file target.c.
References target_ops::beneath, default_fileio_target(), fprintf_unfiltered(), gdb_stdlog, and target_ops::to_fileio_unlink.
void target_find_new_threads (void)
Definition at line 3837 of file target.c.
References target_ops::beneath, current_target, fprintf_unfiltered(), gdb_stdlog, and target_ops::to_find_new_threads.
Referenced by check_for_thread_db(), core_open(), print_ada_task_info(), task_command_1(), and update_thread_list().
void target_flash_done (void)
Definition at line 1936 of file target.c.
References target_ops::beneath, current_target, fprintf_unfiltered(), gdb_stdlog, tcomplain(), and target_ops::to_flash_done.
Referenced by target_write_memory_blocks().
void target_flash_erase (ULONGEST address, LONGEST length)
Definition at line 1918 of file target.c.
References target_ops::beneath, current_target, fprintf_unfiltered(), gdb_stdlog, hex_string(), phex(), tcomplain(), and target_ops::to_flash_erase.
Referenced by target_write_memory_blocks().
int target_follow_fork (int follow_child, int detach_fork)
Definition at line 2816 of file target.c.
References _, target_ops::beneath, current_target, fprintf_unfiltered(), gdb_stdlog, internal_error(), and target_ops::to_follow_fork.
Referenced by follow_fork().
char* target_get_osdata (const char * type)
Definition at line 3245 of file target.c.
References target_ops::beneath, current_target, find_default_run_target(), process_stratum, TARGET_OBJECT_OSDATA, target_read_stralloc(), and target_ops::to_stratum.
Referenced by get_osdata().
struct target_section_table* target_get_section_table (struct target_ops * target) [read]
Definition at line 1327 of file target.c.
References target_ops::beneath, fprintf_unfiltered(), gdb_stdlog, and target_ops::to_get_section_table.
Referenced by exec_xfer_partial(), memory_xfer_live_readonly_partial(), memory_xfer_partial_1(), read_value_memory(), and target_section_by_addr().
void target_goto_record (ULONGEST insn)
Definition at line 4336 of file target.c.
References target_ops::beneath, current_target, tcomplain(), and target_ops::to_goto_record.
Referenced by cmd_record_goto().
void target_goto_record_begin (void)
Definition at line 4302 of file target.c.
References target_ops::beneath, current_target, tcomplain(), and target_ops::to_goto_record_begin.
Referenced by cmd_record_goto_begin().
void target_goto_record_end (void)
Definition at line 4319 of file target.c.
References target_ops::beneath, current_target, tcomplain(), and target_ops::to_goto_record_end.
Referenced by cmd_record_goto_end().
int target_has_all_memory_1 (void)
Definition at line 313 of file target.c.
References target_ops::beneath, current_target, and target_ops::to_has_all_memory.
int target_has_execution_1 (ptid_t)
Definition at line 361 of file target.c.
References target_ops::beneath, current_target, and target_ops::to_has_execution.
Referenced by have_live_inferiors(), and target_has_execution_current().
int target_has_execution_current (void)
Definition at line 373 of file target.c.
References inferior_ptid, and target_has_execution_1().
int target_has_memory_1 (void)
Definition at line 325 of file target.c.
References target_ops::beneath, current_target, and target_ops::to_has_memory.
int target_has_registers_1 (void)
Definition at line 349 of file target.c.
References target_ops::beneath, current_target, and target_ops::to_has_registers.
int target_has_stack_1 (void)
Definition at line 337 of file target.c.
References target_ops::beneath, current_target, and target_ops::to_has_stack.
void target_ignore (void)
Definition at line 471 of file target.c.
Referenced by gdb_stop(), init_dummy_target(), and update_current_target().
int target_info_proc (char * , enum info_proc_what)
Definition at line 3192 of file target.c.
References target_ops::beneath, current_target, find_default_run_target(), fprintf_unfiltered(), gdb_stdlog, process_stratum, target_ops::to_info_proc, and target_ops::to_stratum.
Referenced by info_proc_cmd_1().
void target_info_record (void)
Definition at line 4223 of file target.c.
References target_ops::beneath, current_target, tcomplain(), and target_ops::to_info_record.
int target_insert_breakpoint (struct gdbarch * gdbarch, struct bp_target_info * bp_tgt)
Definition at line 2459 of file target.c.
References _, current_target, target_ops::to_insert_breakpoint, and warning().
Referenced by bkpt_insert_location(), deprecated_insert_raw_breakpoint(), and insert_bp_location().
int target_insert_mask_watchpoint (CORE_ADDR , CORE_ADDR , int)
Definition at line 4050 of file target.c.
References target_ops::beneath, core_addr_to_string(), current_target, fprintf_unfiltered(), gdb_stdlog, and target_ops::to_insert_mask_watchpoint.
Referenced by insert_masked_watchpoint().
void target_insn_history (int size, int flags)
Definition at line 4353 of file target.c.
References target_ops::beneath, current_target, tcomplain(), and target_ops::to_insn_history.
Referenced by cmd_record_insn_history().
void target_insn_history_from (ULONGEST from, int size, int flags)
Definition at line 4370 of file target.c.
References target_ops::beneath, current_target, tcomplain(), and target_ops::to_insn_history_from.
Referenced by cmd_record_insn_history().
void target_insn_history_range (ULONGEST begin, ULONGEST end, int flags)
Definition at line 4387 of file target.c.
References target_ops::beneath, current_target, tcomplain(), and target_ops::to_insn_history_range.
Referenced by cmd_record_insn_history().
int target_is_pushed (struct target_ops * t)
Definition at line 1116 of file target.c.
References _, target_ops::beneath, fprintf_unfiltered(), gdb_stderr, internal_error(), OPS_MAGIC, target_ops::to_magic, and target_ops::to_shortname.
Referenced by inf_ptrace_attach(), inf_ptrace_create_inferior(), and target_close().
void target_kill (void)
Definition at line 476 of file target.c.
References target_ops::beneath, current_target, fprintf_unfiltered(), gdb_stdlog, noprocess(), and target_ops::to_kill.
Referenced by attach_command(), dispose_inferior(), gdb_clear_file(), kill_command(), kill_if_already_running(), kill_inferior_command(), kill_or_detach(), and record_kill().
void target_load (char * arg, int from_tty)
Definition at line 494 of file target.c.
References current_target, target_dcache_invalidate(), and target_ops::to_load.
Referenced by load_command().
int target_masked_watch_num_registers (CORE_ADDR addr, CORE_ADDR mask)
Definition at line 4104 of file target.c.
References target_ops::beneath, current_target, and target_ops::to_masked_watch_num_registers.
Referenced by resources_needed_masked_watchpoint(), and watch_command_1().
void target_mourn_inferior (void)
Definition at line 2840 of file target.c.
References _, target_ops::beneath, current_target, fprintf_unfiltered(), gdb_stdlog, internal_error(), and target_ops::to_mourn_inferior.
Referenced by darwin_kill_inferior(), extended_remote_kill(), gdbsim_kill(), get_windows_debug_event(), gnu_kill_inferior(), handle_inferior_event(), inf_ptrace_kill(), interrupt_query(), linux_nat_attach(), linux_nat_kill(), mips_error(), mips_kill(), mips_readchar(), monitor_interrupt_query(), procfs_kill_inferior(), readchar(), record_mourn_inferior(), remote_detach_1(), remote_kill(), startup_inferior(), and windows_kill_inferior().
char* target_options_to_string (int target_options)
Definition at line 3905 of file target.c.
References DO_TARG_OPTION, str_comma_list_concat_elem(), and TARGET_WNOHANG.
Referenced by linux_nat_wait(), and target_wait().
void target_pass_signals (int nsig, unsigned char * pass_signals)
Definition at line 2753 of file target.c.
References target_ops::beneath, current_target, fprintf_unfiltered(), gdb_signal_to_name(), gdb_stdlog, and target_ops::to_pass_signals.
Referenced by handle_command(), handle_inferior_event(), record_full_resume(), resume(), and signal_catch_update().
char* target_pid_to_str (ptid_t ptid)
Definition at line 2696 of file target.c.
References target_ops::beneath, current_target, normal_pid_to_str(), and target_ops::to_pid_to_str.
Referenced by add_thread_with_info(), amd64_linux_enable_btrace(), attach_thread(), btrace_clear(), btrace_disable(), btrace_enable(), btrace_fetch(), btrace_teardown(), cancel_breakpoint(), clear_proceed_status_thread(), context_switch(), darwin_attach(), darwin_detach(), dcache_info(), debug_to_stop(), debug_to_thread_architecture(), delete_checkpoint_command(), detach_callback(), detach_checkpoint_command(), displaced_step_fixup(), displaced_step_prepare(), displaced_step_restore(), display_one_tib(), do_captured_thread_select(), exit_lwp(), extended_remote_attach_1(), follow_exec(), get_pending_status(), gnu_fetch_registers(), gnu_resume(), gnu_store_registers(), gnu_wait(), handle_inferior_event(), i386_linux_enable_btrace(), inf_ptrace_attach(), inf_ptrace_detach(), inf_ptrace_files_info(), inferior_command(), inferior_pid_to_str(), info_checkpoints_command(), kill_callback(), kill_wait_callback(), lin_lwp_attach_lwp(), linux_fork_context(), linux_fork_detach(), linux_fork_mourn_inferior(), linux_nat_detach(), linux_nat_filter_event(), linux_nat_post_attach_wait(), linux_nat_resume(), linux_nat_stop_lwp(), linux_nat_wait(), linux_nat_wait_1(), linux_thread_alive(), maybe_clear_ignore_sigint(), normal_stop(), prepare_to_proceed(), print_exited_reason(), print_inferior_quit_action(), print_program_space(), print_signal_received_reason(), print_target_wait_results(), print_thread_info(), proceed_after_vfork_done(), procfs_attach(), procfs_detach(), procfs_fetch_registers(), procfs_files_info(), procfs_wait(), push_stop_reply(), record_btrace_info(), remote_detach_1(), remote_disable_btrace(), remote_enable_btrace(), remote_notif_remove_queued_reply(), remote_stop_ns(), resume(), resume_lwp(), resume_stopped_resumed_lwps(), select_event_lwp(), stop_callback(), stop_wait_callback(), target_thread_address_space(), target_translate_tls_address(), thread_apply_all_command(), thread_apply_command(), thread_command(), thread_find_command(), tui_make_status_line(), wait_lwp(), windows_attach(), windows_delete_thread(), and windows_files_info().
void target_pre_inferior (int)
Definition at line 2521 of file target.c.
References agent_capability_invalidate(), gdbarch_has_global_solist(), invalidate_target_mem_regions(), no_shared_libraries(), target_clear_description(), and target_gdbarch().
Referenced by attach_command(), run_command_1(), and target_preopen().
void target_preopen (int)
Definition at line 2582 of file target.c.
References _, dispose_inferior(), dont_repeat(), error(), file_stratum, have_inferiors(), have_live_inferiors(), iterate_over_inferiors(), pop_all_targets_above(), query(), and target_pre_inferior().
Referenced by bsd_kvm_open(), core_open(), exec_open(), m32r_open(), monitor_open(), remote_open_1(), and tfile_open().
void target_program_signals (int nsig, unsigned char * program_signals)
Definition at line 2783 of file target.c.
References target_ops::beneath, current_target, fprintf_unfiltered(), gdb_signal_to_name(), gdb_stdlog, and target_ops::to_program_signals.
Referenced by handle_command(), and update_signals_program_target().
int target_ranged_break_num_registers (void)
Definition at line 4119 of file target.c.
References target_ops::beneath, current_target, and target_ops::to_ranged_break_num_registers.
Referenced by break_range_command(), and resources_needed_ranged_breakpoint().
LONGEST target_read (struct target_ops * ops, enum target_object object, const char * annex, gdb_byte * buf, ULONGEST offset, LONGEST len)
Definition at line 2046 of file target.c.
References len, LONGEST, QUIT, and target_read_partial().
Referenced by darwin_solib_read_all_image_info_addr(), dcache_read_line(), display_one_tib(), gdb_update_mem(), get_target_memory(), ia64_hpux_find_global_pointer_from_solib(), ia64_hpux_stopped_in_syscall(), info_spu_dma_command(), info_spu_event_command(), info_spu_mailbox_command(), info_spu_proxydma_command(), info_spu_signal_command(), linux_get_siginfo_data(), mi_cmd_data_read_memory(), ppu2spu_sniffer(), read_whatever_is_readable(), save_infcall_suspend_state(), siginfo_value_read(), simple_search_memory(), sparc_fetch_wcookie(), spu_current_sos(), spu_fetch_registers(), spu_pseudo_register_read(), spu_pseudo_register_read_spu(), target_read_live_memory(), target_read_memory(), target_read_stack(), and VEC().
LONGEST target_read_alloc (struct target_ops * ops, enum target_object object, const char * annex, gdb_byte ** buf_p)
Definition at line 2388 of file target.c.
References target_read_alloc_1().
Referenced by avr_io_reg_read_command(), dsbt_get_initial_loadmaps(), get_auxv_inferior_data(), linux_make_corefile_notes(), linux_spu_make_corefile_notes(), and sdata_make_value().
struct target_desc* target_read_description (struct target_ops *) [read]
Definition at line 2869 of file target.c.
References target_ops::beneath, and target_ops::to_read_description.
Referenced by target_find_description().
int target_read_memory (CORE_ADDR memaddr, gdb_byte * myaddr, ssize_t len)
Definition at line 1802 of file target.c.
References target_ops::beneath, current_target, TARGET_OBJECT_MEMORY, target_read(), and TARGET_XFER_E_IO.
Referenced by aarch64_get_longjmp_target(), aarch64_stub_unwind_sniffer(), agent_capability_check(), agent_get_helper_thread_id(), agent_run_command(), alpha_get_longjmp_target(), alpha_read_insn(), alpha_skip_prologue(), alphanbsd_sigtramp_offset(), amd64_analyze_stack_align(), amd64_get_longjmp_target(), amd64_in_function_epilogue_p(), amd64_skip_main_prologue(), amd64_skip_xmm_prologue(), amd64_windows_find_unwind_info(), amd64_windows_frame_decode_epilogue(), amd64_windows_frame_decode_insns(), amd64_windows_skip_prologue(), amd64_x32_analyze_stack_align(), arm_adjust_breakpoint_address(), arm_breakpoint_from_pc(), arm_get_longjmp_target(), arm_stub_unwind_sniffer(), arm_symbian_skip_trampoline_code(), bp_loc_is_permanent(), bsd_uthread_wait(), call0_analyze_prologue(), call0_ret(), cp_print_value(), darwin_current_sos(), darwin_load_image_infos(), darwin_read_exec_load_addr(), default_memory_insert_breakpoint(), dis_asm_read_memory(), displaced_step_prepare(), do_search_struct_field(), dsbt_current_sos(), elf_gnu_ifunc_resolve_by_got(), elf_locate_base(), enable_break2(), execute_code(), extend_buffer_earlier(), extract_arm_insn(), fetch_instruction(), fetch_loadmap(), fetch_mips_16(), find_canonical_descriptor_in_load_object(), find_extant_func_descr(), frv_adjust_breakpoint_address(), frv_analyze_prologue(), frv_current_sos(), frv_linux_pc_in_sigtramp(), frv_linux_sigcontext_reg_addr(), frv_skip_main_prologue(), gcore_copy_callback(), get_signo(), hppa32_hpux_find_global_pointer(), hppa32_hpux_search_dummy_call_sequence(), hppa64_convert_code_addr_to_fptr(), hppa64_hpux_find_global_pointer(), hppa64_hpux_search_dummy_call_sequence(), hppa_in_function_epilogue_p(), hppa_linux_find_global_pointer(), hppa_match_insns(), hppabsd_find_global_pointer(), i386_analyze_frame_setup(), i386_analyze_register_saves(), i386_analyze_stack_align(), i386_analyze_struct_return(), i386_darwin_sstep_at_sigreturn(), i386_follow_jump(), i386_frame_cache_1(), i386_get_longjmp_target(), i386_in_function_epilogue_p(), i386_in_stack_tramp_p(), i386_linux_resume(), i386_match_pattern(), i386_skip_main_prologue(), i386_skip_noop(), i386_skip_probe(), i386_skip_prologue(), ia64_breakpoint_from_pc(), ia64_convert_from_func_ptr_addr(), ia64_find_global_pointer_from_dynamic_section(), ia64_hpux_read_dynamic_info(), ia64_hpux_read_tgt_mem(), ia64_memory_insert_breakpoint(), ia64_memory_remove_breakpoint(), insns_match_pattern(), jit_read_code_entry(), jit_read_descriptor(), jit_reader_try_read_symtab(), jit_target_read_impl(), ld_so_xfer_auxv(), lm_base(), lm_info_read(), load_progress(), m32c_analyze_prologue(), m32r_memory_insert_breakpoint(), m68hc11_pseudo_register_read(), m68k_get_longjmp_target(), mem_bfd_iovec_pread(), mi_cmd_trace_frame_collected(), microblaze_fetch_instruction(), microblaze_linux_memory_remove_breakpoint(), mips64_linux_get_longjmp_target(), mips_fetch_instruction(), mips_get_mips16_fn_stub_pc(), mips_linux_get_longjmp_target(), mips_skip_pic_trampoline_code(), mips_stub_frame_sniffer(), mipsnbsd_get_longjmp_target(), mn10300_analyze_prologue(), moxie_process_readu(), msp430_get_opcode_byte(), nios2_get_longjmp_target(), nios2_stub_frame_sniffer(), open_map(), parse_spufs_run(), partial_memory_read(), pascal_object_print_value(), pdc_read_data(), ppc_linux_memory_remove_breakpoint(), ppc_linux_spe_context(), ppu2spu_sniffer(), ps_xfer_memory(), read_clbk(), read_map(), read_program_header(), record_linux_msghdr(), record_linux_sockaddr(), record_linux_system_call(), record_read_memory(), remote_fileio_func_open(), remote_fileio_func_rename(), remote_fileio_func_stat(), remote_fileio_func_system(), remote_fileio_func_unlink(), remote_fileio_func_write(), rl78_get_opcode_byte(), rs6000_fetch_instruction(), rs6000_skip_main_prologue(), rw_common(), rx_get_opcode_byte(), s390_in_function_epilogue_p(), s390_readinstruction(), s390_sigtramp_frame_sniffer(), safe_frame_unwind_memory(), scan_dyntag(), score3_adjust_pc_and_fetch_inst(), score7_breakpoint_from_pc(), score7_fetch_inst(), score7_malloc_and_get_memblock(), search_struct_method(), skip_prologue(), skip_prologue_hard_way(), som_solib_create_inferior_hook(), sparc_fetch_instruction(), sparc_supply_rwindow(), spu2ppu_sniffer(), spu_analyze_prologue(), spu_bfd_iovec_pread(), spu_frame_unwind_cache(), spu_get_longjmp_target(), spu_in_function_epilogue_p(), spu_software_single_step(), stap_modify_semaphore(), target_read_memory_bfd(), target_read_string(), target_write_memory_blocks(), thumb2_copy_table_branch(), thumb_in_function_epilogue_p(), tic6x_get_longjmp_target(), tilegx_get_longjmp_target(), val_print_string(), xstormy16_find_jmp_table_entry(), xstormy16_resolve_jmp_table_entry(), and xtensa_scan_prologue().
int target_read_stack (CORE_ADDR memaddr, gdb_byte * myaddr, ssize_t len)
Definition at line 1818 of file target.c.
References target_ops::beneath, current_target, TARGET_OBJECT_STACK_MEMORY, target_read(), and TARGET_XFER_E_IO.
Referenced by read_stack().
char* target_read_stralloc (struct target_ops * ops, enum target_object object, const char * annex)
Definition at line 2401 of file target.c.
References _, LONGEST, target_read_alloc_1(), and warning().
Referenced by fetch_available_features_from_target(), remote_threads_info(), remote_traceframe_info(), solib_target_current_sos(), target_get_osdata(), and VEC().
int target_read_string (CORE_ADDR , char ** , int , int *)
Definition at line 1260 of file target.c.
References gdb_assert, MIN, offset, target_read_memory(), xmalloc(), and xrealloc().
Referenced by ada_main_name(), darwin_current_sos(), dsbt_current_sos(), fetch_sec_names(), frv_current_sos(), handle_output_debug_string(), inferior_has_bug(), irix_current_sos(), irix_open_symbol_file_object(), open_symbol_file_object(), print_subexp_standard(), read_map(), som_current_sos(), som_open_symbol_file_object(), and svr4_read_so_list().
int target_record_is_replaying (void)
Definition at line 4288 of file target.c.
References target_ops::beneath, current_target, and target_ops::to_record_is_replaying.
Referenced by cmd_record_delete().
int target_remove_breakpoint (struct gdbarch * gdbarch, struct bp_target_info * bp_tgt)
Definition at line 2472 of file target.c.
References _, current_target, target_ops::to_remove_breakpoint, and warning().
Referenced by bkpt_remove_location(), deprecated_remove_raw_breakpoint(), detach_single_step_breakpoints(), and remove_breakpoint_1().
int target_remove_mask_watchpoint (CORE_ADDR , CORE_ADDR , int)
Definition at line 4077 of file target.c.
References target_ops::beneath, core_addr_to_string(), current_target, fprintf_unfiltered(), gdb_stdlog, and target_ops::to_remove_mask_watchpoint.
Referenced by remove_masked_watchpoint().
void target_require_runnable (void)
Definition at line 3046 of file target.c.
References _, arch_stratum, target_ops::beneath, error(), internal_error(), thread_stratum, target_ops::to_create_inferior, target_ops::to_shortname, and target_ops::to_stratum.
Referenced by kill_if_already_running().
void target_resume (ptid_t ptid, int step, enum gdb_signal signal)
Definition at line 2724 of file target.c.
References target_ops::beneath, clear_inline_frame_state(), current_target, fprintf_unfiltered(), gdb_signal_to_name(), gdb_stdlog, noprocess(), ptid_get_pid(), registers_changed_ptid(), set_executing(), set_running(), target_dcache_invalidate(), and target_ops::to_resume.
Referenced by agent_run_command(), cleanup_target_stop(), displaced_step_fixup(), handle_inferior_event(), ia64_hpux_wait(), irix_solib_create_inferior_hook(), osf_solib_create_inferior_hook(), procfs_wait(), resume(), spu_skip_standalone_loader(), and startup_inferior().
void target_save_record (const char * filename)
Definition at line 4240 of file target.c.
References target_ops::beneath, current_target, tcomplain(), and target_ops::to_save_record.
Referenced by cmd_record_save().
int target_search_memory (CORE_ADDR start_addr, ULONGEST search_space_len, const gdb_byte * pattern, ULONGEST pattern_len, CORE_ADDR * found_addrp)
Definition at line 3002 of file target.c.
References target_ops::beneath, current_target, fprintf_unfiltered(), gdb_stdlog, hex_string(), simple_search_memory(), and target_ops::to_search_memory.
Referenced by find_command(), and infpy_search_memory().
struct target_section* target_section_by_addr (struct target_ops * target, CORE_ADDR addr) [read]
Definition at line 1344 of file target.c.
References target_section::addr, target_section::endaddr, target_section_table::sections, sections_end, and target_get_section_table().
Referenced by memory_xfer_live_readonly_partial(), memory_xfer_partial_1(), ppc64_convert_from_func_ptr_addr(), and s390_load().
void target_stop (ptid_t ptid)
Definition at line 3855 of file target.c.
References _, current_target, target_ops::to_stop, and warning().
Referenced by agent_run_command(), async_remote_interrupt(), attach_command(), attach_command_post_wait(), gdb_stop(), interrupt_target_1(), interrupt_thread_callback(), monitor_interrupt(), notice_new_inferior(), nto_interrupt(), and VEC().
enum btrace_read_type void target_stop_recording (void)
Definition at line 4206 of file target.c.
References target_ops::beneath, current_target, and target_ops::to_stop_recording.
void target_store_registers (struct regcache * regcache, int regs)
Definition at line 3977 of file target.c.
References _, target_ops::beneath, current_target, debug_print_register(), error(), noprocess(), and target_ops::to_store_registers.
Referenced by ps_lsetfpregs(), ps_lsetregs(), regcache_raw_write(), rs6000_lynx178_push_dummy_call(), and rs6000_push_dummy_call().
int target_supports_btrace (void)
Definition at line 4133 of file target.c.
References target_ops::beneath, current_target, and target_ops::to_supports_btrace.
Referenced by btrace_enable(), and record_btrace_open().
int target_supports_delete_record (void)
Definition at line 4257 of file target.c.
References target_ops::beneath, current_target, and target_ops::to_delete_record.
Referenced by cmd_record_delete().
int target_supports_disable_randomization (void)
Definition at line 3233 of file target.c.
References target_ops::beneath, current_target, and target_ops::to_supports_disable_randomization.
Referenced by set_disable_randomization(), and show_disable_randomization().
int target_supports_non_stop (void)
Definition at line 3178 of file target.c.
References target_ops::beneath, current_target, and target_ops::to_supports_non_stop.
Referenced by attach_command(), and run_command_1().
void target_teardown_btrace (struct btrace_target_info * btinfo)
Definition at line 4176 of file target.c.
References target_ops::beneath, current_target, tcomplain(), and target_ops::to_teardown_btrace.
Referenced by btrace_teardown().
void target_terminal_inferior (void)
Definition at line 524 of file target.c.
References current_target, sync_execution, target_can_async_p, and target_ops::to_terminal_inferior.
Referenced by attach_command_post_wait(), do_initial_windows_stuff(), handle_inferior_event(), handle_jit_event(), handle_solib_event(), i386_process_record(), i386_record_lea_modrm(), inf_validate_task_sc(), interrupt_query(), m32r_create_inferior(), mips_kill(), monitor_interrupt_query(), record_full_check_insn_num(), record_linux_system_call(), remote_wait_as(), resume(), startup_inferior(), and tui_about_to_proceed().
struct address_space* target_thread_address_space (ptid_t) [read]
Definition at line 3266 of file target.c.
References _, address_space_num(), inferior::aspace, target_ops::beneath, current_target, find_inferior_pid(), fprintf_unfiltered(), gdb_assert, gdb_stdlog, arm-linux::inf, internal_error(), ptid_get_pid(), target_pid_to_str(), and target_ops::to_thread_address_space.
Referenced by get_thread_arch_regcache().
int target_thread_alive (ptid_t ptid)
Definition at line 3814 of file target.c.
References target_ops::beneath, current_target, fprintf_unfiltered(), gdb_stdlog, ptid_get_pid(), and target_ops::to_thread_alive.
Referenced by display_tib(), handle_inferior_event(), lwp_to_thread(), rw_common(), sol_thread_xfer_partial(), and thread_alive().
char* target_thread_name (struct thread_info *)
Definition at line 2710 of file target.c.
References target_ops::beneath, current_target, and target_ops::to_thread_name.
Referenced by print_thread_info(), thpy_get_name(), and thread_find_command().
CORE_ADDR target_translate_tls_address (struct objfile * objfile, CORE_ADDR offset)
Definition at line 1141 of file target.c.
References _, target_ops::beneath, current_target, gdb_exception::error, error(), objfile::flags, gdbarch_fetch_tls_load_module_address(), gdbarch_fetch_tls_load_module_address_p(), inferior_ptid, lm_addr(), gdb_exception::message, OBJF_SHARED, objfile_name(), gdb_exception::reason, RETURN_MASK_ALL, target_gdbarch(), target_pid_to_str(), throw_error(), throw_exception(), TLS_GENERIC_ERROR, TLS_LOAD_MODULE_NOT_FOUND_ERROR, TLS_NO_LIBRARY_SUPPORT_ERROR, TLS_NOT_ALLOCATED_YET_ERROR, target_ops::to_get_thread_local_address, and TRY_CATCH.
Referenced by default_read_var_value(), dwarf_expr_tls_address(), and evaluate_subexp_standard().
int target_verify_memory (const gdb_byte * data, CORE_ADDR memaddr, ULONGEST size)
Definition at line 4023 of file target.c.
References target_ops::beneath, current_target, fprintf_unfiltered(), gdb_stdlog, paddress(), pulongest(), target_gdbarch(), tcomplain(), and target_ops::to_verify_memory.
Referenced by compare_sections_command().
ptid_t target_wait (ptid_t ptid, struct target_waitstatus * status, int options)
Definition at line 2662 of file target.c.
References target_ops::beneath, current_target, fprintf_unfiltered(), gdb_stdlog, noprocess(), ptid_get_pid(), target_options_to_string(), target_waitstatus_to_string(), target_ops::to_wait, and xfree().
Referenced by agent_run_command(), fetch_inferior_event(), gdbtk_wait(), prepare_for_detach(), spu_skip_standalone_loader(), startup_inferior(), and wait_for_inferior().
char* target_waitstatus_to_string (const struct target_waitstatus *)
Definition at line 32 of file waitstatus.c.
References gdb_signal_to_name(), target_waitstatus::integer, target_waitstatus::kind, target_waitstatus::sig, TARGET_WAITKIND_EXECD, TARGET_WAITKIND_EXITED, TARGET_WAITKIND_FORKED, TARGET_WAITKIND_IGNORE, TARGET_WAITKIND_LOADED, TARGET_WAITKIND_NO_HISTORY, TARGET_WAITKIND_NO_RESUMED, TARGET_WAITKIND_SIGNALLED, TARGET_WAITKIND_SPURIOUS, TARGET_WAITKIND_STOPPED, TARGET_WAITKIND_SYSCALL_ENTRY, TARGET_WAITKIND_SYSCALL_RETURN, TARGET_WAITKIND_VFORK_DONE, TARGET_WAITKIND_VFORKED, target_waitstatus::value, and xstrprintf().
Referenced by print_target_wait_results(), and target_wait().
LONGEST target_write (struct target_ops * ops, enum target_object object, const char * annex, const gdb_byte * buf, ULONGEST offset, LONGEST len)
Definition at line 2315 of file target.c.
References target_write_with_progress().
Referenced by dcache_xfer_memory(), restore_infcall_suspend_state(), siginfo_value_write(), spu_pseudo_register_write(), spu_pseudo_register_write_spu(), spu_store_registers(), target_write_memory(), and target_write_raw_memory().
int target_write_memory (CORE_ADDR memaddr, const gdb_byte * myaddr, ssize_t len)
Definition at line 1838 of file target.c.
References target_ops::beneath, current_target, TARGET_OBJECT_MEMORY, target_write(), and TARGET_XFER_E_IO.
Referenced by agent_run_command(), append_insns(), gdb_set_mem(), ia64_memory_insert_breakpoint(), ld_so_xfer_auxv(), m32r_memory_insert_breakpoint(), m68hc11_pseudo_register_write(), pdc_write_data(), ps_xfer_memory(), record_full_exec_insn(), remote_fileio_func_fstat(), remote_fileio_func_gettimeofday(), remote_fileio_func_read(), remote_fileio_func_stat(), restore_binary_file(), restore_section_callback(), rw_common(), som_solib_create_inferior_hook(), sparc_collect_rwindow(), spu_push_dummy_call(), stap_modify_semaphore(), write_clbk(), and write_memory().
int target_write_memory_blocks (VEC(memory_write_request_s)* requests, enum flash_preserve_mode preserve_flash_p, void(*)(ULONGEST, void *) progress_cb)
Definition at line 311 of file target-memory.c.
References _, memory_write_request::baton, memory_write_request::begin, target_ops::beneath, cleanup_request_data(), cleanup_write_requests_vector(), compare_block_starting_address(), current_target, memory_write_request::data, do_cleanups(), memory_write_request::end, error(), flash_preserve, gdb_assert, len, LONGEST, make_cleanup(), null_cleanup(), qsort, split_regular_and_flash_blocks(), target_flash_done(), target_flash_erase(), TARGET_OBJECT_FLASH, TARGET_OBJECT_MEMORY, target_read_memory(), target_write_with_progress(), VEC, VEC_address, VEC_copy, VEC_empty, VEC_iterate, VEC_length, VEC_safe_push, and xmalloc().
Referenced by generic_load().
int target_write_raw_memory (CORE_ADDR memaddr, const gdb_byte * myaddr, ssize_t len)
Definition at line 1857 of file target.c.
References target_ops::beneath, current_target, TARGET_OBJECT_RAW_MEMORY, target_write(), and TARGET_XFER_E_IO.
Referenced by default_memory_insert_breakpoint(), default_memory_remove_breakpoint(), ia64_memory_remove_breakpoint(), m32r_memory_remove_breakpoint(), microblaze_linux_memory_remove_breakpoint(), and ppc_linux_memory_remove_breakpoint().
LONGEST target_write_with_progress (struct target_ops * ops, enum target_object object, const char * annex, const gdb_byte * buf, ULONGEST offset, LONGEST len, void(*)(ULONGEST, void *) progress, void * baton)
Definition at line 2280 of file target.c.
References len, LONGEST, QUIT, and target_write_partial().
Referenced by target_write(), and target_write_memory_blocks().
const char* target_xfer_error_to_string (enum target_xfer_error err)
Definition at line 1236 of file target.c.
References CASE, TARGET_XFER_E_IO, and TARGET_XFER_E_UNAVAILABLE.
Referenced by memory_error_message().
LONGEST target_xfer_partial (struct target_ops * ops, enum target_object object, const char * annex, void * readbuf, const void * writebuf, ULONGEST offset, LONGEST len)
Definition at line 1713 of file target.c.
References _, core_addr_to_string_nz(), error(), fprintf_unfiltered(), fputc_unfiltered(), fputs_unfiltered(), gdb_assert, gdb_stdlog, host_address_to_string(), LONGEST, memory_xfer_partial(), plongest(), TARGET_OBJECT_MEMORY, TARGET_OBJECT_RAW_MEMORY, TARGET_OBJECT_STACK_MEMORY, target_ops::to_shortname, and target_ops::to_xfer_partial.
Referenced by read_memory(), target_read_partial(), and target_write_partial().
int unpush_target (struct target_ops *)
Definition at line 1052 of file target.c.
References _, target_ops::beneath, dummy_stratum, internal_error(), target_close(), target_ops::to_stratum, and update_current_target().
Referenced by bsd_kvm_open(), bsd_uthread_deactivate(), core_detach(), core_open(), darwin_mourn_inferior(), disable_dec_thread(), do_unpush_target(), gdbsim_detach(), gdbsim_open(), gnu_detach(), gnu_mourn_inferior(), go32_mourn_inferior(), inf_ptrace_detach(), inf_ptrace_mourn_inferior(), m32r_detach(), monitor_detach(), monitor_mourn_inferior(), monitor_open(), pd_disable(), pop_all_targets_above(), procfs_detach(), procfs_mourn_inferior(), ravenscar_mourn_inferior(), record_full_core_kill(), record_unpush(), remote_mourn_1(), remove_target_sections(), sol_thread_detach(), sol_thread_mourn_inferior(), spu_multiarch_deactivate(), tfile_open(), thread_db_detach(), thread_db_mourn_inferior(), thread_db_wait(), windows_detach(), and windows_mourn_inferior().
void update_target_permissions (void)
Definition at line 5028 of file target.c.
Referenced by set_observer_mode(), and set_target_permissions().
VEC (memory_read_result_s)
VEC (mem_region_s)
Definition at line 53 of file memattr.c.
References _, target_ops::beneath, current_target, fprintf_filtered(), fprintf_unfiltered(), gdb_stdlog, mem_region::hi, mem_region::lo, mem_region_cmp(), mem_region::number, qsort, VEC, VEC_address, VEC_free, VEC_iterate, VEC_length, and warning().
VEC (btrace_block_s)
Variable Documentation
int baud_rate
Definition at line 629 of file serial.c.
Referenced by captured_main(), monitor_files_info(), monitor_open(), and remote_open_1().
struct target_ops current_target
Referenced by aarch64_linux_stopped_by_watchpoint(), add_minsym(), arm_linux_stopped_by_watchpoint(), attach_command_post_wait(), avr_io_reg_read_command(), create_exception_master_breakpoint(), darwin_solib_read_all_image_info_addr(), dcache_read_line(), default_fileio_target(), display_one_tib(), do_monitor_command(), dsbt_get_initial_loadmaps(), elf_gnu_ifunc_resolve_addr(), elf_gnu_ifunc_resolve_by_got(), elf_gnu_ifunc_resolver_return_stop(), enable_break(), enable_thread_event(), evaluate_subexp_standard(), find_function_addr(), find_record_target(), find_solib_trampoline_target(), gdb_entry_point(), gdb_stop(), gdb_update_mem(), gdbtk_start_timer(), gnuv3_skip_trampoline(), handle_inferior_event(), handle_solib_event(), i386_stopped_by_watchpoint(), ia64_hpux_find_global_pointer_from_solib(), ia64_hpux_handle_dld_breakpoint_1(), ia64_hpux_solib_add_after_attach(), ia64_hpux_stopped_in_syscall(), ia64_linux_stopped_by_watchpoint(), info_auxv_command(), info_spu_dma_command(), info_spu_event_command(), info_spu_mailbox_command(), info_spu_proxydma_command(), info_spu_signal_command(), init_entry_point_info(), inside_main_func(), irix_solib_create_inferior_hook(), linux_get_siginfo_data(), linux_is_uclinux(), linux_make_corefile_notes(), linux_spu_make_corefile_notes(), m32r_stopped_by_watchpoint(), mi_cmd_data_read_memory(), mi_cmd_data_read_memory_bytes(), minsym_found(), osf_solib_create_inferior_hook(), pop_all_targets_above(), ppc_linux_displaced_step_location(), ppc_linux_get_hwcap(), ppc_linux_spe_context(), ppc_linux_stopped_by_watchpoint(), ppu2spu_sniffer(), print_function_pointer_address(), procfs_inferior_created(), quit(), read_memory(), read_program_header(), record_full_open(), remote_check_symbols(), remote_threads_info(), remote_traceframe_info(), restore_infcall_suspend_state(), run_command_1(), s390_load(), save_infcall_suspend_state(), save_sigtrap(), sdata_make_value(), setup_target_debug(), siginfo_value_read(), siginfo_value_write(), sol_get_ada_task_ptid(), solib_target_current_sos(), sparc_fetch_wcookie(), spu_current_sos(), spu_enable_break(), spu_pseudo_register_read(), spu_pseudo_register_read_spu(), spu_pseudo_register_write(), spu_pseudo_register_write_spu(), start_remote(), svr4_exec_displacement(), svr4_fetch_objfile_link_map(), target_attach(), target_call_history(), target_call_history_from(), target_call_history_range(), target_core_of_thread(), target_create_inferior(), target_delete_record(), target_detach(), target_disable_btrace(), target_disconnect(), target_enable_btrace(), target_fetch_registers(), target_find_description(), target_find_new_threads(), target_flash_done(), target_flash_erase(), target_follow_fork(), target_get_osdata(), target_goto_record(), target_goto_record_begin(), target_goto_record_end(), target_has_all_memory_1(), target_has_execution_1(), target_has_memory_1(), target_has_registers_1(), target_has_stack_1(), target_info_proc(), target_info_record(), target_insert_breakpoint(), target_insert_mask_watchpoint(), target_insn_history(), target_insn_history_from(), target_insn_history_range(), target_kill(), target_load(), target_masked_watch_num_registers(), target_mourn_inferior(), target_pass_signals(), target_pid_to_str(), target_program_signals(), target_ranged_break_num_registers(), target_read_live_memory(), target_read_memory(), target_read_stack(), target_record_is_replaying(), target_remove_breakpoint(), target_remove_mask_watchpoint(), target_resume(), target_save_record(), target_search_memory(), target_stop(), target_stop_recording(), target_store_registers(), target_supports_btrace(), target_supports_delete_record(), target_supports_disable_randomization(), target_supports_non_stop(), target_teardown_btrace(), target_terminal_inferior(), target_thread_address_space(), target_thread_alive(), target_thread_name(), target_translate_tls_address(), target_verify_memory(), target_wait(), target_write_memory(), target_write_memory_blocks(), target_write_raw_memory(), tcomplain(), thread_db_load(), update_current_target(), value_assign(), value_fn_field(), VEC(), watchpoints_triggered(), and write_exp_msymbol().
ULONGEST LONGEST len
Definition at line 269 of file target.h.
int may_insert_breakpoints
Referenced by remote_set_permissions(), set_observer_mode(), tcomplain(), and update_observer_mode().
int may_insert_fast_tracepoints
Referenced by download_tracepoint_locations(), remote_set_permissions(), set_observer_mode(), start_tracing(), stop_tracing(), tcomplain(), and update_observer_mode().
int may_insert_tracepoints
Referenced by download_tracepoint_locations(), remote_set_permissions(), set_observer_mode(), start_tracing(), stop_tracing(), tcomplain(), and update_observer_mode().
int may_stop
Referenced by remote_set_permissions(), set_observer_mode(), tcomplain(), and update_observer_mode().
int may_write_memory
Referenced by remote_set_permissions(), set_observer_mode(), and tcomplain().
int may_write_registers
Referenced by remote_set_permissions(), set_observer_mode(), and tcomplain().
ULONGEST offset
Definition at line 269 of file target.h.
int remote_debug
Definition at line 171 of file top.c.
int remote_timeout
Definition at line 167 of file top.c.
Referenced by _initialize_cli_cmds(), captured_main(), getpkt_or_notif_sane_1(), mips_expect(), pmon_check_ack(), pmon_check_entry_address(), putpkt_binary(), read_frame(), remote_flash_done(), remote_flash_erase(), remote_flash_write(), restore_remote_timeout(), send_srec(), and skip_frame().
int target_async_permitted
Definition at line 4987 of file target.c.
Referenced by linux_nat_can_async_p(), linux_nat_is_async_p(), record_full_can_async_p(), record_full_is_async_p(), remote_can_async_p(), remote_is_async_p(), remote_open_1(), remote_terminal_inferior(), remote_terminal_ours(), set_observer_mode(), and set_target_async_command().