GDB (xrefs): /home/stan/gdb/src/gdb/target.c File Reference
/home/stan/gdb/src/gdb/target.c File Reference
#include "defs.h"
#include <errno.h>
#include "gdb_string.h"
#include "target.h"
#include "gdbcmd.h"
#include "symtab.h"
#include "inferior.h"
#include "bfd.h"
#include "symfile.h"
#include "objfiles.h"
#include "dcache.h"
#include <signal.h>
#include "regcache.h"
#include "gdb_assert.h"
#include "gdbcore.h"
#include "exceptions.h"
#include "target-descriptions.h"
#include "gdbthread.h"
#include "solib.h"
#include "exec.h"
#include "inline-frame.h"
#include "tracepoint.h"
#include "gdb/fileio.h"
#include "agent.h"
Defines
#define DEFAULT_ALLOCSIZE 10
#define INHERIT(FIELD, TARGET)
#define de_fault(field, value)
#define CASE(X) case X: return #X
#define MIN(A, B) (((A) <= (B)) ? (A) : (B))
#define SEARCH_CHUNK_SIZE 16000
#define DO_TARG_OPTION(OPT) ret = do_option (&target_options, ret, OPT, #OPT)
Functions
static void target_info (char *, int)
static void default_terminal_info (const char *, int)
static int default_watchpoint_addr_within_range (struct target_ops *, CORE_ADDR, CORE_ADDR, int)
static int default_region_ok_for_hw_watchpoint (CORE_ADDR, int)
static void tcomplain (void)
static void setup_target_debug (void)
static void set_stack_cache_enabled_p (char *args, int from_tty, struct cmd_list_element *c)
static void show_stack_cache_enabled_p (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
void target_dcache_invalidate (void)
static void target_command (char *arg, int from_tty)
int default_child_has_all_memory (struct target_ops *ops)
int default_child_has_memory (struct target_ops *ops)
int default_child_has_stack (struct target_ops *ops)
int default_child_has_registers (struct target_ops *ops)
int default_child_has_execution (struct target_ops *ops, ptid_t the_ptid)
int target_has_all_memory_1 (void)
int target_has_memory_1 (void)
int target_has_stack_1 (void)
int target_has_registers_1 (void)
int target_has_execution_1 (ptid_t the_ptid)
int target_has_execution_current (void)
void complete_target_initialization (struct target_ops *t)
void add_target_with_completer (struct target_ops *t, completer_ftype *completer)
void add_target (struct target_ops *t)
void add_deprecated_target_alias (struct target_ops *t, char *alias)
void target_ignore (void)
void target_kill (void)
void target_load (char *arg, int from_tty)
void target_create_inferior (char *exec_file, char *args, char **env, int from_tty)
void target_terminal_inferior (void)
static int nomemory (CORE_ADDR memaddr, char *myaddr, int len, int write, struct target_ops *t)
void noprocess (void)
static ptid_t default_get_ada_task_ptid (long lwp, long tid)
static enum exec_direction_kind default_execution_direction (void)
static void update_current_target (void)
void push_target (struct target_ops *t)
int unpush_target (struct target_ops *t)
void pop_all_targets_above (enum strata above_stratum)
void pop_all_targets (void)
int target_is_pushed (struct target_ops *t)
CORE_ADDR target_translate_tls_address (struct objfile *objfile, CORE_ADDR offset)
const char * target_xfer_error_to_string (enum target_xfer_error err)
int target_read_string (CORE_ADDR memaddr, char **string, int len, int *errnop)
struct target_section_table * target_get_section_table (struct target_ops *target)
struct target_section * target_section_by_addr (struct target_ops *target, CORE_ADDR addr)
static LONGEST target_read_live_memory (enum target_object object, ULONGEST memaddr, gdb_byte *myaddr, LONGEST len)
static LONGEST memory_xfer_live_readonly_partial (struct target_ops *ops, enum target_object object, gdb_byte *readbuf, ULONGEST memaddr, LONGEST len)
static LONGEST memory_xfer_partial_1 (struct target_ops *ops, enum target_object object, void *readbuf, const void *writebuf, ULONGEST memaddr, LONGEST len)
static LONGEST memory_xfer_partial (struct target_ops *ops, enum target_object object, void *readbuf, const void *writebuf, ULONGEST memaddr, LONGEST len)
static void restore_show_memory_breakpoints (void *arg)
struct cleanup * make_show_memory_breakpoints_cleanup (int show)
LONGEST target_xfer_partial (struct target_ops *ops, enum target_object object, const char *annex, void *readbuf, const void *writebuf, ULONGEST offset, LONGEST len)
int target_read_memory (CORE_ADDR memaddr, gdb_byte *myaddr, ssize_t len)
int target_read_stack (CORE_ADDR memaddr, gdb_byte *myaddr, ssize_t len)
int target_write_memory (CORE_ADDR memaddr, const gdb_byte *myaddr, ssize_t len)
int target_write_raw_memory (CORE_ADDR memaddr, const gdb_byte *myaddr, ssize_t len)
VEC (mem_region_s)
void target_flash_erase (ULONGEST address, LONGEST length)
void target_flash_done (void)
static void show_trust_readonly (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static LONGEST default_xfer_partial (struct target_ops *ops, enum target_object object, const char *annex, gdb_byte *readbuf, const gdb_byte *writebuf, ULONGEST offset, LONGEST len)
static LONGEST current_xfer_partial (struct target_ops *ops, enum target_object object, const char *annex, gdb_byte *readbuf, const gdb_byte *writebuf, ULONGEST offset, LONGEST len)
static LONGEST target_read_partial (struct target_ops *ops, enum target_object object, const char *annex, gdb_byte *buf, ULONGEST offset, LONGEST len)
static LONGEST target_write_partial (struct target_ops *ops, enum target_object object, const char *annex, const gdb_byte *buf, ULONGEST offset, LONGEST len)
LONGEST target_read (struct target_ops *ops, enum target_object object, const char *annex, gdb_byte *buf, ULONGEST offset, LONGEST len)
static void read_whatever_is_readable (struct target_ops *ops, ULONGEST begin, ULONGEST end, VEC(memory_read_result_s)**result)
void free_memory_read_result_vector (void *x)
VEC (memory_read_result_s)
LONGEST target_write_with_progress (struct target_ops *ops, enum target_object object, const char *annex, const gdb_byte *buf, ULONGEST offset, LONGEST len, void(*progress)(ULONGEST, void *), void *baton)
LONGEST target_write (struct target_ops *ops, enum target_object object, const char *annex, const gdb_byte *buf, ULONGEST offset, LONGEST len)
static LONGEST target_read_alloc_1 (struct target_ops *ops, enum target_object object, const char *annex, gdb_byte **buf_p, int padding)
LONGEST target_read_alloc (struct target_ops *ops, enum target_object object, const char *annex, gdb_byte **buf_p)
char * target_read_stralloc (struct target_ops *ops, enum target_object object, const char *annex)
void get_target_memory (struct target_ops *ops, CORE_ADDR addr, gdb_byte *buf, LONGEST len)
ULONGEST get_target_memory_unsigned (struct target_ops *ops, CORE_ADDR addr, int len, enum bfd_endian byte_order)
int target_insert_breakpoint (struct gdbarch *gdbarch, struct bp_target_info *bp_tgt)
int target_remove_breakpoint (struct gdbarch *gdbarch, struct bp_target_info *bp_tgt)
void target_pre_inferior (int from_tty)
static int dispose_inferior (struct inferior *inf, void *args)
void target_preopen (int from_tty)
void target_detach (char *args, int from_tty)
void target_disconnect (char *args, int from_tty)
ptid_t target_wait (ptid_t ptid, struct target_waitstatus *status, int options)
char * target_pid_to_str (ptid_t ptid)
char * target_thread_name (struct thread_info *info)
void target_resume (ptid_t ptid, int step, enum gdb_signal signal)
void target_pass_signals (int numsigs, unsigned char *pass_signals)
void target_program_signals (int numsigs, unsigned char *program_signals)
int target_follow_fork (int follow_child, int detach_fork)
void target_mourn_inferior (void)
struct target_desc * target_read_description (struct target_ops *target)
int simple_search_memory (struct target_ops *ops, CORE_ADDR start_addr, ULONGEST search_space_len, const gdb_byte *pattern, ULONGEST pattern_len, CORE_ADDR *found_addrp)
int target_search_memory (CORE_ADDR start_addr, ULONGEST search_space_len, const gdb_byte *pattern, ULONGEST pattern_len, CORE_ADDR *found_addrp)
void target_require_runnable (void)
static struct target_ops * find_default_run_target (char *do_mesg)
void find_default_attach (struct target_ops *ops, char *args, int from_tty)
void find_default_create_inferior (struct target_ops *ops, char *exec_file, char *allargs, char **env, int from_tty)
static int find_default_can_async_p (void)
static int find_default_is_async_p (void)
static int find_default_supports_non_stop (void)
int target_supports_non_stop (void)
int target_info_proc (char *args, enum info_proc_what what)
static int find_default_supports_disable_randomization (void)
int target_supports_disable_randomization (void)
char * target_get_osdata (const char *type)
struct address_space * target_thread_address_space (ptid_t ptid)
static struct target_ops * default_fileio_target (void)
int target_fileio_open (const char *filename, int flags, int mode, int *target_errno)
int target_fileio_pwrite (int fd, const gdb_byte *write_buf, int len, ULONGEST offset, int *target_errno)
int target_fileio_pread (int fd, gdb_byte *read_buf, int len, ULONGEST offset, int *target_errno)
int target_fileio_close (int fd, int *target_errno)
int target_fileio_unlink (const char *filename, int *target_errno)
char * target_fileio_readlink (const char *filename, int *target_errno)
static void target_fileio_close_cleanup (void *opaque)
static LONGEST target_fileio_read_alloc_1 (const char *filename, gdb_byte **buf_p, int padding)
LONGEST target_fileio_read_alloc (const char *filename, gdb_byte **buf_p)
char * target_fileio_read_stralloc (const char *filename)
static struct gdbarch * default_thread_architecture (struct target_ops *ops, ptid_t ptid)
static int return_zero (void)
static int return_one (void)
static int return_minus_one (void)
struct target_ops * find_target_beneath (struct target_ops *t)
void generic_mourn_inferior (void)
char * normal_pid_to_str (ptid_t ptid)
static char * dummy_pid_to_str (struct target_ops *ops, ptid_t ptid)
static int dummy_find_memory_regions (find_memory_region_ftype ignore1, void *ignore2)
static char * dummy_make_corefile_notes (bfd *ignore1, int *ignore2)
static gdb_byte * dummy_get_bookmark (char *ignore1, int ignore2)
static void dummy_goto_bookmark (gdb_byte *ignore, int from_tty)
static void init_dummy_target (void)
static void debug_to_open (char *args, int from_tty)
void target_close (struct target_ops *targ)
void target_attach (char *args, int from_tty)
int target_thread_alive (ptid_t ptid)
void target_find_new_threads (void)
void target_stop (ptid_t ptid)
static void debug_to_post_attach (int pid)
static char * str_comma_list_concat_elem (char *list, const char *elem)
static char * do_option (int *target_options, char *ret, int opt, char *opt_str)
char * target_options_to_string (int target_options)
static void debug_print_register (const char *func, struct regcache *regcache, int regno)
void target_fetch_registers (struct regcache *regcache, int regno)
void target_store_registers (struct regcache *regcache, int regno)
int target_core_of_thread (ptid_t ptid)
int target_verify_memory (const gdb_byte *data, CORE_ADDR memaddr, ULONGEST size)
int target_insert_mask_watchpoint (CORE_ADDR addr, CORE_ADDR mask, int rw)
int target_remove_mask_watchpoint (CORE_ADDR addr, CORE_ADDR mask, int rw)
int target_masked_watch_num_registers (CORE_ADDR addr, CORE_ADDR mask)
int target_ranged_break_num_registers (void)
int target_supports_btrace (void)
struct btrace_target_info * target_enable_btrace (ptid_t ptid)
void target_disable_btrace (struct btrace_target_info *btinfo)
void target_teardown_btrace (struct btrace_target_info *btinfo)
VEC (btrace_block_s)
void target_stop_recording (void)
void target_info_record (void)
void target_save_record (const char *filename)
int target_supports_delete_record (void)
void target_delete_record (void)
int target_record_is_replaying (void)
void target_goto_record_begin (void)
void target_goto_record_end (void)
void target_goto_record (ULONGEST insn)
void target_insn_history (int size, int flags)
void target_insn_history_from (ULONGEST from, int size, int flags)
void target_insn_history_range (ULONGEST begin, ULONGEST end, int flags)
void target_call_history (int size, int flags)
void target_call_history_from (ULONGEST begin, int size, int flags)
void target_call_history_range (ULONGEST begin, ULONGEST end, int flags)
static void debug_to_prepare_to_store (struct regcache *regcache)
static int deprecated_debug_xfer_memory (CORE_ADDR memaddr, bfd_byte *myaddr, int len, int write, struct mem_attrib *attrib, struct target_ops *target)
static void debug_to_files_info (struct target_ops *target)
static int debug_to_insert_breakpoint (struct gdbarch *gdbarch, struct bp_target_info *bp_tgt)
static int debug_to_remove_breakpoint (struct gdbarch *gdbarch, struct bp_target_info *bp_tgt)
static int debug_to_can_use_hw_breakpoint (int type, int cnt, int from_tty)
static int debug_to_region_ok_for_hw_watchpoint (CORE_ADDR addr, int len)
static int debug_to_can_accel_watchpoint_condition (CORE_ADDR addr, int len, int rw, struct expression *cond)
static int debug_to_stopped_by_watchpoint (void)
static int debug_to_stopped_data_address (struct target_ops *target, CORE_ADDR *addr)
static int debug_to_watchpoint_addr_within_range (struct target_ops *target, CORE_ADDR addr, CORE_ADDR start, int length)
static int debug_to_insert_hw_breakpoint (struct gdbarch *gdbarch, struct bp_target_info *bp_tgt)
static int debug_to_remove_hw_breakpoint (struct gdbarch *gdbarch, struct bp_target_info *bp_tgt)
static int debug_to_insert_watchpoint (CORE_ADDR addr, int len, int type, struct expression *cond)
static int debug_to_remove_watchpoint (CORE_ADDR addr, int len, int type, struct expression *cond)
static void debug_to_terminal_init (void)
static void debug_to_terminal_inferior (void)
static void debug_to_terminal_ours_for_output (void)
static void debug_to_terminal_ours (void)
static void debug_to_terminal_save_ours (void)
static void debug_to_terminal_info (const char *arg, int from_tty)
static void debug_to_load (char *args, int from_tty)
static void debug_to_post_startup_inferior (ptid_t ptid)
static int debug_to_insert_fork_catchpoint (int pid)
static int debug_to_remove_fork_catchpoint (int pid)
static int debug_to_insert_vfork_catchpoint (int pid)
static int debug_to_remove_vfork_catchpoint (int pid)
static int debug_to_insert_exec_catchpoint (int pid)
static int debug_to_remove_exec_catchpoint (int pid)
static int debug_to_has_exited (int pid, int wait_status, int *exit_status)
static int debug_to_can_run (void)
static struct gdbarch * debug_to_thread_architecture (struct target_ops *ops, ptid_t ptid)
static void debug_to_stop (ptid_t ptid)
static void debug_to_rcmd (char *command, struct ui_file *outbuf)
static char * debug_to_pid_to_exec_file (int pid)
static void do_monitor_command (char *cmd, int from_tty)
static void maintenance_print_target_stack (char *cmd, int from_tty)
static void set_target_async_command (char *args, int from_tty, struct cmd_list_element *c)
static void show_target_async_command (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
void update_target_permissions (void)
static void set_target_permissions (char *args, int from_tty, struct cmd_list_element *c)
static void set_write_memory_permission (char *args, int from_tty, struct cmd_list_element *c)
void initialize_targets (void)
Variables
static int stack_cache_enabled_p_1 = 1
static int stack_cache_enabled_p = 1
static DCACHE * target_dcache
static char targ_desc []
int target_async_permitted = 0
static int target_async_permitted_1 = 0
static int may_write_registers_1 = 1
static int may_write_memory_1 = 1
static int may_insert_breakpoints_1 = 1
static int may_insert_tracepoints_1 = 1
static int may_insert_fast_tracepoints_1 = 1
static int may_stop_1 = 1
Define Documentation
#define CASE (X) case X: return #X
Referenced by target_xfer_error_to_string().
#define de_fault (field, value)
Value:
if (!current_target.field)               \
    current_target.field = value
Referenced by update_current_target().
#define DEFAULT_ALLOCSIZE 10
#define DO_TARG_OPTION (OPT) ret = do_option (&target_options, ret, OPT, #OPT)
Referenced by target_options_to_string().
#define INHERIT (FIELD, TARGET)
Value:
if (!current_target.FIELD) \
        current_target.FIELD = (TARGET)->FIELD
Referenced by update_current_target().
#define MIN (A, B) (((A) <= (B)) ? (A) : (B))
Definition at line 1251 of file target.c.
Referenced by target_read_string().
#define SEARCH_CHUNK_SIZE 16000
Referenced by simple_search_memory().
Function Documentation
void add_deprecated_target_alias (struct target_ops * t, char * alias)
Definition at line 456 of file target.c.
References add_cmd(), deprecate_cmd(), no_class, target_ops::to_doc, target_ops::to_open, target_ops::to_shortname, and xstrprintf().
Referenced by _initialize_record_full().
void add_target (struct target_ops * t)
Definition at line 448 of file target.c.
References add_target_with_completer().
Referenced by _initialize_alpha_nat(), _initialize_alphabsd_nat(), _initialize_amd64_sol2_nat(), _initialize_amd64fbsd_nat(), _initialize_amd64nbsd_nat(), _initialize_amd64obsd_nat(), _initialize_arm_netbsd_nat(), _initialize_darwin_inferior(), _initialize_dbug_rom(), _initialize_dink32_rom(), _initialize_go32_nat(), _initialize_hppa_hpux_nat(), _initialize_hppabsd_nat(), _initialize_hppanbsd_nat(), _initialize_i386fbsd_nat(), _initialize_i386gnu_nat(), _initialize_i386nbsd_nat(), _initialize_i386obsd_nat(), _initialize_ia64_hpux_nat(), _initialize_irix5_nat(), _initialize_m32r_rom(), _initialize_m68kbsd_nat(), _initialize_m88kbsd_nat(), _initialize_mips64obsd_nat(), _initialize_mipsnbsd_nat(), _initialize_picobug_rom(), _initialize_ppcbug_rom(), _initialize_ppcfbsd_nat(), _initialize_ppcnbsd_nat(), _initialize_ppcobsd_nat(), _initialize_procfs(), _initialize_record_full(), _initialize_remote_m32r(), _initialize_remote_mips(), _initialize_remote_sim(), _initialize_rs6000_nat(), _initialize_shnbsd_nat(), _initialize_sparc64fbsd_nat(), _initialize_sparc64nbsd_nat(), _initialize_sparc_sol2_nat(), _initialize_sparcnbsd_nat(), _initialize_spu_nat(), _initialize_vax_nat(), _initialize_vaxbsd_nat(), _initialize_windows_nat(), bsd_kvm_add_target(), and linux_nat_add_target().
void add_target_with_completer (struct target_ops * t, completer_ftype * completer)
Definition at line 409 of file target.c.
References _, add_cmd(), add_prefix_cmd(), class_run, cmdlist, complete_target_initialization(), DEFAULT_ALLOCSIZE, no_class, target_command(), target_ops::to_doc, target_ops::to_open, target_ops::to_shortname, xmalloc(), and xrealloc().
Referenced by _initialize_ctf(), _initialize_tracepoint(), and add_target().
void complete_target_initialization (struct target_ops * t)
Definition at line 382 of file target.c.
References default_xfer_partial(), int, return_zero(), target_ops::to_has_all_memory, target_ops::to_has_execution, target_ops::to_has_memory, target_ops::to_has_registers, target_ops::to_has_stack, and target_ops::to_xfer_partial.
Referenced by _initialize_aix_thread(), _initialize_bsd_uthread(), _initialize_dec_thread(), _initialize_sol_thread(), _initialize_spu_multiarch(), add_target_with_completer(), and init_thread_db_ops().
static LONGEST current_xfer_partial (struct target_ops * ops, enum target_object object, const char * annex, gdb_byte * readbuf, const gdb_byte * writebuf, ULONGEST offset, LONGEST len) [static]
Definition at line 2010 of file target.c.
References target_ops::beneath, and target_ops::to_xfer_partial.
Referenced by update_current_target().
static void debug_print_register (const char * func, struct regcache * regcache, int regno) [static]
Definition at line 3923 of file target.c.
References gdbarch::byte_order, core_addr_to_string_nz(), extract_unsigned_integer(), fprintf_unfiltered(), gdb_stdlog, gdbarch_byte_order(), gdbarch_num_regs(), gdbarch_register_name(), get_regcache_arch(), LONGEST, MAX_REGISTER_SIZE, plongest(), regcache_raw_collect(), register_size(), size, and ULONGEST.
Referenced by target_fetch_registers(), and target_store_registers().
static int debug_to_can_accel_watchpoint_condition (CORE_ADDR addr, int len, int rw, struct expression * cond) [static]
Definition at line 4570 of file target.c.
References core_addr_to_string(), fprintf_unfiltered(), gdb_stdlog, and host_address_to_string().
Referenced by setup_target_debug().
static int debug_to_can_run (void) [static]
Definition at line 4848 of file target.c.
References fprintf_unfiltered(), and gdb_stdlog.
Referenced by setup_target_debug().
static int debug_to_can_use_hw_breakpoint (int type, int cnt, int from_tty) [static]
Definition at line 4540 of file target.c.
References fprintf_unfiltered(), and gdb_stdlog.
Referenced by setup_target_debug().
static void debug_to_files_info (struct target_ops * target) [static]
Definition at line 4502 of file target.c.
References fprintf_unfiltered(), and gdb_stdlog.
Referenced by setup_target_debug().
static int debug_to_has_exited (int pid, int wait_status, int * exit_status) [static]
Definition at line 4835 of file target.c.
References fprintf_unfiltered(), and gdb_stdlog.
Referenced by setup_target_debug().
static int debug_to_insert_breakpoint (struct gdbarch * gdbarch, struct bp_target_info * bp_tgt) [static]
Definition at line 4510 of file target.c.
References core_addr_to_string(), fprintf_unfiltered(), gdb_stdlog, and bp_target_info::placed_address.
Referenced by setup_target_debug().
static int debug_to_insert_exec_catchpoint (int pid) [static]
Definition at line 4809 of file target.c.
References fprintf_unfiltered(), and gdb_stdlog.
Referenced by setup_target_debug().
static int debug_to_insert_fork_catchpoint (int pid) [static]
Definition at line 4757 of file target.c.
References fprintf_unfiltered(), and gdb_stdlog.
Referenced by setup_target_debug().
static int debug_to_insert_hw_breakpoint (struct gdbarch * gdbarch, struct bp_target_info * bp_tgt) [static]
Definition at line 4631 of file target.c.
References core_addr_to_string(), fprintf_unfiltered(), gdb_stdlog, and bp_target_info::placed_address.
Referenced by setup_target_debug().
static int debug_to_insert_vfork_catchpoint (int pid) [static]
Definition at line 4783 of file target.c.
References fprintf_unfiltered(), and gdb_stdlog.
Referenced by setup_target_debug().
static int debug_to_insert_watchpoint (CORE_ADDR addr, int len, int type, struct expression * cond) [static]
Definition at line 4661 of file target.c.
References core_addr_to_string(), fprintf_unfiltered(), gdb_stdlog, and host_address_to_string().
Referenced by setup_target_debug().
static void debug_to_load (char * args, int from_tty) [static]
Definition at line 4740 of file target.c.
References fprintf_unfiltered(), and gdb_stdlog.
Referenced by setup_target_debug().
static void debug_to_open (char * args, int from_tty) [static]
Definition at line 3771 of file target.c.
References fprintf_unfiltered(), and gdb_stdlog.
Referenced by setup_target_debug().
static char* debug_to_pid_to_exec_file (int pid) [static]
Definition at line 4892 of file target.c.
References fprintf_unfiltered(), and gdb_stdlog.
Referenced by setup_target_debug().
static void debug_to_post_attach (int pid) [static]
Definition at line 3867 of file target.c.
References fprintf_unfiltered(), and gdb_stdlog.
Referenced by setup_target_debug().
static void debug_to_post_startup_inferior (ptid_t ptid) [static]
Definition at line 4748 of file target.c.
References fprintf_unfiltered(), gdb_stdlog, and ptid_get_pid().
Referenced by setup_target_debug().
static void debug_to_prepare_to_store (struct regcache * regcache) [static]
Definition at line 4453 of file target.c.
References fprintf_unfiltered(), and gdb_stdlog.
Referenced by setup_target_debug().
static void debug_to_rcmd (char * command, struct ui_file * outbuf) [static]
Definition at line 4884 of file target.c.
References fprintf_unfiltered(), and gdb_stdlog.
Referenced by do_monitor_command(), and setup_target_debug().
static int debug_to_region_ok_for_hw_watchpoint (CORE_ADDR addr, int len) [static]
Definition at line 4556 of file target.c.
References core_addr_to_string(), fprintf_unfiltered(), and gdb_stdlog.
Referenced by setup_target_debug().
static int debug_to_remove_breakpoint (struct gdbarch * gdbarch, struct bp_target_info * bp_tgt) [static]
Definition at line 4525 of file target.c.
References core_addr_to_string(), fprintf_unfiltered(), gdb_stdlog, and bp_target_info::placed_address.
Referenced by setup_target_debug().
static int debug_to_remove_exec_catchpoint (int pid) [static]
Definition at line 4822 of file target.c.
References fprintf_unfiltered(), and gdb_stdlog.
Referenced by setup_target_debug().
static int debug_to_remove_fork_catchpoint (int pid) [static]
Definition at line 4770 of file target.c.
References fprintf_unfiltered(), and gdb_stdlog.
Referenced by setup_target_debug().
static int debug_to_remove_hw_breakpoint (struct gdbarch * gdbarch, struct bp_target_info * bp_tgt) [static]
Definition at line 4646 of file target.c.
References core_addr_to_string(), fprintf_unfiltered(), gdb_stdlog, and bp_target_info::placed_address.
Referenced by setup_target_debug().
static int debug_to_remove_vfork_catchpoint (int pid) [static]
Definition at line 4796 of file target.c.
References fprintf_unfiltered(), and gdb_stdlog.
Referenced by setup_target_debug().
static int debug_to_remove_watchpoint (CORE_ADDR addr, int len, int type, struct expression * cond) [static]
Definition at line 4676 of file target.c.
References core_addr_to_string(), fprintf_unfiltered(), gdb_stdlog, and host_address_to_string().
Referenced by setup_target_debug().
static void debug_to_stop (ptid_t ptid) [static]
Definition at line 4875 of file target.c.
References fprintf_unfiltered(), gdb_stdlog, and target_pid_to_str().
Referenced by setup_target_debug().
static int debug_to_stopped_by_watchpoint (void) [static]
Definition at line 4587 of file target.c.
References fprintf_unfiltered(), and gdb_stdlog.
Referenced by setup_target_debug().
static int debug_to_stopped_data_address (struct target_ops * target, CORE_ADDR * addr) [static]
Definition at line 4600 of file target.c.
References core_addr_to_string(), fprintf_unfiltered(), and gdb_stdlog.
Referenced by setup_target_debug().
static void debug_to_terminal_inferior (void) [static]
Definition at line 4699 of file target.c.
References fprintf_unfiltered(), and gdb_stdlog.
Referenced by setup_target_debug().
static void debug_to_terminal_info (const char * arg, int from_tty) [static]
Definition at line 4731 of file target.c.
References fprintf_unfiltered(), and gdb_stdlog.
Referenced by setup_target_debug().
static void debug_to_terminal_init (void) [static]
Definition at line 4691 of file target.c.
References fprintf_unfiltered(), and gdb_stdlog.
Referenced by setup_target_debug().
static void debug_to_terminal_ours (void) [static]
Definition at line 4715 of file target.c.
References fprintf_unfiltered(), and gdb_stdlog.
Referenced by setup_target_debug().
static void debug_to_terminal_ours_for_output (void) [static]
Definition at line 4707 of file target.c.
References fprintf_unfiltered(), and gdb_stdlog.
Referenced by setup_target_debug().
static void debug_to_terminal_save_ours (void) [static]
Definition at line 4723 of file target.c.
References fprintf_unfiltered(), and gdb_stdlog.
Referenced by setup_target_debug().
static struct gdbarch* debug_to_thread_architecture (struct target_ops * ops, ptid_t ptid) [static, read]
Definition at line 4860 of file target.c.
References fprintf_unfiltered(), gdb_stdlog, gdbarch_bfd_arch_info(), host_address_to_string(), and target_pid_to_str().
Referenced by setup_target_debug().
static int debug_to_watchpoint_addr_within_range (struct target_ops * target, CORE_ADDR addr, CORE_ADDR start, int length) [static]
Definition at line 4614 of file target.c.
References core_addr_to_string(), fprintf_filtered(), and gdb_stdlog.
Referenced by setup_target_debug().
int default_child_has_all_memory (struct target_ops * ops)
Definition at line 261 of file target.c.
References inferior_ptid, null_ptid, and ptid_equal().
Referenced by _initialize_remote_mips(), inf_child_target(), init_base_monitor_ops(), init_go32_ops(), init_procfs_ops(), init_ravenscar_thread_ops(), init_remote_ops(), and init_windows_ops().
int default_child_has_execution (struct target_ops * ops, ptid_t the_ptid)
Definition at line 301 of file target.c.
References null_ptid, and ptid_equal().
Referenced by _initialize_remote_mips(), inf_child_target(), init_base_monitor_ops(), init_gdbsim_ops(), init_go32_ops(), init_procfs_ops(), init_ravenscar_thread_ops(), init_remote_ops(), and init_windows_ops().
int default_child_has_memory (struct target_ops * ops)
Definition at line 271 of file target.c.
References inferior_ptid, null_ptid, and ptid_equal().
Referenced by _initialize_remote_mips(), inf_child_target(), init_base_monitor_ops(), init_go32_ops(), init_procfs_ops(), init_ravenscar_thread_ops(), init_remote_ops(), and init_windows_ops().
int default_child_has_registers (struct target_ops * ops)
Definition at line 291 of file target.c.
References inferior_ptid, null_ptid, and ptid_equal().
Referenced by _initialize_remote_mips(), inf_child_target(), init_base_monitor_ops(), init_gdbsim_ops(), init_go32_ops(), init_procfs_ops(), init_ravenscar_thread_ops(), init_remote_ops(), and init_windows_ops().
int default_child_has_stack (struct target_ops * ops)
Definition at line 281 of file target.c.
References inferior_ptid, null_ptid, and ptid_equal().
Referenced by _initialize_remote_mips(), inf_child_target(), init_base_monitor_ops(), init_gdbsim_ops(), init_go32_ops(), init_procfs_ops(), init_ravenscar_thread_ops(), init_remote_ops(), and init_windows_ops().
static enum exec_direction_kind default_execution_direction (void) [static]
Definition at line 578 of file target.c.
References EXEC_FORWARD, gdb_assert_not_reached, target_can_async_p, and target_can_execute_reverse.
Referenced by update_current_target().
static struct target_ops* default_fileio_target (void) [static, read]
Definition at line 3304 of file target.c.
References target_ops::beneath, current_target, find_default_run_target(), process_stratum, and target_ops::to_stratum.
Referenced by target_fileio_close(), target_fileio_open(), target_fileio_pread(), target_fileio_pwrite(), target_fileio_readlink(), and target_fileio_unlink().
static ptid_t default_get_ada_task_ptid (long lwp, long tid) [static]
Definition at line 572 of file target.c.
References inferior_ptid, ptid_build(), and ptid_get_pid().
Referenced by update_current_target().
static int default_region_ok_for_hw_watchpoint (CORE_ADDR addr, int len) [static]
Definition at line 3601 of file target.c.
References gdbarch_ptr_bit(), and target_gdbarch().
Referenced by update_current_target().
static void default_terminal_info (const char * args, int from_tty) [static]
Definition at line 560 of file target.c.
References _, and printf_unfiltered().
Referenced by update_current_target().
static struct gdbarch* default_thread_architecture (struct target_ops * ops, ptid_t ptid) [static, read]
Definition at line 3615 of file target.c.
References target_gdbarch().
Referenced by update_current_target().
static int default_watchpoint_addr_within_range (struct target_ops * target, CORE_ADDR addr, CORE_ADDR start, int length) [static]
Definition at line 3607 of file target.c.
Referenced by update_current_target().
static LONGEST default_xfer_partial (struct target_ops * ops, enum target_object object, const char * annex, gdb_byte * readbuf, const gdb_byte * writebuf, ULONGEST offset, LONGEST len) [static]
Definition at line 1964 of file target.c.
References target_ops::beneath, target_ops::deprecated_xfer_memory, do_cleanups(), make_cleanup(), memcpy(), TARGET_OBJECT_MEMORY, target_ops::to_xfer_partial, xfree(), and xmalloc().
Referenced by complete_target_initialization(), and init_dummy_target().
static int deprecated_debug_xfer_memory (CORE_ADDR memaddr, bfd_byte * myaddr, int len, int write, struct mem_attrib * attrib, struct target_ops * target) [static]
Definition at line 4461 of file target.c.
References fprintf_unfiltered(), fputc_unfiltered(), fputs_unfiltered(), gdb_stdlog, paddress(), and target_gdbarch().
Referenced by setup_target_debug().
static int dispose_inferior (struct inferior * inf, void * args) [static]
Definition at line 2559 of file target.c.
References any_thread_of_process(), inferior::pid, thread_info::ptid, switch_to_thread(), target_detach(), target_has_execution, and target_kill().
Referenced by target_preopen().
static void do_monitor_command (char * cmd, int from_tty) [static]
Definition at line 4959 of file target.c.
References _, current_target, debug_to_rcmd(), error(), gdb_stdtarg, target_rcmd, tcomplain(), and target_ops::to_rcmd.
Referenced by initialize_targets().
static char* do_option (int * target_options, char * ret, int opt, char * opt_str) [static]
Definition at line 3892 of file target.c.
References str_comma_list_concat_elem().
static int dummy_find_memory_regions (find_memory_region_ftype ignore1, void * ignore2) [static]
Definition at line 3704 of file target.c.
References _, and error().
Referenced by init_dummy_target().
static gdb_byte* dummy_get_bookmark (char * ignore1, int ignore2) [static]
Definition at line 3720 of file target.c.
References tcomplain().
Referenced by init_dummy_target().
static void dummy_goto_bookmark (gdb_byte * ignore, int from_tty) [static]
Definition at line 3728 of file target.c.
References tcomplain().
Referenced by init_dummy_target().
static char* dummy_make_corefile_notes (bfd * ignore1, int * ignore2) [static]
Definition at line 3712 of file target.c.
References _, and error().
Referenced by init_dummy_target().
static char* dummy_pid_to_str (struct target_ops * ops, ptid_t ptid) [static]
Definition at line 3697 of file target.c.
References normal_pid_to_str().
Referenced by init_dummy_target().
void find_default_attach (struct target_ops * ops, char * args, int from_tty)
Definition at line 3115 of file target.c.
References find_default_run_target(), and target_ops::to_attach.
Referenced by init_core_ops(), init_dummy_target(), and init_exec_ops().
static int find_default_can_async_p (void) [static]
Definition at line 3137 of file target.c.
References find_default_run_target(), and target_ops::to_can_async_p.
Referenced by init_dummy_target().
void find_default_create_inferior (struct target_ops * ops, char * exec_file, char * allargs, char ** env, int from_tty)
Definition at line 3125 of file target.c.
References find_default_run_target(), and target_ops::to_create_inferior.
Referenced by init_core_ops(), init_dummy_target(), init_exec_ops(), init_record_btrace_ops(), and init_record_full_ops().
static int find_default_is_async_p (void) [static]
Definition at line 3152 of file target.c.
References find_default_run_target(), and target_ops::to_is_async_p.
Referenced by init_dummy_target().
static struct target_ops* find_default_run_target (char * do_mesg) [static, read]
Definition at line 3085 of file target.c.
References _, error(), and target_can_run.
Referenced by default_fileio_target(), find_default_attach(), find_default_can_async_p(), find_default_create_inferior(), find_default_is_async_p(), find_default_supports_disable_randomization(), find_default_supports_non_stop(), target_get_osdata(), and target_info_proc().
static int find_default_supports_disable_randomization (void) [static]
Definition at line 3222 of file target.c.
References find_default_run_target(), and target_ops::to_supports_disable_randomization.
Referenced by init_dummy_target().
static int find_default_supports_non_stop (void) [static]
Definition at line 3167 of file target.c.
References find_default_run_target(), and target_ops::to_supports_non_stop.
Referenced by init_dummy_target().
struct target_ops* find_target_beneath (struct target_ops * t) [read]
Definition at line 3643 of file target.c.
References target_ops::beneath.
Referenced by aix_thread_attach(), aix_thread_detach(), aix_thread_fetch_registers(), aix_thread_mourn_inferior(), aix_thread_pid_to_str(), aix_thread_resume(), aix_thread_store_registers(), aix_thread_thread_alive(), aix_thread_wait(), aix_thread_xfer_partial(), bsd_uthread_fetch_registers(), bsd_uthread_mourn_inferior(), bsd_uthread_resume(), bsd_uthread_store_registers(), bsd_uthread_thread_alive(), bsd_uthread_wait(), dec_thread_detach(), dec_thread_fetch_registers(), dec_thread_mourn_inferior(), dec_thread_pid_to_str(), dec_thread_store_registers(), dec_thread_wait(), ppc_linux_spe_context(), ravenscar_fetch_registers(), ravenscar_mourn_inferior(), ravenscar_prepare_to_store(), ravenscar_resume(), ravenscar_store_registers(), ravenscar_wait(), sol_find_new_threads(), sol_thread_alive(), sol_thread_detach(), sol_thread_fetch_registers(), sol_thread_mourn_inferior(), sol_thread_resume(), sol_thread_store_registers(), sol_thread_wait(), sol_thread_xfer_partial(), spu_fetch_registers(), spu_mourn_inferior(), spu_region_ok_for_hw_watchpoint(), spu_search_memory(), spu_store_registers(), spu_xfer_partial(), thread_db_detach(), thread_db_get_thread_local_address(), thread_db_mourn_inferior(), thread_db_pid_to_str(), thread_db_resume(), and thread_db_wait().
void free_memory_read_result_vector (void * x)
Definition at line 2204 of file target.c.
References memory_read_result::data, VEC, VEC_free, VEC_iterate, and xfree().
Referenced by mi_cmd_data_read_memory_bytes().
void generic_mourn_inferior (void)
Definition at line 3652 of file target.c.
References breakpoint_init_inferior(), deprecated_detach_hook, exit_inferior(), inf_exited, inferior_ptid, mark_breakpoints_out(), null_ptid, ptid_equal(), ptid_get_pid(), registers_changed(), reinit_frame_cache(), and reopen_exec_file().
Referenced by darwin_mourn_inferior(), extended_remote_mourn_1(), gdbsim_close_inferior(), gdbsim_mourn_inferior(), gnu_mourn_inferior(), go32_mourn_inferior(), inf_ptrace_mourn_inferior(), m32r_mourn_inferior(), monitor_mourn_inferior(), procfs_mourn_inferior(), remote_mourn_1(), and windows_mourn_inferior().
void get_target_memory (struct target_ops * ops, CORE_ADDR addr, gdb_byte * buf, LONGEST len)
Definition at line 2435 of file target.c.
References memory_error(), TARGET_OBJECT_RAW_MEMORY, target_read(), and TARGET_XFER_E_IO.
Referenced by get_target_memory_unsigned().
ULONGEST get_target_memory_unsigned (struct target_ops * ops, CORE_ADDR addr, int len, enum bfd_endian byte_order)
Definition at line 2448 of file target.c.
References extract_unsigned_integer(), gdb_assert, get_target_memory(), and ULONGEST.
Referenced by frv_convert_from_func_ptr_addr().
static void init_dummy_target (void) [static]
Definition at line 3737 of file target.c.
References default_xfer_partial(), dummy_find_memory_regions(), dummy_get_bookmark(), dummy_goto_bookmark(), dummy_make_corefile_notes(), dummy_pid_to_str(), dummy_stratum, find_default_attach(), find_default_can_async_p(), find_default_create_inferior(), find_default_is_async_p(), find_default_supports_disable_randomization(), find_default_supports_non_stop(), int, OPS_MAGIC, return_zero(), and target_ignore().
Referenced by initialize_targets().
void initialize_targets (void)
Definition at line 5073 of file target.c.
References _, add_cmd(), add_com(), add_info(), add_setshow_boolean_cmd(), add_setshow_zuinteger_cmd(), class_maintenance, class_obscure, class_support, dcache_init(), do_monitor_command(), init_dummy_target(), maintenance_print_target_stack(), maintenanceprintlist, no_class, push_target(), set_stack_cache_enabled_p(), set_target_async_command(), set_target_permissions(), set_write_memory_permission(), setdebuglist, setlist, show_stack_cache_enabled_p(), show_target_async_command(), show_trust_readonly(), showdebuglist, showlist, and target_info().
Referenced by gdb_init().
static void maintenance_print_target_stack (char * cmd, int from_tty) [static]
Definition at line 4974 of file target.c.
References _, target_ops::beneath, printf_filtered(), target_ops::to_longname, and target_ops::to_shortname.
Referenced by initialize_targets().
struct cleanup* make_show_memory_breakpoints_cleanup (int show) [read]
Definition at line 1701 of file target.c.
References make_cleanup(), and restore_show_memory_breakpoints().
Referenced by bp_loc_is_permanent(), ia64_breakpoint_from_pc(), ia64_memory_insert_breakpoint(), ia64_memory_remove_breakpoint(), and ppc_linux_memory_remove_breakpoint().
static LONGEST memory_xfer_live_readonly_partial (struct target_ops * ops, enum target_object object, gdb_byte * readbuf, ULONGEST memaddr, LONGEST len) [static]
Definition at line 1392 of file target.c.
References target_section::addr, target_section::endaddr, len, memaddr, p, target_section_table::sections, sections_end, target_get_section_table(), target_read_live_memory(), target_section_by_addr(), target_section::the_bfd_section, and ULONGEST.
Referenced by memory_xfer_partial_1().
static LONGEST memory_xfer_partial (struct target_ops * ops, enum target_object object, void * readbuf, const void * writebuf, ULONGEST memaddr, LONGEST len) [static]
Definition at line 1656 of file target.c.
References breakpoint_xfer_memory(), do_cleanups(), make_cleanup(), memcpy(), memory_xfer_partial_1(), xfree(), and xmalloc().
Referenced by target_xfer_partial().
static LONGEST memory_xfer_partial_1 (struct target_ops * ops, enum target_object object, void * readbuf, const void * writebuf, ULONGEST memaddr, LONGEST len) [static]
Definition at line 1444 of file target.c.
References _, mem_region::attrib, available, target_ops::beneath, mem_attrib::cache, dcache_update(), dcache_xfer_memory(), do_cleanups(), error(), find_inferior_pid(), find_pc_overlay(), gdb_assert, get_traceframe_number(), mem_region::hi, arm-linux::inf, inferior_ptid, len, LONGEST, lookup_mem_region(), make_cleanup(), MEM_FLASH, MEM_NONE, MEM_RO, MEM_WO, memaddr, memory_xfer_live_readonly_partial(), mem_attrib::mode, null_ptid, overlay_debugging, overlay_mapped_address(), pc_in_unmapped_range(), ptid_equal(), ptid_get_pid(), section_table_xfer_memory_partial(), target_section_table::sections, target_section_table::sections_end, target_get_section_table(), TARGET_OBJECT_MEMORY, TARGET_OBJECT_STACK_MEMORY, target_section_by_addr(), TARGET_XFER_E_UNAVAILABLE, obj_section::the_bfd_section, target_section::the_bfd_section, target_ops::to_has_all_memory, target_ops::to_xfer_partial, traceframe_available_memory(), VEC, VEC_cleanup, VEC_empty, and VEC_index.
Referenced by memory_xfer_partial().
static int nomemory (CORE_ADDR memaddr, char * myaddr, int len, int write, struct target_ops * t) [static]
Definition at line 539 of file target.c.
Referenced by update_current_target().
void noprocess (void)
Definition at line 554 of file target.c.
References _, and error().
Referenced by call_function_by_hand(), gcore_command(), restore_command(), target_kill(), target_resume(), target_store_registers(), target_wait(), and update_current_target().
char* normal_pid_to_str (ptid_t ptid)
Definition at line 3688 of file target.c.
References ptid_get_pid(), and xsnprintf().
Referenced by bsd_uthread_pid_to_str(), core_pid_to_str(), darwin_pid_to_str(), dummy_pid_to_str(), gdbsim_pid_to_str(), go32_pid_to_str(), i386_windows_core_pid_to_str(), inf_ptrace_pid_to_str(), linux_core_pid_to_str(), linux_nat_pid_to_str(), m32r_pid_to_str(), monitor_pid_to_str(), remote_pid_to_str(), sol2_core_pid_to_str(), target_pid_to_str(), thread_db_pid_to_str(), and windows_pid_to_str().
void pop_all_targets (void)
Definition at line 1108 of file target.c.
References dummy_stratum, and pop_all_targets_above().
Referenced by quit_force().
void pop_all_targets_above (enum strata above_stratum)
Definition at line 1091 of file target.c.
References _, current_target, fprintf_unfiltered(), gdb_stderr, internal_error(), target_ops::to_shortname, target_ops::to_stratum, and unpush_target().
Referenced by pop_all_targets(), remote_unpush_target(), and target_preopen().
void push_target (struct target_ops * t)
Definition at line 1005 of file target.c.
References _, target_ops::beneath, fprintf_unfiltered(), gdb_stderr, internal_error(), OPS_MAGIC, target_close(), target_ops::to_magic, target_ops::to_shortname, target_ops::to_stratum, and update_current_target().
Referenced by add_target_sections(), bsd_kvm_open(), bsd_uthread_activate(), check_for_thread_db(), core_open(), darwin_attach_pid(), do_initial_windows_stuff(), enable_dec_thread(), gdbsim_open(), gnu_attach(), gnu_create_inferior(), go32_create_inferior(), inf_ptrace_attach(), inf_ptrace_create_inferior(), initialize_targets(), m32r_open(), monitor_open(), pd_enable(), procfs_attach(), procfs_create_inferior(), procfs_init_inferior(), ravenscar_inferior_created(), record_btrace_open(), record_full_core_open_1(), record_full_open_1(), remote_open_1(), spu_multiarch_activate(), tfile_open(), and try_thread_db_load_1().
static void read_whatever_is_readable (struct target_ops * ops, ULONGEST begin, ULONGEST end, VEC(memory_read_result_s)** result) [static]
Definition at line 2092 of file target.c.
References memory_read_result::begin, memory_read_result::data, memory_read_result::end, LONGEST, memcpy(), TARGET_OBJECT_MEMORY, target_read(), target_read_partial(), ULONGEST, VEC_safe_push, xfree(), and xmalloc().
Referenced by VEC().
static void restore_show_memory_breakpoints (void * arg) [static]
Definition at line 1695 of file target.c.
Referenced by make_show_memory_breakpoints_cleanup().
static int return_minus_one (void) [static]
Definition at line 3633 of file target.c.
Referenced by update_current_target().
static int return_one (void) [static]
Definition at line 3627 of file target.c.
Referenced by update_current_target().
static int return_zero (void) [static]
Definition at line 3621 of file target.c.
Referenced by complete_target_initialization(), init_dummy_target(), and update_current_target().
static void set_stack_cache_enabled_p (char * args, int from_tty, struct cmd_list_element * c) [static]
Definition at line 222 of file target.c.
References stack_cache_enabled_p_1, and target_dcache_invalidate().
Referenced by initialize_targets().
static void set_target_async_command (char * args, int from_tty, struct cmd_list_element * c) [static]
Definition at line 4994 of file target.c.
References _, error(), have_live_inferiors(), target_async_permitted, and target_async_permitted_1.
Referenced by initialize_targets().
static void set_target_permissions (char * args, int from_tty, struct cmd_list_element * c) [static]
Definition at line 5042 of file target.c.
References _, error(), may_insert_breakpoints_1, may_insert_fast_tracepoints_1, may_insert_tracepoints_1, may_stop_1, may_write_registers_1, target_has_execution, update_observer_mode(), and update_target_permissions().
Referenced by initialize_targets().
static void set_write_memory_permission (char * args, int from_tty, struct cmd_list_element * c) [static]
Definition at line 5063 of file target.c.
References may_write_memory_1, and update_observer_mode().
Referenced by initialize_targets().
static void setup_target_debug (void) [static]
Definition at line 4905 of file target.c.
References current_target, debug_to_can_accel_watchpoint_condition(), debug_to_can_run(), debug_to_can_use_hw_breakpoint(), debug_to_files_info(), debug_to_has_exited(), debug_to_insert_breakpoint(), debug_to_insert_exec_catchpoint(), debug_to_insert_fork_catchpoint(), debug_to_insert_hw_breakpoint(), debug_to_insert_vfork_catchpoint(), debug_to_insert_watchpoint(), debug_to_load(), debug_to_open(), debug_to_pid_to_exec_file(), debug_to_post_attach(), debug_to_post_startup_inferior(), debug_to_prepare_to_store(), debug_to_rcmd(), debug_to_region_ok_for_hw_watchpoint(), debug_to_remove_breakpoint(), debug_to_remove_exec_catchpoint(), debug_to_remove_fork_catchpoint(), debug_to_remove_hw_breakpoint(), debug_to_remove_vfork_catchpoint(), debug_to_remove_watchpoint(), debug_to_stop(), debug_to_stopped_by_watchpoint(), debug_to_stopped_data_address(), debug_to_terminal_inferior(), debug_to_terminal_info(), debug_to_terminal_init(), debug_to_terminal_ours(), debug_to_terminal_ours_for_output(), debug_to_terminal_save_ours(), debug_to_thread_architecture(), debug_to_watchpoint_addr_within_range(), deprecated_debug_xfer_memory(), target_ops::deprecated_xfer_memory, memcpy(), target_ops::to_can_accel_watchpoint_condition, target_ops::to_can_run, target_ops::to_can_use_hw_breakpoint, target_ops::to_files_info, target_ops::to_has_exited, target_ops::to_insert_breakpoint, target_ops::to_insert_exec_catchpoint, target_ops::to_insert_fork_catchpoint, target_ops::to_insert_hw_breakpoint, target_ops::to_insert_vfork_catchpoint, target_ops::to_insert_watchpoint, target_ops::to_load, target_ops::to_open, target_ops::to_pid_to_exec_file, target_ops::to_post_attach, target_ops::to_post_startup_inferior, target_ops::to_prepare_to_store, target_ops::to_rcmd, target_ops::to_region_ok_for_hw_watchpoint, target_ops::to_remove_breakpoint, target_ops::to_remove_exec_catchpoint, target_ops::to_remove_fork_catchpoint, target_ops::to_remove_hw_breakpoint, target_ops::to_remove_vfork_catchpoint, target_ops::to_remove_watchpoint, target_ops::to_stop, target_ops::to_stopped_by_watchpoint, target_ops::to_stopped_data_address, target_ops::to_terminal_inferior, target_ops::to_terminal_info, target_ops::to_terminal_init, target_ops::to_terminal_ours, target_ops::to_terminal_ours_for_output, target_ops::to_terminal_save_ours, target_ops::to_thread_architecture, and target_ops::to_watchpoint_addr_within_range.
Referenced by update_current_target().
static void show_stack_cache_enabled_p (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 232 of file target.c.
References _, and fprintf_filtered().
Referenced by initialize_targets().
static void show_target_async_command (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 5007 of file target.c.
References _, and fprintf_filtered().
Referenced by initialize_targets().
static void show_trust_readonly (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 1953 of file target.c.
References _, and fprintf_filtered().
Referenced by initialize_targets().
int simple_search_memory (struct target_ops * ops, CORE_ADDR start_addr, ULONGEST search_space_len, const gdb_byte * pattern, ULONGEST pattern_len, CORE_ADDR * found_addrp)
Definition at line 2892 of file target.c.
References _, do_cleanups(), error(), free_current_contents(), gdb_assert, hex_string(), make_cleanup(), malloc(), memcpy(), min, plongest(), pulongest(), SEARCH_CHUNK_SIZE, TARGET_OBJECT_MEMORY, target_read(), and warning().
Referenced by remote_search_memory(), spu_search_memory(), and target_search_memory().
static char* str_comma_list_concat_elem (char * list, const char * elem) [static]
Definition at line 3878 of file target.c.
Referenced by do_option(), and target_options_to_string().
void target_attach (char * args, int from_tty)
Definition at line 3793 of file target.c.
References _, target_ops::beneath, current_target, fprintf_unfiltered(), gdb_stdlog, internal_error(), and target_ops::to_attach.
Referenced by attach_command().
void target_call_history (int size, int flags)
Definition at line 4404 of file target.c.
References target_ops::beneath, current_target, tcomplain(), and target_ops::to_call_history.
Referenced by cmd_record_call_history().
void target_call_history_from (ULONGEST begin, int size, int flags)
Definition at line 4421 of file target.c.
References target_ops::beneath, current_target, tcomplain(), and target_ops::to_call_history_from.
Referenced by cmd_record_call_history().
void target_call_history_range (ULONGEST begin, ULONGEST end, int flags)
Definition at line 4438 of file target.c.
References target_ops::beneath, current_target, tcomplain(), and target_ops::to_call_history_range.
Referenced by cmd_record_call_history().
void target_close (struct target_ops * targ)
Definition at line 3779 of file target.c.
References fprintf_unfiltered(), gdb_assert, gdb_stdlog, target_is_pushed(), target_ops::to_close, and target_ops::to_xclose.
Referenced by enable_break(), push_target(), and unpush_target().
static void target_command (char * arg, int from_tty) [static]
Definition at line 252 of file target.c.
References fputs_filtered(), and gdb_stdout.
Referenced by add_target_with_completer().
int target_core_of_thread (ptid_t ptid)
Definition at line 4001 of file target.c.
References target_ops::beneath, current_target, fprintf_unfiltered(), gdb_stdlog, ptid_get_pid(), and target_ops::to_core_of_thread.
Referenced by collect_cores(), mi_on_normal_stop(), and print_thread_info().
void target_create_inferior (char * exec_file, char * args, char ** env, int from_tty)
Definition at line 501 of file target.c.
References _, target_ops::beneath, current_target, fprintf_unfiltered(), gdb_stdlog, internal_error(), and target_ops::to_create_inferior.
Referenced by run_command_1().
void target_dcache_invalidate (void)
Definition at line 244 of file target.c.
References dcache_invalidate().
Referenced by mem_delete_command(), mem_disable_command(), mem_enable_command(), prepare_execute_command(), set_stack_cache_enabled_p(), target_load(), target_resume(), and tfind_1().
void target_delete_record (void)
Definition at line 4271 of file target.c.
References target_ops::beneath, current_target, tcomplain(), and target_ops::to_delete_record.
Referenced by cmd_record_delete().
void target_detach (char * args, int from_tty)
Definition at line 2608 of file target.c.
References _, target_ops::beneath, current_target, fprintf_unfiltered(), gdb_stdlog, gdbarch_has_global_breakpoints(), inferior_ptid, internal_error(), prepare_for_detach(), ptid_get_pid(), remove_breakpoints_pid(), target_gdbarch(), and target_ops::to_detach.
Referenced by detach_command(), dispose_inferior(), gdb_clear_file(), handle_vfork_child_exec_or_exit(), kill_or_detach(), linux_child_follow_fork(), and record_detach().
void target_disable_btrace (struct btrace_target_info * btinfo)
Definition at line 4162 of file target.c.
References target_ops::beneath, current_target, tcomplain(), and target_ops::to_disable_btrace.
Referenced by btrace_disable().
void target_disconnect (char * args, int from_tty)
Definition at line 2639 of file target.c.
References target_ops::beneath, current_target, fprintf_unfiltered(), gdb_stdlog, remove_breakpoints(), tcomplain(), and target_ops::to_disconnect.
Referenced by disconnect_command(), and record_disconnect().
struct btrace_target_info* target_enable_btrace (ptid_t ptid) [read]
Definition at line 4147 of file target.c.
References target_ops::beneath, current_target, tcomplain(), and target_ops::to_enable_btrace.
Referenced by btrace_enable().
void target_fetch_registers (struct regcache * regcache, int regno)
Definition at line 3960 of file target.c.
References target_ops::beneath, current_target, debug_print_register(), and target_ops::to_fetch_registers.
Referenced by bsd_kvm_open(), bsd_kvm_pcb_cmd(), bsd_kvm_proc_cmd(), core_open(), linux_corefile_thread_callback(), ps_lgetfpregs(), ps_lgetregs(), record_full_core_open_1(), and regcache_raw_read().
int target_fileio_close (int fd, int * target_errno)
Definition at line 3405 of file target.c.
References target_ops::beneath, default_fileio_target(), fprintf_unfiltered(), gdb_stdlog, and target_ops::to_fileio_close.
Referenced by target_fileio_close_cleanup().
static void target_fileio_close_cleanup (void * opaque) [static]
Definition at line 3480 of file target.c.
References target_fileio_close().
Referenced by target_fileio_read_alloc_1().
int target_fileio_open (const char * filename, int flags, int mode, int * target_errno)
Definition at line 3318 of file target.c.
References target_ops::beneath, default_fileio_target(), fprintf_unfiltered(), gdb_stdlog, and target_ops::to_fileio_open.
Referenced by target_fileio_read_alloc_1().
int target_fileio_pread (int fd, gdb_byte * read_buf, int len, ULONGEST offset, int * target_errno)
Definition at line 3376 of file target.c.
References target_ops::beneath, default_fileio_target(), fprintf_unfiltered(), gdb_stdlog, pulongest(), and target_ops::to_fileio_pread.
Referenced by target_fileio_read_alloc_1().
int target_fileio_pwrite (int fd, const gdb_byte * write_buf, int len, ULONGEST offset, int * target_errno)
Definition at line 3346 of file target.c.
References target_ops::beneath, default_fileio_target(), fprintf_unfiltered(), gdb_stdlog, pulongest(), and target_ops::to_fileio_pwrite.
LONGEST target_fileio_read_alloc (const char * filename, gdb_byte ** buf_p)
Definition at line 3557 of file target.c.
References target_fileio_read_alloc_1().
static LONGEST target_fileio_read_alloc_1 (const char * filename, gdb_byte ** buf_p, int padding) [static]
Definition at line 3495 of file target.c.
References do_cleanups(), LONGEST, make_cleanup(), QUIT, target_fileio_close_cleanup(), target_fileio_open(), target_fileio_pread(), xfree(), xmalloc(), and xrealloc().
Referenced by target_fileio_read_alloc(), and target_fileio_read_stralloc().
char* target_fileio_read_stralloc (const char * filename)
Definition at line 3569 of file target.c.
References _, LONGEST, target_fileio_read_alloc_1(), and warning().
Referenced by linux_fill_prpsinfo(), linux_find_memory_regions_full(), and linux_info_proc().
char* target_fileio_readlink (const char * filename, int * target_errno)
Definition at line 3456 of file target.c.
References target_ops::beneath, default_fileio_target(), fprintf_unfiltered(), gdb_stdlog, and target_ops::to_fileio_readlink.
Referenced by linux_info_proc().
int target_fileio_unlink (const char * filename, int * target_errno)
Definition at line 3430 of file target.c.
References target_ops::beneath, default_fileio_target(), fprintf_unfiltered(), gdb_stdlog, and target_ops::to_fileio_unlink.
void target_find_new_threads (void)
Definition at line 3837 of file target.c.
References target_ops::beneath, current_target, fprintf_unfiltered(), gdb_stdlog, and target_ops::to_find_new_threads.
Referenced by check_for_thread_db(), core_open(), print_ada_task_info(), task_command_1(), and update_thread_list().
void target_flash_done (void)
Definition at line 1936 of file target.c.
References target_ops::beneath, current_target, fprintf_unfiltered(), gdb_stdlog, tcomplain(), and target_ops::to_flash_done.
Referenced by target_write_memory_blocks().
void target_flash_erase (ULONGEST address, LONGEST length)
Definition at line 1918 of file target.c.
References target_ops::beneath, current_target, fprintf_unfiltered(), gdb_stdlog, hex_string(), phex(), tcomplain(), and target_ops::to_flash_erase.
Referenced by target_write_memory_blocks().
int target_follow_fork (int follow_child, int detach_fork)
Definition at line 2816 of file target.c.
References _, target_ops::beneath, current_target, fprintf_unfiltered(), gdb_stdlog, internal_error(), and target_ops::to_follow_fork.
Referenced by follow_fork().
char* target_get_osdata (const char * type)
Definition at line 3245 of file target.c.
References target_ops::beneath, current_target, find_default_run_target(), process_stratum, TARGET_OBJECT_OSDATA, target_read_stralloc(), and target_ops::to_stratum.
Referenced by get_osdata().
struct target_section_table* target_get_section_table (struct target_ops * target) [read]
Definition at line 1327 of file target.c.
References target_ops::beneath, fprintf_unfiltered(), gdb_stdlog, and target_ops::to_get_section_table.
Referenced by exec_xfer_partial(), memory_xfer_live_readonly_partial(), memory_xfer_partial_1(), read_value_memory(), and target_section_by_addr().
void target_goto_record (ULONGEST insn)
Definition at line 4336 of file target.c.
References target_ops::beneath, current_target, tcomplain(), and target_ops::to_goto_record.
Referenced by cmd_record_goto().
void target_goto_record_begin (void)
Definition at line 4302 of file target.c.
References target_ops::beneath, current_target, tcomplain(), and target_ops::to_goto_record_begin.
Referenced by cmd_record_goto_begin().
void target_goto_record_end (void)
Definition at line 4319 of file target.c.
References target_ops::beneath, current_target, tcomplain(), and target_ops::to_goto_record_end.
Referenced by cmd_record_goto_end().
int target_has_all_memory_1 (void)
Definition at line 313 of file target.c.
References target_ops::beneath, current_target, and target_ops::to_has_all_memory.
int target_has_execution_1 (ptid_t the_ptid)
Definition at line 361 of file target.c.
References target_ops::beneath, current_target, and target_ops::to_has_execution.
Referenced by have_live_inferiors(), and target_has_execution_current().
int target_has_execution_current (void)
Definition at line 373 of file target.c.
References inferior_ptid, and target_has_execution_1().
int target_has_memory_1 (void)
Definition at line 325 of file target.c.
References target_ops::beneath, current_target, and target_ops::to_has_memory.
int target_has_registers_1 (void)
Definition at line 349 of file target.c.
References target_ops::beneath, current_target, and target_ops::to_has_registers.
int target_has_stack_1 (void)
Definition at line 337 of file target.c.
References target_ops::beneath, current_target, and target_ops::to_has_stack.
void target_ignore (void)
Definition at line 471 of file target.c.
Referenced by gdb_stop(), init_dummy_target(), and update_current_target().
static void target_info (char * args, int from_tty) [static]
Definition at line 2489 of file target.c.
References _, target_ops::beneath, dummy_stratum, objfile_name(), printf_unfiltered(), symfile_objfile, target_ops::to_files_info, target_ops::to_has_all_memory, target_ops::to_has_memory, target_ops::to_longname, and target_ops::to_stratum.
Referenced by initialize_targets().
int target_info_proc (char * args, enum info_proc_what what)
Definition at line 3192 of file target.c.
References target_ops::beneath, current_target, find_default_run_target(), fprintf_unfiltered(), gdb_stdlog, process_stratum, target_ops::to_info_proc, and target_ops::to_stratum.
Referenced by info_proc_cmd_1().
void target_info_record (void)
Definition at line 4223 of file target.c.
References target_ops::beneath, current_target, tcomplain(), and target_ops::to_info_record.
int target_insert_breakpoint (struct gdbarch * gdbarch, struct bp_target_info * bp_tgt)
Definition at line 2459 of file target.c.
References _, current_target, target_ops::to_insert_breakpoint, and warning().
Referenced by bkpt_insert_location(), deprecated_insert_raw_breakpoint(), and insert_bp_location().
int target_insert_mask_watchpoint (CORE_ADDR addr, CORE_ADDR mask, int rw)
Definition at line 4050 of file target.c.
References target_ops::beneath, core_addr_to_string(), current_target, fprintf_unfiltered(), gdb_stdlog, and target_ops::to_insert_mask_watchpoint.
Referenced by insert_masked_watchpoint().
void target_insn_history (int size, int flags)
Definition at line 4353 of file target.c.
References target_ops::beneath, current_target, tcomplain(), and target_ops::to_insn_history.
Referenced by cmd_record_insn_history().
void target_insn_history_from (ULONGEST from, int size, int flags)
Definition at line 4370 of file target.c.
References target_ops::beneath, current_target, tcomplain(), and target_ops::to_insn_history_from.
Referenced by cmd_record_insn_history().
void target_insn_history_range (ULONGEST begin, ULONGEST end, int flags)
Definition at line 4387 of file target.c.
References target_ops::beneath, current_target, tcomplain(), and target_ops::to_insn_history_range.
Referenced by cmd_record_insn_history().
int target_is_pushed (struct target_ops * t)
Definition at line 1116 of file target.c.
References _, target_ops::beneath, fprintf_unfiltered(), gdb_stderr, internal_error(), OPS_MAGIC, target_ops::to_magic, and target_ops::to_shortname.
Referenced by inf_ptrace_attach(), inf_ptrace_create_inferior(), and target_close().
void target_kill (void)
Definition at line 476 of file target.c.
References target_ops::beneath, current_target, fprintf_unfiltered(), gdb_stdlog, noprocess(), and target_ops::to_kill.
Referenced by attach_command(), dispose_inferior(), gdb_clear_file(), kill_command(), kill_if_already_running(), kill_inferior_command(), kill_or_detach(), and record_kill().
void target_load (char * arg, int from_tty)
Definition at line 494 of file target.c.
References current_target, target_dcache_invalidate(), and target_ops::to_load.
Referenced by load_command().
int target_masked_watch_num_registers (CORE_ADDR addr, CORE_ADDR mask)
Definition at line 4104 of file target.c.
References target_ops::beneath, current_target, and target_ops::to_masked_watch_num_registers.
Referenced by resources_needed_masked_watchpoint(), and watch_command_1().
void target_mourn_inferior (void)
Definition at line 2840 of file target.c.
References _, target_ops::beneath, current_target, fprintf_unfiltered(), gdb_stdlog, internal_error(), and target_ops::to_mourn_inferior.
Referenced by darwin_kill_inferior(), extended_remote_kill(), gdbsim_kill(), get_windows_debug_event(), gnu_kill_inferior(), handle_inferior_event(), inf_ptrace_kill(), interrupt_query(), linux_nat_attach(), linux_nat_kill(), mips_error(), mips_kill(), mips_readchar(), monitor_interrupt_query(), procfs_kill_inferior(), readchar(), record_mourn_inferior(), remote_detach_1(), remote_kill(), startup_inferior(), and windows_kill_inferior().
char* target_options_to_string (int target_options)
Definition at line 3905 of file target.c.
References DO_TARG_OPTION, str_comma_list_concat_elem(), and TARGET_WNOHANG.
Referenced by linux_nat_wait(), and target_wait().
void target_pass_signals (int numsigs, unsigned char * pass_signals)
Definition at line 2753 of file target.c.
References target_ops::beneath, current_target, fprintf_unfiltered(), gdb_signal_to_name(), gdb_stdlog, and target_ops::to_pass_signals.
Referenced by handle_command(), handle_inferior_event(), record_full_resume(), resume(), and signal_catch_update().
char* target_pid_to_str (ptid_t ptid)
Definition at line 2696 of file target.c.
References target_ops::beneath, current_target, normal_pid_to_str(), and target_ops::to_pid_to_str.
Referenced by add_thread_with_info(), amd64_linux_enable_btrace(), attach_thread(), btrace_clear(), btrace_disable(), btrace_enable(), btrace_fetch(), btrace_teardown(), cancel_breakpoint(), clear_proceed_status_thread(), context_switch(), darwin_attach(), darwin_detach(), dcache_info(), debug_to_stop(), debug_to_thread_architecture(), delete_checkpoint_command(), detach_callback(), detach_checkpoint_command(), displaced_step_fixup(), displaced_step_prepare(), displaced_step_restore(), display_one_tib(), do_captured_thread_select(), exit_lwp(), extended_remote_attach_1(), follow_exec(), get_pending_status(), gnu_fetch_registers(), gnu_resume(), gnu_store_registers(), gnu_wait(), handle_inferior_event(), i386_linux_enable_btrace(), inf_ptrace_attach(), inf_ptrace_detach(), inf_ptrace_files_info(), inferior_command(), inferior_pid_to_str(), info_checkpoints_command(), kill_callback(), kill_wait_callback(), lin_lwp_attach_lwp(), linux_fork_context(), linux_fork_detach(), linux_fork_mourn_inferior(), linux_nat_detach(), linux_nat_filter_event(), linux_nat_post_attach_wait(), linux_nat_resume(), linux_nat_stop_lwp(), linux_nat_wait(), linux_nat_wait_1(), linux_thread_alive(), maybe_clear_ignore_sigint(), normal_stop(), prepare_to_proceed(), print_exited_reason(), print_inferior_quit_action(), print_program_space(), print_signal_received_reason(), print_target_wait_results(), print_thread_info(), proceed_after_vfork_done(), procfs_attach(), procfs_detach(), procfs_fetch_registers(), procfs_files_info(), procfs_wait(), push_stop_reply(), record_btrace_info(), remote_detach_1(), remote_disable_btrace(), remote_enable_btrace(), remote_notif_remove_queued_reply(), remote_stop_ns(), resume(), resume_lwp(), resume_stopped_resumed_lwps(), select_event_lwp(), stop_callback(), stop_wait_callback(), target_thread_address_space(), target_translate_tls_address(), thread_apply_all_command(), thread_apply_command(), thread_command(), thread_find_command(), tui_make_status_line(), wait_lwp(), windows_attach(), windows_delete_thread(), and windows_files_info().
void target_pre_inferior (int from_tty)
Definition at line 2521 of file target.c.
References agent_capability_invalidate(), gdbarch_has_global_solist(), invalidate_target_mem_regions(), no_shared_libraries(), target_clear_description(), and target_gdbarch().
Referenced by attach_command(), run_command_1(), and target_preopen().
void target_preopen (int from_tty)
Definition at line 2582 of file target.c.
References _, dispose_inferior(), dont_repeat(), error(), file_stratum, have_inferiors(), have_live_inferiors(), iterate_over_inferiors(), pop_all_targets_above(), query(), and target_pre_inferior().
Referenced by bsd_kvm_open(), core_open(), exec_open(), m32r_open(), monitor_open(), remote_open_1(), and tfile_open().
void target_program_signals (int numsigs, unsigned char * program_signals)
Definition at line 2783 of file target.c.
References target_ops::beneath, current_target, fprintf_unfiltered(), gdb_signal_to_name(), gdb_stdlog, and target_ops::to_program_signals.
Referenced by handle_command(), and update_signals_program_target().
int target_ranged_break_num_registers (void)
Definition at line 4119 of file target.c.
References target_ops::beneath, current_target, and target_ops::to_ranged_break_num_registers.
Referenced by break_range_command(), and resources_needed_ranged_breakpoint().
LONGEST target_read (struct target_ops * ops, enum target_object object, const char * annex, gdb_byte * buf, ULONGEST offset, LONGEST len)
Definition at line 2046 of file target.c.
References len, LONGEST, QUIT, and target_read_partial().
Referenced by darwin_solib_read_all_image_info_addr(), dcache_read_line(), display_one_tib(), gdb_update_mem(), get_target_memory(), ia64_hpux_find_global_pointer_from_solib(), ia64_hpux_stopped_in_syscall(), info_spu_dma_command(), info_spu_event_command(), info_spu_mailbox_command(), info_spu_proxydma_command(), info_spu_signal_command(), linux_get_siginfo_data(), mi_cmd_data_read_memory(), ppu2spu_sniffer(), read_whatever_is_readable(), save_infcall_suspend_state(), siginfo_value_read(), simple_search_memory(), sparc_fetch_wcookie(), spu_current_sos(), spu_fetch_registers(), spu_pseudo_register_read(), spu_pseudo_register_read_spu(), target_read_live_memory(), target_read_memory(), target_read_stack(), and VEC().
LONGEST target_read_alloc (struct target_ops * ops, enum target_object object, const char * annex, gdb_byte ** buf_p)
Definition at line 2388 of file target.c.
References target_read_alloc_1().
Referenced by avr_io_reg_read_command(), dsbt_get_initial_loadmaps(), get_auxv_inferior_data(), linux_make_corefile_notes(), linux_spu_make_corefile_notes(), and sdata_make_value().
static LONGEST target_read_alloc_1 (struct target_ops * ops, enum target_object object, const char * annex, gdb_byte ** buf_p, int padding) [static]
Definition at line 2331 of file target.c.
References gdb_assert, LONGEST, QUIT, TARGET_OBJECT_MEMORY, target_read_partial(), xfree(), xmalloc(), and xrealloc().
Referenced by target_read_alloc(), and target_read_stralloc().
struct target_desc* target_read_description (struct target_ops * target) [read]
Definition at line 2869 of file target.c.
References target_ops::beneath, and target_ops::to_read_description.
Referenced by target_find_description().
static LONGEST target_read_live_memory (enum target_object object, ULONGEST memaddr, gdb_byte * myaddr, LONGEST len) [static]
Definition at line 1364 of file target.c.
References target_ops::beneath, current_target, do_cleanups(), LONGEST, make_cleanup_restore_traceframe_number(), set_traceframe_number(), and target_read().
Referenced by memory_xfer_live_readonly_partial().
int target_read_memory (CORE_ADDR memaddr, gdb_byte * myaddr, ssize_t len)
Definition at line 1802 of file target.c.
References target_ops::beneath, current_target, TARGET_OBJECT_MEMORY, target_read(), and TARGET_XFER_E_IO.
Referenced by aarch64_get_longjmp_target(), aarch64_stub_unwind_sniffer(), agent_capability_check(), agent_get_helper_thread_id(), agent_run_command(), alpha_get_longjmp_target(), alpha_read_insn(), alpha_skip_prologue(), alphanbsd_sigtramp_offset(), amd64_analyze_stack_align(), amd64_get_longjmp_target(), amd64_in_function_epilogue_p(), amd64_skip_main_prologue(), amd64_skip_xmm_prologue(), amd64_windows_find_unwind_info(), amd64_windows_frame_decode_epilogue(), amd64_windows_frame_decode_insns(), amd64_windows_skip_prologue(), amd64_x32_analyze_stack_align(), arm_adjust_breakpoint_address(), arm_breakpoint_from_pc(), arm_get_longjmp_target(), arm_stub_unwind_sniffer(), arm_symbian_skip_trampoline_code(), bp_loc_is_permanent(), bsd_uthread_wait(), call0_analyze_prologue(), call0_ret(), cp_print_value(), darwin_current_sos(), darwin_load_image_infos(), darwin_read_exec_load_addr(), default_memory_insert_breakpoint(), dis_asm_read_memory(), displaced_step_prepare(), do_search_struct_field(), dsbt_current_sos(), elf_gnu_ifunc_resolve_by_got(), elf_locate_base(), enable_break2(), execute_code(), extend_buffer_earlier(), extract_arm_insn(), fetch_instruction(), fetch_loadmap(), fetch_mips_16(), find_canonical_descriptor_in_load_object(), find_extant_func_descr(), frv_adjust_breakpoint_address(), frv_analyze_prologue(), frv_current_sos(), frv_linux_pc_in_sigtramp(), frv_linux_sigcontext_reg_addr(), frv_skip_main_prologue(), gcore_copy_callback(), get_signo(), hppa32_hpux_find_global_pointer(), hppa32_hpux_search_dummy_call_sequence(), hppa64_convert_code_addr_to_fptr(), hppa64_hpux_find_global_pointer(), hppa64_hpux_search_dummy_call_sequence(), hppa_in_function_epilogue_p(), hppa_linux_find_global_pointer(), hppa_match_insns(), hppabsd_find_global_pointer(), i386_analyze_frame_setup(), i386_analyze_register_saves(), i386_analyze_stack_align(), i386_analyze_struct_return(), i386_darwin_sstep_at_sigreturn(), i386_follow_jump(), i386_frame_cache_1(), i386_get_longjmp_target(), i386_in_function_epilogue_p(), i386_in_stack_tramp_p(), i386_linux_resume(), i386_match_pattern(), i386_skip_main_prologue(), i386_skip_noop(), i386_skip_probe(), i386_skip_prologue(), ia64_breakpoint_from_pc(), ia64_convert_from_func_ptr_addr(), ia64_find_global_pointer_from_dynamic_section(), ia64_hpux_read_dynamic_info(), ia64_hpux_read_tgt_mem(), ia64_memory_insert_breakpoint(), ia64_memory_remove_breakpoint(), insns_match_pattern(), jit_read_code_entry(), jit_read_descriptor(), jit_reader_try_read_symtab(), jit_target_read_impl(), ld_so_xfer_auxv(), lm_base(), lm_info_read(), load_progress(), m32c_analyze_prologue(), m32r_memory_insert_breakpoint(), m68hc11_pseudo_register_read(), m68k_get_longjmp_target(), mem_bfd_iovec_pread(), mi_cmd_trace_frame_collected(), microblaze_fetch_instruction(), microblaze_linux_memory_remove_breakpoint(), mips64_linux_get_longjmp_target(), mips_fetch_instruction(), mips_get_mips16_fn_stub_pc(), mips_linux_get_longjmp_target(), mips_skip_pic_trampoline_code(), mips_stub_frame_sniffer(), mipsnbsd_get_longjmp_target(), mn10300_analyze_prologue(), moxie_process_readu(), msp430_get_opcode_byte(), nios2_get_longjmp_target(), nios2_stub_frame_sniffer(), open_map(), parse_spufs_run(), partial_memory_read(), pascal_object_print_value(), pdc_read_data(), ppc_linux_memory_remove_breakpoint(), ppc_linux_spe_context(), ppu2spu_sniffer(), ps_xfer_memory(), read_clbk(), read_map(), read_program_header(), record_linux_msghdr(), record_linux_sockaddr(), record_linux_system_call(), record_read_memory(), remote_fileio_func_open(), remote_fileio_func_rename(), remote_fileio_func_stat(), remote_fileio_func_system(), remote_fileio_func_unlink(), remote_fileio_func_write(), rl78_get_opcode_byte(), rs6000_fetch_instruction(), rs6000_skip_main_prologue(), rw_common(), rx_get_opcode_byte(), s390_in_function_epilogue_p(), s390_readinstruction(), s390_sigtramp_frame_sniffer(), safe_frame_unwind_memory(), scan_dyntag(), score3_adjust_pc_and_fetch_inst(), score7_breakpoint_from_pc(), score7_fetch_inst(), score7_malloc_and_get_memblock(), search_struct_method(), skip_prologue(), skip_prologue_hard_way(), som_solib_create_inferior_hook(), sparc_fetch_instruction(), sparc_supply_rwindow(), spu2ppu_sniffer(), spu_analyze_prologue(), spu_bfd_iovec_pread(), spu_frame_unwind_cache(), spu_get_longjmp_target(), spu_in_function_epilogue_p(), spu_software_single_step(), stap_modify_semaphore(), target_read_memory_bfd(), target_read_string(), target_write_memory_blocks(), thumb2_copy_table_branch(), thumb_in_function_epilogue_p(), tic6x_get_longjmp_target(), tilegx_get_longjmp_target(), val_print_string(), xstormy16_find_jmp_table_entry(), xstormy16_resolve_jmp_table_entry(), and xtensa_scan_prologue().
static LONGEST target_read_partial (struct target_ops * ops, enum target_object object, const char * annex, gdb_byte * buf, ULONGEST offset, LONGEST len) [static]
Definition at line 2024 of file target.c.
References target_xfer_partial().
Referenced by read_whatever_is_readable(), target_read(), and target_read_alloc_1().
int target_read_stack (CORE_ADDR memaddr, gdb_byte * myaddr, ssize_t len)
Definition at line 1818 of file target.c.
References target_ops::beneath, current_target, TARGET_OBJECT_STACK_MEMORY, target_read(), and TARGET_XFER_E_IO.
Referenced by read_stack().
char* target_read_stralloc (struct target_ops * ops, enum target_object object, const char * annex)
Definition at line 2401 of file target.c.
References _, LONGEST, target_read_alloc_1(), and warning().
Referenced by fetch_available_features_from_target(), remote_threads_info(), remote_traceframe_info(), solib_target_current_sos(), target_get_osdata(), and VEC().
int target_read_string (CORE_ADDR memaddr, char ** string, int len, int * errnop)
Definition at line 1260 of file target.c.
References gdb_assert, MIN, offset, target_read_memory(), xmalloc(), and xrealloc().
Referenced by ada_main_name(), darwin_current_sos(), dsbt_current_sos(), fetch_sec_names(), frv_current_sos(), handle_output_debug_string(), inferior_has_bug(), irix_current_sos(), irix_open_symbol_file_object(), open_symbol_file_object(), print_subexp_standard(), read_map(), som_current_sos(), som_open_symbol_file_object(), and svr4_read_so_list().
int target_record_is_replaying (void)
Definition at line 4288 of file target.c.
References target_ops::beneath, current_target, and target_ops::to_record_is_replaying.
Referenced by cmd_record_delete().
int target_remove_breakpoint (struct gdbarch * gdbarch, struct bp_target_info * bp_tgt)
Definition at line 2472 of file target.c.
References _, current_target, target_ops::to_remove_breakpoint, and warning().
Referenced by bkpt_remove_location(), deprecated_remove_raw_breakpoint(), detach_single_step_breakpoints(), and remove_breakpoint_1().
int target_remove_mask_watchpoint (CORE_ADDR addr, CORE_ADDR mask, int rw)
Definition at line 4077 of file target.c.
References target_ops::beneath, core_addr_to_string(), current_target, fprintf_unfiltered(), gdb_stdlog, and target_ops::to_remove_mask_watchpoint.
Referenced by remove_masked_watchpoint().
void target_require_runnable (void)
Definition at line 3046 of file target.c.
References _, arch_stratum, target_ops::beneath, error(), internal_error(), thread_stratum, target_ops::to_create_inferior, target_ops::to_shortname, and target_ops::to_stratum.
Referenced by kill_if_already_running().
void target_resume (ptid_t ptid, int step, enum gdb_signal signal)
Definition at line 2724 of file target.c.
References target_ops::beneath, clear_inline_frame_state(), current_target, fprintf_unfiltered(), gdb_signal_to_name(), gdb_stdlog, noprocess(), ptid_get_pid(), registers_changed_ptid(), set_executing(), set_running(), target_dcache_invalidate(), and target_ops::to_resume.
Referenced by agent_run_command(), cleanup_target_stop(), displaced_step_fixup(), handle_inferior_event(), ia64_hpux_wait(), irix_solib_create_inferior_hook(), osf_solib_create_inferior_hook(), procfs_wait(), resume(), spu_skip_standalone_loader(), and startup_inferior().
void target_save_record (const char * filename)
Definition at line 4240 of file target.c.
References target_ops::beneath, current_target, tcomplain(), and target_ops::to_save_record.
Referenced by cmd_record_save().
int target_search_memory (CORE_ADDR start_addr, ULONGEST search_space_len, const gdb_byte * pattern, ULONGEST pattern_len, CORE_ADDR * found_addrp)
Definition at line 3002 of file target.c.
References target_ops::beneath, current_target, fprintf_unfiltered(), gdb_stdlog, hex_string(), simple_search_memory(), and target_ops::to_search_memory.
Referenced by find_command(), and infpy_search_memory().
struct target_section* target_section_by_addr (struct target_ops * target, CORE_ADDR addr) [read]
Definition at line 1344 of file target.c.
References target_section::addr, target_section::endaddr, target_section_table::sections, sections_end, and target_get_section_table().
Referenced by memory_xfer_live_readonly_partial(), memory_xfer_partial_1(), ppc64_convert_from_func_ptr_addr(), and s390_load().
void target_stop (ptid_t ptid)
Definition at line 3855 of file target.c.
References _, current_target, target_ops::to_stop, and warning().
Referenced by agent_run_command(), async_remote_interrupt(), attach_command(), attach_command_post_wait(), gdb_stop(), interrupt_target_1(), interrupt_thread_callback(), monitor_interrupt(), notice_new_inferior(), nto_interrupt(), and VEC().
void target_stop_recording (void)
Definition at line 4206 of file target.c.
References target_ops::beneath, current_target, and target_ops::to_stop_recording.
void target_store_registers (struct regcache * regcache, int regno)
Definition at line 3977 of file target.c.
References _, target_ops::beneath, current_target, debug_print_register(), error(), noprocess(), and target_ops::to_store_registers.
Referenced by ps_lsetfpregs(), ps_lsetregs(), regcache_raw_write(), rs6000_lynx178_push_dummy_call(), and rs6000_push_dummy_call().
int target_supports_btrace (void)
Definition at line 4133 of file target.c.
References target_ops::beneath, current_target, and target_ops::to_supports_btrace.
Referenced by btrace_enable(), and record_btrace_open().
int target_supports_delete_record (void)
Definition at line 4257 of file target.c.
References target_ops::beneath, current_target, and target_ops::to_delete_record.
Referenced by cmd_record_delete().
int target_supports_disable_randomization (void)
Definition at line 3233 of file target.c.
References target_ops::beneath, current_target, and target_ops::to_supports_disable_randomization.
Referenced by set_disable_randomization(), and show_disable_randomization().
int target_supports_non_stop (void)
Definition at line 3178 of file target.c.
References target_ops::beneath, current_target, and target_ops::to_supports_non_stop.
Referenced by attach_command(), and run_command_1().
void target_teardown_btrace (struct btrace_target_info * btinfo)
Definition at line 4176 of file target.c.
References target_ops::beneath, current_target, tcomplain(), and target_ops::to_teardown_btrace.
Referenced by btrace_teardown().
void target_terminal_inferior (void)
Definition at line 524 of file target.c.
References current_target, sync_execution, target_can_async_p, and target_ops::to_terminal_inferior.
Referenced by attach_command_post_wait(), do_initial_windows_stuff(), handle_inferior_event(), handle_jit_event(), handle_solib_event(), i386_process_record(), i386_record_lea_modrm(), inf_validate_task_sc(), interrupt_query(), m32r_create_inferior(), mips_kill(), monitor_interrupt_query(), record_full_check_insn_num(), record_linux_system_call(), remote_wait_as(), resume(), startup_inferior(), and tui_about_to_proceed().
struct address_space* target_thread_address_space (ptid_t ptid) [read]
Definition at line 3266 of file target.c.
References _, address_space_num(), inferior::aspace, target_ops::beneath, current_target, find_inferior_pid(), fprintf_unfiltered(), gdb_assert, gdb_stdlog, arm-linux::inf, internal_error(), ptid_get_pid(), target_pid_to_str(), and target_ops::to_thread_address_space.
Referenced by get_thread_arch_regcache().
int target_thread_alive (ptid_t ptid)
Definition at line 3814 of file target.c.
References target_ops::beneath, current_target, fprintf_unfiltered(), gdb_stdlog, ptid_get_pid(), and target_ops::to_thread_alive.
Referenced by display_tib(), handle_inferior_event(), lwp_to_thread(), rw_common(), sol_thread_xfer_partial(), and thread_alive().
char* target_thread_name (struct thread_info * info)
Definition at line 2710 of file target.c.
References target_ops::beneath, current_target, and target_ops::to_thread_name.
Referenced by print_thread_info(), thpy_get_name(), and thread_find_command().
CORE_ADDR target_translate_tls_address (struct objfile * objfile, CORE_ADDR offset)
Definition at line 1141 of file target.c.
References _, target_ops::beneath, current_target, gdb_exception::error, error(), objfile::flags, gdbarch_fetch_tls_load_module_address(), gdbarch_fetch_tls_load_module_address_p(), inferior_ptid, lm_addr(), gdb_exception::message, OBJF_SHARED, objfile_name(), gdb_exception::reason, RETURN_MASK_ALL, target_gdbarch(), target_pid_to_str(), throw_error(), throw_exception(), TLS_GENERIC_ERROR, TLS_LOAD_MODULE_NOT_FOUND_ERROR, TLS_NO_LIBRARY_SUPPORT_ERROR, TLS_NOT_ALLOCATED_YET_ERROR, target_ops::to_get_thread_local_address, and TRY_CATCH.
Referenced by default_read_var_value(), dwarf_expr_tls_address(), and evaluate_subexp_standard().
int target_verify_memory (const gdb_byte * data, CORE_ADDR memaddr, ULONGEST size)
Definition at line 4023 of file target.c.
References target_ops::beneath, current_target, fprintf_unfiltered(), gdb_stdlog, paddress(), pulongest(), target_gdbarch(), tcomplain(), and target_ops::to_verify_memory.
Referenced by compare_sections_command().
ptid_t target_wait (ptid_t ptid, struct target_waitstatus * status, int options)
Definition at line 2662 of file target.c.
References target_ops::beneath, current_target, fprintf_unfiltered(), gdb_stdlog, noprocess(), ptid_get_pid(), target_options_to_string(), target_waitstatus_to_string(), target_ops::to_wait, and xfree().
Referenced by agent_run_command(), fetch_inferior_event(), gdbtk_wait(), prepare_for_detach(), spu_skip_standalone_loader(), startup_inferior(), and wait_for_inferior().
LONGEST target_write (struct target_ops * ops, enum target_object object, const char * annex, const gdb_byte * buf, ULONGEST offset, LONGEST len)
Definition at line 2315 of file target.c.
References target_write_with_progress().
Referenced by dcache_xfer_memory(), restore_infcall_suspend_state(), siginfo_value_write(), spu_pseudo_register_write(), spu_pseudo_register_write_spu(), spu_store_registers(), target_write_memory(), and target_write_raw_memory().
int target_write_memory (CORE_ADDR memaddr, const gdb_byte * myaddr, ssize_t len)
Definition at line 1838 of file target.c.
References target_ops::beneath, current_target, TARGET_OBJECT_MEMORY, target_write(), and TARGET_XFER_E_IO.
Referenced by agent_run_command(), append_insns(), gdb_set_mem(), ia64_memory_insert_breakpoint(), ld_so_xfer_auxv(), m32r_memory_insert_breakpoint(), m68hc11_pseudo_register_write(), pdc_write_data(), ps_xfer_memory(), record_full_exec_insn(), remote_fileio_func_fstat(), remote_fileio_func_gettimeofday(), remote_fileio_func_read(), remote_fileio_func_stat(), restore_binary_file(), restore_section_callback(), rw_common(), som_solib_create_inferior_hook(), sparc_collect_rwindow(), spu_push_dummy_call(), stap_modify_semaphore(), write_clbk(), and write_memory().
static LONGEST target_write_partial (struct target_ops * ops, enum target_object object, const char * annex, const gdb_byte * buf, ULONGEST offset, LONGEST len) [static]
Definition at line 2033 of file target.c.
References target_xfer_partial().
Referenced by target_write_with_progress().
int target_write_raw_memory (CORE_ADDR memaddr, const gdb_byte * myaddr, ssize_t len)
Definition at line 1857 of file target.c.
References target_ops::beneath, current_target, TARGET_OBJECT_RAW_MEMORY, target_write(), and TARGET_XFER_E_IO.
Referenced by default_memory_insert_breakpoint(), default_memory_remove_breakpoint(), ia64_memory_remove_breakpoint(), m32r_memory_remove_breakpoint(), microblaze_linux_memory_remove_breakpoint(), and ppc_linux_memory_remove_breakpoint().
LONGEST target_write_with_progress (struct target_ops * ops, enum target_object object, const char * annex, const gdb_byte * buf, ULONGEST offset, LONGEST len, void(*)(ULONGEST, void *) progress, void * baton)
Definition at line 2280 of file target.c.
References len, LONGEST, QUIT, and target_write_partial().
Referenced by target_write(), and target_write_memory_blocks().
const char* target_xfer_error_to_string (enum target_xfer_error err)
Definition at line 1236 of file target.c.
References CASE, TARGET_XFER_E_IO, and TARGET_XFER_E_UNAVAILABLE.
Referenced by memory_error_message().
LONGEST target_xfer_partial (struct target_ops * ops, enum target_object object, const char * annex, void * readbuf, const void * writebuf, ULONGEST offset, LONGEST len)
Definition at line 1713 of file target.c.
References _, core_addr_to_string_nz(), error(), fprintf_unfiltered(), fputc_unfiltered(), fputs_unfiltered(), gdb_assert, gdb_stdlog, host_address_to_string(), LONGEST, memory_xfer_partial(), plongest(), TARGET_OBJECT_MEMORY, TARGET_OBJECT_RAW_MEMORY, TARGET_OBJECT_STACK_MEMORY, target_ops::to_shortname, and target_ops::to_xfer_partial.
Referenced by read_memory(), target_read_partial(), and target_write_partial().
static void tcomplain (void) [static]
Definition at line 56 of file target.c.
References current_target, may_insert_breakpoints, may_insert_fast_tracepoints, may_insert_tracepoints, may_stop, may_write_memory, and may_write_registers.
Referenced by do_monitor_command(), dummy_get_bookmark(), dummy_goto_bookmark(), target_call_history(), target_call_history_from(), target_call_history_range(), target_delete_record(), target_disable_btrace(), target_disconnect(), target_enable_btrace(), target_flash_done(), target_flash_erase(), target_goto_record(), target_goto_record_begin(), target_goto_record_end(), target_info_record(), target_insn_history(), target_insn_history_from(), target_insn_history_range(), target_save_record(), target_teardown_btrace(), target_verify_memory(), update_current_target(), and VEC().
int unpush_target (struct target_ops * t)
Definition at line 1052 of file target.c.
References _, target_ops::beneath, dummy_stratum, internal_error(), target_close(), target_ops::to_stratum, and update_current_target().
Referenced by bsd_kvm_open(), bsd_uthread_deactivate(), core_detach(), core_open(), darwin_mourn_inferior(), disable_dec_thread(), do_unpush_target(), gdbsim_detach(), gdbsim_open(), gnu_detach(), gnu_mourn_inferior(), go32_mourn_inferior(), inf_ptrace_detach(), inf_ptrace_mourn_inferior(), m32r_detach(), monitor_detach(), monitor_mourn_inferior(), monitor_open(), pd_disable(), pop_all_targets_above(), procfs_detach(), procfs_mourn_inferior(), ravenscar_mourn_inferior(), record_full_core_kill(), record_unpush(), remote_mourn_1(), remove_target_sections(), sol_thread_detach(), sol_thread_mourn_inferior(), spu_multiarch_deactivate(), tfile_open(), thread_db_detach(), thread_db_mourn_inferior(), thread_db_wait(), windows_detach(), and windows_mourn_inferior().
static void update_current_target (void) [static]
Definition at line 602 of file target.c.
References target_ops::beneath, current_target, current_xfer_partial(), de_fault, default_execution_direction(), default_get_ada_task_ptid(), default_region_ok_for_hw_watchpoint(), default_terminal_info(), default_thread_architecture(), default_watchpoint_addr_within_range(), target_ops::deprecated_xfer_memory, INHERIT, LONGEST, memory_insert_breakpoint(), memory_remove_breakpoint(), memset(), nomemory(), noprocess(), return_minus_one(), return_one(), return_zero(), setup_target_debug(), target_ignore(), tcomplain(), target_ops::to_async, target_ops::to_attach_no_wait, target_ops::to_augmented_libraries_svr4_read, target_ops::to_can_accel_watchpoint_condition, target_ops::to_can_async_p, target_ops::to_can_download_tracepoint, target_ops::to_can_execute_reverse, target_ops::to_can_run, target_ops::to_can_run_breakpoint_commands, target_ops::to_can_use_agent, target_ops::to_can_use_hw_breakpoint, target_ops::to_close, target_ops::to_disable_tracepoint, target_ops::to_doc, target_ops::to_download_trace_state_variable, target_ops::to_download_tracepoint, target_ops::to_enable_tracepoint, target_ops::to_execution_direction, target_ops::to_extra_thread_info, target_ops::to_files_info, target_ops::to_find_memory_regions, target_ops::to_get_ada_task_ptid, target_ops::to_get_bookmark, target_ops::to_get_min_fast_tracepoint_insn_len, target_ops::to_get_raw_trace_data, target_ops::to_get_tib_address, target_ops::to_get_trace_state_variable_value, target_ops::to_get_trace_status, target_ops::to_get_tracepoint_status, target_ops::to_goto_bookmark, target_ops::to_has_exited, target_ops::to_has_thread_control, target_ops::to_have_continuable_watchpoint, target_ops::to_have_steppable_watchpoint, target_ops::to_insert_breakpoint, target_ops::to_insert_exec_catchpoint, target_ops::to_insert_fork_catchpoint, target_ops::to_insert_hw_breakpoint, target_ops::to_insert_vfork_catchpoint, target_ops::to_insert_watchpoint, target_ops::to_is_async_p, target_ops::to_load, target_ops::to_log_command, target_ops::to_longname, target_ops::to_magic, target_ops::to_make_corefile_notes, target_ops::to_open, target_ops::to_pid_to_exec_file, target_ops::to_post_attach, target_ops::to_post_startup_inferior, target_ops::to_prepare_to_store, target_ops::to_rcmd, target_ops::to_read_description, target_ops::to_region_ok_for_hw_watchpoint, target_ops::to_remove_breakpoint, target_ops::to_remove_exec_catchpoint, target_ops::to_remove_fork_catchpoint, target_ops::to_remove_hw_breakpoint, target_ops::to_remove_vfork_catchpoint, target_ops::to_remove_watchpoint, target_ops::to_save_trace_data, target_ops::to_set_circular_trace_buffer, target_ops::to_set_disconnected_tracing, target_ops::to_set_permissions, target_ops::to_set_syscall_catchpoint, target_ops::to_set_trace_buffer_size, target_ops::to_set_trace_notes, target_ops::to_shortname, target_ops::to_static_tracepoint_marker_at, target_ops::to_stop, target_ops::to_stopped_by_watchpoint, target_ops::to_stopped_data_address, target_ops::to_stratum, target_ops::to_supports_enable_disable_tracepoint, target_ops::to_supports_evaluation_of_breakpoint_conditions, target_ops::to_supports_multi_process, target_ops::to_supports_string_tracing, target_ops::to_terminal_inferior, target_ops::to_terminal_info, target_ops::to_terminal_init, target_ops::to_terminal_ours, target_ops::to_terminal_ours_for_output, target_ops::to_terminal_save_ours, target_ops::to_thread_architecture, target_ops::to_thread_name, target_ops::to_trace_find, target_ops::to_trace_init, target_ops::to_trace_set_readonly_regions, target_ops::to_trace_start, target_ops::to_trace_stop, target_ops::to_traceframe_info, target_ops::to_upload_trace_state_variables, target_ops::to_upload_tracepoints, target_ops::to_use_agent, target_ops::to_watchpoint_addr_within_range, target_ops::to_xfer_partial, ULONGEST, and VEC.
Referenced by push_target(), and unpush_target().
void update_target_permissions (void)
Definition at line 5028 of file target.c.
Referenced by set_observer_mode(), and set_target_permissions().
VEC (mem_region_s)
Definition at line 1871 of file target.c.
References _, target_ops::beneath, current_target, fprintf_filtered(), fprintf_unfiltered(), gdb_stdlog, mem_region::hi, mem_region::lo, mem_region_cmp(), mem_region::number, qsort, VEC, VEC_address, VEC_free, VEC_iterate, VEC_length, and warning().
VEC (memory_read_result_s)
Definition at line 2217 of file target.c.
References mem_region::attrib, memory_read_result::begin, memory_read_result::data, memory_read_result::end, gdb_assert, mem_region::hi, LONGEST, lookup_mem_region(), MEM_NONE, MEM_WO, min, mem_attrib::mode, offset, QUIT, read_whatever_is_readable(), TARGET_OBJECT_MEMORY, target_read(), VEC, VEC_safe_push, xfree(), and xmalloc().
VEC (btrace_block_s)
Definition at line 4189 of file target.c.
References target_ops::beneath, current_target, and tcomplain().
Variable Documentation
int may_insert_breakpoints_1 = 1 [static]
Definition at line 5020 of file target.c.
Referenced by set_target_permissions().
int may_insert_fast_tracepoints_1 = 1 [static]
Definition at line 5022 of file target.c.
Referenced by set_target_permissions().
int may_insert_tracepoints_1 = 1 [static]
Definition at line 5021 of file target.c.
Referenced by set_target_permissions().
int may_stop_1 = 1 [static]
Definition at line 5023 of file target.c.
Referenced by set_target_permissions().
int may_write_memory_1 = 1 [static]
Definition at line 5019 of file target.c.
Referenced by set_write_memory_permission().
int may_write_registers_1 = 1 [static]
Definition at line 5018 of file target.c.
Referenced by set_target_permissions().
int stack_cache_enabled_p = 1 [static]
Definition at line 214 of file target.c.
int stack_cache_enabled_p_1 = 1 [static]
Definition at line 210 of file target.c.
Referenced by set_stack_cache_enabled_p().
char targ_desc[] [static]
Initial value:
"Names of targets and files being debugged.\nShows the entire \
stack of targets currently in use (including the exec-file,\n\
core-file, and process, if any), as well as the symbol file name."
Definition at line 4953 of file target.c.
int target_async_permitted = 0
Definition at line 4987 of file target.c.
Referenced by linux_nat_can_async_p(), linux_nat_is_async_p(), record_full_can_async_p(), record_full_is_async_p(), remote_can_async_p(), remote_is_async_p(), remote_open_1(), remote_terminal_inferior(), remote_terminal_ours(), set_observer_mode(), and set_target_async_command().
int target_async_permitted_1 = 0 [static]
Definition at line 4991 of file target.c.
Referenced by set_target_async_command().
DCACHE* target_dcache [static]
Definition at line 239 of file target.c.