GDB (xrefs): /home/stan/gdb/src/gdb/terminal.h File Reference
/home/stan/gdb/src/gdb/terminal.h File Reference
#include <fcntl.h>
#include <sgtty.h>
#include <sys/ioctl.h>
Defines
#define TERMINAL struct sgttyb
Functions
void new_tty_prefork (const char *)
void new_tty (void)
void new_tty_postfork (void)
void copy_terminal_info (struct inferior *to, struct inferior *from)
pid_t create_tty_session (void)
int gdb_setpgid (void)
void initialize_stdin_serial (void)
int gdb_has_a_terminal (void)
Variables
int job_control
Define Documentation
#define TERMINAL struct sgttyb
Definition at line 74 of file terminal.h.
Function Documentation
void copy_terminal_info (struct inferior * to, struct inferior * from)
Definition at line 541 of file inflow.c.
References get_inflow_inferior_data(), terminal_info::run_terminal, serial_copy_tty_state(), terminal_info::ttystate, and xfree().
Referenced by linux_child_follow_fork().
pid_t create_tty_session (void)
Definition at line 813 of file inflow.c.
References _, job_control, safe_strerror(), and warning().
Referenced by fork_inferior().
int gdb_has_a_terminal (void)
Definition at line 163 of file inflow.c.
References AUTO_BOOLEAN_AUTO, AUTO_BOOLEAN_TRUE, gdb_has_a_terminal_flag, have_not_checked, no, our_terminal_info, serial_get_tty_state(), terminal_info::tflags, terminal_info::ttystate, and yes.
Referenced by child_terminal_info(), input_from_terminal_p(), show_interactive_mode(), terminal_inferior(), terminal_init_inferior_with_pgrp(), terminal_ours_1(), and terminal_save_ours().
int gdb_setpgid (void)
Definition at line 842 of file inflow.c.
References job_control.
Referenced by fork_inferior().
void initialize_stdin_serial (void)
Definition at line 876 of file inflow.c.
References serial_fdopen().
Referenced by gdb_init().
void new_tty (void)
Definition at line 685 of file inflow.c.
References _, check_syscall(), O_NOCTTY, safe_strerror(), and warning().
Referenced by fork_inferior().
void new_tty_postfork (void)
Definition at line 748 of file inflow.c.
References current_inferior(), get_inflow_inferior_data(), and terminal_info::run_terminal.
Referenced by fork_inferior().
void new_tty_prefork (const char *)
Definition at line 662 of file inflow.c.
Referenced by fork_inferior().
Variable Documentation
int job_control
Referenced by command_line_handler(), command_line_input(), create_tty_session(), gdb_setpgid(), terminal_inferior(), and terminal_ours_1().