GDB (xrefs): /home/stan/gdb/src/gdb/tilegx-linux-tdep.c File Reference
/home/stan/gdb/src/gdb/tilegx-linux-tdep.c File Reference
#include "defs.h"
#include "osabi.h"
#include "linux-tdep.h"
#include "glibc-tdep.h"
#include "solib-svr4.h"
#include "symtab.h"
#include "regcache.h"
#include "regset.h"
#include "tramp-frame.h"
#include "trad-frame.h"
#include "tilegx-tdep.h"
Functions
static void tilegx_linux_sigframe_init (const struct tramp_frame *self, struct frame_info *this_frame, struct trad_frame_cache *this_cache, CORE_ADDR func)
static void tilegx_linux_supply_regset (const struct regset *regset, struct regcache *regcache, int regnum, const void *regs, size_t len)
static struct regset * tilegx_regset_from_core_section (struct gdbarch *gdbarch, const char *sect_name, size_t sect_size)
static void tilegx_linux_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
void _initialize_tilegx_linux_tdep (void)
Variables
static struct tramp_frame tilegx_linux_rt_sigframe
static struct regset tilegx_linux_regset
initialize_file_ftype _initialize_tilegx_linux_tdep
Function Documentation
void _initialize_tilegx_linux_tdep (void)
Definition at line 154 of file tilegx-linux-tdep.c.
References _initialize_tilegx_linux_tdep, GDB_OSABI_LINUX, gdbarch_register_osabi(), and tilegx_linux_init_abi().
static void tilegx_linux_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch) [static]
Definition at line 120 of file tilegx-linux-tdep.c.
References find_solib_trampoline_target(), gdbarch_addr_bit(), glibc_skip_solib_resolver(), linux_get_siginfo_type(), linux_init_abi(), set_gdbarch_fetch_tls_load_module_address(), set_gdbarch_get_siginfo_type(), set_gdbarch_regset_from_core_section(), set_gdbarch_skip_solib_resolver(), set_gdbarch_skip_trampoline_code(), set_solib_svr4_fetch_link_map_offsets(), svr4_fetch_objfile_link_map(), svr4_ilp32_fetch_link_map_offsets(), svr4_lp64_fetch_link_map_offsets(), tilegx_regset_from_core_section(), and tramp_frame_prepend_unwinder().
Referenced by _initialize_tilegx_linux_tdep().
static void tilegx_linux_sigframe_init (const struct tramp_frame * self, struct frame_info * this_frame, struct trad_frame_cache * this_cache, CORE_ADDR func) [static]
Definition at line 35 of file tilegx-linux-tdep.c.
References frame_id_build(), get_frame_memory_unsigned(), get_frame_register_unsigned(), sp, trad_frame_set_id(), trad_frame_set_reg_addr(), and trad_frame_set_reg_value().
static void tilegx_linux_supply_regset (const struct regset * regset, struct regcache * regcache, int regnum, const void * regs, size_t len) [static]
Definition at line 79 of file tilegx-linux-tdep.c.
References get_regcache_arch(), regcache_raw_supply(), TILEGX_FAULTNUM_REGNUM, TILEGX_NUM_EASY_REGS, TILEGX_PC_REGNUM, and tilegx_reg_size.
static struct regset* tilegx_regset_from_core_section (struct gdbarch * gdbarch, const char * sect_name, size_t sect_size) [static, read]
Definition at line 107 of file tilegx-linux-tdep.c.
References tilegx_linux_regset.
Referenced by tilegx_linux_init_abi().
Variable Documentation
initialize_file_ftype _initialize_tilegx_linux_tdep
Referenced by _initialize_tilegx_linux_tdep(), and initialize_all_files().
struct regset tilegx_linux_regset [static]
Initial value:
{
  NULL,
  tilegx_linux_supply_regset
}
Definition at line 100 of file tilegx-linux-tdep.c.
Referenced by tilegx_regset_from_core_section().
struct tramp_frame tilegx_linux_rt_sigframe [static]
Initial value:
{
  SIGTRAMP_FRAME,
  8,
  {
    { 0x00045fe551483000ULL, -1 },
    { 0x286b180051485000ULL, -1 },
    { TRAMP_SENTINEL_INSN, -1 }
  },
  tilegx_linux_sigframe_init
}
Definition at line 64 of file tilegx-linux-tdep.c.