GDB (xrefs): /home/stan/gdb/src/gdb/tilegx-linux-nat.c File Reference
/home/stan/gdb/src/gdb/tilegx-linux-nat.c File Reference
#include "defs.h"
#include "inferior.h"
#include "gdbcore.h"
#include "regcache.h"
#include "linux-nat.h"
#include <sys/ptrace.h>
#include "gdb_assert.h"
#include "gdb_string.h"
#include <sys/procfs.h>
#include "gdb_proc_service.h"
#include "gregset.h"
Functions
void supply_gregset (struct regcache *regcache, const elf_gregset_t *gregsetp)
void fill_gregset (const struct regcache *regcache, elf_gregset_t *gregsetp, int regno)
void supply_fpregset (struct regcache *regcache, const elf_fpregset_t *fpregsetp)
void fill_fpregset (const struct regcache *regcache, elf_fpregset_t *fpregsetp, int regno)
static void fetch_inferior_registers (struct target_ops *ops, struct regcache *regcache, int regnum)
static void store_inferior_registers (struct target_ops *ops, struct regcache *regcache, int regnum)
void _initialize_tile_linux_nat (void)
Variables
static const int regmap []
initialize_file_ftype _initialize_tile_linux_nat
Function Documentation
void _initialize_tile_linux_nat (void)
Definition at line 174 of file tilegx-linux-nat.c.
References _initialize_tile_linux_nat, fetch_inferior_registers(), linux_nat_add_target(), linux_target(), store_inferior_registers(), target_ops::to_fetch_registers, and target_ops::to_store_registers.
static void fetch_inferior_registers (struct target_ops * ops, struct regcache * regcache, int regnum) [static]
Definition at line 131 of file tilegx-linux-nat.c.
References _, inferior_ptid, perror_with_name(), ptid_get_lwp(), ptid_get_pid(), ptrace(), PTRACE_GETREGS, PTRACE_TYPE_ARG3, and supply_gregset().
Referenced by _initialize_tile_linux_nat().
void fill_fpregset (const struct regcache * regcache, elf_fpregset_t * fpregsetp, int regno)
Definition at line 121 of file tilegx-linux-nat.c.
void fill_gregset (const struct regcache * regcache, elf_gregset_t * gregsetp, int regno)
Definition at line 93 of file tilegx-linux-nat.c.
References regcache_raw_collect(), and regmap.
static void store_inferior_registers (struct target_ops * ops, struct regcache * regcache, int regnum) [static]
Definition at line 151 of file tilegx-linux-nat.c.
References _, fill_gregset(), inferior_ptid, perror_with_name(), ptid_get_lwp(), ptid_get_pid(), ptrace(), PTRACE_GETREGS, PTRACE_SETREGS, and PTRACE_TYPE_ARG3.
Referenced by _initialize_tile_linux_nat().
void supply_fpregset (struct regcache * regcache, const elf_fpregset_t * fpregsetp)
Definition at line 110 of file tilegx-linux-nat.c.
void supply_gregset (struct regcache * regcache, const elf_gregset_t * gregsetp)
Definition at line 78 of file tilegx-linux-nat.c.
References regcache_raw_supply(), and regmap.
Variable Documentation
initialize_file_ftype _initialize_tile_linux_nat
Referenced by _initialize_tile_linux_nat().
const int regmap[] [static]
Initial value:
{
   0,  1,  2,  3,  4,  5,  6,  7,
   8,  9, 10, 11, 12, 13, 14, 15,
  16, 17, 18, 19, 20, 21, 22, 23,
  24, 25, 26, 27, 28, 29, 30, 31,
  32, 33, 34, 35, 36, 37, 38, 39,
  40, 41, 42, 43, 44, 45, 46, 47,
  48, 49, 50, 51, 52, 53, 54, 55,
  -1, -1, -1, -1, -1, -1, -1, -1,
  56, 58
}
Definition at line 58 of file tilegx-linux-nat.c.
Referenced by fill_gregset(), and supply_gregset().