GDB (xrefs): /home/stan/gdb/src/gdb/top.c File Reference
/home/stan/gdb/src/gdb/top.c File Reference
#include "defs.h"
#include "gdbcmd.h"
#include "cli/cli-cmds.h"
#include "cli/cli-script.h"
#include "cli/cli-setshow.h"
#include "cli/cli-decode.h"
#include "symtab.h"
#include "inferior.h"
#include "exceptions.h"
#include <signal.h>
#include "target.h"
#include "breakpoint.h"
#include "gdbtypes.h"
#include "expression.h"
#include "value.h"
#include "language.h"
#include "terminal.h"
#include "annotate.h"
#include "completer.h"
#include "top.h"
#include "version.h"
#include "serial.h"
#include "doublest.h"
#include "gdb_assert.h"
#include "main.h"
#include "event-loop.h"
#include "gdbthread.h"
#include "python/python.h"
#include "interps.h"
#include "observer.h"
#include "maint.h"
#include "filenames.h"
#include "readline/readline.h"
#include "readline/history.h"
#include <sys/types.h>
#include "event-top.h"
#include "gdb_string.h"
#include "gdb_stat.h"
#include <ctype.h>
#include "ui-out.h"
#include "cli-out.h"
#include "tracepoint.h"
Classes
struct gdb_readline_wrapper_cleanup
struct qt_args
Defines
#define PROMPT(X) the_prompts.prompt_stack[the_prompts.top + X].prompt
#define PREFIX(X) the_prompts.prompt_stack[the_prompts.top + X].prefix
#define SUFFIX(X) the_prompts.prompt_stack[the_prompts.top + X].suffix
#define DEFAULT_PROMPT "(gdb) "
#define SERVER_COMMAND_LENGTH 7
#define DO_TRY TRY_CATCH (ex, RETURN_MASK_ALL)
#define DO_PRINT_EX
#define Hist_print 10
Functions
void initialize_all_files (void)
static void show_confirm (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
void do_restore_instream_cleanup (void *stream)
void read_command_file (FILE *stream)
struct cleanup * prepare_execute_command (void)
void check_frame_language_change (void)
void execute_command (char *p, int from_tty)
char * execute_command_to_string (char *p, int from_tty)
void command_loop (void)
void dont_repeat (void)
struct cleanup * prevent_dont_repeat (void)
char * gdb_readline (char *prompt_arg)
static void show_write_history_p (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static void show_history_size (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static void show_history_filename (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static void gdb_readline_wrapper_line (char *line)
static void gdb_readline_wrapper_cleanup (void *arg)
char * gdb_readline_wrapper (char *prompt)
static void gdb_rl_operate_and_get_next_completion (void)
static int gdb_rl_operate_and_get_next (int count, int key)
char * command_line_input (char *prompt_arg, int repeat, char *annotation_suffix)
void print_gdb_version (struct ui_file *stream)
void print_gdb_configuration (struct ui_file *stream)
char * get_prompt (void)
void set_prompt (const char *s)
static int kill_or_detach (struct inferior *inf, void *args)
static int print_inferior_quit_action (struct inferior *inf, void *arg)
int quit_confirm (void)
void quit_force (char *args, int from_tty)
int input_from_terminal_p (void)
static void dont_repeat_command (char *ignored, int from_tty)
void show_commands (char *args, int from_tty)
static void set_history_size_command (char *args, int from_tty, struct cmd_list_element *c)
void set_history (char *args, int from_tty)
void show_history (char *args, int from_tty)
void set_verbose (char *args, int from_tty, struct cmd_list_element *c)
void init_history (void)
static void show_prompt (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static void show_async_command_editing_p (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static void show_annotation_level (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static void show_exec_done_display_p (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static void set_gdb_datadir (char *args, int from_tty, struct cmd_list_element *c)
static void set_history_filename (char *args, int from_tty, struct cmd_list_element *c)
static void init_main (void)
void gdb_init (char *argv0)
Variables
const char gdbinit [] = GDBINIT
int inhibit_gdbinit = 0
int use_windows = 0
char lang_frame_mismatch_warn []
int confirm = 1
FILE * instream
int in_user_command
char * current_directory
char gdb_dirbuf [1024]
void(* window_hook)(FILE *, char *)
char * saved_command_line
int saved_command_line_size = 100
int server_command
int remote_timeout = 2
int remote_debug = 0
void(* deprecated_init_ui_hook)(char *argv0)
int(* deprecated_ui_loop_hook)(int)
void(* deprecated_print_frame_info_listing_hook)(struct symtab *s, int line, int stopline, int noerror)
int(* deprecated_query_hook)(const char *, va_list)
void(* deprecated_warning_hook)(const char *, va_list)
void(* deprecated_readline_begin_hook)(char *,...)
char *(* deprecated_readline_hook)(char *)
void(* deprecated_readline_end_hook)(void)
void(* deprecated_attach_hook)(void)
void(* deprecated_detach_hook)(void)
void(* deprecated_interactive_hook)(void)
void(* deprecated_register_changed_hook)(int regno)
ptid_t(* deprecated_target_wait_hook)(ptid_t ptid, struct target_waitstatus *status, int options)
void(* deprecated_call_command_hook)(struct cmd_list_element *c, char *cmd, int from_tty)
void(* deprecated_set_hook)(struct cmd_list_element *c)
void(* deprecated_context_hook)(int id)
int source_line_number
const char * source_file_name
void(* pre_init_ui_hook)(void)
static int suppress_dont_repeat = 0
static int command_editing_p
int history_expansion_p
static int write_history_p
static unsigned int history_size_setshow_var
static char * history_filename
static int gdb_readline_wrapper_done
static char * gdb_readline_wrapper_result
static void(* saved_after_char_processing_hook)(void)
static int operate_saved_history = -1
static char * top_prompt
int info_verbose = 0
Define Documentation
#define DEFAULT_PROMPT "(gdb) "
Definition at line 79 of file top.c.
Referenced by init_main().
#define DO_PRINT_EX
Value:
if (ex.reason < 0) \
    exception_print (gdb_stderr, ex)
Referenced by quit_force().
#define DO_TRY TRY_CATCH (ex, RETURN_MASK_ALL)
Referenced by quit_force().
#define Hist_print 10
Definition at line 1463 of file top.c.
Referenced by show_commands().
#define PREFIX (X) the_prompts.prompt_stack[the_prompts.top + X].prefix
Definition at line 73 of file top.c.
#define PROMPT (X) the_prompts.prompt_stack[the_prompts.top + X].prompt
Definition at line 72 of file top.c.
#define SERVER_COMMAND_LENGTH 7
#define SUFFIX (X) the_prompts.prompt_stack[the_prompts.top + X].suffix
Definition at line 74 of file top.c.
Function Documentation
void check_frame_language_change (void)
Definition at line 348 of file top.c.
References current_language, deprecated_safe_get_selected_frame(), expected_language, get_frame_language(), has_stack_frames(), info_verbose, language_defn::la_language, lang_frame_mismatch_warn, language_info(), language_mode_auto, language_unknown, and printf_filtered().
Referenced by execute_command(), and inferior_event_handler().
char* command_line_input (char * prompt_arg, int repeat, char * annotation_suffix)
Definition at line 887 of file top.c.
References annotation_level, command_editing_p, command_line_input(), deprecated_readline_hook, gdb_flush(), gdb_readline(), gdb_readline_wrapper(), gdb_stderr, gdb_stdout, history_expansion_p, immediate_quit, input_from_terminal_p(), instream, job_control, p, printf_unfiltered(), puts_unfiltered(), QUIT, saved_command_line, saved_command_line_size, server_command, SERVER_COMMAND_LENGTH, source_file_name, source_line_number, wrap_here(), xfree(), xmalloc(), and xrealloc().
Referenced by command_line_input(), command_loop(), decode_line_2(), gdbpy_readline_wrapper(), get_selections(), and read_next_line().
void command_loop (void)
Definition at line 542 of file top.c.
References bpstat_do_actions(), clear_quit_flag(), command_line_input(), do_cleanups(), execute_command(), get_prompt(), instream, make_cleanup(), make_command_stats_cleanup(), null_cleanup(), reinitialize_more_filter(), and window_hook.
Referenced by read_command_file().
void do_restore_instream_cleanup (void * stream)
Definition at line 296 of file top.c.
References instream.
Referenced by execute_user_command(), and read_command_file().
void dont_repeat (void)
Definition at line 587 of file top.c.
References instream, saved_command_line, server_command, and suppress_dont_repeat.
Referenced by add_symbol_file_command(), agent_command_1(), agent_eval_command_one(), attach_command(), auto_load_info_scripts(), cd_command(), cmd_record_call_history(), cmd_record_insn_history(), cmdpy_dont_repeat(), complete_command(), core_file_command(), delete_command(), delete_trace_command(), delete_trace_variable_command(), detach_command(), directory_command(), disconnect_command(), display_command(), dll_symbol_command(), interrupt_target_command(), line_info(), load_command(), maint_agent_printf_command(), maintenance_info_symtabs(), maintenance_print_msymbols(), maintenance_print_objfiles(), maintenance_print_psymbols(), maintenance_print_symbols(), mem_delete_command(), mi_cmd_env_dir(), mi_cmd_env_path(), path_command(), prompt_for_continue(), read_command_lines_1(), recurse_read_control_structure(), run_command_1(), save_bookmark_command(), sharedlibrary_command(), signal_command(), symbol_file_command(), target_preopen(), trace_start_command(), tui_handle_resize_during_io(), tui_rl_switch_mode(), and undisplay_command().
static void dont_repeat_command (char * ignored, int from_tty) [static]
Definition at line 1453 of file top.c.
References saved_command_line.
Referenced by init_main().
void execute_command (char * p, int from_tty)
Definition at line 389 of file top.c.
References _, check_frame_language_change(), cmd_list_element::class, class_user, cmd_func(), cmd_func_p(), cmdlist, deprecated_call_command_hook, deprecated_cmd_warning(), DEPRECATED_WARN_USER, discard_cleanups(), do_cleanups(), do_set_command(), do_show_command(), error(), execute_cmd_post_hook(), execute_cmd_pre_hook(), execute_user_command(), cmd_list_element::flags, gdb_do_one_event(), interpreter_async, is_complete_command(), line, lookup_cmd(), make_bpstat_clear_actions_cleanup(), prepare_execute_command(), print_command_trace(), set_cmd, show_cmd, sync_execution, target_log_command, cmd_list_element::type, and cmd_list_element::user_commands.
Referenced by captured_main(), cmd_record_btrace_start(), cmd_record_full_start(), cmd_record_start(), command_handler(), command_loop(), env_execute_cli_command(), eval_command(), exec_reverse_once(), execute_command_to_string(), execute_control_command(), gdb_cmd(), gdb_immediate_command(), mi_execute_async_cli_command(), mi_execute_cli_command(), nto_init_solib_absolute_prefix(), safe_execute_command(), thread_apply_all_command(), thread_apply_command(), tui_update_command(), and tui_update_gdb_sizes().
char* execute_command_to_string (char * p, int from_tty)
Definition at line 496 of file top.c.
References _, current_uiout, do_cleanups(), execute_command(), gdb_stderr, gdb_stdlog, gdb_stdout, gdb_stdtarg, gdb_stdtargerr, interpreter_async, make_cleanup_restore_integer(), make_cleanup_restore_ui_file(), make_cleanup_ui_file_delete(), make_cleanup_ui_out_redirect_pop(), mem_fileopen(), set_batch_flag_and_make_cleanup_restore_page_info(), ui_file_xstrdup(), ui_out_redirect(), and warning().
void gdb_init (char * argv0)
Definition at line 1814 of file top.c.
References async_init_signals(), current_directory, current_language, deprecated_init_ui_hook, expected_language, finish_python_initialization(), init_cli_cmds(), init_cmd_lists(), init_main(), initialize_all_files(), initialize_current_architecture(), initialize_event_loop(), initialize_inferiors(), initialize_progspace(), initialize_stdin_serial(), initialize_targets(), initialize_utils(), language_c, make_final_cleanup(), pre_init_ui_hook, and set_language().
Referenced by captured_main().
char* gdb_readline (char * prompt_arg)
Definition at line 620 of file top.c.
References fputs_unfiltered(), gdb_flush(), gdb_stdout, instream, xfree(), xmalloc(), and xrealloc().
Referenced by command_line_input().
char* gdb_readline_wrapper (char * prompt)
Definition at line 792 of file top.c.
References after_char_processing_hook, gdb_readline_wrapper_cleanup::already_prompted_orig, display_gdb_prompt(), do_cleanups(), gdb_assert, gdb_do_one_event(), gdb_readline_wrapper_done, gdb_readline_wrapper_line(), gdb_readline_wrapper_result, gdb_readline_wrapper_cleanup::handler_orig, input_handler, make_cleanup(), and xmalloc().
Referenced by command_line_input(), and prompt_for_continue().
static void gdb_readline_wrapper_cleanup (void * arg) [static]
Definition at line 774 of file top.c.
References after_char_processing_hook, gdb_readline_wrapper_cleanup::already_prompted_orig, gdb_assert, gdb_readline_wrapper_done, gdb_readline_wrapper_line(), gdb_readline_wrapper_result, gdb_readline_wrapper_cleanup::handler_orig, input_handler, saved_after_char_processing_hook, and xfree().
static void gdb_readline_wrapper_line (char * line) [static]
Definition at line 751 of file top.c.
References after_char_processing_hook, async_command_editing_p, gdb_assert, gdb_readline_wrapper_done, gdb_readline_wrapper_result, line, and saved_after_char_processing_hook.
Referenced by gdb_readline_wrapper(), and gdb_readline_wrapper_cleanup().
static int gdb_rl_operate_and_get_next (int count, int key) [static]
Definition at line 852 of file top.c.
References after_char_processing_hook, gdb_rl_operate_and_get_next_completion(), and operate_saved_history.
Referenced by init_main().
static void gdb_rl_operate_and_get_next_completion (void) [static]
Definition at line 831 of file top.c.
References after_char_processing_hook, and operate_saved_history.
Referenced by gdb_rl_operate_and_get_next().
char* get_prompt (void)
Definition at line 1255 of file top.c.
References top_prompt.
Referenced by command_loop(), gdb_prompt_command(), and top_level_prompt().
void init_history (void)
Definition at line 1599 of file top.c.
References current_directory, history_filename, history_size_setshow_var, and cmd_list_element::var.
Referenced by captured_main().
static void init_main (void) [static]
Definition at line 1699 of file top.c.
References _, add_com(), add_setshow_boolean_cmd(), add_setshow_filename_cmd(), add_setshow_string_cmd(), add_setshow_uinteger_cmd(), add_setshow_zinteger_cmd(), annotation_level, async_annotation_suffix, async_command_editing_p, class_maintenance, class_obscure, class_support, command_editing_p, confirm, DEFAULT_PROMPT, default_word_break_characters(), dont_repeat_command(), exec_done_display_p, gdb_completion_word_break_characters(), gdb_datadir, gdb_rl_operate_and_get_next(), get_gdb_completer_quote_characters(), history_expansion_p, history_filename, history_size_setshow_var, no_class, readline_line_completion_function(), set_async_editing_command(), set_gdb_datadir(), set_history_filename(), set_history_size_command(), set_prompt(), sethistlist, setlist, show_annotation_level(), show_async_command_editing_p(), show_confirm(), show_exec_done_display_p(), show_history_filename(), show_history_size(), show_prompt(), show_write_history_p(), showhistlist, showlist, top_prompt, and write_history_p.
Referenced by gdb_init().
void initialize_all_files (void)
Definition at line 255 of file init.c.
References _initialize_ada_language, _initialize_addrmap, _initialize_agent, _initialize_annotate, _initialize_arm_linux_tdep, _initialize_arm_netbsd_tdep, _initialize_arm_symbian_tdep, _initialize_arm_tdep, _initialize_arm_wince_tdep, _initialize_armobsd_tdep, _initialize_auto_load, _initialize_auxv, _initialize_avr_tdep, _initialize_ax_gdb, _initialize_bfin_linux_tdep, _initialize_bfin_tdep, _initialize_break_catch_sig, _initialize_break_catch_throw, _initialize_breakpoint, _initialize_bsd_uthread, _initialize_c_language, _initialize_charset, _initialize_cli_cmds, _initialize_cli_dump, _initialize_cli_interp, _initialize_cli_logging, _initialize_cli_script, _initialize_coff_pe_read, _initialize_coffread, _initialize_complaints, _initialize_copying, _initialize_core, _initialize_corelow, _initialize_cp_abi, _initialize_cp_namespace, _initialize_cp_support, _initialize_cp_valprint, _initialize_cris_linux_tdep, _initialize_cris_tdep, _initialize_ctf, _initialize_d_language, _initialize_darwin_solib, _initialize_dbug_rom, _initialize_dbxread, _initialize_dcache, _initialize_demangler, _initialize_dink32_rom, _initialize_dsbt_solib, _initialize_dummy_frame, _initialize_dwarf2_frame, _initialize_dwarf2_read, _initialize_dwarf2expr, _initialize_dwarf2loc, _initialize_elfread, _initialize_exec, _initialize_f_language, _initialize_f_valprint, _initialize_filesystem, _initialize_fork_child, _initialize_frame, _initialize_frame_base, _initialize_frame_reg, _initialize_frame_unwind, _initialize_frv_linux_tdep, _initialize_frv_solib, _initialize_frv_tdep, _initialize_gcore, _initialize_gdb_bfd, _initialize_gdb_osabi, _initialize_gdbarch, _initialize_gdbarch_utils, _initialize_gdbtk, _initialize_gdbtk_interp, _initialize_gdbtypes, _initialize_gnu_v2_abi, _initialize_gnu_v3_abi, _initialize_go_language, _initialize_h8300_tdep, _initialize_hppa_hpux_tdep, _initialize_hppa_linux_tdep, _initialize_hppa_tdep, _initialize_hppabsd_tdep, _initialize_hppanbsd_tdep, _initialize_i386_cygwin_tdep, _initialize_i386_darwin_tdep, _initialize_i386_dicos_tdep, _initialize_i386_linux_nat, _initialize_i386_linux_tdep, _initialize_i386_sol2_tdep, _initialize_i386_tdep, _initialize_i386bsd_tdep, _initialize_i386fbsd_tdep, _initialize_i386gnu_tdep, _initialize_i386nbsd_tdep, _initialize_i386nto_tdep, _initialize_i386obsd_tdep, _initialize_infcall, _initialize_infcmd, _initialize_inflow, _initialize_infrun, _initialize_interpreter, _initialize_iq2000_tdep, _initialize_irix_solib, _initialize_java_language, _initialize_jit, _initialize_language, _initialize_linux_fork, _initialize_linux_nat, _initialize_linux_tdep, _initialize_lm32_tdep, _initialize_m2_language, _initialize_m32c_tdep, _initialize_m32r_linux_tdep, _initialize_m32r_rom, _initialize_m32r_tdep, _initialize_m68hc11_tdep, _initialize_m68k_linux_tdep, _initialize_m68k_tdep, _initialize_m68kbsd_tdep, _initialize_m88k_tdep, _initialize_macrocmd, _initialize_macroscope, _initialize_maint_cmds, _initialize_mdebugread, _initialize_mem, _initialize_mem_search, _initialize_mep_tdep, _initialize_mi_cmd_env, _initialize_mi_cmds, _initialize_mi_interp, _initialize_microblaze_linux_tdep, _initialize_microblaze_tdep, _initialize_mips_irix_tdep, _initialize_mips_linux_tdep, _initialize_mips_tdep, _initialize_mipsnbsd_tdep, _initialize_mipsread, _initialize_mn10300_linux_tdep, _initialize_mn10300_tdep, _initialize_moxie_tdep, _initialize_msp430_tdep, _initialize_mt_tdep, _initialize_nios2_linux_tdep, _initialize_nios2_tdep, _initialize_notif, _initialize_objc_lang, _initialize_objc_language, _initialize_objfiles, _initialize_observer, _initialize_opencl_language, _initialize_osdata, _initialize_pa64_solib, _initialize_parse, _initialize_pascal_language, _initialize_pascal_valprint, _initialize_ppc_linux_tdep, _initialize_ppcbug_rom, _initialize_ppcfbsd_tdep, _initialize_ppcnbsd_tdep, _initialize_ppcobsd_tdep, _initialize_printcmd, _initialize_probe, _initialize_proc_service, _initialize_psymtab, _initialize_python, _initialize_ravenscar, _initialize_record, _initialize_record_btrace, _initialize_record_full, _initialize_regcache, _initialize_reggroup, _initialize_remote, _initialize_remote_m32r, _initialize_remote_mips, _initialize_remote_monitors, _initialize_reverse, _initialize_rl78_tdep, _initialize_rs6000_aix_tdep, _initialize_rs6000_lynx178_tdep, _initialize_rs6000_tdep, _initialize_rx_tdep, _initialize_s390_tdep, _initialize_score_tdep, _initialize_ser_hardwire, _initialize_ser_pipe, _initialize_ser_tcp, _initialize_serial, _initialize_sh_linux_tdep, _initialize_sh_tdep, _initialize_shnbsd_tdep, _initialize_solib, _initialize_solib_aix, _initialize_solib_target, _initialize_som_solib, _initialize_source, _initialize_sparc32obsd_tdep, _initialize_sparc_linux_tdep, _initialize_sparc_sol2_tdep, _initialize_sparc_tdep, _initialize_sparcnbsd_tdep, _initialize_spu_multiarch, _initialize_spu_solib, _initialize_spu_tdep, _initialize_stabsread, _initialize_stack, _initialize_stap_probe, _initialize_step_skip, _initialize_svr4_solib, _initialize_symfile, _initialize_symfile_debug, _initialize_symfile_mem, _initialize_symmisc, _initialize_symtab, _initialize_tailcall_frame, _initialize_target_descriptions, _initialize_tasks, _initialize_thread, _initialize_thread_db, _initialize_tic6x_linux_tdep, _initialize_tic6x_tdep, _initialize_tilegx_linux_tdep, _initialize_tilegx_tdep, _initialize_tracepoint, _initialize_tui_hooks, _initialize_tui_interp, _initialize_tui_layout, _initialize_tui_out, _initialize_tui_regs, _initialize_tui_stack, _initialize_tui_win, _initialize_typeprint, _initialize_ui_out, _initialize_user_regs, _initialize_utils, _initialize_v850_tdep, _initialize_valarith, _initialize_valops, _initialize_valprint, _initialize_values, _initialize_varobj, _initialize_vax_tdep, _initialize_vaxnbsd_tdep, _initialize_vaxobsd_tdep, _initialize_windows_tdep, _initialize_xcoffread, _initialize_xml_support, _initialize_xstormy16_tdep, _initialize_xtensa_linux_tdep, and _initialize_xtensa_tdep.
Referenced by gdb_init().
int input_from_terminal_p (void)
Definition at line 1435 of file top.c.
References batch_flag, gdb_has_a_terminal(), in_user_command, and instream.
Referenced by ATTRIBUTE_PRINTF(), command_line_input(), quit_force(), and read_command_lines().
static int kill_or_detach (struct inferior * inf, void * args) [static]
Definition at line 1282 of file top.c.
References any_thread_of_process(), qt_args::args, inferior::attach_flag, qt_args::from_tty, inferior::pid, thread_info::ptid, switch_to_thread(), target_detach(), target_has_execution, and target_kill().
Referenced by quit_force().
struct cleanup* prepare_execute_command (void) [read]
Definition at line 326 of file top.c.
References make_cleanup_value_free_to_mark(), non_stop, target_dcache_invalidate(), and value_mark().
Referenced by execute_command(), and mi_cmd_execute().
struct cleanup* prevent_dont_repeat (void) [read]
Definition at line 603 of file top.c.
References make_cleanup_restore_integer(), and suppress_dont_repeat.
Referenced by bpstat_do_actions_1().
void print_gdb_configuration (struct ui_file * stream)
Definition at line 1149 of file top.c.
References _, AUTO_LOAD_DIR, AUTO_LOAD_SAFE_PATH, DEBUGDIR, DEBUGDIR_RELOCATABLE, fprintf_filtered(), GDB_DATADIR, GDB_DATADIR_RELOCATABLE, host_name, JIT_READER_DIR, JIT_READER_DIR_RELOCATABLE, SYSTEM_GDBINIT, SYSTEM_GDBINIT_RELOCATABLE, target_name, TARGET_SYSTEM_ROOT, and TARGET_SYSTEM_ROOT_RELOCATABLE.
Referenced by captured_main(), and show_configuration().
void print_gdb_version (struct ui_file * stream)
Definition at line 1094 of file top.c.
References _, fprintf_filtered(), host_name, PKGVERSION, REPORT_BUGS_TO, target_name, and version.
Referenced by captured_main(), and show_version().
static int print_inferior_quit_action (struct inferior * inf, void * arg) [static]
Definition at line 1313 of file top.c.
References _, inferior::attach_flag, fprintf_filtered(), inferior::num, inferior::pid, pid_to_ptid(), and target_pid_to_str().
Referenced by quit_confirm().
int quit_confirm (void)
Definition at line 1336 of file top.c.
References _, do_cleanups(), fprintf_filtered(), have_live_inferiors(), iterate_over_inferiors(), make_cleanup(), make_cleanup_ui_file_delete(), mem_fileopen(), print_inferior_quit_action(), query(), ui_file_xstrdup(), and xfree().
Referenced by gdb_confirm_quit(), and quit_command().
void quit_force (char * args, int from_tty)
Definition at line 1366 of file top.c.
References all_cleanups(), qt_args::args, disconnect_tracing(), do_final_cleanups(), DO_PRINT_EX, DO_TRY, qt_args::from_tty, history_filename, input_from_terminal_p(), int, iterate_over_inferiors(), kill_or_detach(), parse_and_eval(), pop_all_targets(), return_child_result, return_child_result_value, value_as_long(), and write_history_p.
Referenced by captured_main(), gdb_force_quit(), handle_sigterm(), mi_cmd_gdb_exit(), mi_execute_command(), and quit_command().
void read_command_file (FILE * stream)
Definition at line 304 of file top.c.
References command_loop(), do_cleanups(), do_restore_instream_cleanup(), instream, and make_cleanup().
Referenced by script_from_file().
static void set_gdb_datadir (char * args, int from_tty, struct cmd_list_element * c) [static]
Definition at line 1682 of file top.c.
References observer_notify_gdb_datadir_changed().
Referenced by init_main().
void set_history (char * args, int from_tty)
Definition at line 1556 of file top.c.
References _, gdb_stdout, help_list(), printf_unfiltered(), and sethistlist.
Referenced by _initialize_cli_cmds().
static void set_history_filename (char * args, int from_tty, struct cmd_list_element * c) [static]
Definition at line 1688 of file top.c.
References current_directory, and history_filename.
Referenced by init_main().
static void set_history_size_command (char * args, int from_tty, struct cmd_list_element * c) [static]
Definition at line 1527 of file top.c.
References _, error(), and history_size_setshow_var.
Referenced by init_main().
void set_prompt (const char * s)
Definition at line 1263 of file top.c.
References p, top_prompt, and xfree().
Referenced by init_main().
void set_verbose (char * args, int from_tty, struct cmd_list_element * c)
Definition at line 1573 of file top.c.
References CMD_LIST_AMBIGUOUS, cmd_list_element::doc, gdb_assert, info_verbose, lookup_cmd_1(), and showlist.
Referenced by _initialize_cli_cmds().
static void show_annotation_level (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 1664 of file top.c.
References _, and fprintf_filtered().
Referenced by init_main().
static void show_async_command_editing_p (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 1655 of file top.c.
References _, and fprintf_filtered().
Referenced by init_main().
void show_commands (char * args, int from_tty)
Definition at line 1465 of file top.c.
References Hist_print, line, offset, parse_and_eval_long(), and printf_filtered().
Referenced by _initialize_cli_cmds().
static void show_confirm (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 101 of file top.c.
References _, and fprintf_filtered().
Referenced by init_main().
static void show_exec_done_display_p (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 1671 of file top.c.
References _, and fprintf_filtered().
Referenced by init_main().
void show_history (char * args, int from_tty)
Definition at line 1564 of file top.c.
References cmd_show_list(), and showhistlist.
Referenced by _initialize_cli_cmds().
static void show_history_filename (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 708 of file top.c.
References _, and fprintf_filtered().
Referenced by init_main().
static void show_history_size (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 699 of file top.c.
References _, and fprintf_filtered().
Referenced by init_main().
static void show_prompt (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 1648 of file top.c.
References _, and fprintf_filtered().
Referenced by init_main().
static void show_write_history_p (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 687 of file top.c.
References _, and fprintf_filtered().
Referenced by init_main().
Variable Documentation
int command_editing_p [static]
Definition at line 677 of file top.c.
Referenced by command_line_input(), and init_main().
int confirm = 1
Definition at line 98 of file top.c.
Referenced by ATTRIBUTE_PRINTF(), and init_main().
char* current_directory
Definition at line 122 of file top.c.
Referenced by add_path(), bsd_kvm_open(), captured_main(), cd_command(), core_open(), gdb_init(), Gdbtk_Init(), go32_wait(), init_history(), m32r_upload_command(), openp(), pwd_command(), set_history_filename(), shell_escape(), and tfile_open().
void(* deprecated_attach_hook)(void)
Definition at line 229 of file top.c.
Referenced by attach_command_post_wait(), and gdbtk_add_hooks().
void(* deprecated_call_command_hook)(struct cmd_list_element *c, char *cmd, int from_tty)
Definition at line 252 of file top.c.
Referenced by clear_interpreter_hooks(), execute_command(), and gdbtk_add_hooks().
void(* deprecated_context_hook)(int id)
Definition at line 262 of file top.c.
Referenced by clear_interpreter_hooks(), gdbtk_add_hooks(), and handle_inferior_event().
void(* deprecated_detach_hook)(void)
Definition at line 230 of file top.c.
Referenced by detach_command(), disconnect_command(), gdbtk_add_hooks(), and generic_mourn_inferior().
void(* deprecated_init_ui_hook)(char *argv0)
Definition at line 186 of file top.c.
Referenced by _initialize_windows_nat(), clear_interpreter_hooks(), and gdb_init().
void(* deprecated_interactive_hook)(void)
Definition at line 235 of file top.c.
Referenced by clear_interpreter_hooks(), and gdbtk_add_hooks().
void(* deprecated_print_frame_info_listing_hook)(struct symtab *s, int line, int stopline, int noerror)
Definition at line 198 of file top.c.
Referenced by clear_interpreter_hooks(), gdbtk_add_hooks(), print_frame_info(), tui_install_hooks(), and tui_remove_hooks().
int(* deprecated_query_hook)(const char *, va_list)
Definition at line 204 of file top.c.
Referenced by ATTRIBUTE_PRINTF(), clear_interpreter_hooks(), gdbtk_add_hooks(), mi_insert_notify_hooks(), mi_remove_notify_hooks(), tui_install_hooks(), and tui_remove_hooks().
void(* deprecated_readline_begin_hook)(char *,...)
Definition at line 222 of file top.c.
Referenced by clear_interpreter_hooks(), gdbtk_add_hooks(), and read_command_lines().
void(* deprecated_readline_end_hook)(void)
Definition at line 224 of file top.c.
Referenced by clear_interpreter_hooks(), gdbtk_add_hooks(), and read_command_lines().
char*(* deprecated_readline_hook)(char *)
Definition at line 223 of file top.c.
Referenced by clear_interpreter_hooks(), command_line_input(), gdbtk_add_hooks(), and read_next_line().
void(* deprecated_register_changed_hook)(int regno)
Definition at line 240 of file top.c.
Referenced by clear_interpreter_hooks(), gdbtk_add_hooks(), tui_install_hooks(), tui_remove_hooks(), and value_assign().
void(* deprecated_set_hook)(struct cmd_list_element *c)
Definition at line 258 of file top.c.
Referenced by do_set_command(), and gdbtk_add_hooks().
ptid_t(* deprecated_target_wait_hook)(ptid_t ptid, struct target_waitstatus *status, int options)
Definition at line 245 of file top.c.
Referenced by clear_interpreter_hooks(), fetch_inferior_event(), gdbtk_add_hooks(), prepare_for_detach(), and wait_for_inferior().
int(* deprecated_ui_loop_hook)(int)
Definition at line 193 of file top.c.
Referenced by do_hardwire_readchar(), do_ser_base_readchar(), gdb_os_poll_quit(), gdbtk_add_hooks(), wait_for_connect(), and windows_wait().
void(* deprecated_warning_hook)(const char *, va_list)
Definition at line 208 of file top.c.
Referenced by clear_interpreter_hooks(), gdbtk_add_hooks(), and vwarning().
char gdb_dirbuf[1024]
Definition at line 125 of file top.c.
Referenced by captured_main(), cd_command(), mi_cmd_env_pwd(), and pwd_command().
int gdb_readline_wrapper_done [static]
Definition at line 733 of file top.c.
Referenced by gdb_readline_wrapper(), gdb_readline_wrapper_cleanup(), and gdb_readline_wrapper_line().
char* gdb_readline_wrapper_result [static]
Definition at line 737 of file top.c.
Referenced by gdb_readline_wrapper(), gdb_readline_wrapper_cleanup(), and gdb_readline_wrapper_line().
const char gdbinit[] = GDBINIT
Definition at line 84 of file top.c.
Referenced by file_is_auto_load_safe(), get_init_files(), and init_cli_cmds().
int history_expansion_p
Definition at line 683 of file top.c.
Referenced by _initialize_cli_cmds(), command_line_handler(), command_line_input(), and init_main().
char* history_filename [static]
Definition at line 706 of file top.c.
Referenced by init_history(), init_main(), quit_force(), and set_history_filename().
unsigned int history_size_setshow_var [static]
Definition at line 696 of file top.c.
Referenced by init_history(), init_main(), and set_history_size_command().
int in_user_command
Definition at line 118 of file top.c.
Referenced by do_restore_user_call_depth(), execute_user_command(), and input_from_terminal_p().
int info_verbose = 0
Definition at line 1569 of file top.c.
Referenced by _initialize_cli_cmds(), add_memrange(), add_register(), add_static_trace_data(), backtrace_command_1(), check_frame_language_change(), checkpoint_command(), close_with_trace(), collect_symbol(), dbx_psymtab_to_symtab_1(), dbx_read_symtab(), dwarf2_read_symtab(), encode_actions_1(), fbsd_find_memory_regions(), gcore_command(), gcore_create_callback(), handle_vfork_child_exec_or_exit(), ioctl_with_trace(), linux_child_follow_fork(), lm_addr_check(), map_overlay_command(), mdebug_read_symtab(), merge_uploaded_trace_state_variables(), open_with_trace(), overlay_auto_command(), overlay_manual_command(), overlay_off_command(), parse_external(), post_create_inferior(), print_section_info(), procfs_note(), procfs_wait(), psymtab_to_symtab_1(), remote_resume(), restore_command(), set_verbose(), show_info_verbose(), sol_thread_resume(), sol_thread_wait(), solib_add(), solib_read_symbols(), stringify_collection_list(), svr4_exec_displacement(), symbol_file_add_with_addrs(), tfind_1(), wait_with_trace(), windows_delete_thread(), xcoff_psymtab_to_symtab_1(), and xcoff_read_symtab().
int inhibit_gdbinit = 0
Definition at line 86 of file top.c.
Referenced by _initialize_check_for_gdb_ini(), captured_main(), and gdbtk_init().
FILE* instream
Definition at line 114 of file top.c.
Referenced by captured_command_loop(), captured_main(), command_handler(), command_line_handler(), command_line_input(), command_loop(), do_restore_instream_cleanup(), dont_repeat(), execute_user_command(), gdb_readline(), gdb_readline2(), gdb_setup_readline(), gdbtk_command_loop(), handle_sigterm(), input_from_terminal_p(), mi_execute_command_wrapper(), read_command_file(), read_next_line(), and stdin_event_handler().
char lang_frame_mismatch_warn[]
Definition at line 110 of file language.c.
Referenced by check_frame_language_change(), and show_language_command().
int operate_saved_history = -1 [static]
Definition at line 826 of file top.c.
Referenced by gdb_rl_operate_and_get_next(), and gdb_rl_operate_and_get_next_completion().
void(* pre_init_ui_hook)(void)
Definition at line 314 of file top.c.
Referenced by gdb_init().
int remote_debug = 0
Definition at line 171 of file top.c.
Referenced by _initialize_cli_cmds(), async_remote_interrupt(), async_remote_interrupt_twice(), check_binary_download(), gdb_cntrl_c(), gdbsim_close(), gdbsim_create_inferior(), gdbsim_detach(), gdbsim_fetch_register(), gdbsim_files_info(), gdbsim_kill(), gdbsim_load(), gdbsim_mourn_inferior(), gdbsim_open(), gdbsim_resume_inferior(), gdbsim_store_register(), gdbsim_wait(), gdbsim_xfer_memory(), getpkt_or_notif_sane_1(), load_srec(), m32r_close(), m32r_create_inferior(), m32r_detach(), m32r_fetch_register(), m32r_insert_breakpoint(), m32r_insert_watchpoint(), m32r_kill(), m32r_mourn_inferior(), m32r_open(), m32r_prepare_to_store(), m32r_remove_breakpoint(), m32r_remove_watchpoint(), m32r_resume(), m32r_stop(), m32r_store_register(), m32r_wait(), m32r_xfer_memory(), mips_expect_timeout(), mips_kill(), mips_readchar(), mips_receive_header(), mips_receive_packet(), monitor_interrupt(), monitor_read_memory(), monitor_wait(), monitor_wait_filter(), packet_ok(), putpkt_binary(), read_frame(), readchar(), remote_stop(), sdireset_command(), sdistatus_command(), and send_g_packet().
int remote_timeout = 2
Definition at line 167 of file top.c.
Referenced by _initialize_cli_cmds(), captured_main(), getpkt_or_notif_sane_1(), mips_expect(), pmon_check_ack(), pmon_check_entry_address(), putpkt_binary(), read_frame(), remote_flash_done(), remote_flash_erase(), remote_flash_write(), restore_remote_timeout(), send_srec(), and skip_frame().
void(* saved_after_char_processing_hook)(void) [static]
Definition at line 745 of file top.c.
Referenced by gdb_readline_wrapper_cleanup(), and gdb_readline_wrapper_line().
char* saved_command_line
Definition at line 136 of file top.c.
Referenced by captured_main(), command_line_handler(), command_line_input(), dont_repeat(), and dont_repeat_command().
int saved_command_line_size = 100
Definition at line 137 of file top.c.
Referenced by captured_main(), command_line_handler(), and command_line_input().
int server_command
Definition at line 145 of file top.c.
Referenced by ATTRIBUTE_PRINTF(), breakpoint_1(), command_line_handler(), command_line_input(), and dont_repeat().
const char* source_file_name
Definition at line 290 of file top.c.
Referenced by command_line_handler(), command_line_input(), script_from_file(), and source_cleanup_lines().
int source_line_number
Definition at line 284 of file top.c.
Referenced by command_line_handler(), command_line_input(), script_from_file(), and source_cleanup_lines().
int suppress_dont_repeat = 0 [static]
Definition at line 582 of file top.c.
Referenced by dont_repeat(), and prevent_dont_repeat().
char* top_prompt [static]
Definition at line 1250 of file top.c.
Referenced by get_prompt(), init_main(), and set_prompt().
int use_windows = 0
Definition at line 91 of file top.c.
Referenced by captured_main(), and gdb_main().
void(* window_hook)(FILE *, char *)
Definition at line 131 of file top.c.
Referenced by command_loop().
int write_history_p [static]
Definition at line 685 of file top.c.
Referenced by init_main(), and quit_force().