GDB (xrefs): /home/stan/gdb/src/gdb/top.h File Reference
/home/stan/gdb/src/gdb/top.h File Reference
Functions
void print_gdb_version (struct ui_file *)
void print_gdb_configuration (struct ui_file *)
void read_command_file (FILE *)
void init_history (void)
void command_loop (void)
int quit_confirm (void)
void quit_force (char *, int)
void quit_command (char *, int)
void quit_cover (void)
void execute_command (char *, int)
void check_frame_language_change (void)
struct cleanup * prepare_execute_command (void)
char * get_prompt (void)
void set_prompt (const char *s)
void gdb_init (char *)
void show_commands (char *args, int from_tty)
void set_history (char *, int)
void show_history (char *, int)
void set_verbose (char *, int, struct cmd_list_element *)
void do_restore_instream_cleanup (void *stream)
Variables
char * saved_command_line
int saved_command_line_size
FILE * instream
int in_user_command
int confirm
char gdb_dirbuf [1024]
int inhibit_gdbinit
const char gdbinit []
int readnow_symbol_files
int source_line_number
const char * source_file_name
int history_expansion_p
int server_command
char * lim_at_start
Function Documentation
void check_frame_language_change (void)
Definition at line 348 of file top.c.
References current_language, deprecated_safe_get_selected_frame(), expected_language, get_frame_language(), has_stack_frames(), info_verbose, language_defn::la_language, lang_frame_mismatch_warn, language_info(), language_mode_auto, language_unknown, and printf_filtered().
Referenced by execute_command(), and inferior_event_handler().
void command_loop (void)
Definition at line 542 of file top.c.
References bpstat_do_actions(), clear_quit_flag(), command_line_input(), do_cleanups(), execute_command(), get_prompt(), instream, make_cleanup(), make_command_stats_cleanup(), null_cleanup(), reinitialize_more_filter(), and window_hook.
Referenced by read_command_file().
void do_restore_instream_cleanup (void * stream)
Definition at line 296 of file top.c.
References instream.
Referenced by execute_user_command(), and read_command_file().
void execute_command (char * , int)
Definition at line 389 of file top.c.
References _, check_frame_language_change(), cmd_list_element::class, class_user, cmd_func(), cmd_func_p(), cmdlist, deprecated_call_command_hook, deprecated_cmd_warning(), DEPRECATED_WARN_USER, discard_cleanups(), do_cleanups(), do_set_command(), do_show_command(), error(), execute_cmd_post_hook(), execute_cmd_pre_hook(), execute_user_command(), cmd_list_element::flags, gdb_do_one_event(), interpreter_async, is_complete_command(), line, lookup_cmd(), make_bpstat_clear_actions_cleanup(), prepare_execute_command(), print_command_trace(), set_cmd, show_cmd, sync_execution, target_log_command, cmd_list_element::type, and cmd_list_element::user_commands.
void gdb_init (char *)
Definition at line 1814 of file top.c.
References async_init_signals(), current_directory, current_language, deprecated_init_ui_hook, expected_language, finish_python_initialization(), init_cli_cmds(), init_cmd_lists(), init_main(), initialize_all_files(), initialize_current_architecture(), initialize_event_loop(), initialize_inferiors(), initialize_progspace(), initialize_stdin_serial(), initialize_targets(), initialize_utils(), language_c, make_final_cleanup(), pre_init_ui_hook, and set_language().
Referenced by captured_main().
char* get_prompt (void)
Definition at line 1255 of file top.c.
References top_prompt.
Referenced by command_loop(), gdb_prompt_command(), and top_level_prompt().
void init_history (void)
Definition at line 1599 of file top.c.
References current_directory, history_filename, history_size_setshow_var, and cmd_list_element::var.
Referenced by captured_main().
struct cleanup* prepare_execute_command (void) [read]
Definition at line 326 of file top.c.
References make_cleanup_value_free_to_mark(), non_stop, target_dcache_invalidate(), and value_mark().
Referenced by execute_command(), and mi_cmd_execute().
void print_gdb_configuration (struct ui_file *)
Definition at line 1149 of file top.c.
References _, AUTO_LOAD_DIR, AUTO_LOAD_SAFE_PATH, DEBUGDIR, DEBUGDIR_RELOCATABLE, fprintf_filtered(), GDB_DATADIR, GDB_DATADIR_RELOCATABLE, host_name, JIT_READER_DIR, JIT_READER_DIR_RELOCATABLE, SYSTEM_GDBINIT, SYSTEM_GDBINIT_RELOCATABLE, target_name, TARGET_SYSTEM_ROOT, and TARGET_SYSTEM_ROOT_RELOCATABLE.
Referenced by captured_main(), and show_configuration().
void print_gdb_version (struct ui_file *)
Definition at line 1094 of file top.c.
References _, fprintf_filtered(), host_name, PKGVERSION, REPORT_BUGS_TO, target_name, and version.
Referenced by captured_main(), and show_version().
void quit_command (char * , int)
Definition at line 323 of file cli-cmds.c.
References _, error(), query_if_trace_running(), quit_confirm(), and quit_force().
Referenced by _initialize_cli_cmds(), captured_command_loop(), and stdin_event_handler().
int quit_confirm (void)
Definition at line 1336 of file top.c.
References _, do_cleanups(), fprintf_filtered(), have_live_inferiors(), iterate_over_inferiors(), make_cleanup(), make_cleanup_ui_file_delete(), mem_fileopen(), print_inferior_quit_action(), query(), ui_file_xstrdup(), and xfree().
Referenced by gdb_confirm_quit(), and quit_command().
void quit_cover (void)
void quit_force (char * , int)
Definition at line 1366 of file top.c.
References all_cleanups(), qt_args::args, disconnect_tracing(), do_final_cleanups(), DO_PRINT_EX, DO_TRY, qt_args::from_tty, history_filename, input_from_terminal_p(), int, iterate_over_inferiors(), kill_or_detach(), parse_and_eval(), pop_all_targets(), return_child_result, return_child_result_value, value_as_long(), and write_history_p.
Referenced by captured_main(), gdb_force_quit(), handle_sigterm(), mi_cmd_gdb_exit(), mi_execute_command(), and quit_command().
void read_command_file (FILE *)
Definition at line 304 of file top.c.
References command_loop(), do_cleanups(), do_restore_instream_cleanup(), instream, and make_cleanup().
Referenced by script_from_file().
void set_history (char * , int)
Definition at line 1556 of file top.c.
References _, gdb_stdout, help_list(), printf_unfiltered(), and sethistlist.
Referenced by _initialize_cli_cmds().
void set_prompt (const char * s)
Definition at line 1263 of file top.c.
References p, top_prompt, and xfree().
Referenced by init_main().
void set_verbose (char * , int , struct cmd_list_element *)
Definition at line 1573 of file top.c.
References CMD_LIST_AMBIGUOUS, cmd_list_element::doc, gdb_assert, info_verbose, lookup_cmd_1(), and showlist.
Referenced by _initialize_cli_cmds().
void show_commands (char * args, int from_tty)
Definition at line 1465 of file top.c.
References Hist_print, line, offset, parse_and_eval_long(), and printf_filtered().
Referenced by _initialize_cli_cmds().
void show_history (char * , int)
Definition at line 1564 of file top.c.
References cmd_show_list(), and showhistlist.
Referenced by _initialize_cli_cmds().
Variable Documentation
int confirm
Definition at line 98 of file top.c.
Referenced by ATTRIBUTE_PRINTF(), and init_main().
char gdb_dirbuf[1024]
Definition at line 125 of file top.c.
Referenced by captured_main(), cd_command(), mi_cmd_env_pwd(), and pwd_command().
const char gdbinit[]
Definition at line 84 of file top.c.
Referenced by file_is_auto_load_safe(), get_init_files(), and init_cli_cmds().
int history_expansion_p
Definition at line 683 of file top.c.
Referenced by _initialize_cli_cmds(), command_line_handler(), command_line_input(), and init_main().
int in_user_command
Definition at line 118 of file top.c.
Referenced by do_restore_user_call_depth(), execute_user_command(), and input_from_terminal_p().
int inhibit_gdbinit
Definition at line 86 of file top.c.
Referenced by _initialize_check_for_gdb_ini(), captured_main(), and gdbtk_init().
FILE* instream
Definition at line 114 of file top.c.
Referenced by captured_command_loop(), captured_main(), command_handler(), command_line_handler(), command_line_input(), command_loop(), do_restore_instream_cleanup(), dont_repeat(), execute_user_command(), gdb_readline(), gdb_readline2(), gdb_setup_readline(), gdbtk_command_loop(), handle_sigterm(), input_from_terminal_p(), mi_execute_command_wrapper(), read_command_file(), read_next_line(), and stdin_event_handler().
char* lim_at_start
Referenced by captured_main(), make_command_stats_cleanup(), and report_command_stats().
int readnow_symbol_files
Definition at line 84 of file symfile.c.
Referenced by captured_main(), and symbol_file_add_with_addrs().
char* saved_command_line
Definition at line 136 of file top.c.
Referenced by captured_main(), command_line_handler(), command_line_input(), dont_repeat(), and dont_repeat_command().
int saved_command_line_size
Definition at line 137 of file top.c.
Referenced by captured_main(), command_line_handler(), and command_line_input().
int server_command
Definition at line 145 of file top.c.
Referenced by ATTRIBUTE_PRINTF(), breakpoint_1(), command_line_handler(), command_line_input(), and dont_repeat().
const char* source_file_name
Definition at line 290 of file top.c.
Referenced by command_line_handler(), command_line_input(), script_from_file(), and source_cleanup_lines().
int source_line_number
Definition at line 284 of file top.c.
Referenced by command_line_handler(), command_line_input(), script_from_file(), and source_cleanup_lines().