GDB (xrefs): /home/stan/gdb/src/gdb/tracepoint.h File Reference
/home/stan/gdb/src/gdb/tracepoint.h File Reference
#include "breakpoint.h"
#include "target.h"
#include "memrange.h"
#include "gdb_vecs.h"
Classes
struct traceframe_info
struct trace_state_variable
struct trace_status
struct uploaded_tp
struct uploaded_tsv
struct static_tracepoint_marker
struct trace_frame_write_ops
struct trace_file_write_ops
struct trace_file_writer
struct memrange
struct collection_list
Enumerations
enum trace_stop_reason {
trace_stop_reason_unknown, trace_never_run, tstop_command, trace_buffer_full,
trace_disconnected, tracepoint_passcount, tracepoint_error
}
Functions
struct trace_status * current_trace_status (void)
void parse_static_tracepoint_marker_definition (char *line, char **pp, struct static_tracepoint_marker *marker)
void release_static_tracepoint_marker (struct static_tracepoint_marker *)
void free_current_marker (void *arg)
int get_traceframe_number (void)
int get_tracepoint_number (void)
void set_traceframe_number (int)
void set_current_traceframe (int num)
struct cleanup * make_cleanup_restore_current_traceframe (void)
struct cleanup * make_cleanup_restore_traceframe_number (void)
void free_actions (struct breakpoint *)
const char * decode_agent_options (const char *exp, int *trace_string)
struct cleanup * encode_actions_and_make_cleanup (struct bp_location *tloc, struct collection_list *tracepoint_list, struct collection_list *stepping_list)
void encode_actions_rsp (struct bp_location *tloc, char ***tdp_actions, char ***stepping_actions)
void validate_actionline (const char *, struct breakpoint *)
void validate_trace_state_variable_name (const char *name)
struct trace_state_variable * find_trace_state_variable (const char *name)
struct trace_state_variable * find_trace_state_variable_by_number (int number)
struct trace_state_variable * create_trace_state_variable (const char *name)
int encode_source_string (int num, ULONGEST addr, char *srctype, char *src, char *buf, int buf_size)
void parse_trace_status (char *line, struct trace_status *ts)
void parse_tracepoint_status (char *p, struct breakpoint *tp, struct uploaded_tp *utp)
void parse_tracepoint_definition (char *line, struct uploaded_tp **utpp)
void parse_tsv_definition (char *line, struct uploaded_tsv **utsvp)
struct uploaded_tp * get_uploaded_tp (int num, ULONGEST addr, struct uploaded_tp **utpp)
struct uploaded_tsv * get_uploaded_tsv (int num, struct uploaded_tsv **utsvp)
struct tracepoint * create_tracepoint_from_upload (struct uploaded_tp *utp)
void merge_uploaded_tracepoints (struct uploaded_tp **utpp)
void merge_uploaded_trace_state_variables (struct uploaded_tsv **utsvp)
void query_if_trace_running (int from_tty)
void disconnect_tracing (void)
void trace_reset_local_state (void)
void start_tracing (char *notes)
void stop_tracing (char *notes)
void trace_status_mi (int on_stop)
void tvariables_info_1 (void)
void save_trace_state_variables (struct ui_file *fp)
void tfind_1 (enum trace_find_type type, int num, CORE_ADDR addr1, CORE_ADDR addr2, int from_tty)
void trace_save_tfile (const char *filename, int target_does_save)
void trace_save_ctf (const char *dirname, int target_does_save)
struct traceframe_info * parse_traceframe_info (const char *tframe_info)
int traceframe_available_memory (VEC(mem_range_s)**result, CORE_ADDR memaddr, ULONGEST len)
struct traceframe_info * get_traceframe_info (void)
struct bp_location * get_traceframe_location (int *stepping_frame_p)
Variables
char * default_collect
int trace_regblock_size
void(* deprecated_trace_find_hook)(char *arg, int from_tty)
void(* deprecated_trace_start_stop_hook)(int start, int from_tty)
Enumeration Type Documentation
enum trace_stop_reason
Enumerator:
trace_stop_reason_unknown
trace_never_run
tstop_command
trace_buffer_full
trace_disconnected
tracepoint_passcount
tracepoint_error
Definition at line 73 of file tracepoint.h.
Function Documentation
struct trace_state_variable* create_trace_state_variable (const char * name) [read]
Definition at line 312 of file tracepoint.c.
References memset(), trace_state_variable::name, trace_state_variable::number, and VEC_safe_push.
Referenced by create_tsv_from_upload(), mi_cmd_trace_define_variable(), and trace_variable_command().
struct tracepoint* create_tracepoint_from_upload (struct uploaded_tp * utp) [read]
Definition at line 15185 of file breakpoint.c.
References _, uploaded_tp::addr, uploaded_tp::at_string, tracepoint::base, breakpoint_set_commands(), uploaded_tp::cond, uploaded_tp::cond_string, create_breakpoint(), CREATE_BREAKPOINT_FLAGS_INSERTED, uploaded_tp::enabled, gdb_assert, get_current_arch(), get_tracepoint(), hex_string(), uploaded_tp::hit_count, breakpoint::hit_count, uploaded_tp::number, breakpoint::number, uploaded_tp::pass, read_command_lines_1(), read_uploaded_action(), trace_pass_command(), uploaded_tp::traceframe_usage, tracepoint::traceframe_usage, tracepoint_breakpoint_ops, uploaded_tp::type, VEC_empty, warning(), and xsnprintf().
Referenced by merge_uploaded_tracepoints().
struct trace_status* current_trace_status (void) [read]
Definition at line 219 of file tracepoint.c.
Referenced by disable_breakpoint(), disable_command(), enable_breakpoint_disp(), enable_command(), gdb_trace_status(), mi_cmd_trace_find(), query_if_trace_running(), remote_can_download_tracepoint(), remote_start_remote(), start_tracing(), stop_tracing(), tfile_interp_line(), tfile_open(), trace_find_command(), trace_find_line_command(), trace_find_outside_command(), trace_find_pc_command(), trace_find_range_command(), trace_find_tracepoint_command(), trace_save(), trace_start_command(), trace_status_command(), trace_status_mi(), trace_stop_command(), and tvariables_info_1().
const char* decode_agent_options (const char * exp, int * trace_string)
Definition at line 620 of file tracepoint.c.
References _, error(), get_user_print_options(), value_print_options::print_max, skip_spaces_const(), and target_supports_string_tracing.
Referenced by agent_eval_command_one(), encode_actions_1(), trace_dump_actions(), and validate_actionline().
void disconnect_tracing (void)
Definition at line 2308 of file tracepoint.c.
References trace_reset_local_state().
Referenced by detach_command(), disconnect_command(), and quit_force().
struct cleanup* encode_actions_and_make_cleanup (struct bp_location * tloc, struct collection_list * tracepoint_list, struct collection_list * stepping_list) [read]
Definition at line 1662 of file tracepoint.c.
References bp_location::address, all_tracepoint_actions_and_cleanup(), do_cleanups(), do_clear_collection_list(), encode_actions_1(), bp_location::gdbarch, gdbarch_virtual_frame_pointer(), init_collection_list(), LONGEST, make_cleanup(), memrange_sortmerge(), null_cleanup(), and bp_location::owner.
Referenced by encode_actions_rsp(), and mi_cmd_trace_frame_collected().
void encode_actions_rsp (struct bp_location * tloc, char *** tdp_actions, char *** stepping_actions)
Definition at line 1699 of file tracepoint.c.
References do_cleanups(), encode_actions_and_make_cleanup(), and stringify_collection_list().
Referenced by remote_download_tracepoint().
int encode_source_string (int num, ULONGEST addr, char * srctype, char * src, char * buf, int buf_size)
Definition at line 3087 of file tracepoint.c.
References _, bin2hex(), error(), and phex_nz().
Referenced by remote_download_command_source(), remote_download_tracepoint(), and tfile_write_uploaded_tp().
struct trace_state_variable* find_trace_state_variable (const char * name) [read]
Definition at line 325 of file tracepoint.c.
References trace_state_variable::name, and VEC_iterate.
Referenced by create_tsv_from_upload(), find_matching_tsv(), gen_expr(), mi_cmd_trace_define_variable(), trace_variable_command(), and value_of_internalvar().
struct trace_state_variable* find_trace_state_variable_by_number (int number) [read]
Definition at line 341 of file tracepoint.c.
References trace_state_variable::number, and VEC_iterate.
Referenced by mi_cmd_trace_frame_collected().
void free_actions (struct breakpoint *)
void free_current_marker (void * arg)
Definition at line 5338 of file tracepoint.c.
References release_static_tracepoint_marker(), and xfree().
Referenced by VEC().
struct traceframe_info* get_traceframe_info (void) [read]
Definition at line 5730 of file tracepoint.c.
References target_traceframe_info.
Referenced by mi_cmd_trace_frame_collected(), and traceframe_available_memory().
struct bp_location* get_traceframe_location (int * stepping_frame_p) [read]
Definition at line 2979 of file tracepoint.c.
References _, bp_location::address, tracepoint::base, error(), get_current_regcache(), get_tracepoint(), breakpoint::loc, bp_location::next, and regcache_read_pc().
Referenced by mi_cmd_trace_frame_collected(), and trace_dump_command().
int get_traceframe_number (void)
Definition at line 3845 of file tracepoint.c.
Referenced by call_function_by_hand(), ensure_not_tfind_mode(), gdb_get_trace_frame_num(), get_current_frame(), has_stack_frames(), memory_xfer_partial_1(), mi_cmd_trace_find(), set_remote_traceframe(), and tfind_1().
int get_tracepoint_number (void)
Definition at line 3851 of file tracepoint.c.
struct uploaded_tp* get_uploaded_tp (int num, ULONGEST addr, struct uploaded_tp ** utpp) [read]
Definition at line 3939 of file tracepoint.c.
References uploaded_tp::addr, memset(), uploaded_tp::next, uploaded_tp::number, and xmalloc().
Referenced by parse_tracepoint_definition().
struct uploaded_tsv* get_uploaded_tsv (int num, struct uploaded_tsv ** utsvp) [read]
Definition at line 3975 of file tracepoint.c.
References memset(), uploaded_tsv::next, uploaded_tsv::number, and xmalloc().
Referenced by parse_tsv_definition().
struct cleanup* make_cleanup_restore_current_traceframe (void) [read]
Definition at line 3918 of file tracepoint.c.
References do_restore_current_traceframe_cleanup(), make_cleanup_dtor(), restore_current_traceframe_cleanup_dtor(), current_traceframe_cleanup::traceframe_number, and xmalloc().
Referenced by fetch_inferior_event().
struct cleanup* make_cleanup_restore_traceframe_number (void) [read]
Definition at line 3930 of file tracepoint.c.
References make_cleanup_restore_integer().
Referenced by target_read_live_memory().
void merge_uploaded_trace_state_variables (struct uploaded_tsv ** utsvp)
Definition at line 4187 of file tracepoint.c.
References _, create_tsv_from_upload(), find_matching_tsv(), free_uploaded_tsvs(), info_verbose, trace_state_variable::name, uploaded_tsv::next, trace_state_variable::number, uploaded_tsv::number, printf_filtered(), and VEC_iterate.
Referenced by remote_start_remote(), and tfile_open().
void merge_uploaded_tracepoints (struct uploaded_tp ** utpp)
Definition at line 4056 of file tracepoint.c.
References _, uploaded_tp::addr, tracepoint::base, create_tracepoint_from_upload(), find_matching_tracepoint_location(), free_uploaded_tps(), bp_location::gdbarch, get_current_arch(), bp_location::inserted, uploaded_tp::next, uploaded_tp::number, breakpoint::number, tracepoint::number_on_target, observer_notify_breakpoint_modified(), bp_location::owner, paddress(), printf_filtered(), VEC, VEC_free, VEC_iterate, and VEC_safe_push.
Referenced by remote_start_remote(), and tfile_open().
void parse_static_tracepoint_marker_definition (char * line, char ** pp, struct static_tracepoint_marker * marker)
Definition at line 5357 of file tracepoint.c.
References _, static_tracepoint_marker::address, error(), static_tracepoint_marker::extra, static_tracepoint_marker::gdbarch, hex2bin(), line, p, static_tracepoint_marker::str_id, strchr(), target_gdbarch(), ULONGEST, unpack_varlen_hex(), and xmalloc().
Referenced by remote_static_tracepoint_marker_at(), and VEC().
void parse_trace_status (char * line, struct trace_status * ts)
Definition at line 4429 of file tracepoint.c.
References _, trace_status::buffer_free, trace_status::buffer_size, trace_status::circular_buffer, trace_status::disconnected_tracing, error(), hex2bin(), line, trace_status::notes, p, trace_status::running, trace_status::running_known, trace_status::start_time, trace_status::stop_desc, trace_status::stop_reason, trace_status::stop_time, trace_status::stopping_tracepoint, strchr(), trace_buffer_full, trace_disconnected, trace_never_run, trace_stop_reason_unknown, trace_status::traceframe_count, trace_status::traceframes_created, tracepoint_error, tracepoint_passcount, tstop_command, ULONGEST, unpack_varlen_hex(), trace_status::user_name, xfree(), and xmalloc().
Referenced by remote_get_trace_status(), and tfile_interp_line().
struct traceframe_info* parse_traceframe_info (const char * tframe_info) [read]
Definition at line 5608 of file tracepoint.c.
References _, and warning().
Referenced by remote_traceframe_info().
void parse_tracepoint_definition (char * line, struct uploaded_tp ** utpp)
Definition at line 4612 of file tracepoint.c.
References _, uploaded_tp::at_string, bp_fast_tracepoint, bp_static_tracepoint, bp_tracepoint, uploaded_tp::cond, uploaded_tp::cond_string, uploaded_tp::enabled, get_uploaded_tp(), hex2bin(), line, p, parse_tracepoint_status(), uploaded_tp::pass, uploaded_tp::step, strchr(), type, uploaded_tp::type, ULONGEST, unpack_varlen_hex(), VEC_safe_push, warning(), and xmalloc().
Referenced by remote_upload_tracepoints(), and tfile_interp_line().
void parse_tracepoint_status (char * p, struct breakpoint * tp, struct uploaded_tp * utp)
Definition at line 4589 of file tracepoint.c.
References tracepoint::base, uploaded_tp::hit_count, breakpoint::hit_count, uploaded_tp::traceframe_usage, tracepoint::traceframe_usage, ULONGEST, and unpack_varlen_hex().
Referenced by parse_tracepoint_definition(), and remote_get_tracepoint_status().
void parse_tsv_definition (char * line, struct uploaded_tsv ** utsvp)
Definition at line 4727 of file tracepoint.c.
References uploaded_tsv::builtin, get_uploaded_tsv(), hex2bin(), uploaded_tsv::initial_value, line, uploaded_tsv::name, p, ULONGEST, and unpack_varlen_hex().
Referenced by remote_upload_trace_state_variables(), and tfile_interp_line().
void query_if_trace_running (int from_tty)
Definition at line 2267 of file tracepoint.c.
References _, current_trace_status(), trace_status::disconnected_tracing, error(), process_tracepoint_on_disconnect(), query(), trace_status::running, and target_get_trace_status.
Referenced by detach_command(), disconnect_command(), and quit_command().
void release_static_tracepoint_marker (struct static_tracepoint_marker *)
Definition at line 5395 of file tracepoint.c.
References static_tracepoint_marker::str_id, and xfree().
Referenced by decode_static_tracepoint_spec(), free_current_marker(), info_static_tracepoint_markers_command(), init_breakpoint_sal(), update_static_tracepoint(), and VEC().
void save_trace_state_variables (struct ui_file * fp)
Definition at line 568 of file tracepoint.c.
References fprintf_unfiltered(), trace_state_variable::initial_value, trace_state_variable::name, plongest(), and VEC_iterate.
Referenced by save_breakpoints().
void set_current_traceframe (int num)
Definition at line 3860 of file tracepoint.c.
References _, clear_traceframe_info(), registers_changed(), set_traceframe_num(), target_trace_find, tfind_number, and warning().
Referenced by do_restore_current_traceframe_cleanup(), fetch_inferior_event(), and tfind_1().
void set_traceframe_number (int)
Definition at line 3888 of file tracepoint.c.
Referenced by target_read_live_memory().
void start_tracing (char * notes)
Definition at line 1785 of file tracepoint.c.
References _, bp_enabled, bp_fast_tracepoint, current_trace_status(), breakpoint::enable_state, error(), gdb_assert, bp_location::gdbarch, bp_location::inserted, breakpoint::loc, may_insert_fast_tracepoints, may_insert_tracepoints, bp_location::next, breakpoint::number, tracepoint::number_on_target, observer_notify_breakpoint_modified(), probe::pops, bp_location::probe, trace_status::running, probe_ops::set_semaphore, target_download_trace_state_variable, target_download_tracepoint, target_set_circular_trace_buffer, target_set_disconnected_tracing, target_set_trace_buffer_size, target_set_trace_notes, target_supports_enable_disable_tracepoint, target_trace_init, target_trace_set_readonly_regions, target_trace_start, trace_reset_local_state(), breakpoint::type, VEC, VEC_free, VEC_iterate, VEC_length, and warning().
Referenced by mi_cmd_trace_start(), and trace_start_command().
void stop_tracing (char * notes)
Definition at line 1945 of file tracepoint.c.
References _, bp_fast_tracepoint, probe_ops::clear_semaphore, current_trace_status(), bp_location::gdbarch, breakpoint::loc, may_insert_fast_tracepoints, may_insert_tracepoints, bp_location::next, probe::pops, bp_location::probe, trace_status::running, target_set_trace_notes, target_trace_stop, breakpoint::type, VEC, VEC_free, VEC_iterate, and warning().
Referenced by mi_cmd_trace_stop(), and trace_stop_command().
void tfind_1 (enum trace_find_type type, int num, CORE_ADDR addr1, CORE_ADDR addr2, int from_tty)
Definition at line 2319 of file tracepoint.c.
References _, tracepoint::base, current_uiout, do_displays(), error(), frame_id_eq(), get_current_frame(), get_frame_id(), get_selected_frame(), get_traceframe_number(), get_tracepoint_by_number_on_target(), has_stack_frames(), info_verbose, null_frame_id, breakpoint::number, observer_notify_traceframe_changed(), print_stack_frame(), printf_filtered(), printf_unfiltered(), reinit_frame_cache(), set_current_traceframe(), set_traceframe_context(), set_tracepoint_num(), SRC_AND_LOC, SRC_LINE, target_dcache_invalidate(), target_trace_find, tfind_number, trace_find_command(), ui_out_field_int(), ui_out_field_string(), and ui_out_is_mi_like_p().
Referenced by mi_cmd_trace_find(), trace_find_command(), trace_find_line_command(), trace_find_outside_command(), trace_find_pc_command(), trace_find_range_command(), and trace_find_tracepoint_command().
void trace_reset_local_state (void)
Definition at line 1776 of file tracepoint.c.
References clear_traceframe_info(), set_traceframe_context(), set_traceframe_num(), and set_tracepoint_num().
Referenced by disconnect_tracing(), remote_close(), start_tracing(), and tfile_close().
void trace_save_ctf (const char * dirname, int target_does_save)
Definition at line 3747 of file tracepoint.c.
References ctf_trace_file_writer_new(), do_cleanups(), make_cleanup(), trace_file_writer_xfree(), and trace_save().
Referenced by mi_cmd_trace_save().
void trace_save_tfile (const char * filename, int target_does_save)
Definition at line 3733 of file tracepoint.c.
References do_cleanups(), make_cleanup(), tfile_trace_file_writer_new(), trace_file_writer_xfree(), and trace_save().
Referenced by mi_cmd_trace_save().
void trace_status_mi (int on_stop)
Definition at line 2153 of file tracepoint.c.
References trace_status::buffer_free, trace_status::buffer_size, trace_status::circular_buffer, current_trace_status(), current_uiout, trace_status::disconnected_tracing, trace_status::filename, gdb_assert, trace_status::notes, trace_status::running, trace_status::running_known, trace_status::start_time, exsummary::status, trace_status::stop_desc, trace_status::stop_reason, trace_status::stop_time, trace_status::stopping_tracepoint, target_get_trace_status, trace_buffer_full, trace_disconnected, trace_stop_reason_unknown, trace_status::traceframe_count, trace_status::traceframes_created, tracepoint_error, tracepoint_passcount, tstop_command, ui_out_field_int(), ui_out_field_string(), trace_status::user_name, and xsnprintf().
Referenced by mi_cmd_trace_status(), and mi_cmd_trace_stop().
int traceframe_available_memory (VEC(mem_range_s)** result, CORE_ADDR memaddr, ULONGEST len)
Definition at line 5745 of file tracepoint.c.
References get_traceframe_info(), len, mem_range::length, max, mem_ranges_overlap(), memaddr, min, normalize_mem_ranges(), mem_range::start, ULONGEST, VEC_iterate, and VEC_safe_push.
Referenced by memory_xfer_partial_1(), mi_cmd_trace_frame_collected(), and read_value_memory().
void tvariables_info_1 (void)
Definition at line 494 of file tracepoint.c.
References _, current_trace_status(), current_uiout, do_cleanups(), trace_state_variable::initial_value, make_cleanup(), make_cleanup_ui_out_table_begin_end(), make_cleanup_ui_out_tuple_begin_end(), trace_state_variable::name, name, trace_state_variable::number, plongest(), printf_filtered(), target_get_trace_state_variable_value, ui_left, ui_out_field_string(), ui_out_is_mi_like_p(), ui_out_table_body(), ui_out_table_header(), ui_out_text(), trace_state_variable::value, trace_state_variable::value_known, VEC_iterate, VEC_length, and xfree().
Referenced by mi_cmd_trace_list_variables(), and tvariables_info().
void validate_actionline (const char * , struct breakpoint *)
Definition at line 711 of file tracepoint.c.
References _, bp_location::address, ax_reqs(), tracepoint::base, block_for_pc(), cmd_cfunc_eq(), cmdlist, collect_pseudocommand(), decode_agent_options(), do_cleanups(), expression::elts, end_actions_pseudocommand(), error(), free_current_contents(), gen_eval_for_expr(), gen_trace_for_expr(), agent_expr::len, breakpoint::loc, LOC_CONST, LOC_OPTIMIZED_OUT, lookup_cmd(), make_cleanup(), make_cleanup_free_agent_expr(), MAX_AGENT_EXPR_LEN, bp_location::next, exp_element::opcode, p, parse_exp_1(), plongest(), QUIT, report_agent_reqs_errors(), skip_spaces_const(), tracepoint::step_count, strchr(), exp_element::symbol, SYMBOL_CLASS, SYMBOL_PRINT_NAME, SYMBOL_VALUE, teval_pseudocommand(), and while_stepping_pseudocommand().
Referenced by all_tracepoint_actions_and_cleanup(), check_tracepoint_command(), and validate_commands_for_breakpoint().
void validate_trace_state_variable_name (const char * name)
Definition at line 377 of file tracepoint.c.
References _, error(), and p.
Referenced by mi_cmd_trace_define_variable(), and trace_variable_command().
Variable Documentation
char* default_collect
Referenced by _initialize_tracepoint(), all_tracepoint_actions_and_cleanup(), default_collect_info(), remote_download_tracepoint(), save_breakpoints(), and VEC().
void(* deprecated_trace_find_hook)(char *arg, int from_tty)
Definition at line 85 of file tracepoint.c.
Referenced by gdbtk_add_hooks().
void(* deprecated_trace_start_stop_hook)(int start, int from_tty)
Definition at line 86 of file tracepoint.c.
Referenced by gdbtk_add_hooks().
int trace_regblock_size
Definition at line 4249 of file tracepoint.c.
Referenced by remote_get_trace_status(), trace_save(), and traceframe_walk_blocks().