GDB (xrefs): /home/stan/gdb/src/gdb/trad-frame.h File Reference
/home/stan/gdb/src/gdb/trad-frame.h File Reference
#include "frame.h"
Classes
struct trad_frame_saved_reg
Functions
struct trad_frame_cache * trad_frame_cache_zalloc (struct frame_info *)
void trad_frame_set_id (struct trad_frame_cache *this_trad_cache, struct frame_id this_id)
void trad_frame_get_id (struct trad_frame_cache *this_trad_cache, struct frame_id *this_id)
void trad_frame_set_this_base (struct trad_frame_cache *this_trad_cache, CORE_ADDR this_base)
CORE_ADDR trad_frame_get_this_base (struct trad_frame_cache *this_trad_cache)
void trad_frame_set_reg_realreg (struct trad_frame_cache *this_trad_cache, int regnum, int realreg)
void trad_frame_set_reg_unknown (struct trad_frame_cache *this_trad_cache, int regnum, CORE_ADDR addr)
void trad_frame_set_reg_addr (struct trad_frame_cache *this_trad_cache, int regnum, CORE_ADDR addr)
void trad_frame_set_reg_value (struct trad_frame_cache *this_cache, int regnum, LONGEST val)
struct value * trad_frame_get_register (struct trad_frame_cache *this_trad_cache, struct frame_info *this_frame, int regnum)
void trad_frame_set_value (struct trad_frame_saved_reg this_saved_regs[], int regnum, LONGEST val)
void trad_frame_set_unknown (struct trad_frame_saved_reg this_saved_regs[], int regnum)
int trad_frame_value_p (struct trad_frame_saved_reg this_saved_regs[], int regnum)
int trad_frame_addr_p (struct trad_frame_saved_reg this_saved_regs[], int regnum)
int trad_frame_realreg_p (struct trad_frame_saved_reg this_saved_regs[], int regnum)
struct trad_frame_saved_reg * trad_frame_alloc_saved_regs (struct frame_info *)
struct value * trad_frame_get_prev_register (struct frame_info *this_frame, struct trad_frame_saved_reg this_saved_regs[], int regnum)
Function Documentation
int trad_frame_addr_p (struct trad_frame_saved_reg this_saved_regs[], int regnum)
Definition at line 77 of file trad-frame.c.
References trad_frame_saved_reg::addr, and trad_frame_saved_reg::realreg.
Referenced by aarch64_make_prologue_cache(), alpha_heuristic_frame_unwind_cache(), alpha_mdebug_frame_unwind_cache(), arm_exidx_fill_cache(), arm_make_prologue_cache(), avr_frame_prev_register(), hppa_fallback_frame_cache(), lm32_frame_cache(), m32r_frame_unwind_cache(), m68hc11_frame_unwind_cache(), mt_frame_unwind_cache(), s390_prologue_frame_unwind_cache(), spu_frame_unwind_cache(), trad_frame_get_prev_register(), and v850_frame_cache().
struct trad_frame_saved_reg* trad_frame_alloc_saved_regs (struct frame_info *) [read]
Definition at line 52 of file trad-frame.c.
References trad_frame_saved_reg::addr, FRAME_OBSTACK_CALLOC, gdbarch_num_pseudo_regs(), gdbarch_num_regs(), get_frame_arch(), trad_frame_saved_reg::realreg, and regnum.
Referenced by aarch64_make_prologue_cache(), aarch64_make_stub_cache(), alpha_heuristic_frame_unwind_cache(), alpha_mdebug_frame_unwind_cache(), arm_exidx_fill_cache(), arm_m_exception_cache(), arm_make_prologue_cache(), arm_make_stub_cache(), avr_frame_unwind_cache(), cris_frame_unwind_cache(), cris_sigtramp_frame_unwind_cache(), frv_frame_unwind_cache(), hppa_fallback_frame_cache(), hppa_frame_cache(), hppa_hpux_sigtramp_frame_unwind_cache(), hppa_linux_sigtramp_frame_unwind_cache(), hppa_stub_frame_unwind_cache(), lm32_frame_cache(), m32r_frame_unwind_cache(), m32r_linux_sigtramp_frame_cache(), m68hc11_frame_unwind_cache(), m88k_frame_cache(), microblaze_frame_cache(), mips_insn16_frame_cache(), mips_insn32_frame_cache(), mips_micro_frame_cache(), mt_frame_unwind_cache(), rs6000_frame_cache(), s390_frame_unwind_cache(), s390_sigtramp_frame_unwind_cache(), s390_stub_frame_unwind_cache(), score_make_prologue_cache(), sparc32_sol2_sigtramp_frame_cache(), sparc32nbsd_sigcontext_saved_regs(), sparc64_sol2_sigtramp_frame_cache(), sparc64fbsd_sigtramp_frame_cache(), sparc64nbsd_sigcontext_saved_regs(), sparc64obsd_trapframe_cache(), spu_frame_unwind_cache(), tilegx_frame_cache(), trad_frame_cache_zalloc(), v850_alloc_frame_cache(), and vax_frame_cache().
struct trad_frame_cache* trad_frame_cache_zalloc (struct frame_info *) [read]
Definition at line 36 of file trad-frame.c.
References FRAME_OBSTACK_ZALLOC, trad_frame_cache::prev_regs, trad_frame_cache::this_frame, and trad_frame_alloc_saved_regs().
Referenced by amd64obsd_trapframe_cache(), frv_linux_sigtramp_frame_cache(), i386obsd_trapframe_cache(), m68k_linux_sigtramp_frame_cache(), mips_stub_frame_cache(), nios2_stub_frame_cache(), ppcfbsd_sigtramp_frame_cache(), ppcobsd_sigtramp_frame_cache(), tramp_frame_cache(), and vaxobsd_sigtramp_frame_cache().
void trad_frame_get_id (struct trad_frame_cache * this_trad_cache, struct frame_id * this_id)
Definition at line 171 of file trad-frame.c.
References trad_frame_cache::this_id.
Referenced by amd64obsd_trapframe_this_id(), frv_linux_sigtramp_frame_this_id(), i386obsd_trapframe_this_id(), m68k_linux_sigtramp_frame_this_id(), mips_stub_frame_this_id(), nios2_stub_frame_this_id(), ppcfbsd_sigtramp_frame_this_id(), ppcobsd_sigtramp_frame_this_id(), tramp_frame_this_id(), and vaxobsd_sigtramp_frame_this_id().
struct value* trad_frame_get_prev_register (struct frame_info * this_frame, struct trad_frame_saved_reg this_saved_regs[], int regnum) [read]
Definition at line 135 of file trad-frame.c.
References frame_unwind_got_constant(), frame_unwind_got_memory(), frame_unwind_got_optimized(), frame_unwind_got_register(), trad_frame_addr_p(), trad_frame_realreg_p(), and trad_frame_value_p().
Referenced by aarch64_prologue_prev_register(), alpha_heuristic_frame_prev_register(), alpha_mdebug_frame_prev_register(), arm_m_exception_prev_register(), arm_prologue_prev_register(), avr_frame_prev_register(), cris_frame_prev_register(), frv_frame_prev_register(), hppa_frame_prev_register_helper(), hppa_hpux_unwind_adjust_stub(), lm32_frame_prev_register(), m32r_frame_prev_register(), m32r_linux_sigtramp_frame_prev_register(), m68hc11_frame_prev_register(), m88k_frame_prev_register(), microblaze_frame_prev_register(), mips_insn16_frame_prev_register(), mips_insn32_frame_prev_register(), mips_micro_frame_prev_register(), mt_frame_prev_register(), rs6000_frame_prev_register(), s390_trad_frame_prev_register(), score_prologue_prev_register(), sparc32_sol2_sigtramp_frame_prev_register(), sparc32nbsd_sigcontext_frame_prev_register(), sparc32obsd_sigtramp_frame_prev_register(), sparc64_sol2_sigtramp_frame_prev_register(), sparc64fbsd_sigtramp_frame_prev_register(), sparc64nbsd_sigcontext_frame_prev_register(), sparc64obsd_frame_prev_register(), sparc64obsd_trapframe_prev_register(), spu_frame_prev_register(), tilegx_frame_prev_register(), trad_frame_get_register(), v850_frame_prev_register(), and vax_frame_prev_register().
struct value* trad_frame_get_register (struct trad_frame_cache * this_trad_cache, struct frame_info * this_frame, int regnum) [read]
Definition at line 155 of file trad-frame.c.
References trad_frame_cache::prev_regs, and trad_frame_get_prev_register().
Referenced by amd64obsd_trapframe_prev_register(), frv_linux_sigtramp_frame_prev_register(), i386obsd_trapframe_prev_register(), m68k_linux_sigtramp_frame_prev_register(), mips_stub_frame_prev_register(), nios2_stub_frame_prev_register(), ppcfbsd_sigtramp_frame_prev_register(), ppcobsd_sigtramp_frame_prev_register(), tramp_frame_prev_register(), and vaxobsd_sigtramp_frame_prev_register().
CORE_ADDR trad_frame_get_this_base (struct trad_frame_cache * this_trad_cache)
Definition at line 185 of file trad-frame.c.
References trad_frame_cache::this_base.
Referenced by mips_stub_frame_base_address(), and nios2_stub_frame_base_address().
int trad_frame_realreg_p (struct trad_frame_saved_reg this_saved_regs[], int regnum)
Definition at line 84 of file trad-frame.c.
References trad_frame_saved_reg::addr, and trad_frame_saved_reg::realreg.
Referenced by arm_exidx_fill_cache(), and trad_frame_get_prev_register().
void trad_frame_set_id (struct trad_frame_cache * this_trad_cache, struct frame_id this_id)
Definition at line 164 of file trad-frame.c.
References trad_frame_cache::this_id.
Referenced by aarch64_linux_sigframe_init(), am33_linux_sigframe_cache_init(), amd64obsd_trapframe_cache(), arm_linux_restart_syscall_init(), arm_linux_sigtramp_cache(), armobsd_sigframe_init(), bfin_linux_sigframe_init(), frv_linux_sigtramp_frame_cache(), hppanbsd_sigtramp_cache_init(), i386nbsd_sigtramp_cache_init(), i386obsd_trapframe_cache(), m68k_linux_sigtramp_frame_cache(), m68kobsd_sigtramp_cache_init(), microblaze_linux_sigtramp_cache(), mips64obsd_sigframe_init(), mips_irix_n32_stack_tramp_frame_init(), mips_irix_n32_tramp_frame_init(), mips_linux_n32n64_sigframe_init(), mips_linux_o32_sigframe_init(), mips_stub_frame_cache(), nios2_linux_rt_sigreturn_init(), nios2_linux_sigreturn_init(), nios2_stub_frame_cache(), ppc_linux_sigtramp_cache(), ppcfbsd_sigtramp_frame_cache(), ppcnbsd_sigtramp_cache_init(), ppcobsd_sigtramp_frame_cache(), sh_linux_sigtramp_cache(), sparc32_linux_sigframe_init(), sparc64_linux_sigframe_init(), tic6x_linux_rt_sigreturn_init(), tilegx_linux_sigframe_init(), and vaxobsd_sigtramp_frame_cache().
void trad_frame_set_reg_addr (struct trad_frame_cache * this_trad_cache, int regnum, CORE_ADDR addr)
Definition at line 119 of file trad-frame.c.
References trad_frame_saved_reg::addr, trad_frame_cache::prev_regs, and regnum.
Referenced by aarch64_linux_sigframe_init(), am33_linux_sigframe_cache_init(), amd64obsd_trapframe_cache(), arm_linux_sigtramp_cache(), armobsd_sigframe_init(), bfin_linux_sigframe_init(), frv_linux_sigtramp_frame_cache(), hppanbsd_sigtramp_cache_init(), i386nbsd_sigtramp_cache_init(), i386obsd_trapframe_cache(), m68k_linux_sigtramp_frame_cache(), m68kobsd_sigtramp_cache_init(), microblaze_linux_sigtramp_cache(), mips64obsd_sigframe_init(), mips_irix_n32_tramp_frame_init(), mips_linux_n32n64_sigframe_init(), mips_linux_o32_sigframe_init(), nios2_linux_rt_sigreturn_init(), nios2_linux_sigreturn_init(), ppc_linux_sigtramp_cache(), ppcfbsd_sigtramp_frame_cache(), ppcnbsd_sigtramp_cache_init(), ppcobsd_sigtramp_frame_cache(), sh_linux_sigtramp_cache(), sparc32_linux_sigframe_init(), sparc64_linux_sigframe_init(), tic6x_linux_rt_sigreturn_init(), tilegx_linux_sigframe_init(), and vaxobsd_sigtramp_frame_cache().
void trad_frame_set_reg_realreg (struct trad_frame_cache * this_trad_cache, int regnum, int realreg)
Definition at line 111 of file trad-frame.c.
References trad_frame_saved_reg::addr, trad_frame_cache::prev_regs, trad_frame_saved_reg::realreg, and regnum.
Referenced by mips_irix_n32_stack_tramp_frame_init(), mips_stub_frame_cache(), and nios2_stub_frame_cache().
void trad_frame_set_reg_unknown (struct trad_frame_cache * this_trad_cache, int regnum, CORE_ADDR addr)
void trad_frame_set_reg_value (struct trad_frame_cache * this_cache, int regnum, LONGEST val)
Definition at line 102 of file trad-frame.c.
References trad_frame_cache::prev_regs, and trad_frame_set_value().
Referenced by arm_linux_restart_syscall_init(), and tilegx_linux_sigframe_init().
void trad_frame_set_this_base (struct trad_frame_cache * this_trad_cache, CORE_ADDR this_base)
Definition at line 178 of file trad-frame.c.
References trad_frame_cache::this_base.
Referenced by mips_stub_frame_cache(), and nios2_stub_frame_cache().
void trad_frame_set_unknown (struct trad_frame_saved_reg this_saved_regs[], int regnum)
Definition at line 126 of file trad-frame.c.
References trad_frame_saved_reg::addr, trad_frame_saved_reg::realreg, regnum, and TF_REG_UNKNOWN.
Referenced by s390_backchain_frame_unwind_cache(), s390_prologue_frame_unwind_cache(), sparc32_sol2_sigtramp_frame_cache(), and sparc64_sol2_sigtramp_frame_cache().
void trad_frame_set_value (struct trad_frame_saved_reg this_saved_regs[], int regnum, LONGEST val)
Definition at line 92 of file trad-frame.c.
References trad_frame_saved_reg::addr, trad_frame_saved_reg::realreg, regnum, and TF_REG_VALUE.
Referenced by alpha_heuristic_frame_unwind_cache(), alpha_mdebug_frame_unwind_cache(), avr_frame_unwind_cache(), cris_scan_prologue(), frv_analyze_prologue(), hppa_fallback_frame_cache(), hppa_hpux_unwind_adjust_stub(), lm32_frame_cache(), m32r_frame_unwind_cache(), m68hc11_frame_unwind_cache(), m88k_frame_cache(), mips_insn16_frame_cache(), mips_insn32_frame_cache(), mips_micro_frame_cache(), mt_frame_unwind_cache(), rs6000_frame_cache(), score_make_prologue_cache(), sparc32nbsd_sigcontext_saved_regs(), sparc64nbsd_sigcontext_saved_regs(), spu_frame_unwind_cache(), tilegx_analyze_prologue(), tilegx_frame_cache(), trad_frame_set_reg_value(), v850_frame_cache(), and vax_frame_cache().
int trad_frame_value_p (struct trad_frame_saved_reg this_saved_regs[], int regnum)
Definition at line 71 of file trad-frame.c.
References trad_frame_saved_reg::realreg, and TF_REG_VALUE.
Referenced by trad_frame_get_prev_register().