GDB (xrefs): /home/stan/gdb/src/gdb/tramp-frame.h File Reference
/home/stan/gdb/src/gdb/tramp-frame.h File Reference
#include "frame.h"
Classes
struct tramp_frame
Defines
#define TRAMP_SENTINEL_INSN ((LONGEST) -1)
Functions
void tramp_frame_prepend_unwinder (struct gdbarch *gdbarch, const struct tramp_frame *tramp)
Define Documentation
#define TRAMP_SENTINEL_INSN ((LONGEST) -1)
Definition at line 44 of file tramp-frame.h.
Referenced by tramp_frame_prepend_unwinder(), and tramp_frame_start().
Function Documentation
void tramp_frame_prepend_unwinder (struct gdbarch * gdbarch, const struct tramp_frame * tramp)
Definition at line 142 of file tramp-frame.c.
References tramp_frame::bytes, default_frame_unwind_stop_reason(), tramp_frame::frame_type, frame_unwind_prepend_unwinder(), gdb_assert, GDBARCH_OBSTACK_ZALLOC, tramp_frame::insn, tramp_frame::insn_size, frame_unwind::prev_register, frame_unwind::sniffer, frame_unwind::stop_reason, frame_unwind::this_id, frame_data::tramp_frame, tramp_frame_prev_register(), tramp_frame_sniffer(), tramp_frame_this_id(), TRAMP_SENTINEL_INSN, frame_unwind::type, and frame_unwind::unwind_data.
Referenced by aarch64_linux_init_abi(), am33_linux_init_osabi(), arm_linux_init_abi(), armobsd_init_abi(), bfin_linux_init_abi(), hppanbsd_init_abi(), i386nbsd_init_abi(), m68kbsd_aout_init_abi(), microblaze_linux_init_abi(), mips64obsd_init_abi(), mips_irix_init_abi(), mips_linux_init_abi(), nios2_linux_init_abi(), ppc_linux_init_abi(), ppcnbsd_init_abi(), sh_linux_init_abi(), sparc32_linux_init_abi(), sparc64_linux_init_abi(), tic6x_uclinux_init_abi(), and tilegx_linux_init_abi().