GDB (xrefs): /home/stan/gdb/src/gdb/tui/tui-hooks.h File Reference
/home/stan/gdb/src/gdb/tui/tui-hooks.h File Reference
Functions
void tui_install_hooks (void)
void tui_remove_hooks (void)
Function Documentation
void tui_install_hooks (void)
Definition at line 259 of file tui-hooks.c.
References deprecated_print_frame_info_listing_hook, deprecated_query_hook, deprecated_register_changed_hook, deprecated_selected_frame_level_changed_hook, observer_attach_about_to_proceed(), observer_attach_breakpoint_created(), observer_attach_breakpoint_deleted(), observer_attach_breakpoint_modified(), observer_attach_inferior_exit(), tui_about_to_proceed(), tui_event_create_breakpoint(), tui_event_delete_breakpoint(), tui_event_modify_breakpoint(), tui_inferior_exit(), tui_print_frame_info_listing_hook(), tui_register_changed_hook(), and tui_selected_frame_level_changed_hook().
Referenced by tui_enable().
void tui_remove_hooks (void)
Definition at line 285 of file tui-hooks.c.
References deprecated_print_frame_info_listing_hook, deprecated_query_hook, deprecated_register_changed_hook, deprecated_selected_frame_level_changed_hook, observer_detach_about_to_proceed(), observer_detach_breakpoint_created(), observer_detach_breakpoint_deleted(), observer_detach_breakpoint_modified(), and observer_detach_inferior_exit().
Referenced by tui_disable().