GDB (xrefs): /home/stan/gdb/src/gdb/tui/tui-hooks.c File Reference
/home/stan/gdb/src/gdb/tui/tui-hooks.c File Reference
#include "defs.h"
#include "symtab.h"
#include "inferior.h"
#include "command.h"
#include "bfd.h"
#include "symfile.h"
#include "objfiles.h"
#include "target.h"
#include "gdbcore.h"
#include "event-loop.h"
#include "event-top.h"
#include "frame.h"
#include "breakpoint.h"
#include "ui-out.h"
#include "top.h"
#include "observer.h"
#include <unistd.h>
#include <fcntl.h>
#include "tui/tui.h"
#include "tui/tui-hooks.h"
#include "tui/tui-data.h"
#include "tui/tui-layout.h"
#include "tui/tui-io.h"
#include "tui/tui-regs.h"
#include "tui/tui-win.h"
#include "tui/tui-stack.h"
#include "tui/tui-windata.h"
#include "tui/tui-winsource.h"
#include "gdb_curses.h"
#include "readline/readline.h"
Functions
static void tui_new_objfile_hook (struct objfile *objfile)
static int ATTRIBUTE_PRINTF (1, 0)
static void tui_register_changed_hook (int regno)
static void tui_event_create_breakpoint (struct breakpoint *b)
static void tui_event_delete_breakpoint (struct breakpoint *b)
static void tui_event_modify_breakpoint (struct breakpoint *b)
static void tui_about_to_proceed (void)
static void tui_selected_frame_level_changed_hook (int level)
static void tui_print_frame_info_listing_hook (struct symtab *s, int line, int stopline, int noerror)
static void tui_inferior_exit (struct inferior *inf)
void tui_install_hooks (void)
void tui_remove_hooks (void)
void _initialize_tui_hooks (void)
Variables
int tui_target_has_run = 0
static int tui_refreshing_registers = 0
static struct observer * tui_bp_created_observer
static struct observer * tui_bp_deleted_observer
static struct observer * tui_bp_modified_observer
static struct observer * tui_inferior_exit_observer
static struct observer * tui_about_to_proceed_observer
Function Documentation
void _initialize_tui_hooks (void)
static int ATTRIBUTE_PRINTF (1 , 0) [static]
Definition at line 66 of file tui-hooks.c.
References _, do_cleanups(), echo(), fputs_filtered(), gdb_flush(), gdb_stdout, make_cleanup(), printf_filtered(), tui_getc(), wrap_here(), xfree(), and xstrvprintf().
static void tui_about_to_proceed (void) [static]
Definition at line 170 of file tui-hooks.c.
References target_terminal_inferior(), target_terminal_ours, tui_active, and tui_target_has_run.
Referenced by tui_install_hooks().
static void tui_event_create_breakpoint (struct breakpoint * b) [static]
Definition at line 148 of file tui-hooks.c.
References tui_update_all_breakpoint_info().
Referenced by tui_install_hooks().
static void tui_event_delete_breakpoint (struct breakpoint * b) [static]
Definition at line 156 of file tui-hooks.c.
References tui_update_all_breakpoint_info().
Referenced by tui_install_hooks().
static void tui_event_modify_breakpoint (struct breakpoint * b) [static]
Definition at line 162 of file tui-hooks.c.
References tui_update_all_breakpoint_info().
Referenced by tui_install_hooks().
static void tui_inferior_exit (struct inferior * inf) [static]
Definition at line 242 of file tui-hooks.c.
References TUI_COMMAND_MODE, tui_display_main(), tui_set_key_mode(), and tui_show_frame_info().
Referenced by tui_install_hooks().
void tui_install_hooks (void)
Definition at line 259 of file tui-hooks.c.
References deprecated_print_frame_info_listing_hook, deprecated_query_hook, deprecated_register_changed_hook, deprecated_selected_frame_level_changed_hook, observer_attach_about_to_proceed(), observer_attach_breakpoint_created(), observer_attach_breakpoint_deleted(), observer_attach_breakpoint_modified(), observer_attach_inferior_exit(), tui_about_to_proceed(), tui_event_create_breakpoint(), tui_event_delete_breakpoint(), tui_event_modify_breakpoint(), tui_inferior_exit(), tui_print_frame_info_listing_hook(), tui_register_changed_hook(), and tui_selected_frame_level_changed_hook().
Referenced by tui_enable().
static void tui_new_objfile_hook (struct objfile * objfile) [static]
Definition at line 60 of file tui-hooks.c.
References tui_active, and tui_display_main().
static void tui_print_frame_info_listing_hook (struct symtab * s, int line, int stopline, int noerror) [static]
Definition at line 229 of file tui-hooks.c.
References get_selected_frame(), select_source_symtab(), and tui_show_frame_info().
Referenced by tui_install_hooks().
static void tui_register_changed_hook (int regno) [static]
Definition at line 132 of file tui-hooks.c.
References get_selected_frame(), tui_check_data_values(), and tui_refreshing_registers.
Referenced by tui_install_hooks().
void tui_remove_hooks (void)
Definition at line 285 of file tui-hooks.c.
References deprecated_print_frame_info_listing_hook, deprecated_query_hook, deprecated_register_changed_hook, deprecated_selected_frame_level_changed_hook, observer_detach_about_to_proceed(), observer_detach_breakpoint_created(), observer_detach_breakpoint_deleted(), observer_detach_breakpoint_modified(), and observer_detach_inferior_exit().
Referenced by tui_disable().
static void tui_selected_frame_level_changed_hook (int level) [static]
Definition at line 188 of file tui-hooks.c.
References DATA_WIN, find_pc_symtab(), get_frame_pc_if_available(), get_selected_frame(), select_source_symtab(), tui_check_data_values(), tui_is_window_visible(), tui_refreshing_registers, and tui_show_frame_info().
Referenced by tui_install_hooks().
Variable Documentation
struct observer* tui_about_to_proceed_observer [static]
Definition at line 255 of file tui-hooks.c.
struct observer* tui_bp_created_observer [static]
Definition at line 251 of file tui-hooks.c.
struct observer* tui_bp_deleted_observer [static]
Definition at line 252 of file tui-hooks.c.
struct observer* tui_bp_modified_observer [static]
Definition at line 253 of file tui-hooks.c.
struct observer* tui_inferior_exit_observer [static]
Definition at line 254 of file tui-hooks.c.
int tui_refreshing_registers = 0 [static]
Definition at line 129 of file tui-hooks.c.
Referenced by tui_register_changed_hook(), and tui_selected_frame_level_changed_hook().
int tui_target_has_run = 0
Definition at line 57 of file tui-hooks.c.
Referenced by tui_about_to_proceed().