GDB (xrefs): /home/stan/gdb/src/gdb/tui/tui-regs.c File Reference
/home/stan/gdb/src/gdb/tui/tui-regs.c File Reference
#include "defs.h"
#include "arch-utils.h"
#include "tui/tui.h"
#include "tui/tui-data.h"
#include "symtab.h"
#include "gdbtypes.h"
#include "gdbcmd.h"
#include "frame.h"
#include "regcache.h"
#include "inferior.h"
#include "target.h"
#include "gdb_string.h"
#include "tui/tui-layout.h"
#include "tui/tui-win.h"
#include "tui/tui-windata.h"
#include "tui/tui-wingeneral.h"
#include "tui/tui-file.h"
#include "tui/tui-regs.h"
#include "reggroups.h"
#include "valprint.h"
#include "gdb_curses.h"
Functions
static void tui_display_register (struct tui_data_element *data, struct tui_gen_win_info *win_info)
static enum tui_status tui_show_register_group (struct reggroup *group, struct frame_info *frame, int refresh_values_only)
static enum tui_status tui_get_register (struct frame_info *frame, struct tui_data_element *data, int regnum, int *changedp)
static void tui_scroll_regs_forward_command (char *, int)
static void tui_scroll_regs_backward_command (char *, int)
int tui_last_regs_line_no (void)
int tui_line_from_reg_element_no (int element_no)
int tui_first_reg_element_no_inline (int line_no)
void tui_show_registers (struct reggroup *group)
void tui_display_registers_from (int start_element_no)
static void tui_display_reg_element_at_line (int start_element_no, int start_line_no)
int tui_display_registers_from_line (int line_no, int force_display)
void tui_check_register_values (struct frame_info *frame)
static void tui_reg_next_command (char *arg, int from_tty)
static void tui_reg_float_command (char *arg, int from_tty)
static void tui_reg_general_command (char *arg, int from_tty)
static void tui_reg_system_command (char *arg, int from_tty)
static void tui_reg_command (char *args, int from_tty)
void _initialize_tui_regs (void)
static void tui_restore_gdbout (void *ui)
static char * tui_register_format (struct frame_info *frame, int regnum)
Variables
static struct cmd_list_element * tuireglist
initialize_file_ftype _initialize_tui_regs
Function Documentation
void _initialize_tui_regs (void)
Definition at line 617 of file tui-regs.c.
References _, _initialize_tui_regs, add_cmd(), add_com(), add_prefix_cmd(), class_tui, tui_get_cmd_list(), tui_reg_command(), tui_reg_float_command(), tui_reg_general_command(), tui_reg_next_command(), tui_reg_system_command(), tui_scroll_regs_backward_command(), tui_scroll_regs_forward_command(), and xdb_commands.
void tui_check_register_values (struct frame_info * frame)
Definition at line 491 of file tui-regs.c.
References tui_gen_win_info::content, tui_data_info::current_group, display_info(), tui_data_info::display_regs, tui_data_element::highlight, tui_data_element::item_no, tui_data_info::regs_content, tui_data_info::regs_content_count, TUI_DATA_WIN, tui_display_register(), tui_get_register(), and tui_show_registers().
Referenced by tui_check_data_values().
static void tui_display_reg_element_at_line (int start_element_no, int start_line_no) [static]
Definition at line 410 of file tui-regs.c.
References TUI_DATA_WIN, tui_display_registers_from(), tui_first_reg_element_no_inline(), and tui_last_regs_line_no().
Referenced by tui_display_registers_from_line().
static void tui_display_register (struct tui_data_element * data, struct tui_gen_win_info * win_info) [static]
Definition at line 533 of file tui-regs.c.
References tui_data_element::content, tui_gen_win_info::handle, tui_data_element::highlight, tui_refresh_win(), and tui_gen_win_info::width.
Referenced by tui_check_register_values(), and tui_display_registers_from().
void tui_display_registers_from (int start_element_no)
Definition at line 308 of file tui-regs.c.
References tui_gen_win_info::content, tui_data_element::content, tui_which_element::data_window, display_info(), DONT_BOX_WINDOW, tui_gen_win_info::handle, tui_gen_win_info::height, len, tui_gen_win_info::origin, p, tui_data_info::regs_column_count, tui_data_info::regs_content, tui_data_info::regs_content_count, TUI_DATA_WIN, tui_delete_win(), tui_display_register(), tui_make_window(), tui_win_element::which_element, tui_gen_win_info::width, tui_point::x, and tui_point::y.
Referenced by tui_display_all_data(), and tui_display_reg_element_at_line().
int tui_display_registers_from_line (int line_no, int force_display)
Definition at line 448 of file tui-regs.c.
References line, TUI_DATA_WIN, tui_display_reg_element_at_line(), tui_first_reg_element_no_inline(), tui_last_regs_line_no(), and tui_line_from_reg_element_no().
Referenced by tui_display_data_from_line().
int tui_first_reg_element_no_inline (int line_no)
Definition at line 119 of file tui-regs.c.
References TUI_DATA_WIN.
Referenced by tui_display_reg_element_at_line(), tui_display_registers_from_line(), and tui_first_data_element_no_in_line().
static enum tui_status tui_get_register (struct frame_info * frame, struct tui_data_element * data, int regnum, int * changedp) [static]
Definition at line 707 of file tui-regs.c.
References tui_data_element::content, target_has_registers, TUI_FAILURE, tui_register_format(), TUI_SUCCESS, and xfree().
Referenced by tui_check_register_values(), and tui_show_register_group().
int tui_last_regs_line_no (void)
Definition at line 73 of file tui-regs.c.
References TUI_DATA_WIN.
Referenced by tui_display_data_from_line(), tui_display_reg_element_at_line(), and tui_display_registers_from_line().
int tui_line_from_reg_element_no (int element_no)
Definition at line 93 of file tui-regs.c.
References line, and TUI_DATA_WIN.
Referenced by tui_display_data_from(), tui_display_registers_from_line(), and tui_vertical_data_scroll().
static void tui_reg_command (char * args, int from_tty) [static]
Definition at line 606 of file tui-regs.c.
References _, gdb_stdout, help_list(), and printf_unfiltered().
Referenced by _initialize_tui_regs().
static void tui_reg_float_command (char * arg, int from_tty) [static]
Definition at line 586 of file tui-regs.c.
References float_reggroup, and tui_show_registers().
Referenced by _initialize_tui_regs().
static void tui_reg_general_command (char * arg, int from_tty) [static]
Definition at line 592 of file tui-regs.c.
References general_reggroup, and tui_show_registers().
Referenced by _initialize_tui_regs().
static void tui_reg_next_command (char * arg, int from_tty) [static]
Definition at line 567 of file tui-regs.c.
References get_current_arch(), reggroup_next(), TUI_DATA_WIN, and tui_show_registers().
Referenced by _initialize_tui_regs().
static void tui_reg_system_command (char * arg, int from_tty) [static]
Definition at line 598 of file tui-regs.c.
References system_reggroup, and tui_show_registers().
Referenced by _initialize_tui_regs().
static char* tui_register_format (struct frame_info * frame, int regnum) [static]
Definition at line 673 of file tui-regs.c.
References do_cleanups(), gdb_stdout, gdbarch_print_registers_info(), get_frame_arch(), make_cleanup(), p, pagination_enabled, strrchr(), tui_file_get_strbuf(), tui_restore_gdbout(), and tui_sfileopen().
Referenced by tui_get_register().
static void tui_restore_gdbout (void * ui) [static]
Definition at line 662 of file tui-regs.c.
References gdb_stdout, pagination_enabled, and ui_file_delete().
Referenced by tui_register_format().
static void tui_scroll_regs_backward_command (char * arg, int from_tty) [static]
Definition at line 740 of file tui-regs.c.
References BACKWARD_SCROLL, TUI_DATA_WIN, and tui_scroll().
Referenced by _initialize_tui_regs().
static void tui_scroll_regs_forward_command (char * arg, int from_tty) [static]
Definition at line 733 of file tui-regs.c.
References FORWARD_SCROLL, TUI_DATA_WIN, and tui_scroll().
Referenced by _initialize_tui_regs().
static enum tui_status tui_show_register_group (struct reggroup * group, struct frame_info * frame, int refresh_values_only) [static]
Definition at line 191 of file tui-regs.c.
References tui_gen_win_info::content, tui_data_info::data_content_count, DATA_WIN, tui_which_element::data_window, display_info(), gdbarch_num_pseudo_regs(), gdbarch_num_regs(), gdbarch_register_name(), gdbarch_register_reggroup_p(), get_frame_arch(), tui_data_element::highlight, tui_data_element::item_no, name, tui_data_element::name, reggroup_name(), regnum, tui_data_info::regs_content, tui_data_info::regs_content_count, tui_add_content_elements(), tui_alloc_content(), TUI_DATA_WIN, TUI_FAILURE, tui_free_data_content(), tui_get_register(), TUI_SUCCESS, tui_win_element::which_element, and xfree().
Referenced by tui_show_registers().
void tui_show_registers (struct reggroup * group)
Definition at line 134 of file tui-regs.c.
References tui_gen_win_info::content, tui_data_info::current_group, tui_which_element::data, DATA_NAME, tui_which_element::data_window, display_info(), tui_data_info::display_regs, general_reggroup, get_selected_frame(), tui_data_element::highlight, NO_REGS_STRING, tui_data_info::regs_content, tui_data_info::regs_content_count, target_has_memory, target_has_registers, target_has_stack, TUI_DATA_WIN, tui_display_all_data(), tui_enable(), tui_erase_data_content(), TUI_FAILURE, tui_set_layout_for_display_command(), tui_show_register_group(), and tui_win_element::which_element.
Referenced by tui_check_register_values(), tui_reg_float_command(), tui_reg_general_command(), tui_reg_next_command(), tui_reg_system_command(), and tui_set_layout().
Variable Documentation
initialize_file_ftype _initialize_tui_regs
Referenced by _initialize_tui_regs(), and initialize_all_files().
struct cmd_list_element* tuireglist [static]
Definition at line 603 of file tui-regs.c.