GDB (xrefs): /home/stan/gdb/src/gdb/tui/tui-stack.c File Reference
/home/stan/gdb/src/gdb/tui/tui-stack.c File Reference
#include "defs.h"
#include "symtab.h"
#include "breakpoint.h"
#include "frame.h"
#include "command.h"
#include "inferior.h"
#include "target.h"
#include "top.h"
#include "gdb-demangle.h"
#include "gdb_string.h"
#include "source.h"
#include "tui/tui.h"
#include "tui/tui-data.h"
#include "tui/tui-stack.h"
#include "tui/tui-wingeneral.h"
#include "tui/tui-source.h"
#include "tui/tui-winsource.h"
#include "tui/tui-file.h"
#include "gdb_curses.h"
Functions
static char * tui_get_function_from_frame (struct frame_info *fi)
static void tui_set_locator_fullname (const char *fullname)
static void tui_set_locator_info (struct gdbarch *gdbarch, const char *fullname, const char *procname, int lineno, CORE_ADDR addr)
static void tui_update_command (char *, int)
static char * tui_make_status_line (struct tui_locator_element *loc)
void tui_show_locator_content (void)
void tui_update_locator_fullname (const char *fullname)
void tui_show_frame_info (struct frame_info *fi)
void _initialize_tui_stack (void)
Variables
initialize_file_ftype _initialize_tui_stack
Function Documentation
void _initialize_tui_stack (void)
Definition at line 456 of file tui-stack.c.
References _, _initialize_tui_stack, add_com(), class_tui, and tui_update_command().
static char * tui_get_function_from_frame (struct frame_info * fi) [static]
Definition at line 216 of file tui-stack.c.
References demangle, get_frame_arch(), get_frame_pc(), name, p, print_address_symbolic(), strchr(), tui_file_get_strbuf(), tui_sfileopen(), and ui_file_delete().
Referenced by tui_show_frame_info().
static char* tui_make_status_line (struct tui_locator_element * loc) [static]
Definition at line 64 of file tui-stack.c.
References tui_locator_element::addr, fputs_filtered(), tui_locator_element::gdbarch, inferior_ptid, tui_locator_element::line_no, LINE_PREFIX, MAX_PID_WIDTH, MAX_TARGET_WIDTH, MIN_LINE_WIDTH, MIN_PROC_WIDTH, null_ptid, paddress(), PC_PREFIX, tui_locator_element::proc_name, PROC_PREFIX, ptid_equal(), SINGLE_KEY, strcat_to_buf(), string, target_pid_to_str(), target_shortname, tui_current_key_mode, tui_file_get_strbuf(), tui_sfileopen(), TUI_SINGLE_KEY_MODE, tui_term_width(), ui_file_delete(), xmalloc(), and xsnprintf().
Referenced by tui_show_locator_content().
static void tui_set_locator_fullname (const char * fullname) [static]
Definition at line 280 of file tui-stack.c.
References tui_gen_win_info::content, tui_locator_element::full_name, MAX_LOCATOR_ELEMENT_LEN, strcat_to_buf(), tui_locator_win_info_ptr(), and tui_set_locator_info().
Referenced by tui_set_locator_info(), and tui_update_locator_fullname().
static void tui_set_locator_info (struct gdbarch * gdbarch, const char * fullname, const char * procname, int lineno, CORE_ADDR addr) [static]
Definition at line 299 of file tui-stack.c.
References tui_locator_element::addr, tui_gen_win_info::content, tui_gen_win_info::content_size, tui_locator_element::gdbarch, tui_locator_element::line_no, MAX_LOCATOR_ELEMENT_LEN, tui_locator_element::proc_name, strcat_to_buf(), tui_alloc_content(), tui_locator_win_info_ptr(), tui_set_locator_fullname(), and tui_gen_win_info::type.
Referenced by tui_set_locator_fullname(), and tui_show_frame_info().
void tui_show_frame_info (struct frame_info * fi)
Definition at line 335 of file tui-stack.c.
References _, tui_line_or_address::addr, tui_locator_element::addr, tui_gen_win_info::content, EMPTY_SOURCE_PROMPT, find_frame_sal(), find_pc_partial_function(), tui_win_info::generic, get_frame_arch(), get_frame_pc(), get_frame_pc_if_available(), symtab_and_line::line, tui_line_or_address::line_no, tui_locator_element::line_no, tui_line_or_address::loa, tui_line_or_address::LOA_ADDRESS, tui_line_or_address::LOA_LINE, tui_which_element::locator, symtab_and_line::pc, symtab_and_line::symtab, symtab_to_fullname(), tui_addr_is_displayed(), tui_clear_source_content(), TUI_DISASM_WIN, tui_get_function_from_frame(), tui_get_low_disassembly_address(), tui_line_is_displayed(), tui_locator_win_info_ptr(), tui_set_is_exec_point_at(), tui_set_locator_info(), tui_show_locator_content(), tui_source_is_displayed(), tui_source_windows(), TUI_SRC_WIN, tui_update_exec_info(), tui_update_source_window(), tui_line_or_address::u, and tui_gen_win_info::viewport_height.
Referenced by tui_enable(), tui_inferior_exit(), tui_print_frame_info_listing_hook(), and tui_selected_frame_level_changed_hook().
void tui_show_locator_content (void)
Definition at line 246 of file tui-stack.c.
References tui_gen_win_info::content, tui_gen_win_info::content_in_use, tui_gen_win_info::handle, tui_which_element::locator, string, tui_locator_win_info_ptr(), tui_make_status_line(), tui_refresh_win(), tui_win_element::which_element, and xfree().
Referenced by make_visible_with_new_height(), show_data(), show_source_disasm_command(), show_source_or_disasm_and_command(), tui_refresh_all_win(), tui_set_key_mode(), tui_show_frame_info(), and tui_update_locator_fullname().
static void tui_update_command (char * arg, int from_tty) [static]
Definition at line 465 of file tui-stack.c.
References execute_command().
Referenced by _initialize_tui_stack().
void tui_update_locator_fullname (const char * fullname)
Definition at line 327 of file tui-stack.c.
References tui_set_locator_fullname(), and tui_show_locator_content().
Referenced by tui_display_main(), tui_show_disassem_and_update_source(), and tui_show_source().
Variable Documentation
initialize_file_ftype _initialize_tui_stack
Referenced by _initialize_tui_stack(), and initialize_all_files().