GDB (xrefs): /home/stan/gdb/src/gdb/tui/tui-data.c File Reference
/home/stan/gdb/src/gdb/tui/tui-data.c File Reference
#include "defs.h"
#include "symtab.h"
#include "tui/tui.h"
#include "tui/tui-data.h"
#include "tui/tui-wingeneral.h"
#include "gdb_string.h"
#include "gdb_curses.h"
Functions
static void free_content (tui_win_content, int, enum tui_win_type)
static void free_content_elements (tui_win_content, int, enum tui_win_type)
int tui_win_is_source_type (enum tui_win_type win_type)
int tui_win_is_auxillary (enum tui_win_type win_type)
int tui_win_has_locator (struct tui_win_info *win_info)
void tui_set_win_highlight (struct tui_win_info *win_info, int highlight)
int tui_win_resized (void)
void tui_set_win_resized_to (int resized)
struct tui_layout_def * tui_layout_def (void)
struct tui_win_info * tui_win_with_focus (void)
void tui_set_win_with_focus (struct tui_win_info *win_info)
int tui_default_tab_len (void)
void tui_set_default_tab_len (int len)
struct tui_list * tui_source_windows (void)
void tui_clear_source_windows (void)
void tui_clear_source_windows_detail (void)
void tui_add_to_source_windows (struct tui_win_info *win_info)
void tui_clear_win_detail (struct tui_win_info *win_info)
struct tui_gen_win_info * tui_source_exec_info_win_ptr (void)
struct tui_gen_win_info * tui_disassem_exec_info_win_ptr (void)
struct tui_gen_win_info * tui_locator_win_info_ptr (void)
int tui_term_height (void)
void tui_set_term_height_to (int h)
int tui_term_width (void)
void tui_set_term_width_to (int w)
enum tui_layout_type tui_current_layout (void)
void tui_set_current_layout_to (enum tui_layout_type new_layout)
struct tui_win_info * tui_next_win (struct tui_win_info *cur_win)
struct tui_win_info * tui_prev_win (struct tui_win_info *cur_win)
struct tui_win_info * tui_partial_win_by_name (char *name)
char * tui_win_name (struct tui_gen_win_info *win_info)
void tui_initialize_static_data (void)
struct tui_gen_win_info * tui_alloc_generic_win_info (void)
void tui_init_generic_part (struct tui_gen_win_info *win)
static void init_content_element (struct tui_win_element *element, enum tui_win_type type)
static void init_win_info (struct tui_win_info *win_info)
struct tui_win_info * tui_alloc_win_info (enum tui_win_type type)
tui_win_content tui_alloc_content (int num_elements, enum tui_win_type type)
int tui_add_content_elements (struct tui_gen_win_info *win_info, int num_elements)
void tui_del_window (struct tui_win_info *win_info)
void tui_free_window (struct tui_win_info *win_info)
void tui_free_all_source_wins_content (void)
void tui_free_win_content (struct tui_gen_win_info *win_info)
void tui_del_data_windows (tui_win_content content, int content_size)
void tui_free_data_content (tui_win_content content, int content_size)
Variables
struct tui_win_info * tui_win_list [MAX_MAJOR_WINDOWS]
static enum tui_layout_type current_layout = UNDEFINED_LAYOUT
static int term_height
static int term_width
static struct tui_gen_win_info _locator
static struct tui_gen_win_info exec_info [2]
static struct tui_win_info * src_win_list [2]
static struct tui_list source_windows = {src_win_list, 0}
static int default_tab_len = DEFAULT_TAB_LEN
static struct tui_win_info * win_with_focus = (struct tui_win_info *) NULL
static struct tui_layout_def layout_def
static int win_resized = FALSE
Function Documentation
static void free_content (tui_win_content content, int content_size, enum tui_win_type win_type) [static]
Definition at line 872 of file tui-data.c.
References free_content_elements(), and xfree().
Referenced by tui_free_data_content(), and tui_free_win_content().
static void free_content_elements (tui_win_content content, int content_size, enum tui_win_type type) [static]
Definition at line 887 of file tui-data.c.
References CMD_WIN, tui_which_element::command, tui_data_element::content, tui_gen_win_info::content_size, tui_which_element::data, DATA_ITEM_WIN, DATA_WIN, DISASSEM_WIN, tui_command_element::line, tui_data_element::name, SRC_WIN, TUI_REGISTER, tui_data_element::type, tui_data_element::value, tui_win_element::which_element, and xfree().
Referenced by free_content().
static void init_content_element (struct tui_win_element * element, enum tui_win_type type) [static]
Definition at line 478 of file tui-data.c.
References tui_locator_element::addr, CMD_WIN, tui_which_element::command, tui_data_element::content, tui_which_element::data, DATA_ITEM_WIN, DATA_WIN, tui_which_element::data_window, DISASSEM_WIN, EXEC_INFO_WIN, tui_locator_element::full_name, tui_source_element::has_break, tui_data_element::highlight, tui_win_element::highlight, tui_source_element::is_exec_point, tui_data_element::item_no, tui_source_element::line, tui_command_element::line, tui_line_or_address::line_no, tui_locator_element::line_no, tui_source_element::line_or_addr, tui_line_or_address::loa, tui_which_element::locator, LOCATOR_WIN, memset(), tui_data_element::name, tui_locator_element::proc_name, tui_which_element::simple_string, tui_which_element::source, SRC_WIN, tui_alloc_content(), tui_init_generic_part(), TUI_REGISTER, tui_gen_win_info::type, tui_data_element::type, tui_line_or_address::u, UNDEFINED_ITEM, tui_data_element::value, and tui_win_element::which_element.
Referenced by tui_add_content_elements(), and tui_alloc_content().
static void init_win_info (struct tui_win_info * win_info) [static]
Definition at line 528 of file tui-data.c.
References tui_line_or_address::addr, tui_win_info::can_highlight, CMD_WIN, tui_win_info::command_info, tui_command_info::cur_line, tui_command_info::curch, tui_data_info::current_group, tui_data_info::data_content, tui_data_info::data_content_count, tui_win_info::data_display_info, DATA_WIN, tui_win_info::detail, DISASSEM_WIN, tui_data_info::display_regs, tui_source_info::execution_info, tui_source_info::fullname, tui_source_info::gdbarch, tui_win_info::generic, tui_source_info::has_locator, tui_source_info::horizontal_offset, tui_win_info::is_highlighted, tui_line_or_address::loa, tui_win_info::opaque, tui_data_info::regs_column_count, tui_data_info::regs_content, tui_data_info::regs_content_count, tui_data_info::regs_display_type, tui_win_info::source_info, SRC_WIN, tui_source_info::start_line_or_addr, tui_init_generic_part(), TUI_UNDEFINED_REGS, tui_gen_win_info::type, and tui_line_or_address::u.
Referenced by tui_alloc_win_info().
int tui_add_content_elements (struct tui_gen_win_info * win_info, int num_elements)
Definition at line 632 of file tui-data.c.
References tui_gen_win_info::content, tui_gen_win_info::content_size, init_content_element(), tui_alloc_content(), tui_gen_win_info::type, and XMALLOC.
Referenced by tui_show_register_group().
void tui_add_to_source_windows (struct tui_win_info * win_info)
Definition at line 196 of file tui-data.c.
References tui_list::count, and tui_list::list.
Referenced by show_data(), and show_layout().
tui_win_content tui_alloc_content (int num_elements, enum tui_win_type type)
Definition at line 586 of file tui-data.c.
References DATA_WIN, init_content_element(), xfree(), and xmalloc().
Referenced by init_content_element(), tui_add_content_elements(), tui_alloc_source_buffer(), tui_set_exec_info_content(), tui_set_locator_info(), and tui_show_register_group().
struct tui_gen_win_info* tui_alloc_generic_win_info (void) [read]
Definition at line 446 of file tui-data.c.
References tui_init_generic_part(), and XMALLOC.
Referenced by init_and_make_win().
struct tui_win_info* tui_alloc_win_info (enum tui_win_type type) [read]
Definition at line 569 of file tui-data.c.
References tui_win_info::generic, init_win_info(), tui_gen_win_info::type, type, and XMALLOC.
Referenced by init_and_make_win().
void tui_clear_source_windows (void)
Definition at line 173 of file tui-data.c.
References tui_list::count, and tui_list::list.
Referenced by show_layout().
void tui_clear_source_windows_detail (void)
Definition at line 183 of file tui-data.c.
References tui_list::count, tui_list::list, tui_clear_win_detail(), and tui_source_windows().
Referenced by tui_add_win_to_layout().
void tui_clear_win_detail (struct tui_win_info * win_info)
Definition at line 205 of file tui-data.c.
References tui_line_or_address::addr, CMD_WIN, tui_win_info::command_info, tui_command_info::cur_line, tui_command_info::curch, tui_data_info::data_content, tui_data_info::data_content_count, tui_win_info::data_display_info, DATA_WIN, tui_win_info::detail, DISASSEM_WIN, tui_data_info::display_regs, tui_source_info::gdbarch, tui_win_info::generic, tui_source_info::horizontal_offset, tui_line_or_address::loa, tui_data_info::regs_column_count, tui_data_info::regs_content, tui_data_info::regs_content_count, tui_data_info::regs_display_type, tui_win_info::source_info, SRC_WIN, tui_source_info::start_line_or_addr, TUI_UNDEFINED_REGS, tui_gen_win_info::type, and tui_line_or_address::u.
Referenced by tui_clear_source_windows_detail().
enum tui_layout_type tui_current_layout (void)
Definition at line 300 of file tui-data.c.
References current_layout.
Referenced by extract_display_start_addr(), new_height_ok(), next_layout(), prev_layout(), show_layout(), show_source_disasm_command(), show_source_or_disasm_and_command(), tui_add_win_to_layout(), tui_adjust_win_heights(), tui_resize_all(), tui_rl_change_windows(), tui_rl_delete_other_windows(), tui_set_layout(), tui_set_layout_for_display_command(), tui_show_disassem(), tui_show_disassem_and_update_source(), tui_update_source_window_as_is(), tui_update_source_windows_with_addr(), and tui_update_source_windows_with_line().
int tui_default_tab_len (void)
Definition at line 145 of file tui-data.c.
References default_tab_len.
Referenced by tui_set_disassem_content(), and tui_set_source_content().
void tui_del_data_windows (tui_win_content content, int content_size)
Definition at line 816 of file tui-data.c.
References tui_which_element::data_window, tui_gen_win_info::handle, tui_gen_win_info::is_visible, tui_delete_win(), and tui_win_element::which_element.
Referenced by tui_del_window().
void tui_del_window (struct tui_win_info * win_info)
Definition at line 669 of file tui-data.c.
References tui_gen_win_info::content, tui_data_info::data_content, tui_data_info::data_content_count, tui_win_info::data_display_info, DATA_WIN, tui_win_info::detail, DISASSEM_WIN, tui_source_info::execution_info, tui_source_info::fullname, tui_win_info::generic, tui_gen_win_info::handle, tui_gen_win_info::is_visible, tui_data_info::regs_content, tui_data_info::regs_content_count, tui_win_info::source_info, SRC_WIN, tui_del_data_windows(), tui_delete_win(), tui_locator_win_info_ptr(), tui_gen_win_info::type, and xfree().
struct tui_gen_win_info* tui_disassem_exec_info_win_ptr (void) [read]
Definition at line 251 of file tui-data.c.
References exec_info.
Referenced by make_source_or_disasm_window(), and tui_initialize_static_data().
void tui_free_all_source_wins_content (void)
Definition at line 784 of file tui-data.c.
References tui_win_info::detail, tui_source_info::execution_info, tui_win_info::generic, tui_win_info::source_info, tui_free_win_content(), and tui_source_windows().
Referenced by show_layout().
void tui_free_data_content (tui_win_content content, int content_size)
Definition at line 840 of file tui-data.c.
References tui_gen_win_info::content_size, DATA_WIN, tui_which_element::data_window, free_content(), tui_gen_win_info::handle, tui_delete_win(), tui_free_win_content(), and tui_win_element::which_element.
Referenced by tui_free_window(), and tui_show_register_group().
void tui_free_win_content (struct tui_gen_win_info * win_info)
Definition at line 802 of file tui-data.c.
References tui_gen_win_info::content, tui_gen_win_info::content_size, free_content(), and tui_gen_win_info::type.
Referenced by make_visible_with_new_height(), tui_free_all_source_wins_content(), tui_free_data_content(), and tui_free_window().
void tui_free_window (struct tui_win_info * win_info)
Definition at line 719 of file tui-data.c.
References tui_gen_win_info::content, tui_gen_win_info::content_size, tui_data_info::data_content, tui_data_info::data_content_count, tui_win_info::data_display_info, DATA_WIN, tui_win_info::detail, DISASSEM_WIN, tui_data_info::display_regs, tui_source_info::execution_info, tui_source_info::fullname, tui_win_info::generic, tui_gen_win_info::handle, tui_data_info::regs_column_count, tui_data_info::regs_content, tui_data_info::regs_content_count, tui_data_info::regs_display_type, tui_win_info::source_info, SRC_WIN, tui_gen_win_info::title, tui_delete_win(), tui_free_data_content(), tui_free_win_content(), tui_locator_win_info_ptr(), TUI_UNDEFINED_REGS, tui_gen_win_info::type, and xfree().
Referenced by tui_resize_all().
void tui_init_generic_part (struct tui_gen_win_info * win)
Definition at line 458 of file tui-data.c.
References tui_gen_win_info::content, tui_gen_win_info::content_in_use, tui_gen_win_info::content_size, tui_gen_win_info::handle, tui_gen_win_info::height, tui_gen_win_info::is_visible, tui_gen_win_info::last_visible_line, tui_gen_win_info::origin, tui_gen_win_info::title, tui_gen_win_info::viewport_height, tui_gen_win_info::width, tui_point::x, and tui_point::y.
Referenced by init_content_element(), init_win_info(), tui_alloc_generic_win_info(), and tui_initialize_static_data().
void tui_initialize_static_data (void)
Definition at line 437 of file tui-data.c.
References tui_disassem_exec_info_win_ptr(), tui_init_generic_part(), tui_locator_win_info_ptr(), and tui_source_exec_info_win_ptr().
Referenced by tui_init().
struct tui_layout_def* tui_layout_def (void) [read]
Definition at line 121 of file tui-data.c.
References layout_def.
Referenced by tui_set_layout(), tui_toggle_layout_command(), and tui_toggle_split_layout_command().
struct tui_gen_win_info* tui_locator_win_info_ptr (void) [read]
Definition at line 260 of file tui-data.c.
References _locator.
Referenced by make_invisible_and_set_new_height(), make_visible_with_new_height(), show_data(), show_layout(), show_source_disasm_command(), show_source_or_disasm_and_command(), tui_adjust_win_heights(), tui_del_window(), tui_free_window(), tui_get_begin_asm_address(), tui_initialize_static_data(), tui_refresh_all(), tui_resize_all(), tui_set_disassem_content(), tui_set_locator_fullname(), tui_set_locator_info(), tui_set_source_content(), tui_show_frame_info(), tui_show_locator_content(), and tui_source_is_displayed().
struct tui_win_info* tui_next_win (struct tui_win_info * cur_win) [read]
Definition at line 322 of file tui-data.c.
References CMD_WIN, tui_win_info::generic, SRC_WIN, tui_win_list, tui_gen_win_info::type, and type.
Referenced by tui_rl_other_window(), and tui_set_focus().
struct tui_win_info* tui_partial_win_by_name (char * name) [read]
Definition at line 381 of file tui-data.c.
References MAX_MAJOR_WINDOWS, tui_win_list, and tui_win_name().
Referenced by parse_scrolling_args(), tui_set_focus(), and tui_set_win_height().
struct tui_win_info* tui_prev_win (struct tui_win_info * cur_win) [read]
Definition at line 352 of file tui-data.c.
References CMD_WIN, tui_win_info::generic, SRC_WIN, tui_win_list, tui_gen_win_info::type, and type.
Referenced by tui_set_focus().
void tui_set_current_layout_to (enum tui_layout_type new_layout)
Definition at line 308 of file tui-data.c.
References current_layout.
Referenced by show_data(), show_source_disasm_command(), and show_source_or_disasm_and_command().
void tui_set_default_tab_len (int len)
Definition at line 153 of file tui-data.c.
References default_tab_len, and len.
Referenced by tui_set_tab_width_command().
void tui_set_term_height_to (int h)
Definition at line 276 of file tui-data.c.
References term_height.
Referenced by tui_enable(), and tui_resize_all().
void tui_set_term_width_to (int w)
Definition at line 292 of file tui-data.c.
References term_width.
Referenced by tui_enable(), and tui_resize_all().
void tui_set_win_highlight (struct tui_win_info * win_info, int highlight)
Definition at line 92 of file tui-data.c.
References tui_win_info::is_highlighted.
Referenced by tui_highlight_win(), and tui_unhighlight_win().
void tui_set_win_resized_to (int resized)
Definition at line 113 of file tui-data.c.
References win_resized.
Referenced by tui_handle_resize_during_io().
void tui_set_win_with_focus (struct tui_win_info * win_info)
Definition at line 137 of file tui-data.c.
Referenced by tui_set_win_focus_to().
struct tui_gen_win_info* tui_source_exec_info_win_ptr (void) [read]
Definition at line 243 of file tui-data.c.
References exec_info.
Referenced by make_source_or_disasm_window(), and tui_initialize_static_data().
struct tui_list* tui_source_windows (void) [read]
Definition at line 163 of file tui-data.c.
References source_windows.
Referenced by new_height_ok(), parse_scrolling_args(), tui_adjust_win_heights(), tui_clear_source_windows_detail(), tui_display_main(), tui_free_all_source_wins_content(), tui_resize_all(), tui_show_frame_info(), tui_update_all_breakpoint_info(), and tui_update_source_windows_with_addr().
int tui_term_height (void)
Definition at line 268 of file tui-data.c.
References term_height.
Referenced by new_height_ok(), show_data(), show_source_disasm_command(), show_source_or_disasm_and_command(), tui_default_win_height(), tui_resize_all(), tui_update_gdb_sizes(), and tui_xdb_set_win_height().
int tui_term_width (void)
Definition at line 284 of file tui-data.c.
References term_width.
Referenced by make_command_window(), make_data_window(), make_source_or_disasm_window(), show_data(), show_source_disasm_command(), show_source_or_disasm_and_command(), tui_make_status_line(), tui_resize_all(), and tui_update_gdb_sizes().
int tui_win_has_locator (struct tui_win_info * win_info)
Definition at line 85 of file tui-data.c.
References tui_win_info::detail, tui_source_info::has_locator, and tui_win_info::source_info.
Referenced by make_invisible_and_set_new_height(), and make_visible_with_new_height().
int tui_win_is_auxillary (enum tui_win_type win_type)
Definition at line 79 of file tui-data.c.
References MAX_MAJOR_WINDOWS.
Referenced by init_and_make_win(), and make_visible().
int tui_win_is_source_type (enum tui_win_type win_type)
Definition at line 73 of file tui-data.c.
References DISASSEM_WIN, and SRC_WIN.
Referenced by make_all_visible().
char* tui_win_name (struct tui_gen_win_info * win_info)
Definition at line 409 of file tui-data.c.
References CMD_NAME, CMD_WIN, DATA_NAME, DATA_WIN, DISASSEM_NAME, DISASSEM_WIN, name, SRC_NAME, SRC_WIN, and tui_gen_win_info::type.
Referenced by tui_all_windows_info(), tui_partial_win_by_name(), and tui_set_focus().
int tui_win_resized (void)
Definition at line 105 of file tui-data.c.
References win_resized.
Referenced by tui_handle_resize_during_io().
struct tui_win_info* tui_win_with_focus (void) [read]
Definition at line 129 of file tui-data.c.
References win_with_focus.
Referenced by parse_scrolling_args(), tui_all_windows_info(), tui_dispatch_ctrl_char(), tui_resize_all(), tui_rl_other_window(), tui_set_focus(), tui_set_layout(), tui_set_win_focus_to(), tui_show_disassem(), and tui_update_source_window_as_is().
Variable Documentation
struct tui_gen_win_info _locator [static]
Definition at line 41 of file tui-data.c.
Referenced by tui_locator_win_info_ptr().
enum tui_layout_type current_layout = UNDEFINED_LAYOUT [static]
Definition at line 39 of file tui-data.c.
Referenced by tui_current_layout(), and tui_set_current_layout_to().
int default_tab_len = DEFAULT_TAB_LEN [static]
Definition at line 45 of file tui-data.c.
Referenced by tui_default_tab_len(), and tui_set_default_tab_len().
struct tui_gen_win_info exec_info[2] [static]
Definition at line 42 of file tui-data.c.
Referenced by solib_aix_solib_create_inferior_hook(), tui_disassem_exec_info_win_ptr(), tui_erase_exec_info_content(), tui_show_exec_info_content(), and tui_source_exec_info_win_ptr().
struct tui_layout_def layout_def [static]
Initial value:
 {
  SRC_WIN,
  FALSE,
  TUI_UNDEFINED_REGS,
  TUI_SFLOAT_REGS}
Definition at line 47 of file tui-data.c.
Referenced by tui_layout_def(), tui_set_layout(), tui_toggle_layout_command(), and tui_toggle_split_layout_command().
struct tui_list source_windows = {src_win_list, 0} [static]
Definition at line 44 of file tui-data.c.
Referenced by tui_source_windows().
struct tui_win_info* src_win_list[2] [static]
Definition at line 43 of file tui-data.c.
int term_height [static]
Definition at line 40 of file tui-data.c.
Referenced by tui_set_term_height_to(), and tui_term_height().
int term_width [static]
Definition at line 40 of file tui-data.c.
Referenced by tui_set_term_width_to(), and tui_term_width().
struct tui_win_info* tui_win_list[MAX_MAJOR_WINDOWS]
Definition at line 34 of file tui-data.c.
Referenced by make_all_visible(), show_data(), show_layout(), tui_adjust_win_heights(), tui_all_windows_info(), tui_default_win_height(), tui_default_win_viewport_height(), tui_handle_xdb_layout(), tui_is_window_visible(), tui_next_win(), tui_partial_win_by_name(), tui_prev_win(), tui_refresh_all_win(), tui_resize_all(), and tui_xdb_set_win_height().
int win_resized = FALSE [static]
Definition at line 53 of file tui-data.c.
Referenced by tui_set_win_resized_to(), and tui_win_resized().
struct tui_win_info* win_with_focus = (struct tui_win_info *) NULL [static]
Definition at line 46 of file tui-data.c.
Referenced by tui_all_windows_info(), tui_resize_all(), tui_set_layout(), tui_set_win_focus_to(), tui_show_disassem(), and tui_win_with_focus().