GDB (xrefs): /home/stan/gdb/src/gdb/tui/tui-out.c File Reference
/home/stan/gdb/src/gdb/tui/tui-out.c File Reference
#include "defs.h"
#include "ui-out.h"
#include "cli-out.h"
#include "tui.h"
#include "gdb_string.h"
#include "gdb_assert.h"
Classes
struct tui_ui_out_data
Typedefs
typedef struct tui_ui_out_data tui_out_data
Functions
static void tui_field_int (struct ui_out *uiout, int fldno, int width, enum ui_align alignment, const char *fldname, int value)
static void tui_field_string (struct ui_out *uiout, int fldno, int width, enum ui_align align, const char *fldname, const char *string)
static void tui_field_fmt (struct ui_out *uiout, int fldno, int width, enum ui_align align, const char *fldname, const char *format, va_list args)
static void tui_text (struct ui_out *uiout, const char *string)
struct ui_out * tui_out_new (struct ui_file *stream)
void _initialize_tui_out (void)
Variables
static struct ui_out_impl tui_ui_out_impl
Typedef Documentation
typedef struct tui_ui_out_data tui_out_data
Definition at line 37 of file tui-out.c.
Function Documentation
void _initialize_tui_out (void)
static void tui_field_fmt (struct ui_out * uiout, int fldno, int width, enum ui_align align, const char * fldname, const char * format, va_list args) [static]
Definition at line 107 of file tui-out.c.
References tui_ui_out_data::base, cli_ui_out_impl, ui_out_impl::field_fmt, tui_ui_out_data::start_of_line, cli_ui_out_data::suppress_output, and ui_out_data().
static void tui_field_int (struct ui_out * uiout, int fldno, int width, enum ui_align alignment, const char * fldname, int value) [static]
Definition at line 48 of file tui-out.c.
References tui_ui_out_data::base, cli_ui_out_impl, ui_out_impl::field_int, tui_ui_out_data::line, tui_ui_out_data::start_of_line, cli_ui_out_data::suppress_output, and ui_out_data().
static void tui_field_string (struct ui_out * uiout, int fldno, int width, enum ui_align align, const char * fldname, const char * string) [static]
Definition at line 76 of file tui-out.c.
References tui_ui_out_data::base, cli_ui_out_impl, ui_out_impl::field_string, tui_ui_out_data::line, tui_ui_out_data::start_of_line, cli_ui_out_data::suppress_output, tui_show_source(), and ui_out_data().
struct ui_out* tui_out_new (struct ui_file * stream) [read]
Definition at line 149 of file tui-out.c.
References tui_ui_out_data::base, cli_out_data_ctor(), ui_out::data, flags, tui_ui_out_data::line, tui_ui_out_data::start_of_line, tui_ui_out_impl, ui_out_new(), and XMALLOC.
Referenced by tui_initialize_io().
static void tui_text (struct ui_out * uiout, const char * string) [static]
Definition at line 126 of file tui-out.c.
References tui_ui_out_data::base, cli_ui_out_impl, tui_ui_out_data::line, tui_ui_out_data::start_of_line, strchr(), cli_ui_out_data::suppress_output, ui_out_impl::text, and ui_out_data().
Variable Documentation
struct ui_out_impl tui_ui_out_impl [static]
Definition at line 43 of file tui-out.c.
Referenced by tui_out_new().