GDB (xrefs): /home/stan/gdb/src/gdb/tui/tui-winsource.h File Reference
/home/stan/gdb/src/gdb/tui/tui-winsource.h File Reference
#include "tui/tui-data.h"
Defines
#define SCROLL_THRESHOLD 2 /* Threshold for lazy scroll. */
Functions
void tui_update_all_breakpoint_info (void)
int tui_update_breakpoint_info (struct tui_win_info *win, int current_only)
void tui_display_main (void)
void tui_update_source_window (struct tui_win_info *, struct gdbarch *, struct symtab *, struct tui_line_or_address, int)
void tui_update_source_window_as_is (struct tui_win_info *, struct gdbarch *, struct symtab *, struct tui_line_or_address, int)
void tui_update_source_windows_with_addr (struct gdbarch *, CORE_ADDR)
void tui_update_source_windows_with_line (struct symtab *, int)
void tui_clear_source_content (struct tui_win_info *, int)
void tui_erase_source_content (struct tui_win_info *, int)
void tui_show_source_content (struct tui_win_info *)
void tui_horizontal_source_scroll (struct tui_win_info *, enum tui_scroll_direction, int)
enum tui_status tui_set_exec_info_content (struct tui_win_info *)
void tui_show_exec_info_content (struct tui_win_info *)
void tui_erase_exec_info_content (struct tui_win_info *)
void tui_clear_exec_info_content (struct tui_win_info *)
void tui_update_exec_info (struct tui_win_info *)
void tui_set_is_exec_point_at (struct tui_line_or_address, struct tui_win_info *)
enum tui_status tui_alloc_source_buffer (struct tui_win_info *)
int tui_line_is_displayed (int, struct tui_win_info *, int)
int tui_addr_is_displayed (CORE_ADDR, struct tui_win_info *, int)
Define Documentation
#define SCROLL_THRESHOLD 2 /* Threshold for lazy scroll. */
Definition at line 77 of file tui-winsource.h.
Referenced by tui_addr_is_displayed(), and tui_line_is_displayed().
Function Documentation
int tui_addr_is_displayed (CORE_ADDR , struct tui_win_info * , int)
Definition at line 687 of file tui-winsource.c.
References tui_line_or_address::addr, tui_gen_win_info::content, tui_win_info::generic, tui_source_element::line_or_addr, SCROLL_THRESHOLD, tui_which_element::source, tui_line_or_address::u, and tui_win_element::which_element.
Referenced by tui_show_frame_info().
enum tui_status tui_alloc_source_buffer (struct tui_win_info *)
Definition at line 610 of file tui-winsource.c.
References tui_gen_win_info::content, fputs_unfiltered(), gdb_stderr, tui_win_info::generic, tui_gen_win_info::height, SRC_WIN, tui_alloc_content(), TUI_FAILURE, TUI_SUCCESS, tui_gen_win_info::width, xfree(), and xmalloc().
Referenced by tui_set_disassem_content(), and tui_set_source_content().
void tui_clear_exec_info_content (struct tui_win_info *)
Definition at line 593 of file tui-winsource.c.
References tui_gen_win_info::content_in_use, tui_win_info::detail, tui_source_info::execution_info, tui_win_info::source_info, and tui_erase_exec_info_content().
Referenced by tui_update_source_window_as_is(), and tui_update_source_windows_with_addr().
void tui_clear_source_content (struct tui_win_info * , int)
Definition at line 214 of file tui-winsource.c.
References tui_gen_win_info::content, tui_gen_win_info::content_in_use, tui_gen_win_info::content_size, tui_win_info::generic, tui_source_element::has_break, tui_source_element::is_exec_point, tui_which_element::source, tui_erase_source_content(), and tui_win_element::which_element.
Referenced by tui_show_frame_info(), tui_update_source_window_as_is(), and tui_update_source_windows_with_addr().
void tui_display_main (void)
Definition at line 47 of file tui-winsource.c.
References find_pc_line(), symtab_and_line::symtab, symtab_to_fullname(), tui_get_begin_asm_address(), tui_source_windows(), tui_update_locator_fullname(), and tui_update_source_windows_with_addr().
Referenced by tui_inferior_exit(), and tui_new_objfile_hook().
void tui_erase_exec_info_content (struct tui_win_info *)
Definition at line 583 of file tui-winsource.c.
References tui_win_info::detail, exec_info, tui_source_info::execution_info, tui_gen_win_info::handle, tui_win_info::source_info, and tui_refresh_win().
Referenced by tui_clear_exec_info_content(), and tui_refresh_all_win().
void tui_erase_source_content (struct tui_win_info * , int)
Definition at line 236 of file tui-winsource.c.
References EMPTY_SOURCE_PROMPT, tui_win_info::generic, tui_gen_win_info::handle, tui_gen_win_info::height, NO_DISASSEM_STRING, NO_SRC_STRING, SRC_WIN, tui_check_and_display_highlight_if_needed(), tui_refresh_win(), tui_set_source_content_nil(), tui_gen_win_info::type, and tui_gen_win_info::width.
Referenced by tui_adjust_win_heights(), tui_clear_source_content(), tui_resize_all(), and tui_show_source_content().
void tui_horizontal_source_scroll (struct tui_win_info * , enum tui_scroll_direction, int)
Definition at line 321 of file tui-winsource.c.
References tui_gen_win_info::content, tui_win_info::detail, find_pc_symtab(), tui_source_info::gdbarch, tui_win_info::generic, get_current_source_symtab_and_line(), get_frame_pc(), get_selected_frame(), tui_source_info::horizontal_offset, LEFT_SCROLL, offset, tui_win_info::source_info, SRC_WIN, symtab_and_line::symtab, tui_update_source_window_as_is(), and tui_gen_win_info::type.
Referenced by tui_scroll_left(), and tui_scroll_right().
int tui_line_is_displayed (int , struct tui_win_info * , int)
Definition at line 656 of file tui-winsource.c.
References tui_gen_win_info::content, tui_gen_win_info::content_size, tui_win_info::generic, line, tui_line_or_address::line_no, tui_source_element::line_or_addr, SCROLL_THRESHOLD, tui_which_element::source, tui_line_or_address::u, and tui_win_element::which_element.
Referenced by tui_show_frame_info().
enum tui_status tui_set_exec_info_content (struct tui_win_info *)
Definition at line 501 of file tui-winsource.c.
References tui_gen_win_info::content, tui_gen_win_info::content_size, tui_win_info::detail, tui_source_info::execution_info, tui_win_info::generic, tui_source_element::has_break, tui_gen_win_info::height, tui_source_element::is_exec_point, memset(), tui_which_element::simple_string, tui_which_element::source, tui_win_info::source_info, tui_alloc_content(), TUI_BP_BREAK_POS, TUI_BP_DISABLED, TUI_BP_ENABLED, TUI_BP_HARDWARE, TUI_BP_HIT, TUI_BP_HIT_POS, TUI_EXEC_POS, TUI_EXECINFO_SIZE, TUI_FAILURE, TUI_SUCCESS, tui_update_breakpoint_info(), tui_gen_win_info::type, and tui_win_element::which_element.
Referenced by tui_update_exec_info().
void tui_set_is_exec_point_at (struct tui_line_or_address , struct tui_win_info *)
Definition at line 367 of file tui-winsource.c.
References tui_line_or_address::addr, tui_gen_win_info::content, gdb_assert, tui_win_info::generic, tui_source_element::is_exec_point, tui_line_or_address::line_no, tui_source_element::line_or_addr, tui_line_or_address::loa, tui_line_or_address::LOA_ADDRESS, tui_line_or_address::LOA_LINE, tui_which_element::source, tui_refresh_win(), tui_show_source_line(), tui_line_or_address::u, and tui_win_element::which_element.
Referenced by tui_show_frame_info().
void tui_show_exec_info_content (struct tui_win_info *)
Definition at line 563 of file tui-winsource.c.
References tui_gen_win_info::content, tui_gen_win_info::content_in_use, tui_gen_win_info::content_size, tui_win_info::detail, exec_info, tui_source_info::execution_info, tui_gen_win_info::handle, tui_win_info::source_info, and tui_refresh_win().
Referenced by tui_update_exec_info().
void tui_show_source_content (struct tui_win_info *)
Definition at line 301 of file tui-winsource.c.
References tui_gen_win_info::content_in_use, tui_gen_win_info::content_size, tui_win_info::generic, tui_check_and_display_highlight_if_needed(), tui_erase_source_content(), tui_refresh_win(), and tui_show_source_line().
Referenced by show_source_disasm_command(), show_source_or_disasm_and_command(), tui_refresh_all_win(), and tui_update_source_window_as_is().
void tui_update_all_breakpoint_info (void)
Definition at line 406 of file tui-winsource.c.
References tui_list::count, tui_list::list, tui_source_windows(), tui_update_breakpoint_info(), and tui_update_exec_info().
Referenced by tui_event_create_breakpoint(), tui_event_delete_breakpoint(), and tui_event_modify_breakpoint().
int tui_update_breakpoint_info (struct tui_win_info * win, int current_only)
Definition at line 430 of file tui-winsource.c.
References tui_line_or_address::addr, bp_location::address, bp_disabled, bp_hardware_breakpoint, breakpoint_chain, bp_location::cond, tui_gen_win_info::content, tui_gen_win_info::content_size, tui_win_info::detail, breakpoint::enable_state, tui_source_info::fullname, gdb_assert, tui_win_info::generic, tui_source_element::has_break, breakpoint::hit_count, tui_source_element::is_exec_point, line, tui_line_or_address::line_no, bp_location::line_number, tui_source_element::line_or_addr, tui_line_or_address::loa, breakpoint::loc, bp_location::next, breakpoint::next, tui_win_info::source_info, bp_location::symtab, symtab_to_fullname(), TUI_BP_CONDITIONAL, TUI_BP_DISABLED, TUI_BP_ENABLED, TUI_BP_HARDWARE, TUI_BP_HIT, TUI_DISASM_WIN, TUI_SRC_WIN, breakpoint::type, and tui_line_or_address::u.
Referenced by tui_set_exec_info_content(), tui_update_all_breakpoint_info(), and tui_update_source_window_as_is().
void tui_update_exec_info (struct tui_win_info *)
Definition at line 603 of file tui-winsource.c.
References tui_set_exec_info_content(), and tui_show_exec_info_content().
Referenced by tui_refresh_all_win(), tui_show_frame_info(), tui_update_all_breakpoint_info(), and tui_update_source_window_as_is().
void tui_update_source_window (struct tui_win_info * , struct gdbarch * , struct symtab * , struct tui_line_or_address , int)
Definition at line 74 of file tui-winsource.c.
References tui_win_info::detail, tui_source_info::horizontal_offset, tui_win_info::source_info, and tui_update_source_window_as_is().
Referenced by make_visible_with_new_height(), tui_show_disassem(), tui_show_disassem_and_update_source(), and tui_show_frame_info().
void tui_update_source_window_as_is (struct tui_win_info * , struct gdbarch * , struct symtab * , struct tui_line_or_address , int)
Definition at line 90 of file tui-winsource.c.
References tui_line_or_address::addr, tui_gen_win_info::content_size, EMPTY_SOURCE_PROMPT, tui_win_info::generic, init_sal(), symtab_and_line::line, tui_line_or_address::line_no, symtab::objfile, objfile::pspace, symtab_and_line::pspace, set_current_source_symtab_and_line(), SRC_DISASSEM_COMMAND, SRC_WIN, symtab_and_line::symtab, tui_clear_exec_info_content(), tui_clear_source_content(), tui_current_layout(), TUI_DISASM_WIN, TUI_FAILURE, tui_set_disassem_content(), tui_set_source_content(), tui_set_win_focus_to(), tui_show_source_content(), TUI_SRC_WIN, tui_update_breakpoint_info(), tui_update_exec_info(), tui_win_with_focus(), tui_gen_win_info::type, and tui_line_or_address::u.
Referenced by tui_horizontal_source_scroll(), tui_show_symtab_source(), tui_update_source_window(), and tui_vertical_disassem_scroll().
void tui_update_source_windows_with_addr (struct gdbarch * , CORE_ADDR)
Definition at line 139 of file tui-winsource.c.
References DISASSEM_COMMAND, DISASSEM_DATA_COMMAND, EMPTY_SOURCE_PROMPT, find_pc_line(), symtab_and_line::line, tui_line_or_address::line_no, tui_line_or_address::loa, tui_line_or_address::LOA_LINE, SRC_DISASSEM_COMMAND, symtab_and_line::symtab, tui_clear_exec_info_content(), tui_clear_source_content(), tui_current_layout(), tui_show_disassem(), tui_show_disassem_and_update_source(), tui_show_symtab_source(), tui_source_windows(), and tui_line_or_address::u.
Referenced by tui_display_main(), tui_set_layout(), tui_show_assembly(), and tui_update_source_windows_with_line().
void tui_update_source_windows_with_line (struct symtab * , int)
Definition at line 180 of file tui-winsource.c.
References DISASSEM_COMMAND, DISASSEM_DATA_COMMAND, find_line_pc(), get_objfile_arch(), line, tui_line_or_address::line_no, tui_line_or_address::loa, tui_line_or_address::LOA_LINE, symtab::objfile, SRC_DISASSEM_COMMAND, tui_current_layout(), tui_show_disassem(), tui_show_symtab_source(), tui_update_source_windows_with_addr(), and tui_line_or_address::u.
Referenced by tui_show_source().