GDB (xrefs): /home/stan/gdb/src/gdb/tui/tui-wingeneral.c File Reference
/home/stan/gdb/src/gdb/tui/tui-wingeneral.c File Reference
#include "defs.h"
#include "tui/tui.h"
#include "tui/tui-data.h"
#include "tui/tui-wingeneral.h"
#include "tui/tui-win.h"
#include "gdb_curses.h"
Functions
void tui_refresh_win (struct tui_gen_win_info *win_info)
void tui_delete_win (WINDOW *window)
static void box_win (struct tui_gen_win_info *win_info, int highlight_flag)
void tui_unhighlight_win (struct tui_win_info *win_info)
void tui_highlight_win (struct tui_win_info *win_info)
void tui_check_and_display_highlight_if_needed (struct tui_win_info *win_info)
void tui_make_window (struct tui_gen_win_info *win_info, int box_it)
static void make_visible (struct tui_gen_win_info *win_info, int visible)
void tui_make_visible (struct tui_gen_win_info *win_info)
void tui_make_invisible (struct tui_gen_win_info *win_info)
static void make_all_visible (int visible)
void tui_make_all_visible (void)
void tui_make_all_invisible (void)
void tui_refresh_all (struct tui_win_info **list)
Function Documentation
static void box_win (struct tui_gen_win_info * win_info, int highlight_flag) [static]
Definition at line 80 of file tui-wingeneral.c.
References tui_gen_win_info::handle, HILITE, tui_gen_win_info::title, tui_active_border_attrs, tui_border_attrs, tui_border_hline, tui_border_llcorner, tui_border_lrcorner, tui_border_ulcorner, tui_border_urcorner, and tui_border_vline.
Referenced by tui_highlight_win(), tui_make_window(), and tui_unhighlight_win().
static void make_all_visible (int visible) [static]
Definition at line 219 of file tui-wingeneral.c.
References CMD_WIN, make_visible(), MAX_MAJOR_WINDOWS, tui_win_is_source_type(), and tui_win_list.
Referenced by tui_make_all_invisible(), and tui_make_all_visible().
static void make_visible (struct tui_gen_win_info * win_info, int visible) [static]
Definition at line 175 of file tui-wingeneral.c.
References CMD_WIN, tui_gen_win_info::handle, tui_gen_win_info::is_visible, tui_delete_win(), tui_make_window(), tui_win_is_auxillary(), and tui_gen_win_info::type.
Referenced by make_all_visible(), tui_make_invisible(), and tui_make_visible().
void tui_check_and_display_highlight_if_needed (struct tui_win_info * win_info)
Definition at line 137 of file tui-wingeneral.c.
References CMD_WIN, tui_win_info::generic, tui_win_info::is_highlighted, tui_highlight_win(), tui_unhighlight_win(), and tui_gen_win_info::type.
Referenced by make_visible_with_new_height(), tui_display_all_data(), tui_display_data_from_line(), tui_erase_data_content(), tui_erase_source_content(), tui_refresh_all_win(), and tui_show_source_content().
void tui_delete_win (WINDOW * window)
Definition at line 69 of file tui-wingeneral.c.
Referenced by make_invisible_and_set_new_height(), make_visible(), tui_del_data_windows(), tui_del_window(), tui_delete_data_content_windows(), tui_display_registers_from(), tui_free_data_content(), and tui_free_window().
void tui_highlight_win (struct tui_win_info * win_info)
Definition at line 124 of file tui-wingeneral.c.
References box_win(), tui_win_info::can_highlight, tui_win_info::generic, tui_gen_win_info::handle, HILITE, and tui_set_win_highlight().
Referenced by tui_check_and_display_highlight_if_needed(), and tui_set_win_focus_to().
void tui_make_all_invisible (void)
Definition at line 245 of file tui-wingeneral.c.
References make_all_visible().
Referenced by show_data(), and show_layout().
void tui_make_all_visible (void)
Definition at line 239 of file tui-wingeneral.c.
References make_all_visible().
void tui_make_invisible (struct tui_gen_win_info * win_info)
Definition at line 210 of file tui-wingeneral.c.
References make_visible().
Referenced by make_invisible_and_set_new_height(), show_data(), and show_layout().
void tui_make_visible (struct tui_gen_win_info * win_info)
Definition at line 204 of file tui-wingeneral.c.
References make_visible().
Referenced by make_visible_with_new_height(), show_data(), show_source_disasm_command(), and show_source_or_disasm_and_command().
void tui_make_window (struct tui_gen_win_info * win_info, int box_it)
Definition at line 152 of file tui-wingeneral.c.
References box_win(), BOX_WINDOW, tui_gen_win_info::handle, tui_gen_win_info::height, tui_gen_win_info::is_visible, NO_HILITE, tui_gen_win_info::origin, tui_gen_win_info::width, tui_point::x, and tui_point::y.
Referenced by init_and_make_win(), make_visible(), and tui_display_registers_from().
void tui_refresh_all (struct tui_win_info ** list)
Definition at line 253 of file tui-wingeneral.c.
References DISASSEM_WIN, tui_source_info::execution_info, tui_gen_win_info::handle, tui_gen_win_info::is_visible, MAX_MAJOR_WINDOWS, tui_win_info::source_info, SRC_WIN, tui_locator_win_info_ptr(), tui_refresh_win(), and type.
Referenced by show_layout(), and tui_refresh_all_win().
void tui_refresh_win (struct tui_gen_win_info * win_info)
Definition at line 36 of file tui-wingeneral.c.
References CMD_WIN, tui_gen_win_info::content, tui_gen_win_info::content_size, DATA_WIN, tui_gen_win_info::handle, and tui_gen_win_info::type.
Referenced by show_source_disasm_command(), show_source_or_disasm_and_command(), tui_display_register(), tui_erase_exec_info_content(), tui_erase_source_content(), tui_refresh_all(), tui_set_is_exec_point_at(), tui_show_exec_info_content(), tui_show_locator_content(), and tui_show_source_content().
void tui_unhighlight_win (struct tui_win_info * win_info)
Definition at line 111 of file tui-wingeneral.c.
References box_win(), tui_win_info::generic, tui_gen_win_info::handle, NO_HILITE, and tui_set_win_highlight().
Referenced by tui_check_and_display_highlight_if_needed(), and tui_set_win_focus_to().