GDB (xrefs): /home/stan/gdb/src/gdb/tui/tui-interp.c File Reference
/home/stan/gdb/src/gdb/tui/tui-interp.c File Reference
#include "defs.h"
#include "interps.h"
#include "top.h"
#include "event-top.h"
#include "event-loop.h"
#include "ui-out.h"
#include "cli-out.h"
#include "tui/tui-data.h"
#include "readline/readline.h"
#include "tui/tui-win.h"
#include "tui/tui.h"
#include "tui/tui-io.h"
#include "exceptions.h"
Functions
static void tui_exit (void)
static void * tui_init (struct interp *self, int top_level)
int tui_allowed_p (void)
static int tui_resume (void *data)
static int tui_suspend (void *data)
static int tui_display_prompt_p (void *data)
static struct ui_out * tui_ui_out (struct interp *self)
static struct gdb_exception tui_exec (void *data, const char *command_str)
void _initialize_tui_interp (void)
Variables
static int tui_start_enabled = 0
static int tui_is_toplevel = 0
initialize_file_ftype _initialize_tui_interp
Function Documentation
void _initialize_tui_interp (void)
Definition at line 147 of file tui-interp.c.
References _initialize_tui_interp, cli_command_loop(), interp_add(), INTERP_CONSOLE, interp_new(), INTERP_TUI, interpreter_p, tui_display_prompt_p(), tui_exec(), tui_init(), tui_resume(), tui_start_enabled, tui_suspend(), tui_ui_out(), and xfree().
int tui_allowed_p (void)
Definition at line 75 of file tui-interp.c.
References gdb_stdout, tui_is_toplevel, and ui_file_isatty().
Referenced by tui_enable().
static int tui_display_prompt_p (void * data) [static]
Definition at line 120 of file tui-interp.c.
References interp_quiet_p().
Referenced by _initialize_tui_interp().
static struct gdb_exception tui_exec (void * data, const char * command_str) [static, read]
Definition at line 138 of file tui-interp.c.
References _, and internal_error().
Referenced by _initialize_tui_interp().
static void tui_exit (void) [static]
Definition at line 41 of file tui-interp.c.
References tui_disable().
Referenced by tui_init().
static void* tui_init (struct interp * self, int top_level) [static]
Definition at line 54 of file tui-interp.c.
References gdb_stdout, tui_exit(), tui_initialize_io(), tui_initialize_readline(), tui_initialize_static_data(), tui_initialize_win(), tui_is_toplevel, and ui_file_isatty().
Referenced by _initialize_tui_interp().
static int tui_resume (void * data) [static]
Definition at line 84 of file tui-interp.c.
References cli_out_set_stream(), gdb_setup_readline(), gdb_stdout, tui_enable(), tui_old_uiout, and tui_start_enabled.
Referenced by _initialize_tui_interp().
static int tui_suspend (void * data) [static]
Definition at line 110 of file tui-interp.c.
References tui_active, tui_disable(), and tui_start_enabled.
Referenced by _initialize_tui_interp().
static struct ui_out* tui_ui_out (struct interp * self) [static, read]
Definition at line 129 of file tui-interp.c.
References tui_active, tui_old_uiout, and tui_out.
Referenced by _initialize_tui_interp().
Variable Documentation
initialize_file_ftype _initialize_tui_interp
Referenced by _initialize_tui_interp(), and initialize_all_files().
int tui_is_toplevel = 0 [static]
Definition at line 49 of file tui-interp.c.
Referenced by tui_allowed_p(), and tui_init().
int tui_start_enabled = 0 [static]
Definition at line 36 of file tui-interp.c.
Referenced by _initialize_tui_interp(), tui_resume(), and tui_suspend().