GDB (xrefs): /home/stan/gdb/src/gdb/tui/tui-file.c File Reference
/home/stan/gdb/src/gdb/tui/tui-file.c File Reference
#include "defs.h"
#include "ui-file.h"
#include "tui/tui-file.h"
#include "tui/tui-io.h"
#include "tui.h"
#include "gdb_string.h"
Classes
struct tui_stream
Enumerations
enum streamtype { afile, astring }
Functions
static struct ui_file * tui_file_new (void)
static void tui_file_delete (struct ui_file *file)
struct ui_file * tui_fileopen (FILE *stream)
struct ui_file * tui_sfileopen (int n)
static int tui_file_isatty (struct ui_file *file)
static void tui_file_rewind (struct ui_file *file)
static void tui_file_put (struct ui_file *file, ui_file_put_method_ftype *write, void *dest)
void tui_file_fputs (const char *linebuffer, struct ui_file *file)
char * tui_file_get_strbuf (struct ui_file *file)
void tui_file_adjust_strbuf (int n, struct ui_file *file)
static void tui_file_flush (struct ui_file *file)
Variables
static ui_file_flush_ftype tui_file_flush
ui_file_fputs_ftype tui_file_fputs
static ui_file_isatty_ftype tui_file_isatty
static ui_file_rewind_ftype tui_file_rewind
static ui_file_put_ftype tui_file_put
static ui_file_delete_ftype tui_file_delete
static int tui_file_magic
Enumeration Type Documentation
enum streamtype
Enumerator:
afile
astring
Definition at line 32 of file tui-file.c.
Function Documentation
void tui_file_adjust_strbuf (int n, struct ui_file * file)
Definition at line 202 of file tui-file.c.
References _, astring, internal_error(), tui_stream::ts_buflen, tui_stream::ts_magic, tui_stream::ts_strbuf, tui_stream::ts_streamtype, tui_file_magic, ui_file_data(), xmalloc(), and xrealloc().
Referenced by tui_file_fputs().
static void tui_file_delete (struct ui_file * file) [static]
Definition at line 74 of file tui-file.c.
References _, astring, internal_error(), tui_stream::ts_magic, tui_stream::ts_strbuf, tui_stream::ts_streamtype, tui_file_magic, ui_file_data(), and xfree().
static void tui_file_flush (struct ui_file * file) [static]
Definition at line 231 of file tui-file.c.
References _, afile, astring, internal_error(), tui_stream::ts_filestream, tui_stream::ts_magic, tui_stream::ts_streamtype, tui_file_magic, and ui_file_data().
void tui_file_fputs (const char * linebuffer, struct ui_file * file)
Definition at line 172 of file tui-file.c.
References astring, tui_stream::ts_strbuf, tui_stream::ts_streamtype, tui_file_adjust_strbuf(), tui_file_fputs, tui_puts(), and ui_file_data().
char* tui_file_get_strbuf (struct ui_file * file)
Definition at line 188 of file tui-file.c.
References _, internal_error(), tui_stream::ts_magic, tui_stream::ts_strbuf, tui_file_magic, and ui_file_data().
Referenced by tui_disassemble(), tui_get_function_from_frame(), tui_make_status_line(), and tui_register_format().
static int tui_file_isatty (struct ui_file * file) [static]
Definition at line 124 of file tui-file.c.
References _, afile, internal_error(), tui_stream::ts_filestream, tui_stream::ts_magic, tui_stream::ts_streamtype, tui_file_magic, and ui_file_data().
static struct ui_file * tui_file_new (void) [static, read]
Definition at line 58 of file tui-file.c.
References set_ui_file_data(), set_ui_file_flush(), set_ui_file_fputs(), set_ui_file_isatty(), set_ui_file_put(), set_ui_file_rewind(), tui_stream::ts_magic, tui_file_delete, tui_file_flush, tui_file_fputs, tui_file_isatty, tui_file_magic, tui_file_put, tui_file_rewind, ui_file_new(), and XMALLOC.
Referenced by tui_fileopen(), and tui_sfileopen().
static void tui_file_put (struct ui_file * file, ui_file_put_method_ftype * write, void * dest) [static]
Definition at line 149 of file tui-file.c.
References _, astring, internal_error(), tui_stream::ts_magic, tui_stream::ts_strbuf, tui_stream::ts_streamtype, tui_file_magic, and ui_file_data().
static void tui_file_rewind (struct ui_file * file) [static]
Definition at line 138 of file tui-file.c.
References _, internal_error(), tui_stream::ts_magic, tui_stream::ts_strbuf, tui_file_magic, and ui_file_data().
struct ui_file* tui_fileopen (FILE * stream) [read]
Definition at line 90 of file tui-file.c.
References afile, tui_stream::ts_buflen, tui_stream::ts_filestream, tui_stream::ts_strbuf, tui_stream::ts_streamtype, tui_file_new(), and ui_file_data().
Referenced by tui_initialize_io().
struct ui_file* tui_sfileopen (int n) [read]
Definition at line 103 of file tui-file.c.
References astring, tui_stream::ts_buflen, tui_stream::ts_filestream, tui_stream::ts_strbuf, tui_stream::ts_streamtype, tui_file_new(), ui_file_data(), and xmalloc().
Referenced by tui_disassemble(), tui_get_function_from_frame(), tui_make_status_line(), and tui_register_format().
Variable Documentation
ui_file_delete_ftype tui_file_delete [static]
Definition at line 53 of file tui-file.c.
Referenced by tui_file_new().
ui_file_flush_ftype tui_file_flush [static]
Definition at line 48 of file tui-file.c.
Referenced by tui_file_new().
ui_file_fputs_ftype tui_file_fputs
Referenced by tui_file_fputs(), and tui_file_new().
ui_file_isatty_ftype tui_file_isatty [static]
Definition at line 50 of file tui-file.c.
Referenced by tui_file_new().
int tui_file_magic [static]
Definition at line 55 of file tui-file.c.
Referenced by tui_file_adjust_strbuf(), tui_file_delete(), tui_file_flush(), tui_file_get_strbuf(), tui_file_isatty(), tui_file_new(), tui_file_put(), and tui_file_rewind().
ui_file_put_ftype tui_file_put [static]
Definition at line 52 of file tui-file.c.
Referenced by tui_file_new().
ui_file_rewind_ftype tui_file_rewind [static]
Definition at line 51 of file tui-file.c.
Referenced by tui_file_new().