GDB (xrefs): /home/stan/gdb/src/gdb/tui/tui-layout.c File Reference
/home/stan/gdb/src/gdb/tui/tui-layout.c File Reference
#include "defs.h"
#include "arch-utils.h"
#include "command.h"
#include "symtab.h"
#include "frame.h"
#include "source.h"
#include <ctype.h>
#include "tui/tui.h"
#include "tui/tui-data.h"
#include "tui/tui-windata.h"
#include "tui/tui-wingeneral.h"
#include "tui/tui-stack.h"
#include "tui/tui-regs.h"
#include "tui/tui-win.h"
#include "tui/tui-winsource.h"
#include "tui/tui-disasm.h"
#include "tui/tui-layout.h"
#include "gdb_string.h"
#include "gdb_curses.h"
Defines
#define LAYOUT_USAGE "Usage: layout prev | next | <layout_name> \n"
Functions
static void show_layout (enum tui_layout_type)
static void init_gen_win_info (struct tui_gen_win_info *, enum tui_win_type, int, int, int, int)
static void * init_and_make_win (void *, enum tui_win_type, int, int, int, int, int)
static void show_source_or_disasm_and_command (enum tui_layout_type)
static void make_source_or_disasm_window (struct tui_win_info **, enum tui_win_type, int, int)
static void make_command_window (struct tui_win_info **, int, int)
static void make_source_window (struct tui_win_info **, int, int)
static void make_disasm_window (struct tui_win_info **, int, int)
static void make_data_window (struct tui_win_info **, int, int)
static void show_source_command (void)
static void show_disasm_command (void)
static void show_source_disasm_command (void)
static void show_data (enum tui_layout_type)
static enum tui_layout_type next_layout (void)
static enum tui_layout_type prev_layout (void)
static void tui_layout_command (char *, int)
static void tui_toggle_layout_command (char *, int)
static void tui_toggle_split_layout_command (char *, int)
static void extract_display_start_addr (struct gdbarch **, CORE_ADDR *)
static void tui_handle_xdb_layout (struct tui_layout_def *)
enum tui_status tui_set_layout (enum tui_layout_type layout_type, enum tui_register_display_type regs_display_type)
void tui_add_win_to_layout (enum tui_win_type type)
int tui_default_win_height (enum tui_win_type type, enum tui_layout_type layout)
int tui_default_win_viewport_height (enum tui_win_type type, enum tui_layout_type layout)
void _initialize_tui_layout (void)
enum tui_status tui_set_layout_for_display_command (const char *layout_name)
Variables
initialize_file_ftype _initialize_tui_layout
Define Documentation
#define LAYOUT_USAGE "Usage: layout prev | next | <layout_name> \n"
Definition at line 78 of file tui-layout.c.
Referenced by tui_layout_command().
Function Documentation
void _initialize_tui_layout (void)
Definition at line 386 of file tui-layout.c.
References _, _initialize_tui_layout, add_com(), class_tui, tui_layout_command(), tui_toggle_layout_command(), tui_toggle_split_layout_command(), and xdb_commands.
static void extract_display_start_addr (struct gdbarch ** gdbarch_p, CORE_ADDR * addr_p) [static]
Definition at line 524 of file tui-layout.c.
References DISASSEM_COMMAND, DISASSEM_DATA_COMMAND, find_line_pc(), get_current_arch(), get_current_source_symtab_and_line(), symtab_and_line::pc, SRC_COMMAND, SRC_DATA_COMMAND, SRC_DISASSEM_COMMAND, symtab_and_line::symtab, tui_current_layout(), TUI_DISASM_WIN, and TUI_SRC_WIN.
Referenced by tui_set_layout().
static void * init_and_make_win (void * opaque_win_info, enum tui_win_type win_type, int height, int width, int origin_x, int origin_y, int box_it) [static]
Definition at line 934 of file tui-layout.c.
References CMD_WIN, tui_win_info::generic, init_gen_win_info(), tui_alloc_generic_win_info(), tui_alloc_win_info(), tui_make_window(), and tui_win_is_auxillary().
Referenced by make_command_window(), make_data_window(), make_source_or_disasm_window(), show_data(), show_source_disasm_command(), and show_source_or_disasm_and_command().
static void init_gen_win_info (struct tui_gen_win_info * win_info, enum tui_win_type type, int height, int width, int origin_x, int origin_y) [static]
Definition at line 907 of file tui-layout.c.
References CMD_WIN, tui_gen_win_info::height, tui_gen_win_info::origin, tui_gen_win_info::type, type, tui_gen_win_info::viewport_height, tui_gen_win_info::width, tui_point::x, and tui_point::y.
Referenced by init_and_make_win(), show_data(), show_source_disasm_command(), and show_source_or_disasm_and_command().
static void make_command_window (struct tui_win_info ** win_info_ptr, int height, int origin_y) [static]
Definition at line 659 of file tui-layout.c.
References CMD_WIN, DONT_BOX_WINDOW, init_and_make_win(), and tui_term_width().
Referenced by show_source_disasm_command(), and show_source_or_disasm_and_command().
static void make_data_window (struct tui_win_info ** win_info_ptr, int height, int origin_y) [static]
Definition at line 699 of file tui-layout.c.
References BOX_WINDOW, DATA_WIN, init_and_make_win(), and tui_term_width().
Referenced by show_data().
static void make_disasm_window (struct tui_win_info ** win_info_ptr, int height, int origin_y) [static]
Definition at line 689 of file tui-layout.c.
References DISASSEM_WIN, and make_source_or_disasm_window().
Referenced by show_data(), show_source_disasm_command(), and show_source_or_disasm_and_command().
static void make_source_or_disasm_window (struct tui_win_info ** win_info_ptr, enum tui_win_type type, int height, int origin_y) [static]
Definition at line 971 of file tui-layout.c.
References BOX_WINDOW, DONT_BOX_WINDOW, EXEC_INFO_WIN, init_and_make_win(), SRC_WIN, tui_disassem_exec_info_win_ptr(), tui_source_exec_info_win_ptr(), tui_term_width(), and tui_gen_win_info::width.
Referenced by make_disasm_window(), and make_source_window().
static void make_source_window (struct tui_win_info ** win_info_ptr, int height, int origin_y) [static]
Definition at line 677 of file tui-layout.c.
References make_source_or_disasm_window(), and SRC_WIN.
Referenced by show_data(), show_source_disasm_command(), and show_source_or_disasm_and_command().
static enum tui_layout_type next_layout (void) [static]
Definition at line 619 of file tui-layout.c.
References SRC_COMMAND, tui_current_layout(), and UNDEFINED_LAYOUT.
Referenced by tui_set_layout_for_display_command().
static enum tui_layout_type prev_layout (void) [static]
Definition at line 639 of file tui-layout.c.
References DISASSEM_DATA_COMMAND, SRC_COMMAND, tui_current_layout(), and UNDEFINED_LAYOUT.
Referenced by tui_set_layout_for_display_command().
static void show_data (enum tui_layout_type new_layout) [static]
Definition at line 842 of file tui-layout.c.
References tui_win_info::detail, DISASSEM_WIN, DONT_BOX_WINDOW, EXEC_INFO_WIN, tui_source_info::execution_info, tui_source_info::has_locator, init_and_make_win(), init_gen_win_info(), LOCATOR_WIN, make_data_window(), make_disasm_window(), make_source_window(), tui_win_info::source_info, SRC_DATA_COMMAND, SRC_WIN, tui_add_to_source_windows(), TUI_CMD_WIN, TUI_DATA_WIN, tui_locator_win_info_ptr(), tui_make_all_invisible(), tui_make_invisible(), tui_make_visible(), tui_set_current_layout_to(), tui_show_locator_content(), tui_term_height(), tui_term_width(), tui_win_list, and tui_gen_win_info::width.
Referenced by show_layout().
static void show_disasm_command (void) [static]
Definition at line 723 of file tui-layout.c.
References DISASSEM_COMMAND, and show_source_or_disasm_and_command().
Referenced by show_layout().
static void show_layout (enum tui_layout_type layout) [static]
Definition at line 82 of file tui-layout.c.
References DISASSEM_COMMAND, DISASSEM_DATA_COMMAND, show_data(), show_disasm_command(), show_source_command(), show_source_disasm_command(), SRC_COMMAND, SRC_DATA_COMMAND, SRC_DISASSEM_COMMAND, tui_add_to_source_windows(), tui_clear_source_windows(), tui_current_layout(), TUI_DISASM_WIN, tui_free_all_source_wins_content(), tui_locator_win_info_ptr(), tui_make_all_invisible(), tui_make_invisible(), tui_refresh_all(), TUI_SRC_WIN, and tui_win_list.
Referenced by tui_add_win_to_layout(), and tui_set_layout().
static void show_source_command (void) [static]
Definition at line 715 of file tui-layout.c.
References show_source_or_disasm_and_command(), and SRC_COMMAND.
Referenced by show_layout().
static void show_source_disasm_command (void) [static]
Definition at line 731 of file tui-layout.c.
References DONT_BOX_WINDOW, EXEC_INFO_WIN, init_and_make_win(), init_gen_win_info(), LOCATOR_WIN, make_command_window(), make_disasm_window(), make_source_window(), SRC_DISASSEM_COMMAND, TUI_CMD_WIN, tui_current_layout(), TUI_DISASM_WIN, tui_locator_win_info_ptr(), tui_make_visible(), tui_refresh_win(), tui_set_current_layout_to(), tui_show_locator_content(), tui_show_source_content(), TUI_SRC_WIN, tui_term_height(), and tui_term_width().
Referenced by show_layout().
static void show_source_or_disasm_and_command (enum tui_layout_type layout_type) [static]
Definition at line 1005 of file tui-layout.c.
References DONT_BOX_WINDOW, EXEC_INFO_WIN, init_and_make_win(), init_gen_win_info(), LOCATOR_WIN, make_command_window(), make_disasm_window(), make_source_window(), SRC_COMMAND, TUI_CMD_WIN, tui_current_layout(), TUI_DISASM_WIN, tui_locator_win_info_ptr(), tui_make_visible(), tui_refresh_win(), tui_set_current_layout_to(), tui_show_locator_content(), tui_show_source_content(), TUI_SRC_WIN, tui_term_height(), and tui_term_width().
Referenced by show_disasm_command(), and show_source_command().
void tui_add_win_to_layout (enum tui_win_type type)
Definition at line 273 of file tui-layout.c.
References DATA_WIN, DISASSEM_COMMAND, DISASSEM_DATA_COMMAND, DISASSEM_WIN, show_layout(), SRC_COMMAND, SRC_DATA_COMMAND, SRC_DISASSEM_COMMAND, SRC_WIN, tui_clear_source_windows_detail(), and tui_current_layout().
Referenced by tui_show_assembly(), tui_show_disassem(), and tui_show_source().
int tui_default_win_height (enum tui_win_type type, enum tui_layout_type layout)
Definition at line 323 of file tui-layout.c.
References DISASSEM_COMMAND, DISASSEM_DATA_COMMAND, tui_win_info::generic, tui_gen_win_info::height, SRC_COMMAND, SRC_DATA_COMMAND, SRC_DISASSEM_COMMAND, TUI_CMD_WIN, tui_term_height(), tui_win_list, and type.
Referenced by tui_default_win_viewport_height().
int tui_default_win_viewport_height (enum tui_win_type type, enum tui_layout_type layout)
Definition at line 363 of file tui-layout.c.
References TUI_CMD_WIN, tui_default_win_height(), and tui_win_list.
Referenced by tui_get_low_disassembly_address().
static void tui_handle_xdb_layout (struct tui_layout_def * layout_def) [static]
Definition at line 559 of file tui-layout.c.
References DISASSEM_DATA_COMMAND, tui_layout_def::display_mode, tui_layout_def::regs_display_type, tui_layout_def::split, SRC_COMMAND, SRC_DISASSEM_COMMAND, SRC_WIN, tui_set_layout(), tui_set_win_focus_to(), TUI_UNDEFINED_REGS, and tui_win_list.
Referenced by tui_toggle_layout_command(), and tui_toggle_split_layout_command().
static void tui_layout_command (char * arg, int from_tty) [static]
Definition at line 606 of file tui-layout.c.
References _, LAYOUT_USAGE, tui_enable(), tui_set_layout_for_display_command(), TUI_SUCCESS, and warning().
Referenced by _initialize_tui_layout().
enum tui_status tui_set_layout (enum tui_layout_type layout_type, enum tui_register_display_type regs_display_type)
Definition at line 135 of file tui-layout.c.
References DISASSEM_COMMAND, DISASSEM_DATA_COMMAND, DISASSEM_WIN, tui_layout_def::display_mode, extract_display_start_addr(), layout_def, show_layout(), tui_layout_def::split, SRC_COMMAND, SRC_DATA_COMMAND, SRC_DISASSEM_COMMAND, SRC_WIN, exsummary::status, TUI_CMD_WIN, tui_current_layout(), TUI_DATA_WIN, TUI_DISASM_WIN, tui_display_all_data(), TUI_FAILURE, tui_get_begin_asm_address(), tui_layout_def(), tui_set_win_focus_to(), tui_show_registers(), TUI_SRC_WIN, TUI_SUCCESS, TUI_UNDEFINED_REGS, tui_update_source_windows_with_addr(), tui_win_with_focus(), UNDEFINED_LAYOUT, and win_with_focus.
Referenced by tui_enable(), tui_handle_xdb_layout(), tui_rl_change_windows(), tui_rl_delete_other_windows(), and tui_set_layout_for_display_command().
enum tui_status tui_set_layout_for_display_command (const char * layout_name)
Definition at line 420 of file tui-layout.c.
References _, DISASSEM_COMMAND, DISASSEM_DATA_COMMAND, next_layout(), prev_layout(), SRC_COMMAND, SRC_DATA_COMMAND, SRC_DISASSEM_COMMAND, exsummary::status, subset_compare(), tui_current_layout(), TUI_DATA_WIN, TUI_DFLOAT_REGS, TUI_FAILURE, TUI_FLOAT_REGS_NAME, TUI_GENERAL_AND_SPECIAL_REGS, TUI_GENERAL_REGS, TUI_GENERAL_REGS_NAME, TUI_GENERAL_SPECIAL_REGS_NAME, tui_set_layout(), TUI_SFLOAT_REGS, TUI_SPECIAL_REGS, TUI_SPECIAL_REGS_NAME, TUI_SUCCESS, TUI_UNDEFINED_REGS, UNDEFINED_LAYOUT, warning(), and xfree().
Referenced by display_command(), tui_layout_command(), and tui_show_registers().
static void tui_toggle_layout_command (char * arg, int from_tty) [static]
Definition at line 577 of file tui-layout.c.
References DISASSEM_WIN, tui_layout_def::display_mode, layout_def, tui_layout_def::split, SRC_WIN, tui_enable(), tui_handle_xdb_layout(), and tui_layout_def().
Referenced by _initialize_tui_layout().
static void tui_toggle_split_layout_command (char * arg, int from_tty) [static]
Definition at line 594 of file tui-layout.c.
References layout_def, tui_layout_def::split, tui_enable(), tui_handle_xdb_layout(), and tui_layout_def().
Referenced by _initialize_tui_layout().
Variable Documentation
initialize_file_ftype _initialize_tui_layout
Referenced by _initialize_tui_layout(), and initialize_all_files().