GDB (xrefs): /home/stan/gdb/src/gdb/tui/tui-source.h File Reference
/home/stan/gdb/src/gdb/tui/tui-source.h File Reference
#include "tui/tui-data.h"
Functions
void tui_set_source_content_nil (struct tui_win_info *, char *)
enum tui_status tui_set_source_content (struct symtab *, int, int)
void tui_show_symtab_source (struct gdbarch *, struct symtab *, struct tui_line_or_address, int)
int tui_source_is_displayed (const char *)
void tui_vertical_source_scroll (enum tui_scroll_direction, int)
Function Documentation
enum tui_status tui_set_source_content (struct symtab * , int , int)
Definition at line 43 of file tui-source.c.
References tui_gen_win_info::content, find_source_lines(), tui_source_info::fullname, tui_source_info::gdbarch, get_objfile_arch(), tui_source_info::horizontal_offset, tui_source_element::is_exec_point, symtab::line_charpos, tui_line_or_address::line_no, tui_source_element::line_or_addr, tui_line_or_address::loa, name, symtab::nlines, symtab::objfile, offset, open_source_file(), perror_with_name(), print_sys_errmsg(), printf_unfiltered(), tui_which_element::source, tui_source_info::start_line_or_addr, symtab_to_filename_for_display(), symtab_to_fullname(), tui_alloc_source_buffer(), tui_default_tab_len(), TUI_FAILURE, tui_locator_win_info_ptr(), TUI_SRC_WIN, TUI_SUCCESS, tui_line_or_address::u, tui_win_element::which_element, xfree(), and xmalloc().
Referenced by tui_update_source_window_as_is().
void tui_set_source_content_nil (struct tui_win_info * , char *)
Definition at line 255 of file tui-source.c.
References tui_gen_win_info::content, tui_win_info::generic, tui_source_element::has_break, tui_gen_win_info::height, tui_source_element::is_exec_point, tui_source_element::line, tui_line_or_address::line_no, tui_source_element::line_or_addr, tui_line_or_address::loa, tui_which_element::source, tui_line_or_address::u, tui_win_element::which_element, and tui_gen_win_info::width.
Referenced by tui_erase_source_content().
void tui_show_symtab_source (struct gdbarch * , struct symtab * , struct tui_line_or_address , int)
Definition at line 326 of file tui-source.c.
References TUI_SRC_WIN, and tui_update_source_window_as_is().
Referenced by tui_update_source_windows_with_addr(), and tui_update_source_windows_with_line().
int tui_source_is_displayed (const char *)
Definition at line 338 of file tui-source.c.
References tui_locator_element::full_name, tui_which_element::locator, tui_locator_win_info_ptr(), TUI_SRC_WIN, and tui_win_element::which_element.
Referenced by tui_show_frame_info().
void tui_vertical_source_scroll (enum tui_scroll_direction, int)
Definition at line 351 of file tui-source.c.
References find_pc_symtab(), FORWARD_SCROLL, get_current_source_symtab_and_line(), get_frame_pc(), get_selected_frame(), tui_line_or_address::line_no, tui_source_element::line_or_addr, tui_line_or_address::loa, symtab::nlines, print_source_lines(), tui_which_element::source, TUI_SRC_WIN, tui_line_or_address::u, and tui_win_element::which_element.
Referenced by tui_scroll_backward(), and tui_scroll_forward().