GDB (xrefs): /home/stan/gdb/src/gdb/tui/tui-io.h File Reference
/home/stan/gdb/src/gdb/tui/tui-io.h File Reference
Functions
void tui_puts (const char *)
void tui_setup_io (int mode)
void tui_initialize_io (void)
int tui_getc (FILE *)
void tui_redisplay_readline (void)
int key_is_start_sequence (int ch)
int key_is_end_sequence (int ch)
int key_is_backspace (int ch)
int key_is_command_char (int ch)
Variables
struct ui_out * tui_out
struct ui_out * tui_old_uiout
Function Documentation
int key_is_backspace (int ch)
Definition at line 62 of file tui-io.c.
int key_is_command_char (int ch)
Definition at line 68 of file tui-io.c.
References key_is_start_sequence().
Referenced by tui_getc().
int key_is_end_sequence (int ch)
Definition at line 56 of file tui-io.c.
Referenced by tui_dispatch_ctrl_char().
int key_is_start_sequence (int ch)
Definition at line 50 of file tui-io.c.
Referenced by key_is_command_char(), and tui_dispatch_ctrl_char().
int tui_getc (FILE *)
Definition at line 648 of file tui-io.c.
References key_is_command_char(), TUI_CMD_WIN, tui_dispatch_ctrl_char(), and tui_handle_resize_during_io().
Referenced by ATTRIBUTE_PRINTF(), and tui_setup_io().
void tui_initialize_io (void)
Definition at line 601 of file tui-io.c.
References add_file_handler(), cli_out_new(), fprintf_unfiltered(), gdb_pipe_cloexec(), gdb_stderr, gdb_stdout, tui_fileopen(), tui_out_new(), and tui_rl_outstream.
Referenced by tui_init().
void tui_puts (const char *)
Definition at line 164 of file tui-io.c.
References TUI_CMD_WIN.
Referenced by tui_file_fputs(), tui_putc(), and tui_rl_display_match_list().
void tui_redisplay_readline (void)
Definition at line 201 of file tui-io.c.
References CTRL_CHAR, immediate_quit, line, TUI_CMD_WIN, tui_current_key_mode, TUI_ONE_COMMAND_MODE, tui_rl_saved_prompt, tui_set_key_mode(), and TUI_SINGLE_KEY_MODE.
Referenced by tui_rl_startup_hook(), and tui_setup_io().
void tui_setup_io (int mode)
Definition at line 511 of file tui-io.c.
References current_uiout, gdb_stderr, gdb_stdlog, gdb_stdout, gdb_stdtarg, gdb_stdtargerr, tui_deprep_terminal(), tui_getc(), tui_old_rl_deprep_terminal, tui_old_rl_echoing_p, tui_old_rl_getc_function, tui_old_rl_outstream, tui_old_rl_prep_terminal, tui_old_rl_redisplay_function, tui_old_stderr, tui_old_stdout, tui_old_uiout, tui_out, tui_prep_terminal(), tui_redisplay_readline(), tui_rl_display_match_list(), tui_rl_outstream, tui_stderr, and tui_stdout.
Referenced by tui_disable(), and tui_enable().
Variable Documentation
struct ui_out* tui_old_uiout
Definition at line 129 of file tui-io.c.
Referenced by tui_resume(), tui_setup_io(), and tui_ui_out().
struct ui_out* tui_out
Definition at line 124 of file tui-io.c.
Referenced by tui_setup_io(), and tui_ui_out().