GDB (xrefs): /home/stan/gdb/src/gdb/tui/tui-win.h File Reference
/home/stan/gdb/src/gdb/tui/tui-win.h File Reference
#include "tui/tui-data.h"
Functions
void tui_scroll_forward (struct tui_win_info *, int)
void tui_scroll_backward (struct tui_win_info *, int)
void tui_scroll_left (struct tui_win_info *, int)
void tui_scroll_right (struct tui_win_info *, int)
void tui_scroll (enum tui_scroll_direction, struct tui_win_info *, int)
void tui_set_win_focus_to (struct tui_win_info *)
void tui_resize_all (void)
void tui_refresh_all_win (void)
int tui_update_variables (void)
void tui_initialize_win (void)
void tui_update_gdb_sizes (void)
struct cmd_list_element ** tui_get_cmd_list (void)
Variables
chtype tui_border_ulcorner
chtype tui_border_urcorner
chtype tui_border_lrcorner
chtype tui_border_llcorner
chtype tui_border_vline
chtype tui_border_hline
int tui_border_attrs
int tui_active_border_attrs
Function Documentation
struct cmd_list_element** tui_get_cmd_list (void) [read]
Definition at line 340 of file tui-win.c.
References _, add_prefix_cmd(), class_tui, cmdlist, tui_command(), and tuilist.
Referenced by _initialize_tui_regs().
void tui_initialize_win (void)
Definition at line 831 of file tui-win.c.
References memset().
Referenced by tui_init().
void tui_refresh_all_win (void)
Definition at line 620 of file tui-win.c.
References DATA_WIN, DISASSEM_WIN, MAX_MAJOR_WINDOWS, SRC_WIN, tui_check_and_display_highlight_if_needed(), tui_erase_exec_info_content(), tui_refresh_all(), tui_refresh_data_win(), tui_show_locator_content(), tui_show_source_content(), tui_update_exec_info(), tui_win_list, and type.
Referenced by tui_dispatch_ctrl_char(), tui_enable(), tui_handle_resize_during_io(), and tui_refresh_all_command().
void tui_resize_all (void)
Definition at line 655 of file tui-win.c.
References CMD_WIN, tui_gen_win_info::content_size, DISASSEM_COMMAND, DISASSEM_DATA_COMMAND, EMPTY_SOURCE_PROMPT, tui_win_info::generic, tui_gen_win_info::height, tui_gen_win_info::is_visible, make_invisible_and_set_new_height(), make_visible_with_new_height(), MAX_MAJOR_WINDOWS, MIN_CMD_WIN_HEIGHT, MIN_WIN_HEIGHT, tui_gen_win_info::origin, SRC_COMMAND, SRC_DATA_COMMAND, SRC_DISASSEM_COMMAND, SRC_WIN, TUI_CMD_WIN, tui_current_layout(), TUI_DATA_WIN, TUI_DISASM_WIN, tui_erase_source_content(), tui_free_window(), tui_locator_win_info_ptr(), tui_set_term_height_to(), tui_set_term_width_to(), tui_source_windows(), TUI_SRC_WIN, tui_term_height(), tui_term_width(), tui_update_gdb_sizes(), tui_win_list, tui_win_with_focus(), tui_gen_win_info::width, win_with_focus, and tui_point::y.
Referenced by tui_handle_resize_during_io().
void tui_scroll (enum tui_scroll_direction, struct tui_win_info * , int)
Definition at line 595 of file tui-win.c.
References BACKWARD_SCROLL, FORWARD_SCROLL, LEFT_SCROLL, RIGHT_SCROLL, tui_scroll_backward(), tui_scroll_forward(), tui_scroll_left(), and tui_scroll_right().
Referenced by tui_scroll_backward_command(), tui_scroll_forward_command(), tui_scroll_left_command(), tui_scroll_regs_backward_command(), tui_scroll_regs_forward_command(), and tui_scroll_right_command().
void tui_scroll_backward (struct tui_win_info * , int)
Definition at line 522 of file tui-win.c.
References BACKWARD_SCROLL, tui_win_info::generic, tui_gen_win_info::height, TUI_CMD_WIN, TUI_DATA_WIN, TUI_DISASM_WIN, TUI_SRC_WIN, tui_vertical_data_scroll(), tui_vertical_disassem_scroll(), and tui_vertical_source_scroll().
Referenced by tui_dispatch_ctrl_char(), and tui_scroll().
void tui_scroll_forward (struct tui_win_info * , int)
Definition at line 497 of file tui-win.c.
References FORWARD_SCROLL, tui_win_info::generic, tui_gen_win_info::height, TUI_CMD_WIN, TUI_DATA_WIN, TUI_DISASM_WIN, TUI_SRC_WIN, tui_vertical_data_scroll(), tui_vertical_disassem_scroll(), and tui_vertical_source_scroll().
Referenced by tui_dispatch_ctrl_char(), and tui_scroll().
void tui_scroll_left (struct tui_win_info * , int)
Definition at line 548 of file tui-win.c.
References LEFT_SCROLL, TUI_CMD_WIN, TUI_DISASM_WIN, tui_horizontal_source_scroll(), and TUI_SRC_WIN.
Referenced by tui_dispatch_ctrl_char(), and tui_scroll().
void tui_scroll_right (struct tui_win_info * , int)
Definition at line 571 of file tui-win.c.
References RIGHT_SCROLL, TUI_CMD_WIN, TUI_DISASM_WIN, tui_horizontal_source_scroll(), and TUI_SRC_WIN.
Referenced by tui_dispatch_ctrl_char(), and tui_scroll().
void tui_set_win_focus_to (struct tui_win_info *)
Definition at line 480 of file tui-win.c.
References CMD_WIN, tui_win_info::generic, tui_highlight_win(), tui_set_win_with_focus(), tui_unhighlight_win(), tui_win_with_focus(), tui_gen_win_info::type, and win_with_focus.
Referenced by tui_enable(), tui_handle_xdb_layout(), tui_rl_other_window(), tui_set_focus(), tui_set_layout(), tui_show_disassem(), and tui_update_source_window_as_is().
void tui_update_gdb_sizes (void)
Definition at line 464 of file tui-win.c.
References execute_command(), tui_active, TUI_CMD_WIN, tui_term_height(), tui_term_width(), and xsnprintf().
Referenced by tui_disable(), tui_enable(), tui_resize_all(), and tui_set_win_height().
int tui_update_variables (void)
Definition at line 274 of file tui-win.c.
References ACS_HLINE, ACS_LLCORNER, ACS_LRCORNER, ACS_ULCORNER, ACS_URCORNER, ACS_VLINE, translate(), tui_active_border_attrs, tui_active_border_mode, tui_border_attrs, tui_border_hline, tui_border_kind, tui_border_llcorner, tui_border_lrcorner, tui_border_mode, tui_border_ulcorner, tui_border_urcorner, tui_border_vline, and tui_translate::value.
Referenced by tui_enable().
Variable Documentation
int tui_active_border_attrs
Definition at line 251 of file tui-win.c.
Referenced by box_win(), and tui_update_variables().
int tui_border_attrs
Definition at line 250 of file tui-win.c.
Referenced by box_win(), and tui_update_variables().
chtype tui_border_hline
Definition at line 244 of file tui-win.c.
Referenced by box_win(), and tui_update_variables().
chtype tui_border_llcorner
Definition at line 247 of file tui-win.c.
Referenced by box_win(), and tui_update_variables().
chtype tui_border_lrcorner
Definition at line 248 of file tui-win.c.
Referenced by box_win(), and tui_update_variables().
chtype tui_border_ulcorner
Definition at line 245 of file tui-win.c.
Referenced by box_win(), and tui_update_variables().
chtype tui_border_urcorner
Definition at line 246 of file tui-win.c.
Referenced by box_win(), and tui_update_variables().
chtype tui_border_vline
Definition at line 243 of file tui-win.c.
Referenced by box_win(), and tui_update_variables().