GDB (xrefs): /home/stan/gdb/src/gdb/tui/tui-data.h File Reference
/home/stan/gdb/src/gdb/tui/tui-data.h File Reference
#include "tui/tui.h"
#include "gdb_curses.h"
Classes
struct tui_point
struct tui_gen_win_info
struct tui_list
struct tui_line_or_address
struct tui_layout_def
struct tui_source_element
struct tui_data_element
struct tui_command_element
struct tui_locator_element
union tui_which_element
struct tui_win_element
struct tui_data_info
struct tui_source_info
struct tui_command_info
struct tui_win_info
Defines
#define DEFAULT_TAB_LEN 8
#define NO_SRC_STRING "[ No Source Available ]"
#define NO_DISASSEM_STRING "[ No Assembly Available ]"
#define NO_REGS_STRING "[ Register Values Unavailable ]"
#define NO_DATA_STRING "[ No Data Values Displayed ]"
#define MAX_CONTENT_COUNT 100
#define SRC_NAME "SRC"
#define CMD_NAME "CMD"
#define DATA_NAME "REGS"
#define DISASSEM_NAME "ASM"
#define TUI_NULL_STR ""
#define DEFAULT_HISTORY_COUNT 25
#define BOX_WINDOW TRUE
#define DONT_BOX_WINDOW FALSE
#define HILITE TRUE
#define NO_HILITE FALSE
#define WITH_LOCATOR TRUE
#define NO_LOCATOR FALSE
#define EMPTY_SOURCE_PROMPT TRUE
#define NO_EMPTY_SOURCE_PROMPT FALSE
#define UNDEFINED_ITEM -1
#define MIN_WIN_HEIGHT 3
#define MIN_CMD_WIN_HEIGHT 3
#define PROC_PREFIX "In: "
#define LINE_PREFIX "Line: "
#define PC_PREFIX "PC: "
#define SINGLE_KEY "(SingleKey)"
#define MIN_LINE_WIDTH
#define MIN_PROC_WIDTH 12
#define MAX_TARGET_WIDTH 10
#define MAX_PID_WIDTH 14
#define TUI_FLOAT_REGS_NAME "$FREGS"
#define TUI_FLOAT_REGS_NAME_LOWER "$fregs"
#define TUI_GENERAL_REGS_NAME "$GREGS"
#define TUI_GENERAL_REGS_NAME_LOWER "$gregs"
#define TUI_SPECIAL_REGS_NAME "$SREGS"
#define TUI_SPECIAL_REGS_NAME_LOWER "$sregs"
#define TUI_GENERAL_SPECIAL_REGS_NAME "$REGS"
#define TUI_GENERAL_SPECIAL_REGS_NAME_LOWER "$regs"
#define MAX_LOCATOR_ELEMENT_LEN 1024
#define TUI_BP_ENABLED 0x01
#define TUI_BP_DISABLED 0x02
#define TUI_BP_HIT 0x04
#define TUI_BP_CONDITIONAL 0x08
#define TUI_BP_HARDWARE 0x10
#define TUI_BP_HIT_POS 0
#define TUI_BP_BREAK_POS 1
#define TUI_EXEC_POS 2
#define TUI_EXECINFO_SIZE 4
#define TUI_SRC_WIN tui_win_list[SRC_WIN]
#define TUI_DISASM_WIN tui_win_list[DISASSEM_WIN]
#define TUI_DATA_WIN tui_win_list[DATA_WIN]
#define TUI_CMD_WIN tui_win_list[CMD_WIN]
Typedefs
typedef char tui_exec_info_content [TUI_EXECINFO_SIZE]
typedef struct tui_win_element ** tui_win_content
Enumerations
enum tui_scroll_direction { FORWARD_SCROLL, BACKWARD_SCROLL, LEFT_SCROLL, RIGHT_SCROLL }
enum tui_layout_type {
SRC_COMMAND, DISASSEM_COMMAND, SRC_DISASSEM_COMMAND, SRC_DATA_COMMAND,
DISASSEM_DATA_COMMAND, UNDEFINED_LAYOUT
}
enum tui_data_type { TUI_REGISTER, TUI_SCALAR, TUI_COMPLEX, TUI_STRUCT }
enum tui_register_display_type {
TUI_UNDEFINED_REGS, TUI_GENERAL_REGS, TUI_SFLOAT_REGS, TUI_DFLOAT_REGS,
TUI_SPECIAL_REGS, TUI_GENERAL_AND_SPECIAL_REGS
}
Functions
int tui_win_is_source_type (enum tui_win_type win_type)
int tui_win_is_auxillary (enum tui_win_type win_type)
int tui_win_has_locator (struct tui_win_info *win_info)
void tui_set_win_highlight (struct tui_win_info *win_info, int highlight)
void tui_initialize_static_data (void)
struct tui_gen_win_info * tui_alloc_generic_win_info (void)
struct tui_win_info * tui_alloc_win_info (enum tui_win_type)
void tui_init_generic_part (struct tui_gen_win_info *)
void tui_init_win_info (struct tui_win_info *)
tui_win_content tui_alloc_content (int, enum tui_win_type)
int tui_add_content_elements (struct tui_gen_win_info *, int)
void tui_init_content_element (struct tui_win_element *, enum tui_win_type)
void tui_free_window (struct tui_win_info *)
void tui_free_win_content (struct tui_gen_win_info *)
void tui_free_data_content (tui_win_content, int)
void tui_free_all_source_wins_content (void)
void tui_del_window (struct tui_win_info *)
void tui_del_data_windows (tui_win_content, int)
struct tui_win_info * tui_partial_win_by_name (char *)
char * tui_win_name (struct tui_gen_win_info *)
enum tui_layout_type tui_current_layout (void)
void tui_set_current_layout_to (enum tui_layout_type)
int tui_term_height (void)
void tui_set_term_height_to (int)
int tui_term_width (void)
void tui_set_term_width_to (int)
struct tui_gen_win_info * tui_locator_win_info_ptr (void)
struct tui_gen_win_info * tui_source_exec_info_win_ptr (void)
struct tui_gen_win_info * tui_disassem_exec_info_win_ptr (void)
struct tui_list * tui_source_windows (void)
void tui_clear_source_windows (void)
void tui_clear_source_windows_detail (void)
void tui_clear_win_detail (struct tui_win_info *)
void tui_add_to_source_windows (struct tui_win_info *)
int tui_default_tab_len (void)
void tui_set_default_tab_len (int)
struct tui_win_info * tui_win_with_focus (void)
void tui_set_win_with_focus (struct tui_win_info *)
struct tui_layout_def * tui_layout_def (void)
int tui_win_resized (void)
void tui_set_win_resized_to (int)
struct tui_win_info * tui_next_win (struct tui_win_info *)
struct tui_win_info * tui_prev_win (struct tui_win_info *)
Variables
struct tui_win_info * tui_win_list [MAX_MAJOR_WINDOWS]
Define Documentation
#define BOX_WINDOW TRUE
Definition at line 64 of file tui-data.h.
Referenced by make_data_window(), make_source_or_disasm_window(), and tui_make_window().
#define CMD_NAME "CMD"
Definition at line 59 of file tui-data.h.
Referenced by tui_win_name().
#define DATA_NAME "REGS"
Definition at line 60 of file tui-data.h.
Referenced by tui_show_registers(), and tui_win_name().
#define DEFAULT_HISTORY_COUNT 25
Definition at line 63 of file tui-data.h.
#define DEFAULT_TAB_LEN 8
Definition at line 52 of file tui-data.h.
#define DISASSEM_NAME "ASM"
Definition at line 61 of file tui-data.h.
Referenced by tui_win_name().
#define DONT_BOX_WINDOW FALSE
Definition at line 65 of file tui-data.h.
Referenced by make_command_window(), make_source_or_disasm_window(), show_data(), show_source_disasm_command(), show_source_or_disasm_and_command(), and tui_display_registers_from().
#define EMPTY_SOURCE_PROMPT TRUE
Definition at line 70 of file tui-data.h.
Referenced by tui_adjust_win_heights(), tui_erase_source_content(), tui_resize_all(), tui_show_frame_info(), tui_update_source_window_as_is(), and tui_update_source_windows_with_addr().
#define HILITE TRUE
Definition at line 66 of file tui-data.h.
Referenced by box_win(), and tui_highlight_win().
#define LINE_PREFIX "Line: "
Definition at line 78 of file tui-data.h.
Referenced by tui_make_status_line().
#define MAX_CONTENT_COUNT 100
Definition at line 57 of file tui-data.h.
#define MAX_LOCATOR_ELEMENT_LEN 1024
Definition at line 199 of file tui-data.h.
Referenced by tui_set_locator_fullname(), and tui_set_locator_info().
#define MAX_PID_WIDTH 14
Definition at line 87 of file tui-data.h.
Referenced by tui_make_status_line().
#define MAX_TARGET_WIDTH 10
Definition at line 86 of file tui-data.h.
Referenced by tui_make_status_line().
#define MIN_CMD_WIN_HEIGHT 3
Definition at line 74 of file tui-data.h.
Referenced by new_height_ok(), and tui_resize_all().
#define MIN_LINE_WIDTH
Value:
4       /* Use at least 4 digits for line
                                   numbers.  */
Definition at line 84 of file tui-data.h.
Referenced by tui_make_status_line().
#define MIN_PROC_WIDTH 12
Definition at line 85 of file tui-data.h.
Referenced by tui_make_status_line().
#define MIN_WIN_HEIGHT 3
Definition at line 73 of file tui-data.h.
Referenced by new_height_ok(), and tui_resize_all().
#define NO_DATA_STRING "[ No Data Values Displayed ]"
Definition at line 56 of file tui-data.h.
Referenced by tui_display_all_data().
#define NO_DISASSEM_STRING "[ No Assembly Available ]"
Definition at line 54 of file tui-data.h.
Referenced by tui_erase_source_content().
#define NO_EMPTY_SOURCE_PROMPT FALSE
Definition at line 71 of file tui-data.h.
#define NO_HILITE FALSE
Definition at line 67 of file tui-data.h.
Referenced by tui_make_window(), and tui_unhighlight_win().
#define NO_LOCATOR FALSE
Definition at line 69 of file tui-data.h.
#define NO_REGS_STRING "[ Register Values Unavailable ]"
Definition at line 55 of file tui-data.h.
Referenced by tui_show_registers().
#define NO_SRC_STRING "[ No Source Available ]"
Definition at line 53 of file tui-data.h.
Referenced by tui_erase_source_content().
#define PC_PREFIX "PC: "
Definition at line 79 of file tui-data.h.
Referenced by tui_make_status_line().
#define PROC_PREFIX "In: "
Definition at line 77 of file tui-data.h.
Referenced by tui_make_status_line().
#define SINGLE_KEY "(SingleKey)"
Definition at line 80 of file tui-data.h.
Referenced by tui_make_status_line().
#define SRC_NAME "SRC"
Definition at line 58 of file tui-data.h.
Referenced by tui_win_name().
#define TUI_BP_BREAK_POS 1
Definition at line 223 of file tui-data.h.
Referenced by tui_set_exec_info_content().
#define TUI_BP_CONDITIONAL 0x08
Definition at line 218 of file tui-data.h.
Referenced by tui_update_breakpoint_info().
#define TUI_BP_DISABLED 0x02
Definition at line 216 of file tui-data.h.
Referenced by tui_set_exec_info_content(), and tui_update_breakpoint_info().
#define TUI_BP_ENABLED 0x01
Definition at line 215 of file tui-data.h.
Referenced by tui_set_exec_info_content(), and tui_update_breakpoint_info().
#define TUI_BP_HARDWARE 0x10
Definition at line 219 of file tui-data.h.
Referenced by tui_set_exec_info_content(), and tui_update_breakpoint_info().
#define TUI_BP_HIT 0x04
Definition at line 217 of file tui-data.h.
Referenced by tui_set_exec_info_content(), and tui_update_breakpoint_info().
#define TUI_BP_HIT_POS 0
Definition at line 222 of file tui-data.h.
Referenced by tui_set_exec_info_content().
#define TUI_CMD_WIN tui_win_list[CMD_WIN]
Definition at line 319 of file tui-data.h.
Referenced by make_invisible_and_set_new_height(), make_visible_with_new_height(), new_height_ok(), parse_scrolling_args(), show_data(), show_source_disasm_command(), show_source_or_disasm_and_command(), tui_adjust_win_heights(), tui_default_win_height(), tui_default_win_viewport_height(), tui_dispatch_ctrl_char(), tui_enable(), tui_get_command_dimension(), tui_getc(), tui_puts(), tui_redisplay_readline(), tui_resize_all(), tui_rl_display_match_list(), tui_rl_other_window(), tui_scroll_backward(), tui_scroll_forward(), tui_scroll_left(), tui_scroll_right(), tui_set_focus(), tui_set_layout(), and tui_update_gdb_sizes().
#define TUI_DATA_WIN tui_win_list[DATA_WIN]
Definition at line 318 of file tui-data.h.
Referenced by new_height_ok(), show_data(), tui_adjust_win_heights(), tui_check_data_values(), tui_check_register_values(), tui_delete_data_content_windows(), tui_display_all_data(), tui_display_data_from_line(), tui_display_reg_element_at_line(), tui_display_registers_from(), tui_display_registers_from_line(), tui_erase_data_content(), tui_first_data_item_displayed(), tui_first_reg_element_no_inline(), tui_last_regs_line_no(), tui_line_from_reg_element_no(), tui_refresh_data_win(), tui_reg_next_command(), tui_resize_all(), tui_rl_other_window(), tui_scroll_backward(), tui_scroll_forward(), tui_scroll_regs_backward_command(), tui_scroll_regs_forward_command(), tui_set_focus(), tui_set_layout(), tui_set_layout_for_display_command(), tui_show_register_group(), tui_show_registers(), and tui_vertical_data_scroll().
#define TUI_DISASM_WIN tui_win_list[DISASSEM_WIN]
Definition at line 317 of file tui-data.h.
Referenced by extract_display_start_addr(), new_height_ok(), show_layout(), show_source_disasm_command(), show_source_or_disasm_and_command(), tui_adjust_win_heights(), tui_resize_all(), tui_scroll_backward(), tui_scroll_forward(), tui_scroll_left(), tui_scroll_right(), tui_set_disassem_content(), tui_set_layout(), tui_show_disassem(), tui_show_frame_info(), tui_update_breakpoint_info(), tui_update_source_window_as_is(), and tui_vertical_disassem_scroll().
#define TUI_EXEC_POS 2
Definition at line 224 of file tui-data.h.
Referenced by tui_set_exec_info_content().
#define TUI_EXECINFO_SIZE 4
Definition at line 225 of file tui-data.h.
Referenced by tui_set_exec_info_content().
#define TUI_FLOAT_REGS_NAME "$FREGS"
Definition at line 89 of file tui-data.h.
Referenced by tui_set_layout_for_display_command().
#define TUI_FLOAT_REGS_NAME_LOWER "$fregs"
Definition at line 90 of file tui-data.h.
#define TUI_GENERAL_REGS_NAME "$GREGS"
Definition at line 91 of file tui-data.h.
Referenced by tui_set_layout_for_display_command().
#define TUI_GENERAL_REGS_NAME_LOWER "$gregs"
Definition at line 92 of file tui-data.h.
#define TUI_GENERAL_SPECIAL_REGS_NAME "$REGS"
Definition at line 95 of file tui-data.h.
Referenced by tui_set_layout_for_display_command().
#define TUI_GENERAL_SPECIAL_REGS_NAME_LOWER "$regs"
Definition at line 96 of file tui-data.h.
#define TUI_NULL_STR ""
Definition at line 62 of file tui-data.h.
#define TUI_SPECIAL_REGS_NAME "$SREGS"
Definition at line 93 of file tui-data.h.
Referenced by tui_set_layout_for_display_command().
#define TUI_SPECIAL_REGS_NAME_LOWER "$sregs"
Definition at line 94 of file tui-data.h.
#define TUI_SRC_WIN tui_win_list[SRC_WIN]
Definition at line 316 of file tui-data.h.
Referenced by extract_display_start_addr(), new_height_ok(), show_layout(), show_source_disasm_command(), show_source_or_disasm_and_command(), tui_adjust_win_heights(), tui_enable(), tui_resize_all(), tui_scroll_backward(), tui_scroll_forward(), tui_scroll_left(), tui_scroll_right(), tui_set_layout(), tui_set_source_content(), tui_show_disassem(), tui_show_disassem_and_update_source(), tui_show_frame_info(), tui_show_symtab_source(), tui_source_is_displayed(), tui_update_breakpoint_info(), tui_update_source_window_as_is(), and tui_vertical_source_scroll().
#define UNDEFINED_ITEM -1
Definition at line 72 of file tui-data.h.
Referenced by init_content_element().
#define WITH_LOCATOR TRUE
Definition at line 68 of file tui-data.h.
Typedef Documentation
typedef char tui_exec_info_content[TUI_EXECINFO_SIZE]
Definition at line 227 of file tui-data.h.
typedef struct tui_win_element** tui_win_content
Definition at line 248 of file tui-data.h.
Enumeration Type Documentation
enum tui_data_type
Enumerator:
TUI_REGISTER
TUI_SCALAR
TUI_COMPLEX
TUI_STRUCT
Definition at line 128 of file tui-data.h.
enum tui_layout_type
Enumerator:
SRC_COMMAND
DISASSEM_COMMAND
SRC_DISASSEM_COMMAND
SRC_DATA_COMMAND
DISASSEM_DATA_COMMAND
UNDEFINED_LAYOUT
Definition at line 117 of file tui-data.h.
enum tui_register_display_type
Enumerator:
TUI_UNDEFINED_REGS
TUI_GENERAL_REGS
TUI_SFLOAT_REGS
TUI_DFLOAT_REGS
TUI_SPECIAL_REGS
TUI_GENERAL_AND_SPECIAL_REGS
Definition at line 137 of file tui-data.h.
enum tui_scroll_direction
Enumerator:
FORWARD_SCROLL
BACKWARD_SCROLL
LEFT_SCROLL
RIGHT_SCROLL
Definition at line 99 of file tui-data.h.
Function Documentation
int tui_add_content_elements (struct tui_gen_win_info * , int)
Definition at line 632 of file tui-data.c.
References tui_gen_win_info::content, tui_gen_win_info::content_size, init_content_element(), tui_alloc_content(), tui_gen_win_info::type, and XMALLOC.
Referenced by tui_show_register_group().
void tui_add_to_source_windows (struct tui_win_info *)
Definition at line 196 of file tui-data.c.
References tui_list::count, and tui_list::list.
Referenced by show_data(), and show_layout().
tui_win_content tui_alloc_content (int , enum tui_win_type)
Definition at line 586 of file tui-data.c.
References DATA_WIN, init_content_element(), xfree(), and xmalloc().
Referenced by init_content_element(), tui_add_content_elements(), tui_alloc_source_buffer(), tui_set_exec_info_content(), tui_set_locator_info(), and tui_show_register_group().
struct tui_gen_win_info* tui_alloc_generic_win_info (void) [read]
Definition at line 446 of file tui-data.c.
References tui_init_generic_part(), and XMALLOC.
Referenced by init_and_make_win().
struct tui_win_info* tui_alloc_win_info (enum tui_win_type) [read]
Definition at line 569 of file tui-data.c.
References tui_win_info::generic, init_win_info(), tui_gen_win_info::type, type, and XMALLOC.
Referenced by init_and_make_win().
void tui_clear_source_windows (void)
Definition at line 173 of file tui-data.c.
References tui_list::count, and tui_list::list.
Referenced by show_layout().
void tui_clear_source_windows_detail (void)
Definition at line 183 of file tui-data.c.
References tui_list::count, tui_list::list, tui_clear_win_detail(), and tui_source_windows().
Referenced by tui_add_win_to_layout().
void tui_clear_win_detail (struct tui_win_info *)
Definition at line 205 of file tui-data.c.
References tui_line_or_address::addr, CMD_WIN, tui_win_info::command_info, tui_command_info::cur_line, tui_command_info::curch, tui_data_info::data_content, tui_data_info::data_content_count, tui_win_info::data_display_info, DATA_WIN, tui_win_info::detail, DISASSEM_WIN, tui_data_info::display_regs, tui_source_info::gdbarch, tui_win_info::generic, tui_source_info::horizontal_offset, tui_line_or_address::loa, tui_data_info::regs_column_count, tui_data_info::regs_content, tui_data_info::regs_content_count, tui_data_info::regs_display_type, tui_win_info::source_info, SRC_WIN, tui_source_info::start_line_or_addr, TUI_UNDEFINED_REGS, tui_gen_win_info::type, and tui_line_or_address::u.
Referenced by tui_clear_source_windows_detail().
enum tui_layout_type tui_current_layout (void)
Definition at line 300 of file tui-data.c.
References current_layout.
Referenced by extract_display_start_addr(), new_height_ok(), next_layout(), prev_layout(), show_layout(), show_source_disasm_command(), show_source_or_disasm_and_command(), tui_add_win_to_layout(), tui_adjust_win_heights(), tui_resize_all(), tui_rl_change_windows(), tui_rl_delete_other_windows(), tui_set_layout(), tui_set_layout_for_display_command(), tui_show_disassem(), tui_show_disassem_and_update_source(), tui_update_source_window_as_is(), tui_update_source_windows_with_addr(), and tui_update_source_windows_with_line().
int tui_default_tab_len (void)
Definition at line 145 of file tui-data.c.
References default_tab_len.
Referenced by tui_set_disassem_content(), and tui_set_source_content().
void tui_del_data_windows (tui_win_content , int)
Definition at line 816 of file tui-data.c.
References tui_which_element::data_window, tui_gen_win_info::handle, tui_gen_win_info::is_visible, tui_delete_win(), and tui_win_element::which_element.
Referenced by tui_del_window().
void tui_del_window (struct tui_win_info *)
Definition at line 669 of file tui-data.c.
References tui_gen_win_info::content, tui_data_info::data_content, tui_data_info::data_content_count, tui_win_info::data_display_info, DATA_WIN, tui_win_info::detail, DISASSEM_WIN, tui_source_info::execution_info, tui_source_info::fullname, tui_win_info::generic, tui_gen_win_info::handle, tui_gen_win_info::is_visible, tui_data_info::regs_content, tui_data_info::regs_content_count, tui_win_info::source_info, SRC_WIN, tui_del_data_windows(), tui_delete_win(), tui_locator_win_info_ptr(), tui_gen_win_info::type, and xfree().
struct tui_gen_win_info* tui_disassem_exec_info_win_ptr (void) [read]
Definition at line 251 of file tui-data.c.
References exec_info.
Referenced by make_source_or_disasm_window(), and tui_initialize_static_data().
void tui_free_all_source_wins_content (void)
Definition at line 784 of file tui-data.c.
References tui_win_info::detail, tui_source_info::execution_info, tui_win_info::generic, tui_win_info::source_info, tui_free_win_content(), and tui_source_windows().
Referenced by show_layout().
void tui_free_data_content (tui_win_content , int)
Definition at line 840 of file tui-data.c.
References tui_gen_win_info::content_size, DATA_WIN, tui_which_element::data_window, free_content(), tui_gen_win_info::handle, tui_delete_win(), tui_free_win_content(), and tui_win_element::which_element.
Referenced by tui_free_window(), and tui_show_register_group().
void tui_free_win_content (struct tui_gen_win_info *)
Definition at line 802 of file tui-data.c.
References tui_gen_win_info::content, tui_gen_win_info::content_size, free_content(), and tui_gen_win_info::type.
Referenced by make_visible_with_new_height(), tui_free_all_source_wins_content(), tui_free_data_content(), and tui_free_window().
void tui_free_window (struct tui_win_info *)
Definition at line 719 of file tui-data.c.
References tui_gen_win_info::content, tui_gen_win_info::content_size, tui_data_info::data_content, tui_data_info::data_content_count, tui_win_info::data_display_info, DATA_WIN, tui_win_info::detail, DISASSEM_WIN, tui_data_info::display_regs, tui_source_info::execution_info, tui_source_info::fullname, tui_win_info::generic, tui_gen_win_info::handle, tui_data_info::regs_column_count, tui_data_info::regs_content, tui_data_info::regs_content_count, tui_data_info::regs_display_type, tui_win_info::source_info, SRC_WIN, tui_gen_win_info::title, tui_delete_win(), tui_free_data_content(), tui_free_win_content(), tui_locator_win_info_ptr(), TUI_UNDEFINED_REGS, tui_gen_win_info::type, and xfree().
Referenced by tui_resize_all().
void tui_init_content_element (struct tui_win_element * , enum tui_win_type)
void tui_init_generic_part (struct tui_gen_win_info *)
Definition at line 458 of file tui-data.c.
References tui_gen_win_info::content, tui_gen_win_info::content_in_use, tui_gen_win_info::content_size, tui_gen_win_info::handle, tui_gen_win_info::height, tui_gen_win_info::is_visible, tui_gen_win_info::last_visible_line, tui_gen_win_info::origin, tui_gen_win_info::title, tui_gen_win_info::viewport_height, tui_gen_win_info::width, tui_point::x, and tui_point::y.
Referenced by init_content_element(), init_win_info(), tui_alloc_generic_win_info(), and tui_initialize_static_data().
void tui_init_win_info (struct tui_win_info *)
void tui_initialize_static_data (void)
Definition at line 437 of file tui-data.c.
References tui_disassem_exec_info_win_ptr(), tui_init_generic_part(), tui_locator_win_info_ptr(), and tui_source_exec_info_win_ptr().
Referenced by tui_init().
struct tui_layout_def* tui_layout_def (void) [read]
Definition at line 121 of file tui-data.c.
References layout_def.
Referenced by tui_set_layout(), tui_toggle_layout_command(), and tui_toggle_split_layout_command().
struct tui_gen_win_info* tui_locator_win_info_ptr (void) [read]
Definition at line 260 of file tui-data.c.
References _locator.
Referenced by make_invisible_and_set_new_height(), make_visible_with_new_height(), show_data(), show_layout(), show_source_disasm_command(), show_source_or_disasm_and_command(), tui_adjust_win_heights(), tui_del_window(), tui_free_window(), tui_get_begin_asm_address(), tui_initialize_static_data(), tui_refresh_all(), tui_resize_all(), tui_set_disassem_content(), tui_set_locator_fullname(), tui_set_locator_info(), tui_set_source_content(), tui_show_frame_info(), tui_show_locator_content(), and tui_source_is_displayed().
struct tui_win_info* tui_next_win (struct tui_win_info *) [read]
Definition at line 322 of file tui-data.c.
References CMD_WIN, tui_win_info::generic, SRC_WIN, tui_win_list, tui_gen_win_info::type, and type.
Referenced by tui_rl_other_window(), and tui_set_focus().
struct tui_win_info* tui_partial_win_by_name (char *) [read]
Definition at line 381 of file tui-data.c.
References MAX_MAJOR_WINDOWS, tui_win_list, and tui_win_name().
Referenced by parse_scrolling_args(), tui_set_focus(), and tui_set_win_height().
struct tui_win_info* tui_prev_win (struct tui_win_info *) [read]
Definition at line 352 of file tui-data.c.
References CMD_WIN, tui_win_info::generic, SRC_WIN, tui_win_list, tui_gen_win_info::type, and type.
Referenced by tui_set_focus().
void tui_set_current_layout_to (enum tui_layout_type)
Definition at line 308 of file tui-data.c.
References current_layout.
Referenced by show_data(), show_source_disasm_command(), and show_source_or_disasm_and_command().
void tui_set_default_tab_len (int)
Definition at line 153 of file tui-data.c.
References default_tab_len, and len.
Referenced by tui_set_tab_width_command().
void tui_set_term_height_to (int)
Definition at line 276 of file tui-data.c.
References term_height.
Referenced by tui_enable(), and tui_resize_all().
void tui_set_term_width_to (int)
Definition at line 292 of file tui-data.c.
References term_width.
Referenced by tui_enable(), and tui_resize_all().
void tui_set_win_highlight (struct tui_win_info * win_info, int highlight)
Definition at line 92 of file tui-data.c.
References tui_win_info::is_highlighted.
Referenced by tui_highlight_win(), and tui_unhighlight_win().
void tui_set_win_resized_to (int)
Definition at line 113 of file tui-data.c.
References win_resized.
Referenced by tui_handle_resize_during_io().
void tui_set_win_with_focus (struct tui_win_info *)
Definition at line 137 of file tui-data.c.
Referenced by tui_set_win_focus_to().
struct tui_gen_win_info* tui_source_exec_info_win_ptr (void) [read]
Definition at line 243 of file tui-data.c.
References exec_info.
Referenced by make_source_or_disasm_window(), and tui_initialize_static_data().
struct tui_list* tui_source_windows (void) [read]
Definition at line 163 of file tui-data.c.
References source_windows.
Referenced by new_height_ok(), parse_scrolling_args(), tui_adjust_win_heights(), tui_clear_source_windows_detail(), tui_display_main(), tui_free_all_source_wins_content(), tui_resize_all(), tui_show_frame_info(), tui_update_all_breakpoint_info(), and tui_update_source_windows_with_addr().
int tui_term_height (void)
Definition at line 268 of file tui-data.c.
References term_height.
Referenced by new_height_ok(), show_data(), show_source_disasm_command(), show_source_or_disasm_and_command(), tui_default_win_height(), tui_resize_all(), tui_update_gdb_sizes(), and tui_xdb_set_win_height().
int tui_term_width (void)
Definition at line 284 of file tui-data.c.
References term_width.
Referenced by make_command_window(), make_data_window(), make_source_or_disasm_window(), show_data(), show_source_disasm_command(), show_source_or_disasm_and_command(), tui_make_status_line(), tui_resize_all(), and tui_update_gdb_sizes().
int tui_win_has_locator (struct tui_win_info * win_info)
Definition at line 85 of file tui-data.c.
References tui_win_info::detail, tui_source_info::has_locator, and tui_win_info::source_info.
Referenced by make_invisible_and_set_new_height(), and make_visible_with_new_height().
int tui_win_is_auxillary (enum tui_win_type win_type)
Definition at line 79 of file tui-data.c.
References MAX_MAJOR_WINDOWS.
Referenced by init_and_make_win(), and make_visible().
int tui_win_is_source_type (enum tui_win_type win_type)
Definition at line 73 of file tui-data.c.
References DISASSEM_WIN, and SRC_WIN.
Referenced by make_all_visible().
char* tui_win_name (struct tui_gen_win_info *)
Definition at line 409 of file tui-data.c.
References CMD_NAME, CMD_WIN, DATA_NAME, DATA_WIN, DISASSEM_NAME, DISASSEM_WIN, name, SRC_NAME, SRC_WIN, and tui_gen_win_info::type.
Referenced by tui_all_windows_info(), tui_partial_win_by_name(), and tui_set_focus().
int tui_win_resized (void)
Definition at line 105 of file tui-data.c.
References win_resized.
Referenced by tui_handle_resize_during_io().
struct tui_win_info* tui_win_with_focus (void) [read]
Definition at line 129 of file tui-data.c.
References win_with_focus.
Referenced by parse_scrolling_args(), tui_all_windows_info(), tui_dispatch_ctrl_char(), tui_resize_all(), tui_rl_other_window(), tui_set_focus(), tui_set_layout(), tui_set_win_focus_to(), tui_show_disassem(), and tui_update_source_window_as_is().
Variable Documentation
struct tui_win_info* tui_win_list[MAX_MAJOR_WINDOWS]
Definition at line 34 of file tui-data.c.
Referenced by make_all_visible(), show_data(), show_layout(), tui_adjust_win_heights(), tui_all_windows_info(), tui_default_win_height(), tui_default_win_viewport_height(), tui_handle_xdb_layout(), tui_is_window_visible(), tui_next_win(), tui_partial_win_by_name(), tui_prev_win(), tui_refresh_all_win(), tui_resize_all(), and tui_xdb_set_win_height().