GDB (xrefs): /home/stan/gdb/src/gdb/tui/tui-win.c File Reference
/home/stan/gdb/src/gdb/tui/tui-win.c File Reference
#include "defs.h"
#include "command.h"
#include "symtab.h"
#include "breakpoint.h"
#include "frame.h"
#include "cli/cli-cmds.h"
#include "top.h"
#include "source.h"
#include "tui/tui.h"
#include "tui/tui-data.h"
#include "tui/tui-wingeneral.h"
#include "tui/tui-stack.h"
#include "tui/tui-regs.h"
#include "tui/tui-disasm.h"
#include "tui/tui-source.h"
#include "tui/tui-winsource.h"
#include "tui/tui-windata.h"
#include "tui/tui-win.h"
#include "gdb_curses.h"
#include "gdb_string.h"
#include <ctype.h>
#include "readline/readline.h"
#include <signal.h>
Classes
struct tui_translate
Defines
#define WIN_HEIGHT_USAGE "Usage: winheight <win_name> [+ | -] <#lines>\n"
#define XDBWIN_HEIGHT_USAGE "Usage: w <#lines>\n"
#define FOCUS_USAGE "Usage: focus {<win> | next | prev}\n"
#define ACS_LRCORNER '+'
#define ACS_LLCORNER '+'
#define ACS_ULCORNER '+'
#define ACS_URCORNER '+'
#define ACS_HLINE '-'
#define ACS_VLINE '|'
Functions
static void make_visible_with_new_height (struct tui_win_info *)
static void make_invisible_and_set_new_height (struct tui_win_info *, int)
static enum tui_status tui_adjust_win_heights (struct tui_win_info *, int)
static int new_height_ok (struct tui_win_info *, int)
static void tui_set_tab_width_command (char *, int)
static void tui_refresh_all_command (char *, int)
static void tui_set_win_height_command (char *, int)
static void tui_xdb_set_win_height_command (char *, int)
static void tui_all_windows_info (char *, int)
static void tui_set_focus_command (char *, int)
static void tui_scroll_forward_command (char *, int)
static void tui_scroll_backward_command (char *, int)
static void tui_scroll_left_command (char *, int)
static void tui_scroll_right_command (char *, int)
static void parse_scrolling_args (char *, struct tui_win_info **, int *)
static void show_tui_active_border_mode (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static void show_tui_border_mode (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static void show_tui_border_kind (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static struct tui_translate * translate (const char *name, struct tui_translate *table)
int tui_update_variables (void)
static void set_tui_cmd (char *args, int from_tty)
static void show_tui_cmd (char *args, int from_tty)
static void tui_command (char *args, int from_tty)
struct cmd_list_element ** tui_get_cmd_list (void)
void _initialize_tui_win (void)
void tui_update_gdb_sizes (void)
void tui_set_win_focus_to (struct tui_win_info *win_info)
void tui_scroll_forward (struct tui_win_info *win_to_scroll, int num_to_scroll)
void tui_scroll_backward (struct tui_win_info *win_to_scroll, int num_to_scroll)
void tui_scroll_left (struct tui_win_info *win_to_scroll, int num_to_scroll)
void tui_scroll_right (struct tui_win_info *win_to_scroll, int num_to_scroll)
void tui_scroll (enum tui_scroll_direction direction, struct tui_win_info *win_to_scroll, int num_to_scroll)
void tui_refresh_all_win (void)
void tui_resize_all (void)
void tui_initialize_win (void)
static void tui_set_focus (char *arg, int from_tty)
static void tui_set_win_height (char *arg, int from_tty)
static void tui_xdb_set_win_height (char *arg, int from_tty)
Variables
static const char *const tui_border_kind_enums []
static const char *const tui_border_mode_enums []
struct tui_translate tui_border_mode_translate []
struct tui_translate tui_border_kind_translate_vline []
struct tui_translate tui_border_kind_translate_hline []
struct tui_translate tui_border_kind_translate_ulcorner []
struct tui_translate tui_border_kind_translate_urcorner []
struct tui_translate tui_border_kind_translate_llcorner []
struct tui_translate tui_border_kind_translate_lrcorner []
const char * tui_active_border_mode = "bold-standout"
const char * tui_border_mode = "normal"
const char * tui_border_kind = "acs"
chtype tui_border_vline
chtype tui_border_hline
chtype tui_border_ulcorner
chtype tui_border_urcorner
chtype tui_border_llcorner
chtype tui_border_lrcorner
int tui_border_attrs
int tui_active_border_attrs
static struct cmd_list_element * tuilist
initialize_file_ftype _initialize_tui_win
Define Documentation
#define ACS_HLINE '-'
Definition at line 103 of file tui-win.c.
Referenced by tui_update_variables().
#define ACS_LLCORNER '+'
Definition at line 94 of file tui-win.c.
Referenced by tui_update_variables().
#define ACS_LRCORNER '+'
Definition at line 91 of file tui-win.c.
Referenced by tui_update_variables().
#define ACS_ULCORNER '+'
Definition at line 97 of file tui-win.c.
Referenced by tui_update_variables().
#define ACS_URCORNER '+'
Definition at line 100 of file tui-win.c.
Referenced by tui_update_variables().
#define ACS_VLINE '|'
Definition at line 106 of file tui-win.c.
Referenced by tui_update_variables().
#define FOCUS_USAGE "Usage: focus {<win> | next | prev}\n"
Definition at line 84 of file tui-win.c.
Referenced by tui_set_focus().
#define WIN_HEIGHT_USAGE "Usage: winheight <win_name> [+ | -] <#lines>\n"
Definition at line 82 of file tui-win.c.
Referenced by tui_set_win_height().
#define XDBWIN_HEIGHT_USAGE "Usage: w <#lines>\n"
Definition at line 83 of file tui-win.c.
Referenced by tui_xdb_set_win_height().
Function Documentation
void _initialize_tui_win (void)
Definition at line 356 of file tui-win.c.
References _, _initialize_tui_win, add_com(), add_com_alias(), add_info(), add_prefix_cmd(), add_setshow_enum_cmd(), class_tui, class_xdb, no_class, set_tui_cmd(), setlist, show_tui_active_border_mode(), show_tui_border_kind(), show_tui_border_mode(), show_tui_cmd(), showlist, tui_active_border_mode, tui_all_windows_info(), tui_border_kind, tui_border_kind_enums, tui_border_mode, tui_border_mode_enums, tui_refresh_all_command(), tui_scroll_backward_command(), tui_scroll_forward_command(), tui_scroll_left_command(), tui_scroll_right_command(), tui_set_focus_command(), tui_set_tab_width_command(), tui_set_win_height_command(), tui_xdb_set_win_height_command(), and xdb_commands.
static void make_invisible_and_set_new_height (struct tui_win_info * win_info, int height) [static]
Definition at line 1300 of file tui-win.c.
References tui_gen_win_info::content, tui_gen_win_info::content_size, DATA_WIN, tui_win_info::detail, DISASSEM_WIN, tui_source_info::execution_info, tui_win_info::generic, tui_gen_win_info::handle, tui_gen_win_info::height, tui_gen_win_info::origin, tui_win_info::source_info, SRC_WIN, TUI_CMD_WIN, tui_delete_win(), tui_locator_win_info_ptr(), tui_make_invisible(), tui_win_has_locator(), tui_gen_win_info::type, tui_gen_win_info::viewport_height, and tui_point::y.
Referenced by tui_adjust_win_heights(), and tui_resize_all().
static void make_visible_with_new_height (struct tui_win_info * win_info) [static]
Definition at line 1359 of file tui-win.c.
References tui_line_or_address::addr, CMD_WIN, tui_win_info::command_info, tui_gen_win_info::content, tui_command_info::cur_line, tui_command_info::curch, DATA_WIN, deprecated_safe_get_selected_frame(), tui_win_info::detail, DISASSEM_WIN, tui_source_info::execution_info, find_line_pc(), find_pc_symtab(), tui_source_info::gdbarch, tui_win_info::generic, get_current_source_symtab_and_line(), get_frame_arch(), get_frame_pc(), tui_gen_win_info::handle, symtab_and_line::line, tui_line_or_address::line_no, tui_line_or_address::loa, tui_win_info::source_info, SRC_WIN, tui_source_info::start_line_or_addr, symtab_and_line::symtab, tui_check_and_display_highlight_if_needed(), TUI_CMD_WIN, tui_display_all_data(), tui_free_win_content(), tui_locator_win_info_ptr(), tui_make_visible(), tui_show_locator_content(), tui_update_source_window(), tui_win_has_locator(), tui_gen_win_info::type, and tui_line_or_address::u.
Referenced by tui_adjust_win_heights(), and tui_resize_all().
static int new_height_ok (struct tui_win_info * primary_win_info, int new_height) [static]
Definition at line 1435 of file tui-win.c.
References CMD_WIN, DISASSEM_COMMAND, tui_win_info::generic, tui_gen_win_info::height, MIN_CMD_WIN_HEIGHT, MIN_WIN_HEIGHT, SRC_COMMAND, SRC_DISASSEM_COMMAND, TUI_CMD_WIN, tui_current_layout(), TUI_DATA_WIN, TUI_DISASM_WIN, tui_source_windows(), TUI_SRC_WIN, tui_term_height(), and tui_gen_win_info::type.
Referenced by tui_adjust_win_heights(), and tui_xdb_set_win_height().
static void parse_scrolling_args (char * arg, struct tui_win_info ** win_to_scroll, int * num_to_scroll) [static]
Definition at line 1545 of file tui-win.c.
References _, error(), tui_win_info::generic, tui_gen_win_info::is_visible, strchr(), TUI_CMD_WIN, tui_partial_win_by_name(), tui_source_windows(), tui_win_with_focus(), and xfree().
Referenced by tui_scroll_backward_command(), tui_scroll_forward_command(), tui_scroll_left_command(), and tui_scroll_right_command().
static void set_tui_cmd (char * args, int from_tty) [static]
Definition at line 320 of file tui-win.c.
Referenced by _initialize_tui_win().
static void show_tui_active_border_mode (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 206 of file tui-win.c.
References _, and fprintf_filtered().
Referenced by _initialize_tui_win().
static void show_tui_border_kind (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 230 of file tui-win.c.
References _, and fprintf_filtered().
Referenced by _initialize_tui_win().
static void show_tui_border_mode (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 218 of file tui-win.c.
References _, and fprintf_filtered().
Referenced by _initialize_tui_win().
static void show_tui_cmd (char * args, int from_tty) [static]
Definition at line 325 of file tui-win.c.
Referenced by _initialize_tui_win().
static struct tui_translate* translate (const char * name, struct tui_translate * table) [static, read]
Definition at line 256 of file tui-win.c.
References tui_translate::name.
Referenced by tui_update_variables().
static enum tui_status tui_adjust_win_heights (struct tui_win_info * primary_win_info, int new_height) [static]
Definition at line 1144 of file tui-win.c.
References CMD_WIN, tui_gen_win_info::content_size, DISASSEM_COMMAND, EMPTY_SOURCE_PROMPT, tui_win_info::generic, tui_gen_win_info::height, make_invisible_and_set_new_height(), make_visible_with_new_height(), new_height_ok(), tui_gen_win_info::origin, SRC_COMMAND, SRC_DISASSEM_COMMAND, exsummary::status, TUI_CMD_WIN, tui_current_layout(), TUI_DATA_WIN, TUI_DISASM_WIN, tui_erase_source_content(), TUI_FAILURE, tui_locator_win_info_ptr(), tui_source_windows(), TUI_SRC_WIN, TUI_SUCCESS, tui_win_list, tui_gen_win_info::type, and tui_point::y.
Referenced by tui_set_win_height(), and tui_xdb_set_win_height().
static void tui_all_windows_info (char * arg, int from_tty) [static]
Definition at line 961 of file tui-win.c.
References MAX_MAJOR_WINDOWS, printf_filtered(), SRC_WIN, tui_win_list, tui_win_name(), tui_win_with_focus(), type, and win_with_focus.
Referenced by _initialize_tui_win().
static void tui_command (char * args, int from_tty) [static]
Definition at line 332 of file tui-win.c.
References _, gdb_stdout, help_list(), and printf_unfiltered().
Referenced by tui_get_cmd_list().
struct cmd_list_element** tui_get_cmd_list (void) [read]
Definition at line 340 of file tui-win.c.
References _, add_prefix_cmd(), class_tui, cmdlist, tui_command(), and tuilist.
Referenced by _initialize_tui_regs().
void tui_initialize_win (void)
Definition at line 831 of file tui-win.c.
References memset().
Referenced by tui_init().
static void tui_refresh_all_command (char * arg, int from_tty) [static]
Definition at line 983 of file tui-win.c.
References tui_enable(), and tui_refresh_all_win().
Referenced by _initialize_tui_win().
void tui_refresh_all_win (void)
Definition at line 620 of file tui-win.c.
References DATA_WIN, DISASSEM_WIN, MAX_MAJOR_WINDOWS, SRC_WIN, tui_check_and_display_highlight_if_needed(), tui_erase_exec_info_content(), tui_refresh_all(), tui_refresh_data_win(), tui_show_locator_content(), tui_show_source_content(), tui_update_exec_info(), tui_win_list, and type.
Referenced by tui_dispatch_ctrl_char(), tui_enable(), tui_handle_resize_during_io(), and tui_refresh_all_command().
void tui_resize_all (void)
Definition at line 655 of file tui-win.c.
References CMD_WIN, tui_gen_win_info::content_size, DISASSEM_COMMAND, DISASSEM_DATA_COMMAND, EMPTY_SOURCE_PROMPT, tui_win_info::generic, tui_gen_win_info::height, tui_gen_win_info::is_visible, make_invisible_and_set_new_height(), make_visible_with_new_height(), MAX_MAJOR_WINDOWS, MIN_CMD_WIN_HEIGHT, MIN_WIN_HEIGHT, tui_gen_win_info::origin, SRC_COMMAND, SRC_DATA_COMMAND, SRC_DISASSEM_COMMAND, SRC_WIN, TUI_CMD_WIN, tui_current_layout(), TUI_DATA_WIN, TUI_DISASM_WIN, tui_erase_source_content(), tui_free_window(), tui_locator_win_info_ptr(), tui_set_term_height_to(), tui_set_term_width_to(), tui_source_windows(), TUI_SRC_WIN, tui_term_height(), tui_term_width(), tui_update_gdb_sizes(), tui_win_list, tui_win_with_focus(), tui_gen_win_info::width, win_with_focus, and tui_point::y.
Referenced by tui_handle_resize_during_io().
void tui_scroll (enum tui_scroll_direction direction, struct tui_win_info * win_to_scroll, int num_to_scroll)
Definition at line 595 of file tui-win.c.
References BACKWARD_SCROLL, FORWARD_SCROLL, LEFT_SCROLL, RIGHT_SCROLL, tui_scroll_backward(), tui_scroll_forward(), tui_scroll_left(), and tui_scroll_right().
Referenced by tui_scroll_backward_command(), tui_scroll_forward_command(), tui_scroll_left_command(), tui_scroll_regs_backward_command(), tui_scroll_regs_forward_command(), and tui_scroll_right_command().
void tui_scroll_backward (struct tui_win_info * win_to_scroll, int num_to_scroll)
Definition at line 522 of file tui-win.c.
References BACKWARD_SCROLL, tui_win_info::generic, tui_gen_win_info::height, TUI_CMD_WIN, TUI_DATA_WIN, TUI_DISASM_WIN, TUI_SRC_WIN, tui_vertical_data_scroll(), tui_vertical_disassem_scroll(), and tui_vertical_source_scroll().
Referenced by tui_dispatch_ctrl_char(), and tui_scroll().
static void tui_scroll_backward_command (char * arg, int from_tty) [static]
Definition at line 869 of file tui-win.c.
References BACKWARD_SCROLL, parse_scrolling_args(), tui_enable(), and tui_scroll().
Referenced by _initialize_tui_win().
void tui_scroll_forward (struct tui_win_info * win_to_scroll, int num_to_scroll)
Definition at line 497 of file tui-win.c.
References FORWARD_SCROLL, tui_win_info::generic, tui_gen_win_info::height, TUI_CMD_WIN, TUI_DATA_WIN, TUI_DISASM_WIN, TUI_SRC_WIN, tui_vertical_data_scroll(), tui_vertical_disassem_scroll(), and tui_vertical_source_scroll().
Referenced by tui_dispatch_ctrl_char(), and tui_scroll().
static void tui_scroll_forward_command (char * arg, int from_tty) [static]
Definition at line 853 of file tui-win.c.
References FORWARD_SCROLL, parse_scrolling_args(), tui_enable(), and tui_scroll().
Referenced by _initialize_tui_win().
void tui_scroll_left (struct tui_win_info * win_to_scroll, int num_to_scroll)
Definition at line 548 of file tui-win.c.
References LEFT_SCROLL, TUI_CMD_WIN, TUI_DISASM_WIN, tui_horizontal_source_scroll(), and TUI_SRC_WIN.
Referenced by tui_dispatch_ctrl_char(), and tui_scroll().
static void tui_scroll_left_command (char * arg, int from_tty) [static]
Definition at line 885 of file tui-win.c.
References LEFT_SCROLL, parse_scrolling_args(), tui_enable(), and tui_scroll().
Referenced by _initialize_tui_win().
void tui_scroll_right (struct tui_win_info * win_to_scroll, int num_to_scroll)
Definition at line 571 of file tui-win.c.
References RIGHT_SCROLL, TUI_CMD_WIN, TUI_DISASM_WIN, tui_horizontal_source_scroll(), and TUI_SRC_WIN.
Referenced by tui_dispatch_ctrl_char(), and tui_scroll().
static void tui_scroll_right_command (char * arg, int from_tty) [static]
Definition at line 898 of file tui-win.c.
References parse_scrolling_args(), RIGHT_SCROLL, tui_enable(), and tui_scroll().
Referenced by _initialize_tui_win().
static void tui_set_focus (char * arg, int from_tty) [static]
Definition at line 912 of file tui-win.c.
References _, FOCUS_USAGE, tui_win_info::generic, tui_gen_win_info::is_visible, printf_filtered(), subset_compare(), TUI_CMD_WIN, TUI_DATA_WIN, tui_next_win(), tui_partial_win_by_name(), tui_prev_win(), tui_refresh_data_win(), tui_set_win_focus_to(), tui_win_name(), tui_win_with_focus(), warning(), and xfree().
Referenced by tui_set_focus_command().
static void tui_set_focus_command (char * arg, int from_tty) [static]
Definition at line 952 of file tui-win.c.
References tui_enable(), and tui_set_focus().
Referenced by _initialize_tui_win().
static void tui_set_tab_width_command (char * arg, int from_tty) [static]
Definition at line 994 of file tui-win.c.
References _, tui_enable(), tui_set_default_tab_len(), and warning().
Referenced by _initialize_tui_win().
void tui_set_win_focus_to (struct tui_win_info * win_info)
Definition at line 480 of file tui-win.c.
References CMD_WIN, tui_win_info::generic, tui_highlight_win(), tui_set_win_with_focus(), tui_unhighlight_win(), tui_win_with_focus(), tui_gen_win_info::type, and win_with_focus.
Referenced by tui_enable(), tui_handle_xdb_layout(), tui_rl_other_window(), tui_set_focus(), tui_set_layout(), tui_show_disassem(), and tui_update_source_window_as_is().
static void tui_set_win_height (char * arg, int from_tty) [static]
Definition at line 1013 of file tui-win.c.
References _, tui_win_info::generic, tui_gen_win_info::height, tui_gen_win_info::is_visible, printf_filtered(), strchr(), tui_adjust_win_heights(), tui_enable(), TUI_FAILURE, tui_partial_win_by_name(), tui_update_gdb_sizes(), warning(), WIN_HEIGHT_USAGE, and xfree().
Referenced by tui_set_win_height_command().
static void tui_set_win_height_command (char * arg, int from_tty) [static]
Definition at line 1096 of file tui-win.c.
References tui_enable(), and tui_set_win_height().
Referenced by _initialize_tui_win().
void tui_update_gdb_sizes (void)
Definition at line 464 of file tui-win.c.
References execute_command(), tui_active, TUI_CMD_WIN, tui_term_height(), tui_term_width(), and xsnprintf().
Referenced by tui_disable(), tui_enable(), tui_resize_all(), and tui_set_win_height().
int tui_update_variables (void)
Definition at line 274 of file tui-win.c.
References ACS_HLINE, ACS_LLCORNER, ACS_LRCORNER, ACS_ULCORNER, ACS_URCORNER, ACS_VLINE, translate(), tui_active_border_attrs, tui_active_border_mode, tui_border_attrs, tui_border_hline, tui_border_kind, tui_border_llcorner, tui_border_lrcorner, tui_border_mode, tui_border_ulcorner, tui_border_urcorner, tui_border_vline, and tui_translate::value.
Referenced by tui_enable().
static void tui_xdb_set_win_height (char * arg, int from_tty) [static]
Definition at line 1108 of file tui-win.c.
References _, CMD_WIN, new_height_ok(), tui_adjust_win_heights(), tui_enable(), TUI_FAILURE, tui_term_height(), tui_win_list, warning(), and XDBWIN_HEIGHT_USAGE.
Referenced by tui_xdb_set_win_height_command().
static void tui_xdb_set_win_height_command (char * arg, int from_tty) [static]
Definition at line 1136 of file tui-win.c.
References tui_xdb_set_win_height().
Referenced by _initialize_tui_win().
Variable Documentation
initialize_file_ftype _initialize_tui_win
Referenced by _initialize_tui_win(), and initialize_all_files().
int tui_active_border_attrs
Definition at line 251 of file tui-win.c.
Referenced by box_win(), and tui_update_variables().
const char* tui_active_border_mode = "bold-standout"
Definition at line 204 of file tui-win.c.
Referenced by _initialize_tui_win(), and tui_update_variables().
int tui_border_attrs
Definition at line 250 of file tui-win.c.
Referenced by box_win(), and tui_update_variables().
chtype tui_border_hline
Definition at line 244 of file tui-win.c.
Referenced by box_win(), and tui_update_variables().
const char* tui_border_kind = "acs"
Definition at line 228 of file tui-win.c.
Referenced by _initialize_tui_win(), and tui_update_variables().
const char* const tui_border_kind_enums[] [static]
Initial value:
 {
  "space",
  "ascii",
  "acs",
  NULL
}
Definition at line 110 of file tui-win.c.
Referenced by _initialize_tui_win().
struct tui_translate tui_border_kind_translate_hline[]
Initial value:
 {
  { "space",    ' ' },
  { "ascii",    '-' },
  { "acs",      -1 },
  { 0, 0 },
  { "ascii",    '-' }
}
Definition at line 162 of file tui-win.c.
struct tui_translate tui_border_kind_translate_llcorner[]
Initial value:
 {
  { "space",    ' ' },
  { "ascii",    '+' },
  { "acs",      -1 },
  { 0, 0 },
  { "ascii",    '+' }
}
Definition at line 186 of file tui-win.c.
struct tui_translate tui_border_kind_translate_lrcorner[]
Initial value:
 {
  { "space",    ' ' },
  { "ascii",    '+' },
  { "acs",      -1 },
  { 0, 0 },
  { "ascii",    '+' }
}
Definition at line 194 of file tui-win.c.
struct tui_translate tui_border_kind_translate_ulcorner[]
Initial value:
 {
  { "space",    ' ' },
  { "ascii",    '+' },
  { "acs",      -1 },
  { 0, 0 },
  { "ascii",    '+' }
}
Definition at line 170 of file tui-win.c.
struct tui_translate tui_border_kind_translate_urcorner[]
Initial value:
 {
  { "space",    ' ' },
  { "ascii",    '+' },
  { "acs",      -1 },
  { 0, 0 },
  { "ascii",    '+' }
}
Definition at line 178 of file tui-win.c.
struct tui_translate tui_border_kind_translate_vline[]
Initial value:
 {
  { "space",    ' ' },
  { "ascii",    '|' },
  { "acs",      -1 },
  { 0, 0 },
  { "ascii",    '|' }
}
Definition at line 154 of file tui-win.c.
chtype tui_border_llcorner
Definition at line 247 of file tui-win.c.
Referenced by box_win(), and tui_update_variables().
chtype tui_border_lrcorner
Definition at line 248 of file tui-win.c.
Referenced by box_win(), and tui_update_variables().
const char* tui_border_mode = "normal"
Definition at line 216 of file tui-win.c.
Referenced by _initialize_tui_win(), and tui_update_variables().
const char* const tui_border_mode_enums[] [static]
Initial value:
 {
  "normal",
  "standout",
  "reverse",
  "half",
  "half-standout",
  "bold",
  "bold-standout",
  NULL
}
Definition at line 118 of file tui-win.c.
Referenced by _initialize_tui_win().
struct tui_translate tui_border_mode_translate[]
Initial value:
 {
  { "normal",           A_NORMAL },
  { "standout",         A_STANDOUT },
  { "reverse",          A_REVERSE },
  { "half",             A_DIM },
  { "half-standout",    A_DIM | A_STANDOUT },
  { "bold",             A_BOLD },
  { "bold-standout",    A_BOLD | A_STANDOUT },
  { 0, 0 },
  { "normal",           A_NORMAL }
}
Definition at line 138 of file tui-win.c.
chtype tui_border_ulcorner
Definition at line 245 of file tui-win.c.
Referenced by box_win(), and tui_update_variables().
chtype tui_border_urcorner
Definition at line 246 of file tui-win.c.
Referenced by box_win(), and tui_update_variables().
chtype tui_border_vline
Definition at line 243 of file tui-win.c.
Referenced by box_win(), and tui_update_variables().
struct cmd_list_element* tuilist [static]
Definition at line 329 of file tui-win.c.
Referenced by tui_get_cmd_list().