GDB (xrefs): /home/stan/gdb/src/gdb/tui/tui-file.h File Reference
/home/stan/gdb/src/gdb/tui/tui-file.h File Reference
Functions
struct ui_file * tui_fileopen (FILE *)
struct ui_file * tui_sfileopen (int)
char * tui_file_get_strbuf (struct ui_file *)
void tui_file_adjust_strbuf (int, struct ui_file *)
Function Documentation
void tui_file_adjust_strbuf (int , struct ui_file *)
Definition at line 202 of file tui-file.c.
References _, astring, internal_error(), tui_stream::ts_buflen, tui_stream::ts_magic, tui_stream::ts_strbuf, tui_stream::ts_streamtype, tui_file_magic, ui_file_data(), xmalloc(), and xrealloc().
Referenced by tui_file_fputs().
char* tui_file_get_strbuf (struct ui_file *)
Definition at line 188 of file tui-file.c.
References _, internal_error(), tui_stream::ts_magic, tui_stream::ts_strbuf, tui_file_magic, and ui_file_data().
Referenced by tui_disassemble(), tui_get_function_from_frame(), tui_make_status_line(), and tui_register_format().
struct ui_file* tui_fileopen (FILE *) [read]
Definition at line 90 of file tui-file.c.
References afile, tui_stream::ts_buflen, tui_stream::ts_filestream, tui_stream::ts_strbuf, tui_stream::ts_streamtype, tui_file_new(), and ui_file_data().
Referenced by tui_initialize_io().
struct ui_file* tui_sfileopen (int) [read]
Definition at line 103 of file tui-file.c.
References astring, tui_stream::ts_buflen, tui_stream::ts_filestream, tui_stream::ts_strbuf, tui_stream::ts_streamtype, tui_file_new(), ui_file_data(), and xmalloc().
Referenced by tui_disassemble(), tui_get_function_from_frame(), tui_make_status_line(), and tui_register_format().