GDB (xrefs): /home/stan/gdb/src/gdb/tui/tui.h File Reference
/home/stan/gdb/src/gdb/tui/tui.h File Reference
Enumerations
enum tui_status { TUI_SUCCESS, TUI_FAILURE }
enum tui_win_type {
SRC_WIN = 0, DISASSEM_WIN, DATA_WIN, CMD_WIN,
MAX_MAJOR_WINDOWS, LOCATOR_WIN, EXEC_INFO_WIN, DATA_ITEM_WIN,
MAX_WINDOWS, UNDEFINED_WIN
}
enum tui_key_mode { TUI_COMMAND_MODE, TUI_SINGLE_KEY_MODE, TUI_ONE_COMMAND_MODE }
Functions
void strcat_to_buf (char *, int, const char *)
CORE_ADDR tui_get_low_disassembly_address (struct gdbarch *, CORE_ADDR, CORE_ADDR)
void tui_show_assembly (struct gdbarch *gdbarch, CORE_ADDR addr)
int tui_is_window_visible (enum tui_win_type type)
int tui_get_command_dimension (unsigned int *width, unsigned int *height)
void tui_initialize_readline (void)
int tui_allowed_p (void)
void tui_enable (void)
void tui_disable (void)
void tui_set_key_mode (enum tui_key_mode mode)
void tui_show_source (const char *fullname, int line)
struct ui_out * tui_out_new (struct ui_file *stream)
enum tui_status tui_set_layout_for_display_command (const char *)
Variables
enum tui_key_mode tui_current_key_mode
int tui_active
Enumeration Type Documentation
enum tui_key_mode
Enumerator:
TUI_COMMAND_MODE
TUI_SINGLE_KEY_MODE
TUI_ONE_COMMAND_MODE
Definition at line 77 of file tui.h.
enum tui_status
Enumerator:
TUI_SUCCESS
TUI_FAILURE
Definition at line 30 of file tui.h.
enum tui_win_type
Enumerator:
SRC_WIN
DISASSEM_WIN
DATA_WIN
CMD_WIN
MAX_MAJOR_WINDOWS
LOCATOR_WIN
EXEC_INFO_WIN
DATA_ITEM_WIN
MAX_WINDOWS
UNDEFINED_WIN
Definition at line 37 of file tui.h.
Function Documentation
void strcat_to_buf (char * , int , const char *)
Definition at line 467 of file tui.c.
Referenced by tui_make_status_line(), tui_set_locator_fullname(), and tui_set_locator_info().
int tui_allowed_p (void)
Definition at line 75 of file tui-interp.c.
References gdb_stdout, tui_is_toplevel, and ui_file_isatty().
Referenced by tui_enable().
void tui_disable (void)
Definition at line 439 of file tui.c.
References target_terminal_save_ours, tui_active, tui_readline_standard_keymap, tui_remove_hooks(), tui_setup_io(), and tui_update_gdb_sizes().
Referenced by tui_exit(), tui_rl_switch_mode(), and tui_suspend().
void tui_enable (void)
Definition at line 370 of file tui.c.
References _, deprecated_safe_get_selected_frame(), error(), SRC_COMMAND, target_terminal_save_ours, tui_active, tui_allowed_p(), TUI_CMD_WIN, tui_current_key_mode, tui_finish_init, tui_install_hooks(), tui_refresh_all_win(), tui_rl_startup_hook(), tui_set_key_mode(), tui_set_layout(), tui_set_term_height_to(), tui_set_term_width_to(), tui_set_win_focus_to(), tui_setup_io(), tui_show_frame_info(), TUI_SRC_WIN, TUI_UNDEFINED_REGS, tui_update_gdb_sizes(), and tui_update_variables().
Referenced by tui_layout_command(), tui_refresh_all_command(), tui_resume(), tui_rl_switch_mode(), tui_scroll_backward_command(), tui_scroll_forward_command(), tui_scroll_left_command(), tui_scroll_right_command(), tui_set_focus_command(), tui_set_tab_width_command(), tui_set_win_height(), tui_set_win_height_command(), tui_show_registers(), tui_toggle_layout_command(), tui_toggle_split_layout_command(), and tui_xdb_set_win_height().
int tui_get_command_dimension (unsigned int * width, unsigned int * height)
Definition at line 566 of file tui.c.
References tui_active, and TUI_CMD_WIN.
Referenced by init_page_info().
CORE_ADDR tui_get_low_disassembly_address (struct gdbarch * , CORE_ADDR , CORE_ADDR)
Definition at line 370 of file tui-disasm.c.
References DISASSEM_COMMAND, DISASSEM_WIN, tui_default_win_viewport_height(), and tui_find_disassembly_address().
Referenced by disassemble_command(), disassemble_current_function(), and tui_show_frame_info().
void tui_initialize_readline (void)
Definition at line 312 of file tui.c.
References tui_char_command::cmd, tui_keymap, tui_readline_standard_keymap, tui_rl_change_windows(), tui_rl_command_key(), tui_rl_command_mode(), tui_rl_delete_other_windows(), tui_rl_next_keymap(), tui_rl_other_window(), and tui_rl_switch_mode().
Referenced by tui_init().
int tui_is_window_visible (enum tui_win_type type)
Definition at line 554 of file tui.c.
References tui_win_info::generic, tui_gen_win_info::is_visible, tui_active, tui_win_list, and type.
Referenced by print_disassembly(), and tui_selected_frame_level_changed_hook().
struct ui_out* tui_out_new (struct ui_file * stream) [read]
Definition at line 149 of file tui-out.c.
References tui_ui_out_data::base, cli_out_data_ctor(), ui_out::data, flags, tui_ui_out_data::line, tui_ui_out_data::start_of_line, tui_ui_out_impl, ui_out_new(), and XMALLOC.
Referenced by tui_initialize_io().
void tui_set_key_mode (enum tui_key_mode mode)
Definition at line 301 of file tui.c.
References tui_current_key_mode, tui_keymap, tui_readline_standard_keymap, tui_show_locator_content(), and TUI_SINGLE_KEY_MODE.
Referenced by tui_enable(), tui_inferior_exit(), tui_redisplay_readline(), tui_rl_command_key(), tui_rl_command_mode(), tui_rl_next_keymap(), and tui_rl_startup_hook().
enum tui_status tui_set_layout_for_display_command (const char *)
Definition at line 420 of file tui-layout.c.
References _, DISASSEM_COMMAND, DISASSEM_DATA_COMMAND, next_layout(), prev_layout(), SRC_COMMAND, SRC_DATA_COMMAND, SRC_DISASSEM_COMMAND, exsummary::status, subset_compare(), tui_current_layout(), TUI_DATA_WIN, TUI_DFLOAT_REGS, TUI_FAILURE, TUI_FLOAT_REGS_NAME, TUI_GENERAL_AND_SPECIAL_REGS, TUI_GENERAL_REGS, TUI_GENERAL_REGS_NAME, TUI_GENERAL_SPECIAL_REGS_NAME, tui_set_layout(), TUI_SFLOAT_REGS, TUI_SPECIAL_REGS, TUI_SPECIAL_REGS_NAME, TUI_SUCCESS, TUI_UNDEFINED_REGS, UNDEFINED_LAYOUT, warning(), and xfree().
Referenced by display_command(), tui_layout_command(), and tui_show_registers().
void tui_show_assembly (struct gdbarch * gdbarch, CORE_ADDR addr)
Definition at line 547 of file tui.c.
References DISASSEM_WIN, tui_add_win_to_layout(), and tui_update_source_windows_with_addr().
Referenced by print_disassembly().
void tui_show_source (const char * fullname, int line)
Definition at line 535 of file tui.c.
References get_current_source_symtab_and_line(), SRC_WIN, symtab_and_line::symtab, tui_add_win_to_layout(), tui_update_locator_fullname(), and tui_update_source_windows_with_line().
Referenced by tui_field_string().
Variable Documentation
int tui_active
Definition at line 59 of file tui.c.
Referenced by disassemble_command(), disassemble_current_function(), display_command(), tui_about_to_proceed(), tui_disable(), tui_enable(), tui_get_command_dimension(), tui_is_window_visible(), tui_new_objfile_hook(), tui_rl_change_windows(), tui_rl_delete_other_windows(), tui_rl_next_keymap(), tui_rl_other_window(), tui_rl_switch_mode(), tui_suspend(), tui_ui_out(), and tui_update_gdb_sizes().
enum tui_key_mode tui_current_key_mode
Definition at line 62 of file tui.c.
Referenced by tui_enable(), tui_make_status_line(), tui_redisplay_readline(), tui_rl_next_keymap(), tui_rl_startup_hook(), and tui_set_key_mode().