GDB (xrefs): /home/stan/gdb/src/gdb/tui/tui.c File Reference
/home/stan/gdb/src/gdb/tui/tui.c File Reference
#include "defs.h"
#include "gdbcmd.h"
#include "tui/tui.h"
#include "tui/tui-hooks.h"
#include "tui/tui-data.h"
#include "tui/tui-layout.h"
#include "tui/tui-io.h"
#include "tui/tui-regs.h"
#include "tui/tui-stack.h"
#include "tui/tui-win.h"
#include "tui/tui-winsource.h"
#include "tui/tui-windata.h"
#include "target.h"
#include "frame.h"
#include "breakpoint.h"
#include "inferior.h"
#include "symtab.h"
#include "source.h"
#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include <signal.h>
#include <fcntl.h>
#include <setjmp.h>
#include "gdb_curses.h"
#include "readline/readline.h"
Classes
struct tui_char_command
Functions
static int tui_rl_switch_mode (int notused1, int notused2)
static int tui_rl_change_windows (int notused1, int notused2)
static int tui_rl_delete_other_windows (int notused1, int notused2)
static int tui_rl_other_window (int count, int key)
static int tui_rl_command_key (int count, int key)
static int tui_rl_command_mode (int count, int key)
static int tui_rl_next_keymap (int notused1, int notused2)
static int tui_rl_startup_hook (void)
void tui_set_key_mode (enum tui_key_mode mode)
void tui_initialize_readline (void)
void tui_enable (void)
void tui_disable (void)
void strcat_to_buf (char *buf, int buflen, const char *item_to_add)
void tui_show_source (const char *fullname, int line)
void tui_show_assembly (struct gdbarch *gdbarch, CORE_ADDR addr)
int tui_is_window_visible (enum tui_win_type type)
int tui_get_command_dimension (unsigned int *width, unsigned int *height)
Variables
int tui_active = 0
static int tui_finish_init = 1
enum tui_key_mode tui_current_key_mode = TUI_COMMAND_MODE
static struct tui_char_command tui_commands []
static Keymap tui_keymap
static Keymap tui_readline_standard_keymap
Function Documentation
void strcat_to_buf (char * buf, int buflen, const char * item_to_add)
Definition at line 467 of file tui.c.
Referenced by tui_make_status_line(), tui_set_locator_fullname(), and tui_set_locator_info().
void tui_disable (void)
Definition at line 439 of file tui.c.
References target_terminal_save_ours, tui_active, tui_readline_standard_keymap, tui_remove_hooks(), tui_setup_io(), and tui_update_gdb_sizes().
Referenced by tui_exit(), tui_rl_switch_mode(), and tui_suspend().
void tui_enable (void)
Definition at line 370 of file tui.c.
References _, deprecated_safe_get_selected_frame(), error(), SRC_COMMAND, target_terminal_save_ours, tui_active, tui_allowed_p(), TUI_CMD_WIN, tui_current_key_mode, tui_finish_init, tui_install_hooks(), tui_refresh_all_win(), tui_rl_startup_hook(), tui_set_key_mode(), tui_set_layout(), tui_set_term_height_to(), tui_set_term_width_to(), tui_set_win_focus_to(), tui_setup_io(), tui_show_frame_info(), TUI_SRC_WIN, TUI_UNDEFINED_REGS, tui_update_gdb_sizes(), and tui_update_variables().
Referenced by tui_layout_command(), tui_refresh_all_command(), tui_resume(), tui_rl_switch_mode(), tui_scroll_backward_command(), tui_scroll_forward_command(), tui_scroll_left_command(), tui_scroll_right_command(), tui_set_focus_command(), tui_set_tab_width_command(), tui_set_win_height(), tui_set_win_height_command(), tui_show_registers(), tui_toggle_layout_command(), tui_toggle_split_layout_command(), and tui_xdb_set_win_height().
int tui_get_command_dimension (unsigned int * width, unsigned int * height)
Definition at line 566 of file tui.c.
References tui_active, and TUI_CMD_WIN.
Referenced by init_page_info().
void tui_initialize_readline (void)
Definition at line 312 of file tui.c.
References tui_char_command::cmd, tui_keymap, tui_readline_standard_keymap, tui_rl_change_windows(), tui_rl_command_key(), tui_rl_command_mode(), tui_rl_delete_other_windows(), tui_rl_next_keymap(), tui_rl_other_window(), and tui_rl_switch_mode().
Referenced by tui_init().
int tui_is_window_visible (enum tui_win_type type)
Definition at line 554 of file tui.c.
References tui_win_info::generic, tui_gen_win_info::is_visible, tui_active, tui_win_list, and type.
Referenced by print_disassembly(), and tui_selected_frame_level_changed_hook().
static int tui_rl_change_windows (int notused1, int notused2) [static]
Definition at line 130 of file tui.c.
References DISASSEM_COMMAND, DISASSEM_DATA_COMMAND, SRC_COMMAND, SRC_DATA_COMMAND, SRC_DISASSEM_COMMAND, tui_active, tui_current_layout(), tui_rl_switch_mode(), tui_set_layout(), and TUI_UNDEFINED_REGS.
Referenced by tui_initialize_readline().
static int tui_rl_command_key (int count, int key) [static]
Definition at line 234 of file tui.c.
References tui_char_command::cmd, reinitialize_more_filter(), TUI_ONE_COMMAND_MODE, and tui_set_key_mode().
Referenced by tui_initialize_readline().
static int tui_rl_command_mode (int count, int key) [static]
Definition at line 265 of file tui.c.
References TUI_ONE_COMMAND_MODE, and tui_set_key_mode().
Referenced by tui_initialize_readline().
static int tui_rl_delete_other_windows (int notused1, int notused2) [static]
Definition at line 178 of file tui.c.
References DISASSEM_COMMAND, DISASSEM_DATA_COMMAND, SRC_COMMAND, SRC_DATA_COMMAND, SRC_DISASSEM_COMMAND, tui_active, tui_current_layout(), tui_rl_switch_mode(), tui_set_layout(), and TUI_UNDEFINED_REGS.
Referenced by tui_initialize_readline().
static int tui_rl_next_keymap (int notused1, int notused2) [static]
Definition at line 274 of file tui.c.
References tui_active, TUI_COMMAND_MODE, tui_current_key_mode, tui_rl_switch_mode(), tui_set_key_mode(), and TUI_SINGLE_KEY_MODE.
Referenced by tui_initialize_readline().
static int tui_rl_other_window (int count, int key) [static]
Definition at line 213 of file tui.c.
References tui_active, TUI_CMD_WIN, TUI_DATA_WIN, tui_next_win(), tui_refresh_data_win(), tui_rl_switch_mode(), tui_set_win_focus_to(), and tui_win_with_focus().
Referenced by tui_initialize_readline().
static int tui_rl_startup_hook (void) [static]
Definition at line 289 of file tui.c.
References immediate_quit, TUI_COMMAND_MODE, tui_current_key_mode, tui_redisplay_readline(), tui_set_key_mode(), and TUI_SINGLE_KEY_MODE.
Referenced by tui_enable().
static int tui_rl_switch_mode (int notused1, int notused2) [static]
Definition at line 91 of file tui.c.
References dont_repeat(), tui_active, tui_disable(), and tui_enable().
Referenced by tui_initialize_readline(), tui_rl_change_windows(), tui_rl_delete_other_windows(), tui_rl_next_keymap(), and tui_rl_other_window().
void tui_set_key_mode (enum tui_key_mode mode)
Definition at line 301 of file tui.c.
References tui_current_key_mode, tui_keymap, tui_readline_standard_keymap, tui_show_locator_content(), and TUI_SINGLE_KEY_MODE.
Referenced by tui_enable(), tui_inferior_exit(), tui_redisplay_readline(), tui_rl_command_key(), tui_rl_command_mode(), tui_rl_next_keymap(), and tui_rl_startup_hook().
void tui_show_assembly (struct gdbarch * gdbarch, CORE_ADDR addr)
Definition at line 547 of file tui.c.
References DISASSEM_WIN, tui_add_win_to_layout(), and tui_update_source_windows_with_addr().
Referenced by print_disassembly().
void tui_show_source (const char * fullname, int line)
Definition at line 535 of file tui.c.
References get_current_source_symtab_and_line(), SRC_WIN, symtab_and_line::symtab, tui_add_win_to_layout(), tui_update_locator_fullname(), and tui_update_source_windows_with_line().
Referenced by tui_field_string().
Variable Documentation
int tui_active = 0
Definition at line 59 of file tui.c.
Referenced by disassemble_command(), disassemble_current_function(), display_command(), tui_about_to_proceed(), tui_disable(), tui_enable(), tui_get_command_dimension(), tui_is_window_visible(), tui_new_objfile_hook(), tui_rl_change_windows(), tui_rl_delete_other_windows(), tui_rl_next_keymap(), tui_rl_other_window(), tui_rl_switch_mode(), tui_suspend(), tui_ui_out(), and tui_update_gdb_sizes().
struct tui_char_command tui_commands[] [static]
Initial value:
 {
  { 'c', "continue" },
  { 'd', "down" },
  { 'f', "finish" },
  { 'n', "next" },
  { 'r', "run" },
  { 's', "step" },
  { 'u', "up" },
  { 'v', "info locals" },
  { 'w', "where" },
  { 0, 0 },
}
Definition at line 72 of file tui.c.
enum tui_key_mode tui_current_key_mode = TUI_COMMAND_MODE
Definition at line 62 of file tui.c.
Referenced by tui_enable(), tui_make_status_line(), tui_redisplay_readline(), tui_rl_next_keymap(), tui_rl_startup_hook(), and tui_set_key_mode().
int tui_finish_init = 1 [static]
Definition at line 60 of file tui.c.
Referenced by tui_enable().
Keymap tui_keymap [static]
Definition at line 85 of file tui.c.
Referenced by tui_initialize_readline(), and tui_set_key_mode().
Keymap tui_readline_standard_keymap [static]
Definition at line 86 of file tui.c.
Referenced by tui_disable(), tui_initialize_readline(), and tui_set_key_mode().