GDB (xrefs): /home/stan/gdb/src/gdb/typeprint.h File Reference
/home/stan/gdb/src/gdb/typeprint.h File Reference
Classes
struct type_print_options
Functions
void recursively_update_typedef_hash (struct typedef_hash_table *, struct type *)
void add_template_parameters (struct typedef_hash_table *, struct type *)
struct typedef_hash_table * create_typedef_hash (void)
void free_typedef_hash (struct typedef_hash_table *)
struct cleanup * make_cleanup_free_typedef_hash (struct typedef_hash_table *)
struct typedef_hash_table * copy_typedef_hash (struct typedef_hash_table *)
const char * find_typedef_in_hash (const struct type_print_options *, struct type *)
void print_type_scalar (struct type *type, LONGEST, struct ui_file *)
void c_type_print_varspec_suffix (struct type *, struct ui_file *, int, int, int, const struct type_print_options *)
void c_type_print_args (struct type *, struct ui_file *, int, enum language, const struct type_print_options *)
Variables
struct type_print_options type_print_raw_options
Function Documentation
void add_template_parameters (struct typedef_hash_table * , struct type *)
Definition at line 142 of file typeprint.c.
References LOC_TYPEDEF, typedef_hash_table::storage, SYMBOL_CLASS, SYMBOL_LINKAGE_NAME, SYMBOL_TYPE, typedef_hash_table::table, TYPE_N_TEMPLATE_ARGUMENTS, and TYPE_TEMPLATE_ARGUMENT.
Referenced by c_type_print_base().
void c_type_print_args (struct type * , struct ui_file * , int , enum language, const struct type_print_options *)
void c_type_print_varspec_suffix (struct type * , struct ui_file * , int , int , int , const struct type_print_options *)
Definition at line 666 of file c-typeprint.c.
References _, c_type_print_args(), c_type_print_varspec_suffix(), current_language, error(), fprintf_filtered(), get_array_bounds(), language_defn::la_language, LONGEST, plongest(), QUIT, TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_BOOL, TYPE_CODE_CHAR, TYPE_CODE_COMPLEX, TYPE_CODE_DECFLOAT, TYPE_CODE_ENUM, TYPE_CODE_ERROR, TYPE_CODE_FLT, TYPE_CODE_FUNC, TYPE_CODE_INT, TYPE_CODE_MEMBERPTR, TYPE_CODE_METHOD, TYPE_CODE_METHODPTR, TYPE_CODE_NAMESPACE, TYPE_CODE_PTR, TYPE_CODE_RANGE, TYPE_CODE_REF, TYPE_CODE_SET, TYPE_CODE_STRING, TYPE_CODE_STRUCT, TYPE_CODE_TYPEDEF, TYPE_CODE_UNDEF, TYPE_CODE_UNION, TYPE_CODE_VOID, TYPE_NAME, TYPE_TARGET_TYPE, and TYPE_VECTOR.
Referenced by c_print_type(), c_type_print_varspec_suffix(), and java_print_type().
struct typedef_hash_table* copy_typedef_hash (struct typedef_hash_table *) [read]
Definition at line 230 of file typeprint.c.
References copy_typedef_hash_element(), create_typedef_hash(), and typedef_hash_table::table.
Referenced by c_type_print_base().
struct typedef_hash_table* create_typedef_hash (void) [read]
Definition at line 171 of file typeprint.c.
References eq_typedef_field(), hash_typedef_field(), typedef_hash_table::storage, typedef_hash_table::table, xcalloc(), and xfree().
Referenced by c_type_print_base(), copy_typedef_hash(), and create_global_typedef_table().
const char* find_typedef_in_hash (const struct type_print_options * , struct type *)
Definition at line 317 of file typeprint.c.
References find_global_typedef(), type_print_options::local_typedefs, and typedef_hash_table::table.
Referenced by c_print_type(), and find_typedef_for_canonicalize().
void free_typedef_hash (struct typedef_hash_table *)
Definition at line 186 of file typeprint.c.
References typedef_hash_table::storage, typedef_hash_table::table, and xfree().
Referenced by do_free_global_table(), and do_free_typedef_hash().
struct cleanup* make_cleanup_free_typedef_hash (struct typedef_hash_table *) [read]
Definition at line 207 of file typeprint.c.
References do_free_typedef_hash(), and make_cleanup().
Referenced by c_type_print_base().
void print_type_scalar (struct type * type, LONGEST , struct ui_file *)
Definition at line 523 of file typeprint.c.
References _, CHECK_TYPEDEF, error(), fprintf_filtered(), fputs_filtered(), gdb_flush(), LA_PRINT_CHAR, len, print_longest(), print_type_scalar(), TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_BOOL, TYPE_CODE_CHAR, TYPE_CODE_ENUM, TYPE_CODE_ERROR, TYPE_CODE_FLT, TYPE_CODE_FUNC, TYPE_CODE_INT, TYPE_CODE_MEMBERPTR, TYPE_CODE_METHOD, TYPE_CODE_METHODPTR, TYPE_CODE_NAMESPACE, TYPE_CODE_PTR, TYPE_CODE_RANGE, TYPE_CODE_REF, TYPE_CODE_SET, TYPE_CODE_STRING, TYPE_CODE_STRUCT, TYPE_CODE_UNDEF, TYPE_CODE_UNION, TYPE_CODE_VOID, TYPE_FIELD_ENUMVAL, TYPE_FIELD_NAME, TYPE_NFIELDS, TYPE_TARGET_TYPE, and TYPE_UNSIGNED.
Referenced by m2_print_bounds(), m2_print_long_set(), m2_range(), m2_val_print(), pascal_type_print_base(), pascal_val_print(), and print_type_scalar().
void recursively_update_typedef_hash (struct typedef_hash_table * , struct type *)
Definition at line 113 of file typeprint.c.
References recursively_update_typedef_hash(), typedef_hash_table::table, TYPE_BASECLASS, TYPE_N_BASECLASSES, TYPE_TYPEDEF_FIELD, and TYPE_TYPEDEF_FIELD_COUNT.
Referenced by c_type_print_base(), and recursively_update_typedef_hash().
Variable Documentation
struct type_print_options type_print_raw_options
Definition at line 51 of file typeprint.c.
Referenced by ada_print_subexp(), ada_print_typedef(), cp_print_class_member(), dwarf2_compute_name(), gnuv3_print_method_ptr(), print_symbol(), typy_str(), and user_select_syms().