GDB (xrefs): /home/stan/gdb/src/gdb/ui-out.h File Reference
/home/stan/gdb/src/gdb/ui-out.h File Reference
Classes
struct ui_out_impl
Typedefs
typedef void(table_begin_ftype)(struct ui_out *uiout, int nbrofcols, int nr_rows, const char *tblid)
typedef void(table_body_ftype)(struct ui_out *uiout)
typedef void(table_end_ftype)(struct ui_out *uiout)
typedef void(table_header_ftype)(struct ui_out *uiout, int width, enum ui_align align, const char *col_name, const char *colhdr)
typedef void(ui_out_begin_ftype)(struct ui_out *uiout, enum ui_out_type type, int level, const char *id)
typedef void(ui_out_end_ftype)(struct ui_out *uiout, enum ui_out_type type, int level)
typedef void(field_int_ftype)(struct ui_out *uiout, int fldno, int width, enum ui_align align, const char *fldname, int value)
typedef void(field_skip_ftype)(struct ui_out *uiout, int fldno, int width, enum ui_align align, const char *fldname)
typedef void(field_string_ftype)(struct ui_out *uiout, int fldno, int width, enum ui_align align, const char *fldname, const char *string)
typedef void(field_fmt_ftype)(struct ui_out *uiout, int fldno, int width, enum ui_align align, const char *fldname, const char *format, va_list args) ATTRIBUTE_FPTR_PRINTF(6
typedef void() typedef void(spaces_ftype)(struct ui_out *uiout, int numspaces)
typedef void(text_ftype)(struct ui_out *uiout, const char *string)
typedef void(message_ftype)(struct ui_out *uiout, int verbosity, const char *format, va_list args) ATTRIBUTE_FPTR_PRINTF(3
typedef void() typedef void(wrap_hint_ftype)(struct ui_out *uiout, char *identstring)
typedef void(flush_ftype)(struct ui_out *uiout)
typedef int(redirect_ftype)(struct ui_out *uiout, struct ui_file *outstream)
typedef void(data_destroy_ftype)(struct ui_out *uiout)
Enumerations
enum ui_align { ui_left = -1, ui_center, ui_right, ui_noalign }
enum ui_flags { ui_from_tty = 1, ui_source_list = 2 }
enum ui_out_type { ui_out_type_tuple, ui_out_type_list }
Functions
void ui_out_begin (struct ui_out *uiout, enum ui_out_type level_type, const char *id)
void ui_out_end (struct ui_out *uiout, enum ui_out_type type)
struct cleanup * ui_out_begin_cleanup_end (struct ui_out *uiout, enum ui_out_type level_type, const char *id)
void ui_out_table_header (struct ui_out *uiout, int width, enum ui_align align, const char *col_name, const char *colhdr)
void ui_out_table_body (struct ui_out *uiout)
struct cleanup * make_cleanup_ui_out_table_begin_end (struct ui_out *ui_out, int nr_cols, int nr_rows, const char *tblid)
struct cleanup * make_cleanup_ui_out_list_begin_end (struct ui_out *uiout, const char *id)
struct cleanup * make_cleanup_ui_out_tuple_begin_end (struct ui_out *uiout, const char *id)
void ui_out_field_int (struct ui_out *uiout, const char *fldname, int value)
void ui_out_field_fmt_int (struct ui_out *uiout, int width, enum ui_align align, const char *fldname, int value)
void ui_out_field_core_addr (struct ui_out *uiout, const char *fldname, struct gdbarch *gdbarch, CORE_ADDR address)
void ui_out_field_string (struct ui_out *uiout, const char *fldname, const char *string)
void ui_out_field_stream (struct ui_out *uiout, const char *fldname, struct ui_file *stream)
void ui_out_field_fmt (struct ui_out *uiout, const char *fldname, const char *format,...) ATTRIBUTE_PRINTF(3
void void ui_out_field_skip (struct ui_out *uiout, const char *fldname)
void ui_out_spaces (struct ui_out *uiout, int numspaces)
void ui_out_text (struct ui_out *uiout, const char *string)
void ui_out_message (struct ui_out *uiout, int verbosity, const char *format,...) ATTRIBUTE_PRINTF(3
void void ui_out_wrap_hint (struct ui_out *uiout, char *identstring)
void ui_out_flush (struct ui_out *uiout)
int ui_out_set_flags (struct ui_out *uiout, int mask)
int ui_out_clear_flags (struct ui_out *uiout, int mask)
int ui_out_get_verblvl (struct ui_out *uiout)
int ui_out_test_flags (struct ui_out *uiout, int mask)
int ui_out_query_field (struct ui_out *uiout, int colno, int *width, int *alignment, char **col_name)
int ui_out_is_mi_like_p (struct ui_out *uiout)
void * ui_out_data (struct ui_out *uiout)
void uo_field_string (struct ui_out *uiout, int fldno, int width, enum ui_align align, const char *fldname, const char *string)
struct ui_out * ui_out_new (struct ui_out_impl *impl, void *data, int flags)
void ui_out_destroy (struct ui_out *uiout)
int ui_out_redirect (struct ui_out *uiout, struct ui_file *outstream)
Variables
struct ui_out * current_uiout
Typedef Documentation
typedef void(data_destroy_ftype)(struct ui_out *uiout)
Definition at line 200 of file ui-out.h.
typedef void(field_fmt_ftype)(struct ui_out *uiout, int fldno, int width, enum ui_align align, const char *fldname, const char *format, va_list args) ATTRIBUTE_FPTR_PRINTF(6
Definition at line 185 of file ui-out.h.
typedef void(field_int_ftype)(struct ui_out *uiout, int fldno, int width, enum ui_align align, const char *fldname, int value)
Definition at line 175 of file ui-out.h.
typedef void(field_skip_ftype)(struct ui_out *uiout, int fldno, int width, enum ui_align align, const char *fldname)
Definition at line 178 of file ui-out.h.
typedef void(field_string_ftype)(struct ui_out *uiout, int fldno, int width, enum ui_align align, const char *fldname, const char *string)
Definition at line 181 of file ui-out.h.
typedef void(flush_ftype)(struct ui_out *uiout)
Definition at line 197 of file ui-out.h.
typedef void(message_ftype)(struct ui_out *uiout, int verbosity, const char *format, va_list args) ATTRIBUTE_FPTR_PRINTF(3
Definition at line 193 of file ui-out.h.
typedef int(redirect_ftype)(struct ui_out *uiout, struct ui_file *outstream)
Definition at line 198 of file ui-out.h.
typedef void() typedef void(spaces_ftype)(struct ui_out *uiout, int numspaces)
Definition at line 190 of file ui-out.h.
typedef void(table_begin_ftype)(struct ui_out *uiout, int nbrofcols, int nr_rows, const char *tblid)
Definition at line 159 of file ui-out.h.
typedef void(table_body_ftype)(struct ui_out *uiout)
Definition at line 162 of file ui-out.h.
typedef void(table_end_ftype)(struct ui_out *uiout)
Definition at line 163 of file ui-out.h.
typedef void(table_header_ftype)(struct ui_out *uiout, int width, enum ui_align align, const char *col_name, const char *colhdr)
Definition at line 164 of file ui-out.h.
typedef void(text_ftype)(struct ui_out *uiout, const char *string)
Definition at line 191 of file ui-out.h.
typedef void(ui_out_begin_ftype)(struct ui_out *uiout, enum ui_out_type type, int level, const char *id)
Definition at line 169 of file ui-out.h.
typedef void(ui_out_end_ftype)(struct ui_out *uiout, enum ui_out_type type, int level)
Definition at line 172 of file ui-out.h.
typedef void() typedef void(wrap_hint_ftype)(struct ui_out *uiout, char *identstring)
Definition at line 196 of file ui-out.h.
Enumeration Type Documentation
enum ui_align
Enumerator:
ui_left
ui_center
ui_right
ui_noalign
Definition at line 38 of file ui-out.h.
enum ui_flags
Enumerator:
ui_from_tty
ui_source_list
Definition at line 47 of file ui-out.h.
enum ui_out_type
Enumerator:
ui_out_type_tuple
ui_out_type_list
Definition at line 59 of file ui-out.h.
Function Documentation
struct cleanup* make_cleanup_ui_out_list_begin_end (struct ui_out * uiout, const char * id) [read]
Definition at line 461 of file ui-out.c.
References make_cleanup_ui_out_end(), ui_out_begin(), and ui_out_type_list.
Referenced by do_assembly_only(), do_mixed_source_and_assembly(), list_args_or_locals(), list_available_thread_groups(), mi_cmd_data_list_changed_registers(), mi_cmd_data_list_register_names(), mi_cmd_data_list_register_values(), mi_cmd_data_read_memory(), mi_cmd_data_read_memory_bytes(), mi_cmd_list_features(), mi_cmd_list_target_features(), mi_cmd_list_thread_groups(), mi_cmd_stack_list_args(), mi_cmd_stack_list_frames(), mi_cmd_symbol_list_lines(), mi_cmd_trace_frame_collected(), mi_cmd_var_list_children(), mi_cmd_var_update(), mi_on_normal_stop(), output_cores(), output_thread_groups(), print_frame(), print_one_inferior(), print_solib_event(), print_thread_info(), py_mi_print_variables(), py_print_args(), py_print_frame(), py_print_locals(), and varobj_update_one().
struct cleanup* make_cleanup_ui_out_table_begin_end (struct ui_out * ui_out, int nr_cols, int nr_rows, const char * tblid) [read]
Definition at line 371 of file ui-out.c.
References do_cleanup_table_end(), make_cleanup(), and ui_out_table_begin().
Referenced by auto_load_info_scripts(), breakpoint_1(), darwin_debug_regions_recurse(), info_auto_load_libthread_db(), info_osdata_command(), info_probes_for_ops(), info_sharedlibrary_command(), info_spu_dma_cmdlist(), info_spu_mailbox_list(), info_static_tracepoint_markers_command(), maintenance_info_bfds(), print_ada_task_info(), print_inferior(), print_program_space(), print_thread_info(), skip_info(), and tvariables_info_1().
struct cleanup* make_cleanup_ui_out_tuple_begin_end (struct ui_out * uiout, const char * id) [read]
Definition at line 453 of file ui-out.c.
References make_cleanup_ui_out_end(), ui_out_begin(), and ui_out_type_tuple.
Referenced by cmd_show_list(), darwin_debug_regions_recurse(), do_captured_list_thread_ids(), do_mixed_source_and_assembly(), dump_insns(), enumerate_locals(), info_auto_load_cmd(), info_auto_load_libthread_db(), info_osdata_command(), info_probes_for_ops(), info_sharedlibrary_command(), info_spu_dma_cmdlist(), info_spu_dma_command(), info_spu_event_command(), info_spu_mailbox_command(), info_spu_mailbox_list(), info_spu_proxydma_command(), info_spu_signal_command(), list_arg_or_local(), list_available_thread_groups(), list_cp_abis(), mi_cmd_data_read_memory(), mi_cmd_data_read_memory_bytes(), mi_cmd_stack_list_args(), mi_cmd_symbol_list_lines(), mi_cmd_trace_frame_collected(), mi_cmd_var_list_children(), mi_cmd_var_update(), mi_load_progress(), output_register(), print_ada_task_info(), print_frame(), print_frame_arg(), print_frame_info(), print_inferior(), print_it_watchpoint(), print_mention_masked_watchpoint(), print_mention_watchpoint(), print_one_bfd(), print_one_breakpoint(), print_one_breakpoint_location(), print_one_inferior(), print_one_static_tracepoint_marker(), print_program_space(), print_script(), print_thread_info(), print_variable_or_computed(), py_print_frame(), py_print_single_arg(), record_btrace_call_history(), record_btrace_call_history_range(), record_btrace_insn_history(), record_btrace_insn_history_range(), show_remote_cmd(), skip_info(), tvariables_info_1(), and varobj_update_one().
void ui_out_begin (struct ui_out * uiout, enum ui_out_type level_type, const char * id)
Definition at line 379 of file ui-out.c.
References _, internal_error(), push_level(), uo_begin(), and verify_field().
Referenced by make_cleanup_ui_out_list_begin_end(), make_cleanup_ui_out_tuple_begin_end(), mi_cmd_file_list_exec_source_files(), and print_partial_file_name().
struct cleanup* ui_out_begin_cleanup_end (struct ui_out * uiout, enum ui_out_type level_type, const char * id) [read]
int ui_out_clear_flags (struct ui_out * uiout, int mask)
Definition at line 631 of file ui-out.c.
References ui_out::flags.
void* ui_out_data (struct ui_out * uiout)
Definition at line 1068 of file ui-out.c.
References ui_out::data.
Referenced by ATTRIBUTE_PRINTF(), cli_begin(), cli_end(), cli_field_int(), cli_field_skip(), cli_field_string(), cli_flush(), cli_out_set_stream(), cli_redirect(), cli_spaces(), cli_table_begin(), cli_table_body(), cli_table_end(), cli_table_header(), cli_text(), cli_wrap_hint(), field_separator(), mi_begin(), mi_close(), mi_end(), mi_field_fmt(), mi_field_int(), mi_field_string(), mi_flush(), mi_open(), mi_out_buffered(), mi_out_put(), mi_out_rewind(), mi_redirect(), mi_table_body(), mi_table_end(), mi_table_header(), mi_version(), out_field_fmt(), tui_field_fmt(), tui_field_int(), tui_field_string(), and tui_text().
void ui_out_destroy (struct ui_out * uiout)
Definition at line 1126 of file ui-out.c.
References clear_table(), uo_data_destroy(), VEC_free, VEC_iterate, and xfree().
void ui_out_end (struct ui_out * uiout, enum ui_out_type type)
Definition at line 417 of file ui-out.c.
References pop_level(), and uo_end().
Referenced by do_cleanup_end(), mi_cmd_file_list_exec_source_files(), and print_partial_file_name().
void ui_out_field_core_addr (struct ui_out * uiout, const char * fldname, struct gdbarch * gdbarch, CORE_ADDR address)
Definition at line 501 of file ui-out.c.
References print_core_address(), and ui_out_field_string().
Referenced by darwin_debug_regions_recurse(), dump_insns(), info_probes_for_ops(), info_sharedlibrary_command(), mi_cmd_data_read_memory(), mi_cmd_data_read_memory_bytes(), mi_cmd_symbol_list_lines(), mi_cmd_trace_frame_collected(), mi_memory_changed(), print_frame(), print_frame_info(), print_one_breakpoint_location(), print_one_detail_masked_watchpoint(), print_one_exception(), print_one_exception_catchpoint(), print_one_static_tracepoint_marker(), and py_print_frame().
void ui_out_field_fmt (struct ui_out * uiout, const char * fldname, const char * format, ...)
void ui_out_field_fmt_int (struct ui_out * uiout, int width, enum ui_align align, const char * fldname, int value)
Definition at line 483 of file ui-out.c.
References uo_field_int(), and verify_field().
Referenced by print_frame(), print_frame_info(), and py_print_frame().
void ui_out_field_int (struct ui_out * uiout, const char * fldname, int value)
Definition at line 469 of file ui-out.c.
References uo_field_int(), and verify_field().
Referenced by bkpt_print_it(), btrace_func_history_src_line(), darwin_debug_regions_recurse(), do_captured_list_thread_ids(), do_captured_thread_select(), dump_insns(), info_spu_dma_cmdlist(), info_spu_signal_command(), list_arg_or_local(), mi_cmd_data_list_changed_registers(), mi_cmd_data_read_memory(), mi_cmd_file_list_exec_source_file(), mi_cmd_stack_info_depth(), mi_cmd_stack_list_args(), mi_cmd_symbol_list_lines(), mi_cmd_trace_frame_collected(), mi_cmd_var_create(), mi_cmd_var_delete(), mi_cmd_var_info_num_children(), mi_cmd_var_list_children(), mi_load_progress(), mi_on_normal_stop(), output_register(), print_ada_task_info(), print_breakpoint_location(), print_frame(), print_inferior(), print_it_catch_exec(), print_it_catch_fork(), print_it_catch_solib(), print_it_catch_syscall(), print_it_catch_vfork(), print_it_exception(), print_it_exception_catchpoint(), print_it_ranged_breakpoint(), print_mention_exception(), print_mention_exception_catchpoint(), print_mention_masked_watchpoint(), print_mention_watchpoint(), print_one_bfd(), print_one_breakpoint_location(), print_one_catch_fork(), print_one_catch_vfork(), print_one_inferior(), print_one_static_tracepoint_marker(), print_program_space(), print_source_lines_base(), print_thread_info(), print_varobj(), py_print_frame(), py_print_single_arg(), skip_info(), tfind_1(), trace_status_mi(), update_static_tracepoint(), varobj_update_one(), and watchpoint_check().
void void ui_out_field_skip (struct ui_out * uiout, const char * fldname)
Definition at line 530 of file ui-out.c.
References uo_field_skip(), and verify_field().
Referenced by info_sharedlibrary_command(), info_spu_dma_cmdlist(), mi_cmd_trace_frame_collected(), print_ada_task_info(), print_inferior(), print_one_breakpoint_location(), print_one_catch_exec(), print_one_catch_fork(), print_one_catch_solib(), print_one_catch_syscall(), print_one_catch_vfork(), print_one_ranged_breakpoint(), print_one_static_tracepoint_marker(), print_program_space(), print_thread_info(), print_ui_out_info(), py_print_frame(), signal_catchpoint_print_one(), and ui_out_field_stream().
void ui_out_field_stream (struct ui_out * uiout, const char * fldname, struct ui_file * stream)
Definition at line 511 of file ui-out.c.
References do_cleanups(), make_cleanup(), ui_file_rewind(), ui_file_xstrdup(), ui_out_field_skip(), ui_out_field_string(), and xfree().
Referenced by do_show_command(), dump_insns(), list_arg_or_local(), mi_cmd_data_evaluate_expression(), mi_cmd_data_read_memory(), output_register(), print_breakpoint_location(), print_frame(), print_frame_arg(), print_it_watchpoint(), print_one_detail_ranged_breakpoint(), print_return_value(), print_variable_or_computed(), py_print_single_arg(), py_print_type(), and py_print_value().
void ui_out_field_string (struct ui_out * uiout, const char * fldname, const char * string)
Definition at line 543 of file ui-out.c.
References uo_field_string(), and verify_field().
Referenced by bkpt_print_it(), btrace_func_history(), btrace_func_history_src_line(), cmd_show_list(), darwin_debug_regions_recurse(), default_collect_info(), dump_insns(), enumerate_locals(), info_auto_load_cmd(), info_auto_load_libthread_db(), info_osdata_command(), info_probes_for_ops(), info_sharedlibrary_command(), info_spu_dma_cmdlist(), list_available_thread_groups(), list_cp_abis(), mi_cmd_data_list_register_names(), mi_cmd_data_read_memory(), mi_cmd_data_read_memory_bytes(), mi_cmd_env_dir(), mi_cmd_env_path(), mi_cmd_env_pwd(), mi_cmd_file_list_exec_source_file(), mi_cmd_file_list_exec_source_files(), mi_cmd_inferior_tty_show(), mi_cmd_list_features(), mi_cmd_list_target_features(), mi_cmd_trace_frame_collected(), mi_cmd_var_assign(), mi_cmd_var_evaluate_expression(), mi_cmd_var_info_expression(), mi_cmd_var_info_path_expression(), mi_cmd_var_info_type(), mi_cmd_var_list_children(), mi_cmd_var_set_format(), mi_cmd_var_show_attributes(), mi_cmd_var_show_format(), mi_command_param_changed(), mi_load_progress(), mi_memory_changed(), mi_on_normal_stop(), mi_tsv_modified(), momentary_bkpt_print_it(), output_cores(), output_thread_groups(), print_ada_task_info(), print_breakpoint_location(), print_command_lines(), print_end_stepping_range_reason(), print_exited_reason(), print_frame(), print_frame_info(), print_inferior(), print_it_catch_exec(), print_it_catch_fork(), print_it_catch_solib(), print_it_catch_syscall(), print_it_catch_vfork(), print_it_exception(), print_it_exception_catchpoint(), print_it_masked_watchpoint(), print_it_ranged_breakpoint(), print_it_watchpoint(), print_mention_masked_watchpoint(), print_mention_watchpoint(), print_one_bfd(), print_one_breakpoint_location(), print_one_catch_exec(), print_one_catch_fork(), print_one_catch_solib(), print_one_catch_syscall(), print_one_catch_vfork(), print_one_detail_exception_catchpoint(), print_one_exception(), print_one_exception_catchpoint(), print_one_inferior(), print_one_static_tracepoint_marker(), print_partial_file_name(), print_program_space(), print_return_value(), print_script(), print_signal_exited_reason(), print_signal_received_reason(), print_solib_event(), print_source_lines_base(), print_thread_info(), print_ui_out_info(), print_variable_or_computed(), print_varobj(), py_print_frame(), py_print_single_arg(), run_command_1(), show_cp_abi_cmd(), show_remote_cmd(), signal_catchpoint_print_one(), skip_info(), tfind_1(), trace_status_mi(), tracepoint_print_one_detail(), tvariables_info_1(), ui_out_field_core_addr(), ui_out_field_stream(), update_static_tracepoint(), varobj_update_one(), and watchpoint_check().
void ui_out_flush (struct ui_out * uiout)
Definition at line 608 of file ui-out.c.
References uo_flush().
Referenced by interp_set(), and run_command_1().
int ui_out_get_verblvl (struct ui_out * uiout)
Definition at line 650 of file ui-out.c.
Referenced by ATTRIBUTE_PRINTF().
int ui_out_is_mi_like_p (struct ui_out * uiout)
Definition at line 657 of file ui-out.c.
References ui_out::impl, and ui_out_impl::is_mi_like_p.
Referenced by bkpt_print_it(), bkpt_print_mention(), cmd_show_list(), darwin_debug_regions_recurse(), decode_line_full(), do_show_command(), enumerate_args(), enumerate_locals(), fputs_maybe_filtered(), handle_redirections(), info_osdata_command(), info_sharedlibrary_command(), info_spu_dma_cmdlist(), info_spu_dma_command(), info_spu_event_command(), info_spu_mailbox_list(), info_spu_proxydma_command(), info_spu_signal_command(), mention(), mi_execute_command(), momentary_bkpt_print_it(), output_thread_groups(), print_ada_task_info(), print_breakpoint_location(), print_end_stepping_range_reason(), print_exited_reason(), print_frame(), print_frame_arg(), print_frame_info(), print_it_catch_exec(), print_it_catch_fork(), print_it_catch_solib(), print_it_catch_syscall(), print_it_catch_vfork(), print_it_exception(), print_it_exception_catchpoint(), print_it_masked_watchpoint(), print_it_ranged_breakpoint(), print_it_watchpoint(), print_mention_ranged_breakpoint(), print_one_breakpoint_location(), print_one_catch_exec(), print_one_catch_fork(), print_one_catch_solib(), print_one_catch_syscall(), print_one_catch_vfork(), print_one_exception_catchpoint(), print_one_static_tracepoint_marker(), print_signal_exited_reason(), print_signal_received_reason(), print_solib_event(), print_source_lines_base(), print_stack_frame(), print_thread_info(), print_transfer_performance(), py_print_args(), py_print_frame(), py_print_single_arg(), py_print_value(), read_frame_arg(), restore_selected_frame(), signal_catchpoint_print_one(), tfind_1(), tracepoint_print_mention(), tvariables_info_1(), update_static_tracepoint(), and watchpoint_check().
void ui_out_message (struct ui_out * uiout, int verbosity, const char * format, ...)
struct ui_out* ui_out_new (struct ui_out_impl * impl, void * data, int flags) [read]
Definition at line 1098 of file ui-out.c.
References ui_out::data, ui_out_level::field_count, ui_out::flags, flags, ui_out::impl, ui_out::level, ui_out_level::type, ui_out_type_tuple, VEC_safe_push, and XMALLOC.
Referenced by cli_out_new(), mi_out_new(), and tui_out_new().
int ui_out_query_field (struct ui_out * uiout, int colno, int * width, int * alignment, char ** col_name)
Definition at line 1075 of file ui-out.c.
References ui_out_hdr::alignment, ui_out_hdr::col_name, ui_out_hdr::colno, ui_out_hdr::next, and ui_out_hdr::width.
Referenced by wrap_indent_at_field().
int ui_out_redirect (struct ui_out * uiout, struct ui_file * outstream)
Definition at line 614 of file ui-out.c.
References uo_redirect().
Referenced by bppy_get_commands(), do_ui_out_redirect_pop(), execute_command_to_string(), handle_redirections(), mi_breakpoint_created(), mi_breakpoint_modified(), mi_command_param_changed(), mi_memory_changed(), mi_tsv_modified(), pop_output_files(), save_breakpoints(), and set_logging_redirect().
int ui_out_set_flags (struct ui_out * uiout, int mask)
Definition at line 621 of file ui-out.c.
References ui_out::flags.
void ui_out_spaces (struct ui_out * uiout, int numspaces)
Definition at line 578 of file ui-out.c.
References uo_spaces().
Referenced by cli_field_string(), enumerate_locals(), print_command_lines(), print_one_breakpoint_location(), print_one_catch_fork(), print_one_catch_vfork(), print_one_static_tracepoint_marker(), py_print_frame(), and run_command_1().
void ui_out_table_body (struct ui_out * uiout)
Definition at line 311 of file ui-out.c.
References _, internal_error(), and uo_table_body().
Referenced by auto_load_info_scripts(), breakpoint_1(), darwin_debug_regions_recurse(), info_auto_load_libthread_db(), info_osdata_command(), info_probes_for_ops(), info_sharedlibrary_command(), info_spu_dma_cmdlist(), info_spu_mailbox_list(), info_static_tracepoint_markers_command(), maintenance_info_bfds(), print_ada_task_info(), print_inferior(), print_program_space(), print_thread_info(), skip_info(), and tvariables_info_1().
void ui_out_table_header (struct ui_out * uiout, int width, enum ui_align align, const char * col_name, const char * colhdr)
Definition at line 348 of file ui-out.c.
References _, append_header_to_list(), internal_error(), and uo_table_header().
Referenced by auto_load_info_scripts(), breakpoint_1(), darwin_debug_regions_recurse(), gen_ui_out_table_header_info(), info_auto_load_libthread_db(), info_osdata_command(), info_probes_for_ops(), info_sharedlibrary_command(), info_spu_dma_cmdlist(), info_spu_mailbox_list(), info_static_tracepoint_markers_command(), maintenance_info_bfds(), print_ada_task_info(), print_inferior(), print_program_space(), print_thread_info(), skip_info(), and tvariables_info_1().
int ui_out_test_flags (struct ui_out * uiout, int mask)
Definition at line 641 of file ui-out.c.
References ui_out::flags.
Referenced by print_source_lines_base().
void ui_out_text (struct ui_out * uiout, const char * string)
Definition at line 584 of file ui-out.c.
References uo_text().
Referenced by auto_load_info_scripts(), bkpt_print_it(), btrace_func_history(), btrace_func_history_insn_range(), btrace_func_history_src_line(), btrace_insn_history(), cmd_show_list(), darwin_debug_regions_recurse(), default_collect_info(), do_captured_thread_select(), do_mixed_source_and_assembly(), dump_insns(), enumerate_args(), enumerate_locals(), generic_load(), inferior_command(), info_auto_load_cmd(), info_auto_load_libthread_db(), info_osdata_command(), info_probes_for_ops(), info_sharedlibrary_command(), interp_set(), list_cp_abis(), output_thread_groups(), print_ada_task_info(), print_breakpoint_location(), print_command_lines(), print_exited_reason(), print_frame(), print_frame_arg(), print_frame_args(), print_frame_info(), print_inferior(), print_it_catch_exec(), print_it_catch_fork(), print_it_catch_solib(), print_it_catch_syscall(), print_it_catch_vfork(), print_it_exception(), print_it_exception_catchpoint(), print_it_masked_watchpoint(), print_it_ranged_breakpoint(), print_it_watchpoint(), print_mention_exception(), print_mention_exception_catchpoint(), print_mention_masked_watchpoint(), print_mention_watchpoint(), print_no_history_reason(), print_one_bfd(), print_one_breakpoint_location(), print_one_catch_exec(), print_one_catch_fork(), print_one_catch_syscall(), print_one_catch_vfork(), print_one_detail_exception_catchpoint(), print_one_detail_masked_watchpoint(), print_one_detail_ranged_breakpoint(), print_one_static_tracepoint_marker(), print_program_space(), print_return_value(), print_script(), print_signal_exited_reason(), print_signal_received_reason(), print_solib_event(), print_source_lines_base(), print_thread_info(), print_transfer_performance(), py_print_args(), py_print_frame(), py_print_single_arg(), run_command_1(), show_cp_abi_cmd(), show_remote_cmd(), signal_catchpoint_print_one(), skip_info(), tracepoint_print_one_detail(), tvariables_info_1(), update_static_tracepoint(), and watchpoint_check().
void void ui_out_wrap_hint (struct ui_out * uiout, char * identstring)
Definition at line 602 of file ui-out.c.
References uo_wrap_hint().
Referenced by enumerate_args(), print_breakpoint_location(), print_frame(), print_frame_args(), print_one_static_tracepoint_marker(), and py_print_frame().
void uo_field_string (struct ui_out * uiout, int fldno, int width, enum ui_align align, const char * fldname, const char * string)
Definition at line 856 of file ui-out.c.
References ui_out_impl::field_string, and ui_out::impl.
Referenced by cli_field_int(), cli_field_skip(), cli_table_header(), and ui_out_field_string().
Variable Documentation
struct ui_out* current_uiout
Definition at line 235 of file ui-out.c.
Referenced by add_vsyscall_page(), auto_load_info_scripts(), backtrace_command_1(), bkpt_print_it(), bkpt_print_mention(), bppy_get_commands(), breakpoint_1(), breakpoint_notify(), catch_errors(), catch_exceptions_with_msg(), cmd_show_list(), darwin_debug_regions_recurse(), default_collect_info(), do_gdb_disassembly(), do_show_command(), execute_command_to_string(), field_separator(), gen_ui_out_table_header_info(), generic_load(), get_current_frame(), handle_redirections(), inferior_command(), info_auto_load_cmd(), info_auto_load_libthread_db(), info_inferiors_command(), info_osdata_command(), info_probes_for_ops(), info_sharedlibrary_command(), info_spu_dma_cmdlist(), info_spu_dma_command(), info_spu_event_command(), info_spu_mailbox_command(), info_spu_mailbox_list(), info_spu_proxydma_command(), info_spu_signal_command(), info_static_tracepoint_markers_command(), info_tasks_command(), info_threads_command(), interp_set(), list_arg_or_local(), list_args_or_locals(), list_available_thread_groups(), list_cp_abis(), load_progress(), maintenance_info_bfds(), maintenance_info_program_spaces_command(), mention(), mi_cmd_ada_task_info(), mi_cmd_add_inferior(), mi_cmd_data_evaluate_expression(), mi_cmd_data_list_changed_registers(), mi_cmd_data_list_register_names(), mi_cmd_data_list_register_values(), mi_cmd_data_read_memory(), mi_cmd_data_read_memory_bytes(), mi_cmd_disassemble(), mi_cmd_env_dir(), mi_cmd_env_path(), mi_cmd_env_pwd(), mi_cmd_file_list_exec_source_file(), mi_cmd_file_list_exec_source_files(), mi_cmd_gdb_exit(), mi_cmd_inferior_tty_show(), mi_cmd_list_features(), mi_cmd_list_target_features(), mi_cmd_list_thread_groups(), mi_cmd_stack_info_depth(), mi_cmd_stack_list_args(), mi_cmd_stack_list_frames(), mi_cmd_stack_list_locals(), mi_cmd_stack_list_variables(), mi_cmd_symbol_list_lines(), mi_cmd_thread_info(), mi_cmd_thread_list_ids(), mi_cmd_thread_select(), mi_cmd_trace_frame_collected(), mi_cmd_var_assign(), mi_cmd_var_create(), mi_cmd_var_delete(), mi_cmd_var_evaluate_expression(), mi_cmd_var_info_expression(), mi_cmd_var_info_num_children(), mi_cmd_var_info_path_expression(), mi_cmd_var_info_type(), mi_cmd_var_list_children(), mi_cmd_var_set_format(), mi_cmd_var_show_attributes(), mi_cmd_var_show_format(), mi_cmd_var_update(), mi_execute_command(), mi_load_progress(), mi_on_normal_stop(), momentary_bkpt_print_it(), output_register(), pop_output_files(), print_breakpoint_location(), print_disassembly(), print_end_stepping_range_reason(), print_exited_reason(), print_frame(), print_frame_arg(), print_frame_args(), print_frame_info(), print_it_catch_exec(), print_it_catch_fork(), print_it_catch_solib(), print_it_catch_syscall(), print_it_catch_vfork(), print_it_exception(), print_it_exception_catchpoint(), print_it_masked_watchpoint(), print_it_ranged_breakpoint(), print_it_watchpoint(), print_mention_exception(), print_mention_exception_catchpoint(), print_mention_masked_watchpoint(), print_mention_ranged_breakpoint(), print_mention_watchpoint(), print_no_history_reason(), print_one_breakpoint(), print_one_breakpoint_location(), print_one_catch_exec(), print_one_catch_fork(), print_one_catch_solib(), print_one_catch_syscall(), print_one_catch_vfork(), print_one_exception(), print_one_exception_catchpoint(), print_one_inferior(), print_one_ranged_breakpoint(), print_one_static_tracepoint_marker(), print_partial_file_name(), print_return_value(), print_script(), print_signal_exited_reason(), print_signal_received_reason(), print_solib_event(), print_source_lines_base(), print_stack_frame(), print_transfer_performance(), print_ui_out_info(), print_variable_or_computed(), print_varobj(), read_frame_arg(), record_btrace_call_history(), record_btrace_call_history_range(), record_btrace_insn_history(), record_btrace_insn_history_range(), remote_fileio_request(), restore_selected_frame(), run_command_1(), safe_execute_command(), save_breakpoints(), set_logging_redirect(), show_cp_abi_cmd(), show_remote_cmd(), show_user_1(), signal_catchpoint_print_one(), skip_info(), task_command(), tfind_1(), thread_command(), trace_status_mi(), tracepoint_print_mention(), tracepoints_info(), tui_setup_io(), tvariables_info_1(), update_static_tracepoint(), varobj_update_one(), watchpoint_check(), and watchpoints_info().