GDB (xrefs): /home/stan/gdb/src/gdb/ui-out.c File Reference
/home/stan/gdb/src/gdb/ui-out.c File Reference
#include "defs.h"
#include "gdb_string.h"
#include "expression.h"
#include "language.h"
#include "ui-out.h"
#include "gdb_assert.h"
Classes
struct ui_out_hdr
struct ui_out_level
struct ui_out_table
struct ui_out
struct ui_out_end_cleanup_data
Typedefs
typedef struct ui_out_level * ui_out_level_p
Enumerations
enum { MAX_UI_OUT_LEVELS = 8 }
Functions
DEF_VEC_P (ui_out_level_p)
static struct ui_out_level * current_level (struct ui_out *uiout)
static int push_level (struct ui_out *uiout, enum ui_out_type type, const char *id)
static int pop_level (struct ui_out *uiout, enum ui_out_type type)
static void default_table_begin (struct ui_out *uiout, int nbrofcols, int nr_rows, const char *tblid)
static void default_table_body (struct ui_out *uiout)
static void default_table_end (struct ui_out *uiout)
static void default_table_header (struct ui_out *uiout, int width, enum ui_align alig, const char *col_name, const char *colhdr)
static void default_begin (struct ui_out *uiout, enum ui_out_type type, int level, const char *id)
static void default_end (struct ui_out *uiout, enum ui_out_type type, int level)
static void default_field_int (struct ui_out *uiout, int fldno, int width, enum ui_align alig, const char *fldname, int value)
static void default_field_skip (struct ui_out *uiout, int fldno, int width, enum ui_align alig, const char *fldname)
static void default_field_string (struct ui_out *uiout, int fldno, int width, enum ui_align align, const char *fldname, const char *string)
static void default_field_fmt (struct ui_out *uiout, int fldno, int width, enum ui_align align, const char *fldname, const char *format, va_list args) ATTRIBUTE_PRINTF(6
static void static void default_spaces (struct ui_out *uiout, int numspaces)
static void default_text (struct ui_out *uiout, const char *string)
static void default_message (struct ui_out *uiout, int verbosity, const char *format, va_list args) ATTRIBUTE_PRINTF(3
static void static void default_wrap_hint (struct ui_out *uiout, char *identstring)
static void default_flush (struct ui_out *uiout)
static void default_data_destroy (struct ui_out *uiout)
static void uo_table_begin (struct ui_out *uiout, int nbrofcols, int nr_rows, const char *tblid)
static void uo_table_body (struct ui_out *uiout)
static void uo_table_end (struct ui_out *uiout)
static void uo_table_header (struct ui_out *uiout, int width, enum ui_align align, const char *col_name, const char *colhdr)
static void uo_begin (struct ui_out *uiout, enum ui_out_type type, int level, const char *id)
static void uo_end (struct ui_out *uiout, enum ui_out_type type, int level)
static void uo_field_int (struct ui_out *uiout, int fldno, int width, enum ui_align align, const char *fldname, int value)
static void uo_field_skip (struct ui_out *uiout, int fldno, int width, enum ui_align align, const char *fldname)
static void uo_field_fmt (struct ui_out *uiout, int fldno, int width, enum ui_align align, const char *fldname, const char *format, va_list args) ATTRIBUTE_PRINTF(6
static void static void uo_spaces (struct ui_out *uiout, int numspaces)
static void uo_text (struct ui_out *uiout, const char *string)
static void uo_message (struct ui_out *uiout, int verbosity, const char *format, va_list args) ATTRIBUTE_PRINTF(3
static void static void uo_wrap_hint (struct ui_out *uiout, char *identstring)
static void uo_flush (struct ui_out *uiout)
static int uo_redirect (struct ui_out *uiout, struct ui_file *outstream)
static void uo_data_destroy (struct ui_out *uiout)
void _initialize_ui_out (void)
static void append_header_to_list (struct ui_out *uiout, int width, int alignment, const char *col_name, const char *colhdr)
static int get_next_header (struct ui_out *uiout, int *colno, int *width, int *alignment, char **colhdr)
static void clear_header_list (struct ui_out *uiout)
static void clear_table (struct ui_out *uiout)
static void verify_field (struct ui_out *uiout, int *fldno, int *width, int *align)
static void ui_out_table_begin (struct ui_out *uiout, int nbrofcols, int nr_rows, const char *tblid)
void ui_out_table_body (struct ui_out *uiout)
static void ui_out_table_end (struct ui_out *uiout)
void ui_out_table_header (struct ui_out *uiout, int width, enum ui_align alignment, const char *col_name, const char *colhdr)
static void do_cleanup_table_end (void *data)
struct cleanup * make_cleanup_ui_out_table_begin_end (struct ui_out *ui_out, int nr_cols, int nr_rows, const char *tblid)
void ui_out_begin (struct ui_out *uiout, enum ui_out_type type, const char *id)
void ui_out_end (struct ui_out *uiout, enum ui_out_type type)
static void do_cleanup_end (void *data)
static struct cleanup * make_cleanup_ui_out_end (struct ui_out *uiout, enum ui_out_type type)
struct cleanup * make_cleanup_ui_out_tuple_begin_end (struct ui_out *uiout, const char *id)
struct cleanup * make_cleanup_ui_out_list_begin_end (struct ui_out *uiout, const char *id)
void ui_out_field_int (struct ui_out *uiout, const char *fldname, int value)
void ui_out_field_fmt_int (struct ui_out *uiout, int input_width, enum ui_align input_align, const char *fldname, int value)
void ui_out_field_core_addr (struct ui_out *uiout, const char *fldname, struct gdbarch *gdbarch, CORE_ADDR address)
void ui_out_field_stream (struct ui_out *uiout, const char *fldname, struct ui_file *stream)
void ui_out_field_skip (struct ui_out *uiout, const char *fldname)
void ui_out_field_string (struct ui_out *uiout, const char *fldname, const char *string)
void ui_out_field_fmt (struct ui_out *uiout, const char *fldname, const char *format,...)
void ui_out_spaces (struct ui_out *uiout, int numspaces)
void ui_out_text (struct ui_out *uiout, const char *string)
void ui_out_message (struct ui_out *uiout, int verbosity, const char *format,...)
void ui_out_wrap_hint (struct ui_out *uiout, char *identstring)
void ui_out_flush (struct ui_out *uiout)
int ui_out_redirect (struct ui_out *uiout, struct ui_file *outstream)
int ui_out_set_flags (struct ui_out *uiout, int mask)
int ui_out_clear_flags (struct ui_out *uiout, int mask)
int ui_out_test_flags (struct ui_out *uiout, int mask)
int ui_out_get_verblvl (struct ui_out *uiout)
int ui_out_is_mi_like_p (struct ui_out *uiout)
void uo_field_string (struct ui_out *uiout, int fldno, int width, enum ui_align align, const char *fldname, const char *string)
void * ui_out_data (struct ui_out *uiout)
int ui_out_query_field (struct ui_out *uiout, int colno, int *width, int *alignment, char **col_name)
struct ui_out * ui_out_new (struct ui_out_impl *impl, void *data, int flags)
void ui_out_destroy (struct ui_out *uiout)
Variables
struct ui_out_impl default_ui_out_impl
struct ui_out def_uiout
struct ui_out * current_uiout = &def_uiout
Typedef Documentation
typedef struct ui_out_level* ui_out_level_p
Definition at line 57 of file ui-out.c.
Enumeration Type Documentation
anonymous enum
Enumerator:
MAX_UI_OUT_LEVELS
Definition at line 46 of file ui-out.c.
Function Documentation
void _initialize_ui_out (void)
static void append_header_to_list (struct ui_out * uiout, int width, int alignment, const char * col_name, const char * colhdr) [static]
Definition at line 959 of file ui-out.c.
References ui_out_hdr::alignment, ui_out_hdr::col_name, ui_out_hdr::colhdr, ui_out_hdr::colno, ui_out_hdr::next, ui_out_hdr::width, and XMALLOC.
Referenced by ui_out_table_header().
static void clear_header_list (struct ui_out * uiout) [static]
Definition at line 943 of file ui-out.c.
References gdb_assert, and xfree().
Referenced by clear_table(), and ui_out_table_begin().
static void clear_table (struct ui_out * uiout) [static]
Definition at line 808 of file ui-out.c.
References clear_header_list(), and xfree().
Referenced by ui_out_destroy(), and ui_out_table_end().
static struct ui_out_level* current_level (struct ui_out * uiout) [static, read]
Definition at line 120 of file ui-out.c.
References ui_out::level, and VEC_index.
Referenced by pop_level(), and verify_field().
DEF_VEC_P (ui_out_level_p)
static void default_begin (struct ui_out * uiout, enum ui_out_type type, int level, const char * id) [static]
Definition at line 689 of file ui-out.c.
static void default_data_destroy (struct ui_out * uiout) [static]
Definition at line 763 of file ui-out.c.
static void default_end (struct ui_out * uiout, enum ui_out_type type, int level) [static]
Definition at line 697 of file ui-out.c.
static void default_field_fmt (struct ui_out * uiout, int fldno, int width, enum ui_align align, const char * fldname, const char * format, va_list args) [static]
Definition at line 727 of file ui-out.c.
static void default_field_int (struct ui_out * uiout, int fldno, int width, enum ui_align alig, const char * fldname, int value) [static]
Definition at line 704 of file ui-out.c.
static void default_field_skip (struct ui_out * uiout, int fldno, int width, enum ui_align alig, const char * fldname) [static]
Definition at line 711 of file ui-out.c.
static void default_field_string (struct ui_out * uiout, int fldno, int width, enum ui_align align, const char * fldname, const char * string) [static]
Definition at line 717 of file ui-out.c.
static void default_flush (struct ui_out * uiout) [static]
Definition at line 758 of file ui-out.c.
static void default_message (struct ui_out * uiout, int verbosity, const char * format, va_list args) [static]
Definition at line 746 of file ui-out.c.
static void default_spaces (struct ui_out * uiout, int numspaces) [static]
Definition at line 736 of file ui-out.c.
static void default_table_begin (struct ui_out * uiout, int nbrofcols, int nr_rows, const char * tblid) [static]
Definition at line 665 of file ui-out.c.
static void default_table_body (struct ui_out * uiout) [static]
Definition at line 672 of file ui-out.c.
static void default_table_end (struct ui_out * uiout) [static]
Definition at line 677 of file ui-out.c.
static void default_table_header (struct ui_out * uiout, int width, enum ui_align alig, const char * col_name, const char * colhdr) [static]
Definition at line 682 of file ui-out.c.
static void default_text (struct ui_out * uiout, const char * string) [static]
Definition at line 741 of file ui-out.c.
static void default_wrap_hint (struct ui_out * uiout, char * identstring) [static]
Definition at line 753 of file ui-out.c.
static void do_cleanup_end (void * data) [static]
Definition at line 432 of file ui-out.c.
References ui_out_end_cleanup_data::type, ui_out_end(), ui_out_end_cleanup_data::uiout, and xfree().
Referenced by make_cleanup_ui_out_end().
static void do_cleanup_table_end (void * data) [static]
Definition at line 363 of file ui-out.c.
References ui_out::data, and ui_out_table_end().
Referenced by make_cleanup_ui_out_table_begin_end().
static int get_next_header (struct ui_out * uiout, int * colno, int * width, int * alignment, char ** colhdr) [static]
Definition at line 1004 of file ui-out.c.
Referenced by verify_field().
static struct cleanup* make_cleanup_ui_out_end (struct ui_out * uiout, enum ui_out_type type) [static, read]
Definition at line 441 of file ui-out.c.
References do_cleanup_end(), make_cleanup(), type, ui_out_end_cleanup_data::type, ui_out_end_cleanup_data::uiout, and XMALLOC.
Referenced by make_cleanup_ui_out_list_begin_end(), and make_cleanup_ui_out_tuple_begin_end().
struct cleanup* make_cleanup_ui_out_list_begin_end (struct ui_out * uiout, const char * id) [read]
Definition at line 461 of file ui-out.c.
References make_cleanup_ui_out_end(), ui_out_begin(), and ui_out_type_list.
Referenced by do_assembly_only(), do_mixed_source_and_assembly(), list_args_or_locals(), list_available_thread_groups(), mi_cmd_data_list_changed_registers(), mi_cmd_data_list_register_names(), mi_cmd_data_list_register_values(), mi_cmd_data_read_memory(), mi_cmd_data_read_memory_bytes(), mi_cmd_list_features(), mi_cmd_list_target_features(), mi_cmd_list_thread_groups(), mi_cmd_stack_list_args(), mi_cmd_stack_list_frames(), mi_cmd_symbol_list_lines(), mi_cmd_trace_frame_collected(), mi_cmd_var_list_children(), mi_cmd_var_update(), mi_on_normal_stop(), output_cores(), output_thread_groups(), print_frame(), print_one_inferior(), print_solib_event(), print_thread_info(), py_mi_print_variables(), py_print_args(), py_print_frame(), py_print_locals(), and varobj_update_one().
struct cleanup* make_cleanup_ui_out_table_begin_end (struct ui_out * ui_out, int nr_cols, int nr_rows, const char * tblid) [read]
Definition at line 371 of file ui-out.c.
References do_cleanup_table_end(), make_cleanup(), and ui_out_table_begin().
Referenced by auto_load_info_scripts(), breakpoint_1(), darwin_debug_regions_recurse(), info_auto_load_libthread_db(), info_osdata_command(), info_probes_for_ops(), info_sharedlibrary_command(), info_spu_dma_cmdlist(), info_spu_mailbox_list(), info_static_tracepoint_markers_command(), maintenance_info_bfds(), print_ada_task_info(), print_inferior(), print_program_space(), print_thread_info(), skip_info(), and tvariables_info_1().
struct cleanup* make_cleanup_ui_out_tuple_begin_end (struct ui_out * uiout, const char * id) [read]
Definition at line 453 of file ui-out.c.
References make_cleanup_ui_out_end(), ui_out_begin(), and ui_out_type_tuple.
Referenced by cmd_show_list(), darwin_debug_regions_recurse(), do_captured_list_thread_ids(), do_mixed_source_and_assembly(), dump_insns(), enumerate_locals(), info_auto_load_cmd(), info_auto_load_libthread_db(), info_osdata_command(), info_probes_for_ops(), info_sharedlibrary_command(), info_spu_dma_cmdlist(), info_spu_dma_command(), info_spu_event_command(), info_spu_mailbox_command(), info_spu_mailbox_list(), info_spu_proxydma_command(), info_spu_signal_command(), list_arg_or_local(), list_available_thread_groups(), list_cp_abis(), mi_cmd_data_read_memory(), mi_cmd_data_read_memory_bytes(), mi_cmd_stack_list_args(), mi_cmd_symbol_list_lines(), mi_cmd_trace_frame_collected(), mi_cmd_var_list_children(), mi_cmd_var_update(), mi_load_progress(), output_register(), print_ada_task_info(), print_frame(), print_frame_arg(), print_frame_info(), print_inferior(), print_it_watchpoint(), print_mention_masked_watchpoint(), print_mention_watchpoint(), print_one_bfd(), print_one_breakpoint(), print_one_breakpoint_location(), print_one_inferior(), print_one_static_tracepoint_marker(), print_program_space(), print_script(), print_thread_info(), print_variable_or_computed(), py_print_frame(), py_print_single_arg(), record_btrace_call_history(), record_btrace_call_history_range(), record_btrace_insn_history(), record_btrace_insn_history_range(), show_remote_cmd(), skip_info(), tvariables_info_1(), and varobj_update_one().
static int pop_level (struct ui_out * uiout, enum ui_out_type type) [static]
Definition at line 144 of file ui-out.c.
References current_level(), gdb_assert, ui_out::level, VEC_pop, and xfree().
Referenced by ui_out_end().
static int push_level (struct ui_out * uiout, enum ui_out_type type, const char * id) [static]
Definition at line 127 of file ui-out.c.
References ui_out_level::field_count, ui_out::level, ui_out_level::type, type, VEC_safe_push, and XMALLOC.
Referenced by ui_out_begin().
void ui_out_begin (struct ui_out * uiout, enum ui_out_type type, const char * id)
Definition at line 379 of file ui-out.c.
References _, internal_error(), push_level(), uo_begin(), and verify_field().
Referenced by make_cleanup_ui_out_list_begin_end(), make_cleanup_ui_out_tuple_begin_end(), mi_cmd_file_list_exec_source_files(), and print_partial_file_name().
int ui_out_clear_flags (struct ui_out * uiout, int mask)
Definition at line 631 of file ui-out.c.
References ui_out::flags.
void* ui_out_data (struct ui_out * uiout)
Definition at line 1068 of file ui-out.c.
References ui_out::data.
Referenced by ATTRIBUTE_PRINTF(), cli_begin(), cli_end(), cli_field_int(), cli_field_skip(), cli_field_string(), cli_flush(), cli_out_set_stream(), cli_redirect(), cli_spaces(), cli_table_begin(), cli_table_body(), cli_table_end(), cli_table_header(), cli_text(), cli_wrap_hint(), field_separator(), mi_begin(), mi_close(), mi_end(), mi_field_fmt(), mi_field_int(), mi_field_string(), mi_flush(), mi_open(), mi_out_buffered(), mi_out_put(), mi_out_rewind(), mi_redirect(), mi_table_body(), mi_table_end(), mi_table_header(), mi_version(), out_field_fmt(), tui_field_fmt(), tui_field_int(), tui_field_string(), and tui_text().
void ui_out_destroy (struct ui_out * uiout)
Definition at line 1126 of file ui-out.c.
References clear_table(), uo_data_destroy(), VEC_free, VEC_iterate, and xfree().
void ui_out_end (struct ui_out * uiout, enum ui_out_type type)
Definition at line 417 of file ui-out.c.
References pop_level(), and uo_end().
Referenced by do_cleanup_end(), mi_cmd_file_list_exec_source_files(), and print_partial_file_name().
void ui_out_field_core_addr (struct ui_out * uiout, const char * fldname, struct gdbarch * gdbarch, CORE_ADDR address)
Definition at line 501 of file ui-out.c.
References print_core_address(), and ui_out_field_string().
Referenced by darwin_debug_regions_recurse(), dump_insns(), info_probes_for_ops(), info_sharedlibrary_command(), mi_cmd_data_read_memory(), mi_cmd_data_read_memory_bytes(), mi_cmd_symbol_list_lines(), mi_cmd_trace_frame_collected(), mi_memory_changed(), print_frame(), print_frame_info(), print_one_breakpoint_location(), print_one_detail_masked_watchpoint(), print_one_exception(), print_one_exception_catchpoint(), print_one_static_tracepoint_marker(), and py_print_frame().
void ui_out_field_fmt (struct ui_out * uiout, const char * fldname, const char * format, ...)
Definition at line 558 of file ui-out.c.
References uo_field_fmt(), and verify_field().
Referenced by generic_load(), info_spu_dma_cmdlist(), info_spu_dma_command(), info_spu_event_command(), info_spu_mailbox_list(), info_spu_proxydma_command(), info_spu_signal_command(), list_available_thread_groups(), mi_cmd_add_inferior(), mi_memory_changed(), print_ada_task_info(), print_command_lines(), print_exited_reason(), print_one_breakpoint_location(), print_one_inferior(), print_one_static_tracepoint_marker(), print_return_value(), print_signal_received_reason(), print_transfer_performance(), and ui_out_field_uint().
void ui_out_field_fmt_int (struct ui_out * uiout, int input_width, enum ui_align input_align, const char * fldname, int value)
Definition at line 483 of file ui-out.c.
References uo_field_int(), and verify_field().
Referenced by print_frame(), print_frame_info(), and py_print_frame().
void ui_out_field_int (struct ui_out * uiout, const char * fldname, int value)
Definition at line 469 of file ui-out.c.
References uo_field_int(), and verify_field().
Referenced by bkpt_print_it(), btrace_func_history_src_line(), darwin_debug_regions_recurse(), do_captured_list_thread_ids(), do_captured_thread_select(), dump_insns(), info_spu_dma_cmdlist(), info_spu_signal_command(), list_arg_or_local(), mi_cmd_data_list_changed_registers(), mi_cmd_data_read_memory(), mi_cmd_file_list_exec_source_file(), mi_cmd_stack_info_depth(), mi_cmd_stack_list_args(), mi_cmd_symbol_list_lines(), mi_cmd_trace_frame_collected(), mi_cmd_var_create(), mi_cmd_var_delete(), mi_cmd_var_info_num_children(), mi_cmd_var_list_children(), mi_load_progress(), mi_on_normal_stop(), output_register(), print_ada_task_info(), print_breakpoint_location(), print_frame(), print_inferior(), print_it_catch_exec(), print_it_catch_fork(), print_it_catch_solib(), print_it_catch_syscall(), print_it_catch_vfork(), print_it_exception(), print_it_exception_catchpoint(), print_it_ranged_breakpoint(), print_mention_exception(), print_mention_exception_catchpoint(), print_mention_masked_watchpoint(), print_mention_watchpoint(), print_one_bfd(), print_one_breakpoint_location(), print_one_catch_fork(), print_one_catch_vfork(), print_one_inferior(), print_one_static_tracepoint_marker(), print_program_space(), print_source_lines_base(), print_thread_info(), print_varobj(), py_print_frame(), py_print_single_arg(), skip_info(), tfind_1(), trace_status_mi(), update_static_tracepoint(), varobj_update_one(), and watchpoint_check().
void ui_out_field_skip (struct ui_out * uiout, const char * fldname)
Definition at line 530 of file ui-out.c.
References uo_field_skip(), and verify_field().
Referenced by info_sharedlibrary_command(), info_spu_dma_cmdlist(), mi_cmd_trace_frame_collected(), print_ada_task_info(), print_inferior(), print_one_breakpoint_location(), print_one_catch_exec(), print_one_catch_fork(), print_one_catch_solib(), print_one_catch_syscall(), print_one_catch_vfork(), print_one_ranged_breakpoint(), print_one_static_tracepoint_marker(), print_program_space(), print_thread_info(), print_ui_out_info(), py_print_frame(), signal_catchpoint_print_one(), and ui_out_field_stream().
void ui_out_field_stream (struct ui_out * uiout, const char * fldname, struct ui_file * stream)
Definition at line 511 of file ui-out.c.
References do_cleanups(), make_cleanup(), ui_file_rewind(), ui_file_xstrdup(), ui_out_field_skip(), ui_out_field_string(), and xfree().
Referenced by do_show_command(), dump_insns(), list_arg_or_local(), mi_cmd_data_evaluate_expression(), mi_cmd_data_read_memory(), output_register(), print_breakpoint_location(), print_frame(), print_frame_arg(), print_it_watchpoint(), print_one_detail_ranged_breakpoint(), print_return_value(), print_variable_or_computed(), py_print_single_arg(), py_print_type(), and py_print_value().
void ui_out_field_string (struct ui_out * uiout, const char * fldname, const char * string)
Definition at line 543 of file ui-out.c.
References uo_field_string(), and verify_field().
Referenced by bkpt_print_it(), btrace_func_history(), btrace_func_history_src_line(), cmd_show_list(), darwin_debug_regions_recurse(), default_collect_info(), dump_insns(), enumerate_locals(), info_auto_load_cmd(), info_auto_load_libthread_db(), info_osdata_command(), info_probes_for_ops(), info_sharedlibrary_command(), info_spu_dma_cmdlist(), list_available_thread_groups(), list_cp_abis(), mi_cmd_data_list_register_names(), mi_cmd_data_read_memory(), mi_cmd_data_read_memory_bytes(), mi_cmd_env_dir(), mi_cmd_env_path(), mi_cmd_env_pwd(), mi_cmd_file_list_exec_source_file(), mi_cmd_file_list_exec_source_files(), mi_cmd_inferior_tty_show(), mi_cmd_list_features(), mi_cmd_list_target_features(), mi_cmd_trace_frame_collected(), mi_cmd_var_assign(), mi_cmd_var_evaluate_expression(), mi_cmd_var_info_expression(), mi_cmd_var_info_path_expression(), mi_cmd_var_info_type(), mi_cmd_var_list_children(), mi_cmd_var_set_format(), mi_cmd_var_show_attributes(), mi_cmd_var_show_format(), mi_command_param_changed(), mi_load_progress(), mi_memory_changed(), mi_on_normal_stop(), mi_tsv_modified(), momentary_bkpt_print_it(), output_cores(), output_thread_groups(), print_ada_task_info(), print_breakpoint_location(), print_command_lines(), print_end_stepping_range_reason(), print_exited_reason(), print_frame(), print_frame_info(), print_inferior(), print_it_catch_exec(), print_it_catch_fork(), print_it_catch_solib(), print_it_catch_syscall(), print_it_catch_vfork(), print_it_exception(), print_it_exception_catchpoint(), print_it_masked_watchpoint(), print_it_ranged_breakpoint(), print_it_watchpoint(), print_mention_masked_watchpoint(), print_mention_watchpoint(), print_one_bfd(), print_one_breakpoint_location(), print_one_catch_exec(), print_one_catch_fork(), print_one_catch_solib(), print_one_catch_syscall(), print_one_catch_vfork(), print_one_detail_exception_catchpoint(), print_one_exception(), print_one_exception_catchpoint(), print_one_inferior(), print_one_static_tracepoint_marker(), print_partial_file_name(), print_program_space(), print_return_value(), print_script(), print_signal_exited_reason(), print_signal_received_reason(), print_solib_event(), print_source_lines_base(), print_thread_info(), print_ui_out_info(), print_variable_or_computed(), print_varobj(), py_print_frame(), py_print_single_arg(), run_command_1(), show_cp_abi_cmd(), show_remote_cmd(), signal_catchpoint_print_one(), skip_info(), tfind_1(), trace_status_mi(), tracepoint_print_one_detail(), tvariables_info_1(), ui_out_field_core_addr(), ui_out_field_stream(), update_static_tracepoint(), varobj_update_one(), and watchpoint_check().
void ui_out_flush (struct ui_out * uiout)
Definition at line 608 of file ui-out.c.
References uo_flush().
Referenced by interp_set(), and run_command_1().
int ui_out_get_verblvl (struct ui_out * uiout)
Definition at line 650 of file ui-out.c.
Referenced by ATTRIBUTE_PRINTF().
int ui_out_is_mi_like_p (struct ui_out * uiout)
Definition at line 657 of file ui-out.c.
References ui_out::impl, and ui_out_impl::is_mi_like_p.
Referenced by bkpt_print_it(), bkpt_print_mention(), cmd_show_list(), darwin_debug_regions_recurse(), decode_line_full(), do_show_command(), enumerate_args(), enumerate_locals(), fputs_maybe_filtered(), handle_redirections(), info_osdata_command(), info_sharedlibrary_command(), info_spu_dma_cmdlist(), info_spu_dma_command(), info_spu_event_command(), info_spu_mailbox_list(), info_spu_proxydma_command(), info_spu_signal_command(), mention(), mi_execute_command(), momentary_bkpt_print_it(), output_thread_groups(), print_ada_task_info(), print_breakpoint_location(), print_end_stepping_range_reason(), print_exited_reason(), print_frame(), print_frame_arg(), print_frame_info(), print_it_catch_exec(), print_it_catch_fork(), print_it_catch_solib(), print_it_catch_syscall(), print_it_catch_vfork(), print_it_exception(), print_it_exception_catchpoint(), print_it_masked_watchpoint(), print_it_ranged_breakpoint(), print_it_watchpoint(), print_mention_ranged_breakpoint(), print_one_breakpoint_location(), print_one_catch_exec(), print_one_catch_fork(), print_one_catch_solib(), print_one_catch_syscall(), print_one_catch_vfork(), print_one_exception_catchpoint(), print_one_static_tracepoint_marker(), print_signal_exited_reason(), print_signal_received_reason(), print_solib_event(), print_source_lines_base(), print_stack_frame(), print_thread_info(), print_transfer_performance(), py_print_args(), py_print_frame(), py_print_single_arg(), py_print_value(), read_frame_arg(), restore_selected_frame(), signal_catchpoint_print_one(), tfind_1(), tracepoint_print_mention(), tvariables_info_1(), update_static_tracepoint(), and watchpoint_check().
void ui_out_message (struct ui_out * uiout, int verbosity, const char * format, ...)
Definition at line 591 of file ui-out.c.
References uo_message().
Referenced by auto_load_info_scripts(), breakpoint_1(), info_auto_load_libthread_db(), info_probes_for_ops(), info_sharedlibrary_command(), info_task(), load_progress(), print_ada_task_info(), print_inferior(), print_thread_info(), skip_info(), task_command(), tracepoints_info(), and watchpoints_info().
struct ui_out* ui_out_new (struct ui_out_impl * impl, void * data, int flags) [read]
Definition at line 1098 of file ui-out.c.
References ui_out::data, ui_out_level::field_count, ui_out::flags, flags, ui_out::impl, ui_out::level, ui_out_level::type, ui_out_type_tuple, VEC_safe_push, and XMALLOC.
Referenced by cli_out_new(), mi_out_new(), and tui_out_new().
int ui_out_query_field (struct ui_out * uiout, int colno, int * width, int * alignment, char ** col_name)
Definition at line 1075 of file ui-out.c.
References ui_out_hdr::alignment, ui_out_hdr::col_name, ui_out_hdr::colno, ui_out_hdr::next, and ui_out_hdr::width.
Referenced by wrap_indent_at_field().
int ui_out_redirect (struct ui_out * uiout, struct ui_file * outstream)
Definition at line 614 of file ui-out.c.
References uo_redirect().
Referenced by bppy_get_commands(), do_ui_out_redirect_pop(), execute_command_to_string(), handle_redirections(), mi_breakpoint_created(), mi_breakpoint_modified(), mi_command_param_changed(), mi_memory_changed(), mi_tsv_modified(), pop_output_files(), save_breakpoints(), and set_logging_redirect().
int ui_out_set_flags (struct ui_out * uiout, int mask)
Definition at line 621 of file ui-out.c.
References ui_out::flags.
void ui_out_spaces (struct ui_out * uiout, int numspaces)
Definition at line 578 of file ui-out.c.
References uo_spaces().
Referenced by cli_field_string(), enumerate_locals(), print_command_lines(), print_one_breakpoint_location(), print_one_catch_fork(), print_one_catch_vfork(), print_one_static_tracepoint_marker(), py_print_frame(), and run_command_1().
static void ui_out_table_begin (struct ui_out * uiout, int nbrofcols, int nr_rows, const char * tblid) [static]
Definition at line 288 of file ui-out.c.
References _, clear_header_list(), internal_error(), ui_out::level, and uo_table_begin().
Referenced by make_cleanup_ui_out_table_begin_end().
void ui_out_table_body (struct ui_out * uiout)
Definition at line 311 of file ui-out.c.
References _, internal_error(), and uo_table_body().
Referenced by auto_load_info_scripts(), breakpoint_1(), darwin_debug_regions_recurse(), info_auto_load_libthread_db(), info_osdata_command(), info_probes_for_ops(), info_sharedlibrary_command(), info_spu_dma_cmdlist(), info_spu_mailbox_list(), info_static_tracepoint_markers_command(), maintenance_info_bfds(), print_ada_task_info(), print_inferior(), print_program_space(), print_thread_info(), skip_info(), and tvariables_info_1().
static void ui_out_table_end (struct ui_out * uiout) [static]
Definition at line 333 of file ui-out.c.
References _, clear_table(), internal_error(), and uo_table_end().
Referenced by do_cleanup_table_end().
void ui_out_table_header (struct ui_out * uiout, int width, enum ui_align alignment, const char * col_name, const char * colhdr)
Definition at line 348 of file ui-out.c.
References _, append_header_to_list(), internal_error(), and uo_table_header().
Referenced by auto_load_info_scripts(), breakpoint_1(), darwin_debug_regions_recurse(), gen_ui_out_table_header_info(), info_auto_load_libthread_db(), info_osdata_command(), info_probes_for_ops(), info_sharedlibrary_command(), info_spu_dma_cmdlist(), info_spu_mailbox_list(), info_static_tracepoint_markers_command(), maintenance_info_bfds(), print_ada_task_info(), print_inferior(), print_program_space(), print_thread_info(), skip_info(), and tvariables_info_1().
int ui_out_test_flags (struct ui_out * uiout, int mask)
Definition at line 641 of file ui-out.c.
References ui_out::flags.
Referenced by print_source_lines_base().
void ui_out_text (struct ui_out * uiout, const char * string)
Definition at line 584 of file ui-out.c.
References uo_text().
Referenced by auto_load_info_scripts(), bkpt_print_it(), btrace_func_history(), btrace_func_history_insn_range(), btrace_func_history_src_line(), btrace_insn_history(), cmd_show_list(), darwin_debug_regions_recurse(), default_collect_info(), do_captured_thread_select(), do_mixed_source_and_assembly(), dump_insns(), enumerate_args(), enumerate_locals(), generic_load(), inferior_command(), info_auto_load_cmd(), info_auto_load_libthread_db(), info_osdata_command(), info_probes_for_ops(), info_sharedlibrary_command(), interp_set(), list_cp_abis(), output_thread_groups(), print_ada_task_info(), print_breakpoint_location(), print_command_lines(), print_exited_reason(), print_frame(), print_frame_arg(), print_frame_args(), print_frame_info(), print_inferior(), print_it_catch_exec(), print_it_catch_fork(), print_it_catch_solib(), print_it_catch_syscall(), print_it_catch_vfork(), print_it_exception(), print_it_exception_catchpoint(), print_it_masked_watchpoint(), print_it_ranged_breakpoint(), print_it_watchpoint(), print_mention_exception(), print_mention_exception_catchpoint(), print_mention_masked_watchpoint(), print_mention_watchpoint(), print_no_history_reason(), print_one_bfd(), print_one_breakpoint_location(), print_one_catch_exec(), print_one_catch_fork(), print_one_catch_syscall(), print_one_catch_vfork(), print_one_detail_exception_catchpoint(), print_one_detail_masked_watchpoint(), print_one_detail_ranged_breakpoint(), print_one_static_tracepoint_marker(), print_program_space(), print_return_value(), print_script(), print_signal_exited_reason(), print_signal_received_reason(), print_solib_event(), print_source_lines_base(), print_thread_info(), print_transfer_performance(), py_print_args(), py_print_frame(), py_print_single_arg(), run_command_1(), show_cp_abi_cmd(), show_remote_cmd(), signal_catchpoint_print_one(), skip_info(), tracepoint_print_one_detail(), tvariables_info_1(), update_static_tracepoint(), and watchpoint_check().
void ui_out_wrap_hint (struct ui_out * uiout, char * identstring)
Definition at line 602 of file ui-out.c.
References uo_wrap_hint().
Referenced by enumerate_args(), print_breakpoint_location(), print_frame(), print_frame_args(), print_one_static_tracepoint_marker(), and py_print_frame().
void uo_begin (struct ui_out * uiout, enum ui_out_type type, int level, const char * id) [static]
Definition at line 816 of file ui-out.c.
References ui_out_impl::begin, and ui_out::impl.
Referenced by ui_out_begin().
void uo_data_destroy (struct ui_out * uiout) [static]
Definition at line 930 of file ui-out.c.
References ui_out_impl::data_destroy, and ui_out::impl.
Referenced by ui_out_destroy().
void uo_end (struct ui_out * uiout, enum ui_out_type type, int level) [static]
Definition at line 827 of file ui-out.c.
References ui_out_impl::end, and ui_out::impl.
Referenced by ui_out_end().
void uo_field_fmt (struct ui_out * uiout, int fldno, int width, enum ui_align align, const char * fldname, const char * format, va_list args) [static]
Definition at line 867 of file ui-out.c.
References ui_out_impl::field_fmt, and ui_out::impl.
Referenced by ui_out_field_fmt().
void uo_field_int (struct ui_out * uiout, int fldno, int width, enum ui_align align, const char * fldname, int value) [static]
Definition at line 837 of file ui-out.c.
References ui_out_impl::field_int, and ui_out::impl.
Referenced by ui_out_field_fmt_int(), and ui_out_field_int().
void uo_field_skip (struct ui_out * uiout, int fldno, int width, enum ui_align align, const char * fldname) [static]
Definition at line 847 of file ui-out.c.
References ui_out_impl::field_skip, and ui_out::impl.
Referenced by ui_out_field_skip().
void uo_field_string (struct ui_out * uiout, int fldno, int width, enum ui_align align, const char * fldname, const char * string)
Definition at line 856 of file ui-out.c.
References ui_out_impl::field_string, and ui_out::impl.
Referenced by cli_field_int(), cli_field_skip(), cli_table_header(), and ui_out_field_string().
void uo_flush (struct ui_out * uiout) [static]
Definition at line 913 of file ui-out.c.
References ui_out_impl::flush, and ui_out::impl.
Referenced by ui_out_flush().
void uo_message (struct ui_out * uiout, int verbosity, const char * format, va_list args) [static]
Definition at line 895 of file ui-out.c.
References ui_out::impl, and ui_out_impl::message.
Referenced by ui_out_message().
int uo_redirect (struct ui_out * uiout, struct ui_file * outstream) [static]
Definition at line 921 of file ui-out.c.
References ui_out::impl, and ui_out_impl::redirect.
Referenced by ui_out_redirect().
void uo_spaces (struct ui_out * uiout, int numspaces) [static]
Definition at line 878 of file ui-out.c.
References ui_out::impl, and ui_out_impl::spaces.
Referenced by ui_out_spaces().
void uo_table_begin (struct ui_out * uiout, int nbrofcols, int nr_rows, const char * tblid) [static]
Definition at line 770 of file ui-out.c.
References ui_out::impl, and ui_out_impl::table_begin.
Referenced by ui_out_table_begin().
void uo_table_body (struct ui_out * uiout) [static]
Definition at line 780 of file ui-out.c.
References ui_out::impl, and ui_out_impl::table_body.
Referenced by ui_out_table_body().
void uo_table_end (struct ui_out * uiout) [static]
Definition at line 788 of file ui-out.c.
References ui_out::impl, and ui_out_impl::table_end.
Referenced by ui_out_table_end().
void uo_table_header (struct ui_out * uiout, int width, enum ui_align align, const char * col_name, const char * colhdr) [static]
Definition at line 796 of file ui-out.c.
References ui_out::impl, and ui_out_impl::table_header.
Referenced by ui_out_table_header().
void uo_text (struct ui_out * uiout, const char * string) [static]
Definition at line 886 of file ui-out.c.
References ui_out::impl, and ui_out_impl::text.
Referenced by ui_out_text().
void uo_wrap_hint (struct ui_out * uiout, char * identstring) [static]
Definition at line 905 of file ui-out.c.
References ui_out::impl, and ui_out_impl::wrap_hint.
Referenced by ui_out_wrap_hint().
static void verify_field (struct ui_out * uiout, int * fldno, int * width, int * align) [static]
Definition at line 1028 of file ui-out.c.
References _, current_level(), ui_out_level::field_count, get_next_header(), internal_error(), ui_out::level, and ui_noalign.
Referenced by ui_out_begin(), ui_out_field_fmt(), ui_out_field_fmt_int(), ui_out_field_int(), ui_out_field_skip(), and ui_out_field_string().
Variable Documentation
struct ui_out* current_uiout = &def_uiout
Definition at line 235 of file ui-out.c.
Referenced by add_vsyscall_page(), auto_load_info_scripts(), backtrace_command_1(), bkpt_print_it(), bkpt_print_mention(), bppy_get_commands(), breakpoint_1(), breakpoint_notify(), catch_errors(), catch_exceptions_with_msg(), cmd_show_list(), darwin_debug_regions_recurse(), default_collect_info(), do_gdb_disassembly(), do_show_command(), execute_command_to_string(), field_separator(), gen_ui_out_table_header_info(), generic_load(), get_current_frame(), handle_redirections(), inferior_command(), info_auto_load_cmd(), info_auto_load_libthread_db(), info_inferiors_command(), info_osdata_command(), info_probes_for_ops(), info_sharedlibrary_command(), info_spu_dma_cmdlist(), info_spu_dma_command(), info_spu_event_command(), info_spu_mailbox_command(), info_spu_mailbox_list(), info_spu_proxydma_command(), info_spu_signal_command(), info_static_tracepoint_markers_command(), info_tasks_command(), info_threads_command(), interp_set(), list_arg_or_local(), list_args_or_locals(), list_available_thread_groups(), list_cp_abis(), load_progress(), maintenance_info_bfds(), maintenance_info_program_spaces_command(), mention(), mi_cmd_ada_task_info(), mi_cmd_add_inferior(), mi_cmd_data_evaluate_expression(), mi_cmd_data_list_changed_registers(), mi_cmd_data_list_register_names(), mi_cmd_data_list_register_values(), mi_cmd_data_read_memory(), mi_cmd_data_read_memory_bytes(), mi_cmd_disassemble(), mi_cmd_env_dir(), mi_cmd_env_path(), mi_cmd_env_pwd(), mi_cmd_file_list_exec_source_file(), mi_cmd_file_list_exec_source_files(), mi_cmd_gdb_exit(), mi_cmd_inferior_tty_show(), mi_cmd_list_features(), mi_cmd_list_target_features(), mi_cmd_list_thread_groups(), mi_cmd_stack_info_depth(), mi_cmd_stack_list_args(), mi_cmd_stack_list_frames(), mi_cmd_stack_list_locals(), mi_cmd_stack_list_variables(), mi_cmd_symbol_list_lines(), mi_cmd_thread_info(), mi_cmd_thread_list_ids(), mi_cmd_thread_select(), mi_cmd_trace_frame_collected(), mi_cmd_var_assign(), mi_cmd_var_create(), mi_cmd_var_delete(), mi_cmd_var_evaluate_expression(), mi_cmd_var_info_expression(), mi_cmd_var_info_num_children(), mi_cmd_var_info_path_expression(), mi_cmd_var_info_type(), mi_cmd_var_list_children(), mi_cmd_var_set_format(), mi_cmd_var_show_attributes(), mi_cmd_var_show_format(), mi_cmd_var_update(), mi_execute_command(), mi_load_progress(), mi_on_normal_stop(), momentary_bkpt_print_it(), output_register(), pop_output_files(), print_breakpoint_location(), print_disassembly(), print_end_stepping_range_reason(), print_exited_reason(), print_frame(), print_frame_arg(), print_frame_args(), print_frame_info(), print_it_catch_exec(), print_it_catch_fork(), print_it_catch_solib(), print_it_catch_syscall(), print_it_catch_vfork(), print_it_exception(), print_it_exception_catchpoint(), print_it_masked_watchpoint(), print_it_ranged_breakpoint(), print_it_watchpoint(), print_mention_exception(), print_mention_exception_catchpoint(), print_mention_masked_watchpoint(), print_mention_ranged_breakpoint(), print_mention_watchpoint(), print_no_history_reason(), print_one_breakpoint(), print_one_breakpoint_location(), print_one_catch_exec(), print_one_catch_fork(), print_one_catch_solib(), print_one_catch_syscall(), print_one_catch_vfork(), print_one_exception(), print_one_exception_catchpoint(), print_one_inferior(), print_one_ranged_breakpoint(), print_one_static_tracepoint_marker(), print_partial_file_name(), print_return_value(), print_script(), print_signal_exited_reason(), print_signal_received_reason(), print_solib_event(), print_source_lines_base(), print_stack_frame(), print_transfer_performance(), print_ui_out_info(), print_variable_or_computed(), print_varobj(), read_frame_arg(), record_btrace_call_history(), record_btrace_call_history_range(), record_btrace_insn_history(), record_btrace_insn_history_range(), remote_fileio_request(), restore_selected_frame(), run_command_1(), safe_execute_command(), save_breakpoints(), set_logging_redirect(), show_cp_abi_cmd(), show_remote_cmd(), show_user_1(), signal_catchpoint_print_one(), skip_info(), task_command(), tfind_1(), thread_command(), trace_status_mi(), tracepoint_print_mention(), tracepoints_info(), tui_setup_io(), tvariables_info_1(), update_static_tracepoint(), varobj_update_one(), watchpoint_check(), and watchpoints_info().
struct ui_out def_uiout
Initial value:
{
  0,
  &default_ui_out_impl,
}
Definition at line 225 of file ui-out.c.
struct ui_out_impl default_ui_out_impl
Initial value:
{
  default_table_begin,
  default_table_body,
  default_table_end,
  default_table_header,
  default_begin,
  default_end,
  default_field_int,
  default_field_skip,
  default_field_string,
  default_field_fmt,
  default_spaces,
  default_text,
  default_message,
  default_wrap_hint,
  default_flush,
  NULL,
  default_data_destroy,
  0,
}
Definition at line 201 of file ui-out.c.