GDB (xrefs): /home/stan/gdb/src/gdb/user-regs.h File Reference
/home/stan/gdb/src/gdb/user-regs.h File Reference
Typedefs
typedef struct value *(user_reg_read_ftype)(struct frame_info *frame, const void *baton)
Functions
int user_reg_map_name_to_regnum (struct gdbarch *gdbarch, const char *str, int len)
const char * user_reg_map_regnum_to_name (struct gdbarch *gdbarch, int regnum)
struct value * value_of_user_reg (int regnum, struct frame_info *frame)
void user_reg_add_builtin (const char *name, user_reg_read_ftype *read, const void *baton)
void user_reg_add (struct gdbarch *gdbarch, const char *name, user_reg_read_ftype *read, const void *baton)
Typedef Documentation
typedef struct value*(user_reg_read_ftype)(struct frame_info *frame, const void *baton)
Definition at line 59 of file user-regs.h.
Function Documentation
void user_reg_add (struct gdbarch * gdbarch, const char * name, user_reg_read_ftype * read, const void * baton)
Definition at line 111 of file user-regs.c.
References append_user_reg(), deprecated_set_gdbarch_data(), gdbarch_data(), GDBARCH_OBSTACK_ZALLOC, and user_regs_init().
Referenced by aarch64_gdbarch_init(), arm_gdbarch_init(), and mips_gdbarch_init().
void user_reg_add_builtin (const char * name, user_reg_read_ftype * read, const void * baton)
Definition at line 84 of file user-regs.c.
References append_user_reg(), and XMALLOC.
Referenced by _initialize_frame_reg().
int user_reg_map_name_to_regnum (struct gdbarch * gdbarch, const char * str, int len)
Definition at line 128 of file user-regs.c.
References gdb_user_regs::first, gdbarch_data(), gdbarch_num_pseudo_regs(), gdbarch_num_regs(), gdbarch_register_name(), user_reg::name, and user_reg::next.
Referenced by arm_dwarf_reg_to_regnum(), arm_neon_quad_read(), arm_neon_quad_write(), arm_pseudo_read(), arm_pseudo_write(), arm_push_dummy_call(), arm_return_value(), arm_stap_parse_special_token(), encode_actions_1(), evaluate_subexp_standard(), gen_expr(), i386_stap_parse_special_token(), init_sim_regno_table(), ppc_stap_parse_special_token(), registers_info(), stap_parse_register_operand(), and write_dollar_variable().
const char* user_reg_map_regnum_to_name (struct gdbarch * gdbarch, int regnum)
Definition at line 189 of file user-regs.c.
References gdbarch_num_pseudo_regs(), gdbarch_num_regs(), gdbarch_register_name(), user_reg::name, and usernum_to_user_reg().
Referenced by ax_reg(), ax_reg_mask(), frame_unwind_register_value(), registers_info(), and value_fetch_lazy().
struct value* value_of_user_reg (int regnum, struct frame_info * frame) [read]
Definition at line 209 of file user-regs.c.
References user_reg::baton, gdb_assert, gdbarch_num_pseudo_regs(), gdbarch_num_regs(), get_frame_arch(), user_reg::read, and usernum_to_user_reg().
Referenced by registers_info(), and value_of_register().