GDB (xrefs): /home/stan/gdb/src/gdb/utils.c File Reference
/home/stan/gdb/src/gdb/utils.c File Reference
#include "defs.h"
#include "dyn-string.h"
#include "gdb_assert.h"
#include <ctype.h>
#include "gdb_string.h"
#include "gdb_wait.h"
#include "event-top.h"
#include "exceptions.h"
#include "gdbthread.h"
#include "fnmatch.h"
#include "gdb_bfd.h"
#include <signal.h>
#include "timeval-utils.h"
#include "gdbcmd.h"
#include "serial.h"
#include "bfd.h"
#include "target.h"
#include "gdb-demangle.h"
#include "expression.h"
#include "language.h"
#include "charset.h"
#include "annotate.h"
#include "filenames.h"
#include "symfile.h"
#include "gdb_obstack.h"
#include "gdbcore.h"
#include "top.h"
#include "main.h"
#include "solist.h"
#include "inferior.h"
#include "gdb_curses.h"
#include "readline/readline.h"
#include <sys/time.h>
#include <time.h>
#include "gdb_usleep.h"
#include "interps.h"
#include "gdb_regex.h"
Classes
struct restore_integer_closure
struct restore_ui_file_closure
struct internal_problem
Defines
#define NUMCELLS 16
#define CELLSIZE 50
#define HIGH_BYTE_POSN ((sizeof (ULONGEST) - 1) * HOST_CHAR_BIT)
#define AMBIGUOUS_MESS1 ".\nMatching formats:"
#define AMBIGUOUS_MESS2 ".\nUse \"set gnutarget format-name\" to specify the format."
Functions
PTR malloc ()
PTR realloc ()
void free ()
static void vfprintf_maybe_filtered (static void fputs_maybe_filtered(const char struct ui_file *, const char *, va_list, int)
void set_quit_flag (void)
int check_quit_flag (void)
static void show_sevenbit_strings (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static void show_pagination_enabled (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static void do_freeargv (void *arg)
struct cleanup * make_cleanup_freeargv (char **arg)
static void do_dyn_string_delete (void *arg)
struct cleanup * make_cleanup_dyn_string_delete (dyn_string_t arg)
static void do_bfd_close_cleanup (void *arg)
struct cleanup * make_cleanup_bfd_unref (bfd *abfd)
static void do_close_cleanup (void *arg)
struct cleanup * make_cleanup_close (int fd)
static void do_fclose_cleanup (void *arg)
struct cleanup * make_cleanup_fclose (FILE *file)
static void do_obstack_free (void *arg)
struct cleanup * make_cleanup_obstack_free (struct obstack *obstack)
static void do_ui_file_delete (void *arg)
struct cleanup * make_cleanup_ui_file_delete (struct ui_file *arg)
static void do_ui_out_redirect_pop (void *arg)
struct cleanup * make_cleanup_ui_out_redirect_pop (struct ui_out *uiout)
static void do_free_section_addr_info (void *arg)
struct cleanup * make_cleanup_free_section_addr_info (struct section_addr_info *addrs)
static void restore_integer (void *p)
struct cleanup * make_cleanup_restore_integer (int *variable)
struct cleanup * make_cleanup_restore_uinteger (unsigned int *variable)
static void do_unpush_target (void *arg)
struct cleanup * make_cleanup_unpush_target (struct target_ops *ops)
static void do_htab_delete_cleanup (void *htab_voidp)
struct cleanup * make_cleanup_htab_delete (htab_t htab)
static void do_restore_ui_file (void *p)
struct cleanup * make_cleanup_restore_ui_file (struct ui_file **variable)
static void do_value_free_to_mark (void *value)
struct cleanup * make_cleanup_value_free_to_mark (struct value *mark)
static void do_value_free (void *value)
struct cleanup * make_cleanup_value_free (struct value *value)
static void do_free_so (void *arg)
struct cleanup * make_cleanup_free_so (struct so_list *so)
static void do_restore_current_language (void *p)
struct cleanup * make_cleanup_restore_current_language (void)
void free_current_contents (void *ptr)
void vwarning (const char *string, va_list args)
void warning (const char *string,...)
void verror (const char *string, va_list args)
void error (const char *string,...)
void vfatal (const char *string, va_list args)
void fatal (const char *string,...)
void error_stream (struct ui_file *stream)
static void dump_core (void)
static int can_dump_core (const char *reason)
static void ATTRIBUTE_PRINTF (4, 0)
void internal_verror (const char *file, int line, const char *fmt, va_list ap)
void internal_error (const char *file, int line, const char *string,...)
void internal_vwarning (const char *file, int line, const char *fmt, va_list ap)
void internal_warning (const char *file, int line, const char *string,...)
static void set_internal_problem_cmd (char *args, int from_tty)
static void show_internal_problem_cmd (char *args, int from_tty)
static void add_internal_problem_command (struct internal_problem *problem)
static char * perror_string (const char *prefix)
void throw_perror_with_name (enum errors errcode, const char *string)
void perror_with_name (const char *string)
void perror_warning_with_name (const char *string)
void print_sys_errmsg (const char *string, int errcode)
void quit (void)
void malloc_failure (long size)
int myread (int desc, char *addr, int len)
void print_spaces (int n, struct ui_file *file)
void gdb_print_host_address (const void *addr, struct ui_file *stream)
static void do_regfree_cleanup (void *r)
struct cleanup * make_regfree_cleanup (regex_t *r)
char * get_regcomp_error (int code, regex_t *rx)
struct cleanup * compile_rx_or_error (regex_t *pattern, const char *rx, const char *message)
static int ATTRIBUTE_PRINTF (1, 0)
int nquery (const char *ctlstr,...)
int yquery (const char *ctlstr,...)
int query (const char *ctlstr,...)
static int host_char_to_target (struct gdbarch *gdbarch, int c, int *target_c)
int parse_escape (struct gdbarch *gdbarch, const char **string_ptr)
static void printchar (int c, void(*do_fputs)(const char *, struct ui_file *), void(*do_fprintf)(struct ui_file *, const char *,...) ATTRIBUTE_FPTR_PRINTF_2, struct ui_file *stream, int quoter)
void fputstr_filtered (const char *str, int quoter, struct ui_file *stream)
void fputstr_unfiltered (const char *str, int quoter, struct ui_file *stream)
void fputstrn_filtered (const char *str, int n, int quoter, struct ui_file *stream)
void fputstrn_unfiltered (const char *str, int n, int quoter, struct ui_file *stream)
static void show_lines_per_page (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static void show_chars_per_line (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
void init_page_info (void)
static void do_restore_page_info_cleanup (void *arg)
struct cleanup * make_cleanup_restore_page_info (void)
struct cleanup * set_batch_flag_and_make_cleanup_restore_page_info (void)
static void set_screen_size (void)
static void set_width (void)
static void set_width_command (char *args, int from_tty, struct cmd_list_element *c)
static void set_height_command (char *args, int from_tty, struct cmd_list_element *c)
static void prompt_for_continue (void)
void reset_prompt_for_continue_wait_time (void)
struct timeval get_prompt_for_continue_wait_time (void)
void reinitialize_more_filter (void)
void wrap_here (char *indent)
void puts_filtered_tabular (char *string, int width, int right)
void begin_line (void)
static void fputs_maybe_filtered (const char *linebuffer, struct ui_file *stream, int filter)
void fputs_filtered (const char *linebuffer, struct ui_file *stream)
int putchar_unfiltered (int c)
int putchar_filtered (int c)
int fputc_unfiltered (int c, struct ui_file *stream)
int fputc_filtered (int c, struct ui_file *stream)
void puts_debug (char *prefix, char *string, char *suffix)
static void vfprintf_maybe_filtered (struct ui_file *stream, const char *format, va_list args, int filter)
void vfprintf_filtered (struct ui_file *stream, const char *format, va_list args)
void vfprintf_unfiltered (struct ui_file *stream, const char *format, va_list args)
void vprintf_filtered (const char *format, va_list args)
void vprintf_unfiltered (const char *format, va_list args)
void fprintf_filtered (struct ui_file *stream, const char *format,...)
void fprintf_unfiltered (struct ui_file *stream, const char *format,...)
void fprintfi_filtered (int spaces, struct ui_file *stream, const char *format,...)
void printf_filtered (const char *format,...)
void printf_unfiltered (const char *format,...)
void printfi_filtered (int spaces, const char *format,...)
void puts_filtered (const char *string)
void puts_unfiltered (const char *string)
char * n_spaces (int n)
void print_spaces_filtered (int n, struct ui_file *stream)
void fprintf_symbol_filtered (struct ui_file *stream, const char *name, enum language lang, int arg_mode)
int strcmp_iw (const char *string1, const char *string2)
int strcmp_iw_ordered (const char *string1, const char *string2)
int streq (const char *lhs, const char *rhs)
int subset_compare (char *string_to_compare, char *template_string)
static void pagination_on_command (char *arg, int from_tty)
static void pagination_off_command (char *arg, int from_tty)
static void show_debug_timestamp (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
void initialize_utils (void)
static char * get_cell (void)
const char * paddress (struct gdbarch *gdbarch, CORE_ADDR addr)
const char * print_core_address (struct gdbarch *gdbarch, CORE_ADDR address)
hashval_t core_addr_hash (const void *ap)
int core_addr_eq (const void *ap, const void *bp)
static char * decimal2str (char *sign, ULONGEST addr, int width)
static char * octal2str (ULONGEST addr, int width)
char * pulongest (ULONGEST u)
char * plongest (LONGEST l)
char * phex (ULONGEST l, int sizeof_l)
char * phex_nz (ULONGEST l, int sizeof_l)
char * hex_string (LONGEST num)
char * hex_string_custom (LONGEST num, int width)
char * int_string (LONGEST val, int radix, int is_signed, int width, int use_c_format)
const char * core_addr_to_string (const CORE_ADDR addr)
const char * core_addr_to_string_nz (const CORE_ADDR addr)
CORE_ADDR string_to_core_addr (const char *my_string)
const char * host_address_to_string (const void *addr)
char * gdb_realpath (const char *filename)
ULONGEST align_up (ULONGEST v, int n)
ULONGEST align_down (ULONGEST v, int n)
LONGEST gdb_sign_extend (LONGEST value, int bit)
void * hashtab_obstack_allocate (void *data, size_t size, size_t count)
void dummy_obstack_deallocate (void *object, void *data)
static int is_digit_in_base (unsigned char digit, int base)
static int digit_to_int (unsigned char c)
ULONGEST strtoulst (const char *num, const char **trailer, int base)
char * ldirname (const char *filename)
char ** gdb_buildargv (const char *s)
int compare_positive_ints (const void *ap, const void *bp)
int compare_strings (const void *arg1, const void *arg2)
const char * gdb_bfd_errmsg (bfd_error_type error_tag, char **matching)
int parse_pid_to_attach (char *args)
static void do_bpstat_clear_actions_cleanup (void *unused)
struct cleanup * make_bpstat_clear_actions_cleanup (void)
int producer_is_gcc_ge_4 (const char *producer)
static void do_free_char_ptr_vec (void *arg)
struct cleanup * make_cleanup_free_char_ptr_vec (VEC(char_ptr)*char_ptr_vec)
void substitute_path_component (char **stringp, const char *from, const char *to)
int gdb_filename_fnmatch (const char *pattern, const char *string, int flags)
void _initialize_utils (void)
Variables
void(* deprecated_error_begin_hook)(void)
int sevenbit_strings = 0
char * warning_pre_print = "\nwarning: "
int pagination_enabled = 1
const char internal_problem_ask [] = "ask"
const char internal_problem_yes [] = "yes"
const char internal_problem_no [] = "no"
static const char *const internal_problem_modes []
static struct internal_problem internal_error_problem
static struct internal_problem internal_warning_problem
static unsigned int lines_per_page
static unsigned int chars_per_line
static unsigned int lines_printed
static unsigned int chars_printed
static char * wrap_buffer
static char * wrap_pointer
static char * wrap_indent
static int wrap_column
static int thirty_two = 32
initialize_file_ftype _initialize_utils
Define Documentation
#define AMBIGUOUS_MESS1 ".\nMatching formats:"
Definition at line 3368 of file utils.c.
Referenced by gdb_bfd_errmsg().
#define AMBIGUOUS_MESS2 ".\nUse \"set gnutarget format-name\" to specify the format."
Definition at line 3369 of file utils.c.
Referenced by gdb_bfd_errmsg().
#define CELLSIZE 50
Definition at line 2686 of file utils.c.
Referenced by decimal2str(), get_cell(), hex_string(), hex_string_custom(), host_address_to_string(), octal2str(), phex(), and phex_nz().
#define HIGH_BYTE_POSN ((sizeof (ULONGEST) - 1) * HOST_CHAR_BIT)
Definition at line 3215 of file utils.c.
Referenced by strtoulst().
#define NUMCELLS 16
Definition at line 2685 of file utils.c.
Referenced by get_cell().
Function Documentation
void _initialize_utils (void)
Definition at line 3674 of file utils.c.
References add_internal_problem_command().
static void add_internal_problem_command (struct internal_problem * problem) [static]
Definition at line 881 of file utils.c.
References _, add_prefix_cmd(), add_setshow_enum_cmd(), class_maintenance, maintenance_set_cmdlist, maintenance_show_cmdlist, internal_problem::name, set_internal_problem_cmd(), internal_problem::should_dump_core, internal_problem::should_quit, show_internal_problem_cmd(), xfree(), xmalloc(), and xstrprintf().
Referenced by _initialize_utils().
ULONGEST align_down (ULONGEST v, int n)
Definition at line 3164 of file utils.c.
References gdb_assert.
Referenced by aarch64_push_dummy_call(), frv_frame_align(), frv_push_dummy_call(), h8300_push_dummy_call(), hppa_linux_sigtramp_find_sigcontext(), i386_darwin_push_dummy_call(), m88k_store_arguments(), mips_eabi_push_dummy_call(), mips_frame_align(), mips_n32n64_push_dummy_call(), mips_o32_push_dummy_call(), mips_o64_push_dummy_call(), msp430_frame_align(), msp430_push_dummy_call(), mt_frame_align(), nios2_frame_align(), ppc64_sysv_abi_push_dummy_call(), ppc_sysv_abi_push_dummy_call(), rl78_frame_align(), rs6000_lynx178_push_dummy_call(), rx_push_dummy_call(), s390_push_dummy_call(), score_adjust_breakpoint_address(), score_frame_align(), score_push_dummy_call(), tic6x_frame_align(), tic6x_push_dummy_call(), and xtensa_push_dummy_call().
ULONGEST align_up (ULONGEST v, int n)
Definition at line 3156 of file utils.c.
References gdb_assert.
Referenced by ctf_save_align_write(), frv_push_dummy_call(), h8300_push_dummy_call(), hppa32_frame_align(), hppa32_push_dummy_call(), hppa64_frame_align(), hppa64_push_dummy_call(), i386_darwin_push_dummy_call(), i386_push_dummy_call(), mips_eabi_push_dummy_call(), mips_n32n64_push_dummy_call(), mips_o32_push_dummy_call(), mips_o64_push_dummy_call(), nios2_push_dummy_call(), pass_on_stack(), ppc64_sysv_abi_push_dummy_call(), ppc_linux_spe_context(), ppc_sysv_abi_push_dummy_call(), rs6000_lynx178_push_dummy_call(), rx_push_dummy_call(), s390_push_dummy_call(), s390_sigtramp_frame_unwind_cache(), score_push_dummy_call(), spu_push_dummy_call(), store_register(), tic6x_push_dummy_call(), and tilegx_push_dummy_call().
static void ATTRIBUTE_PRINTF (4 , 0) [static]
Definition at line 692 of file utils.c.
References _, begin_line(), can_dump_core(), confirm, do_cleanups(), dump_core(), fputs_unfiltered(), gdb_stderr, internal_error(), make_cleanup(), null_cleanup(), query(), target_terminal_ours, xfree(), xstrprintf(), and xstrvprintf().
static int ATTRIBUTE_PRINTF (1 , 0) [static]
Definition at line 1177 of file utils.c.
References _, annotation_level, confirm, deprecated_query_hook, fputs_filtered(), gdb_flush(), gdb_stdout, gdb_usleep(), input_from_terminal_p(), printf_filtered(), server_command, vfprintf_filtered(), wrap_here(), xfree(), and xstrvprintf().
void begin_line (void)
Definition at line 1979 of file utils.c.
References puts_filtered().
Referenced by ATTRIBUTE_PRINTF(), classes_info(), and selectors_info().
static int can_dump_core (const char * reason) [static]
Definition at line 641 of file utils.c.
References _, fprintf_unfiltered(), and gdb_stderr.
Referenced by ATTRIBUTE_PRINTF().
int check_quit_flag (void)
Definition at line 160 of file utils.c.
Referenced by async_request_quit(), gdb_os_poll_quit(), load_progress(), and remote_wait_as().
int compare_positive_ints (const void * ap, const void * bp)
Integer compare function suitable for qsort.
Definition at line 3350 of file utils.c.
Referenced by list_available_thread_groups(), mi_cmd_list_thread_groups(), print_bcache_statistics(), and print_one_inferior().
int compare_strings (const void * ap, const void * bp)
String compare function suitable for qsort.
Definition at line 3360 of file utils.c.
Referenced by complete_command(), and uniquify_strings().
struct cleanup* compile_rx_or_error (regex_t * pattern, const char * rx, const char * message) [read]
Definition at line 1147 of file utils.c.
References code, error(), gdb_assert, get_regcomp_error(), make_cleanup(), make_regfree_cleanup(), and xfree().
Referenced by handle_gnu_v3_exceptions().
int core_addr_eq (const void * ap, const void * bp)
Definition at line 2749 of file utils.c.
Referenced by call_site_find_chain_1(), func_verify_no_selftailcall(), and read_call_site_scope().
hashval_t core_addr_hash (const void * ap)
Definition at line 2739 of file utils.c.
Referenced by call_site_find_chain_1(), func_verify_no_selftailcall(), and read_call_site_scope().
const char* core_addr_to_string (const CORE_ADDR addr)
Convert a CORE_ADDR into a hex string with leading zeros, and prefixed with "0x" as in C syntax. The output from core_addr_to_string() can be passed direct to string_to_core_addr().
Definition at line 3002 of file utils.c.
References get_cell(), and phex().
Referenced by compile_probe_arg(), compute_probe_arg(), darwin_read_write_inferior(), darwin_xfer_partial(), debug_to_can_accel_watchpoint_condition(), debug_to_insert_breakpoint(), debug_to_insert_hw_breakpoint(), debug_to_insert_watchpoint(), debug_to_region_ok_for_hw_watchpoint(), debug_to_remove_breakpoint(), debug_to_remove_hw_breakpoint(), debug_to_remove_watchpoint(), debug_to_stopped_data_address(), debug_to_watchpoint_addr_within_range(), gdb_entry_point(), gdb_get_breakpoint_info(), gdb_get_tracepoint_info(), gdb_incr_addr(), gdb_load_disassembly(), gdb_loc(), gdb_update_mem(), gdbtk_load_asm(), rs6000_aix_shared_library_to_xml(), solib_aix_get_toc_value(), spu_catch_start(), target_insert_mask_watchpoint(), target_remove_mask_watchpoint(), watch_command_1(), and windows_xfer_memory().
const char* core_addr_to_string_nz (const CORE_ADDR addr)
Convert a CORE_ADDR into a hex string, withOUT leading zeros, and prefixed with "0x" as in C syntax. The output from core_addr_to_string() can be passed direct to string_to_core_addr().
Definition at line 3012 of file utils.c.
References get_cell(), and phex_nz().
Referenced by aarch64_analyze_prologue(), debug_print_register(), decode_add_sub_imm(), decode_adrp(), decode_b(), decode_bcond(), decode_br(), decode_cb(), decode_eret(), decode_movz(), decode_orr_shifted_register_x(), decode_ret(), decode_stp_offset(), decode_stp_offset_wb(), decode_stur(), decode_tb(), gdbarch_dump(), target_xfer_partial(), and VEC().
static char* decimal2str (char * sign, ULONGEST addr, int width) [static]
Definition at line 2758 of file utils.c.
References _, CELLSIZE, get_cell(), internal_error(), and xsnprintf().
Referenced by int_string(), plongest(), and pulongest().
static int digit_to_int (unsigned char c) [static]
Definition at line 3232 of file utils.c.
Referenced by strtoulst().
static void do_bfd_close_cleanup (void * arg) [static]
Definition at line 232 of file utils.c.
References gdb_bfd_unref().
Referenced by make_cleanup_bfd_unref().
static void do_bpstat_clear_actions_cleanup (void * unused) [static]
Definition at line 3432 of file utils.c.
References bpstat_clear_actions().
Referenced by make_bpstat_clear_actions_cleanup().
static void do_close_cleanup (void * arg) [static]
Definition at line 244 of file utils.c.
References cleanup::arg.
Referenced by make_cleanup_close().
static void do_dyn_string_delete (void * arg) [static]
Definition at line 220 of file utils.c.
Referenced by make_cleanup_dyn_string_delete().
static void do_fclose_cleanup (void * arg) [static]
Definition at line 263 of file utils.c.
References cleanup::arg.
Referenced by make_cleanup_fclose().
static void do_free_char_ptr_vec (void * arg) [static]
Definition at line 3491 of file utils.c.
References cleanup::arg, free_char_ptr_vec(), and VEC.
Referenced by make_cleanup_free_char_ptr_vec().
static void do_free_section_addr_info (void * arg) [static]
Definition at line 329 of file utils.c.
References free_section_addr_info().
Referenced by make_cleanup_free_section_addr_info().
static void do_free_so (void * arg) [static]
Definition at line 478 of file utils.c.
References free_so().
Referenced by make_cleanup_free_so().
static void do_freeargv (void * arg) [static]
Definition at line 208 of file utils.c.
Referenced by make_cleanup_freeargv().
static void do_htab_delete_cleanup (void * htab_voidp) [static]
Definition at line 399 of file utils.c.
Referenced by make_cleanup_htab_delete().
static void do_obstack_free (void * arg) [static]
Definition at line 281 of file utils.c.
Referenced by make_cleanup_obstack_free().
static void do_regfree_cleanup (void * r) [static]
Definition at line 1116 of file utils.c.
Referenced by make_regfree_cleanup().
static void do_restore_current_language (void * p) [static]
Definition at line 496 of file utils.c.
References set_language().
Referenced by make_cleanup_restore_current_language().
static void do_restore_page_info_cleanup (void * arg) [static]
Definition at line 1697 of file utils.c.
References set_screen_size(), and set_width().
Referenced by make_cleanup_restore_page_info().
static void do_restore_ui_file (void * p) [static]
Definition at line 421 of file utils.c.
References restore_ui_file_closure::value, and restore_ui_file_closure::variable.
Referenced by make_cleanup_restore_ui_file().
static void do_ui_file_delete (void * arg) [static]
Definition at line 297 of file utils.c.
References ui_file_delete().
Referenced by make_cleanup_ui_file_delete().
static void do_ui_out_redirect_pop (void * arg) [static]
Definition at line 311 of file utils.c.
References _, ui_out_redirect(), and warning().
Referenced by make_cleanup_ui_out_redirect_pop().
static void do_unpush_target (void * arg) [static]
Definition at line 381 of file utils.c.
References unpush_target().
Referenced by make_cleanup_unpush_target().
static void do_value_free (void * value) [static]
Definition at line 462 of file utils.c.
References value_free().
Referenced by make_cleanup_value_free().
static void do_value_free_to_mark (void * value) [static]
Definition at line 445 of file utils.c.
References value_free_to_mark().
Referenced by make_cleanup_value_free_to_mark().
void dummy_obstack_deallocate (void * object, void * data)
Definition at line 3207 of file utils.c.
Referenced by allocate_dwo_file_hash_table(), allocate_dwo_unit_table(), allocate_dwp_loaded_cutus_table(), allocate_signatured_type_table(), allocate_type_unit_groups_table(), create_copied_types_hash(), dwarf2_add_dependence(), elf_gnu_ifunc_record_cache(), load_full_comp_unit_reader(), load_partial_dies(), read_signatured_type_reader(), and set_die_type().
static void dump_core (void) [static]
Definition at line 626 of file utils.c.
Referenced by ATTRIBUTE_PRINTF().
void error (const char * string, ...)
Definition at line 585 of file utils.c.
References GENERIC_ERROR, and throw_verror().
Referenced by _parse_bool_arg(), aarch64_linux_set_debug_regs(), access_value_history(), active_inf(), ada_build_task_list(), ada_coerce_to_simple_array(), ada_decoded_op_name(), ada_discrete_type_high_bound(), ada_discrete_type_low_bound(), ada_encode(), ada_exception_support_info_sniffer(), ada_get_field_index(), ada_has_this_exception_support(), ada_index_struct_field_1(), ada_index_type(), ada_lookup_struct_elt_type(), ada_main_name(), ada_print_scalar(), ada_promote_array_of_integrals(), ada_same_array_size_p(), ada_template_to_fixed_record_type_1(), ada_value_assign(), ada_value_binop(), ada_value_equal(), ada_value_ptr_subscript(), ada_value_struct_elt(), ada_value_subscript(), add_auto_load_safe_path(), add_component_interval(), add_inferior_command(), add_line_to_sigset(), add_register(), add_solib_catchpoint(), add_symbol_file_command(), add_symbol_file_from_memory_command(), address_info(), address_of_variable(), address_space_name_to_int(), advance_command(), agent_command_1(), agent_printf_command(), aggregate_assign_from_choices(), aix_thread_resume(), alias_command(), alpha_register_to_value(), alpha_store_return_value(), alpha_value_to_register(), amd64_linux_disable_btrace(), amd64_linux_enable_btrace(), amd64_linux_read_description(), apply_frame_filter(), apropos_command(), arm_get_next_pc(), arm_get_next_pc_raw(), arm_instruction_changes_pc(), arm_stap_parse_special_token(), async_float_handler(), attach_command(), attach_thread(), ATTRIBUTE_PRINTF(), auto_load_info_scripts(), ax_const_d(), ax_label(), ax_pick(), ax_print(), ax_reg(), ax_reg_mask(), ax_trace_quick(), backtrace_command_1(), bfd_openr_with_cleanup(), bfd_openw_with_cleanup(), bfdcore_read(), bfdcore_write(), bkpt_probe_decode_linespec(), block_lookup(), bootstrap_python_frame_filters(), bppy_init(), break_range_command(), bsd_kvm_fetch_pcb(), bsd_kvm_fetch_registers(), bsd_kvm_open(), bsd_kvm_pcb_cmd(), bsd_kvm_proc_cmd(), bsd_uthread_check_magic(), btrace_enable(), build_command_line(), c_get_string(), c_parse_escape(), c_type_print_varspec_prefix(), c_type_print_varspec_suffix(), c_val_print(), calc_f77_array_dims(), call0_analyze_prologue(), call_function_by_hand(), captured_main(), cast_into_complex(), catch_ada_assert_command_split(), catch_ada_exception_command_split(), catch_command(), catch_exception_command_1(), catch_exec_command_1(), catch_fork_command_1(), catch_syscall_command_1(), check_empty(), check_event(), check_fast_tracepoint_sals(), check_no_tracepoint_commands(), check_parameter_typelist(), check_size(), check_stub_method(), checkpoint_command(), classes_info(), classify_unsafe_function(), cleanup_block_load_all(), clear_command(), clone_inferior_command(), cmd_func(), cmd_record_btrace_start(), cmd_record_goto(), cmd_record_goto_begin(), cmd_record_goto_end(), cmdpy_function(), coerce_for_assign(), coff_symfile_read(), coff_symtab_read(), coffstab_build_psymtabs(), collect_pseudocommand(), commands_command_1(), compare_classes(), compare_sections_command(), compare_selectors(), compile_pattern(), compile_probe_arg(), compile_rx_or_error(), compute_probe_arg(), condition_command(), construct_inferior_arguments(), continue_command(), convert_between_encodings(), convert_escape(), core_detach(), core_open(), cplus_make_method_ptr(), cplus_method_ptr_size(), cplus_method_ptr_to_value(), cplus_print_method_ptr(), cplus_print_vtable(), cplus_type_from_type_info(), cplus_typeid(), cplus_typeid_type(), cplus_typename_from_type_info(), create_breakpoint(), create_dwo_unit_in_dwp_v1(), create_dwp_hash_table(), create_dwp_v2_section(), create_gcore_bfd(), cris_extract_return_value(), cris_sigcontext_addr(), cris_store_return_value(), ctf_save_fseek(), ctf_save_write(), ctf_save_write_metadata(), ctf_start(), ctx_no_dwarf_call(), ctx_no_get_addr_index(), ctx_no_get_base_type(), ctx_no_get_frame_base(), ctx_no_get_frame_cfa(), ctx_no_get_frame_pc(), ctx_no_get_tls_address(), cur_thread(), darwin_attach(), darwin_attach_pid(), darwin_bfd_open(), darwin_pre_ptrace(), darwin_ptrace_me(), darwin_set_sstep(), dbx_symfile_init(), dead_procinfo(), decimal_check_errors(), decimal_compare(), decimal_from_integral(), decimal_from_string(), decimal_to_number(), decimal_to_string(), decode_agent_options(), decode_constrained_packed_array(), decode_frame_entry_1(), decode_line_2(), decode_line_with_current_source(), decode_line_with_last_displayed(), decode_static_tracepoint_spec(), default_gcore_arch(), default_gcore_mach(), default_gen_return_address(), default_get_string(), default_memory_insert_breakpoint(), default_print_typedef(), default_read_var_value(), define_command(), delete_checkpoint_command(), desc_bounds(), destructor_name_p(), detach_breakpoints(), detach_callback(), detach_checkpoint_command(), detach_command(), detach_inferior_command(), die_containing_type(), disassemble_command(), disassemble_current_function(), disassemble_dwarf_expression(), display_tib(), dll_symbol_command(), do_attach(), do_captured_thread_select(), do_monitor_command(), do_search_struct_field(), do_set_command(), do_show_command(), document_command(), down_silently_base(), dprintf_re_set(), dsbt_get_initial_loadmaps(), dummy_find_memory_regions(), dummy_make_corefile_notes(), dump_memory_to_file(), dump_value_to_file(), dwarf2_add_member_fn(), dwarf2_attach_fields_to_type(), dwarf2_attach_fn_fields_to_type(), dwarf2_compile_cfa_to_ax(), dwarf2_compile_expr_to_ax(), dwarf2_evaluate_loc_desc_full(), dwarf2_fetch_constant_bytes(), dwarf2_fetch_die_loc_sect_off(), dwarf2_find_containing_comp_unit(), dwarf2_find_location_expression(), dwarf2_frame_cfa(), dwarf2_get_dwz_file(), dwarf2_read_section(), dwarf_expr_address_type(), dwarf_expr_fetch(), dwarf_expr_fetch_in_stack_memory(), dwarf_expr_frame_base(), dwarf_expr_frame_base_1(), dwarf_expr_pop(), dwarf_expr_require_composition(), dwarf_get_base_type(), dwarf_require_integral(), edit_command(), elf_symfile_read(), elfmdebug_build_psymtabs(), elfstab_build_psymtabs(), enable_breakpoint_disp(), encode_actions_1(), encode_source_string(), end_actions_pseudocommand(), end_msglist(), ensure_not_tfind_mode(), ensure_valid_thread(), entry_point_address(), enumerate_args(), enumerate_locals(), error_check_comp_unit_head(), error_in_psymtab_expansion(), error_is_running(), error_no_arg(), error_stream(), error_value_optimized_out(), eval_python_from_control_command(), evaluate_subexp_c(), evaluate_subexp_for_sizeof(), evaluate_subexp_java(), evaluate_subexp_modula2(), evaluate_subexp_opencl(), evaluate_subexp_standard(), exec_file_attach(), exec_file_command(), exec_make_note_section(), exec_reverse_continue(), exec_reverse_once(), execute_command(), execute_stack_op(), execute_user_command(), expand(), extended_remote_attach_1(), extended_remote_create_inferior_1(), extended_remote_disable_randomization(), extended_remote_kill(), extended_remote_run(), extract_signed_integer(), extract_unsigned_integer(), f77_get_lowerbound(), f77_print_array(), f_get_encoding(), f_type_print_base(), fake_create_process(), fbsd_find_memory_regions(), fetch_lm_info(), fetch_osf_core_registers(), fetch_probe_arguments(), fetch_register(), fetch_register_using_p(), fetch_regs_user_thread(), fill_symbuf(), find_breakpoint_range_end(), find_condition_and_thread(), find_default_run_target(), find_function_addr(), find_function_in_inferior(), find_location_by_number(), find_name_end(), find_new_threads_callback(), find_overload_match(), find_partial_die(), find_procinfo_or_die(), find_size_for_pointer_math(), find_sym_fns(), find_text_range(), find_unwind_entry(), finish_command(), float_info(), floatformat_from_length(), fnpy_call(), follow_die_ref(), follow_die_ref_or_sig(), follow_die_sig(), forward_search_command(), frame_pop(), frame_unwind_register(), fromhex(), frv_relocate_main_executable(), gather_arguments(), gdb_bfd_map_section(), gdb_load_disassembly(), gdb_signal_from_command(), gdb_signal_from_host(), gdbsim_create_inferior(), gdbsim_load(), gdbsim_open(), gdbsim_resume(), gdbsim_stop(), gdbsim_wait(), gdbsim_xfer_memory(), gdbtk_init(), gen_address_of(), gen_binop(), gen_cast(), gen_complement(), gen_deref(), gen_expr(), gen_expr_binop_rest(), gen_fetch(), gen_logical_not(), gen_maybe_namespace_elt(), gen_namespace_elt(), gen_ptrdiff(), gen_repeat(), gen_struct_elt_for_reference(), gen_struct_ref(), gen_struct_ref_recursive(), gen_var_ref(), generic_ext(), generic_load(), generic_val_print(), get_call_history_modifiers(), get_character_constant(), get_comment(), get_context_size(), get_current_frame(), get_exec_file(), get_frame_register_bytes(), get_insn_history_modifiers(), get_insn_number(), get_java_object_type(), get_long_set_bounds(), get_module_name(), get_number_or_range(), get_offsets(), get_osdata(), get_selected_frame(), get_selections(), get_set_value(), get_show_value(), get_signed_type(), get_sim_inferior_data(), get_string_literal(), get_tcb_types_info(), get_traceframe_location(), get_unsigned_type(), get_value_at(), get_var_value(), get_windows_debug_event(), gnu_attach(), gnu_create_inferior(), gnu_fetch_registers(), gnu_resume(), gnu_stop(), gnu_store_registers(), gnu_wait(), gnuv2_baseclass_offset(), gnuv2_virtual_fn_field(), gnuv3_baseclass_offset(), gnuv3_get_typeid(), gnuv3_get_typename_from_type_info(), gnuv3_virtual_fn_field(), go32_attach(), go32_create_inferior(), go32_pde(), go32_pte(), go32_sgdt(), go32_sidt(), go32_sldt(), go32_terminal_inferior(), go32_terminal_ours(), goto_bookmark_command(), h8300_extract_return_value(), h8300_store_return_value(), h8300h_extract_return_value(), hack_disable_interpreter_exec(), handle_command(), handle_inferior_event(), hppa32_hpux_search_dummy_call_sequence(), hppa64_hpux_search_dummy_call_sequence(), hppa_frame_cache(), hppa_hpux_fetch_register(), hppa_hpux_push_dummy_code(), hppa_hpux_store_register(), hppa_hpux_supply_save_state(), hppa_linux_register_addr(), hppa_stub_frame_prev_register(), i386_linux_disable_btrace(), i386_linux_enable_btrace(), i386_linux_sigcontext_addr(), i386_stap_parse_special_token(), ia64_breakpoint_from_pc(), ia64_frame_prev_register(), ia64_hpux_fetch_rnat_register(), ia64_hpux_find_start_vma(), ia64_hpux_read_dynamic_info(), ia64_hpux_store_register(), ia64_linux_fetch_register(), ia64_linux_store_register(), ia64_memory_insert_breakpoint(), ia64_register_addr(), ia64_sigtramp_frame_prev_register(), ignore_command(), indirect_pieced_value(), inf_child_open(), inf_ptrace_attach(), inf_ptrace_detach(), inf_ptrace_fetch_register(), inf_ptrace_store_register(), inf_set_pid(), inf_signal(), inf_startup(), inf_validate_task_sc(), inferior_command(), info_auto_load_libthread_db(), info_auxv_command(), info_mach_exceptions_command(), info_mach_region_command(), info_macro_command(), info_osdata_command(), info_port_rights(), info_proc_cmd_1(), info_sharedlibrary_command(), info_spu_dma_command(), info_spu_event_command(), info_spu_mailbox_command(), info_spu_proxydma_command(), info_spu_signal_command(), info_task(), init_breakpoint_sal(), init_if_undefined_command(), init_stringtab(), insert_args(), insert_single_step_breakpoint(), install_variable(), integer_pow(), interp_set(), interpreter_exec_cmd(), interrupt_target_command(), invalid_synthetic_pointer(), invalid_thread_id_error(), iq2000_breakpoint_from_pc(), is_constructor_name(), is_destructor_name(), is_operator_name(), is_vtable_name(), isvoid_internal_fn(), java_primitive_type(), java_primitive_type_name(), java_type_from_name(), java_value_string(), jit_event_handler(), jit_read_code_entry(), jit_reader_load(), jit_reader_load_command(), jit_reader_unload_command(), jump_command(), kill_command(), kill_if_already_running(), kill_inferior_command(), lex_one_token(), libunwind_frame_cache(), libunwind_frame_prev_register(), linespec_lexer_lex_string(), linespec_parse_variable(), link_map_start(), linux_check_ptrace_features(), linux_core_info_proc(), linux_core_info_proc_mappings(), linux_fork_detach(), linux_info_proc(), linux_nat_attach(), linux_proc_pending_signals(), list_command(), lm32_store_return_value(), load_progress(), load_srec(), locexpr_describe_location_1(), locexpr_describe_location_piece(), loclist_describe_location(), longest_to_int(), lookup_cmd(), lookup_dwo_unit(), lookup_dwo_unit_in_dwp(), lookup_enum(), lookup_opencl_vector_type(), lookup_struct(), lookup_struct_elt_type(), lookup_struct_typedef(), lookup_symbol_aux(), lookup_template_type(), lookup_typename(), lookup_union(), lval_func_read(), lval_func_write(), lwp_to_thread(), m2_is_long_set_of_type(), m2_print_long_set(), m32c_m16c_address_to_pointer(), m32c_return_value(), m32r_create_inferior(), m32r_insert_breakpoint(), m32r_insert_watchpoint(), m32r_load(), m32r_open(), m32r_upload_command(), m32r_wait(), m68hc11_extract_return_value(), m68hc11_store_return_value(), macho_symfile_read(), macro_define_command(), macro_expand_command(), macro_expand_once(), macro_expand_once_command(), macro_undef_command(), maint_agent_printf_command(), maint_print_c_tdesc_cmd(), maintenance_expand_symtabs(), maintenance_info_program_spaces_command(), maintenance_print_msymbols(), maintenance_print_psymbols(), maintenance_print_symbols(), maintenance_set_profile_cmd(), maintenance_translate_address(), map_overlay_command(), mem_command(), memory_xfer_partial_1(), mep_return_value(), mep_store_return_value(), mi_catch_load_unload(), mi_cmd_ada_task_info(), mi_cmd_add_inferior(), mi_cmd_break_commands(), mi_cmd_break_insert_1(), mi_cmd_break_passcount(), mi_cmd_break_watch(), mi_cmd_catch_assert(), mi_cmd_catch_exception(), mi_cmd_data_evaluate_expression(), mi_cmd_data_list_changed_registers(), mi_cmd_data_list_register_names(), mi_cmd_data_list_register_values(), mi_cmd_data_read_memory(), mi_cmd_data_read_memory_bytes(), mi_cmd_data_write_memory(), mi_cmd_data_write_memory_bytes(), mi_cmd_data_write_register_values(), mi_cmd_disassemble(), mi_cmd_enable_frame_filters(), mi_cmd_enable_pretty_printing(), mi_cmd_enable_timings(), mi_cmd_env_cd(), mi_cmd_env_pwd(), mi_cmd_exec_run(), mi_cmd_execute(), mi_cmd_file_list_exec_source_file(), mi_cmd_file_list_exec_source_files(), mi_cmd_inferior_tty_show(), mi_cmd_info_os(), mi_cmd_interpreter_exec(), mi_cmd_list_features(), mi_cmd_list_target_features(), mi_cmd_list_thread_groups(), mi_cmd_remove_inferior(), mi_cmd_stack_info_depth(), mi_cmd_stack_info_frame(), mi_cmd_stack_list_args(), mi_cmd_stack_list_frames(), mi_cmd_stack_list_locals(), mi_cmd_stack_list_variables(), mi_cmd_stack_select_frame(), mi_cmd_symbol_list_lines(), mi_cmd_target_detach(), mi_cmd_target_file_delete(), mi_cmd_target_file_get(), mi_cmd_target_file_put(), mi_cmd_thread_info(), mi_cmd_thread_list_ids(), mi_cmd_thread_select(), mi_cmd_trace_define_variable(), mi_cmd_trace_find(), mi_cmd_trace_frame_collected(), mi_cmd_trace_list_variables(), mi_cmd_var_assign(), mi_cmd_var_create(), mi_cmd_var_delete(), mi_cmd_var_evaluate_expression(), mi_cmd_var_info_expression(), mi_cmd_var_info_num_children(), mi_cmd_var_info_path_expression(), mi_cmd_var_info_type(), mi_cmd_var_list_children(), mi_cmd_var_set_format(), mi_cmd_var_set_frozen(), mi_cmd_var_set_update_range(), mi_cmd_var_set_visualizer(), mi_cmd_var_show_attributes(), mi_cmd_var_show_format(), mi_cmd_var_update(), mi_getopt_1(), mi_parse(), mi_parse_format(), mi_parse_print_values(), microblaze_linux_memory_remove_breakpoint(), microblaze_push_dummy_call(), microblaze_push_dummy_code(), mips64_linux_register_addr(), mips_linux_register_addr(), mips_print_registers_info(), mips_read_fp_register_double(), mips_read_fp_register_single(), mips_readchar(), mipscoff_symfile_read(), monitor_create_inferior(), monitor_error(), monitor_fetch_register(), monitor_insert_breakpoint(), monitor_load(), monitor_open(), monitor_rcmd(), monitor_read_memory(), monitor_readchar(), monitor_remove_breakpoint(), monitor_supply_register(), msp430_gdbarch_init(), net_open(), no_chunk(), noprocess(), nto_node(), number_is_in_list(), open_and_init_dwp_file(), opencl_component_ref(), opencl_logical_not(), opencl_relop(), operator_chars(), operator_length_standard(), overlay_load_command(), pa64_solib_select(), pack_long(), pack_unsigned_long(), packet_command(), packet_ok(), parse_and_eval_type(), parse_auto_binary_operation(), parse_breakpoint_sals(), parse_cmd_to_aexpr(), parse_escape(), parse_expression(), parse_find_args(), parse_format_string(), parse_frame_specification_1(), parse_int_arg(), parse_number(), parse_pid_to_attach(), parse_probes(), parse_scrolling_args(), parse_static_tracepoint_marker_definition(), parse_string_or_char(), parse_trace_status(), pascal_type_print_varspec_prefix(), pascal_type_print_varspec_suffix(), pascal_val_print(), peek_die_abbrev(), pipe_windows_open(), pos_atr(), ppc_linux_displaced_step_location(), ppc_linux_memory_remove_breakpoint(), ppc_stap_parse_special_token(), prepare_for_detach(), print_go_string(), print_gp_register_row(), print_object_command(), print_octal_chars(), print_scalar_formatted(), print_source_lines_base(), print_subexp_standard(), print_thread_info(), print_type_scalar(), proc_trace_syscalls(), process_g_packet(), process_imported_unit_die(), processAttribute(), processInt(), procfs_attach(), procfs_create_inferior(), procfs_fetch_registers(), procfs_info_proc(), procfs_make_note_section(), procfs_open(), procfs_wait(), program_info(), ptrace_check(), push_expression_name(), push_qualified_expression_name(), put_frame_register(), putpkt_binary(), pwd_command(), py_mi_print_variables(), py_print_frame(), py_print_single_arg(), python_interactive_command(), query_if_trace_running(), quit_command(), read_addr_index_1(), read_attribute_value(), read_const(), read_cutu_die_from_dwo(), read_dbx_symtab(), read_fat_string_value(), read_full_die_1(), read_indirect_string_at_offset(), read_indirect_string_from_dwz(), read_next_line(), read_ofile_symtab(), read_one_sym(), read_pieced_value(), read_ptid(), read_str_index(), readchar(), record_btrace_call_history(), record_btrace_call_history_range(), record_btrace_info(), record_btrace_insn_history(), record_btrace_insn_history_range(), record_btrace_open(), record_full_check_insn_num(), record_full_core_open_1(), record_full_core_store_registers(), record_full_core_xfer_partial(), record_full_goto_bookmark(), record_full_goto_entry(), record_full_message(), record_full_open(), record_full_open_1(), record_full_registers_change(), record_full_restore(), record_full_save(), record_full_store_registers(), record_full_xfer_partial(), recurse_read_control_structure(), registers_info(), remote_buffer_add_bytes(), remote_buffer_add_int(), remote_buffer_add_string(), remote_delete_command(), remote_detach_1(), remote_disable_btrace(), remote_disable_tracepoint(), remote_disconnect(), remote_download_trace_state_variable(), remote_download_tracepoint(), remote_enable_btrace(), remote_enable_tracepoint(), remote_file_delete(), remote_file_get(), remote_file_put(), remote_fileio_reply(), remote_flash_done(), remote_flash_erase(), remote_get_command(), remote_get_noisy_reply(), remote_get_tib_address(), remote_get_trace_status(), remote_hostio_error(), remote_hostio_pread(), remote_hostio_readlink(), remote_insert_hw_breakpoint(), remote_notif_stop_ack(), remote_open_1(), remote_parse_stop_reply(), remote_put_command(), remote_rcmd(), remote_read_qxfer(), remote_resume(), remote_save_trace_data(), remote_search_memory(), remote_send(), remote_send_printf(), remote_set_circular_trace_buffer(), remote_set_disconnected_tracing(), remote_set_trace_notes(), remote_start_remote(), remote_static_tracepoint_marker_at(), remote_stop_ns(), remote_threads_info(), remote_trace_find(), remote_trace_init(), remote_trace_start(), remote_trace_stop(), remote_unescape_input(), remote_vcont_resume(), remote_verify_memory(), remote_xfer_partial(), remove_inferior_command(), report_agent_reqs_errors(), require_btrace(), require_not_optimized_out(), require_record_target(), require_rvalue(), reread_symbols(), resolve_sal_pc(), resolve_subexp(), restart_command(), restore_binary_file(), restore_command(), restore_section_callback(), resume(), return_command(), reverse_search_command(), rs6000_aix_core_xfer_shared_libraries_aix(), run_command_1(), run_one_inferior(), s390_push_dummy_call(), s390_return_value(), safe_read_sleb128(), safe_read_uleb128(), safe_skip_leb128(), save_bookmark_command(), save_breakpoints(), save_gdb_index_command(), scalar_binop(), scalar_relop(), scan_filename_with_cleanup(), scan_partial_symbols(), scope_info(), score3_adjust_pc_and_fetch_inst(), score7_breakpoint_from_pc(), score7_fetch_inst(), score7_malloc_and_get_memblock(), score_xfer_register(), search_struct_method(), search_symbols(), select_source_symtab(), selectors_info(), send_g_packet(), send_srec(), set_auto_load_cmd(), set_breakpoint_condition(), set_cp_abi_cmd(), set_dcache_line_size(), set_dcache_size(), set_default_source_symtab_and_line(), set_disable_randomization(), set_exec_direction_func(), set_ext_lang_command(), set_gdbarch_from_file(), set_history_size_command(), set_ignore_count(), set_input_radix_1(), set_internalvar(), set_memory_packet_size(), set_mips64_transfers_32bit_regs(), set_non_stop(), set_observer_mode(), set_output_radix_1(), set_per_command_cmd(), set_schedlock_func(), set_section_command(), set_sig_thread_cmd(), set_substitute_path_command(), set_system_call_allowed(), set_target_async_command(), set_target_permissions(), set_task_exc_port_cmd(), set_thread_exc_port_cmd(), setup_user_args(), sh64_compact_print_registers_info(), sh64_do_fp_register(), sh64_extract_return_value(), sh64_media_print_registers_info(), sh64_register_convert_to_raw(), sh64_register_convert_to_virtual(), sh_extract_return_value_nofpu(), sh_register_convert_to_raw(), sh_register_convert_to_virtual(), shell_escape(), show_substitute_path_command(), show_system_call_allowed(), show_user(), siginfo_value_read(), siginfo_value_write(), signal_command(), simple_overlay_update(), simple_read_overlay_table(), simple_search_memory(), simulator_command(), skip_delete_command(), skip_disable_command(), skip_enable_command(), skip_file_command(), skip_function_command(), skip_one_die(), sniff_core_bfd(), sol_thread_fetch_registers(), sol_thread_resume(), sol_thread_store_registers(), sol_thread_wait(), solib_add(), solib_aix_get_toc_value(), solib_bfd_fopen(), solib_bfd_open(), solib_map_sections(), som_solib_create_inferior_hook(), som_symtab_read(), source_script_with_search(), sources_info(), spu_bfd_open(), spu_return_value(), spu_software_single_step(), stabsect_build_psymtabs(), stap_parse_argument_1(), stap_parse_argument_conditionally(), stap_parse_register_operand(), stap_parse_single_operand(), start_command(), start_tracing(), startup_inferior(), steal_exc_port(), step_1(), step_once(), store_register(), store_register_using_P(), store_registers_using_G(), store_regs_user_thread(), strace_marker_decode_linespec(), string_to_core_addr(), struct_return_convention(), stub_gnu_ifunc_resolve_addr(), stub_gnu_ifunc_resolve_name(), substitute_args(), symbol_file_add_from_memory(), symbol_file_add_with_addrs(), symbol_file_clear(), symbol_file_command(), symfile_bfd_open(), sympy_value(), target_preopen(), target_require_runnable(), target_store_registers(), target_translate_tls_address(), target_write_memory_blocks(), target_xfer_partial(), task_command(), task_command_1(), tcatch_command(), teval_pseudocommand(), tfile_open(), tfile_read(), tfile_start(), tfile_xfer_partial(), tfind_1(), thread_apply_all_command(), thread_apply_command(), thread_command(), thread_db_find_new_threads_2(), thread_find_command(), thread_from_lwp(), thread_get_info_callback(), thread_name_command(), thread_takeover_sc_cmd(), thread_to_lwp(), tk_command(), tlb_value_read(), tlb_value_write(), to_fixed_array_type(), trace_dump_actions(), trace_error(), trace_find_command(), trace_find_line_command(), trace_find_outside_command(), trace_find_pc_command(), trace_find_range_command(), trace_find_tracepoint_command(), trace_pass_command(), trace_save(), trace_save_command(), trace_start_command(), trace_stop_command(), trace_variable_command(), traceframe_walk_blocks(), translate_register(), tui_enable(), type_name_no_tag_or_error(), ui_printf(), uinteger_pow(), undef_cmd_error(), unimplemented(), unk_lang_emit_char(), unk_lang_error(), unk_lang_print_type(), unk_lang_printchar(), unk_lang_printstr(), unk_lang_val_print(), unk_lang_value_print(), unmap_overlay_command(), unpack_long(), unset_substitute_path_command(), until_break_command(), until_command(), until_next_command(), up_silently_base(), update_dprintf_command_list(), update_dynamic_varobj_children(), update_search_result(), update_watchpoint(), user_select_syms(), validate(), validate_actionline(), validate_commands_for_breakpoint(), validate_comname(), validate_format(), validate_history_size(), validate_siginfo_access(), validate_trace_state_variable_name(), value_addr(), value_allocate_space_in_inferior(), value_args_as_decimal(), value_array(), value_as_double(), value_assign(), value_binop(), value_cast(), value_coerce_array(), value_coerce_function(), value_complement(), value_concat(), value_dynamic_cast(), value_equal(), value_find_oload_method_list(), value_from_double(), value_in(), value_ind(), value_less(), value_neg(), value_nsstring(), value_of_builtin_frame_ps_reg(), value_of_builtin_frame_sp_reg(), value_of_this(), value_of_variable(), value_one(), value_pos(), value_ptrdiff(), value_reinterpret_cast(), value_repeat(), value_slice(), value_struct_elt(), value_subscript(), value_subscript_packed(), value_subscripted_rvalue(), value_user_defined_cpp_op(), value_val_atr(), value_vector_widen(), value_x_binop(), value_x_unop(), varobj_create(), varobj_get_handle(), varobj_set_visualizer(), VEC(), vector_binop(), vector_info(), vector_relop(), view_command(), watch_command_1(), whatis_exp(), while_stepping_pseudocommand(), windows_attach(), windows_create_inferior(), windows_detach(), windows_make_so(), windows_open(), write_gcore_file(), write_name_assoc(), write_object_renaming(), write_obstack(), write_pieced_value(), write_psymbols(), write_psymtabs_to_index(), write_var_or_type(), xcoff_initial_scan(), xtensa_dump_tdep(), xtensa_register_read_masked(), xtensa_register_write_masked(), xtensa_window_interrupt_frame_cache(), yyerror(), and yylex().
void error_stream (struct ui_file * stream)
Definition at line 615 of file utils.c.
References error(), make_cleanup(), ui_file_xstrdup(), and xfree().
Referenced by insert_breakpoint_locations(), mi_cmd_execute(), and update_inserted_breakpoint_locations().
void fatal (const char * string, ...)
Definition at line 605 of file utils.c.
References throw_vfatal().
Referenced by internal_verror(), and quit().
void fprintf_filtered (struct ui_file * stream, const char * format, ...)
Definition at line 2314 of file utils.c.
References vfprintf_filtered().
Referenced by ada_dump_subexp_body(), ada_emit_char(), ada_print_array_index(), ada_print_floating(), ada_print_scalar(), ada_print_subexp(), ada_print_type(), ada_print_typedef(), ada_val_print_1(), ada_val_print_array(), ada_value_print(), annotate_error_begin(), arm_get_next_pc_raw(), arm_show_abi(), arm_show_fallback_mode(), arm_show_force_mode(), ax_print(), build_table(), c_print_typedef(), c_type_print_args(), c_type_print_base(), c_type_print_modifier(), c_type_print_template_args(), c_type_print_varspec_prefix(), c_type_print_varspec_suffix(), c_val_print(), c_value_print(), canonicalize_linespec(), complaints_show_value(), cp_print_class_member(), cp_print_value(), cp_print_value_fields(), cp_type_print_derivation_info(), cp_type_print_method_args(), debug_can_evaluate_probe_arguments(), debug_qf_dump(), debug_qf_expand_all_symtabs(), debug_qf_expand_symtabs_for_function(), debug_qf_expand_symtabs_matching(), debug_qf_expand_symtabs_with_fullname(), debug_qf_find_last_source_symtab(), debug_qf_find_pc_sect_symtab(), debug_qf_forget_cached_source_info(), debug_qf_has_symbols(), debug_qf_lookup_symbol(), debug_qf_map_matching_symbols(), debug_qf_map_symbol_filenames(), debug_qf_map_symtabs_matching_filename(), debug_qf_print_stats(), debug_qf_relocate(), debug_sym_compile_to_ax(), debug_sym_evaluate_probe_argument(), debug_sym_finish(), debug_sym_get_probe_argument_count(), debug_sym_init(), debug_sym_new_init(), debug_sym_offsets(), debug_sym_read(), debug_sym_read_linetable(), debug_sym_read_psymbols(), debug_sym_relocate(), debug_sym_relocate_probe(), debug_to_watchpoint_addr_within_range(), default_print_array_index(), default_print_one_register_info(), disassemble_dwarf_expression(), do_attach(), do_one_display(), do_show_command(), dump_insns(), dump_msymbols(), dump_prefix_expression(), dump_psymtab(), dump_raw_expression(), dump_subexp(), dump_subexp_body_standard(), dump_symtab_1(), error_clbk(), f77_print_array_1(), f_type_print_base(), f_type_print_varspec_prefix(), f_type_print_varspec_suffix(), f_val_print(), fbsd_find_memory_regions(), find_oload_champ(), fprint_target_auxv(), fputstr_filtered(), fputstrn_filtered(), gcore_command(), gcore_create_callback(), gdb_print_host_address(), generic_val_print(), get_core_registers(), get_set_value(), get_show_value(), gnuv3_print_method_ptr(), h8300_print_float_info(), h8300_print_register(), handle_inferior_event(), handle_vfork_child_exec_or_exit(), hardwire_print_tty_state(), help_all(), help_cmd(), help_list(), i387_print_float_info(), info_macro_command(), insert_bp_location(), java_print_value_fields(), java_type_print_base(), java_type_print_derivation_info(), java_value_print(), linux_child_follow_fork(), list_arg_or_local(), locexpr_describe_location_1(), locexpr_describe_location_piece(), loclist_describe_location(), m2_array(), m2_emit_char(), m2_enum(), m2_long_set(), m2_pointer(), m2_print_array_contents(), m2_print_long_set(), m2_print_typedef(), m2_print_unbounded_array(), m2_printstr(), m2_procedure(), m2_range(), m2_record_fields(), m2_ref(), m2_short_set(), m2_union(), m2_unknown(), m2_val_print(), m68hc11_print_register(), m68hc11_print_registers_info(), maintenance_print_msymbols(), mips_eabi_push_dummy_call(), mips_n32n64_push_dummy_call(), mips_o32_push_dummy_call(), mips_o64_push_dummy_call(), mips_print_fp_register(), mips_print_register(), mips_print_registers_info(), mt_registers_info(), pascal_object_print_value(), pascal_object_print_value_fields(), pascal_one_char(), pascal_print_func_args(), pascal_print_typedef(), pascal_printstr(), pascal_type_print_base(), pascal_type_print_derivation_info(), pascal_type_print_varspec_prefix(), pascal_type_print_varspec_suffix(), pascal_val_print(), pascal_value_print(), print_address_symbolic(), print_array_type(), print_binary_chars(), print_choices(), print_decimal_chars(), print_dynamic_range_bound(), print_enum_type(), print_exception(), print_field_values(), print_fixed_point_type(), print_float_info(), print_floating(), print_fp_register_row(), print_frame_arg(), print_frame_arg_vars(), print_frame_local_vars(), print_frame_nameless_args(), print_func_type(), print_gdb_configuration(), print_gdb_version(), print_gp_register_row(), print_help_for_command(), print_hex_chars(), print_i387_control_word(), print_i387_ext(), print_i387_status_word(), print_i387_value(), print_inferior_quit_action(), print_macro_definition(), print_octal_chars(), print_one_macro(), print_optional_low_bound(), print_partial_symbols(), print_range(), print_range_bound(), print_range_type(), print_record(), print_record_type(), print_recreate_exception(), print_scalar_formatted(), print_selected_record_field_types(), print_subexp_standard(), print_symbol(), print_type_scalar(), print_unchecked_union_type(), print_variable_and_value(), print_variable_at_address(), print_variant_clauses(), print_variant_part(), print_vector_info(), printf_c_string(), printf_decfloat(), printf_pointer(), printf_wide_c_string(), printstr(), quit_confirm(), range_error(), rank_one_type(), scope_info(), serial_baud_show_cmd(), sh64_do_cr_c_register_info(), sh64_do_fp_register(), sh64_do_pseudo_register(), sh64_do_register(), show_aarch64_debug(), show_addressprint(), show_always_inserted_mode(), show_annotation_level(), show_architecture(), show_asm_demangle(), show_async_command_editing_p(), show_auto_load_dir(), show_auto_load_gdb_scripts(), show_auto_load_local_gdbinit(), show_auto_load_safe_path(), show_auto_load_thread_db(), show_auto_solib_add(), show_automatic_hardware_breakpoints(), show_backtrace_limit(), show_backtrace_past_entry(), show_backtrace_past_main(), show_can_use_agent(), show_can_use_displaced_stepping(), show_can_use_hw_watchpoints(), show_case_command(), show_chars_per_line(), show_check_physname(), show_coerce_float_to_double_p(), show_condition_evaluation_mode(), show_confirm(), show_convenience(), show_dcache_enabled_p(), show_debug_auto_load(), show_debug_coff_pe_read(), show_debug_displaced(), show_debug_file_directory(), show_debug_infrun(), show_debug_linux_nat(), show_debug_symfile(), show_debug_timestamp(), show_debug_xml(), show_demangle(), show_demangling_style_names(), show_disable_randomization(), show_disassemble_next_line(), show_dsbt_debug(), show_dwarf2_always_disassemble(), show_dwarf2_max_cache_age(), show_entry_values_debug(), show_exec_direction_func(), show_exec_done_display_p(), show_expressiondebug(), show_ext_args(), show_filename_display_string(), show_follow_exec_mode_string(), show_follow_fork_mode_string(), show_fp_model(), show_frame_debug(), show_gdbarch_debug(), show_gnutarget_string(), show_history_expansion_p(), show_history_filename(), show_history_size(), show_host_charset_name(), show_inferior_tty_command(), show_info_verbose(), show_input_radix(), show_interactive_mode(), show_interrupt_sequence(), show_jit_debug(), show_language_command(), show_libthread_db_debug(), show_lines_per_page(), show_lines_to_list(), show_logging_filename(), show_logging_overwrite(), show_logging_redirect(), show_maint_show_all_tib(), show_maintenance_profile_p(), show_max_symbolic_offset(), show_max_user_call_depth(), show_mips_abi(), show_mips_compression(), show_non_stop(), show_objectprint(), show_observer_debug(), show_observer_mode(), show_opaque_type_resolution(), show_osabi(), show_output_radix(), show_overload_debug(), show_overload_resolution(), show_pagination_enabled(), show_parserdebug(), show_pascal_static_field_print(), show_pending_break_support(), show_powerpc_exact_watchpoints(), show_pp_source_pos(), show_prettyformat_arrays(), show_prettyformat_structs(), show_print_array_indexes(), show_print_inferior_events(), show_print_max(), show_print_symbol_filename(), show_print_thread_events(), show_print_type_methods(), show_print_type_typedefs(), show_prompt(), show_range_command(), show_range_stepping(), show_ravenscar_task_switching_command(), show_record_debug(), show_remote_debug(), show_remote_timeout(), show_repeat_count_threshold(), show_schedule_multiple(), show_scheduler_mode(), show_script_ext_mode(), show_sevenbit_strings(), show_solib_aix_debug(), show_solib_search_path(), show_spu_auto_flush_cache(), show_spu_stop_on_load(), show_stack_cache_enabled_p(), show_stapexpressiondebug(), show_static_field_print(), show_step_stop_if_no_debug(), show_stop_on_solib_events(), show_stop_print_at_null(), show_strict_type_checking(), show_symbol_print(), show_target_async_command(), show_target_charset_name(), show_target_file_system_kind_command(), show_target_wide_charset_name(), show_trust_readonly(), show_tui_active_border_mode(), show_tui_border_kind(), show_tui_border_mode(), show_unionprint(), show_unwind_on_signal_p(), show_unwind_on_terminating_exception_p(), show_user_1(), show_varobjdebug(), show_vtblprint(), show_watchdog(), show_write_files(), show_write_history_p(), skip_file_command(), skip_function_command(), ui_printf(), val_print(), val_print_array_elements(), val_print_invalid_address(), val_print_optimized_out(), val_print_packed_array_elements(), val_print_string(), val_print_type_code_flags(), val_print_unavailable(), value_check_printable(), and VEC().
void fprintf_symbol_filtered (struct ui_file * stream, const char * name, enum language lang, int arg_mode)
Definition at line 2440 of file utils.c.
References demangle, fputs_filtered(), language_def(), language_demangle(), and xfree().
Referenced by address_info(), cp_print_value_fields(), cp_type_print_method_args(), frame_info(), java_print_value_fields(), pascal_object_print_value_fields(), print_frame(), print_frame_arg(), and py_print_single_arg().
void fprintf_unfiltered (struct ui_file * stream, const char * format, ...)
Definition at line 2324 of file utils.c.
References vfprintf_unfiltered().
Referenced by _initialize_arm_tdep(), _initialize_sol_thread(), aarch64_analyze_prologue(), aarch64_dump_tdep(), aarch64_extract_return_value(), aarch64_handle_unaligned_watchpoint(), aarch64_linux_insert_hw_breakpoint(), aarch64_linux_insert_watchpoint(), aarch64_linux_prepare_to_resume(), aarch64_linux_remove_hw_breakpoint(), aarch64_linux_remove_watchpoint(), aarch64_push_dummy_call(), aarch64_return_value(), aarch64_show_debug_reg_state(), aarch64_store_return_value(), ada_lookup_struct_elt_type(), add_language(), add_path(), add_pe_exported_sym(), add_pe_forwarded_sym(), aix_thread_extra_thread_info(), allocate_psymtab(), allocate_symtab(), amd64_displaced_step_copy_insn(), amd64_displaced_step_fixup(), amd64_relocate_instruction(), amd64_windows_find_unwind_info(), amd64_windows_frame_decode_insns(), amd64_windows_frame_prev_register(), arm_analyze_prologue(), arm_copy_alu_imm(), arm_copy_alu_reg(), arm_copy_alu_shifted_reg(), arm_copy_b_bl_blx(), arm_copy_block_xfer(), arm_copy_bx_blx_reg(), arm_copy_copro_load_store(), arm_copy_extra_ld_st(), arm_copy_ldr_str_ldrb_strb(), arm_copy_preload(), arm_copy_preload_reg(), arm_copy_svc(), arm_copy_undef(), arm_copy_unmodified(), arm_copy_unpred(), arm_displaced_init_closure(), arm_dump_tdep(), arm_linux_cleanup_svc(), arm_linux_copy_svc(), arm_linux_displaced_step_copy_insn(), arm_pc_is_thumb(), arm_process_displaced_insn(), arm_process_record(), arm_push_dummy_call(), async_remote_interrupt(), async_remote_interrupt_twice(), auto_load_objfile_script(), auto_load_objfile_script_1(), auto_load_safe_path_vec_update(), avr_io_reg_read_command(), avr_scan_prologue(), bkpt_print_recreate(), bpstat_what(), build_table(), build_type_unit_groups(), can_dump_core(), cancel_breakpoint(), captured_main(), captured_mi_execute_command(), chain_candidate(), check_binary_download(), check_zombie_leaders(), cleanup_block_load_all(), cleanup_block_load_pc(), cleanup_block_store_pc(), cleanup_svc(), clear_proceed_status_thread(), context_switch(), create_debug_types_hash_table(), create_dwo_cu(), create_dwo_cu_reader(), create_dwo_unit_in_dwp_v1(), create_dwo_unit_in_dwp_v2(), create_new_frame(), create_sentinel_frame(), cris_dump_tdep(), cris_supply_gregset(), darwin_execvp(), dbx_psymtab_to_symtab_1(), dbx_read_symtab(), debug_print_register(), debug_reg_change_callback(), debug_to_can_accel_watchpoint_condition(), debug_to_can_run(), debug_to_can_use_hw_breakpoint(), debug_to_files_info(), debug_to_has_exited(), debug_to_insert_breakpoint(), debug_to_insert_exec_catchpoint(), debug_to_insert_fork_catchpoint(), debug_to_insert_hw_breakpoint(), debug_to_insert_vfork_catchpoint(), debug_to_insert_watchpoint(), debug_to_load(), debug_to_open(), debug_to_pid_to_exec_file(), debug_to_post_attach(), debug_to_post_startup_inferior(), debug_to_prepare_to_store(), debug_to_rcmd(), debug_to_region_ok_for_hw_watchpoint(), debug_to_remove_breakpoint(), debug_to_remove_exec_catchpoint(), debug_to_remove_fork_catchpoint(), debug_to_remove_hw_breakpoint(), debug_to_remove_vfork_catchpoint(), debug_to_remove_watchpoint(), debug_to_stop(), debug_to_stopped_by_watchpoint(), debug_to_stopped_data_address(), debug_to_terminal_inferior(), debug_to_terminal_info(), debug_to_terminal_init(), debug_to_terminal_ours(), debug_to_terminal_ours_for_output(), debug_to_terminal_save_ours(), debug_to_thread_architecture(), decode_add_sub_imm(), decode_adrp(), decode_b(), decode_bcond(), decode_br(), decode_cb(), decode_eret(), decode_movz(), decode_orr_shifted_register_x(), decode_ret(), decode_stp_offset(), decode_stp_offset_wb(), decode_stur(), decode_tb(), deprecated_debug_xfer_memory(), detach_callback(), disable_current_display(), displaced_read_reg(), displaced_step_dump_bytes(), displaced_step_fixup(), displaced_step_prepare(), displaced_step_restore(), displaced_write_reg(), dos_close(), dos_setbaudrate(), dprintf_print_recreate(), dsbt_current_sos(), dump_die_1(), dump_die_shallow(), dump_mem(), dump_psymtab(), dwarf2_build_psymtabs_hard(), elf_symfile_read(), enable_break(), enable_break2(), fetch_register(), fetch_regs_kernel_thread(), fetch_regs_user_thread(), filename_is_in_auto_load_safe_path_vec(), filename_is_in_pattern_1(), find_unwind_entry(), fixup_riprel(), fork_inferior(), fprint_dummy_frames(), fprint_field(), fprint_frame(), fprint_frame_id(), fprint_frame_type(), fputstr_unfiltered(), fputstrn_unfiltered(), frame_debug_got_null_frame(), frame_id_eq(), frame_id_inner(), frame_id_p(), frame_unwind_arch(), frame_unwind_pc_if_available(), frame_unwind_register_value(), frv_current_sos(), gdb_cntrl_c(), gdbarch_addr_bit(), gdbarch_addr_bits_remove(), gdbarch_address_class_name_to_type_flags(), gdbarch_address_class_type_flags(), gdbarch_address_class_type_flags_to_name(), gdbarch_address_to_pointer(), gdbarch_adjust_breakpoint_address(), gdbarch_auto_charset(), gdbarch_auto_wide_charset(), gdbarch_ax_pseudo_register_collect(), gdbarch_ax_pseudo_register_push_stack(), gdbarch_believe_pcc_promotion(), gdbarch_bfd_arch_info(), gdbarch_bits_big_endian(), gdbarch_breakpoint_from_pc(), gdbarch_byte_order(), gdbarch_byte_order_for_code(), gdbarch_call_dummy_location(), gdbarch_cannot_fetch_register(), gdbarch_cannot_step_breakpoint(), gdbarch_cannot_store_register(), gdbarch_char_signed(), gdbarch_coff_make_msymbol_special(), gdbarch_convert_from_func_ptr_addr(), gdbarch_convert_register_p(), gdbarch_core_info_proc(), gdbarch_core_pid_to_str(), gdbarch_core_read_description(), gdbarch_core_regset_sections(), gdbarch_core_xfer_shared_libraries(), gdbarch_core_xfer_shared_libraries_aix(), gdbarch_decr_pc_after_break(), gdbarch_deprecated_fp_regnum(), gdbarch_deprecated_function_start_offset(), gdbarch_displaced_step_copy_insn(), gdbarch_displaced_step_fixup(), gdbarch_displaced_step_free_closure(), gdbarch_displaced_step_hw_singlestep(), gdbarch_displaced_step_location(), gdbarch_double_bit(), gdbarch_double_format(), gdbarch_dummy_id(), gdbarch_dump(), gdbarch_dwarf2_addr_size(), gdbarch_dwarf2_reg_to_regnum(), gdbarch_ecoff_reg_to_regnum(), gdbarch_elf_make_msymbol_special(), gdbarch_elfcore_write_linux_prpsinfo(), gdbarch_fast_tracepoint_valid_at(), gdbarch_fetch_pointer_argument(), gdbarch_fetch_tls_load_module_address(), gdbarch_find_by_info(), gdbarch_find_memory_regions(), gdbarch_float_bit(), gdbarch_float_format(), gdbarch_fp0_regnum(), gdbarch_frame_align(), gdbarch_frame_args_skip(), gdbarch_frame_num_args(), gdbarch_frame_red_zone_size(), gdbarch_gcore_bfd_target(), gdbarch_gdb_signal_from_target(), gdbarch_gdb_signal_to_target(), gdbarch_gen_return_address(), gdbarch_get_longjmp_target(), gdbarch_get_siginfo_type(), gdbarch_get_syscall_number(), gdbarch_half_bit(), gdbarch_half_format(), gdbarch_has_dos_based_file_system(), gdbarch_has_global_breakpoints(), gdbarch_has_global_solist(), gdbarch_has_shared_address_space(), gdbarch_have_nonsteppable_watchpoint(), gdbarch_in_function_epilogue_p(), gdbarch_in_solib_return_trampoline(), gdbarch_info_proc(), gdbarch_inner_than(), gdbarch_int_bit(), gdbarch_integer_to_address(), gdbarch_iterate_over_objfiles_in_search_order(), gdbarch_long_bit(), gdbarch_long_double_bit(), gdbarch_long_double_format(), gdbarch_long_long_align_bit(), gdbarch_long_long_bit(), gdbarch_make_corefile_notes(), gdbarch_max_insn_length(), gdbarch_memory_insert_breakpoint(), gdbarch_memory_remove_breakpoint(), gdbarch_num_pseudo_regs(), gdbarch_num_regs(), gdbarch_osabi(), gdbarch_overlay_update(), gdbarch_pc_regnum(), gdbarch_pointer_to_address(), gdbarch_print_float_info(), gdbarch_print_insn(), gdbarch_print_registers_info(), gdbarch_print_vector_info(), gdbarch_process_record(), gdbarch_process_record_signal(), gdbarch_ps_regnum(), gdbarch_pseudo_register_read(), gdbarch_pseudo_register_read_value(), gdbarch_pseudo_register_write(), gdbarch_ptr_bit(), gdbarch_push_dummy_call(), gdbarch_push_dummy_code(), gdbarch_ravenscar_ops(), gdbarch_read_pc(), gdbarch_record_special_symbol(), gdbarch_register(), gdbarch_register_name(), gdbarch_register_reggroup_p(), gdbarch_register_sim_regno(), gdbarch_register_to_value(), gdbarch_register_type(), gdbarch_regset_from_core_section(), gdbarch_relocate_instruction(), gdbarch_remote_breakpoint_from_pc(), gdbarch_remote_register_number(), gdbarch_return_in_first_hidden_param_p(), gdbarch_return_value(), gdbarch_sdb_reg_to_regnum(), gdbarch_short_bit(), gdbarch_single_step_through_delay(), gdbarch_skip_main_prologue(), gdbarch_skip_permanent_breakpoint(), gdbarch_skip_prologue(), gdbarch_skip_solib_resolver(), gdbarch_skip_trampoline_code(), gdbarch_software_single_step(), gdbarch_sofun_address_maybe_missing(), gdbarch_solib_symbols_extension(), gdbarch_sp_regnum(), gdbarch_stab_reg_to_regnum(), gdbarch_stabs_argument_has_addr(), gdbarch_stap_gdb_register_prefix(), gdbarch_stap_gdb_register_suffix(), gdbarch_stap_integer_prefix(), gdbarch_stap_integer_suffix(), gdbarch_stap_is_single_operand(), gdbarch_stap_parse_special_token(), gdbarch_stap_register_indirection_prefix(), gdbarch_stap_register_indirection_suffix(), gdbarch_stap_register_prefix(), gdbarch_stap_register_suffix(), gdbarch_static_transform_name(), gdbarch_target_desc(), gdbarch_tdep(), gdbarch_unwind_pc(), gdbarch_unwind_sp(), gdbarch_update_p(), gdbarch_value_from_register(), gdbarch_value_to_register(), gdbarch_vbit_in_delta(), gdbarch_virtual_frame_pointer(), gdbarch_vtable_function_descriptors(), gdbarch_write_pc(), gdbsim_close(), gdbsim_create_inferior(), gdbsim_detach(), gdbsim_fetch_register(), gdbsim_files_info(), gdbsim_kill(), gdbsim_load(), gdbsim_mourn_inferior(), gdbsim_open(), gdbsim_resume_inferior(), gdbsim_store_register(), gdbsim_wait(), gdbsim_xfer_memory(), get_frame_func_if_available(), get_frame_id(), get_pending_status(), get_prev_frame_1(), get_prev_frame_raw(), getpkt_or_notif_sane_1(), handle_inferior_event(), handle_notification(), handle_redirections(), handle_syscall_event(), handle_vfork_child_exec_or_exit(), hardwire_raw(), hppa_dump_tdep(), hppa_fallback_frame_cache(), hppa_frame_cache(), i386_displaced_step_copy_insn(), i386_displaced_step_fixup(), i386_process_record(), i386_relocate_instruction(), ia64_dummy_id(), ia64_frame_this_id(), ia64_sigtramp_frame_this_id(), inf_ptrace_wait(), init_cutu_and_read_dies(), init_cutu_and_read_dies_no_follow(), insert_bp_location(), insert_breakpoint_locations(), insert_exception_resume_breakpoint(), insert_exception_resume_from_probe(), insert_longjmp_resume_breakpoint(), insert_step_resume_breakpoint_at_sal_1(), install_minimal_symbols(), jit_bfd_try_read_symtab(), jit_breakpoint_re_set_internal(), jit_frame_sniffer(), jit_inferior_init(), jit_read_descriptor(), jit_reader_load(), jit_reader_try_read_symtab(), jit_register_code(), jit_unwind_reg_set_impl(), kill_callback(), kill_wait_callback(), libunwind_load(), lin_lwp_attach_lwp(), linux_child_follow_fork(), linux_handle_extended_wait(), linux_handle_syscall_trap(), linux_nat_attach(), linux_nat_detach(), linux_nat_filter_event(), linux_nat_post_attach_wait(), linux_nat_resume(), linux_nat_stop_lwp(), linux_nat_wait(), linux_nat_wait_1(), linux_thread_alive(), lm_base(), lookup_dwo_cutu(), m32r_close(), m32r_create_inferior(), m32r_detach(), m32r_fetch_register(), m32r_insert_breakpoint(), m32r_insert_watchpoint(), m32r_kill(), m32r_mourn_inferior(), m32r_open(), m32r_prepare_to_store(), m32r_remove_breakpoint(), m32r_remove_watchpoint(), m32r_resume(), m32r_stop(), m32r_store_register(), m32r_wait(), m32r_xfer_memory(), maybe_clear_ignore_sigint(), mi_breakpoint_created(), mi_breakpoint_deleted(), mi_breakpoint_modified(), mi_cmd_var_create(), mi_command_param_changed(), mi_execute_cli_command(), mi_execute_command(), mi_field_fmt(), mi_field_string(), mi_inferior_added(), mi_inferior_appeared(), mi_inferior_exit(), mi_inferior_removed(), mi_memory_changed(), mi_new_thread(), mi_on_resume(), mi_open(), mi_out_buffered(), mi_output_running_pid(), mi_record_changed(), mi_solib_loaded(), mi_solib_unloaded(), mi_thread_exit(), mi_traceframe_changed(), mi_tsv_created(), mi_tsv_deleted(), mi_tsv_modified(), mips_check_lsi_error(), mips_common_breakpoint(), mips_dump_tdep(), mips_eabi_push_dummy_call(), mips_eabi_return_value(), mips_expect_download(), mips_expect_timeout(), mips_gdbarch_init(), mips_n32n64_push_dummy_call(), mips_n32n64_return_value(), mips_o32_push_dummy_call(), mips_o32_return_value(), mips_o64_push_dummy_call(), mips_o64_return_value(), mips_readchar(), mips_receive_packet(), mips_xfer_register(), mn10300_dump_tdep(), monitor_expect(), monitor_interrupt(), monitor_printf(), monitor_printf_noecho(), monitor_read_memory(), monitor_remove_breakpoint(), monitor_wait(), monitor_wait_filter(), monitor_write(), moxie_process_record(), net_open(), nios2_analyze_prologue(), open_and_init_dwo_file(), open_and_init_dwp_file(), packet_ok(), parser_fprintf(), pass_in_v(), pass_in_x(), pass_on_stack(), pdc_alloc(), pdc_dealloc(), pdc_read_data(), pdc_read_regs(), pdc_realloc(), pdc_symbol_addrs(), pdc_write_data(), pdc_write_regs(), pmon_check_ack(), pmon_makeb64(), pop_all_targets_above(), ppc_displaced_step_fixup(), prepare_for_detach(), prepare_to_proceed(), prepare_to_wait(), print_diff(), print_gdb_help(), print_one_detail_ranged_breakpoint(), print_recreate_catch_exec(), print_recreate_catch_fork(), print_recreate_catch_solib(), print_recreate_catch_syscall(), print_recreate_catch_vfork(), print_recreate_exception_catchpoint(), print_recreate_masked_watchpoint(), print_recreate_ranged_breakpoint(), print_recreate_thread(), print_recreate_watchpoint(), print_subexp_standard(), print_sys_errmsg(), print_target_wait_results(), proceed(), proceed_after_vfork_done(), process_psymtab_comp_unit_reader(), process_queue(), procfs_pidlist(), procfs_store_registers(), ptrace_check(), push_stop_reply(), push_target(), putpkt_binary(), puts_debug(), read_comp_units_from_section(), read_cutu_die_from_dwo(), read_dbx_symtab(), read_die_and_siblings(), read_frame(), read_full_die(), read_pe_exported_syms(), record_full_arch_list_add(), record_full_arch_list_add_end(), record_full_arch_list_add_mem(), record_full_arch_list_add_reg(), record_full_close(), record_full_core_kill(), record_full_exec_insn(), record_full_get_bookmark(), record_full_goto_bookmark(), record_full_open(), record_full_open_1(), record_full_restore(), record_full_save(), record_full_sig_handler(), record_full_wait_1(), record_full_xfer_partial(), record_linux_msghdr(), record_linux_sockaddr(), record_linux_system_call(), regcache_dump(), reggroups_dump(), reinit_frame_cache(), remote_notif_ack(), remote_notif_get_pending_events(), remote_notif_parse(), remote_notif_remove_queued_reply(), remote_stop(), report_initial_inferior(), reschedule(), resume(), resume_lwp(), resume_stopped_resumed_lwps(), rs6000_wait(), s390_displaced_step_fixup(), s390_remove_watchpoint(), save_breakpoints(), save_trace_state_variables(), sdireset_command(), sdistatus_command(), select_event_lwp(), send_g_packet(), send_srec(), ser_base_async(), serial_logchar(), serial_readchar(), serial_write(), set_logging_off(), set_logging_redirect(), shell_escape(), show_endian(), signal_catchpoint_print_recreate(), simple_displaced_step_copy_insn(), solib_aix_free_so(), solib_aix_get_toc_value(), stop_and_resume_callback(), stop_callback(), stop_stepping(), stop_wait_callback(), store_register(), store_regs_kernel_thread(), store_regs_user_thread(), tailcall_dump(), target_attach(), target_close(), target_core_of_thread(), target_create_inferior(), target_detach(), target_disconnect(), target_fileio_close(), target_fileio_open(), target_fileio_pread(), target_fileio_pwrite(), target_fileio_readlink(), target_fileio_unlink(), target_find_new_threads(), target_flash_done(), target_flash_erase(), target_follow_fork(), target_get_section_table(), target_info_proc(), target_insert_mask_watchpoint(), target_is_pushed(), target_kill(), target_mourn_inferior(), target_pass_signals(), target_program_signals(), target_remove_mask_watchpoint(), target_resume(), target_search_memory(), target_thread_address_space(), target_thread_alive(), target_verify_memory(), target_wait(), target_xfer_partial(), terminal_ours_1(), thumb2_copy_alu_imm(), thumb2_copy_b_bl_blx(), thumb2_copy_block_xfer(), thumb2_copy_copro_load_store(), thumb2_copy_load_literal(), thumb2_copy_load_reg_imm(), thumb2_copy_preload(), thumb2_copy_table_branch(), thumb_32bit_copy_undef(), thumb_analyze_prologue(), thumb_copy_16bit_ldr_literal(), thumb_copy_alu_reg(), thumb_copy_b(), thumb_copy_bx_blx_reg(), thumb_copy_cbnz_cbz(), thumb_copy_pc_relative_32bit(), thumb_copy_pop_pc_16bit(), thumb_copy_svc(), thumb_copy_unmodified_16bit(), thumb_copy_unmodified_32bit(), thumb_decode_pc_relative_16bit(), thumb_process_displaced_insn(), tracepoint_print_recreate(), tui_initialize_io(), uninstall_variable(), update_inserted_breakpoint_locations(), value_fetch_lazy(), varobj_create(), VEC(), verify_gdbarch(), vwarning(), wait_for(), wait_for_inferior(), wait_lwp(), watchpoint_value_print(), xcoff_psymtab_to_symtab_1(), xcoff_read_symtab(), xtensa_push_dummy_call(), and xtensa_verify_config().
void fprintfi_filtered (int spaces, struct ui_file * stream, const char * format, ...)
Definition at line 2337 of file utils.c.
References print_spaces_filtered(), and vfprintf_filtered().
Referenced by c_type_print_base(), f_type_print_base(), java_type_print_base(), m2_record_fields(), and pascal_type_print_base().
int fputc_filtered (int c, struct ui_file *)
Write a single char to output.
Definition at line 2141 of file utils.c.
References fputs_filtered().
Referenced by c_printchar(), disassemble_dwarf_expression(), field_separator(), pascal_type_print_method_args(), and putchar_filtered().
int fputc_unfiltered (int c, struct ui_file *)
Write a single char to output, unfiltered.
Definition at line 2132 of file utils.c.
References ui_file_write().
Referenced by canonicalize_linespec(), chain_candidate(), deprecated_debug_xfer_memory(), field_separator(), fputs_maybe_filtered(), mep_gdbarch_init(), mi_close(), mi_cmd_data_read_memory(), mi_open(), mips_receive_header(), putpkt_binary(), puts_debug(), remote_rcmd(), serial_logchar(), and target_xfer_partial().
void fputs_filtered (const char * , struct ui_file *)
Write a string to output, controlled by pagination.
Definition at line 2108 of file utils.c.
References fputs_maybe_filtered().
Referenced by ada_print_scalar(), ada_print_subexp(), ada_printchar(), ada_val_print_1(), address_info(), ATTRIBUTE_PRINTF(), ax_print(), c_print_type(), c_printstr(), c_type_print_base(), c_type_print_template_args(), c_val_print(), cli_text(), cp_print_class_member(), cp_print_static_field(), cp_print_value(), cp_print_value_fields(), cp_type_print_derivation_info(), cp_type_print_method_args(), dbx_psymtab_to_symtab_1(), default_print_one_register_info(), describe_other_breakpoints(), do_examine(), do_show_command(), dump_die_shallow(), dump_msymbols(), dump_prefix_expression(), dump_psymtab(), dump_subexp_body_standard(), dump_symtab_1(), f_print_type(), f_printchar(), f_printstr(), f_type_print_base(), f_val_print(), fprintf_symbol_filtered(), fputc_filtered(), fputstr_filtered(), fputstrn_filtered(), frame_info(), gdbtk_load_asm(), generic_emit_char(), generic_printstr(), generic_val_print(), getpkt_or_notif_sane_1(), gnuv3_print_method_ptr(), go_print_type(), help_cmd(), help_list(), i387_print_float_info(), info_checkpoints_command(), java_print_type(), java_print_value_fields(), java_printchar(), java_type_print_base(), java_type_print_derivation_info(), java_val_print(), java_value_print(), jump_command(), list_arg_or_local(), list_overlays_command(), m2_emit_char(), m2_enum(), m2_long_set(), m2_print_type(), m2_printchar(), m2_printstr(), m2_procedure(), m2_record_fields(), m2_type_name(), m2_typedef(), m2_unbounded_array(), m2_val_print(), m32r_load(), m32r_load_section(), m32r_upload_command(), macro_expand_command(), macro_expand_once_command(), maintenance_check_psymtabs(), maintenance_info_psymtabs(), mips_print_register(), mt_registers_info(), output_source_filename(), pascal_emit_char(), pascal_object_print_static_field(), pascal_object_print_value(), pascal_object_print_value_fields(), pascal_one_char(), pascal_print_func_args(), pascal_print_type(), pascal_printchar(), pascal_printstr(), pascal_type_print_base(), pascal_type_print_derivation_info(), pascal_type_print_method_args(), pascal_val_print(), print_address(), print_address_demangle(), print_address_symbolic(), print_any_exception(), print_decimal_floating(), print_doc_line(), print_enum_type(), print_exception(), print_field_values(), print_floating(), print_frame_arg(), print_func_type(), print_function_pointer_address(), print_go_string(), print_help_for_command(), print_hex_chars(), print_i387_control_word(), print_i387_ext(), print_i387_status_word(), print_longest(), print_macro_definition(), print_name_maybe_canonical(), print_octal_chars(), print_partial_symbols(), print_scalar_formatted(), print_spaces_filtered(), print_subexp_standard(), print_symbol(), print_symbol_info(), print_type_scalar(), print_unpacked_pointer(), print_variable_at_address(), printstr(), psymtab_to_symtab_1(), puts_filtered(), puts_filtered_tabular(), py_print_single_arg(), read_frame(), say_where(), sh64_do_fp_register(), sh64_do_register(), show_disable_randomization(), show_user_1(), target_command(), tui_make_status_line(), val_print_string(), val_print_type_code_flags(), valprint_check_validity(), and xcoff_psymtab_to_symtab_1().
static void fputs_maybe_filtered (const char * linebuffer, struct ui_file * stream, int filter) [static]
Definition at line 2002 of file utils.c.
References batch_flag, chars_printed, fputc_unfiltered(), fputs_unfiltered(), gdb_stdout, interp_ui_out(), prompt_for_continue(), top_level_interpreter(), ui_out_is_mi_like_p(), wrap_buffer, wrap_column, and wrap_here().
Referenced by fputs_filtered(), and vfprintf_maybe_filtered().
void fputstr_filtered (const char * str, int quoter, struct ui_file * stream)
Definition at line 1555 of file utils.c.
References fprintf_filtered(), fputs_filtered(), and printchar().
Referenced by do_show_command(), and print_packet().
void fputstr_unfiltered (const char * str, int quoter, struct ui_file * stream)
Definition at line 1562 of file utils.c.
References fprintf_unfiltered(), fputs_unfiltered(), and printchar().
Referenced by mi_cmd_execute(), mi_field_string(), and mi_print_exception().
void fputstrn_filtered (const char * str, int n, int quoter, struct ui_file * stream)
Definition at line 1569 of file utils.c.
References fprintf_filtered(), fputs_filtered(), and printchar().
void fputstrn_unfiltered (const char * str, int n, int quoter, struct ui_file * stream)
Definition at line 1579 of file utils.c.
References fprintf_unfiltered(), fputs_unfiltered(), and printchar().
Referenced by escape_buffer(), and mi_console_raw_packet().
void free ()
Referenced by dict_free(), gdb_get_blocks(), gdb_listfiles(), gdb_loadfile(), gdb_loc(), gdb_selected_block(), gdb_selected_frame(), gdbtk_annotate_signal(), gdbtk_ignorable_warning(), gdbtk_init(), gdbtk_load_hash(), gdbtk_load_source(), gdbtk_query(), gdbtk_readline_begin(), gdbtk_set_hook(), gdbtk_source_start_file(), gdbtk_two_elem_cmd(), gdbtk_warning(), register_data_with_cleanup(), TclDebug(), tracepoint_exists(), windows_create_inferior(), windows_make_so(), and xfree().
void free_current_contents (void * ptr)
Definition at line 524 of file utils.c.
References _, internal_error(), and xfree().
Referenced by ada_read_renaming_var_value(), agent_eval_command_one(), c_parse(), call_site_find_chain_1(), captured_mi_execute_command(), coff_symfile_read(), compute_enum_values(), dbx_read_symtab(), displaced_step_prepare(), display_gdb_prompt(), dwarf2_add_member_fn(), elf_rel_plt_read(), elfstab_build_psymtabs(), encode_actions_1(), execute_control_command(), expand(), file_is_auto_load_safe(), find_command(), find_symbol_in_baseclass(), gather_arguments(), gdb_eval(), info_macro_command(), info_macros_command(), init_if_undefined_command(), macro_define_command(), macro_expand_command(), macro_expand_once_command(), maintenance_print_type(), mi_cmd_data_evaluate_expression(), mi_cmd_trace_frame_collected(), mi_cmd_var_create(), mi_cmd_var_delete(), output_command_const(), parse_and_eval(), parse_and_eval_address(), parse_and_eval_long(), parse_find_args(), parse_to_comma_and_eval(), print_address_symbolic(), print_command_1(), print_object_command(), print_variable_or_computed(), rbreak_command(), read_array_type(), read_pe_exported_syms(), read_pieced_value(), read_string(), remote_query_supported(), remote_threads_info(), set_command(), simple_search_memory(), stap_parse_argument(), trace_dump_actions(), ui_printf(), validate_actionline(), value_get_print_value(), whatis_exp(), write_pieced_value(), x_command(), and xml_fetch_content_from_file().
const char* gdb_bfd_errmsg (bfd_error_type error_tag, char ** matching)
A wrapper for bfd_errmsg to produce a more helpful error message in the case of bfd_error_file_ambiguously recognized.
Parameters:
error_tag
matching if non-NULL, is the corresponding argument to bfd_check_format_matches, and will be freed.
Definition at line 3373 of file utils.c.
References AMBIGUOUS_MESS1, AMBIGUOUS_MESS2, make_cleanup(), p, xfree(), and xmalloc().
Referenced by exec_file_attach().
char** gdb_buildargv (const char * s)
Call libiberty's buildargv, and return the result. If buildargv fails due to out-of-memory, call nomem. Therefore, the returned value is guaranteed to be non-NULL, unless the parameter itself is NULL.
Definition at line 3338 of file utils.c.
References malloc_failure().
Referenced by add_inferior_command(), add_path(), add_symbol_file_command(), alias_command(), backtrace_command(), clone_inferior_command(), delete_trace_variable_command(), exec_file_command(), extended_remote_run(), gdbpy_string_to_argv(), gdbsim_create_inferior(), gdbsim_load(), gdbsim_open(), generic_load(), handle_command(), interpreter_exec_cmd(), maintenance_expand_symtabs(), maintenance_print_msymbols(), maintenance_print_psymbols(), maintenance_print_symbols(), monitor_load(), pipe_windows_open(), procfs_info_proc(), remote_delete_command(), remote_get_command(), remote_put_command(), set_substitute_path_command(), show_substitute_path_command(), symbol_file_command(), trace_save_command(), unset_substitute_path_command(), and xdb_handle_command().
int gdb_filename_fnmatch (const char * pattern, const char * string, int flags)
Definition at line 3634 of file utils.c.
References gdb_assert.
Referenced by filename_is_in_pattern_1().
void gdb_print_host_address (const void * addr, struct ui_file * stream)
Display the host ADDR on STREAM formatted as ``0xx''.
Definition at line 1107 of file utils.c.
References fprintf_filtered(), and host_address_to_string().
Referenced by ada_dump_subexp_body(), dump_fn_fieldlists(), dump_objfile(), dump_prefix_expression(), dump_psymtab(), dump_psymtabs_for_objfile(), dump_raw_expression(), dump_subexp_body_standard(), dump_symtab_1(), fprint_dummy_frames(), fprint_frame(), print_cplus_stuff(), print_symbol(), and recursive_dump_type().
char* gdb_realpath (const char * filename)
Get the canonicalized absolute pathname for the given filename, returning the result in freshly-allocated memory. This is basically just a host-independent wrapper for realpath().
Parameters:
filename the filename to get a path for
Definition at line 3069 of file utils.c.
References len.
Referenced by auto_load_objfile_script(), auto_load_safe_path_vec_update(), captured_main(), dw2_get_real_path(), dwarf2_get_dwz_file(), exec_file_attach(), filename_is_in_auto_load_safe_path_vec(), find_and_open_source(), iterate_over_symtabs(), maintenance_print_msymbols(), nto_find_and_open_solib(), openp(), and try_thread_db_load().
LONGEST gdb_sign_extend (LONGEST value, int bit)
Definition at line 3174 of file utils.c.
References gdb_assert, and LONGEST.
Referenced by indirect_pieced_value().
static char* get_cell (void) [static]
Definition at line 2688 of file utils.c.
References CELLSIZE, and NUMCELLS.
Referenced by core_addr_to_string(), core_addr_to_string_nz(), decimal2str(), hex_string(), hex_string_custom(), host_address_to_string(), octal2str(), phex(), and phex_nz().
struct timeval get_prompt_for_continue_wait_time (void) [read]
Definition at line 1864 of file utils.c.
Referenced by report_command_stats().
char* get_regcomp_error (int code, regex_t * rx)
Definition at line 1133 of file utils.c.
References xmalloc().
Referenced by add_solib_catchpoint(), apropos_command(), compile_rx_or_error(), and search_symbols().
void* hashtab_obstack_allocate (void * data, size_t size, size_t count)
Definition at line 3192 of file utils.c.
References memset().
Referenced by allocate_dwo_file_hash_table(), allocate_dwo_unit_table(), allocate_dwp_loaded_cutus_table(), allocate_signatured_type_table(), allocate_type_unit_groups_table(), call_site_find_chain_1(), create_copied_types_hash(), dwarf2_add_dependence(), elf_gnu_ifunc_record_cache(), func_verify_no_selftailcall(), load_full_comp_unit_reader(), load_partial_dies(), read_call_site_scope(), read_signatured_type_reader(), and set_die_type().
char* hex_string (LONGEST)
Return a string that contains a number formatted as a hex string.
Definition at line 2929 of file utils.c.
References CELLSIZE, get_cell(), phex_nz(), and xsnprintf().
Referenced by amd64_relocate_instruction(), append_ocl_sos(), bpfinishpy_init(), create_addrmap_from_index(), create_debug_types_hash_table(), create_dwo_cu_reader(), create_dwo_unit_in_dwp_v1(), create_dwo_unit_in_dwp_v2(), create_new_frame(), create_tracepoint_from_upload(), debug_qf_find_pc_sect_symtab(), dump_die_shallow(), edit_command(), find_unwind_entry(), follow_die_sig(), fprint_field(), fprint_frame(), frame_unwind_pc_if_available(), get_frame_func_if_available(), get_function_name(), get_signatured_type(), go32_pte_for_address(), i386_relocate_instruction(), int_string(), linux_core_info_proc_mappings(), linux_info_proc(), list_command(), load_progress(), lookup_dwo_cutu(), lookup_dwp_signatured_type(), maintenance_translate_address(), make_blockvector(), mi_cmd_var_create(), paddress(), parse_partial_symbols(), pdc_read_data(), pdc_read_regs(), pdc_symbol_addrs(), pdc_write_data(), pdc_write_regs(), print_symbol(), process_one_symbol(), process_queue(), read_attribute_value(), read_cutu_die_from_dwo(), read_dbx_symtab(), remote_parse_stop_reply(), rs6000_ptrace64(), scope_info(), simple_search_memory(), spu_current_sos(), target_flash_erase(), target_search_memory(), and unwind_command().
char* hex_string_custom (LONGEST num, int width)
Definition at line 2942 of file utils.c.
References _, CELLSIZE, get_cell(), internal_error(), memset(), and phex_nz().
Referenced by breakpoint_adjustment_warning(), dsbt_current_sos(), enable_break(), enable_break2(), frv_current_sos(), i387_print_float_info(), int_string(), lm_base(), maint_print_section_info(), mem_info_command(), print_core_address(), print_i387_control_word(), print_i387_status_word(), print_msymbol_info(), and print_section_info().
const char* host_address_to_string (const void * addr)
Definition at line 3060 of file utils.c.
References CELLSIZE, get_cell(), phex_nz(), and xsnprintf().
Referenced by allocate_psymtab(), allocate_symtab(), c_print_token(), darwin_xfer_partial(), debug_can_evaluate_probe_arguments(), debug_qf_expand_symtabs_matching(), debug_qf_find_pc_sect_symtab(), debug_qf_map_matching_symbols(), debug_qf_map_symbol_filenames(), debug_qf_map_symtabs_matching_filename(), debug_qf_relocate(), debug_sym_compile_to_ax(), debug_sym_evaluate_probe_argument(), debug_sym_get_probe_argument_count(), debug_sym_offsets(), debug_sym_relocate(), debug_sym_relocate_probe(), debug_to_can_accel_watchpoint_condition(), debug_to_insert_watchpoint(), debug_to_remove_watchpoint(), debug_to_thread_architecture(), gdb_print_host_address(), gdbarch_dump(), gdbarch_find_by_info(), gdbarch_register(), gdbarch_update_p(), gdbsim_xfer_memory(), get_register_types(), gnu_xfer_memory(), handle_exception(), handle_load_dll(), handle_unload_dll(), ia64_frame_this_id(), ia64_sigtramp_frame_this_id(), lookup_dwo_cutu(), maintenance_check_symtabs(), maintenance_info_psymtabs(), maintenance_info_symtabs(), monitor_read_memory(), print_one_bfd(), record_full_arch_list_add(), record_full_exec_insn(), record_full_wait_1(), target_xfer_partial(), unwind_command(), VEC(), xtensa_push_dummy_call(), and xtensa_unwind_pc().
static int host_char_to_target (struct gdbarch * gdbarch, int c, int * target_c) [static]
Definition at line 1398 of file utils.c.
References convert_between_encodings(), do_cleanups(), host_charset(), make_cleanup_obstack_free(), target_charset(), and translit_none.
Referenced by parse_escape().
void init_page_info (void)
Definition at line 1643 of file utils.c.
References batch_flag, gdb_stdout, set_screen_size(), set_width(), tgetnum(), tui_get_command_dimension(), and ui_file_isatty().
Referenced by initialize_utils(), set_batch_flag_and_make_cleanup_restore_page_info(), and set_width().
void initialize_utils (void)
Definition at line 2623 of file utils.c.
References _, add_com(), add_setshow_boolean_cmd(), add_setshow_uinteger_cmd(), class_maintenance, class_support, init_page_info(), pagination_off_command(), pagination_on_command(), set_height_command(), set_width_command(), setdebuglist, setlist, setprintlist, show_chars_per_line(), show_debug_timestamp(), show_lines_per_page(), show_pagination_enabled(), show_sevenbit_strings(), showdebuglist, showlist, showprintlist, and xdb_commands.
Referenced by gdb_init().
char* int_string (LONGEST val, int radix, int is_signed, int width, int use_c_format)
Convert VAL to a numeral in the given radix. For radix 10, IS_SIGNED may be true, indicating a signed quantity; otherwise VAL is interpreted as unsigned. If WIDTH is supplied, it is the minimum width (0-padded if needed). USE_C_FORMAT means to use C format in all cases. If it is false, then 'x' and 'o' formats do not include a prefix (0x or leading 0).
Definition at line 2962 of file utils.c.
References _, decimal2str(), hex_string(), hex_string_custom(), internal_error(), and octal2str().
Referenced by ada_print_type(), c_describe_child(), mi_inferior_exit(), and print_longest().
void internal_error (const char * file, int line, const char * string, ...)
Definition at line 824 of file utils.c.
References internal_verror().
void internal_verror (const char * file, int line, const char * fmt, va_list ap)
Definition at line 817 of file utils.c.
References _, and fatal().
Referenced by internal_error().
void internal_vwarning (const char * file, int line, const char * fmt, va_list ap)
Definition at line 838 of file utils.c.
Referenced by internal_warning().
void internal_warning (const char * file, int line, const char * string, ...)
Definition at line 844 of file utils.c.
References internal_vwarning().
Referenced by maintenance_internal_warning(), and restore_my_cleanups().
static int is_digit_in_base (unsigned char digit, int base) [static]
Definition at line 3221 of file utils.c.
Referenced by strtoulst().
char* ldirname (const char * filename)
Definition at line 3313 of file utils.c.
References memcpy(), and xmalloc().
Referenced by _initialize_python(), dwarf2_get_dwz_file(), file_read_description_xml(), and find_file_and_directory().
struct cleanup* make_bpstat_clear_actions_cleanup (void) [read]
Definition at line 3441 of file utils.c.
References do_bpstat_clear_actions_cleanup(), and make_cleanup().
Referenced by bpstat_do_actions(), execute_command(), fetch_inferior_event(), and inferior_event_handler().
struct cleanup* make_cleanup_bfd_unref (bfd * abfd) [read]
Definition at line 238 of file utils.c.
References do_bfd_close_cleanup(), and make_cleanup().
Referenced by bfd_openr_with_cleanup(), bfd_openw_with_cleanup(), coff_symfile_read(), core_open(), darwin_bfd_open(), darwin_solib_get_all_image_info_addr_at_init(), elf_symfile_read(), gdb_load_info(), generic_load(), jit_bfd_try_read_symtab(), load_srec(), m32r_load(), m32r_upload_command(), macho_add_oso_symfile(), macho_symfile_read(), read_symbols(), reread_symbols(), solib_bfd_open(), spu_symbol_file_add_from_memory(), symbol_file_add(), symbol_file_add_from_memory(), and symfile_bfd_open().
struct cleanup* make_cleanup_close (int fd) [read]
Definition at line 252 of file utils.c.
References do_close_cleanup(), make_cleanup_dtor(), xfree(), and xmalloc().
Referenced by forward_search_command(), get_filename_and_charpos(), iterate_over_mappings(), procfs_open(), procfs_pidlist(), and reverse_search_command().
struct cleanup* make_cleanup_dyn_string_delete (dyn_string_t arg) [read]
Definition at line 226 of file utils.c.
References do_dyn_string_delete(), and make_cleanup().
Referenced by alias_command().
struct cleanup* make_cleanup_fclose (FILE * file) [read]
Definition at line 273 of file utils.c.
References do_fclose_cleanup(), and make_cleanup().
Referenced by auto_load_objfile_script_1(), fbsd_find_memory_regions(), fopen_with_cleanup(), forward_search_command(), linux_proc_pending_signals(), print_source_lines_base(), remote_file_get(), remote_file_put(), reverse_search_command(), source_script_with_search(), and xml_fetch_content_from_file().
struct cleanup* make_cleanup_free_char_ptr_vec (VEC(char_ptr)* char_ptr_vec) [read]
Definition at line 3506 of file utils.c.
References do_free_char_ptr_vec(), and make_cleanup().
Referenced by add_path(), auto_load_objfile_script_1(), build_id_to_debug_bfd(), find_separate_debug_file(), openp(), and thread_db_load_search().
struct cleanup* make_cleanup_free_section_addr_info (struct section_addr_info * addrs) [read]
Definition at line 335 of file utils.c.
References do_free_section_addr_info(), and make_cleanup().
Referenced by addr_info_make_relative(), jit_bfd_try_read_symtab(), and symbol_file_add_separate().
struct cleanup* make_cleanup_free_so (struct so_list * so) [read]
Definition at line 488 of file utils.c.
References do_free_so(), and make_cleanup().
Referenced by svr4_read_so_list().
struct cleanup* make_cleanup_freeargv (char ** arg) [read]
Definition at line 214 of file utils.c.
References do_freeargv(), and make_cleanup().
Referenced by add_inferior_command(), add_symbol_file_command(), alias_command(), backtrace_command(), clone_inferior_command(), delete_trace_variable_command(), exec_file_command(), gdbsim_create_inferior(), gdbsim_load(), generic_load(), handle_command(), interpreter_exec_cmd(), maintenance_expand_symtabs(), maintenance_print_msymbols(), maintenance_print_psymbols(), maintenance_print_symbols(), monitor_load(), pipe_windows_open(), procfs_info_proc(), remote_delete_command(), remote_get_command(), remote_put_command(), set_substitute_path_command(), show_substitute_path_command(), symbol_file_command(), trace_save_command(), unset_substitute_path_command(), and xdb_handle_command().
struct cleanup* make_cleanup_htab_delete (htab_t htab) [read]
Definition at line 409 of file utils.c.
References do_htab_delete_cleanup(), and make_cleanup().
Referenced by apply_frame_filter(), call_site_find_chain_1(), dw2_expand_symtabs_matching(), dw2_map_symbol_filenames(), dwarf_decode_macros(), func_verify_no_selftailcall(), gnuv3_print_vtable(), VEC(), and write_psymtabs_to_index().
struct cleanup* make_cleanup_obstack_free (struct obstack * obstack) [read]
Definition at line 291 of file utils.c.
References do_obstack_free(), and make_cleanup().
Referenced by c_parse(), call_site_find_chain_1(), create_addrmap_from_index(), dwarf2_build_psymtabs_hard(), evaluate_subexp_c(), func_verify_no_selftailcall(), generic_emit_char(), generic_printstr(), go_parse(), host_char_to_target(), indirect_pieced_value(), linux_make_mappings_corefile_notes(), printf_wide_c_string(), signal_catchpoint_print_one(), ui_printf(), and write_psymtabs_to_index().
struct cleanup* make_cleanup_restore_current_language (void) [read]
Definition at line 507 of file utils.c.
References current_language, do_restore_current_language(), language_defn::la_language, and make_cleanup().
Referenced by parse_exp_in_context_1().
struct cleanup* make_cleanup_restore_integer (int * variable) [read]
Definition at line 358 of file utils.c.
References make_cleanup_dtor(), restore_integer(), restore_integer_closure::value, restore_integer_closure::variable, xfree(), and xmalloc().
Referenced by arm_insert_single_step_breakpoint(), c_parse(), checkpoint_command(), do_one_display(), exec_continue(), execute_command_to_string(), execute_user_command(), fetch_inferior_event(), go_parse(), if_command(), make_cleanup_restore_traceframe_number(), make_cleanup_restore_uinteger(), mi_cmd_execute(), mi_cmd_var_assign(), prepare_for_detach(), prevent_dont_repeat(), record_full_gdb_operation_disable_set(), set_batch_flag_and_make_cleanup_restore_page_info(), setup_breakpoint_reporting(), and while_command().
struct cleanup* make_cleanup_restore_page_info (void) [read]
Definition at line 1706 of file utils.c.
References do_restore_page_info_cleanup(), make_cleanup(), and make_cleanup_restore_uinteger().
Referenced by set_batch_flag_and_make_cleanup_restore_page_info().
struct cleanup* make_cleanup_restore_ui_file (struct ui_file ** variable) [read]
Definition at line 432 of file utils.c.
References do_restore_ui_file(), make_cleanup_dtor(), restore_ui_file_closure::value, restore_ui_file_closure::variable, and xfree().
Referenced by execute_command_to_string().
struct cleanup* make_cleanup_restore_uinteger (unsigned int * variable) [read]
Definition at line 373 of file utils.c.
References make_cleanup_restore_integer().
Referenced by make_cleanup_restore_page_info().
struct cleanup* make_cleanup_ui_file_delete (struct ui_file * arg) [read]
Definition at line 303 of file utils.c.
References do_ui_file_delete(), and make_cleanup().
Referenced by ada_print_floating(), ada_varobj_get_value_image(), ada_varobj_scalar_image(), bppy_get_commands(), do_show_command(), dump_insns(), escape_buffer(), eval_command(), execute_command_to_string(), gdb_disassembly(), gdb_eval(), gdb_update_mem(), get_register(), handle_redirections(), insert_breakpoint_locations(), list_arg_or_local(), maintenance_print_architecture(), maintenance_print_dummy_frames(), maintenance_print_msymbols(), maintenance_print_psymbols(), maintenance_print_reggroups(), maintenance_print_symbols(), mi_cmd_data_evaluate_expression(), mi_cmd_data_read_memory(), mi_cmd_execute(), output_register(), print_breakpoint_location(), print_frame(), print_frame_arg(), print_frame_args(), print_it_watchpoint(), print_one_detail_ranged_breakpoint(), print_return_value(), print_variable_or_computed(), py_print_single_arg(), py_print_type(), py_print_value(), quit_confirm(), reattach_breakpoints(), regcache_print(), save_breakpoints(), set_logging_redirect(), type_to_string(), typy_str(), update_inserted_breakpoint_locations(), value_get_print_value(), verify_gdbarch(), and xtensa_verify_config().
struct cleanup* make_cleanup_ui_out_redirect_pop (struct ui_out * uiout) [read]
Definition at line 323 of file utils.c.
References do_ui_out_redirect_pop(), and make_cleanup().
Referenced by execute_command_to_string().
struct cleanup* make_cleanup_unpush_target (struct target_ops * ops) [read]
Definition at line 391 of file utils.c.
References do_unpush_target(), and make_cleanup().
Referenced by inf_ptrace_attach(), and inf_ptrace_create_inferior().
struct cleanup* make_cleanup_value_free (struct value * value) [read]
Definition at line 470 of file utils.c.
References do_value_free(), and make_cleanup().
Referenced by dwarf2_evaluate_loc_desc_full().
struct cleanup* make_cleanup_value_free_to_mark (struct value * mark) [read]
Definition at line 454 of file utils.c.
References do_value_free_to_mark(), and make_cleanup().
Referenced by dwarf2_evaluate_loc_desc_full(), dwarf2_loc_desc_needs_frame(), execute_stack_op(), and prepare_execute_command().
struct cleanup* make_regfree_cleanup (regex_t * r) [read]
Definition at line 1124 of file utils.c.
References do_regfree_cleanup(), and make_cleanup().
Referenced by apropos_command(), compile_rx_or_error(), and search_symbols().
PTR malloc ()
Referenced by gdb_loadfile(), gdbtk_two_elem_cmd(), simple_search_memory(), xmalloc(), and xrealloc().
void malloc_failure (long size)
Definition at line 1062 of file utils.c.
References _, and internal_error().
Referenced by gdb_buildargv(), xcalloc(), xmalloc(), xml_fetch_content_from_file(), and xrealloc().
int myread (int desc, char * addr, int len)
Definition at line 1080 of file utils.c.
References len, and read().
Referenced by find_source_lines().
char* n_spaces (int n)
Definition at line 2405 of file utils.c.
References xfree(), and xmalloc().
Referenced by cp_print_value_fields(), java_print_value_fields(), java_value_print(), pascal_object_print_value_fields(), print_field_values(), print_spaces(), print_spaces_filtered(), print_variable_and_value(), val_print_array_elements(), and val_print_packed_array_elements().
int nquery (const char * ctlstr, ...)
Definition at line 1346 of file utils.c.
Referenced by create_breakpoint(), skip_file_command(), and skip_function_command().
static char* octal2str (ULONGEST addr, int width) [static]
Definition at line 2801 of file utils.c.
References _, CELLSIZE, get_cell(), internal_error(), and xsnprintf().
Referenced by int_string().
const char* paddress (struct gdbarch * gdbarch, CORE_ADDR addr)
Convert CORE_ADDR to string in platform-specific manner. This is usually formatted similar to 0xlx.
Definition at line 2699 of file utils.c.
References gdbarch_addr_bit(), hex_string(), and HOST_CHAR_BIT.
Referenced by aarch64_dump_tdep(), aarch64_push_dummy_call(), ada_val_print_1(), add_symbol_file_command(), add_vsyscall_page(), address_info(), alpha_heuristic_proc_start(), amd64_displaced_step_copy_insn(), amd64_displaced_step_fixup(), amd64_relocate_instruction(), amd64_windows_find_unwind_info(), amd64_windows_frame_decode_insns(), amd64_windows_frame_prev_register(), annotate_frame_begin(), annotate_source(), arm_analyze_prologue(), arm_displaced_init_closure(), arm_process_record(), arm_push_dummy_call(), arm_record_coproc(), arm_record_coproc_data_proc(), arm_record_data_proc_misc_ld_str(), arm_record_extension_space(), ax_print(), bookmark_1(), c_val_print(), call_site_find_chain_1(), call_site_for_pc(), call_site_to_target_addr(), check_fast_tracepoint_sals(), compare_sections_command(), create_thread_event_breakpoint(), darwin_debug_regions(), dcache_info(), dcache_print_line(), decode_insn(), deprecated_debug_xfer_memory(), describe_other_breakpoints(), displaced_step_fixup(), displaced_step_prepare(), displaced_step_restore(), display_one_tib(), dump_msymbols(), dump_psymtab(), dump_symtab_1(), dw2_find_pc_sect_symtab(), dwarf2_frame_cache(), dwarf2_restore_rule(), dwarf_expr_reg_to_entry_parameter(), edit_command(), elf_gnu_ifunc_record_cache(), execute_cfa_program(), f_val_print(), fbsd_find_memory_regions(), filter_overlapping_sections(), find_pc_sect_symtab_from_partial(), finish_block_internal(), fixup_riprel(), fprint_target_auxv(), frame_info(), frame_unwind_register_value(), func_addr_to_tail_call_list(), func_verify_no_selftailcall(), gcore_copy_callback(), gcore_create_callback(), gdb_CA_to_TAS(), gdb_get_blocks(), gdb_selected_block(), gdb_selected_frame(), gdbsim_xfer_memory(), gdbtk_load_asm(), generic_load(), generic_val_print(), gnu_xfer_memory(), gnuv3_get_typename_from_type_info(), handle_inferior_event(), heuristic_proc_start(), hppa_frame_cache(), hppa_skip_trampoline_code(), i386_displaced_step_copy_insn(), i386_displaced_step_fixup(), i386_process_record(), i386_record_lea_modrm(), i386_relocate_instruction(), ia64_dummy_id(), ia64_frame_this_id(), ia64_hpux_at_dld_breakpoint_1_p(), ia64_hpux_fetch_rnat_register(), ia64_hpux_find_global_pointer_from_solib(), ia64_hpux_read_dynamic_info(), ia64_memory_insert_breakpoint(), ia64_memory_remove_breakpoint(), ia64_sigtramp_frame_this_id(), info_cb(), info_checkpoints_command(), info_task(), init_breakpoint_sal(), insert_bp_location(), insert_exception_resume_from_probe(), insert_longjmp_resume_breakpoint(), insert_single_step_breakpoint(), insert_step_resume_breakpoint_at_sal_1(), java_value_print(), jit_bfd_try_read_symtab(), jit_breakpoint_re_set_internal(), jit_event_handler(), jit_read_descriptor(), jit_register_code(), jump_command(), linux_core_info_proc_mappings(), linux_info_proc(), list_command(), list_overlays_command(), lm_addr_check(), lm_info_read(), load_progress(), load_srec(), loclist_describe_location(), m32c_m16c_address_to_pointer(), m32r_insert_breakpoint(), m32r_insert_watchpoint(), m32r_load(), m32r_load_section(), m32r_remove_breakpoint(), m32r_remove_watchpoint(), m32r_upload_command(), m32r_xfer_memory(), macho_add_oso_symfile(), maintenance_check_psymtabs(), maintenance_info_psymtabs(), make_srec(), mbpy_str(), memory_error_message(), merge_uploaded_tracepoints(), microblaze_analyze_prologue(), mips_check_lsi_error(), mips_common_breakpoint(), mips_eabi_push_dummy_call(), mips_n32n64_push_dummy_call(), mips_o32_push_dummy_call(), mips_o64_push_dummy_call(), mips_show_dr(), monitor_error(), monitor_insert_breakpoint(), monitor_read_memory(), monitor_remove_breakpoint(), monitor_write_memory(), moxie_process_readu(), moxie_process_record(), nios2_analyze_prologue(), pascal_val_print(), ppc_displaced_step_fixup(), print_address(), print_address_demangle(), print_disassembly(), print_function_pointer_address(), print_go_string(), print_mention_ranged_breakpoint(), print_one_vtable(), print_partial_symbols(), print_section_info(), print_symbol(), print_unpacked_pointer(), print_variable_at_address(), proceed(), process_psymtab_comp_unit_reader(), program_info(), read_call_site_scope(), read_partial_die(), read_pieced_value(), record_full_arch_list_add_mem(), record_full_exec_insn(), record_full_restore(), record_full_save(), record_full_wait_1(), record_full_xfer_partial(), record_read_memory(), restore_section_callback(), resume(), resume_stopped_resumed_lwps(), s390_displaced_step_fixup(), save_bookmark_command(), say_where(), scope_info(), send_srec(), simple_displaced_step_copy_insn(), skip_function_command(), som_current_sos(), stub_gnu_ifunc_resolve_addr(), svr4_exec_displacement(), svr4_read_so_list(), tailcall_dump(), target_verify_memory(), thumb_analyze_prologue(), thumb_record_misc(), tui_make_status_line(), value_fetch_lazy(), windows_xfer_shared_library(), and write_pieced_value().
static void pagination_off_command (char * arg, int from_tty) [static]
Definition at line 2608 of file utils.c.
Referenced by initialize_utils().
static void pagination_on_command (char * arg, int from_tty) [static]
Definition at line 2602 of file utils.c.
Referenced by initialize_utils().
int parse_escape (struct gdbarch * , const char **)
Parse a C escape sequence. STRING_PTR points to a variable containing a pointer to the string to parse. That pointer should point to the character after the \. That pointer is updated past the characters we use. The value of the escape sequence is returned.
A negative value means the sequence \ newline was seen, which is supposed to be equivalent to nothing at all.
If \ is followed by a null character, we return a negative value and leave the string pointer pointing at the null character.
If \ is followed by 000, we return 0 and leave the string pointer after the zeros. A value of 0 does not mean end of string.
Definition at line 1423 of file utils.c.
References _, error(), host_char_to_target(), host_hex_value(), and target_charset().
Referenced by do_set_command(), echo_command(), and yylex().
int parse_pid_to_attach (char * args)
Return ARGS parsed as a valid pid, or throw an error.
Definition at line 3412 of file utils.c.
References _, dummy, error(), and error_no_arg().
Referenced by darwin_attach(), extended_remote_attach_1(), gnu_attach(), inf_ptrace_attach(), linux_nat_attach(), procfs_attach(), and windows_attach().
static char* perror_string (const char * prefix) [static]
Definition at line 960 of file utils.c.
References safe_strerror(), and xmalloc().
Referenced by perror_warning_with_name(), and throw_perror_with_name().
void perror_warning_with_name (const char * string)
Definition at line 1007 of file utils.c.
References _, perror_string(), warning(), and xfree().
Referenced by source_script_with_search().
void perror_with_name (const char * string)
Definition at line 998 of file utils.c.
References GENERIC_ERROR, and throw_perror_with_name().
Referenced by aarch64_point_encode_ctrl_reg(), alphabsd_fetch_inferior_registers(), alphabsd_store_inferior_registers(), amd64_linux_dr_get(), amd64_linux_dr_set(), amd64_linux_fetch_inferior_registers(), amd64_linux_read_description(), amd64_linux_store_inferior_registers(), amd64bsd_fetch_inferior_registers(), amd64bsd_store_inferior_registers(), arm_linux_insert_hw_breakpoint1(), arm_linux_remove_hw_breakpoint1(), cd_command(), coff_symtab_read(), coffstab_build_psymtabs(), convert_between_encodings(), core_open(), darwin_bfd_open(), dbx_symfile_init(), dbx_symfile_read(), dump_binary_file(), elfstab_build_psymtabs(), exec_file_attach(), fetch_all_fp_regs(), fetch_all_gp_regs(), fetch_altivec_register(), fetch_altivec_registers(), fetch_fpregs(), fetch_fpregs_from_thread(), fetch_gregs(), fetch_gregs_from_thread(), fetch_inferior_registers(), fetch_ppc_register(), fetch_register(), fetch_regs(), fetch_regset(), fetch_vsx_register(), fetch_vsx_registers(), fetch_xstateregs(), fetch_xtregs(), fill_symbuf(), find_source_lines(), fopen_with_cleanup(), fork_inferior(), forward_search_command(), gdb_wait_for_event(), generic_load(), get_spe_registers(), handle_redirections(), hppabsd_fetch_registers(), hppabsd_store_registers(), hppanbsd_fetch_registers(), hppanbsd_store_registers(), hwdebug_insert_point(), hwdebug_remove_point(), i386_linux_dr_get(), i386_linux_dr_set(), i386_linux_resume(), i386bsd_fetch_inferior_registers(), i386bsd_store_inferior_registers(), i386fbsd_resume(), ia64_hpux_get_load_info_addr(), inf_ptrace_attach(), inf_ptrace_detach(), inf_ptrace_resume(), inf_ptrace_wait(), linux_check_ptrace_features(), linux_fork_to_function(), linux_handle_extended_wait(), m32r_load(), m68kbsd_fetch_inferior_registers(), m68kbsd_store_inferior_registers(), m88kbsd_fetch_inferior_registers(), m88kbsd_store_inferior_registers(), maintenance_print_architecture(), maintenance_print_dummy_frames(), maintenance_print_msymbols(), maintenance_print_psymbols(), maintenance_print_reggroups(), maintenance_print_symbols(), make_wchar_iterator(), mips64_linux_regsets_fetch_registers(), mips64_linux_regsets_store_registers(), mips64obsd_fetch_inferior_registers(), mips64obsd_store_inferior_registers(), mips_linux_new_thread(), mips_linux_read_description(), mipsnbsd_fetch_inferior_registers(), mipsnbsd_store_inferior_registers(), monitor_open(), monitor_readchar(), perror_with_name_wrapper(), pmon_download(), ppc_linux_read_description(), ppcfbsd_fetch_inferior_registers(), ppcfbsd_store_inferior_registers(), ppcnbsd_fetch_inferior_registers(), ppcnbsd_store_inferior_registers(), ppcobsd_fetch_registers(), ppcobsd_store_registers(), print_source_lines_base(), proc_error(), procfs_set_exec_trap(), readchar(), regcache_print(), remote_file_get(), remote_file_put(), remote_open_1(), restore_binary_file(), reverse_search_command(), rs6000_ptrace_ldinfo(), s390_fix_watch_points(), s390_stopped_by_watchpoint(), serial_open(), set_logging_redirect(), set_spe_registers(), shnbsd_fetch_inferior_registers(), shnbsd_store_inferior_registers(), solib_bfd_open(), source_script_with_search(), sparc_fetch_inferior_registers(), sparc_store_inferior_registers(), sparc_xfer_wcookie(), stabsect_build_psymtabs(), store_all_fp_regs(), store_all_gp_regs(), store_altivec_register(), store_altivec_registers(), store_fpregs(), store_fpregs_to_thread(), store_gregs(), store_gregs_to_thread(), store_inferior_registers(), store_register(), store_regs(), store_regset(), store_vsx_register(), store_vsx_registers(), store_xstateregs(), store_xtregs(), symfile_bfd_open(), tfile_end(), tfile_open(), tfile_read(), tfile_write_header(), tfile_write_raw_data(), tui_set_source_content(), vax_register_u_offset(), vaxbsd_fetch_inferior_registers(), vaxbsd_store_inferior_registers(), wchar_iterate(), write_psymtabs_to_index(), write_watchpoint_regs(), and xcoff_initial_scan().
char* phex (ULONGEST l, int sizeof_l)
Print a ULONGEST in %0x format (hex with leading zeros).
Parameters:
l the unsigned integer to print
sizeof_l size of integer to print; values of 2, 4, and 8 force sizes of the respective numbers of bytes, any other value will use sizeof(l)
Returns:
a string of hexadecimal digits, from static allocation
Definition at line 2862 of file utils.c.
References CELLSIZE, get_cell(), phex(), and xsnprintf().
Referenced by arm_push_dummy_call(), core_addr_to_string(), debug_reg_change_callback(), display_one_tib(), h8300_print_register(), i386_show_dr(), info_spu_dma_cmdlist(), info_spu_dma_command(), info_spu_event_command(), info_spu_mailbox_list(), info_spu_proxydma_command(), info_spu_signal_command(), mips_eabi_push_dummy_call(), mips_n32n64_push_dummy_call(), mips_o32_push_dummy_call(), mips_o64_push_dummy_call(), monitor_store_register(), pass_in_x(), phex(), procfs_meminfo(), remote_download_trace_state_variable(), remote_flash_erase(), and target_flash_erase().
char* phex_nz (ULONGEST l, int sizeof_l)
Print a ULONGEST in x format (hex, and NO leading zeros).
Parameters:
l the unsigned integer to print
sizeof_l size of integer to print; values of 2, 4, and 8 force sizes of the respective numbers of bytes, any other value will use sizeof(l)
Returns:
a string of hexadecimal digits, from static allocation
Definition at line 2891 of file utils.c.
References CELLSIZE, get_cell(), gdb::printing::long, phex_nz(), and xsnprintf().
Referenced by append_resumption(), core_addr_to_string_nz(), disassemble_dwarf_expression(), encode_source_string(), hex_string(), hex_string_custom(), host_address_to_string(), info_spu_dma_command(), info_spu_event_command(), info_spu_proxydma_command(), info_spu_signal_command(), locexpr_describe_location_piece(), m32r_load_section(), mips_common_breakpoint(), mips_request(), monitor_store_register(), monitor_vsprintf(), phex_nz(), record_full_restore(), record_full_save(), record_linux_msghdr(), record_linux_sockaddr(), record_linux_system_call(), remote_check_symbols(), remote_get_tracepoint_status(), remote_read_qxfer(), remote_search_memory(), remote_trace_find(), remote_write_qxfer(), solist_update_incremental(), spu_pseudo_register_write_spu(), store_register_using_P(), tfile_write_status(), tfile_write_uploaded_tp(), and tfile_write_uploaded_tsv().
char* plongest (LONGEST l)
Print a LONGEST in d format.
Parameters:
l the (signed) integer to print
Returns:
a string of decimal digits
Definition at line 2850 of file utils.c.
References decimal2str().
Referenced by c_type_print_base(), c_type_print_varspec_suffix(), collect_symbol(), debug_print_register(), disassemble_dwarf_expression(), do_set_command(), dump_subexp_body_standard(), fprint_target_auxv(), gcore_copy_callback(), gcore_create_callback(), gdbarch_dump(), gdbsim_xfer_memory(), gnu_xfer_memory(), i386_linux_intx80_sysenter_syscall_record(), locexpr_describe_location_piece(), m2_enum(), maint_print_c_tdesc_cmd(), memory_error_message(), mi_tsv_created(), mi_tsv_modified(), output_thread_groups(), pascal_type_print_base(), pascal_type_print_varspec_prefix(), print_enum_type(), print_exited_reason(), print_go_string(), print_symbol(), recursive_dump_type(), save_trace_state_variables(), scope_info(), signal_to_name_or_int(), simple_search_memory(), som_symtab_read(), target_xfer_partial(), trace_variable_command(), tvariables_info_1(), validate_actionline(), and windows_xfer_memory().
const char* print_core_address (struct gdbarch * gdbarch, CORE_ADDR address)
Return a string representation in hexadecimal notation of ADDRESS, which is suitable for printing.
Definition at line 2720 of file utils.c.
References gdbarch_addr_bit(), hex_string_custom(), and HOST_CHAR_BIT.
Referenced by dsbt_print_loadmap(), print_one_detail_ranged_breakpoint(), stap_gen_info_probes_table_values(), and ui_out_field_core_addr().
void print_spaces (int n, struct ui_file * file)
Definition at line 1099 of file utils.c.
References fputs_unfiltered(), and n_spaces().
Referenced by dump_die_1(), dump_die_shallow(), dump_symtab_1(), and print_symbol().
void print_spaces_filtered (int n, struct ui_file * stream)
Definition at line 2427 of file utils.c.
References fputs_filtered(), and n_spaces().
Referenced by ada_val_print_array(), c_type_print_base(), c_val_print(), cli_spaces(), cp_print_value(), cp_print_value_fields(), default_print_one_register_info(), fprintfi_filtered(), generic_val_print(), java_print_value_fields(), java_type_print_base(), m2_print_array_contents(), m2_record_fields(), m2_val_print(), mt_registers_info(), pascal_object_print_value(), pascal_object_print_value_fields(), pascal_type_print_base(), pascal_val_print(), print_field_values(), print_record(), printfi_filtered(), sh64_do_fp_register(), sh64_do_register(), val_print_array_elements(), and val_print_packed_array_elements().
void print_sys_errmsg (const char * string, int errcode)
Definition at line 1020 of file utils.c.
References fprintf_unfiltered(), gdb_flush(), gdb_stderr, gdb_stdout, and safe_strerror().
Referenced by add_path(), check_syscall(), dead_procinfo(), print_source_lines_base(), proc_warn(), tui_set_source_content(), and windows_create_inferior().
static void printchar (int c, void(*)(const char *, struct ui_file *) do_fputs, void(*)(struct ui_file *, const char *,...) ATTRIBUTE_FPTR_PRINTF_2 do_fprintf, struct ui_file * stream, int quoter) [static]
Definition at line 1503 of file utils.c.
Referenced by fputstr_filtered(), fputstr_unfiltered(), fputstrn_filtered(), and fputstrn_unfiltered().
void printf_filtered (const char * format, ...)
Definition at line 2351 of file utils.c.
References gdb_stdout, and vfprintf_filtered().
Referenced by ada_resolve_function(), add_inferior_command(), add_memrange(), add_register(), add_static_trace_data(), address_info(), alpha_heuristic_proc_start(), ambiguous_line_spec(), annotate_arg_begin(), annotate_arg_end(), annotate_arg_name_end(), annotate_arg_value(), annotate_array_section_begin(), annotate_array_section_end(), annotate_breakpoint(), annotate_breakpoints_headers(), annotate_breakpoints_table(), annotate_breakpoints_table_end(), annotate_catchpoint(), annotate_display_begin(), annotate_display_end(), annotate_display_expression(), annotate_display_expression_end(), annotate_display_format(), annotate_display_number_end(), annotate_display_value(), annotate_elt(), annotate_elt_rep(), annotate_elt_rep_end(), annotate_error(), annotate_exited(), annotate_field(), annotate_field_begin(), annotate_field_end(), annotate_field_name_end(), annotate_field_value(), annotate_frame_address(), annotate_frame_address_end(), annotate_frame_args(), annotate_frame_begin(), annotate_frame_end(), annotate_frame_function_name(), annotate_frame_source_begin(), annotate_frame_source_end(), annotate_frame_source_file(), annotate_frame_source_file_end(), annotate_frame_source_line(), annotate_frame_where(), annotate_function_call(), annotate_quit(), annotate_record(), annotate_signal(), annotate_signal_handler_caller(), annotate_signal_name(), annotate_signal_name_end(), annotate_signal_string(), annotate_signal_string_end(), annotate_signalled(), annotate_source(), annotate_starting(), annotate_stopped(), annotate_value_begin(), annotate_value_end(), annotate_value_history_begin(), annotate_value_history_end(), annotate_value_history_value(), annotate_watchpoint(), ATTRIBUTE_PRINTF(), avr_io_reg_read_command(), backtrace_command_1(), bkpt_print_mention(), bookmark_1(), bookmarks_info(), bpstat_check_watchpoint(), bsd_kvm_files_info(), captured_main(), check(), check_frame_language_change(), checkpoint_command(), child_terminal_info(), classes_info(), clone_inferior_command(), cmdpy_function(), collect_symbol(), compare_sections_command(), continue_command(), core_detach(), core_open(), darwin_debug_regions(), dbx_psymtab_to_symtab_1(), dbx_read_symtab(), dcache_info(), dcache_print_line(), delete_checkpoint_command(), deprecated_cmd_warning(), deprecated_show_value_hack(), describe_other_breakpoints(), detach_checkpoint_command(), disp_exception(), display_current_task_id(), display_descriptor(), display_info(), display_one_tib(), display_page_table(), display_ptable_entry(), display_selector(), display_selectors(), do_examine(), do_one_display(), dos_info(), dsbt_print_loadmap(), dump_fn_fieldlists(), dump_objfile(), dump_psymtabs_for_objfile(), dw2_dump(), dw2_print_stats(), dwarf2_read_symtab(), echo_command(), edit_command(), encode_actions_1(), file_is_auto_load_safe(), find_command(), find_new_threads_once(), finish_command(), fnpy_call(), forward_search_command(), frame_info(), func_command(), gdbsim_detach(), gdbsim_open(), get_number_trailer(), get_tracepoint_by_number(), gnuv3_print_vtable(), go32_pte_for_address(), go32_sldt(), go32_sysinfo(), go_command(), heuristic_proc_start(), ignore_command(), inf_ptrace_files_info(), inferior_command(), info_auto_load_local_gdbinit(), info_cb(), info_checkpoints_command(), info_common_command(), info_common_command_for_block(), info_ext_lang_command(), info_mappings_callback(), info_proc_mappings(), info_record_command(), info_spu_dma_cmdlist(), info_spu_dma_command(), info_spu_event_command(), info_spu_mailbox_list(), info_spu_proxydma_command(), info_spu_signal_command(), info_task(), init_breakpoint_sal(), internal_bkpt_print_it(), jump_command(), kill_command(), line_info(), linux_core_info_proc(), linux_core_info_proc_mappings(), linux_fork_context(), linux_fork_detach(), linux_fork_mourn_inferior(), linux_info_proc(), list_command(), list_overlays_command(), load_srec(), m32r_files_info(), m32r_load(), m32r_load_section(), m32r_open(), m32r_upload_command(), maint_print_section_info(), maintenance_check_psymtabs(), maintenance_check_symtabs(), maintenance_do_deprecate(), maintenance_info_psymtabs(), maintenance_info_sections(), maintenance_info_symtabs(), maintenance_print_target_stack(), maintenance_translate_address(), mdebug_read_symtab(), mem_info_command(), mention(), merge_uploaded_trace_state_variables(), merge_uploaded_tracepoints(), normal_stop(), output_clbk(), output_source_filename(), parse_external(), parse_find_args(), print_bcache_statistics(), print_bfd_flags(), print_bfd_section_info(), print_bit_vector(), print_command_1(), print_command_trace(), print_cplus_stuff(), print_disassembly(), print_gp_register_row(), print_mem(), print_mention_catch_exec(), print_mention_catch_fork(), print_mention_catch_solib(), print_mention_catch_syscall(), print_mention_catch_vfork(), print_mention_ranged_breakpoint(), print_msymbol_info(), print_object_command(), print_objfile_statistics(), print_one_vtable(), print_percentage(), print_program_space(), print_psymtab_stats_for_objfile(), print_section_info(), print_source_lines_base(), print_symbol_bcache_statistics(), print_symbol_info(), print_value_flags(), procfs_attach(), procfs_detach(), procfs_files_info(), procfs_info_proc(), procfs_meminfo(), procfs_open(), procfs_pidlist(), procfs_wait(), program_info(), psymtab_to_symtab_1(), rbreak_command(), read_frame(), record_full_goto_entry(), record_full_info(), record_full_restore(), record_full_save(), recursive_dump_type(), reg_flush_command(), remote_file_delete(), remote_file_get(), remote_file_put(), remote_start_remote(), remote_wait_as(), remove_threaded_breakpoints(), resolve_subexp(), restore_binary_file(), restore_command(), restore_section_callback(), reverse_search_command(), save_bookmark_command(), save_breakpoints(), say_where(), scope_info(), sdistatus_command(), selectors_info(), set_breakpoint_condition(), set_environment_command(), set_ignore_count(), set_input_radix_1(), set_observer_mode(), set_output_radix_1(), set_radix(), show_commands(), show_convenience(), show_copying_command(), show_language_command(), show_mask_address(), show_memory_packet_size(), show_packet_config_cmd(), show_radix(), show_substitute_path_command(), show_tdesc_filename_cmd(), show_values(), show_version(), show_warranty_command(), sig_print_header(), sig_print_info(), signal_catchpoint_print_it(), signal_catchpoint_print_mention(), signal_command(), signals_info(), skip_file_command(), skip_function(), source_info(), sources_info(), step_once(), stop_command(), stopat_command(), stopin_command(), stringify_collection_list(), sym_info(), symtab_symbol_info(), task_command_1(), tfile_files_info(), tfind_1(), thread_apply_all_command(), thread_apply_command(), thread_command(), thread_find_command(), trace_dump_actions(), trace_dump_command(), trace_find_line_command(), trace_find_outside_command(), trace_find_range_command(), trace_pass_set_count(), trace_save_command(), trace_status_command(), trace_variable_command(), tracepoint_print_mention(), tui_all_windows_info(), tui_set_focus(), tui_set_win_height(), tvariables_info_1(), unconditionally_kill_inferior(), unset_command(), update_global_location_list(), update_observer_mode(), update_watchpoint(), whatis_exp(), xcoff_psymtab_to_symtab_1(), xcoff_read_symtab(), and xdb_handle_command().
void printf_unfiltered (const char * format, ...)
Definition at line 2362 of file utils.c.
References gdb_stdout, and vfprintf_unfiltered().
Referenced by add_inferior(), add_symbol_file_command(), add_thread_with_info(), amd64_linux_syscall_record(), annotate_breakpoints_invalid(), annotate_frames_invalid(), annotate_new_thread(), annotate_thread_changed(), append_command(), arm_process_record(), arm_record_coproc(), arm_record_coproc_data_proc(), arm_record_data_proc_misc_ld_str(), arm_record_extension_space(), avr_io_reg_read_command(), binary_append_command(), binary_dump_command(), check_for_thread_db(), clear_command(), cmd_record_delete(), cmd_record_stop(), command_handler(), command_line_handler(), command_line_input(), complete_command(), core_process_module_section(), create_mem_region(), darwin_attach(), darwin_debug_port_info(), darwin_decode_message(), darwin_detach(), darwin_dump_message(), darwin_set_sstep(), debug(), decode_insn(), decode_line_2(), default_terminal_info(), delete_inferior(), detach_inferior(), disable_display(), disp_exception(), display_info(), dump_command(), exec_file_attach(), exec_file_clear(), exit_inferior(), exit_lwp(), extended_remote_attach_1(), fetch_inferior_event(), first_component_command(), follow_exec(), get_task_from_args(), get_tracepoint_by_number(), get_windows_debug_event(), getpkt_or_notif_sane_1(), gnu_attach(), gnu_detach(), go32_create_inferior(), go32_files_info(), go32_open(), go32_resume(), go32_terminal_info(), handle_command(), handle_exception(), handle_file_event(), i386_darwin_fetch_inferior_registers(), i386_linux_intx80_sysenter_syscall_record(), i386_process_record(), i386_show_dr(), ihex_dump_command(), inf_ptrace_attach(), inf_ptrace_detach(), inferior_debug(), inferior_event_handler(), info_command(), info_mach_exceptions_command(), info_mach_ports_command(), info_mach_task_command(), info_mach_tasks_command(), info_mach_thread_command(), info_mach_threads_command(), info_spu_command(), jit_bfd_try_read_symtab(), jit_event_handler(), jit_inferior_init(), jit_read_descriptor(), language_info(), lm_addr_check(), m32r_load(), macho_add_oso_symfile(), macho_symfile_read(), macho_symfile_relocate(), macro_command(), maint_cplus_command(), maint_print_c_tdesc_cmd(), maintenance_command(), maintenance_cplus_namespace(), maintenance_demangle(), maintenance_deprecate(), maintenance_info_command(), maintenance_print_command(), maintenance_set_cmd(), maintenance_space_display(), maintenance_time_display(), maintenance_undeprecate(), map_breakpoint_numbers(), map_display_numbers(), map_overlay_command(), mdebug_build_psymtabs(), mem_delete(), mem_disable(), mem_enable(), mem_info_command(), microblaze_debug(), mips_kill(), mips_receive_packet(), mips_show_dr(), mips_xfer_memory(), monitor_detach(), monitor_files_info(), monitor_open(), moxie_process_readu(), overlay_auto_command(), overlay_command(), overlay_manual_command(), overlay_off_command(), procfs_attach(), procfs_detach(), procfs_files_info(), procfs_wait(), prompt_for_continue(), pwd_command(), read_command_lines(), record_btrace_call_history(), record_btrace_info(), record_btrace_insn_history(), record_linux_system_call(), remote_detach_1(), report_command_stats(), require_partial_symbols(), reread_symbols(), save_command(), serial_set_cmd(), set_ada_command(), set_architecture(), set_arm_command(), set_check(), set_dcache_command(), set_debug(), set_endian(), set_history(), set_logging_command(), set_mips_command(), set_mipsfpu_command(), set_powerpc_command(), set_print(), set_print_raw(), set_print_type(), set_ravenscar_command(), set_record_command(), set_record_full_command(), set_sh_command(), set_task_cmd(), set_thread_cmd(), set_thread_default_cmd(), show_convenience(), show_exceptions_cmd(), show_logging_command(), show_mipsfpu_command(), show_sig_thread_cmd(), show_signals_cmd(), show_stopped_cmd(), show_system_call_allowed(), show_task_detach_sc_cmd(), show_task_pause_cmd(), show_thread_cmd(), show_thread_default_cmd(), show_thread_default_detach_sc_cmd(), show_thread_default_pause_cmd(), show_thread_default_run_cmd(), show_thread_detach_sc_cmd(), show_thread_pause_cmd(), show_thread_run_cmd(), solib_add(), solib_read_symbols(), srec_dump_command(), stdin_event_handler(), svr4_exec_displacement(), symbol_file_add_with_addrs(), symbol_file_clear(), target_info(), tekhex_dump_command(), tfind_1(), thread_db_load_search(), thread_takeover_sc_cmd(), thumb_record_ldm_stm_swi(), thumb_record_misc(), tk_command(), try_thread_db_load(), try_thread_db_load_1(), tui_command(), tui_reg_command(), tui_set_source_content(), unwind_command(), update_breakpoint_locations(), user_select_syms(), windows_attach(), windows_delete_thread(), windows_detach(), and windows_files_info().
void printfi_filtered (int spaces, const char * format, ...)
Definition at line 2375 of file utils.c.
References gdb_stdout, print_spaces_filtered(), and vfprintf_filtered().
Referenced by display_descriptor(), dump_fn_fieldlists(), go32_sysinfo(), print_cplus_stuff(), and recursive_dump_type().
int producer_is_gcc_ge_4 (const char * producer)
Check for GCC >= 4.x according to the symtab->producer string. Return minor version (x) of 4.x in such case. If it is not GCC or it is GCC older than 4.x return -1. If it is GCC 5.x or higher return INT_MAX.
Definition at line 3449 of file utils.c.
Referenced by amd64_skip_xmm_prologue(), and process_full_comp_unit().
static void prompt_for_continue (void) [static]
Definition at line 1786 of file utils.c.
References annotation_level, dont_repeat(), gdb_readline_wrapper(), ignore(), p, printf_unfiltered(), quit(), QUIT, reinitialize_more_filter(), and xfree().
Referenced by fputs_maybe_filtered().
char* pulongest (ULONGEST l)
Print a ULONGEST in u format.
Parameters:
l the (unsigned) integer to print
Returns:
a string of decimal digits
Definition at line 2844 of file utils.c.
References decimal2str().
Referenced by amd64_linux_syscall_record(), c_print_token(), create_dwo_unit_in_dwp_v1(), create_dwo_unit_in_dwp_v2(), create_dwp_hash_table(), disassemble_dwarf_expression(), dump_die_shallow(), ia64_hpux_handle_load_event(), jit_bfd_try_read_symtab(), jit_register_code(), linux_info_proc(), locexpr_describe_location_1(), maintenance_translate_address(), mbpy_str(), open_and_init_dwp_file(), record_full_get_bookmark(), record_full_goto_entry(), record_full_info(), record_linux_system_call(), rs6000_aix_shared_library_to_xml(), simple_search_memory(), target_fileio_pread(), target_fileio_pwrite(), and target_verify_memory().
int putchar_filtered (int c)
Write a single char to gdb_stdout, filtered.
Definition at line 2126 of file utils.c.
References fputc_filtered(), and gdb_stdout.
Referenced by info_checkpoints_command(), and info_common_command_for_block().
int putchar_unfiltered (int c)
Write a single char to gdb_stdout, unfiltered.
Definition at line 2114 of file utils.c.
References gdb_stdout, and ui_file_write().
Referenced by clear_command(), load_srec(), monitor_wait(), monitor_wait_filter(), putpkt_binary(), and unwind_command().
void puts_debug (char * prefix, char * string, char * suffix)
Put out the given string, with special characters escaped, and enclosed by the given prefix and suffix strings.
Definition at line 2155 of file utils.c.
References fprintf_unfiltered(), fputc_unfiltered(), fputs_unfiltered(), and gdb_stdlog.
Referenced by load_srec(), and readchar().
void puts_filtered (const char *)
Write a string to gdb_stdout, filtered.
Definition at line 2391 of file utils.c.
References fputs_filtered(), and gdb_stdout.
Referenced by begin_line(), display_descriptor(), display_info(), display_page_table(), display_ptable_entry(), display_selector(), display_selectors(), do_one_display(), environment_info(), exec_files_info(), frame_info(), go32_pde(), go32_pte(), go32_pte_for_address(), go32_sldt(), go32_sysinfo(), linux_info_proc(), list_overlays_command(), macro_inform_no_debuginfo(), maintenance_check_psymtabs(), packet_command(), path_info(), print_bit_vector(), print_cplus_stuff(), print_mem(), print_packet(), recursive_dump_type(), remote_detach_1(), remote_disconnect(), remote_files_info(), remote_open_1(), restore_section_callback(), show_directories_1(), and wrap_here().
void puts_filtered_tabular (char * string, int width, int right)
Print input string to gdb_stdout, filtered, with wrap, arranging strings in columns of n chars. String can be right or left justified in the column. Never prints trailing spaces. String should never be longer than width.
Definition at line 1936 of file utils.c.
References fputs_filtered(), gdb_assert, and gdb_stdout.
Referenced by classes_info(), and selectors_info().
void puts_unfiltered (const char *)
Write a string to gdb_stdout, unfiltered.
Definition at line 2397 of file utils.c.
References fputs_unfiltered(), and gdb_stdout.
Referenced by command_line_handler(), command_line_input(), i386_show_dr(), jit_bfd_try_read_symtab(), and mips_show_dr().
int query (const char * ctlstr, ...)
Definition at line 1381 of file utils.c.
Referenced by add_symbol_file_command(), attach_command(), ATTRIBUTE_PRINTF(), avr_io_reg_read_command(), cmd_record_delete(), define_command(), delete_bookmark_command(), delete_command(), delete_trace_command(), delete_trace_variable_command(), directory_command(), do_detach(), exec_file_command(), handle_command(), inf_validate_task_sc(), interrupt_query(), irix_open_symbol_file_object(), jump_command(), kill_command(), kill_if_already_running(), maintenance_dump_me(), mem_delete_command(), mips_kill(), monitor_interrupt_query(), open_symbol_file_object(), osf_open_symbol_file_object(), query_if_trace_running(), quit_confirm(), record_full_store_registers(), record_full_xfer_partial(), remote_open_1(), return_command(), set_memory_packet_size(), som_open_symbol_file_object(), symbol_file_add_with_addrs(), symbol_file_clear(), target_preopen(), trace_start_command(), undisplay_command(), unset_environment_command(), and unset_substitute_path_command().
void quit (void)
Definition at line 1040 of file utils.c.
References current_target, fatal(), and target_ops::to_terminal_ours.
Referenced by async_remote_fileio_interrupt(), async_request_quit(), gdbsim_stop_inferior(), gdbsim_wait(), interrupt_query(), mips_kill(), monitor_interrupt_query(), prompt_for_continue(), and x_event().
PTR realloc ()
Referenced by gdb_loadfile(), and xrealloc().
void reinitialize_more_filter (void)
Definition at line 1872 of file utils.c.
Referenced by avr_io_reg_read_command(), command_handler(), command_loop(), prompt_for_continue(), and tui_rl_command_key().
void reset_prompt_for_continue_wait_time (void)
Definition at line 1854 of file utils.c.
Referenced by make_command_stats_cleanup().
static void restore_integer (void * p) [static]
Definition at line 347 of file utils.c.
References restore_integer_closure::value, and restore_integer_closure::variable.
Referenced by make_cleanup_restore_integer().
struct cleanup* set_batch_flag_and_make_cleanup_restore_page_info (void) [read]
Definition at line 1721 of file utils.c.
References batch_flag, init_page_info(), make_cleanup_restore_integer(), and make_cleanup_restore_page_info().
Referenced by execute_command_to_string().
static void set_height_command (char * args, int from_tty, struct cmd_list_element * c) [static]
Definition at line 1777 of file utils.c.
References set_screen_size().
Referenced by initialize_utils().
static void set_internal_problem_cmd (char * args, int from_tty) [static]
Definition at line 856 of file utils.c.
Referenced by add_internal_problem_command().
void set_quit_flag (void)
Definition at line 152 of file utils.c.
Referenced by gdb_stop(), handle_sigint(), and x_event().
static void set_screen_size (void) [static]
Definition at line 1735 of file utils.c.
References chars_per_line, and lines_per_page.
Referenced by do_restore_page_info_cleanup(), init_page_info(), set_height_command(), and set_width_command().
static void set_width (void) [static]
Definition at line 1754 of file utils.c.
References init_page_info(), wrap_buffer, xmalloc(), and xrealloc().
Referenced by do_restore_page_info_cleanup(), init_page_info(), and set_width_command().
static void set_width_command (char * args, int from_tty, struct cmd_list_element * c) [static]
Definition at line 1770 of file utils.c.
References set_screen_size(), and set_width().
Referenced by initialize_utils().
static void show_chars_per_line (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 1603 of file utils.c.
References _, and fprintf_filtered().
Referenced by initialize_utils().
static void show_debug_timestamp (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 2614 of file utils.c.
References _, and fprintf_filtered().
Referenced by initialize_utils().
static void show_internal_problem_cmd (char * args, int from_tty) [static]
Definition at line 861 of file utils.c.
Referenced by add_internal_problem_command().
static void show_lines_per_page (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 1592 of file utils.c.
References _, and fprintf_filtered().
Referenced by initialize_utils().
static void show_pagination_enabled (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 194 of file utils.c.
References _, and fprintf_filtered().
Referenced by initialize_utils().
static void show_sevenbit_strings (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 180 of file utils.c.
References _, and fprintf_filtered().
Referenced by initialize_utils().
int strcmp_iw (const char * string1, const char * string2)
Definition at line 2474 of file utils.c.
References case_sensitive_off, and case_sensitive_on.
Referenced by check_field(), dict_iter_name_first(), dict_iter_name_next(), do_search_struct_field(), dw2_lookup_symbol(), find_method_list(), find_methods(), function_name_is_marked_for_skip(), iterate_over_all_matching_symtabs(), lookup_struct_elt_type(), lookup_symbol_aux_psymtabs(), read_member_functions(), search_struct_method(), skip_prologue_sal(), typy_getitem(), and typy_has_key().
int strcmp_iw_ordered (const char * string1, const char * string2)
This is like strcmp except that it ignores whitespace and treats '(' as the first non-NULL character in terms of ordering. Like strcmp (and unlike strcmp_iw), it returns negative if STRING1 < STRING2, 0 if STRING2 = STRING2, and positive if STRING1 > STRING2 according to that ordering.
If a list is sorted according to this function and if you want to find names in the list that match some fixed NAME according to strcmp_iw(LIST_ELT, NAME), then the place to start looking is right where this function would put NAME.
This function must be neutral to the CASE_SENSITIVITY setting as the user may choose it during later lookup. Therefore this function always sorts primarily case-insensitively and secondarily case-sensitively.
Here are some examples of why using strcmp to sort is a bad idea:
Whitespace example:
Say your partial symtab contains: "foo<char *>", "goo". Then, if we try to do a search for "foo<char*>", strcmp will locate this after "foo<char *>" and before "goo". Then lookup_partial_symbol will start looking at strings beginning with "goo", and will never see the correct match of "foo<char *>".
Parenthesis example:
In practice, this is less like to be an issue, but I'll give it a shot. Let's assume that '$' is a legitimate character to occur in symbols. (Which may well even be the case on some systems.) Then say that the partial symbol table contains "foo$" and "foo(int)". strcmp will put them in this order, since '$' < '('. Now, if the user searches for "foo", then strcmp will sort "foo" before "foo$". Then lookup_partial_symbol will notice that strcmp_iw("foo$", "foo") is false, so it won't proceed to the actual match of "foo(int)" with "foo".
Definition at line 2502 of file utils.c.
References case_sensitive_off, and case_sensitive_on.
Referenced by compare_names_with_case(), compare_psymbols(), and lookup_partial_symbol().
int streq (const char * lhs, const char * rhs)
A simple comparison function with opposite semantics to strcmp.
Definition at line 2580 of file utils.c.
Referenced by _initialize_ada_language(), and ambiguous_names_p().
CORE_ADDR string_to_core_addr (const char * my_string)
Parse a decimal or hexadecimal string of digits, and return a CORE_ADDR. A hexadecimal string must begin with a "0x"; any invalid digits result in an error().
Definition at line 3023 of file utils.c.
References _, and error().
Referenced by gdb_block_vars(), gdb_incr_addr(), gdb_set_mem(), gdb_update_mem(), ia64_hpux_xfer_solib_got(), mi_cmd_var_create(), and variable_create().
ULONGEST strtoulst (const char * num, const char ** trailer, int base)
As for strtoul, but for ULONGEST results.
Definition at line 3241 of file utils.c.
References digit_to_int(), HIGH_BYTE_POSN, int, is_digit_in_base(), and ULONGEST.
Referenced by generic_load(), get_insn_number(), info_spu_event_command(), info_spu_signal_command(), linux_info_proc(), monitor_load(), processInt(), read_mapping(), spu_pseudo_register_read_spu(), spu_symbol_file_add_from_memory(), and spu_xfer_partial().
int subset_compare (char * string_to_compare, char * template_string)
Answer whether string_to_compare is a full or partial match to template_string. The partial match must be in sequence starting at index 0.
Definition at line 2587 of file utils.c.
Referenced by backtrace_command(), tui_set_focus(), and tui_set_layout_for_display_command().
void substitute_path_component (char ** stringp, const char * from, const char * to)
Definition at line 3517 of file utils.c.
References memcpy(), memmove(), string, strstr(), and xrealloc().
Referenced by VEC().
void throw_perror_with_name (enum errors errcode, const char * string)
Definition at line 979 of file utils.c.
References _, make_cleanup(), perror_string(), throw_error(), and xfree().
Referenced by perror_with_name().
void verror (const char * string, va_list args)
Definition at line 579 of file utils.c.
References GENERIC_ERROR, and throw_verror().
Referenced by range_error().
void vfatal (const char * string, va_list args)
Definition at line 599 of file utils.c.
References throw_vfatal().
void vfprintf_filtered (struct ui_file * stream, const char * format, va_list args)
Definition at line 2265 of file utils.c.
References vfprintf_maybe_filtered().
Referenced by ATTRIBUTE_PRINTF(), exception_fprintf(), fprintf_filtered(), fprintfi_filtered(), gdb_os_evprintf_filtered(), gdb_os_printf_filtered(), gdb_os_vprintf_filtered(), monitor_debug(), out_field_fmt(), printf_filtered(), printfi_filtered(), ps_plog(), and range_error().
static void vfprintf_maybe_filtered (static void fputs_maybe_filtered (const char struct ui_file *, const char * , va_list , int) [static]
Definition at line 94 of file utils.c.
References immediate_quit.
Referenced by vfprintf_filtered(), and vprintf_filtered().
static void vfprintf_maybe_filtered (struct ui_file * stream, const char * format, va_list args, int filter) [static]
Definition at line 2251 of file utils.c.
References do_cleanups(), fputs_maybe_filtered(), make_cleanup(), xfree(), and xstrvprintf().
void vfprintf_unfiltered (struct ui_file * stream, const char * format, va_list args)
Definition at line 2271 of file utils.c.
References do_cleanups(), fputs_unfiltered(), gdb_stdlog, len, make_cleanup(), timestamp(), xfree(), xstrprintf(), and xstrvprintf().
Referenced by ATTRIBUTE_PRINTF(), file_is_auto_load_safe(), fprintf_unfiltered(), mi_field_fmt(), parser_fprintf(), printf_unfiltered(), vprintf_unfiltered(), and vwarning().
void vprintf_filtered (const char * format, va_list args)
Definition at line 2302 of file utils.c.
References gdb_stdout, and vfprintf_maybe_filtered().
void vprintf_unfiltered (const char * format, va_list args)
Definition at line 2308 of file utils.c.
References gdb_stdout, and vfprintf_unfiltered().
Referenced by debug(), inferior_debug(), and microblaze_debug().
void vwarning (const char * string, va_list args)
Definition at line 547 of file utils.c.
References deprecated_warning_hook, fprintf_unfiltered(), fputs_unfiltered(), gdb_flush(), gdb_stderr, gdb_stdout, string, target_terminal_ours, vfprintf_unfiltered(), and wrap_here().
Referenced by lim_warning(), range_error(), and warning().
void warning (const char * string, ...)
Definition at line 565 of file utils.c.
References vwarning().
Referenced by _initialize_amd64fbsd_nat(), _initialize_check_for_gdb_ini(), _initialize_i386bsd_nat(), _initialize_loadable(), aarch64_linux_get_debug_reg_capacity(), ada_exception_name_addr(), ada_print_scalar(), ada_template_to_fixed_record_type_1(), ada_varobj_get_array_number_of_children(), add_local_symbols(), add_path(), add_vsyscall_page(), addr_info_make_relative(), agent_capability_check(), agent_get_helper_thread_id(), agent_run_command(), aggregate_assign_positional(), alpha_heuristic_proc_start(), amd64_dwarf_reg_to_regnum(), arm_copy_block_xfer(), arm_gdbarch_init(), avr_dwarf_reg_to_regnum(), backtrace_command_1(), bfin_skip_prologue(), block_lookup(), bpstat_check_breakpoint_conditions(), breakpoint_adjustment_warning(), breakpoint_xfer_memory(), bsd_kvm_close(), build_id_verify(), build_traceframe_info(), bx_write_pc(), check_for_thread_db(), choose_architecture_for_target(), compare_sections_command(), convert_typed_floating(), core_xfer_partial(), cp_canonicalize_string(), cp_lookup_rtti_type(), create_breakpoint(), create_excep_cond_exprs(), create_tracepoint_from_upload(), create_tty_session(), cris_dwarf2_reg_to_regnum(), cris_software_single_step(), crisv32_register_type(), ctrl_c_handler(), darwin_attach_pid(), darwin_kill_inferior(), darwin_read_write_inferior(), darwin_stop_inferior(), dbx_lookup_type(), dec_thread_get_ada_task_ptid(), dec_thread_store_registers(), define_command(), delete_bookmark_command(), delete_checkpoint_command(), delete_trace_state_variable(), delete_trace_variable_command(), detach_inferior_command(), dicos_load_module_p(), disable_breakpoints_in_unloaded_shlib(), disable_probes_interface_cleanup(), displaced_write_reg(), do_examine(), do_one_display(), do_print_variable_and_value(), do_ui_out_redirect_pop(), dsbt_current_sos(), dsbt_solib_create_inferior_hook(), dump_bfd_file(), dump_msymbols(), dump_value_to_file(), dw2_find_pc_sect_symtab(), dwarf2_build_frame_info(), dwarf2_read_index(), dwarf2_read_symtab(), elf_gnu_ifunc_record_cache(), elf_symfile_segments(), enable_break(), enable_break2(), enable_break_failure_warning(), enable_thread_event_reporting(), evaluate_subexp_modula2(), evaluate_subexp_standard(), execute_command_to_string(), execute_control_command(), execute_user_command(), fetch_core_registers(), fetch_elfcore_registers(), fetch_fp_register(), fetch_fp_regs(), fetch_fpregister(), fetch_fpregs(), fetch_instruction(), fetch_register(), fetch_regs(), fetch_sec_names(), fetch_vfp_regs(), fetch_wmmx_regs(), file_is_auto_load_safe(), file_read_description_xml(), find_overload_match(), find_parallel_type_by_descriptive_type(), find_pc_sect_symtab_from_partial(), find_separate_debug_file_by_buildid(), find_separate_debug_file_in_section(), find_source_lines(), follow_fork(), frv_current_sos(), frv_linux_sigcontext_reg_addr(), frv_solib_create_inferior_hook(), gcore_copy_callback(), gcore_create_callback(), gdb_bfd_close_or_warn(), gdb_connect_sync_socket(), gdb_signal_to_host(), gdbarch_init_osabi(), gdbsim_create_inferior(), gdbsim_store_register(), generic_observer_detach(), get_command_line(), get_core_register_section(), get_file_crc(), get_offsets(), get_osdata(), gnu_fetch_registers(), gnu_find_memory_regions(), gnu_read_inferior(), gnu_resume(), gnu_store_registers(), gnu_wait(), gnu_write_inferior(), gnuv3_rtti_type(), handle_output_debug_string(), handle_redirections(), heuristic_proc_start(), hppa32_hpux_in_solib_call_trampoline(), hppa64_dwarf_reg_to_regnum(), hppa_dwarf_reg_to_regnum(), hppa_hpux_find_dummy_bpaddr(), hppa_hpux_in_solib_return_trampoline(), hppa_hpux_skip_trampoline_code(), hppa_skip_trampoline_code(), i386_darwin_fetch_inferior_registers(), i386_extract_return_value(), i386_linux_core_read_xcr0(), i386_store_return_value(), i387_register_to_value(), i387_value_to_register(), ia64_hpux_add_so_from_dld_info(), ia64_hpux_at_dld_breakpoint_p(), ia64_hpux_fetch_register(), ia64_hpux_get_register_from_save_state_t(), ia64_hpux_handle_dld_breakpoint(), ia64_hpux_handle_load_event(), ia64_hpux_solib_add_after_attach(), ia64_memory_remove_breakpoint(), ill_rpc(), inf_continue(), inf_set_traced(), inf_signal(), inf_task_died_status(), info_cb(), init_breakpoint_sal(), insert_bp_location(), irix_current_sos(), irix_open_symbol_file_object(), irix_solib_create_inferior_hook(), jit_bfd_try_read_symtab(), kill_inferior_command(), lin_lwp_attach_lwp(), linux_check_ptrace_features(), linux_core_info_proc(), linux_core_info_proc_mappings(), linux_find_memory_regions_full(), linux_info_proc(), linux_nat_create_inferior(), linux_nat_post_attach_wait(), linux_proc_get_int(), linux_proc_pid_has_state(), linux_ptrace_test_ret_to_nx(), linux_test_for_tracefork(), lm_addr_check(), lm_info_read(), lookup_dwo_cutu(), m32c_m16c_address_to_pointer(), m68hc11_initialize_register_info(), m68k_register_to_value(), m68k_value_to_register(), mach_check_error(), macho_add_oso_symfile(), macho_check_dsym(), macho_resolve_oso_sym_with_minsym(), macho_symfile_read_all_oso(), macho_symtab_read(), make_proc(), map_breakpoint_numbers(), map_display_numbers(), mep_gdbarch_init(), mips16_scan_prologue(), mips_common_breakpoint(), mips_find_abi_section(), mips_find_long_section(), mips_linux_regset_from_core_section(), mn10300_dwarf2_reg_to_regnum(), modify_field(), msp430_dwarf2_reg_to_regnum(), new_tty(), nios2_dwarf_reg_to_regnum(), open_symbol_file_object(), osdata_parse(), parse_traceframe_info(), parse_tracepoint_definition(), perror_warning_with_name(), post_create_inferior(), ppc_linux_masked_watch_num_registers(), print_section_info(), proc_abort(), proc_modify_flag(), proc_restore_exc_port(), proc_set_traced_signals(), proc_steal_exc_port(), process_tracepoint_on_disconnect(), procfs_resume(), rate_to_code(), read_index_from_section(), read_type(), record_btrace_enable_warn(), record_full_exec_insn(), record_full_restore(), remote_download_command_source(), remote_download_tracepoint(), remote_get_threadlist(), remote_packet_size(), remote_parse_stop_reply(), remote_query_attached(), remote_query_supported(), remote_resume(), remote_serial_open(), remote_set_disconnected_tracing(), remote_set_permissions(), remote_set_trace_buffer_size(), remote_supported_packet(), remote_threadlist_iterator(), remote_trace_set_readonly_regions(), remote_unescape_input(), remote_unpack_thread_info_response(), remote_wait_as(), remote_wait_ns(), remove_breakpoint_1(), remove_dbx_link_breakpoint(), remove_inferior_command(), require_user_regions(), restore_binary_file(), restore_section_callback(), restore_selected_frame(), s390_dwarf_reg_to_regnum(), S_msg_sig_post_untraced_reply(), S_proc_wait_reply(), save_breakpoints(), scan_xcoff_symtab(), separate_debug_file_exists(), ser_windows_raw(), ser_windows_wait_handle(), set_case_command(), set_command(), set_condition_evaluation_mode(), set_current_traceframe(), set_logging_overwrite(), set_logging_redirect(), set_range_command(), set_range_stepping(), set_remote_traceframe(), set_trace_notes(), set_trace_stop_notes(), set_trace_user(), show_case_command(), show_range_command(), simple_search_memory(), sniff_core_bfd(), sol_thread_resume(), sol_thread_wait(), solib_aix_bfd_open(), solib_aix_solib_create_inferior_hook(), solib_bfd_open(), solib_target_relocate_section_addresses(), som_current_sos(), som_open_symbol_file_object(), som_solib_create_inferior_hook(), som_solib_section_offsets(), spu_child_wait(), stap_get_probe_argument_count(), stap_modify_semaphore(), start_tracing(), stop_tracing(), store_fp_register(), store_fp_regs(), store_fpregister(), store_fpregs(), store_register(), store_regs(), store_vfp_regs(), store_wmmx_regs(), svr4_read_so_list(), syscall_warn_user(), target_fileio_read_stralloc(), target_find_description(), target_insert_breakpoint(), target_read_stralloc(), target_remove_breakpoint(), target_stop(), tdesc_parse_xml(), tdesc_register_type(), tfile_fetch_registers(), tfile_interp_line(), tfile_open(), thread_apply_command(), thread_db_attach_lwp(), thread_db_load(), thread_rec(), thumb2_copy_block_xfer(), try_thread_db_load_1(), try_thread_db_load_from_pdir_1(), tui_layout_command(), tui_set_focus(), tui_set_layout_for_display_command(), tui_set_tab_width_command(), tui_set_win_height(), tui_xdb_set_win_height(), uninstall_variable(), update_breakpoint_locations(), update_dec_thread_list(), update_dprintf_command_list(), update_solib_list(), update_static_tracepoint(), val_print_array_elements(), validate_files(), value_cast(), value_full_object(), value_ptrdiff(), value_subscript(), varobj_delete(), VEC(), verbose_dlsym(), warning_once(), windows_create_inferior(), write_gcore_file(), xml_fetch_content_from_file(), xtensa_pseudo_register_read(), and xtensa_pseudo_register_write().
void wrap_here (char * indent)
Definition at line 1900 of file utils.c.
References _, chars_printed, fputs_unfiltered(), gdb_stdout, internal_error(), puts_filtered(), and wrap_buffer.
Referenced by ATTRIBUTE_PRINTF(), c_type_print_args(), c_type_print_base(), c_type_print_template_args(), captured_main(), cli_wrap_hint(), command_line_handler(), command_line_input(), cp_print_value_fields(), cp_type_print_derivation_info(), cp_type_print_method_args(), dbx_psymtab_to_symtab_1(), dump_objfile(), dump_psymtab(), dump_psymtabs_for_objfile(), echo_command(), f_type_print_base(), fputs_maybe_filtered(), frame_info(), help_list(), java_print_value_fields(), java_type_print_base(), java_value_print(), line_info(), m2_enum(), m2_print_type(), m2_procedure(), m2_record_fields(), maintenance_check_symtabs(), maintenance_info_psymtabs(), maintenance_info_sections(), maintenance_info_symtabs(), mi_wrap_hint(), mips_error(), output_command_const(), output_source_filename(), pascal_object_print_value_fields(), pascal_print_func_args(), pascal_type_print_base(), print_any_exception(), print_array_type(), print_enum_type(), print_field_values(), print_flush(), print_formatted(), print_func_type(), print_section_info(), psymtab_to_symtab_1(), require_partial_symbols(), reread_symbols(), symbol_file_add_with_addrs(), trace_find_line_command(), val_print_array_elements(), val_print_packed_array_elements(), vwarning(), and xcoff_psymtab_to_symtab_1().
int yquery (const char * ctlstr, ...)
Definition at line 1364 of file utils.c.
Referenced by i386_process_record(), i386_record_lea_modrm(), record_full_check_insn_num(), and record_linux_system_call().
Variable Documentation
initialize_file_ftype _initialize_utils
Referenced by initialize_all_files().
unsigned int chars_per_line [static]
Definition at line 1601 of file utils.c.
Referenced by set_screen_size().
unsigned int chars_printed [static]
Definition at line 1613 of file utils.c.
Referenced by fputs_maybe_filtered(), and wrap_here().
void(* deprecated_error_begin_hook)(void)
Definition at line 90 of file utils.c.
Referenced by clear_interpreter_hooks(), gdbtk_add_hooks(), and print_flush().
struct internal_problem internal_error_problem [static]
Initial value:
 {
  "internal-error", internal_problem_ask, internal_problem_ask
}
Definition at line 812 of file utils.c.
const char internal_problem_ask[] = "ask"
Definition at line 666 of file utils.c.
const char* const internal_problem_modes[] [static]
Initial value:
{
  internal_problem_ask,
  internal_problem_yes,
  internal_problem_no,
  NULL
}
Definition at line 669 of file utils.c.
const char internal_problem_no[] = "no"
Definition at line 668 of file utils.c.
const char internal_problem_yes[] = "yes"
Definition at line 667 of file utils.c.
struct internal_problem internal_warning_problem [static]
Initial value:
 {
  "internal-warning", internal_problem_ask, internal_problem_ask
}
Definition at line 833 of file utils.c.
unsigned int lines_per_page [static]
Definition at line 1590 of file utils.c.
Referenced by set_screen_size().
unsigned int lines_printed [static]
Definition at line 1613 of file utils.c.
int pagination_enabled = 1
Definition at line 192 of file utils.c.
Referenced by set_observer_mode(), tui_register_format(), and tui_restore_gdbout().
int sevenbit_strings = 0
Definition at line 178 of file utils.c.
Referenced by mi_command_loop().
int thirty_two = 32 [static]
Definition at line 2859 of file utils.c.
char* warning_pre_print = "\nwarning: "
String to be printed before the warning message, when a warning occurs. (Typically something like "warning:".)
Definition at line 190 of file utils.c.
Referenced by captured_main().
char* wrap_buffer [static]
Definition at line 1626 of file utils.c.
Referenced by fputs_maybe_filtered(), set_width(), and wrap_here().
int wrap_column [static]
Definition at line 1637 of file utils.c.
Referenced by fputs_maybe_filtered().
char* wrap_indent [static]
Definition at line 1633 of file utils.c.
Referenced by print_one_static_tracepoint_marker(), and wrap_indent_at_field().
char* wrap_pointer [static]
Definition at line 1629 of file utils.c.