GDB (xrefs): /home/stan/gdb/src/gdb/utils.h File Reference
/home/stan/gdb/src/gdb/utils.h File Reference
#include "cleanups.h"
#include "exceptions.h"
Functions
void initialize_utils (void)
char * savestring (const char *ptr, size_t len)
int strcmp_iw (const char *, const char *)
int strcmp_iw_ordered (const char *string1, const char *string2)
int streq (const char *lhs, const char *rhs)
int subset_compare (char *string_to_compare, char *template_string)
ULONGEST strtoulst (const char *num, const char **trailer, int base)
int compare_positive_ints (const void *ap, const void *bp)
int compare_strings (const void *ap, const void *bp)
char * safe_strerror (int)
const char * gdb_bfd_errmsg (bfd_error_type error_tag, char **matching)
void reset_prompt_for_continue_wait_time (void)
struct timeval get_prompt_for_continue_wait_time (void)
int parse_pid_to_attach (char *args)
int parse_escape (struct gdbarch *, const char **)
char ** gdb_buildargv (const char *s)
struct cleanup * make_cleanup_freeargv (char **)
struct cleanup * make_cleanup_dyn_string_delete (struct dyn_string *)
struct cleanup * make_cleanup_ui_file_delete (struct ui_file *)
struct cleanup * make_cleanup_ui_out_redirect_pop (struct ui_out *uiout)
struct cleanup * make_cleanup_free_section_addr_info (struct section_addr_info *))
struct cleanup * make_cleanup_close (int fd)
struct cleanup * make_cleanup_fclose (FILE *file)
struct cleanup * make_cleanup_bfd_unref (bfd *abfd)
struct cleanup * make_cleanup_obstack_free (struct obstack *obstack)
struct cleanup * make_cleanup_restore_integer (int *variable)
struct cleanup * make_cleanup_restore_uinteger (unsigned int *variable)
struct cleanup * make_cleanup_unpush_target (struct target_ops *ops)
struct cleanup * make_cleanup_restore_ui_file (struct ui_file **variable)
struct cleanup * make_cleanup_value_free_to_mark (struct value *)
struct cleanup * make_cleanup_value_free (struct value *)
struct cleanup * make_cleanup_free_so (struct so_list *so)
struct cleanup * make_cleanup_restore_current_language (void)
struct cleanup * make_cleanup_htab_delete (htab_t htab)
void free_current_contents (void *)
void init_page_info (void)
struct cleanup * make_cleanup_restore_page_info (void)
struct cleanup * set_batch_flag_and_make_cleanup_restore_page_info (void)
struct cleanup * make_bpstat_clear_actions_cleanup (void)
char * gdb_realpath (const char *filename)
int gdb_filename_fnmatch (const char *pattern, const char *string, int flags)
void substitute_path_component (char **stringp, const char *from, const char *to)
char * ldirname (const char *filename)
int query (const char *,...) ATTRIBUTE_PRINTF(1
int int nquery (const char *,...) ATTRIBUTE_PRINTF(1
int int int yquery (const char *,...) ATTRIBUTE_PRINTF(1
int int int void begin_line (void)
void wrap_here (char *)
void reinitialize_more_filter (void)
void fputs_filtered (const char *, struct ui_file *)
void fputs_unfiltered (const char *, struct ui_file *)
int fputc_filtered (int c, struct ui_file *)
int fputc_unfiltered (int c, struct ui_file *)
int putchar_filtered (int c)
int putchar_unfiltered (int c)
void puts_filtered (const char *)
void puts_unfiltered (const char *)
void puts_filtered_tabular (char *string, int width, int right)
void puts_debug (char *prefix, char *string, char *suffix)
void vprintf_filtered (const char *, va_list) ATTRIBUTE_PRINTF(1
void void vfprintf_filtered (struct ui_file *, const char *, va_list) ATTRIBUTE_PRINTF(2
void void void fprintf_filtered (struct ui_file *, const char *,...) ATTRIBUTE_PRINTF(2
void void void void fprintfi_filtered (int, struct ui_file *, const char *,...) ATTRIBUTE_PRINTF(3
void void void void void printf_filtered (const char *,...) ATTRIBUTE_PRINTF(1
void void void void void void printfi_filtered (int, const char *,...) ATTRIBUTE_PRINTF(2
void void void void void void void vprintf_unfiltered (const char *, va_list) ATTRIBUTE_PRINTF(1
void void void void void void
void void vfprintf_unfiltered (struct ui_file *, const char *, va_list) ATTRIBUTE_PRINTF(2
void void void void void void
void void void fprintf_unfiltered (struct ui_file *, const char *,...) ATTRIBUTE_PRINTF(2
void void void void void void
void void void void printf_unfiltered (const char *,...) ATTRIBUTE_PRINTF(1
void void void void void void
void void void void void print_spaces (int, struct ui_file *)
void print_spaces_filtered (int, struct ui_file *)
char * n_spaces (int)
void fputstr_filtered (const char *str, int quotr, struct ui_file *stream)
void fputstr_unfiltered (const char *str, int quotr, struct ui_file *stream)
void fputstrn_filtered (const char *str, int n, int quotr, struct ui_file *stream)
void fputstrn_unfiltered (const char *str, int n, int quotr, struct ui_file *stream)
void gdb_print_host_address (const void *addr, struct ui_file *stream)
const char * host_address_to_string (const void *addr)
const char * paddress (struct gdbarch *gdbarch, CORE_ADDR addr)
const char * print_core_address (struct gdbarch *gdbarch, CORE_ADDR address)
hashval_t core_addr_hash (const void *ap)
int core_addr_eq (const void *ap, const void *bp)
char * plongest (LONGEST l)
char * pulongest (ULONGEST l)
char * phex (ULONGEST l, int sizeof_l)
char * phex_nz (ULONGEST l, int sizeof_l)
char * int_string (LONGEST val, int radix, int is_signed, int width, int use_c_format)
const char * core_addr_to_string (const CORE_ADDR addr)
const char * core_addr_to_string_nz (const CORE_ADDR addr)
CORE_ADDR string_to_core_addr (const char *my_string)
char * hex_string (LONGEST)
char * hex_string_custom (LONGEST, int)
void fprintf_symbol_filtered (struct ui_file *, const char *, enum language, int)
void throw_perror_with_name (enum errors errcode, const char *string) ATTRIBUTE_NORETURN
void perror_with_name (const char *) ATTRIBUTE_NORETURN
void perror_warning_with_name (const char *string)
void print_sys_errmsg (const char *, int)
void verror (const char *fmt, va_list ap) ATTRIBUTE_NORETURN ATTRIBUTE_PRINTF(1
void void error (const char *fmt,...) ATTRIBUTE_NORETURN ATTRIBUTE_PRINTF(1
void void void error_stream (struct ui_file *) ATTRIBUTE_NORETURN
void vfatal (const char *fmt, va_list ap) ATTRIBUTE_NORETURN ATTRIBUTE_PRINTF(1
void void fatal (const char *fmt,...) ATTRIBUTE_NORETURN ATTRIBUTE_PRINTF(1
void void void internal_verror (const char *file, int line, const char *, va_list ap) ATTRIBUTE_NORETURN ATTRIBUTE_PRINTF(3
void void void void internal_vwarning (const char *file, int line, const char *, va_list ap) ATTRIBUTE_PRINTF(3
void void void void void internal_warning (const char *file, int line, const char *,...) ATTRIBUTE_PRINTF(3
void void void void void void warning (const char *,...) ATTRIBUTE_PRINTF(1
void void void void void void void vwarning (const char *, va_list args) ATTRIBUTE_PRINTF(1
void void void void void void
void void * hashtab_obstack_allocate (void *data, size_t size, size_t count)
void dummy_obstack_deallocate (void *object, void *data)
int producer_is_gcc_ge_4 (const char *producer)
int myread (int, char *, int)
ULONGEST align_up (ULONGEST v, int n)
ULONGEST align_down (ULONGEST v, int n)
LONGEST gdb_sign_extend (LONGEST value, int bit)
Variables
int sevenbit_strings
int pagination_enabled
struct ui_file * gdb_stdout
struct ui_file * gdb_stdin
struct ui_file * gdb_stderr
struct ui_file * gdb_stdlog
struct ui_file * gdb_stdtarg
struct ui_file * gdb_stdtargerr
struct ui_file * gdb_stdtargin
void(* deprecated_error_begin_hook)(void)
char * warning_pre_print
Function Documentation
ULONGEST align_down (ULONGEST v, int n)
Definition at line 3164 of file utils.c.
References gdb_assert.
Referenced by aarch64_push_dummy_call(), frv_frame_align(), frv_push_dummy_call(), h8300_push_dummy_call(), hppa_linux_sigtramp_find_sigcontext(), i386_darwin_push_dummy_call(), m88k_store_arguments(), mips_eabi_push_dummy_call(), mips_frame_align(), mips_n32n64_push_dummy_call(), mips_o32_push_dummy_call(), mips_o64_push_dummy_call(), msp430_frame_align(), msp430_push_dummy_call(), mt_frame_align(), nios2_frame_align(), ppc64_sysv_abi_push_dummy_call(), ppc_sysv_abi_push_dummy_call(), rl78_frame_align(), rs6000_lynx178_push_dummy_call(), rx_push_dummy_call(), s390_push_dummy_call(), score_adjust_breakpoint_address(), score_frame_align(), score_push_dummy_call(), tic6x_frame_align(), tic6x_push_dummy_call(), and xtensa_push_dummy_call().
ULONGEST align_up (ULONGEST v, int n)
Definition at line 3156 of file utils.c.
References gdb_assert.
Referenced by ctf_save_align_write(), frv_push_dummy_call(), h8300_push_dummy_call(), hppa32_frame_align(), hppa32_push_dummy_call(), hppa64_frame_align(), hppa64_push_dummy_call(), i386_darwin_push_dummy_call(), i386_push_dummy_call(), mips_eabi_push_dummy_call(), mips_n32n64_push_dummy_call(), mips_o32_push_dummy_call(), mips_o64_push_dummy_call(), nios2_push_dummy_call(), pass_on_stack(), ppc64_sysv_abi_push_dummy_call(), ppc_linux_spe_context(), ppc_sysv_abi_push_dummy_call(), rs6000_lynx178_push_dummy_call(), rx_push_dummy_call(), s390_push_dummy_call(), s390_sigtramp_frame_unwind_cache(), score_push_dummy_call(), spu_push_dummy_call(), store_register(), tic6x_push_dummy_call(), and tilegx_push_dummy_call().
int int int void begin_line (void)
Definition at line 1979 of file utils.c.
References puts_filtered().
Referenced by ATTRIBUTE_PRINTF(), classes_info(), and selectors_info().
int compare_positive_ints (const void * ap, const void * bp)
Integer compare function suitable for qsort.
Definition at line 3350 of file utils.c.
Referenced by list_available_thread_groups(), mi_cmd_list_thread_groups(), print_bcache_statistics(), and print_one_inferior().
int compare_strings (const void * ap, const void * bp)
String compare function suitable for qsort.
Definition at line 3360 of file utils.c.
Referenced by complete_command(), and uniquify_strings().
int core_addr_eq (const void * ap, const void * bp)
Definition at line 2749 of file utils.c.
Referenced by call_site_find_chain_1(), func_verify_no_selftailcall(), and read_call_site_scope().
hashval_t core_addr_hash (const void * ap)
Definition at line 2739 of file utils.c.
Referenced by call_site_find_chain_1(), func_verify_no_selftailcall(), and read_call_site_scope().
const char* core_addr_to_string (const CORE_ADDR addr)
Convert a CORE_ADDR into a hex string with leading zeros, and prefixed with "0x" as in C syntax. The output from core_addr_to_string() can be passed direct to string_to_core_addr().
Definition at line 3002 of file utils.c.
References get_cell(), and phex().
Referenced by compile_probe_arg(), compute_probe_arg(), darwin_read_write_inferior(), darwin_xfer_partial(), debug_to_can_accel_watchpoint_condition(), debug_to_insert_breakpoint(), debug_to_insert_hw_breakpoint(), debug_to_insert_watchpoint(), debug_to_region_ok_for_hw_watchpoint(), debug_to_remove_breakpoint(), debug_to_remove_hw_breakpoint(), debug_to_remove_watchpoint(), debug_to_stopped_data_address(), debug_to_watchpoint_addr_within_range(), gdb_entry_point(), gdb_get_breakpoint_info(), gdb_get_tracepoint_info(), gdb_incr_addr(), gdb_load_disassembly(), gdb_loc(), gdb_update_mem(), gdbtk_load_asm(), rs6000_aix_shared_library_to_xml(), solib_aix_get_toc_value(), spu_catch_start(), target_insert_mask_watchpoint(), target_remove_mask_watchpoint(), watch_command_1(), and windows_xfer_memory().
const char* core_addr_to_string_nz (const CORE_ADDR addr)
Convert a CORE_ADDR into a hex string, withOUT leading zeros, and prefixed with "0x" as in C syntax. The output from core_addr_to_string() can be passed direct to string_to_core_addr().
Definition at line 3012 of file utils.c.
References get_cell(), and phex_nz().
Referenced by aarch64_analyze_prologue(), debug_print_register(), decode_add_sub_imm(), decode_adrp(), decode_b(), decode_bcond(), decode_br(), decode_cb(), decode_eret(), decode_movz(), decode_orr_shifted_register_x(), decode_ret(), decode_stp_offset(), decode_stp_offset_wb(), decode_stur(), decode_tb(), gdbarch_dump(), target_xfer_partial(), and VEC().
void dummy_obstack_deallocate (void * object, void * data)
Definition at line 3207 of file utils.c.
Referenced by allocate_dwo_file_hash_table(), allocate_dwo_unit_table(), allocate_dwp_loaded_cutus_table(), allocate_signatured_type_table(), allocate_type_unit_groups_table(), create_copied_types_hash(), dwarf2_add_dependence(), elf_gnu_ifunc_record_cache(), load_full_comp_unit_reader(), load_partial_dies(), read_signatured_type_reader(), and set_die_type().
void void error (const char * fmt, ...)
void void void error_stream (struct ui_file *)
Definition at line 615 of file utils.c.
References error(), make_cleanup(), ui_file_xstrdup(), and xfree().
Referenced by insert_breakpoint_locations(), mi_cmd_execute(), and update_inserted_breakpoint_locations().
void void fatal (const char * fmt, ...)
void void void fprintf_filtered (struct ui_file * , const char * , ...)
void fprintf_symbol_filtered (struct ui_file * , const char * , enum language, int)
Definition at line 2440 of file utils.c.
References demangle, fputs_filtered(), language_def(), language_demangle(), and xfree().
Referenced by address_info(), cp_print_value_fields(), cp_type_print_method_args(), frame_info(), java_print_value_fields(), pascal_object_print_value_fields(), print_frame(), print_frame_arg(), and py_print_single_arg().
void void void void void void void void void fprintf_unfiltered (struct ui_file * , const char * , ...)
void void void void fprintfi_filtered (int , struct ui_file * , const char * , ...)
int fputc_filtered (int c, struct ui_file *)
Write a single char to output.
Definition at line 2141 of file utils.c.
References fputs_filtered().
Referenced by c_printchar(), disassemble_dwarf_expression(), field_separator(), pascal_type_print_method_args(), and putchar_filtered().
int fputc_unfiltered (int c, struct ui_file *)
Write a single char to output, unfiltered.
Definition at line 2132 of file utils.c.
References ui_file_write().
Referenced by canonicalize_linespec(), chain_candidate(), deprecated_debug_xfer_memory(), field_separator(), fputs_maybe_filtered(), mep_gdbarch_init(), mi_close(), mi_cmd_data_read_memory(), mi_open(), mips_receive_header(), putpkt_binary(), puts_debug(), remote_rcmd(), serial_logchar(), and target_xfer_partial().
void fputs_filtered (const char * , struct ui_file *)
Write a string to output, controlled by pagination.
Definition at line 2108 of file utils.c.
References fputs_maybe_filtered().
Referenced by ada_print_scalar(), ada_print_subexp(), ada_printchar(), ada_val_print_1(), address_info(), ATTRIBUTE_PRINTF(), ax_print(), c_print_type(), c_printstr(), c_type_print_base(), c_type_print_template_args(), c_val_print(), cli_text(), cp_print_class_member(), cp_print_static_field(), cp_print_value(), cp_print_value_fields(), cp_type_print_derivation_info(), cp_type_print_method_args(), dbx_psymtab_to_symtab_1(), default_print_one_register_info(), describe_other_breakpoints(), do_examine(), do_show_command(), dump_die_shallow(), dump_msymbols(), dump_prefix_expression(), dump_psymtab(), dump_subexp_body_standard(), dump_symtab_1(), f_print_type(), f_printchar(), f_printstr(), f_type_print_base(), f_val_print(), fprintf_symbol_filtered(), fputc_filtered(), fputstr_filtered(), fputstrn_filtered(), frame_info(), gdbtk_load_asm(), generic_emit_char(), generic_printstr(), generic_val_print(), getpkt_or_notif_sane_1(), gnuv3_print_method_ptr(), go_print_type(), help_cmd(), help_list(), i387_print_float_info(), info_checkpoints_command(), java_print_type(), java_print_value_fields(), java_printchar(), java_type_print_base(), java_type_print_derivation_info(), java_val_print(), java_value_print(), jump_command(), list_arg_or_local(), list_overlays_command(), m2_emit_char(), m2_enum(), m2_long_set(), m2_print_type(), m2_printchar(), m2_printstr(), m2_procedure(), m2_record_fields(), m2_type_name(), m2_typedef(), m2_unbounded_array(), m2_val_print(), m32r_load(), m32r_load_section(), m32r_upload_command(), macro_expand_command(), macro_expand_once_command(), maintenance_check_psymtabs(), maintenance_info_psymtabs(), mips_print_register(), mt_registers_info(), output_source_filename(), pascal_emit_char(), pascal_object_print_static_field(), pascal_object_print_value(), pascal_object_print_value_fields(), pascal_one_char(), pascal_print_func_args(), pascal_print_type(), pascal_printchar(), pascal_printstr(), pascal_type_print_base(), pascal_type_print_derivation_info(), pascal_type_print_method_args(), pascal_val_print(), print_address(), print_address_demangle(), print_address_symbolic(), print_any_exception(), print_decimal_floating(), print_doc_line(), print_enum_type(), print_exception(), print_field_values(), print_floating(), print_frame_arg(), print_func_type(), print_function_pointer_address(), print_go_string(), print_help_for_command(), print_hex_chars(), print_i387_control_word(), print_i387_ext(), print_i387_status_word(), print_longest(), print_macro_definition(), print_name_maybe_canonical(), print_octal_chars(), print_partial_symbols(), print_scalar_formatted(), print_spaces_filtered(), print_subexp_standard(), print_symbol(), print_symbol_info(), print_type_scalar(), print_unpacked_pointer(), print_variable_at_address(), printstr(), psymtab_to_symtab_1(), puts_filtered(), puts_filtered_tabular(), py_print_single_arg(), read_frame(), say_where(), sh64_do_fp_register(), sh64_do_register(), show_disable_randomization(), show_user_1(), target_command(), tui_make_status_line(), val_print_string(), val_print_type_code_flags(), valprint_check_validity(), and xcoff_psymtab_to_symtab_1().
void fputs_unfiltered (const char * , struct ui_file *)
Write a string to output, with no filter.
Definition at line 249 of file ui-file.c.
References ui_file::to_fputs.
Referenced by ATTRIBUTE_PRINTF(), canonicalize_linespec(), captured_main(), captured_mi_execute_command(), chain_candidate(), clear_complaints(), deprecated_debug_xfer_memory(), displaced_step_dump_bytes(), display_gdb_prompt(), do_serial_close(), dump_mem(), dwarf2_compute_name(), fputs_maybe_filtered(), fputstr_unfiltered(), fputstrn_unfiltered(), gdb_os_write_stderr(), gdb_readline(), gdbtk_command_loop(), get_register(), mi_cmd_execute(), mi_cmd_gdb_exit(), mi_command_loop(), mi_console_file_fputs(), mi_console_raw_packet(), mi_execute_command_input_handler(), mi_field_fmt(), mi_load_progress(), mi_on_normal_stop(), mi_on_resume(), mi_print_exception(), monitor_rcmd(), print_gdb_help(), print_i387_ext(), print_spaces(), print_subexp_standard(), puts_debug(), puts_unfiltered(), remote_console_output(), replace_typedefs_qualified_name(), ser_base_read_error_fd(), serial_log_command(), serial_logchar(), target_xfer_partial(), tui_alloc_source_buffer(), vfprintf_unfiltered(), vwarning(), and wrap_here().
void fputstr_filtered (const char * str, int quotr, struct ui_file * stream)
Definition at line 1555 of file utils.c.
References fprintf_filtered(), fputs_filtered(), and printchar().
Referenced by do_show_command(), and print_packet().
void fputstr_unfiltered (const char * str, int quotr, struct ui_file * stream)
Definition at line 1562 of file utils.c.
References fprintf_unfiltered(), fputs_unfiltered(), and printchar().
Referenced by mi_cmd_execute(), mi_field_string(), and mi_print_exception().
void fputstrn_filtered (const char * str, int n, int quotr, struct ui_file * stream)
Definition at line 1569 of file utils.c.
References fprintf_filtered(), fputs_filtered(), and printchar().
void fputstrn_unfiltered (const char * str, int n, int quotr, struct ui_file * stream)
Definition at line 1579 of file utils.c.
References fprintf_unfiltered(), fputs_unfiltered(), and printchar().
Referenced by escape_buffer(), and mi_console_raw_packet().
void free_current_contents (void *)
Definition at line 524 of file utils.c.
References _, internal_error(), and xfree().
Referenced by ada_read_renaming_var_value(), agent_eval_command_one(), c_parse(), call_site_find_chain_1(), captured_mi_execute_command(), coff_symfile_read(), compute_enum_values(), dbx_read_symtab(), displaced_step_prepare(), display_gdb_prompt(), dwarf2_add_member_fn(), elf_rel_plt_read(), elfstab_build_psymtabs(), encode_actions_1(), execute_control_command(), expand(), file_is_auto_load_safe(), find_command(), find_symbol_in_baseclass(), gather_arguments(), gdb_eval(), info_macro_command(), info_macros_command(), init_if_undefined_command(), macro_define_command(), macro_expand_command(), macro_expand_once_command(), maintenance_print_type(), mi_cmd_data_evaluate_expression(), mi_cmd_trace_frame_collected(), mi_cmd_var_create(), mi_cmd_var_delete(), output_command_const(), parse_and_eval(), parse_and_eval_address(), parse_and_eval_long(), parse_find_args(), parse_to_comma_and_eval(), print_address_symbolic(), print_command_1(), print_object_command(), print_variable_or_computed(), rbreak_command(), read_array_type(), read_pe_exported_syms(), read_pieced_value(), read_string(), remote_query_supported(), remote_threads_info(), set_command(), simple_search_memory(), stap_parse_argument(), trace_dump_actions(), ui_printf(), validate_actionline(), value_get_print_value(), whatis_exp(), write_pieced_value(), x_command(), and xml_fetch_content_from_file().
const char* gdb_bfd_errmsg (bfd_error_type error_tag, char ** matching)
A wrapper for bfd_errmsg to produce a more helpful error message in the case of bfd_error_file_ambiguously recognized.
Parameters:
error_tag
matching if non-NULL, is the corresponding argument to bfd_check_format_matches, and will be freed.
Definition at line 3373 of file utils.c.
References AMBIGUOUS_MESS1, AMBIGUOUS_MESS2, make_cleanup(), p, xfree(), and xmalloc().
Referenced by exec_file_attach().
char** gdb_buildargv (const char * s)
Call libiberty's buildargv, and return the result. If buildargv fails due to out-of-memory, call nomem. Therefore, the returned value is guaranteed to be non-NULL, unless the parameter itself is NULL.
Definition at line 3338 of file utils.c.
References malloc_failure().
Referenced by add_inferior_command(), add_path(), add_symbol_file_command(), alias_command(), backtrace_command(), clone_inferior_command(), delete_trace_variable_command(), exec_file_command(), extended_remote_run(), gdbpy_string_to_argv(), gdbsim_create_inferior(), gdbsim_load(), gdbsim_open(), generic_load(), handle_command(), interpreter_exec_cmd(), maintenance_expand_symtabs(), maintenance_print_msymbols(), maintenance_print_psymbols(), maintenance_print_symbols(), monitor_load(), pipe_windows_open(), procfs_info_proc(), remote_delete_command(), remote_get_command(), remote_put_command(), set_substitute_path_command(), show_substitute_path_command(), symbol_file_command(), trace_save_command(), unset_substitute_path_command(), and xdb_handle_command().
int gdb_filename_fnmatch (const char * pattern, const char * string, int flags)
Definition at line 3634 of file utils.c.
References gdb_assert.
Referenced by filename_is_in_pattern_1().
void gdb_print_host_address (const void * addr, struct ui_file * stream)
Display the host ADDR on STREAM formatted as ``0xx''.
Definition at line 1107 of file utils.c.
References fprintf_filtered(), and host_address_to_string().
Referenced by ada_dump_subexp_body(), dump_fn_fieldlists(), dump_objfile(), dump_prefix_expression(), dump_psymtab(), dump_psymtabs_for_objfile(), dump_raw_expression(), dump_subexp_body_standard(), dump_symtab_1(), fprint_dummy_frames(), fprint_frame(), print_cplus_stuff(), print_symbol(), and recursive_dump_type().
char* gdb_realpath (const char * filename)
Get the canonicalized absolute pathname for the given filename, returning the result in freshly-allocated memory. This is basically just a host-independent wrapper for realpath().
Parameters:
filename the filename to get a path for
Definition at line 3069 of file utils.c.
References len.
Referenced by auto_load_objfile_script(), auto_load_safe_path_vec_update(), captured_main(), dw2_get_real_path(), dwarf2_get_dwz_file(), exec_file_attach(), filename_is_in_auto_load_safe_path_vec(), find_and_open_source(), iterate_over_symtabs(), maintenance_print_msymbols(), nto_find_and_open_solib(), openp(), and try_thread_db_load().
LONGEST gdb_sign_extend (LONGEST value, int bit)
Definition at line 3174 of file utils.c.
References gdb_assert, and LONGEST.
Referenced by indirect_pieced_value().
struct timeval get_prompt_for_continue_wait_time (void) [read]
Definition at line 1864 of file utils.c.
Referenced by report_command_stats().
void void void void void void void void* hashtab_obstack_allocate (void * data, size_t size, size_t count)
Definition at line 3192 of file utils.c.
References memset().
Referenced by allocate_dwo_file_hash_table(), allocate_dwo_unit_table(), allocate_dwp_loaded_cutus_table(), allocate_signatured_type_table(), allocate_type_unit_groups_table(), call_site_find_chain_1(), create_copied_types_hash(), dwarf2_add_dependence(), elf_gnu_ifunc_record_cache(), func_verify_no_selftailcall(), load_full_comp_unit_reader(), load_partial_dies(), read_call_site_scope(), read_signatured_type_reader(), and set_die_type().
char* hex_string (LONGEST)
Return a string that contains a number formatted as a hex string.
Definition at line 2929 of file utils.c.
References CELLSIZE, get_cell(), phex_nz(), and xsnprintf().
Referenced by amd64_relocate_instruction(), append_ocl_sos(), bpfinishpy_init(), create_addrmap_from_index(), create_debug_types_hash_table(), create_dwo_cu_reader(), create_dwo_unit_in_dwp_v1(), create_dwo_unit_in_dwp_v2(), create_new_frame(), create_tracepoint_from_upload(), debug_qf_find_pc_sect_symtab(), dump_die_shallow(), edit_command(), find_unwind_entry(), follow_die_sig(), fprint_field(), fprint_frame(), frame_unwind_pc_if_available(), get_frame_func_if_available(), get_function_name(), get_signatured_type(), go32_pte_for_address(), i386_relocate_instruction(), int_string(), linux_core_info_proc_mappings(), linux_info_proc(), list_command(), load_progress(), lookup_dwo_cutu(), lookup_dwp_signatured_type(), maintenance_translate_address(), make_blockvector(), mi_cmd_var_create(), paddress(), parse_partial_symbols(), pdc_read_data(), pdc_read_regs(), pdc_symbol_addrs(), pdc_write_data(), pdc_write_regs(), print_symbol(), process_one_symbol(), process_queue(), read_attribute_value(), read_cutu_die_from_dwo(), read_dbx_symtab(), remote_parse_stop_reply(), rs6000_ptrace64(), scope_info(), simple_search_memory(), spu_current_sos(), target_flash_erase(), target_search_memory(), and unwind_command().
char* hex_string_custom (LONGEST , int)
Definition at line 2942 of file utils.c.
References _, CELLSIZE, get_cell(), internal_error(), memset(), and phex_nz().
Referenced by breakpoint_adjustment_warning(), dsbt_current_sos(), enable_break(), enable_break2(), frv_current_sos(), i387_print_float_info(), int_string(), lm_base(), maint_print_section_info(), mem_info_command(), print_core_address(), print_i387_control_word(), print_i387_status_word(), print_msymbol_info(), and print_section_info().
const char* host_address_to_string (const void * addr)
Definition at line 3060 of file utils.c.
References CELLSIZE, get_cell(), phex_nz(), and xsnprintf().
Referenced by allocate_psymtab(), allocate_symtab(), c_print_token(), darwin_xfer_partial(), debug_can_evaluate_probe_arguments(), debug_qf_expand_symtabs_matching(), debug_qf_find_pc_sect_symtab(), debug_qf_map_matching_symbols(), debug_qf_map_symbol_filenames(), debug_qf_map_symtabs_matching_filename(), debug_qf_relocate(), debug_sym_compile_to_ax(), debug_sym_evaluate_probe_argument(), debug_sym_get_probe_argument_count(), debug_sym_offsets(), debug_sym_relocate(), debug_sym_relocate_probe(), debug_to_can_accel_watchpoint_condition(), debug_to_insert_watchpoint(), debug_to_remove_watchpoint(), debug_to_thread_architecture(), gdb_print_host_address(), gdbarch_dump(), gdbarch_find_by_info(), gdbarch_register(), gdbarch_update_p(), gdbsim_xfer_memory(), get_register_types(), gnu_xfer_memory(), handle_exception(), handle_load_dll(), handle_unload_dll(), ia64_frame_this_id(), ia64_sigtramp_frame_this_id(), lookup_dwo_cutu(), maintenance_check_symtabs(), maintenance_info_psymtabs(), maintenance_info_symtabs(), monitor_read_memory(), print_one_bfd(), record_full_arch_list_add(), record_full_exec_insn(), record_full_wait_1(), target_xfer_partial(), unwind_command(), VEC(), xtensa_push_dummy_call(), and xtensa_unwind_pc().
void init_page_info (void)
Definition at line 1643 of file utils.c.
References batch_flag, gdb_stdout, set_screen_size(), set_width(), tgetnum(), tui_get_command_dimension(), and ui_file_isatty().
Referenced by initialize_utils(), set_batch_flag_and_make_cleanup_restore_page_info(), and set_width().
void initialize_utils (void)
Definition at line 2623 of file utils.c.
References _, add_com(), add_setshow_boolean_cmd(), add_setshow_uinteger_cmd(), class_maintenance, class_support, init_page_info(), pagination_off_command(), pagination_on_command(), set_height_command(), set_width_command(), setdebuglist, setlist, setprintlist, show_chars_per_line(), show_debug_timestamp(), show_lines_per_page(), show_pagination_enabled(), show_sevenbit_strings(), showdebuglist, showlist, showprintlist, and xdb_commands.
Referenced by gdb_init().
char* int_string (LONGEST val, int radix, int is_signed, int width, int use_c_format)
Convert VAL to a numeral in the given radix. For radix 10, IS_SIGNED may be true, indicating a signed quantity; otherwise VAL is interpreted as unsigned. If WIDTH is supplied, it is the minimum width (0-padded if needed). USE_C_FORMAT means to use C format in all cases. If it is false, then 'x' and 'o' formats do not include a prefix (0x or leading 0).
Definition at line 2962 of file utils.c.
References _, decimal2str(), hex_string(), hex_string_custom(), internal_error(), and octal2str().
Referenced by ada_print_type(), c_describe_child(), mi_inferior_exit(), and print_longest().
void void void internal_verror (const char * file, int line, const char * , va_list ap)
void void void void internal_vwarning (const char * file, int line, const char * , va_list ap)
void void void void void internal_warning (const char * file, int line, const char * , ...)
char* ldirname (const char * filename)
Definition at line 3313 of file utils.c.
References memcpy(), and xmalloc().
Referenced by _initialize_python(), dwarf2_get_dwz_file(), file_read_description_xml(), and find_file_and_directory().
struct cleanup* make_bpstat_clear_actions_cleanup (void) [read]
Definition at line 3441 of file utils.c.
References do_bpstat_clear_actions_cleanup(), and make_cleanup().
Referenced by bpstat_do_actions(), execute_command(), fetch_inferior_event(), and inferior_event_handler().
struct cleanup* make_cleanup_bfd_unref (bfd * abfd) [read]
Definition at line 238 of file utils.c.
References do_bfd_close_cleanup(), and make_cleanup().
Referenced by bfd_openr_with_cleanup(), bfd_openw_with_cleanup(), coff_symfile_read(), core_open(), darwin_bfd_open(), darwin_solib_get_all_image_info_addr_at_init(), elf_symfile_read(), gdb_load_info(), generic_load(), jit_bfd_try_read_symtab(), load_srec(), m32r_load(), m32r_upload_command(), macho_add_oso_symfile(), macho_symfile_read(), read_symbols(), reread_symbols(), solib_bfd_open(), spu_symbol_file_add_from_memory(), symbol_file_add(), symbol_file_add_from_memory(), and symfile_bfd_open().
struct cleanup* make_cleanup_close (int fd) [read]
Definition at line 252 of file utils.c.
References do_close_cleanup(), make_cleanup_dtor(), xfree(), and xmalloc().
Referenced by forward_search_command(), get_filename_and_charpos(), iterate_over_mappings(), procfs_open(), procfs_pidlist(), and reverse_search_command().
struct cleanup* make_cleanup_dyn_string_delete (struct dyn_string *) [read]
struct cleanup* make_cleanup_fclose (FILE * file) [read]
Definition at line 273 of file utils.c.
References do_fclose_cleanup(), and make_cleanup().
Referenced by auto_load_objfile_script_1(), fbsd_find_memory_regions(), fopen_with_cleanup(), forward_search_command(), linux_proc_pending_signals(), print_source_lines_base(), remote_file_get(), remote_file_put(), reverse_search_command(), source_script_with_search(), and xml_fetch_content_from_file().
struct cleanup* make_cleanup_free_section_addr_info (struct section_addr_info *) [read]
Definition at line 335 of file utils.c.
References do_free_section_addr_info(), and make_cleanup().
Referenced by addr_info_make_relative(), jit_bfd_try_read_symtab(), and symbol_file_add_separate().
struct cleanup* make_cleanup_free_so (struct so_list * so) [read]
Definition at line 488 of file utils.c.
References do_free_so(), and make_cleanup().
Referenced by svr4_read_so_list().
struct cleanup* make_cleanup_freeargv (char **) [read]
Definition at line 214 of file utils.c.
References do_freeargv(), and make_cleanup().
Referenced by add_inferior_command(), add_symbol_file_command(), alias_command(), backtrace_command(), clone_inferior_command(), delete_trace_variable_command(), exec_file_command(), gdbsim_create_inferior(), gdbsim_load(), generic_load(), handle_command(), interpreter_exec_cmd(), maintenance_expand_symtabs(), maintenance_print_msymbols(), maintenance_print_psymbols(), maintenance_print_symbols(), monitor_load(), pipe_windows_open(), procfs_info_proc(), remote_delete_command(), remote_get_command(), remote_put_command(), set_substitute_path_command(), show_substitute_path_command(), symbol_file_command(), trace_save_command(), unset_substitute_path_command(), and xdb_handle_command().
struct cleanup* make_cleanup_htab_delete (htab_t htab) [read]
Definition at line 409 of file utils.c.
References do_htab_delete_cleanup(), and make_cleanup().
Referenced by apply_frame_filter(), call_site_find_chain_1(), dw2_expand_symtabs_matching(), dw2_map_symbol_filenames(), dwarf_decode_macros(), func_verify_no_selftailcall(), gnuv3_print_vtable(), VEC(), and write_psymtabs_to_index().
struct cleanup* make_cleanup_obstack_free (struct obstack * obstack) [read]
Definition at line 291 of file utils.c.
References do_obstack_free(), and make_cleanup().
Referenced by c_parse(), call_site_find_chain_1(), create_addrmap_from_index(), dwarf2_build_psymtabs_hard(), evaluate_subexp_c(), func_verify_no_selftailcall(), generic_emit_char(), generic_printstr(), go_parse(), host_char_to_target(), indirect_pieced_value(), linux_make_mappings_corefile_notes(), printf_wide_c_string(), signal_catchpoint_print_one(), ui_printf(), and write_psymtabs_to_index().
struct cleanup* make_cleanup_restore_current_language (void) [read]
Definition at line 507 of file utils.c.
References current_language, do_restore_current_language(), language_defn::la_language, and make_cleanup().
Referenced by parse_exp_in_context_1().
struct cleanup* make_cleanup_restore_integer (int * variable) [read]
Definition at line 358 of file utils.c.
References make_cleanup_dtor(), restore_integer(), restore_integer_closure::value, restore_integer_closure::variable, xfree(), and xmalloc().
Referenced by arm_insert_single_step_breakpoint(), c_parse(), checkpoint_command(), do_one_display(), exec_continue(), execute_command_to_string(), execute_user_command(), fetch_inferior_event(), go_parse(), if_command(), make_cleanup_restore_traceframe_number(), make_cleanup_restore_uinteger(), mi_cmd_execute(), mi_cmd_var_assign(), prepare_for_detach(), prevent_dont_repeat(), record_full_gdb_operation_disable_set(), set_batch_flag_and_make_cleanup_restore_page_info(), setup_breakpoint_reporting(), and while_command().
struct cleanup* make_cleanup_restore_page_info (void) [read]
Definition at line 1706 of file utils.c.
References do_restore_page_info_cleanup(), make_cleanup(), and make_cleanup_restore_uinteger().
Referenced by set_batch_flag_and_make_cleanup_restore_page_info().
struct cleanup* make_cleanup_restore_ui_file (struct ui_file ** variable) [read]
Definition at line 432 of file utils.c.
References do_restore_ui_file(), make_cleanup_dtor(), restore_ui_file_closure::value, restore_ui_file_closure::variable, and xfree().
Referenced by execute_command_to_string().
struct cleanup* make_cleanup_restore_uinteger (unsigned int * variable) [read]
Definition at line 373 of file utils.c.
References make_cleanup_restore_integer().
Referenced by make_cleanup_restore_page_info().
struct cleanup* make_cleanup_ui_file_delete (struct ui_file *) [read]
Definition at line 303 of file utils.c.
References do_ui_file_delete(), and make_cleanup().
Referenced by ada_print_floating(), ada_varobj_get_value_image(), ada_varobj_scalar_image(), bppy_get_commands(), do_show_command(), dump_insns(), escape_buffer(), eval_command(), execute_command_to_string(), gdb_disassembly(), gdb_eval(), gdb_update_mem(), get_register(), handle_redirections(), insert_breakpoint_locations(), list_arg_or_local(), maintenance_print_architecture(), maintenance_print_dummy_frames(), maintenance_print_msymbols(), maintenance_print_psymbols(), maintenance_print_reggroups(), maintenance_print_symbols(), mi_cmd_data_evaluate_expression(), mi_cmd_data_read_memory(), mi_cmd_execute(), output_register(), print_breakpoint_location(), print_frame(), print_frame_arg(), print_frame_args(), print_it_watchpoint(), print_one_detail_ranged_breakpoint(), print_return_value(), print_variable_or_computed(), py_print_single_arg(), py_print_type(), py_print_value(), quit_confirm(), reattach_breakpoints(), regcache_print(), save_breakpoints(), set_logging_redirect(), type_to_string(), typy_str(), update_inserted_breakpoint_locations(), value_get_print_value(), verify_gdbarch(), and xtensa_verify_config().
struct cleanup* make_cleanup_ui_out_redirect_pop (struct ui_out * uiout) [read]
Definition at line 323 of file utils.c.
References do_ui_out_redirect_pop(), and make_cleanup().
Referenced by execute_command_to_string().
struct cleanup* make_cleanup_unpush_target (struct target_ops * ops) [read]
Definition at line 391 of file utils.c.
References do_unpush_target(), and make_cleanup().
Referenced by inf_ptrace_attach(), and inf_ptrace_create_inferior().
struct cleanup* make_cleanup_value_free (struct value *) [read]
Definition at line 470 of file utils.c.
References do_value_free(), and make_cleanup().
Referenced by dwarf2_evaluate_loc_desc_full().
struct cleanup* make_cleanup_value_free_to_mark (struct value *) [read]
Definition at line 454 of file utils.c.
References do_value_free_to_mark(), and make_cleanup().
Referenced by dwarf2_evaluate_loc_desc_full(), dwarf2_loc_desc_needs_frame(), execute_stack_op(), and prepare_execute_command().
int myread (int , char * , int)
Definition at line 1080 of file utils.c.
References len, and read().
Referenced by find_source_lines().
char* n_spaces (int)
Definition at line 2405 of file utils.c.
References xfree(), and xmalloc().
Referenced by cp_print_value_fields(), java_print_value_fields(), java_value_print(), pascal_object_print_value_fields(), print_field_values(), print_spaces(), print_spaces_filtered(), print_variable_and_value(), val_print_array_elements(), and val_print_packed_array_elements().
int int nquery (const char * , ...)
const char* paddress (struct gdbarch * gdbarch, CORE_ADDR addr)
Convert CORE_ADDR to string in platform-specific manner. This is usually formatted similar to 0xlx.
Definition at line 2699 of file utils.c.
References gdbarch_addr_bit(), hex_string(), and HOST_CHAR_BIT.
Referenced by aarch64_dump_tdep(), aarch64_push_dummy_call(), ada_val_print_1(), add_symbol_file_command(), add_vsyscall_page(), address_info(), alpha_heuristic_proc_start(), amd64_displaced_step_copy_insn(), amd64_displaced_step_fixup(), amd64_relocate_instruction(), amd64_windows_find_unwind_info(), amd64_windows_frame_decode_insns(), amd64_windows_frame_prev_register(), annotate_frame_begin(), annotate_source(), arm_analyze_prologue(), arm_displaced_init_closure(), arm_process_record(), arm_push_dummy_call(), arm_record_coproc(), arm_record_coproc_data_proc(), arm_record_data_proc_misc_ld_str(), arm_record_extension_space(), ax_print(), bookmark_1(), c_val_print(), call_site_find_chain_1(), call_site_for_pc(), call_site_to_target_addr(), check_fast_tracepoint_sals(), compare_sections_command(), create_thread_event_breakpoint(), darwin_debug_regions(), dcache_info(), dcache_print_line(), decode_insn(), deprecated_debug_xfer_memory(), describe_other_breakpoints(), displaced_step_fixup(), displaced_step_prepare(), displaced_step_restore(), display_one_tib(), dump_msymbols(), dump_psymtab(), dump_symtab_1(), dw2_find_pc_sect_symtab(), dwarf2_frame_cache(), dwarf2_restore_rule(), dwarf_expr_reg_to_entry_parameter(), edit_command(), elf_gnu_ifunc_record_cache(), execute_cfa_program(), f_val_print(), fbsd_find_memory_regions(), filter_overlapping_sections(), find_pc_sect_symtab_from_partial(), finish_block_internal(), fixup_riprel(), fprint_target_auxv(), frame_info(), frame_unwind_register_value(), func_addr_to_tail_call_list(), func_verify_no_selftailcall(), gcore_copy_callback(), gcore_create_callback(), gdb_CA_to_TAS(), gdb_get_blocks(), gdb_selected_block(), gdb_selected_frame(), gdbsim_xfer_memory(), gdbtk_load_asm(), generic_load(), generic_val_print(), gnu_xfer_memory(), gnuv3_get_typename_from_type_info(), handle_inferior_event(), heuristic_proc_start(), hppa_frame_cache(), hppa_skip_trampoline_code(), i386_displaced_step_copy_insn(), i386_displaced_step_fixup(), i386_process_record(), i386_record_lea_modrm(), i386_relocate_instruction(), ia64_dummy_id(), ia64_frame_this_id(), ia64_hpux_at_dld_breakpoint_1_p(), ia64_hpux_fetch_rnat_register(), ia64_hpux_find_global_pointer_from_solib(), ia64_hpux_read_dynamic_info(), ia64_memory_insert_breakpoint(), ia64_memory_remove_breakpoint(), ia64_sigtramp_frame_this_id(), info_cb(), info_checkpoints_command(), info_task(), init_breakpoint_sal(), insert_bp_location(), insert_exception_resume_from_probe(), insert_longjmp_resume_breakpoint(), insert_single_step_breakpoint(), insert_step_resume_breakpoint_at_sal_1(), java_value_print(), jit_bfd_try_read_symtab(), jit_breakpoint_re_set_internal(), jit_event_handler(), jit_read_descriptor(), jit_register_code(), jump_command(), linux_core_info_proc_mappings(), linux_info_proc(), list_command(), list_overlays_command(), lm_addr_check(), lm_info_read(), load_progress(), load_srec(), loclist_describe_location(), m32c_m16c_address_to_pointer(), m32r_insert_breakpoint(), m32r_insert_watchpoint(), m32r_load(), m32r_load_section(), m32r_remove_breakpoint(), m32r_remove_watchpoint(), m32r_upload_command(), m32r_xfer_memory(), macho_add_oso_symfile(), maintenance_check_psymtabs(), maintenance_info_psymtabs(), make_srec(), mbpy_str(), memory_error_message(), merge_uploaded_tracepoints(), microblaze_analyze_prologue(), mips_check_lsi_error(), mips_common_breakpoint(), mips_eabi_push_dummy_call(), mips_n32n64_push_dummy_call(), mips_o32_push_dummy_call(), mips_o64_push_dummy_call(), mips_show_dr(), monitor_error(), monitor_insert_breakpoint(), monitor_read_memory(), monitor_remove_breakpoint(), monitor_write_memory(), moxie_process_readu(), moxie_process_record(), nios2_analyze_prologue(), pascal_val_print(), ppc_displaced_step_fixup(), print_address(), print_address_demangle(), print_disassembly(), print_function_pointer_address(), print_go_string(), print_mention_ranged_breakpoint(), print_one_vtable(), print_partial_symbols(), print_section_info(), print_symbol(), print_unpacked_pointer(), print_variable_at_address(), proceed(), process_psymtab_comp_unit_reader(), program_info(), read_call_site_scope(), read_partial_die(), read_pieced_value(), record_full_arch_list_add_mem(), record_full_exec_insn(), record_full_restore(), record_full_save(), record_full_wait_1(), record_full_xfer_partial(), record_read_memory(), restore_section_callback(), resume(), resume_stopped_resumed_lwps(), s390_displaced_step_fixup(), save_bookmark_command(), say_where(), scope_info(), send_srec(), simple_displaced_step_copy_insn(), skip_function_command(), som_current_sos(), stub_gnu_ifunc_resolve_addr(), svr4_exec_displacement(), svr4_read_so_list(), tailcall_dump(), target_verify_memory(), thumb_analyze_prologue(), thumb_record_misc(), tui_make_status_line(), value_fetch_lazy(), windows_xfer_shared_library(), and write_pieced_value().
int parse_escape (struct gdbarch * , const char **)
Parse a C escape sequence. STRING_PTR points to a variable containing a pointer to the string to parse. That pointer should point to the character after the \. That pointer is updated past the characters we use. The value of the escape sequence is returned.
A negative value means the sequence \ newline was seen, which is supposed to be equivalent to nothing at all.
If \ is followed by a null character, we return a negative value and leave the string pointer pointing at the null character.
If \ is followed by 000, we return 0 and leave the string pointer after the zeros. A value of 0 does not mean end of string.
Definition at line 1423 of file utils.c.
References _, error(), host_char_to_target(), host_hex_value(), and target_charset().
Referenced by do_set_command(), echo_command(), and yylex().
int parse_pid_to_attach (char * args)
Return ARGS parsed as a valid pid, or throw an error.
Definition at line 3412 of file utils.c.
References _, dummy, error(), and error_no_arg().
Referenced by darwin_attach(), extended_remote_attach_1(), gnu_attach(), inf_ptrace_attach(), linux_nat_attach(), procfs_attach(), and windows_attach().
void perror_warning_with_name (const char * string)
Definition at line 1007 of file utils.c.
References _, perror_string(), warning(), and xfree().
Referenced by source_script_with_search().
void perror_with_name (const char *)
Definition at line 998 of file utils.c.
References GENERIC_ERROR, and throw_perror_with_name().
Referenced by aarch64_point_encode_ctrl_reg(), alphabsd_fetch_inferior_registers(), alphabsd_store_inferior_registers(), amd64_linux_dr_get(), amd64_linux_dr_set(), amd64_linux_fetch_inferior_registers(), amd64_linux_read_description(), amd64_linux_store_inferior_registers(), amd64bsd_fetch_inferior_registers(), amd64bsd_store_inferior_registers(), arm_linux_insert_hw_breakpoint1(), arm_linux_remove_hw_breakpoint1(), cd_command(), coff_symtab_read(), coffstab_build_psymtabs(), convert_between_encodings(), core_open(), darwin_bfd_open(), dbx_symfile_init(), dbx_symfile_read(), dump_binary_file(), elfstab_build_psymtabs(), exec_file_attach(), fetch_all_fp_regs(), fetch_all_gp_regs(), fetch_altivec_register(), fetch_altivec_registers(), fetch_fpregs(), fetch_fpregs_from_thread(), fetch_gregs(), fetch_gregs_from_thread(), fetch_inferior_registers(), fetch_ppc_register(), fetch_register(), fetch_regs(), fetch_regset(), fetch_vsx_register(), fetch_vsx_registers(), fetch_xstateregs(), fetch_xtregs(), fill_symbuf(), find_source_lines(), fopen_with_cleanup(), fork_inferior(), forward_search_command(), gdb_wait_for_event(), generic_load(), get_spe_registers(), handle_redirections(), hppabsd_fetch_registers(), hppabsd_store_registers(), hppanbsd_fetch_registers(), hppanbsd_store_registers(), hwdebug_insert_point(), hwdebug_remove_point(), i386_linux_dr_get(), i386_linux_dr_set(), i386_linux_resume(), i386bsd_fetch_inferior_registers(), i386bsd_store_inferior_registers(), i386fbsd_resume(), ia64_hpux_get_load_info_addr(), inf_ptrace_attach(), inf_ptrace_detach(), inf_ptrace_resume(), inf_ptrace_wait(), linux_check_ptrace_features(), linux_fork_to_function(), linux_handle_extended_wait(), m32r_load(), m68kbsd_fetch_inferior_registers(), m68kbsd_store_inferior_registers(), m88kbsd_fetch_inferior_registers(), m88kbsd_store_inferior_registers(), maintenance_print_architecture(), maintenance_print_dummy_frames(), maintenance_print_msymbols(), maintenance_print_psymbols(), maintenance_print_reggroups(), maintenance_print_symbols(), make_wchar_iterator(), mips64_linux_regsets_fetch_registers(), mips64_linux_regsets_store_registers(), mips64obsd_fetch_inferior_registers(), mips64obsd_store_inferior_registers(), mips_linux_new_thread(), mips_linux_read_description(), mipsnbsd_fetch_inferior_registers(), mipsnbsd_store_inferior_registers(), monitor_open(), monitor_readchar(), perror_with_name_wrapper(), pmon_download(), ppc_linux_read_description(), ppcfbsd_fetch_inferior_registers(), ppcfbsd_store_inferior_registers(), ppcnbsd_fetch_inferior_registers(), ppcnbsd_store_inferior_registers(), ppcobsd_fetch_registers(), ppcobsd_store_registers(), print_source_lines_base(), proc_error(), procfs_set_exec_trap(), readchar(), regcache_print(), remote_file_get(), remote_file_put(), remote_open_1(), restore_binary_file(), reverse_search_command(), rs6000_ptrace_ldinfo(), s390_fix_watch_points(), s390_stopped_by_watchpoint(), serial_open(), set_logging_redirect(), set_spe_registers(), shnbsd_fetch_inferior_registers(), shnbsd_store_inferior_registers(), solib_bfd_open(), source_script_with_search(), sparc_fetch_inferior_registers(), sparc_store_inferior_registers(), sparc_xfer_wcookie(), stabsect_build_psymtabs(), store_all_fp_regs(), store_all_gp_regs(), store_altivec_register(), store_altivec_registers(), store_fpregs(), store_fpregs_to_thread(), store_gregs(), store_gregs_to_thread(), store_inferior_registers(), store_register(), store_regs(), store_regset(), store_vsx_register(), store_vsx_registers(), store_xstateregs(), store_xtregs(), symfile_bfd_open(), tfile_end(), tfile_open(), tfile_read(), tfile_write_header(), tfile_write_raw_data(), tui_set_source_content(), vax_register_u_offset(), vaxbsd_fetch_inferior_registers(), vaxbsd_store_inferior_registers(), wchar_iterate(), write_psymtabs_to_index(), write_watchpoint_regs(), and xcoff_initial_scan().
char* phex (ULONGEST l, int sizeof_l)
Print a ULONGEST in %0x format (hex with leading zeros).
Parameters:
l the unsigned integer to print
sizeof_l size of integer to print; values of 2, 4, and 8 force sizes of the respective numbers of bytes, any other value will use sizeof(l)
Returns:
a string of hexadecimal digits, from static allocation
Definition at line 2862 of file utils.c.
References CELLSIZE, get_cell(), phex(), and xsnprintf().
Referenced by arm_push_dummy_call(), core_addr_to_string(), debug_reg_change_callback(), display_one_tib(), h8300_print_register(), i386_show_dr(), info_spu_dma_cmdlist(), info_spu_dma_command(), info_spu_event_command(), info_spu_mailbox_list(), info_spu_proxydma_command(), info_spu_signal_command(), mips_eabi_push_dummy_call(), mips_n32n64_push_dummy_call(), mips_o32_push_dummy_call(), mips_o64_push_dummy_call(), monitor_store_register(), pass_in_x(), phex(), procfs_meminfo(), remote_download_trace_state_variable(), remote_flash_erase(), and target_flash_erase().
char* phex_nz (ULONGEST l, int sizeof_l)
Print a ULONGEST in x format (hex, and NO leading zeros).
Parameters:
l the unsigned integer to print
sizeof_l size of integer to print; values of 2, 4, and 8 force sizes of the respective numbers of bytes, any other value will use sizeof(l)
Returns:
a string of hexadecimal digits, from static allocation
Definition at line 2891 of file utils.c.
References CELLSIZE, get_cell(), gdb::printing::long, phex_nz(), and xsnprintf().
Referenced by append_resumption(), core_addr_to_string_nz(), disassemble_dwarf_expression(), encode_source_string(), hex_string(), hex_string_custom(), host_address_to_string(), info_spu_dma_command(), info_spu_event_command(), info_spu_proxydma_command(), info_spu_signal_command(), locexpr_describe_location_piece(), m32r_load_section(), mips_common_breakpoint(), mips_request(), monitor_store_register(), monitor_vsprintf(), phex_nz(), record_full_restore(), record_full_save(), record_linux_msghdr(), record_linux_sockaddr(), record_linux_system_call(), remote_check_symbols(), remote_get_tracepoint_status(), remote_read_qxfer(), remote_search_memory(), remote_trace_find(), remote_write_qxfer(), solist_update_incremental(), spu_pseudo_register_write_spu(), store_register_using_P(), tfile_write_status(), tfile_write_uploaded_tp(), and tfile_write_uploaded_tsv().
char* plongest (LONGEST l)
Print a LONGEST in d format.
Parameters:
l the (signed) integer to print
Returns:
a string of decimal digits
Definition at line 2850 of file utils.c.
References decimal2str().
Referenced by c_type_print_base(), c_type_print_varspec_suffix(), collect_symbol(), debug_print_register(), disassemble_dwarf_expression(), do_set_command(), dump_subexp_body_standard(), fprint_target_auxv(), gcore_copy_callback(), gcore_create_callback(), gdbarch_dump(), gdbsim_xfer_memory(), gnu_xfer_memory(), i386_linux_intx80_sysenter_syscall_record(), locexpr_describe_location_piece(), m2_enum(), maint_print_c_tdesc_cmd(), memory_error_message(), mi_tsv_created(), mi_tsv_modified(), output_thread_groups(), pascal_type_print_base(), pascal_type_print_varspec_prefix(), print_enum_type(), print_exited_reason(), print_go_string(), print_symbol(), recursive_dump_type(), save_trace_state_variables(), scope_info(), signal_to_name_or_int(), simple_search_memory(), som_symtab_read(), target_xfer_partial(), trace_variable_command(), tvariables_info_1(), validate_actionline(), and windows_xfer_memory().
const char* print_core_address (struct gdbarch * gdbarch, CORE_ADDR address)
Return a string representation in hexadecimal notation of ADDRESS, which is suitable for printing.
Definition at line 2720 of file utils.c.
References gdbarch_addr_bit(), hex_string_custom(), and HOST_CHAR_BIT.
Referenced by dsbt_print_loadmap(), print_one_detail_ranged_breakpoint(), stap_gen_info_probes_table_values(), and ui_out_field_core_addr().
void void void void void void void void void void void print_spaces (int , struct ui_file *)
Definition at line 1099 of file utils.c.
References fputs_unfiltered(), and n_spaces().
Referenced by dump_die_1(), dump_die_shallow(), dump_symtab_1(), and print_symbol().
void print_spaces_filtered (int , struct ui_file *)
Definition at line 2427 of file utils.c.
References fputs_filtered(), and n_spaces().
Referenced by ada_val_print_array(), c_type_print_base(), c_val_print(), cli_spaces(), cp_print_value(), cp_print_value_fields(), default_print_one_register_info(), fprintfi_filtered(), generic_val_print(), java_print_value_fields(), java_type_print_base(), m2_print_array_contents(), m2_record_fields(), m2_val_print(), mt_registers_info(), pascal_object_print_value(), pascal_object_print_value_fields(), pascal_type_print_base(), pascal_val_print(), print_field_values(), print_record(), printfi_filtered(), sh64_do_fp_register(), sh64_do_register(), val_print_array_elements(), and val_print_packed_array_elements().
void print_sys_errmsg (const char * , int)
Definition at line 1020 of file utils.c.
References fprintf_unfiltered(), gdb_flush(), gdb_stderr, gdb_stdout, and safe_strerror().
Referenced by add_path(), check_syscall(), dead_procinfo(), print_source_lines_base(), proc_warn(), tui_set_source_content(), and windows_create_inferior().
void void void void void printf_filtered (const char * , ...)
void void void void void void void void void void printf_unfiltered (const char * , ...)
void void void void void void printfi_filtered (int , const char * , ...)
int producer_is_gcc_ge_4 (const char * producer)
Check for GCC >= 4.x according to the symtab->producer string. Return minor version (x) of 4.x in such case. If it is not GCC or it is GCC older than 4.x return -1. If it is GCC 5.x or higher return INT_MAX.
Definition at line 3449 of file utils.c.
Referenced by amd64_skip_xmm_prologue(), and process_full_comp_unit().
char* pulongest (ULONGEST l)
Print a ULONGEST in u format.
Parameters:
l the (unsigned) integer to print
Returns:
a string of decimal digits
Definition at line 2844 of file utils.c.
References decimal2str().
Referenced by amd64_linux_syscall_record(), c_print_token(), create_dwo_unit_in_dwp_v1(), create_dwo_unit_in_dwp_v2(), create_dwp_hash_table(), disassemble_dwarf_expression(), dump_die_shallow(), ia64_hpux_handle_load_event(), jit_bfd_try_read_symtab(), jit_register_code(), linux_info_proc(), locexpr_describe_location_1(), maintenance_translate_address(), mbpy_str(), open_and_init_dwp_file(), record_full_get_bookmark(), record_full_goto_entry(), record_full_info(), record_linux_system_call(), rs6000_aix_shared_library_to_xml(), simple_search_memory(), target_fileio_pread(), target_fileio_pwrite(), and target_verify_memory().
int putchar_filtered (int c)
Write a single char to gdb_stdout, filtered.
Definition at line 2126 of file utils.c.
References fputc_filtered(), and gdb_stdout.
Referenced by info_checkpoints_command(), and info_common_command_for_block().
int putchar_unfiltered (int c)
Write a single char to gdb_stdout, unfiltered.
Definition at line 2114 of file utils.c.
References gdb_stdout, and ui_file_write().
Referenced by clear_command(), load_srec(), monitor_wait(), monitor_wait_filter(), putpkt_binary(), and unwind_command().
void puts_debug (char * prefix, char * string, char * suffix)
Put out the given string, with special characters escaped, and enclosed by the given prefix and suffix strings.
Definition at line 2155 of file utils.c.
References fprintf_unfiltered(), fputc_unfiltered(), fputs_unfiltered(), and gdb_stdlog.
Referenced by load_srec(), and readchar().
void puts_filtered (const char *)
Write a string to gdb_stdout, filtered.
Definition at line 2391 of file utils.c.
References fputs_filtered(), and gdb_stdout.
Referenced by begin_line(), display_descriptor(), display_info(), display_page_table(), display_ptable_entry(), display_selector(), display_selectors(), do_one_display(), environment_info(), exec_files_info(), frame_info(), go32_pde(), go32_pte(), go32_pte_for_address(), go32_sldt(), go32_sysinfo(), linux_info_proc(), list_overlays_command(), macro_inform_no_debuginfo(), maintenance_check_psymtabs(), packet_command(), path_info(), print_bit_vector(), print_cplus_stuff(), print_mem(), print_packet(), recursive_dump_type(), remote_detach_1(), remote_disconnect(), remote_files_info(), remote_open_1(), restore_section_callback(), show_directories_1(), and wrap_here().
void puts_filtered_tabular (char * string, int width, int right)
Print input string to gdb_stdout, filtered, with wrap, arranging strings in columns of n chars. String can be right or left justified in the column. Never prints trailing spaces. String should never be longer than width.
Definition at line 1936 of file utils.c.
References fputs_filtered(), gdb_assert, and gdb_stdout.
Referenced by classes_info(), and selectors_info().
void puts_unfiltered (const char *)
Write a string to gdb_stdout, unfiltered.
Definition at line 2397 of file utils.c.
References fputs_unfiltered(), and gdb_stdout.
Referenced by command_line_handler(), command_line_input(), i386_show_dr(), jit_bfd_try_read_symtab(), and mips_show_dr().
int query (const char * , ...)
void reinitialize_more_filter (void)
Definition at line 1872 of file utils.c.
Referenced by avr_io_reg_read_command(), command_handler(), command_loop(), prompt_for_continue(), and tui_rl_command_key().
void reset_prompt_for_continue_wait_time (void)
Definition at line 1854 of file utils.c.
Referenced by make_command_stats_cleanup().
char* safe_strerror (int)
A host-specific version of strerror.
This is defined in *-hdep.c, e.g., posix-hdep.c.
Definition at line 50 of file mingw-hdep.c.
References len, strerror(), and xsnprintf().
Referenced by amd64_linux_disable_btrace(), amd64_linux_enable_btrace(), captured_main(), close_with_trace(), create_tty_session(), ctf_save_fseek(), ctf_save_write(), ctf_save_write_metadata(), ctf_start(), darwin_attach(), darwin_decode_message(), darwin_detach(), darwin_kill_inferior(), darwin_pre_ptrace(), darwin_ptrace(), darwin_stop_inferior(), detach_callback(), displaced_step_prepare(), do_attach(), dsbt_current_sos(), fetch_register(), fork_inferior(), frv_current_sos(), gnu_read_inferior(), gnu_wait(), go32_terminal_inferior(), go32_terminal_ours(), hardwire_raw(), hppa_hpux_fetch_register(), hppa_hpux_store_register(), i386_linux_disable_btrace(), i386_linux_enable_btrace(), ia64_linux_fetch_register(), ia64_linux_store_register(), inf_continue(), inf_ptrace_fetch_register(), inf_ptrace_store_register(), inf_ptrace_wait(), inf_set_pid(), inf_set_traced(), inf_signal(), inf_startup(), info_port_rights(), ioctl_with_trace(), irix_current_sos(), irix_open_symbol_file_object(), kill_callback(), lin_lwp_attach_lwp(), linux_nat_create_inferior(), linux_nat_wait_1(), linux_thread_alive(), make_proc(), mi_cmd_env_pwd(), mips_readchar(), mips_receive_packet(), monitor_write(), new_tty(), open_symbol_file_object(), open_with_trace(), perror_string(), pipe_windows_open(), print_sys_errmsg(), proc_restore_exc_port(), proc_steal_exc_port(), proc_update_sc(), procfs_create_inferior(), procfs_meminfo(), procfs_open(), procfs_pidlist(), procfs_store_registers(), ptrace_check(), pwd_command(), remote_hostio_error(), restore_binary_file(), restore_section_callback(), rs6000_wait(), S_msg_sig_post_untraced_reply(), S_proc_wait_reply(), save_breakpoints(), scalar_binop(), serial_logchar(), shell_escape(), som_current_sos(), som_open_symbol_file_object(), spu_child_wait(), steal_exc_port(), stop_callback(), stop_wait_callback(), store_register(), svr4_read_so_list(), terminal_ours_1(), tfile_start(), thread_takeover_sc_cmd(), unpush_and_perror(), wait_for(), and wait_with_trace().
char* savestring (const char * ptr, size_t len)
Make a copy of a string, using freshly-allocated space and limiting to the given length. Space is gotten using xmalloc.
Parameters:
ptr pointer to the string to be copied
len maximum length to copy. If the original string is longer, then the copy will be truncated to len bytes.
Definition at line 156 of file common-utils.c.
References len, memcpy(), p, and xmalloc().
Referenced by add_path(), break_range_command(), cd_command(), copy_token_string(), decode_static_tracepoint_spec(), extract_exception_regexp(), find_condition_and_thread(), gnuv3_get_typename_from_type_info(), init_breakpoint_sal(), lookup_symbol_file(), parse_frame_specification_1(), parse_probes(), process_next_line(), read_member_functions(), read_one_struct_field(), scan_expression_with_cleanup(), scan_filename_with_cleanup(), set_environment_command(), solib_find(), strace_marker_create_sals_from_address(), stringify_collection_list(), trace_variable_command(), and watch_command_1().
struct cleanup* set_batch_flag_and_make_cleanup_restore_page_info (void) [read]
Definition at line 1721 of file utils.c.
References batch_flag, init_page_info(), make_cleanup_restore_integer(), and make_cleanup_restore_page_info().
Referenced by execute_command_to_string().
int strcmp_iw (const char * , const char *)
Definition at line 2474 of file utils.c.
References case_sensitive_off, and case_sensitive_on.
Referenced by check_field(), dict_iter_name_first(), dict_iter_name_next(), do_search_struct_field(), dw2_lookup_symbol(), find_method_list(), find_methods(), function_name_is_marked_for_skip(), iterate_over_all_matching_symtabs(), lookup_struct_elt_type(), lookup_symbol_aux_psymtabs(), read_member_functions(), search_struct_method(), skip_prologue_sal(), typy_getitem(), and typy_has_key().
int strcmp_iw_ordered (const char * string1, const char * string2)
This is like strcmp except that it ignores whitespace and treats '(' as the first non-NULL character in terms of ordering. Like strcmp (and unlike strcmp_iw), it returns negative if STRING1 < STRING2, 0 if STRING2 = STRING2, and positive if STRING1 > STRING2 according to that ordering.
If a list is sorted according to this function and if you want to find names in the list that match some fixed NAME according to strcmp_iw(LIST_ELT, NAME), then the place to start looking is right where this function would put NAME.
This function must be neutral to the CASE_SENSITIVITY setting as the user may choose it during later lookup. Therefore this function always sorts primarily case-insensitively and secondarily case-sensitively.
Here are some examples of why using strcmp to sort is a bad idea:
Whitespace example:
Say your partial symtab contains: "foo<char *>", "goo". Then, if we try to do a search for "foo<char*>", strcmp will locate this after "foo<char *>" and before "goo". Then lookup_partial_symbol will start looking at strings beginning with "goo", and will never see the correct match of "foo<char *>".
Parenthesis example:
In practice, this is less like to be an issue, but I'll give it a shot. Let's assume that '$' is a legitimate character to occur in symbols. (Which may well even be the case on some systems.) Then say that the partial symbol table contains "foo$" and "foo(int)". strcmp will put them in this order, since '$' < '('. Now, if the user searches for "foo", then strcmp will sort "foo" before "foo$". Then lookup_partial_symbol will notice that strcmp_iw("foo$", "foo") is false, so it won't proceed to the actual match of "foo(int)" with "foo".
Definition at line 2502 of file utils.c.
References case_sensitive_off, and case_sensitive_on.
Referenced by compare_names_with_case(), compare_psymbols(), and lookup_partial_symbol().
int streq (const char * lhs, const char * rhs)
A simple comparison function with opposite semantics to strcmp.
Definition at line 2580 of file utils.c.
Referenced by _initialize_ada_language(), and ambiguous_names_p().
CORE_ADDR string_to_core_addr (const char * my_string)
Parse a decimal or hexadecimal string of digits, and return a CORE_ADDR. A hexadecimal string must begin with a "0x"; any invalid digits result in an error().
Definition at line 3023 of file utils.c.
References _, and error().
Referenced by gdb_block_vars(), gdb_incr_addr(), gdb_set_mem(), gdb_update_mem(), ia64_hpux_xfer_solib_got(), mi_cmd_var_create(), and variable_create().
ULONGEST strtoulst (const char * num, const char ** trailer, int base)
As for strtoul, but for ULONGEST results.
Definition at line 3241 of file utils.c.
References digit_to_int(), HIGH_BYTE_POSN, int, is_digit_in_base(), and ULONGEST.
Referenced by generic_load(), get_insn_number(), info_spu_event_command(), info_spu_signal_command(), linux_info_proc(), monitor_load(), processInt(), read_mapping(), spu_pseudo_register_read_spu(), spu_symbol_file_add_from_memory(), and spu_xfer_partial().
int subset_compare (char * string_to_compare, char * template_string)
Answer whether string_to_compare is a full or partial match to template_string. The partial match must be in sequence starting at index 0.
Definition at line 2587 of file utils.c.
Referenced by backtrace_command(), tui_set_focus(), and tui_set_layout_for_display_command().
void substitute_path_component (char ** stringp, const char * from, const char * to)
Definition at line 3517 of file utils.c.
References memcpy(), memmove(), string, strstr(), and xrealloc().
Referenced by VEC().
void throw_perror_with_name (enum errors errcode, const char * string)
Definition at line 979 of file utils.c.
References _, make_cleanup(), perror_string(), throw_error(), and xfree().
Referenced by perror_with_name().
void verror (const char * fmt, va_list ap)
void vfatal (const char * fmt, va_list ap)
void void vfprintf_filtered (struct ui_file * , const char * , va_list)
void void void void void void void void vfprintf_unfiltered (struct ui_file * , const char * , va_list)
void vprintf_filtered (const char * , va_list)
void void void void void void void vprintf_unfiltered (const char * , va_list)
void void void void void void void vwarning (const char * , va_list args)
Like warning, but takes a va_list of arguments.
void void void void void void warning (const char * , ...)
Print a warning message.
The first argument STRING is the warning message, used as a fprintf string, and the remaining args are passed as arguments to it. The primary difference between warnings and errors is that a warning does not force the return to command level.
void wrap_here (char *)
Definition at line 1900 of file utils.c.
References _, chars_printed, fputs_unfiltered(), gdb_stdout, internal_error(), puts_filtered(), and wrap_buffer.
Referenced by ATTRIBUTE_PRINTF(), c_type_print_args(), c_type_print_base(), c_type_print_template_args(), captured_main(), cli_wrap_hint(), command_line_handler(), command_line_input(), cp_print_value_fields(), cp_type_print_derivation_info(), cp_type_print_method_args(), dbx_psymtab_to_symtab_1(), dump_objfile(), dump_psymtab(), dump_psymtabs_for_objfile(), echo_command(), f_type_print_base(), fputs_maybe_filtered(), frame_info(), help_list(), java_print_value_fields(), java_type_print_base(), java_value_print(), line_info(), m2_enum(), m2_print_type(), m2_procedure(), m2_record_fields(), maintenance_check_symtabs(), maintenance_info_psymtabs(), maintenance_info_sections(), maintenance_info_symtabs(), mi_wrap_hint(), mips_error(), output_command_const(), output_source_filename(), pascal_object_print_value_fields(), pascal_print_func_args(), pascal_type_print_base(), print_any_exception(), print_array_type(), print_enum_type(), print_field_values(), print_flush(), print_formatted(), print_func_type(), print_section_info(), psymtab_to_symtab_1(), require_partial_symbols(), reread_symbols(), symbol_file_add_with_addrs(), trace_find_line_command(), val_print_array_elements(), val_print_packed_array_elements(), vwarning(), and xcoff_psymtab_to_symtab_1().
int int int yquery (const char * , ...)
Variable Documentation
void(* deprecated_error_begin_hook)(void)
Definition at line 90 of file utils.c.
Referenced by clear_interpreter_hooks(), gdbtk_add_hooks(), and print_flush().
struct ui_file* gdb_stderr
ui_file stream for serious error notifications
Definition at line 77 of file main.c.
Referenced by _initialize_sol_thread(), ada_lookup_struct_elt_type(), add_language(), add_path(), annotate_error_begin(), arm_get_next_pc_raw(), arm_linux_copy_svc(), ATTRIBUTE_PRINTF(), avr_io_reg_read_command(), avr_scan_prologue(), can_dump_core(), captured_main(), catch_command_errors(), catch_command_errors_const(), catch_errors(), catch_exceptions_with_msg(), check_status_exception_catchpoint(), clear_complaints(), command_line_handler(), command_line_input(), core_open(), create_breakpoint(), cris_supply_gregset(), darwin_execvp(), dbx_psymtab_to_symtab_1(), dbx_read_symtab(), disable_current_display(), do_attach(), do_gdb_disassembly(), dos_close(), dos_setbaudrate(), dump_die_for_error(), dwarf2_build_psymtabs(), enable_breakpoint_disp(), error_clbk(), execute_command_to_string(), fetch_register(), find_new_threads_once(), find_oload_champ(), fork_inferior(), gdb_disable_readline(), gdb_os_evprintf_filtered(), gdb_setup_readline(), gdb_wait_for_event(), gdbsim_fetch_register(), gdbtk_call_wrapper(), gdbtk_command_loop(), gdbtk_fputs(), gdbtk_interpreter_resume(), get_core_registers(), handle_redirections(), hardwire_raw(), inf_ptrace_wait(), inferior_event_handler(), keep_going(), libunwind_load(), linux_child_follow_fork(), mep_gdbarch_init(), mi_interpreter_resume(), mips_check_lsi_error(), mips_common_breakpoint(), mips_eabi_return_value(), mips_error(), mips_expect_download(), mips_n32n64_return_value(), mips_o32_return_value(), mips_o64_return_value(), mips_xfer_register(), monitor_remove_breakpoint(), monitor_wait(), monitor_wait_filter(), monitor_write(), net_open(), parser_fprintf(), pmon_check_ack(), pmon_makeb64(), pop_all_targets_above(), pop_output_files(), print_flush(), print_sys_errmsg(), procfs_pidlist(), procfs_set_exec_trap(), procfs_store_registers(), ps_plog(), push_target(), range_error(), rank_one_type(), read_dbx_symtab(), reload_shared_libraries_1(), remote_get_noisy_reply(), remote_get_trace_status(), rs6000_wait(), s390_remove_watchpoint(), safe_execute_command(), safe_parse_type(), safe_symbol_file_add(), safe_symbol_file_add_cleanup(), save_gdb_index_command(), send_srec(), ser_base_read_error_fd(), set_logging_redirect(), shell_escape(), should_stop_exception(), skip_file_command(), skip_function_command(), solib_read_symbols(), solib_svr4_r_map(), source_gdb_script_for_objfile(), start_event_loop(), store_register(), target_is_pushed(), terminal_ours_1(), thread_db_find_new_threads_silently(), tui_alloc_source_buffer(), tui_initialize_io(), tui_setup_io(), update_solib_list(), varobj_create(), vwarning(), wait_for(), xcoff_psymtab_to_symtab_1(), and xcoff_read_symtab().
struct ui_file* gdb_stdin
ui_file stream for input
Definition at line 79 of file main.c.
Referenced by captured_main().
struct ui_file* gdb_stdlog
Log/debug/trace messages that should bypass normal stdout/stderr filtering. For moment, always call this stream using _unfiltered. In the very near future that restriction shall be removed - either call shall be unfiltered. (cagney 1999-06-13).
Definition at line 78 of file main.c.
Referenced by aarch64_analyze_prologue(), aarch64_extract_return_value(), aarch64_handle_unaligned_watchpoint(), aarch64_linux_insert_hw_breakpoint(), aarch64_linux_insert_watchpoint(), aarch64_linux_prepare_to_resume(), aarch64_linux_remove_hw_breakpoint(), aarch64_linux_remove_watchpoint(), aarch64_push_dummy_call(), aarch64_return_value(), aarch64_show_debug_reg_state(), aarch64_store_return_value(), add_pe_exported_sym(), add_pe_forwarded_sym(), allocate_psymtab(), allocate_symtab(), amd64_displaced_step_copy_insn(), amd64_displaced_step_fixup(), amd64_relocate_instruction(), amd64_windows_find_unwind_info(), amd64_windows_frame_decode_insns(), amd64_windows_frame_prev_register(), arm_analyze_prologue(), arm_copy_alu_imm(), arm_copy_alu_reg(), arm_copy_alu_shifted_reg(), arm_copy_b_bl_blx(), arm_copy_block_xfer(), arm_copy_bx_blx_reg(), arm_copy_copro_load_store(), arm_copy_extra_ld_st(), arm_copy_ldr_str_ldrb_strb(), arm_copy_preload(), arm_copy_preload_reg(), arm_copy_svc(), arm_copy_undef(), arm_copy_unmodified(), arm_copy_unpred(), arm_displaced_init_closure(), arm_linux_cleanup_svc(), arm_linux_copy_svc(), arm_linux_displaced_step_copy_insn(), arm_pc_is_thumb(), arm_process_displaced_insn(), arm_process_record(), arm_push_dummy_call(), async_remote_interrupt(), async_remote_interrupt_twice(), auto_load_objfile_script(), auto_load_objfile_script_1(), auto_load_safe_path_vec_update(), bpstat_what(), build_table(), build_type_unit_groups(), cancel_breakpoint(), captured_mi_execute_command(), chain_candidate(), check_binary_download(), check_zombie_leaders(), cleanup_block_load_all(), cleanup_block_load_pc(), cleanup_block_store_pc(), cleanup_svc(), clear_proceed_status_thread(), context_switch(), create_debug_types_hash_table(), create_dwo_cu(), create_dwo_cu_reader(), create_dwo_unit_in_dwp_v1(), create_dwo_unit_in_dwp_v2(), create_new_frame(), create_sentinel_frame(), debug_can_evaluate_probe_arguments(), debug_print_register(), debug_qf_dump(), debug_qf_expand_all_symtabs(), debug_qf_expand_symtabs_for_function(), debug_qf_expand_symtabs_matching(), debug_qf_expand_symtabs_with_fullname(), debug_qf_find_last_source_symtab(), debug_qf_find_pc_sect_symtab(), debug_qf_forget_cached_source_info(), debug_qf_has_symbols(), debug_qf_lookup_symbol(), debug_qf_map_matching_symbols(), debug_qf_map_symbol_filenames(), debug_qf_map_symtabs_matching_filename(), debug_qf_print_stats(), debug_qf_relocate(), debug_reg_change_callback(), debug_sym_compile_to_ax(), debug_sym_evaluate_probe_argument(), debug_sym_finish(), debug_sym_get_probe_argument_count(), debug_sym_init(), debug_sym_new_init(), debug_sym_offsets(), debug_sym_read(), debug_sym_read_linetable(), debug_sym_read_psymbols(), debug_sym_relocate(), debug_sym_relocate_probe(), debug_to_can_accel_watchpoint_condition(), debug_to_can_run(), debug_to_can_use_hw_breakpoint(), debug_to_files_info(), debug_to_has_exited(), debug_to_insert_breakpoint(), debug_to_insert_exec_catchpoint(), debug_to_insert_fork_catchpoint(), debug_to_insert_hw_breakpoint(), debug_to_insert_vfork_catchpoint(), debug_to_insert_watchpoint(), debug_to_load(), debug_to_open(), debug_to_pid_to_exec_file(), debug_to_post_attach(), debug_to_post_startup_inferior(), debug_to_prepare_to_store(), debug_to_rcmd(), debug_to_region_ok_for_hw_watchpoint(), debug_to_remove_breakpoint(), debug_to_remove_exec_catchpoint(), debug_to_remove_fork_catchpoint(), debug_to_remove_hw_breakpoint(), debug_to_remove_vfork_catchpoint(), debug_to_remove_watchpoint(), debug_to_stop(), debug_to_stopped_by_watchpoint(), debug_to_stopped_data_address(), debug_to_terminal_inferior(), debug_to_terminal_info(), debug_to_terminal_init(), debug_to_terminal_ours(), debug_to_terminal_ours_for_output(), debug_to_terminal_save_ours(), debug_to_thread_architecture(), debug_to_watchpoint_addr_within_range(), decode_add_sub_imm(), decode_adrp(), decode_b(), decode_bcond(), decode_br(), decode_cb(), decode_eret(), decode_movz(), decode_orr_shifted_register_x(), decode_ret(), decode_stp_offset(), decode_stp_offset_wb(), decode_stur(), decode_tb(), deprecated_debug_xfer_memory(), detach_callback(), displaced_read_reg(), displaced_step_fixup(), displaced_step_prepare(), displaced_step_restore(), displaced_write_reg(), dsbt_current_sos(), dump_die(), dump_mem(), dwarf2_build_psymtabs_hard(), elf_symfile_read(), enable_break(), enable_break2(), execute_command_to_string(), fetch_regs_kernel_thread(), fetch_regs_user_thread(), file_is_auto_load_safe(), filename_is_in_auto_load_safe_path_vec(), filename_is_in_pattern_1(), find_unwind_entry(), fixup_riprel(), frame_debug_got_null_frame(), frame_id_eq(), frame_id_inner(), frame_id_p(), frame_unwind_arch(), frame_unwind_pc_if_available(), frame_unwind_register_value(), frv_current_sos(), gdb_cntrl_c(), gdb_disable_readline(), gdb_setup_readline(), gdbarch_addr_bit(), gdbarch_addr_bits_remove(), gdbarch_address_class_name_to_type_flags(), gdbarch_address_class_type_flags(), gdbarch_address_class_type_flags_to_name(), gdbarch_address_to_pointer(), gdbarch_adjust_breakpoint_address(), gdbarch_auto_charset(), gdbarch_auto_wide_charset(), gdbarch_ax_pseudo_register_collect(), gdbarch_ax_pseudo_register_push_stack(), gdbarch_believe_pcc_promotion(), gdbarch_bfd_arch_info(), gdbarch_bits_big_endian(), gdbarch_breakpoint_from_pc(), gdbarch_byte_order(), gdbarch_byte_order_for_code(), gdbarch_call_dummy_location(), gdbarch_cannot_fetch_register(), gdbarch_cannot_step_breakpoint(), gdbarch_cannot_store_register(), gdbarch_char_signed(), gdbarch_coff_make_msymbol_special(), gdbarch_convert_from_func_ptr_addr(), gdbarch_convert_register_p(), gdbarch_core_info_proc(), gdbarch_core_pid_to_str(), gdbarch_core_read_description(), gdbarch_core_regset_sections(), gdbarch_core_xfer_shared_libraries(), gdbarch_core_xfer_shared_libraries_aix(), gdbarch_decr_pc_after_break(), gdbarch_deprecated_fp_regnum(), gdbarch_deprecated_function_start_offset(), gdbarch_displaced_step_copy_insn(), gdbarch_displaced_step_fixup(), gdbarch_displaced_step_free_closure(), gdbarch_displaced_step_hw_singlestep(), gdbarch_displaced_step_location(), gdbarch_double_bit(), gdbarch_double_format(), gdbarch_dummy_id(), gdbarch_dwarf2_addr_size(), gdbarch_dwarf2_reg_to_regnum(), gdbarch_ecoff_reg_to_regnum(), gdbarch_elf_make_msymbol_special(), gdbarch_elfcore_write_linux_prpsinfo(), gdbarch_fast_tracepoint_valid_at(), gdbarch_fetch_pointer_argument(), gdbarch_fetch_tls_load_module_address(), gdbarch_find_by_info(), gdbarch_find_memory_regions(), gdbarch_float_bit(), gdbarch_float_format(), gdbarch_fp0_regnum(), gdbarch_frame_align(), gdbarch_frame_args_skip(), gdbarch_frame_num_args(), gdbarch_frame_red_zone_size(), gdbarch_gcore_bfd_target(), gdbarch_gdb_signal_from_target(), gdbarch_gdb_signal_to_target(), gdbarch_gen_return_address(), gdbarch_get_longjmp_target(), gdbarch_get_siginfo_type(), gdbarch_get_syscall_number(), gdbarch_half_bit(), gdbarch_half_format(), gdbarch_has_dos_based_file_system(), gdbarch_has_global_breakpoints(), gdbarch_has_global_solist(), gdbarch_has_shared_address_space(), gdbarch_have_nonsteppable_watchpoint(), gdbarch_in_function_epilogue_p(), gdbarch_in_solib_return_trampoline(), gdbarch_info_proc(), gdbarch_inner_than(), gdbarch_int_bit(), gdbarch_integer_to_address(), gdbarch_iterate_over_objfiles_in_search_order(), gdbarch_long_bit(), gdbarch_long_double_bit(), gdbarch_long_double_format(), gdbarch_long_long_align_bit(), gdbarch_long_long_bit(), gdbarch_make_corefile_notes(), gdbarch_max_insn_length(), gdbarch_memory_insert_breakpoint(), gdbarch_memory_remove_breakpoint(), gdbarch_num_pseudo_regs(), gdbarch_num_regs(), gdbarch_osabi(), gdbarch_overlay_update(), gdbarch_pc_regnum(), gdbarch_pointer_to_address(), gdbarch_print_float_info(), gdbarch_print_insn(), gdbarch_print_registers_info(), gdbarch_print_vector_info(), gdbarch_process_record(), gdbarch_process_record_signal(), gdbarch_ps_regnum(), gdbarch_pseudo_register_read(), gdbarch_pseudo_register_read_value(), gdbarch_pseudo_register_write(), gdbarch_ptr_bit(), gdbarch_push_dummy_call(), gdbarch_push_dummy_code(), gdbarch_ravenscar_ops(), gdbarch_read_pc(), gdbarch_record_special_symbol(), gdbarch_register(), gdbarch_register_name(), gdbarch_register_reggroup_p(), gdbarch_register_sim_regno(), gdbarch_register_to_value(), gdbarch_register_type(), gdbarch_regset_from_core_section(), gdbarch_relocate_instruction(), gdbarch_remote_breakpoint_from_pc(), gdbarch_remote_register_number(), gdbarch_return_in_first_hidden_param_p(), gdbarch_return_value(), gdbarch_sdb_reg_to_regnum(), gdbarch_short_bit(), gdbarch_single_step_through_delay(), gdbarch_skip_main_prologue(), gdbarch_skip_permanent_breakpoint(), gdbarch_skip_prologue(), gdbarch_skip_solib_resolver(), gdbarch_skip_trampoline_code(), gdbarch_software_single_step(), gdbarch_sofun_address_maybe_missing(), gdbarch_solib_symbols_extension(), gdbarch_sp_regnum(), gdbarch_stab_reg_to_regnum(), gdbarch_stabs_argument_has_addr(), gdbarch_stap_gdb_register_prefix(), gdbarch_stap_gdb_register_suffix(), gdbarch_stap_integer_prefix(), gdbarch_stap_integer_suffix(), gdbarch_stap_is_single_operand(), gdbarch_stap_parse_special_token(), gdbarch_stap_register_indirection_prefix(), gdbarch_stap_register_indirection_suffix(), gdbarch_stap_register_prefix(), gdbarch_stap_register_suffix(), gdbarch_static_transform_name(), gdbarch_target_desc(), gdbarch_tdep(), gdbarch_unwind_pc(), gdbarch_unwind_sp(), gdbarch_update_p(), gdbarch_value_from_register(), gdbarch_value_to_register(), gdbarch_vbit_in_delta(), gdbarch_virtual_frame_pointer(), gdbarch_vtable_function_descriptors(), gdbarch_write_pc(), gdbsim_close(), gdbsim_create_inferior(), gdbsim_detach(), gdbsim_fetch_register(), gdbsim_files_info(), gdbsim_kill(), gdbsim_load(), gdbsim_mourn_inferior(), gdbsim_open(), gdbsim_resume_inferior(), gdbsim_store_register(), gdbsim_wait(), gdbsim_xfer_memory(), gdbtk_fputs(), gdbtk_interpreter_resume(), get_frame_func_if_available(), get_frame_id(), get_pending_status(), get_prev_frame_1(), get_prev_frame_raw(), getpkt_or_notif_sane_1(), handle_inferior_event(), handle_notification(), handle_redirections(), handle_syscall_event(), handle_vfork_child_exec_or_exit(), hppa_fallback_frame_cache(), hppa_frame_cache(), i386_displaced_step_copy_insn(), i386_displaced_step_fixup(), i386_process_record(), i386_relocate_instruction(), ia64_dummy_id(), ia64_frame_this_id(), ia64_sigtramp_frame_this_id(), init_cutu_and_read_dies(), init_cutu_and_read_dies_no_follow(), insert_exception_resume_breakpoint(), insert_exception_resume_from_probe(), insert_longjmp_resume_breakpoint(), insert_step_resume_breakpoint_at_sal_1(), install_minimal_symbols(), jit_bfd_try_read_symtab(), jit_breakpoint_re_set_internal(), jit_frame_sniffer(), jit_inferior_init(), jit_read_descriptor(), jit_reader_load(), jit_reader_try_read_symtab(), jit_register_code(), jit_unwind_reg_set_impl(), kill_callback(), kill_wait_callback(), lin_lwp_attach_lwp(), linux_child_follow_fork(), linux_handle_extended_wait(), linux_handle_syscall_trap(), linux_nat_attach(), linux_nat_detach(), linux_nat_filter_event(), linux_nat_post_attach_wait(), linux_nat_resume(), linux_nat_stop_lwp(), linux_nat_wait(), linux_nat_wait_1(), linux_thread_alive(), lm_base(), lookup_dwo_cutu(), m32r_close(), m32r_create_inferior(), m32r_detach(), m32r_fetch_register(), m32r_insert_breakpoint(), m32r_insert_watchpoint(), m32r_kill(), m32r_mourn_inferior(), m32r_open(), m32r_prepare_to_store(), m32r_remove_breakpoint(), m32r_remove_watchpoint(), m32r_resume(), m32r_stop(), m32r_store_register(), m32r_wait(), m32r_xfer_memory(), maybe_clear_ignore_sigint(), mi_cmd_var_create(), mi_interpreter_resume(), mips_eabi_push_dummy_call(), mips_expect_timeout(), mips_gdbarch_init(), mips_n32n64_push_dummy_call(), mips_o32_push_dummy_call(), mips_o64_push_dummy_call(), mips_readchar(), mips_receive_packet(), mips_xfer_register(), monitor_debug(), monitor_expect(), monitor_interrupt(), monitor_printf(), monitor_printf_noecho(), monitor_read_memory(), moxie_process_record(), nios2_analyze_prologue(), open_and_init_dwo_file(), open_and_init_dwp_file(), packet_ok(), parse_exp_in_context_1(), pass_in_v(), pass_in_x(), pass_on_stack(), pdc_alloc(), pdc_dealloc(), pdc_read_data(), pdc_read_regs(), pdc_realloc(), pdc_symbol_addrs(), pdc_write_data(), pdc_write_regs(), pop_output_files(), ppc_displaced_step_fixup(), prepare_for_detach(), prepare_to_proceed(), prepare_to_wait(), print_target_wait_results(), proceed(), proceed_after_vfork_done(), process_psymtab_comp_unit_reader(), process_queue(), ptrace_check(), push_stop_reply(), putpkt_binary(), puts_debug(), read_comp_units_from_section(), read_cutu_die_from_dwo(), read_die_and_siblings(), read_frame(), read_full_die(), read_pe_exported_syms(), record_full_arch_list_add(), record_full_arch_list_add_end(), record_full_arch_list_add_mem(), record_full_arch_list_add_reg(), record_full_close(), record_full_core_kill(), record_full_exec_insn(), record_full_get_bookmark(), record_full_goto_bookmark(), record_full_open(), record_full_open_1(), record_full_restore(), record_full_save(), record_full_sig_handler(), record_full_wait_1(), record_full_xfer_partial(), record_linux_msghdr(), record_linux_sockaddr(), record_linux_system_call(), reinit_frame_cache(), remote_notif_ack(), remote_notif_get_pending_events(), remote_notif_parse(), remote_notif_remove_queued_reply(), remote_stop(), reschedule(), resume(), resume_lwp(), resume_stopped_resumed_lwps(), s390_displaced_step_fixup(), sdireset_command(), sdistatus_command(), select_event_lwp(), send_g_packet(), ser_base_async(), serial_readchar(), serial_write(), set_logging_redirect(), sigchld_handler(), simple_displaced_step_copy_insn(), solib_aix_free_so(), solib_aix_get_toc_value(), stap_parse_probe_arguments(), stop_and_resume_callback(), stop_callback(), stop_stepping(), stop_wait_callback(), store_regs_kernel_thread(), store_regs_user_thread(), tailcall_dump(), target_attach(), target_close(), target_core_of_thread(), target_create_inferior(), target_detach(), target_disconnect(), target_fileio_close(), target_fileio_open(), target_fileio_pread(), target_fileio_pwrite(), target_fileio_readlink(), target_fileio_unlink(), target_find_new_threads(), target_flash_done(), target_flash_erase(), target_follow_fork(), target_get_section_table(), target_info_proc(), target_insert_mask_watchpoint(), target_kill(), target_mourn_inferior(), target_pass_signals(), target_program_signals(), target_remove_mask_watchpoint(), target_resume(), target_search_memory(), target_thread_address_space(), target_thread_alive(), target_verify_memory(), target_wait(), target_xfer_partial(), thumb2_copy_alu_imm(), thumb2_copy_b_bl_blx(), thumb2_copy_block_xfer(), thumb2_copy_copro_load_store(), thumb2_copy_load_literal(), thumb2_copy_load_reg_imm(), thumb2_copy_preload(), thumb2_copy_table_branch(), thumb_32bit_copy_undef(), thumb_analyze_prologue(), thumb_copy_16bit_ldr_literal(), thumb_copy_alu_reg(), thumb_copy_b(), thumb_copy_bx_blx_reg(), thumb_copy_cbnz_cbz(), thumb_copy_pc_relative_32bit(), thumb_copy_pop_pc_16bit(), thumb_copy_svc(), thumb_copy_unmodified_16bit(), thumb_copy_unmodified_32bit(), thumb_decode_pc_relative_16bit(), thumb_process_displaced_insn(), tui_setup_io(), uninstall_variable(), value_fetch_lazy(), VEC(), vfprintf_unfiltered(), wait_for_inferior(), wait_lwp(), and xtensa_push_dummy_call().
struct ui_file* gdb_stdout
ui_file stream for normal results
Definition at line 76 of file main.c.
Referenced by _initialize_cli_interp(), ada_lookup_struct_elt_type(), address_info(), agent_eval_command_one(), append_command(), apropos_command(), args_info(), ATTRIBUTE_PRINTF(), backtrace_command_1(), binary_append_command(), binary_dump_command(), call_site_find_chain(), child_terminal_info(), cli_interpreter_exec(), cli_interpreter_resume(), command_line_handler(), command_line_input(), darwin_attach(), darwin_detach(), dbx_psymtab_to_symtab_1(), dbx_read_symtab(), deprecated_show_value_hack(), describe_other_breakpoints(), display_gdb_prompt(), display_info(), do_examine(), do_one_display(), do_show_command(), dump_command(), dump_fn_fieldlists(), dump_objfile(), dump_psymtabs_for_objfile(), dwarf2_evaluate_loc_desc_full(), dwarf2_read_symtab(), dwarf2_tailcall_sniffer_first(), echo_command(), execute_command_to_string(), extended_remote_attach_1(), fbsd_find_memory_regions(), find_command(), finish_command_continuation(), float_info(), follow_exec(), fork_inferior(), fputs_maybe_filtered(), frame_info(), gcore_command(), gcore_create_callback(), gdb_disable_readline(), gdb_disassembly(), gdb_os_printf_filtered(), gdb_os_vprintf_filtered(), gdb_readline(), gdb_setup_readline(), gdb_wait_for_event(), gdbtk_call_wrapper(), gdbtk_interpreter_resume(), gdbtk_load_asm(), gdbtk_readline(), generic_load(), get_set_value(), gnu_attach(), gnu_detach(), go32_info_dos_command(), handle_command(), handle_inferior_event(), handle_redirections(), help_command(), ihex_dump_command(), inf_ptrace_attach(), inf_ptrace_detach(), info_auxv_command(), info_checkpoints_command(), info_command(), info_common_command_for_block(), info_macro_command(), info_spu_command(), info_w32_command(), init_page_info(), insert_bp_location(), jump_command(), line_info(), list_overlays_command(), load_srec(), locals_info(), m2_printstr(), m32r_load(), m32r_load_section(), m32r_upload_command(), macro_command(), macro_expand_command(), macro_expand_once_command(), maint_agent_printf_command(), maint_cplus_command(), maintenance_check_psymtabs(), maintenance_command(), maintenance_info_command(), maintenance_info_psymtabs(), maintenance_print_architecture(), maintenance_print_command(), maintenance_print_dummy_frames(), maintenance_print_reggroups(), maintenance_set_cmd(), mdebug_build_psymtabs(), mdebug_read_symtab(), mem_info_command(), mi_execute_cli_command(), mi_interpreter_init(), mi_interpreter_resume(), mips_error(), mips_xfer_memory(), output_command_const(), output_source_filename(), overlay_command(), pop_output_files(), print_any_exception(), print_command_1(), print_cplus_stuff(), print_disassembly(), print_flush(), print_frame(), print_frame_arg_vars(), print_frame_info(), print_macro_definition(), print_one_macro(), print_one_vtable(), print_packet(), print_symbol_info(), print_sys_errmsg(), printf_command(), printf_filtered(), printf_unfiltered(), printfi_filtered(), proceed(), procfs_attach(), procfs_detach(), psymtab_to_symtab_1(), putchar_filtered(), putchar_unfiltered(), puts_filtered(), puts_filtered_tabular(), puts_unfiltered(), read_command_lines(), recursive_dump_type(), regcache_print(), registers_info(), remote_command(), remote_detach_1(), require_partial_symbols(), safe_symbol_file_add(), safe_symbol_file_add_cleanup(), save_command(), say_where(), scope_info(), serial_set_cmd(), set_ada_command(), set_architecture(), set_arm_command(), set_backtrace_cmd(), set_check(), set_dcache_command(), set_debug(), set_dwarf2_cmd(), set_endian(), set_history(), set_logging_off(), set_logging_redirect(), set_mips_command(), set_powerpc_command(), set_print(), set_print_raw(), set_print_type(), set_ravenscar_command(), set_record_command(), set_record_full_command(), set_remote_cmd(), set_sh_command(), set_spu_command(), set_tcp_cmd(), set_tdesc_cmd(), show_case_command(), show_configuration(), show_convenience(), show_inferior_tty_command(), show_language_command(), show_mips_command(), show_pp_source_pos(), show_range_command(), show_sh_command(), show_spu_command(), show_tcp_cmd(), show_user(), show_user_1(), show_values(), show_version(), srec_dump_command(), symbol_file_add_with_addrs(), target_command(), tekhex_dump_command(), trace_find_line_command(), tui_allowed_p(), tui_command(), tui_init(), tui_initialize_io(), tui_reg_command(), tui_register_format(), tui_restore_gdbout(), tui_resume(), tui_setup_io(), unset_command(), unset_tdesc_cmd(), unwind_command(), user_select_syms(), user_set_python(), vector_info(), vprintf_filtered(), vprintf_unfiltered(), vwarning(), whatis_exp(), windows_attach(), windows_detach(), wrap_here(), xcoff_psymtab_to_symtab_1(), and xcoff_read_symtab().
struct ui_file* gdb_stdtarg
Target output that should bypass normal stdout/stderr filtering. For moment, always call this stream using *_unfiltered. In the very near future that restriction shall be removed - either call shall be unfiltered. (cagney 1999-07-02).
Definition at line 82 of file main.c.
Referenced by do_monitor_command(), execute_command_to_string(), gdb_disable_readline(), gdb_os_flush_stdout(), gdb_os_write_stdout(), gdb_setup_readline(), gdbtk_fputs(), gdbtk_interpreter_resume(), handle_redirections(), mi_interpreter_resume(), mips_receive_header(), pop_output_files(), remote_console_output(), remote_fileio_func_write(), set_logging_redirect(), and tui_setup_io().
struct ui_file* gdb_stdtargerr
Definition at line 83 of file main.c.
Referenced by execute_command_to_string(), gdb_disable_readline(), gdb_os_flush_stderr(), gdb_os_write_stderr(), gdb_setup_readline(), handle_redirections(), mi_interpreter_resume(), pop_output_files(), remote_fileio_func_write(), set_logging_redirect(), and tui_setup_io().
struct ui_file* gdb_stdtargin
Definition at line 81 of file main.c.
Referenced by gdbtk_interpreter_resume(), gdbtk_read(), and remote_fileio_func_read().
int pagination_enabled
Definition at line 192 of file utils.c.
Referenced by set_observer_mode(), tui_register_format(), and tui_restore_gdbout().
int sevenbit_strings
Definition at line 178 of file utils.c.
Referenced by mi_command_loop().
char* warning_pre_print
String to be printed before the warning message, when a warning occurs. (Typically something like "warning:".)
Definition at line 190 of file utils.c.
Referenced by captured_main().