GDB (xrefs): /home/stan/gdb/src/gdb/valprint.h File Reference
/home/stan/gdb/src/gdb/valprint.h File Reference
Classes
struct value_print_options
struct generic_val_print_decorations
Functions
void get_user_print_options (struct value_print_options *opts)
void get_no_prettyformat_print_options (struct value_print_options *)
void get_formatted_print_options (struct value_print_options *opts, char format)
void maybe_print_array_index (struct type *index_type, LONGEST index, struct ui_file *stream, const struct value_print_options *)
void val_print_array_elements (struct type *, const gdb_byte *, int, CORE_ADDR, struct ui_file *, int, const struct value *, const struct value_print_options *, unsigned int)
void val_print_type_code_int (struct type *, const gdb_byte *, struct ui_file *)
void val_print_type_code_flags (struct type *type, const gdb_byte *valaddr, struct ui_file *stream)
void val_print_scalar_formatted (struct type *, const gdb_byte *, int, const struct value *, const struct value_print_options *, int, struct ui_file *)
void print_binary_chars (struct ui_file *, const gdb_byte *, unsigned int, enum bfd_endian)
void print_octal_chars (struct ui_file *, const gdb_byte *, unsigned int, enum bfd_endian)
void print_decimal_chars (struct ui_file *, const gdb_byte *, unsigned int, enum bfd_endian)
void print_hex_chars (struct ui_file *, const gdb_byte *, unsigned int, enum bfd_endian)
void print_char_chars (struct ui_file *, struct type *, const gdb_byte *, unsigned int, enum bfd_endian)
void print_function_pointer_address (const struct value_print_options *options, struct gdbarch *gdbarch, CORE_ADDR address, struct ui_file *stream)
int read_string (CORE_ADDR addr, int len, int width, unsigned int fetchlimit, enum bfd_endian byte_order, gdb_byte **buffer, int *bytes_read)
void val_print_optimized_out (const struct value *val, struct ui_file *stream)
void val_print_unavailable (struct ui_file *stream)
void val_print_invalid_address (struct ui_file *stream)
void generic_val_print (struct type *type, const gdb_byte *valaddr, int embedded_offset, CORE_ADDR address, struct ui_file *stream, int recurse, const struct value *original_value, const struct value_print_options *options, const struct generic_val_print_decorations *)
void generic_emit_char (int c, struct type *type, struct ui_file *stream, int quoter, const char *encoding)
void generic_printstr (struct ui_file *stream, struct type *type, const gdb_byte *string, unsigned int length, const char *encoding, int force_ellipses, int quote_char, int c_style_terminator, const struct value_print_options *options)
void output_command_const (const char *args, int from_tty)
int val_print_scalar_type_p (struct type *type)
Variables
struct value_print_options user_print_options
Function Documentation
void generic_emit_char (int c, struct type * type, struct ui_file * stream, int quoter, const char * encoding)
Definition at line 2009 of file valprint.c.
References convert_between_encodings(), do_cleanups(), fputs_filtered(), gdb_WEOF, gdbarch_byte_order(), get_type_arch(), host_charset(), INTERMEDIATE_ENCODING, make_cleanup_obstack_free(), make_cleanup_wchar_iterator(), make_wchar_iterator(), pack_long(), print_wchar(), translit_char, TYPE_LENGTH, wchar_iterate(), and wchar_printable().
Referenced by c_emit_char(), f_emit_char(), and java_emit_char().
void generic_printstr (struct ui_file * stream, struct type * type, const gdb_byte * string, unsigned int length, const char * encoding, int force_ellipses, int quote_char, int c_style_terminator, const struct value_print_options * options)
Definition at line 2338 of file valprint.c.
References convert_between_encodings(), count_next_character(), do_cleanups(), extract_unsigned_integer(), fputs_filtered(), gdbarch_byte_order(), get_type_arch(), host_charset(), INTERMEDIATE_ENCODING, LCST, make_cleanup(), make_cleanup_obstack_free(), make_cleanup_wchar_iterator(), make_wchar_iterator(), obstack_grow_wstr, print_converted_chars_to_obstack(), QUIT, converted_character::result, translit_char, TYPE_LENGTH, VEC, VEC_cleanup, VEC_last, and wchar_iterate_eof.
Referenced by c_printstr(), f_printstr(), and java_printstr().
void generic_val_print (struct type * type, const gdb_byte * valaddr, int embedded_offset, CORE_ADDR address, struct ui_file * stream, int recurse, const struct value * original_value, const struct value_print_options * options, const struct generic_val_print_decorations *)
Definition at line 371 of file valprint.c.
References _, value_print_options::addressprint, check_typedef(), CHECK_TYPEDEF, coerce_ref_if_computed(), common_val_print(), generic_val_print_decorations::complex_infix, generic_val_print_decorations::complex_prefix, generic_val_print_decorations::complex_suffix, current_language, demangle, value_print_options::deref_ref, error(), extract_typed_address(), generic_val_print_decorations::false_name, value_print_options::format, fprintf_filtered(), fputs_filtered(), gdb_assert, gdb_flush(), get_array_bounds(), get_type_arch(), LA_PRINT_CHAR, len, LONGEST, value_print_options::output_format, paddress(), value_print_options::prettyformat_arrays, print_address_demangle(), print_decimal_floating(), print_floating(), print_function_pointer_address(), print_longest(), print_spaces_filtered(), print_unpacked_pointer(), QUIT, value_print_options::symbol_print, generic_val_print_decorations::true_name, type, TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_BOOL, TYPE_CODE_CHAR, TYPE_CODE_COMPLEX, TYPE_CODE_DECFLOAT, TYPE_CODE_ENUM, TYPE_CODE_ERROR, TYPE_CODE_FLAGS, TYPE_CODE_FLT, TYPE_CODE_FUNC, TYPE_CODE_INT, TYPE_CODE_MEMBERPTR, TYPE_CODE_METHOD, TYPE_CODE_METHODPTR, TYPE_CODE_PTR, TYPE_CODE_RANGE, TYPE_CODE_REF, TYPE_CODE_STRUCT, TYPE_CODE_UNDEF, TYPE_CODE_UNION, TYPE_CODE_VOID, TYPE_ERROR_NAME, TYPE_FIELD_ENUMVAL, TYPE_FIELD_NAME, TYPE_FLAG_ENUM, TYPE_LENGTH, TYPE_NFIELDS, type_print(), TYPE_TARGET_TYPE, TYPE_UNSIGNED, unpack_long(), unpack_pointer(), val_print_array_elements(), val_print_scalar_formatted(), val_print_type_code_flags(), val_print_type_code_int(), value_at(), and generic_val_print_decorations::void_name.
Referenced by c_val_print(), f_val_print(), m2_val_print(), and pascal_val_print().
void get_formatted_print_options (struct value_print_options * opts, char format)
Definition at line 150 of file valprint.c.
References value_print_options::format, and user_print_options.
Referenced by ada_value_of_variable(), default_print_one_register_info(), do_examine(), do_one_display(), dwarf2_compute_name(), gdb_eval(), gdb_update_mem(), get_register(), mi_cmd_data_read_memory(), mips_print_fp_register(), mips_print_register(), output_command_const(), output_register(), print_command_1(), sh64_do_register(), value_get_print_value(), and wrap_val_print().
void get_no_prettyformat_print_options (struct value_print_options *)
Definition at line 141 of file valprint.c.
References value_print_options::prettyformat, user_print_options, and Val_no_prettyformat.
Referenced by list_arg_or_local(), mt_registers_info(), print_frame_arg(), print_return_value(), print_subexp_standard(), and print_variable_or_computed().
void get_user_print_options (struct value_print_options * opts)
Definition at line 133 of file valprint.c.
References user_print_options.
Referenced by breakpoint_1(), cplus_describe_child(), cplus_number_of_children(), decode_agent_options(), default_print_one_register_info(), enumerate_args(), enumerate_locals(), evaluate_subexp_standard(), fprint_target_auxv(), gnuv3_print_method_ptr(), gnuv3_print_vtable(), info_common_command_for_block(), mi_cmd_data_evaluate_expression(), print_frame(), print_frame_info(), print_one_breakpoint_location(), print_one_catch_exec(), print_one_catch_fork(), print_one_catch_solib(), print_one_catch_syscall(), print_one_catch_vfork(), print_one_exception(), print_one_exception_catchpoint(), print_one_ranged_breakpoint(), print_subexp_standard(), print_variable_and_value(), py_print_frame(), say_where(), show_convenience(), show_values(), signal_catchpoint_print_one(), skip_info(), update_type_if_necessary(), value_actual_type(), watchpoint_value_print(), and whatis_exp().
void maybe_print_array_index (struct type * index_type, LONGEST index, struct ui_file * stream, const struct value_print_options *)
Definition at line 1580 of file valprint.c.
References LA_PRINT_ARRAY_INDEX, value_print_options::print_array_indexes, and value_from_longest().
Referenced by val_print_array_elements(), and val_print_packed_array_elements().
void output_command_const (const char * args, int from_tty)
Definition at line 1039 of file printcmd.c.
References annotate_value_begin(), annotate_value_end(), decode_format(), do_cleanups(), evaluate_expression(), format_data::format, free_current_contents(), gdb_flush(), gdb_stdout, get_formatted_print_options(), make_cleanup(), parse_expression(), print_formatted(), format_data::raw, value_print_options::raw, format_data::size, validate_format(), value_type(), and wrap_here().
Referenced by output_command(), and trace_dump_actions().
void print_binary_chars (struct ui_file * , const gdb_byte * , unsigned int, enum bfd_endian)
Definition at line 1144 of file valprint.c.
References BITS_IN_BYTES, fprintf_filtered(), len, and p.
Referenced by print_scalar_formatted().
void print_char_chars (struct ui_file * , struct type * , const gdb_byte * , unsigned int, enum bfd_endian)
Definition at line 1519 of file valprint.c.
References LA_EMIT_CHAR, and p.
Referenced by print_scalar_formatted().
void print_decimal_chars (struct ui_file * , const gdb_byte * , unsigned int, enum bfd_endian)
Definition at line 1355 of file valprint.c.
References CARRY_LEFT, CARRY_OUT, dummy, fprintf_filtered(), HIGH_NIBBLE, LOW_NIBBLE, p, SHIFT, xfree(), and xmalloc().
Referenced by print_scalar_formatted().
void print_function_pointer_address (const struct value_print_options * options, struct gdbarch * gdbarch, CORE_ADDR address, struct ui_file * stream)
Definition at line 1555 of file valprint.c.
References value_print_options::addressprint, current_target, demangle, fputs_filtered(), gdbarch_convert_from_func_ptr_addr(), paddress(), and print_address_demangle().
Referenced by c_val_print(), cp_print_value_fields(), f_val_print(), generic_val_print(), print_one_vtable(), and print_unpacked_pointer().
void print_hex_chars (struct ui_file * , const gdb_byte * , unsigned int, enum bfd_endian)
Definition at line 1486 of file valprint.c.
References fprintf_filtered(), fputs_filtered(), len, and p.
Referenced by default_print_one_register_info(), print_scalar_formatted(), regcache_dump(), sh64_do_fp_register(), and val_print_type_code_int().
void print_octal_chars (struct ui_file * , const gdb_byte * , unsigned int, enum bfd_endian)
Definition at line 1204 of file valprint.c.
References _, BITS_IN_BYTES, BITS_IN_OCTAL, CARRY_ONE, CARRY_ZERO, error(), fprintf_filtered(), fputs_filtered(), HIGH_ZERO, len, LOW_ONE, LOW_TWO, LOW_ZERO, MID_ONE, MID_TWO, and p.
Referenced by print_scalar_formatted().
int read_string (CORE_ADDR addr, int len, int width, unsigned int fetchlimit, enum bfd_endian byte_order, gdb_byte ** buffer, int * bytes_read)
Definition at line 1777 of file valprint.c.
References discard_cleanups(), extract_unsigned_integer(), free_current_contents(), make_cleanup(), min, partial_memory_read(), QUIT, xmalloc(), and xrealloc().
Referenced by c_get_string(), and val_print_string().
void val_print_array_elements (struct type * , const gdb_byte * , int , CORE_ADDR , struct ui_file * , int , const struct value * , const struct value_print_options * , unsigned int)
Definition at line 1603 of file valprint.c.
References _, annotate_array_section_begin(), annotate_array_section_end(), annotate_elt(), annotate_elt_rep(), annotate_elt_rep_end(), check_typedef(), current_language, fprintf_filtered(), get_array_bounds(), len, LONGEST, maybe_print_array_index(), n_spaces(), value_print_options::prettyformat_arrays, value_print_options::print_max, print_spaces_filtered(), value_print_options::repeat_count_threshold, TYPE_INDEX_TYPE, TYPE_LENGTH, TYPE_TARGET_TYPE, val_print(), value_available_contents_eq(), warning(), and wrap_here().
Referenced by ada_val_print_array(), c_val_print(), generic_val_print(), m2_print_array_contents(), m2_val_print(), and pascal_val_print().
void val_print_invalid_address (struct ui_file * stream)
Definition at line 354 of file valprint.c.
References _, and fprintf_filtered().
Referenced by cp_print_value(), and pascal_object_print_value().
void val_print_optimized_out (const struct value * val, struct ui_file * stream)
Definition at line 339 of file valprint.c.
References _, fprintf_filtered(), lval_register, and value_lval_const().
Referenced by cp_print_value_fields(), default_print_one_register_info(), java_print_value_fields(), pascal_object_print_value_fields(), val_print_scalar_formatted(), valprint_check_validity(), and value_check_printable().
void val_print_scalar_formatted (struct type * , const gdb_byte * , int , const struct value * , const struct value_print_options * , int , struct ui_file *)
Definition at line 945 of file valprint.c.
References current_language, value_print_options::deref_ref, value_print_options::format, gdb_assert, print_scalar_formatted(), TYPE_LENGTH, val_print(), val_print_optimized_out(), val_print_unavailable(), value_bits_valid(), value_bytes_available(), and value_contents_for_printing_const().
Referenced by ada_val_print_1(), c_val_print(), f_val_print(), generic_val_print(), java_val_print(), m2_val_print(), mips_print_register(), pascal_val_print(), and print_formatted().
int val_print_scalar_type_p (struct type * type)
Definition at line 279 of file valprint.c.
References CHECK_TYPEDEF, TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_REF, TYPE_CODE_SET, TYPE_CODE_STRING, TYPE_CODE_STRUCT, TYPE_CODE_UNION, and TYPE_TARGET_TYPE.
Referenced by list_arg_or_local(), val_print(), and value_check_printable().
void val_print_type_code_flags (struct type * type, const gdb_byte * valaddr, struct ui_file * stream)
Definition at line 916 of file valprint.c.
References fprintf_filtered(), fputs_filtered(), TYPE_FIELD_BITPOS, TYPE_FIELD_NAME, TYPE_NFIELDS, ULONGEST, and unpack_long().
Referenced by generic_val_print().
void val_print_type_code_int (struct type * , const gdb_byte * , struct ui_file *)
Definition at line 883 of file valprint.c.
References extract_long_unsigned_integer(), gdbarch_byte_order(), get_type_arch(), LONGEST, print_hex_chars(), print_longest(), TYPE_LENGTH, TYPE_UNSIGNED, and unpack_long().
Referenced by ada_val_print_1(), c_val_print(), f_val_print(), generic_val_print(), and java_val_print().
void val_print_unavailable (struct ui_file * stream)
Definition at line 348 of file valprint.c.
References _, and fprintf_filtered().
Referenced by cp_print_value(), pascal_object_print_value(), val_print_scalar_formatted(), and valprint_check_validity().
Variable Documentation
struct value_print_options user_print_options
Definition at line 108 of file valprint.c.
Referenced by _initialize_pascal_valprint(), get_formatted_print_options(), get_no_prettyformat_print_options(), and get_user_print_options().