GDB (xrefs): /home/stan/gdb/src/gdb/value.h File Reference
/home/stan/gdb/src/gdb/value.h File Reference
#include "doublest.h"
#include "frame.h"
#include "symtab.h"
#include "gdbtypes.h"
#include "expression.h"
Classes
struct lval_funcs
struct internalvar_funcs
Defines
#define VALUE_LVAL(val) (*deprecated_value_lval_hack (val))
#define VALUE_INTERNALVAR(val) (*deprecated_value_internalvar_hack (val))
#define VALUE_FRAME_ID(val) (*deprecated_value_frame_id_hack (val))
#define VALUE_REGNUM(val) (*deprecated_value_regnum_hack (val))
Typedefs
typedef struct value *(* internal_function_fn)(struct gdbarch *gdbarch, const struct language_defn *language, void *cookie, int argc, struct value **argv)
Enumerations
enum oload_search_type { NON_METHOD, METHOD, BOTH }
Functions
struct value * value_next (struct value *)
struct type * value_type (const struct value *)
void deprecated_set_value_type (struct value *value, struct type *type)
int value_bitsize (const struct value *)
void set_value_bitsize (struct value *, int bit)
int value_bitpos (const struct value *)
void set_value_bitpos (struct value *, int bit)
struct value * value_parent (struct value *)
void set_value_parent (struct value *value, struct value *parent)
int value_offset (const struct value *)
void set_value_offset (struct value *, int offset)
int deprecated_value_modifiable (struct value *value)
struct type * value_enclosing_type (struct value *)
void set_value_enclosing_type (struct value *val, struct type *new_type)
struct type * value_actual_type (struct value *value, int resolve_simple_types, int *real_type_found)
int value_pointed_to_offset (struct value *value)
void set_value_pointed_to_offset (struct value *value, int val)
int value_embedded_offset (struct value *value)
void set_value_embedded_offset (struct value *value, int val)
struct value * allocate_computed_value (struct type *type, const struct lval_funcs *funcs, void *closure)
int valprint_check_validity (struct ui_file *stream, struct type *type, int embedded_offset, const struct value *val)
struct value * allocate_optimized_out_value (struct type *type)
struct lval_funcs * value_computed_funcs (const struct value *)
void * value_computed_closure (const struct value *value)
int value_lazy (struct value *)
void set_value_lazy (struct value *value, int val)
int value_stack (struct value *)
void set_value_stack (struct value *value, int val)
void error_value_optimized_out (void)
gdb_byte * value_contents_raw (struct value *)
const gdb_byte * value_contents (struct value *)
gdb_byte * value_contents_writeable (struct value *)
gdb_byte * value_contents_all_raw (struct value *)
const gdb_byte * value_contents_all (struct value *)
const gdb_byte * value_contents_for_printing (struct value *value)
const gdb_byte * value_contents_for_printing_const (const struct value *value)
int value_fetch_lazy (struct value *val)
int value_contents_equal (struct value *val1, struct value *val2)
int value_optimized_out (struct value *value)
void set_value_optimized_out (struct value *value, int val)
int value_optimized_out_const (const struct value *value)
int value_entirely_optimized_out (const struct value *value)
int value_initialized (struct value *)
void set_value_initialized (struct value *, int)
void set_value_component_location (struct value *component, const struct value *whole)
enum lval_type * deprecated_value_lval_hack (struct value *)
enum lval_type value_lval_const (const struct value *value)
CORE_ADDR value_address (const struct value *)
CORE_ADDR value_raw_address (struct value *)
void set_value_address (struct value *, CORE_ADDR)
struct internalvar ** deprecated_value_internalvar_hack (struct value *)
struct frame_id * deprecated_value_frame_id_hack (struct value *)
short * deprecated_value_regnum_hack (struct value *)
struct value * coerce_ref_if_computed (const struct value *arg)
struct value * readjust_indirect_value_type (struct value *value, struct type *enc_type, struct type *original_type, struct value *original_val)
struct value * coerce_ref (struct value *value)
struct value * coerce_array (struct value *value)
int value_bits_valid (const struct value *value, int offset, int length)
int value_bits_synthetic_pointer (const struct value *value, int offset, int length)
int value_bytes_available (const struct value *value, int offset, int length)
int value_entirely_available (struct value *value)
int value_entirely_unavailable (struct value *value)
void mark_value_bytes_unavailable (struct value *value, int offset, int length)
int value_available_contents_eq (const struct value *val1, int offset1, const struct value *val2, int offset2, int length)
void read_value_memory (struct value *val, int embedded_offset, int stack, CORE_ADDR memaddr, gdb_byte *buffer, size_t length)
struct value * value_vector_widen (struct value *scalar_value, struct type *vector_type)
int print_address_demangle (const struct value_print_options *, struct gdbarch *, CORE_ADDR, struct ui_file *, int)
LONGEST value_as_long (struct value *val)
DOUBLEST value_as_double (struct value *val)
CORE_ADDR value_as_address (struct value *val)
LONGEST unpack_long (struct type *type, const gdb_byte *valaddr)
DOUBLEST unpack_double (struct type *type, const gdb_byte *valaddr, int *invp)
CORE_ADDR unpack_pointer (struct type *type, const gdb_byte *valaddr)
int unpack_value_bits_as_long (struct type *field_type, const gdb_byte *valaddr, int embedded_offset, int bitpos, int bitsize, const struct value *original_value, LONGEST *result)
LONGEST unpack_field_as_long (struct type *type, const gdb_byte *valaddr, int fieldno)
int unpack_value_field_as_long (struct type *type, const gdb_byte *valaddr, int embedded_offset, int fieldno, const struct value *val, LONGEST *result)
struct value * value_field_bitfield (struct type *type, int fieldno, const gdb_byte *valaddr, int embedded_offset, const struct value *val)
void pack_long (gdb_byte *buf, struct type *type, LONGEST num)
struct value * value_from_longest (struct type *type, LONGEST num)
struct value * value_from_ulongest (struct type *type, ULONGEST num)
struct value * value_from_pointer (struct type *type, CORE_ADDR addr)
struct value * value_from_double (struct type *type, DOUBLEST num)
struct value * value_from_decfloat (struct type *type, const gdb_byte *decbytes)
struct value * value_from_history_ref (char *, char **)
struct value * value_at (struct type *type, CORE_ADDR addr)
struct value * value_at_lazy (struct type *type, CORE_ADDR addr)
struct value * value_from_contents_and_address (struct type *, const gdb_byte *, CORE_ADDR)
struct value * value_from_contents (struct type *, const gdb_byte *)
struct value * default_value_from_register (struct type *type, int regnum, struct frame_info *frame)
void read_frame_register_value (struct value *value, struct frame_info *frame)
struct value * value_from_register (struct type *type, int regnum, struct frame_info *frame)
CORE_ADDR address_from_register (struct type *type, int regnum, struct frame_info *frame)
struct value * value_of_variable (struct symbol *var, const struct block *b)
struct value * address_of_variable (struct symbol *var, const struct block *b)
struct value * value_of_register (int regnum, struct frame_info *frame)
struct value * value_of_register_lazy (struct frame_info *frame, int regnum)
int symbol_read_needs_frame (struct symbol *)
struct value * read_var_value (struct symbol *var, struct frame_info *frame)
struct value * default_read_var_value (struct symbol *var, struct frame_info *frame)
struct value * allocate_value (struct type *type)
struct value * allocate_value_lazy (struct type *type)
void value_contents_copy (struct value *dst, int dst_offset, struct value *src, int src_offset, int length)
void value_contents_copy_raw (struct value *dst, int dst_offset, struct value *src, int src_offset, int length)
struct value * allocate_repeat_value (struct type *type, int count)
struct value * value_mark (void)
void value_free_to_mark (struct value *mark)
struct value * value_cstring (char *ptr, ssize_t len, struct type *char_type)
struct value * value_string (char *ptr, ssize_t len, struct type *char_type)
struct value * value_array (int lowbound, int highbound, struct value **elemvec)
struct value * value_concat (struct value *arg1, struct value *arg2)
struct value * value_binop (struct value *arg1, struct value *arg2, enum exp_opcode op)
struct value * value_ptradd (struct value *arg1, LONGEST arg2)
LONGEST value_ptrdiff (struct value *arg1, struct value *arg2)
int value_must_coerce_to_target (struct value *arg1)
struct value * value_coerce_to_target (struct value *arg1)
struct value * value_coerce_array (struct value *arg1)
struct value * value_coerce_function (struct value *arg1)
struct value * value_ind (struct value *arg1)
struct value * value_addr (struct value *arg1)
struct value * value_ref (struct value *arg1)
struct value * value_assign (struct value *toval, struct value *fromval)
struct value * value_pos (struct value *arg1)
struct value * value_neg (struct value *arg1)
struct value * value_complement (struct value *arg1)
struct value * value_struct_elt (struct value **argp, struct value **args, const char *name, int *static_memfuncp, const char *err)
struct value * value_aggregate_elt (struct type *curtype, char *name, struct type *expect_type, int want_address, enum noside noside)
struct value * value_static_field (struct type *type, int fieldno)
int find_overload_match (struct value **args, int nargs, const char *name, enum oload_search_type method, struct value **objp, struct symbol *fsym, struct value **valp, struct symbol **symp, int *staticp, const int no_adl)
struct value * value_field (struct value *arg1, int fieldno)
struct value * value_primitive_field (struct value *arg1, int offset, int fieldno, struct type *arg_type)
struct type * value_rtti_indirect_type (struct value *, int *, int *, int *)
struct value * value_full_object (struct value *, struct type *, int, int, int)
struct value * value_cast_pointers (struct type *, struct value *, int)
struct value * value_cast (struct type *type, struct value *arg2)
struct value * value_reinterpret_cast (struct type *type, struct value *arg)
struct value * value_dynamic_cast (struct type *type, struct value *arg)
struct value * value_zero (struct type *type, enum lval_type lv)
struct value * value_one (struct type *type)
struct value * value_repeat (struct value *arg1, int count)
struct value * value_subscript (struct value *array, LONGEST index)
struct value * value_bitstring_subscript (struct type *type, struct value *bitstring, LONGEST index)
struct value * register_value_being_returned (struct type *valtype, struct regcache *retbuf)
int value_in (struct value *element, struct value *set)
int value_bit_index (struct type *type, const gdb_byte *addr, int index)
enum return_value_convention struct_return_convention (struct gdbarch *gdbarch, struct value *function, struct type *value_type)
int using_struct_return (struct gdbarch *gdbarch, struct value *function, struct type *value_type)
struct value * evaluate_expression (struct expression *exp)
struct value * evaluate_type (struct expression *exp)
struct value * evaluate_subexp (struct type *expect_type, struct expression *exp, int *pos, enum noside noside)
struct value * evaluate_subexpression_type (struct expression *exp, int subexp)
void fetch_subexp_value (struct expression *exp, int *pc, struct value **valp, struct value **resultp, struct value **val_chain, int preserve_errors)
char * extract_field_op (struct expression *exp, int *subexp)
struct value * evaluate_subexp_with_coercion (struct expression *, int *, enum noside)
struct value * parse_and_eval (const char *exp)
struct value * parse_to_comma_and_eval (const char **expp)
struct type * parse_and_eval_type (char *p, int length)
CORE_ADDR parse_and_eval_address (const char *exp)
LONGEST parse_and_eval_long (const char *exp)
void unop_promote (const struct language_defn *language, struct gdbarch *gdbarch, struct value **arg1)
void binop_promote (const struct language_defn *language, struct gdbarch *gdbarch, struct value **arg1, struct value **arg2)
struct value * access_value_history (int num)
struct value * value_of_internalvar (struct gdbarch *gdbarch, struct internalvar *var)
int get_internalvar_integer (struct internalvar *var, LONGEST *l)
void set_internalvar (struct internalvar *var, struct value *val)
void set_internalvar_integer (struct internalvar *var, LONGEST l)
void set_internalvar_string (struct internalvar *var, const char *string)
void clear_internalvar (struct internalvar *var)
void set_internalvar_component (struct internalvar *var, int offset, int bitpos, int bitsize, struct value *newvalue)
struct internalvar * lookup_only_internalvar (const char *name)
struct internalvar * create_internalvar (const char *name)
VEC (char_ptr)*complete_internalvar(const char *name)
struct internalvar * create_internalvar_type_lazy (const char *name, const struct internalvar_funcs *funcs, void *data)
int compile_internalvar_to_ax (struct internalvar *var, struct agent_expr *expr, struct axs_value *value)
struct internalvar * lookup_internalvar (const char *name)
int value_equal (struct value *arg1, struct value *arg2)
int value_equal_contents (struct value *arg1, struct value *arg2)
int value_less (struct value *arg1, struct value *arg2)
int value_logical_not (struct value *arg1)
struct value * value_of_this (const struct language_defn *lang)
struct value * value_of_this_silent (const struct language_defn *lang)
struct value * value_x_binop (struct value *arg1, struct value *arg2, enum exp_opcode op, enum exp_opcode otherop, enum noside noside)
struct value * value_x_unop (struct value *arg1, enum exp_opcode op, enum noside noside)
struct value * value_fn_field (struct value **arg1p, struct fn_field *f, int j, struct type *type, int offset)
int binop_types_user_defined_p (enum exp_opcode op, struct type *type1, struct type *type2)
int binop_user_defined_p (enum exp_opcode op, struct value *arg1, struct value *arg2)
int unop_user_defined_p (enum exp_opcode op, struct value *arg1)
int destructor_name_p (const char *name, struct type *type)
void value_incref (struct value *val)
void value_free (struct value *val)
void free_all_values (void)
void free_value_chain (struct value *v)
void release_value (struct value *val)
void release_value_or_incref (struct value *val)
int record_latest_value (struct value *val)
void modify_field (struct type *type, gdb_byte *addr, LONGEST fieldval, int bitpos, int bitsize)
void type_print (struct type *type, const char *varstring, struct ui_file *stream, int show)
char * type_to_string (struct type *type)
gdb_byte * baseclass_addr (struct type *type, int index, gdb_byte *valaddr, struct value **valuep, int *errp)
void print_longest (struct ui_file *stream, int format, int use_local, LONGEST val)
void print_floating (const gdb_byte *valaddr, struct type *type, struct ui_file *stream)
void print_decimal_floating (const gdb_byte *valaddr, struct type *type, struct ui_file *stream)
void value_print (struct value *val, struct ui_file *stream, const struct value_print_options *options)
void value_print_array_elements (struct value *val, struct ui_file *stream, int format, enum val_prettyformat pretty)
struct value * value_release_to_mark (struct value *mark)
void val_print (struct type *type, const gdb_byte *valaddr, int embedded_offset, CORE_ADDR address, struct ui_file *stream, int recurse, const struct value *val, const struct value_print_options *options, const struct language_defn *language)
void common_val_print (struct value *val, struct ui_file *stream, int recurse, const struct value_print_options *options, const struct language_defn *language)
int val_print_string (struct type *elttype, const char *encoding, CORE_ADDR addr, int len, struct ui_file *stream, const struct value_print_options *options)
void print_variable_and_value (const char *name, struct symbol *var, struct frame_info *frame, struct ui_file *stream, int indent)
void typedef_print (struct type *type, struct symbol *news, struct ui_file *stream)
char * internalvar_name (struct internalvar *var)
void preserve_values (struct objfile *)
struct value * value_copy (struct value *)
struct value * value_non_lval (struct value *)
void preserve_one_value (struct value *, struct objfile *, htab_t)
struct value * varying_to_slice (struct value *)
struct value * value_slice (struct value *, int, int)
struct value * value_literal_complex (struct value *, struct value *, struct type *)
struct value * find_function_in_inferior (const char *, struct objfile **)
struct value * value_allocate_space_in_inferior (int)
struct value * value_subscripted_rvalue (struct value *array, LONGEST index, int lowerbound)
void add_internal_function (const char *name, const char *doc, internal_function_fn handler, void *cookie)
struct value * call_internal_function (struct gdbarch *gdbarch, const struct language_defn *language, struct value *function, int argc, struct value **argv)
char * value_internal_function_name (struct value *)
Define Documentation
#define VALUE_FRAME_ID (val) (*deprecated_value_frame_id_hack (val))
Definition at line 383 of file value.h.
Referenced by address_of_variable(), allocate_value_lazy(), default_value_from_register(), dwarf2_evaluate_loc_desc_full(), read_pieced_value(), sentinel_frame_prev_register(), value_assign(), value_copy(), value_fetch_lazy(), value_from_register(), value_of_register_lazy(), value_primitive_field(), value_slice(), value_subscripted_rvalue(), and write_pieced_value().
#define VALUE_INTERNALVAR (val) (*deprecated_value_internalvar_hack (val))
Definition at line 378 of file value.h.
Referenced by call_internal_function(), set_internalvar(), value_assign(), value_internal_function_name(), and value_of_internalvar().
#define VALUE_LVAL (val) (*deprecated_value_lval_hack (val))
Definition at line 358 of file value.h.
Referenced by aarch64_pseudo_read_value(), ada_convert_actual(), ada_value_assign(), ada_value_primitive_packed_val(), address_of_variable(), allocate_computed_value(), allocate_value_lazy(), amd64_pseudo_register_read_value(), c_get_string(), call_internal_function(), call_site_to_target_addr(), can_use_hardware_watchpoint(), check_condition(), create_value(), default_read_var_value(), default_value_from_register(), dump_value_to_file(), ensure_lval(), evaluate_subexp_java(), evaluate_subexp_modula2(), evaluate_subexp_opencl(), evaluate_subexp_standard(), find_function_addr(), frame_register_unwind(), frame_unwind_register_value(), i386_pseudo_register_read_value(), num_memory_accesses(), print_formatted(), read_frame_register_value(), regcache_cooked_read_value(), set_internalvar(), set_value_component_location(), update_watchpoint(), value_addr(), value_assign(), value_cast(), value_coerce_array(), value_coerce_function(), value_copy(), value_fetch_lazy(), value_free(), value_from_contents_and_address(), value_from_register(), value_full_object(), value_ind(), value_internal_function_name(), value_must_coerce_to_target(), value_non_lval(), value_of_dwarf_reg_entry(), value_of_internalvar(), value_of_register_lazy(), value_one(), value_primitive_field(), value_ptradd(), value_repeat(), value_slice(), value_subscript(), value_subscripted_rvalue(), value_x_binop(), value_x_unop(), value_zero(), varobj_editable_p(), and x_command().
#define VALUE_REGNUM (val) (*deprecated_value_regnum_hack (val))
Definition at line 387 of file value.h.
Referenced by aarch64_pseudo_read_value(), address_of_variable(), allocate_value_lazy(), amd64_pseudo_register_read_value(), default_value_from_register(), frame_register_unwind(), frame_unwind_register_value(), i386_pseudo_register_read_value(), read_frame_register_unsigned(), read_frame_register_value(), regcache_cooked_read_value(), value_assign(), value_copy(), value_fetch_lazy(), value_from_register(), value_of_register_lazy(), value_primitive_field(), and value_subscripted_rvalue().
Typedef Documentation
typedef struct value*(* internal_function_fn)(struct gdbarch *gdbarch, const struct language_defn *language, void *cookie, int argc, struct value **argv)
Definition at line 977 of file value.h.
Enumeration Type Documentation
enum oload_search_type
Enumerator:
NON_METHOD
METHOD
BOTH
Definition at line 667 of file value.h.
Function Documentation
struct value* access_value_history (int num) [read]
Definition at line 1553 of file value.c.
References _, error(), value_history_chunk::next, value_copy(), value_history_chain, VALUE_HISTORY_CHUNK, value_history_count, and value_history_chunk::values.
Referenced by evaluate_subexp_standard(), linespec_parse_variable(), print_command_1(), show_values(), value_from_history_ref(), and whatis_exp().
void add_internal_function (const char * name, const char * doc, internal_function_fn handler, void * cookie)
Definition at line 2192 of file value.c.
References add_cmd(), create_internal_function(), cmd_list_element::destroyer, function_command(), function_destroyer(), lookup_internalvar(), no_class, and set_internalvar_function().
Referenced by fnpy_init().
CORE_ADDR address_from_register (struct type * type, int regnum, struct frame_info * frame)
Definition at line 752 of file findvar.c.
References error_value_optimized_out(), gdb_assert, release_value(), value_as_address(), value_free(), value_from_register(), and value_optimized_out().
Referenced by dwarf_expr_read_reg().
struct value* address_of_variable (struct symbol * var, const struct block * b) [read]
Definition at line 1356 of file valops.c.
References _, error(), frame_find_by_id(), gdb_assert, gdbarch_register_name(), get_frame_arch(), lookup_pointer_type(), lval_memory, lval_register, SYMBOL_PRINT_NAME, SYMBOL_TYPE, TYPE_CODE, TYPE_CODE_FUNC, value_address(), VALUE_FRAME_ID, value_from_pointer(), value_lazy(), VALUE_LVAL, value_of_variable(), and VALUE_REGNUM.
Referenced by evaluate_subexp_with_coercion().
struct value* allocate_computed_value (struct type * type, const struct lval_funcs * funcs, void * closure) [read]
Definition at line 750 of file value.c.
References allocate_value_lazy(), value::closure, value::computed, value::funcs, value::location, lval_computed, and VALUE_LVAL.
Referenced by create_value(), dwarf2_evaluate_loc_desc_full(), siginfo_make_value(), tlb_make_value(), and value_of_dwarf_reg_entry().
struct value* allocate_optimized_out_value (struct type * type) [read]
Definition at line 766 of file value.c.
References allocate_value_lazy(), and set_value_optimized_out().
Referenced by default_read_var_value(), dwarf2_evaluate_loc_desc_full(), frame_unwind_got_optimized(), indirect_pieced_value(), loclist_read_variable_at_entry(), read_frame_arg(), s390_unwind_pseudo_register(), and value_primitive_field().
struct value* allocate_repeat_value (struct type * type, int count) [read]
Definition at line 738 of file value.c.
References allocate_value(), current_language, lookup_array_range_type(), and language_defn::string_lower_bound.
Referenced by evaluate_subexp_standard(), and value_repeat().
struct value* allocate_value (struct type * type) [read]
Definition at line 725 of file value.c.
References allocate_value_contents(), allocate_value_lazy(), and value::lazy.
Referenced by aarch64_pseudo_read_value(), ada_convert_actual(), ada_promote_array_of_integrals(), ada_value_binop(), ada_value_primitive_packed_val(), allocate_repeat_value(), amd64_pseudo_register_read_value(), call_function_by_hand(), cast_into_complex(), coerce_unspec_val_to_type(), create_value(), default_read_var_value(), default_value_from_register(), dwarf2_compute_name(), dwarf2_evaluate_loc_desc_full(), elf_gnu_ifunc_resolve_addr(), elf_gnu_ifunc_resolver_return_stop(), empty_array(), evaluate_subexp_c(), evaluate_subexp_opencl(), evaluate_subexp_standard(), get_return_value(), i386_pseudo_register_read_value(), java_value_print(), lval_func_write(), make_array_descriptor(), opencl_logical_not(), regcache_cooked_read_value(), scalar_binop(), sdata_make_value(), siginfo_make_value(), tlb_make_value(), value_array(), value_cast(), value_complement(), value_copy(), value_cstring(), value_field_bitfield(), value_fn_field(), value_from_contents(), value_from_decfloat(), value_from_double(), value_from_longest(), value_from_pointer(), value_from_register(), value_from_ulongest(), value_literal_complex(), value_neg(), value_non_lval(), value_of_builtin_frame_fp_reg(), value_of_builtin_frame_pc_reg(), value_of_internalvar(), value_one(), value_pos(), value_primitive_field(), value_slice(), value_string(), value_subscripted_rvalue(), value_vector_widen(), value_zero(), vector_binop(), and vector_relop().
struct value* allocate_value_lazy (struct type * type) [read]
Definition at line 675 of file value.c.
References value::address, all_values, value::bitpos, value::bitsize, check_typedef(), value::contents, value::embedded_offset, value::enclosing_type, value::initialized, value::lazy, value::location, value::modifiable, value::next, not_lval, null_frame_id, value::offset, value::optimized_out, value::pointed_to_offset, value::reference_count, type, value::type, VALUE_FRAME_ID, VALUE_LVAL, VALUE_REGNUM, and xzalloc().
Referenced by allocate_computed_value(), allocate_optimized_out_value(), allocate_value(), coerce_unspec_val_to_type(), value_copy(), value_from_contents_and_address(), value_of_register_lazy(), value_primitive_field(), value_slice(), and value_subscripted_rvalue().
gdb_byte* baseclass_addr (struct type * type, int index, gdb_byte * valaddr, struct value ** valuep, int * errp)
void binop_promote (const struct language_defn * language, struct gdbarch * gdbarch, struct value ** arg1, struct value ** arg2)
Definition at line 463 of file eval.c.
References builtin_type::builtin_double, builtin_type::builtin_int, builtin_type::builtin_long, builtin_type::builtin_long_double, builtin_type::builtin_long_long, builtin_type(), builtin_type::builtin_unsigned_int, builtin_type::builtin_unsigned_long, builtin_type::builtin_unsigned_long_long, check_typedef(), coerce_ref(), gdbarch_double_bit(), gdbarch_long_bit(), HOST_CHAR_BIT, is_integral_type(), language_defn::la_language, language_asm, language_c, language_cplus, language_objc, language_opencl, lookup_signed_typename(), lookup_unsigned_typename(), TYPE_CODE, TYPE_CODE_BOOL, TYPE_CODE_DECFLOAT, TYPE_CODE_FLT, TYPE_LENGTH, TYPE_UNSIGNED, value_cast(), and value_type().
Referenced by evaluate_subexp_standard().
int binop_types_user_defined_p (enum exp_opcode op, struct type * type1, struct type * type2)
Definition at line 230 of file valarith.c.
References check_typedef(), TYPE_CODE, TYPE_CODE_REF, TYPE_CODE_STRUCT, and TYPE_TARGET_TYPE.
Referenced by binop_user_defined_p(), and gen_expr_binop_rest().
int binop_user_defined_p (enum exp_opcode op, struct value * arg1, struct value * arg2)
Definition at line 255 of file valarith.c.
References binop_types_user_defined_p(), and value_type().
Referenced by evaluate_subexp_standard().
struct value* call_internal_function (struct gdbarch * gdbarch, const struct language_defn * language, struct value * function, int argc, struct value ** argv) [read]
Definition at line 2154 of file value.c.
References internal_function::cookie, gdb_assert, get_internalvar_function(), internal_function::handler, lval_internalvar, VALUE_INTERNALVAR, and VALUE_LVAL.
Referenced by evaluate_subexp_standard().
void clear_internalvar (struct internalvar * var)
Definition at line 2096 of file value.c.
References internalvar::internalvar_data::data, internalvar_funcs::destroy, internalvar::internalvar_data::functions, internalvar::kind, internalvar::internalvar_data::make_value, internalvar::internalvar_data::string, internalvar::u, internalvar::internalvar_data::value, value_free(), and xfree().
Referenced by clear_exit_convenience_vars(), set_internalvar(), set_internalvar_function(), set_internalvar_integer(), set_internalvar_string(), set_traceframe_context(), and x_command().
struct value* coerce_array (struct value * value) [read]
Definition at line 3366 of file value.c.
References language_defn::c_style_arrays, check_typedef(), coerce_ref(), current_language, type, TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_FUNC, TYPE_VECTOR, value_coerce_array(), value_coerce_function(), and value_type().
Referenced by value_as_address(), value_as_long(), value_assign(), value_equal(), value_find_oload_method_list(), value_ind(), value_less(), value_logical_not(), value_ptradd(), value_ptrdiff(), value_reinterpret_cast(), value_struct_elt(), and varobj_set_value().
struct value* coerce_ref (struct value * value) [read]
Definition at line 3342 of file value.c.
References check_typedef(), coerce_ref_if_computed(), readjust_indirect_value_type(), TYPE_CODE, TYPE_CODE_REF, TYPE_TARGET_TYPE, unpack_pointer(), value_at_lazy(), value_contents(), value_enclosing_type(), and value_type().
Referenced by ada_coerce_ref(), ada_val_print_1(), ada_value_binop(), ada_value_struct_elt(), binop_promote(), coerce_array(), evaluate_subexp_java(), evaluate_subexp_modula2(), evaluate_subexp_standard(), find_overload_match(), gnuv3_get_typeid(), gnuv3_print_vtable(), install_new_value(), opencl_value_cast(), pos_atr(), read_frame_arg(), scalar_binop(), unop_promote(), value_assign(), value_cast(), value_cast_pointers(), value_complement(), value_neg(), value_pos(), value_rtti_indirect_type(), value_subscript(), value_x_binop(), value_x_unop(), and x_command().
struct value* coerce_ref_if_computed (const struct value * arg) [read]
Definition at line 3306 of file value.c.
References check_typedef(), lval_funcs::coerce_ref, lval_computed, TYPE_CODE, TYPE_CODE_REF, value_computed_funcs(), value_lval_const(), and value_type().
Referenced by ada_val_print_1(), coerce_ref(), and generic_val_print().
void common_val_print (struct value * val, struct ui_file * stream, int recurse, const struct value_print_options * options, const struct language_defn * language)
Definition at line 832 of file valprint.c.
References ada_to_fixed_value(), language_defn::la_language, language_ada, val_print(), value_address(), value_check_printable(), value_contents_for_printing(), value_embedded_offset(), and value_type().
Referenced by ada_val_print_1(), ada_varobj_get_value_image(), c_val_print(), cp_print_value_fields(), gdb_eval(), generic_val_print(), java_print_value_fields(), java_value_print(), list_arg_or_local(), mi_cmd_data_evaluate_expression(), pascal_object_print_static_field(), pascal_object_print_value_fields(), pascal_val_print(), pascal_value_print(), print_frame_arg(), print_variable_and_value(), print_variable_at_address(), print_variable_or_computed(), py_print_value(), and value_get_print_value().
int compile_internalvar_to_ax (struct internalvar * var, struct agent_expr * expr, struct axs_value * value)
Definition at line 1827 of file value.c.
References internalvar_funcs::compile_to_ax, internalvar::internalvar_data::data, internalvar::internalvar_data::functions, internalvar::INTERNALVAR_MAKE_VALUE, internalvar::kind, internalvar::internalvar_data::make_value, and internalvar::u.
Referenced by gen_expr().
struct internalvar* create_internalvar (const char * name) [read]
Definition at line 1792 of file value.c.
References internalvar::INTERNALVAR_VOID, internalvars, internalvar::kind, internalvar::name, internalvar::next, and xmalloc().
Referenced by create_internalvar_type_lazy(), lookup_internalvar(), and write_dollar_variable().
struct internalvar* create_internalvar_type_lazy (const char * name, const struct internalvar_funcs * funcs, void * data) [read]
Definition at line 1812 of file value.c.
References create_internalvar(), internalvar::internalvar_data::data, internalvar::internalvar_data::functions, internalvar::INTERNALVAR_MAKE_VALUE, internalvar::kind, internalvar::internalvar_data::make_value, and internalvar::u.
Referenced by _initialize_break_catch_throw(), _initialize_tracepoint(), and _initialize_windows_tdep().
struct value* default_read_var_value (struct symbol * var, struct frame_info * frame) [read]
Definition at line 422 of file findvar.c.
References _, allocate_optimized_out_value(), allocate_value(), BLOCK_START, check_typedef(), error(), gdb_assert, gdb_assert_not_reached, gdbarch_byte_order(), gdbarch_iterate_over_objfiles_in_search_order(), get_frame_arch(), get_frame_args_address(), get_frame_locals_address(), get_objfile_arch(), get_type_arch(), LOC_ARG, LOC_BLOCK, LOC_COMPUTED, LOC_CONST, LOC_CONST_BYTES, LOC_LABEL, LOC_LOCAL, LOC_OPTIMIZED_OUT, LOC_REF_ARG, LOC_REGISTER, LOC_REGPARM_ADDR, LOC_STATIC, LOC_TYPEDEF, LOC_UNRESOLVED, LONGEST, lookup_pointer_type(), memcpy(), memset(), minsym_lookup_iterator_cb(), minsym_lookup_data::name, not_lval, obj_section::objfile, minsym_lookup_data::objfile, overlay_debugging, minsym_lookup_data::result, store_signed_integer(), store_typed_address(), SYMBOL_BLOCK_VALUE, SYMBOL_CLASS, SYMBOL_COMPUTED_OPS, SYMBOL_LINKAGE_NAME, SYMBOL_OBJ_SECTION, SYMBOL_OBJFILE, symbol_overlayed_address(), SYMBOL_PRINT_NAME, symbol_read_needs_frame(), SYMBOL_REGISTER_OPS, SYMBOL_SYMTAB, SYMBOL_TYPE, SYMBOL_VALUE, SYMBOL_VALUE_ADDRESS, SYMBOL_VALUE_BYTES, target_translate_tls_address(), obj_section::the_bfd_section, TYPE_LENGTH, value_as_address(), value_at(), value_at_lazy(), value_contents_raw(), value_from_register(), and VALUE_LVAL.
Referenced by ada_read_var_value().
struct value* default_value_from_register (struct type * type, int regnum, struct frame_info * frame) [read]
Definition at line 622 of file findvar.c.
References allocate_value(), gdbarch_byte_order(), get_frame_arch(), get_frame_id(), len, lval_register, register_size(), regnum, set_value_offset(), TYPE_LENGTH, VALUE_FRAME_ID, VALUE_LVAL, and VALUE_REGNUM.
Referenced by gdbarch_alloc(), s390_value_from_register(), and spu_value_from_register().
void deprecated_set_value_type (struct value * value, struct type * type)
Definition at line 789 of file value.c.
References type, and value::type.
Referenced by ada_value_assign(), coerce_for_assign(), do_search_struct_field(), evaluate_subexp_java(), evaluate_subexp_standard(), gnuv2_virtual_fn_field(), readjust_indirect_value_type(), type_from_class(), value_addr(), value_cast(), value_cast_pointers(), value_full_object(), value_nsstring(), and value_ref().
struct frame_id* deprecated_value_frame_id_hack (struct value *) [read]
Definition at line 1236 of file value.c.
References value::frame_id.
struct internalvar** deprecated_value_internalvar_hack (struct value *) [read]
Definition at line 1230 of file value.c.
References value::internalvar, and value::location.
enum lval_type* deprecated_value_lval_hack (struct value *)
Definition at line 1189 of file value.c.
References value::lval.
int deprecated_value_modifiable (struct value * value)
Definition at line 1248 of file value.c.
References value::modifiable.
Referenced by ada_value_assign(), can_use_hardware_watchpoint(), evaluate_subexp_opencl(), num_memory_accesses(), and value_assign().
short* deprecated_value_regnum_hack (struct value *)
Definition at line 1242 of file value.c.
References value::regnum.
int destructor_name_p (const char * name, struct type * type)
Definition at line 2994 of file valops.c.
References _, error(), len, strchr(), and type_name_no_tag_or_error().
void error_value_optimized_out (void)
Definition at line 911 of file value.c.
References _, and error().
Referenced by address_from_register(), and require_not_optimized_out().
struct value* evaluate_expression (struct expression * exp) [read]
Definition at line 142 of file eval.c.
References EVAL_NORMAL, evaluate_subexp(), and NULL_TYPE.
Referenced by ada_read_renaming_var_value(), breakpoint_cond_eval(), do_one_display(), encode_actions_1(), execute_control_command(), gdb_eval(), info_mach_region_command(), init_if_undefined_command(), mi_cmd_data_evaluate_expression(), output_command_const(), parse_and_eval(), parse_and_eval_address(), parse_and_eval_long(), parse_to_comma_and_eval(), print_command_1(), print_variable_or_computed(), return_command(), set_command(), should_stop_exception(), value_of_root_1(), varobj_create(), varobj_set_value(), wrap_evaluate_expression(), and x_command().
struct value* evaluate_subexp (struct type * expect_type, struct expression * exp, int * pos, enum noside noside) [read]
Definition at line 68 of file eval.c.
References exp_descriptor::evaluate_exp, language_defn::la_exp_desc, and expression::language_defn.
Referenced by evaluate_expression(), evaluate_subexp_for_sizeof(), evaluate_subexp_opencl(), evaluate_subexp_standard(), evaluate_subexp_type(), evaluate_subexp_with_coercion(), evaluate_subexpression_type(), evaluate_type(), fetch_subexp_value(), gen_expr(), print_object_command(), and value_f90_subarray().
struct value* evaluate_subexp_with_coercion (struct expression * , int * , enum noside) [read]
struct value* evaluate_subexpression_type (struct expression * exp, int subexp) [read]
Definition at line 164 of file eval.c.
References EVAL_AVOID_SIDE_EFFECTS, evaluate_subexp(), and NULL_TYPE.
Referenced by parse_expression_for_completion().
struct value* evaluate_type (struct expression * exp) [read]
Definition at line 153 of file eval.c.
References EVAL_AVOID_SIDE_EFFECTS, evaluate_subexp(), and NULL_TYPE.
Referenced by gnuv3_get_type_from_type_info(), maintenance_print_type(), print_variable_or_computed(), varobj_create(), whatis_exp(), and wrap_evaluate_type().
char* extract_field_op (struct expression * exp, int * subexp)
Definition at line 271 of file eval.c.
References BYTES_TO_EXP_ELEM, expression::elts, exp_element::longconst, longest_to_int(), exp_element::opcode, and exp_element::string.
Referenced by parse_expression_for_completion().
void fetch_subexp_value (struct expression * exp, int * pc, struct value ** valp, struct value ** resultp, struct value ** val_chain, int preserve_errors)
Definition at line 193 of file eval.c.
References gdb_exception::error, EVAL_NORMAL, evaluate_subexp(), MEMORY_ERROR, NULL_TYPE, gdb_exception::reason, RETURN_MASK_ALL, RETURN_MASK_ERROR, throw_exception(), TRY_CATCH, value_fetch_lazy(), value_lazy(), value_mark(), and value_release_to_mark().
Referenced by check_condition(), update_watchpoint(), watch_command_1(), and watchpoint_check().
struct value* find_function_in_inferior (const char * , struct objfile **) [read]
Definition at line 132 of file valops.c.
References _, error(), get_objfile_arch(), LOC_BLOCK, lookup_bound_minimal_symbol(), lookup_function_type(), lookup_pointer_type(), lookup_symbol(), bound_minimal_symbol::minsym, bound_minimal_symbol::objfile, SYMBOL_CLASS, SYMBOL_SYMTAB, SYMBOL_VALUE_ADDRESS, target_has_execution, type, value_from_pointer(), value_of_variable(), and VAR_DOMAIN.
Referenced by call_target_sbrk(), checkpoint_command(), evaluate_subexp_standard(), inferior_call_waitpid(), lookup_child_selector(), lookup_objc_class(), print_object_command(), value_allocate_space_in_inferior(), and value_nsstring().
int find_overload_match (struct value ** args, int nargs, const char * name, enum oload_search_type method, struct value ** objp, struct symbol * fsym, struct value ** valp, struct symbol ** symp, int * staticp, const int no_adl)
Definition at line 2408 of file valops.c.
References _, all_cleanups(), BOTH, check_typedef(), classify_oload_match(), coerce_ref(), compare_badness(), cp_func_name(), do_cleanups(), error(), find_oload_champ(), find_oload_champ_namespace(), gdb_assert, INCOMPATIBLE, make_cleanup(), METHOD, name, NON_METHOD, NON_STANDARD, NOT_FOUND_ERROR, null_cleanup(), oload_method_static(), search_struct_field(), SYMBOL_NATURAL_NAME, SYMBOL_TYPE, throw_error(), TYPE_CODE, TYPE_CODE_FUNC, TYPE_CODE_PTR, TYPE_CODE_REF, TYPE_CODE_STRUCT, TYPE_DOMAIN_TYPE, TYPE_FN_FIELD_VIRTUAL_P, TYPE_NAME, value_addr(), value_find_oload_method_list(), value_fn_field(), value_ind(), value_type(), value_virtual_fn_field(), warning(), and xfree().
Referenced by evaluate_subexp_standard(), and value_user_defined_cpp_op().
void free_all_values (void)
Definition at line 1326 of file value.c.
References value::next, value::released, and value_free().
void free_value_chain (struct value * v)
Definition at line 1344 of file value.c.
References value::next, value_free(), and value_next().
Referenced by check_condition().
int get_internalvar_integer (struct internalvar * var, LONGEST * l)
Definition at line 1948 of file value.c.
References check_typedef(), internalvar::internalvar_data::integer, internalvar::kind, TYPE_CODE, TYPE_CODE_INT, internalvar::u, internalvar::internalvar_data::val, internalvar::internalvar_data::value, value_as_long(), and value_type().
Referenced by get_number_trailer(), and linespec_parse_variable().
char* internalvar_name (struct internalvar * var)
Definition at line 2123 of file value.c.
References internalvar::name.
Referenced by dump_subexp_body_standard(), gen_expr(), and print_subexp_standard().
struct internalvar* lookup_internalvar (const char * name) [read]
Definition at line 1847 of file value.c.
References create_internalvar(), and lookup_only_internalvar().
Referenced by add_internal_function(), clear_exit_convenience_vars(), core_open(), find_command(), forward_search_command(), get_number_trailer(), handle_inferior_event(), reverse_search_command(), set_breakpoint_count(), set_next_address(), set_traceframe_context(), set_traceframe_num(), set_tracepoint_count(), set_tracepoint_num(), and x_command().
struct internalvar* lookup_only_internalvar (const char * name) [read]
Definition at line 1753 of file value.c.
References internalvar::name, and internalvar::next.
Referenced by linespec_parse_variable(), lookup_internalvar(), write_dollar_variable(), and yylex().
void mark_value_bytes_unavailable (struct value * value, int offset, int length)
Definition at line 382 of file value.c.
References range::length, max, min, offset, range::offset, range_lessthan(), ranges_overlap(), ULONGEST, VEC_block_remove, VEC_index, VEC_iterate, VEC_length, VEC_lower_bound, and VEC_safe_insert.
Referenced by aarch64_pseudo_read_value(), amd64_pseudo_register_read_value(), dwarf2_evaluate_loc_desc_full(), i386_pseudo_register_read_into_value(), read_pieced_value(), read_value_memory(), regcache_cooked_read_value(), value_contents_copy_raw(), value_fetch_lazy(), value_field_bitfield(), and value_from_register().
void modify_field (struct type * type, gdb_byte * addr, LONGEST fieldval, int bitpos, int bitsize)
Definition at line 3040 of file value.c.
References _, value::bitpos, value::bitsize, extract_unsigned_integer(), gdbarch_bits_big_endian(), gdbarch_byte_order(), get_type_arch(), store_unsigned_integer(), ULONGEST, and warning().
Referenced by make_array_descriptor(), set_internalvar_component(), and value_assign().
void pack_long (gdb_byte * buf, struct type * type, LONGEST num)
Definition at line 3087 of file value.c.
References _, check_typedef(), error(), gdbarch_byte_order(), get_type_arch(), len, store_signed_integer(), store_typed_address(), TYPE_CODE, TYPE_CODE_BOOL, TYPE_CODE_CHAR, TYPE_CODE_ENUM, TYPE_CODE_FLAGS, TYPE_CODE_INT, TYPE_CODE_MEMBERPTR, TYPE_CODE_PTR, TYPE_CODE_RANGE, TYPE_CODE_REF, and TYPE_LENGTH.
Referenced by emit_numeric_character(), frame_unwind_got_address(), generic_emit_char(), linux_make_mappings_callback(), linux_make_mappings_corefile_notes(), and value_from_longest().
struct value* parse_and_eval (const char * exp) [read]
Definition at line 107 of file eval.c.
References do_cleanups(), evaluate_expression(), free_current_contents(), make_cleanup(), and parse_expression().
Referenced by display_tib(), do_captured_thread_select(), dump_value_to_file(), ignore_command(), info_task(), info_vtbl_command(), mi_cmd_trace_define_variable(), parse_frame_specification_1(), print_ada_task_info(), quit_force(), task_command_1(), and trace_variable_command().
CORE_ADDR parse_and_eval_address (const char * exp)
Definition at line 79 of file eval.c.
References do_cleanups(), evaluate_expression(), free_current_contents(), make_cleanup(), parse_expression(), and value_as_address().
Referenced by ada_exception_name_addr_1(), ada_unhandled_exception_name_addr(), ada_unhandled_exception_name_addr_from_raise(), add_symbol_file_command(), add_symbol_file_from_memory_command(), bsd_kvm_pcb_cmd(), bsd_kvm_proc_cmd(), disassemble_command(), dump_memory_to_file(), go32_pte_for_address(), maintenance_translate_address(), mem_command(), mi_cmd_data_read_memory(), mi_cmd_data_read_memory_bytes(), mi_cmd_data_write_memory(), mi_cmd_data_write_memory_bytes(), mi_cmd_data_write_register_values(), mi_cmd_disassemble(), mi_cmd_trace_find(), restore_command(), set_section_command(), set_task_exc_port_cmd(), set_thread_exc_port_cmd(), sym_info(), trace_find_outside_command(), trace_find_pc_command(), trace_find_range_command(), and unwind_command().
LONGEST parse_and_eval_long (const char * exp)
Definition at line 94 of file eval.c.
References do_cleanups(), evaluate_expression(), free_current_contents(), LONGEST, make_cleanup(), parse_expression(), and value_as_long().
Referenced by add_inferior_command(), backtrace_command_1(), breakpoint_1(), call_lseek(), clone_inferior_command(), cmd_record_goto(), continue_command(), delete_checkpoint_command(), detach_checkpoint_command(), display_selectors(), do_set_command(), down_silently_base(), go32_pde(), go32_pte(), go32_sgdt(), go32_sidt(), go32_sldt(), inferior_command(), info_checkpoints_command(), maintenance_info_program_spaces_command(), restart_command(), restore_command(), set_radix(), show_commands(), show_values(), signal_command(), signals_info(), step_1(), trace_find_command(), trace_find_tracepoint_command(), and up_silently_base().
struct type* parse_and_eval_type (char * p, int length) [read]
Definition at line 3059 of file eval.c.
References _, expression::elts, error(), memcpy(), exp_element::opcode, parse_expression(), and exp_element::type.
Referenced by safe_parse_type().
struct value* parse_to_comma_and_eval (const char ** expp) [read]
Definition at line 124 of file eval.c.
References do_cleanups(), evaluate_expression(), free_current_contents(), make_cleanup(), and parse_exp_1().
Referenced by disassemble_command(), info_port_rights(), linespec_expression_to_pc(), parse_find_args(), ui_printf(), and watch_command_1().
void preserve_one_value (struct value * , struct objfile * , htab_t)
Definition at line 2211 of file value.c.
References copy_type_recursive(), value::enclosing_type, value::type, and TYPE_OBJFILE.
Referenced by preserve_one_internalvar(), and preserve_values().
void preserve_values (struct objfile *)
Definition at line 2250 of file value.c.
References create_copied_types_hash(), value_history_chunk::next, internalvar::next, preserve_one_internalvar(), preserve_one_value(), preserve_python_values(), VALUE_HISTORY_CHUNK, and value_history_chunk::values.
Referenced by free_objfile(), and reread_symbols().
int print_address_demangle (const struct value_print_options * , struct gdbarch * , CORE_ADDR , struct ui_file * , int)
Definition at line 786 of file printcmd.c.
References value_print_options::addressprint, fputs_filtered(), paddress(), and print_address_symbolic().
Referenced by c_val_print(), f_val_print(), generic_val_print(), gnuv3_print_method_ptr(), java_val_print(), pascal_val_print(), and print_function_pointer_address().
void print_decimal_floating (const gdb_byte * valaddr, struct type * type, struct ui_file * stream)
Definition at line 1131 of file valprint.c.
References decimal_to_string(), fputs_filtered(), gdbarch_byte_order(), get_type_arch(), len, MAX_DECIMAL_STRING, and TYPE_LENGTH.
Referenced by generic_val_print().
void print_floating (const gdb_byte * valaddr, struct type * type, struct ui_file * stream)
Definition at line 1058 of file valprint.c.
References float_infinite, float_nan, floatformat_classify(), floatformat_from_type(), floatformat_is_negative(), floatformat_mantissa(), fprintf_filtered(), fputs_filtered(), len, TYPE_CODE, TYPE_CODE_FLT, TYPE_LENGTH, and unpack_double().
Referenced by ada_print_floating(), generic_val_print(), and print_scalar_formatted().
void print_longest (struct ui_file * stream, int format, int use_local, LONGEST val)
Definition at line 1000 of file valprint.c.
References _, fputs_filtered(), int_string(), and internal_error().
Referenced by ada_print_scalar(), ada_val_print_1(), ax_print(), dump_raw_expression(), generic_val_print(), gnuv3_print_method_ptr(), h8300_print_register(), java_val_print(), m68hc11_print_register(), mt_registers_info(), print_scalar_formatted(), print_type_scalar(), and val_print_type_code_int().
void print_variable_and_value (const char * name, struct symbol * var, struct frame_info * frame, struct ui_file * stream, int indent)
Definition at line 1980 of file printcmd.c.
References common_val_print(), current_language, value_print_options::deref_ref, fprintf_filtered(), get_user_print_options(), gdb_exception::message, n_spaces(), read_var_value(), gdb_exception::reason, RETURN_MASK_ERROR, SYMBOL_PRINT_NAME, and TRY_CATCH.
Referenced by do_print_variable_and_value().
void read_frame_register_value (struct value * value, struct frame_info * frame)
Definition at line 656 of file findvar.c.
References check_typedef(), gdb_assert, get_frame_arch(), get_frame_register_value(), len, lval_register, offset, reg_offset, register_size(), regnum, set_value_optimized_out(), TYPE_LENGTH, value_contents_copy(), VALUE_LVAL, value_offset(), value_optimized_out(), VALUE_REGNUM, and value_type().
Referenced by value_from_register().
void read_value_memory (struct value * val, int embedded_offset, int stack, CORE_ADDR memaddr, gdb_byte * buffer, size_t length)
Definition at line 950 of file valops.c.
References do_cleanups(), exec_ops, gdb_assert, mem_range::length, make_cleanup(), mark_value_bytes_unavailable(), max, mem_ranges_overlap(), memaddr, min, normalize_mem_ranges(), read_memory(), read_stack(), target_section_table::sections, target_section_table::sections_end, mem_range::start, target_get_section_table(), traceframe_available_memory(), VEC, VEC_cleanup, and VEC_iterate.
Referenced by call_function_by_hand(), read_pieced_value(), value_fetch_lazy(), and value_repeat().
struct value* read_var_value (struct symbol * var, struct frame_info * frame) [read]
Definition at line 609 of file findvar.c.
References gdb_assert, language_defn::la_read_var_value, language_def(), and SYMBOL_LANGUAGE.
Referenced by bpfinishpy_init(), enumerate_locals(), finish_command_continuation(), frapy_read_var(), insert_exception_resume_breakpoint(), print_variable_and_value(), read_frame_arg(), read_frame_local(), return_command(), sympy_value(), value_of_this(), and value_of_variable().
struct value* readjust_indirect_value_type (struct value * value, struct type * enc_type, struct type * original_type, struct value * original_val) [read]
Definition at line 3326 of file value.c.
References deprecated_set_value_type(), set_value_embedded_offset(), set_value_enclosing_type(), TYPE_TARGET_TYPE, value_full_object(), and value_pointed_to_offset().
Referenced by coerce_ref(), and value_ind().
int record_latest_value (struct value * val)
Definition at line 1511 of file value.c.
References memset(), value::modifiable, release_value(), value_fetch_lazy(), value_history_chain, VALUE_HISTORY_CHUNK, value_history_count, value_lazy(), value_history_chunk::values, and xmalloc().
Referenced by print_command_1(), and print_return_value().
struct value* register_value_being_returned (struct type * valtype, struct regcache * retbuf) [read]
void release_value (struct value * val)
Definition at line 1359 of file value.c.
References value::next, and value::released.
Referenced by address_from_register(), bpstat_copy(), do_examine(), dwarf2_compute_name(), frame_register_unwind(), m68hc11_frame_prev_register(), m88k_frame_prev_register(), mep_frame_prev_register(), record_latest_value(), release_value_or_incref(), set_internalvar(), value_of_dwarf_reg_entry(), watch_command_1(), and watchpoint_check().
void release_value_or_incref (struct value * val)
Definition at line 1389 of file value.c.
References release_value(), value::released, and value_incref().
void set_internalvar (struct internalvar * var, struct value * val)
Definition at line 2011 of file value.c.
References _, internalvar::internalvar_data::canonical, check_typedef(), clear_internalvar(), error(), internalvar::internalvar_data::fn, gdb_assert, get_internalvar_function(), internalvar::kind, lval_internalvar, internalvar::name, release_value(), TYPE_CODE, TYPE_CODE_INTERNAL_FUNCTION, TYPE_CODE_VOID, internalvar::u, value_copy(), value_fetch_lazy(), VALUE_INTERNALVAR, value_lazy(), VALUE_LVAL, and value_type().
Referenced by find_command(), set_next_address(), value_assign(), and x_command().
void set_internalvar_component (struct internalvar * var, int offset, int bitpos, int bitsize, struct value * newvalue)
Definition at line 1986 of file value.c.
References _, internal_error(), internalvar::kind, memcpy(), modify_field(), TYPE_LENGTH, internalvar::u, internalvar::internalvar_data::value, value_as_long(), value_contents(), value_contents_writeable(), and value_type().
Referenced by value_assign().
void set_internalvar_integer (struct internalvar * var, LONGEST l)
Definition at line 2063 of file value.c.
References clear_internalvar(), internalvar::internalvar_data::integer, internalvar::kind, internalvar::internalvar_data::type, internalvar::u, and internalvar::internalvar_data::val.
Referenced by core_open(), find_command(), forward_search_command(), handle_inferior_event(), reverse_search_command(), set_breakpoint_count(), set_traceframe_context(), set_traceframe_num(), set_tracepoint_count(), and set_tracepoint_num().
void set_internalvar_string (struct internalvar * var, const char * string)
Definition at line 2074 of file value.c.
References clear_internalvar(), internalvar::kind, internalvar::internalvar_data::string, and internalvar::u.
Referenced by set_traceframe_context().
void set_value_address (struct value * , CORE_ADDR)
Definition at line 1222 of file value.c.
References value::address, gdb_assert, value::location, value::lval, lval_internalvar, and lval_internalvar_component.
Referenced by coerce_unspec_val_to_type(), elf_gnu_ifunc_resolve_addr(), elf_gnu_ifunc_resolver_return_stop(), ensure_lval(), java_link_class_type(), java_value_print(), value_fn_field(), value_from_contents_and_address(), value_of_dwarf_reg_entry(), and value_repeat().
void set_value_bitpos (struct value * , int bit)
Definition at line 811 of file value.c.
References bit, and value::bitpos.
Referenced by ada_value_primitive_packed_val(), and coerce_unspec_val_to_type().
void set_value_bitsize (struct value * , int bit)
Definition at line 822 of file value.c.
References bit, and value::bitsize.
Referenced by ada_value_primitive_packed_val(), and coerce_unspec_val_to_type().
void set_value_component_location (struct value * component, const struct value * whole)
Definition at line 1484 of file value.c.
References value::computed, lval_funcs::copy_closure, value::location, value::lval, lval_computed, lval_internalvar, lval_internalvar_component, and VALUE_LVAL.
Referenced by ada_value_primitive_packed_val(), coerce_unspec_val_to_type(), value_primitive_field(), value_ptradd(), value_slice(), and value_subscripted_rvalue().
void set_value_embedded_offset (struct value * value, int val)
Definition at line 1155 of file value.c.
References value::embedded_offset.
Referenced by do_search_struct_field(), readjust_indirect_value_type(), value_full_object(), and value_non_lval().
void set_value_enclosing_type (struct value * val, struct type * new_type)
Definition at line 2646 of file value.c.
References value::contents, value::enclosing_type, TYPE_LENGTH, value_enclosing_type(), and xrealloc().
Referenced by readjust_indirect_value_type(), value_addr(), value_assign(), value_cast(), value_cast_pointers(), and value_full_object().
void set_value_initialized (struct value * , int)
Definition at line 3424 of file value.c.
References value::initialized, and exsummary::status.
Referenced by dwarf2_evaluate_loc_desc_full().
void set_value_lazy (struct value * value, int val)
Definition at line 1037 of file value.c.
References value::lazy.
Referenced by gnuv2_virtual_fn_field(), java_link_class_type(), java_value_print(), value_assign(), value_fetch_lazy(), and value_of_dwarf_reg_entry().
void set_value_offset (struct value * , int offset)
Definition at line 800 of file value.c.
References offset, and value::offset.
Referenced by ada_value_primitive_packed_val(), default_value_from_register(), dwarf2_evaluate_loc_desc_full(), gnuv2_virtual_fn_field(), java_value_print(), s390_value_from_register(), spu_value_from_register(), value_slice(), and value_subscripted_rvalue().
void set_value_optimized_out (struct value * value, int val)
Definition at line 1108 of file value.c.
References value::optimized_out.
Referenced by allocate_optimized_out_value(), coerce_unspec_val_to_type(), read_frame_register_value(), read_pieced_value(), value_fetch_lazy(), value_from_register(), and write_pieced_value().
void set_value_parent (struct value * value, struct value * parent)
Definition at line 836 of file value.c.
References value::parent, value_free(), and value_incref().
Referenced by ada_value_primitive_packed_val(), value_copy(), and value_primitive_field().
void set_value_pointed_to_offset (struct value * value, int val)
Definition at line 1167 of file value.c.
References value::pointed_to_offset.
Referenced by value_addr(), value_assign(), value_cast(), value_cast_pointers(), and value_non_lval().
void set_value_stack (struct value * value, int val)
Definition at line 1049 of file value.c.
References value::stack.
Referenced by dwarf2_evaluate_loc_desc_full(), and frame_unwind_got_memory().
enum return_value_convention struct_return_convention (struct gdbarch * gdbarch, struct value * function, struct type * value_type)
Definition at line 3391 of file value.c.
References _, code, error(), gdbarch_return_value(), TYPE_CODE, and TYPE_CODE_ERROR.
Referenced by return_command(), and using_struct_return().
int symbol_read_needs_frame (struct symbol *)
Definition at line 345 of file findvar.c.
References _, gdb_assert_not_reached, LOC_ARG, LOC_BLOCK, LOC_COMPUTED, LOC_CONST, LOC_CONST_BYTES, LOC_LABEL, LOC_LOCAL, LOC_OPTIMIZED_OUT, LOC_REF_ARG, LOC_REGISTER, LOC_REGPARM_ADDR, LOC_STATIC, LOC_TYPEDEF, LOC_UNDEF, LOC_UNRESOLVED, SYMBOL_CLASS, and SYMBOL_COMPUTED_OPS.
Referenced by default_read_var_value(), push_variable(), sympy_needs_frame(), sympy_value(), value_of_variable(), and write_var_from_sym().
void type_print (struct type * type, const char * varstring, struct ui_file * stream, int show)
Definition at line 363 of file typeprint.c.
References LA_PRINT_TYPE.
Referenced by ada_dump_subexp_body(), ada_lookup_struct_elt_type(), ada_print_subexp(), ada_val_print_1(), ada_value_print(), c_print_typedef(), c_value_print(), disassemble_dwarf_expression(), dump_subexp_body_standard(), generic_val_print(), inspect_type(), java_type_print_base(), java_value_print(), list_arg_or_local(), m2_print_typedef(), pascal_print_typedef(), pascal_type_print_base(), pascal_value_print(), print_subexp_standard(), print_symbol_info(), print_variable_or_computed(), py_print_type(), type_to_string(), whatis_exp(), and wrap_type_print().
char* type_to_string (struct type * type)
Definition at line 373 of file typeprint.c.
References do_cleanups(), make_cleanup_ui_file_delete(), mem_fileopen(), gdb_exception::reason, RETURN_MASK_ALL, TRY_CATCH, type_print(), and ui_file_xstrdup().
Referenced by c_get_string(), gnuv3_get_typeid(), lookup_struct_elt_type(), update_type_if_necessary(), varobj_get_type(), and watch_command_1().
void typedef_print (struct type * type, struct symbol * news, struct ui_file * stream)
Definition at line 341 of file typeprint.c.
References LA_PRINT_TYPEDEF.
Referenced by print_symbol_info().
void unop_promote (const struct language_defn * language, struct gdbarch * gdbarch, struct value ** arg1)
Definition at line 430 of file eval.c.
References builtin_type::builtin_int, builtin_type(), check_typedef(), coerce_ref(), is_integral_type(), language_defn::la_language, TYPE_LENGTH, value_cast(), and value_type().
Referenced by evaluate_subexp_standard().
int unop_user_defined_p (enum exp_opcode op, struct value * arg1)
Definition at line 268 of file valarith.c.
References check_typedef(), TYPE_CODE, TYPE_CODE_REF, TYPE_CODE_STRUCT, TYPE_TARGET_TYPE, and value_type().
Referenced by evaluate_subexp_standard().
DOUBLEST unpack_double (struct type * type, const gdb_byte * valaddr, int * invp)
Definition at line 2517 of file value.c.
References gdbarch::byte_order, CHECK_TYPEDEF, code, decimal_to_doublest(), extract_typed_floating(), floatformat_from_type(), gdbarch_byte_order(), get_type_arch(), len, TYPE_CODE, TYPE_CODE_DECFLOAT, TYPE_CODE_FLT, TYPE_LENGTH, TYPE_UNSIGNED, ULONGEST, and unpack_long().
Referenced by mips_print_fp_register(), print_floating(), sh64_do_fp_register(), ui_printf(), and value_as_double().
LONGEST unpack_field_as_long (struct type * type, const gdb_byte * valaddr, int fieldno)
Definition at line 2997 of file value.c.
References LONGEST, and unpack_value_field_as_long_1().
Referenced by dynamic_array_type(), and m2_print_unbounded_array().
LONGEST unpack_long (struct type * type, const gdb_byte * valaddr)
Definition at line 2467 of file value.c.
References _, gdbarch::byte_order, check_typedef(), code, decimal_to_doublest(), error(), extract_signed_integer(), extract_typed_address(), extract_typed_floating(), extract_unsigned_integer(), gdbarch_byte_order(), get_type_arch(), len, TYPE_CODE, TYPE_CODE_BOOL, TYPE_CODE_CHAR, TYPE_CODE_DECFLOAT, TYPE_CODE_ENUM, TYPE_CODE_FLAGS, TYPE_CODE_FLT, TYPE_CODE_INT, TYPE_CODE_MEMBERPTR, TYPE_CODE_PTR, TYPE_CODE_RANGE, TYPE_CODE_REF, TYPE_CODE_TYPEDEF, TYPE_LENGTH, TYPE_UNSIGNED, and unpack_long().
Referenced by aarch64_store_return_value(), ada_val_print_1(), alpha_store_return_value(), arm_store_return_value(), avr_integer_to_address(), c_val_print(), do_ppc_sysv_return_value(), evaluate_subexp_c(), f_val_print(), generic_val_print(), hppa32_push_dummy_call(), hppa64_push_dummy_call(), java_val_print(), ppc64_sysv_abi_push_dummy_call(), ppc64_sysv_abi_return_value(), ppc_sysv_abi_push_dummy_call(), print_scalar_formatted(), read_reg(), rs6000_lynx178_return_value(), rs6000_return_value(), spu_integer_to_address(), unpack_double(), unpack_long(), unpack_pointer(), val_print_type_code_flags(), val_print_type_code_int(), value_as_address(), value_as_long(), and value_concat().
CORE_ADDR unpack_pointer (struct type * type, const gdb_byte * valaddr)
Definition at line 2584 of file value.c.
References unpack_long().
Referenced by ada_val_print_1(), c_val_print(), coerce_ref(), dynamic_array_type(), f_val_print(), generic_val_print(), gnuv2_baseclass_offset(), java_val_print(), m2_print_unbounded_array(), m2_val_print(), pascal_val_print(), print_scalar_formatted(), and print_variable_at_address().
int unpack_value_bits_as_long (struct type * field_type, const gdb_byte * valaddr, int embedded_offset, int bitpos, int bitsize, const struct value * original_value, LONGEST * result)
Definition at line 2944 of file value.c.
References gdb_assert, and unpack_value_bits_as_long_1().
Referenced by value_fetch_lazy().
int unpack_value_field_as_long (struct type * type, const gdb_byte * valaddr, int embedded_offset, int fieldno, const struct value * val, LONGEST * result)
Definition at line 2981 of file value.c.
References gdb_assert, and unpack_value_field_as_long_1().
Referenced by print_go_string(), and value_field_bitfield().
int using_struct_return (struct gdbarch * gdbarch, struct value * function, struct type * value_type)
Definition at line 3409 of file value.c.
References RETURN_VALUE_REGISTER_CONVENTION, struct_return_convention(), TYPE_CODE, and TYPE_CODE_VOID.
Referenced by call_function_by_hand(), evaluate_subexp_standard(), and sparc32_push_dummy_code().
void val_print (struct type * type, const gdb_byte * valaddr, int embedded_offset, CORE_ADDR address, struct ui_file * stream, int recurse, const struct value * val, const struct value_print_options * options, const struct language_defn * language)
Definition at line 734 of file valprint.c.
References _, apply_val_pretty_printer(), check_typedef(), fprintf_filtered(), gdb_flush(), language_defn::la_val_print, value_print_options::prettyformat, value_print_options::prettyformat_structs, QUIT, value_print_options::raw, gdb_exception::reason, RETURN_MASK_ERROR, value_print_options::summary, TRY_CATCH, TYPE_STUB, Val_no_prettyformat, Val_prettyformat, Val_prettyformat_default, val_print_scalar_type_p(), and valprint_check_validity().
Referenced by ada_val_print_1(), ada_value_print(), c_value_print(), common_val_print(), cp_print_static_field(), cp_print_value_fields(), default_print_one_register_info(), f77_print_array_1(), f_val_print(), get_register(), java_print_value_fields(), mt_registers_info(), output_register(), pascal_object_print_value_fields(), print_field_values(), sh64_do_register(), val_print_array_elements(), val_print_packed_array_elements(), val_print_scalar_formatted(), and wrap_val_print().
int val_print_string (struct type * elttype, const char * encoding, CORE_ADDR addr, int len, struct ui_file * stream, const struct value_print_options * options)
Definition at line 2454 of file valprint.c.
References gdbarch::byte_order, do_cleanups(), extract_unsigned_integer(), fprintf_filtered(), fputs_filtered(), gdb_flush(), gdbarch_byte_order(), get_type_arch(), LA_PRINT_STRING, make_cleanup(), memory_error_message(), min, value_print_options::print_max, read_string(), target_read_memory(), TYPE_LENGTH, and xfree().
Referenced by c_val_print(), f_val_print(), fprint_target_auxv(), java_value_print(), m2_print_array_contents(), pascal_val_print(), print_formatted(), print_go_string(), print_unpacked_pointer(), and value_get_print_value().
int valprint_check_validity (struct ui_file * stream, struct type * type, int embedded_offset, const struct value * val)
Definition at line 303 of file valprint.c.
References _, CHECK_TYPEDEF, fputs_filtered(), TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_STRUCT, TYPE_CODE_UNION, TYPE_LENGTH, val_print_optimized_out(), val_print_unavailable(), value_bits_synthetic_pointer(), value_bits_valid(), and value_bytes_available().
Referenced by cp_print_value_fields(), and val_print().
struct type* value_actual_type (struct value * value, int resolve_simple_types, int * real_type_found) [read]
Definition at line 869 of file value.c.
References check_typedef(), get_user_print_options(), value_print_options::objectprint, TYPE_CODE, TYPE_CODE_PTR, TYPE_CODE_REF, TYPE_CODE_STRUCT, TYPE_TARGET_TYPE, value_enclosing_type(), value_rtti_indirect_type(), and value_type().
Referenced by adjust_value_for_child_access(), create_child_with_value(), update_type_if_necessary(), and varobj_create().
struct value* value_addr (struct value * arg1) [read]
Definition at line 1509 of file valops.c.
References _, check_typedef(), deprecated_set_value_type(), error(), lookup_pointer_type(), lval_memory, set_value_enclosing_type(), set_value_pointed_to_offset(), TYPE_CODE, TYPE_CODE_FUNC, TYPE_CODE_REF, TYPE_TARGET_TYPE, value_address(), value_coerce_function(), value_coerce_to_target(), value_copy(), value_embedded_offset(), value_enclosing_type(), value_from_pointer(), VALUE_LVAL, and value_type().
Referenced by ada_convert_actual(), amd64_windows_adjust_args_passed_by_pointer(), c_value_print(), call_function_by_hand(), evaluate_subexp_java(), find_function_addr(), find_overload_match(), gnuv2_virtual_fn_field(), gnuv3_get_virtual_fn(), gnuv3_print_vtable(), gnuv3_rtti_type(), java_print_value_fields(), make_array_descriptor(), print_one_vtable(), value_cast_pointers(), value_dynamic_cast(), value_fn_field(), value_ref(), value_reinterpret_cast(), value_x_binop(), value_x_unop(), and watch_command_1().
CORE_ADDR value_address (const struct value *)
Definition at line 1201 of file value.c.
References value::address, value::location, value::lval, lval_internalvar, lval_internalvar_component, value::offset, value::parent, and value_address().
Referenced by ada_tag_value_at_base_address(), ada_to_fixed_type_1(), ada_to_fixed_value(), ada_val_print_1(), ada_value_assign(), ada_value_primitive_packed_val(), ada_value_print(), ada_value_struct_elt(), address_of_variable(), c_value_print(), call_site_to_target_addr(), can_use_hardware_watchpoint(), check_condition(), coerce_unspec_val_to_type(), common_val_print(), compare_value_and_voffset(), cp_print_static_field(), cp_print_value(), desc_bounds(), do_search_struct_field(), dump_value_to_file(), encode_actions_1(), eq_value_and_voffset(), evaluate_subexp_standard(), find_function_addr(), find_method_list(), frame_register_unwind(), frame_unwind_register_value(), frv_push_dummy_call(), get_java_utf8_name(), gnuv2_value_rtti_type(), gnuv3_get_typeid(), gnuv3_rtti_type(), hash_value_and_voffset(), is_unique_ancestor(), java_link_class_type(), java_value_print(), m32r_push_dummy_call(), mips_eabi_push_dummy_call(), mn10300_push_dummy_call(), msp430_push_dummy_call(), pascal_object_print_static_field(), print_formatted(), print_one_vtable(), read_fat_string_value(), search_struct_method(), thin_data_pntr(), type_from_class(), unwrap_value(), update_watchpoint(), v850_push_dummy_call(), value_addr(), value_address(), value_as_address(), value_assign(), value_assign_to_component(), value_cast(), value_cast_structs(), value_coerce_array(), value_coerce_function(), value_dynamic_cast(), value_fetch_lazy(), value_full_object(), value_pointer(), value_primitive_field(), value_print(), value_repeat(), and x_command().
struct value* value_aggregate_elt (struct type * curtype, char * name, struct type * expect_type, int want_address, enum noside noside) [read]
Definition at line 3022 of file valops.c.
References _, internal_error(), TYPE_CODE, TYPE_CODE_NAMESPACE, TYPE_CODE_STRUCT, TYPE_CODE_UNION, value_namespace_elt(), and value_struct_elt_for_reference().
Referenced by evaluate_subexp_standard().
struct value* value_allocate_space_in_inferior (int) [read]
Definition at line 190 of file valops.c.
References _, call_function_by_hand(), error(), find_function_in_inferior(), get_objfile_arch(), target_has_execution, value_from_longest(), and value_logical_not().
Referenced by allocate_space_in_inferior(), ensure_lval(), and find_func_descr().
struct value* value_array (int lowbound, int highbound, struct value ** elemvec) [read]
Definition at line 1631 of file valops.c.
References _, allocate_value(), language_defn::c_style_arrays, current_language, error(), lookup_array_range_type(), TYPE_LENGTH, value_contents_copy(), and value_enclosing_type().
Referenced by evaluate_subexp_standard().
CORE_ADDR value_as_address (struct value * val)
Definition at line 2349 of file value.c.
References coerce_array(), gdbarch_addr_bits_remove(), gdbarch_integer_to_address(), gdbarch_integer_to_address_p(), get_type_arch(), TYPE_CODE, TYPE_CODE_FUNC, TYPE_CODE_METHOD, TYPE_CODE_PTR, TYPE_CODE_REF, unpack_long(), value_address(), value_as_long(), value_contents(), and value_type().
Referenced by ada_tag_name_from_tsd(), ada_value_slice_from_ptr(), ada_varobj_ind(), address_from_register(), c_get_string(), c_value_print(), call_site_to_target_addr(), default_read_var_value(), disassemble_command(), do_one_display(), elf_gnu_ifunc_resolve_addr(), elf_gnu_ifunc_resolver_return_stop(), evaluate_subexp_java(), evaluate_subexp_standard(), find_function_addr(), get_addr_from_python(), gnuv2_value_rtti_type(), gnuv3_get_typename_from_type_info(), gnuv3_get_virtual_fn(), gnuv3_get_vtable(), gnuv3_print_vtable(), gnuv3_rtti_type(), handle_inferior_event(), hppa32_hpux_find_global_pointer(), hppa64_hpux_find_global_pointer(), hppa_linux_find_global_pointer(), hppabsd_find_global_pointer(), indirect_pieced_value(), info_mach_region_command(), insert_exception_resume_breakpoint(), insert_exception_resume_from_probe(), java_class_from_object(), java_class_is_primitive(), java_value_print(), linespec_expression_to_pc(), parse_and_eval_address(), parse_find_args(), parse_frame_specification_1(), ppc64_sysv_abi_push_dummy_call(), print_one_vtable(), printf_c_string(), printf_wide_c_string(), ptid_from_atcb_common(), read_atcb(), read_known_tasks_list(), svr4_handle_solib_event(), value_equal(), value_ind(), value_less(), value_ptradd(), watch_command_1(), and x_command().
DOUBLEST value_as_double (struct value * val)
Definition at line 2334 of file value.c.
References _, error(), unpack_double(), value_contents(), and value_type().
Referenced by cast_to_fixed(), decimal_from_floating(), scalar_binop(), value_cast(), value_equal(), value_less(), value_logical_not(), value_neg(), and value_pos().
LONGEST value_as_long (struct value * val)
Definition at line 2324 of file value.c.
References coerce_array(), unpack_long(), value_contents(), and value_type().
Referenced by ada_array_bound(), ada_array_length(), ada_tag_value_at_base_address(), ada_type_of_array(), ada_value_binop(), ada_which_variant_applies(), add_piece(), aggregate_assign_from_choices(), allocate_space_in_inferior(), call_target_sbrk(), cast_from_fixed(), cast_to_fixed(), check_condition(), checkpoint_command(), decimal_from_integral(), desc_bounds(), display_tib(), do_captured_thread_select(), dwarf2_evaluate_loc_desc_full(), ensure_lval(), evaluate_subexp_java(), evaluate_subexp_modula2(), evaluate_subexp_standard(), execute_stack_op(), find_func_descr(), find_function_addr(), gen_expr(), gen_repeat(), get_int_var_value(), get_internalvar_integer(), get_java_utf8_name(), get_number_trailer(), gnuv2_virtual_fn_field(), gnuv3_baseclass_offset(), gnuv3_rtti_type(), ignore_command(), inferior_call_waitpid(), info_port_rights(), info_task(), java_link_class_type(), linespec_parse_variable(), lookup_child_selector(), lookup_objc_class(), m68hc11_frame_prev_register(), m88k_frame_prev_register(), mep_frame_prev_register(), mi_cmd_trace_define_variable(), msp430_prev_register(), parse_and_eval_long(), parse_find_args(), parse_frame_specification_1(), pos_atr(), print_ada_task_info(), print_object_command(), printf_pointer(), ptid_from_atcb_common(), quit_force(), rank_one_type(), read_atcb(), read_fat_string_value(), rl78_prev_register(), s390_unwind_pseudo_register(), scalar_binop(), scan_discrim_bound(), set_internalvar_component(), task_command_1(), trace_variable_command(), type_from_class(), ui_printf(), value_as_address(), value_assign(), value_cast(), value_complement(), value_concat(), value_dynamic_cast(), value_equal(), value_f90_subarray(), value_in(), value_less(), value_neg(), value_pos(), value_ptrdiff(), and value_val_atr().
struct value* value_assign (struct value * toval, struct value * fromval) [read]
Definition at line 1036 of file valops.c.
References _, CHECK_TYPEDEF, coerce_array(), coerce_ref(), current_target, deprecated_register_changed_hook, deprecated_safe_get_selected_frame(), deprecated_value_modifiable(), error(), frame_find_by_id(), gdb_assert, gdbarch_convert_register_p(), gdbarch_value_to_register(), get_frame_arch(), get_frame_id(), get_frame_register_bytes(), get_type_arch(), HOST_CHAR_BIT, int, LONGEST, lval_computed, lval_internalvar, lval_internalvar_component, lval_memory, lval_register, memcpy(), modify_field(), NOT_AVAILABLE_ERROR, observer_notify_target_changed(), offset, value::parent, put_frame_register_bytes(), read_memory(), select_frame(), set_internalvar(), set_internalvar_component(), set_value_enclosing_type(), set_value_lazy(), set_value_pointed_to_offset(), throw_error(), type, TYPE_CODE, TYPE_CODE_PTR, TYPE_LENGTH, TYPE_UNSIGNED, ULONGEST, value_address(), value_as_long(), value_bitpos(), value_bitsize(), value_cast(), value_computed_funcs(), value_contents(), value_contents_raw(), value_copy(), value_enclosing_type(), VALUE_FRAME_ID, value_from_longest(), VALUE_INTERNALVAR, VALUE_LVAL, value_must_coerce_to_target(), value_of_internalvar(), value_offset(), value_parent(), value_pointed_to_offset(), VALUE_REGNUM, value_type(), lval_funcs::write, and write_memory_with_notification().
Referenced by ada_value_assign(), evaluate_subexp_opencl(), evaluate_subexp_standard(), lval_func_write(), and varobj_set_value().
struct value* value_at (struct type * type, CORE_ADDR addr) [read]
Definition at line 936 of file valops.c.
References get_value_at().
Referenced by ada_value_primitive_packed_val(), c_val_print(), default_read_var_value(), dynamic_array_type(), evaluate_subexp_java(), generic_val_print(), gnuv3_get_vtable(), java_class_from_object(), java_value_print(), pascal_val_print(), print_variable_at_address(), value_cast_structs(), and value_dynamic_cast().
struct value* value_at_lazy (struct type * type, CORE_ADDR addr) [read]
Definition at line 944 of file valops.c.
References get_value_at().
Referenced by ada_value_slice_from_ptr(), ada_value_struct_elt(), coerce_ref(), default_read_var_value(), do_examine(), do_search_struct_field(), dwarf2_evaluate_loc_desc_full(), dynamic_cast_check_1(), dynamic_cast_check_2(), evaluate_subexp_standard(), frame_unwind_got_memory(), gnuv3_get_typeid(), gnuv3_get_vtable(), m2_print_unbounded_array(), print_subexp_standard(), stpy_convert_to_value(), value_cast(), value_cast_structs(), value_coerce_to_target(), value_dynamic_cast(), value_full_object(), value_ind(), and value_static_field().
int value_available_contents_eq (const struct value * val1, int offset1, const struct value * val2, int offset2, int length)
Definition at line 566 of file value.c.
References value::contents, find_first_range_overlap(), gdb_assert, value::lazy, range::length, max, memcmp(), min, range::offset, offset1, ULONGEST, and VEC_index.
Referenced by java_value_print(), read_frame_arg(), val_print_array_elements(), and val_print_packed_array_elements().
struct value* value_binop (struct value * arg1, struct value * arg2, enum exp_opcode op) [read]
Definition at line 1445 of file valarith.c.
References _, check_typedef(), error(), is_integral_type(), scalar_binop(), TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_DECFLOAT, TYPE_CODE_FLT, TYPE_VECTOR, value_type(), value_vector_widen(), and vector_binop().
Referenced by ada_value_binop(), evaluate_subexp_standard(), execute_stack_op(), value_equal(), value_less(), and vector_binop().
int value_bit_index (struct type * type, const gdb_byte * addr, int index)
Definition at line 1830 of file valarith.c.
References extract_unsigned_integer(), gdbarch_bits_big_endian(), gdbarch_byte_order(), get_discrete_bounds(), get_type_arch(), LONGEST, TYPE_INDEX_TYPE, and word.
Referenced by m2_print_long_set(), m2_val_print(), pascal_val_print(), and value_in().
int value_bitpos (const struct value *)
Definition at line 806 of file value.c.
References value::bitpos.
Referenced by ada_value_assign(), ada_value_primitive_packed_val(), check_pieced_value_bits(), coerce_unspec_val_to_type(), indirect_pieced_value(), read_pieced_value(), value_assign(), value_assign_to_component(), value_fetch_lazy(), and write_pieced_value().
int value_bits_synthetic_pointer (const struct value * value, int offset, int length)
Definition at line 1137 of file value.c.
References value::computed, value::location, value::lval, and lval_computed.
Referenced by cp_print_value_fields(), java_print_value_fields(), lval_func_check_synthetic_pointer(), pascal_object_print_value_fields(), and valprint_check_validity().
int value_bits_valid (const struct value * value, int offset, int length)
Definition at line 1125 of file value.c.
References value::computed, value::location, value::lval, lval_computed, and value::optimized_out.
Referenced by c_val_print(), cp_print_value_fields(), cp_print_value_fields_rtti(), dynamic_array_type(), java_print_value_fields(), lval_func_check_any_valid(), lval_func_check_validity(), pascal_object_print_value_fields(), val_print_scalar_formatted(), valprint_check_validity(), and value_fetch_lazy().
int value_bitsize (const struct value *)
Definition at line 817 of file value.c.
References value::bitsize.
Referenced by ada_value_assign(), check_pieced_value_bits(), coerce_unspec_val_to_type(), indirect_pieced_value(), read_pieced_value(), value_assign(), value_assign_to_component(), value_fetch_lazy(), and write_pieced_value().
struct value* value_bitstring_subscript (struct type * type, struct value * bitstring, LONGEST index) [read]
int value_bytes_available (const struct value * value, int offset, int length)
Definition at line 341 of file value.c.
References gdb_assert, value::lazy, and ranges_contain().
Referenced by c_val_print(), gnuv2_baseclass_offset(), list_arg_or_local(), unpack_value_bits_as_long_1(), val_print_scalar_formatted(), valprint_check_validity(), and value_contents_copy_raw().
struct value* value_cast (struct type * type, struct value * arg2) [read]
Definition at line 354 of file valops.c.
References _, allocate_value(), language_defn::c_style_arrays, cast_into_complex(), check_typedef(), CHECK_TYPEDEF, coerce_ref(), cplus_make_method_ptr(), create_array_type(), create_range_type(), current_language, decimal_convert(), decimal_from_floating(), decimal_from_integral(), deprecated_set_value_type(), error(), extract_unsigned_integer(), gdb_assert, gdbarch_addr_bit(), gdbarch_byte_order(), get_discrete_bounds(), get_type_arch(), HOST_CHAR_BIT, LONGEST, lval_memory, not_lval, set_value_enclosing_type(), set_value_pointed_to_offset(), TYPE_ARRAY_UPPER_BOUND_IS_UNDEFINED, TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_BOOL, TYPE_CODE_CHAR, TYPE_CODE_COMPLEX, TYPE_CODE_DECFLOAT, TYPE_CODE_ENUM, TYPE_CODE_FLT, TYPE_CODE_FUNC, TYPE_CODE_INT, TYPE_CODE_MEMBERPTR, TYPE_CODE_METHODPTR, TYPE_CODE_PTR, TYPE_CODE_RANGE, TYPE_CODE_REF, TYPE_CODE_STRUCT, TYPE_CODE_UNION, TYPE_CODE_VOID, TYPE_INDEX_TYPE, TYPE_LENGTH, TYPE_NAME, TYPE_TARGET_TYPE, TYPE_VECTOR, value_address(), value_as_double(), value_as_long(), value_at_lazy(), value_cast(), value_cast_pointers(), value_cast_structs(), value_coerce_array(), value_coerce_function(), value_contents(), value_contents_writeable(), value_copy(), value_from_decfloat(), value_from_double(), value_from_longest(), VALUE_LVAL, value_ref(), value_type(), value_zero(), and warning().
Referenced by aarch64_push_dummy_call(), ada_coerce_to_simple_array_ptr(), ada_get_tsd_from_tag(), ada_promote_array_of_integrals(), ada_tag_value_at_base_address(), ada_val_print_1(), ada_value_assign(), ada_value_cast(), ada_value_ptr_subscript(), ada_value_slice(), adjust_value_for_child_access(), alpha_push_dummy_call(), binop_promote(), compute_exception(), cplus_describe_child(), desc_bounds(), evaluate_subexp_java(), evaluate_subexp_modula2(), evaluate_subexp_standard(), evaluate_subexp_with_coercion(), execute_stack_op(), gnuv2_value_rtti_type(), gnuv2_virtual_fn_field(), gnuv3_get_typeid(), gnuv3_get_virtual_fn(), gnuv3_method_ptr_to_value(), gnuv3_virtual_fn_field(), hppa64_push_dummy_call(), lm32_push_dummy_call(), m88k_store_arguments(), opencl_value_cast(), return_command(), s390_unwind_pseudo_register(), sparc32_store_arguments(), sparc64_store_arguments(), thin_data_pntr(), unop_promote(), value_arg_coerce(), value_assign(), value_assign_to_component(), value_cast(), value_dynamic_cast(), value_fn_field(), value_literal_complex(), value_reinterpret_cast(), value_vector_widen(), varobj_create(), wrap_value_cast(), and xtensa_push_dummy_call().
struct value* value_cast_pointers (struct type * , struct value * , int) [read]
Definition at line 309 of file valops.c.
References check_typedef(), coerce_ref(), deprecated_set_value_type(), gdb_assert, set_value_enclosing_type(), set_value_pointed_to_offset(), TYPE_CODE, TYPE_CODE_REF, TYPE_CODE_STRUCT, TYPE_TARGET_TYPE, value_addr(), value_cast_structs(), value_copy(), value_ind(), value_logical_not(), and value_type().
Referenced by ada_convert_actual(), evaluate_subexp_standard(), value_arg_coerce(), and value_cast().
struct value* value_coerce_array (struct value * arg1) [read]
Definition at line 1473 of file valops.c.
References _, check_typedef(), error(), lookup_pointer_type(), lval_memory, TYPE_TARGET_TYPE, value_address(), value_coerce_to_target(), value_from_pointer(), VALUE_LVAL, and value_type().
Referenced by coerce_array(), lookup_child_selector(), lookup_objc_class(), typecmp(), value_cast(), value_nsstring(), value_subscript(), and wrap_value_coerce_array().
struct value* value_coerce_function (struct value * arg1) [read]
Definition at line 1493 of file valops.c.
References _, error(), lookup_pointer_type(), lval_memory, value_address(), value_from_pointer(), VALUE_LVAL, and value_type().
Referenced by coerce_array(), value_addr(), and value_cast().
struct value* value_coerce_to_target (struct value * arg1) [read]
Definition at line 1435 of file valops.c.
References allocate_space_in_inferior(), check_typedef(), LONGEST, TYPE_LENGTH, value_at_lazy(), value_contents(), value_must_coerce_to_target(), value_type(), and write_memory().
Referenced by value_addr(), value_arg_coerce(), and value_coerce_array().
struct value* value_complement (struct value * arg1) [read]
Definition at line 1791 of file valarith.c.
References _, allocate_value(), check_typedef(), coerce_ref(), error(), get_array_bounds(), is_integral_type(), LONGEST, memcpy(), type, TYPE_CODE, TYPE_CODE_ARRAY, TYPE_LENGTH, TYPE_TARGET_TYPE, TYPE_VECTOR, value_as_long(), value_complement(), value_contents_all(), value_contents_writeable(), value_from_longest(), value_subscript(), and value_type().
Referenced by evaluate_subexp_standard(), execute_stack_op(), and value_complement().
void* value_computed_closure (const struct value * value)
Definition at line 1181 of file value.c.
References value::computed, gdb_assert, value::location, value::lval, and lval_computed.
Referenced by check_pieced_value_bits(), copy_pieced_value_closure(), entry_data_value_coerce_ref(), entry_data_value_copy_closure(), entry_data_value_free_closure(), free_pieced_value_closure(), indirect_pieced_value(), lval_func_check_any_valid(), lval_func_check_synthetic_pointer(), lval_func_check_validity(), lval_func_copy_closure(), lval_func_free_closure(), lval_func_read(), lval_func_write(), read_pieced_value(), and write_pieced_value().
struct lval_funcs* value_computed_funcs (const struct value *) [read]
Definition at line 1173 of file value.c.
References value::computed, gdb_assert, value::location, lval_computed, and value_lval_const().
Referenced by coerce_ref_if_computed(), value_assign(), value_fetch_lazy(), and value_ind().
struct value* value_concat (struct value * arg1, struct value * arg2) [read]
Definition at line 626 of file valarith.c.
References _, check_typedef(), do_cleanups(), error(), longest_to_int(), make_cleanup(), memcpy(), TYPE_CODE, TYPE_CODE_BOOL, TYPE_CODE_CHAR, TYPE_CODE_INT, TYPE_CODE_STRING, TYPE_LENGTH, TYPE_TARGET_TYPE, unpack_long(), value_as_long(), value_contents(), value_string(), value_type(), xfree(), and xmalloc().
Referenced by evaluate_subexp_standard().
const gdb_byte* value_contents (struct value *)
Definition at line 1055 of file value.c.
References require_available(), require_not_optimized_out(), and value_contents_writeable().
Referenced by aarch64_push_dummy_call(), ada_convert_actual(), ada_value_assign(), ada_value_equal(), ada_value_primitive_field(), ada_value_primitive_packed_val(), alpha_push_dummy_call(), amd64_push_arguments(), amd64_windows_adjust_args_passed_by_pointer(), amd64_windows_push_arguments(), amd64_windows_store_arg_in_reg(), arm_push_dummy_call(), avr_push_dummy_call(), c_get_string(), cast_into_complex(), coerce_ref(), coerce_unspec_val_to_type(), create_value(), cris_push_dummy_call(), dump_value_to_file(), dwarf_expr_fetch_address(), ensure_lval(), evaluate_subexp_standard(), extend_simple_arg(), frame_unwind_register_value(), frv_push_dummy_call(), gnuv3_method_ptr_to_value(), h8300_push_dummy_call(), hppa32_push_dummy_call(), hppa64_push_dummy_call(), i387_print_float_info(), ia64_push_dummy_call(), iq2000_push_dummy_call(), lm32_push_dummy_call(), lval_func_read(), lval_func_write(), m32c_push_dummy_call(), m32r_push_dummy_call(), m68hc11_push_dummy_call(), m88k_store_arguments(), mep_push_dummy_call(), mips_eabi_push_dummy_call(), mips_n32n64_push_dummy_call(), mips_o32_push_dummy_call(), mips_o64_push_dummy_call(), mn10300_push_dummy_call(), mt_push_dummy_call(), nios2_push_dummy_call(), parse_find_args(), ppc64_sysv_abi_push_dummy_call(), ppc_sysv_abi_push_dummy_call(), printf_decfloat(), push_large_arguments(), read_frame_register_unsigned(), return_command(), rs6000_lynx178_push_dummy_call(), rs6000_push_dummy_call(), s390_push_dummy_call(), score_push_dummy_call(), set_internalvar_component(), sh64_push_dummy_call(), sh_justify_value_in_reg(), sparc32_store_arguments(), sparc64_store_arguments(), spu_push_dummy_call(), tic6x_push_dummy_call(), tilegx_push_dummy_call(), to_fixed_variant_branch_type(), ui_printf(), v850_push_dummy_call(), value_args_as_decimal(), value_as_address(), value_as_double(), value_as_long(), value_as_string(), value_assign(), value_assign_to_component(), value_cast(), value_coerce_to_target(), value_concat(), value_contents_equal(), value_equal(), value_equal_contents(), value_fetch_lazy(), value_in(), value_literal_complex(), value_logical_not(), value_neg(), value_of_dwarf_reg_entry(), value_pos(), value_primitive_field(), value_strcmp(), write_pieced_value(), xstormy16_push_dummy_call(), and xtensa_push_dummy_call().
const gdb_byte* value_contents_all (struct value *)
Definition at line 951 of file value.c.
References require_available(), require_not_optimized_out(), and value_contents_for_printing().
Referenced by ada_promote_array_of_integrals(), dwarf2_evaluate_loc_desc_full(), evaluate_subexp_opencl(), execute_stack_op(), frame_register_unwind(), hppa_frame_prev_register_helper(), hppa_hpux_unwind_adjust_stub(), i386_darwin_push_dummy_call(), i386_push_dummy_call(), ia64_frame_prev_register(), m68k_push_dummy_call(), msp430_push_dummy_call(), read_pieced_value(), register_changed_p(), rl78_push_dummy_call(), rx_push_dummy_call(), value_complement(), value_neg(), value_non_lval(), value_one(), value_vector_widen(), vax_store_arguments(), and vector_binop().
gdb_byte* value_contents_all_raw (struct value *)
Definition at line 854 of file value.c.
References allocate_value_contents(), and value::contents.
Referenced by siginfo_value_read(), siginfo_value_write(), value_contents_copy_raw(), value_copy(), value_fetch_lazy(), value_non_lval(), and value_repeat().
void value_contents_copy (struct value * dst, int dst_offset, struct value * src, int src_offset, int length)
Definition at line 1019 of file value.c.
References value::lazy, require_not_optimized_out(), value_contents_copy_raw(), and value_fetch_lazy().
Referenced by read_frame_register_value(), value_array(), value_fetch_lazy(), value_slice(), and value_subscripted_rvalue().
void value_contents_copy_raw (struct value * dst, int dst_offset, struct value * src, int src_offset, int length)
Definition at line 970 of file value.c.
References gdb_assert, value::lazy, range::length, mark_value_bytes_unavailable(), max, memcpy(), min, range::offset, ULONGEST, value_bytes_available(), value_contents_all_raw(), and VEC_iterate.
Referenced by value_contents_copy(), and value_primitive_field().
int value_contents_equal (struct value * val1, struct value * val2)
Definition at line 1076 of file value.c.
References check_typedef(), memcmp(), TYPE_LENGTH, value_contents(), and value_type().
const gdb_byte* value_contents_for_printing (struct value * value)
Definition at line 936 of file value.c.
References value::contents, value::lazy, and value_fetch_lazy().
Referenced by ada_val_print_1(), ada_value_print(), c_value_print(), common_val_print(), cp_print_static_field(), default_print_one_register_info(), do_search_struct_field(), dynamic_array_type(), find_method_list(), get_register(), is_unique_ancestor(), m2_print_unbounded_array(), mips_print_register(), output_register(), pascal_object_print_static_field(), print_field_values(), print_formatted(), search_struct_method(), val_print_packed_array_elements(), value_contents_all(), value_dynamic_cast(), value_fetch_lazy(), and value_print().
const gdb_byte* value_contents_for_printing_const (const struct value * value)
Definition at line 944 of file value.c.
References value::contents, gdb_assert, and value::lazy.
Referenced by cp_print_value(), print_go_string(), and val_print_scalar_formatted().
gdb_byte* value_contents_raw (struct value *)
Definition at line 847 of file value.c.
References allocate_value_contents(), value::contents, and value::embedded_offset.
Referenced by aarch64_pseudo_read_value(), ada_convert_actual(), ada_value_assign(), ada_value_binop(), amd64_pseudo_register_read_value(), call_function_by_hand(), cast_into_complex(), coerce_unspec_val_to_type(), default_read_var_value(), do_search_struct_field(), dwarf2_evaluate_loc_desc_full(), elf_gnu_ifunc_resolver_return_stop(), evaluate_subexp_c(), evaluate_subexp_standard(), frame_unwind_got_bytes(), get_return_value(), i386_pseudo_register_read_into_value(), lval_func_read(), read_pieced_value(), regcache_cooked_read(), regcache_cooked_read_value(), scalar_binop(), sdata_make_value(), tlb_value_read(), value_assign(), value_contents_writeable(), value_cstring(), value_fetch_lazy(), value_from_contents(), value_from_decfloat(), value_from_double(), value_from_longest(), value_from_pointer(), value_from_register(), value_from_ulongest(), value_literal_complex(), value_neg(), value_of_builtin_frame_fp_reg(), value_of_builtin_frame_pc_reg(), value_of_dwarf_reg_entry(), value_pos(), and value_string().
gdb_byte* value_contents_writeable (struct value *)
Definition at line 1064 of file value.c.
References value::lazy, value_contents_raw(), and value_fetch_lazy().
Referenced by aarch64_push_dummy_call(), ada_promote_array_of_integrals(), bfin_push_dummy_call(), create_value(), dummy_frame_prev_register(), dwarf2_compute_name(), evaluate_subexp_opencl(), frame_unwind_got_address(), frame_unwind_got_constant(), lval_func_write(), make_array_descriptor(), opencl_logical_not(), set_internalvar_component(), value_assign_to_component(), value_cast(), value_complement(), value_contents(), value_neg(), value_one(), value_vector_widen(), vector_binop(), and vector_relop().
struct value* value_copy (struct value *) [read]
Definition at line 1423 of file value.c.
References allocate_value(), allocate_value_lazy(), value::bitpos, value::bitsize, value::computed, lval_funcs::copy_closure, value::embedded_offset, value::lazy, value::location, lval_computed, memcpy(), value::modifiable, value::offset, value::optimized_out, value::parent, value::pointed_to_offset, set_value_parent(), value::type, TYPE_LENGTH, value_contents_all_raw(), value_embedded_offset(), value_enclosing_type(), VALUE_FRAME_ID, value_lazy(), VALUE_LVAL, VALUE_REGNUM, and VEC_copy.
Referenced by access_value_history(), ada_coerce_to_simple_array_ptr(), ada_value_assign(), ada_value_ptr_subscript(), bpstat_copy(), do_search_struct_field(), set_internalvar(), thin_data_pntr(), value_addr(), value_assign(), value_cast(), value_cast_pointers(), value_full_object(), and value_of_internalvar().
struct value* value_cstring (char * ptr, ssize_t len, struct type * char_type) [read]
Definition at line 1678 of file valops.c.
References allocate_value(), current_language, lookup_array_range_type(), memcpy(), language_defn::string_lower_bound, TYPE_LENGTH, and value_contents_raw().
Referenced by evaluate_subexp_c(), and value_of_internalvar().
struct value* value_dynamic_cast (struct type * type, struct value * arg) [read]
Definition at line 727 of file valops.c.
References _, check_typedef(), class_types_same_p(), dynamic_cast_check_1(), dynamic_cast_check_2(), error(), is_ancestor(), is_public_ancestor(), is_unique_ancestor(), not_lval, TYPE_CODE, TYPE_CODE_CLASS, TYPE_CODE_INT, TYPE_CODE_PTR, TYPE_CODE_REF, TYPE_CODE_VOID, TYPE_TARGET_TYPE, value_addr(), value_address(), value_as_long(), value_at(), value_at_lazy(), value_cast(), value_contents_for_printing(), value_embedded_offset(), value_ind(), value_ref(), value_rtti_type(), value_type(), and value_zero().
Referenced by evaluate_subexp_standard().
int value_embedded_offset (struct value * value)
Definition at line 1149 of file value.c.
References value::embedded_offset.
Referenced by ada_val_print_1(), ada_value_print(), c_value_print(), common_val_print(), compare_value_and_voffset(), cp_print_static_field(), default_print_one_register_info(), do_search_struct_field(), dynamic_array_type(), eq_value_and_voffset(), evaluate_subexp_standard(), get_register(), gnuv3_get_typeid(), gnuv3_rtti_type(), hash_value_and_voffset(), is_unique_ancestor(), java_value_print(), list_arg_or_local(), m2_print_unbounded_array(), mips_print_register(), output_register(), pascal_object_print_static_field(), print_field_values(), print_formatted(), print_one_vtable(), val_print_packed_array_elements(), value_addr(), value_cast_structs(), value_copy(), value_dynamic_cast(), value_fetch_lazy(), value_full_object(), value_non_lval(), value_primitive_field(), value_print(), and value_subscripted_rvalue().
struct type* value_enclosing_type (struct value *) [read]
Definition at line 861 of file value.c.
References value::enclosing_type.
Referenced by bfin_push_dummy_call(), c_value_print(), coerce_ref(), cp_print_static_field(), do_search_struct_field(), gnuv3_rtti_type(), i386_darwin_push_dummy_call(), i386_push_dummy_call(), m68k_push_dummy_call(), read_pieced_value(), rl78_push_dummy_call(), set_value_enclosing_type(), tilegx_push_dummy_call(), value_actual_type(), value_addr(), value_array(), value_assign(), value_copy(), value_entirely_unavailable(), value_fetch_lazy(), value_full_object(), value_ind(), value_non_lval(), value_primitive_field(), value_repeat(), vax_store_arguments(), and xstormy16_push_dummy_call().
int value_entirely_available (struct value * value)
Definition at line 349 of file value.c.
References value::lazy, value_fetch_lazy(), and VEC_empty.
Referenced by c_value_print(), default_print_one_register_info(), frame_register_unwind(), i387_print_float_info(), output_register(), read_frame_register_unsigned(), regcache_cooked_read(), and register_changed_p().
int value_entirely_optimized_out (const struct value * value)
Definition at line 1114 of file value.c.
References value::computed, value::location, value::lval, lval_computed, and value::optimized_out.
Referenced by value_check_printable().
int value_entirely_unavailable (struct value * value)
Definition at line 362 of file value.c.
References value::lazy, range::length, range::offset, TYPE_LENGTH, value_enclosing_type(), value_fetch_lazy(), VEC_index, and VEC_length.
Referenced by list_arg_or_local().
int value_equal (struct value * arg1, struct value * arg2)
Definition at line 1543 of file valarith.c.
References _, check_typedef(), coerce_array(), decimal_compare(), error(), is_integral_type(), len, longest_to_int(), TYPE_CODE, TYPE_CODE_DECFLOAT, TYPE_CODE_FLT, TYPE_CODE_PTR, TYPE_CODE_STRING, TYPE_LENGTH, value_args_as_decimal(), value_as_address(), value_as_double(), value_as_long(), value_binop(), value_contents(), value_strcmp(), and value_type().
Referenced by ada_value_equal(), evaluate_subexp_standard(), execute_stack_op(), scalar_relop(), value_vector_widen(), and wrap_value_equal().
int value_equal_contents (struct value * arg1, struct value * arg2)
Definition at line 1625 of file valarith.c.
References check_typedef(), memcmp(), TYPE_CODE, TYPE_LENGTH, value_contents(), and value_type().
Referenced by watchpoint_check().
int value_fetch_lazy (struct value * val)
Definition at line 3452 of file value.c.
References _, allocate_value_contents(), check_typedef(), fprintf_unfiltered(), frame_debug, frame_find_by_id(), frame_relative_level(), gdb_assert, gdb_stdlog, gdbarch_byte_order(), gdbarch_convert_register_p(), get_frame_arch(), get_frame_register_value(), get_type_arch(), internal_error(), LONGEST, lval_computed, lval_memory, lval_register, mark_value_bytes_unavailable(), offset, value::optimized_out, paddress(), value::parent, read(), lval_funcs::read, read_value_memory(), register_size(), regnum, set_value_lazy(), set_value_optimized_out(), store_signed_integer(), TYPE_LENGTH, unpack_value_bits_as_long(), user_reg_map_regnum_to_name(), value_address(), value_bitpos(), value_bits_valid(), value_bitsize(), value_computed_funcs(), value_contents(), value_contents_all_raw(), value_contents_copy(), value_contents_for_printing(), value_contents_raw(), value_embedded_offset(), value_enclosing_type(), value_fetch_lazy(), VALUE_FRAME_ID, value_free_to_mark(), value_lazy(), VALUE_LVAL, value_mark(), value_offset(), value_optimized_out(), value_parent(), VALUE_REGNUM, value_stack(), and value_type().
Referenced by fetch_subexp_value(), get_value_at(), gnuv2_virtual_fn_field(), install_new_value(), java_value_print(), read_frame_arg(), record_latest_value(), return_command(), set_internalvar(), value_contents_copy(), value_contents_for_printing(), value_contents_writeable(), value_entirely_available(), value_entirely_unavailable(), value_fetch_lazy(), value_of_internalvar(), value_of_register(), value_optimized_out(), value_primitive_field(), and wrap_value_fetch_lazy().
struct value* value_field (struct value * arg1, int fieldno) [read]
Definition at line 2791 of file value.c.
References value_primitive_field(), and value_type().
Referenced by ada_varobj_struct_elt(), compute_vtable_size(), gnuv2_value_rtti_type(), gnuv2_virtual_fn_field(), gnuv3_baseclass_offset(), gnuv3_get_typeid(), gnuv3_get_virtual_fn(), gnuv3_rtti_type(), print_one_vtable(), ptid_from_atcb_common(), read_atcb(), read_fat_string_value(), and read_known_tasks_list().
struct value* value_field_bitfield (struct type * type, int fieldno, const gdb_byte * valaddr, int embedded_offset, const struct value * val) [read]
Definition at line 3012 of file value.c.
References allocate_value(), LONGEST, mark_value_bytes_unavailable(), TYPE_FIELD_TYPE, TYPE_LENGTH, unpack_value_field_as_long(), and value_from_longest().
Referenced by cp_print_value_fields(), java_print_value_fields(), and pascal_object_print_value_fields().
struct value* value_fn_field (struct value ** arg1p, struct fn_field * f, int j, struct type * type, int offset) [read]
Definition at line 2804 of file value.c.
References allocate_value(), BLOCK_START, current_target, gdb_assert, gdbarch_convert_from_func_ptr_addr(), get_objfile_arch(), lookup_bound_minimal_symbol(), lookup_pointer_type(), lookup_symbol(), memset(), bound_minimal_symbol::minsym, bound_minimal_symbol::objfile, set_value_address(), SYMBOL_BLOCK_VALUE, SYMBOL_VALUE_ADDRESS, TYPE_FN_FIELD_PHYSNAME, TYPE_FN_FIELD_TYPE, value_addr(), value_cast(), value_ind(), value_type(), and VAR_DOMAIN.
Referenced by find_overload_match(), and search_struct_method().
void value_free (struct value * val)
Definition at line 1276 of file value.c.
References value::computed, value::contents, lval_funcs::free_closure, gdb_assert, value::location, lval_computed, value::parent, value::reference_count, value_free(), VALUE_LVAL, VEC_free, and xfree().
Referenced by address_from_register(), bpstat_clear_actions(), bpstat_free(), breakpoint_init_inferior(), clear_internalvar(), do_examine(), do_value_free(), dtor_watchpoint(), dwarf2_compute_name(), entry_data_value_free_closure(), frame_register_unwind(), free_all_values(), free_pieced_value_closure(), free_value_chain(), free_variable(), install_new_value(), invalidate_bp_value_on_memory_change(), lval_func_free_closure(), m68hc11_frame_prev_register(), m88k_frame_prev_register(), mep_frame_prev_register(), set_value_parent(), update_watchpoint(), value_free(), and value_free_to_mark().
void value_free_to_mark (struct value * mark)
Definition at line 1307 of file value.c.
References value::next, value::released, and value_free().
Referenced by ada_template_to_fixed_record_type_1(), ada_val_print_1(), assign_component(), bpstat_check_breakpoint_conditions(), breakpoint_cond_eval(), do_value_free_to_mark(), execute_control_command(), info_port_rights(), java_value_print(), lval_func_write(), regcache_cooked_read(), should_stop_exception(), to_record_with_fixed_variant_part(), val_print_packed_array_elements(), value_fetch_lazy(), vector_binop(), watch_command_1(), and watchpoint_check().
struct value* value_from_contents (struct type * , const gdb_byte *) [read]
Definition at line 3217 of file value.c.
References allocate_value(), memcpy(), TYPE_LENGTH, and value_contents_raw().
Referenced by execute_stack_op(), indirect_pieced_value(), and value_from_contents_and_address().
struct value* value_from_contents_and_address (struct type * , const gdb_byte * , CORE_ADDR) [read]
Definition at line 3198 of file value.c.
References allocate_value_lazy(), lval_memory, set_value_address(), value_from_contents(), and VALUE_LVAL.
Referenced by ada_tag_value_at_base_address(), ada_template_to_fixed_record_type_1(), ada_to_fixed_type_1(), ada_to_fixed_value_create(), ada_val_print_1(), ada_which_variant_applies(), amd64_windows_adjust_args_passed_by_pointer(), cp_print_value(), cp_print_value_fields_rtti(), execute_stack_op(), get_value_at(), read_atcb(), read_known_tasks_list(), search_struct_method(), to_record_with_fixed_variant_part(), and value_tag_from_contents_and_address().
struct value* value_from_decfloat (struct type * type, const gdb_byte * decbytes) [read]
Definition at line 3244 of file value.c.
References allocate_value(), memcpy(), TYPE_LENGTH, and value_contents_raw().
Referenced by evaluate_subexp_standard(), printf_decfloat(), scalar_binop(), value_cast(), value_one(), and value_pos().
struct value* value_from_double (struct type * type, DOUBLEST num) [read]
Definition at line 3227 of file value.c.
References _, allocate_value(), check_typedef(), code, error(), store_typed_floating(), TYPE_CODE, TYPE_CODE_FLT, and value_contents_raw().
Referenced by cast_from_fixed(), evaluate_subexp_standard(), print_subexp_standard(), value_cast(), value_neg(), value_one(), and value_pos().
struct value* value_from_history_ref (char * , char **) [read]
Definition at line 3257 of file value.c.
References access_value_history(), and len.
Referenced by get_number_trailer().
struct value* value_from_longest (struct type * type, LONGEST num) [read]
Definition at line 3159 of file value.c.
References allocate_value(), pack_long(), and value_contents_raw().
Referenced by ada_varobj_simple_array_elt(), assign_component(), call_target_sbrk(), cast_to_fixed(), checkpoint_command(), compute_probe_arg(), const_expr(), const_var_ref(), desc_bounds(), dwarf2_compute_name(), evaluate_subexp_c(), evaluate_subexp_for_sizeof(), evaluate_subexp_java(), evaluate_subexp_modula2(), evaluate_subexp_opencl(), evaluate_subexp_standard(), inferior_call_waitpid(), isvoid_internal_fn(), maybe_print_array_index(), opencl_logical_not(), opencl_relop(), print_scalar_formatted(), print_subexp_standard(), s390_unwind_pseudo_register(), thin_data_pntr(), thread_id_make_value(), value_allocate_space_in_inferior(), value_assign(), value_cast(), value_complement(), value_field_bitfield(), value_neg(), value_nsstring(), value_of_internalvar(), value_one(), value_pos(), value_pos_atr(), value_val_atr(), and value_x_unop().
struct value* value_from_pointer (struct type * type, CORE_ADDR addr) [read]
Definition at line 3184 of file value.c.
References allocate_value(), check_typedef(), store_typed_address(), and value_contents_raw().
Referenced by aarch64_push_dummy_call(), ada_val_print_1(), address_of_variable(), alpha_push_dummy_call(), c_value_print(), call_function_by_hand(), const_var_ref(), evaluate_subexp_standard(), find_command(), find_function_in_inferior(), flush_ea_cache(), gnuv3_method_ptr_to_value(), inferior_call_waitpid(), s390_unwind_pseudo_register(), set_next_address(), sparc32_store_arguments(), sparc64_store_arguments(), value_addr(), value_coerce_array(), value_coerce_function(), value_ptradd(), and x_command().
struct value* value_from_register (struct type * type, int regnum, struct frame_info * frame) [read]
Definition at line 702 of file findvar.c.
References allocate_value(), check_typedef(), gdbarch_convert_register_p(), gdbarch_register_to_value(), gdbarch_value_from_register(), get_frame_arch(), get_frame_id(), lval_register, mark_value_bytes_unavailable(), read_frame_register_value(), regnum, set_value_optimized_out(), TYPE_LENGTH, value_contents_raw(), VALUE_FRAME_ID, VALUE_LVAL, and VALUE_REGNUM.
Referenced by address_from_register(), default_read_var_value(), dwarf2_evaluate_loc_desc_full(), and set_gdbarch_value_from_register().
struct value* value_from_ulongest (struct type * type, ULONGEST num) [read]
Definition at line 3171 of file value.c.
References allocate_value(), pack_unsigned_long(), and value_contents_raw().
Referenced by dwarf_expr_push_address(), and execute_stack_op().
struct value* value_full_object (struct value * , struct type * , int , int , int) [read]
Definition at line 3420 of file valops.c.
References _, deprecated_set_value_type(), lval_memory, set_value_embedded_offset(), set_value_enclosing_type(), TYPE_LENGTH, TYPE_NAME, value_address(), value_at_lazy(), value_copy(), value_embedded_offset(), value_enclosing_type(), VALUE_LVAL, value_rtti_type(), value_type(), and warning().
Referenced by c_value_print(), gnuv3_print_vtable(), readjust_indirect_value_type(), and value_cast_structs().
int value_in (struct value * element, struct value * set)
Definition at line 1852 of file valarith.c.
References _, check_typedef(), error(), TYPE_CODE, TYPE_CODE_BOOL, TYPE_CODE_CHAR, TYPE_CODE_ENUM, TYPE_CODE_INT, TYPE_CODE_RANGE, TYPE_CODE_SET, TYPE_TARGET_TYPE, value_as_long(), value_bit_index(), value_contents(), and value_type().
Referenced by evaluate_subexp_standard().
void value_incref (struct value * val)
Definition at line 1266 of file value.c.
References value::reference_count.
Referenced by allocate_lval_closure(), allocate_piece_closure(), dwarf2_evaluate_loc_desc_full(), entry_data_value_coerce_ref(), entry_data_value_copy_closure(), install_new_value(), release_value_or_incref(), and set_value_parent().
struct value* value_ind (struct value * arg1) [read]
Definition at line 1570 of file valops.c.
References _, check_typedef(), coerce_array(), error(), find_function_addr(), lval_funcs::indirect, lval_computed, readjust_indirect_value_type(), TYPE_CODE, TYPE_CODE_FUNC, TYPE_CODE_METHOD, TYPE_CODE_PTR, TYPE_TARGET_TYPE, value_as_address(), value_at_lazy(), value_computed_funcs(), value_enclosing_type(), VALUE_LVAL, value_pointed_to_offset(), and value_type().
Referenced by ada_coerce_to_simple_array(), ada_get_tsd_from_tag(), ada_tag_value_at_base_address(), ada_value_ind(), ada_value_ptr_subscript(), ada_value_struct_elt(), adjust_value_for_child_access(), c_describe_child(), c_value_print(), compute_exception(), decode_constrained_packed_array(), evaluate_subexp_java(), evaluate_subexp_modula2(), evaluate_subexp_standard(), find_overload_match(), gnuv2_virtual_fn_field(), gnuv3_get_typeid(), gnuv3_method_ptr_to_value(), gnuv3_print_vtable(), info_mach_region_command(), java_link_class_type(), java_value_print(), read_fat_string_value(), type_from_class(), value_cast_pointers(), value_dynamic_cast(), value_find_oload_method_list(), value_fn_field(), value_reinterpret_cast(), value_rtti_indirect_type(), value_struct_elt(), value_subscript(), value_user_defined_cpp_op(), and wrap_value_ind().
int value_initialized (struct value *)
Definition at line 3432 of file value.c.
References value::initialized.
Referenced by c_value_print().
char* value_internal_function_name (struct value *)
Definition at line 2141 of file value.c.
References gdb_assert, get_internalvar_function(), lval_internalvar, internal_function::name, VALUE_INTERNALVAR, and VALUE_LVAL.
Referenced by value_check_printable().
int value_lazy (struct value *)
Definition at line 1031 of file value.c.
References value::lazy.
Referenced by ada_value_primitive_packed_val(), address_of_variable(), c_value_of_variable(), can_use_hardware_watchpoint(), coerce_unspec_val_to_type(), fetch_subexp_value(), frame_unwind_register_value(), gnuv2_virtual_fn_field(), install_new_value(), num_memory_accesses(), read_frame_arg(), record_latest_value(), return_command(), set_internalvar(), update_watchpoint(), value_copy(), value_fetch_lazy(), value_of_internalvar(), value_primitive_field(), value_slice(), value_subscripted_rvalue(), varobj_set_display_format(), varobj_set_value(), and x_command().
int value_less (struct value * arg1, struct value * arg2)
Definition at line 1642 of file valarith.c.
References _, check_typedef(), coerce_array(), decimal_compare(), error(), is_integral_type(), longest_to_int(), TYPE_CODE, TYPE_CODE_DECFLOAT, TYPE_CODE_FLT, TYPE_CODE_PTR, TYPE_CODE_STRING, value_args_as_decimal(), value_as_address(), value_as_double(), value_as_long(), value_binop(), value_strcmp(), and value_type().
Referenced by evaluate_subexp_standard(), execute_stack_op(), and scalar_relop().
struct value* value_literal_complex (struct value * , struct value * , struct type *) [read]
Definition at line 3593 of file valops.c.
References allocate_value(), memcpy(), TYPE_LENGTH, TYPE_TARGET_TYPE, value_cast(), value_contents(), and value_contents_raw().
Referenced by cast_into_complex(), and evaluate_subexp_standard().
int value_logical_not (struct value * arg1)
Definition at line 1482 of file valarith.c.
References check_typedef(), coerce_array(), decimal_is_zero(), gdbarch_byte_order(), get_type_arch(), len, p, TYPE_CODE, TYPE_CODE_DECFLOAT, TYPE_CODE_FLT, TYPE_LENGTH, value_as_double(), value_contents(), and value_type().
Referenced by evaluate_subexp_opencl(), evaluate_subexp_standard(), java_value_print(), opencl_logical_not(), scalar_relop(), type_from_class(), value_allocate_space_in_inferior(), value_cast_pointers(), and value_true().
enum lval_type value_lval_const (const struct value * value)
Definition at line 1195 of file value.c.
References value::lval.
Referenced by coerce_ref_if_computed(), gnuv3_get_typeid(), val_print_optimized_out(), and value_computed_funcs().
struct value* value_mark (void) [read]
Definition at line 1257 of file value.c.
References all_values.
Referenced by ada_template_to_fixed_record_type_1(), ada_val_print_1(), assign_component(), bpstat_check_breakpoint_conditions(), breakpoint_cond_eval(), dwarf2_evaluate_loc_desc_full(), dwarf2_loc_desc_needs_frame(), execute_control_command(), execute_stack_op(), fetch_subexp_value(), info_port_rights(), java_value_print(), lval_func_write(), prepare_execute_command(), regcache_cooked_read(), should_stop_exception(), to_record_with_fixed_variant_part(), val_print_packed_array_elements(), value_fetch_lazy(), vector_binop(), watch_command_1(), and watchpoint_check().
int value_must_coerce_to_target (struct value * arg1)
Definition at line 1408 of file valops.c.
References check_typedef(), lval_internalvar, not_lval, TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_STRING, TYPE_VECTOR, VALUE_LVAL, and value_type().
Referenced by value_assign(), and value_coerce_to_target().
struct value* value_neg (struct value * arg1) [read]
Definition at line 1736 of file valarith.c.
References _, allocate_value(), check_typedef(), coerce_ref(), error(), gdbarch_byte_order(), get_array_bounds(), get_type_arch(), is_integral_type(), len, LONGEST, memcpy(), type, TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_DECFLOAT, TYPE_CODE_FLT, TYPE_LENGTH, TYPE_TARGET_TYPE, TYPE_VECTOR, value_as_double(), value_as_long(), value_contents(), value_contents_all(), value_contents_raw(), value_contents_writeable(), value_from_double(), value_from_longest(), value_neg(), value_subscript(), and value_type().
Referenced by const_expr(), evaluate_subexp_standard(), execute_stack_op(), and value_neg().
struct value* value_next (struct value *) [read]
Definition at line 778 of file value.c.
References value::next.
Referenced by can_use_hardware_watchpoint(), free_value_chain(), num_memory_accesses(), and update_watchpoint().
struct value* value_non_lval (struct value *) [read]
Definition at line 1466 of file value.c.
References allocate_value(), memcpy(), not_lval, set_value_embedded_offset(), set_value_pointed_to_offset(), value::type, TYPE_LENGTH, value_contents_all(), value_contents_all_raw(), value_embedded_offset(), value_enclosing_type(), VALUE_LVAL, and value_pointed_to_offset().
Referenced by evaluate_subexp_standard().
struct value* value_of_internalvar (struct gdbarch * gdbarch, struct internalvar * var) [read]
Definition at line 1862 of file value.c.
References _, allocate_value(), internalvar::internalvar_data::data, find_trace_state_variable(), internalvar::internalvar_data::functions, internalvar::internalvar_data::integer, internal_error(), internalvar::kind, value::lval, lval_computed, lval_internalvar, internalvar_funcs::make_value, internalvar::internalvar_data::make_value, internalvar::name, trace_state_variable::number, internalvar::internalvar_data::string, target_get_trace_state_variable_value, internalvar::internalvar_data::type, internalvar::u, internalvar::internalvar_data::val, trace_state_variable::value, internalvar::internalvar_data::value, value_copy(), value_cstring(), value_fetch_lazy(), value_from_longest(), VALUE_INTERNALVAR, trace_state_variable::value_known, value_lazy(), and VALUE_LVAL.
Referenced by evaluate_subexp_standard(), show_convenience(), and value_assign().
struct value* value_of_register (int regnum, struct frame_info * frame) [read]
Definition at line 262 of file findvar.c.
References gdbarch_num_pseudo_regs(), gdbarch_num_regs(), get_frame_arch(), value_fetch_lazy(), value_of_register_lazy(), and value_of_user_reg().
Referenced by default_print_registers_info(), evaluate_subexp_standard(), output_register(), value_of_aarch64_user_reg(), value_of_arm_user_reg(), value_of_builtin_frame_fp_reg(), value_of_builtin_frame_pc_reg(), value_of_builtin_frame_ps_reg(), value_of_builtin_frame_sp_reg(), and value_of_mips_user_reg().
struct value* value_of_register_lazy (struct frame_info * frame, int regnum) [read]
Definition at line 283 of file findvar.c.
References allocate_value_lazy(), frame_id_p(), gdb_assert, gdbarch_num_pseudo_regs(), gdbarch_num_regs(), get_frame_arch(), get_frame_id(), lval_register, register_type(), regnum, VALUE_FRAME_ID, VALUE_LVAL, and VALUE_REGNUM.
Referenced by frame_unwind_got_register(), and value_of_register().
struct value* value_of_this (const struct language_defn * lang) [read]
Definition at line 3490 of file valops.c.
References _, error(), get_frame_block(), get_selected_frame(), language_defn::la_name_of_this, lookup_language_this(), and read_var_value().
Referenced by evaluate_subexp_standard(), and value_of_this_silent().
struct value* value_of_this_silent (const struct language_defn * lang) [read]
Definition at line 3515 of file valops.c.
References RETURN_MASK_ERROR, TRY_CATCH, and value_of_this().
struct value* value_of_variable (struct symbol * var, const struct block * b) [read]
Definition at line 1330 of file valops.c.
References _, BLOCK_FUNCTION, block_inlined_p(), block_innermost_frame(), error(), get_selected_frame(), read_var_value(), SYMBOL_PRINT_NAME, and symbol_read_needs_frame().
Referenced by address_of_variable(), evaluate_subexp_standard(), find_function_in_inferior(), get_var_value(), info_common_command_for_block(), typy_template_argument(), value_static_field(), and value_user_defined_cpp_op().
int value_offset (const struct value *)
Definition at line 795 of file value.c.
References value::offset.
Referenced by check_pieced_value_bits(), find_method_list(), gnuv2_virtual_fn_field(), indirect_pieced_value(), java_value_print(), lval_func_read(), lval_func_write(), read_frame_register_value(), read_pieced_value(), siginfo_value_read(), siginfo_value_write(), value_assign(), value_fetch_lazy(), value_primitive_field(), value_slice(), value_subscripted_rvalue(), and write_pieced_value().
struct value* value_one (struct type * type) [read]
Definition at line 855 of file valops.c.
References _, allocate_value(), check_typedef(), decimal_from_string(), error(), gdb_assert, gdbarch_byte_order(), get_array_bounds(), get_type_arch(), is_integral_type(), LONGEST, memcpy(), not_lval, TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_DECFLOAT, TYPE_CODE_FLT, TYPE_LENGTH, TYPE_TARGET_TYPE, TYPE_VECTOR, value_contents_all(), value_contents_writeable(), value_from_decfloat(), value_from_double(), value_from_longest(), VALUE_LVAL, and value_one().
Referenced by evaluate_subexp_standard(), and value_one().
int value_optimized_out (struct value * value)
Definition at line 1091 of file value.c.
References value::lazy, value::optimized_out, and value_fetch_lazy().
Referenced by address_from_register(), default_print_one_register_info(), dwarf2_evaluate_loc_desc_full(), frame_register_unwind(), frame_unwind_register_value(), get_register(), insert_exception_resume_breakpoint(), mips_print_register(), read_frame_arg(), read_frame_register_unsigned(), read_frame_register_value(), register_changed_p(), s390_unwind_pseudo_register(), and value_fetch_lazy().
int value_optimized_out_const (const struct value * value)
Definition at line 1102 of file value.c.
References value::optimized_out.
Referenced by coerce_unspec_val_to_type().
struct value* value_parent (struct value *) [read]
Definition at line 828 of file value.c.
References value::parent.
Referenced by value_assign(), and value_fetch_lazy().
int value_pointed_to_offset (struct value * value)
Definition at line 1161 of file value.c.
References value::pointed_to_offset.
Referenced by readjust_indirect_value_type(), value_assign(), value_ind(), and value_non_lval().
struct value* value_pos (struct value * arg1) [read]
Definition at line 1705 of file valarith.c.
References _, allocate_value(), check_typedef(), coerce_ref(), error(), is_integral_type(), memcpy(), type, TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_DECFLOAT, TYPE_CODE_FLT, TYPE_LENGTH, TYPE_VECTOR, value_as_double(), value_as_long(), value_contents(), value_contents_raw(), value_from_decfloat(), value_from_double(), value_from_longest(), and value_type().
Referenced by evaluate_subexp_standard().
struct value* value_primitive_field (struct value * arg1, int offset, int fieldno, struct type * arg_type) [read]
Definition at line 2661 of file value.c.
References allocate_optimized_out_value(), allocate_value(), allocate_value_lazy(), baseclass_offset(), BASETYPE_VIA_VIRTUAL, value::bitpos, value::bitsize, check_typedef(), CHECK_TYPEDEF, value::embedded_offset, LONGEST, lval_register, value::offset, value::optimized_out, set_value_component_location(), set_value_parent(), type, value::type, TYPE_FIELD_BITPOS, TYPE_FIELD_BITSIZE, TYPE_FIELD_TYPE, TYPE_LENGTH, TYPE_N_BASECLASSES, value_address(), value_contents(), value_contents_copy_raw(), value_embedded_offset(), value_enclosing_type(), value_fetch_lazy(), VALUE_FRAME_ID, value_lazy(), VALUE_LVAL, value_offset(), and VALUE_REGNUM.
Referenced by aarch64_push_dummy_call(), ada_value_primitive_field(), do_search_struct_field(), gnuv2_virtual_fn_field(), value_field(), and value_struct_element_index().
void value_print (struct value * val, struct ui_file * stream, const struct value_print_options * options)
Definition at line 856 of file valprint.c.
References apply_val_pretty_printer(), current_language, LA_VALUE_PRINT, value_print_options::raw, value_address(), value_check_printable(), value_contents_for_printing(), value_embedded_offset(), and value_type().
Referenced by dwarf2_compute_name(), info_common_command_for_block(), print_formatted(), print_return_value(), print_scalar_formatted(), print_subexp_standard(), show_convenience(), show_values(), and watchpoint_value_print().
void value_print_array_elements (struct value * val, struct ui_file * stream, int format, enum val_prettyformat pretty)
struct value* value_ptradd (struct value * arg1, LONGEST arg2) [read]
Definition at line 86 of file valarith.c.
References check_typedef(), coerce_array(), find_size_for_pointer_math(), LONGEST, lval_internalvar, set_value_component_location(), value_as_address(), value_from_pointer(), VALUE_LVAL, and value_type().
Referenced by ada_get_tsd_from_tag(), ada_tag_value_at_base_address(), ada_value_ptr_subscript(), evaluate_subexp_modula2(), evaluate_subexp_standard(), gnuv2_virtual_fn_field(), gnuv3_method_ptr_to_value(), and value_subscript().
LONGEST value_ptrdiff (struct value * arg1, struct value * arg2)
Definition at line 107 of file valarith.c.
References _, check_typedef(), coerce_array(), error(), gdb_assert, LONGEST, TYPE_CODE, TYPE_CODE_PTR, TYPE_LENGTH, TYPE_TARGET_TYPE, value_as_long(), value_type(), and warning().
Referenced by evaluate_subexp_standard().
CORE_ADDR value_raw_address (struct value *)
Definition at line 1213 of file value.c.
References value::address, value::location, value::lval, lval_internalvar, and lval_internalvar_component.
Referenced by java_value_print().
struct value* value_ref (struct value * arg1) [read]
Definition at line 1553 of file valops.c.
References check_typedef(), deprecated_set_value_type(), lookup_reference_type(), TYPE_CODE, TYPE_CODE_REF, value_addr(), and value_type().
Referenced by c_value_print(), typecmp(), value_arg_coerce(), value_cast(), value_dynamic_cast(), and value_reinterpret_cast().
struct value* value_reinterpret_cast (struct type * type, struct value * arg) [read]
Definition at line 582 of file valops.c.
References _, check_typedef(), coerce_array(), error(), lookup_pointer_type(), type, TYPE_CODE, TYPE_CODE_INT, TYPE_CODE_MEMBERPTR, TYPE_CODE_METHODPTR, TYPE_CODE_PTR, TYPE_CODE_REF, TYPE_TARGET_TYPE, value_addr(), value_cast(), value_ind(), value_ref(), and value_type().
Referenced by evaluate_subexp_standard().
struct value* value_release_to_mark (struct value * mark) [read]
Definition at line 1399 of file value.c.
References value::next, and value::released.
Referenced by fetch_subexp_value().
struct value* value_repeat (struct value * arg1, int count) [read]
Definition at line 1308 of file valops.c.
References _, allocate_repeat_value(), error(), lval_memory, read_value_memory(), set_value_address(), TYPE_LENGTH, value_address(), value_contents_all_raw(), value_enclosing_type(), VALUE_LVAL, and value_stack().
Referenced by evaluate_subexp_standard().
struct type* value_rtti_indirect_type (struct value * , int * , int * , int *) [read]
Definition at line 3371 of file valops.c.
References _, check_typedef(), coerce_ref(), internal_error(), lookup_pointer_type(), lookup_reference_type(), make_cv_type(), type, TYPE_CODE, TYPE_CODE_PTR, TYPE_CODE_REF, TYPE_CONST, TYPE_VOLATILE, value_ind(), value_rtti_type(), and value_type().
Referenced by c_value_print(), evaluate_subexp_standard(), value_actual_type(), and whatis_exp().
struct value* value_slice (struct value * , int , int) [read]
Definition at line 3533 of file valops.c.
References _, allocate_value(), allocate_value_lazy(), check_typedef(), create_array_type(), create_range_type(), error(), get_discrete_bounds(), LONGEST, lval_memory, set_value_component_location(), set_value_offset(), TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_STRING, TYPE_INDEX_TYPE, TYPE_LENGTH, TYPE_TARGET_TYPE, value_contents_copy(), VALUE_FRAME_ID, value_lazy(), VALUE_LVAL, value_offset(), and value_type().
Referenced by ada_value_slice(), evaluate_subexp_standard(), value_f90_subarray(), and wrap_value_slice().
int value_stack (struct value *)
Definition at line 1043 of file value.c.
References value::stack.
Referenced by value_fetch_lazy(), and value_repeat().
struct value* value_static_field (struct type * type, int fieldno) [read]
Definition at line 2597 of file value.c.
References FIELD_LOC_KIND_PHYSADDR, FIELD_LOC_KIND_PHYSNAME, gdb_assert_not_reached, lookup_minimal_symbol(), lookup_symbol(), SYMBOL_VALUE_ADDRESS, TYPE_FIELD_LOC_KIND, TYPE_FIELD_STATIC_PHYSADDR, TYPE_FIELD_STATIC_PHYSNAME, TYPE_FIELD_TYPE, value_at_lazy(), value_of_variable(), and VAR_DOMAIN.
Referenced by cp_print_value_fields(), do_search_struct_field(), java_print_value_fields(), and value_struct_element_index().
struct value* value_string (char * ptr, ssize_t len, struct type * char_type) [read]
Definition at line 1701 of file valops.c.
References allocate_value(), current_language, lookup_string_range_type(), memcpy(), language_defn::string_lower_bound, TYPE_LENGTH, and value_contents_raw().
Referenced by evaluate_subexp_standard(), lookup_child_selector(), lookup_objc_class(), value_concat(), and value_nsstring().
struct value* value_struct_elt (struct value ** argp, struct value ** args, const char * name, int * static_memfuncp, const char * err) [read]
Definition at line 2173 of file valops.c.
References _, check_typedef(), coerce_array(), error(), NOT_FOUND_ERROR, search_struct_field(), search_struct_method(), throw_error(), TYPE_CODE, TYPE_CODE_FUNC, TYPE_CODE_PTR, TYPE_CODE_REF, TYPE_CODE_STRUCT, TYPE_CODE_UNION, TYPE_NFN_FIELDS, value_ind(), and value_type().
Referenced by desc_bounds(), desc_data(), desc_one_bound(), evaluate_subexp_java(), evaluate_subexp_modula2(), evaluate_subexp_opencl(), evaluate_subexp_standard(), get_java_utf8_name(), java_class_from_object(), java_class_is_primitive(), java_link_class_type(), java_value_print(), type_from_class(), value_user_defined_op(), and wrap_value_struct_elt().
struct value* value_subscript (struct value * array, LONGEST index) [read]
Definition at line 148 of file valarith.c.
References _, language_defn::c_style_arrays, check_typedef(), coerce_ref(), current_language, error(), get_discrete_bounds(), LONGEST, lval_memory, TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_STRING, TYPE_INDEX_TYPE, value_coerce_array(), value_ind(), VALUE_LVAL, value_ptradd(), value_subscripted_rvalue(), value_type(), and warning().
Referenced by ada_promote_array_of_integrals(), ada_value_subscript(), c_describe_child(), create_value(), evaluate_subexp_java(), evaluate_subexp_modula2(), evaluate_subexp_opencl(), evaluate_subexp_standard(), gnuv2_virtual_fn_field(), gnuv3_baseclass_offset(), gnuv3_get_virtual_fn(), lval_func_write(), opencl_logical_not(), print_one_vtable(), read_atcb(), value_complement(), value_neg(), vector_binop(), and vector_relop().
struct value* value_subscripted_rvalue (struct value * array, LONGEST index, int lowerbound) [read]
Definition at line 193 of file valarith.c.
References _, allocate_value(), allocate_value_lazy(), check_typedef(), error(), longest_to_int(), lval_memory, set_value_component_location(), set_value_offset(), TYPE_ARRAY_UPPER_BOUND_IS_UNDEFINED, TYPE_LENGTH, TYPE_TARGET_TYPE, value_contents_copy(), value_embedded_offset(), VALUE_FRAME_ID, value_lazy(), VALUE_LVAL, value_offset(), VALUE_REGNUM, and value_type().
Referenced by evaluate_subexp_standard(), and value_subscript().
struct type* value_type (const struct value *) [read]
Definition at line 784 of file value.c.
References value::type.
Referenced by aarch64_pseudo_read_value(), aarch64_push_dummy_call(), ada_args_match(), ada_array_bound(), ada_array_length(), ada_coerce_ref(), ada_coerce_to_simple_array(), ada_coerce_to_simple_array_ptr(), ada_convert_actual(), ada_get_decoded_value(), ada_promote_array_of_integrals(), ada_tag_name(), ada_tag_type(), ada_tag_value_at_base_address(), ada_to_fixed_value(), ada_type_of_array(), ada_val_print_1(), ada_value_assign(), ada_value_binop(), ada_value_cast(), ada_value_equal(), ada_value_ind(), ada_value_is_changeable_p(), ada_value_print(), ada_value_slice(), ada_value_struct_elt(), ada_value_subscript(), ada_varobj_decode_var(), ada_varobj_ind(), ada_varobj_simple_array_elt(), ada_varobj_struct_elt(), aggregate_assign_from_choices(), alpha_push_dummy_call(), amd64_pseudo_register_read_value(), amd64_push_arguments(), amd64_windows_adjust_args_passed_by_pointer(), amd64_windows_push_arguments(), amd64_windows_store_arg_in_reg(), arm_push_dummy_call(), arm_return_value(), assign_component(), avr_push_dummy_call(), bfin_push_dummy_call(), binop_promote(), binop_user_defined_p(), bpfinishpy_pre_stop_hook(), c_get_string(), c_value_print(), call_function_by_hand(), can_use_hardware_watchpoint(), cast_from_fixed(), cast_into_complex(), cast_to_fixed(), check_condition(), check_pieced_value_invalid(), coerce_array(), coerce_for_assign(), coerce_ref(), coerce_ref_if_computed(), coerce_unspec_val_to_type(), common_val_print(), compute_vtable_size(), create_value(), cris_push_dummy_call(), decimal_from_integral(), decode_constrained_packed_array(), default_print_one_register_info(), desc_bounds(), desc_data(), do_search_struct_field(), dump_value_to_file(), dwarf2_evaluate_loc_desc_full(), dwarf_expr_fetch_address(), elf_gnu_ifunc_resolver_return_stop(), ensure_lval(), entry_data_value_coerce_ref(), evaluate_subexp_for_sizeof(), evaluate_subexp_java(), evaluate_subexp_modula2(), evaluate_subexp_opencl(), evaluate_subexp_standard(), execute_stack_op(), extend_simple_arg(), find_function_addr(), find_oload_champ_namespace_loop(), find_overload_match(), finish_command_continuation(), frame_register_unwind(), frv_push_dummy_call(), gen_expr(), gen_repeat(), get_internalvar_integer(), get_java_utf8_name(), get_number_trailer(), get_value_type(), gnuv2_value_rtti_type(), gnuv2_virtual_fn_field(), gnuv3_get_type_from_type_info(), gnuv3_get_typeid(), gnuv3_get_typename_from_type_info(), gnuv3_get_virtual_fn(), gnuv3_method_ptr_to_value(), gnuv3_print_vtable(), gnuv3_rtti_type(), gnuv3_virtual_fn_field(), h8300_push_dummy_call(), hppa32_push_dummy_call(), hppa64_push_dummy_call(), i386_pseudo_register_read_into_value(), ia64_push_dummy_call(), indirect_pieced_value(), info_mach_region_command(), install_new_value(), iq2000_push_dummy_call(), is_unique_ancestor(), isvoid_internal_fn(), java_class_from_object(), java_link_class_type(), java_print_value_fields(), java_value_print(), linespec_parse_variable(), list_arg_or_local(), lm32_push_dummy_call(), lval_func_check_any_valid(), lval_func_check_synthetic_pointer(), lval_func_check_validity(), lval_func_read(), lval_func_write(), m2_print_unbounded_array(), m32c_push_dummy_call(), m32r_push_dummy_call(), m68hc11_push_dummy_call(), m68k_push_dummy_call(), m88k_store_arguments(), maintenance_print_type(), make_array_descriptor(), mep_push_dummy_call(), mips_eabi_push_dummy_call(), mips_n32n64_push_dummy_call(), mips_o32_push_dummy_call(), mips_o64_push_dummy_call(), mips_print_register(), mn10300_push_dummy_call(), msp430_push_dummy_call(), mt_push_dummy_call(), nios2_push_dummy_call(), opencl_component_ref(), opencl_logical_not(), opencl_relop(), opencl_value_cast(), output_command_const(), output_register(), parse_expression_for_completion(), parse_find_args(), pascal_object_print_static_field(), pascal_value_print(), pos_atr(), possible_user_operator_p(), ppc64_sysv_abi_push_dummy_call(), ppc64_sysv_abi_return_value(), ppc_sysv_abi_broken_return_value(), ppc_sysv_abi_push_dummy_call(), ppc_sysv_abi_return_value(), print_command_1(), print_formatted(), print_frame_arg(), print_one_vtable(), print_variable_or_computed(), printf_decfloat(), printf_wide_c_string(), push_large_arguments(), py_print_single_arg(), py_print_type(), py_print_value(), rank_function(), rank_one_type(), read_atcb(), read_fat_string_value(), read_frame_arg(), read_frame_register_value(), read_pieced_value(), regcache_cooked_read_value(), resolve_subexp(), return_command(), rl78_push_dummy_call(), rs6000_lynx178_push_dummy_call(), rs6000_push_dummy_call(), rx_push_dummy_call(), s390_push_dummy_call(), scalar_binop(), scan_discrim_bound(), score_push_dummy_call(), set_internalvar(), set_internalvar_component(), sh64_push_dummy_call(), sh_push_dummy_call_fpu(), sh_push_dummy_call_nofpu(), sh_return_value_fpu(), sh_return_value_nofpu(), sh_stack_allocsize(), siginfo_value_read(), siginfo_value_write(), sparc32_store_arguments(), sparc64_store_arguments(), spu_push_dummy_call(), spu_return_value(), thin_data_pntr(), tic6x_push_dummy_call(), tlb_value_read(), to_fixed_variant_branch_type(), type_from_class(), typecmp(), ui_printf(), unop_promote(), unop_user_defined_p(), unwrap_value(), update_watchpoint(), v850_push_dummy_call(), value_actual_type(), value_addr(), value_arg_coerce(), value_args_as_decimal(), value_as_address(), value_as_double(), value_as_long(), value_assign(), value_assign_to_component(), value_binop(), value_cast(), value_cast_pointers(), value_cast_structs(), value_check_printable(), value_coerce_array(), value_coerce_function(), value_coerce_to_target(), value_complement(), value_concat(), value_contents_equal(), value_dynamic_cast(), value_equal(), value_equal_contents(), value_f90_subarray(), value_fetch_lazy(), value_field(), value_find_oload_method_list(), value_fn_field(), value_full_object(), value_get_print_value(), value_in(), value_ind(), value_less(), value_logical_not(), value_must_coerce_to_target(), value_neg(), value_of_root(), value_pos(), value_print(), value_ptradd(), value_ptrdiff(), value_ref(), value_reinterpret_cast(), value_rtti_indirect_type(), value_slice(), value_strcmp(), value_struct_element_index(), value_struct_elt(), value_subscript(), value_subscript_packed(), value_subscripted_rvalue(), value_val_atr(), value_vector_widen(), value_x_binop(), value_x_unop(), varobj_create(), VEC(), vector_binop(), vector_relop(), watch_command_1(), whatis_exp(), wrap_type_print(), write_pieced_value(), x_command(), and xtensa_push_dummy_call().
struct value* value_vector_widen (struct value * scalar_value, struct type * vector_type) [read]
Definition at line 1355 of file valarith.c.
References _, allocate_value(), check_typedef(), CHECK_TYPEDEF, error(), gdb_assert, get_array_bounds(), LONGEST, memcpy(), TYPE_CODE, TYPE_CODE_ARRAY, TYPE_LENGTH, TYPE_TARGET_TYPE, TYPE_VECTOR, value_cast(), value_contents_all(), value_contents_writeable(), value_equal(), and value_type().
Referenced by opencl_value_cast(), and value_binop().
struct value* value_x_binop (struct value * arg1, struct value * arg2, enum exp_opcode op, enum exp_opcode otherop, enum noside noside) [read]
Definition at line 344 of file valarith.c.
References _, call_function_by_hand(), check_typedef(), coerce_ref(), error(), EVAL_AVOID_SIDE_EFFECTS, NOT_FOUND_ERROR, throw_error(), TYPE_CODE, TYPE_CODE_STRUCT, TYPE_TARGET_TYPE, value_addr(), VALUE_LVAL, value_type(), value_user_defined_op(), and value_zero().
Referenced by evaluate_subexp_standard().
struct value* value_x_unop (struct value * arg1, enum exp_opcode op, enum noside noside) [read]
Definition at line 509 of file valarith.c.
References _, call_function_by_hand(), check_typedef(), coerce_ref(), error(), EVAL_AVOID_SIDE_EFFECTS, get_type_arch(), NOT_FOUND_ERROR, throw_error(), TYPE_CODE, TYPE_CODE_STRUCT, TYPE_TARGET_TYPE, value_addr(), value_from_longest(), VALUE_LVAL, value_type(), value_user_defined_op(), and value_zero().
Referenced by evaluate_subexp_standard().
struct value* value_zero (struct type * type, enum lval_type lv) [read]
Definition at line 844 of file valops.c.
References allocate_value(), lval_computed, not_lval, and VALUE_LVAL.
Referenced by cast_into_complex(), create_value(), dummy_frame_prev_register(), evaluate_subexp_java(), evaluate_subexp_modula2(), evaluate_subexp_opencl(), evaluate_subexp_standard(), execute_stack_op(), frame_unwind_got_address(), frame_unwind_got_bytes(), frame_unwind_got_constant(), value_cast(), value_cast_structs(), value_dynamic_cast(), value_x_binop(), and value_x_unop().
struct value* varying_to_slice (struct value *) [read]
VEC (char_ptr) const