GDB (xrefs): /home/stan/gdb/src/gdb/varobj.h File Reference
/home/stan/gdb/src/gdb/varobj.h File Reference
#include "symtab.h"
#include "gdbtypes.h"
#include "vec.h"
Classes
struct varobj_update_result_t
Typedefs
typedef struct varobj * varobj_p
typedef struct
varobj_update_result_t varobj_update_result
Enumerations
enum varobj_display_formats {
FORMAT_NATURAL, FORMAT_BINARY, FORMAT_DECIMAL, FORMAT_HEXADECIMAL,
FORMAT_OCTAL
}
enum varobj_type { USE_SPECIFIED_FRAME, USE_CURRENT_FRAME, USE_SELECTED_FRAME }
enum varobj_scope_status { VAROBJ_IN_SCOPE = 0, VAROBJ_NOT_IN_SCOPE = 1, VAROBJ_INVALID = 2 }
enum varobj_languages {
vlang_c = 0, vlang_cplus, vlang_java, vlang_ada,
vlang_end
}
Functions
DEF_VEC_P (varobj_p)
DEF_VEC_O (varobj_update_result)
struct varobj * varobj_create (char *objname, char *expression, CORE_ADDR frame, enum varobj_type type)
char * varobj_gen_name (void)
struct varobj * varobj_get_handle (char *name)
char * varobj_get_objname (struct varobj *var)
char * varobj_get_expression (struct varobj *var)
int varobj_delete (struct varobj *var, char ***dellist, int only_children)
enum varobj_display_formats varobj_set_display_format (struct varobj *var, enum varobj_display_formats format)
enum varobj_display_formats varobj_get_display_format (struct varobj *var)
int varobj_get_thread_id (struct varobj *var)
void varobj_set_frozen (struct varobj *var, int frozen)
int varobj_get_frozen (struct varobj *var)
void varobj_get_child_range (struct varobj *var, int *from, int *to)
void varobj_set_child_range (struct varobj *var, int from, int to)
char * varobj_get_display_hint (struct varobj *var)
int varobj_get_num_children (struct varobj *var)
VEC (varobj_p)*varobj_list_children(struct varobj *var
char * varobj_get_type (struct varobj *var)
struct type * varobj_get_gdb_type (struct varobj *var)
char * varobj_get_path_expr (struct varobj *var)
enum varobj_languages varobj_get_language (struct varobj *var)
int varobj_get_attributes (struct varobj *var)
char * varobj_get_formatted_value (struct varobj *var, enum varobj_display_formats format)
char * varobj_get_value (struct varobj *var)
int varobj_set_value (struct varobj *var, char *expression)
void all_root_varobjs (void(*func)(struct varobj *var, void *data), void *data)
VEC (varobj_update_result)*varobj_update(struct varobj **varp
void varobj_invalidate (void)
int varobj_editable_p (struct varobj *var)
int varobj_floating_p (struct varobj *var)
void varobj_set_visualizer (struct varobj *var, const char *visualizer)
void varobj_enable_pretty_printing (void)
int varobj_has_more (struct varobj *var, int to)
int varobj_pretty_printed_p (struct varobj *var)
Variables
char * varobj_format_string []
char * varobj_language_string []
int * from
int int * to
int explicit
Typedef Documentation
typedef struct varobj* varobj_p
Definition at line 68 of file varobj.h.
typedef struct varobj_update_result_t varobj_update_result
Enumeration Type Documentation
enum varobj_display_formats
Enumerator:
FORMAT_NATURAL
FORMAT_BINARY
FORMAT_DECIMAL
FORMAT_HEXADECIMAL
FORMAT_OCTAL
Definition at line 25 of file varobj.h.
enum varobj_languages
Enumerator:
vlang_c
vlang_cplus
vlang_java
vlang_ada
vlang_end
Definition at line 57 of file varobj.h.
enum varobj_scope_status
Enumerator:
VAROBJ_IN_SCOPE
VAROBJ_NOT_IN_SCOPE
VAROBJ_INVALID
Definition at line 42 of file varobj.h.
enum varobj_type
Enumerator:
USE_SPECIFIED_FRAME
USE_CURRENT_FRAME
USE_SELECTED_FRAME
Definition at line 34 of file varobj.h.
Function Documentation
void all_root_varobjs (void(*)(struct varobj *var, void *data) func, void * data)
Definition at line 4114 of file varobj.c.
References varobj_root::next, and varobj_root::rootvar.
Referenced by mi_cmd_var_update(), and varobj_invalidate().
DEF_VEC_O (varobj_update_result)
DEF_VEC_P (varobj_p)
struct varobj* varobj_create (char * objname, char * expression, CORE_ADDR frame, enum varobj_type type) [read]
Definition at line 571 of file varobj.c.
References _, discard_cleanups(), do_cleanups(), error(), evaluate_expression(), evaluate_type(), find_frame_addr_in_frame_chain(), fprintf_unfiltered(), frame_find_by_id(), frame_id_p(), gdb_stderr, get_frame_block(), get_frame_id(), get_frame_pc(), get_selected_frame(), has_stack_frames(), inferior_ptid, innermost_block, install_new_value(), install_variable(), make_cleanup_free_variable(), varobj::name, new_root_variable(), null_frame_id, varobj::obj_name, p, parse_exp_1(), varobj::path_expr, pid_to_thread_id(), gdb_exception::reason, RETURN_MASK_ERROR, select_frame(), TRY_CATCH, varobj::type, USE_CURRENT_FRAME, USE_SELECTED_FRAME, value_actual_type(), value_cast(), value_type(), variable_default_display(), and variable_language().
Referenced by mi_cmd_var_create(), value_of_root(), variable_create(), and varobj_invalidate_iter().
int varobj_delete (struct varobj * var, char *** dellist, int only_children)
Definition at line 798 of file varobj.c.
References _, cppop(), cppush(), delete_variable(), warning(), and xmalloc().
Referenced by mi_cmd_var_delete(), update_dynamic_varobj_children(), update_type_if_necessary(), value_of_root(), variable_delete(), varobj_invalidate_iter(), varobj_set_visualizer(), and VEC().
int varobj_editable_p (struct varobj * var)
Definition at line 3036 of file varobj.c.
References get_value_type(), type, TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_FUNC, TYPE_CODE_METHOD, TYPE_CODE_STRUCT, TYPE_CODE_UNION, varobj::value, and VALUE_LVAL.
Referenced by mi_cmd_var_assign(), varobj_get_attributes(), and varobj_set_value().
void varobj_enable_pretty_printing (void)
Definition at line 71 of file varobj.c.
References pretty_printing.
Referenced by mi_cmd_enable_pretty_printing().
int varobj_floating_p (struct varobj * var)
Definition at line 3073 of file varobj.c.
Referenced by mi_cmd_var_update_iter().
char* varobj_gen_name (void)
Definition at line 738 of file varobj.c.
References xstrprintf().
Referenced by mi_cmd_var_create(), and variable_create().
int varobj_get_attributes (struct varobj * var)
Definition at line 1403 of file varobj.c.
References attributes, and varobj_editable_p().
Referenced by mi_cmd_var_show_attributes(), variable_obj_command(), and variable_value().
void varobj_get_child_range (struct varobj * var, int * from, int * to)
Definition at line 1857 of file varobj.c.
Referenced by varobj_update_one().
enum varobj_display_formats varobj_get_display_format (struct varobj * var)
Definition at line 890 of file varobj.c.
Referenced by mi_cmd_var_show_format(), and variable_format().
char* varobj_get_display_hint (struct varobj * var)
Definition at line 896 of file varobj.c.
References do_cleanups(), gdb_python_initialized, and gdbpy_get_display_hint().
Referenced by mi_cmd_var_list_children(), print_varobj(), and varobj_update_one().
char* varobj_get_expression (struct varobj * var)
Definition at line 787 of file varobj.c.
References name_of_variable().
Referenced by mi_cmd_var_info_expression(), print_varobj(), and variable_obj_command().
char* varobj_get_formatted_value (struct varobj * var, enum varobj_display_formats format)
Definition at line 1421 of file varobj.c.
References my_value_of_variable().
Referenced by mi_cmd_var_evaluate_expression().
int varobj_get_frozen (struct varobj * var)
Definition at line 955 of file varobj.c.
Referenced by print_varobj().
struct type* varobj_get_gdb_type (struct varobj * var) [read]
Definition at line 1341 of file varobj.c.
References varobj::type.
Referenced by mi_print_value_p().
struct varobj* varobj_get_handle (char * name) [read]
Definition at line 754 of file varobj.c.
References _, error(), int, vlist::next, varobj::obj_name, vlist::var, and VAROBJ_TABLE_SIZE.
Referenced by mi_cmd_var_assign(), mi_cmd_var_delete(), mi_cmd_var_evaluate_expression(), mi_cmd_var_info_expression(), mi_cmd_var_info_num_children(), mi_cmd_var_info_path_expression(), mi_cmd_var_info_type(), mi_cmd_var_list_children(), mi_cmd_var_set_format(), mi_cmd_var_set_frozen(), mi_cmd_var_set_update_range(), mi_cmd_var_set_visualizer(), mi_cmd_var_show_attributes(), mi_cmd_var_show_format(), mi_cmd_var_update(), and variable_obj_command().
enum varobj_languages varobj_get_language (struct varobj * var)
Definition at line 1397 of file varobj.c.
References variable_language().
Referenced by mi_cmd_var_info_expression().
int varobj_get_num_children (struct varobj * var)
Definition at line 1235 of file varobj.c.
References dummy, varobj::num_children, number_of_children(), and update_dynamic_varobj_children().
Referenced by mi_cmd_var_info_num_children(), print_varobj(), variable_obj_command(), and varobj_update_one().
char* varobj_get_objname (struct varobj * var)
Definition at line 779 of file varobj.c.
References varobj::obj_name.
Referenced by print_varobj(), variable_children(), variable_update(), and varobj_update_one().
char* varobj_get_path_expr (struct varobj * var)
Definition at line 1382 of file varobj.c.
References gdb_assert, is_root_p(), and varobj::path_expr.
Referenced by ada_path_expr_of_child(), c_describe_child(), cplus_describe_child(), and mi_cmd_var_info_path_expression().
int varobj_get_thread_id (struct varobj * var)
Definition at line 933 of file varobj.c.
Referenced by mi_cmd_var_update_iter(), and print_varobj().
char* varobj_get_type (struct varobj * var)
Definition at line 1327 of file varobj.c.
References CPLUS_FAKE_CHILD, varobj::type, and type_to_string().
Referenced by mi_cmd_var_info_type(), print_varobj(), update_type_if_necessary(), value_of_root(), variable_type(), and varobj_update_one().
char* varobj_get_value (struct varobj * var)
Definition at line 1428 of file varobj.c.
References my_value_of_variable().
Referenced by mi_cmd_var_assign(), mi_cmd_var_evaluate_expression(), mi_cmd_var_set_format(), print_varobj(), variable_value(), and varobj_update_one().
int varobj_has_more (struct varobj * var, int to)
Definition at line 920 of file varobj.c.
References VEC_length.
Referenced by mi_cmd_var_create(), mi_cmd_var_list_children(), varobj_update_one(), and VEC().
void varobj_invalidate (void)
Definition at line 4183 of file varobj.c.
References all_root_varobjs(), and varobj_invalidate_iter().
Referenced by clear_symtab_users().
int varobj_pretty_printed_p (struct varobj * var)
Definition at line 1415 of file varobj.c.
Referenced by mi_print_value_p(), print_varobj(), and varobj_update_one().
void varobj_set_child_range (struct varobj * var, int from, int to)
Definition at line 1867 of file varobj.c.
References from, and to.
Referenced by mi_cmd_var_set_update_range().
enum varobj_display_formats varobj_set_display_format (struct varobj * var, enum varobj_display_formats format)
Definition at line 862 of file varobj.c.
References FORMAT_BINARY, FORMAT_DECIMAL, FORMAT_HEXADECIMAL, FORMAT_NATURAL, FORMAT_OCTAL, varobj::value, value_get_print_value(), value_lazy(), variable_default_display(), varobj_value_is_changeable_p(), and xfree().
Referenced by mi_cmd_var_set_format(), and variable_format().
void varobj_set_frozen (struct varobj * var, int frozen)
Definition at line 942 of file varobj.c.
Referenced by mi_cmd_var_set_frozen().
int varobj_set_value (struct varobj * var, char * expression)
Definition at line 1438 of file varobj.c.
References coerce_array(), evaluate_expression(), gdb_assert, input_radix, install_new_value(), parse_exp_1(), gdb_exception::reason, RETURN_MASK_ERROR, TRY_CATCH, varobj::value, value_assign(), value_lazy(), varobj_editable_p(), varobj_value_is_changeable_p(), and xfree().
Referenced by mi_cmd_var_assign(), and variable_value().
void varobj_set_visualizer (struct varobj * var, const char * visualizer)
Definition at line 1874 of file varobj.c.
References _, do_cleanups(), error(), gdb_python_initialized, gdbpy_print_stack(), make_cleanup_py_decref(), varobj::num_children, and varobj_delete().
Referenced by mi_cmd_var_set_visualizer().
VEC (varobj_p)
VEC (varobj_update_result)
Variable Documentation
int explicit
Definition at line 162 of file varobj.h.
int* from
Definition at line 139 of file varobj.h.
Referenced by ada_value_has_mutated(), amd64_displaced_step_fixup(), arm_catch_kernel_helper_return(), arm_copy_block_xfer(), arm_linux_cleanup_svc(), arm_process_displaced_insn(), avr_scan_prologue(), displaced_read_reg(), fill_fpregset(), i386_displaced_step_fixup(), i387_register_to_value(), ia64_extract_return_value(), m68k_register_to_value(), mi_cmd_var_list_children(), mi_cmd_var_set_update_range(), read_type(), record_btrace_call_history_from(), record_btrace_insn_history_from(), remote_get_noisy_reply(), rs6000_register_to_value(), show_substitute_path_command(), supply_fpregset(), thumb2_copy_block_xfer(), thumb_copy_16bit_ldr_literal(), thumb_copy_b(), thumb_copy_cbnz_cbz(), thumb_copy_pop_pc_16bit(), unset_substitute_path_command(), update_dynamic_varobj_children(), variable_children(), varobj_set_child_range(), and varobj_update_one().
int int* to
Definition at line 139 of file varobj.h.
Referenced by ada_value_has_mutated(), amd64_relocate_instruction(), append_type_stack(), arm_copy_block_xfer(), arm_process_displaced_insn(), extract_bit_field(), fill_fpregset(), i386_relocate_instruction(), i387_value_to_register(), ia64_push_dummy_call(), ia64_store_return_value(), m68k_value_to_register(), mi_cmd_var_list_children(), mi_cmd_var_set_update_range(), mips64_fill_fpregset(), mips_fill_fpregset(), ppc_displaced_step_fixup(), read_type(), remote_get_noisy_reply(), replace_bit_field(), restrict_range(), rs6000_value_to_register(), thumb2_copy_block_xfer(), thumb_copy_pop_pc_16bit(), variable_children(), varobj_set_child_range(), and varobj_update_one().
char* varobj_format_string[]
Definition at line 61 of file varobj.c.
Referenced by mi_cmd_var_set_format(), and mi_cmd_var_show_format().
char* varobj_language_string[]
Definition at line 65 of file varobj.c.
Referenced by mi_cmd_var_info_expression().