GDB (xrefs): /home/stan/gdb/src/gdb/vax-tdep.c File Reference
/home/stan/gdb/src/gdb/vax-tdep.c File Reference
#include "defs.h"
#include "arch-utils.h"
#include "dis-asm.h"
#include "floatformat.h"
#include "frame.h"
#include "frame-base.h"
#include "frame-unwind.h"
#include "gdbcore.h"
#include "gdbtypes.h"
#include "osabi.h"
#include "regcache.h"
#include "regset.h"
#include "trad-frame.h"
#include "value.h"
#include "gdb_string.h"
#include "vax-tdep.h"
Classes
struct vax_frame_cache
Functions
static const char * vax_register_name (struct gdbarch *gdbarch, int regnum)
static struct type * vax_register_type (struct gdbarch *gdbarch, int regnum)
static void vax_supply_gregset (const struct regset *regset, struct regcache *regcache, int regnum, const void *gregs, size_t len)
static struct regset * vax_regset_from_core_section (struct gdbarch *gdbarch, const char *sect_name, size_t sect_size)
static CORE_ADDR vax_store_arguments (struct regcache *regcache, int nargs, struct value **args, CORE_ADDR sp)
static CORE_ADDR vax_push_dummy_call (struct gdbarch *gdbarch, struct value *function, struct regcache *regcache, CORE_ADDR bp_addr, int nargs, struct value **args, CORE_ADDR sp, int struct_return, CORE_ADDR struct_addr)
static struct frame_id vax_dummy_id (struct gdbarch *gdbarch, struct frame_info *this_frame)
static enum return_value_convention vax_return_value (struct gdbarch *gdbarch, struct value *function, struct type *type, struct regcache *regcache, gdb_byte *readbuf, const gdb_byte *writebuf)
static const gdb_byte * vax_breakpoint_from_pc (struct gdbarch *gdbarch, CORE_ADDR *pc, int *len)
static CORE_ADDR vax_skip_prologue (struct gdbarch *gdbarch, CORE_ADDR pc)
static struct vax_frame_cache * vax_frame_cache (struct frame_info *this_frame, void **this_cache)
static void vax_frame_this_id (struct frame_info *this_frame, void **this_cache, struct frame_id *this_id)
static struct value * vax_frame_prev_register (struct frame_info *this_frame, void **this_cache, int regnum)
static CORE_ADDR vax_frame_base_address (struct frame_info *this_frame, void **this_cache)
static CORE_ADDR vax_frame_args_address (struct frame_info *this_frame, void **this_cache)
static int vax_frame_num_args (struct frame_info *frame)
static CORE_ADDR vax_unwind_pc (struct gdbarch *gdbarch, struct frame_info *next_frame)
static struct gdbarch * vax_gdbarch_init (struct gdbarch_info info, struct gdbarch_list *arches)
void _initialize_vax_tdep (void)
Variables
static struct regset vax_gregset
static struct frame_unwind vax_frame_unwind
static struct frame_base vax_frame_base
Function Documentation
void _initialize_vax_tdep (void)
static const gdb_byte* vax_breakpoint_from_pc (struct gdbarch * gdbarch, CORE_ADDR * pc, int * len) [static]
Definition at line 260 of file vax-tdep.c.
Referenced by vax_gdbarch_init().
static struct frame_id vax_dummy_id (struct gdbarch * gdbarch, struct frame_info * this_frame) [static, read]
Definition at line 196 of file vax-tdep.c.
References frame_id_build(), get_frame_pc(), get_frame_register_unsigned(), and VAX_FP_REGNUM.
Referenced by vax_gdbarch_init().
static CORE_ADDR vax_frame_args_address (struct frame_info * this_frame, void ** this_cache) [static]
Definition at line 420 of file vax-tdep.c.
References get_frame_register_unsigned(), and VAX_AP_REGNUM.
static CORE_ADDR vax_frame_base_address (struct frame_info * this_frame, void ** this_cache) [static]
Definition at line 412 of file vax-tdep.c.
References vax_frame_cache::base, and vax_frame_cache().
static struct vax_frame_cache* vax_frame_cache (struct frame_info * this_frame, void ** this_cache) [static, read]
Definition at line 317 of file vax-tdep.c.
References trad_frame_saved_reg::addr, vax_frame_cache::base, FRAME_OBSTACK_ZALLOC, get_frame_memory_unsigned(), get_frame_register_unsigned(), regnum, vax_frame_cache::saved_regs, trad_frame_alloc_saved_regs(), trad_frame_set_value(), ULONGEST, VAX_AP_REGNUM, VAX_FP_REGNUM, VAX_PC_REGNUM, VAX_PS_REGNUM, and VAX_SP_REGNUM.
Referenced by vax_frame_base_address(), vax_frame_prev_register(), and vax_frame_this_id().
static int vax_frame_num_args (struct frame_info * frame) [static]
Definition at line 436 of file vax-tdep.c.
References get_frame_base_address(), get_frame_memory_unsigned(), get_frame_register_unsigned(), and VAX_AP_REGNUM.
Referenced by vax_gdbarch_init().
static struct value* vax_frame_prev_register (struct frame_info * this_frame, void ** this_cache, int regnum) [static, read]
Definition at line 392 of file vax-tdep.c.
References vax_frame_cache::saved_regs, trad_frame_get_prev_register(), and vax_frame_cache().
static void vax_frame_this_id (struct frame_info * this_frame, void ** this_cache, struct frame_id * this_id) [static]
Definition at line 379 of file vax-tdep.c.
References vax_frame_cache::base, frame_id_build(), get_frame_func(), and vax_frame_cache().
static struct gdbarch* vax_gdbarch_init (struct gdbarch_info info, struct gdbarch_list * arches) [static, read]
Definition at line 464 of file vax-tdep.c.
References core_addr_lessthan(), floatformats_vax_d, floatformats_vax_f, frame_base_set_default(), frame_unwind_append_unwinder(), gdbarch_list::gdbarch, gdbarch_alloc(), gdbarch_init_osabi(), gdbarch_list_lookup_by_info(), set_gdbarch_believe_pcc_promotion(), set_gdbarch_breakpoint_from_pc(), set_gdbarch_deprecated_function_start_offset(), set_gdbarch_double_format(), set_gdbarch_dummy_id(), set_gdbarch_float_format(), set_gdbarch_frame_args_skip(), set_gdbarch_frame_num_args(), set_gdbarch_inner_than(), set_gdbarch_long_double_bit(), set_gdbarch_long_double_format(), set_gdbarch_num_regs(), set_gdbarch_pc_regnum(), set_gdbarch_print_insn(), set_gdbarch_ps_regnum(), set_gdbarch_push_dummy_call(), set_gdbarch_register_name(), set_gdbarch_register_type(), set_gdbarch_regset_from_core_section(), set_gdbarch_return_value(), set_gdbarch_skip_prologue(), set_gdbarch_sp_regnum(), set_gdbarch_unwind_pc(), vax_breakpoint_from_pc(), vax_dummy_id(), vax_frame_num_args(), VAX_NUM_REGS, VAX_PC_REGNUM, VAX_PS_REGNUM, vax_push_dummy_call(), vax_register_name(), vax_register_type(), vax_regset_from_core_section(), vax_return_value(), vax_skip_prologue(), VAX_SP_REGNUM, and vax_unwind_pc().
static CORE_ADDR vax_push_dummy_call (struct gdbarch * gdbarch, struct value * function, struct regcache * regcache, CORE_ADDR bp_addr, int nargs, struct value ** args, CORE_ADDR sp, int struct_return, CORE_ADDR struct_addr) [static]
Definition at line 147 of file vax-tdep.c.
References gdbarch::byte_order, gdbarch_byte_order(), regcache_cooked_write(), regcache_cooked_write_unsigned(), store_unsigned_integer(), VAX_FP_REGNUM, VAX_R1_REGNUM, VAX_SP_REGNUM, vax_store_arguments(), and write_memory().
Referenced by vax_gdbarch_init().
static const char* vax_register_name (struct gdbarch * gdbarch, int regnum) [static]
Definition at line 42 of file vax-tdep.c.
References regnum.
Referenced by vax_gdbarch_init().
static struct type* vax_register_type (struct gdbarch * gdbarch, int regnum) [static, read]
Definition at line 61 of file vax-tdep.c.
References builtin_type::builtin_int, and builtin_type().
Referenced by vax_gdbarch_init().
static struct regset* vax_regset_from_core_section (struct gdbarch * gdbarch, const char * sect_name, size_t sect_size) [static, read]
Definition at line 98 of file vax-tdep.c.
References vax_gregset, and VAX_NUM_REGS.
Referenced by vax_gdbarch_init().
static enum return_value_convention vax_return_value (struct gdbarch * gdbarch, struct value * function, struct type * type, struct regcache * regcache, gdb_byte * readbuf, const gdb_byte * writebuf) [static]
Definition at line 206 of file vax-tdep.c.
References frame_info::addr, len, memcpy(), read_memory(), regcache_cooked_read(), regcache_cooked_write(), regcache_raw_read_unsigned(), RETURN_VALUE_ABI_RETURNS_ADDRESS, RETURN_VALUE_REGISTER_CONVENTION, TYPE_CODE, TYPE_CODE_ARRAY, TYPE_CODE_STRUCT, TYPE_CODE_UNION, TYPE_LENGTH, ULONGEST, VAX_R0_REGNUM, and VAX_R1_REGNUM.
Referenced by vax_gdbarch_init().
static CORE_ADDR vax_skip_prologue (struct gdbarch * gdbarch, CORE_ADDR pc) [static]
Definition at line 272 of file vax-tdep.c.
References gdbarch_byte_order(), and read_memory_unsigned_integer().
Referenced by vax_gdbarch_init().
static CORE_ADDR vax_store_arguments (struct regcache * regcache, int nargs, struct value ** args, CORE_ADDR sp) [static]
Definition at line 112 of file vax-tdep.c.
References gdbarch::byte_order, gdbarch_byte_order(), get_regcache_arch(), len, regcache_cooked_write(), store_unsigned_integer(), TYPE_LENGTH, value_contents_all(), value_enclosing_type(), VAX_AP_REGNUM, and write_memory().
Referenced by vax_push_dummy_call().
static void vax_supply_gregset (const struct regset * regset, struct regcache * regcache, int regnum, const void * gregs, size_t len) [static]
Definition at line 73 of file vax-tdep.c.
References regcache_raw_supply(), and VAX_NUM_REGS.
static CORE_ADDR vax_unwind_pc (struct gdbarch * gdbarch, struct frame_info * next_frame) [static]
Definition at line 450 of file vax-tdep.c.
References frame_unwind_register_unsigned(), and VAX_PC_REGNUM.
Referenced by vax_gdbarch_init().
Variable Documentation
struct frame_base vax_frame_base [static]
Initial value:
{
  &vax_frame_unwind,
  vax_frame_base_address,
  vax_frame_base_address,
  vax_frame_args_address
}
Definition at line 425 of file vax-tdep.c.
struct frame_unwind vax_frame_unwind [static]
Initial value:
{
  NORMAL_FRAME,
  default_frame_unwind_stop_reason,
  vax_frame_this_id,
  vax_frame_prev_register,
  NULL,
  default_frame_sniffer
}
Definition at line 400 of file vax-tdep.c.
struct regset vax_gregset [static]
Initial value:
{
  NULL,
  vax_supply_gregset
}
Definition at line 88 of file vax-tdep.c.
Referenced by vax_regset_from_core_section().