GDB (xrefs): /home/stan/gdb/src/gdb/vax-nat.c File Reference
/home/stan/gdb/src/gdb/vax-nat.c File Reference
#include "defs.h"
#include "inferior.h"
#include "gdb_assert.h"
#include <sys/types.h>
#include <sys/dir.h>
#include <sys/user.h>
#include <machine/reg.h>
#include "vax-tdep.h"
#include "inf-ptrace.h"
#include <nlist.h>
Defines
#define PT_READ_U 3
#define _PATH_UNIX "/vmunix"
Functions
static CORE_ADDR vax_register_u_addr (CORE_ADDR u_ar0, int regnum)
static CORE_ADDR vax_register_u_offset (struct gdbarch *gdbarch, int regnum, int store_p)
void _initialize_vax_nat (void)
Variables
static CORE_ADDR vax_kernel_u_addr = 0x80020000
static int vax_register_index []
Define Documentation
#define _PATH_UNIX "/vmunix"
Definition at line 89 of file vax-nat.c.
Referenced by _initialize_vax_nat().
#define PT_READ_U 3
Definition at line 33 of file vax-nat.c.
Referenced by vax_register_u_offset().
Function Documentation
void _initialize_vax_nat (void)
Definition at line 96 of file vax-nat.c.
References _PATH_UNIX, add_target(), inf_ptrace_trad_target(), vax_kernel_u_addr, and vax_register_u_offset().
static CORE_ADDR vax_register_u_addr (CORE_ADDR u_ar0, int regnum) [static]
Definition at line 61 of file vax-nat.c.
References gdb_assert, VAX_R0_REGNUM, and vax_register_index.
Referenced by vax_register_u_offset().
static CORE_ADDR vax_register_u_offset (struct gdbarch * gdbarch, int regnum, int store_p) [static]
Definition at line 70 of file vax-nat.c.
References _, inferior_ptid, perror_with_name(), PT_READ_U, ptid_get_pid(), ptrace(), vax_kernel_u_addr, and vax_register_u_addr().
Referenced by _initialize_vax_nat().
Variable Documentation
CORE_ADDR vax_kernel_u_addr = 0x80020000 [static]
Definition at line 49 of file vax-nat.c.
Referenced by _initialize_vax_nat(), and vax_register_u_offset().
int vax_register_index[] [static]
Initial value:
{
  R0, R1, R2, R3, R4, R5,
  R6, R7, R8, R9, R10, R11,
  AP, FP, SP, PC, PS
}
Definition at line 53 of file vax-nat.c.
Referenced by vax_register_u_addr().