GDB (xrefs): /home/stan/gdb/src/gdb/vaxbsd-nat.c File Reference
/home/stan/gdb/src/gdb/vaxbsd-nat.c File Reference
#include "defs.h"
#include "inferior.h"
#include "regcache.h"
#include "target.h"
#include <sys/types.h>
#include <sys/ptrace.h>
#include <machine/reg.h>
#include "vax-tdep.h"
#include "inf-ptrace.h"
#include <machine/pcb.h>
#include "bsd-kvm.h"
Functions
static void vaxbsd_supply_gregset (struct regcache *regcache, const void *gregs)
static void vaxbsd_collect_gregset (const struct regcache *regcache, void *gregs, int regnum)
static void vaxbsd_fetch_inferior_registers (struct target_ops *ops, struct regcache *regcache, int regnum)
static void vaxbsd_store_inferior_registers (struct target_ops *ops, struct regcache *regcache, int regnum)
static int vaxbsd_supply_pcb (struct regcache *regcache, struct pcb *pcb)
void _initialize_vaxbsd_nat (void)
Function Documentation
void _initialize_vaxbsd_nat (void)
Definition at line 136 of file vaxbsd-nat.c.
References add_target(), bsd_kvm_add_target(), inf_ptrace_target(), target_ops::to_fetch_registers, target_ops::to_store_registers, vaxbsd_fetch_inferior_registers(), vaxbsd_store_inferior_registers(), and vaxbsd_supply_pcb().
static void vaxbsd_collect_gregset (const struct regcache * regcache, void * gregs, int regnum) [static]
Definition at line 48 of file vaxbsd-nat.c.
References regcache_raw_collect(), and VAX_NUM_REGS.
Referenced by vaxbsd_store_inferior_registers().
static void vaxbsd_fetch_inferior_registers (struct target_ops * ops, struct regcache * regcache, int regnum) [static]
Definition at line 66 of file vaxbsd-nat.c.
References _, inferior_ptid, perror_with_name(), ptid_get_pid(), ptrace(), PTRACE_TYPE_ARG3, and vaxbsd_supply_gregset().
Referenced by _initialize_vaxbsd_nat().
static void vaxbsd_store_inferior_registers (struct target_ops * ops, struct regcache * regcache, int regnum) [static]
Definition at line 82 of file vaxbsd-nat.c.
References _, inferior_ptid, perror_with_name(), ptid_get_pid(), ptrace(), PTRACE_TYPE_ARG3, and vaxbsd_collect_gregset().
Referenced by _initialize_vaxbsd_nat().
static void vaxbsd_supply_gregset (struct regcache * regcache, const void * gregs) [static]
Definition at line 35 of file vaxbsd-nat.c.
References regcache_raw_supply(), regnum, and VAX_NUM_REGS.
Referenced by vaxbsd_fetch_inferior_registers().
static int vaxbsd_supply_pcb (struct regcache * regcache, struct pcb * pcb) [static]
Definition at line 107 of file vaxbsd-nat.c.
References regcache_raw_supply(), regnum, VAX_AP_REGNUM, VAX_FP_REGNUM, VAX_PC_REGNUM, VAX_PS_REGNUM, VAX_R0_REGNUM, and VAX_SP_REGNUM.
Referenced by _initialize_vaxbsd_nat().