GDB (xrefs): /home/stan/gdb/src/gdb/vaxobsd-tdep.c File Reference
/home/stan/gdb/src/gdb/vaxobsd-tdep.c File Reference
#include "defs.h"
#include "arch-utils.h"
#include "frame.h"
#include "frame-unwind.h"
#include "osabi.h"
#include "symtab.h"
#include "trad-frame.h"
#include "vax-tdep.h"
#include "gdb_string.h"
Defines
#define GDB_OSABI_OPENBSD_AOUT GDB_OSABI_NETBSD_AOUT
Functions
static int vaxobsd_sigtramp_sniffer (const struct frame_unwind *self, struct frame_info *this_frame, void **this_cache)
static struct trad_frame_cache * vaxobsd_sigtramp_frame_cache (struct frame_info *this_frame, void **this_cache)
static void vaxobsd_sigtramp_frame_this_id (struct frame_info *this_frame, void **this_cache, struct frame_id *this_id)
static struct value * vaxobsd_sigtramp_frame_prev_register (struct frame_info *this_frame, void **this_cache, int regnum)
static void vaxobsd_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
static enum gdb_osabi vaxobsd_aout_osabi_sniffer (bfd *abfd)
void _initialize_vaxobsd_tdep (void)
Variables
static const int vaxobsd_page_size = 4096
static const int vaxobsd_sigreturn_offset = 0x11
static const gdb_byte vaxobsd_sigreturn []
static struct frame_unwind vaxobsd_sigtramp_frame_unwind
Define Documentation
#define GDB_OSABI_OPENBSD_AOUT GDB_OSABI_NETBSD_AOUT
Definition at line 157 of file vaxobsd-tdep.c.
Referenced by vaxobsd_aout_osabi_sniffer().
Function Documentation
void _initialize_vaxobsd_tdep (void)
static enum gdb_osabi vaxobsd_aout_osabi_sniffer (bfd * abfd) [static]
Definition at line 160 of file vaxobsd-tdep.c.
References GDB_OSABI_OPENBSD_AOUT, and GDB_OSABI_UNKNOWN.
static void vaxobsd_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch) [static]
Definition at line 148 of file vaxobsd-tdep.c.
References frame_unwind_append_unwinder().
static struct trad_frame_cache* vaxobsd_sigtramp_frame_cache (struct frame_info * this_frame, void ** this_cache) [static, read]
Definition at line 86 of file vaxobsd-tdep.c.
References frame_id_build(), func, get_frame_memory_unsigned(), get_frame_pc(), get_frame_register_unsigned(), trad_frame_cache_zalloc(), trad_frame_set_id(), trad_frame_set_reg_addr(), VAX_AP_REGNUM, VAX_FP_REGNUM, VAX_PC_REGNUM, VAX_PS_REGNUM, VAX_SP_REGNUM, and vaxobsd_page_size.
Referenced by vaxobsd_sigtramp_frame_prev_register(), and vaxobsd_sigtramp_frame_this_id().
static struct value* vaxobsd_sigtramp_frame_prev_register (struct frame_info * this_frame, void ** this_cache, int regnum) [static, read]
Definition at line 126 of file vaxobsd-tdep.c.
References trad_frame_get_register(), and vaxobsd_sigtramp_frame_cache().
static void vaxobsd_sigtramp_frame_this_id (struct frame_info * this_frame, void ** this_cache, struct frame_id * this_id) [static]
Definition at line 116 of file vaxobsd-tdep.c.
References trad_frame_get_id(), and vaxobsd_sigtramp_frame_cache().
static int vaxobsd_sigtramp_sniffer (const struct frame_unwind * self, struct frame_info * this_frame, void ** this_cache) [static]
Definition at line 60 of file vaxobsd-tdep.c.
References find_pc_partial_function(), get_frame_pc(), memcmp(), name, safe_frame_unwind_memory(), vaxobsd_page_size, vaxobsd_sigreturn, and vaxobsd_sigreturn_offset.
Variable Documentation
const int vaxobsd_page_size = 4096 [static]
Definition at line 46 of file vaxobsd-tdep.c.
Referenced by vaxobsd_sigtramp_frame_cache(), and vaxobsd_sigtramp_sniffer().
const gdb_byte vaxobsd_sigreturn[] [static]
Initial value:
 {
  0xbc, 0x8f, 0x67, 0x00,
  0xbc, 0x01
}
Definition at line 54 of file vaxobsd-tdep.c.
Referenced by vaxobsd_sigtramp_sniffer().
const int vaxobsd_sigreturn_offset = 0x11 [static]
Definition at line 49 of file vaxobsd-tdep.c.
Referenced by vaxobsd_sigtramp_sniffer().
struct frame_unwind vaxobsd_sigtramp_frame_unwind [static]
Initial value:
 {
  SIGTRAMP_FRAME,
  default_frame_unwind_stop_reason,
  vaxobsd_sigtramp_frame_this_id,
  vaxobsd_sigtramp_frame_prev_register,
  NULL,
  vaxobsd_sigtramp_sniffer
}
Definition at line 135 of file vaxobsd-tdep.c.