GDB (xrefs): /home/stan/gdb/src/gdb/common/vec.c File Reference
/home/stan/gdb/src/gdb/common/vec.c File Reference
#include "defs.h"
#include "vec.h"
Classes
struct vec_prefix
Functions
static unsigned calculate_allocation (const struct vec_prefix *pfx, int reserve)
void * vec_p_reserve (void *vec, int reserve)
void * vec_o_reserve (void *vec, int reserve, size_t vec_offset, size_t elt_size)
Function Documentation
static unsigned calculate_allocation (const struct vec_prefix * pfx, int reserve) [inline, static]
Definition at line 40 of file vec.c.
References vec_prefix::alloc, gdb_assert, and vec_prefix::num.
Referenced by vec_o_reserve().
void* vec_o_reserve (void * vec, int reserve, size_t vec_offset, size_t elt_size)
Definition at line 96 of file vec.c.
References vec_prefix::alloc, calculate_allocation(), vec_prefix::vec, and xrealloc().
Referenced by vec_p_reserve().
void* vec_p_reserve (void * vec, int reserve)
Definition at line 85 of file vec.c.
References vec_o_reserve().