GDB (xrefs): /home/stan/gdb/src/gdb/target/waitstatus.c File Reference
/home/stan/gdb/src/gdb/target/waitstatus.c File Reference
#include "defs.h"
#include "waitstatus.h"
Functions
char * target_waitstatus_to_string (const struct target_waitstatus *ws)
Function Documentation
char* target_waitstatus_to_string (const struct target_waitstatus * ws)
Definition at line 32 of file waitstatus.c.
References gdb_signal_to_name(), target_waitstatus::integer, target_waitstatus::kind, target_waitstatus::sig, TARGET_WAITKIND_EXECD, TARGET_WAITKIND_EXITED, TARGET_WAITKIND_FORKED, TARGET_WAITKIND_IGNORE, TARGET_WAITKIND_LOADED, TARGET_WAITKIND_NO_HISTORY, TARGET_WAITKIND_NO_RESUMED, TARGET_WAITKIND_SIGNALLED, TARGET_WAITKIND_SPURIOUS, TARGET_WAITKIND_STOPPED, TARGET_WAITKIND_SYSCALL_ENTRY, TARGET_WAITKIND_SYSCALL_RETURN, TARGET_WAITKIND_VFORK_DONE, TARGET_WAITKIND_VFORKED, target_waitstatus::value, and xstrprintf().
Referenced by print_target_wait_results(), and target_wait().