GDB (xrefs): /home/stan/gdb/src/gdb/windows-tdep.c File Reference
/home/stan/gdb/src/gdb/windows-tdep.c File Reference
#include "defs.h"
#include "windows-tdep.h"
#include "gdb_obstack.h"
#include "xml-support.h"
#include "gdbarch.h"
#include "target.h"
#include "value.h"
#include "inferior.h"
#include "command.h"
#include "gdbcmd.h"
#include "gdbthread.h"
#include "objfiles.h"
#include "symfile.h"
#include "coff-pe-read.h"
#include "gdb_bfd.h"
#include "complaints.h"
#include "solib.h"
#include "solib-target.h"
Classes
struct thread_information_block_32
struct thread_information_block_64
Typedefs
typedef struct
thread_information_block_32 thread_information_32
typedef struct
thread_information_block_64 thread_information_64
Functions
static struct type * windows_get_tlb_type (struct gdbarch *gdbarch)
static void tlb_value_read (struct value *val)
static void tlb_value_write (struct value *v, struct value *fromval)
static struct value * tlb_make_value (struct gdbarch *gdbarch, struct internalvar *var, void *ignore)
static int display_one_tib (ptid_t ptid)
static void display_tib (char *args, int from_tty)
void windows_xfer_shared_library (const char *so_name, CORE_ADDR load_addr, struct gdbarch *gdbarch, struct obstack *obstack)
static void windows_iterate_over_objfiles_in_search_order (struct gdbarch *gdbarch, iterate_over_objfiles_in_search_order_cb_ftype *cb, void *cb_data, struct objfile *current_objfile)
static void show_maint_show_all_tib (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
static void info_w32_command (char *args, int from_tty)
void init_w32_command_list (void)
void windows_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
void _initialize_windows_tdep (void)
Variables
struct cmd_list_element * info_w32_cmdlist
static const char * TIB_NAME []
static const int MAX_TIB32
static const int MAX_TIB64
static const int FULL_TIB_SIZE = 0x1000
static int maint_display_all_tib = 0
static struct lval_funcs tlb_value_funcs
static int w32_prefix_command_valid = 0
initialize_file_ftype _initialize_windows_tdep
static struct internalvar_funcs tlb_funcs
Typedef Documentation
typedef struct thread_information_block_32 thread_information_32
typedef struct thread_information_block_64 thread_information_64
Function Documentation
void _initialize_windows_tdep (void)
Definition at line 515 of file windows-tdep.c.
References _, add_alias_cmd(), add_cmd(), add_setshow_boolean_cmd(), class_info, class_maintenance, create_internalvar_type_lazy(), display_tib(), init_w32_command_list(), maintenance_set_cmdlist, maintenance_show_cmdlist, and show_maint_show_all_tib().
static int display_one_tib (ptid_t ptid) [static]
Definition at line 293 of file windows-tdep.c.
References _, current_target, extract_unsigned_integer(), FULL_TIB_SIZE, gdbarch_byte_order(), gdbarch_ptr_bit(), max, MAX_TIB32, MAX_TIB64, paddress(), phex(), printf_filtered(), size, target_gdbarch(), target_get_tib_address, TARGET_OBJECT_MEMORY, target_pid_to_str(), target_read(), TIB_NAME, and ULONGEST.
Referenced by display_tib().
static void display_tib (char * args, int from_tty) [static]
Definition at line 370 of file windows-tdep.c.
References _, display_one_tib(), error(), find_thread_id(), inferior_ptid, null_ptid, parse_and_eval(), thread_info::ptid, ptid_equal(), target_thread_alive(), and value_as_long().
Referenced by _initialize_windows_tdep().
static void info_w32_command (char * args, int from_tty) [static]
Definition at line 468 of file windows-tdep.c.
References class_info, gdb_stdout, and help_list().
Referenced by init_w32_command_list().
void init_w32_command_list (void)
Definition at line 475 of file windows-tdep.c.
References _, add_prefix_cmd(), class_info, info_w32_command(), and infolist.
Referenced by _initialize_windows_nat(), and _initialize_windows_tdep().
static void show_maint_show_all_tib (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 460 of file windows-tdep.c.
References _, and fprintf_filtered().
Referenced by _initialize_windows_tdep().
static struct value* tlb_make_value (struct gdbarch * gdbarch, struct internalvar * var, void * ignore) [static, read]
Definition at line 278 of file windows-tdep.c.
References allocate_computed_value(), allocate_value(), inferior_ptid, null_ptid, ptid_equal(), target_has_stack, and windows_get_tlb_type().
static void tlb_value_read (struct value * val) [static]
Definition at line 247 of file windows-tdep.c.
References _, check_typedef(), error(), inferior_ptid, store_typed_address(), target_get_tib_address, value_contents_raw(), and value_type().
static void tlb_value_write (struct value * v, struct value * fromval) [static]
Definition at line 261 of file windows-tdep.c.
References _, and error().
static struct type* windows_get_tlb_type (struct gdbarch * gdbarch) [static, read]
Definition at line 107 of file windows-tdep.c.
References append_composite_type_field(), arch_composite_type(), arch_integer_type(), arch_type(), gdbarch_ptr_bit(), lookup_pointer_type(), TYPE_CODE_PTR, TYPE_CODE_STRUCT, TYPE_LENGTH, TYPE_NAME, and TYPE_TARGET_TYPE.
Referenced by tlb_make_value().
void windows_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch)
Definition at line 490 of file windows-tdep.c.
References set_gdbarch_has_dos_based_file_system(), set_gdbarch_iterate_over_objfiles_in_search_order(), set_solib_ops(), solib_target_so_ops, and windows_iterate_over_objfiles_in_search_order().
Referenced by amd64_windows_init_abi(), arm_wince_init_abi(), and i386_cygwin_init_abi().
static void windows_iterate_over_objfiles_in_search_order (struct gdbarch * gdbarch, iterate_over_objfiles_in_search_order_cb_ftype * cb, void * cb_data, struct objfile * current_objfile) [static]
Definition at line 434 of file windows-tdep.c.
References ALL_OBJFILES.
Referenced by windows_init_abi().
void windows_xfer_shared_library (const char * so_name, CORE_ADDR load_addr, struct gdbarch * gdbarch, struct obstack * obstack)
Definition at line 392 of file windows-tdep.c.
References gdb_bfd_open_maybe_remote(), gdb_bfd_unref(), obstack_grow_str, p, paddress(), pe_text_section_offset(), text_offset, xfree(), and xml_escape_text().
Referenced by core_process_module_section(), and windows_xfer_shared_libraries().
Variable Documentation
initialize_file_ftype _initialize_windows_tdep
Referenced by initialize_all_files().
const int FULL_TIB_SIZE = 0x1000 [static]
Definition at line 100 of file windows-tdep.c.
Referenced by display_one_tib().
struct cmd_list_element* info_w32_cmdlist
Definition at line 37 of file windows-tdep.c.
Referenced by _initialize_windows_nat().
int maint_display_all_tib = 0 [static]
Definition at line 102 of file windows-tdep.c.
const int MAX_TIB32 [static]
Initial value:
  sizeof (thread_information_32) / sizeof (uint32_t)
Definition at line 96 of file windows-tdep.c.
Referenced by display_one_tib().
const int MAX_TIB64 [static]
Initial value:
  sizeof (thread_information_64) / sizeof (uint64_t)
Definition at line 98 of file windows-tdep.c.
Referenced by display_one_tib().
const char* TIB_NAME[] [static]
Initial value:
  {
    " current_seh                 ",
    " current_top_of_stack        ",
    " current_bottom_of_stack     ",
    " sub_system_tib              ",
    " fiber_data                  ",
    " arbitrary_data_slot         ",
    " linear_address_tib          ",
    " environment_pointer         ",
    " process_id                  ",
    " current_thread_id           ",
    " active_rpc_handle           ",
    " thread_local_storage        ",
    " process_environment_block   ",
    " last_error_number           "
  }
Definition at line 78 of file windows-tdep.c.
Referenced by display_one_tib().
struct internalvar_funcs tlb_funcs [static]
Initial value:
{
  tlb_make_value,
  NULL,
  NULL
}
Definition at line 507 of file windows-tdep.c.
struct lval_funcs tlb_value_funcs [static]
Initial value:
  {
    tlb_value_read,
    tlb_value_write
  }
Definition at line 266 of file windows-tdep.c.
int w32_prefix_command_valid = 0 [static]
Definition at line 473 of file windows-tdep.c.