GDB (xrefs): /home/stan/gdb/src/gdb/windows-tdep.h File Reference
/home/stan/gdb/src/gdb/windows-tdep.h File Reference
Functions
void init_w32_command_list (void)
void windows_xfer_shared_library (const char *so_name, CORE_ADDR load_addr, struct gdbarch *gdbarch, struct obstack *obstack)
void windows_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
Variables
struct cmd_list_element * info_w32_cmdlist
Function Documentation
void init_w32_command_list (void)
Definition at line 475 of file windows-tdep.c.
References _, add_prefix_cmd(), class_info, info_w32_command(), and infolist.
Referenced by _initialize_windows_nat(), and _initialize_windows_tdep().
void windows_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch)
Definition at line 490 of file windows-tdep.c.
References set_gdbarch_has_dos_based_file_system(), set_gdbarch_iterate_over_objfiles_in_search_order(), set_solib_ops(), solib_target_so_ops, and windows_iterate_over_objfiles_in_search_order().
Referenced by amd64_windows_init_abi(), arm_wince_init_abi(), and i386_cygwin_init_abi().
void windows_xfer_shared_library (const char * so_name, CORE_ADDR load_addr, struct gdbarch * gdbarch, struct obstack * obstack)
Definition at line 392 of file windows-tdep.c.
References gdb_bfd_open_maybe_remote(), gdb_bfd_unref(), obstack_grow_str, p, paddress(), pe_text_section_offset(), text_offset, xfree(), and xml_escape_text().
Referenced by core_process_module_section(), and windows_xfer_shared_libraries().
Variable Documentation
struct cmd_list_element* info_w32_cmdlist
Definition at line 37 of file windows-tdep.c.
Referenced by _initialize_windows_nat().