GDB (xrefs): /home/stan/gdb/src/gdb/windows-nat.h File Reference
/home/stan/gdb/src/gdb/windows-nat.h File Reference
Typedefs
typedef int(segment_register_p_ftype)(int regnum)
Functions
void windows_set_context_register_offsets (const int *offsets)
void windows_set_segment_register_p (segment_register_p_ftype *fun)
Typedef Documentation
typedef int(segment_register_p_ftype)(int regnum)
Definition at line 25 of file windows-nat.h.
Function Documentation
void windows_set_context_register_offsets (const int * offsets)
Definition at line 274 of file windows-nat.c.
Referenced by _initialize_amd64_windows_nat(), and _initialize_i386_windows_nat().
void windows_set_segment_register_p (segment_register_p_ftype * fun)
Definition at line 282 of file windows-nat.c.
Referenced by _initialize_amd64_windows_nat(), and _initialize_i386_windows_nat().