GDB (xrefs): /home/stan/gdb/src/gdb/features/i386/x32-linux.c File Reference
/home/stan/gdb/src/gdb/features/i386/x32-linux.c File Reference
#include "defs.h"
#include "osabi.h"
#include "target-descriptions.h"
Functions
static void initialize_tdesc_x32_linux (void)
Variables
struct target_desc * tdesc_x32_linux
Function Documentation
static void initialize_tdesc_x32_linux (void) [static]
Definition at line 10 of file x32-linux.c.
References allocate_target_description(), osabi_from_tdesc_string(), set_tdesc_architecture(), set_tdesc_osabi(), tdesc_add_field(), tdesc_add_flag(), tdesc_create_feature(), tdesc_create_flags(), tdesc_create_reg(), tdesc_create_union(), tdesc_create_vector(), tdesc_named_type(), and type.
Referenced by _initialize_amd64_linux_tdep().
Variable Documentation
struct target_desc* tdesc_x32_linux
Definition at line 8 of file x32-linux.c.
Referenced by amd64_linux_core_read_description(), amd64_linux_read_description(), and amd64_x32_linux_init_abi().