GDB (xrefs): /home/stan/gdb/src/gdb/xml-support.c File Reference
/home/stan/gdb/src/gdb/xml-support.c File Reference
#include "defs.h"
#include "gdbcmd.h"
#include "exceptions.h"
#include "xml-support.h"
#include "filestuff.h"
#include "gdb_string.h"
#include "safe-ctype.h"
Functions
const char * fetch_xml_builtin (const char *filename)
LONGEST xml_builtin_xfer_partial (const char *filename, gdb_byte *readbuf, const gdb_byte *writebuf, ULONGEST offset, LONGEST len)
static void show_debug_xml (struct ui_file *file, int from_tty, struct cmd_list_element *c, const char *value)
void obstack_xml_printf (struct obstack *obstack, const char *format,...)
char * xml_fetch_content_from_file (const char *filename, void *baton)
void _initialize_xml_support (void)
Variables
static int debug_xml
Function Documentation
void _initialize_xml_support (void)
const char* fetch_xml_builtin (const char * filename)
Definition at line 929 of file xml-support.c.
References xml_builtin.
Referenced by xml_builtin_xfer_partial().
void obstack_xml_printf (struct obstack * obstack, const char * format, ...)
Definition at line 979 of file xml-support.c.
References obstack_grow_str, xfree(), and xml_escape_text().
static void show_debug_xml (struct ui_file * file, int from_tty, struct cmd_list_element * c, const char * value) [static]
Definition at line 972 of file xml-support.c.
References _, and fprintf_filtered().
LONGEST xml_builtin_xfer_partial (const char * filename, gdb_byte * readbuf, const gdb_byte * writebuf, ULONGEST offset, LONGEST len)
Definition at line 946 of file xml-support.c.
References fetch_xml_builtin(), gdb_assert, len, LONGEST, memcpy(), and offset.
char* xml_fetch_content_from_file (const char * filename, void * baton)
Definition at line 1019 of file xml-support.c.
References _, discard_cleanups(), do_cleanups(), free_current_contents(), gdb_fopen_cloexec(), len, make_cleanup(), make_cleanup_fclose(), malloc_failure(), offset, warning(), xfree(), xmalloc(), and xrealloc().
Referenced by file_read_description_xml().
Variable Documentation
int debug_xml [static]
Definition at line 30 of file xml-support.c.