GDB (xrefs): /home/stan/gdb/src/gdb/xml-syscall.c File Reference
/home/stan/gdb/src/gdb/xml-syscall.c File Reference
#include "defs.h"
#include "gdbtypes.h"
#include "xml-support.h"
#include "xml-syscall.h"
#include "target.h"
#include "filenames.h"
#include "gdb_assert.h"
Functions
static void syscall_warn_user (void)
void set_xml_syscall_file_name (const char *name)
void get_syscall_by_number (int syscall_number, struct syscall *s)
void get_syscall_by_name (const char *syscall_name, struct syscall *s)
const char ** get_syscall_names (void)
Function Documentation
void get_syscall_by_name (const char * syscall_name, struct syscall * s)
Definition at line 66 of file xml-syscall.c.
References syscall::name, syscall::number, syscall_warn_user(), and UNKNOWN_SYSCALL.
Referenced by VEC().
void get_syscall_by_number (int syscall_number, struct syscall * s)
Definition at line 57 of file xml-syscall.c.
References syscall::name, syscall::number, and syscall_warn_user().
Referenced by catch_syscall_command_1(), print_it_catch_syscall(), print_mention_catch_syscall(), print_one_catch_syscall(), print_recreate_catch_syscall(), and VEC().
const char** get_syscall_names (void)
Definition at line 75 of file xml-syscall.c.
References syscall_warn_user().
void set_xml_syscall_file_name (const char * name)
Definition at line 51 of file xml-syscall.c.
Referenced by amd64_linux_init_abi_common(), arm_linux_init_abi(), bfin_linux_init_abi(), i386_linux_init_abi(), mips_linux_init_abi(), ppc_linux_init_abi(), sparc32_linux_init_abi(), and sparc64_linux_init_abi().
static void syscall_warn_user (void) [static]
Definition at line 39 of file xml-syscall.c.
References _, and warning().
Referenced by get_syscall_by_name(), get_syscall_by_number(), and get_syscall_names().