GDB (xrefs): /home/stan/gdb/src/gdb/xtensa-linux-nat.c File Reference
/home/stan/gdb/src/gdb/xtensa-linux-nat.c File Reference
#include "defs.h"
#include "gdb_string.h"
#include "frame.h"
#include "inferior.h"
#include "gdbcore.h"
#include "regcache.h"
#include "gdb_assert.h"
#include "target.h"
#include "linux-nat.h"
#include <stdint.h>
#include <sys/types.h>
#include <signal.h>
#include <sys/user.h>
#include <sys/ioctl.h>
#include "gdb_wait.h"
#include <fcntl.h>
#include <sys/procfs.h>
#include <sys/ptrace.h>
#include "gregset.h"
#include "xtensa-tdep.h"
#include "xtensa-xtregs.c"
Defines
#define GET_THREAD_ID(PTID) get_thread_id (PTID)
Functions
static int get_thread_id (ptid_t ptid)
void fill_gregset (const struct regcache *regcache, gdb_gregset_t *gregsetp, int regnum)
void supply_gregset_reg (struct regcache *regcache, const gdb_gregset_t *gregsetp, int regnum)
void supply_gregset (struct regcache *regcache, const gdb_gregset_t *gregsetp)
void fill_fpregset (const struct regcache *regcache, gdb_fpregset_t *fpregsetp, int regnum)
void supply_fpregset (struct regcache *regcache, const gdb_fpregset_t *fpregsetp)
static void fetch_gregs (struct regcache *regcache, int regnum)
static void store_gregs (struct regcache *regcache, int regnum)
static void fetch_xtregs (struct regcache *regcache, int regnum)
static void store_xtregs (struct regcache *regcache, int regnum)
void xtensa_linux_fetch_inferior_registers (struct target_ops *ops, struct regcache *regcache, int regnum)
void xtensa_linux_store_inferior_registers (struct target_ops *ops, struct regcache *regcache, int regnum)
void _initialize_xtensa_linux_nat (void)
Variables
static int xtreg_lo
static int xtreg_high
Define Documentation
#define GET_THREAD_ID (PTID) get_thread_id (PTID)
Definition at line 56 of file xtensa-linux-nat.c.
Referenced by fetch_gregs(), fetch_xtregs(), store_gregs(), and store_xtregs().
Function Documentation
void _initialize_xtensa_linux_nat (void)
Definition at line 299 of file xtensa-linux-nat.c.
References xtensa_regtable_t::gdb_regnum, linux_nat_add_target(), linux_target(), xtensa_regtable_t::name, target_ops::to_fetch_registers, target_ops::to_store_registers, xtensa_linux_fetch_inferior_registers(), xtensa_linux_store_inferior_registers(), xtensa_regmap_table, xtreg_high, and xtreg_lo.
static void fetch_gregs (struct regcache * regcache, int regnum) [static]
Definition at line 185 of file xtensa-linux-nat.c.
References _, GET_THREAD_ID, inferior_ptid, perror_with_name(), ptrace(), PTRACE_GETREGS, and supply_gregset_reg().
Referenced by xtensa_linux_fetch_inferior_registers().
static void fetch_xtregs (struct regcache * regcache, int regnum) [static]
Definition at line 232 of file xtensa-linux-nat.c.
References _, xtensa_regtable_t::gdb_regnum, GET_THREAD_ID, inferior_ptid, xtensa_regtable_t::name, perror_with_name(), ptrace(), xtensa_regtable_t::ptrace_offset, regcache_raw_supply(), XTENSA_ELF_XTREG_SIZE, and xtensa_regmap_table.
Referenced by xtensa_linux_fetch_inferior_registers().
void fill_fpregset (const struct regcache * regcache, gdb_fpregset_t * fpregsetp, int regnum)
Definition at line 168 of file xtensa-linux-nat.c.
References AARCH64_FPCR_REGNUM, AARCH64_FPSR_REGNUM, AARCH64_V0_REGNUM, AARCH64_V31_REGNUM, regcache_raw_collect(), and V_REGISTER_SIZE.
void fill_gregset (const struct regcache * regcache, gdb_gregset_t * gregsetp, int regnum)
Definition at line 59 of file xtensa-linux-nat.c.
References AARCH64_CPSR_REGNUM, AARCH64_X0_REGNUM, xtensa_elf_gregset_t::ar, gdbarch_tdep::ar_base, gdbarch_pc_regnum(), gdbarch_ps_regnum(), gdbarch_tdep(), get_regcache_arch(), xtensa_elf_gregset_t::lbeg, xtensa_elf_gregset_t::lcount, xtensa_elf_gregset_t::lend, gdbarch_tdep::num_aregs, xtensa_elf_gregset_t::pc, xtensa_elf_gregset_t::ps, regcache_raw_collect(), xtensa_elf_gregset_t::sar, xtensa_elf_gregset_t::windowbase, xtensa_elf_gregset_t::windowstart, and X_REGISTER_SIZE.
static int get_thread_id (ptid_t ptid) [static]
Definition at line 49 of file xtensa-linux-nat.c.
References ptid_get_lwp(), and ptid_get_pid().
static void store_gregs (struct regcache * regcache, int regnum) [static]
Definition at line 204 of file xtensa-linux-nat.c.
References _, fill_gregset(), GET_THREAD_ID, inferior_ptid, perror_with_name(), ptrace(), PTRACE_GETREGS, and PTRACE_SETREGS.
Referenced by xtensa_linux_store_inferior_registers().
static void store_xtregs (struct regcache * regcache, int regnum) [static]
Definition at line 248 of file xtensa-linux-nat.c.
References _, xtensa_regtable_t::gdb_regnum, GET_THREAD_ID, inferior_ptid, xtensa_regtable_t::name, perror_with_name(), ptrace(), xtensa_regtable_t::ptrace_offset, regcache_raw_collect(), XTENSA_ELF_XTREG_SIZE, and xtensa_regmap_table.
Referenced by xtensa_linux_store_inferior_registers().
void supply_fpregset (struct regcache * regcache, const gdb_fpregset_t * fpregsetp)
Definition at line 175 of file xtensa-linux-nat.c.
References aarch64_linux_supply_fpregset().
void supply_gregset (struct regcache * regcache, const gdb_gregset_t * gregsetp)
Definition at line 162 of file xtensa-linux-nat.c.
References aarch64_linux_supply_gregset(), and supply_gregset_reg().
void supply_gregset_reg (struct regcache * regcache, const gdb_gregset_t * gregsetp, int regnum)
Definition at line 110 of file xtensa-linux-nat.c.
References xtensa_elf_gregset_t::ar, gdbarch_tdep::ar_base, gdbarch_pc_regnum(), gdbarch_ps_regnum(), gdbarch_tdep(), get_regcache_arch(), xtensa_elf_gregset_t::lbeg, xtensa_elf_gregset_t::lcount, xtensa_elf_gregset_t::lend, gdbarch_tdep::num_aregs, xtensa_elf_gregset_t::pc, xtensa_elf_gregset_t::ps, regcache_raw_supply(), xtensa_elf_gregset_t::sar, xtensa_elf_gregset_t::windowbase, and xtensa_elf_gregset_t::windowstart.
Referenced by fetch_gregs(), and supply_gregset().
void xtensa_linux_fetch_inferior_registers (struct target_ops * ops, struct regcache * regcache, int regnum)
Definition at line 267 of file xtensa-linux-nat.c.
References fetch_gregs(), fetch_xtregs(), xtreg_high, and xtreg_lo.
Referenced by _initialize_xtensa_linux_nat().
void xtensa_linux_store_inferior_registers (struct target_ops * ops, struct regcache * regcache, int regnum)
Definition at line 282 of file xtensa-linux-nat.c.
References store_gregs(), store_xtregs(), xtreg_high, and xtreg_lo.
Referenced by _initialize_xtensa_linux_nat().
Variable Documentation
int xtreg_high [static]
Definition at line 226 of file xtensa-linux-nat.c.
Referenced by _initialize_xtensa_linux_nat(), xtensa_linux_fetch_inferior_registers(), and xtensa_linux_store_inferior_registers().
int xtreg_lo [static]
Definition at line 225 of file xtensa-linux-nat.c.
Referenced by _initialize_xtensa_linux_nat(), xtensa_linux_fetch_inferior_registers(), and xtensa_linux_store_inferior_registers().