GDB (xrefs): /home/stan/gdb/src/gdb/xtensa-linux-tdep.c File Reference
/home/stan/gdb/src/gdb/xtensa-linux-tdep.c File Reference
#include "defs.h"
#include "osabi.h"
#include "linux-tdep.h"
#include "solib-svr4.h"
#include "symtab.h"
Enumerations
enum { XTENSA_LINUX_SIGRTMIN = 32, XTENSA_LINUX_SIGRTMAX = 63 }
Functions
static enum gdb_signal xtensa_linux_gdb_signal_from_target (struct gdbarch *gdbarch, int signal)
static int xtensa_linux_gdb_signal_to_target (struct gdbarch *gdbarch, enum gdb_signal signal)
static void xtensa_linux_init_abi (struct gdbarch_info info, struct gdbarch *gdbarch)
void _initialize_xtensa_linux_tdep (void)
Variables
initialize_file_ftype _initialize_xtensa_linux_tdep
Enumeration Type Documentation
anonymous enum
Enumerator:
XTENSA_LINUX_SIGRTMIN
XTENSA_LINUX_SIGRTMAX
Definition at line 33 of file xtensa-linux-tdep.c.
Function Documentation
void _initialize_xtensa_linux_tdep (void)
Definition at line 115 of file xtensa-linux-tdep.c.
References _initialize_xtensa_linux_tdep, GDB_OSABI_LINUX, gdbarch_register_osabi(), and xtensa_linux_init_abi().
static enum gdb_signal xtensa_linux_gdb_signal_from_target (struct gdbarch * gdbarch, int signal) [static]
Definition at line 43 of file xtensa-linux-tdep.c.
References int, linux_gdb_signal_from_target(), offset, XTENSA_LINUX_SIGRTMAX, and XTENSA_LINUX_SIGRTMIN.
Referenced by xtensa_linux_init_abi().
static int xtensa_linux_gdb_signal_to_target (struct gdbarch * gdbarch, enum gdb_signal signal) [static]
Definition at line 66 of file xtensa-linux-tdep.c.
References linux_gdb_signal_to_target(), offset, and XTENSA_LINUX_SIGRTMIN.
Referenced by xtensa_linux_init_abi().
static void xtensa_linux_init_abi (struct gdbarch_info info, struct gdbarch * gdbarch) [static]
Definition at line 98 of file xtensa-linux-tdep.c.
References linux_init_abi(), set_gdbarch_gdb_signal_from_target(), set_gdbarch_gdb_signal_to_target(), set_solib_svr4_fetch_link_map_offsets(), svr4_ilp32_fetch_link_map_offsets(), xtensa_linux_gdb_signal_from_target(), and xtensa_linux_gdb_signal_to_target().
Referenced by _initialize_xtensa_linux_tdep().
Variable Documentation
initialize_file_ftype _initialize_xtensa_linux_tdep
Referenced by _initialize_xtensa_linux_tdep(), and initialize_all_files().