GDBserver: /home/stan/gdb/src/gdb/common/agent.c File Reference
/home/stan/gdb/src/gdb/common/agent.c File Reference
#include "defs.h"
#include "target.h"
#include "inferior.h"
#include <string.h>
#include <unistd.h>
#include "agent.h"
#include "filestuff.h"
Classes
struct ipa_sym_addresses
Defines
#define DEBUG_AGENT(fmt, args...)
Functions
int agent_loaded_p (void)
int agent_look_up_symbols (void *arg)
static unsigned int agent_get_helper_thread_id (void)
static int gdb_connect_sync_socket (int pid)
int agent_run_command (int pid, const char *cmd, int len)
int agent_capability_check (enum agent_capa agent_capa)
void agent_capability_invalidate (void)
Variables
int debug_agent = 0
int use_agent = 0
static unsigned int helper_thread_id = 0
struct {
const char * name
int offset
int required
} symbol_list []
static struct ipa_sym_addresses ipa_sym_addrs
static int all_agent_symbols_looked_up = 0
static unsigned int agent_capability = 0
Define Documentation
#define DEBUG_AGENT (fmt, args...)
Value:
if (debug_agent)                        \
    fprintf_unfiltered (gdb_stdlog, fmt, ##args);
Definition at line 40 of file agent.c.
Referenced by agent_look_up_symbols(), and agent_run_command().
Function Documentation
int agent_capability_check (enum agent_capa agent_capa)
Definition at line 328 of file agent.c.
References _, ipa_sym_addresses::addr_capability, agent_capability, ipa_sym_addrs, read_inferior_memory(), and warning().
Referenced by cmd_qtdp(), cmd_qtstart(), and in_process_agent_supports_ust().
void agent_capability_invalidate (void)
Definition at line 355 of file agent.c.
References agent_capability.
static unsigned int agent_get_helper_thread_id (void) [static]
Definition at line 120 of file agent.c.
References _, ipa_sym_addresses::addr_helper_thread_id, helper_thread_id, ipa_sym_addrs, read_inferior_memory(), and warning().
Referenced by agent_run_command().
int agent_loaded_p (void)
Definition at line 78 of file agent.c.
References all_agent_symbols_looked_up.
Referenced by cmd_qtstart(), cmd_qtstatus(), handle_tracepoint_bkpts(), in_process_agent_supports_ust(), install_tracepoint(), linux_wait_1(), maybe_move_out_of_jump_pad(), maybe_write_ipa_not_loaded(), maybe_write_ipa_ust_not_loaded(), stop_tracing(), stuck_in_jump_pad_callback(), tracepoint_finished_step(), tracepoint_look_up_symbols(), and x86_get_min_fast_tracepoint_insn_len().
int agent_look_up_symbols (void * arg)
Definition at line 87 of file agent.c.
References all_agent_symbols_looked_up, DEBUG_AGENT, ipa_sym_addrs, look_up_one_symbol(), name, and symbol_list.
Referenced by tracepoint_look_up_symbols().
int agent_run_command (int pid, const char * cmd, int len)
Definition at line 212 of file agent.c.
References _, ipa_sym_addresses::addr_cmd_buf, agent_get_helper_thread_id(), DEBUG_AGENT, errno, gdb_connect_sync_socket(), IPA_CMD_BUF_SIZE, ipa_sym_addrs, thread_resume::kind, memset(), mywait(), non_stop, null_ptid, ptid_build(), ptid_equal(), read_inferior_memory(), target_ops::resume, thread_resume::sig, the_target, thread_resume::thread, warning(), and write_inferior_memory().
Referenced by run_inferior_command().
static int gdb_connect_sync_socket (int pid) [static]
Definition at line 161 of file agent.c.
References _, errno, gdb_socket_cloexec(), strerror, warning(), and xsnprintf().
Referenced by agent_run_command().
Variable Documentation
unsigned int agent_capability = 0 [static]
Definition at line 323 of file agent.c.
Referenced by agent_capability_check(), and agent_capability_invalidate().
int all_agent_symbols_looked_up = 0 [static]
Definition at line 75 of file agent.c.
Referenced by agent_loaded_p(), and agent_look_up_symbols().
int debug_agent = 0
Definition at line 33 of file agent.c.
unsigned int helper_thread_id = 0 [static]
Definition at line 60 of file agent.c.
Referenced by agent_get_helper_thread_id().
struct ipa_sym_addresses ipa_sym_addrs [static]
Definition at line 73 of file agent.c.
Referenced by agent_capability_check(), agent_get_helper_thread_id(), agent_look_up_symbols(), and agent_run_command().
const char* name
Definition at line 64 of file agent.c.
int offset
Definition at line 65 of file agent.c.
int required
Definition at line 66 of file agent.c.
struct { ... } symbol_list[] [static]
Referenced by agent_look_up_symbols().
int use_agent = 0
Definition at line 46 of file agent.c.
Referenced by cmd_qtdp(), cmd_qtstart(), and handle_general_set().