GDBserver: /home/stan/gdb/src/gdb/common/agent.h File Reference
/home/stan/gdb/src/gdb/common/agent.h File Reference
Defines
#define STRINGIZE_1(STR) #STR
#define STRINGIZE(STR) STRINGIZE_1(STR)
#define IPA_SYM(SYM)
#define IPA_CMD_BUF_SIZE 1024
Enumerations
enum agent_capa { AGENT_CAPA_FAST_TRACE = 0x1, AGENT_CAPA_STATIC_TRACE = (0x1 << 1) }
Functions
int agent_run_command (int pid, const char *cmd, int len)
int agent_look_up_symbols (void *)
int agent_loaded_p (void)
int agent_capability_check (enum agent_capa)
void agent_capability_invalidate (void)
Variables
int debug_agent
int use_agent
Define Documentation
#define IPA_CMD_BUF_SIZE 1024
Definition at line 34 of file agent.h.
Referenced by agent_run_command(), gdb_agent_about_to_close(), probe_marker_at(), tracepoint_send_agent(), and unprobe_marker_at().
#define IPA_SYM (SYM)
Value:
{                                                    \
    STRINGIZE (gdb_agent_ ## SYM),                      \
    offsetof (struct ipa_sym_addresses, addr_ ## SYM)   \
  }
Definition at line 26 of file agent.h.
#define STRINGIZE (STR) STRINGIZE_1(STR)
Definition at line 25 of file agent.h.
#define STRINGIZE_1 (STR) #STR
Definition at line 24 of file agent.h.
Enumeration Type Documentation
enum agent_capa
Enumerator:
AGENT_CAPA_FAST_TRACE
AGENT_CAPA_STATIC_TRACE
Definition at line 47 of file agent.h.
Function Documentation
int agent_capability_check (enum agent_capa)
void agent_capability_invalidate (void)
Definition at line 355 of file agent.c.
References agent_capability.
int agent_loaded_p (void)
Definition at line 78 of file agent.c.
References all_agent_symbols_looked_up.
Referenced by cmd_qtstart(), cmd_qtstatus(), handle_tracepoint_bkpts(), in_process_agent_supports_ust(), install_tracepoint(), linux_wait_1(), maybe_move_out_of_jump_pad(), maybe_write_ipa_not_loaded(), maybe_write_ipa_ust_not_loaded(), stop_tracing(), stuck_in_jump_pad_callback(), tracepoint_finished_step(), tracepoint_look_up_symbols(), and x86_get_min_fast_tracepoint_insn_len().
int agent_look_up_symbols (void *)
Definition at line 87 of file agent.c.
References all_agent_symbols_looked_up, DEBUG_AGENT, ipa_sym_addrs, look_up_one_symbol(), name, and symbol_list.
Referenced by tracepoint_look_up_symbols().
int agent_run_command (int pid, const char * cmd, int len)
Definition at line 212 of file agent.c.
References _, ipa_sym_addresses::addr_cmd_buf, agent_get_helper_thread_id(), DEBUG_AGENT, errno, gdb_connect_sync_socket(), IPA_CMD_BUF_SIZE, ipa_sym_addrs, thread_resume::kind, memset(), mywait(), non_stop, null_ptid, ptid_build(), ptid_equal(), read_inferior_memory(), target_ops::resume, thread_resume::sig, the_target, thread_resume::thread, warning(), and write_inferior_memory().
Referenced by run_inferior_command().
Variable Documentation
int debug_agent
Definition at line 33 of file agent.c.
int use_agent
Definition at line 46 of file agent.c.
Referenced by cmd_qtdp(), cmd_qtstart(), and handle_general_set().