GDBserver: /home/stan/gdb/src/gdb/common/buffer.h File Reference
/home/stan/gdb/src/gdb/common/buffer.h File Reference
#include <stddef.h>
#include <string.h>
#include "ansidecl.h"
Classes
struct buffer
Defines
#define buffer_grow_str(BUFFER, STRING) buffer_grow (BUFFER, STRING, strlen (STRING))
#define buffer_grow_str0(BUFFER, STRING) buffer_grow (BUFFER, STRING, strlen (STRING) + 1)
Functions
void buffer_grow (struct buffer *buffer, const char *data, size_t size)
void buffer_free (struct buffer *buffer)
void buffer_init (struct buffer *buffer)
char * buffer_finish (struct buffer *buffer)
void buffer_xml_printf (struct buffer *buffer, const char *format,...) ATTRIBUTE_PRINTF(2
Define Documentation
#define buffer_grow_str (BUFFER, STRING) buffer_grow (BUFFER, STRING, strlen (STRING))
Definition at line 58 of file buffer.h.
Referenced by buffer_xml_printf(), handle_qxfer_threads_proper(), linux_common_xfer_osdata(), linux_xfer_osdata_fds(), linux_xfer_osdata_isockets(), linux_xfer_osdata_modules(), linux_xfer_osdata_msg(), linux_xfer_osdata_processes(), linux_xfer_osdata_processgroups(), linux_xfer_osdata_sem(), linux_xfer_osdata_shm(), linux_xfer_osdata_threads(), and traceframe_read_info().
#define buffer_grow_str0 (BUFFER, STRING) buffer_grow (BUFFER, STRING, strlen (STRING) + 1)
Definition at line 60 of file buffer.h.
Referenced by handle_qxfer_threads_proper(), linux_attach_lwp_1(), linux_common_xfer_osdata(), linux_xfer_osdata_fds(), linux_xfer_osdata_isockets(), linux_xfer_osdata_modules(), linux_xfer_osdata_msg(), linux_xfer_osdata_processes(), linux_xfer_osdata_processgroups(), linux_xfer_osdata_sem(), linux_xfer_osdata_shm(), linux_xfer_osdata_threads(), and traceframe_read_info().
Function Documentation
char* buffer_finish (struct buffer * buffer)
Definition at line 77 of file buffer.c.
References buffer::buffer, buffer::buffer_size, and buffer::used_size.
Referenced by handle_qxfer_threads(), handle_qxfer_traceframe_info(), linux_attach_lwp_1(), linux_common_xfer_osdata(), linux_xfer_osdata_fds(), linux_xfer_osdata_isockets(), linux_xfer_osdata_modules(), linux_xfer_osdata_msg(), linux_xfer_osdata_processes(), linux_xfer_osdata_processgroups(), linux_xfer_osdata_sem(), linux_xfer_osdata_shm(), and linux_xfer_osdata_threads().
void buffer_free (struct buffer * buffer)
Definition at line 59 of file buffer.c.
References buffer::buffer, buffer::buffer_size, buffer::used_size, and xfree().
Referenced by handle_qxfer_btrace(), handle_qxfer_threads(), handle_qxfer_traceframe_info(), linux_common_xfer_osdata(), linux_xfer_osdata_fds(), linux_xfer_osdata_isockets(), linux_xfer_osdata_modules(), linux_xfer_osdata_msg(), linux_xfer_osdata_processes(), linux_xfer_osdata_processgroups(), linux_xfer_osdata_sem(), linux_xfer_osdata_shm(), and linux_xfer_osdata_threads().
void buffer_grow (struct buffer * buffer, const char * data, size_t size)
Definition at line 36 of file buffer.c.
References buffer::buffer, buffer::buffer_size, memcpy(), buffer::used_size, and xrealloc().
Referenced by buffer_xml_printf().
void buffer_init (struct buffer * buffer)
Definition at line 71 of file buffer.c.
References memset().
Referenced by handle_qxfer_threads(), handle_qxfer_traceframe_info(), linux_attach_lwp_1(), linux_common_xfer_osdata(), linux_xfer_osdata_fds(), linux_xfer_osdata_isockets(), linux_xfer_osdata_modules(), linux_xfer_osdata_msg(), linux_xfer_osdata_processes(), linux_xfer_osdata_processgroups(), linux_xfer_osdata_sem(), linux_xfer_osdata_shm(), and linux_xfer_osdata_threads().
void buffer_xml_printf (struct buffer * buffer, const char * format, ...)