GDBserver: /home/stan/gdb/src/gdb/gdbserver/dll.c File Reference
/home/stan/gdb/src/gdb/gdbserver/dll.c File Reference
#include "server.h"
#include "dll.h"
Defines
#define get_dll(inf) ((struct dll_info *)(inf))
Functions
static void free_one_dll (struct inferior_list_entry *inf)
static int match_dll (struct inferior_list_entry *inf, void *arg)
void loaded_dll (const char *name, CORE_ADDR base_addr)
void unloaded_dll (const char *name, CORE_ADDR base_addr)
void clear_dlls (void)
Variables
struct inferior_list all_dlls
int dlls_changed
Define Documentation
#define get_dll (inf) ((struct dll_info *)(inf))
Definition at line 21 of file dll.c.
Referenced by free_one_dll().
Function Documentation
void clear_dlls (void)
Definition at line 107 of file dll.c.
References all_dlls, for_each_inferior(), free_one_dll(), inferior_list::head, and inferior_list::tail.
Referenced by clear_inferiors().
static void free_one_dll (struct inferior_list_entry * inf) [static]
Definition at line 27 of file dll.c.
References get_dll, and dll_info::name.
Referenced by clear_dlls(), and unloaded_dll().
void loaded_dll (const char * name, CORE_ADDR base_addr)
Definition at line 58 of file dll.c.
References add_inferior_to_list(), all_dlls, dll_info::base_addr, dlls_changed, dll_info::entry, inferior_list_entry::id, memset(), minus_one_ptid, dll_info::name, xmalloc(), and xstrdup().
Referenced by win32_add_one_solib().
static int match_dll (struct inferior_list_entry * inf, void * arg) [static]
Definition at line 39 of file dll.c.
References dll_info::base_addr, and dll_info::name.
Referenced by unloaded_dll().
void unloaded_dll (const char * name, CORE_ADDR base_addr)
Definition at line 75 of file dll.c.
References all_dlls, dll_info::base_addr, dlls_changed, dll_info::entry, find_inferior(), free_one_dll(), match_dll(), dll_info::name, and remove_inferior().
Referenced by handle_unload_dll().
Variable Documentation
struct inferior_list all_dlls
Definition at line 23 of file dll.c.
Referenced by clear_dlls(), handle_qxfer_libraries(), loaded_dll(), and unloaded_dll().
int dlls_changed
Definition at line 24 of file dll.c.
Referenced by handle_v_attach(), loaded_dll(), main(), prepare_resume_reply(), and unloaded_dll().