GDBserver: /home/stan/gdb/src/gdb/common/filestuff.h File Reference
/home/stan/gdb/src/gdb/common/filestuff.h File Reference
Functions
void notice_open_fds (void)
void mark_fd_no_cloexec (int fd)
void unmark_fd_no_cloexec (int fd)
void close_most_fds (void)
int gdb_open_cloexec (const char *filename, int flags, unsigned long mode)
FILE * gdb_fopen_cloexec (const char *filename, const char *opentype)
int gdb_socketpair_cloexec (int namespace, int style, int protocol, int filedes[2])
int gdb_socket_cloexec (int namespace, int style, int protocol)
int gdb_pipe_cloexec (int filedes[2])
Function Documentation
void close_most_fds (void)
Definition at line 231 of file filestuff.c.
References do_close(), and fdwalk().
Referenced by linux_create_inferior(), lynx_create_inferior(), and spu_create_inferior().
FILE* gdb_fopen_cloexec (const char * filename, const char * opentype)
Definition at line 311 of file filestuff.c.
References errno, maybe_mark_cloexec(), and O_CLOEXEC.
Referenced by command_from_pid(), commandline_from_pid(), linux_common_core_of_thread(), linux_proc_get_int(), linux_proc_pid_has_state(), linux_xfer_osdata_modules(), linux_xfer_osdata_msg(), linux_xfer_osdata_sem(), linux_xfer_osdata_shm(), and print_sockets().
int gdb_open_cloexec (const char * filename, int flags, unsigned long mode)
Definition at line 298 of file filestuff.c.
References maybe_mark_cloexec(), and O_CLOEXEC.
int gdb_pipe_cloexec (int filedes[2])
Definition at line 387 of file filestuff.c.
References _, gdb_assert_not_reached, mark_cloexec(), maybe_mark_cloexec(), and O_CLOEXEC.
int gdb_socket_cloexec (int namespace, int style, int protocol)
Referenced by gdb_connect_sync_socket().
int gdb_socketpair_cloexec (int namespace, int style, int protocol, int filedes[2])
void mark_fd_no_cloexec (int fd)
Definition at line 183 of file filestuff.c.
void notice_open_fds (void)
Definition at line 175 of file filestuff.c.
References fdwalk().
Referenced by main().
void unmark_fd_no_cloexec (int fd)
Definition at line 191 of file filestuff.c.
References _, gdb_assert_not_reached, open_fds, VEC_iterate, and VEC_unordered_remove.