GDBserver: /home/stan/gdb/src/gdb/common/format.c File Reference
/home/stan/gdb/src/gdb/common/format.c File Reference
#include "defs.h"
#include <string.h>
#include "format.h"
Functions
struct format_piece * parse_format_string (const char **arg)
void free_format_pieces (struct format_piece *pieces)
void free_format_pieces_cleanup (void *ptr)
Function Documentation
void free_format_pieces (struct format_piece * pieces)
Definition at line 376 of file format.c.
References xfree().
Referenced by ax_printf(), and free_format_pieces_cleanup().
void free_format_pieces_cleanup (void * ptr)
Definition at line 390 of file format.c.
References free_format_pieces().
struct format_piece* parse_format_string (const char ** arg) [read]
Definition at line 31 of file format.c.
References _, format_piece::argclass, decfloat_arg, double_arg, error(), int_arg, literal_piece, long_arg, long_double_arg, long_long_arg, ptr_arg, strchr(), format_piece::string, string, string_arg, USE_PRINTF_I64, wide_char_arg, wide_string_arg, and xmalloc().
Referenced by ax_printf().