GDBserver: /home/stan/gdb/src/gdb/gdbserver/gdbthread.h File Reference
/home/stan/gdb/src/gdb/gdbserver/gdbthread.h File Reference
#include "server.h"
#include "inferiors.h"
Classes
struct thread_info
Defines
#define current_ptid ((struct inferior_list_entry *) current_inferior)->id
Functions
void remove_thread (struct thread_info *thread)
void add_thread (ptid_t ptid, void *target_data)
struct thread_info * find_thread_ptid (ptid_t ptid)
struct thread_info * gdb_id_to_thread (unsigned int)
Variables
struct inferior_list all_threads
Define Documentation
#define current_ptid ((struct inferior_list_entry *) current_inferior)->id
Definition at line 77 of file gdbthread.h.
Referenced by fetch_ppc_memory(), fetch_ppc_register(), myresume(), process_serial_event(), read_ptid(), run_inferior_command(), spu_proc_xfer_spu(), spu_request_interrupt(), spu_resume(), spu_thread_alive(), store_ppc_memory(), and thread_db_find_new_threads().
Function Documentation
void add_thread (ptid_t ptid, void * target_data)
Definition at line 90 of file inferiors.c.
References add_inferior_to_list(), all_threads, thread_info::entry, inferior_list_entry::id, thread_info::last_resume_kind, thread_info::last_status, memset(), thread_info::target_data, and xmalloc().
Referenced by child_add_thread(), handle_extended_wait(), linux_attach_lwp_1(), linux_create_inferior(), lynx_add_threads_after_attach(), lynx_wait_1(), nto_find_new_threads(), spu_attach(), and spu_create_inferior().
struct thread_info* find_thread_ptid (ptid_t ptid) [read]
Definition at line 130 of file inferiors.c.
References all_threads, thread_info::entry, get_thread, inferior_list::head, inferior_list_entry::id, inferior_list_entry::next, and ptid_equal().
Referenced by gdb_id_to_thread_id(), handle_btrace_general_set(), handle_query(), handle_qxfer_btrace(), linux_attach(), lynx_add_threads_after_attach(), lynx_thread_alive(), lynx_wait_1(), nto_find_new_threads(), prepare_resume_reply(), and set_desired_inferior().
struct thread_info* gdb_id_to_thread (unsigned int) [read]
void remove_thread (struct thread_info * thread)
Definition at line 162 of file inferiors.c.
References all_threads, thread_info::btrace, free_one_thread(), remove_inferior(), and target_disable_btrace.
Referenced by delete_lwp(), delete_thread_info(), lynx_wait_1(), and nto_find_new_threads().
Variable Documentation
struct inferior_list all_threads
Definition at line 28 of file inferiors.c.
Referenced by add_thread(), child_continue(), child_delete_thread(), child_init_thread_list(), clear_inferiors(), fake_breakpoint_event(), find_one_thread(), find_thread_ptid(), gdb_agent_about_to_close(), gdb_wants_all_threads_stopped(), get_child_debug_event(), handle_query(), handle_qxfer_threads_proper(), handle_status(), last_thread_of_process_p(), linux_detach(), linux_kill(), linux_resume(), linux_wait_1(), linux_wait_for_event(), process_serial_event(), regcache_invalidate(), regcache_release(), remove_thread(), set_desired_inferior(), switch_to_process(), target_running(), thread_id_to_gdb_id(), thread_rec(), win32_clear_inferiors(), win32_thread_alive(), and x86_arch_setup_process_callback().