GDBserver: /home/stan/gdb/src/gdb/gdbserver/hostio-errno.c File Reference
/home/stan/gdb/src/gdb/gdbserver/hostio-errno.c File Reference
#include <errno.h>
#include "server.h"
#include "gdb/fileio.h"
Functions
static int errno_to_fileio_error (int error)
void hostio_last_error_from_errno (char *buf)
Function Documentation
static int errno_to_fileio_error (int error) [static]
Definition at line 29 of file hostio-errno.c.
Referenced by hostio_last_error_from_errno().
void hostio_last_error_from_errno (char * buf)
Definition at line 81 of file hostio-errno.c.
References errno, errno_to_fileio_error(), and error().