GDBserver: /home/stan/gdb/src/gdb/gdbserver/hostio.h File Reference
/home/stan/gdb/src/gdb/gdbserver/hostio.h File Reference
Functions
int handle_vFile (char *, int, int *)
void hostio_last_error_from_errno (char *own_buf)
Function Documentation
int handle_vFile (char * , int , int *)
Definition at line 516 of file hostio.c.
References handle_close(), handle_open(), handle_pread(), handle_pwrite(), handle_readlink(), and handle_unlink().
Referenced by handle_v_requests().
void hostio_last_error_from_errno (char * own_buf)
Definition at line 81 of file hostio-errno.c.
References errno, errno_to_fileio_error(), and error().