GDBserver: /home/stan/gdb/src/gdb/gdbserver/i386-low.h File Reference
/home/stan/gdb/src/gdb/gdbserver/i386-low.h File Reference
Classes
struct i386_debug_reg_state
Defines
#define DR_FIRSTADDR 0
#define DR_LASTADDR 3
#define DR_NADDR 4 /* The number of debug address registers. */
#define DR_STATUS 6
#define DR_CONTROL 7
Functions
void i386_low_init_dregs (struct i386_debug_reg_state *state)
int i386_low_insert_watchpoint (struct i386_debug_reg_state *state, char type_from_packet, CORE_ADDR addr, int len)
int i386_low_remove_watchpoint (struct i386_debug_reg_state *state, char type_from_packet, CORE_ADDR addr, int len)
int i386_low_region_ok_for_watchpoint (struct i386_debug_reg_state *state, CORE_ADDR addr, int len)
int i386_low_stopped_data_address (struct i386_debug_reg_state *state, CORE_ADDR *addr_p)
int i386_low_stopped_by_watchpoint (struct i386_debug_reg_state *state)
void i386_dr_low_set_addr (const struct i386_debug_reg_state *state, int regnum)
CORE_ADDR i386_dr_low_get_addr (int regnum)
void i386_dr_low_set_control (const struct i386_debug_reg_state *state)
unsigned i386_dr_low_get_control (void)
unsigned i386_dr_low_get_status (void)
Define Documentation
#define DR_CONTROL 7
Definition at line 38 of file i386-low.h.
Referenced by i386_dr_low_get_control(), and x86_linux_prepare_to_resume().
#define DR_FIRSTADDR 0
Definition at line 34 of file i386-low.h.
Referenced by i386_dr_low_get_addr(), i386_dr_low_set_addr(), and x86_linux_prepare_to_resume().
#define DR_LASTADDR 3
Definition at line 35 of file i386-low.h.
Referenced by i386_dr_low_get_addr(), i386_dr_low_set_addr(), and x86_linux_prepare_to_resume().
#define DR_NADDR 4 /* The number of debug address registers. */
Definition at line 36 of file i386-low.h.
Referenced by i386_insert_aligned_watchpoint(), and i386_low_region_ok_for_watchpoint().
#define DR_STATUS 6
Definition at line 37 of file i386-low.h.
Referenced by i386_dr_low_get_status(), and x86_linux_prepare_to_resume().
Function Documentation
CORE_ADDR i386_dr_low_get_addr (int regnum)
Definition at line 560 of file linux-x86-low.c.
References current_inferior, debug_reg_state, DR_FIRSTADDR, DR_LASTADDR, i386_debug_reg_state::dr_mirror, gdb_assert, get_thread_lwp, ptid_of, and x86_linux_dr_get().
Referenced by i386_low_stopped_data_address().
unsigned i386_dr_low_get_control (void)
Definition at line 585 of file linux-x86-low.c.
References current_inferior, debug_reg_state, DR_CONTROL, i386_debug_reg_state::dr_control_mirror, get_thread_lwp, ptid_of, and x86_linux_dr_get().
Referenced by i386_low_stopped_data_address().
unsigned i386_dr_low_get_status (void)
Definition at line 597 of file linux-x86-low.c.
References current_inferior, debug_reg_state, DR_STATUS, i386_debug_reg_state::dr_status_mirror, get_thread_lwp, ptid_of, and x86_linux_dr_get().
Referenced by i386_low_stopped_data_address().
void i386_dr_low_set_addr (const struct i386_debug_reg_state * state, int regnum)
Definition at line 546 of file linux-x86-low.c.
References all_lwps, current_inferior, debug_registers_changed, debug_registers_used, DR_FIRSTADDR, DR_LASTADDR, fatal(), find_inferior(), get_thread_lwp, pid_of, and update_debug_registers_callback().
Referenced by i386_update_inferior_debug_regs().
void i386_dr_low_set_control (const struct i386_debug_reg_state * state)
Definition at line 574 of file linux-x86-low.c.
References all_lwps, current_inferior, debug_registers_changed, debug_registers_used, find_inferior(), get_thread_lwp, pid_of, and update_debug_registers_callback().
Referenced by i386_update_inferior_debug_regs().
void i386_low_init_dregs (struct i386_debug_reg_state * state)
Definition at line 147 of file i386-low.c.
References ALL_DEBUG_REGISTERS, i386_debug_reg_state::dr_control_mirror, i386_debug_reg_state::dr_mirror, i386_debug_reg_state::dr_ref_count, and i386_debug_reg_state::dr_status_mirror.
Referenced by i386_initial_stuff(), and x86_linux_new_process().
int i386_low_insert_watchpoint (struct i386_debug_reg_state * state, char type_from_packet, CORE_ADDR addr, int len)
Definition at line 459 of file i386-low.c.
References debug_hw_points, hw_read, i386_handle_nonaligned_watchpoint(), i386_insert_aligned_watchpoint(), i386_length_and_rw_bits(), i386_show_dr(), i386_update_inferior_debug_regs(), TARGET_HAS_DR_LEN_8, WP_INSERT, and Z_packet_to_hw_type().
Referenced by i386_insert_point(), and x86_insert_point().
int i386_low_region_ok_for_watchpoint (struct i386_debug_reg_state * state, CORE_ADDR addr, int len)
Definition at line 535 of file i386-low.c.
References DR_NADDR, hw_write, i386_handle_nonaligned_watchpoint(), and WP_COUNT.
int i386_low_remove_watchpoint (struct i386_debug_reg_state * state, char type_from_packet, CORE_ADDR addr, int len)
Definition at line 499 of file i386-low.c.
References debug_hw_points, i386_handle_nonaligned_watchpoint(), i386_length_and_rw_bits(), i386_remove_aligned_watchpoint(), i386_show_dr(), i386_update_inferior_debug_regs(), TARGET_HAS_DR_LEN_8, WP_REMOVE, and Z_packet_to_hw_type().
Referenced by i386_remove_point(), and x86_remove_point().
int i386_low_stopped_by_watchpoint (struct i386_debug_reg_state * state)
Definition at line 632 of file i386-low.c.
References i386_low_stopped_data_address().
Referenced by i386_stopped_by_watchpoint(), and x86_stopped_by_watchpoint().
int i386_low_stopped_data_address (struct i386_debug_reg_state * state, CORE_ADDR * addr_p)
Definition at line 552 of file i386-low.c.
References ALL_DEBUG_REGISTERS, debug_hw_points, hw_write, I386_DR_GET_RW_LEN, i386_dr_low_get_addr(), i386_dr_low_get_control(), i386_dr_low_get_status(), I386_DR_WATCH_HIT, and i386_show_dr().
Referenced by i386_low_stopped_by_watchpoint(), i386_stopped_data_address(), and x86_stopped_data_address().