GDBserver: /home/stan/gdb/src/gdb/gdbserver/i387-fp.c File Reference
/home/stan/gdb/src/gdb/gdbserver/i387-fp.c File Reference
#include "server.h"
#include "i387-fp.h"
#include "i386-xstate.h"
Classes
struct i387_fsave
struct i387_fxsave
struct i387_xsave
Functions
void i387_cache_to_fsave (struct regcache *regcache, void *buf)
void i387_fsave_to_cache (struct regcache *regcache, const void *buf)
void i387_cache_to_fxsave (struct regcache *regcache, void *buf)
void i387_cache_to_xsave (struct regcache *regcache, void *buf)
static int i387_ftag (struct i387_fxsave *fp, int regno)
void i387_fxsave_to_cache (struct regcache *regcache, const void *buf)
void i387_xsave_to_cache (struct regcache *regcache, const void *buf)
Variables
unsigned long long x86_xcr0 = I386_XSTATE_SSE_MASK
Function Documentation
void i387_cache_to_fsave (struct regcache * regcache, void * buf)
Definition at line 114 of file i387-fp.c.
References collect_register(), collect_register_by_name(), i387_fsave::fctrl, find_regno(), i387_fsave::fioff, i387_fsave::fiseg, i387_fsave::fooff, i387_fsave::fop, i387_fsave::foseg, i387_fsave::fstat, i387_fsave::ftag, i387_fsave::st_space, and regcache::tdesc.
Referenced by x86_fill_fpregset().
void i387_cache_to_fxsave (struct regcache * regcache, void * buf)
Definition at line 190 of file i387-fp.c.
References collect_register(), collect_register_by_name(), i387_fxsave::fctrl, find_regno(), i387_fxsave::fioff, i387_fxsave::fiseg, i387_fxsave::fooff, i387_fxsave::fop, i387_fxsave::foseg, i387_fxsave::fstat, i387_fxsave::ftag, i387_fxsave::mxcsr, register_size(), i387_fxsave::st_space, regcache::tdesc, and i387_fxsave::xmm_space.
Referenced by x86_fill_fpregset(), and x86_fill_fpxregset().
void i387_cache_to_xsave (struct regcache * regcache, void * buf)
Definition at line 243 of file i387-fp.c.
References collect_register(), collect_register_by_name(), i387_xsave::fctrl, find_regno(), i387_xsave::fioff, i387_xsave::fiseg, i387_xsave::fooff, i387_xsave::fop, i387_xsave::foseg, i387_xsave::fstat, i387_xsave::ftag, I386_XSTATE_AVX, I386_XSTATE_SSE, I386_XSTATE_X87, memcmp(), memcpy(), memset(), i387_xsave::mxcsr, register_size(), i387_xsave::st_space, regcache::tdesc, x86_xcr0, i387_xsave::xmm_space, i387_xsave::xstate_bv, and i387_xsave::ymmh_space.
Referenced by x86_fill_xstateregset().
void i387_fsave_to_cache (struct regcache * regcache, const void * buf)
Definition at line 154 of file i387-fp.c.
References i387_fsave::fctrl, find_regno(), i387_fsave::fioff, i387_fsave::fiseg, i387_fsave::fooff, i387_fsave::fop, i387_fsave::foseg, i387_fsave::fstat, i387_fsave::ftag, i387_fsave::st_space, supply_register(), supply_register_by_name(), and regcache::tdesc.
Referenced by x86_store_fpregset().
static int i387_ftag (struct i387_fxsave * fp, int regno) [static]
Definition at line 367 of file i387-fp.c.
References i387_fxsave::st_space.
Referenced by i387_fxsave_to_cache(), and i387_xsave_to_cache().
void i387_fxsave_to_cache (struct regcache * regcache, const void * buf)
Definition at line 414 of file i387-fp.c.
References i387_fxsave::fctrl, find_regno(), i387_fxsave::fioff, i387_fxsave::fiseg, i387_fxsave::fooff, i387_fxsave::fop, i387_fxsave::foseg, i387_fxsave::fstat, i387_fxsave::ftag, i387_ftag(), i387_fxsave::mxcsr, register_size(), i387_fxsave::st_space, supply_register(), supply_register_by_name(), regcache::tdesc, and i387_fxsave::xmm_space.
Referenced by x86_store_fpregset(), and x86_store_fpxregset().
void i387_xsave_to_cache (struct regcache * regcache, const void * buf)
Definition at line 467 of file i387-fp.c.
References i387_xsave::fctrl, find_regno(), i387_xsave::fioff, i387_xsave::fiseg, i387_xsave::fooff, i387_xsave::fop, i387_xsave::foseg, i387_xsave::fstat, i387_xsave::ftag, I386_XSTATE_AVX, I386_XSTATE_SSE, I386_XSTATE_X87, i387_ftag(), i387_xsave::mxcsr, register_size(), i387_xsave::st_space, supply_register(), supply_register_by_name(), supply_register_zeroed(), regcache::tdesc, x86_xcr0, i387_xsave::xmm_space, i387_xsave::xstate_bv, and i387_xsave::ymmh_space.
Referenced by x86_store_xstateregset().
Variable Documentation
unsigned long long x86_xcr0 = I386_XSTATE_SSE_MASK
Definition at line 570 of file i387-fp.c.
Referenced by i387_cache_to_xsave(), i387_xsave_to_cache(), and x86_linux_read_description().