GDBserver: /home/stan/gdb/src/gdb/gdbserver/inferiors.c File Reference
/home/stan/gdb/src/gdb/gdbserver/inferiors.c File Reference
#include <stdlib.h>
#include "server.h"
#include "gdbthread.h"
#include "dll.h"
Defines
#define get_thread(inf) ((struct thread_info *)(inf))
#define clear_list(LIST) do { (LIST)->head = (LIST)->tail = NULL; } while (0)
Functions
void add_inferior_to_list (struct inferior_list *list, struct inferior_list_entry *new_inferior)
void for_each_inferior (struct inferior_list *list, void(*action)(struct inferior_list_entry *))
void remove_inferior (struct inferior_list *list, struct inferior_list_entry *entry)
void add_thread (ptid_t thread_id, void *target_data)
ptid_t thread_id_to_gdb_id (ptid_t thread_id)
ptid_t thread_to_gdb_id (struct thread_info *thread)
struct thread_info * find_thread_ptid (ptid_t ptid)
ptid_t gdb_id_to_thread_id (ptid_t gdb_id)
static void free_one_thread (struct inferior_list_entry *inf)
void remove_thread (struct thread_info *thread)
struct inferior_list_entry * find_inferior (struct inferior_list *list, int(*func)(struct inferior_list_entry *, void *), void *arg)
struct inferior_list_entry * find_inferior_id (struct inferior_list *list, ptid_t id)
void * inferior_target_data (struct thread_info *inferior)
void set_inferior_target_data (struct thread_info *inferior, void *data)
void * inferior_regcache_data (struct thread_info *inferior)
void set_inferior_regcache_data (struct thread_info *inferior, void *data)
void clear_inferiors (void)
struct process_info * add_process (int pid, int attached)
void remove_process (struct process_info *process)
struct process_info * find_process_pid (int pid)
static int started_inferior_callback (struct inferior_list_entry *entry, void *args)
int have_started_inferiors_p (void)
static int attached_inferior_callback (struct inferior_list_entry *entry, void *args)
int have_attached_inferiors_p (void)
struct process_info * get_thread_process (struct thread_info *thread)
struct process_info * current_process (void)
Variables
struct inferior_list all_processes
struct inferior_list all_threads
struct thread_info * current_inferior
Define Documentation
#define clear_list (LIST) do { (LIST)->head = (LIST)->tail = NULL; } while (0)
Definition at line 232 of file inferiors.c.
Referenced by clear_inferiors().
#define get_thread (inf) ((struct thread_info *)(inf))
Definition at line 32 of file inferiors.c.
Referenced by find_thread_ptid(), and free_one_thread().
Function Documentation
void add_inferior_to_list (struct inferior_list * list, struct inferior_list_entry * new_inferior)
Definition at line 35 of file inferiors.c.
References inferior_list::head, inferior_list_entry::next, and inferior_list::tail.
Referenced by add_lwp(), add_process(), add_thread(), and loaded_dll().
struct process_info* add_process (int pid, int attached) [read]
Definition at line 247 of file inferiors.c.
References add_inferior_to_list(), all_processes, process_info::attached, process_info::head, inferior_list_entry::id, pid_to_ptid(), and xcalloc().
Referenced by do_attach(), do_initial_child_stuff(), linux_add_process(), lynx_add_process(), spu_attach(), and spu_create_inferior().
void add_thread (ptid_t thread_id, void * target_data)
Definition at line 90 of file inferiors.c.
References add_inferior_to_list(), all_threads, thread_info::entry, inferior_list_entry::id, thread_info::last_resume_kind, thread_info::last_status, memset(), thread_info::target_data, and xmalloc().
Referenced by child_add_thread(), handle_extended_wait(), linux_attach_lwp_1(), linux_create_inferior(), lynx_add_threads_after_attach(), lynx_wait_1(), nto_find_new_threads(), spu_attach(), and spu_create_inferior().
static int attached_inferior_callback (struct inferior_list_entry * entry, void * args) [static]
Definition at line 305 of file inferiors.c.
References process_info::attached.
Referenced by have_attached_inferiors_p().
void clear_inferiors (void)
Definition at line 236 of file inferiors.c.
References all_threads, clear_dlls(), clear_list, for_each_inferior(), and free_one_thread().
Referenced by lynx_mourn(), spu_detach(), spu_kill(), spu_wait(), and win32_clear_inferiors().
struct process_info* current_process (void) [read]
Definition at line 329 of file inferiors.c.
References fatal(), and get_thread_process().
Referenced by aarch64_arch_setup(), aarch64_get_debug_reg_state(), any_persistent_commands(), arm_arch_setup(), arm_insert_point(), arm_remove_point(), attach_thread(), bfin_arch_setup(), check_breakpoints(), check_mem_read(), check_mem_write(), cris_arch_setup(), current_target_desc(), delete_all_breakpoints(), delete_breakpoint(), delete_disabled_breakpoints(), delete_fast_tracepoint_jump(), delete_reinsert_breakpoints(), find_fast_tracepoint_jump_at(), find_gdb_breakpoint_at(), find_new_threads_callback(), find_one_thread(), find_raw_breakpoint_at(), handle_query(), ia64_arch_setup(), linux_look_up_symbols(), linux_qxfer_libraries_svr4(), linux_wait_1(), look_up_one_symbol(), lynx_resume(), m32r_arch_setup(), m68k_arch_setup(), mips_arch_setup(), mips_cannot_fetch_register(), mips_cannot_store_register(), mips_insert_point(), mips_remove_point(), mips_stopped_by_watchpoint(), mips_stopped_data_address(), nios2_arch_setup(), ppc_arch_setup(), ppc_cannot_store_register(), ppc_get_hwcap(), reinsert_all_breakpoints(), s390_arch_setup(), s390_regs_info(), set_breakpoint_at(), set_fast_tracepoint_jump(), set_raw_breakpoint_at(), sh_arch_setup(), sparc_arch_setup(), thread_db_create_event(), thread_db_enable_reporting(), thread_db_find_new_threads(), thread_db_init(), thread_db_look_up_one_symbol(), thread_db_look_up_symbols(), tic6x_arch_setup(), tile_arch_setup(), try_thread_db_load_1(), uninsert_all_breakpoints(), validate_breakpoints(), x86_arch_setup(), x86_insert_point(), x86_remove_point(), x86_stopped_by_watchpoint(), x86_stopped_data_address(), and xtensa_arch_setup().
struct inferior_list_entry* find_inferior (struct inferior_list * list, int(*)(struct inferior_list_entry *, void *) func, void * arg) [read]
Definition at line 175 of file inferiors.c.
References inferior_list::head, and inferior_list_entry::next.
Referenced by aarch64_notify_debug_reg_change(), arm_insert_point(), arm_remove_point(), child_continue(), find_lwp_pid(), handle_status(), have_attached_inferiors_p(), have_started_inferiors_p(), i386_dr_low_set_addr(), i386_dr_low_set_control(), last_thread_of_process_p(), linux_cancel_breakpoints(), linux_detach(), linux_kill(), linux_mourn(), linux_resume(), linux_stabilize_threads(), linux_wait_1(), linux_wait_for_event(), mips_insert_point(), mips_remove_point(), proceed_all_lwps(), process_serial_event(), regcache_invalidate(), select_event_lwp(), stop_all_lwps(), switch_to_process(), unloaded_dll(), unstop_all_lwps(), unsuspend_all_lwps(), and x86_arch_setup_process_callback().
struct inferior_list_entry* find_inferior_id (struct inferior_list * list, ptid_t id) [read]
Definition at line 194 of file inferiors.c.
References inferior_list::head, inferior_list_entry::id, inferior_list_entry::next, and ptid_equal().
Referenced by child_delete_thread(), find_one_thread(), find_process_pid(), get_child_debug_event(), handle_query(), linux_wait_1(), process_serial_event(), thread_rec(), and win32_thread_alive().
struct process_info* find_process_pid (int pid) [read]
Definition at line 275 of file inferiors.c.
References all_processes, find_inferior_id(), and pid_to_ptid().
Referenced by aarch64_linux_prepare_to_resume(), arm_prepare_to_resume(), get_thread_process(), handle_target_event(), handle_v_cont(), linux_detach(), linux_kill(), linux_wait_for_lwp(), lynx_detach(), lynx_kill(), lynx_wait_1(), mips_linux_prepare_to_resume(), myresume(), process_serial_event(), spu_detach(), spu_kill(), win32_detach(), win32_kill(), and x86_linux_prepare_to_resume().
struct thread_info* find_thread_ptid (ptid_t ptid) [read]
Definition at line 130 of file inferiors.c.
References all_threads, thread_info::entry, get_thread, inferior_list::head, inferior_list_entry::id, inferior_list_entry::next, and ptid_equal().
Referenced by gdb_id_to_thread_id(), handle_btrace_general_set(), handle_query(), handle_qxfer_btrace(), linux_attach(), lynx_add_threads_after_attach(), lynx_thread_alive(), lynx_wait_1(), nto_find_new_threads(), prepare_resume_reply(), and set_desired_inferior().
void for_each_inferior (struct inferior_list * list, void(*)(struct inferior_list_entry *) action)
Definition at line 49 of file inferiors.c.
References inferior_list::head, and inferior_list_entry::next.
Referenced by child_init_thread_list(), clear_dlls(), clear_inferiors(), detach_or_kill_for_exit(), fake_breakpoint_event(), gdb_wants_all_threads_stopped(), handle_status(), linux_stabilize_threads(), process_serial_event(), regcache_release(), stop_all_lwps(), win32_clear_inferiors(), and x86_linux_update_xmltarget().
static void free_one_thread (struct inferior_list_entry * inf) [static]
Definition at line 154 of file inferiors.c.
References free_register_cache(), get_thread, and inferior_regcache_data().
Referenced by clear_inferiors(), and remove_thread().
ptid_t gdb_id_to_thread_id (ptid_t gdb_id)
Definition at line 146 of file inferiors.c.
References thread_info::entry, find_thread_ptid(), inferior_list_entry::id, and null_ptid.
Referenced by process_serial_event().
struct process_info* get_thread_process (struct thread_info * thread) [read]
Definition at line 322 of file inferiors.c.
References thread_info::entry, find_process_pid(), inferior_list_entry::id, and ptid_get_pid().
Referenced by current_process(), get_thread_regcache(), and thread_db_get_tls_address().
int have_attached_inferiors_p (void)
Definition at line 315 of file inferiors.c.
References all_processes, attached_inferior_callback(), and find_inferior().
Referenced by detach_or_kill_for_exit().
int have_started_inferiors_p (void)
Definition at line 296 of file inferiors.c.
References all_processes, find_inferior(), and started_inferior_callback().
Referenced by detach_or_kill_for_exit().
void* inferior_regcache_data (struct thread_info * inferior)
Definition at line 221 of file inferiors.c.
References thread_info::regcache_data.
Referenced by free_one_thread(), free_register_cache_thread(), get_thread_regcache(), and regcache_invalidate_thread().
void* inferior_target_data (struct thread_info * inferior)
Definition at line 209 of file inferiors.c.
References thread_info::target_data.
Referenced by continue_one_thread(), delete_thread_info(), suspend_one_thread(), and thread_rec().
void remove_inferior (struct inferior_list * list, struct inferior_list_entry * entry)
Definition at line 63 of file inferiors.c.
References inferior_list::head, inferior_list_entry::next, and inferior_list::tail.
Referenced by delete_lwp(), remove_process(), remove_thread(), and unloaded_dll().
void remove_process (struct process_info * process)
Definition at line 266 of file inferiors.c.
References all_processes, clear_symbol_cache(), free_all_breakpoints(), process_info::head, remove_inferior(), and process_info::symbol_cache.
Referenced by linux_mourn(), nto_mourn(), spu_detach(), spu_kill(), spu_mourn(), win32_detach(), win32_kill(), and win32_mourn().
void remove_thread (struct thread_info * thread)
Definition at line 162 of file inferiors.c.
References all_threads, thread_info::btrace, free_one_thread(), remove_inferior(), and target_disable_btrace.
Referenced by delete_lwp(), delete_thread_info(), lynx_wait_1(), and nto_find_new_threads().
void set_inferior_regcache_data (struct thread_info * inferior, void * data)
Definition at line 227 of file inferiors.c.
References thread_info::regcache_data.
Referenced by free_register_cache_thread(), and get_thread_regcache().
void set_inferior_target_data (struct thread_info * inferior, void * data)
Definition at line 215 of file inferiors.c.
References thread_info::target_data.
static int started_inferior_callback (struct inferior_list_entry * entry, void * args) [static]
Definition at line 285 of file inferiors.c.
References process_info::attached.
Referenced by have_started_inferiors_p().
ptid_t thread_id_to_gdb_id (ptid_t thread_id)
Definition at line 109 of file inferiors.c.
References all_threads, inferior_list::head, inferior_list_entry::id, inferior_list_entry::next, null_ptid, and ptid_equal().
ptid_t thread_to_gdb_id (struct thread_info * thread)
Definition at line 124 of file inferiors.c.
References thread_info::entry, and inferior_list_entry::id.
Referenced by handle_query(), handle_qxfer_threads_proper(), lynx_fetch_registers(), lynx_read_memory(), lynx_request_interrupt(), lynx_resume(), lynx_store_registers(), lynx_wait_1(), lynx_write_memory(), nto_fetch_registers(), nto_stopped_by_watchpoint(), nto_stopped_data_address(), and nto_store_registers().
Variable Documentation
struct inferior_list all_processes
Definition at line 27 of file inferiors.c.
Referenced by add_process(), detach_or_kill_for_exit(), find_process_pid(), handle_query(), handle_status(), have_attached_inferiors_p(), have_started_inferiors_p(), process_serial_event(), remove_process(), and x86_linux_update_xmltarget().
struct inferior_list all_threads
Definition at line 28 of file inferiors.c.
Referenced by add_thread(), child_continue(), child_delete_thread(), child_init_thread_list(), clear_inferiors(), fake_breakpoint_event(), find_one_thread(), find_thread_ptid(), gdb_agent_about_to_close(), gdb_wants_all_threads_stopped(), get_child_debug_event(), handle_query(), handle_qxfer_threads_proper(), handle_status(), last_thread_of_process_p(), linux_detach(), linux_kill(), linux_resume(), linux_wait_1(), linux_wait_for_event(), process_serial_event(), regcache_invalidate(), regcache_release(), remove_thread(), set_desired_inferior(), switch_to_process(), target_running(), thread_id_to_gdb_id(), thread_rec(), win32_clear_inferiors(), win32_thread_alive(), and x86_arch_setup_process_callback().
struct thread_info* current_inferior
Definition at line 30 of file inferiors.c.
Referenced by aarch64_arch_setup(), aarch64_notify_debug_reg_change(), aarch64_stopped_data_address(), arm_breakpoint_at(), arm_read_description(), arm_reinsert_addr(), arm_stopped_by_watchpoint(), arm_stopped_data_address(), attach_inferior(), cancel_breakpoint(), cmd_qtminftpilen(), cris_insert_point(), cris_reinsert_addr(), cris_remove_point(), cris_stopped_by_watchpoint(), cris_stopped_data_address(), current_inferior_ptid(), current_target_desc(), disable_thread_event_reporting(), gdb_agent_about_to_close(), gdb_condition_true_at_breakpoint(), get_child_debug_event(), get_pc(), get_thread_regcache(), handle_target_event(), handle_v_cont(), i386_dr_low_get_addr(), i386_dr_low_get_control(), i386_dr_low_get_status(), i386_dr_low_set_addr(), i386_dr_low_set_control(), input_interrupt(), linux_attach_lwp_1(), linux_qxfer_libraries_svr4(), linux_qxfer_spu(), linux_read_auxv(), linux_read_memory(), linux_request_interrupt(), linux_resume_one_lwp(), linux_stabilize_threads(), linux_stopped_by_watchpoint(), linux_stopped_data_address(), linux_wait_1(), linux_wait_for_event(), linux_wait_for_lwp(), linux_write_memory(), linux_xfer_siginfo(), lynx_fetch_registers(), lynx_read_memory(), lynx_request_interrupt(), lynx_resume(), lynx_store_registers(), lynx_wait_1(), lynx_write_memory(), maybe_move_out_of_jump_pad(), mips_insert_point(), mips_read_description(), mips_reinsert_addr(), mips_stopped_by_watchpoint(), mips_stopped_data_address(), myresume(), need_step_over_p(), nios2_reinsert_addr(), nto_fetch_registers(), nto_stopped_by_watchpoint(), nto_stopped_data_address(), nto_store_registers(), prepare_resume_reply(), process_serial_event(), ps_getpid(), ps_lgetregs(), putpkt_binary_1(), regcache_invalidate(), regcache_invalidate_thread(), remove_thread_event_breakpoints(), run_breakpoint_commands(), s390_arch_setup(), set_desired_inferior(), sparc_reinsert_addr(), start_inferior(), start_step_over(), switch_to_process(), thread_db_create_event(), thread_db_get_tls_address(), tile_arch_setup(), update_registers_callback(), wait_for_sigstop(), win32_wait(), x86_arch_setup_process_callback(), x86_linux_read_description(), x86_linux_update_xmltarget(), and x86_siginfo_fixup().