GDBserver: /home/stan/gdb/src/gdb/gdbserver/linux-i386-ipa.c File Reference
/home/stan/gdb/src/gdb/gdbserver/linux-i386-ipa.c File Reference
#include "server.h"
#include <stdint.h>
#include <sys/mman.h>
#include "tracepoint.h"
Defines
#define i386_num_regs 16
#define FT_CR_EAX 15
#define FT_CR_ECX 14
#define FT_CR_EDX 13
#define FT_CR_EBX 12
#define FT_CR_UESP 11
#define FT_CR_EBP 10
#define FT_CR_ESI 9
#define FT_CR_EDI 8
#define FT_CR_EIP 7
#define FT_CR_EFL 6
#define FT_CR_DS 5
#define FT_CR_ES 4
#define FT_CR_FS 3
#define FT_CR_GS 2
#define FT_CR_SS 1
#define FT_CR_CS 0
Enumerations
enum i386_gdb_regnum {
I386_EAX_REGNUM, I386_ECX_REGNUM, I386_EDX_REGNUM, I386_EBX_REGNUM,
I386_ESP_REGNUM, I386_EBP_REGNUM, I386_ESI_REGNUM, I386_EDI_REGNUM,
I386_EIP_REGNUM, I386_EFLAGS_REGNUM, I386_CS_REGNUM, I386_SS_REGNUM,
I386_DS_REGNUM, I386_ES_REGNUM, I386_FS_REGNUM, I386_GS_REGNUM,
I386_ST0_REGNUM
}
Functions
void init_registers_i386_linux (void)
void supply_fast_tracepoint_registers (struct regcache *regcache, const unsigned char *buf)
ULONGEST __attribute__ ((visibility("default"), used))
static void initialize_fast_tracepoint_trampoline_buffer (void)
void initialize_low_tracepoint (void)
Variables
struct target_desc * tdesc_i386_linux
static const int i386_ft_collect_regmap []
const char * gdbserver_xmltarget
Define Documentation
#define FT_CR_CS 0
Definition at line 70 of file linux-i386-ipa.c.
#define FT_CR_DS 5
Definition at line 65 of file linux-i386-ipa.c.
#define FT_CR_EAX 15
Definition at line 55 of file linux-i386-ipa.c.
#define FT_CR_EBP 10
Definition at line 60 of file linux-i386-ipa.c.
#define FT_CR_EBX 12
Definition at line 58 of file linux-i386-ipa.c.
#define FT_CR_ECX 14
Definition at line 56 of file linux-i386-ipa.c.
#define FT_CR_EDI 8
Definition at line 62 of file linux-i386-ipa.c.
#define FT_CR_EDX 13
Definition at line 57 of file linux-i386-ipa.c.
#define FT_CR_EFL 6
Definition at line 64 of file linux-i386-ipa.c.
#define FT_CR_EIP 7
Definition at line 63 of file linux-i386-ipa.c.
#define FT_CR_ES 4
Definition at line 66 of file linux-i386-ipa.c.
#define FT_CR_ESI 9
Definition at line 61 of file linux-i386-ipa.c.
#define FT_CR_FS 3
Definition at line 67 of file linux-i386-ipa.c.
#define FT_CR_GS 2
Definition at line 68 of file linux-i386-ipa.c.
#define FT_CR_SS 1
Definition at line 69 of file linux-i386-ipa.c.
#define FT_CR_UESP 11
Definition at line 59 of file linux-i386-ipa.c.
#define i386_num_regs 16
Definition at line 49 of file linux-i386-ipa.c.
Referenced by __attribute__(), and supply_fast_tracepoint_registers().
Enumeration Type Documentation
enum i386_gdb_regnum
Enumerator:
I386_EAX_REGNUM
I386_ECX_REGNUM
I386_EDX_REGNUM
I386_EBX_REGNUM
I386_ESP_REGNUM
I386_EBP_REGNUM
I386_ESI_REGNUM
I386_EDI_REGNUM
I386_EIP_REGNUM
I386_EFLAGS_REGNUM
I386_CS_REGNUM
I386_SS_REGNUM
I386_DS_REGNUM
I386_ES_REGNUM
I386_FS_REGNUM
I386_GS_REGNUM
I386_ST0_REGNUM
Definition at line 28 of file linux-i386-ipa.c.
Function Documentation
ULONGEST __attribute__ ((visibility("default"), used))
Definition at line 102 of file linux-i386-ipa.c.
References I386_CS_REGNUM, i386_ft_collect_regmap, I386_GS_REGNUM, and i386_num_regs.
void init_registers_i386_linux (void)
Referenced by initialize_low_arch(), and initialize_low_tracepoint().
static void initialize_fast_tracepoint_trampoline_buffer (void) [static]
Definition at line 202 of file linux-i386-ipa.c.
References errno, IPA_BUFSIZ, and strerror.
Referenced by initialize_low_tracepoint().
void initialize_low_tracepoint (void)
Definition at line 252 of file linux-i386-ipa.c.
References init_registers_i386_linux(), and initialize_fast_tracepoint_trampoline_buffer().
void supply_fast_tracepoint_registers (struct regcache * regcache, const unsigned char * buf)
Definition at line 84 of file linux-i386-ipa.c.
References I386_CS_REGNUM, i386_ft_collect_regmap, I386_GS_REGNUM, i386_num_regs, and supply_register().
Variable Documentation
const char* gdbserver_xmltarget
Definition at line 196 of file linux-i386-ipa.c.
const int i386_ft_collect_regmap[] [static]
Initial value:
{
  FT_CR_EAX * 4, FT_CR_ECX * 4, FT_CR_EDX * 4, FT_CR_EBX * 4,
  FT_CR_UESP * 4, FT_CR_EBP * 4, FT_CR_ESI * 4, FT_CR_EDI * 4,
  FT_CR_EIP * 4, FT_CR_EFL * 4, FT_CR_CS * 4, FT_CR_SS * 4,
  FT_CR_DS * 4, FT_CR_ES * 4, FT_CR_FS * 4, FT_CR_GS * 4
}
Definition at line 75 of file linux-i386-ipa.c.
Referenced by __attribute__(), and supply_fast_tracepoint_registers().
struct target_desc* tdesc_i386_linux