GDBserver: /home/stan/gdb/src/gdb/gdbserver/linux-tile-low.c File Reference
/home/stan/gdb/src/gdb/gdbserver/linux-tile-low.c File Reference
#include "server.h"
#include "linux-low.h"
#include <arch/abi.h>
#include <sys/ptrace.h>
Defines
#define tile_num_regs 65
#define tile_breakpoint_len 8
Functions
void init_registers_tilegx (void)
void init_registers_tilegx32 (void)
static int tile_cannot_fetch_register (int regno)
static int tile_cannot_store_register (int regno)
static CORE_ADDR tile_get_pc (struct regcache *regcache)
static void tile_set_pc (struct regcache *regcache, CORE_ADDR pc)
static int tile_breakpoint_at (CORE_ADDR where)
static void tile_fill_gregset (struct regcache *regcache, void *buf)
static void tile_store_gregset (struct regcache *regcache, const void *buf)
static struct regs_info * tile_regs_info (void)
static void tile_arch_setup (void)
void initialize_low_arch (void)
Variables
struct target_desc * tdesc_tilegx
struct target_desc * tdesc_tilegx32
static int tile_regmap []
static uint64_t tile_breakpoint = 0x400b3cae70166000ULL
static struct regset_info tile_regsets []
static struct regsets_info tile_regsets_info
static struct usrregs_info tile_usrregs_info
static struct regs_info regs_info
struct linux_target_ops the_low_target
Define Documentation
#define tile_breakpoint_len 8
Definition at line 89 of file linux-tile-low.c.
#define tile_num_regs 65
Definition at line 34 of file linux-tile-low.c.
Referenced by tile_fill_gregset(), and tile_store_gregset().
Function Documentation
void init_registers_tilegx (void)
Referenced by initialize_low_arch().
void init_registers_tilegx32 (void)
Referenced by initialize_low_arch().
void initialize_low_arch (void)
Definition at line 193 of file linux-tile-low.c.
References init_registers_tilegx(), init_registers_tilegx32(), and tile_regsets_info.
static void tile_arch_setup (void) [static]
Definition at line 159 of file linux-tile-low.c.
References _, current_inferior, current_process(), error(), get_thread_lwp, linux_pid_exe_is_elf_64_file(), pid_of, and process_info::tdesc.
static int tile_breakpoint_at (CORE_ADDR where) [static]
Definition at line 92 of file linux-tile-low.c.
References target_ops::read_memory, the_target, and tile_breakpoint.
static int tile_cannot_fetch_register (int regno) [static]
Definition at line 50 of file linux-tile-low.c.
static int tile_cannot_store_register (int regno) [static]
Definition at line 61 of file linux-tile-low.c.
static void tile_fill_gregset (struct regcache * regcache, void * buf) [static]
Definition at line 106 of file linux-tile-low.c.
References collect_register(), tile_num_regs, and tile_regmap.
static CORE_ADDR tile_get_pc (struct regcache * regcache) [static]
Definition at line 72 of file linux-tile-low.c.
References collect_register_by_name().
static struct regs_info* tile_regs_info (void) [static, read]
Definition at line 153 of file linux-tile-low.c.
References regs_info.
static void tile_set_pc (struct regcache * regcache, CORE_ADDR pc) [static]
Definition at line 81 of file linux-tile-low.c.
References supply_register_by_name().
static void tile_store_gregset (struct regcache * regcache, const void * buf) [static]
Definition at line 116 of file linux-tile-low.c.
References supply_register(), tile_num_regs, and tile_regmap.
Variable Documentation
struct regs_info regs_info [static]
Initial value:
  {
    NULL,
    &tile_usrregs_info,
    &tile_regsets_info,
  }
Definition at line 145 of file linux-tile-low.c.
Referenced by tile_regs_info().
struct target_desc* tdesc_tilegx
struct target_desc* tdesc_tilegx32
struct linux_target_ops the_low_target
Initial value:
{
  tile_arch_setup,
  tile_regs_info,
  tile_cannot_fetch_register,
  tile_cannot_store_register,
  NULL,
  tile_get_pc,
  tile_set_pc,
  (const unsigned char *) &tile_breakpoint,
  tile_breakpoint_len,
  NULL,
  0,
  tile_breakpoint_at,
}
Definition at line 176 of file linux-tile-low.c.
uint64_t tile_breakpoint = 0x400b3cae70166000ULL [static]
Definition at line 88 of file linux-tile-low.c.
Referenced by tile_breakpoint_at().
int tile_regmap[] [static]
Initial value:
{
   0,  1,  2,  3,  4,  5,  6,  7,
   8,  9, 10, 11, 12, 13, 14, 15,
  16, 17, 18, 19, 20, 21, 22, 23,
  24, 25, 26, 27, 28, 29, 30, 31,
  32, 33, 34, 35, 36, 37, 38, 39,
  40, 41, 42, 43, 44, 45, 46, 47,
  48, 49, 50, 51, 52, 53, 54, 55,
  -1, -1, -1, -1, -1, -1, -1, -1,
  56
}
Definition at line 36 of file linux-tile-low.c.
Referenced by tile_fill_gregset(), and tile_store_gregset().
struct regset_info tile_regsets[] [static]
Initial value:
{
  { PTRACE_GETREGS, PTRACE_SETREGS, 0, tile_num_regs * 8,
    GENERAL_REGS, tile_fill_gregset, tile_store_gregset },
  { 0, 0, 0, -1, -1, NULL, NULL }
}
Definition at line 125 of file linux-tile-low.c.
struct regsets_info tile_regsets_info [static]
Initial value:
  {
    tile_regsets,
    0,
    NULL,
  }
Definition at line 132 of file linux-tile-low.c.
Referenced by initialize_low_arch().
struct usrregs_info tile_usrregs_info [static]
Initial value:
  {
    tile_num_regs,
    tile_regmap,
  }
Definition at line 139 of file linux-tile-low.c.