GDBserver: /home/stan/gdb/src/gdb/gdbserver/linux-cris-low.c File Reference
/home/stan/gdb/src/gdb/gdbserver/linux-cris-low.c File Reference
#include "server.h"
#include "linux-low.h"
#include <sys/ptrace.h>
Defines
#define cris_num_regs 32
#define cris_breakpoint_len 2
Functions
void init_registers_cris (void)
static int cris_cannot_store_register (int regno)
static int cris_cannot_fetch_register (int regno)
static CORE_ADDR cris_get_pc (struct regcache *regcache, void)
static void cris_set_pc (struct regcache *regcache, CORE_ADDR pc)
static int cris_breakpoint_at (CORE_ADDR where)
static CORE_ADDR cris_reinsert_addr (void)
static void cris_arch_setup (void)
static struct regs_info * cris_regs_info (void)
void initialize_low_arch (void)
Variables
struct target_desc * tdesc_cris
static int cris_regmap []
int debug_threads
static const unsigned short cris_breakpoint = 0xe938
static struct usrregs_info cris_usrregs_info
static struct regs_info regs_info
struct linux_target_ops the_low_target
Define Documentation
#define cris_breakpoint_len 2
Definition at line 82 of file linux-cris-low.c.
Referenced by cris_breakpoint_at().
#define cris_num_regs 32
Definition at line 28 of file linux-cris-low.c.
Referenced by cris_cannot_fetch_register(), and cris_cannot_store_register().
Function Documentation
static void cris_arch_setup (void) [static]
Definition at line 112 of file linux-cris-low.c.
References current_process(), and process_info::tdesc.
static int cris_breakpoint_at (CORE_ADDR where) [static]
Definition at line 85 of file linux-cris-low.c.
References cris_breakpoint, cris_breakpoint_len, target_ops::read_memory, and the_target.
static int cris_cannot_fetch_register (int regno) [static]
Definition at line 54 of file linux-cris-low.c.
References cris_num_regs, and cris_regmap.
static int cris_cannot_store_register (int regno) [static]
Definition at line 45 of file linux-cris-low.c.
References cris_num_regs, and cris_regmap.
static CORE_ADDR cris_get_pc (struct regcache * regcache, void) [static]
Definition at line 65 of file linux-cris-low.c.
References collect_register_by_name(), and debug_threads.
static struct regs_info* cris_regs_info (void) [static, read]
Definition at line 130 of file linux-cris-low.c.
References regs_info.
static CORE_ADDR cris_reinsert_addr (void) [static]
Definition at line 103 of file linux-cris-low.c.
References collect_register_by_name(), current_inferior, and get_thread_regcache().
static void cris_set_pc (struct regcache * regcache, CORE_ADDR pc) [static]
Definition at line 75 of file linux-cris-low.c.
References supply_register_by_name().
void init_registers_cris (void)
Referenced by initialize_low_arch().
void initialize_low_arch (void)
Definition at line 155 of file linux-cris-low.c.
References init_registers_cris().
Variable Documentation
const unsigned short cris_breakpoint = 0xe938 [static]
Definition at line 81 of file linux-cris-low.c.
Referenced by cris_breakpoint_at().
int cris_regmap[] [static]
Initial value:
 {
  15*4, 14*4, 13*4, 12*4,
  11*4, 10*4, 9*4, 8*4,
  7*4, 6*4, 5*4, 4*4,
  3*4, 2*4, 23*4, 19*4,
  -1, -1, -1, -1,
  -1, 17*4, -1, 16*4,
  -1, -1, -1, 18*4,
  -1, 17*4, -1, -1
}
Definition at line 31 of file linux-cris-low.c.
Referenced by cris_cannot_fetch_register(), and cris_cannot_store_register().
struct usrregs_info cris_usrregs_info [static]
Initial value:
  {
    cris_num_regs,
    cris_regmap,
  }
Definition at line 117 of file linux-cris-low.c.
int debug_threads
Definition at line 71 of file server.c.
struct regs_info regs_info [static]
Initial value:
  {
    NULL,
    &cris_usrregs_info,
  }
Definition at line 123 of file linux-cris-low.c.
Referenced by cris_regs_info().
struct target_desc* tdesc_cris
struct linux_target_ops the_low_target
Initial value:
 {
  cris_arch_setup,
  cris_regs_info,
  cris_cannot_fetch_register,
  cris_cannot_store_register,
  NULL,
  cris_get_pc,
  cris_set_pc,
  (const unsigned char *) &cris_breakpoint,
  cris_breakpoint_len,
  cris_reinsert_addr,
  0,
  cris_breakpoint_at,
  0,
  0,
  0,
  0,
}
Definition at line 135 of file linux-cris-low.c.