GDBserver: /home/stan/gdb/src/gdb/nat/linux-waitpid.c File Reference
/home/stan/gdb/src/gdb/nat/linux-waitpid.c File Reference
#include "defs.h"
#include "signal.h"
#include "nat/linux-nat.h"
#include "nat/linux-waitpid.h"
#include "gdb_wait.h"
Functions
static void linux_debug (const char *format,...)
int my_waitpid (int pid, int *status, int flags)
Function Documentation
static void linux_debug (const char * format, ...) [inline, static]
Definition at line 35 of file linux-waitpid.c.
References debug_threads.
Referenced by my_waitpid().
int my_waitpid (int pid, int * status, int flags)
Definition at line 55 of file linux-waitpid.c.
References errno, and linux_debug().
Referenced by handle_extended_wait(), linux_check_ptrace_features(), linux_join(), linux_test_for_tracefork(), and linux_wait_for_lwp().