GDBserver: /home/stan/gdb/src/gdb/gdbserver/linux-low.h File Reference
/home/stan/gdb/src/gdb/gdbserver/linux-low.h File Reference
#include "gdb_thread_db.h"
#include <signal.h>
#include "gdbthread.h"
#include "gdb_proc_service.h"
#include "linux-ptrace.h"
Classes
struct usrregs_info
struct regs_info
struct process_info_private
struct linux_target_ops
struct lwp_info
Defines
#define PTRACE_XFER_TYPE long
#define ptid_of(proc) ((proc)->head.id)
#define pid_of(proc) ptid_get_pid ((proc)->head.id)
#define lwpid_of(proc) ptid_get_lwp ((proc)->head.id)
#define get_lwp(inf) ((struct lwp_info *)(inf))
#define get_thread_lwp(thr) (get_lwp (inferior_target_data (thr)))
#define get_lwp_thread(proc)
Functions
int linux_pid_exe_is_elf_64_file (int pid, unsigned int *machine)
void linux_attach_lwp (unsigned long pid)
struct lwp_info * find_lwp_pid (ptid_t ptid)
void linux_stop_lwp (struct lwp_info *lwp)
void initialize_low_arch (void)
int thread_db_init (int use_events)
void thread_db_detach (struct process_info *)
void thread_db_mourn (struct process_info *)
int thread_db_handle_monitor_command (char *)
int thread_db_get_tls_address (struct thread_info *thread, CORE_ADDR offset, CORE_ADDR load_module, CORE_ADDR *address)
int thread_db_look_up_one_symbol (const char *name, CORE_ADDR *addrp)
Variables
struct linux_target_ops the_low_target
struct inferior_list all_lwps
Define Documentation
#define get_lwp (inf) ((struct lwp_info *)(inf))
Definition at line 230 of file linux-low.h.
#define get_lwp_thread (proc)
Value:
((struct thread_info *)                 \
                              find_inferior_id (&all_threads,           \
                                                get_lwp (proc)->head.id))
Definition at line 232 of file linux-low.h.
Referenced by cancel_breakpoint(), cancel_breakpoints_callback(), count_events_callback(), delete_lwp(), get_pc(), handle_tracepoints(), linux_detach_one_lwp(), linux_resume_one_lwp(), linux_wait_1(), linux_wait_for_event(), linux_wait_for_lwp(), maybe_move_out_of_jump_pad(), move_out_of_jump_pad_callback(), need_step_over_p(), proceed_one_lwp(), ps_lgetregs(), select_event_lwp_callback(), select_singlestep_lwp_callback(), start_step_over(), status_pending_p_callback(), stuck_in_jump_pad_callback(), and x86_get_thread_area().
#define get_thread_lwp (thr) (get_lwp (inferior_target_data (thr)))
Definition at line 231 of file linux-low.h.
Referenced by aarch64_arch_setup(), aarch64_notify_debug_reg_change(), aarch64_stopped_data_address(), arm_read_description(), arm_stopped_by_watchpoint(), arm_stopped_data_address(), find_one_thread(), get_detach_signal(), i386_dr_low_get_addr(), i386_dr_low_get_control(), i386_dr_low_get_status(), i386_dr_low_set_addr(), i386_dr_low_set_control(), kill_one_lwp_callback(), linux_attach_lwp_1(), linux_detach_one_lwp(), linux_qxfer_libraries_svr4(), linux_qxfer_spu(), linux_read_auxv(), linux_read_memory(), linux_request_interrupt(), linux_resume_one_thread(), linux_set_resume_request(), linux_stabilize_threads(), linux_stopped_by_watchpoint(), linux_stopped_data_address(), linux_thread_stopped(), linux_wait_1(), linux_wait_for_event(), linux_write_memory(), linux_xfer_siginfo(), mips_insert_point(), mips_read_description(), mips_stopped_by_watchpoint(), mips_stopped_data_address(), ps_getpid(), s390_arch_setup(), thread_db_create_event(), thread_db_get_tls_address(), tile_arch_setup(), update_registers_callback(), x86_linux_read_description(), and x86_siginfo_fixup().
#define lwpid_of (proc) ptid_get_lwp ((proc)->head.id)
Definition at line 228 of file linux-low.h.
Referenced by aarch64_arch_setup(), aarch64_linux_prepare_to_resume(), aarch64_stopped_data_address(), arm_prepare_to_resume(), arm_read_description(), arm_stopped_by_watchpoint(), debug_reg_change_callback(), dequeue_one_deferred_signal(), enqueue_one_deferred_signal(), handle_extended_wait(), kill_one_lwp_callback(), linux_detach_one_lwp(), linux_fast_tracepoint_collecting(), linux_kill(), linux_kill_one_lwp(), linux_qxfer_libraries_svr4(), linux_qxfer_spu(), linux_read_auxv(), linux_read_memory(), linux_request_interrupt(), linux_resume_one_lwp(), linux_resume_one_thread(), linux_set_resume_request(), linux_stabilize_threads(), linux_wait_1(), linux_wait_for_event(), linux_write_memory(), linux_xfer_siginfo(), maybe_move_out_of_jump_pad(), mips_insert_point(), mips_read_description(), mips_stopped_by_watchpoint(), mips_stopped_data_address(), move_out_of_jump_pad_callback(), need_step_over_p(), proceed_all_lwps(), proceed_one_lwp(), send_sigstop(), start_step_over(), unstop_all_lwps(), wait_for_sigstop(), x86_get_thread_area(), x86_linux_read_description(), and x86_siginfo_fixup().
#define pid_of (proc) ptid_get_pid ((proc)->head.id)
Definition at line 227 of file linux-low.h.
Referenced by aarch64_notify_debug_reg_change(), arm_prepare_to_resume(), debug_reg_change_callback(), delete_lwp_callback(), handle_extended_wait(), i386_dr_low_set_addr(), i386_dr_low_set_control(), linux_attach_lwp_1(), linux_set_resume_request(), linux_wait_for_lwp(), mips_insert_point(), mips_remove_point(), ps_getpid(), s390_arch_setup(), switch_to_process(), tile_arch_setup(), update_debug_registers_callback(), update_registers_callback(), and update_watch_registers_callback().
#define ptid_of (proc) ((proc)->head.id)
Definition at line 226 of file linux-low.h.
Referenced by aarch64_linux_prepare_to_resume(), cancel_breakpoint(), get_detach_signal(), i386_dr_low_get_addr(), i386_dr_low_get_control(), i386_dr_low_get_status(), linux_detach_one_lwp(), linux_kill_one_lwp(), linux_wait_1(), linux_wait_for_event(), mips_linux_prepare_to_resume(), select_event_lwp(), and x86_linux_prepare_to_resume().
#define PTRACE_XFER_TYPE long
Definition at line 28 of file linux-low.h.
Referenced by linux_read_memory(), and linux_write_memory().
Function Documentation
struct lwp_info* find_lwp_pid (ptid_t ptid) [read]
Definition at line 1266 of file linux-low.c.
References all_lwps, find_inferior(), and same_lwp().
Referenced by attach_thread(), linux_kill(), linux_thread_alive(), linux_wait_for_event(), linux_wait_for_lwp(), maybe_attach_thread(), ps_lgetregs(), wait_for_sigstop(), and x86_get_thread_area().
void initialize_low_arch (void)
Definition at line 1305 of file linux-aarch64-low.c.
References arm_regsets_info, copy_target_description(), cris_regsets_info, init_registers_aarch64(), init_registers_amd64_linux(), init_registers_arm(), init_registers_arm_with_iwmmxt(), init_registers_arm_with_neon(), init_registers_arm_with_vfpv2(), init_registers_arm_with_vfpv3(), init_registers_bfin(), init_registers_cris(), init_registers_crisv32(), init_registers_i386_avx_linux(), init_registers_i386_linux(), init_registers_i386_mmx_linux(), init_registers_ia64(), init_registers_m32r(), init_registers_m68k(), init_registers_mips64_dsp_linux(), init_registers_mips64_linux(), init_registers_mips_dsp_linux(), init_registers_mips_linux(), init_registers_nios2_linux(), init_registers_powerpc_32l(), init_registers_powerpc_64l(), init_registers_powerpc_altivec32l(), init_registers_powerpc_altivec64l(), init_registers_powerpc_cell32l(), init_registers_powerpc_cell64l(), init_registers_powerpc_e500l(), init_registers_powerpc_isa205_32l(), init_registers_powerpc_isa205_64l(), init_registers_powerpc_isa205_altivec32l(), init_registers_powerpc_isa205_altivec64l(), init_registers_powerpc_isa205_vsx32l(), init_registers_powerpc_isa205_vsx64l(), init_registers_powerpc_vsx32l(), init_registers_powerpc_vsx64l(), init_registers_s390_linux32(), init_registers_s390_linux32v1(), init_registers_s390_linux32v2(), init_registers_s390_linux64(), init_registers_s390_linux64v1(), init_registers_s390_linux64v2(), init_registers_s390_te_linux64(), init_registers_s390x_linux64(), init_registers_s390x_linux64v1(), init_registers_s390x_linux64v2(), init_registers_s390x_te_linux64(), init_registers_sh(), init_registers_sparc64(), init_registers_tic6x_c62x_linux(), init_registers_tic6x_c64x_linux(), init_registers_tic6x_c64xp_linux(), init_registers_tilegx(), init_registers_tilegx32(), init_registers_xtensa(), ppc_regsets_info, sh_regsets_info, tic6x_regsets_info, tile_regsets_info, xmalloc(), target_desc::xmltarget, and xmltarget_i386_linux_no_xml.
Referenced by initialize_low().
void linux_attach_lwp (unsigned long pid)
Definition at line 758 of file linux-low.c.
References linux_attach_lwp_1().
Referenced by attach_thread().
int linux_pid_exe_is_elf_64_file (int pid, unsigned int * machine)
Definition at line 338 of file linux-low.c.
References elf_64_file_p().
Referenced by tile_arch_setup(), x86_linux_read_description(), and x86_siginfo_fixup().
void linux_stop_lwp (struct lwp_info * lwp)
Definition at line 2823 of file linux-low.c.
References send_sigstop().
Referenced by debug_reg_change_callback(), update_debug_registers_callback(), update_registers_callback(), and update_watch_registers_callback().
void thread_db_detach (struct process_info *)
Definition at line 903 of file thread-db.c.
References disable_thread_event_reporting(), process_info::private, remove_thread_event_breakpoints(), and process_info_private::thread_db.
Referenced by linux_detach().
int thread_db_get_tls_address (struct thread_info * thread, CORE_ADDR offset, CORE_ADDR load_module, CORE_ADDR * address)
Definition at line 483 of file thread-db.c.
References thread_db::all_symbols_looked_up, current_inferior, find_one_thread(), get_thread_lwp, get_thread_process(), lwp_info::head, inferior_list_entry::id, process_info::private, TD_ERR, TD_NOTHR, TD_OK, thread_db::td_thr_tls_get_addr_p, and process_info_private::thread_db.
int thread_db_handle_monitor_command (char *)
Definition at line 946 of file thread-db.c.
References libthread_db_search_path, monitor_output(), and xstrdup().
int thread_db_init (int use_events)
Definition at line 796 of file thread-db.c.
References current_process(), thread_db_enable_reporting(), thread_db_find_new_threads(), thread_db_load_search(), thread_db_look_up_symbols(), thread_db_mourn(), and thread_db_use_events.
Referenced by linux_look_up_symbols().
int thread_db_look_up_one_symbol (const char * name, CORE_ADDR * addrp)
Definition at line 469 of file thread-db.c.
References thread_db::all_symbols_looked_up, current_process(), look_up_one_symbol(), process_info::private, and process_info_private::thread_db.
Referenced by ps_pglobal_lookup().
void thread_db_mourn (struct process_info *)
Definition at line 917 of file thread-db.c.
References thread_db::handle, process_info::private, td_ta_delete(), thread_db::thread_agent, and process_info_private::thread_db.
Referenced by linux_mourn(), and thread_db_init().
Variable Documentation
struct inferior_list all_lwps
Definition at line 150 of file linux-low.c.
Referenced by aarch64_notify_debug_reg_change(), add_lwp(), arm_insert_point(), arm_remove_point(), delete_lwp(), find_lwp_pid(), i386_dr_low_set_addr(), i386_dr_low_set_control(), linux_cancel_breakpoints(), linux_mourn(), linux_resume(), linux_stabilize_threads(), linux_wait_1(), linux_wait_for_event(), mips_insert_point(), mips_remove_point(), proceed_all_lwps(), select_event_lwp(), stop_all_lwps(), unstop_all_lwps(), and unsuspend_all_lwps().
struct linux_target_ops the_low_target
Definition at line 1278 of file linux-aarch64-low.c.