GDBserver: /home/stan/gdb/src/gdb/gdbserver/linux-m68k-low.c File Reference
/home/stan/gdb/src/gdb/gdbserver/linux-m68k-low.c File Reference
#include "server.h"
#include "linux-low.h"
#include <asm/ptrace.h>
Defines
#define m68k_num_regs 29
#define m68k_num_gregs 18
#define m68k_breakpoint_len 2
Functions
void init_registers_m68k (void)
static int m68k_cannot_store_register (int regno)
static int m68k_cannot_fetch_register (int regno)
static CORE_ADDR m68k_get_pc (struct regcache *regcache)
static void m68k_set_pc (struct regcache *regcache, CORE_ADDR value)
static int m68k_breakpoint_at (CORE_ADDR pc)
static struct regs_info * m68k_regs_info (void)
static void m68k_arch_setup (void)
void initialize_low_arch (void)
Variables
struct target_desc * tdesc_m68k
static int m68k_regmap []
static struct regset_info m68k_regsets []
static const unsigned char m68k_breakpoint [] = { 0x4E, 0x4F }
static struct regsets_info m68k_regsets_info
static struct usrregs_info m68k_usrregs_info
static struct regs_info regs_info
struct linux_target_ops the_low_target
Define Documentation
#define m68k_breakpoint_len 2
Definition at line 126 of file linux-m68k-low.c.
#define m68k_num_gregs 18
Definition at line 31 of file linux-m68k-low.c.
#define m68k_num_regs 29
Definition at line 30 of file linux-m68k-low.c.
Referenced by m68k_cannot_fetch_register(), and m68k_cannot_store_register().
Function Documentation
void init_registers_m68k (void)
Referenced by initialize_low_arch().
void initialize_low_arch (void)
Definition at line 226 of file linux-m68k-low.c.
References init_registers_m68k().
static void m68k_arch_setup (void) [static]
Definition at line 205 of file linux-m68k-low.c.
References current_process(), and process_info::tdesc.
static int m68k_breakpoint_at (CORE_ADDR pc) [static]
Definition at line 146 of file linux-m68k-low.c.
References read_inferior_memory().
static int m68k_cannot_fetch_register (int regno) [static]
Definition at line 64 of file linux-m68k-low.c.
References m68k_num_regs.
static int m68k_cannot_store_register (int regno) [static]
Definition at line 58 of file linux-m68k-low.c.
References m68k_num_regs.
static CORE_ADDR m68k_get_pc (struct regcache * regcache) [static]
Definition at line 129 of file linux-m68k-low.c.
References collect_register_by_name().
static struct regs_info* m68k_regs_info (void) [static, read]
Definition at line 199 of file linux-m68k-low.c.
References regs_info.
static void m68k_set_pc (struct regcache * regcache, CORE_ADDR value) [static]
Definition at line 138 of file linux-m68k-low.c.
References supply_register_by_name().
Variable Documentation
const unsigned char m68k_breakpoint[] = { 0x4E, 0x4F } [static]
Definition at line 125 of file linux-m68k-low.c.
int m68k_regmap[] [static]
Initial value:
{
  14 * 4, 0 * 4, 1 * 4, 2 * 4, 3 * 4, 4 * 4, 5 * 4, 6 * 4,
  7 * 4, 8 * 4, 9 * 4, 10 * 4, 11 * 4, 12 * 4, 13 * 4, 15 * 4,
  17 * 4, 18 * 4,
  21 * 4, 24 * 4, 27 * 4, 30 * 4, 33 * 4, 36 * 4,
  39 * 4, 42 * 4, 45 * 4, 46 * 4, 47 * 4
}
Definition at line 34 of file linux-m68k-low.c.
struct regset_info m68k_regsets[] [static]
Initial value:
 {
  { 0, 0, 0, -1, -1, NULL, NULL }
}
Definition at line 113 of file linux-m68k-low.c.
struct regsets_info m68k_regsets_info [static]
Initial value:
  {
    m68k_regsets,
    0,
    NULL,
  }
Definition at line 178 of file linux-m68k-low.c.
struct usrregs_info m68k_usrregs_info [static]
Initial value:
  {
    m68k_num_regs,
    m68k_regmap,
  }
Definition at line 185 of file linux-m68k-low.c.
struct regs_info regs_info [static]
Initial value:
  {
    NULL,
    &m68k_usrregs_info,
    &m68k_regsets_info
  }
Definition at line 191 of file linux-m68k-low.c.
Referenced by m68k_regs_info().
struct target_desc* tdesc_m68k
struct linux_target_ops the_low_target
Initial value:
 {
  m68k_arch_setup,
  m68k_regs_info,
  m68k_cannot_fetch_register,
  m68k_cannot_store_register,
  NULL,
  m68k_get_pc,
  m68k_set_pc,
  m68k_breakpoint,
  m68k_breakpoint_len,
  NULL,
  2,
  m68k_breakpoint_at,
}
Definition at line 210 of file linux-m68k-low.c.