GDBserver: /home/stan/gdb/src/gdb/gdbserver/linux-amd64-ipa.c File Reference
/home/stan/gdb/src/gdb/gdbserver/linux-amd64-ipa.c File Reference
#include "server.h"
#include "tracepoint.h"
Defines
#define FT_CR_RIP 0
#define FT_CR_EFLAGS 1
#define FT_CR_R8 2
#define FT_CR_R9 3
#define FT_CR_R10 4
#define FT_CR_R11 5
#define FT_CR_R12 6
#define FT_CR_R13 7
#define FT_CR_R14 8
#define FT_CR_R15 9
#define FT_CR_RAX 10
#define FT_CR_RBX 11
#define FT_CR_RCX 12
#define FT_CR_RDX 13
#define FT_CR_RSI 14
#define FT_CR_RDI 15
#define FT_CR_RBP 16
#define FT_CR_RSP 17
#define X86_64_NUM_FT_COLLECT_GREGS (sizeof (x86_64_ft_collect_regmap) / sizeof(x86_64_ft_collect_regmap[0]))
Functions
void init_registers_amd64_linux (void)
void supply_fast_tracepoint_registers (struct regcache *regcache, const unsigned char *buf)
ULONGEST __attribute__ ((visibility("default"), used))
void initialize_low_tracepoint (void)
Variables
struct target_desc * tdesc_amd64_linux
static const int x86_64_ft_collect_regmap []
Define Documentation
#define FT_CR_EFLAGS 1
Definition at line 31 of file linux-amd64-ipa.c.
#define FT_CR_R10 4
Definition at line 34 of file linux-amd64-ipa.c.
#define FT_CR_R11 5
Definition at line 35 of file linux-amd64-ipa.c.
#define FT_CR_R12 6
Definition at line 36 of file linux-amd64-ipa.c.
#define FT_CR_R13 7
Definition at line 37 of file linux-amd64-ipa.c.
#define FT_CR_R14 8
Definition at line 38 of file linux-amd64-ipa.c.
#define FT_CR_R15 9
Definition at line 39 of file linux-amd64-ipa.c.
#define FT_CR_R8 2
Definition at line 32 of file linux-amd64-ipa.c.
#define FT_CR_R9 3
Definition at line 33 of file linux-amd64-ipa.c.
#define FT_CR_RAX 10
Definition at line 40 of file linux-amd64-ipa.c.
#define FT_CR_RBP 16
Definition at line 46 of file linux-amd64-ipa.c.
#define FT_CR_RBX 11
Definition at line 41 of file linux-amd64-ipa.c.
#define FT_CR_RCX 12
Definition at line 42 of file linux-amd64-ipa.c.
#define FT_CR_RDI 15
Definition at line 45 of file linux-amd64-ipa.c.
#define FT_CR_RDX 13
Definition at line 43 of file linux-amd64-ipa.c.
#define FT_CR_RIP 0
Definition at line 30 of file linux-amd64-ipa.c.
#define FT_CR_RSI 14
Definition at line 44 of file linux-amd64-ipa.c.
#define FT_CR_RSP 17
Definition at line 47 of file linux-amd64-ipa.c.
#define X86_64_NUM_FT_COLLECT_GREGS (sizeof (x86_64_ft_collect_regmap) / sizeof(x86_64_ft_collect_regmap[0]))
Definition at line 57 of file linux-amd64-ipa.c.
Referenced by __attribute__(), and supply_fast_tracepoint_registers().
Function Documentation
ULONGEST __attribute__ ((visibility("default"), used))
Definition at line 71 of file linux-amd64-ipa.c.
References x86_64_ft_collect_regmap, and X86_64_NUM_FT_COLLECT_GREGS.
void init_registers_amd64_linux (void)
Referenced by initialize_low_arch(), and initialize_low_tracepoint().
void initialize_low_tracepoint (void)
Definition at line 170 of file linux-amd64-ipa.c.
References init_registers_amd64_linux().
Referenced by initialize_tracepoint().
void supply_fast_tracepoint_registers (struct regcache * regcache, const unsigned char * buf)
Definition at line 61 of file linux-amd64-ipa.c.
References supply_register(), x86_64_ft_collect_regmap, and X86_64_NUM_FT_COLLECT_GREGS.
Referenced by get_context_regcache().
Variable Documentation
struct target_desc* tdesc_amd64_linux
const int x86_64_ft_collect_regmap[] [static]
Initial value:
 {
  FT_CR_RAX * 8, FT_CR_RBX * 8, FT_CR_RCX * 8, FT_CR_RDX * 8,
  FT_CR_RSI * 8, FT_CR_RDI * 8, FT_CR_RBP * 8, FT_CR_RSP * 8,
  FT_CR_R8 * 8,  FT_CR_R9 * 8,  FT_CR_R10 * 8, FT_CR_R11 * 8,
  FT_CR_R12 * 8, FT_CR_R13 * 8, FT_CR_R14 * 8, FT_CR_R15 * 8,
  FT_CR_RIP * 8, FT_CR_EFLAGS * 8
}
Definition at line 49 of file linux-amd64-ipa.c.
Referenced by __attribute__(), and supply_fast_tracepoint_registers().