GDBserver: /home/stan/gdb/src/gdb/gdbserver/linux-m32r-low.c File Reference
/home/stan/gdb/src/gdb/gdbserver/linux-m32r-low.c File Reference
#include "server.h"
#include "linux-low.h"
Defines
#define m32r_num_regs 25
#define m32r_breakpoint_len 2
Functions
void init_registers_m32r (void)
static int m32r_cannot_store_register (int regno)
static int m32r_cannot_fetch_register (int regno)
static CORE_ADDR m32r_get_pc (struct regcache *regcache)
static void m32r_set_pc (struct regcache *regcache, CORE_ADDR pc)
static int m32r_breakpoint_at (CORE_ADDR where)
static void m32r_arch_setup (void)
static struct regs_info * m32r_regs_info (void)
void initialize_low_arch (void)
Variables
struct target_desc * tdesc_m32r
static int m32r_regmap []
static const unsigned short m32r_breakpoint = 0x10f1
static struct usrregs_info m32r_usrregs_info
static struct regs_info regs_info
struct linux_target_ops the_low_target
Define Documentation
#define m32r_breakpoint_len 2
Definition at line 74 of file linux-m32r-low.c.
Referenced by m32r_breakpoint_at().
#define m32r_num_regs 25
Definition at line 30 of file linux-m32r-low.c.
Referenced by m32r_cannot_fetch_register(), and m32r_cannot_store_register().
Function Documentation
void init_registers_m32r (void)
Referenced by initialize_low_arch().
void initialize_low_arch (void)
Definition at line 131 of file linux-m32r-low.c.
References init_registers_m32r().
static void m32r_arch_setup (void) [static]
Definition at line 92 of file linux-m32r-low.c.
References current_process(), and process_info::tdesc.
static int m32r_breakpoint_at (CORE_ADDR where) [static]
Definition at line 77 of file linux-m32r-low.c.
References m32r_breakpoint, m32r_breakpoint_len, target_ops::read_memory, and the_target.
static int m32r_cannot_fetch_register (int regno) [static]
Definition at line 51 of file linux-m32r-low.c.
References m32r_num_regs.
static int m32r_cannot_store_register (int regno) [static]
Definition at line 45 of file linux-m32r-low.c.
References m32r_num_regs.
static CORE_ADDR m32r_get_pc (struct regcache * regcache) [static]
Definition at line 57 of file linux-m32r-low.c.
References collect_register_by_name(), and debug_threads.
static struct regs_info* m32r_regs_info (void) [static, read]
Definition at line 110 of file linux-m32r-low.c.
References regs_info.
static void m32r_set_pc (struct regcache * regcache, CORE_ADDR pc) [static]
Definition at line 67 of file linux-m32r-low.c.
References supply_register_by_name().
Variable Documentation
const unsigned short m32r_breakpoint = 0x10f1 [static]
Definition at line 73 of file linux-m32r-low.c.
Referenced by m32r_breakpoint_at().
int m32r_regmap[] [static]
Initial value:
 {
  4 * 4, 4 * 5, 4 * 6, 4 * 7, 4 * 0, 4 * 1, 4 * 2, 4 * 8,
  4 * 9, 4 * 10, 4 * 11, 4 * 12, 4 * 13, 4 * 24, 4 * 25, 4 * 23,
  4 * 19, 4 * 31, 4 * 26, 4 * 23, 4 * 20, 4 * 30, 4 * 16, 4 * 15, 4 * 32
}
Definition at line 32 of file linux-m32r-low.c.
struct usrregs_info m32r_usrregs_info [static]
Initial value:
  {
    m32r_num_regs,
    m32r_regmap,
  }
Definition at line 97 of file linux-m32r-low.c.
struct regs_info regs_info [static]
Initial value:
  {
    NULL,
    &m32r_usrregs_info,
  }
Definition at line 103 of file linux-m32r-low.c.
Referenced by m32r_regs_info().
struct target_desc* tdesc_m32r
struct linux_target_ops the_low_target
Initial value:
 {
  m32r_arch_setup,
  m32r_regs_info,
  m32r_cannot_fetch_register,
  m32r_cannot_store_register,
  NULL,
  m32r_get_pc,
  m32r_set_pc,
  (const unsigned char *) &m32r_breakpoint,
  m32r_breakpoint_len,
  NULL,
  0,
  m32r_breakpoint_at,
}
Definition at line 115 of file linux-m32r-low.c.