GDBserver: /home/stan/gdb/src/gdb/common/linux-ptrace.c File Reference
/home/stan/gdb/src/gdb/common/linux-ptrace.c File Reference
#include "defs.h"
#include "gdb_string.h"
#include "linux-ptrace.h"
#include "linux-procfs.h"
#include "nat/linux-waitpid.h"
#include "buffer.h"
#include "gdb_assert.h"
#include "gdb_wait.h"
#include <stdint.h>
Functions
void linux_ptrace_attach_warnings (pid_t pid, struct buffer *buffer)
static void linux_ptrace_test_ret_to_nx (void)
static int linux_fork_to_function (gdb_byte *child_stack, void(*function)(gdb_byte *))
static void linux_grandchild_function (gdb_byte *child_stack)
static void linux_child_function (gdb_byte *child_stack)
static void linux_test_for_tracesysgood (int child_pid)
static void linux_test_for_tracefork (int child_pid)
static void linux_check_ptrace_features (void)
void linux_enable_event_reporting (pid_t pid)
static int ptrace_supports_feature (int ptrace_options)
int linux_supports_tracefork (void)
int linux_supports_traceclone (void)
int linux_supports_tracevforkdone (void)
int linux_supports_tracesysgood (void)
void linux_ptrace_init_warnings (void)
Variables
static int current_ptrace_options = -1
Function Documentation
static void linux_check_ptrace_features (void) [static]
Definition at line 317 of file linux-ptrace.c.
References _, current_ptrace_options, error(), linux_child_function(), linux_fork_to_function(), linux_test_for_tracefork(), linux_test_for_tracesysgood(), my_waitpid(), perror_with_name(), PTRACE_TYPE_ARG3, and warning().
Referenced by linux_enable_event_reporting().
static void linux_child_function (gdb_byte * child_stack) [static]
Definition at line 298 of file linux-ptrace.c.
References linux_fork_to_function(), linux_grandchild_function(), and PTRACE_TYPE_ARG3.
Referenced by linux_check_ptrace_features().
void linux_enable_event_reporting (pid_t pid)
Definition at line 467 of file linux-ptrace.c.
References current_ptrace_options, linux_check_ptrace_features(), and PTRACE_TYPE_ARG3.
Referenced by linux_wait_for_event().
static int linux_fork_to_function (gdb_byte * child_stack, void(*)(gdb_byte *) function) [static]
Definition at line 245 of file linux-ptrace.c.
References gdb_assert, perror_with_name(), and xmalloc().
Referenced by linux_check_ptrace_features(), and linux_child_function().
static void linux_grandchild_function (gdb_byte * child_stack) [static]
Definition at line 283 of file linux-ptrace.c.
References xfree().
Referenced by linux_child_function().
void linux_ptrace_attach_warnings (pid_t pid, struct buffer * buffer)
Definition at line 45 of file linux-ptrace.c.
References _, buffer_xml_printf(), linux_proc_get_tracerpid(), and linux_proc_pid_is_zombie().
Referenced by linux_attach_lwp_1().
void linux_ptrace_init_warnings (void)
Definition at line 535 of file linux-ptrace.c.
References linux_ptrace_test_ret_to_nx().
Referenced by initialize_low().
static void linux_ptrace_test_ret_to_nx (void) [static]
Definition at line 78 of file linux-ptrace.c.
References _, errno, gdb_assert_not_reached, PTRACE_TYPE_ARG3, strerror, and warning().
Referenced by linux_ptrace_init_warnings().
int linux_supports_traceclone (void)
Definition at line 508 of file linux-ptrace.c.
References ptrace_supports_feature().
Referenced by linux_look_up_symbols().
int linux_supports_tracefork (void)
Definition at line 497 of file linux-ptrace.c.
References ptrace_supports_feature().
int linux_supports_tracesysgood (void)
Definition at line 526 of file linux-ptrace.c.
References ptrace_supports_feature().
int linux_supports_tracevforkdone (void)
Definition at line 517 of file linux-ptrace.c.
References ptrace_supports_feature().
static void linux_test_for_tracefork (int child_pid) [static]
Definition at line 378 of file linux-ptrace.c.
References _, current_ptrace_options, my_waitpid(), PTRACE_TYPE_ARG3, and warning().
Referenced by linux_check_ptrace_features().
static void linux_test_for_tracesysgood (int child_pid) [static]
Definition at line 360 of file linux-ptrace.c.
References current_ptrace_options, and PTRACE_TYPE_ARG3.
Referenced by linux_check_ptrace_features().
static int ptrace_supports_feature (int ptrace_options) [static]
Definition at line 484 of file linux-ptrace.c.
References current_ptrace_options, and gdb_assert.
Referenced by linux_supports_traceclone(), linux_supports_tracefork(), linux_supports_tracesysgood(), and linux_supports_tracevforkdone().
Variable Documentation
int current_ptrace_options = -1 [static]
Definition at line 38 of file linux-ptrace.c.
Referenced by linux_check_ptrace_features(), linux_enable_event_reporting(), linux_test_for_tracefork(), linux_test_for_tracesysgood(), and ptrace_supports_feature().