GDBserver: /home/stan/gdb/src/gdb/gdbserver/linux-ia64-low.c File Reference
/home/stan/gdb/src/gdb/gdbserver/linux-ia64-low.c File Reference
#include "server.h"
#include "linux-low.h"
#include <asm/ptrace_offsets.h>
Defines
#define ia64_num_regs 462
#define IA64_GR0_REGNUM 0
#define IA64_FR0_REGNUM 128
#define IA64_FR1_REGNUM 129
Functions
void init_registers_ia64 (void)
static int ia64_cannot_store_register (int regno)
static int ia64_cannot_fetch_register (int regno)
static int ia64_fetch_register (struct regcache *regcache, int regnum)
static struct regs_info * ia64_regs_info (void)
static void ia64_arch_setup (void)
void initialize_low_arch (void)
Variables
struct target_desc * tdesc_ia64
static int ia64_regmap []
static struct usrregs_info ia64_usrregs_info
static struct regs_info regs_info
struct linux_target_ops the_low_target
Define Documentation
#define IA64_FR0_REGNUM 128
Definition at line 283 of file linux-ia64-low.c.
Referenced by ia64_fetch_register().
#define IA64_FR1_REGNUM 129
Definition at line 284 of file linux-ia64-low.c.
Referenced by ia64_fetch_register().
#define IA64_GR0_REGNUM 0
Definition at line 282 of file linux-ia64-low.c.
Referenced by ia64_fetch_register().
#define ia64_num_regs 462
Definition at line 30 of file linux-ia64-low.c.
Function Documentation
static void ia64_arch_setup (void) [static]
Definition at line 342 of file linux-ia64-low.c.
References current_process(), and process_info::tdesc.
static int ia64_cannot_fetch_register (int regno) [static]
Definition at line 276 of file linux-ia64-low.c.
static int ia64_cannot_store_register (int regno) [static]
Definition at line 270 of file linux-ia64-low.c.
static int ia64_fetch_register (struct regcache * regcache, int regnum) [static]
Definition at line 287 of file linux-ia64-low.c.
References gdb_assert, IA64_FR0_REGNUM, IA64_FR1_REGNUM, IA64_GR0_REGNUM, register_size(), supply_register(), and regcache::tdesc.
static struct regs_info* ia64_regs_info (void) [static, read]
Definition at line 336 of file linux-ia64-low.c.
References regs_info.
void init_registers_ia64 (void)
Referenced by initialize_low_arch().
void initialize_low_arch (void)
Definition at line 357 of file linux-ia64-low.c.
References init_registers_ia64().
Variable Documentation
int ia64_regmap[] [static]
Definition at line 34 of file linux-ia64-low.c.
struct usrregs_info ia64_usrregs_info [static]
Initial value:
  {
    ia64_num_regs,
    ia64_regmap,
  }
Definition at line 323 of file linux-ia64-low.c.
struct regs_info regs_info [static]
Initial value:
  {
    NULL,
    &ia64_usrregs_info
  }
Definition at line 329 of file linux-ia64-low.c.
Referenced by ia64_regs_info().
struct target_desc* tdesc_ia64
struct linux_target_ops the_low_target
Initial value:
 {
  ia64_arch_setup,
  ia64_regs_info,
  ia64_cannot_fetch_register,
  ia64_cannot_store_register,
  ia64_fetch_register,
}
Definition at line 348 of file linux-ia64-low.c.