GDBserver: /home/stan/gdb/src/gdb/gdbserver/linux-nios2-low.c File Reference
/home/stan/gdb/src/gdb/gdbserver/linux-nios2-low.c File Reference
#include "server.h"
#include "linux-low.h"
#include <sys/ptrace.h>
#include <endian.h>
#include "gdb_proc_service.h"
#include <asm/ptrace.h>
Classes
union nios2_register
Defines
#define PTRACE_GET_THREAD_AREA 25
#define nios2_num_regs 49
#define nios2_breakpoint_len 4
Functions
void init_registers_nios2_linux (void)
static void nios2_arch_setup (void)
static int nios2_cannot_fetch_register (int regno)
static int nios2_cannot_store_register (int regno)
static CORE_ADDR nios2_get_pc (struct regcache *regcache)
static void nios2_set_pc (struct regcache *regcache, CORE_ADDR pc)
static CORE_ADDR nios2_reinsert_addr (void)
static int nios2_breakpoint_at (CORE_ADDR where)
ps_err_e ps_get_thread_area (const struct ps_prochandle *ph, lwpid_t lwpid, int idx, void **base)
static struct regs_info * nios2_regs_info (void)
void initialize_low_arch (void)
Variables
struct target_desc * tdesc_nios2_linux
static int nios2_regmap []
static const unsigned int nios2_breakpoint = 0x003b6ffa
static struct regset_info nios2_regsets []
static struct regsets_info nios2_regsets_info
static struct usrregs_info nios2_usrregs_info
static struct regs_info regs_info
struct linux_target_ops the_low_target
Define Documentation
#define nios2_breakpoint_len 4
Definition at line 122 of file linux-nios2-low.c.
#define nios2_num_regs 49
Definition at line 38 of file linux-nios2-low.c.
#define PTRACE_GET_THREAD_AREA 25
Definition at line 30 of file linux-nios2-low.c.
Referenced by ps_get_thread_area().
Function Documentation
void init_registers_nios2_linux (void)
Referenced by initialize_low_arch().
void initialize_low_arch (void)
Definition at line 262 of file linux-nios2-low.c.
References init_registers_nios2_linux().
static void nios2_arch_setup (void) [static]
Definition at line 70 of file linux-nios2-low.c.
References current_process(), and process_info::tdesc.
static int nios2_breakpoint_at (CORE_ADDR where) [static]
Definition at line 139 of file linux-nios2-low.c.
References nios2_breakpoint, target_ops::read_memory, and the_target.
static int nios2_cannot_fetch_register (int regno) [static]
Definition at line 78 of file linux-nios2-low.c.
References nios2_regmap.
static int nios2_cannot_store_register (int regno) [static]
Definition at line 89 of file linux-nios2-low.c.
References nios2_regmap.
static CORE_ADDR nios2_get_pc (struct regcache * regcache) [static]
Definition at line 100 of file linux-nios2-low.c.
References nios2_register::buf, collect_register_by_name(), and nios2_register::reg32.
static struct regs_info* nios2_regs_info (void) [static, read]
Definition at line 240 of file linux-nios2-low.c.
References regs_info.
static CORE_ADDR nios2_reinsert_addr (void) [static]
Definition at line 127 of file linux-nios2-low.c.
References nios2_register::buf, collect_register_by_name(), current_inferior, get_thread_regcache(), and nios2_register::reg32.
static void nios2_set_pc (struct regcache * regcache, CORE_ADDR pc) [static]
Definition at line 111 of file linux-nios2-low.c.
References nios2_register::buf, nios2_register::reg32, and supply_register_by_name().
ps_err_e ps_get_thread_area (const struct ps_prochandle * ph, lwpid_t lwpid, int idx, void ** base)
Definition at line 152 of file linux-nios2-low.c.
References PS_ERR, PS_OK, and PTRACE_GET_THREAD_AREA.
Variable Documentation
const unsigned int nios2_breakpoint = 0x003b6ffa [static]
Definition at line 121 of file linux-nios2-low.c.
Referenced by nios2_breakpoint_at().
int nios2_regmap[] [static]
Initial value:
 {
  -1,  1,  2,  3,  4,  5,  6,  7,
  8,  9,  10, 11, 12, 13, 14, 15,
  16, 17, 18, 19, 20, 21, 22, 23,
  24, 25, 26, 27, 28, 29, 30, 31,
  32, 33, 34, 35, 36, 37, 38, 39,
  40, 41, 42, 43, 44, 45, 46, 47,
  48,
  0
}
Definition at line 56 of file linux-nios2-low.c.
Referenced by nios2_cannot_fetch_register(), and nios2_cannot_store_register().
struct regset_info nios2_regsets[] [static]
Initial value:
{
  { 0, 0, 0, -1, -1, NULL, NULL }
}
Definition at line 210 of file linux-nios2-low.c.
struct regsets_info nios2_regsets_info [static]
Initial value:
  {
    nios2_regsets,
    0,
    NULL,
  }
Definition at line 219 of file linux-nios2-low.c.
struct usrregs_info nios2_usrregs_info [static]
Initial value:
  {
    nios2_num_regs,
    nios2_regmap,
  }
Definition at line 226 of file linux-nios2-low.c.
struct regs_info regs_info [static]
Initial value:
  {
    NULL,
    &nios2_usrregs_info,
    &nios2_regsets_info
  }
Definition at line 232 of file linux-nios2-low.c.
Referenced by nios2_regs_info().
struct target_desc* tdesc_nios2_linux
struct linux_target_ops the_low_target
Initial value:
{
  nios2_arch_setup,
  nios2_regs_info,
  nios2_cannot_fetch_register,
  nios2_cannot_store_register,
  NULL,
  nios2_get_pc,
  nios2_set_pc,
  (const unsigned char *) &nios2_breakpoint,
  nios2_breakpoint_len,
  nios2_reinsert_addr,
  0,
  nios2_breakpoint_at,
}
Definition at line 245 of file linux-nios2-low.c.