GDBserver: /home/stan/gdb/src/gdb/gdbserver/linux-bfin-low.c File Reference
/home/stan/gdb/src/gdb/gdbserver/linux-bfin-low.c File Reference
#include "server.h"
#include "linux-low.h"
#include "libiberty.h"
#include <asm/ptrace.h>
Defines
#define bfin_num_regs ARRAY_SIZE (bfin_regmap)
#define bfin_breakpoint_len 2
Functions
void init_registers_bfin (void)
static int bfin_cannot_store_register (int regno)
static int bfin_cannot_fetch_register (int regno)
static CORE_ADDR bfin_get_pc (struct regcache *regcache)
static void bfin_set_pc (struct regcache *regcache, CORE_ADDR pc)
static int bfin_breakpoint_at (CORE_ADDR where)
static void bfin_arch_setup (void)
static struct regs_info * bfin_regs_info (void)
void initialize_low_arch (void)
Variables
struct target_desc * tdesc_bfin
static int bfin_regmap []
static const unsigned char bfin_breakpoint [bfin_breakpoint_len] = {0xa1, 0x00}
static struct usrregs_info bfin_usrregs_info
static struct regs_info regs_info
struct linux_target_ops the_low_target
Define Documentation
#define bfin_breakpoint_len 2
Definition at line 76 of file linux-bfin-low.c.
Referenced by bfin_breakpoint_at().
#define bfin_num_regs ARRAY_SIZE (bfin_regmap)
Definition at line 44 of file linux-bfin-low.c.
Referenced by bfin_cannot_fetch_register(), and bfin_cannot_store_register().
Function Documentation
static void bfin_arch_setup (void) [static]
Definition at line 95 of file linux-bfin-low.c.
References current_process(), and process_info::tdesc.
static int bfin_breakpoint_at (CORE_ADDR where) [static]
Definition at line 80 of file linux-bfin-low.c.
References bfin_breakpoint, bfin_breakpoint_len, and read_inferior_memory().
static int bfin_cannot_fetch_register (int regno) [static]
Definition at line 53 of file linux-bfin-low.c.
References bfin_num_regs.
static int bfin_cannot_store_register (int regno) [static]
Definition at line 47 of file linux-bfin-low.c.
References bfin_num_regs.
static CORE_ADDR bfin_get_pc (struct regcache * regcache) [static]
Definition at line 59 of file linux-bfin-low.c.
References collect_register_by_name().
static struct regs_info* bfin_regs_info (void) [static, read]
Definition at line 113 of file linux-bfin-low.c.
References regs_info.
static void bfin_set_pc (struct regcache * regcache, CORE_ADDR pc) [static]
Definition at line 69 of file linux-bfin-low.c.
References supply_register_by_name().
void init_registers_bfin (void)
Referenced by initialize_low_arch().
void initialize_low_arch (void)
Definition at line 135 of file linux-bfin-low.c.
References init_registers_bfin().
Variable Documentation
const unsigned char bfin_breakpoint[bfin_breakpoint_len] = {0xa1, 0x00} [static]
Definition at line 77 of file linux-bfin-low.c.
Referenced by bfin_breakpoint_at().
int bfin_regmap[] [static]
Initial value:
{
  PT_R0, PT_R1, PT_R2, PT_R3, PT_R4, PT_R5, PT_R6, PT_R7,
  PT_P0, PT_P1, PT_P2, PT_P3, PT_P4, PT_P5, PT_USP, PT_FP,
  PT_I0, PT_I1, PT_I2, PT_I3, PT_M0, PT_M1, PT_M2, PT_M3,
  PT_B0, PT_B1, PT_B2, PT_B3, PT_L0, PT_L1, PT_L2, PT_L3,
  PT_A0X, PT_A0W, PT_A1X, PT_A1W, PT_ASTAT, PT_RETS,
  PT_LC0, PT_LT0, PT_LB0, PT_LC1, PT_LT1, PT_LB1,
  -1 , -1 ,
  -1 , PT_SEQSTAT, PT_SYSCFG, PT_PC, PT_RETX, PT_RETN, PT_RETE,
  PT_PC,
}
Definition at line 31 of file linux-bfin-low.c.
struct usrregs_info bfin_usrregs_info [static]
Initial value:
  {
    bfin_num_regs,
    bfin_regmap,
  }
Definition at line 100 of file linux-bfin-low.c.
struct regs_info regs_info [static]
Initial value:
  {
    NULL,
    &bfin_usrregs_info,
  }
Definition at line 106 of file linux-bfin-low.c.
Referenced by bfin_regs_info().
struct target_desc* tdesc_bfin
struct linux_target_ops the_low_target
Initial value:
 {
  bfin_arch_setup,
  bfin_regs_info,
  bfin_cannot_fetch_register,
  bfin_cannot_store_register,
  NULL,
  bfin_get_pc,
  bfin_set_pc,
  bfin_breakpoint,
  bfin_breakpoint_len,
  NULL,
  2,
  bfin_breakpoint_at,
}
Definition at line 118 of file linux-bfin-low.c.