GDBserver: /home/stan/gdb/src/gdb/gdbserver/mem-break.c File Reference
/home/stan/gdb/src/gdb/gdbserver/mem-break.c File Reference
#include "server.h"
#include "regcache.h"
#include "ax.h"
#include <stdint.h>
Classes
struct raw_breakpoint
struct point_cond_list
struct point_command_list
struct breakpoint
struct fast_tracepoint_jump
Defines
#define MAX_BREAKPOINT_LEN 8
#define fast_tracepoint_jump_insn(fp) ((fp)->insn_and_shadow + 0)
#define fast_tracepoint_jump_shadow(fp) ((fp)->insn_and_shadow + (fp)->length)
Enumerations
enum bkpt_type { gdb_breakpoint, reinsert_breakpoint, other_breakpoint }
Functions
int any_persistent_commands ()
static struct raw_breakpoint * find_raw_breakpoint_at (CORE_ADDR where)
static struct raw_breakpoint * set_raw_breakpoint_at (CORE_ADDR where)
static struct
fast_tracepoint_jump * find_fast_tracepoint_jump_at (CORE_ADDR where)
int fast_tracepoint_jump_here (CORE_ADDR where)
int delete_fast_tracepoint_jump (struct fast_tracepoint_jump *todel)
void inc_ref_fast_tracepoint_jump (struct fast_tracepoint_jump *jp)
struct fast_tracepoint_jump * set_fast_tracepoint_jump (CORE_ADDR where, unsigned char *insn, ULONGEST length)
void uninsert_fast_tracepoint_jumps_at (CORE_ADDR pc)
void reinsert_fast_tracepoint_jumps_at (CORE_ADDR where)
struct breakpoint * set_breakpoint_at (CORE_ADDR where, int(*handler)(CORE_ADDR))
static int delete_raw_breakpoint (struct process_info *proc, struct raw_breakpoint *todel)
static int release_breakpoint (struct process_info *proc, struct breakpoint *bp)
static int delete_breakpoint_1 (struct process_info *proc, struct breakpoint *todel)
int delete_breakpoint (struct breakpoint *todel)
struct breakpoint * find_gdb_breakpoint_at (CORE_ADDR where)
int set_gdb_breakpoint_at (CORE_ADDR where)
int delete_gdb_breakpoint_at (CORE_ADDR addr)
void clear_gdb_breakpoint_conditions (CORE_ADDR addr)
void add_condition_to_breakpoint (struct breakpoint *bp, struct agent_expr *condition)
int add_breakpoint_condition (CORE_ADDR addr, char **condition)
int gdb_condition_true_at_breakpoint (CORE_ADDR where)
void add_commands_to_breakpoint (struct breakpoint *bp, struct agent_expr *commands, int persist)
int add_breakpoint_commands (CORE_ADDR addr, char **command, int persist)
int gdb_no_commands_at_breakpoint (CORE_ADDR where)
void run_breakpoint_commands (CORE_ADDR where)
int gdb_breakpoint_here (CORE_ADDR where)
void set_reinsert_breakpoint (CORE_ADDR stop_at)
void delete_reinsert_breakpoints (void)
static void uninsert_raw_breakpoint (struct raw_breakpoint *bp)
void uninsert_breakpoints_at (CORE_ADDR pc)
void uninsert_all_breakpoints (void)
static void reinsert_raw_breakpoint (struct raw_breakpoint *bp)
void reinsert_breakpoints_at (CORE_ADDR pc)
void reinsert_all_breakpoints (void)
void check_breakpoints (CORE_ADDR stop_pc)
void set_breakpoint_data (const unsigned char *bp_data, int bp_len)
int breakpoint_here (CORE_ADDR addr)
int breakpoint_inserted_here (CORE_ADDR addr)
static int validate_inserted_breakpoint (struct raw_breakpoint *bp)
static void delete_disabled_breakpoints (void)
void validate_breakpoints (void)
void check_mem_read (CORE_ADDR mem_addr, unsigned char *buf, int mem_len)
void check_mem_write (CORE_ADDR mem_addr, unsigned char *buf, const unsigned char *myaddr, int mem_len)
void delete_all_breakpoints (void)
void mark_breakpoints_out (struct process_info *proc)
void free_all_breakpoints (struct process_info *proc)
Variables
const unsigned char * breakpoint_data
int breakpoint_len
Define Documentation
#define fast_tracepoint_jump_insn (fp) ((fp)->insn_and_shadow + 0)
Definition at line 266 of file mem-break.c.
Referenced by check_mem_write(), and set_fast_tracepoint_jump().
#define fast_tracepoint_jump_shadow (fp) ((fp)->insn_and_shadow + (fp)->length)
Definition at line 270 of file mem-break.c.
Referenced by check_mem_read(), check_mem_write(), delete_fast_tracepoint_jump(), reinsert_fast_tracepoint_jumps_at(), set_fast_tracepoint_jump(), and uninsert_fast_tracepoint_jumps_at().
#define MAX_BREAKPOINT_LEN 8
Definition at line 29 of file mem-break.c.
Referenced by delete_raw_breakpoint(), set_raw_breakpoint_at(), and uninsert_raw_breakpoint().
Enumeration Type Documentation
enum bkpt_type
Enumerator:
gdb_breakpoint
reinsert_breakpoint
other_breakpoint
Definition at line 77 of file mem-break.c.
Function Documentation
int add_breakpoint_commands (CORE_ADDR addr, char ** command, int persist)
Definition at line 896 of file mem-break.c.
References add_commands_to_breakpoint(), find_gdb_breakpoint_at(), and gdb_parse_agent_expr().
Referenced by process_point_options().
int add_breakpoint_condition (CORE_ADDR addr, char ** condition)
Definition at line 804 of file mem-break.c.
References add_condition_to_breakpoint(), find_gdb_breakpoint_at(), and gdb_parse_agent_expr().
Referenced by process_point_options().
void add_commands_to_breakpoint (struct breakpoint * bp, struct agent_expr * commands, int persist)
Definition at line 878 of file mem-break.c.
References point_command_list::cmd, breakpoint::command_list, point_command_list::next, point_command_list::persistence, and xcalloc().
Referenced by add_breakpoint_commands().
void add_condition_to_breakpoint (struct breakpoint * bp, struct agent_expr * condition)
Definition at line 787 of file mem-break.c.
References point_cond_list::cond, breakpoint::cond_list, point_cond_list::next, and xcalloc().
Referenced by add_breakpoint_condition().
int any_persistent_commands (void)
Definition at line 142 of file mem-break.c.
References process_info::breakpoints, breakpoint::command_list, current_process(), point_command_list::next, breakpoint::next, and point_command_list::persistence.
Referenced by process_serial_event().
int breakpoint_here (CORE_ADDR addr)
Definition at line 1170 of file mem-break.c.
References find_raw_breakpoint_at().
Referenced by linux_wait_1(), and need_step_over_p().
int breakpoint_inserted_here (CORE_ADDR addr)
Definition at line 1176 of file mem-break.c.
References find_raw_breakpoint_at(), and raw_breakpoint::inserted.
Referenced by count_events_callback(), linux_wait_1(), and select_event_lwp_callback().
void check_breakpoints (CORE_ADDR stop_pc)
Definition at line 1128 of file mem-break.c.
References process_info::breakpoints, current_process(), breakpoint::handler, raw_breakpoint::inserted, breakpoint::next, raw_breakpoint::pc, breakpoint::raw, release_breakpoint(), and warning().
Referenced by handle_exception(), and linux_wait_1().
void check_mem_read (CORE_ADDR mem_addr, unsigned char * buf, int mem_len)
Definition at line 1243 of file mem-break.c.
References breakpoint_len, current_process(), delete_disabled_breakpoints(), fast_tracepoint_jump_shadow, process_info::fast_tracepoint_jumps, gdb_assert, raw_breakpoint::inserted, fast_tracepoint_jump::inserted, fast_tracepoint_jump::length, memcpy(), raw_breakpoint::next, fast_tracepoint_jump::next, raw_breakpoint::old_data, raw_breakpoint::pc, fast_tracepoint_jump::pc, process_info::raw_breakpoints, and validate_inserted_breakpoint().
Referenced by read_inferior_memory().
void check_mem_write (CORE_ADDR mem_addr, unsigned char * buf, const unsigned char * myaddr, int mem_len)
Definition at line 1323 of file mem-break.c.
References breakpoint_data, breakpoint_len, current_process(), delete_disabled_breakpoints(), fast_tracepoint_jump_insn, fast_tracepoint_jump_shadow, process_info::fast_tracepoint_jumps, gdb_assert, raw_breakpoint::inserted, fast_tracepoint_jump::inserted, fast_tracepoint_jump::length, memcpy(), raw_breakpoint::next, fast_tracepoint_jump::next, raw_breakpoint::old_data, raw_breakpoint::pc, fast_tracepoint_jump::pc, process_info::raw_breakpoints, and validate_inserted_breakpoint().
Referenced by write_inferior_memory().
void clear_gdb_breakpoint_conditions (CORE_ADDR addr)
Definition at line 760 of file mem-break.c.
References agent_expr::bytes, point_cond_list::cond, breakpoint::cond_list, find_gdb_breakpoint_at(), and point_cond_list::next.
Referenced by delete_gdb_breakpoint_at(), and process_serial_event().
void delete_all_breakpoints (void)
Definition at line 1412 of file mem-break.c.
References process_info::breakpoints, current_process(), and delete_breakpoint_1().
int delete_breakpoint (struct breakpoint * todel)
Definition at line 681 of file mem-break.c.
References current_process(), and delete_breakpoint_1().
Referenced by clear_installed_tracepoints(), delete_gdb_breakpoint_at(), linux_wait_1(), maybe_move_out_of_jump_pad(), remove_thread_event_breakpoints(), stop_tracing(), and upload_fast_traceframes().
static int delete_breakpoint_1 (struct process_info * proc, struct breakpoint * todel) [static]
Definition at line 648 of file mem-break.c.
References process_info::breakpoints, breakpoint::next, release_breakpoint(), and warning().
Referenced by delete_all_breakpoints(), delete_breakpoint(), delete_disabled_breakpoints(), and free_all_breakpoints().
static void delete_disabled_breakpoints (void) [static]
Definition at line 1207 of file mem-break.c.
References process_info::breakpoints, current_process(), delete_breakpoint_1(), breakpoint::next, breakpoint::raw, and raw_breakpoint::shlib_disabled.
Referenced by check_mem_read(), check_mem_write(), and validate_breakpoints().
int delete_fast_tracepoint_jump (struct fast_tracepoint_jump * todel)
Definition at line 298 of file mem-break.c.
References current_process(), debug_threads, fast_tracepoint_jump_shadow, process_info::fast_tracepoint_jumps, fast_tracepoint_jump::length, memcpy(), fast_tracepoint_jump::next, paddress(), fast_tracepoint_jump::pc, fast_tracepoint_jump::refcount, strerror, warning(), and write_inferior_memory().
Referenced by clear_installed_tracepoints().
int delete_gdb_breakpoint_at (CORE_ADDR addr)
Definition at line 735 of file mem-break.c.
References breakpoint_data, clear_gdb_breakpoint_conditions(), delete_breakpoint(), and find_gdb_breakpoint_at().
Referenced by set_gdb_breakpoint_at(), and x86_remove_point().
static int delete_raw_breakpoint (struct process_info * proc, struct raw_breakpoint * todel) [static]
Definition at line 565 of file mem-break.c.
References breakpoint_len, debug_threads, raw_breakpoint::inserted, MAX_BREAKPOINT_LEN, memcpy(), raw_breakpoint::next, raw_breakpoint::old_data, paddress(), raw_breakpoint::pc, process_info::raw_breakpoints, strerror, warning(), and write_inferior_memory().
Referenced by release_breakpoint().
void delete_reinsert_breakpoints (void)
Definition at line 989 of file mem-break.c.
References process_info::breakpoints, current_process(), breakpoint::next, reinsert_breakpoint, release_breakpoint(), and breakpoint::type.
Referenced by finish_step_over().
int fast_tracepoint_jump_here (CORE_ADDR where)
Definition at line 290 of file mem-break.c.
References find_fast_tracepoint_jump_at().
Referenced by need_step_over_p().
static struct fast_tracepoint_jump* find_fast_tracepoint_jump_at (CORE_ADDR where) [static, read]
Definition at line 277 of file mem-break.c.
References current_process(), process_info::fast_tracepoint_jumps, fast_tracepoint_jump::next, and fast_tracepoint_jump::pc.
Referenced by fast_tracepoint_jump_here(), reinsert_fast_tracepoint_jumps_at(), set_fast_tracepoint_jump(), and uninsert_fast_tracepoint_jumps_at().
struct breakpoint* find_gdb_breakpoint_at (CORE_ADDR where) [read]
Definition at line 688 of file mem-break.c.
References process_info::breakpoints, current_process(), gdb_breakpoint, breakpoint::next, raw_breakpoint::pc, breakpoint::raw, and breakpoint::type.
Referenced by add_breakpoint_commands(), add_breakpoint_condition(), clear_gdb_breakpoint_conditions(), delete_gdb_breakpoint_at(), gdb_breakpoint_here(), gdb_condition_true_at_breakpoint(), gdb_no_commands_at_breakpoint(), run_breakpoint_commands(), and set_gdb_breakpoint_at().
static struct raw_breakpoint* find_raw_breakpoint_at (CORE_ADDR where) [static, read]
Definition at line 159 of file mem-break.c.
References current_process(), raw_breakpoint::next, raw_breakpoint::pc, and process_info::raw_breakpoints.
Referenced by breakpoint_here(), breakpoint_inserted_here(), reinsert_breakpoints_at(), set_raw_breakpoint_at(), and uninsert_breakpoints_at().
void free_all_breakpoints (struct process_info * proc)
Definition at line 1435 of file mem-break.c.
References process_info::breakpoints, delete_breakpoint_1(), and mark_breakpoints_out().
Referenced by remove_process().
int gdb_breakpoint_here (CORE_ADDR where)
Definition at line 974 of file mem-break.c.
References find_gdb_breakpoint_at().
Referenced by linux_wait_1(), move_out_of_jump_pad_callback(), need_step_over_p(), and stuck_in_jump_pad_callback().
int gdb_condition_true_at_breakpoint (CORE_ADDR where)
Definition at line 836 of file mem-break.c.
References point_cond_list::cond, breakpoint::cond_list, current_inferior, find_gdb_breakpoint_at(), gdb_eval_agent_expr(), get_thread_regcache(), point_cond_list::next, eval_agent_expr_context::regcache, eval_agent_expr_context::tframe, and eval_agent_expr_context::tpoint.
Referenced by linux_wait_1(), and need_step_over_p().
int gdb_no_commands_at_breakpoint (CORE_ADDR where)
Definition at line 927 of file mem-break.c.
References breakpoint::command_list, debug_threads, find_gdb_breakpoint_at(), paddress(), and phex_nz().
Referenced by linux_wait_1(), and need_step_over_p().
void inc_ref_fast_tracepoint_jump (struct fast_tracepoint_jump * jp)
Definition at line 361 of file mem-break.c.
References fast_tracepoint_jump::refcount.
Referenced by clone_fast_tracepoint().
void mark_breakpoints_out (struct process_info * proc)
Definition at line 1423 of file mem-break.c.
References raw_breakpoint::inserted, raw_breakpoint::next, and process_info::raw_breakpoints.
Referenced by free_all_breakpoints(), and handle_target_event().
void reinsert_all_breakpoints (void)
Definition at line 1117 of file mem-break.c.
References current_process(), raw_breakpoint::inserted, raw_breakpoint::next, process_info::raw_breakpoints, and reinsert_raw_breakpoint().
Referenced by run_inferior_command().
void reinsert_breakpoints_at (CORE_ADDR pc)
Definition at line 1096 of file mem-break.c.
References debug_threads, find_raw_breakpoint_at(), paddress(), and reinsert_raw_breakpoint().
Referenced by finish_step_over().
void reinsert_fast_tracepoint_jumps_at (CORE_ADDR where)
Definition at line 491 of file mem-break.c.
References debug_threads, error(), fast_tracepoint_jump_shadow, find_fast_tracepoint_jump_at(), fast_tracepoint_jump::inserted, fast_tracepoint_jump::length, memcpy(), paddress(), strerror, and write_inferior_memory().
Referenced by finish_step_over().
static void reinsert_raw_breakpoint (struct raw_breakpoint * bp) [static]
Definition at line 1078 of file mem-break.c.
References breakpoint_data, breakpoint_len, debug_threads, error(), raw_breakpoint::inserted, paddress(), raw_breakpoint::pc, strerror, the_target, and target_ops::write_memory.
Referenced by reinsert_all_breakpoints(), and reinsert_breakpoints_at().
static int release_breakpoint (struct process_info * proc, struct breakpoint * bp) [static]
Definition at line 627 of file mem-break.c.
References delete_raw_breakpoint(), breakpoint::raw, and raw_breakpoint::refcount.
Referenced by check_breakpoints(), delete_breakpoint_1(), and delete_reinsert_breakpoints().
void run_breakpoint_commands (CORE_ADDR where)
Definition at line 942 of file mem-break.c.
References point_command_list::cmd, breakpoint::command_list, current_inferior, find_gdb_breakpoint_at(), gdb_eval_agent_expr(), get_thread_regcache(), point_command_list::next, eval_agent_expr_context::regcache, eval_agent_expr_context::tframe, and eval_agent_expr_context::tpoint.
Referenced by linux_wait_1().
struct breakpoint* set_breakpoint_at (CORE_ADDR where, int(*)(CORE_ADDR) handler) [read]
Definition at line 538 of file mem-break.c.
References process_info::breakpoints, current_process(), breakpoint::handler, breakpoint::next, other_breakpoint, breakpoint::raw, set_raw_breakpoint_at(), breakpoint::type, and xcalloc().
Referenced by cmd_qtstart(), get_child_debug_event(), install_tracepoint(), maybe_move_out_of_jump_pad(), set_gdb_breakpoint_at(), set_reinsert_breakpoint(), thread_db_enable_reporting(), and upload_fast_traceframes().
void set_breakpoint_data (const unsigned char * bp_data, int bp_len)
Definition at line 1163 of file mem-break.c.
References breakpoint_data, and breakpoint_len.
Referenced by initialize_low().
struct fast_tracepoint_jump* set_fast_tracepoint_jump (CORE_ADDR where, unsigned char * insn, ULONGEST length) [read]
Definition at line 367 of file mem-break.c.
References current_process(), debug_threads, fast_tracepoint_jump_insn, fast_tracepoint_jump_shadow, process_info::fast_tracepoint_jumps, find_fast_tracepoint_jump_at(), fast_tracepoint_jump::inserted, fast_tracepoint_jump::length, memcpy(), fast_tracepoint_jump::next, paddress(), fast_tracepoint_jump::pc, read_inferior_memory(), fast_tracepoint_jump::refcount, strerror, write_inferior_memory(), and xcalloc().
Referenced by install_fast_tracepoint(), and tracepoint_send_agent().
int set_gdb_breakpoint_at (CORE_ADDR where)
Definition at line 701 of file mem-break.c.
References breakpoint_data, delete_gdb_breakpoint_at(), find_gdb_breakpoint_at(), gdb_breakpoint, set_breakpoint_at(), breakpoint::type, and validate_breakpoints().
Referenced by x86_insert_point().
static struct raw_breakpoint* set_raw_breakpoint_at (CORE_ADDR where) [static, read]
Definition at line 172 of file mem-break.c.
References breakpoint_data, breakpoint_len, current_process(), debug_threads, error(), find_raw_breakpoint_at(), raw_breakpoint::inserted, MAX_BREAKPOINT_LEN, memcpy(), raw_breakpoint::next, raw_breakpoint::old_data, paddress(), raw_breakpoint::pc, process_info::raw_breakpoints, read_inferior_memory(), raw_breakpoint::refcount, strerror, the_target, target_ops::write_memory, and xcalloc().
Referenced by set_breakpoint_at().
void set_reinsert_breakpoint (CORE_ADDR stop_at)
Definition at line 980 of file mem-break.c.
References reinsert_breakpoint, set_breakpoint_at(), and breakpoint::type.
Referenced by start_step_over().
void uninsert_all_breakpoints (void)
Definition at line 1067 of file mem-break.c.
References current_process(), raw_breakpoint::inserted, raw_breakpoint::next, process_info::raw_breakpoints, and uninsert_raw_breakpoint().
Referenced by run_inferior_command().
void uninsert_breakpoints_at (CORE_ADDR pc)
Definition at line 1045 of file mem-break.c.
References debug_threads, find_raw_breakpoint_at(), raw_breakpoint::inserted, paddress(), and uninsert_raw_breakpoint().
Referenced by start_step_over().
void uninsert_fast_tracepoint_jumps_at (CORE_ADDR pc)
Definition at line 442 of file mem-break.c.
References debug_threads, fast_tracepoint_jump_shadow, find_fast_tracepoint_jump_at(), fast_tracepoint_jump::inserted, fast_tracepoint_jump::length, memcpy(), paddress(), fast_tracepoint_jump::pc, strerror, and write_inferior_memory().
Referenced by start_step_over().
static void uninsert_raw_breakpoint (struct raw_breakpoint * bp) [static]
Definition at line 1014 of file mem-break.c.
References breakpoint_len, debug_threads, raw_breakpoint::inserted, MAX_BREAKPOINT_LEN, memcpy(), raw_breakpoint::old_data, paddress(), raw_breakpoint::pc, strerror, and write_inferior_memory().
Referenced by uninsert_all_breakpoints(), and uninsert_breakpoints_at().
void validate_breakpoints (void)
Definition at line 1228 of file mem-break.c.
References process_info::breakpoints, current_process(), delete_disabled_breakpoints(), raw_breakpoint::inserted, breakpoint::next, breakpoint::raw, and validate_inserted_breakpoint().
Referenced by handle_query(), and set_gdb_breakpoint_at().
static int validate_inserted_breakpoint (struct raw_breakpoint * bp) [static]
Definition at line 1186 of file mem-break.c.
References breakpoint_data, breakpoint_len, gdb_assert, raw_breakpoint::inserted, memcmp(), raw_breakpoint::pc, target_ops::read_memory, raw_breakpoint::shlib_disabled, and the_target.
Referenced by check_mem_read(), check_mem_write(), and validate_breakpoints().
Variable Documentation
const unsigned char* breakpoint_data
Definition at line 26 of file mem-break.c.
Referenced by check_mem_write(), delete_gdb_breakpoint_at(), reinsert_raw_breakpoint(), set_breakpoint_data(), set_gdb_breakpoint_at(), set_raw_breakpoint_at(), and validate_inserted_breakpoint().
int breakpoint_len
Definition at line 27 of file mem-break.c.
Referenced by check_mem_read(), check_mem_write(), delete_raw_breakpoint(), reinsert_raw_breakpoint(), set_breakpoint_data(), set_raw_breakpoint_at(), uninsert_raw_breakpoint(), and validate_inserted_breakpoint().