GDBserver: /home/stan/gdb/src/gdb/gdbserver/notif.c File Reference
/home/stan/gdb/src/gdb/gdbserver/notif.c File Reference
#include "notif.h"
Functions
void notif_write_event (struct notif_server *notif, char *own_buf)
int handle_notif_ack (char *own_buf, int packet_len)
void notif_event_enque (struct notif_server *notif, struct notif_event *event)
void notif_push (struct notif_server *np, struct notif_event *new_event)
static void notif_event_xfree (struct notif_event *event)
void initialize_notif (void)
Variables
static struct notif_server * notifs []
Function Documentation
int handle_notif_ack (char * own_buf, int packet_len)
Definition at line 79 of file notif.c.
References notif_server::ack_name, notif_write_event(), QUEUE_deque, QUEUE_is_empty, QUEUE_length, remote_debug, and xfree().
Referenced by handle_v_requests().
void initialize_notif (void)
Definition at line 160 of file notif.c.
References notif_event_xfree(), and QUEUE_alloc.
Referenced by main().
void notif_event_enque (struct notif_server * notif, struct notif_event * event)
Definition at line 117 of file notif.c.
References notif_server::notif_name, QUEUE_enque, QUEUE_length, and remote_debug.
Referenced by notif_push(), queue_stop_reply(), and queue_stop_reply_callback().
static void notif_event_xfree (struct notif_event * event) [static]
Definition at line 154 of file notif.c.
References xfree().
Referenced by initialize_notif().
void notif_push (struct notif_server * np, struct notif_event * new_event)
Definition at line 131 of file notif.c.
References notif_event_enque(), notif_server::notif_name, PBUFSIZ, putpkt_notif(), QUEUE_is_empty, notif_server::write, and xsnprintf().
Referenced by handle_target_event().
void notif_write_event (struct notif_server * notif, char * own_buf)
Definition at line 61 of file notif.c.
References QUEUE_is_empty, QUEUE_peek, notif_server::write, and write_ok().
Referenced by handle_notif_ack(), and handle_status().
Variable Documentation
struct notif_server* notifs[] [static]
Initial value:
{
  &notif_stop,
}
Definition at line 52 of file notif.c.