GDBserver: /home/stan/gdb/src/gdb/common/ptid.c File Reference
/home/stan/gdb/src/gdb/common/ptid.c File Reference
#include "ptid.h"
Functions
ptid_t ptid_build (int pid, long lwp, long tid)
ptid_t pid_to_ptid (int pid)
int ptid_get_pid (ptid_t ptid)
long ptid_get_lwp (ptid_t ptid)
long ptid_get_tid (ptid_t ptid)
int ptid_equal (ptid_t ptid1, ptid_t ptid2)
int ptid_is_pid (ptid_t ptid)
int ptid_lwp_p (ptid_t ptid)
int ptid_tid_p (ptid_t ptid)
Variables
ptid_t null_ptid = { 0, 0, 0 }
ptid_t minus_one_ptid = { -1, 0, 0 }
Function Documentation
ptid_t pid_to_ptid (int pid)
Definition at line 43 of file ptid.c.
References ptid_build().
Referenced by add_process(), attach_inferior(), attach_thread(), find_process_pid(), handle_query(), handle_v_kill(), linux_kill(), linux_wait_for_lwp(), maybe_attach_thread(), process_serial_event(), ps_lgetregs(), spu_wait(), start_inferior(), wait_for_sigstop(), win32_wait(), and x86_get_thread_area().
ptid_t ptid_build (int pid, long lwp, long tid)
Definition at line 30 of file ptid.c.
References ptid::lwp, ptid::pid, and ptid::tid.
Referenced by agent_run_command(), child_add_thread(), child_delete_thread(), debug_event_ptid(), do_attach(), get_cores_used_by_process(), handle_extended_wait(), linux_attach(), linux_attach_lwp_1(), linux_create_inferior(), linux_xfer_osdata_threads(), lynx_ptid_build(), nto_find_new_threads(), nto_request_interrupt(), nto_wait(), pid_to_ptid(), read_ptid(), spu_attach(), spu_create_inferior(), and spu_wait().
int ptid_equal (ptid_t ptid1, ptid_t ptid2)
Definition at line 75 of file ptid.c.
References ptid::lwp, ptid::pid, and ptid::tid.
Referenced by agent_run_command(), find_inferior_id(), find_thread_ptid(), handle_btrace_general_set(), handle_query(), handle_qxfer_btrace(), handle_v_cont(), linux_request_interrupt(), linux_set_resume_request(), linux_wait(), linux_wait_1(), linux_wait_for_event(), linux_wait_for_lwp(), lynx_resume(), lynx_wait_1(), myresume(), nto_set_thread(), prepare_resume_reply(), process_serial_event(), ptid_is_pid(), ptid_lwp_p(), ptid_tid_p(), spu_resume(), spu_thread_alive(), status_pending_p_callback(), target_pid_to_str(), thread_id_to_gdb_id(), and win32_resume().
long ptid_get_lwp (ptid_t ptid)
Definition at line 59 of file ptid.c.
References ptid::lwp.
Referenced by aarch64_linux_prepare_to_resume(), do_attach(), fetch_ppc_memory(), fetch_ppc_register(), find_one_thread(), handle_v_cont(), linux_common_core_of_thread(), linux_set_resume_request(), linux_wait_for_lwp(), lynx_ptid_get_tid(), mips_linux_prepare_to_resume(), nto_set_thread(), nto_thread_alive(), ptid_is_pid(), ptid_lwp_p(), same_lwp(), spu_proc_xfer_spu(), spu_request_interrupt(), spu_resume(), store_ppc_memory(), target_pid_to_str(), write_ptid(), x86_linux_dr_get(), and x86_linux_dr_set().
int ptid_get_pid (ptid_t ptid)
Definition at line 51 of file ptid.c.
References ptid::pid.
Referenced by aarch64_linux_prepare_to_resume(), any_thread_of(), detach_or_kill_inferior_callback(), first_thread_of(), gdb_agent_about_to_close(), get_thread_process(), handle_target_event(), handle_v_cont(), kill_inferior_callback(), kill_one_lwp_callback(), last_thread_of_process_p(), linux_common_core_of_thread(), linux_detach_one_lwp(), linux_set_resume_request(), linux_wait_for_event(), lynx_ptid_get_pid(), mips_linux_prepare_to_resume(), myresume(), nto_set_thread(), nto_thread_alive(), nto_wait(), prepare_resume_reply(), print_attached_pid(), print_started_pid(), process_serial_event(), read_ptid(), regcache_invalidate(), regcache_invalidate_one(), remove_all_on_match_pid(), run_inferior_command(), same_lwp(), same_process_callback(), second_thread_of_pid_p(), spu_wait(), status_pending_p_callback(), target_pid_to_str(), write_ptid(), x86_arch_setup_process_callback(), and x86_linux_prepare_to_resume().
long ptid_get_tid (ptid_t ptid)
Definition at line 67 of file ptid.c.
References ptid::tid.
Referenced by ptid_is_pid(), ptid_tid_p(), and target_pid_to_str().
int ptid_is_pid (ptid_t ptid)
Definition at line 85 of file ptid.c.
References ptid_equal(), ptid_get_lwp(), and ptid_get_tid().
Referenced by linux_set_resume_request(), and linux_wait_for_event().
int ptid_lwp_p (ptid_t ptid)
Definition at line 97 of file ptid.c.
References ptid_equal(), and ptid_get_lwp().
int ptid_tid_p (ptid_t ptid)
Definition at line 109 of file ptid.c.
References ptid_equal(), and ptid_get_tid().
Variable Documentation
ptid_t minus_one_ptid = { -1, 0, 0 }
Definition at line 25 of file ptid.c.
Referenced by handle_btrace_general_set(), handle_query(), handle_qxfer_btrace(), handle_target_event(), handle_v_cont(), linux_request_interrupt(), linux_set_resume_request(), linux_stabilize_threads(), linux_wait_1(), linux_wait_for_event(), linux_wait_for_lwp(), loaded_dll(), lynx_resume(), lynx_wait_1(), main(), myresume(), nto_set_thread(), process_serial_event(), spu_resume(), status_pending_p_callback(), target_pid_to_str(), win32_detach(), and win32_resume().
ptid_t null_ptid = { 0, 0, 0 }
Definition at line 24 of file ptid.c.
Referenced by agent_run_command(), attach_inferior(), finish_step_over(), gdb_id_to_thread_id(), handle_btrace_general_set(), handle_query(), handle_qxfer_btrace(), linux_request_interrupt(), linux_wait(), linux_wait_1(), lynx_add_process(), lynx_create_inferior(), myresume(), nto_set_thread(), process_serial_event(), start_inferior(), target_pid_to_str(), thread_id_to_gdb_id(), and wait_for_sigstop().