GDBserver: /home/stan/gdb/src/gdb/gdbserver/regcache.c File Reference
/home/stan/gdb/src/gdb/gdbserver/regcache.c File Reference
#include "server.h"
#include "regdef.h"
#include "gdbthread.h"
#include "tdesc.h"
#include <stdlib.h>
#include <string.h>
Functions
struct regcache * get_thread_regcache (struct thread_info *thread, int fetch)
void regcache_invalidate_thread (struct thread_info *thread)
static int regcache_invalidate_one (struct inferior_list_entry *entry, void *pid_p)
void regcache_invalidate (void)
struct regcache * init_register_cache (struct regcache *regcache, const struct target_desc *tdesc, unsigned char *regbuf)
struct regcache * new_register_cache (const struct target_desc *tdesc)
void free_register_cache (struct regcache *regcache)
void regcache_cpy (struct regcache *dst, struct regcache *src)
void registers_to_string (struct regcache *regcache, char *buf)
void registers_from_string (struct regcache *regcache, char *buf)
struct reg * find_register_by_name (const struct target_desc *tdesc, const char *name)
int find_regno (const struct target_desc *tdesc, const char *name)
struct reg * find_register_by_number (const struct target_desc *tdesc, int n)
static void free_register_cache_thread (struct thread_info *thread)
static void free_register_cache_thread_one (struct inferior_list_entry *entry)
void regcache_release (void)
int register_cache_size (const struct target_desc *tdesc)
int register_size (const struct target_desc *tdesc, int n)
static unsigned char * register_data (struct regcache *regcache, int n, int fetch)
void supply_register (struct regcache *regcache, int n, const void *buf)
void supply_register_zeroed (struct regcache *regcache, int n)
void supply_regblock (struct regcache *regcache, const void *buf)
void supply_register_by_name (struct regcache *regcache, const char *name, const void *buf)
void collect_register (struct regcache *regcache, int n, void *buf)
void collect_register_as_string (struct regcache *regcache, int n, char *buf)
void collect_register_by_name (struct regcache *regcache, const char *name, void *buf)
CORE_ADDR regcache_read_pc (struct regcache *regcache)
void regcache_write_pc (struct regcache *regcache, CORE_ADDR pc)
Function Documentation
void collect_register (struct regcache * regcache, int n, void * buf)
Definition at line 410 of file regcache.c.
References memcpy(), register_data(), register_size(), and regcache::tdesc.
Referenced by aarch64_fill_fpregset(), aarch64_fill_gregset(), arm_fill_gregset(), arm_fill_vfpregset(), arm_fill_wmmxregset(), arm_store_inferior_register(), collect_16bit_register(), collect_register_by_name(), cris_fill_gregset(), gdb_eval_agent_expr(), i386_store_inferior_register(), i387_cache_to_fsave(), i387_cache_to_fxsave(), i387_cache_to_xsave(), lynx_i386_fill_fpregset(), lynx_ppc_fill_fpregset(), lynx_ppc_fill_gregset(), nto_store_registers(), ppc_collect_ptrace_register(), ppc_fill_evrregset(), ppc_fill_vrregset(), ppc_fill_vsxregset(), s390_collect_ptrace_register(), s390_supply_ptrace_register(), sh_fill_gregset(), sparc_fill_fpregset(), sparc_fill_gregset(), sparc_fill_gregset_to_stack(), spu_store_registers(), tic6x_collect_register(), tile_fill_gregset(), x86_fill_gregset(), and xtensa_fill_gregset().
void collect_register_as_string (struct regcache * regcache, int n, char * buf)
Definition at line 419 of file regcache.c.
References convert_int_to_ascii(), register_data(), register_size(), and regcache::tdesc.
Referenced by outreg().
void collect_register_by_name (struct regcache * regcache, const char * name, void * buf)
Definition at line 426 of file regcache.c.
References collect_register(), find_regno(), and regcache::tdesc.
Referenced by aarch64_get_pc(), arm_breakpoint_at(), arm_fill_vfpregset(), arm_get_pc(), arm_reinsert_addr(), bfin_get_pc(), cris_get_pc(), cris_insert_point(), cris_reinsert_addr(), cris_remove_point(), cris_stopped_by_watchpoint(), cris_stopped_data_address(), i387_cache_to_fsave(), i387_cache_to_fxsave(), i387_cache_to_xsave(), m32r_get_pc(), m68k_get_pc(), mips_get_pc(), mips_reinsert_addr(), nios2_get_pc(), nios2_reinsert_addr(), parse_spufs_run(), ppc_arch_setup(), ppc_fill_evrregset(), ppc_fill_vrregset(), ppc_get_pc(), s390_arch_setup(), s390_fill_system_call(), s390_get_pc(), s390_set_pc(), sh_get_pc(), sparc_get_pc(), sparc_reinsert_addr(), tic6x_get_pc(), tile_get_pc(), x86_fill_gregset(), x86_get_pc(), x86_get_thread_area(), xtensa_fill_gregset(), xtensa_fill_xtregset(), and xtensa_get_pc().
struct reg* find_register_by_name (const struct target_desc * tdesc, const char * name) [read]
Definition at line 241 of file regcache.c.
References fatal(), target_desc::num_registers, and target_desc::reg_defs.
struct reg* find_register_by_number (const struct target_desc * tdesc, int n) [read]
Definition at line 265 of file regcache.c.
References target_desc::reg_defs.
int find_regno (const struct target_desc * tdesc, const char * name)
Definition at line 253 of file regcache.c.
References fatal(), target_desc::num_registers, and target_desc::reg_defs.
Referenced by arm_fill_vfpregset(), arm_store_vfpregset(), collect_register_by_name(), i387_cache_to_fsave(), i387_cache_to_fxsave(), i387_cache_to_xsave(), i387_fsave_to_cache(), i387_fxsave_to_cache(), i387_xsave_to_cache(), mips_cannot_fetch_register(), mips_cannot_store_register(), ppc_arch_setup(), ppc_cannot_store_register(), ppc_fill_evrregset(), ppc_fill_vrregset(), ppc_fill_vsxregset(), ppc_store_evrregset(), ppc_store_vrregset(), ppc_store_vsxregset(), prepare_resume_reply(), s390_arch_setup(), sparc_fill_gregset_to_stack(), sparc_store_gregset_from_stack(), supply_register_by_name(), xtensa_fill_gregset(), and xtensa_store_gregset().
void free_register_cache (struct regcache * regcache)
Definition at line 166 of file regcache.c.
References regcache::register_status, regcache::registers, and regcache::registers_owned.
Referenced by free_one_thread(), free_register_cache_thread(), ppc_arch_setup(), process_serial_event(), and s390_arch_setup().
static void free_register_cache_thread (struct thread_info * thread) [static]
Definition at line 274 of file regcache.c.
References free_register_cache(), inferior_regcache_data(), regcache_invalidate_thread(), and set_inferior_regcache_data().
Referenced by free_register_cache_thread_one().
static void free_register_cache_thread_one (struct inferior_list_entry * entry) [static]
Definition at line 288 of file regcache.c.
References free_register_cache_thread().
Referenced by regcache_release().
struct regcache* get_thread_regcache (struct thread_info * thread, int fetch) [read]
Definition at line 30 of file regcache.c.
References current_inferior, fatal(), fetch_inferior_registers, get_thread_process(), inferior_regcache_data(), new_register_cache(), regcache::registers_valid, set_inferior_regcache_data(), and process_info::tdesc.
Referenced by arm_breakpoint_at(), arm_reinsert_addr(), cancel_breakpoint(), cris_insert_point(), cris_reinsert_addr(), cris_remove_point(), cris_stopped_by_watchpoint(), cris_stopped_data_address(), gdb_condition_true_at_breakpoint(), get_pc(), linux_resume_one_lwp(), linux_wait_1(), linux_wait_for_lwp(), maybe_move_out_of_jump_pad(), mips_reinsert_addr(), nios2_reinsert_addr(), prepare_resume_reply(), process_serial_event(), ps_lgetregs(), run_breakpoint_commands(), sparc_reinsert_addr(), tracepoint_finished_step(), tracepoint_was_hit(), win32_wait(), and x86_get_thread_area().
struct regcache* init_register_cache (struct regcache * regcache, const struct target_desc * tdesc, unsigned char * regbuf) [read]
Definition at line 115 of file regcache.c.
References fatal(), gdb_assert, target_desc::num_registers, REG_UNAVAILABLE, regcache::register_status, regcache::registers, regcache::registers_owned, target_desc::registers_size, regcache::registers_valid, regcache::tdesc, and xcalloc().
Referenced by do_action_at_tracepoint(), get_context_regcache(), new_register_cache(), and traceframe_get_pc().
struct regcache* new_register_cache (const struct target_desc * tdesc) [read]
Definition at line 155 of file regcache.c.
References gdb_assert, init_register_cache(), target_desc::registers_size, and xmalloc().
Referenced by get_thread_regcache(), ppc_arch_setup(), process_serial_event(), and s390_arch_setup().
void regcache_cpy (struct regcache * dst, struct regcache * src)
Definition at line 180 of file regcache.c.
References gdb_assert, memcpy(), target_desc::num_registers, regcache::register_status, regcache::registers, target_desc::registers_size, regcache::registers_valid, and regcache::tdesc.
Referenced by do_action_at_tracepoint().
void regcache_invalidate (void)
Definition at line 104 of file regcache.c.
References all_threads, current_inferior, thread_info::entry, find_inferior(), inferior_list_entry::id, ptid_get_pid(), and regcache_invalidate_one().
Referenced by lynx_resume(), nto_resume(), spu_resume(), and win32_resume().
static int regcache_invalidate_one (struct inferior_list_entry * entry, void * pid_p) [static]
Definition at line 90 of file regcache.c.
References inferior_list_entry::id, ptid_get_pid(), and regcache_invalidate_thread().
Referenced by regcache_invalidate().
void regcache_invalidate_thread (struct thread_info * thread)
Definition at line 68 of file regcache.c.
References current_inferior, inferior_regcache_data(), regcache::registers_valid, and store_inferior_registers.
Referenced by free_register_cache_thread(), linux_detach_one_lwp(), linux_resume_one_lwp(), and regcache_invalidate_one().
CORE_ADDR regcache_read_pc (struct regcache * regcache)
Definition at line 435 of file regcache.c.
References internal_error(), target_ops::read_pc, and the_target.
Referenced by traceframe_get_pc().
void regcache_release (void)
Definition at line 296 of file regcache.c.
References all_threads, for_each_inferior(), and free_register_cache_thread_one().
Referenced by x86_linux_update_xmltarget().
void regcache_write_pc (struct regcache * regcache, CORE_ADDR pc)
Definition at line 449 of file regcache.c.
References internal_error(), the_target, and target_ops::write_pc.
Referenced by do_action_at_tracepoint(), and fetch_traceframe_registers().
int register_cache_size (const struct target_desc * tdesc)
Definition at line 304 of file regcache.c.
References target_desc::registers_size.
Referenced by do_action_at_tracepoint().
static unsigned char* register_data (struct regcache * regcache, int n, int fetch) [static]
Definition at line 316 of file regcache.c.
References target_desc::reg_defs, regcache::registers, and regcache::tdesc.
Referenced by collect_register(), collect_register_as_string(), supply_register(), and supply_register_zeroed().
int register_size (const struct target_desc * tdesc, int n)
Definition at line 310 of file regcache.c.
References target_desc::reg_defs.
Referenced by collect_register(), collect_register_as_string(), gdb_eval_agent_expr(), i387_cache_to_fxsave(), i387_cache_to_xsave(), i387_fxsave_to_cache(), i387_xsave_to_cache(), ia64_fetch_register(), mips_get_pc(), mips_reinsert_addr(), mips_set_pc(), outreg(), parse_spufs_run(), ppc_arch_setup(), ppc_collect_ptrace_register(), ppc_get_hwcap(), ppc_get_pc(), ppc_set_pc(), ppc_supply_ptrace_register(), registers_to_string(), s390_collect_ptrace_register(), s390_get_pc(), s390_regs_info(), s390_set_pc(), s390_store_last_break(), s390_supply_ptrace_register(), supply_register(), supply_register_zeroed(), x86_fill_gregset(), x86_get_pc(), x86_set_pc(), x86_store_gregset(), xtensa_fill_gregset(), and xtensa_store_gregset().
void registers_from_string (struct regcache * regcache, char * buf)
Definition at line 224 of file regcache.c.
References convert_ascii_to_int(), regcache::registers, target_desc::registers_size, regcache::tdesc, and warning().
Referenced by process_serial_event().
void registers_to_string (struct regcache * regcache, char * buf)
Definition at line 199 of file regcache.c.
References convert_int_to_ascii(), memset(), target_desc::num_registers, REG_VALID, register_size(), regcache::register_status, regcache::registers, and regcache::tdesc.
Referenced by process_serial_event().
void supply_regblock (struct regcache * regcache, const void * buf)
Definition at line 366 of file regcache.c.
References memcpy(), memset(), target_desc::num_registers, REG_UNAVAILABLE, REG_VALID, regcache::register_status, regcache::registers, target_desc::registers_size, and regcache::tdesc.
Referenced by fetch_traceframe_registers(), and get_context_regcache().
void supply_register (struct regcache * regcache, int n, const void * buf)
Definition at line 326 of file regcache.c.
References memcpy(), memset(), REG_UNAVAILABLE, REG_VALID, register_data(), register_size(), regcache::register_status, and regcache::tdesc.
Referenced by aarch64_store_fpregset(), aarch64_store_gregset(), arm_fetch_inferior_register(), arm_store_gregset(), arm_store_vfpregset(), arm_store_wmmxregset(), cris_store_gregset(), i386_fetch_inferior_register(), i387_fsave_to_cache(), i387_fxsave_to_cache(), i387_xsave_to_cache(), ia64_fetch_register(), lynx_i386_store_fpregset(), lynx_ppc_store_fpregset(), lynx_ppc_store_gregset(), nto_fetch_registers(), ppc_store_evrregset(), ppc_store_vrregset(), ppc_store_vsxregset(), ppc_supply_ptrace_register(), s390_supply_ptrace_register(), sparc_store_fpregset(), sparc_store_gregset(), sparc_store_gregset_from_stack(), spu_fetch_registers(), supply_16bit_register(), supply_fast_tracepoint_registers(), supply_register_by_name(), tic6x_supply_register(), tile_store_gregset(), x86_store_gregset(), and xtensa_store_gregset().
void supply_register_by_name (struct regcache * regcache, const char * name, const void * buf)
Definition at line 401 of file regcache.c.
References find_regno(), supply_register(), and regcache::tdesc.
Referenced by aarch64_set_pc(), arm_set_pc(), arm_store_vfpregset(), bfin_set_pc(), cris_insert_point(), cris_remove_point(), cris_set_pc(), cris_write_data_breakpoint(), i387_fsave_to_cache(), i387_fxsave_to_cache(), i387_xsave_to_cache(), m32r_set_pc(), m68k_set_pc(), mips_set_pc(), nios2_set_pc(), ppc_set_pc(), ppc_store_evrregset(), ppc_store_vrregset(), s390_set_pc(), s390_store_last_break(), s390_store_system_call(), sh_set_pc(), tic6x_set_pc(), tile_set_pc(), x86_set_pc(), x86_store_gregset(), xtensa_set_pc(), xtensa_store_gregset(), and xtensa_store_xtregset().
void supply_register_zeroed (struct regcache * regcache, int n)
Definition at line 351 of file regcache.c.
References memset(), REG_VALID, register_data(), register_size(), regcache::register_status, and regcache::tdesc.
Referenced by i387_xsave_to_cache().