GDBserver: linux_target_ops Struct Reference
linux_target_ops Struct Reference
#include <linux-low.h>
Public Attributes
void(* arch_setup)(void)
struct regs_info *(* regs_info)(void)
int(* cannot_fetch_register)(int)
int(* cannot_store_register)(int)
int(* fetch_register)(struct regcache *regcache, int regno)
CORE_ADDR(* get_pc)(struct regcache *regcache)
void(* set_pc)(struct regcache *regcache, CORE_ADDR newpc)
const unsigned char * breakpoint
int breakpoint_len
CORE_ADDR(* breakpoint_reinsert_addr)(void)
int decr_pc_after_break
int(* breakpoint_at)(CORE_ADDR pc)
int(* insert_point)(char type, CORE_ADDR addr, int len)
int(* remove_point)(char type, CORE_ADDR addr, int len)
int(* stopped_by_watchpoint)(void)
CORE_ADDR(* stopped_data_address)(void)
void(* collect_ptrace_register)(struct regcache *regcache, int regno, char *buf)
void(* supply_ptrace_register)(struct regcache *regcache, int regno, const char *buf)
int(* siginfo_fixup)(siginfo_t *native, void *inf, int direction)
struct arch_process_info *(* new_process)(void)
struct arch_lwp_info *(* new_thread)(void)
void(* prepare_to_resume)(struct lwp_info *)
void(* process_qsupported)(const char *)
int(* supports_tracepoints)(void)
int(* get_thread_area)(int lwpid, CORE_ADDR *addrp)
int(* install_fast_tracepoint_jump_pad)(CORE_ADDR tpoint, CORE_ADDR tpaddr, CORE_ADDR collector, CORE_ADDR lockaddr, ULONGEST orig_size, CORE_ADDR *jump_entry, CORE_ADDR *trampoline, ULONGEST *trampoline_size, unsigned char *jjump_pad_insn, ULONGEST *jjump_pad_insn_size, CORE_ADDR *adjusted_insn_addr, CORE_ADDR *adjusted_insn_addr_end, char *err)
struct emit_ops *(* emit_ops)(void)
int(* get_min_fast_tracepoint_insn_len)(void)
int(* supports_range_stepping)(void)
Detailed Description
Definition at line 125 of file linux-low.h.
Member Data Documentation
void(* linux_target_ops::arch_setup)(void)
Definition at line 128 of file linux-low.h.
Referenced by do_attach(), initialize_low(), linux_wait_for_lwp(), and x86_arch_setup_process_callback().
const unsigned char* linux_target_ops::breakpoint
Definition at line 147 of file linux-low.h.
Referenced by initialize_low().
int(* linux_target_ops::breakpoint_at)(CORE_ADDR pc)
Definition at line 152 of file linux-low.h.
Referenced by cancel_breakpoint(), and linux_wait_1().
int linux_target_ops::breakpoint_len
Definition at line 148 of file linux-low.h.
Referenced by initialize_low().
CORE_ADDR(* linux_target_ops::breakpoint_reinsert_addr)(void)
Definition at line 149 of file linux-low.h.
Referenced by can_hardware_single_step(), and start_step_over().
int(* linux_target_ops::cannot_fetch_register)(int)
Definition at line 131 of file linux-low.h.
int(* linux_target_ops::cannot_store_register)(int)
Definition at line 136 of file linux-low.h.
void(* linux_target_ops::collect_ptrace_register)(struct regcache *regcache, int regno, char *buf)
Definition at line 163 of file linux-low.h.
int linux_target_ops::decr_pc_after_break
Definition at line 151 of file linux-low.h.
Referenced by cancel_breakpoint(), and get_stop_pc().
struct emit_ops*(* linux_target_ops::emit_ops)(void) [read]
Definition at line 214 of file linux-low.h.
Referenced by linux_emit_ops().
int(* linux_target_ops::fetch_register)(struct regcache *regcache, int regno)
Definition at line 143 of file linux-low.h.
Referenced by linux_fetch_registers().
int(* linux_target_ops::get_min_fast_tracepoint_insn_len)(void)
Definition at line 218 of file linux-low.h.
Referenced by linux_get_min_fast_tracepoint_insn_len().
CORE_ADDR(* linux_target_ops::get_pc)(struct regcache *regcache)
Definition at line 145 of file linux-low.h.
Referenced by get_pc(), get_stop_pc(), linux_read_pc(), linux_resume_one_lwp(), linux_wait_for_lwp(), and supports_breakpoints().
int(* linux_target_ops::get_thread_area)(int lwpid, CORE_ADDR *addrp)
Definition at line 195 of file linux-low.h.
Referenced by linux_fast_tracepoint_collecting().
int(* linux_target_ops::insert_point)(char type, CORE_ADDR addr, int len)
Definition at line 156 of file linux-low.h.
Referenced by linux_insert_point(), and win32_insert_point().
int(* linux_target_ops::install_fast_tracepoint_jump_pad)(CORE_ADDR tpoint, CORE_ADDR tpaddr, CORE_ADDR collector, CORE_ADDR lockaddr, ULONGEST orig_size, CORE_ADDR *jump_entry, CORE_ADDR *trampoline, ULONGEST *trampoline_size, unsigned char *jjump_pad_insn, ULONGEST *jjump_pad_insn_size, CORE_ADDR *adjusted_insn_addr, CORE_ADDR *adjusted_insn_addr_end, char *err)
Definition at line 199 of file linux-low.h.
Referenced by linux_install_fast_tracepoint_jump_pad(), and supports_fast_tracepoints().
struct arch_process_info*(* linux_target_ops::new_process)(void) [read]
Definition at line 177 of file linux-low.h.
Referenced by linux_add_process().
struct arch_lwp_info*(* linux_target_ops::new_thread)(void) [read]
Definition at line 182 of file linux-low.h.
Referenced by add_lwp().
void(* linux_target_ops::prepare_to_resume)(struct lwp_info *)
Definition at line 185 of file linux-low.h.
Referenced by linux_detach_one_lwp(), and linux_resume_one_lwp().
void(* linux_target_ops::process_qsupported)(const char *)
Definition at line 188 of file linux-low.h.
Referenced by linux_process_qsupported().
struct regs_info*(* linux_target_ops::regs_info)(void) [read]
Definition at line 130 of file linux-low.h.
Referenced by get_usrregs_info(), linux_fetch_registers(), linux_store_registers(), s390_collect_ptrace_register(), s390_fill_gregset(), and s390_supply_ptrace_register().
int(* linux_target_ops::remove_point)(char type, CORE_ADDR addr, int len)
Definition at line 157 of file linux-low.h.
Referenced by linux_remove_point(), and win32_remove_point().
void(* linux_target_ops::set_pc)(struct regcache *regcache, CORE_ADDR newpc)
Definition at line 146 of file linux-low.h.
Referenced by cancel_breakpoint(), linux_wait_1(), linux_write_pc(), and maybe_move_out_of_jump_pad().
int(* linux_target_ops::siginfo_fixup)(siginfo_t *native, void *inf, int direction)
Definition at line 172 of file linux-low.h.
Referenced by siginfo_fixup().
int(* linux_target_ops::stopped_by_watchpoint)(void)
Definition at line 158 of file linux-low.h.
Referenced by linux_wait_for_lwp(), and win32_stopped_by_watchpoint().
CORE_ADDR(* linux_target_ops::stopped_data_address)(void)
Definition at line 159 of file linux-low.h.
Referenced by linux_wait_for_lwp(), and win32_stopped_data_address().
void(* linux_target_ops::supply_ptrace_register)(struct regcache *regcache, int regno, const char *buf)
Definition at line 165 of file linux-low.h.
int(* linux_target_ops::supports_range_stepping)(void)
Definition at line 221 of file linux-low.h.
Referenced by linux_supports_range_stepping().
int(* linux_target_ops::supports_tracepoints)(void)
Definition at line 191 of file linux-low.h.
Referenced by linux_supports_tracepoints().
The documentation for this struct was generated from the following file:
/home/stan/gdb/src/gdb/gdbserver/linux-low.h