GDBserver: thread_db Struct Reference
thread_db Struct Reference
Public Attributes
struct ps_prochandle proc_handle
td_thragent_t * thread_agent
int all_symbols_looked_up
void * handle
struct breakpoint * td_create_bp
td_err_e(* td_ta_new_p)(struct ps_prochandle *ps, td_thragent_t **ta)
td_err_e(* td_ta_event_getmsg_p)(const td_thragent_t *ta, td_event_msg_t *msg)
td_err_e(* td_ta_set_event_p)(const td_thragent_t *ta, td_thr_events_t *event)
td_err_e(* td_ta_event_addr_p)(const td_thragent_t *ta, td_event_e event, td_notify_t *ptr)
td_err_e(* td_ta_map_lwp2thr_p)(const td_thragent_t *ta, lwpid_t lwpid, td_thrhandle_t *th)
td_err_e(* td_thr_get_info_p)(const td_thrhandle_t *th, td_thrinfo_t *infop)
td_err_e(* td_thr_event_enable_p)(const td_thrhandle_t *th, int event)
td_err_e(* td_ta_thr_iter_p)(const td_thragent_t *ta, td_thr_iter_f *callback, void *cbdata_p, td_thr_state_e state, int ti_pri, sigset_t *ti_sigmask_p, unsigned int ti_user_flags)
td_err_e(* td_thr_tls_get_addr_p)(const td_thrhandle_t *th, psaddr_t map_address, size_t offset, psaddr_t *address)
const char **(* td_symbol_list_p)(void)
Detailed Description
Definition at line 41 of file thread-db.c.
Member Data Documentation
int thread_db::all_symbols_looked_up
Definition at line 53 of file thread-db.c.
Referenced by thread_db_get_tls_address(), thread_db_look_up_one_symbol(), and thread_db_look_up_symbols().
void* thread_db::handle
Definition at line 57 of file thread-db.c.
Referenced by disable_thread_event_reporting(), thread_db_mourn(), and try_thread_db_load_1().
struct ps_prochandle thread_db::proc_handle
Definition at line 45 of file thread-db.c.
Referenced by try_thread_db_load_1().
struct breakpoint* thread_db::td_create_bp
Definition at line 68 of file thread-db.c.
Referenced by remove_thread_event_breakpoints(), and thread_db_enable_reporting().
const char**(* thread_db::td_symbol_list_p)(void)
Definition at line 91 of file thread-db.c.
Referenced by thread_db_look_up_symbols(), and try_thread_db_load_1().
td_err_e(* thread_db::td_ta_event_addr_p)(const td_thragent_t *ta, td_event_e event, td_notify_t *ptr)
Definition at line 76 of file thread-db.c.
Referenced by thread_db_enable_reporting(), and try_thread_db_load_1().
td_err_e(* thread_db::td_ta_event_getmsg_p)(const td_thragent_t *ta, td_event_msg_t *msg)
Definition at line 72 of file thread-db.c.
Referenced by thread_db_create_event(), thread_db_enable_reporting(), and try_thread_db_load_1().
td_err_e(* thread_db::td_ta_map_lwp2thr_p)(const td_thragent_t *ta, lwpid_t lwpid, td_thrhandle_t *th)
Definition at line 78 of file thread-db.c.
Referenced by find_one_thread(), and try_thread_db_load_1().
td_err_e(* thread_db::td_ta_new_p)(struct ps_prochandle *ps, td_thragent_t **ta)
Definition at line 71 of file thread-db.c.
Referenced by try_thread_db_load_1().
td_err_e(* thread_db::td_ta_set_event_p)(const td_thragent_t *ta, td_thr_events_t *event)
Definition at line 74 of file thread-db.c.
Referenced by thread_db_enable_reporting(), and try_thread_db_load_1().
td_err_e(* thread_db::td_ta_thr_iter_p)(const td_thragent_t *ta, td_thr_iter_f *callback, void *cbdata_p, td_thr_state_e state, int ti_pri, sigset_t *ti_sigmask_p, unsigned int ti_user_flags)
Definition at line 83 of file thread-db.c.
Referenced by thread_db_find_new_threads(), and try_thread_db_load_1().
td_err_e(* thread_db::td_thr_event_enable_p)(const td_thrhandle_t *th, int event)
Definition at line 82 of file thread-db.c.
Referenced by attach_thread(), find_one_thread(), and try_thread_db_load_1().
td_err_e(* thread_db::td_thr_get_info_p)(const td_thrhandle_t *th, td_thrinfo_t *infop)
Definition at line 80 of file thread-db.c.
Referenced by find_new_threads_callback(), find_one_thread(), and try_thread_db_load_1().
td_err_e(* thread_db::td_thr_tls_get_addr_p)(const td_thrhandle_t *th, psaddr_t map_address, size_t offset, psaddr_t *address)
Definition at line 88 of file thread-db.c.
Referenced by thread_db_get_tls_address(), and try_thread_db_load_1().
td_thragent_t* thread_db::thread_agent
Definition at line 48 of file thread-db.c.
Referenced by disable_thread_event_reporting(), find_one_thread(), thread_db_create_event(), thread_db_enable_reporting(), thread_db_find_new_threads(), thread_db_mourn(), and try_thread_db_load_1().
The documentation for this struct was generated from the following file:
/home/stan/gdb/src/gdb/gdbserver/thread-db.c