GDBserver: /home/stan/gdb/src/gdb/gdbserver/tdesc.c File Reference
/home/stan/gdb/src/gdb/gdbserver/tdesc.c File Reference
#include "server.h"
#include "tdesc.h"
#include "regdef.h"
Functions
void init_target_desc (struct target_desc *tdesc)
void copy_target_description (struct target_desc *dest, const struct target_desc *src)
struct target_desc * current_target_desc (void)
Variables
static struct target_desc default_description
Function Documentation
void copy_target_description (struct target_desc * dest, const struct target_desc * src)
Definition at line 47 of file tdesc.c.
References target_desc::expedite_regs, target_desc::num_registers, target_desc::reg_defs, target_desc::registers_size, and target_desc::xmltarget.
Referenced by initialize_low_arch().
struct target_desc* current_target_desc (void) [read]
Definition at line 58 of file tdesc.c.
References current_inferior, current_process(), default_description, and process_info::tdesc.
Referenced by get_features_xml(), prepare_resume_reply(), process_serial_event(), traceframe_get_pc(), and traceframe_walk_blocks().
void init_target_desc (struct target_desc * tdesc)
Definition at line 23 of file tdesc.c.
References fatal(), target_desc::num_registers, offset, PBUFSIZ, target_desc::reg_defs, and target_desc::registers_size.
Variable Documentation
struct target_desc default_description [static]
Definition at line 44 of file tdesc.c.
Referenced by current_target_desc().