GDBserver: /home/stan/gdb/src/gdb/gdbserver/win32-arm-low.c File Reference
/home/stan/gdb/src/gdb/gdbserver/win32-arm-low.c File Reference
#include "server.h"
#include "win32-low.h"
Defines
#define CONTEXT_FLOATING_POINT 0
#define context_offset(x) ((int)&(((CONTEXT *)NULL)->x))
#define arm_wince_breakpoint_len 4
Functions
void init_registers_arm (void)
static void arm_get_thread_context (win32_thread_info *th, DEBUG_EVENT *current_event)
static void arm_set_thread_context (win32_thread_info *th, DEBUG_EVENT *current_event)
static char * regptr (CONTEXT *c, int r)
static void arm_fetch_inferior_register (struct regcache *regcache, win32_thread_info *th, int r)
static void arm_store_inferior_register (struct regcache *regcache, win32_thread_info *th, int r)
static void arm_arch_setup (void)
Variables
struct target_desc * tdesc_arm
static const int mappings []
static const unsigned long arm_wince_breakpoint = 0xe6000010
struct win32_target_ops the_low_target
Define Documentation
#define arm_wince_breakpoint_len 4
Definition at line 120 of file win32-arm-low.c.
#define CONTEXT_FLOATING_POINT 0
Definition at line 22 of file win32-arm-low.c.
Referenced by i386_get_thread_context().
#define context_offset (x) ((int)&(((CONTEXT *)NULL)->x))
Definition at line 45 of file win32-arm-low.c.
Referenced by arm_fetch_inferior_register().
Function Documentation
static void arm_arch_setup (void) [static]
Definition at line 112 of file win32-arm-low.c.
References init_registers_arm(), and win32_tdesc.
static void arm_fetch_inferior_register (struct regcache * regcache, win32_thread_info * th, int r) [static]
Definition at line 96 of file win32-arm-low.c.
References win32_thread_info::context, context_offset, regptr(), and supply_register().
static void arm_get_thread_context (win32_thread_info * th, DEBUG_EVENT * current_event) [static]
Definition at line 30 of file win32-arm-low.c.
References win32_thread_info::context, and win32_thread_info::h.
static void arm_set_thread_context (win32_thread_info * th, DEBUG_EVENT * current_event) [static]
Definition at line 40 of file win32-arm-low.c.
References win32_thread_info::context, and win32_thread_info::h.
static void arm_store_inferior_register (struct regcache * regcache, win32_thread_info * th, int r) [static]
Definition at line 105 of file win32-arm-low.c.
References collect_register(), win32_thread_info::context, and regptr().
void init_registers_arm (void)
static char* regptr (CONTEXT * c, int r) [static]
Definition at line 80 of file win32-arm-low.c.
References mappings.
Referenced by arm_fetch_inferior_register(), and arm_store_inferior_register().
Variable Documentation
const unsigned long arm_wince_breakpoint = 0xe6000010 [static]
Definition at line 119 of file win32-arm-low.c.
const int mappings[] [static]
Initial value:
 {
  context_offset (R0),
  context_offset (R1),
  context_offset (R2),
  context_offset (R3),
  context_offset (R4),
  context_offset (R5),
  context_offset (R6),
  context_offset (R7),
  context_offset (R8),
  context_offset (R9),
  context_offset (R10),
  context_offset (R11),
  context_offset (R12),
  context_offset (Sp),
  context_offset (Lr),
  context_offset (Pc),
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  context_offset (Psr),
}
Definition at line 46 of file win32-arm-low.c.
Referenced by regptr().
struct target_desc* tdesc_arm
struct win32_target_ops the_low_target
Initial value:
 {
  arm_arch_setup,
  sizeof (mappings) / sizeof (mappings[0]),
  NULL,
  arm_get_thread_context,
  arm_set_thread_context,
  NULL,
  arm_fetch_inferior_register,
  arm_store_inferior_register,
  NULL,
  (const unsigned char *) &arm_wince_breakpoint,
  arm_wince_breakpoint_len,
  NULL,
  NULL,
  NULL,
  NULL
}
Definition at line 122 of file win32-arm-low.c.