GDBserver: /home/stan/gdb/src/gdb/gdbserver/win32-i386-low.c File Reference
/home/stan/gdb/src/gdb/gdbserver/win32-i386-low.c File Reference
#include "server.h"
#include "win32-low.h"
#include "i386-low.h"
Defines
#define CONTEXT_EXTENDED_REGISTERS 0
#define FCS_REGNUM 27
#define FOP_REGNUM 31
#define FLAG_TRACE_BIT 0x100
#define context_offset(x) ((int)&(((CONTEXT *)NULL)->x))
#define i386_win32_breakpoint_len 1
Functions
void init_registers_i386 (void)
void i386_dr_low_set_addr (const struct i386_debug_reg_state *state, int regnum)
CORE_ADDR i386_dr_low_get_addr (int regnum)
void i386_dr_low_set_control (const struct i386_debug_reg_state *state)
unsigned i386_dr_low_get_control (void)
unsigned i386_dr_low_get_status (void)
static int i386_insert_point (char type, CORE_ADDR addr, int len)
static int i386_remove_point (char type, CORE_ADDR addr, int len)
static int i386_stopped_by_watchpoint (void)
static CORE_ADDR i386_stopped_data_address (void)
static void i386_initial_stuff (void)
static void i386_get_thread_context (win32_thread_info *th, DEBUG_EVENT *current_event)
static void i386_set_thread_context (win32_thread_info *th, DEBUG_EVENT *current_event)
static void i386_thread_added (win32_thread_info *th)
static void i386_single_step (win32_thread_info *th)
static void i386_fetch_inferior_register (struct regcache *regcache, win32_thread_info *th, int r)
static void i386_store_inferior_register (struct regcache *regcache, win32_thread_info *th, int r)
static void i386_arch_setup (void)
Variables
struct target_desc * tdesc_i386
static struct i386_debug_reg_state debug_reg_state
static int debug_registers_changed = 0
static int debug_registers_used = 0
static const int mappings []
static const unsigned char i386_win32_breakpoint = 0xcc
struct win32_target_ops the_low_target
Define Documentation
#define CONTEXT_EXTENDED_REGISTERS 0
Definition at line 23 of file win32-i386-low.c.
Referenced by i386_get_thread_context().
#define context_offset (x) ((int)&(((CONTEXT *)NULL)->x))
Definition at line 252 of file win32-i386-low.c.
Referenced by i386_fetch_inferior_register(), and i386_store_inferior_register().
#define FCS_REGNUM 27
Definition at line 26 of file win32-i386-low.c.
Referenced by i386_fetch_inferior_register().
#define FLAG_TRACE_BIT 0x100
Definition at line 29 of file win32-i386-low.c.
Referenced by i386_single_step().
#define FOP_REGNUM 31
Definition at line 27 of file win32-i386-low.c.
Referenced by i386_fetch_inferior_register().
#define i386_win32_breakpoint_len 1
Definition at line 401 of file win32-i386-low.c.
Function Documentation
static void i386_arch_setup (void) [static]
Definition at line 404 of file win32-i386-low.c.
References init_registers_i386(), and win32_tdesc.
CORE_ADDR i386_dr_low_get_addr (int regnum)
Definition at line 62 of file win32-i386-low.c.
References debug_reg_state, DR_FIRSTADDR, DR_LASTADDR, i386_debug_reg_state::dr_mirror, and gdb_assert.
Referenced by i386_low_stopped_data_address().
unsigned i386_dr_low_get_control (void)
Definition at line 82 of file win32-i386-low.c.
References debug_reg_state, and i386_debug_reg_state::dr_control_mirror.
Referenced by i386_low_stopped_data_address().
unsigned i386_dr_low_get_status (void)
Definition at line 91 of file win32-i386-low.c.
References debug_reg_state, and i386_debug_reg_state::dr_status_mirror.
Referenced by i386_low_stopped_data_address().
void i386_dr_low_set_addr (const struct i386_debug_reg_state * state, int regnum)
Definition at line 49 of file win32-i386-low.c.
References debug_registers_changed, debug_registers_used, DR_FIRSTADDR, DR_LASTADDR, and fatal().
Referenced by i386_update_inferior_debug_regs().
void i386_dr_low_set_control (const struct i386_debug_reg_state * state)
Definition at line 72 of file win32-i386-low.c.
References debug_registers_changed, and debug_registers_used.
Referenced by i386_update_inferior_debug_regs().
static void i386_fetch_inferior_register (struct regcache * regcache, win32_thread_info * th, int r) [static]
Definition at line 371 of file win32-i386-low.c.
References win32_thread_info::context, context_offset, FCS_REGNUM, FOP_REGNUM, mappings, and supply_register().
static void i386_get_thread_context (win32_thread_info * th, DEBUG_EVENT * current_event) [static]
Definition at line 156 of file win32-i386-low.c.
References win32_thread_info::context, CONTEXT_EXTENDED_REGISTERS, CONTEXT_FLOATING_POINT, debug_reg_state, debug_registers_changed, i386_debug_reg_state::dr_control_mirror, i386_debug_reg_state::dr_mirror, i386_debug_reg_state::dr_status_mirror, error(), win32_thread_info::h, and win32_thread_info::tid.
static void i386_initial_stuff (void) [static]
Definition at line 148 of file win32-i386-low.c.
References debug_reg_state, debug_registers_changed, debug_registers_used, and i386_low_init_dregs().
static int i386_insert_point (char type, CORE_ADDR addr, int len) [static]
Definition at line 101 of file win32-i386-low.c.
References debug_reg_state, and i386_low_insert_watchpoint().
static int i386_remove_point (char type, CORE_ADDR addr, int len) [static]
Definition at line 117 of file win32-i386-low.c.
References debug_reg_state, and i386_low_remove_watchpoint().
static void i386_set_thread_context (win32_thread_info * th, DEBUG_EVENT * current_event) [static]
Definition at line 197 of file win32-i386-low.c.
References win32_thread_info::context, debug_reg_state, debug_registers_changed, i386_debug_reg_state::dr_control_mirror, i386_debug_reg_state::dr_mirror, and win32_thread_info::h.
static void i386_single_step (win32_thread_info * th) [static]
Definition at line 238 of file win32-i386-low.c.
References win32_thread_info::context, and FLAG_TRACE_BIT.
static int i386_stopped_by_watchpoint (void) [static]
Definition at line 133 of file win32-i386-low.c.
References debug_reg_state, and i386_low_stopped_by_watchpoint().
static CORE_ADDR i386_stopped_data_address (void) [static]
Definition at line 139 of file win32-i386-low.c.
References debug_reg_state, and i386_low_stopped_data_address().
static void i386_store_inferior_register (struct regcache * regcache, win32_thread_info * th, int r) [static]
Definition at line 393 of file win32-i386-low.c.
References collect_register(), win32_thread_info::context, context_offset, and mappings.
static void i386_thread_added (win32_thread_info * th) [static]
Definition at line 215 of file win32-i386-low.c.
References win32_thread_info::context, debug_reg_state, debug_registers_used, i386_debug_reg_state::dr_control_mirror, i386_debug_reg_state::dr_mirror, and win32_thread_info::h.
void init_registers_i386 (void)
Variable Documentation
struct i386_debug_reg_state debug_reg_state [static]
Definition at line 41 of file win32-i386-low.c.
Referenced by i386_dr_low_get_addr(), i386_dr_low_get_control(), i386_dr_low_get_status(), i386_get_thread_context(), i386_initial_stuff(), i386_insert_point(), i386_remove_point(), i386_set_thread_context(), i386_stopped_by_watchpoint(), i386_stopped_data_address(), and i386_thread_added().
int debug_registers_changed = 0 [static]
Definition at line 43 of file win32-i386-low.c.
Referenced by i386_dr_low_set_addr(), i386_dr_low_set_control(), i386_get_thread_context(), i386_initial_stuff(), and i386_set_thread_context().
int debug_registers_used = 0 [static]
Definition at line 44 of file win32-i386-low.c.
Referenced by i386_dr_low_set_addr(), i386_dr_low_set_control(), i386_initial_stuff(), and i386_thread_added().
const unsigned char i386_win32_breakpoint = 0xcc [static]
Definition at line 400 of file win32-i386-low.c.
const int mappings[] [static]
Definition at line 253 of file win32-i386-low.c.
Referenced by i386_fetch_inferior_register(), and i386_store_inferior_register().
struct target_desc* tdesc_i386
struct win32_target_ops the_low_target
Initial value:
 {
  i386_arch_setup,
  sizeof (mappings) / sizeof (mappings[0]),
  i386_initial_stuff,
  i386_get_thread_context,
  i386_set_thread_context,
  i386_thread_added,
  i386_fetch_inferior_register,
  i386_store_inferior_register,
  i386_single_step,
  &i386_win32_breakpoint,
  i386_win32_breakpoint_len,
  i386_insert_point,
  i386_remove_point,
  i386_stopped_by_watchpoint,
  i386_stopped_data_address
}
Definition at line 415 of file win32-i386-low.c.