GDBserver: /home/stan/gdb/src/gdb/gdbserver/win32-low.c File Reference
/home/stan/gdb/src/gdb/gdbserver/win32-low.c File Reference
#include "server.h"
#include "regcache.h"
#include "gdb/signals.h"
#include "gdb/fileio.h"
#include "mem-break.h"
#include "win32-low.h"
#include "gdbthread.h"
#include "dll.h"
#include "hostio.h"
#include <stdint.h>
#include <windows.h>
#include <winnt.h>
#include <imagehlp.h>
#include <tlhelp32.h>
#include <psapi.h>
#include <process.h>
#include <sys/cygwin.h>
Defines
#define OUTMSG(X) do { printf X; fflush (stderr); } while (0)
#define OUTMSG2(X)
#define _T(x) TEXT (x)
#define COUNTOF(STR) (sizeof (STR) / sizeof ((STR)[0]))
#define GETPROCADDRESS(DLL, PROC) ((winapi_ ## PROC) GetProcAddress (DLL, #PROC))
#define NUM_REGS (the_low_target.num_regs)
#define READ_BUFFER_LEN 1024
Typedefs
typedef HMODULE DWORD
typedef HMODULE LPDWORD
Functions
typedef BOOL (WINAPI *winapi_DebugActiveProcessStop)(DWORD dwProcessId)
static void win32_resume (struct thread_resume *resume_info, size_t n)
static ptid_t current_inferior_ptid (void)
static ptid_t debug_event_ptid (DEBUG_EVENT *event)
static void win32_get_thread_context (win32_thread_info *th)
static void win32_set_thread_context (win32_thread_info *th)
static win32_thread_info * thread_rec (ptid_t ptid, int get_context)
static win32_thread_info * child_add_thread (DWORD pid, DWORD tid, HANDLE h, void *tlb)
static void delete_thread_info (struct inferior_list_entry *thread)
static void child_delete_thread (DWORD pid, DWORD tid)
static int win32_insert_point (char type, CORE_ADDR addr, int len)
static int win32_remove_point (char type, CORE_ADDR addr, int len)
static int win32_stopped_by_watchpoint (void)
static CORE_ADDR win32_stopped_data_address (void)
static int child_xfer_memory (CORE_ADDR memaddr, char *our, int len, int write, struct target_ops *target)
static void child_init_thread_list (void)
static void do_initial_child_stuff (HANDLE proch, DWORD pid, int attached)
static int continue_one_thread (struct inferior_list_entry *this_thread, void *id_ptr)
static BOOL child_continue (DWORD continue_status, int thread_id)
static void child_fetch_inferior_registers (struct regcache *regcache, int r)
static void child_store_inferior_registers (struct regcache *regcache, int r)
char * strwinerror (DWORD error)
static BOOL create_process (const char *program, char *args, DWORD flags, PROCESS_INFORMATION *pi)
static int win32_create_inferior (char *program, char **program_args)
static int win32_attach (unsigned long pid)
static void handle_output_debug_string (struct target_waitstatus *ourstatus)
static void win32_clear_inferiors (void)
static int win32_kill (int pid)
static int win32_detach (int pid)
static void win32_mourn (struct process_info *process)
static void win32_join (int pid)
static int win32_thread_alive (ptid_t ptid)
static void win32_add_one_solib (const char *name, CORE_ADDR load_addr)
static char * get_image_name (HANDLE h, void *address, int unicode)
typedef DWORD (WINAPI *winapi_GetModuleFileNameExA)(HANDLE
static BOOL load_psapi (void)
static int psapi_get_dll_name (LPVOID BaseAddress, char *dll_name_ret)
typedef HANDLE (WINAPI *winapi_CreateToolhelp32Snapshot)(DWORD
static BOOL load_toolhelp (void)
static int toolhelp_get_dll_name (LPVOID BaseAddress, char *dll_name_ret)
static void handle_load_dll (void)
static void handle_unload_dll (void)
static void handle_exception (struct target_waitstatus *ourstatus)
static void suspend_one_thread (struct inferior_list_entry *entry)
static void fake_breakpoint_event (void)
static int get_child_debug_event (struct target_waitstatus *ourstatus)
static ptid_t win32_wait (ptid_t ptid, struct target_waitstatus *ourstatus, int options)
static void win32_fetch_inferior_registers (struct regcache *regcache, int regno)
static void win32_store_inferior_registers (struct regcache *regcache, int regno)
static int win32_read_inferior_memory (CORE_ADDR memaddr, unsigned char *myaddr, int len)
static int win32_write_inferior_memory (CORE_ADDR memaddr, const unsigned char *myaddr, int len)
static void win32_request_interrupt (void)
static int win32_get_tib_address (ptid_t ptid, CORE_ADDR *addr)
void initialize_low (void)
Variables
int using_threads = 1
static int attaching = 0
static HANDLE current_process_handle = NULL
static DWORD current_process_id = 0
static DWORD main_thread_id = 0
static enum gdb_signal last_sig = GDB_SIGNAL_0
static DEBUG_EVENT current_event
static int soft_interrupt_requested = 0
static int faked_breakpoint = 0
struct target_desc * win32_tdesc
typedef HMODULE
typedef LPMODULEINFO
typedef LPSTR
static winapi_EnumProcessModules win32_EnumProcessModules
static winapi_GetModuleInformation win32_GetModuleInformation
static winapi_GetModuleFileNameExA win32_GetModuleFileNameExA
typedef LPMODULEENTRY32
static
winapi_CreateToolhelp32Snapshot win32_CreateToolhelp32Snapshot
static winapi_Module32First win32_Module32First
static winapi_Module32Next win32_Module32Next
static struct target_ops win32_target_ops
Define Documentation
#define _T (x) TEXT (x)
Definition at line 56 of file win32-low.c.
Referenced by load_toolhelp(), win32_attach(), win32_detach(), and win32_request_interrupt().
#define COUNTOF (STR) (sizeof (STR) / sizeof ((STR)[0]))
Definition at line 60 of file win32-low.c.
Referenced by strwinerror().
#define GETPROCADDRESS (DLL, PROC) ((winapi_ ## PROC) GetProcAddress (DLL, #PROC))
Definition at line 67 of file win32-low.c.
Referenced by load_psapi(), load_toolhelp(), win32_attach(), win32_detach(), and win32_request_interrupt().
#define NUM_REGS (the_low_target.num_regs)
Definition at line 93 of file win32-low.c.
Referenced by child_fetch_inferior_registers(), and child_store_inferior_registers().
#define OUTMSG (X) do { printf X; fflush (stderr); } while (0)
Definition at line 43 of file win32-low.c.
Referenced by continue_one_thread(), suspend_one_thread(), thread_rec(), win32_resume(), and win32_wait().
#define OUTMSG2 (X)
Value:
do                                              \
    {                                           \
      if (debug_threads)                        \
        {                                       \
          printf X;                             \
          fflush (stderr);                      \
        }                                       \
    } while (0)
Definition at line 45 of file win32-low.c.
Referenced by fake_breakpoint_event(), get_child_debug_event(), handle_exception(), handle_output_debug_string(), win32_create_inferior(), and win32_wait().
#define READ_BUFFER_LEN 1024
Referenced by handle_output_debug_string().
Typedef Documentation
typedef DWORD
Definition at line 999 of file win32-low.c.
typedef HMODULE LPDWORD
Definition at line 999 of file win32-low.c.
Function Documentation
typedef BOOL (WINAPI * winapi_DebugActiveProcessStop)
Referenced by child_xfer_memory(), create_process(), psapi_get_dll_name(), and win32_create_inferior().
static win32_thread_info* child_add_thread (DWORD pid, DWORD tid, HANDLE h, void * tlb) [static]
Definition at line 185 of file win32-low.c.
References add_thread(), win32_thread_info::h, ptid_build(), the_low_target, win32_thread_info::thread_local_base, thread_rec(), win32_thread_info::tid, and xcalloc().
Referenced by get_child_debug_event().
static BOOL child_continue (DWORD continue_status, int thread_id) [static]
Definition at line 372 of file win32-low.c.
References all_threads, continue_one_thread(), current_event, faked_breakpoint, and find_inferior().
Referenced by get_child_debug_event(), win32_kill(), win32_resume(), and win32_wait().
static void child_delete_thread (DWORD pid, DWORD tid) [static]
Definition at line 219 of file win32-low.c.
References all_threads, delete_thread_info(), find_inferior_id(), inferior_list::head, ptid_build(), and inferior_list::tail.
Referenced by get_child_debug_event().
static void child_fetch_inferior_registers (struct regcache * regcache, int r) [static]
Definition at line 389 of file win32-low.c.
References current_inferior_ptid(), NUM_REGS, the_low_target, and thread_rec().
Referenced by win32_fetch_inferior_registers(), and win32_wait().
static void child_init_thread_list (void) [static]
Definition at line 312 of file win32-low.c.
References all_threads, delete_thread_info(), and for_each_inferior().
Referenced by do_initial_child_stuff().
static void child_store_inferior_registers (struct regcache * regcache, int r) [static]
Definition at line 403 of file win32-low.c.
References current_inferior_ptid(), NUM_REGS, the_low_target, and thread_rec().
Referenced by win32_store_inferior_registers().
static int child_xfer_memory (CORE_ADDR memaddr, char * our, int len, int write, struct target_ops * target) [static]
Definition at line 280 of file win32-low.c.
References BOOL(), and current_process_handle.
Referenced by win32_read_inferior_memory(), and win32_write_inferior_memory().
static int continue_one_thread (struct inferior_list_entry * this_thread, void * id_ptr) [static]
Definition at line 344 of file win32-low.c.
References win32_thread_info::context, win32_thread_info::h, inferior_target_data(), OUTMSG, strwinerror(), win32_thread_info::suspended, win32_thread_info::tid, and win32_set_thread_context().
Referenced by child_continue().
static BOOL create_process (const char * program, char * args, DWORD flags, PROCESS_INFORMATION * pi) [static]
Definition at line 470 of file win32-low.c.
References BOOL().
Referenced by win32_create_inferior().
static ptid_t current_inferior_ptid (void) [static]
Definition at line 105 of file win32-low.c.
References current_inferior.
Referenced by child_fetch_inferior_registers(), and child_store_inferior_registers().
static ptid_t debug_event_ptid (DEBUG_EVENT * event) [static]
Definition at line 112 of file win32-low.c.
References ptid_build().
Referenced by get_child_debug_event(), win32_resume(), and win32_wait().
static void delete_thread_info (struct inferior_list_entry * thread) [static]
Definition at line 208 of file win32-low.c.
References win32_thread_info::h, inferior_target_data(), and remove_thread().
Referenced by child_delete_thread(), child_init_thread_list(), and win32_clear_inferiors().
static void do_initial_child_stuff (HANDLE proch, DWORD pid, int attached) [static]
Definition at line 318 of file win32-low.c.
References add_process(), child_init_thread_list(), current_event, current_process_handle, current_process_id, faked_breakpoint, last_sig, main_thread_id, memset(), soft_interrupt_requested, process_info::tdesc, the_low_target, and win32_tdesc.
Referenced by win32_attach(), and win32_create_inferior().
typedef DWORD (WINAPI * winapi_GetModuleFileNameExA)
static void fake_breakpoint_event (void) [static]
Definition at line 1363 of file win32-low.c.
References all_threads, current_event, faked_breakpoint, for_each_inferior(), main_thread_id, memset(), OUTMSG2, and suspend_one_thread().
Referenced by get_child_debug_event().
static int get_child_debug_event (struct target_waitstatus * ourstatus) [static]
Definition at line 1389 of file win32-low.c.
References all_threads, attaching, check_remote_input_interrupt_request(), child_add_thread(), child_continue(), child_delete_thread(), current_event, current_inferior, current_process_handle, debug_event_ptid(), fake_breakpoint_event(), find_inferior_id(), handle_exception(), handle_load_dll(), handle_output_debug_string(), handle_unload_dll(), inferior_list::head, last_sig, main_thread_id, OUTMSG2, set_breakpoint_at(), and soft_interrupt_requested.
Referenced by win32_wait().
static char* get_image_name (HANDLE h, void * address, int unicode) [static]
Definition at line 951 of file win32-low.c.
Referenced by handle_load_dll().
typedef HANDLE (WINAPI * winapi_CreateToolhelp32Snapshot)
Referenced by win32_add_one_solib(), win32_attach(), and win32_join().
static void handle_exception (struct target_waitstatus * ourstatus) [static]
Definition at line 1236 of file win32-low.c.
References check_breakpoints(), current_event, last_sig, OUTMSG2, and phex_nz().
Referenced by get_child_debug_event().
static void handle_load_dll (void) [static]
Definition at line 1188 of file win32-low.c.
References current_event, current_process_handle, get_image_name(), psapi_get_dll_name(), server_waiting, toolhelp_get_dll_name(), and win32_add_one_solib().
Referenced by get_child_debug_event().
static void handle_output_debug_string (struct target_waitstatus * ourstatus) [static]
Definition at line 658 of file win32-low.c.
References current_event, monitor_output(), OUTMSG2, READ_BUFFER_LEN, read_inferior_memory(), and server_waiting.
Referenced by get_child_debug_event(), and win32_kill().
static void handle_unload_dll (void) [static]
Definition at line 1227 of file win32-low.c.
References current_event, and unloaded_dll().
Referenced by get_child_debug_event().
void initialize_low (void)
Definition at line 1836 of file win32-low.c.
References linux_target_ops::arch_setup, linux_target_ops::breakpoint, linux_target_ops::breakpoint_len, initialize_low_arch(), linux_init_signals(), linux_ptrace_init_warnings(), memset(), set_breakpoint_data(), set_target_ops(), sigchld_handler(), and the_low_target.
static BOOL load_psapi (void) [static]
Definition at line 1011 of file win32-low.c.
References GETPROCADDRESS.
Referenced by psapi_get_dll_name().
static BOOL load_toolhelp (void) [static]
Definition at line 1115 of file win32-low.c.
References _T, and GETPROCADDRESS.
Referenced by toolhelp_get_dll_name().
static int psapi_get_dll_name (LPVOID BaseAddress, char * dll_name_ret) [static]
Definition at line 1036 of file win32-low.c.
References BOOL(), current_process_handle, error(), HMODULE, load_psapi(), and strwinerror().
Referenced by handle_load_dll().
char* strwinerror (DWORD error)
Definition at line 425 of file win32-low.c.
References COUNTOF.
Referenced by continue_one_thread(), perror(), psapi_get_dll_name(), suspend_one_thread(), thread_rec(), win32_attach(), and win32_create_inferior().
static void suspend_one_thread (struct inferior_list_entry * entry) [static]
Definition at line 1344 of file win32-low.c.
References win32_thread_info::h, inferior_target_data(), OUTMSG, strwinerror(), and win32_thread_info::suspended.
Referenced by fake_breakpoint_event().
static win32_thread_info* thread_rec (ptid_t ptid, int get_context) [static]
Definition at line 153 of file win32-low.c.
References all_threads, win32_thread_info::context, find_inferior_id(), win32_thread_info::h, inferior_target_data(), OUTMSG, strwinerror(), win32_thread_info::suspended, and win32_get_thread_context().
Referenced by child_add_thread(), child_fetch_inferior_registers(), child_store_inferior_registers(), win32_get_tib_address(), and win32_resume().
static int toolhelp_get_dll_name (LPVOID BaseAddress, char * dll_name_ret) [static]
Definition at line 1151 of file win32-low.c.
References current_event, load_toolhelp(), and win32_CreateToolhelp32Snapshot.
Referenced by handle_load_dll().
static void win32_add_one_solib (const char * name, CORE_ADDR load_addr) [static]
Definition at line 895 of file win32-low.c.
References HANDLE(), loaded_dll(), and strrchr().
Referenced by handle_load_dll().
static int win32_attach (unsigned long pid) [static]
Definition at line 622 of file win32-low.c.
References _T, attaching, do_initial_child_stuff(), error(), GETPROCADDRESS, HANDLE(), HMODULE, and strwinerror().
static void win32_clear_inferiors (void) [static]
Definition at line 702 of file win32-low.c.
References all_threads, clear_inferiors(), current_process_handle, delete_thread_info(), and for_each_inferior().
Referenced by win32_detach(), win32_kill(), and win32_wait().
static int win32_create_inferior (char * program, char ** program_args) [static]
Definition at line 525 of file win32-low.c.
References attaching, BOOL(), create_process(), current_process_id, do_initial_child_stuff(), error(), OUTMSG2, and strwinerror().
static int win32_detach (int pid) [static]
Definition at line 745 of file win32-low.c.
References _T, current_process_id, find_process_pid(), GETPROCADDRESS, HMODULE, thread_resume::kind, minus_one_ptid, remove_process(), thread_resume::sig, thread_resume::thread, win32_clear_inferiors(), and win32_resume().
static void win32_fetch_inferior_registers (struct regcache * regcache, int regno) [static]
Definition at line 1646 of file win32-low.c.
References child_fetch_inferior_registers().
static void win32_get_thread_context (win32_thread_info * th) [static]
Definition at line 120 of file win32-low.c.
References win32_thread_info::context, current_event, memcpy(), memset(), and the_low_target.
Referenced by thread_rec().
static int win32_get_tib_address (ptid_t ptid, CORE_ADDR * addr) [static]
Definition at line 1775 of file win32-low.c.
References win32_thread_info::thread_local_base, and thread_rec().
static int win32_insert_point (char type, CORE_ADDR addr, int len) [static]
Definition at line 240 of file win32-low.c.
References linux_target_ops::insert_point, and the_low_target.
static void win32_join (int pid) [static]
Definition at line 789 of file win32-low.c.
References HANDLE().
static int win32_kill (int pid) [static]
Definition at line 713 of file win32-low.c.
References child_continue(), current_event, current_process_handle, find_process_pid(), handle_output_debug_string(), remove_process(), and win32_clear_inferiors().
static void win32_mourn (struct process_info * process) [static]
Definition at line 782 of file win32-low.c.
References remove_process().
static int win32_read_inferior_memory (CORE_ADDR memaddr, unsigned char * myaddr, int len) [static]
Definition at line 1663 of file win32-low.c.
References child_xfer_memory().
static int win32_remove_point (char type, CORE_ADDR addr, int len) [static]
Definition at line 250 of file win32-low.c.
References linux_target_ops::remove_point, and the_low_target.
static void win32_request_interrupt (void) [static]
Definition at line 1681 of file win32-low.c.
References _T, current_process_handle, current_process_id, GETPROCADDRESS, and soft_interrupt_requested.
static void win32_resume (struct thread_resume * resume_info, size_t n) [static]
Definition at line 817 of file win32-low.c.
References child_continue(), win32_thread_info::context, current_event, debug_event_ptid(), error(), thread_resume::kind, last_sig, minus_one_ptid, OUTMSG, ptid_equal(), regcache_invalidate(), thread_resume::sig, the_low_target, thread_resume::thread, thread_rec(), and win32_set_thread_context().
Referenced by win32_detach().
static void win32_set_thread_context (win32_thread_info * th) [static]
Definition at line 132 of file win32-low.c.
References win32_thread_info::context, current_event, memcmp(), and the_low_target.
Referenced by continue_one_thread(), and win32_resume().
static int win32_stopped_by_watchpoint (void) [static]
Definition at line 260 of file win32-low.c.
References linux_target_ops::stopped_by_watchpoint, and the_low_target.
static CORE_ADDR win32_stopped_data_address (void) [static]
Definition at line 269 of file win32-low.c.
References linux_target_ops::stopped_data_address, and the_low_target.
static void win32_store_inferior_registers (struct regcache * regcache, int regno) [static]
Definition at line 1654 of file win32-low.c.
References child_store_inferior_registers().
static int win32_thread_alive (ptid_t ptid) [static]
Definition at line 801 of file win32-low.c.
References all_threads, and find_inferior_id().
static ptid_t win32_wait (ptid_t ptid, struct target_waitstatus * ourstatus, int options) [static]
Definition at line 1592 of file win32-low.c.
References child_continue(), child_fetch_inferior_registers(), current_event, current_inferior, debug_event_ptid(), get_child_debug_event(), get_thread_regcache(), OUTMSG, OUTMSG2, pid_to_ptid(), server_waiting, and win32_clear_inferiors().
static int win32_write_inferior_memory (CORE_ADDR memaddr, const unsigned char * myaddr, int len) [static]
Definition at line 1673 of file win32-low.c.
References child_xfer_memory().
Variable Documentation
int attaching = 0 [static]
Definition at line 74 of file win32-low.c.
Referenced by get_child_debug_event(), win32_attach(), and win32_create_inferior().
DEBUG_EVENT current_event [static]
Definition at line 81 of file win32-low.c.
Referenced by child_continue(), do_initial_child_stuff(), fake_breakpoint_event(), get_child_debug_event(), handle_exception(), handle_load_dll(), handle_output_debug_string(), handle_unload_dll(), toolhelp_get_dll_name(), win32_get_thread_context(), win32_kill(), win32_resume(), win32_set_thread_context(), and win32_wait().
HANDLE current_process_handle = NULL [static]
Definition at line 75 of file win32-low.c.
Referenced by child_xfer_memory(), do_initial_child_stuff(), get_child_debug_event(), handle_load_dll(), psapi_get_dll_name(), win32_clear_inferiors(), win32_kill(), and win32_request_interrupt().
DWORD current_process_id = 0 [static]
Definition at line 76 of file win32-low.c.
Referenced by do_initial_child_stuff(), win32_create_inferior(), win32_detach(), and win32_request_interrupt().
int faked_breakpoint = 0 [static]
Definition at line 89 of file win32-low.c.
Referenced by child_continue(), do_initial_child_stuff(), and fake_breakpoint_event().
typedef HMODULE
Definition at line 1001 of file win32-low.c.
Referenced by psapi_get_dll_name(), win32_attach(), and win32_detach().
enum gdb_signal last_sig = GDB_SIGNAL_0 [static]
Definition at line 78 of file win32-low.c.
Referenced by do_initial_child_stuff(), get_child_debug_event(), handle_exception(), and win32_resume().
typedef LPMODULEENTRY32
Definition at line 1103 of file win32-low.c.
typedef LPMODULEINFO
Definition at line 1001 of file win32-low.c.
typedef LPSTR
Definition at line 1003 of file win32-low.c.
DWORD main_thread_id = 0 [static]
Definition at line 77 of file win32-low.c.
Referenced by do_initial_child_stuff(), fake_breakpoint_event(), and get_child_debug_event().
int soft_interrupt_requested = 0 [static]
Definition at line 85 of file win32-low.c.
Referenced by do_initial_child_stuff(), get_child_debug_event(), and win32_request_interrupt().
int using_threads = 1
Definition at line 71 of file win32-low.c.
winapi_CreateToolhelp32Snapshot win32_CreateToolhelp32Snapshot [static]
Definition at line 1106 of file win32-low.c.
Referenced by toolhelp_get_dll_name().
winapi_EnumProcessModules win32_EnumProcessModules [static]
Definition at line 1006 of file win32-low.c.
winapi_GetModuleFileNameExA win32_GetModuleFileNameExA [static]
Definition at line 1008 of file win32-low.c.
winapi_GetModuleInformation win32_GetModuleInformation [static]
Definition at line 1007 of file win32-low.c.
winapi_Module32First win32_Module32First [static]
Definition at line 1107 of file win32-low.c.
winapi_Module32Next win32_Module32Next [static]
Definition at line 1108 of file win32-low.c.
struct target_ops win32_target_ops [static]
Definition at line 1786 of file win32-low.c.
struct target_desc* win32_tdesc
Definition at line 91 of file win32-low.c.
Referenced by arm_arch_setup(), do_initial_child_stuff(), and i386_arch_setup().